### ISSUE TITLE
Remove "No match" entry in editor's code completion widget

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#10002]
When there's no match in the code completion widget we're showing a "No match" entry that makes no sense to me:

![Selección_018](https://user-images.githubusercontent.com/365293/62838973-92bb5900-bc83-11e9-9814-48bae0bdd3a2.png)

@steff456, please take care of removing it.

**Comment by steff456** [comment]
@ccordoba12, @andfoy already made this fix in the code snippets PR #9850

**Comment by ccordoba12** [comment]
Yeah, I noticed it, but I don't know when that PR is going to be merged. Could you take that fix and create a new PR with it? Thanks!
