### ISSUE TITLE
Ipython kernel will not start in Spyder, importing wrong io module

### ISSUE THREAD

**Issue by ericspod** [spyder-ide/spyder#10019]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Whenever an ipython console opens the kernel fails to start with the following complaint:

```
An error ocurred while starting the kernel
Fatal Python error: init_sys_streams: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007f51f0009700 (most recent call first):
```

This is with a fresh install of the latest Miniconda on Ubuntu 16.04. If a fresh environment is created with nothing else installed except Spyder the issue persists. Starting `ipython` or `jupyter qtconsole` on a terminal does not produce this error.

### What steps reproduce the problem?

1. Install latest Miniconda
2. Install Spyder
3. Start Spyder

### What is the expected output? What do you see instead?

Expected to see a ipython console, get this error instead.

## Versions

* Spyder version: 3.36
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 16.04

### Dependencies

```
IPython >=4.0     :  7.7.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
> AttributeError: module 'io' has no attribute 'OpenWrapper'

This means you have a file called `io.py` in your home or in your current working directory. Please find it and delete or rename it.

**Comment by ericspod** [comment]
That doesn't appear to be the case as far as I can tell. There are io.py files found in various locations, including the miniconda install, but none of these are in the current or home directory now otherwise seemingly accessible to Spyder.

**Comment by ccordoba12** [comment]
You can also see if you have PYTHONPATH set that could be interfering with your imports.

Those are the only explanation we know for this, sorry.

**Comment by ericspod** [comment]
What I finally discovered through a process of deleting everything possibly Python related in my home directory is that deleting `~/.config/spyder-py3/path` fixed the problem. This file contained directories that still existed so it doesn't seem to be related to deleting things. The directories also didn't contain any files called `io.py` nor was that file found anywhere else relevant or in any variables. The file name issue seems to be totally unrelated to the issue I encountered.

**Comment by ccordoba12** [comment]
> What I finally discovered through a process of deleting everything possibly Python related in my home directory is that deleting ~/.config/spyder-py3/path fixed the problem

That file saves user modifications to PYTHONPATH through our interface, so I guess you used our PYTHONPATH manager to add the site-packages of another Python interpreter, which is terribly wrong, but it corresponds to my second possible cause mentioned above:

> > You can also see if you have PYTHONPATH set that could be interfering with your imports.

**Comment by ericspod** [comment]
The file contained directories for packages outside any Python interpreter library, and certainly not site-packges, and also didn't contain a io.py file anywhere. What it did contain was an absolute path to a directory followed by that directory's parent so perhaps that caused an issue for search code somewhere. Regardless the error message still bore no relation to the actual problem.

**Comment by ccordoba12** [comment]
Sure, but that was generated by one of our dependencies, not by Spyder itself.
