### ISSUE TITLE
How to change UI language

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1001]
_From [mentat...@gmail.com](https://code.google.com/u/116256814944482205201/) on 2012-04-21T12:22:36Z_

Hi,

I'd like to change the UI language: default from OS is French in my computer, but I want it in English. I thought it was obvious, but I can't find the settings.

Any idea?
Thanks

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1001_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-22T00:10:58Z_

Well, it's not so common for people to choose a language different from their locale: that's why language selection is automatic in Spyder.

However, you may override this behavior by defining a standard variable environment (and this should also change the UI language of any installed software using GNU gettext):
LANG=en_US

**Status:** Done

**Comment by spyder-issues-migrator** [comment]
_From [ajit....@gmail.com](https://code.google.com/u/103127063444650459571/) on 2014-08-11T08:22:03Z_

Hi,

I too have the same problem.I installed Python(x,y) on windows. I want to change UI language from Spanish to English and I cannot find the location of LANG.

Any help ?

Thanks
Ajit

**Comment by spyder-issues-migrator** [comment]
_From [ajit....@gmail.com](https://code.google.com/u/103127063444650459571/) on 2014-08-11T08:32:13Z_

Hi,

I was able to locate language and region and made changes to UK. Things worked.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-11T17:20:44Z_

How do you do it?

**Comment by hg2051** [comment]
Tools-->Current user environment variables-->OK-->Right click-->Insert-->Key-->en-US-->OK.
Exit, restart.

**Comment by ccordoba12** [comment]
This was asked several times, so we need an option in Preferences to do it.

**Comment by goanpeca** [comment]
As soon as the restart PR is merged I can take this one, now it would be friendly to ask for a restart.

**Comment by ccordoba12** [comment]
Good! Please add this to

    Preferences > General

**Comment by goanpeca** [comment]
:+1:

**Comment by charlesjansen** [comment]
same issue, I got it in French and need it in English, on Windows

**Comment by vanshika-bawa** [comment]
I had the same issue. This worked : 
Tools --> *Preferences --> General --> Advanced settings --> Language

**Comment by hg2051** [comment]
Thanks. I managed to do it too (I don't remember if the way you did it or
otherway)

**Comment by JMDesperrier** [comment]
For anyone who would find this bug when looking for info about how to change the language with Spider 6.0.3 or above, the option is now in 
Tools --> Preferences --> Application --> Advanced settings tab (to the right of Interface) --> Language.
