### ISSUE TITLE
Unable to load .spydata

### ISSUE THREAD

**Issue by michaelgtadesse** [spyder-ide/spyder#10013]
### What steps will reproduce the problem?

Error message: Object arrays cannot be loaded when allow_pickle = False

### Traceback
```python-traceback
  File "C:\Users\mi292519\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 135, in perform_request
TypeError: 'NoneType' object is not subscriptable
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> Error message: Object arrays cannot be loaded when allow_pickle = False

Please provide a simple and reproducible code example that generates this error.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
