### ISSUE TITLE
code introspection does not work

### ISSUE THREAD

**Issue by Rayapur** [spyder-ide/spyder#10023]
### What steps will reproduce the problem?

on my macbook, i have installed anaconda and then spyder through anaconda. the code introspection and command+I work from IPython console but not from Editor. what is the fix for it? i have checked the boxes under preferences -> Help. 

appreciate your response. 

## Versions

* Spyder version: 3.3.6 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.7.0

### Dependencies

```
IPython >=4.0     :  7.7.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by goanpeca** [comment]
@Rayapur, code introspection has been completely reworked to the issues you and other users have encountered. These changes will come with Spyder 4.0 to be released in a couple of months.

**Comment by ccordoba12** [comment]
For now there's nothing else we plan to do to improve the situation in Spyder 3.
