### ISSUE TITLE
Use stdio instead of tcp by default to communicate to LSP servers

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#10021]
This would have two advantages in my mind:

1. It'd simplify our validations to avoid issues like #9992. If we switch to stdio by default, we could remove the `address:port` values that we provide right now (leaving instead placeholders), which will force people to introduce their own if they want to use an external server or tcp for communications.
2. It will simplify the addition of new LSP servers because people wouldn't have to provide the `address:port` server info. Besides, not all servers support tcp, but they must support stdio one way or another to work.

@andfoy, what do you think?

**Comment by andfoy** [comment]
Not all lsp servers support stdio, and not all lsp servers support tcp.

**Comment by ccordoba12** [comment]
You didn't understand me. I don't want to *eliminate* tcp in favor of stdio (or vice-versa). What I meant is that we should switch to use stdio by default in our Preferences:

![Selección_019](https://user-images.githubusercontent.com/365293/63105036-4c664280-bf80-11e9-8bef-8c99e0f1b60e.png)

![Selección_021](https://user-images.githubusercontent.com/365293/63105162-86cfdf80-bf80-11e9-881b-d819d370c2a5.png)

That would help us simplify things in the ways I mentioned above.

**Comment by andfoy** [comment]
Got it @ccordoba12, sorry about the confusion

**Comment by ccordoba12** [comment]
@steff456, the idea is the following to complete this:

* Activate the option "Use stdio pipes to communicate with server" (the one in the first screenshot) by default.
* Remove the values for "IP address and port to bind the server to" and leave placeholders there with the same values that appear right now.

That's it! After this is in place, we can create a simpler validation to fix issue #9992.

**Comment by ccordoba12** [comment]
Let's leave this for Spyder 5 because we don't have time to move our tests to use stdio and also to allow beta users let us know if that's working well in all OSes.

**Comment by goanpeca** [comment]
It seems stdio is slower, so we should not probably do this
