### ISSUE TITLE
Feature Request: Changeable dark theme variant

### ISSUE THREAD

**Issue by validatedev** [spyder-ide/spyder#10027]
Why there's the dark theme with just the dark blue color? There should be the dark gray-blackish color variant. That's the true dark mode experience IMO.

**Comment by ccordoba12** [comment]
> Why there's the dark theme with just the dark blue color?

Because we're using the [QDarkstyle](https://github.com/ColinDuquesnoy/QDarkStyleSheet) package to provide a dark theme, and they decided to use dark blue.

> There should be the dark gray-blackish color variant. That's the true dark mode experience IMO.

QDarkstyle could add different palettes in the future, but that depends on them and not us, sorry.
