### ISSUE TITLE
Editor has several problems to handle emojis

### ISSUE THREAD

**Issue by tisboyo** [spyder-ide/spyder#10039]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Attempting to place an emoji in the code causes the last character of the line to be erased when leaving said line.

### What steps reproduce the problem?

1. Line attempted to write is: await ctx.message.add_reaction('🚫')
2. Hit enter or arrow to leave the line

### What is the expected output? What do you see instead?
Expect the line to remain intact, instead the last character is being deleted.

This is a fresh anaconda install, with spyder running in a fresh environment. 
I was previously running 4.0.0b2 and did not have this issue.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.0b4
* Python version: 3.74 64bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 1903

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
@impact27, I think this problem could be related to your changes in PR #8734. Could you take a look at it?

**Comment by tisboyo** [comment]
Turning off the option 'Automatically strip trailing spaces on changed lines' does stop the behavior. 

Turning on 'Automatically remove trailing spaces when saving files' does not cause the problem to return.

**Comment by impact27** [comment]
The composed emoji is quite broken :/ I tried this: 💆🏽‍♂️
(Which is 
<img width="53" alt="Screenshot 2019-08-19 at 11 03 58" src="https://user-images.githubusercontent.com/6740194/63257325-6e5a1080-c271-11e9-80e6-ea02d4965965.png">
)
`a = '💆🏽‍♂️'` gives:
<img width="86" alt="Screenshot 2019-08-19 at 11 04 34" src="https://user-images.githubusercontent.com/6740194/63257361-7e71f000-c271-11e9-8258-edd2e28ebad5.png">
So the male attribute is separated from the emoji. (That might be a Qt problem.)
Then if I try to remove what should be a single charater, I have to press return five times:
<img width="86" alt="Screenshot 2019-08-19 at 11 04 34" src="https://user-images.githubusercontent.com/6740194/63257466-c133c800-c271-11e9-8d48-eca89200a60b.png">
<img width="89" alt="Screenshot 2019-08-19 at 11 04 54" src="https://user-images.githubusercontent.com/6740194/63257473-c42eb880-c271-11e9-9219-493d5f2ca957.png">
<img width="77" alt="Screenshot 2019-08-19 at 11 04 59" src="https://user-images.githubusercontent.com/6740194/63257482-c729a900-c271-11e9-9de1-a61282dabb3d.png">
<img width="103" alt="Screenshot 2019-08-19 at 11 05 03" src="https://user-images.githubusercontent.com/6740194/63257487-c98c0300-c271-11e9-98b6-d5177b77d198.png">
<img width="78" alt="Screenshot 2019-08-19 at 11 05 08" src="https://user-images.githubusercontent.com/6740194/63257492-cc86f380-c271-11e9-8856-00a17caca04c.png">
<img width="62" alt="Screenshot 2019-08-19 at 11 05 13" src="https://user-images.githubusercontent.com/6740194/63257495-cee94d80-c271-11e9-8dd0-b6fd91f60fd0.png">
There is also a highlighting issue as the right `'` is not green.

Another problem I noticed is for `a = '🚫'`. If I add a space after the emoji `a = '🚫 '`, I go from:
<img width="73" alt="Screenshot 2019-08-19 at 11 12 31" src="https://user-images.githubusercontent.com/6740194/63257692-4323f100-c272-11e9-9d5f-0206ab67c83b.png">
to:
<img width="100" alt="Screenshot 2019-08-19 at 11 11 43" src="https://user-images.githubusercontent.com/6740194/63257648-2687b900-c272-11e9-91a7-0072cdd20f86.png">

So my guess is that there is a problem with the termination character of emojis, probably in Qt.

**Comment by impact27** [comment]
For example:
`cursor.block().text()` = `('a')`
`len(cursor.block().text())` = 5
`cursor.block().length()` = 6 (with '\n')
But:
`cursor.block().text()` = `('🚫')`
`len(cursor.block().text())` = 5
`cursor.block().length()` = 7 !!!

**Comment by impact27** [comment]
From https://doc.qt.io/qt-5/qtextcursor.html:

> Note: The "characters" in this case refer to the string of QChar objects, i.e. 16-bit Unicode characters, and the position is considered an index into this string. This does not necessarily correspond to individual graphemes in the writing system, as a single grapheme may be represented by multiple Unicode characters, such as in the case of surrogate pairs, linguistic ligatures or diacritics.

**Comment by impact27** [comment]
After investigation, `a = '💆🏽‍♂️'` is a problem in qtconsole as well, while` a = '🚫 '` is a syntax highlighter issue.

**Comment by ccordoba12** [comment]
@impact27, do you have any solution for this? If this is not easy to solve, I'm afraid we'll have to leave this one to be solved by the community.

**Comment by impact27** [comment]
I tried to import QString but it is not avilable in pyqt5. So basically pyqt will give these kind of errors for any string that contains characters that can not be represented by a single utf16 char. What I could do is to write a function that tries to guess what the length of a QString containing that string would be.

**Comment by impact27** [comment]
```
def QString_len(text):
    """
    Tries to compute what the length of an utf16-encoded QString would be.
    """
    if PY2:
        # I don't know what this is encoded in, so there in nothing I can do.
        return len(text)
    utf16_text = text.encode('utf16')
    length = len(utf16_text) // 2
    # Remove Byte order mark.
    # TODO: All unicode Non-characters should be removed
    if utf16_text[:2] in [b'\xff\xfe', b'\xff\xff', b'\xfe\xff']:
        length -= 1
    return length
```

**Comment by impact27** [comment]
Obviously it is not perfect but it would at least help a bit. I feel like this is reinventing the wheel but I am not sure what is the proper way of doing that.

**Comment by impact27** [comment]
Well the proper way would be to get the length of a QString but I don't think we can access QStrings from qtpy.

**Comment by ccordoba12** [comment]
> Obviously it is not perfect but it would at least help a bit

Ok, sounds good to me. Thanks for taking a look at this!

> Well the proper way would be to get the length of a QString but I don't think we can access QStrings from qtpy.

That's not possible. See here:

https://www.riverbankcomputing.com/pipermail/pyqt/2014-January/033561.html
