### ISSUE TITLE
Outline explorer gets tripped up by line wrapping

### ISSUE THREAD

**Issue by c-hahn** [spyder-ide/spyder#10037]
## Problem Description

The outline explorer may get tripped up when line wrapping is active and long lines from the source file are displayed as multiple lines in the editor (apparently the explorer counts these displayed lines.) Selecting an item then may jump to the wrong line in the editor file, and the tooltip ("defined at line #") will also show the wrong line. If "Editor > Wrap lines" is turned off, everything works fine.

### What steps reproduce the problem?

1. Enable "Editor > Wrap lines"
2. Open a source file with multiple items in the outline explorer and long lines that are wrapped in the editor.
3. The mismatch between the position reported in the outline explorer and the actual position in the file grows progressively worse, the more wrapped lines occur before an item's source code.

### What is the expected output? What do you see instead?

Expected to see correct line number for each item in the outline explorer.

## Versions

* Spyder version: 4.0.0b4
* Python version: 3.6.8 64-bit
* Qt version: 5.12.3
* PyQt version: 5.12.2
* Operating System name/version: Ubuntu 18.04.3 / Linux 4.15.0-58-generic

### Dependencies

```
pygments >=2.0    :  2.4.0 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
psutil >=0.3      :  5.6.2 (OK)
pyls >=0.27.0     :  v0.28.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.3 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
This shouldn't be a problem anymore in Spyder 4.2.0
