### ISSUE TITLE
installing spyder-3.3.6 on windows-10 requiring admin password on a user install

### ISSUE THREAD

**Issue by ebo** [spyder-ide/spyder#10030]
I installed anaconda as a non-privileged user into a non-standard directory which mirror install locations on our servers.  I have been successfully running anaconda in this environment for months.  Today I attempted to install spyder, and anaconda is trying to set something in the registry which is requiring the administration password.  

Steps to reproduce:

    run Anaconda3-2019.03-Windows-864_64.exe to install the base system on any non standard location a non-privileged user can install -- try c:\temp\anaconda3

Update everything:

    conda update --all

and verify everything is functional.

install sypder from the conda-forge channel -- note: some of my dependencies require the use of conda-forge, and if you do not use the conda-forge channel then non-conformant libraries get pulled in their place:

  conda install -c conda-forge spyder

I also tried  "conda install spyder" with similar results.

I will try restarting the machine and other things, but I was not expecting anything to request admin privileges from a user installation.  I will update this issue if I find anything helpful, but I will not be able to maintain any packages long term which require privileged access on these machines.

Any idea why the spyder install is requiring privelaged access when nothing else has?

Info:
* I checked the issues before posting.  I did not find any that clearly addressed this.
* I have tried to install this in both the root (base) environment as well as a newly created one (dev)
* qtconsole-4.5.3  (py_0    conda-forge)
* this is basically a new clean install with a number of required packages installed
* ipython-7.7.0 python-3..7.3  qt-5.9.7 
* again, this is on a new Windows-10 box.

Since this is a problem with the install, it does not fall within the rest of the spyder troubleshooting guide.

**Comment by ccordoba12** [comment]
This is not something we can help you to solve, sorry. Please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/
