### ISSUE TITLE
example_latin1.py and example.py missing from v3.3.6 sdist

### ISSUE THREAD

**Issue by jayvdb** [spyder-ide/spyder#10040]
The v3.3.6 sdist doesnt contain spyder/utils/tests/example.py and example_latin1.py 

They are in the tree for that tag, and needed by the tests

https://github.com/spyder-ide/spyder/tree/v3.3.6/spyder/utils/tests/data

**Comment by jayvdb** [comment]
Also missing spam.py https://github.com/spyder-ide/spyder/blob/v3.3.6/spyder/widgets/tests/data/spam.py

**Comment by jayvdb** [comment]
fwiw, with those three files added, the test suite pass on openSUSE with only a few tests de-selected
https://build.opensuse.org/request/show/724489

**Comment by ccordoba12** [comment]
Tests are not distributed anymore with our tarballs, sorry.

Testing Spyder is a very complex matter so upstream packagers really have to trust that we're doing our job correctly.

**Comment by jayvdb** [comment]
@ccordoba12 , thanks for the update.  I see v4 beta sdists are excluding tests.  Distros can get them from the GitHub release tarballs. :+1:

Worth noting however that distros doing their own tests complements your teams testing, such as testing on platforms that the team here doesnt have access to, and different combinations of dependency versions, but more importantly it ensures the distro packaging was correct, hopefully failing whenever there are incorrect versions of dependencies, or other subtle breakages caused on their side rather than your side.

**Comment by ccordoba12** [comment]
I understand it's useful for you to perform those extra checks. However, we don't have a simple way to test that we're packaging everything that's needed to run our test suite. So, it's simpler easier for us to exclude tests from our own tarballs.

**Comment by jayvdb** [comment]
Typically https://pypi.org/project/check-manifest/ works quite well at ensuring the sdist is complete.  Not sure if that would not work in this project, which is larger than most projects and possibly breaks check-manifest.
