### ISSUE TITLE
Open files on mac with anaconda-installed python.

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#10054]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When installing spyder on mac, the user has two options:

 - Use macports and get a macport installed python.
 - Use Anaconda / pip and get an anaconda/pip installed python.

I am not sure if it is possible to use the same python version, but using different python versions is a pain. The problem is, with the anaconda-installed python (or pip-installed), the files are not opened when double-clicking on them. (Or right-click + open with spyder). This is because spyder need to be an app to solve this.

The solution I came up with for myself is as follow: I have spyder installed as a module, and I created an app that is a wrapper around `bootstrap.py`. This means I can update spyder, python and all other packages with conda / brew + pip, and still use the same app.

The wrapper has the following structure:
```
+ Spyder.app
|
+-+ Contents
  |
  +-+ MacOS
  | +- Spyder (This is bootstrap.py + `#!/usr/local/bin/python3` prefix)
  |
  +-+ Resources
  | +- spyder.icns (The icon)
  |
  +- Info.plist (A plist file listing the extensions spyder can read (All code files))
```

These three files allow me to keep the same spyder app while spyder is updated via anaconda. That allows me to keep spyder in the dock and open spyder by double clicking a `.py` file. The changes I need to make to the spyder code base to make this work are small. (https://github.com/spyder-ide/spyder/commit/cc04e5192261fea31858d3b1efcf3531b0a370d1)

My question is therefore: Is that something that could be of interest to other users? I guess I see either:
 - An option to gererate the .app folder from spyder, so the correct `sys.executable` can be set.
 - Instructions on the spyder installation website, saying that this is an (Advanced? unsupported?) alternative to using MacPorts.

**Comment by ccordoba12** [comment]
> My question is therefore: Is that something that could be of interest to other users?

Yes, I think this would be a huge improvement for macOS users in terms of usability.

> An option to gererate the .app folder from spyder, so the correct sys.executable can be set.

Instead of that (which would be useful for power users only), I'd prefer to add support for macOS to the [menuinst](https://github.com/ContinuumIO/menuinst/) package, so when Spyder is installed in any conda env an app is created automatically pointing to it.

Right now that package is responsible for adding menu entries on Windows for Spyder, but it can be extended to support other operating systems.

**Comment by goanpeca** [comment]
Menuinst originally supported that behavior, so there is code in there to do precisely this.

Also the issue is how to handle if spyder is installed in an environment in which case there is a flag in conda to ibstall the app or not (and how the name of the app depends on the env name)

**Comment by ccordoba12** [comment]
> Menuinst originally supported that behavior, so there is code in there to do precisely this.

Where is that code? And also, how to make that work for any conda package that declares itself as an app?

**Comment by impact27** [comment]
I can open a PR for https://github.com/spyder-ide/spyder/commit/1a324f3f6a87621f25ddd6bacc15e0be6559b723 . I am not sure how to use  menuinst, but looking at https://github.com/ContinuumIO/menuinst/blob/master/menuinst/darwin.py, I am not sure if:
```
"""\
#!/bin/bash
%s/python.app/Contents/MacOS/python %s
"""
```
Would work. First, python is not necesarly installed as an app (`.../python.app/Contents/MacOS/python`, mine is at `/usr/local/opt/python/bin/python3.7`). Secondly, I used `#!/bin/bash` + sys.executable for a while, but that stopped working for some reason (6 months ago or so). I now use `#!/usr/local/bin/python3` + the content of `bootstrap.py` and this works well.

**Comment by impact27** [comment]
Actually, the executable file should probably be:
```
'#!' + sys.executable + '\n\nfrom spyder.app import start\nstart.main()\n'
```

**Comment by impact27** [comment]
The executable can be created by:
```python
fn_executable = '/Applications/Spyder.app/Contents/MacOS/Spyder'
with open(fn_executable, 'w') as f:
    f.write('#!' + sys.executable + '\n\nfrom spyder.app import start\nstart.main()\n')
os.chmod(fn_executable, 0o755)
```
Then the logo and the plist file can simply be copied.

**Comment by impact27** [comment]
Copying the plist is easier than creating it programatically. The menuinst does not support `CFBundleDocumentTypes` yet so the app could not open files anyway.

**Comment by ccordoba12** [comment]
> I can open a PR for 1a324f3

Sure, no problem with that.

> I am not sure how to use menuinst

I think you need to create a json file that declares how to create the app (i.e. executable, icon and plist). This is the one for Windows:

https://github.com/conda-forge/spyder-feedstock/blob/master/recipe/menu-windows.json

which tells `menuinst` how to create menus for Spyder.

> The menuinst does not support CFBundleDocumentTypes yet so the app could not open files anyway.

Then you'd need to add support for that too.

**Comment by impact27** [comment]
closing this issue since we have macOS installer in spyder-ide/spyder since v4.2.0.
