### ISSUE TITLE
Add an option to set font in Outline Explorer

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1006]
_From [petrus.h...@gmail.com](https://code.google.com/u/113904071220560210639/) on 2012-04-27T02:25:20Z_

I can not / can not find the way / to change the font in the outline exporer. 

I find the default font too big for my small screen.

The same applies for the variable exporer, but that is already reported in separate issue. What version of the product are you using? On what operating system? Mac osx 10.7
spyder 2.1.9 Python 2.7.3, Qt 4.8.0, PyQt4 (API v2) 4.9.1 on Darwin 

Many thanks

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1006_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-28T05:10:51Z_

**Summary:** Add an option to set font in Outline Explorer  
  **Status:** Accepted  
  **Labels:** -Type-Defect Type-Enh MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T14:39:50Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:53:22Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by goanpeca** [comment]
@ccordoba12 is this worth implementing?, should each plugin have the avility to set its fonts ?

**Comment by ccordoba12** [comment]
Nop, we need to set the same font for all plugins for 3.0.
