### ISSUE TITLE
 module 'numpy' has no attribute 'byte'

### ISSUE THREAD

**Issue by vanetoj** [spyder-ide/spyder#10068]
### What steps will reproduce the problem?

i m just importing numpy and its giving me this error- "  module 'numpy' has no attribute 'byte'. not sure whats that about..

### Traceback
```python-traceback
  File "C:\Users\vanet\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

ImportError: numpy.core.multiarray failed to import
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
I'm sorry but this problem has nothing to do with Spyder. It was probably caused by using pip to install some software in Anaconda.

Please reinstall Anaconda to fix it.
