### ISSUE TITLE
File stops running after a few minutes.

### ISSUE THREAD

**Issue by jamesyongithub** [spyder-ide/spyder#10078]
### What steps will reproduce the problem?

I have a couple of scripts I expect to take a long time to run. They map functions on 10000x10000 numpy arrays, so I expect them to take a while. When dealing with an array of 10000x6000, the program will run, but then appears to stop. 
I say appears to, because the console input line shows up (What i mean is,"In 1:" appears in my console) and the memory in the bottom corner of my screen jumps back down to 30% from 92%. 
However the stop button is still red and clickable. 
I checked my work directory and the files I wanted the script to create were not made. I also have the same issue when using matplotlib.pyplot.savefig() when I set the dpi over 2500. 

My issue seems to be, if my script runs for too long, it aborts running without printing any warnings or notification to the console. How do i fix this?

Kindest regards.

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.9
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 5.2.9-125.current

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.2 (OK)
nbconvert >=4.0   :  5.5.0.dev0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.11 (OK)
qtconsole >=4.2.0 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> My issue seems to be, if my script runs for too long, it aborts running without printing any warnings or notification to the console. How do i fix this?

I'm sorry but this looks to be an issue with your program and not with Spyder. Probably you program consumes all RAM available in your computer and then aborts due to that.

What you can is add some print's to your code to verify that it's progressing as expected.
