### ISSUE TITLE
.py written in 3.3.3 in anaconda can't run in 3.3.6

### ISSUE THREAD

**Issue by fanzz1982** [spyder-ide/spyder#10075]
### What steps will reproduce the problem?

my program 。 It seems that the axes[].plot() from matplotlib has sth wrong in spyder 3.3.6.The alarm messenge is :tuple index out id range

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.4 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> my program 。 It seems that the axes[].plot() from matplotlib has sth wrong in spyder 3.3.6.The alarm messenge is :tuple index out id range

This is not a problem in Spyder but in Matplotlib. You probably need to update your code to work with the Matplotlib version you have now installed.
