### ISSUE TITLE
Outline trace to editor wrong when nodes condensed in editor

### ISSUE THREAD

**Issue by Mantxurreta** [spyder-ide/spyder#10073]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The outline link to the editor goes to the wrong line when a node is condensed in the editor above the class you select in the outline.

### What steps reproduce the problem?

1. open a file with several class definitions
2. put the outline panel in view if it is not yet.
3. Condense one node in the editor.
4. Clic on a class in the Outline defined below the condensed node in the editor.

### What is the expected output? What do you see instead?
This is leading the editor to a wrong location in the file.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder 4.0.0b4 
* Python version: Python 3.6.8 64-bit 
* Qt version: Qt 5.12.4
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Linux 5.1.0-050100-generic 

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  v0.28.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.17.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this one?

**Comment by impact27** [comment]
In `spyder/plugins/editor/utils/editor.py`:

```
def _move_cursor_to(self, line):
        cursor = self._editor.textCursor()
        block = self._editor.document().findBlockByNumber(line-1)
        cursor.setPosition(block.position())
        return cursor
```
`findBlockByNumber` should be replaced by findBlockByLineNumber I think.

**Comment by impact27** [comment]
There is 23 other occurences of `findBlockByNumber` in the code. But I guess the problem is:

<img width="197" alt="Screenshot 2019-08-25 at 10 13 44" src="https://user-images.githubusercontent.com/6740194/63647994-0bf58a00-c721-11e9-8bec-ad3499b1419a.png">

Here `C.c` is on line 15 (defined by `block.firstLineNumber() + 1`) or line 19 (`block.blockNumber() + 1`)
