### ISSUE TITLE
Feature request: Extract method

### ISSUE THREAD

**Issue by danuker** [spyder-ide/spyder#10099]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [N/A] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [N/A] Tried basic troubleshooting (if a bug/error)
    * [N/A] Restarted Spyder
    * [N/A] Reset preferences with ``spyder --reset``
    * [N/A] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [N/A] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I would love to see a feature similar to PyCharm's ["Extract method"](https://www.jetbrains.com/help/pycharm/extract-method.html).

This would be especially useful to aid refactoring, when splitting large functions. Doing it by hand is quite error-prone, but an automated tool will come in very handy.

### What steps reproduce the problem?

1. Select a piece of code
2. Try finding the "Extract Method" option
3. Does not exist (yet)

### What is the expected output? What do you see instead?

After selecting a piece of code, and then choosing the menu option to "Extract method", a dialog pops up asking you about the order and names of parameters and the return value.

On clicking OK, the selected code is replaced with a function/method call, and a new function/method is created below the current one.

It should show a failure message, if it does not detect a pattern which it can extract (for example, the selection is not inside a function or method).

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.3 64-bit
* Qt version: 5.10.0
* PyQt version: 5.10
* Operating System name/version: Debian 10; Linux 4.19.0-5-amd64

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.1 (OK)
pandas >=0.13.1   :  None (NOK)
psutil >=0.3      :  5.5.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
Thanks for the suggestion. You're basically asking for refactoring support, which has been asked several times in the past. We'll try to implement it next year.

**Comment by danuker** [comment]
@ccordoba12 I suppose you mean issue #415; mentioning it here for reference. Thanks for the reply!
