### ISSUE TITLE
Spyder 4.0.0 b4 installation

### ISSUE THREAD

**Issue by SandeepShaw2017** [spyder-ide/spyder#10105]
I have been facing issues while installation of Spyder 4. Following is the error. Pls guide.

(C:\ProgramData\Anaconda3) C:\Users\admin\Documents>conda install -c spyder-ide spyder=4.0.0b4
Fetching package metadata ...........
Solving package specifications: .

PackageNotFoundError: Package not found: '' Dependencies missing in current win-64 channels:
  - spyder 4.0.0b4* -> atomicwrites
  - spyder 4.0.0b4* -> pexpect
  - spyder 4.0.0b4* -> python-language-server >=0.27.0 -> autopep8
  - spyder 4.0.0b4* -> python-language-server >=0.27.0 -> jedi >=0.13.2,<0.14
  - spyder 4.0.0b4* -> python-language-server >=0.27.0 -> pluggy
  - spyder 4.0.0b4* -> python-language-server >=0.27.0 -> pydocstyle >=2.0.0
  - spyder 4.0.0b4* -> python-language-server >=0.27.0 -> yapf
  - spyder 4.0.0b4* -> python-language-server >=0.27.0 -> python >=3.7,<3.8.0a0
  - spyder 4.0.0b4* -> qtawesome >=0.5.7
  - spyder 4.0.0b4* -> qtconsole >=4.5.2
  - spyder 4.0.0b4* -> qtpy >=1.5.0
  - spyder 4.0.0b4* -> spyder-kernels >=1.4.0,<1.5.0 -> ipykernel >4.9.0
  - spyder 4.0.0b4* -> spyder-kernels >=1.4.0,<1.5.0 -> jupyter_client >=5.2.3
  - spyder 4.0.0b4* -> spyder-kernels >=1.4.0,<1.5.0 -> pyzmq >=17

Close matches found; did you mean one of these?

    pexpect: execnet
    pydocstyle: pycodestyle

You can search for packages on anaconda.org with

    anaconda search -t conda yapf

(and similarly for the other packages)

**Comment by ccordoba12** [comment]
> (and similarly for the other packages)

If you're having this kind of problems, it probably means that you broke Anaconda. So now you need to uninstall and reinstall it again.
