### ISSUE TITLE
Spyder Error on Startup

### ISSUE THREAD

**Issue by zdhughes5** [spyder-ide/spyder#10108]
### What steps will reproduce the problem?

After updating spyder with:

conda install -c spyder-ide jedi=0.14.1

As a solution to this issue:

https://github.com/spyder-ide/spyder/issues/10057

Starting spyder with:

spyder --new-instance &

Creates to provided error message on the spyder splash screen when starting up.

UPDATE:
In my case Spyder is being loaded over a network filesystem. I noticed that the network bandwidth was being used to capacity; since returning to normal levels the issue seems to have been resolved.

### Traceback
```python-traceback
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 319, in on_msg_received
    handler(resp['params'])
  File "/nfs/programs/zdhughes/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/languageserver/client.py", line 378, in process_server_capabilities
    if isinstance(server_capabilites['textDocumentSync'], int):
KeyError: 'textDocumentSync'
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.1.6-1.el7.elrepo.x86_64

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.5.2 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Sorry, you also need to update `python-language-server` with this command:

    conda install -c spyder-ide python-language-server=0.28.2
