### ISSUE TITLE
Open Collective

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#10118]
Hello,

1) Can you put Open Collective Badge on top
of Spyder documentation page /github readme ?
Easier for people to contribute financially.

2) Is it way to finance by open collective some new features dev in Spyder ?

3) Is there a way to see new feature requests ?

**Comment by ccordoba12** [comment]
> Can you put Open Collective Badge on top

Thanks for the suggestion. We'll add the Github "Sponsor" button that redirects to Open collective.

> Is it way to finance by open collective some new features dev in Spyder ?

No, sorry. We use the money as we consider necessary.

**Comment by arita37** [comment]
Hello,

1) Can you create a list of 
best voting features ? (ie most wanted)

2) People can also contribute 
by Open Collective to those features ?
It makes easier to hire “students” or people.
and will attract much more donator.

By controbuting, it does not mean that it will get done right, but increase attractivity of donators....


What do you think ?

**Comment by techtonik** [comment]
@arita37 you can fund any feature you find important with https://gitcoin.co

**Comment by arita37** [comment]
Thanks
How to link your github features with gitcoin.

Thanks, Regards

**Comment by techtonik** [comment]
@arita37 look here - https://gitcoin.co/how/funder- you don't need to create an issue on GitHub - it is possible to select existing one.

**Comment by arita37** [comment]
Thanks.
Does it appear on the spyder github issues too ?

Regards.

**Comment by techtonik** [comment]
@arita37 gitcoin.co is a parallel bounty service that is independent from this project, and attracts people from outside.

**Comment by ccordoba12** [comment]
@steff456, please take care of this one so we can display the new Github "Support" button on top of all pages in this repo.
