### ISSUE TITLE
displaying DOcplex variable list index wrong

### ISSUE THREAD

**Issue by a280558071** [spyder-ide/spyder#10116]
### What steps will reproduce the problem?

from docplex.mp.model import Model
test_var=model.binary_var_list(20)

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by a280558071** [comment]
![image](https://user-images.githubusercontent.com/11343667/64062002-4759f200-cc14-11e9-98de-d4053a34e285.png)

**Comment by ccordoba12** [comment]
This is already fixed and it'll be part of beta5.
