### ISSUE TITLE
Python has stopped working

### ISSUE THREAD

**Issue by ccie5000** [spyder-ide/spyder#10119]
Win7Pro SP1 64-bit
new Anaconda3-2019.07 install

Every time I try to start Spyder it fails with the error message: Python has stopped working.

I've tried restarting, rebooting, and deinstalling/reinstalling Anaconda.

Does anybody have any idea what might be causing this, or how I might resolve the issue?

-- 
Jerry J. Anderson, CCIE #5000

**Comment by ccordoba12** [comment]
This is probably related to you antivirus and/or firewall. Please deactivate them and try again.

**Comment by ccie5000** [comment]
I deinstalled all virus/firewall software and rebooted.  I then deinstalled Anaconda.  I removed the C:\Users\<userid>\Anaconda3 directory.  I rebooted again.  Finally I reinstalled Anaconda.  I tried running Spyder, and got the same "Python has stopped working" error message.

**Comment by ccordoba12** [comment]
I'm very sorry about that, but that's the only advice we have for this kind of problem without more details about the issue.

There's probably another software in your computer causing this, but it's impossible to know for us which one.

**Comment by dreynolds109** [comment]
I have the exact same issue.  Windows 7 64 bit.  Have done everything you have done and still get the same Python has stopped working.  Very frustrating.  Have checked to make sure python is in the path and no other versions of Anaconda or .anaconda files were on my computer when I installed Anaconda 3.7 64 bit.  Spyder was working fine in the old version I had Anaconda 2.0.
