### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by JOISSONG** [spyder-ide/spyder#10120]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Idont know what happened
conda could not install pybrain,so I uninstall Python on my PC(installed before conda), and before that, I do " numpy.test('full')' by nose,
then this jump out

**Comment by ccordoba12** [comment]
This doesn't look to be a Spyder error, sorry.
