### ISSUE TITLE
Spyder Crash when no user defined on current uid - Linux

### ISSUE THREAD

**Issue by aber69** [spyder-ide/spyder#10129]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder crached on initialization when pwd.getpwuid() returns and error.
In spyder/utils/programs.py:43 in get_temp_dir, there is a call to getpass.getuser which can raise exception (e.g. KeyError from pwd.getpwuid) and this exception is not catched.

### What steps reproduce the problem?

1.  Run spyder from linux-docker, when the is no user under current uid, (with X support)
2.  Get crash after the splash screen

### What is the expected output? What do you see instead?
Please add any reasonable treatment to avoid the crash.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please suggest what we could do because we need to identify the user home directory to create our configuration preferences there.

**Comment by ccordoba12** [comment]
Ok, I saw that you can add a user in docker by using the useradd directive to create a user, so you need to use that in your dockerfile.

**Comment by aber69** [comment]
Hi,
I'm using spyder 4b2 so functions and code lines are according to it.
During the startup of spyder you call get_temp_dir function from utils/programs.py
It uses on row 43:
username = encoding.to_unicode_from_fs(getuser())
which is used then to create user specific tempdir name

My suggestion is to wrap this code by try ... except KeyError and in this case exeption assign some random name instead of user name.

Rather simple...

The idea to create work around with all relavant users leads to more complex problems on level of entire X.

**Comment by ccordoba12** [comment]
If this is so important to you, please take the time to create a pull request for it.

For us it's a pretty narrow use case and we already offered you a solution for it (by the way, useradd is a docker command, not a Spyder one).
