### ISSUE TITLE
I am using spyder 3.3.6. When I work in a project and close after saving it, after reopening the same file I don't get any variable there. I have tried to solve it by saving the variables. But main problem is after reopening I select entire .py part and tried shit+enter and F9 and ctrl+ enter to run the entire file. But it didn't work. I need to run every cell one by one. Its irritating and time consuming. Is there any solution? 

### ISSUE THREAD

**Issue by srvmig** [spyder-ide/spyder#10121]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Sorry, there isn't.

**Comment by ccordoba12** [comment]
I'm sorry, I should have clearer. These are my comments to what you said:

1. You simply need to press F5 to run an entire file.
2. Variables saved in the Variable explorer are not restored automatically after you open a project. What you need to do is to press the "Import" button in the Variable Explorer in order to do that.

**Comment by srvmig** [comment]
I have used r-studio. Its quite handy to work with. I am not complaining. Because spyder is quite new. Can you try to make a like r-studio one? And I need your one suggestion. Which IDE will be best for practicing data science?

**Comment by srvmig** [comment]
Can I ask another help please? When I am using pandas I am getting shorter at .description. I changed it to pd.set_display. When I am closing it, it again got back to shorter display option. Should I set it every time when I use? Or there is any option to do it one time?

**Comment by ccordoba12** [comment]
> Should I set it every time when I use?

Yes, it's better if you add that to your code because Pandas options doesn't remain after a Spyder is restarted.
