### ISSUE TITLE
Tooltips not closed upon CTRL+Enter to jump to definition

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10130]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In beta 4, if you move the mouse over a function call, after a brief second a tooltip window appears, as it should. If you CTRL+LEFT click on the call while the tooltip is displayed you are taken to the function definition. However the tooltip window is not cleared - you can move the mouse around anywhere and the tooltip remains. You can start typing in the editor - the tooltip window remains.

You can get very unexpected behavior by then hovering the mouse over the definition - in a short time a second, identical tooltip window is displayed, so now you have two tooltips displayed for the same function. Moving the mouse away clears the one that just opened, but not the one that was created before the CTRL+LEFT click.

### What steps reproduce the problem?

1. Hover over function call, wait for tooltip to appear
2. CTRL+CLICK on the function

### What is the expected output? What do you see instead?

I'd expect the tooltip to disappear, or at least still be 'watching'the mouse and keyboard so it disappears as soon as you do something. However, I'd argue for disappear, since it obscures the code I'm trying to read. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.0.0b4
* Python version:  3.7.3 64-bit
* Qt version:  5.9.6
* PyQt version:  5.9.2
* Operating System name/version:  Windows 7

### Dependencies

pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)

**Comment by goanpeca** [comment]
This has been fixes on master already. Will be available on the next beta to be released next week
