### ISSUE TITLE
Clicked on tooltip, Spyder reports internal problem

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10132]
### What steps will reproduce the problem?

I CTRL+CLICKed on function call to jump to its definition. As reported in #10130 the tooltip did not disappear. I couldn't get it to disappear no matter what I did. Eventually I clicked inside of it, which caused the "Spyder has encountered an internal problem!" window to appear, which I'm using to report this problem. 

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 918, in inspect_current_object
    offset = cursor.position()
AttributeError: 'NoneType' object has no attribute 'position'
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
This has been fixed in master and will be available on beta5
