### ISSUE TITLE
Issue reporter misbehaves if you delete characters of the header with the Delete key

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10136]
### What steps will reproduce the problem?

Open the Issue reporter window, and start typing in the Steps to reproduce edit box, just a word or two is fine. Then go up to the first line ("### What steps will reproduce the problem") and delete the third hash mark. This effectively breaks editing. For example, but the cursor on the line you typed, hit HOME, then type another character. The cursor jumps to the end of the line and inserts the character there. 

Alternatively, open the window and immediately delete the third hash mark. You will now be in a mode where you cannot enter any text at all, including adding the hash mark back.

Alternatively, open the Issues reporter window, select all text in the Steps to reproduce edit box, and press delete. All text disappears, and you are no longer able to enter any text at all. 

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
You missed the critical part in your report, but thanks for doing it. This was caused by a refactoring in our code editor widget to better handle the Del key there, but we forgot to update the issue reporter after that.
