### ISSUE TITLE
Issue reporter dialog should not be modal

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10135]
### What steps will reproduce the problem?

This may be intentional, but the Issue reporter window is modal. I've wanted to cut/paste code from my editor to this Window, and or test aspects of what I'm reporting, but I cannot do that since this window is modal. I suggest making the window non-modal, as with the Preferences window.

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is a good point and something that was mentioned before. @dalthviz, please work on it.
