### ISSUE TITLE
Can't click in tooltip because it disappears

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10131]
### What steps will reproduce the problem?

In beta relase 4, when you hover over a symbol briefly in the editor a tooltip appears. At the bottom it states "Click anywhere in this tooltip for additional help". If you move the mouse to try to click in the in the tooltip the tooltip disappears due to the mouse move, making it impossible to click inside it. 

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
@dalvithz could you check this? Might be related to what I saw earleir

**Comment by ccordoba12** [comment]
Repinging @dalthviz here because the above ping was wrong.

**Comment by dalthviz** [comment]
@goanpeca @ccordoba12 I will check, but probably is related to the behavior @goanpeca experienced when testing PR #9897 (I added a fix there but I'm not sure if that covers the case for the tooltip being shown without the completion widget)

**Comment by goanpeca** [comment]
>Should I do the fix for this issue on that PR?

Hmm let's try to find a fix on a separate PR.

**Comment by ccordoba12** [comment]
@goanpeca, what's exactly happening here?

**Comment by goanpeca** [comment]
Under some circumstances the tooltip dialog might hide when trying to click on it because there is a small gap between the bound box that triggers the tooltip and the tooltip itslef. It does not happen all the time but it seems it might be for win 7 ?
