### ISSUE TITLE
Ctrl+I doesn't work in editor when hovers are deactivated

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10141]
### What steps will reproduce the problem?

Pressing Ctrl+I on any object on the editor should display help in the Help windows if you have it enabled in Preferences. 

1. Under Help in Preferences, turn on Ctrl+I for both the console and editor.

2. In the editor, type 'print' on a blank line, put the cursor in front of the p, and press Ctrl+I. Nothing appears in the help window.

3. In the IPython console type 'print', put the cursor in front of the p, and press Ctrl+I. Documentation for print correctly appears in the help window.

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.2 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.4 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This can only happen if hovers are deactivated in our Preferences. We need to think how to decuple help from hovers.

Any ideas @goanpeca, @andfoy?

**Comment by goanpeca** [comment]
Hmmm yes I think we can work this better after the completions Pr is merged

**Comment by andfoy** [comment]
> This can only happen if hovers are deactivated in our Preferences. We need to think how to decuple help from hovers.

We could send the hover request regardless if it is activated for doing hovering. Right now, the LSP protocol does not offer any alternative mechanism to retrieve signatures, besides ```textDocument/hover request

**Comment by goanpeca** [comment]
@ccordoba12 I create this PR https://github.com/spyder-ide/spyder/pull/10252 so while the Kite issue is sorted, we can use the functionality (which I need for this fix)

**Comment by ccordoba12** [comment]
Good call, I agree with that.
