### ISSUE TITLE
Anaconda/Spyder3/wins10 crashed during last session

### ISSUE THREAD

**Issue by LexaChen** [spyder-ide/spyder#10154]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
(Deprecated) --show console does nothing, now the default  behavior is to show the console, use --hide-console if you want to hide it
Traceback (most recent call last):
  File "C:\Users\Lexa\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3285, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Lexa\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3140, in run_spyder
    main.setup()
  File "C:\Users\Lexa\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 844, in setup
    from spyder.plugins.editor import Editor
  File "C:\Users\Lexa\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1721
    annotation_match = re.search('"""(?:(?!""").|[\n\r])*"""', text)
                                                                   ^
TabError: inconsistent use of tabs and spaces in indentation

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> annotation_match = re.search('"""(?:(?!""").|[\n\r])*"""', text)

This line (mentioned in your error above) is not part of our code. So it seems (somehow) Spyder was corrupted and you need to reinstall it.

For that please open the Anaconda Prompt and run

    conda install -f spyder

If that doesn't work, please reinstall Anaconda instead.

**Comment by isalirezag** [comment]
i have the same issue, my spyder is working okay, but every time i use 'enter' for a new line it shows me `TabError: inconsistent use of tabs and spaces in indentation`
should i change something in the setting? usually to fix it i use 'space', tab or enter gives me that error
