### ISSUE TITLE
Cannot open vars from variable explorer

### ISSUE THREAD

**Issue by AhteshamulHaque** [spyder-ide/spyder#10155]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

* Occured during preprocessing using python
* Variables are splitted into X and Y
* Var explorer not working when accessing Y even when it is an 1D array

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
