### ISSUE TITLE
TypeError in kite client

### ISSUE THREAD

**Issue by alimehrdad** [spyder-ide/spyder#10159]
### What steps will reproduce the problem?

when i move mouse the error rasises
kite is installed
linux ubuntu 18

### Traceback
```python-traceback
  File "/home/mehrad/P374/lib/python3.7/site-packages/spyder/plugins/completion/kite/client.py", line 135, in perform_request
TypeError: 'NoneType' object is not subscriptable
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.4
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 5.0.0-25-generic

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.17.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, I think this is valid. In line 104 below (which was line 135 in beta4):

https://github.com/spyder-ide/spyder/blob/08f04cfb50cfb74e8120e8ac91f2f5e510999b5a/spyder/plugins/completion/kite/client.py#L100-L106

you're trying to apply a function to `response` when `response` can be `None` (as line 105 shows).

This should be an easy fix, but I'm unsure what do to do, so please take a look at it.

**Comment by ccordoba12** [comment]
@steff456, please ask @andfoy how to solve this one and create a PR for it.
