### ISSUE TITLE
Index order is not correct 

### ISSUE THREAD

**Issue by qinxi117** [spyder-ide/spyder#10168]
## Problem Description
The index order should be 0,1,2,3,4,5.....10,11,12,13
Not 0,1,10,11,12,13...

![图片1](https://user-images.githubusercontent.com/25376959/64569526-b679c980-d32b-11e9-846c-f6e9e9dd4408.png)

## Versions

* Spyder version: Spyder 4.0.0 beta4
* Python version: Python 3.7.3
* Qt version:  Qt version 5.9.7
* PyQt version: PyQt5 5.10.1
* Operating System name/version: Win10

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in beta5.
