### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by pinkylynn** [spyder-ide/spyder#10171]
### What steps will reproduce the problem?

dataset = pd.read_csv('balsht-ecom2018.csv')
X = dataset.iloc[:, :-3].values

Where data balsht-ecom2018.csv -
costOfRevenue	discontinuedOperations	ebit	grossProfit	incomeBeforeTax	incomeTaxExpense	interestExpense	minorityInterest	netIncome	netIncomeApplicableToCommonShares	netIncomeFromContinuingOps	operatingIncome	otherOperatingExpenses	researchDevelopment	sellingGeneralAdministrative	totalOperatingExpenses	totalOtherIncomeExpenseNet	totalRevenue	Current price	12/31/2018
1.39156E+11		12421000000	93731000000	11270000000	1197000000	-1417000000		10073000000	10073000000	10073000000	12421000000	296000000	28837000000	52177000000	2.20466E+11	-1151000000	2.32887E+11	1831.35	AMZN
2.04086E+11		61606000000	1.72758E+11	96787000000	16553000000	-5190000000	1.16326E+11	87886000000	87600000000	80234000000	61606000000		37435000000	62990000000	3.15238E+11	35181000000	3.76844E+11	177.78	BABA

### Traceback
```python-traceback
  File "C:\Users\pingl\Documents\Python\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 470, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\Users\pingl\Documents\Python\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.17.0 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
