### ISSUE TITLE
Spyder wont't launch since the first time I tried to open

### ISSUE THREAD

**Issue by Vitor050291** [spyder-ide/spyder#10193]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. When I try to open Spyder an error windows shows up saying "Python stopped working"
No matter if I open trhough anaconda interface or anaconda prompt
Jupyter works normally
My computer is a Xiaomi laptop, not DELL.

### What is the expected output? What do you see instead?
Spyder running normally

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0 beta (update to fourth version trying to solve the problem. Before it was 3.3.6)
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

```

**Comment by ccordoba12** [comment]
Please open an Anaconda Prompt, execute on it

    spyder

and post any error messages that appear there.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
