### ISSUE TITLE
Files created with spyder have mixed end of line characters

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#102]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2009-10-26T23:47:33Z_

I have a file which I created with spyder, and only edited with spyder. 
When I re-open it with spyder, I get a message saying that it contains
mixed end of line characters, and asking me if I would like to fix it. 
This suggests that either spyder is creating mixed line end characters, or
something is wrong with the mixed characters detection.

I am running under windows and have spyder left on the default windows line
end character setting.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=102_

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2009-10-26T22:04:51Z_

PS: I checked the file in question with a hex editor.  It seems that at the end of
one line there was a line-feed (\n 0x0a) without an accompanying carriage return (\r
0x0d).  But every other line was okay.  So probably there is a small glitch somewhere
in some particular case of editing/deleting or whatever... I can't remember exactly
what I did with this file whilst I was editing it!

**Comment by spyder-issues-migrator** [comment]
_From [DavidAnt...@gmail.com](https://code.google.com/u/108698404730356683634/) on 2009-10-26T22:29:58Z_

Hmmm, okay, I think I figured out the cause.  The line in question was one that I had
pasted into spyder from a web page.  So perhaps spyder is just doing its job and this
isn't really a bug.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2009-10-28T13:05:44Z_

I think it does indeed. I even reimplemented the "paste" method for QsciScintilla and
QTextEdit widgets: the native method is replacing EOL chars by only line feeds even
on Windows... I don't know why actually but I replaced these by the right OS-related
EOL chars.

**Status:** Invalid

**Comment by boardtc** [comment]
Why was this closed?

When I run the following code and open the resultant csv file in Spyder I get the message: "<file_name.csv contains mixed end-of-line characters. Spyder will fix this automatically. On clicking OK blanks lines are inserted between each output line

> with open('employee_birthday.csv', mode='w') as csv_file:
>         fieldnames = ["name","department","birthday month"]
>         csv_writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
>         csv_writer.writeheader()
>         csv_writer.writerow({"name":"Bob One", "department": "Finance", "birthday month": "October"})
>         csv_writer.writerow({"name":"Alice Two", "department": "HR", "birthday month": "April"})

There is nothing I can write to the file different to avoid this message?    
So people should avoid opening the .csv files in Spyder?
