### ISSUE TITLE
Cannot launch anything in Anaconda Navigator

### ISSUE THREAD

**Issue by Amandasunny** [spyder-ide/spyder#10201]
### Issue Report Checklist

* [√ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [√ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [√ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ √] Tried basic troubleshooting (if a bug/error)
    * [√ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [√ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ √] Tried the other applicable steps from the Troubleshooting Guide
* [√ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just downloaded Anaconda 3.7 version, but when I opened the Anaconda Navigator, all the items cannot be launched. I tried several times to uninstall and reinstall the software but nothing changed. 

### What steps reproduce the problem?

1. rebot the laptop
2. uninstall the Anaconda
3. reinstall the Anadonca

### What is the expected output? What do you see instead?
I expected that all items could run properly but actually they couldn't.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
```json
[
    {
        "level": "ERROR",
        "line": 234,
        "message": "Invalid url https://www.anaconda.com/wp-content/uploads/2017/05/Webinar20-20Three20Ways20to20Move20your20Data20Science20Projects20to20Production.png",
        "method": "_download",
        "module": "download_api",
        "path": "C:/Users/Amanda/python/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2019-09-15 14:43:53,879"
    }
]
```
```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 3.3.6
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
Soory, there is no Dependencies in the version.
```

**Comment by ccordoba12** [comment]
Please report this problem here:

https://github.com/ContinuumIO/anaconda-issues/issues
