### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by venkatm-95** [spyder-ide/spyder#10213]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Not able to view variable in variable explorer even when they are float or int in spyder, please fix the bug

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
