### ISSUE TITLE
Minimal pyxdg version not set in setup.py

### ISSUE THREAD

**Issue by MuellerSeb** [spyder-ide/spyder#10214]
Hey there,

After installing spyder4.0b5, it complained about the xdg version (which was 0.25 in my case, and it wanted at least 0.26).

Maybe this could be set in the setup.py:

https://github.com/spyder-ide/spyder/blob/ac379b34028e009d523c00f7394489469e35a0ab/setup.py#L236

Cheers,
Sebastian

**Comment by ccordoba12** [comment]
@steff456, please take care of this one by adding 0.26 as the minimal required version in our `setup.py`.
