### ISSUE TITLE
Kite completions ordering is not respected

### ISSUE THREAD

**Issue by metalogical** [spyder-ide/spyder#10227]
## Problem Description

Kite completions ordering is not respected

1. start Spyder in debug mode with Kite installed & running
2. type the following
```python
import numpy as np

np.ar‸
```
3. backspace and type `r` repeatedly until Kite completions show up (see #10226 )

![Screen Shot 2019-09-16 at 4 36 08 PM](https://user-images.githubusercontent.com/1977419/65000354-1dedc700-d8a0-11e9-9c16-697d2b849255.png)

These completions appear to be sorted alphabetically, but the Kite response shown in the debug logs has `array(...)` as the first completion, which is much better, since `array` is much more likely to be called based on usage frequency.

**Comment by ccordoba12** [comment]
> These completions appear to be sorted alphabetically

That's right, they are sorted alphabetically.

> array is much more likely to be called based on usage frequency.

I think we need to introduce a new sorting criteria and use it when Kite is enabled.

@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
I'll take a look at it, we have several manually introduced "z" characters on our gather routine
