### ISSUE TITLE
None value

### ISSUE THREAD

**Issue by halidziya** [spyder-ide/spyder#10222]
I am not really sure about the reason, but variable node becomes None and raises an exception here. 
I suspect code completion is creating this.

https://github.com/spyder-ide/spyder/blob/643bee5627ddf5c95a44d59c9bb5c8557542b333/spyder/plugins/editor/extensions/snippets.py#L327

**Comment by ccordoba12** [comment]
Please post the entire error you're seeing, along with a simple code that generates it. Else, we won't be able to help you, sorry.

**Comment by ccordoba12** [comment]
I was able to reproduce this one, so you don't need to worry about it. We're going to centralize problems like this one on issue #10230.
