### ISSUE TITLE
Selecting a new font in Appearance causes Spyder to crash

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#10228]
### Problem Description

Font setting causes spyder to crash

![TIM图片20190917093017](https://user-images.githubusercontent.com/1759365/65005570-dd8b5900-d932-11e9-8231-acb895570a47.png)

![TIM图片20190917093746](https://user-images.githubusercontent.com/1759365/65005611-fe53ae80-d932-11e9-91a2-eeef80d4ac92.png)

Although the spyder closes and exits, the Python process is not killed.
![image](https://user-images.githubusercontent.com/1759365/65009615-e898b600-d93f-11e9-8040-97fbeb863a79.png)

Subsequent problems is #10229 
## Versions

* Spyder version: 4.0.0b5
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win7

**Comment by ccordoba12** [comment]
This probably happens because you have fonts with Chinese characters on its name.

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one: install a font whose name contains Chinese characters on Windows and try to see if you can reproduce this.

**Comment by steff456** [comment]
> @steff456, please take a look at this one: install a font whose name contains Chinese characters on Windows and try to see if you can reproduce this.

I download three fonts that contain Chinese and Korean characters on Windows but I cannot reproduce the issue, even changing spyder language to Chinese.

**Comment by ccordoba12** [comment]
Thanks @steff456! Maybe this problem happens if your Windows versions is in Chinese too, but we don't have the means to test that, sorry.

**Comment by ccordoba12** [comment]
@leavor, could you remove your fonts with Chinese characters and try again? Maybe that could help.

**Comment by leavor** [comment]
> @leavor, could you remove your fonts with Chinese characters and try again? Maybe that could help.

There are too many fonts,
![image](https://user-images.githubusercontent.com/1759365/65210280-37c02180-dacd-11e9-8bef-77300c9bdaae.png)

 I don't know which one I need to delete, and when I delete it, I am prompted that this font is protected by the system and cannot be deleted.
I put my font library on the cloud disk, I am not sure if this will provide a little help.
the address is as follows:

https://pan.baidu.com/s/1Z9og-tFCe6-OVVwWe7ZIjQ

extract code: lkqg

**Comment by ccordoba12** [comment]
I don't think the problem has to do with Chinese fonts specifically, but with a combination between those fonts and a Chinese version of Windows.

So thanks for the link, but we're going to pursue this further because we don't have a way to install a Chinese version of Windows.

**Comment by lhalb** [comment]
I have the same problem with a german version of Windows 10. 

When I start the App via the "start.py" Script, I get the following Error Message: 

QWidget::repaint: Recursive repaint detected
DirectWrite: CreateFontFaceFromHDC() failed (Gibt einen Fehler in einer Eingabedatei an, zum Beispiel eine Schriftartdatei.) for QFontDef(Family="MS Serif", pointsize=12, pixelsize=20, styleHint=5, weight=50, stretch=100, hintingPreference=0) LOGFONT("MS Serif", lfWidth=0, lfHeight=-20) dpi=120
QBackingStore::endPaint() called with active painter on backingstore paint device

![Error](https://user-images.githubusercontent.com/35839167/66741664-4bfe0100-ee76-11e9-9668-b21a52cdf84c.jpg)

**Comment by ccordoba12** [comment]
@lhalb, thanks for the error message. This looks like a bug in Qt itself.

Could you please update to PyQt 5.12 and try again? Maybe this bug is fixed in that version.

**Comment by haidernab** [comment]
Was this solved? I just intalled spyder 4 and experiencing the same issue. It crashes at the font selection drop down.

**Comment by goanpeca** [comment]
@haidernab could you provide details? os qt version etc?

**Comment by jnsebgosselin** [comment]
@ccordoba12 @goanpeca I think this is the same bug I've reported in https://github.com/spyder-ide/spyder/issues/10893.

So there is indeed a Qt bug with fonts on Windows (see https://bugreports.qt.io/browse/QTBUG-57180), which causes a harmless warning for some fonts that are not scalable.

The crash however is due to a bug with the internal console when it tries to paint this harmless message.

**Comment by ccordoba12** [comment]
Duplicate of #10893
