### ISSUE TITLE
python venv autocompletion in editor not working

### ISSUE THREAD

**Issue by karenc3** [spyder-ide/spyder#10231]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm using the latest beta version for Spyder v4.0.0b5. I've installed spyder using pip in my base python environment with the command: 
`pip install --pre -U spyder`
I've create a virtual environment using `python -m venv <env-name>` and followed the instructions that can be found [here](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder). I've also installed the latest version of PyQT in the `vene` because I read on SO that either `pyqt` or `pyside` were required for auto completion.

Issue: Editor auto completion is not working

I'm deleting the rest of the template since it is not relevant here

## Versions

* Spyder version: 4.0.0b5
* Python version: 3.7.4
* Qt version: 5.13.1
* PyQt version: 5.13.1
* Operating System name/version: Windows 10

### Installed packages
```
# pip freeze output
astroid==2.2.5
backcall==0.1.0
certifi==2019.9.11
chardet==3.0.4
cloudpickle==1.2.2
colorama==0.4.1
decorator==4.4.0
ez-setup==0.9
idna==2.8
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.1
jupyter-client==5.3.2
jupyter-core==4.5.0
lazy-object-proxy==1.4.2
mccabe==0.6.1
nltk==3.4.5
numpy==1.17.2
oauthlib==3.1.0
pandas==0.25.1
parso==0.5.1
pickleshare==0.7.5
prompt-toolkit==2.0.9
Pygments==2.4.2
pylint==2.3.1
PyQt5==5.13.1
PyQt5-sip==4.19.19
pysentiment==0.2
PySocks==1.7.0
python-dateutil==2.8.0
pytz==2019.2
pywin32==225
pyzmq==18.1.0
requests==2.22.0
requests-oauthlib==1.2.0
six==1.12.0
spyder-kernels==1.5.0
textblob==0.15.3
tornado==6.0.3
traitlets==4.3.2
tweepy==3.8.0
typed-ast==1.4.0
urllib3==1.25.3
wcwidth==0.1.7
wrapt==1.11.2
```

I've gone through several similar issues here: #5462, #5782, #8289
Is kite integration not available in the v4 beta?

**Comment by ccordoba12** [comment]
> I've also installed the latest version of PyQT

We dom't support the latest version of PyQt. The last version we support is 5.12.

> # pip freeze output

You don't have installed the python-language-server among your dependencies, which is the package that provides code completion for the editor.

----

Sorry, but I'm closing this one because I don't understand how you ended up with an incomplete installation and we don't have time to help you with that.

If you're really new to Python, please use Anaconda instead, which is far simpler and easier to use.

**Comment by ccordoba12** [comment]
Sorry, I guess you're not getting code completion for the packages in your virtualenv (something which is not mentioned in your issue description but I understood after reading your title).

If that's the case, then this is known problem and we'll try to fix it for the final release of Spyder 4.

Again, sorry for the confusion.

**Comment by karenc3** [comment]
> Sorry, I guess you're not getting code completion for the packages in your virtualenv

My bad! I should have framed the issue better.  Thank you. That is exactly what I was looking for!

> final release of Spyder 4

I read this in one of the issues here. I thought the feature will be rolled out in the beta version itself.

Just for clarification: I have installed spyder using in my base python so that I don't need to install it in every venv that I create. I read this [here](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach)

**Comment by ccordoba12** [comment]
> Just for clarification: I have installed spyder using in my base python so that I don't need to install it in every venv that I create

Yes, that's exactly the workflow we're trying to nudge our users to adopt.

> I thought the feature will be rolled out in the beta version itself.

Not yet. Please see issue #7724 for the things that we to finish regarding code completion.
