### ISSUE TITLE
using tweepy API

### ISSUE THREAD

**Issue by Makuei-Deng** [spyder-ide/spyder#10232]
#output error 401
  File "C:\Users\Mak\Anaconda3\lib\site-packages\tweepy\streaming.py", line 281, in _run
    sleep(self.retry_time)

KeyboardInterrupt

**Comment by ccordoba12** [comment]
Sorry but this doesn't seem to be a problem with Spyder.

**Comment by Makuei-Deng** [comment]
Thanks it was due to Twitter time zone difference....I hope it works.will
do it in a few minutes.
