### ISSUE TITLE
Trailing spaces are being removed on line change even if the option is unset in preferences

### ISSUE THREAD

**Issue by odinsbane** [spyder-ide/spyder#10248]
## Problem Description

In the editor, if I move down from an indented line to another indented line, then move back up, the line above is no longer indented.

I tried to  disable the option "automatically strip trailing spaces on changed lines" in preferences->editor->source code, but the spaces are still removed.

### What steps reproduce the problem?

1. Create a new function.
2. Press enter to go to the next line, which should be indented.
3. Press enter again, to go to a second indented line.
4. Press up to move back up to the previous line, and it is no longer indented and no longer contains any spaces.

### What is the expected output? What do you see instead?

I dont expect the first lines to lose their indentations. If I add "show spaces" I can see the first line losses it's indentations when I press return the second time. I would like.

```
def main():
    
    
```
(The spaces are there, but I am not sure of a good way to show them on this interface.)

Quite possibly, I am not setting/unsetting the correct option.

## Versions
Spder 4.0.0b5

Python 3.6.8 64-bit  
Qt 5.12.4  
PyQt5 5.12.3  
Linux 3.10.0-1062.el7.x86_64
Centos 7

**Comment by bcolsen** [comment]
@odinsbane Thank you for the testing out Spyder beta!

This is a known issue documented on #10146, but I'll leave this issue open as it is more directly about the setting.

**Comment by ccordoba12** [comment]
@odinsbane, thanks for reporting. I agree this is a valid concern, so I fixed it myself.
