### ISSUE TITLE
Could not launch the spyder3 in terminal command.

### ISSUE THREAD

**Issue by Ethan-LWT** [spyder-ide/spyder#10242]
### Issue Report Checklist

* [x] Reproduced the issue after updating with ``pip-review --local --interactive`` 
* [x] Could not open the sypder3

## Problem Description

After the pip-review --local --interactive command has been done, the sypder3 could not launch.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

Message form MacOS:
Traceback (most recent call last):
  File "/usr/local/bin/spyder3", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/spyder/app/start.py", line 178, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_spyder_kernels()
  File "/usr/local/lib/python3.7/site-packages/spyder/requirements.py", line 66, in check_spyder_kernels
    % actual_ver)
  File "/usr/local/lib/python3.7/site-packages/spyder/requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels < 1.0 is required (found 1.5.0).

Message form Windows:
ERROR: spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.13.1 which is incompatible. 
ERROR: spyder 3.3.6 has requirement pyqtwebengine<5.13; python_version >= "3", but you'll have pyqtwebengine 5.13.1 which is incompatible. 
ERROR: spyder 3.3.6 has requirement spyder-kernels<1.0,>=0.5.0, but you'll have spyder-kernels 1.5.0 which is incompatible.
```

## Versions

* Spyder version: 3.3.6
* Spyder-kernels: 1.5.0
* Python version: 3.7.4
* PyQt version: 5.13.1
* Operating System name/version: MacOS 10.14.6 & Microsoft Windows [Version 10.0.18362.356]

**Comment by ccordoba12** [comment]
> ERROR: spyder 3.3.6 has requirement pyqt5<5.13; python_version >= "3", but you'll have pyqt5 5.13.1 which is incompatible. 
ERROR: spyder 3.3.6 has requirement pyqtwebengine<5.13; python_version >= "3", but you'll have pyqtwebengine 5.13.1 which is incompatible. 
ERROR: spyder 3.3.6 has requirement spyder-kernels<1.0,>=0.5.0, but you'll have spyder-kernels 1.5.0 which is incompatible.

Please read the messages, I think they are clear enough. You need to manually fix the versions of the packages mentioned above for things to work correctly.
