### ISSUE TITLE
Spyder 'crashes' when running script

### ISSUE THREAD

**Issue by estherroosenbrand** [spyder-ide/spyder#10267]
When importing data (through netCDF's Dataset) my script periodically 'crashes'. This entails the variable explorer beging cleared and the red square in the python console being there for eternity. I've run import script before, with a larger amount of data to be imported, and it's worked fine. It periodically did this crashing behaviour at that time too. 
Now however, I can't get it to run at all. I've updated my conda and my netCDF. No errors show up in the console when clicking on the red square.
Suggestions are very much welcome!
Thanks!

**Comment by ccordoba12** [comment]
I'm sorry for not being able to help you but this is not a problem with Spyder but with netCDF, so I'm afraid I'm going to close this one.
