### ISSUE TITLE
No documentation shown even though Kite returns docs

### ISSUE THREAD

**Issue by plungg** [spyder-ide/spyder#10265]
## Problem Description

Documentation for some functions are not shown, even though the debugger shows a response is received from Kite. 

### What steps reproduce the problem?

1. Run Spyder in debug mode `python bootstrap.py --debug`
2. Type `import numpy as np`
3. Have cursor on numpy
4. Cmd+I, shows "no further documentation available"
Debug shows that Kite provides documentation in the response.
![image](https://user-images.githubusercontent.com/5544312/65277178-34816180-dade-11e9-85de-589d6b05c182.png)

### What is the expected output? What do you see instead?
I expect to see documentation from Kite.

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: f1e18174d)
Python 3.7.4 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Darwin 18.6.0 
* Operating System name/version: Mac OS Mojave

**Comment by ccordoba12** [comment]
@metalogical, @its-dhung, is the Kite copilot supported on Linux?

**Comment by metalogical** [comment]
Yes, the Kite Copilot is supported on macOS, Windows, and Linux.

**Comment by ccordoba12** [comment]
Thanks @metalogical!

@plungg, Kite's documentation is shown on its own Copilot window, not in our Help pane for now.

@andfoy, I think we could use Kite's docs and send them to our Help pane. What do you think?

**Comment by plungg** [comment]
@ccordoba12 On our Friday call, did you mention that Kite docs now show in the help pane but you can't repro this issue?

**Comment by ccordoba12** [comment]
@andfoy mentioned that and he showed that the docs for `numpy.linspace` are shown in our Help pane by Kite (they are not available through the LSP).

**Comment by plungg** [comment]
@andfoy if this issue no longer repros, please close

**Comment by ccordoba12** [comment]
Closing then.
