### ISSUE TITLE
Autocomplete introduces code snippet in import statement

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10276]
### What steps will reproduce the problem?

In an empty editor with 'show completions on the fly' turned off, enter

    from collections import defa

With the cursor after the a in 'defa' press tab to autocomplete the import (I'm trying to import defaultdict).

The autocomplete reads

    from collections import defaultdict(default_factory, iterable, kwargs)

whereas it should read

    from collections import defaultdict
   
The same happens with 'show completions on the fly' turned on, it is just in that case you can see what would be inserted. 

## Versions

* Spyder version: 4.0.0b5 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by goanpeca** [comment]
@andfoy thoughts?

**Comment by andfoy** [comment]
That is strange, LSP shouldn't respond with snippets on import statements, I think we need to check that on pyls

**Comment by ccordoba12** [comment]
Until this problem is fixed in the PyLS, we need to deactivate code snippets on it.

**Comment by Keou0007** [comment]
I have a similar issue with autocomplete entering the wrong thing frequently and consistently, but nothing to do with snippets.

I type, for example:
`import re` hit return and I get `import return`
`import glob` i get `import global`

IMHO I don't think the return key should accept an autocomplete. The return key has a well defined function and it shouldn't be changed in normal typing.

**Comment by ccordoba12** [comment]
> IMHO I don't think the return key should accept an autocomplete. The return key has a well defined function and it shouldn't be changed in normal typing.

This was already fixed in master by waiting a little bit before showing the completion options. It'll be part of our next beta.
