### ISSUE TITLE
why issue reported popup manytimes while using spyder ?!

### ISSUE THREAD

**Issue by hmae** [spyder-ide/spyder#10279]
### What steps will reproduce the problem?

[1] Just when clicking on a file [left click] to open it in editor.
    from the file viewer sidebar .. on my left. [Project Folder]
[2] suddenly [Issue Reporter] Appeare !

# Note:
    [] this problem happened many times before.
       i thought it is due to my clicks .. but now ..
       it is a weird thing while writing my CODE ;( .
    [] there is another problem i dont know what it is actually.
        [] when pressing SHIFT+END ..
        [] this should select characters of the line to the end.
        [] but i feel like lag or something ..
        [] i should press manytimes on END key ..
        [] i thought this due to Hight Memory Usage .. ;D
        [] i noticed, it can happened just when working on spyder

# LAST ..
   sorry for my english . much to say .. but thank you for this software i love spyder environment [anaconda].
   many options to test.

# goals ..
   I hope i can arrange ui by myself, 
   drag items there and here .. etc.
   colors are awesome, but i faced some lag when applying themes.
   is that normal thing !?

Thank YOU ^_^
   hmae.py

### Traceback
```python-traceback
    self.process_code_analysis(params['params'])
    self.cleanup_code_analysis()
    self.setUpdatesEnabled(False)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

Traceback (most recent call last):
    msg = self.format(record)
    return fmt.format(record)
    record.message = record.getMessage()
    msg = msg % self.args
ValueError: incomplete format
Call stack:
    sys.exit(main())
    mainwindow.main()
    mainwindow = run_spyder(app, options, args)
    app.exec_()
    handler(resp['params'])
    {'params': diagnostics})
    handler(params)
    self.log_lsp_handle_errors("Error when processing linting")
    logger.error('%', 1, stack_info=True)
Arguments: (1,)
Traceback (most recent call last):
  File "C:\Users\hmae\Anaconda3\envs\myenv\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 319, in on_msg_received
    handler(resp['params'])
  File "C:\Users\hmae\Anaconda3\envs\myenv\lib\site-packages\spyder\plugins\completion\languageserver\providers\document.py", line 41, in process_document_diagnostics
    {'params': diagnostics})
  File "C:\Users\hmae\Anaconda3\envs\myenv\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 842, in handle_response
    self.lsp_response_signal.emit(method, params)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.6.9
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  v0.28.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.5.2 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This error was fixed in beta5, please update.

**Comment by ccordoba12** [comment]
I meant this error:

> RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

**Comment by ccordoba12** [comment]
> colors are awesome, but i faced some lag when applying themes.
is that normal thing !?

Yes, that's normal. We're working to improve it in a future release.
