### ISSUE TITLE
Request: Make "toggle comment" function comply with PEP 8

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#10271]
Spyder has three comment functions, the simple "toggle comment" one only inserts a # without a space afterwards, so everytime this is used the PEP 8-checker complains about it.

Requesting the "toggle comment" function to insert `# ` with a trailing space instead of `#`.

Spyder Version 3.3.6

**Comment by ccordoba12** [comment]
Thanks for reporting. This was already solved and it'll be part of Spyder 4.
