### ISSUE TITLE
I can't use auto completion

### ISSUE THREAD

**Issue by astroamirreza** [spyder-ide/spyder#10285]
## Description

I think my settings are correct and it problem is a new unfixed bug, I can not use auto completion and more with Ctrl + Space in the spyder 3 editor, not console. please fix this bug or help me.

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.9.4-1 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```
### screenshots (Settings)
![Screenshot (1)](https://user-images.githubusercontent.com/52854984/65390181-aa4d2d80-dd69-11e9-965e-2e5598e26fbd.png)
![Screenshot (2)](https://user-images.githubusercontent.com/52854984/65390182-aae5c400-dd69-11e9-82c8-4cc0e97a7b12.png)
![Screenshot (3)](https://user-images.githubusercontent.com/52854984/65390183-aae5c400-dd69-11e9-9bc7-f266baf0ff4f.png)

### screenshot (Packages)
![Screenshot (4)](https://user-images.githubusercontent.com/52854984/65390255-31020a80-dd6a-11e9-8625-c92879c5c080.png)

Thanks.

**Comment by astroamirreza** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/52854984/65390161-84c02400-dd69-11e9-947a-4a067b8d6581.png)
![Screenshot (2)](https://user-images.githubusercontent.com/52854984/65390162-8558ba80-dd69-11e9-84c1-625c49cb5695.png)
![Screenshot (3)](https://user-images.githubusercontent.com/52854984/65390163-8558ba80-dd69-11e9-92fc-ee1ade13fb02.png)

**Comment by ccordoba12** [comment]
This is (most probably) going to be fixed in Spyder 4, to be released in a month or so. In the meantime, you can take a look at #5782.
