### ISSUE TITLE
spyder-kernels < 1.0 is required (found 1.4.0)

### ISSUE THREAD

**Issue by shuntera** [spyder-ide/spyder#10297]
Trying to launch Spyder via Anaconda Navigator and I get a dialog pop up with the following error at the end:

spyder-kernels < 1.0 is required (found 1.4.0)

**Comment by goanpeca** [comment]
@shuntera please open the `anaconda prompt` and run the following command and try again.

```
conda install spyder-kernels=1.4 -c spyder-ide
```

**Comment by ccordoba12** [comment]
@shuntera, it's the other way around because it seems you have Spyder 3 installed. So the command you need to run is

    conda install spyder-kernels=0.*

**Comment by goanpeca** [comment]
Oops, I misread 🤦‍♂

**Comment by ccordoba12** [comment]
No prob :+1:
