### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ZihanRen** [spyder-ide/spyder#10295]
Spyder has encountered an internal problem
I can't see variables in variable explorer
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by goanpeca** [comment]
@ZihanRen please fill in the issue template that was there when you opened the issue

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

@goanpeca, this problem was caused by our incorrect usage of Numpy's internal API but it was fixed several months ago.

**Comment by goanpeca** [comment]
>@goanpeca, this problem was caused by our incorrect usage of Numpy's internal API but it was fixed several months ago.

Got it!
