### ISSUE TITLE
Deleting line when breakpoint it set causes crash

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10290]
### What steps will reproduce the problem?

Put the following in an empty editor(yes, the indentation is meant to be incorrect, it's not a typo)

    def truth_vs_stuff(truth, stuff):
        for t in truth:
        pass
    
    
    truth_vs_stuff([3], [4])

Put a breakpoint on `pass`. Press the start debugging button. You get an IndentationError exception as expected.

Go delete the line `for t in truth' by selecting it and using the delete key. This tends to create this crash. Sometimes I have to press delete a few times before it crashes. I can get the same crash in other ways, such as adding the breakpoint after running and getting the exception, but I figure all the various permutations are due to the same bug.

I don't know if the indentation error has anything to do with the crash; it is just what caused me to first find this error. 

### Traceback
```python-traceback
Exception in comms call set_breakpoints:
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 330, in _handle_remote_call
    buffer['call_kwargs'])
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 341, in _remote_callback
    *call_args, **call_kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 104, in set_spyder_breakpoints
    self._pdb_obj.set_spyder_breakpoints(breakpoints)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 380, in set_spyder_breakpoints
    lineno = frame.f_lineno
AttributeError: 'NoneType' object has no attribute 'f_lineno'
```

## Versions

* Spyder version: 4.0.0b5 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this one?

**Comment by impact27** [comment]
I can't reproduce, but my guess is:
running debugfile with indentation error causes `SpyderPdb.starting` to be set to true, but the debugging ends before `SpyderPdb.starting = False` is executed because of the syntax error.

When trying to modify a breakpoint, SpyderPdb.starting is still true but we are not debugging, so self.curframe is false.
