### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by aumkiran** [spyder-ide/spyder#10307]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Please do your magic. Kernel doesnot load on starting Sypder.
Please fix this issue Sypderman. Thank you

**Comment by ccordoba12** [comment]
> Please do your magic

We can help you if you don't care to upload the error you're seeing on your side.

So please upload a screenshot or the text of the error here.

**Comment by aumkiran** [comment]
Thank you very much for your message and support. :)
Please see attached images for error screenshots
![1_Connecting_Kernel](https://user-images.githubusercontent.com/36146370/65810139-72345900-e174-11e9-9340-168fb4e14f56.JPG)
![2_Connecting_Kernel](https://user-images.githubusercontent.com/36146370/65810142-7a8c9400-e174-11e9-8953-fce680c29756.JPG)

**Comment by ccordoba12** [comment]
You need to run

    pip install pywin32

to fix this problem.
