### ISSUE TITLE
Annoying regular (2/4 sec) sending of newlines to console when using external kernel

### ISSUE THREAD

**Issue by liar666** [spyder-ide/spyder#10315]
### Issue Report Checklist

* [ X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ NO] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ X] Tried basic troubleshooting (if a bug/error)
    * [ X] Restarted Spyder
    * [ X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Some carriage return chars get regularly sent to the Console/Ipython external kernel.

It does not occur with the console started by Spyder

### What steps reproduce the problem?

1. I start an external kernel with
source ~/My/VenV/bin/activate #activates my venv, which contains lots of up-to-date data science packages
ipython3 kernel  # starts the external kernel

2. I connect spyder to this external using "connect to external kernel" then selecting the correct ~/.local/share/jupyter/runtime/kernel-xxx.json file

3. The kernel automatically receives carriage returns every 2/4 sec...

So, if I try to type an expression (e.g. "151//2"), then the first characters (e.g. "15") get "validated" (but not send to the kernel?!) before I could type the rest of the expression...

Also, this generates MANY useless empty entries which make the "kernel"
 tab very difficult to read and MOST IMPORTANTLY crashes Spyder3 (at least when let a few hours without any activity)...

### What is the expected output? What do you see instead?

There should not be any carriage return sent automatically to the console

## Versions

Spyder 3.3.2 (XUbuntu package) & Spyder 3.3.6 (installed in venv with pip)
Python 3.7.3 64-bit | Qt 5.12.2 | PyQt5 5.12.1 | Linux 5.0.0-29-generic 

### Dependencies

```
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.17.2 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.1 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  None (NOK)
```

Following video demontrates the problem (only moment I type enter is when you see the Out[2]. Other carriage returns are automagically inserted...)
![2019-09-27 14-34-56](https://user-images.githubusercontent.com/3216927/65769768-b869c800-e134-11e9-9423-82d644e8969e.gif)

**Comment by liar666** [comment]
For the sake of completeness, I've just tested with a fresh/empty venv (i.e. without the hundreds of DS packages I have in the venv used in the previous post) and it also occurs

**Comment by liar666** [comment]
Just tested with a "jupyter console" connected external kernel. Apparently the kernel crashes regularly, that's the source of the line refreshes...

**Comment by ccordoba12** [comment]
Please select the interpreter of your environment in

     Preferences > Python interpreter

and try again. That could help.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by mariopaolucci** [comment]
Hello,

I have the exact same issue using spyder3 3.3.6 (on a mac) with server on python 3.7.3.

I'm reading ccordoba's answer but I have nothing to select on Python interpreter. What should I type there? The path to the executable on the kernel machine?

**Comment by gyshion** [comment]
Hi @ccordoba12 ,
Same issue again.
spyder 3.3.6 on win10, and python 3.7.4 on server.

what should I do after " Preferences > Python interpreter"?
