### ISSUE TITLE
unexpected closure 

### ISSUE THREAD

**Issue by ShrutiCRC** [spyder-ide/spyder#10310]
### What steps will reproduce the problem?

The Spyder just hangs and closes automatically while i am working on it and code bcomes a little longer

### Traceback
```python-traceback
  File "C:\Users\s.gaur\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor\panels\debugger.py", line 122, in mouseMoveEvent
    event)
  File "C:\Users\s.gaur\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1598, in get_linenumber_from_mouse_event
    scope = FoldScope(block)
  File "C:\Users\s.gaur\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\editor\utils\folding.py", line 69, in __init__
    raise ValueError('Not a fold trigger')
ValueError: Not a fold trigger
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please post a simple code example that generates this error when you try to fold it. Otherwise we can't fix this error, sorry.

**Comment by craigmau** [comment]
Experiencing the same issue, latest 3.x version, quit suddenly frequently. Annoying.

**Comment by ccordoba12** [comment]
@craigmau, version 3.x does't have folding.

----

Closing due to lack of response.

**Comment by craigmau** [comment]
> @craigmau, version 3.x does't have folding.
> 

I don't know what reason. But it crashes suddenly and quite frequently.
