### ISSUE TITLE
Spyder uses old versions of Scipy

### ISSUE THREAD

**Issue by aliakbariTAMU** [spyder-ide/spyder#10320]
### Issue Report Checklist

* [ *] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [*] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [*] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ *] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have installed scipy 1.2.1 and the "conda list" shows me the correct version; however, spider imports scipy 1.0.0. I open spyder from Anaconda promt and both Spyder and scipy 1.21 are in the current activated environment (base).

### What steps reproduce the problem?

1. import scipy
    print(scipy.__version__)
2. 
3. 

### What is the expected output? What do you see instead?
I expect the spyder to use version 1.2.1

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.21.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Please read the info in this link:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to understand how to solve this problem.
