### ISSUE TITLE
Editor plugin not raised after selecting file in Switcher

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#10335]
This is relevant for Spyder 4.0.0b5 and master.

As I remember (which may well not be correct), in the old file switcher (before #10060), when selecting a file which is opened in the editor, the editor plugin is raised to the front. This normally does not matter, because the editor plugin occupies a space all by itself. However, it becomes noticeable if the notebook plugin is installed, because now the switcher can be used to switch between files in the editor and the notebook plugin. I think that the editor plugin should raise itself if a file from the editor is selected in the switcher.

**Comment by ccordoba12** [comment]
I agree, thanks for reporting this @jitseniesen!
