### ISSUE TITLE
Spyder working with a virtual environnement python 

### ISSUE THREAD

**Issue by matthiasLevy** [spyder-ide/spyder#10346]
Hi !
I'm facing an issue that makes impossbile to open an ipython console in Spyder... Thanks for your help, and sorry if I made something wrong in the configuration...

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda) Issue appears xith several versions of Spyder, including last release and last beta,
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related) #NA
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Running Spyder with a virtualenv version of python, the connection to kernel in ipython console seems to loop endlessly. 

### What steps reproduce the problem?

1. Installing Anaconda, updating, installing pip, `pip install pipenv`
2. `pipenv install`
3. `conda update qt pyqt`
4. Launching spyder and changing the python interpreter for the one in the virtual env
5. Installing `spyder-kernels` in the virtualenv
6. relaunching the ipython console.

### What is the expected output? What do you see instead?
Instead of launching the console, the "connecting to kernel" loop never ends.

## Versions

* Spyder version:b Python version: 4.0.0.b5 (tried also with 3.6)
* Qt version: 5.9.7
* PyQt version: 5.12.3
* Operating System name/version: Windows X professional updated

**Comment by ccordoba12** [comment]
> pipenv install

You can't mix conda and pip packages because that's a recipe for disaster. You most probably broke your Anaconda installation by doing that, so please uninstall it and reinstall it again.

Besides, please read [our guide](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder) to understand how to work with conda environments (which is really what you need to use, not pipenv).

**Comment by matthiasLevy** [comment]
Hi,

Thanks for your answer. Unfortunately, I work in a team where pipenv is 
used for its dependency management. I installed no conda environment, 
only the virtualenv of pipenv (venv). Isn't there any way of using venv 
python?


signature

*Matthias Lévy*

Tel : +33 9 72 62 23 15
Fax : +33 4 83 07 54 33

www.corsicasole.com <http://www.corsicasole.com/>

www.corsicasole.com
Ce message (et toutes ses pièces jointes éventuelles) est confidentiel 
et établi à l'intention exclusive de ses destinataires.
Toute utilisation de ce message non conforme à sa destination, toute 
diffusion ou toute publication, totale ou partielle, est interdite, sauf 
autorisation expresse.
Internet ne permettant pas d'assurer l'intégrité de ce message, CORSICA 
SOLE et ses filiales déclinent toute responsabilité au titre de ce 
message, s'il a été altéré, déformé ou falsifié.
Le 03/10/2019 à 16:42, Carlos Cordoba a écrit :

**Comment by ccordoba12** [comment]
> I work in a team where pipenv is used for its dependency management

Then you don't need conda at all. Sorry but I really don't understand your use case.

**Comment by matthiasLevy** [comment]
Well, when beginning the project, I had read that lines:

> Spyder installation
> ---
> Installing with pip (experts only)
> Warning
> While this installation method is a viable option for experienced users, installing Spyder (and other SciPy stack packages) with pip can lead to a number of tricky issues. While you are welcome to try this on your own, we unfortunately do not have the resources to help you if you do run into problems, except to recommend you use Anaconda instead.
> 

Now you're right: I started again, installing only python, spyder and a virtual env., and it works perfectly. I can use Spyder again, thanks !

**Comment by ccordoba12** [comment]
> Now you're right: I started again, installing only python, spyder and a virtual env., and it works perfectly

Yeah, that's the point: it's better to use conda or pip, and avoid as much as possible to mix them.
