### ISSUE TITLE
Kite autosearch docs not working on mouse events

### ISSUE THREAD

**Issue by its-dhung** [spyder-ide/spyder#10349]
## Problem Description

With Kite enabled, docs are not automatically displayed in the Kite Copilot on mouse events. However, docs are automatically displayed on keyboard (e.g. arrow key) events.

### What steps reproduce the problem?

1. Open the following file:
```python
import pandas as pd
df = pd.read_csv('csv')
```
2. Open the Kite Copilot and enable "Docs Follow Cursor".
3. In the file above, try clicking on different identifiers e.g. `panads` or `read_csv`.

### What is the expected output? What do you see instead?

__Expected:__ Docs should show up automatically in the Copilot.
__Actual:__ Nothing happens. However, if you use the arrow keys to move the cursor, docs are updated.

![spyder-autosearch-bug](https://user-images.githubusercontent.com/3752225/66146075-e598f900-e5c0-11e9-84ed-18890b1da44a.gif)

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: e362c9525) 
* Python version: Python 3.7.3 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Darwin 18.7.0 

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by andfoy** [comment]
We're not relaying mouse events, aka textDocument/hover requests to Kite

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
@metalogical, do we know which is the call Spyder should be making to Kite on such situation?

**Comment by jjslee** [comment]
Is the kite co-pilot suppose to show documentation while hovering? I see it is showing in Spyder when I hover but it is only appearing in the co-pilot if I click.

**Comment by goanpeca** [comment]
Hi @jjslee. Copilot follows the cursor so that means in this case only clicks, not hovers.

Cheers
