### ISSUE TITLE
Syntax coloring  incorrect with import as statements

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10351]
### What steps will reproduce the problem?

Enter the following in an editor

    import subprocess as subp

Using the dark scheme, the 'import' and 'as' are purple, and 'subprocess' is white, as expected. However, the first 3 characters of 'subp' are purple, and the p in it is white.

This seems consistent - the first 4 characters after 'as' are purple. To illustrate this, put the cursor in between 'as' and 'subp' and insert a space. Now only 'su' is purple, and 'bp' is white. 

## Versions

* Spyder version: 4.0.0b5 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by goanpeca** [comment]
I can reproduce this

![image](https://user-images.githubusercontent.com/3627835/66158932-910b7300-e5ec-11e9-827e-2955e714191b.png)

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one. It's probably cause by an error in our syntax highlighter.
