### ISSUE TITLE
Python sets not supported in variable explorer

### ISSUE THREAD

**Issue by cyogian** [spyder-ide/spyder#10359]
![Spyder](https://user-images.githubusercontent.com/18527186/66259188-ae4a6800-e7cb-11e9-8993-9273cc35476a.png)

The screenshot  explains the problem with the variable explorer.
It is not showing objects of type "set".

Now I know that there are other closed issues about this problem. But all of them say that this issue has been resolved.
But I am getting this issue.
Spyder 3.3.6
I installed spyder packaged with Anaconda3-2019.07-Linux-x86_64.sh.

**Comment by ccordoba12** [comment]
Sets will be supported in Spyder 4, to be released in a month or so.
