### ISSUE TITLE
Error with core connection

### ISSUE THREAD

**Issue by T-hash-alt** [spyder-ide/spyder#10375]
### What steps will reproduce the problem?

trying to install spyder-kernels latest version with Anaconda navigator and trying to solve with the solution proposed at:
https://github.com/jupyter/notebook/issues/4907
but something failed

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
> but something failed

Please post here the error you're seeing.

**Comment by ccordoba12** [comment]
Please run in the Anaconda Prompt

    conda update jupyter_client

That should fix this problem.
