### ISSUE TITLE
Virtual Environment in Python 2.7 "No Qt bindings could be found"

### ISSUE THREAD

**Issue by noahkrever** [spyder-ide/spyder#10377]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide

## Problem Description
I am working on a project requiring python 2.7 in a virtual env called haiman, all was well until spyder started crashing, and now when I try to run it in my env I am getting this issue. I have looked at other threads, and most other fixes I cannot do because of the restrictions of Python 2, or they just haven't worked. Any ideas?

### Paste Traceback/Error Below (if applicable)

```python-traceback

(haiman) C:\Users\noahk>spyder
Traceback (most recent call last):
  File "C:\Users\noahk\Anaconda3\envs\haiman\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\noahk\Anaconda3\envs\haiman\lib\site-packages\spyder\app\start.py", line 159, in main
    from spyder.app import mainwindow
  File "C:\Users\noahk\Anaconda3\envs\haiman\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\noahk\Anaconda3\envs\haiman\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\noahk\Anaconda3\envs\haiman\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

## Versions

* Spyder version: 3.2.8
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Windows 10 Pro/1903

**Comment by ccordoba12** [comment]
How did you install packages in your virtualenv? Using pip or conda?

**Comment by noahkrever** [comment]
I used conda for all ones that I could. Older/more technical packages like astroML, for example, I don’t think had that capability so I used pip.

**Comment by ccordoba12** [comment]
Instead of mixing pip and conda packages (which is most probably the cause of your error), please install Spyder in one environment and the packages you want to use in a different one and connect Spyder to the last env.

To understand how to do that, please follow our guide:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
