### ISSUE TITLE
"Run selected cell" runs whole program

### ISSUE THREAD

**Issue by becks0815** [spyder-ide/spyder#10383]
## Problem Description
Run selected cell not working, instead of the selected/highlighted text the whole program is run.

### What steps reproduce the problem?

1. Mark a part of a python program
2. Either hit cntrl+enter or select "run cell" from the context menu.

### What is the expected output? What do you see instead?
Only the selected portion should be run. Instead, the whole program is run, no matter if the selected cell is at the beginning or the end of a program. 

Ipython shows runcell(0, <programname>) as first line, but not the copy&pasted code block like it is was the case in spyder3.3.x

```

## Versions
* Spyder version:  4.0.0.b5
* Python version: 3.7.0 64 bit
* Qt version: 5.11.2
* PyQt version: 5.11.3
* Operating System name/version: Windows 10

Also tested with:

* Spyder version:  4.0.0.b5
* Python version:  3.6.1 32bit
* Qt version: 5.13.1
* PyQt version: 5.13.1
* Operating System name/version: Windows 7



### Dependencies

cloudpickle >=0.5.0          :  0.5.5 (OK)
pygments >=2.0               :  2.2.0 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.3.1 (OK)
sphinx >=0.6.6               :  1.7.8 (OK)
pylint >=0.25                :  2.1.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.4 (OK)
zmq >=17                     :  17.1.2 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.8.0 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.3.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)

**Comment by bcolsen** [comment]
I think you are looking for "Run selection or current line" found in the run menu and the toolbar (shortcut `F9`). This will run only the selected text in the editor or the current line if no text is selected.

As for the use of code cells please see the Documentation for usage notes. Try them out. You'll might like using them. The names of the code cells even appear in the outliner.

https://docs.spyder-ide.org/editor.html#defining-code-cells

I'm going to close this issue, but let me know if this doesn't work for you.
