### ISSUE TITLE
Used F8 to analyze, then hit Analyze button

### ISSUE THREAD

**Issue by arborescere** [spyder-ide/spyder#10389]
### What steps will reproduce the problem?

I had the editor in focus and pressed F8 to perform a static analysis. the text box which holds the filepath to the file or package to be analyzed became empty; I shifted focus back to the editor and tried F8 again to no avail. I then clicked the Analyze button in the static code analysis pane, and this internal problem dialogue was raised.

The file I was analyzing is only 18 lines in length and had previously analyzed at 10.00/10. I added an un-named variable "BLAH" to the last line before my initial press of the F8 key, because I had not used the keyboard shortcut before and wanted to verify that it worked. I guess it may not.

### Traceback
```python-traceback
KeyError: None

WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
I think this is already fixed in master, and it'll be part of our next major version (Spyder 4), to be released in a month or so.

Please post again here after Spyder 4 is released if that's not the case.

**Comment by arborescere** [comment]
Thanks Carlos! It was working great for me a minute ago, I’ll keep you posted.

Kind regards,
Maxwell
