### ISSUE TITLE
  how are you able to open small windows when you click the variables In the variable explorer?

### ISSUE THREAD

**Issue by alpaylamar** [spyder-ide/spyder#10394]
Non full screen:  whenever I try to click a variable and 1variable window opens up, if I try to open another, the first one goes below Spyder so that I can't see it. I can't have more than 1 minimized variable windows open in Spyder unlike in the video.

Full screen: if I press a variable it opens in a completely new full screen window that I can't minimize

MacOS Catalina

**Comment by alpaylamar** [comment]
![IMG_1112](https://user-images.githubusercontent.com/54598735/66720234-c856fc80-ee02-11e9-9804-333533271fd1.PNG)

First picture is how I need it to look


second picture Is how it looks for me
<img width="1680" alt="Screenshot 2019-10-13 at 21 46 34" src="https://user-images.githubusercontent.com/54598735/66720246-f0466000-ee02-11e9-88d4-0dbb2d73af51.png">

**Comment by ccordoba12** [comment]
Thanks for reporting. I think this will be fixed in Spyder 4, to be released in a month or so.

If that's not the case, please report back in this issue.

**Comment by mexiQQ** [comment]
It still doesn't work
