### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by HuihuiYangshell** [spyder-ide/spyder#10397]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
if the code is:
y_train = np.random.randint(2, size=(1000, 1))
I can not open y_train;

but if the code is:
y_train = np.random.randint(2, size=(100, 1))
it works fine.

I think maybe it is the problem of the lenth, and why?

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
