### ISSUE TITLE
No completions returned from Kite after unicode emoji

### ISSUE THREAD

**Issue by metalogical** [spyder-ide/spyder#10401]
## Problem Description

```
json.loa # returns completions
send_message("user","😒")
json.loa # does not return completions
```

I suspect this is because Spyder does not correctly handle communicating about unicode with Kite.

Kite accepts a top-level `offset_encoding` parameter in the completions request JSON. This indicates whether the offset are counting utf-32 code units (4-byte sequences), utf-16 code units (2-byte sequences), or utf-8 code units (bytes). The default is utf-8.

It looks like this parameter is sent as `utf-32` for signature requests, but no other Kite requests.

### What is the expected output? What do you see instead?

Kite should return completions for both of the cases described above.

**Comment by ccordoba12** [comment]
@metalogical, bugs reported by you or other guys from the Kite team are expected to be handled by the Kite team, right?

**Comment by metalogical** [comment]
In this case, feel free to assign to me. In general, I think it'll depend on the nature of the bug (but this should be easy for us to fix).
