### ISSUE TITLE
Permission problems with macOS Catalina

### ISSUE THREAD

**Issue by josequinonez** [spyder-ide/spyder#10406]
### What steps will reproduce the problem?

- I had an Anaconda installation
- I updated mac OS to Catalina
- Problems
- I reinstalled Anaconda from command line
- Jupyter notebooks wroked well, but not Spyder

### Traceback
```python-traceback
  File "/Users/jose/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor.py", line 1942, in load
    finfo = self.editorstacks[0].load(filename, set_current=False)
  File "/Users/jose/anaconda3/lib/python3.7/site-packages/spyder/widgets/editor.py", line 2251, in load
    text, enc = encoding.read(filename)
  File "/Users/jose/anaconda3/lib/python3.7/site-packages/spyder/utils/encoding.py", line 249, in read
    text, encoding = decode( open(filename, 'rb').read() )
PermissionError: [Errno 1] Operation not permitted: '/Users/jose/Documents/Udacity/deep-learning-v2-pytorch-master/extracurricular/keras/conv-dims.py'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> I updated mac OS to Catalina

This is a problem with Catalina and not with Spyder. Unfortunately we don't know how to help users with it, sorry.

**Comment by ccordoba12** [comment]
The solution seems to be explained here:

https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/

**Comment by josequinonez** [comment]
Hi Carlos,
I tried a workaround. I just launch Spyder from a terminal using sudo spyder, instead of calling it from Anaconda Navigator. It worked!
It seems like it has to do with having installed Anaconda in a user folder.
Thank you


________________________________
De: Carlos Cordoba <notifications@github.com>
Enviado: lunes, 14 de octubre de 2019 06:46 p. m.
Para: spyder-ide/spyder <spyder@noreply.github.com>
CC: josequinonez <jose.quinonez.lopez@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [spyder-ide/spyder] Permission prpoblems after a fresh installation of Anaconda from command (#10406)


I updated mac OS to Catalina

This is a problem with Catalina and not with Spyder. Unfortunately we don't know how to help users with it, sorry.

**Comment by ccordoba12** [comment]
> I just launch Spyder from a terminal using sudo spyder

This is really bad because you'll be executing arbitrary code as root, which can cause irreparable damages to your system.

Please follow the Anaconda guide and stop using sudo.

**Comment by acarrami** [comment]
I had the same problem. I could run my code when calling spyder from a terminal, rather than from the anaconda app, WITHOUT having to use sudo.

**Comment by hughmurphy** [comment]
I can no longer use Conda commands on a Mac OS Catalina. Think it may be something to do with the shell changing to bin/zsh. Having the same problem with anaconda and Spyder wonder if they are connected?
