### ISSUE TITLE
Matplotlib forced on qt4 with Spyder

### ISSUE THREAD

**Issue by doudouball** [spyder-ide/spyder#10417]
Hello everybody,
I recently reinstalled Anaconda, since I was still using python 2 and since, I can't plot anything with Matplotlib
even the simplest code:
``import matplotlib.pyplot as pyplot
 pyplot.plot([1, 2, 3, 4, 5, 6],[4, 5, 1, 3, 6, 7])
 pyplot.show()``
raises an exception:
"Cannot load backend 'Qt4Agg' which requires the 'qt4' interactive framework, as 'qt5' is currently running "

No matter what I do to force matlab on qt5, each time I run my code, it wants to go on qt4. On the other hand, everything works fine on Conda (but it is less convenient to code there) 
Do any of you happens to know the why and how of this problem?

## Versions
Spyder version: 3.3.6
Python version: 3.7
Qt version: 5.9.6
PyQt version: 5.9.2
Operating System name/version: win32 - Windows 10

### Dependencies
```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by bcolsen** [comment]
> No matter what I do to force matlab [sic] on qt5, each time I run my code, it wants to go on qt4

What settings have you tier in "Preferences>IPython console>graphics>graphics backend" ?

**Comment by doudouball** [comment]
I tried QT4, QT5 and automatic and it always raises the exception.

**Comment by bcolsen** [comment]
Do gtk and tk backends work?

**Comment by doudouball** [comment]
I don't know how to check that...

**Comment by bcolsen** [comment]
Try to change "Preferences>IPython console>graphics>graphics backend" to "Gtk", "Gtk3" or "TKinter

**Comment by ccordoba12** [comment]
> Do gtk and tk backends work?

@bcolsen, @doudouball is on Windows.

----

@doudouball, I really doubt this is a problem with Spyder. It's usually caused by a `matplotlibrc` file lying around in your file system. Please look for it and remove it.

**Comment by doudouball** [comment]
@ccordoba12 The thing is when I run my code directly, it runs without problem, that's why I believe the issue is due to Spyder. When i remove matplotlibrc, I get the exception "RuntimeError: Could not find matplotlibrc file; your Matplotlib install is broken"

**Comment by ccordoba12** [comment]
> The thing is when I run my code directly

What do you mean by this? Is it "outside Spyder"?

**Comment by doudouball** [comment]
When I use the Anaconda prompt and call the .py file, it runs without any issue

**Comment by ccordoba12** [comment]
I'm sorry but I don't know what happens in your case. The only solution that occurs to me is to to go to

    Tools > Preferences > IPython console > Graphics

deactivate the option called `Activate support` and run directly `%matplotlib qt5` in our consoles.

**Comment by shahrjoo** [comment]
> I tried QT4, QT5 and automatic and it always raises the exception.

I Changed it to  QT5 and restart kernel, it worked for me

**Comment by ajaykumar2017** [comment]
Hi I am getting Error
**Cannot load backend 'Qt4Agg' which requires the 'qt4' interactive framework, as 'qt5' is currently running**
Tell me how to resolve it...?
