### ISSUE TITLE
Spyder 4 Optional Dependencies Not Installed

### ISSUE THREAD

**Issue by PhilipYip1988** [spyder-ide/spyder#10422]
### What steps will reproduce the problem?

Launch Spyder 4 beta after installation, select help and then Dependencies...

The Optional Dependencies are all marked with a !
Typing in a script and then executing the script and restarting Spyder 4 solves the issue.

pip install sympy
pip install cython
pip install matplotlib
pip install pandas
pip install numpy
pip install scipy 

## Versions

* Spyder version: 4.0.0b6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
> Spyder 4 Optional Dependencies Not Installed

That's why they are optional, i.e. they are not needed for Spyder to run so it depends on users if they want to have additional support for SymPy, Numpy, Scipy, etc.

**Comment by ccordoba12** [comment]
Besides, this dependency

    rtree >=0.8.3                :  0.8.3 (OK)

shows that you're using Anaconda, but by running these commands

    pip install sympy
    pip install cython
    pip install matplotlib
    pip install pandas
    pip install numpy
    pip install scipy

instead of

    conda install sympy
    conda install cython
    conda install matplotlib
    conda install pandas
    conda install numpy
    conda install scipy

you broke your Anaconda installation and now you have to reinstall it. That's because pip and conda packages are incompatible for the most part.

So from now on please use conda first to install packages and only use pip if they are not available through conda.

**Comment by PhilipYip1988** [comment]
Trying again in a fresh Windows 10 VM after installing the latest build of Anaconda for Windows 10 64 Bit and running in a powershell script:

conda update anaconda
conda update spyder
conda create --channel spyder-ide --name spyder-beta spyder=4.0.0b6
conda activate spyder-beta

Opening up Spyder 4 shows the ! for: 
sympy
cython
matplotlib
pandas
numpy
scipy

Note the conda install doesn't work in the Spyder 4 console:

conda install sympy

Note: you may need to restart the kernel to use updated packages.
'conda' is not recognized as an internal or external command,
operable program or batch file.

The Spyder 4 optional dependencies are still marked with a !
sympy
cython
matplotlib
pandas
numpy
scipy

If ran in the anaconda powershell prompt:

(base) PS C:\Users\Philip> conda install sympy
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) PS C:\Users\Philip>

These work with Spyder 3 without any issue.

The Spyder 4 optional dependencies are still marked with a !
sympy
cython
matplotlib
pandas
numpy
scipy

![conda2](https://user-images.githubusercontent.com/56493395/66894186-a9fe2600-efe7-11e9-9280-c132d07316e0.PNG)

pip install sympy in the Spyder 4 console works however.

pip install sympy
Collecting sympy
  Downloading https://files.pythonhosted.org/packages/21/21/f4105795ca7f35c541d82c5b06be684dd2f5cb4f508fb487cd7aea4de776/sympy-1.4-py2.py3-none-any.whl (5.3MB)
Collecting mpmath>=0.19 (from sympy)
  Downloading https://files.pythonhosted.org/packages/ca/63/3384ebb3b51af9610086b23ea976e6d27d6d97bf140a76a365bd77a3eb32/mpmath-1.1.0.tar.gz (512kB)
Building wheels for collected packages: mpmath
  Building wheel for mpmath (setup.py): started
  Building wheel for mpmath (setup.py): finished with status 'done'
  Created wheel for mpmath: filename=mpmath-1.1.0-cp37-none-any.whl size=532244 sha256=5ccb4cf2318f898070ead4a7000c3b38d32da29d5d69076a1ec5c5fddbf6f3c3
  Stored in directory: C:\Users\Philip\AppData\Local\pip\Cache\wheels\63\9d\8e\37c3f6506ed3f152733a699e92d8e0c9f5e5f01dea262f80ad
Successfully built mpmath
Installing collected packages: mpmath, sympy
Successfully installed mpmath-1.1.0 sympy-1.4
Note: you may need to restart the kernel to use updated packages.

Using the following:
pip install sympy
pip install cython
pip install matplotlib
pip install pandas
pip install numpy
pip install scipy
Clears the ! for the optional dependencies.

**Comment by ccordoba12** [comment]
> Opening up Spyder 4 shows the ! for:

That's a warning. Please don't insist.

**Comment by ccordoba12** [comment]
> Note the conda install doesn't work in the Spyder 4 console:

Conda and pip commands need to be run in the Anaconda Prompt, not in the Spyder console.

**Comment by PhilipYip1988** [comment]
Sorry I meant to clarify that when ran the _conda install sympy_ in the Anaconda Prompt I got "All requested packages already installed" however after that when I relaunched Spyder 4 it was still marked with a warning. The only way I could get the warning to disappear was to use the _pip install sympy_ within the Spyder 4 console.
