### ISSUE TITLE
numpy datetime64 and numpy timedelta64 variable explorer

### ISSUE THREAD

**Issue by PhilipYip1988** [spyder-ide/spyder#10423]
## Description

import numpy as np
import datetime

a=datetime.datetime(2019,9,9,12,40,1,100000)
b=datetime.timedelta(hours=8)
c=np.datetime64('2019-09-09T12:40:01.1')
d=np.timedelta64(1,'h')
e=np.arange(start=np.datetime64('2018-01-01'),stop=np.datetime64('2019-01-01'),step=np.timedelta64(100,'D'))

value of a shows up on the variable explorer as "2019-09-09 12:40:01.100000"
value of b shows up on the variable explorer as "8:00:00"
value of c shows up as "datetime64 object of numpy module"
value of d shows up as "timedelta64 object of numpy module"
value of e shows as ndarray object of numpy module

Please update the value of a and b to show the same as c and d in the same form as a and b respectively.

Please update e to have the same form as a but in an array.

## Versions

* Spyder version: 4.0.0b6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
> Please update the value of a and b to show the same as c and d in the same form as a and b respectively.

Sorry but we only handle `datetime.datetime` types in the variable explorer.

**Comment by PhilipYip1988** [comment]
Okay thanks, it's a shame as it limits the use of the numpy datetime64 and timedelta64 library which are easier to use (especially when coming from MATLAB) in particular to create a list of dates using the np.arange function opposed to using a for loop.
