### ISSUE TITLE
Another TypeError when going to definition

### ISSUE THREAD

**Issue by kai3341** [spyder-ide/spyder#10439]
### What steps will reproduce the problem?

Try to go to definition of any 3rd party package
Maybe I set incorrect path using PYTHONPATH Manager?
I've set path ".../venv/lib64/python3.7/site-packages". Is it correct?
So, system libraries definition opens fine

### Traceback
```python-traceback
  File "/home/kai/Projects/spyder/4/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 1221, in handle_go_to_definition
    def_range = position['range']
TypeError: string indices must be integers
```

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.7.3
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.19.0-6-amd64

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.2 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by ccordoba12** [comment]
> I've set path ".../venv/lib64/python3.7/site-packages". Is it correct?

No, it's not. Please remove that directory from our PYTHONPATH manager and install Spyder in your virtualenv instead.

**Comment by ccordoba12** [comment]
This error was fixed in beta7 (although you said you're using that version). So please provide an example that's giving you this error (after removing `.../venv/lib64/python3.7/site-packages` from our PYTHONPATH manager).

**Comment by kai3341** [comment]
Great thank, i've change entry in PYTHONPATH Manager, but i don't see any changes: the same exception

**Comment by ccordoba12** [comment]
Please post a simple code example that is generating this problem.

**Comment by kai3341** [comment]
Yes, I have:
```
def should_use_eventloop(self):
    return True


def patch_worker():
    from celery.worker import worker
    WorkController = worker.WorkController
    WorkController.should_use_eventloop = should_use_eventloop
```
I'm trying to go to definition of worker

**Comment by ccordoba12** [comment]
@steff456, please try to reproduce this one on Linux.

**Comment by ccordoba12** [comment]
A simpler code to generate this error:

```python
from qtpy.QtCore import Qt
Qt.FramelessWindowHint
```

and trying to go to the definition of `FramelessWindowHint`.

**Comment by steff456** [comment]
> A simpler code to generate this error:

I can reproduce the error with this example on a linux machine.

**Comment by kai3341** [comment]
Great! Thank a lot!
