### ISSUE TITLE
Fresh install - An error occured while starting the kernel

### ISSUE THREAD

**Issue by pkonrad-spec** [spyder-ide/spyder#10440]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
An error occured while starting the kernel

Kernel won't start, hence i get no console.

### What steps reproduce the problem?

1. starting spyder
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\Konrad\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\Konrad\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\Konrad\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\Konrad\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\Konrad\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\Konrad\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Konrad\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂮e03188e16e3.json'

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 3.3.6
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version:

**Comment by ccordoba12** [comment]
To fix this you need to open the Anaconda Prompt and run there

    conda update jupyter_client jupyter_core

**Comment by ccordoba12** [comment]
@jjhelmus, @mingwandroid, @msarahan, I think you should release a bug fix version for Anaconda 2019.10 because this problem was introduced in jupyter_client 5.3.3 (the version shipped by 2019.10) and fixed in  jupyter_client 5.3.4 and jupyter_core 4.6.0 (as I already mentioned to @jjhelmus).

This is very serious because it prevents Python kernel creation on Windows not only for Spyder but also for the Jupyter notebook and JupyterLab.

**Comment by ccordoba12** [comment]
> it prevents Python kernel creation

Sorry, any kernel creation, because this is a bug in jupyter_client.

**Comment by pkonrad-spec** [comment]
Thanks a lot ccordoba12!
