### ISSUE TITLE
"Remove all variables" should re-run "Startup"

### ISSUE THREAD

**Issue by allefeld** [spyder-ide/spyder#10445]
When the preference "Run / Remove all variables before execution" is checked and a file is run, this results not only in interactively created variables to be removed, but also any initialization through IPython's `startup.ipy` or the preference "IPython console / Startup / Run code" and "Run a file".

This makes sense if the purpose is to check whether the Python script contains all necessary initialization itself, but it is inconvenient for initialization that is meant to make IPython use easier, like aliases.

Possible solutions:
– re-run the startup initialization as an additional preference
– re-run the startup initialization after the script has finished
– remove variables, but preserve IPython state.

Python 3.7.4 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Linux 4.19.0-6-amd64 (Debian buster)

**Comment by ccordoba12** [comment]
> the preference "IPython console / Startup / Run code" and "Run a file"

I'm sorry but those preferences are meant to be run only once at startup, not before every time a code is run.

Therefore, I think we're not going to address your request, sorry.

@goanpeca, what do you think?

**Comment by allefeld** [comment]
Then how about preserving the IPython state, especially aliases? Aliases become useless if they have to be reset after each script run.

Basically what I'm aiming here for is a similar experience to that in Matlab, when running a script with `clear all` at the beginning. Of course there are no aliases in Matlab, the equivalent are simple helper function .m-files. And they are still accessible after, because `clear all` does not affect the path.

**Comment by goanpeca** [comment]
I am not sure I understand the issue. Could you elaborate more on this @allefeld ?

**Comment by allefeld** [comment]
OK, I'll explain it concretely how I encountered it. I have the line
```
%alias ls ls -lrtp --time-style +"%F %T" --color=always
```
in `~/.ipython/profile_default/startup/startup.ipy`, so that when I enter `ls` in the IPython console in Spyder, I get a file listing formatted the way I like it. This is part of my personal customization of the Spyder/IPython environment. When I then run a Python script with "Remove all variables before execution" enabled, afterwards this alias is gone, and `ls` gives the plain uninformative list.

The same applies to other interactively useful personal customizations like `np.set_printoptions(floatmode='unique')` so that when numpy arrays are printed, I can be sure that the decimal representation uniquely identifies the number, or to the selection of my favorite matplotlib backend, etc. etc.

I could simply deactivate "Remove all variables before execution", but in Matlab I found it useful to put a `clear all` at the top of scripts, so leftovers from previous interactive use do not interfere with the execution of the script, so I'd rather keep it.

Or to put it another way, I'd like the effect of "Execute in a dedicated console", but without cluttering the GUI with dozens of consoles.

Does that make it clear?

**Comment by goanpeca** [comment]
So your requests is that the clear all variables option runs the startup scripts (if any) as an option? or as a default?

I think what you suggest makes sense, I am not sure if it would be too heavy? or if should make that an option (and the default?) an also we should somehow warn users if a startup script was found.

Thoughts @ccordoba12 ?

**Comment by allefeld** [comment]
Yes, I think it would be best to make it optional.

An alternative to rerunning startup scripts would be to exclude certain elements from "remove all variables", so that it does something more similar to Matlab's "clear all". Exclude at least IPython settings like aliases, but maybe also not to remove imported packages.

**Comment by goanpeca** [comment]
>Exclude at least IPython settings like aliases, but maybe also not to remove imported packages.

I think this is very difficult to control.

**Comment by allefeld** [comment]
> I think this is very difficult to control.

I just found this part in the documentation of IPython's `%run` line magic:

> The file is executed in a namespace initially consisting only of `__name__=='__main__'` and `sys.argv` constructed as indicated. It thus sees its environment as if it were being run as a stand-alone program (except for sharing global objects such as previously imported modules). But after execution, the IPython interactive namespace gets updated with all variables defined in the program (except for `__name__` and `sys.argv`). This allows for very convenient loading of code for interactive work, while giving each program a 'clean sheet' to run in.

This sounds like almost exactly what I propose. So it is already implemented, Spyder only would have to make "Run / Run" execute `%run` instead of `runfile`. Or put a copy the functionality into `runfile`. Unless I am missing something?

**Comment by goanpeca** [comment]
@bcolsen thoughts?

**Comment by bcolsen** [comment]
>This sounds like almost exactly what I propose. So it is already implemented, Spyder only would have to make "Run / Run" execute %run instead of runfile. Or put a copy the functionality into runfile. Unless I am missing something?

This is already in spyder 4 as "runfile in a empty namespace". This will be the new default behavior when running a file. 

It would be great if you could try out the spyder 4 beta to see if it meets you needs.

**Comment by ccordoba12** [comment]
> This sounds like almost exactly what I propose

Closing this because it's already implemented and meets @allefeld's needs.

**Comment by allefeld** [comment]
OK, good to know, thanks!

I tried testing the current beta of Spyder 4 by installing it from a Github zip-file, but ran into problems. I may try it again by installing in a new conda environment. Looking forward to the release of Spyder 4!
