### ISSUE TITLE
The kite logo on the status bar is pixelated on retina display:

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10442]
The kite logo on the status bar is pixelated on retina display:

<img width="391" alt="Screen Shot 2019-10-17 at 11 23 07" src="https://user-images.githubusercontent.com/3627835/67028195-84008080-f0d0-11e9-882a-e20fd893f62e.png">

**Comment by ccordoba12** [comment]
@goanpeca, please take care of this one.
