### ISSUE TITLE
Kernel times out when sending big variable (it worked in Spyder 3)

### ISSUE THREAD

**Issue by QuntuamLoop** [spyder-ide/spyder#10449]
Hi, all. there is problem when I edited the dict with 40000keys and values whose shape is (100,1) .
![360截图18180711365759](https://user-images.githubusercontent.com/32284800/67058617-2b8cba00-f188-11e9-9fad-0c53f678d888.png)

**Comment by ccordoba12** [comment]
That dict is too big, so it's not possible to retrieve its value to show in Spyder, sorry.

However, the error message can be improved to better explain the reasons of the failure.

**Comment by QuntuamLoop** [comment]
but in the versiont 3.3.6 spyder with kernel 0.5.2, it give me a warning "will be slow", but give the correct  solution. I think it's a better solution, when 4.0.0b7 give the error and then every vaviables  show the same erro window.
![360截图1729050796134121](https://user-images.githubusercontent.com/32284800/67091427-2c9d0600-f1df-11e9-8edf-e6c8cc6016d3.png)
![360截图17800304446571](https://user-images.githubusercontent.com/32284800/67091438-31fa5080-f1df-11e9-8cd2-64804d9bdedd.png)
