### ISSUE TITLE
interactive inline figure

### ISSUE THREAD

**Issue by allefeld** [spyder-ide/spyder#10456]
Is it possible to have inline & interactive plots (with the ability to zoom etc.) in Spyder's IPython console, in the style of `%matplotlib widget`?

I really like the diary-style inlining of figures, but I miss the ability to examine data in detail.

I could switch to Jupyter Lab notebooks, but there I miss essential development tools like graphical debugging for non-notebook (module) py-files.

Python 3.7.4 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Linux 4.19.0-6-amd64 (Debian buster)

**Comment by ccordoba12** [comment]
> Is it possible to have inline & interactive plots (with the ability to zoom etc.) in Spyder's IPython console, in the style of %matplotlib widget?

No, unfortunately that's only supported in the notebook. However, one of our main goals for Spyder 5 is to add a new pane that will be able to display interactive content (in much the similar way as JupyterLab).
