### ISSUE TITLE
messed docstring in function arguments popup in ipython console

### ISSUE THREAD

**Issue by callegar** [spyder-ide/spyder#10477]
## Problem Description

entering a function and then '(' in the ipython console makes a popup appear with the function arguments both in spyder and in jupyter qtconsole.  However, in the latter the arguments are followed by a properly formatted docstring which is shown truncated if too long. Conversely, in spyder the popup shows a docstring with all the linebreaks and spaces removed so that it is quite hard to read. Furthermore, the docstring is not truncated, leading to a too big popup in some cases. 

## Versions

* Spyder version: 
* Python version: 3.7.3 
* Qt version: 3.3.6
* PyQt version: 5.12.3 (qt 5.12.4)
* Operating System name/version: Kubuntu linux 19.04

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed already and it'll be part of Spyder 4, to be released next month.
