### ISSUE TITLE
Spyder4 (trunk of the day) doesn't want to start in WinPython 

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#10472]
I know it's not the urgency, but as a remark I fail to make Spyder4 finish to start on WinPython. It's stuck in this state.

Any basic clue, if you have, is welcomed. I suppose there is a special detail now needed, that wasn't needed before in Spyder3, and is not by default in WinPython.

![image](https://user-images.githubusercontent.com/4312421/67165961-5bf07600-f38b-11e9-97e2-4c794d8c29fc.png)

pip list
Package                       Version     
----------------------------- ------------
alabaster                     0.7.12      
argh                          0.26.2      
asn1crypto                    1.0.1       
astroid                       2.3.1       
atomicwrites                  1.3.0       
attrs                         19.3.0      
autopep8                      1.4.4       
Babel                         2.7.0       
backcall                      0.1.0       
bcrypt                        3.1.7       
bleach                        3.1.0       
Brotli                        1.0.7       
certifi                       2019.9.11   
cffi                          1.13.0      
chardet                       3.0.4       
cloudpickle                   1.2.2       
colorama                      0.4.1       
cryptography                  2.7         
dask                          2.6.0       
decorator                     4.4.0       
defusedxml                    0.6.0       
diff-match-patch              20181111    
docopt                        0.6.2       
docutils                      0.15.2      
entrypoints                   0.3         
fsspec                        0.5.2       
future                        0.18.0      
helpdev                       0.6.10      
idlex                         1.18        
idna                          2.8         
imagesize                     1.1.0       
importlib-metadata            0.23        
ipykernel                     5.1.2       
ipython                       7.8.0       
ipython-genutils              0.2.0       
isort                         4.3.21      
jedi                          0.14.1      
Jinja2                        2.10.3      
joblib                        0.14.0      
jsonschema                    3.1.1       
jupyter-client                5.3.4       
jupyter-core                  4.6.0       
keyring                       19.2.0      
lazy-object-proxy             1.4.2       
locket                        0.2.0       
MarkupSafe                    1.1.1       
mccabe                        0.6.1       
mistune                       0.8.4       
nbconvert                     5.6.0       
nbformat                      4.4.0       
numpydoc                      0.9.1       
packaging                     19.2        
pandocfilters                 1.4.2       
paramiko                      2.6.0       
parso                         0.5.1       
partd                         1.0.0       
pathtools                     0.1.2       
pexpect                       4.7.0+dummy 
pickleshare                   0.7.5       
pip                           19.3.1      
pluggy                        0.13.0      
prompt-toolkit                2.0.10      
psutil                        5.6.3       
ptpython                      2.0.6       
pycodestyle                   2.5.0       
pycosat                       0.6.3       
pycparser                     2.19        
pydocstyle                    4.0.1       
pyflakes                      2.1.1       
Pygments                      2.4.2       
pylint                        2.4.2       
Pympler                       0.7         
PyNaCl                        1.3.0       
pyodbc                        4.0.27      
pyparsing                     2.4.2       
PyQt5                         5.12.3      
PyQt5-sip                     4.19.19     
PyQtWebEngine                 5.12.1      
pyrsistent                    0.15.4      
python-dateutil               2.8.0       
python-jsonrpc-server         0.2.0       
python-language-server        0.28.3      
python-snappy                 0.5.4       
pythonnet                     2.4.0       
pytz                          2019.3      
pywin32                       225         
pywin32-ctypes                0.2.0       
PyYAML                        5.1.2       
pyzmq                         18.1.0      
QDarkStyle                    2.7         
QtAwesome                     0.6.0       
qtconsole                     4.5.5       
QtPy                          1.9.0       
requests                      2.22.0      
rope                          0.14.0      
setuptools                    41.4.0      
six                           1.12.0      
snowballstemmer               2.0.0       
Sphinx                        2.2.0       
sphinxcontrib-applehelp       1.0.1       
sphinxcontrib-devhelp         1.0.1       
sphinxcontrib-htmlhelp        1.0.2       
sphinxcontrib-jsmath          1.0.1       
sphinxcontrib-qthelp          1.0.2       
sphinxcontrib-serializinghtml 1.1.3       
spyder                        4.0.0.dev0  
spyder-kernels                1.6.0       
sqlite-bro                    0.9.1       
testpath                      0.4.2       
toolz                         0.10.0      
tornado                       6.0.3       
traitlets                     4.3.3       
typed-ast                     1.4.0       
urllib3                       1.25.6      
watchdog                      0.9.0       
wcwidth                       0.1.7       
webencodings                  0.5.1       
wheel                         0.33.6      
winpython                     2.1.20191018
wrapt                         1.11.2      
yapf                          0.28.0      
zipp                          0.5.2

**Comment by ccordoba12** [comment]
> spyder-kernels 1.6.0

You can't run our latest master with that version of spyder-kernels. in other words, you also need master of spyder-kernels too.

Please try that and let us know if it works for you.

**Comment by stonebig** [comment]
Using spyder-kernel-1.7.0dev0 of last night doesn't change the situation https://github.com/spyder-ide/spyder-kernels/commit/f4d04ee03196017aabdad4046f6819e3b3641149.

I'll digg again at RC.

**Comment by ccordoba12** [comment]
Closing because there's nothing we can do to help, sorry.
