### ISSUE TITLE
Spyder fail to load ipython console on win10 if not run as administrator

### ISSUE THREAD

**Issue by yumeng426** [spyder-ide/spyder#10490]
## Problem Description
After update anaconda to 2019.10, spyder fail to load ipython console. I can start ipython from powershell and if I run spyder as administrator.

## What I have tried
1. Reset Sypder
2. Downgrade to 2019.07 update to the latest custom packages, spyder works fine. But it would fail if I continue and install 2019.10. I have listed what last changes on packages in Dependencies. 
3. Strangely, usually conda update anaconda should land me straight on the latest non-custom anaconda, but not this time. I can only land on 2019.10 from 2019.07 by conda update anaconda twice, 2019.07 -> custome -> 2019.10.

### What steps reproduce the problem?

1. Open Spyder

### What is the expected output? What do you see instead?

I expect it to load ipython as usual.

### Paste Traceback/Error Below (if applicable)

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "D:\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "D:\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "D:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "D:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "D:\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "D:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Yumeng\\AppData\\Roaming\\jupyter\\runtime\\kernel𔂲a8496f4b8c8.json'

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Win10 Version	10.0.18362 Build 18362

### Dependencies
packages changed since last successful run

  anaconda                                    custom-py37_1 --> 2019.10-py37_0
  python                                   3.7.3-h8c8aaf0_1 --> 3.7.4-h5263a28_0

The following packages will be SUPERSEDED by a higher-priority channel:

  jupyter_core       pkgs/main/win-64::jupyter_core-4.6.0-~ --> pkgs/main/noarch::jupyter_core-4.5.0-py_0

The following packages will be DOWNGRADED:

  astropy                              3.2.2-py37he774522_0 --> 3.2.1-py37he774522_0
  ca-certificates                              2019.10.16-0 --> 2019.8.28-0
  dask                                           2.6.0-py_0 --> 2.5.2-py_0
  dask-core                                      2.6.0-py_0 --> 2.5.2-py_0
  distributed                                    2.6.0-py_0 --> 2.5.2-py_0
  jupyter_client                               5.3.4-py37_0 --> 5.3.3-py37_1
  openssl                                 1.1.1d-he774522_3 --> 1.1.1d-he774522_2
  pandas                              0.25.2-py37ha925a31_0 --> 0.25.1-py37ha925a31_0
  pip                                         19.3.1-py37_0 --> 19.2.3-py37_0

**Comment by yumeng426** [comment]
maybe it is caused by  
jupyter_core       pkgs/main/win-64::jupyter_core-4.6.0-~ --> pkgs/main/noarch::jupyter_core-4.5.0-py_0

I don't know why this would change

**Comment by goanpeca** [comment]
You need to update to the latest version of jupyter core. This might differ from the latest anaconda, but that package introduced some errors.

**Comment by ccordoba12** [comment]
> You need to update to the latest version of jupyter core

And also jupyter_client. The right versions that solve this problem are

* jupyter_core 4.6.0
* jupyter_client 5.3.4

I'm closing this because it's not a Spyder bug but a Jupyter one, which is already fixed in those versions.
