### ISSUE TITLE
matplotlib error

### ISSUE THREAD

**Issue by yousefakhlaghi** [spyder-ide/spyder#10505]
I installed anaconda 2.7. Then I create a new environment python 3.6. After that install all packages in 3.6 like packages in 2.7. Right now I run one simple code in both versions:
    import matplotlib.pyplot as plt
    x=[1,2,3,4,5,6]
    plt.plot(x) 
In 2.7 it works correctly, but in 3.6 it shows an error:
    TypeError: 'NoneType' object is not iterable
What should I do

**Comment by goanpeca** [comment]
Please complete the information that was requested when opening the issue:



### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below


## Problem Description



### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?



### Paste Traceback/Error Below (if applicable)


```python-traceback

PASTE TRACEBACK HERE

```

## Versions


* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies


```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
