### ISSUE TITLE
Existing kernel connection ssh

### ISSUE THREAD

**Issue by theoVag** [spyder-ide/spyder#10518]
## Description

**What steps will reproduce the problem?**

1. Add json file
2. connect
3. It occurs after every command execution

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.8
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.4 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
> Spyder Version: 3.2.6

This is a very, very old version. Please download and install Anaconda, which comes with our latest version (3.3.6), which most probably has a fix for this problem.
