### ISSUE TITLE
Completions are not working for underscore variables

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10528]
If a method or variable starts with `_`, completions are not working:

```python
def _test1():
    pass


_test2 = 2
__test3 = 1

_*
```

Press `<tab>` on the cursor (*) and none of `_test1`, `_test2` `__test3` appear.

**Comment by goanpeca** [comment]
It was working on v4.0.0b4

<img width="370" alt="Screen Shot 2019-10-29 at 07 10 29" src="https://user-images.githubusercontent.com/3627835/67765917-47f7e480-fa1b-11e9-8ae5-02c74187e743.png">

**Comment by ccordoba12** [comment]
Please take a look at this @goanpeca. Most probably the sorting algorithm for completion entries is now dropping underscores.

**Comment by goanpeca** [comment]
Will do.
