### ISSUE TITLE
Send segmentation fault reports to Github

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#10536]
When an internal python error happens in spyder, a report can be sent automatically by the user to github. I think it would be a good idea to extend this behaviour to C errors such as segmentation faults.

Steps:
 [ ] Define a file where the crash data is saved
 [ ] Have spyder check if the file is empty when starting. If it is not, show a message like "It appears Spyder crashed last time you openned it. Do you want to send a report on Github?"
 [ ] When launching spyder, open a file handler to the log file, and pass it to `faulthandler.enable`

I am currently using this:
```
from spyder.app import start
import faulthandler
with open('/Users/quentinpeter/spyder_faulthandler.log', 'w') as f:
    faulthandler.enable(file=f)
    start.main()
```

I think this code should be moved to `main()`

**Comment by ccordoba12** [comment]
@impact27, I finished your PR #10553 to have this functionality in 4.1.1.

So from now on people will be able to start Spyder with

    spyder --report-segfault

then start Spyder again with

    spyder

and send segfault reports to Github.
