### ISSUE TITLE
under search toolbar, the &replace text button can not 'replace all'   selected strings

### ISSUE THREAD

**Issue by keepgoing365** [spyder-ide/spyder#10554]
## Description

**What steps will reproduce the problem?**

1. under search toolbar, the 
![before replace text](https://user-images.githubusercontent.com/50706951/67910890-6f87b200-fbbf-11e9-821b-46dcee45ad6c.png)
![after replace text](https://user-images.githubusercontent.com/50706951/67910893-7282a280-fbbf-11e9-8dda-a5e8915af44d.png)

&replace text button can not 'replace all'   selected strings,it can replace only 1 or 2 chars 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.16.0 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
> 3.0.0

This is three(**!!**) years old! Please update to our latest version (3.3.6) and try again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
