### ISSUE TITLE
Missing characters in help panel.

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#10555]
I'm using spyder from the master repository, in Windows 10 os, with the Chinese language environment.

After opening spyder, type in `import numpy as np; np.array` in the console, then press `Ctrl+I`, the help information should be displayed in the help panel, like the following:
![image](https://user-images.githubusercontent.com/4179106/67915186-348c7b00-fbcd-11e9-967a-474e97335e84.png)

Note that in the "Parameters" section, there should be a colon after parameter names, like `object: array_like`.

There are actually colons if you type in `np.array?` in the console:

```
In [2]: np.array?
Docstring:
array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    __array__ method returns an array, or any (nested) sequence.
dtype : data-type, optional
    The desired data-type for the array.  If not given, then the type will
    be determined as the minimum type required to hold the objects in the
    sequence.  This argument can only be used to 'upcast' the array.  For
    downcasting, use the .astype(t) method.
```

**Comment by gepcel** [comment]
I'm guessing it might be some missing fonts? But don't know how to locate it.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a problem with Sphinx 2+ and it was already reported.
