### ISSUE TITLE
Nonetype object is not subscriptable

### ISSUE THREAD

**Issue by dray89** [spyder-ide/spyder#10578]
### What steps will reproduce the problem?

I open the project and it comes up with the box that says Spyder has encountered an internal project. 
 File "C:\Users\rayde\iCloudDrive\GitHub\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 135, in perform_request

### Traceback
```python-traceback
  File "C:\Users\rayde\iCloudDrive\GitHub\Anaconda3\lib\site-packages\spyder\plugins\completion\kite\client.py", line 135, in perform_request
TypeError: 'NoneType' object is not subscriptable
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.17.1 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> Spyder version: 4.0.0b4

Please update to beta7. This error should be fixed in that version.
