### ISSUE TITLE
30% CPU usage on Windows 7

### ISSUE THREAD

**Issue by kdano** [spyder-ide/spyder#10585]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have just installed Anaconda and Spyder with it on my Windows 7 machine. I haven't even written any code yet, and still:
Spyder uses 30% of my CPU whenever it's running (python.exe, svchost.exe and dwm.exe combined, see task manager screenshot).
![spyder](https://user-images.githubusercontent.com/11364554/68073169-284b1e00-fd85-11e9-8420-1517af752798.png)

## What steps reproduce the problem?

1. Launch Spyder, leave it idle.

It doesn't matter whether I launch Spyder from the Anaconda Navigator or separately. 
The only difference is that if I launch Spyder separately, then I see pythonw.exe instead of python.exe in the task manager.

### What is the expected output? What do you see instead?

I would expect 1-2% CPU usage max in idle state.

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 7 64-bit

### Dependencies

```
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
I don't what's happening, sorry. Please wait until Spyder 4 is released (next month) and try again.

**Comment by kdano** [comment]
I am now on version 4.0.1 but the problem persists (with Anaconda).
Interestingly, there is no problem with Spyder installed via WinPython.

**Comment by asmwarrior** [comment]
I also see the similar issue, I'm using WinPython Winpython64-3.7.6.0.exe, and when Spyder is in Idle, it still use about 5% or 8% cpu time.

See image shot below:
![2020-03-13 13 10 33](https://user-images.githubusercontent.com/561818/76591757-43484e80-652c-11ea-9fca-0d95e0fc4575.png)


Python 3.7.6 64-bit | Qt 5.14.0 | PyQt5 5.14.0 | Windows 7
