### ISSUE TITLE
an error while starting the kernel

### ISSUE THREAD

**Issue by mmmsh** [spyder-ide/spyder#10580]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
It's first time i use spyder and i face this problem directly , how can i solved with easy way please ?

### What steps reproduce the problem?

1. install anaconda 2019
2. open spyder
3. and the problem was in the Ipython console 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 2.7
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
Traceback (most recent call last):
File "C:\anaconda\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1562, in create_kernel_manager_and_kernel_client
config=None, autorestart=True)
File "C:\anaconda\lib\site‑packages\traitlets\config\configurable.py", line 73, in __init__
super(Configurable, self).__init__(**kwargs)
File "C:\anaconda\lib\site‑packages\traitlets\traitlets.py", line 997, in __init__
setattr(self, key, value)
File "C:\anaconda\lib\site‑packages\traitlets\traitlets.py", line 585, in __set__
self.set(obj, value)
File "C:\anaconda\lib\site‑packages\traitlets\traitlets.py", line 559, in set
new_value = self._validate(obj, value)
File "C:\anaconda\lib\site‑packages\traitlets\traitlets.py", line 591, in _validate
value = self.validate(obj, value)
File "C:\anaconda\lib\site‑packages\traitlets\traitlets.py", line 2053, in validate
raise TraitError(msg.format(value, self.name, class_of(obj)))
TraitError: Could not decode 'C:\\Users\\\xe3\xdf\xca\xc8 \xc7\xcd\xe3\xcf \xe1\xe1\xcd\xc7\xd3\xc8\xc7\xca\\AppData\\Roaming\\jupyter\\runtime\\kernel‑cae4b83b15ef.json' for unicode trait 'connection_file' of a QtKernelManager instance.
```

**Comment by ccordoba12** [comment]
> Spyder version: 2.7
Python version: 3.7

I think this is incorrect. Instead, it seems you're using a Python 2 version of both Anaconda and Spyder.

And this part of the error is very telling: 

> TraitError: Could not decode 'C:\\Users\\\xe3\xdf\xca\xc8 \xc7\xcd\xe3\xcf \xe1\xe1\xcd\xc7\xd3\xc8\xc7\xca\\AppData\\Roaming\\jupyter\\runtime\\kernel‑cae4b83b15ef.json' for unicode trait 'connection_file' of a QtKernelManager instance.

It basically shows that you have a user name with a bunch of non-ascii chars (i.e. letters like `ñ`, `á`, Chinese characters, etc).

So you have two possible solutions here:

1. Change your user name to have only ascii letters (i.e. something like `John`).
2. Start using Python 3 (it's about time because Python 2 will reach end-of-life in just two months).
