### ISSUE TITLE
Cannot find Terminal

### ISSUE THREAD

**Issue by Brunox13** [spyder-ide/spyder#10581]
### What steps will reproduce the problem?

I have installed the Terminal plugin using

```
conda install spyder-terminal -c spyder-ide
```

However, I cannot see it anywhere. (I have tried going to View -> Panes.) Is that because of version incompatibility? Thanks!

## Versions

* Spyder version: 4.0.0b7 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.6.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
spyder-terminal is not ready for Spyder 4. Right now @steff456 is in the process of updating it and a new version will be available in a month or so.

**Comment by dkinneyBU** [comment]
Why is this closed if it has not been resolved? Embedded terminal is a pretty important feature (PyCharm, RStudio...) If you close the issue how do we track progress?

**Comment by ccordoba12** [comment]
Spyder terminal is being developed externally:

https://github.com/spyder-ide/spyder-terminal

**Comment by SergeiDBykov** [comment]
So how it is with adding Spyder 4 for Spyder-terminal? It doesn't start on 4.0.1.
