### ISSUE TITLE
DEBUG:spydercustomize:Could not get breakpoints from the frontend

### ISSUE THREAD

**Issue by SvenMeyer** [spyder-ide/spyder#10596]
### What steps will reproduce the problem?

Menu : Debug > Debug

debugfile('/home/sum/PycharmProjects/py38/email_multipart.py', wdir='/home/sum/PycharmProjects/py38')
DEBUG:spydercustomize:Could not get breakpoints from the frontend.

## Versions

* Spyder version: 4.0.0rc1 
* Python version: 3.8.0+
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.19.80-1-MANJARO

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.7.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.29.3;<0.30.0        :  0.29.3 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by ccordoba12** [comment]
@impact27, please take a look at this one. I think we should remove the logging entry from the kernel because (as you can see), users interpret it as an error.

**Comment by impact27** [comment]
I am not sure about that:
 - AFAIK, the user need to enable logging to see that?
 - This actually is an error, and it might help the user understand why the code doesn't stop on breakpoints. So we might actually want to make sure this is printeds for every user.

**Comment by ccordoba12** [comment]
> AFAIK, the user needs to enable logging to see that?

Sure, but we can do it because his/her program requires it.

> This actually is an error, and it might help the user understand why the code doesn't stop on breakpoints. So we might actually want to make sure this is printed for every user.

You're right. Then we just need to improve the logging messages we're printing right now.

**Comment by ccordoba12** [comment]
Closing because no one else has reported something like this (as far as I recall).
