### ISSUE TITLE
Kite tutorial keeps trying to reload tutorial file

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#10609]
### What steps will reproduce the problem?

If you follow the instructions in kite_tutorial.py as soon as you accept any of the autocomplete spyder pops up a dialog box stating the file has been changed and do you want to reload it. If you say yes it reloads your file. If you say no it sometimes causes Spyder to crash (this is hard to duplicate for me). By crash I mean exit to Windows, popping up the 'do you want to debug Windows dialog, not catch an exception.

I also think the text is incorrect in 1b. The instructions have you try to autocomplete 'pyplot as plt', but the code already reads "import matplotlib.pyplot as plt" - maybe that got inserted by me one time while trying to reproduce the crash?

## Versions

* Spyder version: 4.0.0rc1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.7.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.29.3;<0.30.0        :  0.29.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
@rlabbe about the `1.b` step of the tutorial, as you mention, in the base file is already done. I think that is an issue for Kite @ccordoba12 (probably is in their backlog because I remember talking about something like that when I was reviewing the initial PR for the onboarding).

**Comment by ccordoba12** [comment]
> I also think the text is incorrect in 1b. The instructions have you try to autocomplete 'pyplot as plt', but the code already reads "import matplotlib.pyplot as plt" - maybe that got inserted by me one time while trying to reproduce the crash?

@plungg, @metalogical, could you take a look at this comment? Thanks!

**Comment by metalogical** [comment]
we merged the fix to the file today, should be released shortly
