### ISSUE TITLE
Icons in dark mode on kde

### ISSUE THREAD

**Issue by bijang** [spyder-ide/spyder#10608]
Please see attached screenshot, is there any fix for this, I couldnt see an icon colour in the setting, or a dark mode compatibility
![spyder](https://user-images.githubusercontent.com/15066720/68155121-f54d8980-ff40-11e9-9c31-97f531c9c20f.png)

**Comment by ccordoba12** [comment]
A full dark theme is coming for Spyder 4. We don't plan to address this for Spyder 3, sorry.
