### ISSUE TITLE
Can't determine a global variable exists when you run a script

### ISSUE THREAD

**Issue by minientertainment** [spyder-ide/spyder#10612]
## Problem Description
You can't check whether a global variable exists by running below script:
'var_name' in globals()

### What steps reproduce the problem?

1. in ipython console made a new variable,
In[1]: tmp = 2
In[2]: print('tmp' in globals())
True
2. made a new script 'test.py',
print('tmp' in globals())
3. run test.py

### What is the expected output? What do you see instead?
expected: True
got: False

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.0.0.rc1 (installed by anaconda)
* Python version:  3.7.0
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS mojave

**Comment by ccordoba12** [comment]
In Spyder 4 files are run by default in an empty namespace to avoid picking up previous variables defined in the console.

To get the previous behavior, you need to go to the menu

    Run > Configuration per file

and select the option called

    Run in console's namespace instead of an empty one.
