### ISSUE TITLE
AttributeError: module 'dateutil.tz' has no attribute 'UTC'

### ISSUE THREAD

**Issue by Fire007-zq** [spyder-ide/spyder#10620]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

AttributeError: module 'dateutil.tz' has no attribute 'UTC'
AttributeError: module 'dateutil.tz' has no attribute 'UTC'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.16.4 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
> What steps will reproduce the problem?

This information is missing and without that info we can't help you. So please describe how this error appeared in your case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Gladysgong** [comment]
conda install dateutil
