### ISSUE TITLE
'Show completions on the fly' cannot be turned off

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#10634]
## Problem Description

Completions on the fly kicks in even when the option is unchecked.

![bug_auto_completion](https://user-images.githubusercontent.com/10170372/68405713-99585000-014e-11ea-8406-7a315d597d93.gif)

### What steps reproduce the problem?

1. Uncheck the option `Show completions on the fly`
2. Type some code that includes a '.'
3. Wait for completions to kicks in.

The problem seems to come from the code here :

https://github.com/spyder-ide/spyder/blob/90df471cff7d2713d20ebce900d27ede7b11e6f5/spyder/plugins/editor/widgets/codeeditor.py#L3602-L3610

It results in a call to `self.do_completion` directly even when the option `Show completions on the fly` is unchecked. Adding `and self.automatic_completions` to the condition `elif text in self.auto_completion_characters:` seems to fix the problem.

## Versions

* Spyder 4.0.0.dev0 (Commit: 3fd0553b4) 
* Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by goanpeca** [comment]
@jnsebgosselin thanks for this!

Could you open a PR ? Thanks!

**Comment by jnsebgosselin** [comment]
If it is as simple as that, sure.

However, I don't completely understand why some calls are made directly to `do_completion`, ignoring the timer.

**Comment by goanpeca** [comment]
True, cause the `'.'` is a special case so yes the timer is being ignored. 

Let me handles this, so I can fix the logic.

**Comment by jnsebgosselin** [comment]
Excellent, thanks!
