### ISSUE TITLE
Code style linting performance is extremely low

### ISSUE THREAD

**Issue by JoElfner** [spyder-ide/spyder#10643]
### What steps will reproduce the problem?

Writing code will reproduce the problem.
Code style linting will degrade the performance of the Editor by several magintudes. Especially in large class definitions with more than 1k LOC, the linting completely stops the editor for several seconds (usually around 10-15 seconds in a file with 3k LOC) each time a line is altered.
Writing new lines makes the Editor hang for around 3 seconds, but typed symbols will still appear after some time.

Especially assert statements with isinstance() checks seem to break the performance.

Please add a warning to the "Enable code style linting" checkbox in settings -> "Completition and lintint -> Code style" as long as this is not resolved, since finding the root of the performance drops takes ages...
Thanks!

**EDIT**:
I didn't know the button "report bug" in Spyder directly created an Issue... So if you think that creating an issue for this problem is too much, feel free to close it.

## Versions

* Spyder version: 4.0.0rc1 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.7.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.29.3;<0.30.0        :  0.29.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
> Especially assert statements with isinstance() checks seem to break the performance.

This seems the problem because we haven't observed nor it hasn't been reported before such performance problems.

Please post a code example that generates this issue in your side so we can reproduce it and try to fix it.

**Comment by JoElfner** [comment]
While writing these really simple lines, Spyder completely crashed two times (not only for a few seconds, a full restart was required):

```
import numpy as np

class LntngTest():
    def __init__(self):
        self.a = np.random.rand(1000, 10)
        self.b = np.linspace(10, 100.)

    def foo(self, **kwds):
        if 'abc' in kwds:
            assert(isinstance(kwds['abc'], float) and (kwds['abc'] > 5.))
```

The first crash occured at the line `self.b = np.linspace(10, 100.)`, when adding the "float"-dot at `100.`.

The second crash occured at the line `assert(isinstance(kwds['abc'], float) and (kwds['abc'] > 5.))`.
I did not crash while simply typing the line. I entered the line `assert(type(kwds['abd']) == float and kwds['abc'] > 5.)`, which was fine. Then I began replacing `type(...)` with `isinstance` and as soon as I removed the closing brace at `type(kwds['abd'])` and added a comma Spyder crashed.

Interestingly my "real" code with much more LOC does not make the editor completely crash, but only hang for several seconds.

**Comment by ccordoba12** [comment]
Ok, thanks a lot for the code sample!

@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
@ccordoba12 @JoElfner I tried to replicated the issue but I was unable to do it (tried with the lines above in a empty file and inside our `codeeditor.py` which has +4000 lines). I see a drop of responsiveness inside the `codeeditor.py` while typing (a couple of seconds of delay that can cause some strange behaviors like leaving a character at the end of the completion or showing a tooltip from a element below the line being edited) but not to the point to crash:

![completion](https://user-images.githubusercontent.com/16781833/68549512-b4cd9000-03c6-11ea-901d-daf6c3f4a37a.gif)

Also, @JoElfner do you have any other setting set without a default value? Maybe you could record a `.gif` to understand better the way the crash presents to you. Thanks for all the feedback and info you can give us in order to reproduce this!

**Comment by ccordoba12** [comment]
@dalthviz, could deactivate the PyLS completions and only leave the ones from Kite to see what happens in that case?

**Comment by dalthviz** [comment]
@ccordoba12 deactivating the PyLS completions (which I think also deactivates the details widget and the on the fly completion) and just leaving the ones from Kite, make the Editor look more responsive. Also, seems like the modification of a file could trigger a big update in terms of code style (for example when adding a new line/modified line at the beginning of the file) making most of the following code being labeled with warnings):

![codes](https://user-images.githubusercontent.com/16781833/68550869-0f6de880-03d5-11ea-9ef2-ffa8d10b65e5.gif)

**Comment by ccordoba12** [comment]
Closing due to lack of response.

Thanks @dalthviz for your help here.
