### ISSUE TITLE
Spyder crashes on launch

### ISSUE THREAD

**Issue by OD1995** [spyder-ide/spyder#10642]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder fails to launch and instead the error below is returned:

<img width="272" alt="spyd err 3" src="https://user-images.githubusercontent.com/34351331/68476158-ebb67100-0221-11ea-9e4a-6f989f8f509a.PNG">

When attempting to debug:

<img width="354" alt="spyd err 1" src="https://user-images.githubusercontent.com/34351331/68476527-c9712300-0222-11ea-8896-16b52808c097.PNG">
<img width="187" alt="spyd err 2" src="https://user-images.githubusercontent.com/34351331/68476529-cb3ae680-0222-11ea-929a-dd58d8c931f7.PNG">

### What steps reproduce the problem?

1. Open Spyder

I had originally attempted to update my (working) Spyder 3.3.4 to Spyder 4.0.0rc1. But then when attempting to launch the new version, I got the issue above. I then uninstalled Anaconda and reinstalled, but this has not changed anything.

### What is the expected output? What do you see instead?

Spyder opening as normal

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
This looks like a problem with your Intel video card drivers, at least according to a quick Google search.

Unfortunately that's all we know and we can't help you further with this problem because we have no idea what's really happening.
