### ISSUE TITLE
Increase or make adjustable the maximum number of Recent Projects

### ISSUE THREAD

**Issue by sochtends** [spyder-ide/spyder#10640]
###  Problem Description

The number of Recent Projects is hard coded to 10 as can be seen from file 
https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/projects/plugin.py

    def add_to_recent(self, project):
        """
        Add an entry to recent projetcs
        We only maintain the list of the 10 most recent projects
        """
        if project not in self.recent_projects:
            self.recent_projects.insert(0, project)
            self.recent_projects = self.recent_projects[:10]

### What steps reproduce the problem?

1.  Discussed on Stackoverflow 
https://stackoverflow.com/questions/58748718/is-there-a-way-to-increase-the-maximum-number-of-recent-projects-in-spyder

### What is the expected output? What do you see instead?
It would be nice to increase to 50 or make adjustable the maximum number of Recent Projects.

## Versions

* Spyder version: 3.3.6

**Comment by ccordoba12** [comment]
@juanis2112, the idea here is to add a new entry to the "Recent projects" submenu

![Selección_001](https://user-images.githubusercontent.com/365293/68601490-6aa1e880-0472-11ea-9892-8b97ebd21fd1.png)

called "Maximum number of recent projects...", that works in the same way as "Maximum number of recent files..." in the "Open recent" submenu

![Selección_002](https://user-images.githubusercontent.com/365293/68601635-b3f23800-0472-11ea-97d7-a7c719e9444f.png)

**Comment by sochtends** [comment]
Thanks a lot for the feature! Really great!
