### ISSUE TITLE
Layout of undocked windows not saved on Spyder 4

### ISSUE THREAD

**Issue by Rational-IM** [spyder-ide/spyder#10649]
## Problem Description

I work with multiple 4K monitors and I believe the location of undocked windows is not holding, forcing me to rearrange a series of windows after each reboot. 

Carlos Cordoba requested that I opened a new issue here. Here is what he said on Google Groups: "Currently we're not saving the layout of undocked windows when closing Spyder, but it's definitely something we could do (we just haven't thought about it). Please open a new issue for it [on GitHub] so we don't forget to tackle it in the future."

This is suggestion is related to Spyder v4.0

**Comment by ccordoba12** [comment]
Thanks for opening this issue. We'll try to implement this enhacenment after releasing Spyder 4.

**Comment by miguelmhs** [comment]
Hello. I am interested in this enhancement too. Are you planning to be it released on Spyder 4.2?.

**Comment by ccordoba12** [comment]
Maybe, but it's not easy to solve.

**Comment by goanpeca** [comment]
@ccordoba12 would it not just be:

- Track docked state in the config,
- When closing spyder check plugins that are undocked and save the geometry (in a similar way we do for the mainwindow, and save this information also on the config?
- On start check which plugins are "undocKed" in the config and see if there is the geometry info available, and if available use it to"undock" the plugin and locate it accodrdingly?

**Comment by ccordoba12** [comment]
Yep, that sounds like a plan, but I don't see it as a simple fix.

And what about panes on multiple monitors? How to restore them properly?

Besides, we'd need to add an option for this, because perhaps some people don't want all their undocked plugins to be undocked again after a restart (see #12139).

**Comment by goanpeca** [comment]
>And what about panes on multiple monitors? How to restore them properly?

Hmmm I do not have an external monitor, so I cannot check atm. I would need to check a bit, but in theory doable as we can also save screen information (if needed).

>Besides, we'd need to add an option for this, because perhaps some people don't want all their undocked plugins to be undocked again after a restart (see #12139).

True, we would need an option for it.

**Comment by ccordoba12** [comment]
> but in theory doable as we can also save screen information (if needed).

Great!

**Comment by ybagdasa** [comment]
This would be a great feature. I always have to undock the editor every time I restart Spyder.

**Comment by brhubbar** [comment]
Poking this, I think it'd be a great feature to have for multiple monitor folks. I always undock my editor and move it to my 'tall' monitor, leaving the console and variable/file explorers docket together.
