### ISSUE TITLE
Snippets corrupted after completion inserted over placeholder

### ISSUE THREAD

**Issue by metalogical** [spyder-ide/spyder#10647]
## Problem Description

The placeholders visually don't line up after inserting a completion, and it selects the wrong thing after tab.

![2019-11-08 11 26 17](https://user-images.githubusercontent.com/1977419/68504817-beb29000-021a-11ea-8629-be1849f2eb6c.gif)

### What steps reproduce the problem?

See gif above.

### What is the expected output? What do you see instead?

1. `plt.plot(Ellipsis, [y], label=[str])` should be in the buffer (this is working as expected)
2. `[y]` and `[str]` should be the remaining placeholders (broken)
3. my cursor should automatically have jumped over to select `[y]` after inserting `Ellipsis`
    - I think it tries to automatically move to the next placeholder (?), but it doesn't work right.
4. after another tab, `[str]` should be selected as the active placeholder.

I started looking into this but the Snippets code is fairly complex, and @andfoy probably has more context here.

**Comment by plungg** [comment]
@andfoy has this been fixed for RC2, or do we expect it in by 4.0 release?

**Comment by ccordoba12** [comment]
This will be fixed for the final release.
