### ISSUE TITLE
Saving a protected file hangs Spyder

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#10657]
Here protected means "read only".
Actually I've tried to fix a python package (.py) directly in spyder, it hanged upon saving, instead than rejected the save without administrator rights.
[Window, last master, Python 3.6]

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix it after we release Spyder 4.

**Comment by endolith** [comment]
(Still running into this in Spyder 4.0.1.  Was very confused...)

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one asap.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one to see if you can reproduce it. @steff456 tried to generate the reported error on Windows and macOS, but she was unable to.

**Comment by dalthviz** [comment]
@ccordoba12 I was able to reproduce this trying to modify a file under `Program Files` on Windows (where admin rights are needed to modify files and usually users have `Read and Execution` rights only).

**Comment by dalthviz** [comment]
Note: After testing seems like an issue with `atomicwrites`

**Comment by ccordoba12** [comment]
Thanks @dalthviz! Please talk to @steff456 to let her know how to reproduce this problem and how you think i could be fixed.

**Comment by dalthviz** [comment]
Note: bug related to `tempfile` hanging in Windows https://bugs.python.org/issue1473760
