### ISSUE TITLE
comment line using CTL-1 doesn't comply to PEP8 rules

### ISSUE THREAD

**Issue by yshohet** [spyder-ide/spyder#10655]
### What steps will reproduce the problem?

in Prefernce checkbox "real time code style analysis" (refer to pep8 page)
go to any line in the code
line of code
CTL-1 to comment the line
#line of code
PEP8 warning shows up

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. That's already fixed and it'll be part of Spyder 4, to be released later this month.

**Comment by yshohet** [comment]
Thank you,
Yuval
