### ISSUE TITLE
Cannot open console with different interpreter

### ISSUE THREAD

**Issue by lululukas** [spyder-ide/spyder#10665]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have a fresh install of `spyder 4.0.0rc1` in its own conda env. Everything works like a charm, until I change the interpreter Spyder should use. The conda env is mainly to hold the Spyder beta, I don't want to install all my packages there. When I change the interpreter to the one from my base env, I cannot open consoles in Spyder anymore.

### What steps reproduce the problem?

1. Fresh install of `spyder 4.0.0rc1`
2. Change interpreter to anaconda base
3. Open a new console

### What is the expected output? What do you see instead?

Expected to get a new console, yet get below error message.

### Paste Traceback/Error Below (if applicable)

```

Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed. Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels

```

## Versions

* Spyder version: 4.0.0rc1 (initially ocurred with 4.0.0b2, since updated)
* Python version: 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

I've seen some solutions to similar issues mention `jupyter_core` and `jupyter_client`, their versions are 4.6.1 and 5.3.4 respectively.

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.7.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.29.3;<0.30.0        :  0.29.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
> When I change the interpreter to the one from my base env, I cannot open consoles in Spyder anymore.

You need `spyder-kernels` version 1.7.0 to work with Spyder 4.0.0rc1, so I guess you don't have that version in your base env.

You can install it with this command:

    conda install -c spyder-ide spyder-kernels=1.7.0

Please do that and let us know if it works for you.

**Comment by lululukas** [comment]
That was indeed the issue. I just installed it into another now env together with pandas etc.

I now have another problem with jedi. Somehow pyls expects version 0.15.1 but spyder requires 0.14.1. Anyway, different problem. Thanks for your help!

**Comment by ccordoba12** [comment]
Closing because I saw you opened a new issue about Jedi.
