### ISSUE TITLE
Resolution problem in Windows 10

### ISSUE THREAD

**Issue by ansin218** [spyder-ide/spyder#10666]
I have been a long term Spyder user, nearly 3 years, and have used it on Ubuntu 18.04 LTS without any problems. At work, I was also using it on Windows 7 without any problems. However, recently I had an upgrade to Windows 10 and since then the screen looks pretty unpleasant. I am facing this problem only in Spyder; some parts of the screen are just way too large and is hurting the eyes.

![2019-11-11 10_25_52-](https://user-images.githubusercontent.com/4587915/68577296-1564d780-0470-11ea-9763-9eea37aa7eb1.png)
![2019_11_11_10_40_41_Spyder_Python_3 7_](https://user-images.githubusercontent.com/4587915/68577299-16960480-0470-11ea-8269-a75e56d236b7.png)

I have Spyder as part of Anaconda distribution package with Spyder 3.3.6, I have also tried installing slightly older versions but the problem persists. 

My current Windows 10 display resolution is set to 1680x1050. I have checked other relevant links and I have also tried scaling the DPI from Spyder with different options like 0.5, 1, 1.5, 2.5 but to no luck. Can anyone please help me here?

**Comment by ccordoba12** [comment]
> I have also tried scaling the DPI from Spyder with different options like 0.5, 1, 1.5, 2.5 but to no luck.

What happens in this case?

**Comment by ansin218** [comment]
Thank you for responding @ccordoba12 !

Unfortunately, it doesnt rescale neatly. It just blows up in a worse manner (for ex: 2.5) or stays in the same way more or less (like 1 or 1.5).

**Comment by Dan-Patterson** [comment]
have you tried autoscaling and windows instead of windows-vista?

**Comment by ansin218** [comment]
Hey @Dan-Patterson Yes, I tried all. 

However, as strange as it may sound may be, I just reset it to factory defaults and restarted the OS, and now everything is back to normal. 

Hope this helps others.

**Comment by ccordoba12** [comment]
These are the best news, i.e. when bugs get auto-solved!
