### ISSUE TITLE
Docs Dont Say How to Start Spider after Installing with pip. 

### ISSUE THREAD

**Issue by hanoisteve** [spyder-ide/spyder#10667]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

For people new to Python we need to be able to just run Spider after install. There is a gap here between showing how to install the spider package and the docs showing screens of the app. How do I startup spider after the install?

     python spider
python: can't open file 'spider': [Errno 2] No such file or directory
(base) coffee:~ Steven$ spider
-bash: spider: command not found
(base) coffee:~ Steven$ 

Sure Im sure I am missing something but I dont claim to be a Python developer and the docs need to show how to startup the app.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> (base) coffee:~ Steven$ spider

The package is called **`spyder`**, not *spider*. And if you're using Anaconda (as the bash prompt above indicates), you don't need to use pip to install it, just conda.
