### ISSUE TITLE
Getting "kite_tutorial.py" has been modified outside Spyder message each time I use Kite's suggestion

### ISSUE THREAD

**Issue by sergeyFlakon** [spyder-ide/spyder#10675]
### Problem Description
Getting "kite_tutorial.py" has been modified outside Spyder message each time I use Kite's suggestion

### Steps:

1. Launch spyder and get kite_tutorial.py opened
2. Type something to this file // nothing will happen, and that's fine
3.  Go to line 88, put cursor to the right of "m" and press "ctrl+space" 
4. Pick suggestion and proceed with it

or:

1. Launch spyder and get kite_tutorial.py opened
2. Type something to this file
3. Switch to another window using alt+tab
4. Get back to Spyder ide

In both cases above I get  ("kite_tutorial.py" has been modified outside Spyder) message

![image](https://user-images.githubusercontent.com/25489358/68631086-6f11e400-04fa-11ea-9d49-d5f9ced77987.png)

### Expected: 
This message is nagging, and what's really is changing this file?

### Note: 
I'm launching editor through spyder.exe --debug-info verbose
This doesn't happen to other .py files

## Versions

* Spyder version: 4.0.0rc1 
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

**Comment by ccordoba12** [comment]
We already fixed this and it'll be part of our next release.

**Comment by sergved** [comment]
im encountering almost the same problem while working in my files, not only kite_tutorial.py. ""your_file.py" has been modified outside Spyder" - this message appears right before the suggestions window about to pop up. It appears from time to time, several times per hour, so i dont exactly know how to reproduce it.

**Comment by sergved** [comment]
> We already fixed this and it'll be part of our next release.

im encountering almost the same problem while working in my files, not only kite_tutorial.py. ""your_file.py" has been modified outside Spyder" - this message appears right before the suggestions window about to pop up. It appears from time to time, several times per hour, so i dont exactly know how to reproduce it.
