### ISSUE TITLE
Observing $0 / $1 vars in help topic name upon clicking a tooltip

### ISSUE THREAD

**Issue by sergeyFlakon** [spyder-ide/spyder#10674]
### Problem Description
Observing $0 at the end of help topic title upon clicking tooltip for suggestion

### steps:

1. create or open .py file with following content
```
import json
json
```
2. Put . to the right off **json** to get list of suggestions and tooltip for dumps(
3. Click tooltip
![image](https://user-images.githubusercontent.com/25489358/68630175-87343400-04f7-11ea-872f-1075dd0ef198.png)

This will open help page with $0 at the end of "dumps"
![image](https://user-images.githubusercontent.com/25489358/68630160-7be10880-04f7-11ea-86f3-de79c7904be4.png)

### Expected: 
Not to get "$0" at the end in this case

### Note: 
This happens only by clicking tooltip
ctrl+i won't make this to appear
Clicking on tooltip of json.loads shows **loads($1)$0** title
## Versions

* Spyder version: 4.0.0rc1 
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

**Comment by ccordoba12** [comment]
Good catch! We'll try to fix in our next version.

@dalthviz, please take a look at this one.
