### ISSUE TITLE
Fix path manager synchronize on windows

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10686]
After https://github.com/spyder-ide/spyder/pull/10623/, the sync was disabled. Need to reenable and make sure tests are correctly passing.

**Comment by jnsebgosselin** [comment]
@goanpeca If you need help with that, I can provide some. I'm familiar with this feature and I'm developing on windows, so this is "easy" for me to test or contribute. Just let me know.

**Comment by goanpeca** [comment]
@jnsebgosselin I am having some issues with Spyder master on my Windows VM.

Is Spyder working ok for you on master? I start it and after the ipython console loads, it just shuts down, no error trace or segfault message.

**Comment by jnsebgosselin** [comment]
Yes, it is working fine on latest master.

**Comment by goanpeca** [comment]
Hmm ok, :-p trying out some things. I will work on this @jnsebgosselin no worries ;-)

**Comment by jnsebgosselin** [comment]
> I will work on this @jnsebgosselin no worries ;-)

Excellent, thank you very much! I was afraid to see this feature go.

Updating the python paths through the `Windows Environment Variables` manager is a pain. It was significantly improved in Windows 10 compared to 7, but it is still way more easy to do it with Spyder.

**Comment by goanpeca** [comment]
>Updating the python paths through the Windows Environment Variables manager is a pain. It was significantly improved in Windows 10 compared to 7, but it is still way more easy to do it with Spyder.

It was just a temporary disable ;-), no worries

**Comment by jnsebgosselin** [comment]
> @jnsebgosselin I am having some issues with Spyder master on my Windows VM.
> 
> Is Spyder working ok for you on master? I start it and after the ipython console loads, it just shuts down, no error trace or segfault message.

I just realized, last week Spyder stopped working for me too after updating it on master. I tried a bunch of stuff and ended up reinstalling it in a new conda environment.

So I don't know when the last time you logged into you Windows VM, but maybe the same thing is happening to you.

**Comment by goanpeca** [comment]
>I just realized, last week Spyder stopped working for me too after updating it on master. I tried a bunch of stuff and ended up reinstalling it in a new conda environment.

I had to do the same thing!

**Comment by ccordoba12** [comment]
Nice to know that that's another of the hidden gems Spyder users find very valuable!
