### ISSUE TITLE
Some proposed improvements to the file switcher

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#10682]
**1. Make items sorted in ascending order**

I think it would make more sense to sort the **filtered** items in ascending order instead of descending order in the switcher.

![image](https://user-images.githubusercontent.com/10170372/68684032-ca14fc80-0535-11ea-82a3-63c246c8ed8c.png)

**2. Make the list view looks like is has the focus.**

The focus is given to the line edit of the switcher, while the focus policy of the list view is set to `NoFocus`. This is not a big deal, but this make the selected item in the list looks like it is not active (while in reality, it is implemented in such a way that it has the functionality of an active list view, i.e. navigation with the arrows, selection with enter, etc).

So, I think the switcher should look like it has the focus and is active as a whole. I suggest that we trick the html delegate that is used in the list view into thinking that it is active at all times, even if strictly speaking it is not. 

![image](https://user-images.githubusercontent.com/10170372/68682829-c2ecef00-0533-11ea-985c-fb85899db25d.png)

## Versions

* Spyder 4.0.0.dev0 (Commit: a74824da2) 
* Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by goanpeca** [comment]
>I think it would make more sense to sort the filtered items in ascending order instead of descending order in the switcher.

That is probably a regression from moving to the new switcher. 👍 

>So, I think the switcher should look like it has the focus and is active as a whole. I suggest that we trick the html delegate that is used in the list view into thinking that it is active at all times, even if strictly speaking it is not.

Sounds good too !

Could you open a PR @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
> Could you open a PR @jnsebgosselin ?

Yes, I'm already working on this 👍

**Comment by ccordoba12** [comment]
I agree with both suggestions. Thanks @jnsebgosselin for helping us with them!
