### ISSUE TITLE
Autocompletion not working if jedi 0.15.1 was previously installed in env (Spyder 4.0.0rc1)

### ISSUE THREAD

**Issue by lululukas** [spyder-ide/spyder#10680]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I installed spyder-4.0.0rc1 into a conda env that previously had jedi 0.15.1 installed. I have jedi 0.14.1 now, which is the version required by spyder, but when I start Spyder it complains about not finding METADATA of **jedi 0.15.1** dist-info. Solved that by removed the dist-info folder of 0.15.1 that was still present in the site-directory of the env. However, I now don't get an error anymore, yet also no autocompletion.

As a workaround, I installed Spyder into its own conda env and use the interpreter from the other env that also has the correct `spyder-kernels` version installed. Like this, I have autocompletion and can use all packages installed in the second env. The only problem is that now I cannot open variables from the variable explorer anymore. I get the error:

```
Spyder was unable to retrieve the value of this variable from the console.

The error message was:
'tuple' object has no attribute 'raise_error'
```

This does not seem to dependent on the actual type of the variable. Should I make a separate issue for this? I'd prefer to just install Spyder 4 into my base env, but there I also have jedi 0.15.1 so I expect the same issue.

### What steps reproduce the problem?

1. Install Spyder 4.0.0rc1 into env that previously had jedi 0.15.1 installed
2. Run `spyder`

### What is the expected output? What do you see instead?

Expected autocompletion to work with correct version of jedi installed. Instead no autocompletion available, even though in an install in a clean env with the same version of jedi autocompletion works.

## Versions

* Spyder version: 4.0.0rc1
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

```
$ conda list | grep jedi
jedi                      0.14.1                   py37_0    spyder-ide
```

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.7.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.29.3;<0.30.0        :  0.29.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
> I installed spyder-4.0.0rc1 into a conda env that previously had jedi 0.15.1 installed. I have jedi 0.14.1 now, which is the version required by spyder, but when I start Spyder it complains about not finding METADATA of jedi 0.15.1 dist-info. Solved that by removed the dist-info folder of 0.15.1 that was still present in the site-directory of the env. However, I now don't get an error anymore, yet also no autocompletion.

Ok, thanks for letting us know about this, it's a very serious issue indeed. How did replace Jedi 0.15.1 with 0.14.1? Did you use pip for that?

> The only problem is that now I cannot open variables from the variable explorer anymore

This is very serious too. Please open a new issue about it so here we focus only on the Jedi problem.

**Comment by lululukas** [comment]
Excuse late reply.

> How did replace Jedi 0.15.1 with 0.14.1? Did you use pip for that?

`conda install` of spyder 4.0.0rc1 automatically downgraded jedi.

> This is very serious too. Please open a new issue about it so here we focus only on the Jedi problem.

To be clear, this only happens when choosing a different interpreter than the one of the env in which Spyder is installed.

**Comment by ccordoba12** [comment]
> To be clear, this only happens when choosing a different interpreter than the one of the env in which Spyder is installed.

Sure, I understand that.

**Comment by ccordoba12** [comment]
This was not reported by anyone else, so I think it was a problem with your setup.
