### ISSUE TITLE
Fix several UI issues

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10687]
- [ ] Reduce size and change icon of Previous/Next path Icons on global directory
- [ ] Add margin on toolbars
- [ ] Reduce a little size of icons on toolbars
- [ ] Add separators for toolbars
- [ ] Fix rounded cropped corners on dockwidgets

**Comment by dalthviz** [comment]
Superseded by https://github.com/spyder-ide/ux-improvements/issues
