### ISSUE TITLE
Code completion complete the parameters inside the function

### ISSUE THREAD

**Issue by rotemgb** [spyder-ide/spyder#10699]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Auto-complete adds the parameters inside the function.
![Screenshot from 2019-11-13 15-42-29](https://user-images.githubusercontent.com/35784524/68813966-5bff3100-062c-11ea-9251-c4bee029cacd.png)

### What steps reproduce the problem?

1. Type `for i in ran` and hit enter or tab to complete

### What is the expected output? What do you see instead?
The expected output is either `for i in range` or `for i in range()`.

Instead, the output is `for i in range(start, stop)`

## Versions

* Spyder version: 4.0.0.dev0
* Python version:  3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Pop_Os 19.10, Linux 5.3.0-20-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.7.0;<2.0.0:  1.7.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.29.3;<0.30.0        :  0.29.3 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by rotemgb** [comment]
I just saw a PR from few days ago, and realized it's an improvement for the code completion. I was just not used to it, and didn't realize I can press Tab to change the parameters. Sorry for that.. I'm closing the issue.

**Comment by ccordoba12** [comment]
@rotemgb, yes, this an improvement we added for Spyder 4. I'd like to know (from a user perspective), what's your opinion about it? Do you think it's easier to understand and use?

**Comment by rotemgb** [comment]
After some time getting use to,I found it useful in most cases. The only times it was slowing me down was when it autocomplete parameters which I don't necessarily need. For example, the 'start' parameter in range(), which is not needed in some case.
The other thing is when I want to import a function from a module. Although I notice I can import it as text, and then it doesn't autocomplete the parameters, it takes paying more attention.
I hope that's helpful.. :)

**Comment by ccordoba12** [comment]
Thanks for your feedback @rotemgb!

> The other thing is when I want to import a function from a module. Although I notice I can import it as text, and then it doesn't autocomplete the parameters, it takes paying more attention.

What do you mean exactly by this?
