### ISSUE TITLE
my file just got deleted by itself when I was saving

### ISSUE THREAD

**Issue by bhuv-nesh-alt** [spyder-ide/spyder#10693]
### What steps will reproduce the problem?

i just created a program for extracting slices from list for running the program i was saving it and it id not got saved i tried to save it again and it suddenly vanished i do not konw how

please help 

I am not that free to create program again nd again

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
We're sorry but unless your file was under version control (i.e. git or mercurial) there's nothing we can do about it.

However, this is going to be improved in Spyder 4, to be released at the end of this month.
