### ISSUE TITLE
Autocomplete in the console only displays file extensions

### ISSUE THREAD

**Issue by ortk95** [spyder-ide/spyder#10692]
### What steps will reproduce the problem?

When typing a filename in the console, the autocomplete suggestions (from pressing TAB) only show the file extension and not the full filenames.

For example, if a directory contains the following files:

```
$ ls
file.txt     script1.py   script2.py   script3.sh   script4.a.b
```

When typing a command such as ```edit s``` into the console, then pressing TAB to bring up the autocomplete suggestions, I get the suggestions

```
py
py
sh
b
```
for the files, whereas I would expect these to be the full filenames, i.e.

```
script1.py
script2.py
script3.sh
script4.a.b
```
Selecting any of the suggestions will autocomplete the correct full filename, so it is just an issue with the names *displayed* in the dropdown suggestions.

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.14.1 (OK)
psutil >=0.3      :  5.6.5 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.17.3 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.14 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.9.0 (OK)
matplotlib >=2.0.0:  3.1.2 (OK)
pylint >=0.25     :  2.4.3 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one. This problem was introduced by some changes you did in qtconsole to improve how code completion works there.
