### ISSUE TITLE
spyder crashed

### ISSUE THREAD

**Issue by DeLaRiva** [spyder-ide/spyder#10707]
### What steps will reproduce the problem?

The issue occured when I was about to mark a line in the variable/dataframe inspector.

**Comment by goanpeca** [comment]
Please provide more information next time as requested on the issue tenplate.

**Comment by DeLaRiva** [comment]
This was the automatic response by Spyder as sending through Spyder didn't work. And that was the generic text it created on its own so I just performed that as I thought, when the system uses this kind of information, the devs know what they want ;)

However, I had this problem in a dataframe (125 columns and 64 rows) which I converted by a certain formula into another dataframe (125 columns and 64 rows). While each process worked, I couldn't inspect the dataframe in Spyder..  at column.. I don't know, let's say 20+ it crashed or rather it froze. But when trying to slide back to the first columns several times, it worked again - until I reached that certain column again.
The error is reproducible, so also restarting and so on didn't change anything.
