### ISSUE TITLE
Spyder opens with an error message which doesn't go away with re-loading Anaconda

### ISSUE THREAD

**Issue by sentier1** [spyder-ide/spyder#10700]
### Issue Report Checklist

* [v ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [v] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [v] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [v] Tried basic troubleshooting (if a bug/error)
    * [v] Restarted Spyder
    * [v] Reset preferences with ``spyder --reset``
    * [v] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [v] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I open Spyder it shows error in Console

### What steps reproduce the problem?

1. starting Spyder from Anaconda3
2. re-installing Anaconda a few times, putting it in different directories, just for me or for all users, also ran from venv
3. same thing if run from prompt, also from inside the spyder app 

I am new to Python and programming, could not figure out how to run from Jupyter

### What is the expected output? What do you see instead?

error message which is impossible to get rid of

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 100, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 53, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: The specified procedure could not be found.
```

## Versions

* Spyder version: 3.6.6
* Python version: 3.7.0
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
IPython >=4.0     :  7.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by AxelMKlein** [comment]
I'm affected with the same effects.

**Comment by ccordoba12** [comment]
This is not a problem in our code. Please report it here:

https://github.com/jupyter/jupyter_client

**Comment by sentier1** [comment]
Nice and helpful reply...Thahks(+34) 6 3031 2442 

    On Friday, 15 November 2019, 17:45:37 CET, Carlos Cordoba <notifications@github.com> wrote:  
 
 
This is not a problem in our code. Please report it here:

https://github.com/jupyter/jupyter_client
