### ISSUE TITLE
Errors when removing variables in the Variable Explorer

### ISSUE THREAD

**Issue by Lee-Lilly** [spyder-ide/spyder#10709]
## Problem Description
In panel "Variable explorer", right click on a variable, select "remove". It deletes the variable below instead of deleting the current variable

### What steps reproduce the problem?
1. Run a python script, which returns several variable
2. Open variable explorer, right click on a variable, select "remove".

### What is the expected output? What do you see instead?
Expected: to remove the chosen variable
Instead: the variable below (on the list) was removed.

## Versions
* Spyder version: 4.0.0 rc1
* Python version: 3.7.4 (64-bit)
* Qt version: 5.9.2
* PyQt version:  5.9.6
* Operating System name/version: Windows 10

**Comment by goanpeca** [comment]
@dalthviz could you take a look?

**Comment by bcolsen** [comment]
This problem was mentioned in #10702 as well

**Comment by Khalilsqu** [comment]
@dalthviz 
A similar error also exists for the function rename.
![rename](https://user-images.githubusercontent.com/22060413/68987975-795d1680-0849-11ea-8853-ad44583f3e7b.gif)

commit = [c8ea0afa0](https://github.com/spyder-ide/spyder/commit/c8ea0afa0)

**Comment by ccordoba12** [comment]
@Khalilsqu, please open a new issue about that.
