### ISSUE TITLE
Add a clock to the statusbar

### ISSUE THREAD

**Issue by rotemgb** [spyder-ide/spyder#10712]
## Description
I usually work in a fullscreen mode, and I find having a clock on the statusbar help the workflow.

![Screenshot from 2019-11-14 13-35-41_edited](https://user-images.githubusercontent.com/35784524/68903428-f83e3c00-06ef-11ea-87e9-e717c2f8ea9f.png)

I am willing to open a PR for that if you find it a useful widget to add.

**Comment by ccordoba12** [comment]
> I usually work in a fullscreen mode

I think it'd be very valuable to a have a clock for this use case.

@goanpeca, what do you think?

**Comment by goanpeca** [comment]
>@goanpeca, what do you think?

Sounds good :-) !

**Comment by ccordoba12** [comment]
Please go for it @rotemgb!
