### ISSUE TITLE
runfile changes the current tab in the editor

### ISSUE THREAD

**Issue by Lo-Srt** [spyder-ide/spyder#10736]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

First of all, I guess this is more of an inconvenience than a real problem. Since Spyder 4.0.0b7, calling `runfile("someFile.py")` in the iPython console produces the following behavior :
- If `someFile.py` is not open in the editor, just execute `runfile`
- If `someFile.py` is open in the editor, execute `runfile` **and switch to the corresponding tab**

Sometimes you need to run / re-run some main file many times while working on another, and having to switch back from the former to the latter each time you execute runfile (or press F6) is quite annoying.

It seems that this behavior was not present in Spyder 4.0.0b6.

### What steps reproduce the problem?

1. Open two files `a.py` and `b.py` in the editor
2. Go to tab of `b.py` and execute `runfile("a.py")` (or press F6 after having run `a.py` beforehand)

## Versions

* Spyder version: Spyder 4.0.0rc1 
* Python version: Python 3.6.9 64-bit 
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version:  Ubuntu 18.04  /  Linux 4.15.0-66-generic

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this one?

**Comment by impact27** [comment]
How about `runcell`? Should runcell switch to the tab? I think it makes sense for runcell at least.

**Comment by bcolsen** [comment]
> How about runcell? Should runcell switch to the tab? I think it makes sense for runcell at least.

I could see that someone might make a cell in a different file that processes or displays data from the current file kind of like a using a function. If people are running things from the console it might be because they don't want the editor to change.

**Comment by impact27** [comment]
> If people are running things from the console it might be because they don't want the editor to change.

Agreed, I updated the PR.
