### ISSUE TITLE
changed py path

### ISSUE THREAD

**Issue by adills** [spyder-ide/spyder#10737]
### What steps will reproduce the problem?

I used steps here:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

so that I can run a specific pipenv environment.

### Traceback
```python-traceback
  File "/usr/local/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch

```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.5
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.5 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.9.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
You need to have spyder-kernels 0.5.2 in your external interpreter. Please verify that that's the case and try again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by adills** [comment]
After installing spyder-kernels 0.5.2 in my environment it worked. I previously had a later kernel version installed.
