### ISSUE TITLE
Variable explorer viewers too small on high DPI

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10745]
On both Spyder 3.3.6 and Spyder 4.0.0rc1, when I tried to view some variable by double-clicking a variable from the variable explorer, I found the popup window is too small (in terms of the proportion to the whole screen).

I am using Ubuntu 18.04 on a 4k monitor, with a system-wide 200% zoom.

I tried to play with Spyder's high DPI scaling options (setting it to auto, or to manual 1.5, or to manual 1), and did not see any significant changes.

**Comment by ccordoba12** [comment]
I think our viewers have a fixed size, and that was adjusted for non-high resolution monitors.

This is a very low priority issue for us, so maybe you or someone else in the community would like to tackle it.

**Comment by jsh9** [comment]
Could you point me to the place in the code base? I may try to fix it, but I need some pointers first :)

Thanks!

**Comment by ccordoba12** [comment]
Our viewers are placed here

https://github.com/spyder-ide/spyder/tree/master/spyder/plugins/variableexplorer/widgets

**Comment by jsh9** [comment]
Hi @ccordoba12 , I found the hard-coded window sizes in this folder. Those numbers were written down 10 years ago, when the mainstream screen resolution was around 1024 x 768. That's why the variable explorer windows look so small on today's monitors.

I can manually increase the window sizes and submit a pull request.

One question: I also found that some dialog box (such as "Open file...") to be also very small. Shall I also fix it?  If so, please point me to the directory.

**Comment by ccordoba12** [comment]
> I can manually increase the window sizes and submit a pull request.

Well, perhaps we should detect if the window is high resolution or not and adjust the sizes accordingly. I say it because the current sizes are still fine for me in regular screens.

> One question: I also found that some dialog box (such as "Open file...") to be also very small. Shall I also fix it? If so, please point me to the directory.

Is not that defined by the operating system? How does that dialog look in other applications?

**Comment by jsh9** [comment]
Could you tell me how we can detect screen resolution? Are there any Python libraries?
  A few things we need to consider:
- Cross platform
- Real time detection? (If I have two monitors with different resolutions, and I could potentially more Spyder from one monitor to another any time.)

If we don't want to dynamically adjust the variable explorer window size, we can use some hard-coded window sizes that are more suitable for today's standard.

For example, I think most Spyder users use 1920 x 1080, 2560 x 1440, 3840 x 2160, and in-between resolutions (such as macbook pros). Very few people may still use low resolutions such as 1366 x 768, so we won't let our hard-coded window exceed 1200 pixels in length and 760 pixels in height. Then I feel like we can find a happy middle ground for most people.

===============
As for the "Open file" dialog box, I suppose you are right: its size is defined by the OS, so we can't do anything about it.

**Comment by ccordoba12** [comment]
> Could you tell me how we can detect screen resolution?

That's when things get complex. @dalthviz, please give @jsh9 a hand on how to detect the resolution of the screen in which Spyder is running.

> For example, I think most Spyder users use 1920 x 1080, 2560 x 1440, 3840 x 2160, and in-between resolutions (such as macbook pros)

I don't think you could find a size that goes with both high and regular screens. Besides, very few in our team have screens with such resolutions (I certainly don't), so you have to submit a PR that works for us too.

**Comment by jsh9** [comment]
Are all of your screen resolutions between HD (1920 x 1080) and 4k (3840 x 2160)? If so, then the static numbers that I have in mind will work fine for you.

Detecting screen resolutions seems a bit of an overkill: current Spyder doesn't do it for variable explorer windows, so there isn't really a big reason for us to suddenly start doing so. All I think is necessary is to upgrade the size to to a larger standard.

**Comment by ccordoba12** [comment]
> Are all of your screen resolutions between HD (1920 x 1080) and 4k (3840 x 2160)?

No, they aren't, they are smaller. That was my point precisely.

**Comment by jsh9** [comment]
Do you know how much smaller?

**Comment by ccordoba12** [comment]
Whatever number I can give would be arbitrary, i.e. there could still be people using Spyder with 1366x768 screens.

Look, you're not going to get away with a fixed size, sorry to put it plain and simple. As I said, you need to detect the screen resolution and generate the size dynamically.

**Comment by jsh9** [comment]
> For example, I think most Spyder users use 1920 x 1080, 2560 x 1440, 3840 x 2160, and in-between resolutions (such as macbook pros). Very few people may still use low resolutions such as 1366 x 768, so we won't let our hard-coded window exceed 1200 pixels in length and 760 pixels in height. Then I feel like we can find a happy middle ground for most people.

Please see this from my previous reply. I don't plan to go above 760 pixels in height.

The current implementation in Spyder can get away with a fixed size, so I don't see why the proposed new plan has to use a dynamic size. Do you have some special considerations?

**Comment by jsh9** [comment]
In any case, I'll wait for @dalthviz 's input on how to detect screen resolution, and I'll push two versions (fixed size vs dynamic size) for you all to take a look.

**Comment by dalthviz** [comment]
Hi @jsh9 just in case [here](https://github.com/spyder-ide/spyder/pull/10880#issuecomment-559881109) is the comment about a possible way to set the dialog size dynamically
