### ISSUE TITLE
Hitting "Enter" not always work in ipython console

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10746]
In the IPython console of Spyder, usually we type some command, such as `a = [1, 2, 3]`, and hit "Enter" to execute it.

I've found that sometimes hitting "Enter" won't execute the command, the cursor only goes to a new line (same behavior as "ctrl + enter"). I have to use "shift + enter" to actually execute it.

This happens sporadically and on both Spyder 3.3.x and Spyder 4.0.x. There is no prediction of when this happens.

So I think this maybe a bug?

**Comment by ccordoba12** [comment]
> So I think this maybe a bug?

Yes, it is. I should be fixed in qtconsole **4.6.0**, just released today. Conda packages should be available shortly.
