### ISSUE TITLE
new environment in anaconda,conda install spyder,open the spyder occur the problem.

### ISSUE THREAD

**Issue by 1731lin** [spyder-ide/spyder#10748]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

AttributeError: module 'dateutil.tz' has no attribute 'UTC'
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
AttributeError: module 'dateutil.tz' has no attribute 'UTC'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.25.3 (OK)
numpy >=1.7      :  1.17.4 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.14.0 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
> Spyder Version: 3.2.3

This version is very old. Please update to a newer version and try again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by 1731lin** [comment]
> > Spyder Version: 3.2.3
> 
> This version is very old. Please update to a newer version and try again.

thanks，i took care of it
