### ISSUE TITLE
Difficulty updating to Spyder 4.0.0rc1

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10744]
I installed Anaconda 3 (with Spyder 3.3.6), and I wanted to upgrade to Spyder 4.0.0rc1, so I ran
```
conda update qt pyqt
conda install -c spyder-ide spyder=4.0.0rc1
```
But dependency solving took a long time finally `conda` told me the conflict was too much.

So I used `conda uninstall spyder` to try to uninstall 3.3.6, but it turned out that lots of the packages (such as numpy, matplotlib, etc) got uninstalled together.

Is there an easier way to upgrade to Spyder 4?

**Comment by ccordoba12** [comment]
> Is there an easier way to upgrade to Spyder 4?

Yes, please create a new conda env for it instead of trying to install it in the base env or a previous env you have.
