### ISSUE TITLE
ubuntu16.04 right click on keyboard causes quit

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#10759]
### What steps reproduce the problem?

**1. Use spyder in ubuntu16.04, when I click the right-click button on keyboard, it makes spyder quit. Seemed when install spyder on a new ubuntu, so came the problem. When use right-click button on there app in computer, there is no problem, but got crazy on spyder. When coding, quit, god!!!**

### What is the expected output? What do you see instead?

Fix this!

## Versions

* Spyder version: 3.3.6
* Python version: 3.6.5
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: ubuntu16.04

**Comment by ccordoba12** [comment]
If you're using Anaconda, please update PyQt and try again.

**Comment by ccordoba12** [comment]
And for that please open a terminal and run

    conda update qt pyqt

**Comment by zysNLP** [comment]
@ccordoba12 Thank  you, but it seemed not work. I update qt to 5.9.6 and pyqt to 5.9.2, when start spyder in a new Terminal, right-click on keyboard still make spyder quit.

**Comment by zysNLP** [comment]
After the spyder was closed with the right-click button, a line of "Segmentation fault (core dumped)" appeared in the Terminal.

**Comment by ccordoba12** [comment]
> right-click on keyboard

What do you mean by this?

**Comment by zysNLP** [comment]
@ccordoba12 A button on our computer keyboard. It's to the left of CTRL, to the right of ALT or Fn

**Comment by ccordoba12** [comment]
I'm sorry but I have no more advice for you.

**Comment by ccordoba12** [comment]
Please try Spyder 4 when it comes up. Maybe that fixes your problem.
