### ISSUE TITLE
Automatic error repoit should be more reminder, like pycharm, and it should be convenient to set a breakpoint to debuggingrt

### ISSUE THREAD

**Issue by guanyonglai** [spyder-ide/spyder#10768]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
> Automatic error repoit should be more reminder, like pycharm

That's your opinion, but thanks for the suggestion.
