### ISSUE TITLE
Fails to install Spyder4.0.0rc2 on Windows due to ujson dependency

### ISSUE THREAD

**Issue by jcafhe** [spyder-ide/spyder#10763]
## Problem Description
First of all, this is a dependency issue so it may be not solved by the Spyder-team but I thought that you may want to know about it.

Spyder 4.0.0rc2 actually fails to install (via pip) on Windows if MSVC compiler is not installed. This is related to the fact that some dependencies depend on `ujson` package, which require MSVC 14 as shown in the log below.

So the dependency tree goes like that: rc2 requires `python-language-server` 0.31.0, which requires `ujson` and `python-jsonrpc-server` 0.3.0, which requires `ujson` too:
```
spyder 4.0.0rc2
    python-language-server 0.31.0
        ujson (since python-language-server 0.31.0, previous 0.30.0)
        python-jsonrpc-server 0.3.0
            ujson (since python-jsonrpc-server 0.3.0, previous 0.2.0)
```

This is working with rc1 when pre-installing first python-jsonrpc-server v0.2.0, then python-language-server 0.30.0.

### What steps reproduce the problem?

1. Install release candidate 2 on W10  `pip install --pre spyder`

### Error

```
[...]
  Running setup.py install for ujson ... error
[...]
    Warning: 'classifiers' should be a list, got type 'filter'
    running install
    running build
    running build_ext
    building 'ujson' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
```

## Versions

* Spyder version: -
* Python version: 3.7.5
* Qt version: -
* PyQt version: - 
* Operating System name/version: Windows 10, AMD64

**Comment by ccordoba12** [comment]
Sorry but ujson increases a lot the responsiveness of code completion and linting in our editor.

Besides, we only support Anaconda, so it seems this will really make people move to it.

**Comment by ccordoba12** [comment]
> we only support Anaconda

By this I mean that even if we provide wheels and give people the ability to use pip to install Spyder, we really don't have the time to support it, so we'd prefer most of our users to switch to Anaconda instead.

**Comment by jcafhe** [comment]
Ok, thanks for your clarification.

**Comment by ccordoba12** [comment]
On a second thought, we're going to address this because members of our team are also suffering from it. Sorry if I sounded harsh before.

**Comment by ilayn** [comment]
I encountered this and I don't understand this response at all. If this is going to be an Anaconda product, then please put a disclaimer on it in caps-lock. 

If you fix only problems that your team members encounter then probably it is time for me to move away from this project.

**Comment by ccordoba12** [comment]
> I encountered this and I don't understand this response at all. If this is going to be an Anaconda product, then please put a disclaimer on it in caps-lock.

There is not, but we're going to integrate even further with Anaconda in the future.

> If you fix only problems that your team members encounter then probably it is time for me to move away from this project.

That's your choice.

**Comment by tstreibl** [comment]
I like spyder and I like winpython. Therefore, I hope spyder doesn’t become incompatible to standard python distributions when it integrates further with Anaconda. In this sense, I would be happy to see all the nice new spyder 4 capabilities coming sooner or later to winpython, too. You have a large winpython fanbase out there!

**Comment by ccordoba12** [comment]
> Therefore, I hope spyder doesn’t become incompatible to standard python distributions when it integrates further with Anaconda

It won't. We just plan to add more functionality based on conda (like environment management).

> You have a large winpython fanbase out there!

Ok, thanks for letting us know about it! We didn't know, so we're leaned towards Anaconda.

In any case, this is an easy to fix error and @dalthviz already created two PRs for it.
