### ISSUE TITLE
Ipython console not starting with interpreter from another environment

### ISSUE THREAD

**Issue by GPoloVera** [spyder-ide/spyder#10773]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Following the modular approach of #Working with packages and environments in Spyder#, the Ipython console fails to start with this message (installing just spyder on the environment):
 "Your Python environment or installation doesn't have the spyder‑kernels ..."
On the virtual env ** with Python version 3.6** doing $pip list | grep spyder you can see that the spyder-kernels 0.5.2 is installed, I have also tried with the last version spyder-kernels 1.8 but I have read that this is for Spyder version 4, just to trhoubleshooting, the same problem.
I have updated spyder in the spyder_env conda environemt ($conda update spyder).

### What steps reproduce the problem?

1.  Create a conda environment with just spyder: $conda create --name spyder_env spyder **This environtment has Python version 3.7**
2. Within a virtualenv, install using pip the spyder-kernels 0.5.2 package: (env) $ pip install spyder-kernels==0.*  Note: **This environtment has Python version 3.6**
3. Run the command to copy the python interpreter path: $ python -c "import sys; print(sys.executable)"
4.  Deactivate the virtualenv: (env) $ deactivate
5. Activate the spyder_env: $ conda activate spyder_env
6. Launch Spyder: $ spyder &
7. Go to preferences > Python Interpreter > Use the following interpreter: Paste the path 
/Users/gonzalopolo/Projects/semantic-analyser/env/bin/python

### What is the expected output? What do you see instead?
Now, once I apply this interpreter of the virtualenv where spyder-kernels has been installed, the IPython console says in a Red box "An error ocurred while starting the kernel" and telling theat the spyder-kernels module is not installed or the version is not correct. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

NO ERROR TRACEBACK APPEARS on the console

```

## Versions

* Spyder version: 3.3.6
* Python version: Python 3.7.0 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: macOS Mojave version 10.14.6

### Dependencies

```
IPython >=4.0     :  7.9.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
psutil >=0.3      :  5.6.5 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
> Within a virtualenv, install using pip the spyder-kernels 0.5.2 package

This is the problem (I think): You can't mix conda and pip packages.

**Comment by GPoloVera** [comment]
I dont think this is the only problem.
Just to give more information, if you create an environment with the same version of the one you want Spyder to use its interpreter everithing works fine:
`$conda create --name spyder_env python=3.6 spyder`
So now, bot environments (the conda one and the virtualenv one) have the Python version 3.6. Doing so everything works fine and Spyder is running like within the virtualenv environment, but only if the python version is the same.
