### ISSUE TITLE
Debugger console doesn't allow editing command

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10770]
When I'm in the debugging mode, I can use the debugger console to view variables, for example:

```python
print(a)
```

And I can also use the up/down arrow key to select previous commands.

However, when I use the up arrow key to select a previous command (for example, `print(a)`), I cannot use left/right arrow keys or Backspace to edit `print(a)`. I have to type everything manually all over again.

Is this a bug, or by design?

(Found this issue in both Spyder 3.x.x and Spyder 4.0.x)

Thanks!

**Comment by ccordoba12** [comment]
Please upload a video (animated gif) to better understand what's happening here.

**Comment by jsh9** [comment]
Please take a look:

![debug](https://user-images.githubusercontent.com/25124332/69319656-76b94300-0bf4-11ea-9504-4862f93c4f8a.gif)

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this one?

**Comment by impact27** [comment]
This looks like a bug with an old version of qtconsole. Could you update qtconsole and report back?

**Comment by impact27** [comment]
For reference: https://github.com/jupyter/qtconsole/pull/331

**Comment by jsh9** [comment]
I upgraded `qtconsole` to the newest version, and the problem was resolved.
