### ISSUE TITLE
Alt+Space shortcut cannot be set in Spyder 4

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#10786]
Moved to Spyder 4 RC2 - awesome work guys! The dark theme is super slick!

I miss something from previouos Spyders  though - I cannot set the `Alt+Space` shortcut anymore. I had this for delete line (and have it in all my other editors). 

So if it's fixable I would appreciate if you can bring it back : )

**Comment by ccordoba12** [comment]
Ok, we'll take a look at it in the future.

**Comment by jnsebgosselin** [comment]
Please see https://github.com/spyder-ide/spyder/issues/7981, it is closely related to the issue reported here.

**Comment by jnsebgosselin** [comment]
Also, @gerazov, what is your operating system? Thanks!

**Comment by gerazov** [comment]
Yeah, I saw #7981 but most of it was about Emacs support, I just wanted my shortcut back :smile: 
I'm on Manjaro 18.1.2 with KDE running on kernel 5.3.8-3.

**Comment by jnsebgosselin** [comment]
> Yeah, I saw #7981 but most of it was about Emacs support, I just wanted my shortcut back 😄
> I'm on Manjaro 18.1.2 with KDE running on kernel 5.3.8-3.

What happens when you try to set the shortcut with `Alt + Space`?

**Comment by gerazov** [comment]
Nothing happens - like I didn't press anything, but `Alt+x` gets registered fine.

**Comment by FabianHofmann** [comment]
Hey, I'm having the same issue using Ubuntu 18.04

**Comment by ccordoba12** [comment]
@FabianHofmann, those kind of comments are not helpful. For next time please leave an emoji reaction on the issue description.

**Comment by jnsebgosselin** [comment]
> 
> Nothing happens - like I didn't press anything, but `Alt+x` gets registered fine.

Ok thanks. I don't understand why it is not registered because we are not blocking it. So if the OS is not eating the event, it should be passed to the shortcut editor dialog. 

When you press `Alt + Space` in the Editor, is this registered as a normal space? Sorry, but I don't have access to your OS, so I'm trying to guess where the problem is from your inputs.

**Comment by goanpeca** [comment]
>Manjaro 18.1.2 with KDE running on kernel 5.3.8-3.

I could create a VM later and try to see what the issue is. On Mac `alt+space` is registered fine.

**Comment by goanpeca** [comment]
This is close enough, right?
https://osdn.net/projects/manjaro/storage/kde/18.1.3/manjaro-kde-18.1.3-191114-linux53.iso/ @gerazov ?

**Comment by jnsebgosselin** [comment]
> 
> 
> > Manjaro 18.1.2 with KDE running on kernel 5.3.8-3.
> 
> I could create a VM later and try to see what the issue is. On Mac `alt+space` is registered fine.

Cool thanks! On Windows, I haven't found a way yet to override without some dirty hack the `open the window menu`  that is triggered by `Alt + Space`.

**Comment by goanpeca** [comment]
>without some dirty hack 

We will probably need to do this anyway even if to notify the user this is not a suitable shortcut on windows as it interferes with the OS

**Comment by gerazov** [comment]
@jnsebgosselin yeah `Alt+space` adds spaces in the editor. KDE does define this is a shortcut to `krunner` but I've disabled that in the System Settings.

I have Spyder 3 still installed in a different `conda` environment and the shortcut is working fine and does register in the keyboard settings.

@goanpeca that's the one.

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin yeah `Alt+space` adds spaces in the editor. KDE does define this is a shortcut to `krunner` but I've disabled that in the System Settings.
> 
> I have Spyder 3 still installed in a different `conda` environment and the shortcut is working fine and does register in the keyboard settings.


Ok thanks, that is useful. I can reproduce this on Windows with `Ctrl+Space`.

I think I have found a way to fix that, I'll submit a PR.

**Comment by goanpeca** [comment]
On KDE alt+space has already meaning so I dont think there ismuch we can do about it

<img width="366" alt="Screen Shot 2019-11-25 at 19 36 15" src="https://user-images.githubusercontent.com/3627835/69589669-e0519c80-0fba-11ea-957c-0a4cf68fdbc3.png">

**Comment by goanpeca** [comment]
<img width="620" alt="Screen Shot 2019-11-25 at 19 35 43" src="https://user-images.githubusercontent.com/3627835/69589694-f3fd0300-0fba-11ea-83c0-76d3960debae.png">

**Comment by jnsebgosselin** [comment]
> 
> 
> On KDE alt+space has already meaning so I dont think there ismuch we can do about it
> 

Yes but, if you disable it through the system settings, like @gerazov did, is it working after the change I'm proposing in PR #10836?

**Comment by goanpeca** [comment]
>Yes but, if you disable it through the system settings, like @gerazov did, is it working after the change I'm proposing in PR #10836?

<img width="1042" alt="Screen Shot 2019-11-25 at 19 43 58" src="https://user-images.githubusercontent.com/3627835/69589977-f6ac2800-0fbb-11ea-86e8-3cf8a08a7c3b.png">

Yep it does work @jnsebgosselin

**Comment by gerazov** [comment]
ok great - thanks! :smile:
