### ISSUE TITLE
all the data disappeared

### ISSUE THREAD

**Issue by matssnaps** [spyder-ide/spyder#10799]
### What steps will reproduce the problem?

All my data including python scripts and data was removed when I tried to remove just one file through file explorer!!!

### Traceback
```python-traceback
  File "/Applications/Anaconda/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor.py", line 1921, in load
    filenames = [_convert(filenames)]
  File "/Applications/Anaconda/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor.py", line 1912, in _convert
    fname = osp.abspath(encoding.to_unicode_from_fs(fname))
  File "/Applications/Anaconda/anaconda3/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
PermissionError: [Errno 1] Operation not permitted
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.2 (OK)
numpy >=1.7       :  1.17.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.9.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.3 (OK)
```

**Comment by ccordoba12** [comment]
We're very sorry but this looks like a problem with Catalina and not with Spyder. Catalina has several permission problems like the one you posted above, that were not present in previous versions.

Besides, if you didn't have your code and data under version control (git or mercurial), there's nothing we can do to help you.
