### ISSUE TITLE
Indent guides missaligning when sidescrolling

### ISSUE THREAD

**Issue by richy330** [spyder-ide/spyder#10807]
## Problem Description

Not a serious issue, but the indent guides in the Editor missalign when sidescrolling. They seem to move about twice the speed as the rest of the code in the Editor. They are resetted to the proper location when scrolling to the initiall position(scrolling to the left end in the editor)

### What steps reproduce the problem?

1. Write code with loops and activate indentation guides
2. Set editor window size so that sidescrolling is allowed
3. Sidescroll
![ezgif com-crop](https://user-images.githubusercontent.com/58080997/69440538-50f18280-0d49-11ea-81be-399fd70b6d11.gif)

## Versions

* Spyder version: Spyder 4.0.0rc2 
* Python version: Python 3.7.5 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Win10

### Dependencies

cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.8.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.31.0;<0.32.0        :  0.31.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
I can't reproduce this anymore with our latest implementation. Please let us know if that's not the case.

**Comment by richy330** [comment]
Hello, I'm currently using Spyder 4.0.0 and can't reproduce it as well (did
only a quick check, though). Guess it is fixed!

Thank you very much for your effort, I love your work!

Yours
Richard

Mit AquaMail Android
https://www.mobisystems.com/aqua-mail



Am 14. Dezember 2019 17:26:33 schrieb Carlos Cordoba
<notifications@github.com>:
