### ISSUE TITLE
No Code Folding

### ISSUE THREAD

**Issue by JohnRobson** [spyder-ide/spyder#10816]
I'm using version 4.0.0.dev0 and there is no Code Folding.  Should I enable or install something?

![2019-11-23 01:03:28](https://user-images.githubusercontent.com/378523/69474309-8d46d200-0d8d-11ea-9cd6-3a0c4171f3aa.png)

**Comment by ccordoba12** [comment]
Code folding now depends on the latest version of the Python language server. Please update to it or wait until rc3 is out, which will have the right dependencies for the new code folding implementation.

**Comment by JohnRobson** [comment]
Spyder requires "pyls >=0.31.0;<0.32.0", I'm using "0.31.0-1", still not working, still complaining "pyls >=0.31.0" and now shows this message:

"Completion and linting in the editor for Python files will not work during the current session, or stopped working.

To fix this, please verify that your firewall or antivirus allows Python processes to open ports in your system, or restart Spyder."

I disabled the firewall, deleted the old ".config/spyder-py3-dev", restarted it and still with the same msgs and not working.

**Comment by JohnRobson** [comment]
I'm using this one:  [https://www.archlinux.org/packages/community/any/python-language-server/](https://www.archlinux.org/packages/community/any/python-language-server/)

**Comment by ccordoba12** [comment]
> "Completion and linting in the editor for Python files will not work during the current session, or stopped working.
To fix this, please verify that your firewall or antivirus allows Python processes to open ports in your system, or restart Spyder."

Sorry but the message is quite clear. We can't do anything about that, so you need to figure it out why ports are blocked in your system and unblock them.

Now (in master, I mean) folding is provided by the same server that gives completion and linting, and that's why you're not seeing it in the editor.

**Comment by JohnRobson** [comment]
I disabled the firewall. There are no ports blocking. Please, how can I enable this linting?

**Comment by ccordoba12** [comment]
You can have a corrupted `/etc/hosts` file. Please see the last comments of issue #10209 for a possible solution.
