### ISSUE TITLE
Feature request: include environment when initializing new script

### ISSUE THREAD

**Issue by jonschwenk** [spyder-ide/spyder#10814]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When initializing a new script in Spyder, the new script includes a header:
```
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 22 19:01:45 2019

@author: authorname
"""
```
As someone with an unhealthy number of environments, I am wondering if it would be possible to also include the Anaconda environment name in the header automatically. Something like:

```
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 22 19:01:45 2019

@author: authorname

environment: envname
"""
```
I guess some might not want this automatically included for whatever reason, but it would've been really helpful to me as I dig through older code. It could be a togglable option.

**Comment by ccordoba12** [comment]
Thanks for the suggestion, but instead of doing this, we plan to allow users to associate a conda env with a project.
