### ISSUE TITLE
I only install spyder-notebook

### ISSUE THREAD

**Issue by lwbaqueros** [spyder-ide/spyder#10819]
### What steps will reproduce the problem?

I only intall spyder-notebook by conda console, and then open again spyder from the console

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.2.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.6.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.17.3 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.5.5 (OK)
IPython >=4.0      :  7.9.0 (OK)
matplotlib >=2.0.0 :  3.1.1 (OK)
pylint >=0.25      :  2.4.3 (OK)
```

**Comment by ccordoba12** [comment]
Closing because this was already solved.
