### ISSUE TITLE
Facing TesseractNotFoundError using Spyder IDE but working in Python CLI (Anaconda)

### ISSUE THREAD

**Issue by DebalB** [spyder-ide/spyder#10818]
### What steps will reproduce the problem?

I have installed Tesseract and Pytesseract on Windows 10 (Anaconda).
I have added the path to Tesseract installation folder in the PATH System Environment Variables.
When running my script, I am facing the following error:
"TesseractNotFoundError: tesseract is not installed or it's not in your path"

Following is an example scirpt which can reproduce the problem
###########
import numpy as np
import pytesseract
config = ("-l eng --oem 1 --psm 7")
roi = np.ones((20,20))
pytesseract.image_to_string(roi, config=config)
############

However above code works fine if executed via Python CLI in Anaconda Prompt.
Am I missing some configuration?
Python version 3.7

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.5.2 (OK)
IPython >=4.0     :  7.6.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please read our guide

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to understand how to fix this problem.
