### ISSUE TITLE
Error message when launching Spyder

### ISSUE THREAD

**Issue by lindseyjne** [spyder-ide/spyder#10823]
When launching Spyder, I'm getting the following error and I'm not sure how to solve this.

AttributeError: module 'dateutil.tz' has no attribute 'UTC'
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
AttributeError: module 'dateutil.tz' has no attribute 'UTC'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
This is not a problem with Spyder. Please an Anaconda Prompt and run there

    conda update --all

That should solve it.

**Comment by lindseyjne** [comment]
I did try that numerous times without success.  The only thing that worked was uninstalling Anaconda completely and reinstalling.

**Comment by ccordoba12** [comment]
I was about to suggest that too. Sorry that you had to do that.

**Comment by lindseyjne** [comment]
No worries - it was an easy process.
