### ISSUE TITLE
Hover tips interfere with editor text selection

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#10835]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The hover hints interfere with highlighting text.

![hover_and _drag](https://user-images.githubusercontent.com/10513354/69575406-66ec8680-0f87-11ea-9cbd-ffc88b045033.gif)

![hover_and _drag_up](https://user-images.githubusercontent.com/10513354/69575408-67851d00-0f87-11ea-844e-2ac30e36a0b0.gif)

### What steps reproduce the problem?

1. Activate a hover
2. Click and drag to highlight
3. Can't see the highlighting

### What is the expected output? What do you see instead?

I think that if the hover windows disapapere if the user clicks in the editor that would be one way to solve it

## Versions

* Spyder version: master
* Python version: 3.7.3 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Linux

### Dependencies

```
PASTE DEPENDENCIES HERE
```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.9.0.dev0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.0 (OK)
pandas >=0.13.1              :  0.25.0 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.0;<0.32.0        :  0.31.1 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

**Comment by liuyigh** [comment]
I also have this issue. 

Another problem is that hover tips crash on 4.0.0rc2+MacOS 10.11.6. The crash does not affect Spyder, only hover tip itself.

**Comment by bcolsen** [comment]
> Another problem is that hover tips crash on 4.0.0rc2+MacOS 10.11.6. The crash does not affect Spyder, only hover tip itself.

@liuyigh please write a separate issue for this with an error traceback and a reproducible code example so we can keep track of the error.

**Comment by liuyigh** [comment]
#10852 issue submitted. Thanks!

**Comment by ccordoba12** [comment]
@goanpeca, what do you think we could do about this one?

**Comment by goanpeca** [comment]
>I think that if the hover windows disapapere if the user clicks in the editor that would be one way to solve it

I agree that the hover should probably disappear on any key press. This should be a very easy fix.

**Comment by bcolsen** [comment]
@goanpeca I forgot to mention that the hover is also activated while the mouse button is held down as well. See my second gif.

Would it be possible to disable hovers tips while the mouse button is depressed as well?

**Comment by goanpeca** [comment]
>Would it be possible to disable hovers tips while the mouse button is depressed as well?

Absolutely! that is a silly UX :-p this one is probably on me 😆
