### ISSUE TITLE
Calculation Error in Spider!!!

### ISSUE THREAD

**Issue by Peshangh** [spyder-ide/spyder#10831]
### What steps will reproduce the problem?

I think everyone of you can understand what is the output of the following code:
`
   for j, F in zip(range(1000), [(x/1000)+0.001 for x in range(1000)]):
   print ("j = ",j, "==========", "F = ", F )
`
should be 0.001.....1.0
    but instead in spider I get 0.502 .....1.0. Only half of the numbers, I am using the same code in Jupiter the result is true.
I think you need to check spider. I downloaded Anaconda, so spider came with it.
    

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Not all numbers are printed in Spyder, just the last 500 for efficiency reasons.

**Comment by Peshangh** [comment]
Thank you very much I tested my numbers and it's counting all but for printing not all numbers are shown!
