### ISSUE TITLE
Outline View collpases files when selecting editor.

### ISSUE THREAD

**Issue by NK308** [spyder-ide/spyder#10830]
## Problem Description

While multiple modules are opened simultaneously in the editor, setting the focus to the editor collapses all other modules in the outline view.

### What steps reproduce the problem?

1. Open multiple modules (from same package) simultaneously in the editor in spyder.
2. Show outline view in spyder.
3. Set the outline view to show all files.
4. Expand arbitrary parts of the trees in the outline view (manually or by rightclick->Expand all).
5. Click into the editor to set the focus to the editor and edit one of the files.

### What is the expected output? What do you see instead?

Now the outline view is collapsing all trees except of the tree for the file, which is choosen in the editor right now.
The outline view should give an overview of the functions and method of all opened files, which is impossible, if the trees of other modules cannot be expanded while editing a file.

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.5 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version:  Ubuntu 18.04 Linux 4.15.0-70-generic

### Dependencies
IPython >=4.0     :  7.9.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  1.17.3 (OK)
pandas >=0.13.1   :  0.25.2 (OK)
psutil >=0.3      :  5.6.5 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.3 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 4. Now the outline doesn't collapse when you move from editor to another.
