### ISSUE TITLE
Variable explorer shows NumPy arrays as objects

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#10860]
Spyder 4.0.0rc3

Kudos guys for the new object explorer! However, when you open a NumPy array from the Variable Explorer it now opens it as an object.

Steps to reproduce:
1. In the IPython console write:
```python
In [1]: import numpy as np

In [2]: a = np.arange(10)
```
2. Now double click on `a` in Variable explorer and you get the object explorer window.
![image](https://user-images.githubusercontent.com/15214418/69716289-06d21d80-110a-11ea-8666-efe19c0848a3.png)

**Comment by gerazov** [comment]
Ok, this was fixed on restart, and I'm not able to reproduce. Should I close it?

**Comment by goanpeca** [comment]
Yep, closing

**Comment by ccordoba12** [comment]
This happens if you don't have numpy installed on the same env that Spyder is installed, you install it afterwards but didn't restart Spyder.

**Comment by gerazov** [comment]
Makes sense! I was resetting my conda environment and wanted to try out rc3 before I got to installing numpy :smile: 

I love how you can open NumPy arrays from object properties - awesome stuff :clap:
