### ISSUE TITLE
Refactor the Outline Explorer code to use the LSP Symbols request

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10867]
The Outline explorer currently uses information from the syntax highlighter which parses the code and saves some info to be used by the OE.

We could simplify the syntax highlighters so that it only needs to worry about syntax and simplify the Outline Explorer so that it can use the information provided by the symbols request.

https://github.com/palantir/python-language-server/blob/develop/pyls/plugins/symbols.py

**Comment by ccordoba12** [comment]
This was solved already in 4.2.0
