### ISSUE TITLE
Date/time-based filename (when saving) for figures on Plots pane

### ISSUE THREAD

**Issue by Rational-IM** [spyder-ide/spyder#10864]
Generate a date/time-based filename (so we don't need to rename each picture we want to save if saving multiple figures). Look at the picture below to see how Snip & Sketch generates a date/time-based file name:

![Annotation 2019-11-27 105138](https://user-images.githubusercontent.com/57544001/69744084-844b5d00-110d-11ea-9451-af2e2338e3f1.jpg)

**Comment by goanpeca** [comment]
Thoughts on this @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
> 
> Thoughts on this @jnsebgosselin ?

Its a good idea to add the date.

From the screenshot above, it seems that the first 6 characters of a uuid is also added at the end to ensure uniqueness of the filename. Do you think we should do that also?

**Comment by RIM-LLC** [comment]
The last 6 characters represent the time in the format "hhmmss", which is great when one is saving a series of charts on the same day.

**Comment by jnsebgosselin** [comment]
> 
> 
> The last 6 characters represent the time in the format "hhmmss", which is great when one is saving a series of charts on the same day.

Ah I see! ahah Thanks for the clarification.

I can implement that if the feature is accepted.

**Comment by goanpeca** [comment]
>I can implement that if the feature is accepted.

I like it :-) @ccordoba12 ?

**Comment by ccordoba12** [comment]
Sure. it'd be nice to have in Spyder 5.

**Comment by jnsebgosselin** [comment]
Does future means "Do it against master branch" or it can be done against the 4.x branch?

**Comment by goanpeca** [comment]
Hmmm well, if you want to work on it soon, then 4.x is fine I guess. 

---

Side note:
We are now using zenhub to organize the workflow and in that workflow milestones are sprints, releases (a zenhub thing) groups what we used as milestones and we added this as labels as well for non zenhub users.

**Comment by ccordoba12** [comment]
> Hmmm well, if you want to work on it soon, then 4.x is fine I guess.

Agreed.
