### ISSUE TITLE
Plots should remember last saved path

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#10863]
Python 4.0.0rc3

I really like the Plots pane - chasing down open figures was a lot of hassle ...

It would be nice if the Plot pane remembers the last folder for saving - just so you don't have to navigate down the same path on every save. Currently it opens the current working directory.

**Comment by goanpeca** [comment]
We could add this to the CONF and stored the last saved dir @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
Yes, I will add this, this is a good idea.

Thanks for the suggestion @gerazov

**Comment by gerazov** [comment]
np guys - keep up the good work! :clap:
