### ISSUE TITLE
Spyder crashes 0xc0000005 windows's error code and the affected file is pythonw.exe and Qt5Gui.dll

### ISSUE THREAD

**Issue by silvestre125** [spyder-ide/spyder#10875]
## Problem Description
I'm dealing with a repetitive error that crashes Spyder randomly. The only info about the error is that the problem has 0xc0000005 windows's error code and the affected file is pythonw.exe and Qt5Gui.dll

### What steps reproduce the problem?

1. Randomly

### Versions

* Spyder version: 3.3.6
* Python version: 3.7.3
* IPython: 7.6.1
* Operating System name/version: Windows 10 LTSC 2019

**Comment by ccordoba12** [comment]
Sorry but this is not something we can solve here. Please try to find if there are more `Qt5Gui.dll` in your system and remove them. That's the only advice we can give you.
