### ISSUE TITLE
Autocomplete not working for standard modules on 4.0.0rc3 without Kite

### ISSUE THREAD

**Issue by doogra** [spyder-ide/spyder#10874]
### What steps will reproduce the problem?

Prerequisite: Kite is NOT installed

Launch Python 4rc3. Attempt to invoke autocomplete by typing "table=pd.". This should provide a set of pandas autocomplete options as pandas is listed in the default modules to be loaded in Spyder4. Spyder should be falling back to jedi or other valid autocomplete options if Kite is not installed on the system. However, this does not seem to be working currently as it was in my 3.x version.

## Versions

* Spyder version: 4.0.0rc3 
* Python version: 3.6.9
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-70-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  6.0.0a0 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.1 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.0;<2.0.0:  1.8.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.0 (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.3 (OK)
pyls >=0.31.1;<0.32.0        :  0.31.1 (OK)
xdg >=0.26                   :  0.26 (OK)
```

**Comment by ccordoba12** [comment]
How did you install Spyder?

**Comment by doogra** [comment]
Hi,

I did it per the webpage instructions here:

https://github.com/spyder-ide/spyder/releases

pip install --pre -U spyder

Doug

**Comment by ccordoba12** [comment]
> pip install --pre -U spyder

Ok, I'm very sorry but we don't have enough resources to support custom installations (i.e. not Anaconda ones). They are basically for expert users who are able to debug and solve these kind of issues.

If you don't know how to do that, please download and use Anaconda instead.

**Comment by doogra** [comment]
Ok cool. Thanks.

Doug
