### ISSUE TITLE
String "Run in console's namespace instead of an empty one" translated but still show English on UI

### ISSUE THREAD

**Issue by suokunlong** [spyder-ide/spyder#10884]
## Problem Description

The following string is translated in PO files, but on UI it still shows in English.

spyder/preferences/runconfig.py:46":
msgid "Run in consoleâs namespace instead of an empty one"

It seems to be related to the special characters. In PO files it is:
msgid "Run in consoleâs namespace instead of an empty one"
but in source file it is:
CONSOLE_NAMESPACE = _("Run in console’s namespace instead of an empty one").

**Comment by goanpeca** [comment]
We will look into it! thanks

**Comment by ccordoba12** [comment]
@suokunlong, you need to submit a new PR for that string because I removed the non-ascii character it contained.
