### ISSUE TITLE
Show hidden files in the project explorer

### ISSUE THREAD

**Issue by MuellerSeb** [spyder-ide/spyder#10883]
Is it possible to show hidden files like ``.travis.yml`` or ``.coveragerc`` in the project explorer?

There is an option called "Show all files" under ``Preferences -> Files -> General``, but this doesn't make these files show up.

If it's not my fault by missing a checkbox, I think it's quite inconvenient that accessing necessary files for a python project is not possible through the project explorer.

System: Ubuntu 18.04
Spyder: 4.0.0rc3
Python: 3.6.9

**Comment by goanpeca** [comment]
@MuellerSeb you are correct, we will fix this for V4.1 !

**Comment by david-cortes** [comment]
To add: in windows, hidden folders (as in windows-hidden, rather than name starting with `.`) also don't show up in the `Files` pane browser, whereas files with a name starting with `.` show up as expected.
