### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Hejinzefinance** [spyder-ide/spyder#10881]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
When I double click the variable of numpy.arrays, of which the size is (100,10), in the Variable explorer of Spyder, not only can't I view my matrix variable in the form of 2-dimensional numpy.arrays, but also I will encounter the internal error in Spyder.

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

**Comment by Hejinzefinance** [comment]
Thank you!!! It works!
