### ISSUE TITLE
Spyder ID getting crashed

### ISSUE THREAD

**Issue by piyushy1** [spyder-ide/spyder#10891]
Hi, I am using Spyder IDE under conda environment in windows 10. Everytime I launch my spyder I get the following exception. Sometimes the ide works while sometimes it does not launch.

**Please provide any additional information below**

    plugin.register_plugin()
    self.create_new_client(give_focus=False)
    server_info = nbopen(filename)
    server_info = find_best_server(filename)
    servers = [si for si in notebookapp.list_running_servers()
    servers = [si for si in notebookapp.list_running_servers()
    info = json.load(f)
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
    return _default_decoder.decode(s)
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.15.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.2 (OK)
cython >=0.21    :  0.28.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is an error with spyder-notebook and we don't know why it happens. Please uninstall it to not see this error.
