### ISSUE TITLE
ipdb set_trace() is not working properly in spyder

### ISSUE THREAD

**Issue by camilomarino** [spyder-ide/spyder#10895]
## Problem Description

When I write (at any script):
import ipdb; ipdb.set_trace()

Always when I press n the program send me to "interactiveshell"

    --Return--
    None
    > <ipython-input-1-606cc96bec96>(7)<module>()
          6 
    ----> 7 import ipdb; ipdb.set_trace()
          8 

    ipdb> n
    > /home/***/anaconda3/envs/***/lib/python3.7/site-packages/IPython/core/interactiveshell.py(3329)run_code()
       3328                 # Reset our crash handler in place
    -> 3329                 sys.excepthook = old_excepthook
       3330         except SystemExit as e:

    ipdb> 

If I run this same script from the Ubuntu console it works correctly. It does not work in Spyder

## Versions

* Versión de Spyder: 3.3.6 
* Versión de Python: 3.7.5 64-bit
* Versión Qt: 5.9.6
* Versión PyQt: 5.9.2
* Nombre / versión del sistema operativo: Ubuntu 18.04

### Dependencies
```
IPython >=4.0     :  7.9.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  1.17.4 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
psutil >=0.3      :  5.6.5 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
Please try this next week after we release Spyder 4 to see if the error still persists there.

**Comment by impact27** [comment]
Please also use `pdb` instead of `ipdb` with Spyder 4.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
