### ISSUE TITLE
Cannot connect to remote existing kernel on macOS Catalina

### ISSUE THREAD

**Issue by jwa5426** [spyder-ide/spyder#10898]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder fails to connect to remote kernel running on Ubuntu from MacOS.

I'm able to connect to the kernel using [this recipe](https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh) so I do not think this is a problem with my setup.

### What steps reproduce the problem?

1. Follow the steps in the [doc](https://docs.spyder-ide.org/ipythonconsole.html#connecting-to-a-console)

### What is the expected output? What do you see instead?

Could not open ssh tunnel. The error was: Could not connect to remote host

<img width="468" alt="Screen Shot 2019-12-01 at 12 02 28 PM" src="https://user-images.githubusercontent.com/27090100/69917513-e9b48c00-1434-11ea-8965-f760ef4df796.png">

## Versions

macOS Catalina (client)
* Spyder version: 3.3.6
* Python version: 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Catalina 10.15.1

Ubuntu (server)
macOS Catalina (client)
* Spyder version: 3.3.6
* Python version: 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu desktop 18.04 LTS

### Dependencies

IPython >=4.0     :  7.9.0 (OK)
cython >=0.21     :  0.29.14 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  1.17.4 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
psutil >=0.3      :  5.6.5 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by ccordoba12** [comment]
Sorry but we don't the means to debug this. If the IPython recipe is working for you, then you'll have to use that instead.

**Comment by jwa5426** [comment]
Feel free to keep this closed if you want but I think you’re ignoring a sign of broken functionality. If I have to use a console outside of the IDE to run my code why use Spyder at all?

**Comment by ccordoba12** [comment]
> Feel free to keep this closed if you want but I think you’re ignoring a sign of broken functionality. If I have to use a console outside of the IDE to run my code why use Spyder at all?

That's your choice. The functionality of running in remote kernels runs well in most cases, but we can't cover all OS host/guest combinations.

**Comment by hofsaess** [comment]
Hi,
I  had a very similar problem. I tried to connect to a remote kernel. Client and Server are both linux system (Debian 10 and CentOS7) and both use the same software versions (python 3.7.3, spyder 4.0.1, spyder_kernels 1.8.1, IPython 7.13.0).
I create on a server the remote kernel with python -m spyder_kernels.console --debug -f kernel-6787.json to use an old configuration.
On the client i follow the normal workflow and go to the menu and choose the entry "connect to ..." and take the copied kernel file.  
Then happened nothing and on the internal console is written out, that "WARNING:traitlets:kernel died: 3.00736"
As a work around I use the description [here](https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh), to set up the ssh tunnel manual and than connect to remote kernel. That is working. 

Is there a possibility to debug the problem?

**Comment by jwa5426** [comment]
This isn’t really a solution, but I ended up just setting up a Jupyter notebook server on my Ubuntu machine in order to do my work.

Again, not a solution to the problem but it worked well for my situation.
