### ISSUE TITLE
Regression: Indent guides broken in any Editor split panel except the first

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#10900]
As requested by @ccordoba12 . This is a serious regression in a major new feature that's been present since Beta 1, so it should presumably be fixed before the final release.

PR #10782 adds a new system for indent guides, but they are broken (don't appear at all) in any split Editor panel that isn't the first, leading me to initially think that they weren't working at all until I could get them to work in the first panel. Ergo, this should be fixed.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
