### ISSUE TITLE
Feature Idea: Dock the Kite copilot in Spyder

### ISSUE THREAD

**Issue by alexschw** [spyder-ide/spyder#10904]
### Issue Report Checklist
* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

### Feature Description
It might be a nice feature to dock the Kite window into a new pane in the Spyder window. It bothers me a bit to always put it on top of the maximized window and cover parts of the Editor. Maybe [this](https://stackoverflow.com/questions/57015932/how-to-attach-and-detach-an-external-app-with-pyqt5-or-dock-an-external-applicat) might be helpful for this feature.

**Comment by ccordoba12** [comment]
> Maybe this might be helpful for this feature.

I think something like that only works on Linux.

Would you prefer to disable the Kite Copilot? Or to only show it on demand?

**Comment by alexschw** [comment]
> Would you prefer to disable the Kite Copilot? Or to only show it on demand?

Neither. I thought that the kite copilot might be included in a pane. If this is only possible on Linux, I guess I'll stick to putting it on top of the help pane.

**Comment by goanpeca** [comment]
>Neither. I thought that the kite copilot might be included in a pane. If this is only possible on Linux, I guess I'll stick to putting it on top of the help pane.

We could eventually add the content of copilot within the help pane (it is a web rendering widget) if kite can send it 🤷‍♂

**Comment by ccordoba12** [comment]
@metalogical, is the Copilot showing webpages served by Flask or something? If that's the case, we could embed its contents in a Qt web widget instead.

**Comment by metalogical** [comment]
The Copilot currently communicates with the Kite daemon using a custom data representation and uses a JS rendering component to display the documentation.

So it would be a substantial amount of work either in Kite (to render as HTML) or within Spyder (to implement the copilot rendering logic) to support this.

**Comment by goanpeca** [comment]
Ok, this is a won’t fix. Closing @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, sorry @alexschw but there's nothing we can do about this one.
