### ISSUE TITLE
Change theme settings in external plugins is not possible

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#10911]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When the theme changes in the appearance section of the configuration page, there's not a signal that is emitted to external plugins. So, the external plugins are unable to change their appearance according to the defined Spyder theme.

**Comment by goanpeca** [comment]
@ccordoba12 we could add a signal for this specific issue or generalize all plugins to receive all changed options and act accordingly?

**Comment by ccordoba12** [comment]
> generalize all plugins to receive all changed options and act accordingly?

This sounds better to me, to not have a similar issue in the future related to another option.
