### ISSUE TITLE
No plotting available for some variables in Variable Explorer

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#10917]
Spyder 4.0.0rc3

There's no plotting available for some of the variables in Variable Explorer. Neither on the pane's toolbar or on right click:

<img src="https://user-images.githubusercontent.com/15214418/70036433-14c5e980-15b5-11ea-87a0-f385132e2da0.png" width="500"/>

For most of the others it works:
<img src="https://user-images.githubusercontent.com/15214418/70036663-830aac00-15b5-11ea-9e25-3466804f78bb.png" width="500"/>

Even though in this case one variable is made from the other one like so:
```python
energy = 10**(logenergy/10)
```

Also there is no Plot button on the pane's toolbar.

It's hard to reproduce in a new IPython console though ...

**Comment by ccordoba12** [comment]
@gerazov, please post some code that generates an array for which plotting is not available.

**Comment by gerazov** [comment]
Sorry - it's really elusive - tried to make a minimum working example, and half way there plotting became available, after which previous versions also had plotting ...

**Comment by ccordoba12** [comment]
@dalthviz, can you reproduce this one with @gerazov example above?

**Comment by dalthviz** [comment]
@ccordoba12 yep I can reproduce this, no plot action in shown in the context menu of the Variable Explorer

**Comment by gerazov** [comment]
Ok thanks!
