### ISSUE TITLE
Snippets completion bug when function starts with "_"

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#10924]
## Problem Description
Snippets completion bug when function starts with underline,code like this:
```Python
def __testA(a,b):
    pass

def _testB(a,b):
    pass

def testC(a,b):
    pass

__testA(${1:a}, b)
_testB(${1:a}, b)
testC(a, b)
```
## Versions

* Spyder version: 4.0.0rc3
* Python version: 3.7.1 64-bit
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: windows10

**Comment by ccordoba12** [comment]
Duplicate of #11237
