### ISSUE TITLE
Sypder and Jupiter both shows "An error occured while starting the kernel

### ISSUE THREAD

**Issue by priyansh8** [spyder-ide/spyder#10927]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have tried many ways to remove the error but it still persists. I am beginner with anaconda so i dont know about all the commands. So please guide me how to solve this problem.

Spyder shows the error given below. Please help me how to fix this. It will be very helpful. Thank You..

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "E:\anaconda\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "E:\anaconda\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "E:\anaconda\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "E:\anaconda\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "E:\anaconda\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "E:\anaconda\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Vivek Agarwal\\AppData\\Roaming\\jupyter\\runtime\\kernel󈛑f0cb9da688.json'

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda update --all

That should fix your problem.

**Comment by priyansh8** [comment]
I tried the above given code but it didn't work for me...After downloading all the files..it says executing transactions and after that it throws error. The images are attached and given below please help me. Thanks for helping..


![Screenshot (91)](https://user-images.githubusercontent.com/43928121/70377990-1e4aab00-1941-11ea-90c0-e129c6eab9ee.png)
![Screenshot (92)](https://user-images.githubusercontent.com/43928121/70377994-34f10200-1941-11ea-91bf-4dc8022381b0.png)
![Screenshot (93)](https://user-images.githubusercontent.com/43928121/70377997-3fab9700-1941-11ea-8c21-fb83fd6939fa.png)
