### ISSUE TITLE
Request: add white background to math symbols

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#10921]
In Linux, if I set a dark theme and try to visualize variable names rendered as mathjax from sympy, these will show as black text on dark-grey background, which makes it illegible:
![sympy_unreadable](https://user-images.githubusercontent.com/11860098/70085549-2214bf80-1619-11ea-9785-21668f67fcef.png)
Would be nice if Spyder could add a white background for them when it renders math equations.

**Comment by ccordoba12** [comment]
This was solved in Spyder 4, to be released shortly.
