### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by krjin** [spyder-ide/spyder#10937]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/Users/JINRONG/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (prompt-toolkit 3.0.2 (/Users/JINRONG/anaconda3/lib/python3.6/site-packages), Requirement.parse('prompt-toolkit<2.1.0,>=2.0.0'))

**Comment by ccordoba12** [comment]
It seems you used pip to install some packages, which generated the problem above. Please open Terminal.app and run there

    conda install prompt_toolkit=2

If that doesn't fix the problem, I'm afraid you'll have to reinstall Anaconda.
