### ISSUE TITLE
The default indentation characters should be "4 spaces" instead of "tab"!

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1093]
_From [iacopoma...@gmail.com](https://code.google.com/u/118409931281630189118/) on 2012-06-16T05:18:44Z_

It's a python standard coding style and a best practice: http://www.python.org/dev/peps/pep-0008/#tabs-or-spaces .

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1093_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-04T07:43:40Z_

When you hit tab in the Editor, 4 spaces are automatically inserted instead of a tab character. However you can control this behavior under

Tools > Preferences > Editor > Advanced Settings > Indentation characters

Maybe you changed that option without noticing it :-)

**Status:** Invalid

**Comment by Tun555** [comment]
How I change key "Tab" (indentation characters key) in spyder to anorther key?

**Comment by ccordoba12** [comment]
Hey @Tun555, that's not possible, sorry.
