### ISSUE TITLE
Collapsing with comments

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#10942]
Often when I am separating my code, I have my function, and some testing code below it. When I productize, I eliminate the testing code, but during the building phase it is helpful to have. I often separate my functions with long strings of '#########' so that I can scroll fast and not pay attention to the names. 

The feature request comes from something I can do in R studio. There, if there is a long enough string of comments, it will allow me to collapse my code below it until it hits another long string of comments.

eg:

######################## Some Function for something #################
def some_function(variables):
  *Insert long code here *

######################## Some Function for something Testing ############
 *Long bunch of test code here *

####################### another one ################################
def another_one(variables):
 *code *

######################### another one testing ########################

*more testing code *

in the above example, it would be nice to be able to collapse the long comment strings so I can block out testing code or function code while I'm working on another area.

**Comment by ccordoba12** [comment]
This is what cells are for. We plan to add support for folding cells in the future.
