### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Martinrk1991** [spyder-ide/spyder#10959]
I cannot open and visualize my data.
I simply created randomly a dataset:
    data = np.random.randn(50000)  * 20 + 20
    
    
   AND THIS ERROR APPEARED

**Comment by goanpeca** [comment]
What error?

**Comment by ccordoba12** [comment]
This should be fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
