### ISSUE TITLE
Spyder and Jupyter both shows "An error occured while opening the Kernel"

### ISSUE THREAD

**Issue by priyansh8** [spyder-ide/spyder#10957]
I tried
 
"conda update --all" 

but it didn't work for me...After downloading all the files..it says executing transactions and after that it throws error. The images are attached and given below please help me. Thanks for helping..

![Screenshot (91)](https://user-images.githubusercontent.com/43928121/70378755-383cbb80-194a-11ea-8eb7-6f891ef7b41d.png)
![Screenshot (92)](https://user-images.githubusercontent.com/43928121/70378759-3c68d900-194a-11ea-89d7-7eaed0e4821f.png)
![Screenshot (93)](https://user-images.githubusercontent.com/43928121/70378761-3ecb3300-194a-11ea-8b13-b5249f7d0830.png)

**Comment by ccordoba12** [comment]
Please report this error here:

https://github.com/ContinuumIO/anaconda-issues/issues/

There's nothing we can do about it here.
