### ISSUE TITLE
Auto PEP8 your source code

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1096]
_From [eng...@gmail.com](https://code.google.com/u/113881073069619832939/) on 2012-06-19T02:44:39Z_

There is an utility to auto pep8 your source code. I guess this would go hand in hand with the current "remove trailing spaces". It could be nice if that could be done directly in spyder. http://pypi.python.org/pypi/autopep8

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1096_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-04T07:31:28Z_

Sounds interesting but someone will have to stand up to implement it. It shouldn't be too hard to do it though :)

**Status:** HelpNeeded  
  **Labels:** -Priority-Medium Priority-Low Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [omegat...@gmail.com](https://code.google.com/u/104763487637795491186/) on 2013-03-08T07:14:56Z_

What's the purpose of https://code.google.com/p/spyderlib/source/browse/pep8.py ?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-08-29T15:35:24Z_

I made a plugin for autopep8 (see attached file). This is my first experience with spyder code and it's mainly copy-paste. It was tested on python 2.7 and python 3.3. It runs with the default options.

I still have a few problems:
- I did not find how to enable undoing the changes (with ctrl+Z)
- on Arch Linux the bundled pep8 version was too old to be compatible with arch autopep8. I guess compatible versions should be put in external-py2 and external-py3 (autopep8 is compatible with both python versions without modifications) to avoid this kind of problem.

**Attachment:** [p_autopep8.py](http://code.google.com/p/spyderlib/issues/detail?id=1096#hc3)

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-08-30T01:33:45Z_

I forgot a third problem:
- how to stop loading the plugin if no autopep8 module is found ? Note that this won't be a problem if autopep8 is embedded like pep8.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-30T05:22:39Z_

issue #1504 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-09-07T05:42:53Z_

No answers ? Is my code that bad ? ^^

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-07T07:19:27Z_

Sorry, I overlooked it. Thanks for pinging us again. I'll take a look at it later today.

Giving the increasing interest in adding Spyder plugins, one solution would be to add them to PyPi until they are mature enough.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-09-07T11:20:44Z_

I can put it on pypi, but it won't work if installed with pip, the file has to be put in the right spyder subfolder. github may be a better compromise ?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-09-16T02:30:13Z_

I created a github repo for the plugin : https://github.com/Nodd/spyder_autopep8 .

Is there another way to install plugins other than putting the files in /usr/lib/python2.7/dist-packages/spyderplugins/ (or equivalent) ? Something like ~/.spyder2/plugins would be useful.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-10-14T15:34:02Z_

I found solutions to my basic problems. It should be usable now.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:17:41Z_

**Labels:** MS-v2.4

**Comment by goanpeca** [comment]
@Nodd do you want to make your plugin more like a package? I had already started to do it [here](https://github.com/goanpeca/spyderplugin.autopep8)

@ccordoba12, should we make an additional repo for this plugin inside spyder-ide repo? It could also be useful as an example of how to make such plugins.

**Comment by ccordoba12** [comment]
I depends on @Nodd :-)

**Comment by Nodd** [comment]
Yes, it should be made as a package, but only when spyder will be able to load plugins from a directory in `spyderplugins`.

**Comment by goanpeca** [comment]
@ccordoba12 have you made any progress in this direction ?

**Comment by Nodd** [comment]
For information I just started working on `spyderplugins`. I'll soon create a PR to discuss about it.

**Comment by ccordoba12** [comment]
@goanpeca, nop, I'm in review mode these days :-)

**Comment by Nodd** [comment]
Then you can start reviewing #2362 !

**Comment by Nodd** [comment]
There is a working external plugin for spyder 3.0 (incoming!) at https://github.com/spyder-ide/spyder.autopep8
