### ISSUE TITLE
Create/Update translations for Spyder and related projects with Crowdin

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#10969]
# Crowdin

The Spyder organization will start using Crowdin for handling localization of Spyder and associated projects and plugins. Crowdin provides a simple web based platform/interface for translators :-)

To start translating please visit the Spyder organization associated projects:
- https://crowdin.com/project/spyder or look for the badges on the repos  [![Crowdin](https://badges.crowdin.net/spyder/localized.svg)](https://crowdin.com/project/spyder)
- https://crowdin.com/project/spyder-terminal
- https://crowdin.com/project/spyder-notebook
- https://crowdin.com/project/spyder-reports
- https://crowdin.com/project/spyder-unittest

# Translators

## French
@afvincent, @Nodd, @SylvainCorlay

## Hungarian
@blackPantherOS, @martindurant

## Japanese
@sohnishi

## Portuguese (Brazilian)
@sehnem, @manipuladordedados

## Russian
@burrbull, @Qlogin

## Spanish
@ccordoba12, @goanpeca

## Simplified Chinese
@suokunlong, @kingmo888, @nnnewb, @gepcel

## German
@alexschw, @be-we

**Comment by sohnishi** [comment]
Dear @goanpeca, the links (ex. https://crowdin.com/translate/spyder/25/en-ja) seem to be broken.

Crowdin returns "Error loading resources. Please try again".

**Comment by goanpeca** [comment]
I just tried the link and it seems to work ok

![image](https://user-images.githubusercontent.com/3627835/70486644-92f82380-1ac0-11ea-901b-b2ed8bb0f2d7.png)

**Comment by sohnishi** [comment]
Thank you. There must be some troubles in my environment...

**Comment by ccordoba12** [comment]
This is already done (at least for the most important projects in our ecosystem).
