### ISSUE TITLE
Feature request: scroll line up/down using keyboard shortcut

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#10968]
Hi!

I've found that vscode and pycharm have a quite neat feature, which is to scroll down/up one line per key press, using ctrl + up/down.

Here is vscode's keyboard shortcut: https://code.visualstudio.com/docs/getstarted/keybindings (seacrh for "scrollLineDown"), and PyCharm has the same keyboard shortcut.

Currently, Spyder's ctrl + up/down is reserved for navigating between different code cells, so I wonder if we can have a line-by-line scroll assigned to another keyboard shortcut?

**Comment by ccordoba12** [comment]
Again, a nice suggestion of yours but unfortunately we don't have time to implement it. You're welcome to submit a PR though.

**Comment by jnsebgosselin** [comment]
I think this would be a nice feature to have for the editor.

The hard part is to find a proper key sequence that everyone will agree with...

**Comment by jnsebgosselin** [comment]
Maybe we could use `Ctrl+Shift+Up` and `Ctrl+Shift+Down`?

@goanpeca any thoughts?

**Comment by jsh9** [comment]
Psychologically, `ctrl + up/down` feels more incremental, and `ctrl + shift + up/down` feels more like a bigger step. If we are OK with breaking past user behaviors, I'd say assign `ctrl + up/down` to "scroll by line", and `ctrl + shift + up/down` to "navigate by cell".

**Comment by ccordoba12** [comment]
@jsh9, you can easily remap shortcuts to your convenience, so I don't think that's necessary.

**Comment by jnsebgosselin** [comment]
Ok I can take care of that one, I've tested it and it is simple to implement.

**Comment by ccordoba12** [comment]
Sure, thanks a lot for your help @jnsebgosselin!

**Comment by ccordoba12** [comment]
I think new, non-critical features should go for Spyder 5. So please create your branch from master.
