### ISSUE TITLE
Revise gettext.translation.lgettext as it is deprecated

### ISSUE THREAD

**Issue by suokunlong** [spyder-ide/spyder#10972]
Per the Python 3 Docs, the gettext funcionts lgettext is deprecated since version 3.8, and will be removed in version 3.10.
https://docs.python.org/3/library/gettext.html#gettext.lgettext

Spyder uses gettext.translation.lgettext to get the translation strings, in spyder/config/base.py. This code should be revised to avoid Exception in the near future.

**Comment by juliangilbey** [comment]
I think this can be closed; lgettext is no longer used.
