### ISSUE TITLE
IPython Terminal not starting properly

### ISSUE THREAD

**Issue by PJussel** [spyder-ide/spyder#10985]
### Problem Description

When starting a spyder instance, IPython console is not displayed at all.

### What steps reproduce the problem?

1. Start Spyder
2. Wait until all is loaded, IPython console is not rendering

### What is the expected output? What do you see instead?

I have to once press F5 to execute some script, instantly IPython console and output is displayed properly. Seems like it has been already there, but just not rendered at all. See below two images, before executing script, and after executing script.

![empty_console](https://user-images.githubusercontent.com/12828726/70440235-059dda80-1a92-11ea-961b-8bc8ee9a6dd9.jpg)

![code_run](https://user-images.githubusercontent.com/12828726/70440236-059dda80-1a92-11ea-9047-d37db4a45a95.jpg)

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.4-64bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please post the code you're trying to execute to better understand your problem.

**Comment by PJussel** [comment]
Nothing specific, any code in editor window will do. In above example the python file executed only contained one command "dir()" just to do something.

**Comment by ccordoba12** [comment]
Sorry but we're not seeing this problem in our side. Please feel free to post other comments here if you manage to narrow down the cause of this issue.

**Comment by 1313e** [comment]
I have the same problem.
Simply opening Spyder 4 will show the IPython console window to be completely blank with nothing inside it.
It is impossible to interact with the console while it is in this state (you cannot type anything in it).
Opening a second IPython console will cause both consoles to show up correctly, and running a script in the first console will show it properly as well.
It seems that it is not related to time, as I have waited once for over 10 minutes before actually running anything and it was still blank.
Finally, I do have a script that is ran every time a new IPython console is opened.
I can see that this did actually run, but it will not show any messages that the script should display in the console after it becomes visible.
Not sure if that has something to do with it, but just mentioning it anyway.

It looks to me as if the IPython console widget that is created during start-up is not set to be visible, therefore not actually showing up.
Switching between tabs will obviously result in the general tab widget behavior, which hides one tab and unhides the other.

**Comment by ccordoba12** [comment]
Without a way to reproduce this there's nothing we can do about it, sorry.

**Comment by PJussel** [comment]
Resetting settings worked for me, cannot reproduce now any more the behaviour. Seems like there  must be either some fragments from older settings (rc01, rc02 or rc03)...
