### ISSUE TITLE
imported data can not called in the editor,but can be called in the interpreter

### ISSUE THREAD

**Issue by areur3ady** [spyder-ide/spyder#10980]
### What steps will reproduce the problem?

imported data can not be called in the editor, but can be called in the interpreter.
To run the program edited in the editor, shortcut 'f5' response a name not defined error.
Copy the file to the interpreter work.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by daharn** [comment]
I can confirm this. Running a script using `runfile` seems to run it in a sperate console without any variables present that were defined before. 
This only happened to me today after updating my Linux machine to Sypder 4.0 (via Anaconda) though, yesterday on a different Windows computer I had no issues with this.

**Comment by ccordoba12** [comment]
@areur3ady, @daharn, sorry for the confusion but the previous behavior led to a lot of headaches for newbies, so teachers requested us this feature.

Besides, it incorrectly made your code to depend on the current state of your namespace, which also generated big issues with reproducibility.

Therefore, we don't plan to go back to the previous default, sorry.

**Comment by daharn** [comment]
Thank you for the clarification. Of course, that decision is yours to make. 

Funny, it probably really depends on your coding background which behavior occurs more "natural" to you. As someone coming from matlab (as supposedly many who use spyder), I always considered scripts and console to share the same workspace. Otherwise, what is the point in having both opened alongside? 

But I also understand that from a more traditional programming view, it makes sense to run each script in a "fresh" environment.
