### ISSUE TITLE
Cannot resolve dependencies for spyder 4 when using conda-forge on win64

### ISSUE THREAD

**Issue by Lewn** [spyder-ide/spyder#10989]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] ~Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)~
* [ ] ~Could not reproduce inside ``jupyter qtconsole`` (if console-related)~
* [ ] ~Tried basic troubleshooting (if a bug/error)~
    * [ ] ~Restarted Spyder~
    * [ ] ~Reset preferences with ``spyder --reset``~
    * [ ] ~Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)~
    * [ ] ~Tried the other applicable steps from the Troubleshooting Guide~
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Installing Spyder 4 from conda-forge does not succeed on win64 due to failing dependency checks.

Is conda-forge not yet supported?

### What steps reproduce the problem?

1. Open a conda console
2. conda create -c conda-forge --name spyder_test spyder=4

### What is the expected output? What do you see instead?
Installation of Spyder 4 with dependencies.

### Paste Traceback/Error Below (if applicable)

```

(base) C:\Users\...\python>conda create -c conda-forge --name spyder_test spyder=4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package atomicwrites conflicts for:
spyder=4 -> atomicwrites
Package qdarkstyle conflicts for:
spyder=4 -> qdarkstyle[version='>=2.7']
Package pyzmq conflicts for:
spyder=4 -> pyzmq
Package pygments conflicts for:
spyder=4 -> pygments[version='>=2.0']
Package python-language-server conflicts for:
spyder=4 -> python-language-server[version='>=0.31.2,<0.32.0']
Package jedi conflicts for:
spyder=4 -> jedi=0.14.1
Package nbconvert conflicts for:
spyder=4 -> nbconvert
Package sphinx conflicts for:
spyder=4 -> sphinx
Package pympler conflicts for:
spyder=4 -> pympler
Package pickleshare conflicts for:
spyder=4 -> pickleshare
Package rtree conflicts for:
spyder=4 -> rtree
Package spyder-kernels conflicts for:
spyder=4 -> spyder-kernels[version='>=1.8.1,<2.0.0']
Package qtpy conflicts for:
spyder=4 -> qtpy[version='>=1.5.0']
Package qtawesome conflicts for:
spyder=4 -> qtawesome[version='>=0.5.7']
Package pexpect conflicts for:
spyder=4 -> pexpect
Package pyqt conflicts for:
spyder=4 -> pyqt[version='>=5.6,<5.13']
Package watchdog conflicts for:
spyder=4 -> watchdog
Package cloudpickle conflicts for:
spyder=4 -> cloudpickle
Package keyring conflicts for:
spyder=4 -> keyring
Package diff-match-patch conflicts for:
spyder=4 -> diff-match-patch
Package psutil conflicts for:
spyder=4 -> psutil
Package python conflicts for:
spyder=4 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
Package qtconsole conflicts for:
spyder=4 -> qtconsole[version='>=4.6.0']
Package numpydoc conflicts for:
spyder=4 -> numpydoc
Package pylint conflicts for:
spyder=4 -> pylint
Package chardet conflicts for:
spyder=4 -> chardet[version='>=2.0.0']
Package intervaltree conflicts for:
spyder=4 -> intervaltree
Package paramiko conflicts for:
spyder=4 -> paramiko
Note that strict channel priority may have removed packages required for satisfiability.


```

**Comment by goanpeca** [comment]
how about just 

`conda create --name spyder_test spyder -c conda-forge`

**Comment by ccordoba12** [comment]
Yeah, that's the way to go for now. Also, we don't have any way to solve this kind of problems here. So for next time please report them in

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by ccordoba12** [comment]
Finally, if you're using Python 3.8, then there are some of our dependencies that don't have versions for it yet.

They will be available in a month or so, I guess. That depends on conda-forge maintainers, really.

**Comment by Lewn** [comment]
> 
> 
> how about just
> 
> `conda create --name spyder_test spyder python=3.7 -c conda-forge`

That does indeed work, but it will install spyder 3, not spyder 4. If I guess this means that spyder 4 is not yet compatible with the conda-forge repository.

> 
> 
> Finally, if you're using Python 3.8, then there are some of our dependencies that don't have packages for it yet.
> 
> They will be available in a month or so, I guess. That depends on conda-forge maintainers, really.

Yes, thats why i'm using python 3.7 for the moment.

**Comment by goanpeca** [comment]
that is werid

https://anaconda.org/conda-forge/spyder

**Comment by Lewn** [comment]
Thats what I thought, but it does not seem able to solve dependencies if I specify python=3.7 and spyder=4

**Comment by ccordoba12** [comment]
conda-forge is down at the moment, so I can't test it.

@Lewn, what operating system (Windows/Linux/macOS) are you using?

**Comment by Lewn** [comment]
Windows 64 bit

**Comment by mherrmann3** [comment]
Any update on this? I'm also still not able to update to Spyder v4.0.0 on Win x64 with the `conda-forge` channel (`UnsatisfiableError`) . However, it works with the `anaconda` channel:
`conda create -n spyder -c anaconda spyder`

**Comment by mherrmann3** [comment]
Update: the problem was that I use `conda-forge` as the top channel & the setting `channel_priority: strict`. Solution:

    conda config --env --set channel_priority disabled
    conda update spyder

See details here: [stackoverflow.com/a/59307296/3801913](https://stackoverflow.com/a/59307296/3801913)

I guess this means that `strict` `channel_priority` is not a really clever (and future proof) idea, yet.
