### ISSUE TITLE
Installing spyder with anaconda but without including it on environment.yml

### ISSUE THREAD

**Issue by ccamara** [spyder-ide/spyder#10988]
## Problem Description

I have successfully installed Spyder using anaconda according to the [official documentation](https://docs.spyder-ide.org/installation.html) and works fine. However, since I am pretty new to python, I am not sure if I did it fine when combining it with virtual environments, as I by doing so, I am listing an IDE as a dependency wereas in strict sense, it is not  (after all, other developers may want to use another IDE). As a result, I am wondering if there is another better way to install it and running than the one I followed (see below):

### What steps reproduce the problem?

1. I created a `environment.yml` file containing, amongst others, `spyder`:
```
name: my_environment
channels:
  - conda-forge
  - defaults
dependencies:
  - spyder
```
2. I created a virtual environment out of it: `conda env create -f environment.yml`
3. I activated my custom virtual environment: `conda activate my_environment`
4. I run `spyder` from CLI
5. Spyder works just fine, and can use all the other libraries and dependencies within `my_environment`

### What is the expected output? What do you see instead?

My question is if there is another way to install and execute `spyder` out of the virtual environment but at the same time make use of all the dependencies within the virtual environment.

**Comment by ccordoba12** [comment]
You only need to install spyder-kernels in your env and switch interpreters in the Spyder installed in your base env.

Please see here

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

for the details.

**Comment by ccamara** [comment]
Thank you! I didn't see that page.

PS: congrats with new 4.0 version!

**Comment by ccordoba12** [comment]
> Thank you! I didn't see that page.

No problem.

> PS: congrats with new 4.0 version!

Thanks for your kind words!
