### ISSUE TITLE
Spyder4 adds a space when commenting code

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#10981]
### What steps reproduce the problem?

1. When annotate codes in spyder4 it add a space in front of every line. when turn to uncomment in spyder4, it is return to delete this space. but if I open codes in other ides or txt like spyder3, I should delete space once upon a time when debug! I think it is not convenient.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.0
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: ubuntu16.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by 1313e** [comment]
I am pretty sure this has to do with the fact that in PEP8, there must be a space between the `#` and the actual comment.
However, I actually find this annoying as well, as I used to comment out code and the PEP8 warnings would quickly notify me that I still had commented code somewhere (as there would be no space).
That is a minor thing though.

**Comment by zysNLP** [comment]
Yes, I just don't think the code is portable well.

**Comment by ccordoba12** [comment]
Sorry but this was requested many times in the past to have comments that are pep8 compatible, as @1313e mentioned.

So this is now the new default and there's no way to go back to the previous behavior, sorry.

**Comment by zysNLP** [comment]
Ok, Thank you.
