### ISSUE TITLE
Panes can not be resized or positioned individualy like was the case in spyder 3

### ISSUE THREAD

**Issue by Jogala** [spyder-ide/spyder#10994]
I am using Ubuntu 18.4. and I just updated to Spyder 4. 

1. Issue

The panes can not be resized. For example pane

Editor, Console, File Explorer and Variable Explorer are open. The variable explorer is automatically arranged horizontally at the bottom. But it is not possible to actually see the variables, because it is not possible to resize the variable pane!!!

![bugg_spyder_1](https://user-images.githubusercontent.com/5442389/70467275-2df2fc80-1ac5-11ea-8b79-acabcf8e3e5b.jpg)

2. Issue 

The panes can not be moved and arranged like in Spyder 3. Basically this

https://stackoverflow.com/questions/28882541/repositioning-panes-in-spyder-panes

is not working anymore. Also therefore it is not possible to have two panes overlaying each other. I liked that feature I used to bring the file pane over the terminal pane by using ctrl + shift + x and then letting it disappear again. 

Best, someone who supports you also financially, even if it is not very much as I am a poor PhD student.

**Comment by goanpeca** [comment]
Hello, you need to unlock panes before you can start rearranging them: 

<img width="254" alt="Screen Shot 2019-12-09 at 15 04 52" src="https://user-images.githubusercontent.com/3627835/70468536-464b2300-1a95-11ea-8c30-2b63dd71a622.png">

**Comment by ccordoba12** [comment]
Yep, that's the solution.

**Comment by Jogala** [comment]
No it is not. It is still not possible to resize the pane.

**Comment by ccordoba12** [comment]
Please post a video (with the Licecap application) to understand how you're unable to resize that pane.

**Comment by Jogala** [comment]
I will post a videos one of the following days!

**Comment by wqp89324** [comment]
I thought I have the same issue, but this ticket definitely helped. After unlocking, click on this icon to start dragging panes around:
![image](https://user-images.githubusercontent.com/8864839/70743405-46416200-1ce5-11ea-8e16-c5a70687795d.png)

**Comment by ccordoba12** [comment]
Closing due to lack of response.
