### ISSUE TITLE
Segmentation fault while visualizing a numpy array containing inf

### ISSUE THREAD

**Issue by Cesco14** [spyder-ide/spyder#10999]
I report a strange segmentation fault error in visualizing a numpy array containing np.inf.

```python
import numpy as np
a = np.array([np.inf,np.inf])
```

If I try to visualize it in the variable explorer, I get a segmentation fault error.
I'm using Spyder 4.0.0 on Ubuntu 19.10.

Thanks

**Comment by ccordoba12** [comment]
Duplicate of #8093

**Comment by ccordoba12** [comment]
We'll fix this in our next version.
