### ISSUE TITLE
Spyder Crashes while Launching after Attempted Update

### ISSUE THREAD

**Issue by msearles7** [spyder-ide/spyder#10995]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am working on an hp zbook running on Windows 10. It is a computer given to me by my company and therefore it has certain security protocols and procedures for installing applications. I tried using `conda install spyder=4.0.0` but this didn't work. I tried using `pip` instead and Spyder appeared to update successfully. However, when I try to launch Spyder, it crashes during the launch process. 

### What steps reproduce the problem?

1. I have tried entering the command `spyder --reset` using the Anaconda prompt. This still results in Spyder crashing on launch.
2. I have tried uninstalling and reinstalling Anaconda twice. Once using administrator privileges as I've needed to for other applications and once as usual.
3. I tried launching Spyder from the Anaconda Navigator instead of from the icon in the start menu and it still crashes while trying to launch.

### What is the expected output? What do you see instead?
The expected output is for Spyder to launch after having been updated to Spyder 4.0.0. Instead, I see the error message for when Spyder crashes.

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) C:\Users\605018>spyder
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.
Traceback (most recent call last):
  File "C:\Users\605018\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 3711, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\605018\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 3552, in run_spyder
    main.setup()
  File "C:\Users\605018\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 1010, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "C:\Users\605018\AppData\Roaming\Python\Python37\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 24, in <module>
    from jupyter_client.connect import find_connection_file
  File "C:\Users\605018\AppData\Roaming\Python\Python37\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\605018\AppData\Roaming\Python\Python37\site-packages\jupyter_client\connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write' from 'jupyter_core.paths' (C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\paths.py)

```

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> I tried using conda install spyder=4.0.0 but this didn't work. I tried using pip instead and Spyder appeared to update successfully

We warn very loudly against using pip when you have Anaconda both in our update dialog and in our release instructions (see the end of the link below):

https://github.com/spyder-ide/spyder/releases/tag/v4.0.0

Now you have corrupted your Anaconda installation (the problem you reported is a symptom of it) and have to reinstall it (or ask your IT to do it for you).

Before that, please also remove all the contents of these directories:

- `C:\ProgramData\Anaconda3`
- `C:\Users\605018\AppData\Roaming\Python\Python37`

And please **never** use pip again to update Spyder in Anaconda.
