### ISSUE TITLE
Spyder Crashes when using Replace in Selection

### ISSUE THREAD

**Issue by Jogala** [spyder-ide/spyder#11005]
Hi, I am using Ubuntu 18.

If I select text and than use the replace menu and select replace in selection, spyder gui crashes and disappears, without any notification.

**Comment by goanpeca** [comment]
@Jogala please provide the requested information on the issue, otherwise we cannot help.

**Comment by Jogala** [comment]
I will post a video the next days.

**Comment by goanpeca** [comment]
@Jogala a Video is not enough. When you opened the issue you had a lot of information requested: 



### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below


## Problem Description



### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?



### Paste Traceback/Error Below (if applicable)


```python-traceback

PASTE TRACEBACK HERE

```

## Versions


* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies


```
PASTE DEPENDENCIES HERE
```


Without this we cannot help
