### ISSUE TITLE
set_namespace_view_settings

### ISSUE THREAD

**Issue by lilyofthe** [spyder-ide/spyder#11017]
### What steps will reproduce the problem?

#upgrade issue
I was trying to upgrade syder 4.0.0, but it presumably some steps slipped off , it didn't successed . 

### Traceback
```python-traceback

**Comment by goanpeca** [comment]
See https://github.com/spyder-ide/spyder/issues/10964 for more information.

Also next time you open an issue please provide the information requested on the issue template, otherwise it will be very difficult to debug the issue and provide help.
