### ISSUE TITLE
Interrupt (Ctrl+C) in the console does not work in Spyder on Mac Os X

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1101]
_From [rebound1...@gmail.com](https://code.google.com/u/103512134821022628905/) on 2012-06-23T06:39:42Z_

I tried to interrupt a command in the console with Ctrl-C, then with Cmd-C, and then with Ctrl-Q, Ctrl-D, none of them interrupts 

What steps will reproduce the problem?

 1.  write an infinite forloop
2. Use run-selection to run it in the console
3.  try to interrupt the infinite loop using any common keyboard interrupt combination. What is the expected output? What do you see instead? I expect to see the console interrupted, but the console does not respond. 

I use spyder 2.1.10 on OS X Lion, installed through macports 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1101_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-04T07:21:27Z_

Probably a mapping a problem and a serious one :) I'll try to fix it for the next release.

**Summary:** Interrupt (Ctrl+C) does not work in Spyder on Mac Os X  
  **Owner:** ccordoba12  
  **Labels:** Cat-Console MS-v2.1 OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-07-18T06:59:20Z_

FWIW, cmd-c works for me (as long as the focus is in the console)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-18T07:02:17Z_

And Ctrl+C works for the IPython console (although I tried it in 10.6, not in 10.7). rebound1618, can you confirm?

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-07-19T06:20:03Z_

I've placed a patch [1] in the MacPorts version now that makes it ctrl-c for interrupt and cmd-c for copy (as we don't have the ambiguity on mac for this particular combo.  The patch is not cross-platform (no check for am I a mac?) currently, so it would need some fences to be merged if desired...

[1] https://trac.macports.org/browser/trunk/dports/python/py-spyder/files/spyderlib_widgets_shell.py.diff?rev=95694

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-08-06T21:21:19Z_

Be sure to grab the updated patch: https://trac.macports.org/browser/trunk/dports/python/py-spyder/files/spyderlib_widgets_shell.py.diff?rev=96288 fixes a bug where 'c' couldn't be typed in console (introduced by previous patch)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-01-27T01:44:10Z_

**Labels:** -MS-v2.1 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-28T11:48:12Z_

Thanks eborisch for the patch and sorry for the delay in answering. I'm going to merge it now.

**Summary:** Interrupt (Ctrl+C) in the console does not work in Spyder on Mac Os X  \<span class="oldvalue"> (was: Interrupt (Ctrl+C) does not work in Spyder on Mac Os X) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-28T14:53:21Z_

This issue was updated by revision 17889ffd225e .


- Before only Cmd+C was triggering an interrupt but this shorcut
is used only for copying.

**Status:** Fixed

**Comment by sgnsabir** [comment]
same issue observed in windows 11

**Comment by sgnsabir** [comment]
solved by restart kernel
