### ISSUE TITLE
Autocomplete triggered by Ctrl + Enter

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#11021]
**Steps to reproduce:**
* Write a call to some function in the editor.
* Write something inside the function arguments.
* Position the focus to right before the closing parenthesis.
* Wait until some auto-complete suggestion comes up (or don't wait at all, they will show up anyway).
* Press Ctrl + Enter (shortcut to run a line).
```python
import numpy as np
y = np.random.random(size = 1000<focus here and press Ctrl + Enter>)
```
result:
```
y = np.random.random(size = 1000ArithmeticError)
```

**Expected behavior:** should run the line (Ctrl + Enter having precedence over raw Enter).

**Actual behavior:** triggers autocomplete, and doesn't run line.

**Comment by jnsebgosselin** [comment]
The default shortcut for to run a line is `F9`. `Ctrl+Enter is for running the current cell. You can remap the keybind for these shortcuts in the settings if you want.

![image](https://user-images.githubusercontent.com/10170372/70737260-1fccf800-1ce0-11ea-8536-07a6098fdba7.png)

The auto-complete showing after a number is related to https://github.com/spyder-ide/spyder/issues/10833

**Comment by goanpeca** [comment]
Yes, working on a fix for that now.!

**Comment by ccordoba12** [comment]
> Press Ctrl + Enter (shortcut to run a line).

Lines don't run anymore with Ctrl+Enter, so you need to remap that shortcut as @jnsebgosselin pointed out.

**Comment by david-cortes** [comment]
I remapped the shortcut, but the issue still persists (Ctrl + Enter triggers autocomplete).

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification. @goanpeca said he's working on this right now.

**Comment by bcolsen** [comment]
I can confirm this. It's not the shortcut but the the fact that only enter should except the completeion and not shift or ctrl(or alt, cmd, super, meta?) + enter should except the completion.

Should this issue it be reopened?

**Comment by goanpeca** [comment]
>I can confirm this. It's not the shortcut but the the fact that only enter should except the completeion and not shift or ctrl(or alt, cmd, super, meta?) + enter should except the completion.

I do not understand what you meant, could you please rephrase?

**Comment by bcolsen** [comment]
> I do not understand what you meant, could you please rephrase?

Obviously not autocompleting on entering numbers, whitespaces or newlines fixes the original posters bug here(Great fix by the way!), but I don't think that ctrl+ enter (or shift, etc + enter) should accept completions at all. This is nice for people (like me) who work with code cells or for people who change short cuts and want ctrl+enter as inset a new line. Currently the completion overlay takes all of those key presses as accept the suggestion when it's active.

I hope this is more clear.

**Comment by ccordoba12** [comment]
@andfoy, please don't forget to address this one next week.
