### ISSUE TITLE
Request: add file landmarks to browse/move

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#11022]
Would be nice to be able to quickly browse and move through a file's content like in other IDEs and editors:
![file_landmarks](https://user-images.githubusercontent.com/11860098/70610911-0b6bfb00-1c0d-11ea-8f88-70d0891ea94a.png)

**Comment by ccordoba12** [comment]
That's already implemented. Just please `Ctrl+Alt+P` to get the symbols (i.e. classes, functions and methods) present in a file.

**Comment by david-cortes** [comment]
Good to know, thanks! Although my first thought would have been to try to find it under the editor shortcuts (context = editor) instead of the general shortcuts.

**Comment by ccordoba12** [comment]
That's because that widget can be called from any pane. For Spyder 5 we'll the ability to switch IPython consoles from it and you can already use to pick up notebooks when spyder-notebook is installed.
