### ISSUE TITLE
Feature Request: Embed Kite Sidekick In Spyder

### ISSUE THREAD

**Issue by dbirdflyshi** [spyder-ide/spyder#11029]
Instead of having a window show what's going on, is it possible to have it show up in spyder itself somewhere like a tab next to Help, Variable Explorer, Plots, and Files. Maybe an enhancement to help since help doesnt always have what you need.

**Comment by bcolsen** [comment]
That's going to be too difficult unfortunately.

Closing as a duplicate of #10904
