### ISSUE TITLE
Spyder help docs lead to a broken link https://pythonhosted.org/spyder/

### ISSUE THREAD

**Issue by a1ultima** [spyder-ide/spyder#11025]
## Description

**What steps will reproduce the problem?**

1. Install Spyder on ubuntu 18.04 using ubuntu software manager
2. X299 motherboard architecture
3. When spyder is up, press F1 for help (or click Help)

**What is the expected output? What do you see instead?**

A link to a working website, instead it was a broken link File not found

> An error occurred during a connection to pythonhosted.org.
> 
>     Check the file name for capitalisation or other typing errors.
>     Check to see if the file was moved, renamed or deleted.
> 
> 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
> Spyder Version: 3.2.6

This version is almost two years old. As usual, Debian-based Linux distros package very outdated versions of Spyder and that's not our fault.

Please download and install Anaconda if you want to use a more recent version that has the bug you reported above solved.

**Comment by a1ultima** [comment]
> > Spyder Version: 3.2.6
> 
> This version is almost two years old. As usual, Debian-based Linux distros package very outdated versions of Spyder and that's not our fault.
> 
> Please download and install Anaconda if you want to use a more recent version that has the bug you reported above solved.

OK, anaconda is not an option. Cheers.
