### ISSUE TITLE
Slow GUI on 4K monitor

### ISSUE THREAD

**Issue by bbutler3** [spyder-ide/spyder#11034]
### What steps will reproduce the problem?

**Important update to what's below:** This only happens when I launch Spyder from the Ubuntu command line in Windows 10. When I run Spyder from Windows itself, the problem is not reproduced. This makes it more likely that the issue lies in something to do with my settings, or with Windows 10's implementation of Ubuntu. Still, though, I'd be curious to know what's going on.

I just upgraded to Spyder 4.0.0 on Windows, and the GUI is extremely sluggish on 4K screens. More specifically, any graphical things I do (using the menu bar at the top, changing Preferences, etc.) are *very* slow (I have to wait a couple of seconds each time I use the backspace key in defining my own syntax coloring, for example). The actual editor window isn't sluggish at all, and neither is iPython. 

This problem *only* happens on my 4K monitor; I have a normal 1080p monitor and the sluggishness disappears if I simply drag Spyder over to it. I have also tried several different DPI scalings (Normal, Enable auto high DPI scaling, and a couple custom scalings), to no avail.

Reproducing the problem might be immediate on a different 4K monitor. Just open Spyder and navigate to some graphical menu (for example, Preferences). It becomes immediately obvious for me.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.4.0-18362-Microsoft

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
This looks like a problem with your graphics card, so not something we can solve here, sorry.

If you find a way to solve this, please let us know with a comment below.
