### ISSUE TITLE
Spyder 4.0.0 crashed constantly for Python 3.7 and Win7-64bit

### ISSUE THREAD

**Issue by tyNeanderthal** [spyder-ide/spyder#11037]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Upon updating conda (from conda prompt) and Spyder (to 4.0.0, from Anaconda Navigator), and then launching Spyder (from Anaconda Navigator), Spyder predictably crash in about 5 seconds after launched with message "Python has stopped working". Launching Spyder from the start menu or from the conda prompt gave the same results. Have tried to restart Spyder/conda/PC a couple of times, as well as updating conda, re-installing Spyder 4.0.0, and none would change the behavior. The problem seems to be resolved when re-installed and launched Spyder 3.3.6, but re-emerge when re-updated to 4.0.0.

### What steps reproduce the problem?

1. update conda (conda version : 4.8.0
conda-build version : 3.15.1
python version : 3.7.0.final.0)
2. update Spyder to 4.0.0
3. launch Spyder

### What is the expected output? What do you see instead?
I wasn't interacting with Spyder so I expect it to remain still. It crashed instead.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

I ran "spyder --debug-info verbose --debug-output file"
and attached the log
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/3953652/spyder-debug.log)

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.0.final.0
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 7 Professional (service pack 1)

### Dependencies

```
PASTE DEPENDENCIES HERE
```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

**Comment by ccordoba12** [comment]
> I ran "spyder --debug-info verbose --debug-output file"
and attached the log
spyder-debug.log

There's nothing fishy in your debug output.

> The problem seems to be resolved when re-installed and launched Spyder 3.3.6, but re-emerge when re-updated to 4.0.0.

Then we recommend you to keep using 3.3.6 until we add the ability to report hard crashes like the one you're reporting in our next version (4.1.0).

I'm going to close this one because there's nothing else we can do for you until 4.1.0 is out.

**Comment by tyNeanderthal** [comment]
OK. Just an update, I upgraded the dependencies marked NOK, and wasn't able to change the behavior. This is the updated dependency log while the crash is reproduced.

cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  2.2.2 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

**Comment by dweissner** [comment]
Do you guys have an ETA on the new Spyder? Mine keeps crashing too.

**Comment by ccordoba12** [comment]
Hopefully it'll be available in Anaconda by the end of the week at most. Unfortunately, we are not in control of that.

**Comment by vinejain** [comment]
I updated to spyder 4.0 (python 3.7, Win10), it works fine at first then spyder just freezes every 5 mins with 'Not Responding' message. Its a headache as I have to remember to keep saving my code in every 2-3 mins before it crashes. I re-installed, have the same issue.

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.3
