### ISSUE TITLE
Spyder4.0.0 official release fails  - Aborted (core dumped)  [FIX?]

### ISSUE THREAD

**Issue by stavna** [spyder-ide/spyder#11044]
in continuation to #10604 - we found the potential trouble maker!

after creating a fresh conda env, and installing the latest spyder4.0.0 official release I was still receiving the same error as in  #10604 

BUT
after executing
$ conda remove --force rtree

spyder4 loads!! but prompts an error that rtree is missing (duhh) but at least it runs.

any ideas ??
@ccordoba12 

Thanks!

**Comment by ccordoba12** [comment]
> $ conda remove --force rtree

You won't have code snippets in the Editor if you remove rtree.

> spyder4 loads!! but prompts an error that rtree is missing (duhh) but at least it runs.

You'll see this message everytime Spyder starts and there's nothing to do about it, sorry.

> any ideas ??

I'm glad you found the solution to your problem. However, we can't do anything for you here.

Instead, please inform the Anaconda people [here](https://github.com/ContinuumIO/anaconda-issues/issues/) that rtree packages on Linux are not compiled for the same Glibc version as the other ones, which is causing the problem you described on issue #10604.

**Comment by stavna** [comment]
@ccordoba12 
Id like to note that rtree packages works perfectly in conda env (tested on ipython etc/)

its just the spyder4 ide that crashs with it

**Comment by ccordoba12** [comment]
If you're implying that we access special functions of rtree for specific glibc versions, I can assure you that's not the case.
