### ISSUE TITLE
update spyder4

### ISSUE THREAD

**Issue by MrCrazyCrab** [spyder-ide/spyder#11041]
@yuvipanda 
 i have update the anoconda to the latest version(1.9.7) on windows10, but i still can not to update spyder to 4.0. However, i can use spder 4.0 on ubunto16.04 when i use the anoconda navigator1.9.7.
I have followed the issuse 10964, but i meet a new 
![QQ截图20191212135911](https://user-images.githubusercontent.com/52489106/70686711-13e53400-1ce8-11ea-867e-49f6f46f90be.png)
and if i copy the Anaconda/DLLS/libssl-1_1-x64.dll to Anaconda/Library/bin, i can install the spyder4.0. But when i start it, i come into that:
```
Traceback (most recent call last):
File "D:\Progran_file\Anaconda3\envs\py1_2\lib\site-packages\spyder\app\mainwindow.py", line 3711, in main
mainwindow = run_spyder(app, options, args)
File "D:\Progran_file\Anaconda3\envs\py1_2\lib\site-packages\spyder\app\mainwindow.py", line 3552, in run_spyder
main.setup()
File "D:\Progran_file\Anaconda3\envs\py1_2\lib\site-packages\spyder\app\mainwindow.py", line 1010, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "D:\Progran_file\Anaconda3\envs\py1_2\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 52, in 
from spyder.plugins.ipythonconsole.widgets import ClientWidget
File "D:\Progran_file\Anaconda3\envs\py1_2\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in 
from .debugging import DebuggingWidget
File "D:\Progran_file\Anaconda3\envs\py1_2\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 22, in 
from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'
```
So how can i solve it?
looking for you reply.

**Comment by leavor** [comment]
用Anaconda搞的新的虚拟环境，同时安装spyder就行了，我就是这么搞的
conda create -n python37 python=3.7 spyder=4.0

**Comment by ccordoba12** [comment]
It looks like you need to reinstall Anaconda because your current installation is broken.

**Comment by GabrieleBrambilla** [comment]
Unfortunately I don't think it's an uncommon case.
Recently I tried to update Anaconda and then Spyder from 3 to 4 on two different machines and in both of them Spyder stopped working with this error. I think either Anaconda or Spyder "updater" is broken...

**Comment by ccordoba12** [comment]
It's usually better to use a new conda env to try major Spyder versions, instead of updating things in the base env.

**Comment by Ardentflame** [comment]
I have the same problem, I used pip to install the new update, i'm on Linux Mint and a beginner in Linux.

**Comment by ccordoba12** [comment]
If you're beginner please use Anaconda. Pip is for experts or very knowledgeable people.

**Comment by rbgt** [comment]
I had this problem, if you have this message you need to update your IPython by doing : 
`conda update IPython`
If you have several environment, just precise the environment you installed spyder : 
`conda update IPython -n (envname)`

**Comment by kurt-rhee** [comment]
I have this issue.  Spyder in the base environment works fine with spyder kernels in a virtual environment.  It does not work with spyder kernels in a different virtual environment.

**Comment by mattpopovich** [comment]
For whoever else runs into this unfortunate scenario, after trying to fix my environment to no avail... it was just easier to create a new environment as @leavor suggested: 
`conda create -n python37 python=3.7 spyder=4.0`
Not sure if there's an issue with the most recent version of spyder or Python but I can confirm Python 3.7 and spyder 4.0 work together.

**Comment by KunZhou9646** [comment]
Agree with @rbgt. Just update your IPython with conda.
