### ISSUE TITLE
Help problem

### ISSUE THREAD

**Issue by mohamed22251** [spyder-ide/spyder#11045]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
# there is a problem with the Help 

![image](https://user-images.githubusercontent.com/54647305/70708709-cff03000-1ce3-11ea-832d-5d6eb3151cc8.png)

**Comment by ccordoba12** [comment]
Sometimes help can be parsed correctly. Sorry but that's something we can solve for now, maybe in Spyder 5.
