### ISSUE TITLE
Feature request: add a minimum height for the slider range of the scrollflag panel

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#11050]
## Problem Description

The slider range of the scrollflag panel is really useful for navigating quickly from one place to another in a file.

By design, the height of the slider range is scaled to the total height of the file. However, unlike the scrollbar's slider, there is no minimum height set on the scrollflag panel's slider range. So for files with a lot of lines, it becomes very small and can be hard to see on the screen.

I was thinking that maybe we should set a minimum height for the scrollflag panel's slider range. We could use the same minimum value as that used for the scrollbar?

![image](https://user-images.githubusercontent.com/10170372/70720557-00bf6d80-1cc2-11ea-84b1-89428baee5d2.png)

**Comment by ccordoba12** [comment]
> I was thinking that maybe we should set a minimum height for the scrollflag panel's slider range. We could use the same minimum value as that used for the scrollbar?

Good suggestion @jnsebgosselin! I agree with it!

Since I don't this to be a big change, you can make it for `4.x`.
