### ISSUE TITLE
I can not launch after previous spyder upgare

### ISSUE THREAD

**Issue by ainureg** [spyder-ide/spyder#11052]
I upgraded spyder. Everything seems to be ok. After I reboot my comp I can not lauch it.
Well, I created new virtual env
```
python3 -m venv virtenv/
pip3 install --pre -U spyder  
```
![image](https://user-images.githubusercontent.com/5558125/70733380-43616400-1d1b-11ea-9cf1-afbd86278501.png)
btw it's the same error.
spyder-4.0.0-py3

```
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

```

**Comment by ainureg** [comment]
btw, previous version 
pip3 install spyder==4.0.0rc2
helped me a lot. It works fine

**Comment by ccordoba12** [comment]
I'm sorry but we don't have the time nor the resources to help people with pip installations. So our only suggestion is for you to switch to Anaconda.
