### ISSUE TITLE
qtconsole 4.6.0 installed, Spyder reads qtconsole 4.5.1

### ISSUE THREAD

**Issue by Code-Babylon** [spyder-ide/spyder#11051]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Code-Babylon** [comment]
Problem Description:
Spyder says qtconsole is version 4.5.1 but Anaconda environments says version 4.6.0 is installed

Steps to Reproduce:
1. Install Anaconda
2. Update Spyder 3.3.6 to Spyder 4.0.0
3. Open Spyder 4.0.0

Expected output:
Use iPython console

What happens instead:
It just says "Connecting to kernal"

Error:
You have missing dependencies!

 qtconsole >= 4.6.0: 4.5.1 

Please install them to avoid this message! 

Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you install all the listed missing dependencies. 

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.

Versions:
Spyder: 4.0.0
Python: 3.7
Qt: ?
PyQt: (Could someone please tell me the difference between Qt and PyQt?)
OS: Windows 10

Dependencies:
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.5.1 (NOK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.2 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.6.1 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

**Comment by ccordoba12** [comment]
> qtconsole >=4.6.0 : 4.5.1 (NOK)

This is even reported here above among your dependencies.

As I said to you in jupyter/qtconsole#398, you need to solve this by yourself. So please **stop** creating new issues for this in different repos.

If necessary, please remove and reinstall Anaconda. After that, you need to do

    conda update anaconda
    conda install spyder=4

**Comment by ccordoba12** [comment]
Those two command should fix your problem.

**Comment by Code-Babylon** [comment]
I tried that. Multiple times. It didn't work. And yes, I see it's reported in the dependencies, but that doesn't mean I know what the problem is. Also, how can I solve a problem for myself when I myself have tried multiple different ways to solve this problem and have run out of options?

**Comment by ccordoba12** [comment]
What have you tried exactly?

**Comment by Code-Babylon** [comment]
I have tried uninstalling, reinstalling, and updating Spyder, I have tried uninstalling, reinstalling, and updating qtconsole, I have tried uninstalling, reinstalling, and updating Anaconda itself. Plus, I'm new to Anaconda, I'm new to Spyder, so I don't know everything, so I'm looking for help. That's the whole reason for these forums is to seek help, right? Not have someone say "Oh, that's your own problem. Deal with it yourself" and have that person close your issue without the problem being solved.

**Comment by ccordoba12** [comment]
> Not have someone say "Oh, that's your own problem. Deal with it yourself" and have that person close your issue without the problem being solved.

This problem can't be solved by us, it's a problem in your computer. So I don't know what else you expect us to do.

Besides, by opening an issue here, in qtconsole and a question in StackOverflow (yes, I saw that too), you're annoying us a lot for a very simple problem. That's not only very unpolite, but also your demand that we **must** give you help to solve it. If you want to be a programmer, you should be prepared for this kind of issues and learn how to solve them by yourself.

Now, my last piece of advice is this. I think that at some point you used pip to install qtconsole (or some other packages), so the 4.5.1 version reported in our dependencies should be coming from it. So you need to look for the `qtconsole` name in your entire PC, detect where it is installed and remove its directory and all other package directories at the same level.

**Comment by Code-Babylon** [comment]
I'm not saying you **must** give me help, I'm merely asking for help. I ask for help when my research and trial and error tests have run dry. While this problem **may** seem simple to you, for someone new to Anaconda, it is not so simple. And no, I have not used pip for Anaconda in any capacity whatsoever. I have searched `qtconsole` on my computer and tried deleting qtconsole 4.5.1 from it to no avail. 

I'm here looking for advice on what I am possibly missing or doing wrong. That is all.

**Comment by ccordoba12** [comment]
> I'm here looking for advice on what I am possibly missing or doing wrong. That is all.

Ok. You could also try to remove by hand the folder where Anaconda is installed.

> I have searched qtconsole on my computer and tried deleting qtconsole 4.5.1 from it to no avail.

qtconsole 4.5.1 should be installed somewhere in your computer, so you need to find it and remove it.

**Comment by Ianfrancisuk** [comment]
I have some sympathy with Code-Babylon as I had the same troubles.  In fairness to ccordoba12 he was trying to help, but this particular problem leaves you spinning around installing/uninstalling Anaconda and Spyder and Qt Console, I was also getting same warning on jedi.  In the end it was because I had been dabbling with Python before Anaconda and Qtconsole et al was in my AppData\Python\Python37 directory - which was on my path.

Hope that saves others the stress.

**Comment by ccordoba12** [comment]
Thanks for the input @Ianfrancisuk! At the end @Code-Babylon found that that was their problem too.
