### ISSUE TITLE
It looks like you need to reinstall Anaconda because your current installation is broken.

### ISSUE THREAD

**Issue by MrCrazyCrab** [spyder-ide/spyder#11067]
It looks like you need to reinstall Anaconda because your current installation is broken.

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/11041#issuecomment-565007805_

i don't think so. i have reinstalled the anoconda. And it has the same question, but if found when i use tensorflow it's ok to upgrade spyder4.0, and it won't work in pytorch.

**Comment by ccordoba12** [comment]
Then please a different conda env to work with Pytorch, instead of installing it alongside Spyder. To understand how to do that, please read our guide for that:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
