### ISSUE TITLE
Allow users to choose if plots appear as pop up windows or in the dedicated pane

### ISSUE THREAD

**Issue by dhendricks-medic** [spyder-ide/spyder#11062]
## Problem Description
I just installed a fresh copy of spyder 4.0.0 (clean install of anaconda) and was stunned to discover that having plots appear as separate pop up windows was no longer supported, but that all plots are forced to be inline or in the dedicated "plots pane."

This is a major step backwards for people who routinely need multiple plots to understand complex data sets, and to iterate quickly through changes in their code. Creating multiple pop up windows and placing them strategically on a separate monitor before testing changes to your pipeline is a huge benefit. I have no desire to interact with all plots in a single pane, even if that pane is pop-out-able.  

If this is already an option, then it needs to be displayed in a more prominent/user friendly place because I could not find the option after searching for it for over half an hour. 

### What steps reproduce the problem?

Upgrade to Spyder 4.0.0

### What is the expected output?

Users have the option of using a dedicated pane for all plots OR an option of using separate pop up windows for each new plot.

## Versions
* Spyder version: 4.0.0
* Python version: Python 3.6.9 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

**Comment by ccordoba12** [comment]
> I just installed a fresh copy of spyder 4.0.0 (clean install of anaconda) and was stunned to discover that having plots appear as separate pop up windows was no longer supported, but that all plots are forced to be inline or in the dedicated "plots pane."

This is not true. To have plots in separate windows, you just need to change your graphics backend in the menu

    Tools > Preferences > IPython console > Graphics > Graphics backend

and change the `Backend` entry from `inline` to `Automatic`.

> If this is already an option, then it needs to be displayed in a more prominent/user friendly place because I could not find the option after searching for it for over half an hour.

This has been the way to do this for a very long time (5 years or more). So we don't think it's necessary to promote it more.

**Comment by dhendricks-medic** [comment]
Thank you for your quick response. I love spyder and appreciate the work you do on it.

Before creating this issue, I had tried switching from inline to automatic (as I do every time I install a new version of spyder), but it did not change anything. I restarted spyder and the plots continued to display in the pane. 

After your comment, I closed spyder, re-launched it yet again, and the plots continued to display in the pane. I then restarted the ipython kernel, and then plots popped out in a separate window. 

So somehow closing and restarting spyder did not affect the changes, but restarting the kernel did...

I don't think it's worth re opening for this, but it was a minor quirk.

Thanks again for the response.

**Comment by ccordoba12** [comment]
> So somehow closing and restarting spyder did not affect the changes, but restarting the kernel did...

Sorry, that's a usability issue that leads to terrible confusions like the one you just reported here. We'll try to fix it for Spyder 5.
