### ISSUE TITLE
Variables always removed before execution

### ISSUE THREAD

**Issue by ortk95** [spyder-ide/spyder#11079]
### What steps will reproduce the problem?

Since upgrading to Spyder 4, variables always seem to be removed before code execution, regardless of the _Remove all variables before execution_ setting.

For example, with the simple test script:

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
try:
    print(x)
except NameError as e:
    print(repr(e))
	
x = 1
```

I would expect the output to be `NameError("name 'x' is not defined")` the first time the script is run, then the output to be `1` the second time. However, every time I run the script, I always get `NameError("name 'x' is not defined")`.

I am able to view the value of `x` in the variable explorer and in the iPython console as normal after running the script, so it appears the issue occurs at the start of running the test script.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by jnsebgosselin** [comment]
Thanks for you report. Please got to Issue https://github.com/spyder-ide/spyder/issues/11015 for the solution to your problem.

I'm going to close this issue but if this doesn't cover it for your use case feel free to reopen.
