### ISSUE TITLE
Copying or duplicating multiple selected lines deselects last line each time

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#11070]
Currently on Spyder 4.0.0 but this one was there in Spyder 3 too, yet it seems no one was bothered enough to report it :smile: 

There's a small but irritating bug in the way `copy line` and `duplicate line` work for a selection of lines in the Editor.

If you select the lines up to the next new line, which is the normal way to select multiple lines using the keyboard, that each time you do `copy line` (`Alt+Shift+Down`) or `duplicate line` (`Alt+Shift+Up`) it forgets about the last copied line, i.e. deselects it. Thus, with each new copy, a smaller number number of the originally selected lines is copied, like so:

<img src="https://user-images.githubusercontent.com/15214418/70788311-e86a5400-1d90-11ea-86c3-5461af7acff7.gif" width="300" />

On the other hand if you select the lines up to the end of the last line, which takes more keystrokes to do, the copying works as expected:

<img src="https://user-images.githubusercontent.com/15214418/70788400-18195c00-1d91-11ea-8d4a-06c529e8086b.gif" width="300" />

**Comment by jnsebgosselin** [comment]
I can replicate this. Thanks for reporting.

I think this is something I can fix if you need @ccordoba12.

**Comment by ccordoba12** [comment]
Yes, please do @jnsebgosselin. And thanks for your help!
