### ISSUE TITLE
Turning off highlight of current "window "

### ISSUE THREAD

**Issue by MichelangeloConserva** [spyder-ide/spyder#11078]
### What steps will reproduce the problem?

I cannot find a way to turn off the option that makes every tab I have the cursur on highlighted. 

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.0.0-36-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by goanpeca** [comment]
Could you please provide a screenshot to understand what you mean?

Thanks

**Comment by MichelangeloConserva** [comment]
![Screenshot from 2019-12-14 08-32-02](https://user-images.githubusercontent.com/37903256/70845949-6b041980-1e4c-11ea-974c-2e62c8dfa1a2.png)
![Screenshot from 2019-12-14 08-32-06](https://user-images.githubusercontent.com/37903256/70845950-6b9cb000-1e4c-11ea-98ec-ecd6ef55cde4.png)

The blue lines in the pictures that highlight the frame of the window you mouse is over.

**Comment by goanpeca** [comment]
That is part of the theme (https://github.com/ColinDuquesnoy/QDarkStyleSheet ) and something that cannot be disabled on Spyder.

**Comment by ccordoba12** [comment]
Closing because we can't solve this here.
