### ISSUE TITLE
Kite pop-up doesn't show up if Editor pane undocked

### ISSUE THREAD

**Issue by Rational-IM** [spyder-ide/spyder#11076]
Kite works fine if Editor pane docked (see Picture 1). If I undock the Editor pane and move to another monitor (let's say the "Vertical Right" monitor you see on Picture 1), Kite's pop-up window will not show up. You can see on Picture 2 an example of the issue (i.e. the absence of Kite's pop-up window).

I also observed that some shortcuts don't work if the Editor pane is undocked and on another monitor. For instance, if the cursor is on the Editor pane when undocked, and I press F5, it will not run the file. I have to click on the Console pane first. Maybe both issues are interconnected?

PS: tagging @metalogical as requested (as I contacted Kite first about the issue)

### Picture 1
<img width="640" alt="Full screen" src="https://user-images.githubusercontent.com/57544001/70808051-dedeed00-1d8c-11ea-8f2f-84399e55dd93.png">

### Picture 2
<img width="316" alt="Kite not working" src="https://user-images.githubusercontent.com/57544001/70808071-e7cfbe80-1d8c-11ea-9729-86a05adbe0b3.png">

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
