### ISSUE TITLE
Syntax theme is not matching the interface theme

### ISSUE THREAD

**Issue by Hujedamej** [spyder-ide/spyder#11085]
Version: 4.0.0

The name of the interface theme Dark should be changed to blue.
If I change the Syntax theme in spyder to t.ex. Monokai the main editor background gets dark but the rest of the elements are still blue.

Am I making it wrong or is it intended to look like that - it hurts in the eyes.
It would be great if one could change the color theme of the whole spyder window.

**Comment by ccordoba12** [comment]
> The name of the interface theme Dark should be changed to blue.

Dark doesn't mean black.

> Am I making it wrong or is it intended to look like that

It's intended because we're using the [QDarkStyle](https://github.com/ColinDuquesnoy/QDarkStyleSheet) package to provide a dark theme in Spyder.

> it hurts in the eyes.

That's your opinion.

> It would be great if one could change the color theme of the whole spyder window.

Unless you want to contribute to QDarkStyle, that's not going to happen in the short nor the mid term.

**Comment by Hujedamej** [comment]
fair points,
thanks for your answer
