### ISSUE TITLE
Outline pane is too slow when updating

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#11084]
As a follow up to PR #11010 partially fixing #10992 

For large files the outliner updates are still quite slow. You can see the difference after #11010 by closing and opening the outliner pane.

The next step would be to optimize `populate_branch` or only run partial updates on the document near the change: https://github.com/spyder-ide/spyder/blob/d3a0aeb442f366bc03489ce85cb04cbd467b5e75/spyder/plugins/outlineexplorer/widgets.py#L495

It could also be put into a non-blocking thread as well.

**Comment by ccordoba12** [comment]
Do you have to do this soon @bcolsen? I'm asking because I plan to do a 4.0.1 release next week with all the optimizations done during these days.

**Comment by goanpeca** [comment]
>It could also be put into a non-blocking thread as well.

Definitely something to do. On the other hand, we could get rid of most of the code and use  the pyls to populate it. But before we can do that we need to add cell capability to the pyls.

**Comment by ccordoba12** [comment]
> Definitely something to do. On the other hand, we could get rid of most of the code and use the pyls to populate it. But before we can do that we need to add cell capability to the pyls.

I definitely think we should leave this for Spyder 5. I know is though to maintain for v4, it could require a big refactoring to move things to the PyLS.

**Comment by bcolsen** [comment]
>  Do you have time to do this soon @bcolsen? I'm asking because I plan to do a 4.0.1 release next week with all the optimizations done during these days.

I think a 4.0.1 release is would be great. I won't have time in the next week or so, but over the break I'll try to see if there are any simple things I can do to speed it up.

**Comment by ccordoba12** [comment]
This no longer applies with the move to use LSP symbols in in 4.2
