### ISSUE TITLE
"Select All" in Variable Explorer for DataFrames

### ISSUE THREAD

**Issue by matbuechner** [spyder-ide/spyder#11096]
Hi, 

thanks for the great Spyder 4 release. 

I have noticed that in contrast to Spyder 3, when opening a pandas DataFrame (with index and column names) in the variable explorer and hitting "Select All", this will **not** copy the index / column names. For copying and pasting to external applications it would be great if the old behaviour from Spyder 3 that also copied index and column headers could be re-established.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a valid request.

@dalthviz, please take a look at this one.
