### ISSUE TITLE
Copy line and duplicate line shortcuts are confusing

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#11092]
In my opinion, the `copy line` and `duplicate line` shortcuts are confusing. From the dosctrings in the source code, these shortcuts are defined as :

copy line :  Paste the duplicated text *before* the current line/selected text
duplicate line: Paste the duplicated text *after* the current line/selected text

I think that "copy" and "duplicate" do not imply that the text is copied either up or down or below or after. I think it would be clearer if, as in vscode for example, we refer to these shortcuts as:

- `Copy line down` and `Copy line up` or
- `Copy line above` and `Copy line below` or
- `Duplicate line down` and `Duplicate line up` or
- `Duplicate line above` and `Duplicate line below`

https://vscode-docs.readthedocs.io/en/stable/customization/keybindings/

![image](https://user-images.githubusercontent.com/10170372/70855889-45a0fb00-1ea0-11ea-8c28-91a76db7d7a6.png)

**Comment by goanpeca** [comment]
Agreed!

**Comment by ccordoba12** [comment]
+1 from me too.
