### ISSUE TITLE
Magics are marked as invalid syntax in ipy files

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#11090]
### What steps will reproduce the problem?

1. Create a `.ipy` file containing on a line `%matplotlib qt5`
2. The editor informs me this in invalid syntax, while this is valid ipython code.
3. 

### What is the expected output? What do you see instead?

I would suggest passing the code through `IPython.core.inputtransformer2.transform_cell` before sending it to PyLS.

## Versions

* Spyder version: 5.0.0.dev0 b93be993d
* Python version: 3.7.5
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.2.0

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.7.0.dev0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.1 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0.dev0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.11.0.dev (OK)
matplotlib >=2.0.0           :  3.1.2 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.3 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
applaunchservices >=0.1.7    :  0.2.1 (OK)
```

**Comment by ccordoba12** [comment]
So linting and code completion are working for `.ipy` files?

**Comment by impact27** [comment]
Not yet but I am working on it. (I am not trying to integrate any magic completion but that would be nice)

**Comment by impact27** [comment]
> So linting and code completion are working for `.ipy` files?

Yes but if we want magic completion we need to update PLS to work with ipy files.

**Comment by goanpeca** [comment]
So the approach would be to remove any magic related warnings if the file extension is .ipy since jedi does not have any special handling of those files AFIK.

**Comment by impact27** [comment]
> So the approach would be to remove any magic related warnings if the file extension is .ipy since jedi does not have any special handling of those files AFIK.

The approach is to translate ipython code to python code and send that to PLS

**Comment by goanpeca** [comment]
>The approach is to translate ipython code to python code and send that to PLS

Cool, yes I saw that

**Comment by ccordoba12** [comment]
> Should we move that translation step to pyls?

I think so, yes. Processing should be done on the server side, not ours (like folding computations). The most important thing is to preserve line numbers, so linting and code completions keep working as expected.

**Comment by impact27** [comment]
> I think so, yes. Processing should be done on the server side, not ours (like folding computations). The most important thing is to preserve line numbers, so linting and code completions keep working as expected.

There is two problems with preserving lines numbers that you need to be aware of:
 - `IPython.core.inputtransformer2.transform_cell` removes any leading blank line. (I am adding them back)
 -  In the case of a cell magic, `transform_cell` outputs a single line. (The cell magic only work if they are the first line of the transformed code. This is also a problem if you want to run a file with several cell magic because they will be treated a line magic.)

I don't think we should solve the runfile problem. You can see it by running in ipythonconsole:
```
%%python2
print '1'
```
(prints 1)

and
```
# comment
%%python2
print '1'
```
(SyntaxError)

**Comment by ccordoba12** [comment]
> I don't think we should solve the runfile problem

Agreed. `runfile` has never worked with IPython magics, so there won't be a regression if we don't support them with it in Spyder 4.
