### ISSUE TITLE
Project creation causes crash

### ISSUE THREAD

**Issue by edwin-bergstedt** [spyder-ide/spyder#11116]
### What steps will reproduce the problem?

I tried creating a new Project, when i clicked on the "File Explorer" the software froze and I had to force quit. Repeated several times with the same result. Tried to create a Project without clicking the file explorer. The program froze. The program restarted in a temporary file and in a frozen state. I had to delete the newly created project folder to recover.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.5-050305-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
pylint >=0.25                :  2.4.3 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.13 (OK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.2 (OK)
numpy >=1.7                  :  1.17.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
Does your project has a lot of files?

**Comment by edwin-bergstedt** [comment]
Hello,

No, it was a empty project.

Best regards Edwin

**Comment by ccordoba12** [comment]
Are you trying to create in a directory with non-ascii characters (e.g. ñ, á, etc) on its name?

**Comment by edwin-bergstedt** [comment]
No, no special characters. As soon as I press the icon to access the file
browser I got the crash. Repeated multiple times with the same result. Then
I tried just pressing create without accessing the file explorer, the
program crashed.

**Comment by ccordoba12** [comment]
> As soon as I press the icon to access the file browser I got the crash

What icon?

**Comment by edwin-bergstedt** [comment]
In the menu: Project -> New Project -> Dialog box appears. There are a name
field and a location field on the dialog. If I press inside the location
field, I get a crash. There are also a small icon to the right of the
location field that opens the file browser (at least on Spyder3), I get the
crash as soon I press the icon.

Den tis 17 dec. 2019 kl 21:04 skrev Carlos Cordoba <notifications@github.com

**Comment by ccordoba12** [comment]
What Linux distro are you using?

**Comment by edwin-bergstedt** [comment]
I'm running Linux mint 19.2

Den tis 17 dec. 2019 kl 22:10 skrev Carlos Cordoba <notifications@github.com

**Comment by ccordoba12** [comment]
With gnome-shell?

**Comment by edwin-bergstedt** [comment]
I tried on another system with almost identical setup an it worked. So I
did a reset on the settings and did a reboot and now everything works
again.
Thank you for your assistance, I really appreciate the work and effort you
put into this project.

Best regards Edwin

Den tis 17 dec. 2019 kl 22:54 skrev Carlos Cordoba <notifications@github.com

**Comment by ccordoba12** [comment]
Ok, great to know you managed to solve this problem.
