### ISSUE TITLE
Connecting to kernel not going away

### ISSUE THREAD

**Issue by Code-Babylon** [spyder-ide/spyder#11111]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
IPython terminal keeps saying "Connecting to kernel", so I can't use the terminal. I have tried to look at other solutions people have come up with, but nothing has worked.

### What steps reproduce the problem?

1. Download Anaconda
2. Open Anaconda Prompt and enter conda update --all
3. Open Spyder 4

### What is the expected output? What do you see instead?
I expect to use the terminal, but I keep seeing "Connecting to kernel"

### Paste Traceback/Error Below (if applicable)
Unsure how to get the traceback

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.5
* Qt version: 5.7.9
* PyQt version: 5.9.2
* Operating System name/version:  Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.2 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.6.1 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Is this the same problem you asked help for on StackOverflow? About jupyter_console, I mean.

**Comment by Code-Babylon** [comment]
No, different help. I got that one fixed, as the error no longer shows up.

**Comment by ccordoba12** [comment]
This is usually caused by your firewall and/or antivirus. Please disable them and try again.

**Comment by Code-Babylon** [comment]
Just tried disabling my firewall/antivirus, but it didn't work.

**Comment by ccordoba12** [comment]
Then please open the Anaconda Prompt, run the following command:

    spyder --debug-info verbose --debug-output file

and upload here the file called `spyder-debug.log`, which is created in the same directory where you ran the command above.

**Comment by Code-Babylon** [comment]
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/3971447/spyder-debug.log)

**Comment by Code-Babylon** [comment]
There's the flie

**Comment by ccordoba12** [comment]
I'm sorry but I don't see anything strange in that file. What happens if you open other consoles by going to the menu

    Consoles > New console

? Does the problem persist?

**Comment by Code-Babylon** [comment]
The same thing happens. Just a constant "Connecting to kernel"

**Comment by ccordoba12** [comment]
What happens when you open the Anaconda Prompt and run there

    jupyter qtconsole

? Are you able to evaluate code there or not?

**Comment by Code-Babylon** [comment]
I did a ```print("Hello World")``` test there, and that ran. Not sure how I can run my code from Spyder there though.

**Comment by ccordoba12** [comment]
Please go to the menu

    Tools > Preferences > IPython console > Graphics

turn off the option called `Activate support`, close Spyder and open it again.

**Comment by Code-Babylon** [comment]
I did that, but I still have the "Connecting to kernel" thing

**Comment by juliareis** [comment]
I'm having the same issue.

**Comment by ccordoba12** [comment]
Please close Spyder, open the Anaconda Prompt, run there

    spyder --reset

and try again.

**Comment by juliareis** [comment]
Thank you! What worked was I ran conda update conda from Mac's terminal, and then spyder --reset.

**Comment by Code-Babylon** [comment]
I reset spyder --reset, but that didn't work. Still had "Connecting to kernel"

**Comment by Code-Babylon** [comment]
Just tried uninstalling Anaconda and reinstalling it. It didn't work

**Comment by ccordoba12** [comment]
I'm sorry but I have no idea what's happening in your case.

**Comment by Code-Babylon** [comment]
Guess I have to use 3.3.6 then. I prefer 4 as it uses Kite and the UI is better in my opinion.

**Comment by ccordoba12** [comment]
Ok, let's try one more thing. Please open the Anaconda Prompt and run there

    python -m spyder_kernels.console

and report here the text printed in the console afterwards.

**Comment by Code-Babylon** [comment]
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-17360.json
Traceback (most recent call last):
  File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\lib\site-packages\spyder_kernels\console\__main__.py", line 11, in <module>
    start.main()
  File "C:\Anaconda3\lib\site-packages\spyder_kernels\console\start.py", line 306, in main
    kernel.initialize()
  File "<C:\Users\John Boland\AppData\Roaming\Python\Python37\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\Users\John Boland\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\John Boland\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "C:\Users\John Boland\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\John Boland\AppData\Roaming\Python\Python37\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 35, in __init__
    self.frontend_comm = FrontendComm(self)
  File "C:\Anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 87, in __init__
    parent_close = self.kernel.parent.close
AttributeError: 'IPKernelApp' object has no attribute 'close'

**Comment by ccordoba12** [comment]
Ok, finally we have an error to take a look at and the solution is very simple (although I don't understand why it was displayed in the console directly).

To solve this you need to manually remove this directory:

    File "C:\Users\John Boland\AppData\Roaming\Python

The directory above was created by pip, so in the future please avoid using pip to install Python packages if those packages are provided by Anaconda too (i.e. if they can be installed by `conda install package_name`). 

Please remove that directory and report back to know if it solves your problem.

**Comment by Code-Babylon** [comment]
I have some packages that I can't seem to install using Anaconda though, so how would I install them? (google being an example)

**Comment by Code-Babylon** [comment]
Removing the directory worked

**Comment by ccordoba12** [comment]
You should only install those packages with pip, not core packages like `ipykernel` and `traitlets`, which is clear from the error you posted that they were also installed by pip, either directly or by installing other packages that depend on them.

**Comment by ccordoba12** [comment]
> Removing the directory worked

Ok, great to know! At last!

**Comment by JSharp4273** [comment]
Hello I am sorry to bother you.
I am facing the same issue. 
I execute the command: `python -m spyder_kernels.console
` here is the output for my case:

_NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-30659.json
Traceback (most recent call last):
  File "/hdd2/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/hdd2/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/hdd2/anaconda3/lib/python3.7/site-packages/spyder_kernels/console/__main__.py", line 11, in <module>
    start.main()
  File "/hdd2/anaconda3/lib/python3.7/site-packages/spyder_kernels/console/start.py", line 306, in main
    kernel.initialize()
  File "</hdd2/anaconda3/lib/python3.7/site-packages/decorator.py:decorator-gen-124>", line 2, in initialize
  File "/hdd2/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/hdd2/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 484, in initialize
    self.init_kernel()
  File "/hdd2/anaconda3/lib/python3.7/site-packages/ipykernel/kernelapp.py", line 389, in init_kernel
    user_ns=self.user_ns,
  File "/hdd2/anaconda3/lib/python3.7/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/hdd2/anaconda3/lib/python3.7/site-packages/spyder_kernels/console/kernel.py", line 35, in __init__
    self.frontend_comm = FrontendComm(self)
  File "/hdd2/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/frontendcomm.py", line 87, in __init__
    parent_close = self.kernel.parent.close
AttributeError: 'IPKernelApp' object has no attribute 'close'_

It is quite obscured to me where is the error.

I previously try to reset spyder as well as reinstall it without success.

Thanks in advance for any help.
