### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by magichush** [spyder-ide/spyder#11119]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
When I check an big array(shape 6050,) in variable explorer, the variable explorer reports an error.which not occur when i check small array.

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
