### ISSUE TITLE
Spyder error with python3

### ISSUE THREAD

**Issue by krnvi** [spyder-ide/spyder#11123]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I open spyder3 I'm getting below shown error

 get_ipython().kernel._show_mpl_backend_errors()

AttributeError: 'SpyderKernel' object has no attribute '_show_mpl_backend_errors'
Please advise
### What steps reproduce the problem?

1. install spyder3 with dnf install python3-spyder on fedora 30
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  3.3.4
* Python version: 3.7.5 64 bit
* Qt version: Qt 5.12.1 
* PyQt version: PyQt5 5.11.3
* Operating System name/version:  Fedora 30 ; Linux 5.3.6-200.fc30.x86_64
* IPython 7.2.0 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> install spyder3 with dnf install python3-spyder on fedora 30

Please report it upstream with your Linux distro because we don't have control on packages distributed by Fedora.
