### ISSUE TITLE
Variable explorer shows DatetimeIndex with numpy datetime64 format instead of timestamp

### ISSUE THREAD

**Issue by greg500** [spyder-ide/spyder#11129]
## Problem Description

Pandas datetime index appears  in spyder 4 variable explorer with the very unfriendly numpy datetime64 format instead of timestamp.

### What steps reproduce the problem?

`import numpy as np`
`import pandas as pd`

`ds=pd.Series(np.arange(10),index=pd.date_range('2019-01-01',periods=10))`

### What is the expected output? What do you see instead?

Expected output (spyder 3.3.6):

![variable_explorer_spyder3](https://user-images.githubusercontent.com/36016034/71080412-606bbc00-218d-11ea-90ca-7ecf3af48f3c.PNG)

Spyder 4.0.0 output:

![variable_explorer_spyder4](https://user-images.githubusercontent.com/36016034/71080520-99a42c00-218d-11ea-8a93-986a2f569aed.PNG)

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version:  5.9.2
* Operating System name/version: windows 10 x64

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
