### ISSUE TITLE
Can't able to run a locally created .py in remote server's kernel.

### ISSUE THREAD

**Issue by KatheravanArumugam** [spyder-ide/spyder#11134]
Step 1: Using Ipython-kernel Json file, the remote kernel was connected successfully.

Step 2: Write a python script to add two numbers and save it in a local machine.

Step 3: While running from RUN icon or f5 
facing a error "ERROR:root:File `C:\\users\\Desktop\\ab.py'`

Step 4: But in runfile can able to see  [%run "C:\users\\Desktop\ab.py"]
Still facing an error.
Please look on this issue and made it to execute any code in local to run in remote kernel.

**Comment by ccordoba12** [comment]
You need to use Spyder 4 for this to work. What version are you using?

**Comment by KatheravanArumugam** [comment]
Hi Carlos,

I am using Spyder 4. Still iam facing the Error on path.


Thanks,
Katheravan Arumugam

**Comment by ccordoba12** [comment]
Unfortunately, most of our team is on vacations so we'll take a look at this in January. For now, please run your file with `Shift+Enter` to evaluate it like a cell. That should work, but if not, you'll have to wait until then.

@dalthviz, please take a look at this one.

**Comment by KatheravanArumugam** [comment]
Thanks for the reply. Will check on Jan

**Comment by impact27** [comment]
I think that this would only work if you run spyder-kernels. Is that the kernel you are running? `%run "C:\users\Desktop\ab.py"` should only show for a non-spyder kernel

**Comment by ccordoba12** [comment]
@KatheravanArumugam, to run local files in a remote machine you need to start your kernels with the command

    python -m spyder_kernels.console

not with

    ipython kernel

That should fix your problem.

**Comment by KatheravanArumugam** [comment]
Hi carlos,

I tried with 
           python -m spyder_kernels.console
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-45622.json


Even after using this kernel file "%run "C:\Users\kaarumug\Desktop\untitled0.py"
ERROR:root:File `'C:\\Users\\kaarumug\\Desktop\\untitled0.py'` not found." Observing the same.

Please help to solve this.
I have my .py file and kernel json file in my local desktop is this okay?
please correct me if i am wrong.

**Comment by SuperKnightss** [comment]
I have the same problem.

**Comment by impact27** [comment]
`%run "C:\Users\kaarumug\Desktop\untitled0.py` will look for a file in the machine where spyder kernels is running. If you want to run a file from the spyder editor, you should press the green play button. It should add a call to runfile() in the console.
