### ISSUE TITLE
Spyder crashing on launch, python.exe has stopped working

### ISSUE THREAD

**Issue by PKdot123** [spyder-ide/spyder#11130]
Hello,

I have tried the following code to solve this issue:
```
conda uninstall spyder
conda install spyder

conda update --all
conda spyder --reset
conda update qt pyqt
```

reinstalling spyder in a new environment

Reinstalling Anaconda for all users

### What steps reproduce the problem?

1. Launch spyder
2. Wait
3. Get error message " python.exe has stopped working"

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

**Comment by ccordoba12** [comment]
> Get error message " python.exe has stopped working"

I'm very sorry but we can't offer you any help at the moment about this.

Please post a comment on pull request #10553 to receive a notification when we implement the functionality to allow users to report hard crashes (such as yours) to Github.
