### ISSUE TITLE
Commenting lines that include the first one in a file freezes Spyder

### ISSUE THREAD

**Issue by MuratAmca** [spyder-ide/spyder#11148]
### What steps will reproduce the problem?

If I select more than one line together, but last or first line should partially selected, and if I try to comment out with Ctrl+1, Spyder crashes.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
I can't reproduce this. Please post a video (animated gif) with the Licecap program to understand how the crash is generated.

**Comment by OverLordGoldDragon** [comment]
I, too, experience this, but rarely - and in Spyder 3; haven't seen it in 4 yet. Per the unpredictable nature of this bug, making a gif would require monitoring the screen 24/7 (or determining steps to reproduce) - but understandably can't fix what can't be seen break.

**Comment by KimByoungmo** [comment]
same issue when i use spyder4

**Comment by ccordoba12** [comment]
> or determining steps to reproduce

Exactly. We really need a way to reproduce this.

However, this could be generated by #10918 and that's why it's so elusive.

**Comment by KimByoungmo** [comment]
i reproduce this issue
in my case, this happened in the first row in editor
![image](https://user-images.githubusercontent.com/17247035/71539234-bfdf7e00-297c-11ea-8454-a773b2aea066.png)

**Comment by MuratAmca** [comment]
I tried this scenario several times, and get crashed every time.

![Untitled-2](https://user-images.githubusercontent.com/40452678/71574150-8c296300-2af8-11ea-847d-6dce204c8173.png)

**Comment by ccordoba12** [comment]
Thanks @KimByoungmo and @MuratAmca for the reproducible cases. I can generate the error now.

**Comment by MuratAmca** [comment]
Hi Carlos,
I upgraded my Spyder to 4.0.1 but the issue is still there.
Even without selection, just put the cursor on first line of the editor and try to comment out with ctrl+1.
Maybe I should wait next update.

Best

**Comment by ccordoba12** [comment]
Yes, this is going to be fixed in our next version.
