### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by xiasongnihao** [spyder-ide/spyder#11147]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
my spyder cannot show the details of a huge array in the variable explorer, even though it is a two dimensions array with size of (10000,10). However if this array is smaller, I can read every parameters in it. I do not know what is wrong with it, and it always shows that spyder has encountered an internal problem.

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
