### ISSUE TITLE
Pandas variables not visible

### ISSUE THREAD

**Issue by tarunluthra** [spyder-ide/spyder#11143]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

can anyone tell me where all pandas dataframe view has been taken away to? currrently I see very irrelevant pandas dataframe output. I want to actually see the actual values. 
how do I see it?
![image](https://user-images.githubusercontent.com/18536817/71215239-0b52a780-226c-11ea-8c38-f51938b692b6.png)

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
can anyone tell me where all pandas dataframe view has been taken away to? currrently I see very irrelevant pandas dataframe output. I want to actually see the actual values. 
how do I see it?
![image](https://user-images.githubusercontent.com/18536817/71215239-0b52a780-226c-11ea-8c38-f51938b692b6.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This happens because you don't have Pandas installed in same environment where you have Spyder installed.

So to view dataframes as before, you need to make sure to install Pandas alongside Spyder.

**Comment by tarunluthra** [comment]
I had pandas on spyder 3.4 or whatever and anaconda asked me to update it and it forgot all other previous dependices, do I have to install them all over again?

**Comment by ccordoba12** [comment]
If you used a separate conda env to install Spyder 4, then yes, you need to install Pandas, Numpy, Sympy and all other optional dependencies you want to use with Spyder.
