### ISSUE TITLE
keyboard shortcut "ctrl+space" isn't useful

### ISSUE THREAD

**Issue by Coco614** [spyder-ide/spyder#11166]
### What steps will reproduce the problem?

tutorial says that presssng ctrl+space if autocompletions aren't on, but in the step 1c and 1d,  "ctrl+space" doesn't work. No matter how many times I press, autocompletions don't show. 

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
What are steps 1c and 1d?

**Comment by bmw2142** [comment]
kite tutorial python file

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @bmw2142, sorry for the delay, could you check if installing `matplotlib` helps? (seems like you don't have it installed). Also, if that doesn't help, could you set as env variable `SPYDER_DEBUG=3` and run Spyder from a console? (with that maybe we could get more info about what's going on here). Thanks!

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by ccordoba12** [comment]
> could you check if installing matplotlib helps?
> matplotlib >=2.0.0           :  None (NOK)

Well spotted @dalthviz!!
