### ISSUE TITLE
Need bigger icons for Retina display

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1116]
_From [mathieu....@gmail.com](https://code.google.com/u/100688524968566189216/) on 2012-07-12T20:19:28Z_

This is not really an issue, but it would be nice to fix it (I guess it is not so hard, but I may be wrong): with the new Retina display on the the new MacBook pro, the IDE looks ugly (both icons and texts).

I'm using the latest stable version of spider (2.1.10), compiled from source.
The OS is OS X Lion (10.7).

I love this Python IDE (by far the best), and I use it on my Linux, Windows and Mac machines.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1116_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-16T11:25:46Z_

Could you be more specific on the differences you see between your Spyder experiences on Linux, Windows and now on Mac with your MacBook Pro Retina display?
(a screenshot may help)

**Comment by spyder-issues-migrator** [comment]
_From [mathieu....@gmail.com](https://code.google.com/u/100688524968566189216/) on 2012-07-16T12:05:55Z_

Sure. The following links are screenshots taken from the Mac and my Linux machine: https://dl.dropbox.com/u/11013311/spyder_linux.png https://dl.dropbox.com/u/11013311/spyder_mac_retina.png https://dl.dropbox.com/u/11013311/finder_mac.png As you can see, the icons and texts on the Retina display do not look smooth (we do see the pixels on the edges). As for comparison, I've also made a screenshot of another software on the Mac that do not suffer from this problem (only a few actually are in this case, mostly coming form Apple). Those two screenshots from the Mac may look zoomed-in, but they are not.

By the way, both the screens (Linux and Mac) are set at 1920x1200 resolution, though the Retina display may go up to 2880x1800 (so that makes a 220 pixels per inch).

Hope this may help.
Regards.


Le 16 juil. 2012  11:25, spyderlib@googlecode.com a crit :

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-17T00:44:14Z_

I see, this is a very ugly upscaling algorithm indeed!
Have you tried any other Qt-based (or even better PyQt-based) software?

**Comment by spyder-issues-migrator** [comment]
_From [mathieu....@gmail.com](https://code.google.com/u/100688524968566189216/) on 2012-07-17T15:11:41Z_

I've just downloaded Veuz to try another PyQt4 apps, and it is also ugly.


Le 17 juil. 2012  00:44, spyderlib@googlecode.com a crit :

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-07-17T22:17:02Z_

The problem is Retina display means a much higher resolution than before (almost twice than the previous one), so to solve this issue we must provide bigger icons for every action and button we have. So instead of using 16x16 icons, we now have to increase their size to 32x32.

**Comment by spyder-issues-migrator** [comment]
_From [mathieu....@gmail.com](https://code.google.com/u/100688524968566189216/) on 2012-07-17T22:58:56Z_

Icons are one part of the problem, texts is another, more important (at least for me).
But I guess one should start with the easiest and straight forward fix :)


Le 17 juil. 2012  22:17, spyderlib@googlecode.com a crit :

**Comment by spyder-issues-migrator** [comment]
_From [phjon...@gmail.com](https://code.google.com/u/117456410358077289149/) on 2012-11-04T04:46:13Z_

I just installed spyder through macports (it took ages...) and I can confirm that spyder looks ugly, ugly enough to make me change resolution up to 2880x1800 with an utility called SetResX and adjust the size of the fonts being used in the editor, console...

What is really weird is that spyder as distributed through the DMG looks just fine (ok, some icons may not be high resolution but that is not a problem)

As there are some issues with the dmg, I'll make a new post about them.

**Comment by spyder-issues-migrator** [comment]
_From [phjon...@gmail.com](https://code.google.com/u/117456410358077289149/) on 2012-12-18T05:53:02Z_

I found a fix here : https://trac.macports.org/ticket/36410 Solution for running spyder through macports on retina macbook is to edit Info.plist from the macports python.app :

For me it is :
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/Info.plist

Edit it, and add :
    \<key>NSPrincipalClass</key>
    \<string>NSApplication</string>

(The NSHighResolutionCapable can be ignored here, I suppose it would only make sense for an application showing text and images)

Save. Then make a copy of the Python.app and replace Python.app with its copy, or log out and log in, to prevent osx from using the Info.plist in cache.

And run spyder, fonts should be perfectly rendered from now on.

(The DMG spyder executable has a Info.plist with this key already, which explains why it looks just right...)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-12-18T07:54:43Z_

I think there is nothing we can do in our side, sorry. I'm cc'ing eborisch, the spyder macports maintainer.

eborisch, could you fix this in your side, given that now there is a simple patch to do it?

**Cc:** ebori...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-12-18T08:26:32Z_

The patch ( https://trac.macports.org/ticket/36410 ) upstream is to the python package itself, not to spyder. The maintainer of the python package in macports has already stated (same link) that once it actually decided upstream what the correct fixes are, he will put a patch in place.

I would close that as a 'won't fix' and point out that once agreement is reached upstream as to the correct fix, the MacPorts python will be updated, and this will be resolved.

I understand that this seem glib, but just because it makes spyder look pretty isn't a valid reason to change the python package -- it might break something else (lots of things use python.) When upstream says "this is the way to address it" then we'll go with it.

**Comment by spyder-issues-migrator** [comment]
_From [ebori...@gmail.com](https://code.google.com/u/102672023975932251472/) on 2012-12-18T08:28:35Z_

BTW, if installing spyder through MacPorts takes ages (one of the comments above), you likely are not using the default path (/opt/local) or have something else set non-standard. Most of the dependencies are now downloaded as binaries (if settings are left default -- many packages compile in paths, so binaries cannot be distributed for an non-standard path install) from macports, so the install should be rather quick.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-12-18T09:27:22Z_

Thanks for taking the time to give us a thorough explanation. I thought the fix could go directly to the spyder port not to the python one, so you're right to wait until upstream takes a decision.

For what is worth, for our DMG I just compiled Python as a Framework. I didn't tweak Info.plist nor anything else.

I'm also glad to hear that you are providing binary packages for most of your ports. It'll be far more easier to install spyder that way now! :)

Finally, I'm going to leave this open because we need to provide bigger icons so that Spyer looks better on such resolutions.

**Summary:** Need bigger icons for the new MacBook pro Retina display  \<span class="oldvalue"> (was: Looks ugly with the new MacBook pro Retina display) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [phjon...@gmail.com](https://code.google.com/u/117456410358077289149/) on 2012-12-18T10:47:55Z_

As regards the long installation of spyder through macports, I am not sure what options I added for my first installation (rMBP), there was +pil option in py27-spider and probably some verbose flag, but path was left as default, and for sure every package got built from source (including two flavours of gcc I think, and Qt so it took a long time...). It got much faster when I built it on my desktop where it seems it downloaded at least some binary packages.

For the DMG, my guess is that py2app did put by default that key that is much appreciated by us spoiled retina macbook users...

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-28T14:24:45Z_

**Status:** HelpNeeded  
  **Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T06:01:04Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [mich...@strukt.org](https://code.google.com/u/110636623457663298042/) on 2014-03-10T06:03:41Z_

I would also add I'm using spyder on one of the new dell precision M3800 laptops on windows 8 with a similar resolution and am facing the same issues. Is there a configuration equivalent I can set to upscale the images and set the fonts a bit larger overall?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-10T10:39:04Z_

Nop, there is no option to adjust this. Unfortunately we would need to provide a bigger (64x64?) version of each of our icons and we don't have the sources of all of them.

**Summary:** Need bigger icons for Retina display  \<span class="oldvalue"> (was: Need bigger icons for the new MacBook pro Retina display) \</span>  
  **Cc:** -ebori...@gmail.com  
  **Labels:** -OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [mich...@strukt.org](https://code.google.com/u/110636623457663298042/) on 2014-03-11T01:55:15Z_

Where can I get the resources we have available and how would you then apply the upscaled/larger icons to the app? More than happy to give it a try.

**Comment by spyder-issues-migrator** [comment]
_From [m.bosch....@gmail.com](https://code.google.com/u/111857247407397434141/) on 2014-03-17T01:37:22Z_

Maybe an option is to change the icon theme as proposed in issue #950 https://code.google.com/p/spyderlib/issues/detail?id=950

**Comment by SylvainCorlay** [comment]
Closing to the benefit of #2210.
