### ISSUE TITLE
Visualize what line of code the editor is running 

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#11177]
So this is just an idea, but when I am running lots of code with 'run current selection' it would be cool if the  lines in the IPython consol were a different color after they were run.

So picture entering:

func1(args)
func2(args)
.
.
.
funN(args)

and you select all functions and press run current selection.

What is func2-funcN were all greyed out while func1 was running, then func2 gets color when its running, etc, etc. That way, we know what lines have already run and where our code is in the process!

Just an idea, it beats a bunch of print functions/waiting and hoping.

**Comment by impact27** [comment]
I think it would slow down the code significantly. I had the idea to have a plug-in where you can push a button and it would show you where the code is. Updating continuously would take too much time in my opinion.

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder/pull/10461

**Comment by Travis-Barton** [comment]
>  I had the idea to have a plug-in where you can push a button and it would show you where the code is.

I think thats a wonderful idea! That would very be a quality of life feature that I would use regularly, and would fit my need perfectly!
@impact27
