### ISSUE TITLE
Snap windows in Windows

### ISSUE THREAD

**Issue by CrispyCalzone** [spyder-ide/spyder#11195]
### What steps will reproduce the problem?

For reproduction, open 4 instances of Spider, snap window in each corner, the windows keep overlapping

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.5 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
Please post a screenshot about this to better understand what you mean.

**Comment by CrispyCalzone** [comment]
![Capture](https://user-images.githubusercontent.com/58981874/71558137-09e56400-2a50-11ea-96a9-a23e7467c110.PNG)

**Comment by CrispyCalzone** [comment]
![Capture3](https://user-images.githubusercontent.com/58981874/71558377-fd163f80-2a52-11ea-8a01-c4ae17e3fccc.PNG)
![Capture2](https://user-images.githubusercontent.com/58981874/71558378-fd163f80-2a52-11ea-8b83-1babec1f36cd.PNG)

Basically when the project explorer is opened the windows don't snap into place correctly anymore. I don't know if it depends on resolution.

changing the resolution from 1920x1080 to 1680x1050 made things way worse

**Comment by ccordoba12** [comment]
@dalthviz, can you reproduce this one? It looks like a Windows only issue.

**Comment by dalthviz** [comment]
@ccordoba12 I'm able to reproduce this. I think that maybe is related to the minimum width of the widgets. For example the default layout of Spyder vs only having the Editor:

![split](https://user-images.githubusercontent.com/16781833/71691629-e4b96400-2d75-11ea-8efc-932bf5fcbe94.gif)

**Comment by goanpeca** [comment]
>to the minimum width of the widgets. 

Could you manually set the minimum width of some of those widgets to check?

If that is the case, we should reconsider those values or not setting them at all?

**Comment by dalthviz** [comment]
After testing for some time it seems like the issue is caused by the way Windows manages the windows snap. Seems like at some point you can rearrange the proportions that each window takes (by dragging the point where the windows meet) and after that I can use the shortcut to snap (Windows Key + Arrow Keys) without Spyder taking an extra space. Maybe this could be of some help for you @CrispyCalzone ?:

![snap2](https://user-images.githubusercontent.com/16781833/71700287-8d28f180-2d91-11ea-8675-70d5e231d0f0.gif)

![snap](https://user-images.githubusercontent.com/16781833/71700889-5e604a80-2d94-11ea-91cf-a3bf25a84c99.gif)

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by CrispyCalzone** [comment]
Thnaks guys it works

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________
