### ISSUE TITLE
visualization of multiply  indented code

### ISSUE THREAD

**Issue by adampara** [spyder-ide/spyder#11207]
It is not an issue, but rather a suggestion. I have large piece of code with several indentation levels..It is quite tedious and error prone to trace the indentation, while the consequences of mistakes can be quite serious.  I think it would be very convenient to have an option in the editor to highlight the regions with different indentation  with different colors.. It can be either automatic (based on the indentation) or manual (by user specified levels of cells, for example)

**Comment by ccordoba12** [comment]
This was sort of fixed in Spyder 4 because in that version we added indent guides to the editor.

You can activate them by going to the menu

    Source > Indent guides

> I think it would be very convenient to have an option in the editor to highlight the regions with different indentation with different colors

Sorry, we don't have plans to implement something like that.
