### ISSUE TITLE
'Python has stopped working' on Spyder launch, 'No symbol file loaded for Qt5Core.dll'

### ISSUE THREAD

**Issue by OD1995** [spyder-ide/spyder#11213]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
'Python has stopped working' message appears when attempting to launch Spyder

### What steps reproduce the problem?

1. Launch Spyder 

### What is the expected output? What do you see instead?
A normal working Spyder. Spyder does open as normal but immediately the 'Spyder is not working' message appears.

### Paste Traceback/Error Below (if applicable)

After selecting the debug option when the 'Python is not working' window appears. This is the outcome:
<img width="407" alt="spyd4 error" src="https://user-images.githubusercontent.com/34351331/71669962-5689b180-2d66-11ea-91fe-163220904892.PNG">

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.1
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
> Qt version: 5.6.2
PyQt version: 5.6.0

You're using very old versions of Qt/PyQt. Please update and try again.

**Comment by OD1995** [comment]
Updating qt and pyqt leads to the same 'Python is not working' message and this error when debugging:
<img width="377" alt="spyd4 error 2" src="https://user-images.githubusercontent.com/34351331/71679988-ce64d580-2d80-11ea-93ce-fa13107f74f7.PNG">

**Comment by ccordoba12** [comment]
I think you have another Qt5 version installed in your system (due to another program doing that). Try to find it by searching for `Qt5Core.dll` and removing those not installed by Anaconda.

That's the only advice I jave for you. If the problem persists, please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/
