### ISSUE TITLE
Controlling two or more python editors independently

### ISSUE THREAD

**Issue by irnmn** [spyder-ide/spyder#11214]
## Problem Description

Hi,

I would like to know how can we control two or more python editors independently. As you can see in the image below, I vertically divided editor windows vertically but whatever I do for the right-hand side mirrors to the lefthand side window!

![image](https://user-images.githubusercontent.com/13536632/71683957-30a5e200-2d51-11ea-8c19-b1af5c1bc785.png)

What I need to have is I want to use left-hand side window for reference files and keep them fixed there and not to show them in the righthand side window.

is that possible?

Thx!

**Comment by ccordoba12** [comment]
> What I need to have is I want to use left-hand side window for reference files and keep them fixed there and not to show them in the righthand side window.

Sorry but this is not possible at the moment. The only option is for you to open two Spyder instances at the same time.

For that, please go to

    Tools > Preferences > General > Advanced settings

and deactivate the option called `Use a single instance`.

**Comment by irnmn** [comment]
it does not make any difference! You mean open two different spyder instances and use them side by side? That would be great if you can add this. Actually notepad++ have this property. Controlling the windows left and right hand side independently!

**Comment by ccordoba12** [comment]
That can't be done in the same instance, nor it's plan to be added, sorry.

You need to start two Spyder instances, as I said.

**Comment by irnmn** [comment]
ok that's pitty! then. Thanks. What is the `Use a single instance.` anyway ? If I active it does it mean every spyter window that I opened uses the one common kernel?

**Comment by ccordoba12** [comment]
No, it means you can only open a single Spyder window.

**Comment by irnmn** [comment]
ok. Thanks cordoba!

**Comment by kiranbeethoju** [comment]
In spyder 5 it is available, thanks Dear lovely developers..
