### ISSUE TITLE
Spyder crashes during startup since upgrade to version 4

### ISSUE THREAD

**Issue by Kinzowa** [spyder-ide/spyder#11215]
Hello,

Since update to version 4 with `pip` my spyder IDE is crashing at start up. I don't understand what's happen because I did the update with `pip install --upgrade spyder` and saw ERROR due to requirement incompatibility for others packages:

```
Successfully built python-language-server diff-match-patch watchdog intervaltree python-jsonrpc-server ujson pathtools
ERROR: spyder-kernels 1.8.1 has requirement pyzmq>=17, but you'll have pyzmq 16.0.2 which is incompatible.
ERROR: jupyter-client 5.3.4 has requirement jupyter-core>=4.6.0, but you'll have jupyter-core 4.4.0 which is incompatible.
ERROR: helpdev 0.6.10 has requirement psutil>=5.6, but you'll have psutil 5.4.2 which is incompatible.
ERROR: autopep8 1.4.4 has requirement pycodestyle>=2.4.0, but you'll have pycodestyle 2.3.1 which is incompatible.
ERROR: flake8 3.7.9 has requirement pycodestyle<2.6.0,>=2.5.0, but you'll have pycodestyle 2.3.1 which is incompatible.
ERROR: flake8 3.7.9 has requirement pyflakes<2.2.0,>=2.1.0, but you'll have pyflakes 1.6.0 which is incompatible.
Installing collected packages: parso, jedi, jupyter-client, ipykernel, spyder-kernels, qtconsole, more-itertools, zipp, importlib-metadata, helpdev, qdarkstyle, pluggy, ujson, python-jsonrpc-server, autopep8, entrypoints, flake8, snowballstemmer, pydocstyle, yapf, python-language-server, diff-match-patch, pyxdg, argh, pathtools, watchdog, sortedcontainers, intervaltree, atomicwrites, spyder
  Found existing installation: parso 0.1.1
    Uninstalling parso-0.1.1:
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: 'normalizer.cpython-36.pyc'
Consider using the `--user` option or check the permissions.
```
As recommanded I tried with the ` --user` and the update completed but still with the ERROR incompatibility for the other packages. I decided to update all these packages with `pip install --upgrade packageName --user` and everything went fine, but unfortunately Spyder crashes at startup :-(

I noticed the only spyder binary on my Ubuntu was `spyder3` while I see the new Spyder 4 popup during startup. This is the error returned during startup:

```
abcdefg@pseudo-lenovo-ideapad-710s-13isk:~$ spyder3
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "/home/aaz/.local/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/aaz/.local/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "/home/aaz/.local/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1010, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "/home/aaz/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 52, in <module>
    from spyder.plugins.ipythonconsole.widgets import ClientWidget
  File "/home/aaz/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/__init__.py", line 16, in <module>
    from .debugging import DebuggingWidget
  File "/home/aaz/.local/lib/python3.6/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 22, in <module>
    from IPython.core.inputtransformer2 import TransformerManager
ModuleNotFoundError: No module named 'IPython.core.inputtransformer2'
```

So I decided to install Spyder with `sudo apt install spyder` and now I have both `spyder` and `spyder3`. The new binary `spyder` launch without problem but it is still version 3, and when I follow the upgrade instruction and run `pip install --pre -U spyder` it returns no error but it start version 3 again. 

So how can I manage to upgrade to version 4? 

Thank you,

**Comment by ccordoba12** [comment]
You have a serious dependencies problem and I don't know how you ended up in that state. Please remove this directory:

    /home/aaz/.local/lib/python3.6/

and use a virtualenv/pyenv to install Spyder instead.

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ccordoba12** [comment]
> So I decided to install Spyder with sudo apt install spyder

Also remove that package too.

**Comment by Kinzowa** [comment]
Thank you for your help Cordoba I appreciate. `spyder3` starts without error after removing the folder above, and I deleted the `spyder` apt package. But from here, wht is the best way to upgrade to version 4? Shall I follow the recommandation and run `pip install --pre -U spyder`?

**Comment by Kinzowa** [comment]
Hello, just to let you know that Spyder 4 is working great now. I created a
virtual environnment and installed in it with `pip3` instead of `pip`.
Maybe it was the issue

Le jeu. 2 janv. 2020 à 19:56, Carlos Cordoba <notifications@github.com> a
écrit :

**Comment by r3klaw** [comment]
I had the same issue, I solved mine by uninstalling pylint and reinstalling it.
