### ISSUE TITLE
set_options_opengl is called too late

### ISSUE THREAD

**Issue by hmaarrfk** [spyder-ide/spyder#11227]
https://github.com/spyder-ide/spyder/blob/26504d5ed48fdaa28b76cf72962859d4fdbce0cf/spyder/app/mainwindow.py#L3651

It needs to get called before the application is created. This means, before the splash screen.

The whole block that gets the options needs to be imported sooner, but importing
```
spyder.apps.cli_options
```
might be expensive to load

In either case, without moving it forward, Qt warns the user

Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.

**Comment by ccordoba12** [comment]
Thanks for reporting, I noticed this too. It's something that changed between Qt 5.9 and 5.12.

**Comment by hmaarrfk** [comment]
got it.

**Comment by goanpeca** [comment]
@ccordoba12 are you fixing this? otherwise to reassign :-)

**Comment by ccordoba12** [comment]
I have some initial code for this. I'll push it tomorrow so someone else can help me to finish it.
