### ISSUE TITLE
Spyder 4.0.1 not yet on conda?

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#11220]
Hi Spyder develpers,

Spyder 4.0.1 has been released on GitHub, but it still doesn't show up on Anaconda Cloud (https://anaconda.org/anaconda/spyder).

Do we simply keep waiting? Or shall someone manually upload it to Anaconda?

Thanks!

**Comment by Dan-Patterson** [comment]
Patience... as indicated in a closed thread [https://github.com/spyder-ide/spyder/issues/11218](url)

**Comment by ccordoba12** [comment]
That's right. Please wait until new packages are available.

We really don't have control over when the Anaconda team uploads new packages, but they don't usually take more than a week to do it.

**Comment by jsh9** [comment]
Thank you both @ccordoba12 @Dan-Patterson  :)
