### ISSUE TITLE
Just opened a file

### ISSUE THREAD

**Issue by aviallon** [spyder-ide/spyder#11224]
### What steps will reproduce the problem?

I opened a python file (mostly empty), which I just closed before.
I have several programs running in the background, but I have 16 GB of RAM left.

### Consequences

This dialog popped up. I do not know if it really crashed.

### Traceback
```python-traceback
  File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2819, in start_open_files_server
OSError: [Errno 9] Mauvais descripteur de fichier
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.8.1
* Qt version: 5.14.0
* PyQt5 version: 5.14.0
* Operating System: Linux 5.4.7-arch1-1

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.2.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.7 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.18.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.11.1 (OK)
matplotlib >=2.0.0:  3.1.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
We don't support yet PyQt 5.14, as it's clearly stipulated in our requirements.

Please install and use Anaconda instead.

**Comment by ccordoba12** [comment]
For more support, please contact your distribution
