### ISSUE TITLE
Spyder 4.0.0 iPython Console Not Working With Python 3.8

### ISSUE THREAD

**Issue by tusharkhoche** [spyder-ide/spyder#11231]
I installed Python 3.8 & Spyder 4.0.0 on Windows 10. I changed Interpreter from default to 3.8. After that iPython shows this error

> Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.8.0 and < 2.0.0). Without this module is not possible for Spyder to create a console for you.

> You can install it by running in a system terminal:
conda install spyder‑kernels or pip install spyder‑kernels

![Spyder4-1](https://user-images.githubusercontent.com/19679029/71797173-ed11e780-3072-11ea-8253-a0372e2a88c3.png)
![Spyder4-2](https://user-images.githubusercontent.com/19679029/71797174-ed11e780-3072-11ea-9610-5c7ae24d82b5.png)

**Comment by ccordoba12** [comment]
Well, the message is pretty clear. Did you install spyder-kernels in your Python 3.8 installation?

**Comment by tusharkhoche** [comment]
Yes already installed

![image](https://user-images.githubusercontent.com/19679029/71803614-4421b780-3087-11ea-9fc8-daa5a170ed17.png)

**Comment by tusharkhoche** [comment]
**Had to install Spyder 4.0.0 in another environment in Anaconda**
![image](https://user-images.githubusercontent.com/19679029/71806142-0a07e400-308e-11ea-8faf-a6767e6728eb.png)

**Installed Spyder-Kernels in this environment also**
![image](https://user-images.githubusercontent.com/19679029/71806169-1db34a80-308e-11ea-832c-004ceda6ca9c.png)

**Comment by ccordoba12** [comment]
You're doing things incorrectly. Please remove

    C:\Program Files (x86)\Python38-32

then run instead in the Anaconda Prompt

    conda create -n py38 python=3.8 spyder-kernels

and finally select the interpreter of your `py38` in

    Python Interpreter > Use the following interpreter

**Comment by ccordoba12** [comment]
For more doubts, please read our guide about this:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

**Comment by NitinSaini18** [comment]
hey, the same issue I am facing did you find any solution?

**Comment by OmkarPatkar** [comment]
> I installed Python 3.8 & Spyder 4.0.0 on Windows 10. I changed Interpreter from default to 3.8. After that iPython shows this error
> 
> > Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.8.0 and < 2.0.0). Without this module is not possible for Spyder to create a console for you.
> 
> > You can install it by running in a system terminal:
> > conda install spyder‑kernels or pip install spyder‑kernels
> 
> ![Spyder4-1](https://user-images.githubusercontent.com/19679029/71797173-ed11e780-3072-11ea-8253-a0372e2a88c3.png)
> ![Spyder4-2](https://user-images.githubusercontent.com/19679029/71797174-ed11e780-3072-11ea-9610-5c7ae24d82b5.png)

**************************************************************************************************************************************************

I solved it just by reseting spyder ide. Tap on tools inside spyder then tap on reset spyder to factory defaults.

**Comment by Pranjal10052000** [comment]
> > I installed Python 3.8 & Spyder 4.0.0 on Windows 10. I changed Interpreter from default to 3.8. After that iPython shows this error
> > > Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.8.0 and < 2.0.0). Without this module is not possible for Spyder to create a console for you.
> > 
> > 
> > > You can install it by running in a system terminal:
> > > conda install spyder‑kernels or pip install spyder‑kernels
> > 
> > 
> > ![Spyder4-1](https://user-images.githubusercontent.com/19679029/71797173-ed11e780-3072-11ea-8253-a0372e2a88c3.png)
> > ![Spyder4-2](https://user-images.githubusercontent.com/19679029/71797174-ed11e780-3072-11ea-9610-5c7ae24d82b5.png)
> 
> I solved it just by reseting spyder ide. Tap on tools inside spyder then tap on reset spyder to factory defaults.

worked for me... Thank you!!
