### ISSUE TITLE
Graphs reaches out of subplot

### ISSUE THREAD

**Issue by BajerJonas** [spyder-ide/spyder#11234]
### What steps will reproduce the problem?

When ever I draw 2 subplots of different places in the graph. It will draw outside of both at the graph. This did not happen in Spyder 3.

Heres an example:

"""
import numpy as np
import matplotlib.pyplot as plt

x2 = np.linspace(-20,120)
y3 = (x2 - 30)/2
y4 = (x2 - 32)*(5/9)

plt.subplot(1,2,1)
plt.plot(x2,y3, "b",x2,y4, "g")
plt.xlabel("F", color="gray")
plt.ylabel("C", color="gray")
plt.axis([-20,20,-30,0])
plt.legend(["$C=(F-30)/2$","$C=(F-32)*5/9$"], loc=2)

plt.subplot(122)
plt.plot(x2,y3, "b",x2,y4, "g")
plt.xlabel("F", color="gray")
plt.ylabel("C", color="gray")
plt.axis([90,120,20,50])
plt.legend(["$C=(F-30)/2$","$C=(F-32)*5/9$"], loc=4)
"""

## Versions

* Spyder version: 4.0.0 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.12 (OK)
IPython >=4.0                :  7.6.1 (OK)
matplotlib >=2.0.0           :  3.1.0 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.2.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by ccordoba12** [comment]
I don't understand what you mean. Please post a screenshot about this.

**Comment by bcolsen** [comment]
I get this:

![image](https://user-images.githubusercontent.com/10513354/71937312-48260600-3169-11ea-93be-c472eaf7e751.png)

If the lines aren't being masked by the plot edges than that would be a matplotlib error. Can you reproduce this a the qtconsole?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
