### ISSUE TITLE
Problem occurs when loading sympy

### ISSUE THREAD

**Issue by linlin98126** [spyder-ide/spyder#11249]
### What steps will reproduce the problem?

It seems that sympy malfucntions in spyder4.0:
input this codes in the Ipython console in spyder:

---------------------------------------
from sympy import symbols

x = symbols('x')

x
---------------------------------------

then the output seems to be a block, or in other words, unreadable code. Why would this happen?

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5 (OK)
```

**Comment by ccordoba12** [comment]
Please post a screenshot because I don't understand what you mean.

**Comment by linlin98126** [comment]
Please look at the  Out[4]
| |
Yijiang Lin
|
|
linlin98126@163.com
|
签名由网易邮箱大师定制
On 1/7/2020 22:37，Carlos Cordoba<notifications@github.com> wrote：

Please post a screenshot because I don't understand what you mean.

**Comment by ccordoba12** [comment]
You can't send attachments over email. You need to upload it directly here.

**Comment by ccordoba12** [comment]
And by screenshot I mean an image of what you're seeing.

**Comment by linlin98126** [comment]
![Issue](https://user-images.githubusercontent.com/30435805/71903517-395a4600-319f-11ea-9b59-7aeab895ae51.png)

**Comment by ccordoba12** [comment]
Do you have Miktex installed?

**Comment by linlin98126** [comment]
No, but I installed textlive.

**Comment by ccordoba12** [comment]
And is `pdflatex` in your PATH?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
