### ISSUE TITLE
How to save entire project with variables ?

### ISSUE THREAD

**Issue by irnmn** [spyder-ide/spyder#11243]
Hi,

I want to know is there a option when we want to save entire project with all variables so when we re-open the project all of the variables still there. Like R studio.

I've found this post
https://github.com/spyder-ide/spyder/issues/3398

but seems there is no further info.

Thx

**Comment by ccordoba12** [comment]
Duplicate of #3398

**Comment by ccordoba12** [comment]
This is planned for a future version (Spyder 5, to be released later this year, or maybe Spyder 6).
