### ISSUE TITLE
Spyder crashes at startup after setting custom high DPI scaling at less than 1.0

### ISSUE THREAD

**Issue by Boris-Molina** [spyder-ide/spyder#11240]
### What steps reproduce the problem?

1. Spyder 4.0 crashes at startup after setting custom high DPI scaling at value less than 1.0
2. In Tools>Preferences>General>Interface set "Custom High DPI Scaling" at 0.8
3. Confirmation window "Spyder needs to restart to change the following setting" fails to list the new setting to be changed: shows only a blank bullet as opposed to when setting automatic high DPI scaling, which correctly shows the settings being changed.
4. When I hit yes to restart Spyder for the new setting to take effect, there is a floating point violation cum core dump.

### What is the expected output? What do you see instead?
When performing auto DPI scaling the resulting font size is way too small. Was playing around: scaling factors greater than one increase the default font size, less than one should make them smaller. Was looking for a scaling factor to better use the screen without it becoming illegible, used to do this in spyder 3.*

### ERROR MESSAGE in terminal:

(quant) cygnus_x1@BM-SurfaceBook-2:~$ spyder
[1:1:0100/000000.837530:ERROR:broker_posix.cc(41)] Invalid node channel message
[1:1:0100/000000.837621:ERROR:broker_posix.cc(41)] Invalid node channel message
Floating point exception (core dumped)

I am able to restart spyder after resetting (spyder --reset).

## Versions
* Spyder version: Spyder 4.0.0 
* Python version: Python 3.7.5 64-bit
* Qt version: Qt 5.9.6 
* PyQt version:  PyQt5 5.9.2
* Operating System name/version:  Linux 5.1.15-surface-linux-surface Ubuntu 18.04 LTS running on a Windows SurfaceBook 2 using the Linux jakeday kernel (https://github.com/jakeday/linux-surface)

### Dependencies
```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.10.2 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

**Comment by Boris-Molina** [comment]
Reproduced the same error on another Ubuntu laptop running Linux 5.0.0-37-generic, so its not a problem with the jakeday kernel.

**Comment by ccordoba12** [comment]
I can confirm this problem. It seems it's not possible to set a factor less than 1.0 by design.

@dalthviz, please take care of this one by adding a validation to the scaling factor so when users try to set a factor lesser than 1.0, we show a message saying that that's not possible and setting a value of 1.0 on it.

**Comment by ccordoba12** [comment]
@Boris-Molina, you need to run

    spyder --reset

in a terminal to reset the previous setting and have a working Spyder again.

**Comment by Boris-Molina** [comment]
Thanks... 

An additional comment.  When I set the DPI scaling to automatic, in windows Spyder sizes the fonts (smaller) I manage to get a lot of use from the my hi-res monitor.  However, in Ubuntu 18.04 the dual screen management is weaker: it merges both monitors, which leads Spyder to use an auto scaling factor which sets the fonts too small to read.  

I was trying to fix this manually: if I set the scaling factor at 1.0 or larger, the font/rendering increases in size. So, I figured that to achieve smaller font size the scaling factor needs to be less than 1.0 (but larger than the one used to shrink the font down to illegibility in the auto scaling option).

This is Spyder in Windows 10 with autoscaling on a high-res monitor:
![Spyder_Windows_AutoScaling](https://user-images.githubusercontent.com/42842838/72007783-7581bb00-3220-11ea-9f21-ddc8551d84f0.PNG)

**Comment by Boris-Molina** [comment]
In Ubuntu, on my second terminal this is how Spyder looks with manual DPI scaling at 1.0:

![Spyder_Ubuntu_Scaling_1 0](https://user-images.githubusercontent.com/42842838/72008848-b11d8480-3222-11ea-953e-c910ad42a1e4.png)


When I turn on AutoScaling, this is what I see:


![Spyder_Ubuntu_AutoScaling](https://user-images.githubusercontent.com/42842838/72008876-be3a7380-3222-11ea-9db1-43da81a16546.png)

How do I set an intermediate font/window scaling?

Thanks!!

**Comment by dalthviz** [comment]
@Boris-Molina inside Spyder you can try to use the zoom in the Editor (`Ctrl++` and `Ctrl+-`) and the fonts size config (`Appearance > Fonts > Plain Text/Rich Text`), although probably it could not be enough. Also, maybe the following link could be of some help (regarding fractional scaling in Ubuntu 18.04): https://askubuntu.com/questions/1029436/enable-fractional-scaling-for-ubuntu-18-04
