### ISSUE TITLE
spyder launch error:  ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

### ISSUE THREAD

**Issue by yfang831** [spyder-ide/spyder#11252]
Hi,

I have a windows 10 PC, using conda to manage virtual environment.  I am running python 3.6.3 and spyder 4.0.0.  

Normally, I would open a anaconda command prompt, then activate the virtual environment, then type in spyder to launch spyder.  

## Problem Description
It all worked fine until today.  Last night, they applied some windows patch to my PC.  So this morning when I type in spyder from the command prompt, the following error message showed up:

(playground3) C:\Windows>spyder
[1332:1544:0107/101324.708:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

After that, spyder can still run and it seemed fine.  

### What steps reproduce the problem?
This happens every time when I ran spyder.  I also uninstalled/reinstalled spyder, but the error message remain the same.

Do you have recommendation how to resolve this error?

Thanks.

**Comment by ccordoba12** [comment]
> After that, spyder can still run and it seemed fine.

That's good.

> Do you have recommendation how to resolve this error?

Sorry I haven't seen this error before and I don't know what could be causing it (a quick Google search doesn't reveal anything).

So I'm going to close this one, but you're welcome to keep posting here if you something else about it.

**Comment by yfang831** [comment]
I don’t know how to resolve this, because the error is still occurring.  But it doesn’t seem to impact the operation of Spyder.

**Comment by meiji477** [comment]
Hi

I have installed the latest 64 bit anaconda navigator version on my laptop with windows 10 pro as a operating system. Whenever I launch spyder from the anaconda navigator following message as mentioned by yfang831 shows up 

[740:6504:0514/000841.771:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8

Even after that, spyder can still run and it seemed fine. This happens every time when I launch the spyder. I have also reinstall anaconda navigator multiple times but the issue persists.

Please help if any one has any recommendation to resolve this error

Thanks.
