### ISSUE TITLE
Shortcut keys conflict with Gnome Unity

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1125]
_From [anatoliy...@gmail.com](https://code.google.com/u/101136359641652000647/) on 2012-07-26T10:17:01Z_

Spyder Version:  2.1.10
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux
Ubuntu Precise 

What steps will reproduce the problem?

1. The default shortcut key for duplicate line (I think, Ctrl-Alt-down) conflicts with Gnome Unity, and nothing happens.  Ditto for its cousin Ctrl-Alt-up.
2. The shortcut key for last edit location(Shift-Ctrl-Alt-left) works only if I press the 'left' on my numeric pad, not the arrow on the main part of the keyboard
3.There are probably other issues with shortcut keys.  Maybe let's aggregate them all here.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1125_

**Comment by spyder-issues-migrator** [comment]
_From [rene.sen...@gmail.com](https://code.google.com/u/107758418560424156423/) on 2012-08-29T23:18:21Z_

Also the shortcut key for line comment doesn't work (CTRL-3) ... It just prints out the number. 

Same for uncomment and block-uncomment. The only thing that works regarding comments is a block-comment (CTRL-4).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:22:43Z_

**Summary:** Shortcut keys conflict with Gnome Unity  \<span class="oldvalue"> (was: Shortcut keys don't all work properly) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:23:02Z_

**Labels:** Cat-Settings MS-v2.4

**Comment by ccordoba12** [comment]
We can't really do anything about it. You need to reconfigure your shortcuts (either in Unity or Spyder) to make things work :-)
