### ISSUE TITLE
Parentheses Pair Highlight Color

### ISSUE THREAD

**Issue by rwijtvliet** [spyder-ide/spyder#11264]
## Problem Description
The gui highlights parentheses-pairs, which is very useful. However, in a dark theme, this becomes unreadable, as both the highlighting color as well as the font color are white (or very light):
![image](https://user-images.githubusercontent.com/4106013/71974423-bcb47f80-3211-11ea-9171-6330814cacf2.png)
(What are these? Parentheses? Brackets? Braces?)

### What steps reproduce the problem?

1. Open Spyder
2. Select dark theme; restart
3. Type "print(hello)"
4. Put cursor at end of line, after the closing parenthesis.

### What is the expected output? What do you see instead?
Expected: readable parentheses.
Result instead: unreadable parentheses.

## Versions
* Spyder version: 4.0.1
* Python version: 3.7.5 64-bit 
* Qt 5.9.6 
* PyQt5 5.9.2 
* Linux 5.3.0-7625-generic

**Comment by rwijtvliet** [comment]
Ok,

**Comment by e2t** [comment]
Same problem. Completely unreadable default design.
