### ISSUE TITLE
IPython Console is not loading

### ISSUE THREAD

**Issue by shankarThiyagaraajan** [spyder-ide/spyder#11275]
### What steps will reproduce the problem?

IPython console is loading "Connecting to Kernel..." always. I'm Using Python3 and Spyder 3.

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  5.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt, run there

    python -m spyder_kernels.console

and report back any errors that appear afterwards.

**Comment by shankarThiyagaraajan** [comment]
## FYI,
![image](https://user-images.githubusercontent.com/10199091/72154516-e074f280-33d6-11ea-83fe-23e9716a8ebf.png)

**Comment by ccordoba12** [comment]
Everything seems to be working fine. Then please update to Spyder 4.0.1 with these commands in the Anaconda Prompt

    conda update anaconda
    conda install spyder=4.0.1

and try again.

**Comment by shankarThiyagaraajan** [comment]
## After the Update of Conda and Spyder.

![image](https://user-images.githubusercontent.com/10199091/72237534-d2a2b580-3600-11ea-95bc-3ffafcb5bacc.png)

**Comment by ccordoba12** [comment]
You can safely ignore that. Is the console working as expected or not?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
