### ISSUE TITLE
No output appears in the console if using datatable to process data. 

### ISSUE THREAD

**Issue by Fred-Wu** [spyder-ide/spyder#11276]
I am using spyder 4.01 at the moment. I don't know whether this issue is due to spyder or datatable package. I asked here because it works fine when using VSCode and RStudio by default. 

The issue is when I create a data frame with datatable package, and run it in the console, the output does not appear unless I run `print()` after it. It happens to every function applying to that data. But the data created with pandas has no such an issue. 

I do apologise if this is nothing to do with spyder. 

```
import datatable as dt
import pandas as pd
import numpy as np
df1 = dt.Frame(np.random.randn(1000000))
df2 = pd.DataFrame(np.random.randn(1000000))
```
```
In [11]: df1
Out[11]: <Frame [1000000 rows x 1 col]>

In [12]: df2
Out[12]: 
               0
0      -0.951374
1       1.527134
2       0.218090
3      -1.236205
4      -0.077038
         ...
999995 -0.750939
999996  0.913532
999997  0.770788
999998 -0.504217
999999 -1.261031

In [18]: df1.sum()
Out[18]: <Frame [1 row x 1 col]>

In [19]: df2.sum()
Out[19]: 
0   -1050.63101
dtype: float64

In [24]: df1.head()
Out[24]: <Frame [10 rows x 1 col]>

In [25]: df2.head()
Out[25]: 
          0
0 -0.951374
1  1.527134
2  0.218090
3 -1.236205
4 -0.077038
```

**Comment by ccordoba12** [comment]
The `datatable` package is incorrectly detecting that the our IPyhon console is a Jupyter notebook and that's why it's not printing its contents as expected.

Please re-open this issue here:

https://github.com/h2oai/datatable

and ping me (using `@ccordoba12` in a comment), so we can help the maintainers of that package to fix this problem.
