### ISSUE TITLE
Run cells through a function called runcell instead of pasting their contents directly to the console.

### ISSUE THREAD

**Issue by Liso77** [spyder-ide/spyder#11284]
This is special issue because title is copied from changelog.md! 

Why is this "feature" introduced? It rather spoils history by senseless lines.

Could it be at least optionable?

**Comment by ccordoba12** [comment]
To turn off this behavior you need to go to the menu

    Tools > Preferences > Editor > Run Code

and activate the option called

    Copy full cell contents to the console when running code cells

**Comment by Liso77** [comment]
Cool! Thanks! :)
