### ISSUE TITLE
how to turn off the Dialog box off 'no documentation available'

### ISSUE THREAD

**Issue by Ao-Lee** [spyder-ide/spyder#11281]
If I put the mouth on every variable, it shows a dialog that 'no documentation available'. I would like to as is there a way to turn it off or make it disappear? thanks

**Comment by Ao-Lee** [comment]
btw, in the preferance->help-> auto connections, I already turned off all the options, but it doesn't help

**Comment by ccordoba12** [comment]
Sorry, that's not possible.

**Comment by colt18** [comment]
Tools --> Preferences --> Completing and linting --> Introspection --> Enable hover hints

Untincking Enable hover hints worked for me.

**Comment by Ao-Lee** [comment]
> Tools --> Preferences --> Completing and linting --> Introspection --> Enable hover hints
> 
> Untincking Enable hover hints worked for me. It was so frustrating hints appearing at desktop prior to switching tasks.

Great help !!! many thanks !!!

**Comment by ccordoba12** [comment]
> Untincking Enable hover hints worked for me. It was so frustrating hints appearing at desktop prior to switching tasks.

This was fixed in 4.1.3. Please update.
