### ISSUE TITLE
PROJ_LIB environmental variable not set within Spyder

### ISSUE THREAD

**Issue by clive3** [spyder-ide/spyder#11289]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have a python environment called "coast" that installs the osgeo package.

Within my code I use various osgeo.gdal functions such as:

"image_dataset_gdal = gdal.Open(input_file, gdal.GA_ReadOnly)
projection            = image_dataset_gdal.GetProjectionRef()"

The GetProjectionRef() require the environmental variable PROJ_LIB to be set to the path of the folder containing the proj.db file.

For me this is "...\Anaconda3\envs\coast\Library\share\proj"

I can obviously set this every new Spyder session or simply start Spyder from an Anaconda command prompt. However, I am trying to educate myself so I would like to know how I can add this environmental variable to where ever the IPython gets configured. I have had a good look around and the best I can find is that perhaps I need to edit the kernel.json file but I do not know the snytax so I have been unsuccessful so far. If I knew how then I'd only have to do this once.

### What steps reproduce the problem?

1. If I use an Anaconda command prompt to start Spyder this environmental variable is set correctly
2. If I use the Start Menu shortcut to  start Spyder for my "coast" environment then PROJ_LIB environmental variable is not set

3. This can be tested by using the magic command "%env PROJ_LIB" - in case 1 above it is set correctly and in case 2 the environmental variable does not exist 

### What is the expected output? What do you see instead?

I would expect that when I opened a Spyder session from the Windows10 start menu for my coast environment that PROJ_LIB was already set correctly

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
For Spyder to be able to read your environment variables, you need to start it from a system terminal (i.e. cmd.exe in this case), assuming (of course) that your variables are present in every terminal after opening them.

**Comment by clive3** [comment]
This behavior happens from both terminal windows and from Windows start menu
