### ISSUE TITLE
[Question] Any risk in running multiple Spyders in same conda env?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11288]
```
# new Anaconda Powershell Prompt
conda activate some_env
spyder

# new Anaconda Powershell Prompt
conda activate some_env
spyder --new-instance
```
Any stability concerns in running multiple Spyder instances in one virtual env?

**Comment by ccordoba12** [comment]
Things should work fine as far as we know. However, Preferences for the last instance you close will be the only ones saved. In other words, if you modify your preferences for other instances, they'll be overwritten after closing the last one.
