### ISSUE TITLE
[Question] Can one search in files in a single directory (not subdirectories)?

### ISSUE THREAD

**Issue by m-bouville** [spyder-ide/spyder#11298]
I have a subdirectory with archives, so I get results from past versions (excluding files by extension cannot help). I could not find a box I could uncheck saying "search subdirectories". Does this box exist? If not, should it?

**Comment by ccordoba12** [comment]
The way to do that is to add an exclusion pattern for the subdirectory names you don't want to search in in your main directory:

![Selección_085](https://user-images.githubusercontent.com/365293/72283321-8198be80-360c-11ea-83d4-bcf57e8da4a8.png)

In the above screenshot I'm excluding files of the `test` subdirectory in my search.
