### ISSUE TITLE
Variables from environment created by other script cant be used in another script

### ISSUE THREAD

**Issue by diogobotelho** [spyder-ide/spyder#11296]
I cant use global variables generated by one script in another.
Example:

Script 1:
a=1

Script 2:
print(a)

I run script 1 and then script 2 and the error is 
NameError: name 'a' is not defined

Why is this? these variables are supposed to be global. I can interact with the variables from the console and the variables are shown on Variables Explorer. Cant use them in a script.

Using spyder 4.0.1

**Comment by ibrahim-elshar** [comment]
You can change that in the Preferences>Settings>Run>General settings> check "run in console's namespace instead of an empty one. Now what you want above should work.
Or you can just select the line print(a) in Script 2 then right click and Run cell.

**Comment by jitseniesen** [comment]
In Spyder 4, scripts run in an empty namespace with no global variables. After the script is run, all variables are copied in the console's namespace. This is because the old behaviour often caused problems. However, if you want the old behaviour back, you can as described above.

**Comment by diogobotelho** [comment]
That makes sense. I just couldn’t find an answer to this. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
