### ISSUE TITLE
typing "ls" into command causes internal problem

### ISSUE THREAD

**Issue by austinturbs** [spyder-ide/spyder#11295]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
On my home directory, I type "ls" into the command line. Nothing happens. I type "cd Documents" and then I get an error about "ls"

**Comment by ccordoba12** [comment]
What's the error?

**Comment by austinturbs** [comment]
I think this may be an issue with my own computer setup. I just updated to the latest macOS and believe I am just encountering permission problems within Spyder.

I can navigate just fine in my built-in terminal app, but the Spyder terminal is giving me trouble.

**Comment by ccordoba12** [comment]
This is not a problem with Spyder. Please see this

https://stackoverflow.com/questions/58372768/file-permissions-issue-with-python-spyder-anaconda-after-upgrading-mac-to-catali

to understand how to solve it.
