### ISSUE TITLE
Debugger hangs, ignores breakpoints (Spyder 4)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11300]
- Sometimes some breakpoints are ignored
 - Debugger gets stuck in a certain function call, where regular execution proceeds normally
 - Debugger stops working entirely after several kernel restarts (i.e. "Debug" command does nothing but print `debugfile("...")`); fixed by restarting Spyder

Difficult to reproduce second bullet, as it occurs in a highly customized TF-Keras context; nonetheless the offending call is `K.gradients(loss, params)` in `keras\optimizers.py`, after compiling model and loading its weights. Other bullets are highly inconsistent and occur in various settings.

The bugpile's become rather overwhelming; think I'll downgrade to 3 or seek alternatives. Hope 4.1's more stable

**Comment by ccordoba12** [comment]
> The bugpile's become rather overwhelming; think I'll downgrade to 3 or seek alternatives. Hope 4.1's more stable

You need to give us something that works in Spyder 3 but not in 4. Otherwise, there's nothing for us to do about this.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Every bug I named in this post is absent in Spyder 3 (or never occurred to me despite extensive usage)

**Comment by ccordoba12** [comment]
But we haven't observed those bugs in Spyder 4.

In any case, I think this

> Debugger stops working entirely after several kernel restarts

indicates that it's related to #11137, so I'm going to close it for now.
