### ISSUE TITLE
Error occured while using Inspect current object(Ctrl+I) on Editor but works fine on console

### ISSUE THREAD

**Issue by saka10101** [spyder-ide/spyder#11304]
### What steps will reproduce the problem?

    When pressed (Ctrl+I) on any object in the editor gives following error :
    
    - Message window title: Help
    
    - Message Content :
        The following error occured when calling Sphinx 2.2.0 
        Incompatible Sphinx version or doc string decoding failed
        
        Error message:
        Paths don't have the same drive
        
    

### Traceback
```python-traceback
  File "F:\ANACONDA3\lib\site-packages\spyder\plugins\help.py", line 858, in toggle_plain_text
    self.force_refresh()
  File "F:\ANACONDA3\lib\site-packages\spyder\plugins\help.py", line 765, in force_refresh
    self.set_object_text(None, force_refresh=True)
  File "F:\ANACONDA3\lib\site-packages\spyder\plugins\help.py", line 780, in set_object_text
    found = self.show_help(text, ignore_unknown=ignore_unknown)
  File "F:\ANACONDA3\lib\site-packages\spyder\plugins\help.py", line 994, in show_help
    self.set_plain_text(hlp_text, is_code=is_code)
  File "F:\ANACONDA3\lib\site-packages\spyder\plugins\help.py", line 689, in set_plain_text
    self.plain_text.set_text(full_text, is_code)
  File "F:\ANACONDA3\lib\site-packages\spyder\plugins\help.py", line 247, in set_text
    self.editor.set_text(text)
  File "F:\ANACONDA3\lib\site-packages\spyder\widgets\sourcecode\codeeditor.py", line 1595, in set_text
    self.setPlainText(text)
TypeError: setPlainText(self, str): argument 1 has unexpected type 'bool'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by saka10101** [comment]
- Message window title: Help

- Message Content :
    The following error occured when calling Sphinx 2.2.0 
    Incompatible Sphinx version or doc string decoding failed


    

    Error message:
    Paths don't have the same drive
![Error](https://user-images.githubusercontent.com/19640959/72240852-67131500-360d-11ea-866e-f69cf6bbefa3.JPG)

**Comment by ccordoba12** [comment]
Unfortunately Spyder 3 is no longer maintained. So you need to update to 4.0.1, where this error is no longer present.

I understand if you don't want to update, but if that's your decision, please don't report this error.
