### ISSUE TITLE
Help console throwing error 

### ISSUE THREAD

**Issue by seenustag** [spyder-ide/spyder#11303]
### What steps will reproduce the problem?

when we tried to press control and i to findiut suggestion for a function it throws an error 
following error occured  when calling sphinx 2.2.0
incompatable spinx version or doc string failed 
Error message : 
Paths dont have same drive 

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by seenustag** [comment]
[issue to diplay help console.docx](https://github.com/spyder-ide/spyder/files/4052317/issue.to.diplay.help.console.docx)

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.0.1
