### ISSUE TITLE
Spyder doesn't launch after updating to latest version 4.0.1

### ISSUE THREAD

**Issue by marinafridman** [spyder-ide/spyder#11306]
## Problem Description
Spyder opened normally today, but asked me to update. I updated conda and spyder as per the instructions (from the Anaconda prompt). When I try to launch spyder, I get a ValueError: PyCapsule_GetPointer called with incorrect name. I only updated the spyder in a virtual environment, but now I can't open it irrespective of which environment I call it from. Rolling back spyder to version 4.0.0 doesn't fix it. Calling spyder --reset gets the same ValueError.

### What steps reproduce the problem?
In Anaconda prompt:
1. conda update -n base conda
2. conda update spyder
3. spyder

### What is the expected output? What do you see instead?
I expect spyder to launch. Instead I see:
```
Traceback (most recent call last):
  File "C:\Users\Marina\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Marina\Anaconda3\lib\site-packages\spyder\app\start.py", line 200, in main
    from spyder.app import mainwindow
  File "C:\Users\Marina\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 90, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\Marina\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name
```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro 64-bit

**Comment by ccordoba12** [comment]
> I only updated the spyder in a virtual environment, but now I can't open it irrespective of which environment I call it from

This and the error you posted above clearly point to the cause of your problem: you installed pyqt5 with pip in one of your environments.

That completely broke your Anaconda installation and now you have to remove it (with all its environments) and reinstall it again. Sorry for the hassle, but we warn about this over and over again and people don't listen us.

**Comment by DanielGoncalves47264** [comment]
I ran into the same issue today.
Following this answer solved the problem. I guess it saves some of the hassle. [https://stackoverflow.com/a/66012782]
