### ISSUE TITLE
Add external plugins to dependencies

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#11318]
The idea is that this will allow the user to discover which plugins are installed. The list of plugins should also be included when using Spyder's issue reporter. Inspired by spyder-ide/spyder-line-profiler#39.

**Comment by goanpeca** [comment]
I suggest we add a different tree parent (`Third party plugins` or `Spyder plugins`) to add this!
<img width="850" alt="Screen Shot 2020-01-15 at 11 46 00" src="https://user-images.githubusercontent.com/3627835/72453150-a156f080-378c-11ea-8755-4ab6adc5d556.png">

**Comment by ccordoba12** [comment]
> I suggest we add a different tree parent (Third party plugins or Spyder plugins) to add this!

Agreed and my vote is for a new "Spyder plugins" section.

**Comment by jitseniesen** [comment]
@goanpeca I am happy for you to implement this, if you prefer
