### ISSUE TITLE
Spyder 4 GUI regressions on Windows

### ISSUE THREAD

**Issue by patrick984** [spyder-ide/spyder#11314]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Have noticed a number of GUI regressions on Windows after upgrading from Spyder 3 to Spyder 4.

On almost all of the panes, there is no "padding" between the toolbar controls and the elements above. This gives the toolbar buttons an unbalanced appearance (they don't appear vertically centred as expected) and the top of some elements are cut off.

### What steps reproduce the problem?

1. Set Appearance -> Main interface -> Interface theme: Light
2. Set Appearance -> Main interface -> Qt windows style: WindowsVista

### What is the expected output? What do you see instead?

Top pixels of selected tab are cut off:
![spyder 1](https://user-images.githubusercontent.com/12247036/72306677-16aebc80-36cc-11ea-9f58-0b18d9f2024e.png)

Toolbar controls are hard against the top, they should have the same padding above as below.
![spyder 2](https://user-images.githubusercontent.com/12247036/72306685-25956f00-36cc-11ea-9f0c-28662c89e774.png)

![spyder 3](https://user-images.githubusercontent.com/12247036/72306689-28905f80-36cc-11ea-99a9-f46fcaf2fca8.png)

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
@jnsebgosselin, is this something that's going to be address by your PR #10626?

**Comment by jnsebgosselin** [comment]
I think a new option was added in Spyder 4 to adjust that, but I'm not sure.

@patrick984 Can you check if increasing the value of the pane margins in the preferences solve your issue?

![image](https://user-images.githubusercontent.com/10170372/72357388-e3aefd80-36b8-11ea-8ca4-d7f4861c300a.png)

@ccordoba12 Maybe the minimum value of the pane margins should be changed to 1 instead of 0?

**Comment by ccordoba12** [comment]
Things look fine in the dark theme.

**Comment by jnsebgosselin** [comment]
> 
> Things look fine in the dark theme.

It is true. It is probably due to the fact that a lot of 'hidden' hard coded padding is added in the dark theme.

So considering that, I think we should leave this option as is to allow 0 padding in the dark theme.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by patrick984** [comment]
Adjusting custom margin for panes can compensate for the lack of padding on the top of panes but adds unwanted spacing between panes also, see yellow highlight:

Spyder 3:
![spyder3](https://user-images.githubusercontent.com/12247036/72771258-72d98980-3c54-11ea-9ba5-a5fb64e53e95.png)

Spyder 4 (with custom margin set to 3px):
![spyder4](https://user-images.githubusercontent.com/12247036/72771266-7bca5b00-3c54-11ea-9c54-6c1bab2a1c65.png)
