### ISSUE TITLE
Numpy arrays not writable

### ISSUE THREAD

**Issue by ab-5860** [spyder-ide/spyder#11331]
### What steps will reproduce the problem?

whenever i open a variable in variable explorer, i can only resize but neither the format and change background color option is working.
plz respond to this problem.

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.10.2 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5 (OK)
```

**Comment by ccordoba12** [comment]
I don't understand what you mean. Please post some screenshots of your problem.

**Comment by ab-5860** [comment]
![problem](https://user-images.githubusercontent.com/33214238/72550165-225ed680-38b8-11ea-9d71-b6439ff03229.PNG)
Unable to use format and background color option.

**Comment by ccordoba12** [comment]
Ok, I understand your problem now. Please post the code you used to generate that array so we can reproduce it in our side.

**Comment by ab-5860** [comment]
import numpy as np
import pandas as pd

dataset = pd.read_csv("Data.csv")
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,3].values

**Comment by ccordoba12** [comment]
That's not reproducible because we don't have the contents of Data.csv. Please upload that file too.

**Comment by ab-5860** [comment]
[Data.xlsx](https://github.com/spyder-ide/spyder/files/4077705/Data.xlsx)

**Comment by ccordoba12** [comment]
Sorry for not answering before. I think the problem is that Numpy arrays obtained like this

    X=dataset.iloc[:,:-1].values

are object arrays, and those are read-only by default.

**Comment by ccordoba12** [comment]
@steff456, please verify if my assumption is correct. If that's the case, we need to change the window title of our array editor (see the screenshot in https://github.com/spyder-ide/spyder/issues/11331#issuecomment-575272837) from `NumPy array (read only)` to `NumPy object array (read only)`.

**Comment by ab-5860** [comment]
Thanks for your help.
Yes your assumption is correct.

**Comment by ccordoba12** [comment]
@ab-5860, thanks for confirming it! The thing is object arrays can't be edited because we don't know what kind of elements they contain (i.e. they can contain strings, numbers, lists, etc).

**Comment by ArthurShen8118** [comment]
I met the same issue as well. So are there any solution for this case

**Comment by ArthurShen8118** [comment]
How to change the title of windows from NumPy array (read only) to NumPy object array (read only).
