### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by phn409** [spyder-ide/spyder#11339]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I get this error message everytime I start up Spyder. It goes by the following:
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
