### ISSUE TITLE
sypder fault

### ISSUE THREAD

**Issue by Jireh-Jam** [spyder-ide/spyder#11336]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

AttributeError: module 'dateutil.tz' has no attribute 'UTC'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.0
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.18.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
> Spyder Version: 3.2.3
> Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

You're using very old versions of Spyder, Qt and PyQt. Please update using Anaconda (recommended) or pip in a virtualenv.
