### ISSUE TITLE
Kernel connection

### ISSUE THREAD

**Issue by Chun-614** [spyder-ide/spyder#11345]
### What steps will reproduce the problem?

Anaconda could not launch Spyder. Then I reinstalled Anaconda, Spyder can be launched now, but the IPython console displays "Connecting to kernel" all the time and could not run any command.

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1416, in close_client
    self.create_new_client()
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/ipythonconsole.py", line 1106, in create_new_client
    version='<1.0.0')
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/utils/programs.py", line 460, in is_module_installed
    return eval(output.decode())
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.17.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Please run in Terminal.app

    spyder --reset

and try again.

**Comment by Chun-614** [comment]
> Please run in Terminal.app
> 
> ```
> spyder --reset
> ```
> 
> and try again.



> Please run in Terminal.app
> 
> ```
> spyder --reset
> ```
> 
> and try again.

The reset worked. Thank you!!
