### ISSUE TITLE
[Feature Request] Protection against involuntary (and implausible) collapse

### ISSUE THREAD

**Issue by m-bouville** [spyder-ide/spyder#11341]
I sometimes collapse something by clicking too close to the edge. But in some cases this folds a class making up almost the entire file. I am very unlikely to want to collapse everything and see nothing left. There could be a cut-off triggering a message: "You are about to fold 90% of the file. Confirm?"

**Comment by ccordoba12** [comment]
Sorry but that this is very specific, so we don't plan to implement it. Besides, you can very easily unfold what you folded before.

**Comment by m-bouville** [comment]
I have this problem when I try to highlight a whole line.
- Is there a shortcut for selecting a line?
- Is there a way to increase the space between the arrows for collapsing and the main window (adding a no man's land)?
