### ISSUE TITLE
Editor: wrong tooltip position when undocking

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#11355]
The tooltips are being placed incorrectly after a docking or undocking of the Editor:

![tooltipe](https://user-images.githubusercontent.com/16781833/72756502-66ddc100-3b9b-11ea-8bfd-dedd2434cd37.gif)

As discussed with @ccordoba12

**Comment by igurin-invn** [comment]
I'm getting this exact issue on v6.1.2.

**Comment by ccordoba12** [comment]
I can't reproduce this issue on Linux @igurin-invn.

**Comment by igurin-invn** [comment]
I'm on Windows 11 Enterprise. Do you want any other information?

**Comment by ccordoba12** [comment]
Yeah, how did you install Spyder?

And, is it the problem exactly the same as in the video posted in the initial post?

**Comment by igurin-invn** [comment]
Yes, it's the same.

I installed Spyder via pip in a virtual environment. The Python version is 3.11.9.

https://github.com/user-attachments/assets/f77aec51-3bab-4fb5-9e60-4608562747a0

**Comment by ccordoba12** [comment]
Ok, thanks for the extra info @igurin-invn.

@dalthviz, please check if you're able to reproduce this on Windows.

**Comment by dalthviz** [comment]
Checked locally with Spyder 6.1.2 from the installers on Windows and I was able to reproduce. Seems like when the tooltip is shown, the window that has the Editor moves under the mainwindow 🤔 

![Image](https://github.com/user-attachments/assets/88350554-8aca-4b80-b4ef-384f96d2e6f5)

Should we open a new issue to track again this @ccordoba12 ?

**Comment by igurin-invn** [comment]
Great, thanks for confirming! Yeah, this is very annoying. It makes the undocked editor almost impossible to use.

**Comment by ccordoba12** [comment]
> Should we open a new issue to track again this @ccordoba12 ?

Yep, please do, tag it for 6.1.4 and try to solve it after we release 6.1.3.
