### ISSUE TITLE
Find in files: excluding comments and strings

### ISSUE THREAD

**Issue by m-bouville** [spyder-ide/spyder#11368]
I was looking for all places where I used of a certain variable in my code. But Find in files found a lot of commented-out code and of cases where I just printed the value of the variable. The lines where the variable was actually used were thus mixed with false positives. 

As far as I can tell, "exclude" only excludes files, not types of content within the files. A possible enhancement would be a box allowing one not to search comments and (another?) not to search strings.

**Comment by ccordoba12** [comment]
Well, it's easy to detect if a line starts with a specific character (e.g. `#` or `"`), but we couldn't easily detect inline comments or strings. So that's the best we could provide.

Is that ok for you?

**Comment by goanpeca** [comment]
I would say that the user could use a regex for this?

**Comment by ccordoba12** [comment]
That's true too. @goanpeca, could share a Licecap video to show the OP how to do that?

**Comment by goanpeca** [comment]
@m-bouville if you had something like this

```python
variable = 1


"""variable """
"""  variable """
'''  variable '''
' variable '
" variable "
# variable 



def test():
    variable = 1
    
    
    """variable """
    """  variable """
    '''  variable '''
    ' variable '
    " variable "
    # variable 
```

Using the find with a regex like

```python
^(?!^\s*["'#]).*variable
```

Would yield:

<img width="745" alt="Screen Shot 2020-01-21 at 13 44 11" src="https://user-images.githubusercontent.com/3627835/72833123-22fac280-3c54-11ea-96a7-f29d1d07ae04.png">

**Comment by ccordoba12** [comment]
Closing because (although hard) using regexps is the way to go to have more fine grained results.

**Comment by goanpeca** [comment]
We could maybe add this to the website FAQ 🤷‍♂ ?

**Comment by ccordoba12** [comment]
Please open an issue in our docs repo so @juanis2112 can add an example for this when describing the Find pane.
