### ISSUE TITLE
TypeError in configdialog.py caused by external plugins not defining CONF_DEFAULTS

### ISSUE THREAD

**Issue by timhughes** [spyder-ide/spyder#11385]
### What steps will reproduce the problem?

I saved some preferences. Appears to be the same as https://github.com/spyder-ide/spyder/issues/11302 

hughest@argon [0] $ pip freeze 
alabaster==0.7.12
argh==0.26.2
astroid==2.3.3
asttokens==2.0.3
atomicwrites==1.3.0
attrs==19.3.0
autopep8==1.5
Babel==2.8.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cloudpickle==1.2.2
coloredlogs==10.0
cryptography==2.8
cycler==0.10.0
decorator==4.4.1
defusedxml==0.6.0
diff-match-patch==20181111
docutils==0.16
entrypoints==0.3
flake8==3.7.9
helpdev==0.6.10
humanfriendly==4.18
idna==2.8
imagesize==1.2.0
importlib-metadata==1.4.0
intervaltree==3.0.2
ipykernel==5.1.3
ipython==7.11.1
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.14.1
jeepney==0.4.2
Jinja2==2.10.3
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-core==4.6.1
keyring==21.1.0
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
line-profiler==3.0.2
lxml==4.4.2
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mccabe==0.6.1
memory-profiler==0.57.0
mistune==0.8.4
modelx==0.2.0
more-itertools==8.1.0
nbconvert==5.6.1
nbformat==5.0.3
networkx==2.4
notebook==6.0.3
numpy==1.18.1
numpydoc==0.9.2
packaging==20.0
pandocfilters==1.4.2
parso==0.5.2
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
pluggy==0.13.1
prometheus-client==0.7.1
prompt-toolkit==3.0.2
psutil==5.6.7
ptyprocess==0.6.0
Pweave==0.30.3
pycodestyle==2.5.0
pycparser==2.19
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.5.2
pylint==2.4.4
pyparsing==2.4.6
PyQt5==5.12.3
PyQt5-sip==12.7.0
PyQtWebEngine==5.12.1
pyrsistent==0.15.7
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.7
pytz==2019.3
pyxdg==0.26
PyYAML==5.3
pyzmq==18.1.1
QDarkStyle==2.8
QtAwesome==0.6.1
qtconsole==4.6.0
QtPy==1.9.0
requests==2.22.0
rope==0.16.0
SecretStorage==3.1.2
Send2Trash==1.5.0
six==1.14.0
snowballstemmer==2.0.0
sortedcontainers==2.1.0
Sphinx==2.3.1
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.2
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.3
spyder==4.0.1
spyder-kernels==1.8.1
spyder-line-profiler==0.2.0
spyder-memory-profiler==0.2.0
spyder-modelx==0.1.0
spyder-notebook==0.2.1
spyder-reports==0.1.1
spyder-terminal==0.2.4
spyder-unittest==0.4.0
terminado==0.8.3
testpath==0.4.4
tornado==6.0.3
traitlets==4.3.3
ujson==1.35
urllib3==1.25.8
watchdog==0.9.0
wcwidth==0.1.8
webencodings==0.5.1
wrapt==1.11.2
wurlitzer==2.0.0
yapf==0.29.0
zipp==2.0.0

### Traceback
```python-traceback
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/plugins/base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/preferences/configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/preferences/configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
Traceback (most recent call last):
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 3139, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/plugins/base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/preferences/configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "/home/hughest/.pyenv/versions/3.8.1/lib/python3.8/site-packages/spyder/preferences/configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.8.1
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.16-300.fc31.x86_64

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.2 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @timhughes, do you have installed any plugin with Spyder? if that's the case, you are probably correct and this is a duplicated of #11302

**Comment by timhughes** [comment]
yeah i have the following. I can see if i can isolate which one 
```
spyder==4.0.1
spyder-kernels==1.8.1
spyder-line-profiler==0.2.0
spyder-memory-profiler==0.2.0
spyder-modelx==0.1.0
spyder-notebook==0.2.1
spyder-reports==0.1.1
spyder-terminal==0.2.4
spyder-unittest==0.4.0
```

**Comment by jitseniesen** [comment]
This error is definitely present in those versions of spyder-line-profiler and spyder-memory-profiler, and fixed by PR spyder-ide/spyder-line-profiler#40 and spyder-ide/spyder-memory-profiler#24 respectively. Other plugins may have the same problem.

**Comment by dalthviz** [comment]
I will check. Thanks @jitseniesen for the info :+1:

**Comment by ccordoba12** [comment]
> spyder-reports==0.1.1
spyder-terminal==0.2.4

These plugins are incompatible with Spyder 4. Please uninstall them and update spyder-memory-profiler and spyder-line-profiler to their latest versions.

**Comment by timhughes** [comment]
cheers , thanks
