### ISSUE TITLE
Kernel dies silently and doesn't restart properly.

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#11406]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Type in the kernel:
```
import numpy as np
a = np.zeros((2, 18030, 162542200), float) * np.nan
```
2. Wait for python to crash
3. When you get a prompt back, try running a cell.

### What is the expected output? What do you see instead?

spyder:
```
Python 3.7.5 (default, Nov  1 2019, 02:16:23) 
Type "copyright", "credits" or "license" for more information.

IPython 7.10.2 -- An enhanced Interactive Python.

In [1]: import numpy as np
   ...: a = np.zeros((2, 18030, 162542200), float) * np.nan

In [1]: 
```
qtconsole:
```
Jupyter QtConsole 4.7.0.dev0
Python 3.7.5 (default, Nov  1 2019, 02:16:23) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.10.2 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np
   ...: a = np.zeros((2, 18030, 162542200), float) * np.nan

Kernel died, restarting


 
Kernel died, restarting


 
Kernel died, restarting


 

In [1]: 

In [1]: 
```

python3:
```
Python 3.7.5 (default, Nov  1 2019, 02:16:23) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.zeros((2, 18030, 162542200), float) * np.nan
zsh: killed     python3
```

After the prompt returns and I run a cell, I get:
```
In [1]: runcell(0, 'test.py')
This command failed to be executed because an error occurred while trying to get the cell code from Spyder's editor. The error was:


An exception has occurred, use %tb to see the full traceback.

CommError: Can't make a request to a closed comm
```
### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
What do you suggest we should do? I mean, it seems more a problem in Jupyter than in Spyder, right?

**Comment by impact27** [comment]
Not really, the kernel crashes because it asks for an unreasonable amount of memory. But spyder doesn’t show the “kernel died” message and doesn’t reopen the comm.

**Comment by ccordoba12** [comment]
> But spyder doesn’t show the “kernel died” message and doesn’t reopen the comm.

Creating a new kernel after the previous one dies is done by jupyter_client, not by Spyder.

Are you able to run code in qtconsole after the kernel dies and you have a new prompt?

**Comment by impact27** [comment]
In `qtconsole` I get a message that says "Kernel died, restarting" which I don't in `spyder`. Futhermore there is the problem with the disconnected comm.

**Comment by impact27** [comment]
Easier way to reproduce the same issue:
```
import os
os.getpid()
```
Then open a terminal and type `kill <pid>` where `<pid>` is the number you got from the kernel.

**Comment by impact27** [comment]
It looks like `client.py` `_restart_thread_end` is not called somehow

**Comment by ccordoba12** [comment]
> It looks like client.py _restart_thread_end is not called somehow

Is that code part of jupyter_client?

**Comment by impact27** [comment]
I was looking at code from one of my PR. This is fixed there.
