### ISSUE TITLE
Spyder 4 is not preserving files creation time

### ISSUE THREAD

**Issue by senlin198** [spyder-ide/spyder#11403]
Hello,Spyder developer，when i use Spyder 4.0.1 to edit my python file it change my file creation time. Spyder change my python file creation time to newest time but creation time is very important for me. Creation time is a important record for me so could your solve this issue？I am looking forward your reply . How can i recover my python file creation time? Creation time is important for me! my email：lin649665076@gmail.com.

**Comment by ccordoba12** [comment]
Thanks for reporting. We haven't noticed this before.

> How can i recover my python file creation time?

There's no way to recover that date, sorry. So I'm afraid you'll have to use another editor until we fix this in Spyder.

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one. This probably happens because we're not preserving the creation date after doing an atomic write.

**Comment by senlin198** [comment]
> Thanks for reporting. We haven't noticed this before.
> 
> > How can i recover my python file creation time?
> 
> There's no way to recover that date, sorry. So I'm afraid you'll have to use another editor until we fix this in Spyder.

It's too bad. Creation time is a important record for me, because it record beginning to program.
