### ISSUE TITLE
Spyder IDE hangs (not responding) while copying when a process is running.

### ISSUE THREAD

**Issue by apremgeorge** [spyder-ide/spyder#11414]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
1. Spyder IDE 4.0.1 hangs (not responding), when a process is running and same time I do copy pasting codes in .py file the ide goes not responding, waiting for long time also didn't help, I have to close and open.
2. If I copy a set of code, suddenly the codes disappears and a special character appears at that place.

### What steps reproduce the problem?

1. I am running a keras model and doing a copy paste in the code when the model running, the spyder hangs, I have to wait till running process finishes. Not only keras model, while any long run process.
2. Copy a set of codes, switch between 2 screens, the highlighted copied code disappears and a special character like omega, alpha.... appears.

### What is the expected output? What do you see instead?
1. IDE hangs
2.  special characters

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.4
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please post a video (animated gif) of your problem with the Licecap program to better understand what's happening.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
