### ISSUE TITLE
while saving  code in editor says no file found

### ISSUE THREAD

**Issue by rajku209** [spyder-ide/spyder#11411]
### What steps will reproduce the problem?

while saving code from editor,it says file not found at destination folder location

![Capture](https://user-images.githubusercontent.com/9960634/73200142-3a5a1400-415c-11ea-93c3-c067afd126cf.PNG)

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Please update to Spyder 4 by opening the Anaconda Prompt and running the commands

    conda update anaconda
    conda update spyder

Then try again.

**Comment by rajku209** [comment]
Thanx. really helped in manyways
