### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by IADSJohn** [spyder-ide/spyder#11421]
In Spyder, I double clicked on an array in the variable explorer. An error box came up asking me to submit a report. No array came up as before. This behavior started as soon as I installed Spyder 3.2.8, Anaconda 4.7.12 is the package.

**Comment by ccordoba12** [comment]
This is fixed in our latest version Spyder 3. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

**Comment by IADSJohn** [comment]
Thanks, Carlos
