### ISSUE TITLE
[Feature] Add sphinx/reStructuredText docstrings

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#11435]
Is there a reason why Sphinx/reStructuredText annotation is not added to Spyder auto-doc?
It's a little more simplistic than numpy/google.

**Comment by ccordoba12** [comment]
I don't understand what you mean. Please be more explicit.

**Comment by skjerns** [comment]
under settings->editor->advanced you can set a docstring format that is automatically introduced. Here it would be useful to have the option of reStructuredText, e.g.

```Python
def func(p):
    """
    function description
    
    :param p: this does x
    :returns: 'hello'
    """
    return 'hello'
```

**Comment by ccordoba12** [comment]
That feature was added by a volunteer contributor, and he decided to add support for Numpy and Google style docstrings only.

So it's up to you or the community to fill this gap if they want to see Sphinx/reStructuredText kind of auto-generated docstrings support.

**Comment by ok97465** [comment]
@skjerns @ccordoba12 May I try to solve this issue?

**Comment by skjerns** [comment]
of course!

**Comment by ccordoba12** [comment]
> May I try to solve this issue?

Sure, please go ahead.

**Comment by ok97465** [comment]
Thank you :smile:!

@skjerns There's something I want to check.
>This format is a bit older, but also a bit more space saving and simpler

The sphinx format of autodocsting of vscode is also long.
![Screenshot from 2020-02-02 05-50-24](https://user-images.githubusercontent.com/22970578/73598893-e6e32e00-4580-11ea-912b-d74cde71b5f6.png)

Is this the format you want?

**Comment by garthmortensen** [comment]
Thank you for adding this @ok97465!
