### ISSUE TITLE
Internal Problem By Itself

### ISSUE THREAD

**Issue by Hogbobson** [spyder-ide/spyder#11436]
### What steps will reproduce the problem?

I'm not sure what the problem is, or why it happened. I simply have had Spyder open for a few days now - i was not actively using it when the problem occurred. Sorry.

### Traceback
```python-traceback
  File "/home/hogbobson/anaconda3/envs/hpsim/lib/python3.7/site-packages/spyder/utils/introspection/plugin_client.py", line 158, in _on_finished
    self.run()
  File "/home/hogbobson/anaconda3/envs/hpsim/lib/python3.7/site-packages/spyder/utils/introspection/plugin_client.py", line 104, in run
    raise IOError('Could not start %s' % self)
OSError: Could not start <spyder.utils.introspection.plugin_client.PluginClient object at 0x7f15b06d7048>
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.0.0-37-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is a problem with our old code completion architecture, and it no longer applies to our new one (i.e. the one we added to Spyder 4).

So if you don't want to update to Spyder 4, please ignore this error and don't report it anymore.
