### ISSUE TITLE
Kernel     Error

### ISSUE THREAD

**Issue by aneervan2000** [spyder-ide/spyder#11433]
### What steps will reproduce the problem?

whenever i am opening spyder it is showing kernel error
i have installed and uninstalled anaconda for this thing many time but stil the problem exist

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
What's the error? Please post it here so we can really help you.

**Comment by Shongololo** [comment]
Hi. Is this not the issue generally known as 'win32security.GetFileSecurity kernel error'. I understand you need to deprecate your jupyter client and server as follows "conda install jupyterlab_server=1.0.0 jupyter_client=5.3.1". For this reason I can't seem to upgrade to 4.0.1. I will post another related to my problem.

**Comment by ccordoba12** [comment]
@Shongololo, please don't setup in other users issues for next time.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
