### ISSUE TITLE
high CPU usage and system freezing even when spyder is idle

### ISSUE THREAD

**Issue by isalirezag** [spyder-ide/spyder#11440]
Im using Spyder 4.0.1, Python 3.6.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Linux 4.15.0-76-generic .
My system is ubuntu 16.04

When I have spyde idle and just open I see cpu usage suddenly increases (Without doing anything else) and also the system freezes for a min or so.

Is there anything in the setting that I can change so it does not happen?

**Comment by goanpeca** [comment]
@isalirezag just to check. Spyder is idle and the cpu usage is up?

Or it is idle, and then you "wake it" and at that moment is that the CPU spikes?

Thanks!

**Comment by isalirezag** [comment]
@goanpeca Spyder is idle and I am just drifting my mouse and cpu usage is up.
Not sure what do you mean by wake it up?

**Comment by goanpeca** [comment]
I meant if you have the windows of spyder open and you are moving inside spyder or if spyder is minimized and you are doing something else on another program. Or are you seeing this if you move the mouse inside the editor, if you do it on another part (console, help plugin) it does not spike?

**Comment by isalirezag** [comment]
@goanpeca I see, thanks for the clarification.
Spyder is minimized and I am just browsing my mouse, I see the system freeze time to time. If I close spyder it does not happened

**Comment by goanpeca** [comment]
Ok, thanks for the details. @andfoy @ccordoba12 can you reproduce this on your linux machines?

**Comment by isalirezag** [comment]
@goanpeca is there any option in tool that I can change to see if it will reduce the cpu/memory usage in general?

**Comment by ccordoba12** [comment]
Please start Spyder from the command line with this option:

    spyder --debug-info verbose

and try to detect what messages are displayed when Spyder freezes your system.

**Comment by isalirezag** [comment]
I will close it for now and reopen it when I find something then.
