### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by NicolasRanc** [spyder-ide/spyder#11445]
### What steps will reproduce the problem?

Just starting Spyder after a full update of anaconda packages.

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.7
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.1.1 (OK)
pycodestyle >=2.3:  2.5.0 (OK)
pygments >=2.0   :  2.5.2 (OK)
pandas >=0.13.1  :  1.0.0 (OK)
numpy >=1.7      :  1.17.5 (OK)
sphinx >=0.6.6   :  2.3.1 (OK)
rope >=0.9.4     :  0.16.0 (OK)
jedi >=0.9.0     :  0.16.0 (OK)
nbconvert >=4.0  :  5.6.1 (OK)
sympy >=0.7.3    :  1.5.1 (OK)
cython >=0.21    :  0.29.14 (OK)
qtconsole >=4.2.0:  4.6.0 (OK)
IPython >=4.0    :  7.11.1 (OK)
pylint >=0.25    :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version Spyder 3. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
