### ISSUE TITLE
Autocomplete in a cmd2.cmdloop()

### ISSUE THREAD

**Issue by mortenholmjensen** [spyder-ide/spyder#11466]
## Problem Description

Autocomplete is not working when running cmd2.cmdloop inside IPython console in spyder. Running the same program from an IPython terminal outside spyder (e.g. for windows cmd.exe) then autocompleting is working fine.

### What steps reproduce the problem?

1. Run the program for an IPython terminal outside spyder:
```python
import cmd2

class Cmd2Test(cmd2.Cmd):
    def __init__(self):
        cmd2.Cmd.__init__(self)

    def do_hello(self, args):
        print('Hello world')

if __name__ == '__main__':
    app = Cmd2Test()
    app.cmdloop()
```
2. Type "he" and pres <TAB> and it will complete the command hello
3. Redo the above from a IPython console in spyder. Then tab complete is not working.

## Versions
* Spyder version: 3.3.6 
* Python version: 3.3.6 
* Operating System name/version: Windows 10

### Dependencies
```
cmd2 >= 0.9.23
```

**Comment by ccordoba12** [comment]
`cmd2` only works correctly in a system terminal (like xterm, Terminal.app or cmd.exe) because it uses readline to provide code completion, history, etc (our IPython console can't use readline, sorry).

**Comment by mortenholmjensen** [comment]
Thanks for the reply. Do you have any suggestion of a cmd loop module that can be used inside spyder?

**Comment by ccordoba12** [comment]
I don't think cmd's can be used inside Spyder, sorry.
