### ISSUE TITLE
Spyder freezes regularly

### ISSUE THREAD

**Issue by raphaelquast** [spyder-ide/spyder#11486]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The issue I'm facing is a bit of a strange one...

I've been using Spyder for years now, but since the update of Spyder 4 the editor is regularly freezing (infinitely) and up to now I could not figure out the cause.
(By regularly I mean this is happening at least once but usually multiple times a day!)

posting a video of it is quite difficult as I have so far not been able to track down the cause of it
and it is happening completely out of nowhere (e.g. the editor freezes simply while I'm writing code)
I could start making a video of a whole days work but i don't think that this would really help...

I've tried to see if other people experience similar issues and it seems like those ones could be related to the same problem (experiencing freezing while being similarly vague in the cause)   #11451  #11414 #11480) However, I've not been able to reproduce the freezing by simply copying something while a process is runnning as described in #11414

So far the only things that could be a start are the following:
1) It seems that spyder is having troubles with the network-drive where 
the spyder-project is located... (e.g. in case the drive is disconnected for a very short instance of time)
This manifests itself as shown in the following image which shows 2 states of the file-explorer:
![spyderissue](https://user-images.githubusercontent.com/22773387/73643477-dfe91800-4673-11ea-969b-c7b4fe1d7b37.png)

2) the code-folding is regularly showing rather strange behaviour
    - it takes quite some time to initialize the fold-indicators when a file is first opened
    - after some time of coding, the folds start to become "misplaced" (e.g. they show up at wrong positions or they don't get updated correctly)

Any help in tracking down this issue would be great since I would very much like to continue using sypder 4 but working with an editor that shuts itself down every couple of hours is not suitable...
(while using spyder 3 i did not experience those issues)

### What steps reproduce the problem?
nothing special... just simple coding for a couple of hours

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.6.7
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: windows 10 64bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  2.2.2 (OK)
numpy >=1.7                  :  1.17.3 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. About your issues:

> It seems that spyder is having troubles with the network-drive where
the spyder-project is located

Fixed already in #11473.

> the code-folding is regularly showing rather strange behaviour

This is being tracked in #11412.

**Comment by raphaelquast** [comment]
that's good news :-) thanks for the quick reply... can you tell when this fix is incorporated in a new release?

so this might solve the crashes as well?

**Comment by ccordoba12** [comment]
These fixes will be available in 4.1.0, to be released in two or three weeks.

**Comment by raphaelquast** [comment]
perfect, thanks! 👍

**Comment by liangbright** [comment]
Is 4.1.0 available ?
The problem is severe

**Comment by ccordoba12** [comment]
Almost there. It should be ready in a couple of days.

**Comment by raphaelquast** [comment]
good news :-) looking forward to it... Thanks!!
