### ISSUE TITLE
Add wxWidgets to the dmg macos X installer

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1148]
_From [emmanuel...@gmail.com](https://code.google.com/u/100385603887224922824/) on 2012-09-10T10:30:48Z_

Everything is in the title!
It would be nice to be able to run ipython with --pylab=wx

(version 2.9.xxx of wxWidgets and not 2.8.xxx)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1148_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-09-19T07:41:34Z_

Thanks for reporting. Hope it's not that hard.

**Status:** Accepted  
  **Labels:** MS-v2.2 OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-11T08:55:57Z_

I'll consider it for the next release. It won't probably happen because the DMG's are big enough right now (we have a 200Mb limit in googlecode).

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:57:20Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by ccordoba12** [comment]
Closing because it has shown very little interest.
