### ISSUE TITLE
run cell ctrl+enter is not running i.e. run cell runs the whole script instead of part script

### ISSUE THREAD

**Issue by v2ancha** [spyder-ide/spyder#11484]
### What steps will reproduce the problem?

run cell ctrl+enter is not running i.e. run cell runs the whole script instead of part script

If i select a part code and right click to run cell it should run only the part of script highlighted which was the case earlier but now it is not working and the whole script starts to get running...every time

## Versions

* Spyder version: 4.0.1 
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.0 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
You need to remap the `Ctrl+Enter` shortcut to run a line or selection instead of the current cell by going to the menu

    Tools > Preferences > Keyboard shortcuts

and searching for

    run selection

**Comment by thomasrmulhern** [comment]
I'm running into the same issue on OSX, but when I remap Shift+Enter to run selection,  and apply the changes, it does nothing when I press Shift+Enter rather than  either run the selection or run all the code.

spyder: 4.0.1
spyder-kernel: 1.8.1
Operating System: OSX Catalina 10.15.3 (19D76)
PyQt5: 5.12.3

**Comment by sk-ys** [comment]
I had the same problem, which was solved by resetting the spyder settings. Specifically, I opened the Anaconda Prompt and typed "spyder --reset".

spyder: 4.1.2
spyder-kernels: 1.9.0
Operating System: WIndows 10 x64 Build 18363
qt: 5.9.7
PyQt5: 5.12.3
