### ISSUE TITLE
autocomplete goes after cmd+enter

### ISSUE THREAD

**Issue by Travis-Barton** [spyder-ide/spyder#11483]
I changed 'run current line' to cmd+enter, and now every time i do so, autocomplete tries to finish my sentence. Is there any way you all could make autocomplete only fire if I press enter (and only enter)?
I NEVER mean arithmaticerror XD 

better yet, is there a way to turn off those types of autocompletion all together? I want it to finish a line, but at this point its a nuisance.

**Comment by ccordoba12** [comment]
> and now every time i do so, autocomplete tries to finish my sentence

This should be fixed in PR #11413.

> better yet, is there a way to turn off those types of autocompletion all together?

You can do that by going to the menu

    Tools > Preferences > Completion and linting > Completion

and deactivating `Show completions on the fly`; or

    Tools > Preferences > Completion and linting > Advanced

and deactivating `Enable fallback completions`.
