### ISSUE TITLE
I donot know what is the problem but the internal problem box is opening up everytime I open the system

### ISSUE THREAD

**Issue by zouluclara** [spyder-ide/spyder#11490]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
The internal problem box opened up when I open the spyder

**Comment by ccordoba12** [comment]
Please post the error you're getting here, else we can't help you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
