### ISSUE TITLE
Sphinx issues continue

### ISSUE THREAD

**Issue by Dan-Patterson** [spyder-ide/spyder#11491]
The problem persists with Sphinx.  Anything not equal to 1.8.5 fouls up numpy docstrings.
Is it a Spyder issue? a numpydoc issue? But I do a lot of install/uninstall/repair work and this has been a nagging issue for months.  I would appreciate any workaround or timeline since I don't know what to repair on my own
Regards.

Spyder 4.0.1
Windows 10
The only thing that works is to 
conda install sphinx=1.8.5 --no-pin

![sphinx_docstring_error](https://user-images.githubusercontent.com/6071199/73993547-780b2980-4920-11ea-8bc9-6e0fc7e020a9.png)

**Comment by ccordoba12** [comment]
It's a Sphinx issue and it'll be fixed in our next version (4.1.0), to be released in a couple of weeks.
