### ISSUE TITLE
Flags are misaligned when scrolling if code is folded

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#11495]
The scrolling behaviour is broken on master:
![broken_master](https://user-images.githubusercontent.com/6740194/74016980-a249ff00-4993-11ea-979b-57db775b0417.png)

_Originally posted by @impact27 in https://github.com/spyder-ide/spyder/pull/11488#issuecomment-583304164_

**Comment by goanpeca** [comment]
@impact27, I think you tackled two issue on a single PR, one was fix for this, while other was the optimization.

Could you split them in spearate PRs? This makes it much easier to review and faster to merge (since one is a bug and the other is more of an enhancement)

Thanks!

**Comment by impact27** [comment]
Well I rewrote part of the logic for optimisation so I can’t really separate them.

**Comment by goanpeca** [comment]
>Well I rewrote part of the logic for optimisation so I can’t really separate them.

Ok
