### ISSUE TITLE
Make fallback completions respect prefix

### ISSUE THREAD

**Issue by its-dhung** [spyder-ide/spyder#11493]
## Problem Description
It appears that fallback completions do not always respect the prefix underneath the user's cursor.

### What steps reproduce the problem?

1. Have fallback completions enabled.
2. Have the following buffer state:
```python
x = 1$
```
3. Manually request completions.

### What is the expected output? What do you see instead?

In this case, I would expect no completions to be returned. Instead, fallback completions seem to show builtin symbols:

![image](https://user-images.githubusercontent.com/3752225/74003773-a12fb800-4928-11ea-92a2-91b4164fa35f.png)

This is especially a problem when on-the-fly completions are enabled. The user ends up seeing wrong completions in cases like this.

## Versions

Spyder 4.0.1 | Python 3.7.0 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Darwin 19.3.0 

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.0 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by ElieGouzien** [comment]
Let me add that completion is also proposed (with everything possible) when indenting existing line.
To reproduce, just write
```python
x = 1
```
go at the beginning and press [tab].

I guess it is directly linked.

I haven't checked if #11531 also correct this.

**Comment by goanpeca** [comment]
@andfoy do we check if after hitting tab there is nothing behind the word?

**Comment by andfoy** [comment]
> do we check if after hitting tab there is nothing behind the word?

Yes, I can reproduce it. However, that's unrelated to this issue
