### ISSUE TITLE
Spyder 4 cannot launch when Kite is installed

### ISSUE THREAD

**Issue by Supltz** [spyder-ide/spyder#11497]
### What steps will reproduce the problem?

Traceback (most recent call last):
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 3711, in main
mainwindow = run_spyder(app, options, args)
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 3552, in run_spyder
main.setup()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 137, in start
running = check_if_kite_running()
File "F:\Anaconda\envs\tensorflow\lib\site-packages\spyder\plugins\completion\kite\utils\status.py", line 42, in check_if_kite_running
'status']):
TypeError: process_iter() got an unexpected keyword argument 'attrs'

I have install and uninstall several times.It still doesn't work.
BTW,Spyder works fine when I uninstall Kite.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  0.4.0 (NOK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  1.6.3 (OK)
pylint >=0.25                :  1.7.2 (OK)
psutil >=0.3                 :  5.2.2 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  17.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.7.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  unknown (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.12.0 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
numpy >=1.7                  :  1.17.0 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
```

**Comment by Supltz** [comment]
Kite can not detect spyder either.

**Comment by ccordoba12** [comment]
@metalogical, any ideas of what can be happening here?

**Comment by goanpeca** [comment]
>process_iter() got an unexpected keyword argument 'attrs'

?

**Comment by Supltz** [comment]
![tw](https://user-images.githubusercontent.com/60577034/74105906-ce849c00-4b9c-11ea-8fde-303167b91baf.png)
is anything wrong in status.py ?

**Comment by metalogical** [comment]
The fact that Kite doesn't see Spyder is a red herring - Kite's detection logic can fail in many cases, but it shouldn't otherwise affect the behavior of the integration.

It looks like [`psutil==5.2.2`](https://github.com/giampaolo/psutil/releases/tag/release-5.2.2) doesn't support any arguments for [`process_iter`](https://github.com/giampaolo/psutil/blob/c54a0f4/psutil/__init__.py#L1454). I think we just need to update the dependency to require a newer version of the library.

**Comment by goanpeca** [comment]
@Supltz  you need to update your `psutil` package

```sh
conda install psutil>=5.3
```

We will add constraints to our dependencies so newer versions of spyder do not incur in this error

**Comment by Supltz** [comment]
@goanpeca 
![0](https://user-images.githubusercontent.com/60577034/74241744-99e91f80-4d17-11ea-954a-06cc28b13777.png)
![1](https://user-images.githubusercontent.com/60577034/74241745-9b1a4c80-4d17-11ea-8d0e-111639da1f18.png)

still fails to launch

**Comment by Supltz** [comment]
Problem solved. Thanks a lot

**Comment by goanpeca** [comment]
Glad to be of help!
