### ISSUE TITLE
Suggestion: Spyder Editor Horizontal splitter required to navigate code quickly

### ISSUE THREAD

**Issue by anilm17** [spyder-ide/spyder#11494]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Split screen required, This is not an issue however a suggestion
Code editor: Horizontal splitter which helps in navigation from one part of code to another.
This basically helps in navigating large code within the same program. It does available in SAP ABAP Editor and Robust button base debugger required where one can click on variable/class/objects
value will appear on the debugger screen.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
It's available here:

![Selección_108](https://user-images.githubusercontent.com/365293/74105297-8462d280-4b2a-11ea-81da-a4802d0a9c32.png)
