### ISSUE TITLE
Remember collapses

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11504]
It'd be nice for Spyder to remember which blocks of code I've collapsed when saving code, sparing repetitive manual work upon reopening a file. (Feature request)

**Comment by ccordoba12** [comment]
Nice suggestion! We'll try to implement it in a future version.

**Comment by bcolsen** [comment]
Saving code folding state is mentioned in #8090(code folding unofficial epic). I'm closing as duplicate of #8090.

**Comment by bcolsen** [comment]
Sorry didn't see that it was labelled 4.2. @ccordoba12 can close if you want.

**Comment by ccordoba12** [comment]
Sorry, I didn't know this was already mentioned on issue #8090.
