### ISSUE TITLE
Unintuitive behavior: Mouse wheel scrolling in editor steals keyboard focus

### ISSUE THREAD

**Issue by matheger** [spyder-ide/spyder#11502]
## Problem Description

With keyboard focus in the internal console, hovering the mouse cursor over the editor window and scrolling through the code with the mouse wheel places keyboard focus back into the editor window instead of leaving it in the console. This feels very counterintuitive to me compared to the general behavior in Windows, where the mouse wheel can be used to scroll through background windows without the active one losing its focus. 

It seems like a minor issue but it's very annoying to me because now I keep accidentally messing up my code instead of typing in the console. I also think Spyder 3 did not show this behavior; not quite sure, but I don't remember anything like this before upgrading to 4.

## Versions

* Spyder version: 4.0.1
* Python version: Python 3.7.6 64-bit
* Qt version: 5.9.6 
* PyQt version: 5.9.2 
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by bcolsen** [comment]
I can confirm this in Ubuntu. Only the editor seems to steal focus.
