### ISSUE TITLE
Cannot launch Spyder in a new environment 

### ISSUE THREAD

**Issue by qwang925** [spyder-ide/spyder#11508]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have NO issue when installing Spyder with default Python (version =3.7.4) in a new environment (conda create --name coursera_Kaggle python spyder). However, when I specified the Python version to be 3.6, and installed Spyder (conda create --name coursera_Kaggle python=3.6 spyder), Spyder cannot launch. I tried the latest version 4.0.1 and version 3.3.6, and neither of them launches. 

Spyder was installed via Anaconda on Windows 10.

I first tried the "reset" shortcut associated with the new environment (such a script shortcut was created after the new environment was created and Spyder was installed), but it still doesn't solve the issue. Instead of working in the new environment, it clears/resets the setting the base environment, i.e. after running the reset script, my Spyder in the base environment was reset to the default settings.

I searched online and tried all solutions I can find, but none of them works.

### What steps reproduce the problem?

1. conda create --name coursera_Kaggle python=3.6 spyder
2. conda activate coursera_Kaggle
3. spyder

for version 3.3.6, the first command line is 

conda create --name coursera_Kaggle python=3.6 spyder=3.3.6

### What is the expected output? What do you see instead?

It doesn't launch.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\spyder\app\mainwindow.py", line 1010, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 26, in <module>
    from qtconsole.client import QtKernelClient
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\qtconsole\client.py", line 12, in <module>
    from zmq.eventloop import ioloop, zmqstream
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\zmq\eventloop\ioloop.py", line 78, in <module>
    while _IOLoop.configurable_default() is not _IOLoop:
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\tornado\ioloop.py", line 328, in configurable_default
    from tornado.platform.asyncio import AsyncIOLoop
  File "C:\ProgramData\Anaconda3\envs\coursera_Kaggle\lib\site-packages\tornado\platform\asyncio.py", line 34, in <module>
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
@qwang925 yes, this issue was introduced by the latest tornado package form the Anaconda Default Channels. We have already notified about the issue and a new package should be built soon (within some days?)

In the meantime you either install another version python like 3.7, 

```python
conda create --name coursera_Kaggle python=3.7 spyder=4
```

or if you definitely need 3.6 you could instal your packages from the conda-forge channel with:

```python
conda create --name coursera_Kaggle python=3.7 spyder=4 -c conda-forge
```

**Comment by qwang925** [comment]
@goanpeca Thank you for the quick response. If a solution could be found relatively soon, I would rather wait because I need some specific version of packages which might even introduce more issues (i.e. headache). Do you know how long it might takes to update the package, one week, one month, etc.? Thanks a lot!!

**Comment by goanpeca** [comment]
Doing this would work right away

```
conda create --name coursera_Kaggle python=3.7 spyder=4 -c conda-forge
```

Usually a couple of days. A week at most I would say.

**Comment by qwang925** [comment]
@goanpeca That's great! How may we be notified when the tornado package is updated, so we use Spyder "normally"? ^_^

**Comment by qwang925** [comment]
@goanpeca never mind. I will simply try it again one week later. Thank you for your help!!

**Comment by ccordoba12** [comment]
Closing because this can't be solved by us directly.
