### ISSUE TITLE
code completion and go to definition function break down in editor

### ISSUE THREAD

**Issue by yucheng90** [spyder-ide/spyder#11500]
## Problem Description
Code completion and go to definition function break down in editor in some cases.

### What steps reproduce the problem?

1. Use the script below
![image](https://user-images.githubusercontent.com/16459229/74084945-21802580-4aaf-11ea-98ca-3ce1fcd3a1dd.png)

2. When press 'tab' key or use keyboard shortcut for code completion after 'np.', the code completion function breaks down without any traceback. Go to definition(ctrl + left-clicking) function also breaks down. This problem only shows up in editor and doesn't happen in ipython console. 

3. The break down happens when trying to trigger code completion function in some cases but not in  all cases. Here are some examples that will break the code completion and go to definition function:
1). press 'tab' key after 'np.'
2). press 'tab' key after 'np.a'
3). press 'tab' key after 'pd.'
4). press 'tab' key after 'pd.D'
5). press 'tab' key after 'datetime.d'
6). press 'tab' key after 'scipy.'

Here are some examples that will **NOT** break the code completion and go to definition function:
1). press 'tab' key after 'time.'
2). press 'tab' key after 'np.ab'
3). press 'tab' key after 'pd.S'
4). press 'tab' key after 'pd.Da'
5). press 'tab' key after 'datetime.da'

4. Once code completion and go to definition function break down, the two function will fail in all cases.

5. The problem happens when Kite is disabled. If enable Kite, code completion will work but go to definition function(a very import function especially when script is large) still breaks down. I think code completion and go to definition function in editor should always work with or without Kite.

### What is the expected output? What do you see instead?
If code completion function works, when press 'tab' key or use keyboard shortcut for code completion after 'np.' or after 'np.a', a small window pop up and show some completion options.
![image](https://user-images.githubusercontent.com/16459229/74085243-01059a80-4ab2-11ea-9646-4cf2d71fc832.png)
Once the function breaks down, nothing happens(no pop up, no error traceback) after pressing 'tab' key. 

If go to definition functions works, left-clicking a defined function will jump to the definition of that function. In the problem above, nothing happens(no pop up, no error traceback) after left-clicking any defined function.

I tested the problem above in two computers. In one computer, I installed anaconda 2019.10 version. The default version of spyder is 3.3.9, I updated anaconda(conda update anaconda) first and then updated spyder(conda update spyder) to 4.0.1 and I got the problem above. In the other computer, I updated spyder from 3.3.3(on which the problem above doesn't show up) and update anaconda from 2019.3 version and I got the same problem.

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.3 and 3.7.4
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win7 and win10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda install parso=0.5.2

That should fix this problem.

**Comment by gulatiparidhi** [comment]
@ccordoba12  I am using Spyder 3.3.6 and facing the same issue as above. What should I do?

**Comment by Vaderv** [comment]
Any resolution to this ? 
Thank you
