### ISSUE TITLE
Unable to import streamlit 0.55

### ISSUE THREAD

**Issue by jontis** [spyder-ide/spyder#11512]
I try to import streamlit 0.55 in spyder 4.0.1 & python 3.7.
It fails with "tornado autoreload ..."
Importing streamlit in the same environment in ipython works fine.

As streamlit involves several gui components, is this an extepted collision?
Should I expect them to not be compatible at all? Or is this an issue?

**Comment by goanpeca** [comment]
@jontis could you provide the rest of the information that was requested on the issue template (when you first opened the issue?) Otherwise it is very difficult for us to debug the problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
