### ISSUE TITLE
Error when changing the Python interpreter to Python 2

### ISSUE THREAD

**Issue by PrinceFPF** [spyder-ide/spyder#11514]
## Description

I want to change the python interpreter to python2.However, an error occurred after setting.Specific steps are as follows:
**step 1.choose 'Preference' -> 'Python interpreter'**
**step 2.change the python interpreter to python2 and click the button named 'Apply' or 'OK'**

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 236, in button_clicked
    configpage.apply_changes()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 99, in apply_changes
    self.apply_callback()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 282, in <lambda>
    self.apply_settings(self.changed_options))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\preferences\maininterpreter.py", line 257, in apply_settings
    change = self.python_executable_changed(executable)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\preferences\maininterpreter.py", line 161, in python_executable_changed
    not self.warn_python_compatibility(pyexec)):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\preferences\maininterpreter.py", line 190, in warn_python_compatibility
    ) % (console_version, spyder_version), QMessageBox.Ok)
TypeError: not all arguments converted during string formatting
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Windows 7

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.8.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.16.5 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  1.4 (OK)
```

**Comment by goanpeca** [comment]
@dalthviz can you reproduce this one?

**Comment by dalthviz** [comment]
@goanpeca @PrinceFPF I'm not being able to reproduce this one. When using a Python 2 interpreter I get a warning (that refers to the use a Python 2 interpreter while Spyder is being run with a Python 3 interpreter):

![image](https://user-images.githubusercontent.com/16781833/74255122-6da1b480-4cbf-11ea-9653-8754bebc81d5.png)

@PrinceFPF could you upload a `.GIF` using something like LICECap to understand how the issue is being trigger for you? Also, how did you install the Python 2 interpreter? Did you create another env (that's the way I tested this, ensuring the other env also has all the needed dependencies like `spyder-kernels`). Any new info to reproduce this is greatly appreciated :)

**Comment by PrinceFPF** [comment]
![question-spyder](https://user-images.githubusercontent.com/11377700/74315022-84283880-4db1-11ea-9741-1a65f0f1c086.gif)
@dalthviz I have reproduced it once again. For specific operations, please see the gif picture. In addition, the following provides you with a list of my Anconda conda package manager and a list of pip.
**conda list**
[conda list.txt](https://github.com/spyder-ide/spyder/files/4190613/conda.list.txt)
**pip list**
[pip list.txt](https://github.com/spyder-ide/spyder/files/4190614/pip.list.txt)

**Comment by dalthviz** [comment]
Thanks for the feedback @PrinceFPF ! Could you also share here the list of packages (`conda list` and `pip list`) of the env you are using to launch Spyder?

Seems like the problem isn't in the env you have the kernel, and checking the initial trace back of the issue more carefully, seems like it is pointing to the installation you have in your base env.

The only thing I'm seeing is the use of a mirror to get the packages in your py2 env, but I'm unsure if that could cause some issue.

**Comment by PrinceFPF** [comment]
@goanpeca @dalthviz @ccordoba12 @maraigue Thank you very much for your help. According to your suggestions, I have temporarily switched the IDE environment to English. I look forward to future updates and fixes this BUG. I also look forward to spyder IDE getting better and better in the future.

**Comment by ccordoba12** [comment]
We'll fix this error in our next version.

**Comment by PrinceFPF** [comment]
@dalthviz @ccordoba12 Hello, I saw your PR number 11540. I tried to modify the spyder.mo and spyder.po files according to your method, which solved my problem. ,However, I also found another problem. After switching the python interpreter, the IPython kernel does not switch automatically, and the IDE must be restarted to take effect.
![question2-spyder](https://user-images.githubusercontent.com/11377700/74355192-7eeddc80-4df7-11ea-8c2a-8bbd57b41b91.gif)

**Comment by goanpeca** [comment]
@PrinceFPF you don need to restart spyder, but you do need to restart the Console Manually. 

We will add a check so we can ask users if they want to have this done for them automatically.

Have you tried retsarting the console by clicking on:

<img width="96" alt="Screen Shot 2020-02-12 at 11 34 21" src="https://user-images.githubusercontent.com/3627835/74356003-a4450100-4d8b-11ea-981e-2dddb936e16d.png">

**Comment by PrinceFPF** [comment]
@goanpeca Thank you very much. According to your suggestion, I have solved my doubts.
