### ISSUE TITLE
Ctrl-C doesn't copy to clipboard in object inspector

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1151]
_From [omegat...@gmail.com](https://code.google.com/u/104763487637795491186/) on 2012-09-16T18:53:03Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. type 'min?'
2. select some text from the docstring in the object inspector
3. press ctrl-c What is the expected output? What do you see instead? it should copy to clipboard, same as right-clicking and selecting "copy", but it does not What version of the product are you using? On what operating system? spyder 2.1.9 
windows 7 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1151_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-09-19T07:05:12Z_

I noticed this issue only on Windows (it works as expected on Linux). It's very unpleasant but it could depend on the PyQt version.

Did you install Spyder through Python(x,y)? If not, please tell us what your Qt and PyQt versions are. You can find them going to the "?" menu and selecting "About Spyder". They are at bottom of the dialog.

**Labels:** MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [omegat...@gmail.com](https://code.google.com/u/104763487637795491186/) on 2012-09-19T07:11:29Z_

Yes. Python(x,y) 2.7.2.3
Python 2.7.2, Qt 4.7.4, PyQt4 (API v1) 4.8.6 on Windows

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T14:40:23Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-04T14:57:47Z_

I can confirm this issue, hope to fix it after 2.3 is released.

**Status:** Accepted  
  **Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:52:50Z_

**Labels:** -MS-v2.3.1 MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:13:24Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:18:07Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
@blink1073, could you test if this is still a problem on Windows?

**Comment by blink1073** [comment]
Works for me.

**Comment by ccordoba12** [comment]
Ok, thanks for the confirmation. I don't know when this was fixed, so let's say it was in this release.
