### ISSUE TITLE
Autocomplete dict error

### ISSUE THREAD

**Issue by hlouzada** [spyder-ide/spyder#11526]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When pressed TAB button to autocomplete and connected to an LSP server, spyder returns an error in cursor.setPosition(completion['textEdit']['range']['start'])

### What steps reproduce the problem?

1. Connect to an LSP server
2. Open a file to edit or new
3. Request autocomplete list
4. Insert autocomplete text

### What is the expected output? What do you see instead?
It is expected that the selected autocomplete option is inserted on the current line and character, but it returns an error instead

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/home/hendrik/anaconda3/envs/fIDE5/lib/python3.8/site-packages/spyder/plugins/editor/widgets/completion.py", line 312, in keyPressEvent
    self.item_selected(item=item)
  File "/home/hendrik/anaconda3/envs/fIDE5/lib/python3.8/site-packages/spyder/plugins/editor/widgets/completion.py", line 434, in item_selected
    self.textedit.insert_completion(item.data(Qt.UserRole),
  File "/home/hendrik/anaconda3/envs/fIDE5/lib/python3.8/site-packages/spyder/plugins/editor/widgets/base.py", line 883, in insert_completion
    cursor.setPosition(completion['textEdit']['range']['start'])
TypeError: setPosition(self, int, mode: QTextCursor.MoveMode = QTextCursor.MoveAnchor): argument 1 has unexpected type 'dict'

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.8.1
* Qt version: 5.12.7
* PyQt version: 5.12.3
* Operating System name/version: Linux 5.3.0-29-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  None (NOK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting this problem. However, your description is not enough for us to reproduce this problem. In particular, this is extremely vague:

> Connect to an LSP server

What server (there are dozens of servers)? And how did you connect to it?

**Comment by hlouzada** [comment]
Sorry for the vague description, i thought that it would happen with any LSP server, because all of them uses the same protocol. The server that I am using is the one provided by my extension, the F server, it should be automatically configured if you install the extension. I am providing an link to download below.

[Download extension](https://drive.google.com/file/d/1OntIvcKiu0C7bsRXwYVNxMh1lsyeu0vm/view?usp=sharing)

Thank you for your reply.

**Comment by ccordoba12** [comment]
> I am providing an link to download below.

Thanks!

@andfoy, please try to reproduce this one.

**Comment by andfoy** [comment]
@hlouzada Thanks for the information, I'm wondering how are you implementing the ``textDocument/completion`` call

**Comment by hlouzada** [comment]
Hi @andfoy I am currently using the xtext with the lsp4j implementation for the language server. When `textDocument/completion` is called it should return something like this:

```
{
    'isIncomplete': True,
    'items': [{
        'label': 'shim',
        'kind': 14,
        'sortText': '00000',
        'textEdit': {
            'range': {
                'start': {'line': 24, 'character': 4},
                'end': {'line': 24, 'character': 5}
            },
            'newText': 'shim'
        }
    },{
        'label': 'start',
        'kind': 14,
        'sortText': '00001',
        'textEdit': {
            'range': {
                'start': {'line': 24, 'character': 4},
                'end': {'line': 24, 'character': 5}
            },
            'newText': 'start'
        }
    }]
}
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at the last @hlouzada comment.
