### ISSUE TITLE
Lost file at crash.

### ISSUE THREAD

**Issue by AdrienMau** [spyder-ide/spyder#11523]
### What steps will reproduce the problem?

Spyder crashed, or my laptop shutted down.
When reopening spyder i get a warning message that spyder does not load and i may need to reset.
I go to spyder installation folder and click spyder-reset.
Then... on opening of spyder, i realize my script file is now completely empty and i have lost three days of work.

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.6
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by jitseniesen** [comment]
Your version of Spyder is quite old. From version 4, Spyder includes an autosave mechanism which should be able to recover from crashes, so please upgrade.
