### ISSUE TITLE
Spyder 4.0.1 crashing after 2-3 hours

### ISSUE THREAD

**Issue by DanyEle** [spyder-ide/spyder#11525]
## Problem Description

I'm a great fan of the Spyder IDE, and I've been using it for over a year now. 

Yesterday, I got a new computer at my office and installed the latest version of Spyder, and Spyder 4.0.1 was automatically installed with the command:

`pip install spyder`

I've been using Spyder for the whole day yesterday, and after about 2-3 hours of intense usage the IDE completely got stuck, and I was forced to close it down. Same thing happened this morning. Not sure if this helps, but in both cases I had two instances of spyder open at the new same.

*OS* Windows 10
*Python version* : 3.7.4

In the meantime, I will revert to the good old spyder3, which does not cause the same issue to happen.

### What steps reproduce the problem?

1. Run 1 spyder instance
2.  Run another spyder instance
3. Work with it for 2-3 hours
4. Wait for it to crash.

### What is the expected output? What do you see instead?

I would expect Spyder not to get stuck and force me to close it.

## Versions
* Spyder version:  4.0.1.
* Python version: 3.7.4
* Qt version: 5.12.7
* PyQt version: 5.12.3
* Operating System name/version:  Windows 10 64-bit

### Dependencies
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.8 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.16.4 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ccordoba12** [comment]
Besides, several fixes will be available in our next version (4.1.0) that should improve or totally this situation.

**Comment by DanyEle** [comment]
Great, eagerly waiting for version 4.1.0!! Which version would be installed if I were to get Spyder from anaconda?

**Comment by ccordoba12** [comment]
You need to run

    conda install spyder=4.0.1
    conda install parso=0.5.2

**Comment by DanyEle** [comment]
Same issue occurred using spyder=4.0.0 with pip.

Solved it using by installing conda and installing spyder3.3.6 with the command:

`conda install spyder`

**Comment by DanyEle** [comment]
Also, just as a general suggestion, spyder3.3.6 just feels smoother and way more responsive than spyder4.0.1 or spyder4.0.0. It may be useful to try and improve these aspects of spyder4.
