### ISSUE TITLE
fuzzy autocompletion.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11535]
Hi,

Can you let the spyder support fuzzy autocompletion instead of beginning-based completion.

Say, for pycurl,  the following:

```
import pycurl
pycurl.time<tab>
```

Should you let it also give suggestions such as:  

pycurl.CONNECT_TIME

Regards

**Comment by goanpeca** [comment]
Closing as duplicate of https://github.com/spyder-ide/spyder/issues/2374

**Comment by hongyi-zhao** [comment]
It seems it still in progress, and not implemented currently.

**Comment by ccordoba12** [comment]
It will be implemented in a couple of months.
