### ISSUE TITLE
Using "Go to definition" does not works for tensorflow packages 

### ISSUE THREAD

**Issue by colt18** [spyder-ide/spyder#11553]
I'm a ML pracititioner and using Spyder since 2017. Back then when doing my CNN stuff, I was using keras as a wrapper for tensorflow. They were seperate packages and autocomplete and go to function definitions of keras imported modules were working fine. I mean I could simply go to function definition of lets say Conv2D in `from keras.layers import Conv2D `, by just `ctrl+click` or `ctrl+g` the Conv2D text. 

Since tf 2.0 keras is a submodule of tf ecosystem and it is loaded by some kind of "lazy import" or "module load" stuff or whatever sth that I don't have any idea. So the correct way of importing keras submodules is now the statement `from tensorflow.keras.layers import Conv2D`. But the problem here is sypder can't go to function definiton because there is no `keras.layers.Conv2D` under `tensorflow` cuz it actually resides under `tensorflow_core.python.keras.Conv2D` and imported by means of explained above. So the question is, Instead of typing `tensorflow_core.python.keras.Conv2D` to make use of go to function definiton of `Conv2D`, are there any ways that `from tensorflow.keras.Conv2D` can go to function definition.

Thanks.

**Comment by goanpeca** [comment]
@andfoy do you have some ideas here?

**Comment by andfoy** [comment]
This is an open issue on most Deep Learning libraries, which have extensive and complex compilation systems. For instance, PyTorch is now including ``.pyi`` typing files for this purpose. 

Sadly, we cannot do much about this besides recommending the user to ask for ``.pyi`` files for TF/Keras or use Kite instead.

**Comment by ccordoba12** [comment]
> or use Kite instead.

I agree. That's the best we can do at the moment, i.e. recommending Kite if you want better code completion for Tensorflow.

**Comment by colt18** [comment]
Kite is doing fine with "auto complete" feature, but still "go to function definiton" is unaccessible.
