### ISSUE TITLE
Spyder Autocomplete

### ISSUE THREAD

**Issue by aryankhatana01** [spyder-ide/spyder#11563]
How do i Turn on the spyder autocomplete feature because i have installed kite and everytime i have to press ctrl+space to see the results. How do i see them while typing?

**Comment by dalthviz** [comment]
Hi @aryankhatana01 to change the completions preferences you will need to open the Preferences dialog by either clicking the wrench button 🔧 , going to the menu `Tools > Preferences` or using the shortcut `Ctrl + Alt + Shift + P`.

Then, go to the section  `Completion and linting` and there you can enable the option `Show completions on the fly`. Also, be sure of setting the appropriated values for the number of characters and keyboard idle to show the automatic completions that suits you the best:

![image](https://user-images.githubusercontent.com/16781833/74597470-fefd8780-502d-11ea-82b0-4b8f8a60540d.png)
