### ISSUE TITLE
Unable to start Spyder from bootstrap.py

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#11560]
After PR #11350 I get this error when trying to start from the `bootstrap.py`:

### Paste Traceback/Error Below (if applicable)

```python-traceback
(spyder_dev2) D:\Desktop>python C:\Users\User\spyder\bootstrap.py
Executing Spyder from source checkout
Revision aa9fdaf73, Branch: spyder-ide/master
01. Patched sys.path with C:\Users\User\spyder
Traceback (most recent call last):
  File "C:\Users\User\spyder\bootstrap.py", line 133, in <module>
    for path in os.listdir('external-deps'):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'external-deps'
```

I don't know if this is a problem with my own setup, but maybe we might want to enclose the following 2 blocks of code under a `if osp.exists(<path>)` condition to prevent this error.

https://github.com/spyder-ide/spyder/blob/9716eb1e6c94c08a692cd00136ed83db81985978/bootstrap.py#L131-L137

https://github.com/spyder-ide/spyder/blob/9716eb1e6c94c08a692cd00136ed83db81985978/conftest.py#L25-L30

## Versions
* Spyder 5.0.0.dev0 (Commit: aa9fdaf73) 
* Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by jnsebgosselin** [comment]
This was already fixed 2 days ago in https://github.com/spyder-ide/spyder/pull/11541.

**Comment by ccordoba12** [comment]
So, is it fixed for you now with the latest master?

**Comment by jnsebgosselin** [comment]
> 
> 
> So, is it fixed for you now with the latest master?

Yes, it is working fine with the fix you implemented.

**Comment by ccordoba12** [comment]
Great to know!
