### ISSUE TITLE
Code analysis pops error too fast then never clears

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#11566]
## Problem Description

When editing code, the IDE frequently flags an error 'undefined name' for a partially typed variable, then the red flag in the margin won't clear even when the code is correct.

### What steps reproduce the problem?

1.  Editing code.  Say, model_data is a valid pandas DataFrame
2.  Begin typing a line that references model_data
3.  IDE shows error as:

![image](https://user-images.githubusercontent.com/30508983/74596877-69083380-5012-11ea-9c85-ee16de1f191d.png)

### What is the expected output? What do you see instead?

1) Don't throw the error so fast
2) Properly clear the error

### Paste Traceback/Error Below (if applicable)

```
no errors or traceback

```

## Versions

Spyder 4.0.1 
Python 3.7.6 64-bit
Qt 5.9.6
PyQt5 5.9.2
Windows 10 

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.13 (OK)
matplotlib >=2.0.0           :  2.2.3 (OK)
numpy >=1.7                  :  1.17.4 (OK)
pandas >=0.13.1              :  0.25.1+0.g171c716.dirty (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

```

**Comment by ccordoba12** [comment]
I'm almost sure this will fixed in our next release (4.1.0). Please report back if that's the case or not when that release is out.
