### ISSUE TITLE
Sypder update problem

### ISSUE THREAD

**Issue by aryankhatana01** [spyder-ide/spyder#11570]
I updated my anaconda but it downgraded my Spyder version from 4.0.1 to 3.3.6. Now I am trying to update just Spyder by conda update spyder, it says that #All required packages installed but is still on spyder 3

**Comment by ccordoba12** [comment]
Duplicate of #11550

**Comment by aryankhatana01** [comment]
Hello, I had a look at the issue #11550 but couldn't find the solution...how do I fix it??

**Comment by dalthviz** [comment]
@aryankhatana01 try running `conda install spyder=4.0.1` as https://github.com/spyder-ide/spyder/issues/11550#issuecomment-586645800 suggests. If you need more info or you want to give some feedback regarding this, please add a comment in #11550
