### ISSUE TITLE
Spyder not launching after update 

### ISSUE THREAD

**Issue by Klumpfisk** [spyder-ide/spyder#11597]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder crashing upon startup.

I have just installed anaconda3 on this computer (a first time install), and updated anaconda and spyder to the newest versions. Initially it worked fine, but having forgotten numpy, I closed down, and installed it. When trying to open spyder4 again it would not work. I have restarted my pc, uninstalled and reinstalled anaconda and spyder a few times, and never have I gotten spyder to open again.

### What steps reproduce the problem?

1. Fresh install of conda from website (64-Bit Graphical Installer for python 3.7)
2. In the conda prompt write `conda update anaconda` followed by `conda install spyder=4.0.1`
(Note to 2: When updating anaconda it'll post some debugging lines, and when installing spyder it'll fail with initial frozen solve to solve the environment and commence debugging at the end - see screenshots for all) 
3. Run `spyder --reset`
4. Launch spyder

### What is the expected output? What do you see instead?
Pops up with the traceback instead of opening spyder.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "F:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "F:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "F:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "F:\Anaconda\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "F:\Anaconda\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 141, in start
self.kite_process = run_program(path)
File "F:\Anaconda\lib\site-packages\spyder\utils\programs.py", line 214, in run_program
return subprocess.Popen(fullcmd, **subprocess_kwargs)
File "F:\Anaconda\lib\subprocess.py", line 775, in __init__
restore_signals, start_new_session)
File "F:\Anaconda\lib\subprocess.py", line 1178, in _execute_child
startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application


```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.4 (also tried 3.7.6 with no change)
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
I'm assuming this is if spyder is launchable - which it isn't for me. (cannot find this)
```

### Pictures of prompt window (from note to 2)
![updating conda](https://user-images.githubusercontent.com/61242596/74856295-36c44200-5342-11ea-813c-b04580484926.png)
![installing spyder](https://user-images.githubusercontent.com/61242596/74856293-36c44200-5342-11ea-87f7-d7c863016047.png)
![installing spyder 2](https://user-images.githubusercontent.com/61242596/74856291-362bab80-5342-11ea-8d16-6c8eecb75c9c.png)

**Comment by ccordoba12** [comment]
If you have Kite installed, please uninstall it. That should solve your problem.

@dalthviz, do you know what's happening in this case?

**Comment by Klumpfisk** [comment]
> If you have Kite installed, please uninstall it. That should solve your problem.

When I first launched spyder (the time it worked) it asked if I wanted to install Kite, which I just accepted. The install failed and installer closed, and I thought nothing more of it. I cannot find kite using Window's add/remove programs feature, so I don't know if there are some files from it remaining from the failed install.

**Comment by dalthviz** [comment]
@ccordoba12 I'm not sure but maybe some how the failed installation make available the service that Kite uses while actually not being installed?

@Klumpfisk could you check if there is Kite related processes running in your machine? Also, could you try to download the installer manually (available [here](https://kite.com/download/)) and try to install Kite?. For example, when I run the installer I get the following message:

![image](https://user-images.githubusercontent.com/16781833/74865532-3fefe780-531f-11ea-9db2-41e48053273d.png)

Maybe by running the installer we can get more info?

**Comment by Klumpfisk** [comment]
Okay, so it seems kite has made a folder on my machine with that path, however it doesn't have an uninstaller. I get the same message when trying to install kite. I'll try to manually remove the folder and check it (I'll need to install a few things again as I reinstalled conda and used the 3.3.6 version of python)

**Comment by Klumpfisk** [comment]
Alright, that fixed it.
Thanks a lot, would've never found this on my own :)

**Comment by dalthviz** [comment]
Thanks for the patience to reinstall and install everything @Klumpfisk ! Glad you could make it work :)

**Comment by dalthviz** [comment]
@ccordoba12 maybe we need to add at least a message regarding failed installations and the need of a manual (or automatic) deletion of remaining files?

**Comment by ccordoba12** [comment]
> maybe we need to add at least a message regarding failed installations and the need of a manual (or automatic) deletion of remaining files?

Definitely, please open a PR for that.

**Comment by 1CoreBrain** [comment]
> Thanks for the patience to reinstall everything @Klumpfisk ! Glad you could make it work :)

Hi, I have met the same problem. I tried to uninstall Kite before upgrading spyder. I found the first step of uninstallation of Kite is to uninstall plugins. The expected interface would be like this:
![image](https://user-images.githubusercontent.com/53115881/75077074-9a44a000-54f9-11ea-889f-bcbe0c9d9ec9.png)

However what is shown on my PC is:
![image](https://user-images.githubusercontent.com/53115881/75077120-bea07c80-54f9-11ea-9180-ae9125e97497.png)

Plugins for Spyder is shown on the 'installed editor plugins' part but there is no uninstall button.

What should I do to uninstall the plugin?

**Comment by dalthviz** [comment]
Hi @1CoreBrain in your case, as Kite Copilot mentions, the thing is that you are using Spyder version `3.3.6`. If you want to use Kite inside Spyder, please update to Spyder 4 which is the version that supports Kite (if you use Anaconda you can update running something like `conda install spyder=4.0.1`)

**Comment by ccordoba12** [comment]
@1CoreBrain, your problem was adequately answered by @dalthviz. Please don't add more comments on this issue about it because it's really unrelated to what @Klumpfisk reported initially.

**Comment by 1CoreBrain** [comment]
> @1CoreBrain, your problem was adequately answered by @dalthviz. Please don't add more comments on this issue about it because it's really unrelated to what @Klumpfisk reported initially.

Hi, sorry for that, I think I did not say it clearly.

My question is how to UNINSTALL Kite instead of using it.

The thing is when I want to UPDATE the Spyder to 4.0.1, I got EXACTLY what Klumpfisk has met, like:
![image](https://user-images.githubusercontent.com/53115881/75088870-a7d64600-554a-11ea-99d6-3a5458685c7d.png)

And I was looking for help and found this discussion. As @dalthviz said, Kite should be uninstalled before updating Spyder. However, I met a problem when I was trying to uninstall Kite, which I have mentioned before.

Following the uninstallation step below, I need to uninstall the Spyder plugin first.
![image](https://user-images.githubusercontent.com/53115881/75088962-b5d89680-554b-11ea-9dfb-c9fd90d981e2.png)

However, there is no UNINSTALL button when I try to uninstall the Spyder plugin, I even don't know whether it is installed.
![image](https://user-images.githubusercontent.com/53115881/75089028-76f71080-554c-11ea-9e24-ace40c331bd0.png)

Hence I wrote a comment on this issue because I meet the same problem as @Klumpfisk reported and met a problem when following the suggestion of @dalthviz.

**Comment by ccordoba12** [comment]
@1CoreBrain, please look at the directory shown @Klumpfisk's last screenshot above and remove it.

**Comment by 1CoreBrain** [comment]
> @1CoreBrain, please look at the directory shown in @Klumpfisk's last screenshot above and remove it.

Alright, thanks a lot. Spyder works again.

**Comment by ccordoba12** [comment]
Great to hear!

**Comment by elahedaneshmand** [comment]
hi
i have same problem as you. i uninstal kite but spyder not launching yet.
