### ISSUE TITLE
Options for different modes of documentation are not available when the Help Pane is undocked. 

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#11591]
## Problem Description
 
Options for the pane's menu are deactivated when the pane is undocked

![Screen Shot 2020-02-18 at 2 52 19 PM](https://user-images.githubusercontent.com/18587879/74772703-829dbb00-525e-11ea-85e1-6ac2ac31317f.png)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment]
@ccordoba12 @dalthviz

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one ASAP.
