### ISSUE TITLE
plse help me to solve this problem

### ISSUE THREAD

**Issue by arshif685** [spyder-ide/spyder#11599]
not able to sove this 
runfile('D:/Projects/cameradistance.py', wdir='D:/Projects')
![error](https://user-images.githubusercontent.com/60957363/74872093-92aebb00-5382-11ea-987a-91a8b9463645.png)
![error](https://user-images.githubusercontent.com/60957363/74872220-d86b8380-5382-11ea-8bbe-b1cc99e42e3c.png)

**Comment by bcolsen** [comment]
This error is a result of using tabs and spaces in your python program. 

You can try `Source -> Fix indentation` or you can use `source -> show blank spaces` to see tabs as arrows and spaces as dots. You want everything to be a dot.

I am closing bug report because this is not a Spyder bug
