### ISSUE TITLE
Auto-completion should not complete already complete words

### ISSUE THREAD

**Issue by ElieGouzien** [spyder-ide/spyder#11600]
## Problem Description
Auto-completion (without kite, maybe also with, but I didn't test) propose to complete already complete words.

### What steps reproduce the problem?
Use LSP auto-completion (not tested with kite).

Write
```
something = 1
something
```
and wait. Auto-completion propose `something`

### What is the expected output? What do you see instead?
I would expect auto-completion to disappear when I write entirely what I wanted to.
It's not a major bug, but quite annoying.

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Jedi version: 0.14.1
*  python-language-server version: 0.31.8

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by goanpeca** [comment]
If the prefix matches something on the retuned completion options, do not show it.

**Comment by ElieGouzien** [comment]
I think in the ideal case I would expect something a little more complicated (but faster to run):
1. if there is only one possible completion and it matches the prefix, I expect the completion to be hidden (or closed)(see example in first comment);
2. if several completions are possible, I expect in this case to propose completion for the already complete word (as it work now).

The example bellow should make things clearer for the 2.:
```python
some = 1
something = 2
some
```
In that case I expect completion to propose `some` and `something` so that user can know `some` is a possible choice (showing only `something` would be confusing).
