### ISSUE TITLE
plt.close('all') is not working

### ISSUE THREAD

**Issue by xing1014** [spyder-ide/spyder#11607]
### Issue Report Checklist

* [*] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ N/A] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ N/A] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ *] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [ N/A] Reset preferences with ``spyder --reset``
    * [ *] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ *] Tried the other applicable steps from the Troubleshooting Guide
* [* ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

plt.close('all') not working in spyder

I have a script that produces a lot of plots in the viewer and I would like to close them all at one. I have tried plt.close('all') but it does not work. I have written a simple script below to demonstrate my problem. With this script I still cannot close the one figure it produces. Any help is appreciated, thanks in advance!

### What steps reproduce the problem?

import matplotlib.pyplot as plt

plt.title('test')
plt.show()
input("Press Enter to continue...")
plt.close('all')

### What is the expected output? What do you see instead?

I expect the plot to show after the plt.show() line, and then close after giving the input, but the plot stays in the view

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.0 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
> I have a script that produces a lot of plots in the viewer

What viewer? Please be more specific.

**Comment by xing1014** [comment]
> > I have a script that produces a lot of plots in the viewer
> 
> What viewer? Please be more specific.

In the spyder IDE, there is a Plots pane where my plots display. My goal is to just close all the plots in this pane at once.

**Comment by ccordoba12** [comment]
It's not possible to do that via a code statement. You need to manually press the button that appears below to remove all plots from history

![Selección_001](https://user-images.githubusercontent.com/365293/74972897-8c572800-53f0-11ea-95e1-0be232dac7a6.png)

Another alternative is for you to restart the console's kernel manually:

![Selección_002](https://user-images.githubusercontent.com/365293/74972989-ae50aa80-53f0-11ea-96d2-b6945dbcc536.png)

**Comment by emilyt-nist** [comment]
It would be nice to be able to programmatically close plots to keep them from taking up lots of memory.  I realize I could instead not show them in the first place.  But sometimes that is not what I want.

**Comment by ccordoba12** [comment]
@emilyt-nist, do you mean closing figures generated with a Matplotlib interactive backend (i.e. that are shown in separate windows)? Or removing figures from Spyder's Plots pane?

**Comment by emilyt-nist** [comment]
I would like to be able to programatically remove figures from Spyder's Plots pane to free up memory.

**Comment by ccordoba12** [comment]
Ok, I think that's a good idea. Could you open a new issue about that? We'll try to implement it for 6.2.0, to be released next year.

Unfortunately, it's not possible to do it in a 6.1.x version because it requires changes to both Spyder and Spyder-kernels that need to be in sync.
