### ISSUE TITLE
Spyder won't launch

### ISSUE THREAD

**Issue by maiiasleptcova** [spyder-ide/spyder#11604]
### Issue Report Checklist

* [ +] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ +] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ +] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ +] Restarted Spyder
    * [ +] Reset preferences with ``spyder --reset``
    * [ +] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ +] Tried the other applicable steps from the Troubleshooting Guide
* [ +] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just downloaded the latest version of Anaconda from anaconda website and installed it. When I start Anaconda Navigator, it takes 6 minutes to launch. When I click on Spyder, it won't launch. I just see in the beginning a couple of command prompt windows opening and closing very quickly and that's it. 

Uninstalled and installed Anaconda again - didn't work. 
Ran spyder --reset in Anaconda prompt, and the notification popped up "Python has stopped working". 

Tried conda update spyder, but I see an error:

```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))
```

I can access https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json and https://www.anaconda.com from the browser.

I added Anaconda, python and spyder to the list of apps allowed through Window Firewall. 

This is a company computer, however, everything's working fine for two of my colleagues, and I am the only person for whom it's not working. 

### What steps reproduce the problem?

1. Opening Anaconda Navigator
2. Clicking on Spyder

### What is the expected output? What do you see instead?
Launch Spyder
Instead nothing happens

## Versions

* Spyder version:   3.3.6
* Python version: 3.7.4
* Qt version: 5.9.7
* PyQt version:   5.9.2
* Operating System name/version: Windows 10 Enterprise, version 1607

**Comment by dalthviz** [comment]
Hi @maiiasleptcova could you try running from an Anaconda prompt `spyder --debug-info verbose` and paste here what you get? Maybe with that we can get a better understanding of the issue here. Thanks!

**Comment by maiiasleptcova** [comment]
thanks @dalthviz , here's the output

```
Usage: spyder [options] files

spyder: error: no such option: --debug-info
```

**Comment by dalthviz** [comment]
Oh sorry @maiiasleptcova my mistake, since you are running Spyder 3 you need to do the following:

1.  Set the env variable `SPYDER_DEBUG` to 3 running this: `set SPYDER_DEBUG=3`
2.  Run Spyder from the console.

**Comment by maiiasleptcova** [comment]
That's what pops us:
![image](https://user-images.githubusercontent.com/17163595/74947178-66cb1e00-53f2-11ea-90ba-8f2733b19a17.png)

**Comment by dalthviz** [comment]
@maiiasleptcova is anaconda the only python installation that you have? (it seems strange to me the path that's being referenced for the `pythonw.exe` executable).  Did you install anaconda just for your user or system wide?

Also, a couple of things that maybe could help:

* Maybe you can run from a cmd and also from the anaconda prompt `where python` to check the path that the system is getting Python.
* Try to create an env with `conda` from the anaconda prompt, something like `conda create -n spyder spyder=3.3.6` (if it fails, then something beyond Spyder is happening here, and maybe is related to your Python installation itself).

Any new info it's greatly appreciated in order to understand what's happening here :)

**Comment by maiiasleptcova** [comment]
@dalthviz yes, anaconda is the only python installation, installed only for one user (me)

from cmd:

`INFO: Could not find files for the given pattern(s).`

from anaconda prompt:

`C:\Users\Sleptcom\AppData\Local\Continuum\anaconda3\python.exe`

output from running 

`conda create -n spyder spyder=3.3.6 `

is:

```
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'tls_process_server_certificate\', \'certificate verify failed\')])")))'))

```
 As before, I can access the links above from the browser without any problem.

**Comment by dalthviz** [comment]
@maiiasleptcova maybe your company uses a proxy (and your browser has it configured but such config is missing for your anaconda installation)? If that is the case, maybe you could try to [config Anaconda to use it](https://docs.anaconda.com/anaconda/user-guide/tasks/proxy/), although, I'm unsure of how that could be causing Spyder to not start :/

@ccordoba12 do you know if having a proxy set in a machine could cause Spyder to being unable to start?

**Comment by ccordoba12** [comment]
> do you know if having a proxy set in a machine could cause Spyder to being unable to start?

It shouldn't be an issue.

> This is a company computer, however, everything's working fine for two of my colleagues, and I am the only person for whom it's not working.

I'm sorry @maiiasleptcova but that's all the help we can offer you. Please consult with your IT department because this looks like an issue with your computer and not with Spyder.
