### ISSUE TITLE
Why is spyder trying to determine if files in my home folder are binaries or not?

### ISSUE THREAD

**Issue by ArchangeGabriel** [spyder-ide/spyder#11624]
While getting log for #11623, I saw groups of lines like this (I’ve removed them in the other ticket for privacy reasons):
```
[spyder.utils.external.binaryornot.check] -> is_binary: '/home/<user>/.zshrc'
[spyder.utils.external.binaryornot.helpers] -> nontext_ratio1: 0.0029296875
[spyder.utils.external.binaryornot.helpers] -> nontext_ratio2: 0.9970703125
[spyder.utils.external.binaryornot.helpers] -> is_likely_binary: False
```
And thus for every file in my home folder, even if the folder I ran spyder from wasn’t my home.

Why does spyder cares about the binarity of files in my home?

**Comment by goanpeca** [comment]
What was the CWD you had in both cases? starting Spyder from a given directory does not mean the current workin directory will be THAT directory.

So probably Spyder default CWD is the user home directory.

**Comment by ccordoba12** [comment]
> So probably Spyder default CWD is the user home directory.

Actually, it is @goanpeca.

> Why is spyder trying to determine if files in my home folder are binaries or not?

@ArchangeGabriel, that happens because we need to associate the right icon per file in the `Files` pane.

**Comment by ccordoba12** [comment]
By the way, I closed this issue because I think there's nothing else to discuss @ArchangeGabriel since I answered your question.

**Comment by ArchangeGabriel** [comment]
Yes, it’s fine, I’m just surprised the CWD is the home and not the directory from which spyder is ran.
