### ISSUE TITLE
Problems with matplotlib in Spyder 4.0.1--"Module not found"

### ISSUE THREAD

**Issue by NerdyJock** [spyder-ide/spyder#11636]
I just updated to Spyder 4.0.1, but now I'm getting an error stating that matplotlib.pyplot isn't a module. Did something change? 

I'm running on Windows

![20200223_214435](https://user-images.githubusercontent.com/61167799/75128371-5ed8db80-5689-11ea-9d46-cc484c307e45.jpg)

**Comment by goanpeca** [comment]
@NerdyJock please provide the information that was requested when you first opened this usue, otherwise we cannot help.

**Comment by ccordoba12** [comment]
Please also see [our guide](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder) to learn how to solve this kind of problems.

**Comment by goanpeca** [comment]
No updates were received. Closing.

**Comment by NerdyJock** [comment]
Sorry, I figured it out...well, sort of. I got it working, just don't know
why it didn't.
