### ISSUE TITLE
Get list of cell code of my .py file

### ISSUE THREAD

**Issue by DidierCrab** [spyder-ide/spyder#11639]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hello,
First, many thanks for Spyder, it's so useful !
I just want to know if it is possible to get a list of cell code of my .py file. They are sometimes long (more than 1000 lines) and it would be useful to get an overview of the content of the file

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.6 (downgraded from 4 due to specific modules) with anaconda
* Python version: Python 3.7.5 64-bit 
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
>get a list of cell code of my .py file.

You mean the amount of cells in your code and name if the cell has a name?

**Comment by DidierCrab** [comment]
Hello,
Thanks for your reply,
with Spyder 4.0, I can use runcell to run cell code by index or by name (and this is very useful).
My question was to know if it is possible to get the list of the different code cells of my .py files.
As an example, it could be a command to parse a py file and get list of tuples as :
[(index, 'title'),
(0,'imports'),
(1,'data analysis'),
(2,'graphs')
(3,'export to pdf')]
Hope to be clear
Thanks again

**Comment by goanpeca** [comment]
@bcolsen @impact27 thoughts?

**Comment by impact27** [comment]
- The `cell_count()` function gives you the number of cells
 - The outline explorer shows the cells
 - You can write a small script with regexes and:
```python
def get_code_cell_name(text):
    """Returns a code cell name from a code cell comment."""
    name = text.strip().lstrip("#% ")
    if name.startswith("<codecell>"):
        name = name[10:].lstrip()
    elif name.startswith("In["):
        name = name[2:]
        if name.endswith("]:"):
            name = name[:-1]
        name = name.strip()
    return name
```

**Comment by DidierCrab** [comment]
Thank you !
I didn't know the cell_count function and the outline explorer which looks to be very useful.
I'm not sure to understand the small script. I see the way to split the text variable, but how to get the title of the code cell ? it's not clear for me.
I think we can close this topic.
Thanks again

**Comment by impact27** [comment]
> Thank you !
> I didn't know the cell_count function and the outline explorer which looks to be very useful.
> I'm not sure to understand the small script. I see the way to split the text variable, but how to get the title of the code cell ? it's not clear for me.
> I think we can close this topic.
> Thanks again

The script is from the source of spyder. It is a bit of logic that transforms a cell comment to a cell name. (`# %% Name` -> `Name`). If you want to implement something yourself to parse the files this might be useful.
