### ISSUE TITLE
Spyder 4 crashes (seg fault) on launch over SSH w/ X11 forwarding

### ISSUE THREAD

**Issue by vawalker** [spyder-ide/spyder#11648]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder crashes on launch when run on a remote machine w/ X11 forwarding after updating to version 4 (v4.0.1). Previous spyder version (v3.3.6) opened as expected. Qt version held at 5.6.3 as more recent versions result in qt.glx errors when attempting to forward.

EDIT: I am unable to personally update conda as I do not have privileges to make changes that affect other users on the remote. To resolve this I've set conda-forge as my priority channel. 

### What steps reproduce the problem?

1. Connect to remote machine via ssh -X
2. ``spyder &``

### What is the expected output? What do you see instead?

Expected: Spyder opens on local machine.
Actual: Spyder crashes when the splash screen transitions to the main window.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Unable to access View > Panes > Internal Console
Terminal indicates Segmentation Fault.

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.6.7
* Qt version: 5.6.3
* PyQt version: 5.6.0
* Operating System name/version: CentOS 7 (remote), Ubuntu 18.04 (local)

### Dependencies

```

Unable to access Help > Dependencies

```

**Comment by bcolsen** [comment]
You can try `spyder --opengl=software`

It dosen't work for me however:
```bash
~$ spyder --opengl=software
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Could not initialize GLX
Aborted (core dumped)
```

**Comment by ccordoba12** [comment]
> To resolve this I've set conda-forge as my priority channel.

This is going to be fixed in Spyder 4.0.1

> It dosen't work for me however

What's your Qt version @bcolsen?

**Comment by vawalker** [comment]
@ccordoba12 I'm using Spyder 4.0.1 when I get the seg fault on launch.
``spyder                    4.0.1                    py36_3    conda-forge``

@bcolsen  ``spyder --opengl=software`` results in a seg fault on launch as well.

**Comment by bcolsen** [comment]
> What's your Qt version @bcolsen?

qt-5.9.7 on the remote server.

**Comment by ccordoba12** [comment]
@vawalker, sorry, I meant 4.1.0.

**Comment by vawalker** [comment]
@ccordoba12 Thank you for your help; I'll downgrade back to 3.3.6 in the meantime. Is there an ETA for 4.1.0 to be released to conda-forge?

**Comment by ccordoba12** [comment]
A couple of weeks from now.
