### ISSUE TITLE
Crashes Changing Window Layout

### ISSUE THREAD

**Issue by mckayb512** [spyder-ide/spyder#11643]
### What steps will reproduce the problem?

I don't know how to reproduce this problem.  Somehow I got my window configuration into a state that causes Spyder to crash.  I tried adding a horizontal split to my source file...I think that may have been it.  After crashing the first time, some of the windows I usually use got hidden somehow, so I tried 'View -> Window Layouts -> Spyder Default layout' to reset the window configuration to the default.  This crashed Spyder again.  Similarly, setting it to the Matlab default crashes spyder.  The problem persists--changing the window layout causes Spyder to crash, even if it's the first thing I do after launching Spyder.

Likely there's an .ini file somewhere that I should delete.  This is why I don't know how to reproduce...whatever I did was likely done long in the past.  I'd submit that .ini file with this bug report if I knew where it was.

### Traceback
```python-traceback
TypeError: _start_server() missing 1 required positional argument: 'port'
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.8.0
* PyQt5 version: 5.8.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by mckayb512** [comment]
Aha..this might be the .ini file
C:\Users\mckay\.spyder-py3\spyder.ini

(attached, modified extension to .txt since this page reports 'We don't suport that file type' for .ini files)
[spyder.ini.txt](https://github.com/spyder-ide/spyder/files/4247437/spyder.ini.txt)

**Comment by goanpeca** [comment]
You are using an old version of Spyder. Please update to 3.3.6 or update to 4.0

**Comment by ccordoba12** [comment]
This error was fixed a long time ago (two years). Please update.
