### ISSUE TITLE
IPython call preview shows nonexistent kwarg

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11640]
`import pandas as pd; df = pd.read_csv(...)`

![image](https://user-images.githubusercontent.com/16495490/75174584-48468900-574a-11ea-830b-65add18079ba.png)

**Comment by goanpeca** [comment]
Are you using kite?

**Comment by OverLordGoldDragon** [comment]
@goanpeca No, it is off

**Comment by ccordoba12** [comment]
Please at least report what Pandas version you're using.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 `0.25.3`; apparently there's a `>1.0` now, which `conda` failed to install for some reason - guess I should upgrade

**Comment by OverLordGoldDragon** [comment]
`conda update pandas` - I'll pass

<img src="https://user-images.githubusercontent.com/16495490/75190338-869f7080-5769-11ea-8005-9f1a18d03f76.png" width="500">

**Comment by OverLordGoldDragon** [comment]
This is ancient and I've not had the same problem since
