### ISSUE TITLE
Spyder hangs 30 secs on runfile command

### ISSUE THREAD

**Issue by jennirinker** [spyder-ide/spyder#11642]
### Issue Report Checklist

Not a bug, so I skipped basic troubleshooting.

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When running a file in Spyder using F5, Spyder hangs for approximately 30 seconds before finally executing the file. Running a cell occurs instantly. The problem persists in version 4 of spyder. However, I think the problem only occurs on certain wifi connections, so this could be related to my virus scanner. But then I don't understand why `runfile` would hang but a cell executes instantly.

### What steps reproduce the problem?

1. Be connected to my home wifi instead of work wifi or no wifi.
2. Open any script in spyder.
3. Hit F5.
4. Do some stretches while I wait for Spyder to stop "being busy".
5. Finally I get to see the error messages because I left a bug in the script.
6. Rinse and repeat.

Not sure if relevant, but I generally run a python kernel that is in a different environment from Spyder. But the problem persists even if I use the default kernel.

### What is the expected output? What do you see instead?

As mentioned in the description, the problem is exclusively when using `runfile`. Running a cell in Spyder 3 or using `runcell` in Spyder 4 work instantaneously.

## Versions

* Spyder version: 3.36
* Python version: Python 3.7.2 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 Enterprise

### Dependencies

```
IPython >=4.0     :  7.12.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.16.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.24.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.5.2 (OK)
pylint >=0.25     :  2.4.4 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
rope >=0.9.4      :  0.16.0 (OK)
sphinx >=0.6.6    :  2.4.0 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
> However, I think the problem only occurs on certain wifi connections, so this could be related to my virus scanner

Please deactivate then and try again.

**Comment by jennirinker** [comment]
Company laptop, I'm not give that option. :(

**Comment by ccordoba12** [comment]
Then please ask your IT department to let you do that for a moment and try again. Else it's not possible for us to continue giving you feedback.

**Comment by jennirinker** [comment]
Highly doubt they'd let me connect to my home network on an unsecured laptop. 

Regardless, I verified that the problem is resolved if I'm at home but VPN'd to my work network. So this is almost certainly something caused by IT's security protocol. I'll close this and follow up with IT. 

Sorry for not catching this sooner.

**Comment by ccordoba12** [comment]
No problem. I'm glad you found a solution.
