### ISSUE TITLE
Console tabs are too big because they display the full filename

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1165]
_From [andreasn...@googlemail.com](https://code.google.com/u/106330885117898830116/) on 2012-10-04T15:20:39Z_

The console tabs of running or run programs are quite big, because they display the complete filename including path, e.g.:

"Console - /home/user/python/myproject/util/module.py"

On some Spyder window setups, this big tab uses much space and thus leaves very little space for the other views tabs, I have put in the same pane. These other tabs then often show only one letter and it is somehow unpleasing to the eye.

Not so long ago, only the filename ("Console - module.py") was displayed in these tabs. Can we have an option for choosing between long and short filenames in the console tabs?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1165_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-10-08T09:58:26Z_

We certainly can have this! I've also being bothered by this but haven't found time to fix it. I'll try to do it during the 2.2 cycle.

Thanks for reporting.

**Summary:** Console tabs are too big because they display the full filename  
  **Status:** Accepted  
  **Labels:** MS-v2.2 Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T14:27:24Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:53:28Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-27T05:20:41Z_

To solve this you need to look in plugins/externalconsole.py, for the method called "start", and the arg called "fname", which you can redefine to contain only the file name instead of the full path.

**Labels:** Easy

**Comment by Nodd** [comment]
Consoles now show the filename on the tab, and the full path in the title of the dockwidget. I don't know when it was fixed, but it is !

**Comment by ccordoba12** [comment]
@Nodd, the idea is **not** to show the full path, but only the filename :-)

**Comment by Nodd** [comment]
yes, that's what they do ?

**Comment by ccordoba12** [comment]
Not at the moment. That's why the console title can be too wide, and the idea is to fix that ;-)

**Comment by Nodd** [comment]
Are we speaking about the same thing ?
I see the full path in the console title (and I think it's fine), and I see the filename only in the tab (and that's fine too). The title width does not limit the dockwidget's size (I tested by making it floating instead of docked).
![spydertabs](https://cloud.githubusercontent.com/assets/506348/7475999/3383b046-f34b-11e4-9b81-f6dc540be3e5.png)

**Comment by ccordoba12** [comment]
Sorry for not being clear enough :-)

When our Python Console is tabbed next to other panes (e.g. History Log or IPython Console), then it's tab title is too big because it uses the full filename path. The idea is to use a shorter title ;-)

**Comment by Nodd** [comment]
Ooooooh, the title of the dockwidget is used for the dockwidget's tab title ! Now I get it.
I need to update my telepathy package !

**Comment by goanpeca** [comment]
Well... I have access to the tabs now since the dockwidget tab reordering PR, so I could just make sure it is always a fixed value :-)

**Comment by ccordoba12** [comment]
Even better!! Thanks :-)

**Comment by ccordoba12** [comment]
@malliwi88, please work on this one.

**Comment by ccordoba12** [comment]
@malliwi88, I hope to see your PR for this on Monday or Tuesday. It's an easy fix :-)

**Comment by malliwi88** [comment]
Okay, we're talking about this, right?

This is the problem
![seleccion_012](https://cloud.githubusercontent.com/assets/5307894/20856168/ae2fe178-b8d6-11e6-9cac-2929618cdb08.png)

This is the result of PR #37
![seleccion_013](https://cloud.githubusercontent.com/assets/5307894/20856175/ee38ab9c-b8d6-11e6-9020-77b8ed8caa53.png)

Thanks @ccordoba12

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.
