### ISSUE TITLE
Facing error when trying to open spyder tutorial

### ISSUE THREAD

**Issue by thakardarshit** [spyder-ide/spyder#11652]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
This is the error when trying to open spyder tutorial or getting help for a function in rich text format
![image](https://user-images.githubusercontent.com/58983090/75320673-34f40480-5895-11ea-9804-ecc4dfc16558.png)

### What steps reproduce the problem?

1. When trying to open spyder tutorial 
2. Getting help for a function in rich text format 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.4
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 home

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@dalthviz, this happens because people install Anaconda in drives different from `C:\`, but try to load the tutorial from `C:\`.

**Comment by thakardarshit** [comment]
@ccordoba12 I uninstalled anaconda and then reinstalled it in c:\ Now it is working fine Thanks .

**Comment by ccordoba12** [comment]
Thanks for letting us know about it! Still, this is an issue we have to solve.
