### ISSUE TITLE
Move `create_action` function inside the plugin API 

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#11658]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
We are creating actions inside different plugins and then we need to register the shortcut even if we include the `shortcut` kwarg on the function. If we don't do this, then we need to restart spyder after a change in the shortcuts. Also, we will be able to reduce the number of code lines in our plugin files.

### What steps reproduce the problem?

1. Create an action in a plugin
2. <Forget to call the register_action function of the plugin>

### What is the expected output? What do you see instead?
By creating an action, the shortcut will be registered.

## Versions

Python 3.8.1 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Darwin 19.2.0

**Comment by ccordoba12** [comment]
Please work on this in the master branch @steff456.

**Comment by goanpeca** [comment]
This is now part of the new API so I am closing this
