### ISSUE TITLE
Kite failed to given code suggestions for sub methods/functions of sys.argv[].*

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11666]
Hi,

Spyer git master version, failed to autocomplete the following with kite plugin:

```
import sys
sys.argv[1].<tab>
```

While jedi will works smoothly.  I'm not sure this is due to spyder or kite, so I posted this issue here and kite's support maillist.  

ps.  Tested with Ubuntu 19.10 + anaconda3-2019.10 + spyder git master version.

Regards

**Comment by ccordoba12** [comment]
Ok, please let us know what the Kite people say about this.

**Comment by ccordoba12** [comment]
This is not something we can solve here, as I mentioned before.
