### ISSUE TITLE
Autocompletion for the stuff in code comment block and gereral spell checking.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11663]
Hi,

It seems the spyder currently don't support:

1 Auto-completion for the stuff in code comment block.
2 Spell-check.

Should these features be enabled?

**Comment by ccordoba12** [comment]
> Auto-completion for the stuff in code comment block.

We do in Spyder 4, although this is going to be much better in Spyder 4.1.0, to be released next week.

> Spell-check.

We don't support spell checking and we don't have plans to do it, sorry.
