### ISSUE TITLE
Help: Check if more info can be retrieved from Kite

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#11675]
Is it possible to get the format of the information  (MD vs rst vs... ?)

**Comment by goanpeca** [comment]
@dalthviz is this something we need to ask to the Kite team, or something we can investigate ourselves?

**Comment by dalthviz** [comment]
I think there is an endpoint that currently we aren't using which we could investigate (I think is the one the Copilot retrieves the parsed info). Also, I think Kite can provide an HTML version of the documentation but yes I think we can check first ourselves :+1:

**Comment by ccordoba12** [comment]
This issue no longer applies, so I'm going to close it.
