### ISSUE TITLE
No code folding at startup

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#11671]
## Problem Description

After commit https://github.com/spyder-ide/spyder/commit/1f7911b9f64683d0514dbce001be4ebf95456fb6, code folding is not initiated automatically at startup. It is activated though as soon as a change is registered in the document.

![code_folding](https://user-images.githubusercontent.com/10170372/75462932-076d9080-5953-11ea-8b9b-cab9d86f6278.gif)

## Versions

* Spyder 5.0.0.dev0 (Commit: f21d862d0) 
* Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.3.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.2.2 (OK)
diff_match_patch >=20181111   :  20181111 (OK)
intervaltree                  :  None (OK)
IPython >=4.0                 :  7.9.0 (OK)
jedi =0.14.1                  :  0.14.1 (OK)
nbconvert >=4.0               :  5.6.0 (OK)
numpydoc >=0.6.0              :  0.9.1 (OK)
paramiko >=2.4.0              :  2.6.0 (OK)
parso =0.5.2                  :  0.5.2 (OK)
pexpect >=4.4.0               :  4.7.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.6.3 (OK)
pygments >=2.0                :  2.4.2 (OK)
pylint >=0.25                 :  2.4.3 (OK)
pyls >=0.31.2;<0.32.0         :  0.31.2 (OK)
qdarkstyle >=2.7              :  2.8 (OK)
qtawesome >=0.5.7             :  0.6.0.dev0 (OK)
qtconsole >=4.6.0             :  4.7.0.dev0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.8.3 (OK)
sphinx >=0.6.6                :  2.2.1 (OK)
spyder_kernels >=1.8.1;<2.0.0 :  2.0.0.dev0 (OK)
watchdog                      :  None (OK)
zmq >=17                      :  18.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.13 (OK)
matplotlib >=2.0.0            :  3.1.3 (OK)
numpy >=1.7                   :  1.17.2 (OK)
pandas >=0.13.1               :  0.25.2 (OK)
scipy >=0.17.0                :  1.3.1 (OK)
sympy >=0.7.3                 :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
There seems to be some kind of race condition when there are two or more tabs already open. Actually, there are sometimes that the folding is displayed at stratup, but others that not

**Comment by ccordoba12** [comment]
@impact27, could you also help us with this one? This is a regression introduced by your work in PR #11488.

**Comment by ccordoba12** [comment]
Sorry @impact27, I talked too soon.

@andfoy, The faulty commit is 1f7911b9f64683d0514dbce001be4ebf95456fb6. Now we have to understand why.

**Comment by jnsebgosselin** [comment]
> 
> 
> Sorry @impact27, I talked too soon.
> 
> @andfoy, the faulty commit is [1f7911b](https://github.com/spyder-ide/spyder/commit/1f7911b9f64683d0514dbce001be4ebf95456fb6). Now we have to understand why.

I confirm, sorry for that, this is my fault, I was lazy and did a poor job tracing back the bug to the right commit.

**Comment by ccordoba12** [comment]
No worries. Thanks to you for finding this nasty regression before the final release!
