### ISSUE TITLE
cant able to run local.py in remote machine directly using RUN icon.

### ISSUE THREAD

**Issue by KatheravanArumugam** [spyder-ide/spyder#11677]
Hi carlos,

I tried with
python -m spyder_kernels.console
NOTE: When using the ipython kernel entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see ipython/ipython#2049

To connect another client to this kernel, use:
--existing kernel-45622.json

Even after using this kernel file "%run "C:\Users\kaarumug\Desktop\untitled0.py"
ERROR:root:File 'C:\\Users\\kaarumug\\Desktop\\untitled0.py' not found." Observing the same.

Please help to solve this.
I have my .py file and kernel json file in my local desktop is this okay?
please correct me if i am wrong.

**Comment by ccordoba12** [comment]
This is solved in Spyder 4. Please update.
