### ISSUE TITLE
change behavior of runcell in spyder4

### ISSUE THREAD

**Issue by ricmarchao** [spyder-ide/spyder#11685]
## Problem Description
I just upgraded from Spyder 3 to 4
I used to do cntr+Enter on a selected block of code, it would then assume that to be the current cell
and exectute
with Spyder4 the selected block is ignored and tries to run the code at the beginning of the page
it doesn't assume the currentcell as the selected/highlighted block of code

to select a block of code I use shift with the down and up arrows,so it becomes highlighted

F9 runs the selected code in both Spyder3 and Spyder 4, I am aware of that

still there is a change in behavior from Spyder3 to Spyder4 , Spyder3  if a piece of code was selected that would be defined as the current cell in Spyder 4 the selected text is ignored and takes the top of the page as the current cell, that makes less sense to me.

Expected behavior is that whatever code block is selected should be the current cell

### What steps reproduce the problem?

take this code for example:
`a=3+"abc"
print(a)

text_var="abc"
print(text_var)
`
select the last two lines, so they are highlighted, ctrn+enter will return an error since it executes the first 2 lines
F9 will work fine, in both Spyder3 and 4 , but cntrl+enter only works in Spyder3 

### What is the expected output? What do you see instead?
I would like in Spyder4 for runcell to take the current selected block of text, instead of going to the top of the page and trying to execute code that is not selected 

## Versions

* Spyder version:  4.0.1
* Python version: 3.7.6
* Operating System name/version: windows 10

**Comment by ccordoba12** [comment]
This has been asked several times before. For instance here

https://github.com/spyder-ide/spyder/issues/11484

Please search our issues for next time for duplicates, as we suggest.

**Comment by Whiax** [comment]
I can confirm the behavior change is still unexpected and "weird".
When I select a part of the code, right click and do "run cell", which is the first option, it runs the whole code.
I feel that if a part of the code is selected, "run cell" should fall on the "run selection" behavior.

On the fly code execution is the best/main feature of Spyder for me. The ability to run the code part by part just by (1) select, (2) right click and (3) select 1st option.

It feels less intuitive when "run cell" runs the whole file whatever is selected. And even if it feels ridiculous, in terms of ux design it's less easy to reach an option that is between other multiple options
