### ISSUE TITLE
Dialog Box Out of Control

### ISSUE THREAD

**Issue by xiapo00** [spyder-ide/spyder#11688]
When I use tkinter or pygame, the new dialog box created is always out of control after I press the close button on the top-right.
It seems that the only way to get it closed is to restart the ipython console, which is hardly convenient.
I don't know wheather it is a common problem.
If yes, could you please fix it in the next version?

**Comment by ccordoba12** [comment]
Did you set your Graphics backend and restarted Spyder before running your code?

**Comment by xiapo00** [comment]
> Did you set your Graphics backend to `Tk` and restarted Spyder before running your code?

I did, several times, but still fail.

**Comment by ccordoba12** [comment]
You need to restart your kernel or Spyder after doing that. Did you do that?

**Comment by xiapo00** [comment]
Finally, the problem was solved by upgrading ipython. Thanks.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
