### ISSUE TITLE
Linter false red flag on try-try-finally

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11683]
```python
def f():
    a = "a"
    try:
        print("`try` executed")
    except:    
        print("`except` executed")
        try:
            pass
        finally:
            print("`finally` executed")
            del a
    print(a)
f()
```
```
`try` executed
a
```

<img src="https://user-images.githubusercontent.com/16495490/75593452-d7cb9f00-5a9e-11ea-86ed-2f68432a3549.png" width="300">

<hr>

Not a big deal, but an orange marker instead with something like "`a` may be undefined" may be more appropriate.

**Comment by goanpeca** [comment]
This is more of a pyflakes issue, since it is returning an E (Error)
