### ISSUE TITLE
Crowdin translations are outdated

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#11692]
@goanpeca, I checked yesterday the Spanish translation in Crowdin and it's outdated. On the hand, the strings shown there that need to translated are not in the right places according to the code in the latest 4.x and master branches. And on the other hand, we added and modified several strings for 4.1 and they are not shown in Crowdin.

Please take a look at that asap, so we can inform our translators that they can start their work before the release of 4.1.0 next weekend. Thanks!

**Comment by goanpeca** [comment]
@ccordoba12 have you updated the `.po`files with the gettext helper scripts?

**Comment by ccordoba12** [comment]
> have you updated the .pofiles with the gettext helper scripts?

No, but do we have to do that manually? I thought that was done by Crowdin too.

**Comment by goanpeca** [comment]
Nope we need to do it. I will push a PR, no worries;-)
