### ISSUE TITLE
copy to clipboard

### ISSUE THREAD

**Issue by ACE0999** [spyder-ide/spyder#11691]
### What steps will reproduce the problem?

Just copying a pandas dataframe to clipboard with either ctrl+c or right-click copy.
I am using df.to_clipboard() in the meantime.

### Traceback
```python-traceback
  File "C:\Users\Lenovo_student\Anaconda_3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 664, in copy
    obj.to_csv(output, sep='\t', index=index, header=header)
  File "C:\Users\Lenovo_student\Anaconda_3\lib\site-packages\pandas\core\generic.py", line 3007, in to_csv
    escape = config.get_option("display.latex.escape")
  File "C:\Users\Lenovo_student\Anaconda_3\lib\site-packages\pandas\io\formats\csvs.py", line 25, in <module>
    from pandas.io.common import (
ImportError: cannot import name 'get_compression_method' from 'pandas.io.common' (C:\Users\Lenovo_student\Anaconda_3\lib\site-packages\pandas\io\common.py)
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.14 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
Please update to the latest spyder version

**Comment by ccordoba12** [comment]
@ACE0999, this look like an installation problem with Pandas. If you installed it with pip at some point, then you broke your Anaconda installation and you need to remove and reinstall Anaconda entirely. If not, please open the Anaconda prompt and run there

    conda install -f pandas

That could solve this issue.

**Comment by ACE0999** [comment]
Thank you for your replies, I'm trying both suggestions above and will let you guys know

**Comment by ACE0999** [comment]
The issue was resolved after reinstallation... Thanks

**Comment by ccordoba12** [comment]
Great!! For next time, please use conda to install packages and not pip. The things is conda and pip provide incompatible binary packages, so they can't be mixed.

**Comment by ACE0999** [comment]
@ccordoba12 
Question please, after updating Spyder, I am now having issues when trying to double click on variables in the variables explorer. Basically, trying to see a numpy array is giving "object array are currently not supported". Is this normal or should I revert to an older version of spyder?
I currently have Spyder version 3.3.6 and numpy version 1.16.5

**Comment by ACE0999** [comment]
Sorry for that, figured it out... I guess storing hex now in the new version, in numpy and pandas causes issues for spyder if trying to open those dataframes and arrays under variable explorer

**Comment by ccordoba12** [comment]
> The error message was ContextualVersionConflict(cytools 0.10.0... for pandas

That still looks like an installation issue caused by pip.

**Comment by ACE0999** [comment]
yes the only package I installed with pip was web3.py, which I couldn't find on conda... guess I'll have to live with this... Thanks

**Comment by ACE0999** [comment]
just wanting to update you on the issue, I reverted back to an older spyder version (3.3.0) and seems everything works great again no more issues with opening up variables in the explorer...
