### ISSUE TITLE
How to add new fonts?

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#11703]
### Problem Description

    As I saw in tools>preferences>appearance>, I found there are few fonts to use for me. How can I add new fonts and show them here.

### My envs:
* Spyder version: 4.0.1
* Python version: 3.6.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: windows10

**Comment by ccordoba12** [comment]
You need to install them using the Windows facilities for that (please google for it). This is not something you can do through Spyder, sorry.
