### ISSUE TITLE
Align indented lines after pasting

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11701]
Currently, when pasting wholly copied lines onto a new line, the indenting whitespaces are combined as below. In multiline highlighting, this requires to always fully backspace on the line being pasted into (or unindenting), which is tedious and is handled automatically by other IDEs.

![image](https://user-images.githubusercontent.com/16495490/75725780-a94a0000-5cfa-11ea-9c00-40aaf3e44f04.png)

**Comment by ccordoba12** [comment]
Good suggestion! @steff456, please take a look at this one.

**Comment by impact27** [comment]
I agree that autoindent on paste would be great. In atom for example it is implemented here:
https://github.com/atom/atom/blob/976cb9ef3a611163052f9d31c6c3685dc1e6c5b4/src/selection.js#L501
(On paste, `options.autoIndent` is True)

**Comment by ccordoba12** [comment]
@impact27, I agree. Would you like to take a look at it?

**Comment by impact27** [comment]
Having worked with this for a while, I feel that this is a serious quality of life improvment! Thanks @OverLordGoldDragon for the suggestion!

**Comment by OverLordGoldDragon** [comment]
p.s. I unintentionally pulled an ad campaign for Spyder with [this answer](https://stackoverflow.com/a/58667409/10133797) (check question views)
