### ISSUE TITLE
Panes are hard to click and drag

### ISSUE THREAD

**Issue by matheger** [spyder-ide/spyder#11705]
## Problem Description

The click are to "grab" a pane and move it around  to dock it somewhere else in the main window is awfully small - in fact, it just seems to be one pixel tall.

To visualize the problem: In the attached image, I would expect to be able to move the "Files" pane out of its current dock by clicking anywhere in the blue area (outside of the buttons) and dragging the pane to a new position. Instead, I have to hit _exactly_ on the red line. Needless to say it's frustratingly hard to rearrange the UI to my liking this way.

![Untitled](https://user-images.githubusercontent.com/34485360/75742148-0083ac80-5cca-11ea-8352-32c1d7a26d51.png)

Python 3.7.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by ccordoba12** [comment]
That's not the area from which you can drag panes. For that you need to go to the `View` menu and deactivate the option called `Lock panes and toolbars`. After that, this is what you'll see for the Files pane:

![Selección_019](https://user-images.githubusercontent.com/365293/75791350-7162ad00-5d3a-11ea-9101-b40d06b1c026.png)

As you can see, there's a new region on top of every pane. You need to right click on it to move any pane to a new location in the window, like this:

![Selección_020](https://user-images.githubusercontent.com/365293/75791583-c272a100-5d3a-11ea-98d6-a0b0606d92fd.png)

**Comment by matheger** [comment]
Oof. I really went out of my way to solve a non-issue here, didn't I. I guess it's just a quirk of the UI then that I can still drag locked panes by that 1-pixel area.

**Comment by ccordoba12** [comment]
No worries. Truth is this is not an intuitive process at all and many users are still confused by it. We have to think how to improve it.

> I guess it's just a quirk of the UI then that I can still drag locked panes by that 1-pixel area.

Absolutely! I didn't know that was possible.

**Comment by matheger** [comment]
> Absolutely! I didn't know that was possible.

Imagine the persistence that it took me to figure this out... if only I had put that effort into finding the correct menu option instead. :)
