### ISSUE TITLE
Blank screen never ending

### ISSUE THREAD

**Issue by JmiXIII** [spyder-ide/spyder#11729]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Blank Screen

### What steps reproduce the problem?
pip install spyder==4.0.1

1. cd app directory
2. python start.py
3. 

### What is the expected output? What do you see instead?
expected Spyder with filled screens
Seing -> Spyder with blank and never ending waiting cursor

### Paste Traceback/Error Below (if applicable)

```python-traceback

Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.8.2
* Qt version: 
* PyQt version: 
* Operating System name/version: W10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
I don't know how you expect us to understand your problem just from the statement "blank screen*. So I'm closing this for now.

This could be solved in our next version (4.1.0), to be released next week. So please check again when that version is available.
