### ISSUE TITLE
The problem with scrollbars when Spyder starts with Dark Theme

### ISSUE THREAD

**Issue by SergeiDBykov** [spyder-ide/spyder#11728]
### Issue Report Checklist

* [ +] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ +] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [+ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ +] Tried basic troubleshooting (if a bug/error)
    * [+ ] Restarted Spyder
    * [ +] Reset preferences with ``spyder --reset``
    * [ +] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [+ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If one starts Spyder from dark mode, two problems appear

1. Right-side scrollbar hides the minimap with warnings (or may be minimap just does not appear):

![Screen Shot 2020-03-05 at 12 53 14 PM](https://user-images.githubusercontent.com/60148493/75971696-318af980-5ee3-11ea-8dae-ff3bc27200da.png)
2. When on a screen, HORIZONTAL scrollbar partly hides useful information, e.g., variable name in variable explorer

![scroll](https://user-images.githubusercontent.com/60148493/75971821-6008d480-5ee3-11ea-8537-8cc5d71c5622.gif)

### What steps reproduce the problem?

1. Set dark theme for the editor
2.  Re-run spyder

### What is the expected output? What do you see instead?

Everything works fine in Light Mode for the editor. 

Strange thing I found: If you have problems described above, go to the appearance settings, set Light Theme (do not quit after that!), then set Dark theme again (it this very window you selected Light Theme!), close preferences, and everything is okay in editor even if scrollbar persists, including minimap and horizontal scroll does not impede visibility:

![Screen Shot 2020-03-05 at 1 19 05 PM](https://user-images.githubusercontent.com/60148493/75972148-f0471980-5ee3-11ea-9afa-a5064fbecf22.png)

However it is not a good solution, because if you restart Spyder, the problems appear again.

## Versions

* Spyder version: 
spyder                    4.0.1                    py37_0  
spyder-kernels            1.8.1                    py37_0  
* Python version: 
python                    3.7.4                h359304d_1  
* Qt version: 
qt                        5.9.7                h468cd18_1  
qtawesome                 0.6.1                      py_0  
qtconsole                 4.6.0                      py_1  
qtpy                      1.9.0                      py_0  
* PyQt version: 
pyqt                      5.9.2            py37h655552a_2  
* Operating System name/version: 
macOs Sierra 10.12.6
### Dependencies
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  None (NOK)

**Comment by ccordoba12** [comment]
This could happen because you activated the option to vertically align the Pane tabs (i.e. the ones that hold the Variable Explorer, Project, Files, etc). Could you deactivate that option and try again?

**Comment by SergeiDBykov** [comment]
> This could happen because you activated the option to vertically align the Pane tabs (i.e. the ones that hold the Variable Explorer, Project, Files, etc). Could you deactivate that option and try again?

I'm sorry, but could you tell please where this option is? I cannot find it in Spyder.

Also I find out that any changes in appearance (e.g. "Tear off menus") result in correct work of scrollbars and mini map.

**Comment by ccordoba12** [comment]
It's either "Vertical tabs in panes":

![Selección_032](https://user-images.githubusercontent.com/365293/76154714-fd643400-60ae-11ea-91f2-6dd974294ce1.png)

**Comment by SergeiDBykov** [comment]
> It's "Vertical tabs in panes":

I actually tried with different options in this preferences tab, including vertical tabs alignment, but after the reopening, the issue is still there,

And again, changing anything in the appearance removes the bug until you reload Spyder.

**Comment by ccordoba12** [comment]
Could you run

    spyder --reset

in the Anaconda Prompt and try again?

**Comment by SergeiDBykov** [comment]
> Could you run
> 
> ```
> spyder --reset
> ```
> 
> in the Anaconda Prompt and try again?

Sure, but how can I save my Spyder settings before (preferences, layouts, etc?). I rebooted anaconda two times before opening the issue and I am tired of doing reconfiguration every time.

**Comment by ccordoba12** [comment]
Please open Terminal.app and run there these commands

    cp -R ~/.spyder-py3 ~/.spyder-py3.old

Before resetting, please verify that `~/.spyder-py3.old` exists and proceed.

**Comment by ccordoba12** [comment]
So your old settings will be saved in `~/.spyder-py3.old` and you can restore them easily afterwards.

**Comment by SergeiDBykov** [comment]
Thanks. It does work, after reset, the minimap is on place right after start. But when I transfer my old settings, the problem appears again. 
I will try to figure out what's happening, and if I find something, I report you.

Thanks!

**Comment by ccordoba12** [comment]
No worries. I'm glad that at least things went back to normal after the reset.
