### ISSUE TITLE
Error while starting Kernel in spyder... Please help

### ISSUE THREAD

**Issue by Nrup147** [spyder-ide/spyder#11720]
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\NRUP\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1572, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\NRUP\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\NRUP\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\NRUP\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\NRUP\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\NRUP\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\NRUP\\AppData\\Roaming\\jupyter\\runtime\\kernel󈛨de317b3b75.json'

I have tried the command ' conda update --all ' but in the end it gives a verification error.
I have tried reinstalling several times and still i have kept getting this error.

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for conda located at C:\Users\NRUP\.conda\pkgs\conda-4.8.2-py37_0
appears to be corrupted. The path 'Lib/site-packages/conda/gateways/__pycache__/anaconda_client.cpython-37.pyc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for conda located at C:\Users\NRUP\.conda\pkgs\conda-4.8.2-py37_0
appears to be corrupted. The path 'Lib/site-packages/conda/gateways/anaconda_client.py'
specified in the package manifest cannot be found.

**Comment by ccordoba12** [comment]
To fix this, please open the Anaconda Prompt and run there the following commands:<br><br>`conda update anaconda`<br>`conda install jupyter_client=5.3.4`

**Comment by Nrup147** [comment]
(base) C:\Users\NRUP>conda update anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\NRUP\Anaconda3

  added / updated specs:
    - anaconda


The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/win-64::_anaconda_depends-2019.03-py37_0
  hypothesis         pkgs/main/noarch::hypothesis-5.5.4-py_0
  matplotlib-base    pkgs/main/win-64::matplotlib-base-3.1.3-py37h64f37c6_0
  path               pkgs/main/win-64::path-13.1.0-py37_0
  pytest-astropy-he~ pkgs/main/noarch::pytest-astropy-header-0.1.2-py_0
  pywin32-ctypes     pkgs/main/win-64::pywin32-ctypes-0.2.0-py37_1000

The following packages will be UPDATED:

  anaconda-project                               0.8.3-py_0 --> 0.8.4-py_0
  asn1crypto                                   1.0.1-py37_0 --> 1.3.0-py37_0
  astroid                                      2.3.1-py37_0 --> 2.3.3-py37_0
  astropy                              3.2.1-py37he774522_0 --> 4.0-py37he774522_0
  attrs                                         19.2.0-py_0 --> 19.3.0-py_0
  babel                                          2.7.0-py_0 --> 2.8.0-py_0
  backports.functoo~                               1.5-py_2 --> 1.6.1-py_0
  beautifulsoup4                               4.8.0-py37_0 --> 4.8.2-py37_0
  bitarray                             1.0.1-py37he774522_0 --> 1.2.1-py37he774522_0
  bokeh                                        1.3.4-py37_0 --> 1.4.0-py37_0
  bottleneck                           1.2.1-py37h452e1ab_1 --> 1.3.2-py37h2a96729_0
  ca-certificates                               2019.8.28-0 --> 2020.1.1-0
  certifi                                  2019.9.11-py37_0 --> 2019.11.28-py37_0
  cffi                                1.12.3-py37h7a1dbc1_0 --> 1.14.0-py37h7a1dbc1_0
  cloudpickle                                    1.2.2-py_0 --> 1.3.0-py_0
  colorama           pkgs/main/win-64::colorama-0.4.1-py37~ --> pkgs/main/noarch::colorama-0.4.3-py_0
  conda                                       4.7.12-py37_0 --> 4.8.2-py37_0
  contextlib2                                    0.6.0-py_0 --> 0.6.0.post1-py_0
  cryptography                           2.7-py37h7a1dbc1_0 --> 2.8-py37h7a1dbc1_0
  curl                                    7.65.3-h2a8f88b_0 --> 7.68.0-h2a8f88b_0
  cython                             0.29.13-py37ha925a31_0 --> 0.29.15-py37ha925a31_0
  cytoolz                             0.10.0-py37he774522_0 --> 0.10.1-py37he774522_0
  dask                                           2.5.2-py_0 --> 2.11.0-py_0
  dask-core                                      2.5.2-py_0 --> 2.11.0-py_0
  decorator          pkgs/main/win-64::decorator-4.4.0-py3~ --> pkgs/main/noarch::decorator-4.4.1-py_0
  distributed        pkgs/main/noarch::distributed-2.5.2-p~ --> pkgs/main/win-64::distributed-2.11.0-py37_0
  docutils                                    0.15.2-py37_0 --> 0.16-py37_0
  fsspec                                         0.5.2-py_0 --> 0.6.2-py_0
  future                                      0.17.1-py37_0 --> 0.18.2-py37_0
  h5py                                 2.9.0-py37h5e291fa_0 --> 2.10.0-py37h5e291fa_0
  imageio                                      2.6.0-py37_0 --> 2.6.1-py37_0
  imagesize          pkgs/main/win-64::imagesize-1.1.0-py3~ --> pkgs/main/noarch::imagesize-1.2.0-py_0
  importlib_metadata                            0.23-py37_0 --> 1.5.0-py37_0
  intel-openmp                                   2019.4-245 --> 2020.0-166
  ipykernel                            5.1.2-py37h39e3cac_0 --> 5.1.4-py37h39e3cac_0
  ipython                              7.8.0-py37h39e3cac_0 --> 7.12.0-py37h5ca1d4c_0
  jedi                                        0.15.1-py37_0 --> 0.16.0-py37_0
  jinja2                                        2.10.3-py_0 --> 2.11.1-py_0
  joblib             pkgs/main/win-64::joblib-0.13.2-py37_0 --> pkgs/main/noarch::joblib-0.14.1-py_0
  jsonschema                                   3.0.2-py37_0 --> 3.2.0-py37_0
  jupyter_client                               5.3.3-py37_1 --> 5.3.4-py37_0
  jupyter_console    pkgs/main/win-64::jupyter_console-6.0~ --> pkgs/main/noarch::jupyter_console-6.1.0-py_0
  jupyter_core       pkgs/main/noarch::jupyter_core-4.5.0-~ --> pkgs/main/win-64::jupyter_core-4.6.1-py37_0
  jupyterlab                             1.1.4-pyhf63ae98_0 --> 1.2.6-pyhf63ae98_0
  keyring                                     18.0.0-py37_0 --> 21.1.0-py37_0
  krb5                                    1.16.1-hc04afaa_7 --> 1.17.1-hc04afaa_0
  lazy-object-proxy                    1.4.2-py37he774522_0 --> 1.4.3-py37he774522_0
  libcurl                                 7.65.3-h2a8f88b_0 --> 7.68.0-h2a8f88b_0
  liblief                                  0.9.0-ha925a31_2 --> 0.9.0-ha925a31_3
  libtiff                                 4.0.10-hb898794_2 --> 4.1.0-h56a325e_0
  llvmlite                            0.29.0-py37ha925a31_0 --> 0.31.0-py37ha925a31_0
  lxml                                 4.4.1-py37h1350720_0 --> 4.5.0-py37h1350720_0
  matplotlib                           3.1.1-py37hc8f65d3_0 --> 3.1.3-py37_0
  mkl                                            2019.4-245 --> 2020.0-166
  mkl_fft                             1.0.14-py37h14836fe_0 --> 1.0.15-py37h14836fe_0
  mock                  pkgs/main/win-64::mock-3.0.5-py37_0 --> pkgs/main/noarch::mock-4.0.1-py_0
  more-itertools     pkgs/main/win-64::more-itertools-7.2.~ --> pkgs/main/noarch::more-itertools-8.2.0-py_0
  nbconvert                                    5.6.0-py37_1 --> 5.6.1-py37_0
  nbformat           pkgs/main/win-64::nbformat-4.4.0-py37~ --> pkgs/main/noarch::nbformat-5.0.4-py_0
  networkx                                         2.3-py_0 --> 2.4-py_0
  notebook                                     6.0.1-py37_0 --> 6.0.3-py37_0
  numba                               0.45.1-py37hf9181ef_0 --> 0.48.0-py37h47e9c7a_0
  numexpr                              2.7.0-py37hdce8814_0 --> 2.7.1-py37h25d0782_0
  numpy                               1.16.5-py37h19fb1c0_0 --> 1.18.1-py37h93ca92e_0
  numpy-base                          1.16.5-py37hc3f5095_0 --> 1.18.1-py37hc3f5095_1
  numpydoc                                       0.9.1-py_0 --> 0.9.2-py_0
  openpyxl                                       3.0.0-py_0 --> 3.0.3-py_0
  openssl                                 1.1.1d-he774522_2 --> 1.1.1d-he774522_4
  packaging                                       19.2-py_0 --> 20.1-py_0
  pandas                              0.25.1-py37ha925a31_0 --> 1.0.1-py37h47e9c7a_0
  parso                                          0.5.1-py_0 --> 0.6.1-py_0
  partd                                          1.0.0-py_0 --> 1.1.0-py_0
  path.py                                       12.0.1-py_0 --> 12.4.0-0
  pillow                               6.2.0-py37hdc69c19_0 --> 7.0.0-py37hcc1f983_0
  pip                                         19.2.3-py37_0 --> 20.0.2-py37_1
  pluggy                                      0.13.0-py37_0 --> 0.13.1-py37_0
  prompt_toolkit                                2.0.10-py_0 --> 3.0.3-py_0
  psutil                               5.6.3-py37he774522_0 --> 5.6.7-py37he774522_0
  py                      pkgs/main/win-64::py-1.8.0-py37_0 --> pkgs/main/noarch::py-1.8.1-py_0
  py-lief                              0.9.0-py37ha925a31_2 --> 0.9.0-py37ha925a31_3
  pycurl                            7.43.0.3-py37h7a1dbc1_0 --> 7.43.0.5-py37h7a1dbc1_0
  pygments                                       2.4.2-py_0 --> 2.5.2-py_0
  pylint                                       2.4.2-py37_0 --> 2.4.4-py37_0
  pyodbc                              4.0.27-py37ha925a31_0 --> 4.0.30-py37ha925a31_0
  pyopenssl                                   19.0.0-py37_0 --> 19.1.0-py37_0
  pyparsing                                      2.4.2-py_0 --> 2.4.6-py_0
  pyrsistent                          0.15.4-py37he774522_0 --> 0.15.7-py37he774522_0
  pytables                             3.5.2-py37h1da0976_1 --> 3.6.1-py37h1da0976_0
  pytest                                       5.2.1-py37_0 --> 5.3.5-py37_0
  pytest-astropy     pkgs/main/win-64::pytest-astropy-0.5.~ --> pkgs/main/noarch::pytest-astropy-0.8.0-py_0
  pytest-doctestplus                             0.4.0-py_0 --> 0.5.0-py_0
  python-dateutil    pkgs/main/win-64::python-dateutil-2.8~ --> pkgs/main/noarch::python-dateutil-2.8.1-py_0
  pywavelets                           1.0.3-py37h8c2d366_1 --> 1.1.1-py37he774522_0
  pywin32                                223-py37hfa6e2cd_1 --> 227-py37he774522_1
  pywinpty                                  0.5.5-py37_1000 --> 0.5.7-py37_0
  pyyaml                               5.1.2-py37he774522_0 --> 5.3-py37he774522_0
  pyzmq                               18.1.0-py37ha925a31_0 --> 18.1.1-py37ha925a31_0
  qtawesome                                      0.6.0-py_0 --> 0.6.1-py_0
  qtconsole          pkgs/main/noarch::qtconsole-4.5.5-py_0 --> pkgs/main/win-64::qtconsole-4.6.0-py37_1
  requests                                    2.22.0-py37_0 --> 2.22.0-py37_1
  rope                                          0.14.0-py_0 --> 0.16.0-py_0
  ruamel_yaml                        0.15.46-py37hfa6e2cd_0 --> 0.15.87-py37he774522_0
  scikit-image                        0.15.0-py37ha925a31_0 --> 0.16.2-py37h47e9c7a_0
  scikit-learn                        0.21.3-py37h6288b17_0 --> 0.22.1-py37h6288b17_0
  scipy                                1.3.1-py37h29ff71c_0 --> 1.4.1-py37h9439919_0
  seaborn            pkgs/main/win-64::seaborn-0.9.0-py37_0 --> pkgs/main/noarch::seaborn-0.10.0-py_0
  setuptools                                  41.4.0-py37_0 --> 45.2.0-py37_0
  six                                         1.12.0-py37_0 --> 1.14.0-py37_0
  soupsieve                                    1.9.3-py37_0 --> 1.9.5-py37_0
  sphinx                                         2.2.0-py_0 --> 2.4.0-py_0
  sphinxcontrib-web~                             1.1.2-py_0 --> 1.2.0-py_0
  sqlalchemy                           1.3.9-py37he774522_0 --> 1.3.13-py37he774522_0
  sqlite                                  3.30.0-he774522_0 --> 3.31.1-he774522_0
  statsmodels                         0.10.1-py37h8c2d366_0 --> 0.11.0-py37he774522_0
  sympy                                          1.4-py37_0 --> 1.5.1-py37_0
  tbb                                     2019.4-h74a9793_0 --> 2020.0-h74a9793_0
  tblib                                          1.4.0-py_0 --> 1.6.0-py_0
  terminado                                    0.8.2-py37_0 --> 0.8.3-py37_0
  testpath           pkgs/main/win-64::testpath-0.4.2-py37~ --> pkgs/main/noarch::testpath-0.4.4-py_0
  tornado                              6.0.3-py37he774522_0 --> 6.0.3-py37he774522_3
  tqdm                                          4.36.1-py_0 --> 4.42.1-py_0
  urllib3                                     1.24.2-py37_0 --> 1.25.8-py37_0
  vs2015_runtime                     14.16.27012-hf0eaf9b_0 --> 14.16.27012-hf0eaf9b_1
  wcwidth            pkgs/main/win-64::wcwidth-0.1.7-py37_0 --> pkgs/main/noarch::wcwidth-0.1.8-py_0
  werkzeug                                      0.16.0-py_0 --> 1.0.0-py_0
  wheel                                       0.33.6-py37_0 --> 0.34.2-py37_0
  xlsxwriter                                     1.2.1-py_0 --> 1.2.7-py_0
  xlwings                                    0.15.10-py37_0 --> 0.17.1-py37_0
  zipp                                           0.6.0-py_0 --> 2.2.0-py_0

The following packages will be DOWNGRADED:

  anaconda                                   2019.10-py37_0 --> custom-py37_1
  pycosat                              0.6.3-py37hfa6e2cd_0 --> 0.6.3-py37he774522_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

CondaVerificationError: The package for conda located at C:\Users\NRUP\.conda\pkgs\conda-4.8.2-py37_0
appears to be corrupted. The path 'Lib/site-packages/conda/gateways/__pycache__/anaconda_client.cpython-37.pyc'
specified in the package manifest cannot be found.

CondaVerificationError: The package for conda located at C:\Users\NRUP\.conda\pkgs\conda-4.8.2-py37_0
appears to be corrupted. The path 'Lib/site-packages/conda/gateways/anaconda_client.py'
specified in the package manifest cannot be found.

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults::notebook-6.0.3-py37_0, defaults::notebook-6.0.3-py37_0
  path: 'menu/notebook.json'

Sir this is what i keep getting...My installation is corrupted ... I have tried reinstalling Anaconda Several times.

**Comment by Nrup147** [comment]
> To fix this, please open the Anaconda Prompt and run there the following commands:
> 
> `conda update anaconda`
> `conda install jupyter_client=5.3.4`

Sir Please review this problem as i have posted the response.

**Comment by ccordoba12** [comment]
> CondaVerificationError: The package for conda located at C:\Users\NRUP.conda\pkgs\conda-4.8.2-py37_0

Please read the messages. If conda is corrupted, you need to remove and reinstall Anaconda again.

**Comment by Nrup147** [comment]
> > CondaVerificationError: The package for conda located at C:\Users\NRUP.conda\pkgs\conda-4.8.2-py37_0
> 
> Please read the messages. If conda is corrupted, you need to remove and reinstall Anaconda again.

Sir with all due respect.I have reinstalled it several times still i keep getting the same error.

**Comment by ccordoba12** [comment]
Sorry, then this is not a problem with Spyder but with Anaconda. So please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by Nrup147** [comment]
Okay..thankyou so much.
