### ISSUE TITLE
How do I get forward to the task 

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#11736]
## Problem Description

    As we known, we can use CTRL+Z to make our operations back. How can we use an opposite approach to make operations forward.

## Versions

* Spyder version: 4.0.0
* Python version: 3.6.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu16.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
You need to use Ctrl+Y.
