### ISSUE TITLE
Importing package failed; spyder-kernels not working with clean install

### ISSUE THREAD

**Issue by DuncanMcRae** [spyder-ide/spyder#11735]
## Problem Description
Failed to load modules from conda env with spyder-kernels

### What steps reproduce the problem?

1. Format laptop with fresh Win10- update windows/drivers the works incl. installing Qt.
2. Install latest Miniconda: Miniconda3-latest-Windows-x86_64.exe
3. Open Anaconda Powershell Prompt (Miniconda3)
4.<base> conda update conda
5.<base> conda create -n spyder
6.<base> conda activate spyder

7.<spyder> conda config --env --add channels conda-forge
8.<spyder> conda config --env --set channel_priority strict
9.<spyder> conda install python>=3.8.1
10.<spyder> conda install -c defaults --override-channels spyder
11.<spyder> conda activate base
12.<base> conda create -n ds
13.<base> conda activate ds
14.<ds> conda config --env --add channels conda-forge
15.<ds> conda config --env --set channel_priority strict
16.<ds> conda install python>=3.8.1
17.<ds> conda install spyder-kernels
18.<ds> conda activate spyder
19.<spyder> spyder
>>>>Change python path to **C:\Users\dunca\Miniconda3\envs\ds\pythonw.exe**
20.<spyder> spyder
>>>>Result: kernel just cycled over and over "kernel died" or something similar
21.<spyder> conda activate ds
22.<ds> conda install -c defaults --override-channels spyder-kernels
23.<ds> conda install numpy
24.<ds> conda activate spyder
25.<spyder> spyder
>>>>Change python path to **C:\Users\dunca\Miniconda3\envs\ds\pythonw.exe**
26.<spyder> spyder
>>>>import numpy

### What is the expected output? What do you see instead?
Expecting numpy to import OK. Why is it so hard to use miniconda and install spyder with environments? I tried for hours before re-isntalling windows as well.

### Paste Traceback/Error Below (if applicable)

```python-traceback

import numpy
Traceback (most recent call last):

  File "C:\Users\dunca\Miniconda3\envs\ds\lib\site-packages\numpy\core\__init__.py", line 24, in <module>
    from . import multiarray

  File "C:\Users\dunca\Miniconda3\envs\ds\lib\site-packages\numpy\core\multiarray.py", line 14, in <module>
    from . import overrides

  File "C:\Users\dunca\Miniconda3\envs\ds\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-d4cdadb62aa7>", line 1, in <module>
    import numpy

  File "C:\Users\dunca\Miniconda3\envs\ds\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core

  File "C:\Users\dunca\Miniconda3\envs\ds\lib\site-packages\numpy\core\__init__.py", line 54, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.8 from "C:\Users\dunca\Miniconda3\envs\ds\pythonw.exe",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.1" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.

```

## Versions
Spyder 4.0.1 
Python 3.8.1 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10 
Python 3.8.1 (default, Mar  2 2020, 13:06:26) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

* Spyder version: Spyder 4.0.1 
* Python version <base>: 3.7.4
* Python version <spyder>: 3.8.1
* Python version <ds>: 3.8.1
* Qt version <spyder>:  5.9.7
* PyQt version <spyder>: 5.9.2
* Qt version <ds>:  n/a
* PyQt version <ds>: n/a

* Operating System name/version:  Windows 10 

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  None (NOK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  None (NOK)

```

**Comment by ccordoba12** [comment]
The problem was that we were not activating the conda environment where spyder-kernels is installed. But that was fixed and it'll be part of Spyder 4.1.0, to be released next week.
