### ISSUE TITLE
Set proxy for spyder to download plugins, say, kite. 

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11742]
Hi,

When I install kite from within spyder, the progress bar of downloading is flash again and again, displayed as 100% and then redisplaying as )%, and so on.

This is due to the connection issue from my location to the kite's server.  In order to solve this issue, I want to via a socks5/http proxy to do the job, but I cannot find any options for this on the preference panel.

Could you please add some options of setting proxy for spyder to download plugins, say, kite. 

Regards

**Comment by ccordoba12** [comment]
@metalogical, @its-dhung, what do you think about this?

**Comment by akdor1154** [comment]
@hongyi-zhao does setting the HTTP_PROXY env var, or your system proxy preferences, fix this?

**Comment by ccordoba12** [comment]
Yeah, I think this should be solved at the operating system level, not by us. Sorry, there are not enough hours in the day to implement all feature requests.
