### ISSUE TITLE
Spyder says dependencies have wrong version, but it lists different versions than installed

### ISSUE THREAD

**Issue by nicerman1** [spyder-ide/spyder#11749]
## Problem Description
When i start up spyder 4.0.1 it says i have missing dependencies. It lists that my jedi version is only 0.14.0, and should be 0.14.1. It gives a similar problem with qtconsole: it needs 4.6.0 and says i have version 4.5.1. When i actually go and use conda list, it says i do have jedi version 0.14.1 and qtconsole 4.6.0:
![image](https://user-images.githubusercontent.com/3341771/76166724-fdbd0780-6160-11ea-8294-ecc7f134939f.png)

![image](https://user-images.githubusercontent.com/3341771/76166740-204f2080-6161-11ea-87a2-7c9d8b48f5f3.png)

On my second computer i have the same package versions and everything works flawlessly on there, so i really don't get why it's acting up. I tried rebooting, reinstalling anaconda (and rebooting), resetting spyder, manually removing spyder, reinstalling it again, reinstalling anaconda again, and it just doesn't want to work. 

Previous spyder version do work, but i'd like to just use the latest one (which i would think shouldn't be that hard, but i've been trying to fix this for the past 4 hours...)

### What steps reproduce the problem?

1. Use conda update --all
2. Use conda update spyder
3. Start spyder

### What is the expected output? What do you see instead?
I just want spyder to work normally, it misses dependencies and iconsole doesn't work.

## Versions
* Spyder version: 4.0.1
* Python version: 3.7.6 (64 bit)
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.6.0 (OK)
jedi =0.14.1                 :  0.14.0 (NOK)
nbconvert >=4.0              :  5.5.0 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.0.2 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.5.1 (NOK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.0 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.3.0 (OK)
sympy >=0.7.3                :  1.4 (OK)

```

**Comment by ccordoba12** [comment]
This happens because you installed those packages with pip and Spyder is picking up those versions instead of the ones provided by Anaconda.

Please look for `jedi` or `qtconsole` in your hard drive and remove the directory or directories (not part of Anaconda) where those packages were installed.

They are usually placed in

    C:\Users\<your user>\AppData\Roaming\Python\

And for next time, please **do not** install packages with pip if they can be installed with conda. That creates a hell of mess and usually breaks Anaconda too.
