### ISSUE TITLE
Failed for autocompletion with pymatgen package.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#11743]
Hi,

Here is git master version of spyder + kite, tested with the following steps.

The code are from here:
https://ma.issp.u-tokyo.ac.jp/en/app-post/1146

```
from pymatgen.io.vasp.inputs import Kpoints
from pymatgen.core import Structure
from pymatgen.symmetry.bandstructure import HighSymmKpath

struct = Structure.from_file("POSCAR")
kpath = HighSymmKpath(struct)
kpts = Kpoints.automatic_linemode(divisions=40,ibz=kpath)
kpts.write_file("KPOINTS_nsc")
```

In the above the code snippets, both of the following failed to completions and gives nothing:

```
kpath.<tab>
kpts.<tab>
```

Regards

**Comment by ccordoba12** [comment]
Spyder is simply a frontend for what Kite and Jedi (the open source library used by the [python-language-server](https://github.com/palantir/python-language-server)) can provide for code completion.

If neither of them can't complete your code, there's nothing we can do about it, sorry.
