### ISSUE TITLE
pytorch tensor grda_fn is None

### ISSUE THREAD

**Issue by SerendipityForZhch** [spyder-ide/spyder#11750]
### What steps will reproduce the problem?

'''
print(torch.__version__)
x = torch.tensor([1.0,2.2],requires_grad=True)
print(x)
y = x + 2
print(y)
print(y.grad_fn , x.grad_fn)
'''
we get such output:
'''
1.2.0
tensor([1.0000, 2.2000], requires_grad=True)
tensor([3.0000, 4.2000])
None None
'''
The question is why y.grad_fn is None. 

However,the output is different when the same code runs on jupyter notebook. the output is
""" y.grad_fn = <AddBackward0 object at 0x000000000F22A630> """ 

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is a problem with Pytorch and not with Spyder. Please report it here instead:

https://github.com/pytorch/pytorch/
