### ISSUE TITLE
Provide syntax highlighting for functions

### ISSUE THREAD

**Issue by pianite** [spyder-ide/spyder#11753]
Compared to other editors, the syntax highlighting in Spyder is not as easy to quickly skim. This is largely due to a variety of syntax using the "plain text" coloring. I've seen this addressed in other editors with a highlighting color for function calls. Specifically, once parenthesis are added after an object. This would significantly improve syntax readability.

**Comment by goanpeca** [comment]
@pianite could you provide some screenshots to understand what you mean?

Thanks!

**Comment by pianite** [comment]
Yes definitely, sorry if my description was not clear. Here is a comparison of snippets in Atom with Hydrogen (top) and Spyder (bottom). Although there are multiple additional things highlighted, I think having a color for functions (and perhaps keyword arguments) does the most to improve readability.

![image](https://user-images.githubusercontent.com/1291068/76246582-d6167f80-61f2-11ea-80c0-af3dbf258667.png)

![image](https://user-images.githubusercontent.com/1291068/76246616-e4fd3200-61f2-11ea-85d0-69b79daf94ec.png)

**Comment by ccordoba12** [comment]
Duplicate of #1500

**Comment by ccordoba12** [comment]
We'll try to implement this for Spyder 5.

**Comment by pianite** [comment]
Rad, thank you!

**Comment by theoschaefer** [comment]
Any plans when the syntax highlighting will be updated?

I'm a big fan of Spyder, but the current syntax highlighting certainly makes reading my own code difficult compared to other editors.

Thanks!

**Comment by ccordoba12** [comment]
That will come for Spyder 6, to be released next year.

**Comment by theoschaefer** [comment]
Ah great! Thx for the fast reply!

**Comment by victorsanchezarevalo** [comment]
Will this functionality be included in Spyder 6? I think it is super usefull.

**Comment by ccordoba12** [comment]
@victorsanchezarevalo, sorry, it won't. Although it seems simple, this is actually a tricky problem because it requires to completely replace the current backend that does syntax highlighting in the Editor for a more powerful one.

We'll try to do that next year, but it won't available in 6.1 either because almost all work for that version is already planned.

**Comment by guilhermeguy** [comment]
Hi! 
Any plans on this functionality? Really looking forward to it.

**Comment by ccordoba12** [comment]
@guilhermeguy, we don't have the resources to address this right now. If you're interested in helping us solve it in the future, please donate to this project:

https://www.spyder-ide.org/donate/syntax-highlighting
