### ISSUE TITLE
Sometimes go to definition(ctrl+G) dosen't work.

### ISSUE THREAD

**Issue by Ikhwansong** [spyder-ide/spyder#11759]
### What steps will reproduce the problem?

Hi! glad to meet you!
Thanks for your making this IDE! I really appreciate you.

Get to the point, sometimes 'go to definition (ctrl +G)' dosen't work.

My system environment is follow

1. Pure, Vanila spyder on anaconda 
2. Linux mint 19.1 Tessa 

symptom is that 

when I start spyder, Shortly afterwards spyder's 'go to definition' doesn't work.
So if I want to use 'go to definition' , should have to restart the spyder.

Is there any bugs or other issues related this issue? 

Sorry for my bad English! 

## Versions

* Spyder version: 4.0.1 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-64-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.11.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.3.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.14 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment]
That's expected. There are some libraries (e.g. Tensorflow) for which Ctrl+G doesn't work because their sources are in a different language than Python (e.g. C++).

**Comment by Ikhwansong** [comment]
Thanks!!!!
