### ISSUE TITLE
Spyder is not running in anaconda

### ISSUE THREAD

**Issue by kuppas** [spyder-ide/spyder#11751]
Hi...
I updated the anaconda then I try to open my spyder editor it will not open it shows an error message in terminal like that 

**/home/kuppa/.anaconda/navigator/scripts/spyder.sh: 5: /home/kuppa/anaconda3/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: "(" unexpected**

* Spyder version: * Python version: * Qt version: * PyQt version: 
 
**conda info**
     active environment: None
       user config file : /home/kuppa/.condarc
 populated config files : /home/kuppa/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.12
         python version : 3.6.10.final.0
       virtual packages : __glibc=2.23
       base environment : /home/kuppa/anaconda3  (writable)
           channel URLs: https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/menpo/linux-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kuppa/anaconda3/pkgs
                          /home/kuppa/.conda/pkgs
       envs directories : /home/kuppa/anaconda3/envs
                          /home/kuppa/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.23.0 CPython/3.6.10 Linux/4.15.0-88-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

* Operating System name/version: Ubuntu 
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by ccordoba12** [comment]
Please start Spyder directly from the terminal instead of using Navigator.

Also, if you want to see this problem solved in Navigator, please report it here instead:

https://github.com/ContinuumIO/anaconda-issues/issues/
