### ISSUE TITLE
Can not open Notebook

### ISSUE THREAD

**Issue by aaronfoe** [spyder-ide/spyder#11760]
### What steps will reproduce the problem?

Open an existing Jupyter Notebook in Notebook view
Get a 404 error
Close the corresponding tab
Get the issue reporter which asks me to type the thing I'm currently typing

### Traceback
```python-traceback
  File "/Users/Aaron/miniconda3/lib/python3.7/site-packages/spyder_notebook/notebookplugin.py", line 387, in close_client
    client.shutdown_kernel()
  File "/Users/Aaron/miniconda3/lib/python3.7/site-packages/spyder_notebook/widgets/client.py", line 255, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "/Users/Aaron/miniconda3/lib/python3.7/site-packages/spyder_notebook/widgets/client.py", line 248, in get_kernel_id
    notebook_path = session.get('notebook', {}).get('path')
AttributeError: 'str' object has no attribute 'get'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.5.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
sphinx >=0.6.6    :  2.4.0 (OK)
rope >=0.9.4      :  0.16.0 (OK)
jedi >=0.9.0      :  0.16.0 (OK)
psutil >=0.3      :  5.6.7 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  1.0.1 (OK)
numpy >=1.7       :  1.18.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.15 (OK)
qtconsole >=4.2.0 :  4.6.0 (OK)
IPython >=4.0     :  7.12.0 (OK)
matplotlib >=2.0.0:  3.1.3 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by jitseniesen** [comment]
This is already reported as spyder-ide/spyder-notebook#192 and it is fixed in the last release of spyder-notebook (version 0.2.2), so please upgrade to that version with the command
```
conda install spyder-notebook=0.2 -c spyder-ide
```
This will also upgrade Spyder itself.

**Comment by aaronfoe** [comment]
Thanks for your quick reply. Unfortunately the upgrade to Spyder 4 does not work for me after I had to reinstall my Anaconda distribution. It appears to be incompatible with the latest Anaconda version.

**Comment by ccordoba12** [comment]
The next version of Anaconda will come with Spyder 4 by default, so that won't be a problem.
