### ISSUE TITLE
When in full screen mode, Spyder window always stays in the foreground

### ISSUE THREAD

**Issue by IonutBarbu** [spyder-ide/spyder#11767]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If I switch Spyder to full screen mode (F11), then the Spyder windows always stays on top of other program windows that I have opened. Switching to another program (say  Outlook) is then only possible if I exit fullscreen mode from Spyder.

### What steps reproduce the problem?

1. Have at least another application open besides Spyder e.g Chrome 
2. Activate fullscreen mode (F11)
3.  Try to switch to Chrome by Alt+Tab. 

### What is the expected output? What do you see instead?
It will not work. Focus will stay on the Spyder window. Exiting fullscreen mode allows switching to Chrome 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.0.1
* Python version: Python 3.7.1 64-bit   Windows 10 
* Qt version:  Qt 5.9.6
* PyQt version:  PyQt5 5.9.2 
* Operating System name/version: Win 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.7.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.16.4 (OK)
pandas >=0.13.1              :  0.25.0 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  None (NOK)

```

**Comment by ccordoba12** [comment]
> If I switch Spyder to full screen mode (F11), then the Spyder windows always stays on top of other program windows that I have opened. Switching to another program (say Outlook) is then only possible if I exit fullscreen mode from Spyder.

That's how full screen mode works.

**Comment by hsaidc** [comment]
Same problem here, it behaves like "Always on top" is marked. But it shouldn't be like that. Sorry but, full screen does not work like that @ccordoba12. I should be able to switch other windows in full screen mode.

**Comment by danisuar3z** [comment]
> > If I switch Spyder to full screen mode (F11), then the Spyder windows always stays on top of other program windows that I have opened. Switching to another program (say Outlook) is then only possible if I exit fullscreen mode from Spyder.
> 
> That's how full screen mode works.

I use fullscreen mode in various apps and I like to gain that extra space while being able to switch between windows.
I think it would be a nice feature to consider.
Thanks in advance.
