### ISSUE TITLE
freq T not understood - error

### ISSUE THREAD

**Issue by Girl-dev** [spyder-ide/spyder#11777]
### What steps will reproduce the problem?

I used the following code:

decomposition = sm.tsa.seasonal_decompose(ts_log) 

to get 'freq T not understood. Please report if you think this is an error.

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is not a problem with Spyder, so I'm going to close this issue.

It looks an issue with statsmodels. If that's the case, please report it here:

https://github.com/statsmodels/statsmodels

**Comment by Girl-dev** [comment]
Hello,

I'm not sure what that means... I was just trying to post a query, and I
don't know how to post one another way?

Kind regards,

Roo

**Comment by ccordoba12** [comment]
I'm sorry if I was not clear enough before. This issue tracker is only meant to report internal errors about Spyder (e.g. problems saving files, opening IPython consoles, etc).

Your error seems to arise from the code you wrote in Spyder (using statsmodels) and that you're trying to run in the IPython console. Therefore, we can't help you with that here.

I suggest you to open an issue about your error in the above repository or ask for help in:

https://stackoverflow.com/

**Comment by Girl-dev** [comment]
Dear Carlos,

Ah thank you! I’ll try making a post on that site!

Kind regards,

Wurood
