### ISSUE TITLE
Create github action for common repetitive tasks

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#11778]
- [ ] Rebase PRs from master to 4.x and viceversa
- [ ] Update translations
- [ ] Tag zenhub releases based on label and viceversa

**Comment by jitseniesen** [comment]
A loosely related question, just out of interest ... Why are we using GitHub labels and not GitHub releases? I understand that we need something on GitHub that corresponds to ZenHub releases for people that do not use ZenHub.

**Comment by ccordoba12** [comment]
That's a good question. @goanpeca?

**Comment by goanpeca** [comment]
>A loosely related question, just out of interest ... Why are we using GitHub labels and not GitHub releases? I understand that we need something on GitHub that corresponds to ZenHub releases for people that do not use ZenHub.

A github release is a point in time and is attached to a TAG

<img width="1022" alt="Screen Shot 2020-03-12 at 16 46 48" src="https://user-images.githubusercontent.com/3627835/76569480-37538280-6481-11ea-81c2-b0269265e948.png">

A Zenhub release is "like"a milestone in that it groups issues and assign to a "release". Zenhub recommends using milestones for sprints (Fixed amount of work in a given and set period of time)

Some reading that might be useful: https://help.zenhub.com/support/solutions/articles/43000010815-planning-and-executing-a-sprint-with-zenhub

**Comment by ccordoba12** [comment]
> Rebase PRs from master to 4.x and viceversa

Given the huge rewrite happening in master, this is really feasible. In other words, most merges need to be solved manually.

> Update translations

I don't consider this important enough to invest the time needed to build an action. Also, perhaps it's easier to add to our bot, so it works for the entire organization.

> Tag zenhub releases based on label and viceversa

No biggie either.
