### ISSUE TITLE
Error related to Binary image classification 

### ISSUE THREAD

**Issue by Krisanu029** [spyder-ide/spyder#11771]
Epoch 1/5
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-29-d4cd27ec2f96> in <module>
      1 ##fitting the model to images
----> 2 classifier.fit_generator(train_set, steps_per_epoch=98,epochs=5, validation_data=test_set, validation_steps=38)

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   1295         shuffle=shuffle,
   1296         initial_epoch=initial_epoch,
-> 1297         steps_name='steps_per_epoch')
   1298 
   1299   def evaluate_generator(self,

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py in model_iteration(model, data, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, validation_freq, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch, mode, batch_size, steps_name, **kwargs)
    219     step = 0
    220     while step < target_steps:
--> 221       batch_data = _get_next_batch(generator)
    222       if batch_data is None:
    223         if is_dataset:

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py in _get_next_batch(generator)
    361   """Retrieves the next batch of input data."""
    362   try:
--> 363     generator_output = next(generator)
    364   except (StopIteration, errors.OutOfRangeError):
    365     return None

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py in get(self)
    783     except Exception:  # pylint: disable=broad-except
    784       self.stop()
--> 785       six.reraise(*sys.exc_info())
    786 
    787 

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\six.py in reraise(tp, value, tb)
    701             if value.__traceback__ is not tb:
    702                 raise value.with_traceback(tb)
--> 703             raise value
    704         finally:
    705             value = None

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py in get(self)
    777     try:
    778       while self.is_running():
--> 779         inputs = self.queue.get(block=True).get()
    780         self.queue.task_done()
    781         if inputs is not None:

C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

C:\ProgramData\Anaconda3\envs\tf\lib\multiprocessing\pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
    119         job, i, func, args, kwds = task
    120         try:
--> 121             result = (True, func(*args, **kwds))
    122         except Exception as e:
    123             if wrap_exception and func is not _helper_reraises_exception:

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\tensorflow_core\python\keras\utils\data_utils.py in get_index(uid, i)
    569       The value at index `i`.
    570   """
--> 571   return _SHARED_SEQUENCES[uid][i]
    572 
    573 

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\keras_preprocessing\image\iterator.py in __getitem__(self, idx)
     63         index_array = self.index_array[self.batch_size * idx:
     64                                        self.batch_size * (idx + 1)]
---> 65         return self._get_batches_of_transformed_samples(index_array)
     66 
     67     def __len__(self):

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\keras_preprocessing\image\iterator.py in _get_batches_of_transformed_samples(self, index_array)
    228                            color_mode=self.color_mode,
    229                            target_size=self.target_size,
--> 230                            interpolation=self.interpolation)
    231             x = img_to_array(img, data_format=self.data_format)
    232             # Pillow images should be closed after `load_img`,

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\keras_preprocessing\image\utils.py in load_img(path, grayscale, color_mode, target_size, interpolation)
    106         color_mode = 'grayscale'
    107     if pil_image is None:
--> 108         raise ImportError('Could not import PIL.Image. '
    109                           'The use of `load_img` requires PIL.')
    110     img = pil_image.open(path)

ImportError: Could not import PIL.Image. The use of `load_img` requires PIL.

Please help me to resolve this above issue.

**Comment by ccordoba12** [comment]
> ImportError: Could not import PIL.Image. The use of load_img requires PIL.

Please close Spyder, open the Anaconda Prompt and run there

    conda install pillow

For next time please only report here errors related to Spyder (this was an issue with tensorflow).
