### ISSUE TITLE
Environment not loaded if spyder launched with anaconda-navigator 1.9.12 

### ISSUE THREAD

**Issue by mereshow** [spyder-ide/spyder#11776]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Using Spyder in an environment other than base with Anaconda Navigator 1.9.12 does not use the activated environment properly. After several installations, upgrades, etc, I narrowed it down to an anaconda-navigator 1.9.12 and Spyder problem. It does not happen if anaconda-navigator is downgraded to 1.9.7.

### What steps reproduce the problem?
1. Intall Anaconda 2020.02 or update existing to have anaconda-navigator 1.9.12
2. Create a new environment
3. In anaconda-navigator > Home, select the new environment
4. Install and launch Spyder
5. In the status bar (and "Show sys.path contents" we see that the root environment is used

### What is the expected output? What do you see instead?
When an environment is activated, and Spyder is launched in Anaconda Navigator, it should use the activated environment, not the base one.

## Versions
* Spyder version: 4.0.1
* Python version: 3.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 19.10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  None (NOK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment]
> I narrowed it down to an anaconda-navigator 1.9.12 and Spyder problem. It does not happen if anaconda-navigator is downgraded to 1.9.7.

That means that it's not a problem with Spyder but with Navigator. Therefore, please report this issue here:

https://github.com/ContinuumIO/anaconda-issues/issues/
