### ISSUE TITLE
Unable to launch Spyder, Python has stopped working

### ISSUE THREAD

**Issue by seowwy** [spyder-ide/spyder#11779]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm getting the 'Python has stopped working' error on Windows 7 when trying to start Spyder from Anaconda prompt, I don't see the Spyder splash screen, only the windows popup. If I try to open spyder from the start menu, or Anaconda navigator, 'nothing' happens. By nothing, I mean no pop up, no Spyder splash screen, no error messages. I had 4 environments in Anaconda that worked fine previously, but Spyder would not run on any of them.

![Image](https://user-images.githubusercontent.com/24206854/76503582-14c16980-6481-11ea-872f-1bc98da45ad8.png)

When running spyder through Anaconda prompt, there are no traceback error messages in the prompt, once I hit the 'close' button on the windows popup, a new line appears.
![image](https://user-images.githubusercontent.com/24206854/76503943-b648bb00-6481-11ea-8bf0-565b619b2a60.png)

Jupyter (also installed with Anaconda3) runs fine. Previously Spyder has worked for me. I don't recall having done any software installation between the time when Spyder worked and when it stopped working. I have tried creating a new environment in Anaconda and installing Spyder, again, same problem. I tried Spyder 3.3.6 and 4.0.1 and both gave me the same problems. Previously (just a week ago) I have ran both versions of Spyder on the same computer (different environments) with no problems. 

### What steps reproduce the problem?
1. Tried ``conda update python``, ``conda update spyder``, ``conda update anaconda``, ``conda update qt pyqt``. The update either gets completed with no issues, or reports back that the requested packages are already installed, but Spyder is still unable to start up. I checked all the packages listed in the Spyder requirements and they were present and above the minimum required version.
2. I tried to ``cd`` to the ``start.py`` directory and run the ``start.py`` and ``mainwindow.py`` scripts, got the same problem.
3. I have tried uninstalling Anaconda3 and reinstalling with a fresh Anaconda download, both 'Just for me' and 'For all users'. (Computer was restarted after each uninstall.) Ran ``anaconda-clean --yes`` for good measure, and also tried to hunt down any residue Anaconda/Spyder files and deleted them between installs. The same problem persists.
4. Tried to run ``spyder --reset`` and I get the same 'Python has stopped working' error. 

### What is the expected output? What do you see instead?
I expect Spyder to run, instead I saw either nothing happening, or a windows error message saying 'Python has stopped working'

### Paste Traceback/Error Below (if applicable)

Unfortunately there are no error dialogs or messages to help with the troubleshooting.

## Versions

* Spyder version: 4.0.1 (also tried with 3.3.6)
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7 enterprise, service pack 1
Windows firewall has been disabled.
![image](https://user-images.githubusercontent.com/24206854/76503892-a5984500-6481-11ea-9749-03fe2c8e8437.png)

**Comment by ccordoba12** [comment]
I'd suggest you to remove and reinstall Anaconda again. Sorry for the hassle but I see no other choice at the moment.

**Comment by seowwy** [comment]
> I'd suggest you to remove and reinstall Anaconda again. Sorry for the hassle but I see no other choice at the moment.

Any particular way that I should do that? Or things to take note of? Because I have uninstalled and reinstalled at least 5 times now... Probably closer to 10. Certainly I could do it again, but I'm pretty certain by now that repeating the same steps wouldn't help. Thanks!

**Comment by ccordoba12** [comment]
> Because I have uninstalled and reinstalled at least 5 times now

Sorry, I didn't read your original post in detail.

**Comment by ccordoba12** [comment]
You could try to deactivate your firewall and/or antivirus and try again.

**Comment by seowwy** [comment]
> You could try to deactivate your firewall and/or antivirus and try again.

Tried, still unresolved :(

**Comment by ccordoba12** [comment]
Please update to the latest Spyder version (4.1.1) and run there

    spyder --report-segfault

After it crashes, please run again

    spyder --report-segfault

Then a dialog will be shown that will allow you to upload the crash report here to Github.

If no dialog appears, please look for a file called `faulthandler.log` in Spyder's configuration directory (`C:\Users\<your user>\.spyder-py3` on Windows; `/Users/<your user>/.spyder-py3` on macOS; or `/home/<your user>/.config/spyder-py3` on Linux) and upload it here.

**Comment by DuncanMcRae** [comment]
Same issue with me after running conda update --all. Windows 10 and Python 3.8.1.

**Comment by DuncanMcRae** [comment]
conda create --name new
conda activate new
conda install python=3.8.1
conda install spyder
spyder

Runs through the splash screen. Then just loads a full white screen and won't boot properly.

**Comment by ccordoba12** [comment]
@DuncanMcRae, there's no need to step into other people issues and mention the same problem several times (@seowwy said he/she is using Python 3.7).

**Comment by seowwy** [comment]
> Please update to the latest Spyder version (4.1.1) and run there
> 
> ```
> spyder --report-segfault
> ```
> 
> After it crashes, please run again
> 
> ```
> spyder --report-segfault
> ```
> 
> Then a dialog will be shown that will allow you to upload the crash report here to Github.
> 
> If no dialog appears, please look for a file called `faulthandler.log` in Spyder's configuration directory (`C:\Users\<your user>\.spyder-py3` on Windows; `/Users/<your user>/.spyder-py3` on macOS; or `/home/<your user>/.config/spyder-py3` on Linux) and upload it here.

Hi, sorry for the late reply, work has been busy.

I tried updating anaconda navigator, and with it Spyder for updated to 4.1.1, and voilà. It now works... 

I swear I've tried this at least 3 times before but it didn't work. Was there some minor spyder/anaconda update that solved this issue, or was there some update my company did on their side... I guess I would never know.

Yeah, been a few days now and I've not encountered any problems again. Thanks loads!

**Comment by Darshandata** [comment]
Hi, My anaconda navigator was working fine last week, I updated it through terminal by using `conda updated --all` it worked for couple of days fine, but now it is not opening. When I open anaconda navigator it shows error as 'python has stopped working' and never opens. And if I open Spyder directly from start menu, it takes about 5 minutes to launch and after start also doesn't work fast, when I click anywhere it throws error as not responding everytime. I tried uninstalling and reinstalling anaconda but not helped. Please help me.

**Comment by ccordoba12** [comment]
> I updated it through terminal by using conda updated --all it worked for couple of days fine

`conda update --all` is not a good command to use because it usually generates this kind of problems.

I think the best you can do is to uninstall and reinstall Anaconda again. To learn how to properly do that, please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).

**Comment by Darshandata** [comment]
> > I updated it through terminal by using conda updated --all it worked for couple of days fine
> 
> `conda update --all` is not a good command to use because it usually generates this kind of problems.
> 
> I think the best you can do is to uninstall and reinstall Anaconda again. To learn how to properly do that, please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).

Hi I followed that video, but it is not of my problem which is anaconda navigator is not launching, that video is only about spyder. Please help me solve my core problem whcih is, I reinstalled anaconda navigator with removing all envs and pkgs, but it didn't helped. Please help me resolve this.

**Comment by ccordoba12** [comment]
We know the video is about Spyder and your problem is about Navigator, but it comes down to same cause: an installation issue with Anaconda that you need to solve by reinstalling Anaconda.
