### ISSUE TITLE
Adding Persian (Farsi) Language

### ISSUE THREAD

**Issue by spoorgholi74** [spyder-ide/spyder#11785]
Hi, 
As one of my first open-source contributions, I was wondering if you are interested in adding Persian(Farsi) language to Spyder?

**Comment by ccordoba12** [comment]
Thanks a lot for offering your help to help us with that! We need to set up some changes here and after that you could start doing your translation through a web platform called [Crowdin](https://crowdin.com/project/spyder).

For the moment, please open an account in Crowdin and ask to be added to our organization. As soon as everything is ready here, we'll let you know.

**Comment by ccordoba12** [comment]
@goanpeca, please take a look at this one.

**Comment by spoorgholi74** [comment]
@ccordoba12 Is it also possible to work with something like Poedit and submit a PR?

**Comment by ccordoba12** [comment]
That's very brittle and prone to error due to the merge conflicts that appear after updating the po files. So we have discouraged that in favor of Crowdin, sorry.

**Comment by spoorgholi74** [comment]
No problem.
@goanpeca please let me know if you are interested to have this feature.

**Comment by goanpeca** [comment]
@spoorgholi74 thought we do prefer in general to have users/devs and translators use Crowdin, it is fine it you want to use Poedit and make a PR. (It is a bit more work on our side, but having a new translation is worth that ;-) )

However I do encourage you to give https://crowdin.com/project/spyder a try. Just added Persian as Language.

Thanks!

**Comment by spoorgholi74** [comment]
Great! thank you

**Comment by ccordoba12** [comment]
Closing because we did all that was necessary from our side. When you're translation is at least at 90% (as reported by Crowdin), we'll merge it.

Thanks for your help!
