### ISSUE TITLE
Mark draggable tile borders in UI

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#11794]
Spyder UI tiles are resizable by dragging the borders with the mouse.

But there's no way to _find_ where the draggable borders _are_ other than "probing" with the mouse and watching for the mouse cursor to change (on Windows, anyway).

I suggest adding lines to the UI (perhaps in some distinctive thickness or color or pattern), marking the draggable borders, making them quicker to find.

* Spyder version:  3.3.6
* Operating System name/version:  Windows 10 x64

**Comment by ccordoba12** [comment]
> Spyder version: 3.3.6

Spyder 3 is not supported anymore. These kind of borders are shown in our dark theme, available in Spyder 4:

![Selección_001](https://user-images.githubusercontent.com/365293/76686859-caf59200-65ec-11ea-9f33-5c0f7d627eba.png)

**Comment by nerdfever** [comment]
Ah, thanks. Spyder 4 isn't in WinPython yet, I think.

**Comment by ccordoba12** [comment]
Sorry to hear that.
