### ISSUE TITLE
How are plots so pretty?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11802]
Among my main reasons for sticking with Spyder 4 is its SVG-like plot quality. How's this accomplished - can it be reproduced in a Jupyter notebook or JupyterLab? Their `notebook` backends are nice-ish, but still far from Spyder's inline - and their inline is a smudge. I'm seeing the same graphics backend options in Preferences as in Spyder 3, yet visual quality differs significantly.

Alternatively, can Spyder's IPython console be 'used in' JupyterLab?

**Comment by ccordoba12** [comment]
> How's this accomplished

I don't think we do anything special about it, but @jnsebgosselin is the one who created that plugin, so he knows better.

> can it be reproduced in a Jupyter notebook or JupyterLab?

Could you post screenshots of what you see in Spyder 4 and the notebook? I'm curious to see the difference between both outputs.

> and their inline is a smudge

Did you customize our inline backend to get better resolution? I say it because you can do the same in the notebook, the only problem is that they don't offer graphical options for that.

> I'm seeing the same graphics backend options in Preferences as in Spyder 3, yet visual quality differs significantly.

Again, could you post Spyder 3, 4 and notebook screenshots? Thanks!

> Alternatively, can Spyder's IPython console be 'used in' JupyterLab?

Well, you can connect one of our IPython consoles to an already running notebook, but it can't be embedded in JupyterLab (if that's what you want).

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Strange... Spyder 3's are now identical to 4's - and looking through my old screenshots, nothing particularly distinct. I might be under a false impression.

Spyder definitively stomps Jupyter (and Colab), though - here are some screenshots along them gif'd (quality degraded), and reproducing source code below:

<img src=https://user-images.githubusercontent.com/16495490/76745113-bea93a80-678e-11ea-8a87-efb4f50215e5.png width="600">

<img src="https://user-images.githubusercontent.com/16495490/76745130-c537b200-678e-11ea-895d-64c9f39674cb.png" width="600">

<img src="https://user-images.githubusercontent.com/16495490/76745139-c79a0c00-678e-11ea-8697-9977ad353edd.png" width="600">

<img src="https://user-images.githubusercontent.com/16495490/76745170-d680be80-678e-11ea-89b9-226f9bad25e1.png" width="600">

<img src="https://user-images.githubusercontent.com/16495490/76745153-cf59b080-678e-11ea-9bc6-aeac5814c7b4.png" width="600">

![image](https://media.giphy.com/media/cj8YLFhIMvDgKowEfS/giphy.gif)

![image](https://media.giphy.com/media/iDgEZg0JpXAIwgyLIA/giphy.gif)

<hr>

**Code**:

```python
import numpy as np
import matplotlib.pyplot as plt


def test(scaling=1):
    def _style_and_show(w, h, scaling, noticks=True):
        plt.gcf().set_size_inches(w * scaling, h * scaling)
        if noticks:
            plt.xticks([])
            plt.yticks([])
        plt.show()

    np.random.seed(1)
    x = np.random.randn(400, 400)
    for w, h, noticks in [(4, 4, False), (9, 9, True)]:
        plt.imshow(x, cmap='bwr')
        _style_and_show(w, h, scaling, noticks)
    
    np.random.seed(1)
    y = np.random.randn(10000)
    plt.hist(y, bins=500)
    _style_and_show(9, 4, scaling)
    
scaling = (5.17 / 4)  # jupyter-to-spyder
# test()         # jupyter
test(scaling)  # spyder
```

_Note_: had to rescale to match # of pixels, maybe per each using a different DPI setting. For Spyder:

<img src="https://user-images.githubusercontent.com/16495490/76747202-37f65c80-6792-11ea-83d5-5e69997b309f.png" width="300">

**Comment by OverLordGoldDragon** [comment]
And JUST as I pasted the last image, I searched "Jupyter DPI", and StackOverflow spit out the fix:

```
%config InlineBackend.figure_format = 'retina'
```

Fun times.

**Comment by ccordoba12** [comment]
> Fun times.

Yeah, we plan to activate that option by default in 4.2 when we detect a HiDPI display. That's the advantage of Spyder being a desktop app: we can very simply detect and set those things on behalf of the users.
