### ISSUE TITLE
IPython shell commands fail to update a defined function after running program in the editor

### ISSUE THREAD

**Issue by AGD60** [spyder-ide/spyder#11827]
### What steps will reproduce the problem?

I created a short program containing a definition of a function called show_flashcard(). To test the function, I ran the program, then entered q to quit, then set the value of user_input = 'e' in the IPython shell, then called the function show_flashard() in the shell. It still uses 'q' rather than new value of user_inout = 'e' (or any new value). The program is

```python
from random import *
easy_glossary = {'word1':'defn1', 'word2':'defn2'}
hard_glossary = {'word2':''defn1','word2':'defn2'}
def show_flashcard():
    glossary_type = {'e':easy_glossary, 'h':hard_glossary}
    glossary = glossary_type[user_input]
    random_key = choice(list(glossary))
    print('Define: ', random_key)
    input('Press return to see the definition')
    print(glossary[random_key])

exit = False
while not exit:
    user_input = input('Enter e to show an easy flashcard, h to show a hard flashcard, or q to quit')
    if user_input == 'q':
        exit = True
    elif user_input == 'e' or user_input == 'h':
        show_flashcard()
    else:
        print('You need to enter either e, h, or q.')
```
    

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
If you want IPython to run its [`%autoreload` magic](https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html), you need to import your function, not simply run it, i.e. to execute

    from foo import show_flashcard

then run your input code.

**Comment by AGD60** [comment]
Thank you for the prompt reply. If I first type
from foo import show_flashcard
in the IPython console, I get the error message
No module named 'foo'

**Comment by ccordoba12** [comment]
That's because I don't know how the file where you put your `show_flashcard` is named. So I just used `foo` as if that file was named `foo.py`.

This is all the help I can give you. If you want to learn about Python import mechanism, please google for it.

**Comment by AGD60** [comment]
Thanks Carlos, I appreciate your help. I have been researching import statements for IPython, it is more involved than I thought.
