### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Manojkumar-code** [spyder-ide/spyder#11831]
runfile('C:/Users/Admin/.spyder-py3/temp.py', wdir='C:/Users/Admin/.spyder-py3')

**Comment by Manojkumar-code** [comment]
> runfile('C:/Users/Admin/.spyder-py3/temp.py', wdir='C:/Users/Admin/.spyder-py3')

**Comment by ccordoba12** [comment]
This is not an error. It's the command used to run files in Spyder.
