### ISSUE TITLE
Spyder not starting on macos High Sierra: "Python quit unexpectedly"

### ISSUE THREAD

**Issue by EdoSiggi** [spyder-ide/spyder#11849]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Trying to open spyder IDE from Anaconda Navigator or from Terminal result in a "Python quit unexpectedly" error on macos High Sierra 10.13.6. 
I've tryed the commands `conda update --all`, `conda update spyder`, `conda update python`, `conda update python python.app` and `conda update python.app` all resulting in the message 

> `# All requested packages already installed.`

### What steps reproduce the problem?

1. Open Spyder from Anaconda Navigator or from Terminal
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macos High Sierra 10.13.6

### Dependencies
```
PASTE DEPENDENCIES HERE
```

**Comment by EdoSiggi** [comment]
Any updates regarding the fix?

**Comment by ccordoba12** [comment]
Please update to the latest Spyder version (4.1.1) and run there

    spyder --report-segfault

After it crashes, please run again

    spyder --report-segfault

Then a dialog will be shown that will allow you to upload the crash report here to Github.

If no dialog appears, please look for a file called `faulthandler.log` in Spyder's configuration directory (`C:\Users\<your user>\.spyder-py3` on Windows; `/Users/<your user>/.spyder-py3` on macOS; or `/home/<your user>/.config/spyder-py3` on Linux) and upload it here.

**Comment by EdoSiggi** [comment]
I tried to do that from terminal (I'm on macOS) but every time I try to run Spyder it says: `/Users/<user>/opt/anaconda3/bin/pythonw: line 3:  4885 Illegal instruction: 4  /Users/<user>/opt/anaconda3/python.app/Contents/MacOS/python "$@"`
and no file was generated.

**Comment by ccordoba12** [comment]
Ok, then that's the problem. Please run in the terminal

    conda install -f python.app

and try again.

If that doesn't fix the problem, please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/
