### ISSUE TITLE
DOC: after 'pip install' you can run spyder via python -mspyder.app.start

### ISSUE THREAD

**Issue by mattip** [spyder-ide/spyder#11864]
Spyder works well with `pip install` (on Ubuntu 180.4 at least), but it does not create a binary in `venv/bin/spyder`. I found I could start it with `python -mspyder.app.start`. What would be preferable: a PR to add a binary shim, or a PR to document this way to start spyder? Maybe both?

**Comment by ccordoba12** [comment]
The binary is called `spyder3`, if you install in a virtualenv with Python 3.
