### ISSUE TITLE
Code folding disabled w/ <2000 lines (4.1.1)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11869]
[demo](https://puu.sh/Fmns3/ccc8ec6539.mp4); release notes state it should only happen for files w/ >2000 lines (which hopefully won't be needed in a future version) - but folding's disabled for 300-liners also.

_Note_: also occurs in 4.1

**Comment by ccordoba12** [comment]
You're right. I don't understand how we miss this one. We'll fix it in 4.1.2.
