### ISSUE TITLE
Error python 3.6 _handle_remote_call_reply()

### ISSUE THREAD

**Issue by pretoronix** [spyder-ide/spyder#11906]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I just openend anaconda spyder the first time. I just have install anaconda in a virtual environment and started spyder over the console in the envoronment.

**Comment by ronnychou** [comment]
just like it:
> Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "E:\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "E:\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'

**Comment by ccordoba12** [comment]
@ronnychou, you're using the wrong version of spyder-kernels.

The pairing of versions between Spyder and spyder-kernels is:

* For Spyder 4.0.1 and 4.0.0 you need spyder-kernels 1.8.1
* For Spyder 4.1.0 and 4.1.1 you require spyder-kernels 1.9.0

This is clearly reported by our dependencies dialog at the beginning, so please read those messages for next time.
