### ISSUE TITLE
"Please verify that your firewall or antivirus allows Python processes to open ports in your system"

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#11901]
What does the quoted excerpt mean in terms of what I should configure in the antivirus? Add python.exe's path, or PYTHONPATH, to exceptions? Add Spyder, Anaconda - all of the above? Don't know what's meant by "open ports."

(But yes, a restart does work)

<img src="https://user-images.githubusercontent.com/16495490/77215177-27483c80-6b2c-11ea-80e7-b9501002d670.png" width="380">

**Comment by ccordoba12** [comment]
python.exe should be enough.

**Comment by ccordoba12** [comment]
Please try that and let us know if that works for you.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Can't tell; while the same error no longer pops up after many hours of working with several large files, various linter functionalities still die - e.g.:

![image](https://user-images.githubusercontent.com/16495490/77239614-254ab000-6bf6-11ea-8d14-01bbc844b0e4.png)

**Comment by OverLordGoldDragon** [comment]
... aaand it popped up.

**Comment by ccordoba12** [comment]
Let's close this as a duplicate of #11026. We'll try to restart the server automatically in the background if it fails.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 It now popped up only 30 mins into the session - also forgot to mention, once it shows up it "never leaves"; almost anything I do makes it pop-up again, rather obnoxiously - [demo](https://puu.sh/FpUVH/02a7ec5752.mp4). This time the line sum-total was 979 across 6 files, max 376 per file.

**Comment by ccordoba12** [comment]
See PR #12020.

**Comment by Chabole** [comment]
Any one have fixed the problem ?

**Comment by lwade-biomech** [comment]
I am also suddenly getting this issue. Only thing i can think of that might have changed was that i updated Anaconda
