### ISSUE TITLE
after updating Spyder and lauch this error shows up. 

### ISSUE THREAD

**Issue by mlearnx** [spyder-ide/spyder#11905]
### What steps will reproduce the problem?

import mne
Traceback (most recent call last):

  File "<ipython-input-1-d70f97b8aea9>", line 1, in <module>
    import mne

  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/mne/__init__.py", line 22, in <module>
    from .utils import (set_log_level, set_log_file, verbose, set_config,

  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/mne/utils/__init__.py", line 9, in <module>
    from .check import (check_fname, check_version, check_random_state,

  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/mne/utils/check.py", line 14, in <module>
    from ._logging import warn, logger

  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/mne/utils/_logging.py", line 15, in <module>
    from ..fixes import _get_args

  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/mne/fixes.py", line 21, in <module>
    from scipy import linalg

  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/scipy/__init__.py", line 63, in <module>
    from numpy import show_config as show_numpy_config

ImportError: cannot import name 'show_config' from 'numpy' (unknown location)

### Traceback
```python-traceback
  File "/home/user/.conda/envs/mne/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

During handling of the above exception, another exception occurred:

ImportError: numpy.core.multiarray failed to import
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.0-42-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.9 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  None (NOK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment]
This happens because you probably installed numpy with pip and not with conda. This is not our fault.

Besides, by doing that you probably corrupted your Anaconda installation, so now you have to remove it and reinstall it again.
