### ISSUE TITLE
Possible to remove line separators in current cell? (dark theme)

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#11907]
I'm using the new Spyder-Dark theme

Is there any way to separate the line separators that are displayed between the lines when a cell is highlighted? That means, highlight the whole cell background? 

![Capture](https://user-images.githubusercontent.com/14980558/77228093-37403a80-6b85-11ea-85f8-d64d837818ea.PNG)

edit: I just see that they've been there in the light theme as well, just almost invisible due to the little color difference.

**Comment by goanpeca** [comment]
@skjerns yes we should be able to remove this. Future work :-)

**Comment by ccordoba12** [comment]
I don't understand what you mean @skjerns.

**Comment by skjerns** [comment]
the background color leaves lines between the highlightes cell lines (the spacing).

I mean the black lines between the lines. Does that make sense?

**Comment by ccordoba12** [comment]
I haven't noticed that. What resolution does your screen have?

**Comment by skjerns** [comment]
2560x1440 with scaling 200% (Windows 10). That might indeed be the culprit! I'm having scaling trouble in other applications as well (fonts and input boxes to small/big)

**Comment by ccordoba12** [comment]
Closing because this doesn't look like an Spyder issue.

**Comment by OverLordGoldDragon** [comment]
Same problem for me after moving from 1920x1080 to 2560x1600. Changing `Scale` from 175% to 100% doesn't help (recommended default is 150%, Windows 11). 

Only happens in _highlighted_ cells. It's fairly distracting. Disabling `Preferences > Editor > Display > Highlight current cell` fixes it, but highlighting is useful. I still opted to disable for now.

**Comment by ccordoba12** [comment]
> Changing Settings > System > Display > Scale from 175% to 100% doesn't help (recommended default is 150%, Windows 11).

Changing to other scale factors (e.g. 200%) could help, at least according to the comments above.

> Changing resolution to 1920x1080 also didn't help, but I tested incompletely (didn't restart computer or Spyder).

I think that requires restarting Spyder at least.

**Comment by OverLordGoldDragon** [comment]
With restarting:

  - 2560x1600 150%, 175%, 200% and 1920x1080 150% didn't work
  - 2560x1600 100%, 125% and 1920x1080 100%, 125% worked

Whatever does work makes everything else look awful, including outside Spyder. Unlike @ skjerns, I'm not seeing issues in nearly any other application, though of course it's true some will fail. It does seem to be a Spyder issue to me, seems fair to expect that at least native settings work across devices ("recommended" `Scale`).

**Comment by OverLordGoldDragon** [comment]
DPI scaling can also cause/fix this, `Preferences > Application > Interface > Screen resolution`, e.g. `Set a custom high DPI scaling`. Now I have black lines that are spaced out. It seems the black lines are always there, they simply disappear (height rounds to zero) with certain resolution settings.
