### ISSUE TITLE
Spyder 4.1.1 Plots in plot pane are not interactive

### ISSUE THREAD

**Issue by conmccann1** [spyder-ide/spyder#11900]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When looking at plots in the plot pane the zoom buttons are faded out and the image quality of the plots is not the same as pop out figures.

### What steps reproduce the problem?

N/A since any plot in the plot pane is not interactive for me

### What is the expected output? What do you see instead?

I expect to be able to interact with plots in the plot pane but only see a picture instead

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.4 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

```

**Comment by ccordoba12** [comment]
> When looking at plots in the plot pane the zoom buttons are faded out and the image quality of the plots is not the same as pop out figures.

You need to go to the Plots options menu, and deactivate the option called `Fit plots to window`:

![Selección_001](https://user-images.githubusercontent.com/365293/77210876-17027400-6ad0-11ea-892d-22344c7bfffc.png)

Then you'll be able to zoom in/out them.

About the quality, it'll be improved in one of our next releases for high resolution screens.

**Comment by michael-greenwood** [comment]
I think what the original poster wants is :
Tools-Preferences->ipython console
go to graphics tab, 
change backend to automatic
restart your kernel

Then you plots will open in a separate window which allows you to interact with them.

Not a bug, this is still functional.
