### ISSUE TITLE
An issue with the "File Association" example in the settings

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#11919]
## Problem Description
When adding file associations, the example in the pop-up dialog "x.json,x,csv" should be "x.json,x.csv".(I don’t know how to enter the star symbol, sometimes it is displayed successfully, sometimes it is not displayed)

Same for edit dialog!

![image](https://user-images.githubusercontent.com/1759365/77279046-da1ac500-6cfb-11ea-8826-5a33e963783b.png)

### What steps reproduce the problem?

Click Preferences-Files-File Associations-File Types Add

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win10

**Comment by ccordoba12** [comment]
> I don’t know how to enter the star symbol, sometimes it is displayed successfully, sometimes it is not displayed

This is probably an issue because you're using a Chinese version of Windows. Please confirm.

**Comment by leavor** [comment]
> > I don’t know how to enter the star symbol, sometimes it is displayed successfully, sometimes it is not displayed
> 
> This is probably an issue because you're using a Chinese version of Windows. Please confirm.
I mean enter the star symbol in the edit box of github issue, so I use "x" instead when describing the problem.
Please see my screenshot, an example of file association. Obviously, the comma in front of csv should be a dot.
This is just a display issue

**Comment by ccordoba12** [comment]
Oh, I see. I understand now. We'll fix it in a future release.
