### ISSUE TITLE
Interactive tour - suspension of the 3rd page

### ISSUE THREAD

**Issue by StBanas** [spyder-ide/spyder#11913]
### What steps will reproduce the problem?

1. Opened Spyder from Anaconda Navigation set. My system is Manjaro on 64 Dell studio  notbook. 
2. from pull-down menu "Help" choosen "Interactive Tour" 
3. First page was ok went to second page
4. Second page was ok. went to the third
6. 3rd page haden't developed - only one part with "IPython console" was active, the small window with the pages numbers (activ available with links to the next pages window) was in ie. on and off (apearing and vanishing on and off)
7. I had to close all active applications and reboot system  to get rid of the page (and the low information folder at the bar)

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.14.30-1-MANJARO

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.17.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Are you using Wayland in your system?

**Comment by StBanas** [comment]
Hi,
I don't use Wayland (as far as I know).

niedz., 22 mar 2020 o 19:21 Carlos Cordoba <notifications@github.com>
napisał(a):

**Comment by ccordoba12** [comment]
Sorry but this seems very specific to your Linux distro. I'm a Linux user myself (Kubuntu 19.04 at the moment) and everything works fine for me.

Although I understand this is a valid bug, we really don't have time create a virtual machine with your specs and try to understand what's happening there, sorry,

**Comment by StBanas** [comment]
This is ok. I will use Spider any way as it seems to be user friendly. In case of any other problems I will let you know about it. Regards
Piotr
