### ISSUE TITLE
Run in console's namespace with existing kernel not working

### ISSUE THREAD

**Issue by davidaue** [spyder-ide/spyder#11923]
I cannot access variables from an existing kernel hooked to spyder from a spyder script.
I am trying to use spyder with an embedded kernel from a C# application and there are things in the kernels namespace I need to access. They are accessible in the console but not from scripts. I'd be happy for any way to accomplish this.

**Repro**

Start a spyder kernel:
      python -m spyder_kernels.console

In spyder connect a console to this existing kernel
Set configuration per file to use the current console and "Run in console's namespace"

In the console set a variable:
In []:   x = 5

Run a script in spyder to print that variable:
print(x}

You get:
   NameError: name 'x' is not defined

This works if I use a console made in spyder but not with an existing kernel.

**Comment by davidaue** [comment]
I see that with the console made in spyder the script is run with: 
runfile('C:/home/.spyder-py3/temp.py', wdir='C:/home/.spyder-py3', current_namespace=True)

Whereas in the existing kernel it's:
%run "C:\home\.spyder-py3\temp.py"

Can I get spyder to use runfile with the existing kernel?

**Comment by ccordoba12** [comment]
@davidaue, thanks for reporting. The fix shouldn't be that hard.

@dalthviz, please take a look at this one. We should use `runfile` for external kernels that are in fact spyder-kernels (that's decided in the IPython console plugin module).

**Comment by ccordoba12** [comment]
Just for reference: I think this problem

https://stackoverflow.com/questions/41530184/spyder-run-script-located-on-remote-server

will be fixed when we fix this too.
