### ISSUE TITLE
main.py: error: the following arguments are required: -fs/--fs_functions, -s/--score_name

### ISSUE THREAD

**Issue by aliarrshad** [spyder-ide/spyder#11929]
if __name__ == "__main__": 
    argv = sys.argv[1:]
parser = argparse.ArgumentParser()
parser.parse_args()
# DATASETS
# 'KC3', 'PC2', 'PC4', 'ant', 'camel', 'MC1'
# fs_functions: pearson, fisher, greedy_auc, greedy_gmeans
# fs_functions defines the forward selection functions
parser.add_argument('-fs','--fs_functions', nargs="+", required=True,
                    choices=["pearson", "fisher", "greedy"])

parser.add_argument('-m','--method', default="forward_selection",
                    choices=["forward_selection","ensemble_svm",
                             "ensemble_heter"])

parser.add_argument('-d','--dataset_name', default="ant")

parser.add_argument('-n','--n_clfs', default=5, type=int)

parser.add_argument('-s','--score_name', required=True,
                     choices=["auc","gmeans"])

args = parser.parse_args()    
  
method = args.method
dataset_name = args.dataset_name
fs_functions = args.fs_functions
n_clfs = args.n_clfs
score_name = args.score_nam

**Comment by ccordoba12** [comment]
Please see this to understand how to pass arguments to a script in Spyder:

https://stackoverflow.com/questions/26679272/how-to-use-argv-with-spyder/
