### ISSUE TITLE
Tornado issue with Py38, windows & spyder

### ISSUE THREAD

**Issue by hyamanieu** [spyder-ide/spyder#11928]
Spyder 4.1.1 on a conda env with Python 3.8 on windows cannot start.

It seems to be linked to this `tornado `issue: https://github.com/tornadoweb/tornado/issues/2608
The solution for this issue is additional documentation: https://github.com/tornadoweb/tornado/pull/2686/commits/aa879d1934e36fd81f49535cd3a1d5bc60b0e044

I am not sure exactly where you must add these lines in your code:

```
import sys

if sys.platform == 'win32':
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```

I found out about it by reading the log upon starting Spyder with `spyder --debug-info verbose`. Here are the last bits with the traceback:

> 2020-03-23 11:09:17,493 [ERROR] [tornado.application] -> Exception in callback functools.partial(<function ThreadedZMQSocketChannel.__init__.<locals>.setup_stream at 0x000002F86CEB7790>)
> Traceback (most recent call last):
>   File "C:\Users\hy.amanieu\AppData\Local\Continuum\anaconda3\envs\pyviztest2\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
>     ret = callback()
>   File "C:\Users\hy.amanieu\AppData\Local\Continuum\anaconda3\envs\pyviztest2\lib\site-packages\jupyter_client\threaded.py", line 47, in setup_stream
>     self.stream = zmqstream.ZMQStream(self.socket, self.ioloop)
>   File "C:\Users\hy.amanieu\AppData\Local\Continuum\anaconda3\envs\pyviztest2\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
>     self._init_io_state()
>   File "C:\Users\hy.amanieu\AppData\Local\Continuum\anaconda3\envs\pyviztest2\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
>     self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
>   File "C:\Users\hy.amanieu\AppData\Local\Continuum\anaconda3\envs\pyviztest2\lib\site-packages\tornado\platform\asyncio.py", line 100, in add_handler
>     self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
>   File "C:\Users\hy.amanieu\AppData\Local\Continuum\anaconda3\envs\pyviztest2\lib\asyncio\events.py", line 501, in add_reader
>     raise NotImplementedError
> NotImplementedError

**Comment by ccordoba12** [comment]
This is not something we can solve here, sorry. In the meantime please use Python 3.7 or create a Python 3.8 environment with spyder-kernels and  change your main interpreter to it, as explained here:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

**Comment by maximlt** [comment]
Just to report that I've had the same issue while trying to create a fresh environment with spyder installing it with the following command:
``conda create -n spyder spyder``.
Launching spyder from the command line didn't report any error, I had a launch it with ``--debug-info minimal`` to spot the error and arrive here :D !

It worked fine with ``conda create -n spyder spyder python=3.7``.

**Comment by ccordoba12** [comment]
@maximlt, support for Python 3.8 on Windows will come in our next version (4.1.3), to be released this week.
