### ISSUE TITLE
Not a smooth update at all -- come on spyder...

### ISSUE THREAD

**Issue by Nathaniel3133** [spyder-ide/spyder#11922]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
I don't know understand what you're referring to, so closing, sorry.

**Comment by Nathaniel3133** [comment]
I’m not sure what’s wrong. But I just spent the last 4 hours
troubleshooting anaconda navigator. It started with Spyder erring out upon
start up I’m not sure if this was because of the Spyder 4 update or not. I
think there are just a lot of inconsistencies between dependency versions.
If I run into any other error messages I will copy them and send them to
you all.

**Comment by ccordoba12** [comment]
Sorry to hear that. I think the easiest way to update Spyder is installing it in a new conda env.
