### ISSUE TITLE
Spyder 4.1.1 crashed constantly for Python 3.7 and Win7-64bit

### ISSUE THREAD

**Issue by tyNeanderthal** [spyder-ide/spyder#11926]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder freezes and crashes with message "this program has stopped working"
I experienced the same with 4.0.0 and 4.1.0, see 11037

### What steps reproduce the problem?

1. Reinstall Spyder 4.1.1
2. Launch Spdyer from Anaconda prompt, Anaconda Navigator, or quick access
3. Wait for abou 10 seconds (doing nothing within Spyder)

### What is the expected output? What do you see instead?

Spyder is expected to be stable with no operation runing whatsoever. It crashes.

### Paste Traceback/Error Below (if applicable)

```python-traceback

I ran "spyder --debug-info verbose --debug-output file"
and attached the log
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/4368370/spyder-debug.log)

```

## Versions

* Spyder version: 4.1.1.
* Python version: 3.7.0 64-bit
* Qt version: 5.6.2
* PyQt version: PyQt5 5.6
* Operating System name/version: Windows 7 64-bit

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.10.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.4.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  2.2.2 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  2.2.2 (OK)
numpy >=1.7                    :  1.17.4 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.3.2 (OK)
sympy >=0.7.3                  :  1.4 (OK)

**Comment by tyNeanderthal** [comment]
Reattching the log
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/4368374/spyder-debug.log)

**Comment by ccordoba12** [comment]
> Qt version: 5.6.2
PyQt version: PyQt5 5.6

These versions are too old. Please open the Anaconda prompt and run there

    conda install pyqt=5.9 qt=5.9

and try again.

**Comment by DuncanMcRae** [comment]
I have pyqt @ 5.12.3 and qt @ 5.12.5 after a conda update --all and my spyder 4.1.1 doesn't even boot. It has the splash screen and then just a full white screen. My old_spyer env with 4.0.1 still works.

Windows 10 and Python 3.8.1

**Comment by ccordoba12** [comment]
> Windows 10 and Python 3.8.1

There are still problems like the one you mentioned with Python 3.8. Please use 3.7 for now.

**Comment by tyNeanderthal** [comment]
> 
> 
> > Qt version: 5.6.2
> > PyQt version: PyQt5 5.6
> 
> These versions are too old. Please open the Anaconda prompt and run there
> 
> ```
> conda install pyqt=5.9 qt=5.9
> ```
> 
> and try again.

Problem resolved with:
Python 3.7.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 7
