### ISSUE TITLE
Tests are fragile

### ISSUE THREAD

**Issue by ElieGouzien** [spyder-ide/spyder#11930]
## Problem Description

Tests are not robust ; in particular, the following lines induce failures of Azur pipeline Windows-3.6-slow:
https://github.com/spyder-ide/spyder/blob/1142a7643c754d2edb0154c18fbdb6baa0af7fc6/spyder/plugins/editor/widgets/tests/conftest.py#L236-L237

Even if it's possible to live with this problem since it doesn't affect users, it's very frustrating for contributors to spend way more time trying to fix "random" behavior of tests than actually working on the proposed fix. Notice that this failure can't be tested locally.

### What steps reproduce the problem?

1. copy content of /spyder/plugins/editor/widgets/tests/test_completion.py into /spyder/plugins/editor/widgets/tests/test_introspection.py
2. Run azur pipeline, Windows 3.6-slow will (maybe) fail

### What is the expected output?

More robust tests.

### What was tried to fix the issue?
I tried changing the timeout to 60000 (in #11916) , without effect.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this after we release Spyder 4.1.2

**Comment by impact27** [comment]
Random idea: A lot of tests are `@flaky`. Can the CI system log which one fail so we can have statistics of which tests are very flaky and try to improve them?
