### ISSUE TITLE
cannot make comment in *.sh file

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#11934]
I am using the latest version of spyder 4.1.1.
for a *.sh file it cannot make a line to be a comment.
It will be useful to add for the future I guess.
Thanks

**Comment by ccordoba12** [comment]
It's working fine for me on Linux. I'm sorry but I'm going to close this issue because you didn't bother to fill the info we require from users (like Operating system, Spyder version, Qt/PyQt versions, etc).

If you want us to take a look at this, please open a new issue with that info filled.
