### ISSUE TITLE
I'm not able to find files/folder when I go to directory...

### ISSUE THREAD

**Issue by JCalucag** [spyder-ide/spyder#11941]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/josecalucag/anaconda/lib/python3.5/site-packages/spyder/plugins/__init__.py", line 425, in visibility_changed
    self.refresh_plugin()   # To give focus to the plugin's widget
  File "/Users/josecalucag/anaconda/lib/python3.5/site-packages/spyder/plugins/explorer.py", line 92, in refresh_plugin
    self.treewidget.update_history(new_path)
  File "/Users/josecalucag/anaconda/lib/python3.5/site-packages/spyder/widgets/explorer.py", line 1107, in update_history
    directory = osp.abspath(to_text_string(directory))
  File "/Users/josecalucag/anaconda/lib/python3.5/posixpath.py", line 361, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
