### ISSUE TITLE
About the mark "x" when a parameter or function is undefined in the code

### ISSUE THREAD

**Issue by ahmida-bendjoudi** [spyder-ide/spyder#11943]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Dear Spyder programmer, 
sometimes a user uses variables from other files (which are defined in console, i.e. files have been run before), i.e. these variables are defined with respect to console, but Spyder still shows the mark "x", 

it would be better if you allow users to remove this mark (if they want, i.e. based on choice)

**Comment by goanpeca** [comment]
>sometimes a user uses variables from other files (which are defined in console, i.e. files have been run before)

This is a bad practice and is not reproducible work. The editor is correctly indicating that the variable does not exist as it has not been defined, so this is not something we will add a configuration for.

**Comment by ccordoba12** [comment]
I agree, that's a really, really bad practice: you shouldn't depend on the variables defined in the console to write code in the editor. Besides, the default behavior in Spyder 4 gives an error when that happens.

**Comment by ahmida-bendjoudi** [comment]
yes, I agree "it is a bad practice",
however, when some files are supposed to run (let us say:  x) to compute long calculation, it should be run only once (because they take long time),
then their results are used in other codes from other files, this is the reason for which I write

**Comment by ccordoba12** [comment]
Sorry but we're not going to promote bad practices through Spyder.

**Comment by ahmida-bendjoudi** [comment]
Anyway, it is not a big deal, I can copy-paste the code into the console and it will work
