### ISSUE TITLE
The 'go to definition (ctrl +G)'  often doesn't work  after updated Spyder4.

### ISSUE THREAD

**Issue by CharMingF** [spyder-ide/spyder#11948]
What steps will reproduce the problem?
Hi! Nice to meet you!
I enjoy the Spyder4,Thanks a lot.

The 'go to definition (ctrl +G)'  often doesn't work  after updated Spyder4.

My system environment is follow

Win10 education,1909 18363.720

"go to definition (ctrl +G) or ctrl+click" key wrok well  after spyder lanch,but it can't work once `go to definition` open the new file for fuction in library such as pandas and matplots, or switch other file ues the key and reback the previous file,the key doesn't work.  

It work when I restart spyder4.

Versions
Spyder version: 4.1.1
Python version: 3.7.6
Qt 5.12.5 
PyQt5 5.12.3 
Windows 10

**Comment by ccordoba12** [comment]
That doesn't work all the time, sometimes it works and sometimes it fails. That's a current limitation for which there's no solution, sorry.
