### ISSUE TITLE
Internal error of spyder from anaconda or conda-forge with spyder-kernels

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#11959]
## Problem Description
Spyder starts off with an internal error message window which keeps popping up. The error hints at something in the spyder-kernels. It may be related to Issue #11798. But the solution proposed there, i.e. to use Anaconda does not apply, since it is exactly Anaconda which is used for the present issue.

### What steps reproduce the problem?
Start spyder

### What is the expected output?
spyder gui

### What do you see instead?
Window with error message superimposed on gui: "Spider has encountered an internal problem!"

## Traceback
  File "/home/userX/.anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/home/userX/.anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/home/userX/.anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for fa92a2ae6def11eabb7bc85b767e8801
Traceback (most recent call last):
  File "/home/userX/.anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "/home/userX/.anaconda3/lib/python3.7/site-packages/qtconsole/comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "/home/userX/.anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'

## Versions
* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Linux kernel 4.12.14-lp151.28.40-default 

## Dependencies
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  2.4.4 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.0 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.2.1 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
You're using the wrong version of spyder-kernels. Please update to our latest version (4.1.1), which fixes this problem.
