### ISSUE TITLE
key bindings/shortcuts on Mac: F9 key

### ISSUE THREAD

**Issue by massimopinto** [spyder-ide/spyder#11969]
## Problem Description
On Spyder 4.1.1 on Mac, the keyboard shortcut ```F9``` to "Run selection or current line" is not functional. This isssue was discussed on StackExchange [before for Spyder 3.1.4](https://stackoverflow.com/questions/43962568/python-spyder-3-1-4-shortcut-macos-sierra-10-12-4). HItting the ```fn + F9``` activates a different action on Mac OS 10.13.6 

### What steps reproduce the problem?

1. ```F9``` key shortcut not operative

### What is the expected output? What do you see instead?
Expected: "Run selection or current line"
Instead: Active program windows demagnified to be all visibile on screen 

## Versions

* Spyder version: 4.1.1.
* Python version: 3.7.0
* Qt version: 5.9.7
* PyQt version: 5.9.2 
* Operating System name/version: OS 10.13.6

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Sorry but the only solution for now is to remap that shortcut to something that works for you in `Preferences > Keyboard shortcuts`.

We're planning to add shortcuts that work well for macOS in our 4.2.0 version, to be released in two or three months.
