### ISSUE TITLE
spyder-kernels < 1.0 is required (found 1.9.0) when launching spyder 4.1.1

### ISSUE THREAD

**Issue by DaPiePiece** [spyder-ide/spyder#11974]
### Issue Report Checklist

* [done] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [done] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [done] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [done] Tried basic troubleshooting (if a bug/error)
    * [done] Restarted Spyder
    * [can't do, doesn't run] Reset preferences with ``spyder --reset``
    * [done] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [done] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

after updating to spyder 4.1.1 and to spyder-kernels 1.9.0, all versions of spyder won't launch.

### What steps reproduce the problem?

1. "conda update spyder" in the anaconda console

### What is the expected output? What do you see instead?

I expect spyder to launch. It doesn't.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\user\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\spyder\app\start.py", line 178, in main
from spyder.app import mainwindow
File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\spyder\app\mainwindow.py", line 49, in 
requirements.check_spyder_kernels()
File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\spyder\requirements.py", line 66, in check_spyder_kernels
% actual_ver)
File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\spyder\requirements.py", line 24, in show_warning
raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels 

```

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7 Professional 64-bit

### Dependencies

```
atomicwrites >=1.2.0
chardet >=2.0.0
cloudpickle >=0.5.0
diff-match-patch >=20181111
intervaltree
jedi 0.15.2.*
keyring
nbconvert >=4.0
numpydoc >=0.6.0
paramiko >=2.4.0
parso 0.5.2.*
pexpect >=4.4.0
pickleshare >=0.4
psutil >=5.3
pygments >=2.0
pylint >=0.25
pyqt >=5.6,<5.13
python >=3.7,<3.8.0a0
python-language-server >=0.31.9,<0.32.0
pyzmq >=17
qdarkstyle >=2.8
qtawesome >=0.5.7
qtconsole >=4.6.0
qtpy >=1.5.0
rtree >=0.8.3
sphinx >=0.6.6
spyder-kernels >=1.9.0,<1.10.0
watchdog
```

Note: the installation doesn't work even in a new environment, same error.

**Comment by ccordoba12** [comment]
Please remove this directory

    C:\Users\user\AppData\Roaming\Python

to fix the problem.

And please, for next time, **do not** use pip to install packages that can be installed by conda. It's clear that you did that because the directory I referenced above is created by pip, not by conda.
