### ISSUE TITLE
strict pinning of Jedi and Parso still needed?

### ISSUE THREAD

**Issue by bnavigator** [spyder-ide/spyder#11975]
Is it still necessary to pin to very specific versions of Jedi and Parso? I see you pinned to 0.15.2 in #11809 but rolling distributions might want to have newer versions. OpenSUSE Tumbleweed is already on 0.16.0 (and will actually even include some commits newer than the release [soon](https://build.opensuse.org/request/show/786032))

I did not encounter an immediate problem on my tests with Jedi 0.16.0 and Spyder 4.1.1

Maybe @davidhalter can chime in about possilby breaking API changes between 0.15 and 0.16 and how to catch API changes in unit tests for future Spyder development?

**Comment by ccordoba12** [comment]
> Is it still necessary to pin to very specific versions of Jedi and Parso?

I'm sorry but we don't have plans to change this until 4.2.0, to be released in June or July.

> I did not encounter an immediate problem on my tests with Jedi 0.16.0 and Spyder 4.1.1

That doesn't mean that our entire test suite, along with the python-language-server one (which we co-maintain) is passing. It's hard enough to try stabilize 4.1.0 to move to a new Jedi version on top of that.

So if you want to see this happening, please open PRs here and in the python-language-server repo, update the requirement accordingly and make them pass.

> Maybe @davidhalter can chime in about possilby breaking API changes between 0.15 and 0.16 and how to catch API changes in unit tests for future Spyder development?

We've had a couple of discussions with him about this in the PyLS repo and he knows my position about it.

**Comment by bnavigator** [comment]
Are you talking about [palantir/python-language-server](https://github.com/palantir/python-language-server) or [spyder-pyls](https://github.com/spyder-ide/spyder-pyls)? Or is the latter just a development repo?)

Because, if you strictly need PyLS from your own fork it would be great to let distro package maintainers know by documenting it! Right now the OpenSUSE package uses the plain upstream version.

And the unittest suite for the [spyder3 package](https://build.opensuse.org/package/show/devel:languages:python:numeric/spyder3) there passes, except for the excluded tests. Note that the package will be renamed to [spyder](https://build.opensuse.org/package/show/devel:languages:python:numeric/spyder3) soon. (Ironically that version does not build yet because it cannot resolve the dependency to PyLS>=0.31.9 yet)

**Comment by goanpeca** [comment]
@bnavigator you can ignore  `spyder-pyls` that is a dev repo, so @ccordoba12 meant  palantir/python-language-server

**Comment by davidhalter** [comment]
> Maybe @davidhalter can chime in about possilby breaking API changes between 0.15 and 0.16 and how to catch API changes in unit tests for future Spyder development?

There are deprecations between these versions. Minor ones, but I understand that people don't automatically upgrade. IMO pinning is a good way, people should just try to upgrade sooner :).

Jedi will be 1.0 soon. At that point removals of features will only happen on major releases. Then it might make sense to "auto-upgrade" Jedi for minor versions, for now it doesn't. Auto-upgrading micro versions always made sense.

**Comment by ccordoba12** [comment]
> IMO pinning is a good way, people should just try to upgrade sooner :)

Glad you agree on us pinning Jedi. I understand we should try to upgrade sooner, but with a rate of 200 to 300 bugs per month, maintaining Spyder and trying to keep it stable is a very hard job. So we prefer to stick to a particular Jedi version instead of risking to receive a huge amount of bugs in case an update breaks us. 

> Jedi will be 1.0 soon. At that point removals of features will only happen on major releases. Then it might make sense to "auto-upgrade" Jedi for minor versions, for now it doesn't. Auto-upgrading micro versions always made sense.

Ok, thanks for the heads up! Then we'll wait until 1.0 is released and add a `>=1.0,<2.0` constraint.

**Comment by bnavigator** [comment]
I understand your reasoning. It works for the conda world. But Linux distributions work differently.

As my efforts trying to get Spyder and PyLS to a current version of Jedi and Parso (#11984) did not get any support, [my next approach is to provide packages for the pinned versions](https://build.opensuse.org/project/show/home:bnavigator:branches:devel:languages:python). We cannot use just the old packages from a while ago, because they were built for older dependencies including older Python versions. OpenSUSE Tumbleweed has Python 3.8 now. Parso builds fine and passes unit tests. Jedi does not.

```
[   33s] =================================== FAILURES ===================================
[   33s] ________________________ [doctest] jedi.api.Interpreter ________________________
[   33s] 426 
[   33s] 427     In addition to completion of simple attribute access, Jedi
[   33s] 428     supports code completion based on static code analysis.
[   33s] 429     Jedi can complete attributes of object which is not initialized
[   33s] 430     yet.
[   33s] 431 
[   33s] 432     >>> from os.path import join
[   33s] 433     >>> namespace = locals()
[   33s] 434     >>> script = Interpreter('join("").up', [namespace])
[   33s] 435     >>> print(script.completions()[0].name)
[   33s] UNEXPECTED EXCEPTION: IndexError('list index out of range')
[   33s] Traceback (most recent call last):
[   33s] 
[   33s]   File "/usr/lib64/python3.8/doctest.py", line 1329, in __run
[   33s]     exec(compile(example.source, filename, "single",
[   33s] 
[   33s]   File "<doctest jedi.api.Interpreter[3]>", line 1, in <module>
[   33s] 
[   33s] IndexError: list index out of range

[...]

[   33s] test/test_inference/test_gradual/test_typeshed.py:144: AssertionError
[   33s] === 46 failed, 810 passed, 32 skipped, 1867 deselected, 1 xfailed in 26.18s ====
```

The situation gets more complicated: The current package of python-jedi-0.16.0 does not even run the unittest, because -- according to the comment in the specfile --  the bundled typeshed not used in the distro causes problems. It is unclear to me, whether also disabling unit tests for the 0.15.2 package produces a usable package for Sypder/PyLS or if that is no improvement to just unpinning the versions in the Spyder specfile.

Probably better to discuss the Jedi problems in the Jedi repo than here. Just wanted to give you a bigger picture.

Would you consider maintaining an "LTS" branch of Jedi 0.15 and co.,  where you backport fixes for e.g. Python 3.8 support without changing the API?

**Comment by davidhalter** [comment]
> Probably better to discuss the Jedi problems in the Jedi repo than here. Just wanted to give you a bigger picture.
> Would you consider maintaining an "LTS" branch of Jedi 0.15 and co., where you backport fixes for e.g. Python 3.8 support without changing the API?

There's nothing to discuss there - from Jedi's side everything is fine, I'm not patching old versions.
If somebody is paying for that I might reconsider. Jedi versions are mostly backwards compatible and 0.16 fixes a lot of bugs that would be annoying to backport.

IMO you can probably just use Jedi 0.16 with Spyder at your own risk for the time being. Everything probably works. To be officially supported in Spyder you probably have to do the heavy lifting yourself, create a PR here that makes it possible for Spyder to use Jedi 0.16 properly.

**Comment by bnavigator** [comment]
> IMO you can probably just use Jedi 0.16 with Spyder at your own risk for the time being. Everything probably works.

Well, then we are back at the beginning of this thread. That's what our package is doing right now. My question was whether this is a viable option or whether the pinning is strictly necessary.

**Comment by davidhalter** [comment]
As I said, you can probably do it at your own risk, at that point you should probably just help out the spyder maintainers with bug reports, otherwise it's not really fair, because your users will post issues here.

In case you really want to help, probably just try to upgrade Jedi and get the CI passing for Spyder, at that point I think @ccordoba12 will probably also be happy to merge.

**Comment by bnavigator** [comment]
Yeah we still have most of the test suite active during the package build. Any fixes relevant for upstream will be reported.

**Comment by ccordoba12** [comment]
Closing this because we're going to always require a strict pinning on those packages to avoid surprises with new Jedi versions.
