### ISSUE TITLE
"Directly enter debugging when errors appear" is not working

### ISSUE THREAD

**Issue by keepiru** [spyder-ide/spyder#11986]
### Issue Report Checklist
Yep, did it

## Problem Description
The debugger does not start when an unhandled exception is raised.

### What steps reproduce the problem?

1. tools, prefs, Run, General Settings, check "Directly enter debugging when errors appear"
2. Create new file, contents "raise RuntimeError"
3. F5

### What is the expected output? What do you see instead?

Expected (version 3.3.6):

```
In [1]: runfile('/home/user/.config/spyder-py3/temp.py', wdir='/home/user/.config/spyder-py3', post_mortem=True)
Traceback (most recent call last):

  File "<ipython-input-1-527ce6822f9c>", line 1, in <module>
    runfile('/home/user/.config/spyder-py3/temp.py', wdir='/home/user/.config/spyder-py3', post_mortem=True)

  File "/home/user/miniconda3/envs/test3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/user/miniconda3/envs/test3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/user/.config/spyder-py3/temp.py", line 1, in <module>
    raise RuntimeError

RuntimeError

****************************************
Entering post mortem debugging...
****************************************
> /home/user/.config/spyder-py3/temp.py(1)<module>()
----> 1 raise RuntimeError


ipdb> 
```

Actual (version 4.1.1)

```
In [1]: runfile('/home/user/untitled1.py', wdir='/home/user', post_mortem=True)
Traceback (most recent call last):

  File "/home/user/untitled1.py", line 1, in <module>
    raise RuntimeError

RuntimeError


In [2]: 
```

## Versions

3.3.6 is good, 4.1.1 is broken.

**Comment by keepiru** [comment]
Testing with 4.0.0b4, I suspect the problem is actually in spyder-kernels.

good: 1.4.0-py37_0
bad: 1.5.0-py37_0

**Comment by keepiru** [comment]
02cd43403ee68c566088350cc0918b6b02afd067 is the first bad commit

"Add context manager for namespace"

**Comment by bcolsen** [comment]
I can confirm this bug with "run config per file" as well

**Comment by ccordoba12** [comment]
@impact27, could take a look at this one?

**Comment by impact27** [comment]
The problem on the spyder-kernels side is fixed. The "run config per file" isn't fixed as this is a different problem and I am not familiar with this code.

**Comment by ccordoba12** [comment]
> The "run config per file" isn't fixed

What do you mean by this? What needs to be fixed there?

**Comment by impact27** [comment]
Sorry it actually works, but only if the file is saved. If the file is not saved this won't work but I don't think this is really a problem.

**Comment by ccordoba12** [comment]
Agreed.

**Comment by mlemarenko** [comment]
For me the feature is broken on 4.1.2 and is working incorrectly on 5.0.0 (which I don't use due to other bugs). 
In 5.0.0 is does enter in ipdb but loses the context, jumps outside of the function where the error is located. What is expected, is that it stops execution on the line where the exception is thrown and gives user the context.
If is really a must have feature if, for example, you want have Matlab users be attracted by your product.

**Comment by ccordoba12** [comment]
@mlemarenko, that's called post mortem debugging and you can enable it by going to the menu

    Run > Configuration per file

and activating the option called `Directly enter debugging when errors appear`.

**Comment by mlemarenko** [comment]
@ccordoba12 : this is exactly my point. I did search quite a lot how to do it. None of the methods, including this one, work. Here is [Stackoverflow link ](https://stackoverflow.com/questions/56027006/how-can-we-get-spyder-to-pause-execution-after-an-error-has-occurred) where people report having the same problem. 
For instance, when I do what you suggest, Spyder 4.1.2 just ignores this condition. Spyder 5.0.0 shows ipdb line, but the content of variable explorer does not correspond to what is within the function that has thrown the exception. It shows the outermost layer only. Ok for debugging a flat script but not if one has functions.

**Comment by ccordoba12** [comment]
> this is exactly my point. I did search quite a lot how to do it.

Although I understand your frustration, you're most probably searching for the wrong info. There's no Spyder debugger, we only provide an interface for the Python debugger (aka Pdb). So if you need some advanced debugging features, you need to search for Pdb stuff.

> It shows the outermost layer only

Then you need to navigate up/down in the stack to get to point that you need using the `up` and `down` commands. You can find the essential Pdb commands here:

https://realpython.com/python-debugging-pdb/#essential-pdb-commands
