### ISSUE TITLE
error massage when start spyder 4 

### ISSUE THREAD

**Issue by ljafari** [spyder-ide/spyder#12001]
Hi everybody
Due to not ending problems 
1- I uninstalled anaconda and removed every folder and files depended on it and then installed anaconda 2020. 
1- At first I installed anaconda 64 bit but it couldnt open and I after a lot of trying I had to uninstalled it and then installed 32 bit version. 
2- Then it had an issue with jedi and parso. So I did instructions in issue #4587 and did
pip uninstall pyqtwebengine
pip install pyqtwebengine
3-Then did "pip install jedi==0.15.2 and pip install parso==0.5.2

Now I can open spyder but when it opens it shows this messages:

![1](https://user-images.githubusercontent.com/62611676/77677324-23de0680-6fad-11ea-910d-6a158537e714.png)

what should I do? I have a lot of problems with spyder!

**Comment by ljafari** [comment]
Also I closed my anti virus but nothing changed!

**Comment by ljafari** [comment]
My problem solved when I removed every file related to python. I also uninstalled PyCharm. 
Then I searched for every file related to Conda and python and Spyder in my c:/Users and reminded files after uninstall of anaconda and PyCharm.
 Then I reset my laptop and after that I installed Anaconda 2020 64 bit. 
Finally I installed packages with "conda install" instead of "pip install". 
After that anaconda and spyder worked fine.

**Comment by ccordoba12** [comment]
@ljafari, I'm really you were able to solve your problem and sorry for not being able to give you feedback about it. Sometimes there are too many issues per day and I'm almost the only one that answers them all.

**Comment by ljafari** [comment]
Hi Dear Carlos Cardoba
I'm really appreciative for your response. I faced a lot of errors and
uninstalled Anaconda and delete every file in C drive that I guess related
to python and then installed Anaconda again and after that it worked fine.
Now I have new problem that wasted my time for completely 2 days!!  I
discussed it in "https://github.com/tensorflow/tensorflow/issues/37978"
I tried a lot but could'nt solve it until now. Maybe you can help me?
thanks a lot

**Comment by ccordoba12** [comment]
It seems your Nvidia drivers are too old for the Cuda version you have. That's all the advice I can give, because I don't use Tensorflow, sorry.
