### ISSUE TITLE
Spyder runs imported modules, even if they have already been run

### ISSUE THREAD

**Issue by ahmida-bendjoudi** [spyder-ide/spyder#12009]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Some modules (from the same directory of the project in execution) have already been run by Spyder, when these modules are imported, Spyder runs them once more,
when these modules carry long calculation, it would be then a bad idea to run them once more (because they take long time), since they are opened on Spyder, and run, and their results are registred as variables,

Dear Spyder programmers, you can insert a simple code to:
1/check whether the imported module have been run or not since Spyder is opened
2/ check whether the imported module (i.e. the codes) have been changed or not since last run,
3/ if they have not been changed, then Spyder imports them without running,

this will make Spyder faster and better (this will solve the issue #11943 I reported before )

**Comment by UniqASL** [comment]
I guess [this](https://github.com/spyder-ide/spyder/issues/11558) should solve your problem.

**Comment by ahmida-bendjoudi** [comment]
Thanks UniqASL, the problem is solved with your  [#11558](this)

**Comment by ccordoba12** [comment]
Thanks for chiming in about this @UniqASL!
