### ISSUE TITLE
Spyder logs error at the start

### ISSUE THREAD

**Issue by PeterMoresco** [spyder-ide/spyder#12010]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/plugins/editor.py", line 1759, in new
    if not osp.isfile(fname):
  File "/usr/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character '\xed' in position 5: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.14.1, PyQt5 5.14.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.6.1 (OK)
pandas >=0.13.1  :  1.0.3 (OK)
numpy >=1.7      :  1.18.2 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.16.0 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.6.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  7.13.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
