### ISSUE TITLE
Unable to save file to mapped network drive on Windows 7

### ISSUE THREAD

**Issue by pocar** [spyder-ide/spyder#12024]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I try to save a file to a network drive, I get the following error dialog:
``"Unable to save file 'my_file.py'
Error message:
[Errno 2] No such file or directory: '\\\\sshfs\\deu219564@10.50.229.93\\\\testscripts\\my_file.py'
``

This is new in Spyder 4.1.1, it worked in 4.1.0.

### What steps reproduce the problem?

1. Open a file (or create a new one) from a mapped network drive (e.g., X:)
2. Make some change to it
3. Try to save it

### What is the expected output? What do you see instead?

No error dialog poping out and the change in file when reopening it.

### Paste Traceback/Error Below (if applicable)

There  is no output in internal console.

However, I did some debugging on my own and the problem is in the file
[..]\site-packages\spyder\utils\encoding.py" line 245:
``
            absolute_filename = to_text_string(
                pathlib.Path(filename).resolve())
``
When I replace line with ``absolute_filename = osp.realpath(filename)`` it saves file correctly (without error).

## Versions

* Spyder version: Spyder 4.1.1 
* Python version: Python 3.6.3 64-bit
* Qt version: Qt 5.12.6
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Windows 7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@dalthviz, please take care of this one to see if we can include a fix for it in 4.1.2.

**Comment by dalthviz** [comment]
@ccordoba12 @pocar I was unable to reproduce this using `4.1.1` or running from develop `4.2.0dev0`:

![ns](https://user-images.githubusercontent.com/16781833/77922935-5581f680-7267-11ea-9be0-012127b86ec4.gif)

However I did PR #12050 following the solution found by @pocar

@pocar could you test if the fix in PR #12050 works for you? Thanks!
