### ISSUE TITLE
Spider fails and does not autosave

### ISSUE THREAD

**Issue by dickwalvis** [spyder-ide/spyder#12021]
### What steps will reproduce the problem?

Condition: 
MAC OS 10.15.4 (19E266)
Spyder 4.1.1 
Python 3.7.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Darwin 19.4.0 
Opened through Anaconda 1.9.12

The Autosave directory shows saved versions of 2 files I am editing.
Then I delete 5 lines in one of the .py files, spider closes and the autosave directory is empty. 

All editing is lost

Thank you

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.4.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
> The Autosave directory shows saved versions of 2 files I am editing.
Then I delete 5 lines in one of the .py files, spider closes and the autosave directory is empty.

Our autosave mechanism saves a copy of your files every certain seconds. So if you want a smaller interval, please to Preferences and select an smaller interval:

![Selección_001](https://user-images.githubusercontent.com/365293/77808654-3b26fd80-705a-11ea-9921-6b5adde1107a.png)

**Comment by dickwalvis** [comment]
Good morning

I don't think the saving interval is the issue but creating this response made me look at this more closely.

My first observation is that the autosave process does not create an autosaved copy of a new editing window unless one has saved the window to a file. That is not intuitive.

So that may have been why there was no file in the autosave directory when Spyder crashed. 

However, I am pretty certain that there was at least one file, from another editing window/file, in the autosave directory when Spyder crashed. When I restarted Spyder there were no files in the autosave directory at all.

I'll keep an eye on it and let you know.

I do like the Spyder interface. I am worried about crashing though.

Thank you,

Dick Walvis

**Comment by ccordoba12** [comment]
> My first observation is that the autosave process does not create an autosaved copy of a new editing window unless one has saved the window to a file. That is not intuitive.

Yeah, it doesn't work for unsaved files, sorry.
