### ISSUE TITLE
tkinker strange windows

### ISSUE THREAD

**Issue by Czimchik** [spyder-ide/spyder#12030]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

from tkinter import *

root = Tk()

from tkinter import filedialog

root = Tk()

import os

desktop = os.path.join(os.path.join(os.environ['USERPROFILE']), 'Desktop')

root.filename = filedialog.askopenfilename(filetypes= (('pliki .xlsx', '*.xlsx'), ('pliki .xls', '*.xls')), initialdir = desktop, title='Wybierz plik excel')

#here i got 2 windows named 'tk' that didn't disappear by themselves, one of them was not responding in task manager

root.filename

Out[27]: 'C:/Users/Ukasz/Desktop/sample.xlsx'

#i tried to close not responding one

Restarting kernel...

**Comment by ccordoba12** [comment]
You need to activate the Tkinter graphics backend if you want to work with Tkinter.

For that you need to go to

    Tools > Preferences > IPython console > Graphics > Backend

and select `Tkinter` there.
