### ISSUE TITLE
Spyder can not locate **jedi** and **parso** although they are properly installed

### ISSUE THREAD

**Issue by neoglez** [spyder-ide/spyder#12040]
## Problem Description
Spyder can not locate **jedi** and **parso** although they are properly installed.

### What steps reproduce the problem?

1. Install the latest anaconda2 for linux (4.8.3)
2. Create a python 3.7 environment.
3. Install spyder with conda install spyder
4. execute spyder

### What is the expected output?
Expected: Normal IDE GUI

What do you see instead?
An Error window "You have missing dependencies"
Mandatory: jedi and parso (see attached)

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "/home/turandot/.conda/envs/py37/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'python' is not defined
>>> 

```

## Versions

* Spyder version: 4.1.1
* Python version: Linux ubuntu 16.04 python 2.7.16. Problem found in environment with python 3.7.6
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Kubuntu 16.04.6 LTS

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.16.0 (NOK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.6.2 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```
![spyder-missing-dependencies](https://user-images.githubusercontent.com/3646037/77898541-971c9c80-727b-11ea-859f-feed6da2e46a.png)

**Comment by ccordoba12** [comment]
Please take a look at the versions in the screenshot you posted above. It's not that you don't have those packages, it's that you have the wrong versions if them.

So please correct that by installing the right versions.

**Comment by neoglez** [comment]
Thanks for the tip. The task was not necessarily trivial though. I had to downgrade first parso and then jedi (in that order). Then I had to create a pinned file (as described in the documentation) and freeze the packages:
```
parso ==0.5.2
jedi ==0.15.2  
```
Finally, I had to install spyder. Let this serve others with the same problem.

**Comment by ccordoba12** [comment]
Yeah, that's not simple matter if you constantly run `conda update --all`. But if you avoid that (which I think you should) and only update the packages you need, then things will be much simpler.

**Comment by mahimakaushik-oss** [comment]
im facing problem in spyder and anaconda both. nothing is installing and any component is not worling in my anaconda . please help
![image](https://user-images.githubusercontent.com/59880406/95355917-b871db80-08e3-11eb-9e71-aef6ef5618af.png)

**Comment by ccordoba12** [comment]
Hey @mahimakaushik-oss, you need to remove the following directory to fix your problem:

    C:\Users\Mahima Kaushik\AppData\Roaming\Python

**Comment by mahimakaushik-oss** [comment]
thanks a lot. your suggestion solved my problem. a big thanks for you :). i tried it for 5 hrs but failed but your suggestion solved my problem. thank you again

**Comment by mahimakaushik-oss** [comment]
@ccordoba12  but still my anaconda is not installing others files like dash , plotly . its showing something like " multiple error encountered". what to do for that?

**Comment by ccordoba12** [comment]
I'd recommend you to remove and reinstall Anaconda. Please see the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) for that.

**Comment by mahimakaushik-oss** [comment]
@ccordoba12 i saw, thanks

**Comment by hikmatilloahatov** [comment]
I have it like this situation

**Comment by ccordoba12** [comment]
> @ccordoba12 Do you have an alternative directory to remove on Linux?

~/.local/lib/pythonX.X
