### ISSUE TITLE
Spyder reduces window when exploring variable

### ISSUE THREAD

**Issue by Colin-Gnt** [spyder-ide/spyder#12047]
## Problem Description

When I click on a variable in the variable explorer in Spyder, it creates the tab with the variable but reduces the window. So I need to re-expand it every time I want to explore a new variable.

### What steps reproduce the problem?

On my cumputer's Spyder
1. crate any variable (numpy.array for example)
2. click on the variable in the varable explorer pan
3. observe the reduced window with the new variable tab

### What is the expected output? What do you see instead?
The main window without a change in size with the new tab.

## Versions

* Spyder version: Spyder 4.1.1
* Python version: Python 3.7.6 (default, Jan  8 2020, 13:42:34) 
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Macbook Pro retina (early 2015) on Mojave : 10.14.6

### Dependencies

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
> When I click on a variable in the variable explorer in Spyder, it creates the tab with the variable but reduces the window. So I need to re-expand it every time I want to explore a new variable.

I'm sorry but this is an issue with the way macOS handles different windows of the same program. So I doubt we can do something about it.

@goanpeca, what do you think?

**Comment by Colin-Gnt** [comment]
I had some other UI issues (#11846) with the new version of spyder (4.1). But I don't want to downgrade it yet because it causes issues with the kernel when running a code.
But I can try to downgrade it later see if the bug still appear because I don't remember having this issue before.

**Comment by goanpeca** [comment]
I can take a look

**Comment by ccordoba12** [comment]
Closing for now because we don't have time to take a look at this, sorry.
