### ISSUE TITLE
spyder‑kernels module issue

### ISSUE THREAD

**Issue by rnandip** [spyder-ide/spyder#12059]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I started spyder IDE through anaconda command prompt, it threw below error
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.0 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.

### What steps reproduce the problem?

1.  Installed new anaconda version (anaconda 2020.02)
2. Created new environment and installed latest python version (3.8.2)
3. and also Spyder latest version 4.1.1 and tried to open spyder.  Ipython kernel section threw error

### What is the expected output? What do you see instead?

Not able to run anything in spyder IDE

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.0 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.
```

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
> and also Spyder latest version 4.1.1 and tried to open spyder. Ipython kernel section threw error

Do you mean that you installed Spyder in your Python 3.8 env too?

**Comment by rnandip** [comment]
I downgraded python version to 3.7 and installed spyder latest version. It didn't work and then used
conda update --all to update the whole environment.

**Comment by ccordoba12** [comment]
Please then open the Anaconda prompt and run there

    spyder --reset

That should fix the problem.

**Comment by rnandip** [comment]
Thanks. It worked

**Comment by wyjzll** [comment]
Yes, it works, thanks

**Comment by richlysakowski** [comment]
Thank you, it worked.  I don't really understand what the --reset command does.  

Can someone please explain?    

Here's what I did and what I got...

```
(conda_pip_test) C:\Users\RichLysakowski>spyder --reset
*** Reset Spyder settings to defaults ***
removing: C:\Users\RichLysakowski\.spyder-py3\help
removing: C:\Users\RichLysakowski\.spyder-py3\onlinehelp
removing: C:\Users\RichLysakowski\.spyder-py3\temp.py
removing: C:\Users\RichLysakowski\.spyder-py3\template.py
removing: C:\Users\RichLysakowski\.spyder-py3\history.py
removing: C:\Users\RichLysakowski\.spyder-py3\history_internal.py
removing: C:\Users\RichLysakowski\.spyder-py3\workingdir
removing: C:\Users\RichLysakowski\.spyder-py3\langconfig
removing: C:\Users\RichLysakowski\.spyder-py3\spyder.lock
removing: C:\Users\RichLysakowski\.spyder-py3\config\spyder.ini
removing: C:\Users\RichLysakowski\.spyder-py3\config\transient.ini
removing: C:\Users\RichLysakowski\.spyder-py3\plugins

```

**Comment by ccordoba12** [comment]
`spyder --reset` removes all your configuration files, so that Spyder can start with factory defaults again.

**Comment by Narendra-027** [comment]
> Please then open the Anaconda prompt and run there
> 
> ```
> spyder --reset
> ```
> 
> That should fix the problem.

In my case it is not working

**Comment by tuba89** [comment]
> > Please then open the Anaconda prompt and run there
> > ```
> > spyder --reset
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That should fix the problem.
> 
> In my case it is not working

I my case too, it's not working
