### ISSUE TITLE
Automating re-runs

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12058]
Much of my workflow is: run `__main__`, edit `.py` files, restart kernel, repeat. The "restart kernel" + "run" or "debug + continue until breakpoint" steps typically elapse 10 seconds, which really adds up over time; it'd be nicer if I could issue a single command to do all these steps and force window focus back on Spyder (like it already does when continuing until breakpoint) when finished, while I tab to other windows.

Is there something like this already in Spyder (if not, I suggest it as a feature), or does anyone happen to know how to macro such a thing? Thanks

<hr>

_Note:_ while  a kernel restart isn't required to refresh .py files, I found the autoreload feature to be not reliable at times, so a kernel restart is the only way to be sure.

**Comment by bcolsen** [comment]
@OverLordGoldDragon Have you tried your scripts without restarting the kernel in Spyder 4? I ask because by default Spyder 4 runs scripts in a new namespace which might help with troubles you may have had in previous versions.

**Comment by OverLordGoldDragon** [comment]
@bcolsen Yes, issues encountered up to Spyder 4.0.1. To clarify, I'm not entirely certain the issue has ever occurred outside of and unrelated to TensorFlow sessions, which are difficult to clean up without a kernel restart (and a new namespace surely doesn't do it). But this doesn't help, since I work with TensorFlow extensively.

**Comment by ccordoba12** [comment]
We don't have time to implement this, sorry. So unless you send us a pull request for it, I'm afraid it's not going to happen.

Please report back if you'd like to do that and need some guidance for it. Else, I'm afraid I'll close this issue.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Understandable, thanks.

**Comment by ccordoba12** [comment]
Thanks for understanding!
