### ISSUE TITLE
TypeError when trying to view output of Code Analysis pane

### ISSUE THREAD

**Issue by ssingh09299** [spyder-ide/spyder#12052]
### What steps will reproduce the problem?

Run analyze in code analysis
Opening the output gave a message - "Spyder has encountered an internal problem"

### Traceback
```python-traceback
  File "/home/Saurabh/anaconda3/lib/python3.7/site-packages/spyder/plugins/pylint/widgets/pylintgui.py", line 308, in show_log
    readonly=True, size=(700, 500)).exec_()
TypeError: __init__() got an unexpected keyword argument 'size'
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.19.0-1-amd64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.6.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.8.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.1.2 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.12 (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  0.24.2 (OK)
scipy >=0.17.0                 :  1.3.0 (OK)
sympy >=0.7.3                  :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
> Run analyze in code analysis

Please post the code you're trying to analyze so we can reproduce this in our end.

**Comment by ssingh09299** [comment]
Please find the attached code with the screenshot of the error.

Saurabh
________________________________

**Comment by ssingh09299** [comment]
`"""Code for comparison of binomil and normal distribution."""
import numpy as np
from matplotlib import pyplot as plt
from N_choose_k import N_choose_k


total_moves = 100

step = 2
right_limit = total_moves+step
left_limit = -1*(right_limit-step)

resultant_right_moves = np.arange(left_limit, right_limit, step)
num_points = np.size(resultant_right_moves)

probability_right_move = 0.4
probabiilty_left_move = 1-probability_right_move

mean = total_moves*probability_right_move
std_dev = np.sqrt(total_moves*probability_right_move*probabiilty_left_move)

binomial_dist = np.zeros((num_points, 1))
normal_dist = np.zeros((num_points, 1))
counter = 0

for resultant_moves in resultant_right_moves:
    right_moves = total_moves/2+resultant_moves/2
    left_moves = total_moves/2-resultant_moves/2
    binomial_dist[counter] = N_choose_k(total_moves, int(right_moves)) * \
        (probability_right_move**right_moves) * \
        (probabiilty_left_move**left_moves)
    normal_dist[counter] = (1/(np.sqrt(2*np.pi)*std_dev)) * \
        np.exp((-1/(2*std_dev**2)) * (right_moves-mean) ** 2)
    counter += 1

plt.plot(resultant_right_moves, binomial_dist)
plt.plot(resultant_right_moves, normal_dist)
plt.xlabel('Resultant right moves')
plt.ylabel('Probability')
plt.legend(['Binomial', 'Normal'])
`

**Comment by ccordoba12** [comment]
Thanks! I could reproduce it and it'll be fixed in our next version.
