### ISSUE TITLE
Can we free used memory in Spyder?

### ISSUE THREAD

**Issue by pranavsathe** [spyder-ide/spyder#12069]
I have developed a web scraper for an asynchronous javascript website. I am scraping data on need basis, to do this I have also connected my script to database. 

- When I schedule my script to run everyday, it gives memory issues. 
- Since I am dealing with Asynchronous web pages, I have to use this library, from requests_html import AsyncHTMLSession.  
- This library only work well only with Spyder. Is there a way to free used memory by web scraper after each run? I believe the imported libraries take a lot of memory space. 
The gc.mem_free() function doesn't work well with Python 3.3. Is there a way to solve this?

**Comment by ccordoba12** [comment]
There were several people that told you already in StackOverflow that this is not a problem with Spyder but with your code. So you're not going to get a different answer here.

You need to take a look at your code and see how you can make it more memory efficient. That's the only way you're going to reduce memory consumption for it.
