### ISSUE TITLE
tool preference can't open

### ISSUE THREAD

**Issue by xioajiumi** [spyder-ide/spyder#12060]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
When I was design my own Preference in Tools, but suddenly it has response no more. How? .........

**Comment by xioajiumi** [comment]
My problem is well-solved.  Just input 'spyder --reset'' in cmd. Thanks for the mighty Troubleshooting.

**Comment by ccordoba12** [comment]
Glad to hear @xioajiumi!!
