### ISSUE TITLE
Just updated to spyder 4.0.1 and experience this problem.Whenever spyder opens the issue reporter pops open saying that spyder has encountered an internal problem, clicked on details it showed

### ISSUE THREAD

**Issue by Deepan1303** [spyder-ide/spyder#12061]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Just updated to spyder 4.0.1 and experience this problem.
Whenever spyder opens the issue reporter pops open saying that spyder has encountered an internal problem, clicked on details it showed

File "/usr/local/lib/python3.5/dist-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'

**Comment by ccordoba12** [comment]
Please open xterm or your terminal of choice and run there

    spyder --reset

That should fix this problem.
