### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by futureteacher** [spyder-ide/spyder#12075]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I restarted the kernel and I keep on getting connecting to kernel

**Comment by ccordoba12** [comment]
This is proably fixed in our latest Spyder 3 version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.6

Also, please report back if that fixes the problem or not.

**Comment by futureteacher** [comment]
Thanks. I uninstalled and installed spyder and it works now

**Comment by ccordoba12** [comment]
Great to know!
