### ISSUE TITLE
No print output in IP console when running print code from editory reffering to issue #12090

### ISSUE THREAD

**Issue by uncrushedIce** [spyder-ide/spyder#12092]
Issue Report Checklist
[x ] Searched the issues page for similar reports
[x ] Read the relevant sections of the Spyder Troubleshooting Guide and followed its advice
[x ] Reproduced the issue after updating with conda update spyder (or pip, if not using Anaconda)
 Could not reproduce inside jupyter qtconsole (if console-related)
[x ] Tried basic troubleshooting (if a bug/error)
[x ] Restarted Spyder
[x ] Reset preferences with spyder --reset
x[ ] Reinstalled the latest version of Anaconda
 Tried the other applicable steps from the Troubleshooting Guide
[x ] Completed the Problem Description, Steps to Reproduce and Version sections below
Problem Description
When running a file or cell with print functions in them, they produce no output (for example hello world gives no output.

What steps reproduce the problem?

Open or write simple print("Hello World") function
Run cell or file
No print output in the IP console

What is the expected output? What do you see instead?

Expected:
In [1]: runfile('C:/.../HelloWorld.py', wdir='C:/...)
Hello world

Instead:
In [1]: runfile('C:/.../HelloWorld.py', wdir='C:/...)

Versions
Spyder version: 4.1.1
Python version: 3.7.7
Qt version: 5.9.7
PyQt version: 5.9.2
Operating System name/version: Windows 10.0 Build 18362
Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    jupyter qtconsole

Then run

    print('Hello world')

and see if it works or not.

**Comment by uncrushedIce** [comment]
#%%
def hello():
    print("Hello, world!")


Thats the cell

**Comment by uncrushedIce** [comment]
In the qtconsole i get a output

**Comment by uncrushedIce** [comment]
I also get an output when i tipe the print function directly in the ip console

**Comment by uncrushedIce** [comment]
When i write the function in the editor and run it i get no output

**Comment by ccordoba12** [comment]
This could be an issue with your firewall or antivirus. Please deactivate them and try again.

**Comment by uncrushedIce** [comment]
Thank you for the suggestion

With everything (Firewall and Antivirus) deactivated still same results :/

**Comment by ccordoba12** [comment]
Sorry, I have no more ideas. This has been reported by only one more person before, so we don't know what's causing it.

**Comment by ccordoba12** [comment]
In the meantime, you can to the menu:

    Tools > Preferences > Editor > Run code

and activate the option called

    Copy full cell contents to the console when running code cells

and run the file with Shift+Enter or Ctrl+Enter. That should work.

**Comment by uncrushedIce** [comment]
Thanks anyways for the help!

Copying full cell contents still gives no outputs :/

**Comment by ccordoba12** [comment]
Could you a screenshot of what you're seeing? Copying cell contents is equivalent to writing your code in the console and pressing Enter to evaluate it.

**Comment by uncrushedIce** [comment]
![image](https://user-images.githubusercontent.com/48356933/78165984-66d82800-744c-11ea-8ea4-0e81ffc16bbf.png)

**Comment by ccordoba12** [comment]
You're still using `runcell` in your first command, meaning that it seems you haven't activated the option I told you about.

**Comment by uncrushedIce** [comment]
oh sorry, i had it and deactivated it again. Mom

**Comment by uncrushedIce** [comment]
![image](https://user-images.githubusercontent.com/48356933/78166860-c3881280-744d-11ea-9061-9ce8da29295d.png)

**Comment by bcolsen** [comment]
@uncrushedIce 

The error is that your code doesn't do anything but define functions.

Python doesn't run a function when it is defined only when it called.

At the bottom of your file write:
```python
%##
hello()
````
And run the cell to see `hello world`
