### ISSUE TITLE
Update Working with packages and environments in Spyder?

### ISSUE THREAD

**Issue by maximlt** [spyder-ide/spyder#12107]
Hi and thanks for your great work, it is much appreciated :)

I've been using Spyder for a while and like the approach of having just one Spyder instance installed in its dedicated conda environment (that I simply call spyder), it makes maintaining/updating Spyder easier if it's just there on its own and not put together with 200 other packages. If I wanna connect Spyder to an other environment, I install ``spyder-kernels`` in that environment and change the **Interpreter** in the settings to point to the python executable of that environment. That works fine (most of the time!) and this way I have just one Spyder version installed, not in each environment (which would be a pain to maintain).

I got this trick from your wiki, [here](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder) exactly. The page is a little old though, 09/2018, and maybe it needs to be updated? For instance, it suggests to run ``conda install spyder-kernels=0.*``, which pins ``spyder-kernels`` to older (spyder 3.X?) versions.

I also wonder if my approach is still the right way? If so, I believe it should be better documented and probably added to the official docs, as it's kind of hidden now unfortunately.

In the long run, I hope your team will have enough funding to get closer to the experience provided by vscode, i.e. a super smooth way to activate any environment from the GUI.

**Comment by ccordoba12** [comment]
> I got this trick from your wiki, here exactly. The page is a little old though, 09/2018, and maybe it needs to be updated?

@maximlt, the wiki is public. Could you edit it to reflect the changes in Spyder 4?

> I also wonder if my approach is still the right way?

Yes, it is.

> If so, I believe it should be better documented and probably added to the official docs, as it's kind of hidden now unfortunately.

We were hoping to add graphical support for this in Spyder 4, but unfortunately it didn't make it. We'd really appreciate if you could help us to move that to our [docs](https://github.com/spyder-ide/spyder-docs). Do you have time for that too?

**Comment by maximlt** [comment]
Hi!

Yes sure I could try to improve the doc :)

One comment though, I guess it'd be better in terms of maintenance not to duplicate content between the official docs and the Wiki. If you agree, where would you like to see this content to live? If you believe that it should be in the official docs, it could have a page on its own, right after ``Installation``. If it's on the Wiki, the Wiki index page (https://github.com/spyder-ide/spyder/wiki) should be updated too as now it doesn't point to that page.

**Comment by ccordoba12** [comment]
> Yes sure I could try to improve the doc :)

Thanks a lot!

> If you believe that it should be in the official docs

We're in the process of updating our docs for Spyder 4, so I think we should leave the move for later.

> If it's on the Wiki, the Wiki index page (https://github.com/spyder-ide/spyder/wiki) should be updated too as now it doesn't point to that page.

Agreed. Please update it accordingly.

**Comment by goanpeca** [comment]
@maximlt could you update the wiki :-) ?

Thanks for the help!

**Comment by maximlt** [comment]
@goanpeca that was still in my plan sorry for the delay! Before updating the wiki I wanted to make sure it worked well with a fresh install and had some issues with that, I'll try again soon and hopefully get that done by the end of the week-end.

**Comment by maximlt** [comment]
@goanpeca I've updated the [Wiki](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder) with some more info. I left the references to Spyder 3 if some people use old versions for some reasons, they could be removed though if you feel they're not necessary. I've added a link to that page in the [Home](https://github.com/spyder-ide/spyder/wiki) page.

**Comment by goanpeca** [comment]
Thanks a lot for the help :-)

**Comment by ccordoba12** [comment]
@CAM-Gerlach, could you proofread that page real quick?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Sure, in work.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 @maximlt Done, just added a few commas, tweaked syntax a few places, cleaned up a few stray spaces/line breaks, and made one content-relevant change: added the manual venv activation script since `workon` isn't always available everywhere. Thanks so much for your help!

I support adding this to the docs; I believe we initially wanted to but for whatever reason we didn't. I'd be happy to submit a PR to get that done when the time is right; it also reflects a lot of what we tell people in our Pip vs. Conda video that we're working on right now...maybe as material to accompany that? Or we can do it separately or later.

**Comment by ccordoba12** [comment]
> I'd be happy to submit a PR to get that done when the time is right

Thanks for your help @CAM-Gerlach!

**Comment by ccordoba12** [comment]
Closing this one then. Thanks @maximlt and @CAM-Gerlach for your help!
