### ISSUE TITLE
Namespace is not set correctly while debugging

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#12102]
## Problem Description
Setting a breakpoint inside the function for debugging,
Looking at the value of the function's input parameter in variable explorer, it is not expected

### What steps reproduce the problem?
![debug](https://user-images.githubusercontent.com/1759365/78227221-854b2b80-74ff-11ea-96da-49818c454251.gif)
### What is the expected output? What do you see instead?
Normally, the value of a variable is not printed using "print", but viewed directly through variable explorer.
I think ,when debugging,the value of the variable "a" should be 5,not 10

### code

```python
def test(a):
    print('a:',a)
    print()#Set a breakpoint on this line
a = 10
test(5)
```

## Versions

* Spyder version: 4.1.1
* Python version: 3.7.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win 10

**Comment by ccordoba12** [comment]
Thanks for reporting. It seems the user namespace is shadowing the pdb namespace and that's why `a` is shown as `10` and not as `5`.

@impact27, could you take a look at this one?

**Comment by impact27** [comment]
Fixed in https://github.com/spyder-ide/spyder-kernels/pull/212

**Comment by ccordoba12** [comment]
Thanks for the quick response @impact27! Could you add a test for this? (I don't know if it's necessary to do it here or in spyder-kernels).

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder/pull/12117
