### ISSUE TITLE
import cv2

### ISSUE THREAD

**Issue by alim0401** [spyder-ide/spyder#12103]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1047, in create_client_for_kernel
    password)
  File "/usr/lib/python3/dist-packages/spyder/plugins/ipythonconsole.py", line 1745, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "/home/alimjan/.local/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 55, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.10.0, PyQt5 5.10 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.6.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.16.0 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.16.0 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.6.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.29.16 (OK)
qtconsole >=4.2.0:  4.7.2 (OK)
IPython >=4.0    :  7.13.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest Spyder 3 version. Please update.
