### ISSUE TITLE
Suggestion: separate config module

### ISSUE THREAD

**Issue by SamSchott** [spyder-ide/spyder#12106]
This is not a bug report but merely a suggestion. Spyder's config module is a quite nice way of handling configuration files and their version upgrades. I could imagine it being very useful for a number of projects and, as far as I know, there currently is no equivalent package in Python ecosystem.

Personally, I have used Spyder's config module in a number of projects from small to more elaborate and have found it very helpful. Have you ever considered making it available as a separate package? Or is its development cycle too closely linked to the needs and changes of Spyder?

**Comment by ccordoba12** [comment]
Thanks for the suggestion but we're not planning to do that in the short nor mid terms. That module is heavily customized to our needs, so trying to move it to a separate package could come with some issues we don't want to deal with right now, sorry.

However, you can take a look at this project:

https://github.com/jnsebgosselin/appconfigs

It's developed by one of our core contributors and inspired in our config system.

You could collaborate with him and add to it the improvements we developed for Spyder 4.

**Comment by SamSchott** [comment]
Ok, thanks for the pointer!

**Comment by ccordoba12** [comment]
No problem!

(I forgot to ping @jnsebgosselin about this, just in case).
