### ISSUE TITLE
spyder 4.1.1 hangs on windows 10

### ISSUE THREAD

**Issue by danny-arroway** [spyder-ide/spyder#12116]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Using python-3.8.2-amd64 and after upgrading pip and installing spyder
with:
pip install spyder

spyder v 4.1.1 hangs on "setting up main window" gui

### What steps reproduce the problem?

1. reinstall python3.8.2
2. install spyder with pip
3. launch spyder

### What is the expected output? What do you see instead?
Spyder IDE
Hangs on initialization of main window

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
Requirement already satisfied: spyder in c:\python38\lib\site-packages (4.1.1)
Requirement already satisfied: pyqt5<5.13; python_version >= "3" in c:\python38\lib\site-packages (from spyder) (5.12.3)
Requirement already satisfied: pylint>=0.25 in c:\python38\lib\site-packages (from spyder) (2.4.4)
Requirement already satisfied: parso==0.5.2 in c:\python38\lib\site-packages (from spyder) (0.5.2)
Requirement already satisfied: jedi==0.15.2 in c:\python38\lib\site-packages (from spyder) (0.15.2)
Requirement already satisfied: numpydoc>=0.6.0 in c:\python38\lib\site-packages (from spyder) (0.9.2)
Requirement already satisfied: paramiko>=2.4.0; platform_system == "Windows" in c:\python38\lib\site-packages (from spyder) (2.7.1)
Requirement already satisfied: spyder-kernels<1.10.0,>=1.9.0 in c:\python38\lib\site-packages (from spyder) (1.9.0)
Requirement already satisfied: keyring; sys_platform != "linux2" in c:\python38\lib\site-packages (from spyder) (21.2.0)
Requirement already satisfied: qtconsole>=4.6.0 in c:\python38\lib\site-packages (from spyder) (4.7.2)
Requirement already satisfied: qdarkstyle>=2.8 in c:\python38\lib\site-packages (from spyder) (2.8.1)
Requirement already satisfied: python-language-server[all]<0.32.0,>=0.31.9 in c:\python38\lib\site-packages (from spyder) (0.31.9)
Requirement already satisfied: intervaltree in c:\python38\lib\site-packages (from spyder) (3.0.2)
Requirement already satisfied: pexpect>=4.4.0 in c:\python38\lib\site-packages (from spyder) (4.8.0)
Requirement already satisfied: pyqtwebengine<5.13; python_version >= "3" in c:\python38\lib\site-packages (from spyder) (5.12.1)
Requirement already satisfied: sphinx>=0.6.6 in c:\python38\lib\site-packages (from spyder) (2.4.4)
Requirement already satisfied: qtpy>=1.5.0 in c:\python38\lib\site-packages (from spyder) (1.9.0)
Requirement already satisfied: atomicwrites>=1.2.0 in c:\python38\lib\site-packages (from spyder) (1.3.0)
Requirement already satisfied: nbconvert>=4.0 in c:\python38\lib\site-packages (from spyder) (5.6.1)
Requirement already satisfied: chardet>=2.0.0 in c:\python38\lib\site-packages (from spyder) (3.0.4)
Requirement already satisfied: psutil>=5.3 in c:\python38\lib\site-packages (from spyder) (5.7.0)
Requirement already satisfied: watchdog in c:\python38\lib\site-packages (from spyder) (0.10.2)
Requirement already satisfied: cloudpickle>=0.5.0 in c:\python38\lib\site-packages (from spyder) (1.3.0)
Requirement already satisfied: qtawesome>=0.5.7 in c:\python38\lib\site-packages (from spyder) (0.7.0)
Requirement already satisfied: diff-match-patch>=20181111 in c:\python38\lib\site-packages (from spyder) (20181111)
Requirement already satisfied: ipython>=4.0 in c:\python38\lib\site-packages (from spyder) (7.13.0)
Requirement already satisfied: pickleshare>=0.4 in c:\python38\lib\site-packages (from spyder) (0.7.5)
Requirement already satisfied: pyzmq>=17 in c:\python38\lib\site-packages (from spyder) (19.0.0)
Requirement already satisfied: pygments>=2.0 in c:\python38\lib\site-packages (from spyder) (2.6.1)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in c:\python38\lib\site-packages (from pyqt5<5.13; python_version >= "3"->spyder) (12.7.1)
Requirement already satisfied: mccabe<0.7,>=0.6 in c:\python38\lib\site-packages (from pylint>=0.25->spyder) (0.6.1)
Requirement already satisfied: colorama; sys_platform == "win32" in c:\python38\lib\site-packages (from pylint>=0.25->spyder) (0.4.3)
Requirement already satisfied: astroid<2.4,>=2.3.0 in c:\python38\lib\site-packages (from pylint>=0.25->spyder) (2.3.3)
Requirement already satisfied: isort<5,>=4.2.5 in c:\python38\lib\site-packages (from pylint>=0.25->spyder) (4.3.21)
Requirement already satisfied: Jinja2>=2.3 in c:\python38\lib\site-packages (from numpydoc>=0.6.0->spyder) (2.11.1)
Requirement already satisfied: pynacl>=1.0.1 in c:\python38\lib\site-packages (from paramiko>=2.4.0; platform_system == "Windows"->spyder) (1.3.0)
Requirement already satisfied: cryptography>=2.5 in c:\python38\lib\site-packages (from paramiko>=2.4.0; platform_system == "Windows"->spyder) (2.9)
Requirement already satisfied: bcrypt>=3.1.3 in c:\python38\lib\site-packages (from paramiko>=2.4.0; platform_system == "Windows"->spyder) (3.1.7)
Requirement already satisfied: ipykernel in c:\python38\lib\site-packages (from spyder-kernels<1.10.0,>=1.9.0->spyder) (5.2.0)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\python38\lib\site-packages (from spyder-kernels<1.10.0,>=1.9.0->spyder) (6.1.2)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\python38\lib\site-packages (from keyring; sys_platform != "linux2"->spyder) (0.2.0)
Requirement already satisfied: ipython-genutils in c:\python38\lib\site-packages (from qtconsole>=4.6.0->spyder) (0.2.0)
Requirement already satisfied: jupyter-core in c:\python38\lib\site-packages (from qtconsole>=4.6.0->spyder) (4.6.3)
Requirement already satisfied: traitlets in c:\python38\lib\site-packages (from qtconsole>=4.6.0->spyder) (4.3.3)
Requirement already satisfied: helpdev>=0.6.10 in c:\python38\lib\site-packages (from qdarkstyle>=2.8->spyder) (0.6.10)
Requirement already satisfied: python-jsonrpc-server>=0.3.2 in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (0.3.4)
Requirement already satisfied: pluggy in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (0.13.1)
Requirement already satisfied: yapf; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (0.29.0)
Requirement already satisfied: rope>=0.10.5; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (0.16.0)
Requirement already satisfied: pycodestyle; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (2.5.0)
Requirement already satisfied: pydocstyle>=2.0.0; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (5.0.2)
Requirement already satisfied: pyflakes>=1.6.0; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (2.1.1)
Requirement already satisfied: flake8; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (3.7.9)
Requirement already satisfied: autopep8; extra == "all" in c:\python38\lib\site-packages (from python-language-server[all]<0.32.0,>=0.31.9->spyder) (1.5)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in c:\python38\lib\site-packages (from intervaltree->spyder) (2.1.0)
Requirement already satisfied: ptyprocess>=0.5 in c:\python38\lib\site-packages (from pexpect>=4.4.0->spyder) (0.6.0)
Requirement already satisfied: requests>=2.5.0 in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (2.23.0)
Requirement already satisfied: setuptools in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (41.2.0)
Requirement already satisfied: snowballstemmer>=1.1 in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (2.0.0)
Requirement already satisfied: sphinxcontrib-jsmath in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.0.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (0.7.12)
Requirement already satisfied: sphinxcontrib-devhelp in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.0.2)
Requirement already satisfied: sphinxcontrib-htmlhelp in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.0.3)
Requirement already satisfied: babel!=2.0,>=1.3 in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (2.8.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.1.4)
Requirement already satisfied: packaging in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (20.3)
Requirement already satisfied: sphinxcontrib-applehelp in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.0.2)
Requirement already satisfied: docutils>=0.12 in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (0.16)
Requirement already satisfied: sphinxcontrib-qthelp in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.0.3)
Requirement already satisfied: imagesize in c:\python38\lib\site-packages (from sphinx>=0.6.6->spyder) (1.2.0)
Requirement already satisfied: entrypoints>=0.2.2 in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (0.3)
Requirement already satisfied: bleach in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (3.1.4)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (0.8.4)
Requirement already satisfied: nbformat>=4.4 in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (5.0.5)
Requirement already satisfied: testpath in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (0.4.4)
Requirement already satisfied: defusedxml in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (0.6.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\python38\lib\site-packages (from nbconvert>=4.0->spyder) (1.4.2)
Requirement already satisfied: pathtools>=0.1.1 in c:\python38\lib\site-packages (from watchdog->spyder) (0.1.2)
Requirement already satisfied: six in c:\python38\lib\site-packages (from qtawesome>=0.5.7->spyder) (1.14.0)
Requirement already satisfied: backcall in c:\python38\lib\site-packages (from ipython>=4.0->spyder) (0.1.0)
Requirement already satisfied: decorator in c:\python38\lib\site-packages (from ipython>=4.0->spyder) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\python38\lib\site-packages (from ipython>=4.0->spyder) (3.0.5)
Requirement already satisfied: wrapt==1.11.* in c:\python38\lib\site-packages (from astroid<2.4,>=2.3.0->pylint>=0.25->spyder) (1.11.2)
Requirement already satisfied: lazy-object-proxy==1.4.* in c:\python38\lib\site-packages (from astroid<2.4,>=2.3.0->pylint>=0.25->spyder) (1.4.3)
Requirement already satisfied: MarkupSafe>=0.23 in c:\python38\lib\site-packages (from Jinja2>=2.3->numpydoc>=0.6.0->spyder) (1.1.1)
Requirement already satisfied: cffi>=1.4.1 in c:\python38\lib\site-packages (from pynacl>=1.0.1->paramiko>=2.4.0; platform_system == "Windows"->spyder) (1.14.0)
Requirement already satisfied: tornado>=4.2 in c:\python38\lib\site-packages (from ipykernel->spyder-kernels<1.10.0,>=1.9.0->spyder) (6.0.4)
Requirement already satisfied: python-dateutil>=2.1 in c:\python38\lib\site-packages (from jupyter-client>=5.3.4->spyder-kernels<1.10.0,>=1.9.0->spyder) (2.8.1)
Requirement already satisfied: pywin32>=1.0; sys_platform == "win32" in c:\python38\lib\site-packages (from jupyter-core->qtconsole>=4.6.0->spyder) (227)
Requirement already satisfied: importlib-metadata in c:\python38\lib\site-packages (from helpdev>=0.6.10->qdarkstyle>=2.8->spyder) (1.6.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\python38\lib\site-packages (from requests>=2.5.0->sphinx>=0.6.6->spyder) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\python38\lib\site-packages (from requests>=2.5.0->sphinx>=0.6.6->spyder) (1.25.8)
Requirement already satisfied: idna<3,>=2.5 in c:\python38\lib\site-packages (from requests>=2.5.0->sphinx>=0.6.6->spyder) (2.9)
Requirement already satisfied: pytz>=2015.7 in c:\python38\lib\site-packages (from babel!=2.0,>=1.3->sphinx>=0.6.6->spyder) (2019.3)
Requirement already satisfied: pyparsing>=2.0.2 in c:\python38\lib\site-packages (from packaging->sphinx>=0.6.6->spyder) (2.4.6)
Requirement already satisfied: webencodings in c:\python38\lib\site-packages (from bleach->nbconvert>=4.0->spyder) (0.5.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in c:\python38\lib\site-packages (from nbformat>=4.4->nbconvert>=4.0->spyder) (3.2.0)
Requirement already satisfied: wcwidth in c:\python38\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=4.0->spyder) (0.1.9)
Requirement already satisfied: pycparser in c:\python38\lib\site-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=2.4.0; platform_system == "Windows"->spyder) (2.20)
Requirement already satisfied: zipp>=0.5 in c:\python38\lib\site-packages (from importlib-metadata->helpdev>=0.6.10->qdarkstyle>=2.8->spyder) (3.1.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=4.0->spyder) (0.16.0)
Requirement already satisfied: attrs>=17.4.0 in c:\python38\lib\site-packages (from jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert>=4.0->spyder) (19.3.0)

**Comment by MrFuppes** [comment]
sounds like the tornado-issue, see https://stackoverflow.com/questions/58557238/spyder-ide-fails-to-start-on-windows-10-with-python-3-8

**Comment by danny-arroway** [comment]
MrFuppes:
Brilliant, this works perfectly, thanks so much!
I had reverted to Python 3.7.5 to get Spyder 4.1.1 working, but your solution allows me to use the latest version on Windows. No issues on Linux Mint.
Thanks again!

**Comment by danny-arroway** [comment]
Thanks very much!
Really appreciate your help!

**Comment by MrFuppes** [comment]
Glad I could help! I hope the Spyder core developers find a fix for this before the next Python release (3.8.3) since this affects ALL Windows users and Carlos stated that Spyder is in fact not using asyncio...

**Comment by pybokeh** [comment]
Thanks!  Adding the import in asyncio.py fixed for me.
