### ISSUE TITLE
cannot locate ordinary number 242 error messeage on launch

### ISSUE THREAD

**Issue by Druid-error** [spyder-ide/spyder#12113]
hello. recently i installed anaconda3 to use the spyder IDE, as recommended by my IT teacher. but i cannot open spyder, and a error messeage pops up saying "cannot locate ordinal number 242 on the dinamic bond library C:\ProgramData\Anaconda3\Library\bin\mkl_intel_thread.dll"(the whole thing is in portuguese, so this translation might not be 100% accurate to the english version).

i just started learning programming, so i'm overall very very lost.

### What steps reproduce the problem?

1. installing anaconda3 normally
2. 
3. 

### What is the expected output? What do you see instead?
spyder should open, instead it doesnt, and the  "cannot locate ordinal number 242 on the dinamic bond library C:\ProgramData\Anaconda3\Library\bin\mkl_intel_thread.dll" window shows up, even thought this particular file is in this directory

## Versions

* Spyder version: 4.0.1
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10 64-bit

**Comment by bcolsen** [comment]
This can happen when mkl is already installed in system32 in the windows directory.

You can search for `mkl_core.dll` on your computer to see if you have another installation.

**Comment by bcolsen** [comment]
See #7357

**Comment by Druid-error** [comment]
i will check this thread out, will update if managed to solve the issue

**Comment by ccordoba12** [comment]
Closing because this is not an issue with Spyder.
