### ISSUE TITLE
spyder won't launch kernels, *error message useless for debugging*

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#12124]
## Problem Description
Spyder complains about the version of `spyder-kernels`:
![image](https://user-images.githubusercontent.com/881019/78364553-fc1c1d80-7600-11ea-88c0-0b792f7625f2.png)

I assume it's complaining about the version I have installed because I do have version `2.0.0.dev0` installed. As worded though it's completely ambiguous whether the version listed in the error message is the version installed (which is somehow incorrect?) or is the required version.

Since I do have master of `spyder-kernels` installed as well I assume there's some incompatibility between the master of both projects. If the spyder IDE has gone to the extent to check the version of `spyder-kernels` installed and found it somehow inadequate then it should let the user know, in the error message, what the version constraint is.

I'm running spyder master on win64/py37:

![image](https://user-images.githubusercontent.com/881019/78364664-32f23380-7601-11ea-80c1-3fb479f1132b.png)

**Comment by dhirschfeld** [comment]
```python
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> import spyder_kernels
>>> spyder_kernels.__version__
'2.0.0.dev0'

>>> 
```

**Comment by dhirschfeld** [comment]
...internal console...
```python
>>> from spyder.utils import programs
>>> programs.is_module_installed('spyder_kernels',version='>=2.0.0.dev0')
True

>>> 
```

**Comment by dhirschfeld** [comment]
Ok, so replacing the below code with `has_spyder_kernels  = True` and everything works fine.
https://github.com/spyder-ide/spyder/blob/204ff33dde969a8cbb29f1fd1170419afae4839c/spyder/plugins/ipythonconsole/plugin.py#L680-L683

As demonstrated above, the above code returns True when I run it from teh spyder internal console but apparently when spyder tries to start a kernel it incorrectly return False.

Seems like a strange bug! ¯\\_(ツ)_/¯

It perhaps points to an issue with `is_module_installed` when `bootstrap.py` is run from a conda environment with spyder-kernels installed with `pip install --no-deps -e .`

Perhaps this is such a specialised use-case that the solution is for me to just patch my source (as I have done)

**Comment by ccordoba12** [comment]
> Seems like a strange bug! ¯\(ツ)/¯

You're welcome to submit a PR to fix it.

Sorry, but we don't have time to support people that wants to run master when we haven't released the first beta for Spyder 5.
