### ISSUE TITLE
kite plugin is not able to install

### ISSUE THREAD

**Issue by ashton2323** [spyder-ide/spyder#12120]
i had tried installing kite plugin for spyder in linux but it doesnot get install . it shows installation error. everytime. i had spyder installed in anaconda env.

**Comment by ashton2323** [comment]
(base) ashton2323@ashton2323:~$ ./kite-installer install kite
[installer] no previous kite installation found
[installer] latest version is 2.20200327.0, downloading now...
[installer] /home/ashton2323/.local/share/kite/kite-updater-2.20200327.0.sh already exists, validating...
[installer] checksum doesn't match, downloading again...
[installer] Downloading Kite:  100.0% of 398MiB
[installer] verifying checksum
[installer] validating signature
[installer] installing version 2.20200327.0
[installer] installed ~/.config/autostart/kite-autostart.desktop
[installer] installed ~/.config/systemd/user/kite-updater.service
[installer] installed ~/.config/systemd/user/kite-updater.timer
[installer] error installing system files: error installing ~/.local/share/applications/kite-copilot.desktop: open /home/ashton2323/.local/share/applications/kite-copilot.desktop: permission denied
[installer] Rolling back installed data...
[installer] terminating kite processes
[installer] removing kite-updater systemd service
[installer] removed ~/.config/autostart/kite-autostart.desktop
[installer] removed ~/.config/systemd/user/kite-updater.service
[installer] removed ~/.config/systemd/user/kite-updater.timer
[installer] removed ~/.local/share/kite
Rollbar error: received response: 429 Too Many Requests
Rollbar error: received response: 429 Too Many Requests
Rollbar error: received response: 429 Too Many Requests
Rollbar error: received response: 429 Too Many Requests

**Comment by ccordoba12** [comment]
Sorry but this is an issue with Kite and not Spyder. Please report it here:

https://github.com/kiteco/plugins
