### ISSUE TITLE
I ran the update as requested...

### ISSUE THREAD

**Issue by kewlncguy** [spyder-ide/spyder#12129]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by kewlncguy** [comment]
I ran the update as requested ( I am A+< Network + MCSE x 3 MCITP< MCSA x 3 CCNP) and all of the other letters on paper. I tried to update twice and it just kept running through saying it was checking why it would not update for and hour aalmost and then gave an ambiguious message like iy maybe had complete but I opened it up and it gave me another "Upate Available" THis was on a new MSI WIndows 10 machine and a new install of the software

**Comment by ccordoba12** [comment]
Please run first

    conda update anaconda

and then

    conda install spyder=4.1.1

**Comment by kewlncguy** [comment]
I have already done this procedure. Just to double check I ran the first command and it listed the files and said "All of the files will be DOWNGRADED (y/n) so I chose n
