### ISSUE TITLE
If main window is closed with undocked panes, those are not shown during the next session

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12139]
I undocked the Plots pane - when restarted Spyder, it was no longer where it was previously docked (or in any other window; had to Tools -> Panes -> Plots). Bug or feature? If latter, it'd help to have an option to have Spyder dock to latest position after undock + restart.

**Comment by OverLordGoldDragon** [comment]
Oh, actually the pane it docks itself back if closed before shutting down Spyder itself - better, but with a taskbar salad can be a slight nuisance.

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one. The idea is to close all undocked windows before closing the main one.

**Comment by andfoy** [comment]
> The idea is to close all undocked windows before closing the main one.

It seems that we're already doing this:
https://github.com/spyder-ide/spyder/blob/d6e2e849b1969e531aad65f7b9afcf439726bbbd/spyder/app/mainwindow.py#L2477

https://github.com/spyder-ide/spyder/blob/d6e2e849b1969e531aad65f7b9afcf439726bbbd/spyder/plugins/base.py#L338

**Comment by OverLordGoldDragon** [comment]
@andfoy [demo.mp4](https://puu.sh/FwzCO/ca76b9d91c.mp4) of what I'm seeing

**Comment by ccordoba12** [comment]
Thanks for the video. That really clarified for us what the problem was.
