### ISSUE TITLE
Feature request: Memory profiler

### ISSUE THREAD

**Issue by gerazov** [spyder-ide/spyder#12147]
It might be a good idea to have an integrated memory profiler at user disposal. I've had to deal with memory leaks a few times when working with large data, and sometimes it's helpful to use a memory profiler to pinpoint the problematic areas.

I've used [memory-profiler](https://pypi.org/project/memory-profiler/) before with great success.

**Comment by jitseniesen** [comment]
The [spyder-memory-profiler](https://github.com/spyder-ide/spyder-memory-profiler) plugin integrates memory-profiler into Spyder. If for some reason that is not sufficient for your needs, then file an issue in that repository.

**Comment by gerazov** [comment]
Sorry, missed that one. Thanks!
