### ISSUE TITLE
Move plots in Plots pane

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12158]
Possible? I currently have to re-plot stuff to order them a certain way for viewing, which can be quite expensive. The Plots pane is nice for directly comparing images, but this feature seems absent.

**Comment by goanpeca** [comment]
@jnsebgosselin what do you think?

**Comment by ccordoba12** [comment]
Nice suggestion @OverLordGoldDragon! It shouldn't be that hard to implement (I think).

**Comment by jnsebgosselin** [comment]
Like moving up and down the plots in the thumbnail scrollbar?

If it is implemented with toolbuttons like for the Python path manger, this will be easy. If it needs to be done with some kind of drag and drop feature, this will be harder.

![image](https://user-images.githubusercontent.com/10170372/78521522-1d634200-7798-11ea-86ec-79c2eb1e0b59.png)

**Comment by tstreibl** [comment]
Would be great to combine this with a full size view of the thumb upon double click? Ideally you could  scroll through your thumbs with "image up", "image down" keys in full size view. Maybe the magnifying glass icons already serve this purpos, but in my case they are disabled, at least for mathplotlib pictures.

**Comment by OverLordGoldDragon** [comment]
@jnsebgosselin Yeah, in the thumbnail scrollbar. Drag & drop doesn't really matter - though it'd be even better if it had shortcuts.

@tstreibl Do you mean like below? You can undock the Plots pane and drag away the thumbnail bar to maximize view size.

![image](https://user-images.githubusercontent.com/16495490/78558002-ea19c500-7822-11ea-9795-7a51b56cff50.png)

<details>
  <summary>Plot code</summary>

```python
import numpy as np
import matplotlib.pyplot as plt

def pplot(r, w=1, h=1):
    plt.polar(r)
    plt.gcf().set_size_inches(18 * w, 18 * h)

pplot(- np.linspace(0, 1, 300)**12)
pplot(np.exp(- np.linspace(0, 1, 400)))
pplot(np.linspace(0, 1, 300) ** 2)
```

</defails>

**Comment by tstreibl** [comment]
Wow - did't realize that it's so easy. Sorry that I did't get it. Problem solved. Thanks.

**Comment by jnsebgosselin** [comment]
>Maybe the magnifying glass icons already serve this purpos, but in my case they are disabled, at least for mathplotlib pictures.

They are disabled when `Fits plot to window` is checked.

![image](https://user-images.githubusercontent.com/10170372/78564440-6e038b00-77ea-11ea-85a8-ffb9bfea38ce.png)

**Comment by tstreibl** [comment]
komplete shame on me. Thanks.

**Comment by jnsebgosselin** [comment]
No worries, it's not like it was well documented and you are not the first confused by this. Maybe we need to change that to make it less confusing...

**Comment by tstreibl** [comment]
It's intuitive and fit's together once you decide to play around with the docking capabilities. I like that it's also easy to redock, so it's in deed a full featured image viewer. Great.

**Comment by OverLordGoldDragon** [comment]
Any progress? Am willing to contribute, with some guidance

**Comment by OverLordGoldDragon** [comment]
Pinging in case notifs failed, @jnsebgosselin @ccordoba12

**Comment by OverLordGoldDragon** [comment]
@jnsebgosselin My main use case by far is executing some IPython code twice with an altered parameter, then comparing the resulting images. To me this is best done in an "overlapped" manner, just without overlapping - by pressing up and down arrow keys and changing between the images, effectively a GIF. When it's just one image, it can already be done, no problem.

In additional to manual sorting, it'd be great if there was a feature to automatically arrange images this way - like

```
0 1 2 3 4 5
-->
0 3 1 4 2 5
```

**Comment by jnsebgosselin** [comment]
Thanks for your feedback @OverLordGoldDragon and sorry for not implementing this sooner. I am going to start on this next week, for real this time XD.

**Comment by OverLordGoldDragon** [comment]
@jnsebgosselin Glad it's being worked on at all!

**Comment by OverLordGoldDragon** [comment]
It can't be helped if I'm the only one asking, but, I'd still appreciate this feature. I understand if it's out of scope though.

**Comment by ccordoba12** [comment]
Sorry for the long delay in addressing this one. I took a look at it today and managed to implement it quickly thanks to this resource on the web:

https://www.pythonguis.com/faq/pyqt-drag-drop-widgets/

So, I'm marking it for 6.0 beta1, to be released in two or three weeks.

**Comment by OverLordGoldDragon** [comment]
Thank you! This is great for me.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 While I can drag the plots, the arrow keys think nothing was dragged:

![image](https://github.com/user-attachments/assets/9f5bcd55-15dc-4a28-baa9-46eca3602750)

**Comment by ccordoba12** [comment]
Ok, please open a new issue about it.
