### ISSUE TITLE
Problem of starting the kernel 

### ISSUE THREAD

**Issue by Wq-dd** [spyder-ide/spyder#12164]
### What steps will reproduce the problem?

step1. I upgrade spyder to version 3.3.6
step2. I restart spyder but there is a problem message showing in the console, which noting that "The directory /home/ff.../runtime is not writable and it is required to create IPython consoles. Please make it writable"
step3. I tried to reset spyder and restart my PC. But the problem is not solved

### Traceback
```python-traceback
  File "/home/ff/anaconda3/envs/tf/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 1396, in close_client
    if len(related_clients) == 0 and osp.exists(client.stderr_file):
  File "/home/ff/anaconda3/envs/tf/lib/python3.5/genericpath.py", line 19, in exists
    os.stat(path)
TypeError: stat: can't specify None for path argument
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.5.4
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-91-generic

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.6.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.16.0 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  0.25.3 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0     :  6.1.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  1.7.2 (OK)
```

**Comment by ccordoba12** [comment]
Please fix the problem on your side by doing what the error message says. The problem is not in Spyder, so no amount of reset will fix it.
