### ISSUE TITLE
Lambda Function error 

### ISSUE THREAD

**Issue by LuisAzabache** [spyder-ide/spyder#12163]
Hello, may I ask why Im having this error in Spyder while in another IDE its running correctly?

triangle_area=lambda base,height:(base*height)/2
triangle1=triangle_area(5,5)
print(str(triangle1))

Traceback (most recent call last):

  File "<ipython-input-23-a73befa553cb>", line 5, in <module>
    print(str(triangle1))

TypeError: 'float' object is not callable

Thanks in advance for watching and taking care on this.

Spyder 4.1.1 
Python 3.7.4 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by jitseniesen** [comment]
It works fine on my computer. My guess is that you redefined `print` or `str`, so restart the kernel or Spyder and try again. If that does not work, please provide specific step-by-step instructions on how to reproduce the errors and a screen shot.
