### ISSUE TITLE
spyder crash and reset

### ISSUE THREAD

**Issue by rajiroseseirni** [spyder-ide/spyder#12174]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
whenever im opening spyder it showing crash of spyder4.1.1 and reset spyder. how can i fix this problem

**Comment by ccordoba12** [comment]
Please post a screenshot of what you're seeing because I don't understand what you mean by this.

**Comment by rajiroseseirni** [comment]
Ok sure

**Comment by rajiroseseirni** [comment]
This is what I'm getting.

**Comment by rajiroseseirni** [comment]
I reset spyder in anaconda prompt. Again same issue arising. How to fix
this issue. Please help me.

**Comment by ccordoba12** [comment]
Sorry but we can't help you with so little info. So I'm afraid I'll have to close this one.

**Comment by ccordoba12** [comment]
And unless you manage to give us more info, please don't open more issues about this problem.
