### ISSUE TITLE
Code Analysis not working properly

### ISSUE THREAD

**Issue by evanraj513** [spyder-ide/spyder#12199]
So I just updated to Spyder 4.0 using conda python update, and the code analysis portion is quite finicky. Typically, when I hovered over any warning sign in Python 3.7, it would give me the code analysis. Once I updated, it will now only do this hover pop-up on some issues. Others I cannot get to leave, and then some will display the error if I compact the code and then unpack it. Any suggestions? It's small, but exceedingly annoying. 

On another note, I love the new dark mode! 

Working with Mac OS 10.13.6.

**Comment by ccordoba12** [comment]
Please be sure to use 4.1.2, which fixes a lot of these problems, and try again.

**Comment by evanraj513** [comment]
I am using Spyder 4.1.2, and am on Anaconda 1.9.12.

**Comment by ccordoba12** [comment]
Then please post one or more screenshots of what you mean because your description is very imprecise.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by rustequal** [comment]
same here, version 4.1.3. The code analysis works about 5 minutes, after that it just gets stuck

**Comment by MikeJonessss** [comment]
same problem for me. after reseting spyder back to factory defaults it works again for a while, then after a while working gets stuck. I first thought the problem was due to Kite, but I uninstalled that. I like the code analysis feature, so it is quite annoying to see that it still works in Spyder 3 but not in 4. Thank you very much.

**Comment by ccordoba12** [comment]
This should be fixed in our next version (4.1.4) to be released next week.

**Comment by MikeJonessss** [comment]
great! i notice that if I turn stdio pipes on and off in advanced completion and linting the code analysis also starts working again. I look forward to the new version, thank you very much.

**Comment by geograz** [comment]
> 
> 
> great! i notice that if I turn stdio pipes on and off in advanced completion and linting the code analysis also starts working again. I look forward to the new version, thank you very much.

I have the same problem, but this trick surprisingly helps. Thanks!
