### ISSUE TITLE
Fix conflicts on generation of po files with crowdin

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#12198]
- [ ] Dates are causing conflicts, easy to solve, but maybe that could be omitted from generated files to avoid unnecessary conflicts.
- [ ] Check how to avoid more conflicts

**Comment by ccordoba12** [comment]
@goanpeca verified that simply closing the current PR generated by Crowdin and waiting for it to generate a new one solves this problem. So there's no need to do anything else in our side.
