### ISSUE TITLE
Feature Request: Upgrade Spyder's Environment Handling

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#12200]
## Feature Request & Discussion

I've been poking around in the code related to external iPython kernels as it relates to getting the standalone Mac application up and running and noticed that establishing the custom interpreter is largely done by inspecting the path of the selected python interpreter. This work fine for conda environments, but precludes the use of pyenv environments.

I propose adding a feature that can capture a user's system virtual environments upon launching the preferences window and lists them in a drop-down menu for selection. Rather than listing the path to a python interpreter, this list would show only the virtual environment names. The custom interpreter field can still be used for venv environments that cannot be easily captured. This would be more convenient for the user to identify and select console environments without the need to navigate file structures. Additionally, it would always reflect environments added or removed from the user's system.

### How it works
I think that a simple login shell script should be able to capture all of a user's conda environments and pyenv environments by name, as well as the any necessary environment activation prefixes. These can then be stored in the configuration object, the names of which can be displayed in a dropdown list. The existing custom interpreter field could still be used to capture localized venv environments not visible to a simple system query.

**Comment by ccordoba12** [comment]
> This work fine for conda environments, but precludes the use of pyenv environments.

Could you explain why?

> I propose adding a feature that can capture a user's system virtual environments upon launching the preferences window and lists them in a drop-down menu for selection.

Nice idea! However, if this requires important changes to the our Preferences (either in the UI or code), I'm afraid we'll have to leave it for Spyder 5.

> Rather than listing the path to a python interpreter, this list would show only the virtual environment names. The custom interpreter field can still be used for venv environments that cannot be easily captured. This would be more convenient for the user to identify and select console environments without the need to navigate file structures. Additionally, it would always reflect environments added or removed from the user's system.

Sounds good. Are you thinking to replace the "Python interpreter" entry in Preferences with this?

> I think that a simple login shell script should be able to capture all of a user's conda environments and pyenv environments by name

Please remember that this also needs to work on Windows. So I don't know if this would work there too.

**Comment by mrclary** [comment]
> > This work fine for conda environments, but precludes the use of pyenv environments.
> 
> Could you explain why?

Sure. Like conda environments, pyenv environments must be activated to work properly. Unlike conda environments, the environment can't be determined from the python executable path. For conda, you have something like `/Users/<user>/anaconda3/bin/envs/<env>/bin/python` or some variation, with the `<env>` specified in the path, which can be extracted and later provided as the environment to activate in an activation script.

For pyenv, however, the executable path is a symlink, the target of which does _not_ have the environment in the path. This is an example from my system:
`/Users/rclary/.pyenv/versions/3.7.7/envs/spy377-sa/bin/python -> /Users/rclary/.pyenv/versions/3.7.7/bin/python3.7`
The symlink is resolved upon selecting in the preferences and before the environment (here `spy377-sa`) can be extracted, thus Spyder has no way of knowing which environment to tell pyenv to activate.

> > I propose adding a feature that can capture a user's system virtual environments upon launching the preferences window and lists them in a drop-down menu for selection.
> 
> Nice idea! However, if this requires important changes to the our Preferences (either in the UI or code), I'm afraid we'll have to leave it for Spyder 5.

Absolutely. This will not be a small project and may require refactoring our extraction of interpreter information, which is presently conda-centric.
 
> > Rather than listing the path to a python interpreter, this list would show only the virtual environment names. The custom interpreter field can still be used for venv environments that cannot be easily captured. This would be more convenient for the user to identify and select console environments without the need to navigate file structures. Additionally, it would always reflect environments added or removed from the user's system.
> 
> Sounds good. Are you thinking to replace the "Python interpreter" entry in Preferences with this?

I propose something like this:
<img width="1162" alt="Screen Shot 2020-04-07 at 10 56 23 AM" src="https://user-images.githubusercontent.com/9618975/78703592-521de900-78bf-11ea-91ee-1b3f4a6d27f5.png">

> > I think that a simple login shell script should be able to capture all of a user's conda environments and pyenv environments by name
> 
> Please remember that this also needs to work on Windows. So I don't know if this would work there too.

I don't know exactly how this works on Windows, so this would have to be investigated. However, I assume that there must be a way to do this. For *nix systems, pyenv and conda provide envrionment variables that tell where `conda` and `pyenv` commands are. They must provide similar information on Windows systems. Both conda and pyenv also list their virtual environments, e.g. `conda env list` or `pyenv versions`. These commands will also be available on Windows systems. However, for these to work, conda and pyenv must be setup in one's shell startup chain (usually in `~/.bash_profile` on MacOS). This is guaranteed on *nix systems if a login shell is invoked, i.e. having the `-l` flag on the shabang line: `/usr/bin/env bash -l`. I assume there is an analogous paradigm on Windows.

**Comment by ccordoba12** [comment]
> Sure. Like conda environments, pyenv environments must be activated to work properly. Unlike conda environments, the environment can't be determined from the python executable path.

Ok, I didn't know that. I must confess I haven't used  pyenv's at all.

> I propose something like this

I agree with your proposed UI. And perhaps we should also rename the "Python interpreter" entry to be "Python environment" instead.

**Comment by mrclary** [comment]
I've only recently become aware of pyenv, pyenv-virtualenv, and venv in the effort to revive the Mac app. So now I know enough to get into real trouble, but not enough to get out ;-)

**Comment by mrclary** [comment]
Okay, just to recap and flesh out the idea a bit more...

Currently Spyder provides a way to select the iPython environment of new consoles in the preferences.
This works well as a "default" setting for new consoles but it would be very nice to be able to select environments for new consoles on the fly or change the environment of existing consoles.
I envision the following features:
* In the preferences, the default iPython environment for new consoles will keep the existing mechanisms of "Default (i.e. the Same as Spyder's)" or "Use the following Python interpreter", but have an additional selection option "Use the following environment" which would be a drop-down list populated from environments automatically identified on the system. These environments could include the system Python, identified Conda environments, and identified Pyenv environments.
* The status bar environment indicator, when clicked, will reveal the list of identified environments on the system (as in the preferences in the previous item). When selected, the current console will restart in the new environment.
* The status bar environment indicator should indicate the environment of the current console, not necessarily the environment selected in Spyder's preferences.
* The console widget settings dropdown menu item "New console (default settings)" will change to "New Console" with a submenu list of "Default" and the identified environments on the system.
* The "Run configuration per file" console settings, in addition to selecting a current, dedicated, or external console, should should have a dropdown list of identified system environments to use. This would be greyed out if "current" console is selected.

Note that in order to properly handle Pyenv environments, the paths to identified python executables should not be resolved if they are symbolic links, or a different mechanism for identifying environments should be used.

**Comment by goanpeca** [comment]
@mrclary so some things could go to 4.2 if they are not too disruptive.

1. Being able to have the Environment status widget track the current console seems not that I would be in favor of adding to 4.2
2. Being able to select an environment by clicking on that widget is also something I would consider beneficial enough to go in 4.2

@spyder-ide/core-developers thoughts?

I can help and provide some pointed to you to get this done @mrclary

**Comment by ccordoba12** [comment]
> Being able to have the Environment status widget track the current console seems not that I would be in favor of adding to 4.2

That would require adding a handler in the kernel that can be called each time a console gains focus. @dalthviz can help with that because he knows how to do it very well.

> Being able to select an environment by clicking on that widget is also something I would consider beneficial enough to go in 4.2

This would require some library code to detect all venv/conda environments available. The conda part is rather easy (`conda env list --json`) but I have no idea how to do that for other venvs.

Once that info is collected, creating the UI for it shouldn't be that hard.

> @spyder-ide/core-developers thoughts?

I agree that this could go for 4.2, if delivered by end of August at most.

**Comment by mrclary** [comment]
> This would require some library code to detect all venv/conda environments available. The conda part is rather easy (`conda env list --json`) but I have no idea how to do that for other venvs.

For other envs:
* Pyenv would be similar to conda but a bit more involved since it doesn't provide a convenient "json" output. Basically `pyenv versions --bare --skip-aliases` gives a list of all environments.
* venv environments would be difficult to automatically detect since they may be located anywhere in the filesystem.

**Comment by ccordoba12** [comment]
Great! Then let's leave automatic detection of venv's out of picture. But if a user enters one in `Python interpreter`, then we should add it to the list.

**Comment by mrclary** [comment]
Is it that difficult to add the drop-down selection to the preferences window as well? Then it seems that all of the bullets could be included. Though, maybe the end of August will be too ambitous...maybe 4.3?

**Comment by goanpeca** [comment]
>Is it that difficult to add the drop-down selection to the preferences window as well?

Not really but it is easier to tackle these things in steps. Smaller steps are more likely to succeed in this case were clear tasks can be defined.

**Comment by CAM-Gerlach** [comment]
Adding a submenu to the IPython console options and context menus to launch a console in the selected environment (like we currently have for launching "special" consoles) is also a relatively small but very impactful change we should fast-track, IMO; I've been wanting to do it for some time just with the existing saved environments and it should be relatively straightforward, while hugely improving the UX for opening one or more consoles in different environments and having (arguably) the most "bang for the buck" of the improvements suggested here.

It doesn't actually require the new environment detection infra to be in place; it can also use the existing saved list; all that should be needed is adding a submenu object populated with items corresponding with the env list, and having [`spyder.plugins.ipythonconsole.plugin.create_new_client()`](https://github.com/spyder-ide/spyder/blob/c2abd47c5e822540689db3a02e4dfa4f0cf549b2/spyder/plugins/ipythonconsole/plugin.py#L720) take an argument with the interpreter path (or some key corresponding to the same). The one complexity is updating this list if the user adds an interpreter in the preferences, but perhaps that could be handled with a Qt Signal or similar?

The current alternative is opening preferences, navigating to the correct pane, selected the desired environment from the list, waiting 20-30 seconds for Spyder to check it and the setting to save and apply, closing the dialog, and then opening a new console; double if the user wants to switch back to their original default after. This is especially annoying as switching projects closes all open consoles and restarts a single console in the current default environment, requiring users to set up their desired consoles again, which can easily take multiple minutes with the current UX but would take only seconds with this proposed UX

**Comment by ccordoba12** [comment]
@mrclary, we decided to take care of this one because it has several UX/UI issues that we need to carefully design and test. @steff456 and @juanis2112 are going to work on them.

**Comment by juanis2112** [comment]
Thanks @ccordoba12. Here is the issue where our designer posted the mock up for this https://github.com/spyder-ide/ux-improvements/issues/10

**Comment by CAM-Gerlach** [comment]
@ccordoba12 This should be re-opened and retargeted for Spyder 5 to correspond to spyder-ide/ux-improvements#10 , since the only part of @mrclary 's feature request, or his or my detailed proposals that was actually addressed in PR #13950 was also the subject of issue #13903 , which that PR also closed.

Also, @mrclary , we'd love to have your input on spyder-ide/ux-improvements#10 ; its clear you've put a ton of thought and effort into how to make this work well, in addition to being a heavy user of environments and productive contributor to Spyder so it would be very valuable if you wouldn't mind sharing your ideas over there. Thanks.

**Comment by ccordoba12** [comment]
Please don't reopen it. This is already referenced in our changeling, so we can't do that.

Let's continue the discussion in the ux-improvements repo instead.
