### ISSUE TITLE
Variables not cleaned up completely in current console

### ISSUE THREAD

**Issue by jrast** [spyder-ide/spyder#12209]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder does not delete all variables from the previous runfile if the previous run terminated with an exception. This leads to errors if resources are opened which can only be opened once and would normaly be closed if the variable holding the resource is deleted.

### What steps reproduce the problem?

1.  Create a file with the following content
````python
import socket

s = socket.socket()  # This is our resource which can only be used once
s.bind(('', 12345))
s.listen(5)

raise ValueError('Here something happens and the script aborts')

s.close()  # Ooops, not closed! But should be closed if s is deleted
````
2. Run the file, make sure the "Remove all variables before execution" checkbox is checked in the file configuration (see attached image). This run will terminate with a ValueError
3. Run the file again. This run will terminate with an OSError because the socket is still open.

![image](https://user-images.githubusercontent.com/146369/78697810-ad70cb00-7901-11ea-84b1-afbaf17531aa.png)

### What is the expected output? What do you see instead?
I expect that the checkbox "Delete all variables before execution" would really delete all variables. But they are kept somehow, even if no longer accessible.
For example, this works in a IPython console and i expected the same from spyder:
````ipython
%run script.py
# --> ValueError
%reset -sf
%run script.py
# --> ValueError
````

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.6 64-bit
* Qt version: 5.12.7
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
I'm sorry but I don't think we could do something about this because (as you clearly mentioned) that socket can't be deleted because it was not properly closed.

In this case you simply need to restart the kernel, sorry.

**Comment by jrast** [comment]
> I'm sorry but I don't think we could do something about this because (as you clearly mentioned) that socket can't be deleted because it was not properly closed.

It's no problem at all to delete the socket without closing it first! And if the socket is deleted, it's also correctly closed! Try this:
````python
import socket

s = socket.socket()  # This is our resource which can only be used once
s.bind(('', 12345))
s.listen(5)

try:
    raise ValueError('Here something happens and the script aborts')
except:
    del s
    raise

s.close()  # Ooops, not closed! But should be closed if s is deleted
````
This works as expected!

> In this case you simply need to restart the kernel, sorry.

Why does it require a restart in Spyder but not in the IPython console? I always tought that "deleting all variables before execution" is something like `%reset -sf` in the ipython console, but obviously it's not, because in the ipython console it's working!

**Comment by jrast** [comment]
In the mean time I played around on another machine, using almost the same setup. It seems there is a workaround for this: 
If the Option "Run in  console's namespace instead of an empty one" is checked in the "Run configuration per file" Dialog, the behaviour is as expected: the socket is deleted/closed!

So, there is clearly something going on on how spyder is preparing the run of the script, and the preparation is different depending on this setting!

PS: the installation on this machine is in english, the other in german...

**Comment by ccordoba12** [comment]
Glad you were able to find a workaround. If you find the cause, please submit a pull request with the fix.

**Comment by jrast** [comment]
Can you give me a pointer on where to start investigating this issue? 
Is this the right place to look at: https://github.com/spyder-ide/spyder/blob/a27be76e00ac95291c5d7ab35c9b7bc7cf421472/spyder/plugins/ipythonconsole/plugin.py#L422
