### ISSUE TITLE
Spyder stuck or locked keys 

### ISSUE THREAD

**Issue by mez3252** [spyder-ide/spyder#12212]
### What steps will reproduce the problem?

I was working the other day and suddenly the spyder keys locked. For example, if I type “asdf” it is displayed withing the IDE as “aaaa”. If I press shift-“some new key”, it will switch to a new key but remain locked on that key. 

I’ve reinstalled Spyder and Anacada multiple times, taking care to remove any files associated with Anaconda. And tried older versions of spyder as well. 

I am using Windows 10 v1809 and Spyder 4.1.2 and windows remote desktop from my home Apple laptop. All other text editors are fine. I’m actually writing this message in word and copying it into the spyder Issue Reporter. My work’s IT support believes there might be a Spyder keyboard mapping file or config file that is missing. 

Any help on resolving this would be great. Thank you!

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.16 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
> I’ve reinstalled Spyder and Anacada multiple times, taking care to remove any files associated with Anaconda. And tried older versions of spyder as well.

This shows that the problem is not with Spyder. Perhaps a restart of the remote computer could help.

Sorry for not being more helpful.

**Comment by mez3252** [comment]
I restarted the computer multiple times as well. The issue does not resolve. Do you recommend reinstalling the OS?

**Comment by ccordoba12** [comment]
I couldn't say, sorry.
