### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by Nathanael1108** [spyder-ide/spyder#12213]
## Problem Description

Hello everyone. I'm encountering a problem when starting up Spyder and this for several months (October 2019). So I decided to open an issue today. I have already looked at the troubleshooting here: https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ and tested the "Emergency CPR: Spyder won't launch" part. I also want to point out that Jupyter Notebook and Anaconda Navigator won't start (so I can't do anything with them). When starting Jupyter Notebook, it opens and closes immediately and shows an error message. I tried the command ``conda update spyder`` in Anaconda Prompt but it displays an error as well. I have already uninstalled and reinstalled Anaconda several times and it always fails. 
I don't know what to do anymore... Thanks to the people who will be able to help me. 

### What steps reproduce the problem?

    1. installed Anaconda3 on my windows 10 (64 bits)
    2. launched Spyder in windows startup
    3. 'Spyder crashed during last session' came out

### What is the expected output? What do you see instead?

I was expecting Spyder to open after the 'initialization' appear. However I see an error message that says 'Spyder crashed during last session' and links to troubleshooting.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\github.py", line 51, in <module>
    from urllib2 import build_opener, HTTPSHandler, Request, HTTPError
ModuleNotFoundError: No module named 'urllib2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
    main.setup()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 908, in setup
    from spyder.plugins.console.plugin import Console
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\console\plugin.py", line 39, in <module>
    from spyder.widgets.reporterror import SpyderErrorDialog
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\reporterror.py", line 28, in <module>
    from spyder.widgets.github.backend import GithubBackend
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\github\backend.py", line 36, in <module>
    from spyder.utils.external import github
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\external\github.py", line 59, in <module>
    from urllib.request import build_opener, HTTPSHandler, HTTPError, Request
ImportError: cannot import name 'HTTPSHandler' from 'urllib.request' (C:\ProgramData\Anaconda3\lib\urllib\request.py)

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 - 64 bits

**Comment by ccordoba12** [comment]
Please install Anaconda for your user (instead of for all users in your computer) and try again. That could help.

**Comment by ccordoba12** [comment]
Also, what are the contents of this file?

    C:\ProgramData\Anaconda3\lib\urllib\request.py

**Comment by Nathanael1108** [comment]
Hello, thank you for your response. I'll try that and let you know. As for the file request.py, I opened it with Notepad ++ and it's a code written in python. Would you like me to share a copy of the code?

**Comment by Nathanael1108** [comment]
Hi, I just reinstalled Anaconda for this user only. The result is still the same.

**Comment by ccordoba12** [comment]
Yes, please upload that file here.

**Comment by Nathanael1108** [comment]
Okay, this is the file : https://pastebin.com/xjqNqK6y. Thanks for your help.

**Comment by rajiroseseirni** [comment]
![IMG-20200408-WA0029](https://user-images.githubusercontent.com/62426549/78811343-5a714380-79e7-11ea-9aac-e58f51c939c4.jpg)
This is my problem. How to fix this problem?

**Comment by Nathanael1108** [comment]
Hello, have you tried what was said (re-installing Anaconda) ? For me, it didn't work. Well, I hope it works for you. If it doesn't, be patient, like me.

**Comment by ccordoba12** [comment]
> Okay, this is the file : https://pastebin.com/xjqNqK6y. Thanks for your help.

This file has the right contents.

----

I'm really sorry but I don't what's happening in your case. Perhaps you have another Python installation in your system, old packages in `C:\Users\<your user>\AppData\Roaming\Python` or set the `PYTHONPATH` environment variable to some strange directory.

In any case, this is not really a Spyder problem but an installation one that is specific to your computer. So we can't help you further, sorry.

**Comment by Nathanael1108** [comment]
Thank you very much. I'll look into it and try to reinstall it in another hard drive eventually. Have a nice day!

**Comment by rajiroseseirni** [comment]
Ok.. thank you

**Comment by rajiroseseirni** [comment]
Ok. Thank you

**Comment by praveenkumar1980** [comment]
> > Okay, this is the file : https://pastebin.com/xjqNqK6y. Thanks for your help.
> 
> This file has the right contents.
> 
> I'm really sorry but I don't know what's happening in your case. Perhaps you have another Python installation in your system, old packages in `C:\Users\<your user>\AppData\Roaming\Python` or set the `PYTHONPATH` environment variable to some strange directory.
> 
> In any case, this is not really a Spyder problem but an installation one that is specific to your computer. So we can't help you further, sorry.

This is not one case . This is common on windows
