### ISSUE TITLE
Spyder doesn't use Native OS X fullscreen

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1221]
_From [alexchan...@gmail.com](https://code.google.com/u/112047091393661378494/) on 2013-01-09T18:18:00Z_

Spyder Version:  2.2.0dev
Python Version:  2.7.3
Qt Version:      4.7.4, PyQt4 (API v2) 4.9.4 on Darwin 

What steps will reproduce the problem?

1. Open Spyder.
2. It lacks a Fullscreen button (top-right corner of the window). What is the expected output? What do you see instead? Spyder should enable the OS-native fullscreen. 

Please provide any additional information below

. This behavior is common to Mac apps, and expected by users.
We'll have to look into how to do this through either PyQt or PyObjC.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1221_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-01-27T07:10:26Z_

This is already available for applications based on Qt5, see here: http://qt-project.org/forums/viewthread/14120/#85593 However Spyder is based on Qt4 and it doesn't seem possible to do it for this version. See for example this question, which went unanswered on stackoverflow: http://stackoverflow.com/q/13715190/438386

**Labels:** MS-v2.3 Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [alexchan...@gmail.com](https://code.google.com/u/112047091393661378494/) on 2013-02-03T19:34:47Z_

So can Spyder be updated to Qt5? Tests with qtperf suggest rendering is about 25% faster. Widgets may look better as well.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:50:55Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by ccordoba12** [comment]
Let's hope this is solved after the move to PyQt5.
