### ISSUE TITLE
The spyder somehow got stuck

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#12220]
## Problem Description

![image](https://user-images.githubusercontent.com/45376689/78765304-68f53600-79ba-11ea-9437-da02b84502f2.png)

### What steps reproduce the problem?

1.  The spyder gave this warning without warning
2. 
3. 

### What is the expected output? What do you see instead?

     How to solve this problem thoroughly, instead of restarting spyder again and again

## Versions

* Spyder version: 4.1.0
* Python version: 3.6.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: win10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This is fixed in 4.1.2. Please update.
