### ISSUE TITLE
Why is dictionary no longer work properly in Spyder?

### ISSUE THREAD

**Issue by BillLe2000** [spyder-ide/spyder#12226]
Hello,

In Spyder, I ran a piece of python code below:
mydict = { "A": 4, "B":5, "C":6, "D": 7}
print(mydict.keys())
I expected the output as below:
["A", "B", "C", "D"]
However, the output I received as below:
dict_keys(["A", "B", "C", "D"])
Can anyone know why? How do I fix this issue? Please help! 

Thank you a lot!
Ben

**Comment by goanpeca** [comment]
This is how python works. Newer versions of Python  return a dicts_keys object instead of a list.

Please read the documentation: 
https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects

**Comment by BillLe2000** [comment]
Hello Gonzalo,
Thank you so much for the information!
Ben Le
