### ISSUE TITLE
Plots Tab Disappeared

### ISSUE THREAD

**Issue by wladykam** [spyder-ide/spyder#12249]
I have the most updated version of both Spyder and the Anaconda Navigator. I had gotten familiar with navigating using the new plots pane by clicking on the plots tab. However, I had undocked my plots pane from Spyder and when I closed all my images, the tab just disappeared. I'm not sure how this happened and after searching around and looking through Spyder documentation, I don't know how to get it back. I've attached a picture of the portion of my Spyder IDE that used to contain the "Plots" tab, with a red circle around the 3 remaining tabs "Variable Explorer", "Help", and "Files" and as you can see "Plots" is now missing. I've tried the obvious things like restarting, updating both Anaconda and Spyder and going into preferences within the Spyder IDE, then "IPython Console" -> "Graphics" and then changing the Graphics backend configuration between Automatic and Inline. I should state that I am able to get plots to show, but they show up as detached PNG files with no option to redock them back into the Spyder IDE. I've also included a screenshot of one of those graphs. 

![image](https://user-images.githubusercontent.com/46423310/78921114-08b5d100-7a5a-11ea-8ba8-5874ad26cf07.png)

![image](https://user-images.githubusercontent.com/46423310/78921701-ec666400-7a5a-11ea-806b-01e9850778c8.png)

**Comment by ccordoba12** [comment]
All panes are present in the menu

    View > Panes

So please select "Plots" from it to show it again.
