### ISSUE TITLE
No further documentation available..

### ISSUE THREAD

**Issue by Ochitsuku** [spyder-ide/spyder#12254]
Spyder - Python 3.7 

Moving with the mouse over any library or code and pressing ctrl+i return is "no further documentation available"

![Capture1](https://user-images.githubusercontent.com/48127110/78946300-45b1b000-7aba-11ea-8540-1e290af5ebd3.PNG)

Expected Result:

![Capture2](https://user-images.githubusercontent.com/48127110/78946406-8c070f00-7aba-11ea-8e7b-b124f57b1d4f.PNG)

**Comment by ccordoba12** [comment]
That means that it can't be retrieved from the editor, sorry.

**Comment by Ochitsuku** [comment]
> That means that it can't be retrieved from the editor, sorry.

Hmm, why does it work then for the instrcutor?

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @Ochitsuku could you please provide the version of Spyder that you guys are using? You can check it in the `Help > About Spyder...` menu. 

Also, seems like you are using Kite (which should be able to get the docs of the `Imputer` class). Could you run Spyder from the Anaconda Prompt with `spyder --debug-info verbose` and post here the generated log please, and also check if the Kite Copilot show any message regarding the connection with Spyder? Any new info to understand and reproduce this is greatly appreciated :)

**Comment by dalthviz** [comment]
Note: Testing with only the LSP and Spyder 4.1.2 I'm unable to get help docs for the `Imputer` class, although I can get help for the `sklearn` and `sklearn.preprocessing`:

![help](https://user-images.githubusercontent.com/16781833/78958740-9d4a1e80-7aae-11ea-936e-233434976aa8.gif)

**Comment by Ochitsuku** [comment]
@dalthviz Im using spyder via anaconda and its the 4.0.1 Version.

**Comment by ccordoba12** [comment]
> Note: Testing with only the LSP and Spyder 4.1.2 I'm unable to get help docs for the Imputer class, although I can get help for the sklearn and sklearn.preprocessing

@dalthviz, could you review if this a problem with Jedi or the PyLS?

**Comment by dalthviz** [comment]
>@dalthviz Im using spyder via anaconda and its the 4.0.1 Version.

@Ochitsuku please update to Spyder 4.1.2 to check if that allows you to get documentation (while having Kite enabled).

>@dalthviz, could you review if this a problem with Jedi or the PyLS?

@ccordoba12 seems like that´s the case (tested with Jedi 0.15.2):

* Empty definitions for `Imputer`:

![image](https://user-images.githubusercontent.com/16781833/79138431-1df06f80-7d7a-11ea-9586-dbe25035808b.png)

* A definition is retrieved for `sklearn`:

![image](https://user-images.githubusercontent.com/16781833/79138888-ea621500-7d7a-11ea-86e3-52235d1c7320.png)

**Comment by ccordoba12** [comment]
Ok, thanks @dalthviz! Please try with Jedi 0.17 to see if that version can retrieve a definition.

**Comment by dalthviz** [comment]
@ccordoba12 testing with Jedi 0.17.0 (master) it doesn't work either:

![image](https://user-images.githubusercontent.com/16781833/79147832-349ec280-7d8a-11ea-86c7-506428036dc6.png)

**Comment by ccordoba12** [comment]
Ok, thanks @dalthviz.

@Ochitsuku, it seems newer versions of the libraries we use to extract documentation are unable to do that for Imputer. So unless you install and use Kite, there's nothing we can do about this, sorry.

**Comment by Ochitsuku** [comment]
@dalthviz as I am using anaconda, I am unable as far my awareness goes to update to the 4.1 version. As anaconda has not released that yet

**Comment by dalthviz** [comment]
@Ochitsuku I think Spyder 4.1.2 is already available through Anaconda. Could you try to update using `conda install spyder=4.1.2` ?

**Comment by ccordoba12** [comment]
@Ochitsuku, if that doesn't work or it gives an error, you need to run first

    conda update anaconda

**Comment by Ochitsuku** [comment]
Unfortunately I am getting an unexpected error when trying to do that. @dalthviz

**Comment by Ochitsuku** [comment]
@ccordoba12 @dalthviz thanks this works now with the imputer class. Is it also supposed to provide information with for example import? As this doesn't give a response.

**Comment by dalthviz** [comment]
I think you don't get docs for stuff like `import` but I'm not totally sure @Ochitsuku

**Comment by Ochitsuku** [comment]
@dalthviz alright, no problem. Was just a curiosity question. Thanks again for the great help here! I appreciate and love the docs feature btw!

**Comment by liweiyiw** [comment]
I just did the conda update anaconda and  it's Spyder 4.1.3 now. 
It still show 'No further documentation available' when CTRL +I on the editor

**Comment by dalthviz** [comment]
Hi @liweiyiw as described in the [comment above](https://github.com/spyder-ide/spyder/issues/12254#issuecomment-613065110) for some objects (including `Imputer` but probably no limiting just to it) the libraries we use don't provide further documentation. For the moment you could try installing Kite to check if Spyder is able to show further documentation :)

**Comment by vnum** [comment]
Imputer is deprecated.
Try this: `from sklearn.impute import SimpleImputer`
