### ISSUE TITLE
[Debugger] NameError: name is not defined (but it is)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12257]
Has been happening since 4.0.0 (now 4.1.2): variable names clearly defined are reported undefined:

![image](https://user-images.githubusercontent.com/16495490/78956282-db693180-7af2-11ea-930c-88bd09a394bd.png)

Don't know how to minimally reproduce, behavior is intermittent.

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder-kernels/pull/212 should fix most issues related to local variables.

In this example however, `values_per_key` and `plot_kws` are correctly identified as being not defined. If you want to see them, you have to go `up` in the frame inside of the function `_unpack_plot-kws`. 

The important think to understand is that list comprehensions creates a new frame. In the same way, if I have:
```
def a():
    i = 1
def b():
    j = 3
    a()
```
and put a breakpoint at `i = 1`, the frame in `a()` won't have `j` defined.

**Comment by OverLordGoldDragon** [comment]
Ah, thanks for explaining. Another issue, however - almost any (or any) variable inside `list()` becomes undefined, whether from running code or declared straight in debugger:

<img src="https://user-images.githubusercontent.com/16495490/79026880-40786200-7b9b-11ea-8423-a57e6135d38f.png" width="200">

yet works fine in a list comprehension:

<img src="https://user-images.githubusercontent.com/16495490/79026938-669e0200-7b9b-11ea-87e4-9026712be6bd.png" width="200">

Should I open a new issue, or am I missing something again?

**Comment by impact27** [comment]
`list` is a pdb command (https://docs.python.org/3.8/library/pdb.html#pdbcommand-list)

If you run code in pdb, it will first try to interpret that as a command, and if that fails it will interpret that as code. For example:
```
ipdb> a = 1

ipdb> a

ipdb> 
```
Won't create a new variable named `a` because `a(ll)` is a pdb command. To indicate you have code, add `!`:
```
ipdb> !x = (1, 2)

ipdb> !list(x)
[1, 2]

ipdb> 
```

**Comment by OverLordGoldDragon** [comment]
Lots of subtleties - that clears it, thank you.

**Comment by ccordoba12** [comment]
> Lots of subtleties - that clears it, thank you.

I'm sure these things are causing troubles for a lot of people. So our plan for Spyder 5 is to redefine Pdb commands as magics (e.g. `%list` instead of `list`) to avoid this kind of confusions.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Sound idea, this way 'regular' commands will run directly, and 'special' commands will use special prefixes.

**Comment by ccordoba12** [comment]
> Sound idea, this way 'regular' commands will run directly, and 'special' commands will use special prefixes.

Exactly!! That's the great behind the IPython magics system (i.e. to have a namespace for special commands separate from regular code) and what it makes it so powerful. We just need to extend that idea to Pdb commands.

**Comment by impact27** [comment]
> > Lots of subtleties - that clears it, thank you.
> 
> I'm sure these things are causing troubles for a lot of people. So our plan for Spyder 5 is to redefine Pdb commands as magics (e.g. `%list` instead of `list`) to avoid this kind of confusions.

I think that this would be a good idea but I think "%" should be kept for ipython magics. Using the same symbol would confuse the users.

**Comment by OverLordGoldDragon** [comment]
@impact27 Agreed, another symbol should do
