### ISSUE TITLE
The close of the Spyder data viewing window and full screen under macOS

### ISSUE THREAD

**Issue by p5ydn0** [spyder-ide/spyder#12258]
## Problem Description
When I use Spyder to generate a Dataframe data and double-click the data object in the variable console to view the Dataframe:

1. I can't close the Dataframe window with command + W shortcut;
2. After I maximize the window:
    * Pressing the Esc key will directly close the window instead of making the window to the size before it is maximized;
    * When I press Esc to close the window, there will be a short "full screen black screen" after the window disappears, and then return to the previous desktop.

3. Every time the Dataframe data window is maximized and the Esc key is pressed to close the window, a new "all black" desktop will be created (not by pressing the maximize key). like this：

![image](https://user-images.githubusercontent.com/25891214/78956821-1c267200-7b16-11ea-8b00-470c43bd3a91.png)

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.3
* Qt version: 
* PyQt version: 1.7.1
* Operating System name/version: macOS 10.15.4

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.1.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.5.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.2 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.7.1 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.1.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.10 (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  0.24.2 (OK)
scipy >=0.17.0                 :  1.2.1 (OK)
sympy >=0.7.3                  :  1.4 (OK)
```

**Comment by ccordoba12** [comment]
This seems very specific to the way macOS handles windows, so there's little we can do about it, sorry.

**Comment by benji972** [comment]
Same for me - Same configuration :-(
