### ISSUE TITLE
redundancy in keyboard shortcuts

### ISSUE THREAD

**Issue by aleksejsk** [spyder-ide/spyder#12268]
is it possible to have redundancy in keyboard shortcuts? (i.e. use more than one shortcut for a specific Spyder command)

**Comment by jnsebgosselin** [comment]
No yet. We are working on it though. Please see https://github.com/spyder-ide/spyder/pull/11694.

**Comment by ccordoba12** [comment]
Let's close this one as a duplicate of the issues that PR solves.
