### ISSUE TITLE
Check kite install on CI

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#12272]
After moving to github actions that test was skipped. Check why it was failing and try to reenabled it.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one for 4.1.3

**Comment by dalthviz** [comment]
Note: The Kite install is failing since Kite tries to add and enable a service to update it self. The installation fails with a `Failed to connect to bus: No such file or directory` message

**Comment by ccordoba12** [comment]
Perhaps you need to activate the dbus service for that to work?

**Comment by dalthviz** [comment]
Seems like the problem is related with running `systemctl` at user level. Kite adds the update service at user level (which I think was mentioned [here](https://github.com/spyder-ide/spyder/issues/11880#issuecomment-606829866)) but the install process can't enable it.
