### ISSUE TITLE
Entries are not visible in completion widget when using the light theme

### ISSUE THREAD

**Issue by lee-grand** [spyder-ide/spyder#12278]
![color_problem](https://user-images.githubusercontent.com/63506999/79047359-9d106700-7c05-11ea-96a7-c4af6e78e526.png)
Problem:
In light theme, when autocomplete popups with selection of choices, currently selected option has non-inverted font color, so it is not possible to see the text of selected option. As selection color is dark and font is dark too.

Steps reproduce the problem

1. Interface of Windows 7 is set to classical, and selection color is set to dark (blue, black...)
2. Spyder 4.1.2 interface theme is set to light.
3. When autocomplete window appears any selected element will be with dark font and dark background so it is not possible to see what is the text under selection.

Expected output

Font color is inverted under selection of popup autocomplete.

Spyder version: 4.1.2
Python version: 3.7.7
Qt version: 5.9.6
PyQt version: 5.9.2
Operating System name/version: Windows 7 Pro

**Comment by goanpeca** [comment]
Indeed I can reproduce this on mac as well. We need to update the color of the text based on the currently selected item.

**Comment by ccordoba12** [comment]
@juanis2112, this is one is for you.

**Comment by RichardShea** [comment]
I'm have the same issue.  The color appears to be dependent on the (mac) accent color setting.
System Preferences > General > Highlight color.

<img width="232" alt="Screen Shot 2020-12-13 at 6 04 45 PM" src="https://user-images.githubusercontent.com/51180538/102026836-37651380-3d6e-11eb-8b3a-134e2114d668.png">

<img width="402" alt="Screen Shot 2020-12-13 at 6 07 12 PM" src="https://user-images.githubusercontent.com/51180538/102026813-13093700-3d6e-11eb-8162-d00229db0117.png">

Hope this helps, but I think Spyder should let us choose the colors.

**Comment by ccordoba12** [comment]
This no longer applies because we have a light theme independent from the OS one.
