### ISSUE TITLE
Spyder not Launching from anaconda navigator 

### ISSUE THREAD

**Issue by kiranraviprakash** [spyder-ide/spyder#12307]
I have installed a virtual environment. But spyder, jupiter notebooks or any other ide is not getting launched in that specific virtual environment in the anaconda navigator. Spyder is launching from the base(root) environment. 
I reinstalled spyder, did reset spyder but no positive results. No error also being displayed. 

![image](https://user-images.githubusercontent.com/54947278/79140059-a5d37b00-7d74-11ea-8540-89bf66c696d4.png)

**Comment by goanpeca** [comment]
Please report at https://github.com/ContinuumIO/anaconda-issues/issues/
