### ISSUE TITLE
Spyder 4.1.2 for python3 doesn't launch on Linux

### ISSUE THREAD

**Issue by lgmventura** [spyder-ide/spyder#12303]
## Problem Description
Spyder 3 worked fine. Since upgrade to Spyder 4, it doesn't work anymore after multiple reinstallations both locally and in standard `/usr/local/lib/`.

### What steps reproduce the problem?

1. Install Spyder with `sudo pip3 install -U spyder3`
2. Downgrade PyQt5 to 5.10.1 with `pip install PyQt5==5.10.1`, since it doesn't work with the newest version (https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe).
3. Run Spyder with `spyder3`.

### What is the expected output? What do you see instead?
Expected Spyder to launch. Instead, it crashes before it opens.

### Traceback/Error from terminal:
```

/usr/local/lib/python3.6/dist-packages/qtpy/__init__.py:211: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyqt"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
Traceback (most recent call last):
  File "/usr/local/bin/spyder3", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/spyder/app/start.py", line 200, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python3.6/dist-packages/spyder/app/mainwindow.py", line 53, in <module>
    requirements.check_qt()
  File "/usr/local/lib/python3.6/dist-packages/spyder/requirements.py", line 42, in check_qt
    package_name, required_ver = qt_infos[qtpy.API]
KeyError: 'pyqt'

```

## Versions

* Spyder version: 4.1.2
* Python version: 3.6.9
* Qt version: 5.9.5
* PyQt version: 5.
* Operating System name/version: Ubuntu 18.04

### Dependencies
Can't run Spyder to check this.

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by mczakk** [comment]
HI @ccordoba12, I read this post with interest as i can't seem to get spyder 4 to work on my linux machine. I am also having issues getting anaconda to work as detailed here : [https://github.com/conda/conda/issues/10103](url)
i appreciate that using conda is the preferred method, but how am i supposed to do tha if conda doesnt work?

**Comment by ccordoba12** [comment]
@mczakk, I left you a comment in conda/conda#10103. Hope that helps.
