### ISSUE TITLE
Play Audio track in Spyder

### ISSUE THREAD

**Issue by Mustafa-SportScience** [spyder-ide/spyder#12319]
### What steps will reproduce the problem?

Is there any way to use the IPython.display library for the Audio class to show the audio-player interface and play the audio track in Spyder by using this library?
This library works well in Jupyter Notebook but it doesn't funct in Spyder.

I tried this code, which works perfet in Jupyter Notebook but not in Spyder.

import scipy.io.wavfile
fs, bc = scipy.io.wavfile.read("filename.wav")

from IPython.display import Audio
Audio(np.array(bc[:,0]), rate=fs)  

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.9 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.2 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.4 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by bcolsen** [comment]
IPython.display Audio only support the Jupyter notebook not the qtconsole that Spyder uses by default. You can try the spyder-notebook plug-in. 

Also here are some other possibilities to look into:
https://realpython.com/playing-and-recording-sound-python/
https://pythonbasics.org/python-play-sound/

**Comment by Baytars** [comment]
@bcolsen  Which IPython.display objects has Spyder qtconsole supported so far?

**Comment by bcolsen** [comment]
Tables, Images and Latex Math it seems

https://github.com/jupyter/qtconsole/blob/e018066eb12c2d93c1a73e305e55ee3396fb8401/qtconsole/rich_jupyter_widget.py

**Comment by Baytars** [comment]
> Tables, Images and Latex Math it seems
> 
> https://github.com/jupyter/qtconsole/blob/e018066eb12c2d93c1a73e305e55ee3396fb8401/qtconsole/rich_jupyter_widget.py

Thanks for the information. Hope more objects are supported in the future.

**Comment by Dexter-Wang** [comment]
pip install playsound==1.2.2

from playsound import playsound    
playsound(file path of ".wav" or ".mp3")

**Comment by Dexter-Wang** [comment]
another way,

import pygame
pygame.mixer.init()

sound = pygame.mixer.Soundfile path of ".wav" or ".mp3")          
sound.play()

**Comment by Dexter-Wang** [comment]
this is also good for some application,

import soundfile as sf
import sounddevice as sd

def PlayAudio(speech_dict) :  
    #--- save to io.BytesIO() ------
    virtual_file = io.BytesIO()
    sf.write(
          virtual_file, 
          speech_dict['audio'],   
          samplerate=speech_dict['sampling_rate'], 
          format='wav'
    )        
    
   #--- Read audio data & play the audio using sounddevice ----
   virtual_file.seek(0)
    with sf.SoundFile(virtual_file) as sound:
        audio_data  = sound.read(dtype='float32') 
        sample_rate = sound.samplerate              
        sd.play(audio_data, samplerate=sample_rate)
