### ISSUE TITLE
run current cell not working

### ISSUE THREAD

**Issue by mrazagit** [spyder-ide/spyder#12323]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Spyder Version 4.1.2 installed through Anaconda
Run current cell button is not working...instead its running the whole file.
Also throwing ModuleNotFoundError, for pandas and numpy etc...which are vital and already installed.

**Comment by bcolsen** [comment]
@mrazagit This isn't enough information to solve the problem. Do you have some code that you can share that shows the problem?

**Comment by mrazagit** [comment]
![image](https://user-images.githubusercontent.com/45151184/79360457-61570380-7f5d-11ea-9cee-27f8081b506a.png)
This is a snippet from code, it's not importing pandas, and also when I press the runcell button... it tries to execute the who file, instead of running the selected lines of code.

**Comment by ccordoba12** [comment]
See my answer in #12339 (I think you have the same problem as the user that reported that issue).

And about the pandas import error: please read our guide

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to understand how to fix it.
