### ISSUE TITLE
Hey I want to know how to get the plots in the ipython console 

### ISSUE THREAD

**Issue by ajaykumar-br** [spyder-ide/spyder#12322]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by bcolsen** [comment]
@ajaykumar-br Find the "plots" pane(the tab beside the "Files" and "variable explorer"). In the "plots" pane there is an options menu (a square button with three horizontal lines). In that menu uncheck "mute inline plotting".

@jnsebgosselin What are your thoughts about making a separate "graphics backend" for the plots pane, like a "plots pane" backend. Currently when users pick "inline" they don't actually get "inline" plots like the name would suggest.  We can still keep the "mute" option in the plots pane to show both.

**Comment by jnsebgosselin** [comment]
> @jnsebgosselin What are your thoughts about making a separate "graphics backend" for the plots pane, like a "plots pane" backend. Currently when users pick "inline" they don't actually get "inline" plots like the name would suggest. We can still keep the "mute" option in the plots pane to show both.

Maybe this option should be moved to the IPython console instead. We could also add the option in the preferences at `Preferences > IPython console > Inline backend`

**Comment by ccordoba12** [comment]
Give the importance of switching between Inline and Automatic, I think we should add a new entry to the Plots options menu to control that (the IPython console one is already too crowded).

**Comment by bcolsen** [comment]
>Give the importance of switching between Inline and Automatic, I think we should add a new entry to the Plots options menu to control that (the IPython console one is already too crowded).

Unless I'm missing a resent change, I still need to restart the kernel to change between the switching between "inline" and  "Automatic". Having a quick access feature in the plots tab that requires a kernel restart could be pretty confusing. 

One possible change to the preferences dialogue to simplify the choice would be to have a radio button choice between having "interactive plots in a separate window" and "image plots thin the plots pane or console" the interactive plots would activate the selection for a backend and the image plots option would activate the image settings(which only apply to the inline backend if I'm not mistaken).

Excuse my horrible mock up:
![plotting prefences](https://user-images.githubusercontent.com/10513354/79363988-e6163300-7f05-11ea-89c1-154e806b982c.png)

**Comment by ajaykumar-br** [comment]
understood the working
