### ISSUE TITLE
Unable to launch Anaconda Navigator or Spyder (Windows 10/64-bit)

### ISSUE THREAD

**Issue by ResearchLabDev** [spyder-ide/spyder#12327]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Unable to launch Anaconda Navigator (anaconda3) or Spyder on a 64-bit Windows 10 machine . I have reviewed several reports of this issue, however, the fixes (e.g., update conda, reinstall PyQt) have not resolved my issue.

### What steps reproduce the problem?

1. Clicked Anaconda Navigator and Spyder shortcuts, neither will launch desired program.
2. Attempted to load Anaconda Navigator and Spyder via command prompt, but still no launch.

### What is the expected output? What do you see instead?

I was expecting either Anaconda Navigator and Spyder to launch.  However, neither were able to. The below Traceback is from when I tried to launch Anaconda Navigator via the command prompt.

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Users\Admin\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Users\Admin\anaconda3\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Users\Admin\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Microsoft Windows 10 Home/64-bit

### Dependencies

```
dependencies:
    atomicwrites >=1.2.0
    chardet >=2.0.0
    cloudpickle >=0.5.0
    diff-match-patch >=20181111
    intervaltree
    jedi 0.15.2.*
    keyring
    nbconvert >=4.0
    numpydoc >=0.6.0
    paramiko >=2.4.0
    parso 0.5.2.*
    pexpect >=4.4.0
    pickleshare >=0.4
    psutil >=5.3
    pygments >=2.0
    pylint >=0.25
    pyqt >=5.6,<5.13
    python >=3.8,<3.9.0a0
    python-language-server >=0.31.9,<0.32.0
    pyzmq >=17
    qdarkstyle >=2.8
    qtawesome >=0.5.7
    qtconsole >=4.6.0
    qtpy >=1.5.0
    rtree >=0.8.3
    sphinx >=0.6.6
    spyder-kernels >=1.9.0,<1.10.0
    watchdog
```
Thank you for the assistance.

**Comment by ccordoba12** [comment]
I'm sorry but this is an installation issue and not a problem with Spyder itself. The only advice we can give you is to remove and reinstall Anaconda.

If that doesn't work, please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/
