### ISSUE TITLE
Spyder fails to upgrade

### ISSUE THREAD

**Issue by Zechariah2020** [spyder-ide/spyder#12335]
Hello.
I'm using the latest version of Anaconda 3 and Spyder 4.0.1 is installed on it by default and I want to upgrade Spyder to the latest version (4.1.2). When I try to upgrade it by the command (conda install spyder=4.1.2) it fails.
What should I do?

**Comment by jitseniesen** [comment]
What do you mean with it fails? How? If there is an error message, please copy it.

**Comment by ccordoba12** [comment]
You need to run first

    conda update anaconda

if you are on Windows.
