### ISSUE TITLE
runcell is not working

### ISSUE THREAD

**Issue by malponur** [spyder-ide/spyder#12339]
Runcell is not working for me. When I click shift and enter also ctrl and enter it doesnt copy to the console

Code
```
#%%
#built in functions 

str1 = 'deneme'

float1 = 10.6
#float(10)
#int(float1)
#round(float1)

str2 = '1881'
#int(str2)
#%%

```

* Spyder version: 4.1
* Python version: 3.7
MacbookPro 10.15.4 Catalina

![image](https://user-images.githubusercontent.com/58391418/79366111-47fd8980-7f54-11ea-8810-222c57cf61e8.png)

**Comment by ccordoba12** [comment]
You're not printing anything in your cells. Therefore, you're not getting any result after running them (which is the expected result).

If you want to have the behavior in Spyder 3, you need to go to the menu

    Tools > Preferences > Editor > Run code

and activate the option called "Copy full cell contents to the console when running code cells".

**Comment by malponur** [comment]
Solved. Thank you so much
