### ISSUE TITLE
No kernel connection without error

### ISSUE THREAD

**Issue by trixxx3** [spyder-ide/spyder#12353]
## Problem Description

Since i didnt updated anaconda a while i started anaconda prompt and did so.
   conda update anaconda

First Spyder runned normally, but suddenly ther kernel does not connect anymore and does not produce an error. Reinstalling Anaconda or Downgrading Spyder does not work either. After Reinstalling Anaconda Kite request does not show up either (whyever).  It would be really nice if there is any solution.

best regards
Lukas

### What steps reproduce the problem?

1. spyder  --reset
2. reinstalling anaconda
3. downgrading Spyder
4. Starting Spyder from inside Anaconda Nav, Start Menue Link or Anaconda Prompt, Anaconda Powershell. Spyder starts and looks like a bright version

What worked was starting spyder from Anaconda Powershell (from outside anaconda) with
    start spyder
Spyder starts here in a dark version and the kernel quickly connects

### Paste Traceback/Error Below (if applicable)
no errors

## Versions

* Spyder version: 4.1.2
* Spyder-kernels version: 1.9.0
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Win10

### Dependencies

 # Mandatory:
 atomicwrites >=1.2.0           :  1.3.0 (OK)
 chardet >=2.0.0                :  3.0.4 (OK)
 cloudpickle >=0.5.0            :  1.3.0 (OK)
 diff_match_patch >=20181111    :  20181111 (OK)
 intervaltree                   :  None (OK)
 IPython >=4.0                  :  7.13.0 (OK)
 jedi =0.15.2                   :  0.15.2 (OK) 
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

**Comment by trixxx3** [comment]
Found the Propblem but still unsatisfied with the solution:

As long as i start the programs as admin the kernel works at spyder appears in dark theme
elseway it is not working and in brigth scheme.

It was not like this before. So where is the reason for this behavior now.

**Comment by ccordoba12** [comment]
This looks like a problem with your installation not with Spyder. So I'd suggest you to remove and reinstall Anaconda again.

**Comment by ccordoba12** [comment]
That's the only advice we have for you.

**Comment by trixxx3** [comment]
Thats is what i did already 5 times

**Comment by ccordoba12** [comment]
Then you probably installed Spyder with pip at some point and that's interfering with Anaconda. You need to find if you have Python files in your computer outside Anaconda and not being created by you, and remove them

**Comment by trixxx3** [comment]
like which files?

**Comment by ccordoba12** [comment]
The ones in

    C:\Users\<your user>\AppData\Roaming\Python\

**Comment by trixxx3** [comment]
perfect. helped. thanx a lot
