### ISSUE TITLE
Spyder throws the Error "An error ocurred while starting the kernel"

### ISSUE THREAD

**Issue by shubham4576** [spyder-ide/spyder#12369]
## Problem Description
After running this code - 
**import cv2

cap = cv2.VideoCapture("output.avi")

print(cap.isOpened())
while(cap.isOpened()):
    ret, frame = cap.read()
    
    
    cap.get(cv2.CAP_PROP_FRAME_WIDTH)
    cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
    cap.get(cv2.CAP_PROP_FRAME_COUNT)
    
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    cv2.imshow('frame',gray)
    
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()
**
I am getting this error. And now if i run any code it gives this error. 

### What is the expected output? What do you see instead?

> An error ocurred while starting the kernel
> [ WARN:1] global C:\projects\opencv‑python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
> [ WARN:2] global C:\projects\opencv‑python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
> [ WARN:3] global C:\projects\opencv‑python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
> [ WARN:4] global C:\projects\opencv‑python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
> [ WARN:0] global C:\projects\opencv‑python\opencv\modules\videoio\src\cap_msmf.cpp (674) SourceReaderCB::~SourceReaderCB terminating async callback
> [ERROR:0] global C:\projects\opencv‑python\opencv\modules\videoio\src\cap.cpp (116) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:
> 
> OpenCV(4.2.0) C:\projects\opencv‑python\opencv\modules\videoio\src\cap_images.cpp:253: error: (𔂯:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): output.avi in function 'cv::icvExtractPattern'
> 

## Versions

* Spyder version:  4.0.1
* Python version: 3.7.6 64-bit
* Qt version: 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

```
**_I don't know how to solve this problem. Please help guys._**

**Comment by ccordoba12** [comment]
This is an installation issue with OpenCV, so there's nothing we can do about it, sorry.

Besides, if you're not using Anaconda, we highly recommend you to do it.
