### ISSUE TITLE
Unable to import rdflib

### ISSUE THREAD

**Issue by tweezer69** [spyder-ide/spyder#12371]
### Issue Report Checklist

* [* ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [* ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ *] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [* ] Reset preferences with ``spyder --reset``
    * [ *] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [* ] Tried the other applicable steps from the Troubleshooting Guide
* [* ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. import rdflib
2. pip install rdflib
3. pip install pickle

### What is the expected output? What do you see instead?
I expect to browse the semantic web using the rdflib library in Python,yet even after using import rdflib and the pip install commands, I still receive the error message: "ModuleNotFoundError: No module named 'rdflib'"

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please read our guide

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to understand how to solve this kind of problems.
