### ISSUE TITLE
Wrong Invalid Syntax (pyflakes E) Report and Failure of the Linter

### ISSUE THREAD

**Issue by deathes** [spyder-ide/spyder#12383]
This is a known error but we still don't understand why it's happening. Thanks for reporting.

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/12275#issuecomment-612461608_

Since the other issue that was posted from someone else is closed, here's why it happens.

It's happening because of the jedi package. For some reason jedi 0.15.2 version causes a problem. I couldn't test 0.16.0 or 0.17.0 because python language server doesn't work with them . It requires 0.16 - 0.14.1. Funnily, it would work if the jedi package's version was 0.16 instead of 0.16.0.

There are two workarounds at the moment.

Preferred Workaround 1: Revert back to jedi 0.15.1. Spyder will give a warning but it's fine.
Warning-Free Workaround 2: Revert back to Spyder 4.1.0 (which reverts the jedi to 0.14.1) and start spyder up from prompt because that version has a bug that prevents ipython kernel startup if you launch spyder from a shortcut.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to update to a newer Jedi version in a month or so.
