### ISSUE TITLE
Jupyterlab support of spyder.

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#12394]
Hi,

Can spyder support Jupyterlab now?

Regards

**Comment by goanpeca** [comment]
@hongyi-zhao what do you mean by

>Can spyder support Jupyterlab now?
?

If you are asking about notebook support you, please refer to https://github.com/spyder-ide/spyder-notebook/

**Comment by hongyi-zhao** [comment]
I mean the supporting for https://github.com/jupyterlab/jupyterlab from within spyder.

Regards

**Comment by goanpeca** [comment]
>I mean the supporting for https://github.com/jupyterlab/jupyterlab from within spyder.

No, we will support the Notebook component of jupyterlab, not the entire jupyterlab. Fot that you should use JupyterLab itself 🤷

**Comment by ccordoba12** [comment]
Agreed. If you want JupyterLab, then please use JupyterLab. It doesn't make sense to me to embed JupyterLab inside Spyder just for the sake of embedding it.
