### ISSUE TITLE
Blank window when I open Spyder

### ISSUE THREAD

**Issue by craigmau** [spyder-ide/spyder#12390]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Blank window when I open Spyder.

### What steps reproduce the problem?

1. View
2. Windows Layout
3. Stwich layout

### What is the expected output? What do you see instead?
I tried to switch the layout, but it become blank window. 
Then I tried to uninstall and reinstall Anaconda and Spyder, the issue was not resolved. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 
* PyQt version: 
* Operating System name/version: MACOS 10.14.6

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by craigmau** [comment]
![Screenshot 2020-04-18 23 28 41](https://user-images.githubusercontent.com/13712407/79678798-0e838300-81cd-11ea-8743-710337cb7d7f.png)

**Comment by ccordoba12** [comment]
Please close Spyder, open Terminal.app, run there

    spyder --reset

and try again.

**Comment by craigmau** [comment]
Fixed. Thanks!
