### ISSUE TITLE
color theme

### ISSUE THREAD

**Issue by githiakalaban** [spyder-ide/spyder#12402]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
please would you provide user  preferences theme,like one can change,coz i liked the dark gray theme now i get a white theme which is so bright 

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: upto date
* Python version:  upto date
* Qt version:  upto date
* PyQt version:  upto date
* Operating System name/version: linux

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @githiakalaban sorry for such a late response, not totally sure but, just in case, to choose the theme (if your installed Spyder version supports it) you can go to `Tools > Preferences > Appearence > Main interface > Interface theme` and select `Dark`.

I'm closing this one but let us know if the above helps!
