### ISSUE TITLE
Cursor very Laggy for 4.1.1 and 4.1.2

### ISSUE THREAD

**Issue by EnderWiggin14** [spyder-ide/spyder#12411]
### What steps will reproduce the problem?

I'm running Windows 10. I just installed tensorflow 1.15. I performed "conda install spyder." I was running spyder 4.1.1. I didn't realize that this wasn't the correct operation to upgrade to 4.1.2. I tried typing in the editor and moving the cursor with my arrow keys. The cursor movement and text appearance was very laggy. The lag was on the order of .5-1.0 seconds.

I then installed 4.1.2 via "conda install spyder=4.1.2" which completed and was laggy. I have reverted to back 4.1.1 and am still seeing plenty of lag.

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.3.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by EnderWiggin14** [comment]
Note: The cursor movement works fine immediately after startup, but once typing begins, the problem starts for both typing and cursor movement. The problem persists (possibly indefinitely) until program restart.

**Comment by ccordoba12** [comment]
This looks like an installation issue. Please reinstall Anaconda or install Spyder in a conda env and try again.

**Comment by EnderWiggin14** [comment]
I did reinstall everything multiple times. I must correct that I wasn't
previously using 4.1.1. I was using 4.0.1. I didn't remember the version
number and didn't realize there were 3 new pushes in a one month span
during March. 4.1.1 doesn't work properly either. I didn't try 4.1.0.

I rolled back to 4.0.1. During this process I noticed that the Jedi and
Parso dependency versions changed. 4.0.1 works just fine on my computer. My
guess is something in Spyder's implementation of Jedi and/or Parso or those
packages has changed in such a way that they are poorly optimized or just
don't work well on older computers. It could also be something unrelated to
Jedi and Parso, but something in Spyder itself. Installation errors aren't
the problem. My computer is old, but it's capable of handling 4.0.1

Currently Installed:
Jedi = 0.14.1-37_0
Parso = 0.5.2-py_0

**Comment by ccordoba12** [comment]
No one else has reported this problem, so then I guess (as you said) probably your computer is unable to handle newer versions of Jedi and/or Parso.

**Comment by EnderWiggin14** [comment]
what it sounds like to me is that you don't want to fix a clear problem.

**Comment by ccordoba12** [comment]
You're not giving us any information to do that. I don't know how handy you're with git, but you could use `git bisect` between 4.0.1 and 4.1.0 to detect the exact commit that introduced the problem. You also need to be aware that at some points in the history you'll probably need to have the right version of spyder-kernels for Spyder to run correctly.

Other than that, it's impossible for us to help you because we don't have the means to reproduce this problem.

**Comment by EnderWiggin14** [comment]
That is a far more useful response for me, thank you. I am familiar with
git, but by no means a power user. It's certainly something I can figure
out though.

Also, I pip installed Jedi 0.16.0 and Parso 0.6.2, the dependencies of
spyder 4.1.2. I ran 4.0.1 with the updated packages and it didn't reproduce
the problems of 4.1.2. There is still no lag in spyder 4.0.1. I'm not sure
if that tells you anything.

It very well may be my older computer, but it probably means that there is
something that isn't optimized as well as it could be. Newer computers
might be powerful enough to make the lag unnoticeable, but that doesn't
mean that performance isn't suffering.
