### ISSUE TITLE
Where is the config file for spyder when I run it from the local git repo?

### ISSUE THREAD

**Issue by hongyi-zhao** [spyder-ide/spyder#12420]
Hi,

I run spyder directly using the local git repo and then do some settings with `Tools --> Preferences `.
Where is the config file used by spyder to save the above settings?

Regards

**Comment by ccordoba12** [comment]
Windows/macOS: it's in `~/.spyder-py3-dev`, where `~` is your Users directory.

Linux: It's in `~/.config/spyder-py3-dev`
