### ISSUE TITLE
Typing in Editor Lagging

### ISSUE THREAD

**Issue by EnderWiggin14** [spyder-ide/spyder#12428]
### What steps will reproduce the problem?

My previous report was prematurely closed by the mods. I was told that it was an install problem. I uninstalled Anaconda and reinstalled Anaconda and installed spyder via "conda install spyder=4.1.2". The lag is far better than before, but it's not how it was, before I had previously performed any updates, while using spyder 4.1.1.

EDIT: Correction, it's almost as bad as it was prior to re-installation of Anaconda and Spyder.
Also, to provide how I got this happen. I uninstalled Anaconda. I re-installed Anaconda. I ran "conda install spyder=4.1.2" in powershell. I started Spyder. Prior to any typing, cursor movement is fine. Once typing begins, cursor movement begins to lag and appearance of typed letters also lags by varying amounts. I'm not running Kite. I'm not using the outline pane. The problem occurs whether code completion is active or inactive. 

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.2.1 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  0.6.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.2.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.4.0 (OK)
numpydoc >=0.6.0               :  0.8.0 (OK)
paramiko >=2.4.0               :  2.4.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.4.8 (OK)
pygments >=2.0                 :  2.3.1 (OK)
pylint >=0.25                  :  2.2.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.5.2 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  1.8.2 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  17.1.2 (OK)

# Optional:
cython >=0.21                  :  0.29.2 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  0.23.4 (OK)
scipy >=0.17.0                 :  1.1.0 (OK)
sympy >=0.7.3                  :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
If it's not a problem with the outline pane nor code completion, it has to be an installation issue or a problem with your computer, so there is nothing we can do about it, sorry.

So please don't open more issues about this. Sorry for not being able to help you further.
