### ISSUE TITLE
Improve Readme instructions on how to install Spyder from source

### ISSUE THREAD

**Issue by Jogala** [spyder-ide/spyder#12424]
In  `README.md` page 3, you write:

```
conda install spyder
conda remove spyder
git clone https://github.com/spyder-ide/spyder.git
cd spyder
python bootstrap.py
```
I guess you are recommending installing spyder first and then removing it because you want to get the dependencies.  I tried it and it did not work. I found the answer here:

https://stackoverflow.com/questions/38459186/conda-uninstall-one-package-and-one-package-only

Hence I suggest replacing 

`conda remove spyder 
`

with

`conda remove --force spyder
`

Otherwise the dependencies are not kept.

OS: Ubuntu 18

**Comment by ccordoba12** [comment]
I preferred to simply reference the instructions in our Contributing guide

https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md

to not have to maintain two sets of instructions.
