### ISSUE TITLE
 module 'numpy' has no attribute '__version__'

### ISSUE THREAD

**Issue by tapacino-dotcom** [spyder-ide/spyder#12429]
### What steps will reproduce the problem?

keep getting this error when i run my code,
 module 'numpy' has no attribute '__version__'

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  None (NOK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by tapacino-dotcom** [comment]
please explain to me how to solve this problem step by step as i am very new to python

**Comment by bcolsen** [comment]
Sorry we would need to see your code in order to help, but this doesn't sound like Spyder bug.

**Comment by tapacino-dotcom** [comment]
I don't believe is the code, because the same code works fine on my other
laptop. with Spyder 3.7. i checked online and this is common error which
happens to so many users.
I don't mind sharing the code but I've tried multiple of my codes that
were/are working good, and I still get the same error. I'm more than 100%
sure it is Spyder bug.

Thanks
Sammy

**Comment by bcolsen** [comment]
This isn’t a problem with your code or Spyder but it's a problem with your installation.

I think the easiest thing would be to reinstall Anaconda.

**Comment by ccordoba12** [comment]
Agreed. That's the only advise we can give, sorry.
