### ISSUE TITLE
Minor issue with editor on macOS and the light theme

### ISSUE THREAD

**Issue by jandyman** [spyder-ide/spyder#12437]
On MacOS Catalina on a high DPI screen the left right buttons that activate when there are a number of buffers open get "clipped". See attached [picture.]

<img width="263" alt="clipped arrow" src="https://user-images.githubusercontent.com/7635406/79925396-1d498000-83ef-11ea-9a93-f066916ac0aa.png">

**Comment by ccordoba12** [comment]
Thanks for reporting.

@goanpeca, any chance you can take a look at this one?

**Comment by ccordoba12** [comment]
@goanpeca, do you think a fix for this could be ready for 4.1.4?

**Comment by goanpeca** [comment]
>do you think a fix for this could be ready for 4.1.4?

Not sure, I tried a quick fix and did not work, will look into this after I finish the scrollbar issue.
