### ISSUE TITLE
Folder and file names completion on console using cd and edit returns unexpected options

### ISSUE THREAD

**Issue by silveira-lucas** [spyder-ide/spyder#12444]
## Problem Description

Inside the console, the completion (tab) of the command cd returns multiple options all containing the first folder name. The completion of the command edit returns multiple options all containing the last file name. I observe this problem only on the Mac OS, it runs smoothly on my Linux (Pop-OS) machine.

### What steps reproduce the problem?

1.  Create multiple folders with the same start (eg.: mkdir toto_1 toto_2 toto_3)
2. On the console type: cd toto_ and press tab
3. 

### What is the expected output? What do you see instead?

toto_1
toto_2
toto_3

## Versions
* Spyder 4.1.2
* Python 3.7.6 64-bit
* Qt 5.9.6 
* PyQt5 5.9.2 
* Darwin 19.4.0 (Mac OS Catalina)

<img width="476" alt="Screenshot 2020-04-22 at 18 07 12" src="https://user-images.githubusercontent.com/60890450/80008385-f90da200-84c7-11ea-9398-09b9ceb8773e.png">

**Comment by silveira-lucas** [comment]
Has anyone else experienced the same issue, is it related to the OS?

**Comment by goanpeca** [comment]
@silveira-lucas thanks for the report. I just checked and I see another space related issue (but might be related)

I have a bunch of screenshots on the Desktop and I get this:

![image](https://user-images.githubusercontent.com/3627835/80932133-b3808d00-8d83-11ea-8533-5bb3896f3fc6.png)

So there is definitely an issue!

**Comment by dalthviz** [comment]
Note: Probably this needs to be fixed over QtConsole
