### ISSUE TITLE
Click in to code goes to wrong place

### ISSUE THREAD

**Issue by DrXorile** [spyder-ide/spyder#12446]
### What steps will reproduce the problem?

1. Open code (I'm using Ubuntu version)
2. Suppose the cursor is on line 20.
3. Click out of the Spyder window (e.g. on a dual screen click into a browser on the other screen).
4. Mouse-over the code (without clicking into the window) and scroll down using the scroll wheel on the mouse.
5. Click, eg into line 180. 

Instead of going to line 180 it will go to a line near line 20. I presume it calculates the mouse position based on the scroll location before you clicked out (step 3 above), and not taking into account that the scroll location may have changed.

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-46-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Please post an animated gif of what you're doing because I don't understand what the error is in your case, sorry.

**Comment by DrXorile** [comment]
![Peek 2020-04-22 11-55](https://user-images.githubusercontent.com/23677835/80022119-73223480-8490-11ea-9aff-4ca35f91d7e1.gif)

1. I start by clicking into line 13.
2. I click out of Spyder.
3. I scroll down to line 81.
4. I click into line 81.
5. I find myself in line 35.

**Comment by ccordoba12** [comment]
> I click out of Spyder.

What do you mean exactly by this?

**Comment by DrXorile** [comment]
I updated the comments. I mean that I click into a different application so that Spyder is no longer the active window. In Ubuntu, you can still scroll up and down in a window that is not active by mouse-over and using the scroll wheel.

**Comment by bcolsen** [comment]
@DrXorile From the kernel version it looks like you are using 19.10, correct?

I can reproduce this on 20.04. It looks like a it might be a Qt bug with the window manager. The anaconda version is still qt=5.9. When I tried Spyder in a fresh conda environment with qt=5.12.5 from conda-forge the bug is gone.

**Comment by DrXorile** [comment]
Okay. Should I close the issue then? Is there an easy way to update qt in anacondas? I'm sure I kind find it, but just if you happened to know the command line.

**Comment by ccordoba12** [comment]
> I can reproduce this on 20.04. It looks like a it might be a Qt bug with the window manager.

This should be a bug in Ubuntu because I can't reproduce it in Kubuntu.

> Is there an easy way to update qt in anacondas?

@DrXorile, to create a conda env with a more recent version of Qt (i.e. the one in conda-forge), you need to run this command

    conda create -n py37 -c conda-forge python=3.7 spyder

Afterwards you need to run

    conda activate py37
    spyder

**Comment by DrXorile** [comment]
I can confirm that the bug no longer occurs after the above commands.
