### ISSUE TITLE
installed modules not available when choosing python virtualenv as interpreter

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#12447]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When setting virtualenv Python as interpreter modules are not available

### What steps reproduce the problem?

1. Install virtual environment through poetry (or other means) with test package
```
 curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
poetry new demo
cd demo
poetry config virtualenvs.in-project true
poetry add pip-install-test
poetry env info --path
/Users/daniel/PhD/Projects/demo/.venv%
```

1a) creating  venv using  `vanilla`  will result later  in the same error
```
python3 -m venv .venv/demo
source . /.venv/demo/bin/python/activate
pip install scipy

```

2. Open virtualnv, get python path and test import in virtualenv
```
import sys
print(sys.executable)
''/Users/daniel/PhD/Projects/demo/.venv/bin/python'
import scipy
```
No error as effect
3.
set this path as interpreter in Spyder
`/Users/daniel/PhD/Projects/demo/.venv/bin/python`
restart Spyder
```
import sys
print(sys.executable)
/Users/daniel/PhD/Projects/demo/.venv/bin/python

import scipy
Traceback (most recent call last):

  File "<ipython-input-4-4363d2be0702>", line 1, in <module>
    import scipy

ModuleNotFoundError: No module named 'scipy'
``` 

### What is the expected output? What do you see instead?
Running this python from terminal or setting in VSC work, problem with spyder 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.2
* Python version: 3.8.2
* Qt version: 
* PyQt version: 
* Operating System name/version: Darwin/MacOS 10.15.4

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by danieltomasz** [comment]
System was tre

**Comment by ccordoba12** [comment]
Great to know!
