### ISSUE TITLE
How to make ubuntu spyder use font: "Lucida Sans Typewriter"?

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#12441]
## Problem Description

    I found spyder in win10 has a fontstyle: Lucida Sans Typewriter, How to make spyder in ubuntu also use this font?

## Versions

* Spyder version: 4.1.2
* Python version: 3.6.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: ubuntu16.04

**Comment by zysNLP** [comment]
Could you please this font for ubuntu spyder in the next 4.1.3 version?

**Comment by ccordoba12** [comment]
Sorry but we don't distribute fonts along with Spyder. You need to download that font or copy it from another computer and install it in your Ubuntu PC.

**Comment by zysNLP** [comment]
@ccordoba12 But in which folder should I put the font I want?

**Comment by goanpeca** [comment]
See https://itsfoss.com/install-fonts-ubuntu/

**Comment by zysNLP** [comment]
@goanpeca Thank you! But I install a font "monaco.ttf", then I found it still not install in Plain Text but can installed in Rich Text. Why? @ccordoba12
