### ISSUE TITLE
tooltips, tab completion for imported modules work in console, but not editor

### ISSUE THREAD

**Issue by jimmyknowles** [spyder-ide/spyder#12451]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

It seems that autocompletion works differently in the editor vs. the console. Editor uses Kite while console uses something different.

I use arcpy and autocomplete only works in the console for this imported module. It will not work in the editor.

If I import arcpy in the console and hit tab after 'arcpy.', I'll get a list as expected.

If I do the same in the editor and wait or hit ctrl-space for the tooltip or autocompletion, I don't get anything. 

Is this expected behavior?

### What steps reproduce the problem?

1. import arcpy in the editor 
2. type arcpy. and wait for autocompletion to show up. Nothing shows up.
3. hit ctrl-space after the . and nothing shows up.

### What is the expected output? What do you see instead?

I expect to see the autocompletion or tooltip  in the editor.

## Versions

* Spyder version: 4.1.2
* Python version: 3.6.9
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.16.6 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.4 (OK)

**Comment by ccordoba12** [comment]
> I use arcpy and autocomplete only works in the console for this imported module. It will not work in the editor.

Sorry but there's nothing we can do about it because it doesn't depend on us but on the libraries we depend for code completion.

Code completion works fine for some modules in the editor, but it fails for others (like arcpy in your case)

**Comment by jimmyknowles** [comment]
Thanks @ccordoba12 for your quick reply.

Is there any way to use the same code completion method in the editor that is available in the console?

Is it jedi or another library that would be causing the code completion to fail? Just in case I want to pursue working with jedi or arcpy maintainers to see if we can get it working.

**Comment by ccordoba12** [comment]
> Is there any way to use the same code completion method in the editor that is available in the console?

No, there isn't for now, sorry.

> Is it jedi or another library that would be causing the code completion to fail? Just in case I want to pursue working with jedi or arcpy maintainers to see if we can get it working.

It's Jedi.
