### ISSUE TITLE
Spyder quits when removing a plot and save plots dialog is wrong.

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#12459]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

1) The dialog when saving multiple plots in the plots pane is wrong, it should be the dialog that says "Save"
![Screen Shot 2020-04-23 at 4 15 59 AM](https://user-images.githubusercontent.com/18587879/80082894-95f92b00-851a-11ea-9aac-ba810b043f6c.png)

2) Spyder quits unexpectedly when removing a plot from the context menu.

![issue](https://user-images.githubusercontent.com/18587879/80083062-cd67d780-851a-11ea-82d4-56787fb40b8e.gif)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder 4.2.0.dev0 (Commit: 89791cb28) 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version:  macOS Catalina 10.15.3

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks a lot @juanis2112 for finding this on time before 4.1.3! I can reproduce it on Linux too and it's critical for us to solve before we can do the release.

@dalthviz, please take a look at this one.

**Comment by jnsebgosselin** [comment]
1. I think it is Ok to use `getExistingDirectory` for the feature to save all figures to disk. Since we are saving multiple figures, I don't see how the "getSaveFileName" would work...  The idea is to select a directory where all figures are saved in batch in that directory. The names of the figures are determined programattically.

2. Thank you very much for finding this nasty bug! In Windows everything is working fine though.

**Comment by dalthviz** [comment]
@ccordoba12 is working for me on Windows:

![plots](https://user-images.githubusercontent.com/16781833/80428145-d0621f80-88ae-11ea-8380-5c3fee5cebd9.gif)

**Comment by goanpeca** [comment]
I can try to fix it. It does happen to me as well.

**Comment by ccordoba12** [comment]
> @ccordoba12 is working for me on Windows

Yeah, it doesn't fail on Windows, just Linux and macOS.

> I can try to fix it. It does happen to me as well.

Thanks @goanpeca! Please also address @juanis2112 first comment as well.
