### ISSUE TITLE
Github - Spyder Project

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#12463]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Please let me know if this is not the right place to ask this, but basically, I have Github desktop on my pc. When working on a Spyder project, I added *.ini *.pyc *.bak to gitignore, so that any changes done by Spyder on these files are not added to a commit. But this doesn't work, as these files always show up as being changed in the Github desktop app. Has anyone figured out a way as to why or how to ensure that these files are ignored automatically by git?

![image](https://user-images.githubusercontent.com/62237347/80117969-1b66f480-8588-11ea-8707-39d5dfbda420.png)

### What steps reproduce the problem?

1. Modify any spyder project
2. Check github desktop app for changes

### What is the expected output? What do you see instead?
file extensions added to gitignore should not be captured by github, unless spyder does something that should be added to gitignore.

### Paste Traceback/Error Below (if applicable)

```python-traceback
NA
```

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.4
* Qt version: 5.9.2
* PyQt version: 5
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
You are correct this is not an issues with spyder.

You need to make sure the file is named `.gitignore`

**Comment by kaleb-keny** [comment]
thanks, I'll check it out

**Comment by kaleb-keny** [comment]
Turns out it's a cache issue, in case someone comes across it, you can fix this with the below
`git rm --cached <filename>`
