### ISSUE TITLE
Error - "SyntaxError: unexpected EOF while parsing", only by F5 but not by F9

### ISSUE THREAD

**Issue by sregiters** [spyder-ide/spyder#12469]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ]x Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### Problem Description
The following error message was appeared when carrying out the code 'temp.py' only by F9, not by F5.  The code, described bellow, is intact from one provided by the Spyder.

> In [2]: def hello(name):
> File "<ipython-input-2-70b3a3311a22>", line 1
> def hello(name):
>  ________________^
> SyntaxError: unexpected EOF while parsing 

`# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
def hello(name):
    """Given an object 'name', print 'Hello ' and the object."""
    print("Hello {}".format(name))

i = 42
if __name__ == "__main__":
    hello(i)
`

### What steps reproduce the problem?

1.  Project > New Project ... --> ... --> 'temp.py', described above, was created.
2.  Pushed F9 on the line of 14 "def hello(name):" --> The error message appeared.

### What is the expected output? What do you see instead?
F5 gave the result successfully.

### Paste Traceback/Error Below (if applicable)

```python-traceback

//no message 

```

###Versions

* Spyder version: 4.1.2
* Python version: 3.7.7 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

###Dependencies
```
# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

```

**Comment by ccordoba12** [comment]
You can't perform line-by-line evaluations of code with F9 if that code is not a complete Python statement. In your case, this statement:

```python
def hello(name):
```

is clearly not complete because it requires more code to be so.

In that case you need to select with the mouse the entire definition:

 ```python
def hello(name):
"""Given an object 'name', print 'Hello ' and the object."""
print("Hello {}".format(name))
```

and then press F9 to evaluate it.
