### ISSUE TITLE
spyder app suddenly close

### ISSUE THREAD

**Issue by mitrasafari** [spyder-ide/spyder#12470]
##Problem Description
I have a spyder app (v4) in my one of environments and it was working correctly till I start to install some libraries for image processing like scikit-learn, metric-learn, and ...
now my spyder app suddenly closes and when I open it again it's happening again.
I update my version of my spyder app (4.1.2) but still the same. why is happening? and what should I do?

## Versions

* Spyder version: 4.1.2
* Python version: 3.6.7
* Qt version: 5.6.2
* PyQt version: 5 5.6
* Operating System name/version: windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.11.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.4.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  2.3.1 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.2.0 (OK)
sympy >=0.7.3                  :  None (OK) 

```

**Comment by ccordoba12** [comment]
Did you use pip to install those libraries you mentioned?

**Comment by mitrasafari** [comment]
Hi @ccordoba12, thanks for the reply
most of them, no but for some libraries like metric-learn l try pip install

**Comment by ccordoba12** [comment]
Well, as I imagined, that was (most probably) what introduced the problem. Please remove your environment and recreate it again, but without installing Spyder on it. Instead, please follow the instructions in this guide:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to understand how to use the packages in that environment from the Spyder version installed in your base conda env.

If problems persist, I'm afraid you'll have to remove and reinstall Anaconda.
