### ISSUE TITLE
Spyder won't launch without Administrator credentials

### ISSUE THREAD

**Issue by saurabh87prabhu** [spyder-ide/spyder#12476]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Just installed Anaconda3-2020.02 using the 64-bit installer on Windows 7 pc. When I try to open Spyder using the "Launch" button in the Navigator, nothing happens. No prompts, no errors, no warnings. When I try running from the conda prompt using the command "spyder" and "spyder --show-console", nothing happens. No error, no messages, no traceback.

When I run as Administrator, everything works fine. It's hard to get admin credentials regularly at my company. 
Also, it seems to work fine for some of my colleagues, without admin credentials . Is this a known issue? Thanks in advance.

![spyder_launch_issue](https://user-images.githubusercontent.com/26367729/80226380-ea5ef080-8669-11ea-9979-a5ee1650e285.PNG)
### What steps reproduce the problem?

1. Installed Anaconda3-2020.02 (using the 'Just me' option). No admin credentials given during installation
2. Hit 'Launch' button from Spyder
3. 'spyder' command on console
Restarted PC, Anaconda several times.

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

**Comment by ccordoba12** [comment]
This is an installation issue and not a problem with Spyder. Please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/
