### ISSUE TITLE
Kite deletion causing spyder crash maybe!?

### ISSUE THREAD

**Issue by Blindsh0t** [spyder-ide/spyder#12479]
### Issue Report Checklist

* [ O] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ O] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ O] Tried basic troubleshooting (if a bug/error)
    * [O ] Restarted Spyder
    * [ O] Reset preferences with ``spyder --reset``
    * [ O] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ O] Tried the other applicable steps from the Troubleshooting Guide
* [ O] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I recently installed Anaconda and Spyder with it installed Kite. Wanted to look about.
Didnt much like Kite so wanted to uninstall on my mac but kept saying its being used even though Anaconda or any other products were closed.
Hence i had to remove it and its components from terminal. 
Since then I am getting 2 types of error

### What steps reproduce the problem?

1. when tried to open spyder it says `'Traceback Error`
as given below

2.  Every few minutes on my mac started getting a pop up `For security reasons, you need to code sign your application or sign your updates with a EdDSA key.`

### What is the expected output? What do you see instead?
I have reset via terminal
reinstalled Full Anaconda 3 times 
Installed Kite seperately and failed to close as it was "being open"
Somehow managed to remove kite from application 
But still cant open Spyder

### Paste Traceback/Error Below (if applicable)
```
Traceback (most recent call last):
File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 3557, in run_spyder
main = MainWindow(options)
File "/opt/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 423, in __init__
from spyder.preferences.appearance import AppearanceConfigPage
File "/opt/anaconda3/lib/python3.7/site-packages/spyder/preferences/appearance.py", line 20, in 
from spyder.plugins.editor.widgets.codeeditor import CodeEditor
File "/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/widgets/codeeditor.py", line 61, in 
from spyder.plugins.completion.kite.widgets.calltoaction import (
ModuleNotFoundError: No module named 'spyder.plugins.completion.kite 

```
```python-traceback

PASTE TRACEBACK HERE

```

## Versions
1.9.12 

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> Hence i had to remove it and its components from terminal.

I don't know what you did here, but the error above shows an incomplete Spyder installation, i.e. a file is missing from our source code.

To solve it, please remove Anaconda again, then remove this directory `/opt/anaconda3` entirely, then reinstall it again. That should solve your problem.

> Every few minutes on my mac started getting a pop up For security reasons, you need to code sign your application or sign your updates with a EdDSA key.

I don't know why this warning appears, but it's also probably related to the way you removed Kite.

**Comment by Blindsh0t** [comment]
First, I had installed in my home directory Anaconda
Now i have done as `/opt`
It did solve one problem but now i have 2 pip and 3 python versions
But yeah one problem down :)

**Comment by ccordoba12** [comment]
> It did solve one problem but now i have 2 pip and 3 python versions

Please uninstall them all because they interfere between each other. And leave only one in Anaconda.

**Comment by Blindsh0t** [comment]
ok, but this will also create issues with previously used pip as having installed a lot of things on it. Also, some paths have to change, is it so?

**Comment by ccordoba12** [comment]
> /Library/Frameworks/Python.framework/Versions/3.8/bin/

It's a really bad practice to install things in your system Python because it can break your operating system. So whatever you installed there, please remove it.

> /usr/local/lib/python3.7/site-packages

This probably comes from a Homebrew installation. It's fine to leave it but you need to avoid mixing packages there with Anaconda.

----

I'm sorry but I'm going to close this issue because it's not a problem with Spyder but with the way you installed and mixed several Python versions. So you need to untangle the mess you made and things should be fine again.

**Comment by Blindsh0t** [comment]
Thanks for the help, actually I was going to uninstall Spyder and all not gonna lie
But you actually helped me through. I will learn to untangle this mess and I will keep and learn more about Spyder :)
