### ISSUE TITLE
Hovers don't hide when Spyder loses focus

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#12477]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The issue started with version 4 of Spyder, where the help boxes remain persistent despite me going to another window/browser as can be seen with the picture below.

### What steps reproduce the problem?

1. Hovering over some variable produces a help box
2. Going to another window/browser/desktop the help box persists

![image](https://user-images.githubusercontent.com/62237347/80231040-19b63300-8653-11ea-904d-482f90e02637.png)

### What is the expected output? What do you see instead?
The help box should not be persistent on the screen.

### Paste Traceback/Error Below (if applicable)

```python-traceback

NA
```

## Versions

(even going to get the Spyder version this pops up and persists)
![image](https://user-images.githubusercontent.com/62237347/80231199-53873980-8653-11ea-9642-6bb9d8316310.png)

* Spyder version: 4.1.2
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.3.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This behavior is very annoying indeed!!

I have already a fix for it, which will part of our next version (4.1.3), to be released in a week and a half.

**Comment by kaleb-keny** [comment]
Hi @ccordoba12  I know we discussed and closed this issue, but I am still having it I have the latest spyder 4.1.5 and running on windows 10, with the latest python version... Should I open a seperate issue?

**Comment by kaleb-keny** [comment]
![image](https://user-images.githubusercontent.com/62237347/97755669-e66cc900-1af9-11eb-8739-740775324269.png)

**Comment by ccordoba12** [comment]
Sure, please do. I haven't seen this error on Linux after I merged the PR that solved this issue though.

**Comment by kaleb-keny** [comment]
Alright, I'll try to see when it happens again exactly what I did to try and replicate it, then i'll raise the issue... as It's not consistent honestly, but when it does happen it's very annoying...
