### ISSUE TITLE
Spyder crashes when saving or opening files

### ISSUE THREAD

**Issue by Nat250** [spyder-ide/spyder#12478]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I've been trying to get Spyder to work so I can try to learn python, but every time I try to open or save a file with it, it crashes. I've tried reinstalling python and Anaconda, updating it, following the troubleshooting guide, but nothing works. I lose anything I wasn't able to save too, so I can't work around it.

### What steps reproduce the problem?

1. Attempting to open a file
2. Attempting to save a file
3. 

### What is the expected output? What do you see instead?

The expected output is being able to save and open files with Spyder. What I see is it opening the file folder, freezing after a few seconds, and crashing, without as much as an error message.

### Paste Traceback/Error Below (if applicable)

```python-traceback

WARNING:traitlets:kernel died: 18.059669256210327
WARNING:traitlets:kernel died: 18.000118255615234
WARNING:traitlets:kernel died: 18.00024652481079
WARNING:traitlets:kernel died: 18.000144958496094
WARNING:traitlets:kernel died: 18.000624179840088

```

## Versions

* Spyder version: 3.3.5 and 4.0.1
* Python version: 3.7.6 64 bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

```

**Comment by ccordoba12** [comment]
This is not a problem with Spyder. Please see issue #3903 for a possible solution.
