### ISSUE TITLE
Collapsed code search bug

### ISSUE THREAD

**Issue by Valemos** [spyder-ide/spyder#12485]
### What steps will reproduce the problem?

if i have collapsed function in class and i try to find something in code, and this can be found inside that function, the whole class collapses.

Also related big bug - if i have collapsed functions, after some actions their names no more highlited as collapsed and clicking arrow button again "collapses" again already collapsed code.

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
> if i have collapsed function in class and i try to find something in code, and this can be found inside that function, the whole class collapses.

I can't reproduce this bug, or at least not following the instructions you mentioned. Please make an animated gif of problem using the Licecap program to better understand what you mean by this.

> Also related big bug - if i have collapsed functions, after some actions their names no more highlited as collapsed and clicking arrow button again "collapses" again already collapsed code.

What actions? Your description is not enough to understand how to reproduce this issue. Again, if you can post an animated gif it'd much easier for us to see what's happening.

**Comment by derekeden** [comment]
I can confirm this issue. Sometimes I collapse a block of code, and if I make some changes to code above this collapsed block (i.e. add or remove lines) the collapse arrow no longer lines up with the original function/class that was collapsed. Then it can be uncollapsed and starts collapsing random bits of code.

**Comment by Valemos** [comment]
> 
> 
> > if i have collapsed function in class and i try to find something in code, and this can be found inside that function, the whole class collapses.
> 
> I can't reproduce this bug, or at least not following the instructions you mentioned. Please make an animated gif of problem using the [Licecap](https://www.cockos.com/licecap/) program to better understand what you mean by this.
> 
> > Also related big bug - if i have collapsed functions, after some actions their names no more highlited as collapsed and clicking arrow button again "collapses" again already collapsed code.
> 
> What actions? Your description is not enough to understand how to reproduce this issue. Again, if you can post an animated gif it'd much easier for us to see what's happening.

This is another problem with code collapse (they can be related). Currently I'm looking for conditions to reproduse the first issue
![error_gif](https://user-images.githubusercontent.com/26038728/80707197-3ee2ef80-8af2-11ea-8eee-21a808bc797d.gif)

**Comment by goanpeca** [comment]
@Valemos it seems you try to upload a GIF, but it seems to be correupted? Could you please reupload, thanks!

**Comment by Valemos** [comment]
![error_gif](https://user-images.githubusercontent.com/26038728/80753743-73789a80-8b36-11ea-9f30-a424603ba322.gif)

**Comment by Valemos** [comment]
I can definitely say, that this issue happens when deleting a piece of code

**Comment by goanpeca** [comment]
Thanks for the input @Valemos , definitely an issue there with deletion. We are not properly updating the folding ranges after that.

@andfoy I think with this example is now clearer what triggers the problem. Please take a look at it.

**Comment by shalinshal** [comment]
>> if i have collapsed function in class and i try to find something in code, and this can be found inside that function, the whole class collapses.
>>
> I can't reproduce this bug, or at least not following the instructions you mentioned. Please make an animated gif of problem using the Licecap program to better understand what you mean by this.
>
I guess this is what @Valemos meant
method gaussian(collapsed) has a print statement in it. typing in search bar toggles between folding and unfolding the class
![search](https://user-images.githubusercontent.com/7792558/84973607-7da72600-b0ef-11ea-8708-76d61f1b581d.gif)

**Comment by shalinshal** [comment]
>> Also related big bug - if i have collapsed functions, after some actions their names no more highlited as collapsed and clicking arrow button again "collapses" again already collapsed code.
>>
> What actions? Your description is not enough to understand how to reproduce this issue. Again, if you can post an animated gif it'd much easier for us to see what's happening.
>
Actually quite the opposite of what @Valemos meant, but you will get the idea. 
Coming back to this file after working(let's call it some actions) on a different one. You can see that the method `def check()` was greyed with the arrow suggesting that it's folded, even though it wasn't. When clicking on arrow it unfolded the already unfolded method, and changed the arrow to it correct position.
![collapsed](https://user-images.githubusercontent.com/7792558/84979624-e3021380-b0fd-11ea-8699-227a22a95561.gif)

**Comment by jmoraispk** [comment]
@shalinshal I also believe that's what @Valemos meant. At least that's exactly what's happening in my case.
