### ISSUE TITLE
An idea to improve the visual of the 'Lock panes and toolbars' action in the View menu

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#12488]
This is a simple idea to maybe improve the action to lock and unlock panes and toolbars in Spyder.

I can push a PR if you like or you can close if you don't, that is ok too :)

Basically, the icon and text of the action is changed according to the locked state of the panes and toolbars.

![lock_unlock_interface](https://user-images.githubusercontent.com/10170372/80288305-22674180-8705-11ea-966f-fb495cf53932.gif)

For comparison, this is the current behaviour.

![lock_unlock_interface_old](https://user-images.githubusercontent.com/10170372/80288316-30b55d80-8705-11ea-9c0b-73270ffce6bf.gif)

**Comment by ccordoba12** [comment]
> Basically, the icon and text of the action is changed according to the locked state of the panes and toolbars.

I really like it!! Thanks a lot for the suggestion and your PR is more than welcome!

**Comment by jnsebgosselin** [comment]
Excellent! Do I do it against Master or 4.x?

**Comment by goanpeca** [comment]
4.x :-)
