### ISSUE TITLE
error on starting spyder 4 kernel

### ISSUE THREAD

**Issue by milmun** [spyder-ide/spyder#12504]
I have created a new environment in Anaconda, using the same version of Python and spyder kernels as those of the root environment. However, when I changed the Python Interpreter to the Python installed in the environment, the Kernel tries to start but dies in a loop. Do you know how to solve the problem?

**Comment by ccordoba12** [comment]
Please update to our 4.1.2 version and try again. That version will report the cause of the error.

**Comment by milmun** [comment]
This is the message I get:

Traceback (most recent call last):
File "C:\Users\anaconda3\envs\ox\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\anaconda3\envs\ox\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\spyder_kernels\console\start.py", line 288, in main
import_spydercustomize()
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\IPython\__init__.py", line 49, in 
from .terminal.embed import embed
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\IPython\terminal\embed.py", line 18, in 
from IPython.terminal.interactiveshell import TerminalInteractiveShell
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\IPython\terminal\interactiveshell.py", line 16, in 
from prompt_toolkit.document import Document
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\__init__.py", line 16, in 
from .interface import CommandLineInterface
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\interface.py", line 19, in 
from .application import Application, AbortAction
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\application\__init__.py", line 1, in 
from .application import Application
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\application\application.py", line 39, in 
from prompt_toolkit.buffer import Buffer
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\buffer.py", line 9, in 
from .completion import Completer, Completion, CompleteEvent
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\completion\__init__.py", line 1, in 
from .base import (
File "C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\completion\base.py", line 7, in 
from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator' from 'prompt_toolkit.eventloop' (C:\Users\anaconda3\envs\ox\lib\site‑packages\prompt_toolkit\eventloop\__init__.py)

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but an installation issue in your `ox` environment. Please post the output of

    conda list

for it.

**Comment by milmun** [comment]
Here are my packages on my environment:

attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
boost-cpp                 1.72.0               h0caebb8_0    conda-forge
branca                    0.4.0                      py_0    conda-forge
brotlipy                  0.7.0           py37h4ab8f01_1000    conda-forge
bzip2                     1.0.8                hfa6e2cd_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37ha419a9e_0    conda-forge
cfitsio                   3.470                hfa6e2cd_2    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
colorama                  0.4.3                      py_0    conda-forge
cryptography              2.8              py37hb32ad35_1    conda-forge
curl                      7.69.1               h1dcc11c_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
descartes                 1.1.0                      py_4    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
expat                     2.2.9                he025d50_2    conda-forge
fiona                     1.8.13           py37hb7fdc2d_0    conda-forge
folium                    0.10.1                     py_0    conda-forge
freetype                  2.10.1               ha9979f8_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      3.0.4            py37hd44be9e_8    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geopy                     1.21.0                     py_0    conda-forge
geos                      3.8.1                he025d50_0    conda-forge
geotiff                   1.5.1               h3d29ae3_10    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.64.2               he4de6d7_0    conda-forge
hdf4                      4.2.13            hf8e6fe8_1003    conda-forge
hdf5                      1.10.6          nompi_ha405e13_100    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       64.2                 he025d50_1    conda-forge
idna                      2.9                        py_1    conda-forge
intel-openmp              2020.0                      166
ipykernel                 5.2.1            py37h5ca1d4c_0    conda-forge
ipython                   5.8.0                    py37_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kealib                    1.4.13               h3b59ab9_1    conda-forge
kiwisolver                1.2.0            py37heaa310e_0    conda-forge
krb5                      1.17.1               hdd46e55_0    conda-forge
libblas                   3.8.0                    15_mkl    conda-forge
libcblas                  3.8.0                    15_mkl    conda-forge
libcurl                   7.69.1               h1dcc11c_0    conda-forge
libffi                    3.2.1             h6538335_1007    conda-forge
libgdal                   3.0.4                h6f60a84_8    conda-forge
libiconv                  1.15              hfa6e2cd_1006    conda-forge
libkml                    1.3.0             h7e985d0_1011    conda-forge
liblapack                 3.8.0                    15_mkl    conda-forge
libnetcdf                 4.7.4           nompi_h256d12c_103    conda-forge
libpng                    1.6.37               hfe6a214_1    conda-forge
libpq                     12.2                 hd9aa61d_1    conda-forge
libsodium                 1.0.17               h2fa13f4_0    conda-forge
libspatialindex           1.9.3                he025d50_3    conda-forge
libspatialite             4.3.0a            h51df0ed_1038    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.1.0                h885aae3_6    conda-forge
libwebp-base              1.1.0                hfa6e2cd_3    conda-forge
libxml2                   2.9.10               h9ce36c8_0    conda-forge
lz4-c                     1.9.2                h33f27b4_0    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
markupsafe                1.1.1            py37h8055547_1    conda-forge
matplotlib-base           3.2.1            py37h911224e_0    conda-forge
mkl                       2020.0                      166
mkl-service               2.3.0            py37hb782905_0
msys2-conda-epoch         20160418                      1
munch                     2.5.0                      py_0    conda-forge
networkx                  2.4                        py_1    conda-forge
numpy                     1.18.1           py37h90d3380_1    conda-forge
openjpeg                  2.3.1                h57dd2e7_3    conda-forge
openssl                   1.1.1g               he774522_0    conda-forge
osmnx                     0.12               pyh9f0ad1d_0    conda-forge
pandas                    1.0.3            py37h3bbf574_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 h6538335_0    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.0.2                     py_2    conda-forge
poppler                   0.87.0               h0cd1227_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 he14cc48_1    conda-forge
proj                      7.0.0                haa36216_3    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.0            py37he833962_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywin32                   227              py37hfa6e2cd_0    conda-forge
pyzmq                     19.0.0           py37h8c16cda_1    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
rtree                     0.9.4            py37h804a536_1    conda-forge
scikit-learn              0.22.2.post1     py37h7208079_0    conda-forge
scipy                     1.4.1            py37h9439919_0
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
shapely                   1.7.0            py37he1cf020_3    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.14.0                     py_1    conda-forge
spyder-kernels            1.9.0            py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
tbb                       2018.0.5             he980bc4_0    conda-forge
tiledb                    1.7.7                h0b90766_1    conda-forge
tk                        8.6.10               hfa6e2cd_0    conda-forge
tornado                   6.0.4            py37hfa6e2cd_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vc                        14.1                 h869be7e_1    conda-forge
vincent                   0.4.4                      py_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
win_inet_pton             1.1.0                    py37_0    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
xerces-c                  3.2.2             h6538335_1004    conda-forge
xz                        5.2.5                h2fa13f4_0    conda-forge
zeromq                    4.3.2                h6538335_2    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
zstd                      1.4.4                h9f78265_3    conda-forge

**Comment by ccordoba12** [comment]
> prompt-toolkit 3.0.5 py_0 conda-forge
prompt_toolkit 1.0.15 py_1 conda-forge

You have these two prompt_toolkit versions installed (I don't know how you got both). Besides, you're using a very old IPython version (5.8.0), when the latest one for Python 3 is 7.13.0.

A solution for your problem could be to remove `prompt_toolkit 1.0.15` and update IPython to 7.13.0. If that doesn't work, I'm afraid you'll have to remove and recreate your `ox` env from scratch because it looks broken to me.
