### ISSUE TITLE
Show only user variables in Variable explorer

### ISSUE THREAD

**Issue by shivaadusumilli** [spyder-ide/spyder#12506]
Recently I reinstalled spyder(Anaconda) and now I wasn't able to delete some variables from variable explorer.
excluding all possible variables from top-right menu isn't working.
is there any other way to remove those variables?

System Details:
Windows 10
Spyder 4.1.2
Anaconda Navigator 1.9.12

![Screenshot (35)](https://user-images.githubusercontent.com/34206318/80321166-9f470800-8838-11ea-87ab-90003e342a28.png)

**Comment by ccordoba12** [comment]
Those variables appeared because you are importing Pylab by default in the IPython console. To avoid that, please go to the menu

    Tools > Preferences > IPython console > Graphics

and deactivate the option called `Automatically load Pylab and NumPy modules`.

If that doesn't work, please open the Anaconda Prompt and run there

    spyder --reset

**Comment by shivaadusumilli** [comment]
@ccordoba12 thank you. It worked.

**Comment by ccordoba12** [comment]
Great!!
