### ISSUE TITLE
How can I run a local script in a remote kernel in Spyder 4?

### ISSUE THREAD

**Issue by ale0hub** [spyder-ide/spyder#12503]
### What steps will reproduce the problem?

I have connected to a remote kernel, with the descriptor json file. It seems to work fine, since I write the command print("Hello world") at it prints it. However, I'm not albe to run the same print("Hello world") written in a local file. It says ERROR:root:File [filepath] not found.
Does Spyder allow this operation? Or am I missing some step to make it work?

Thanks in advance

I'm Using Spyder 4 with Anaconda, I downloaded and installed it again just two days before from the last current update in the web page.

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting.

@impact27, I thought this workflow was possible in our new kernel architecture, i.e. passing the file contents to the kernel if it can't be found locally. Is that not really the case?

**Comment by impact27** [comment]
is the remote kernel a spyder kernel?

**Comment by ale0hub** [comment]
![Captura2](https://user-images.githubusercontent.com/64269434/80382919-334db980-88a3-11ea-95a4-897710413c9c.PNG)

When I open spyder I only see Terminal 1/A, then I do the remote kernel assignment and it appears Terminal 2/A and there I run first the code and after the local file I have open. 

One guy in my work prepared the machine for me, Im pretty sure he did it right, he knew my purposes. Although how can I check if it is actually a Spyder a kernel or do I need some requirements to tell him when creating the machine?

**Comment by impact27** [comment]
It looks like it is just a regular kernel and not a spyder kernel. In this case you can only run a file that is on the remote machine. As a workaround you can copy the content of the file in the kernel or run cells

**Comment by ale0hub** [comment]
Cool, thank you, I'll try these methods. Is there any documentation to properly build a spyder kernel?

**Comment by ccordoba12** [comment]
Yes, our docs for that are here:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

The short summary is:

* Install spyder-kernels in your remote machine
* Start a spyder kernel with `python -m spyder_kernels.console`
* Get the json file of the kernel and connect to it in your local machine.
