### ISSUE TITLE
Add functionality forwards/backwards mouse button

### ISSUE THREAD

**Issue by rlloretb** [spyder-ide/spyder#12521]
Would it be possible to link "previous cursor position" and "next cursor position" to the backwards and forward button of a mouse, as when we use a web browser?

**Comment by ccordoba12** [comment]
Sorry, that's not possible. But we fixed and greatly improved this functionality, and created new shortcuts for it (`Alt+Left/Right arrow keys`). All these fixes will be available in our next version (4.1.3).

**Comment by goanpeca** [comment]
>Sorry, that's not possible.

Is it not possible?

**Comment by ccordoba12** [comment]
Not with our current way of grabbing shortcuts in our Preferences.

**Comment by ccordoba12** [comment]
Yeah, that's what I meant. We'd need to expand our way of capturing shortcuts to include mouse buttons and I don't know if Qt supports that.

**Comment by rlloretb** [comment]
> Sorry, that's not possible. But we fixed and greatly improved this functionality, and created new shortcuts for it (`Alt+Left/Right arrow keys`). All these fixes will be available in our next version (4.1.3).

This is a great alternative. In line with Firefox's commands.

**Comment by ccordoba12** [comment]
Glad to know you agree with our changes :+1:
