### ISSUE TITLE
unseen variable 

### ISSUE THREAD

**Issue by Dalin9Chen** [spyder-ide/spyder#12528]
### What steps will reproduce the problem?

import tensorflow as tf
import numpy as np

from tensorflow.keras.datasets import mnist

(X, Y), (X_test, Y_test) = mnist.load_data()

examples_per_digit = 20

X_train=[[[0 for i in range(28*28)] for j in range(examples_per_digit)] for t in range(10)]
Y_train=[[0 for i in range(examples_per_digit)] for j in range(10)]
X_counters = [0 for _ in range(10)]

n_total_train_examples = 0

from itertools import chain
i = 0
while n_total_train_examples<examples_per_digit*10:
    if X_counters[Y[i]]<examples_per_digit:
        X_flatten = list(chain.from_iterable(X[i]))
        for j in X_flatten:
             X_train[Y[i]][X_counters[Y[i]]][j]=X_flatten[j]
        Y_train[Y[i]][X_counters[Y[i]]] = Y[i]
        X_counters[Y[i]]+=1
        n_total_train_examples+=1
    i+=1

U = []
S = []
VH = []
for i in range(len(X_train)):   
    u,s,vh = np.linalg.svd(X_train[i],full_matrices=True)  
    U.append(u)
    S.append(s)
    VH.append(vh)
    
#just run the code above, the variable "VH" not shown in the variable explorer

### Traceback
```python-traceback
  File "D:\programs\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 790, in contextMenuEvent
    self.refresh_menu()
  File "D:\programs\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 707, in refresh_menu
    self.refresh_plot_entries(index)
  File "D:\programs\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 712, in refresh_plot_entries
    is_list = self.is_list(key)
  File "D:\programs\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 1464, in is_list
    return self.var_properties[name]['is_list']
KeyError: 'vh'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.13.0 (OK)
jedi =0.14.1                 :  0.16.0 (NOK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.0 (OK)
pygments >=2.0               :  2.6.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.10 (OK)
zmq >=17                     :  19.0.0 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  0.7.0 (OK)
qtconsole >=4.6.0            :  4.7.2 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.4 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.3 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in our next version (4.1.3), to be released next week.
