### ISSUE TITLE
Spyder is not detecting the presence of iPython 0.13.1rc2 nor IPython 1.0dev

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1253]
_From [nick.sil...@gmail.com](https://code.google.com/u/114353310198631997295/) on 2013-02-05T17:28:39Z_

Spyder Version:  2.2.0beta2
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v1) 4.9.3 on Linux Mint 14 

What steps will reproduce the problem?

 1. open spyder 2.2.0beta2 2. 3. What is the expected output? What do you see instead? I would expect to see and ipython console or an option to open an ipython console.  It is as if Spyder does not see any ipython version installed on my computer.  I have, however, successfully installed ipython 0.13.1.rc2.  What do I need to do to get ipython working? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1253_

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-02-05T17:00:47Z_

@-nick.silverman11: Could you launch beta2 once more, look at the "Interpreters" menu and report back what you see there?

**Comment by spyder-issues-migrator** [comment]
_From [nick.sil...@gmail.com](https://code.google.com/u/114353310198631997295/) on 2013-02-05T17:30:51Z_

There is only one option: "Open a Python interpreter"

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-02-05T20:06:00Z_

You're right. Spyder is not finding IPython. There really isn't anything special to configure from Spyder's perspective. I assume you can launch IPython fine outside of Spyder. What results when you try to run "ipython qtconsole" from a terminal?

I'm no expert on the various flavors of Linux, but I do know that there are package dependencies for some platforms. This is from the Spyder README: On Ubuntu you need to install ipython-qtconsole, on Fedora ipython-gui and on Gentoo ipython with the qt4 USE flag.

I'm having a hard time reproducing this situation on Ubuntu 12.04 or 12.10. I even rolled my IPython back to 0.13.1.rc2 just to see if there was something special about that version that would cause problems. Nothing so far.

**Comment by spyder-issues-migrator** [comment]
_From [nick.sil...@gmail.com](https://code.google.com/u/114353310198631997295/) on 2013-02-06T10:56:26Z_

OK...I just upgraded ipython to 0.13.1 and it started working in 
Spyder.  I guess it just did not like version 0.13.1.rc2.  Thanks for 
your help..

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-02-06T11:11:27Z_

Ok. Good to hear that it's working now.

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-07T09:58:22Z_

Nick, it seems our checking version algorithm is not too good. Thanks for your patience.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-18T05:53:39Z_

It seems this bug keeps hunting us. And I just noticed that the version you reported is the one that comes with Ubuntu 12.10, so this needs a proper fix.

**Summary:** Spyder is not detecting the presence of iPython 0.13.1rc2 nor IPython 1.0dev  \<span class="oldvalue"> (was: iPython 0.13.1 not available in Spyder 2.2.0beta2) \</span>  
  **Status:** Accepted  
  **Labels:** -Priority-Medium -Cat-SpyderGUI -OpSys-Linux Priority-High Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-18T06:06:27Z_

This has to be fixed now by revision 20e74405d8c .

**Status:** Fixed  
  **Labels:** MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [frcjean](https://code.google.com/u/frcjean/) on 2013-05-14T10:28:18Z_

Apparently this isn't fixed - I have ipython 0.12 and spyder 2.2.0, and ipython is not detected. There is only "Open a Python interpreter" available in the "Interpreters" menu.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-05-14T10:51:45Z_

Spyder 2.2 only works with IPython 0.13.x, not 0.12 nor 1.0dev, so you need to upgrade.

**Comment by stuppie** [comment]
I had the same issue with ipython3 version 1.2.1 and Spyder 2.3.2 
Installing ipython3-qtconsole fixed it

**Comment by ccordoba12** [comment]
@stuppie Yes, that's mentioned in our docs

http://pythonhosted.org/spyder/installation.html#recommended-modules
