### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by ola0908** [spyder-ide/spyder#12540]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ola0908** [comment]
I tried spyder --reset 
reinstall anaconda 
spyder console show 
I don't know what to do

**Comment by ccordoba12** [comment]
Please post a screenshot of what you're seeing because I don't understand what's happening in your case.

**Comment by ola0908** [comment]
Here it id.
-------- Oryginalna wiadomość --------Od: Carlos Cordoba <notifications@github.com> Data: 29.04.2020  15:54  (GMT+01:00) Do: spyder-ide/spyder <spyder@noreply.github.com> DW: ola0908 <olcia12406@wp.pl>, Author <author@noreply.github.com> Temat: Re: [spyder-ide/spyder] Spyder crashed during last session (#12540) 
Please post a screenshot of what you're seeing because I don't understand what's happening in your case.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spyder-ide/spyder/issues/12540#issuecomment-621224001",
"url": "https://github.com/spyder-ide/spyder/issues/12540#issuecomment-621224001",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ola0908** [comment]
![Screenshot_20200429-155816_Teams](https://user-images.githubusercontent.com/64536930/80605705-b56ce800-8a33-11ea-92d2-d6f6895f53b8.jpg)

**Comment by ccordoba12** [comment]
What happens after you press `Ok` in that dialog?

**Comment by ola0908** [comment]
Nothing

**Comment by ola0908** [comment]
It's just closing The window

**Comment by andrevbrito** [comment]
I had the exact same problem and i still dont know what to do. Have you managed to fix that problem?

**Comment by adeny100** [comment]
Hi, 
  I have the same error where my spyder crashes. I have asked for help on spyder's gitter community but they did not manage to fix it for me. 
This is the error that did not change throughout even after spyder --reset.
(base) C:\Users\agnel>spyder
Traceback (most recent call last):
File "C:\Users\agnel\Downloads\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\agnel\Downloads\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "C:\Users\agnel\Downloads\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 960, in setup
self.completions.start()
File "C:\Users\agnel\Downloads\anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 292, in start
client_info['plugin'].start()
File "C:\Users\agnel\Downloads\anaconda3\lib\site-packages\spyder\plugins\completion\kite\plugin.py", line 141, in start
self.kite_process = run_program(path)
File "C:\Users\agnel\Downloads\anaconda3\lib\site-packages\spyder\utils\programs.py", line 214, in run_program
return subprocess.Popen(fullcmd, **subprocess_kwargs)
File "C:\Users\agnel\Downloads\anaconda3\lib\subprocess.py", line 800, in init
restore_signals, start_new_session)
File "C:\Users\agnel\Downloads\anaconda3\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

(base) C:\Users\agnel>

**Comment by adeny100** [comment]
Note: I have managed to open spyder once before. I was prompt to install kite after that but installing kite had errors. After a week without touching spyder, I went to launch it again. I was greeted with a normal green spyder screen and I thought it was going to launch completely well. However, after the green screen loads completely, it disappears. Nothing shows up, so I tried to launch it again. Then it loads again and there I met the error "Spyder crashed during last session." 
Spyder version: 3.7

**Comment by ccordoba12** [comment]
@adeny100, your problem is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.1.2

**Comment by ccordoba12** [comment]
@ola0908, I'm sorry but I'm going to close this one because we don't have any way to help you given that there's no error we can take a look at to guide you.

**Comment by praveenkumar1980** [comment]
![image](https://user-images.githubusercontent.com/66399101/83708929-0ecfc480-a63b-11ea-90ac-8bfb5734449d.png)
This is a constant issue even after uninstalling, reinstal and doing n number of things . Unfortunate
