### ISSUE TITLE
When i open orange 3 After installing from Anaconda it shows black screen.......... Plz someone tell me solution

### ISSUE THREAD

**Issue by Aditya222002** [spyder-ide/spyder#12545]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Aditya222002** [comment]
![image](https://user-images.githubusercontent.com/64554000/80635502-92fdbd80-8a79-11ea-923c-5398cd7304bb.png)

**Comment by goanpeca** [comment]
@Aditya222002 this repository is for `Spyder` related questions. Also since you are using Anaconda, and Anaconda-Navigator, the place to ask this is: 
https://github.com/ContinuumIO/anaconda-issues/issues/

Please make sure that your issues are related to Spyder next time ;-), cheers!
