### ISSUE TITLE
Connecting to remote kernel

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#12551]
### What steps will reproduce the problem?

Connect and reconnect to remote kernel several times.  Connection sometimes gets terminated because VPN connection is terminated.  Spyder has been open for multiple days.

### Traceback
```python-traceback
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1122, in create_client_for_kernel
    password)
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1804, in _create_client_for_kernel
    kernel_client.load_connection_file()
  File "/Users/selah/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 493, in load_connection_file
    with open(connection_file) as f:
IsADirectoryError: [Errno 21] Is a directory: '/Users/selah/Projects'
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by goanpeca** [comment]
Thanks for the report @selahlynch 

It seems you are using Spyder version 3. Spyder version 4 has been released for a few months now.

Could you update it and check if the problem persists?

Cheers!

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by selahlynch** [comment]
FYI - I haven't been able to reproduce this error either before or after upgrading.

**Comment by ccordoba12** [comment]
Ok, closing then. Thanks for letting us know about it.
