### ISSUE TITLE
Scrolling down in IPython Console isn't easy during code execution

### ISSUE THREAD

**Issue by andreamoro-git** [spyder-ide/spyder#12553]
During code execution, if I scroll up, the visualization sticks (properly) to the scrolled up location. However, there is no quick shortcut for going to the bottom of the output, which may have increased a lot in the meantime. I have to manually pull down the scrollbar, whereas a quick shortcut (ctrl-down for example) should do the trick. 

related to #3504

**Comment by goanpeca** [comment]
Thanks for the suggestion @andreamoro-git ! Indeed, these can be annoying. Would you be interested in giving as a hand? That could speed things up.

Cheers

**Comment by Akashtyagi08** [comment]
This sounds a good handy shortcut. I will love to take a look at this @goanpeca . 
Though I am not sure I understand the codebase completely, some help would be appreciated.

**Comment by ccordoba12** [comment]
Hey @Akashtyagi08, thanks for your interest in helping us with this issue. I think this feature needs to be added to the project we rely on for our IPython console:

https://github.com/jupyter/qtconsole
