### ISSUE TITLE
Spyder not detecting installed libraries in virtualenv, but showing in pip freeze

### ISSUE THREAD

**Issue by waageesh** [spyder-ide/spyder#12552]
Hi @ccordoba12  , 
I am getting same Error in Spyder Ipython console.
I have installed Spyder using PIP and created a virtualenvironment and istalled sklearn , pandas, numpy, Django and django_restframework in virtualenv,
I have checked python versions in virtualenv created by runing query

> `python -c  "import sys;print(sys.executable)"`
> `C:\Users\Jyothi\AppData\Local\Programs\Python\Python38-32\Scripts\spyder3.exe`

it gives python console that is being run in the environment
now i opened spyder and changed the default spyder's python console to above python.exe in virtual environment as below

> Preferences > Python Interpreter > Use the following interpreter

Later checked what all libraries are available in spyder now using 
`pip freeze.`
```
asgiref==3.2.7Note: you may need to restart the kernel to use updated packages.
backcall==0.1.0
cloudpickle==1.4.1
colorama==0.4.3
decorator==4.4.2
Django==3.0.5

djangorestframework==3.11.0
gunicorn==20.0.4
ipykernel==5.2.1
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.17.0
joblib==0.14.1
jupyter-client==6.1.3
jupyter-core==4.6.3
numpy==1.18.3
parso==0.7.0
pickleshare==0.7.5
prompt-toolkit==3.0.5
psycopg2==2.8.4
Pygments==2.6.1
python-dateutil==2.8.1
pytz==2019.3
pywin32==227
pyzmq==19.0.0
scikit-learn==0.22.2.post1
scipy==1.4.1
six==1.14.0
sklearn==0.0
spyder-kernels==1.9.0
sqlparse==0.3.1
tornado==6.0.4
traitlets==4.3.3
wcwidth==0.1.9
```
packages and libraries i have installed in my virtual environment are all available in Spyder Ipython console
when i checked 
`import pandas as pd`
`Traceback (most recent call last):`
`  File "<ipython-input-1-7dd3504c366f>", line 1, in <module>`
`ModuleNotFoundError: No module named 'pandas'`

I have even restarted the kernel multiple time, still the same error

How to run/open spyder with created virtualenv in django ?
please help me

![image](https://user-images.githubusercontent.com/16902073/80726214-bf6d1480-8b21-11ea-93a0-4a877137f808.png)

![image](https://user-images.githubusercontent.com/16902073/80726423-fba07500-8b21-11ea-9238-ffd9ffbbc043.png)

![image](https://user-images.githubusercontent.com/16902073/80726422-fba07500-8b21-11ea-94fb-f5db0fd0ecb3.png)

_Originally posted by @waageesh in https://github.com/spyder-ide/spyder/issues/7867#issuecomment-621912972_

**Comment by waageesh** [comment]
Issue has been solved,
I thought Pandas would be installed along with sklearn when we install
`pip install sklearn`
I installed pandas again and its working now in spyder

**Comment by Nakkhatra** [comment]
Hi, I have all the required libraries (i.e.: tensorflow) installed via pip in my virtual environment. But it is not being loaded and showing the same error and not importing tensorflow even though I can see it installed in pip list

**Comment by waageesh** [comment]
> Hi, I have all the required libraries (i.e.: tensorflow) installed via pip in my virtual environment. But it is not being loaded and showing the same error and not importing tensorflow even though I can see it installed in pip list

Try `pip install tensorflow` in spyder console itself, and try importing tensorflow

**Comment by Nakkhatra** [comment]
Hi, I actually did pip install tensorflow at the first place. Anyways, it works fine now, but for some unknown reason I couldn't find tensorflow installed in my new environment this time. So I reinstalled using pip, now it's working fine.
