### ISSUE TITLE
Intended behaviour of add_pathlist_to_PYTHONPATH not clear

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#12564]
What is the intended behaviour is of the function `add_pathlist_to_PYTHONPATH()` in `spyder.utils.misc`? That function is used in the unittest plugin, but I'm not sure what it is supposed to do and whether it is used correctly in the plugin.

This is prompted by the following comment in PR spyder-ide/spyder-unittest#150 (but I remember that I was puzzled by this in the past):

> I'm not sure if this isn't a logic flaw in [`add_pathlist_to_PYTHONPATH`](https://github.com/spyder-ide/spyder/blob/e2db403d7a4a97690114f20da78e144ece3eeca6/spyder/utils/misc.py#L226): I think if `ipyconsole` is `False` it should look for `PYTHONPATH` not in the actual OS environment but in the passed-in `env` list.

This function is ten years old and added in commit eeb594aec07ac6d854177179fcf226febd3379e3 by Pierre.

**Comment by goanpeca** [comment]
@ccordoba12 may know better. 

@jitseniesen you think we are better off with removing that code? Anywhere else you think a cleaning up is called for ?

**Comment by jitseniesen** [comment]
> you think we are better off with removing that code?

I don't know, in the unittest plugin it turned out that it was actually cleaner not to use the function, but it's probably used differently in other places. It feels like the function grew in a bit of a monster with a hidden dependency on the OS environment, but changing code we (no longer) fully understand is inherently risky, so it depends on how much Carlos can reconstruct on what the code is supposed to do.

**Comment by ccordoba12** [comment]
That function was quite messy. I simplified it and added a docstring and test for it in PR #14022.

**Comment by jitseniesen** [comment]
It looks much better now, thanks!

**Comment by ccordoba12** [comment]
Great! I think the original intent of that function was the one I left in PR #14022.

The problem is I hijacked it to use it in our kernelspec several years ago.
