### ISSUE TITLE
Go To Definition stops working shortly after startup

### ISSUE THREAD

**Issue by rwijtvliet** [spyder-ide/spyder#12565]
### What steps will reproduce the problem?

Whenever I start Spyder, the Go To Definition functionality works (`ctrl-g` or `ctrl`-click or from the context menu). However, very soon afterwards (~1 min), it consistently breaks, and nothing happens using the shortcut.
 
I suppose it is due to a component being loaded, but I don't know how to further isolate it. I've followed the steps [here](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#recommended-troubleshooting-steps) to resolve, but to no avail. 

Be sure to ask me for any logs or further information if necessary. 

Many thanks

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-7648-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.18.0 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
Hi @randallpittman thanks for the bug report.

To debug Spyder and provide us with some additional logs please follow the steps described in 

https://github.com/spyder-ide/spyder/wiki/Frequently-asked-questions#how-to-debug-spyder

Thanks!

**Comment by mrclary** [comment]
@rwijtvliet , have you tried restarting the LSP server from the statusbar? Will this restore the proper behavior, even if only temporarily?

**Comment by rwijtvliet** [comment]
I just tried that and yes indeed, it does restore correct behaviour.

**Comment by goanpeca** [comment]
@rwijtvliet issues with the LSP are being track on other issues but you could help us a lot if you could provide information with logs

See: https://github.com/spyder-ide/spyder/wiki/Frequently-asked-questions#how-to-debug-spyder

If you start Spyder in that mode (debug mode) you can work for a while and if you noticed the LSP stopped working then you can send us the logs and we can check and see what might be the cause.

Thanks
