### ISSUE TITLE
Variable Explorer very slow with large dataframe

### ISSUE THREAD

**Issue by Skullnick** [spyder-ide/spyder#12575]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Variable Explorer is extremely slow in a dataframe containing 30k+ rows.
It's nearly nstantaneous in Spyder 3.3.3.
Scrolling is extremely laggy, window freezes frequently.

### What steps reproduce the problem?

Run the code following:
```
import pandas as pd
import numpy as np
from datetime import datetime

bdates = pd.bdate_range(start = datetime(1900, 1, 1), end = datetime.today())
vect_random = np.random.normal(size=len(bdates))
df = pd.DataFrame(vect_random, index = bdates)
```

And open the df variable in the Variable Explorer, and scroll.

### What is the expected output? What do you see instead?

Should be as fast to open and scroll as in 3.3.3

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by goanpeca** [comment]
Hi @Skullnick, thanks for the report.

I can confirm that this is indeed an issue with the provided example. The scrolling is really slow.

**Comment by goanpeca** [comment]
Hi @dalthviz it seems we have some performance degradation. Please take a look at this one to see what might be caiusing the slowdowns.

**Comment by dalthviz** [comment]
Note: Seems like the problem is the handling of the datetime index. With a numeric index no performance degradation is experienced (even testing with more than 30k rows):

No degradation case:
```python
import pandas as pd
import numpy as np

bdates = range(50000)
vect_random = np.random.normal(size=len(bdates))
df = pd.DataFrame(vect_random, index = bdates)
```

**Comment by goanpeca** [comment]
Indeed @dalthviz it is the conversion we are doing to the datetime index.

**Comment by ccordoba12** [comment]
> Note: Seems like the problem is the handling of the datetime index

How is this conversion performed?

**Comment by goanpeca** [comment]
See: https://github.com/spyder-ide/spyder/pull/11210
