### ISSUE TITLE
Support for jedi 0.17.0

### ISSUE THREAD

**Issue by ritesh024** [spyder-ide/spyder#12572]
## Problem Description
I am running spyder 4.1.2 and the only version of jedi it supports is 0.15.2 but I have 0.16.0 installed on my system. Since spyder doesn't support the latest version of jedi I get the dependency error when I launch spyder. I guess the autocomplete feature is also not working because of it.
I want to know if I need to downgrade the version of jedi or is it possible to support the latest version of jedi in spyder 4.1.2.

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.16.0 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.6.2 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.2 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

```
PASTE DEPENDENCIES HERE
```

**Comment by bnavigator** [comment]
See https://github.com/spyder-ide/spyder/issues/11975 and https://github.com/palantir/python-language-server/pull/781

**Comment by ritesh024** [comment]
@bnavigator Thanks for your reply. I changed the dependencies to not have spyder pinned to a single version of jedi and spyder ran without throwing any warnings. 
my autocomplete is still not working for some reason. neither the tab nor the ctrl+space is working for autocompletition.

**Comment by bnavigator** [comment]
That's because PyLS does not fully work with the newer Jedi without the patches. You need to patch it yourself (Only use the patch up to https://github.com/palantir/python-language-server/pull/781/commits/afafa62b680a7f4762937b956bc2fee57126c56d if you really need to use Jedi 0.16 instead of 0.17) or wait until that PR is finally accepted and released. Afterwards, spyder likely also needs some fixes. I am already seeing deprecation warnings related to Jedi in my test runs with a patched PyLS.

**Comment by ccordoba12** [comment]
> I am running spyder 4.1.2 and the only version of jedi it supports is 0.15.2 but I have 0.16.0 installed on my system

Jedi 0.16.0 is broken for Pandas. We're going to aim at supporting Jedi 0.17.0 in our 4.1.4 version, to be released at the end May (most probably).

> I guess the autocomplete feature is also not working because of it

That's not the reason. You need to have Jedi 0.15.2 and Parso 0.5.2 installed for things to work correctly.

> I want to know if I need to downgrade the version of jedi

Yes, you need to, and also your Parso version, as I said above.

> is it possible to support the latest version of jedi in spyder 4.1.2.

That's basically not possible, unless you're very knowledgeable about our dependencies and how they work among them. And even if you manage to sort out all issues with them (as @bnavigator was suggesting above), you could get dependency errors (not generated by Spyder but by other packages) at runtime.

**Comment by bnavigator** [comment]
@ritesh024 yes it is possible, you just won't get any help from @ccordoba12.

**Comment by ccordoba12** [comment]
> unless you're very knowledgeable about our dependencies and how they work among them

That's why I clearly said *unless* above. Please don't try to start an out-of-place discussion here with your comments.

**Comment by bnavigator** [comment]
Then stop stating wrong facts. He does not need to downgrade to things to work correctly.

BTW, next IPython will require Jedi >=0.16 https://github.com/ipython/ipython/pull/12207, so why not pin that too while you are at it.

**Comment by ccordoba12** [comment]
> He does not need to downgrade to things to work correctly.

He does *unless* @ritesh024 is an expert on how our entire code completion machinery works. I really don't understand why you keep pushing with this (as I said, it seems you'd want to start a discussion about it).

> BTW, next IPython will require Jedi >=0.16 ipython/ipython#12207, so why not pin that too while you are at it.

Thanks for letting me about it! Sure will do in our next release.

**Comment by bnavigator** [comment]
> Sure will do in our next release.

And completely unnecessary, if you just would accept the pending and reviewed PR in PyLS.

**Comment by ritesh024** [comment]
I have always used notepad++ or jupyter notebooks for my python related needs, this is my first time trying to use an IDE for python. I didn't know there would be so many dependencies an IDE has to obey for it to function normally. I'll just wait for the new version of Spyder. Thanks for the replies.

**Comment by ccordoba12** [comment]
Thanks for understanding @ritesh024!
