### ISSUE TITLE
Spyder 4.1.2 won't launch after updates may 2th, 2020

### ISSUE THREAD

**Issue by cpkc** [spyder-ide/spyder#12579]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I was unable to launch spyder 4.1.2 even from Anaconda Navigator (Windows 10 and XUbuntu)

### What steps reproduce the problem?

1. start spyder
2. 
3. 

### What is the expected output? What do you see instead?
Open spyder normally, splash screen starts then crashs suddenly.

### Paste Traceback/Error Below (if applicable)

```python-traceback

....
 import toml
ModuleNotFoundError: No module named 'toml'
....

```

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 and XUbuntu

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by cpkc** [comment]
I solved the problem with (Windows 10):
conda install toml

**Comment by dovsay** [comment]
@cpkc   it works,thank you!

**Comment by gkvallis** [comment]
I also had this problem on a Mac with OS X. Similarly, 'conda install toml' solved the problem.

**Comment by goanpeca** [comment]
Hi @cpkc and others. Indeed this is an issue with the latest pylint package release by Anaconda.

We have reported the issue already on this PR https://github.com/conda-forge/pylint-feedstock/pull/42

We have to wait for Anaconda to make the fix to see the problem go away. In the meantime the manual fix is to install the `toml` package as suggested by others.


```
conda install toml
```
