### ISSUE TITLE
I am getting error in renaming the columns

### ISSUE THREAD

**Issue by Aditya222002** [spyder-ide/spyder#12588]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

CODE:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
url="C:/Users/Lenovo/Desktop/Edited_car1.csv"
car=pd.read_csv(url)
drive_wheels_count=car["drive-wheels"].value_counts()
drive_wheels_count.rename(columns={'drive-wheels':'value_count'},inplace=True)

### What steps reproduce the problem?

1. Retyping the code
2. 
3. 

### What is the expected output? What do you see instead?

The column name should have changed

### Paste Traceback/Error Below (if applicable)

```python-traceback

runfile('C:/Users/Lenovo/.spyder-py3/untitled0.py', wdir='C:/Users/Lenovo/.spyder-py3')
Traceback (most recent call last):

File "C:\Users\Lenovo.spyder-py3\untitled0.py", line 7, in
drive_wheels_count.rename(columns={'drive-wheels':'value_count'},inplace=True)

TypeError: rename() got an unexpected keyword argument 'columns'

```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 7, 64-bit

### Dependencies

```
[
![image](https://user-images.githubusercontent.com/64554000/80918372-386aa700-8d82-11ea-9f0a-e62291e8e4ed.png)
](url)
```

**Comment by goanpeca** [comment]
Hi @Aditya222002, thanks for reporting.

However this issue is not a Spyder related issue. It seems a Pandas issue, or by reading 

`TypeError: rename() got an unexpected keyword argument 'columns'` a problem in how you are using pandas.

Please refer to the pandas documentation or their issue tracker. https://github.com/pandas-dev/pandas

Cheers!
