### ISSUE TITLE
Add keyboard shortcut for restarting Python Language Server

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#12609]
Hi,

I am using version 4.1.2 of Spyder, and the Python Language Server crashes frequently (for me, 1-2 times per day).  The PLS restart functionality of 4.1.2 is good, but is it possible to add a keyboard shortcut to it?

Thanks!

**Comment by steff456** [comment]
Hi @jsh9,

Right now we are not able to restart the Python Language Server without restarting Spyder. So for the moment please restart Spyder when the PLS crashes. We are working on stabilizing the PLS for stopping these type of crashes.

**Comment by jsh9** [comment]
Hi @steff456 , just curious: why does PyLS crash so frequently?  Is it PyLS's issue or Spyder's issue?  Thanks!

**Comment by ccordoba12** [comment]
@jsh9, it's an Spyder issue that happened only on Windows. We already found the error and fixed it in #12771. It'll be part of our next version (4.1.4), to be released in mid June.

If you want the fix right now, please take a look at the changes in #12771 and apply them to your current installation.

**Comment by ccordoba12** [comment]
This shouldn't be necessary due to the improvements we've done to our code completion architecture. However, we'll reevaluate if it's really necessary for 4.2.0.

**Comment by jsh9** [comment]
I think we can close this issue now.  I don't think I have encountered this issue any more in Spyder 5.
