### ISSUE TITLE
Spyder does not start when using external DisplayLink monitors

### ISSUE THREAD

**Issue by b-a0** [spyder-ide/spyder#12601]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Whenever my two DisplayLink monitors are attached to my mid 2015 MacBook Pro, Spyder does not start.
When I run `conda activate my_env` and then `spyder` an app icon titled `python` starts bouncing in my dock, but it keeps bouncing without any window opening. No output is written to the terminal.

## Results from following Troubleshooting Guide

* Possible related issues:
  * #6368: But that issue was with WinPython, I don't use that.
  * #7369: There Spyder did start and the issue was resolved by toggling fullscreen
* Check if `jupyter qtconsole` runs: It does and can plot figures.
* Starting Spyder via different means: tried Terminal and Anaconda Navigator. Same issue.
* Start Spyder as administrator: Same issue.
* run `start.py` manually: I've run below code, but Spyder does not start.
```bash
conda activate my_env
python /Users/username/opt/anaconda3/pkgs/spyder-4.1.2-py37hc8dfbb8_0/lib/python3.7/site-packages/spyder/app/start.py
```
No output until interrupted by keyboard:

```text
^CTraceback (most recent call last):
  File "/Users/username/opt/anaconda3/pkgs/spyder-4.1.2-py37hc8dfbb8_0/lib/python3.7/site-packages/spyder/app/start.py", line 223, in <module>
    main()
  File "/Users/username/opt/anaconda3/pkgs/spyder-4.1.2-py37hc8dfbb8_0/lib/python3.7/site-packages/spyder/app/start.py", line 201, in main
    from spyder.app import mainwindow
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 125, in <module>
    MAIN_APP = qapplication()
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 93, in qapplication
    app = SpyderApplication(['Spyder'])
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 621, in __init__
    QApplication.__init__(self, *args)
KeyboardInterrupt
```
* run `mainwindow.py` manually. I've run below command, but Spyder does not start.
```bash
conda activate my_env
python /Users/username/opt/anaconda3/pkgs/spyder-4.1.2-py37hc8dfbb8_0/lib/python3.7/site-packages/spyder/app/mainwindow.py 
```

No output until interrupted by keyboard:

```text
^CTraceback (most recent call last):
  File "/Users/username/opt/anaconda3/pkgs/spyder-4.1.2-py37hc8dfbb8_0/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 125, in <module>
    MAIN_APP = qapplication()
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 93, in qapplication
    app = SpyderApplication(['Spyder'])
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 621, in __init__
    QApplication.__init__(self, *args)
KeyboardInterrupt
```

### What steps reproduce the problem?

1. Create a new environment `conda create --name my_env python=3.7`
2. Activate the new environment `conda activate my_env`
2. Install spyder with `conda install spyder=4.1.2`
3. Connect the DisplayLink monitors via USB
3. Run `spyder` (or open the environment in Anaconda Navigator and open Spyder there).

### What is the expected output? What do you see instead?

**Expected**: A Spyder icon starts bouncing in the dock, the splashscreen shows and Spyder opens after a few seconds. This happens whenever the DisplayLink monitor is not connected.

**Actual result**: An app icon titled `python` starts bouncing in my dock, but it keeps bouncing without any window opening. No output is written to the terminal.
When I press <kbd>CTRL</kbd>+<kbd>C</kbd> to terminate it I get the following output:

```text
^CTraceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/felyx/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/app/start.py", line 201, in main
    from spyder.app import mainwindow
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 125, in <module>
    MAIN_APP = qapplication()
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 93, in qapplication
    app = SpyderApplication(['Spyder'])
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 621, in __init__
    QApplication.__init__(self, *args)
KeyboardInterrupt
```

**Workaround**: Shut down MacBook Pro, unplug DisplayLink USB, open MacBook Pro, start machine (restart needed otherwise DisplayLink does not enable the built-in screen). Start Spyder and wait until it has fully loaded. Then plugin the DisplayLink USB, close lid of MacBook Pro.

### Paste Traceback/Error Below (if applicable)

```python-traceback

No traceback as Spyder does not open.

```

## Versions

* Spyder version: 4.1.2 build py37_0
* Python version: 3.7.7 build hc70fcce_0_cpython
* Qt version: 5.9.7 build h468cd18_1
* PyQt version: 5.9.2 build py37h655552a_2
* Operating System name/version: macOS Catalina 10.15.4

### Dependencies

```
Cannot do that as Spyder does not start.
```

**Comment by goanpeca** [comment]
Hi @b-a0 thanks for your report.

Could you start Spyder in debug mode, see https://github.com/spyder-ide/spyder/wiki/Frequently-asked-questions#how-to-debug-spyder

And provide the info.

Thanks!

**Comment by b-a0** [comment]
Hi,

Thanks for the suggestion.

I did `conda activate my_env` and then `spyder --debug-info verbose --debug-output file` but the same happened. Icon kept bouncing. No file was created.

When I interrupted with <kbd>CTRL</kbd>+<kbd>C</kbd> I got:

```text
^CTraceback (most recent call last):
  File "/Users/username/opt/anaconda3/envs/felyx/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/app/start.py", line 201, in main
    from spyder.app import mainwindow
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 125, in <module>
    MAIN_APP = qapplication()
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 93, in qapplication
    app = SpyderApplication(['Spyder'])
  File "/Users/username/opt/anaconda3/envs/felyx/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 621, in __init__
    QApplication.__init__(self, *args)
KeyboardInterrupt
```

**Comment by goanpeca** [comment]
Could you share the debug file that was created?

**Comment by b-a0** [comment]
No debug file was created.

**Comment by goanpeca** [comment]
Could you try looking for this line https://github.com/spyder-ide/spyder/blob/v4.1.2/spyder/plugins/console/widgets/internalshell.py#L169 and comment it and then try to launch it again (in the terminal) and see if some error or traceback gets printed?

**Comment by b-a0** [comment]
Thanks for bearing with me.

I've commented out line `169` (`self.start_interpreter(namespace)`) in the file `/Users/username/opt/anaconda3/pkgs/spyder-4.1.2-py37hc8dfbb8_0/lib/python3.7/site-packages/spyder/plugins/console/widgets/internalshell.py`.

* Running `spyder` has the same issue. Bouncing icon, nothing else. On keyboard interrupt it gives the same traceback as before.
* Same with `spyder --debug-info verbose --debug-output file`. No debug file is written.

**Comment by goanpeca** [comment]
>Thanks for bearing with me.

@b-a0 hmmm this is a though cookie! Hardware issues are hard to debug since they are specific to the hardware sometimes. Do you have the reference of your monitor, so maybe I can look into similar issues on the web?

Sorry I cannot provide more help at the moment!

**Comment by b-a0** [comment]
I have two [PHILIPS 241B7QUPEB](https://www.philips.co.uk/c-p/241B7QUPEB_00/brilliance-usb-docking-lcd-monitor) monitors.   
I've installed this driver from DisplayLink: [DisplayLink USB Graphics Software for macOS](https://www.displaylink.com/downloads/macos) version 5.2.1

Same monitors with a Windows laptop in clamshell mode do launch Spyder, not sure if that helps narrowing down the problem.

**Comment by goanpeca** [comment]
I have seen some reports on Qt Bug tracker and issues like [this](https://github.com/DisplayLink/evdi/issues/82#issue-210745725)

Sorry I do not have a better answer. 

Could you create a new environment using conda forge and check if that works for you?

The Qt is different so maybe we can see if that is solved with the different Qt version :shrug: ?

```
conda create -n spy-forge python=3.7 spyder=4.1.2 toml -c conda-forge
```

Cheers!

**Comment by b-a0** [comment]
Thanks for finding that other issue. Seems very much like mine.
I tried creating a new environment as you suggested, but when launching Spyder the result is the same: bouncing icon, no window *but* the traceback now has a new line prepended:

```trace
qt.qpa.openglcontext: Could not find virtual screen for QCocoaScreen(0x7f9020c73fa0, index=0, native=<NSScreen: 0x7f9020b12ed0>, geometry=QRect(0,0 1920x1080), dpr=1, name="PHL 241B7Q") with displayId 1124254485
```
which is followed by the old traceback:
```trace
Traceback (most recent call last):
  File "/Users/ba/opt/anaconda3/envs/spy-forge/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/ba/opt/anaconda3/envs/spy-forge/lib/python3.7/site-packages/spyder/app/start.py", line 201, in main
    from spyder.app import mainwindow
  File "/Users/ba/opt/anaconda3/envs/spy-forge/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 125, in <module>
    MAIN_APP = qapplication()
  File "/Users/ba/opt/anaconda3/envs/spy-forge/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 93, in qapplication
    app = SpyderApplication(['Spyder'])
  File "/Users/ba/opt/anaconda3/envs/spy-forge/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 621, in __init__
    QApplication.__init__(self, *args)
KeyboardInterrupt
```
When I google `Could not find virtual screen for` I only find it referenced in the [code of qt](https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/cocoa/qcocoaglcontext.mm#n301).
Unfortunately I can't read C++, so I'm not sure what the underlying issue for this warning is.

**Comment by goanpeca** [comment]
Awesome this is some progress. I will take a look :-)

**Comment by goanpeca** [comment]
Also related https://bugreports.qt.io/browse/QTBUG-77656

It seems like a Qt bug on Mac and it does not seem to be fixed on the latest one, so yeah :-\

**Comment by ccordoba12** [comment]
@goanpeca, should we close this one? Or leave it open for future reference?

**Comment by goanpeca** [comment]
We should leave open and see if Qt 5.15 fixes it.

**Comment by b-a0** [comment]
Thank you for investigating this issue down to the source.

For future visitors: below a workaround until this is fixed in Qt.
It involves using the DisplayLink Beta drivers and fiddling with the display settings of your macbook. Tested on Catalina 10.15.4 with a mid 2015 macbook pro.

1. Uninstall the stable 5.X.X DisplayLink drivers. To do this [download the latest official driver](https://www.displaylink.com/downloads/macos) and use the provided uninstaller (it requires a restart).
2. Download and install [the beta DisplayLink driver](https://www.displaylink.com/downloads/macos) (0.5 at time of writing).
3. If you use the internal screen next to the external displaylink screens you're now done: start Spyder as you normally would (via the command line or anaconda navigator).
4. If you are used to clamshell mode: open display settings, and mirror the internal screen with external screen. If you have more than 1 external screen, [here's an explanation how you can only mirror one specific screen](https://create.pro/how-to-mirror-specific-displays-in-os-x-mirror-some-but-not-all-of-your-monitors-on-an-apple-system/).
5. Dim the internal screen, put the macbook aside and semi-close the lid.

Apparently the lack of clamshell mode is a shortcoming of the beta drivers. When you close the lid, everything goes to sleep.
With steps 4 and 5 I effectively have "clamshell mode" with the lid slightly open.

**Comment by b-a0** [comment]
Currently on macOS 12.3.1, DisplayLink drivers 1.6.1 (build 59.135) and Spyder 5.3.0.
The issue seems fixed, I can start Spyder while my laptop is in clamshell mode and has two DisplayLink displays connected without any problem.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
