### ISSUE TITLE
Virtual explorer doesn't show DataFrame values.

### ISSUE THREAD

**Issue by SamAct** [spyder-ide/spyder#12605]
Virtual explorer failed to show the DataFrame values.
To replicate this you may:
import numpy as np
import pandas as pd

x=np.loadtxt(some_text_file)
a=pd.DataFrame(x)

I am sure it is a part of other issues, you may add this to the list of Virtual Explorer issues.

**Comment by goanpeca** [comment]
@SamAct, thanks for reporting.

Could you provide us the contents of `some_text_file`, some minimal example that reproduces the behavior.

Also you mentioned: `failed to show the DataFrame values.`. What do you mean by `failed`did you get an error traceback?

Please post an animation of the behavior using https://www.cockos.com/licecap/ or similar.

Cheers

**Comment by SamAct** [comment]
Closing this as i couldn't replicate it.
