### ISSUE TITLE
Spyder The completion and syntax checking functions of Python files in the editor cannot work in the current session, or will stop working.

### ISSUE THREAD

**Issue by Supltz** [spyder-ide/spyder#12628]
### What steps will reproduce the problem?

To fix this, make sure that the firewall or virus protection software in your operating system allows the python process to open the port, or try restarting Spyder

I have already check my firewall and it does not block any python process file.
Plus,I don't have any virus protection software on my computer.

## Versions

* Spyder version: 4.0.0 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  0.4.0 (NOK)
pygments >=2.0               :  2.5.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  1.6.3 (OK)
pylint >=0.25                :  1.7.2 (OK)
psutil >=0.3                 :  5.4.5 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  17.0.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.7.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  unknown (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.12.0 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
numpy >=1.7                  :  1.18.2 (OK)
scipy >=0.17.0               :  1.3.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
```

**Comment by Supltz** [comment]
![image](https://user-images.githubusercontent.com/60577034/81176628-f9359380-8fd7-11ea-85f3-50c0d1685d8a.png)
translation:
error
The completion and syntax checking functions of Python files in the editor cannot work in the current session, or will stop working.

To fix this, make sure that the firewall or virus protection software in your operating system allows the python process to open the port, or try restarting Spyder

**Comment by Supltz** [comment]
win10 firewall infomation:
![image](https://user-images.githubusercontent.com/60577034/81176948-7cef8000-8fd8-11ea-9300-9bc5bd475042.png)

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=4.1.2
