### ISSUE TITLE
Console does not add up shows below runfile

### ISSUE THREAD

**Issue by satishiyer** [spyder-ide/spyder#12626]
a = 10
b = 10
a+b

runfile('C:/Users/Satish Iyer/.spyder-py3/temp.py', wdir='C:/Users/Satish Iyer/.spyder-py3')

**Comment by jitseniesen** [comment]
Hello @satishiyer . This is how Python works, scripts that you run do not display any results unless you tell them to. If you replace the line `a+b` with `print(a+b)`, you should see the result.
