### ISSUE TITLE
An error ocurred while starting the kernel in spyder 4.1.2, python 3.8

### ISSUE THREAD

**Issue by chandu8542** [spyder-ide/spyder#12621]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.0 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels

I installed spyder 4.1.2 using pip and spyder kernel is 1.9.0. But still it says error starting the kernel. I tried to uninstall kernel and then re-install using pip but error persists.

Successfully installed spyder-kernels-1.9.0
Python 3.8.2 64-bit | Qt 5.12.8 | PyQt5 5.12.3 | Linux 4.15.0-96-generic

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> I installed spyder 4.1.2 using pip and spyder kernel is 1.9.0

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by chandu8542** [comment]
Hi Carlos,
I'm not sure if the issue was due to custom installation but `spyder --reset` did the work and now it's working.

**Comment by ccordoba12** [comment]
Glad to know!

**Comment by ehsanrs2** [comment]
update to new version, its work for me
`conda install spyder=4.1.5`
