### ISSUE TITLE
Feature Request: --safe-mode in spyder main cli options

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#12631]
Safe mode is currently implemented in bootstrap.py as a convenient way to help developers to trouble shoot development issues. Safe mode opens Spyder with default settings and temporary config directory that is removed when it is closed.

This would also be a great for uses diagnosing configuration and installation issues. We also wouldn't need to suggest users need to --reset Spyder when submitting a bug. Most users wouldn't want to loose their configurations when submitting a bug.

**Comment by dalthviz** [comment]
Hi @bcolsen that sounds good to me :+1: (needing to reset config can be quite excessive and sometimes it doesn't even help to make Spyder work again). Probably if we change this we will need to update the FAQ/trouble shooting guide and also the issue template.

@spyder-ide/core-developers what do you guys think?

**Comment by ccordoba12** [comment]
I agree with this. @dalthviz, since you're a senior dev, please decide who among our junior ones (Stephannie or Juanita) is going to implement this and add this issue to 4.1.4.

**Comment by dalthviz** [comment]
Hi @juanis2112 , please check this one. I think the relevant files were changes need to be done are:
* `...\spyder\bootstrap.py` - Remove the argument and logic of the option:
     * https://github.com/spyder-ide/spyder/blob/833de4b928a5d2b28422d2c56a08e9217af6ad2a/bootstrap.py#L55-L57
     * https://github.com/spyder-ide/spyder/blob/833de4b928a5d2b28422d2c56a08e9217af6ad2a/bootstrap.py#L249-L255
* `...\spyder\spyder\app\cli_options.py` - Add the argument of the option (probably before the `--report-segfault`):
     * https://github.com/spyder-ide/spyder/blob/833de4b928a5d2b28422d2c56a08e9217af6ad2a/spyder/app/cli_options.py#L124-L133
* `...\spyder\spyder\app\mainwindow.py` - Add the logic to handle the argument (which should be similar to what we are doing in `bootstrap.py`, and should be added before the `show_console` option or `reset` option handling done in this file):
     * https://github.com/spyder-ide/spyder/blob/833de4b928a5d2b28422d2c56a08e9217af6ad2a/spyder/app/mainwindow.py#L3691-L3710
