### ISSUE TITLE
clicked on Read our tutorial and got the Issue reporter - Spyder has encountered and internal problem!

### ISSUE THREAD

**Issue by MikeD-Respond** [spyder-ide/spyder#12634]
### What steps will reproduce the problem?

Opened Spyder
was prompted to get latest update 
Did that using 

returned to Spyder and clicked on "tutorial" in the Usage dialog box New to Spyder? Read our tutorial

then got this internal error, issue reporter

### Traceback
```python-traceback
  File "C:\Apps\Anaconda\lib\site-packages\spyder\plugins\help.py", line 752, in handle_link_clicks
  File "C:\Apps\Anaconda\lib\site-packages\spyder\plugins\help.py", line 746, in show_tutorial
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Apps\\Anaconda\\lib\\site-packages\\spyder\\utils\\help\\tutorial.rst'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @MikeD-Respond after updating, did you restart Spyder? Also, what command did you use to update Spyder? (seems like the command is missing in the issue description). Thank you for the feedback!

**Comment by dalthviz** [comment]
Closing due to lack of response.
