### ISSUE TITLE
Please on Anaconda Prompt, run there

### ISSUE THREAD

**Issue by AnanyBahekar28** [spyder-ide/spyder#12647]
Please on Anaconda Prompt, run there

    conda install -f spyder-kernels=0.3

and try again.

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/8581#issuecomment-454413857_

**Comment by andfoy** [comment]
@AnanyBahekar28 Thanks for opening this issue, however, it is not clear which is your problem. Could you please include more information about it? Otherwise, we will be obliged to close it.

**Comment by andfoy** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.
Thanks for reporting!
