### ISSUE TITLE
Spyder 4.1.2 wont get past splash screen Windows 10

### ISSUE THREAD

**Issue by jaray200** [spyder-ide/spyder#12652]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The other day I was unable to start Spyder 4.1.2 after not having used Anaconda in a while and updating all packages.  Running spyder in my environment loaded the splash screen, but it was replaced with a dialog box that says, "Spyder was unable to load the Spyder 3 icon theme.  That's why it's going to fallback to the theme used in Spyder 2.

For that, please close this window and start Spyder again."

So I did just that.  This time the splash screen came up (says Spyder 4)and got to where it says "Setting up Main Window."  Here it hangs and never gets past.  The only way to close this is to force quit it.  

I followed another Issue on here where someone said they had luck with uninstalling with anaconda-clean, uninstalling, removing registry entries, and deleting any folders that remained.  I tried this and reinstalled.  The first thing I did here was update conda with conda update conda, followed by conda update --all, followed by creating a new environment where the first thing installed was spyder.  

Running spyder this time did the same thing starting with the icon pack issue.  

### What steps reproduce the problem?

1.  Create a new environment
2. Update standard packages
3. Install spyder
4. Try to open

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.2
* Python version: 3.8.2
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 10.0.18362

### Dependencies

```
[package.txt](https://github.com/spyder-ide/spyder/files/4596003/package.txt)

PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @jaray200 , from the description posted above, it seems that you have a broken installation of Anaconda. Did you installed packages using pip?

**Comment by jaray200** [comment]
Good evening @andfoy ,

Based on other issues I thought that could be the issue.  I used pip on a previous environment.  Based on advice from the other issues, I have completely reinstalled anaconda multiple times.  I've tried to remove any trace, but maybe there is something still hanging around.

**Comment by andfoy** [comment]
> I have completely reinstalled anaconda multiple times. I've tried to remove any trace, but maybe there is something still hanging around.

Have you tried to install miniconda? Or using a clean environment?

**Comment by ccordoba12** [comment]
Please remove this directory (if present in your system)

    C:\Users\<your user>\AppData\Roaming\Python\

And also try to remove the directory where you installed Anaconda.

One of those two options should solve your problem.

**Comment by andfoy** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.
Thanks for reporting!
