### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by sontakkeshweta** [spyder-ide/spyder#12650]
### What steps will reproduce the problem?

Step 1. Launch spyder

error:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\palas\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\palas\anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\palas\anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\palas\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 287, in main
import_spydercustomize()
File "C:\Users\palas\anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\palas\anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 24, in 
from IPython.core.getipython import get_ipython
File "C:\Users\palas\anaconda3\lib\site‑packages\IPython\__init__.py", line 55, in 
from .core.application import Application
File "C:\Users\palas\anaconda3\lib\site‑packages\IPython\core\application.py", line 23, in 
from traitlets.config.application import Application, catch_config_error
File "C:\Users\palas\anaconda3\lib\site‑packages\traitlets\config\__init__.py", line 6, in 
from .application import *
File "C:\Users\palas\anaconda3\lib\site‑packages\traitlets\config\application.py", line 17, in 
from decorator import decorator
ImportError: cannot import name 'decorator' from 'decorator' (C:\Users\palas\decorator.py)

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by andfoy** [comment]
Hi, @sontakkeshweta, thanks for reporting this issue. According to the stacktrace posted previously, it seems that there is a downstream error on some of the libraries on which Spyder is dependent on. This error may happen due to version incompatibility and also old versions. Also, you are using Spyder 4.0.1, right now the latest version is 4.1.2, so I would recommend you to upgrade and verify that the error does appear again.

**Comment by sontakkeshweta** [comment]
Hi @andfoy, 
Greetings!! 
I updated the Spyder, but the error is still there.

**Comment by bcolsen** [comment]
```
File "C:\Users\palas\anaconda3\lib\site‑packages\traitlets\config\application.py", line 17, in
from decorator import decorator
ImportError: cannot import name 'decorator' from 'decorator' (C:\Users\palas\decorator.py)
```

This part of the error says that traitlets is trying to import decorator from a file in your user directory (C:\Users\palas\decorator.py). You need to remove or rename that file.

**Comment by ccordoba12** [comment]
@andfoy, please take note of @bcolsen's advice so you can give this feedback again next time (this is a very common problem).
