### ISSUE TITLE
Segmentation fault just after startup

### ISSUE THREAD

**Issue by agentmorris** [spyder-ide/spyder#12660]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [n/a] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [n/a] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder starts, the IDE shows briefly, then Spyder segv's and closes 3-5 seconds later, before the kernel finishes starting.  No information is reported at the console other than:

`Segmentation fault (core dumped)`

I can run qtconsole from the command line (i.e., jupyter qtconsole), and it starts normally.

`spyder --reset` runs (including the splash screen) and terminates normally.

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version:  5.6.0
* PyQt version: 5.6.3
* Operating System name/version: Ubuntu 16.04 

Qt and PyQt were rolled back to 5.6.* in this case from the current 5.9 versions because of the "Could not initialize GLX" error.  I don't <i>think</i> this is related to the present issue, since the IDE shows for a few seconds before the segv in this case.

Let me know what else I can provide to help debug!  Thanks.

**Comment by juanis2112** [comment]
Hi @agentmorris, please try updating your Qt and PyQt versions back to 5.9 and try updating the last drivers of your graphics card. Is it Nvidia?

**Comment by agentmorris** [comment]
Yes, it's Nvidia hardware... before I update the drivers, which will break a few other dependencies on the system (due to other projects with specific CUDA version dependencies), do you think it's reasonably plausible that this is graphics-related, given that the IDE starts up OK and the IDE _looks_ normal (albeit briefly)?  If you say you've seen cases where a driver or qt version issue caused a segv _after_ the IDE successfully rendered for a few seconds, I believe you, and I'll go ahead and try a driver update.  Thanks!

**Comment by CAM-Gerlach** [comment]
@agentmorris Thanks for your very detailed and considerate response! Based on the information you've provided, it still seems quite plausible, though far from certain, that crashes are GPU/driver related even if Spyder does draw for a few seconds; we have had some reported in the past and your errors may be in fact be related to an underlying issue in your graphics stack, especially given you're on an older Linux distro and the drivers aren't always so stable and with more variables that could potentially trigger an incompatibility. However, given the evident cost and disruption for you to update your drivers, and the fact that (at least in the past) there are a number of other potential causes/solutions, I'd recommend saving that for last.

At least the "failed to initialize GLX" error appears to be [a known one with Ubuntu 16.04 and Nvidia CUDA drivers](https://forums.developer.nvidia.com/t/could-not-initialize-glx-with-nvidia-384-66-on-ubuntu-16-04/53012) that Spyder doesn't have direct control over, that was reported to us before as #5710 . The error also occurs with Qt 5.9 and SSH connections using X11 forwarding, sometimes coupled with a Qt 5.6 segfault (e.g. #7152, and possibly #7447 ,  #11648 ), but I'm not sure if that's relevant to your situation.

As a first step, aside from anything system-level recommended on the Nvidia thread, I'd recommend try starting Spyder with each of the three graphics mode: ``spyder --opengl {software,desktop,gles} under each Qt version (Qt 5 first), and seeing if any combination works for you. This has solved many of the aforementioned issues by working around starting in whichever graphics mode that caused the problem.

Aside from that, more general steps to try:

* Install PyOpenGL with ``conda install pyopengl``
* If you have multiple GPU (e.g. integrated + discrete), or have another you can use, try disabling/forcing one or the other
* Run ``spyder --reset``, just in case. If you value your preferences (e.g. a custom syntax theme or shortcuts), make a copy of the ``spyder-py3`` directory in your user/home folder and restore if it resetting fails to fix the issue.
* If you haven't already, create a new, clean conda environment, and see if the problem still persists:

```
conda create -n spyder-env -c defaults spyder=3 python=3.6
conda activate spyder-env
spyder
```

* If this doesn't work, try create a new environment with `-c conda-forge` instead, to see if their packages (using Qt 5.12?) don't have the issue.

* Consider upgrading your distro and/or GPU drivers

Its also possible you may get some more specific output to help track down the error if you run Spyder with ``spyder --debug-info verbose --debug-output file` and upload for us the `spyder-debug.log` in your current working directory.

Thanks, and best of luck!

**Comment by agentmorris** [comment]
Good news and bad news... 

The good news first: your suggestion to start from a clean conda environment was really a two-for-one: you were also suggesting a rollback to Spyder 3.  When I did this, I hit the GLX issue, which I resolved with the qt and pyqt version updates, and voila, working Spyder 3!  So, I'm good for now, thank you!

The bad news is that this gives you zero information about what was actually happening.  I put a debug log here:

[http://dmorris.net/misc/tmp/spyder-debug.log](http://dmorris.net/misc/tmp/spyder-debug.log)

FYI I did try installing pyopengl and I tried all three graphics modes; none of them made Spyder 4 work.

Let me know if I can provide any other information, otherwise I'm OK working with Spyder 3 on this machine.  FWIW I have a zillion other machines where Spyder 4 is working fine.

Thanks!

**Comment by ccordoba12** [comment]
I don't understand why things are working for Spyder 3 and not 4. That's very strange.

Please let us know if you find more about that, otherwise we'd have to close this issue.

**Comment by agentmorris** [comment]
I'm fine with closing the issue, you've resolved my immediate issue.  The only other thing I can offer is that I think the GLX issue created a bit of a red herring around graphics/rendering/etc., but this doesn't feel like a graphics/rendering/issue to me.  If I had to take a guess, I think the instant at which the segv occurs is precisely the instant at which the kernel finishes loading, i.e. the "initializing kernel" spinner goes away and the console appears.  Sorry I can't provide more data!  Thanks for your responsiveness.

**Comment by CAM-Gerlach** [comment]
> you were also suggesting a rollback to Spyder 3

Ha, this was actually an accident; I copied the sequence of commands from my (not entirely up to date) troubleshooting guide; those were the modern-ish versions at the time I wrote it years ago a downgrade (nor to the older Python 3.6). Nevertheless, glad it worked for you, though given Spyder 3 is outdated and no longer supported, its not really a permanent solution. So if you upgrade again, it doesn't work?

> the GLX issue created a bit of a red herring around graphics/rendering/etc.,

Yeah, but if you can fix the GLX issue, which is blocking the upgrade to Qt 5.9 (as 5.6 will inevitably be dropped eventually, its many years old) then its possible this issue won't reoccur there.

Otherwise, you could try the following to see if you can get it working with a conda-forge build (@ccordoba12 does that pull in Qt 5.12  now instead of 5.9?)

```
conda create -n spyder-env-cf -c conda-forge spyder
conda activate spyder-env-cf
spyder
```

**Comment by ccordoba12** [comment]
> (@ccordoba12 does that pull in Qt 5.12 now instead of 5.9?)

Yes, it does.

**Comment by CAM-Gerlach** [comment]
Thanks. Seems worth a try then @agentmorris

**Comment by agentmorris** [comment]
I tried that; I still get the GLX error, and in the conda-forge-based environment, I can't fix it by installing qt=5.6* and pyqt=5.6*, because those appear to be incompatible with python 3.8.  So I created a conda-forge-based environment and specified python=3.7*, after which I got the GLX error but _could_ fix it with qt=5.6* and pyqt=5.6*, after which Spyder 4 crashes in the same way as above.

If we think this is all related to the GLX error, I don't think this is worth debugging; it's clear that this particular environment is using out-of-date drivers that are complicating things.  I still think the GLX error is an unfortunate coincidence, but I don't know what else to provide to help debug the segv, so this one may remain a mystery, and I recommend closing... thanks!

**Comment by ccordoba12** [comment]
Closing then.

**Comment by CAM-Gerlach** [comment]
@agentmorris Really sorry we weren't able to fix it. Until you are able to upgrade your drivers or your distro, you could keep using Spyder 3, with the understanding that we don't officially support it anymore but it should still be pretty stable so long as its key deps are supported. Have you considered installing either your drivers or Spyder in a chroot, docker/kubernates container or some other form of isolation? That seems to be the generally recommended approach to the issue that you are facing, which seems to be much broader than just Spyder itself.

In any case, we wish you the best of luck, and let us know if we can help more or you find a solution. Thanks for being so understanding in what is surely a very frustrating issue for you. Cheers!

**Comment by agentmorris** [comment]
NP, I consider this fixed for me; Spyder 4 works everywhere except for one archaic machine where Spyder 3 works fine.  I call that a win!  Thanks for your quick responses... 

I do all my dev in Spyder and have since I picked up Python, I'm a super-fan!  

Thanks.

**Comment by CAM-Gerlach** [comment]
Glad to hear! Users like you are the reason we do what we do!
