### ISSUE TITLE
Revert #12271 When Jedi>0.17.0 is Adopted

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#12664]
## Problem Description

When launching Spyder from non-conda environments, jedi does not add site-packages for target conda environments properly (see davidhalter/jedi#1540).

Site-package for the target environment were added to the extra_paths configuration for jedi in PR #12271 as a patch for this.

When python-language-server adopts jedi>0.17.0 (see palantir/python-language-server#744), many of the changes in #12271 may be reverted.

**Comment by mrclary** [comment]
Also see #12259

**Comment by mrclary** [comment]
Affected lines and/or blocks of code in #12271 are marked with 'TODO: issue 12664', and can be removed upon resolution of palantir/python-language-server#744. Where appropriate, additional instruction is provided.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

We'll try to upgrade to Jedi 0.17 for Spyder 4.1.4.

**Comment by mrclary** [comment]
Just to be absolutely clear, version 0.17.0 is the latest version and does _not_ have the bug fix. The fix is complete and merged but will not be available until the next release (I assume 0.17.1)

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification. We'll wait for 0.17.1 then before moving our requirement here.

**Comment by mrclary** [comment]
This issue is obsolete. Closing.
