### ISSUE TITLE
Add instructions about using "conda update anaconda" to the update dialog

### ISSUE THREAD

**Issue by ModeratelyModular** [spyder-ide/spyder#12677]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ModeratelyModular** [comment]
Started a introductory course on Python at MITOpenCourseware. This required installation of Anaconda. Like in the course I wanted to use Spyder, and after installating Anaconda this immediately repeatingly wanted an update (which is also 'strongly recommanded). However, this update didn't work, taking a lot of time and finally reporting conflicts. I found the/a solution that worked at: https://github.com/spyder-ide/spyder/issues/10964 (suggesting several solutions, but for me the "conda update anaconda" worked)), but this is a closed issue. However, it stil persists almost half a year and four versions later. This is very discouraging for beginning students, not being skilled as system manager.

**Comment by ModeratelyModular** [comment]
I'm sorry, closed by accident.

**Comment by adeny100** [comment]
hi i have the same issue not being able to install spyder 4.1.2, when u said downgrading does it downgrade to the older versions? and then ur able to install spyder 4.1.2?

**Comment by ModeratelyModular** [comment]
@adeny100 I noticed it being mentioned when I did the "conda update anaconda" command in the Anaconda Prompt, so it happend automatically. It did downgrade something, but I don't know what. My impression, for what it's worth, was not the Spyder, not the Anaconda and not the Python.

**Comment by ccordoba12** [comment]
This is a known issue with Anaconda, i.e. that you need to run first

    conda update anaconda

before running

    conda install spyder=4.1.2

after a fresh Anaconda installation.

I updated the instructions in our [Releases page](https://github.com/spyder-ide/spyder/releases) with that info. However, we'll also add this advice to our update dialog so that people can have access to that info from within Spyder too.

**Comment by ccordoba12** [comment]
@ModeratelyModular, on a side note: could you let us know the name of the Python course you're taking that uses Spyder?

**Comment by ModeratelyModular** [comment]
@ccordoba12  I used the link from here:

https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/assignments/

In the video course they use Spider (that apparently comes with Anaconda, but it is stated the other way around too ;-))

**Comment by ccordoba12** [comment]
Thanks for the info @ModeratelyModular!

@juanis2112, could you blog about this? The last course available "Introduction to Computer Science and Programming in Python" course in MIT's OpenCourseWare is using Spyder, as can be seen in the screenshot below:

![imagen](https://user-images.githubusercontent.com/365293/81483060-f669b700-9200-11ea-9d4c-a8e98bd48e16.png)

That's good old Spyder 2, but I still think it's important!

**Comment by ccordoba12** [comment]
This is the link to the page I'm showing above:

https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-0001-introduction-to-computer-science-and-programming-in-python-fall-2016/lecture-videos/lecture-2-branching-and-iteration/

The video is paused in minute `4:33`.

**Comment by adeny100** [comment]
I'm so glad that my spyder 4.1.2 could be installed because of this. Thank you so much @ModeratelyModular and @ccordoba12 !!!

**Comment by ModeratelyModular** [comment]
@adeny100 You're welcome. Glad to have been of any help.
@ccordoba12  Thanks for the quick and adequate response.
