### ISSUE TITLE
How can I make the code font size bigger?

### ISSUE THREAD

**Issue by mtafadar** [spyder-ide/spyder#12681]
### What steps will reproduce the problem?

I have the lastest version on Spyder but I am having problem with  font size. I can read the code nor can I type code properly. Also, can I change the theme back into white? 

Thanks in advance

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.3.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
@mtafadar thanks for the report.

So let's first update to the latest version of Spyder. Please open a terminal and type:

```
conda update anaconda
conda install spyder=4.1.2

```

Check if you still se the issues.

Now, to change the font you can go to the Preferences/Appearance and update the Fonts:

<img width="1162" alt="Screen Shot 2020-05-10 at 17 46 30" src="https://user-images.githubusercontent.com/3627835/81512445-322a7c80-92e6-11ea-8d49-b2a361cd4620.png">

You can also use `Cmd++` and `Cmd+-`to change the zoom on the editor.

To change back to the light theme you can go to the Preferences/Appearance, select `light`
<img width="1040" alt="Screen Shot 2020-05-10 at 17 47 36" src="https://user-images.githubusercontent.com/3627835/81512470-5b4b0d00-92e6-11ea-9406-d60738797d81.png">

And then restart.

**Comment by mtafadar** [comment]
Thank you so much.
