### ISSUE TITLE
autocomplete doesn't work on Spyder 4 without Kite installed

### ISSUE THREAD

**Issue by shinelion** [spyder-ide/spyder#12684]
## Problem Description
I just installed the latest Anaconda3 (the installation package 2020.02) that contains Spyder 4.0.1 by default. But it looked Spyder could not support autocomplete function without Kite installed. I don't want to install Kite or any other extra software like it, partly because my computer hardware is not very strong to support all kinds of software running smoothly. I turned on all the autocomplete relevant settings as I did it with Spyder 3.x, but nothing worked on Spyder 4.0.1. I could neither get any suggestion for inputting symbols nor view a function body by clicking the function name with Ctrl or pressing Ctrl+G ("Go to definition"). I understand Kite could be helpful and convenient, but I think an alternative without Kite also needs to be provided at the same time for the developers.

### What steps reproduce the problem?

1. Turn on the autocomplete settings in Tools - Preferences without Kite installed.
2. Autocomplete doesn't work.
3. "Go to definition" doesn't work (by clicking the function name with Ctrl or Ctrl+G).

### What is the expected output? What do you see instead?
Autocomplete works and "Go to definition" works, even without Kite.

## Versions
* Spyder version: 4.0.1 (with Anaconda3 2020.02)
* Python version: 3.7.6  64bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

PASTE DEPENDENCIES HERE
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by goanpeca** [comment]
@shinelion  please open a command prompt and type:

```bash
conda update anaconda
conda install spyder=4.1.3
```

And check if this solves the issues you are seeing. Autocompletion without kite should also be working.

Cheers!

**Comment by shinelion** [comment]
@goanpeca Yes, it works perfectly just as you said! Thanks for the great help!
