### ISSUE TITLE
QGLXContext: Failed to create dummy context WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed. Failed to create OpenGL context for format QSurfaceFormat. finished with exit code 134 (interrupted by signal 6: SIGABRT)

### ISSUE THREAD

**Issue by moehjze** [spyder-ide/spyder#12687]
i have this error whene i use qt5 for creation a web-browser
i use Ubuntu and python3
pycharm:
    error message : 

QGLXContext: Failed to create dummy context
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

by terminal: 
    error message:

WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Abandon (core dumped)

i need your help plz, thank you.

**Comment by ccordoba12** [comment]
> i have this error whene i use qt5 for creation a web-browser

This means the problem is in your code, not in Spyder. This issue tracker is to report Spyder problems only

> i use Ubuntu and python3
pycharm:

It's not  clear from your message if you're using PyCharm, but if you do, then that's another reason for you to look for help in another place, sorry.
