### ISSUE TITLE
there are no output after running this file. runfile('C:/Users/lenovo/Desktop/ML/Part 2 Pre-Processing/Section 2.    Part 1/temp.py', wdir='C:/Users/lenovo/Desktop/ML/Part 2 Pre-Processing/Section 2.    Part 1')

### ISSUE THREAD

**Issue by mi44164** [spyder-ide/spyder#12699]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @mi44164,

Can you please fill out the form that we have for reporting the issue? Give us the steps that you are running and what output do you have vs the expected output.
If you are trying to run a certain piece of code that generates an error, please also put it in here.

**Comment by mi44164** [comment]
Hello, I already import the dataset to my code and I'm trying to execute
that code but it shows me below error instead of the same line of code
which I'm trying to execute.

Here is the code.

#importing the data set.
Dataset = pd.read_csv('Data.csv')


Output:

 runfile('C:/Users/lenovo/Desktop/ML/Part 2 Pre-Processing/Section 2.
Part 1/temp.py', wdir='C:/Users/lenovo/Desktop/ML/Part 2
Pre-Processing/Section 2.    Part 1')

**Comment by steff456** [comment]
What is the output you have vs the expected output? 
Do you have an error in spyder or the bug report window pops up?
