### ISSUE TITLE
Opening settings: Spyder internal error with vanilla installation

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#12692]
### What steps will reproduce the problem?

I reset Spyder using `--reset` (resp. delete the .spyder3 folder), then start it, open settings, close settings without changing anything and restart. Then everytime I open the settings, I get an internal error.

The error seems to be coming from the option `use_colors`, but I could not find with option this refers to. Nothing else seems to be affected by it, all settings load fine.

Detailed print of Exception:
`raise Exception(f'{option} {sec} {default}')
Exception: use_colors None True`

PS: Great work recently! Spyder is getting more awesome every release.

### Traceback
```python-traceback
  File "C:\Users\Simon\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3170, in show_preferences
    widget = plugin._create_configwidget(dlg, self)
  File "C:\Users\Simon\Anaconda3\lib\site-packages\spyder\plugins\base.py", line 117, in _create_configwidget
    configwidget.initialize()
  File "C:\Users\Simon\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 72, in initialize
    self.load_from_conf()
  File "C:\Users\Simon\Anaconda3\lib\site-packages\spyder\preferences\configdialog.py", line 327, in load_from_conf
    checkbox.setChecked(self.get_option(option, default, section=sec))
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.4
* Qt version: 5.14.1
* PyQt5 version: 5.14.1
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

# Spyder plugins:
spyder_line_profiler           :  0.2.0 (OK)
```

**Comment by goanpeca** [comment]
Hi @skjerns, do you have a Spyder plugin installed?

Could you open the settings `~/.spyder/config/spyder.ini` and `~/.spyder/config/transient.ini` and see if there is a `use_colors` setting? It should be True or False, but it seems it has a different value.

Cheers!

**Comment by skjerns** [comment]
there is no `use_colors` setting in the `spyder.ini` or `transient.ini`

I have `spyder-line-profiler` installed!
Uninstalling this solved the problem, thanks :)

**Comment by goanpeca** [comment]
> have spyder-line-profiler

Ok, we will need to check that over there.

Thanks

**Comment by goanpeca** [comment]
Issue moved to [spyder-ide/spyder-line-profiler #49](https://github.com/spyder-ide/spyder-line-profiler/issues/49) via [**ZenHub**](https://www.zenhub.com/)

**Comment by skjerns** [comment]
Issue does not appear anymore after installing develop-version of spyder-line-profiler :)
