### ISSUE TITLE
Can't install new Spyder version via conda

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12705]
For each of 4.1.0, 4.1.1, 4.1.2

**Comment by OverLordGoldDragon** [comment]
Solution: `conda uninstall jedi` --> `conda install -c anaconda spyder==4.1.3`. I don't know why it works, but it does. Anaconda spends 20+ mins resolving packages, and dumps a large output log of conflicts that isn't very helpful.

**Comment by OverLordGoldDragon** [comment]
`spyder-unittest` was refusing to install afterwards, so I did the following (unsure all are necessary): 

```
pip uninstall lxml
pip uninstall python-jsonrpc-server
conda uninstall flake8
conda uninstall jedi
conda install -c spyder-ide spyder-unittest
```

**Comment by OverLordGoldDragon** [comment]
Exactly same deal with 4.1.3 with a fresh Anaconda reinstall; reopened for maintainers' awareness. Close anytime.

**Comment by ccordoba12** [comment]
You need to run

    conda update anaconda

and then

    conda install spyder=4.1.3

after a fresh Anaconda install.
