### ISSUE TITLE
Deleting space before a word trigger meaningless completion

### ISSUE THREAD

**Issue by ElieGouzien** [spyder-ide/spyder#12704]
Hi spyder devs,
I've find a new way of improving the completion:

## Problem Description
Deleting space before a word trigger meaningless completion.

### What steps reproduce the problem?

1. In a new document type `None`;
2. add a space before it;
3. remove this space.

### What is the expected output? What do you see instead?
I would expect nothing, I see the completion with all possibilities.

## Versions

* Spyder version: 4.1.3
* Python version: 3.8

I'm sorry, but this time I don't have time to investigate more.

**Comment by leavor** [comment]
The same problem, when real-time code completion is available

**Comment by steff456** [comment]
Hi @ElieGouzien and @leavor,

We are going to fix this for spyder 4.1.4 release. Thanks for reporting!
