### ISSUE TITLE
Enable text size zooming with Ctrl + mousewheel

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1270]
_From [samuel.l...@gmail.com](https://code.google.com/u/106548631604770110294/) on 2013-02-13T05:21:34Z_

Spyder Version:  2.1.9
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux

The only thing I'm missing in Spyder, compared to other editors (like geany), is ability to zoom the text size in and out with Ctrl + the mousewheel.

Ctrl + Mousewheel up = Increase editor text size by 1 step.
Ctrl + Mousewheel down = Decrease editor text size by 1 step.

I use this all the time, when switching between different distances to the monitor, showing code to someone else, on my small laptop monitor, etc.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1270_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-02-17T02:57:38Z_

This issue was updated by revision 508222c28ef2 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [samuel.l...@gmail.com](https://code.google.com/u/106548631604770110294/) on 2013-06-20T01:19:17Z_

Sorry, I have realized that I missed to add that:

1. Ctrl + "+" and Ctrl + "-" should do the same thing as Ctrl + "Mouse wheel up" and Ctrl + "Mouse wheel down" respectively.
2. Ctrl + 0 should reset the font size to default.

... at least that is how I find most other text editors to be configured (including the Gnome terminal), and use constantly :)

**Comment by kyledmiller** [comment]
I actually really hate it when this ctrl+scroll zooming is enabled because I tend to overlap my scrolling with saving the document (ctrl+s). If I'm scrolling really fast when I hit ctrl, Spyder will sometimes even seg fault.

Is there a way to disable this feature?

Thanks!

**Comment by felixcra** [comment]
@kyledmiller I have exactly the same problem when using the touchpad on my Thinkpad. I hate this feature.
