### ISSUE TITLE
Move collections editor out of Variable Explorer into widgets

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#12725]
The IPython Console, Console and (potentially) other Plugins make (might) use of the collections editor to display env variables and other information. 

Since the new API work is decoupling all the moving parts and there will be a precedence in plugin order of loading, this should move out of the variable explorer, as discussed with @ccordoba12

**Comment by jitseniesen** [comment]
> The IPython Console, Console and (potentially) other Plugins make (might) use of the collections editor to display env variables and other information.

The same goes for the text editor, which is used by the Profiler, Code Analysis and several external plugins.

**Comment by goanpeca** [comment]
>The same goes for the text editor, which is used by the Profiler, Code Analysis and several external plugins.

Indeed, I will address that in another PR @jitseniesen 

Thanks for the input!

**Comment by goanpeca** [comment]
Plugins will now have optional and required requirements

So it will go something like

internal console
coreui (name to be defined)
ipython console
lsp
editor

The rest...

But since the console was being loaded first, having it depend on the variable explorer did not make much sense. However having all the other plugins depend on the editor does make more sense.
