### ISSUE TITLE
Code Analysis customize history not working and actions unavailable when pane is undocked

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#12740]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
1. Changing the number maximum entries in the history option in the Code Analysis options menu doesn't do anything. Number of maximum files shown when dropping down the arrow in the directory path stays the same.

![Screen Shot 2020-05-14 at 1 09 55 AM](https://user-images.githubusercontent.com/18587879/81899221-f01c6780-957f-11ea-932c-cfd263b46dbe.png)
![Screen Shot 2020-05-14 at 1 11 59 AM](https://user-images.githubusercontent.com/18587879/81899229-f27ec180-957f-11ea-971c-76daf0392462.png)
(There are more than 10 entries)

2. Actions from options menu are unavailable when Code Analysis pane is undocked.

![Screen Shot 2020-05-14 at 12 54 37 AM](https://user-images.githubusercontent.com/18587879/81898039-7daa8800-957d-11ea-84e2-4615024496d4.png)

### What steps reproduce the problem?

1. Open Code Analysis
2. Go to options menu
3. Select history
4. Change number of entries

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.2.0.dev0 and 4.1.3
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: Mac OS

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment]
These appear to be two fully separate issues, but I can reproduce both of them on WIndows and Spyder as far back as 4.0.0 final, and I can also confirm the history length persists even after a full restart, and running additional code analyses in the pane.
