### ISSUE TITLE
Spyder stops BLAS library from using multiple threads

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1274]
_From [thomas.u...@gmail.com](https://code.google.com/u/110894844152548721934/) on 2013-02-18T17:25:31Z_

Spyder Version:  2.1.10
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v1) 4.9.3 on Linux

Hi! I'm running Spyder 2.1.10 under Ubuntu 2.10, using NumPy 1.6.2. I'm using OpenBLAS as a BLAS library for numpy ( https://github.com/xianyi/OpenBLAS ). This library can use multiple threads to speed up vector operations. The maximal number of threads can be controlled via environment variables. If nothing is set, 4 threads are used.

However, no matter what I do, when I run my code from within Spyder, OpenBLAS will always only use 1 thread.

Here is a minimal example that I used:

from numpy import *
import time
x = random.random((5000,5000))
t1 = time.time()
foo = dot(x.T, x)
print time.time() - t1

This piece of code will run in ~6.9 seconds on my machine, using 4 threads (I can clearly see the CPU utilization going up to 400&#37; in `top`). 

Inside Spyder, the same piece of code will always only run on 1 CPU and takes considerably longer (~16 seconds). Here are the things that I've tried to get Spyder working, all of which (and combinations of which) failed:

1. Explicitly set the environmental variable that controls the number of threads via the "Environmental Variables" option in the console view.
2.  Explicitly set the environmental variable via os.environ
3. start an IPython console instead of a Python console inside Spyder.
4. store the code in an external file, and do "&#37;run filename.py" in an IPython console.
5. Explicitly start spyder via "OMP_NUM_THREADS=4 spyder" from a shell.

I checked the os.environ variable from within Python/IPython shells, and haven't found any environment variable that would stop OpenBLAS from using multiple threads.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1274_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-03-12T08:39:36Z_

I tried OpenBlas on Ubuntu 12.10 and it gave me just segfaults, so I don't know how to test it.

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [uwe.fech...@gmail.com](https://code.google.com/u/113523341511773808284/) on 2013-09-07T09:51:30Z_

Detailed instructions to install OpenBLAS on Ubuntu 12.04. Might also work on Ubuntu 12.10.

See: http://osdf.github.io/blog/numpyscipy-with-openblas-for-ubuntu-1204-second-try.html sudo apt-get install git python-dev gfortran
cd ~
mkdir 00Software
cd 00Software
git clone git://github.com/xianyi/OpenBLAS
cd OpenBLAS
make -j4 FC=gfortran
sudo make PREFIX=/usr/local/ install

sudo pip uninstall numpy
cd ~/00Software
git clone https://github.com/numpy/numpy cd numpy
cp site.cfg.example site.cfg

Change the following lines:
[DEFAULT] 
library_dirs = /usr/local/lib 
include_dirs = /usr/local/include 

[openblas]  
libraries = openblas  
library_dirs = /usr/local/lib         
include_dirs = /usr/local/include  

export BLAS=/usr/local/lib/libopenblas.a
export LAPACK=/usr/local/lib/libopenblas.a
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/

python setup.py config

check the output !!!

python setup.py build
sudo python setup.py install
sudo ldconfig

Run the following test program:

import numpy
import sys
import timeit

try:
    import numpy.core._dotblas
    print 'FAST BLAS'
except ImportError:
    print 'slow blas'

print "version:", numpy.__version__
print "maxint:", sys.maxint
print

x = numpy.random.random((1000,1000))

setup = "import numpy; x = numpy.random.random((1000,1000))"
count = 5

t = timeit.Timer("numpy.dot(x, x.T)", setup=setup)
print "dot:", t.timeit(count)/count, "sec"

Installing SciPy

sudo pip uninstall scipy
cd ~/00Software
git clone https://github.com/scipy/scipy cd scipy
python setup.py build
sudo python setup.py install
sudo ldconfig

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:41:59Z_

**Labels:** MS-v2.4

**Comment by ccordoba12** [comment]
Closing because we were never able to confirm this issue.
