### ISSUE TITLE
UnknownProblem1

### ISSUE THREAD

**Issue by Aishvarya5** [spyder-ide/spyder#12775]
### What steps will reproduce the problem?

I keep getting this error everytime I open spyder. Even if it's open in the background (and I have not run a code), it shows this error. 

I am new to Python.. can't understand the reason for this error.

### Traceback
```python-traceback
  File "/opt/anaconda3/lib/python3.7/site-packages/spyder/widgets/explorer.py", line 878, in restore_directory_state
    for basename in os.listdir(root):
PermissionError: [Errno 1] Operation not permitted: '/Users/aishvarya/Documents/RA/Dream11'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.0.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
psutil >=0.3      :  5.6.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.18.1 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.16 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by goanpeca** [comment]
Hi @Aishvarya5,  thanks for your report.

It seems you are using and old (and now unmaintained version of Spyder). Please update to the latest version (4.1.3). To do this, open the terminal and type:

```
conda update anacoda
conda install spyder=4.1.3
```

Cheers!

**Comment by ccordoba12** [comment]
@Aishvarya5, your problem could also be solved by following the instructions mentioned here:

https://stackoverflow.com/questions/58372768/file-permissions-issue-with-python-spyder-anaconda-after-upgrading-mac-to-catali
