### ISSUE TITLE
Spyder directly switches to debug mode even when the option is turned off

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#12807]
### What steps will reproduce the problem?

Spyder directly switches to debug mode even when the option is turned off

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.3.0-53-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by goanpeca** [comment]
Hi @ma-sadeghi, thanks for the report.

>Spyder directly switches to debug mode even when the option is turned off

That do you mean, could you elaborate on the issue?

Thanks

**Comment by ma-sadeghi** [comment]
Hi @goanpeca,

When I press F5, the code runs as if it's in debugger mode, meaning that if there's a bug in the code, the IPython console shows the debugger stopped at the buggy line with `ipdb>` showing at the prompt. Normally, I expect IPython console to throw an error and exit.

**Comment by goanpeca** [comment]
Thanks @ma-sadeghi, will check.

---


@impact27 is this the default behavior now?

**Comment by ccordoba12** [comment]
@goanpeca, that's not the default.

@ma-sadeghi, this can only happen for all files if you went to

    Tools > Preferences > Run > General settings

and activated the option

    Directly enter debugging when errors appear

or for the file you're working with, if you went to

    Run > Configuration per file

and activated the same option.

**Comment by ma-sadeghi** [comment]
I turned it off when recording the gif, I'll double check

**Comment by ma-sadeghi** [comment]
@ccordoba12 Sorry, my bad. Although I had indeed turned off the debug mode in Preferences, apparently I had turned it on for that specific file, which overrode the Preferences. Anyways, thanks for the follow up.

**Comment by ccordoba12** [comment]
No problem and glad you found the cause for this.
