### ISSUE TITLE
Wring pandas library version

### ISSUE THREAD

**Issue by dbau** [spyder-ide/spyder#12818]
### What steps will reproduce the problem?

I run spyder from the spyder env. The python interpeter is the default one. Python version is 3.7.3.

When I load pandas inside python in the shell, the pandas version is 1.0.3.
In spyder in 0.24.

conda list pandas
# packages in environment at ~/miniconda3/envs/spyder-beta:
#
# Name                    Version                   Build  Channel
pandas                    1.0.3            py37h0da4684_1    conda-forge

Any help?
Thanks!

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.3
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-1079-oem

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.6.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.8.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  2.1.2 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  0.24.0 (OK)
scipy >=0.17.0                 :  1.3.0 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)
```

**Comment by andfoy** [comment]
Hi @dbau, it seems that you have some setting errors regarding the environments that you are using, more specifically, it is possible that the environment that you are using to execute Spyder is different from the one that has Pandas installed. Could you please post here a detailed description about how are you executing Spyder?

**Comment by dbau** [comment]
Hi @andfoy,

I guess you are right. This is what I get from within my spyder env:
```
spyder-beta: conda list pandas
# packages in environment at /home/dbau/miniconda3/envs/spyder-beta:
#
# Name                    Version                   Build  Channel
pandas                    1.0.3            py37h0da4684_1    conda-forge

spyder-beta: python
Python 3.7.3 | packaged by conda-forge | (default, Dec  6 2019, 08:54:18) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> print (pd.__version__)
0.24.0
>>> 

```

**Comment by dbau** [comment]
Apparently it works if I use python 3.6.7 from the main conda env instead of python 3.7.3 from the spyder env.

**Comment by andfoy** [comment]
@dbau I'm glad that you managed to fix this issue, I'm closing this one, since is not related to the Spyder internals

**Comment by dbau** [comment]
@andfoy 
Just as an update, I found what was wrong with the spyder env. There was a pip installed version od pandas (v 0.24) that was loaded instead of the conda installed one (1.0.3). 
`pip uninstall pandas` 
finally solved the issue.
