### ISSUE TITLE
Variable inspector opens window out of focus

### ISSUE THREAD

**Issue by silvestre125** [spyder-ide/spyder#12825]
## Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide

## Problem Description
When I open a variable like a list or dict in python and I try to open a long string field, the new variable window for the long string is opened behind the main list (or dict) variable window previously opened.

<img width="681" alt="imagen" src="https://user-images.githubusercontent.com/46159929/82662724-ae9a5500-9c2e-11ea-8d20-1b448a529784.png">

### What steps reproduce the problem?

1. Create a list or dict with a field with a long string
2. Open the list/dict in variable explorer
3. The string editor is opened behind the list/dict variable window

### Versions

* Spyder version: From 4.0.0 to 4.1.3 with the same issue
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macos Catalina 10.15.4

**Comment by ccordoba12** [comment]
Thanks for reporting.

@goanpeca, please take a look at this one (I thought you already fix it some time ago).

**Comment by goanpeca** [comment]
>(I thought you already fix it some time ago).

Can't recall.
