### ISSUE TITLE
I am executing my code on Spyder IDE and it does not show me on the console as an OUTPUT.

### ISSUE THREAD

**Issue by mi44164** [spyder-ide/spyder#12823]
whats should I do in this case?

I am executing below code.

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import statsmodels.api as sm
X = np.append(arr = X, values = np.ones((50,1)).astype(int), axis = 1)
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
#Our X_opt array has a dtype of object and this may be causing an error. Try changing it to float.
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()

And I am looking for P- Values from above code as an output but it shows me blow line instead of P-values.

runfile('C:/Users/lenovo/Desktop/ML/Python/Part 2 Regrassion/Section 7 - Multiple Linear Regression/Python/01 Multiple linear regression.py', wdir='C:/Users/lenovo/Desktop/ML/Python/Part 2 Regrassion/Section 7 - Multiple Linear Regression/Python')

I am Using Python 3.7

**Comment by jitseniesen** [comment]
@mi44164 This is a question on how to use statsmodels, not about Spyder, so I am closing this issue. You should go to a place for questions about statsmodels for help. 

It looks to me like you are missing some steps: you still need to fit the model and then you can find the p-values. Have a look at https://www.statsmodels.org/stable/gettingstarted.html#model-fit-and-summary .

**Comment by mi44164** [comment]
My main problem is with Ipython console, not the given code.
the main problem is when I execute my code it does not show the result on
the console.
That's the main concern.

**Comment by jitseniesen** [comment]
I don't understand why you think that your code would show any results. If you look at the link that I sent, it says: 

> "Fitting a model in statsmodels typically involves 3 easy steps: 1. Use the model class to describe the model; 2. Fit the model using a class method; 3. Inspect the results using a summary method."

You did step 1 and 2. You need to do step 3 to see a result.

**Comment by mi44164** [comment]
Ohk.
Got it.

**Comment by mi44164** [comment]
import statsmodels.api as sm 
X = np.append(arr = X, values = np.ones((50,1)).astype(int), axis = 1)
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
#Our X_opt array has a dtype of object and this may be causing an error. Try changing it to float.
X_opt = np.array(X_opt, dtype=float)
regressor_OLS = sm.OLS(endog = Y, exog = X_opt).fit()
regressor_OLS.summary()


**After successfully executing the above code I am not getting P- value on Ipython console and the reason is Below screenshot.
Its executed properly but not showing the values.
Each and every program I'm not getting executed code on console but I get only below lines.**

runfile('C:/Users/lenovo/Desktop/ML/Python/Part 2 Regrassion/Section 7 - Multiple Linear Regression/Python/01 Multiple linear regression.py', wdir='C:/Users/lenovo/Desktop/ML/Python/Part 2 Regrassion/Section 7 - Multiple Linear Regression/Python')

**Comment by jitseniesen** [comment]
You need to print the summary to show the values:
```
print(regressor_OLS.summary())
```

The `runfile(...)` shows that the Python console has run the file. 

There is a difference between running code directly in the console and running a Python file. If you run code directly in the console, Python will automatically print the result. So if you run `3+5` in the console, Python will print `8`. However, if you run a Python file, the result will not be printed unless you explicitly say so. If you run a Python file with the command `3+5`, nothing will be printed. To print the answer, you need to put `print(3+5)` in the Python file.

**Comment by mi44164** [comment]
Thank you so much.
Now it is working properly the way I want. 👍
