### ISSUE TITLE
Spyder broken when open a project

### ISSUE THREAD

**Issue by Prayforhanluo** [spyder-ide/spyder#12824]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder broken when open a project and find the files in a sub-directory
It does seem like the issue https://github.com/spyder-ide/spyder/issues/11126 which I had before

### What steps reproduce the problem?

1. open spyder
2. create a project by a  exit directory
3. Click the subdirectory or file under the project directory on the left

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> open spyder
    create a project by a exit directory
    Click the subdirectory or file under the project directory on the left

I don't understand your instructions, sorry. Please create an animated gif with the Licecap program and upload it here to see what's happening in your case.

> Spyder version:
    Python version:
    Qt version:
    PyQt version:
    Operating System name/version:

Please fill this information. Without that we can't help you, sorry.

**Comment by Prayforhanluo** [comment]
![spyder_issue](https://user-images.githubusercontent.com/20788781/82722569-8e37cc80-9cfa-11ea-9610-9950cd669ea6.gif)
![Uploading spyder_issue2.gif…]()

**Comment by Prayforhanluo** [comment]
# Mandatory:
atomicwrites >=1.2.0           :  1.2.1 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  0.5.5 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.10.2 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.1.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.8.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.3.0 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.28.5 (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.15.4 (OK)
pandas >=0.13.1                :  0.24.0 (OK)
scipy >=0.17.0                 :  1.3.0 (OK)
sympy >=0.7.3                  :  1.1.1 (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)

**Comment by Prayforhanluo** [comment]
Spyder is really my favorite IDE,  I don't want to give it up.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Carlos Cordoba<mailto:notifications@github.com>
发送时间: 2020年5月23日 3:46
收件人: spyder-ide/spyder<mailto:spyder@noreply.github.com>
抄送: luo han<mailto:hluo_lc@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [spyder-ide/spyder] Spyder broken when open a project (#12824)


open spyder
create a project by a exit directory
Click the subdirectory or file under the project directory on the left

I don't understand your instructions, sorry. Please create an animated gif with the Licecap program and upload it here to see what's happening in your case.

Spyder version:
Python version:
Qt version:
PyQt version:
Operating System name/version:

Please fill this information. Without that we can't help you, sorry.

―

**Comment by Prayforhanluo** [comment]
spyder : 4.1.3
python : 3.7.0
system : window 10

**Comment by ccordoba12** [comment]
Are you trying to drag a directory from the Project pane to the left to the editor?

**Comment by Prayforhanluo** [comment]
No , I just want to check the files under the sub-directory, But when I click the the triangle to the left of the sub-directory, It got stuck

**Comment by ccordoba12** [comment]
Did you use Anaconda to install Spyder?

**Comment by Prayforhanluo** [comment]
Yes , Update spyder in Anaconda Prompt:
conda install spyder=4.1.3

**Comment by ccordoba12** [comment]
I'm sorry but I don't know what happens in your case. No one else has reported a problem like thus.

**Comment by ccordoba12** [comment]
Please update to our 4.1.4 version. That probably solves this problem.
