### ISSUE TITLE
Can't move plugins to different windows in layout

### ISSUE THREAD

**Issue by stcmeh** [spyder-ide/spyder#12821]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Can't move plugins to different windows in layout

### What steps reproduce the problem?

1. Start Spyder
2. Try to drag - say - the Plots window from the top-right dock to the bottom right dock where the Python Console is...
3. Well it won't go there.

### What is the expected output? What do you see instead?

Expected the plots window to move to a new tab in the bottom-right window section - as per Spyder 3. Also that they stay there when Spyder is restarted.

Note - I really went to town trying to fix this myself - made a plug-in and copied the layout code out of GIT. Using this approach I could move a plugin to a different window but it would _not_ stay there after restarting or saving the layout.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.6
* Qt version: 
* PyQt version: 
* Operating System name/version: Centos 7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @stcmeh, thanks for opening this issue, we want to know how are you moving the panes across Spyder, have you tried to disable the option "Lock panes and toolbars" found under the View menu on the toolbar?

**Comment by stcmeh** [comment]
That's it - sorry. Case closed.
