### ISSUE TITLE
Spyder_keeps_crashing_giving error python3.6

### ISSUE THREAD

**Issue by TB2016** [spyder-ide/spyder#12833]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Anaconda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1014, in create_new_client
    interpreter=pyexec)
  File "C:\Anaconda\lib\site-packages\spyder\utils\programs.py", line 425, in is_module_installed
    return eval(output.decode())
  File "<string>", line 2
    Anaconda2\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(213) : fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
            ^
SyntaxError: invalid syntax

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
It seems at some point you installed some packages with pip, which broke your Anaconda installation. Now I'm afraid you'll have to uninstall it, manually remove `C:\Anaconda` and reinstall it again, sorry.
