### ISSUE TITLE
Spyder was unable to receive the value of this variable from the console error

### ISSUE THREAD

**Issue by shamimae** [spyder-ide/spyder#12832]
## Problem Description
I am using genetic algorithm (NSGA II) for optimization of different paramters of my  model. Model need to call several DLLs for simulation. However, the program works file for simulation, but I am getting the above mention error for the DLL. I get access the value of the variable if do not call the DLL.

![image](https://user-images.githubusercontent.com/65723040/82708867-8dd8fc00-9c3c-11ea-9c4e-a0a17340935d.png)

### What is the expected output? What do you see instead?
I would like to get the variables from the following function:

res = minimize(problem,
               algorithm,
               termination,
               seed=1,
               pf=problem.pareto_front(use_cache=False),
               save_history=True,
               verbose=False)

**Comment by ccordoba12** [comment]
There are two things here:

1. This is not an error. As the message says, Spyder was simply unable to retrieve the value from the console to visualize it.
2. You're using an old version of Spyder. In out latest version (4.1.3) we also show this additional note when this happens:

    > Note: Please don't report this problem on Github, there's nothing to do about it.

**Comment by shamimae** [comment]
Dear Sir,Thanks for reply. Sorry, I am very new in Github. I am using spyder 4.1.3. Is there any suggestion for visualisation of the resultsThanks 


Sent from Yahoo Mail for iPhone


On Friday, May 22, 2020, 3:07 PM, Carlos Cordoba <notifications@github.com> wrote:




There are two things here:
   
   -    
This is not an error. As the message says, Spyder was simply unable to retrieve the value from the console to visualize it.

   -    
You're using an old version of Spyder. In out latest version (4.1.3) we also show this additional note when this happens:
   
   
Note: Please don't report this problem on Github, there's nothing to do about it.

**Comment by ccordoba12** [comment]
> I am using spyder 4.1.3

Sorry, I was thinking on other message. The message you posted above is the one we're showing at the moment.

> Is there any suggestion for visualisation of the results

Unfortunately, there is way to view them, sorry.
