### ISSUE TITLE
Different environments share .ini files, temp files, history...

### ISSUE THREAD

**Issue by ptoche** [spyder-ide/spyder#12842]
On my system at least, which is a 2-hour old clean install of `MacOS Catalina` with `miniconda3` and the latest `Spyder` build, if I create two `conda` environments, `env1` and `env2` in which I install `spyder`, both setups refer to the same `.spyder-py3` configs. So if I open two instances (let's say I want to test the latest version of Spyder against the previous one), if I modify the theme or a keyboard shortcut in one instance, this immediately conflicts with the other instance. If I write in the `temp.py` file, likewise, as it is open in both instances.

A solution must involve an environment-specific `.spyder-py3` directory.  

This is a *conda* problem in a sense, but in the `README` file, *conda* is listed at the top as the method by which to obtain *Spyder*, so I'm reporting here. Please move if you feel it is appropriate.

**Comment by ccordoba12** [comment]
> A solution must involve an environment-specific .spyder-py3 directory.

Thanks for reporting. This is planned for Spyder 5, to be released next year.

**Comment by ptoche** [comment]
Thanks Carlos. Since posting my suggestion I have noticed several discussions on related topics, including [here](https://github.com/spyder-ide/spyder/issues/3891), [here](https://github.com/spyder-ide/spyder/issues/4150), [here](https://github.com/spyder-ide/spyder/issues/8466).
