### ISSUE TITLE
Spyder Object Format issue

### ISSUE THREAD

**Issue by ArthurShen8118** [spyder-ide/spyder#12840]
![2020-05-24 00 12 24](https://user-images.githubusercontent.com/65834733/82742233-5c068900-9d53-11ea-83fa-cc5bc52b6517.png)

I try to do format on the variable x but it seems like gray up. Could anyone help me with this 

Many thnaks

**Comment by ccordoba12** [comment]
@ArthurShen8118, you're trying to edit a Numpy object array. Unfortunately, that can't be done in Spyder because object arrays can contain any kind of data, so we can't assure arrays will be saved reliably after the change.

**Comment by ccordoba12** [comment]
> I try to do format on the variable x but it seems like gray up. Could anyone help me with this

And format doesn't work for them either, sorry.
