### ISSUE TITLE
Execution fails with F5 (run) with pre-loaded modules

### ISSUE THREAD

**Issue by diggee** [spyder-ide/spyder#12850]
## Problem Description
Hi. I have run into a strange bug. I am using a startup file (as explained [here](https://towardsdatascience.com/how-to-automatically-import-your-favorite-libraries-into-ipython-or-a-jupyter-notebook-9c69d89aa343)) to pre-load the common libraries that I use, like pandas and numpy. When I run the file using F5, spyder throws an error (traceback pasted below) that it does not recognize the variable 'pd', which is the pandas import from my startup file. Similarly, it does not recognise any of the other packages as well if run with F5. However, if I execute a certain section of the script, it runs just fine. Below is the example section of the script.

```
#%% read data

df = pd.read_csv('train.csv')

plt.figure(figsize = (12,4))
plt.plot(df['signal'])

plt.figure(figsize = (12,4))
plt.plot(df['open_channels'])

batch_size = 50 * 10000
df['batch'] = np.floor(df.index/batch_size) + 1

similar_batches = [(1,2), (3,7), (4,8), (5,10), (6,9)]

train = df.copy()
test = pd.read_csv('test.csv')
for i in range(len(similar_batches)):
    train['signal'][train.batch == similar_batches[i][1]] = train['signal'][train.batch == similar_batches[i][0]].values
```

If I run just the above section (ctrl+ enter), it runs fine. Also, if I start typing in the console and try to use any of the pre-loaded libraries, they work just fine. It is just that I cannot get them to work if I run the entire file using F5 (run). I have also attached a screenshot illustrating the same. 

![Capture](https://user-images.githubusercontent.com/56080380/82832483-d7de0e00-9ed8-11ea-9ea0-f69de68f7780.PNG)

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "C:\Users\admin\Documents\Machine Learning\Projects\Ion Switching\ion_switching_analysis.py", line 3, in <module>
    df = pd.read_csv('train.csv')

NameError: name 'pd' is not defined

```

I tried searching for this bug but couldn't find anything. If this is a known issue, it will be great if you guys could point me to something as it is really frustrating to run the script section by section and not in one go, specially for very large script files. 

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.3 64-bit
* Qt version: 5.12.8
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

**Comment by goanpeca** [comment]
Hi @diggee thanks for your report.

We will look into it

**Comment by ccordoba12** [comment]
`runfile` runs in an empty namespace by default, i.e. it doesn't use any variable or import present in the console to prevent picking up values defined before on it.

If you want to change that for all your files (although I'd highly recommend you **not** to do that because your code would completely unreproducible), you can to the menu

    Tools > Preferences > Run > General settings

and activate the option called `Run in console's namespace instead of an empty one`.

**Comment by diggee** [comment]
@ccordoba12 yup, that worked. thanks a ton!
