### ISSUE TITLE
a problem when switching to python2

### ISSUE THREAD

**Issue by beignner** [spyder-ide/spyder#12860]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
a problem when using ythoninterpret to switch to python2

**Comment by steff456** [comment]
Hi @beignner,

Can you please give us a step-by-step for us to be able to reproduce your issue?

**Comment by steff456** [comment]
Closing this issue because there was not a response after a week.
