### ISSUE TITLE
Files disappearing and reappearing

### ISSUE THREAD

**Issue by bdgrantham** [spyder-ide/spyder#12870]
### What steps will reproduce the problem?

Python files I am working on keep disappearing from my project directory.

Open a file and make a change to it.
Save the file.
The file will then periodicly disappear and then reappear.
An error is sent if I set the focus to that file Spyder says the file doesn't exist and if I really want to close it.  I select no and save it and if the file has reappeared, it will save fine, or it will promt me like it was a new file.

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by steff456** [comment]
Hi @bdgrantham,

Can you please upload a gif or a video where you can explain how to reproduce this issue?

Thanks!

**Comment by bdgrantham** [comment]
Here is a gif showing the behavior,


![File_issue](https://user-images.githubusercontent.com/47894783/82951028-1244bb00-9f6c-11ea-9dda-360af3ce7076.gif)

**Comment by steff456** [comment]
Are you using  Dropbox, Box, One Drive or something similar to synchronize your files?

**Comment by bdgrantham** [comment]
We have File Director and our ITS team is looking into that as well.  At this point, Spyder is the only application exhibiting this issue.

**Comment by ccordoba12** [comment]
What does File Director do exactly?

**Comment by bdgrantham** [comment]
We use It to backup our local drive to a network drive automatically.

**Comment by ccordoba12** [comment]
Ok, please let us know if your IT team can fix this issue or not.

**Comment by steff456** [comment]
Hi @bdgrantham we are going to close this issue, please let us know if your IT team could fix this issue via a comment here. 
Thanks for reporting!
