### ISSUE TITLE
Disabled shortcut still set 

### ISSUE THREAD

**Issue by dbau** [spyder-ide/spyder#12878]
### What steps will reproduce the problem?

Hi,

I have disabled the shortcut "Alt+Shift+Enter" to avoid to run the file accidenty. 
However, even if this shortcut has been disabled in the shortcut panel, whenever I accidently type "Alt+Shift+Enter", the file is executed.  

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.3
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-1079-oem

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.6.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.5.0 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.4.2 (OK)
pylint >=0.25                  :  2.3.1 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.8.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  2.1.2 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.16.4 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)
```

**Comment by ptoche** [comment]
Have you checked in your `spyder.ini` file that `editor/debug cell = Alt+Shift+Return` is replaced with `editor/debug cell?

I recently experienced a problem with shortcuts that was caused by attempting to assign a key binding in Spyder that was already assigned by MacOS. That caused all of my settings to be reset. 

You'll find the `spyder.ini` file inside your home directory and the "invisible" directory `.spyder-py3/config` . Make a backup of the file just in case and play around to see if you can disable the shortcut.

**Comment by dbau** [comment]
Hi @ptoche,

I confirm that modifying the `spyder.ini` file as you suggested fixed the issue.

Thanks a lot for your help!

**Comment by ccordoba12** [comment]
Thanks for your help @ptoche!

**Comment by ptoche** [comment]
You have helped me many times before! Love Spyder!
