### ISSUE TITLE
 No module named 'prompt_toolkit.formatted_text'

### ISSUE THREAD

**Issue by QuetzalcoatlRosso** [spyder-ide/spyder#12885]
## Problem Description
 No module named 'prompt_toolkit.formatted_text'

### What steps reproduce the problem?

1. $ spyder
2. bug report textbox opens suggestion spyder --reset
3. $ spyder --reset
4. $ spyder
5. Go to step (1) above.

Also tried $pip  install prompt_toolkit but "Requirement already satisfied".
Should I switch to PyCharm?

### What is the expected output? What do you see instead?
Spyder console expected to open but instead stdout " No module named 'prompt_toolkit.formatted_text'"

### Paste Traceback/Error Below (if applicable)
  File "C:\Users\user\anaconda3\lib\site-packages\IPython\terminal\interactiveshell.py", line 21, in <module>
    from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3
* Python version: 3.7.x
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows

### Dependencies
N/A: can't open Spyder now

**Comment by dalthviz** [comment]
Hi @QuetzalcoatlRosso sorry to here that, seems like the env you are working on got corrupted some how. Please try to check our [Troubleshooting Guide and FAQ](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) to see if that helps you :)

Also, maybe the problem could be the version of `prompt-toolkit` you are using so you could try running something like `pip install -U prompt-toolkit` (which should update `prompt-toolkit` if it's already installed).

For now there is not much we can do in case like the one you are experiencing, sorry about that :/

**Comment by QuetzalcoatlRosso** [comment]
thanks for the quick response! I appreciate it. will compare with pycharm.
