### ISSUE TITLE
Spyder Not Opening KeyError: 'pyside2'

### ISSUE THREAD

**Issue by balasaravanan3502** [spyder-ide/spyder#12896]
## Problem Description
C:\Users\admin>spyder
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\app\start.py", line 201, in main
    from spyder.app import mainwindow
  File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 53, in <module>
    requirements.check_qt()
  File "C:\Users\admin\Anaconda3\lib\site-packages\spyder\requirements.py", line 42, in check_qt
    package_name, required_ver = qt_infos[qtpy.API]
KeyError: 'pyside2'

## Versions

 Spyder version: 4.1.3
 Python version: 3.7.7
 Qt version: 5.12.5
 PyQt version: 5.12.3

**Comment by texadactyl** [comment]
This seems to be a new qtpy issue i.e. different package.  I had the same surprise this morning on Xubuntu 20.04 although I have no idea how qtpy got this requirement while I was sleeping!  (=:

My traceback:
```
Traceback (most recent call last):
  File "/home/elkins/.local/lib/python3.8/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'
```

When I try to install PySide, I get this:
```
Collecting PySide
  Using cached PySide-1.2.4.tar.gz (9.3 MB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1o4p6jo0/PySide/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1o4p6jo0/PySide/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h6hiepoa
         cwd: /tmp/pip-install-1o4p6jo0/PySide/
    Complete output (1 lines):
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

My Python version is 3.8.2.  I am not going back (somehow) to 3.4.

**Comment by texadactyl** [comment]
Okay, out of frustration, I removed recursively the pip cache, lib, and bin stuff.  Not recommended to the feint at heart.

Reinstalled my working set of pip packages and now Spyder launches just fine.  No nasty tracebacks.  Installed versions:
```
spyder                        4.1.3         
spyder-kernels                1.9.1     
QtPy                          1.9.0         
```
and no pyside or PySide.  Happy to be back in business but wondering what happened.

**Comment by juanis2112** [comment]
Hello @Balasarav, thanks for reporting this. Are you trying to set QT_API to pyside2? If you are, this is probably causing the error because Spyder doesn't work with pyside2 yet.

**Comment by juanis2112** [comment]
@texadactyl Thanks for your insight on this. I think this error that you are talking about is unrelated to what @Balasarav was saying, but I'm glad you got it to work.

**Comment by texadactyl** [comment]
@juanis2112  Me too!  But I should not have had to rebuild the universe.  No idea what happened since I thought nothing had changed.  Maybe my orange tabby cat (gato loco) walked on my keyboard.

**Comment by balasaravanan3502** [comment]
> Hello @Balasarav, thanks for reporting this. Are you trying to set QT_API to pyside2? If you are, this is probably causing the error because Spyder doesn't work with pyside2 yet.

Then should I reinstall pyside with older version.

**Comment by balasaravanan3502** [comment]
> Hello @Balasarav, thanks for reporting this. Are you trying to set QT_API to pyside2? If you are, this is probably causing the error because Spyder doesn't work with pyside2 yet.

Thank you. I installed pyside version 1 and it worked for me.

**Comment by ccordoba12** [comment]
Sorry to say it but Spyder worked with Pyside 1 in versions that right now are more than 4 or 5 years old and completely unsupported.

**Comment by CamiloMartinezM** [comment]
I just upgraded Spyder from 5.0.0 to 5.0.3 and got this error.

```
Traceback (most recent call last):
  File "/home/camilo/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/camilo/anaconda3/lib/python3.8/site-packages/spyder/app/start.py", line 210, in main
    from spyder.app import mainwindow
  File "/home/camilo/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 43, in <module>
    requirements.check_qt()
  File "/home/camilo/anaconda3/lib/python3.8/site-packages/spyder/requirements.py", line 45, in check_qt
    package_name, required_ver = qt_infos[qtpy.API]
KeyError: 'pyside2'
```

**Comment by ioannis12** [comment]
I'm getting the same error message, any ideas?

**Comment by texadactyl** [comment]
The current version of spyder is 5.15.
Consider upgrading.

**Comment by ioannis12** [comment]
thanks for the reply, I have an old macbook currently running OS El Capitan, you know what is the least required OS to run a more current spyder version without problems?

**Comment by texadactyl** [comment]
Best way to find out is just do it.  You can always fall back if necessary.
