### ISSUE TITLE
Python Language server won't start

### ISSUE THREAD

**Issue by Aman-A** [spyder-ide/spyder#12904]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I installed spyder in my base environment (python version  = 3.7.7) and a second condaa environment that uses a different python version (3.6.8). In this second environment, spyder can't seem to connect to the python language server, as the bottom toolbar is stuck at "LSP Python: starting...". Clicking this button and clicking "Restart Python Language Server" just changes it to "restarting...". Code completion and linting doesn't work. However, in my base environment, this all works fine. 

python-language-server version is updated 0.31.10

### What steps reproduce the problem?

1. Launching spyder within specific conda environment
## Versions

* Spyder version: 4.1.3
* Python version: 3.6.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Mojave (10.14.6)

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)```

**Comment by ccordoba12** [comment]
Please post the output of `conda list` for the environment that's giving you troubles.

**Comment by Aman-A** [comment]
Sure: 
packages in environment at /Users/amanaberra/opt/anaconda3/envs/bpopt_env:

Name                    Version                   Build  Channel
alabaster                 0.7.12                   py36_0  
applaunchservices         0.2.1                      py_0  
appnope                   0.1.0                    pypi_0    pypi
argh                      0.26.2                   py36_0  
argparse                  1.4.0                    pypi_0    pypi
astroid                   2.4.1                    py36_0  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.4.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.1.0                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.1.4                      py_0  
bluepyopt                 1.9.27                   pypi_0    pypi
ca-certificates           2020.1.1                      0  
cairo                     1.14.12              hc4e6be7_4  
certifi                   2020.4.5.1               py36_0  
cffi                      1.14.0           py36hb5b8e2f_0  
chardet                   3.0.4                 py36_1003  
cloudpickle               1.4.1                      py_0  
cryptography              2.9.2            py36ha12b0ac_0  
cycler                    0.10.0           py36hfc81398_0  
cython                    0.29.17          py36h0a44026_0  
dbus                      1.13.14              h517e14e_0  
deap                      1.3.1                    pypi_0    pypi
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20181111                   py_0  
docutils                  0.16                     py36_0  
efel                      3.0.80                   pypi_0    pypi
entrypoints               0.3                      py36_0  
expat                     2.2.6                h0a44026_0  
flake8                    3.7.9                    py36_0  
fontconfig                2.13.0               h5d5b041_1  
freetype                  2.9.1                hb4e5f40_0  
fribidi                   1.0.5                h1de35cc_0  
future                    0.18.2                   py36_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.63.1               hd977a24_0  
graphite2                 1.3.13               h2098e52_0  
graphviz                  2.40.1               hefbbd9a_2  
greenlet                  0.4.15                   pypi_0    pypi
harfbuzz                  1.8.8                hb8d4a28_0  
hjson                     3.0.1                    pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      2.9                        py_1  
imagesize                 1.2.0                      py_0  
importlib-metadata        1.6.0                    py36_0  
importlib_metadata        1.6.0                         0  
intel-openmp              2019.4                      233  
intervaltree              3.0.2                      py_0  
ipykernel                 5.2.1                    pypi_0    pypi
ipyparallel               6.2.4                    pypi_0    pypi
ipython                   7.13.0           py36h5ca1d4c_0  
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                    py36_0  
isort                     4.3.21                   py36_0  
jedi                      0.15.2                   py36_0  
jinja2                    2.11.2                     py_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.2.0                    py36_0  
jupyter_client            6.1.3                      py_0  
jupyter_core              4.6.3                    py36_0  
keyring                   21.1.1                   py36_2  
kiwisolver                1.2.0            py36h04f5b5a_0  
lazy-object-proxy         1.4.3            py36h1de35cc_0  
libcxx                    10.0.0                        1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h0a44026_6  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.16                 h1de35cc_0  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.16               h3efe00b_0  
libspatialindex           1.9.3                h0a44026_0  
libtiff                   4.1.0                hcb84e12_0  
libxml2                   2.9.9                hf6e021a_1  
markupsafe                1.1.1            py36h1de35cc_0  
matplotlib                3.1.3                    py36_0  
matplotlib-base           3.1.3            py36h9aa3819_0  
mccabe                    0.6.1                    py36_1  
mistune                   0.8.4            py36h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py36hfbe908c_0  
mkl_fft                   1.0.15           py36h5e564d8_0  
mkl_random                1.1.1            py36h959d312_0  
nbconvert                 5.6.1                    py36_0  
nbformat                  5.0.6                      py_0  
ncurses                   6.2                  h0a44026_1  
networkx                  2.4                        py_0  
numpy                     1.18.2                   pypi_0    pypi
numpy-base                1.18.1           py36h3304bdc_1  
numpydoc                  0.9.2                      py_0  
openssl                   1.1.1g               h1de35cc_0  
packaging                 20.3                       py_0  
pandas                    1.0.3                    pypi_0    pypi
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
pango                     1.42.4               h7e27002_1  
parso                     0.5.2                      py_0  
pathtools                 0.1.2                      py_1  
pcre                      8.43                 h0a44026_0  
pebble                    4.3.10                   pypi_0    pypi
pexpect                   4.8.0                    py36_0  
pickleshare               0.7.5                    pypi_0    pypi
pip                       20.0.2                   py36_3  
pixman                    0.38.0               h1de35cc_0  
pluggy                    0.13.1                   py36_0  
prompt-toolkit            3.0.5                    pypi_0    pypi
prompt_toolkit            3.0.4                         0  
psutil                    5.7.0            py36h1de35cc_0  
ptyprocess                0.6.0                    pypi_0    pypi
pycodestyle               2.5.0                    py36_0  
pycparser                 2.20                       py_0  
pydocstyle                4.0.1                      py_0  
pyflakes                  2.1.1                    py36_0  
pygments                  2.6.1                      py_0  
pygraphviz                1.3              py36h1de35cc_1  
pylint                    2.5.2                    py36_0  
pyopenssl                 19.1.0                   py36_0  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py36h655552a_2  
pyrsistent                0.16.0           py36h1de35cc_0  
pysocks                   1.7.1                    py36_0  
python                    3.6.8                haf84260_0  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.10                  py36_0  
python.app                2                       py36_10  
pytz                      2020.1                     py_0  
pyyaml                    5.3.1            py36h1de35cc_0  
pyzmq                     19.0.0                   pypi_0    pypi
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.0                      py_0  
qtconsole                 4.7.4                      py_0  
qtpy                      1.9.0                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.23.0                   py36_0  
rope                      0.17.0                     py_0  
rtree                     0.9.4                    py36_1  
scipy                     1.4.1            py36h9fa6033_0  
scoop                     0.7.1.1                  pypi_0    pypi
setuptools                46.4.0                   py36_0  
sip                       4.19.8           py36h0a44026_0  
six                       1.14.0                   py36_0  
snowballstemmer           2.0.0                      py_0  
sortedcontainers          2.1.0                    py36_0  
sphinx                    3.0.3                      py_0  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
spyder                    4.1.3                    py36_0  
spyder-kernels            1.9.1                    py36_0  
sqlite                    3.31.1               h5c1f38d_1  
testpath                  0.4.4                      py_0  
tk                        8.6.8                ha441bb4_0  
toml                      0.10.0           py36h28b3542_0  
tornado                   6.0.4            py36h1de35cc_1  
traitlets                 4.3.3                    py36_0  
typed-ast                 1.4.1            py36h1de35cc_0  
ujson                     1.35             py36h1de35cc_0  
urllib3                   1.25.8                   py36_0  
watchdog                  0.10.2           py36h1de35cc_0  
wcwidth                   0.1.9                      py_0  
webencodings              0.5.1                    py36_1  
wheel                     0.34.2                   py36_0  
wrapt                     1.11.2           py36h1de35cc_0  
wurlitzer                 2.0.0                    py36_0  
xz                        5.2.5                h1de35cc_0  
yaml                      0.1.7                hc338f04_2  
yapf                      0.28.0                     py_0  
zeromq                    4.3.1                h0a44026_3  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
zstd                      1.3.7                h5bba6e5_0

**Comment by ccordoba12** [comment]
I see that you have Pyzmq installed with pip in your environment, and that could be the cause of your problem. It's a very bad idea to mix pip and conda packages because they are binary incompatible.

Please create a new environment for Python 3.6 by using only only conda or only pip and try again.

**Comment by Aman-A** [comment]
I see, that fixed it, thanks! I unfortunately need to use some packages (bluepyopt, efel, etc.) that can only be installed over pip, so I think i can install them last after installing spyder and all its dependencies. Or if I run into issues, I'll try installing for source

**Comment by ccordoba12** [comment]
> so I think i can install them last after installing spyder and all its dependencies

You need to install everything with `pip`. That should solve your problem.
