### ISSUE TITLE
Can I 'source' the config file while running?

### ISSUE THREAD

**Issue by ptoche** [spyder-ide/spyder#12910]
**With the Spyder IDE already running, how can I programmatically send a command to Spyder to re-source the config file?**

Use case: I have written scripts to edit the config files based on which environment Spyder is running in, but the edits come in too late, when Spyder has already sourced the default `spyder.ini` file: I would like Spyder to source the config file while running.

**Bonus question:** how can I source a configuration file located in a directory other than the default `.spyder-py3/config`? 

I adapted some code found in `Spyder/start.py` and `Spyder/restart.py`, but being new to this I didn't get very far. My idea was to save the environment's arguments, append `'--new-instance'` and send the command to Spyder. Would that work? My first problem is at `str(sys.argv[1:])`, which returns an empty list.

    def reset_config():
        """
        Reset Spyder configuration file while an instance of spyder is running.
        """
        import os
        import sys
        import ast
        from inspect import getsourcefile
        from spyder.app.cli_options import get_options

        # store the environment
        env = os.environ.copy()

        # get the variables
        options, args = get_options()
        spyder_args = str(sys.argv[1:])  # can't find any spyder arguments  :-(

        if not spyder_args:
            error = "This script can only be called from within a Spyder instance"
            raise RuntimeError(error)
    
        # Parse variables stored as string literals in the environment.
        args = ast.literal_eval(spyder_args)

        # Enforce the --new-instance flag
        args.append('--new-instance')

        # Arrange arguments to be passed to the restarter subprocess
        args = ' '.join(args)

        # Get python excutable running this script
        python = sys.executable

        # Get the spyder base directory:
        this_folder = os.path.split(os.path.dirname(os.path.abspath(getsourcefile(lambda:0))))[0]
        spyder_folder = os.path.split(this_folder)[0]
        spyderdir = os.path.join(spyder_folder, 'spyder')
        spyder = os.path.join(spyderdir, 'app', 'start.py')

        # Build the command:
        cmd = '"{0}" "{1}" {2}'.format(python, spyder, args)

        # Restart -- Open a pipe to command cmd:
        try:
            subprocess.Popen(cmd, shell=True, env=env)
        except Exception as error:
            restarter.launch_error_message(error_type=RESTART_ERROR, error=error)

Currently what I do is ask myself which environment I'm going to work in, run a script to modify the configuration file accordingly, and then launch Spyder. And if I need to change environment, I need to close Spyder and start again. I'm hoping that the logic I describe here will allow me to have several instances of Spyder running, each with its own config file sourced at launch time from the appropriate environment.

**Comment by ccordoba12** [comment]
> With the Spyder IDE already running, how can I programmatically send a command to Spyder to re-source the config file?

I don't think this is possible. I mean, you can read and write to our conf file while Spyder is running, but I don't think you can load its entire contents again.

@goanpeca, what do you think?

> Bonus question: how can I source a configuration file located in a directory other than the default .spyder-py3/config?

That's already supported but not exposed yet anywhere in the interface. I don't know exactly the details, but @goanpeca knows them because he implemented that change.

**Comment by goanpeca** [comment]
>I don't think this is possible. I mean, you can read and write to our config file while Spyder is running, but I don't think you can load its entire contents again.

Well, you could load them, but we do not have a mechanism to propagate ALL the config once again, as this is read when some widgets are created. In theory we could "source" it and then reapply settings using all possible options keys so that we make sure things are updated.

So could be done with some changes.

> That's already supported but not exposed yet anywhere in the interface. I don't know exactly the details, but @goanpeca knows them because he implemented that change.

So we could maybe add an option to make spyder use configuration on a specific folder?

```
spyder --config-path <some-path>

spyder --config-path <some-other-path>
```

If there is a config there, spyder would use that otherwise it would start from scratch?

**Comment by ccordoba12** [comment]
> So we could maybe add an option to make spyder use configuration on a specific folder?

The thing is this shouldn't be necessary after we revamp our Projects support to include this. So I'm kind of reluctant to do it right now.

**Comment by goanpeca** [comment]
>The thing is this shouldn't be necessary after we revamp our Projects support to include this. So I'm kind of reluctant to do it right now.

I guess, but we still need something to handle multiple Spyder instances.

**Comment by ccordoba12** [comment]
You're right. In that case, I agree with adding that command line option.

**Comment by ptoche** [comment]
Thanks guys for your responsiveness! I can live without this functionality. What I'm doing right now is I run a script that copies my environment's config file to `.spyder-py3/config'  before launching Spyder. Adds one small step, it's fine. 

@goanpeca, 

> we still need something to handle multiple Spyder instances.

You could have config files saved in each environment's root directory, changing the line 

    osp.join(get_home_dir(), '.spyder.ini')

to something like:

    osp.join(get_env_dir(), '.spyder.ini')

assuming a function like `get_env_dir()` returns the path to the environment (I think it may actually be called `get_user_env()`, but not certain)

Or do you worry that users would be confused if they set up their preferences in one environment and find that they do not apply in another environment?

**Comment by goanpeca** [comment]
>Or do you worry that users would be confused if they set up their preferences in one environment and find that they do not apply in another environment?

Hmmm interesting, but yes it could be confusing.

**Comment by ptoche** [comment]
To reduce the possibility of confusion, I have a message in my temp file to remind me of the environment I'm in. To do that, I run a script at startup to load an environment-specific `temp.py` file. At the top of that file I write "This file resides in the <env> environment" to remind myself of the environment I'm working in. Before I install a package, I always check to make sure I'm in the right environment: Since my `temp.py` file is always open and visible, I find it convenient. To do that requires only small changes to the Spyder code. Example:



    def make_temp_file(envname=None, filename=None):
        """
        Create a temp file for a named environment inside a subdirectory. 
        If the file already exists, load it (I like to keep/edit the temp files across sessions).
        """
        from pathlib import Path  # to create a directory if needed
        from spyder.utils import encoding  # not needed, but more general
        from spyder.py3compat import to_text_string  # not needed, but more general
        from IPython import get_ipython  # to load a new instance of a file in the editor
        if not filename:
            filename = os.path.join(os.path.expanduser('~'), '.spyder-py3/temp.py')
        # if no environment is supplied, use temp.py in root directory,
        root = os.path.dirname(filename)
        # otherwise create a temp.py inside an <envname> directory
        if not envname:
            envname =''
            envdir = root
            editor_location = "It resides in the <root> environment."
        else: 
            # if directory <envname> does not exist, create it:
            envdir = os.path.join(root, 'envs', envname)
            Path(envdir).mkdir(parents=True, exist_ok=True)
            editor_location = "It resides in the <"+envname+"> environment."
        tempfile = os.path.join(envdir, os.path.basename(filename))
        # if temp.py file does not exist, create it
        if not os.path.isfile(tempfile):
            # Creating temporary file
            default = ['# -*- coding: utf-8 -*-',
                        '"""', '' "Spyder Editor", '',
                        "This is a temporary script file", '',
                        editor_location, '',
                        '"""', '', '']
            text = os.linesep.join([encoding.to_unicode(qstr)
                                    for qstr in default])
            encoding.write(to_text_string(text), tempfile, 'utf-8')
        # now load the new temp file
        ipython = get_ipython()
        ipython.magic(f"%edit {tempfile}")
        return None

**Comment by ptoche** [comment]
Related thought: If you save the environment-specific config files (`temp.py`, `spyder.ini`, etc.) in a subdirectory of `.spyder-py3`, the settings won't get lost even if you remove the environment.  Removing an environment can occur accidentally, as I've experienced before... in conda you're supposed to do something like `conda remove -n myenv`, but if you get the syntax mixed up and do something like `conda uninstall -n myenv` (I don't remember exactly), everything gets wiped off. So by keeping config files in `.spyder-py3`, it offers a bit of insurance against that.

**Comment by ccordoba12** [comment]
There's a command line option now to set a different config directory for Spyder: `--conf-dir`. That should cover this use case.

So, I'm going to close this issue.
