### ISSUE TITLE
Spyder 4.1.3 cannot assess to the network folder

### ISSUE THREAD

**Issue by Oridrew** [spyder-ide/spyder#12936]
### Issue Report Checklist

* [.] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [.] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [.] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [.] Restarted Spyder
    * [.] Reset preferences with ``spyder --reset``
    * [.] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [.] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After upgrading Spyder to version 4.1.3, I lost assess the network folder. I can navigate to local folders, but not to network folders.
In parallel, I installed a fresh Anaconda with the latest version of Spyder on another PC and I am having the same problem.

Everything is works in the IPython console. Therefore, I feel that the problem is with the Spyder IDE and only with the latest version (everything was fine before the update).

### Paste Traceback/Error Below (if applicable)

```python-traceback

FileNotFoundError: [WinError 3] The system cannot find the path specified: 'Z:\\emattitan\\Andrey\\Data'

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Win10 Pro

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

**Comment by steff456** [comment]
Hi @Oridrew,

Can you please give to us a step-by-step of how are you getting the error?
Is it present when you open, save or read a file in the ipython console?

**Comment by Oridrew** [comment]
I am ashamed to admit, but the day after installing a new version of the program and several attempts to make it work, everything started to work as it should. I can’t explain what has changed on both computers at the same time, but now everything is fine and I think that the case can be closed.
