### ISSUE TITLE
LSP Python restarting

### ISSUE THREAD

**Issue by dbau** [spyder-ide/spyder#12934]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
How can I prevent LSP Python to restart?
It restarts periodically, freezing spyder until the restart has finished.

Thanks!
Davide

**Comment by steff456** [comment]
Hi @dbau, 

We've been working really hard to stabilize the LSP, in the next release of Spyder 4.1.4. We upgraded jedi's version to the latest, we avoid the linter to get stuck and other fixes that we hope to enhance the experience with LSP.

Once Spyder's 4.1.4 is released please test it through and open a new issue if the error is still present.

**Comment by dbau** [comment]
Hi @steff456,

Thanks a lot for the information and for your work.

Best,
Davide

**Comment by dbau** [comment]
Hi, 

Could we have a pre-release fix for this?

Thanks,
Davide

**Comment by steff456** [comment]
Hi @dbau,

We are planning to do the release today/tomorrow, at the end we found more critical bugs that delayed the release of 4.1.4, thanks for your patience and hope this will enhance your experience with Spyder :)

**Comment by kai3341** [comment]
Has the same error. Rebuilding `venv` solved it.

**Comment by dbau-igenomix** [comment]
Hi @steff456,

Great work! Problem fixed now :)

Thanks a lot,
Davide
