### ISSUE TITLE
Searching file into working directory

### ISSUE THREAD

**Issue by PasaOpasen** [spyder-ide/spyder#12931]
Please add this feature:

If I'm opening some file I want to start searching it into my correct working directory, not in user directory

**Comment by steff456** [comment]
Hi @PasaOpasen,

Can you please give us further details of what feature do you want?
Please note that we already support different options in `search in`, 
![image](https://user-images.githubusercontent.com/20992645/83588460-11d19480-a517-11ea-80bc-08d503a5ba49.png)

**Comment by PasaOpasen** [comment]
I want this:

When I press File->Open file there will be openFileDialog into
