### ISSUE TITLE
Issue: Ask for help Spyder Anaconda crash by auto jump into new lines while typing

### ISSUE THREAD

**Issue by abcdhelia** [spyder-ide/spyder#12955]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [Yes ] Restarted Spyder
    * [Yes ] Reset preferences with ``spyder --reset``
    * [Yes ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [Yes ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Each line only allow me to type 2-3 words
I have been experiencing the problem of each line can only type 2 - 3 words.

For example:
line 1: pri
line 2: nt
line 3: (
line 4: )

Q1: Can someone advise me how to solve this issue? I tried to reset to factory default. It works for a while but it crash again like this. 

Q2: At the same time, i tried to update for Spyder using anaconda prompt too. But it comes out asking "Enter your command number" . Can someone tell me where to find this number?

#tried restart, reinstall anaconda, troubleshoot for Spyder, check for updates and reset Spyder to factory default.
#installed kite on Spyder

![Anaconda prompt](https://user-images.githubusercontent.com/66429596/83798514-f3b29280-a6d6-11ea-8d15-5932aeb1126c.jpg)
![Spyder python 3 7](https://user-images.githubusercontent.com/66429596/83798554-0331db80-a6d7-11ea-82ae-4c88aba17bb2.jpg)

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
I am expect to see
print(Hello World)

### Paste Traceback/Error Below (if applicable)

Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.

print()

print()

pr
Traceback (most recent call last):

  File "<ipython-input-3-07c73c38aafa>", line 1, in <module>
    pr

NameError: name 'pr' is not defined

n
Traceback (most recent call last):

  File "<ipython-input-4-ab0680a89434>", line 1, in <module>
    n

NameError: name 'n' is not defined

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 
* PyQt version: 
* Operating System name/version: Window 8.1 64bit operating system

### Dependencies

```
PASTE DEPENDENCIES HERE
```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by andfoy** [comment]
Hi @abcdhelia, thanks for reporting this issue, by looking at your description, it seems that you have some issues with your Anaconda installation, have you tried to uninstall and delete all the folders and try to install it again?

**Comment by abcdhelia** [comment]
Hi @andfoy, I tried to uninstall at control panel for Anaconda, eventually Anaconda also works well for other programming languages in my pc. I tried using Anaconda prompt, it does work and ask for "Enter your command number". Can you point out what's error or advise what should I do?

**Comment by bcolsen** [comment]
after you uninstall anaconda delete this folder C:\Users\<your-username>\Anaconda3\

Then download a new version of anaconda. If yours is installing spyder 4.0.1 it's rather old and many improvements have been made to spyder since

**Comment by abcdhelia** [comment]
> after you uninstall anaconda delete this folder C:\Users<your-username>\Anaconda3\
> 
> Then download a new version of anaconda. If yours is installing spyder 4.0.1 it's

**Comment by abcdhelia** [comment]
@bcolsen Ya, I tried by following as what u said. But now i realised it continuously execute the code once i click a run. I even tried CTRL + C to stop running. but sometimes it works n sometimes it doesnt. I have a Kite installation. Would it affect the Spyder 4?

**Comment by bcolsen** [comment]
> I have a Kite installation. Would it affect the Spyder 4?

Yes. You should uninstall Kite and Anaconda. The latest versions of Spyder will guide you through the Kite installation process.

**Comment by abcdhelia** [comment]
Alright. Thanks alot for the guidance. Good day.
