### ISSUE TITLE
Spyder crashes after installing Anaconda

### ISSUE THREAD

**Issue by statixx** [spyder-ide/spyder#12956]
**Problem Description** 
I installed Anaconda recently. 
When I run Spyder I get an error message stating Spyder crashed during the last session.

**What steps reproduce the problem?**
**What is the expected output? What do you see instead?**

Simply opening Spyder makes the problem showing up.
I followed the troubleshooting guidelines:
1) Restarting the computer => issue not solved
2) Upgrading Spyder => ok
3) Updating Spyder's dependencies and environment => the following issue appears:

```
"Executing transaction: - DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\aguiot\AppData\Local\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\aguiot\AppData\Local\Anaconda3\pythonw.exe, args are ['C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\cwp.py', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\pythonw.exe', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\aguiot\AppData\Local\Anaconda3\python.exe, args are ['C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\cwp.py', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\python.exe', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\aguiot\AppData\Local\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\aguiot\AppData\Local\Anaconda3\pythonw.exe, args are ['C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\cwp.py', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\pythonw.exe', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\aguiot\AppData\Local\Anaconda3\python.exe, args are ['C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\cwp.py', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\python.exe', 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\Scripts\\spyder-script.py', '--reset']
done
Rolling back transaction: | menuinst Exception
Traceback (most recent call last):
  File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 246, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\menuinst\__init__.py", line 74, in install
    _install(path, remove, prefix, mode='user')
  File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\Menu\\spyder_shortcut.jso- menuinst Exception
Traceback (most recent call last):
  File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 246, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\menuinst\__init__.py", line 74, in install
    _install(path, remove, prefix, mode='user')
  File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aguiot\\AppData\\Local\\Anaconda3\\Menu\\spyder_shortcut.jsodone

[WinError 87] The parameter is incorrect"
```

I got this other error message when I launch Spyder from Anaconda console:
```
Traceback (most recent call last):
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 961, in setup
self.completions.start_client(language='python')
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\spyder\plugins\completion\plugin.py", line 306, in start_client
client_started = client_info['plugin'].start_client(language)
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\plugin.py", line 212, in start_client
language_client['instance'].start()
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\site-packages\spyder\plugins\completion\languageserver\client.py", line 262, in start
env=new_env)
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\subprocess.py", line 800, in __init__
restore_signals, start_new_session)
File "C:\Users\aguiot\AppData\Local\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
startupinfo)
OSError: [WinError 87] The parameter is incorrect
```

**Versions**

* Spyder version: 4.0.1.
* Python version: 3.7.6.
* Qt version: 5.9.6.
* PyQt version: 5.9.2.
* Operating System name/version: Windows 10

**Dependencies**
Unfortunately, I cannot paste the dependencies... Doesn't work.

**Comment by andfoy** [comment]
Hi @statixx, thanks for reporting this issue, by looking at your description, it seems that you have some issues with your Anaconda installation, have you tried to uninstall and delete all the folders and try to install it again?

**Comment by ChrisCheesy** [comment]
Hi I just joined because i'm having a similar issue but all of this tech-talk is kind of going over my head as i'm new to this myself and don't want to create a new thread unnecessarily. How does one go about uninistalling anaconda on a mac? Simply going to applications and dragging to trash bin suffices?

**Comment by statixx** [comment]
Hi @andfoy, I think I have serious installation issues as well as dependency ones. 

I actually uninstall Anaconda (from Control Panel\Programs\Programs and Features) 3 times and reinstall it using the 64bit and Python 3.7 version installer. I always get the same error messages.

The thing is I am not sure about how clean is the uninstall process through \Programs and Features). Is it clean? Is there any better way to cleanly uninstall Anaconda?
I notice that, after unstalling it, I still have some Anaconda or Spyder-related folders on my C:\...

**Comment by bcolsen** [comment]
you should uninstall and then delete `C:\Users\<your-username>\Anaconda3\` (unless you installed it somewhere else) Then reinstall.

**Comment by statixx** [comment]
> you should uninstall and then delete `C:\Users\<your-username>\Anaconda3\` (unless you installed it somewhere else) Then reinstall.

As I wrote, I already uninstalled. Please, read my post before feeding it.

**Comment by bcolsen** [comment]
The thing is I am not sure about how clean is the uninstall process through \Programs and Features). Is it clean? Is there any better way to cleanly uninstall Anaconda?
I notice that, after unstalling it, I still have some Anaconda or Spyder-related folders on my C:...

Sorry for not being more clear, but you were asking about a clean uninstall. removing the anaconda3 folder, C:\Users\aguiot\AppData\Local\Anaconda3 in your case, should be a clean uninstall.

**Comment by statixx** [comment]
Ah ok, thank you. I usually do uninstall from Control Panel\Programs\Programs and Features (I use Windows) so I don't need to care where the files are located. How do you uninstall?

**Comment by bcolsen** [comment]
>How do you uninstall?

I usually use Linux, but on Windows I usually do the same as you. Anaconda can be a little different though.

**Comment by statixx** [comment]
So, as I wrote, I uninstalled many times. It doesn't solve my issue. Any suggestion?

**Comment by bcolsen** [comment]
Do you have Kite installed? That can install separately from Anaconda.

**Comment by statixx** [comment]
No, I don't. Ok I will try to donwload it. Thanks

**Comment by bcolsen** [comment]
I don't think that installing it will help. I was thinking that if it was installed separately from Anaconda it could be causing you trouble.

**Comment by statixx** [comment]
Ok. Does anyone can solve this issue?

**Comment by CAM-Gerlach** [comment]
Hey @statixx , sorry for the long delay before replying; I just happened to notice this issue while helping a user with another. It appears the problem is due to something with your Anaconda install outside of Spyder's control. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of these types of issues.

I would skip to Step 4 under [Basic Troubleshooting](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#recommended-troubleshooting-steps), and if those don't work, try those under [First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch). Also, it would be helpful if you could post the full output of ``conda list`` run from the Anaconda Prompt in the environment in which you are trying to launch Spyder (`base`, by default), inside details and literal tags like so:

~~~
<details>

```
<PASTE YOUR CONDA LIST OUTPUT HERE>
```

</details>
~~~

Thanks!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
