### ISSUE TITLE
f-string rendering in IPython: bug or feature?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#12995]
Can't quite tell:

<img src="https://user-images.githubusercontent.com/16495490/84334136-ad5fa680-aba2-11ea-8241-b335d0d7c96a.png" width="250">

It is in a way more intuitive, but also inconsistent relative to Editor - I don't mind it, just reporting as a possible bug.

**Comment by dalthviz** [comment]
Hi @OverLordGoldDragon thanks for your feedback! I think the Editor doesn't have support for the moment to highlight correctly the f-string syntax. Maybe this one is related to #7265
