### ISSUE TITLE
Missing fold marks in the Spyder 2 theme

### ISSUE THREAD

**Issue by brodders61** [spyder-ide/spyder#13009]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The code folding marks are present as are mouse-over-able and operate correctly, but are not visible.

Line 9 in the image is folded, lines 50 and 54 are not.

![MissingFoldMarks](https://user-images.githubusercontent.com/12859315/84502820-f271fe80-acb0-11ea-8bc5-1f9affd9dfbf.png)

### What steps reproduce the problem?

1. use Spyder (this is the most recent build: Anaconda3-2020.02-Windows-x86_64.exe)

### What is the expected output? What do you see instead?
As shown in image attached, the Line number column is now widthed to show the folding indication marks, which are present and clickable - but but not shown. The colour scheme is Spyder Dark with Spyder 2 icons.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
spyder                    4.0.1                    py37_0
spyder-kernels       1.8.1                    py37_0

* Python version:
python                    3.7.6                h60c2a47_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.7                   py37_0
python-libarchive-c       2.8                     py37_13

* Qt version:
qt                        5.9.7            vc14h73c81de_0

* PyQt version:
pyqt                      5.9.2            py37h6538335_2

* Operating System name/version: Windows 8.1 64bit

### Dependencies

```
PASTE DEPENDENCIES HERE
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

Thanks!

**Comment by juanis2112** [comment]
Hi @brodders61 thanks for reporting this. I will take a look!

**Comment by juanis2112** [comment]
We solved this issue in https://github.com/spyder-ide/spyder/pull/13015 so we should have this fixed in out new release. Thanks again @brodders61 for reporting this error.
