### ISSUE TITLE
Right-clicking an empty folder doesn't show the context menu of the Files pane

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13004]
Entering inside a folder without elements and then right clicking inside it doesn't show the context menu of the Files pane:
![explorer1](https://user-images.githubusercontent.com/16781833/84448408-3f51c880-ac10-11ea-9110-0240471561bb.gif)

_Originally posted by @dalthviz in https://github.com/spyder-ide/spyder/pull/12401#issuecomment-642978296_

**Comment by goanpeca** [comment]
@ccordoba12 do you think this should go for 4.1.4? Seems like an easy enough fix.

**Comment by ccordoba12** [comment]
Sure. @steff456, please take a look at this one.

**Comment by steff456** [comment]
I'm not able to reproduce this issue in macOs or linux in the current 4.x branch

![prueba](https://user-images.githubusercontent.com/20992645/84699863-e89e0480-af17-11ea-9c50-07937314646f.gif)

![image](https://user-images.githubusercontent.com/20992645/84699996-18e5a300-af18-11ea-8068-30e1e1086e49.png)
