### ISSUE TITLE
Feature Request and Issue: Reinstaniate Editor Button for code folding and syntax errors

### ISSUE THREAD

**Issue by EnderWiggin14** [spyder-ide/spyder#13014]
## Problem Description
The problem is that the the code folding arrows occasionally move to the lines above or below where they are supposed to be. The arrows then incorrectly associate the code to be folded. This sometimes generates additional incorrectly placed folding arrows. I know it has some kind of association with adding code directly before a foldable body of code, but that is about it.

The second issue is that occasionally syntax error warning will appear correctly but will not disappear when fixed. (i.e. code will compile and run as expected).

The feature request as a lazy-man's fix is a button to force the reinstancing of the editor to cause proper reallignment of the folding arrows and to fix the syntax error warnings.

### What steps reproduce the problem?
I don't pay enough attention to know what is causing the problem.
Restarting Spyder fixes the problem.

I cannot share code for work reasons. Also for work reasons no screenshots or videos are allowed.
```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 4.1.3
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

```

**Comment by juanis2112** [comment]
Hi @EnderWiggin14 thanks for reporting this. This was fixed in https://github.com/spyder-ide/spyder/pull/12912 so it will be available in our next release!
