### ISSUE TITLE
Wishlist item: Spyder 4 -> Raspberry Pi OS (Raspbian)

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#13010]
## Problem Description

Spyder in Raspbian pypi will not install on a Raspberry Pi OS (Raspbian) system.

### What steps reproduce the problem?

```pip3 install spyder```

### What is the expected output? What do you see instead?

Expected: Installed

Saw instead that Spyder 4 was not installed.

### Paste Traceback/Error Below (if applicable)

```
pip3 messages:

Collecting pyqtwebengine<5.13; python_version >= "3" (from spyder)
  Could not find a version that satisfies the requirement pyqtwebengine<5.13; python_version >= "3" (from spyder) (from versions: 5.14.0, 5.15.0)
No matching distribution found for pyqtwebengine<5.13; python_version >= "3" (from spyder)
```

## Versions

* Spyder version: pypi
* Python version: 3.7.3
* Qt version: 5
* PyQt version: python3-pyqt5 5.11.3+dfsg-1+rpi1+b3
* Operating System name/version: Raspbian GNU/Linux 10 (buster)

## Work-around

sudo apt install spyder3-3.3.3

**Comment by ccordoba12** [comment]
Unfortunately there no wheels for `pyqtwebengine` in that architecture, so you won't be able to install Spyder on it.

Sorry but there's nothing we can do about it.

**Comment by texadactyl** [comment]
I appreciate your position.  The maintainer of pyqtwebengine is commercial (Riverbank Computing Limited).  So, there is not even a chance of getting an update without writing them a check.

**Comment by texadactyl** [comment]
I am doing fine with Spyder 3.3 on my RPi 4 on Xubuntu 64-bit ARM.
