### ISSUE TITLE
Spyder wont open when using conda-forge packages on macOS

### ISSUE THREAD

**Issue by valverde667** [spyder-ide/spyder#13013]
Problem Description
After updating with conda update --all spyder will not open through Navigator or via terminal. The output when entering "spyder" in the terminal is:

**/Users/nickvalverde/anaconda3/bin/pythonw: line 3: /Users/nickvalverde/anaconda3/python.app/Contents/MacOS/python: No such file or directory**

I went followed the path and in python.app/ there are two directories 1) Contents and 2) pythonapp. 
The /Contents directory only has a file "lib" in it. 
The /pythonapp directory has the right path. That is, when I cd into /pythonapp there is /Contents/MacOS/python. 

It looks like the appropriate path is /Users/nickvalverde/anaconda3/python.app/pythonapp/Contents/MacOS.
However, I'm not sure how to go about fixing this or how this occurred in the first place. 

Versions
* Spyder version: 4.1.3
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: MacOS Catalina V:10.15.5

--Update
As a quick-fix I copied all the contents in .../python.app/pythonapp/Contents into 
.../python.app/Contents and now it works. Still odd though.

**Comment by juanis2112** [comment]
@valverde667 thanks for reporting this. Apparently this is a problem with the Spyder packages in Conda-forge. 

For now the solution you have will work but we will fix this in our next release! Thanks

**Comment by ccordoba12** [comment]
I hope this is solved by now (no else has reported this problem in the last couple of months).

If the problem persist, please let us know.
