### ISSUE TITLE
Spyder 4.1.3 does not render plots neither on the plot pane nor the console

### ISSUE THREAD

**Issue by astropherenia** [spyder-ide/spyder#13016]
<img width="960" alt="2" src="https://user-images.githubusercontent.com/65301293/84556711-9e1d5c00-ad4e-11ea-9b1d-ad969690356e.png">

### Issue Report Checklist

* [* ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [ *] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [* ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I can't see the plot output neither on the plot pane neither on the console, because I click the close button on the option of plot pane, now I don't know how return it back. since I can't see any plot and I've tried to reinstall several times and it still doesn't work at all.

### What steps reproduce the problem?

1. When try to plot any figure.
2. 
3. 

### What is the expected output? What do you see instead?
I expect that I can see my plot in the plot pane as usual, but nothing there. and when I did uncheck the mute inline in the console to show the plot in my console it also doesn't work. so the plot doesn't rendered neither on plot pane nor on the console.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> I can't see the plot output neither on the plot pane neither on the console, because I click the close button on the option of plot pane, now I don't know how return it back

Please go to the menu `View > Panes` and select the entry called `Plots` to get it back.
