### ISSUE TITLE
Spyder crashing even after installation and reinstallation

### ISSUE THREAD

**Issue by praveenkumar1980** [spyder-ide/spyder#13021]
This is common issue i am facing since long . The spyder is crashing very often
![image](https://user-images.githubusercontent.com/66399101/84587386-6bea2800-ae3c-11ea-86e2-a4c79b2676f5.png)

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This message is no longer displayed in our latest version (4.1.3). So please update to that version and try again.

**Comment by ccordoba12** [comment]
I'm leaving this one for you @goanpeca after this point. Just wanted to give my feedback.

**Comment by praveenkumar1980** [comment]
I tried this option also long back but then it failed . I had read your comments in another thread . I think Spyder has stuck in its own web and crashed . Jupyter is still better

**Comment by praveenkumar1980** [comment]
This is resolved now :


With this solution
conda install spyder-kernels=1.9.1
conda install spyder=4.1.3

But the kite is showing faulty. How to reset?

https://github.com/spyder-ide/spyder/issues/12709
