### ISSUE TITLE
Spyder does not run my new code - Error Message(Code did not run through)

### ISSUE THREAD

**Issue by Ahmed0028** [spyder-ide/spyder#13030]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
My pythpn script read some files (*.csv) and did some transformation and send the results  as files to Google drive . 

### What steps reproduce the problem?

1.  When I try to run the code I always get this Error-Massage 
"Code did not run through" even i've update  spyder to its last version but and restart the kernel and my PC as well but the probelem still. 

### What is the expected output? What do you see instead?

write some files to Google Drive 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

# Name                    Version                   Build  Channel
spyder                    4.1.3                    py37_0  

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version:  Windows 10  pro

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @Ahmed0028, thanks for the report. Is this error appearing on any script you run, or only on that specific script you mention?

Cheers

**Comment by Ahmed0028** [comment]
Hi @goanpeca  , the error appearing only on that specific script.  Thanks!

**Comment by goanpeca** [comment]
Could you share the script? Or a similar minimal example that we can run on our side to reproduce the issue?

**Comment by Ahmed0028** [comment]
Any part of my Script reproduce  the  issue, even just import some libraries 

For Example:
`import re
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import os
import datetime
import pygsheets
  
path  = 'C:/Users/Reports/'


#authorization
os.chdir(path+'credentials/')
gauth = GoogleAuth()

gauth.LoadCredentialsFile("mycreds.txt")
if gauth.credentials is None:
    gauth.LocalWebserverAuth()
elif gauth.access_token_expired:
    gauth.Refresh()
else:
    gauth.Authorize()
# Save the current credentials to a file
gauth.SaveCredentialsFile("mycreds.txt")

# connect to google sheet
gc = pygsheets.authorize(service_file=path+'credentials/pygsheet_serviceaccount.json')

# Create GoogleDrive instance with authenticated GoogleAuth instance.
drive = GoogleDrive(gauth)

def delta_define(value,variable):
    '''Adjustments done for specific value of variable as input to google ads script'''
    if variable=='zero_days_6':
        if value==1.0:
            return -0.5
        elif value>=0.9:
            return -0.35    


`

**Comment by goanpeca** [comment]
Is the problem only occurring when importing these libraries?

```python
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
import pygsheets
```

How did you install them?

**Comment by Ahmed0028** [comment]
No, the issue was reproduced  when i import these libs as well: 


`import os, os.path
import pandas as pd
import time
import datetime as dt
import numpy as np`

I've installed them using pip on Spyder command line.

**Comment by bcolsen** [comment]
Does your script run in the anaconda prompt with "python <script name>.py"?

**Comment by Ahmed0028** [comment]
NO. Also doesn't run on jupyter or any other Python environment.

**Comment by bcolsen** [comment]
If it doesn't run in python or jupyter then this seems like a problem in your code or with pygsheets. Unfortunately we don't have enough experience with this package to help you. Sorry.
