### ISSUE TITLE
spyder(python2.7) install failed

### ISSUE THREAD

**Issue by JonathanCao1** [spyder-ide/spyder#13036]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

AttributeError: 'module' object has no attribute 'UTC'
AttributeError: 'module' object has no attribute 'UTC'
AttributeError: 'module' object has no attribute 'UTC'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.6 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by steff456** [comment]
Hi @JonathanCao1 

Can you please give us further information of how you are getting this error?

**Comment by steff456** [comment]
Closing this issue because there was no follow-up answer in a week.
