### ISSUE TITLE
Large file defined in spyder 4.1.3

### ISSUE THREAD

**Issue by sweettyler** [spyder-ide/spyder#13044]
whenever a file has more than 2000 lines, spyder gives a large file warning:

                "One of the files in the editor or the file you are trying
                 to open contains more than 2000 lines.
                 Code folding and indent guidelines will be disabled for
                 this kind of files in order to prevent performance
                 degradation."

and disables code folding and indent guidelines.

According to my own tests (in function "request_folding(self)" , changing the if condition from "if total_lines > 2000 and self.code_folding" to "if total_lines > 5000 and self.code_folding"), 5000 lines is more appropriate in most cases. 

So I would like to suggest to increase the threshold from 2000 to 5000 if it is hard-coded, or just give the users a choice in the preference.

**Comment by steff456** [comment]
Hi @sweettyler,

We already remove this limitation for Spyder 4.1.4, please update once the release is done.

Thanks for reporting!
