### ISSUE TITLE
The window automatically is closed if I try to save or if I keep the editor file open for more then 3 min.

### ISSUE THREAD

**Issue by MariaCarmela** [spyder-ide/spyder#13058]
### What steps will reproduce the problem?

Hi evryone,
if I try to save my py file or if I keep the editor file open more then 3 minute, the application crashes and the window is closed. I've already tried to update spyder and conda, try to unistall and install the lastest version but nothing changes. How can I do?
Thanks in advance for the help.

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.4 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```

**Comment by ccordoba12** [comment]
@MariaCarmela, thanks for reporting. Please open the Anaconda Prompt and start Spyder with the following command

    spyder --report-segfault

After it crashes, please run again

    spyder --report-segfault

Then a dialog will be shown that will allow you to upload the crash report here to Github.

If no dialog appears, please look for a file called `faulthandler.log` in Spyder's configuration directory (`C:\Users\<your user>\.spyder-py3` on Windows; `/Users/<your user>/.spyder-py3` on macOS; or `/home/<your user>/.config/spyder-py3` on Linux) and upload it here.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
