### ISSUE TITLE
Incorrect error reported

### ISSUE THREAD

**Issue by dasdebashish17** [spyder-ide/spyder#13055]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have a class defined as:
class A2L_Singleton:
    __instance = None
    @staticmethod

```
    def getInstance():
        """ Static access method. """
        if A2L_Singleton.__instance == None:
            A2L_Singleton()
        return A2L_Singleton.__instance

    def __init__(self):
        """ Virtually private constructor. """
        if A2L_Singleton.__instance != None:
            raise Exception("This class is a singleton!")
        else:
            A2L_Singleton.__instance = self
            self.InitObjects()

    def InitObjects(self):
        self.A2L_INST = A2L()

```
I have some additional code/class build around the class mentioned above. There in some line. it throws error as mentioned below:

> AttributeError: 'A2L_Singleton' object has no attribute 'A2L_INST'

The error is quite misleading and makes it difficult to figure out the exact issue in my code.

### What steps reproduce the problem?
Not sure why this error occurs

### What is the expected output? What do you see instead?
No error/ the precise location of the error

### Paste Traceback/Error Below (if applicable)

```python-traceback

runfile('D:/_Code/python3/SIPConfigurator/_CodeRestructure/CanoeConfigGeneratorData.py', wdir='D:/_Code/python3/SIPConfigurator/_CodeRestructure')
Traceback (most recent call last):

  File "D:\_Code\python3\SIPConfigurator\_CodeRestructure\CanoeConfigGeneratorData.py", line 507, in <module>
    SIPConfigObj.Inst.ParseA2L()

  File "D:\_Code\python3\SIPConfigurator\_CodeRestructure\CanoeConfigGeneratorData.py", line 121, in ParseA2L
    self.A2L_INST.A2L_INST.Init(self.A2LFile)

AttributeError: 'A2L_Singleton' object has no attribute 'A2L_INST'

```

## Versions

* Spyder version:  4.1.3
* Python version: Python 3.7.3 64-bit 
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

```

**Comment by dasdebashish17** [comment]
After my analysis, I figured out the issue.

`
import re
import os
import hashlib
import json
from zipfile import ZipFile

""" Class to contain all relevant information for the A2L file """
class A2L:
    # Initialize with the a2l file name
    def __init__(self, A2LFile=''):
        self.Init(A2LFile)



    # Initialization function
    def Init(self, A2LFile):
        # Set the a2l file full path
        self.A2LFile = A2LFile
        # Update file checksum
        self.UpdateChecksum()
        # Update workspace directory
        self.SetWorkspaceDir()
        # Initialize the regular expression
        self.Init_Regex()
        # Initialize the dictionaries associated with data types
        self.Init_DataTypeDict()
        # Initialize the dictionary to hold the parsed a2l information
        self.Init_A2LDataDict()
        # Initialize the dictionary to hold the comment information
        self.Init_BlockCommentDict()
        # Initialize the list of block types for which data needs to be processed
        self.Init_BlockListToProcess()
        # Initialize flag to 0 to indicate a2l file has been initialized but not processed
        self.ProcessDataEna = 0



    def UpdateChecksum(self):
        """ Function to get the a2l file content checksum """
        self.FileChecksum = hashlib.md5(open(self.A2LFile, 'rb').read()).hexdigest()
`

When the function  `A2L.UpdateChecksum()` was called, `self.A2LFile` was not set to any file. So there was error in the call of `hashlib.md5`. But instead of showing this error, Python threw some other error (as mentioned in the error description). This is undesired.

**Comment by dalthviz** [comment]
Closing as not related with Spyder
