### ISSUE TITLE
why spyder is weaker in Automatically checking for code errors

### ISSUE THREAD

**Issue by MrCrazyCrab** [spyder-ide/spyder#13051]
## Problem Description

 spyder4.1.13 is weaker in Automatically checking for code errors than spyder 3.6

### What steps reproduce the problem?

Unable to detect duplicate words or some words imported but noe used. Sometime it can do it if i have restart the spyder. Howerver if i run the spyder all the time, it will be weaker in in Automatically checking for code errors. Althoght the Code hinting is better than before but not as good as checking errors. I both used ubuntu and windows and i met the much more in windows than ubuntu.

* Spyder version: 4.1.13
* Python version: 3.6.7
* Qt version: /
* PyQt version:/ 
* Operating System name/version:  windows 10

**Comment by dalthviz** [comment]
Hi @MrCrazyCrab sorry to heart that. I think we have made some improvements in the LSP for Windows that could prevent such behavior. They will be available for the next release of Spyder 4.1.4

Pinging @andfoy @ccordoba12 just in case they want to provide more feedback :)

**Comment by MrCrazyCrab** [comment]
@dalthviz  looking forward to the spyder4.1.4, and when can i use it? the spyder4.1.3 did not meet my expectations.

**Comment by ccordoba12** [comment]
@MrCrazyCrab, there were some issues on Windows when checking for errors, but they should be solved now.

4.1.4 should be available next week.

**Comment by dalthviz** [comment]
Closing due to lack of response
