### ISSUE TITLE
Load plugins on start up that were enabled (visible and shown) when shutting down

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#13067]
This will provide a faster startup time by loading only plugins that the user is actually using.

Require:
- [ ] Update the storage of available plugins (not only registered plugins)
- [ ] Create the help menu (panes) based on this new list and use mock actions (since the plugin is not started we cannot use the toggle view action from the plugin)
- [ ] Check plugins do not have side effects on other parts of the main window
- [ ] Create a method to load a plugin after startup. This method should do the register steps plus the initialization plus the on visible setup.

**Comment by ccordoba12** [comment]
This was implemented in Spyder 5.2.0.
