### ISSUE TITLE
Connecting remotely via ssh

### ISSUE THREAD

**Issue by sama2689** [spyder-ide/spyder#13065]
I have a server (which I will call the target server) that I can access via putty/WinSCP which I am trying to run spyder on remotely from my home computer. I am attempting to follow the instructions in the documentation here: https://docs.spyder-ide.org/ipythonconsole.html

I have installed anaconda, paramiko, and  spyder-kernels on the target server
After step 1 I get the following message

```
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-29742.json
```
So I copy the json to my computer, getting its address using `jupyter --runtime-dir ` and then proceed to steps 4 and 5. Now when it seems that my connection is working, I get an error within spyder. It says that there is an internal problem and yields the following error codes

```
Exception in comms call _send_comm_config:
  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 342, in _handle_remote_call
    buffer['call_kwargs'])
  File "/home/user/anaconda3/lib/python3.7/site-packages/spyder_kernels/comms/commbase.py", line 355, in _remote_callback
    raise CommError("No such spyder call type: %s" % call_name)
spyder_kernels.comms.commbase.CommError: No such spyder call type: _send_comm_config

```

Interestingly when I use ls in the terminal on the target server terminal on spyder all sub-directories list without a problem, but I always get the popup saying that spyder has encountered an internal error. Does anyone have any idea what might fix this? Seems to have something to do with the packages in the target server and how they compare to the packages in my host computer perhaps?

**Comment by ccordoba12** [comment]
What's the Spyder version in your home computer and the spyder-kernels version in your remote server?

I think your error is caused by a mismatch in those versions, but in order to be sure I need to know the info I mentioned above.

**Comment by sama2689** [comment]
> 
> 
> What's the Spyder version in your home computer and the spyder-kernels version in your remote server?
> 
> I think your error is caused by a mismatch in those versions, but in order to be sure I need to know the info I mentioned above.

Yes that's possible, the spyder version on my home computer is version 4.0.1 with kernels version 1.8.1 and the spyder versions on the target computer are 4.1.3 for spyder and 1.9.1 for the kernels. How would I get these to match? I'd like to just update both to the latest version but not sure how to do that through the console

**Comment by ccordoba12** [comment]
Please run these commands in your home computer to update to Spyder latest version there:

    conda update anaconda
    conda install spyder=4.1.3

That should fix this problem for you.
