### ISSUE TITLE
#feature request: Investigate changes in Git repository﻿

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#13074]
I am sorry if this feature already exists. I could not find it in spyder and I think it is so important and useful.
If it already exists please let me know where I can read about it?
If it does not exist:
I think it is so important to have spyder be more compatible with git, something like what pycharm has [here](https://www.jetbrains.com/help/pycharm/investigate-changes.html)

**Comment by goanpeca** [comment]
Hi @seyeeet, thanks for the request. Currently, support is limited and work for it is tracked on https://github.com/spyder-ide/spyder/issues/9001.

Cheers.
