### ISSUE TITLE
Spyder-4.1.3 can't remove Files to left.

### ISSUE THREAD

**Issue by Wusir2018** [spyder-ide/spyder#13082]
Hello everyone,
Thank you for your contribution.
Spyder-4.1.3 can't control the location of the `Files`. It can only be dock on right. Can you add a function like Spyder-3.3.6 to let the location of the `Files` dock on left ?

**Comment by steff456** [comment]
Hi @Wusir2018,

For moving the pane of `Files` you need to first go to `View>Lock panes and toolbars` and uncheck the option. Then you will be able to move around the panes as you want to. Once you have the look you want, you can lock the panes again so they will be fixed.

![files](https://user-images.githubusercontent.com/20992645/85433816-a2195d00-b54a-11ea-967c-308cf96d3bd5.gif)

Please let me know if that works

**Comment by Wusir2018** [comment]
Hey @steff456,
Yes, it works. Thank you very much!
