### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by 2019GETUP** [spyder-ide/spyder#13086]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda\anaconda\envs\python2\lib\site-packages\spyder\plugins\projects.py", line 147, in <lambda>
    lambda v: self.main.update_window_title())
  File "D:\Anaconda\anaconda\envs\python2\lib\site-packages\spyder\app\mainwindow.py", line 1310, in update_window_title
    title = '{0} - {1}'.format(path, title)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-5: ordinal not in range(128)
  elif res.tzname and res.tzname in time.tzname:

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 2.7.18
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  2.2.0 (OK)
pycodestyle >=2.3 :  2.6.0 (OK)
pygments >=2.0    :  2.5.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.6 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.17.0 (OK)
jedi >=0.9.0      :  0.15.2 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.7.4 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
py

**Comment by steff456** [comment]
Hi @2019GETUP,

Can you please update to the latest Spyder 3 version (3.3.6)? This issue is fixed in that release.

Please let me know if that works

**Comment by steff456** [comment]
Closing this issue because there was not a followup response after a week.
