### ISSUE TITLE
getcontext().prec causes Spyder to freeze up

### ISSUE THREAD

**Issue by bjgreene123** [spyder-ide/spyder#13106]
### What steps will reproduce the problem?

from decimal import *
getcontext().prec = 1
b = Decimal(0.1) + Decimal(0.2)

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by andfoy** [comment]
Hi @bjgreene123, thanks for reaching out, have you tried to update to the latest version of Spyder? Also, does the error also happens in a standard Python interpreter on your system?

**Comment by bjgreene123** [comment]
Hi. The version of Spyder I'm using is Spyder 4.0.1. I'll check if there is a newer version. I tried in a separate python3 interpreter through puTTY connecting to a Linux server at work and did not have the issue. I am working (from home) from a workplace-provided windows desktop and have limited privileges.

Thanks,
Betty


--
Betty J. Greene
deciBel Research, Inc.
325 Bob Heath Drive
Huntsville, AL  35806
bgreene@dbresearch.net<mailto:bgreene@dbresearch.net>
256-489-6830

________________________________

**Comment by andfoy** [comment]
Thanks @bjgreene123 for the followup, could you please update Spyder to 4.1.3 and confirm that this error does not occur on that version?

**Comment by bjgreene123** [comment]
Hi,


I downloaded python as part of Anaconda. Anaconda Navigator version is 1.9.12. It looks like the latest version of Spyder as part of the Anaconda version I have is 4.0.1. Do you know if there is a newer version of Anaconda that I might be able to download?


Thanks for your help,

Betty


--
Betty J. Greene
deciBel Research, Inc.
325 Bob Heath Drive
Huntsville, AL  35806
bgreene@dbresearch.net<mailto:bgreene@dbresearch.net>
256-489-6830


________________________________

**Comment by andfoy** [comment]
@bjgreene123, have you tried to execute `conda update spyder` in your current environment?

**Comment by ccordoba12** [comment]
@andfoy, unfortunately that usually gives dependency issues. The commands to perform a successful update are

    conda update anaconda
    conda install spyder=4.1.3

**Comment by andfoy** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.
Thanks for reporting!

**Comment by bjgreene123** [comment]
Thank you. I apologize for the lack of response. I was not able to update Spyder on my system since I don't have admin privileges. Thank you for your help.


--
Betty J. Greene
deciBel Research, Inc.
325 Bob Heath Drive
Huntsville, AL  35806
bgreene@dbresearch.net<mailto:bgreene@dbresearch.net>
256-716-0787

________________________________
