### ISSUE TITLE
Feature Request: "Run to here" in context menu

### ISSUE THREAD

**Issue by bsumlin** [spyder-ide/spyder#13117]
It would be a great feature if we could right-click somewhere in the code and choose "Run to here", which would run from the beginning of the script to, well, "here". This would be a quicker and simpler option than managing breakpoints.

**Comment by juanis2112** [comment]
Hey @bsumlin, thanks for opening this issue. This is actually very similar to running cells in the Editor so I don't think we will implement this for now.

To create a cell in the editor, type ```#%%```before and after the portion of the code you want to run and then use the "Run cell" icon in the top bar of the editor.

![cells](https://user-images.githubusercontent.com/18587879/85939416-f28e1300-b8da-11ea-8239-0153ebc5029a.gif)

**Comment by bsumlin** [comment]
It's not at all like running cells. What if I have a script with thirty cells, and I want to run from the beginning to halfway through cell 19?
