### ISSUE TITLE
TypeError: KiteClient.sig_response_ready in Kite's client

### ISSUE THREAD

**Issue by xavierricci** [spyder-ide/spyder#13121]
### What steps will reproduce the problem?

I the procedures on the uninstall of kite through the terminal. Then I found the kite folders on my macbook and i send them to trash, but now my spider give me this issue report constantly. 

i tryed to open a new enviroment in anaconda but the problem persist.

Should I unistall and reinstall all spider?

Thx

### Traceback
```python-traceback
  File "/Users/xaf/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
Traceback (most recent call last):
  File "/Users/xaf/opt/anaconda3/lib/python3.7/site-packages/spyder/plugins/completion/kite/client.py", line 173, in perform_request
    self.sig_response_ready.emit(req_id, response or {})
TypeError: KiteClient.sig_response_ready[int, dict].emit(): argument 2 has unexpected type 'str'
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.4 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
@xavierricci, thanks for reporting. We're not really sure what to do about your problem

@dalthviz, is there anything we could to prevent this?

**Comment by dalthviz** [comment]
I will need to check @ccordoba12.

Maybe for now @xavierricci , as a workaround, you could try to disable Kite from the preferences of Spyder? (if Spyder doesn't start check for the `spyder.ini` file which should be in `...\.spyder-py3\config` under your user, and change there the option `enable` under the `[kite]` section)

**Comment by dalthviz** [comment]
Note: After a quick check of the code, a validation could be added before emitting the signal as well as a message indicating that an unexpected result from Kite was received and you need to check your Kite installation (maybe we can add a link in that message to the Kite troubleshooting page or their link to contact support?).

**Comment by ccordoba12** [comment]
Agreed, those are very good ideas @dalthviz!
