### ISSUE TITLE
Pylint run fails

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#13141]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Launch Spyder

### What is the expected output? What do you see instead?
Spyder crashes

### Paste Traceback/Error Below (if applicable)

```python-traceback
% python3
Python 3.7.7 (default, Mar 10 2020, 15:43:33) 
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from spyder.app import start
>>> start.main()

spyder.api.plugins.options_from_conf
Warning: option "css_path" not found in section "help" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "locked" not found in section "help" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "plain_mode" not found in section "help" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "show_source" not found in section "help" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "console_shortcut" not found in section "help" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "font" not found in section "historylog" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "handle_links" not found in section "onlinehelp" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "history" not found in section "workingdir" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "workdir" not found in section "workingdir" of configuration!

spyder.api.plugins.options_from_conf
Warning: option "text_color" not found in section "profiler" of configuration!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/start.py", line 204, in main
    mainwindow.main()
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 4250, in main
    mainwindow = run_spyder(app, options, args)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 4124, in run_spyder
    main.setup()
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 1295, in setup
    plugin = module.PLUGIN_CLASS(self)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/pylint/plugin.py", line 60, in __init__
    top_max_entries=MAX_HISTORY_ENTRIES)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/pylint/widgets/pylintgui.py", line 260, in __init__
    self.set_filename(f)
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/pylint/widgets/pylintgui.py", line 287, in set_filename
    self.curr_filenames.pop(index)
IndexError: pop index out of range
>>> code True


```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by impact27** [comment]
Spyder runs if I delete the settings folder (~/.spyder-py3-dev)

**Comment by goanpeca** [comment]
Hi @impact27 

>Spyder runs if I delete the settings folder (~/.spyder-py3-dev)

You men it starts and the next start it fails, or the removal of the folder solved the issues?

The warning are harmless and will be removed when the new API migration is done. For the error that appears, it seems related to work on the PyLint plugin.

@steff456 please take a look.

**Comment by ccordoba12** [comment]
Closing because I think this no longer applies.
