### ISSUE TITLE
Spyder prints "code True" in internal console

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#13142]
When starting spyder with the master, I see:
```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> code True
```
`code True` is printed here:
https://github.com/spyder-ide/spyder/blob/fa39a2f4fd460bc6448ffc4845c3af95e539877b/spyder/plugins/onlinehelp/widgets.py#L263
Is that expected?

**Comment by goanpeca** [comment]
Hi @impact27, yes that is fixed on a separate PR from the API waiting to be merged. Namely https://github.com/spyder-ide/spyder/pull/12196/files#diff-e6c0de1a8bc04e019b4a8eda7e427176L263
