### ISSUE TITLE
Kernal problems

### ISSUE THREAD

**Issue by NelsonFana** [spyder-ide/spyder#13154]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I erased by mistake all the variables and now my kernal gives me tracebacks

**Comment by dalthviz** [comment]
Hi @NelsonFana sorry to hear that, but without anymore info there isn't much that we can do to help.

In the future, please provide info about your environment in general (OS, Python version, Spyder version, Dependencies version, etc) as listed in the issue template, and as many info to understand what could be happening (in your case, for example, the tracebacks). 

There is no much that we can do with the info provided, although if you keep facing some issue, please open another issue following the template and providing as much info as you can :)
