### ISSUE TITLE
Why is Spyder using libraries from base environment instead of virtual environment

### ISSUE THREAD

**Issue by jafetgado** [spyder-ide/spyder#13160]
I created and activated a virtual environment with virtualenv:

```none
virtualenv venv
source venv/bin/activate
```

Then I installed spyder kernels and other libraries in the virtual environment:

```none
pip install spyder-kernels==0.*
pip install numba==0.50
```

Then I launched Spyder in the virtual environment:
```
spyder
```

And I changed the python interpreter in Spyder to the correct path using: > Python > Preferences > Python interpreter > Use the following Python interpreter

My Python interpreter in my virtual environment is
```none
/Users/myname/venv/bin/python
```

**However**, when I import libraries in Spyder, rather than the libraries installed in the virtual environment, Spyder uses the libraries from the base Anaconda environment.

```Python
import numba
print(numba.__version__)
0.38.0
print(numba.__file__)
/anaconda3/lib/python3.6/site-packages/numba/__init__.py
```

This is causing all kinds of errors in my code.
What can I do to force Spyder to only use libraries installed in my virtual environment?

**Comment by andfoy** [comment]
Hi @jafetgado, thanks for opening this issue. From your description, it seems that you did not restart the console kernels/Spyder to apply the interpreter switch. Also, it is not clear if you installed Spyder in the virtualenv. Please try to restart the console kernels or Spyder and see if that fixes your issue

**Comment by jafetgado** [comment]
Yes, I restarted the console several times, but it did not resolve the issue. Spyder was installed with Anaconda, but I installed the Spyder-kernels in the virtual environment.

**Comment by ccordoba12** [comment]
> pip install spyder-kernels==0.*

What's your Spyder version? I mention it because that version of spyder-kernels doesn't work with Spyder 4.

**Comment by jafetgado** [comment]
My spyder version is 3.2.8.

**Comment by ccordoba12** [comment]
That's very old. Please update at least to 3.3.6 and try again.

**Comment by jafetgado** [comment]
I upgraded Anaconda Navigator to the most recent version, which came with Spyder 4.0.1 and Python 3.7.6. That alone solved the problem for me. Thank you.

**Comment by ccordoba12** [comment]
Glad to know! That version has a lot of bugs though, so I'd recommend to update again to 4.1.3.
