### ISSUE TITLE
Kernel fails to send config sometimes

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#13164]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The kernel is supposed to send the config when opening:

https://github.com/spyder-ide/spyder-kernels/blob/05476b35cf9e55787521c43f91dd5eedcb56c7a2/spyder_kernels/comms/frontendcomm.py#L183

But sometimes it doesn't! And it is known because I added this line:

https://github.com/spyder-ide/spyder-kernels/blob/05476b35cf9e55787521c43f91dd5eedcb56c7a2/spyder_kernels/comms/frontendcomm.py#L163

Which solves this exact problem.

I found a workaround in https://github.com/spyder-ide/spyder/pull/12134 that I could include in a standalone PR. But the problem remains: it should not be needed.

### What steps reproduce the problem?

1. The kernel connects to the comm but fails to send the configuration
2. The kernel sends a blocking request to the frontend (debugging / runfile / ...)
3. The frontend doesn't know the port to which the reply should be sent and the kernel is not listening to the shell channel (because it is waiting for a reply)

### What is the expected output? What do you see instead?

This causes a comm timeout error. I have no idea why the kernel fails to send the config. 

### Solutions
1 - Figure out why the config is not sent
2 - Always send the config with every message

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> I found a workaround in #12134 that I could include in a standalone PR

Please do, so I can include it for 4.1.4.

> But the problem remains: it should not be needed.

Perhaps things could be solved if we moved to use the control channel instead of our own (dedicated) commsn channel? I say it because that channel is present by default (which could be part of the issue).

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder-kernels/pull/230

**Comment by ccordoba12** [comment]
Thanks a lot @impact27!

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder/pull/13166

**Comment by impact27** [comment]
I think #13174 is a more reliable way of fixing this issue

**Comment by ccordoba12** [comment]
Ok, thanks for your work on this. I'll review it and try to include it for 4.1.4
