### ISSUE TITLE
spyder 问题

### ISSUE THREAD

**Issue by cixisy** [spyder-ide/spyder#13177]
spyder 使用tensorflow的时候报错

**Comment by juanis2112** [comment]
Can you post here the steps that reproduced this problem along with the output of `conda list` in your terminal or anaconda prompt?

**Comment by cixisy** [comment]
Thank you. I've worked it out

发送自 Windows 10 版邮件应用

发件人: Juanita Gomez
发送时间: 2020年7月4日 5:52
收件人: spyder-ide/spyder
抄送: AS; Author
主题: Re: [spyder-ide/spyder] spyder 问题 (#13177)

Can you post here the steps that reproduced this problem along with the output of conda list in your terminal or anaconda prompt?

**Comment by juanis2112** [comment]
Im glad!
