### ISSUE TITLE
Issue when opening spyder 4

### ISSUE THREAD

**Issue by jpoubelle** [spyder-ide/spyder#13182]
Hi there,

I have had some troubles with my computer lately forcing me to perform a system restore (I run on Windows).
I made a conda update anaconda in my conda prompt
this lead to a spyder update to spyder 4, just as I had before my system restore

Nevertheless, since then I have the Following message when opeing spyder : 

You have missed depencies !
pyls >=0.31.2;<0.32.0 : 0 .1.6

So I have a pyls librairie installed which is at version 0.1.6 (and does not at all exist at version 0.31.XX) AND a python-langage-server librairie which is at version 0.31.7.

It seems to me that I have a kind of name conflict here that I do not know how to solve. 

Does someone have a clue ?

Thanks

**Comment by ccordoba12** [comment]
> So I have a pyls librairie installed which is at version 0.1.6

Please remove that library, Spyder doesn't really need it. It requires the Python module called `pyls`, provided by the `python-langage-server`, which you already have installed.

**Comment by jpoubelle** [comment]
Hi,

thanks so much for the reply. I removed the Library no problem. nevertheless I keep on getting this message at each stratup. How could I remove it ?

Thanks

**Comment by ccordoba12** [comment]
Please post the output of `conda list`, to better understand what's your problem.

**Comment by jpoubelle** [comment]
Thanks for taking time to look

here it is, attached to this post.
[list.txt](https://github.com/spyder-ide/spyder/files/4886647/list.txt)

**Comment by ccordoba12** [comment]
The output seems correct. What operating system (Windows, Linux, macOS) are you using?

**Comment by jpoubelle** [comment]
I am using Windows 10.

**Comment by jpoubelle** [comment]
Also, spyder stopped indicating me errors in the left margin since this error showed up.
I had the error since I migrated to spyder 4. It worked well at first and then I had to perform a system recovery and everything seems kind of slightly broken since then.

How could I perform a clean uninstall of everything then reinstall everything at the same version (I do not want to loose all my code…)

thank you so much if you have any idea.

**Comment by ccordoba12** [comment]
I think you installed some packages with pip and they are conflicting with the ones that come with Anaconda. So please go to this directory

    C:\Users\<your user>\AppData\Roaming\Python\

remove all subdirectories there and try again.

**Comment by jpoubelle** [comment]
I have no Python directory in Roaming… should I add one ?

**Comment by ccordoba12** [comment]
No, don't worry. I'm afraid you'll have to reinstall Anaconda for things to work correctly again.

Please follow the instructions in our video to learn how to do that:

https://www.youtube.com/watch?v=Ul79ihg41Rs

**Comment by jpoubelle** [comment]
So OK, everything is back to normal thanks to the "unmess your mess" step. I did not have to re install everything but the video helped me solve it.

Thank you so much !

**Comment by ccordoba12** [comment]
Pinging @juanis2112 about this one (who is the one that made that video). Thanks @juanis2112 for all the work you put on it! As you can see, that's helping users such as @jpoubelle to have Spyder working again.

**Comment by juanis2112** [comment]
@jpoubelle Im glad you fixed your issue.
@ccordoba12 Im glad I could help
