### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by hyejung-rachel** [spyder-ide/spyder#13193]
### What steps will reproduce the problem?

I installed anaconda3 and python2.7 virtual environment. When  I open spyder using py2 environment it crashes upon startup. Is there any workaround without installing anaconda2 on top of anaconda3?

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
This could be fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.3

**Comment by hyejung-rachel** [comment]
I tried to update spyder to 4.1.3 in the py2 environment and received the
following error message:

Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: failed with repodata from current_repodata.json, will
retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with
flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining spyder=4.1.3:
100%|████████████████████████████████████████████████████████████| 2/2
[00:00<00:00, 16.84it/s]\failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your
environment:

Specifications:

  - spyder=4.1.3 ->
python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']

Your python: python=2.7

If python is on the left-most side of the chain, that's the version you've
asked for.
When python appears to the right, that indicates that the thing on the left
is somehow
not available for the python version you are constrained to. Note that
conda will not
change your python version to a different minor version unless you
explicitly specify
that.

Take note: I downloaded anaconda3 but I wanted to run python2 in an
anaconda environment I created (py2). I successfully updated spyder to
4.1.3 in base (python3) env but it still doesn't work.
Do you have any workarounds? Thank you!t

**Comment by ccordoba12** [comment]
I'm very sorry, I forgot Anaconda stopped creating packages for Python 2 in February. So if you still need to use Python 2 for your code, but have the latest Spyder version to avoid the problem you mentioned, please follow these steps:

* Create a new environment for Python 3.7 and install Spyder 4.1.3 on it, with the following command:

    conda create -n spyder-py3 python=3.7 spyder=4.1.3

* Create a different environment for Python 2 and install `spyder-kernels` on it with pip. That's because there are no conda packages available for the `spyder-kernels` version required by Spyder 4.1.3. You can do that with the following commands:

    conda create -n py2-env python=2
    conda activate py2-env
    pip install spyder-kernels

* Follow [our guide](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#working-with-other-environments-and-python-installations) to connect the Python interpreter in `py2-env` with the Spyder you installed in `spyder-py3`. Or you can also watch [our video](https://youtu.be/Ul79ihg41Rs?t=399) about that.
