### ISSUE TITLE
Spyder saves files before running code cells (but should not)

### ISSUE THREAD

**Issue by adriesse** [spyder-ide/spyder#13197]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

As commented in #12651 Spyder saves files when a cell is run.  Some versions ago it did not do this, and probably it shouldn't.

### What steps reproduce the problem?

1. Change some code or comment.
2. Run a code cell.

### What is the expected output? What do you see instead?
Expected: file not saved.
Instead: file saved.

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.2
* Qt version: 
* PyQt version: 
* Operating System name/version: Win7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.2.1 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  0.6.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.3.1 (OK)
numpydoc >=0.6.0               :  0.8.0 (OK)
paramiko >=2.4.0               :  2.4.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.4.8 (OK)
pygments >=2.0                 :  2.3.1 (OK)
pylint >=0.25                  :  2.2.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.5.7 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.5.2 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  1.8.2 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  17.1.2 (OK)

# Optional:
cython >=0.21                  :  0.29.2 (OK)
matplotlib >=2.0.0             :  3.0.2 (OK)
numpy >=1.7                    :  1.15.4 (OK)
pandas >=0.13.1                :  0.24.2 (OK)
scipy >=0.17.0                 :  1.2.1 (OK)
sympy >=0.7.3                  :  1.3 (OK)

```

**Comment by impact27** [comment]
The relevant code is:
https://github.com/spyder-ide/spyder/blob/0ea6b2b90fdd1cb6798ef163c36407532abd4716/spyder/plugins/ipythonconsole/widgets/shell.py#L616

So it should save the file only if you have the "save_all_before_run" option enabled. Is that your case?

**Comment by adriesse** [comment]
I don't think it should ever save anything when just running a cell, and the option should be for running a whole file.  Since I have the option turned off now, it doesn't matter so much which way you go as long as the intent is clear.

**Comment by ccordoba12** [comment]
This is not what I'm seeing on my end:

![Selección_001](https://user-images.githubusercontent.com/365293/86625972-9f2b5d00-bf8b-11ea-8021-8ec1bd284411.png)

As you can see, I'm running a cell in an untitled, unsaved file. Besides, I think @impact27 added a test for this, so we're sure that functionality is still in place and working as expected.

So you need to give us a reproducible way to generate your problem in order for us to understand what's happening in your case.

**Comment by impact27** [comment]
I think the problem is with an existing, modified file. In this case the file would be saved. I think it woul dmake sense to not save the file in this case.

**Comment by ccordoba12** [comment]
Agreed. Could you take a look at that @impact27?
