### ISSUE TITLE
Spyder code not able to access the variables in the variable explorer. 

### ISSUE THREAD

**Issue by TJTapajyoti** [spyder-ide/spyder#13199]
## Problem Description
Using spyder version 4.0.1 in anaconda. My code is unable to access and use the variables shown in the variable explorer. The console can access it but the not the raw code.

I am very sure previous spyder versions could use the variables stored in the variable explorer. It should be noted that the console can access the variable df. Just the code cannot.

### What steps reproduce the problem?

Example : I read a csv file and run pandas. The csv file is stored in a dataframe called df. df is now stored and shown in the variable explorer. However if I remove/comment the df=pd.read_csv(..) line, calling df does not work in my code.

### What is the expected output? What do you see instead?
Suppose this read_csv line is reading a large file. Takes many seconds to be read. I used to read it once. The variable got stored in the variable explorer and then I used to comment out the read_csv line and the code used to work perfectly and faster. I have used this so many times before.
Now the code refuses to access the variable from the explorer and says variable not found. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0.1
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @TJTapajyoti, thanks for the report. Do you have this option selected?

<img width="516" alt="Screen Shot 2020-07-06 at 12 05 23" src="https://user-images.githubusercontent.com/3627835/86619883-fbd54a80-bf80-11ea-8477-f391ef1cfc3c.png">

Cheers

**Comment by TJTapajyoti** [comment]
HI Thank you so much for the solution. I did not know of this setting inside Spyder. It is working perfectly - solved.
