### ISSUE TITLE
Crazy issue with unrecognized global variable from the console

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#13212]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Running file with F5 does not 'mount' global variables properly in the console.
Seems like they have different namespace!!!

### What steps reproduce the problem?

I edit `foo.py` and write

```
def foo():
    global x
    x=1
```
then launch this file (F5)
In the console (ipython 7.16.1), I run
`foo()`
runs fine, foo() is known.
`x`
return "NameError: name 'x' is not defined"

### What is the expected output? What do you see instead?
1

if I write in the file at the end
```
foo()
print(x)
```
It works (output 1 in the console after F5).
If I write the `foo()` function code directly in the console, it works...
Note that I `%reset` console each time to avoid hanging variables.
Defining `x` previously both in the file or in the console does not help.

Sound crazy...

## Versions

* Spyder version: both with last master & 4.1.3
* Python version: 3.6
* Operating System name/version: Win10

**Comment by steff456** [comment]
Hi @sylvain-bougnoux,

This happens in Spyder 4 because the files are executed in a clean namespace so we will not be taking into account defined variables in the console. In this way, the code you create is highly reproducible. If you want to have the previous behavior you can go to `Run>Configuration per file` and activate the option `Run in console's namespace instead of an empty one`.

Hope this works and thanks for reporting!

**Comment by sylvain-bougnoux** [comment]
Thanks you very much for you prompt answer. I understand. But how can you make it clearer for a beginner. I don’t mean your explanation, but as a warning when launching the console, or so... This kind of behavior in spyder is a pure source of frustration driving nuts, when e.g. copying the code from someone else. Is this well known or not, I am not sure? For me it is a disaster. But I do understand that the other solution/option could also be error prone. Honestly I’ve never noticed before this very important subtlety. Thanks again.

Ce message et toutes les pièces jointes sont confidentiels et établis a l'intention exclusive de ses destinataires.
 Toute utilisation ou diffusion non autorisée est interdite. 
 
 This message and any attachments are confidential and intended solely for the addresses.
 Any unauthorised use or dissemination is prohibited.

**Comment by steff456** [comment]
When we changed the default option, we knew that old users will be confused. Right now we are working on documentation for all the panels of Spyder, we can add a friendly message on the documentation were this behavior is explained for beginners and new users. Thanks for the idea!

**Comment by sylvain-bougnoux** [comment]
Actually it seems more severe than that, & still weird for me. When pressing F5 on the file, the `foo()` function gets transferred to the console namespace. Thus when calling `foo() `**from the console**, at 1st glance, it should be run in the console namespace, and thus `x` should appear in same namespace, but it does not. So you mean `foo()` is in the console namespace, but when executed (from the console) _still run in a clean namespace_? And the same `foo()` (the same code), depending on how it arrived in the console, produces different behaviors!

I understand that it is wiser to start from a clean namespace when F5, to avoid pollution from the console (as context or input). But every output (definition, variable...) should be transferred to the console, and everything from the console should be run in the console... The option you pointed out should concern the input but not the output.

Last remark, if `def foo()` is in a cell, and this cell executed, the old behavior is used. `x` gets defined when calling `foo()` from the console. I do think this inconsistency (between F5 & ctrl+return) is largely puzzling.

Sorry for being long, but it sounds important.
