### ISSUE TITLE
Spyder 4.1.3 broken after conda update --all

### ISSUE THREAD

**Issue by DiegoF90** [spyder-ide/spyder#13228]
## Problem Description

My spyder 3.1.4 installation works fine in an environment with the following packages:

> _license                  1.1                      py36_1    https://repo.continuum.io/pkgs/free
> alabaster                 0.7.10                   py36_0    https://repo.continuum.io/pkgs/free
> anaconda                  4.4.0               np112py36_0    https://repo.continuum.io/pkgs/free
> anaconda-client           1.6.3                    py36_0    https://repo.continuum.io/pkgs/free
> anaconda-navigator        1.6.2                    py36_0    https://repo.continuum.io/pkgs/free
> anaconda-project          0.6.0                    py36_0    https://repo.continuum.io/pkgs/free
> asn1crypto                0.22.0                   py36_0    https://repo.continuum.io/pkgs/free
> astroid                   1.4.9                    py36_0    https://repo.continuum.io/pkgs/free
> astropy                   1.3.2               np112py36_0    https://repo.continuum.io/pkgs/free
> babel                     2.4.0                    py36_0    https://repo.continuum.io/pkgs/free
> backports                 1.0                      py36_0    https://repo.continuum.io/pkgs/free
> beautifulsoup4            4.6.0                    py36_0    https://repo.continuum.io/pkgs/free
> bitarray                  0.8.1                    py36_1    https://repo.continuum.io/pkgs/free
> blaze                     0.10.1                   py36_0    https://repo.continuum.io/pkgs/free
> bleach                    1.5.0                    py36_0    https://repo.continuum.io/pkgs/free
> bokeh                     0.12.5                   py36_1    https://repo.continuum.io/pkgs/free
> boto                      2.46.1                   py36_0    https://repo.continuum.io/pkgs/free
> bottleneck                1.2.1               np112py36_0    https://repo.continuum.io/pkgs/free
> bzip2                     1.0.6                    vc14_3  [vc14]  https://repo.continuum.io/pkgs/free
> cffi                      1.10.0                   py36_0    https://repo.continuum.io/pkgs/free
> chardet                   3.0.3                    py36_0    https://repo.continuum.io/pkgs/free
> click                     6.7                      py36_0    https://repo.continuum.io/pkgs/free
> cloudpickle               0.2.2                    py36_0    https://repo.continuum.io/pkgs/free
> clyent                    1.2.2                    py36_0    https://repo.continuum.io/pkgs/free
> colorama                  0.3.9                    py36_0    https://repo.continuum.io/pkgs/free
> comtypes                  1.1.2                    py36_0    https://repo.continuum.io/pkgs/free
> conda                     4.3.21                   py36_0    https://repo.continuum.io/pkgs/free
> conda-env                 2.6.0                         0    https://repo.continuum.io/pkgs/free
> console_shortcut          0.1.1                    py36_1    https://repo.continuum.io/pkgs/free
> contextlib2               0.5.5                    py36_0    https://repo.continuum.io/pkgs/free
> cryptography              1.8.1                    py36_0    https://repo.continuum.io/pkgs/free
> curl                      7.52.1                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
> cycler                    0.10.0                   py36_0    https://repo.continuum.io/pkgs/free
> cython                    0.25.2                   py36_0    https://repo.continuum.io/pkgs/free
> cytoolz                   0.8.2                    py36_0    https://repo.continuum.io/pkgs/free
> dask                      0.14.3                   py36_1    https://repo.continuum.io/pkgs/free
> datashape                 0.5.4                    py36_0    https://repo.continuum.io/pkgs/free
> decorator                 4.0.11                   py36_0    https://repo.continuum.io/pkgs/free
> distributed               1.16.3                   py36_0    https://repo.continuum.io/pkgs/free
> docutils                  0.13.1                   py36_0    https://repo.continuum.io/pkgs/free
> entrypoints               0.2.2                    py36_1    https://repo.continuum.io/pkgs/free
> et_xmlfile                1.0.1                    py36_0    https://repo.continuum.io/pkgs/free
> fastcache                 1.0.2                    py36_1    https://repo.continuum.io/pkgs/free
> flask                     0.12.2                   py36_0    https://repo.continuum.io/pkgs/free
> flask-cors                3.0.2                    py36_0    https://repo.continuum.io/pkgs/free
> freetype                  2.5.5                    vc14_2  [vc14]  https://repo.continuum.io/pkgs/free
> get_terminal_size         1.0.0                    py36_0    https://repo.continuum.io/pkgs/free
> gevent                    1.2.1                    py36_0    https://repo.continuum.io/pkgs/free
> greenlet                  0.4.12                   py36_0    https://repo.continuum.io/pkgs/free
> h5py                      2.7.0               np112py36_0    https://repo.continuum.io/pkgs/free
> hdf5                      1.8.15.1                 vc14_4  [vc14]  https://repo.continuum.io/pkgs/free
> heapdict                  1.0.0                    py36_1    https://repo.continuum.io/pkgs/free
> html5lib                  0.999                    py36_0    https://repo.continuum.io/pkgs/free
> icu                       57.1                     vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
> idna                      2.5                      py36_0    https://repo.continuum.io/pkgs/free
> imagesize                 0.7.1                    py36_0    https://repo.continuum.io/pkgs/free
> ipykernel                 4.6.1                    py36_0    https://repo.continuum.io/pkgs/free
> ipython                   5.3.0                    py36_0    https://repo.continuum.io/pkgs/free
> ipython_genutils          0.2.0                    py36_0    https://repo.continuum.io/pkgs/free
> ipywidgets                6.0.0                    py36_0    https://repo.continuum.io/pkgs/free
> isort                     4.2.5                    py36_0    https://repo.continuum.io/pkgs/free
> itsdangerous              0.24                     py36_0    https://repo.continuum.io/pkgs/free
> jdcal                     1.3                      py36_0    https://repo.continuum.io/pkgs/free
> jedi                      0.10.2                   py36_2    https://repo.continuum.io/pkgs/free
> jinja2                    2.9.6                    py36_0    https://repo.continuum.io/pkgs/free
> jpeg                      9b                       vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
> jsonschema                2.6.0                    py36_0    https://repo.continuum.io/pkgs/free
> jupyter                   1.0.0                    py36_3    https://repo.continuum.io/pkgs/free
> jupyter_client            5.0.1                    py36_0    https://repo.continuum.io/pkgs/free
> jupyter_console           5.1.0                    py36_0    https://repo.continuum.io/pkgs/free
> jupyter_core              4.3.0                    py36_0    https://repo.continuum.io/pkgs/free
> lazy-object-proxy         1.2.2                    py36_0    https://repo.continuum.io/pkgs/free
> libpng                    1.6.27                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
> libtiff                   4.0.6                    vc14_3  [vc14]  https://repo.continuum.io/pkgs/free
> llvmlite                  0.18.0                   py36_0    https://repo.continuum.io/pkgs/free
> locket                    0.2.0                    py36_1    https://repo.continuum.io/pkgs/free
> lxml                      3.7.3                    py36_0    https://repo.continuum.io/pkgs/free
> markupsafe                0.23                     py36_2    https://repo.continuum.io/pkgs/free
> matplotlib                2.0.2               np112py36_0    https://repo.continuum.io/pkgs/free
> menuinst                  1.4.7                    py36_0    https://repo.continuum.io/pkgs/free
> mistune                   0.7.4                    py36_0    https://repo.continuum.io/pkgs/free
> mkl                       2017.0.1                      0    https://repo.continuum.io/pkgs/free
> mkl-service               1.1.2                    py36_3    https://repo.continuum.io/pkgs/free
> mpmath                    0.19                     py36_1    https://repo.continuum.io/pkgs/free
> msgpack-python            0.4.8                    py36_0    https://repo.continuum.io/pkgs/free
> multipledispatch          0.4.9                    py36_0    https://repo.continuum.io/pkgs/free
> navigator-updater         0.1.0                    py36_0    https://repo.continuum.io/pkgs/free
> nbconvert                 5.1.1                    py36_0    https://repo.continuum.io/pkgs/free
> nbformat                  4.3.0                    py36_0    https://repo.continuum.io/pkgs/free
> networkx                  1.11                     py36_0    https://repo.continuum.io/pkgs/free
> nltk                      3.2.3                    py36_0    https://repo.continuum.io/pkgs/free
> nose                      1.3.7                    py36_1    https://repo.continuum.io/pkgs/free
> notebook                  5.0.0                    py36_0    https://repo.continuum.io/pkgs/free
> numba                     0.33.0              np112py36_0    https://repo.continuum.io/pkgs/free
> numexpr                   2.6.2               np112py36_0    https://repo.continuum.io/pkgs/free
> numpy                     1.12.1                   py36_0    https://repo.continuum.io/pkgs/free
> numpydoc                  0.6.0                    py36_0    https://repo.continuum.io/pkgs/free
> odo                       0.5.0                    py36_1    https://repo.continuum.io/pkgs/free
> olefile                   0.44                     py36_0    https://repo.continuum.io/pkgs/free
> openpyxl                  2.4.7                    py36_0    https://repo.continuum.io/pkgs/free
> openssl                   1.0.2l                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
> packaging                 16.8                     py36_0    https://repo.continuum.io/pkgs/free
> pandas                    0.20.1              np112py36_0    https://repo.continuum.io/pkgs/free
> pandocfilters             1.4.1                    py36_0    https://repo.continuum.io/pkgs/free
> partd                     0.3.8                    py36_0    https://repo.continuum.io/pkgs/free
> path.py                   10.3.1                   py36_0    https://repo.continuum.io/pkgs/free
> pathlib2                  2.2.1                    py36_0    https://repo.continuum.io/pkgs/free
> patsy                     0.4.1                    py36_0    https://repo.continuum.io/pkgs/free
> pep8                      1.7.0                    py36_0    https://repo.continuum.io/pkgs/free
> pickleshare               0.7.4                    py36_0    https://repo.continuum.io/pkgs/free
> pillow                    4.1.1                    py36_0    https://repo.continuum.io/pkgs/free
> pip                       9.0.1                    py36_1    https://repo.continuum.io/pkgs/free
> ply                       3.10                     py36_0    https://repo.continuum.io/pkgs/free
> prompt_toolkit            1.0.14                   py36_0    https://repo.continuum.io/pkgs/free
> psutil                    5.2.2                    py36_0    https://repo.continuum.io/pkgs/free
> py                        1.4.33                   py36_0    https://repo.continuum.io/pkgs/free
> pycosat                   0.6.2                    py36_0    https://repo.continuum.io/pkgs/free
> pycparser                 2.17                     py36_0    https://repo.continuum.io/pkgs/free
> pycrypto                  2.6.1                    py36_6    https://repo.continuum.io/pkgs/free
> pycurl                    7.43.0                   py36_2    https://repo.continuum.io/pkgs/free
> pyflakes                  1.5.0                    py36_0    https://repo.continuum.io/pkgs/free
> pygments                  2.2.0                    py36_0    https://repo.continuum.io/pkgs/free
> pylint                    1.6.4                    py36_1    https://repo.continuum.io/pkgs/free
> pynput                    1.6.8                     <pip>
> pyodbc                    4.0.16                   py36_0    https://repo.continuum.io/pkgs/free
> pyopenssl                 17.0.0                   py36_0    https://repo.continuum.io/pkgs/free
> pyparsing                 2.1.4                    py36_0    https://repo.continuum.io/pkgs/free
> pyqt                      5.6.0                    py36_2    https://repo.continuum.io/pkgs/free
> pytables                  3.2.2               np112py36_4    https://repo.continuum.io/pkgs/free
> pytest                    3.0.7                    py36_0    https://repo.continuum.io/pkgs/free
> python                    3.6.1                         2    https://repo.continuum.io/pkgs/free
> python-dateutil           2.6.0                    py36_0    https://repo.continuum.io/pkgs/free
> pytz                      2017.2                   py36_0    https://repo.continuum.io/pkgs/free
> pywavelets                0.5.2               np112py36_0    https://repo.continuum.io/pkgs/free
> pywin32                   220                      py36_2    https://repo.continuum.io/pkgs/free
> pyyaml                    3.12                     py36_0    https://repo.continuum.io/pkgs/free
> pyzmq                     16.0.2                   py36_0    https://repo.continuum.io/pkgs/free
> qt                        5.6.2                    vc14_4  [vc14]  https://repo.continuum.io/pkgs/free
> qtawesome                 0.4.4                    py36_0    https://repo.continuum.io/pkgs/free
> qtconsole                 4.3.0                    py36_0    https://repo.continuum.io/pkgs/free
> qtpy                      1.2.1                    py36_0    https://repo.continuum.io/pkgs/free
> requests                  2.14.2                   py36_0    https://repo.continuum.io/pkgs/free
> rope                      0.9.4                    py36_1    https://repo.continuum.io/pkgs/free
> ruamel_yaml               0.11.14                  py36_1    https://repo.continuum.io/pkgs/free
> scikit-image              0.13.0              np112py36_0    https://repo.continuum.io/pkgs/free
> scikit-learn              0.18.1              np112py36_1    https://repo.continuum.io/pkgs/free
> scipy                     0.19.0              np112py36_0    https://repo.continuum.io/pkgs/free
> seaborn                   0.7.1                    py36_0    https://repo.continuum.io/pkgs/free
> selenium                  3.141.0                   <pip>
> setuptools                27.2.0                   py36_1    https://repo.continuum.io/pkgs/free
> simplegeneric             0.8.1                    py36_1    https://repo.continuum.io/pkgs/free
> singledispatch            3.4.0.3                  py36_0    https://repo.continuum.io/pkgs/free
> sip                       4.18                     py36_0    https://repo.continuum.io/pkgs/free
> six                       1.10.0                   py36_0    https://repo.continuum.io/pkgs/free
> snowballstemmer           1.2.1                    py36_0    https://repo.continuum.io/pkgs/free
> sortedcollections         0.5.3                    py36_0    https://repo.continuum.io/pkgs/free
> sortedcontainers          1.5.7                    py36_0    https://repo.continuum.io/pkgs/free
> sphinx                    1.5.6                    py36_0    https://repo.continuum.io/pkgs/free
> sphinxcontrib-websupport  1.2.1                     <pip>
> spyder                    3.1.4                    py36_0    https://repo.continuum.io/pkgs/free
> sqlalchemy                1.1.9                    py36_0    https://repo.continuum.io/pkgs/free
> statsmodels               0.8.0               np112py36_0    https://repo.continuum.io/pkgs/free
> sympy                     1.0                      py36_0    https://repo.continuum.io/pkgs/free
> tblib                     1.3.2                    py36_0    https://repo.continuum.io/pkgs/free
> testpath                  0.3                      py36_0    https://repo.continuum.io/pkgs/free
> tk                        8.5.18                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
> toolz                     0.8.2                    py36_0    https://repo.continuum.io/pkgs/free
> tornado                   4.5.1                    py36_0    https://repo.continuum.io/pkgs/free
> tqdm                      4.46.0                    <pip>
> traitlets                 4.3.2                    py36_0    https://repo.continuum.io/pkgs/free
> unicodecsv                0.14.1                   py36_0    https://repo.continuum.io/pkgs/free
> urllib3                   1.25.9                    <pip>
> vs2015_runtime            14.0.25123                    0    https://repo.continuum.io/pkgs/free
> wcwidth                   0.1.7                    py36_0    https://repo.continuum.io/pkgs/free
> werkzeug                  0.12.2                   py36_0    https://repo.continuum.io/pkgs/free
> wheel                     0.29.0                   py36_0    https://repo.continuum.io/pkgs/free
> widgetsnbextension        2.0.0                    py36_0    https://repo.continuum.io/pkgs/free
> win_unicode_console       0.5                      py36_0    https://repo.continuum.io/pkgs/free
> wrapt                     1.10.10                  py36_0    https://repo.continuum.io/pkgs/free
> xlrd                      1.0.0                    py36_0    https://repo.continuum.io/pkgs/free
> xlsxwriter                0.9.6                    py36_0    https://repo.continuum.io/pkgs/free
> xlwings                   0.10.4                   py36_0    https://repo.continuum.io/pkgs/free
> xlwt                      1.2.0                    py36_0    https://repo.continuum.io/pkgs/free
> zict                      0.1.2                    py36_0    https://repo.continuum.io/pkgs/free
> zlib                      1.2.8                    vc14_3  [vc14]  https://repo.continuum.io/pkgs/free

I wanted to update to the most recent spyder version and ran

`conda upgrade spyder`

and then figured it would also be good to update all packages using:

`conda update --all`

This left me with the packages shown below in section **Versions**.

My Spyder is now broken and crashes before starting due to a ModuleNotFoundError for prompt_toolkit.enums. I have tried to both up/downgrade prompt_toolkit and spyder but have not managed to make it work.

### What steps reproduce the problem?

From the anaconda prompt
1. conda update --all
2. spyder

### What is the expected output? What do you see instead?

Spyder should start but rather breaks.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\app\mainwindow.py", line 3748, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\app\mainwindow.py", line 3623, in run_spyder
    main.setup()
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\app\mainwindow.py", line 945, in setup
    from spyder.plugins.ipythonconsole.plugin import IPythonConsole
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 46, in <module>
    from spyder.plugins.ipythonconsole.widgets import (ClientWidget,
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\plugins\ipythonconsole\widgets\__init__.py", line 16, in <module>
    from .debugging import DebuggingWidget
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 15, in <module>
    from IPython.core.history import HistoryManager
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\IPython\__init__.py", line 56, in <module>
    from .terminal.embed import embed
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\IPython\terminal\embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "C:\Users\1520797\AppData\Local\conda\conda\envs\my_root\lib\site-packages\IPython\terminal\interactiveshell.py", line 19, in <module>
    from prompt_toolkit.enums import DEFAULT_BUFFER, EditingMode
ModuleNotFoundError: No module named 'prompt_toolkit.enums'

```

## Versions
_anaconda_depends         5.1.0                    py36_2    /
_license                  1.1                      py36_1    https://repo.continuum.io/pkgs/free
alabaster                 0.7.12                     py_0    /
anaconda                  custom                   py36_1    /
anaconda-client           1.7.2                    py36_0    /
anaconda-navigator        1.9.12                   py36_0    /
anaconda-project          0.8.4                      py_0    /
argh                      0.26.2                   py36_0    /
asn1crypto                1.3.0                    py36_0    /
astroid                   2.4.2                    py36_0    /
astropy                   4.0.1.post1      py36he774522_1    /
atomicwrites              1.4.0                      py_0    /
attrs                     19.3.0                     py_0    /
autopep8                  1.5.3                      py_0    /
babel                     2.8.0                      py_0    /
backcall                  0.2.0                      py_0    /
backports                 1.0                        py_2    /
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2    /
bcrypt                    3.1.7            py36he774522_1    /
beautifulsoup4            4.9.1                    py36_0    /
bitarray                  1.2.2            py36he774522_0    /
bkcharts                  0.2              py36h7e685f7_0    /
blas                      1.0                         mkl    /
blaze                     0.11.3           py36h8a29ca5_0    /
bleach                    3.1.5                      py_0    /
blosc                     1.19.0               h7bd577a_0    /
bokeh                     2.1.0                    py36_0    /
boto                      2.49.0                   py36_0    /
bottleneck                1.3.2            py36h2a96729_1    /
brotlipy                  0.7.0           py36he774522_1000    /
bzip2                     1.0.8                he774522_0    /
ca-certificates           2020.1.1                      0    /
cachecontrol              0.12.5                   py36_0    /
certifi                   2020.6.20                py36_0    /
cffi                      1.14.0           py36h7a1dbc1_0    /
chardet                   3.0.4                 py36_1003    /
click                     7.1.2                      py_0    /
cloudpickle               1.4.1                      py_0    /
clyent                    1.2.2            py36hb10d595_1    /
colorama                  0.4.3                      py_0    /
comtypes                  1.1.7                 py36_1001    /
console_shortcut          0.1.1                         4    /
contextlib2               0.6.0.post1                py_0    /
contextvars               2.4                        py_0    /
cryptography              2.9.2            py36h7a1dbc1_0    /
curl                      7.69.1               h2a8f88b_0    /
cycler                    0.10.0           py36h009560c_0    /
cython                    0.29.20          py36ha925a31_0    /
cytoolz                   0.10.1           py36he774522_0    /
dask                      2.19.0                     py_0    /
dask-core                 2.19.0                     py_0    /
datashape                 0.5.4                    py36_1    /
decorator                 4.4.2                      py_0    /
defusedxml                0.6.0                      py_0    /
diff-match-patch          20181111                   py_0    /
distlib                   0.2.9                    py36_0    /
distributed               2.19.0                   py36_0    /
docutils                  0.16                     py36_1    /
entrypoints               0.3                      py36_0    /
et_xmlfile                1.0.1            py36h3d2d736_0    /
fastcache                 1.1.0            py36he774522_0    /
filelock                  3.0.12                     py_0    /
flake8                    3.8.3                      py_0    /
flask                     1.1.2                      py_0    /
flask-cors                3.0.8                      py_0    /
freetype                  2.10.2               hd328e21_0    /
fsspec                    0.7.4                      py_0    /
future                    0.18.2                   py36_1    /
get_terminal_size         1.0.0                h38e98db_0    /
gevent                    1.4.0            py36he774522_0    /
glob2                     0.7                        py_0    /
greenlet                  0.4.16           py36he774522_0    /
h5py                      2.10.0           py36h5e291fa_0    /
hdf5                      1.10.4               h7ebc959_0    /
heapdict                  1.0.1                      py_0    /
html5lib                  1.0.1                      py_0    /
icc_rt                    2019.0.0             h0cc432a_1    /
icu                       58.2             vc14hc45fdbb_0  [vc14]  /
idna                      2.9                        py_1    /
imageio                   2.8.0                      py_0    /
imagesize                 1.2.0                      py_0    /
immutables                0.14             py36he774522_0    /
importlib-metadata        1.6.1                    py36_0    /
importlib_metadata        1.6.1                         0    /
intel-openmp              2020.1                      216    /
intervaltree              3.0.2                      py_0    /
ipykernel                 5.3.0            py36h5ca1d4c_0    /
ipython                   7.15.0                   py36_0    /
ipython_genutils          0.2.0            py36h3c5d0ee_0    /
ipywidgets                7.5.1                      py_0    /
isort                     4.3.21                   py36_0    /
itsdangerous              1.1.0                      py_0    /
jdcal                     1.4.1                      py_0    /
jedi                      0.15.2                   py36_0    /
jinja2                    2.11.2                     py_0    /
joblib                    0.15.1                     py_0    /
jpeg                      9b               vc14h4d7706e_1  [vc14]  /
json5                     0.9.5                      py_0    /
jsonschema                3.2.0                    py36_0    /
jupyter                   1.0.0                    py36_7    /
jupyter_client            6.1.3                      py_0    /
jupyter_console           6.1.0                      py_0    /
jupyter_core              4.6.3                    py36_0    /
jupyterlab                2.1.4                      py_1    /
jupyterlab_launcher       0.13.1                   py36_0    /
jupyterlab_server         1.1.5                      py_0    /
keyring                   21.1.1                   py36_2    /
kiwisolver                1.2.0            py36h74a9793_0    /
krb5                      1.17.1               hc04afaa_0    /
lazy-object-proxy         1.4.3            py36he774522_0    /
libcurl                   7.69.1               h2a8f88b_0    /
libiconv                  1.15             vc14h29686d3_5  [vc14]  /
libpng                    1.6.37               h2a8f88b_0    /
libsodium                 1.0.16               h9d3ae62_0    /
libspatialindex           1.9.3                h33f27b4_0    /
libssh2                   1.9.0                h7a1dbc1_1    /
libtiff                   4.1.0                h56a325e_1    /
libxml2                   2.9.10               h464c3ec_1    /
libxslt                   1.1.34               he774522_0    /
llvmlite                  0.32.1           py36ha925a31_0    /
locket                    0.2.0            py36hfed976d_1    /
lockfile                  0.12.2           py36h0468280_0    /
lxml                      4.5.1            py36h1350720_0    /
lz4-c                     1.9.2                h62dcd97_0    /
lzo                       2.10             vc14h0a64fa6_1  [vc14]  /
markupsafe                1.1.1            py36he774522_0    /
matplotlib                3.2.2                         0    /
matplotlib-base           3.2.2            py36h64f37c6_0    /
mccabe                    0.6.1            py36hb41005a_1    /
menuinst                  1.4.16           py36he774522_1    /
mistune                   0.8.4            py36he774522_0    /
mkl                       2019.4                      245    /
mkl-service               2.3.0            py36hb782905_0    /
mkl_fft                   1.1.0            py36h45dec08_0    /
mkl_random                1.1.0            py36h675688f_0    /
mock                      4.0.2                      py_0    /
more-itertools            8.4.0                      py_0    /
mpmath                    1.1.0                    py36_0    /
msgpack-python            1.0.0            py36h74a9793_1    /
multipledispatch          0.6.0                    py36_0    /
navigator-updater         0.2.1                    py36_0    /
nbconvert                 5.6.1                    py36_0    /
nbformat                  5.0.7                      py_0    /
networkx                  2.4                        py_0    /
nltk                      3.5                        py_0    /
nose                      1.3.7            py36h1c3779e_2    /
notebook                  6.0.3                    py36_0    /
numba                     0.49.1           py36h47e9c7a_0    /
numexpr                   2.7.1            py36h25d0782_0    /
numpy                     1.18.5           py36h6530119_0    /
numpy-base                1.18.5           py36hc3f5095_0    /
numpydoc                  1.0.0                      py_0    /
odo                       0.5.1            py36h7560279_0    /
olefile                   0.46                       py_0    /
openpyxl                  3.0.3                      py_0    /
openssl                   1.1.1g               he774522_0    /
packaging                 20.4                       py_0    /
pandas                    1.0.5            py36h47e9c7a_0    /
pandoc                    2.2.3.2                       0    /
pandocfilters             1.4.2            py36h3ef6317_1    /
paramiko                  2.7.1                      py_0    /
parso                     0.5.2                      py_0    /
partd                     1.1.0                      py_0    /
path                      14.0.1                   py36_0    /
path.py                   12.0.2                     py_0    /
pathlib2                  2.3.5                    py36_0    /
pathtools                 0.1.2                      py_1    /
patsy                     0.5.1                    py36_0    /
pep8                      1.7.1                    py36_0    /
pexpect                   4.8.0                    py36_0    /
pickleshare               0.7.5                    py36_0    /
pillow                    7.1.2            py36hcc1f983_0    /
pip                       20.1.1                   py36_1    /
pkginfo                   1.5.0.1                  py36_0    /
pluggy                    0.13.1                   py36_0    /
ply                       3.11                     py36_0    /
progress                  1.5                      py36_0    /
prometheus_client         0.8.0                      py_0    /
prompt-toolkit            3.0.5                      py_0    /
prompt_toolkit            3.0.5                         0    /
psutil                    5.7.0            py36he774522_0    /
py                        1.8.2                      py_0    /
pyasn1                    0.4.8                      py_0    /
pycodestyle               2.6.0                      py_0    /
pycosat                   0.6.3            py36hfa6e2cd_0    /
pycparser                 2.20                       py_0    /
pycrypto                  2.6.1           py36he774522_10    /
pycurl                    7.43.0.5         py36h7a1dbc1_0    /
pydocstyle                5.0.2                      py_0    /
pyflakes                  2.2.0                      py_0    /
pygments                  2.6.1                      py_0    /
pylint                    2.5.3                    py36_0    /
pympler                   0.7                        py_0    /
pynacl                    1.3.0            py36h62dcd97_0    /
pynput                    1.6.8                     <pip>
pyodbc                    4.0.30           py36ha925a31_0    /
pyopenssl                 19.1.0                   py36_0    /
pyparsing                 2.4.7                      py_0    /
pyqt                      5.9.2            py36ha878b3d_0    /
pyreadline                2.1              py36h094d952_1    /
pyrsistent                0.16.0           py36he774522_0    /
pysocks                   1.7.1                    py36_0    /
pytables                  3.6.1            py36h1da0976_0    /
pytest                    5.4.3                    py36_0    /
python                    3.6.10               h9f7ef89_2    /
python-dateutil           2.8.1                      py_0    /
python-jsonrpc-server     0.3.4                      py_0    /
python-language-server    0.31.9                   py36_0    /
pytz                      2020.1                     py_0    /
pywavelets                1.1.1            py36he774522_0    /
pywin32                   227              py36he774522_1    /
pywin32-ctypes            0.2.0                 py36_1000    /
pywinpty                  0.5              py36h6538335_2    /
pyyaml                    5.3.1            py36he774522_0    /
pyzmq                     18.1.1           py36ha925a31_0    /
qdarkstyle                2.8.1                      py_0    /
qt                        5.9.7            vc14h73c81de_0  [vc14]  /
qtawesome                 0.7.2                      py_0    /
qtconsole                 4.7.5                      py_0    /
qtpy                      1.9.0                      py_0    /
regex                     2020.5.14        py36he774522_0    /
requests                  2.24.0                     py_0    /
rope                      0.17.0                     py_0    /
rtree                     0.9.4            py36h21ff451_1    /
ruamel_yaml               0.15.87          py36he774522_0    /
scikit-image              0.16.2           py36h47e9c7a_0    /
scikit-learn              0.22.1           py36h6288b17_0    /
scipy                     1.4.1            py36h9439919_0    /
seaborn                   0.10.1                     py_0    /
selenium                  3.141.0                   <pip>
send2trash                1.5.0                    py36_0    /
setuptools                47.3.1                   py36_0    /
simplegeneric             0.8.1                    py36_2    /
singledispatch            3.4.0.3          py36h17d0c80_0    /
sip                       4.19.22          py36ha925a31_0    /
six                       1.15.0                     py_0    /
snappy                    1.1.7            vc14h2dea872_1  [vc14]  /
snowballstemmer           2.0.0                      py_0    /
sortedcollections         1.2.1                      py_0    /
sortedcontainers          2.2.2                      py_0    /
soupsieve                 2.0.1                      py_0    /
sphinx                    3.1.1                      py_0    /
sphinxcontrib             1.0              py36hbbac3d2_1    /
sphinxcontrib-applehelp   1.0.2                      py_0    /
sphinxcontrib-devhelp     1.0.2                      py_0    /
sphinxcontrib-htmlhelp    1.0.3                      py_0    /
sphinxcontrib-jsmath      1.0.1                      py_0    /
sphinxcontrib-qthelp      1.0.3                      py_0    /
sphinxcontrib-serializinghtml 1.1.4                      py_0    /
sphinxcontrib-websupport  1.2.2                      py_0    /
sphinxcontrib-websupport  1.2.1                     <pip>
spyder                    4.1.3                    py36_0    /
spyder-kernels            1.9.1                    py36_0    /
sqlalchemy                1.3.17           py36he774522_0    /
sqlite                    3.32.3               h2a8f88b_0    /
statsmodels               0.11.1           py36he774522_0    /
sympy                     1.6                      py36_0    /
tbb                       2020.0               h74a9793_0    /
tblib                     1.6.0                      py_0    /
terminado                 0.8.3                    py36_0    /
testpath                  0.4.4                      py_0    /
tk                        8.6.10               he774522_0    /
toml                      0.10.0             pyh91ea838_0    /
toolz                     0.10.0                     py_0    /
tornado                   6.0.4            py36he774522_1    /
tqdm                      4.46.1                     py_0    /
tqdm                      4.46.0                    <pip>
traitlets                 4.3.3                    py36_0    /
typed-ast                 1.4.1            py36he774522_0    /
typing                    3.7.4.1                  py36_0    /
typing_extensions         3.7.4.2                    py_0    /
ujson                     1.35             py36hfa6e2cd_0    /
unicodecsv                0.14.1           py36h6450c06_0    /
urllib3                   1.25.9                     py_0    /
vc                        14.1                 h21ff451_4    /
vs2015_runtime            14.16.27012          hf0eaf9b_2    /
watchdog                  0.10.2                   py36_0    /
wcwidth                   0.2.4                      py_0    /
webencodings              0.5.1            py36h67c50ae_1    /
werkzeug                  1.0.1                      py_0    /
wheel                     0.34.2                   py36_0    /
widgetsnbextension        3.5.1                    py36_0    /
win_inet_pton             1.1.0                    py36_0    /
win_unicode_console       0.5              py36hcdbd4b5_0    /
wincertstore              0.2              py36h7fe50ca_0    /
winpty                    0.4.3                hfa6e2cd_4    /
wrapt                     1.11.2           py36he774522_0    /
xlrd                      1.2.0                      py_0    /
xlsxwriter                1.2.9                      py_0    /
xlwings                   0.19.4                   py36_0    /
xlwt                      1.3.0            py36h1a4751e_0    /
xmltodict                 0.12.0                     py_0    /
xz                        5.2.5                h62dcd97_0    /
yaml                      0.1.7            vc14hb31d195_1  [vc14]  /
yapf                      0.29.0                     py_0    /
zeromq                    4.3.1                h33f27b4_3    /
zict                      2.0.0                      py_0    /
zipp                      3.1.0                      py_0    /
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  /
zstd                      1.4.4                ha9fde0e_3    /

**Comment by dalthviz** [comment]
Hi @DiegoF90 sorry to hear that seems like the env you are working on got corrupted then (`conda update --all` can be a tricky command to run as you are experiencing). Please try to check our [Troubleshooting Guide and FAQ](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) to see if that helps you. Also, checking the list of dependencies that you provided, seems like in your env you have two installations of `prompt_toolkit` maybe you could check if that is the case an remove one.  

I'm closing this one since there is not much we can do to help here, but let us know if you manage to fix your env :)
