### ISSUE TITLE
Add Tutorial Videos item to Spyder Help menu

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#13239]
## Problem Description

Now that we have our tutorial video series, we should consider adding a link to the playlist as an item in the Help menu, like we have the Spyder website, docs, Troubleshooting Guide, Google Group, and various other doc sites. Maybe not right away, but hopefully for 4.2 when they are more complete.

**Comment by ccordoba12** [comment]
This is a good point, but perhaps it'd be even better to embed our docs inside the Help pane. And that's what we're planning to do for Spyder 5.

@juanis2112, what do you think about this one?

**Comment by CAM-Gerlach** [comment]
> This is a good point, but perhaps it'd be even better to embed our docs inside the Help pane. And that's what we're planning to do for Spyder 5.

It would certainly be, without a doubt, and we could actually play the videos within the help pane assuming QWebEngine supports Youtube. However, I don't think we should wait until whenever that happens to expose one of the most useful help resources that we offer, at least in some form, considering that embedding the docs may involve several orders of magnitude more time, complexity and risk than spending a few minutes adding a simple menu item (which I can do for 4.2 or whatever the next version is, if we all agree). After all, the videos are for Spyder 4, not Spyder 5, so we may as well share them with our users now so the community gets the most benefit out of @juanis2112 's hard work.

**Comment by juanis2112** [comment]
Agreed.
