### ISSUE TITLE
Spyder should complain if the wrong version of spyder-kernel is used

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#13232]
If the wrong version of spyder-kernel is used, the integration will fail in random ways. We should check the version of spyder kernel and if it not correct, display a big warning and either:
 - Refuse to work with it
 - Treat it like an external kernel with all comms disabled.

**Comment by dalthviz** [comment]
Could this be closed or something different than the current message needs to be added @impact27 ?:

![imagen](https://user-images.githubusercontent.com/16781833/141351151-996ab10d-494a-4801-97af-4b39b7af9c39.png)
