### ISSUE TITLE
Python is not responding..IDE HANGS 

### ISSUE THREAD

**Issue by tylerdurden1313** [spyder-ide/spyder#13237]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
As i imported Pygame in my spyder and when i run it the pygame window shows "python is not responding".

**Comment by dalthviz** [comment]
Hi @tylerdurden1313 , sorry for the late response, maybe this is related with the selected graphics backend being use for the IPython console. I will close this one in favor of https://github.com/spyder-ide/spyder/issues/4471 but if you have more info about this issue let us know
