### ISSUE TITLE
Problem with debug mode

### ISSUE THREAD

**Issue by toufraita** [spyder-ide/spyder#13246]
Hello. 

I looked in other issues but could find the answer to this problem. I hop I'm giving enough information...

## Problem Description

The debug mode is not working properly : the debug buttons in the toolbars do not work, as well as the keyboard short cuts. Breakpoints are not recognized, such that the debug run is stuck on first line. In the ipython console, commands run properly (for instance, 'n' to go next line), but as breakpoints are not working, 'continue' simply execute the programm.

### What steps reproduce the problem?

I came upon this problem after updating conda : 

` conda update --all `

I did a full re-installation of conda (Anaconda3-2020.02-Linux-x86_64.sh), with the default packages, which solved the problem. But then the spyder version is 

```
spyder                    4.0.1                    py37_0  
spyder-kernels            1.8.1                    py37_0 
```

But if I create a new clean environment with `conda create -n tmp spyder=4.1.3 `, then the problem is happening again.

## Versions

For the working environement :

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04.4 LTS bionic

For the not working environement :

* Spyder version: 4.1.3
* Python version: 3.6.10
* Qt version: 5.12.3
* PyQt version: 5.12.5
* Operating System name/version: Ubuntu 18.04.4 LTS bionic

### Dependencies
 
For the working environment

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.26 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

For the non working envionement

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  1.8.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Are you using conda-forge to install our 4.1.3 version?

**Comment by toufraita** [comment]
Yas I am.

Just to make sure, I tried again `conda create -n tmp -c conda-forge spyder=4.1.3`, and the result is the same.

**Comment by toufraita** [comment]
For some reason, the problem seems to be solved, though I'm not sure what I did... When I run again conda create `-n tmp spyder 4.1.3`, the resulting environnement works fine, with the same configuartion as the environement that did not work previously, aprat from :

- Qt version: 5.12.5
-PyQt version: 5.12.3

but I may have  inverted the verion numbers in my first post. I played a little bit around with conda channels (removing and adding again conda-forge), but I don't see how it could be relevant...

**Comment by ccordoba12** [comment]
Mixing channels is not a good idea in general. And I'm glad you solved the issue.

If you find a clear way to reproduce it, please let us know about it.
