### ISSUE TITLE
Spyder doesn't recognise my Windows10 language correctly and installs with Spanish lang.

### ISSUE THREAD

**Issue by razorree** [spyder-ide/spyder#13245]
Spyder doesn't recognise my Windows10 language correctly and installs with Spanish lang.

My notebook is from Spanish distribution, however during Windows configuration i chose english language,
and my region is set to 'UK'.

Why Spyder installed Spanish language by default?  which Windows setting is responsible for that ?

**Comment by dalthviz** [comment]
Hi @razorree, sorry for the late response. The way Spyder detects the machine language is by running `locale.getdefaultlocale()[0]`:

https://github.com/spyder-ide/spyder/blob/99ec511f05ee7eeb9dd28892b9a72c40f00e4bf9/spyder/config/base.py#L407-L444

For more info regarding that you can check: https://docs.python.org/es/3.9/library/locale.html#locale.getdefaultlocale

I'm closing this one but if you have any other question let us know

**Comment by dalthviz** [comment]
Also, just in case, you can change the language at: `Tools > Preferences > Application > Advanced settings > Language` in the latest Spyder version
