### ISSUE TITLE
AssertionError: Some tests have failed.

### ISSUE THREAD

**Issue by Zay-Nab** [spyder-ide/spyder#13255]
### Issue Report Checklist

* [ *] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ *] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ *] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ *] Tried basic troubleshooting (if a bug/error)
    * [ *] Restarted Spyder
    * [ *] Reset preferences with ``spyder --reset``
    * [* ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ *] Tried the other applicable steps from the Troubleshooting Guide
* [ *] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

new to paython..i use anaconda ..installed package called verde..when i run the command verde.test() ..i get error massage says: 
ERROR: usage:  [options] [file_or_dir] [file_or_dir] [...]
: error: unrecognized arguments: --mpl
  inifile: None
  rootdir: C:\Users\ZayNab\.spyder-py3
AssertionError: Some tests have failed.

### What steps reproduce the problem?

1. import verde
2. verde.test()
3. run the program

### What is the expected output? What do you see instead?

new to paython and have no expectation..yet exploring

### Paste Traceback/Error Below (if applicable)

```python-traceback
  File "<ipython-input-3-aafae1b23fe8>", line 1, in <module>
    verde.test()

  File "C:\Users\ZayNab\anaconda3\lib\site-packages\verde\__init__.py", line 81, in test
    assert status == 0, "Some tests have failed."

```

## Versions
* Spyder version: 4.1.3
* Python version: 3.7
* Qt version: 5.9.7
* PyQt version: 
* Operating System name/version: windows 8.1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment]
This seems to be a problem with the code you're trying to run in Spyder rather than with the code itself. Is `verde` a package we can install with conda or pip so we can give you a hand with it?

**Comment by Zay-Nab** [comment]
I installed verde using anaconda prompt..is that differ than installing by conda?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ccordoba12** [comment]
Sorry but this a problem with the `verde` package (not with Spyder) and we don't have time to help you with it.
