### ISSUE TITLE
I cannot install Spyder 4.1.4

### ISSUE THREAD

**Issue by rlloretb** [spyder-ide/spyder#13267]
(default) localhost:~ user$ conda install spyder=4.1.4
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=4.1.4

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ccordoba12** [comment]
@rlloretb, Anaconda takes a few days (usually not more than a week) to upload packages for a new Spyder version. Please be patient.
