### ISSUE TITLE
spyder cannot start properly

### ISSUE THREAD

**Issue by soocrash** [spyder-ide/spyder#13266]
### What steps will reproduce the problem?

- create a new conda env and install chatterbot=0.8.7 using pip 
- launch spyder
- spyder cannot start properly and the console gets stuck 'connecting to kernel'

### Traceback
```python-traceback
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
AttributeError: module 'dateutil.tz' has no attribute 'UTC'
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.6.1 (OK)
sphinx >=0.6.6    :  3.0.3 (OK)
rope >=0.9.4      :  0.16.0 (OK)
jedi >=0.9.0      :  0.14.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  1.0.3 (OK)
numpy >=1.7       :  1.18.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.7.3 (OK)
IPython >=4.0     :  7.13.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.5.0 (OK)
```

**Comment by ccordoba12** [comment]
> install chatterbot=0.8.7 using pip

This is probably interfering with Spyder and making it crash. Please [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn to how get Spyder back to life.
