### ISSUE TITLE
the error came when i run the file in spyder 

### ISSUE THREAD

**Issue by asmajaved** [spyder-ide/spyder#13261]
TThis is the error come on the spyder Console:

 Python 3.7.6 (default, Jan  8 2020, 16:21:45) [MSC v.1916 32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.

IPython 7.12.0 -- An enhanced Interactive Python.

runfile('C:/Users/ashar/Downloads/intr 2 AI with Python/lecture 1/projects/minesweeper/minesweeper/minesweeper.py', wdir='C:/Users/ashar/Downloads/intr 2 AI with Python/lecture 1/projects/minesweeper/minesweeper')

The code is 
import itertools
import random

class Minesweeper():
    """
    Minesweeper game representation
    """

    def __init__(self, height=8, width=8, mines=8):

        # Set initial width, height, and number of mines
        self.height = height
        self.width = width
        self.mines = set()

        # Initialize an empty field with no mines
        self.board = []
        for i in range(self.height):
            row = []
            for j in range(self.width):
                row.append(False)
            self.board.append(row)

        # Add mines randomly
        while len(self.mines) != mines:
            i = random.randrange(height)
            j = random.randrange(width)
            if not self.board[i][j]:
                self.mines.add((i, j))
                self.board[i][j] = True

        # At first, player has found no mines
        self.mines_found = set()

    def print(self):
        """
        Prints a text-based representation
        of where mines are located.
        """
        for i in range(self.height):

**Comment by goanpeca** [comment]
Hello @asmajaved, thanks for the report. Could you please fill in the complete template that was there when you first opened the issue?

Without that information, we will not be able to provide more feedback.

Cheers!

**Comment by goanpeca** [comment]
Closing due to lack of response.
