### ISSUE TITLE
Spyder cannot launch: Access denied

### ISSUE THREAD

**Issue by ashura1** [spyder-ide/spyder#13270]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Not able to launch Spyder4 in Windows10. 
Error: Access denied
Python is working well. I ran upgrade on Spyder and it also fine.

### What steps reproduce the problem?

1. Run Spyder4.exe from the folder
2. 
3. 

### What is the expected output? What do you see instead?
I see access denied message. Spyder has been running properly since installed and no changes to my Windows 10 until recently.

### Paste Traceback/Error Below (if applicable)

```python-traceback

No Traceback. Only Access denied.
PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.8
* Qt version: QtPy 1.9.0
* PyQt version: PyQt 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @ashura1, thanks for the report. How did you install Spyder?

**Comment by ashura1** [comment]
Hi,I used Pip and there are no failed messages. I had been using it for quite sometimes but it suddenly stopped working with access denied message. This is what annoyed me. I still can launch Python directly with no issue so I can say Python and folders access are fine. I have local admin rights on my laptop too.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Gonzalo Peña-Castellanos <notifications@github.com> Date: 14/7/20  23:10  (GMT+10:00) To: spyder-ide/spyder <spyder@noreply.github.com> Cc: ashura1 <johnnylau133@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [spyder-ide/spyder] Spyder cannot launch: Access denied (#13270) 
Hi @ashura1, thanks for the report. How did you install Spyder?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/spyder-ide/spyder/issues/13270#issuecomment-658169639",
"url": "https://github.com/spyder-ide/spyder/issues/13270#issuecomment-658169639",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by goanpeca** [comment]
@ashura1 did you install with admin priviledges?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
