### ISSUE TITLE
When I use a non-default python interpreter in spyder, the debug button in spyder does not respond.

### ISSUE THREAD

**Issue by coder-wangzhen** [spyder-ide/spyder#13272]
### Issue Report Checklist

* [ *] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [* ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [ *] Reset preferences with ``spyder --reset``
    * [* ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [* ] Tried the other applicable steps from the Troubleshooting Guide
* [* ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I use a non-default python interpreter in spyder. 
![image](https://user-images.githubusercontent.com/38872958/87263395-9e487d00-c4ef-11ea-90ae-7d86cf9e49ff.png)
I can execute the python program normally. But when I try to debug the code, spyder's debug buttons are not responding except the "Debug file" button (I have set breakpoints). 
![image](https://user-images.githubusercontent.com/38872958/87263415-b02a2000-c4ef-11ea-977d-0f164abc5056.png)
 And the IPython console has always been like this: IPython console
![image](https://user-images.githubusercontent.com/38872958/87263426-b7e9c480-c4ef-11ea-88a1-d666c867b74e.png)

Can someone tell me what is the problem? Thank you!

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:4.1.3
* Python version: 3.7.7
* Spyder kernels:1.9.1 
* Qt version: 
* PyQt version: 
* Operating System name/version: windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by goanpeca** [comment]
Hi @coder-wangzhen, thanks for the report.

@impact27 are you able to reproduce this?

**Comment by impact27** [comment]
I can't reproduce this. It should be noted that nothing will be printed to the console if you use the buttons, so maybe you mistook that for the buttons not working?

**Comment by coder-wangzhen** [comment]
@impact27 Thank you for your reply. Did you click the “Restart Kernel” in the IPython window after changing the python interpreter？
![image](https://user-images.githubusercontent.com/38872958/87516080-625c1600-c6af-11ea-99a1-321b0bdf74f9.png)
If you did not restart the kernel, you still execute the program in the default python interpreter.

**Comment by coder-wangzhen** [comment]
@goanpeca @impact27 are you able to reproduce this after clicking the “Restart Kernel” in the IPython window ?

**Comment by ccordoba12** [comment]
@coder-wangzhen, please update to 4.1.4 and try again. I think your problem is fixed in that version (after a kernel restart).

**Comment by coder-wangzhen** [comment]
@ccordoba12 yes, it works after I update spyder to 4.1.4 and update spyder-kernels in another virtual environment to 1.9.2. Thank you for your help ! @ccordoba12 @goanpeca @impact27

**Comment by ccordoba12** [comment]
No problem. Glad to know this bug is already fixed.
