### ISSUE TITLE
Keyboard shortcut Shift + Enter ignored when reassigned

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#13277]
**Steps to reproduce:**
* Go to `Tools` -> `Preferences` -> `Keyboard shortcuts`.
* Assign `Shift` + `Enter` (default: `Run cell and advance`) to `Run selection` (default: F9).
* When it prompts you about re-assigning this key combination from its current action, select Ok.
* Write some code in the editor.
* Select said code and press `Shift` + `Enter`.

**Expected behavior:** should execute selected code as was configured in the shortcuts.

**Actual behavior:** does not execute the selected code, despite the configured shortcut.

The `Shift` + `Enter` key combination works fine when it is assigned to its default `Run cell and advance`.

**Setup:** spyder 4.1.3, running on debian linux (KDE).

**Comment by goanpeca** [comment]
Hi @david-cortes, thanks for the report. Question, on restart the problem persists? 

Thanks

**Comment by david-cortes** [comment]
Not sure if it works after just a spyder restart, but tested it again today on 2 computers (which have undergone some full restarts since changing the configuration) and it worked.

**Comment by goanpeca** [comment]
Ok @david-cortes will close for now. Let me know if you see it again, or if you spot what might be causing it. Cheers!
