### ISSUE TITLE
kernel died restarting

### ISSUE THREAD

**Issue by Nikita11042001** [spyder-ide/spyder#13287]
### What steps will reproduce the problem?

i did a program on socket and then this happened.i am not able to work in spyder

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by steff456** [comment]
Hi @Nikita11042001,

What is the error you are encountering in spyder?

**Comment by Nikita11042001** [comment]
I remember, sometime before I did a program using import socket then after
that I am not able to use spyder .Also I reinstalled it but still I am not
able to use kernel..it is showing kernel died restarting

**Comment by steff456** [comment]
Have you tried updating to the latest version of Spyder?

**Comment by Nikita11042001** [comment]
Is this the problem?

**Comment by steff456** [comment]
Please upload the code you generated to see if we can understand your problem.

**Comment by Nikita11042001** [comment]
Thank you for your cooperation my problem is solved .
