### ISSUE TITLE
Can't terminate debugging session

### ISSUE THREAD

**Issue by Maques64** [spyder-ide/spyder#13283]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Can't stop script execution when debugging.

### What steps reproduce the problem?

1. Debug any Python script with CTRL+F5
2. Continue execution with CTRL+F12
3. 

### What is the expected output? What do you see instead?

Debugging can't be terminated with CTRL+SHFT+F12 or the 'stop debugging' button.  Also the stop button in the console pane is greyed out.  Spyder has to be terminated to stop the script from running.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @Maques64,

Can you please upload a gif where we can see the behavior and the file which is causing you this problem?

**Comment by Maques64** [comment]
![issue](https://user-images.githubusercontent.com/68271700/87512798-8f88d400-c66f-11ea-98f8-a8fd82767165.jpg)

Attached an image of the problem, with a very simple Python script.

Script debugging was started with CTRL+F5 then CTRL+F12.  At that point debugging couldn't be stopped (CTRL+SHFT+F12 did nothing, and the stop button in the top right of the console pane is greyed-out).

One workaround I've found is restarting the kernel in the console window will stop execution.

**Comment by steff456** [comment]
Hi @Maques64,

Please remember that for using the debugger you need to create a breakpoint in the pane next to the number of rows. In that way, the debugger will stop your program in that line. Additionally, please remember that the stop button in the IPythonConsole pane is for stopping execution in the kernel, so it will be activated when you are in the middle of the execution of some code.

![image](https://user-images.githubusercontent.com/20992645/87571857-4301c080-c690-11ea-8f79-d53760af06e5.png)

**Comment by steff456** [comment]
> Ok, so debugging can only be stopped (CTRL+SHFT+F12) if the debugger is stopped on a breakpoint?
Yes

> That works for me, but seems counter intuitive that I wouldn't be able to stop execution unless stopped on a breakpoint.

You have a point, we are going to review if we can do something to enhance this behavior.
Also, now can reproduce the error if I don't put any breakpoint, run the code and then give continue to the debugger. For now, you can stop the execution by hitting `Ctrl+C` in the console.

**Comment by steff456** [comment]
@ccordoba12 can you please take a look at this one?
