### ISSUE TITLE
Add dependency injection to register method and change plugin NAME to ID

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#13285]
- `NAME` is a bit misleading, it is actually and `ID` so it is better to use `ID` as it conveys the right usage. 

Currently, plugins need to "manually" call a plugin before its usage on the register method. This can get annoying after a while  and we already have this information from REQUIRES and OPTIONAL, so we can just use inject them

so something like:

```python

class SomePlugin(SpyderDockablePlugin)
    ID = 'some-unique-id'
    REQUIRES = ["some-plugin-id"]
    OPTIONAL = ["some-other-plugin-id"]

    def register(self, some_plugin_id, some_other_plugin_id=None):
        pass
```

This way the plugins are ready to be used.

The `get_plugin` will still be available if a plugin needs to be used on an API method of the `SomePlugin`.

**Comment by ccordoba12** [comment]
This probably no longer applies now that we have a plugin registry.
