### ISSUE TITLE
Spyder (copy and rename jpg file)

### ISSUE THREAD

**Issue by minatt-y** [spyder-ide/spyder#13296]
I'm new in Python, and what I'm trying to do is to copy a jpg file on the Desktop of my MacBook and rename it. I followed every step expect in the directory because I'm using my MacBook to program and the explaining was in windows. 
I think there's something wrong with my directory address but I don't know how to fix it.
Here's the code I'm trying to run. 
<img width="1440" alt="Screen Shot 2020-07-15 at 10 28 16 AM" src="https://user-images.githubusercontent.com/67622560/87496360-f74a1980-c685-11ea-8957-82e46c5cd9b5.png">
Thanks :)

**Comment by steff456** [comment]
Hi @minatt-y,

This isn't a spyder error and we are closing this issue, but I'm happy to help you fix your error. The first lines of your code you are including a python instruction in the string, it will be fixed if you wrote it the following way,
```
import os
src = os.path.expanduser("~/Desktop/wallpaper.jpg")
dst = os.path.expanduser("~/Desktop/wallpaper1.jpg")
...
```
Please note that there's a lot of cool python libraries that can help you read/write/process images in a readable format. 
Hope this helps, and thanks for reporting!
