### ISSUE TITLE
Error while running Spyder shell. Where could I find caffe2_nvrtc.dll  file.

### ISSUE THREAD

**Issue by shkm34** [spyder-ide/spyder#13322]
FileNotFoundError: Could not find module 'C:\Users\shkm1\anaconda3\envs\virtual_platform\lib\site-packages\torch\lib\caffe2_nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by juanis2112** [comment]
Hi @shkm34, I think this issue is not related to Spyder. However, I suggest uninstalling and installing PyTorch again with conda which might help you solve this issue.

**Comment by juanis2112** [comment]
You can fin instructions of how to do this here:

https://pytorch.org/get-started/locally/

**Comment by juanis2112** [comment]
Closing due to no response
