### ISSUE TITLE
SAVE automatically creates a tmp file

### ISSUE THREAD

**Issue by YwEwanHuang** [spyder-ide/spyder#13337]
I just updated Spyder to version 4.1.4. 

I found that every time I modify and save a .py file, there would be a file with prefix **tmp** generated automatically in the same directory, e.g., **tmp_1wsn3oj** and **tmpg_3kfhp4**. The **tmp** file contains the same source code as the original .py file.

I am just wondering if there is an option to prevent this as when I noticed this issue, I already got more than 500 tmp files in the folder.

**Comment by goanpeca** [comment]
Hi @YwEwanHuang thanks for the report.

@jitseniesen is this related to the autosave?

**Comment by jitseniesen** [comment]
I think this is related to atomic writes, it looks like issue #13041. @YwEwanHuang are you perhaps using Dropbox or a similar program?

**Comment by YwEwanHuang** [comment]
Hi @jitseniesen, yep, I am using Dropbox. I've read the issue #13041 and I don't see any **tmp** files if I work outside Dropbox.

Thanks for the heads up!

**Comment by ccordoba12** [comment]
@YwEwanHuang, we'll solve this issue in our next version. For now the only workaround is to save your files out of Dropbox.

We're very sorry for the inconvenience.
