### ISSUE TITLE
I need help on this please

### ISSUE THREAD

**Issue by donet3088** [spyder-ide/spyder#13332]
Traceback (most recent call last):
  File "/Users/user/opt/anaconda3/envs/mytfenv/bin/spyder", line 7, in <module>
    from spyder.app.start import main
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages/spyder/app/start.py", line 35, in <module>
    from spyder.config.manager import CONF
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages/spyder/config/manager.py", line 351, in <module>
    CONF = ConfigurationManager()
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages/spyder/config/manager.py", line 72, in __init__
    remove_obsolete=False,
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages/spyder/config/user.py", line 782, in __init__
    self._configs_map[name] = config_class(**new_kwargs)
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages/spyder/config/user.py", line 212, in __init__
    self._load_from_ini(previous_fpath)
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/site-packages/spyder/config/user.py", line 333, in _load_from_ini
    self.read(fpath, encoding='utf-8')
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/Users/user/opt/anaconda3/envs/mytfenv/lib/python3.7/configparser.py", line 1110, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/Users/user/.spyder-py3/config/transient.ini'
	[line 99]: "y']\n"

**Comment by texadactyl** [comment]
What version of Spyder?  If it is less than 4.1.14 (latest), you might try an update.  You could also try using ```conda``` to update its dependencies.

**Comment by donet3088** [comment]
I’m running the latest version of spyder, that is 4.1.4

**Comment by texadactyl** [comment]
Did you try ```conda update --all``` but still get the same results afterwards?

**Comment by donet3088** [comment]
Yes please I did but to no avail. Pycharm and jupyter notebook works but spyder doesn’t

**Comment by texadactyl** [comment]
You didn't say what OS you are using.  If it is Linux or Unix, I would try renaming ```/Users/user/.spyder-py3``` to something else like ```/Users/user/HOLD.spyder-py3```.  See if it helps for spyder to recreate the config.  I suggest this because it looks like the existing ```transient.ini``` has been mangled.

Alternatively, you could share the contents of ```/Users/user/.spyder-py3/config/transient.ini```

**Comment by donet3088** [comment]
I’m using Unix but I’m finding it difficult to locate the file .spyder

**Comment by texadactyl** [comment]
My Xubuntu Linux system stores that file in ```$HOME/.config/spyder-py3/config```.

**Comment by texadactyl** [comment]
The top of the .config tree is a hidden directory.  I know that this can be confusing.

In a terminal window, do this:
```
cd /Users/user/.spyder-py3/config
```
Then you will see the spyder config file

**Comment by donet3088** [comment]
I’m finding it difficult to locate it

**Comment by texadactyl** [comment]
When you executed the above ```cd``` command, what PRECISELY did you see on the terminal?

**Comment by texadactyl** [comment]
Also, which Unix are you using?

**Comment by donet3088** [comment]
Ok now o get 4 files
Backups, defaults, spyder.ini, transient.ini

**Comment by donet3088** [comment]
What do I do next please?

**Comment by texadactyl** [comment]
The traceback is telling you that something did not parse in transient.ini.
Try renaming it to transient.ini.HOLD and relaunch spyder.

**Comment by texadactyl** [comment]
That should work around the transient.ini issue.  I just did it successfully.

**Comment by donet3088** [comment]
So to rename in terminal, I should do mv transient.ini.Hold transient.ini

**Comment by texadactyl** [comment]
yes

**Comment by texadactyl** [comment]
New to Unix?

**Comment by texadactyl** [comment]
Oops, just the reverse:

**Comment by texadactyl** [comment]
```mv transient.ini transient.ini.HOLD```

**Comment by donet3088** [comment]
Yes I did that. I want to relunch spyder from anaconda and then see if that works

**Comment by texadactyl** [comment]
Processing for all commands is left to right

**Comment by texadactyl** [comment]
I do not know what your Unix/Linux experience level is

**Comment by texadactyl** [comment]
I hope that you do not expect to use Spyder with Fortran source (E.g. seismic_cpml).  That won't work.

**Comment by donet3088** [comment]
I refer as and when I need to do anything in terminal 😃

**Comment by donet3088** [comment]
No not at all.

**Comment by texadactyl** [comment]
Did it launch?

**Comment by texadactyl** [comment]
If that does not work, try using Anaconda to uninstall and then reinstall spyder.

**Comment by donet3088** [comment]
It didn’t work. I will try to uninstall and then reinstall to see if that will work

**Comment by texadactyl** [comment]
What happened when it launched?
Details please.

**Comment by texadactyl** [comment]
"It didn't work" is not descriptive.

**Comment by donet3088** [comment]
Nothing happened when lunched from anaconda

**Comment by texadactyl** [comment]
It might be a launcher in your desktop start menu.
You could also try launching from a terminal window ("spyder" or "spyder3").

**Comment by donet3088** [comment]
Now it lunches successfully. Thanks for the assistance

**Comment by texadactyl** [comment]
Your are welcome.  So, re-installing solved it?

Please close this issue.

**Comment by donet3088** [comment]
I didn’t reinstall. Renaming the transient.ini solved the issue. I just needed to be patient for spyder to lunch

**Comment by texadactyl** [comment]
In the future, please keep in mind that detailed feedback is important to someone who is trying to help you while flying blind (cannot see your screen or what you have done).  You can provide screenshots or copy/paste of terminal window or Anaconda GUI segments or something else if that is relevant.

**Comment by donet3088** [comment]
Well noted Sir
