### ISSUE TITLE
configparser.NoOptionError: No option 'custom-0/background' in section: 'appearance'

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#13330]
Started after a computer reboot; Spyder was working before it. This is with Spyder 4.1.4 via `conda update anaconda`.

```
(tf2_env) PS C:\Users\OverL> spyder
Traceback (most recent call last):
  File "D:\Anaconda\envs\tf2_env\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\app\start.py", line 201, in main
    from spyder.app import mainwindow
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\app\mainwindow.py", line 104, in <module>
    from spyder.app.utils import set_opengl_implementation
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\app\utils.py", line 23, in <module>
    from spyder.utils.qthelpers import file_uri
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\utils\qthelpers.py", line 31, in <module>
    from spyder.utils import icon_manager as ima
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\utils\icon_manager.py", line 26, in <module>
    if is_dark_interface():
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\config\gui.py", line 150, in is_dark_interface
    if not is_dark_font_color(color_scheme):
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\config\gui.py", line 139, in is_dark_font_color
    color_scheme = get_color_scheme(color_scheme)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\config\gui.py", line 114, in get_color_scheme
    color_scheme[key] = CONF.get("appearance", "%s/%s" % (name, key))
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\config\manager.py", line 228, in get
    return config.get(section=section, option=option, default=default)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\config\user.py", line 976, in get
    return config.get(section=section, option=option, default=default)
  File "D:\Anaconda\envs\tf2_env\lib\site-packages\spyder\config\user.py", line 513, in get
    raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'custom-0/background' in section: 'appearance'
```

**Comment by OverLordGoldDragon** [comment]
Same error in a _different_ virtual env which still has 4.1.3 installed ... this isn't how Anaconda should work

**Comment by OverLordGoldDragon** [comment]
I've ran a reinstall of Anaconda following instructions [here](https://docs.anaconda.com/anaconda/install/uninstall/), and the error _still persists_, in base environment with Spyder 4.0.1, no additional package installed. No clue what's going on.

**Comment by OverLordGoldDragon** [comment]
Finally did it, with a thorough uninstall; I suspect the most important steps were deleting `.anaconda_backup`, `.spyder`, and `.spyder-py3`, but I'll still include everything I did:

 1. Delete `Anaconda/envs` and `Anaconda/pkgs`
 2. Run `Uninstall-Anaconda3.exe`
 3. `Start -> Run -> regedit`, delete:
    - HKEY_CURRENT_USER -> Software -> Python
    - HKEY_LOCAL_MACHINE_USER -> SOFTWARE -> Python
 4. Delete:
    - `C:\Users\.conda`
    - `C:\Users\.anaconda_backup`
    - `C:\Users\.spyder`
    - `C:\Users\.spyder-py3` **NOTE**: backup `config` folder inside before deleting
    - `C:\Users\Name\AppData\Local\conda`
    - `C:\Users\Name\AppData\Local\Spyder`
    - `C:\Users\Name\AppData\Local\Temp\spyder`
    - `C:\Users\Name\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)`
    - `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Python 3.7`
    
 5. Search `**conda**`, then `**spyder**`, in `C:` and `D:` to ensure nothing remains, except:
    - `Anaconda3-2020.02-Windows-x86_64.exe`
    - Files in `.vscode\extensions`
    - Files in `Microsoft Visual Studio\...\Extensions`
 6. If conda or Python (PYTHONPATH) is a system environment variable, remove them
 7. Reboot device
 8. Validate [hashes](https://docs.anaconda.com/anaconda/install/hashes/Anaconda3-2020.02-Windows-x86_64.exe-hash/)
 9. Close other applications
 10. Run `Anaconda3-2020.02-Windows-x86_64.exe`
 11. Launch `Anaconda Powershell Prompt`
 12. `spyder`

**Comment by OverLordGoldDragon** [comment]
... aand just found the culprit: `config`. No idea what exactly - [attached](https://puu.sh/G8GFF/3d1d44ca2a.zip).

**Comment by konstandev** [comment]
Have you tried reseting spyder?
1)open cmd
2)type: spyder --reset

**Comment by OverLordGoldDragon** [comment]
@konstandev If resetting involves clearing configs, it's not a solution. The fix is to restore an earlier `spyder.ini`; I'm keeping the Issue open in case maintainers wish to address this.

**Comment by dalthviz** [comment]
Just in case, I think this is related with https://github.com/spyder-ide/spyder/issues/5790

**Comment by ccordoba12** [comment]
Ok, let's close it in favor of #5790.
