### ISSUE TITLE
IndexError in Code Analysis prevents Spyder from getting launched

### ISSUE THREAD

**Issue by dasdebashish17** [spyder-ide/spyder#13342]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
On launching Spyder, I get error as mentioned below:

### What steps reproduce the problem?

1. launch Spyder
2. 
3. 

### What is the expected output? What do you see instead?
Spyder IDE not getting launched

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3638, in run_spyder
main.setup()
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 984, in setup
plugin = module.PLUGIN_CLASS(self)
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\pylint\plugin.py", line 56, in __init__
self.pylint = PylintWidget(self, max_entries=max_entries,
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 252, in __init__
self.set_filename(f)
File "C:\Users\uidn7351\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 279, in set_filename
self.curr_filenames.pop(index)
IndexError: pop index out of range
```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 
As I am unable to launch Spyder, please let me know how to get these details.

### Dependencies

```
As I am unable to launch Spyder, please let me know how to get these details.
```
```NOTE: Today I upgraded Spyder and few other modules. Since then there is this issue.```

**Comment by goanpeca** [comment]
Hi @dasdebashish17, thanks for the report.

Could you provide the missing information?

```
Spyder version:
Python version:
Qt version:
PyQt version:
Operating System name/version:
```

you can open the Anaconda Prompt and type

```
conda info
conda list
```

And paste the output here as text. 

Cheers!

**Comment by dasdebashish17** [comment]
Hello Team,

I tried reinstalling, again the same issue. 
Steps followed:

- Uninstall Anaconda
- Install latest Python 3.7 64-bit 
- Launch Spyder (it works)
- Run `conda update anaconda`
- Run `conda install spyder=4.1.4`. Syder no longer works

Regards,
Debashish

**Comment by dasdebashish17** [comment]
Hi,

Awaiting your reply.

Thanks & Regards,
Debashish

**Comment by Lucurus** [comment]
Hi team, I have the same `IndexError: pop index out of range` error. If I can help with providing any additional information, feel free to reach out.

Downgrading spyder to 4.1.3 solves the error.

**Comment by matheger** [comment]
Same problem here. 

spyder 4.1.4
python 3.83
qt 5.9.7
pyqt 5.9.2

**Comment by robert99** [comment]
Same problem 4.1.4 did work for a while then would not start giving similar error message.
Downgrading to 4.1.3 works perfectly.

**Comment by ccordoba12** [comment]
To all people that have posted here: please close Spyder, open the Anaconda Prompt, run there

    spyder --reset

and try again.

**Comment by matheger** [comment]
`spyder --reset` worked for me.

Before running that command, I made a backup of my .spyder-py3 folder to copy the old files back and see what might have caused the problem. Initially it seemed as if the `pylint.results` file might have been the culprit, but now I can't reproduce it. Maybe someone could try to simply delete that file and see if that solves things.

**Comment by ccordoba12** [comment]
> Initially it seemed as if the pylint.results

Yes. that's the culprit.

**Comment by asmunds** [comment]
Same problem: `spyder --reset` worked

**Comment by Lucurus** [comment]
I can confirm that only deleting the `pylint.results` file solves the error so there is no need for the `spyder --reset` command in case someone wants to keep their preferences.

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one to prevent it from happening (it's a very serious bug).

**Comment by robert99** [comment]
My problem is that I reverted back to Spyder 4.1.3.
My Anaconda will not allow any upgrade to 4.1.4 so that I can try the suggested workarounds.
It tells me there is an upgrade available but when run it just finishes without upgrading to 4.1.4.
