### ISSUE TITLE
Matplotlib plot window unresponsive when shown through spyder

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [spyder-ide/spyder#13348]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The window that matplotlib uses to show plots when "Graphics Backend" is set to "Automatic" is unresponsive if the code is run with spyder. The save button does not prompt the saving dialog window, and the responsiveness in general is laggy when zooming plots and rotating 3d-plots. It works just fine when the same script is run through a regular console: `python <nameofscript>`. It used to work fine with spyder 4.1.3. `spyder --reset` did not change anything. 

### What steps reproduce the problem?

1. write script that makes plots
2. set "Graphics Backend" to "automatic" or "Qt5"
3. run script through spyder

### What is the expected output? What do you see instead?

Got a plot, but cannot save it using the save button, and interaction in general is very laggy.

### Paste Traceback/Error Below (if applicable)
[log.txt](https://github.com/spyder-ide/spyder/files/4954624/log.txt)

## Versions

* Spyder version: 4.1.4
* Python version: 3.7.8
* Qt version: 5.15.0
* PyQt version: 5.15.0
* Operating System name/version: Gentoo Linux, kernel 5.7.9

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.19.0 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

# Spyder plugins:
spyder_line_profiler           :  0.2.1 (OK)
spyder_memory_profiler         :  0.2.1 (OK)
spyder_notebook                :  0.2.3 (OK)
spyder_terminal                :  0.3.2 (OK)
spyder_unittest                :  0.4.1 (OK)
```

**Comment by steff456** [comment]
Hi @AndrewAmmerlaan,
Can you please send me the snippet of code which is causing you trouble? I tried to reproduce this with simple plots and it is not presenting any error.

**Comment by AndrewAmmerlaan** [comment]
> Can you please send me the snippet of code which is causing you trouble? 

[simil-deltaomega.zip](https://github.com/spyder-ide/spyder/files/4954978/simil-deltaomega.zip)

This is rather large, sorry about that. I've experienced this issue both with `plotter2` and `plotter3`. It also occurs when I comment out the 3d plots.

This is a simulation of the quantum oscillations in InSb and the effect they have on the frequency, phase and amplitude of a oscillating cantilever. The upper section of the file is just functions I need for the simulation, the lower section contains the functions `plotter1`, `plotter2` and `plotter3`.

> I tried to reproduce this with simple plots and it is not presenting any error.

To clarify, I'm not seeing any error message either, rotating the plot and zooming the plot is just way more laggy then running the same script directly with python from a terminal. And the save button is unresponsive, while I can save if I set the "Graphics Backend" to "inline". It feels like the whole plot window is lagging when run through spyder, the animation that is shown when hovering over a button (e.g. the save button) is also delayed.

**Comment by steff456** [comment]
I'm seeing that your script is generating 8 plots, I generate them using multiple configurations of the backend of spyder and the command line, and all of them are laggy. I will recommend you to only generate and visualize one plot at the time for now, 3d plots are tricky to generate and visualize. Also, please report this issue in matplotlib, https://github.com/matplotlib/matplotlib, to see if they are able to enhance the performance.

**Comment by AndrewAmmerlaan** [comment]
> I'm seeing that your script is generating 8 plots, I generate them using multiple configurations of the backend of spyder and the command line, and all of them are laggy. I will recommend you to only generate and visualize one plot at the time for now, 3d plots are tricky to generate and visualize. Also, please report this issue in matplotlib, https://github.com/matplotlib/matplotlib, to see if they are able to enhance the performance.

I understand that the plots are rather resource heavy, but the thing is that this is laggy *only* when running it with spyder for me. There is a *significant* performance difference between running the script through spyder, and running the script directly from a terminal. Have you tried running the script from a terminal? Did you notice a difference? Are you able to save a plot through the plotting window when running the script through spyder?

**Comment by ccordoba12** [comment]
@AndrewAmmerlaan, I think your problem is related to https://github.com/ipython/ipykernel/issues/528. We're looking into it right now.

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan, I think your problem is related to [ipython/ipykernel#528](https://github.com/ipython/ipykernel/issues/528). We're looking into it right now.

@ccordoba12 Thank You, downgrading to ipykernel-5.3.2 fixed my problems :smile:
