### ISSUE TITLE
FATAL BUG: Pasting a certain code snippet into Spyder would crash the IDE.

### ISSUE THREAD

**Issue by likenji** [spyder-ide/spyder#13355]
### Issue Report Checklist

* [ T] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ T] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [T ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [T ] Tried basic troubleshooting (if a bug/error)
    * [ T] Restarted Spyder
    * [ T] Reset preferences with ``spyder --reset``
    * [ T] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ T] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. open any program in Spyder
2. Input or copy-paste
```
"""
bb-1
"""
```
3. 

### What is the expected output? What do you see instead?

The whole program crashes.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions 

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @likenji could you try to update to our latest version and try again? Seems like you are using Spyder 4.0.1, the latest version is 4.1.4. You can do this by running:

* If you are using Conda; `conda install spyder=4.1.4`
* If you are using Pip : `pip install -U spyder`

I checked with our latest version and I was unable to reproduce this.

Let us know if the update helps. Thanks!

**Comment by dalthviz** [comment]
Closing do to lack of response
