### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by mouslm01** [spyder-ide/spyder#13352]
### What steps will reproduce the problem?

run spyder3 in Terminal 

In Kernel console:

The error is:

Traceback (most recent call last):
File "/home/majed/.local/lib/python3.8/site‑packages/spyder/plugins/ipythonconsole/plugin.py", line 1223, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "/home/majed/.local/lib/python3.8/site‑packages/jupyter_client/manager.py", line 304, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "/home/majed/.local/lib/python3.8/site‑packages/jupyter_client/manager.py", line 251, in pre_start_kernel
self.write_connection_file()
File "/home/majed/.local/lib/python3.8/site‑packages/jupyter_client/connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "/home/majed/.local/lib/python3.8/site‑packages/jupyter_client/connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "/home/majed/anaconda3/envs/test_environment/lib/python3.8/contextlib.py", line 113, in __enter__
return next(self.gen)
File "/home/majed/.local/lib/python3.8/site‑packages/jupyter_core/paths.py", line 437, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
PermissionError: [Errno 13] Permission denied: '/home/majed/.local/share/jupyter/runtime/kernel�db0a1e481.json'

I am looking forward for help please.

Thanks

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.3.0-62-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  None (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by mouslm01** [comment]
Still the problem not solve

**Comment by ccordoba12** [comment]
Hey @mouslm01, did you install Spyder in the Windows Subsystem for Linux?

**Comment by dalthviz** [comment]
Also, @mouslm01 seems like you have a mixed installation of pip (--user installed) packages and anaconda. Probably you will need to remove the local packages installed at `/home/majed/.local/lib/python3.8/site‑packages/` to prevent mixing them with the conda env your trying to setup.

Let us know if that help :)

**Comment by mouslm01** [comment]
> Hey @mouslm01, did you install Spyder in the Windows Subsystem for Linux?

Hi @ccordoba12. I am install spyder and Anaconda in the Ubuntu20.

**Comment by mouslm01** [comment]
> Also, @mouslm01 seems like you have a mixed installation of pip (--user installed) packages and anaconda. Probably you will need to remove the local packages installed at `/home/majed/.local/lib/python3.8/site‑packages/` to prevent mixing them with the conda env your trying to setup.
> 
> Let us know if that helps :)

Do you mean to remove the whole packages installed at link above? 
I tried to remove it by typing:
$ sudo rm /home/majed/.local/lib/python3.8/site‑packages/

but it does not work 

rm: cannot remove '/home/majed/.local/lib/python3.8/site‑packages/': No such file or directory

Thanks

Majed

**Comment by dalthviz** [comment]
@mouslm01 I think you need to run the `rm` command with the `-r` flag. Also, since you are under your home dir, I think you should not need to run the command with `sudo`. Something like this should work: `rm -r /home/majed/.local/lib/python3.8/site‑packages/`

**Comment by ccordoba12** [comment]
Closing due to lack of response.
