### ISSUE TITLE
ENH: add "Insert above/below" options for lists in variable explorer

### ISSUE THREAD

**Issue by dpturibio** [spyder-ide/spyder#13371]
## Problem Description

My team works on Spyder integrating our system as a plugin, and we edit some variables using Variable Explorer(specifically lists). Would be very useful to have the option "insert bellow" when you right click on an item, because the "insert" option, inserts the item in the current position. So if you click in the last item and choose insert, variable explorer inserts it in penultimate position. To have it as the last item, you need to duplicate the last item and edit it(what is not very intuitive).

### What steps reproduce the problem?

1. create any list in the editor, for example: `test_list = [1,2,3,4,5]`
2. Click in Run->Run with "IPython console" and "Variable explorer" active
3. Double-click in test_list variable in "Variable explorer" window.
4. In the opened window, right click on the last item and choose "insert"
5. Type 6 for example and hit enter,
6. Validate that the item is inserted between 4 and 5 items.
7. The final sequence is 1,2,3,4,**6**,5

### What is the expected output? What do you see instead?
I suggest to add the option "insert bellow" when editing lists. How: Changing in collectionseditor.py file, class BaseTableView, setup_menu() method the following:

```
#FROM:
self.insert_action = create_action(self, _("Insert"),
                                           icon=ima.icon('insert'),
                                           triggered=self.insert_item)
#TO:
self.insert_action_above = create_action(self, _("Insert above"),
                                           icon=ima.icon('insert'),
                                           triggered=lambda:self.insert_item(bellow=False))
self.insert_action_bellow = create_action(self, _("Insert bellow"),
                                           icon=ima.icon('insert'),
                                           triggered=lambda:self.insert_item(bellow=True))

#FROM:
 menu_actions = [self.edit_action, self.plot_action, self.hist_action,
                        self.imshow_action, self.save_array_action,
                        self.insert_action, self.remove_action,
                        self.copy_action, self.paste_action,
                        self.view_action,
                        None, self.rename_action, self.duplicate_action,
                        None, resize_action, resize_columns_action]
#TO:
 menu_actions = [self.edit_action, self.plot_action, self.hist_action,
                        self.imshow_action, self.save_array_action,
                        self.insert_action_above, self.insert_action_bellow, self.remove_action,
                        self.copy_action, self.paste_action,
                        self.view_action,
                        None, self.rename_action, self.duplicate_action,
                        None, resize_action, resize_columns_action]

#FROM:
add_actions(self.empty_ws_menu,
                    [self.insert_action, self.paste_action,
                     None, resize_action, resize_columns_action])
#TO:
add_actions(self.empty_ws_menu,
                    [self.insert_action_above, self.insert_action_bellow, self.paste_action,
                     None, resize_action, resize_columns_action])
```

and in insert_item(self) method, change:

```
#FROM:
@Slot()
    def insert_item(self):
#TO:
@Slot()
    def insert_item(self, bellow=True):


#FROM:
        if not index.isValid():
            row = self.source_model.rowCount()
        else:
            row = self.proxy_model.mapToSource(index).row()
#TO:
        if not index.isValid():
            row = self.source_model.rowCount()
        else:
            if bellow:
                row = self.proxy_model.mapToSource(index).row()+1
            else:
                row = self.proxy_model.mapToSource(index).row()
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.3
* Python version: 3.8.3
* Qt version: 1.9.0
* PyQt version: 5.12.3
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment]
Thanks for opening this issue @dpturibio! It sounds like a great idea. Would you be interested in opening a pull request with these changes o would you want someone from the team to do it?

**Comment by dpturibio** [comment]
Thank you for the prompt reply @juanis2112 , I will open a pull request and link with this issue.
