### ISSUE TITLE
Error in Ipython console when specifing the Python interpreter for Spyder in the base enviroment

### ISSUE THREAD

**Issue by AZippelius** [spyder-ide/spyder#13372]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I want to change the python interpreter to one of a different conda enviroment. But once I've changed it, the ipython console doesn't start, and produces an error that shows up in the ipython window. There are also blank command prompt windows that keep popping up. This is on a fresh installation of anaconda.

Furthermore, this happens even if I set the interpreter the base enviroment to be used. This issue does not appear if the Default option is used. 

It also does not appear if Spyder is installed in a new enviroment, not base. In this case, no error appears.

### What steps reproduce the problem?

1. Install Anaconda
2. Go to Prefernces>Python Interpreter and set it to use a specified Python interpreter
3. Try to create a new ipython console

### Paste Traceback/Error Below (if applicable)
path-to-enviroment\\lib\site‑packages\setuptools\distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
"Distutils was imported before Setuptools. This usage is discouraged "
Traceback (most recent call last):
File "path-to-enviroment\\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "path-to-enviroment\\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "path-to-enviroment\\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "path-to-enviroment\\lib\site‑packages\spyder_kernels\console\start.py", line 289, in main
import_spydercustomize()
File "path-to-enviroment\\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "path-to-enviroment\\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 27, in 
from spyder_kernels.comms.frontendcomm import CommError, frontend_request
File "path-to-enviroment\\lib\site‑packages\spyder_kernels\comms\frontendcomm.py", line 17, in 
from jupyter_client.localinterfaces import localhost
File "path-to-enviroment\\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "path-to-enviroment\\lib\site‑packages\jupyter_client\connect.py", line 21, in 
import zmq
File "path-to-enviroment\\lib\site‑packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "path-to-enviroment\\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "path-to-enviroment\\lib\site‑packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "path-to-enviroment\\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "path-to-enviroment\\lib\site‑packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "path-to-enviroment\\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

## Versions

Python 3.7.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

### Dependencies

atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)

**Comment by steff456** [comment]
Hi @AZippelius,

We already fix this error in our latest release of spyder, please update with the following commands:
```
conda update anaconda
conda install spyder=4.1.4
```

Thanks for reporting!
