### ISSUE TITLE
spyder 4.1.4 does not stat

### ISSUE THREAD

**Issue by mshariful** [spyder-ide/spyder#13385]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have installed spyder 4.1.4 in Anaconda. I had an older version of spyder and it was working. I used
conda install spyder=4.1.4 to installl the new version. But now I can not start spyder. Anaconda navigator shows this error:
Traceback (most recent call last):
File "C:\Users\Shariful\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\Shariful\Anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\Users\Shariful\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3763, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\Shariful\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3638, in run_spyder
main.setup()
File "C:\Users\Shariful\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 945, in setup
from spyder.plugins.ipythonconsole.plugin import IPythonConsole
File "C:\Users\Shariful\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 24, in 
from jupyter_client.connect import find_connection_file
File "C:\Users\Shariful\Anaconda3\lib\site-packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Shariful\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 35, in 
from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write' from 'jupyter_core.paths' (C:\Users\Shariful\Anaconda3\lib\site-packages\jupyter_core\paths.py)

Please help. TIA, Shariful

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@mshariful, thanks for reporting. It seems your Anaconda installation became corrupted after you tried to update to Spyder 4.1.4.

Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) on how you can fix that problem.

**Comment by mshariful** [comment]
Thank you so much for your support. I removed spyder ( using conda remove ) and then I conda update --all
It solved the problem. :-)  
Have a nice day! Ciao, Sharif
