### ISSUE TITLE
Autocomplete "from aaa " with "import "

### ISSUE THREAD

**Issue by PanderMusubi** [spyder-ide/spyder#13405]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* n/a [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * n/a [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Autocomplete `from aaa ` with `import `. Note that both strings have a space at the end.

### What steps reproduce the problem?

1. Open a new file
2. Type `from os ` ending with a space, Any other module name could be use where now `os` is written.

### What is the expected output? What do you see instead?

Spyder should write `import ` with a space at the end after the entered characters resulting in the line `from os import ` with the cursor at the end. At the moment, nothing happens. Offering this saves the user from typing characters that are evident. This feature is also available in e.g. LiClipse with PyDev.

### Paste Traceback/Error Below (if applicable)
n/a

## Versions

* Spyder version: 4.1.4
* Python version: 3.8.2
* Qt version: 5.12.8
* PyQt version: 5.12.3
* Operating System name/version: Ubuntu 20.04

### Dependencies

```# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.3.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.17.4 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)```

**Comment by steff456** [comment]
Hi @PanderMusubi,
This is a difficult case, after multiple changes we decided that the autocompletion will not be triggered after a space because it can be really invasive specially when writing a lot. The fastest way for Spyder to write the `import` is by pressing `Ctrl+space` and `enter` selecting the first option, if you want a more automatic way of introducing this you can try using Kite completions.

**Comment by PanderMusubi** [comment]
Thanks
