### ISSUE TITLE
Spyder 4.1.4 Starting the Kernel Error 

### ISSUE THREAD

**Issue by fberks** [spyder-ide/spyder#13413]
I checked other pages and tried everything that I could find but I couldn't resolve the issue.

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After "update --all", my kernel is not starting.

### What steps reproduce the problem?
See above
1. 
2. 
3. 

### What is the expected output? What do you see instead?
N/A

### Paste Traceback/Error Below (if applicable)
An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\fberks\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1223, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\fberks\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 304, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\Users\fberks\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 251, in pre_start_kernel
self.write_connection_file()
File "C:\Users\fberks\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "C:\Users\fberks\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\fberks\Anaconda3\lib\contextlib.py", line 113, in __enter__
return next(self.gen)
File "C:\Users\fberks\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\fberks\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 377, in win32_restrict_file_to_user
win32security.SetFileSecurity(fname, win32security.DACL_SECURITY_INFORMATION, sd)
pywintypes.error: (87, 'SetFileSecurity', 'The parameter is incorrect.')

## Versions
* Spyder version: 4.1.4
* Python version: 3.8.3 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

**Comment by dalthviz** [comment]
Hi @fberks seems like the package causing this is `jupyter_core` (see https://github.com/jupyter/jupyter_client/issues/481 and https://github.com/jupyter/jupyter_core/pull/183). Maybe you could try updating/installing `jupyter_core` 4.6.3 (running something like `conda install jupyter_core=4.6.3`). Also, you could try to create another env.

Hopefully this info will let you fix your env, but there is not much more we can do, sorry :/
