### ISSUE TITLE
Linter dies in a file (4.1.4)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#13420]
[clip.mp4](https://puu.sh/GcliQ/2e6f178af5.mp4) -- This is a first, resolved with a file reopen (just like #11154). It differs from #11506 as I didn't have to restart LSP. Don't know how to reproduce yet. Note this is a fairly minimal environment (no TF, Keras, etc), even smaller than conda base, using only `conda install`.

**Comment by OverLordGoldDragon** [comment]
Possibly identical trigger, `.` (`__getattr__`), was typing fast but linter died shortly after a `.`. Only the offending file is affected.

**Comment by ccordoba12** [comment]
Ok, please let us know if you can reproduce it reliably.

**Comment by OverLordGoldDragon** [comment]
Seems resolved
