### ISSUE TITLE
Freezing for a few min on starting spyder 1.4.1

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#13433]
I am using the latest spyder on Ubuntu 16.04. I notice that when I open the spyder it freezes for a few minutes and then works fine.
It is annoying at the beginning when it freezes.
Any suggestions why this happens.

Spyder 4.1.4 
Python 3.6.6 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Linux 4.15.0-112-generic 
Using anaconda to install spyder

**Comment by ccordoba12** [comment]
Please open a terminal, run

    spyder --reset

and try again.

**Comment by seyeeet** [comment]
Thanks, I think it helps to solve it, but it also reset everything, all my project history is gone and all my custom settings are gone as well. I have mix of feeling now :|
Is there any other way for the future?

**Comment by ccordoba12** [comment]
I'm sorry you lost your settings, but without more details about why you were having this problem, it was really hard for me to offer you other kind of advice.

I hope this problem doesn't happen to you in the future.

**Comment by seyeeet** [comment]
no worries. Thanks for your help!

**Comment by seyeeet** [comment]
@ccordoba12 Unfortunately, the error show up again.
