### ISSUE TITLE
Installed Kite through spyder and it doesn't work

### ISSUE THREAD

**Issue by ismaelbrowne** [spyder-ide/spyder#13449]
## Problem Description
I installed Kite through spyder and whenever I launch spyder; 
Case 1: Sometimes spyder's launcher shows and stays stuck on "Loading code completion client for python" and I need to click on the launcher, later it will say the python isn't answering and it'll ask me if I want to try to restore Python, and if I select that option, spyder will load but Kite won't and at the bottom right of spyder it'll show "Kite: ".
Case 2: Other times spyder loads well but kite's copilot doesn't launch and at the bottom right of spyder it shows "Kite: ".
Case 3: And other times the kite copilot does launch but it stays stuck on "Initializing", and at the bottom right of spyder it shows "Kite: Indexing". 
I also tried downloading kite through the web page but the same errors occur.  Also please note I haven't tried with other IDEs and I don't think they would change that Kite never goes past "initializing" even if I launch it alone. I also tried downgrading spyder to 4.0.1 for that the LSP can't work because I read an issue that was similar to mine where downgrading spyder worked, but it didn't work for me. And I have also set an issue through the Kite issues repository but 5 days have passed and they haven't answered.

### What steps reproduce the problem?

Most of the time when I launch spyder after turning on the pc, case 1 will occur, but after closing spyder and opening it again, or case 3 or case 2 will occur, but case 3 happens most of the time when launching spyder again. But recently now when I launch spyder after turning on the pc, case 2 is starting to happen more often. Also in very little cases I need to do case 1 after closing and relaunching spyder.

## Versions

* Spyder version: 4.1.4
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Home

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @ismaelbrowne, this is clearly a problem with Kite and not with Spyder. Please report it here:

https://github.com/kiteco/issue-tracker

to get appropriate support for it.

Thanks!
