### ISSUE TITLE
No handlers could be found for logger "OpenGL.Tk"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1346]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2013-04-07T10:57:40Z_

Spyder Version:  2.2.0rc
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.3 on Linux

hello, in the internal I have this message

\>>> No handlers could be found for logger "OpenGL.Tk"

See you

Fred

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1346_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-07T09:02:11Z_

Does this happens every time you start Spyder? Or only the first time when there is no .spyder2 dir in your home dir.

**Comment by spyder-issues-migrator** [comment]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2013-04-07T09:09:13Z_

yes you are right only the first time when there is nor .spyder2 or an old one

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-11T10:48:37Z_

I know where this error is coming from, but I don't know yet how to fix.

I'll dig into it after 2.2 is released because it's a minor issue.

**Status:** Accepted  
  **Labels:** MS-v2.2 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T15:08:37Z_

**Labels:** MS-v2.2.1

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T15:10:06Z_

**Labels:** -MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-19T13:20:13Z_

**Labels:** -MS-v2.2.1 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T12:51:01Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:52:50Z_

**Labels:** -MS-v2.3.1 MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:13:24Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:14:59Z_

**Labels:** -MS-v2.3.3 MS-v2.4

**Comment by ccordoba12** [comment]
This is an old issue. Closing.
