### ISSUE TITLE
Fix some further issues with the Files pane UX

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#13465]
## Problem Description

After testing the new changes proposed in #13179 and executed in #13209 as part of reviewing spyder-ide/spyder-docs#146 , I found a few remaining issues that should be resolved. The changes should be simple and the implementation very straightforward, closely following that already reviewed #13209 , so I can have a PR ready as soon as we agree on them, which can hopefully be discussed, reviewed and merged in short order.

They are:

* [ ] ~~Rename the option `Show all files`, enabled by default, to be `Show only files matching patterns`, disabled by default, making it much clearer what this option does and what files _wouldn't_ be shown. This was very confusing to me as a user, and that was _before_ I tested the latest changes with the `Show hidden files` option, which makes what `Show all files` does even more befuddling. I would also move this option to be directly above the option to edit filename filters, so its more clearly connected with that.~~ Simply remove the option, have filters always on if any are present, and clear the filter list by default.
* [ ] Rename the option `Show filenames with these extensions...` to `Edit filename filters...` to avoid misleading users that only the extensions are matched, since the patterns can match anywhere in the name, and in fact a third of the default patterns don't involve extensions at all. It also links it more clearly with the option that enables/disables the filter.
* [ ] Make the window title of the filename filter dialog match the options menu text (it currently is stuck with the old name) and add a clearer description, e.g. `Enter the glob patterns, separated by commas, at least one of which a filename must match to be shown if any have been entered.`
* [ ] Modify the preferences accordingly and add a section around it
* [ ] Change `Python script` to `Python file` in the `New` submenu, since the file can be either a script, a module or both.

![image](https://user-images.githubusercontent.com/17051931/89362360-5ef6f180-d693-11ea-8e20-dddfdaee6a1e.png)

@ccordoba12 , am I good to go ahead with a PR with these changes? Thanks!

**Comment by CAM-Gerlach** [comment]
Note, we will either have to special-case the situation of no patterns being entered, since that would mean no files would be displayed (since the patterns show, not hide, files), which is probably optimal for performance and ease of understanding, or have the default value be `*` which includes everything. Alternatively, we could have the filters be a list of file types to exclude; that might be easier to understand and would make the behavior with nothing entered more intuitive and natural, but I'm not sure how well that would fit the usecase vs. the status quo (I don't really use it myself).

Also, updated the various parts based on what we discussed.

**Comment by juanis2112** [comment]
After our meeting with Isabella and taking into account your suggestions, these are the changes that we propose:

- [ ] Add filter icon as button on toolbar (needs the blue outline pressed state)

- [ ] Add tooltip for new button (maybe “Activate and deactivate filter”)

- [ ] Change hamburger menu description to “Edit filter settings” or something similar (this menu item is now the way to open the dialog)

- [ ] Remove “Show all files” option in the hamburger menu

- [ ] Add “Return to default” button in the filter settings dialog 

- [ ] Change Python script to Python file in the New submenu

- [ ] Make the window title of the filename filter dialog match the options menu text 

- [ ] Add a description in the filter dialog

**Comment by juanis2112** [comment]
@steff456 can you take care of this one please?

**Comment by isabela-pf** [comment]
I think it would be good to add just a little more info to the Edit Filter dialog so that it's not only the (extremely important) technical info. I'd also add a simple suggestion of filter use like "Filter files by name, extension, or more using glob patterns" before @CAM-Gerlach's explanation of glob patterns. I think of this proposed addition as the "why" to the technical "how."

I'd also like to make sure the dialog's title matches the name of the hamburger menu item (Edit Filter).

**Comment by CAM-Gerlach** [comment]
Thanks @isabela-pf Definitely agreed, I'm a lot happier with that vs. the original, since it does a much better job explaining what they can be used for and many users without a *nix background may not be familiar.
