### ISSUE TITLE
Plotnine plots not showing up

### ISSUE THREAD

**Issue by salil91** [spyder-ide/spyder#13464]
I am running the example code from the plotnine website using a script. The plot shows up with the exact same code in Jupyter, but not in Spyder (neither inline, nor in the Plots window)

```
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))

```

Found a workaround but hoping for a more practical solution. I slightly modify the ggplot code in the script to
`ss=(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)')))
`
and then type the following into the console:
`(ss+ geom_point() + stat_smooth(method='lm') + facet_wrap('~gear'))
`

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment]
@salil91, thanks for reporting. You're right: `plotnine` plots are not being shown in Plots nor the console when running cells or files.

Right now, the only solution is to break your file into two cells:

```python
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

#%%

(ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))
```

Then go to `Tools > Preferences > Editor > Run cide` and activate the option called `Copy full cell contents to the console when running code cells`. And finally run both cells with `Shift+Enter`.

**Comment by ccordoba12** [comment]
@impact27, could you take a look at this one? I don't understand why this happens because (as far as I know) `plotnine` is a wrapper around Matplotlib, in a similar way to Seaborn.

**Comment by salil91** [comment]
> @impact27, could you take a look at this one? I don't understand why this happens because (as far as I know) `plotnine` is a wrapper around Matplotlib, in a similar way to Seaborn.

I can confirm that Seaborn plots work fine when I choose "inline" under Preferences > IPython console > Graphics > Graphics backend.

**Comment by impact27** [comment]
This doesn't work either:
```python
In [2]: from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
   ...: from plotnine.data import mtcars
   ...: def a():
   ...:     (ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
   ...:      + geom_point()
   ...:      + stat_smooth(method='lm')
   ...:      + facet_wrap('~gear'))
   ...: a()
```

So the problem is that this package doesn't plot when called from a function somehow. Is that the case in jupyter?

**Comment by impact27** [comment]
There is the same problem in the jupyter console, so this is not a Spyder issue

**Comment by salil91** [comment]
I do not face the same problem in Jupyter. The code I included in the original post creates a plot as intended in Jupyter.

**Comment by ccordoba12** [comment]
> Should we report it upstream?

Yes, please do @impact27. If things doesn't work on Qtconsole, then this is not our fault.

**Comment by impact27** [comment]
So the answer is: you need to print the object:

```python
from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
from plotnine.data import mtcars

a = (ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
 + geom_point()
 + stat_smooth(method='lm')
 + facet_wrap('~gear'))

print(a)
```

**Comment by salil91** [comment]
> So the answer is: you need to print the object:
> 
> ```python
> from plotnine import ggplot, geom_point, aes, stat_smooth, facet_wrap
> from plotnine.data import mtcars
> 
> a = (ggplot(mtcars, aes('wt', 'mpg', color='factor(gear)'))
>  + geom_point()
>  + stat_smooth(method='lm')
>  + facet_wrap('~gear'))
> 
> print(a)
> ```

This works! Thank you!

**Comment by SalenaAshton** [comment]
This worked for me too, using vim on ubuntu. Thanks.

**Comment by fhg-isi** [comment]
a.draw(True) also works. When using print I would expect some console output.
