### ISSUE TITLE
go to definition erros

### ISSUE THREAD

**Issue by SpongeBob-Q** [spyder-ide/spyder#13477]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @SpongeBob-Q without more info is quite difficult to us to provide you some help/guidance. If the problem persist, please checkout our [Troubleshooting Guide & FAQ](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ).
