### ISSUE TITLE
Manjaro Spyder Bugs

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#13487]
OS: Manjaro 20.0.3 Lysia
Kernel: x86_64 Linux 5.7.9-1-MANJARO

* Spyder version: 4.1.3 on Manjaro / 4.1.4 on Anaconda
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt version: 5.9.2

0. I am a manjaro user. I have downloaded spyder from pacman (I don't use spyder from anaconda because it cannot open .py files simply by double clicking the file). It is very slow and sometimes stop when clicking "OK" on settings and returns this:
![Screenshot_20200806_171845](https://user-images.githubusercontent.com/65082432/89514806-eb76f080-d808-11ea-9444-bcb14024574d.png)

1. I found that my spyder on anaconda for linux cannot use all the mono fonts on my computer, and I cannot input letters besides English, like Greek letters or Chinese characters.

2. On the other hand, with anaconda for windows, where its spyder can type Chinese, I found that the line height will become higher when that line has Chinese characters in the same font size, unlike VScode or PyCharm where the line heights are fixed. (It seems that in 4.1.3 for Manjaro it is OK, maybe it is Windows' fault?)

3. My language is set to Chinese, copy and paste texts in Chinese into Spyder is OK.If you try to input the letter, does nothing happen, or is a different letter produced instead? It will review the English letter because in fact I cannot change my input method into Chinese, so what I print is what I see.

4. Spyder has no permission for ipython-kernel
I have downloaded spyder from pacman (I don't use spyder from anaconda because it cannot open .py files simply by double clicking the file). But when I set the interpreter as anaconda python and installed ipython-kernel, it says that:

An error ocurred while starting the kernel
The error is:

![Screenshot_20200806_171745](https://user-images.githubusercontent.com/65082432/89514707-c4202380-d808-11ea-9b15-0a82abf350fc.png)

Like it can only use the default interpreter, installed when installing Manjaro. conda update anaconda & conda install jupyter_client=5.3.4 don't work.

I hope that Spyder can do better in supporting numerous languages. Maybe we can choose several fonts like VScode, with priority levels, and remain the line height fixed. And also for the Manjaro version, give the permission to use all python interpreters on the computer instead of the default python on /root. Thank you！

**Comment by ccordoba12** [comment]
About your issues:

0. We can't help you with that. Please report it to the maintainers of the Spyder package in Manjaro.
1. This is probably the same issue as #4120. Unfortunately, there's no solution at the moment because it'll require a significant effort to compile and upload packages for input method libraries on Linux (such as [fcitx-qt5](https://github.com/fcitx/fcitx-qt5)).
2. Please upload a screenshot to understand what you mean.
3. Same as issue #4120.
4. Not something we can fix here, sorry. Please report it to the Manjaro maintainers.

**Comment by ccordoba12** [comment]
Also, please be patient for next time instead of opening 3 or 4 issues to report the exact same problem. We volunteer our time to give support to our users and although we try to respond as quickly as we can, sometimes we need sometime to respond or we're simply not available.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
