### ISSUE TITLE
Size of autosave window

### ISSUE THREAD

**Issue by EleanorCoutts** [spyder-ide/spyder#13489]
### What steps will reproduce the problem?

After Spyder crashes the autosave window pops up, but I cannot choose any of the options, as the size of the window is too small, I can only see the table headers, not the options listed below the headers. 

I am using an Alienware laptop running Win10, screen res is 3840x2160 (recommended), scale is 250x (recommended). 

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.12.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
numpydoc >=0.6.0             :  0.9.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.7 (OK)
pygments >=2.0               :  2.5.2 (OK)
pylint >=0.25                :  2.4.4 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.1 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.1 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.4.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.15 (OK)
matplotlib >=2.0.0           :  3.1.3 (OK)
numpy >=1.7                  :  1.18.1 (OK)
pandas >=0.13.1              :  1.0.1 (OK)
scipy >=0.17.0               :  1.4.1 (OK)
sympy >=0.7.3                :  1.5.1 (OK)
```

**Comment by EleanorCoutts** [comment]
Example screenshot below

![Autosave_screenshot](https://user-images.githubusercontent.com/64859102/89549841-c1b9cb80-d800-11ea-89be-02525539e8de.png)

I cannot resize the window, and there is only a scroll bar to scrool horizontally, not vertically.

**Comment by juanis2112** [comment]
Hi @EleanorCoutts, thanks for opening this issue. This was fixed in a later version of Spyder. Please update your Spyder by running in your anaconda prompt:

```
conda update anaconda
conda update spyder
```

**Comment by EleanorCoutts** [comment]
Thankyou, I didn't realise it was an older version, will update. Thanks!!

**Comment by juanis2112** [comment]
No problem, let me know if this solves your problem :)
