### ISSUE TITLE
4 Bugs in Spyder for Manjaro

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#13486]
OS: Manjaro 20.0.3 Lysia
Kernel: x86_64 Linux 5.7.9-1-MANJARO

* Spyder version: 4.1.3 on Manjaro / 4.1.4 on Anaconda
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt version: 5.9.2

0. I am a manjaro user. I have downloaded spyder from pacman (I don't use spyder from anaconda because it cannot open .py files simply by double clicking the file). It is very slow and sometimes stop when clicking "OK" on settings and returns this:
[OK] [OK] [OK]
1. I found that my spyder on anaconda for linux cannot use all the mono fonts on my computer, and I cannot input letters besides English, like Greek letters or Chinese characters.

2. On the other hand, with anaconda for windows, where its spyder can type Chinese, I found that the line height will become higher when that line has Chinese characters in the same font size, unlike VScode or PyCharm where the line heights are fixed. (It seems that in 4.1.3 for Manjaro it is OK, maybe it is Windows' fault?)

3. My language is set to Chinese, copy and paste texts in Chinese into Spyder is OK.If you try to input the letter, does nothing happen, or is a different letter produced instead? It will review the English letter because in fact I cannot change my input method into Chinese, so what I print is what I see.

4. Spyder has no permission for ipython-kernel
I have downloaded spyder from pacman (I don't use spyder from anaconda because it cannot open .py files simply by double clicking the file). But when I set the interpreter as anaconda python and installed ipython-kernel, it says that:

An error ocurred while starting the kernel
The error is:

**PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site‑packages/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh'**

Like it can only use the default interpreter, installed when installing Manjaro.

I hope that Spyder can do better in supporting numerous languages. Maybe we can choose several fonts like VScode, with priority levels, and remain the line height fixed. And also for the Manjaro version, give the permission to use all python interpreters on the computer instead of the default python on /root. Thank you！

**Comment by ccordoba12** [comment]
Hey @1900011604, please report your problem with the Manjaro developers. This issue was introduced by them, not by us.
