### ISSUE TITLE
plt savefig not working

### ISSUE THREAD

**Issue by lorenzznerol** [spyder-ide/spyder#13498]
I have no time for a thorough and reproducible report, I might improve this in a week. Please just see the link.

https://stackoverflow.com/questions/53217247/stop-showing-plots-in-spyder/53217344#53217344

Essence from the comment below the question:

The plt.ioff() helped me only at first: now a day later, using the exactly same script, I do not get the png saved. The other answer (deactivate graphics support in "Preferences | IPython Consonle | Graphics | Support for Graphics") does not help either in this situation. I use Spyder 4.1.4 on Windows 10 64bit. The same script is running fine in PyCharm.

The script that does not save the png:

        # Plot
        result_mul = seasonal_decompose(x=df.data, model='multiplicative', extrapolate_trend='freq', period=3)
        plt.rcParams.update({'figure.figsize': (10,10)})
        result_mul.plot().suptitle('Multiplicative Decompose', fontsize=22)
        plt.savefig('example.png', format="png")
        plt.close()

**Comment by ccordoba12** [comment]
> I have no time for a thorough and reproducible report

Ok, please let us know when you have one.

**Comment by lorenzznerol** [comment]
I have found the files. The files have been saved directly in my user folder `C:\Users\Admin`. Apparently, my working directory was not set correctly. Normally, I would expect Spyder to set the working directory to the directory of the .py file itself. It is possible that I have missed something here, since I have found other pictures saved a month ago, thus I do not make this mistake the first time. Could you please tell me whether in Spyder the working directory needs to be set in every session?

**Comment by lorenzznerol** [comment]
I found out at https://stackoverflow.com/questions/38393628/set-working-directory-in-python-spyder-so-that-its-reproducible that this is an old and still open issue, see https://github.com/spyder-ide/spyder/issues/3154. This can be closed.

**Comment by ccordoba12** [comment]
Glad you figured this one out. I was about to tell you the same. I doubt we'll address because we're clearly displaying what the current directory is at any time and for every console.
