### ISSUE TITLE
Debug switch function, function in the window before the data is gone.

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#13493]
## Problem Description

I am debugging a called function. When I use Ctrl+F11 to jump to the inside of this function to debug, I find that the window in the upper right corner of the spyder loses the variables before entering the function. Is there a way to retrieve these variables?

For example, in the following example, I set a breakpoint on the line y_pred = rnn.forward(X[i]). When I enter the forward function to debug, the variables X, Y, rnn, learning_rate, etc., saved in the window They are temporarily hidden. After entering forward, the window only displays the variables such as self and x of forward itself. I want to see the original X, Y, rnn, learning_rate at the same time as the debug forward function. Can it be achieved?
------------------------------------
    X, y_int2, y_int10 = gen_data(20, 2, 5) # X.shape---(samples, input_size1, input_size2)
    X = np.array(X)        # A sample of data is [X[0], Y[0]]
    Y = np.array(y_int10)  # Y.shape=(20, 1)---(samples, input_size)
    # 初始
    rnn = RNN(5, 2)  # input_size, hidden_size
    learning_rate = 1e-3
    for epoch in range(3000):
        for i in range(len(X)):
            y_pred = rnn.forward(X[i])
------------------------------------
    def forward(self, x):
        self.h_state = []
        self.x = x
        h = np.zeros(self.hidden_size)
        for i in x:
            self.h_state.append(h)
            h = self.rnncell.forward(i, h) # h每次被更新后保存到h_state
        self.h_out = h
        return self.h_out
------------------------------------
### What steps reproduce the problem?

1. 
2. 
3. 

## Versions

* Spyder version: 4.1.2
* Python version: 3.6.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu16

**Comment by juanis2112** [comment]
@impact27 can you take a look at this one?

**Comment by impact27** [comment]
When you are debugging, the variable explorer only shows the current variables. When you are inside `def forward(self, x):`, `X, Y, rnn, learning_rate, etc.` are not defined so they are not displayed in the variable explorer. If you need to get these values, you should use the pdb `up` command (https://docs.python.org/3/library/pdb.html#pdbcommand-up) to go up on the call stack. You will then have access to all these variables. To go back down, use `down` (https://docs.python.org/3/library/pdb.html#pdbcommand-down)
