### ISSUE TITLE
matplotlib plot is not showing mathematical cherecters

### ISSUE THREAD

**Issue by srvmig** [spyder-ide/spyder#13497]
I tried to plot some data with some mathematical character. But I am not getting the LaTex on the plotted chart.
```from pylab import  *
import numpy as np

x = np.linspace(-np.pi, np.pi, 256, endpoint=True)

## compute cos for every x
y = np.cos(x)

## compute sin for every x
y1 = np.sin(x)

## plot cos
plot(x, y)

## Plot sin
plot(x, y1)

## define plot title
title('Functions $\sin$ and $\cos$')

## set x limit
xlim(-3.0, 3.0)
## set y limit
ylim(-1.0, 1.0)

## format ticks at specific values
xticks([-np.pi, -np.pi/2, 0, np.pi/2, np.pi],
       [r'$-pi$', r'$-pi/2$', r'$0$', r'$pi/2$', r'$pi$'])

yticks([-1,0,1],
       [r'$-1$', r'$0$', r'$1$'])
show()
```

![Figure 2020-08-08 124336](https://user-images.githubusercontent.com/45663120/89704440-8ab8f680-d975-11ea-96d7-e0da5cea7a9d.png)

## Versions

* Spyder version: 4.1.4
* Python version: 3.7.7
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: windows 10

**Comment by jitseniesen** [comment]
I don't think this has anything to do with Spyder, so I'm closing this issue.

If you want the symbol for pi (the Greek letter), you need to add a backslash and write `r'$\pi$'` instead of `r'$pi$'`.
