### ISSUE TITLE
Unable to Sort by Numeric Value

### ISSUE THREAD

**Issue by MMS413** [spyder-ide/spyder#13491]
Problem Description
I am unable to sort by Numeric Value.

### What steps reproduce the problem?
import pandas 
data = pandas.read_csv('nesarc_pds.csv', low_memory=False)
data["S2AQ8A"] = data["S2AQ8A"].apply(pandas.to_numeric,errors="coerce")
data["S2AQ8B"] = data["S2AQ8B"].apply(pandas.to_numeric,errors="coerce")

print("counts for S2AQ8A - How often drank in last 12 months")
c4 = data["S2AQ8A"].value_counts(sort=False, dropna=False)
print (c4)

print("percentages for S2AQ8A How often drank in last 12 months")
p4 = data["S2AQ8A"].value_counts(sort=False, normalize=True)
print (p4)

print("counts for S2AQ8B - How many drinks consumed on days when drank")
c5 = data["S2AQ8B"].value_counts(sort=False, dropna=False)
print (c5)

print("percentages for S2AQ8B How many drinks consumed on days when drank")
p5 = data["S2AQ8B"].value_counts(sort=False, normalize=True)   
print (p5)

### What is the expected output? What do you see instead?
The output I get is:
counts for S2AQ8A - How often drank in last 12 months
NaN     16147
8.0      1805
3.0      2619
4.0      2914
2.0      1210
1.0      1865
9.0      3210

Name: S2AQ8A, dtype: int64
percentages for S2AQ8A How often drank in last 12 months
8.0     0.066986
3.0     0.097194
4.0     0.108142
2.0     0.044905
1.0     0.069212

Name: S2AQ8A, dtype: float64
counts for S2AQ8B - How many drinks consumed on days when drank
NaN     16147
1.0     10350
3.0      3678
2.0      7880
4.0      1724

Name: S2AQ8B, dtype: int64
percentages for S2AQ8B How many drinks consumed on days when drank
1.0     0.384102
2.0     0.292437
3.0     0.136495
4.0     0.063980

Name: S2AQ8B, dtype: float64

#####
The output I EXPECT (want to get) is: 

counts for S2AQ8A - How often drank in last 12 months
NaN     16147
1.0      1865
2.0      1210
3.0      2619
4.0      2914

Name: S2AQ8A, dtype: int64
percentages for S2AQ8A How often drank in last 12 months
1.0     0.069212
2.0     0.044905
3.0     0.097194
4.0     0.108142

Name: S2AQ8A, dtype: float64
counts for S2AQ8B - How many drinks consumed on days when drank
NaN     16147
1.0     10350
2.0      7880
3.0      3678
4.0      1724

Name: S2AQ8B, dtype: int64
percentages for S2AQ8B How many drinks consumed on days when drank
1.0     0.384102
2.0     0.292437
3.0     0.136495
4.0     0.063980

Name: S2AQ8B, dtype: float64

**Comment by andfoy** [comment]
Hi @MMS413, thanks for reaching out, according to your issue report, it seems that it is not related to Spyder but instead it is related to Pandas. By inspecting your code it seems that you are using the ``sort=False`` flag on some calls, please make sure you doublecheck against the Pandas API documentation to see if there any directions to follow.
