### ISSUE TITLE
Feature ;Recommendation for spyder 5.0

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#13495]
Am using over the last 3 years, this is a great IDE, why ?
(am on windows)

   Variable Explorer is perfect for quick coding/data wrangling.
   Embedded Ipython for quick prototyping / debugging.
   Auto-completion is good, not perfect, but doing the job of accelerating typing.
   Can open Jupyter notebook (!!!)
   "Relatively" stable.

Now, am using Spyder 3.0 instead of Spyder 4.0 , why ?  

     New features was brought Auto-completion, in the end this became very instable, barely usable.
     The only spyder version I found usable is 4.0 beta 5 
     A lot of code/feature breaking ; Variable Explorer. Pane freezing,....
     Finally, I came back to Spyder 3.0 , Why   :  
     It just works, without heavy memory   :  
        Variable Explorer, Auto-completion, Open Jupyter notebook, Almost never crash....

My advice for Spyder 5,0 :  
    Double the amount of code testing,  
    Add testing using "IDE Robot Click"  to simulate basic user scenarios....
    Just having basic things work well, is the key for productivity (vs a ton of features, not usable).

Thanks

**Comment by ccordoba12** [comment]
Thanks for reporting @arita37. Most of the issues you mentioned have been fixed in our 4.1.4 version, released last month. And we're still working on more fixes for our next version (4.2.0), to be released in a couple of months.

**Comment by arita37** [comment]
This is good work.
However, advice to find a way to do regression testing more deeply...
Spyder 3 is a model of stability

**Comment by arita37** [comment]
This is for automatic GUi testing :

https://towardsdatascience.com/automate-ui-testing-with-pyautogui-in-python-4a3762121973
