### ISSUE TITLE
Restarting Kernel after error message

### ISSUE THREAD

**Issue by DataGrl** [spyder-ide/spyder#13501]
### What steps will reproduce the problem?

I ran this code, received an error message. Spyder stopped running, I clicked on restart kernel and then an error box appeared saying Spyder had an internal error.

# Create a watermark program so Pop can "write" on the digital photos
# Steps:
    # 1. Open a photo he selects
    # 2. Make a copy of that pictures
    # 3. Display the picture for him
    # 4. Accept his wording
    # 5. Save picture under a different name

# Import packages
import matplotlib.pyplot as plt
from tkinter import *
from PIL import ImageTk, Image
from tkinter import filedialog
from PIL import ImageFont
from PIL import ImageDraw

# This is where the code for opening the image should go
root = Tk()
root.title('Open File')

root.filename = filedialog.askopenfilename(initialdir="D:/PythonCode/PhythonImage",
                                           title="Select a file",
                                           filetypes=(("jpg files", "*.jpg"),
                                                      ("All files", "*.*")))

print('Open image')
# open the images
# img = Image.open("JulieSample.jpg")
# img2 = Image.open("IMG00698.jpg")

my_label = Label(root,text=root.filename).pack()
print('')
print(my_label)
# img = ImageTk.PhotoImage(Image.open(root.filename))
# img = Image.open(root.filename)
img = Image(root.filename)
print('')
print(root.filename)
im = img

my_image_label = Label(image = img).pack()

# Place code to show image here

# This is the input for the image
mark = input("Enter Text: ")

# Text Watermark
# Use this to create a program, where Pop can open an image, create text,
# and write what these pictures are and who is in them.

watermarked_image = im.copy()
draw = ImageDraw.Draw(watermarked_image)
font = ImageFont.truetype("arial.ttf",200) # choose font

# (pos, text, fill_color, font_object)
draw.text((0,0),mark,(0,0,0),font=font)

#draw tex
plt.imshow(watermarked_image)

# Add code to save image here

# Add code to ask user to shutdown
# or choose another picture

root.mainloop()

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 868, in send_signal
    cext.proc_kill(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\client.py", line 578, in _restart_thread_main
    stderr=self.stderr_handle)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 361, in restart_kernel
    self.shutdown_kernel(now=now, restart=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 327, in shutdown_kernel
    self.finish_shutdown()
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 289, in finish_shutdown
    self._kill_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 86, in _kill_kernel
    self.kill_proc_tree(self.kernel.pid)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\utils\manager.py", line 59, in kill_proc_tree
    child_process.send_signal(sig)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 292, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 1214, in send_signal
    self._proc.send_signal(sig)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=21444)
```

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.4.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.1 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @DataGrl, thanks for reporting!

This can be fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.4

**Comment by ccordoba12** [comment]
Closing due to lack of response.
