### ISSUE TITLE
Error with Keras and Spyder in macOS Catalina

### ISSUE THREAD

**Issue by luismiguells** [spyder-ide/spyder#13500]
## Problem Description

I try to run a piece of code using Keras and Spyder but when I click start the kernel restart. This is what the console show:

```python-traceback

Using TensorFlow backend.
2020-08-08 10:00:42.403342: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-08 10:00:42.403645: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 12. Tune using inter_op_parallelism_threads for best performance.
Trainig process...
Epoch 1/5

Restarting kernel... 

[SpyderKernelApp] WARNING | No such comm: e1cbc398d98711ea94c1acde48001122

```

 I'm using a virtual environment to run Keras and Python 3.6.10. Because in Anaconda the version of Tensorflow is 2.0.0 and that is not supported in Python 3.8. I attached a photo of the problem.
![Captura de Pantalla 2020-08-08 a la(s) 9 53 05](https://user-images.githubusercontent.com/25065697/89713526-d790d300-d95d-11ea-977a-4c258a0a506f.png)

## Versions

* Spyder version: 4.1.4
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS 10.15.6

**Comment by ccordoba12** [comment]
Hey @luismiguells, thanks for reporting!

As you can clearly see, that's just a warning. Therefore, please ignore it.

**Comment by luismiguells** [comment]
@ccordoba12 yes it's a warning but I can't run my code. After Catalina updated I've been experiment troubles with Keras and Python, and I can't install the latest version of Keras.

**Comment by ccordoba12** [comment]
Sorry to hear it, but that's not a problem with Spyder.

**Comment by RSKothari** [comment]
I have the exact same problem on my system. My situation has nothing to do with tensorflow or any other library, the kernel just restart with the following cryptic message:
![image](https://user-images.githubusercontent.com/10388010/90125584-455b4700-dd30-11ea-881f-66cdc2b30ee6.png)

**Comment by ccordoba12** [comment]
As you can clearly see, it's just warning. So please ignore it.
