### ISSUE TITLE
Tkinter window different format while executing .py file and with spyder

### ISSUE THREAD

**Issue by manojbuddha** [spyder-ide/spyder#13506]
My Tkinter window is appearing different while I am executing the .py file compared to how it is appearing while executing with spyder. I want my window to look like spyder execution on normal .py file execution. I am not sure what is causing this, i suspect it is something related spyder encoding or something

spyder version: 4.1.3
Python version: 3.7.6 (anaconda installation)

The below image is the execution of .py file
![without spyder](https://user-images.githubusercontent.com/62382910/89760572-4b6fde80-db0a-11ea-9e5f-e94d047fb0df.jpg)
the below image is execution with spyder
![with spyder](https://user-images.githubusercontent.com/62382910/89760575-4d39a200-db0a-11ea-9c33-6ca121b89ebe.jpg)

GIT Hub link: https://github.com/manojbuddha/minesweeper-using-tkinter.git (code link)

**Comment by steff456** [comment]
Hi @manojbuddha, 

I'm not encountering your problem in macOS,
This is the result of your code in spyder:
![image](https://user-images.githubusercontent.com/20992645/89820976-74e13800-db13-11ea-83ca-f7ef30824fd7.png)

This is the result running in the terminal:
![image](https://user-images.githubusercontent.com/20992645/89821053-980be780-db13-11ea-9870-fb556c0d83d3.png)

Are you running the code in the same environment in both cases?

**Comment by manojbuddha** [comment]
@steff456 , yes I am running the code in the same environment for both the cases.

**Comment by manojbuddha** [comment]
@steff456 , thanks for the help it was due to an issue with my code, I gave different font weights which was the reason for the issue.

**Comment by steff456** [comment]
I'm glad that you fixed your error! Thanks for reporting :)
