### ISSUE TITLE
Plotting won't work after introducing Fix #525

### ISSUE THREAD

**Issue by AlgDevK** [spyder-ide/spyder#13517]
### What steps will reproduce the problem?

I experienced the same problem as reported in issue #13275 after installing Spyder 4.1.4. The fix proposed in #525 got rid of the flush of warning in the console, but plotting became very slow (interactive zooming etc. takes forever) and the plot windows mostly stay in the background. I tried differnt things, like changing the backend and reinstalling Anaconda but finally found that commenting out the lines of code that were proposed in fix #525 was the only thing that fixed the plotting issue. But then I get the warnings back. 
This can be reproduced by plotting anything, like e.g. x = [1,2,3,4,5], plt.plot(x) (matplotlib.pyplot)
What can I do? Thanks!

**Comment by ccordoba12** [comment]
Hey @AlgDevK, please update to ipykernel 5.3.4. This problem is fixed in that version.

**Comment by AlgDevK** [comment]
Thanks! I tried to update the ipykernel but it won't work. conda install ipykernel will always install/keep 5.3.2.

**Comment by ccordoba12** [comment]
You need to run 

    conda update ipykernel
