### ISSUE TITLE
TFinstall Fault

### ISSUE THREAD

**Issue by Modamam** [spyder-ide/spyder#13515]
### What steps will reproduce the problem?

Spyder has encountered an internal problem! What should I do?!

### Traceback
```python-traceback
  File "E:\D\PYTHON\envs\keras\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

During handling of the above exception, another exception occurred:

ImportError: numpy.core.multiarray failed to import
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by steff456** [comment]
Hi @Modamam,
It seems this isn't a problem of Spyder rather than from traitlets. Did you encountered this problem after installing tensorflow in your environment? And how did you installed it?

**Comment by Modamam** [comment]
> Hi @Modamam,
> It seems this isn't a problem of Spyder rather than from traitlets. Did you encountered this problem after installing tensorflow in your environment? And how did you installed it?

Hi Stephannie, thanks for your answer. 
I faced it after installing hdf5 by adding it to anaconda's environment. I didn't have any clue about hdf5 but I saw an error of hdf5 version when I tried to import newly installed tensorflow . 
Then I tried to uninstall installed libraries, but I can't

**Comment by steff456** [comment]
Can you please try to install everything in a new environment to see if it works?

**Comment by Modamam** [comment]
I did and encountered this problem 

"from keras import models
Traceback (most recent call last):

  File "E:\D\PYTHON\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *

ImportError: DLL load failed: The specified module could not be found.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "E:\D\PYTHON\lib\site-packages\keras\__init__.py", line 3, in <module>
    from tensorflow.keras.layers.experimental.preprocessing import RandomRotation

  File "E:\D\PYTHON\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util

  File "E:\D\PYTHON\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context

  File "E:\D\PYTHON\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe

  File "E:\D\PYTHON\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow

  File "E:\D\PYTHON\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "E:\D\PYTHON\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-4df790c7bc60>", line 1, in <module>
    from keras import models

  File "E:\D\PYTHON\lib\site-packages\keras\__init__.py", line 6, in <module>
    'Keras requires TensorFlow 2.2 or higher. '

ImportError: Keras requires TensorFlow 2.2 or higher. Install TensorFlow via `pip install tensorflow`"

Actually the tensorflow version shown on my new environment is 2.3!

**Comment by steff456** [comment]
I will suggest you to follow the official guide of installation of tensorflow, https://www.tensorflow.org/install in a new environment. If you continue to encounter problems, please open an issue in the tensorflow repository https://github.com/tensorflow/tensorflow

We cannot do anything further because this is not a problem related to Spyder, hope you can fix it and thanks for reporting!

**Comment by Modamam** [comment]
OK. Thanks for you explanation
