### ISSUE TITLE
Spyder will not launch with Python 2.7

### ISSUE THREAD

**Issue by larajan67** [spyder-ide/spyder#13510]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have to use Python 2.7 due to a required python module 'arcPy' for my code that due to my ArcGIS copy (version 10) I can not update. I have created a new environment via conda with python 2.7. When I try to install the latest version of Spyder it does not work. If I install a version <3.2.5 I can get Spyder installed, but then it will not launch. I reset Spyder and it still will not launch.

### What steps reproduce the problem?

1. Uninstall and Reinstall Anaconda
2. Install Spyder 3.2.4 via conda
3.  Launch Spyder via command prompt or the Anaconda Navigator

### What is the expected output? What do you see instead?

The expected output is Spyder launches and opens. I see instead Spyder attempt to open and then crash. 

### Paste Traceback/Error Below (if applicable)

PASTE TRACEBACK HERE
Traceback (most recent call last):
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\Scripts\spyder-script.py", line 3, in 
import spyder.app.start
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\lib\site-packages\spyder\app\start.py", line 26, in 
from spyder.config.base import get_conf_path, running_in_mac_app
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\lib\site-packages\spyder\config\base.py", line 362, in 
_ = get_translation("spyder")
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\lib\site-packages\spyder\config\base.py", line 334, in get_translation
language = load_lang_conf()
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\lib\site-packages\spyder\config\base.py", line 315, in load_lang_conf
lang = get_interface_language()
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\lib\site-packages\spyder\config\base.py", line 286, in get_interface_language
spyder_languages = get_available_translations()
File "C:\Users\ljansen-admin.ESM-SB1-314-JB\Desktop\ANAconda\envs\py2\lib\site-packages\spyder\config\base.py", line 257, in get_available_translations
error = _('Update LANGUAGE_CODES (inside config/base.py) if a new '
NameError: global name '_' is not defined
## Versions

* Spyder version: 3.2.4
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Windows 10

```

**Comment by steff456** [comment]
Hi @larajan67,

You have multiple options:
1. Create a conda environment with Spyder 3.3.6, which is the stable version for Spyder 3 that supports Python 2.
2. Create a conda environment with Spyder 4.0.1, which is the last Spyder version that has all packages for Python 2. The downside of this option is that it may include multiple bugs that we have fixed during this year.
3. Create a conda environment with Python 3 and Spyder 4.1.4, and another environment with Python 2 with conda installation and install in this second environment spyder-kernels with pip, which we explain in the second part of the following video https://www.youtube.com/watch?v=Ul79ihg41Rs&t

If you want to continue using Python 2 in your code, the last option is the more viable alternative, even though the first one is pretty usefull but remember that we are not fixing Spyder 3 bugs anymore. 

I will highly recommend you to start migrating your code to Python 3 because since December of the last year there's no more support for Python 2 and a lot of projects are not longer providing code so it will be even harder to continue working on Python 2 as time pass by.

Please let me know if this helps you and thanks reporting!

**Comment by larajan67** [comment]
Hi @steff456,
Thanks for the quick response and advice! The last option (3) was only one that did get Spyder working. When I tried to create a new environment with either Spyder 3.3.6 or 4.0.1 it still would not launch and just crash. 

My concern now is pip installation of my required python modules are not all working and I am not sure if that is due to working in Python 2.7 or not. I found conda installation had worked previously. I realize this is a separate issue. 
I understand the need to move to Python 3. The code I am using does not have the flexibility to move to Python 3 as far as I can tell due to limitations of the ArcGIS python module-'arcpy' staying static with Python 2 with my institution's ArcGIS 10. ArcGIS Pro (most updated version) moved to Python 3, but I do not have the capacity to get ArcGIS Pro. If anyone knows otherwise about 'arcpy' please let me know.

**Comment by ccordoba12** [comment]
@larajan67, could you give us a step by setp description of the modules you need to install in Python 2? Perhaps we could help you to solve the issues you're having.

**Comment by larajan67** [comment]
@ccordoba12 Thanks for the offer-the 3 main modules (which have many dependencies) are georasters, geopandas and rasterios.  I was actually able to install them via 'pipwin' and pip. I think I had to pull from specific wheels is my guess. However, now that I am trying to import the packages in Spyder, errors keep popping up -'restarting kernel' and then:
[SpyderKernelApp] WARNING | No such comm: b3c77a8adb6b11ea9a35f8b156a1475f
[SpyderKernelApp] WARNING | No such comm: fb40163ddb6b11ea8179f8b156a1475f

Is this because it is unstable environment? I got warning messages when I switched the python interpreter as @steff456 instructed. I apologize that my issues keep changing. If this is an issue that has appeared in another thread please let me know.
Thank you-

**Comment by steff456** [comment]
Hi @larajan67,
I had a hard time trying to replicate your issue but I could make it work. So I have my development environment in python 3.8, also I created another environment in python 2.7 where I installed the three packages that you mention with spyder-kernels which I found to be the tricky part. So, this is the step-by-step commands that I used and worked without having that error in the IPython console. 

```
conda create -n py2 python=2.7
conda activate py2
conda install -c conda-forge geopandas
```

The last command will install the three packages `georasters, rasterio, geopandas`

```
pip install spyder-kernels
```
Afterwards I opened a Spyder and connected the kernel with the executable of the environment `py2`. I could load a sample dataset and see it on the variable explorer.

![image](https://user-images.githubusercontent.com/20992645/90075636-836e5180-dcc3-11ea-817d-f2bd544006b3.png)

Hope you can work with your code as well and please let me know if these instructions helped in any further way

**Comment by larajan67** [comment]
Hi @steff456 ,
I apologize for the delayed response. I am in talks with the code developer to get the code updated in Python 3, which is great news.
I did try your code and it did load all the packages and set up the environment. Yet Spyder still had the same issue as it did before with repeatedly 'restarting kernels' and no code is running.  I did notice when I ran the pip install of spyder-kernels that there was an error message about python 2 being an issue:
ERROR: spyder-kernels 1.9.3 has requirement ipykernel>=5.1.3; python_version > "2", but you'll have ipykernel 4.10.1 which is incompatible.

Could this be the issue and do I need to install an earlier version of spyder-kernels or install spyder-kernels in another environment (ie not py2)?
Thanks for your help

**Comment by steff456** [comment]
I'm glad to know that the migration of the code is in progress! 

> I did try your code and it did load all the packages and set up the environment. Yet Spyder still had the same issue as it did before with repeatedly 'restarting kernels' and no code is running. I did notice when I ran the pip install of spyder-kernels that there was an error message about python 2 being an issue:
ERROR: spyder-kernels 1.9.3 has requirement ipykernel>=5.1.3; python_version > "2", but you'll have ipykernel 4.10.1 which is incompatible.

In my py2 environment I have the same dependencies that you report of spyder-kernels and ipykernel. I believe I had the same error when I installed, but when I run Spyder I don't have the same behavior that you have. Did you install any further package or have a special configuration in your Spyder?

> Could this be the issue and do I need to install an earlier version of spyder-kernels or install spyder-kernels in another environment (ie not py2)?

You need to have spyder-kernels installed in order to connect to that python executable and get a working terminal inside Spyder.

**Comment by steff456** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!

**Comment by Zenobio-L** [comment]
> Hi @larajan67,
> I had a hard time trying to replicate your issue but I could make it work. So I have my development environment in python 3.8, also I created another environment in python 2.7 where I installed the three packages that you mention with spyder-kernels which I found to be the tricky part. So, this is the step-by-step commands that I used and worked without having that error in the IPython console.
> 
> ```
> conda create -n py2 python=2.7
> conda activate py2
> conda install -c conda-forge geopandas
> ```
> 
> The last command will install the three packages `georasters, rasterio, geopandas`
> 
> ```
> pip install spyder-kernels
> ```
> 
> Afterwards I opened a Spyder and connected the kernel with the executable of the environment `py2`. I could load a sample dataset and see it on the variable explorer.
> 
> ![image](https://user-images.githubusercontent.com/20992645/90075636-836e5180-dcc3-11ea-817d-f2bd544006b3.png)
> 
> Hope you can work with your code as well and please let me know if these instructions helped in any further way

Hi steff!

I've followed your step-by-step solution posted back in Aug2020. The Anaconda prompt at the end gave me this message: 

"ERROR: spyder-kernels 1.10.0 has requirement ipykernel>=5.1.3; python_version > "2", but you'll have ipykernel 4.10.1 which is incompatible."

does that mean Spyder no longer supports python 2.x now?

Thanks in advanced.

**Comment by asanganuwan** [comment]
Found a workaround to use Spyder on python 2.7.
1. setup two virtual environments for Python 2.7 and 3.6.
2. Launce anaconda navigator and install spyder 3.3.6 on both the environments
3. Launch spyder on the environment with Python 3.6
4. Preferences-->Python Interpreter --> set the Python path for 2.7
5. Restart Spyder
Done!

**Comment by mlondono74** [comment]
> Found a workaround to use Spyder on python 2.7.
> 
> 1. setup two virtual environments for Python 2.7 and 3.6.
> 2. Launce anaconda navigator and install spyder 3.3.6 on both the environments
> 3. Launch spyder on the environment with Python 3.6
> 4. Preferences-->Python Interpreter --> set the Python path for 2.7
> 5. Restart Spyder
>    Done!


 I tried this and got the following error:

Traceback (most recent call last):
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\runpy.py", line 174, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\runpy.py", line 72, in _run_code
exec code in run_globals
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\spyder_kernels\console\start.py", line 297, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\ipykernel\connect.py", line 18, in 
import jupyter_client
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\jupyter_client\connect.py", line 24, in 
import zmq
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\zmq\__init__.py", line 47, in 
from zmq import backend
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Mateo\anaconda3\envs\irbc27\lib\site‑packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
