### ISSUE TITLE
"Run in current namespace" missing in Spyder 5.0.0a1

### ISSUE THREAD

**Issue by Dollarius** [spyder-ide/spyder#13524]
The Spyder Run options are missing from the latest version of the software.
In particular, it is not possible to set the option for running scripts in "console's current namespace instead of an empty one", as described here: https://github.com/spyder-ide/spyder/pull/10032

Is there a workaround for setting "current_namespace=True" to all runfile calls?
I need to define variables on-the-fly and use them while running script files.

Thank you for your help.

**Comment by ccordoba12** [comment]
@goanpeca, please take a look at this one.

**Comment by ccordoba12** [comment]
> Is there a workaround for setting "current_namespace=True" to all runfile calls?

Sorry, there isn't.

> I need to define variables on-the-fly and use them while running script files.

Please go back to 4.1.4. 5.0.0a1 is still very alpha and has several issues we need to fix.
