### ISSUE TITLE
kernel problem 

### ISSUE THREAD

**Issue by Emmanuel11111** [spyder-ide/spyder#13522]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2545, in path_manager_callback
    plugin.dockwidget.remove_title_bar()
  File "C:\Users\user\Anaconda3\lib\site-packages\spyder\widgets\pathmanager.py", line 41, in __init__
    assert isinstance(path, (tuple, None))
TypeError: WARNING:traitlets:kernel died: 18.000995635986328
isinstance() arg 2 must be a type or tuple of types

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  None (NOK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by dalthviz** [comment]
Hi @Emmanuel11111 could you try to update to one of our latest releases (Spyder 3.3.6 in the case of Spyde 3 or Spyder 4.1.4 in the case of Spyder 4)? 

If you want to keep using the Spyder 3.x you can run from an Anaconda Prompt something like `conda install spyder=3.3.6`. In case you want to checkout Spyder 4.x you can run from an Anaconda Prompt something like `conda install spyder=4.1.4`

Let us know if after doing the update the error keeps raising and please give us the steps you followed to trigger the error :)

**Comment by dalthviz** [comment]
Since no reply was done I'm closing this one. Feel free to reopen if the issue persist and you have more info in order to replicate it.
