### ISSUE TITLE
Exception when i try to get a variables type (note exception comes when i write type)

### ISSUE THREAD

**Issue by efo42** [spyder-ide/spyder#13525]
### What steps will reproduce the problem?

Python 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.2.0 -- An enhanced Interactive Python.

a = 1

[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\ander\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\ander\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\ander\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\ander\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 604, in inspect_request
    content.get('detail_level', 0),
  File "C:\Users\ander\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 423, in do_inspect
    detail_level=detail_level
  File "C:\Users\ander\AppData\Roaming\Python\Python37\site-packages\IPython\core\interactiveshell.py", line 1765, in object_inspect_mime
    detail_level=detail_level
  File "C:\Users\ander\AppData\Roaming\Python\Python37\site-packages\IPython\core\oinspect.py", line 600, in _get_info
    info = self._info(obj, oname=oname, info=info, detail_level=detail_level)
  File "C:\Users\ander\AppData\Roaming\Python\Python37\site-packages\IPython\core\oinspect.py", line 863, in _info
    names = [sub.__name__ for sub in obj.__subclasses__()]
TypeError: descriptor '__subclasses__' of 'type' object needs an argument

type(a)
Out[2]: int

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.2.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.0.2 (OK)
numpy >=1.7                    :  1.17.0 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

# Spyder plugins:
spyder_notebook                :  0.3.0 (OK)
spyder_terminal                :  0.4.1 (OK)
spyder_unittest                :  0.4.1 (OK)
```

**Comment by efo42** [comment]
It's after i have assigned the value to variable "a" that I start to write "type(a)" and then the exception occurs.

**Comment by ccordoba12** [comment]
Hey @efo42, thanks for reporting. It seems you installed some packages with pip, which is causing this issue. To fix it, please remove this directory

    C:\Users\ander\AppData\Roaming\Python\

and try again.

**Comment by efo42** [comment]
Hi thanks for the answer and that fixed the problem

Best Regards
Anders

**Comment by ccordoba12** [comment]
Great to know! Happy Spydering @efo42!
