### ISSUE TITLE
Spyder 4.1.4 ERROR: execution aborted

### ISSUE THREAD

**Issue by ammarkaust** [spyder-ide/spyder#13530]
### Issue Report Checklist

* [ x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x ] Tried basic troubleshooting (if a bug/error)
    * [ x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I re-installed Anaconda again yesterday as it had stopped working properly. It worked fine after the re-install yesterday though matplotlib.pyplot had some issues while plotting: it was slow. Today I started having serious issues.

Issue: After an exception, the IPython console stops processing any command and instead gives ERROR: execution aborted. 

Attempted Solutions:

Close current console and open new console. The new console suffers from the same issue that it gives ERROR: execution aborted after any exception

Updating Anaconda and Spyder: Everything updated as new installation

Re-installing Anaconda: Re-installed anaconda again to day. Unfortunately did not fix the problem.

A similar issue was reported [here](https://github.com/spyder-ide/spyder/issues/13453). Unfortunately, no fix was provided and the issue closed.

### What steps reproduce the problem?

1. Any exception is raised.
2. 
3. 

### What is the expected output? What do you see instead?
The expected out put for 1 would be 1. Instead I see  ERROR: execution aborted
![Untitled](https://user-images.githubusercontent.com/41770085/90202461-2092cc80-de21-11ea-838a-7a4cf019dce0.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.4
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

**Comment by ccordoba12** [comment]
Please update to ipykernel **5.3.4** and try again.

**Comment by ammarkaust** [comment]
> 
> 
> Please update to ipykernel **5.3.4** and try again.

Thanks ccordoba. I have done a complete uninstallation of Anaconda and then re-installed again. It seems to be working now. I will keep your solution in mind if this problem comes back.

Also a small thing, how do I check the checkboxes when submitting an issue? If you look at my submission I just put x there lol

**Comment by ccordoba12** [comment]
> It seems to be working now

Great to now. Closing this one then.

> Also a small thing, how do I check the checkboxes when submitting an issue? If you look at my submission I just put x there lol

You need to avoid leaving spaces around them, like this: `[x]`
