### ISSUE TITLE
Run configuration per file dialog doesn't display complete

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#13531]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Run configuration per file dialog is too tall for my screen and I can't scroll down to see the complete information on it.

![Screen Shot 2020-08-14 at 1 20 45 AM](https://user-images.githubusercontent.com/18587879/90219854-96b91400-ddcc-11ea-919e-4ab1c1dc5815.png)

I suggest fixing the max height of the dialog to the height of the Spyder's window and adding a scroll bar when it's not fully displayed. 

(It might be a MacOS problem)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.4
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS Catalina 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by juanis2112** [comment]
@steff456 can you take a look at this one?

**Comment by ccordoba12** [comment]
Thanks @juanis2112 for reporting this. Could you let us know what's your screen size?

Also, I think we should discuss this with Isabella in our next meeting. I don't know if adding a scrollbar is the best option in this case and I'm not sure how to reduce the dialog's height.

What do you think @juanis2112 and @steff456?
