### ISSUE TITLE
Pandas Series index wrong in Variable Explorer

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#13544]
## Problem Description

When viewing a Series in the variable explorer, sorting the series or the index does not change the index displayed

### What steps reproduce the problem?

1. Double Click a Pandas Series in the Variable Explorer to Open the floating pane
2. Sort the series either up or down on values, or up or down on index
3. Index does not change

### What is the expected output? What do you see instead?

Expected output--index order will change when the series is sorted in various ways.

Actual output:
![image](https://user-images.githubusercontent.com/30508983/90320804-632bd600-df01-11ea-8f72-bad0be03d4ab.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

NONE

```

## Versions

Spyder 4.1.4  
Python 3.7.6 64-bit  
Qt 5.9.6  
PyQt5 5.9.2  
Windows 10  

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.7 (OK)
pygments >=2.0                 :  2.5.2 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.6.1 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.3.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.13 (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.17.4 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

# Spyder plugins:
spyder_terminal                :  0.3.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @eafpres, thanks for reporting. I think this an important bug and we'll try to fix it in our next release.

**Comment by eafpres** [comment]
The problem exists in Pandas Series and Pandas DataFrames in the same form.
The problem does not exist for lists.
There is a variant of the problem for NumPy arrays--they don't sort at all.
Here is a reproducible example:

`
\# -*- coding: utf-8 -*-
"""
Created on Sun Aug 16 12:00:16 2020

@author: Blaine Bateman (eafpres)
"""
\#
\#%% libraries
\#
import pandas as pd
import numpy as np
\#
\#%% create data
\#
my_series = pd.Series(np.random.sample(1000))
my_list = list(np.random.random_integers(0, 1000, 1000))
my_dataframe = pd.DataFrame({'reals' : my_series,
                             'ints' : my_list})
my_array_1D = np.array(my_series)
my_array_2D = np.array(my_dataframe)
\#
\# now for each object:
\#  open Variable explorer
\#  click on the column or index headins
\#  list sorts data and index correctly
\#  Pandas Series and Pandas DataFrame do not sort index correctly
\#  NumPy objects do not sort at all
\#
`

**Comment by Ecarulan** [comment]
Do you know what is the latest version that does not have this issue?

**Comment by eafpres** [comment]
> Do you know what is the latest version that does not have this issue?

In 4.1.2, Pandas Series and DataFrames sort correctly.
In 4.1.2, NumPy objects don't sort at all (as in 4.1.4)
In 4.1.2, Python Lists sort erratically:

![image](https://user-images.githubusercontent.com/30508983/90551777-14737b80-e14f-11ea-9bc5-e47ad04b45d0.png)

In the above, the list is 1000 element long. Sorting on the index should put 999 or 0 at the top.   
Scrolling down in the list and sorting produces different results depending on the location:
![image](https://user-images.githubusercontent.com/30508983/90552069-821fa780-e14f-11ea-84dd-9d596647eec5.png)

**Comment by eafpres** [comment]
@ccordoba12 The entire spyder team ROCKS with support!  Thank you!

**Comment by ccordoba12** [comment]
Thanks for your kind words @eafpres!

**Comment by Ceballosk** [comment]
What about the bagground color?
