### ISSUE TITLE
Spyder requesting PySide but unable to install the module.

### ISSUE THREAD

**Issue by luismglvieira** [spyder-ide/spyder#13553]
Hey, recently Spyder stopped working and I tested this issue in two different Manjaro installations. From what I understand, Spyder requests a module named PySide, but this one isn't available with the most recent Python version (atm is 3.8), so it won't install at all.

So I tried to install PySide2, and it did install, but Spyder is still requesting PySide, so it won't start.

I don't understand how there's no one else with this same issue tho.

This is the console output when I try to run Spyder:
`Traceback (most recent call last):
  File "/home/~/.local/lib/python3.8/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
**ModuleNotFoundError: No module named 'PySide'**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in <module>
    start.main()
  File "/usr/lib/python3.8/site-packages/spyder/app/start.py", line 200, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 53, in <module>
    requirements.check_qt()
  File "/usr/lib/python3.8/site-packages/spyder/requirements.py", line 41, in check_qt
    import qtpy
  File "/home/~/.local/lib/python3.8/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
`

And this is the output when I run "pip install PySide"

`    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mbomvpq0/pyside/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mbomvpq0/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-i518bqx5
         cwd: /tmp/pip-install-mbomvpq0/pyside/
    Complete output (1 lines):
    **only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]**
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by ccordoba12** [comment]
Hey @luismglvieira, thanks for reporting. Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
