### ISSUE TITLE
Spyder Won't Launch post machine reboot, clean install, etc

### ISSUE THREAD

**Issue by BrotherKoW** [spyder-ide/spyder#13563]
### Issue Report Checklist

* [ done] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [done ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ done] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [done ] Tried basic troubleshooting (if a bug/error)
    * [ done] Restarted Spyder
    * [ done] Reset preferences with ``spyder --reset``
    * [ done] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ done] Tried the other applicable steps from the Troubleshooting Guide
* [ done] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After power outage, Spyder will not boot via anaconda console, shortcut, or navigator.
I have tried steps offered on other tickets. I have also uninstalled Anaconda, removed all leftover folders having to do with anaconda/spyder/python, removed registry entries, restarted machine, installed Anaconda (latest version), rebooted machine again. Spyder will still not launch. A clean install on a different machine does work.

### What is the expected output? What do you see instead?
Expect Spyder to launch. It does not launch, offers no error messages in anaconda terminal. There is no hanging process.

### Paste Traceback/Error Below (if applicable)
From Windows Event Viewer:
Faulting application name: python.exe, version: 3.8.3150.1013, time stamp: 0x5efe0bf7
Faulting module name: atig6txx.dll, version: 21.19.128.15, time stamp: 0x57f447ff
Exception code: 0xc0000005
Fault offset: 0x000000000000d22e
Faulting process id: 0x1d88
Faulting application start time: 0x01d67583c96f12e9
Faulting application path: C:\Users\mike\Anaconda3\python.exe
Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\c0308740.inf_amd64_3987e247e98b52d7\atig6txx.dll
Report Id: 089e6d55-b652-41c8-8d3b-0dbd06d15011
Faulting package full name: 
Faulting package-relative application ID: 
Fault bucket 1863156689323284158, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: python.exe
P2: 3.8.3150.1013
P3: 5efe0bf7
P4: atig6txx.dll
P5: 21.19.128.15
P6: 57f447ff
P7: c0000005
P8: 000000000000d22e
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCC2D.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDB4.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDC5.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDD3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERCDE3.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_python.exe_c5ed44d980ea531c9b14e0fd4c94558a617ed4f1_98e5facc_56acd44a-91a7-4e2e-8343-4371a0f3bf8e

Analysis symbol: 
Rechecking for solution: 0
Report Id: 089e6d55-b652-41c8-8d3b-0dbd06d15011
Report Status: 268435456
Hashed bucket: 945ebced8cda89d7c9db43233401d6be
Cab Guid: 0

```python-traceback

I have attempted to launch start.py via batch file and get following output:
C:\Users\mike\Anaconda3\Lib\site-packages\spyder\app>C:\Users\mike\Anaconda3\python.exe start.py
_cffi_ext.c
C:\Users\mike\Anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(266): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "start.py", line 22, in <module>
    import zmq
  File "C:\Users\mike\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\mike\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\mike\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\mike\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\mike\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\mike\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.

_However I do not believe this is relevant. Running the same batch file on the machine with working install yields the same output, despite it being a working install._



```

## Versions

* Spyder version: 4.1.4
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro Version 1903

**Comment by steff456** [comment]
Hi @BrotherKoW,

Did you install a particular package in your environment or are you trying to start Spyder from a clean one? If not please create a new environment and install only spyder to see if it works with the following commands,

```
conda create -n test-env
conda activate test-env
conda install spyder=4.1.4
```

Please let me know if this works

**Comment by BrotherKoW** [comment]
Thanks @steff456 
I'm trying to start spyder from a clean one. But I followed your instructions, created activated a test environment and installed only conda into it. Spyder will not launch from the test env. I get only the following output:
(test-env) C:\Users\mike>spyder
(test-env) C:\Users\mike>

**Comment by ccordoba12** [comment]
> Faulting module path: C:\WINDOWS\System32\DriverStore\FileRepository\c0308740.inf_amd64_3987e247e98b52d7\atig6txx.dll

This seems to indicate a problem with your graphics card. Please update the drivers for it and try again.

**Comment by BrotherKoW** [comment]
Driver update did not work....switcfhing out the graphics card did. I will put more faith in the event viewer next time. Thanks for the help.

**Comment by ccordoba12** [comment]
No problem. Glad you were able to solve your problem!
