### ISSUE TITLE
Spyder crashes with Segmentation fault: 11 when Mac goes to sleep

### ISSUE THREAD

**Issue by laurajanem** [spyder-ide/spyder#13570]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

Hello - I've seen some similar issues like, but nothing that exactly fits what I'm experiencing.

## Problem Description
spyder crashes when computer goes to sleep. Error message is `segmentation fault: 11`

### What steps reproduce the problem?
1. Launch spyder from terminal
`spyder3`
2. Everything is fine all day as I'm using it. 
3. Close laptop, computer goes to sleep.
4. Come back the next day, spyder has crashed, with the message `Segmentation fault: 11` in the terminal.
5. This happens every day

### What is the expected output? What do you see instead?
I expect it not to happen

### Paste Traceback/Error Below (if applicable)

```python-traceback

Since spyder has crashed, there are no logs to copy.

```

## Versions

* Spyder version: 4.1.4
* Python version: 3.7.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: MacOS Catalina 10.15.6

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.19.0 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @laurajanem thanks for the feedback! Maybe this is related with the Qt/PyQt version that you are using but I'm unsure :/, what do you think @ccordoba12 ? I checked and seems like in the wiki some info exist to [debug segfaults](https://github.com/spyder-ide/spyder/wiki/How-to-debug-PyQt-PySide-internal-crashes-(segfaults)-affecting-Spyder) although it seems kind of outdated. Also, maybe @steff456 or @juanis2112 could help here.

**Comment by steff456** [comment]
@dalthviz it seems that there may be a problem with Qt as seen in https://github.com/spyder-ide/spyder/issues/3732 
@laurajanem did you install python apart from the conda installation?

**Comment by laurajanem** [comment]
I did use the `pip` install because we don't use `conda` for our virt environments where I work. Is there a specific version of Qt that is known to work with Catalina + Spyder 4?

**Comment by dalthviz** [comment]
Thanks @steff456 for the info :+1:

@laurajanem could you try creating an env using PyQt 5.9.2 and Qt 5.9.7 ? Let us know if that helps :)

**Comment by laurajanem** [comment]
aaahh when I downgraded to PyQt 5.9.2 all of a sudden my menu bar was not responsive - this menu bar:

<img width="814" alt="Screen Shot 2020-08-19 at 4 06 40 PM" src="https://user-images.githubusercontent.com/17499453/90687760-5c6fcc80-e23b-11ea-9af1-ad071be05ec0.png">

spyder launched fine, and the rest of the UI worked, just not the top menu menu bar.

**Comment by ccordoba12** [comment]
> aaahh when I downgraded to PyQt 5.9.2 all of a sudden my menu bar was not responsive - this menu bar:

You need to use `pythow` to start Spyder in order to avoid that. I think that's not the default interpreter used when Spyder is installed with pip, but it certainly is the one used by Anaconda.

**Comment by ccordoba12** [comment]
> Uninstalled/reinstalled and now it works again, but I'm back at the updated versions.

So you'd said your problem is fixed now?

**Comment by laurajanem** [comment]
Yes, the problem with the menu bar being unresponsive is fixed. But I don't think the original issue will be fixed - If downgrading the version of PyQt is the solution, since it seems to cause another problem. 
Is there another, maybe later version of PyQT5 that has known compatibility with Catalina? I'm assuming this is somehow OS related, given some other similar issues raised here.

Also - I have another Mac laptop running Mojave that does not have this problem.

**Comment by ccordoba12** [comment]
> Is there another, maybe later version of PyQT5 that has known compatibility with Catalina? I'm assuming this is somehow OS related, given some other similar issues raised here.

Not right now, but we'll try to update our requirements to support PyQt 5.15 for our 4.2 version, to be released in two months.

> Also - I have another Mac laptop running Mojave that does not have this problem.

This is very weird.

**Comment by ccordoba12** [comment]
@laurajanem, since there's nothing else we can do at the moment and you're unable to use Anaconda (which is our recommended installation method), is it ok if we close this issue?

**Comment by laurajanem** [comment]
Sure, that's fine.
