### ISSUE TITLE
Jedi and parso dependencies requirements met, but error still found

### ISSUE THREAD

**Issue by mindyKornfeld** [spyder-ide/spyder#13571]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I open spyder, I receive the following error:
You have missing dependencies! 
![image](https://user-images.githubusercontent.com/52978328/90654781-c0c86700-e20e-11ea-9408-aa922dc066ff.png)

### What steps reproduce the problem?
I updated spyder as well as running pip install jedi and pip install parso.
In addition, I opened Help --> Dependencies to see what version I had installed

### What is the expected output? What do you see instead?
As I expected, I have jedi and parso installed to the latest versions. However, the required version of the dependency is less than that. For example - jedi requires 0.15.2 and parso requires 0.5.2. I have more updated versions installed. These are the only dependencies that do not have the >= sign

## Versions

* Spyder version: 4.1.3
* Python version: 3.7.4 64-bit
* Qt version: 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.15.2                   :  0.17.1 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.7.0 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.3 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
![Annotation 2020-08-19 112323](https://user-images.githubusercontent.com/52978328/90654494-70e9a000-e20e-11ea-88f6-e1c656bf1dee.png)

**Comment by ccordoba12** [comment]
Hey @mindyKornfeld, thanks for reporting. You said

> I updated spyder as well as running pip install jedi and pip install parso.

This is really bad because it looks like you're using Anaconda and yet you updated those packages with pip. Unfortunately, that that could have broken your installation.

Please [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to fix that. And let us know if it works for you.

**Comment by mindyKornfeld** [comment]
Thanks for your help! The video was very clear and informative

**Comment by ccordoba12** [comment]
I'm glad you were able to solve your problem with it!
