### ISSUE TITLE
Plain text in help pane has a bug

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#13585]
## Problem Description
When I open spyder, go to the help pane and in the hamburger menu I activate the option `Plain Text` if the source is in the console I will see,

![image](https://user-images.githubusercontent.com/20992645/90807962-e4f67780-e2e4-11ea-8161-fcf08a75b90b.png)

If the source is editor I will see the pane empty.

Then if I write in a file in the editor `import numpy as np` and `Ctrl+I`, the pane will show me 
![image](https://user-images.githubusercontent.com/20992645/90808080-17a07000-e2e5-11ea-83e1-5df13707dc1e.png)

### What is the expected output? What do you see instead?
Remove the `No further documentation available` from the actual documentation shown in the plain text option of the help pane

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one. It shouldn't be that hard to fix.
