### ISSUE TITLE
conflict with Wing pro 7

### ISSUE THREAD

**Issue by Wusir2018** [spyder-ide/spyder#13581]
Hello everyone,
There are conflict with Wing pro 7 when I install Spyder-4.1.4 in my envs. My `numpy`, `pandas` and `PyQt5` will broken. If I use Wing pro 7 and Spyder-4.1.4 in different envs, it's OK. How can use them in the same envs?
Could you help me? 
Best wishes!

**Comment by andfoy** [comment]
Hi @Wusir2018, thanks for opening this issue. Could you please add a detailed description about how you did install Spyder and also the dependencies used?

**Comment by ccordoba12** [comment]
@Wusir2018, as I told you before, if some of the packages you need are not available in conda, you need to install them using pip. However, you need to install Spyder on that environment, only the packages you need to run your code, and then connect that environment to Spyder.

Please see part 2 of  [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that.

**Comment by Wusir2018** [comment]
@ccordoba12  Thank you for your reply, it helps me a lot. Thank you very much!
Best wishes! 👍
