### ISSUE TITLE
Plot DataFrames from the Variable Explorer context menu

### ISSUE THREAD

**Issue by Naikless** [spyder-ide/spyder#13583]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Feature request for being able to plot pandas Dataframes (or Series) via right-click "plot", as it is already possible for lists and numpy arrays. This has been requested [over at SO some time ago](https://stackoverflow.com/questions/45876533/in-spyder-is-there-some-way-to-plot-a-dataframe-by-right-clicking-it-like-you-c), but I still couldn't find an issue related to it. Would be a very nice feature. Maybe even more valuable in combination with [this feature request](https://github.com/spyder-ide/spyder/issues/4303).

**Comment by jitseniesen** [comment]
Discussion about this has started in issue #21025 so I am closing this issue (even though it was opened earlier) to keep everything centralized.
