### ISSUE TITLE
Editor sluggish in cycles coocurring with audible increased disk usage

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder#13595]
### potentially related issues:
#13020 
#13041 

## Problem Description

Writing in the editor is slow, but the slowing occurs in cycles - the speed is ok for a while but then is slow (and then ok again).
This is visible even in cursor movement. Pressing left key and keeping it pressed leads to cursor running normally, then experiencing major jumps and hiccups, and then again it runs normally (and so on it repeats).
The slowing happens approximmately when I hear intensified disk work (Spyder may be saving or reading something). The disk work also happens in cycles, even if I am not typing anything in the editor: the increased disk usage can be heard every 2-3 seconds for about 1 second. The disk sound goes away when I close Spyder, or don't use it for a while. It usually starts a few seconds after I switch to Spyder (for example to check its version just now) and still lasts for about 4-5 cycles after I move the focus somewhere else.

I updated Spyder not so long ago (to `4.1.4`), but the sluggish editor problem started only recently (about 1-2 days ago). One thing that I did recently may be related to this issue:
The project I am working on has its directory on Dropbox. Because of this I get many Spyder temp files written there (#13041). I've recently moved these files to a separate directory to later see if they contain something useful. Maybe the disk work is somehow related to this?
I have also turned on many linting options recently - but after experiencing the slowdown I turned them all off and this did not help so I doubt this is related, although it happend in similar time window.

## Versions
* Spyder version: `4.1.4`
* Python version: `3.7.3`
* Qt version: `5.9.7`
* PyQt version: `5.9.2`
* Operating System name/version: Windows 10 Home, version 1909, build 18363.1016

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.0 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.12 (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.2.3 (OK)
```

**Comment by mmagnuski** [comment]
The same problem returned just now although I did not delete anything from Dropbox.

**Comment by mmagnuski** [comment]
I have reset Spyder again, but the next day the problem returned.

**Comment by ccordoba12** [comment]
We're fixing several things to improve performance in the editor for our next version (4.2.0), to be released at the beginning of November.

I hope your problem will be fixed in that version.

**Comment by mmagnuski** [comment]
Great, thanks @ccordoba12, I will check it out as soon as it is released!

**Comment by mmagnuski** [comment]
I think it is safe to assume this has been fixed. I haven't had this issue in a long time.
