### ISSUE TITLE
Anaconda 2020.07 Matplotlib not updating

### ISSUE THREAD

**Issue by addarnr** [spyder-ide/spyder#13597]
I just updated my Anaconda (to 2020.07) and Spyder (to 4.1.4)installations. However, the Matplotlib package shows up as version 3.3.0 using pip list and 3.2.2 using conda list commands. Which is correct? Also, how can I install the latest version of Matplotlib package? I followed the following to update my Anaconda and Spyder with the hope that it will upgrade all packages including Matplotlib,

conda install conda        
conda install anaconda        
conda install spyder

Thanks!

**Comment by CAM-Gerlach** [comment]
Hey @addarnr , I see some `pip`-installed packages in your `base` environment that should generally be avoided if possible, but nothing that looks too obviously problematic. However, I was unable to reproduce `pip list` reporting a different Matplotlib version while following our recommended install procedure on my Windows machine, and I suspect you may have another Matplotlib version installed via `pip`, either in the User Site Packages directory or elsewhere via the Anaconda installed `pip`, or from a previous Python install somewhere on your machine.

To get to the bottom of this, could you provide the output of the following commands?

In Spyder's IPython console, run:
* `import sys; sys.executable` 
* `import matplotlib; matplotlib.__path__; matplotlib.__file__; matplotlib.__version__`
* `import sysconfig; sysconfig.get_paths()`
* `import site; site._script()`

In Anaconda prompt, run:
* `where python`
* `python -c "import sys; print(sys.executable)"`
* `echo %PYTHONPATH%`
* `python -m site`
* `python -c "import sysconfig; print(sysconfig.get_paths())"`
* `conda info`
* `pip show matplotlib`

Thanks!

**Comment by apesquita** [comment]
Hello all,

I seem to be encountering the same issue as @addarnr 

```
import matplotlib as mpl
print('matplotlib version:', mpl.__version__)
```
**matplotlib version: 3.3.2**


I tried the update matplotlib with:
 conda update matplotlib
But the version remains the same (3.3.2)

@CAM-Gerlach 
Here is the requested trouble-shooting info. Thank you do much for having a look at this.

In Spyder's IPython console:

- import sys; sys.executable

Out[2]: '/home/pesquita/anaconda3/bin/python'

- import matplotlib; matplotlib.__path__; matplotlib.__file__; matplotlib.__version__

Out[3]: '3.3.2'

- import sysconfig; sysconfig.get_paths()

Out[4]: 
{'stdlib': '/home/pesquita/anaconda3/lib/python3.7',
 'platstdlib': '/home/pesquita/anaconda3/lib/python3.7',
 'purelib': '/home/pesquita/anaconda3/lib/python3.7/site-packages',
 'platlib': '/home/pesquita/anaconda3/lib/python3.7/site-packages',


> import site; site._script()

sys.path = [
    '/home/pesquita',
    '/home/pesquita/anaconda3/lib/python37.zip',
    '/home/pesquita/anaconda3/lib/python3.7',
    '/home/pesquita/anaconda3/lib/python3.7/lib-dynload',
    '',
    '/home/pesquita/anaconda3/lib/python3.7/site-packages',
    '/home/pesquita/anaconda3/lib/python3.7/site-packages/IPython/extensions',
    '/home/pesquita/.ipython',
]
USER_BASE: '/home/pesquita/.local' (exists)
USER_SITE: '/home/pesquita/.local/lib/python3.7/site-packages' (doesn't exist)
ENABLE_USER_SITE: True
An exception has occurred, use %tb to see the full traceback.

SystemExit: 0

/home/pesquita/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
 'include': '/home/pesquita/anaconda3/include/python3.7m',
 'platinclude': '/home/pesquita/anaconda3/include/python3.7m',
 'scripts': '/home/pesquita/anaconda3/bin',
 'data': '/home/pesquita/anaconda3'}

**Comment by CAM-Gerlach** [comment]
Thanks @apesquita for all the info, really appreciate it. The key piece I'm missing here is what you're seeing that's not what's expected. The problem the OP was reporting was that the version of Matplotlib version shown when importing it in Spyder and the version shown in `conda list` didn't match, but here, all the output provided reports the same version. 3.3.2, which is the [latest version](https://anaconda.org/anaconda/matplotlib) on the Anaconda defaults channel. Therefore, could you explain what you're expecting to see instead? Thanks.

**Comment by juanis2112** [comment]
Closing due to no response.
