### ISSUE TITLE
Latest version of parso 0.8 crashes Spyder 3.3.1 with python 3.5

### ISSUE THREAD

**Issue by vik748** [spyder-ide/spyder#13605]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Latest version of parso version 0.8.0 causes Spyder 3.3.1 to not start with Python 3.5

### What steps reproduce the problem?
```
conda create -n spyder_test python=3.5 spyder 
conda activate spyder_test
spyder &
```

### What is the expected output? What do you see instead?
Spyder should startup successfully instead it crashes.

### Paste Traceback/Error Below (if applicable)

```python-traceback
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3181, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3057, in run_spyder
    main.setup()
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 896, in setup
    from spyder.plugins.ipythonconsole import IPythonConsole
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 59, in <module>
    from spyder.widgets.ipythonconsole import ClientWidget
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in <module>
    from .debugging import DebuggingWidget
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/debugging.py", line 17, in <module>
    from qtconsole.rich_jupyter_widget import RichJupyterWidget
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/qtconsole/rich_jupyter_widget.py", line 14, in <module>
    from .jupyter_widget import JupyterWidget
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/qtconsole/jupyter_widget.py", line 20, in <module>
    from IPython.lib.lexers import IPythonLexer, IPython3Lexer
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax
```

## Versions

* Spyder version: 3.3.1
* Python version: 3.5.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 16.04
* Parso version: 0.8.0 

## Workaround
Using parso 0.7 works:
```
conda create -n spyder_test python=3.5 spyder parso=0.7
conda activate spyder_test
spyder &
```

**Comment by vik748** [comment]
@absognety I do use the latest Spyder where possible, but there are projects where I have you use Python 3.5 for legacy reasons and the newer Spyder / ipython-kernels doesn't work with those.
It might be work specifying in the dependencies / compatibility for version 3.3.1 to limit parso to less than 0.8.  This way a conda install of Spyder in python 3.5 environment would automatically install appropriate version of parso.

**Comment by absognety** [comment]
@vik748  what feature of parso from 0.8.0 are you trying to work with that is not already there in parso 0.7.0? clearly solving this version incompatibility is a painful as it is clearly stated in changelog, maybe there is some better way of doing your task using another package that is compatible with your requirments?

**Comment by shahvi** [comment]
None. I don't care about parso but looks like Spyder needs it.

**Comment by absognety** [comment]
> ### Issue Report Checklist
> * [x]  Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
> * [] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
> * [x]  Reproduced the issue after updating with `conda update spyder` (or `pip`, if not using Anaconda)
> * [ ]  Could not reproduce inside `jupyter qtconsole` (if console-related)
> * [x]  Tried basic troubleshooting (if a bug/error)
>   
>   * [x]  Restarted Spyder
>   * [x]  Reset preferences with `spyder --reset`
>   * [x]  Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
>   * [x]  Tried the other applicable steps from the Troubleshooting Guide
> * [x]  Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below
> 
> ## Problem Description
> Latest version of parso version 0.8.0 causes Spyder 3.3.1 to not start with Python 3.5
> 
> ### What steps reproduce the problem?
> ```
> conda create -n spyder_test python=3.5 spyder 
> conda activate spyder_test
> spyder &
> ```
> 
> ### What is the expected output? What do you see instead?
> Spyder should startup successfully instead it crashes.
> 
> ### Paste Traceback/Error Below (if applicable)
> ```
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3181, in main
>     mainwindow = run_spyder(app, options, args)
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 3057, in run_spyder
>     main.setup()
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 896, in setup
>     from spyder.plugins.ipythonconsole import IPythonConsole
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 59, in <module>
>     from spyder.widgets.ipythonconsole import ClientWidget
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in <module>
>     from .debugging import DebuggingWidget
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/debugging.py", line 17, in <module>
>     from qtconsole.rich_jupyter_widget import RichJupyterWidget
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/qtconsole/rich_jupyter_widget.py", line 14, in <module>
>     from .jupyter_widget import JupyterWidget
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/qtconsole/jupyter_widget.py", line 20, in <module>
>     from IPython.lib.lexers import IPythonLexer, IPython3Lexer
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
>     from .terminal.embed import embed
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
>     from IPython.terminal.interactiveshell import TerminalInteractiveShell
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
>     from .debugger import TerminalPdb, Pdb
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
>     from IPython.core.completer import IPCompleter
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
>     import jedi
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
>     from jedi.api import Script, Interpreter, set_debug_function, \
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
>     import parso
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
>     from parso.parser import ParserSyntaxError
>   File "/home/vik748/miniconda3/envs/spyder_test/lib/python3.5/site-packages/parso/parser.py", line 113
>     node_map: Dict[str, type] = {}
>             ^
> SyntaxError: invalid syntax
> ```
> 
> ## Versions
> * Spyder version: 3.3.1
> * Python version: 3.5.6
> * Qt version: 5.9.6
> * PyQt version: 5.9.2
> * Operating System name/version: Ubuntu 16.04
> * Parso version: 0.8.0
> 
> ## Workaround
> Using parso 0.7 works:
> 
> ```
> conda create -n spyder_test python=3.5 spyder parso=0.7
> conda activate spyder_test
> spyder &
> ```

Related  issue: https://github.com/spyder-ide/spyder/issues/13476

**Comment by rhkarls** [comment]
@vik748 Isn't the problem here that conda installs parso 0.8 in a 3.5 environment, although 3.5 support was dropped in parso 0.8? So this is a conda issue I think

**Comment by vik748** [comment]
@rhkarls That is a valid point, I will also add an issue in their repo.

**Comment by ccordoba12** [comment]
@vik748, thanks for reporting. @dalthviz will submit a pull request to fix this dependency in Anaconda.

**Comment by ccordoba12** [comment]
This is fixed now.
