### ISSUE TITLE
Auto indentation after parentheses

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#13607]
The current behavior of Spyder's auto indentation, when we hit "Enter" right after typing `(` is like this:
```python
result = function(
    |)
```
("`|`" is where the cursor is)

It seems that PyCharm and VSCode are both using this following style:
```python
result = function(
    |
)
```

If I remember correctly, PyCharm's and VSCode's style is the recommended style in PEP?  Is it possible for you to make a small tweak in Spyder?  Thanks!

**Comment by steff456** [comment]
Hi @jsh9,

Both forms are valid in PEP8, we implemented the first one. If more users request the second form for auto indentation we can see if we can add an option to shift between the two forms.

Thanks for reporting!
