### ISSUE TITLE
Confusion about new variable explorer with dataframes

### ISSUE THREAD

**Issue by lschneidpro** [spyder-ide/spyder#13619]
# Problem Description
Hi there,
I have been using spyder for a while and have been enjoying the variable explorer to check my data frames.
I quickly started a new environment for a project and I am not able to access a table explorer as it was used to be.
Let me know if I am missing anything as I could not find anything in the documentation

Thanks a lot.

![Capture d’écran 2020-08-24 à 16 26 49](https://user-images.githubusercontent.com/40396043/91057481-881df880-e627-11ea-81c9-e507ae2599ee.jpg)

### What steps reproduce the problem?

Reproducible code:

```
import requests
import pandas as pd

r = requests.get('http://corona-api.com/countries/GR')
check = r.json()
check2 = check['data']['timeline']
df = pd.DataFrame(check2)
```

## Versions

* Spyder version: 4.1.4
* Python version:  3.8.5 
* Qt version: 5.9.7 
* PyQt version:  5.9.2 
* Operating System name/version: mac OS 10.15.6

**Comment by steff456** [comment]
Hi @lschneidpro,

Which version of pandas do you have installed in your environment? I couldn't reproduce your error with pandas 1.0.5

**Comment by steff456** [comment]
Please see https://github.com/spyder-ide/spyder/issues/13620 and tell me if you can fix your problem

**Comment by ccordoba12** [comment]
@lschneidpro, also, please consider to install Pandas in the same environment you have Spyder (in case you haven't). That could be the root cause of this problem.

**Comment by lschneidpro** [comment]
ok super weird.

1) I recreated an environment with python 3.6 and spyder 4.1 and it worked.
2) I recreated an environment (as above) with the latest python, latest spyder, latest pandas and it worked.

I guess the thread can be closed :)
