### ISSUE TITLE
spyder quits when replacing text in selection

### ISSUE THREAD

**Issue by bsierieb1** [spyder-ide/spyder#13617]
hi, very often (almost every time) I click on "replace selection", spyder quits. any suggestions on what might be causing the problem?

**Comment by steff456** [comment]
Hi @bsierieb1,

Can you please upload a gif or video where you show us this behavior?

**Comment by steff456** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!
