### ISSUE TITLE
Lag spikes about every 6 seconds if spyder is started.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1362]
_From [mail.t...@gmx.de](https://code.google.com/u/104947229556192903674/) on 2013-04-23T10:36:08Z_

Spyder Version:  2.2.0beta4
Python Version:  2.7.3 (64 Bit)
Qt Version:      4.8.4, PyQt4 (API v2) 4.10 on Windows 

What steps will reproduce the problem?

 1. Starting Spyder What is the expected output? What do you see instead? If Spyder is started, my ping spikes about ever six seconds. 
If Spyder is closed again, not spikes are seen. 

Please provide any additional information below

. I closed all Windows in Spyder and the Issue is still there.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1362_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-23T14:17:16Z_

What do you mean exactly by "my ping spikes"?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-23T14:24:21Z_

**Labels:** Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [mail.t...@gmx.de](https://code.google.com/u/104947229556192903674/) on 2013-04-24T06:51:22Z_

I discovered this behavior while gaming with spyder open,
sometimes the games were almost unplayable due to lag and
it took its time until i found the culprit.

Using ping my_router_ip -n 1000 without spyder, every ping is under 5ms.
With spyder, around every 6 second a packet needs 600-1400 ms.

**Comment by spyder-issues-migrator** [comment]
_From [mail.t...@gmx.de](https://code.google.com/u/104947229556192903674/) on 2013-04-24T09:56:49Z_

Here the ping behavior with spyder:


Microsoft Windows [Version 6.2.9200]
(c) 2012 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Tillsten>ping -n 1000 speedport.ip

Ping wird ausgeführt für speedport.ip [192.168.2.1] mit 32 Bytes Daten:
Antwort von 192.168.2.1: Bytes=32 Zeit=1ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=6ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=8ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=792ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=7ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=1ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=3ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=8ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=5ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=4ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=12ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=833ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=1ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=3ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=9ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=8ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=4ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=7ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=4ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=4ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=872ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=2ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=7ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=5ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=1ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=6ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=5ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=3ms TTL=64
Antwort von 192.168.2.1: Bytes=32 Zeit=3ms TTL=64

Ping-Statistik für 192.168.2.1:
    Pakete: Gesendet = 34, Empfangen = 34, Verloren = 0
    (0% Verlust),
Ca. Zeitangaben in Millisek.:
    Minimum = 1ms, Maximum = 872ms, Mittelwert = 77ms
STRG-C
^C
C:\Users\Tillsten>

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-06T14:28:27Z_

Have you tried sniffing traffic with Wireshark to see if there is something that Spyder or its plugins are trying to reach? In theory Sphinx may include some remote .js libraries and IPython may do some lookups.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:50:40Z_

No idea where this one was coming from, but I hope you've found how to fix it by now.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [mail.t...@gmx.de](https://code.google.com/u/104947229556192903674/) on 2015-01-03T05:00:41Z_

I think it was properly a Qt issue.

**Comment by chrothenbach** [comment]
Has any solution been found for this? I encounter the same issues. When Spyder is running, if I ping a server, my latency goes from 40-50ms to that server to about 3000ms, every 6 seconds or so.  I am running the latest version of Spyder (updated it with Conda) and the issue persists.
