### ISSUE TITLE
Update spyder-kernels subrepo

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#13635]
Is there a reason why the spyder-kernels subrepo has not been updated?
I see that we have an official release of 1.9.3, but it appears that the subrepo in spyder is still 1.9.2.

spyder/external-deps/spyder-kernels/.gitrepo
```
; DO NOT EDIT (unless you know what you are doing)
;
; This subdirectory is a git "subrepo", and this file is maintained by the
; git-subrepo command. See https://github.com/git-commands/git-subrepo#readme
;
[subrepo]
	remote = https://github.com/spyder-ide/spyder-kernels.git
	branch = 1.x
	commit = 1a9d44950edb462188f52cec51c975b80f5f0f6f
	parent = adbc02315db0e49bbaa2cd6dae94526264398fc1
	method = merge
	cmdver = 0.4.1
```
``adbc02`` occurred back on July 6, and ``1a9d44`` is just before the spyder-kernels 1.9.2 tag

**Comment by dalthviz** [comment]
Hi @mrclary thanks for the feedback! yep I think the subrepo should be updated, right @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, it should. We haven't done it yet because there's no significant difference between 1.9.2 and 1.9.3 (1.9.3 only added a new dependency to `setup.py` that was required to run a test on non-conda based systems).

**Comment by ccordoba12** [comment]
@steff456, please take care of this one. The instructions on how to do that are present in our contributing guide.
