### ISSUE TITLE
RuntimeError: Failed to process string with tex because latex could not be found

### ISSUE THREAD

**Issue by shrisant** [spyder-ide/spyder#13630]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by shrisant** [comment]
import pylab
import numpy as np

x = np.linspace(0, 20)
y = np.sin(np.pi/10 * x)
xticks = [0, 10, 20]
xtickslabel = ['$0$', '$\pi$', '$2\pi$']
pylab.plot(x, 2.0 * y, 'r-', label ='Voltage')
pylab.stem(x, y, linefmt ='g--', markerfmt ='gD', label ='Current')
pylab.xlabel("xval", size = 20)
pylab.ylabel("yval", size = 20)
pylab.xticks(xticks, xtickslabel)
pylab.legend(loc = "upper right")
#pylab.ylim(-4.0, 2.5)
pylab.grid()
pylab.show()

This is the code I am writing however i am running the same msg coming in the console:

File "C:\Users\DELL\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 458, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)

  File "C:\Users\DELL\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 338, in make_dvi
    self._run_checked_subprocess(

  File "C:\Users\DELL\Anaconda3\lib\site-packages\matplotlib\texmanager.py", line 308, in _run_checked_subprocess
    raise RuntimeError(

RuntimeError: Failed to process string with tex because latex could not be found

<Figure size 432x288 with 1 Axes>

**Comment by dalthviz** [comment]
Hi @shrisant I think you don't have Latex installed. If you type in your cmd `latex` you get it as a valid command?

Checking a little bit, maybe this could help: https://stackoverflow.com/questions/58121461/runtimeerror-failed-to-process-string-with-tex-because-latex-could-not-be-found

Since seems like this isn't Spyder related I'm closing it but hopefully the info above can help you :)
