### ISSUE TITLE
Spyder upgrade from 3 to 4

### ISSUE THREAD

**Issue by Nilton2018** [spyder-ide/spyder#13646]
### What steps will reproduce the problem?

I have upgraded spyder from 3 to 4 using pip3:

pip3 install --upgrade spyder

It seems that the upgrade has been done. Nevertheless, the icon shows spyder3 yet. In the field 'About' shows 4.1 and when it is openning also indicates 4. When I list the packages instaleed via pip (pip3 list) it shows version 4 too. I think the problem is only the icon but I am not sure and I want to know how to fix it. My email is nbamado@gmail.com 

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.2
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-42-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.7.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.6.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.5.1 (OK)
pygments >=2.0                 :  2.3.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.6.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  1.8.5 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by andfoy** [comment]
Hi @Nilton2018, thanks for reaching out. We don't recommend using pip to install Spyder, we recommend using conda instead. In this case, we recommend you to install spyder on a clean environment, such that there are no package and dependency clashes

**Comment by Nilton2018** [comment]
Do you know what file should I edit and what modification should I do? It
seems that if the proper editions are made, the icon will be proper defined?
Best regards,
Nilton


Em sex., 28 de ago. de 2020 às 15:02, Edgar Andrés Margffoy Tuay <
notifications@github.com> escreveu:

**Comment by ccordoba12** [comment]
We use the spyder3 name when installing with pip to signal that that's a Spyder version that works with Python 3. It has nothing to do with the Spyder version (3 or 4) itself.

It's been like that for a very long time (5 years now, I think) but we plan to change it to just spyder in our 4.2 version, which will only support Python 3 (so there's no ambiguity between the executables for Python 2 and 3).

**Comment by Nilton2018** [comment]
Ok. But i think it is possible to change this configuration myself.
Anyway, thank you for your support.
Best regards,
Nilton


Em dom, 30 de ago de 2020 00:55, Carlos Cordoba <notifications@github.com>
escreveu:
