### ISSUE TITLE
Can't restart kernel after seeing a TensorFlow message

### ISSUE THREAD

**Issue by chrismaliszewski** [spyder-ide/spyder#13644]
## Problem Description
I encountered a major problem with Spyder. I'm not able to restart kernel after seeing any kind of TensorFlow message, i.e.:
_Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2_
_"I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll"_ 
The problem has started to appear after creating a new env in Conda and it has never happened before with the previous versions of Spyder and/or Tensorflow. 

### What steps reproduce the problem?
1. Run below commands in Anaconda command line to have the same env I have:
```
conda create -n cpu python=3.7
activate cpu
conda update --all
conda install spyder
conda install tensorflow
pip install pyfftw
pip install yattag
pip install tqdm
pip install hurry.filesize
pip install matplotlib
pip install Pillow
pip install sklearn
```
2. Run spyder.
```
spyder
```
3. Run the code (I know the method below is deprecated but it's the easiest one I found to replicate the issue and that shows the warning):
```
import tensorflow as tf
tf.test.is_gpu_available()
```
4. Click the hamburger button.
5. Click Restart kernel.
6. Click Yes.

### What is the expected output? What do you see instead?
Expected output: the kernel restarts.
What happens: the kernel stays / it does not restart. The only possible option to restart a kernel is to create a new one or restart Spyder.

### Paste Traceback/Error Below (if applicable)

No internal errors.

## Versions
Spyder 

* Spyder version: 4.1.4
* Python version: 3.7
* Operating System name/version: Windows 10, 10.0.18362

### Dependencies
```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.17.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.3 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by andfoy** [comment]
Hi @chrismaliszewski, thanks for opening this issue. Have you tried to install tensorflow in a separate environment different from the one that Spyder uses? Also, does this issue also happens on a standard python interpreter?

**Comment by chrismaliszewski** [comment]
Hi @andfoy. Not sure how I should do what you wrote. 
1. How can I import a module (TF) if it's not installed in an env with Spyder? 
2. How can I restart a standard python interpreter?

**Comment by ccordoba12** [comment]
> conda create -n cpu python=3.7
activate cpu
conda update --all
conda install spyder
conda install tensorflow
pip install pyfftw
pip install yattag
pip install tqdm
pip install hurry.filesize
pip install matplotlib
pip install Pillow
pip install sklearn

Please install everything (or the  most packages that you can) with conda. Mixing conda and pip usually leads to this kind of odd errors.

**Comment by chrismaliszewski** [comment]
@ccordoba12, it isn't mixing conda and pip. The previous version of an env I had that was working find had the same installation instructions. 

@andfoy, I think I found the reason for the problem. I simply needed to turn warning/logs/info off. I may have done it in the past looong time ago in the env itself so I didn't need to do that in my code and I forgot about this when creating a new env. After running this piece of code:
```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
```
I am now able to restart Kernel any time I want, finally. 

There must be some kind of bug either in Spyder to TF that shuts the restart possibility when a log is displayed.

**Comment by ccordoba12** [comment]
> @ccordoba12, it isn't mixing conda and pip. The previous version of an env I had that was working find had the same installation instructions. 

You're clearly installing some packages with pip and others with conda. It doesn't matter if your previous env was working, that mix always causes strange errors. So please don't report issues with that kind of setup again, in case you want to keep it. 

> I am now able to restart Kernel any time I want, finally. 

That's good to know.

**Comment by chrismaliszewski** [comment]
@ccordoba12, I'm not saying it doesn't cause strange errors just **it isn't the cause of the problem** since everything worked before and a new kind of issue appeared causing the problem.

**Comment by chrismaliszewski** [comment]
> [...] So please don't report issues with that kind of setup again, in case you want to keep it. [...]
It looks like you're threating you'll delete an issue if you don't like it. I'm shocked. In my personal opinion, you shouldn't be involved with the community with your attitude because you may cause more harm/don't help at all instead of helping others. I don't have anything else to say to that...

**Comment by ccordoba12** [comment]
Issues are not deleted. My comment was directed to clarify that we simply can't offer more support if you want to ignore our advice and keep mixing pip and conda packages in the way you're doing it now, even when it's known it causes tons of problems and odd bugs. For instance, the pip and conda Numpy packages are totally incompatible on Windows, so using a conda installed Spyder with a pip Numpy to visualize an array can end up in disaster. 

We know what we're talking about after years of experience dealing with these issues. One of our core developers even spent one month to produce a video about that:

https://m.youtube.com/watch?v=Ul79ihg41Rs

So simply calm down and listen to our advice. But if you don't want to do it, please refrain to request our support in the future.

**Comment by badlammajamma** [comment]
Thank you @ccordoba12 ! I had the same issue as above, and step 3 in the video you linked solved my problem (though I had to subsequently re-install tensorflow in my conda env).

**Comment by js185529** [comment]
So was there ever any solution to this? I have the same issue (conda installed everything). As soon as I import tensorflow, the same issue arises as stated.

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
```

did not work.

**Comment by chrismaliszewski** [comment]
I eventually switched from Spyder to PyCharm. No issues what so ever.

**Comment by ccordoba12** [comment]
@js185529, did you run

```python
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
```

before importing tensorflow?
