### ISSUE TITLE
low resolution problem

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#13649]
does anyone know why the resolution for the font at the bottom bar are so big? tried to reset spyder but they are still lower than what they should be
![image](https://user-images.githubusercontent.com/62394093/91626841-7d919500-e980-11ea-8106-0405c6942b35.png)

**Comment by seyeeet** [comment]
how can I remove the history of spyder completely? maybe that helps. spyder reset did not help with graphic problem

**Comment by juanis2112** [comment]
Hi @seyeeet thanks for reporting this. Can you try enabling auto high DPI scaling to see if that fixes the issue?
![Screen Shot 2020-08-30 at 2 57 00 AM](https://user-images.githubusercontent.com/18587879/91654213-97a8a180-ea6c-11ea-869e-84d0f9352b6d.png)

**Comment by seyeeet** [comment]
@juanis2112 Unfortuanately, it did not help:
![image](https://user-images.githubusercontent.com/62394093/91668503-3a980480-eadb-11ea-8779-e83d89d81d73.png)


Is there a folder that the graphic setting for spyder is saved? maybe I can delete that folder and reinstall it to see if it helps?

**Comment by seyeeet** [comment]
hmmm this also did not help :(
```
locate spyder
/home/sey/anaconda3/bin/spyder
pip uninstall spyder
conda remove spyder
which spyder
sudo rm -rf /home/sey/.config/spyder-py3/
sudo apt install locate && sudo updatedb
locate spyder
conda install spyder=4.1.4
conda update spyder
```

**Comment by ccordoba12** [comment]
> does anyone know why the resolution for the font at the bottom bar are so big?

That's not controlled by Spyder but by the fonts you're using in your operating system. So, if you want to change the font size of our status bar, you need to decrease the font size used by all Ubuntu applications, using its own preferences system. [Here](https://vitux.com/how-to-change-text-size-in-ubuntu/) you can read how to do that.

**Comment by ccordoba12** [comment]
> how can I remove the history of spyder completely? maybe that helps

What do you mean by this?

**Comment by seyeeet** [comment]
@ccordoba12 I dont think that the font of my system is changed at all because all the fonts for other apps or even for the different part of spyder is the same as they used to be. The only inconvenience is the status bar font, as you can see it does not match with the rest.
I installed spyder on a completely similar system and the problem was gone. but for some reason whatever the status bar resolution is bigger than what it should be here.



> > how can I remove the history of spyder completely? maybe that helps
> 
> What do you mean by this?

I meant to remove the kernels for spyder, I did it and reinstall everything but it didnot help neither.

**Comment by ccordoba12** [comment]
> The only inconvenience is the status bar font, as you can see it does not match with the rest.

What do you mean by "the rest" here?

**Comment by seyeeet** [comment]
The folder, the scrips, the stuff in the console.
Everything is normal. but the font of the status bar is ridiculously large.
![image](https://user-images.githubusercontent.com/62394093/91774932-eb73d180-ebb7-11ea-8100-3fc80d4783ee.png)

**Comment by ccordoba12** [comment]
Looks fine to me (on Linux/Kubuntu):

![Selección_083](https://user-images.githubusercontent.com/365293/92069094-291a5b00-ed6e-11ea-9219-79c326cb6dda.png)

> but the font of the status bar is ridiculously large.

That's a matter of opinion (they look a bit large, but fine to me). Since this is highly dependent on people's operating systems and opinions, I think it's a bit too much to try fix this (besides, no one else has complained about it).

@juanis2112, what do you think?

**Comment by seyeeet** [comment]
Sure if you think it is not an issue please close the issue.
Thanks

**Comment by juanis2112** [comment]
I don't really see a way of fixing it without being able to reproduce it @ccordoba12. Did you try decreasing the font size in your OS settings @seyeeet ?
