### ISSUE TITLE
namespace from PYTHONSTARTUP undefined in Editor

### ISSUE THREAD

**Issue by lit-sk-localadmin** [spyder-ide/spyder#13655]
### What steps will reproduce the problem?

I created a simple python script that loads some libraries, for example:

import our_stuff.library1 as liba
import our_stuff.library2 as libb
import their_stuff as libc
import narsort
import numpy as np

and set-up environment variable PYTHONSTARTUP that is pointing to it.

("our_stuff", "their_stuff" is defined in the python path).

It is more about loading the "our_stuff" libraries than numpy, I simply wanted to keep all the loading in one place and make it available to all the new users, straight after python/spyder starts up.

Spyder console recognizes the namespaces, that is: when I type liba and pres dot and Tab, I see the suggestions with what is available inside liba. For example, I would see that the function liba.print_hello_world() exists. This part is fine, then.

However, when I open the editor and load a .py script in which I would also call the same function, next to the liba.print_hello_world() I see "undefined name 'liba'".

This means that the console knows the "liba," the editor doesn't. Is that an expected beavior?

It would be great if you explained how to handle this or what I am doing wrong.

Thanks,
Bartosz

Python: 3.8.3
IPython: 7.16.1
Spyder: 4.1.4 (issue seen also in spyder 3.3.6)

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-101-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by steff456** [comment]
Hi @lit-sk-localadmin,

I believe that in our completions engine we are not sending the environment variable and that's why you are getting those errors. We will work on adding this feature to our next release.

Thanks for reporting!

**Comment by steff456** [comment]
@andfoy please take a look at this one

**Comment by lit-sk-localadmin** [comment]
Hi Stephannie, thanks for looking into that. I hope my comment is useful and that it will make into a nice feature of spyder!
Thanks,Bartosz

**Comment by ccordoba12** [comment]
I'm sorry but PYTHONSTARTUP is only used to configure the Python interpreter at startup, according to the [Python docs](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP):

>  PYTHONSTARTUP
    If this is the name of a readable file, the Python commands in that file are executed before the first prompt is displayed in interactive mode. The file is executed in the same namespace where interactive commands are executed so that objects defined or imported in it can be used without qualification in the interactive session.

Therefore, passing that env var to our code completion machinery won't have any effect.

To do what you want in a proper way, you can use a Spyder project with `our_stuff` included on it. Or you can create a Python package for `our_stuff` and install it in with `pip`.

Please try those options and let us know if they work for you.

**Comment by lit-sk-localadmin** [comment]
Hi Carlos, OK, then it seems it is indeed the expected behavior. I was simply a little confused since I saw the namespace being known in the console (and there the code completion is working).
The proper ways you are suggesting are indeed the better ways of approaching the problem.
I think you can consider the issue solved and please close it.
Thanks,
Bartosz

**Comment by ccordoba12** [comment]
Great! I'm glad you consider my suggestions useful for your use case.
