### ISSUE TITLE
Plots pane issues and details

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#13659]
- [ ] Thumbnails scrollbar by default appears too big and plot size too small:
<details>

#### Master
![image](https://user-images.githubusercontent.com/16781833/91754350-e189a880-eb8e-11ea-8662-f017ee99d876.png)

#### 4.x
![image](https://user-images.githubusercontent.com/16781833/91754414-f9612c80-eb8e-11ea-8c40-0a542b22ee41.png)

</details>

- [ ] Shortcuts Toolbar:
    - [ ] Save all plots (Cmd+alt+S) not showing on tooltip and not working
    - [ ] Remove plot (Cmd+W) not showing on tooltip and not working
    - [ ] Remove all plots (Cmd+Shift+W) not showing on tooltip and not working
    - [ ] Previous plot/Next plot (Arrows) WORKING but not showing on tooltip
    - [ ] Zoom in/Zoom out (cmd+/-) not showing on tooltip and not working

- [ ] Tooltips names:
    - [ ] Save plot as (master) v.s. Save plot as… (4x)
    - [ ] Save all plots (master) v.s. Save all plots…(4x)
    - [ ] Copy plot to clipboard as image (master) v.s Copy image (4x)

- [ ] Context menu:
    - [ ] `Remove plot` in the context menu is not showing the shortcut (Cmd + W)

Example code used for the plot:

<details>

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 20 00:38:09 2020
​
@author: juanis
"""
import numpy as np
import matplotlib.pyplot as plt
​
# example data
x = np.arange(0.1, 4, 0.1)
y1 = np.exp(-1.0 * x)
y2 = np.exp(-0.5 * x)
​
# example variable error bar values
y1err = 0.1 + 0.1 * np.sqrt(x)
y2err = 0.1 + 0.1 * np.sqrt(x/2)
​
​
# Now switch to a more OO interface to exercise more features.
fig, (ax_l, ax_c) = plt.subplots(nrows=1, ncols=2,
                                       sharex=True, figsize=(12, 6))
​
ax_l.set_title('all errorbars')
ax_l.errorbar(x, y1, yerr=y1err)
ax_l.errorbar(x, y2, yerr=y2err)
​
ax_c.set_title('only every 6th errorbar')
ax_c.errorbar(x, y1, yerr=y1err, errorevery=6)
ax_c.errorbar(x, y2, yerr=y2err, errorevery=6)
​
​
fig.suptitle('Errorbar subsampling for better appearance')
plt.show()
```

</details>

**Comment by dalthviz** [comment]
@goanpeca could you look into this please? Thanks!

**Comment by goanpeca** [comment]
Thanks for the feedback @dalthviz, will work on the fixes.
