### ISSUE TITLE
Internal console inserts unwanted background highlighting on left parenthesis

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#13666]
## Problem Description

If I type left parenthesis on the internal console, then close it and press backspace, the console remains with a green background.

![imagen](https://user-images.githubusercontent.com/1878982/91772338-51595c80-ebaa-11ea-9602-c2404086f958.png)

### What steps reproduce the problem?

1. Type left parenthesis <kbd>(</kbd>
2. Type right parenthesis <kbd>)</kbd>
3. Press Backspace

### What is the expected output? What do you see instead?
The console should not have any highlighting after closing the parenthesis

**Comment by ccordoba12** [comment]
Thanks @andfoy for reporting! I verified this was fixed as part of my work in PR #13281.
