### ISSUE TITLE
Maximum entries in History pane is not working

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#13663]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If I change the number of maximum entries in the history pane it doesn't do anything.

![image35](https://user-images.githubusercontent.com/20992645/91770870-9a5be180-eba7-11ea-93d1-d1a2a2a4dab0.png)

### What steps reproduce the problem?

1. Write more than 10 commands in the IPython console 
2. Open the history pane and go to the hamburger menu and select the maximum entries
3. Change to 10 -> nothing happens

### What is the expected output? What do you see instead?
Change dynamically the number of lines shown by the history on the plugin

**Comment by ccordoba12** [comment]
This no longer applies because that option was removed in 4.2.1.
