### ISSUE TITLE
Internal console inserts unwanted red highlighting on background

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#13668]
## Problem Description
When inserting multiple backspaces on an unclosed parenthesis and then closing it, the internal console remains with an unwanted red background. 

![imagen](https://user-images.githubusercontent.com/1878982/91772636-e3616500-ebaa-11ea-9865-256d40a0e7c6.png)

### What steps reproduce the problem?

1. Insert left parenthesis <kbd>(</kbd>
2. Insert multiple backspaces
3. Insert right parenthesis <kbd>)</kbd>

### What is the expected output? What do you see instead?
The internal console should not highlight the background in red color

**Comment by ccordoba12** [comment]
Thanks @andfoy for reporting! I verified this was fixed as part of my work in PR #13281.
