### ISSUE TITLE
spyder problem

### ISSUE THREAD

**Issue by zhang-chao-zhi** [spyder-ide/spyder#13678]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Program Files (x86)\anaconda\lib\site-packages\spyder\plugins\editor.py", line 1711, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "D:\Program Files (x86)\anaconda\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\.spyder-py3\\template.py'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.5
* Qt Versions: 5.9.4, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.19.0 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)

```

**Comment by steff456** [comment]
Hi @zhang-chao-zhi,

It seems there's something wrong with the installation of Spyder, I will recommend to you to upgrade to our latest Spyder version 4.1.4 with the following commands,

```
conda update anaconda
conda install spyder=4.1.4
```

Please try it and let me know if that fixes your error

**Comment by steff456** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!
