### ISSUE TITLE
Spyder failed to start because no Qt platform plugin could be initialized.

### ISSUE THREAD

**Issue by corymasterman** [spyder-ide/spyder#13687]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Anaconda Navigator and Spyder fail to start. I've uninstalled and reinstalled as well as updating conda and all associated plugins but still encounter the issue. 

### What steps reproduce the problem?

1. Download Anaconda
2. Open Anaconda Navigator
3. 

### What is the expected output? What do you see instead?

The program should start

### Paste Traceback/Error Below (if applicable)

```python-traceback

qt.qpa.plugin: Could not load the Qt platform plugin "windows" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: direct2d, minimal, offscreen, windows.

```

## Versions

* Spyder version: 4.1.4
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

PASTE DEPENDENCIES HERE
![AnacondaError](https://user-images.githubusercontent.com/46691630/91907013-b37b9580-ec6e-11ea-8f3e-b2a8eb4a16d4.PNG)
![AnacondaError2](https://user-images.githubusercontent.com/46691630/91907017-b6768600-ec6e-11ea-8459-c9e3c5c7cc5e.PNG)

**Comment by steff456** [comment]
Hi @corymasterman,

If you open your terminal and type `spyder` do you see the same error?

**Comment by corymasterman** [comment]
@steff456 If I try opening in the terminal, neither are recognized. I get the following error "'spyder' is not recognized as an internal or external command, operable program or batch file."

**Comment by ccordoba12** [comment]
Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to understand how to solve this issue. It has a lot of detailed and careful instructions that can help you to get Spyder back to life again.

You can also check our [this page](http://docs.spyder-ide.org/current/emergency-cpr.html) in our documentation for that.

**Comment by corymasterman** [comment]
@ccordoba12 I followed the steps in the video as well as the documentation page but still receive errors.

When creating a new environment for spyder, upon the "conda install -y spyder" command, these error lines pop up 
"Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source."

In the documentation page, I am unable to run "python start.py", I get an error or "ImportError: DLL load failed while importing error: The specified module could not be found."

When trying to open anaconda-navigator afterwards, I still get the same error of "qtpy.PythonQtError: No Qt bindings could be found"

**Comment by steff456** [comment]
@corymasterman, can you re-install anaconda, please make sure to completely uninstall the current version you have and tell us if the error persists

**Comment by corymasterman** [comment]
I uninstalled and removed all related folders in the AppData folder. I get the same error after re-installing.

**Comment by steff456** [comment]
Did you clear as well all the environment variables before installing?

**Comment by corymasterman** [comment]
Yes, still getting the error "qtpy.PythonQtError: No Qt bindings could be found" when trying to open anaconda-navigator from the Anaconda prompt.

**Comment by steff456** [comment]
And if you add conda to the path and type `conda` in your terminal does it exists?

**Comment by corymasterman** [comment]
Yes, conda is recognized in the terminal. I think the problem is coming from the pyqt package. I am unable to install it and the pyqt package is what contains pyside which is the main error that I get when trying to open anaconda-navigator.

**Comment by corymasterman** [comment]
So I found the root of the problem. I did not have the most current version of Microsoft Visual C++ installed on my machine, the latest version I had was from 2013. Once I downloaded the most current version of Microsoft Visual C++, I was able to reinstall and everything seems to be functioning normally.

**Comment by ManPython** [comment]
Does Spyder still using QT GUI as base framework? If not this then what is here used??

**Comment by dalthviz** [comment]
Hi @ManPython Spyder uses PyQt5. Currently Spyder supports PyQt <=5.16 . You can check the contraint that Spyder has for PyQt in the `setup.py` file at: https://github.com/spyder-ide/spyder/blob/dc90e8fa1bb0559846f0e01639e6e43a59c385bc/setup.py#L230

**Comment by corymasterman** [comment]
Please remove me from this thread.On Mar 4, 2023, at 9:01 PM, Daniel Althviz Moré ***@***.***> wrote:﻿
Hi @ManPython Spyder uses PyQt5. Currently Spyder supports PyQt <=5.16 . You can check the contraint that Spyder has for PyQt in the setup.py file at: https://github.com/spyder-ide/spyder/blob/dc90e8fa1bb0559846f0e01639e6e43a59c385bc/setup.py#L230

**Comment by ccordoba12** [comment]
@corymasterman, you need to do it yourself by clicking on the `Unsubscribe` button to the right.
