### ISSUE TITLE
After upgrading to 4.1.5, code completion and syntax inspection are invalid

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#13696]
## Problem Description
After upgrading to 4.1.5, code completion and linting are invalid.
Restart spyder or LSP，the problem still exists.

The status of the LSP in the status bar is "down", and the following pop-up box appears.
![2FFADC47-2AC2-492c-8ADF-C3BB98A7FB63](https://user-images.githubusercontent.com/1759365/92061695-82fc3e80-edc9-11ea-8ec9-d9760112e922.png)

### What steps reproduce the problem?

1. conda update spyder
2. Start spyder
3. Restart spyder or LSP

## Versions

* Spyder version: 4.1.5
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: win10

**Comment by leavor** [comment]
After uninstalling spyder, reinstall, the problem is solved.Use the following command:

conda uninstall spyder
conda install spyder=4.1.5

**Comment by ccordoba12** [comment]
Glad you find how to solve this problem.
