### ISSUE TITLE
not able to update!!!!

### ISSUE THREAD

**Issue by akkiteja** [spyder-ide/spyder#13702]
I am not able to update spyder!!!

**Comment by andfoy** [comment]
Hi @akkiteja, could you please provide more information about the error that you are getting?

**Comment by luismiguells** [comment]
I have the same problem. I'm using Anaconda Navigator in macOS and when I use the the command ```conda update spyder```  it tells me:

```
Updating spyder is constricted by 

anaconda -> requires spyder==4.1.4=py38_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done

# All requested packages already installed.
```

**Comment by ccordoba12** [comment]
@akkiteja, @luismiguells, please open the Anaconda prompt and run there

    conda update anaconda
    conda update spyder

That should work.

**Comment by luismiguells** [comment]
@ccordoba12 there is not Anaconda prompt in macOS.

**Comment by ccordoba12** [comment]
Then ue `Terminal.app`.

**Comment by akkiteja** [comment]
Thanks. Can I invite any of you members to my organization?????

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by akkiteja** [comment]
K

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by PrinceBlueberry** [comment]
I believe I am having a similar issue.  When I run the commands you suggested, I am told:
```
>conda update anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: done
# All requested packages already installed.
```
Then
```
>conda update spyder
Collecting package metadata (current_repodata.json): done
Solving environment: |
Updating spyder is constricted by
anaconda -> requires spyder==3.3.6=py37_0
If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>
done
# All requested packages already installed.
```
FYI:
```
>conda --version
conda 4.8.4
```
On Windows 10.

**Comment by ccordoba12** [comment]
@PrinceBlueberry, please run

    conda install spyder=4.1.5

to see if it works for you.

**Comment by PrinceBlueberry** [comment]
@ccordoba12 after about 30 minutes of run time (and thousands of debug lines), `conda install spyder=4.1.5` decided:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:
```
and then listed a bunch of things like `python-dateutil -> python[version='>=3.8,<3.9.0a0']`.  I'm assuming that means the version of python that I have insalled (v3.7) is not compatible with Spyder v4+?

By the way, one of the debug messages was:
```
If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```
So if someone did want conda to update python along with Spyder, then how would they "explicitly specify that"?

**Comment by ccordoba12** [comment]
It seems you'd need to reinstall Anaconda to avoid that issue. If you don't want to do that, then you need to install Spyder in a different environment.

For that, please use this command:

    conda create -n spyder-4 spyder=4.1.5 python=3.7

**Comment by luismiguells** [comment]
> @PrinceBlueberry, please run
> 
> ```
> conda install spyder=4.1.5
> ```
> 
> to see if it works for you.

I use the command in the ```Terminal.app``` in macOS 10.15.6 and it doesn't update, throws me the following:
![Captura de Pantalla 2020-09-04 a la(s) 12 07 02](https://user-images.githubusercontent.com/25065697/92268035-4a329700-eea7-11ea-8b0e-9e917311d16f.png)

**Comment by ccordoba12** [comment]
@luismiguells, It hasn't finished. Please wait for it to finish.

**Comment by luismiguells** [comment]
After using the command ```conda install spyder=4.1.5``` suggested by @ccordoba12, Spyder is updated. The problem is that when I use  ```conda update --all``` command  it downgraded the version. I atttach the picture.
![Captura de Pantalla 2020-09-04 a la(s) 12 44 05](https://user-images.githubusercontent.com/25065697/92270987-a6e48080-eeac-11ea-84da-9736dcf1fc84.png)

**Comment by ccordoba12** [comment]
Then don't use that command (it's really not recommended).

**Comment by akkiteja** [comment]
hi
