### ISSUE TITLE
Cannot use Python interpreter in hidden/dot folder (selection menu doesn't display dot folders)

### ISSUE THREAD

**Issue by everetr** [spyder-ide/spyder#13706]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] ~~Could not reproduce inside ``jupyter qtconsole`` (if console-related)~~
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``~~
    * [ ] ~~Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)~~
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I want to select a Python interpreter inside a "hidden" folder (`~/.cache/pypoetry/`). The interpreter selection menu doesn't display hidden/dot folders.

### What steps reproduce the problem?

1. open Spyder
1. go to Tools > Preferences > Python interpreter
1. select "Use the following Python interpreter"
1. click the "Select file" button
1. Notice there are no folder names beginning with a period

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5 64-bit
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Kubuntu 18.04.5

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
This doesn't depend on Spyder but on the open dialog used in your operating system. In KDE you can simply do right-mouse click on that dialog to show your hide files:

![Selección_095](https://user-images.githubusercontent.com/365293/92425488-0bbe0600-f14d-11ea-97f0-f4410f0dd0ad.png)

Please try that and let us know if it works for you.

**Comment by everetr** [comment]
Works. Sorry about that. I've only ever used Ctrl+H.
