### ISSUE TITLE
Numbers on sidebar gone, unable to add lines

### ISSUE THREAD

**Issue by Captain-Squiggles** [spyder-ide/spyder#13716]
### What steps will reproduce the problem?

I was using spyder on a laptop that was connected to a dock, then i removed the laptop from the dock and now spyder is unusable, the numbers on the left side are gone and i cannot add lines by pressing enter. I have tried resettig spyder to factory settings and reinstalling, but nothing fixes it. this message appears on anaconda when i launch spyder:  
DirectWrite: CreateFontFaceFromHDC() failed (Unspecified error) for QFontDef(Family="DejaVu Sans Mono", pointsize=10, pixelsize=13, styleHint=5, weight=75, stretch=100, hintingPreference=0) LOGFONT("DejaVu Sans Mono", lfWidth=0, lfHeight=-13) dpi=96
QWindowsFontEngine::QWindowsFontEngine: GetTextMetrics failed (The operation completed successfully.)

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by juanis2112** [comment]
Hi @Captain-Squiggles. Thanks for opening this issue. I'm not sure what's causing this issue, but here are some things you can try (in order):

* Try ``conda update qt pyqt qtconsole spyder spyder-kernels qtpy sip`` at the Anaconda prompt
* Update your OS and GPU drivers
* Install PyOpenGL with ``conda install pyopengl``
* Try starting Spyder in different opengl modes, with ``spyder --opengl=software``; ``spyder --opengl=desktop`` and ``spyder --opengl=gles``
* If you have multiple GPU  (e.g. Nvidia discrete and Intel integrated, common in higher end laptops), or have another you can use, try disabling/forcing one or the other
* If you haven't already, create a new, clean conda environment, and see if the problem still persists:
~~~bash
conda create -n spyder-env -c defaults spyder
conda activate spyder-env
spyder
~~~
* If this doesn't work, try creating another new environment with `-c conda-forge` instead of `-c defaults`, to see if Qt 5.12 don't have the issue.

Let me know if any of this helps and if not, we will continue looking for a solution.

**Comment by Captain-Squiggles** [comment]
Thank you for answering @juanis2112 !
I tried all the suggestions you gave, but nothing seems to fix the issue :/
I tried to manually delete all related files that i could find and reinstall anaconda, but the problem still appears.
![image](https://user-images.githubusercontent.com/70731237/92485392-2ba40700-f1eb-11ea-8d83-20fe90ef761f.png)

**Comment by CAM-Gerlach** [comment]
Hey @Captain-Squiggles , really sorry you're still experiencing this issue; I'm honestly baffled as to what could be causing this. The error messages certainly seem related as the problem appears to be something with font rendering, but they mostly seem to trace back to specific versions of Qt, developer errors or other problems that don't seem directly related to yours.

The fact that it started suddenly after a display/system configuration change and persists even after a reinstall and settings reset indicates to me that there might be either some state not managed by Spyder (font caches, Qt temp files, etc) that is causing it, or some other non-Anaconda packages installed on your machine that may be causing it, but I'm really not sure.

After racking my brain, here are some more things to try:

* Change the fonts used by Spyder under `Preferences > Appearance > Fonts` and see if they make any difference; also try changing the options under the `Main interface` section
* Under the `View` menu, try `Lock panes and toolbars`, as well as `Fullscreen mode` and `Spyder Default Layout` & `Reset to Spyder default` under the Window Layouts submenu
* Try updating QtAwesome with `conda update qtawesome`
* Use an application like CCleaner to remove your temporary files, old prefetch data and window size/location cache and follow this procedure to remove the font cache: https://help.extensis.com/hc/en-us/articles/360008494153-How-to-rebuild-the-Font-Cache-in-Windows-Universal-Type-Client-6
* Run 
If this still doesn't work, I can scour over your config and debug info to see if I can find any clues to this mystery. Please paste the output of the following commands run in Anaconda prompt inside code blocks, like so:

~~~
```
COMMAND OUTPUT HERE
```
~~~

* `where python`
* `python -c "import sys; print(sys.executable)"`
* `python -m site`
* `conda info`
* `conda list` in your normal Spyder env (probably `base`, the default) and in the new environments you created in the last two steps above

**Comment by CAM-Gerlach** [comment]
Hey @Captain-Squiggles , really sorry you're still experiencing this issue; I'm honestly baffled as to what could be causing this. The error messages certainly seem related as the problem appears to be something with font rendering, but they mostly seem to trace back to specific versions of Qt, developer errors or other problems that don't seem directly related to yours.

The fact that it started suddenly after a display/system configuration change and persists even after a reinstall and settings reset indicates to me that there might be either some state not managed by Spyder (font caches, Qt temp files, etc) that is causing it, or some other non-Anaconda packages installed on your machine that may be causing it, but I'm really not sure.

After racking my brain, here are some more things to try:

* Change the fonts used by Spyder under `Preferences > Appearance > Fonts` and see if they make any difference; also try changing the options under the `Main interface` section
* Under the `View` menu, try `Lock panes and toolbars`, as well as `Fullscreen mode` and `Spyder Default Layout` & `Reset to Spyder default` under the Window Layouts submenu
* Try updating QtAwesome with `conda update qtawesome`
* Use an application like CCleaner to remove your temporary files, old prefetch data and window size/location cache and follow this procedure to remove the font cache: https://help.extensis.com/hc/en-us/articles/360008494153-How-to-rebuild-the-Font-Cache-in-Windows-Universal-Type-Client-6
* Try downgrading to Qt 5.6 by running `conda install qt=5.6 pyqt=5.6` in the environment you created in the second to last step you followed previously
* Move or remove the directory listed in the output of `python -m site --user-site` in Anaconda prompt, if anything is there (you may need to show invisible files or type/paste the path manually)
* Run `conda clean --all --yes`, then follow the procedure specified under Option 2 (then proceed with Option 1 as indicated) on the [Anaconda uninstall page](https://docs.anaconda.com/anaconda/install/uninstall/) (the page appears to be down right now for some reason), and finally manually manually remove any remaining contents of the Anaconda directory (listed under `base environment` in the output of `conda info`; make sure to run **before** uninstalling), and reinstall Anaconda once more

If this still doesn't work, I can scour over your config and debug info to see if I can find any clues to this mystery. Please paste the output of the following commands run in Anaconda prompt inside code blocks, like so:

~~~
```
COMMAND OUTPUT HERE
```
~~~

* `where python`
* `python -c "import sys; print(sys.executable)"`
* `python -m site`
* `conda info`
* `conda list` in your normal Spyder env (probably `base`, the default) and in the new environments you created in the last two steps above

Also, please attach the output file produced by `dxdiag` (type it in the Start menu or any command prompt, and click `Save all information`). Thanks!

**Comment by Captain-Squiggles** [comment]
Wow, such a simple solution!
Changing the font did in fact solve the issue! (for some reason?) :smile:
Thank you for putting so much thought and time into my issue, i highly appreciate it.
[DxDiag.txt](https://github.com/spyder-ide/spyder/files/5317608/DxDiag.txt)

**Comment by CAM-Gerlach** [comment]
Great, thanks! So glad it worked :smile: 

Seems like something got stuck with the font chosen for the application that made things stop working, and even a Spyder settings reset didn't fix it (since it was lower level in Qt or the OS).

My pleasure to help, and happy Spydering!
