### ISSUE TITLE
IPython console freezes sometimes

### ISSUE THREAD

**Issue by matkaa94** [spyder-ide/spyder#13732]
Hello everyone,

since I know there are some related issues with freezing console, mine is somehow different.

## Problem Description
The console freezes only at some specific commands. I am writing a tensorflow-based program on it and have some problems, due to installing different version of tf. However I tried for example to uninstall tensorflow and it doesnt do anything.

pip uninstall tensorflow
other commands with pip uninstall work (e.g. pip uninstall tensorflow-tensorboard)

also this command lets the console freeze: !tensorboard --logdir=models

### What is the expected output? What do you see instead?
I should at least get someting as output, but its not doing anything. CTRL+C stops the process, but i am curios why this happens only to these commands (also some other but these are the ones i am dealing right now with)

## Versions
here my versions in conda list:

<details>
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
absl-py                   0.9.0                    pypi_0    pypi
alabaster                 0.7.12                     py_0
anaconda                  custom                   py38_1
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.9.12                   py38_0
anaconda-project          0.8.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38he774522_1
asn1crypto                1.4.0                      py_0
astroid                   2.4.2                    py38_0
astropy                   4.0.1.post1      py38he774522_1
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                      py_0
attrs                     20.1.0                     py_0
autopep8                  1.5.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.shutil_get_terminal_size 1.0.0                    py38_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bazel                     0.0.0.20200723           pypi_0    pypi
bcrypt                    3.2.0            py38he774522_0
beautifulsoup4            4.9.1                    py38_0
bitarray                  1.5.3            py38he774522_0
bkcharts                  0.2                      py38_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.20.0               h7bd577a_0
bokeh                     2.2.1                    py38_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38h2a96729_1
brotlipy                  0.7.0           py38he774522_1000
bzip2                     1.0.8                he774522_0
ca-certificates           2020.7.22                     0
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py38_0
cffi                      1.14.2           py38h7a1dbc1_0
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.6.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.3                      py_0
comtypes                  1.1.7                 py38_1001
conda                     4.8.4                    py38_0
conda-build               3.18.11                  py38_1
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py38h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              3.1              py38h7a1dbc1_0
curl                      7.71.1               h2a8f88b_1
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38ha925a31_0
cytoolz                   0.10.1           py38he774522_0
dask                      2.25.0                     py_0
dask-core                 2.25.0                     py_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
distributed               2.25.0                   py38_0
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
fastcache                 1.1.0            py38he774522_0
filelock                  3.0.12                     py_0
finta                     1.0                      pypi_0    pypi
flake8                    3.8.3                      py_0
flask                     1.1.2                      py_0
flatbuffers               1.12                     pypi_0    pypi
freetype                  2.10.2               hd328e21_0
fsspec                    0.8.0                      py_0
future                    0.18.2                   py38_1
gast                      0.3.3                    pypi_0    pypi
get_terminal_size         1.0.0                h38e98db_0
gevent                    20.6.2           py38he774522_0
glob2                     0.7                        py_0
gmpy2                     2.0.8            py38h7edee0f_3
google-auth               1.20.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  0.4.16           py38he774522_0
grpcio                    1.31.0                   pypi_0    pypi
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0
iniconfig                 1.0.1                      py_0
intel-openmp              2020.2                      254
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.18.1           py38h5ca1d4c_0
ipython_genutils          0.2.0                    py38_0
ipywidgets                7.5.1                      py_0
isort                     5.4.2                    py38_0
itsdangerous              1.1.0                      py_0
jdcal                     1.4.1                      py_0
jedi                      0.17.1                   py38_0
jinja2                    2.11.2                     py_0
joblib                    0.16.0                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py38_0
jupyter                   1.0.0                    py38_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.6.3                    py38_0
jupyterlab                2.2.6                      py_0
jupyterlab_server         1.2.0                      py_0
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   21.4.0                   py38_0
kiwisolver                1.2.0            py38h74a9793_0
krb5                      1.18.2               hc04afaa_0
lazy-object-proxy         1.4.3            py38he774522_0
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.1               h2a8f88b_1
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libxml2                   2.9.10               h464c3ec_1
libxslt                   1.1.34               he774522_0
llvmlite                  0.33.0           py38ha925a31_0
locket                    0.2.0                    py38_1
lxml                      4.5.2            py38h1350720_0
lz4-c                     1.9.2                h62dcd97_1
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.1                         0
matplotlib-base           3.3.1            py38hba9282a_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.1.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.2                      py_0
more-itertools            8.5.0                      py_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.1.0                    py38_0
msgpack-python            1.0.0            py38h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
navigator-updater         0.2.1                    py38_0
nbconvert                 5.6.1                    py38_0
nbformat                  5.0.7                      py_0
networkx                  2.5                        py_0
nltk                      3.5                        py_0
nnfs                      0.5.0                    pypi_0    pypi
nose                      1.3.7                    py38_2
notebook                  6.1.1                    py38_0
numba                     0.50.1           py38h47e9c7a_0
numexpr                   2.7.1            py38h25d0782_0
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
numpydoc                  1.1.0                      py_0
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0
openpyxl                  3.0.5                      py_0
openssl                   1.1.1g               he774522_1
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0
pandas                    1.1.1            py38ha925a31_0
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py38_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      15.0.0                   py38_0
path.py                   12.5.0                        0
pathlib2                  2.3.5                    py38_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py38_0
pep8                      1.7.1                    py38_0
pexpect                   4.8.0                    py38_0
pickleshare               0.7.5                 py38_1000
pillow                    7.2.0            py38hcc1f983_0
pip                       20.2.2                   py38_0
pkginfo                   1.5.0.1                  py38_0
pluggy                    0.13.1                   py38_0
ply                       3.11                     py38_0
poloniex                  0.0.17                   pypi_0    pypi
powershell_shortcut       0.0.1                         3
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.7                      py_0
prompt_toolkit            3.0.7                         0
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.2            py38he774522_0
py                        1.9.0                      py_0
py-lief                   0.10.1           py38ha925a31_0
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py38he774522_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.5         py38h7a1dbc1_0
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pylint                    2.6.0                    py38_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py38ha925a31_4
pyreadline                2.1                      py38_1
pyrsistent                0.16.0           py38he774522_0
pysocks                   1.7.1                    py38_0
pytables                  3.6.1            py38ha5be198_0
pytest                    6.0.1                    py38_0
python                    3.8.3                he1778fa_2
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py38_0
python-libarchive-c       2.9                        py_0
pytz                      2020.1                     py_0
pywavelets                1.1.1            py38he774522_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.3.1            py38he774522_1
pyzmq                     19.0.1           py38ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.6                      py_0
qtpy                      1.9.0                      py_0
regex                     2020.7.14        py38he774522_0
requests                  2.24.0                     py_0
requests-oauthlib         1.3.0                    pypi_0    pypi
rope                      0.17.0                     py_0
rsa                       4.6                      pypi_0    pypi
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.87          py38he774522_1
scikit-image              0.16.2           py38h47e9c7a_0
scikit-learn              0.23.2           py38h47e9c7a_0
scipy                     1.4.1                    pypi_0    pypi
seaborn                   0.10.1                     py_0
send2trash                1.5.0                    py38_0
setuptools                49.6.0                   py38_0
simplegeneric             0.8.1                    py38_2
singledispatch            3.4.0.3                  py38_0
sip                       4.19.13          py38ha925a31_0
six                       1.15.0                     py_0
snappy                    1.1.8                h33f27b4_0
snowballstemmer           2.0.0                      py_0
sortedcollections         1.2.1                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.2.1                      py_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
sphinxcontrib-websupport  1.2.4                      py_0
spyder                    4.1.5                    py38_0
spyder-kernels            1.9.4                    py38_0
sqlalchemy                1.3.19           py38he774522_0
sqlite                    3.33.0               h2a8f88b_0
statsmodels               0.11.1           py38he774522_0
sympy                     1.6.2                    py38_0
tbb                       2020.2               h74a9793_0
tblib                     1.7.0                      py_0
telebot                   0.0.3                    pypi_0    pypi
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
tensorflow-gpu            2.3.0                    pypi_0    pypi
tensorflow-gpu-estimator  2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3                    py38_0
testpath                  0.4.4                      py_0
tf-estimator-nightly      2.4.0.dev2020081801          pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
toolz                     0.10.0                     py_0
tornado                   6.0.4            py38he774522_1
tqdm                      4.48.2                     py_0
traitlets                 4.3.3                    py38_0
typing_extensions         3.7.4.3                    py_0
ujson                     1.35             py38he774522_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py38_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1                      py_0
wheel                     0.35.1                     py_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0                    py38_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.11.2           py38he774522_0
xlrd                      1.2.0                      py_0
xlsxwriter                1.3.3                      py_0
xlwings                   0.20.5                   py38_0
xlwt                      1.3.0                    py38_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zict                      2.0.0                      py_0
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.4                      py38_0
zope.interface            5.1.0            py38he774522_0
zstd                      1.4.5                h04227a9_0

### Dependencies

PASTE DEPENDENCIES HERE

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
</details>

Can anybody help me? I am searching for almost a week now for the problem and cant figure it out.

**Comment by ccordoba12** [comment]
You can't mix pip and conda packages as you're doing now because that causes problems like the ones you're experiencing.

Please see our video

https://m.youtube.com/watch?v=Ul79ihg41Rs

to understand how to avoid that problem. That could help you with your issue.

**Comment by matkaa94** [comment]
Thank you I just created a new environment and deleted the old one. On the new one i dont have these problems
