### ISSUE TITLE
Can we have a better package?

### ISSUE THREAD

**Issue by sweettyler** [spyder-ide/spyder#13747]
When I tried to install the latest Spyder 4.1.5 I got the following message:

================================================
...
The following NEW packages will be INSTALLED:

  _anaconda_depends  pkgs/main/linux-64::_anaconda_depends-2020.07-py38_0

The following packages will be UPDATED:

  ca-certificates                               2020.6.24-0 --> 2020.7.22-0
  spyder                                       4.1.4-py38_0 --> 4.1.5-py38_0
  spyder-kernels                               1.9.2-py38_0 --> 1.9.4-py38_0

The following packages will be DOWNGRADED:

  anaconda                                   2020.07-py38_0 --> custom-py38_1
  cffi                                1.14.0-py38he30daa8_1 --> 1.14.0-py38h2e261b9_0
  glib                                    2.65.0-h3eb4bd4_0 --> 2.63.1-h5a9c865_0
  harfbuzz                                 2.4.0-hca77d97_1 --> 1.8.8-hffaf4a1_0
  libffi                                     3.3-he6710b0_2 --> 3.2.1-hd88cf55_4
  pango                                   1.45.3-hd140c19_0 --> 1.42.4-h049681c_0
  python                                   3.8.3-hcff3b4d_2 --> 3.8.2-hcf32534_0

....
=========================================================

My Anaconda is the latest version, 2020.07, freshly installed with all the latest packages. I know somebody may explain as "package dependencies ..." but I really wonder if Spyder really denpends so strictly on these outdated packages. Can we make the package based on the current stable version of Anaconda so that we don't need downgrade any other package?

Thank you.

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @sweettyler, thanks for reporting. You said

> I know somebody may explain as "package dependencies ..." but I really wonder if Spyder really denpends so strictly on these outdated packages

Spyder doesn't depend on those packages directly, but I think they are dependencies of our dependencies (with the exception of Python, of course).

> Can we make the package based on the current stable version of Anaconda so that we don't need downgrade any other package?

As far as I know, that's not possible because Anaconda releases every three months or so with the available versions at that moment.

However, that's not something we can solve here. Please report it on

https://github.com/ContinuumIO/anaconda-issues/issues/

to get more feedback about it.

**Comment by ccordoba12** [comment]
Since this issue is not directly related to Spyder,  but to installation shortcomings with conda (which we don't control, as I said above), I'm going to close it.

**Comment by sweettyler** [comment]
"Since this issue is not directly related to Spyder,..."

I am curious what kind of changes in the latest 4.1.5 triggered the new requirement of package dependencies. If there is just small changes compared to 4.1.4, then there is no need to change any dependency.

**Comment by ccordoba12** [comment]
The only dependency we changed is spyder-kernels.

We don't know (and can't fix) the wayconda computes dependencies, so please talk with the Anaconda guys to see what feedback they can give you about that.
