### ISSUE TITLE
runfile issue, spyder return runcell(0, 'D:/anaconda_files/s2s/mindspore/test1.py') instead of the output

### ISSUE THREAD

**Issue by peterzsj6** [spyder-ide/spyder#13744]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
F9 still works on my spyder, but ctrl+enter or run the whole file will only return the message :

In [39]:runcell(0, 'D:/anaconda_files/s2s/mindspore/test1.py')

I created a new environment for mindspore(a new deep learning platform) , and installed spyder and jupyter notebook on it.  Jupyter notebook functioned all right, but Spyder wont give me output (unless I use f9 to run the cells). 

Please let me know if I am missing something really obvious.
### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
expected:
train_set[:10]
Out[38]: 
[['aca', 'aca'],
 ['dddbadad', 'dadabddd'],
 ['adcbaca', 'acabcda'],
 ['a', 'a'],
 ['adbdabddb', 'bddbadbda'],
 ['bbdcad', 'dacdbb'],
 ['abcacdbcc', 'ccbdcacba'],
 ['dadbddbc', 'cbddbdad'],
 ['cadabdcda', 'adcdbadac'],
 ['acdbbbab', 'babbbdca']]

what I am seeing:
In [39]:runcell(0, 'D:/anaconda_files/s2s/mindspore/test1.py')

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: spyder                    4.1.5                   
* Python version:  py37_0
* Qt version: qt                        5.9.7
* PyQt version:  pyqt                      5.9.2
* Operating System name/version:  win10

the whole env:

(mindspore_env) D:\anaconda_files>conda list
# packages in environment at D:\anaconda\file\envs\mindspore_env:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
argh                      0.26.2                   py37_0
argon2-cffi               20.1.0           py37he774522_1
argparse                  1.4.0                    pypi_0    pypi
astroid                   2.4.2                    py37_0
asttokens                 2.0.4                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
atomicwrites              1.4.0                      py_0
attrs                     20.2.0                   pypi_0    pypi
autopep8                  1.5.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
bcrypt                    3.2.0            py37he774522_0
bleach                    3.1.5                      py_0
brotlipy                  0.7.0           py37he774522_1000
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py37_0
cffi                      1.14.2           py37h7a1dbc1_0
chardet                   3.0.4                 py37_1003
cloudpickle               1.6.0                      py_0
colorama                  0.4.3                      py_0
cryptography              3.1              py37h7a1dbc1_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                    pypi_0    pypi
diff-match-patch          20200713                   py_0
docutils                  0.16                     py37_1
easydict                  1.9                      pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
flake8                    3.8.3                      py_0
future                    0.18.2                   py37_1
helpdev                   0.7.1                    pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.18.1           py37h5ca1d4c_0
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                    py37_0
isort                     5.5.1                    pypi_0    pypi
jedi                      0.17.1                   py37_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
jsonschema                3.2.0                    py37_1
jupyter-client            6.1.7                    pypi_0    pypi
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py37_0
keyring                   21.4.0                   py37_0
lazy-object-proxy         1.4.3            py37he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37hfa6e2cd_1
mccabe                    0.6.1                    pypi_0    pypi
mindspore                 0.7.0                    pypi_0    pypi
mistune                   0.8.4           py37hfa6e2cd_1001
mpmath                    1.1.0                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
nbconvert                 5.6.1                    py37_1
nbformat                  5.0.7                      py_0
notebook                  6.1.1                    py37_0
numpy                     1.19.1                   pypi_0    pypi
numpydoc                  1.1.0                      py_0
openssl                   1.1.1g               he774522_1
packaging                 20.4                       py_0
pandas                    1.1.1                    pypi_0    pypi
pandoc                    2.10.1                        0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathtools                 0.1.2                      py_1
pexpect                   4.8.0                    py37_1
pickleshare               0.7.5                 py37_1001
pillow                    7.2.0                    pypi_0    pypi
pip                       20.2.2                   py37_0
pluggy                    0.13.1                   py37_0
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.7                      py_0
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.2            py37he774522_0
ptyprocess                0.6.0                    pypi_0    pypi
pycodestyle               2.6.0                      py_0
pycparser                 2.20                       py_2
pydocstyle                5.1.1                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pylint                    2.6.0                    py37_0
pynacl                    1.4.0            py37h62dcd97_1
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pyqt                      5.9.2            py37h6538335_2
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py37he774522_0
pysocks                   1.7.1                    py37_1
python                    3.7.5                h8c8aaf0_0
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py37_0
pytz                      2020.1                     py_0
pywin32                   228                      pypi_0    pypi
pywin32-ctypes            0.2.0                 py37_1001
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.2                   pypi_0    pypi
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.7                    pypi_0    pypi
qtpy                      1.9.0                      py_0
requests                  2.24.0                     py_0
rope                      0.17.0                     py_0
rtree                     0.9.4            py37h21ff451_1
scipy                     1.3.3                    pypi_0    pypi
send2trash                1.5.0                    py37_0
setuptools                49.6.0                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.2.2                      py_0
sphinx                    3.2.1                      py_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.1.5                    py37_0
spyder-kernels            1.9.4                    py37_0
sqlite                    3.33.0               h2a8f88b_0
sympy                     1.6.2                    pypi_0    pypi
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
toml                      0.10.1                     py_0
tornado                   6.0.4            py37he774522_1
traitlets                 5.0.4                    pypi_0    pypi
typed-ast                 1.4.1            py37he774522_0
ujson                     1.35             py37hfa6e2cd_0
urllib3                   1.25.10                    py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py37_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.35.1                     py_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.12.1                   pypi_0    pypi
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @peterzsj6 to enable such output you need to enable the option `Copy full cell contents to the console when running code cells`. You can find it in `Preferences > Editor > Run code > Copy full cell contents to the console when running code cells`

![image](https://user-images.githubusercontent.com/16781833/92660995-316c1c00-f2c1-11ea-8a0b-be6d95bf19a8.png)

Let us know if the info above helps :)

**Comment by peterzsj6** [comment]
> Hi @peterzsj6 to enable such output you need to enable the option `Copy full cell contents to the console when running code cells`. You can find it in `Preferences > Editor > Run code > Copy full cell contents to the console when running code cells`
> 
> ![image](https://user-images.githubusercontent.com/16781833/92660995-316c1c00-f2c1-11ea-8a0b-be6d95bf19a8.png)
> 
> Let us know if the info above helps :)

LOL, it works. Thank you! I knew I was missing something obvious.

**Comment by dmenin** [comment]
Hi, this was very helpful, why isn't this the default behaviour. It used to be as far as I remember....

**Comment by dalthviz** [comment]
Hi @dmenin for Spyder 4 we did some changes and one of them is the way to run cells. For more details on that you can check #7113

**Comment by dmenin** [comment]
Thanks for pointing that out. I'd like to give some feedback. It seems that Spyder is moving in the direction to be an IDE like, lets say, pycharm? I have installed spyder 4 and I had to make two changes to make it run like 3, this one and changing the binding to run the cell with crtl+enter, instead of F9. Please keep in mind that the main reason why me (and a good amount of the developers I know) like Spyder is the ease of code development and execution - specially to quickly just run a few lines, not the whole file (and not having to wrap it in comments for example) - please dont take that away from us and dont make it hard to do  :) 
thanks and keep up the good work

**Comment by dalthviz** [comment]
Thanks @dmenin for your feedback actually we are checking some of the usability/user experience elements for Spyder 5 in a different repository: https://github.com/spyder-ide/ux-improvements/issues . For example, regarding running cells: https://github.com/spyder-ide/ux-improvements/issues/30 if you have any thoughts or things maybe that could be a space to chat about them :)
