### ISSUE TITLE
Completion of spyder4

### ISSUE THREAD

**Issue by Schira4396** [spyder-ide/spyder#13742]
When the code is completed, the font in the candidate area is very small, and it does not look as comfortable as the code font. I don't know what's going on? Sorry I cannot take a screenshot when the candidate box appears

**Comment by steff456** [comment]
Hi @ChaoYangDongYongGuaiGe,

Can you please upload a gif with the behavior you are having?

**Comment by ChaoYangDongYongGuaiGe** [comment]
![mNrQmF5hvm](https://user-images.githubusercontent.com/57404930/92561260-7a62a700-f2a6-11ea-8e87-04610702313f.gif)
Look at this, the font of the completion candidate area is different from the font of the code editing area, which makes me very uncomfortable. Is this a bug or is it the case?

**Comment by steff456** [comment]
What I can see in your gif, is that it is the same font that you have in the complete path and the filename. Did you set this font in your Windows?

**Comment by ccordoba12** [comment]
@steff456, I think we are not using the editor font but the one used by other elements in the operating system. Could you confirm?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
