### ISSUE TITLE
Spyder shows up 'Spyder has encountered an internal problem!'

### ISSUE THREAD

**Issue by laurence-lin** [spyder-ide/spyder#13752]
### What steps will reproduce the problem?

Yesterday my Spyder works normally, today when I open it shows up the issure reporter "Spyder has encountered an internal problem!"

I don't know what happened to the Sypder. Yerterday I'd installed some tools on Windows, like WSL 2: Linux on Windows and some python packages.

### Traceback
```python-traceback
  File "C:\Users\lawrence123\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.6.10
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  0.8.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.6 (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.13.3 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.2.1 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @laurence-lin seems like the installation of the packages could have messed up the version of an indirect dependency of Spyder? What packages did you install? Also, could you try to get a full traceback of the error? (seems like the one posted is truncated)

From what the traceback says seems like could be some kind of issue with the numpy version. Maybe you could try to update numpy? (you can try something like `conda install numpy`)

Also you can check our [Basic First Aid](https://docs.spyder-ide.org/current/basic-first-aid.html) to check if something there helps

Seems like this is a package installation issue that is not directly related with Spyder but hopefully the info above could be of help :)

**Comment by laurence-lin** [comment]
> Hi @laurence-lin seems like the installation of the packages could have messed up the version of an indirect dependency of Spyder? What packages did you install? Also, could you try to get a full traceback of the error? (seems like the one posted is truncated)
> 
> From what the traceback says seems like could be some kind of issue with the numpy version. Maybe you could try to update numpy? (you can try something like `conda install numpy`)
> 
> Also you can check our [Basic First Aid](https://docs.spyder-ide.org/current/basic-first-aid.html) to check if something there helps
> 
> Seems like this is a package installation issue that is not directly related with Spyder but hopefully the info above could be of help :)

The message don't show up now, after I'd download and upgrade some packages via pip in command line.
It may be some problem that the older version of packages installed mess up with the Spyder dependency. Thank you.

**Comment by dalthviz** [comment]
Thanks for the info @laurence-lin glad is working now. I'm closing this one then :+1:
