### ISSUE TITLE
Spyder editor very slow (macOS)

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#13751]
- Spyder version: 4.1.4
- OS: macOS Catalina

The code editor in my Spyder is quite slow: there is a significant lag when typing.  If I type faster than ~3 characters per second, the characters show up in the editor later than my typing.

I don't have code folding enabled, nor Kite, nor indent guide.  My mac computer is fast enough -- system resources should not be an issue.

Can any of the developers on macOS replicate or verify this behavior?  I am not seeing this on Ubuntu.  Thanks!

**Comment by ccordoba12** [comment]
Hey @jsh9, thanks for reporting. This is a know problem (see for instance all the comments on issue #13020) and we're working to fix that in our next release.
