### ISSUE TITLE
The pyqt5 module does not have automatic completion

### ISSUE THREAD

**Issue by CatNofishing** [spyder-ide/spyder#13759]
I cannot get any intelisese  for the ptqt5 module, no autocompletiong ，please add support for pyqt5！

**Comment by andfoy** [comment]
Hi @CatNofishing, PyQt is a binary library, i.e., it does contain code in C or other languages, therefore completions are complicated to obtain. Nowadays, libraries can include mypy typing stubs in the form of pyi files, thus the creation of such files depend on the library authors and it is beyond the scope of Spyder.
