### ISSUE TITLE
Console does not process command lines

### ISSUE THREAD

**Issue by mazalgarab-git** [spyder-ide/spyder#13760]
### What steps will reproduce the problem?

The console does not process all the command lines; reset Spyder to factory default does not solve the issue.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by mazalgarab-git** [comment]
It was not a console issue. It was on a programming issue; the input command management. The variable productTypeSelection should apply the int command so that the remain code can be ran.

# Code: Select Product Type

print("=========================================")
print("Product Type Selection")
print("=========================================")
productTypeSelection = input("Insert the number option: (1) Population | (2) Prototype | (3) Sampling || : ")
print("\n=========================================")

productTypeSelection = int(productTypeSelection) **#Solution; without this statement the next if statement does not run.**

if (productTypeSelection == 1): productType = 'population'

if (productTypeSelection == 2): productType = 'prototype'

if (productTypeSelection == 3):
    productType = 'sampling'
    print("=========================================")
    print("Sampling Size Determination for the training dataset")
    print("=========================================")
    samplingSize = input("Insert the sampling size (0-100% of the dataset): ")
    print("\n=========================================")

**Comment by andfoy** [comment]
Hi @mazalgarab-git, since you managed to find the error on your code and it is not Spyder-related, I will proceed to close this issue.
