### ISSUE TITLE
Highlighting word when there is only one occurence

### ISSUE THREAD

**Issue by cjh9** [spyder-ide/spyder#13762]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
This is perhaps a bit connected to https://github.com/spyder-ide/spyder/issues/2112

I have highlight occurrence set after 100ms. That is how it seems to work in other editors like VSCode. But there the word will only be highlighted if there several occurrences. (Two or more)

 In spyder everything will be highlighted after 100ms. 

### What steps reproduce the problem?

1. Set highlight occurrence after 100ms
2. Write something
3. It will be highlighted immediately even if there is only one occurrence

### What is the expected output? What do you see instead?
It should only be highlighted if there are several occurrences.

## Versions
Latest version spyder

**Comment by steff456** [comment]
Hi @cjh9,

I could reproduce this issue, we will work in this for our next release.

Thanks for reporting!

**Comment by ccordoba12** [comment]
@steff456, to solve this issue, please take a look at the `__mark_occurrences` method of `CodeEditor`. There we build the list of occurrences, which we can avoid if the length of that list is equal to one.
