### ISSUE TITLE
Spyder stops working automatically

### ISSUE THREAD

**Issue by saumyaborwankar** [spyder-ide/spyder#13770]
### What steps will reproduce the problem?

from selenium import webdriver
import time
from webdriver_manager.chrome import ChromeDriverManager
import pandas as pd
import matplotlib.pyplot as plt

chrome_options = webdriver.ChromeOptions()
prefs = {"profile.default_content_setting_values.notifications" : 2}
chrome_options.add_experimental_option("prefs",prefs)

from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager

driver = webdriver.Chrome(ChromeDriverManager().install())

#driver = webdriver.Chrome(chrome_options=chrome_options)
driver.implicitly_wait(7)

#login
driver.get('https://yocket.in/account/login')
driver.find_element_by_xpath('//*[@id="overlay"]/div/div[1]/div/div[2]/form/div[2]/input').send_keys(user)
driver.find_element_by_xpath('//*[@id="overlay"]/div/div[1]/div/div[2]/form/div[3]/button').click()
driver.find_element_by_xpath('//*[@id="overlay"]/div/div[1]/div/div[2]/form/div[2]/div[2]/input').send_keys(passw)
driver.find_element_by_xpath('//*[@id="overlay"]/div/div[1]/div/div[2]/form/div[3]/button').click()

s=input("If Logged in Sucessfully enter k or otherwise login manually then enter k")
data=[]
for i in range(1,5):
    driver.get('https://yocket.in/applications-admits-rejects/1855-california-state-university-fresno/2?page='+str(i))
    name_container = driver.find_elements_by_class_name('col-sm-6')
    for i in name_container:
        k =(i.text)
        t=[i for i in k.strip().split("\n") if len(i) is not 0]
        data.append(t)
    time.sleep(1)

### Traceback
```python-traceback
  File "D:\Anacona3\envs\tf_gpuu\lib\site-packages\spyder\plugins\variableexplorer\widgets\dataframeeditor.py", line 520, in <lambda>
    lambda val: self.load_more_data(val, rows=True))
NameError: free variable 'self' referenced before assignment in enclosing scope
```

## Versions

* Spyder version: 4.1.1 
* Python version: 3.7.6
* Qt version: 5.12.7
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.17 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @saumyaborwankar, thanks for reporting. This is fixed in our latest version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.5

**Comment by ccordoba12** [comment]
Closing due to lack of response.
