### ISSUE TITLE
Code doesn't fold in Spyder 4.1.5

### ISSUE THREAD

**Issue by marekkolman** [spyder-ide/spyder#13771]
## Problem Description
Code folding doesn't work at all in my Spyder 4.1.5. I know there have been these issues in the prev versions of Spyder but to me it happens with the latest version.

I assume this _might have something to do_ with the fact that I use working PC, where some Spyder elements might not be available:
![error](https://user-images.githubusercontent.com/25546774/93016813-2ddbdc00-f5c4-11ea-95b1-256641d66c8c.GIF)
On my personal PC code folding works fine. I'd still expect code folding should work on my working PC as well.

### What steps reproduce the problem?

![folding_not_working2](https://user-images.githubusercontent.com/25546774/93016676-56170b00-f5c3-11ea-9b84-47a88d40d640.gif)

### What is the expected output? What do you see instead?
The code should fold.

### Paste Traceback/Error Below (if applicable)

```python-traceback

QProcess: Destroyed while process ("C:\\Users\\KolmanM\\AppData\\Local\\Continuum\\anaconda3\\python.exe") is still running.
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '-1' out of range
QTextCursor::setPosition: Position '-1' out of range


```

## Versions

* Spyder version: 4.1.5
* Python version: 3.7.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  None (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  None (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
> pyls >=0.34.0;<1.0.0           :  None (OK)

This is the problem, i.e. you don't have this package installed and that's what's causing this issue.

To fix that, please close Spyder, open the Anaconda Prompt, run there

    conda install python-language-server

and try again.

**Comment by marekkolman** [comment]
Thank you. I had the package installed, so I removed and installed again. After reinstall Spyder saw that package in dependencies but it still didn't work. What I did is that I enabled this:
![spyder_issue](https://user-images.githubusercontent.com/25546774/93024325-f71eb980-f5f5-11ea-9946-6ea3c35635be.GIF)
Not sure exactly what it does but now all runs fine. It might have something to do with the working PC config (ports blocked or so).

**Comment by ccordoba12** [comment]
> Not sure exactly what it does but now all runs fine

Great to know!

> It might have something to do with the working PC config (ports blocked or so).

Probably. That option sets a particular port for the completion and linting server to run on (yes, we use a server to provide those services, along with folding and many other things in the editor).

**Comment by ccordoba12** [comment]
I'm going to close this issue for everything is working for you now. Thanks for using Spyder!

**Comment by RSKothari** [comment]
Since I didn't want to re-open a previous issue, I'm facing similar issue [here](https://github.com/spyder-ide/spyder/issues/14166).
