### ISSUE TITLE
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'defaults::ipykernel-4.10.0-py35_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Lenovo\Anaconda3\envs\Chatbot\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

### ISSUE THREAD

**Issue by NitinSaini18** [spyder-ide/spyder#13776]
### What steps will reproduce the problem?

When i created new environment with python=3.5.0 version and tensorflow = 1.0.0
after the when i tried to install Spyder using *conda install Spyder* but then it is showing me this error :
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing package 'defaults::ipykernel-4.10.0-py35_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\Lenovo\Anaconda3\envs\Chatbot\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Please help me with this issue. I have anaconda 5.1.0 version 

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.4.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.4.7 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.8.3 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  17.1.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
@NitinSaini18, as I told you yesterday, these are conda installation issues, not bugs in Spyder.

Therefore, we can't solve them here. Instead, please report them in this repo

https://github.com/ContinuumIO/anaconda-issues
