### ISSUE TITLE
Is there a command to restart the plot window in the new version of spyder?

### ISSUE THREAD

**Issue by hdnh2006** [spyder-ide/spyder#13780]
## Problem Description
Hello! 

I am plotting several figures using `matplotlib` in spyder. With the new version (4.1.3) the plots are now shown inside a the IDE like is done in R for example (which is awesome!), but now I want to close all the windows plotted with just a simple command or pressing any shortcut.

Is there a way to do that?

### What steps reproduce the problem?
```

import matplotlib.pyplot as plt

for i in range(0,7):
    x=list(range(i,i+10))
    y=list(range(i,i+10))
    plt.figure()
    plt.plot(x,y,linewidth=2, markersize=12)
```
![image](https://user-images.githubusercontent.com/17271049/93086437-6bf60000-f697-11ea-96c4-d4f788ed13ca.png)

### What is the expected output? What do you see instead?
This is what I expect:

![image](https://user-images.githubusercontent.com/17271049/93086598-a5c70680-f697-11ea-9218-1fcad074a562.png)

## Versions
* Spyder version: 4.1.3
* Python version:  3.7.5 64-bit 
* Qt version: 5.12.4
* PyQt version: 5.12.3
* Operating System name/version: Ubuntu 19

Thanks in advance

**Comment by steff456** [comment]
Hi @hdnh2006,

I'm glad that you like our plots feature, it is great! If you want to erase all the plots you generated, you can go ahead and click the highlighted icon in red,

<img width="618" alt="Captura de Pantalla 2020-09-14 a la(s) 12 33 46 p  m" src="https://user-images.githubusercontent.com/20992645/93118910-99867d80-f686-11ea-97d1-1327d8faa1df.png">

For further information please note that two weeks ago we released the new documentation site where you can find a lot of guidance of how to use each pane of Spyder. For instance, this is the site of the plots pane, https://docs.spyder-ide.org/current/plots.html

Thanks for reporting!

**Comment by sofalzone** [comment]
Is there a way to do this programmatically? Like how you can clear the consol with:

from IPython import get_ipython

get_ipython().magic('clear')

get_ipython().magic('reset -sf')

**Comment by ccordoba12** [comment]
No, there isn't.
