### ISSUE TITLE
Changing color of object in f-strings

### ISSUE THREAD

**Issue by bwinsto2** [spyder-ide/spyder#13801]
## Problem Description
I have a very simple issue that I haven't found an answer for here or online. Apologies if it exists somewhere. 
Inside of f-strings, I'm wondering if there is a way to change the color of the object. For example in, `f'hello my name is {name}'`, I'm wondering if there is a way in spyder to set the color scheme such that {name} appears a different color than the rest of the string.

Cheers!

* Spyder version: 4.01
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: rhel 7

**Comment by andfoy** [comment]
Hi @bwinsto2, we are working in improving the syntax highlighting support for Spyder 5. The improvements include better support for semantic highlighting for Python as well as supporting more languages.

**Comment by bwinsto2** [comment]
Ok--thanks.

**Comment by Sam-OT** [comment]
> 
> 
> Hi @bwinsto2, we are working in improving the syntax highlighting support for Spyder 5. The improvements include better support for semantic highlighting for Python as well as supporting more languages.

Thanks, @bwinsto2, for your work on Spyder. I really like it and use it a lot! I just wanted to say, though, that the same issue still happens in Spyder 5.0.5. My specifications are Python 3.9.6 64-bit, Qt 5.9.7, PyQt5 5.9.2 and Windows 10 .

![image](https://user-images.githubusercontent.com/81111289/135428001-fba14970-4cab-4807-9fea-733832e568ee.png)

Incidentally, if I put this in the IPython console, then it behaves as desired.

![image](https://user-images.githubusercontent.com/81111289/135428075-79e0a06e-5c18-4e10-a3d7-fb7c0ba5b0c1.png)

So it seems like it has only been partially implemented?

**Comment by backmind** [comment]
Any update about this? This feature could be very handy :)

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 6, to be released at the end of the year or beginning of the next one.

**Comment by TMdeRuyter** [comment]
It appears that this has still not been resolved as of Spyder 6.0.0a5 :(

**Comment by ccordoba12** [comment]
@TMdeRuyter, unfortunately this won't be solved in 6.0 because we're really busy with other things. But we'll try to do it in a follow-up one.
