### ISSUE TITLE
Incorrect size shown after appending new key to the dictionary


### ISSUE THREAD

**Issue by colt18** [spyder-ide/spyder#13802]
### What steps will reproduce the problem?

We have following dictionary with keys, values and sizes shown correctly.
![resim](https://user-images.githubusercontent.com/26602153/93499351-8b9d5a80-f91b-11ea-87e0-9c3329e5b9e4.png)

Then we add final key 'openTest_11.png' and poof. As the key is not appended to the end but inserted into mid(due to sorting keys), sizes are shown incorrect.  

![resim](https://user-images.githubusercontent.com/26602153/93499527-c8695180-f91b-11ea-8f38-dfe3ffcb26e1.png)

Though sizes are shown correct by calling dictionary keys and size(). Just the table is broken.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.6 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @colt18, thanks for reporting. Sorry, this was a regression introduced in our 4.1.5 version (see issue #13733), but it was just fixed (see pull request #13791).

The fix will be available in our next version.
