### ISSUE TITLE
segmentation fault w/fresh spyder install

### ISSUE THREAD

**Issue by pracplayopen** [spyder-ide/spyder#13811]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [na ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Fresh install of conda/spyder (stable) into new environment.   

No issues during install, but seg faults running spyder from command line.

Again this is a brand new install from conda-forge so all packages are latest.

Interestingly, running via python interpretter produced missing module for spyder itself, even as conda says spyder is installed into the environment.

Seemed superficially similiar to https://github.com/spyder-ide/spyder/issues/6968 but that bug was fixed in spyder 3.x and i'm running stable (4.1.5).  (also the workarounds did not change behavior)

### What steps reproduce the problem?

```
$ conda --version
conda 4.8.3
$ conda create -n minimal_ds
$ conda activate minimal_ds
(minimal_ds) $ conda install spyder numpy scipy pandas matplotlib sympy cython pyopengl
(minimal_ds) $ conda list|egrep "pyqt|spyder"
pyqt                      5.12.3           py38ha8c2ead_3    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtchart                 5.12                     pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
spyder                    4.1.5            py38h32f6830_0    conda-forge
spyder-kernels            1.9.4            py38h32f6830_0    conda-forge
(minimal_ds) $ SPYDER_DEBUG="3" spyder
Segmentation fault (core dumped)
(minimal_ds) $ SPYDER_DEBUG="3" python $(which spyder)
Traceback (most recent call last):
  File "/home/zzzzzz/work/miniconda3/envs/minimal_ds/bin/spyder", line 7, in <module>
    from spyder.app.start import main
ModuleNotFoundError: No module named 'spyder'
(minimal_ds) $ python --version
Python 3.8.3

```

### What is the expected output? What do you see instead?

(listed above)

### Paste Traceback/Error Below (if applicable)

(see above)

## Versions

* Spyder version: (see above)
* Python version: (see above)
* Qt version: (see above)

```
(minimal_ds) $ qmake --version
QMake version 3.1
Using Qt version 5.12.9 in /home/zzzzz/work/miniconda3/envs/minimal_ds/lib
```

* PyQt version: (see above)
* Operating System name/version: 

```
(minimal_ds) $ uname -a
Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```

### Dependencies

(n/a since spyder doesn't boot)

### Other info

Also tried starting start.py as recommended in troubleshooting guide, complains about zmq module missing though that module is also installed:

```
(minimal_ds) $ /usr/bin/python3.8 $(find pkgs/spyder-4.1.5-py38h32f6830_0 -iname 'start.py')
Traceback (most recent call last):
  File "pkgs/spyder-4.1.5-py38h32f6830_0/lib/python3.8/site-packages/spyder/app/start.py", line 22, in <module>
    import zmq
ModuleNotFoundError: No module named 'zmq'
(minimal_ds) $ conda list|grep zmq
pyzmq                     19.0.2           py38ha71036d_0    conda-forge
(minimal_ds) $ conda install pyzmq
# All requested packages already installed.

```

**Comment by pracplayopen** [comment]
as a work around, was able to get dev version installed from github to a clean conda environment (per: https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)

The only differences between stable install and spyder github dev are:

1. github instructions use a spyder channel to install conda packages  (not conda-forge)
1. github instructions pin to versions, tho all the versions seem to agree with conda-forge defaults used above

Guessing you don't want to have new installs use dev channel.

If something else can do to help isolate specific version or package causing issue with stable, very willing to help.

**Comment by ccordoba12** [comment]
Hey @pracplayopen, thanks for reporting. This seems a problem in your system or conda-forge, and not in Spyder. You could try to install everything from `defaults` in a new environment.

Other than that, we don't have more recommendations for you, sorry.

**Comment by pracplayopen** [comment]
it was a stock machine w/everything new from stable so figured it was worth a report.

understanding is conda-forge is supposed to be more recommended than defaults/anaconda channel.  

was able to reproduce original problem using instructions provided, so not system issue.

today confirmed spyder does start w/out conda-forge.    

like you don't have time to investigate further the actual discrepency between packages.  general warning to be wary of using conda-forge w/spyder i guess.

workaround is just to do less :)

```
$ conda create -n spyder-default
$ conda activate spyder-default
(spyder-default) ~ $ conda install pandas matplotlib notebook spyder sympy scipy cython numpy
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(spyder-default) ~ $  spyder &
# no more segfault/missing pkgs that are actually installed. spyder now loads as normal w/out needing dev channel stuff

```

thanks
