### ISSUE TITLE
Blocky monospaced fonts in Spyder Mac OS Catalina

### ISSUE THREAD

**Issue by LudgerHentschel** [spyder-ide/spyder#13815]
Spyder (4.1.5) displays monospaced fonts in a weird "bold" and blocky format under Mac OS Catalina. Other applications display the same monspaced fonts without this issue. (Proportionally spaced fonts in the Help pane in Spyder also look OK to me.)

These blocky monspaced fonts in Spyder materially reduce readability and seem undesirable to me. I recognize that this is partly a matter of personal preference. 

What appears to be a previous report of this issue was closed on October 23, 2018 with the comment that Qt 5.12 will fix this. (See "Spyder fonts have changed and are now too blocky #8132". https://github.com/spyder-ide/spyder/issues/8132)

I have installed the latest version of Anaconda Python 3.8.1 under Mac OS X 10.15.6 but still see what I presume to be the same issue. Anaconda installed Qt 5.9.7. Maybe Qt 5.12 is still a long time away. 

In the meantime, using a very thin monospaced font makes Spyder look much better. Spyder still makes the font fatter; but starting with a very thin font makes the final display in Spyder look OK. 

I have had success with Google Roboto Mono (https://fonts.google.com/specimen/Roboto+Mono). Spyder only shows a single Roboto Mono font, even if several weights are installed. Uninstalling or disabling the heavier styles forces Spyder to use the lighter weights.  Since there are several weights in the package, it is possible to keep and use the one that looks best.

Here is Andale Mono in Spyder

![Screen Shot 2020-09-19 at 5 58 00 PM](https://user-images.githubusercontent.com/28766875/93690090-8dddf100-faa2-11ea-9de6-9caab36a593c.png)

Here is Andale Mono in BBEdit, for comparison

![Screen Shot 2020-09-19 at 5 59 59 PM](https://user-images.githubusercontent.com/28766875/93690078-76066d00-faa2-11ea-8b74-26b65948e821.png)

Here is Roboto Mono (Light) in Spyder
 
![Screen Shot 2020-09-19 at 5 55 20 PM](https://user-images.githubusercontent.com/28766875/93690068-638c3380-faa2-11ea-8e61-1b4d9f04615e.png)

All fonts sizes are 14pt in the screenshots above.

**Comment by ccordoba12** [comment]
Hey @LudgerHentschel, thanks for reporting. I also think this is an issue with Qt, hence something we can't fix directly. We just need to wait until Anaconda publish packages for more recent Qt versions, sorry.
