### ISSUE TITLE
How can i see the contents of my dataframe in the variable explorer in spyder 4.0.1

### ISSUE THREAD

**Issue by shankyemcee** [spyder-ide/spyder#13831]
![image](https://user-images.githubusercontent.com/30503832/93827716-da0e6a00-fc37-11ea-98c1-d64a7d8ea259.png)

**Comment by ccordoba12** [comment]
Hey @shankyemcee, thanks for reporting. You need to install Pandas in the same environment that Spyder is running to solve this problem.

Please do that and let us know if it works for you.

**Comment by shankyemcee** [comment]
Hi @ccordoba12  Thanks for your reply.

I have already installed Pandas in the directory of my spyder environment. But once I open the dataframe in the variable explorer, it just shows me the attributes of the dataframe. How can i see the table structure like in versions of spyder 3?

**Comment by ccordoba12** [comment]
> I have already installed Pandas in the directory of my spyder environment

Please post the output of `conda list` to confirm.

**Comment by jondo** [comment]
I just had the same problem, because I had installed Pandas only after opening Spyder. Re-opening Spyder fixed it.  (I am using pip with pip-tools, btw.)

**Comment by ccordoba12** [comment]
> because I had installed Pandas only after opening Spyder. Re-opening Spyder fixed it.

RIght, I forgot to mention that. Thanks @jondo for chiming in.

**Comment by shankyemcee** [comment]
Oh thanks  @jondo  restarting spyder fixed it. Thanks for the support @ccordoba12.

**Comment by ccordoba12** [comment]
No problem, glad you were able to solve this issue.
