### ISSUE TITLE
Issue 13611 reopen?

### ISSUE THREAD

**Issue by Fizz04** [spyder-ide/spyder#13842]
I suddenly received an email that my issue #13611 was closed.  Nothing has been resolved, but i was told to patiently await for a reply.  And yet i haven't seen any further resolution to the issue.
-Fizz

**Comment by dalthviz** [comment]
Hi @Fizz04 I will reopen the original issue #13611 however there is not much we can do about it, since seems like is related with Anaconda Navigator not picking the correct env when launching applications
