### ISSUE TITLE
Change Spyder-Kernels version designation on Spyder version bump

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#13841]
So, one issue for building the Spyder standalone Mac application is that after it's built with the subrepos of python-language-server and spyder-kernels, it is unclear which version of these packages is used.

When Spyder gets a version bump, the version designation is set, e.g. ``version_info = (4, 1, 5)``, and is associated with a known commit.
The problem for the standalone app is that probing the internal console for spyder-kernels will only reveal ``'1.10.0.dev0'``, which is virtually meaningless.

While it is possible to explicitly build with the release versions of the subrepos, in which case the exact commit for these packages can be known, this may not be the best solution since Spyder release versions are tested with the existing subrepo state, whatever commit that may be.

One solution may be to only use release version states in the subrepos. Another may be to bump the package versions in conjunction with Spyder version bumps. Or maybe there are other solutions...

@ccordoba12 , What do advise?

**Comment by ccordoba12** [comment]
> So, one issue for building the Spyder standalone Mac application is that after it's built with the subrepos of python-language-server and spyder-kernels, it is unclear which version of these packages is used.

I don't understand why you're doing that. If that's the case even for our stable versions, I'd recommend you to revert that behavior. What I have in mind for our macOS app (and also for our Windows installer) is to provide a very stable and robust Spyder version, not something that is constantly changing.

> One solution may be to only use release version states in the subrepos. Another may be to bump the package versions in conjunction with Spyder version bumps. Or maybe there are other solutions...

The subrepos are only a way to provide a nice development environment for all our contributors by allowing them to not constantly keep updated `spyder-kernels` and `python-language-server` from their master branches.

**Comment by mrclary** [comment]
@ccordoba12, if I understand you correctly, then you're suggesting that I build Spyder with with release versions of python-language-server and spyder-kernels. If that is correct, then that is simple enough to do, no problem.

Perhaps I'm confused about the testing environment, though. Is it correct to say that Spyder is tested with the release versions of python-language-server and spyder-kernels and _not_ the subrepo versions? When I looked at the test manifests it appeared to me that both python-language-server and spyder-kernels are installed and _removed_ in the "Create test environment" stage as well as in the "Post install conda" stage. Neither appear in the "Show test environment" manifest.

**Comment by ccordoba12** [comment]
> if I understand you correctly, then you're suggesting that I build Spyder with with release versions of python-language-server and spyder-kernels

Well, my idea is to only build stable versions of Spyder for the app, which require stable versions of python-language-server and spyder-kernels.

What's yours?

> Is it correct to say that Spyder is tested with the release versions of python-language-server and spyder-kernels and not the subrepo versions?

No, that's not correct. We test things against the packages present in our subrepos.

> When I looked at the test manifests it appeared to me that both python-language-server and spyder-kernels are installed and removed in the "Create test environment" stage as well as in the "Post install conda" stage. Neither appear in the "Show test environment" manifest.

Yeah, that's right. We do that to ensure that we run our tests against our subrepos and not their conda packages.

**Comment by mrclary** [comment]
> Well, my idea is to only build stable versions of Spyder for the app, which require stable versions of python-language-server and spyder-kernels.
> 
> What's yours?

My idea is the same. I was under the (correct) impression that Spyder was tested with the subrepo versions, so I've doing test builds with those. It seems to me that there could be potential issues if users run Spyder's release version with release versions of pyls and spyder-kernels, when the Spyder release version was only tested with (potentially updated) subrepo versions.

**Comment by ccordoba12** [comment]
> It seems to me that there could be potential issues if users run Spyder's release version with release versions of pyls and spyder-kernels, when the Spyder release version was only tested with (potentially updated) subrepo versions.

I understand your concerns, but before every Spyder release, I also release new versions of those two packages (if necessary) and update our requirements on them to ensure everything works together.

I know it seems convoluted to someone not very familiar with our development process, but it's the best way I've found to develop such a tight integration between Spyder, spyder-kernels and python-language-server.

**Comment by mrclary** [comment]
Okay, I see. It's not so convoluted, now that I understand what's going on. I see that Spyder's 4.1.4 and 4.1.5 were using spyder-kernels=1.9.4 and python-language-server=0.34.0 release versions in the subrepo. I was under the (erroneous) impression that the subrepos were updated more frequently to include commits _between_ release versions of these packages. My apologies!
