### ISSUE TITLE
IPython kernel fails to start on fresh install of Anaconda

### ISSUE THREAD

**Issue by Jamesekmills** [spyder-ide/spyder#13855]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
IPython console reports: An error ocurred while starting the kernel

I have tried: 
1. Uninstalling following the [guide ](https://docs.anaconda.com/anaconda/install/uninstall/) and reinstalling Anaconda
2. Reset Spyder settings
3. Following the advice given in previous threads I have tried many combinations of updating and rolling back jupyter_client and jupyter_core
4. conda update conda
5. conda update spyder
6. conda install spyder=4.1.5
7. conda update setuptools
8. conda update --all
9. Uninstalled and reinstalled Anaconda for the n'th time and asked for help here!

### What steps reproduce the problem?

1. Install latest version of Anaconda
2. Start Spyder  

### What is the expected output? What do you see instead?

"An error ocurred while starting the kernel"

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1223, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 304, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 251, in pre_start_kernel
self.write_connection_file()
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\James.Mills1\Anaconda3\lib\contextlib.py", line 113, in __enter__
return next(self.gen)
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\James.Mills1\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 369, in win32_restrict_file_to_user
sd = win32security.GetFileSecurity(fname, win32security.DACL_SECURITY_INFORMATION)
pywintypes.error: (50, 'GetFileSecurity', 'The request is not supported.')

```

## Versions

Spyder 4.1.4
Python 3.8.3 64-bit 
Qt 5.9.7
PyQt5 5.9.2 
Windows 8.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Jamesekmills** [comment]
I should note that I have found it is possible to get spyder 4.1.4 to work via: pip install jupyter-client==5.3.1. This gives the following warning,

ERROR: spyder-kernels 1.9.2 has requirement jupyter-client>=5.3.4, but you'll have jupyter-client 5.3.1 which is incompatible. 

Spyder seems to run just fine despite this conflict, however, from [previous posts](https://github.com/spyder-ide/spyder/issues/11438) I learn that this dependency is required to avoid security issues so I'm looking for a better solution.

**Comment by juanis2112** [comment]
Hi @Jamesekmills. Can you please post here the output or running `conda list`. It seems the problem might be due to installing packages with pip and conda in the same environment. Take a look at our video https://youtu.be/Ul79ihg41Rs to see how to uninstall anaconda correctly.

**Comment by juanis2112** [comment]
Closing for no response.
