### ISSUE TITLE
TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

### ISSUE THREAD

**Issue by BM8143** [spyder-ide/spyder#13851]
after updating spyder it is showing for every program as the title said above

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```
CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by impact27** [comment]
It sounds like you have a mismatching version of spyder and spyder-kernels

**Comment by MrCrazyCrab** [comment]
@impact27 @BM8143  i met the same problem, and i can not run my code before that for the reason that the memory of GPU is not enough. However, if i shut down the spyder and use the cmd to run my code, everything is ok.

**Comment by Bert-Joost** [comment]
This issue already exists (#13715, closed)
Resolved by upgrading/installing Spyder 4.1.5

**Comment by ccordoba12** [comment]
That's correct. You need to update to 4.1.5 to fix this. Thanks for reporting @BM8143.

**Comment by jasonharris438** [comment]
I've got conflict between my python version and spyder 4.1.5, which isn't allowing me to upgrade to latest spyder=4.1.5.

I got this same error - TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all' - when running the debugger with spyder=4.1.3 and spyder-kernels=1.9.4.

Downgrading to spyder-kernels=1.9.3 with spyder=4.1.3 fixed the problem for me.

**Comment by ccordoba12** [comment]
@jasonharris438, you need to use spyder-kernels 1.9.4, along with Spyder 4.1.5, to fix that problem.

**Comment by jasonharris438** [comment]
Thanks @ccordoba12, will remember that once I have the correct python version to proceed with

**Comment by pyforever** [comment]
@ccordoba12, what's the correct way to upgrade Spyder to 4.1.5?
I tried from prompt: "conda update --all" but it leads to the problem with Spyder and it isn't solved upgrading the kernel to 1.9.4.
I'm stuck here, please help!

**Comment by ccordoba12** [comment]
Hey @pyforever, the right way to update Spyder is by running

    conda update anaconda
    conda install spyder=4.1.5

**Comment by pyforever** [comment]
Thanks, I'll do so.

**Comment by pyforever** [comment]
When I tried to install spyder 4.1.5 it told me there were conflicts and now are more than 20 hours it's examining them: is it normal all this time?

**Comment by ccordoba12** [comment]
They shouldn't appear if you ran `conda update anaconda` first. But if that didn't work, perhaps you need to reinstall Anaconda again.

Please see the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do it correctly.

**Comment by pyforever** [comment]
Yes, I ran conda update anaconda but ittold me  "all requested packages wew already installed" and ended.

**Comment by endolith** [comment]
Hey @pyforever, the right way to update Spyder is by running

> conda update anaconda
> conda install spyder=4.1.5

But anaconda.com says you should *not* run `conda update anaconda`:

https://www.anaconda.com/blog/keeping-anaconda-date

> What 95% of People Actually Want
> 
> In most cases what you want to do when you say that you want to update Anaconda is to execute the command:
> 
> conda update --all
> 
> Updating the Anaconda Package is Almost Always a Bad Idea

I don't know who to believe :(

**Comment by Ikhwansong** [comment]
I solved this problem by modifying the version of the spyder-kernel via anaconda-navigator.

The solution what i did is as follows 
First. downgrade the spyder to 4.1.1
Second. downgrade the kernels to 1.9.1
