### ISSUE TITLE
Spyder Stuck on Launch Console

### ISSUE THREAD

**Issue by taylorpack13** [spyder-ide/spyder#13854]
### Issue Report Checklist

* [ y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [y ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [y ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [y ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ y] Tried basic troubleshooting (if a bug/error)
    * [y ] Restarted Spyder
    * [ y] Reset preferences with ``spyder --reset``
    * [y ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [y ] Tried the other applicable steps from the Troubleshooting Guide
* [y ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I am new to Spyder and Python in general and have been running Spyder for about a month with no problems. Last week I had a Windows update and was having this same issue but it was fixed by updating Spyder. It was working fine after that and then Yesterday I had a blue screen of death and afterwards I tried to launch Spyder and it gets stuck in the launch console on "Launching code completion client for Python..." After several minutes Window's will tell me Python is unresponsive and close the launcher. 

### What steps reproduce the problem?

1. Launching Spyder from Start
2. Launching Spyder from command prompt 
3. Launching Spyder from Anaconda Navigator 

### What is the expected output? What do you see instead?

Expect Spyder to launch but gets stuck in launch console and becomes unresponsive instead. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @taylorpack13, thanks for reaching out, have you tried to execute Spyder outside Anaconda Navigator (via the Anaconda prompt)? Also, have you tried reinstalling Anaconda?

**Comment by taylorpack13** [comment]
Yes. I tried both of those and am still having the same issue.

**Comment by andfoy** [comment]
Thanks for your reply, when you uninstalled Anaconda, did you ensure that all environment variables and files were removed?

**Comment by ccordoba12** [comment]
@taylorpack13, you can also take a look at the advice we provide in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to see if that helps.

**Comment by taylorpack13** [comment]
Yes everything was removed. I followed the instructions in the video as well and it still is stuck.

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and start Spyder with the following command:

    spyder --debug-info verbose --debug-output file

and upload a file called `spyder-debug.log` present in the same directory where you started the previous command.

**Comment by taylorpack13** [comment]
I ran that command and the spyder-debug.log file was empty. 
This is what comes up after running the command:
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "D:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3606, in main
    setup_logging(options)
  File "D:\Anaconda3\lib\site-packages\spyder\app\utils.py", line 94, in setup_logging
    handlers.append(logging.FileHandler(open(log_file, 'w+')))
  File "D:\Anaconda3\lib\logging\__init__.py", line 1130, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper

**Comment by ccordoba12** [comment]
I don't know what happens in your case. I'm out of ideas, sorry.

**Comment by taylorpack13** [comment]
I tried uninstalling and reinstalling Anaconda again. Now it is working. Not sure what happened or what I did differently this time but thank you for your help.

**Comment by ccordoba12** [comment]
I'm really glad that finally Spyder worked for you again.

**Comment by taylorpack13** [comment]
So I had this same issue happen again today and I tried following the same steps I did last time and nothing was working. I even used third party systems to uninstall anaconda. Then I deleted Kite and spyder works fine now. Why does Kite cause this problem? Am I fine to run sypder without Kite?

**Comment by ccordoba12** [comment]
> Am I fine to run sypder without Kite?

Yes, you are. Kite provides additional functionality but it's required to run Spyder.
