### ISSUE TITLE
SpyderKernalApp not working after updating

### ISSUE THREAD

**Issue by carrios24** [spyder-ide/spyder#13861]
### What steps will reproduce the problem?

I updated my spyder and anaconda. I got this error message [SpyderKernelApp] WARNING | No such comm: 2420ea1cffaa11ea9a108cae4ce01fdf. I dont know why it keeps doing that when I run my code. It used to work in a previous version. 

I would also like to add that my project code works on my friends computer. He uses Spyder: 3.3.6, Python: 3.7.3, Qt: 5.9.6, PyQt5: 5.9.2, OS: Windows 10. 

I also found an issue with icons overlapping words in the drop down menus. For example, when you click on help the bug icon overlaps with the R in "Report issue..." 

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @carrios24, thanks for reporting. You said:

> I updated my spyder and anaconda. I got this error message [SpyderKernelApp] WARNING | No such comm: 

Please post an screenshot to see where that messages is appearing.

> I also found an issue with icons overlapping words in the drop down menus. For example, when you click on help the bug icon overlaps with the R in "Report issue..."

I don't understand this problem. Please post an screenshot about it too.

**Comment by carrios24** [comment]
Thanks for the quick response! Here is a screenshot of both issues. The console log shows the SpyderKernelApp warning and the help menu shows the logo overlapping.
![image](https://user-images.githubusercontent.com/43592381/94352033-d6eaf380-0014-11eb-8717-09c245186b00.png)

**Comment by ccordoba12** [comment]
Ok, thanks! I understand better your problems now.

> I updated my spyder and anaconda. I got this error message [SpyderKernelApp] WARNING | No such comm:

This is simply a warning. The real problem is that your code is causing a crash (I don't know why). Are you able to run it outside Spyder? You can do that by opening the Anaconda Prompt and running there

    python game.py

> I also found an issue with icons overlapping words in the drop down menus. For example, when you click on help the bug icon overlaps with the R in "Report issue..."

This could be a problem with your screen resolution. What's your resolution?

**Comment by carrios24** [comment]
Woah it works on Anaconda Prompt! And my screen resolution is 3000 x 2000

**Comment by carrios24** [comment]
Also I can send you a link to the package that I am using. It opens a new window to display the code I wrote as a game. I think that might be causing the issue?

**Comment by ccordoba12** [comment]
> Also I can send you a link to the package that I am using. It opens a new window to display the code I wrote as a game. I think that might be causing the issue?

Yes, that could be the problem. Please send us the link so we can test it in our side.

**Comment by carrios24** [comment]
[pgl.txt](https://github.com/spyder-ide/spyder/files/5295628/pgl.txt)

**Comment by ccordoba12** [comment]
Closing because this is quite old now. Hopefully you managed to solve this problem.
