### ISSUE TITLE
Running Debug mode - RecursionError: maximum recursion depth exceeded - new install

### ISSUE THREAD

**Issue by sidsidsidsid** [spyder-ide/spyder#13863]
![2020-09-26_16-29-30](https://user-images.githubusercontent.com/30485694/94349831-51684300-0016-11eb-9632-38bfae9ddabe.png)

### Issue Report Checklist
* [#5203 is similar, but it was closed] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ check] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [no need, just installed a day ago ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [not related ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ check below] Tried basic troubleshooting (if a bug/error)
    * [check] Restarted Spyder
    * [check ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [check ] Tried the other applicable steps from the Troubleshooting Guide
* [check ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Get "RecusionError" when attempting "Debugging." Issue #5023, is similar, but no guidance was offered. 

I was attempting my own created python file with code when the error started. Then attempted other code files and still, the same error persisted. 

I decided to run a simple test, with one line of code,  to see if it's my code or Spyder, so I created a new file with a one-line statement and the error persisted.

### What steps reproduce the problem?
1. select untitled.py file in the image attached to this issue
2. select "debug' from the Spyder menu
3. 

### What is the expected output? What do you see instead?
Start in debug mode. See a Recursion error

### Paste Traceback/Error Below (if applicable)
"....debugfile('C:/Users/XXX/ide/Anaconda3_projects/spyder_project_vest/untitled1.py', wdir='C:/Users/XXX/ide/Anaconda3_projects/spyder_project_vest')..."

The Error in the console is very long. Partially shown in the image attached to this issue.

## Versions
* Spyder version: 4.1.5
* Python version: 3.6.10
* Qt version: 5.12.6
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.12.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  1.8.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.3 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.1 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

**Comment by ccordoba12** [comment]
Hey @sidsidsidsid, thanks for reporting, Please open an Anaconda prompt, run there

    echo %HOME%

and post the result here.

**Comment by sidsidsidsid** [comment]
@ccordoba12  command output below:


(vestv1) C:\Users\XXX>echo %HOME%
%HOME%

**Comment by sidsidsidsid** [comment]
@ccordoba12 I tried the below env too.

(vestv1) C:\Users\XXX>echo %HOMEPATH%
\Users\XXX

**Comment by ccordoba12** [comment]
> (vestv1) C:\Users\XXX>echo %HOME%
%HOME%

This is weird. What happens if you run this?

    echo %FOO%

**Comment by sidsidsidsid** [comment]
(vestv1) C:\Users\XXX>echo %FOO%
%FOO%

it appears the "echo" command does this for non-defined environment variables

When I do the below command it will list all the defined env variables. So, env variables are defined, but not %HOME% or %FOO%

(vestv1) C:\Users\XXX>set
...
...
...

**Comment by ccordoba12** [comment]
Ok, then please run the following code in one of our IPython consoles:

    import os
    os.environ['HOME']

and paste the output here.

**Comment by sidsidsidsid** [comment]
Below is the output:


""""""""""""""""""""""""""""""
import os

os.environ['HOME']
Traceback (most recent call last):

  File "<ipython-input-3-9baf0305498a>", line 1, in <module>
    os.environ['HOME']

  File "C:\Users\sims\miniconda3\envs\vestv1\lib\os.py", line 669, in __getitem__
    raise KeyError(key) from None

KeyError: 'HOME'

**Comment by ccordoba12** [comment]
Ok, then please add these line to the top of your file

    import os
    os.environ['HOME'] = ''

and try to debug your file.

**Comment by sidsidsidsid** [comment]
_TEST A : I tried the following tests and all four returned the same Debug error_
1. **top of python file**
import os
os.environ['HOME'] = '\\users\\XXX'

2. **top of python file**
import os
os.environ['HOME'] = ''

3. used **ipython command console**
import os
os.environ['HOME'] = '\\users\\XXX'

4.  used **ipython command console**
import os
os.environ['HOME'] = ''



_TEST B: cut&paset line generating the error_

I noticed the error seems to have started in ntpath.py on line-324 and ended in _collections_abc.py on line-666.

I set HOME [per image attachment] and ran line-324 from ntpath.py in the ipython command console. The error did not happen.
But when I ran the Debug [line-20 of the ipython console command] the error occurs again.

It appears the error is only activated when running via python file. But, if you manually run line-324 in the console the error does not happen. I'm not sure if these tests lend any value.


![home-spyder test1](https://user-images.githubusercontent.com/30485694/94392320-e9088700-0125-11eb-98ad-c316f54e4514.png)

**Comment by ccordoba12** [comment]
> I noticed the error seems to have started in ntpath.py on line-324 and ended in _collections_abc.py on line-666.

Yes, I noticed that too. Unfortunately this is not an error in Spyder but in Python itself, so I don't know how to give you more support, sorry.

**Comment by ccordoba12** [comment]
Perhaps you should remove and reinstall Anaconda to see if the error goes away.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
