### ISSUE TITLE
Jedi & Parso dependency version

### ISSUE THREAD

**Issue by ariane-er** [spyder-ide/spyder#13879]
### What steps will reproduce the problem?

Clean install of Spyder4 using Anaconda in Ubuntu.
The versions of Jedi & Parso aren't the latest. When I downgrade, Spyder still takes on the 'latest version' and throws a warning, even though I've downgraded the dependencies.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-118-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.2 (NOK)
keyring                        :  None (OK)
nbconvert >=4.0                :  6.0.5 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.1 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.2 (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @ariane-er, thanks for reporting. You said:

> The versions of Jedi & Parso aren't the latest.

That's correct and it's by design, i.e. our 4.1.5 version doesn't work with the latest versions of Jedi and Parso.

> When I downgrade, Spyder still takes on the 'latest version' and throws a warning, even though I've downgraded the dependencies.

According to the list of dependencies you posted above, there's still a mismatch between the versions you have installed and those required by Spyder:

    jedi =0.17.1                   :  0.17.2 (NOK)
    parso =0.7.0                   :  0.7.1 (NOK)

So you need to run this command to fix your problem:

    conda install jedi=0.17.1 parso=0.7.0

**Comment by ariane-er** [comment]
Thanks Carlos. I did. However, I get this:

`conda install jedi=0.17.1 parso=0.7.0                                      ─╯

Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
`
If I look at my anaconda-navigator the correct package versions are installed as well. I'm at a loss as to why Spyder isn't picking up on them. 

I appreciate your swift response!

**Comment by ccordoba12** [comment]
> I'm at a loss as to why Spyder isn't picking up on them.

Ok, to find that out please go to the menu `View > Panes` and select the entry called `Internal console`. That will open a Python interpreter that runs the same Python versions as Spyder.

There please run these commands

    import jedi
    jedi.__file__

The last result will show you where that packages is installed.

**Comment by ariane-er** [comment]
Great trick! Here's the result I got. How can I make conda update those packages? I apologize if this is obvious, I'm rather new to conda and Spyder.

```
>>> import jedi
>>> jedi.__file__
'/home/ariane/.local/lib/python3.8/site-packages/jedi/__init__.py'

>>> import parso
>>> parso.__file__
'/home/ariane/.local/lib/python3.8/site-packages/parso/__init__.py'
```

**Comment by ccordoba12** [comment]
As I imagined, you installed those packages with `pip` and they are being picked up by Spyder over its conda counterparts. By simply removing this directory

    /home/ariane/.local/lib/python3.8

you'll fix this issue.

It's better for you remove it because keeping it could cause odd bugs either with Spyder or other packages in Anaconda.

**Comment by ariane-er** [comment]
That was it! It worked. Thank you so much :) Hope you have a great day.

**Comment by ccordoba12** [comment]
Glad it worked! Happy Spydering!
