### ISSUE TITLE
Feature enhancement: Keyboard shortcut to duplicate a line of code

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#13893]
Right now by pressing ctr+D we can delete a line
it would be great to have a Keyboard shortcut to duplicate a line as well.

**Comment by jnsebgosselin** [comment]
![image](https://user-images.githubusercontent.com/10170372/94725562-f9894f00-0329-11eb-93f7-a8961bf82c78.png)

**Comment by dalthviz** [comment]
Hi @seyeeet there is currently a way to do that as @jnsebgosselin's screenshot shows. Let us know if that is what you where looking for :)

**Comment by seyeeet** [comment]
Thank you, that is what I was looking for

**Comment by juliepierson** [comment]
Hi all, sorry to reopen this, but with version 6 of Spyder this feature seems to have disappeared ? I can't find any keyboard shortcuts to duplicate lines since I've upgraded Spyder. Thanks !

**Comment by ccordoba12** [comment]
@juliepierson, the shortcuts are still working (`Alt+Shift+Up/Down`) but the problem is that it's not possible to configure them in Preferences in Spyder 6.

That bug was reported before (see issue #22516) and we'll try to fix it in our 6.0.3 version, to be released in a few weeks.

**Comment by juliepierson** [comment]
Thanks for your answer, sorry I didn't see the new issue. I'll be waiting for the next release then :smile:
