### ISSUE TITLE
Outline explorer only populate its content after a file is changed on latest 4.x

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#13897]
## Problem Description

After PR #13109, the outline explorer populate its content only after a change is made to a file.

It would be great if the content of the outline explorer could be populated for all files that are open on startup.

![outline_explorer_populated](https://user-images.githubusercontent.com/10170372/94730448-3c9af080-0331-11eb-94bd-28fcf2766a29.gif)

## Versions

* Spyder version: 4.2.0.dev0 2b8b7f669
* Python version: 3.7.6 64-bit
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by dalthviz** [comment]
Thanks @jnsebgosselin for the feedback! @ccordoba12 @andfoy is there something that we can do here?

**Comment by andfoy** [comment]
Yes, we are aware of this bug, I think this is a problem with the LSP requests, which are being sent before the server is fully initialized. I can add a workaround on PR https://github.com/spyder-ide/spyder/pull/13885 as well

**Comment by andfoy** [comment]
@jnsebgosselin, do you have any further comments regarding the new outline explorer improvements?

**Comment by jnsebgosselin** [comment]
No, I think everything else is looking good. Thanks for the work you've done here. I'm glad that the OE was finally migrated to use the LSP, I think this is neat and I hope this will be easier to maintain too.

**Comment by andfoy** [comment]
Dwelling more into this subject, I think this issue is more related to PR https://github.com/spyder-ide/spyder/pull/13828

**Comment by ccordoba12** [comment]
> Dwelling more into this subject, I think this issue is more related to PR #13828, I don't know what @ccordoba12 thinks about it

Yeah, I think it is. I'll take a look at this problem in that PR.

@andfoy, please don't add a workaround for now (it shouldn't be necessary).

**Comment by ccordoba12** [comment]
> No, I think everything else is looking good. Thanks for the work you've done here. I'm glad that the OE was finally migrated to use the LSP, I think this is neat and I hope this will be easier to maintain too.

Yes, we think it's going to be much easier to maintain and extend.

**Comment by jnsebgosselin** [comment]
@ccordoba12 PR #13938 fixed the problem when **starting** Spyder, thank you very much!

However, the same problem is still present when **switching projects**.
