### ISSUE TITLE
Turning "Highlight current line" off breaks parenthesis matching highlighting

### ISSUE THREAD

**Issue by pkars** [spyder-ide/spyder#13908]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related) _Not console-related_
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/) _Not applicable, as I use miniconda._
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If _Highlight current line_ option is turned off, matching/unmatching parenthesis (brackets etc.) highlighting color keeps following the cursor when typing. See images below.

When typing inside autocompleted parenthesis, the green highlight is continuous:
![spyder-highlight-matching-autocomplete](https://user-images.githubusercontent.com/36196790/94891042-a9290300-0489-11eb-99b2-1510ff9ee0da.png)

When typing at a highlighted matched parenthesis, the green highlight follows:
![spyder-highlight-matching-follows](https://user-images.githubusercontent.com/36196790/94891059-b0e8a780-0489-11eb-882d-ac244820eaec.png)

Remove autocompleted parenthesis and start typing from the lone unmatched parenthesis, and the red highlight follows:
![spyder-highlight-unmatching](https://user-images.githubusercontent.com/36196790/94891051-ad552080-0489-11eb-8084-92d1ec5c7dfd.png)

The highlighting follows across linebreaks:
![spyder-highlight-linebreak](https://user-images.githubusercontent.com/36196790/94891632-47699880-048b-11eb-8ffc-f1d5501f69be.png)

Possibly related to #13666 and #13668.

### What steps reproduce the problem?

1. Reset Spyder settings
2. Toggle _Highlight current line_ off (Preferences -> Editor -> Display)
3. Open a new file
4. Type a parenthesis and anything else

### What is the expected output? What do you see instead?

Only the parenthesis should be highlighted.

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Ubuntu 18.04

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @pkars, thanks a lot for reporting! Although I was not aware of it, I verified this error (and also #13666 and #13668) were fixed as part of my work in pull request #13281.

The fix will be available in our 4.2.0 version, to be released the first week of November.
