### ISSUE TITLE
The updates in .py file are gone!!

### ISSUE THREAD

**Issue by opamuk** [spyder-ide/spyder#13924]
I have been working on a file that is  very important for me. This morning when I started spyder it gave an unusual message which I don't remember literally but it was saying something like that: The updates were not saved in the file, what do you want to do? There were three buttons like restore, discard and open. I have clicked on the restore button though I had no idea what it means. After spyder start, updates done in the last two days are gone!  As far as I understand it turned back to an autosave point of the file that is stored in autosave directory. Is there a way to fix? The version is Spyder 4.1.5. Please help

**Comment by steff456** [comment]
Hi @opamuk,

I'm really sorry to hear that you lost an important file. There's not much for us to do about it, please try to restore using your OS recovery utility, I really hope that you can recover that file.

I think we need to add more information to that dialog so this problem doesn't happen again. Thanks for reporting!

**Comment by OverLordGoldDragon** [comment]
Check the following folders; to search all python files, [search](https://user-images.githubusercontent.com/16495490/95598801-59d26c00-0a61-11eb-80de-74312fba670b.png) `**.py**`.

 - `C:\Users\<name>\.spyder-py3\autosave` 
 - `C:\Windows\Temp`
 - or [entire drive(s)](https://user-images.githubusercontent.com/16495490/95599114-b9c91280-0a61-11eb-89ea-4fd7d6afa6cd.png)

If nothing, try recovery, and try to install as few things as possible before it; when you delete normally, it isn't really "gone", just space is freed on disk - and installing (or writing in any way to disk) risks overwriting that space.

**Comment by opamuk** [comment]
I had to rewrite the code. Thanks anyway.
