### ISSUE TITLE
Let the user select his/her own localization settings

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1394]
_From [lio...@gmail.com](https://code.google.com/u/109282912794444035424/) on 2013-05-16T01:45:03Z_

Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.3, PyQt4 (API v2) 4.9.5 on Windows 

What steps will reproduce the problem?

 1. Open Spyder from the Python(x,y) icon on the desktop What is the expected output? What do you see instead? This localization thing is very annoying: The whole window is flipped right-to-left (see attached image). I'm using Windows 7, 64 bit, English version, but I have an alternative keyboard layout of Hebrew. The Windows localization settings are set to Israel. I would like to use the IDE without any translations, direction-flipping, etc. 

Please provide any additional information below

. See attached snapshot. This might be a QT issue, but I believe the IDE should no rely on the QT settings for scientific software, where the only valid language is English (and Python :)

**Attachment:** [Untitled.png](http://code.google.com/p/spyderlib/issues/detail?id=1394)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1394_

**Comment by spyder-issues-migrator** [comment]
_From [lio...@gmail.com](https://code.google.com/u/109282912794444035424/) on 2013-05-16T04:55:20Z_

Temporary solution is to add these two lines to c:\python27\scripts\xyhome.pyw:

import os
os.environ['lang']='en_us'

I really think there should be a way to ignore this environment variable from the IDE options menu.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-28T21:56:18Z_

Thanks for reporting. We'll what we can do about it. For now you'll have to use your own approach.

**Summary:** Let the user select his/her own localization settings  \<span class="oldvalue"> (was: The IDE is right-aligned, with no way of restoring regular left-alignment) \</span>  
  **Status:** Accepted  
  **Labels:** -Localization -RTL Cat-SpyderGUI MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-21T11:23:40Z_

We could add this facility to

    Preferences > General

by using a dropdown menu. There are only three possibilities: English, French and Spanish.

**Labels:** Easy

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-21T11:41:18Z_

issue #1806 has been merged into this issue.

**Comment by ccordoba12** [comment]
This was solved by PR #2349.
