### ISSUE TITLE
issue at starting kernel

### ISSUE THREAD

**Issue by Syed-FaizRaza** [spyder-ide/spyder#13944]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "e:\software\anaconda\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.29.17 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  2.2.2 (OK)

```

**Comment by dalthviz** [comment]
Hi @Syed-FaizRaza please update to our latest version of Spyder 3 (3.3.6). For that you can use something like `conda install spyder=3.3.6`. Also, be sure that you have the correct version of `numpy` installed and you are not mixing pip/conda packages in your env.

Hope the info above helps :)

**Comment by dalthviz** [comment]
Closing do to lack of response
