### ISSUE TITLE
Unable to open Spyder with Ubuntu

### ISSUE THREAD

**Issue by w142236** [spyder-ide/spyder#13945]
I installed Spyder into a virtualenv on Ubuntu using:

**Steps to get Problem**
1. `source venv/bin/activate`
2. `sudo pip3 install spyder` (which you are apparently never supposed to use sudo pip together ever) 
3. `spyder3`

I get the following errors each time:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-quit'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

I have read that the libGL error is often associated with an Nvidia graphics card [which I read here](https://askubuntu.com/questions/834254/steam-libgl-error-no-matching-fbconfigs-or-visuals-found-libgl-error-failed-t), but I ran the following to check for the problematic driver which would be caused by Nvidia:

sudo ldconfig -p | grep -i gl.so
which outputs:

    libwayland-egl.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libwayland-egl.so.1
    libcogl.so.20 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcogl.so.20
    libQt5OpenGL.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libQt5OpenGL.so.5
    libGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGL.so.1
    libEGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so.1

I did not find the nvidia driver amongst these. 
Maybe it's the case that one of these libs listed is the problematic one, or I do not have the lib that it wants to run Spyder?

**Comment by dalthviz** [comment]
Hi @w142236 seems like some sort of issue related with the driver of you graphics card and maybe is related with using `sudo` in the installation with pip, could you try to install Spyder in an env without using `sudo`? What happens if you run the `spyder3` command with `sudo` (`sudo spyder3`)?

In this kind of cases there is not much we can do but hopefully some of the info above helps :)

**Comment by w142236** [comment]
Thank you for getting back to me! I am tied up today. I will give that a try and get back to you on Friday afternoon on whether or not that worked.

**Comment by texadactyl** [comment]
Without sudo, Spyder works well in an active venv environment:
spyder                        4.1.5
spyder-kernels                1.9.4

My environment: Xubuntu 20.10-beta.

**Comment by w142236** [comment]
> 
> 
> Without sudo, Spyder works well in an active venv environment:
> spyder 4.1.5
> spyder-kernels 1.9.4
> 
> My environment: Xubuntu 20.10-beta.

What do you mean "without sudo"? Using sudo to install spyder or running `sudo spyder3` to open it?

**Comment by w142236** [comment]
> 
> 
> I did not use `sudo` to install spyder.
> This command was used:
> `pip install spyder`

I went ahead installed spyder in a new virtualenv using what you suggested.
`virtualenv venvspyder`
`source venvspyder/bin/activate`
`pip install spyder`
`spyder3`

I still get the same issue:
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-quit'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

Maybe how it was installed, whether using sudo or pip, wasn't the issue?

**Comment by texadactyl** [comment]
I installed venv this way:
```sudo apt install venv```
How did you install venv?

**Comment by texadactyl** [comment]
```dpkg -L python3-venv```
/.
/usr
/usr/bin
/usr/share
/usr/share/doc
/usr/share/man
/usr/share/man/man1
/usr/bin/pyvenv
/usr/share/doc/python3-venv
/usr/share/man/man1/pyvenv.1.gz

**Comment by texadactyl** [comment]
Previously, I explained how I installed spyder in a venv environment in a piecemeal fashion.  So, I repeated what I did in its entirety in the interest of clarity:

```
# Start fresh:
sudo apt purge python3-venv 
sudo apt autoclean
sudo apt autorermove

# Ground up install of venv:
sudo apt install python3-venv
cd; cd Downloads
python3 -m venv venvspyder
cd venvspyder
source bin/activate

# Install Spyder using pip3
pip install spyder # pip=pip3
which spyder3
     #>>> $HOME/Downloads/venvspyder/bin/spyder3
spyder3 # successfully launches Spyder
```

I do not know what "virtualenv" is that you used but it has nothing to do with venv.  Maybe you mixed 2 different tools?

**Comment by w142236** [comment]
Thank you for getting back to me.
I decided to do a fresh uninstall and reinstall of ubuntu to clean everything out and ran the following:

`sudo apt-get -y upgrade`
`sudo apt-get -y update `
`sudo apt install python3-venv `
`python3 -m venv venvspyder`
`cd venvspyder`
`source bin/activate `
`pip install spyder `
Then I got errors involving building wheels so I control-C'd out of the install and ran:
`pip install wheel`
`pip install spyder`
Got an error for psutil and control-C'd out of install again and ran:
`sudo apt-get install python3.8-dev -y`
`pip install psutil`
`pip install spyder`
And it installed without any errors.
I then ran: `spyder3`
And got the following:
Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder
Traceback (most recent call last):
  File "/home/quit/venvspyder/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libsmime3.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/quit/venvspyder/bin/spyder3", line 8, in <module>
    sys.exit(main())
  File "/home/quit/venvspyder/lib/python3.8/site-packages/spyder/app/start.py", line 200, in main
    from spyder.app import mainwindow
  File "/home/quit/venvspyder/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 84, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/quit/venvspyder/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

Do I simply install the missing module while inside the venv, or does this issue require additional steps to solve?

**Comment by ccordoba12** [comment]
@w142236, are you trying to install Spyder in a Docker instance or something? I mention it because it doesn't seem you have the minimal deb packages to run it.

**Comment by w142236** [comment]
> 
> 
> @w142236, are you trying to install Spyder in a Docker instance or something? I mention it because it doesn't seem you have the minimal deb packages to run it.

I don't understand what that means. I installed it as an app off the Microsoft Store if that helps to answer your question. Otherwise I'm not sure. Sorry!

**Comment by ccordoba12** [comment]
> I installed it as an app off the Microsoft Store if that helps to answer your question

@w142236, you should have clarified that from the start. Running Ubuntu through the WSL is very different from a regular installation. That seems to give you a version runs in the command line, not one that can run graphical applications.

Unfortunately, we don't have any experience doing that. So we can offer you further support for your use case, sorry.

**Comment by w142236** [comment]
> 
> 
> > I installed it as an app off the Microsoft Store if that helps to answer your question
> 
> @w142236, you should have clarified that from the start. Running Ubuntu through the WSL is very different from a regular installation. That seems to give you a version that runs in the command line, not one that can run graphical applications (such as Spyder).
> 
> Unfortunately, we don't have any experience doing that. So we can't offer you further support for your use case, sorry.

So is the OS the issue? Would this only work on a Linux computer?

**Comment by dalthviz** [comment]
@w142236 maybe this could be useful for your use case: https://techcommunity.microsoft.com/t5/windows-dev-appconsult/running-wsl-gui-apps-on-windows-10/ba-p/1493242 (not totally sure if something there will help to launch Spyder without issue in your WSL Ubuntu instance but let us know if something there helps :) )

**Comment by ccordoba12** [comment]
Sorry @w142236, what I meant is that we don't know how to install Spyder in WSL. So we can't help you with that.

**Comment by jogareau** [comment]
Hello @w142236 , not sure if this is too late, but I had similar issues recently when installing Spyder on WSL Ubuntu. The only way I got it to work was through anaconda3. So install anaconda 3 for linux and Spyder will be installed automatically as a package. Then you only type spyder as a command, or you can create environments as well.

**Comment by dalthviz** [comment]
Also, just in case fro wsl/wsl2, we have some docs regarding the usage of Spyder with wsl2 instances here: https://docs.spyder-ide.org/current/faq.html?highlight=run%20cell#install-wsl2 (not installing Spyder itself in the wsl2 instance but connecting to a remote kernel started there from you host on Windows)

**Comment by texadactyl** [comment]
Xubuntu (ubuntu base + XFCE) 21.10

```python3 -m pip install spyder``` works fine.  No need for anaconda or miniconda.

**Comment by therebele** [comment]
> Also, just in case fro wsl/wsl2, we have some docs regarding the usage of Spyder with wsl2 instances here: https://docs.spyder-ide.org/current/faq.html?highlight=run%20cell#install-wsl2 (not installing Spyder itself in the wsl2 instance but connecting to a remote kernel started there from you host on Windows)


Can verify this works on WSL1 Ubuntu 20.04 with 
spyder 5.3.3           
spyder-kernels  2.3.3
