### ISSUE TITLE
Spyder 4 editor is slow

### ISSUE THREAD

**Issue by maxyar12** [spyder-ide/spyder#13946]
Hi,

  I have been working on Spyder 4.x including 4.1.5 for the last month. The editor is extremely laggy and slow. The following actions are slow:

 - typing anything is very slow. I can type a letter on my keyboard and then it will take 1 second to appear in the editor
- I can click somewhere and it will take about 1 second for the cursor to appear at the right spot

My machine is a modern windows 10 PC with a decent processor and 8GB of memory. This occurs with no other application open.

Furthermore, when I dowgraded to spyder 3.3.5 there are no responsiveness issues, so it is clearly a bug in Spyder 4.

By the way,,I have tried turning off every single setting in the tools -> preferences -> editor

literally turning off every single preference that might affect performance... nothing helps

Is anyone else experiencing this? 

This is reproducible particularly when opening multiple files of codes...

**Comment by ccordoba12** [comment]
Hey @maxyar12, thanks for reporting. We are aware of this problem (see for instance issues #13020 and #8864, and especially PR #13864). Unfortunately, the many improvements to the editor in Spyder 4 were not very well tested for many or large files.

Right now we're working very hard to solve all the bottlenecks we've detected. Hopefully, things will be greatly improved in our next version (4.2), to be released at the beginning of November).

**Comment by jmoraispk** [comment]
@ccordoba12, I still detect this slowness for large files. Is this something still in the works for upcoming versions?

**Comment by ccordoba12** [comment]
Yeah, that's still a problem for large files. To fix that we need to do a big refactoring in the editor, which is planned for the second half of this year.

**Comment by jmoraispk** [comment]
Alright. I thought the problem was as simple as introducing a 'code linting interval' in the preferences such that the whole file wouldn't be checked for errors so often, but it may be more complex than that. Anyways, great news, thank you!
