### ISSUE TITLE
Missing dependcies

### ISSUE THREAD

**Issue by SuperDim666** [spyder-ide/spyder#13955]
### What steps will reproduce the problem?

I got a problem when starting spyder each time.
It tole me that I missed dependencies of parso 0.7.0==0.8.0 since I have installed parso of 0.8.0 for updating it by using "pip install --upgrade" in the conda powershell. In fact, the parso is the latest version whereas the spyder still makes the wrong message to me. Does the current version of spyder not support the latest version of Parso 0.8.0?? Please solve the issue as soon as possible.
My email address: 12501015753@qq.com for contacting, Thank you!

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.15.1
* PyQt5 version: 5.15.1
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.8.0 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @SuperDim666, thanks for reporting. You said:

> In fact, the parso is the latest version whereas the spyder still makes the wrong message to me. Does the current version of spyder not support the latest version of Parso 0.8.0??

No, it doesn't. Spyder only supports Parso 0.7.0.

> It tole me that I missed dependencies of parso 0.7.0==0.8.0 since I have installed parso of 0.8.0 for updating it by using "pip install --upgrade" in the conda powershell.

By doing that, you most probably broke your Anaconda installation and now you have to reinstall it. That's because conda and pip packages are incompatible.

Please see [out video](https://www.youtube.com/watch?v=Ul79ihg41Rs) on how to do that correctly.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
