### ISSUE TITLE
Markdown emojis not supported

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#13956]
### What steps will reproduce the problem?

Markdown emojis are currently not supported, and they don't appear as expected.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ma-sadeghi** [comment]
# Spyder
![image](https://user-images.githubusercontent.com/14086031/95587167-b2791900-0a0f-11eb-9ffe-f5cf3aac9ba3.png)

# Sublime Text 3
![image](https://user-images.githubusercontent.com/14086031/95587200-befd7180-0a0f-11eb-8c0d-900fc3b8f26c.png)

**Comment by ccordoba12** [comment]
Hey @ma-sadeghi, thanks for reporting. Quick question: was your file saved as utf-8?

**Comment by ma-sadeghi** [comment]
> Hey @ma-sadeghi, thanks for reporting. Quick question: was your file saved as utf-8?

How can I check? I'm using Windows btw.

**Comment by ccordoba12** [comment]
That's displayed in the status bar at the bottom:

![Selección_020](https://user-images.githubusercontent.com/365293/95598387-7943a780-0a15-11eb-9bc7-85ba9ba59602.png)

**Comment by ma-sadeghi** [comment]
Thanks, it's WINDOWS-1254

**Comment by ccordoba12** [comment]
I think that's the problem. Could you create a new file in Spyder, paste your emoji there and save it? On that case you should't see any error.

**Comment by ma-sadeghi** [comment]
That's right, it works with utf-8. So, I'm closing this. Btw, how does Sublime Text render the same file?

**Comment by ccordoba12** [comment]
I have no idea, sorry.
