### ISSUE TITLE
Replace with | replace/find next | replace in selection | replace all

### ISSUE THREAD

**Issue by mvillion** [spyder-ide/spyder#13957]
Hello!

The four "replace" in the replace box take too much space and force the editor to resize over 80 columns.

Replacing them with: "Replace w/", "/find next", "in selection" and "all" would save some space.
That would also enable to increase the size of the "replace string" QLineEdit which currently allows to display only the first 3 characters of the replacement string.
?
Thank you

**Comment by TediaN97** [comment]
i would like if u assign me on this issue

**Comment by juanis2112** [comment]
Hi @mvillion this is a good point. Thanks for reporting this. I think we should not change the "Replace with" one but the other 3, we could change them for "Find next", "In selection", "All". What is your thought on this @ccordoba12 ?

@TediaN97 thanks for offering to solve this. Once @ccordoba12 approves these changes, I'll assign you to this issue!

**Comment by juanis2112** [comment]
FYI here is a screenshot of that box.
![Uploading Screenshot 2020-10-09 at 1.41.02 PM.png…]()

**Comment by juanis2112** [comment]
Here is a screenshot of the current replace box:
<img width="725" alt="Screenshot 2020-10-09 at 1 43 55 PM" src="https://user-images.githubusercontent.com/18587879/95620241-7b1d6300-0a35-11eb-92f1-6f54098adb4e.png">

**Comment by ccordoba12** [comment]
> What is your thought on this @ccordoba12 ?

I agree, that's a very good suggestion @juanis2112! Let's implement those changes!

> @TediaN97 thanks for offering to solve this

Yeah, thanks a lot for that! Please don't forget to read our [Contributing guide](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md) before getting started.
