### ISSUE TITLE
memory error   

### ISSUE THREAD

**Issue by Nasseer125** [spyder-ide/spyder#13969]
### What steps will reproduce the problem?

---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
~\Anaconda3\envs\PythonGPU\lib\site-packages\IPython\core\formatters.py in __call__(self, obj)
    339                 pass
    340             else:
--> 341                 return printer(obj)
    342             # Finally look for special method names
    343             method = get_real_method(obj, self.print_method)

~\Anaconda3\envs\PythonGPU\lib\site-packages\IPython\core\pylabtools.py in <lambda>(fig)
    246 
    247     if 'png' in formats:
--> 248         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    249     if 'retina' in formats or 'png2x' in formats:
    250         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~\Anaconda3\envs\PythonGPU\lib\site-packages\IPython\core\pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    130         FigureCanvasBase(fig)
    131 
--> 132     fig.canvas.print_figure(bytes_io, **kw)
    133     data = bytes_io.getvalue()
    134     if fmt == 'svg':

~\Anaconda3\envs\PythonGPU\lib\site-packages\matplotlib\backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, bbox_inches, **kwargs)
   2089                     orientation=orientation,
   2090                     bbox_inches_restore=_bbox_inches_restore,
-> 2091                     **kwargs)
   2092             finally:
   2093                 if bbox_inches and restore_bbox:

~\Anaconda3\envs\PythonGPU\lib\site-packages\matplotlib\backends\backend_agg.py in print_png(self, filename_or_obj, metadata, pil_kwargs, *args, **kwargs)
    525 
    526         else:
--> 527             FigureCanvasAgg.draw(self)
    528             renderer = self.get_renderer()
    529             with cbook._setattr_cm(renderer, dpi=self.figure.dpi), \

~\Anaconda3\envs\PythonGPU\lib\site-packages\matplotlib\backends\backend_agg.py in draw(self)
    384         Draw the figure using the renderer.
    385         """
--> 386         self.renderer = self.get_renderer(cleared=True)
    387         with RendererAgg.lock:
    388             self.figure.draw(self.renderer)

~\Anaconda3\envs\PythonGPU\lib\site-packages\matplotlib\backends\backend_agg.py in get_renderer(self, cleared)
    397                           and getattr(self, "_lastKey", None) == key)
    398         if not reuse_renderer:
--> 399             self.renderer = RendererAgg(w, h, self.figure.dpi)
    400             self._lastKey = key
    401         elif cleared:

~\Anaconda3\envs\PythonGPU\lib\site-packages\matplotlib\backends\backend_agg.py in __init__(self, width, height, dpi)
     84         self.width = width
     85         self.height = height
---> 86         self._renderer = _RendererAgg(int(width), int(height), dpi)
     87         self._filter_renderers = []
     88 

MemoryError: In RendererAgg: Out of memory

### Traceback
```python-traceback
  File "C:\Users\Worou Nassirou\Anaconda3\envs\PythonGPU\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 417, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\Users\Worou Nassirou\Anaconda3\envs\PythonGPU\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 861, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\Users\Worou Nassirou\Anaconda3\envs\PythonGPU\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 935, in set_current_thumbnail
    thumbnail.canvas.fig, thumbnail.canvas.fmt)
  File "C:\Users\Worou Nassirou\Anaconda3\envs\PythonGPU\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 522, in load_figure
    self.scale_image()
  File "C:\Users\Worou Nassirou\Anaconda3\envs\PythonGPU\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 629, in scale_image
    self.sig_zoom_changed.emit(self.get_scaling())
  File "C:\Users\Worou Nassirou\Anaconda3\envs\PythonGPU\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 633, in get_scaling
    return round(self.figcanvas.width() / self.figcanvas.fwidth * 100)
ZeroDivisionError: division by zero
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  None (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.1 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.15.4 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.1.0 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @Nasseer125, thanks for reporting. This problem should be fixed in our latest version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.1.5

**Comment by ccordoba12** [comment]
Closing due to lack of response.
