### ISSUE TITLE
Cannot connect variable explorer to remote kernel

### ISSUE THREAD

**Issue by sama2689** [spyder-ide/spyder#13966]
I am trying to remote connect into a linux system running python 3.7.7, from a windows system running spyder in a python 3.7.7 environment.
I am able to connect successfully, however the variable explorer is completely empty for any code I run in the new kernel. 

I have tried the steps outlined [here](https://stackoverflow.com/questions/55354020/spyder-variable-explorer-does-not-show-variable-for-connected-remote-kernel) but they don't work for me and the variable explorer remains empty. Not even the 'show environment variables' option from the drop-down menu does anything.

I have also tried re-starting spyder and anaconda on both machine with no luck. Is there some way to get variable explorer to work with remote connections or will I have to just use to console without being able to see variables update?

**Comment by ccordoba12** [comment]
Hey @sama2689, thanks for reporting. This is duplicate of issue #11538.
