### ISSUE TITLE
PYTHONPATH not set when running profiler

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#13964]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
It seems like the PYTHONPATH set in Spyder is not used when profiling. This causes a bit of issues if one is profiling library code. 

Except for the behavior not being as expected, the following code:
``` python
import os
try:
    user_paths = os.environ['PYTHONPATH'].split(os.pathsep)
except KeyError:
    user_paths = []
print(user_paths)
```
results in `[]` in the profiler output (despite PYTHONPATH being non-empty in the dialog).

Maybe related to: #12564 #9388 #3161 (I commented there as well, but not sure it is the same problem).

### What steps reproduce the problem?

1. Add a module to PYTHONPATH in the Spyder dialog
2. Profile code that relies on that module

### What is the expected output? What do you see instead?
That the PYTHONPATH is set in the profiler.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.1.5 and 5.0.0.dev0 62e0dfe
* Python version: 3.7.9 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0        :  1.4.0 (OK)
chardet >=2.0.0             :  3.0.4 (OK)
cloudpickle >=0.5.0         :  1.6.0 (OK)
cookiecutter >=1.6.0        :  1.7.2 (OK)
diff_match_patch >=20181111 :  20200713 (OK)
intervaltree                :  None (OK)
IPython >=4.0               :  7.18.1 (OK)
jedi =0.17.2                :  0.17.2 (OK)
nbconvert >=4.0             :  6.0.7 (OK)
numpydoc >=0.6.0            :  1.1.0 (OK)
paramiko >=2.4.0            :  2.7.2 (OK)
parso =0.7.0                :  0.7.0 (OK)
pexpect >=4.4.0             :  4.8.0 (OK)
pickleshare >=0.4           :  0.7.5 (OK)
psutil >=5.3                :  5.7.2 (OK)
pygments >=2.0              :  2.7.1 (OK)
pylint >=1.0                :  2.6.0 (OK)
pyls >=0.35.0;<1.0.0        :  v4.0.0b2+5278.g62e0dfe (OK)
qdarkstyle >=2.8            :  2.8.1 (OK)
qtawesome >=0.5.7           :  1.0.1 (OK)
qtconsole >=4.7.7           :  4.7.7 (OK)
qtpy >=1.5.0                :  1.9.0 (OK)
rtree >=0.8.3               :  0.9.4 (OK)
sphinx >=0.6.6              :  3.2.1 (OK)
spyder_kernels >=2.0.0dev0  :  2.0.0.dev0 (OK)
watchdog                    :  None (OK)
zmq >=17                    :  19.0.2 (OK)

# Optional:
cython >=0.21               :  0.29.21 (OK)
matplotlib >=2.0.0          :  3.3.1 (OK)
numpy >=1.7                 :  1.19.1 (OK)
pandas >=1.1.1              :  1.1.3 (OK)
scipy >=0.17.0              :  1.5.2 (OK)
sympy >=0.7.3               :  1.8.dev (OK)

```

**Comment by oscargus** [comment]
I can confirm that, not surprisingly, the problem exists on my Linux machine as well.

**Comment by ccordoba12** [comment]
Hey @oscargus, thanks for reporting. I know what's happening in this case and we'll fix the underlying problem in our next version (4.2.0) to be released in November.

For now, I think you can avoid it by dropping `PYTHONPATH` from the terminal where you plan to start Spyder.

**Comment by pj1989** [comment]
Is it possible that this issue is still present in 4.2.0?

Profiling a very minimal example as
```
import xlrd
```
results in

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 185, in <module>
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 178, in main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 20, in runctx
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\profile.py", line 62, in runctx
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\cProfile.py", line 100, in runctx
  File "C:/Users/<user-name>/Desktop/deleteme.py", line 8, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'
```

obviously the code runs fine when executed either in Spyder console or outside Spyder completely.

**Comment by ccordoba12** [comment]
I think that's not the same error and this one is caused because we're not using the same Python interpreter set in

    Preferences > Main interpreter

to run the profiler. We're aware of that limitation and will try to fix it in a future release.

**Comment by pj1989** [comment]
Is there any workaround in 4.2.0 to profile a code using non-standard packages?
Which interpreter is the profiler using?

**Comment by ccordoba12** [comment]
No, there's no workaround and the profiler is using the same interpreter that Spyder is running on.
