### ISSUE TITLE
Linter dies and won't revive without reopening file

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#13961]
[demo.mp4](https://puu.sh/GBWjz/8fe9397775.mp4). Happens time-to-time, not really a bother since fix is trivial, but I never tried resetting the language server before, and that didn't help - figured I'd report.

**Comment by ccordoba12** [comment]
Thanks for reporting @OverLordGoldDragon. However, you know the only way we can fix this is with a reproducible use case.

Until you find one, there's nothing we can do about it.

**Comment by OverLordGoldDragon** [comment]
Seems resolved
