### ISSUE TITLE
Spyder 4.1.5 won't launch in any of my anaconda environments

### ISSUE THREAD

**Issue by NasonZ** [spyder-ide/spyder#13983]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Open anaconda 
2. Launch by clicking Spyder 4.1.5
3. Wait til infinity for IDE to launch 

### What is the expected output? What do you see instead?
I expect the IDE to launch as usual. Instead, I can see the icon on the taskbar but the IDE itself doesn't appear.
I can get spyder working if I downgrade to version 3.x.x but this is not ideal 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @NasonZ could you try to run Spyder from the console/terminal and check if any traceback is generated? (you can run Spyder typing `spyder` in an Anaconda prompt). Maybe our [Troubleshooting guide](https://docs.spyder-ide.org/current/first-steps.html) could be useful. 

Without more information there isn't much we can do about this, sorry :/

**Comment by NasonZ** [comment]
@dalthviz Hey Dal, I ran spyder from anaconda terminal but I still get the same behavior in all environments, unfortunately there's no error code given as the IDE seems to be stuck loading. Hovering my cursor over the spyder icon on the taskbar shows a blank white window.

**Comment by dalthviz** [comment]
Um did you use a second screen in the past by any chance? could you try to check if using the Win key + arrow keys helps you show Spyder?

**Comment by NasonZ** [comment]
Nope just one screen, I've tried the window arrow key but nothing happens. Any other suggestions?

**Comment by dalthviz** [comment]
Could you try to reset your Spyder preferences? You can run something like `spyder --reset` from the Anaconda prompt to do it

**Comment by dalthviz** [comment]
Closing due to lack of response
