### ISSUE TITLE
Performance is really bad when Kite engine not running.

### ISSUE THREAD

**Issue by johnh865** [spyder-ide/spyder#13990]
### What steps will reproduce the problem?

After Kite integration and version 4, performance is very slow when you don't use Kite. Also, the Kite popup is really annoying and I'm not sure how to get rid of the popup when Spyder starts. 

Reproduce by:

Go to:

Preferences -> Advanced -> Enable Kite -> Uncheck. 

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @johnh865, sorry to hear that. Some questions for you:

> After Kite integration and version 4, performance is very slow when you don't use Kite

What performance are you specifically talking about?

> Also, the Kite popup is really annoying and I'm not sure how to get rid of the popup when Spyder starts.

What pop up are referring to? Please be more specific by uploading a screenshot.

**Comment by johnh865** [comment]
Carlos,

I get very noticeable "lag" whenever I am just typing code or press enter
to make a new line when Kite is disabled. When Kite is re-enabled (which I
started doing after I read I think an earlier solution for this lag), the
"lag" disappears. I have been having this issue since the first Spyder 4
release. I decided to report after I updated to the latest Spyder version
this week.

I am talking about this Kite popup:

[image: image.png]

This popup shows up every time I run Spyder with Kite enabled.

(20 minutes later after playing around with Spyder trying to reproduce the
issue)
Very strange... I tried to reproduce this error and today it's finally
stopped, after I clicked some options in preferences & in this popup. The
popup I screenshotted above had been popping up for the last couple of
weeks/months but now it has finally stopped coming back up, and I can't
reproduce the "lag" issue anymore... That's funny because I've reproduced
this "lag" after multiple uninstalls and reinstalls of Spyder. I will try
to uninstall and reinstall Spyder later today to see if I can get the issue
to come back.

Thanks for your reply.

John Huang

**Comment by ccordoba12** [comment]
> I get very noticeable "lag" whenever I am just typing code or press enter
to make a new line when Kite is disabled

This will be fixed in our next version (4.2.0) to be released the first week of November.

> I am talking about this Kite popup:

You can't send images via email. Please upload it here directly by dragging and dropping it in this text field.

**Comment by johnh865** [comment]
![0](https://user-images.githubusercontent.com/44849700/96178634-43129600-0ef5-11eb-9f82-c2f388b9db50.png)


Carlos, this is the image. After fiddling around with some preferences, uninstalling Anaconda, and reinstalling Spyder, this popup no longer shows up so I guess it is no longer an issue and I cannot reproduce.

**Comment by ccordoba12** [comment]
No problem. Glad you were able to solve that annoyance.
