### ISSUE TITLE
'cerr' output multiplied with multiple clicks of 'Run'.

### ISSUE THREAD

**Issue by luciansmith** [spyder-ide/spyder#13991]
## Problem Description

This might be related to https://github.com/spyder-ide/spyder/issues/9759

I sent an email to the list, but nobody had any insights there:  https://groups.google.com/g/spyderlib/c/2BUb4dVGpaM/m/3ATuq_9oAwAJ

Basically, the problem is that our library will send warning messages to cout via the poco library.  In a console, we get the same behavior whether typing in the Spyder console, in a Jupyter console, or just running 'python' from the command line.  Namely:  the first time we run something that reports a warning, we see it, and after that we don't see anything.

But when we hit 'Run', we see it the first time, and then the next time, we see *two* copies of it, then three, etc.

### What steps reproduce the problem?

pip install tellurium

Create the following program:

import tellurium as te
te.loada("species a")

Hit 'Run'
Hit 'Run'
Hit 'Run'

### What is the expected output? What do you see instead?
Expected output:  The first 'Run':
```
Warning: species 'a' has neither initial amount nor concentration set.  Setting initial concentration to 0.0
```
Subsequent 'Run's should either produce that one line again or nothing at all--nothing at all is what we see when typing the program in at the prompts directly.

Observed output:
The expected output on the first 'Run', but by the third 'Run':
```
Warning: species 'a' has neither initial amount nor concentration set.  Setting initial concentration to 0.0
Warning: species 'a' has neither initial amount nor concentration set.  Setting initial concentration to 0.0
Warning: species 'a' has neither initial amount nor concentration set.  Setting initial concentration to 0.0
```
For what it's worth, I see the next prompt (i.e. 'In [3]') before the warnings are added *above* the prompt.

## Versions
* Spyder version: 4.1.5 None
* Python version: 3.7.3 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by impact27** [comment]
I think what is happening is that we save cerr to a file, and print the file if it is modified. So we should:
 - Do the same with cout, because something could be written there
 - Fix this issue by only printing the new lines, not the entire file

**Comment by luciansmith** [comment]
Oh, that sounds promising.  I should say that I could be wrong about what Poco pipes these messages to--it could already be cerr.  If the whole cerr file is being printed every time, that would certainly explain the phenomenon I'm seeing.  Thank you!

**Comment by luciansmith** [comment]
(If the only point of the cerr/cout file is to display to the user, you could always delete it after displaying it.  Is there anyone who needs 'all the cerr output' for something if it's been printed to the screen already?)
