### ISSUE TITLE
Python Path Manager paths are not added to sys.path for external Consoles in the macOS app

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#14042]
## Problem Description
Spyder's Python paths listed in Python Path Manager are not transferred to `sys.path` for external IPython consoles running in the macOS application. This is true for both conda or venv environments, and does not affect bootstrapping or "Same as Spyder" consoles in the macOS app.

See https://github.com/spyder-ide/spyder/pull/14033#issuecomment-714763834

@ccordoba12 , please assign to me.

**Comment by mrclary** [comment]
Okay, this is a non-issue. The external console environments I was testing were using spyder-kernels=1.9.4, not the latest in the subrepo. When I installed external-deps/spyder-kernels in the external environments, everything worked just fine.
We'll just have to ensure our users remember to update spyder-kernels in their external environments when updating Spyder.

This does raise a question: is it possible to have the external console use the same spyder-kernels as Spyder?
We already do this when bootstrapping by adding the `external-deps` path to the `PYTHONPATH`, which is exactly why this issue didn't manifest in this situation.

If we were able to use a single installation for spyder-kernels, then users wouldn't have to install it in any of their external environments. This would be *very* convenient.
I think the real problem would be accessing spyder-kernels' dependencies without exposing Spyder's environment packages or polluting the console's sys.path...

Anyway, just a thought.

**Comment by ccordoba12** [comment]
> If we were able to use a single installation for spyder-kernels, then users wouldn't have to install it in any of their external environments. This would be very convenient.

Adding our spyder-kernels subrepo to PYTHONPATH is convenient for development, but you also need things like `cloudpickle` and `pyzmq` to run our kernel. Should we add them and their dependencies to PYTHONPATH too?

I think you're aware of the perils of mixing packages from two Python installations and that's what we'd end up doing with that approach. So the cleanest and safest way is to have a separate, small package (i.e. spyder-kernels) that you can install in your environments to have a single Spyder installation that can run code in any of them.
