### ISSUE TITLE
important(kernel not run)

### ISSUE THREAD

**Issue by elif34ist** [spyder-ide/spyder#14050]
### What steps will reproduce the problem?

restarting kernel error
runfile error
kernel not run

## Versions

* Spyder version: 4.1.5 
* Python version: 3.9.0
* Qt version: 5.15.1
* PyQt5 version: 5.15.1
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @elif34ist, thanks for reporting. Could you give us more details about your problem?

Under what conditions the kernel is not running?

**Comment by elif34ist** [comment]
I am writing any code. But the spyder console constantly gives a restarting kernel warning and doesn't run the code. When I try to run a file it gives a runfile warning.
However I don't think this is pc related. Because python is running at the command prompt. Likewise idle works too. The problem may be caused by the spyder terminal. But I could not find out why.

**Comment by ccordoba12** [comment]
> When I try to run a file it gives a runfile warning.

This is not a warning. It's the command used by Spyder to run your code. If you are only seeing a text containing `runfile` in the console, it's because you're not printing anything in your file.

For instance, the following code should show `16` as a result in the console:

```python
def square(x):
    return x ** 2

print(square(4))
```

**Comment by elif34ist** [comment]
You are right, I used the wrong word. For example, when I open the spyder to write your code, it gave a direct restarting kernel warning. Then I wrote the code, it said runfile. Then it went into the restarting kernel loop again. Actually, the problem is that the restarting kernel always comes out and the code doesn't work.

**Comment by ccordoba12** [comment]
> Python version: 3.9.0
Qt version: 5.15.1
PyQt5 version: 5.15.1

Ok, it seems you're trying to use Spyder with Python 3.9, something we haven't tested yet. And on top of that, you're using Qt/PyQt versions we don't support yet.

So our recommendation is for you to remove your current Python installation and install Anaconda instead. If you don't want to do that, at least reinstall using Python 3.8, which is known to work with Spyder.

**Comment by elif34ist** [comment]
I also installed Anaconda and encountered the same error, even though I tried the old versions, it was giving an error.
So can I try version 3.8? Would there be any downsides to using the old version for me?
Have version 3.8 been tested and is it supported?
By the way, thank you for helping.

**Comment by ccordoba12** [comment]
> I also installed Anaconda and encountered the same error, even though I tried the old versions, it was giving an error.

Does the kernel restart automatically after trying to run any code too?

> So can I try version 3.8? Would there be any downsides to using the old version for me?

No, there shouldn't be any downsides.

> Have version 3.8 been tested and is it supported?

Yes, it's supported.

> By the way, thank you for helping.

No problem.

**Comment by elif34ist** [comment]
And what version do you recommend downloading for anaconda?
Or which one should I download from the old version of spyder?

**Comment by elif34ist** [comment]
> Herhangi bir kod çalıştırmayı denedikten sonra çekirdek de otomatik olarak yeniden başlatılıyor mu?

Evet sürekli yeniden başlatıyor.

**Comment by ccordoba12** [comment]
And did you install Python 3.9 already?

**Comment by elif34ist** [comment]
> And did you install Python 3.9 already?

Since I use this program with my school now, I have to download Winpython or Anaconda, which includes all libraries.

**Comment by ccordoba12** [comment]
Ok, please open the Anaconda Prompt, run there

    python -m spyder_kernels.console

and report back any errors or messages you see there.

**Comment by MatParr** [comment]
> > When I try to run a file it gives a runfile warning.
> 
> This is not a warning. It's the command used by Spyder to run your code. If you are only seeing a text containing `runfile` in the console, it's because you're not printing anything in your file.
> 
> For instance, the following code should show `16` as a result in the console:
> 
> ```python
> def square(x):
>     return x ** 2
> 
> print(square(4))
> ```
Hi @[ccordoba12](https://github.com/ccordoba12),

In reference to your quote about, Can you elaborate on this for multi function processing, please?
I have load of print statements and nothing is being printed as it did efficiently before I upgraded to python 3.9.11 and IPython 8.1.1. 

I am constantly getting this error below and no matter what I do I cannot seem to get pass this! can you assist here, please?
`runfile('/Users/symbadian/opt/3DCNNtesting/packages.ipy', wdir='/Users/symbadian/opt/3DCNNtesting')
[TerminalIPythonApp] WARNING | Unrecognized alias: 'batch', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'epoch', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'videos', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'nclass', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'output', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'color', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'skip', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'depth', it will have no effect.`

**Comment by ccordoba12** [comment]
IPython 8 is not yet supported by us. Please downgrade to 7.32.0

**Comment by MatParr** [comment]
Ahhh I see thanks

Cheer to positive perspectives!

Matt.
________________________________

**Comment by MatParr** [comment]
> IPython 8 is not yet supported by us. Please downgrade to 7.32.0

Hey @ccordoba12, would these issues be a result of having a new mac? just upgraded to get more processing power and was faced with those challenges:

See the versions at the top of the errors, I wrote it out in the previous communication but i would like for you to see how the error actually is from the spyder console:

Thanx so much in advance pal, really appreciate this as I have been googling since 5am searching for a solution.

'''
Python 3.9.11 (main, Mar 29 2022, 14:04:42) 
Type "copyright", "credits" or "license" for more information.

IPython 8.1.1 -- An enhanced Interactive Python.

runfile('/Users/symbadian/opt/3DCNNtesting/packages.ipy', wdir='/Users/symbadian/opt/3DCNNtesting')
[TerminalIPythonApp] WARNING | Unrecognized alias: 'batch', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'epoch', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'videos', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'nclass', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'output', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'color', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'skip', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'depth', it will have no effect.


'''
