### ISSUE TITLE
Spyder crashes when I try to save the file

### ISSUE THREAD

**Issue by SadhviV** [spyder-ide/spyder#14066]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @SadhviV, thanks for reporting. Could you elaborate more and let us now what is the crash you're seen? Otherwise we won't be able to help you.

**Comment by SadhviV** [comment]
Hello,

Spyder crashes whenever I try to save a new file in anaconda. The only file
I am able to use and save is the default temp.py file which is there
already when I open spyder.
Anaconda navigator : 2020.07
Spyder : 4.1.4
The error message says:
"Python stopped working"
"A problem caused the program to stop working correctly.Windows will close
the program and notify you if a solution is available"

Can you guide me on this issue. What steps need to be taken to resolve this
issue?

What steps will reproduce the problem?

   1. Open Anaconda
   2. Open Spyder, click on new file
   3. Try saving the new file and this error will pop up.

What is the expected output? What do you see instead?
The expected output is to see the new file getting saved in the location
specified. Instead the spyder application crashes after the following error
message.

"Python stopped working"
"A problem caused the program to stop working correctly.Windows will close
the program and notify you if a solution is available"

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    spyder --report-segfault

After it crashes, please run again

    spyder --report-segfault

Then a dialog will be shown that will allow you to upload the crash report here to Github.

If no dialog appears, please look for a file called `faulthandler.log` in Spyder's configuration directory (`C:\Users\<your user>\.spyder-py3` on Windows; `/Users/<your user>/.spyder-py3` on macOS; or `/home/<your user>/.config/spyder-py3` on Linux) and upload it here.

**Comment by SadhviV** [comment]
please find the attached file.

Best Regards,
Sadhvi

**Comment by ccordoba12** [comment]
I saw the issue you opened with the crash information for this (#14111). Unfortunately, it couldn't capture any useful information, sorry.

**Comment by SadhviV** [comment]
Do you want me to provide you with more details?
please provide me with the workaround for this issue?

**Comment by ccordoba12** [comment]
Some ideas:

* Perhaps you have some firewall or antivirus program that prevents Spyder to work.
* Or you're writing to a protected directory, which causes the crash.
* Or you're writing to a Dropbox or OneDrive directories.

If none of that helps, I'm sorry but I have no more advice nor workarounds to offer.

**Comment by sysadmin75** [comment]
Spyder version: 4.1.5
Python version: 3.9.1
Qt version: 4.8.7-57
PyQt version: 5.15.0-4
Operating System name/version: Fedora release 33

I've been able to reproduce this issue consistently. I open the distro install app, then try to save the default file and it just crashes.

I installed spyder using the distro package manager (dnf).
Here is the backtrace: https://gist.github.com/sysadmin75/130aec232c0489908c625023f23e2ff4

I tried reproducing the problem by setting up a dev environment following the instructions [here](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md).  I tested against master but was unable to repro the problem.

I also tried against branch 4.1.x and was still unable to repro the problem.

**Comment by ccordoba12** [comment]
@sysadmin75, thanks for chiming in but we don't have the resources nor the time to offer support for custom installations (only Anaconda and our installers).

And, as you already verified, everything is working with Anaconda. So please bring your problem to the attention of your distro maintainers.

**Comment by ccordoba12** [comment]
Also, I'm going to close this one due to lack of response.
