### ISSUE TITLE
Error on start up

### ISSUE THREAD

**Issue by aikimark** [spyder-ide/spyder#14060]
### What steps will reproduce the problem?

Launch Spyder from a menu or from the Explorer window.

Error msg:
This command failed to be executed because an error occurred while trying to get the file code from Spyder's editor. The error was:

An exception has occurred, use %tb to see the full traceback.

TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

===============
Traceback results:
Traceback (most recent call last):

  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 463, in get_file_code
    filename, save_all=save_all)

  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)

  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    return self._sync_error(reply['value'])

  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 488, in _sync_error
    error_wrapper.raise_error()

  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)

TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

==================
Environment:
Windows 7
Python 3.7
Anaconda used for installations

### Traceback
```python-traceback
  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
ERROR:traitlets:Exception in comm_msg for 4a337c58165511eba55700269ec3f96c
Traceback (most recent call last):
  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\qtconsole\comms.py", line 177, in comm_msg
    comm.handle_msg(msg)
  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\qtconsole\comms.py", line 265, in handle_msg
    return self._msg_callback(msg)
  File "C:\Users\Public\Documents\Anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 331, in _comm_message
    msg_dict, buffer)
TypeError: _handle_remote_call_reply() missing 1 required positional argument: 'load_exception'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.6.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.18.1 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  6.0.7 (OK)
numpydoc >=0.6.0             :  1.1.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.2 (OK)
pygments >=2.0               :  2.7.1 (OK)
pylint >=0.25                :  2.6.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  19.0.2 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  1.0.1 (OK)
qtconsole >=4.6.0            :  4.7.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  3.2.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.9.4 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.21 (OK)
matplotlib >=2.0.0           :  3.3.2 (OK)
numpy >=1.7                  :  1.19.1 (OK)
pandas >=0.13.1              :  0.25.1 (OK)
scipy >=0.17.0               :  1.5.2 (OK)
sympy >=0.7.3                :  1.6.2 (OK)
```

**Comment by aikimark** [comment]
I ran the conda command as per your instructions.  I now see a different, kernel related, error message.  Here is the traceback text from Spyder:

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "C:\Users\Public\Documents\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1209, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle, **kwargs)
File "C:\Users\Public\Documents\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 313, in start_kernel
self.kernel = self._launch_kernel(kernel_cmd, **kw)
File "C:\Users\Public\Documents\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 220, in _launch_kernel
return launch_kernel(kernel_cmd, **kw)
File "C:\Users\Public\Documents\Anaconda3\lib\site‑packages\jupyter_client\launcher.py", line 131, in launch_kernel
proc = Popen(cmd, **kwargs)
File "C:\Users\Public\Documents\Anaconda3\lib\subprocess.py", line 775, in __init__
restore_signals, start_new_session)
File "C:\Users\Public\Documents\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by ccordoba12** [comment]
Please run

    conda install spyder=4.1.5

That should fix the problem.

**Comment by aikimark** [comment]
That seems to have fixed the problem.  Thanks.

Here is the activity of the **conda install 4.1.5** command.
=========================================
(base) C:\Users\New User>conda install spyder=4.1.5
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata
source.
Collecting package metadata (repodata.json): done
Solving environment: /
Warning: 4 possible package resolutions (only showing differing packages):
  - https://repo.continuum.io/pkgs/main/win-64/console_shortcut-0.1.1-h6bb2dd7_3.tar.bz2/win-64::con
sole_shortcut-0.1.1-h6bb2dd7_3, https://repo.continuum.io/pkgs/main/win-64/get_terminal_size-1.0.0-h
38e98db_0.tar.bz2/win-64::get_terminal_size-1.0.0-h38e98db_0
  - defaults/win-64::console_shortcut-0.1.1-h6bb2dd7_3, https://repo.continuum.io/pkgs/main/win-64/g
et_terminal_size-1.0.0-h38e98db_0.tar.bz2/win-64::get_terminal_size-1.0.0-h38e98db_0
  - defaults/win-64::get_terminal_size-1.0.0-h38e98db_0, https://repo.continuum.io/pkgs/main/win-64/
console_shortcut-0.1.1-h6bb2dd7_3.tar.bz2/win-64::console_shortcut-0.1.1-h6bb2dd7_3
  - defaults/win-64::console_shortcut-0.1.1-h6bb2dd7_3, defaults/win-64::get_terminal_size-1.0.0-h38
e98dbdone

## Package Plan ##

  environment location: C:\Users\Public\Documents\Anaconda3

  added / updated specs:
    - spyder=4.1.5


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jedi-0.17.1                |           py37_0         914 KB
    parso-0.7.0                |             py_0          72 KB
    python-language-server-0.34.1|           py37_0          96 KB
    spyder-4.1.5               |           py37_0         5.7 MB
    ------------------------------------------------------------
                                           Total:         6.7 MB

The following packages will be UPDATED:

  jedi                                        0.14.1-py37_0 --> 0.17.1-py37_0
  parso                                          0.5.2-py_0 --> 0.7.0-py_0
  python-language-s~                          0.31.7-py37_0 --> 0.34.1-py37_0
  spyder                                       4.1.0-py37_0 --> 4.1.5-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
spyder-4.1.5         | 5.7 MB    | ######################################################## | 100%
parso-0.7.0          | 72 KB     | ######################################################## | 100%
jedi-0.17.1          | 914 KB    | ######################################################## | 100%
python-language-serv | 96 KB     | ######################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: - DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFO
RM}', prefix: 'C:\Users\Public\Documents\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'use
r'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Documents\Anaconda3\pythonw.exe, a
rgs are ['C:\\Users\\Public\\Documents\\Anaconda3\\cwp.py', 'C:\\Users\\Public\\Documents\\Anaconda3
', 'C:\\Users\\Public\\Documents\\Anaconda3\\pythonw.exe', 'C:\\Users\\Public\\Documents\\Anaconda3\
\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Documents\Anaconda3\python.exe, ar
gs are ['C:\\Users\\Public\\Documents\\Anaconda3\\cwp.py', 'C:\\Users\\Public\\Documents\\Anaconda3'
, 'C:\\Users\\Public\\Documents\\Anaconda3\\python.exe', 'C:\\Users\\Public\\Documents\\Anaconda3\\S
cripts\\spyder-script.py', '--reset']
DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\P
ublic\Documents\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
\ DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Documents\Anaconda3\pythonw.exe,
 args are ['C:\\Users\\Public\\Documents\\Anaconda3\\cwp.py', 'C:\\Users\\Public\\Documents\\Anacond
a3', 'C:\\Users\\Public\\Documents\\Anaconda3\\pythonw.exe', 'C:\\Users\\Public\\Documents\\Anaconda
3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Documents\Anaconda3\python.exe, ar
gs are ['C:\\Users\\Public\\Documents\\Anaconda3\\cwp.py', 'C:\\Users\\Public\\Documents\\Anaconda3'
, 'C:\\Users\\Public\\Documents\\Anaconda3\\python.exe', 'C:\\Users\\Public\\Documents\\Anaconda3\\S
cripts\\spyder-script.py', '--reset']
/ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users
\Public\Documents\Anaconda3', env_name: 'None', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Documents\Anaconda3\pythonw.exe, a
rgs are ['C:\\Users\\Public\\Documents\\Anaconda3\\cwp.py', 'C:\\Users\\Public\\Documents\\Anaconda3
', 'C:\\Users\\Public\\Documents\\Anaconda3\\pythonw.exe', 'C:\\Users\\Public\\Documents\\Anaconda3\
\Scripts\\spyder-script.py']
- DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\Public\Documents\Anaconda3\python.exe,
args are ['C:\\Users\\Public\\Documents\\Anaconda3\\cwp.py', 'C:\\Users\\Public\\Documents\\Anaconda
3', 'C:\\Users\\Public\\Documents\\Anaconda3\\python.exe', 'C:\\Users\\Public\\Documents\\Anaconda3\
\Scripts\\spyder-script.py', '--reset']
done
