### ISSUE TITLE
breakpoints not honored

### ISSUE THREAD

**Issue by henryeck** [spyder-ide/spyder#14089]
### What steps will reproduce the problem?

file: me.py:

import you

def hello():
    print('hello from me')
    return

hello()
you.hello()

file you.py:

def hello():
    print('hello from you')
    return

breakpoint on the return statement in you.py will not be honored.  in general, breakpoints in included files will never be honored, although it will stop at breakpoints in the top-level file

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.3
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-52-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
parso =0.7.0                   :  0.7.1 (NOK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.1.6 (NOK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.1.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.1.1 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.4 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @henryeck I'm not totally sure to understand the issue you mention but seems like using the buttons to navigate the debugging session doesn't show the frames in Spyder 4.1.5 (preview with buttons and then using the command directly in the console):

![debug](https://user-images.githubusercontent.com/16781833/97595162-6cd9bb80-19d1-11eb-9e44-2cfb25ce26bd.gif)

Is that what you are referring with breakpoints not being honored?

Pinging @ccordoba12 @impact27 just in case

**Comment by henryeck** [comment]
[spyderbp.zip](https://github.com/spyder-ide/spyder/files/5460018/spyderbp.zip)

thanks for responding.  I made a recording to demo the issue. (had to wrap in a zip to upload)
thank you for your help.

**Comment by dalthviz** [comment]
Thanks @henryeck for the video! Maybe then this issue affects only Linux installations? (I tested on Windows). @andfoy @ccordoba12 could you check if you can reproduce this?

Adding the video in GIF format here just in case:

![testrecording](https://user-images.githubusercontent.com/16781833/97609316-723f0200-19e1-11eb-9f0e-43863f5cc1c0.gif)

**Comment by impact27** [comment]
Works for me on macOS

**Comment by henryeck** [comment]
i installed in windows 10, tried with spyder 4.1.4 and 4.1.5, worked fine.

must be some issue in linux or with this install.  is there anything i could/should do to debug the installation ?  The problem is 100% reproducible there - it only stops at breakpoints in the main script, never in the included py scripts

**Comment by impact27** [comment]
The function that decides whether to stop is:
https://github.com/spyder-ide/spyder-kernels/blob/3932a2e7053870e7c644f043f8ac91528a5c0f3e/spyder_kernels/customize/spyderpdb.py#L229

It the debugger doesn't work it will be hard to debug but I would add print statements to find out:
 - If it is called on the correct frame
 - Why it decides to not stop

**Comment by impact27** [comment]
But I would first try to disable "Ignore libraries while debugging" under Debug

**Comment by henryeck** [comment]
sorry but could you give me some more detail about how to accomplish the suggested experiment.  Do I need to modify a kernel script, and how?  thanks

**Comment by impact27** [comment]
Go to `Debug` > `Ignore libraries while debugging` and check if this option changes the behaviour you see

if that doesn't work:

Open `spyder_kernels/customize/spyderpdb.py` that is installed in you python folder. locate the `stop_here` method and add a bunch of print statements. For example:
```
    def stop_here(self, frame):
        """Check if pdb should stop here."""
        print("Called stop_here on ", frame.f_code.co_filename)
        if not super(SpyderPdb, self).stop_here(frame):
            print("Super returned False")
            return False
        filename = frame.f_code.co_filename
        if filename.startswith('<'):
            # This is not a file
            print("This is a file")
            return True
        if self.pdb_ignore_lib and path_is_library(filename):
            print("This is a hidden lib")
            return False
        print("return True")
        return True
```
(This will print a lot of things)

**Comment by henryeck** [comment]
Thanks you for your help and suggestions on this issue.  It seems to have gone away when we reinstalled spyder.  So I never identified the cause.  thanks for your help.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it @henryeck.
