### ISSUE TITLE
running code in a (remote) spyder-kernel in chunks bigger than a cell (file/project)

### ISSUE THREAD

**Issue by nerohmot** [spyder-ide/spyder#14085]
### Situation:

The first versions of [spyder-remote](https://github.com/Semi-ATE/spyder-remote) are available, we are now able to start a [spyder-kernel](https://github.com/spyder-ide/spyder-kernels) on a remote machine by the click of a button. :smile: 

Now, from spyder we can execute a chunk of code from the editor to the remote-console by using the `run current cell`, but the `run` button is not able to execute bigger chunks (the current file, together with the current project) as the `run` button sends `runfile('/home/nerohmot/Desktop/temp.py', wdir='/home/nerohmot/Desktop')` to the current console (which happens to be a remote spyder-kernel) which would be fine if the remote system would have the local tree mirrored ...

Anyway we need to brainstorm on how this could be achieved.

### Interesting library
- [fsspec](https://github.com/intake/filesystem_spec) ([RTD](https://filesystem-spec.readthedocs.io/en/latest/?badge=latest))

## Versions

* Spyder version: >= 5.0.0
* Python version: any
* Qt version: N/A
* PyQt version:  N/A
* Operating System name/version:
  - host : any
  - remote : Linux (Windows/macOS afterwards)

**Comment by ccordoba12** [comment]
> The first versions of spyder-remote are available, we are now able to start a spyder-kernel on a remote machine by the click of a button.

Great news! Congrats @nerohmot!

> Now, from spyder we can execute a chunk of code from the editor to the remote-console by using the run current cell, but the run button is not able to execute bigger chunks

This limitation has been known for a long time (see issue #3587). Therefore, I'm going to close this issue in favor of that one.

I'll also give you a ping there so you can receive updates on that issue.

> which would be fine if the remote system would have the local tree mirrored ...

That's a good idea, but perhaps we should do it only when a project is active to mirror only the root of your project (and not your entire home).
