### ISSUE TITLE
Set column width automatically after changing autoformatter

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#14082]
To provide a better UX for autoformatting, I think we should apply some options related to the max allowed column width in the editor automatically, either when changing formatters or other optiions in Spyder.

Concretely, i think we should do the following:

* If people select Black, we should set **88** as the value of `Completion and linting > Code style > Maximum allowed length`. And this value should be **79** if people select Autopep8 or Yapf.
* When using Black, we should set **88** as the value of `Editor > Display > Show vertical lines at`. And this value should be **79** if people select Autopep8 or Yapf.
* If people manually set the value of `Completion and linting > Code style > Maximum allowed length`, we should tell the current formatter to use that value instead of the one they used by default. And if people select another formatter, that option needs to be passed to the new formatter too.
* If people manually set the value of `Completion and linting > Code style > Maximum allowed length`, we should also use that value to set `Editor > Display > Show vertical lines at`.
* If people manually set `Editor > Display > Show vertical lines at`, we shouldn't do anything because that's not related to autoformatting.

**Comment by steff456** [comment]
- Remove `Show vertical lines at` from the editor and put an option in codestyle `Show vertical line`

**Comment by MuellerSeb** [comment]
If using `black` it would be nice to be still able to set the line-length to e.g. `79`. Since black provides the `-l` option, this should be possible. I am fine with auto setting it to `88`, when switching the autoformatter.

**Comment by ccordoba12** [comment]
@MuellerSeb, good point! Could you open a new issue so we don't forget to address that in our next version?

**Comment by MuellerSeb** [comment]
@ccordoba12 done.
