### ISSUE TITLE
nightmare issue using globals

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#14103]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``ipython`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I've a very bad issue causing error prone usage of spyder. It is related to the way globals are populated and used inside the ipython console (I've checked that this does not happen in ipython console directly therefore I suspect spyder 4.1.5 with up-to-date modules by anaconda).

**In "run/general options" I've checked, "execute in console namespace instead of an empty one".**

The problem is a bit tricky to describe therefore I've created 2 files for you to reproduce.

1st file 'main.py'
```python
# reveal a python (spyder?) 'bug'
# run this file from ipython
# change lib.a below, eg to 2, rerun
# now the printed values will be different, which they should not!

import lib

lib.a=1

if 'bug' not in globals() or not bug: bug = lib.BUG()

print(bug.test(), lib.test())

if bug.test()!=lib.test():
    print('BUG revealed')
```
2nd file 'lib.py'
```python

a=0

class BUG:
  def __init__(self):
    print('__init__ called')

  def test(self):
    return a
    
def test():
  return a
```

### What steps reproduce the problem?

1. create the 2 files above
2. run main.py file
3. change lib.a value in main.py, eg to 2, rerun, **now the printed values will be different, which they should not**.

### What is the expected output? What do you see instead?

1st run might output `1 1`
2nd run might output `2 2`

I see `2 1` for the 2nd run.

It means that the instance `bug` & the function `test()` do not see the same value of the global variable `a` despite being in the same namespace. Note that the instance `bug` is not recreated during the 2nd run. For me it is a nightmare.

PS: it might be a 2nd bug but maybe related ? If so I will write a 2nd issue. If one force re-saving the file `lib.py` (without any change, or eg just a comment in practice). Then **without running anything**. The variable `lib.a` gets to 0 in the console. For me it sounds absurd but it might be normal? ipython does not have this issue either (executed using `%run -i main.py`).

## Versions

* Spyder version: 4.1.5
* Python version:  3.8
* Operating System name/version: windows 10

**Comment by impact27** [comment]
I can reproduce

Running with ipython / the console:
```
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.18.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 

In [1]: import lib
   ...: 
   ...: lib.a=1
   ...: 
   ...: if 'bug' not in globals() or not bug: bug = lib.BUG()
   ...: 
   ...: print(bug.test(), lib.test())
   ...: 
   ...: if bug.test()!=lib.test():
   ...:     print('BUG revealed')
   ...: 
__init__ called
1 1

In [2]: import lib
   ...: 
   ...: lib.a=2
   ...: 
   ...: if 'bug' not in globals() or not bug: bug = lib.BUG()
   ...: 
   ...: print(bug.test(), lib.test())
   ...: 
   ...: if bug.test()!=lib.test():
   ...:     print('BUG revealed')
   ...: 
2 2
```

Running with a file:
```
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
Type "copyright", "credits" or "license" for more information.

IPython 7.18.1 -- An enhanced Interactive Python.

In [1]: runfile('/Users/quentinpeter/Desktop/untitled1.py', wdir='/Users/quentinpeter/Desktop', current_namespace=True)
Reloaded modules: spyder, spyder.pil_patch
__init__ called
1 1

In [2]: runfile('/Users/quentinpeter/Desktop/untitled1.py', wdir='/Users/quentinpeter/Desktop', current_namespace=True)
Reloaded modules: lib, spyder, spyder.pil_patch
1 2
BUG revealed

In [3]: runfile('/Users/quentinpeter/Desktop/untitled1.py', wdir='/Users/quentinpeter/Desktop', current_namespace=True)
Reloaded modules: lib, spyder, spyder.pil_patch
1 2
BUG revealed

In [4]: 
```

So the problem is in the `runfile` function.

**Comment by impact27** [comment]
So the problem is that we modify the way modules work. Usually modules are loaded once and never again. This can be surprising for users because if they are writing their own modules and importing them, they usually expect modifications to have an effect. Therefore `runfile` reloads the modules if it is not an installed one. To disable this, you can set `SPY_UMR_ENABLED` to `False`, or running:
```
from spyder_kernels.customize.spydercustomize import __umr__; __umr__.enabled = False
```
```
Python 3.8.6 (default, Oct  8 2020, 14:06:32) 
Type "copyright", "credits" or "license" for more information.

IPython 7.18.1 -- An enhanced Interactive Python.

In [1]: from spyder_kernels.customize.spydercustomize import __umr__
   ...: __umr__.enabled = False

In [2]: runfile('/Users/quentinpeter/Desktop/untitled1.py', wdir='/Users/quentinpeter/Desktop', current_namespace=True)
lib imported
__init__ called
1 1

In [3]: runfile('/Users/quentinpeter/Desktop/untitled1.py', wdir='/Users/quentinpeter/Desktop', current_namespace=True)
2 2

In [4]: 
```

**Comment by ccordoba12** [comment]
@impact27, thanks a lot for taking a look at this issue and finding its cause.

@sylvain-bougnoux, you can disable our User Module Reloader (UMR) by going to the `Tools` meolnu and selecting

    Preferences > Python Interpreter

and then deactivating the option called `Enable UMR`.

**Comment by ccordoba12** [comment]
@sylvain-bougnoux, sorry, I forgot to mention that what @impact27 found is that our UMR is what's causing the odd behavior you're observing.
