### ISSUE TITLE
Completion and litning does not work

### ISSUE THREAD

**Issue by DIMPODIMPO** [spyder-ide/spyder#14118]
### Issue Report Checklist

* [ yes] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ yes] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [yes ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [yes ] Restarted Spyder
    * [yes ] Reset preferences with ``spyder --reset``
    * [ yes] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [yes ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have just updated spyder to version 4.1.5 and as soon as I did it it started to come up this message.
I have tried to rester both spyder and anaconda several times but nothing changed.
What can I do to solve this problem?

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please open a terminal (cmd.exe, Terminal.app or xterm) and run the following command:

    spyder --debug-info verbose --debug-output file

and upload here the file called `spyder-debug.log`, which is created in the same directory where you ran the command above.

**Comment by DIMPODIMPO** [comment]
When I try to run the line above in the terminal it gives me this error:
TypeError: expected str, bytes or os.PathLike object, not _io.TextIOWrapper
Obviously then the file spyder-debug.log is just an empty file.

**Comment by ccordoba12** [comment]
Ok, then it seems that Anaconda is broken for you. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) on how to remove it and reinstall it again.

**Comment by DIMPODIMPO** [comment]
I have followed all the steps in the video but still nothing changed.
Still I see no linting and still if I try to run the debug line I get an error.

**Comment by ccordoba12** [comment]
Sorry but without additional debug info it's impossible for us to know what's happening in your case.

**Comment by ccordoba12** [comment]
Closing because there's nothing else we can do to help, sorry.
