### ISSUE TITLE
Open and/or Write to File Running Individually Cells vs Entire File

### ISSUE THREAD

**Issue by renato-favarin** [spyder-ide/spyder#14124]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Open and write to a txt file when I run individual cells.

### What steps reproduce the problem?

1. Open Spyder
2. Try to run any of these 2 following cells:

```python
#%%
def lerArquivo(filename):
    arqEntrada = open(filename, 'r')
    conteudo = arqEntrada.read()
    arqEntrada.close()
    lista_palavras = conteudo.split(sep=' ')
    print(lista_palavras)
    return len(lista_palavras), len(conteudo)

n_palavras, n_caracteres = lerArquivo('teste.txt')


#%%
idade = 30
idade2 = 33
outfile = open('teste_escrever_arq.txt','w')
outfile.write('Sua idade é'+str(idade)+'anos.\n')
outfile.write('Sua idade é {} anos.\n'.format(idade2))
outfile.write('Sua idade é %s anos.\n' %(idade2))
outfile.write('Sua idade é %r anos.\n' %(idade2))
outfile.close()
```

3.  Copy and paste the content of any cell above into a new file. 

4. Run this file and now it will work.

5 If I go back to the file with the 2 cells and try to run individually cells again, now it works.

## Versions

* Spyder version:  Spyder 4.1.4 
* Python version: Python 3.8.3 64-bit 
* Qt version: Qt 5.9.7
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @renato-favarin, thanks for reporting. I don't understand what's exactly not working. Could you clarify that?

**Comment by renato-favarin** [comment]
Hello @ccordoba12 . I noticed a difference between running a cell and the entire file. Specifically, when I try to open, read and close a txt file. 

If I have a saved *.py like this:

```
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

#%%
def readFile(filename):
    entryFile = open(filename, 'r')
    content = entryFile.read()
    entryFile.close()
    word_list = content.split(sep=' ')
    print(word_list)
    return len(word_list), len(content)

#calling the function
n_palavras, n_caracteres = readFile("test.txt")


```
And if I decide to run just the cell, which starts with the "def readFile(filename)", I got this:

```
runcell(1, 'C:/Users/RNFAVAR.EMBAD/Documents/Pessoais/Python_tests/temp.py')
Traceback (most recent call last):

  File "C:\Users\RNFAVAR.EMBAD\Documents\Pessoais\Python_tests\temp.py", line 19, in <module>
    n_palavras, n_caracteres = readFile("test.txt")

  File "C:\Users\RNFAVAR.EMBAD\Documents\Pessoais\Python_tests\temp.py", line 11, in readFile
    entryFile = open(filename, 'r')

FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'
```

However, if I just click in "Run" (not only the cell), I got this:

```
runfile('C:/Users/RNFAVAR.EMBAD/Documents/Pessoais/Python_tests/temp.py', wdir='C:/Users/RNFAVAR.EMBAD/Documents/Pessoais/Python_tests')
['cat', 'house', 'ball', 'brick', 'guitar', 'floor']
```

I hope I could explain a little better. I also can provide some PrtScr.

Thank you!

**Comment by ccordoba12** [comment]
Closing because this is quite old now. Hopefully you managed to solve this problem.
