### ISSUE TITLE
some issues while starting apyder3 IDE

### ISSUE THREAD

**Issue by ShubhAgarwal-dev** [spyder-ide/spyder#14132]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS
    from spyder.api.plugins import SpyderPluginWidget
ModuleNotFoundError: No module named 'spyder.api'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by steff456** [comment]
Hi @ShubhAgarwal-dev,

Can you please let me know which version of Spyder Notebook are you running? In case you installed the latest version of Spyder Notebook, please update your Spyder to Spyder 4 using the following commands,
```
conda update anaconda
conda install spyder=4.1.5
```

Please let me know if this works.

**Comment by ShubhAgarwal-dev** [comment]
> Hi @ShubhAgarwal-dev,
> 
> Can you please let me know which version of Spyder Notebook are you running? In case you installed the latest version of Spyder Notebook, please update your Spyder to Spyder 4 using the following commands,
> ```
> conda update anaconda
> conda install spyder=4.1.5
> ```
> 
> Please let me know if this works. 
**Thanks**
It started without this prompt now but I also have to add some things in python path too
