### ISSUE TITLE
upgrade to latest spyder and program stops working

### ISSUE THREAD

**Issue by shallst** [spyder-ide/spyder#14133]
### What steps will reproduce the problem?

program worked fine with previous version of spyder, but now crashes.
Seems to be in the sub routines.

%tb
Traceback (most recent call last):

  File "C:\Users\Admin\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 463, in get_file_code
    filename, save_all=save_all)

  File "C:\Users\Admin\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    call_dict, call_data, self._comm_id)

  File "C:\Users\Admin\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 432, in _get_call_return_value
    return self._sync_error(reply['value'])

  File "C:\Users\Admin\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 488, in _sync_error
    error_wrapper.raise_error()

  File "C:\Users\Admin\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)

TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=0.25                  :  2.6.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by steff456** [comment]
Hi @shallst,

Can you please update your Spyder's version to the latest with the following commands to see if that fixes your error,
```
conda update anaconda
conda install spyder=4.1.5
```

Please let me know if this works

**Comment by shallst** [comment]
That solved the issue.Thank you!

Sent from Yahoo Mail on Android 
 
  On Tue, Nov 3, 2020 at 10:14 AM, Stephannie Jimenez Gacha<notifications@github.com> wrote:   


Hi @shallst,

Can you please update your Spyder's version to the latest with the following commands to see if that fixes your error,
conda update anaconda
conda install spyder=4.1.5

Please let me know if this works

**Comment by steff456** [comment]
Perfect! Thanks for reporting :)!
