### ISSUE TITLE
Feature request: fold all and collapse all

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#14148]
It'd be handy to have fold all/collapse all features.

**Comment by andfoy** [comment]
Hi @ma-sadeghi, thanks for opening this issue. Could you please explain more in detail about what are you referring as "fold all/collapse all features"?

**Comment by ma-sadeghi** [comment]
Hi @andfoy, so let's say you have 10 functions inside file.py. To fold code for all 10 functions, you need to manually go 1 by 1 and click on the upside down triangle next to `def` keyword. Other IDEs have a feature to fold/collapse all functions/classes in a given file.

**Comment by ccordoba12** [comment]
Hey @ma-sadeghi, thanks for the suggestion. We already have issue #8090 for all suggestions on how to improve code folding. Please leave yours there.
