### ISSUE TITLE
Can't create folders/packages

### ISSUE THREAD

**Issue by MZbiec** [spyder-ide/spyder#14151]
### What steps will reproduce the problem?

Right-clicking on my top folder and selecting new->Folder..., or new-> Python package results in Unable to create folder error. Error message says it's a Win Error 3.
Also package creation results in additional error: unable to create file for __init__.py file. I've tried running spyder as administrator, spyder --restart in "cmd", restarting machine, and running spyder in new enviroment. Nothing helps.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.1.1 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by andfoy** [comment]
Hi @MZbiec, have you checked if the folder that you are trying to write in is contained inside a read-only folder/volume?

**Comment by MZbiec** [comment]
It is not. I can create python scripts (via new ->  Python Script...)  in this folder just fine. Just not folders/packages.

**Comment by ccordoba12** [comment]
Hey @MZbiec, this is a duplicate if issue #13722 and it'll be fixed in our next version, to be released in a few days.
