### ISSUE TITLE
Parso dependency

### ISSUE THREAD

**Issue by Dan-Patterson** [spyder-ide/spyder#14156]
Problem Description

Parso is currently pinned to 0.7.  This has caused issues with other software (ArcGIS Pro, by esri) 
that I use and recently installed.
Can someone articulate the reason for the pin? (jedi? version).
I need both for work.  Currently I am "parallel processing" using 2 machines :(

* Spyder version:   4.15
* Python version:   3.7.9 [MSC v.1922 64 bit (AMD64)]
* Qt version:          qt   5.9.7    vc14h73c81de_0
* PyQt version:       pyqt    5.9.2    py37h6538335_2
* Operating System name/version:   Windows 10 Oct 2020 update

```
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.2 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.0 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.1 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Dan-Patterson, thanks for reporting. You said:

> Can someone articulate the reason for the pin? (jedi? version).

Jedi `0.17.{0, 1, 2}` doesn't work with Parso `0.8.0`. And Parso `0.7.1` only has some minor bugfixes over `0.7.0`.

**Comment by Dan-Patterson** [comment]
@ccordoba12 many thanks for this.  
I will pass this information on to those that distribute the other software's conda distribution.  They have Jedi at 0.17.2 and left parso to install the latest.
