### ISSUE TITLE
Items are collapsed in the outline explorer after a change was made in the editor when the option "Follow cursor position" is unchecked.

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#14152]
## Problem Description

In the outline explorer, items are collapsed after a change was made in the editor when the option `Follow cursor position` is unchecked.

![outline_explorer_collapse](https://user-images.githubusercontent.com/10170372/98272449-19321980-1f5f-11eb-8e14-406019a22b67.gif)

I believe this is a regression compared to the old behaviour. Here is an animation showing how it was working before the migration.

![outline_explorer_collapse_before](https://user-images.githubusercontent.com/10170372/98272116-b6408280-1f5e-11eb-9e03-91520e69c064.gif)

## Versions

* Spyder version: 4.2.0.dev0 b7e9cf9b1
* Python version: 3.7.6 64-bit
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by andfoy** [comment]
@jnsebgosselin, thanks for reporting this one, I'll take a look at it

**Comment by jnsebgosselin** [comment]
Thank you so much @andfoy !

**Comment by SebastianHD** [comment]
This "bug" seems to have reemerge.

When following cursor, it seems to at least re-expand the tree to the current class function, but still collapses all others.

* Spyder version: 5.5.4  (pip)
* Python version: 3.12.3 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
@SebastianHD, that's not exactly this bug but a different one and I can confirm it's still present in Spyder.

Please open a new issue about it so we don't forget to solve it in a future release.

**Comment by qsff-awareness** [comment]
Is there any update here? The issue is still there:
Spyder: 6.1.0
Python: 3.13.9
Qt: 5.15.2
PyQt5: 5.15.11
Win 11, build 24H2

https://github.com/user-attachments/assets/cffc13a6-bc0f-4972-bbc7-c0d22832078e
