### ISSUE TITLE
Editor does not add colon and autoindent when I enter e.g. if a==3 # comment

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1416]
_From [bgai...@gmail.com](https://code.google.com/u/115200413098054342316/) on 2013-05-31T11:58:25Z_

What steps will reproduce the problem?

 1. in editor enter if a==3 # comment

What is the expected output?
if a==3: # comment
  (indentation)

What do you see instead?
if a==3 # comment
(no  indentation)

What version of the product are you using? 
2.3.0 Dev 1

On what operating system?
Win XP

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1416_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:58:26Z_

**Labels:** Cat-Editor MS-v2.4

**Comment by ccordoba12** [comment]
Automatic colons are inserted only at the end of the line.

However, indentation work if you write

    if a == 3:<Enter> # comment

I think it's the best that we can do :-)

**Comment by Nodd** [comment]
It should be doable: strip comments, check if colon needs to be added, readd comment, and voilà ! (same for indentation).

**Comment by ccordoba12** [comment]
I think it's hard to get it right in all situations. But if you want to try it, please submit a PR :-)

**Comment by Nodd** [comment]
Yeah, I can see some corner cases:
```python
if c == "#": # comment
```
