### ISSUE TITLE
Allow setting line length, when setting `black` as autoformatter

### ISSUE THREAD

**Issue by MuellerSeb** [spyder-ide/spyder#14175]
## Problem Description

When setting `black` as autoformatter, the line-length (and the vertical ruler) are set and fixed to `88`.
Related: #14082

### What steps reproduce the problem?

1. set `Preferences` -> `Completion and linting` -> `Code formatting` -> `Choose the code formatting provider` to `black`
2. `Preferences` -> `Completion and linting` -> `Code style` -> `Maximum allowed line length` is auto. set to `88`
3. can't change this `Maximum allowed line length`

### What is the expected output? What do you see instead?
Preset of `88` for `black` is fine, but since `black` provides the `-l` option ([link](https://github.com/psf/black#command-line-options)), the maximum line length should be changeable. 

## Versions
* Spyder version: 4.2.0

### Dependencies
* black

**Comment by steff456** [comment]
Hi @MuellerSeb,

Black has a default of 88 for the maximum line length, so we decided to change those options automatically in case of choosing black as the autoformatter. If you want to preserve the 79 option, please change those options manually in `Preferences > Completion and linting > Code style > Maximum allowed line length`

Please let me know if this works

**Comment by MuellerSeb** [comment]
Hey @steff456,
when I type e.g. 79 there and click apply, it just snaps back to 88. So I consider this a bug.

**Comment by steff456** [comment]
You are right! I can reproduce it, we will work in fixing it :)

**Comment by ccordoba12** [comment]
@steff456, I think the solution to this is to move the `Maximum allowed length` option out of the group `Enable code style linting`, so that users don't require to activate that just to change it:

![Selección_024](https://user-images.githubusercontent.com/365293/98733894-399f1100-236f-11eb-8495-a2508fab0809.png)

Besides, we need to remove the validations we added to automatically set that value according to the auto-formatter currently selected. Instead, we need to let users pick out that value freely.

**Comment by ccaprani** [comment]
Sorry to re-open, but this isn't fixed in v5.0.5: I have maximum length set to 79 (PEP8) and when using black on save it autoformats to 88 character lines.

**Comment by ccordoba12** [comment]
Hey @ccaprani, we're aware this problem resurfaced again (see issue #14558). We'll try to fix it in our next version (5.2.0), to be released at the end of September.

**Comment by ccaprani** [comment]
My apologies @ccordoba12 , and thanks so much for your efforts.
