### ISSUE TITLE
EOFError: EOF when reading a line

### ISSUE THREAD

**Issue by sargent2002** [spyder-ide/spyder#14174]
![Screenshot from 2020-11-09 14-02-55](https://user-images.githubusercontent.com/74177115/98517687-50246a00-2294-11eb-8f7b-562d132bd82c.png)

```

**Comment by ccordoba12** [comment]
Hey @sargent2002, thanks for reporting. Please rename or remove this file to fix your problem:

    /home/himanshu/IP PROJECT/New Folder/Hospital/code.py

That should fix your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
