### ISSUE TITLE
Show vertical line at maximum allowed line length does not respect max allowed line length at startup

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#14188]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The vertical line indicating the maximum allowed line length does not respect the value in the preferences on startup.

### What steps reproduce the problem?

1. Change the vertical line location in the Editor by changing the max allowed line length in the Preferences.
2. Notice that the vertical line changes position, as expected.
3. Quit and reopen Spyder
4. Notice that the vertical line in the Editor is again at 79; Preferences still indicates the previously entered maximum line length.

## Versions

* Spyder version: 4.3.0.dev0 b4c0facea (bootstrap)
* Python version: 3.7.9 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

**Comment by mrclary** [comment]
Tangentially, is it possible to have the vertical line in the Editor use the maximum allowed line length from a relevant pycodestyle.cfg file? I.e. linting already uses these files to appropriately analyze code style, including `max_line_length`; it would make sense to use this value to override the value in Preferences.

**Comment by steff456** [comment]
Hi @mrclary, I can reproduce this error, we will work in this because there's something weird happening with that preference setting

**Comment by urob** [comment]
I am having the same issue. One observation: it seems that the setting is actually correctly used by the code style linter. For instance, if line length is set to 88, then the linter doesn't show a warning for lines between 80 and 87 characters. Only the location of the vertical line is off.

**Comment by Cuahchic** [comment]
I can confirm this issue still persists in 5.0.3. If I go into settings and change it the line will move, but at startup it's incorrect.

**Comment by joooeey** [comment]
I just noticed that when I change the max allowed line length in the settings, the vertical line only changes in the active panel. In other open panels it stays at 79 characters.

**Comment by ccordoba12** [comment]
> I just noticed that when I change the max allowed line length in the settings, the vertical line only changes in the active panel. In other open panels it stays at 79 characters.

Hey @joooeey, thanks for mentioning this! I'll fix it as part of this issue too.
