### ISSUE TITLE
TypeError when getting text snippets

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#14183]
## Problem Description
The problem encountered by chance cannot be reproduced. It can be determined that the "sequence" is None under certain special circumstances.

![image](https://user-images.githubusercontent.com/1759365/98640830-b62cf200-2365-11eb-8d39-30bae45d4ab5.png)

## Versions

* Spyder version: 4.2.0
* Python version: 3.7.6
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: win10

**Comment by ccordoba12** [comment]
I don't understand what you mean by this. Could you clarify it?

**Comment by ccordoba12** [comment]
Sorry, I understood it after seeing your screenshot. We'll fix it in our next version.

**Comment by ElieGouzien** [comment]
I can confirm this issue. Not sure why it happens for me and @leavor, but for sure we are not alone, and as the bug window appear as soon as we start typing, it's a critical bug.

I propose a quick fix in #14185, that I suggest to be released as soon as possible.

**Comment by ElieGouzien** [comment]
I was finally able to reproduce this bug (in 4.2.0).
  1. Create a file containing

```
def f_g():
    pass

f_g()
```

  2. put the cursor at the beggining of line `f_g()`
  3. type `_, _` ; the error should pop when writing the last `_`

**Comment by ElieGouzien** [comment]
And now I'm able to reproduce it, I withdraw what I said about criticality, it's a definitely not a critical bug.
