### ISSUE TITLE
Pager when getting help blocks IPython console

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#14192]
## Problem Description
Use "?" in the console to view the function help, 
continue to operate in spyder, 
there is no output in the console, 
nor can it be input in the console, 
even if the kernel is restarted, the problem still exists.

The screen recording is as follows

![spyder控制台输入输出bug](https://user-images.githubusercontent.com/1759365/98793408-d7174500-2442-11eb-9d89-d869410b046d.gif)

## Versions

* Spyder version: 4.2.0
* Python version: 3.6.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: win10

**Comment by impact27** [comment]
You can press escape to exit this mode

**Comment by dalthviz** [comment]
Hi @leavor thanks for the feedback, as @impact27 you need to exit the help mode to be able to use again the console

**Comment by ccordoba12** [comment]
I think this is caused by the removal of the pager option in PR #14056 (which I thought was broken). I'll take care of this one because it's really confusing indeed.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Maybe it's better to add a "press Q to close" rather than restore old behavior, as docs replacing code in IPython window isn't really desired, and the new coloring is richer.

**Comment by ccordoba12** [comment]
Good suggestion, thanks @OverLordGoldDragon!

**Comment by AmerM137** [comment]
@ccordoba12 is there a way to keep the ability to scroll up/down in the pager? A qtconsole instance launched from conda prompt allows for this behavior with pgUP/pgDN or arrow keys, however the embedded spyder console only allows quitting, no scrolling allowed unless it's with the mouse wheel.

With this change I have to take my hands off the keyboard and use the scroll wheel to scroll up to the top to see function arguments for example.

**Comment by ccordoba12** [comment]
Very good point @AmerM137, thanks for bringing it up. Fortunately it was not hard to fix (see pull request #15635). That fix will be part of our next version (5.0.3), to be released tomorrow.

**Comment by AmerM137** [comment]
Much appreciated thank you!
