### ISSUE TITLE
Spyder Won't Launch - Windows 10

### ISSUE THREAD

**Issue by JustinNewport** [spyder-ide/spyder#14196]
I have Windows 10 and Spyder wont even launch for the first time immediately after installing the most recent version of Anaconda. Restarting after install does not resolve. Can't imagine needing to update anything if I'm getting the latest version of everything. (November 11th 2020)

Error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 6, in <module>
    from spyder.app.start import main
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 22, in <module>
    import zmq
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.

**Comment by dalthviz** [comment]
Hi @JustinNewport did you install Anaconda with Administrator rights across the machine or only for your user? What happens if you try to launch Spyder with Admin rights? Checking, issues with a similar traceback have been reported: #13250 (related with admin rights) #13563 (related with a faulty graphics card). Let us know if the info there helps or if you manage to gather more info to try to find the root cause of the issue :)

**Comment by JustinNewport** [comment]
> Hi @JustinNewport did you install Anaconda with Administrator rights across the machine or only for your user? What happens if you try to launch Spyder with Admin rights? Checking, issues with a similar traceback have been reported: #13250 (related with admin rights) #13563 (related with a faulty graphics card). Let us know if the info there helps or if you manage to gather more info to try to find the root cause of the issue :)

Hello @dalthviz, thank you for following up so quickly. I have tried both installing for me as a single user as well as a clean install for the entire machine. I have also tried running Spyder with Admin rights with no success. If launching from start menu, the mouse will spin for a split second, but nothing happens after that. Current GPU installed is 2080 super. 

I will attempt to troubleshoot further and post additional details.

**Comment by JustinNewport** [comment]
Issue finally resolved. Uninstalled ALL (2005, 2008, 2010, 2012, 2013, and 2015-2019) Microsoft Visual C++ Redistributables. Every single one. Repairing wasn't working. Then reinstalled each of them, both the x86 and x64 version.
