### ISSUE TITLE
Ctrl+G cannot jump to python page of method call

### ISSUE THREAD

**Issue by GithubWangXiaoXi** [spyder-ide/spyder#14204]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
"Ctrl + G" or "Ctrl + Left key" cannot jump to python page of method call.
spyder version: 4.1.5

**Comment by ccordoba12** [comment]
Hey @GithubWangXiaoXi, thanks for reporting. Please see my https://github.com/spyder-ide/spyder/issues/14166#issuecomment-723523256 on how to get debug information about your problem.

Please post your findings on that issue as well.
