### ISSUE TITLE
Kernel not starting on Spyder 4.2.0 installed with stand-alone installer

### ISSUE THREAD

**Issue by pj1989** [spyder-ide/spyder#14205]
## Problem Description
When launching Spyder, the following message appears

```
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.10.0 and < 1.11.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels
```

after restarting the kernel, the message becomes:

```
Cannot restart a kernel not started by Spyder
```

In `preferences` > `Python interpreter` is selected `Use the following Python interpreter` pointing to `C:\Users\<username>\AppData\Local\Continuum\anaconda3\python.exe`

I also tried to replace `python.exe` with `pythonw.exe`, but this is reverted automatically.

I have `spyder-kernels` 1.10.0 installed.

## Versions

* Spyder version: 4.2.0
* Python version: 3.7.9 64-bit
* Qt version:  5.12.9
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Windows 10 

### Dependencies
```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  50.3.2 (OK)
sphinx >=0.6.6                  :  3.3.0 (OK)
**spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)**
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  None (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  1.1.4 (OK)
scipy >=0.17.0                  :  1.5.4 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @pj1989, thanks for reporting. You need to install spyder-kernels in the interpreter you selected in preferences to fix this problem. The one you're pointing out is the version that comes with the installer itself. 

For that, you need to open the Anaconda prompt and run there

    conda install spyder-kernels=1.10.0

However, most probably that command will give you an error because conda packages for the new versions of Spyder and spyder-kernels are not available yet.

If that's the case, you need to try again next week.

**Comment by pj1989** [comment]
Installing spyder-kernels 1.10.0 solved the problem. Note however that this had to be done with 
```
conda install -c conda-forge spyder-kernels=1.10.0
```
As per today, `spyder-kernels` are not yet available on `conda`. Running
```
conda install spyder-kernels=1.10.0
```
returns a `PackagesNotFoundError` error.

Also `conda install -c conda-forge spyder-kernels=1.10.0` took a suspiciously long time to run, failing "environment solve" several times. I'm not this familiar with conda, so I'm not sure of what this means.
