### ISSUE TITLE
Spyder closing when trying to view pandas dataframe in the variable explorer while connected to kernel

### ISSUE THREAD

**Issue by shankyemcee** [spyder-ide/spyder#14212]
I am using spyder 4.1.4. When i am connected to a local kernel, and i try to open the pandas dataframe in the variable explorer spyder shuts down.

**Comment by juanis2112** [comment]
Hi @shankyemcee, thanks for reporting this. Can you please update to our latest version 4.1.5.
In your terminal or anaconda prompt (if you are using Windows) type:
```
conda update anaconda
conda install spyder=4.1.5
```

**Comment by juanis2112** [comment]
If the error persists can you please post a screenshot of the dataframe you are trying to visualize?

**Comment by shankyemcee** [comment]
Appears to be working now. Thanks.
