### ISSUE TITLE
Improvements to the Windows installer

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#14220]
Some things we didn't have time to implement for 4.2.0, but that we'd like to have in our Windows installer are:

* Add a context menu entry to the Windows Explorer so that people can open files in Spyder directly from it.
* Add the [rtree wheel](https://www.lfd.uci.edu/~gohlke/pythonlibs/#rtree) from Christoph Gohlke's unofficial wheels repository, so we can have code and text snippets in our Windows app. That's not part of our setup.py because there are no wheels available for that package and it's very hard to compile.

**Comment by Qaazi** [comment]
C Cordoba....what the hell have u guys done to spyder?????
its has been two months it all messed up
nothing works
have tried re-installing it...re-installing spyder kernels, and all the help on stackoverflow
nothing works

spyder doesnt just work at all

i want to throw it into dustbin
