### ISSUE TITLE
spyder 4.1.5 no response

### ISSUE THREAD

**Issue by jessezwd** [spyder-ide/spyder#14224]
I am using spyder 4.1.5, newly installed on Manjarolinux 20.2. the launch seems ok, but it stuck at the first interface, no response to any keyboard or mouse input.

**Comment by ccordoba12** [comment]
Hey @jessezwd, thanks for reporting. Please open a bug report in your Linux distro bug tracker for this. 

Unfortunately we don't have the resources nor the time to give support to installation methods other than Anaconda.

**Comment by jessezwd** [comment]
@ccordoba12 thanks! I got this message: spyder_kernels >=1.9.4;<1.10.0 : 1.10.0(NOK).
and I have spyder_kernels 1.10.0 installed.

**Comment by ccordoba12** [comment]
If you're using Spyder 4.1.5, you need to use spyder-kernels 1.9.4, not 1.10.0. That's the problem you're having.

**Comment by jessezwd** [comment]
@ccordoba12 ok, thanks!
