### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by yomoko** [spyder-ide/spyder#14237]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
```
Traceback (most recent call last):
File "C:\programdata\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\programdata\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\programdata\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\programdata\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "C:\programdata\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "C:\programdata\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 36, in 
from IPython.core.inputtransformer2 import (
ImportError: cannot import name 'leading_empty_lines' from 'IPython.core.inputtransformer2' (C:\programdata\Anaconda3\lib\site‑packages\IPython\core\inputtransformer2.py)

```

### What steps reproduce the problem?

1.  conda install -c anaconda spyder=4.2.0
2. When it's open , it's like that
3. After installing the kernel `conda install spyder-kernels=1.10` it's the same

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @yomoko,

Can you please update anaconda first before installing spyder and spyder-kernels?
```
conda update anaconda
conda install spyder=4.2.0
```

Let me know if that works

**Comment by ccordoba12** [comment]
@steff456, this was already reported in spyder-ide/spyder-kernels#256 and it was introduced in spyder-kernels 1.10.0, which was is required for Spyder 4.2.0

@yomoko, we'll fix this in spyder-kernels and release a new version soon. In the meantime, please run

    conda update ipython

to fix this problem.

**Comment by yomoko** [comment]
@steff456 Is it a must? I don't update on purpose. There's always problems with new version. Such as spyder.....

**Comment by ccordoba12** [comment]
It is if you want this problem solved. Our fix will be basically to require a new IPython version in spyder-kernels.
