### ISSUE TITLE
1st Project_GSIMPLEE

### ISSUE THREAD

**Issue by Yaducode** [spyder-ide/spyder#14235]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @Yaducode, thanks for reporting. Unfortunately, this issue is empty.

Could you describe your problem?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
