### ISSUE TITLE
Add wheel for rtree to Mac installer

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#14243]
We don't declare `rtree` as a dependency in our `setup.py` because it's a binary package and doesn't have wheels in PyPI.

So to add it to the Mac app we'd have either to find a Mac wheel for it (easy) or to compile it in Github Actions (hard).

@mrclary, could you take a look at this one?

**Comment by mrclary** [comment]
@ccordoba12, code snippets are working on macOS app. What exactly was `rtree` used for? Is there some behavior that I can look at?

**Comment by ccordoba12** [comment]
`rtree` allows us tp paint a box around the snippet regions, so users can move between them using `Tab`. Could you test for that?

**Comment by mrclary** [comment]
@ccordoba12 @dalthviz, FYI I think that Toblerity/rtree#163 will have wheels uploaded to PyPi soon for windows, linux, and macOS.
