### ISSUE TITLE
can not install spyder using pip!

### ISSUE THREAD

**Issue by zengdabo** [spyder-ide/spyder#14240]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

can not install spyder using pip!

### What steps reproduce the problem?

1.  python3 -m pip  -U pip
2.  python3 -m pip  -U spyder
3. 

### What is the expected output? What do you see instead?

ERROR: Could not find a version that satisfies the requirement pyqtwebengine<5.13 (from spyder) (from versions: 5.14.0, 5.15.0, 5.15.1)
ERROR: No matching distribution found for pyqtwebengine<5.13 (from spyder)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  4.2.0
* Python version:  3.7.3
* Qt version: 
* PyQt version: 
* Operating System name/version: 

Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> Distributor ID: Raspbian

Hey @zengdabo, thanks for reporting. Unfortunately, Spyder is not supported in Raspberry Pi due precisely to our usage of the `pyqtwebengine` package. The thing is there are no `pyqtwebengine` packages provided for Arm64 in PyPI, sorry.
