### ISSUE TITLE
different result in spyder 4.1.5

### ISSUE THREAD

**Issue by devineniraghava** [spyder-ide/spyder#14255]
### What steps will reproduce the problem?

 I have some code that makes some calculations with dataframes. 
 
 I run the same code in spyder 4.1.5 and 3.3.6
 
 The console shows a different result. The result displayed in the console in different, but when I print or save the result both versions of spyder have the same result. 

The same is true if I try to access any given data from my class. The data displayed is simply inconsistent

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.8
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.3 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```
![Screenshot 2020-11-18 144718](https://user-images.githubusercontent.com/64875320/99538505-58278c80-29ad-11eb-931e-9f8278868fc6.png)
![Screenshot 2020-11-18 144854](https://user-images.githubusercontent.com/64875320/99538508-58c02300-29ad-11eb-8c1e-214f302729e0.png)

**Comment by danieltomasz** [comment]
Maybe there some variables that are not cleared in some instance or you are actually doing different operations earlier in the console? Could you clean all the variables or reset kernel and repeat exactly the same steps in the console for both instances ?

Could you share Minimal Working Example of your code to  be able reproduce this issue?

**Comment by dalthviz** [comment]
Hi @devineniraghava could you check your run preferences (`Run > Configuration per file...` or `Ctrl + F6` to see them)? Maybe you need to check or uncheck the option `Run in console's namespace instead of an empty one`.

If you keep experiencing different execution result after changing the Run options, an example code snippet will be greatly appreciated. Without a reproducible example there is not much we can do, sorry :/

Also, thanks @danieltomasz for giving some suggestion to try to better understand the issue :+1:

**Comment by dalthviz** [comment]
Closing due to lack of response
