### ISSUE TITLE
How to downgrade python version on spyder?

### ISSUE THREAD

**Issue by bhnrus** [spyder-ide/spyder#14250]
Hi, 
I recently upgraded my ubuntu from 16.04 to 20.04, and it upgraded my spyder to python 3.8 version. I would like to come back to the python 2.7 version. I tried to change the python interpreter, but it seems the path I selected (the python 2.7 folder in my usr/ folder) was not valid. how to bring back the good-old python 2.7? 
Thanks!
_

**Comment by dalthviz** [comment]
Hi @bhnrus my guess is that you should use some sort of environment (using [virtualenv, pyenv, conda, etc](https://stackoverflow.com/a/41573588) to create it) with the Python version and packages you want to use instead of messing with your OS Python. Hope this info helps you with your setup :)
