### ISSUE TITLE
Make filenames for Spyder pickled data specific for Python version

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1425]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-03T14:27:27Z_

Seems like I am running into problems testing Spyder 2.3.0dev2 with both Python 2 and Python 3. I can not be sure, but it looks like some configuration data pickled by Python 2 can not be unpickled by Python 3.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1425_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-07T09:41:46Z_

I think it depends on your Python versions: if you have 3.3 and 2.7 it should work without problems, but to test it with 3.2 and 2.7 you need to run first

spyder --reset

Is that right Jed?

**Cc:** jed.lud...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-06-07T10:48:52Z_

The project workspace information is stored in pickle format, and there is an incompatibility between 2 and 3. I don't know if that is a basic limitation of Python or if it relates to Spyder's use of pickle. Haven't had time to investigate any further than that.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-08T03:06:33Z_

How often the workspace information needs to be serialized and restored? Can we use human-readable format for it like YAML? This will add cross-language compatibility for foreseeable future, change tracking, migrations from version to version, external tools and easy troubleshooting.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-09-09T07:24:08Z_

**Cc:** -jed.lud...@gmail.com

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T12:44:02Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:42:50Z_

**Labels:** -MS-v2.3.1 MS-v2.4

**Comment by bilderbuchi** [comment]
+1 on human-readable workspace and project files. These files seem to change every time spyder is restarted, which is kinda annoying if you use a version control system. At least with human-readable format, I'd get a meaningful diff.

On a related note, maybe the part of the workspace/project definition that changes on every restart (open file count? viewer positions?) could be delegated out into a separate file, which could then be ignored by your VCS to eliminate meaningless noise.

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.0 when we rewrote Projects from scratch. They save plain text files now instead of pickled ones.
