### ISSUE TITLE
Update or create new Mac installers for Big Sur

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#14257]
Users have reported on issues #14218 and #14222 that our Mac installers are not working on Big Sur (they simply crash at startup). So it'd be nice if for our next version we can make them work for that Mac version.

@mrclary, could you take care of this one?

**Comment by mrclary** [comment]
I'll have to upgrade to Big Sur first to test it out. Is Big Sur available yet for GitHub Actions? It may be as simple as running the build on the new OS. But then we'll need to check that it's backward compatible. If not, we can add multiple operating systems to the matrix build...

**Comment by mrclary** [comment]
Okay, I've caught up on those issues mentioned, including #14256. I'm not sure that we'll need to change anything for the Mac installer. It looks like updating Qt and/or adding QT_MAC_WANTS_LAYER to `start.py` will resolve the issue. Am I wrong?

**Comment by mrclary** [comment]
Nevertheless, I'll update one of my computers to Big Sur to test the build process and backward compatibility.

**Comment by impact27** [comment]
My understanding is that updating Qt from 5.9 to 5.12 resolves the sluggishness of the editor (at least partially) and using  QT_MAC_WANTS_LAYER=1 allows the app to be launched. I am not sure why sometimes  QT_MAC_WANTS_LAYER is needed (for me with conda python) and sometimes not (for me with brew python).
Seeing how this is quite a bad issue and a lot of people are updating to Big Sur, should we consider releasing 4.2.1 sooner than planned?

**Comment by ccordoba12** [comment]
@impact27, I understand your concern. However, we're trying to adjust our schedule to release a new version every six weeks and making a new release now would disrupt our planning for the next six months (yes, we're also trying to make longer term plans). Fortunately, there's now a workaround and people will be able to use Spyder in the meantime.

Another possibility would be to generate a new installer only with PR #14256 (which is a very simple patch) and make an announcement about it. But for that we'd need to change our Github action to upload a new artifact not only `on_release`,  but also when instructed and applying certain patches (or copying files to certain locations). @mrclary, what do you think?

**Comment by mrclary** [comment]
@ccordoba12 @impact27, I suppose what we are really talking about is "hot fixes", but I don't have the experience to say how that should be handled. But for now, I think the easiest thing is for users to grab the artifact from the PR build of #14256. We've instructed others to do this for the purpose of testing before.

Indeed, there is no reason why this can't be done for other issues either (such as #14269). If there are a few of these issues that can be resolved fairly quickly, then their PRs could easily be rebased on top of each other before, and before we make any substantive updates to the code base, then we could point users to the last PR build as a "patch" until our next scheduled release (in ~month).

I don't see any reason why this couldn't be a standard option for app users: the next release is always at most about 6 weeks away; if an issue is so important that they can't wait, then any relevant PR build should carry them through...

**Comment by mrclary** [comment]
Ultimately, post build testing is required to preempt issues such as #14269, and testing new (beta) operating systems in advance of their release would help us preempt issues such as #14222. Is it possible to get beta operating systems for Github Actions?

**Comment by ccordoba12** [comment]
Hey @mrclary, sorry for not answering this one but in the end I decided to not update our installers and leave them to be fixed in 4.2.1.

I'd just like to ask you: is the full installer working on Big Sur?

@impact27, if you're in Big Sur already, could you give us a hand testing the full installer as well? Thanks!

**Comment by mrclary** [comment]
> I'd just like to ask you: is the full installer working on Big Sur?

Unfortunately, I am unable to test at this time. I have two computers: my personal iMac (late 2013), which I discovered will not support Big Sur; and my work Macbook Pro 16" (really nice!), which I'm currently prohibited from updated to Big Sur at this time.

I expected to install Big Sur in VMWare Fusion on my Macbook, but was unable to do so. I seem to have been able to successfully create the installer iso disk image, but VMWare won't bootup into it for installation...
If anyone has some insight here, I'd greatly appreciate it.

**Comment by mrclary** [comment]
@ccordoba12 , I now have access to Big Sur on a separate machine. I can confirm that our latest 4.2.1 macOS installer (which includes the QT_MAC_WANTS_LAYER fix) _does_ work on macOS 11.1. I have not yet tested _building_ on 11.1 yet, but I don't think that is an issue at this time since building on Catalina is working just fine.

I think we can close this issue. When our GitHub action `runs-on: macos-latest` actually moves to Big Sur, we can investigate any issues that may arise. In particular, we may want to watch for the ability to build on Apple silicon as well.

**Comment by ccordoba12** [comment]
> I can confirm that our latest 4.2.1 macOS installer (which includes the QT_MAC_WANTS_LAYER fix) does work on macOS 11.1

That's great to know! Thanks for the confirmation.

> I think we can close this issue. When our GitHub action runs-on: macos-latest actually moves to Big Sur, we can investigate any issues that may arise. In particular, we may want to watch for the ability to build on Apple silicon as well.

I think we should keep building our installers in Catalina for all people that don't want or is unable to upgrade to Big Sur.
