### ISSUE TITLE
not able to install spyder 4.2.0 via conda

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#14260]
hi im using spyder 4.1.4 and interested in upgrading to 4.2.0 but I cannot.
I am using ubuntu 16.04 python 3.6.6
Im using spyder through anaconda.
here is what I did:
```
conda update spyder
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.
```
then 
```
conda install spyder=4.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=4.2.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

hmmm any suggestion?

**Comment by dalthviz** [comment]
Hi @seyeeet usually there is a delay between the release done in PyPI and the package being available through conda. Usually takes a couple of days for a new version of Spyder to be available in the default anaconda channel. For now please wait a little bit more, probably in the upcoming days the package will be available. For more details about the release you can check: https://github.com/spyder-ide/spyder/releases/tag/v4.2.0
