### ISSUE TITLE
!git add "file.py" !git commit -m "My commit" !git push origin master

### ISSUE THREAD

**Issue by TDMVu18** [spyder-ide/spyder#14285]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @TDMVu18, thanks for reporting. I don't understand your problem, but if you're running `git` commands in our IPython console and they're not working as expected, please use a proper system terminal (xterm on Linux, Terminal.app on macOS or cmd.exe on Windows) to run them.

You can install and use our plugin to embed terminals: [spyder-terminal](https://github.com/spyder-ide/spyder-terminal).

**Comment by akibkamani** [comment]
try 
git push origin main

**Comment by ccordoba12** [comment]
Closing due to lack of response.
