### ISSUE TITLE
crash when open pandas dataframe from Variable Explorer

### ISSUE THREAD

**Issue by YaoLIII** [spyder-ide/spyder#14294]
### What steps will reproduce the problem?

1. I samply read a dataframe from an csv file (df = pd.readcsv('file.csv'))

2. when double clike variable df at Variable Explorer, to check the df, Spyder crashed and closed automatically

3. The dataframe is only 3*12, so it's quite small. Didn't understand why this happened... Version is 4.1.4

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @YaoLIII, thanks for reporting. Please post your dataframe so we can try to reproduce the error you're seeing in our side.

**Comment by YaoLIII** [comment]
Thank you for the quick response, here is my data:
[df.zip](https://github.com/spyder-ide/spyder/files/5584049/df.zip)

**Comment by ccordoba12** [comment]
@YaoLIII, I don't see anything strange in your dataframe. Perhaps your problem could be solved by updating.

Please do that by opening the Anaconda Prompt and running there

    conda install pandas=1.1

**Comment by ccordoba12** [comment]
Closing due to lack of response.
