### ISSUE TITLE
internal problem spyder 

### ISSUE THREAD

**Issue by himmel101** [spyder-ide/spyder#14291]
### What steps will reproduce the problem?

#The final recommendation table
movies_df.loc[movies_df['movieId'].isin(recommendationTable_df.head(20).keys())]

used print('\n\n', the above,'\n)

Module 5, Machine Learning, Content Based Recommender system

/home/john/Downloads/ML0101EN-RecSys-Content-Based-movies-py-v1(1).ipynb

### Traceback
```python-traceback
  File "/home/john/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "/home/john/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "/home/john/anaconda3/lib/python3.7/site-packages/spyder/plugins/editor/utils/autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: '/home/john/.config/spyder-py3/autosave/Mod_5_Content_Based_Rec_211120.py'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-53-generic

### Dependencies

```
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.6.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.19.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
keyring                      :  None (OK)
nbconvert >=4.0              :  6.0.7 (OK)
numpydoc >=0.6.0             :  1.1.0 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.7.2 (OK)
pygments >=2.0               :  2.7.2 (OK)
pylint >=0.25                :  2.6.0 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
xdg >=0.26                   :  0.27 (OK)
zmq >=17                     :  19.0.2 (OK)
qdarkstyle >=2.7             :  2.8.1 (OK)
qtawesome >=0.5.7            :  1.0.1 (OK)
qtconsole >=4.6.0            :  4.7.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.4 (OK)
sphinx >=0.6.6               :  3.2.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  0.29.21 (OK)
matplotlib >=2.0.0           :  3.3.2 (OK)
numpy >=1.7                  :  1.19.2 (OK)
pandas >=0.13.1              :  1.1.3 (OK)
scipy >=0.17.0               :  1.5.2 (OK)
sympy >=0.7.3                :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @himmel101, thanks for reporting. This problem is fixed in our latest version. Please update by closing Spyder, opening a terminal and running there

    conda update anaconda
    conda install spyder=4.1.5

**Comment by himmel101** [comment]
Hi Carlos

Actually I think the problem was caused by a typo because I copy / pasted
the code after the error and it worked fine.
But I am having a problem updating spyder to 4.1.5 in my ubuntu anaconda
navigator.

No solution yet for that.

Thanks

John

**Comment by ccordoba12** [comment]
> But I am having a problem updating spyder to 4.1.5 in my ubuntu anaconda
navigator.

Please use the terminal and run the command I posted above. Updating Spyder won't work through Navigator because it doesn't run the first command.
