### ISSUE TITLE
Spyder 4.1.5 Controversial behavior of autocompletion

### ISSUE THREAD

**Issue by capitanevs** [spyder-ide/spyder#14299]
Hi,

I am experiencing some issues with the autocompletion system of Spyder 4.1.x (in Anaconda, Windows10)

With "autocompletion" I mean both the Listbox where items appear and the tooltip where documentation on the syntax appears.

I looked for some open issues, but I didn't find any. Please, redirect me to more appropriate places if need be.

I have gathered two examples.

 In Spyder 4.1.4

**Example1)**
The old version of spyder:
![immagine](https://user-images.githubusercontent.com/13431660/99983543-46c6f180-2dac-11eb-80b4-1d0862f2c904.png)

New version of spyder:
![immagine](https://user-images.githubusercontent.com/13431660/99984054-e84e4300-2dac-11eb-8e86-643ef5def462.png)
I don't know if this a feature or a bug, but I think it is less effective because it does not provide information on the function unless I specifically write it. 

**Example 2)**
I load a certain module, and I get a partial autocompletion list:
![immagine](https://user-images.githubusercontent.com/13431660/99984915-f18bdf80-2dad-11eb-9862-67de3aeb815b.png)

Then I "mess around" (see below) with the cursor, and I get a complete autocompletion list
![immagine](https://user-images.githubusercontent.com/13431660/99984966-00729200-2dae-11eb-8670-e3959dc0e61c.png)

"mess around" =  I put the cursor to the end of the import line (#7), then press enter, then type “rm.”.  Conversely, if I just start typing anywhere in the sheet "rm." , I get an “incomplete list”.

Today I upgraded spyder to Version 4.1.5. The situation got even worse... the autocompletion list is totally empty.

![immagine](https://user-images.githubusercontent.com/13431660/99985746-a0c8b680-2dae-11eb-9951-88e0fb1e8556.png)

The code is working properly. LibWiser is a folder (set in python search path). The autocompletion system correctly works in the console.
![immagine](https://user-images.githubusercontent.com/13431660/99986094-0fa60f80-2daf-11eb-89fd-a697729ae399.png)

I have tried to restart LSP, Kite, etc but with no success.

Do you have any suggestions?

Thanks!

Mike

**Comment by dalthviz** [comment]
Hi @capitanevs thanks for the feedback! Maybe this is related with the LSP not finding the path to your local package. Are you adding the dir of your package inside the `PYTHONPATH` option that Spyder (`Tools > PYTHONPATH manager`) uses or outside as an env variable?

**Comment by capitanevs** [comment]
Hi dalthviz,
thanks for answering.

Yes, PYTHONPATH variable is ok (I used the "sync" command in the "Python Path Manager" window).

Actually, now Idid another test. I have disabled Kite, and my LSP is totally stuck.
Even
`import numpy as np
np.
`
leaves me without any autocompletion :-(

Is this normal? 

LSP results as "ready", indeed.

**Comment by dalthviz** [comment]
Um not having completions seems like an error then (if you have numpy installed in the environment selected for the interpreter in the preferences).

Could you try to run Spyder from cmd/anaconda prompt/terminal with the `debug-info` flag? Something like `spyder --debug-info verbose` and check if any error gets log?

Also, could you provide us more info about your setup (OS, Python version, dependencies version, etc)? the more detailed description of your setup we can get the easier will be to see what can be done or if is an issue solvable from Spyder itself

**Comment by capitanevs** [comment]
Hi Daniel,

perhaps you got it. I run spyder with ` spyder --debug-info verbose`. Here's what I get:

```
2020-11-26 10:50:17,584 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 10 Got response from lsp
2020-11-26 10:50:17,584 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 10 removed
2020-11-26 10:50:17,584 [DEBUG] [spyder.plugins.completion.plugin] -> Gather responses for textDocument/foldingRange
2020-11-26 10:50:17,684 [DEBUG] [spyder.plugins.completion.languageserver.client] -> python Response error: {'code': -32602, 'message': 'jedi.api.environment.InvalidPythonEnvironment: Could not get version information for \'C:\\\\ProgramData\\\\Anaconda3\\\\python.exe\': InternalError("The subprocess C:\\\\ProgramData\\\\Anaconda3\\\\python.exe has crashed (EOFError(\'Ran out of input\',), stderr=).",)', 'data': {'traceback': ['  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls_jsonrpc\\endpoint.py", line 113, in consume\n    self._handle_request(message[\'id\'], message[\'method\'], message.get(\'params\'))\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls_jsonrpc\\endpoint.py", line 182, in _handle_request\n    handler_result = handler(params)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls_jsonrpc\\dispatchers.py", line 23, in handler\n    return method(**(params or {}))\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\python_ls.py", line 334, in m_text_document__document_symbol\n    return self.document_symbols(textDocument[\'uri\'])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\python_ls.py", line 250, in document_symbols\n    return flatten(self._hook(\'pyls_document_symbols\', doc_uri))\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\python_ls.py", line 156, in _hook\n    return hook_handlers(config=self.config, workspace=workspace, document=doc, **kwargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\hooks.py", line 286, in __call__\n    return self._hookexec(self, self.get_hookimpls(), kwargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\manager.py", line 93, in _hookexec\n    return self._inner_hookexec(hook, methods, kwargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\manager.py", line 337, in traced_hookexec\n    return outcome.get_result()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py", line 52, in from_call\n    result = func()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\manager.py", line 335, in <lambda>\n    outcome = _Result.from_call(lambda: oldcall(hook, hook_impls, kwargs))\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\manager.py", line 87, in <lambda>\n    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py", line 208, in _multicall\n    return outcome.get_result()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py", line 80, in get_result\n    raise ex[1].with_traceback(ex[2])\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pluggy\\callers.py", line 187, in _multicall\n    res = hook_impl.function(*args)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\plugins\\symbols.py", line 12, in pyls_document_symbols\n    definitions = document.jedi_names(all_scopes=all_scopes)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\workspace.py", line 221, in jedi_names\n    script = self.jedi_script()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\workspace.py", line 235, in jedi_script\n    sys_path = self.sys_path(environment_path) + extra_paths\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\pyls\\workspace.py", line 268, in sys_path\n    path.extend(environment.get_sys_path())\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jedi\\cache.py", line 111, in wrapper\n    result = method(self, *args, **kwargs)\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jedi\\api\\environment.py", line 129, in get_sys_path\n    return self._get_subprocess().get_sys_path()\n', '  File "C:\\ProgramData\\Anaconda3\\lib\\site-packages\\jedi\\api\\environment.py", line 80, in _get_subprocess\n    exc))\n']}}
2020-11-26 10:50:17,684 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 11 Got response from lsp
2020-11-26 10:50:17,684 [DEBUG] [spyder.plugins.completion.plugin] -> Completion plugin: Request 11 removed
2020-11-26 10:50:17,684 [DEBUG] [spyder.plugins.completion.plugin] -> Gather responses for textDocument/documentSymbol
2020-11-26 10:50:19,927 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/status?filename=D%3A%5CTopics%5CSimulazioni+FERMI2%5CMixed+Scans%5CInvestigator_BatchLauncher_Theta_Fermi2.py HTTP/1.1" 200 76
2020-11-26 10:50:20,842 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/status?filename=D%3A%5CTopics%5CWISEr%5CExamples+2020%5CTest+grating%5Ctest_grating_nov_01.py HTTP/1.1" 200 76
2020-11-26 10:50:20,842 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Set focus to: D:\Topics\WISEr\Examples 2020\Test grating\test_grating_nov_01.py
2020-11-26 10:50:20,842 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Current changed: 3 - D:\Topics\WISEr\Examples 2020\Test grating\test_grating_nov_01.py
2020-11-26 10:50:20,846 [DEBUG] [urllib3.connectionpool] -> http://127.0.0.1:46624 "GET /clientapi/status?filename=D%3A%5CTopics%5CWISEr%5CExamples+2020%5CTest+grating%5Ctest_grating_nov_01.py HTTP/1.1" 200 76
```

It seems that line 4 reports some error, probably connected with "non getting the python environment"?

I have spyder 4.1.5, installed with Anaconda (also python is installed with anaconda, version 4.6.5; OS: Windows10). Please, just tell me if you need more.
Thanks,
Mike

**Comment by dalthviz** [comment]
Seems like a problem with Jedi. What is the version of Jedi you are using? could you try running something like `conda install -f jedi=0.17.1 python-language-server=0.34.1` and see if that helps?

Also, can you paste here what `conda list` gives you in the current env you are working? Thanks!

**Comment by capitanevs** [comment]
HI Daniel,

sorry for the late feedback.

I attempted the `conda install`, which went fine, but did not the improve the situation. My test is always doing
`import numpy as np
np.[see if autocompletion appears]`

and any time I see no autocompletion (I have de-activated Kite).

This is the output of conda list.

It seems that there is something quite deep which is not working . If you think that it might be useful to keep on investigating, for me it's ok. Otherwise I can just uninstall anaconda and do a fresh installation, and see how it goes.

Thanks, 
(also do CAM.Gerlach for correcting the title)

Mike

`C:\Users\Mike>conda list
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
alabaster                 0.7.12                   py36_0
anaconda-client           1.7.2                    py36_0
anaconda-navigator        1.9.12                   py36_0
argh                      0.26.2                   py36_0
astroid                   2.4.2                    py36_0
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.5.3                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.1.7            py36he774522_1
beautifulsoup4            4.9.1                    py36_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
brotlipy                  0.7.0           py36he774522_1000
ca-certificates           2020.10.14                    0
certifi                   2020.11.8        py36haa95532_0
cffi                      1.14.0           py36h7a1dbc1_0
chardet                   3.0.4                 py36_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py36_1
colorama                  0.4.3                      py_0
conda                     4.9.2            py36haa95532_0
conda-build               3.10.5                   py36_0
conda-package-handling    1.6.1            py36h62dcd97_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                h6bb2dd7_3
cryptography              2.9.2            py36h7a1dbc1_0
cycler                    0.10.0           py36h009560c_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
docutils                  0.16                     py36_1
engineering-notation      0.6.0                    pypi_0    pypi
entrypoints               0.3                      py36_0
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
freetype                  2.10.2               hd328e21_0
future                    0.18.2                   py36_1
glob2                     0.7                        py_0
h5glance                  0.6                      pypi_0    pypi
h5py                      2.10.0           py36h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
htmlgen                   1.2.2                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py36_0
importlib_metadata        1.7.0                         0
intel-openmp              2019.4                      245
intervaltree              3.0.2                      py_1
ipykernel                 5.3.4            py36h5ca1d4c_0
ipython                   7.16.1           py36h5ca1d4c_0
ipython_genutils          0.2.0                    py36_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py36_0
jedi                      0.17.1                   py36_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py36_0
jupyter_client            6.1.6                      py_0
jupyter_core              4.6.3                    py36_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
keyring                   21.2.1                   py36_0
kiwisolver                1.2.0            py36h74a9793_0
lazy-object-proxy         1.4.3            py36he774522_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libtiff                   4.1.0                h56a325e_1
llvmlite                  0.31.0           py36ha925a31_0
lz4-c                     1.9.2                h62dcd97_1
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py36he774522_0
mat4py                    0.4.2                    pypi_0    pypi
matlabruntimeforpython    R2017a                   pypi_0    pypi
matplotlib                3.1.1            py36hc8f65d3_0
mccabe                    0.6.1                    py36_1
menuinst                  1.4.16           py36he774522_1
mistune                   0.8.4            py36he774522_0
mkl                       2018.0.3                      1
msgpack                   0.6.1                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
navigator-updater         0.2.1                    py36_0
nbconvert                 5.6.1                    py36_0
nbformat                  5.0.7                      py_0
notebook                  6.0.3                    py36_0
numba                     0.47.0           py36hf9181ef_0
numpy                     1.14.3                   pypi_0    pypi
numpydoc                  1.1.0                      py_0
olefile                   0.46                     py36_0
openssl                   1.1.1h               he774522_0
packaging                 20.4                       py_0
pandas                    0.25.3           py36ha925a31_0
pandoc                    2.10                          0
pandocfilters             1.4.2                    py36_1
paramiko                  2.7.1                      py_0
parso                     0.7.0                      py_0
pathtools                 0.1.2                      py_1
pexpect                   4.8.0                    py36_0
pickleshare               0.7.5                    py36_0
pillow                    7.2.0            py36hcc1f983_0
pip                       19.3.1                   pypi_0    pypi
pkginfo                   1.5.0.1                  py36_0
playsound                 1.2.2                    pypi_0    pypi
plotly                    2.7.0                    pypi_0    pypi
pluggy                    0.13.1                   py36_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
psutil                    5.7.0            py36he774522_0
pycodestyle               2.6.0                      py_0
pycosat                   0.6.3            py36he774522_0
pycparser                 2.20                       py_2
pydocstyle                5.0.2                      py_0
pyflakes                  2.2.0                      py_0
pygments                  2.6.1                      py_0
pyjwt                     1.7.1                    pypi_0    pypi
pylint                    2.5.3                    py36_0
pynacl                    1.4.0            py36h62dcd97_1
pyopenssl                 19.1.0                     py_1
pyparsing                 2.4.7                      py_0
pypubsub                  4.0.3                    pypi_0    pypi
pyqt                      5.9.2            py36h6538335_2
pyqt5-sip                 12.7.1                   pypi_0    pypi
pyreadline                2.1                      py36_1
pyrsistent                0.16.0           py36he774522_0
pysocks                   1.7.1                    py36_0
pytango                   9.3.1                    pypi_0    pypi
python                    3.6.5                h0c2934d_0
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_1
python-language-server    0.34.1                   py36_0
pytz                      2020.1                     py_0
pywin32                   227              py36he774522_1
pywin32-ctypes            0.2.0                 py36_1000
pywinpty                  0.5.7                    py36_0
pyyaml                    5.3.1            py36he774522_1
pyzmq                     19.0.1           py36ha925a31_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
recordclass               0.12.1                   pypi_0    pypi
requests                  2.24.0                     py_0
requests-toolbelt         0.8.0                    pypi_0    pypi
rope                      0.17.0                     py_0
rtree                     0.9.4            py36h21ff451_1
ruamel_yaml               0.15.87          py36he774522_1
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.1.0            py36hc28095f_0
send2trash                1.5.0                    py36_0
setuptools                49.2.0                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.14.0                   pypi_0    pypi
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.1.2                      py_0
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.1.5                    py36_0
spyder-kernels            1.9.4                    py36_0
sqlite                    3.32.3               h2a8f88b_0
srxraylib                 1.0.29                   pypi_0    pypi
syned                     1.0.16                   pypi_0    pypi
tbb                       2020.0               h74a9793_0
terminado                 0.8.3                    py36_0
testpath                  0.4.4                      py_0
tk                        8.6.10               he774522_0
toml                      0.10.1                     py_0
tornado                   6.0.4            py36he774522_1
tqdm                      4.23.4                   pypi_0    pypi
traitlets                 4.3.3                    py36_0
twine                     1.11.0                   pypi_0    pypi
typed-ast                 1.4.1            py36he774522_0
ujson                     1.35             py36hfa6e2cd_0
urllib3                   1.25.9                     py_0
vboxapi                   1.0                      pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py36_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py36_1
wheel                     0.34.2                   py36_0
widgetsnbextension        3.5.1                    py36_0
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
winpty                    0.4.3                         4
wiselib2                  1.0.2                     dev_0    <develop>
wofry                     1.0.23                   pypi_0    pypi
wofrywise2                1.0.1                    pypi_0    pypi
wrapt                     1.11.2           py36he774522_0
xlrd                      1.2.0                    py36_0
xlwt                      1.3.0            py36h1a4751e_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
zeromq                    4.3.2                ha925a31_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zoomus                    1.1.3                    pypi_0    pypi
zstd                      1.4.5                h04227a9_0`

**Comment by dalthviz** [comment]
Thanks for the feedback @capitanevs maybe you could try to update to Spyder 4.2.0 and check if that helps but currently it is only available through conda-forge. If you want to try that you will need to run something like `conda install spyder=4.2.0 -c conda-forge`. However, since you are using your base env and you have some pip installed packages there, I'm not totally sure if there could be unexpected result caused by mixing packages sources (anaconda v.s conda-forge v.s pip).

But as is possible for you to just uninstall anaconda I would say that you could:

* Try the update (`conda install spyder=4.2.0 -c conda-forge`)
* If it seems like is still not working, try a full reinstall of Anaconda.

Let us know if that helps :)

**Comment by capitanevs** [comment]
Hi Daniel.

Things are getting worse :-)

Updating spyder to 4.2 did not solve the problem, so I decided to uninstall and reinstall Anaconda on my laptop (Windows10).

I downloaded the latest version from Anaconda home page, apparently all went ok.

BUT...

it seems that neither python nor anaconda are properly linked to the system.
If I press [win] + start typing "anaconda" or "spyder" nothing appears (it used to), and if I go to the prompt and type python commands such as "pip" "conda" "spyder" they are not found.

I tried to uninstall and reinstall several times, but without success...

If I go to the "anaconda\script" folder and attempt to launch spyder, I finally get this error message (never had this problem before in so many years!)

![immagine](https://user-images.githubusercontent.com/13431660/100868995-ad2ecc80-349c-11eb-8b16-31d358097757.png)

Now I do not really know what to do to have python back working again. 
I will keep on attempting. If in the meanwhile you have some clue, it will be very much appreciated :-)

Thanks!

Mike

![immagine](https://user-images.githubusercontent.com/13431660/100868155-80c68080-349b-11eb-840b-09348a57e4e4.png)

**Comment by capitanevs** [comment]
Hi Daniel,

I have some conclusive news.

- Installing the new version of spyder did not solve the problem, so I went through a fresh installation of Anaconda (it gave me some problems, I wrote a post which I have deleted, so ignore the notification).
- I also have installed anaconda on another win10 laptop (which had never seen Python Again).
- By comparing the two laptops I can confirm/better state the behavior I originally posted.

1. If I type `import.numpy ` then `numpy.` the autocompletion list will appear, but **after an exceedingly long time**, that is approximately 6 seconds (4/5 blinks of the cursor). 

2. The autocompletion coming with numpy does not really look nice. It misses some important features

2a. Certain members which clearly are functions are marked as "module", such as 'abs'
![immagine](https://user-images.githubusercontent.com/13431660/100875201-ff282000-34a5-11eb-9d85-0d586a75f626.png)

2b.  I still do not have documentation/tooltip details in the **editor**, but I can get both of them in the console (always talking about numpy)

2c. If I start typing `np.ar[+tab]`, looking for the autocompletion of 'arange', spyder does not react.

3.If I attempt the same procedure on a module I wrote, certain things work better. I get the autocompletion in a **shorter but still long time** (1-3 sec, depending on the module)
2a. attributes are correctly marked.
2b. I have documentation in both editor and console
2c. autocompletion + tab works nicely.

Notes:
-This behavior is similar on both laptops.
-Both laptops have no extra packages managed via pip install.
-The tests are done with "fresh" anaconda installation, without using KITE.

**My personal (intermediate) conclusion**
Downstream all the investigation, I still see some unexpected behavior of the autocompletion system which I have not noticed on any spyder/anaconda distribution before. It involved two laptops mounting Win10, and one of the two had never used python before. In both cases, the installation of anaconda was done "for all users".

I am now curious to know whether someone else is experiencing the same issue as me (perhaps in windows) :-)

If yes, the issue may be worth (sooner or later) some extra investigation by someone who is more experienced than me. What do you think? :-)



1. If I import a custom module

Update on the **original topic** (not the detour it took by uninstalling anaconda):

I installed the latest version of anaconda on another laptop Win10 (which had never seen python before), without Kite. I confirm/correct the same behavior of the original post:
When typing `import numpy`, and then `numpy.` the autocompletion list appears but after a very long time (6 seconds!). I don't exclude that also in my old laptop it behaved like that, but I never waited for such a long time B-). I confirm that the "details" on functions are missing in the editor (e.g. if you type `numpy.arange` and press ctrl+I, spyder does not find the documentation.

Conversely, if you run the line in the console, the tooltip with the documentation correctly appears (as I originally posted at the beginning of the post).

**Comment by dalthviz** [comment]
Thanks @capitanevs for the descriptions and testing! What do you guys think @ccordoba12 @andfoy ?

**Comment by ccordoba12** [comment]
- The delay to show completions for Numpy is known. We'll fix it next year when we move the Python language server to asyncio and support a new completion provider (Rope).
- For now, your best option is to use Kite to get faster completions.
- I'm getting the right object description for `np.abs`

    ![Selección_050](https://user-images.githubusercontent.com/365293/100941970-838b9a80-34c8-11eb-8861-47f6c20e6a49.png)

@capitanevs, could you try our new [Windows installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.0/Spyder_64bit_full.exe)? It was designed precisely to avoid this kind of problems (dependency issues and faulty installations).

**Comment by capitanevs** [comment]
Thank for you support and for the time you all took for answering.

I was not aware the issue was known and the superposition of many little different things made it difficult to give it the right name.

@ccordoba12 , thank you for the link, I will certainly use your Windows Installer and Kite. I was not aware of it, as I did everything from within Anaconda.

I will close the post. Wish you a nice day.

**Comment by ccordoba12** [comment]
Thanks @capitanevs! Please let us know if the installer fixes the issue with our completion machinery reporting the wrong object name for `np.abs`.
