### ISSUE TITLE
New way to update folding regions (PR #13783) freezes Spyder

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#14309]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

While using the editor, Spyder freeses for ~30s very often. I saw with the frame explorer that it was blocked in the new code intoduced by PR #13783. After reverting the merge, spyder works again.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @impact27 thanks for the feedback :+1: Not sure if @andfoy or @ccordoba12 are aware of the performance issue but pinging them here just in case

**Comment by ccordoba12** [comment]
Thanks @impact27 for reporting. How long is the file that shows the freezes?

**Comment by jnsebgosselin** [comment]
I'm experiencing the same thing too. It occurs on files that are not very long, like 500 lines maybe.

**Comment by ccordoba12** [comment]
@andfoy, could you reproduce this one?

**Comment by andfoy** [comment]
It seems that textdistance is causing delays here:

![imagen](https://user-images.githubusercontent.com/1878982/100280225-cf24ce00-2f35-11eb-96c5-66a8ba5f1009.png)

**Comment by andfoy** [comment]
It seems that the lag was due to the usage of Jaro-Wrinkler distance, after replacing it with a normalized Jaccard index, the performance did improve:

![spyder_prof](https://user-images.githubusercontent.com/1878982/100281576-29bf2980-2f38-11eb-8307-18f2016ddd26.png)

**Comment by andfoy** [comment]
@impact27 @jnsebgosselin could you please check if https://github.com/spyder-ide/spyder/pull/14315 improves the editor performance?

**Comment by jnsebgosselin** [comment]
Ok, I will test it while I work. I can report back tomorrow. Thanks for working on this.

**Comment by jnsebgosselin** [comment]
I confirm that PR#14315 fixes the editor performance for me.

**Comment by ccordoba12** [comment]
Great! Thanks @jnsebgosselin for the confirmation!
