### ISSUE TITLE
Unable to update to 4.2.0 via conda. Latest version 4.1.5 (anaconda.org)?

### ISSUE THREAD

**Issue by JanWaldhorn** [spyder-ide/spyder#14304]
## Problem Description

Until now I could update spyder every time with the command "conda install spyder=x.x.x". But currently I get the message that [4.1.5 seems to be the latest version](https://anaconda.org/anaconda/spyder) and therefore no 4.2.0 is available.

There is the latest version under[ conda-forge,](https://anaconda.org/conda-forge/spyder) but I suspect that version 4.2.0 should also be officially available.

I have done the usual troubleshooting  (`conda update anaconda` then `conda update spyder`), but since the anaconda repro 4.1.5 is mentioned as the current version, I do not suspect a local error.

### What steps reproduce the problem?

1. Under win 10, open an Anaconda prompt with admin rights.
2. `conda install spyder=4.2.0`

### What is the expected output? What do you see instead?

C:\WINDOWS\system32>conda install spyder=4.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=4.2.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

## Versions

* Spyder version: 4.1.5 None
* Python version: 3.7.9 64-bit
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)

# Spyder plugins:
spyder_notebook                :  0.3.1 (OK)

```

**Comment by luismiguells** [comment]
Same issue here.

**Comment by wenjingsu16** [comment]
Same issue. I am on macOS too.

**Comment by dalthviz** [comment]
Hi @JanWaldhorn and @luismiguells seems like version in 4.2.0 is still not available. From our side there is not much we can do about it, sorry :/ . Pinging @ccordoba12 just in case we can ask someone over the Anaconda side to check if there is something that prevents updating the package version available on the anaconda channel.

Also, for Spyder 4.2.0 we started building standalone application installer for Mac and Windows. You can check them in the [release page](https://github.com/spyder-ide/spyder/releases/tag/v4.2.0) or for more info about installation/run options you can check them in the [documentation page](https://docs.spyder-ide.org/current/installation.html)

**Comment by luismiguells** [comment]
@dalthviz thanks for the information 👍🏽. I tried running the standalone application on macOS 11.0.1 but it never opens, so I return to Anaconda. I don't know if I need to install something else or just the standalone application because if you don't have Anaconda you can't run the the `conda` commands as far as I know.

**Comment by ccordoba12** [comment]
@luismiguells, our installer will work with Big Sur in our next version (4.2.1), to be released in three week.s

**Comment by dcasasor-purdue** [comment]
After some days, I was able to install spyder 4.2.0 on windows by simply doing `conda install spyder=4.2.0`. However, for unix-based systems, this is not possible yet. I once tried `conda install -c conda-forge spyder=4.2.0` on Linux but it messed up with my dependencies and I had to install anaconda from scratch.

Is there a way make the new version available for Linux/Mac or should we wait for the 4.2.1 version?

**Comment by JanWaldhorn** [comment]
@dcasasor-purdue fascinating to hear. I just tried it again and it still does not work for me. Also the version on the Anaconda page has not changed (still 4.1.5). btw thanks for the explanation @dalthviz 

Maybe I try the stand a lone version, but at the moment 4.1.5. works just fine for me.

**Comment by dalthviz** [comment]
Hi @dcasasor-purdue if you want to have Spyder 4.2.0 I would suggest to create a new env and install from the conda-forge channel (to prevent messing up with your base env and default channel packages). Something like this should be create an env `spyder42` with Spyder 4.2.0: `conda create -n spyder42 spyder=4.2.0 -c conda-forge `

**Comment by rlloretb** [comment]
It still not working. Will it be solved?

**Comment by ccordoba12** [comment]
It doesn't depend on us but in the Anaconda team, sorry.

**Comment by Dan-Patterson** [comment]
This should be closed... it finally appears yesterday (2020-12-11).

**Comment by JanWaldhorn** [comment]
Yes indeed it works for me too. Thanks to all for the help.

**Comment by NaderNazemi** [comment]
still unable to upgrade.

**Comment by dalthviz** [comment]
Hi @NaderNazemi seems like the issue in your case is an inconsistency being generated do the packages you have in your env. That could be related with #14548 . As suggestion, if you want to check Spyder 4.2.x, is to create a new env and install there Spyder 4.2.0 (running something like this from the Anaconda Prompt should create the new env: `conda create -n spyder42 spyder=4.2.0`
