### ISSUE TITLE
Spyder crashing while idling in background. 

### ISSUE THREAD

**Issue by Llaves** [spyder-ide/spyder#14306]
## Problem Description
Spyder crashes while sitting idle in background
(idle in background means the Spyder window is open on the desktop, but not in active use. Occurs whether or not focus is on the window.)

### What steps reproduce the problem?

1. Launch spyder
2. wait a while (30-60 minutes or so)

No error dialog, nothing. Spyder just disappears.
The crash occurs consistently pretty much every time spyder is run and left idling

Launched from anaconda prompt with --debug-verbose --report-segfault
Here's the last lines up to the crash
```
2020-11-24 19:02:01,293 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2020-11-24 19:03:01,283 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2020-11-24 19:04:01,292 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2020-11-24 19:05:01,277 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2020-11-24 19:06:01,282 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:189)
2020-11-24 19:06:07,870 [ERROR] [asyncio] -> Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Anaconda3\lib\asyncio\selector_events.py", line 119, in _read_from_self
    data = self._ssock.recv(4096)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
```

### Runtime environment - 

```
Windows 10 Home, 64bit
Spyder 4.1.5
Python 3.7.7
PYQT_VERSION = 329986
PYQT_VERSION_STR = 5.9.2
QOpenGLVersionProfile = <class 'PyQt5.QtGui.QOpenGLVersionProfile'>
QOperatingSystemVersion = <class 'PyQt5.QtCore.QOperatingSystemVersion'>
QT_VERSION = 329990
QT_VERSION_STR = 5.9.6
QVersionNumber = <class 'PyQt5.QtCore.QVersionNumber'>
```
Spyder 4.1.5 installed yesteday over 4.1.4
PyQt updated to latest yesterday

**Comment by ccordoba12** [comment]
Hey @Llaves, thanks for reporting. It seems another program (probably your firewall or antivurs) is closing a connection Spyder needs in the background.

So please try to deactivate them and see if that's what's causing the crash.

**Comment by Llaves** [comment]
I run the native WIndows 10 Defender for virus and firewall. I turned both off completely (or as completely as I understand), then launched Spyder from the command prompt. It took several hours, but it eventually crashed:
```
2020-11-25 12:35:30,485 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2020-11-25 12:36:30,484 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
2020-11-25 12:37:30,486 [DEBUG] [spyder.plugins.editor.utils.autosave] -> Autosave triggered
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:368)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:189)
Assertion failed: Connection reset by peer [10054] (C:\ci\zeromq_1599741307349\work\src\signaler.cpp:189)
```

What can I look at next to help track this down?

**Comment by ccordoba12** [comment]
I have no idea, sorry. As I said, from your logs it seems another program is closing a connection opened by Spyder, which causes the crash.

**Comment by Llaves** [comment]
The fact that a closed network connection was the cause hinted that I should look at something in the networking stack. The prime suspect was Networx, a program for monitoring network traffic, since it inserts itself at the top of the stack. I shut down Networx and Spyder has been running for over 15 hours, far in excess of the time it took to crash in the past. Not only that, but it survived multiple sleep and hibernate transitions, which in the past also caused a crash with high regularity.

So dear reader, if you find yourself in a similar situation, check for any programs that attach to the network stack, like traffic monitors, firewalls, VPN, and the like.

**Comment by ccordoba12** [comment]
Glad you were able to figure this one out @Llaves!
