### ISSUE TITLE
Spyder crashes after conda update --all (on conda-forge)

### ISSUE THREAD

**Issue by egayer** [spyder-ide/spyder#14300]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After updating all dependencies in a particular environment with 

`conda update --all -c conda-forge`

Spyder starts and then crashes immediately after loading the different panels and after displaying a warning message impossible to read.

### What steps reproduce the problem?

1. launching spyder from terminal
2. 
3. 

### What is the expected output? What do you see instead?

- starting window as expected
- then spyder appears and crashes

### Paste Traceback/Error Below (if applicable)

```python-traceback

/anaconda/envs/condaforge/bin/pythonw: line 3:  1853 Segmentation fault: 11  /anaconda/envs/condaforge/python.app/Contents/MacOS/python "$@" 

```

## Versions

* Spyder version: 4.2.0            py36h79c6626_0    conda-forge
* Python version: Python 3.6.11
* Qt version: 5.6.2             h822fa55_1013    conda-forge
* PyQt version: 5.6.0           py36hc26a216_1008    conda-forge
* Operating System name/version: Mac OSX 10.13.6

### Dependencies

```

```

**Comment by ccordoba12** [comment]
Hey @egayer, thanks for reporting. Please run

    conda install -f -c conda-forge python.app

That could solve your problem.

**Comment by egayer** [comment]
Thank you @ccordoba12  for your quick answer.

Yes it solved the problem although it downgraded Spyder to 3.3.5.

Do you think it is a problem with the conda-forge version of the packages, I had Spyder 4 working fine prior to `conda update --all -c conda-forge`

I hope to be able to get to Spyder 4 in a near future.

**Comment by ccordoba12** [comment]
Did you run `conda update --all -c conda-forge` in a separate conda environment (with all packages installed from Anaconda) or in your base env?

**Comment by egayer** [comment]
Yes I did update all the packages within a separate conda env, running `conda update --all -c conda-forge` after activating this env (`source activate myenv`) and all packages in this env were installed from Anaconda (no mixing with pip) and from the conda-forge channel

**Comment by ccordoba12** [comment]
> Operating System name/version: Mac OSX 10.13.6

Ok, then it's possible that you need to update your Mac version.

Other than that, I'm out if ideas, sorry.

**Comment by egayer** [comment]
ok, thank you for your help.
