### ISSUE TITLE
Inconsistancies in math formula display (ipython console)

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#14349]
## Problem Description

Hi, 
Displaying math formula as png in the console provides 'random' output. Whereas the same works fine in a jupyter notebook.
I've already asked sympy (sympy/sympy#20491), but I guess it is a spyder issue as it works in a notebook?

### What steps reproduce the problem?

eg (in the spyder IPython console):

```
import sympy as sp
sp.var(x)
x*x
```
![image](https://user-images.githubusercontent.com/6706662/100760483-17d6fe00-33f2-11eb-945d-4075a990c7d1.png)

Ok fine, now:
![image](https://user-images.githubusercontent.com/6706662/100760644-4359e880-33f2-11eb-9c3f-a3dca401c3fb.png)

Switch to pretty print mode (no image)!

Another example (from IPython doc)
```
from IPython.display import Math
Math(r'F(k) = \int_{-\infty}^{\infty} f(x) e^{2\pi i k} dx')
Out[1]: 
<IPython.core.display.Math object>
```
While in a 'pure' notebook:
![image](https://user-images.githubusercontent.com/6706662/100759153-96cb3700-33f0-11eb-8121-c59cddbeb31b.png)

## Versions
Anaconda 3 (updated)
spyder 4.1.5

Hope this helps, thanks.

**Comment by steff456** [comment]
Hi @sylvain-bougnoux,

Are you expecting to see this output on the IPython Console or the Notebook plugin in Spyder?

**Comment by sylvain-bougnoux** [comment]
@steff456, Hi sorry for the confusion, I expect in the spyder IPython console.

In notebook (outside of spyder) it works. I am not sure what you mean by 'Notebook plugin in spyder'. I've not tested in direct qtconsole. In direct IPython console it does not make sense (no image output).

Thanks

**Comment by steff456** [comment]
Ok, for getting the expected result you need to:
1. Install Latex in your machine (Miktex in Windows, Texlive in macOS/Linux)
2. Create a new special console for Sympy in the hamburger menu of the IPython console, so `Consoles > New special console > New Sympy console`

If you don't want to use the Sympy console, then you need to read the following documentation to make it work, https://docs.sympy.org/latest/modules/interactive.html?highlight=init_printing#sympy.interactive.printing.init_printing 

Please let me know if it works for you

**Comment by sylvain-bougnoux** [comment]
Thanks for your help, actually I am aware of this answer, but I suspect it is more subtle. Currently I don't have Miktex.

For me, a notebook works so the latex system is already somewhere on my machine (maybe it uses mathjax, mathml or something?). So it could be a path issue?

My concern on spyder is: 
1. why a notebook using the same ipython (maybe not) work while spyder don't?
2. why some formulas like `sqrt(x)` turn to image (`x^2` in my former example) thus succeed using latex? While why some other turn to pretty mode (text mode)?

![image](https://user-images.githubusercontent.com/6706662/100850559-443b5a80-3484-11eb-84b8-5fd56d4dc352.png)

Without Latex, the special sympy console does not help. I had already tested "Options>Console options>Advanced>Use symbolic calculation. Which apparently does the same?

For me, it is like some mimetypes are not recognized/erroneous, or depending on the formula, different strategies are used for rendering, with one failing? Strange.

Thanks

**Comment by ccordoba12** [comment]
> why a notebook using the same ipython (maybe not) work while spyder don't?

Because the notebook uses web technologies and Spyder doesn't. Specifically, the notebook uses Mathjax to render Latex (even if the user doesn't have Latex installed), but that can't be used by Spyder.

> why some formulas like sqrt(x) turn to image (x^2 in my former example) thus succeed using latex? While why some other turn to pretty mode (text mode)?

Because Sympy uses some unicode symbols to better display those expressions. But (I think) it can't do that trick for all mathematical expressions.

> Without Latex, the special sympy console does not help

@steff456 clearly told you to first install Latex and then use that console. So I don't understand what else you were expecting here.

> I had already tested "Options>Console options>Advanced>Use symbolic calculation. Which apparently does the same?

Yes, it's the same.

**Comment by sylvain-bougnoux** [comment]
@ccordoba12 Hi carlos, thanks for the clarifications. Actually I could reproduce the issue in a `jupyter qtconsole`, so it is not spyder anymore :-) . 

I tried to avoid installing latex as I thought (now erroneously), that latex was there somewhere (because notebook succeed). Indeed as I want to distribute a tool needing this functionality, I would have like to avoid people installing latex. Now I understand that the notebook bypasses latex, and if we want 'complex' formula as images in spyder or in the qtconsole, we have to install latex. Thanks again and sorry for the confusion.

**Comment by ccordoba12** [comment]
No worries @sylvain-bougnoux.

I forgot to mention that next year we plan to add a new Viewer pane to visualize web content directly inside Spyder. Then we'll be able to display Sympy objects exactly as it's done in a Jupyter notebook.
