### ISSUE TITLE
Not working working directory (-w) of project (-p) from command line

### ISSUE THREAD

**Issue by rflamary** [spyder-ide/spyder#14348]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The command line options for working directory and project do not work on spyder 4.2.0 

### What steps reproduce the problem?

1. Execute $ spyder -w some/dir
2. Be sad because it opened directory from last selected project (pwd and graphical interface)

Or:

1. Execute $ spyder -p some/dir
2. Be sad because it opened directory from last selected project (pwd and graphical interface)

### What is the expected output? What do you see instead?

I would like those command line parameter to work because it can be very usefull when using from a command line and it avoids going through the folder selection.

note that is checked the code and the command line parameters are parsed correctly, it meas that somehow the workingdirectory/projects plugin are not doing their job or that some initialisation in the app failed (could not find it I don't know the code well).

## Versions

* Spyder version: 4.2.0 
* Python version: 3.6 and Python 3.8.5 64-bit
* Qt version: Qt 5.12.10  
* PyQt version: PyQt5 5.12.3 
* Operating System name/version: Ubuntu 18.04 and 20.04, Linux 5.4.0-56-generic

**Comment by rflamary** [comment]
This might be related to #5452 but it is happening on Ubuntu  to I thinks it is not just git bash.

**Comment by ccordoba12** [comment]
Hey @rflamary, thanks for reporting. You said

> Execute $ spyder -w some/dir
> Be sad because it opened directory from last selected project (pwd and graphical interface)

We haven't considered that possibility. We'll fix it in our next version.

> Execute $ spyder -p some/dir
> Be sad because it opened directory from last selected project (pwd and graphical interface)

We broke the `-p` option in 4.2.0, but it'll be fixed in our next version as well.

**Comment by rflamary** [comment]
This is awesome, thank you for your quick response, I will apply the PR locally for the time being.

Thank you for all your work.  I have been using happily spyder for a long time (even proposed a buggy implementation for debugger buttons on google code a long time ago) but this bug was a real pain.
