### ISSUE TITLE
Issue with NumPy

### ISSUE THREAD

**Issue by achoque21** [spyder-ide/spyder#14341]
### What steps will reproduce the problem?

import numpy as np
Traceback (most recent call last):

  File "<ipython-input-3-0aa0b027fcb6>", line 1, in <module>
    import numpy as np

  File "C:\Users\adcho\AppData\Local\Programs\Spyder\pkgs\numpy\__init__.py", line 305, in <module>
    _win_os_check()

  File "C:\Users\adcho\AppData\Local\Programs\Spyder\pkgs\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None

RuntimeError: The current Numpy installation ('C:\\Users\\adcho\\AppData\\Local\\Programs\\Spyder\\pkgs\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86

## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.9
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  50.3.2 (OK)
sphinx >=0.6.6                  :  3.3.0 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  None (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @achoque21, thanks for reporting. Unfortunately, this is a problem with Numpy, not with Spyder, so we can't provide you with much assistance.

I think the solution for now is to downgrade to Numpy 1.19.3. You can do that by running the following command:

    pip install  numpy==1.19.3
