### ISSUE TITLE
Spyder kernel dies while reading NetCDF file with netcdf4

### ISSUE THREAD

**Issue by alexrsanchez** [spyder-ide/spyder#14358]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm running Spyder 4.1.5. in Ubuntu 20.04 and I found out that kernel dies when I try to read a NetCDF file (2.6Gb size). This had never happened to me in other OS. Neither this occurs while doing other operations such us reading .csv and plotting large datasets.
I have tried everything: reset Spyder, unistalling and re-installing Anaconda, and followed every step of [this video](https://www.youtube.com/watch?v=Ul79ihg41Rs).

### What steps reproduce the problem?

1. I iniciate Spyder
2. It goes all right until it reaches the line where netcdf file is readed.
3. Kernel dies

### What is the expected output? What do you see instead?
I expect no errors, but this appears instead:
![imagen](https://user-images.githubusercontent.com/72650160/100938402-e8f58080-34f4-11eb-8d9b-dff1f698db30.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

Restarting kernel... 


 
[SpyderKernelApp] WARNING | No such comm: 6516af1e34ea11eb8e72d101fe563a39

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 1.9.0
* Operating System name/version: Ubuntu 20.04

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.27 (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.4 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @alexrsanchez, could you check if reading a smaller file also causes the message to appear? Could you provide us an example script to use to reproduce the error?

Any new info that helps reproduce the issue in our side is greatly appreciated :)

**Comment by alexrsanchez** [comment]
> Hi @alexrsanchez, could you check if reading a smaller file also causes the message to appear? Could you provide us an example script to use to reproduce the error?
> 
> Any new info that helps reproduce the issue in our side is greatly appreciated :)

Hi @dalthviz thank you for the answer. It seemss to work with smaller files (20 Mb aprox.) but it is awkward because I don't think 2Gb should be a problem to the memory, I have opened larger files in the past without any problem.
I attach an script snapshot as image. As you can see the memory usage is pretty small. The problem appears when reading the NetCDF file, I checked that none other line gives an error
![imagen](https://user-images.githubusercontent.com/72650160/100988513-1c192d80-3550-11eb-8beb-161f6256e829.png)

**Comment by ccordoba12** [comment]
Hey @alexrsanchez, does your code to load those files work in a Jupyter notebook?

**Comment by alexrsanchez** [comment]
No @ccordoba12, it also dies in Jupyter. I also tried with other similar NetCDF file quite smaller (388 Mb) and the kernel still dies both in Spyder and in Jupyter

**Comment by ccordoba12** [comment]
Ok, that means this is not a Spyder problem but an issue with NetCDF. So I don't know in what other way we could help you here (we're not experts in NetCDF, sorry).

**Comment by dalthviz** [comment]
@alexrsanchez is your NetCDf file using compound data structures in it? Seems like there is an issue regarding that in the `netcdf4-python` issue tracker (an issue about a memory leak of some sort?)

**Comment by dalthviz** [comment]
Closing due to lack of response
