### ISSUE TITLE
Horizontal scrollbar in console hiding the last line

### ISSUE THREAD

**Issue by lisatostrams** [spyder-ide/spyder#14354]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When the Spyder console has displayed output too wide to view, it adds a horizontal scroll bar to the bottom. This scrollbar hides the last command line of the console, and it seems I am unable to scroll down further. It's a very minor issue but it's annoying the hell out of me. 

I recorded my screen to show the issue: https://youtu.be/WYuA6Zssges

### What steps reproduce the problem?

1. Plot a large figure like `fig,ax=plt.subplots(figsize=(15,15))`
2. Try to type a new command
3. When you can't see the command you type, try to scroll down

### What is the expected output? What do you see instead?

Expected output: a full view of the console
Current output: a truncated view of the console

## Versions

* Spyder version: 4.0.1
* Python version: 3.7.6
* Qt version:  5.9.7
* PyQt version: 4.6.0
* IPython verion: 7.12.0
* Operating System name/version: macOS Catalina 10.15.7

**Comment by dalthviz** [comment]
Hi @lisatostrams could you try to update and check if the issue remains? Thanks! 

Pinging @steff456 @juanis2112 to check if they can reproduce this in the latest Spyder available

**Comment by lisatostrams** [comment]
Hi @dalthviz,

Updating spyder did in fact work, so sorry i thought i had the latest version! Thanks for the quick reply anyway :) 

Closing!

**Comment by dalthviz** [comment]
Awesome @lisatostrams ! Glad things are working better :)
