### ISSUE TITLE
spyder crashes upon launch

### ISSUE THREAD

**Issue by NelsonUpenn** [spyder-ide/spyder#14364]
I run macOS10.15.7 (19H15). I updated anaconda for macOS on 4 Dec 2020.
I got a problem described below. Next I deleted anaconda, downloaded, and reinstalled it, and said
$ conda update --all
Those steps did not cure the problem. 
## Problem Description
Summary: spyder won't launch from Terminal. Anaconda Launcher also offers to launch Spyder, but after a delay fails to do so with no visible error message.

### What steps reproduce the problem?
Even when I just say 
$ spyder --reset
(or try to launch spyder), I get the error below.

### What is the expected output? What do you see instead?
In Terminal, 
/Users/pcn/opt/anaconda3/bin/pythonw: line 3: /Users/pcn/opt/anaconda3/python.app/Contents/MacOS/python: No such file or directory

### First comments:
So I looked at the file anaconda3/bin/pythonw
which is just 3 lines:
--------
#!/bin/bash
export PYTHONEXECUTABLE=/Users/pcn/opt/anaconda3/bin/python
/Users/pcn/opt/anaconda3/python.app/Contents/MacOS/python "$@"
--------

Indeed, saying
$ ls anaconda3/python.app/Contents/
shows that there is no folder called MacOS/. In fact there is only one entry, a folder called lib/ which contains a folder called python3.8.

## Versions
 I run macOS10.15.7 (19H15). I updated anaconda for macOS on 4 Dec 2020.
I can't ask Spyder its version because it won't launch. It is the one supplied by anaconda on 4 Dec 2020.

Thanks Phil Nelson

**Comment by juanis2112** [comment]
Hi @NelsonUpenn thanks for reporting this.
Can you try opening your terminal and running 
```
conda install -f python.app
```

**Comment by NelsonUpenn** [comment]
Ms Gomez

Thank you for your immediate reply:

> On Dec 4, 2020, at 3:18 PM, Juanita Gomez <notifications@github.com> wrote:
> 
> 
> Hi @NelsonUpenn thanks for reporting this.
> Can you try opening your terminal and running
> 
> conda install -f python.app

** This was successful. I can now launch Spyder 4.1.5 (below).

Philip Nelson

* Spyder version: 4.1.5 None
* Python version: 3.8.5 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 19.6.0

**Comment by juanis2112** [comment]
You're welcome. I'm glad it worked!
