### ISSUE TITLE
spyder frequently  becomes unresponsive

### ISSUE THREAD

**Issue by fdarvas** [spyder-ide/spyder#14362]
### What steps will reproduce the problem?

Just clicking on the spyder window will gray it out - with a message in window title - Not responding - This occurs randomly.

This seems to happen mostly, when I am left clicking in any of the different panes and windows, e.g. such as the issue reporter.

After a few seconds, activity resumes. There are no error messages - the whole window just freezes for a few seconds.

I tried to shut down all panes, except for the help pane, but the problem persists.
 
 Spyder was installed recently -12/2/2020 - with a fresh anaconda install on a new windows 10 system.
 
 
* Spyder version: 4.1.5 None
* Python version: 3.8.5 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10
 

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by andfoy** [comment]
Hi @fdarvas, thanks for contacting us, it seems that you are using an old version of Spyder, could you please try to upgrade to version 4.2.0 via the new Windows installer and see if it works for you? The installer is available at https://github.com/spyder-ide/spyder/releases/download/v4.2.0/Spyder_64bit_full.exe

**Comment by fdarvas** [comment]
Hi,

The old version came with the conda installer and was strangely not
upgraded by the new installer. But conda uninstall spyder did the trick,
i.e. removing the 4.15 version - the other notable difference is that the
'old' spyder came with python 3.8, but the newer one now runs python 3.7.9?
The original issue seems to be gone, but now numpy is broken:

RuntimeError: The current Numpy installation
('C:\\Users\\felix\\AppData\\Local\\Programs\\Spyder\\pkgs\\numpy\\__init__.py')
fails to pass a sanity check due to a bug in the windows runtime. See this
issue for more information: https://tinyurl.com/y3dm3h86

which is actually worse than the previous bug...

best,
Felix

**Comment by ccordoba12** [comment]
> the other notable difference is that the
'old' spyder came with python 3.8, but the newer one now runs python 3.7.9?

That's right. Due to some technical limitations, the installer can't be created with Python 3.8

> The original issue seems to be gone

Great!

> but now numpy is broken

This is also known and it'll be fixed once we release new installers along with Spyder 4.2.1.

In the meantime, you can install Spyder 4.2.0 from conda-forge, by running the following commands:

    conda create -n conda-forge-env -c conda-forge python=3.8 spyder=4.2.0
    conda activate conda-forge-env
    spyder

**Comment by fdarvas** [comment]
Hi Carlos,

I did reinstall the new spyder (4.2.0) in the conda environment as
instructed and initially thought the problem was gone, but it still
persists.

Just randomly clicking in the UI or selecting a menu item will trigger the
whole spyder window to freeze up for several seconds - I had a suspicion it
had something to do with the autosave function (or the fact that I was
using files in a WSL 2 folder on windows was causing this (file access to
WSL files can be slow...), so I tested it with only opening files in native
windows folders and disabled autosave - but no luck in removing that random
freezing.

best,
Felix

**Comment by ccordoba12** [comment]
Ok, but do the problems show up with the Spyder version that comes with our own instaler?

**Comment by fdarvas** [comment]
Yes - same problems. Just randomly clicking in the UI or trying to enter
text in the ipython console will freeze it.

The most reliable reproduction I had so far was selecting the preferences
menu - this freezes it up for about 2 seconds (apparently not long enough
for windows to trigger the No-response message in the window) - other
random clicks or UI actions seem to freeze it longer.

best,
Felix

**Comment by ccordoba12** [comment]
I think there's another application installed in your computer that it's interfering with Spyder. Please try to search for `Qt*.dll` libraries and remove apps related to them.

**Comment by fdarvas** [comment]
I am finding Spyder, Anaconda and MicroSoft OneDrive are the
only applications that use Qt*.dlls.
Removing Anaconda would be pointless (no need for spyder the either) and
OneDrive is part of windows and presumably very common?
I did uninstall OneDrive - and still the same issue.
- Felix

**Comment by ccordoba12** [comment]
Then maybe is an issue with your firewall/antivirus blocking internal traffic in your computer. I'd turn them off and see what happens.

**Comment by fdarvas** [comment]
I turned the firewall/virusblocking off, still the same.
- Felix

**Comment by ccordoba12** [comment]
Sorry, I'm out of ideas.

**Comment by fdarvas** [comment]
Hi Carlos,

I think I found out what is was - I had files mounted on WSL2 Ubuntu 20.04
(on the same machine through a virtual network) open in Spyder - Since this
never caused any problems in PyCharm, I did not originally suspected this
to be a problem - especially since I turned off autosaving - so the file is
just sitting there in the editor, but it turns out that windows makes these
file accesses super slow - and Spyder, despite autosave turned off, does
seem to access the file on UI interactions (?), which caused the freeze.
After copying the file from the virtual machine over to a regular windows
file location, it seems to be working fine.

best,
Felix

**Comment by ccordoba12** [comment]
Great! I'm glad you were able to figure this one out.
