### ISSUE TITLE
Debug mode not working on win10 for any code

### ISSUE THREAD

**Issue by yellowpuppy** [spyder-ide/spyder#14380]
### Issue Report Checklist

* [Y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [Y] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [Y] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [Y] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
any code, such as
 `a = 1 # you can see the traceback follow, the spyder hanging at the first line of the code`
`b = 1`
`c = a + b`
All operations (such as step F10, continue to next breakpoint F12) not responding when spyder in debug mode. it seems like the IDE is hanging, all I can do is click the "Stop the current command" to exit the debug mode.

### What steps reproduce the problem?

1. debug any code and try to step inside

### What is the expected output? What do you see instead?

the spyder can stop at the pre-setted break points, and can step the code

### Paste Traceback/Error Below (if applicable)

```python-traceback

debugfile('E:/Public2/paper/universalLAIEstimation/test.py', wdir='E:/Public2/paper/universalLAIEstimation')
> e:\public2\paper\universallaiestimation\test.py(6)<module>()
      4 
      5 @author: WIN
----> 6 """
      7 
      8 a = 1


--KeyboardInterrupt--

KeyboardInterrupt: Interrupted by user

```

## Versions

* Spyder version: 4.1.2
* Python version: 3.7.7
* Qt version: 
* PyQt version: 
* Operating System name/version: win10 1909

### Dependencies

```
NO DEPENDENCIES
```

**Comment by yellowpuppy** [comment]
![debug2](https://user-images.githubusercontent.com/23078349/101341784-92a18c80-38bc-11eb-85db-d80916d23695.gif)

**Comment by ccordoba12** [comment]
@yellowpuppy, thanks for reporting.

@impact27, could you take a look at this one?

**Comment by impact27** [comment]
My guess is that your spyder-kernels version doesn't match your spyder version. Could you try updating the two of them?

I opened https://github.com/spyder-ide/spyder/pull/14382 that might mitigate this issue, which I assume is comms not being connected.

**Comment by yellowpuppy** [comment]
Thanks for your advise. I have updated the two of them by "conda update spyder ; conda update spyder-kernels", now the version of spyder is 4.1.2 and spyder-kernels is 1.9.4. However when I am in debug mode, the spyder throw a error like this.
```
debugfile('E:/Public2/paper/universalLAIEstimation/test.py', wdir='E:/Public2/paper/universalLAIEstimation')
This command failed to be executed because an error occurred while trying to get the file code from Spyder's editor. The error was:


An exception has occurred, use %tb to see the full traceback.

TypeError: handle_get_file_code() got an unexpected keyword argument 'save_all'
```

**Comment by ccordoba12** [comment]
@yellowpuppy, please run 

    conda update anaconda

then

    conda install spyder=4.1.5

That should fix your problem.

**Comment by yellowpuppy** [comment]
It works!, thank you all.

**Comment by ccordoba12** [comment]
Great! I'll reopen this issue because @impact27 has a fix for your problem that we plan to add in our next release.

**Comment by ccordoba12** [comment]
I mean, a fix that will allow you to use the debugger even if Spyder and spyder-kernels versiions don't match.

**Comment by impact27** [comment]
Maybe we should explicitely check the spyder-kernels version

**Comment by M-Nassir** [comment]
I have this same issue running on Mac OS Monterey with anaconda installation of Spyder 5.1.5. Debug mode just hangs and does nothing further. I cannot hit a breakpoint or step through.

**Comment by M-Nassir** [comment]
@Ningyezi My solution was to install spyder 5.2.2 from Conda source forge on to the base python conda environment. Then after you start spyder in the base environment you can change in the interpreter in spyder settings.

if I installed spyder onto another environment it just would close after starting.

**Comment by theshmo0** [comment]
Same problem as @M-Nassir after the last `conda update anaconda` on win10.
Package versions: spyder 5.1.5, spyder-kernels 2.1.3, python 3.8.10

**Comment by ccordoba12** [comment]
@theshmo0, as @M-Nassir said in the comment just above yours, the solution is to update to our 5.2.2 version.

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by andre5620** [comment]
I have used the win11, what's the prevision for the update ?

**Comment by davbish** [comment]
I am having the same issue with macOS Monterey using Spyder 4.1.5. Upgrading to Spyder 5.2 is not an option, as it is not compatible with my current environment.
