### ISSUE TITLE
Can't hotkey from IPython to Plots pane

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14383]
When focus (cursor) is in IPython console, hotkey to tab to Plots pane (which occupies same window) won't work - but vice versa (Plot -> IPython) works. Also tabbing between Editor and either of them always works. [demo.mp4](https://puu.sh/GVdbg/4762b6e146.mp4).

 - Editor: `Ctrl + Shift + E` -- IPython: `Ctrl + Shift + I` -- Plots: `Ctrl + Shift + P`

**Comment by dalthviz** [comment]
Tested with the current Spyder release (`5.1.5`) and is working with the default shortcuts (the shortcut for the Plots pane is `Ctrl + Shift + G`; the shortcut `Ctrl + Shift + P` is set for the Project Explorer). However, I was able to reproduce this by changing the shortcuts. My guess is that resusing the `Ctrl + Shift + P` can silently collide with the hardcoded shortcut for the `Print` action available in the Console instance context menu:

![print](https://user-images.githubusercontent.com/16781833/141491583-71328fe5-57b2-4cd8-8cd7-3d4dd276d6fa.png)

**Comment by OverLordGoldDragon** [comment]
Confirming, rebinding to `Ctrl + Shift + G` fixes this.
