### ISSUE TITLE
Tkinter failed to import

### ISSUE THREAD

**Issue by superuser789** [spyder-ide/spyder#14385]
I have installed Python 3.7.9 64bit in Windows 10 Pro and have installed the latest Spyder from setup installer for windows from [here](www.spyder-ide.org).  
When I import tkinter module, I get this error :
```
import tkinter as tk
Traceback (most recent call last):

  File "<ipython-input-2-e89bfb5dd03b>", line 1, in <module>
    import tkinter as tk

  File "C:\Program Files\Spyder\pkgs\tkinter\__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk

ImportError: DLL load failed: The specified module could not be found.
```
How can I resolve it ?

**Comment by ccordoba12** [comment]
Hey @superuser789, thanks for reporting. We'll take a look at that in our 4.2.2 version, to be released on February of next year (unfortunately 4.2.1 is almost ready to be released).

**Comment by dalthviz** [comment]
Note: Check https://github.com/takluyver/pynsist/issues/124

**Comment by Simon-Clifford** [comment]
I have this same issue too:
  File "C:\Program Files\Spyder\pkgs\tkinter\__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk

ImportError: DLL load failed: The specified module could not be found.

There doesn't seem to be any option to regress to an older version of Spyder that does work ? Do you have a release date for when 4.2.2 will be available ?

**Comment by dalthviz** [comment]
Hi @Simon-Clifford sadly all the versions of the Windows installer have this issue. If you want to overcome this you will need for now to install Spyder through `conda` for example. Regarding 4.2.2, is planned to be released at the end of February. If you want to check progress regarding this issue the PR that will be fixing this (which also builds previous of the installers) is #14727 :)
