### ISSUE TITLE
Show "Spyder" instead of "python" in macOS menubar

### ISSUE THREAD

**Issue by cbrnr** [spyder-ide/spyder#14405]
### Issue Report Checklist
* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The menubar on macOS shows "python" instead of "Spyder".

<img width="726" alt="Screen Shot 2020-12-11 at 10 26 21" src="https://user-images.githubusercontent.com/4377312/101886213-798a2b80-3b9b-11eb-827b-9c60671d3603.png">

### What steps reproduce the problem?
1. Start Spyder on macOS.
2. Observe the app name in the menubar.

### What is the expected output? What do you see instead?
The name should be "Spyder" and not "python".

### Proposed solution
The app name can be set with `pyobj-framework-cocoa`. Here's an example how I did it: https://github.com/cbrnr/mnelab/blob/master/mnelab/__main__.py#L16-L28

However, I'm not sure if Spyder already has other ways to set the name and if it's just broken on my machine. Let me know if you'd like me to submit a PR.

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.6
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: macOS Big Sur

### Dependencies

<details>
```
# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.2.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=4.7.7               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20201009 (OK)
sphinx >=0.6.6                  :  3.3.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.1 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```
</details>

**Comment by ccordoba12** [comment]
Thanks for the suggestion @cbrnr! We'll do it for our 4.2.2 version (to be released in two months).

**Comment by cbrnr** [comment]
Nice! Thanks @ccordoba12!

**Comment by mrclary** [comment]
@cbrnr I recommend using our macOS installer, which does not have this problem.
Also, if launching Spyder from commandline in a conda environment, I'm not sure that it is possible to change the menu bar name, since macOS sees the application as "Python". This was among the many motivations I had for developing the installer: it is then a bona-fide macOS application.

**Comment by cbrnr** [comment]
It is possible, see the link in my previous comment. But I agree that it's probably better to use the standalone app.

**Comment by mrclary** [comment]
> It is possible, see the link in my previous comment.

Well, I learn something new every day! Thanks @cbrnr.

**Comment by cbrnr** [comment]
I'm closing this because the recommended way to install Spyder is to use the standalone installers, where this works out of the box. My workaround is also just a hack.
