### ISSUE TITLE
Spyder on Macos Bigsur

### ISSUE THREAD

**Issue by Jameelgh** [spyder-ide/spyder#14401]
### What steps will reproduce the problem?

Hey! so i downloaded Anconda via your website then launched syder, I am trying to work on it but it's supper laggy on my 2019 macbook pro. 
I have a course next week and I have to have it up and working smoothly.  I would love an email on what should I do as I tried searching online for solutions but couldn't find any. 
email: jameel.2909@gmail.com

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.1.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Jameelgh, thanks for reporting. Please read our docs for the workaround you have to run for now:

http://docs.spyder-ide.org/current/faq.html#troubleshooting-macos-bigsur

**Comment by Jameelgh** [comment]
Hey! I ran the first code in terminal. Ahould I then Lanuch spyder via
anaconda?

**Comment by ccordoba12** [comment]
No, it won't take effect from Anaconda Navigator. You need to launch Spyder from the terminal too.

**Comment by Jameelgh** [comment]
how can i launch it from the terminal?
should I remove everything I have from Anaconda?

**Comment by ccordoba12** [comment]
> how can i launch it from the terminal?

You need to enter these commands (they are mentioned in the link I posted above, by the way):

    conda activate spyder-dev
    export QT_MAC_WANTS_LAYER=1
    spyder

> should I remove everything I have from Anaconda?

No, there's no need of that.

**Comment by Jameelgh** [comment]
it says "command not found" what should i do?
