### ISSUE TITLE
Feature request: Auto-set python interpreter when changing virtual (conda) environment

### ISSUE THREAD

**Issue by alessandrocornacchia** [spyder-ide/spyder#14409]
### Problem statement

As best practice, I usually create a new conda environment for each project I'm working on. In order not to duplicate the spyder installation, I usually follow the modular approach suggested in

[https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder](url) 

and install just type on each new environment

> conda install spyder-kernel

However, it is quite a daunting task to manually change Spyder Preferences > Python Interpreter, in order to set the correct one whenever I switch from one project to another. 

### Request

It would be very nice to get the job automatically done, such that when I change the working directory from the IDE, then the appropriate interpreter for any project is automatically set.
Something like the possibility to add a script/file in the directory of interest, that if present will trigger the change in the IDE..

![immagine](https://user-images.githubusercontent.com/62019963/101941849-dc55e400-3be8-11eb-9bbf-3e1422f01ac5.png)

**Comment by ccordoba12** [comment]
Hey @alessandrocornacchia, we were aware of this limitation and improved the situation in our 4.2.0. So now we detect your environments automatically and how them in `Use the following Python interpreter`.

Please update to that version by running

    conda update anaconda
    conda install=4.2.0

and then try that new feature to see if it's working as expected for you.

**Comment by sirhc78** [comment]
Hi,
Thank you for  all those updates!
Unfortunately, I've got the same problem when I switch from a project to another.

With 4.2.0, it seems worth.
Using " use the following Python Interpreter" and the combobox, I can now only choose between Spyder installation environment and previous project environment. So now I must write manually the correct env path instead of just selecting it.

I hope this help or may be I should use "default" settings ?

**Comment by alessandrocornacchia** [comment]
Hi, thank you for your answer. 
Let me better clarify my concern. I know I can manually tweek the python interpreter, under "use the following Python Interpreter". However, this has to be done again and again, every time I switch from one project to another (since I have a clean solution with one environment per project). 

Instead, is it possible to add a feature such that the Python Interpreter is automatically changed, as I move from one project directory to another (and so from one environment to another)? 

For instance, one option could be having to write a simple script file (according to whatever syntax) to insert in the root directory of any project. Then, I expect that upon changing directory, the IDE will search for that script and execute its directives, which essentially will trigger the setting of the Python Interpreter I want (the one associated to the project).

Thanks, regards

**Comment by ccordoba12** [comment]
@alessandrocornacchia, thanks for the clarification. This has been requested before and we'll try to implement it in a future version (I can't commit to a specific date because we haven't planned things in detail for next year, sorry).

**Comment by ryohei22** [comment]
Has this suggestion already been implemented? I think this is quite useful.

**Comment by ccordoba12** [comment]
@ryohei22, what do you mean exactly? Using a specific interpreter per project?

**Comment by ryohei22** [comment]
> @ryohei22, what do you mean exactly? Using a specific interpreter per project?

Yes, automatically switching the conda environment when switching one project to another.

**Comment by ccordoba12** [comment]
Ok, this is going to be implemented in Spyder 6 because we'll allow users to associate a project with a conda environment and it'll enabled when switching projects.

**Comment by ryohei22** [comment]
> Ok, this is going to be implemented in Spyder 6 because we'll allow users to associate a project with a conda environment and it'll enabled when switching projects.

I appreciate it and I look forward to it.
