### ISSUE TITLE
Spyder won't update to 4.2.0 due to Python < 3.8 requirement

### ISSUE THREAD

**Issue by Caseyb87** [spyder-ide/spyder#14416]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Trying to update Spyder to 4.2.0 (from 4.1.5) through Anaconda but update will not install due to Python < 3.8.0 requirement.

### What steps reproduce the problem?

1. conda update conda
2. conda update spyder

- will say "# All requested packages already installed."

3. conda install spyder=4.2.0

- gives the Python requirement <3.8.0 (as shown below)

### What is the expected output? What do you see instead?

Spyder should update and Python version 3.8.0 should not prevent the Spyder update. I haven't updated Python seperately, just using Anaconda, so seems like my Python version should be fine? 

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) C:\>conda install spyder=4.2.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spyder=4.2.0 -> python[version='>=3.7,<3.8.0a0']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.3 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.3 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)

```

**Comment by bogdandrpi** [comment]
Hello Caseyb87,
I had the same issue (I'm sure many others have also)
After trying to update using Anaconda Prompt I got the same errors as you described, but after restarting Anaconda Navigator, it signaled me that Spyder 4.1.5 has an updated version (a small blue arrow near the 4.1.5 version). I clicked on the Gear symmbol in the corner and choose Update application - That did NOT worked! but when I choose **Install specific version - 4.2.0** it failed with the message **spyder==4.2.0 cannot be installled on this enviroment Do you want to install the package in an existing enviroment or create a new enviroment?** Creating new enviroment did the trick for me.
HTH!

![spyder1](https://user-images.githubusercontent.com/48052425/102011822-7172ed00-3d4f-11eb-8632-28445968db00.png)
![spyder2](https://user-images.githubusercontent.com/48052425/102011824-75067400-3d4f-11eb-8d43-1d9f42d225fa.png)

**Comment by ccordoba12** [comment]
The Anaconda team hasn't released packages for Spyder 4.2 and Python 3.8 yet (only 3.7 at the moment). So please be patient, I'm sure they'll release Python 3.8 packages soon.

**Comment by Caseyb87** [comment]
Ah - OK, makes sense. 

Is there anyway for Spyder to be a bit smarter with its update prompt then? It's rather confusing for new users (or at least for me!) to be told there's an update avilable, follow all of the documentation/guidance, to then only find the update isn't actually yet available without fundamentally changing their current (and recommended) installation set-up.

In short: could Spyder be context aware and actually check if an update is available _for that user_, rather than just checking that there's been a new release?

**Comment by ccordoba12** [comment]
This is the first time in six years that Anaconda has released packages for one Python version instead of all of them at the same time (I didn't follow Anaconda previous to that). So it's highly unusual of them and our update prompt mechanism was not adapted to that.

**Comment by Dan-Patterson** [comment]
Fresh off the newswire
[https://anaconda.org/anaconda/spyder/files]
just appeared this evening

**Comment by ccordoba12** [comment]
Great! Thanks for the update @Dan-Patterson!
