### ISSUE TITLE
Anaconda error on start up

### ISSUE THREAD

**Issue by Achim210959** [spyder-ide/spyder#14425]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I had an HTTP error yesterday when trying to retrieve the URL to update Spyder. I have this proble often, what I do is to reinstall Anaconda completely after deinstalling the installed version.
After reinstallation Python started perfectly well, but today I'm having problems. I tried a variety of solutions indicated on
https://docs.anaconda.com/anaconda/navigator/troubleshooting/#:~:text=If%20you%20cannot%20launch%20the,problem%20with%20the%20licenses%20directory%2C%20.&text=Open%20a%20terminal%20or%20Anaconda,continuum%20directory., Finally Spyder opened, but I found the "Issue reported" pop-up window to which I'm now responding. I may try to reinstall Anaconda

**Comment by steff456** [comment]
Hi @Achim210959, please reinstall Anaconda and let me know if you could reproduce your error or if you fix it

**Comment by ccordoba12** [comment]
@Achim210959, you could also try the instructions we mention in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) about how to get Spyder back to life.

**Comment by Achim210959** [comment]
Thank youI've reinstalled Anaconda and the problem is fixed.A nice holiday season to you allAchimAchim AlbrechtEn France1 rue Harpon Résidence BaleineF 92290 Châtenay-MalabryTel.: 00 33 155520703Travail: 0146118456Portable : 00 33 (0)640359561En SuisseEmil Oprechtstr. 7CH 8050 ZürichTel fix.: 00 41 44 3821005 envoyé : 16 décembre 2020 à 17:19de : Stephannie Jimenez Gacha <notifications@github.com>à : spyder-ide/spyder <spyder@noreply.github.com>cc : Achim210959 <achim.albrecht@orange.fr>, Mention <mention@noreply.github.com>objet : Re: [spyder-ide/spyder] Anaconda error on start up (#14425) Hi @Achim210959, please reinstall Anaconda and let me know if you could reproduce your error or if you fix it—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jitseniesen** [comment]
The comment I deleted said "Thank youI've reinstalled Anaconda and the problem is fixed. A nice holiday season to you all"
