### ISSUE TITLE
Spyder has encountered a problem

### ISSUE THREAD

**Issue by Keven-Gao** [spyder-ide/spyder#14436]
can't open the spyder thought anaconda navigator, i have activate tensorflow and the ralated module of spyder in environment was finished. what's the problem.

**Comment by steff456** [comment]
Hi @Keven-Gao,

If you try to open spyder via the terminal, open a system terminal in your system and type `spyder` and please let me know if it works.

**Comment by Keven-Gao** [comment]
Hi Gacha,


Thank you for your help. I try to open the Spyder in cmd commend, but it has some errors as this screenshot.


Is there something wrong when I set the environment of tensorflow? It can open spyder throught cmd before I install tensorflow.


If you have some solutions, please let me know. Thank you!


Yours,









Kaifeng&nbsp;Gao
kaifeng.gao@foxmail.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spyder-ide/spyder"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月17日(星期四) 凌晨0:47
收件人:&nbsp;"spyder-ide/spyder"<spyder@noreply.github.com&gt;;
抄送:&nbsp;"高凯锋"<1476297415@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [spyder-ide/spyder] Spyder has encountered a problem (#14436)





 
Hi @Keven-Gao,
 
If you try to open spyder via the terminal, open a system terminal in your system and type spyder and please let me know if it works.

**Comment by ccordoba12** [comment]
This was probably caused by installing Tensorflow or other packages with pip. To fix, you need to remove and reinstall Anaconda, as described in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).
