### ISSUE TITLE
vcruntime140_1.dll

### ISSUE THREAD

**Issue by FrontheStevee** [spyder-ide/spyder#14433]
## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.9
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  50.3.2 (OK)
sphinx >=0.6.6                  :  3.3.0 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  None (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  1.1.4 (OK)
scipy >=0.17.0                  :  1.5.4 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by steff456** [comment]
Hi @FrontheStevee,

What error message are you encountering when you open up Spyder?

**Comment by FrontheStevee** [comment]
> Hi @FrontheStevee,
> 
> What error message are you encountering when you open up Spyder?


Good Day  the Error is "The code execution cannot proceed because VCRUNTIME140_1.dll was not found Reinstalling the program may fix this problem", its a QtWebEngineProcess.eve - System Error

![statupdate](https://user-images.githubusercontent.com/47195944/102407441-facd2e00-3fa0-11eb-8b95-3fc4b8f04eaf.JPG)

**Comment by ccordoba12** [comment]
@FrontheStevee, are you using our Windows installer?

**Comment by FrontheStevee** [comment]
> @FrontheStevee, are you using our Windows installer?

yes I am

**Comment by ccordoba12** [comment]
We thought this problem only happened on Windows 7. But perhaps this also happens in old builds of Windows 10.

Please try to follow these instructions to see if that fixes your problem:

https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954

**Comment by FrontheStevee** [comment]
> We thought this problem only happened on Windows 7. But perhaps this also happens in old builds of Windows 10.
> 
> Please try to follow these instructions to see if that fixes your problem:
> 
> https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954

Thank you! Let me see if i can get it to work

**Comment by FrontheStevee** [comment]
> We thought this problem only happened on Windows 7. But perhaps this also happens in old builds of Windows 10.
> 
> Please try to follow these instructions to see if that fixes your problem:
> 
> https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954

I have a Question after Downloading x86 and x64 Versions of Mircosoft Visual c++ 2015-2019 ....can i delete Microsoft Visual c++ 2012(x86),Microsoft Visual c++ 2013(x86),Microsoft Visual c++ 2013(x64) ???

**Comment by ccordoba12** [comment]
I'm not really sure. @dalthviz, what do you say?

**Comment by FrontheStevee** [comment]
> I'm not really sure. @dalthviz, what do you say?
 **I did what ** https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954 ****Shared and it worked ! **  but I noticed i have the same Microsoft Visual c++ from 2013 and 2012, But I just downloaded the same thing but in... i would assume newer versions which are   x86 and x64 versions of the Microsoft Visual C++ 2015 - 2019. can i delete the Micosoft Visual c++ from 2013 and 2012?
![issue](https://user-images.githubusercontent.com/47195944/102678581-4f69d800-415e-11eb-9f06-3afb499a72e9.JPG)

**Comment by ccordoba12** [comment]
If the error doesn't appear for yoy anymore, it's probably not wise to remove those other versions.

**Comment by Thunder380** [comment]
this has happened to me twice. I went to Control Panel and uninstall programs. found microsoft visualc++2015, right click and select Repair.

**Comment by DiploMaths** [comment]
Hello,

I just installed SPyder on W10, and the same issue occurs. Exactly the same pop up message.

I went to the C++ tutorial, and installed the files.

But I can't install X64 version cause I already have the 2017 one :

Microsoft Visual C++ 2015 (REdistribuable) x86
Microsoft Visual C++ 2017 (REdistribuable) x64

I updated the x86, but the problem is still here... can you help me please?
