### ISSUE TITLE
spyder wont launch under conda env and even cannot uninstall ...

### ISSUE THREAD

**Issue by GZ82** [spyder-ide/spyder#14445]
I created a conda env
then installed spyder using anaconda navigator
afterwards I find it cannot be launched, just stack there
then I search online followed an instruction: pip uninstall PyQt5
things getting worse, error pump up
then I tried: pip install PyQt5, 
spyder start in halfway, but jump away soon
so I planned to uninstall and reinstall using Anaconda navigator
it terminated in halfway also with following error reports .....

please suggest what I can do now

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package tornado conflicts for:
qtconsole -> ipykernel[version='>=4.1'] -> tornado[version='>=4.0|>=4.2|>=4.1']
graph-tool -> matplotlib-base -> tornado
rdkit -> matplotlib-base -> tornado
dask -> bokeh[version='>=1.0.0,!=2.0.0'] -> tornado[version='>=4.3|>=5|>=5.1|>=6.0.3|>=4.5.1']
jupyter -> ipykernel -> tornado[version='>=4,=4.0|>=4.2|>=5.0|>=5.0,=4.1,
Package six conflicts for:
ipython -> prompt-toolkit[version='!=3.0.0,!=3.0.1,=2.0.0'] -> six[version='>=1.9.0']
qtconsole -> traitlets -> six
dask -> bokeh[version='>=1.0.0,!=2.0.0'] -> six[version='>=1.5.2']

Package setuptools conflicts for:
ipython -> pygments -> setuptools
ipython -> setuptools[version='>=18.5']
python=3.8 -> pip -> setuptools
rdkit -> matplotlib-base -> setuptools
dask -> distributed[version='>=2020.12.0'] -> setuptools
graph-tool -> matplotlib-base -> setuptools
qtconsole -> pygments -> setuptools

Package pytz conflicts for:
dask -> pandas[version='>=0.25.0'] -> pytz[version='>=2017.2']
rdkit -> pandas -> pytz[version='>=2017.2']

Package decorator conflicts for:
ipython -> decorator
qtconsole -> traitlets -> decorator

Package qt conflicts for:
qtconsole -> pyqt -> qt[version='5.6.*|5.9.*|>=5.9.7,=5.9.6,pyqtwebengine -> qt[version='>=5.12.9,pyqt -> pyqtchart==5.12=py38h721a93c_6 -> qt[version='>=5.12.9,pyqtchart -> qt[version='>=5.12.9,pyqt -> qt[version='5.6.*|5.9.*|>=5.9.7,=5.9.6,
Package pyqtwebengine conflicts for:
pyqt -> pyqtwebengine==5.12.1=py38h721a93c_6
pyqtwebengine
qtconsole -> pyqt -> pyqtwebengine==5.12.1=py38h721a93c_6

Package ca-certificates conflicts for:
jupyter -> python[version='>=2.7, ca-certificates
ipython -> python[version='>=2.7, ca-certificates
python.app -> python[version='>=2.7, ca-certificates
certifi -> python -> ca-certificates
python=3.8 -> openssl[version='>=1.1.1g, ca-certificates
dask -> openssl!=1.1.1e -> ca-certificates
openssl -> ca-certificates
pyqt -> python[version='>=2.7, ca-certificates
qtconsole -> python -> ca-certificates
ca-certificates

Package python_abi conflicts for:
pyqt -> python_abi=3.8[build=*_cp38]
graph-tool -> python_abi=3.8[build=*_cp38]
pyqtwebengine -> python_abi=3.8[build=*_cp38]
pyqtchart -> python_abi=3.8[build=*_cp38]
qtconsole -> ipykernel[version='>=4.1'] -> python_abi=3.8[build=*_cp38]
dask -> numpy[version='>=1.15.1'] -> python_abi=3.8[build=*_cp38]
ipython -> python_abi=3.8[build=*_cp38]
ipython -> setuptools[version='>=18.5'] -> python_abi[version='3.6.*|3.7.*',build='*_cp36m|*_cp37m']
rdkit -> python_abi=3.8[build=*_cp38]
jupyter -> ipykernel -> python_abi=3.8[build=*_cp38]

Package qtconsole conflicts for:
qtconsole
jupyter -> qtconsole

Package libglib conflicts for:
rdkit -> cairo[version='>=1.16.0, libglib[version='>=2.64.6,pyqt -> dbus[version='>=1.13.2, libglib[version='>=2.64.6,graph-tool -> gdk-pixbuf -> libglib[version='>=2.64.6,pyqtchart -> dbus[version='>=1.13.6, libglib[version='>=2.64.6,pyqtwebengine -> dbus[version='>=1.13.6, libglib[version='>=2.64.6,
Package glib conflicts for:
pyqt -> dbus[version='>=1.13.12, glib[version='>=2.53.6,=2.56.1,=2.56.2,=2.63.1,graph-tool -> gtk3 -> glib
pyqtwebengine -> dbus[version='>=1.13.6, glib[version='>=2.56.2,=2.63.1,pyqtchart -> dbus[version='>=1.13.6, glib[version='>=2.56.2,=2.63.1,
Package pyqt conflicts for:
qtconsole -> pyqt[version='>=5.9.2,pyqt
jupyter -> qtconsole -> pyqt[version='>=5.9.2,
Package python-dateutil conflicts for:
rdkit -> matplotlib-base -> python-dateutil[version='>=2.1|>=2.7.3|>=2.6.1|>=2.5.*']
dask -> bokeh[version='>=1.0.0,!=2.0.0'] -> python-dateutil[version='>=2.1|>=2.7.3|>=2.6.1|>=2.5.*']
qtconsole -> jupyter_client[version='>=4.1'] -> python-dateutil[version='>=2.1']
graph-tool -> matplotlib-base -> python-dateutil[version='>=2.1']

Package boost-cpp conflicts for:
graph-tool -> boost-cpp[version='>=1.72.0,graph-tool -> boost[version='>=1.72.0, boost-cpp=1.72.0

Package prompt_toolkit conflicts for:
jupyter -> jupyter_console -> prompt_toolkit[version='>=1.0.0,=2.0.0,=2.0.0,ipython -> prompt_toolkit[version='>=1.0.4,=2.0.0,=2.0.0,
Package cairo conflicts for:
graph-tool -> cairomm-1.0[version='>=1.12.2'] -> cairo[version='1.14.*|>=1.14.10,=1.14.12,=1.16.0,=1.16.0,rdkit -> cairo[version='>=1.16.0,rdkit -> pycairo -> cairo[version='1.14.*|>=1.14.10,=1.14.12,
Package certifi conflicts for:
ipython -> setuptools[version='>=18.5'] -> certifi[version='>=2016.09|>=2016.9.26']
certifi
graph-tool -> matplotlib-base -> certifi[version='>=2020.06.20']
rdkit -> matplotlib-base -> certifi[version='>=2020.06.20']

Package openssl conflicts for:
graph-tool -> python[version='>=3.8, openssl[version='>=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,dask -> python[version='>=3.6'] -> openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1b,=1.1.1c,=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,=1.1.1i,=1.0.2l,=1.0.2p,qtconsole -> python -> openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1b,=1.1.1c,=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,=1.1.1i,=1.0.2l,=1.0.2p,openssl
python=3.8 -> openssl[version='>=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,certifi -> python[version='>=3.7, openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1b,=1.1.1c,=1.1.1d,=1.1.1e,=1.1.1g,=1.0.2l,=1.1.1h,=1.1.1i,=1.0.2p,pyqt -> python[version='>=3.9, openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,=1.1.1i,=1.1.1c,=1.0.2l,=1.0.2p,=1.1.1b,ipython -> python[version='>=3.9, openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1b,=1.1.1c,=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,=1.1.1i,=1.0.2l,=1.0.2p,python.app -> python[version='>=3.7, openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1b,=1.1.1c,=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,=1.0.2l,=1.1.1i,=1.0.2p,dask -> openssl!=1.1.1e
pyqtwebengine -> python[version='>=3.8, openssl[version='>=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,jupyter -> python[version='>=3.9, openssl[version='1.0.*|>=1.0.2m,=1.0.2n,=1.0.2o,=1.1.1a,=1.1.1b,=1.1.1c,=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,=1.1.1i,=1.0.2l,=1.0.2p,rdkit -> python[version='>=3.8, openssl[version='>=1.1.1d,=1.1.1e,=1.1.1g,=1.1.1h,
Package pyqtchart conflicts for:
pyqtchart
pyqt -> pyqtchart==5.12=py38h721a93c_6
qtconsole -> pyqt -> pyqtchart==5.12=py38h721a93c_6

Package jinja2 conflicts for:
dask -> bokeh[version='>=1.0.0,!=2.0.0'] -> jinja2[version='>=2.7']
jupyter -> nbconvert -> jinja2[version='>=2.4']

Package libcxxabi conflicts for:
python=3.8 -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hcfea43d_1|hebd6815_0']
pyqt -> libcxx[version='>=4.0.1'] -> libcxxabi==4.0.1[build='hcfea43d_1|hebd6815_0']

Package tzdata conflicts for:
dask -> python[version='>=3.6'] -> tzdata
pyqt -> python[version='>=3.9, tzdata
qtconsole -> python -> tzdata
python.app -> python[version='>=3.9, tzdata
jupyter -> python[version='>=3.9, tzdata
certifi -> python[version='>=3.9, tzdata
ipython -> python[version='>=3.9, tzdata

Package ipython conflicts for:
jupyter -> ipykernel -> ipython[version='>=4.0.0|>=4.0|>=5.0']
ipython
qtconsole -> ipykernel[version='>=4.1'] -> ipython[version='>=4.0.0|>=4.0|>=5.0']

Package libclang conflicts for:
pyqtwebengine -> qt[version='>=5.12.9, libclang[version='>=10.0.1,pyqtchart -> qt[version='>=5.12.9, libclang[version='>=10.0.1,
Package numpy conflicts for:
graph-tool -> matplotlib-base -> numpy[version='>=1.11.3,=1.14.6,=1.15.4,=1.16.6,=1.15.1,=1.9.3,graph-tool -> numpy[version='>=1.16.5,
Package numpy-base conflicts for:
graph-tool -> numpy[version='>=1.16.5, numpy-base[version='1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.17.0|1.17.0',build='py36ha711998_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py37ha711998_0|py27ha711998_0|py27h6575580_0|py39hd037223_1|py39h7ca7dfd_1|py36h68fea81_0|py37hcfb5961_0|py37h68fea81_0|py36hcfb5961_0|py38h68fea81_0|py36h68fea81_0|py39hde55871_0|py39h3a452eb_0|py37h68fea81_0|py38hcfb5961_0|py37hcfb5961_0|py38hcfb5961_0|py36hcfb5961_0|py38h68fea81_0|py38ha711998_0|py38h6575580_0|py37h6575580_0|py36h6575580_0|py36ha711998_0|py37h6575580_0|py27h6575580_0|py36ha711998_0|py36h6575580_0']
dask -> numpy[version='>=1.15.1'] -> numpy-base[version='1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.11.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.3|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.4|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.5|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.14.6|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.0|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.1|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.2|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.3|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.15.4|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.0|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.1|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.2|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.3|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.4|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.17.0|1.17.0',build='py27h9797aa9_7|py27ha9ae307_7|py27h9797aa9_8|py36ha9ae307_8|py36h9797aa9_8|py37ha9ae307_8|py37he97cb71_9|py27h8a80b8c_9|py27he97cb71_9|py36he97cb71_9|py27h42e5f7b_10|py36h8a80b8c_10|py27h8a80b8c_10|py37h8a80b8c_10|py35ha711998_10|py27ha711998_11|py36ha711998_11|py27h6575580_11|py36h6575580_11|py36h6575580_12|py37ha711998_12|py27ha711998_12|py38ha711998_12|py38h6575580_12|py38h6575580_13|py38ha711998_14|py38ha711998_15|py36h7ef55bc_1|py35h479e554_1|py27h479e554_1|py27h7ef55bc_1|py35h7ef55bc_1|py27ha9ae307_0|py36ha9ae307_0|py36h9797aa9_0|py36ha9ae307_0|py36h9797aa9_0|py27ha9ae307_0|py27h9797aa9_1|py36h9797aa9_1|py37ha9ae307_1|py36ha9ae307_2|py36h9797aa9_3|py37h9797aa9_3|py37ha9ae307_3|py36ha9ae307_4|py36h9797aa9_4|py37ha9ae307_4|py35h9797aa9_4|py35ha711998_4|py35h8a80b8c_4|py37ha711998_4|py37h8a80b8c_4|py36h6575580_5|py37h6575580_5|py27he97cb71_0|py37he97cb71_0|py36he97cb71_0|py35h8a80b8c_0|py35he97cb71_0|py36h6575580_0|py36h42e5f7b_0|py27h42e5f7b_0|py37h8a80b8c_0|py27ha711998_0|py35ha711998_0|py37ha711998_0|py27ha711998_0|py35h8a80b8c_0|py37ha711998_0|py35ha711998_0|py27ha711998_1|py36ha711998_1|py36h8a80b8c_1|py37ha711998_0|py27ha711998_0|py27ha711998_0|py37ha711998_0|py27ha711998_0|py37ha711998_0|py27h6575580_0|py27ha711998_1|py36ha711998_1|py27ha711998_0|py37ha711998_0|py27h6575580_0|py37h6575580_0|py36ha711998_1|py27ha711998_0|py37ha711998_0|py27h6575580_0|py37h6575580_0|py27ha711998_0|py37ha711998_0|py27h6575580_0|py37ha711998_0|py27ha711998_0|py37h6575580_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py37ha711998_0|py27ha711998_0|py27h6575580_0|py39hd037223_1|py39h7ca7dfd_1|py36h68fea81_0|py37hcfb5961_0|py37h68fea81_0|py36hcfb5961_0|py38h68fea81_0|py36h68fea81_0|py39hde55871_0|py39h3a452eb_0|py37h68fea81_0|py38hcfb5961_0|py37hcfb5961_0|py38hcfb5961_0|py36hcfb5961_0|py38h68fea81_0|py38ha711998_0|py38h6575580_0|py37h6575580_0|py36h6575580_0|py36ha711998_0|py37h6575580_0|py27h6575580_0|py36ha711998_0|py36h6575580_0|py27h6575580_0|py36ha711998_0|py36h6575580_0|py37h6575580_0|py36ha711998_0|py36h6575580_0|py36ha711998_0|py36h6575580_1|py37ha711998_1|py27ha711998_1|py37h6575580_1|py27h6575580_1|py36h6575580_0|py36ha711998_0|py36h6575580_1|py27h6575580_1|py37ha711998_1|py37h6575580_1|py36h6575580_0|py36ha711998_0|py37h6575580_0|py36h6575580_0|py27h6575580_0|py37h6575580_0|py36ha711998_0|py36h8a80b8c_0|py37h8a80b8c_0|py27h8a80b8c_0|py36h8a80b8c_0|py27h8a80b8c_0|py36ha711998_0|py37h8a80b8c_0|py37h8a80b8c_1|py27h8a80b8c_1|py37ha711998_1|py36ha711998_0|py27h8a80b8c_0|py36h8a80b8c_0|py37h8a80b8c_0|py36ha711998_0|py35h8a80b8c_0|py27h8a80b8c_0|py35h42e5f7b_0|py36h8a80b8c_0|py37h42e5f7b_0|py36ha711998_0|py36h8a80b8c_0|py27h8a80b8c_0|py37h8a80b8c_0|py37ha711998_5|py27h6575580_5|py27ha711998_5|py36ha711998_5|py38h6575580_4|py38ha711998_4|py27h8a80b8c_4|py36h8a80b8c_4|py27ha711998_4|py36ha711998_4|py35ha9ae307_4|py37h9797aa9_4|py27h9797aa9_4|py27ha9ae307_4|py27ha9ae307_3|py27h9797aa9_3|py36ha9ae307_3|py27ha9ae307_2|py37ha9ae307_2|py27h9797aa9_2|py36h9797aa9_2|py37h9797aa9_2|py36ha9ae307_1|py27ha9ae307_1|py37h9797aa9_1|py35h9797aa9_0|py35ha9ae307_0|py27h9797aa9_0|py35ha9ae307_0|py35h9797aa9_0|py27h9797aa9_0|py36h479e554_1|py38h6575580_15|py38h6575580_14|py38ha711998_13|py37h6575580_12|py36ha711998_12|py27h6575580_12|py37h6575580_11|py37ha711998_11|py36ha711998_10|py37ha711998_10|py27ha711998_10|py36h42e5f7b_10|py35h8a80b8c_10|py35h42e5f7b_10|py37h42e5f7b_10|py35he97cb71_9|py35h8a80b8c_9|py36h8a80b8c_9|py37h8a80b8c_9|py35ha9ae307_8|py35h9797aa9_8|py37h9797aa9_8|py27ha9ae307_8|py37ha9ae307_7|py36ha9ae307_7|py36h9797aa9_7|py37h9797aa9_7']
rdkit -> numpy[version='>=1.16.5, numpy-base[version='1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.5|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.16.6|1.17.2.*|1.17.3.*|1.17.4.*|1.18.1.*|1.18.5.*|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.1|1.19.2|1.17.0|1.17.0',build='py36ha711998_0|py37ha711998_0|py27ha711998_0|py36h6575580_0|py37ha711998_0|py27ha711998_0|py27h6575580_0|py39hd037223_1|py39h7ca7dfd_1|py36h68fea81_0|py37hcfb5961_0|py37h68fea81_0|py36hcfb5961_0|py38h68fea81_0|py36h68fea81_0|py39hde55871_0|py39h3a452eb_0|py37h68fea81_0|py38hcfb5961_0|py37hcfb5961_0|py38hcfb5961_0|py36hcfb5961_0|py38h68fea81_0|py38ha711998_0|py38h6575580_0|py37h6575580_0|py36h6575580_0|py36ha711998_0|py37h6575580_0|py27h6575580_0|py36ha711998_0|py36h6575580_0']

Package sip conflicts for:
qtconsole -> pyqt -> sip[version='4.18.*|4.19.13.*|>=4.19.4,pyqt -> sip[version='4.18.*|4.19.13.*|>=4.19.4,

**Comment by dalthviz** [comment]
Hi @GZ82 sorry to hear that, could you try to delete the `conda env` that you created and create a new one? Also, some resources that could be useful for you:

* First Aid guide: https://docs.spyder-ide.org/current/basic-first-aid.html
* Available standalone installers: https://www.spyder-ide.org/#section-download

 Let us know if that helps :)

**Comment by GZ82** [comment]
Hi Daniel,
Thanks so much for your suggestions!
I tried the first aid but none is useful
A lot conflictions found during: conda update spyder
I have been installed rdkit and graph-tool under this virtual env
graph-tool always leads to many problems
I will install spyder in a different env

Thanks again and Wish you Merry Christmas!

best regards
Zhen
________________________________
