### ISSUE TITLE
ImportError: cannot import name 'ft2font' from partially initialized module 'matplotlib' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by Buddhakarmakar** [spyder-ide/spyder#14442]
![issue](https://user-images.githubusercontent.com/42817842/102397660-2df4d900-4004-11eb-8056-789a0a1ee3d5.png)
![issue](https://user-images.githubusercontent.com/42817842/102397692-3d742200-4004-11eb-80c2-30db00b76df8.png)

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @Buddhakarmakar by the traceback seems like an issue with your matplotlib installation rather than with Spyder. A solution for a similar traceback is proposed here: https://stackoverflow.com/a/63187840

Let us know if that helps :)

**Comment by Buddhakarmakar** [comment]
Thank U very much @dalthviz
