### ISSUE TITLE
Can't install spyder 4.2.1 using the conda install spyder=4.2.1 command in mac terminal

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#14459]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Can't install spyder 4.2.1 using the conda install spyder=4.2.1 command. I get the following error:

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=4.2.1

### What steps reproduce the problem?

1. conda install spyder=4.2.1
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=4.2.1
 
```

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.5
* Qt version: 
* PyQt version: 
* Operating System name/version: macos 11.1

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by Dan-Patterson** [comment]
If it isn't on this list, then it isn't available yet
[https://anaconda.org/anaconda/repo](url)

**Comment by mhdmyz** [comment]
> If it isn't on this list, then it isn't available yet
> [https://anaconda.org/anaconda/repo](url)
In the link you provided 4.2.0 is available. But Spyder released this version (4.2.1) about 7 hours ago! How long should it take to become available on anaconda as well? 4.2.0 doesn't work on mac os Big Sur and it's very annoying!

**Comment by ccordoba12** [comment]
@mhdmyz, you can use our Mac installer in the meantime:

https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg

If that fails to start, please try this one:

https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder-Lite.dmg

**Comment by mhdmyz** [comment]
> @mhdmyz, you can use our Mac installer in the meantime:
> 
> https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg
> 
> If that fails to start, please try this one:
> 
> https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder-Lite.dmg

Thanks Carlos! But I need to use it on anaconda! Do you know when it gets available on conda?

**Comment by ccordoba12** [comment]
No idea, sorry.

**Comment by marekkolman** [comment]
@mhdmyz I'm also very impatient as this version fixes bugs that were critical for me.
From my experience, it will be earlier on conda-forge channel (although I don't see there v4.2.1 yet). So you might consider using that channel when using conda for updates: https://anaconda.org/conda-forge/spyder

**Comment by ma-sadeghi** [comment]
@ccordoba12 It seems that you haven't merged the PR for 4.2.1 on conda feedstock: https://github.com/conda-forge/spyder-feedstock/pull/89

**Comment by mhdmyz** [comment]
> @mhdmyz I'm also very impatient as this version fixes bugs that were critical for me.
> From my experience, it will be earlier on conda-forge channel (although I don't see there v4.2.1 yet). So you might consider using that channel when using conda for updates: https://anaconda.org/conda-forge/spyder

Thanks man! I have this channel in my anaconda channels as well. Good point!

**Comment by ma-sadeghi** [comment]
@ccordoba12 One more thing, you probably already know about this, but you can add automerge bot in the conda feedstock so that whenever you push a new version to pip, conda will automatically merge the PR (if all tests pass)

**Comment by marekkolman** [comment]
@mhdmyz I now see 4.2.1 is on conda-forge

**Comment by mhdmyz** [comment]
> @mhdmyz I now see 4.2.1 is on conda-forge

Yeah finally! I hope we won't go through this in the next updates!

**Comment by mhdmyz** [comment]
@ccordoba12 Are you sure the issue with Big Sur got resolved in 4.2.1?!
I installed 4.2.1 by running `conda install spyder=4.2.1`, update was successful but spyder didn't launch!
Then I uninstalled Anaconda from my system completely and installed it again fresh, then `conda update anaconda` and `conda install spyder=4.2.1`, again same problem!

**Comment by ccordoba12** [comment]
Yes, it is. Please see our FAQ about that:

https://docs.spyder-ide.org/current/faq.html#troubleshooting-macos-bigsur

**Comment by mrclary** [comment]
I recommend using the macOS installer, as @ccordoba12 [mentioned](https://github.com/spyder-ide/spyder/issues/14459#issuecomment-748387341). You can still use your existing conda environments by selecting them in the Python Interpreter tab of Spyder Preferences.

<img width="1054" alt="Screen Shot 2021-01-20 at 12 40 40 PM" src="https://user-images.githubusercontent.com/9618975/105232177-dc68ce00-5b1c-11eb-87e1-9e85fd210f88.png">

**Comment by mhdmyz** [comment]
> I recommend using the macOS installer, as @ccordoba12 [mentioned](https://github.com/spyder-ide/spyder/issues/14459#issuecomment-748387341). You can still use your existing conda environments by selecting them in the Python Interpreter tab of Spyder Preferences.
> 
> <img alt="Screen Shot 2021-01-20 at 12 40 40 PM" width="1054" src="https://user-images.githubusercontent.com/9618975/105232177-dc68ce00-5b1c-11eb-87e1-9e85fd210f88.png">

Thank you @mrclary! yeah I was suggested the same solution 11 days go in #14561.

**Comment by jaafargaber** [comment]
just launch  "anaconda Prompt" terminal and enter the following commands : 
conda config --add channels conda-forge
conda config --set channel_priority strict
conda install  spyder=4.2.1

**Comment by ccordoba12** [comment]
@jaafargaber, that would lead to mixing conda and conda-forge packages, which is a really bad suggestion. Therefore, I'm going to hide your comment and this one.

By the way, you can find the right solution a couple of comments above (it's one with a link to our FAQ).

**Comment by ccordoba12** [comment]
Closing because this was solved.
