### ISSUE TITLE
MacOS Download link is broken

### ISSUE THREAD

**Issue by pixeluk42** [spyder-ide/spyder#14457]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The new 4.2.1 download doesn't work. 404 not found.

### What steps reproduce the problem?

1. Click download link on GitHub or the official website.
2. 404 not found.
3. Be sad.

### What is the expected output? What do you see instead?

A download of a dmg file.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by pixeluk42** [comment]
Solved now.

**Comment by dalthviz** [comment]
Thanks for the feedback @pixeluk42 just in case, as an explanation, this happens since the workflow that builds the installers (which usually takes 20-30 mins for Mac) runs  *after* the Github Release is created so a little wait is needed before being available to actually download the installer :)
