### ISSUE TITLE
macOS Big Sur error message after following the Spyder page recommendation

### ISSUE THREAD

**Issue by Jacques2101** [spyder-ide/spyder#14460]
Hi, 
I saw that there is problem with Spyder with macOS big sur and I have the same I suppose but with a different output : 
I follow the [https://docs.spyder-ide.org/current/faq.html#troubleshooting-macos-bigsur](Spyder reported bug on macOS Big Sur) internet's page but after that I get an error message : 
`/Users/jacques/opt/anaconda3/bin/pythonw: line 3: /Users/jacques/opt/anaconda3/python.app/Contents/MacOS/python: No such file or directory`

## Versions
* Spyder version: 4.2
* Python version: 3.8.5
* Qt version: 5.9.7 
* PyQt version: 5.9.2
* Operating System name/version: macOS Big Sur

**Comment by ccordoba12** [comment]
Hey @Jacques2101, thanks for reporting. Please run the following commands to fix your problem:

    conda activate spyder-dev
    conda install -f python.app

That should be enough.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by pierre-ludmann-depinfonancy** [comment]
Ended up here for I had the same error. The line `conda install -f python.app` sufficed to fix the issue. Thanks.
