### ISSUE TITLE
Hitting debug twice makes it unable to continue

### ISSUE THREAD

**Issue by nassimbnm** [spyder-ide/spyder#14472]
When hitting debug one more time during a debugging session the prompt changes from IPdb [2] to ipdb>
Then I'm unable to continue debugging and have to enter any pdb command to exit.

Can reproduce every time.
Just add a break point and hit debug twice.

Issue since 4.2.0 and 4.2.1
Works ok in 4.1.5

**Comment by steff456** [comment]
Hi @nassimbnm,

I'm able to reproduce this error, my question is why are you hitting the debug button once in the debug session? In this way we can see how to address this behavior in Spyder.

**Comment by nassimbnm** [comment]
For no special reason, sometimes by accident when already debugging for a long time I forget and hit the button again.
Also the icon may suggest the debugging can be paused and resumed, perhaps the button sould be greyed / deactivated.
Also I was curious to see if nested debug sessions were possible.

**Comment by ccordoba12** [comment]
> Also the icon may suggest the debugging can be paused and resumed, perhaps the button sould be greyed / deactivated.

Good point @nassimbnm! Thanks for bringing it out.

@impact27, what do you think about this one?

**Comment by impact27** [comment]
So nested debugging should be possible. This is definitely a bug to fix.

**Comment by ccordoba12** [comment]
> So nested debugging should be possible

I was thinking the same.

> This is definitely a bug to fix.

Could you help us with it?

**Comment by nassimbnm** [comment]
Thank you guys @steff456 @ccordoba12  @impact27
You and all people behind Spyder are doing an amazing job.

**Comment by ccordoba12** [comment]
Thanks @nassimbnm for your kind words! We really appreciate them.

**Comment by Caseyb87** [comment]
> 
> Also the icon may suggest the debugging can be paused and resumed, perhaps the button sould be greyed / deactivated.

Yes, I really dislike that this button appears to be a "pause" button. Coming from IDL, in which you can just pause a program, it totally threw me that this wasn't actually a pause program button.
