### ISSUE TITLE
Debugger ignores some tuple assignments

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14477]
```python
IPdb [1]: a, b = 1, 2
IPdb [2]: !a, b = 1, 2
```
Neither assign anything to `a` or `b`; further, into a debug session, the expression results local variables being printed, though I could not reproduce it minimally. Below, however, works fine:

```python
IPdb [3]: (a, b) = 1, 2
```
Stranger yet, only *after* executing `[3]`, `[1]` begins to work properly.

**Comment by steff456** [comment]
Hi @OverLordGoldDragon,

I'm unable to reproduce this error, can you please upload a gif with the behavior you are having?

**Comment by ccordoba12** [comment]
I could reproduce it @steff456 (please notice again that this only happens in the debugger).

@OverLordGoldDragon, I think the problem is with the variable names you picked for your example code. If I change them like this

```python
IPdb [1]: x, y = 1, 2
```

I don't see any errors. Could you try that and let us know what happens?

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 Yeah that works fine, I actually initially titled the issue like "tuple assignment treated as command", so `pdb` is getting confused by `a` but then it's somehow resolved by doing `(a, b) = ` first.

**Comment by ccordoba12** [comment]
Ok, then the problem lies in our logic to detect when an expression involves a Pdb command.

@impact27, how do you think we could solve this?
