### ISSUE TITLE
Disabling monitor scale change warning when using two screens

### ISSUE THREAD

**Issue by pmassat** [spyder-ide/spyder#14479]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ N/A] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ N/A] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I use two screens with different resolutions. When I drag the Spyder window from one screen to the other, the following message appears: 
"A monitor scale change was detected.
We recommend restarting Spyder to ensure that it's properly displayed. If you don't want to do that, please be sure to activate the option
Enable auto high DPI scaling 
in Preferences > General > Interface, in case Spyder is not displayed correctly.
Do you want to restart Spyder?"
This warning message appears when the Preferences > General > Interface > Screen resolution setting is set to either "Normal" or "Custom high DPI scaling".
It does not appear when "Enable auto high DPI scaling" is selected, however I do not like the automatic scaling of the window, I prefer when the scaling is the same on both screens.

### What steps reproduce the problem?

1. Open Spyder
2. With the Preferences > General > Interface > Screen resolution setting set to either "Normal" or "Custom high DPI scaling", drag the window from one screen to the other, which has a different resolution.
3. 

### What is the expected output? What do you see instead?
I do not want to apply any DPI scaling, as I am perfectly content with how Spyder is displayed on both monitors with the "Normal" setting of the Preferences > General > Interface > Screen resolution menu. Of course I can disable the warning message temporarily by ticking the "Hide this message during the current session" box before clicking the "Dismiss" button of the warning window, but it is kind of tedious having to do it at each session. Is there a way of disabling it permanently?

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.4.0 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  None (NOK)

```

**Comment by ccordoba12** [comment]
Hey @pmassat, thanks for reporting. You said:

> Of course I can disable the warning message temporarily by ticking the "Hide this message during the current session" box before clicking the "Dismiss" button of the warning window, but it is kind of tedious having to do it at each session

Unfortunately, we can't offer an option to hide that warning forever because it would lead to an inconsistent interface if you connect Spyder to different monitors than the ones you describe in this issue.

So, if don't want to take our advice of setting `Enable auto high DPI scaling`, I'm afraid you'll have to leave with this minor inconvenience, sorry.

**Comment by pmassat** [comment]
Ok no worries, thanks for your response.

**Comment by KennethGrimes** [comment]
> Hey @pmassat, thanks for reporting. You said:
> 
> > Of course I can disable the warning message temporarily by ticking the "Hide this message during the current session" box before clicking the "Dismiss" button of the warning window, but it is kind of tedious having to do it at each session
> 
> Unfortunately, we can't offer an option to hide that warning forever because it would lead to an inconsistent interface if you connect Spyder to different monitors than the ones you describe in this issue.
> 
> So, if don't want to take our advice of setting `Enable auto high DPI scaling`, I'm afraid you'll have to live with this minor inconvenience, sorry.

Hi Carlos, 

I have the same issue as the original poster, I tried setting "Enable auto high DPI scaling" and restarting Spyder but the error message continues to appear. Is there any way to make this warning disappear??

Thanks in advance!

**Comment by ccordoba12** [comment]
Given that a lot of people find that warning very annoying and it's also triggered in the wrong circumstances, we will offer an option to not show it again in our next version (5.1.2), to be released shortly.

**Comment by GroovyGeek** [comment]
Even with high dpi autoscaling turned on, there is still a prompt to restart Spyder.  Unfortunately, very often the modal dialog to acknowledge the restart is hidden behind the main window with no means of bringing it to the front.  This locks up Spyder completely necessitating a manual termination of the process and restart.  I personally would find it less annoying if it just did the restart without asking for confirmation.  At the very least the confirmation dialog should not be modal.

**Comment by ccordoba12** [comment]
@GroovyGeek, please open a new issue about making that dialog non-modal. I understand your point but it's not so easy to do it as it sounds.

**Comment by debvrat** [comment]
> Given that a lot of people find that warning very annoying and it's also triggered in the wrong circumstances, we will offer an option to not show it again in our next version (5.1.2), to be released shortly.

Thanks. Now that we work in an increasingly remote environment, the monitor-change-phenomenon happens a lot unfortunately.

**Comment by jeremymatt** [comment]
Thank you very much for fixing this; much appreciated.
