### ISSUE TITLE
The first execution keeps no response, but the follow-up is normal

### ISSUE THREAD

**Issue by Aegis1863** [spyder-ide/spyder#14475]
When I first execute any program, it keeps no return state. It's like the picture below.
![image](https://user-images.githubusercontent.com/46989391/102794114-d67cb180-43e5-11eb-8efa-78504865cba8.png)

But when I cleared the variables and executed the same program again, the output was normal as follow.
![image](https://user-images.githubusercontent.com/46989391/102794145-e399a080-43e5-11eb-9d38-2b677a9f9acf.png)

- It happens not every time, sometimes I reboot computer, the bug disappear, but sometimes it happens again.
- Another bug, sometimes I run code, it return `execution aborted`, only if I open a new console, it could be solve.
![image](https://user-images.githubusercontent.com/46989391/103071633-f5a25b80-45fe-11eb-91cd-992e3ed6fbd2.png)

- BTW, after I update Spyder, there are two shortcut, the bug seems to due to the old shortcut.
- However, in my another computer, it doesn't have the bugs mentioned above.
- The Spyder version is 4.2.1.
- Windows 10.

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.4.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  50.3.1.post20201107 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)

**Comment by Aegis1863** [comment]
All right, after reboot my computer, this bug is disappear.

**Comment by Aegis1863** [comment]
It seems to have been solved after I run `conda update anaconda`, BTW

**Comment by ccordoba12** [comment]
Hey @Aegis1863, thanks for reporting. This looks like an an Anaconda installation issue, so you need to remove and reinstall it again.

Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do it.

**Comment by Aegis1863** [comment]
@ccordoba12 Thank you, I will try it.

**Comment by Aegis1863** [comment]
I solve this by code `conda install anaconda-clean` and then `anaconda-clean --yes`.
