### ISSUE TITLE
Set a minimal width for the projects pane 

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#14486]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When the projects pane opens automatically after creating a new project the width is too low.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by angelasofiaremolinagutierrez** [comment]
I tried to reproduce the problem in the version of spyder I had installed in my pc (4.1.5)

![image](https://user-images.githubusercontent.com/10239480/219408540-c89c33c2-3aa1-4d97-9073-57e9d3bde006.png)

and the problem occurred, see gif below:

![old-spyder](https://user-images.githubusercontent.com/10239480/219408696-4f473c01-75f6-4529-be85-49d6b7ecd3ad.gif)




**But** when I tried to reproduce the problem with the spyder I cloned from branch `5.x`

![image](https://user-images.githubusercontent.com/10239480/219409222-d60fff3c-f358-4f3e-ba1c-8b85680db674.png)

the problem **did not** occur, see gif below:

![new-spyder](https://user-images.githubusercontent.com/10239480/219409375-accae159-76af-4182-8ab4-5a937acc7073.gif)

**Comment by angelasofiaremolinagutierrez** [comment]
@dalthviz  I think the bug has been resolved in this newer version

I'm navigated the project to make sure this was solved. And I found in the file [`spyder\plugins\projects\widgets\main_widget.py`](https://github.com/spyder-ide/spyder/blob/5.x/spyder/plugins/projects/widgets/main_widget.py)
the following line:

 `self.setMinimumWidth(200)`

**Comment by ccordoba12** [comment]
Good job @angelasofiaremolinagutierrez! You're right, this bug is fixed now and we were not aware of it. Sorry for making you waste time on it.

Then, please take a look at issue #16466. And your time to solve it is extended to up to next Thursday.

Good luck with that one!
