### ISSUE TITLE
numbers without apostrophies arent working

### ISSUE THREAD

**Issue by lilith-2000** [spyder-ide/spyder#14490]
### What steps will reproduce the problem?

character_name = 'lujain'
character_age = 50   #typing the number wihtout apostrpohies isnt letting me produce the same result i want when it is supposed to work since it is a number , no need for apostrophies.same oproblem in the belowe character_name

print('There was once a man named ' + character_name + ',')
print('he was ' + character_age + ' years old.')

character_name = 'omar'
character_age = 20

print('he really like the name ' + character_name + ',')
print('but didnt like being ' + character_age + '.')

## Versions

* Spyder version: 4.1.4 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @lilith-2000 this is unrelated to Spyder but basically to concatenate a string with a number you need to parse the number as a string (you can use the built-in function `str()`) If you don't do that then an error will appear when trying to run your code (probably something like: `TypeError: can only concatenate str (not "int") to str`). For more info you can checkout resources like this: https://stackoverflow.com/a/51805256

Hope this info helps you :)
