### ISSUE TITLE
ModuleNotFoundError: No module named 'spyder.utils.iofuncs'

### ISSUE THREAD

**Issue by chessybo** [spyder-ide/spyder#14505]
I want to load .spydata files with load_dictionary. However for some reason it can't find the module. I thought this was something already in Spyder? I am running spyder 3.3.1 and I don't want to update it for compatibility reasons.

from spyder.utils.iofuncs import load_dictionary
ModuleNotFoundError: No module named 'spyder.utils.iofuncs'

also, whats the difference between using pip install or conda install? I install from the Anaconda Command prompt. I've used pip install for pyqt5. is that going to cause problems?

**Comment by ccordoba12** [comment]
Hey @chessybo, thanks for reporting. You said:

> I am running spyder 3.3.1 and I don't want to update it for compatibility reasons.

Unfortunately, Spyder 3 is no longer maintained, so we can't offer you help about this. Thanks for understanding.
