### ISSUE TITLE
Internal problem encountered, and Spyder still slow

### ISSUE THREAD

**Issue by gkvallis** [spyder-ide/spyder#14509]
### What steps will reproduce the problem?

I upgraded to Spyder 4.2.1 using conda install spyder=4.2.1 -c conda-forge.   (the 4.2.1 only seems available on conda forge.)

I open SPyder and it tells me it has encounterd an internal problem, but not what that problem is. 
However, SPyder 4.2.1 is still very slow, and the keyboard isunresponsive as before, on a Imac running Big Sur.

I also tried out the MacOS version, with Spyder as a regular Mac application. The problem does not occur there.  (As a general question, is there a push to use the Mac application rather than conda? But unfortunately, I can't get the notebook to appear on the Mac application)

### Traceback
```python-traceback
  File "/Users/gkv/anaconda3/lib/python3.8/site-packages/spyder/plugins/editor/widgets/status.py", line 113, in process_git_data
    branches, branch, files_modified = output
TypeError: cannot unpack non-iterable NoneType object
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.1
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 20.2.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.7.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.4.0 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by gkvallis** [comment]
I subsequently typed in:  conda update spyder  (without any conda-forge; and I do not have conda forge in my .condarc file). It told me certain packages would be superseded, and the  internal start-up error then went away. However, spyder  (4.2.1) still has an unusably slow keyboard response.

**Comment by ccordoba12** [comment]
Hey @gkvallis, thanks for reporting. You said:

> However, SPyder 4.2.1 is still very slow, and the keyboard isunresponsive as before, on a Imac running Big Sur.

Please run

    conda install -c conda-forge pyqt=5.12

to fix that.

By the way, I hope you've created a different conda environment to install things from conda-forge, as we recommend [here](https://docs.spyder-ide.org/current/faq.html#troubleshooting-macos-bigsur). Otherwise, you probably borked your Anaconda installation and now you have to reinstall it.

> As a general question, is there a push to use the Mac application rather than conda?

Yes, our new application is now our recommended installation method, instead of Anaconda.

> But unfortunately, I can't get the notebook to appear on the Mac application

Yeah, our notebook plugin is still a work in progress so we don't plan to massively distribute it yet, sorry.

**Comment by gkvallis** [comment]
Thanks. I figured it might be an old pyqt issue.  Re conda forge, the solution (for me) was to start again with miniconda and have condo-forge be the priority channel for everything. 

Looking forward to having the Mac application working fully. One suggestion for notebooks: if you open a notebook from the top file menu, or with "open -a spyder filename.ipynb", it would be good if it automatically opened in the notebook  console rather than the regular editing window. (VScode does this, and it is vey useful.) 
It might  also be good to be able to call the spyder application from the command line with some of the same options as the anaconda version. 

Thsnks again for the reply, and for Spyder itself.

**Comment by ccordoba12** [comment]
@gkvallis, glad to know Spyder is working for you now.
