### ISSUE TITLE
Cannot launch Spyder via Anaconda Navigator

### ISSUE THREAD

**Issue by justinchencya** [spyder-ide/spyder#14507]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Could not launch Spyder via Anaconda.

### What steps reproduce the problem?

1. Downloaded newest version of Anaconda Navigator
2. Updated all packages, including Spyder, using conda update --all
3. Tried to remove Spyder from Anaconda but failed

### What is the expected output? What do you see instead?
I clicked launch in Anaconda, which should launches Spyder. However, nothing happens at all.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.5
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS Catalina 10.15.7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @justinchencya, thanks for reporting. You said:

> Updated all packages, including Spyder, using conda update --all

This could have been the problem (it's not advisable to use that option). Please create a new conda environment, install Spyder on it and try again.

**Comment by justinchencya** [comment]
I see. Thanks.
