### ISSUE TITLE
exception while deleting selection in editor

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#14517]
### What steps will reproduce the problem?

I had a ~550 line Python script, I selected some code, hit delete, and got this exception. 

I tried it again (ctrl-z to undo the delete, then selected and deleted again) and I didn't get the exception, so not very reproducible. this is the first time it happened after around 3 days of having Spyder/Anaconda installed on a new machine while using several hours a day. But at least this lets you know there is a problem in that region of code.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\editor.py", line 161, in _exec_requested_job
    self._job(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor\panels\codefolding.py", line 471, in _highlight_block
    end_line = self.folding_regions[block_line]
KeyError: 42
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @rlabbe, thanks for reporting. This is already fixed and part of our 4.2.1 version, released two weeks ago.

Since the Anaconda team is taking too much time to update our releases, you're welcome to use our [Windows installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder_64bit_full.exe) instead.

If you prefer not to do that, you'll have to wait two more weeks (perhaps more) until new conda packages are available.
