### ISSUE TITLE
How to view numbers in a dataframe with thousands separator in spyder variable explorer?

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#14518]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
How to view numbers in a dataframe with thousands separator in spyder variable explorer?

### What steps reproduce the problem?

1. I tried typing %,.2f and %0:,.2f and many other similar combinations in the float formatting filed of the format section but didn't work!
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.5
* Qt version: 
* PyQt version: 
* Operating System name/version: macos 11.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @mhdmyz, 

Can you please post a screenshot of what you are seeing after typing `%,.2f and %0:,.2f`?

**Comment by ccordoba12** [comment]
@jitseniesen, could you take a look at this one?

**Comment by jitseniesen** [comment]
I don't think these are valid formats, according to [`printf`-style String Formatting](https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting) in the Python docs.

If we need to provide this functionality, I think we need to use `.format()` instead of the `%` operator to format the numbers.

**Comment by ccordoba12** [comment]
> I think we need to use .format() instead of the % operator to format the numbers.

That sounds more powerful than our current approach. Do you have time to do that?

**Comment by jitseniesen** [comment]
No problem, I'll take care of it. It will introduce a minor incompatibility, in that the user will have to input the format string as `.6f` instead of `%.6f`, but config files should remain valid and it will actually simplify the code.

Should I target v4 or v5?

**Comment by ccordoba12** [comment]
> Should I target v4 or v5?

If the change is small or not disruptive, you can target it for 4.x. Otherwise, it needs to go against master.

**Comment by mg3146** [comment]
did anything ever come of this?  I'd be interested on it too!  thx!

**Comment by jitseniesen** [comment]
@mg3146 Thanks for the reminder. Nothing seems to have done about this. I don't remember what happened at that time, but it looks like I forgot about this. I will add it to my to-do list.

**Comment by ccordoba12** [comment]
@mg3146, this will be part of Spyder 6, to be released in the second half of the year.
