### ISSUE TITLE
Update Editor features page - add screenshot with current element highlight

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1452]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-21T08:22:09Z_

Highlight of the element under cursor both in text and in scrollbar is a convenient feature of Spyder. It should be documented in a screenshot.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1452_

**Comment by ccordoba12** [comment]
This no longer applies.
