### ISSUE TITLE
Line break before type hint breaks docstring generation

### ISSUE THREAD

**Issue by Richardk2n** [spyder-ide/spyder#14521]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

If a function cantains a line break between a parameter and its type hint like so:
```
def test(v:
         int):
```
Typing """ does not activate the docstring generator and using the shortcut produces the following:
```
def test(v:
    """
    

    Parameters
    ----------
    v : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    """
         int):
```
It looks like the generator thinks the function ends in the first line (besides the lacking ')') because, see example below:
```
def test(d: str, v:
         int, a: None) -> bool:
```
```
def test(d: str, v:
    """
    

    Parameters
    ----------
    d : str
        DESCRIPTION.
    v : TYPE
        DESCRIPTION.

    Returns
    -------
    None.

    """
         int, a: None) -> bool:
```

### What steps reproduce the problem?

1. Enter the provided example
2. Press the docstring shortcut
3. 

### What is the expected output? What do you see instead?

A valid docstring
See above

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 1.9.1
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @Richardk2n,

I could reproduce this issue, we will work in this for one of our future releases.

Thanks for reporting!

**Comment by Richardk2n** [comment]
By the way, this issue is caused by the code checking for ":" to determine the function definition end. I have a fix running, that changes that to `endswith("):") or endswith("]:") or (endswith(":") and contains("->"))` this works for most cases i can imagine. If you want, I could try to write a proper fix.

**Comment by ccordoba12** [comment]
> this works for most cases i can imagine. If you want, I could try to write a proper fix.

Yes, please do! We'd really appreciate your help with that.
