### ISSUE TITLE
auto format is not enabled at spyder 4.2.1 installed using conda

### ISSUE THREAD

**Issue by zhl355** [spyder-ide/spyder#14538]
### What steps will reproduce the problem?

Go to source, the drop down list shows up format files or selection with autopep8. But this item is gray which is un-clickable

## Versions

* Spyder version: 4.2.1 
* Python version: 3.6.12
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-58-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.8.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.4.2 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by steff456** [comment]
Hi @zhl355,

Did you notice if the option become gray after changing a particular configuration in the preferences pane?

**Comment by zhl355** [comment]
They are too many things in **Preferences**. I restore the **Preferences** to default using **Reset to defaults**. Spyder restarts automatically. The format file option under **Source** is still gray.

**Comment by steff456** [comment]
Can you see the option you have under `Preferences>Code completion and linting>Code style and formatting>Code formatting` and let me know if you have autopep8 there?

**Comment by zhl355** [comment]
![autopep8](https://user-images.githubusercontent.com/32444985/103968142-2793e180-5118-11eb-89b5-3c298f6b5cbc.png)

**Comment by steff456** [comment]
If you do right click on the editor can you select the option `autoformat with autopep8`? Also what happens if you try with the shortcut `Ctrl+Alt+I`?

**Comment by zhl355** [comment]
Nothing happened right click is still gray. Shortcut is not working neither. If there is not quick fix, I could just use other text-editor for this and wait for future updates. 
https://user-images.githubusercontent.com/32444985/104065422-90309c00-51b4-11eb-921d-1cb72b11ed2f.mp4

**Comment by ccordoba12** [comment]
@zhl355, according to your initial report, you're using Python 3.6.12.  So this could be an issue with that Python version.

Please create a conda environment with Python 3.7, install Spyder on it and try again. We can assure you this functionality is working fine in 3.7 and later versions (we don't run our tests on 3.6 anymore, sorry).

**Comment by zhl355** [comment]
@ccordoba12 The option is enabled when I using python 3.8.6. The formatter itself is not working well though. But I guess it is not your team's problem.

**Comment by ccordoba12** [comment]
Ok, good to know you finally saw that functionality available in Spyder.
