### ISSUE TITLE
After crash Spyder will not start even after reinstall

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1453]
_From [lower...@gmail.com](https://code.google.com/u/100568078051384101626/) on 2013-06-21T11:01:56Z_

I've the following issue which is now affecting 2 computers using spyder-2.2.0 on 64 bit Win7.

1. Open a large array component of a dictionary in var. explorer
2. Spyder crashes
3. When I attempt to restart Spyder it will not restart (even after reinstalling)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1453_

**Comment by spyder-issues-migrator** [comment]
_From [luckw...@gmail.com](https://code.google.com/u/111063060450190910996/) on 2013-06-25T16:15:21Z_

I have a similar problem, and it sounds like others have had it too.  Issues 1344 and 1242 seem to be related.

One solution in the comments of issue #1344 was that you can restart Spyder if you open a terminal and write:
rm .spyder2/spyder.lock

This didn't work for me.  I had to modify it to
rm -r .spyder2/spyder.lock

I didn't know what the equivalent command was in DOS, so I used the above command in a Cygwin terminal.  It has allowed me to reopen Spyder, although this clearly does not fix the larger issue of the crashing.

**Comment by spyder-issues-migrator** [comment]
_From [lower...@gmail.com](https://code.google.com/u/100568078051384101626/) on 2013-06-26T02:26:37Z_

Ah right - that makes sense and let me get spyder running again. thanks

spyder.lock is a folder which tells spyder not to start another instance. With these crashes it doesn't seem to be being removed (as Spyder isn't closing). You can find it in windows inside your \<username>\spyder2 directory and deleting it will fix the no-restart problem (that's what the rm command is doing - del or just deleting from explorer works as well).

I'll live with the occasional crash.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-26T03:11:48Z_

I believe we can do better by writing process id into the spyder.lock if it is impossible to create symlink for this process. For that we may need to upgrade/enhance/replace ./utils/external/lockfile.py

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-29T08:42:49Z_

**Status:** Duplicate  
  **Mergedinto:** 1441

**Comment by ccordoba12** [comment]
Also related to issue #2363
