### ISSUE TITLE
Extra space added to multiline bracketed objects

### ISSUE THREAD

**Issue by Balter85** [spyder-ide/spyder#14533]
When attempting to begin a multiline bracketed object, such as a list or dictionary, an extra space is added upon hitting return.

![Intentation Issue](https://user-images.githubusercontent.com/28100883/103577494-ee9f0700-4ea2-11eb-8f8b-940479017da5.gif)

### What steps reproduce the problem?

1.  See Gif

### What is the expected output? What do you see instead?
I expect that hitting return will place the cursor one space behind where it does.

## Versions
* Spyder version: 4.2.0
* Python version: 3.8.5 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by Balter85** [comment]
On more experimentation, this only seems to be a problem with short variable names.  For instace:

mylist = [
    1, 2, 3
]

Does not seem to suffer from this problem.

**Comment by ccordoba12** [comment]
Hey @Balter85, thanks for reporting. This really depends on the way you want to format your code. We add the extra space you mentioned to keep the indentation level of the previous line, which is what most people expects, but not in this case.

Fortunately, we now offer auto-formatting with Black, which could solve this issue automatically. To activate it, please go to

    Tools > Preferences > Completion and linting > Code formatting

and change our formatting provider to `black`. After that, you can use the `Ctrl+Alt+I` keyboard shortcut to format your current file or selection.

Please do that and let us know if it works for you.

**Comment by Balter85** [comment]
Hi,

  Thank you for the response.  While it doesn't solve this particular issue, I was unaware of CTRL-ALT-I which does make my life easier.  Thank you.  Feel free to close the issue.

**Comment by ccordoba12** [comment]
> I was unaware of CTRL-ALT-I which does make my life easier. Thank you

Glad you found our new auto-formatting functionality useful.

>  Feel free to close the issue.

Ok, closing then.
