### ISSUE TITLE
"no module name pip" showing in spyder

### ISSUE THREAD

**Issue by Anushka290** [spyder-ide/spyder#14541]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version: window 7

### Dependencies

```
PASTE DEPENDENCIES HERE
```
@ccordoba12 
![Screenshot (1)](https://user-images.githubusercontent.com/57558433/103653790-094cab00-4f8b-11eb-922c-ae064285600c.png)

**Comment by Anushka290** [comment]
it is not working
![Screenshot (2)](https://user-images.githubusercontent.com/57558433/103739013-fb466b00-501a-11eb-8ed6-2529114ade83.png)
![Screenshot (3)](https://user-images.githubusercontent.com/57558433/103739019-fe415b80-501a-11eb-999f-aaab7032b9b2.png)
![Uploading Screenshot (4).png…]()

**Comment by ccordoba12** [comment]
Thanks for the screenshots. I can see in them you incorrectly typed the second command I posted above:

    conda create -n myenv spyder-kernels nltk

You wrote spyder-kern**a**ls, when the correct name is spyder-kern**e**ls.

So, please try again.

**Comment by Anushka290** [comment]
sir thank you for giving me your precious time @ccordoba12 
![Screenshot (5)](https://user-images.githubusercontent.com/57558433/103801184-6459cd00-5073-11eb-94af-f5330ebef3f5.png)
![Screenshot (6)](https://user-images.githubusercontent.com/57558433/103801220-6e7bcb80-5073-11eb-98f0-02b8571ceb75.png)
![Screenshot (7)](https://user-images.githubusercontent.com/57558433/103801225-720f5280-5073-11eb-8792-fc18864ac688.png)

**Comment by Anushka290** [comment]
but spyder kernal is not working
![Screenshot (8)](https://user-images.githubusercontent.com/57558433/103803467-9e789e00-5076-11eb-981e-788efc12eaff.png)

**Comment by ccordoba12** [comment]
I don't understand what you did to get the error in your last screenshot, but after selecting `myenv` in `Python Interpreter` you need to go to the menu

    Consoles > New console (default settings)

That will open a new console that you can use with `nltk`.

Or you can simply close and start Spyder again.

**Comment by Anushka290** [comment]
![Screenshot (9)](https://user-images.githubusercontent.com/57558433/103852327-a7e32400-50d1-11eb-86ef-1032a19087d5.png)
![Screenshot (10)](https://user-images.githubusercontent.com/57558433/103852336-ad406e80-50d1-11eb-96bd-8d583dbe1b3a.png)

**Comment by ccordoba12** [comment]
I don't understand why you keep posting screenshots with you trying to install `spyder-kernal` when I told you that the right package name is `spyder-kernels`.

Please close Spyder and run these commands in `cmd.exe` now to see if you're able to successfully install and use `nltk`:

    conda activate base
    conda env remove -n myenv
    conda create -n myenv spyder-kernels nltk

**Comment by aagha** [comment]
@ccordoba12 Your documentation is helpful. Thanks.

I've followed your steps, but keep running into this issue in Spyder:

![image](https://user-images.githubusercontent.com/5522103/152238953-d1ea6d4e-f8c4-43ae-9156-b6e6ad4450a5.png)

*Note requirement for >- 2.2.1

The issue seems to be that if you run:

`conda create -n myenv spyder-kernels nltk`

a version prior to 2.2.1 is getting pulled in.

If I change your create call to:

`conda create -n myenv spyder-kernels=2.2.1 nltk`

That package is not found.

Any ideas on how to satisfy this version requirement for spyder-kernels?

**Comment by ccordoba12** [comment]
Please run

    conda create -n myenv -c conda-forge spyder-kernels=2.2.1 nltk

The problem is the Anaconda team takes way too much time to update our packages, so lately they are only available in Conda-forge.

**Comment by CoveMach** [comment]
> Trying this last command, 'conda create -n myenv -c conda-forge spyder-kernels=2.2.1 nltk' I reach past the proceed ([y]/n)? question, but then I get the following test: 

```
"Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(730): An error occurred while installing package 'conda-forge::vs2015_runtime-14.29.30037-h902a5da_6'.
Rolling back transaction: done

[Errno 13] Permission denied: 'C:\\Users\\---\\miniconda3\\envs\\myenv\\vcruntime140.dll'
()"
```

**Comment by bahnen** [comment]
```
cloudpickle-2.0.0    | 32 KB     | ############################################################################ | 100%
python-3.10.4        | 15.9 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```
I have been struggling with this as Everything ran and updated correctly, however I am not able to find where to connect when changing my environment preference.  Has anyone else ran into this issue?  Thanks

**Comment by xryxz** [comment]
I have read through this and done every step yet when I try to run my script using spyder, and I click run there is a pop up that says "can't open file" and "[errno 2] no such file or directory". How should i fix this?

**Comment by ketho96** [comment]
I solved the Issue. Download WinPython as a developement environment vai https://sourceforge.net/projects/winpython/ . Then execute the file. In the directory you will find the spyder.exe.
pip install will work.
