### ISSUE TITLE
cannot make code analysis and profiler panes narrower

### ISSUE THREAD

**Issue by rlloretb** [spyder-ide/spyder#14553]
I cannot make the code analysis and profiler panes narrow enough than if the pane did not have them.
This problem does not arise with Variable Explorer, Help, Plots, Files, Find.

This is inconvenient when working with small screens.

* Spyder version: 4.2.0
* Python version: 3.7.7
* Qt version: 
* PyQt version: 
* Operating System name/version: MacOS Catalina

**Comment by ccordoba12** [comment]
Hey @rlloretb, thanks for reporting. This is a known issue and we'll try to fix it for Spyder 5.
