### ISSUE TITLE
Big Sur: spyder 4.2.0 or 4.2.1, undocking the editor results in high typing latency; the focused tab in the editor has a white squa

### ISSUE THREAD

**Issue by btglau** [spyder-ide/spyder#14550]
## Problem Description

There has been a documented / discussed problem with spyder 4.2.0 on Big Sur where there is high typing latency in the editor. I have tried 4.2.1 which solves the typing latency. **However**, if the editor is undocked (such that macos now presents a single spyder window with two tabs, one for everything else, and one for the editor), and if you drag the tab out to a separate window, the typing latency reappears.

Additionally, there is a problem where the current file open in the editor is whited out. This issue also occurs for the "Variable Explorer" and "Plots" buttons.
<img width="280" alt="Screen Shot 2021-01-07 at 1 26 12 PM" src="https://user-images.githubusercontent.com/14989045/103929942-fdc4c580-50eb-11eb-96f9-559f33e215d0.png">

### What steps reproduce the problem?

1. Open spyder 4.2.0 or 4.2.1
2. Undock the editor, optionally try dragging the undocked editor tab out to its own window
3. Try typing

### What is the expected output? What do you see instead?
No typing latency. High typing latency. 

Note, for the information below, I followed the FAQ to install spyder 4.2.1 as a fix for Big Sur typing problems.
## Versions

* Spyder version: 4.2.0
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Darwin 20.2.0

### Dependencies

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.4.2 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.0 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

**Comment by ccordoba12** [comment]
Hey @btglau, thanks for reporting. This is probably an issue with Qt (the graphical toolkit used by Spyder), so there's little we can do about it.

@impact27, are you observing the same behavior when undocking the editor?

**Comment by impact27** [comment]
With: Python 3.8.6 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Darwin 20.2.0  I don't have any problem undocking the editor.

**Comment by ccordoba12** [comment]
Thanks @impact27 for your help testing that!

@btglau, please download and install Spyder with our [DMG installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg). You shouldn't see any problems with it in Big Sur.

**Comment by btglau** [comment]
Hi @ccordoba12 thanks for the tip. If I use this installer, will it be compatible with an anaconda installation?

**Comment by ccordoba12** [comment]
Yes, Spyder automatically detects your conda environments so you can use them from the application. Please follow the instructions in our [FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) to learn how to do that.

**Comment by btglau** [comment]
Hi, the new version as installed from the dmg indeed fixes both issues I outlined. It also picked up my old environment and preferences without me having to set anything, which is nice. Thanks!

**Comment by ccordoba12** [comment]
Great to know, thanks for the update @btglau!

Closing this report then.
