### ISSUE TITLE
saving empty profiler

### ISSUE THREAD

**Issue by Czimchik** [spyder-ide/spyder#14563]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
1. Profiler not showing any data
2. Clicked "Save data"
3. Tried to save on desktop
4. This error

**Comment by ccordoba12** [comment]
Hey @Czimchik, thanks for reporting. Please post the error you're getting to understand what's happening in your case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
