### ISSUE TITLE
Can we setup Spyder as default text file editor?

### ISSUE THREAD

**Issue by Mr-ZBin** [spyder-ide/spyder#14587]
Hi,

I have question about to open text file. Can we open a file via double-click it just similarly open it in notepad?
Also, can we setup Spyder as a **default text file editor** likes notepad?

Thank you very much.

**Comment by andfoy** [comment]
Hi @Mr-ZBin, if you are using Windows or Mac, you can install Spyder from one of our official installers: https://github.com/spyder-ide/spyder/releases/tag/v4.2.1, the new installers allow for better context menu integration on the OS, which means that you set Spyder as your default text editor

**Comment by Mr-ZBin** [comment]
Hi, Thanks for your response. I got it.
