### ISSUE TITLE
I think there is a problem with main focus

### ISSUE THREAD

**Issue by lsw417** [spyder-ide/spyder#14580]
## Problem Description

1. I think there is a problem with main focus while working with run selection in spyder.
   -For one editor, the main focus editor option works fine.
   -In the case of two editors using a new window, there is a fatal problem with focus on the console after run selection.

2. If you open the same "test.py" in the new window and zoom in, the main editor and the new window editor zoom together. I think they should apply differently

**Comment by dalthviz** [comment]
Hi @lsw417 for the feedback!

Regarding your first comment I was unable to reproduce the issue, could you be able to send us a video capture or GIF that shows how you are being able to generated the error?

Regarding the second comment, I was able to reproduce it and actually I think currently the editors (the one in the main window and any other in a new window, are linked (not only zoom but also for example the files that are open), what do you think about that @ccordoba12 ?

**Comment by dalthviz** [comment]
Closing due to lack of response
