### ISSUE TITLE
"ImportError: No module named PySide" in console when start-up

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1459]
_From [a9602...@gmail.com](https://code.google.com/u/114708001219724688662/) on 2013-06-26T01:51:55Z_

Hello,

I installed the Spyder-2.2.0.dmg file on my Mac (OSX 10.8.4). After I opened Spyder, the following error occurred at startup in the console box. Could someone tell me what is this problem and how to resolve it? 

Thanks in advance, 
James

Python 2.7.3 (default, Jul 24 2012, 20:20:13) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.9.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/spyderlib/scientific_startup.py", line 16, in \<module>
    from pylab import *  #analysis:ignore
  File "pylab.pyc", line 1, in \<module>
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/pylab.py", line 265, in \<module>
    from matplotlib.pyplot import *
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/pyplot.py", line 97, in \<module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/backends/__init__.py", line 25, in pylab_setup
    globals(),locals(),[backend_name])
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/backends/backend_qt4agg.py", line 13, in \<module>
    from backend_qt4 import QtCore, QtGui, FigureManagerQT, FigureCanvasQT,\
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/backends/backend_qt4.py", line 24, in \<module>
    from qt4_compat import QtCore, QtGui, _getSaveFileName, __version__
  File "/Applications/Spyder.app/Contents/Resources/lib/python2.7/matplotlib/backends/qt4_compat.py", line 80, in \<module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ImportError: No module named PySide

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1459_

**Comment by spyder-issues-migrator** [comment]
_From [a9602...@gmail.com](https://code.google.com/u/114708001219724688662/) on 2013-06-27T19:45:19Z_

Can anyone shed light on what is this problem? That'd be much appreciated. Thanks!

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-06-28T09:18:26Z_

Spyder depend on having either PyQt or PySide installed on your system. Do you have either of those installed?

**Comment by spyder-issues-migrator** [comment]
_From [a9602...@gmail.com](https://code.google.com/u/114708001219724688662/) on 2013-06-28T09:27:04Z_

I see. I didn't have those installed, I'm a complete beginner so I don't know about it. I couldn't find it mentions such requirements on the installation instructions so I thought the dmg file is self-complete. 

1 .Which version of PyQt or PySide would you recommend? 

2. Should I remove Spyder and install PyQt/PySide first before reinstalling Spyder? 

To uninstall Spyder on my Mac, what steps should I take to completely remove all the files and dependencies (anything else besides dragging the icon to the trash bin)?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-06-28T09:33:18Z_

Jed I think this is a problem with our attempt to auto-detect if PyQt or PySide is installed so that we can set the right matplotlib backend.

@-a9602343: To solve it, you need to go to:

Preferences > Tools > Console > External Modules > Matplotlib

and change it from "Qt4Agg" to "MacOSX"

**Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [kevinydi...@gmail.com](https://code.google.com/u/102902147470781123711/) on 2013-09-13T13:28:42Z_

I get the same error after installing 32 bit Spyder on Windows 7.  I don't see how ccordoba12's suggestion can work when Spyder won't open up in the first place. I've attached the error's output.

**Attachment:** [spyder-error.png](http://code.google.com/p/spyderlib/issues/detail?id=1459#hc5)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T19:04:02Z_

I hope you've found how to fix this one by now :-)

**Status:** WontFix

**Comment by JimHokanson** [comment]
I'm using Windows 7. I encountered this problem after installing Anaconda for Python 2.7 after having Python 3.4 installed (via Anaconda). I ended up not needing Python 2.7 so I switched the spyder shortcut back to Python 3.4 and things work fine.
