### ISSUE TITLE
KeyError('pandas._libs.interval') while opening a dataframe in variable explorer in dmg version of spyder

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#14593]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm getting KeyError('pandas._libs.interval') while opening a dataframe in the variable explorer. I'm using dmg version of spyder on an anaconda environment. I reinstalled both anaconda and spyder but didn't solve the issue.

<img width="415" alt="Screen Shot 1399-10-25 at 22 14 43" src="https://user-images.githubusercontent.com/47456155/104634735-449b5800-56b6-11eb-829e-b4c1a7ce8de8.png">

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 
* PyQt version: 
* Operating System name/version: macos 11.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @mhdmyz, thanks for reporting this issue, this was fixed on https://github.com/spyder-ide/spyder/pull/14545, which is going to available on the next Spyder release, v4.2.2. Until the next release is available, there is nothing much we can do at this moment. Thanks for you patience

**Comment by mhdmyz** [comment]
Thank you! When is it going to be released? It's weird! it was working fine on my MacBook before reinstalling anaconda!

**Comment by mhdmyz** [comment]
> Hi @mhdmyz, thanks for reporting this issue, this was fixed on #14545, which is going to available on the next Spyder release, v4.2.2. Until the next release is available, there is nothing much we can do at this moment. Thanks for you patience

Thank you! When is it going to be released? It's weird! it was working fine on my MacBook before reinstalling anaconda!

**Comment by ccordoba12** [comment]
The 15th of February

**Comment by mhdmyz** [comment]
> The 15th of February

Can I downgrade anything to make it work properly?! because I'm on the M1 MacBook and the anaconda version also has a huge delay while typing!

**Comment by b-a0** [comment]
@mhdmyz please stick to one problem per issue, this is not a forum. 
The issue where we're posting this is related to opening a dataframe in Spyder. The resolution is posted: we have to wait until th 15th of February for the new release.

The issue of the M1 typing delay sounds like a different problem. Have you [searched the existing issues for this](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue+is%3Aopen+m1)? If you did, you might have found #14599, which sounds like the same problem you have. Can you try out the solution proposed there and post back (on *that* issue!) if you run into any problems.

**Comment by mhdmyz** [comment]
> @mhdmyz please stick to one problem per issue, this is not a forum.
> The issue where we're posting this is related to opening a dataframe in Spyder. The resolution is posted: we have to wait until th 15th of February for the new release.
> 
> The issue of the M1 typing delay sounds like a different problem. Have you [searched the existing issues for this](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue+is%3Aopen+m1)? If you did, you might have found #14599, which sounds like the same problem you have. Can you try out the solution proposed there and post back (on _that_ issue!) if you run into any problems.

Thanks! I believe these two issues are kind of interrelated! I tried the solution #14599 (installing the dmg version) first and the problem was data frames won't open in the variable explorer. So I switched into the anaconda version and now there's a huge delay while typing! Seems there are only two options for me and both practically unusable!

**Comment by b-a0** [comment]
Then unfortunately the conclusion seems to be: there's no Spyder version that works on an M1 MacBook yet to your liking.

However, you're free to try older Spyder versions. You can [create a separate conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

```
conda create --name older_spyder 
```

and [install an older version](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-packages):

```
conda activate older_spyder
conda install spyder=any.version.number
```

**Comment by mhdmyz** [comment]
> Then unfortunately the conclusion seems to be: there's no Spyder version that works on an M1 MacBook yet to your liking.
> 
> However, you're free to try older Spyder versions. You can [create a separate conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)
> 
> ```
> conda create --name older_spyder 
> ```
> 
> and [install an older version](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-packages):
> 
> ```
> conda activate older_spyder
> conda install spyder=any.version.number
> ```

Yeah! and having to wait for a month in this situation is easier said than done! Is there a link to older dmg versions of Spyder to see whether they work?

**Comment by b-a0** [comment]
Does creating environments and installing older versions through conda not work? If so, why not?
Did you search Google for older spyder dmg files?

**Comment by mhdmyz** [comment]
> Does creating environments and installing older versions through conda not work? If so, why not?
> Did you search Google for older spyder dmg files?

I tried creating a new environment and installing an older version of Spyder on it (4.1.5) but it didn't work because still there was a huge delay while typing!
I did search google but couldn't find anything! doesn't spyder archive it's older versions?!

**Comment by ccordoba12** [comment]
There's a workaround. Please go to pull request https://github.com/spyder-ide/spyder/pull/14600, click on `View details`, then the `Details` link to the right of `macOS App Bundle (Full)`, then `Artifacts` (to the right):

![imagen](https://user-images.githubusercontent.com/365293/104828223-e2b52c80-5834-11eb-8aed-6c77822cea4b.png)

and finally click on `Spyder.dmg` on the menu that appears there.

That will give an installer with our latest fixes in our stable branch (i.e. everything that will be part of 4.2.2, including our fix for Pandas). However, please be aware that it could contain other bugs or problems because it's still a work in progress.

**Comment by mhdmyz** [comment]
> There's a workaround. Please go to pull request #14600, click on `View details`, then the `Details` link to the right of `macOS App Bundle (Full)`, then `Artifacts` (to the right):
> 
> ![imagen](https://user-images.githubusercontent.com/365293/104828223-e2b52c80-5834-11eb-8aed-6c77822cea4b.png)
> 
> and finally click on `Spyder.dmg` on the menu that appears there.
> 
> That will give you an installer with our latest fixes in our stable branch (i.e. everything that will be part of 4.2.2, including our fix for Pandas). However, please be aware that it could contain other bugs or problems because it's still a work in progress.

Thank you so much Carlos! I was going to ask you kind of the same thing! to release 4.2.2 sooner to let people who have the M1 MacBooks be able to use Spyder till the next update is released which is a long time to wait (a month!). Since there is was no other working option for this category of users and also because the problem was already solved in #14545. So again thank you!

**Comment by mhdmyz** [comment]
> There's a workaround. Please go to pull request #14600, click on `View details`, then the `Details` link to the right of `macOS App Bundle (Full)`, then `Artifacts` (to the right):
> 
> ![imagen](https://user-images.githubusercontent.com/365293/104828223-e2b52c80-5834-11eb-8aed-6c77822cea4b.png)
> 
> and finally click on `Spyder.dmg` on the menu that appears there.
> 
> That will give you an installer with our latest fixes in our stable branch (i.e. everything that will be part of 4.2.2, including our fix for Pandas). However, please be aware that it could contain other bugs or problems because it's still a work in progress.

I can confirm that this workaround works just fine! But be sure to remove the older dmg version of spyder fro your Mac and then reinstall this version. Otherwise you'll get `No module named 'encodings'` error. Again thank you so much @ccordoba12!

**Comment by mhdmyz** [comment]
> There's a workaround. Please go to pull request #14600, click on `View details`, then the `Details` link to the right of `macOS App Bundle (Full)`, then `Artifacts` (to the right):
> 
> ![imagen](https://user-images.githubusercontent.com/365293/104828223-e2b52c80-5834-11eb-8aed-6c77822cea4b.png)
> 
> and finally click on `Spyder.dmg` on the menu that appears there.
> 
> That will give you an installer with our latest fixes in our stable branch (i.e. everything that will be part of 4.2.2, including our fix for Pandas). However, please be aware that it could contain other bugs or problems because it's still a work in progress.

The only question is wouldn't it be better to provide us a dmg version for Spyder 4.2.2.dev instead of Spyder 4.3.0.dev0? I'm not sure whether it's possible, I just think it would be safer considering the probable bugs!

**Comment by ccordoba12** [comment]
> The only question is wouldn't it be better to provide us a dmg version for Spyder 4.2.2.dev instead of Spyder 4.3.0.dev0? I'm not sure whether it's possible, I just think it would be safer considering the probable bugs!

Good thinking. However, that correspond to the way we name development versions. We don't name bugfix releases (i.e. `4.2.2dev`), just minor ones (i.e. `4.3.0dev`).

I understand that's a bit odd (specially because there's not going to be a `4.3.0` release at the end), but we decided to do that years ago for all projects we maintain, so now it's kind of hard for us to change it.

**Comment by mhdmyz** [comment]
> > The only question is wouldn't it be better to provide us a dmg version for Spyder 4.2.2.dev instead of Spyder 4.3.0.dev0? I'm not sure whether it's possible, I just think it would be safer considering the probable bugs!
> 
> Good thinking. However, that correspond to the way we name development versions. We don't name bugfix releases (i.e. `4.2.2dev0`), just minor ones (i.e. `4.3.0dev0`).
> 
> I understand that's a bit odd (specially because there's not going to be a `4.3.0` release at the end), but we decided to do that years ago for all projects we maintain, so now it's kind of hard for us to change it.

Got you! If it's only a naming thing, it won't be an issue. Again Thanks!
