### ISSUE TITLE
Lag when writting in the console 

### ISSUE THREAD

**Issue by valentinayustym014** [spyder-ide/spyder#14599]
I have the new Mac book Air M1 processor.
I downloaded Anaconda 
Opened Spyder
Agreed on installing Kite 
And there is a 4 second lag every time I write on the console. 
I already updated the version and completed the instructions of common problems but it is still present. I need help.

**Comment by juanis2112** [comment]
Hi @valentinayustym014 thanks for reporting this. I think this might be a problem with the M1 processor. We have some problems with Anaconda and our latest Spyder version in Mac. I suggest downloading Spyder with our new installers that don't depend on Anaconda. You can find the installers in the "Download" section of our webpage https://www.spyder-ide.org

**Comment by juanis2112** [comment]
Closing for no response
