### ISSUE TITLE
KeyError('pandas._libs.interval') while opening a dataframe in variable explorer in dmg version of spyder

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#14603]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm getting KeyError('pandas._libs.interval') while opening a dataframe in the variable explorer. I'm using dmg version of spyder on an anaconda environment. I reinstalled both anaconda and spyder but didn't solve the issue.

* I opened this issue once and I was told I should wait for 4.2.2 to be released. I wanted to know when 4.2.2 will be released and whether I can downgrade anything to be able to use this again. It's weird because it was working fine few days ago before reinstalling my anaconda!

<img width="415" alt="104634735-449b5800-56b6-11eb-829e-b4c1a7ce8de8" src="https://user-images.githubusercontent.com/47456155/104816451-8819d180-5830-11eb-82a3-bcde60341b96.png">

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by b-a0** [comment]
Why open a new issue when you can comment on the [old one](https://github.com/spyder-ide/spyder/issues/14593)?

**Comment by ccordoba12** [comment]
Agreed, this doesn't make sense. @mhdmyz, please don't report this issue again.

**Comment by mhdmyz** [comment]
Sorry, the previous issue was closed and I was not sure you'll be address that if I comment on it after it has been closed.
