### ISSUE TITLE
Document Python workarounds in Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1460]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-26T02:32:18Z_

It will help for core Python development to have a separate page mentioning features of internal Spyder IDE source code, that are build as en enhancement or workarounds to core Python library.
- For example, pythonw.exe issues on Python 2
- Single instance locking
  ...

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1460_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-06-26T03:07:13Z_

* Detect if previous process that put a lock file is still running
    * Warn user if it is running
    * Auto clean up if there is nothing
    (tests: Linux, Windows, Mac OS)

**Status:** HelpNeeded

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T16:21:21Z_

**Status:** Accepted  
  **Labels:** -Type-Other Type-Enh MS-v2.4 Cat-Miscelleneous

**Comment by goanpeca** [comment]
The wiki already provides some info around this but this issue is too vague and has not received updates in a long time
