### ISSUE TITLE
Python 3.9 does not recognize sympy.

### ISSUE THREAD

**Issue by SaarHersonsky** [spyder-ide/spyder#14618]
### What steps will reproduce the problem?

Following the directions in the link 
https://github.com/spyder-ide/spyder/issues/14218#event-4014068160

And running Sypder from terminal I am getting:
import sympy
Traceback (most recent call last):

  File "<ipython-input-11-f3b5e8a7e105>", line 1, in <module>
    import sympy

ModuleNotFoundError: No module named 'sympy'

### Traceback
```python-traceback
  File "/Users/saarhersonsky/opt/anaconda3/envs/spyder-dev/lib/python3.9/site-packages/spyder/plugins/completion/snippets/actor.py", line 92, in handle_msg
    if language_snippets[current_word]:
  File "/Users/saarhersonsky/opt/anaconda3/envs/spyder-dev/lib/python3.9/site-packages/spyder/plugins/completion/snippets/trie.py", line 81, in __getitem__
    if len(sequence) == 0:
TypeError: object of type 'NoneType' has no len()
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.9.1
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.2.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=4.7.7               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  21.0.1 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by Dan-Patterson** [comment]
[Sympy's supported version](https://docs.sympy.org/latest/install.html) doesn't include python 3.9.  Perhaps that is the issue

**Comment by ccordoba12** [comment]
Hey @SaarHersonsky, thanks for reporting. I think the only way to use Spyder in Big Sur right now is by using [our installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg). So please download and install it, and let us know if things work for you (it comes with Sympy).

Unfortunately, people have reported mixed success with Conda/Conda-forge: for some it works and for other it doesn't.

**Comment by mrclary** [comment]
@SaarHersonsky , It looks like `sympy` is not installed on your system. Are you unable to install it? Otherwise I agree with @ccordoba12: try using our installer. I have confirmed that it works on macOS 11.1 and `sympy` imports from a Spyder terminal.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
