### ISSUE TITLE
Suggestion: provide Spyder on Chocolatey

### ISSUE THREAD

**Issue by ba-tno** [spyder-ide/spyder#14616]
This is not an issue but a suggestion for improvement (hence I've removed the issue template completely).

As the [releases](https://github.com/spyder-ide/spyder/releases) now include a standalone installer, is it possible to provide a [Chocolatey](https://chocolatey.org/) package for Spyder? [This page](https://chocolatey.org/courses/creating-chocolatey-packages/summary-rules-and-guidlines) has more information on the creation of chocolatey packages.

**Comment by ccordoba12** [comment]
Hey @ba-tno, thanks for the suggestion. Unfortunately, we don't have any experience with that package manager nor the time to create packages for it.

**Comment by fricpa** [comment]
Would be nice to also provide on WinGet.

**Comment by ccordoba12** [comment]
@fricpa, we're a small team with limited resources, so support for additional package managers will have to come from the community (like the flatpack packages provided on Linux).

As an alternative, you should try our standalone installers:

https://www.spyder-ide.org/download

They come with their own auto-update mechanism, so you only need to install them once and then accept to install the updates after each new version is released (which is roughly every six weeks).
