### ISSUE TITLE
View and Help application menus are not being display in master.

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#14612]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The View and Help application menus are not being display in master.

<img width="1280" alt="Screenshot 2021-01-18 at 4 37 55 PM" src="https://user-images.githubusercontent.com/18587879/104964939-86284d80-59ab-11eb-8187-cdcf8027cb83.png">

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: master
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
I confirm I'm not seeing this on Linux, so it seems to happen only on Mac.

**Comment by dalthviz** [comment]
Note: https://stackoverflow.com/questions/26004830/qt-change-application-qmenubar-contents-on-mac-os-x (seems like the menu needs to have at least one action to be visible)

**Comment by dnourie** [comment]
Yes this is exactly my issue. No View in the uppermost menu!

**Comment by ccordoba12** [comment]
@dnourie, `View` was renamed to `Window` in our 6.1.0 version.
