### ISSUE TITLE
Add variables to watches feature request

### ISSUE THREAD

**Issue by adriannick** [spyder-ide/spyder#14629]
Hello Spyder Team,

(Relatively new user of Spyder IDE here). Would it be possible to have a similar feature to the one of pycharm 'add to watches'? However, I'm guessing that having a sub-window within the variable explorer might make things somewhat more difficult. I was thinking about the following alternative options: in the right-click menu, to pin/stick the variable(s) at the top of the list in the variable explorer or maybe somehow enabling multiple variables/types search separated by semicolon. 

A short unrelated question. In the 'Outline' pane, there is an option 'Show special comments', but I could not find what is considered a special comment. 

Thank you!

**Comment by andfoy** [comment]
Hi @adriannick, thanks for opening this feature request, could you please elaborate more about this feature would work since we're not familiar with PyCharm? 

> A short unrelated question. In the 'Outline' pane, there is an option 'Show special comments', but I could not find what is considered a special comment.

Is it possible to know which version of Spyder are you using? Special comments are defined by `# ----`

**Comment by adriannick** [comment]
Sure. Basically they have a separate window in their version of variable explorer where you can add certain variables. The variables stay in this window until you remove them from there. It allows you the access them just as you would from the main variable explorer window.

I think is a useful feature to have if you debug a larger program that has many variables and you are interested in checking a specific few each time you rerun/debug it. Instead of searching for each one or individually printing them in the console, have them pinned at the top would make the checking process quicker. 

> Is it possible to know which version of Spyder are you using? Special comments are defined by # ----
I am using Spyder 4.2.0. Thanks, it works!

**Comment by andfoy** [comment]
@ccordoba12 what do you think about this one?

**Comment by ccordoba12** [comment]
It's an interesting suggestion, but instead of having a separate window, we could allow users to "pin" certain variables and exclude the others.

However, unless someone is willing to implement it (or fund us to do it), it's not going to happen anytime soon, sorry.

**Comment by adriannick** [comment]
Yes, I think pinning the variables at the top of the list would work just as well. 

Totally understandable and nothing to be sorry about. It was just a suggestion for future implementations. Thanks for considering it!

**Comment by ccordoba12** [comment]
This is already covered by the Spyder-watchlist plugin, which is described here:

https://www.spyder-ide.org/blog/introducing-watchlist-plugin/
