### ISSUE TITLE
F9 crashes the IPconsole while F5 works good

### ISSUE THREAD

**Issue by AlexStox** [spyder-ide/spyder#14620]
## Problem Description
After running the show() for a figure of pyplot, the IPython console executes the code, but then it freezes - the square in the top right corner is always red and a new line for a new command never appears. No issues or errors appear. 

If you run a script with F5, it will work fine in the IPconsole, but if you select the same code and run it with F9, it will give the above behavior! 

### What steps reproduce the problem?

1. Run the code from the Editor using F5 - everything should work properly
```
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 20 00:09:46 2021

@author: Aleks Ko
"""

import pandas as pd
import numpy as np
dates = pd.date_range('1/1/2000', freq = '3D', periods=8)

df = pd.DataFrame(np.random.randn(8, 4), index=dates, columns=['A', 'B', 'C', 'D'])

import webbrowser
mozilla_path="C:\\Program Files\\Mozilla Firefox\\firefox.exe"
webbrowser.register('firefox', None,webbrowser.BackgroundBrowser(mozilla_path))

import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = 'firefox'

df_p = df.reset_index()
df_p.rename(columns={'index':''}, inplace = True)

fig = go.Figure(data=[go.Table(
    header=dict(values=list(df_p.columns),
                fill_color='paleturquoise',
                align='left'),
    cells=dict(values=[df_p[col] for col in df_p.columns],
               fill_color='lavender',
               align='left'))
])

fig.show()
```

2. Select the code entire code in the Editor and Run it using F9 -> you'll get the output table in Firefox, but even if you close it and turn back to Spyder, the IPconsole will be in "busy" mode and with the red square in the top right corner.  

3. If you try to stop the console by clicking on that square, you won't receive a new line in the console - the only solution will be to close this console and create a new one. 

### What is the expected output? What do you see instead?
Expected output - the console is back to normal "non-busy" mode and the red square in the top right conrner becomes gray
Instead, I see the opposite - the console is busy and no new command line to work with the console

### Paste Traceback/Error Below (if applicable)

```python-traceback

  File "C:\Users\Public\anaconda\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'python' is not defined

```

## Versions

* Spyder version: 4.2.0
* Python version: 3.8.3
* Qt version: 5.12.1
* PyQt version: 5.12
* Operating System name/version: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.1.2.post20210110 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  None (NOK)

```

**Comment by ccordoba12** [comment]
Hey @aladdin-hub, thanks for reporting.

@impact27, could you give us a hand with this one? I remember you've helped us with similar issues in the past.

**Comment by ccordoba12** [comment]
Closing because this is quite old now. Hopefully you managed to solve this problem.
