### ISSUE TITLE
Kernel Dies unexpectedly

### ISSUE THREAD

**Issue by cub525** [spyder-ide/spyder#14627]
## Description
I'm running code with turtle, and was initially having problems with turtle, but now the kernel dies unexpectedly.

### What steps will reproduce the problem?
run [the code](https://github.com/tilaloz/fractals/blob/master/lsystem.py), and the kernel gives me this error **intermittently**:
```
Tcl_AsyncDelete: async handler deleted by the wrong thread

Kernel died, restarting


 
Tcl_AsyncDelete: async handler deleted by the wrong thread
[SpyderKernelApp] WARNING | No such comm: 119eef935b6a11eb9239c8348e03ce48
```
Everything appears to work fine afterwards, except for debugging, which won't respond to the debugging controls in the GUI, or the keyboard interrupt key at the top of the console pane:
![Shows the error if I attempt to use a keyboard interrupt](https://user-images.githubusercontent.com/49500036/105247599-4344b200-5b32-11eb-9807-0cfc6fbb3260.png)

## Versions

* Spyder version: 4.2.0 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.2.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.4 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
@cub525, thanks for reporting. Did you activate the Tk backend in our Preferences before running your code?

**Comment by cub525** [comment]
Changing the default backend under Preferences>IPython Console>Graphics Backend to automatic appears to have solved the problem, tk windows now behave expectedly, and although I'm not exactly sure what was causing the issue, so I will reopen if the issue reoccurs

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it @cub525!

**Comment by hshg64** [comment]
Changing the Graphic Backend to either of Inline or Automatic does not resolve the problem of restarting the kernel in my case.
The code was running without such a problem two days before. I was working on it by adding new parts.
It is around 1000 lines and uses more than 10 modules.

Any comment/idea?
