### ISSUE TITLE
Feature request: GPU Dashboards

### ISSUE THREAD

**Issue by dkinneyBU** [spyder-ide/spyder#14641]
There is a super-cool Jupyter Lab extension for GPU dashboards, that I find indispensable when developing neural networks. Spyder has some awesome panes (I could not live without the Variable explorer or the Terminal; two features that were the catalysts behind me abandoning both PyCharm and VS Code in favor of Spyder). So, just wanted to throw this out there: any chance you could incorporate this into Spyder, or facilitate some way to embed them?

https://github.com/rapidsai/jupyterlab-nvdashboard/blob/branch-0.5/demo/GPU%20Dashboard%20Demo.ipynb

I know, pie in the sky, but it doesn't hurt to ask. :-)

Keep up the good work--hope my monthly contribution helps the cause!

**Comment by ccordoba12** [comment]
Hey @dkinneyBU, thanks for the suggestion. Unfortunately, this is a bit out of the scope for Spyder. But for Spyder 5 (to be released in April) we'll have a new API for the entire application, which (hopefully) will interest people to create panes like this.

> Keep up the good work--hope my monthly contribution helps the cause!

Thanks for your contribution! We really value all the support our community give us to continue forward.

**Comment by dkinneyBU** [comment]
Fair enough, like I said, doesn't hurt to ask. :-)
