### ISSUE TITLE
File corrupted

### ISSUE THREAD

**Issue by jeneeshr47** [spyder-ide/spyder#14640]
I was running a .py file and it was corrupted when I was accidentally clicked a key, so it went empty but i didn't save it. Now it's still showing the same error even though I have downloaded the new file from the backup. Anyone know what we can do in this type of situation. If we mistakenly click any key and if it went empty what we need to do to undo it. Please someone suggest.

**Comment by ccordoba12** [comment]
Hey @jeneeshr47, thanks for reporting and sorry to hear that you had this problem with Spyder. You said:

> Now it's still showing the same error even though I have downloaded the new file from the backup

Unfortunately, if your backup file is showing the same problem, there's not much you can do to recover its previous contents. We offer autosave functionality to recover a file is Spyder crashes while you're working on it. But this doesn't seem to be the case, so Spyder can't help you to recover it.

Sorry for the bad news, but please let us know if we can help you with something else.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
