### ISSUE TITLE
kite start

### ISSUE THREAD

**Issue by Mathemilda** [spyder-ide/spyder#14644]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @Mathemilda,

Can you tell me if you got any error message in Spyder? And if so, what error did you had?

**Comment by Mathemilda** [comment]
There were no error message. At some point when my desktop was apparently using up a lot of resources, I looked up at my Task Manager and discovered Kite there as one of the most intense users. I was not using Spyder at the time, killed the process and checked if it is in my Startup Apps. It was not, and it was back on my Task Manager in a few minutes.  I came here and do not see the issue described yet, so I put it here. Then I went to Kite website and learned that a lot of people complain about excessive use of resources by the app, and the developer response is "we are working at improving it, although you can remove it if you do not like it". I removed and hope it won't create any problems.  Will it?

**Comment by steff456** [comment]
Kite is an independent completion tool from Spyder, but thanks for opening the issue. We can tell the kite devs about the high consumption problem so they can prioritize it. For now, if you uninstalled Kite, the problem should be gone and Spyder will use the PyLS completion engine. 

If you continue to have any problems related with Kite please reopen this issue.

**Comment by Mathemilda** [comment]
Thanks!
