### ISSUE TITLE
Spyder running natively on the M1 chip

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#14642]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Hi, Is there any ETA for Spyder running natively on the Apple M1 chip?

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @mhdmyz, thanks for reporting. This doesn't depend on us but on the Scientific Python ecosystem (to build our installers) or Anaconda/Conda-forge (to install it with conda).

I'd say that could take between three to six months (not really sure though). However, the most important thing to not lose performance with Rosetta2 is not that Spyder runs natively, but that Numpy, Pandas, Scikit-learn, Tensorflow, Pytorch, etc, are migrated to the M1 architecture. And most of them already are in Conda-forge (don't know about the pip packages).

**Comment by mhdmyz** [comment]
Thank you for your comprehensive reply Carlos! I know, I'm already running all my necessary modules like Numpy, Pandas, Scikit-learn etc. natively on the M1 thanks to python 3.9.1 and Conda-forge (miniforge) [I sent you a "Thank you!" email yesterday regarding this, not sure you read that]. I was asking specifically about the IDE (Spyder) running natively on the M1.

**Comment by mhdmyz** [comment]
> Hey @mhdmyz, thanks for reporting. This doesn't depend on us but on the Scientific Python ecosystem (to build our installers) or Anaconda/Conda-forge (to install it with conda).
> 
> I'd say that could take between three to six months (not really sure though). However, the most important thing to not lose performance with Rosetta2 is not that Spyder runs natively, but that Numpy, Pandas, Scikit-learn, Tensorflow, Pytorch, etc, are migrated to the M1 architecture. And most of them already are in Conda-forge (don't know about the pip packages).

Thank you for your comprehensive reply Carlos! I know, I'm already running all my necessary modules like Numpy, Pandas, Scikit-learn etc. natively on the M1 thanks to python 3.9.1 and Conda-forge (miniforge) [I sent you a "Thank you!" email yesterday regarding this, not sure you read that]. I was asking specifically about the IDE (Spyder) running natively on the M1.

**Comment by mhdmyz** [comment]
> This doesn't depend on us but on the Scientific Python ecosystem (to build our installers)

Aren't you supposed to build your own installer (dmg installer) running natively on the M1? 🤔

**Comment by ccordoba12** [comment]
>  [I sent you a "Thank you!" email yesterday regarding this, not sure you read that]

Thanks! I read it but I haven't had time to answer it, sorry.

> Aren't you supposed to build your own installer

We create the installer, yes, but we don't build the packages that come with it, i.e. we don't build PyQt, Numpy, Pandas, etc from its sources. We simply install them with pip in a Python version that we then package into a Mac native application using `py2app`.

When/if those libraries provide universal wheels (i.e. pip packages that can run on Intel and M1 chips), then our application will run natively on M1.

**Comment by mhdmyz** [comment]
> > [I sent you a "Thank you!" email yesterday regarding this, not sure you read that]
> 
> Thanks! I read it but I haven't had time to answer it, sorry.
> 
> > Aren't you supposed to build your own installer
> 
> We create the installer, yes, but we don't build the packages that come with it, i.e. we don't build PyQt, Numpy, Pandas, etc from its sources. We simply install them with pip in a Python version that we then package into a Mac native application using `py2app`.
> 
> When/if those libraries provide universal wheels (i.e. pip packages that can run on Intel and M1 chips), then our application will run natively on M1.

Got you! thanks!

**Comment by mhdmyz** [comment]
I'm using a miniforge environment which runs natively on M1 and I've connected my Spyder IDE to this environment but the Spyder dmg itself runs on Intel! Can you develop a version of Spyder which runs natively on M1?

<img width="725" alt="Screen Shot 1400-01-14 at 20 47 02" src="https://user-images.githubusercontent.com/47456155/113484482-c2088480-94bd-11eb-9934-3ebf972e6626.png">

**Comment by ccordoba12** [comment]
Sorry but that's not something that really depend on us. As i mentioned above, Spyder is composed of a lot of different packages and not all of them are ported to M1 yet. In particular, we use PÿQt5 as the graphical library to build Spyder and there are no M1 binaries for it.

So until there is a M1 package for it (and all our other binary dependencies), we won't be able to provide an M1 compatible installer for Spyder, sorry.

**Comment by mhdmyz** [comment]
Hi. Any news on this?
I have a python environment (miniforge) which runs completely natively on the M1 chip. Now the problem is only my IDE (Spyder), which still can't run natively on the Apple Silicon!

**Comment by ccordoba12** [comment]
Hopefully, it'll be available in the next months in conda-forge. We're working on that right now.

**Comment by vwxyzjn** [comment]
Hello, it seems pyqt5 is already available for the M1 chip: https://formulae.brew.sh/formula/pyqt@5; would this help?

**Comment by ccordoba12** [comment]
Only if you install Spyder with Homebrew.

**Comment by vwxyzjn** [comment]
Sorry quick follow up question for this @ccordoba12 , so if I install spyder via homebrew today, do I just get the native spyder? Or are there more tweaks I need to do?

**Comment by ccordoba12** [comment]
Yeah, the main interface will be running natively. But I don't think all our binary dependencies have universal wheels yet (i.e. pyzmq, rtree, watchdog, etc).

**Comment by vwxyzjn** [comment]
Cool will try it out thanks!

**Comment by mhdmyz** [comment]
> Only if you install Spyder with Homebrew.

I installed Spyder using Homebrew today, but it's still running on Intel! (Not natively on the Apple Silicon)

**Comment by duaghk** [comment]
> > Only if you install Spyder with Homebrew.
> 
> I installed Spyder using Homebrew today, but it's still running on Intel! (Not natively on the Apple Silicon)

hi. How about to install spyder using pip? (using native python, not brew python)
python3 -m pip install Spyder

**Comment by mhdmyz** [comment]
> > > Only if you install Spyder with Homebrew.
> > 
> > 
> > I installed Spyder using Homebrew today, but it's still running on Intel! (Not natively on the Apple Silicon)
> 
> hi. How about to install spyder using pip? (using native python, not brew python)
> python3 -m pip install Spyder

As I guessed it didn't work!

**Comment by mhdmyz** [comment]
> Only if you install Spyder with Homebrew.

Did you try it yourself?

**Comment by duaghk** [comment]
> > Only if you install Spyder with Homebrew.
> 
> Did you try it yourself?

Sorry, I didn't. 
But I use Spyder via python install(intel)

so, I think it would work, but not.

I apologize about that.

**Comment by mhdmyz** [comment]
> Only if you install Spyder with Homebrew.

It's not as you said! Did you try it yourself?

**Comment by srajanseth84** [comment]
> Hopefully, it'll be available in the next months in conda-forge. We're working on that right now.

How much more we have to wait for native spyder?
It's almost a month

**Comment by stanislasgrare** [comment]
From what I understand the main issue is that PyQt is not M1 native. I am using PyQt and I am desperately waiting for the M1 native. I think PyQt6 will be native when Qt 6.2 is released (version 6.2 contains M1 binaries). From their website, the final version of Qt 6.2 will be released at the end of september if everything goes well. I guess PyQt6 will be available soon after. Spyder is based on PyQt5 right?. I don't know when M1 binaries are available for Qt5.

I am not an expert and I might totally wrong by the way.

**Comment by silveira-lucas** [comment]
I installed the native version of python3 through miniforge (Apple version) and Spyder (Intel version) through homebrew and everything is working just fine for me with one exception, I've observed one strange behaviour when setting the "graphics backend" option to "automatic" instead of "inline".

When I start Spyder with the "inline" option and switch to "automatic", the opened kernels function just as expected. However, if I open new consoles they don't work at all. The issue also persists after restarting Spyder. The only way I manage to plot graphics in a separate window is to start Spyder with IPython console "graphics backend" set to "inline" and then change it to "automatic".

If I run python3 through terminal, plotting graphics works just fine as well.

My installation commands were:

brew install --cask miniforge
conda init zsh
conda activate
brew install --cask spyder
brew install PyQt@5
pip3 install matplotlib

**Comment by mhdmyz** [comment]
> Hopefully, it'll be available in the next months in conda-forge. We're working on that right now.

@ccordoba12 any news on this? 7 months have passed since then!

**Comment by ccordoba12** [comment]
One of our developers is working on it. It could take a couple of months more to finish it.

**Comment by drbz-zhou** [comment]
@mhdmyz could you give some pointers how you connected the Spyder IDE to an native Python environment? I have the M1 native python and Tensorflow-metal environment set up and it's working with Jupyter notebook (following the instructions from [jeffheaton](https://github.com/jeffheaton)). But I'd like to be able to use Spyder even if it's running on Rosetta as long as the ipython console is using a native python interpreter. I tried in the environment
conda install spyder‑kernels=2.1
as recommended by Spyder's prompt, but it couldn't find the package in the set channels
  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
I'm hesitant to add more channels because the others might not yet be native.
I tried 
conda install -c conda-forge spyder-kernels=2.1
but it's finding a lot of conflicts.

**Comment by ccordoba12** [comment]
This is available in Conda-forge now.

**Comment by AminDar** [comment]
> This is available in Conda-forge now.

using  `conda install -c conda-forge spyder ` gives me the following error on M1:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spyder -> python[version='2.7|>=3.4|>=3.6|>=3.11,<3.12.0a0|>=3.11,<3.12.0a0|>=3.5|>=3.7|>=3|>=3.7.2|>=3.6.2|>=3.6.2,<4|>=3.6,<4|3.10.*|>=3.8|>=2.7|3.9.*|3.8.*',build=*_cpython]
  - spyder -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.8,<3.9.0a0',build=*_cpython]

Your python: defaults/osx-arm64::python==3.9.13=hbdb9e5c_1

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==12.6=0
  - feature:/osx-arm64::__unix==0=0
  - feature:|@/osx-arm64::__osx==12.6=0
  - spyder -> applaunchservices[version='>=0.3.0'] -> __osx
  - spyder -> spyder-kernels[version='>=2.4.0,<2.5.0'] -> __unix
  - spyder -> spyder-kernels[version='>=2.4.0,<2.5.0'] -> __win

Your installed version is: 0

Note that strict channel priority may have removed packages required for satisfiability.

```
p.s: on conda 22.9.0

**Comment by ccordoba12** [comment]
@AminDar, Spyder is not available yet for Python 3.11, which is the version you seem to have in your environment. If that's the case, I'd also like to remark that we don't know when Spyder packages for 3.11 will be uploaded to conda-forge.

**Comment by mhdmyz** [comment]
Hi, any news on this? Years just passed!

**Comment by ccordoba12** [comment]
This is already possible since at least six months ago. Just install Spyder with Conda-forge and you'll get native support for M1/M2 chips.

**Comment by mhdmyz** [comment]
Thanks! Just found it right now!

**Comment by iamjingxian** [comment]
> mhdmyz

Hi! i tried installing spyder using conda-forge in an environment that was set up for tensorflow and got the following error, and I'm wondering if you had previously also encountered, and managed to resolve it?

Appreciate you help on this! (ps, added you on twitter!) 

The following packages are causing the inconsistency:

  - conda-forge/osx-arm64::shap==0.41.0=py39hd2dba81_0
  - conda-forge/osx-arm64::xgboost==1.7.4=cpu_py39h2fb42d7_0
  - conda-forge/osx-arm64::lightgbm==3.3.5=py39h7dbb43e_0
  - conda-forge/noarch::pyro-ppl==1.8.4=pyhd8ed1ab_0
  - conda-forge/osx-arm64::py-xgboost==1.7.4=cpu_py39h6861412_0
  - conda-forge/noarch::forestci==0.6=pyha21a80b_0
  - conda-forge/osx-arm64::causalml==0.13.0=py39h4d8bf0d_0

I created my tensorflow environment using the instructions here, which allows tensorflow to tap on the GPU. 

"How to Install TensorFlow GPU for Mac M1/M2 with Conda" at https://youtu.be/5DgWvU0p2bk
