### ISSUE TITLE
Feature request: dynamically update "inline" matplotlib figures

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#14658]
Currently, with "inline" graphing, there seems to be no way of dynamically updating an individual figure (to create a live animation for instance).

**Comment by ccordoba12** [comment]
Hey @ma-sadeghi, thanks for reporting. Unfortunately, the figures generated by the Inline backend are static PNG images, so it's not possible to generate animations with them or update them dynamically, sorry.

**Comment by ma-sadeghi** [comment]
Thanks @ccordoba12 for getting back to me. Quick question: is this something that in principle could be implemented in Spyder? (such that inline plots in the Plots pane are interactive) I'm asking since, if I recall correctly, this can be done in Atom.

**Comment by ccordoba12** [comment]
> Quick question: is this something that in principle could be implemented in Spyder?

Yes, but not for the Plots pane. We need to add a new pane to render web content that comes from evaluating content in the console, and tell users they need to switch to the web Matplotlib backend to see animations.

We're planning to do that for Spyder 6, to be released next year.

> I'm asking since, if I recall correctly, this can be done in Atom.

Atom is based on web technologies, so probably they are using the web backend and not the inline one.

**Comment by ma-sadeghi** [comment]
@ccordoba12 Many thanks for your thorough response, looking forward to Spyder v6 👍

**Comment by ccordoba12** [comment]
Great, thanks for understanding.

**Comment by SergeiDBykov** [comment]
@ccordoba12 
Hi! I reckon that until spyder 6 is out it would be great to add a button (and a short-cut) for fit/unfit figure to the current plot pane.
Suppose one needs to zoom into a particular part of a plot. But After switching to another plot, the zoom stays the same. I think this is not very handy. 

Currently it is done via a small toggle on the top left of a plot pano, but I think it would be much better if it were a shortcut AND a button in the proximity of zooming buttons.
