### ISSUE TITLE
FileNotFoundError when opening or saving files in network drives

### ISSUE THREAD

**Issue by sound-fx** [spyder-ide/spyder#14660]
### What steps will reproduce the problem?

I don't know how to reproduce. I'd just opened a script and and clicked the Debug button Spyder's toolbar. It took about 10 seconds to respond with this error.

### Traceback
```python-traceback
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\ntpath.py", line 647, in realpath
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 53] The network path was not found: '\\\\kraken\\buildbot\\built_executables\\assemble_distributables.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 388, in <lambda>
    self.main.editor.load(fname, lineno, word,
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2016, in load
    current_editor = self.set_current_filename(filename,
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\site-packages\spyder\plugins\editor\plugin.py", line 1552, in set_current_filename
    return editorstack.set_current_filename(filename, focus)
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1665, in set_current_filename
    index = self.has_filename(filename)
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1659, in has_filename
    if fixpath(filename) == fixpath(finfo.filename):
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\site-packages\spyder\plugins\editor\widgets\editor.py", line 1657, in <lambda>
    fixpath = lambda path: osp.normcase(osp.realpath(path))
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\ntpath.py", line 651, in realpath
    path = _getfinalpathname_nonstrict(path)
  File "C:\Users\greg\Anaconda3\envs\nwra3\lib\ntpath.py", line 601, in _getfinalpathname_nonstrict
    path = _getfinalpathname(path)
FileNotFoundError: [WinError 53] The network path was not found: '\\\\kraken\\buildbot\\built_executables\\assemble_distributables.py'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by andfoy** [comment]
Hi @sound-fx, thanks for opening this issue, have you tried updating to the latest version of Spyder to see if the error still occurs?

**Comment by sound-fx** [comment]
On my Windows 10 machine, Spyder 4.1.5 is installed as part of Anaconda 2020.11.  In the past, I've never had success upgrading Spyder after installing a distribution of anaconda.  Something like
`conda install spyder=4.2`
typically finds many conflicts and eventually gives up after hours of trying. Instead, I usually wait for a new anaconda distribution.
How do other people get around this?  Is the trick to switch to miniconda?

**Comment by andfoy** [comment]
@sound-fx, we now provide native Windows installers to prevent these errors, you can find them on the Releases page of Spyder: https://github.com/spyder-ide/spyder/releases/tag/v4.2.1

**Comment by sound-fx** [comment]
Thank you for that. I'm now running 4.2.1.
As I don't know how to reproduce the issue even with 4.1.5, we'll just have to wait to see whether it recurs on its own with 4.2.1.  If so, I'll submit the report.

**Comment by ccordoba12** [comment]
@sound-fx, I think the problem is that you're trying to open a file in a network drive, at least according to the last line of your error:

```python-traceback
FileNotFoundError: [WinError 53] The network path was not found: '\\\\kraken\\buildbot\\built_executables\\assemble_distributables.py'
```

Could you try again to open that file and let us know if the error persists in 4.2.1?

**Comment by ccordoba12** [comment]
@dalthviz, this seems to be a Windows error. Any ideas about it?

**Comment by dalthviz** [comment]
Seems like the network mount was disconnected while trying to be accessed in debugging mode (the signal `edit_goto` is triggered for every frame where the debugger stops) which causes the IPython Console to trigger the Editor to load a file that is not accessible at the moment (is in a network dir which could be not available).

@sound-fx all your code is in the network dir? the connection to that network dir is unstable in some way? Maybe a way to reproduce this is entering in debug mode, disconnecting your network dir associated with the code you're running and trying to go to the next step with the debugger. Any new info is greatly appreciated :)

**Comment by sound-fx** [comment]
Sorry for the slow follow-up.

At @dalthviz 's suggestion, I was able to able to reproduce the problem in Spyder v. 4.1.5:
1. Start that script (that resides on a network drive) in debug mode.
2. After hitting a breakpoint, disconnect from the network.  
3. Upon clicking the Run Current Line button on the toolbar (to advance the debugger to the next line), Spyder displays the error message that the file could not be found and offers to either close the file or keep it open.
4. Clicking to keep the file open, Spyder shows the exception dialog with the traceback and the option to report the error.

Following those same steps using Spyder v. 4.2.1, I confirm that everything works as expected.  Steps 1 - 3 seem to behave the same in both 4.1.5 and 4.2.1, but in Step 4 (clicking to keep the file open) quietly leaves the file open, with no further error dialog, so no offer to send the traceback along with details.

Thank you for the suggestions and for the great software!

**Comment by miklos-zoldi** [comment]
Hi! I have a very similar issue now with the latest Spyder version v5.1.5. 

I open a new script in Spyder editor and then go to File -> Save as... to save my file. I can save it onto my local drive normally. However, if I select a mapped network drive a network error occurs (see attached image below). 

Spyder can reach the network drive - I can load a text file from there, read its content, modify it, and then save it with another name, the only thing which throws an error if I try to _save the script itself via Save as._ Interestingly, saving without using the Save as function (i.e., modifying a script loaded into Spyder from the network drive, and then simply running it or saving it via ctrl+s) also works. So a simple workaround would be just not using the Save as function but renaming my scripts simply via Windows' File Explorer. However, I often get the very same error message if I just try to _drag and drop a script from the network drive to Spyder's editor_. Unfortunately this does not happen always, so I cannot reproduce. Hence, the only workaround for me is to copy my scripts to my local drive and work there, and then copy the files back to my mapped network drive when finished working. Do you have any better idea? 

![Spyder](https://user-images.githubusercontent.com/33951282/163044774-5c8c7baa-0f08-4c62-8bce-a4fd81c02ce5.JPG)

**Comment by miklos-zoldi** [comment]
hi @dalthviz , thanks for suggestions! I tired the 5.3.0 version in a new environment, but the error message still persists. 
I already have Spyder as part of Anaconda, so I would not install a standalone version. Do you think it would make any difference?

**Comment by dalthviz** [comment]
Oh I see @miklos-zoldi then could you open a new issue with all your setup details and traceback to check again this please? Thanks!

**Comment by miklos-zoldi** [comment]
Hi Daniel,

I reported the issue o Github just now, I was out of town for a bit, hence
the delay.

Thank you guys for your help!
Miklos

Daniel Althviz Moré ***@***.***> ezt írta (időpont: 2022.
ápr. 15., P, 12:09):
