### ISSUE TITLE
There's a blank space in the menus in the top in macOS

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#14661]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In the current master, when navigating through the menus a blank entry is shown

![image](https://user-images.githubusercontent.com/20992645/106196494-7cf36980-617f-11eb-91a8-765eab6ce1a5.png)

![image](https://user-images.githubusercontent.com/20992645/106196514-8250b400-617f-11eb-9a28-f910f837ae75.png)

**Comment by dalthviz** [comment]
Maybe this is being caused by the changes in PR #14619 . Probably the space is the initial 'empty' action to enable the addition of the menu to the `menuBar` on Mac since the menus are populated dynamically in the `aboutToShow` signal

**Comment by dalthviz** [comment]
Seems like this happens only for non-migrated menus (currently only `Views` and `Help` are migrated).

@ccordoba12 should I add handling for non-migrated and migrated menus to prevent this (basically some kind of flag when creating the menu to indicate if the initial action is needed or not) or just wait to have all the menus migrated?

**Comment by ccordoba12** [comment]
> should I add handling for non-migrated and migrated menus to prevent this (basically some kind of flag when creating the menu to indicate if the initial action is needed or not)

Yes, please do that so we can have a uniform look and feel for menus until all of them are migrated.
