### ISSUE TITLE
Change the style of pushed QActions in the new API

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#14662]
## Problem Description
With the refactoring of the new API, we are changing all the QPushButtons to QActions, which makes a difference in our UI as seen in the following examples,

**Migrated plugins**
![image](https://user-images.githubusercontent.com/20992645/106206093-85eb3780-618d-11eb-9be1-6f130449381b.png)

![image](https://user-images.githubusercontent.com/20992645/106206165-9e5b5200-618d-11eb-8996-644ffcb8db22.png)

**4.x**
![image](https://user-images.githubusercontent.com/20992645/106206131-93a0bd00-618d-11eb-9930-b0c874ae0059.png)

![image](https://user-images.githubusercontent.com/20992645/106206186-a5826000-618d-11eb-849a-ea3bc7da4971.png)

Once all the plugins are migrated we need to change the state of the pushed QAction colors given our decisions with the new palette and style.

**Comment by ccordoba12** [comment]
@isabela-pf, what do you think about our current style? I mean, the blue border around the button to signify that it's pushed?

Do you think we could use a different style?

**Comment by juanis2112** [comment]
I think we are already considering this problem in this issue https://github.com/spyder-ide/ux-improvements/issues/28. I think it will most likely be the same as the activated state color of the buttons in the toolbar unless we want different behaviours for the pane toolbars

**Comment by ccordoba12** [comment]
I think you're right @juanis2112, and I haven't thought about it. Pushed buttons are like continously pressed or activated ones, so we don't need to distinguish them with a different style.

So this issue will be basically solved when you implement those changes (it's pretty close to that now, actually).

**Comment by isabela-pf** [comment]
I think this issue might be resolved/can be closed? Can anyone confirm?

**Comment by ccordoba12** [comment]
You're totally right @isabela-pf! One less issue to worry about in our backlog!

This was solved in QDarkstyle 3.0.
