### ISSUE TITLE
url too long, spyder 3.2.6

### ISSUE THREAD

**Issue by pakair** [spyder-ide/spyder#14668]
## Problem Description

1. I clicked on preferences, then keyboard shortcuts and got a window popup with title, error. 
2. Clicked on Submit to Github, I get URL too long on my browser (FF 85.0)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):

this error repeats many many times hence the URL too long error.
```

## Versions

* Spyder version: 3.2.6
* Python version:  3.6.9
* Qt version: 
* PyQt version: 
* Operating System name/version: Linux Mint MATE 19.3 (kernel 5.4.0-65-generic)

**Comment by juanis2112** [comment]
Hi @pakair. This was fixed in spyder 4 please update to our latest version.
From your comand line run:
```
conda update anaconda
conda update spyder
```

**Comment by pakair** [comment]
Thank you for your reply. I do not have conda installed. 
I installed spyder3 just with "sudo apt install spyder3" which brought in 3.2.6

**Comment by juanis2112** [comment]
I think the solution is then to create a virtualenv and install spyder 4 with pip. Please check the "Using Pip" section of our Installation Guide https://docs.spyder-ide.org/current/installation.html#using-pip
Warning: Please don't do `sudo pip install spyder` because you can break your environment.

**Comment by pakair** [comment]
I followed the guide you provided and was able to install spyder 4.2.1 in its own virtualenv but I saw errors (line 314 and further) during the install. Here's the log of the install, [https://l.termbin.com/g21b](https://l.termbin.com/g21b) 
Maybe you can tell me if I can fix those errors. Thank you.

**Comment by ccordoba12** [comment]
@pakair, please run in your virtualenv

    pip install wheel

then try again. That should fix the errors you're seeing.

**Comment by pakair** [comment]
When you say, "try again" should I remove the (spyder-env) completely and use the same commands I used before?  

python3 -m venv spyder-env   
source spyder-env/bin/activate   
pip install wheel
pip install spyder

**Comment by ccordoba12** [comment]
Yeah, that's correct.

**Comment by pakair** [comment]
thank you ... install was good, no errors. I'll close this ticket.
