### ISSUE TITLE
No module named 'netCDF4'

### ISSUE THREAD

**Issue by AP25-stack** [spyder-ide/spyder#14676]
### What steps will reproduce the problem?

Install netCDF4 via Anaconda (or miniconda) prompt or the command line. Then type import netCDF4 in Spyder. There are many complaints on StackOverflow and other websites about this problem. However, there do not seem to be any feasible solutions.

## Versions

* Spyder version: 4.2.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.5.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.3 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0 (OK)
sphinx >=0.6.6                  :  3.3.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.4 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by AP25-stack** [comment]
I have installed all the recommended packages and Spyder still refuses to recognise netCDF4. The error message is ModuleNotFoundError: No module named 'netCDF4'.

**Comment by steff456** [comment]
Hi @AP25-stack,

Did you install `netCDF4` in the same environment where you installed Spyder? If you installed it in other environment you can connect to it in `Preferences > Python Interpreter > Python Interpreter > Use the following Python Interpreter` and select in the dropdown the env where you installed the package. Please take into account that you'll need to install `spyder-kernels` in that environment for it to connect to the console and use it in the console.

Let me know if this works for you :)

**Comment by Dan-Patterson** [comment]
The only issues on StackOverflow seem to be 27 days old or more and seem to revolve around confusion on package installation and environments and have nothing to do with Spyder
[issue 1](https://stackoverflow.com/questions/65593971/module-installed-in-anaconda-same-interpreter-with-spyder-yet-spyder-gets-modu)

**Comment by mikki64** [comment]
I've encountered the same issue: 

Tried new clean installs to Win10 of the full 64- and 32-bit Anaconda packages (downloaded 12May2021), then used 'conda install netcdf4' in both regular Anaconda prompt and PowerShell: shows-up in Navigator as being installed, but get a 'no such library' message in Spyder. 

Also tried installing netcdf4 through Navigator, but seems not to succeed ('multiple errors').

Thanks for looking at this!

**Comment by mikki64** [comment]
Hah - import netCDF4 does work, however!
Oops.

**Comment by steff456** [comment]
Hi @mikki64, I'm glad you could resolve this issue! @AP25-stack does this fixes your error too?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
