### ISSUE TITLE
Different plot results in Spyder and Jupyter vs. Eclipse/PyDev, Visual Studio, & VS Code

### ISSUE THREAD

**Issue by biomathematicus** [spyder-ide/spyder#14672]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am a newbie to Spyder, but not to scientific computing. Thanks you for a great piece of software, and I hope this is a meaningful contribution. My apologies if I am missing something trivial, but I noticed this on day 1 of giving Spyder a test ride.  For the purpose of referencing functions below, I first import matplotlib.pyplot as plt

The problem is that when plotting multiple times inside a for loop, the use of plt.pause creates a divergent behavior in {Spyder,Jupyter} vs {PyDev,Visual Studio,VS Code}. See code below in steps for reproducing the issue. 

Within a for loop, plt.pause creates a new figure for every iteration with plt.plot and creates a single figure with plt.scatter instead of updating the existing figure. I found this unexpected and contrary to what other python IDEs such as PyDev, Visual Studio, VS Code as well as other computing platforms such as Matlab, RStudio, Octave, Scilab using comparable code. 

### What steps reproduce the problem?

``` python

import numpy as np
import matplotlib.pyplot as plt

l = np.pi; # or any other length... pi simply make results intuitive
x = np.linspace(0, l, 100) # 100 points in the interval [0,l]
m = 3 #number of frequencies
q = np.linspace(1,m,m)

#Same result in {Spyder,Jupyter} vs {PyDev,Visual Studio,VS Code}
fig = plt.figure(1)
for n in q:
    y = np.sin(n * np.pi * x / l) 
    #plt.pause(0.001)
    plt.plot(x, y)
plt.show()

#Same result in {Spyder,Jupyter} vs {PyDev,Visual Studio,VS Code}
fig = plt.figure(2)
ax = fig.gca()
for n in q:
    y = np.sin(n * np.pi * x / l) 
    ax.scatter(x, y)
    #plt.pause(0.001)
    plt.draw()
plt.show()

#Different result in {Spyder,Jupyter} vs {PyDev,Visual Studio,VS Code}
fig = plt.figure(3)
for n in q:
    y = np.sin(n * np.pi * x / l) 
    plt.pause(0.001)
    plt.plot(x, y)
plt.show()

#Different result in {Spyder,Jupyter} vs {PyDev,Visual Studio,VS Code}
fig = plt.figure(4)
ax = fig.gca()
for n in q:
    y = np.sin(n * np.pi * x / l) 
    ax.scatter(x, y)
    plt.pause(0.001)
    plt.draw()
plt.show()

```

### What is the expected output? 

Expected and obtained in Spyder/Jupyter when plt.pause is not used. This result is also obtained irrespective of the  use of plt.pause in PyDev, Visual Studio, VS Code: 
With plt.plot: 
![image](https://user-images.githubusercontent.com/22688130/106394343-ccc17300-63c1-11eb-8f27-26823587c627.png)

with plt.scatter:
![image](https://user-images.githubusercontent.com/22688130/106394350-d2b75400-63c1-11eb-9173-7c22f3f0b7f5.png)

### What do you see instead?

Obtained when plt.pause is in the for loop in Spyder and Jupyter: 
With plt.plot: 
![image](https://user-images.githubusercontent.com/22688130/106394356-e367ca00-63c1-11eb-8abb-520a42a105a4.png)

with plt.scatter:
![image](https://user-images.githubusercontent.com/22688130/106394369-e8c51480-63c1-11eb-9e91-e5b4fe06e257.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by biomathematicus** [comment]
PS. It might be worthwhile to mention that I ran yesterday 
```
conda update --all
```
I just ran now
```
conda update anaconda
conda install spyder=4.2.0
```
Incidentally, in VS Code, I have to use 
```
import matplotlib
matplotlib.use('TKAgg')
```
otherwise, I run into issue #13687. You'd think it is a VS Code problem, except that it also happens when I used the Spyder installer for version 4.2.1. All this information is simply to convey that I have tried multiple versions, I have updated all, I uninstalled and installed again. 

The result is the same.

**Comment by steff456** [comment]
Hi @biomathematicus,

Right now Spyder uses the same backend as Jupyter for plotting, we can investigate why this is happening but it is highly probable that the fix has to be done in Jupyter. Can you please open the same issue in their repo so they can investigate as well?

**Comment by biomathematicus** [comment]
@steff456 Thank you for your response. 

I have reported the issue in JupyterLab here: https://github.com/jupyterlab/jupyterlab/issues/9720

**Comment by ccordoba12** [comment]
@biomathematicus, I tested this and I think your use case doesn't work with the Inline Matplotlib backend (which is the one that generate the static png's we display in the Plots pane).

To change that backend to one that works, please go to the menu:

    Tools > Preferences

Then select

    IPython console > Graphics > Backend

and change it from `Inline` (the default) to `Automatic`. The please restart the console's kernel by going to the menu

    Consoles > Restart kernel

or close and start Spyder again.

After that, things should work as expected.

**Comment by biomathematicus** [comment]
@ccordoba12   Thanks a lot!  You rock. 

I see now that I was searching with the wrong keywords.   This was a newbie's mistake.  I was intuitively expecting functionality like Matlab's.  But I learned a lot about Spyder during this exercise. Apologies for taking your time.

This has been addresses before at:  https://stackoverflow.com/questions/23585126/how-do-i-get-interactive-plots-again-in-spyder-ipython-matplotlib

**Comment by ccordoba12** [comment]
No problem, I'm glad that things are working for you now. And yeah Python/Spyder are close Matlab, but things are usually more complicated in this side of the world.
