### ISSUE TITLE
pyqt5 and pyqtwebengine - allow >= 5.13?

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#14697]
Hi there!
`setup.py` specifies `pyqt5<5.13` and `pyqtwebengine<5.13`. But version 5.13.0 was released in July 2019 and the current version is 5.15.2.  As far as I can tell, Spyder seems to be working OK with the current version of these packages (which is what is available in Debian testing, and the soon-to-be released Debian stable).  I wonder if the issues which led to the version restriction have been addressed, and if so, could the version restriction be relaxed?

Best wishes, Julian

**Comment by ccordoba12** [comment]
This has been asked several times in the past and it's on our TODO list. Unfortunately, some of our tests fail with PyQt 5.15 and we haven't had time to fix them.

Besides, there's not a big incentive for us to spend time on this given than Anaconda is on PyQt 5.9 and Conda-forge on 5.12, sorry.

However, you're welcome to help us fixing our tests here on Github with that version.

**Comment by juliangilbey** [comment]
Thanks; that makes sense! I don't know enough about how PyQt works to stand much chance of helping fix this, though :-(

**Comment by ccordoba12** [comment]
Ok, no problem. Closing then.
