### ISSUE TITLE
Second row of tabs [request]

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#14691]
Rarely do I need to immediately know the full path of a tab's file, as I can hover:

![image](https://user-images.githubusercontent.com/16495490/106892208-2c42ba00-6705-11eb-84c4-08ad94e092ff.png)

What I do need plenty of, is tab space. It's not simply two clicks away, it's two clicks _and skimming a dropdown_ away. Not a huge deal, but I'd appreciate it as a QoL addition.

![image](https://user-images.githubusercontent.com/16495490/106892795-079b1200-6706-11eb-9148-0ab9e482b029.png)

**Comment by Dan-Patterson** [comment]
even dropping the `.py` from the filename would possibly squeak in a tab or two

**Comment by OverLordGoldDragon** [comment]
@Dan-Patterson Agreed, not like I use Spyder for anything other than `.py` anyway

**Comment by andfoy** [comment]
@OverLordGoldDragon, have you tried using the outline explorer to navigate across all the files?

**Comment by OverLordGoldDragon** [comment]
@andfoy If you refer to below, sure, but it's fairly less convenient than seeing all tabs at once. I'm not necessarily aware of their order so need to skim the entire list - not horrible, but can be better. (also cluttered with full filepaths)

![image](https://user-images.githubusercontent.com/16495490/107071541-444a3480-67fe-11eb-9328-be6c6b1dc37b.png)

**Comment by andfoy** [comment]
I was referring to the outline explorer pane, (leftmost panel on the image). You can find it under View → Panes → Outline Explorer, there you can select the option `Show all files` to get a list of all the files opened

![imagen](https://user-images.githubusercontent.com/1878982/107080121-d2062f80-67be-11eb-87cf-0cab584d3579.png)

**Comment by andfoy** [comment]
@isabela-pf @ccordoba12, we might need to consider this issue for the upcoming UX improvements

**Comment by OverLordGoldDragon** [comment]
That's effectively a permanent dropdown, which is fine for those who already dedicated the window, but to me it's an extra window, which is overkill.

**Comment by ccordoba12** [comment]
This has been requested several times, but I'm still unsure if we should do something about it. We'll discuss it with the team and come back to you.

**Comment by OverLordGoldDragon** [comment]
@ccordoba12 If this is troublesome I'd settle for dropping the `.py`; after some getting used to, the existing dropdown option has become acceptable. What'd also save lots space is an option to drop the "x" (can still Ctrl + W or right-click), or only show it when hovering over the tab:

![image](https://user-images.githubusercontent.com/16495490/110362352-9dee8a80-805a-11eb-85fa-ed3452deb034.png)

Significant shortening.

**Comment by ccordoba12** [comment]
> @ccordoba12 If this is troublesome I'd settle for dropping the .py

Not all files end in `.py`.

> after some getting used to, the existing dropdown option has become acceptable

Yeah, I think your proposal is a good idea and we'll try to implement it in the future. However, it's not so easy as it sounds.

**Comment by OverLordGoldDragon** [comment]
> Not all files end in `.py`.

Right but I imagine most of us work almost exclusively with `.py`, so every other extension could be kept - and worst case, `.py` can be kept via Preferences. I understand if making it optional is somehow difficult - just noting.

**Comment by OverLordGoldDragon** [comment]
Fully used to `Ctrl + P` at this point, others are free to reopen if they wish.
