### ISSUE TITLE
Spyder.ttf font has print and preview only restrictions

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#14701]
Spyder is kindly licensed with the permissive MIT license.  The `spyder.ttf` font, though, seems to be quite restricted, but there is no explicit documentation explaining this: the OS/2 table has `fsType = 0x04`, which according to [the TrueType Reference Manual](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6OS2.html) means:

> Preview and print embedding; should not be 1 if bits 1 or 3 are one. Fonts that have only this bit set may be embedded in documents and temporarily loaded on the remote system. Documents containing such fonts must be opened “read-only;” no edits can be applied to the document.

This means that it is probably not actually installable with Spyder, which doesn't seem to make much sense.  So it should probably be changed to have `fsType = 0x00` meaning that the font is fully installable on the system.

Here is a modified version of the font with this change made should you wish to use it:
[spyder-installable.zip](https://github.com/spyder-ide/spyder/files/5932819/spyder-installable.zip)

Thanks!

**Comment by juanis2112** [comment]
Thanks @juliangilbey I think you are right. Let's ask @SylvainCorlay who is the original author of the file if he agrees with this change.

**Comment by juanis2112** [comment]
Pinging @SylvainCorlay again about this

**Comment by ccordoba12** [comment]
Hey @juliangilbey, I think we don't have a problem with your proposed change. Could you create a pull request against 4.x with it? Thanks!
