### ISSUE TITLE
Most people left Spyder due to lack of Remote Development

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#14703]
I have been using spyder for 4 years, and despite all the small bugs that it has I loved using it. However, I'm at a point in life that I need to use remote servers and clusters.
It was sad that spyder does not have the features to support Remote Development yet. I had to switch to VScode. 
I just wanted to 1) thank you guys for the great spyder and support and 2) just mention that if you wanna keep up being among the top ide you should consider developing that feature sooner and more seriously and with the highest priority.
To my knowledge, a lot of people are leaving spyder to vscode because VS Code supports Remote Development very well (and based on psychology  when people change an ide they usually won't come back)
Good luck.

**Comment by Dan-Patterson** [comment]
thankfully I am not most people.  Support your local environment ;)

**Comment by ccordoba12** [comment]
Hey @seyeeet, thanks for the feedback. We are aware of this limitation and will try to address it in a future release.

Since there are several issues opened already about this, I'm going to close this one.

**Comment by seyeeet** [comment]
@ccordoba12 do you have an estimate when 'future release' would be?

**Comment by ccordoba12** [comment]
Probably Spyder 6, to be released at the end of this year.
