### ISSUE TITLE
No pandas packages in mac os installer package.

### ISSUE THREAD

**Issue by bt-worm** [spyder-ide/spyder#14708]
import pandas
print ("foo")

will lead to something like "ModuleNotFoundError" and "KeyErro" about pandas

when checking "Dependencies" in Help, the pandas entry is marked with an exclamation symbol.

I found no pandas directory under /Applications/Spyder.app/Contents/Resources/lib/python3.9

The installer dmg (full version) was download from github. tried 4.2.1 & 4.2.0, same result.

windows version just works OOB.

thanks

Spyder version: 4.2.1
Python version: 3.9.1 64-bit
Qt version: 5.12.1
PyQt version: 5.12.3
Operating System name/version: macOS 10.15.7 (Catalina)

**Comment by ccordoba12** [comment]
Hey @bt-worm, thanks for reporting. This was fixed already, but unfortunately you need to wait until we release installers for our next version (4.2.2) in a couple of weeks.
