### ISSUE TITLE
Running python\python.exe spyder.launch.pyw from application directory does not work

### ISSUE THREAD

**Issue by char101** [spyder-ide/spyder#14706]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When given a relative path, `__file__` in `Spyder.launch.pyw` is relative (platform: Windows, python: 3.7.9). Thus the `pkgs` directory added to `PYTHONPATH` is relative, and this causes module loading failure when spyder is launching.

## Solution

Make `__file__` absolute by adding `os.path.abspath(__file__)`.

### What steps reproduce the problem?

1.  cd `spyder-dir`
2.  python\python.exe spyder.launch.pyw

### What is the expected output? What do you see instead?

Expected: spyder is running
Instead: module not found error

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "Spyder.launch.pyw", line 37, in <module>
    main()
  File "pkgs\spyder\app\start.py", line 213, in main
  File "pkgs\spyder\app\mainwindow.py", line 3624, in main
  File "pkgs\spyder\app\mainwindow.py", line 3482, in create_window
  File "pkgs\spyder\app\mainwindow.py", line 816, in setup
ModuleNotFoundError: No module named 'spyder.plugins.help.plugin'
```

## Versions

* Spyder version: 4.2.1
* Python version:  3.7.9
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @char101, thanks for reporting. You said that you're doing:

1. cd spyder-dir
2. python\python.exe spyder.launch.pyw

However, our Windows application is not meant to be started like that. Instead, you need to use the menu entry that we create in the Windows menu.

Furthermore, I think it's not possible to perform the change you want because the installer is created programmatically. @dalthviz, what do you think?

**Comment by char101** [comment]
Hi,

You are right, the launcher is generated by pynsist, so it is not a problem with spyder.

Thanks.
