### ISSUE TITLE
Lag in editor on MacOS (even with small files)

### ISSUE THREAD

**Issue by bbutler3** [spyder-ide/spyder#14702]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am having trouble with a large amount of lag when typing in the editor that makes the IDE essentially unusable. The CPU usage seems to spike whenever I start to type. The issue only occurs on my Mac installation (in Windows and in Ubuntu through WSL there is no such problem). I have recently updated all three of those Anaconda installations to Python 3.8, and Spyder is now at version 4.2.1 on all. The issue was not occurring prior to the update. I saw a couple of previous issues that were similar to this, but they seem to have been solved by previous Spyder updates. Any help you can provide would be appreciated. I am happy to provide more specific information upon request.

### What steps reproduce the problem?

1. Launching Spyder from the command line
2. Attempting to type anything in any open file in the editor

### What is the expected output? What do you see instead?
N/A

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Darwin 20.3.0 (MacOS Big Sur - 11.2)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by doublewhy** [comment]
+1 I experience the same issue.

**Comment by ccordoba12** [comment]
Hey @bbutler3 and @doublewhy, thanks for reporting. Unfortunately, some packages we depend on are quite outdated in Anaconda and don't work with Big Sur.

There are two things you can do to workaround this:

1. Download our [DMG installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg) and then connect it to your conda environments by following our FAQ [here](http://docs.spyder-ide.org/current/faq.html#using-existing-environment). All users that tried this have reported it solves the lags for them.
2. Install Spyder from Conda-forge with the following commands:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

    That should work too but we have received mixed feedback about it (for some users it does work but not for others).

**Comment by bbutler3** [comment]
Workaround 1 worked perfectly for me. Thank you @ccordoba12. Hopefully some of those packages get updated soon! For now, though, this is actually fairly handy for me, as I like that I can start Spyder from my Applications if I want. I appreciate the help.

**Comment by ccordoba12** [comment]
Thanks for the confirmation @bbutler3. Closing then.
