### ISSUE TITLE
Found conflicts! Looking for incompatible packages...

### ISSUE THREAD

**Issue by jpcam** [spyder-ide/spyder#14712]
Hey everyone, Anaconda just released new packages for 4.2.1 with fixes for all the errors you reported. Please run

    conda update spyder

if you already have 4.2.1, or

    conda install spyder=4.2.1

or if you had to roll back to a previous version, and let us know if things are working for you now.

Thanks for your help!

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/14687#issuecomment-773641452_

**Comment by jpcam** [comment]
Didnt resolve conflicts. 
Result is pandas df style.formats dont function on spyder but function on Jupyter.
[Spyder update fail.docx](https://github.com/spyder-ide/spyder/files/5940507/Spyder.update.fail.docx)

**Comment by ccordoba12** [comment]
Hey @jpcam, thanks for reporting. Please run

    conda update anaconda
    conda install spyder=4.2.1

to solve your problem.

**Comment by jpcam** [comment]
Carlos,
Many thanks for taking the time to look at this.
I have since run the updates and things seem to be operating as before.
Sadly, the other issue that I was hoping this update would resolve still remains (see #14728)
I have had a response on #14728 from the Spyder team who said they have reproduced the same issue but that
It would possibly only get resolved in Spyder 5.0.
Unfortunately, I am still a python beginner so won't be able to help you make any progress with it.

So for now patiently wating for 5.0

Have a nice day
JP

________________________________

**Comment by ccordoba12** [comment]
Ok, I'm closing this one then because it's fixed now.

**Comment by ArnaldoMatute** [comment]
I'm installing spyder 5.0.5. It says "found conflicts! Looking for incompatible packages". It began to examine conflicts and it's been 24 hours and has not ended. Should I keep waiting till it ends?

**Comment by ccordoba12** [comment]
@ArnaldoMatute, you need to run first

    conda update anaconda

**Comment by ArnaldoMatute** [comment]
Hi @ccordoba12. I had done it before I tried to install Spyder 5.0.5 and I got what I told you in the other post.

**Comment by big-mat** [comment]
@ArnaldoMatute, what ended up happening? The same thing has just happened to me..

**Comment by ArnaldoMatute** [comment]
I had to completely uninstall Anaconda the way explained here, under "Full uninstall": https://docs.anaconda.com/anaconda/install/uninstall/
Then, I installed it again.
