### ISSUE TITLE
Spyder is not displaying Matplotlib Plot inline

### ISSUE THREAD

**Issue by OrbitalMechanic** [spyder-ide/spyder#14723]
## Problem Description
Not able to display Matplotlib plot inline in Spyder.

### What steps reproduce the problem?
Running the follow ing Python program in Spyder:

"""
Spyder Editor

This is a temporary script file.
"""

```
import matplotlib.pyplot as plt
import numpy as np

plt.switch_backend('QT5Agg')
plt.style.use("ggplot")

t = np.arange(0.0, 2.0, 0.1)
s = np.sin(2 * np.pi * t)
s2 = np.cos(2 * np.pi * t)
plt.plot(t, s, "o-", lw=4.1)
plt.plot(t, s2, "o-", lw=4.1)
plt.xlabel("time (s)")
plt.ylabel("Voltage (mV)")
plt.title("Simple plot $\\frac{\\alpha}{2}$")
plt.grid(True)

plt.savefig("test.png")

plt.show()
```
 

### What is the expected output? What do you see instead?
I expected to see my plot inline in Spyder, I get the plot in a separate Python window. See below:

<img width="661" alt="Screen Shot 2021-02-09 at 03 40 03" src="https://user-images.githubusercontent.com/4779511/107338270-5a1f5a00-6a89-11eb-90e3-a8c0d6991b4d.png">
### Paste Traceback/Error Below (if applicable)

```
IPython console displayed:
Python 3.8.1 (default, Jan  8 2020, 16:15:59) 
Type "copyright", "credits" or "license" for more information.

IPython 7.20.0 -- An enhanced Interactive Python.

runfile('/Users/user/temp.py', wdir='/Users/user')
```

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version:  Mac OS X, Big Sur (11.2)

### Dependencies
N/A

**Comment by Dan-Patterson** [comment]
Tools menu, Preferences, IPython console, Backend... is it set to "inline"

**Comment by OrbitalMechanic** [comment]
I have tried it with Backend set to "Inline" as well as "Automatic" and 
it does not output a plot to the Spyder window.

Please advise.

Sam Dupree.

**Comment by Dan-Patterson** [comment]
Could be a Mac thing

**Comment by ccordoba12** [comment]
Hey @OrbitalMechanic, thanks for reporting. You're changing the backend to Qt in this line of the code you posted above:

```python
plt.switch_backend('QT5Agg')
```

so that's why you're not getting inline plots in Spyder. If you comment it, you'll see your plot in the Plots pane.

**Comment by OrbitalMechanic** [comment]
Thank you. Between commenting out plt.switch_backend( 'QT5Agg' ), 
setting Backend to Inline and restarting the kernel did the trick.
I appreciate the help from all the contributors to this thread.

Sam Dupree.
