### ISSUE TITLE
Spyder Slow on Mac Big Sur

### ISSUE THREAD

**Issue by frohmm25** [spyder-ide/spyder#14735]
Quick thing i learned, when I hoop up a monitor and drag spyder to the attached monitor it works great without lag. Odd, but maybe this helps some of you.

**Comment by ccordoba12** [comment]
Hey @frohmm25, thanks for reporting. The only known workaround to make Spyder work in Big Sur is to download our [DMG installer](https://github.com/spyder-ide/spyder/releases/download/v4.2.1/Spyder.dmg) and then connect it to your conda environments by following our FAQ [here](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

All users that tried this have reported it solves the lags for them.
