### ISSUE TITLE
Bug at code folding of code cells 

### ISSUE THREAD

**Issue by jbund256** [spyder-ide/spyder#14730]
## Problem Description

When I fold cole cells or subcells, the initator line, i.e. the line beginning with # %%, of the next code cell is folded as well. Thus the title of the next code cell is vanished. 

### What steps reproduce the problem?

1.  Open a python file in Spyder
2. Create two code cells with # %% *title*
3. Fold the first code cell.

```python
# %% Title 1

a = 1
b = 2

# %% Title 2
```

### What is the expected output? What do you see instead?

I see that the title of the second code cell is vanished. I would expect that the title of the second code cell does not vanish. Ideally, if there is a blank line before the second code cell, after folding the first code cell the blank line should remain there and should not be folded (for better readability). 

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro/ Version 20H2

**Comment by dalthviz** [comment]
Hi @jbund256 thanks for the feedback! I was able to reproduce this :+1: 

![foldecell](https://user-images.githubusercontent.com/16781833/107556204-65cd6680-6bd8-11eb-9897-efb22ae8358d.gif)


Pinging @andfoy and @ccordoba12 just in case

**Comment by remisalmon** [comment]
The code folding of cells was introduced in https://github.com/spyder-ide/pyls-spyder/pull/15

I have just pushed a fix at https://github.com/spyder-ide/pyls-spyder/pull/18

**Comment by ccordoba12** [comment]
Thanks a lot for your help @remisalmon! I tested your fix manually and it's working as expected.

This will be part of our next version (4.2.2), to be released in a week.
