### ISSUE TITLE
Inline images copied from IPython and pasted in Word/Writter have low resolution

### ISSUE THREAD

**Issue by DavidMSou** [spyder-ide/spyder#14736]
1. Create a plot from matplotlib with inline option set in Spyder.
2. Right click and select "Copy image", above the "Save image as..." option.
3. Paste on Libreoffice Writter or Microsoft Office Word (or any software actually, even Inkscape).

The expected output was a higher resolution image but instead it is grainy.
Changing the DPI from the SVG panel in Spyder's preferences has no effect.

* Spyder version: Spyder 4.2.0
* Python version: 3.8.3 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Linux Mint 20 (5.4.0-65-generic)

**Comment by Dan-Patterson** [comment]
Directing the plot to the Plots pane and saving to disk or copy/paste to an image editor (SnagIt) results in the same image resolution.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
