### ISSUE TITLE
Add rtree to our setup.py dependencies

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#14748]
- Now that `rtree` has wheels for Python 2.7 - 3.9, we can add a dependency for it in our `setup.py`.
- We also need to increase the minimal required version to `>=0.9.7`.

**Comment by mrclary** [comment]
@ccordoba12, this will work for the installers, but not for conda, unless we support the conda-forge channel. conda pkgs/main is still stuck at `rtree=0.9.4`. We could add this to #14496.

**Comment by ccordoba12** [comment]
> conda pkgs/main is still stuck at rtree=0.9.4.

If we increase our minimal required version to `0.9.7`, they'll have to catch up and add it to the `defaults` channel, so don't worry about that.

> We could add this to #14496.

Sure, please do. Thanks for helping me with that!
