### ISSUE TITLE
Find in files plugin does not forward results to editor properly

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#14755]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When clicking on a result in the find in files plugin, the editor doesn't always goes to the right result.

### What steps reproduce the problem?

1. Create a new file in an empty folder
2. Paste: 
```
we Weee wee
We
wee
```
3. Save the file, then set the current working directory to the partent folder
4. Go to the Find plugin
5. Search for `we+` with regexp enabled and no case sensitivity
6. Click on one of the 5 results
7. Only the first one is properly selected
 
3. 

### What is the expected output? What do you see instead?
I would expect to go to the bold text, instead it sometimes goes there, sometimes it just go to the line, sometimes it goes to the first result, event if there is multiple results in the line.

## Versions

Spyder 4.3.0.dev0
Python 3.7.6 64-bit | Qt 5.12.8 | PyQt5 5.12.3 | Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Thanks @impact27 ! Pinging @ccordoba12 just in case
