### ISSUE TITLE
avahi_service_browser_new (when starting kernel)

### ISSUE THREAD

**Issue by florianteichmann** [spyder-ide/spyder#14750]
Hello,

I am running Spyder with Python 3.6 on ubuntu. I want to connect to a tobii eyetracker via the tobii_research SDK. When a run:

import tobii_research
tobii_research.find_all_eyetrackers 

I get:

An error occurred while starting the kernel
python3.6: browser.c:581: avahi_service_browser_new: Assertion 'client' failed.

(I expect an output with a list of the connected tobii eye tracker)

I have reset tried to: set Spyder to factory defaults, started a new console, restart the computer, check all versions and libraries - can someone help?

**Comment by florianteichmann** [comment]
I have also tried this and get the same error:

user@00000000:~/Desktop > python3 
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import tobii_research
python3: browser.c:581: avahi_service_browser_new: Assertion `client' failed.

Aborted (core dumped)

**Comment by steff456** [comment]
Hi @florianteichmann,

How did you installed the package `tobii_research `?

**Comment by florianteichmann** [comment]
Hi @steff456,

with pip install (I also checked with pip list if its the most recent version)

**Comment by steff456** [comment]
I'm unable to reproduce this issue, can you please post here a screenshot with the error?

**Comment by florianteichmann** [comment]
![Bildschirmfoto 2021-02-14 um 21 24 07](https://user-images.githubusercontent.com/58268524/107985145-c76f4580-6fc9-11eb-8fec-86e12bf026bd.png)

**Comment by florianteichmann** [comment]
![Uploading IMG_0820.jpeg…]()

**Comment by florianteichmann** [comment]
![IMG_0820](https://user-images.githubusercontent.com/58268524/107985321-2a60dc80-6fca-11eb-86a8-009ca3e41433.jpeg)

**Comment by florianteichmann** [comment]
![Screenshot_2021-02-16_11-06-17](https://user-images.githubusercontent.com/58268524/108048435-51112880-7047-11eb-8c14-49c9e368376b.png)

**Comment by ccordoba12** [comment]
@florianteichmann, given that when you run `import tobii_research` in a Python interpreter outside Spyder, it makes the interpreter crash, this is not a problem related to Spyder but to that package.

Therefore, there's nothing we can do to help you here, sorry. Instead, please try to report it to the maintainers of that package to see if they can help you with it.
