### ISSUE TITLE
special comments (e.g. #--- ) no longer appear in the outline pane after updating to 4.2.1

### ISSUE THREAD

**Issue by garfieldthecat** [spyder-ide/spyder#14753]
## Problem Description

Special comments used to appear in the outline pane ( view - panes - outline).
By special comments I mean any comment starting with #--- , e.g.:

#--- Bookmark 1

and starting with other keywords specified in tools - preferences - editor - advanced settings - annotations (eg TODO), as long as right click on the file name in the outline pane -> "show special comments" is enabled.

**After the update to Spyder 4.2.1, only a comment followed by 4 hyphens is recognised, while comments followed by 3 hyphens no longer are.**

This means that I would have to add an hyphen to all the bookmarks in my existing code base!

* Spyder version:  4.2.1
* Python version: 3.7.9
* Qt version: qmake version 3.1 using qt version 5.9.7
* PyQt version: 329986 (5.9.2)
* Operating System name/version: Windows 10 64 bit

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.20.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.7.4 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  5.0.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.4.3 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.2.1 (OK)
scipy >=0.17.0                 :  1.6.0 (OK)
sympy >=0.7.3                  :  1.7.1 (OK)

# Spyder plugins:
spyder_unittest                :  0.4.1 (OK)

```

**Comment by steff456** [comment]
Hi @garfieldthecat,

We decided to define that block comments will start with four hyphens `# ----`, please start using this notation for seeing the in the outline pane.

**Comment by garfieldthecat** [comment]
May I ask where this is documented and if there were other changes, eg to how TODO etc are interpreted? I looked for it in the changelog https://github.com/spyder-ide/spyder/blob/master/CHANGELOG.md#version-421-2020-12-18 and in the docs https://docs.spyder-ide.org/current/editor.html?highlight=outline but couldn't find it mentioned. 

Also, may I ask why? Having to update larger code bases is a bit of a pain...

**Comment by jagiella** [comment]
> Hi @garfieldthecat,
> 
> We decided to define that block comments will start with four hyphens `# ----`, please start using this notation for seeing the in the outline pane.

I justed tested this notation and it doesn't work for me.
I tested:
`# ---- TEST`
and 
`#---- TEST`
Any idea why?
