### ISSUE TITLE
Goto function definition not working in Spyder 3.3.6

### ISSUE THREAD

**Issue by gulatiparidhi** [spyder-ide/spyder#14764]
Goto definition does not work in my IDE. I have tried reset but still doesnt work. The correct file paths are also added in PYTHONPATH manager. Could someone help?

Dependencies:
IPython >=4.0;<6.0:  5.8.0 (OK)
cython >=0.21     :  0.29.13 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
numpy >=1.7       :  1.16.5 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.5.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by ccordoba12** [comment]
Hey @gulatiparidhi, thanks for reporting. Unfortunately, Spyder 3 is no longer maintained, so you need to install Spyder 4 instead.
