### ISSUE TITLE
Spyder doesn't launch on anaconda, it's also very slow in a newly created environment

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#14766]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm not sure whether these issues are solved or not, but I still can't launch Spyder on anaconda in the base environment (despite restoring my base environment to it's original revision). Also if I create a new environment from scratch and install Spyder on it, typing in the IDE is annoyingly slow!

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS 11.2.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @mhdmyz, thanks for reporting. We've already gone through this: the only way to make Spyder work on Big Sur right now is to use our DMG installer.

There's nothing we can do about Anaconda because they're using a very old version of Qt (the graphical library upon which Spyder is built). If you want to get information about when that will be fixed, please open an issue here:

https://github.com/ContinuumIO/anaconda-issues/
