### ISSUE TITLE
Output of os.system, subprocess.call goes to wrong console

### ISSUE THREAD

**Issue by kbauer** [spyder-ide/spyder#14783]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related) *It was reproducible there.*
* [x] Tried basic troubleshooting (if a bug/error)
    
* [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When running `os.system` or `subprocess.call` on Windows 10, no output is produced in the Spyder iPython console. Instead the output goes to the Anaconda Prompt console or, if Spyder was started from the start menu, is simply discarded.

Additionally, error messages may be shown repeatedly in the iPython console pane, which is like related to pull request https://github.com/spyder-ide/spyder/pull/14025, but its not clear whether the pull-request would also solve the "misplaced stdout" part of the observation.

The same issue is reproducible with `jupyter qtconsole` and `ipython qtconsole`.

When running bare-bones consoles (`ipython`, `python`), the issue does not appear, presumably because everything is displayed in the same console.

On Linux, the issue did not occur.

![image](https://user-images.githubusercontent.com/7498468/108419134-71e9a180-7232-11eb-9f80-7bd3c11964ad.png)
![image](https://user-images.githubusercontent.com/7498468/108419143-757d2880-7232-11eb-9a45-821259e3c0be.png)

### What steps reproduce the problem?

1. Open Spyder from the Anaconda prompt.
2. In the iPython console type `os.system(r"mkdir C:\tmp\demo & dir C:\tmp\demo")`

Likewise when running `jupyter qtconsole` or `ipython qtconsole`.

### What is the expected output? What do you see instead?

The expectation is to see the output in the graphical console, together with the output of `print` or `sys.stdout.write`.

Instead the output is displayed in the command prompt window.

### Paste Traceback/Error Below (if applicable)
Not applicable

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2, PyQt5: 5.12.3
* Operating System name/version: Windows 10, Version 2004 (OS Build 19041.804)

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.6.0 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by andfoy** [comment]
Hi @kbauer, thanks for opening this issue, since you found that this issue is also reproducible on QtConsole, I would recommend opening this issue there, since Spyder uses it as a downstream dependency and we cannot fix it from here, thanks.
