### ISSUE TITLE
Kernel die when saving a preload keras model

### ISSUE THREAD

**Issue by rogeravs1997** [spyder-ide/spyder#14788]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When trying to save a loaded Keras model, the console die and show message "An error ocurred while starting the kernel"

### What steps reproduce the problem?

1. load keras model
2. save keras model
3. 

### What is the expected output? What do you see instead?
Kernel died and red message pops out saying: "An error ocurred while starting the kernel"

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.15
* Python version: 3.8.5
* Qt version:  5.9.7
* PyQt version:  5.9.2
* Operating System name/version: Windows 10 Home 1909 x64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.20.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.7.4 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  5.0.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.4.3 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.4 (OK)
numpy >=1.7                    :  1.20.1 (OK)
pandas >=0.13.1                :  1.2.2 (OK)
scipy >=0.17.0                 :  1.6.0 (OK)
sympy >=0.7.3                  :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @rogeravs1997, thanks for reporting. Could you test things in a Jupyter notebook? If you observe the same problem there, it means it's not a problem with Spyder but with Keras.

Thanks for your help!

**Comment by rogeravs1997** [comment]
> Hey @rogeravs1997, thanks for reporting. Could you test things in a Jupyter notebook? If you observe the same problem there, it means it's not a problem with Spyder but with Keras.
> 
> Thanks for your help!

I've just tried and the problem persists. I'll be trying with some other versions of the packages involved, I have an intuition that the problem it's related to dependencies. Thank you so much. I guess you can close the issue, but please let it open to participants, so I can comment if I found a solution.
Thanks again!

**Comment by ccordoba12** [comment]
Ok, I'll leave it open for a while then. Hope you can find a solution for your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response. If you find a way to reproduce this problem, please let us know.
