### ISSUE TITLE
Can't import vpython in the standalone version

### ISSUE THREAD

**Issue by GuidodiPasquo** [spyder-ide/spyder#14802]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Vpython fails to import, I get the following error:

ModuleNotFoundError: No module named 'vpython'

The program runs fine from the console.
I'm using the new standalone version of Spyder (4.2.2), in the past I used anaconda and it worked alright, but I'm trying to not use it in this machine if possible.

### What steps reproduce the problem?

1. Run:
```
import vpython as vp
vp.box()
```

### What is the expected output? What do you see instead?

A new browser tab with a box inside.

I get an error.

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):

  File "C:\Users\guido\Desktop\vp_test.py", line 8, in <module>
    import vpython as vp

ModuleNotFoundError: No module named 'vpython'

```

## Versions

* Spyder version: 4.2.2
* Python version: Python 3.7.9 64-bit
* Qt version: Qt 5.12.10 
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Windows 10 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  53.0.0 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @GuidodiPasquo, thanks for reporting. If you want to use to other packages that don't come with our installer, you need to do the following:

1. Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html).

2. Create a [conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) after that with the packages you want to use and `spyder-kernels`. In your case you need to run these commands in a system terminal (i.e. `cmd.exe`):

        conda activate base
        conda create -n myenv -c conda-forge spyder-kernels vpython

3. Connect Spyder to that environment by following [these instructions](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Please do that and let us know if it works for you.

**Comment by GuidodiPasquo** [comment]
I'm getting the following error:
```
Traceback (most recent call last):

  File "C:\Users\guido\.spyder-py3\temp.py", line 8, in <module>
    import vpython as vp

  File "C:\Python\Miniconda\envs\myenv\lib\site-packages\vpython\__init__.py", line 57, in <module>
    _warn_if_spyder_settings_wrong()

  File "C:\Python\Miniconda\envs\myenv\lib\site-packages\vpython\_notebook_helpers.py", line 23, in _warn_if_spyder_settings_wrong
    from spyder import __version__

ModuleNotFoundError: No module named 'spyder'
```

**Comment by GuidodiPasquo** [comment]
I had forgotten to install Spyder in the environment, after running
```
conda install spyder
```
it started working.
Thanks a lot for the answer!

**Comment by ccordoba12** [comment]
> I had forgotten to install Spyder in the environment

I was about to tell you. I'm really glad you were able to figure that out by yourself.
