### ISSUE TITLE
Error thrown when re-starting kernel

### ISSUE THREAD

**Issue by b-a0** [spyder-ide/spyder#14828]
### What steps will reproduce the problem?

1. In the hamburg menu of the interpreter press "Restart kernel"

### Traceback
```python-traceback
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/client.py", line 642, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "jupyter_client/manager.pyc", line 454, in restart_kernel
  File "jupyter_client/manager.pyc", line 314, in start_kernel
  File "qtconsole/manager.pyc", line 57, in post_start_kernel
  File "jupyter_client/manager.pyc", line 295, in post_start_kernel
  File "jupyter_client/manager.pyc", line 228, in _connect_control_socket
  File "jupyter_client/connect.pyc", line 545, in _create_connected_socket
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/zmq/sugar/context.py", line 234, in socket
    raise ZMQError(ENOTSUP)
zmq.error.ZMQError: Operation not supported
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/client.py", line 629, in <lambda>
    lambda: self._finalise_restart(True))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/widgets/client.py", line 664, in _finalise_restart
    sw.spyder_kernel_comm.open_comm(sw.kernel_client)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/comms/kernelcomm.py", line 135, in open_comm
    kernel_client.comm_manager.new_comm(self._comm_name, data={
AttributeError: 'NoneType' object has no attribute 'new_comm'
```

## Versions

* Spyder version: 4.2.2 
* Python version: 3.9.1
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.3.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  52.0.0 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
@b-a0, thanks for reporting. Did you connect Spyder to a kernel in another environment?

**Comment by b-a0** [comment]
Yes, I tried to restart the kernel just after switching the environment with "Change default environment in Preferences"

**Comment by ccordoba12** [comment]
Ok, thanks for the update.

@mrclary, can you reproduce this error?

**Comment by mrclary** [comment]
@b-a0 and @ccordoba12, I cannot reproduce this error. I've tried with internal Python interpreter, external pyenv interpreter, and external conda interpreter. I've tried using the console menu as well as the keyboard shortcut. All attempts have successfully restarted the kernel.

I did notice one issue that does not seem to be related. When I started with an internal interpreter, changed to external conda interpreter in the preferences, but restarted the kernel _before_ closing the internal interpreter IPython Console, I did get 
```python-traceback
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000112c04dc0 (most recent call first):
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010aacadc0 (most recent call first):
/Users/rclary/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh: line 14: 6136 Abort trap: 6 $CONDA_ENV_PYTHON ‑m spyder_kernels.console ‑f $SPYDER_KERNEL_SPEC
```
However, this was quickly remedied by closing the Console tab. This seems to be unrelated to the OP, and is an idiosyncrasy of restarting the kernel under these precise conditions that I stumbled upon.

**Comment by mrclary** [comment]
@b-a0, are you on Big Sur?
Can you clarify under which of the following conditions the error occurs?
### Option 1
  * IPython Console running with environment "A"
  * Environment "A" selected in Preferences
  * Restart the kernel.
### Option 2
  * IPython Console running with environment "A"
  * Environment "B" selected in Preferences
  * Restart the kernel
### Option 3
  * IPython Console running with environment "A"
  * Environment "B" selected in Preferences
  * Close all console tabs (a new tab in environment "B" should open)
  * Restart the kernel

Can you post the environment(s) that you are using for the IPython Console?

**Comment by mrclary** [comment]
I have not been able to reproduce this issue on Big Sur either

**Comment by ccordoba12** [comment]
Thanks @mrclary for your thorough testing!

This part of the error message posted by @b-a0 seems interesting to me:

```python-traceback
File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/zmq/sugar/context.py", line 234, in socket
    raise ZMQError(ENOTSUP)
zmq.error.ZMQError: Operation not supported
```

It seems to point out to a problem on @b-a0's side instead of one in Spyder.

**Comment by b-a0** [comment]
Thanks for looking into this.

Yes, I'm on Big Sur (11.2.1 at the time of this issue, now on 11.2.2).

I've tried out the different options from [this comment](https://github.com/spyder-ide/spyder/issues/14828#issuecomment-787641842), restarting Spyder in between my tries, but can no longer reproduce this issue. Hence I'm closing it.

**Comment by mrclary** [comment]
@b-a0 I'm glad it's working for you now. If the issue resurfaces, please reopen the issue with any new information.
