### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by IgorIzyurov** [spyder-ide/spyder#14820]
![image](https://user-images.githubusercontent.com/56837204/109262796-78fc4b00-7802-11eb-833f-fb23add809dc.png)

**Comment by juanis2112** [comment]
Hi @IgorIzyurov can you please provide more information on what version of Spyder you are trying to launch and how did you install Spyder?

**Comment by IgorIzyurov** [comment]
> Hi @IgorIzyurov can you please provide more information on what version of Spyder you are trying to launch and how did you install Spyder?

Hi! It is the latest Spyder 4.2.1. I installed it within Anaconda. The error notification started to appear after the update every time I launch Spyder. It doesn't seem to affect the work of the rest IDE.

Also, details of the error:
  File "/home/igor/.anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2198, in update_source_menu
    self.editor.refresh_formatter_name()
AttributeError: 'NoneType' object has no attribute 'refresh_formatter_name'

**Comment by juanis2112** [comment]
This seems to be a problem with Anaconda rather than Spyder. I suggest installing Spyder in a brand new environment using conda-forge instead. To do this read the following section in our installation guide https://docs.spyder-ide.org/current/installation.html#new-conda-environment

**Comment by juanis2112** [comment]
Closing for no response.
