### ISSUE TITLE
Spyder does not recognize rtree 0.9.4

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#14822]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I did a fresh install of Miniconda in Python 3.8, created a new environment, and installed Spyder. Nothing has been yet configured or changed. On startup Spyder always complains about rtree >=0.8.3 being a missing dependency. Conda list shows that rtree 0.9.4 is installed which satisfies the version requirement.

### What steps reproduce the problem?

1. Create fresh conda environment with a fresh Spyder install on Python 3.8.
2. Start Spyder

### What is the expected output? What do you see instead?

Spyder should acknowledge that rtree is installed.

## Versions

* Spyder version: 4.2.1
* Python version: 3.8.8 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Linux 5.8.0-44-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  None (NOK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by Khris777** [comment]
Solved after switching to conda-forge channel which updated rtree to 0.9.7.

**Comment by juanis2112** [comment]
Hi @Khris777 thanks for reporting this. It seems this problem is not related to Spyder but to miniconda. Several people have reported it before and it seems like installing from conda-forge is a good solution https://stackoverflow.com/questions/59981914/missing-dependancies-of-rtree.

I'll close this one since you managed to solve it but let me know if there is anything else we can help you with.
