### ISSUE TITLE
Spyder kernel issue 

### ISSUE THREAD

**Issue by gkvallis** [spyder-ide/spyder#14829]
I installed Anaconda3 on a new Macobook Pro. Then I installed Spyder v4.2.2, using the Mac installer, and pointed it to the Python in Anaconda. However, Spyder won't open an iPython console -- it says I need a Spyder kernel => 1.10.0. But when I update spyder-kernels (even using conda-forge) it just gives me version 1.9.4. If I specify 1.10.0 it doesn't work. So I can't get Spyder to work properly. 

Thanks for your help.

**Comment by ccordoba12** [comment]
Hey @gkvallis, thanks for reporting. To update to a more recent version of spyder-kernels please run the following commands:

    conda update anaconda
    conda install spyder=4.2.1

By updating Spyder to 4.2.1 you'll automatically get spyder-kernels 1.10.1

**Comment by gkvallis** [comment]
That works. Thanks for the prompt response!
