### ISSUE TITLE
Spyder Missing Dependencies! error on latest Anaconda

### ISSUE THREAD

**Issue by Samk19** [spyder-ide/spyder#14833]
## Problem Description
After launching spyder, got the following error:

You have missing dependencies!
rtree >=0.8.3 : None (NOK)

Please install them to avoid this message.

rtree version 0.9.4 already installed.....screenshot of conda list provided below

### What steps reproduce the problem?

    Download and install Anaconda3-2020.11-Linux-x86_64.sh;
    After installation, launching spyder and notice there is no above mentioned error.
    Update Anaconda by command "conda update --all"
    After update, launching spyder and above mentioned error appears.

### What is the expected output? What do you see instead?
No error

But The latest Anaconda update breaks Spyder with missing dependencies error.

## Versions

* Spyder version: 4.2.1
*Python 3.8.8 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Linux 5.8.0-7642-generic 
*OS: Pop!_OS 20.04

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.1 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  None (NOK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

Screenshots of conda list

![Screenshot from 2021-02-28 19-00-11](https://user-images.githubusercontent.com/36104528/109420955-3fdafb00-79fb-11eb-9915-45fbe86b0e09.png)
![Screenshot from 2021-02-28 19-01-09](https://user-images.githubusercontent.com/36104528/109420956-41a4be80-79fb-11eb-9f51-3a8061ee7796.png)

**Comment by ccordoba12** [comment]
Hey @Samk19, thanks for reporting. Please go to the menu `View > Panes > Internal console`. In the new panel that opens after that write the following code:

    import rtree
    rtree.__file__
 
Then paste the result here. Thanks!

**Comment by Samk19** [comment]
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> import rtree
Traceback (most recent call last):
  File "/home/samk/anaconda3/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
  File "/home/samk/anaconda3/lib/python3.8/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/samk/anaconda3/lib/python3.8/site-packages/rtree/index.py", line 6, in <module>
    from . import core
  File "/home/samk/anaconda3/lib/python3.8/site-packages/rtree/core.py", line 143, in <module>
    rt.Error_GetLastErrorNum.restype = ctypes.c_int
  File "/home/samk/anaconda3/lib/python3.8/ctypes/__init__.py", line 394, in __getattr__
    func = self.__getitem__(name)
  File "/home/samk/anaconda3/lib/python3.8/ctypes/__init__.py", line 399, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/samk/anaconda3/bin/python: undefined symbol: Error_GetLastErrorNum
>>> rtree.__file__
Traceback (most recent call last):
  File "/home/samk/anaconda3/lib/python3.8/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'rtree' is not defined
>>>

**Comment by ccordoba12** [comment]
This seems to be caused by issues with LD_LIBRARY_PATH, at least according to this issue.

https://github.com/Toblerity/rtree/issues/64

So it doesn't seem related to Spyder.

**Comment by Samk19** [comment]
Got few solutions 
FOR LINUX (tested and worked): sudo apt install libspatialindex-dev
FOR MAC: brew install spatialindex

still not sure if its a permanent fix or not 

after using above command (i.e linux one).....spyder rtree error message gone 

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

**Comment by ccordoba12** [comment]
Your fix means that you're mixing Python packages installed in your system with ones from Anaconda (most probably through `LD_LIBRARY_PATH`).

I hope you understand what you're doing because, as (I think) Wes McKinney said, hell is others `LD_LIBRARY_PATH`.
