### ISSUE TITLE
scaling issue - huge icons 

### ISSUE THREAD

**Issue by gli-1** [spyder-ide/spyder#14849]
### What steps will reproduce the problem?

Just opening the Spyder causes the issue. The icons on top are huge, and I don't know how to fix this. It used to be normal and when I started using an exterior monitor this issue popped up. 

Thanks!

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.1 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by steff456** [comment]
Hi @gli-1,

Can you please post a screenshot for us to see how the icons appear on your screen? Also, can you please tell me what size of screen are you using?

**Comment by gli-1** [comment]
![Screenshot 2021-03-02 201604](https://user-images.githubusercontent.com/34671336/109737485-27521880-7b94-11eb-8ff3-a00b68b1ce95.jpg)
Hi, 

Please see the attached screenshot. My laptop is 1920 x 1080 and the exterior monitor is 3840 x 2160, and the same issue exists in both. 

Thanks!

**Comment by steff456** [comment]
Have you changed something under `Preferences > Interface > Screen resolution`?

![image](https://user-images.githubusercontent.com/20992645/109746626-b286da80-7ba3-11eb-92c0-6a91feab20ae.png)

**Comment by gli-1** [comment]
Hi,

Yes it was set to enable auto high DPI scaling. After I changed it to Normal, this issue resolved. Thank you very much!

**Comment by steff456** [comment]
Great! I'm closing this issue because it is fixed.

Thanks for reporting!
