### ISSUE TITLE
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.2 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.  You can install it by running in a system terminal:  conda install spyder‑kernels

### ISSUE THREAD

**Issue by NitinSaini18** [spyder-ide/spyder#14844]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder keeps showing me this error no matter either I create a new environment or use an old one. this error is not going. I have already checked spyder-kernels it is already installed.  Could anyone give me any suggestions?
![p2](https://user-images.githubusercontent.com/53210334/109607387-fc58bd80-7adc-11eb-84cc-0de43d032e19.jpg)

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

basically, I want to use tensorflow in my program which is installed only in one of the env. and when I tried to switch from the default python interpreter to my env. then spyder gives me this error. A month ago when I tried to switch from one env. to another it did not give me the error that time.

### Paste Traceback/Error Below (if applicable)

Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.2 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running it in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels
```python-traceback

PASTE TRACEBACK HERE

```

## Versions

# Name                    Version                   Build  Channel
absl-py                   0.10.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.12.5        py36ha15d459_1    conda-forge
chardet                   3.0.4                    pypi_0    pypi
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
gast                      0.3.3                    pypi_0    pypi
google-auth               1.21.2                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        1.7.0                    pypi_0    pypi
ipykernel                 5.5.0            py36h7b2dad6_1    conda-forge
ipython                   5.8.0                    py36_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jsonpickle                1.4.1                    pypi_0    pypi
jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
jupyter_core              4.7.1            py36ha15d459_0    conda-forge
keras-preprocessing       1.1.2                    pypi_0    pypi
libsodium                 1.0.18               h8d14728_1    conda-forge
markdown                  3.2.2                    pypi_0    pypi
numpy                     1.18.5                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
opt-einsum                3.3.0                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pip                       20.2.3                     py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
protobuf                  3.13.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
python                    3.6.11          h6f26aa1_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pywin32                   300              py36h68aa20f_0    conda-forge
pyzmq                     22.0.3           py36h1d5d788_1    conda-forge
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scipy                     1.4.1                    pypi_0    pypi
setuptools                49.6.0           py36h9f0ad1d_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
spyder-kernels            0.2.6                      py_1    conda-forge
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.0                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tornado                   6.1              py36h68aa20f_1    conda-forge
traitlets                 4.3.3            py36h9f0ad1d_1    conda-forge
urllib3                   1.25.10                  pypi_0    pypi
vc                        14.1                 h869be7e_1    conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
wincertstore              0.2                   py36_1003    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.1.0                    pypi_0    pypi
* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @NitinSaini18,

Which error is appearing to you in Spyder? The screenshot you posted is from spyder-terminal or your system terminal?

**Comment by NitinSaini18** [comment]
Hi @steff456,
The above screenshot is of my system terminal( already installed spyder-kernels) and yet it is showing me this error on spyder.

![p1](https://user-images.githubusercontent.com/53210334/109755493-f88b7080-7b9a-11eb-9960-92410aa40166.jpg)

**Comment by steff456** [comment]
If you do `conda list` in your environment which version of spyder-kernels appear?

Also I'm seeing in the list you added in the issue that you have a mix of packages installed by pip and conda. Did you installed tensorflow with pip or conda?

**Comment by NitinSaini18** [comment]
Here is the screenshot after running `conda list `

![3](https://user-images.githubusercontent.com/53210334/109759877-9afb2200-7ba2-11eb-865e-9c6000a4ab4e.jpg)

**Comment by steff456** [comment]
Can you please in a clean environment install all the packages with only conda or only pip? 

Please remember that it is not a good idea to mix pip with conda, if you want to learn more about it please see this video https://www.youtube.com/watch?v=Ul79ihg41Rs. In there you can probably find a way to solve your environment and get Spyder running with the dependencies you need.

**Comment by setegonz** [comment]
Same issue here. All packages have been installed via anaconda.
 `conda list`
```

(nlp) C:\Users\Me>conda list
# packages in environment at C:\Users\Steven\anaconda3\envs\nlp:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyhd3eb1b0_0
ca-certificates           2021.4.13            haa95532_1
certifi                   2020.12.5        py39haa95532_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
decorator                 5.0.6              pyhd3eb1b0_0
ipykernel                 5.3.4            py39h7b7c402_0
ipython                   7.22.0           py39hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.17.2           py39haa95532_1
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py39haa95532_0
libsodium                 1.0.18               h62dcd97_0
openssl                   1.1.1k               h2bbff1b_0
parso                     0.7.0                      py_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.0.1           py39haa95532_0
prompt-toolkit            3.0.17             pyh06a4308_0
pygments                  2.8.1              pyhd3eb1b0_0
python                    3.9.4                h6244533_0
python-dateutil           2.8.1              pyhd3eb1b0_0
pywin32                   228              py39he774522_0
pyzmq                     20.0.0           py39hd77b12b_1
setuptools                52.0.0           py39haa95532_0
six                       1.15.0           py39haa95532_0
spyder-kernels            2.0.1            py39haa95532_0
sqlite                    3.35.4               h2bbff1b_0
tornado                   6.1              py39h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
tzdata                    2020f                h52ac0ba_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py39h2bbff1b_0
zeromq                    4.3.3                ha925a31_3
```

**Comment by steff456** [comment]
Hi @setegonz,

Which version of Spyder are you using?

**Comment by setegonz** [comment]
@steff456 `4.1.5`

**Comment by ccordoba12** [comment]
@setegonz, please install spyder-kernels 1.10.2

**Comment by setegonz** [comment]
@ccordoba12 @steff456

`conda remove spyder-kernels`

then:

`conda install spyder-kernels=1.10.2`

And the issue continues....
```
# packages in environment at C:\Users\Steven\anaconda3\envs\nlp:
#
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyhd3eb1b0_0
ca-certificates           2021.4.13            haa95532_1
certifi                   2020.12.5        py39haa95532_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.4              pyhd3eb1b0_0
decorator                 5.0.6              pyhd3eb1b0_0
ipykernel                 5.3.4            py39h7b7c402_0
ipython                   7.22.0           py39hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.17.2           py39haa95532_1
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py39haa95532_0
libsodium                 1.0.18               h62dcd97_0
openssl                   1.1.1k               h2bbff1b_0
parso                     0.7.0                      py_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.0.1           py39haa95532_0
prompt-toolkit            3.0.17             pyh06a4308_0
pygments                  2.8.1              pyhd3eb1b0_0
python                    3.9.4                h6244533_0
python-dateutil           2.8.1              pyhd3eb1b0_0
pywin32                   228              py39he774522_0
pyzmq                     20.0.0           py39hd77b12b_1
setuptools                52.0.0           py39haa95532_0
six                       1.15.0           py39haa95532_0
spyder-kernels            1.10.2           py39haa95532_0
sqlite                    3.35.4               h2bbff1b_0
tornado                   6.1              py39h2bbff1b_0
traitlets                 5.0.5              pyhd3eb1b0_0
tzdata                    2020f                h52ac0ba_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                      py_0
wheel                     0.36.2             pyhd3eb1b0_0
wincertstore              0.2              py39h2bbff1b_0
zeromq                    4.3.3                ha925a31_3
```

**Comment by ccordoba12** [comment]
Sorry, the mapping between Spyder and spyder-kernels is here:

http://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-not-installed-incompatible
