### ISSUE TITLE
Ctrl-Shift-E not working

### ISSUE THREAD

**Issue by dbau** [spyder-ide/spyder#14846]
### What steps will reproduce the problem?

Hi, 

The shortcut to jump to the editor (Ctrl-Shift-E) is not longer working. 
For some reason, when using this shortcut form the console, an 'e' character get printed on the console (and deleted when repeating the shorcut).

## Versions

* Spyder version: 4.2.1 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-66-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.18.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.4.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.1 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  50.3.1.post20201107 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  1.18.1 (OK)
pandas >=1.1.1                  :  1.1.4 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @dbau,

I could not reproduce this issue in the latest release, can you please update your Spyder and let me know if the error persist?

**Comment by dbau** [comment]
Hi @steff456,

After updating to Spyder 4.2.2 the error pesists. Maybe some dependencies missing?

**Comment by steff456** [comment]
Did you changed the shortcut in preferences? What happens if you change to any shortcut and then revert it?

**Comment by dbau** [comment]
Hi,

If I change it to a different one (e.g. CTRL-SHIFT-Q or CTRL-SHIFT-J) it world. Reverting it back does not work. Still the same problem. Apparently the problem is only with the CTRL-SHIFT-E shortcut. 
I just updated to version 4.2.3 and the error persists.

**Comment by ccordoba12** [comment]
I can't reproduce this either. Do you have a special keyboard? I mean, one that requires an extra key to be pressed to get this shortcut?

**Comment by dbau** [comment]
[SOLVED]

The issue is because on Ubuntu 20.04, Gnome sets  the following shortcut:
[Gnome] Disable emoji keyboard shortcut (Ctrl+Shift+E)

Disabling the OS' emoji picker shortcut via the ibus-setup GUI solved the issue.

Thanks a lot!
