### ISSUE TITLE
Spyder not opening in different ways after conda update

### ISSUE THREAD

**Issue by btmmf** [spyder-ide/spyder#14867]
## Problem Description
I have a very similar problem to this: https://github.com/spyder-ide/spyder/issues/12557:

I updated  my conda environment and now Spyder does not start at all.
I don't even see its splash screen.

### What steps reproduce the problem?
qft: https://github.com/spyder-ide/spyder/issues/12557#issuecomment-623669614

I tried to execute spyder from command line to get some error output in two ways:
1. open PowerShell and execute `env\Scripts> ./spyder.exe`,
2. open Anaconda prompt, `activate env`, then `spyder`

Where `env` is the conda environment directory

### What is the expected output? What do you see instead?

1. ` ImportError: DLL load failed: The specified module could not be found.`
With the last line in the traceback below.with the original troublemaker being `import zmq`
`File "...env\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,`
2. `ModuleNotFoundError: No module named 'textdistance'` which comes from here:
`File "...env\lib\site-packages\spyder\plugins\editor\panels\utils.py", line 15, in <module>
    import textdistance`

## Versions

* Spyder version:   4.2.1
* Python version: 3.6.12
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by btmmf** [comment]
## Workaround

Don't update spyder to 4.2.1

The environment update included this:
`spyder  {4.2.0 (defaults/win-64) -> 4.2.1 (defaults/win-64)}`
I rolled back the update by explicitly specifying the spyder version in `environment.yml` to `spyder=4.2.0`, such that the next environment update included the rollback:
`spyder  {4.2.1 (defaults/win-64) -> 4.2.0 (defaults/win-64)}`

Now spyder works again.

**Comment by 9harshit** [comment]
on terminal run the command 'conda install -f python.app'

**Comment by btmmf** [comment]
> on terminal run the command `conda install -f python.app`
> And then launch again

That doesn't make any sense to me for two reasons:
1. What does the `-f` stand for?
It is not listed in the [documentation for `conda install`](https://docs.conda.io/projects/conda/en/latest/commands/install.html#conda-install)
2. This package is not available to me.
     - There's [no package with the name `python.app` available for windows from anaconda](https://anaconda.org/search?q=platform%3Awin-64+python.app). 
     - Packages with that name are only available for OSX-64.
     - Most of the packages with that name share the same description  
       > Proxy on **macOS** letting Python libraries hook into the GUI event loop

Please elaborate.

**Comment by 9harshit** [comment]
> > on terminal run the command `conda install -f python.app`
> > And then launch again
> 
> That doesn't make any sense to me for two reasons:
> 
> 1. What does the `-f` stand for?
>    It is not listed in the [documentation for `conda install`](https://docs.conda.io/projects/conda/en/latest/commands/install.html#conda-install)
> 2. This package is not available to me.
>    
>    * There's [no package with the name `python.app` available for windows from anaconda](https://anaconda.org/search?q=platform%3Awin-64+python.app).
>    * Packages with that name are only available for OSX-64.
>    * Most of the packages with that name share the same description
>      > Proxy on **macOS** letting Python libraries hook into the GUI event loop
> 
> Please elaborate.

Just try this :

uninstall pyQt using
conda uninstall pyqt

uninstall sip package
conda uninstall sip

then install these packages in following order
conda install sip

conda install pyqt

conda upgrade spyder

**Comment by btmmf** [comment]
> Just try this :
> 
> uninstall pyQt using
> conda uninstall pyqt
> 
> uninstall sip package
> conda uninstall sip
> 
> then install these packages in following order
> conda install sip
> 
> conda install pyqt
> 
> conda upgrade spyder

I'm afraid this is not really an option for me.
This is just another workaround and I already have one. I need this to work out of the box from the `environment.yml` definition.
If I need to manually re-install dependencies, then there's no point in using environments - and/or something's wrong in how spyder gathers dependencies.
This might very well be `conda`'s fault.
This is supposed to be a productivity tool, not a "_Yo, we haven't touched the minor version, (let alone the major), just did a +1 on the patch and now you have to reinstall some dependencies manually in some specific order._"-tool.

But thanks anyway.

The only real solution for me would be to be able to go back from ` - spyder=4.2.0` to just  ` - spyder`, when a newer version is available that fixes the dependency problems.

**Comment by 9harshit** [comment]
> > Just try this :
> > uninstall pyQt using
> > conda uninstall pyqt
> > uninstall sip package
> > conda uninstall sip
> > then install these packages in following order
> > conda install sip
> > conda install pyqt
> > conda upgrade spyder
> 
> I'm afraid this is not really an option for me.
> This is just another workaround and I already have one. I need this to work out of the box from the `environment.yml` definition.
> If I need to manually re-install dependencies, then there's no point in using environments - and/or something's wrong in how spyder gathers dependencies.
> This might very well be `conda`'s fault.
> This is supposed to be a productivity tool, not a "_Yo, we haven't touched the minor version, (let alone the major), just did a +1 on the patch and now you have to reinstall some dependencies manually in some specific order._"-tool.
> 
> But thanks anyway.
> 
> The only real solution for me would be to be able to go back from ` - spyder=4.2.0` to just ` - spyder`, when a newer version is available that fixes the dependency problems.

I understand that. Many people are skeptic to update using `conda` due to this reason. Even I suffered from the attack of `conda update`

But now Spyder's official recommendation is to use as a separate application from Anaconda. So maybe try that and visit Spyder's official website

**Comment by ccordoba12** [comment]
Closing because this is not a problem we can solve here. Please report it on:

https://github.com/ContinuumIO/anaconda-issues/
