### ISSUE TITLE
jjnnnnnnnnnnnnnnnnnnnnn

### ISSUE THREAD

**Issue by garvit997** [spyder-ide/spyder#14862]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @garvit997, please **stop** opening issues with no proper title (this issue has no content whatsoever either).

If you open one more issue like this, I'm afraid I'll have to ban you from our organization for one week.
