### ISSUE TITLE
Outline GUI not working in `__init__.py` of a module

### ISSUE THREAD

**Issue by real-yfprojects** [spyder-ide/spyder#14871]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``pip install -U spyder``
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Retried in a new development environment
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am currently writing an python module in a spyder project. The `__init__.py` files classes aren't shown in the outline. I am not able to find any error message in the debug output.
If I rename the file to `test.py`, the outline immediately shows the classes as intended. After renaming the file back to `__init__.py` the outline doesn't show any classes again.
Outside a spyder project the outline works for the file. When I open the file in a different project it doesn't work.

After testing the things above I closed the project - and the outline didn't work, even after reopening the file.

I am therefore not able to postulate a rule when the problem occurs. It seems like it is more likely to occur within spyprojects.

#### Update 1
When looking at some code in the spyder repository I had this issue with other files as well. [One][1] didn't work even after renaming, the outline showed its loading animation. Another [file][2] worked after placing the cursor inside the linked line.

[1]: https://github.com/spyder-ide/spyder/blob/5eef7ad7c4d903c22cb77f19b67b930157f307b6/spyder/plugins/completion/languageserver/plugin.py
[2]: https://github.com/spyder-ide/spyder/blob/5eef7ad7c4d903c22cb77f19b67b930157f307b6/spyder/plugins/outlineexplorer/plugin.py#L49

### What is the expected output? What do you see instead?
<details><summary>I see:</summary>

![grafik](https://user-images.githubusercontent.com/62463991/110015546-e08f2a80-7d1b-11eb-8d8f-8f02e9c1ce1e.png)
</details>

<details><summary>I expect something like that:</summary>

![grafik](https://user-images.githubusercontent.com/62463991/110016200-ad00d000-7d1c-11eb-8dcb-7b1f92179740.png)
</details>

## Versions

* Spyder version: 4.2.3 [Spyder 5.0.0.dev0 (Commit: 670613c98)]
* Python version: 3.8.5 64-bit
* Qt version: 5.12.10
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Linux 5.4.0-66-generic

<details> <summary>Dependencies</summary>

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.7.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.3 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  53.1.0 (OK)
sphinx >=0.6.6                  :  3.4.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  1.5.4 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

# Spyder plugins:
spyder_memory_profiler          :  0.2.1 (OK)
```
</details>

**Comment by cdfredrick** [comment]
I have the same problem. When looking at an __init__.py file in the editor, the outline pane does not display any variables, functions, or classes. Special comments "# ----" and cells "# %%" do still appear in the outline, but cell hierarchy is flattened ("# %%%" does not appear nested beneath "# %%" in the outline). Using Spyder 5.0.1, Python 3.8.5 64-bit, Qt 5.9.7, PyQt5 5.9.2, Windows 10

**Comment by real-yfprojects** [comment]
I am able to reproduce the problem on the same machine but reliable even with the newest main version of Spyder *(6.0.0.dev0 - Revision 474057d0b)*.

1. I cloned [this repository](https://github.com/real-yfprojects/ectec/tree/53bc1eabbb6d20ce31541efabc834e64f1e1191d) and switched to the develop branch. 
2.  I created a new project from the existing repository directory. 
3. I opened [this file](https://github.com/real-yfprojects/ectec/blob/53bc1eabbb6d20ce31541efabc834e64f1e1191d/python/ectec/src/__init__.py) called `__init__.py`. 
<details> <summary>The outline shows this.</summary>

<img src="https://user-images.githubusercontent.com/62463991/118130798-4d463580-b3ed-11eb-9125-b25e657d58d5.png" width="300">
</details>

4. I closed the project in spyder.
5. I opened the file again.
<details> <summary>The outline now shows this.</summary>

<img width="300" src="https://user-images.githubusercontent.com/62463991/118131250-d2314f00-b3ed-11eb-92f4-335a6522d092.png"/>
</details>
