### ISSUE TITLE
what is the spyder light theme?

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#14877]
I am using vscode and I was used to spyder light theme so much, but I cannot find it in vscode themes. There are too many themes in vscode, but sadly, none is similar to spyder light theme.
I appreciate it if anyone can tell me more about the spyder light theme and if there is any way to use it other APIs?

**Comment by juanis2112** [comment]
Hi @seyeet. We did not create Spyder's light theme. It is based on Qt's Fusion theme https://doc.qt.io/qt-5/qtquickcontrols2-fusion.html. I don't think it can be used for VSCode.
