### ISSUE TITLE
failed in debug

### ISSUE THREAD

**Issue by shankyemcee** [spyder-ide/spyder#14882]
### What steps will reproduce the problem?

input_tensor, mask_tensor, output_tensor = batch_embedding

using spyder 4.2.0 with pytorch 1.6.0 cuda 10.2

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "C:\shankar\anaconda3\envs\spyder\lib\site-packages\spyder_kernels\comms\commbase.py", line 314, in _comm_message
    buffer = cloudpickle.loads(msg['buffers'][0],
ModuleNotFoundError: No module named 'torch'
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.9.2
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=4.7.7               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.2 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @shankyemcee, thanks for reporting. Unfortunately, the information you reported is not enough for us to reproduce your problem.

Please a complete and simple code example that generates this error after being evaluated in the console. Thanks!

**Comment by shankyemcee** [comment]
Hi...Here is the code i am executing:

# -*- coding: utf-8 -*-

import argparse
from Configs.ConfigHandler import ConfigHandler
from DataHandler.DataHandler import DataHandler
#from transformers import GPT2Config
from transformers import GPT2LMHeadModel, GPT2Tokenizer
import torch as th
#from tensorboardX import SummaryWriter
import datetime
import tensorflow as tf




if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--config_file", type=str, default='config.ini',
                        help="the .ini file containing all the model and program settings")
    parser.add_argument("--section", type=str, default='DEFAULT',
                        help="the section of config file")
    args = parser.parse_args()    
    
#load all the model configuration settings from the config file
    config=ConfigHandler.get_configs(filename=args.config_file,section=args.section)
    print(config)
    
    
    tokenizer = GPT2Tokenizer.from_pretrained(config['model'])

#add these tokens to the dictionary otherwise model considers [ENT] as 
#3 seperate tokens([,ENT,])

    tokenizer.add_tokens(['[ENT]', '[SEP]'])

#load the gpt2 model from transformers library
    
    model = GPT2LMHeadModel.from_pretrained(config['model'])

#resize the token embeddings since the model has two extra tokens added
    model.resize_token_embeddings(len(tokenizer))
    
    if config['stage'] == 2:
            model.load_state_dict(th.load(config['checkpoint_dir'] + config['model_checkpoint_file']))
    
    device = th.device(config['device'])
#load the model to the default gpu/cpu device specified in config    
    model.to(device)
# set the model to train mode    
    model.train()
    
    dataHandler = DataHandler()
    
#load the gold references file of the model for training    
    gold_train = dataHandler.get_gold_train(config)
    
    loss_function = th.nn.CrossEntropyLoss(reduction='none')

    optimizer = th.optim.Adam(model.parameters(), lr=float(config['learning_rate']))
    
    current_time = datetime.datetime.now().strftime("%Y_%m_%d_%H_%M_%S")
    writer = tf.summary.create_file_writer(config['log_dir'] + current_time)
    #writer.add_scalar('datetime of starting: ', current_time)
    
    for epoch in range(int(config['epochs'])):
        for row in range(len(gold_train)):
            batch_embedding = dataHandler.get_train_embedding(gold_train,config,tokenizer)        
            input_tensor, mask_tensor, output_tensor = batch_embedding
            input_tensor = input_tensor.to(device)
            mask_tensor = mask_tensor.to(device)
            output_tensor = output_tensor.to(device)
            
            optimizer.zero_grad()
            
#the input tensor can sometimes be smaller than the output tensor 
#or sometimes greater, but the model output will be of dimension equal
#to the model input and should match the size of output tensor before
#feeding to the softmax. Thus we concatenate and truncate by max sequence
#length to prevent the size of the tensor going over the max length
            model_input = th.cat([input_tensor,output_tensor],1)
            model_input = model_input[:,:int(config['max_length'])]

        # extract the predicted tensor and store in model_output
            model_output = model(model_input)[0]
            model_output = model_output[:,-output_tensor.shape[1]:,:].contiguous()
            loss_tensor = loss_function(model_output.view(-1,model_output.shape[2]),output_tensor.view(-1))
            
        #we multiply back the mask tensor to set all the extra pad tokens from the
        #input and caption tensors to 0 so they do no contribute towards the loss    
            loss_tensor = loss_tensor * mask_tensor.view(-1)
            loss_tensor = loss_tensor.sum()/loss_tensor.shape[0]
            loss_tensor.backward()
            optimizer.step()
            
            with writer.as_default():
                tf.summary.scalar('loss', loss_tensor.tolist(), step=epoch)
        print("epoch: " + str(epoch) + "  loss: " + loss_tensor.tolist())    
        th.save(model.state_dict(), config['checkpoint_dir'] + 'C2F_stage{}_epoch{}.pt'.format(config['stage'], epoch))

    writer.close()       
         


The model fails at the line:

**Comment by shankyemcee** [comment]
Here is the error message I get when i run the full program in execution mode:

RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 8.00 GiB total capacity; 6.24 GiB already allocated; 9.69 MiB free; 6.58 GiB reserved in total by PyTorch)

**Comment by ccordoba12** [comment]
Sorry but the last error message you posted implies that this is not an error in Spyder but one CUDA not finding enough memory in your GPU to run the computations you want.

Are you able to run your code outside Spyder? For instance, in a Jupyter notebook?

**Comment by shankyemcee** [comment]
Oh okay maybe my gpu has ran out of memory....I am able to run the code on a cloud cluster like compute canada using cuda....I was previously able to run on my system using cpu version of pytorch....I think my system might be just running out of gpu memory...Ok thanks
