### ISSUE TITLE
Spyder debugger sudden issue - Spyder 4.1.5

### ISSUE THREAD

**Issue by andrea83ny** [spyder-ide/spyder#14899]
## Problem Description
Hi, since a couple of days my Spyder 4.1.5 debugger has an odd problem.
It stops precisely at my breaking points, however, the IPython console does not let me code/write anything in there.
Please see my screenshot. This makes the debugger pretty much useless.
This has been happening since a couple of days.
Thanks
![spyder debugger issue](https://user-images.githubusercontent.com/61430203/110522292-bdc79200-80de-11eb-9094-66298600916a.PNG)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @andrea83ny,

Can you please update your Spyder to the latest version and let me know if the error persists?

**Comment by andrea83ny** [comment]
@steff456 trying to do it, but it seems something really hard to do ...

**Comment by ccordoba12** [comment]
Closing because this probably no longer applies to our latest version.
