### ISSUE TITLE
Allow wider file pane when IDE window in half-screen width

### ISSUE THREAD

**Issue by PanderMusubi** [spyder-ide/spyder#14890]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When Spyder IDE window is set to the half width of the screen, there is less space for the content in Spyder. However, the file edit pane should be allowed more space to display at least 80 characters width of source file.

### What steps reproduce the problem?

1. Start Spyder
2. Use window manager shortcuts to set the window to half the size of the screen
3. Move the pane separator to left and right in order to show more of the source file.

### What is the expected output? What do you see instead?

Not enough is shown, only about 63 characters in width.

## Versions

* Spyder version: 4.2.2 None
* Python version: 3.8.6 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.8.0-7630-generic

## Screenshots

![Screenshot from 2021-03-08 16-25-35](https://user-images.githubusercontent.com/198964/110342182-66b4b500-802b-11eb-8c4c-4267b362f005.png)

**Comment by PanderMusubi** [comment]
'Maximize current page' allow for this but changes the content of the Code Analysis pane.

**Comment by steff456** [comment]
Hi @PanderMusubi,

This is a known issue, what happens is that the Code Analysis pane has a lot of widgets in the toolbar so that unable you to shrink the left part more. If you don't need to use the Code Analysis pane please close it, and then you will be able to move it a little bit more. This is something we are working to fix in Spyder 5.

Thanks for reporting!
