### ISSUE TITLE
runfile('C:/Users/pavan kalyan/Desktop/untitled0.py', wdir='C:/Users/pavan kalyan/Desktop') i am not getting any output after this

### ISSUE THREAD

**Issue by pavan1585** [spyder-ide/spyder#14902]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by SofieLuffe** [comment]
Hi, I have the same problem. When I run a cell it just writes "runfile('/Users/sofiebechthougaard/Desktop/Python/StartPython.py', wdir='/Users/sofiebechthougaard/Desktop/Python')"

My cell code is: 
#%%
def hello():
    print("Hello, world!")
    

If I write hello() it will print "hello, world!" 

<img width="1433" alt="Screenshot 2021-06-27 at 15 35 32" src="https://user-images.githubusercontent.com/86559661/123546551-500ea700-d75d-11eb-9943-bf59e3c07872.png">

**Comment by dalthviz** [comment]
Hi @SofieLuffe in your case the thing is that you are defining a function so unless you call it you will not see any output (even if you run it as a code cell). To call it you run `hello()` in this case. Maybe what you want is to run the cell and see in the console the code that was run? If that's the case you can check in preferences (`Tools > Preferences` or the 🔧 wrench button):

![image](https://user-images.githubusercontent.com/16781833/123670174-36dd2780-d83d-11eb-9881-e2ee6a86d260.png)

Hope the info above helps :)

**Comment by SofieLuffe** [comment]
SOO HELPFULL! Thank u so much dalthviz!

**Comment by SofieLuffe** [comment]
Thank u dalthviz! that was a great help
