### ISSUE TITLE
wizcoin name for modules, import error

### ISSUE THREAD

**Issue by nilson-z** [spyder-ide/spyder#14907]
### What steps will reproduce the problem?

Created a module wizcoin.py

wizcoin.py

```
class WizCoin:
    def __init__(self, galleons, sickles, knuts):
        self.galleons = galleons
        self.sickles = sickles
        self.knuts = knuts
```

Then, in a blank file (in the same directory as wizcoin.py) in Spyder IDE:
```
import wizcoin
spam = wizcoin.Wizcoin(1, 1,  1)
```

AttributeError: module 'wizcoin' has no attribute 'WizCoin'

Note: I don't have third party wizcoin module installed. I am using spyder IDE through Anaconda Distribution. And I already ran the code in other IDEs such as Sublime Text 3 and Jupyter Notebook. No error was raised on neither of them.

The problem is I don't understand why is the error only raised on Spyder.

P.S: I changed the name of wizcoin.py to wiz_coin.py and it worked. No error was raised. Still don't understand why it didn't work with wizcoin.py

## Versions

* Spyder version: 4.2.3 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @nilson-z could you check if you can import `wizcoin` from the IPython console inside Spyder (even when renaming your file)? My guess is that somehow (maybe because of your PYTHONPATH or your selected interpreter inside Spyder?) your being able to load a module `wizcoin` from somewhere else (and then not taking your `wizcoin.py`). Maybe try to see if you can print the path to the module and verify if it is pointing to your file or a different file?

Seems like you found a workaround but let us know if the info above helps :)

**Comment by nilson-z** [comment]
When importing wizcoin with my file named as wiz_coin.py, the output was "ModuleNotFoundError". But, after renaming the wiz_coin.py file back to wizcoin.py and restarting the kernel everything worked. @dalthviz Thank you very much!
