### ISSUE TITLE
kernel crashing

### ISSUE THREAD

**Issue by pruthvisushanth** [spyder-ide/spyder#14919]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
![image](https://user-images.githubusercontent.com/73953312/110910495-6f610000-8337-11eb-8608-c9be5a51d94f.png)
kernel always crashes while restarting.

**Comment by juanis2112** [comment]
Hi @pruthvisushanth, we need more information in order to be able to help you. Please open another issue with all the information requested in the template.
