### ISSUE TITLE
Adding Vyper Support

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#14925]
## Feature Request - Vyper Ethereum Programming Language
I've  been a long time user of spyder-ide and use it almost everyday. I don't know if it's possible to include Vyper (which works almost identically to python) to the ide so that it could  compile the code and highlight syntactic errors and use it for testing with the spyder debgging tools.
Vyper is used to code smart contracts in ethereum which is basically kind of a class in python however it can be used to work with programmable money. 
I've asked myself  the devs there to include vy in conda, which they did recently, hoping that eventually it could help with my case to try and add it to the spyder ide.
I've include below some useful links on the topic below:
- [conda package](https://anaconda.org/conda-forge/vyper)
- [vy conda request](https://github.com/vyperlang/vyper/issues/2214)
- [docs](https://vyper.readthedocs.io/en/stable/)
- [vy on vs](https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-vyper)
- [vy resources](https://github.com/vyperlang/vyper/wiki/Vyper-tools-and-resources)

**Comment by ccordoba12** [comment]
Hey @kaleb-keny, thanks for reporting. This is a very interesting idea, but unfortunately we're too tied to Python and its ecosystem to go in this direction.

Thanks for the suggestion though.

**Comment by kaleb-keny** [comment]
no worries, was worth a shot, maybe some day. thank you.
