### ISSUE TITLE
error when starting Spyder "QWidget: Must construct a QApplication before a QWidget"

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder#14920]
## Problem Description
Spyder fails to start, whether from the command line, Windows Shortcut, or from within Anaconda Desktop.  

When I try to launch Spyder from the command line, I get the Spyder 4.3.2 Spyder splash screen (which goes away), but then Spyder never launches.  I cannot find it in Windows Task Manager during that time.  Then I get the following error message, and the console returns to the command prompt : 

    "QWidget: Must construct a QApplication before a QWidget"

I just updated Spyder to v4.3.2 (from v.4.2.1) on Windows 10, using "conda update conda", followed by "conda update spyder".  I installed PyQtChart 5.12, PyQtDataVisualization, and some other PyQt5 components after taht.  PyQtDataVisualization would not complete the installation due to a "file permissions error".  I tried it again from an Administrator console with the correct privileges, but that didn't work due to the same "file permissions error".  So I forced the installation of PyQtDataVisualization by specifying the "--user" option with pip.  

But after that Spyder doesn't start.  I just get a splash screen and it does not actually start.  There is no Python process running in Windows Task Manager.   Jupyter and other Anaconda applications start up fine, but not Spyder.  

## Versions

* Spyder version: 4.2.3
* Python version:  3.8.8
* Qt version:   PyQt5
* PyQt version:   5.15.4
* Operating System name/version:  Windows 10 Pro

pyqt                          5.12.3           py38haa244fe_7    conda-forge
pyqt5                        5.15.4                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.8.1                   pypi_0    pypi
pyqtchart                 5.12             py38h885f38d_7    conda-forge
pyqtdatavisualization-qt5 5.15.2                   pypi_0    pypi
pyqtwebengine        5.12.1           py38h885f38d_7    conda-forge

**Comment by juanis2112** [comment]
Hi @richdevboston thanks for reporting this. I think this error is likely caused because broke your environment by mixing packages from pip and conda. I suggest watching our video that explains how to deal with problems when mixing this packages.  https://youtu.be/Ul79ihg41Rs

**Comment by juanis2112** [comment]
Please let me know if this helps you solve your issue.

**Comment by richdevboston** [comment]
I am still debugging this problem.  My development is not dead in the water, because I have multiple environments where Spyder is still working fine.  My BASE environment is one of 2 or 3 environments where Spyder won't start completely.   I have projects in about 10 environments at various stages of developments, so I am reluctant to remove and reinstall Anaconda completely.   I don't know how to EASILY (automatedly) preserve / reinstall or recreate all my projects and environments once Anaconda is removed.  I am lazy and stubborn and want to fix my existing Anaconda installation (if possible.)  But having a corrupted BASE environment bugs me because I like doing most things in BASE and only use custom environments for "riskier" projects where I anticipate package dependency problems.  

If I compare the behavior of the "bad" environments where Spyder fails to start completely, I see several packages loading during the splash screen, but not all packages finish loading in the Splash screen.  I also monitor the Windows Task Manager to see two new Python kernels start and stop running (two Pythonw.exe processes).   The Splash screen shows messages:
0) "Initializing"
1) "Starting Code Completion Manager"... 
2) "Loading Help"

For the environments where Spyder starts up fine I see 
0) "Initializing"
1) "Starting Code Completion Manager"... 
2) "Loading Help"
...
3) "Loading iPython"
4) "Loading Projects"
5) "Loading Variable Explorer"
... etc.   (The rest of them flash by so fast I cannot read them all.

This brings me to ask if there is a "Startup Log" or Debug Mode" in Spyder that I can use to see where all the steps that happen when it starts successfully and when it fails to startup completely? 

I will try running a script to compare the packages in the environments that work with the ones that don't.    I'll report back any interesting anomalies.

**Comment by ccordoba12** [comment]
> This brings me to ask if there is a "Startup Log" or Debug Mode" in Spyder that I can use to see where all the steps that happen when it starts successfully and when it fails to startup completely?

@richdevboston, please open the Anaconda Prompt and run there

    spyder --debug-info verbose --debug-output file

and upload the file called `spyder-debug.log`, which is generated in the same directory where you started Spyder.

**Comment by gerazov** [comment]
Might be related - starting Spyder 5.0.0 I'm getting :

```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
```

Spyder does start so no biggy - there are no errors or warnings in the log file.

**Comment by ccordoba12** [comment]
That's a duplicate of issue #15163 and it'll be fixed in QDarkstyle (the package that it's generating that warning) after we release Spyder 5.0.1.

**Comment by dalthviz** [comment]
Closing due to lack of response and possible duplicate being resolved
