### ISSUE TITLE
Cannot display all uppercase variable

### ISSUE THREAD

**Issue by mIgLLL** [spyder-ide/spyder#14934]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Cannot display the variable that are all uppercase in the variable explorer!
such as ABC, BBB

### What steps reproduce the problem?

1. A=pd.DataFrame() # This is visiable!
2. AA=pd.DataFrame() # This is unvisiable!
3. AAa=pd.DataFrame() # This is visiable!

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.3
* Python version: 3.8.8
* Qt version: 
* PyQt version: 
* Operating System name/version: win 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @mIgLLL,

The variable explorer has the option to exclude the uppercase variables, in the cases where you don't want to see constants in there. If you want to show them please uncheck in the `hamburger menu > Exclude all-uppercase references` and you should be able to see them.

Thanks for reporting!
