### ISSUE TITLE
variable explorer didn't remove variable after restart kernel

### ISSUE THREAD

**Issue by jialunchen** [spyder-ide/spyder#14937]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @jialunchen, thanks for reporting. Unfortunately, you didn't post more information about your error so it's hard for us to know how to solve it.

So the only recommendation we can give you is to update Spyder with the following commands in the Anaconda Prompt or your system terminal

    conda update anaconda
    conda install spyder=4.2.3

**Comment by ccordoba12** [comment]
Closing due to lack of response.
