### ISSUE TITLE
object explorer change the size of whole window

### ISSUE THREAD

**Issue by Y-H-Joe** [spyder-ide/spyder#14954]
## Problem Description
my full screen shot:
![image](https://user-images.githubusercontent.com/28485220/111664929-48477a00-87e0-11eb-94de-88c46110293c.png)

when I choose "view with the object explorer" (or just double click it):
![image](https://user-images.githubusercontent.com/28485220/111665037-62815800-87e0-11eb-9c16-ed98af4a7c73.png)

suddenly become very small:
![image](https://user-images.githubusercontent.com/28485220/111665114-75942800-87e0-11eb-9f58-deece6a74852.png)

### What steps reproduce the problem?

please see above 

### What is the expected output? What do you see instead?
Expecting a seperate window when I want to view the object like in Spyder3.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Spyder version: 4.2.1
Python version: 2.7
Qt version: 5.9.7
PyQt version: 5
Operating System name/version: Mac Mojave

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Y-H-Joe, thanks for reporting.

@juanis2112 or @steff456, are you able to reproduce this on Mac?

**Comment by steff456** [comment]
I'm unable to reproduce this issue on Mac, it is working as expected

![image](https://user-images.githubusercontent.com/20992645/112067225-b7e99c00-8b35-11eb-8ec4-c924de0c06ed.png)

**Comment by ccordoba12** [comment]
Ok, the problem has to do with Mac adding related windows in tabs.

Unfortunately, there's nothing we can do about it @Y-H-Joe because that's a Mac feature, sorry.

**Comment by Y-H-Joe** [comment]
I solved it via rolling back to spyder3. Openning dataframe in spyder3 will not change size, and the auto-completion in spyder3 is much faster than spyder4 or 5. So I don't think this is a mac problem. my mac system is mojave 10.14.6.
