### ISSUE TITLE
File explorer should have an option called "Insert filename into code"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1495]
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2013-07-25T16:28:45Z_

The file explorer shall have an option (context menu) saying:

Insert into code.

This would do:

import os

os.path.joint('path', 'to', 'file).

A real ease for any quick work on input files!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1495_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T12:53:22Z_

Really cool proposal! It shouldn't be that hard to do if you would like to tackle it (unfortunately I don't have time to do it myself).

**Summary:** File explorer should have an option called "Insert filename into code"  \<span class="oldvalue"> (was: File explore shall have an option insert into code) \</span>  
  **Status:** HelpNeeded  
  **Labels:** -Type-Defect Type-Enh Cat-Miscelleneous

**Comment by goanpeca** [comment]
@dalthviz could you take a look at this one?

**Comment by dalthviz** [comment]
@goanpeca I'm not quite sure about what is the option to implemented. What will this functionality do?, Is something like copying the path of the file into the clipboard?.

**Comment by ccordoba12** [comment]
@dalthviz, I don't think this is useful anymore. Only one person has asked for something like this, and it's tied to Python.

(I know I said it was a cool proposal, but that was three years ago ;-)

**Comment by ccordoba12** [comment]
@goanpeca, if you want to look for things to assign our juniors to do, please look in the `3.x` milestone.

That's where I keep suggestions/bugs that I consider important. If it's not in that milestone, it's not that important.
