### ISSUE TITLE
Spyder does not detect virtual environments created after its installation

### ISSUE THREAD

**Issue by thistlillo** [spyder-ide/spyder#14959]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ X Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If you create a new conda virtual environmet after Spyder has run at least once, the new environment is not listed among the conda environment Spyder can use.

### What steps reproduce the problem?

1. On Windows 10 Pro, install the latest version of Spyder using the exe installer https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe
2. Run Spyder
3. Now create a new conda environment E.
4. In Spyder, open the menu "Tools", "Preferences"
5. Select Python Interpreter
6. Select the radio button "Use the following Python interpreter"
7. Open the drop-down list.
The new environment E is missing.

### What is the expected output? What do you see instead?
E in the list of available conda environments. I see only the environments created before the installation of Spyder,

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A
```

## Versions

* Spyder version: 4.2.4
* Python version: 3.8.3
* Qt version: Don't know
* PyQt version: 1.9.0
* Operating System name/version: Windows 10 Pro, 19042.867, Experience pack Windows Feature Experience Pack 120.2212.551.0

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree                    :  None (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  54.1.2 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog                        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.3 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

```

**Comment by juanis2112** [comment]
Thanks for reporting this @thistlillo. I can successfully reproduce this. Even after restarting it, it doesn't list the new environment created after launching it the first time.

See screenshot:
<img width="1393" alt="Screenshot 2021-03-19 at 7 02 11 PM" src="https://user-images.githubusercontent.com/18587879/111852774-42d45780-88e6-11eb-96ee-004daaf6b33a.png">

We will fix this in our next version.

**Comment by thistlillo** [comment]
Thank you.

**Comment by ccordoba12** [comment]
This is already fixed, so closing.
