### ISSUE TITLE
sypder 4 dark theme, the output in console is black, as well as the background color

### ISSUE THREAD

**Issue by Y-H-Joe** [spyder-ide/spyder#14953]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

sypder 4 dark theme, the output in console is black, as well as the background color
### What steps reproduce the problem?
![image](https://user-images.githubusercontent.com/28485220/111660795-6f9c4800-87dc-11eb-8508-7766e08b4216.png)

### What is the expected output? What do you see instead?
How can the output be white rather than black?

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 2.7
* Qt version: 5.9.7
* PyQt version: 5
* Operating System name/version: Mac Mojave

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Y-H-Joe, thanks for reporting. Did you import Sympy or Astropy before making the `a1=1` assignment?

**Comment by Y-H-Joe** [comment]
And I found how to

**Comment by Y-H-Joe** [comment]
And I found how to reproduce it.
Because the default spyder Mac anaconda install will be spyder3, when the user want to update the spyder3 to spyder4, he will click "install" from the anaconda navigator gui. However, the waiting time will be endless. So he will try to "conda install spyder=4.2.5" from command line, he will success, but when he opens the spyder4, the font color in console will be black. If he create a new environment with spyder initially installed to be version 4.2.5, everything would be normal.
So here are two issues, 
1. navigator gui install spyder4 will continue waiting forever
2. command line install spyder4 will cause unknown issues.

**Comment by Y-H-Joe** [comment]
I solved issue 2. User should "conda uninstall spyder" at first, then do "conda install spyder=4.2.5", and then" conda update spyder".
But still don't know about issue 1

**Comment by ccordoba12** [comment]
> navigator gui install spyder4 will continue waiting forever

Please report this to the Anaconda team:

https://github.com/ContinuumIO/anaconda-issues/

They are the ones who develop Navigator, so we can't help with that, sorry.

**Comment by ccordoba12** [comment]
And glad to know you were able to solve the issues with Spyder!
