### ISSUE TITLE
Spyder 4.2.4 for Windows ignores window sizing

### ISSUE THREAD

**Issue by SFMornay** [spyder-ide/spyder#14966]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just updated from 4,2,3 to 4,2,4 via pip. I'm using WIndows 10. When I start Spyder, it always opens in a maximized window. When I resize the window by dragging, it is not remembered (unlike all previous versions of Spyder that I have used) and the next time I start Spyder, either from a command prompt or a shortcut icon(with "normal window" specified) it starts again in a maximized window. When I click the "Restore Down" button in the window frame, the window shrinks to an arbitrary size that has nothing to do with my previous resizing. In  spyder.ini, both "window/is_maximized" and "window/is_fullscreen" remain "False". In transient.ini, the "window/position" and "window size" get resized to whatever Spyder arbitrarily wants, regardless of how I edit them. (But with 4.2.3, the window size and position are remembered and written properly to transient.ini as usual.)

### What steps reproduce the problem?

1. Starting and restarting Spyder
2. 
3. 

### What is the expected output? What do you see instead?
Window size is remembered. Instead, window size is not remembered.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.3
* Python version: 3.9.2
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: 
Windows 10 Pro / 2004
### Dependencies

```
PASTE DEPENDENCIES HERE
`
# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  49.2.1 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
``

**Comment by brhubbar** [comment]
This is very likely related to #14962

**Comment by ccordoba12** [comment]
Yep, it's most probably related to that issue. Thanks for noticing it @brhubbar!

Closing in favor of #14962.
