### ISSUE TITLE
Restore from autosave 

### ISSUE THREAD

**Issue by Sritej26** [spyder-ide/spyder#14969]
### What steps will reproduce the problem?

whenever i open spyder a pop up is appearing before start and it says restore from autosave

## Versions

* Spyder version: 4.1.5 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.21.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.8.1 (OK)
pylint >=1.0                   :  2.7.2 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.0.2 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.5.2 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.22 (OK)
matplotlib >=2.0.0             :  3.3.4 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.2.3 (OK)
scipy >=0.17.0                 :  1.6.1 (OK)
sympy >=0.7.3                  :  1.7.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Sritej26, please press the `Discard` button placed on the right of that window to avoid showing that windows in the next Spyder session.

**Comment by ccordoba12** [comment]
You can't send photos to Github from your email. Instead, you need to drag and drop them here.

**Comment by Sritej26** [comment]
![IMG_20210323_193106](https://user-images.githubusercontent.com/54658086/112373910-79a3d680-8d07-11eb-97e4-08d17268491b.jpg)

**Comment by Sritej26** [comment]
The above pop up appears when ever I start Spyder.
The only buttons I can click on that are close or cancel after that spyder will open. And this is being continued whenever I close and start spyder back again

**Comment by ccordoba12** [comment]
Please make that dialog bigger and with the horizontal scrollbar show above the `Cancel` button, please move to the right of the content inside the dialog to find the `Discard` button I told you about.

**Comment by Sritej26** [comment]
Hi, that dialog box is size constrained can't expand it either. 
![image](https://user-images.githubusercontent.com/54658086/112423981-a08af880-8d59-11eb-9523-21955b963b2a.png)

**Comment by ccordoba12** [comment]
I think this is a problem with your computer because we don't constrain the size of that dialog. So the only solution we can give you is to find a directory called `.spyder-py3` under your Users home directory (`C:\Users\<your user name>`) and remove it.

That will wipe out your Spyder settings but at the same time avoid the appearance of that dialog.

**Comment by Sritej26** [comment]
Thank you so much for your quick replies,
I found a folder called autosave in that directory. By deleting .py files
in that folder, the issue is resolved.
