### ISSUE TITLE
Console Problem

### ISSUE THREAD

**Issue by KarenPHS** [spyder-ide/spyder#14976]
Versions
Spyder version: 4.1.5
Operating System: Windows 10

I just install Anaconda. When I use the default settings below, everything works fine.
```
(Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython 7.19.0 -- An enhanced Interactive Python.
```

But when I run "conda create -n py36 python=3.6 spyder-kernels" to create env and then use it, the console shows the message below.

```
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.4 and < 1.10.0). Without this module is not possible for Spyder to create a console for you.
You can install it by running in a system terminal:
conda install spyder‑kernels
or
pip install spyder‑kernels
```

What should I do to solve the problem? Thank you.

**Comment by ccordoba12** [comment]
Hey @KarenPHS, thanks for reporting. This part of the message is the key to understand your problem:

> Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 1.9.4 and < 1.10.0)

That means that you don't have the right version of `spyder-kernels` in your environment to work with Spyder 4.1.5.

To fix that, please open the Anaconda Prompt and run there

    conda activate py36
    conda install spyder-kernels=1.9.4

That should fix your problem.

**Comment by KarenPHS** [comment]
Thank you. The problem is solved.
