### ISSUE TITLE
spyder is unable to show the variable you are trying to view because the module azureml was not found

### ISSUE THREAD

**Issue by JamiVaraPrasad** [spyder-ide/spyder#14972]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi there,
I couldn't see the contents of a variable in Variable explorer.
Giving below error:
![image](https://user-images.githubusercontent.com/42294529/111891940-11977c80-89f7-11eb-9ab1-2091f094f96c.png)
Though I could see azureml in files
![image](https://user-images.githubusercontent.com/42294529/111892008-a13d2b00-89f7-11eb-9319-1297f83b940b.png)

I followed the below link to create a new environment for azureml - (modular approach)
https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

### What steps reproduce the problem?

1. Create a new environment
2. Activate new environment
3. install azureml-sdk
4. install spyder-kernel
5. Deactivate new environment
6. Goto (base) anaconda environment
7. launch spyder
8. change IPython Interpreter to point to the Python.exe file in new environment
9. restart kernel
10. from azureml.core module import Workspace class
11. Try to veiw content of Worskspace class in variable explorer by double clicking

### What is the expected output? What do you see instead?
The content of Workspace class
![image](https://user-images.githubusercontent.com/42294529/111892264-0f82ed00-89fa-11eb-93b5-1dfbcd12d36e.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.5 
* Qt version: 5.9.7
* PyQt version:  5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by JamiVaraPrasad** [comment]
I could see the contents of the variable if I install spyder separately in the new environment (Naïve approach)
![image](https://user-images.githubusercontent.com/42294529/111892594-27a83b80-89fd-11eb-9272-c9ac2e5e2945.png)

**Comment by ccordoba12** [comment]
Hey @JamiVaraPrasad, thanks for reporting. The only to follow this approach

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

and view your objects is (as you already found) to install `azureml-sdk` in the same environment as Spyder is installed. This is basically what our message is telling you:

![imagen](https://user-images.githubusercontent.com/365293/111892875-2e1ebf00-89cd-11eb-8f62-6d7b72f784aa.png)

This is a Python limitation and for now there's nothing we can do about it, sorry.
