### ISSUE TITLE
pip install spyder missing rtree requirement

### ISSUE THREAD

**Issue by jaxankey** [spyder-ide/spyder#14995]
## Problem Description

I found that installing into a new conda environment with pip brought up the following: 
![image](https://user-images.githubusercontent.com/8275367/112183813-fd10db00-8bd4-11eb-9188-5f0caede7dcd.png)

### What steps reproduce the problem?
From the anaconda prompt,

1. conda create --name test
2. conda activate test
3. pip install spyder
4. spyder

### What is the expected output? What do you see instead?

Spyder should launch normally. It almost does, with the above error.

## Versions

* Spyder version: 4.2.4
* Python version: 3.9.2
* Qt version: 5 something (current version as of 2021-03-23)
* PyQt version: 5.12.3
* Operating System name/version: Linux Mint or Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  None (NOK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  None (NOK)

**Comment by jaxankey** [comment]
Also, when I load spyder on Windows, I get this in the terminal area (even after pip install rtree):

Traceback (most recent call last):
File "c:\users\jack\miniconda3\envs\test\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users\jack\miniconda3\envs\test\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\spyder_kernels\console\start.py", line 284, in main
kernel.initialize()
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\traitlets\config\application.py", line 87, in inner
return method(app, *args, **kwargs)
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\ipykernel\kernelapp.py", line 570, in initialize
self.write_connection_file()
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\ipykernel\kernelapp.py", line 230, in write_connection_file
write_connection_file(cf, ip=self.ip, key=self.session.key, transport=self.transport,
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\jupyter_client\connect.py", line 136, in write_connection_file
with secure_write(fname) as f:
File "c:\users\jack\miniconda3\envs\test\lib\contextlib.py", line 117, in __enter__
return next(self.gen)
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\jupyter_core\paths.py", line 461, in secure_write
win32_restrict_file_to_user(fname)
File "c:\users\jack\miniconda3\envs\test\lib\site‑packages\jupyter_core\paths.py", line 387, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.

**Comment by steff456** [comment]
Hi @jaxankey,

This normally happens when you start to mix pip with conda, for now we are working towards adding `rtree` to our `setup.py`. Also we are waiting to have `rtree` wheels on pip to add them as well. For now, please wait for Spyder 4.2.4 to be available as a package in conda.

**Comment by jaxankey** [comment]
All good, and sorry if this was covered before (I only searched "open"). 

My motivation for doing this is pip has more packages (several we need) and the installs from pip are much faster / lighter weight. Would greatly ease our distribution.

We will keep using conda for now!

**Comment by jaxankey** [comment]
(Conda is great for being self-contained and its environment management, but pip is great for everything else, almost. Conda seems to routinely break if it's a year old or so.)

**Comment by steff456** [comment]
We hope to be fixing this issue soon, sync new dependencies is not always as easy as we want to.

**Comment by jaxankey** [comment]
No worries! Just providing a data point. 🙂
________________________________
