### ISSUE TITLE
When Kite is enabled, disabling "Show Calltips" has no effect.

### ISSUE THREAD

**Issue by kbauer** [spyder-ide/spyder#15007]
### What steps will reproduce the problem?

It looks like Kite causes the "Show calltips" setting to be ignored.

1. Disable Kite in *Preferences > Completion and Linting > Advanced*.
2. Enable Calltips in *Preferences > Completion and Linting > Introspection*.

3. Type

        import numpy # Press F5
        numpy.array(
    
    Now a calltip should be shown.
    
4. Disable Calltips. Typing the same again should not not show a calltip.
5. Enable Kite. Now calltips will be shown again.

## Versions

* Spyder version: 4.2.4 
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 4.12.14-lp151.28.52-default

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.19.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  21.4.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.7.2 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  50.3.1.post20201107 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  0.10.3 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  19.0.2 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.2 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @kbauer, thanks for reporting. This should be fixed in Spyder 5, to be released next week.

Please let us know if that's the case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by ccordoba12** [comment]
Sorry, Spyder 5 is out, please try it and let us know if it works for you.

**Comment by kbauer** [comment]
Cannot provide feedback, because a series of dependency issues prevents starting Spyder 5.

Installed with `conda`, see https://stackoverflow.com/questions/66958984/spyder-5-laughing-error-modulenotfounderror

Installed with `pip3`, it reports several missing dependencies and the layout is heavily distorted (large empty space around each icon).

**Comment by ccordoba12** [comment]
Please install Spyder in a clean env and try again. The space around icons was added by us to make our toolbars accessible.

If you don't want to update to Spyder 5, please close this issue because we can't fix it in Spyder 4.

**Comment by ccordoba12** [comment]
And about the missing dependencies you're probably seeing with pip, one is a false alarm (see #15091) and the other (rtree) is reported when you use pip in Anaconda, but you can safely ignore it for now (we'll fix that in a future version)

**Comment by kbauer** [comment]
I tried running with 

    conda create --prefix /tmp/spyder python=3.9 spyder=5.0.0
    conda activate /tmp/spyder
    spyder --safe-mode

"Show Calltips" now correctly disables also calltips when Kite is enabled.

However, in return when disabling

    Preferences > Completion and linting > General > Provides > Enable Kite provider

neither completions nor calltips are shown *at all*.

![image](https://user-images.githubusercontent.com/7498468/113852865-4c423880-979d-11eb-9699-ae6398c08829.png)

# Side remarks

While testing I ran into additional issues. (Sorry for not listing them separately, I'm short on time this week)

## matplotlib

When creating the environment as described above, I am greeted with a console that tells me, that it won't work without installing matplotlib. Should it maybe be listed as dependency of Spyder?

## About the icons

> The space around icons was added by us to make our toolbars accessible.

I understand the accessibility argument, but for everyone who doesn't need it, using up a lot of screen space is a disadvantage and it should be possible to select "small icons" or similar.

## Broken layout of menu icons

![image](https://user-images.githubusercontent.com/7498468/113853978-9d9ef780-979e-11eb-97ef-fe544503fd08.png)

Same issue across all menu items with icons, in both menu bar and right-click context menus.

# Dependencies Listing of the environment

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Closing because this is quite old now. Hopefully you managed to solve this problem.
