### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Laiaborrell** [spyder-ide/spyder#15011]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Double clicking to open a variable in the variable explorer.

**Comment by ccordoba12** [comment]
Hey @Laiaborrell, thanks for reporting. Please open the Anaconda Prompt and run there

    conda install spyder=3.3.6

That should fix your problem, although without knowing more it it's really hard for us to tell what's happening in your case.
