### ISSUE TITLE
spyder requires qtconsole >= 5.0.3, but highest version available in conda is 5.0.2

### ISSUE THREAD

**Issue by gica3618** [spyder-ide/spyder#15020]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Upon startup, the following error message appears:
You have missing dependencies!
Mandatory:
qtconsole >=5.0.3 : 5.0.2 (NOK)
Please install them to avoid this message.
Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you to install all the listed missing dependencies.
Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.

## Versions
```
* Spyder version: 4.2.4
* Python version: 3.9.2 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Linux 4.15.0-122-generic 
```

## Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.2 (NOK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  None (NOK)
```
As can be seen from the dependencies, spyder requires qtconsole >=5.0.3. However, `conda search -f qtconsole` reveals that the highest version available is 5.0.2. The [qtconsole docs](https://qtconsole.readthedocs.io/en/stable/index.html) say that the latest release is 5.0.3. Is this just an issue with conda not having the latest version yet?

**Comment by leavor** [comment]
I also encountered the same problem.
I use the following method to solve.
```
conda install qtconsole=5.0.3
```

**Comment by ccordoba12** [comment]
Hey @gica3618, thanks for reporting. I'll inform the Anaconda team about this problem so they can fix it as soon as possible.

**Comment by Dan-Patterson** [comment]
same with python 3.7 and windows setup

(arcgispro-py3) C:\arc_pro\bin\Python\envs\arcgispro-py3>conda install qtconsole=5.0.3 --dry-run
Fetching package metadata .............

PackageNotFoundError: Packages missing in current channels:

  - qtconsole 5.0.3*

Maybe it was removed.

**Comment by ccordoba12** [comment]
Nop, it haven't been added.

**Comment by SlimShadys** [comment]
I was able to fix this problem, by running:
`conda install -c conda-forge qtconsole`

The updated qtconsole lib (5.0.3) can be found here: https://anaconda.org/conda-forge/qtconsole

**Comment by Dan-Patterson** [comment]
@ccordoba12 
you can close...
All the updates are available on the main anaconda site today

**Comment by ccordoba12** [comment]
Thanks for the update!
