### ISSUE TITLE
Speach recognition

### ISSUE THREAD

**Issue by Nenem-Talom** [spyder-ide/spyder#15035]
I have python 3.9.2 installed in my PC and i cannot install Speach Recognition using 'pip install SpeachRecognition'. It says:
Note: you may need to restart thr kernel to use updated package which i already did.
ERROR: Could not find a version that satisfies the requirement SpeachRecognition
ERROR No matching distribution found for SpeachRecognition.
Please help me with some suggestions.

**Comment by ccordoba12** [comment]
Hey @Nenem-Talom, thanks for reporting. Unfortunately this is a problem with the package you're trying to use and not with Spyder. So we can't help you with it, sorry.
