### ISSUE TITLE
Unable to restart Kernel

### ISSUE THREAD

**Issue by EnderWiggin14** [spyder-ide/spyder#15047]
### What steps will reproduce the problem?

Unfortunately, I do not know what series of actions prevents the use of the kernel restart function. I don't use it enough to pay attention. However, it has happened a number of times to me.

## Versions

* Spyder version: 4.2.3 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  51.0.0 (OK)
sphinx >=0.6.6                  :  3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.4 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)
```

**Comment by steff456** [comment]
Hi @EnderWiggin14,

Did you had any error message on Spyder? Or this issue is about a current behavior of Spyder? Please post a screenshot or gif of what you are seeing that you are not expecting.

**Comment by EnderWiggin14** [comment]
I cannot provide screen shot at this moment. I needed to restart Spyder in order to restart the kernel because I needed to reset variables, clear the console, reset the console line to [1], and most importantly reload the available python packages because I had just installed a new package.

What I did was attempt to use the drop down menu at the top-right corner of the console/terminal to select "restart kernel." Upon selecting "restart kernel" I'm prompted to verify that I do in fact want to restart the kernel. I select yes only to be met with absolutely nothing occurring as a result of me trying to restart the kernel. No error was thrown. It acted like if one called the following function,

```
def do_nothing():
    return
```

**Comment by ccordoba12** [comment]
Hey @EnderWiggin14, this problem is fixed in our latest version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=4.2.5

**Comment by BjornFJohansson** [comment]
I have this problem in 5.0.1 on linux mint running on anaconda.

**Comment by ccordoba12** [comment]
Closing because this probably no longer applies to our latest version.
