### ISSUE TITLE
I can't install Kite

### ISSUE THREAD

**Issue by cecustodioc** [spyder-ide/spyder#15057]
### What steps will reproduce the problem?

I try to install Kite in Ubuntu Linux 20.04 con Spider 4, Python 3.8.5 and Ipytho 7.20.0

## Versions

* Spyder version: 4.2.3 
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.8.0-48-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  18.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.6.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.0 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  45.2.0 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.26 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.3.3 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.2.2 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @cecustodioc,

What error are you finding when trying to install Kite?

**Comment by cecustodioc** [comment]
Only reach the 87% of the process, and fail.
I install every prerrequisite of the app, but not work properly.

**Comment by cecustodioc** [comment]
[image: Error install kite by cmd line.png]
[image: Error Kite! 30032021.png]
I try to complete installation by two methods (cmd line and Spyder IDE)
with the same result.


Carlos Ernesto Custodio Cadena.
Este mensaje se dirige exclusivamente a su destinatario y puede contener
información privilegiada o CONFIDENCIAL. Si no es Ud. el destinatario
indicado, queda notificado de que la utilización, divulgación o copia sin
autorización está prohibida en virtud de la legislación vigente. Si ha
recibido este mensaje por error, se ruega lo comunique inmediatamente por
esta misma vía y proceda a su destrucción.
This message is intended exclusively for its addressee and may contain
information that is CONFIDENTIAL and protected by professional privilege.
If you are not the intended recipient you are hereby notified that any
dissemination, copy or disclosure of this communication is strictly
prohibited by law. If this message has been received in error, please
inmediately notify us via e-mail and delete it.

**Comment by steff456** [comment]
Hi @cecustodioc,

Can you please open this issue in the Kite repository, https://github.com/kiteco/issue-tracker. As this is their error there's not much that we can do about it.

Thanks for reporting!

**Comment by cecustodioc** [comment]
> Hi @cecustodioc,
> 
> Can you please open this issue in the Kite repository, https://github.com/kiteco/issue-tracker. As this is their error there's not much that we can do about it.
> 
> Thanks for reporting!

I am in the unsupported minority, I will be await, thank's

**Comment by ccordoba12** [comment]
Sorry that you feel that way @cecustodioc. The problem is that we can't help you to solve Kite installation issues because we don't create it. We simply promote it among our users as an alternative to have better code completions in our editor.

So, if you're unable to install Kite, you need to report it in the link @steff456 posted above so you can receive proper support for that.
