### ISSUE TITLE
Please close all Serial sessions on Abnormal Program Termination? Spyder 4.x

### ISSUE THREAD

**Issue by dougshade** [spyder-ide/spyder#15061]
When my program terminates abnormally  _(frequently... MY problem not Python's nor Spyder's_) all the serial connections the program opened at run start... stay open.  On re-run... I can not re-establish serial sessions as the port was not previously released.

Is there a switch / control / feature in Spyder where all serial sessions are CLOSED on any program termination?

CTRL + . in the Console restarts the Kernel... but is slow.

(LiClipse shut down all Serial connections on any termination and I didn't realize how needed this feature was... until it was gone.)

Cheers! Doug

**Comment by ccordoba12** [comment]
Hey @dougshade, what do you mean exactly by serial connections?

**Comment by dougshade** [comment]
Early in the program....
import serial
ser = serial.Serial(
    port='COM20',
    baudrate=115200, 
    timeout=1,
    parity=serial.PARITY_NONE,
    stopbits=serial.STOPBITS_ONE,
    bytesize=serial.EIGHTBITS
    )

in the middle of the program.... some of my (errant) code causes abnormal termination of program which prevents the "clean up" portion of my code from running: specifically:

ser.close()

So... the Kernel still has an open serial COM port. 

Re-execution of the program fails now... because the COM port has not been released.

Restarting the kernel is a slow work around.
typing ser.close() in the iPython console works only sometimes (weird)

LiClipse IDE apparently closed all open serial connections at program termination... regardless of how it terminated.

**Comment by dougshade** [comment]
(just 6 hours or so of stick time with Spyder... so probably overlooking some feature)

**Comment by impact27** [comment]
I have a similar problem but I don't think we can do anything.
What happens with me:
 - I open a kernel, open a serial connection
 - The program crashes, so can't close the serial connection properly.

At that point it is up to the OS to notice that the program that opened the serial connection is dead. Unfortunately Windows doesn't appear to do that. What I do is:
 1. Close the kernel, open a new one, connect, it fails
 2. Close the kernel, open a new one, connect, it succeeds 

I guess the OS is resetting something during the first try.

**Comment by dougshade** [comment]
The IDE I was previously using (LiClipse) apparently was handling all of this in the background for me. When I changed over to Spyder (which I like for other reasons) is causing me all manner of grief. Like you... I have to keep resetting the kernel. (Or typing ser.close() in the iPython console... but even that only works "sometimes". There is a bug in here somewhere... and I can't get consistent behavior to help with the debug.

**Comment by impact27** [comment]
What do you mean exactly by "Abnormal Program Termination"? Is it just an exception but the kernel is still running? (The "In[]" prompt didn't reset)
In that case I am not sure the closing should happen at the spyder level (not everyone would want to have their serial connection randomly closed.)
I would advise that you add to your code:
```
try:
    # Here your code that might crash
except Exception:
    ser.close()
```

**Comment by ccordoba12** [comment]
I agree with @impact27, this is not something we can solve here, sorry.
