### ISSUE TITLE
Syntax highglight changes are not applied on Mac

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1507]
_From [djhock...@gmail.com](https://code.google.com/u/101178012149633210735/) on 2013-08-03T16:13:59Z_

Spyder Version:  2.2.0
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Darwin

Macbook Pro OS 10.8.4

When I change the syntax highlighting in the preferences the apply button doesn't become available. If I click ok, the color doesn't change. I would like to use Spyder/dark or Emacs.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1507_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T19:36:04Z_

Thanks for reporting and for your interest in Spyder. It's very strange that it's not working as expected.

I'll take a look it this weekend.

**Summary:** Syntax Hihglight changes are not applied on Mac   \<span class="oldvalue"> (was: Syntax Hihglight problem on Mac ) \</span>  
  **Labels:** Cat-Editor OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-02T05:57:12Z_

I tested this in our Mac application and everything is working fine, i.e. color scheme is applied correctly to the Editor.

I have two questions for you:

1. How did you install Spyder?

2. Removing our preferences with

rm -Rf ~/.spyder2

and restarting does help?

**Summary:** Syntax highglight changes are not applied on Mac   \<span class="oldvalue"> (was: Syntax Hihglight changes are not applied on Mac ) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [djhock...@gmail.com](https://code.google.com/u/101178012149633210735/) on 2013-09-02T10:30:07Z_

I used the dmg file from the website to install ( https://code.google.com/p/spyderlib/downloads/detail?name=spyder-2.2.1.dmg&can=2&q= ). I had version 2.2.0. I tried running rm -Rf ~/.spyder2 in the terminal and restarting but it didn't help. I updated to v2.2.1 via the link above with .dmg installer but still had no luck.

I tried changing the colors in custom but that didn't do anything. If I manually change the colors in the Spyder color options, it is effective in changing the colors. I just cant' switch to any of the other themes.

I can try install spyder via Macports if you think that would help. The workaround for now could be to manually copy and paste each color from Spyder Dark to Spyder.

Let me know if you need more info regarding settings or anything.

Thanks,
Dan
***************************************************
Daniel Hocking
djhocking@gmail.com http://www.nerunningservices.com http://danieljhocking.wordpress.com/ ***************************************************

**Comment by ccordoba12** [comment]
Well, this was fixed in 2.3.5.2

**Comment by RogelioRodriguez** [comment]
I FIGURED OUT THE SOLUTION
When you are in color scheme editor and after you make the changes and hit ok it appears as though the preferences window closes too but it does not! It is hiding behind the Spyder window so just move it out of the way and hit apply to apply the changes.
You're welcome
