### ISSUE TITLE
spyder /bin/bash: pip: command not found

### ISSUE THREAD

**Issue by kellylizi** [spyder-ide/spyder#15085]
## Problem Description
I have installed anaconda, but the spyder(internal 3.8.8) in anaconda has input hysteresis problem. So I installed Spyder4.2.5(internal 3.9.2) from github. When I use the independent Spyder4.2.5(internal 3.9.2), it appears error: /bin/bash: pip: command not found.  I tried  sudo easy_install pip, but i still can't use pip

### What steps reproduce the problem?

1. install anaconda
2. install latest spyder from github
3. pip install <package>

### Paste Traceback/Error Below (if applicable)
/bin/bash: pip: command not found

Searching for pip
Best match: pip 21.0.1
Processing pip-21.0.1-py2.7.egg
pip 21.0.1 is already the active version in easy-install.pth
Installing pip script to /usr/local/bin
Installing pip2.7 script to /usr/local/bin
Installing pip2 script to /usr/local/bin

Using /Library/Python/2.7/site-packages/pip-21.0.1-py2.7.egg
Processing dependencies for pip
Finished processing dependencies for pip

## Versions

* Spyder version: spyder4.2.5(internal python3.8.8),spyder4.2.5(internal python3.9.2)
* Python version: python3.8.8/python3.9.2
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS BIG SUR 11.1

### Dependencies

# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.21.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  53.0.0 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.3 (OK)
scipy >=0.17.0                  :  1.6.1 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

**Comment by andfoy** [comment]
Hi @kellylizi, it seems that you are trying to install Spyder using a non-official installation method, I would suggest to use one of our Mac installers, which you can find on our release page: https://github.com/spyder-ide/spyder/releases/tag/v4.2.5

**Comment by ccordoba12** [comment]
Another important point @kellylizi is that our self-contained macOS installer (which is the one you seem to be using) doesn't come with pip to avoid breaking Spyder by installing packages inside the installer.

If you want to use other packages with it, you need to connect Spyder to the Anaconda environments you already have. Please read [our FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) to learn how to to do that.
