### ISSUE TITLE
Project menu indicator overlapped by its text, missing icons

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/spyder#15082]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

There is a problem with Qt < 5.14 that makes the indicators and icons really hard to be styled properly. See this issue (also many Qt issues mentioned in it):  https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/214

If you don't want to add that space for all menus you have some other approaches: use the instance name in the CSS patch, add a transparent icon for at least one entry in the menu, or **add normal icons to menu entries** as added in the title has missing icons I think it would be nice to have those.

![image](https://user-images.githubusercontent.com/5084939/113328742-19a6c480-92f3-11eb-9f57-0f111105932d.png)

![project-menu](https://user-images.githubusercontent.com/5084939/113328186-4f977900-92f2-11eb-8e21-15f634493f51.gif)

Since using the QDarkStyle (actually, any changes in the menu style) cause this, so other versions of Spyder already have this problem.

### What steps reproduce the problem?

1. Open spyder
2. Go to the projects menu
3. Last option has its indicator overlapped by the text

### What is the expected output? What do you see instead?

The text does not overlap indicator/entries have icons.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.0.0.dev
* Python version: 3.8.8
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks a lot for your help @dpizetta! I plan to fix this problem in PR #15081.
