### ISSUE TITLE
New file not saving when closing Spyder

### ISSUE THREAD

**Issue by Kaabasane** [spyder-ide/spyder#15092]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If a new file is being saved while closing Spyder, it is not saved. [This issue is resolved in Spyder 5.0.0]

### What steps reproduce the problem?

1. Create new file.
2. Make changes to the new file. Do not save the file yet.
3. Close Spyder, it will prompt you to save the new file.
4. Follow the procedure to saving the file
5. The file will not be saved!!

### What is the expected output? What do you see instead?
The file should be saved when closing Spyder. It is niether visible in File Explorer nor in Spyder.

## Versions

* Spyder version: 4.2.*
* Python version: 3.8.5 64-bit
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Linux 5.8.0-48-generic (Ubuntu 20.4)

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0			:	1.4.0 (OK)
chardet >=2.0.0				:	3.0.4 (OK)
cloudpickle >=0.5.0			:	1.6.0 (OK)
diff_match_patch >=20181111		:	20200713 (OK)
intervaltree >=3.0.2			:	3.1.0 (OK)
IPython >=7.6.0				:	7.21.0 (OK)
jedi =0.17.2				:	0.17.2 (OK)
jsonschema >=3.2.0			:	3.2.0 (OK)
keyring >=17.0.0			:	18.0.1 (OK)
nbconvert >=4.0				:	6.0.7 (OK)
numpydoc >=0.6.0			:	1.1.0 (OK)
parso =0.7.0				:	0.7.0 (OK)
pexpect >=4.4.0				:	4.6.0 (OK)
pickleshare >=0.4			:	0.7.5 (OK)
psutil >=5.3				:	5.8.0 (OK)
pygments >=2.0				:	2.8.1 (OK)
pylint >=1.0				:	2.7.2 (OK)
pyls >=0.36.2;<1.0.0			:	0.36.2 (OK)
pyls_black >=0.4.6			:	0.4.6 (OK)
pyls_spyder >=0.3.2			:	0.3.2 (OK)
qdarkstyle >=2.8;<3.0			:	2.8.1 (OK)
qtawesome >=0.5.7			:	1.0.2 (OK)
qtconsole >=5.0.3			:	5.0.3 (OK)
qtpy >=1.5.0				:	1.9.0 (OK)
setuptools >=39.0.0			:	54.2.0 (OK)
sphinx >=0.6.6				:	3.5.2 (OK)
spyder_kernels >=1.10.2;<1.11.0		:	1.10.3 (OK)
textdistance >=4.2.0			:	4.2.1 (OK)
three_merge >=0.1.1			:	0.1.1 (OK)
watchdog >=0.10.3;<2.0.0		:	1.0.2 (OK)
xdg >=0.26				:	0.26 (OK)
zmq >=17				:	22.0.3 (OK)

# Optional:
cython >=0.21				:	0.29.22 (OK)
matplotlib >=2.0.0			:	3.3.4 (OK)
numpy >=1.7					:	1.20.1 (OK)
pandas >=1.1.1				:	1.2.3 (OK)
scipy >=0.17.0				:	1.6.1 (OK)
sympy >=0.7.3				:	1.7.1 (OK)
```

**Comment by steff456** [comment]
Hi @Kaabasane,

I'm unable to reproduce this issue in the latest Spyder 4.2 in macOS. Are you sure you are saving the file in the directory you have Spyder's working directory?

**Comment by Kaabasane** [comment]
> Hi @Kaabasane,
> 
> I'm unable to reproduce this issue in the latest Spyder 4.2 in macOS. Are you sure you are saving the file in the directory you have Spyder's working directory?

This issue was in Ubuntu 20.4. I also am not able to reproduce this in Ubuntu 18.4.

**Comment by steff456** [comment]
It seems that you are using pip instead of conda, I recommend you to use anaconda and create a clean environment to run Spyder in. We don't offer support for pip installation, so we are unable to give you more guidance.

Thanks for reporting!
