### ISSUE TITLE
#Mandatory: Spyder_kernels> = 2.0.1, <2.1.0: 2.0.1 (NOK)

### ISSUE THREAD

**Issue by oldassagt** [spyder-ide/spyder#15094]
### What steps will reproduce the problem?

You have missing dependencies!
#Mandatory: Spyder_kernels> = 2.0.1, <2.1.0: 2.0.1 (NOK)
Please install these to avoid this message.
Note: Spyder could work without some of these dependencies,
But to have a smooth experience when using Spyder, we recommend you
Urgent to install all listed missing dependencies.
If these dependencies are not installed, it can
Errors come. Please make sure that found mistakes are not the
Direct sequence of missing dependencies are before you report a new problem. 

================== Orginal
Sie haben fehlende Abhängigkeiten!
#Mandatory: spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
Bitte installieren Sie diese, um diese Nachricht zu vermeiden.
Hinweis: Spyder könnte ohne einige dieser Abhängigkeiten arbeiten, 
aber um ein reibungsloses Erlebnis bei der Verwendung von Spyder zu haben, empfehlen wir Ihnen 
dringend, alle aufgeführten fehlenden Abhängigkeiten zu installieren.
Wenn diese Abhängigkeiten nicht installiert werden, kann es zu 
Fehlern kommen. Bitte stellen Sie sicher, dass gefundene Fehler nicht die 
direkte Folge fehlender Abhängigkeiten sind, bevor Sie ein neues Problem melden.

### Traceback
```python-traceback
c:\program files\python\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.3
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.5.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.3 (OK)
pygments >=2.0                :  2.7.2 (OK)
pylint >=1.0                  :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.1 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  49.2.1 (OK)
sphinx >=0.6.6                :  3.3.1 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  0.10.4 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ilayn** [comment]
Duplicate of #15091

**Comment by ccordoba12** [comment]
Yes,  it is. Thanks for noticing it @ilayn.

@oldassagt, thanks for reporting. This problem will be fixed in our next version, to be released in a couple of days.
