### ISSUE TITLE
Add support for javascript syntax highlighting

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1509]
_From [phyo.arkarlwin](https://code.google.com/u/phyo.arkarlwin/) on 2013-08-06T11:44:51Z_

As javascript (d3js, threejs) become very popular for browser side cross platform , interactive visualizations , is there any plan to support (just syntax highlight) in spyderide? 

Should be very easy to support as scintilla have them all.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1509_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T19:41:10Z_

We don't use scintilla but pygments, but in any case you're right: it's very easy to add and I want it too.

I'll do it in our next release.

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [phyo.arkarlwin](https://code.google.com/u/phyo.arkarlwin/) on 2013-08-09T22:58:30Z_

I will check the code to see if i can help.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-10T02:14:06Z_

**Summary:** Add support for javascript syntax highlighting  \<span class="oldvalue"> (was: Feature Request : Javascript Support (just syntax highlight)) \</span>  
  **Status:** Accepted  
  **Owner:** ccordoba12

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T06:47:23Z_

Don't worry. I have it working on my local repo and will push it later today.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T09:08:53Z_

**Labels:** MS-v2.2.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T09:22:30Z_

This issue was updated by revision 9f8b36e01450 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [phyo.arkarlwin](https://code.google.com/u/phyo.arkarlwin/) on 2013-08-13T07:05:10Z_

Thank you very much! I will check it now. You Rock!

**Comment by spyder-issues-migrator** [comment]
_From [snaipp...@gmail.com](https://code.google.com/u/102257053029775563600/) on 2013-08-31T04:00:30Z_

Sweet!

**Comment by bramson** [comment]
I'm using Spyder 3.2.8 via Bash on Ubunto on Windows, and there is no syntax coloring for my javascript (*.js) or CSS (*.css) files.  My HTML, however, file is colored properly.  Also, the IDE gives me a python error message on the first line of the CSS and HTML file about "invalid syntax" (but not the js file).  Is there a setting or preference to tell Spyder to treat .js files as javascript etc.?
