### ISSUE TITLE
Problems with zooming in/out

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1510]
_From [dantis...@gmail.com](https://code.google.com/u/109799630906197024972/) on 2013-08-07T11:46:03Z_

Spyder Version:  2.2.1
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Darwin 

What steps will reproduce the problem?

 1. Attempt to save document on mac with trackpad
2. document zooms almost every time
3. attempt not to pull out hair What is the expected output? What do you see instead? It would be fantastic to either be able to change to zoom command (say, to mod +/-) or simply disable the zoom via scroll option all together. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1510_

**Comment by spyder-issues-migrator** [comment]
_From [dantis...@gmail.com](https://code.google.com/u/109799630906197024972/) on 2013-08-07T09:47:15Z_

I should point out, I suppose, that the save command is cmd+s, and the zoom command is cmd+scroll

**Comment by spyder-issues-migrator** [comment]
_From [samuel.l...@gmail.com](https://code.google.com/u/106548631604770110294/) on 2013-08-09T04:36:17Z_

Yeah, I also realized, after posting the feature request for the Ctrl + mouse wheel feature, that Ctrl + +/- is even more neat: https://code.google.com/p/spyderlib/issues/detail?id=1270&can=1&q=zoom&colspec=ID%20MS%20Stars%20Priority%20Modified%20Cat%20Type%20Status%20Owner%20Summary ... In fact, most text editors I know of (including the gnome terminal), have both of these. But I agree that it is nice if one can change the commands, in case you run into trouble.

**Comment by spyder-issues-migrator** [comment]
_From [dantis...@gmail.com](https://code.google.com/u/109799630906197024972/) on 2013-08-09T09:16:28Z_

Yes: changing the behavior is certainly critical.

I also realized/learned that new macs use "momentum" in scrolling, and the result of simply lightly brushing the trackpad/mouse in a scrolling direction while holding cmd (for saving, etc.) is zooming --with momentum--, leading to excessive scrolling.

I would suggest making the default behavior ctrl/cmd+ +/-, with an option to change it in preferences.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-09T19:49:30Z_

Thanks for reporting. There is one thing I don't understand about your bug report: you need to hold ctrl and then use the mouse wheel to zoom in/out, so why is this activated by using just the trackpad?

I'm not opposed to do the change you suggested, I just want to understand better your problem.

**Summary:** Problems with zooming in/out  \<span class="oldvalue"> (was: Turn off zoom) \</span>  
  **Labels:** Cat-Editor OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [dantis...@gmail.com](https://code.google.com/u/109799630906197024972/) on 2013-08-10T11:39:37Z_

On mac laptops (my peers have had this issue too) with their large trackpads, the action of holding the modifier key to save leads to an extra quarter second or so of simply holding the key down while not pressing "s". During this time, light brushes against the trackpad (say, with the side of a hand) either up or down can lead to the trackpad measuring "momentum" in a scrolling direction, causing zoom.. Does that make sense? I'm not sure how better to describe it.

**Comment by spyder-issues-migrator** [comment]
_From [emmh...@gmail.com](https://code.google.com/u/115290571104363730221/) on 2013-08-10T12:50:03Z_

I would like to add that I have the same issue using the magic mouse on a Mac. I usually hold down the command button to navigate the cursor by skipping words and to save. So when I accidentally flick my finger on the magic mouse surface the screen starts zooming in or out and it locks up ending up too zoomed in or zoomed out. Also returning to original zoom is tricky because the zooming in or out is not smooth. It doesn't happen often but it is very frustrating when it does. I think it would be better to control the zoom level only using the keyboard (using command(ctrl)+ or - for example). I hope this helps, thank you.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-08-10T14:32:45Z_

Thanks dantiston, your explanation makes total sense now. I also think the best approach is to use Ctrl+{+,-} for zooming.

Pierre, what do you think about this one for 2.2.2?

**Cc:** pierre.raybaut  
  **Labels:** MS-v2.2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-11T06:18:08Z_

This issue was updated by revision d703c90266fa .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-11T06:18:09Z_

This issue was closed by revision 9b8196c92c6a .

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-08-11T06:18:25Z_

Tested on Windows 8.

**Comment by endolith** [comment]
Is there a way to just disable mouse zooming?  I don't know why anyone would ever want to zoom text once it's set to a usable font size.

**Comment by ccordoba12** [comment]
@endolith, no, there isn't, sorry. What's the problem with that?

**Comment by endolith** [comment]
> @endolith, no, there isn't, sorry. What's the problem with that?

Just that I trigger it by accident once in a while and then I have to find the setting to restore the normal size, and there's absolutely no reason I would ever want to zoom in or out plain text source code (as opposed to changing the font size once to set it up for a particular screen).

**Comment by ccordoba12** [comment]
@endolith, I don't think that this is much of an issue for most users, but if you're willing to take the time to implement an option for it (in `Preferences > Editor > Interface > Other`), we could consider adding it.

**Comment by parmonom** [comment]
> > [@endolith](https://github.com/endolith), no, there isn't, sorry. What's the problem with that?
> 
> Just that I trigger it by accident once in a while and then I have to find the setting to restore the normal size

Same for me, happens everyday, really annoying not be able to disable it.

**Comment by ccordoba12** [comment]
@parmonom, how do you have this problem? By using mouse gestures in a trackpad?

**Comment by parmonom** [comment]
@ccordoba12, yes I use trackpad, I scroll up and down with two fingers (up and down gesture). I think it happens because there is kind of inertia in the scroll. If I press ctrl before the end of the scroll it dramatically zoom in/out. The problem is that because of the inertia, I find it hard to know when exactly the scroll motion end.

**Comment by ccordoba12** [comment]
Ok, I see. Then please open a new issue about this so we don't forget to address it for 6.1.0, to be released in a few weeks.
