### ISSUE TITLE
in your file "\Lib\site-packages\spyder\dependencies.py", change line 66

### ISSUE THREAD

**Issue by Jacques2101** [spyder-ide/spyder#15110]
in your file "\Lib\site-packages\spyder\dependencies.py", change line 66

from
`SPYDER_KERNELS_REQVER = '>=2.0.1,<2.1.0' `

to
`SPYDER_KERNELS_REQVER = '>=2.0.1;<2.1.0'`

and it will be fine

_Originally posted by @stonebig in https://github.com/spyder-ide/spyder/issues/15091#issuecomment-812848088_

**Comment by Jacques2101** [comment]
I have the same problem I suppose (I am on macOS). Before update everything was ok but after I got an error message. 
<img width="1560" alt="Capture d’écran 2021-04-05 à 14 52 16" src="https://user-images.githubusercontent.com/49912455/113575701-9224c280-961e-11eb-9f41-7f5fecdf78b3.png">

I tried to change "\Lib\site-packages\spyder\dependencies.py" but can't find it. I have many files dependancies.py. 

thx for your help.

**Comment by stonebig** [comment]
There ? https://github.com/spyder-ide/spyder/issues/15091#issuecomment-812864812

**Comment by Jacques2101** [comment]
https://github.com/spyder-ide/spyder/issues/15091#issuecomment-813401884

**Comment by ccordoba12** [comment]
Hey @Jacques2101, thanks for reporting. We're aware of this problem and there's a pull request to fix it (see #15100).

If you're using Anaconda, please be aware that spyder-kernels 2.0.1 is not available there yet and we don't know when it will be.

**Comment by ccordoba12** [comment]
Also, a new version with this fix will be available later today.

**Comment by Jacques2101** [comment]
I installed Spyder as a standalone app. but also have anaconda in parallel 
I tried to change the file \Lib\site-packages\spyder\dependencies.py as the published solution recommend but can't find it. 
I am on MacOS.

**Comment by ccordoba12** [comment]
That's the solution to avoid seeing the dialog telling you to install spyder-kernels 2.0.1.

However, to use Spyder 5 with Anaconda, you need to wait until they release new packages for that version of spyder-kernels. Until that happens, please use Spyder 4.2.5 instead.

**Comment by Jacques2101** [comment]
I am not sure I understood correctly. 
I have installed spyder as a standalone app. but my environment is managed inside anaconda. So what should I do ? 
If I need to downgrade to 4.2.5 from the standalone app, how should I do ? 
Last but not the least, inside version 5.0 as a standalone app will it be possible to install and use notebook as in the anaconda spyder app ? 
Thx.

**Comment by Jacques2101** [comment]
I downgraded to 4.2.5 version and I have now this error message. The same as with version 5.0 no ? 

I go there to get spyder 4.2.5 : [https://github.com/spyder-ide/spyder/releases](url)

<img width="839" alt="Capture d’écran 2021-04-05 à 19 29 08" src="https://user-images.githubusercontent.com/49912455/113604211-3b7eaf00-9645-11eb-9bad-10efc520d12b.png">
