### ISSUE TITLE
Spyder 5 is broken in Anaconda

### ISSUE THREAD

**Issue by Sinooshka** [spyder-ide/spyder#15113]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Hi, 
After updating the spyder with anaconda to version 5,  I get this error when I try running spyder : 

ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'

### What steps reproduce the problem?

1.  conda update spyder 
2. spyder

### What is the expected output? What do you see instead?

An updated version of spyder to pop-up. Instead I get the above mentioned error. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Traceback (most recent call last):
  File "/home/sina/anaconda3/envs/py37/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/sina/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/app/start.py", line 210, in main
    from spyder.app import mainwindow
  File "/home/sina/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 72, in <module>
    from spyder.app import tour
  File "/home/sina/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/app/tour.py", line 37, in <module>
    from spyder.utils.qthelpers import add_actions, create_action
  File "/home/sina/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/utils/qthelpers.py", line 34, in <module>
    from spyder.utils.icon_manager import ima
  File "/home/sina/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/utils/icon_manager.py", line 23, in <module>
    from spyder.utils.palette import QStylePalette, SpyderPalette
  File "/home/sina/anaconda3/envs/py37/lib/python3.7/site-packages/spyder/utils/palette.py", line 12, in <module>
    from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'
```

## Versions

* Spyder version: 5.0.0
* Python version: 3.7.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Fedora 32 (64X)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CommanderCRM** [comment]
Same. When I try to force update qdarkstyle with conda, it says that qdarkstyle will be updated from 2.8.1 to 3.0.2, but spyder will be downgraded from 5.0.0 to 4.2.3. This is tested on a clean spyder-env environment installed according to troubleshooting guide on Spyder website. Python version is 3.9.2, Spyder is 5.0.0, Qt is 5.9.7 and PyQt is 5.9.2, Windows 10 x64.

**Comment by shreyaskamathkm** [comment]
I tried `conda install -c conda-forge qdarkstyle=3.0.2` and it worked. But yeah there must be some bug.

**Comment by CommanderCRM** [comment]
> I tried `conda install -c conda-forge qdarkstyle=3.0.2` and it worked. But yeah there must be some bug.

The thing is, conda-forge qdarkstyle installs spyder 4.2.3 as well.

**Comment by shreyaskamathkm** [comment]
That is interesting. I have the following log when I click about spyder in the help tab.

```
* Spyder version: 5.0.0 None
* Python version: 3.8.8 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.8.18-050818-generic
```
![image](https://user-images.githubusercontent.com/16343884/113599653-e4f57e80-960c-11eb-8ae6-f1c556b6afe2.png)

**Comment by ccordoba12** [comment]
This is a problem in the new packages released by the Anaconda team. I'll talk to them right away so they can fix this problem as soon as possible.

**Comment by PhysicsGuyBrian** [comment]
Same problem here.  I also tried conda install -c conda-forge qdarkstyle=3.0.2 and waited for quite some time and eventually got to this point...
![image](https://user-images.githubusercontent.com/3181310/113621763-e2952380-9610-11eb-8699-c8d5feed1721.png)

then a swift n [enter] was in order!  Now waiting for a better solution.

**Comment by matheger** [comment]
I'm getting a different weird package error now. I first installed `spyder-5.0.0` from `conda-forge`, which got me the same error. Then I updated all packages using `conda update --all`, which installed the proper `qtdarkstyle` and even kept my 5.0.0 installation intact. 

However, now spyder warns me on startup that I allegedly have the wrong `spyder-kernels` version (>=2.0.1, <2.1.0), even though I have 2.0.1 installed.

**Comment by Dan-Patterson** [comment]
Same issue with qdarkstyle
What I can't do....
   1 . Not able to update Anaconda since we are using a specialized conda distribution
   2.  can't update using conda, because "they" are using an older, hence restricted non-accessable version of conda
   3.  Not able to use conda-forge because of (1), even if I add it to channels to check.
A good old zip file would be great right about now so I could unzip into my site-packages folder (sigh)

**Comment by matheger** [comment]
Dan, would a rollback to 4.2.5 work for you?

**Comment by matheger** [comment]
@ccordoba12 I have another problem right now: When I click on the "file link" of an exception trace in the internal console, the editor doesn't jump to that location. Could this be related to spyder not recognizing my `spyder-kernels` version (see above)? Do you want me to open a new issue for it?

**Comment by ccordoba12** [comment]
The (temporary) solution for this is to downgrade to our 4.2.5 version with the command:

    conda install spyder=4.2.5

----

For all people that have this problem right now: if you want to use a very stable and well tested Spyder version, please stay with our latest version of Spyder **4** (we plan to maintain it for two more months with small bug fixes).

Spyder 5 is still a work in progress and it'll take two or three months until reaches the same level of stability.

----

Finally, I'm going to lock this issue so that new people that arrives to this issue can read my message and doesn't get lost with new ones.

**Comment by ccordoba12** [comment]
> When I click on the "file link" of an exception trace in the internal console, the editor doesn't jump to that location

@matheger, please open a new issue about it. It's completely unrelated to this.

**Comment by ccordoba12** [comment]
This seems to be fixed now in Anaconda, so I'm closing it.
