### ISSUE TITLE
erro EOF

### ISSUE THREAD

**Issue by dongseeme** [spyder-ide/spyder#15133]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\XZH\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 413, in eventFilter
    return self._event_filter_console_keypress(event)
  File "C:\Users\XZH\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 108, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "C:\Users\XZH\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "C:\Users\XZH\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 1425, in _event_filter_console_keypress
    self.copy()
  File "C:\Users\XZH\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 249, in copy
    was_newline = text[-1] == '\n'
IndexError: string index out of range

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by steff456** [comment]
Hi @dongseeme,

This issue should be fixed by updating qtconsole to the latest version, please also consider to update your Spyder to Spyder 4  that is very stable now.

Thanks for reporting!

**Comment by dongseeme** [comment]
Hi！Stephannie Jimenez Gacha，
I got it, thanks very much!

---Original---
From: "Stephannie Jimenez ***@***.***&gt;
Date: Wed, Apr 7, 2021 00:32 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [spyder-ide/spyder] erro EOF (#15133)




 
Hi @dongseeme,
 
This issue should be fixed by updating qtconsole to the latest version, please also consider to update your Spyder to Spyder 4  that is very stable now.
 
Thanks for reporting!
