### ISSUE TITLE
[5.0.0] Fresh install, missing dependencies (spyder-kernels)

### ISSUE THREAD

**Issue by Kochise** [spyder-ide/spyder#15136]
![capture_20210406_110728_001](https://user-images.githubusercontent.com/23077417/113687639-d9678d80-96c8-11eb-8067-41d660f5d8f1.png)

Yet :

```
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.22.0 -- An enhanced Interactive Python.

In [1]: !pip install --upgrade spyder-kernels
Requirement already satisfied: spyder-kernels in c:\program files\spyder\pkgs (2.0.1)
Requirement already satisfied: ipykernel>=5.3.0 in c:\program files\spyder\pkgs (from spyder-kernels) (5.5.3)
Requirement already satisfied: ipython>=7.6.0 in c:\program files\spyder\pkgs (from spyder-kernels) (7.22.0)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\program files\spyder\pkgs (from spyder-kernels) (6.1.12)
Requirement already satisfied: decorator<5 in c:\program files\spyder\pkgs (from spyder-kernels) (4.4.2)
Requirement already satisfied: cloudpickle in c:\program files\spyder\pkgs (from spyder-kernels) (1.6.0)
Requirement already satisfied: pyzmq>=17 in c:\program files\spyder\pkgs (from spyder-kernels) (22.0.3)
Requirement already satisfied: tornado>=4.2 in c:\program files\spyder\pkgs (from ipykernel>=5.3.0->spyder-kernels) (6.1)
Requirement already satisfied: traitlets>=4.1.0 in c:\program files\spyder\pkgs (from ipykernel>=5.3.0->spyder-kernels) (5.0.5)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (3.0.18)
Requirement already satisfied: pickleshare in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (0.7.5)
Requirement already satisfied: pygments in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (2.8.1)
Requirement already satisfied: backcall in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (54.2.0)
Requirement already satisfied: colorama in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (0.4.4)
Requirement already satisfied: jedi>=0.16 in c:\program files\spyder\pkgs (from ipython>=7.6.0->spyder-kernels) (0.17.2)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in c:\program files\spyder\pkgs (from jedi>=0.16->ipython>=7.6.0->spyder-kernels) (0.7.0)
Requirement already satisfied: jupyter-core>=4.6.0 in c:\program files\spyder\pkgs (from jupyter-client>=5.3.4->spyder-kernels) (4.7.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files\spyder\pkgs (from jupyter-client>=5.3.4->spyder-kernels) (2.8.1)
Requirement already satisfied: pywin32>=1.0 in c:\program files\spyder\pkgs (from jupyter-core>=4.6.0->jupyter-client>=5.3.4->spyder-kernels) (300)
Requirement already satisfied: wcwidth in c:\program files\spyder\pkgs (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.6.0->spyder-kernels) (0.2.5)
Requirement already satisfied: six>=1.5 in c:\program files\spyder\pkgs (from python-dateutil>=2.1->jupyter-client>=5.3.4->spyder-kernels) (1.15.0)
Requirement already satisfied: ipython-genutils in c:\program files\spyder\pkgs (from traitlets>=4.1.0->ipykernel>=5.3.0->spyder-kernels) (0.2.0)
```

**Comment by BastianZim** [comment]
Same here.

Installed packages:

```zsh
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
applaunchservices         0.2.1                      py_0    conda-forge
appnope                   0.1.2            py39h6e9494a_1    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
arrow                     1.0.3            py39h6e9494a_0    conda-forge
astroid                   2.5.2            py39h6e9494a_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
autopep8                  1.5.6              pyhd8ed1ab_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.3              pyhd8ed1ab_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     20.8b1                     py_1    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
brotlipy                  0.7.0           py39hcbf5805_1001    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
cffi                      1.14.5           py39h319c39b_0    conda-forge
chardet                   4.0.0            py39h6e9494a_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cookiecutter              1.7.2              pyh9f0ad1d_0    conda-forge
cryptography              3.4.7            py39ha2c9959_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
dbus                      1.13.6               ha13b53f_2    conda-forge
decorator                 5.0.5              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
docutils                  0.17             py39h6e9494a_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.3.0                he49afe7_0    conda-forge
flake8                    3.8.4                      py_0    conda-forge
future                    0.18.2           py39h6e9494a_3    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
glib                      2.68.0               he49afe7_2    conda-forge
glib-tools                2.68.0               he49afe7_2    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.10.0           py39h6e9494a_0    conda-forge
importlib_metadata        3.10.0               hd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.5.3            py39h71a6800_0    conda-forge
ipython                   7.22.0           py39h71a6800_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.8.0              pyhd8ed1ab_0    conda-forge
jedi                      0.17.2           py39h6e9494a_1    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39h6e9494a_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
keyring                   23.0.1           py39h6e9494a_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lazy-object-proxy         1.6.0            py39h89e85a6_0    conda-forge
libclang                  11.1.0          default_he082bbe_0    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libglib                   2.68.0               hd556434_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.1                 h052a64a_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libspatialindex           1.9.3                h1c7c35f_3    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                1.1.1            py39hcbf5805_3    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py39hcbf5805_1003    conda-forge
mypy_extensions           0.4.3            py39h6e9494a_3    conda-forge
mysql-common              8.0.23               h694c41f_1    conda-forge
mysql-libs                8.0.23               hbeb7981_1    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py39h6e9494a_3    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
nspr                      4.30                 hcd9eead_0    conda-forge
nss                       3.47                 hc0980d9_0    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandoc                    2.13                 h0d85af4_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py39h6e9494a_4    conda-forge
poyo                      0.5.0                      py_0    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
psutil                    5.8.0            py39hcbf5805_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydocstyle                6.0.0              pyhd8ed1ab_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pylint                    2.7.2            py39h6e9494a_0    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.2              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py39h6e9494a_7    conda-forge
pyqt-impl                 5.12.3           py39hef7122c_7    conda-forge
pyqt5-sip                 4.19.18          py39hd8f94c5_7    conda-forge
pyqtchart                 5.12             py39hef7122c_7    conda-forge
pyqtwebengine             5.12.1           py39hef7122c_7    conda-forge
pyrsistent                0.17.3           py39hcbf5805_2    conda-forge
pysocks                   1.7.1            py39h6e9494a_3    conda-forge
python                    3.9.2           h2502468_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python-slugify            4.0.1              pyh9f0ad1d_0    conda-forge
python.app                1.3              py39hcbf5805_4    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39hcbf5805_0    conda-forge
pyzmq                     22.0.3           py39h7fec2f1_1    conda-forge
qdarkstyle                3.0.2              pyhd8ed1ab_0    conda-forge
qstylizer                 0.1.10             pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtawesome                 1.0.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.0.3              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
regex                     2021.4.4         py39h89e85a6_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rope                      0.18.0             pyh9f0ad1d_0    conda-forge
rtree                     0.9.7            py39h7d0d40a_1    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
spyder                    5.0.0            py39h6e9494a_0    conda-forge
spyder-kernels            2.0.1            py39h6e9494a_0    conda-forge
sqlite                    3.35.4               h44b9ce1_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.2.1              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss                   0.4             pyhd8ed1ab_1002    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39hcbf5805_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.2            py39hcbf5805_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
ujson                     4.0.2            py39h9fcab8e_0    conda-forge
unidecode                 1.2.0              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
watchdog                  1.0.2            py39hcbf5805_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
wrapt                     1.12.1           py39hcbf5805_3    conda-forge
wurlitzer                 2.1.0            py39h6e9494a_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yapf                      0.30.0             pyh9f0ad1d_0    conda-forge
zeromq                    4.3.4                h1c7c35f_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge
```

<img width="421" alt="Screenshot 2021-04-06 at 13 00 52" src="https://user-images.githubusercontent.com/10774221/113695267-57cc2b80-96d9-11eb-956b-78cf8425bb75.png">


Error when starting terminal:

```zsh
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Layer-backing can not be explicitly controlled on 10.14 when built against the 10.14 SDK
<QNSWindow: 0x7f9abccc3b50; contentView=<QNSView: 0x7f9abccc3440; QCocoaWindow(0x7f9abccc3320, window=QWidgetWindow(0x7f9abccc40c0, name="QLabelClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
<QNSWindow: 0x7f9a88025b40; contentView=<QNSView: 0x7f9a88025430; QCocoaWindow(0x7f9a88025310, window=QWidgetWindow(0x7f9a88024d80, name="QLabelClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
<QNSWindow: 0x7f9a7f2c0a40; contentView=<QNSView: 0x7f9a7f2c0330; QCocoaWindow(0x7f9a7f2c0210, window=QWidgetWindow(0x7f9a7f2bfca0, name="QLabelClassWindow"))>> has active key-value observers (KVO)! These will stop working now that the window is recreated, and will result in exceptions when the observers are removed. Break in QCocoaWindow::recreateWindowIfNeeded to debug.
```

**Comment by salmanea** [comment]
Same here:
adodbapi                      2.6.1.3
affine                        2.3.0
aiofiles                      0.5.0
aiohttp                       3.7.1
aiosqlite                     0.15.0
alabaster                     0.7.12
altair                        4.1.0
altair-data-server            0.4.1
altair-transform              0.2.0
altair-widgets                0.2.2
altgraph                      0.17
amply                         0.1.4
aniso8601                     8.0.0
ansiwrap                      0.8.4
appdirs                       1.4.4
argon2-cffi                   20.1.0
arrow                         1.0.3
asciitree                     0.3.3
asgi-csrf                     0.6.1
asgiref                       3.2.10
asteval                       0.9.19
astroid                       2.4.2
astroML                       0.4.1
astropy                       4.0.3
async-generator               1.10
async-timeout                 3.0.1
atomicwrites                  1.4.0
attrs                         20.2.0
autopep8                      1.5.3
Babel                         2.8.0
backcall                      0.2.0
backports-abc                 0.5
baresql                       0.7.6
bcrypt                        3.1.7
beautifulsoup4                4.9.3
binaryornot                   0.4.4
black                         20.8b1
bleach                        3.2.1
blinker                       1.4
blosc                         1.9.2
bloscpack                     0.16.0
bokeh                         2.2.3
botorch                       0.3.2
Bottleneck                    1.3.2
bqplot                        0.12.18
branca                        0.4.1
brewer2mpl                    1.4.1
Brotli                        1.0.9
cachelib                      0.1.1
Cartopy                       0.18.0
category-encoders             2.2.2
certifi                       2020.6.20
cffi                          1.14.3
cftime                        1.2.1
chardet                       3.0.4
click                         7.1.2
click-default-group           1.2.2
click-plugins                 1.1.1
cligj                         0.7.0
cloudpickle                   1.6.0
clrmagic                      0.0.1a2
colorama                      0.4.4
colorcet                      2.0.2
comtypes                      1.1.7
cookiecutter                  1.7.2
cryptography                  3.2
cvxopt                        1.2.5
cvxpy                         1.1.7
cx-Freeze                     6.3
cycler                        0.10.0
Cython                        0.29.21
cytoolz                       0.11.0
dask                          2.30.0
dask-glm                      0.2.0
dask-labextension             3.0.0
dask-ml                       1.7.0
dask-searchcv                 0.2.0
databases                     0.4.0
datasette                     0.50.2
datashader                    0.11.1
datashape                     0.5.2
db.py                         0.5.4b1
decorator                     4.4.2
defusedxml                    0.6.0
Deprecated                    1.2.10
descartes                     1.1.0
diff-match-patch              20200713
distlib                       0.3.1
distributed                   2.30.0
docopt                        0.6.2
docrepr                       0.1.1
docutils                      0.16
ecos                          2.0.7.post1
emcee                         3.0.2
entrypoints                   0.3
fast-histogram                0.9
fastapi                       0.61.1
fasteners                     0.15
fastparquet                   0.4.1
feather-format                0.4.1
filelock                      3.0.12
Fiona                         1.8.17
flake8                        3.8.4
Flask                         1.1.2
flask-accepts                 0.17.4
Flask-Mail                    0.9.1
flask-restx                   0.2.0
Flask-Session                 0.3.2
Flask-SQLAlchemy              2.4.4
flaskerize                    0.14.0
folium                        0.11.0
formlayout                    2.0.0a0
fs                            2.4.11
fsspec                        0.8.4
future                        0.18.2
fuzzywuzzy                    0.18.0
GDAL                          3.1.4
geographiclib                 1.50
geopandas                     0.8.1
geopy                         2.0.0
geoviews                      1.8.1
gmpy2                         2.0.8
gpytorch                      1.2.1
greenlet                      0.4.17
guidata                       1.7.9
guiqwt                        3.0.5
h11                           0.11.0
h2                            4.0.0
h5py                          2.10.0
HeapDict                      1.0.1
helpdev                       0.7.1
holoviews                     1.13.5
hpack                         4.0.0
html5lib                      1.1
httpcore                      0.12.0
httpie                        2.2.0
httpx                         0.16.1
hupper                        1.10.2
husl                          4.0.3
hvplot                        0.6.0
Hypercorn                     0.11.1
hyperframe                    6.0.0
hypothesis                    5.37.4
ibis-framework                1.3.0
idlex                         1.18
idna                          2.10
imageio                       2.9.0
imageio-ffmpeg                0.4.2
imagesize                     1.2.0
imbalanced-learn              0.7.0
imblearn                      0.0
importlib-metadata            2.0.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.0
intervaltree                  3.0.2
ipykernel                     5.3.4
ipyleaflet                    0.13.3
ipympl                        0.5.8
ipython                       7.18.1
ipython-genutils              0.2.0
ipython-sql                   0.4.1b1
ipywidgets                    7.5.1
isort                         5.6.4
itsdangerous                  1.1.0
janus                         0.5.0
jedi                          0.17.2
Jinja2                        2.11.2
jinja2-time                   0.2.0
joblib                        0.17.0
json5                         0.9.5
jsonschema                    3.2.0
julia                         0.5.6
jupyter                       1.0.0
jupyter-bokeh                 2.0.3
jupyter-client                6.1.7
jupyter-console               6.2.0
jupyter-core                  4.6.3
jupyter-server                1.0.5
jupyter-server-proxy          1.5.0
jupyter-sphinx                0.3.2
jupyterlab                    2.2.9
jupyterlab-launcher           0.13.1
jupyterlab-pygments           0.1.2
jupyterlab-server             1.2.0
keyring                       21.4.0
kiwisolver                    1.2.0
lazy-object-proxy             1.4.3
llvmlite                      0.34.0
lmfit                         1.0.1
locket                        0.2.0
loky                          2.9.0
lxml                          4.6.1
lz4                           3.1.0
Markdown                      3.3.2
MarkupSafe                    1.1.1
marshmallow                   3.8.0
matplotlib                    3.3.2
mccabe                        0.6.1
mercantile                    1.1.6
mergedeep                     1.3.0
metakernel                    0.27.0
mistune                       0.8.4
mizani                        0.7.1
mkl-service                   2.3.0
mlxtend                       0.17.3
monotonic                     1.5
moviepy                       1.0.3
mpl-scatter-density           0.7
mpld3                         0.5.1
mpldatacursor                 0.7.1
mpmath                        1.1.0
msgpack                       1.0.0
msvc-runtime                  14.27.29016.1
multidict                     5.0.0
multipledispatch              0.6.0
munch                         2.5.0
mypy                          0.790
mypy-extensions               0.4.3
mysql-connector-python        8.0.21
nbclient                      0.5.1
nbconvert                     6.0.7
nbconvert-reportlab           0.2
nbformat                      5.0.8
nest-asyncio                  1.4.2
netCDF4                       1.5.4
networkx                      2.5
NLopt                         2.6.2
nltk                          3.5
notebook                      6.1.4
numba                         0.51.2
numcodecs                     0.7.2
numdifftools                  0.9.39
numexpr                       2.7.2
numpy                         1.19.2+mkl
numpydoc                      1.1.0
oct2py                        5.2.0
octave-kernel                 0.32.0
osqp                          0.6.1
outcome                       1.0.1
packaging                     20.4
palettable                    3.3.0
pandas                        1.1.3
pandas-datareader             0.9.0
pandocfilters                 1.4.3
panel                         0.10.1
papermill                     2.2.0
param                         1.10.0
parambokeh                    0.2.3
paramiko                      2.7.2
paramnb                       2.0.4
parso                         0.7.0
partd                         1.1.0
pathspec                      0.8.0
pathtools                     0.1.2
patsy                         0.5.1
pdfrw                         0.4
pdvega                        0.2.1.dev0
pefile                        2019.4.18
pep8                          1.7.1
pexpect                       4.8.0
pg8000                        1.16.5
pickleshare                   0.7.5
Pillow                        8.0.1
Pint                          0.16.1
pip                           21.0.1
pipdeptree                    1.0.0
pkginfo                       1.6.0
plotly                        4.12.0
plotnine                      0.7.1
pluggy                        0.13.1
ply                           3.11
portpicker                    1.3.1
poyo                          0.5.0
ppci                          0.5.8
prettytable                   1.0.1
priority                      1.3.0
proglog                       0.1.9
prometheus-client             0.7.1
prompt-toolkit                3.0.8
protobuf                      4.0.0rc1
psutil                        5.7.3
ptpython                      3.0.7
ptyprocess                    0.6.0
PuLP                          2.3
py                            1.9.0
pyaml                         20.4.0
pyarrow                       2.0.0
PyAudio                       0.2.11
pybars3                       0.9.7
pybind11                      2.6.0
pycodestyle                   2.6.0
pycosat                       0.6.3
pycparser                     2.20
pyct                          0.4.6
pydantic                      1.6.1
pydeck                        0.5.0
pydocstyle                    5.1.1
pyepsg                        0.4.0
pyflakes                      2.2.0
pyflux                        0.4.17
pygame                        1.9.6
pygbm                         0.1.0
Pygments                      2.7.2
pyhdf                         0.10.2
PyInstaller                   3.6
pylint                        2.6.0
pyls-black                    0.4.6
pyls-spyder                   0.3.2
pymc                          2.3.8
PyMeta3                       0.5.1
pymongo                       3.11.0
PyNaCl                        1.4.0
pyodbc                        4.0.30
PyOpenGL                      3.1.5
pypandoc                      1.5
pyparsing                     2.4.7
pyproj                        2.6.1.post1
PyQt5                         5.12.3
PyQt5-sip                     12.8.1
pyqt5-tools                   5.15.1.1.7.5
pyqtgraph                     0.11.0
PyQtWebEngine                 5.12.1
pyrsistent                    0.17.3
pyserial                      3.4
pyshp                         2.1.2
pystache                      0.5.4
pytest                        6.1.1
python-baseconv               1.2.2
python-dateutil               2.8.1
python-dotenv                 0.14.0
python-hdf4                   0.10.0+dummy
python-jsonrpc-server         0.4.0
python-language-server        0.36.2
python-Levenshtein            0.12.0
python-slugify                4.0.1
python-snappy                 0.5.4
pythonnet                     2.5.1
PythonQwt                     0.8.3
pytz                          2020.1
pyviz-comms                   0.7.6
PyWavelets                    1.1.1
pywin32                       228
pywin32-ctypes                0.2.0
pywinpty                      0.5.7
pywinusb                      0.4.2
PyYAML                        5.3.1
pyzmq                         19.0.2
pyzo                          4.11.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.1
qtconsole                     5.0.3
QtPy                          1.9.0
quantecon                     0.4.8
Quart                         0.13.1
rasterio                      1.1.8
readme-renderer               28.0
redis                         3.5.3
regex                         2020.10.23
reportlab                     3.5.53
requests                      2.24.0
requests-toolbelt             0.9.1
retrying                      1.3.3
rfc3986                       1.4.0
rise                          5.7.0
rope                          0.18.0
rpy2                          3.4.0.dev0
Rtree                         0.9.4
ruamel.yaml                   0.16.12
ruamel.yaml.clib              0.2.2
Rx                            3.1.1
scikit-fuzzy                  0.4.1
scikit-image                  0.17.2
scikit-learn                  0.23.2
scikit-optimize               0.8.1
scilab2py                     0.6.2
scipy                         1.5.3
scramp                        1.2.0
scs                           2.1.2
seaborn                       0.11.0
Send2Trash                    1.5.0
setuptools                    50.3.2
shap                          0.36.0
Shapely                       1.7.1
simpervisor                   0.3
simplegeneric                 0.8.1
simplejson                    3.17.2
simpy                         4.0.1
six                           1.15.0
slicer                        0.0.4
snakeviz                      2.1.0
sniffio                       1.2.0
snowballstemmer               2.0.0
snuggs                        1.4.7
sortedcontainers              2.2.2
sounddevice                   0.4.1
soupsieve                     2.0.1
Sphinx                        3.2.1
sphinx-rtd-theme              0.5.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
spyder                        5.0.0
spyder-kernels                2.0.1
SQLAlchemy                    1.3.20
sqlite-bro                    0.9.1
sqlparse                      0.4.1
starlette                     0.13.6
statsmodels                   0.12.0
streamz                       0.5.6
style                         1.1.0
supersmoother                 0.4
sympy                         1.6.2
tables                        3.6.1
tblib                         1.7.0
tenacity                      6.2.0
termcolor                     1.1.0
terminado                     0.9.1
testpath                      0.4.4
text-unidecode                1.3
textdistance                  4.2.0
textwrap3                     0.9.2
threadpoolctl                 2.1.0
three-merge                   0.1.1
thrift                        0.13.0
tifffile                      2020.10.1
tinycss                       0.4
toml                          0.10.1
toolz                         0.11.1
torch                         1.6.0+cpu
torchvision                   0.7.0+cpu
tornado                       6.0.4
tqdm                          4.50.2
traitlets                     5.0.5
traittypes                    0.2.1
tranquilizer                  0.5.0+1.gff8dd5f
trio                          0.17.0
trio-asyncio                  0.11.0
twine                         3.2.0
twitter                       1.18.0
typed-ast                     1.4.1
typing-extensions             3.7.4.3
tzlocal                       2.1
ujson                         4.0.1
umap-learn                    0.4.6
uncertainties                 3.1.4
update                        0.0.1
urllib3                       1.25.11
uvicorn                       0.12.2
vega                          3.4.0
vega-datasets                 0.8.0
virtualenv                    20.1.0
ViTables                      3.0.2
voila                         0.2.4
wasmer                        0.4.2b11
watchdog                      0.10.3
wcwidth                       0.2.5
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.35.1
widgetsnbextension            3.5.1
winpython                     3.0.20201028
winrt                         1.0.20239.1
wordcloud                     1.8.0
wrapt                         1.12.1
wsproto                       0.15.0
xarray                        0.16.1
xgboost                       1.2.1
xlrd                          1.2.0
XlsxWriter                    1.3.7
xlwings                       0.20.8
yapf                          0.30.0
yarl                          1.6.2
zarr                          2.5.0
zict                          2.0.0
zipp                          3.3.2

**Comment by ccordoba12** [comment]
You can safely ignore this message in the meantime, it's a false alarm.
