### ISSUE TITLE
missing optional xlrd dependencies

### ISSUE THREAD

**Issue by nts0000** [spyder-ide/spyder#15141]
### What steps will reproduce the problem?

so whenever the programming run anything about reading the file from xlsx type file... it will appear this error. it is asking me to use pip or conda to install xlrd. However i already install the xlrd to my computer but this spyder is still not working anyone has any full tutorial on how to adding it to the dependencies

**Comment by ccordoba12** [comment]
@nts0000, thanks for reporting. How did install Spyder and xlrd?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
