### ISSUE TITLE
Short sad story: Spyder 5 installer?

### ISSUE THREAD

**Issue by thistlillo** [spyder-ide/spyder#15157]
I was happily running the latest minor of the Spyder 4 app on Windows 10. Then, today, I get a message saying Spyder 5 is available and asking me if I want to update. Since 
1- letting your app update itself has never been a good idea;
2- I really wanted the new version
3- I am running out of hd space

I uninstalled spyder 4 and went to get the installer for the new version. I could not find it because the dropdown menu on the upper left here https://docs.spyder-ide.org/current/installation.html says Spyder 4 and 3. So I selected Spyder 4.

I started downloading again the Spyder 4 installer and came here to fill a formal complain. While here, I noticed that it is not yet a good idea to download Spyder 5 and became happy not to have found it.

When the downloaded completed, I found out that, despite I selected Spyder 4, the installer was for version 5.

So now I am sad again.

Please sync your web pages with the current version.

**Comment by ccordoba12** [comment]
Hey @thistlillo, we understand your confusion. Unfortunately, we haven't had time to update our docs but we plan to do that in the next couple of months.

For now, please go to our Releases page to download Spyder 4.2.5:

https://github.com/spyder-ide/spyder/releases
