### ISSUE TITLE
Can't click on tracebacks in the IPython console and go to the corresponding line in the editor

### ISSUE THREAD

**Issue by Smsmadly** [spyder-ide/spyder#15166]
### What steps will reproduce the problem?

When click line_10 in ipython console.
I can't go to line_10 of file by click it. ( can't it in spyder 5 / can it in spyder 4 )

![image](https://user-images.githubusercontent.com/41870428/113882015-3cd2e780-97bd-11eb-8887-82aeb914feef.png)

Versions
Spyder version: 5.0.0
Python version: 3.8.6
Qt version: 5.12.10
PyQt5 version: 5.12.3
Operating System: Windows 10

**Comment by dalthviz** [comment]
Hi @Smsmadly I was able to reproduce this. We will check it for a future release, thanks for the feedback!

**Comment by dalthviz** [comment]
Just in case as a workaround maybe you could use the option `Directly enter debugging when errors appear` from the `Run > Configuration per file...` dialog
