### ISSUE TITLE
current directory mismatch in Spyder 5.0.0

### ISSUE THREAD

**Issue by Smsmadly** [spyder-ide/spyder#15167]
### What steps will reproduce the problem?

Incorrect path with function getcwd()

![image](https://user-images.githubusercontent.com/41870428/113885127-def3cf00-97bf-11eb-90ea-e26b32f6172d.png)

Actual Result
current directory : C:\Users\osama\.spyder-py3

Expect Result
current directory : B:\Scripts

Versions
Spyder version: 5.0.0
Python version: 3.8.6
Qt version: 5.12.10
PyQt5 version: 5.12.3
Operating System: Windows 10

**Comment by dalthviz** [comment]
Hi @Smsmadly thanks for the feedback. Seems like your current working directory is at `C:\Users\osama\.spyder-py3` (the current working directory that Spyder is using is shown in the `Working Directory toolbar` at the top right of the window). If you want to use the file directory as working directory when running you need to go to `Run > Configuration per file... > Working directory settings` and select the option `The directory of the file being executed`

Let us know if the info above helps :)
