### ISSUE TITLE
newbie having trouble with restarting kernel

### ISSUE THREAD

**Issue by greentree0021** [spyder-ide/spyder#15171]
## Problem Description

Dear advisors, i am totally new to python / spyder. 
I am facing trouble to restart the kernel after changing the python interpreter from the default setting to a user selected file (where the additionally downloaded python3.9 is located). 
The error code listed below keeps showing.
Could you please guide me as to how i may approach this error?
The python interpreter is changed as i wish to use pip that is within the folder.

Thank you. 

Traceback (most recent call last):
File "C:\Users\Sehoon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\Sehoon\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Program Files\Spyder\pkgs\spyder_kernels\console\__main__.py", line 23, in 
start.main()
File "C:\Program Files\Spyder\pkgs\spyder_kernels\console\start.py", line 253, in main
import_spydercustomize()
File "C:\Program Files\Spyder\pkgs\spyder_kernels\console\start.py", line 43, in import_spydercustomize
import spydercustomize
File "C:\Program Files\Spyder\pkgs\spyder_kernels\customize\spydercustomize.py", line 28, in
from spyder_kernels.comms.frontendcomm import CommError, frontend_request
File "C:\Program Files\Spyder\pkgs\spyder_kernels\comms\frontendcomm.py", line 17, in 
from jupyter_client.localinterfaces import localhost
File "C:\Program Files\Spyder\pkgs\jupyter_client\__init__.py", line 4, in 
from .connect import *
File "C:\Program Files\Spyder\pkgs\jupyter_client\connect.py", line 21, in 
import zmq
File "C:\Program Files\Spyder\pkgs\zmq\__init__.py", line 125, in 
from zmq import backend
File "C:\Program Files\Spyder\pkgs\zmq\backend\__init__.py", line 32, in 
raise original_error from None
File "C:\Program Files\Spyder\pkgs\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Program Files\Spyder\pkgs\zmq\backend\select.py", line 32, in select_backend
mod = import_module(name)
File "C:\Users\Sehoon\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "C:\Program Files\Spyder\pkgs\zmq\backend\cython\__init__.py", line 6, in 
from . import (
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\Program Files\Spyder\pkgs\zmq\backend\cython\__init__.py)

### What steps reproduce the problem?

1. restarting the kernel
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: windows 10 

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.4 (OK)
setuptools >=39.0.0           :  54.2.0 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1,<2.1.0 :  2.0.1 (NOK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.22 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.3 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.7.1 (OK)

**Comment by dalthviz** [comment]
Hi @greentree0021 did you install `spyder-kernels` inside the environment with Python3.9 that you are selecting as custom interpreter. How are you creating that python installation? Maybe out documentation could be useful here: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-modular-approach

Let us know if the info above helps :)

**Comment by PabloBorda** [comment]
Same problem with spyder-kerbnel here , despite I have spyder-kernels 2.0.1 installed I get 

You have missing dependencies!


# Mandatory:
spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)

Please install them to avoid this message.

Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you to install all the listed missing dependencies.

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.


They mentioned is a bug and they will fix it in few days in version 5.0.1 ? 

Thank you

**Comment by ccordoba12** [comment]
> They mentioned is a bug and they will fix it in few days in version 5.0.1 ?

Yes, it's a duplicate of issue #15091 and it'll be fixed in 5.0.1.

**Comment by dalthviz** [comment]
Closing due to lack of response
