### ISSUE TITLE
No function definitions showing

### ISSUE THREAD

**Issue by pchristian4481** [spyder-ide/spyder#15182]
### What steps will reproduce the problem?

Spyder 5.0 can not go to function or class (Ctrl-G) definition

**Comment by ccordoba12** [comment]
Hey @pchristian4481, thanks for reporting. It works in some cases and not in others. We'll try to fix that in the future.

**Comment by pchristian4481** [comment]
Thanks. It work initially and then stopped working?. I may try to reinstall it and see if it starts working again. It also said several things would not install some of the dependencies.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
