### ISSUE TITLE
Spyder-kernels version 2.0.1  installed but version error persists

### ISSUE THREAD

**Issue by audsyn** [spyder-ide/spyder#15184]
### What steps will reproduce the problem?

On startup, I get dependency error that spyder-kernels needs to be >= v2.0.1 and that 2.0.1 is installed. Confirmed in dependencies window that 2.0.1 is installed and that >=2.0.1,<2.1.0 is required.

**Comment by ccordoba12** [comment]
Hey @audsyn, thanks for reporting. This is a duplicate of issue #15091 and it'll be fixed in our next version.
