### ISSUE TITLE
matplotlib.pyplot

### ISSUE THREAD

**Issue by gjain75** [spyder-ide/spyder#15193]
### What steps will reproduce the problem?

import matplotlib.pyplot
plt.plot([1,2,3,4,5], np.random.random(5))

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 417, in _handle_new_figure
    self.thumbnails_sb.add_thumbnail(fig, fmt)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 861, in add_thumbnail
    self.set_current_thumbnail(thumbnail)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 937, in set_current_thumbnail
    thumbnail.highlight_canvas(thumbnail == self.current_thumbnail)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 1030, in highlight_canvas
    qdarkstyle.palette.DarkPalette.COLOR_SELECTION_LIGHT
AttributeError: module 'qdarkstyle.palette' has no attribute 'DarkPalette'
```

## Versions

* Spyder version: 4.1.3 
* Python version: 3.7.10
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.8.1 (OK)
pylint >=0.25                  :  2.7.2 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.0.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  3.5.3 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.0.3 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  3.4.1 (OK)
numpy >=1.7                    :  1.20.2 (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @gjain75, thanks for reporting. To fix this, please close Spyder, open the Anaconda Prompt and run there

    conda install qdarkstyle=2.8.1

Please let us know if it works for you.

**Comment by ccordoba12** [comment]
@gjain75, I'm going to close this issue because several people have attested that this is the real fix for your problem.

**Comment by gjain75** [comment]
Hi Thanks for help, I am still unable to start Spyder see below error:

“””
An error ocurred while starting the kernel
Fatal Python error: initsite: Failed to import the site module Traceback (most recent call last):
File "C:\Users\Gautam\site.py", line 8, in
from flask import Flask
ModuleNotFoundError: No module named 'flask'
“””

I checked with pip, flask is already installed. Conda cannot find flask. Tried installing again through conda/pip, gives following error:
“””
(base) PS C:\WINDOWS\system32> pip install flask
Requirement already satisfied: flask in c:\programdata\anaconda3\lib\site-packages (1.1.2)
Requirement already satisfied: Jinja2>=2.10.1 in c:\programdata\anaconda3\lib\site-packages (from flask) (2.11.3)
Requirement already satisfied: Werkzeug>=0.15 in c:\programdata\anaconda3\lib\site-packages (from flask) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in c:\programdata\anaconda3\lib\site-packages (from flask) (1.1.0)
Requirement already satisfied: click>=5.1 in c:\programdata\anaconda3\lib\site-packages (from flask) (7.1.2)
Requirement already satisfied: MarkupSafe>=0.23 in c:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.10.1->flask) (1.1.1)
WARNING: Error parsing requirements for tensorflow: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\lib\\site-packages\\tensorflow-2.0.0.dist-info\\METADATA'
WARNING: Error parsing requirements for rsa: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\lib\\site-packages\\rsa-4.0.dist-info\\METADATA'
WARNING: Error parsing requirements for google-pasta: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\lib\\site-packages\\google_pasta-0.1.8.dist-info\\METADATA'
(base) PS C:\WINDOWS\system32> pip install tensorflow=2.0.0
ERROR: Invalid requirement: 'tensorflow=2.0.0'
Hint: = is not a valid operator. Did you mean == ?
(base) PS C:\WINDOWS\system32> pip install tensorflow-2.0.0
ERROR: Could not find a version that satisfies the requirement tensorflow-2.0.0
ERROR: No matching distribution found for tensorflow-2.0.0
(base) PS C:\WINDOWS\system32> pip install tensorflow
Requirement already satisfied: tensorflow in c:\programdata\anaconda3\lib\site-packages (2.0.0)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\lib\\site-packages\\tensorflow-2.0.0.dist-info\\METADATA'
“””

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
