### ISSUE TITLE
variable explorer size display error

### ISSUE THREAD

**Issue by berich-ai** [spyder-ide/spyder#15244]
### What steps will reproduce the problem?

Environment: win10
Spyder version: 4.1.5
When set system language region as Chinese(Simp. HK), Syder variable explorer size will display 1 as string '<'.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by berich-ai** [comment]
![image](https://user-images.githubusercontent.com/79389909/114298312-4f645e00-9ae8-11eb-9d18-71f88534fa78.png)
size display error!

**Comment by berich-ai** [comment]
I found that spyder 3.x.x would display normally, and had troubles in 4.x.x and 5.0.0.

**Comment by ccordoba12** [comment]
@berich-ai, thanks for reporting. Unfortunately we don't have an easy way to test this problem.

@leavor, could you give us a with it? Thanks!

**Comment by leavor** [comment]
In my case, there is no such problem in simplified Chinese or English environment.

![image](https://user-images.githubusercontent.com/1759365/114329572-47510080-9b72-11eb-962e-6214f6b4a94d.png)

![image](https://user-images.githubusercontent.com/1759365/114329683-926b1380-9b72-11eb-8340-49c01e90e407.png)

**Comment by ccordoba12** [comment]
Closing due to lack of response.
