### ISSUE TITLE
Move calltip to not crop code written in the console

### ISSUE THREAD

**Issue by nielsp** [spyder-ide/spyder#15264]
Is it possible to move the function-help popup-rectangle in Spyder?

I find it very annoying that this popup blocks what I'm writing in the function. I like the help, but I just want to move it a little bit up, so it doesn't block what I'm writing. 

See the picture below:
![spyder popup](https://user-images.githubusercontent.com/1209758/114517918-1a1e5400-9c3f-11eb-985e-6d7bec5105b6.jpg)

Thanks in advance!

**Comment by ccordoba12** [comment]
Hey @nielsp, thanks for reporting. I agree this is very annoying and we'll try to fix it in a future release.

**Comment by nielsp** [comment]
Thank you so much, @ccordoba12 ! I really helps that someone just acknowledges that it's an issue! That will help me keep calm(er) !
