### ISSUE TITLE
Spyder 5.0.0, Solving Environment failed, Conflicts in packages

### ISSUE THREAD

**Issue by Runelaron** [spyder-ide/spyder#15273]
## Problem Description
(base) C:\Users\User\anaconda3>conda install spyder=5.0.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.

### What steps reproduce the problem?

1. conda install spyder=5.0.0

### What is the expected output? What do you see instead?

Install complete

### Paste Traceback/Error Below (if applicable)

```python-traceback


Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining pkginfo:   3%|█▋                                                             | 9/347 [00:00<00:28, 11.89it/s]\Examining pynacl:   6%|███▉                                                           | 22/347 [00:02<00:29, 11.15it/s]/Examining black:   7%|████▍                                                           | 24/347 [00:02<00:32, 10.07it/s]-Examining locket:   8%|█████                                                          | 28/347 [00:02<00:25, 12.43it/s]\Examining jsonschema:   9%|█████▎                                                     | 31/347 [00:02<00:25, 12.43it/s]|Examining more-itertools:  10%|█████▏                                                 | 33/347 [00:03<00:20, 15.02it/s]\Examining tk:  11%|███████▎                                                           | 38/347 [00:05<00:30, 10.21it/s]/Examining qdarkstyle:  20%|███████████▉                                               | 70/347 [00:29<01:09,  3.96it/s]\Examining partd:  21%|█████████████▎                                                  | 72/347 [00:29<00:59,  4.61it/s]
Examining yaml:  24%|███████████████▎                                                 | 82/347 [00:30<00:38,  6.92it/s]\
Examining keyring:  24%|██████████████▊                                               | 83/347 [00:30<00:38,  6.92it/s]/
Examining xlwings:  24%|███████████████                                               | 84/347 [00:31<00:37,  7.00it/s]\
Examining charls:  27%|█████████████████▏                                             | 95/347 [00:32<00:49,  5.10it/s]/
Examining jpeg:  29%|██████████████████▍                                             | 100/347 [00:33<00:36,  6.79it/s]/
Examining wincertstore:  31%|█████████████████▌                                      | 109/347 [00:35<01:03,  3.73it/s]|
Examining typing_extensions:  35%|█████████████████▋                                 | 120/347 [00:36<00:47,  4.75it/s]|
Examining intel-openmp:  35%|███████████████████▊                                    | 123/347 [00:36<00:36,  6.14it/s]/
Examining docutils:  42%|█████████████████████████▏                                  | 146/347 [00:45<01:27,  2.30it/s]/
Examining zope.interface:  53%|████████████████████████████▊                         | 185/347 [01:06<02:07,  1.27it/s]\
Examining pytables:  54%|████████████████████████████████▎                           | 187/347 [01:16<01:18,  2.03it/s]/
Examining libarchive:  55%|███████████████████████████████▉                          | 191/347 [01:18<05:12,  2.00s/it]|
Examining networkx:  57%|██████████████████████████████████▏                         | 198/347 [01:19<01:48,  1.37it/s]\
Examining mpc:  58%|█████████████████████████████████████▋                           | 201/347 [01:19<01:20,  1.81it/s]/
Examining mccabe:  60%|████████████████████████████████████▉                         | 207/347 [01:19<00:54,  2.55it/s]-
Examining sphinxcontrib-jsmath:  61%|█████████████████████████████                   | 210/347 [01:19<00:53,  2.55it/s]|
Examining autopep8:  62%|█████████████████████████████████████▎                      | 216/347 [01:20<00:30,  4.33it/s]\
Examining xz:  66%|███████████████████████████████████████████▋                      | 230/347 [01:25<00:49,  2.38it/s]-
Examining appdirs:  68%|█████████████████████████████████████████▍                   | 236/347 [01:25<00:26,  4.24it/s]\
Examining nbformat:  70%|██████████████████████████████████████████                  | 243/347 [01:28<00:41,  2.49it/s]\
Examining toml:  70%|█████████████████████████████████████████████                   | 244/347 [01:29<00:32,  3.14it/s]|
Examining numpydoc:  78%|██████████████████████████████████████████████▌             | 269/347 [01:34<00:24,  3.13it/s]-
Examining notebook:  79%|███████████████████████████████████████████████▍            | 274/347 [01:35<00:18,  4.05it/s]|
Examining json5:  82%|███████████████████████████████████████████████████▍           | 283/347 [01:38<00:15,  4.04it/s]\
Examining vs2015_runtime:  88%|███████████████████████████████████████████████▊      | 307/347 [01:39<00:03, 13.24it/s]/
Examining attrs:  90%|████████████████████████████████████████████████████████▍      | 311/347 [01:40<00:05,  6.18it/s]/
Examining bitarray:  91%|██████████████████████████████████████████████████████▍     | 315/347 [01:40<00:04,  7.77it/s]-
Examining blas:  91%|██████████████████████████████████████████████████████████▍     | 317/347 [01:40<00:03,  9.43it/s]\
Examining jupyter_server:  94%|██████████████████████████████████████████████████▌   | 325/347 [01:53<00:01, 12.58it/s]|
Examining mkl_fft:  94%|█████████████████████████████████████████████████████████▍   | 327/347 [01:53<00:20,  1.01s/it]/
Examining openjpeg:  95%|████████████████████████████████████████████████████████▋   | 328/347 [01:54<00:20,  1.07s/it]/
Examining sphinxcontrib:  96%|████████████████████████████████████████████████████▊  | 333/347 [01:54<00:10,  1.30it/s]\
Examining libaec:  97%|████████████████████████████████████████████████████████████▍ | 338/347 [01:56<00:04,  1.83it/s]|
Examining requests:  99%|███████████████████████████████████████████████████████████▋| 345/347 [01:59<00:01,  1.14it/s]-
Examining conflict for iniconfig pysocks simplegeneric diff-match-patch singledispatch nbclassic mkl-service prompt_too\
Examining conflict for ipython anaconda _anaconda_depends simplegeneric jupyter_console ipykernel jupyterlab ipywidgets-Examining conflict for anaconda _anaconda_depends intel-openmp numexpr numpy-base mkl mkl-service scipy mkl_random nump-
Examining conflict for anaconda notebook _anaconda_depends jupyter_console widgetsnbextension spyder-kernels nbclassic -Examining conflict for anaconda nbclassic jupyter_core jupyterlab ipywidgets jupyter spyder-notebook ipython nbformat j-Examining conflict for anaconda astropy python bleach bcrypt packaging pip _anaconda_depends bokeh nbconvert jupyterlab|
Examining conflict for _anaconda_depends jupyter-packaging _ipyw_jlab_nb_ext_conf jupyterlab:  13%|▏| 45/347 [2:03:31<1\
Examining conflict for ipython anaconda _anaconda_depends jedi python-language-server parso spyder spyder-notebook:  14/
Examining conflict for anaconda astropy pip bleach _anaconda_depends packaging bokeh scikit-image pyparsing seaborn jup|
Examining conflict for ipython anaconda astropy _anaconda_depends jupyter_console prompt_toolkit prompt-toolkit wcwidth-Examining conflict for anaconda _anaconda_depends cython:  18%|██▉              | 61/347 [2:47:58<14:01:28, 176.53s/it]|
Examining conflict for anaconda argon2-cffi notebook _anaconda_depends widgetsnbextension nbclassic jupyterlab jupyter \
Examining conflict for anaconda _anaconda_depends pyflakes python-language-server flake8 spyder pyls-black pyls-spyder:\
Examining conflict for lcms2 imagecodecs tifffile:  20%|████▋                   | 68/347 [3:11:39<13:42:38, 176.91s/it]/
Examining conflict for anaconda pillow _anaconda_depends python-libarchive-c blosc lcms2 libarchive zstd openjpeg conda-Examining conflict for anaconda xlsxwriter _anaconda_depends:  22%|██▉          | 77/347 [3:32:18<12:49:26, 170.99s/it]|
Examining conflict for anaconda _anaconda_depends numpydoc sphinx spyder sphinxcontrib-serializinghtml:  22%|▏| 78/347 |
Examining conflict for spyder attrs pyls-black black:  23%|████▊                | 80/347 [3:41:07<12:57:29, 174.72s/it]\
Examining conflict for pathspec pyls-black black:  23%|█████▊                   | 81/347 [3:44:06<12:54:34, 174.72s/it]/
Examining conflict for mypy_extensions pyls-black black:  25%|████▍             | 86/347 [3:54:10<12:14:58, 168.96s/it]\
Examining conflict for pydocstyle anaconda _anaconda_depends python-language-server spyder pyls-black pyls-spyder:  26%\
Examining conflict for backports.weakref isort anaconda get_terminal_size tornado pywinpty pydocstyle ipython path.py s|
Examining conflict for pydocstyle anaconda _anaconda_depends python-language-server snowballstemmer numpydoc sphinx spy-
Examining conflict for anaconda _anaconda_depends pylint lazy-object-proxy astroid:  28%|▎| 96/347 [4:25:08<14:05:06,|
Examining conflict for notebook anaconda _anaconda_depends nbclient nbconvert jupyter jupyter_server spyder:  28%|▎| 97|\
```

### Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda                  custom                   py38_1
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.10.0                   py38_0
anaconda-project          0.9.1              pyhd3eb1b0_1
anyio                     2.2.0            py38haa95532_1
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38h2bbff1b_1
asn1crypto                1.4.0                      py_0
astroid                   2.5              py38haa95532_1
astropy                   4.2.1            py38h2bbff1b_1
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     20.3.0             pyhd3eb1b0_0
autopep8                  1.5.6              pyhd3eb1b0_0
babel                     2.9.0              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.0                pyhd3eb1b0_2
backports.functools_lru_cache 1.6.3              pyhd3eb1b0_0
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py38he774522_0
beautifulsoup4            4.9.3              pyha847dfd_0
bitarray                  1.9.1            py38h2bbff1b_1
bkcharts                  0.2                      py38_0
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
blosc                     1.21.0               h19a0ad4_0
bokeh                     2.3.1            py38haa95532_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38h2a96729_1
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py38h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2021.1.19            haa95532_1
certifi                   2020.12.5        py38haa95532_0
cffi                      1.14.5           py38hcd4344a_0
chardet                   4.0.0           py38haa95532_1003
charls                    2.2.0                h6c2663c_0
click                     7.1.2              pyhd3eb1b0_0
cloudpickle               1.6.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.4              pyhd3eb1b0_0
comtypes                  1.1.9           py38haa95532_1002
conda                     4.10.0           py38haa95532_0
conda-build               3.21.4           py38haa95532_0
conda-env                 2.6.0                         1
conda-package-handling    1.7.2            py38h76e460a_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               0.6.0.post1                py_0
cryptography              3.4.7            py38h71e12ea_0
curl                      7.71.1               h2a8f88b_1
cycler                    0.10.0                   py38_0
cython                    0.29.22          py38hd77b12b_0
cytoolz                   0.11.0           py38he774522_0
dask                      2021.4.0           pyhd3eb1b0_0
dask-core                 2021.4.0           pyhd3eb1b0_0
decorator                 4.4.2              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713                   py_0
distributed               2021.4.0         py38haa95532_0
docutils                  0.17             py38haa95532_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
fastcache                 1.1.0            py38he774522_0
filelock                  3.0.12             pyhd3eb1b0_1
flake8                    3.9.0              pyhd3eb1b0_0
flask                     1.1.2              pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
fsspec                    0.9.0              pyhd3eb1b0_0
future                    0.18.2                   py38_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    21.1.2           py38h2bbff1b_1
giflib                    5.2.1                h62dcd97_0
glob2                     0.7                pyhd3eb1b0_0
gmpy2                     2.0.8            py38h7edee0f_3
greenlet                  1.0.0            py38hd77b12b_2
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyhd3eb1b0_0
imagecodecs               2021.3.31        py38h5da4933_0
imageio                   2.9.0              pyhd3eb1b0_0
imagesize                 1.2.0              pyhd3eb1b0_0
importlib-metadata        3.10.0           py38haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2020.2                      254
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.22.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
isort                     5.8.0              pyhd3eb1b0_0
itsdangerous              1.1.0              pyhd3eb1b0_0
jdcal                     1.4.1                      py_0
jedi                      0.17.2           py38haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
joblib                    1.0.1              pyhd3eb1b0_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                      py_2
jupyter                   1.0.0                    py38_7
jupyter-packaging         0.7.12             pyhd3eb1b0_0
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_console           6.4.0              pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
jupyter_server            1.4.1            py38haa95532_0
jupyterlab                3.0.11             pyhd3eb1b0_1
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.4.0              pyhd3eb1b0_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keyring                   22.3.0           py38haa95532_0
kiwisolver                1.3.1            py38hd77b12b_0
krb5                      1.18.2               hc04afaa_0
lazy-object-proxy         1.6.0            py38h2bbff1b_0
lcms2                     2.12                 h83e58a3_0
lerc                      2.2.1                hd77b12b_0
libaec                    1.0.4                h33f27b4_1
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.1               h2a8f88b_1
libdeflate                1.7                  h2bbff1b_5
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.2.0                hd0e1b90_0
libxml2                   2.9.10               hb89e7f3_3
libxslt                   1.1.34               he774522_0
libzopfli                 1.0.3                ha925a31_0
llvmlite                  0.36.0           py38h34b8924_4
locket                    0.2.1            py38haa95532_1
lxml                      4.6.3            py38h9b66d53_0
lz4-c                     1.9.3                h2bbff1b_0
lzo                       2.10                 he774522_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py38he774522_0
matplotlib                3.3.4            py38haa95532_0
matplotlib-base           3.3.4            py38h49ac443_0
mccabe                    0.6.1                    py38_1
menuinst                  1.4.16           py38he774522_1
mistune                   0.8.4           py38he774522_1000
mkl                       2020.2                      256
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h46781fe_0
mkl_random                1.1.1            py38h47e9c7a_0
mock                      4.0.3              pyhd3eb1b0_0
more-itertools            8.7.0              pyhd3eb1b0_0
mpc                       1.1.0                h7edee0f_1
mpfr                      4.0.2                h62dcd97_1
mpir                      3.0.0                hec2e145_1
mpmath                    1.2.1            py38haa95532_0
msgpack-python            1.0.2            py38h59b6b97_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                    py38_0
mypy_extensions           0.4.3                    py38_0
navigator-updater         0.2.1                    py38_0
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py38_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.5.1              pyhd3eb1b0_0
nltk                      3.5                        py_0
nose                      1.3.7           pyhd3eb1b0_1006
notebook                  6.3.0            py38haa95532_0
numba                     0.53.1           py38hf11a4ad_0
numexpr                   2.7.3            py38hcbcaa1e_0
numpy                     1.19.2           py38hadc3359_0
numpy-base                1.19.2           py38ha3acd2a_0
numpydoc                  1.1.0              pyhd3eb1b0_1
olefile                   0.46                       py_0
openjpeg                  2.3.0                h5ec785f_1
openpyxl                  3.0.7              pyhd3eb1b0_0
openssl                   1.1.1k               h2bbff1b_0
packaging                 20.9               pyhd3eb1b0_0
pandas                    1.2.3            py38hf11a4ad_0
pandoc                    2.12                 haa95532_0
pandocfilters             1.4.3            py38haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
partd                     1.1.0                      py_0
path                      15.1.2           py38haa95532_0
path.py                   12.5.0                        0
pathlib2                  2.3.5            py38haa95532_2
pathspec                  0.7.0                      py_0
pathtools                 0.1.2                      py_1
patsy                     0.5.1                    py38_0
pep8                      1.7.1                    py38_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.2.0            py38h4fa10fc_0
pip                       21.0.1           py38haa95532_0
pkginfo                   1.7.0            py38haa95532_0
pluggy                    0.13.1           py38haa95532_0
ply                       3.11                     py38_0
powershell_shortcut       0.0.1                         3
prometheus_client         0.10.1             pyhd3eb1b0_0
prompt-toolkit            3.0.17             pyh06a4308_0
prompt_toolkit            3.0.17               hd3eb1b0_0
psutil                    5.8.0            py38h2bbff1b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
py                        1.10.0             pyhd3eb1b0_0
py-lief                   0.10.1           py38ha925a31_0
pycodestyle               2.6.0              pyhd3eb1b0_0
pycosat                   0.6.3            py38h2bbff1b_0
pycparser                 2.20                       py_2
pycurl                    7.43.0.6         py38h7a1dbc1_0
pydocstyle                6.0.0              pyhd3eb1b0_0
pyerfa                    1.7.2            py38h2bbff1b_0
pyflakes                  2.2.0              pyhd3eb1b0_0
pygments                  2.8.1              pyhd3eb1b0_0
pylint                    2.7.4            py38haa95532_1
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyodbc                    4.0.30           py38ha925a31_0
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38ha925a31_4
pyreadline                2.1                      py38_1
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
pytables                  3.6.1            py38ha5be198_0
pytest                    6.2.3            py38haa95532_2
python                    3.8.8                hdbf39b2_4
python-dateutil           2.8.1              pyhd3eb1b0_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-libarchive-c       2.9                pyhd3eb1b0_1
pytz                      2021.1             pyhd3eb1b0_0
pywavelets                1.1.1            py38he774522_2
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     20.0.0           py38hd77b12b_1
qdarkstyle                2.8.1                      py_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.2              pyhd3eb1b0_0
qtconsole                 5.0.3              pyhd3eb1b0_0
qtpy                      1.9.0                      py_0
regex                     2021.4.4         py38h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
rope                      0.18.0                     py_0
rtree                     0.9.4            py38h21ff451_1
ruamel_yaml               0.15.100         py38h2bbff1b_0
scikit-image              0.18.1           py38hf11a4ad_0
scikit-learn              0.24.1           py38hf11a4ad_0
scipy                     1.6.2            py38h14eb087_0
seaborn                   0.11.1             pyhd3eb1b0_0
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py38haa95532_0
simplegeneric             0.8.1                    py38_2
singledispatch            3.6.1           pyhd3eb1b0_1001
sip                       4.19.13          py38ha925a31_0
six                       1.15.0           py38haa95532_0
snappy                    1.1.8                h33f27b4_0
sniffio                   1.2.0            py38haa95532_1
snowballstemmer           2.1.0              pyhd3eb1b0_0
sortedcollections         2.1.0              pyhd3eb1b0_0
sortedcontainers          2.3.0              pyhd3eb1b0_0
soupsieve                 2.2.1              pyhd3eb1b0_0
sphinx                    3.5.3              pyhd3eb1b0_0
sphinxcontrib             1.0                      py38_1
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0
sphinxcontrib-websupport  1.2.4                      py_0
spyder                    4.2.5            py38haa95532_0
spyder-kernels            1.10.2           py38haa95532_0
spyder-notebook           0.3.2              pyh44b312d_0    spyder-ide
sqlalchemy                1.4.7            py38h2bbff1b_0
sqlite                    3.35.4               h2bbff1b_0
statsmodels               0.12.2           py38h2bbff1b_0
sympy                     1.7.1            py38haa95532_0
tbb                       2020.3               h74a9793_0
tblib                     1.7.0                      py_0
terminado                 0.9.4            py38haa95532_0
testpath                  0.4.4              pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
threadpoolctl             2.1.0              pyh5ca1d4c_0
three-merge               0.1.1              pyhd3eb1b0_0
tifffile                  2021.3.31          pyhd3eb1b0_1
tk                        8.6.10               he774522_0
toml                      0.10.2             pyhd3eb1b0_0
toolz                     0.11.1             pyhd3eb1b0_0
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.59.0             pyhd3eb1b0_1
traitlets                 5.0.5              pyhd3eb1b0_0
typed-ast                 1.4.2            py38h2bbff1b_1
typing_extensions         3.7.4.3            pyha847dfd_0
ujson                     4.0.2            py38hd77b12b_0
unicodecsv                0.14.1                   py38_0
urllib3                   1.26.4             pyhd3eb1b0_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  1.0.2            py38haa95532_1
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1              pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py38_0
win_inet_pton             1.1.0            py38haa95532_0
win_unicode_console       0.5                      py38_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py38he774522_1
xlrd                      2.0.1              pyhd3eb1b0_0
xlsxwriter                1.3.8              pyhd3eb1b0_0
xlwings                   0.23.0           py38haa95532_0
xlwt                      1.3.0                    py38_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.3                ha925a31_3
zfp                       0.5.5                hd77b12b_6
zict                      2.0.0              pyhd3eb1b0_0
zipp                      3.4.1              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4
zope                      1.0                      py38_1
zope.event                4.5.0                    py38_0
zope.interface            5.3.0            py38h2bbff1b_0
zstd                      1.4.5                h04227a9_0

**Comment by steff456** [comment]
Hi @Runelaron,

Did you tried to install Spyder in a new environment or in an existent one? Can you please retry to install it in a new environment and let me know if it works?

**Comment by Runelaron** [comment]
Installing in a new environment will install but with Kernel error.

# Current error
![SpyderKernals](https://user-images.githubusercontent.com/50124140/114634171-d8110480-9c76-11eb-9526-80df702cca55.png)


# Attempt to install kernels in new environment
(myenv) C:\Users\User\anaconda3>conda install spyder-kernels
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

**Comment by Runelaron** [comment]
Ran the install with a debug log for the first couple resolve failures.  Hope this helps.
[spyder_5_install_debug_log.txt](https://github.com/spyder-ide/spyder/files/6311463/spyder_5_install_debug_log.txt)

**Comment by ccordoba12** [comment]
Please run

    conda install spyder-kernels=2.0.1

to see if that fixes the problem.

**Comment by Runelaron** [comment]
## Results

(base) C:\Users\User\anaconda3>conda activate myenv

(myenv) C:\Users\User\anaconda3>conda install spyder-kernels=2.0.1
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.10.0
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\Runel\anaconda3\envs\myenv

  added / updated specs:
    - spyder-kernels=2.0.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2021.4.13  |       haa95532_1         115 KB
    ------------------------------------------------------------
                                           Total:         115 KB

The following packages will be UPDATED:

  ca-certificates                      2021.1.19-haa95532_1 --> 2021.4.13-haa95532_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
ca-certificates-2021 | 115 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

### New error
![image](https://user-images.githubusercontent.com/50124140/114781735-ebcb7200-9d2d-11eb-841a-e724b3e2ccac.png)

#### Steps
1. Updated kernel
2. Updated Conda
3. Run Spyder

Hope this data helps.

**Comment by ccordoba12** [comment]
Ok, please now run

    spyder --reset

and try again.

**Comment by Runelaron** [comment]
## Result
Reset corrected the issue, It seems to be an issue with Spyder notebook after reading the conflict files.
The disappointing thing is I lost the Notebook plugin and all settings, I backed them up under the config location luckily.

I appreciate your help and will attempt to do that under Base, as my current environment is used for Tensor.

**Comment by ccordoba12** [comment]
> Will attempt to re-install notebook package report back.

Spyder-notebook doesn't work with Spyder 5 yet.

> Thank you for all your help.

Glad you were able to sort out this problem at the end.

**Comment by ArnaldoMatute** [comment]
I'm installing spyder 5.0.5. It says "found conflicts! Looking for incompatible packages". It began to examine conflicts and it's been 24 hours and has not ended. Should I keep waiting till it ends? Is it worth it?

**Comment by Runelaron** [comment]
It will not solve, there have been many adjustments to 5.0.5 that its having to shift items line by line.

I would suggest using Spyder 4 until Notebook is fully compatible.

**Comment by ArnaldoMatute** [comment]
> It will not solve, there have been many adjustments to 5.0.5 that its having to shift items line by line.
> 
> I would suggest using Spyder 4 until Notebook is fully compatible.

It didn't actually... It ended after almost 48 hours. I had to clean every trace of anaconda in my PC, uninstall it and install it again. It came with Spyder 4.3.5 instead of the 4.3.2 I had when the kernel crashed every time I run and matplotlib function. With this new version, the problem is apparently gone.
