### ISSUE TITLE
Transition from console to editor by line number doesn't work

### ISSUE THREAD

**Issue by poormag** [spyder-ide/spyder#15282]
In case of error, the console previously had the ability to go to the line in the editor, now this feature is absent...

```
  File "test.py", line 35, in function1
    angle = float(obj[5])*np.pi/180

IndexError: index 5 is out of bounds for axis 0 with size 5
```
For example I can not press line 35 to go to the line in the editor for checking my code...

**Comment by dalthviz** [comment]
Hi @poormag thanks for the feedback! I think this issue is a duplicate of https://github.com/spyder-ide/spyder/issues/15166 . A fix was already done and will be available in our next release (Spyder `5.0.1`) :)
