### ISSUE TITLE
Plots are overwritten on inline mode (Spyder 5.0)

### ISSUE THREAD

**Issue by je-santos** [spyder-ide/spyder#15283]
Dear developers,

First of all, thanks for the great experience that Spyder 5 provides. I can't live without it.

I found a small bug after I updated to v5. 
Whenever I plot something like: 

plt.imshow(np.ones((3,3)))

the figure it is shown in the plot panes, but does not appear as an icon. Whenever I plot something else, it disappears. I have attached a screenshot. I'm using spyder 5 with python 3.8 in a windows machine.

Thanks!

![image](https://user-images.githubusercontent.com/42117435/114723431-4352e900-9d00-11eb-91d4-38a2547c26ad.png)

**Comment by dalthviz** [comment]
Hi @je-santos thanks for the feedback! Could you provide us an example code snippet to check this in our side. Any other info in order to reproduce this is greatly appreciated :)

**Comment by je-santos** [comment]
Hi @dalthviz,

Thanks for your prompt response. It was a bizarre error on my end which I solved by creating a new environment. It looks good now.

Thanks, Spyder 5 is 🔥

**Comment by dalthviz** [comment]
Thanks for your response @je-santos ! Glad is working for you know :)
