### ISSUE TITLE
Error in installing  scikit-learn==0.20.3

### ISSUE THREAD

**Issue by mohanasrujana** [spyder-ide/spyder#15286]
### What steps will reproduce the problem?

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\Srujana\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Srujana\\AppData\\Local\\Temp\\pip-install-sqv_3fh9\\scikit-learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\Srujana\\AppData\\Local\\Temp\\pip-install-sqv_3fh9\\scikit-learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Srujana\AppData\Local\Temp\pip-record-gxvw4l3h\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\Srujana\anaconda3\Include\scikit-learn' Check the logs for full command output.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by stonebig** [comment]
for this you  may try:
`pip install msvc_runtime`

**Comment by dalthviz** [comment]
Thanks @stonebig for the help! @mohanasrujana let us know if something of the above helps :)

**Comment by mohanasrujana** [comment]
I have tried the suggestion by @stonebig . But i am still getting the same error

**Comment by dalthviz** [comment]
Hi @mohanasrujana after checking this and your other issue report (#15285), seems like the errors are unrelated to Spyder and ratter related with `scikit-learn`. The issues you are having maybe are related with the discrepancy between the `scikit-learn` version used for training your model and running it (building vs loading the model). Also, maybe creating a new environment with the right version of `scikit-learn` could be easier for you than trying to upgrade or downgrade your current env (which seems like is some how corrupted).

There is not much we can do in our side to help you but hope the info above helps :)
