### ISSUE TITLE
Plot A List Of Floats In Variable Explorer Not Possible

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1529]
_From [AxelMich...@gmail.com](https://code.google.com/u/111817611783299914193/) on 2013-08-22T08:20:45Z_

Spyder Version:  2.2.2
Python Version:  2.7.2
Qt Version:      4.7.3, PyQt4 (API v1) 4.8.5 on Windows 

What steps will reproduce the problem?

1. I have a list of 8 floats.
2. In Variable Explorer, select the variable (vbg2 in this case) with right mouse-button click and click on a 'Plot'.

What is the expected output? What do you see instead?

No plot is generated.
See error messages attached. 

Please provide any additional information below

.

**Attachment:** [spyder_plot_error.png](http://code.google.com/p/spyderlib/issues/detail?id=1529)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1529_

**Comment by spyder-issues-migrator** [comment]
_From [jcbretz@sym....com](http://code.google.com/u/115430633681747940486/) on 2013-08-22T08:20:45Z_

I am also having this problem - any fix in the works?

**Comment by ccordoba12** [comment]
I'll take a look at it for our next release

**Comment by ccordoba12** [comment]
This is not an error anymore. It seemed a problem just with guiqwt, so please report the problem with its maintainers.
