### ISSUE TITLE
Open spyder error report

### ISSUE THREAD

**Issue by TinsenLY** [spyder-ide/spyder#15309]
## Description

**What steps will reproduce the problem?**

1. Open spyder
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\anaconda3\envs\tf-gpu_210\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by juanis2112** [comment]
Hi @TinsenLY. You seem to be using a very old version of Spyder. I suggest updating to spyder 4.
Open your anaconda prompt and run 
```
conda update anaconda
conda install spyder=4.2.5
```

**Comment by dalthviz** [comment]
Closing due to lack of response. However, just in case, such error could be related with the version of numpy and pandas being use
