### ISSUE TITLE
Install/Uninstall Kite makes plot pane uncloseable.

### ISSUE THREAD

**Issue by jwoehr** [spyder-ide/spyder#15311]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Since installing and removing (with difficulty) Kite the Plots pane will not close.
The option to uncheck it is greyed out.
I have uninstalled and reinstalled Spyder 5 and I cannot close the plots pane.

### What steps reproduce the problem?

1. Install Kite
2. Uninstall Kite
3. Try to close plots pane

### What is the expected output? What do you see instead?
Plots pane checkmark greyed out.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.2
* Qt version: 
* PyQt version: 
* Operating System name/version: Mac OS Big Sur 11.2.3

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by jwoehr** [comment]
Managed to close it with "close current pane" after all other panes closed. That is the only way

**Comment by ccordoba12** [comment]
This will be fixed in 5.0.1.

**Comment by jwoehr** [comment]
Thanks @ccordoba12
