### ISSUE TITLE
Dataframe viewer cannot show "_" in column names

### ISSUE THREAD

**Issue by mIgLLL** [spyder-ide/spyder#15320]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When a variable name with "_", such as "a_a", you can just see "a a" in the column rather than "a_a"

![image](https://user-images.githubusercontent.com/31037879/115099664-f5d9b480-9f69-11eb-85e2-22d159531254.png)

### What steps reproduce the problem?

1. import pandas as pd
2. a=pd.DataFrame()
3. a['a_a']=1
4. Open the variable explorer and check the column name of "a_a"

### What is the expected output? What do you see instead?
See the "a_a" instead.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.3 （since 4.1.x , I forgot when, and it still happends in 5.0.0）
* Python version: 3.8.8
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @mIgLLL, thanks for reporting. We'll take a look at it for our next version.
