### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by drklingman** [spyder-ide/spyder#15334]
### What steps will reproduce the problem?

On Spyder 5.0.0 startup, the message

"You have missing dependencies!

# Mandatory:
spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)

Please install them to avoid this message."

is displayed.  I have 2.0.1 installed and it appears that it is the latest version available.

**Comment by stonebig** [comment]
Solved in Spyder-5.0.1 ... maybe upgrade ?

**Comment by drklingman** [comment]
> Solved in Spyder-5.0.1 ... maybe upgrade ?

I tried to under Anaconda and it doesn't find ver. 5.0.1.  Did a 'conda update --all' and Spyder stopped working altogether.  I think I'm going to drop Anaconda, it's been quirky under the MacOS.  Thanks for the reply.

**Comment by stonebig** [comment]
otherwise the fix for Spyder -5.0.0 is a single character
https://github.com/spyder-ide/spyder/pull/15097/files

**Comment by ccordoba12** [comment]
@drklingman, this problem will be fixed as soon as Anaconda uploads packages for our 5.0.1 version, released last Friday. Until then, please be patient and ignore that warning.
