### ISSUE TITLE
Help pane cannot be toggled persistently in Spyder 5

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#15331]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The 'Help' pane cannot be toggled persistently during restarts of spyder, instead, for every start of spyder I get the 'Help' pane to show up.

### What steps reproduce the problem?

1. Start spyder. The 'Help' pane shows.
2. Uncheck `View->Panes->Help`. The 'Help' pane disappears.

### What is the expected output? What do you see instead?

Restart spyder. It would be reasonable to expect that previously done adjustments of settings are persistent. However, the 'Help' pane is back after restart, including the previously unchecked check mark in `View->Panes->Help` pulldown menu.

## Versions
* Spyder version: 5.0.1 None
* Python version: 3.7.10 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 4.12.14-lp151.28.91-default

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by ccordoba12** [comment]
Hey @xaverm, thanks for reporting. This is clearly a bug and we'll try to fix it in the coming months.

**Comment by brhubbar** [comment]
I've been noticing this issue as well. If Help is in its own stack (no other tabs to choose from) and is then closed (removing the stack), that stack will be restored upon restart of Spyder. If it is in a stack with other panes, then closed, leaving the remaining panes, Help will be restored and activated upon restart of Spyder.

**Comment by xaverm** [comment]
I love you guys and your work on this project!!! ... even if you won't fix this little annoyance ever ... maybe make it a New Year's resolution?

**Comment by dalthviz** [comment]
Hi @xaverm although this is not solved yet something you could do for now (if you use at least Spyder 5.2.0) is to completly disable the `Help` pane by going to `Tools > Preferences > Plugins` and unchecking `Help`.

**Comment by ccordoba12** [comment]
@xaverm, I have an idea on how to fix this. So it'll probably land in 5.2.2, our first version in 2022.

**Comment by xaverm** [comment]
So it **is** a New Year's resolution. Amazing. I'll be eager to check out 5.2.2.

**Comment by xaverm** [comment]
yippee!
