### ISSUE TITLE
Spyder Notebook installation on spyder 5 (standalone installation) 

### ISSUE THREAD

**Issue by Jacques2101** [spyder-ide/spyder#15344]
Hi, 
I would like to install Spyder-Notebook extension on Spyder version 5.0.1. 
I have installed the standalone application. 

Thx for your help.

**Comment by ccordoba12** [comment]
This is not possible at the moment because we don't package spyder-notebook with our installer. There are plans to do that in the future, but nothing concrete yet, sorry.
