### ISSUE TITLE
ipython console get different result in spyder

### ISSUE THREAD

**Issue by psn417** [spyder-ide/spyder#15357]
Hi!
I find that when I use ipython outside spyder, I can run the code successfully. 
![1](https://user-images.githubusercontent.com/36497958/115360158-f3898b80-a1f1-11eb-863e-cb88d7e2dd80.JPG)

but when I use the ipython within spyder, I get an error
![2](https://user-images.githubusercontent.com/36497958/115360558-4d8a5100-a1f2-11eb-85fe-c5d48d7a1eb3.JPG)

I'm using spyder 5.0.0.

**Comment by psn417** [comment]
* Spyder version: 5.0.0 None
* Python version: 3.8.5 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 3.10.0-1160.15.2.el7.x86_64

**Comment by psn417** [comment]
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by steff456** [comment]
Hi @psn417,

Are you using the same version of the ipython in both cases?

**Comment by psn417** [comment]
> Hi @psn417,
> 
> Are you using the same version of the ipython in both cases?

yes, I'm using the same version of ipython (it's the ipython within anaconda).

**Comment by ccordoba12** [comment]
Do you use LD_LIBRARY_PATH or a similar trick to add libraries to the linker?

**Comment by psn417** [comment]
> Do you use LD_LIBRARY_PATH or a similar trick to add libraries to the linker?

Yes. The lammps module is install by modifying LD_LIBRARY_PATH.
I find that the error is caused by other reasons. It won' occur if i use another anaconda version, or use python2.7. So it may not  related with spyder. Maybe it is the problem of anaconda.

**Comment by psn417** [comment]
After I upgrate python to 3.8.8, spyder works correctly.
Thank you for you reply!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
