### ISSUE TITLE
Text and icon overlap in options

### ISSUE THREAD

**Issue by XingLiu1** [spyder-ide/spyder#15369]
### What steps will reproduce the problem?

I update spyder to version 5.0.0 and
Text and icon overlap in options

**Comment by XingLiu1** [comment]
![image](https://user-images.githubusercontent.com/46082449/115523244-74fb1f80-a2bf-11eb-86de-7bdb3e35b7e3.png)

**Comment by ccordoba12** [comment]
Hey @XingLiu1, thanks for reporting. This is already fixed in our 5.0.1 version, released last Friday and that will be part of Anaconda soon.
