### ISSUE TITLE
kernel problem after upgrading to syper 5 via brew on BigSure OSX

### ISSUE THREAD

**Issue by duemme** [spyder-ide/spyder#15364]
Hello, I'm having a problem after upgrading spyder to version 5.
Spyder 5 tells me "An error ocurred while starting the kernel", "Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.0.1 and < 2.1.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels"

I was using Spyder 4 with 3.9.1_8, with no problems.
Both Spyder and Python installed via Home Brew. When I installed Spyder 4 I had to manually select the interpreter looking for the python bin installed by home brew and run pip3 install spyder-kernels and everything worked just fine.

Then I upgraded both python (3.9.1_8 -> 3.9.4) and Spyder (v. 5) via Home Brew and I get the error.
I selected the new interpreter but the problem is still there.

If run pip3 install spyder‑kernels

I get this error:
ERROR: Invalid requirement: 'spyder‑kernels'

Do I need to wait for a new version of the software?

**Comment by duemme** [comment]
Downgraded to Spyder 4 and everything works again.

**Comment by steff456** [comment]
Hi @duemme,

Can you please install in a clean environment Spyder 5.0.1 if you want we now have installers for mac that you can download from here: https://github.com/spyder-ide/spyder/releases/tag/v5.0.1 

Please let me know if it works

**Comment by duemme** [comment]
Thanks for the replay but it doesn't work.

**Comment by steff456** [comment]
For installing Spyder in a new environment please do, 

```
conda create -n my-env python=3.9
conda activate my-env
conda install spyder=5.0.1 -c conda-forge
```

Note: I'm putting the `conda-forge` channel because anaconda default channel doesn't have the latest Spyder version yet.

Then you can run spyder in that environment and install the other packages you need,

Please let me know if this works

**Comment by duemme** [comment]
I'm not using anaconda.
I installed python and spyder using homebrew.
I'm not sure that mixing conda and brew it's safe.

**Comment by steff456** [comment]
We don't make the brew package, so we don't recommend it. If you want you can try uninstalling python and spyder from homebrew and then install anaconda's latest version. Once you've done that you should be able to use the `conda` command in your terminal and install Spyder from there or one of our installers.

**Comment by duemme** [comment]
ok, thanks for your help.
