### ISSUE TITLE
code reformat not working in latest version of spyder

### ISSUE THREAD

**Issue by pctablet505** [spyder-ide/spyder#15360]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
On pressing Ctrl + Alt + I 
codes are not being reformatted.

### What steps reproduce the problem?

1. Press Ctrl + Alt + I 
2. go to source menu and click autoformat file

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @pctablet505,

Can you please let me know what version of Spyder are you running? Also, have you changed any preference?

**Comment by pctablet505** [comment]
5.01

**Comment by steff456** [comment]
Can you please give me an example of the code you are trying to format?

**Comment by pctablet505** [comment]
befoe reformat on spyder 4.2.5
`import numpy as np
a=np.array(([
    [1,2,3,4],
             [5,6,7,8],
             9,10,11,12]))`

after reformatting
`import numpy as np
a = np.array(([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    9, 10, 11, 12]))
`

But the same is not happening in spyder 5.0.0 and spyder 5.0.1

**Comment by ccordoba12** [comment]
@pctablet505, how did you install Spyder? Using pip or Anaconda?

**Comment by pctablet505** [comment]
I installed using pip on ubuntu and windows,
and spyder_5 setup.exe on windows.

**Comment by ccordoba12** [comment]
Ok, thanks. Then please read our Troubleshooting Guide:

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by ccordoba12** [comment]
You can also use our [Windows installer](https://github.com/spyder-ide/spyder/releases/download/v5.0.1/Spyder_64bit_full.exe) instead.
