### ISSUE TITLE
Graphics. Icons appearing on the menu list

### ISSUE THREAD

**Issue by Ego-max** [spyder-ide/spyder#15377]
### What steps will reproduce the problem?

I updated my spyder 4 to 5 and when I opened the file menu, the icons of the list appeared on top of the options. This is really disturbing and reading issues also may occour.

**Comment by ccordoba12** [comment]
Hey @Ego-max, thanks for reporting. This is fixed in our latest version (5.0.1), which should be part of Anaconda soon.

**Comment by Ego-max** [comment]
Ok thank you
