### ISSUE TITLE
Menu Options Symbols Overwritten by Menu text

### ISSUE THREAD

**Issue by robert99** [spyder-ide/spyder#15375]
### What steps will reproduce the problem?

Spyder 5 Menu options have a symbol then text.
For example, Print shows a printer symbol then text that should be "Print".
On my system (Windows 10, Python 3.8 Anaconda), the printer symbol has "Pr" text on top of it then "int" follows.
Same issue throughout makes menu options very hard to read.

PS. Could the green triangle for "Run" be made bigger/ darker? Hard to find at first.

**Comment by ccordoba12** [comment]
Hey @robert99, thanks for reporting. This is already fixed in our 5.0.1 version, released last Friday and part of Anaconda soon.
