### ISSUE TITLE
[5.0.1] Connect remote kernel -> Permission Denied

### ISSUE THREAD

**Issue by thistlillo** [spyder-ide/spyder#15371]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have just
- uninstalled Spyder 4
- installed Spyder 5.0.1
I have an error related to an access violation when Spyder tries to access my own user folder while connecting to a remote kernel.

### What steps reproduce the problem?

1. In the menu of the Console pane, select "Connect to an existing kernel" 
2. Tick "This is a remote kernel (via SSH)
3. Insert your data, then OK
4. The error in the attached image is shown.

### What is the expected output? What do you see instead?
I would not expect an error related to a "permission denied" to read from my own Application Data.

## Versions

* Spyder version: 5.0.1
* Python version: 3.7.9 64-bit  
* Qt version: 5.12.10
* PyQt version:  5.12.3
* Operating System name/version: Windows 10 Pro
* 
![spyder-error](https://user-images.githubusercontent.com/6717655/115550577-4d4d8c80-a2aa-11eb-9e6a-fd0138315459.png)

**Comment by ccordoba12** [comment]
Hey @thistlillo, thanks for reporting. You need to fix your permissions for that folder because we can't do that for users in Spyder.

This usually happens when people started Spyder or Jupyter as an Administrator.

**Comment by thistlillo** [comment]
I have just installed spyder for all users, clearly elevating the installation process. What am I supposed to do to correct?

**Comment by ccordoba12** [comment]
Maybe making that folder readable for all users? I'm not really sure, sorry.

**Comment by thistlillo** [comment]
Ok, since I am not able to fully understand what happens if I open that folder to "All Users", I think I will reinstall Spyder for my user only.

But this is not normal behaviour. You closed this thread, but - may be - you should evaluate to remove the possibility to install the app for "All Users", it is clearly broken.
