### ISSUE TITLE
Feature Request for Future: Remote-SSH X11 Forwarding for Debugging mode

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#15395]
This is gonna be a feature request for the upcoming spyder Probaby a year or so from now.

I know that you guys are working on the feature that can make spyder be able to connect to the remote server as a remote ide. 
It would be nice if when that feature is included also have the features that make us be able visualize while debuging as we can do it now in spyder (eg visualize images and stuff).

I think they call it Remote-SSH X11 Forwarding for display, TBH spyder has a very nice debugging set up and in the future if we have remote-server option it would be awesome to has the ability of displaying images while debugging.
I had to switch to vscode due to remote-server limitation of spyder, but if one day we have it in spyder i will switch.
vscode still suffer from Remote-SSH X11 Forwarding and display images while debugging, so it would be nice if you guys dont have this issue in the future...
Thanks

**Comment by juanis2112** [comment]
Hi @seyeeet thanks for opening this. What do you think about this @spyder-ide/core-developers

**Comment by ccordoba12** [comment]
Sorry @seyeeet but this is not something we can handle in Spyder. It requires special configurations both in the remote server and in your local machine, and it's not easy to setup (at least that's what I remember when I tried to do it).

> if we have remote-server option it would be awesome to has the ability of displaying images while debugging

For that you can use now the Plots pane and static images. For Spyder 6 we plan to add a new pane to visualize web content, so then you'll be able to use the Matplotlib web backend, which has the same features as the Automatic one.
