### ISSUE TITLE
Fedora 33 - Spyder 4.1.5 - Linting Not Working

### ISSUE THREAD

**Issue by Shadmeister** [spyder-ide/spyder#15391]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
With an editor open, and Preferences -> Completion and Linting -> Linting -> Enable Linting/Underline errors and warnings selected, linting and warnings do not work. It worked in Spyder 3 on Fedora 32, and does not function in F33. 

I have checked the closed issues and run through the libraries that others have had issues with, and my installation seems to be ok. 
### What steps reproduce the problem?

1. Set the relevant options for linting, restsrt Spyder 4 and run a test file with error to invoke linting
2. I have tried to output the debug to a file, but this fails to work.
3. 

### What is the expected output? What do you see instead?
Warnings and errors highlighted in the margin and within the text.

### Paste Traceback/Error Below (if applicable)

```python-traceback

No traceback

```

## Versions

* Spyder version: 4.1.5 None
* Python version: 3.9.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.0
* Operating System: Linux 5.11.14-200.fc33.x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.18.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
keyring                        :  None (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.3 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
xdg >=0.26                     :  0.26 (OK)
zmq >=17                       :  19.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.3.4 (OK)
numpy >=1.7                    :  1.19.4 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.4 (OK)
sympy >=0.7.3                  :  1.7.1 (OK)
```
Code typed to invoke linting notifications/warnings :

import numpy as np 
import matplotlib.pyplot as plt 

X = np.linspace(-np.pi, np.pi, 256, endpoint=True) 
C, S = np.cos(X), np.sin(X) 
plt.plot(X, C) 
plt.plot(X, S) 
plt.show()
m = 4.0

The variable m should show an error as never used.

**Comment by ccordoba12** [comment]
Please read our Troubleshooting Guide:

http://docs.spyder-ide.org/current/first-steps.html

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom or distro installations, so it's up to you to figure this one out.

**Comment by ccordoba12** [comment]
You can also report this problem to your distro maintainers to see if they can help you.

**Comment by Shadmeister** [comment]
For information :
After using the command line debug mode and examining the logs - installed libraries and linting now working.

Raised a bug with redhat to include the relevant libraries as dependencies when installing python3-spyder. 
https://bugzilla.redhat.com/show_bug.cgi?id=1952890

**Comment by ccordoba12** [comment]
Great! Thanks for your help to track that problem down.

**Comment by Shadmeister** [comment]
Hi @ccordoba12 ,
To add further, as per redhat bug raised, from the response, it is possible that the github repo for Spyder does not include all the information for a Spyder installation for linting to function. 
https://bugzilla.redhat.com/show_bug.cgi?id=1952890#c2
Regards,
Shadmeister.
