### ISSUE TITLE
Overlapping Icons in Menus

### ISSUE THREAD

**Issue by sirinath** [spyder-ide/spyder#15404]
There are icons overlapping the text in menus:

![image](https://user-images.githubusercontent.com/637415/115883851-e11a8680-a46b-11eb-89a9-1da84ea1c959.png)

![image](https://user-images.githubusercontent.com/637415/115883924-f5f71a00-a46b-11eb-8395-33061f021bbe.png)

**Comment by ccordoba12** [comment]
Hey @sirinath, thanks for reporting. This bug is already fixed in our 5.0.1 version, released last week and soon to be part of Anaconda.
