### ISSUE TITLE
Help pane not connected to Editor for local packages

### ISSUE THREAD

**Issue by physici** [spyder-ide/spyder#15400]
## Problem Description
In Spyder 5.0.0 the Help pane does not seem to be connected to the Editor window. Online help of functions is shown correctly as tooltips, but CNTRL+I does not retrieve the docstring in the Help-pane.

### What steps reproduce the problem?

1. In IPython load custom module
2. enter a function and press CNTRL + I at the end of the function -> Docstring displayed in Help pane (see 1st screen gif)
3. Repeat in Editor -> Help pane shows "No documentation available" (see 2nd screen gif)
4. 
### What is the expected output? What do you see instead?
Help pane should show the Doc string as it does when triggered from IPython

## Versions

* Spyder version: 5.0.0
* Python version: 3.8.6
* Qt version: 
* PyQt version: 5.12.3
* Operating System name/version: Win10 64bit

### Dependencies
![Ipython](https://user-images.githubusercontent.com/15417017/115823889-6f105600-a407-11eb-92d8-f4fb30f375a3.gif)
![edit](https://user-images.githubusercontent.com/15417017/115824165-d3cbb080-a407-11eb-86a5-2791a7f07217.gif)

**Comment by juanis2112** [comment]
Hi @physici thanks for reporting this. Can you try downloading Spyder 5.0.1 from our webpage https://www.spyder-ide.org/#section-download and let me know if this issue persists?

**Comment by physici** [comment]
I've upgraded to 5.0.1, but the problem persists.

**Comment by ccordoba12** [comment]
@physici, do you have Kite installed?

**Comment by physici** [comment]
I don't. Vanilla Spyder.

**Comment by KevinNadaud** [comment]
I have similar problem with spyder 5.0.1 (from pip) on Linux Mint .
In my case, even for a installed library such numpy, help pane does not work. 
It works well from the console even for my own modules.

**Comment by physici** [comment]
Is there any update here?

**Comment by shcrela** [comment]
Same problem, Spyder 5.0.4.

**Comment by gersonjferreira** [comment]
Still the same problem with Spyder 5.0.5 installed from pip. Could it be a missing dependency? 

Help pane works from iPython but bugs if it comes from the Editor.
