### ISSUE TITLE
why-does-python-not-pick-up-a-global-variable

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#15408]
Is this normal and expected? Why? 

https://stackoverflow.com/questions/67245429/why-does-python-not-pick-up-a-global-variable

Screenshot:

![image](https://user-images.githubusercontent.com/9833299/115967818-b8919b80-a502-11eb-99fa-26e41b1ef41c.png)

**Comment by ccordoba12** [comment]
See here:

https://stackoverflow.com/questions/59271717/override-global-variable-inside-function-not-working-with-spyder-4

By default we run files in an empty namespace to avoid picking up variables declared in the console which makes users code non-reproducible.

**Comment by nerdfever** [comment]
Thanks! Somebody really needs to write a proper user's guide for Spyder - there is so much functionality that's only hinted at by the UI and needs to be explained.

I'm willing to donate some $$ if there's a willing person who wants to get paid for doing it.

**Comment by ccordoba12** [comment]
> there is so much functionality that's only hinted at by the UI and needs to be explained.

I understand your frustration but we try to do our best: http://docs.spyder-ide.org/current/index.html

I think we could add this specific issue to our FAQ though: http://docs.spyder-ide.org/current/faq.html

> I'm willing to donate some $$ if there's a willing person who wants to get paid for doing it.

Please send me an email so we can discuss about it. It'd be great to know what other things you think need better docs in Spyder.

My email is here:

https://github.com/ccordoba12
