### ISSUE TITLE
Hungarian Keyboard Left Bracket does not work

### ISSUE THREAD

**Issue by totlasz** [spyder-ide/spyder#15402]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by totlasz** [comment]
On my Hungarian keyboard  to insert left bracket ( [ )  into to a program script  I should press Ctrl+Alt+F .
Using Spyder 5 nothing happens when I press this combination.   The cursor stays as it is.
With Spyder 4.2.5  I do not have such a problem., this is definitely not a hardware issue, 
I am using Windows 10.   Alt Gr + F does not work either.

**Comment by ccordoba12** [comment]
@totlasz, thanks for reporting. We'll see what we can do about this.

@jnsebgosselin, any ideas about it?

**Comment by ccordoba12** [comment]
Sorry but we don't have a way to test this. At least you can use our 4.2.5 version for now.

**Comment by akkiss** [comment]
I have similar problem through RDP. When connecting to the Windows 10 desktop through RDP, in Spyder 5, when pressing "Alt Gr + F" (hungarian keyboard), nothing happens ('[' should appear). Works fine in Spyder 4.
Tried to set this combination as keyboard shortcut to check if this is due to an assigned function, but is says no conflicts (identifies as Ctrl+Alt+[).

**Comment by akkiss** [comment]
> I have similar problem through RDP. When connecting to the Windows 10 desktop through RDP, in Spyder 5, when pressing "Alt Gr + F" (hungarian keyboard), nothing happens ('[' should appear). Works fine in Spyder 4.
> Tried to set this combination as keyboard shortcut to check if this is due to an assigned function, but is says no conflicts (identifies as Ctrl+Alt+[).

Realized that something happens, the find window is activated when I press AltGr+'F'. In the keyboard shortcuts 'switch to find_in_files' had Ctrl+Alt+'F' assigned to it.
Removed the shortcut, but it still activated find_in_files window.
Restarted spyder, still the same.
Set a different shortcut to 'switch to find_in_files', the shortcut works but still does AltGr+'F'.

**Comment by akkiss** [comment]
It seems there has been a similar issue a few years back, maybe it is of similar nature.
https://github.com/spyder-ide/spyder/issues/220

**Comment by akkiss** [comment]
Funny thing is when I press AltGr+F using US layout, it simply drops down File menu, with US layout setting a shortcut to AltGr+F identifies as Alt+F

**Comment by akkiss** [comment]
Found a solution to the problem. There is a "find_in_files/find in files" shortcut which is Ctrl+Alt+F by default. If I'm not mistaken this should only be triggered in the find_in_files panel's context, however this seem to be activated in both the editor and the interactive console because if I change this shortcut to something different, the '[' works fine with HU layout.

**Comment by totlasz** [comment]
Dear Ákos,

Thank you,  changing the  Ctrl+Alt+F  shortcut as you suggested really
solves the problem.
Would be nice if the  next Spyder version would be released   without
this bug. 

László Tóthfalusi 





>>> Ákos Kiss ***@***.***> 07/28/21 4:09 PM >>>

 Found a solution to the problem. There is a "find_in_files/find in
files" shortcut which is Ctrl+Alt+F by default. If I'm not mistaken this
should only be triggered in the find_in_files panel's context, however
this seem to be activated in both the editor and the interactive console
because if I change this shortcut to something different, the '[' works
fine with HU layout.

**Comment by dalthviz** [comment]
Hi @akkiss thanks for digging into this and finding a workaround! Just in case, the current open issue related with this bug is https://github.com/spyder-ide/spyder/issues/15654

**Comment by dvulin** [comment]
the same issue happens (and the same is workaround) with Slovakian and Croatian keyboards. @Ákos, you are a life-saver, big thanks.

**Comment by Zagyvaakos** [comment]
You have to change the find in files shortcut (ctrl+alt+f) to something else and it will work!
I 've just ran into this bug too, changed to ctrl+alt+o and voila alt+f works, i can write left bracket now

**Comment by ccordoba12** [comment]
@dvulin, this problem is fixed in our latest version (5.2.0) released a week ago.
