### ISSUE TITLE
Figures from different Consoles are not shown

### ISSUE THREAD

**Issue by Tissot11** [spyder-ide/spyder#15411]
## Problem Description
If you open two consoles in Spyder 5.0.1 and plot figures in each panels. Then on switching to consoles, you only see the figures from the last consoles shown in all plots panels. This was not the case before. and it appears to be a problem in Spyder 5.0.1.

### What steps reproduce the problem?

1. Open two Consoles. Run some scripts to plot something using matplotlib in each Console.
2. Try to switching between these two Consoles. You only see the figure from the last run in the last Console.

### What is the expected output? What do you see instead?

On switching to different Consoles, one should figures, plots etc corresponding to that scripts run in that consoles.

**Comment by ccordoba12** [comment]
@Tissot11, thanks for reporting. You're totally right and we haven't noticed it.

We'll try to fix it in our next version.
