### ISSUE TITLE
Improve spyder-kernels installation message

### ISSUE THREAD

**Issue by bolton-lab** [spyder-ide/spyder#15420]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I install Spyder 5.0.1 Spyder.dmg on Mac BigSur and I try to change the environment to the conda installation I get:
```
Your Python environment or installation doesn't have the spyder‑kernels module or the right version 
of it installed (>= 2.0.1 and < 2.1.0). Without this module is not possible for Spyder to create a console 
for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels
```
I already have spyder-kernels and installing with conda doesn't change anything.

### What steps reproduce the problem?

1. Use Spyder.dmg installer
2. Change to conda python as the interpreter `/Users/brian/anaconda3/bin/python`
3. 

### What is the expected output? What do you see instead?
In my Spyder4 version I installed with conda initially after Anaconda installation I can change to the conda env as well as any other conda venv and it works fine.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Our instructions are not quite explicit about what you need to do. Please run instead:

    conda install spyder-kernels=2.0.1

If that gives you an error, please run first

    conda update anaconda

**Comment by bolton-lab** [comment]
great worked with reinstall of Spyder.dmg!

**Comment by bolton-lab** [comment]
Shoot didn't mean to close if you want to update message in console

**Comment by ccordoba12** [comment]
Yeah, thanks @bolton-lab for reopening it! I'll update that message with more explicit instructions for our next version.
