### ISSUE TITLE
use coverage.py to measure test coverege

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1543]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-08-30T06:26:10Z_

There is this nice tool called coverage.py ( http://nedbatchelder.com/code/coverage/ ) that generates some reports regarding test coverage of your code. For VIM there exists a plugin that uses that report to mark the lines/functions/classes that are not covered by tests ( http://www.vim.org/scripts/script.php?script_id=4292 ). This might be a nice feature to have in Spyder as well.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1543_

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-08-30T04:29:42Z_

A request for unittest/nose support in Spyder is mentioned in issue #219

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-08-30T05:05:41Z_

**Status:** New

**Comment by spyder-issues-migrator** [comment]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2014-12-12T10:53:01Z_

I'm going to try and make a plugin for this. I'm not used to PyQT (I prefer wxPython) so it might take some time. But at least you know that someone is working on it!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-12T14:05:13Z_

Great to hear it! Thanks for the effort and let us know when you have something working.

**Status:** HelpNeeded

**Comment by spyder-issues-migrator** [comment]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2014-12-15T11:05:03Z_

Attached is an unpolished-but-mostly-working plugin for coverage. The default kb shortcut is Alt+F11.

Install Steps:
1. Put p_coverage.py in %pythonpath%\Lib\site-packages\spyderplugins
2. Put coveragegui.py in %pythonpath%\Lib\site-packages\spyderplugins\widgets
3. Load up spyder. It *should* work.

The code is hosted at https://github.com/dougthor42/spyder-coverage-plugin

**Attachment:** [p_coverage.py coveragegui.py](http://code.google.com/p/spyderlib/issues/detail?id=1543#hc6)

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-12-18T12:53:32Z_

We really need a simpler way to install plugins...

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-18T13:32:00Z_

Yes, I'm going to work on it for 2.4.

Great work by the way Doug!

**Comment by spyder-issues-migrator** [comment]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2014-12-18T14:53:56Z_

Thanks, although it seems like all I really did was rename a bunch of variables from Pierre's pylintgui.py :-D

There are still a few things I think should be added. These features can be found as issues in the github repo, but I don't think that any of them are gating a release.

Also, I would recommend downloading the plugin files directly from the repo rather than the attachments in my post - a minor tweak have been made which makes the output a little cleaner (fixes Github Issue `#1` : program output added to results).

**Comment by dougthor42** [comment]
Adding comment so that I get notifications and so that I can find my issues/comments more easily.

**Comment by goanpeca** [comment]
This has been implemented already with https://github.com/spyder-ide/spyder/pull/3803 and we are using [coveralls](https://coveralls.io/github/spyder-ide/spyder)
