### ISSUE TITLE
spyder doesn't start

### ISSUE THREAD

**Issue by vardhan-siramdasu** [spyder-ide/spyder#15438]
## Problem Description
spyder won't be responding while starting by using terminal or anaconda navigator

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

Application launch error

Application spyder launch may have produced errors.

Traceback (most recent call last):
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3718, in main
mainwindow = run_spyder(app, options, args)
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3559, in run_spyder
main.setup()
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 1277, in setup
self.apply_shortcuts()
File "D:\anaconda\lib\site-packages\spyder\app\mainwindow.py", line 3189, in apply_shortcuts
plugin_name))
File "D:\anaconda\lib\site-packages\spyder\config\manager.py", line 305, in get_shortcut
return config.get('shortcuts', context + '/' + name.lower())
File "D:\anaconda\lib\site-packages\spyder\config\user.py", line 976, in get
return config.get(section=section, option=option, default=default)
File "D:\anaconda\lib\site-packages\spyder\config\user.py", line 513, in get
raise cp.NoOptionError(option, section)
configparser.NoOptionError: No option 'find_replace/find next' in section: 'shortcuts'

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @vardhan-siramdasu, thanks for reporting. Please close Spyder, open the Anaconda Prompt, run there

    spyder --reset

and try again.

That should fix your problem.

**Comment by vardhan-siramdasu** [comment]
> Hey @vardhan-siramdasu, thanks for reporting. Please close Spyder, open the Anaconda Prompt, run there
> 
> ```
> spyder --reset
> ```
> 
> and try again.
> 
> That should fix your problem.

It won't working @ccordoba12

**Comment by ccordoba12** [comment]
Sorry but without additional information we can't give more feedback.

**Comment by ccordoba12** [comment]
I saw that in your other issue you posted that your Spyder version is **4.0.1**. So please open the Anaconda Prompt and run there

    conda update anaconda
    conda install spyder=4.2.5

That should solve your problem.

**Comment by vardhan-siramdasu** [comment]
thank u @ccordoba12 issue resolved
