### ISSUE TITLE
Visual representation of profiler results

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1544]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-08-30T07:00:11Z_

Visualize profiling results using tools such as:
- runsnakerun ( http://www.vrplumber.com/programming/runsnakerun/ )
- gprof2dot ( https://code.google.com/p/jrfonseca/wiki/Gprof2Dot )
- KCachegrind ( http://kcachegrind.sourceforge.net/html/Home.html ) According to this ( http://blog.ionelmc.ro/2013/06/08/python-profiling-tools/ ) there are even windows binaries available
- others?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1544_

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-08-30T05:05:51Z_

**Status:** New

**Comment by goanpeca** [comment]
Its been three years and no extra feedback, closing.
