### ISSUE TITLE
Bad display of toolbar

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#15442]
![IMG_20210427_140626](https://user-images.githubusercontent.com/65082432/116193568-25ef3780-a762-11eb-98f5-3edc4fb6cffd.jpg)

This is spyder 5.0.1 on python 3.8.5

My desktop has a 200% enlarge HiDPI setting and I use auto-HiDPI on spyder

On spyder 4.2.5 it is fine.

**Comment by 1900011604** [comment]
![16195039070526590294132022857432](https://user-images.githubusercontent.com/65082432/116193818-84b4b100-a762-11eb-85cd-48024bb2bf0a.jpg)

as for here, the icons cannot display whole. This has not fixed in spyder 4 and 5

**Comment by steff456** [comment]
Hi @1900011604,

Can you please let me know which version of `qt`, `pyqt` are you using in your environment? If you change the HDPI setting the interface change?

**Comment by 1900011604** [comment]
qt 5.9.7/pyqt 5.9.2

**Comment by steff456** [comment]
Can you please create a new environment to run Spyder with conda-forge?

```
conda create -n my_env
conda activate my_env
conda install spyder=5.0.1 -c conda-forge
spyder
```

And let me know if you see the same that before

**Comment by DeltaMod** [comment]
I came here to report the same problem, though I run at standard DPI settings. Either way, I've created that environment and installed conda-forge, and found that the icons now display correctly as compared to my other spyder installation.
Hope that helps

**Comment by steff456** [comment]
Hi @DeltaMod,

Can you confirm me your current Spyder version?

**Comment by DeltaMod** [comment]
@steff456 
Sure!
Spyder 5.0.0 is the one that currently still has the problem, and that is the one I was using before installing 5.0.1 using conda-forge, which had all toolbar icons aligned properly. 
I would have tested also with `conda install spyder=5.0.1`, but it seems to not yet be in any of the conda repositories.

**Comment by steff456** [comment]
Thanks for the response, we fixed this problem in 5.0.1 and it is just available in conda-forge channel right now.

I just need to know if the problem persists with high DPI in the latest version.

**Comment by 1900011604** [comment]
I cannot install with conda-forge due to internet problems(?). But ver 5.0.1 is still not in conda
![Uploading 16203982384653479882199476385630.jpg…]()

**Comment by steff456** [comment]
Once the version is on anaconda and you update, can you please let us know if you continue having this issue?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by 1900011604** [comment]
> Closing due to lack of response.

Still Spyder 5.0.0 on my miniconda, so I cannot follow up.
