### ISSUE TITLE
matplotlib not being called

### ISSUE THREAD

**Issue by 2000samdavis** [spyder-ide/spyder#15453]
### What steps will reproduce the problem?

All I did was attempt to import matplotlib and I get an error that says "No module named 'matplotlib'". I used the commands:
import matplotlib.pyplot as plt
and
from matplotlib import pyplot as plt.

I've never had this issue before, and I don't know why it suddenly stopped working.

**Comment by dalthviz** [comment]
Hi @2000samdavis could you give us more information regarding your setup (how do you have Spyder installed, your OS, Python version, package dependencies installed, etc) and did you do any change recently in your setup?

Without more info there is not much we can do, sorry :/

Some resources that you could also check: https://docs.spyder-ide.org/current/troubleshooting/first-steps.html

**Comment by dalthviz** [comment]
Closing due to lack of response
