### ISSUE TITLE
Crashes!! anaconda is even more buggy!

### ISSUE THREAD

**Issue by keyofg-pi** [spyder-ide/spyder#15450]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
"A problem occurred" box pops up as soon as  I try to use spyder.

Anaconda 1.10 keeps flipping between spyder 4.1.5 and 5.0

also spyder cant import lumpy or Matplotlib even though condo update spyder worked perfectly and showed these "missing"
modules installed

**Comment by dalthviz** [comment]
Hi @keyofg-pi sorry to hear that, could you try to install Spyder latest version using conda-forge as channel in a new env and check if that helps? Also, I'm not sure about your issue regarding `numpy` or  matplotlib`, did you install them along side with Spyder but you are unable to import them? (To use numpy or matplotlib you need to install explicitly they are not Spyder dependencies)

Maybe our troubleshooting guide could be useful for you: https://docs.spyder-ide.org/current/troubleshooting/first-steps.html
Or maybe you could give a try to our installers (for MacOS or Windows): https://docs.spyder-ide.org/current/installation.html#standalone-installers-ref

Without more info there is not much we can do to help you, but let us know if checking something of the above helps you :)

**Comment by dalthviz** [comment]
Closing due to lack of response
