### ISSUE TITLE
Updates don't seem to be working.  

### ISSUE THREAD

**Issue by progpilgrim** [spyder-ide/spyder#15454]
### What steps will reproduce the problem?

Tried "conda update spyder" from command prompt twice.  Both times said it had completed.  Downloaded Spyder_64bit_full and ran it.  Still getting v4.1.5 and prompt to update when I open Navigator.

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.22.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.8.1 (OK)
pylint >=1.0                   :  2.7.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.0.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.23 (OK)
matplotlib >=2.0.0             :  3.3.4 (OK)
numpy >=1.7                    :  1.20.1 (OK)
pandas >=0.13.1                :  1.2.4 (OK)
scipy >=0.17.0                 :  1.6.2 (OK)
sympy >=0.7.3                  :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @progpilgrim, thanks for reporting. To update Spyder, please run the following commands:

    conda update anaconda
    conda install spyder=4.2.5

**Comment by progpilgrim** [comment]
Forgive me, but I'm a newbie.   FWIW, the instructions on the reference website say the command is simply "conda **update** spyder" rather than **install** with a specific v#.  I have "notify of updates at startup" checked on, or whatever the preference is.  It's telling me the latest spyder is v# is 5.0.0.  I downloaded a file called Spyder_64bit_full on 4/28.  It's 177,011KB.  Anyway, that's the one I ran and I expected the Navigator to reflect update.  Trying your suggestion.

When I run the commands you suggested, it completes the "update anaconda" command and tells me I have all current files.  I then specified that it should install spyder=5.0.0 since that appears to be latest and relaunching Navigator confirms Spyder is now 5.0.0.   So, thank you.  I ended up with desired outcome.

**Comment by progpilgrim** [comment]
In case anyone looks at this posting and follows, one more piece of info to add.  I got a Warning after installing Spyder 5.0.0. . .. .a message that reads:

Completion and linting in the editor for Python files will not work during the current session, or stopped working.
To try to fix this, please verify that your firewall or antivirus allows Python processes to open ports in your system, or restart Spyder.

I tried restarting Spyder several times and kept getting same warning.  Rather than mess with firewall or antivirus settings, I took ccordoba12's advice and installed spyder v 4.2.5 instead.  Noticed that there's a Settings Cog icon in the upper right of each app's box on Anaconda Navigator.  Within the pulldown, there's an option to select the version you want to install.  Once done, no longer getting the Warning.
