### ISSUE TITLE
Menu icons overlapped by menu text

### ISSUE THREAD

**Issue by MogensBLaursen** [spyder-ide/spyder#15461]
### What steps will reproduce the problem?

Activate any top menu of Spyder 5.0.0.
If a menu item has an icon, the icon and the text do overlap making the text less readable.

**Comment by ccordoba12** [comment]
Hey @MogensBLaursen, thanks for reporting. This is already fixed in our 5.0.1 version, released two weeks ago and soon to be part of Anaconda.
