### ISSUE TITLE
Spyder debugger gets out of context whenever there are panes undocked

### ISSUE THREAD

**Issue by jorgekoronis** [spyder-ide/spyder#15464]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Whenever there is any pane undocked in Spyder 5.0.0 GUI, step debugging does not work properly. The user must click on the editor pane after every breakpoint in order to be able to launch Ctrl+F10 or Ctrl+F12.

### What steps reproduce the problem?

1. Making an algorithm with a flow that includes two breakpoints
2. Debugging with Ctrl+F5
3. Trying any of these shortcuts, Ctrl+F10 or Ctrl+F12, once the first breakpoint has been reached.

### What is the expected output? What do you see instead?
I expect not having to click back on the editor pane before being able to continue every time the debugger reaches a breakpoint.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version: Cent OS 8

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @jorgekoronis, thanks for reporting this issue. @impact27, do you know why this could be happening?

**Comment by impact27** [comment]
I am not sure how to reproduce. The focus goes to the console but that is expected as if you use the console that helps you with inputting more advanced commands, but the shortcuts should still work. Where is the focus in your case?

**Comment by jorgekoronis** [comment]
Do the following:
1. undock "IPython console" pane
2. Set a couple of break points.
3. Lauch Ctrl+F5
4. After reaching the first breakpoint try to launch ctrl+F10/ctrl+F12. In my case ctrl+F10/ctrl+F12 does not work unless I click back on the "Editor" pane.

**Comment by impact27** [comment]
Maybe this is OS specific? It works as expected on macOS as far as I can tell.

**Comment by jorgekoronis** [comment]
My OS is CentOS 8.

**Comment by ccordoba12** [comment]
This is a known issue. To solve it, we'd need to register global shortcuts in the windows that contain undocked plugins, but we don't know how to do that yet, sorry.
