### ISSUE TITLE
Plots pane keeps coming back

### ISSUE THREAD

**Issue by lukecherveny** [spyder-ide/spyder#15467]
### What steps will reproduce the problem?

With in-line plotting checked in Spyder 5.0, plotting from editor or console still switches to the plots pane.  If the plots pane is closed, it just comes back.

Basically, I want to plot in-line and never deal with or see the Plots panel, as was possible in Spyder 4.0.

**Comment by andfoy** [comment]
Hi @lukecherveny, thanks for opening this bug. This issue is a regression from Spyder 4 and we'll take a look at it.

**Comment by ccordoba12** [comment]
I'll take a look at this one for 5.0.2 because it's a serious regression. Thanks for reporting @lukecherveny!

**Comment by JohnRobson** [comment]
Another problem with the Plots Pane related to this problem is that the options "Undock" and "Close" are Disable, only after you plot something they become enabled.

**Comment by ccordoba12** [comment]
That was fixed in our 5.0.1 version, released two weeks ago.
