### ISSUE TITLE
Outline view does not correctly display

### ISSUE THREAD

**Issue by johnh865** [spyder-ide/spyder#15476]
### What steps will reproduce the problem?

Outline view does not display any functions or classes or anything with the newest version of Spyder 5.0.1. This issue is reproduced by performing a fresh install of Spyder using pip install spyder. 

The issue disappears once I uninstall the latest and reinstall Spyder 4.2.5 with "pip install spyder==4.2.5"

**Comment by juanis2112** [comment]
Hi @johnh865, Thanks for reporting. This is a duplicate of #15139
