### ISSUE TITLE
Lag in the editor, replace all hangs Spyder indefinitely

### ISSUE THREAD

**Issue by dinsmoro** [spyder-ide/spyder#15471]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [n] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm using Python 3.7.10 and Spyder 5.0.1 and I have an i5-4690K CPU on Windows.

I have a very long file, 13k lines. The editor chokes on this and editing code is very laggy and slow. I've turned off as much of the completion/linting as I can, but the issue still occurs. Task Manager shows 1 core + a bit more (~25-33% CPU) is taken up by Spyder's Python instance while the editor lag is occurring.

It's been happening since 4.2.X to the current 5.0.1. The file wasn't as long before 4.2.X so I'm not sure if previous versions have the same issue or not.

I made a tester file that tries to simulate the issues. The problem seems worse in different parts of the code, though I can't really tell what makes it worse.

Here's the tester file: https://www.dropbox.com/s/vzn6ifemrsvv17c/tester.py?dl=0
It's just 13k lines of copied simple nested if-else statements.

And lastly, if you replace anything that occurs a lot with anything else, Spyder will hang and I assume crash eventually. Or it might succeed at some point, but I don't wait around to find out.

Let me know if there's any other info I can provide!

### What steps reproduce the problem?
Warning: Once opening tester.py and replacing "prev" with "\n" made it so Spyder crashes on "Setting up main window". Reset to Spyder allows it to open again. Only happened once.

1. Open tester.py
2. Delete some random lines at the top, go to the bottom and start writing in random if-else or for statements and other things
3. It will slow down heavily (not as bad as my main code which is more complex, sometimes I get ~5 sec pauses)
4. Revert the file and just edit in random if-else and other statements
5. Delete the entire if-else zone and it'll take a minute to work through false line errors
6. Ctrl+R replace "prev" with "\n" and hang the program

### Paste Traceback/Error Below (if applicable)

Just either slow or crashes, no visible errors.

## Versions

* Spyder version:  5.0.1
* Python version:  3.7.10
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 20H2

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)

**Comment by andfoy** [comment]
Hi @dinsmoro, thanks for the useful information regarding the large file lags, we will try to use this information in order to improve the editor performance.

**Comment by sharon92** [comment]
I have the same issue, my script is about 1k lines long. Sometimes the ide would just stop responding, and I have to restart it.

**Comment by hassne-larc** [comment]
I"m having same issue as dinsmoro and sharon92, and I'm only 115 lines into my build.  Ugh.  Hope you can ferret this one out.

**Comment by dinsmoro** [comment]
I'm not sure what changed, but now the "Completions, linting, code folding, and symbols status" is stuck at "starting..." (little icon in the bottom right). There's no lag in the editor anymore, but there's no basic Python syntax errors either so I don't think the trade-off is worth it. I have everything turned off in "Preferences" -> "Completion and linting" except "Plugin Status: Enable code completion and linting in the editor" under General and "Enable basic linting" under Linting. Reseting Spyder will probably make it work again, but I don't want to do that right now as it'll close all the files I have open 🤷

Clicking on the icon/text brings up an Issue reporter and the most recent error is:

```
Traceback (most recent call last):
  File "F:\Miniconda\lib\site-packages\spyder\plugins\completion\providers\languageserver\widgets\status.py", line 70, in show_menu
    language = self.current_language.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

I also checked and replacing still crashes Spyder with the linting engine not running.
