### ISSUE TITLE
Highlight Stuff in curly brackets in f-strings

### ISSUE THREAD

**Issue by GoofyPy** [spyder-ide/spyder#15484]
It would be very, very helpful if all the stuff in the curly brackets of f-strings could be highlighted and not appear in the same, green color of the general string

**Comment by steff456** [comment]
Hi @GoofyPy,

Thanks for the feedback, we already have planned working towards a new syntax highlighting backend that will enhance the colors of the editor including this case. I cannot estimate when this will be ready but it is going to be done in a future.

Thanks for reporting!
