### ISSUE TITLE
spyder 4.2 auto indentation does not work

### ISSUE THREAD

**Issue by ms003** [spyder-ide/spyder#15509]
for Spyder 4.2 and above auto indentation does not seem to work although selected from preferences > editor

**Comment by steff456** [comment]
Hi @ms003,

Which version of Spyder are you currently using? Also, what type of method of installation did you made?

**Comment by ms003** [comment]
hi steff

* Spyder version: 4.1.5 (I have tried until 5.0, problem is same)
* Python version: 3.8.1
* Environment: Anaconda 2.0.1
* Operating System name/version: macOS Big Sur, version 11.3

**Comment by ms003** [comment]
fixed it..
