### ISSUE TITLE
Outline pane navigates to the wrong file

### ISSUE THREAD

**Issue by flipsurf** [spyder-ide/spyder#15517]
### What steps will reproduce the problem?

- open a file with some cells (outline pane should work now)
- go to "save as" and use a new name
- try to navigate with the outline pane in your renamed file
--> spyder re-opens the old file and jumps to the selected cell

## Versions

* Spyder version: 4.2.3 
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.16.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.5.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.1.3 (OK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  1.1.5 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @flipsurf, thanks for reporting. We'll take a look at this in a future release.

**Comment by KardoPaska** [comment]
FYI This has been an obstacle for quite some time.  One habit I have developed is to use "Save copy as...".  This will save with desired name and reopen the file.  You still have to manually close or otherwise deal with the unsaved/original file. 

Hint: If you mouse hover over the top level file name in Outline pane it will display the path of the file it will navigate to.  The issue is that it shows "untitled0.py" or whatever the wrong file name is.

**Comment by eafpres** [comment]
I discovered this today as I found myself editing the wrong file, thought I was crazy, then figured out what was happening.

In case it helps, here is a repro:

1) Use this code and save as test_spyder_outline.py
```
# -*- coding: utf-8 -*-
"""
Created on Sat Jul 31 11:43:08 2021

@author: Blaine Bateman
"""
#%% libraries
#
import pandas as pd
#
#%% data
#
my_data = pd.DataFrame({'index' : range(10),
                        'data' : range(10)})
#
#%% some stuff
#
my_data['data'] = my_data['data'] + 6
my_data['data'] = my_data['data']**2
#
```
2) Open the file, then save as 'test_spyder_outline_copy.py'
3) Click on a name in the Outline panel
4) The original file will open and navigate to that cell

Note that if the other file is already open, it will just shift to that tab in the editor and go to that cell. It's so fast, I missed it the first few times.

**Comment by eafpres** [comment]
Update--it appears saving the project and reopening fixes this.
