### ISSUE TITLE
Spyder Crashing on Startup

### ISSUE THREAD

**Issue by rkapoor2323** [spyder-ide/spyder#15510]
### Issue Report Checklist

* [ y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ y] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ y] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ y] Tried basic troubleshooting (if a bug/error)
    * [ y] Restarted Spyder
    * [ y] Reset preferences with ``spyder --reset``
    * [ y] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ y] Tried the other applicable steps from the Troubleshooting Guide
* [ y] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
i updated spyder and anaconda and my spyder will not start up. Crashes on start up.

### What steps reproduce the problem?

1. first ran conda update anaconda
2. update spyder using pip install --user spyder==5.0.0
3. try starting up spyder from the anaconda navigator
4. error message will appear as it does not start up.

### What is the expected output? What do you see instead?

i expect spyder to startup, but it crashes on startup and i get the message below.

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
File "C:\Users\ritik\anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in 
from PySide import __version__ as PYSIDE_VERSION # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\ritik\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\ritik\AppData\Roaming\Python\Python38\site-packages\spyder\app\start.py", line 209, in main
from spyder.app import mainwindow
File "C:\Users\ritik\AppData\Roaming\Python\Python38\site-packages\spyder\app\mainwindow.py", line 43, in 
requirements.check_qt()
File "C:\Users\ritik\AppData\Roaming\Python\Python38\site-packages\spyder\requirements.py", line 41, in check_qt
import qtpy
File "C:\Users\ritik\anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in 
raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found


```

## Versions

* Spyder version: 5.0.0
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version:  Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```
There is no dependencies tab under my Help tab in the Anaconda Navigator

**Comment by ccordoba12** [comment]
Hey @rkapoor2323, thanks for reporting. You said

> update spyder using pip install --user spyder==5.0.0

This is what broke Spyder. You can't use pip to install packages in Anaconda if those packages are provided by Anaconda itself. For next time, please update Spyder by doing

    conda update anaconda
    conda install spyder=5

and avoid as much as possible using pip.

To solve your problem, please remove this directory

    C:\Users\ritik\AppData\Roaming\Python

If the problem persists, please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to reinstall Anaconda after installing packages with pip.

**Comment by acjames76** [comment]
Spyder was working for me 2 weeks ago, now after reinstall, I get this:
![image](https://user-images.githubusercontent.com/4119061/117168996-893e2280-ad7d-11eb-9245-1d71dad7ef32.png)

**Comment by acjames76** [comment]
![image](https://user-images.githubusercontent.com/4119061/117169131-af63c280-ad7d-11eb-866f-82a0b8f2fae1.png)

**Comment by ccordoba12** [comment]
> Spyder was working for me 2 weeks ago, now after reinstall, I get this:

You need to give permissions in Settings to run the app. See [here](https://support.apple.com/en-us/HT202491) for the details.

**Comment by rkapoor2323** [comment]
awesome! That makes sense, it works now! I've been looking for a solution for this everywhere and could not find, thank you so much, i'll keep in mind!

**Comment by ccordoba12** [comment]
No problem, I'll glad Spyder is working for you again.
