### ISSUE TITLE
Spyder 5.0.1 dev installation fails in Pycharm Debugger

### ISSUE THREAD

**Issue by selahlynch** [spyder-ide/spyder#15518]
## Problem Description
I trying run Spyder from source code in a debugger, but I am unable to.   I am able however able to run it the "old fashioned way" by pressing the Run button instead of the Debug button.  I am using Pycharm as my IDE to run Spyder from source.

### What steps reproduce the problem?

1. Checkout v5.0.1 from Spyder code repository
2. Run `conda install -c spyder-ide/label/dev --file requirements/conda.txt`
3. Use Pycharm Run function to run boostrap.py and verify that it runs successfully
4. Use Pycharm debugger to run bootstrap.py
5. Behold the error.

### What is the expected output? What do you see instead?
When I press run I see this in my Pycharm console:
```
/Users/selah/opt/anaconda3/envs/spyder-dev/bin/python /Users/selah/Repos/spyder/bootstrap.py
Executing Spyder from source checkout
*. Patched sys.path with /Users/selah/Repos/spyder
*. Patched sys.path with /Users/selah/Repos/spyder/external-deps/spyder-kernels
*. Patched sys.path with /Users/selah/Repos/spyder/external-deps/qdarkstyle
*. Patched sys.path with /Users/selah/Repos/spyder/external-deps/python-language-server
*. Installing PyLS locally
*. Declaring completion providers
*. PyQt5 is detected, selecting
*. Imported Spyder 5.0.1 - Revision 1f54323e5, Branch: (HEAD detached at v5.0.1)
    [Python 3.7.7 64bits, Qt 5.9.6, PyQt5 5.9.2 on Darwin]
*. Running Spyder
Bootstrap completed in 00:00:04.7186
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 

```
When I press debug I see this in my Pycharm console:
```
/Users/selah/opt/anaconda3/envs/spyder-dev/bin/python "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 55460 --file /Users/selah/Repos/spyder/bootstrap.py
pydev debugger: process 26557 is connecting

Connected to pydev debugger (build 202.6397.98)
Executing Spyder from source checkout
WARNING: 3rd party Python exception hook is active: '_fallback_excepthook'
*. Patched sys.path with /Users/selah/Repos/spyder
*. Patched sys.path with /Users/selah/Repos/spyder/external-deps/spyder-kernels
*. Patched sys.path with /Users/selah/Repos/spyder/external-deps/qdarkstyle
*. Patched sys.path with /Users/selah/Repos/spyder/external-deps/python-language-server
*. Installing PyLS locally
unknown option --port
usage: /Users/selah/opt/anaconda3/envs/spyder-dev/bin/python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
Traceback (most recent call last):
  File "/Users/selah/opt/anaconda3/envs/spyder-dev/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/selah/opt/anaconda3/envs/spyder-dev/bin/python', '-W', 'ignore', 'setup.py', 'develop', '--no-deps', '--install-dir', '/Users/selah/Repos/spyder/external-deps/python-language-server/.installation-dir']' returned non-zero exit status 2.
python-BaseException

Process finished with exit code 1
```

## Versions

* Spyder version: 5.0.1
* Python version: 3.7.7
* Operating System name/version: MacOS Mohave 10.14.6

**Comment by ccordoba12** [comment]
> Use Pycharm debugger to run bootstrap.py

Sorry but we don't give support to run our development version in ways that we don't endorse. In this case, no one of us use Pycharm, so we won't be able to help you with your problem.

**Comment by selahlynch** [comment]
Fair.  Is there a debugging setup that you do endorse?  I'd love to get this running so that I can make some code contributions of my own to the Spyder project.

**Comment by ccordoba12** [comment]
We don't use Pdb to debug Spyder, sorry. Due to its complexity and that we also have a Python interpreter to introspect its internals, I doubt that's even feasible.

You just have to use old print's here and there.

**Comment by selahlynch** [comment]
Got it.  Thanks!

**Comment by ccordoba12** [comment]
Great! Thanks for understanding.
