### ISSUE TITLE
The "Spyder 2" icon set have almost all files/directories as "❌" or "Not Found" icon in files view in Spyder 5.0.0

### ISSUE THREAD

**Issue by battaglia01** [spyder-ide/spyder#15511]
### Issue Report Checklist

* [☑️] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [☑️] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [☑️] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [☑️] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [☑️] Tried basic troubleshooting (if a bug/error)
    * [☑️] Restarted Spyder
    * [☑️] Reset preferences with ``spyder --reset``
    * [☑️] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [☑️] Tried the other applicable steps from the Troubleshooting Guide
* [☑️] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In Spyder 5.0.0, if I go to the "Spyder 2" icon set, almost the entirety of the file explorer has the "❌" icon rather than any file/folder icon. Only .pyc files have any icon:

![image](https://user-images.githubusercontent.com/1020594/117095848-7f90cc80-ad35-11eb-927b-75ccb9630a49.png)

### What steps reproduce the problem?

1. Go to preferences and change icon set to Spyder 2
2. Restart Spyder
3. All icons are ❌ except .pyc

### What is the expected output? What do you see instead?

To have file/folder icons, or at least use the Spyder 3 icons if the originals aren't available

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.4 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Darwin 17.7.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @battaglia01, thanks for reporting. We only use the Spyder 2 icon set as fallback in case we are unable to load our icon theme based in Material Design (that's still a problem for some Windows versions).

We plan to fix that bug in the future and remove that set. So we don't have plans to fix the problem you reported nor address any other issue about it, sorry.
