### ISSUE TITLE
Error - PyTorch

### ISSUE THREAD

**Issue by Vivekk9** [spyder-ide/spyder#15522]
### What steps will reproduce the problem?

PyTorch running in console. Internal issue pops up. 

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "/home/vivek/.local/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 314, in _comm_message
    buffer = cloudpickle.loads(msg['buffers'][0],
ModuleNotFoundError: No module named 'torch'
```

## Versions

* Spyder version: 5.0.1 
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.8.0-50-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
setuptools >=39.0.0           :  53.0.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.14 (OK)
matplotlib >=2.0.0            :  3.4.1 (OK)
numpy >=1.7                   :  1.17.4 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```
![ipython](https://user-images.githubusercontent.com/20682477/117265837-070c3780-ae2b-11eb-8668-09fbb2c4444d.png)

**Comment by Vivekk9** [comment]
![ipython](https://user-images.githubusercontent.com/20682477/117253407-90b50880-ae1d-11eb-94f5-3b78b94acd90.png)

**Comment by Vivekk9** [comment]
I figured that Python 3.6.13 is an old version and the PyTorch environment doesn't match with this version. Made some updates in Jupyter Kernels that could be used with the spyder console with the following command:
**conda install -c conda-forge spyder-kernels**

Finally, the python version seems to be fine. **Python 3.9.2 | packaged by conda-forge** and PyTorch is working fine as well.
However, there's still some issue with the Spyder version: 5.0.1 as the internal problem is still encountering by the Spyder.

**Exception in comms call get_namespace_view:
  File "/home/vivek/.local/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 314, in _comm_message
    buffer = cloudpickle.loads(msg['buffers'][0],
ModuleNotFoundError: No module named 'torch'**

**Comment by emmanuel-contreras** [comment]
Just thought I'd comment and say that I'm running into the same error when using an environment that is not the base. I just switched to the base environment and I don't get the error. Oh and also if the error shows up debugging stops working so I could not step through after the error shows up.

**Comment by ccordoba12** [comment]
@emmanuel-contreras, you need to install Pytorch in the same environment as Spyder to solve this error. That's the only available solution right now.
