### ISSUE TITLE
Abnormal layout in main window

### ISSUE THREAD

**Issue by okling** [spyder-ide/spyder#15529]
## Problem Description
When I started spyder after upgrading to v5.0.1, it has this abnormal layout in the main window shown in the following screenshot:
![output](https://user-images.githubusercontent.com/32896474/117332427-1d041180-ae98-11eb-8e70-95fdf97d41ce.png)

### What steps reproduce the problem?
I've restarted spyder, done `spyder --reset`, updated anaconda/conda, but the problem persists.

### What is the expected output? What do you see instead?
I installed spyder v5.0.1 in a new environment and it shows up okay:
![expected](https://user-images.githubusercontent.com/32896474/117332620-589edb80-ae98-11eb-80c8-3967c49f356e.png)

### Paste Traceback/Error Below (if applicable)
```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Traceback (most recent call last):
  File "/Users/angelling/anaconda3/envs/obspy_dev/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1637, in moveEvent
    if not self.isMaximized() and not self.layouts.get_fullscreen_flag():
  File "/Users/angelling/anaconda3/envs/obspy_dev/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1180, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "/Users/angelling/anaconda3/envs/obspy_dev/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 170, in get_plugin
    'Plugin "{}" not found!'.format(plugin_name))
spyder.api.exceptions.SpyderAPIError: Plugin "layout" not found!
```

## Versions
* Spyder version: 5.0.1
* Python version: 3.7.10
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: macOS Catalina

**Comment by steff456** [comment]
Hi @okling,

Can you please reset your spyder configuration and see if the error persists? For reseting your configuration please use `spyder --reset` command. 

Let me know if that works

**Comment by okling** [comment]
Hi @steff456,

Thanks for the reply. Yes, I've restarted spyder, tried `spyder --reset`, updated anaconda/conda, but the problem/error still persists.

**Comment by steff456** [comment]
Can you please create a new environment and install the latest version of Spyder via conda-forge:

```
conda create -n spyder-test python=3.7
conda activate spyder-test
conda install -c conda-forge spyder
spyder
```

And let me know if the error persists?

**Comment by okling** [comment]
Hi, yes, I created a new test environment. Although the layout is fine, I still receive similar error messages:

```
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Traceback (most recent call last):
  File "/Users/angelling/anaconda3/envs/spyder-test/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1638, in moveEvent
    if not self.isMaximized() and not self.layouts.get_fullscreen_flag():
  File "/Users/angelling/anaconda3/envs/spyder-test/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1181, in __getattr__
    return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
  File "/Users/angelling/anaconda3/envs/spyder-test/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 170, in get_plugin
    'Plugin "{}" not found!'.format(plugin_name))
spyder.api.exceptions.SpyderAPIError: Plugin "layout" not found!
```

**Comment by steff456** [comment]
@dalthviz do you know why this may be happening?

**Comment by dalthviz** [comment]
@steff456 not totally sure, but seems related to the handling of the `moveEvent`. @okling could you submit a screen recording (GIF or some sort of video) here to understand better what is triggering this behavior for you? Thanks!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
