### ISSUE TITLE
outline no function list tree

### ISSUE THREAD

**Issue by willywen844** [spyder-ide/spyder#15536]
I can't see function list in the outline 
but in the 3.3.6 this feature is OK
Any one know what's problems?

**Comment by andfoy** [comment]
Hi @willywen844, thanks for opening this issue. Do you have Kite installed? If so, this is a duplicate of #15139, which was fixed on PR https://github.com/spyder-ide/spyder/pull/15448, which is going to be available on Spyder 5.0.2, to be released this weekend

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by eafpres** [comment]
I am currently running 5.04 and see the same issue.  I am not running Kite.  In prior to 5 versions, the functions in a cell would appear indented and differently formatted.  Now, there is nothing but the special comments.

**Comment by eafpres** [comment]
Update--this may have to do with older projects or something about the project.  When I opened a newer (also smaller) project the functions appear in the outline tree.  I then opened a file from a project where I don't see the functions, in the "good" project, and the functions show up.  Opening the same file in the "bad" project, they do not show up.

**Comment by ccordoba12** [comment]
We'll try to fix the many problem with our Outline pane in Spyder 5.1.0, to be released at the end of the month.

**Comment by eafpres** [comment]
> We'll try to fix the many problem with our Outline pane in Spyder 5.1.0, to be released at the end of the month.

Sweet!
