### ISSUE TITLE
Add project's path to our PYTHONPATH so that it can be imported in the console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1554]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-09-10T10:11:14Z_

This is motivated by this SO question: http://stackoverflow.com/questions/18608001/problems-in-importing-self-defined-packages-and-modules

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1554_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T12:47:14Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:48:05Z_

**Labels:** -MS-v2.3.1 MS-v2.4

**Comment by ccordoba12** [comment]
@goanpeca you need to take care of this one when working on the new Projects support

**Comment by goanpeca** [comment]
Ok, I have been assigning to myself anything that looks related to the project explorer so if you find something related please assign me, so I keep track and tackle these issues from the start
