### ISSUE TITLE
Indentation guide not working

### ISSUE THREAD

**Issue by BassamMasry** [spyder-ide/spyder#15555]
## Problem Description
The indentation guide in the latest version of Spyder IDE is not working

### What steps reproduce the problem?

1. Restart Spyder to default using ``spyder --reset`` or freshly install a new version
2. Open Tools tab -> Preferences -> Editor -> Display tab
3. Activate checkbox for ``Show indent guide``

### What is the expected output? What do you see instead?

No indentation guide is visible

## Versions

* Spyder version: 5.0.1
* Python version: 3.7.3
* Qt version: 5.11
* PyQt version: 5.12.3
* Operating System name/version: Debian 10 on Dell G5 Intel I5 10th gen, Nvidia GTX 1660 Ti

### Dependencies

None

![Indentation not working](https://user-images.githubusercontent.com/43927300/117554504-d281c100-b060-11eb-8321-ebd910c04af4.png)

**Comment by ccordoba12** [comment]
Hey @BassamMasry, thanks for reporting. This should be fixed in our next version (5.0.2), to be released shortly.

If that's not the case, please let us know.

**Comment by BassamMasry** [comment]
Great. Thank you

**Comment by BassamMasry** [comment]
The problem is solved in spyder 5.0.2
