### ISSUE TITLE
can't use keyboard input or stop the program on a remote IPython kernel

### ISSUE THREAD

**Issue by tarneaux** [spyder-ide/spyder#15556]
I don't know if this is the right place, but anyways:
I am connected to a raspberry pi 4 which is running the IPython kernel in an SSH session. I'm connected to it in the Spyder IPython console.
But when I try to use keyboard input or interrupt the program, it does nothing or says 
`Cannot interrupt a kernel I did not start.`
I can use the keyboard input in my SSH session where the IPython kernel is running, but my goal is to only have spyder opened.
Any ideas?

**Comment by ccordoba12** [comment]
Hey @tarneaux, thanks for reporting. This is a known limitation of the Jupyter architecture (yes, we use the same architecture as they do to run code).

Unfortunately, the only workaround for now is (as you discovered) to press `Ctrl+C` in the same SSH session where you started the kernel, sorry.

We plan to solve this (hopefully) in Spyder 6.

**Comment by fohria** [comment]
hey @ccordoba12 , the hydrogen plugin for atom can interrupt the remote/local kernel it's connected to and it works quite reliably in my experience. maybe it won't help because spyder is too different, so just a tip in case it might work  :)

**Comment by ccordoba12** [comment]
Thanks for the tip @fohria! We'll take a look at what Hydrogen does to see if we can solve this in our side.
