### ISSUE TITLE
problem with xlrd module

### ISSUE THREAD

**Issue by niloofarzg** [spyder-ide/spyder#15560]
### What steps will reproduce the problem?

Hi, I have a problem with xlrd module. (Python 3.7.9 on windows 7)
I have installed it, but I cannot import it in Spyder 5. Everyime trying to import xlrd, I receive this message:

Traceback (most recent call last):

  File "<ipython-input-7-2743bb67f6dd>", line 1, in <module>
    import xlrd

ModuleNotFoundError: No module named 'xlrd'

How can I fix it?

**Comment by ccordoba12** [comment]
Hey @niloofarzg, thanks foe reporting. Did you install Spyder using our Windows installer?

**Comment by niloofarzg** [comment]
> 
> 
> Hey @niloofarzg, thanks foe reporting. Did you install Spyder using our Windows installer?

Yes, using this link:
https://github.com/spyder-ide/spyder/releases/download/v5.0.1/Spyder_64bit_full.exe

**Comment by niloofarzg** [comment]
> 
> 
> > Hey @niloofarzg, thanks foe reporting. Did you install Spyder using our Windows installer?
> 
> Yes, using this link:
> https://github.com/spyder-ide/spyder/releases/download/v5.0.1/Spyder_64bit_full.exe

I am a little bit confused by the version of python I'm using
![git](https://user-images.githubusercontent.com/81688050/117585905-fd145e00-b0e2-11eb-8ca4-83e4976c5e8e.png)

**Comment by ccordoba12** [comment]
> I am a little bit confused by the version of python I'm using

It is fine. You have two Python versions installed in your system (the one that comes with the Spyder installer and another one).

To connect Spyder to your Python 3.8 version (where you installed `xlrd`), please read [our docs](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Let us know if you any more doubts we can help you with.

**Comment by ccordoba12** [comment]
> After installing spyder‑kernels, the problem still exist

What problem? Are you able to run your code after installing spyder-kernels?

> I cannot restart kernel: "Cannot restart a kernel not started by Spyder"

This can only happen if you started the kernel outside Spyder, which means you didn't follow our docs guide. Was that the case?

**Comment by niloofarzg** [comment]
> 
> 
> > After installing spyder‑kernels, the problem still exist
> 
> What problem? Are you able to run your code after installing spyder-kernels?
> 
> > I cannot restart kernel: "Cannot restart a kernel not started by Spyder"
> 
> This can only happen if you started the kernel outside Spyder, which means you didn't follow our docs guide. Was that the case?

Even though spyder‑kernels is installed, I get this: "Cannot restart a kernel not started by Spyder"; So, I cannot run any code.

**Comment by ccordoba12** [comment]
Did you start the kernel outside Spyder and then connect to it? That's the only way that message can be shown.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
