### ISSUE TITLE
Spyder 5 launching cmd.exe upon launch

### ISSUE THREAD

**Issue by sama2689** [spyder-ide/spyder#15574]
This is in a way a duplicate of [this issue](https://github.com/spyder-ide/spyder/issues/3529) except that I am having it in Spyder 5 instead of Spyder 3 (after having no problems with Spyder 4). Spyder is launching a command prompt upon launch and closing the command prompt cannot be done without closing Spyder (however closing spyder does not close to command prompt). The text displayed on the command prompt is as follows

`1>C:\Users\user\AppData\Roaming\.anaconda\navigator\.anaconda\navigator\scripts\Python38\spyder-out-1.txt 2>C:\Users\user\AppData\Roaming\.anaconda\navigator\.anaconda\navigator\scripts\Python38\spyder-err-1.txt`

**Comment by ccordoba12** [comment]
Hey @sama2689, thanks for reporting. This seems a problem with the way Anaconda Navigator launches Spyder, and not with Spyder itself.

Since we can't fix things in Navigator, please report it here:

https://github.com/ContinuumIO/anaconda-issues/
