### ISSUE TITLE
Spyder 5.0.2 works fine by installing the binaries from https://www.spyder-ide.org/ BUT not by pipping spyder

### ISSUE THREAD

**Issue by AnthonyTheKoala** [spyder-ide/spyder#15575]
First, I love spyder and its interface. Thank you.

First some information:
```
Spyder: 5.0.2 
Python: 3.8.9
OS: Windows 7

```
Problem: When I have been updating spyder using the pip command, which I have been always been using
`pip install -U spyder --upgrade
`
Under the ppping method, the spyder.exe has always been available in the c:\python38\scripts\ folder.

I have my own shortcut on my WIndows Taskbar to:
`c:\python38\scripts\spyder.exe
`
**Issue:**
The problem is that by pipping spyder and updating, the  spyder.exe in c:\python38\scripts\ was not there! 

In versions of Spyder < 5.0.2, I have had no problems running the pipped installation of spyder. No problem at all.

In the meantime, I installed the binaries from https://www.spyder-ide.org/.  This installation required 180MB compared to the pipped version of 11MB.

**Questions please:**
* I would like to know why spyder.exe in the c:\python38\scripts directory was missing.
* I have had no problem updating 11MB by pipping, but had to download the binary package at https://www.spyder-ide.org/ which was 180MB.
* Instead of my latest spyder being at c:\python38\scripts\spyder.exe, it is **NOW** "C:\Program Files\Spyder\Spyder.launch.pyw"
* Updates: When a future spyder 5.x is available, will I be able pip OR will I need to keep on downloading the 180MB package?

Again, I love the spyder IDE, but wondered why the spyder.exe was missing from c:\python38\scripts folder.

Thank you, gracias, 
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
Solved - I will provide the details.
I would like the assignees to the problem close it off.

Result:
* From my experience, this problem only occurred when using Python 3.8.9 and Python 3.8.10.

What did I do:
* Simply uninstalling Python 3.8.10 and re-installing Python 3.8.8 did not work. When 3.8.8 was installed, and ran IDLE, I still got Python 3.8.10 installed - that's a Python Issue, not a Spyder Issue. Recall original issue was that c:\python38\scripts\spyder.exe did not exist.
* Uninstalled Python 3.8.10 anyway.
* Installed Python 3.8.8 to a temporary c:\PythonBoo - NOTE did not want to 'generate' the path unchecked it.
* Copied all of C:\PythonBoo to c:\Python38
* Ran Idle and Python version was what wanted 3.8.8.

NOW
* Uninstalled Spyder installed from the binary executables.
* Pipped spyder by
pip install -U spyder==5.0.2 --force-reinstall
* spyder.exe was installed in c::\python38\scripts

Conclusion:
* Python 3.8.10 was causing the problem of no c:\python38\scripts\spyder.exe
* It appears that a pipped Spyder will not work with Python 3.8.10
* I prefer the pipped version of Spyder than the installable binary executable. The pipped version can add any other packages when available.

Thank you,
Anthony of Sydney

**Comment by ccordoba12** [comment]
Ok, I'm glad you were able to solve it.

Closing this one as you requested.
