### ISSUE TITLE
"Plots" pane can't be permanently closed

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#15572]
I am using Spyder 5.0.0, and I unchecked "mute inline plotting" in the "Plots" pane.  This is because I only want my plots shown in the IPython console.

However, every time I run my scripts and generate plots in the IPython console, the "Plots" pane shows up (even if I closed it before).  And the more annoying behavior is: when the "Plots" pane shows up, it covers the other pane in the same space. 

How can I permanently close the "Plots" pane?  Thanks.

**Comment by ccordoba12** [comment]
Hey @jsh9, thanks for reporting. This was fixed in our 5.0.2 version, released some hours ago. I hope it'll be added soon to Anaconda.
