### ISSUE TITLE
Getting slow during editing docstrings and finally crashes (V 4.2.3)

### ISSUE THREAD

**Issue by cg-mayrhofer** [spyder-ide/spyder#15586]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When editing the Docstrings (added by ctrl+alt+d, type=numpy) Spyder starts to get slow and laggy so that cahracters need about 2..5 seconds to appear. At least three times I experienced Spyder to crash. When crashed there was not even the bugreport screen. 
It seems like editing existing docstrings is worse than writing new ones and preferably when adding an example.
It happens when Spyder has been started a while before (30-50mins.) but never right after starting Spyder. 

## Versions
4.2.3

* Spyder version: 4.2.3 in Miniconda
* Operating System name/version: Win 10 64bit

**Comment by steff456** [comment]
Hi @cg-mayrhofer,

Can you please update to 4.2.5 version and let me know if the error persists?

**Comment by cg-mayrhofer** [comment]
Hi Steff, thanks for your response. 
Oh I thought Anaconda installs the latest version automatically.... Sorry for using the outdated one. With 4.2.5 Spyder has not crashed yet but still slows down .

**Comment by steff456** [comment]
In a new environment can you install 5.0.2 version from conda-forge and let me know if the error persists?

```
conda create -n test-spyder python=3.8
conda activate test-spyder
conda install -c conda-forge spyder
spyder
```

**Comment by ccordoba12** [comment]
Closing in favor of issue #15631 because it has more details.
