### ISSUE TITLE
Installation Spyder 5.0

### ISSUE THREAD

**Issue by hannahbus** [spyder-ide/spyder#15587]
## Problem Description

I updated to Spyder 5.0 via the CLI on two Macs (MacOs Big Sur). On both machines, the latest version of Anaconda is installed. Installation of Spyder 5.0 seemed successful (I checked via conda list). However,  when trying to start Spyder via `conda run spyder`, I got an error. Apparently, Spyder needed python to be here '/opt/anaconda3/python.app/Contents/MacOS/python'. I manually copied python from '/opt/anaconda3/bin/python' in this directory and all is fine now. I am not sure whether this issue relates to Spyder or Anaconda. I guess would be fine to let people know and if possible fix this. 

## Versions

* Spyder version: 5
* Python version: 3.8.5
* Operating System name/version: macOS Big Sur (11.2.3)

**Comment by steff456** [comment]
Hi @hannahbus,

This seems related to Anaconda's error rather than Spyder's error. Thank you for including the fix you made and I'm happy that you could find a workaround for using Spyder.
