### ISSUE TITLE
Troubleshooting guide missing

### ISSUE THREAD

**Issue by Greedquest** [spyder-ide/spyder#15584]
http://docs.spyder-ide.org/current/first-steps.html

Takes me to a page not found in github pages

![image](https://user-images.githubusercontent.com/25348920/117774339-48d51d80-b231-11eb-8bf2-1d7f1e7e7f08.png)

**Comment by steff456** [comment]
Hi @Greedquest,

Thanks for reporting this! Can you please point me where did you find that link? 

The correct link for you to use is this one: https://docs.spyder-ide.org/current/troubleshooting/first-steps.html?highlight=first%20steps

**Comment by juanis2112** [comment]
Thanks @Greedquest for checking. I will close this one then :)
