### ISSUE TITLE
Can't install a working spyder 3.x in a conda environment to use with python 2.7

### ISSUE THREAD

**Issue by lkshrsch** [spyder-ide/spyder#15593]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I can't launch Spyder 3 in a conda environment with python 2.7, any versions, and from multiple channels. 

### What steps reproduce the problem?

1. Make a conda environment with python 2.7 and spyder 3:   conda create -n py2 python=2.7 spyder=3 -c free 
2. Activate environment:  conda activate py2
3. Launch spyder:   spyder

### What is the expected output? What do you see instead?
Expected: Spyder GUI will launch.
Instead spyder fails to launch, with AttributeError NoneType has no attribute SetProperties, or similar errores depending on different versions of spyder I install. Or when opening spyder independently from the conda environment and then selecting the Spyder executable from the environment (under preferences), kernel fails to open.

### Paste Traceback/Error Below (if applicable)
Gtk-Message: 14:17:35.876: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "/home/deeperthought/anaconda3/envs/py2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3093, in main
    mainwindow = run_spyder(app, options, args)
  File "/home/deeperthought/anaconda3/envs/py2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2993, in run_spyder
    main = MainWindow(options)
  File "/home/deeperthought/anaconda3/envs/py2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 525, in __init__
    self.apply_settings()
  File "/home/deeperthought/anaconda3/envs/py2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2548, in apply_settings
    style.setProperty('name', style_name)
AttributeError: 'NoneType' object has no attribute 'setProperty'

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.x, 3.2.3 
* Python version: 2.7.x
* Qt version: 4.8.7
* PyQt version: 4.11.4
* Operating System name/version: Ubuntu 18.4

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @lkshrsch,

Both python 2 and Spyder 3 are not supported anymore. I will recommend you to update all the code you have to python 3 and use the latest version of Spyder. For your information, the latest version of Spyder that supports python 2 is Spyder 4.1.6

You can try to install that version and see if it works. I'm closing this issue because we don't support this installation anymore.
