### ISSUE TITLE
Completion & Linting settings missing from the preferences menu

### ISSUE THREAD

**Issue by Greedquest** [spyder-ide/spyder#15594]
### What steps will reproduce the problem?

Upgraded to 5.0.2, the settings are not visible anymore (see image)

![image](https://user-images.githubusercontent.com/25348920/117866624-430e2500-b28f-11eb-8344-fc6425b9eb6d.png)

I would expect to see it in the left navbar like this:
![image](https://user-images.githubusercontent.com/25348920/117866864-88325700-b28f-11eb-8349-6ce749d4d34f.png)

**Comment by steff456** [comment]
Hi @Greedquest,

This is a known issue and we are working towards fixing it in our next release. For now please reset your configurations with `spyder --reset` and the `Completions and linting` menu will appear. If you uncheck the option `enable code completion and linting in the editor` and close Spyder then you will loose for ever the page. For now please just disable all the providers section for turning off the linting without killing the page.

Thanks for reporting!

**Comment by raphaelquast** [comment]
hey, just to let you know...
I just upgraded from 5.0.2 to 5.0.3 and experienced the same issue... 

`spyder --reset` solves the problem
(it might be worth mentioning that executing this command will  delete any history on previously opened files, projects etc.)

**Comment by Wuhuuu2** [comment]
Isn't there any comand line text that enables it again. (And thus maybe showing the wonderful tab)

**Comment by ccordoba12** [comment]
You need to run `run --reset`, mentioned by @raphaelquast. We're working to fix this problem in Spyder 5.1.0, to be released at the end of July.

**Comment by yengip** [comment]
Running ` !spyder --reset` from the ipython console and restarting spyder has had no effect for me, completion and linting options still not visible.  Also, I am unable to collapse my functions and the outline pane is not available to select in the View-> Panes list.  Is that related?
![image](https://user-images.githubusercontent.com/86871336/126270880-114c6980-7413-4135-9d55-150b6dc3075b.png)

**Comment by raphaelquast** [comment]
not sure about this but I guess you should run `spider --reset` in the **anaconda prompt** (or whatever console you use) and not in spider's ipython-console .... (spider most probably can't reset itself while it is running)

**Comment by andfoy** [comment]
This will be fixed on #16012
