### ISSUE TITLE
Spyder 5.0.2  and other python packages

### ISSUE THREAD

**Issue by leyojoseph** [spyder-ide/spyder#15592]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have  Spyder installed via Anconda. Version of spyder was 5.0. I have installed many python packages like pyvisa and  is working fine. As Spyder 5.0.2 is not available in Anaconda, Installed stand-alone version of  spyder 5.0.2. But in the spyder 5.0.2, I am not able to use packages like pyvisa etc. How to install these packages so that I can use it with Spyder 5.0.2.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by leyojoseph** [comment]
Will this update  spyder in Anaconda to 5.0.2 or will it install another Spyder 5.0.2 in my PC? Please let me know.
Thanks

**Comment by leyojoseph** [comment]
I am executing "conda install -c conda-forge/label/cf201901 spyder " at the Anconda prompt. This is the correct way,right

**Comment by Greedquest** [comment]
No I think just `conda install -c conda-forge spyder` or `conda install -c conda-forge spyder=5.0.2` if the former does not work(only goes to 5.0.0 say - look when it says "the following packages will be installed" in the prompt). This should replace your existing conda spyder installation. As for your standalone installation I don't know, you may want to uninstall that first?

**Comment by leyojoseph** [comment]
Thanks a lot...conda install -c conda-forge spyder=5.0.2 worked!!. Now I am enjoying all of new features of 5.0.2 version...

**Comment by steff456** [comment]
Hi @leyojoseph,

Right now we are waiting for Anaconda to publish 5.0.2 in the defaults channel, if you want to upgrade via anaconda please use `conda install -c conda-forge spyder`. If you are interested on using our installers, you will need to create a new environment with all the packages you need and `spyder-kernels` and then link to that interpreter in preferences.

I'm glad that you could resolve this issue with other users! I'm closing this issue and thank you for reporting :)
