### ISSUE TITLE
Why doesn't Tensorboard get invoked from Spyder - everything works now except this

### ISSUE THREAD

**Issue by AnthonyTheKoala** [spyder-ide/spyder#15600]
Dear assignees, 
Thank you for your time.
### Summary
Everything with Spyder is working now beautifully.
Spyder: 5.0.2
IPython from within Spyder: 7.23.1
Python: 3.8.9

**NOTE:** don't know whether this is a bug or installation problem.

### Problem
When I invoke the script in Spyder, I get this 
![image](https://user-images.githubusercontent.com/26536316/117969067-4c1ff480-b36a-11eb-86fa-d495580b3c83.png)
Tensorboard is invoked, but I don't see the the tensorboard.

I am running a simple script that is supposed to invoke the tensorboard.
![image](https://user-images.githubusercontent.com/26536316/117968517-9ce31d80-b369-11eb-9280-4a0901a4ecfc.png)

### For your information the program is test_notebook.ipy
**NOTE:** This is not about tensorflow. It is about why tensorboard is not invoked from IPython despite being installed.

```
import tensorflow as tf

import datetime,os

%load_ext tensorboard

mnist = tf.keras.datasets.mnist
(x_train,y_train), (x_test, y_test) = mnist.load_data()

x_train, x_test = x_train/255.0 , x_test/255.0

model = tf.keras.models.Sequential([
	tf.keras.layers.Flatten(input_shape=(28,28)),
	tf.keras.layers.Dense(512, activation='relu'),
	tf.keras.layers.Dropout(0.2),
	tf.keras.layers.Dense(10,activation='softmax')
])
%reload_ext tensorboard
%tensorboard --logdir logs

```

### Summary:
Tensorboard is invoked but not displayed even though the tensorboard is installed.
Why can't I see the tensorboard.

Thank you, merci, gracias.
Anthony of Sydney

**Comment by dalthviz** [comment]
Hi @AnthonyTheKoala thanks for the feedback! I'm not totally sure but maybe the output from running tensorboard is not being handled by QtConsole properly. Seems like there is some output but it gets printed as `<IPython.core.display.HTML>` Also, just in case, is the plots pane empty, right?

@ccordoba12 what do you think?

**Comment by ccordoba12** [comment]
Yeah, if I'm not mistaken, Tensorboard is a web application and we can't display web content yet in Spyder.

We'll try to address that in Spyder 6, to be released next year.

**Comment by AnthonyTheKoala** [comment]
Dear Daniel and Carlos,
Thank you for your reply.

Here is the output from the console at bottom and the plots panel at the top:
![image](https://user-images.githubusercontent.com/26536316/118007606-9f586e00-b38f-11eb-8e11-1b74ca04b9cf.png)

I wrote this a few minutes before you closed the issue, researching a method to work out if there are any other ways to get the HTML object.

Look forward to v6.

Thank you, merci, gracias,
Anthony of Sydney

**Comment by heitor-mendonca** [comment]
Encountered the same error.
For anyone coming across this: to go around it, I started TensorBoard from conda pointing at the log directory and just went to localhost 6006.

There might be a solution within spyder, but I didn't find it.
