### ISSUE TITLE
Code folding does not work in projects

### ISSUE THREAD

**Issue by TieuMinhChau** [spyder-ide/spyder#15625]
### What steps will reproduce the problem?

1. Create or open a project
2. Create any python file with functions, classes
3. Ensure code folding enabled.
4. See code folding not working

**Comment by ccordoba12** [comment]
Hey @TieuMinhChau, thanks for reporting. This problem was solved in our 5.0.2 version, released last Monday.

Hopefully it'll be soon part of Anaconda.
