### ISSUE TITLE
Can't update my Spyder IDE in Ubuntu 32bit 18.04LTS 

### ISSUE THREAD

**Issue by Ahnaf702** [spyder-ide/spyder#15620]
I have installed Spyder IDE from Software Store in my Ubuntu 32bit 18.04LTS 

While updating Spyder IDE (From 3.2.6 to 5.0.2)

I run this below command in my terminal .

`pip install --upgrade spyder`

**Then I got below error**

>  Collecting pyls-black>=0.4.6 (from spyder)
Could not find a version that satisfies the requirement pyls-black>=0.4.6 (from spyder) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5)
No matching distribution found for pyls-black>=0.4.6 (from spyder)

Then I run this below command in my terminal .

`pip3 install --upgrade spyder`

**got below error**

> Collecting pyqt5<5.13 (from spyder)
  Could not find a version that satisfies the requirement pyqt5<5.13 (from spyder) (from versions: 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4)
No matching distribution found for pyqt5<5.13 (from spyder)

**Versions**

- 
    Spyder version: 3.2.6
    Python version: 3.9.4
    Qt version: 5.9.5
    PyQt5 version: 5.10.1 on Linux
    Operating System name/version: Ubuntu 32bit 18.04LTS 

**Dependencies**

IPython >=4.0    :  5.5.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.17.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.4.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by andfoy** [comment]
Hi @Ahnaf702, thanks for reaching out, sadly 32bit packages (both pypi and conda/conda-forge) for most of Spyder dependencies are not being published these days, which means that 32bit machines are no longer supported by newer versions of Spyder, in this case you will need to defer to your own distribution packages (via APT in this case), which are third-party and unofficial from the Spyder point-of-view. Our recommendation is to move to a x64 machine as soon as possible.
