### ISSUE TITLE
Items in Spyder pulldown menus don't display properly

### ISSUE THREAD

**Issue by Greg1950** [spyder-ide/spyder#15626]
### Issue Report Checklist
* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Icon and description of pulldown menu items display superposed.

### What steps reproduce the problem?
1. Start Spyder.
2. Click on a pulldown menu, for example "Search"

### What is the expected output? What do you see instead?
I expect to see a pulldown menu with various items listed.  Typically an item consists of some icon followed by a short item description.  For example, the second item of the "Search" pulldown menu should show a down arrow icon followed by the description "Find next   F3".  Instead the down arrow icon and the description's first three letters ("Fin") are visually superposed.  This makes it difficult to read both the icon and the description.

Attachment **Spyder_pulldown_menu.jpg** shows a  screenshot of the problem.

## Versions
* Spyder version:  5.0.0
* Python version:  3.9.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10
![Spyder_pulldown_menu](https://user-images.githubusercontent.com/28631328/118297324-9789ee00-b4a3-11eb-9c3a-4112e6f15c4c.jpg)

**Comment by steff456** [comment]
Hi @Greg1950, 

Please update to our latest release 5.0.2 to have the fix for this issue. Right now it is not available yet in the anaconda defaults channel, so please consider updating using conda-forge channel or one of our installers.

Thanks for reporting!
