### ISSUE TITLE
Copy Paste not working

### ISSUE THREAD

**Issue by ElJdP** [spyder-ide/spyder#15630]
I've got no clue if that issue has occurred to anyone else here.  Since ~April, I'm unable to copy paste my plots to anywhere else, with plt.savefig or without it. It suggests me to have ctrl+c to select it, but if I go into another app, say Twitter or GMail, it does not let me paste the plot I copied. Has anyone faced a similar issue?

**Comment by ccordoba12** [comment]
Hey @ElJdP, thanks for reporting. I'm going to ask you to reopen this issue with the information we ask in our issue template (i.e. Spyder version, Qt/PyQt versions, etc). All that is available in the dialog showed when you go to the menu `Help > About Spyder`.

Without that information we can't properly help. Please don't discard it for next time here nor in other projects that require it.
