### ISSUE TITLE
Copy paste not working properly

### ISSUE THREAD

**Issue by ElJdP** [spyder-ide/spyder#15639]
### What steps will reproduce the problem?

plt.scatter(x,y)
plt.savefig('name.png', dpi=500)
open plots tab
copy plot
paste into another appp (e.g Twitter or Discord)
plot does not appear

## Versions

* Spyder version: 4.2.5 
* Python version: 3.9.5
* Qt version: 5.15.2
* PyQt5 version: 5.15.0
* Operating System: Linux 5.11.19-300.fc34.x86_64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  None (NOK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.8.0 (NOK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.2 (NOK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  53.0.0 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  0.10.2 (NOK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  22.0.3 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  3.4.1 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @ElJdP, thanks a lot for reopening your issue with the information we require. It seems that you installed Spyder through your Linux distro instead of using Anaconda or pip. As you can also see above, several of your dependencies have incorrect versions (e.g. parso, qtconsole and watchdog).

Since I'm unable to reproduce this problem with Anaconda or pip, could install one of them and try again?

Also, could you describe how you're trying to copy the plot?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Abhinav-IIRS** [comment]
Hello, I am having the same issue with copying and pasting. I use spyder on HPC with CentOS. Earlier the problem of pasting of text outside from spyder application into spyder editor was common. If clicked on some other text, the new text would be copied to clipboard and previous one removed. However, now it seems that I cannot copy and paste anything within the editor and console.
