### ISSUE TITLE
Then please run

### ISSUE THREAD

**Issue by AABotros** [spyder-ide/spyder#15644]
Hi, I was getting an error and found these instructions:

Then please run

    conda remove spyder-kernels
    conda install spyder-kernels=0.*
    conda install spyder=3.3.1

_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/7802#issuecomment-417952290_

I was able to execute the first one, but now when I try executing the second, I get this error:
ModuleNotFoundError: No module named 'conda'
any ideas?

Thanks

**Comment by steff456** [comment]
Hi @AABotros,

Did you installed Spyder with conda? Also, do you have conda installed in your computer?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
