### ISSUE TITLE
Everthing is perfect,  Kite=Ready, LSP Python = ready, but there is no autocomplete 

### ISSUE THREAD

**Issue by AnthonyTheKoala** [spyder-ide/spyder#15642]
Dear assignee(s),  
First thank you for your time, it is appreciated.
### Autocompletion appears not to work
I have the following status bar:  
Kite = Ready, LSP Python = ready.
![image](https://user-images.githubusercontent.com/26536316/118400145-be167780-b6a3-11eb-9c64-10299ca26f80.png)

The Kite installed is from the binaries from the Kite site at https://www.kite.com/download/

### What happens when one tries autocompletion:
As mentioned before, Kite = ready
![image](https://user-images.githubusercontent.com/26536316/118400145-be167780-b6a3-11eb-9c64-10299ca26f80.png)

When one installs Spyder and Kite, one of the tabs has a Kite Tutorial.

![image](https://user-images.githubusercontent.com/26536316/118400866-ce7c2180-b6a6-11eb-952f-aa76ec1cfe8a.png)

I use the tutorial as an example of using the autocompletion.

The tutorial says to ensure that the Kite is "switched on" by pressing CTRL+space.

In the first two exercises, the first is supposed to autocomplete `matplotlib` after typing a.  The second is supposed to suggest that by pressing the dot after matplotlib, it is supposed to suggest a function as pyplot. 

![image](https://user-images.githubusercontent.com/26536316/118403994-6cc2b400-b6b4-11eb-830d-b2a45b5e0e3f.png)

In other words, in the first exercise, I type 'a' after the dot. No autocompletion.
In other words, in the second exercise, I type a '.' after matplotlib. No autocompletion.

Yes, I have set the preferences in Preferences to autocomplete to 1 character and delay of 100ms, and enabling Kite:
![image](https://user-images.githubusercontent.com/26536316/118403422-9d551e80-b6b1-11eb-8b08-99d3bbc9c633.png)

BUT autocompletion seems to work on writing a program, BUT not as suggested by the Kite tutorial:

I try an an example program the following lines

```
import matplotlib 
import numpy as np
np.
```
In the first example, as soon as I type m, I get suggested with `math, matplotlib, multiprocessing`.,,,,
**BUT** 
in the second example, when I type `np. `The suggestions drop down list appear after 17 seconds, NOT immediately. eg `random, int, array `etc.

### Summary:
* Kite and LSP Python have ready status as shown above.
* Autocompletion did not work as supposed on the Kite tutorial
* Autocompletion did work when writing one's own program, BUT after 17 seconds.
* Settings in Preferences are as suggested for timing 100ms and autocompletion after 1 character as shown above.

### Other info:
OS: Windows 10 recently installed.
Python: 3.8.10
Spyder: 5.0.2
Kite: Version: 1.2021.310.0, downloaded from the Kite site, https://www.kite.com/download/

Thank you, gracias, merci
Anthony of Sydney

**Comment by ccordoba12** [comment]
As we found last time we tried to help you, you're using a custom (i.e. pip) installation. And as you discovered then, by using `pip --user` you broke our code completion machinery, which took us several messages and the participation of two team members to find out.

Therefore, unless you're willing to use our Windows installer or Anaconda, we won't be able to help you anymore. That's because pip installations are really hard to debug and we don't have the time nor the resources to support them.

It's also fine if you want to keep using pip, but please don't open more bug reports for your installation.

Thanks for understanding.

**Comment by AnthonyTheKoala** [comment]
Dear Carlos,
Thank you for your reply.

### Introduction - Spyder Binary from your site had issues, I had no issue with a pipped version on my other machine.

For your information, I did use the binaries for Spyder, and after a while, I kept getting errors in the IPython console. The IPython did not even operate on the basis of the Spyder binary even when I reinstalled IPython. That was with a Spyder installation from https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe .  

* Yes the binary installation has issues.

* For your information, which I neglected to say to you, I have another machine with a **pipped** version of Spyder, and it works **PERFECTLY.**  It was **not a binary installation** of Spyder from https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe. There was no issue in that matter.

**I had problems with the binary executable of Spyder from the Spyder website.**
* What I did with the machine that I had trouble with was to uninstall the Spyder binary from https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe . I removed it completely because I got trouble with the IPython console within Spyder even where there was an uninstall reinstall of the binary executable from https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe. 

* Then I did a **complete clean install** of the Python located at c:\python38. 

### Problem with Spyder had to do with Python interpreter 3.8 onwards being more reliant on Windows 10.
* Problems with Spyder were also related to Python 3.8 onwards being more reliant on Windows 10 and less on Windows 7. **So in the last few days from about 13-05-2021, I changed the OS to Windows 10 **

### Complete reinstall of Python 3.8 
* The complete reinstall of Python included a complete reinstall of Spyder via the pipping.
* For your information, my environment variables for user = me and system are the same. This includes the PATH. 
  I set them up that way, so it would not matter that I `pip install package `or `pip install --user package`.
* There were no issues when I pipped other packages whether I used the `pip install package `or `pip install --user package`.
* This result was that Spyder worked as expected. The Kite and LSP Python were 'ready' , not as before in previous issues that I raised on this site

### Issue: autocompletion taking more than several seconds.
* However, the autocompletion was taking over 17 seconds to show a drop box of autocompletion suggestions.
Eg:
import numpy as np.
np.        
After the dot '.' it took nearly 17 seconds to get a drop down box of suggestions.

* The settings were as suggested by Kite.
![image](https://user-images.githubusercontent.com/26536316/118530668-3fdfd100-b788-11eb-8c33-244204c1385f.png)

So my question was why am I getting a delay of displaying Kite's suggestions as soon as I hit the "."

Thank you again, gracias, merci,
Anthony of Sydney

**Comment by AnthonyTheKoala** [comment]
### Update:
Installed the latest pipped Spyder==5.0.3
The problem still exists but the duration to get the dropdown list after the dot has been reduced.
Eg in the text editor of Spyder.
```
import tensroflow as bob
import keras as boo
boo.

```
The time for the droplist of suggestions takes time but been reduced to about 5 seconds.

Thank you,
Anthony of Sydney

**Comment by ccordoba12** [comment]
Unfortunately, it is not possible for us to show completions for `arange`. However, you can get them for `np.array`.

It's a bit complicated to explain why, but we'll try improve that in the future.
