### ISSUE TITLE
Unable to view source code tree in Spyder 5

### ISSUE THREAD

**Issue by gamesbook** [spyder-ide/spyder#15640]
* Spyder version: 5.0.0
* Python version: Python 3.7.7 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Mint 19 - Linux 4.15.0-135-generic 

I recently upgraded to Spyder 5 and am now unable to see / access the expandable code "tree" (outline) that was working in the previous version.

Image below is all I can see (e.g. for a typical Django models file) - what is needed to create/activate the code tree?

![spy](https://user-images.githubusercontent.com/354027/118399551-0317bb00-b65e-11eb-9f5f-947cff531b6c.png)

(Note I am **not** showing the code pane - this problem is constant regardless of the structure of any Python file I have open).

**Comment by ccordoba12** [comment]
Hey @gamesbook, thanks for reporting. This problem was fixed in our 5.0.2 version, released a week ago. Hopefully, the Anaconda team will update Spyder to that version soon.

**Comment by gamesbook** [comment]
Which is the best place to check for new Anaconda releases?

**Comment by ccordoba12** [comment]
This is where I look for them:

https://repo.anaconda.com/pkgs/

**Comment by gamesbook** [comment]
OK, thanks - if I go to https://repo.anaconda.com/pkgs/main/linux-64/ - I see they are still packaging 5.0.0 from 13 April.  I assume I just need to keep checking back every few days.
