### ISSUE TITLE
sort list variable error

### ISSUE THREAD

**Issue by cdhx** [spyder-ide/spyder#15650]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\HX\.conda\envs\py36\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 250, in fetchMore
    self.rows_loaded + items_to_fetch)
  File "C:\Users\HX\.conda\envs\py36\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 179, in set_size_and_type
    for index in range(start, stop) ]
  File "C:\Users\HX\.conda\envs\py36\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 179, in <listcomp>
    for index in range(start, stop) ]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.13
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.3.1 (OK)
pycodestyle >=2.3:  2.7.0 (OK)
pygments >=2.0   :  2.8.1 (OK)
pandas >=0.13.1  :  None (OK)
numpy >=1.7      :  None (OK)
sphinx >=0.6.6   :  1.8.5 (OK)
rope >=0.9.4     :  0.18.0 (OK)
jedi >=0.9.0     :  0.18.0 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.0.3 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  2.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Hey @cdhx, thanks for reporting. This problem is fixed in our latest Spyder 3 version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda install spyder=3.3.6
