### ISSUE TITLE
Spyder3 needs escaped backslash "\\" for fixed_directory values in the spyder.ini file when using a UNC network path

### ISSUE THREAD

**Issue by swizard101** [spyder-ide/spyder#15652]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Setting of Tools/Preferences in two places for "The following directory:" under Run and Current Working Directory will save UNC paths to network drive without escaped backslashes. Looking in "spyder.ini" the save paths have only the standard single slashes that the Windows dialog GUI hands back to Spyder. However Spyder does not then add in the needed escape characters to change each "\" to "\\" and for that reason the startup code of Spyder does not work to set the desired working directory for files or the console.

### What steps reproduce the problem?

1.  Open Tools/Preferences and select "Run" (or  "Current Working Directory"
2.  Select "The following Directory" item
3. Click the folder icon at far right, navigate to a network UNC path and folder, then pick it
4. Observe the string has non-escaped "\" characters
5. Close Spyder3 and then open and view the spyder.ini file
6. Search for "fixed_directory" and observe the spyder.ini file has a string without escaped "\" characters
7. Start Spyder3 and it does not set the desired path due to expecting a string with escaped "\\" characters
 

### What is the expected output? What do you see instead?
N/A

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.7.0
* Qt version: N/A
* PyQt version: N/A
* Operating System name/version: Windows 10 Enterprise Ver. 1809 (OS Build 17763.1579)

### Dependencies

```
N/A
```

**Comment by ccordoba12** [comment]
Hey @swizard101, thanks for reporting. Unfortunately, we don't support Spyder 3 anymore. Could you try with our latest version (5.0.3) and try again?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
