### ISSUE TITLE
Clicking on an error message no longer takes me to the error line in the file.

### ISSUE THREAD

**Issue by domokane** [spyder-ide/spyder#15663]
## Problem Description
When I have an error report from running code within Spyder, clicking on the path to the file that was reported in the error message used to open the file in the editor at the correct line number. This does not happen any more in Spyder 5.0.

### What steps reproduce the problem?

1. Run code
2. Error message from code
3. Left click on error message
4. Nothing happens

### What is the expected output? What do you see instead?
I expect it to open the file. I even see the cursor change to a hand with a finger but nothing happens when I do a left mouse click.  

I am using Spyder 5.0.0.

**Comment by andfoy** [comment]
Hi @domokane, have you tried to update to Spyder 5.0.3 to see if this error persists?

**Comment by domokane** [comment]
That fixed it! Thanks.
