### ISSUE TITLE
conda install spyder=3.3.6 fails in Python 3.5 Environment

### ISSUE THREAD

**Issue by Acetyl-CodeA** [spyder-ide/spyder#15671]
conda install spyder=3.3.6
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spyder=3.3.6 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.5

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

I can't fix it because it fails at this step.

_Originally posted by @Acetyl-CodeA in https://github.com/spyder-ide/spyder/issues/15670#issuecomment-846257000_

**Comment by ccordoba12** [comment]
Hey @Acetyl-CodeA, thanks for reporting. Unfortunately, there's nothing we can do about this because there are no conda packages available for our 3.3.6 and Python 3.5.

I'm afraid you'll have to create an environment with Python 3.6 for, with the following command

    conda create -n py36 python=3.6 spyder=3.3.6

After that, you need to activate your environment and run Spyder after that

    conda activate py36
    spyder

Please try that and let us know if it works for you.

**Comment by Acetyl-CodeA** [comment]
Thank you so much for your help @ccordoba12 ! (Sorry for the delay in followup) 

Unfortunately, I'm using a Python library that is not supported past 3.5 so I can't use 3.6.  Luckily I have Spyder working for my other environment with the latest version of Python, but this won't work for me. Thank you for letting me know that there's not conda packages available! I'll try a different workaround then.

Appreciated, 
Acetyl-CodeA

**Comment by ccordoba12** [comment]
In that case, you can connect a more recent Spyder, installed in another environment, to your Python 3.5 environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by Acetyl-CodeA** [comment]
So the issue isn't getting Spyder (as a whole) working it's the kernel that's not working. I can get Spyder's kernels (and everything else) working regardless on the 3.6.8 version but I cannot get the kernels working on the 3.5 version.
