### ISSUE TITLE
Issues in spyder w/ tabs

### ISSUE THREAD

**Issue by ElJdP** [spyder-ide/spyder#15673]
![image](https://user-images.githubusercontent.com/68053570/119232850-f0eac080-bb26-11eb-82ed-554982de35c3.png)
As you can see, i've clicked help. Unfortunately, it doesn't open. Any of the tabs don't work, just like hidden files. It's a recent issue I've encountered in recent weeks after updating to spyder 5.0.2 (just updated to 5.0.3, same problem)

I'd be happy if this could be fixed

**Comment by ccordoba12** [comment]
@ElJdP, we have thought about this before. Please do not open an issue without filling our template info.

Please reopen this issue again with that info filled. Thanks!

**Comment by ElJdP** [comment]
Hello,
I can't really reproduce it, as in it is just the menu itself. It is not a
coding issue, I just could not open buttons like click, help etc.

**Comment by ccordoba12** [comment]
That error is most likely caused by some packages Spyder depends on because we're not observing it. That's why we need to information we require in our template.
