### ISSUE TITLE
ImportError: DLL load failed while importing win32security

### ISSUE THREAD

**Issue by GAS33** [spyder-ide/spyder#15672]
### What steps will reproduce the problem?

I just opened spyder and the message
was already in the console saying
a error was occurred while starting
the kernel. At the last part of 
this message was the ImportError:
DLL load failed while importing
win32security: %1 no es una aplicación
win32 válida. 

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @GAS33, thanks for reporting. This usually happens because because at some point you used pip to install packages provided by Anaconda.

Please create a new conda environment to see if the error disappears. For that, please close Spyder, open the Anaconda prompt and run there

    conda create -n test-env python=3.8 spyder=4.2.5
    conda activate test-env
    spyder

If that works but you don't want to use an environment to use Spyder, I'm afraid you'll have to reinstall Anaconda. For that, please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) for that.

**Comment by GAS33** [comment]
Thanks for your support. I really appreciate it. 

I tried to reinstall Anaconda but it didn´t work. 

I can work now in a new environment but I am having some troubles yet. This new environment doesn´t allow me to install slycot, So I can not run my code. 

Do you know why the problem persists even when I reinstalled Anaconda? 
I followed all the steps in the video but I am still struggling with it.

**Comment by ccordoba12** [comment]
> Do you know why the problem persists even when I reinstalled Anaconda?

You need to remove this directory too, in case it's present:

    C:\Users\<your user>\AppData\Roaming\Python\

**Comment by dalthviz** [comment]
Closing due to lack of response
