### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by upendra122** [spyder-ide/spyder#15678]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/qtconsole/console_widget.py", line 1520, in _on_flush_pending_stream_timer
    self._flush_pending_stream()
  File "/usr/lib/python3/dist-packages/qtconsole/console_widget.py", line 1532, in _flush_pending_stream
    self._insert_plain_text(self._get_end_cursor(), text, flush=True)
  File "/usr/lib/python3/dist-packages/qtconsole/console_widget.py", line 1820, in _insert_plain_text
    for substring in self._ansi_processor.split_string(text):
  File "/usr/lib/python3/dist-packages/qtconsole/ansi_code_processor.py", line 144, in split_string
    raw = string[start:]
MemoryError

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.5.0 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @upendra122, thanks for reporting. I'd like to ask you things:

1. Please update Spyder to our latest Spyder 3 version by opening the Anaconda prompt and running there

        conda install spyder=3.3.6

2. After that, if the error appears again, please let us know what series of steps are necessary to generate it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
