### ISSUE TITLE
spyder  1>nul 2>nul

### ISSUE THREAD

**Issue by mazalgarab-git** [spyder-ide/spyder#15688]
### What steps will reproduce the problem?

Get Anaconda Version2.0.3
Get Spyder version 4.2.5
Launch Spyder
Issue-> It appears a comment 'spyder 1>nul 2>nul' in 'cmd.exe' window. The windows does not get close.

---------------------------------------
Windows Detail | cmd.exe
---------------------------------------

C:\Users\mazal>chcp 1252
Active code page: 1252

C:\Users\mazal>call C:\Users\mazal\Anaconda3\Scripts\activate C:\Users\mazal\Anaconda3\envs\DICOM

(DICOM) C:\Users\mazal>spyder  1>nul 2>nul

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.10
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.9.0 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  None (NOK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @mazalgarab-git,

Can you please give me some steps to try to reproduce this issue? Have you tried to install Spyder using the installers for Windows?

**Comment by ccordoba12** [comment]
Hey @mazalgarab-git, this problem happens only with Anaconda Navigator. It doesn't occur if you start Spyder from the Anaconda Prompt or using our installers, as @steff456 mentioned.

Since we can't make changes in Navigator because it's an Anaconda product, please report this problem in

https://github.com/ContinuumIO/anaconda-issues/

**Comment by mazalgarab-git** [comment]
No. I tried to install Spyder using Anaconda.

  *   Get Anaconda 2.0.3
  *   Get Spyder 4.2.5
  *   Run Spyder
  *   ---> A windows of cmd.exe appears with the message “spyder 1>nul 2>nul”; if one tries to close the windows, the Spyder window closes along with the cmd.exe window.

Regards,

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by lauracami0742** [comment]
Hi! I have the same issue. Did you @mazalgarab-git find out how to fix it?

**Comment by ccordoba12** [comment]
@lauracami0742, this is not a problem with Spyder so we can't solve it here. It's a problem with Anaconda Navigator.

**Comment by ccordoba12** [comment]
No, we can't fix here, sorry.

**Comment by aleksandar-anastasov** [comment]
Try this in anaconda.navigator: 
1. go to File >> Preferences >> Configure Conda >> Reset to defaults
2. go to File >> Preferences >> Configure Navigator >> Reset to defaults
This worked for me.

**Comment by kuldeepbishnoi** [comment]
Thanks @aleksandar-anastasov 
It worked for me too and launching time of anaconda also reduced significantly

**Comment by trsnacr** [comment]
@aleksandar-anastasov thank you ıt worked !

**Comment by RaulMazilu** [comment]
@aleksandar-anastasov still works as of Nov 23. Thanks!
