### ISSUE TITLE
possible to use spyder 4 icons with spyder 5?

### ISSUE THREAD

**Issue by manfred2020** [spyder-ide/spyder#15686]
not a real issue, but it it possible to use the old icons with spyder 5? or is it planned for future if it's not possible now?

the design up to spyder 4.2.5 was really good and pretty, now it's a step backwards.

**Comment by ccordoba12** [comment]
Hey @manfred2020, thanks for reporting. Unfortunately, that's not possible, sorry.

Also, it's sad to hear that you consider our new design a step backwards. Most people liked it (including us) but we can't please everyone.
