### ISSUE TITLE
Automatically update doctest example outputs

### ISSUE THREAD

**Issue by Illviljan** [spyder-ide/spyder#15684]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [N/A] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [N/A] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [N/A] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [N/A] Tried basic troubleshooting (if a bug/error)
    * [N/A] Restarted Spyder
    * [N/A] Reset preferences with ``spyder --reset``
    * [N/A] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [N/A] Tried the other applicable steps from the Troubleshooting Guide
* [N/A] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Docstring examples are a great way of explaining how a function works to the new user. But creating and maintaining excellent doctest examples can be rather time consuming. It's rather common that something upstream changes the display of the repr or some bugfix changes all the outputs which makes maintainers reluctant in adding a lot of doctests.

Spyder can make this easier by running the doctests and fixing the output when requested. 

Example of module that spyder could call with this functionality:
* https://github.com/max-sixty/pytest-accept

**Comment by steff456** [comment]
Hi @Illviljan,

Thank you for sharing this package, unfortunately the majority of the tests for Spyder require the use of graphic elements that could be overwhelming to add in the docstring of every function. As well, the majority of the tests have a lot of mocks to make them work isolated from the complete application. Also, we are working towards using Numpy docstring convention which doesn't include this type of testing. 

In case I completely misunderstood your issue, you could create new external plugin for Spyder that enables users to use that package while working in Spyder. If you need help to know where to get started with this please let us know.

Thanks for reporting!

**Comment by Illviljan** [comment]
This was indeed a new feature suggestion from a user perspective. 

For example you have the file `add.py` which contains:
```python
def add(x, y):
    """
    Adds two values.

    >>> add(1, 1)
    3

    >>> add("ab", "c")
    'bac'
    """

    return x + y
```

Which has wrong docstring results at the moment. 

Now click on some spyder button and it will fix the docstring to:
```python
def add(x, y):
    """
    Adds two values.

    >>> add(1, 1)
    2

    >>> add("ab", "c")
    'abc'
    """

    return x + y
```

To me this seems to be in a similar Quality of Life-scope as the:
 * automatic docstring construction 
* autoformatting on save using black.

I have no interest in maintaining this as an external plugin.

**Comment by steff456** [comment]
Great @Illviljan,

We could discuss with the team to add this as an external plugin for the PyLS server, but if you are not interested in maintaining it we will have this on our low priority list. 

Thanks for reporting!

**Comment by ccordoba12** [comment]
Hi, unfortunately we don't time to work on this and it hasn't been requested by other users. So, I'm going to close it as not planned.
