### ISSUE TITLE
Kernal Restart Issue

### ISSUE THREAD

**Issue by SanjuSoni** [spyder-ide/spyder#15699]
I am unable to restart the kernel in Spyder 5.

Please help me to fix this issue.

**Comment by ccordoba12** [comment]
Hey @SanjuSoni, what's your Spyder version? And how did you install it?

**Comment by SanjuSoni** [comment]
Thanks @ccordoba12 

I have created an environment in Anaconda for TensorFlow version 1.15.

Then I installed the spyder editor using the command  "   pip install spyder " which installed version 5.0.0

**Comment by ccordoba12** [comment]
Ok, please install our 5.0.3 version and try again. The problem we had to restart kernels should be fixed on that version.

**Comment by SanjuSoni** [comment]
@ccordoba12 
the following command will work for installing spyder version 5.0.3
"  pip install spyder=5.0.3 "

**Comment by ccordoba12** [comment]
No, it needs to be

    pip install spyder==5.0.3

**Comment by SanjuSoni** [comment]
Thank @ccordoba12 


I used  the command
"pip install --upgrade spyder"

Now after upgrading kernel is accepting the restart command.

**Comment by ccordoba12** [comment]
Great! I'm glad it works for you now.
