### ISSUE TITLE
Variable explorer does not work with remote kernel

### ISSUE THREAD

**Issue by drinbs** [spyder-ide/spyder#15701]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I connected spyder (ver.5.0.3) to the remote kernel in the docker image of the same machine, the variables in variable explorer are not updated. If I re-connect to the remote kernel with closing tab and selecting 'Connect to an existing kernel', the variables are updated.
I also noticed that when I use older version (4.2.5) with the same way, spyder crashes as soon as I selected variable explorer panel. The variable explorer works perfectly if I use local kernel.
As I am noob in connecting external kernel and docker, correct me if I am wrong.

### What steps reproduce the problem?

1. Set up kaggle docker image with following Dockerfile and docker-compose.yml.
```
FROM gcr.io/kaggle-gpu-images/python:v100
ENV NVIDIA_VISIBLE_DEVICES all
ENV LD_LIBRARY_PATH=/usr/local/cuda/lib64
RUN pip install -U pip && \
    pip install fastprogress japanize-matplotlib mlflow && \
    pip install pretrainedmodels efficientnet_pytorch

RUN conda install -c conda-forge nodejs spyder=5.0.3

RUN jupyter labextension install @lckr/jupyterlab_variableinspector

RUN pip install autopep8 \
    && pip install jupyterlab_code_formatter \
    && jupyter labextension install @ryantam626/jupyterlab_code_formatter \
    && jupyter serverextension enable --py jupyterlab_code_formatter

RUN apt update && apt install -y openssh-server
RUN mkdir /var/run/sshd
RUN sed -i "s/#PermitRootLogin prohibit-password/PermitRootLogin yes/g" /etc/ssh/sshd_config &&\
echo "root:password" | chpasswd
ENV NOTVISIBLE "in users profile"
RUN source /usr/local/sdkman/bin/sdkman-init.sh;echo "PATH=/usr/local/spark/bin:${PATH}" >> ~/.bashrc &&\
 echo "if [ -f ~/.bashrc ]; then  . ~/.bashrc;  fi" >>~/.bash_profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
```
```
version: "2.3"
services:
  spyder:
    build: .
    volumes:
      - ./:/tmp/working
    working_dir: /tmp/working
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "20022:22"
    command: /usr/sbin/sshd -D
    restart: always
```
2. Run docker-compose, SSH to the remote kernel in the docker image, and run 'python -m spyder_kernels.console' .
2. Run spyder in the local machine and connect to the remote kernel with 'Connect to an existing kernel'.
3. Input variables.

### What is the expected output? What do you see instead?
The variables in the variable explorer should be updated as soon as I input something.

## Versions

Local
* Spyder version: 5.0.3
* Python version: 3.8.8 64-bit 
* Qt version: 5.12.10
* PyQt version:  5.12.3 
* Operating System name/version: 5.8.0-53-generic 

Remote (base: kaggle docker v100)
* Spyder version: 5.0.3
* Python version: 3.7.10 64-bit 
* Qt version: 5.12.9
* PyQt version:  5.12.3 
* Operating System name/version: 5.8.0-53-generic 

### Dependencies

Local

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @drinbs thanks for the feedback! Maybe this is related with https://github.com/spyder-ide/spyder/issues/14894 ? 

Pinging @ccordoba12 just in case

**Comment by ccordoba12** [comment]
Yeah, I think it's a similar case. @drinbs, you need to open all ports necessary for the connection. As you see on #14894, the comms port (which is the one that makes the variable explorer work) is created on the fly and not listed in the kernel json file.

**Comment by drinbs** [comment]
Thank you for your reply!
I searched, but missed it. The variable explorer now works perfectly.

For those interested, this is what I did.

1. Get comm port number with get_ipython().kernel.frontend_comm.comm_port in spyder console (in my case 46757)
2. Add this port number to my docker-compose.yml file
3. Re-run docker-compose
