### ISSUE TITLE
Anaconda main spyder distrib well behind latest (5.0.0 vs 5.0.3)

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#15707]
I have just checked the latest [Anaconda main spyder release](https://anaconda.org/main/spyder/files) which is 5.0.0 updated on the 15th April, whereas the latest repo release here is 5.0.3 updated 17 May.

Is there an Anaconda channel that we can raise an issue to get the more up-to-date release made available through Anaconda?

**Comment by dalthviz** [comment]
Hi @durack1 thanks for the feedback! Currently if you want to have the latest version using conda you can use the conda-forge channel to install it. The best to not mix packages then is to create a new env and install there the latest spyder. You can run something like this:

    conda create -n latest_spyder spyder=5.0.3 -c conda-forge

There is not much we can do but to wait for Anaconda to update the package in the default channel I'm afraid. Pinging @ccordoba12 just in case

**Comment by ccordoba12** [comment]
> Is there an Anaconda channel that we can raise an issue to get the more up-to-date release made available through Anaconda?

Please complain about that here:

https://github.com/ContinuumIO/anaconda-issues/

Unfortunately, there's nothing we can do about it. I've written personal emails to ask for updates to my former Anaconda manager, but it's been unhelpful too.
