### ISSUE TITLE
Pylint uses startup Python interpreter/enviroment even if costum interpreter/enviroment is set

### ISSUE THREAD

**Issue by mwawra** [spyder-ide/spyder#15709]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
If Spyder is installed and opened from an enviroment in which a module is not installed and then a costum interpreter of another enviroment is set in which this module is installed, it can be imported, but Pylint does not find the module ("E0401 (import-error): Unable to import 'foo'.").
Pylint seems to always take the enviroment that was used at startup.

### What steps reproduce the problem?

1. Open Spyder in env A (without module foo)
2. Change to interpreter of env B (with module foo)
3. Analyze Python file with "import foo"

### What is the expected output? What do you see instead?
No import error expected.
Pylint raises error E0401 (import-error).

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by dalthviz** [comment]
Hi @mwawra thank you for the feedback! I was able to reproduce this, we will work on it in a future release :+1:

**Comment by mwawra** [comment]
Hello @dalthviz , thank you for keep e look on this.

**Comment by mwawra** [comment]
Hello @dalthviz, thank you for looking at this!
I had some time on the weekend and played with different solutions for this problem.
Since I'm not sure what the best way would be, I wanted to discuss this here before I make a PR.
Possible solutions:
1. Run pylint from the custom env -> pylint must be installed in this env (against the module approach of spyder)
2. Run pylint from the custom env with the site-package-path of the default env in PYTHONPATH (use processEnvironment.insert("PYTHONPATH", s_p_pypath)) -> all packages in the default env are also seen and "used" by pylint
3. Run pylint from the default env and load the custom env in the init-hook (e.g. with pylint_venv) -> again all packages in the default env are also seen and "used" by pylint and there is a new dependency (if pylint_venv is used)
4. Copy pylint from default env to temp_path (e.g. with module tempfile), then run pylint from the custom env with the temp_path in PYTHONPATH (use processEnvironment.insert("PYTHONPATH", temp_path)) -> non of the above problems, but somehow "ugly"

I also thought about using importlib to just load pylint directly from its full path, but I couldn't get this to work, probably because there is a subprocess.Popen() in pylint.
Did I forget something? What would be your preferred solution?

**Comment by ccordoba12** [comment]
I think the easiest solution is to have Pylint installed in your env.

**Comment by dalthviz** [comment]
Hi @mwawra thanks for the interest in this one! Regarding the options, I guess number 1 seems good although probably then we need to somehow let the users know that they need to install also `pylint` in their custom envs to properly support their code analysis functionality if they use a custom env. How do you see that from a UI/UX element @ccordoba12 ?

**Comment by ccordoba12** [comment]
> How do you see that from a UI/UX element @ccordoba12 ?

Yeah, that's the thing that worries me. It's similar to the pain users have to go right now to install spyder-kernels in external envs.

In that case, perhaps we should use `pylint_venv`. But it seems to be tailored to the console (unless we could use it programmatically somehow).

**Comment by mwawra** [comment]
Apart from the somewhat tricky string formatting, there is no problem to use `pylint_venv` programmatically in main_widget.py of the pylint plugin in spyder.

Going back to installing pylint in the custom environment, wouldn`t it be possible to make `pylint` a requirement of the spyder-kernels? That way it would simply be installed along with it.

**Comment by mwawra** [comment]
@ccordoba12

**Comment by ccordoba12** [comment]
> Apart from the somewhat tricky string formatting, there is no problem to use pylint_venv programmatically in main_widget.py of the pylint plugin in spyder.

That's good news! Then, this is really the way to go.

> Going back to installing pylint in the custom environment, wouldnt it be possible to make pylint` a requirement of the spyder-kernels?

Although convenient, Pylint has nothing to do with our console kernels, so I'm -1 on this idea.

**Comment by mwawra** [comment]
> 
> 
> > Apart from the somewhat tricky string formatting, there is no problem to use pylint_venv programmatically in main_widget.py of the pylint plugin in spyder.
> 
> That's good news! Then, this is really the way to go.
>
Ok, I think I can make an PR tomorrow.

>
> > Going back to installing pylint in the custom environment, wouldnt it be possible to make pylint` a requirement of the spyder-kernels?
> 
> Although convenient, Pylint has nothing to do with our console kernels, so I'm -1 on this idea.

That's, of course, true.

**Comment by ccordoba12** [comment]
> Ok, I think I can make a PR tomorrow.

Great!! Thanks a lot for your help with that!

**Comment by mwawra** [comment]
Thank you for the helpful discussion!

**Comment by mwawra** [comment]
Hello, I somehow stuck with the PR, where do I have to insert the new requirement (pylint_venv)? I insert it to setup.py and dependencies.py. Right now, it is of course not installed when I install the dev-version of spyder. Since it is only available on pip I can not insert it to conda.txt.

**Comment by dalthviz** [comment]
Hi @mwawra I think we will need to create a feedstock for the package (to make it available through the `spyder-ide` channel for the tests). Also, you will need to add it to the `binder/environment.yml` file (besides the `conda.txt`), right @ccordoba12 ?

**Comment by ccordoba12** [comment]
The problem is that there's no conda package for it, so we'd need to create one.

@mwawra, do you have experience with it?

**Comment by mwawra** [comment]
Hello, no experience with building conda packages so far.
Anyway, conda package in conda-forge is on the way... [PR#15165](https://github.com/conda-forge/staged-recipes/pull/15165)

**Comment by mwawra** [comment]
Pylint-venv is know available on conda-forge.
