### ISSUE TITLE
Spyder Installation ERROR in Conda Environment

### ISSUE THREAD

**Issue by SanjuSoni** [spyder-ide/spyder#15713]
I am installing spyder using conda command inside an environment  (TF1)  creted in Conda.

command line is :    " `conda install spyder `"    
                                "  `pip install spyder`  "

outside TF1 env, above command installed the latest version of Spyder (5.0.3) but inside the env, I am getting the following errors.

Error message after using   ` conda install spyder `

```
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'defaults::qt-5.9.7-vc14h73c81de_0'.
Rolling back transaction: done

LinkError: post-link script failed for package defaults::qt-5.9.7-vc14h73c81de_0
location of failed script: C:\Users\suman\anaconda3\envs\TF1\Scripts\.qt-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout:         1 file(s) copied.

stderr: 'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.
'chcp' is not recognized as an internal or external command,
operable program or batch file.

return code: 1

()
```

Error message inside TF1 env: after using command    ` pip install spyder` is:

```
Requirement already satisfied: sphinx>=0.6.6 in c:\users\suman\anaconda3\envs\tf1\lib\site-packages (from spyder) (4.0.2)
Requirement already satisfied: ipython>=7.6.0 in c:\users\suman\anaconda3\envs\tf1\lib\site-packages (from spyder) (7.23.1)
Requirement already satisfied: paramiko>=2.4.0 in c:\users\suman\anaconda3\envs\tf1\lib\site-packages (from spyder) (2.7.2)
Requirement already satisfied: pickleshare>=0.4 in c:\users\suman\anaconda3\envs\tf1\lib\site-packages (from spyder) (0.7.5)
Requirement already satisfied: pyls-black>=0.4.6 in c:\users\suman\anaconda3\envs\tf1\lib\site-packages (from spyder) (0.4.6)
Collecting numpydoc>=0.6.0
  Using cached numpydoc-1.1.0-py3-none-any.whl (47 kB)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\users\\suman\\anaconda3\\envs\\tf1\\lib\\site-packages\\parso-0.7.0.dist-info\\METADATA'
```

Spyder is working well outside the TF1 env.

Please help me fix this issue

Thanks in Advance.

**Comment by andfoy** [comment]
Hi @SanjuSoni, we recommend you to install Spyder into its own environment and install other libraries, such as TensorFlow in your case in other environment. In order to get access to the Tensorflow environment from Spyder, you can change your current interpreter by clicking on the environment status bar widget and then selecting the `Change default environment in preferences`, there you can select `Use the following interpreter`, under which your Tensorflow environment should appear.

**Comment by SanjuSoni** [comment]
@andfoy 
I have discovered a new way to compile a code using different interpreter using your suggestion.

Still there is some lagging issue in the editor. It is taking longer time to type a single word in editor  which is potentially effecting my work.

Please suggest me to fix this issue.

Thanks

**Comment by ccordoba12** [comment]
@SanjuSoni, please look at issue #15631 for some possible fixes to your problem.
