### ISSUE TITLE
spyder not responsive, waiting circle

### ISSUE THREAD

**Issue by bytelinker** [spyder-ide/spyder#15729]
## Problem Description
Coding with Spyder for approx. 15-30 minutes on a 1000 line py file, the ide gets unresponsive. The waiting circle is showing up. The ide is blocked for 10-60 s and you can go on with coding. The duration of blocking seams to increase, when it start for the first time.

Kite is activated.

The issue may be caused by a proxy, but within Kite the proxy is disabled. Maybe other reasons are involved.

There is no log here, because it don't know where to find proxy related problems,

The problem can be solved by closing and restarting Spyder. But the problem will be back soon.

The problem started at least with Version 5.0. The problem also occurs with resetting the settings.

## Versions
* Spyder version: 5.0.3 None => Spyder from 64 bit full install with python included
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

Thank you very much.
bytelinker

**Comment by ccordoba12** [comment]
Hey @bytelinker, thanks for reporting. We're aware about the problems with large files, but fixing that requires a big refactoring in the editor, which is planned for the second half of the year.

For the issue that Spyder becomes slower after some time, please see issue #15631. There are several tips that could help you in the meantime.
