### ISSUE TITLE
Some suggest of Spyder

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#15727]
## Problem Description

Hope the spyder can have better the variable explorer for sympy. 
When I use this code,"from sympy import *", or use the SymPy console, the variable explorer always load too much varialbes. And the area of type-box always so big that the value-box are hidden. 
And the values displayed sometimes is hard to read. I think spyder can replace that with the  return value of the print function. I think this can be a way to deal with the displayed of the unsupported variables.

## Versions

* Spyder version: 5.0.3
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version:  win10

**Comment by ccordoba12** [comment]
Hey @Vincent0706, thanks for reporting. You said

> When I use this code,"from sympy import *", or use the SymPy console, the variable explorer always load too much varialbes

It seems you don't understand how those imports work, which is very similar to the way the Sympy console works too. They import a lot of variables and objects from Sympy to make it easier to work with that library. And those are the objects shown in the Variable Explorer.

One way to avoid that is to the activate the option called "Exclude unsupported data types". But then no Sympy object would be displayed in the Variable Explorer.

![image](https://user-images.githubusercontent.com/365293/120114921-06737200-c147-11eb-8a98-ea0902c34f83.png)

> I think spyder can replace that with the return value of the print function

Yeah, I agree. There's some work for that but unfortunately no one has been able to finish it:

https://github.com/spyder-ide/spyder-kernels/pull/129
