### ISSUE TITLE
Debugger broken with IPython 7.24.0

### ISSUE THREAD

**Issue by matheger** [spyder-ide/spyder#15738]
Running "Debug" (Ctrl+F5) on a file does not stop on breakpoints anymore, but simply runs through them.

I first noticed it after upgrading spyder in my normal work environment from 5.0.1 to 5.0.3. However, the same thing happens with a clean spyder install in a separate conda environment, even if I revert to .1 or .2.

Python 3.8.10 64-bit | Qt 5.12.9 | PyQt5 5.12.3 | Windows 10

**Comment by ccordoba12** [comment]
@matheger, thanks for reporting. Please post your full configuration (`conda list` or `pip list`) and a an animated git that displays your problem (you generate it with the Licecap program).

**Comment by matheger** [comment]
Just using a random assignment to demonstrate. Same thing happened anywhere in actual production code.

![Animation](https://user-images.githubusercontent.com/34485360/120137121-dbae0b80-c190-11eb-90f6-b226aeec387f.gif)

**Comment by matheger** [comment]
`conda list`:

**Comment by ccordoba12** [comment]
@matheger, thanks for the gif. This problem was introduced by IPython `7.24.0`, released last Friday. I already submitted a couple of PRs there, so hopefully this issue will be fixed soon.

In the meantime, please downgrade to version `7.23.1`.

**Comment by arnaud-nt2i** [comment]
I'm still having the debugger bug with spyder 5.0.4 and kernel 2.0.4...
So I still need to downgrade IPython ?
