### ISSUE TITLE
Spyder -Anaconda is very slow

### ISSUE THREAD

**Issue by korosig** [spyder-ide/spyder#15748]
I have installed Spyder 4.1.5 (behind Anaconda), and when I open a large CSV file, the Spyder IDE is working with terrible slow speed. For example for df.info(), df.describe() I have to wait minutes. While I search for the solution for this problem, I have installed the Sypder 5.0.3 which is works well, but It is not supported by Anaconda, and I have a problem with package access.

My questions are:
- Why Syder 4.1.5 (behind Anaconda) is superslow with DataFrames
- How can I setup Spyder  5.0.3 to use the same environment as Spyder 4.1.5 (behind Anaconda)

My machine has iCore 9, 64Gb mem, with 1T SSD and 2x3080GeFroce so the hardware is not the bottleneck.....  

Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)]
IPython 7.22.0 
conda 4.10.1
Anaconda Navigator 1.10.1

**Comment by ccordoba12** [comment]
Hey @korosig, thanks for reporting. You said:

> Why Syder 4.1.5 (behind Anaconda) is superslow with DataFrames

I really don't know. We've fixed a lot of things since 4.1.5, which is several months old. But even if I do, we don't support Spyder 4 anymore, which means that all fixes go to Spyder 5.

> How can I setup Spyder 5.0.3 to use the same environment as Spyder 4.1.5 (behind Anaconda)

Please read our FAQ about that:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

and let us know if it works for you.

**Comment by korosig** [comment]
Hi 

I have installed Spyder 5 (behind Anaconda) and I got the same problem. I tested my script in Jupiter and it works fast.

I did the next things:
I loaded a 1.3 Gb CSV with pandas, and then I use df.info(), df.columns, etc.
It is often freezing or, I have to wait minutes to run. By comparison, in jupyterlab, this runs in seconds.

tested with (Python 3.8.8 , IPython 7.22.0 , Spyder 4.2.5, pandas 1.2.4)  - very slow
tested with (Python 3.9.5 , IPython 7.22.0 , Spyder 5.0.0, pandas 1.2.4)  - very slow

tested with (Python 3.8.8 , Jupyter lab 3.0.14, pandas 1.2.4) - Fast

I reinstalled ANACONDA, SPYDER, PYTHON, and all packages....

**Comment by korosig** [comment]
I hope I found the source of the error..

When I use these lines, the SPYDER broke down....

pd.set_option('max_columns', None)
pd.set_option('max_rows', None)
pd.set_option('max_colwidth', None)

**Comment by ccordoba12** [comment]
What those options do?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
