### ISSUE TITLE
chcp 1254 Active code page: 1254

### ISSUE THREAD

**Issue by taneresen** [spyder-ide/spyder#15750]
### What steps will reproduce the problem?

When I was starting spyder in anaconda firstly opening "C:\Windows\system32\cmd.exe". after that : C:\Users\taner>chcp 1254
Active code page: 1254

C:\Users\taner>call C:\Users\taner\anaconda3\Scripts\activate C:\Users\taner\anaconda3

(base) C:\Users\taner>spyder  1>nul 2>nul

after update this windows comme. 

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.10
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.9.0 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  1.20.2 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @taneresen,

This error happened when you started Spyder or when you started Anaconda navigator? Can you please try to open Spyder from the terminal by opening a system terminal and typing `spyder` and see if it runs as expected?

**Comment by taneresen** [comment]
Hi @steff456 ,

no problems starting anaconda, but whenever I start spyder I get this error.I don't get this error in terminal.very strange situation.I'll be happy if you can help me.

**Comment by steff456** [comment]
So you only get this error when trying to launch Spyder from the anaconda navigator?

**Comment by taneresen** [comment]
hi @steff456 ,

Yes

**Comment by steff456** [comment]
If Spyder is running from your terminal but not from Anaconda Navigator, then the problem is on their side and we cannot do anything to fix it. If you are interested in having Spyder as an application and launch it without the terminal I will recommend you to download one of our installers for Windows (https://github.com/spyder-ide/spyder/releases/tag/v4.2.5).

If you are interested you could also report this issue on Anaconda Navigator: https://github.com/conda/conda/issues

Hope this helps and thanks for reporting!

**Comment by taneresen** [comment]
hi @steff456 

Thankyou so much for your answer.
