### ISSUE TITLE
Icons are covered on words

### ISSUE THREAD

**Issue by Einspanner123** [spyder-ide/spyder#15764]
## Icons are covered on words
Open any of the menu's icon
you'll see them

**Comment by Einspanner123** [comment]
Spyder5

**Comment by dalthviz** [comment]
Hi @Einspanner123 could you provide us the details regarding your installation (Spyder, Qt/PyQt, Python version, OS, etc)? We had errors related with the icons layout for Spyder 5.0.0 but the current version is 5.0.3 so probably an update could help.

Let us know if after updating you keep seeing the strange layout in the menus.

**Comment by caleyjag** [comment]
> Hi @Einspanner123 could you provide us the details regarding your installation (Spyder, Qt/PyQt, Python version, OS, etc)? We had errors related with the icons layout for Spyder 5.0.0 but the current version is 5.0.3 so probably an update could help.
> 
> Let us know if after updating you keep seeing the strange layout in the menus.

I can confirm that updating from 5.0.0 to 5.0.3 fixed the problem for me (Windows 10). Thanks!

**Comment by dalthviz** [comment]
Note: Updating Spyder 5.x to the most recent version should help
