### ISSUE TITLE
The editor is non responsive

### ISSUE THREAD

**Issue by ski123786** [spyder-ide/spyder#15776]
### What steps will reproduce the problem?

While just typing in the spyder editor, after few minutes the spyder editor becomes very less response and a high usage of memory and CPU are observed during that time. The similar behavior was also observed in spyder 4 version.

**Comment by andfoy** [comment]
Hi @ski123786, we are aware of this problem and we are working towards a solution to it. I'm closing this one, since it is a duplicate of https://github.com/spyder-ide/spyder/issues/14823
