### ISSUE TITLE
SpyderKernelApp

### ISSUE THREAD

**Issue by shunlei-li** [spyder-ide/spyder#15773]
### What steps will reproduce the problem?

I can run my code and spyder show an error. But when I debug it, Console shows warning as shown in this:

--- load model ---
start the training at epoch 0

--- train ---
[SpyderKernelApp] WARNING | WARNING: attempted to send message from fork
{'header': {'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'username': 'shunlei', 'session': '46f554ff-d257cc9e51819bf04bb2ce2d', 'date': datetime.datetime(2021, 6, 3, 15, 35, 7, 258780, tzinfo=datetime.timezone.utc), 'version': '5.3'}, 'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': '35e86fd0-88c265b68084286ab459496a_146', 'msg_type': 'execute_request', 'username': 'shunlei', 'session': '35e86fd0-88c265b68084286ab459496a', 'date': datetime.datetime(2021, 6, 3, 15, 34, 55, 41504, tzinfo=tzutc()), 'version': '5.3'}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': 'get_pdb_settings', 'call_id': 'ef0b22b46a6645d0bf828d0adc954716', 'settings': {'blocking': True, 'timeout': None, 'send_reply': True}, 'comm_port': 35377, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.8 (default, Apr 13 2021, 19:58:26) \n[GCC 7.3.0]'}, 'comm_id': 'aaa5bc58c47f11eb87fce9f46bbe0ee4'}, 'metadata': {}}
[SpyderKernelApp] WARNING | WARNING: attempted to send message from fork
{'header': {'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'username': 'shunlei', 'session': '46f554ff-d257cc9e51819bf04bb2ce2d', 'date': datetime.datetime(2021, 6, 3, 15, 35, 7, 260384, tzinfo=datetime.timezone.utc), 'version': '5.3'}, 'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': '35e86fd0-88c265b68084286ab459496a_146', 'msg_type': 'execute_request', 'username': 'shunlei', 'session': '35e86fd0-88c265b68084286ab459496a', 'date': datetime.datetime(2021, 6, 3, 15, 34, 55, 41504, tzinfo=tzutc()), 'version': '5.3'}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': 'get_pdb_settings', 'call_id': 'b13d385286c94c7aa038e4f94b03191c', 'settings': {'blocking': True, 'timeout': None, 'send_reply': True}, 'comm_port': 35377, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.8 (default, Apr 13 2021, 19:58:26) \n[GCC 7.3.0]'}, 'comm_id': 'aaa5bc58c47f11eb87fce9f46bbe0ee4'}, 'metadata': {}}
[SpyderKernelApp] WARNING | WARNING: attempted to send message from fork
{'header': {'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'username': 'shunlei', 'session': '46f554ff-d257cc9e51819bf04bb2ce2d', 'date': datetime.datetime(2021, 6, 3, 15, 35, 7, 273153, tzinfo=datetime.timezone.utc), 'version': '5.3'}, 'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': '35e86fd0-88c265b68084286ab459496a_146', 'msg_type': 'execute_request', 'username': 'shunlei', 'session': '35e86fd0-88c265b68084286ab459496a', 'date': datetime.datetime(2021, 6, 3, 15, 34, 55, 41504, tzinfo=tzutc()), 'version': '5.3'}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': 'get_pdb_settings', 'call_id': 'be09f242383440ada361019b95b1fa30', 'settings': {'blocking': True, 'timeout': None, 'send_reply': True}, 'comm_port': 35377, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.8 (default, Apr 13 2021, 19:58:26) \n[GCC 7.3.0]'}, 'comm_id': 'aaa5bc58c47f11eb87fce9f46bbe0ee4'}, 'metadata': {}}
[SpyderKernelApp] WARNING | WARNING: attempted to send message from fork
{'header': {'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'username': 'shunlei', 'session': '46f554ff-d257cc9e51819bf04bb2ce2d', 'date': datetime.datetime(2021, 6, 3, 15, 35, 7, 273711, tzinfo=datetime.timezone.utc), 'version': '5.3'}, 'msg_id': '46f554ff-d257cc9e51819bf04bb2ce2d_68', 'msg_type': 'comm_msg', 'parent_header': {'msg_id': '35e86fd0-88c265b68084286ab459496a_146', 'msg_type': 'execute_request', 'username': 'shunlei', 'session': '35e86fd0-88c265b68084286ab459496a', 'date': datetime.datetime(2021, 6, 3, 15, 34, 55, 41504, tzinfo=tzutc()), 'version': '5.3'}, 'content': {'data': {'spyder_msg_type': 'remote_call', 'content': {'call_name': 'get_pdb_settings', 'call_id': '444be0b1102647acb4cf4b531c18d079', 'settings': {'blocking': True, 'timeout': None, 'send_reply': True}, 'comm_port': 35377, 'pickle_highest_protocol': 5}, 'pickle_protocol': 5, 'python_version': '3.8.8 (default, Apr 13 2021, 19:58:26) \n[GCC 7.3.0]'}, 'comm_id': 'aaa5bc58c47f11eb87fce9f46bbe0ee4'}, 'metadata': {}}

Pls help me! Thank you!

Best regards

**Comment by ccordoba12** [comment]
Hey @shunlei-li, thanks for reporting. How did you install Spyder?

**Comment by shunlei-li** [comment]
Hi @ccordoba12 , I did by pip install spyder.

**Comment by shunlei-li** [comment]
Hi Carlos,


I did by pip install spyder


Best regards

________________________________
发件人: Carlos Cordoba ***@***.***>
发送时间: 2021年6月3日 17:59:03
收件人: spyder-ide/spyder
抄送: Shunlei Li; Mention
主题: Re: [spyder-ide/spyder] SpyderKernelApp (#15773)


Hey @shunlei-li<https://github.com/shunlei-li>, thanks for reporting. How did you install Spyder?

―

**Comment by shunlei-li** [comment]
Hi @ccordoba12 , I intalled again by apt_get install spyder3. It works now. Thank you.
