### ISSUE TITLE
%run -d [filename] doesn't stop on breakpoints

### ISSUE THREAD

**Issue by battaglia01** [spyder-ide/spyder#15780]
### Issue Report Checklist

* [✅] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [✅] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [✅] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [✅] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [✅] Tried basic troubleshooting (if a bug/error)
    * [✅] Restarted Spyder
    * [✅] Reset preferences with ``spyder --reset``
    * [✅] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [✅] Tried the other applicable steps from the Troubleshooting Guide
* [✅] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After running a file with `%run -d [filename]`, Spyder skips breakpoints. It only seems to work if you type the much more verbose `debugfile([filename], post_mortem=True, current_namespace=True)`, which is annoying if you want to pass command line args.

### What steps reproduce the problem?

1. Set breakpoint
2. Type $run -d [filename]
3. Breakpoint is skipped

### What is the expected output? What do you see instead?

It just skips the breakpoints entirely; I would like it if it followed the breakpoints.

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Darwin 17.7.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by battaglia01** [comment]
I'll make my question even clearer - I just want to put things into some mode such that I can type function names into the console, and try different things, and have breakpoints activate when they are reached. Is there any way to do this? Can I somehow put the entire console into debug mode?

**Comment by ccordoba12** [comment]
I really doubt there's something we can do about it because `debugfile` is required to use our own debugger instead of regular `ipdb`.

@impact27, what do you think?

**Comment by battaglia01** [comment]
It would maybe be useful if there were just a different %magic that calls
`debugfile`, but uses the `%run -d filename arg1 arg2 arg3` syntax.
Something like `%sdbg` or something, for "spyder-debug" (and similarly
%srun). Is that something that's possible to do?

Mike

**Comment by impact27** [comment]
1 - Why do you want to use `%run -d` instead of the `debugfile`? It has the same functionality. For args use the `args` keyword. Also you can set all the options in the settings.
2 - if you want to debug a function from the debugger you need to have a recursive debugger. so from pdb instead of calling `f()`, use the debug command `debug f()`

**Comment by impact27** [comment]
Also `%run -d` does stop at the breakpoints. Do you have a reproducible example where it doesn't?

**Comment by battaglia01** [comment]
Breakpoints don't work with %run -d on my machine and the behavior is perfectly reproducible. If I am interpreting @ccordoba12 's prior comment correctly, that seems to be the standard behavior and has to do with which debugger is being used. If it's working on *your* machine with %run -d, I'd like to know how...

**Comment by impact27** [comment]
Sure:
 1- Create a file named "test.py" with a single `print(0)`
 2- in the console, run `%run -d test.py`
 3- Check that it did stop at the breakpoint as expected. 

@ccordoba12  could you check that this works as expected on your machine?

**Comment by battaglia01** [comment]
This only works because `%run -d [filename]` automatically sets a breakpoint on the first line regardless of what it is, or if you've set a breakpoint there or not. This doesn't work

```
print(0)
print(1) # breakpoint here
```

No matter what you've set, `%run -d [filename]` will automatically breakpoint before the `print(0)` just because it's line 1, and skip the breakpoint at `print(1)`.

**Comment by ccordoba12** [comment]
> @ccordoba12 could you check that this works as expected on your machine?

It seems @battaglia01 is right:

![imagen](https://user-images.githubusercontent.com/365293/121224589-5987ac00-c84e-11eb-8731-904bfce65d7e.png)

**Comment by ccordoba12** [comment]
For this to work we probably need to patch `%run -d` to get breakpoints from Spyder and set them in Pdb. However, that's what we already do in `debugfile`, so it's not something I'd like to put resources into.

Of course, if you'd like to give us a hand with that @battaglia01, you're more than welcome.

**Comment by battaglia01** [comment]
Sure, I can try - is there some way to programmatically get Spyder's list of breakpoints from the console?

**Comment by ccordoba12** [comment]
@impact27, could you point him in the right direction?

**Comment by impact27** [comment]
I tried to checkout spyder 5.0.0 and spyder-kernels 2.0.1 but `%run -d` still stops on the breakpoints, so I don't know what is going on. Also, I can't think of anything special that `debugfile` does to the debugger compared to `%run -d`. It mostly exists to make sure we call `runfile` from the debugger to use all the spyder options, but otherwise doesn't really do anything special to the debugger.

You can access the debugger breakpoints from the debugger with the `b` command.

If you want more advanced access:
```
shell = get_ipython()
pdb_obj = shell.kernel._pdb_obj
pdb_obj.breaks
```
This only works if the debugger is running, otherwise you will get `None` for `_pdb_obj`

**Comment by battaglia01** [comment]
Ok, but how do I get *Spyder*'s breakpoints from the command line (to put
into pdb to begin with), not the ones that pdb already has put into it?

**Comment by battaglia01** [comment]
Ah, sorry, the "more advanced access" method gave me what I was looking for
- thank you
Mike

**Comment by impact27** [comment]
Wait `b` and `pdb_obj.breaks` *should* return the exact same thing. The command line doesn't know anything about spyder. If you want to have access to spyder console, go to View > Panes > Internal console
From there you can get the breakpoints by:
```
from spyder.config.manager import CONF
CONF.get('run', 'breakpoints', {})
```

**Comment by battaglia01** [comment]
It looks like once the debugger has been run at least one time, `shell.kernel._pdb_obj` is no longer `None`.

It looks like that code you gave also runs from the regular console (e.g. internal console not required) which is good, because I will probably just need a general API for spyder stuff from the regular console... Is there some documentation for this?

**Comment by battaglia01** [comment]
OK to @ccordoba12 and @impact27 , I think I figured this out...

The **very first** time you call `%run -d _____`, it seems to set all the breakpoints correctly, as @impact27 said. But, once you call it **twice**, it doesn't work anymore.

This seems to be a larger problem with `%debug` in general, and I just wrote another issue in #15830. But, now that I'm doing it, I think it's all part of the same thing, which is that Spyder only sets the ipdb breakpoints correctly the first time you type either `debug` or `%run -d ___` or etc from the console, and then doesn't set them correctly afterward.

For instance, this is the file:

```
#!/usr/bin/env python3
# breakpointtest2.py

print("line 1!")
print("line 2 - breakpoint here!")
```

Now let's call `%run -d`:
```
>>> %run -d breakpointtest2.py
*** Blank or comment
*** Blank or comment
*** Blank or comment
*** Blank or comment
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> /Volumes/Shared/Projects/Python/breakpointtest2.py(4)<module>()
      1 #!/usr/bin/env python3
      2 # breakpointtest2.py
      3 
----> 4 print("line 1!")
      5 print("line 2 - breakpoint here!")
```
We're pausing at the first line. Before we continue, we will look at the breakpoints and see that we get

```
IPdb [1]: b
Num Type         Disp Enb   Where
1   breakpoint   keep yes   at /Volumes/Shared/Projects/Python/breakpointtest2.py:5
```

They are set correctly. Then if we continue:

```
IPdb [2]: c
line 1!
> /Volumes/Shared/Projects/Python/breakpointtest2.py(5)<module>()
      1 #!/usr/bin/env python3
      2 # breakpointtest2.py
      3 
      4 print("line 1!")
1---> 5 print("line 2 - breakpoint here!")
```
So it **does** successfully get the breakpoint the first time. Now if we run it again:


```
>>> %run -d breakpointtest2.py
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> /Volumes/Shared/Projects/Python/breakpointtest2.py(4)<module>()
      1 #!/usr/bin/env python3
      2 # breakpointtest2.py
      3 
----> 4 print("line 1!")
      5 print("line 2 - breakpoint here!")
# ^^ Pausing on first line, So far so good

IPdb [1]: b
# ^^ breakpoints empty?!

IPdb [2]: c
line 1!
line 2 - breakpoint here!
# Runs everything without breaking!
```

So this and the problem in #15830 seem to be equivalent; if you do any debugger thing from the console it seems to only set breakpoints correctly the first time and then doesn't afterward. (Perhaps these two issues should be merged now that this is clear...)

**Comment by impact27** [comment]
I can reproduce that. I will take a look when I have time. 

One important thing is that Spyder and the kernel might not run on the same machine, so `CONF.get('run', 'breakpoints', {})` has no garantee to return the right stuff hwen run from the ipython kernel. All the code for spyder pdb can be found here: https://github.com/spyder-ide/spyder-kernels/blob/master/spyder_kernels/customize/spyderpdb.py

The breakpoints are set in this file by:
```
pdb_settings = frontend_request().get_pdb_settings()
self.set_spyder_breakpoints(pdb_settings['breakpoints'])
```

**Comment by battaglia01** [comment]
Is that what sets Spyder's internal breakpoints? Where is the code in which
Spyder communicates those breakpoints to pdb/ipdb?

**Comment by ccordoba12** [comment]
> Is that what sets Spyder's internal breakpoints?

It's the second line of the code @impact27 posted in his last comment.

> Where is the code in which Spyder communicates those breakpoints to pdb/ipdb?

It's in the first line.

**Comment by impact27** [comment]
`self.starting` is not True when calling from the magic. PR https://github.com/spyder-ide/spyder-kernels/pull/300 fixes this

**Comment by impact27** [comment]
`preloop` is called each time you stop somewhere. So if I press continue and the debugger stops at a breakpoint, preloop is called again. In this case we don't want the breakpoint set by the user in the debugging session to be removed.

**Comment by arnaud-nt2i** [comment]
@ccordoba12 @impact27 debugger is still not stoping at break point after spyder 5.0.4 and spyder_kernels
