### ISSUE TITLE
Regarding spyder crash

### ISSUE THREAD

**Issue by Keerthana-R2001** [spyder-ide/spyder#15791]
### What steps will reproduce the problem?

When i try opening any python file in spyder, i encounter the error " python stopped working and program closes". Please help to solve the error

**Comment by ccordoba12** [comment]
Hey @Keerthana-R2001, thanks for reporting. Please remove your current Spyder installation and use our Windows installer instead, which you can find [here](https://github.com/spyder-ide/spyder/releases).

After doing that, please let us know if the error continues or it was fixed.

**Comment by Keerthana-R2001** [comment]
When I tried opening from the link which was mentioned, I got an message
stating " file or directory is corrupted and readable"

**Comment by ccordoba12** [comment]
Are you using Windows or macOS? Also, could you post a screenshot of that message?

**Comment by Keerthana-R2001** [comment]
I am using windows

**Comment by Keerthana-R2001** [comment]
i think the ss is available

**Comment by ccordoba12** [comment]
@Keerthana-R2001, you need to take the screenshot and drag and drop it directly here because you can't send it via email.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
