### ISSUE TITLE
kite detection does not properly fail

### ISSUE THREAD

**Issue by wesnm** [spyder-ide/spyder#15793]
In spyder/plugins/completion/providers/kite/utils/status.py:
```
def check_if_kite_installed():
    """Detect if kite is installed and return the installation path."""
    path = ''
    if os.name == 'nt':
        path = 'C:\\Program Files\\Kite\\kited.exe'
    elif sys.platform.startswith('linux'):
        path = osp.expanduser('~/.local/share/kite/kited')
    elif sys.platform == 'darwin':
        path = locate_kite_darwin()
    return osp.exists(osp.realpath(path)), path
```

This does not properly consider a platform (e.g. FreeBSD) not matching the supplied tests. In that case, realpath('') returns the current working directory, exists(...) will be true, and check_if_kite_installed() returns (True, ''). This leads to an exception and failure to launch the IDE:
```
  File "/home/morganw/.local/lib/python3.9/site-packages/spyder-6.0.0.dev0-py3.9
.egg/spyder/plugins/completion/plugin.py", line 283, in register
    self.start_all_providers()
  File "/home/morganw/.local/lib/python3.9/site-packages/spyder-6.0.0.dev0-py3.9
.egg/spyder/plugins/completion/plugin.py", line 776, in start_all_providers
    provider_info['instance'].start()
  File "/home/morganw/.local/lib/python3.9/site-packages/spyder-6.0.0.dev0-py3.9
.egg/spyder/plugins/completion/providers/kite/provider.py", line 108, in start
    self.kite_process = run_program(path)
  File "/home/morganw/.local/lib/python3.9/site-packages/spyder-6.0.0.dev0-py3.9
.egg/spyder/utils/programs.py", line 271, in run_program
    raise ProgramError("Program %s was not found" % program)
spyder.utils.programs.ProgramError: Program  was not found
```

Is osp.realpath() necessary? A broken symlink still passes the tests. The canonical path is not used, and osp.exists('') fails nicely.

**Comment by ccordoba12** [comment]
Hey @wesnm, thanks for reporting. You said

> This does not properly consider a platform (e.g. FreeBSD) not matching the supplied tests.

I'm very sorry but we currently don't support any of the BSDs nor is our plan to support them in the future. I want to be very clear about it because even if we accepted a patch for this, there are a lot of other places where we only check for Windows/Linux/macOS.

Thanks for understanding.

**Comment by wesnm** [comment]
Thanks for the explanation @ccordoba12. I'll submit a PR for the port maintainer instead.

I do, however, believe my point about realpath() being unnecessary to be correct, and it has the side effect of fixing the problem for unsupported platforms without adding any code to support those platforms.

Ciao!
