### ISSUE TITLE
The python kernel does not appear to be a conda environment

### ISSUE THREAD

**Issue by shailenderjain** [spyder-ide/spyder#15792]
I have installed Spyder 5.0.3 on Windows 10. I am trying to create a separate virtual environment with the following command 

              "conda create -n spyder-env spyder=4"

However, i am getting the following error 
              "ValueError: The python kernel does not appear to be a conda environment.  Please use ``%pip install`` instead."

**Comment by ccordoba12** [comment]
Hey @shailenderjain, that command is not meant to be run inside our consoles. If you want to use to other modules that don't come with our installer, you need to do the following:

1. Install [Miniconda](https://docs.conda.io/en/latest/miniconda.html).

2. Create a [conda environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands) after that with the packages you want to use and `spyder-kernels`. In your case you need to run these commands in a system terminal (i.e. `cmd.exe`):

        conda activate base
        conda create -n myenv spyder-kernels <foo>

3. Connect Spyder to that environment by following [these instructions](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
