### ISSUE TITLE
Enable auto high DPI scaling in spyder 5.0.0

### ISSUE THREAD

**Issue by ymcasky** [spyder-ide/spyder#15811]
This is from spyder 5.0.0 
I change the monitor and it show warning which is A monitor scale changed was detected.

Spyder suggest I should Enable auto high DPI scaling in Prererence > General > Interface
But I can't find General button in spyder 5.0.0.
![image](https://user-images.githubusercontent.com/6229000/121109455-31904c80-c83e-11eb-9990-746b8fe7a08c.png)

Where can I find Enable auto high DPI scaling in spyder 5.0.0?
Thanks!

**Comment by ccordoba12** [comment]
Hey @ymcasky, thanks for reporting. That message is outdated, but you can find the option it refers to in

    Application > Interface

Note: That message was updated in the meantime, but sadly Anaconda has not updated to our latest version (5.0.3), which has that fix.
