### ISSUE TITLE
Spyder randomly freeze and/or slow down but does not crash and recovers

### ISSUE THREAD

**Issue by mscheltienne** [spyder-ide/spyder#15815]
## Problem Description

Since a few weeks ago, I observed freeze, lags, slowdowns of spyder on 2 different computers:
- Windows with Python 3.9.5
- macOS Big Sur with Python 3.8.10

On both, Spyder is up to date: 5.0.3. PyQt 5.12.3.

The freeze lags manifest themselves by: 
- Input lag of several seconds (keystrokes in the editor): I can see the word/variable name I am typing getting typed letter by letter, in super slow motion.
- Copy/Paste in the editor sometimes taking several seconds during which I should not touch anything, or Spyder will crash.
- Scrolling gets not smooth and it becomes hard to scroll in a file.

### What steps reproduce the problem?

The only thing I changed since this problem appeared, is that I have been using the split windows editor mode to have 2 editors next to each other (split horizontally). The problem does seem to occur after long (a few hours) session of Spyder, and my best 'fix' for now is to restart Spyder when it starts lagging.

Both computers are powerful with 32 GB of RAM and good (if not excellent on the Windows PC) CPU/GPU, thus ruling out any resource sharing issue. 

Does anyone else experience the same kind of lags/freeze?

**Comment by ccordoba12** [comment]
Hey @mscheltienne, thanks for reporting. This problem is being tracked on issue #15631.

There are several workarounds there you can try to deal with this until we can properly fix it at the end of the year (the fix is not simple). Besides what's mentioned there, you can also try to disable folding in the menu

    Source > Show code folding

**Comment by ccordoba12** [comment]
I'm going to close this issue in favor of #15631 to have all reports about this consolidated in one place. Please post additional comments on that issue so that other people can benefit from them.

**Comment by mscheltienne** [comment]
@ccordoba12 Thanks, glad to know it is a known problem! I will turn off code folding.
