### ISSUE TITLE
PIP command's problem "you may need to restart the kernel to use updated packages" (on Spyder 4.0)

### ISSUE THREAD

**Issue by Paulparishelp** [spyder-ide/spyder#15813]
# Problem Description
I wanted to install OpenCV's module by entering this command : (> pip install opencv-python) through my spyder's console.
But it turned out that any pip's commands are not available so i decided to uninstall all anaconda's apps But after reinstall all these devices, it shows the same problem again.
I tried also to delete then reinstall Python.
But nothing works

### What steps reproduce the problem?

1. entering >pip
2. or entering any pip's commands >pip install [...]
3. 

### What is the expected output? What do you see instead?
I expect to install OpenCV's module then be able to use it commands.
But I can't do anything since the "pip" command doesn't work.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Note: you may need to restart the kernel to use updated packages.
'C:\Users\Paul' n'est pas reconnu en tant que commande interne
ou externe, un programme ex‚cutable ou un fichier de commandes.

```

(it's the same message for all pip's commands)

## Versions

* Spyder version: 4.0
* Python version: 3.8

* Operating System name/version: Windows 10 _ x64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)

```

thanks for helping

**Comment by ccordoba12** [comment]
Hey @Paulparishelp, thanks for reporting. You said

> I wanted to install OpenCV's module by entering this command : (> pip install opencv-python) through my spyder's console.

That's not the right way to do it. If you're using Anaconda (as it seems you are), please close Spyder, open the Anaconda Prompt and run there

    conda install opencv

**Comment by ccordoba12** [comment]
Please do that and let us know if it works for you.

**Comment by Paulparishelp** [comment]
Hello thanks for replying!
i tried this method but it put an error : 
"
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Paul CHU\anaconda3

  added / updated specs:
    - opencv


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libopencv-4.0.1            |       hbb9e17c_0        28.6 MB
    opencv-4.0.1               |   py38h2a7c758_0          22 KB
    py-opencv-4.0.1            |   py38he44ac1e_0         1.5 MB
    ------------------------------------------------------------
                                           Total:        30.1 MB

The following NEW packages will be INSTALLED:

  libopencv          pkgs/main/win-64::libopencv-4.0.1-hbb9e17c_0
  opencv             pkgs/main/win-64::opencv-4.0.1-py38h2a7c758_0
  py-opencv          pkgs/main/win-64::py-opencv-4.0.1-py38he44ac1e_0


Proceed ([y]/n)?


Downloading and Extracting Packages
opencv-4.0.1         | 22 KB     | ####################################################################################################################################################################### | 100%
libopencv-4.0.1      | 28.6 MB   | ####################################################################################################################################################################### | 100%
py-opencv-4.0.1      | 1.5 MB    | ####################################################################################################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done


(base) C:\Users\Paul>cocondapip
'cocondapip'  is not recognized as an internal or external command [...]

"

So It stopped after this error and therefore I can't finish the download 
But anyway, on my another laptop I can download opencv directly by taping : pip install opencv-python
so it installs all the devices needed on Spyder..
But I don't know why after the update, I can't do it anymore

**Comment by Paulparishelp** [comment]
And when I try to install openCV on Spyder it shows: 
"
conda install opencv

Note: you may need to restart the kernel to use updated packages.

EnvironmentLocationNotFound: Not a conda environment: C:\Users\Paul

"

Same with the command : 
"
pip install opencv-python
Note: you may need to restart the kernel to use updated packages.
'C:\Users\Paul' is not recognized as an internal or external command operable program or batch file
"

**Comment by ccordoba12** [comment]
> So It stopped after this error and therefore I can't finish the download

There are no errors. The installation worked as expected.

> But anyway, on my another laptop I can download opencv directly by taping : pip install opencv-python

If you're using Anaconda in your other laptop, that's wrong. Please stop doing that because it'll eventually break your installation.

> And when I try to install openCV on Spyder it shows:

As I told you, you don't need to do that in Spyder. In fact, it's the wrong way to install packages. Opening the Anaconda Prompt and installing them with conda (as you did) is the right way.

----

So, is OpenCV working for you or not? You were not clear about that.

**Comment by Paulparishelp** [comment]
> 
> 
> > So It stopped after this error and therefore I can't finish the download
> 
> There are no errors. The installation worked as expected.
> 
> > But anyway, on my another laptop I can download opencv directly by taping : pip install opencv-python
> 
> If you're using Anaconda in your other laptop, that's wrong. Please stop doing that because it'll eventually break your installation.
> 
> > And when I try to install openCV on Spyder it shows:
> 
> As I told you, you don't need to do that in Spyder. In fact, it's the wrong way to install packages. Opening the Anaconda Prompt and installing them with conda (as you did) is the right way.
> 
> So, is OpenCV working for you or not? You were not clear about that.

Nop I dont think it is working but thanks for the tip. I will be careful next time

**Comment by ccordoba12** [comment]
Closing because I don't think there's something else I can help with here.
