### ISSUE TITLE
Saving an empty file crash spyder.

### ISSUE THREAD

**Issue by mscheltienne** [spyder-ide/spyder#15822]
## Problem Description

By default, a Spyder file starts with:

```
# -*- coding: utf-8 -*-
"""
Created on Wed Jun  9 13:32:39 2021

@author: Mathieu
"""
```

If you remove those lines and try to save an empty file, regardless of the location/filename, Spyder stops responding and ultimately crash. 
I do have a couple of editor options turn on which might be related:
- (1) Editor > Source Code > Automatically remove trailing spaces
- (2) Editor > Source Code > Insert a new line at the end if one does not exist
- (3) Editor > Source Code > Trim all new lines after the final one

I tried turning them off one by one; and of course; it was the last one which resumed correct behavior and saving of empty files without a crash. Thus the combos:
- (1) + (2) does work; 
- (1) + (2) + (3) does not work;
- (3) by itself does not work.

Install information:
* Spyder version: 5.0.3
* Python version: 3.9.5
* PyQt version: 5.12.3
* Operating System name/version: Windows

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.23.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  56.2.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  22.0.3 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @mscheltienne thanks you for the feedback and the detailed description! I was able to reproduce this, we will work in a fix for this in a future release :+1:

**Comment by ccordoba12** [comment]
> (1) + (2) + (3) does not work;
(3) by itself does not work.

It seems we're not considering the case in which the file is empty when trimming new lines. Thanks for noticing it @mscheltienne!

**Comment by mscheltienne** [comment]
It looks like it has been fixed in the latest release.
