### ISSUE TITLE
Inconsistent behavior when debugging with `debug` at the command line, breakpoints only set correctly the first time debug is called

### ISSUE THREAD

**Issue by battaglia01** [spyder-ide/spyder#15830]
### Issue Report Checklist

* [:)] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [:)] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [:)] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [:)] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [:)] Tried basic troubleshooting (if a bug/error)
    * [:)] Restarted Spyder
    * [:)] Reset preferences with ``spyder --reset``
    * [:)] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [:)] Tried the other applicable steps from the Troubleshooting Guide
* [:)] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I initially started writing this as part of #15780, but seemed to be much broader so I made a new issue for it.

Suppose we have this file

```
#!/usr/bin/env python3
# breakpointtest.py
def my_func():
    print("line 1 in func")
    print("line 2 in func - breakpoint here!") # <-- breakpoint set in spyder
```

Now I open a new console, and type
```
>>> import breakpointtest

>>> debug breakpointtest.my_func()
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(1)<module>()
```

It auto-breaks on the first line which is ok so far. Even before typing `c`, I can type `b` to show that the breakpoints have been correctly imported from spyder:

```
IPdb [1]: b
Num Type         Disp Enb   Where
1   breakpoint   keep yes   at /Volumes/Shared/Projects/Python/breakpointtest.py:6
```

If I then type `c`, then it successfully breaks correctly at the breakpoint:

```
IPdb [2]: c
line 1 in func
> /Volumes/Shared/Projects/Python/breakpointtest.py(6)my_func()
      2 # breakpointtest.py
      3 
      4 def my_func():
      5     print("line 1 in func")
1---> 6     print("line 2 in func - breakpoint here!") # <-- breakpoint set in spyder

IPdb [3]: c
line 2 in func - breakpoint here!
```

So all is well.

**However**, if I then immediately debug the same function **again**, it no longer works:

```
>>> debug breakpointtest.my_func()
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(1)<module>()
# ^^ Breaking on first line again, ok...

IPdb [1]: b
# ^^ No breakpoints set?!

IPdb [2]: c
line 1 in func
line 2 in func - breakpoint here!
# ^^ Function runs without any breakpoints
```

**I also get the same problem if I call debug for *a different* function from here on out; breakpoints are not set; `b` is empty**

So it seems as though, for whatever reason, Spyder only sets the breakpoints correctly the very first time that `debug` is run. Is there some way to make this work?

## Versions

* Spyder version: 5.0.0
* Python version: 3.9.4
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Darwin 17.7.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.1 (OK)
pylint >=1.0                  :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.0.3 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  3.5.3 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by battaglia01** [comment]
FWIW, it does seem like it still does work if I make a new file and call `debugfile` on that instead. So I guess one workaround would be to create a magic which automatically makes a new file and calls `debug` on it. But in general, I think the expected (and intended?) behavior is that if you call something with `%debug _____`, breakpoints are set correctly.

**Comment by battaglia01** [comment]
This also happens if you try with `%run -d ____`, which I'd previously talked about in #15780. I hadn't realized, in that thread, that `%run -d ____` *does* set breakpoints correctly on the very first run and then breaks thereafter, which perhaps explains some of the variance in user behavior... So these two bugs are likely part of the same thing, which has to do with spyder not setting ipdb breakpoints correctly after the first time some debugging thing is done from the console.

**Comment by ccordoba12** [comment]
I'm going to close this one in favor of #15780 because all talk related to this problem has happened there.

@battaglia01, feel free to rewrite that issue's title and more comments there as you consider necessary.
