### ISSUE TITLE
Pop-up window "New Spyder version" blocks loading the main window

### ISSUE THREAD

**Issue by thluDK** [spyder-ide/spyder#15839]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Pop-up window "New Spyder version" is not showing in taskbar. Spyder is easily 'lost' behind other windows while waiting to press OK to continue loading of main window.

### What steps reproduce the problem?

1. Use old version of Spyder (5.0.1)
2. Open Spyder
3. Pop-up "Spyder 5.0.3 is available!" is showing

### What is the expected output? What do you see instead?
Spyder continues to load while pop-up is showing.

## Versions

* Spyder version: 5.0.1
* Python version: Python 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

**Comment by juanis2112** [comment]
Hi @thluDK thanks for reporting. I'm not quite sure we can fix this behaviour. @ccordoba12 any ideas?

**Comment by ccordoba12** [comment]
@thluDK, thanks a lot bringing this up to our attention! We'll fix this usability issue in our next version (5.1.0), to be released at the end of July, by making that pop-up to be shown after the window is already visible.

If you have time, please report back if that works for you after that.
