### ISSUE TITLE
JIRA access getting SSLError Certificate Verify Failed

### ISSUE THREAD

**Issue by krishtej23** [spyder-ide/spyder#15846]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Trying to access JIRA server but unable to get in. Receiving SSL: CERTIFICATE_VERIFY_FAILED. If the same commands are run in Win Powershell, everything works fine but getting error in Spyder. In the initial stages, even in Powershell the same error popped up but it was resolved when "python-certifi-win32" is installed but the same solution is NOT helping in spyder.

### What steps reproduce the problem?
```from jira import JIRA

server =  'https://jira.company.com:444/'
usrnme = "id"
pwd = "password"
jira_instance = JIRA(server = server, basic_auth=(usrnme, pwd))
```
1. Code above ran in powershell without error
2. Same code throws error in Spyder

### What is the expected output? What do you see instead?
Expected output is a jira session object in "jira_instance" instead receiving SSL Certificate Verify Failed

### Paste Traceback/Error Below (if applicable)

```python-traceback

runfile('C:/Users/desktop/JiraConnection.py', wdir='C:/Users/desktop')
WARNING:root:HTTPSConnectionPool(host='jira.company.com', port=444): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)'))) while doing GET https://jira.company.com:444/rest/api/2/serverInfo [{'params': None, 'headers': {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type': 'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='jira.company.com', port=444): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)')))] errno:None on GET https://jira.company.com:444/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}
{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET https://jira.company.com:444/rest/api/2/serverInfo, will retry [1/3] in 12.00957322719334s. Err: HTTPSConnectionPool(host='jira.company.com', port=444): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)')))
Traceback (most recent call last):

  File "C:\Users\desktop\JiraConnection.py", line 6, in <module>
    jira_instance = JIRA(server = server, basic_auth=(usrnme, pwd))

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\client.py", line 506, in __init__
    si = self.server_info()

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\client.py", line 2551, in server_info
    j = self._get_json("serverInfo")

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\client.py", line 3139, in _get_json
    r = self._session.get(url, params=params)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\resilientsession.py", line 172, in get
    return self.__verb("GET", url, **kwargs)

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\resilientsession.py", line 156, in __verb
    response_or_exception, url, verb.upper(), retry_number

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\resilientsession.py", line 120, in __recoverable
    logging.debug("response.headers: %s", response.headers)

AttributeError: 'SSLError' object has no attribute 'headers'

```

## Versions

* Spyder version: 5.0.0 64-bit
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Win 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.2.1 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  0.6.1 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  17.0.0 (OK)
nbconvert >=4.0               :  5.4.0 (OK)
numpydoc >=0.6.0              :  0.8.0 (OK)
paramiko >=2.4.0              :  2.4.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.4.8 (OK)
pygments >=2.0                :  2.3.1 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.2 (OK)
qtconsole >=5.0.3             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.5.2 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  1.8.2 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  17.1.2 (OK)

# Optional:
cython >=0.21                 :  0.29.2 (OK)
matplotlib >=2.0.0            :  3.0.2 (OK)
numpy >=1.7                   :  1.15.4 (OK)
pandas >=1.1.1                :  0.23.4 (NOK)
scipy >=0.17.0                :  1.1.0 (OK)
sympy >=0.7.3                 :  1.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @krishtej23, thanks for reporting. This looks like a problem with your code and not with Spyder.

Are you able to run your code outside Spyder? I mean, for instance, by opening the Anaconda Prompt and running the following command there

    python C:\Users\desktop\JiraConnection.py

Please do that and let us if the error persists or not.

**Comment by krishtej23** [comment]
Hey Carlos.

Yes, I checked in Anaconda Prompt now and it worked smoothly and as
expected.

*With regards,*
*Krishna Teja.*

**Comment by ccordoba12** [comment]
So could you test in Spyder again? Just to be sure that it works (or not) for you there too.

**Comment by krishtej23** [comment]
No luck, same error:

WARNING:root:HTTPSConnectionPool(host='jira.company.com', port=444): Max
retries exceeded with url: /rest/api/2/serverInfo (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain
(_ssl.c:1051)'))) while doing GET
https://jira.company.com:444/rest/api/2/serverInfo [{'params': None,
'headers': {'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding':
'gzip, deflate', 'Accept': 'application/json,*.*;q=0.9', 'Connection':
'keep-alive', 'Cache-Control': 'no-cache', 'Content-Type':
'application/json', 'X-Atlassian-Token': 'no-check'}}]
WARNING:root:Got ConnectionError [HTTPSConnectionPool(host='jira.company.com',
port=444): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain
(_ssl.c:1051)')))] errno:None on GET
https://jira.company.com:444/rest/api/2/serverInfo
{'response': None, 'request': <PreparedRequest [GET]>}
{'response': None, 'request': <PreparedRequest [GET]>}
WARNING:root:Got recoverable error from GET
https://jira.company.com:444/rest/api/2/serverInfo, will retry [1/3] in
3.399093183865971s. Err: HTTPSConnectionPool(host='jira.company.com',
port=444): Max retries exceeded with url: /rest/api/2/serverInfo (Caused by
SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED]
certificate verify failed: self signed certificate in certificate chain
(_ssl.c:1051)')))
Traceback (most recent call last):

  File "C:\Users\desktop\JiraConnection.py", line 6, in <module>
    jira_instance = JIRA(server = server, basic_auth=(usrnme, pwd))

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\client.py", line
506, in __init__
    si = self.server_info()

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\client.py", line
2551, in server_info
    j = self._get_json("serverInfo")

  File "C:\ProgramData\Anaconda3\lib\site-packages\jira\client.py", line
3139, in _get_json
    r = self._session.get(url, params=params)

  File
"C:\ProgramData\Anaconda3\lib\site-packages\jira\resilientsession.py", line
172, in get
    return self.__verb("GET", url, **kwargs)

  File
"C:\ProgramData\Anaconda3\lib\site-packages\jira\resilientsession.py", line
156, in __verb
    response_or_exception, url, verb.upper(), retry_number

  File
"C:\ProgramData\Anaconda3\lib\site-packages\jira\resilientsession.py", line
120, in __recoverable
    logging.debug("response.headers: %s", response.headers)

AttributeError: 'SSLError' object has no attribute 'headers'

*With regards,*
*Krishna Teja.*

**Comment by krishtej23** [comment]
Carlos,

I rechecked the Anaconda prompt and my mistake is that I ran the file as "
*py *C:\Users\desktop\JiraConnection.py" instead of "*python *
C:\Users\desktop\JiraConnection.py". I apologize. So with "py" in anaconda
prompt code is working fine but with "python" it is not.
I get this in python of anaconda prompt:
>>> import sys
>>> print(sys.prefix)
C:\ProgramData\Anaconda3

I get this in py of win powershell:
>>> import sys
>>> print(sys.prefix)
C:\Users\krish\AppData\Local\Programs\Python\Python39

*With regards,*
*Krishna Teja.*

**Comment by krishtej23** [comment]
Carlos,
So similar to "python-certifi-win32" installation, I used "conda install -c conda-forge python-certifi-win32" from https://anaconda.org/conda-forge/python-certifi-win32 and there is NO error.
Both Spyder and Anaconda Prompt had no issues.

**Comment by ccordoba12** [comment]
Great! I'm really glad you were finally able to solve this problem.

**Comment by krishtej23** [comment]
Carlos,

Is there a way or may be guide me in packaging this python-certifi-win32 in an executable created by PyInstaller? I created an executable using PyInstaller and when I run it, I get the same SSLError again. Thanks.

**Comment by ccordoba12** [comment]
Sorry, I don't know about that.
