### ISSUE TITLE
Preferences option not showing up on Spyder in Big Sur. 

### ISSUE THREAD

**Issue by TJTapajyoti** [spyder-ide/spyder#15845]
## Problem Description
When clicking on spyder on the  menubar, preferences does not show up. Pressing Command + , does not do anything. 

## Versions

* Spyder version: 5.0.3
* Python version: 3.8.8
* Operating System name/version: Big Sur

**Comment by ccordoba12** [comment]
Hey @TJTapajyoti, thanks for reporting. This is a known issue with Spyder 5 and we still don't know how to fix it (see issue #14917).

For now the only solution is to click several times in the menubar and then Spyder until Preferences appear in the right place. Sorry for the inconvenience.

**Comment by ccordoba12** [comment]
I'm going to close this one in favor of #14917.
