### ISSUE TITLE
Paramiko no seen by spyder

### ISSUE THREAD

**Issue by CLiNTPELiX** [spyder-ide/spyder#15840]
### What steps will reproduce the problem?

Using Mininconda and setted my own environment, I can see Paramiko 2.7.2 installed but when I start spyder, a box appears with Paramiko missing dependency

**Comment by juanis2112** [comment]
Hi @CLiNTPELiX It is possible that the environment in which you installed Paramiko isn't the same in which you are running spyder. Can you let me know which was your method of installation?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
