### ISSUE TITLE
Spyder 5 fail to detect Rtree

### ISSUE THREAD

**Issue by algent-al** [spyder-ide/spyder#15849]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
![rtree](https://user-images.githubusercontent.com/46356616/121779772-a85e7a00-cb9d-11eb-9b74-ed92dae5da56.png)

`python-rtree` is currently installed
```
$ pip3 show rtree
Name: Rtree
Version: 0.9.7
Summary: R-Tree spatial index for Python GIS
Home-page: https://github.com/Toblerity/rtree
Author: Sean Gillies
Author-email: sean.gillies@gmail.com
License: MIT
Location: /usr/lib64/python3.7/site-packages
Requires: 
Required-by: spyder
```

### What steps reproduce the problem?

1. Run `spyder` 

## Versions

* Spyder version: 5.0.3 and 5.0.4 (The issue present since 5.0.3)
* Python version: 3.7.10
* Qt version: 5.15.3
* PyQt version: 5.15.2
* Operating System name/version: Solus Budgie 4.2

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  22.2.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.8.0 (OK)
pylint >=1.0                  :  2.6.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  None (NOK)
setuptools >=39.0.0           :  47.1.0 (OK)
sphinx >=0.6.6                :  3.5.1 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  0.10.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  19.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.16.6 (OK)
pandas >=1.1.1                :  1.2.2 (OK)
scipy >=0.17.0                :  1.6.0 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

My workaround for now is to edit `spyder/dependencies.py`
`RTREE_REQVER = '>=0.9.7'` to `RTREE_REQVER = None`

**Comment by ccordoba12** [comment]
Hey @algent-al, thanks for reporting. Please report this problem to your Linux distro maintainers. Unfortunately, we can't give support for Spyder installed through your package manager because Linux maintainers make several changes to our code to make it work with the latest versions of everything.

My only advice is to try to install `libspatialindex` (which is the main Rtree dependency). That could fix your problem.

**Comment by algent-al** [comment]
You are right. Installing `libspatialindex` fixed the issue.
