### ISSUE TITLE
torch tensor raising spyder issues

### ISSUE THREAD

**Issue by tarunbhavnani** [spyder-ide/spyder#15858]
### What steps will reproduce the problem?

import torch
from transformers import BertTokenizer, BertModel
model_path = r'C:\Users\ELECTROBOT\Desktop\bert_base_uncased'
tokenizer= BertTokenizer.from_pretrained(model_path)

#tokenizer.encode_plus(train.excerpt.iloc[1])

#text = ["this is a bert model tutorial", "we will fine-tune a bert model"]
#tokenizer.batch_encode_plus(text, padding=True)

bert_model= BertModel.from_pretrained(model_path)
#create input for Bert model

from torch.utils.data import DataLoader, TensorDataset

#lets check ofr max length

#np.mean([len(i) for i in train.excerpt])

train_tokens= tokenizer.batch_encode_plus(train['excerpt'].tolist(),
                                          max_length=1000,
                                          pad_to_max_length=True,
                                          truncation=True)

train_seq= torch.tensor(train_tokens['input_ids'])

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "c:\users\electrobot\anaconda3\envs\tarun37\lib\site-packages\spyder_kernels\comms\commbase.py", line 315, in _comm_message
    encoding='latin-1')
ModuleNotFoundError: No module named 'torch'
```

## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.0 (NOK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.8.2 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.4.0 (OK)
qdarkstyle >=2.8                :  3.0.2 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=4.7.7               :  5.0.1 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  57.0.0 (OK)
sphinx >=0.6.6                  :  4.0.2 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  2.1.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.22 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.1.3 (OK)
scipy >=0.17.0                  :  1.5.3 (OK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by steff456** [comment]
Hi @tarunbhavnani,

It seems you don't have Pytorch installed in your environment. Please add it to your environment to avoid the error and use the library. If you are using one of our installers please create a new environment with all the dependencies you need, and then go to `Preferences > Python interpreter > Python interpreter > Use the following Python interpreter` and search for your environment in the combobox or type the path to your new environment.

Thanks for reporting!
