### ISSUE TITLE
Unexpected indent while importing packages

### ISSUE THREAD

**Issue by S2Sofficial** [spyder-ide/spyder#15856]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. While importing packages like numpy, pandas, matplotlib 

### Paste Traceback/Error Below (if applicable)

```python-traceback

ImportError: cannot import name 'TYPE_CHECKING' from 'typing' (/usr/local/lib/python3.7/dist-packages/numpy/typing/__init__.py)



```

## Versions

* Spyder version: 
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @S2Sofficial, thanks for reporting. This is not an error with Spyder but Numpy, so we can't help you here.

The only recommendation we can give you is use Anaconda for your user instead of `sudo pip`, which is what you seem to used to install Numpy.
