### ISSUE TITLE
Pyplot interactive plots blocking full screen

### ISSUE THREAD

**Issue by shadoxxhd** [spyder-ide/spyder#15860]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [n/a] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [n/a] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [no] Reset preferences with ``spyder --reset``
    * [n/a] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Reinstalled latest version of [Spyder](https://github.com/spyder-ide/spyder/)
    * [n/a] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When using the qt5 backend, plots open in fullscreen with no way to minimize/drag around/change window size _when using high dpi settings and having the taskbar at the top of the screen_.

### What steps reproduce the problem?

1.  Enable qt5 backend (IPython Console -> graphics -> graphics backend; alternatively using %matplotlib qt5)
2.  Try to plot something at high dpi (eg. plt.figure(dpi=500) + plt.plot(range(3)))
3. have your taskbar at the top of the screen for maximum annoyance (can't resize/close window normally)

### What is the expected output? What do you see instead?

The plot should appear inside a window, instead it blocks the whole screen and can only be closed from the taskbar/task manager.

The concrete problem is that the window is a) larger than the screen and b) its title bar appears behind the taskbar, making interacting with the window impossible. Limiting the size of the window (to screen resolution, or a configurable max size) and preventing it from appearing at y=0 would prevent this problematic behavior.

## Versions

* Spyder version: 5.0.2, 5.0.4
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.24.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by impact27** [comment]
I think that is a matplotlib issue as we don't control the matplotlib qt5 window directly. Cuold you check if you have the same issue with `jupyter qtconsole`?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
