### ISSUE TITLE
kivy gui can't close

### ISSUE THREAD

**Issue by hengqha** [spyder-ide/spyder#15862]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
when i try to close the gui founding with kivy,the windows will stop working

**Comment by steff456** [comment]
Hi @hengqha,

Can you please upload a gif showing the behavior you are having for us to try to reproduce it on our end? Also please give us the Spyder  and Python version. 

Thanks for reporting!

**Comment by hengqha** [comment]
![wrongInformation](https://user-images.githubusercontent.com/62489148/122076248-4caa2000-ce2d-11eb-888a-bf095e037460.gif)
Thanks for your reply！ Please refer to the GIF for the error,My Spyder version is 5.0.3,Python version is 3.7.
Thanks again!

**Comment by steff456** [comment]
Can you share with me the code that your are running? Also, can you paste the information that appears when you do `show details` in the error dialog?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by hengqha** [comment]
Hi!
       Firstly,Thanks for your reply! I have upload the gif,my spyder version is 5.0.3,python version is 3. 7.
       Thanks again!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Stephannie Jimenez ***@***.***>
发送时间: 2021年6月15日 0:57
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [spyder-ide/spyder] kivy gui can't close (#15862)


Hi @hengqha<https://github.com/hengqha>,

Can you please upload a gif showing the behavior you are having for us to try to reproduce it on our end? Also please give us the Spyder and Python version.

Thanks for reporting!

―
