### ISSUE TITLE
Possible Spyder Bug - Bogus Path elements created by Anaconda that do not exist

### ISSUE THREAD

**Issue by IqbalHamid** [spyder-ide/spyder#15874]
### What steps will reproduce the problem?

I just wanted to report what may be a possible bug.  I was inspecting my %PATH% variable through anaconda command prompt and repeatedly get paths that do not exist on my computer.  The suffix 'in' is being appended to 

C:\ProgramData\Anaconda 

to give:
C:\ProgramData\Anacondain

This is also happening to other path elements.  See below

C:\ProgramData\Anaconda3
C:\ProgramData\Anaconda3\Library\mingw-w6in
C:\ProgramData\Anaconda3\Library\usin
C:\ProgramData\Anaconda3\Librarin
C:\ProgramData\Anaconda3\Scripts
C:\ProgramData\Anacondain
C:\ProgramData\Anaconda3\condabin

This is also happeneing in my anaconda environments so for example I am getting the following appearing in the %PATH% environment variable for my GameDev environment:

C:\Users\Iqbal\.conda\envs\GameDev
C:\Users\Iqbal\.conda\envs\GameDev\Library\mingw-w6in
C:\Users\Iqbal\.conda\envs\GameDev\Library\usin
C:\Users\Iqbal\.conda\envs\GameDev\Librarin
C:\Users\Iqbal\.conda\envs\GameDev\Scripts
C:\Users\Iqbal\.conda\envs\GameDein
C:\ProgramData\Anaconda3\condabin

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by steff456** [comment]
Hi @IqbalHamid,

Can you please upload a screenshot on what is appearing for you in the path manager of Spyder? Did you modified something in there before?

**Comment by IqbalHamid** [comment]
Hi Stephannie

 

To be honest, I subsequently realised this is more of an Anaconda bug so have reported it to them also.  However, as Spyder is intrinsically linked to Anaconda this may interest the Spyder team also.  Maybe you can help but if not, that’s okay because despite this anomaly, thigs so far appear to be running fine.  However, I have only recently downloaded Anaconda with Spyder, so have not been able to fully put the installation to a test.

 

Anyway, to give you what you asked for, here is the screenshot.  I have not modified any of the settings here.

 



 

Kind Regards

Iqbal Hamid

**Comment by steff456** [comment]
Hi @IqbalHamid,

Sadly if you reply by email I will not be able to see the images attached. I'm glad that you noticed that it seems an error on Anaconda's side and not ours, please try to upload the image directly in Github just to double check if there's something that we can do.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
