### ISSUE TITLE
Standalone install missing aiohttp module

### ISSUE THREAD

**Issue by rtmcg** [spyder-ide/spyder#15879]
### What steps will reproduce the problem?

1. Start Spyder.
2. Type 'help("modules")' into the IPython console.
3. This error appears:

Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.24.1 -- An enhanced Interactive Python.

In [1]: help("modules")

Please wait a moment while I gather a list of all available modules...

C:\Users\rturne11\AppData\Local\Programs\Spyder\pkgs\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
aiohttp dependency is not installed: No module named 'aiohttp'. Please re-install black with the '[d]' extra install to obtain aiohttp_cors: `pip install black[d]`
An exception has occurred, use %tb to see the full traceback.

Traceback (most recent call last):

  File "C:\Users\rturne11\AppData\Local\Programs\Spyder\pkgs\blackd\__init__.py", line 11, in <module>
    from aiohttp import web

ModuleNotFoundError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

SystemExit: -1

Warning
It seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.
 C:\Users\rturne11\AppData\Local\Programs\Spyder\pkgs\IPython\core\interactiveshell.py:3449: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [2]: %tb
Traceback (most recent call last):

  File "C:\Users\rturne11\AppData\Local\Programs\Spyder\pkgs\blackd\__init__.py", line 11, in <module>
    from aiohttp import web

ModuleNotFoundError: No module named 'aiohttp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-1-672d1fb75e1b>", line 1, in <module>
    help("modules")

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\_sitebuiltins.py", line 103, in __call__

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1892, in __call__

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 1939, in help

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 2091, in listmodules

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pydoc.py", line 2120, in run

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\pkgutil.py", line 92, in walk_packages

  File "C:\Users\rturne11\AppData\Local\Programs\Spyder\pkgs\blackd\__init__.py", line 20, in <module>
    sys.exit(-1)

SystemExit: -1

In [3]:

**Comment by rtmcg** [comment]
I wanted to see the list of installed modules that come with the Spyder stand-alone installer.
This raises a question: How do we update/maintain the modules that are installed with Spyder?

**Comment by ccordoba12** [comment]
Hey @rtmcg, thanks for reporting. This seems to be a problem with `help(modules)` more than with the installer itself. According to this part of your error above

> aiohttp dependency is not installed: No module named 'aiohttp'. Please re-install black with the '[d]' extra install to obtain aiohttp_cors: pip install black[d]

an extra functionality of the Black package requires `aiohttp` and we don't provide it in our installers because we don't need it in Spyder. However, `help(modules)` tries to import it and fails.

You also said:

> I wanted to see the list of installed modules that come with the Spyder stand-alone installer.

The list of installed modules is in the `pkgs` directory of the installer. In your case that is

    C:\Users\rturne11\AppData\Local\Programs\Spyder\pkgs

> This raises a question: How do we update/maintain the modules that are installed with Spyder?

There's no way to do that and we don't plan to support it. The installers are completely self-contained and can't be modified to add other packages or update the current ones.

If you want to use packages that don't come with out installers, you need to follow the procedure described in [this FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) in our docs.

**Comment by ccordoba12** [comment]
Please let us know if you need other clarifications or we can close this issue.

**Comment by rtmcg** [comment]
Thank you for your reply, @ccordoba12. I guess there's no real **issue** here except my own confusion. Keep up the great work!

**Comment by ccordoba12** [comment]
Thanks @rtmcg! Will do.
