### ISSUE TITLE
Pylint package not found with the Syder 5.0.4 Mac installer

### ISSUE THREAD

**Issue by ColedanosTX** [spyder-ide/spyder#15885]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Step-1 Python file (.py) already opened in the Editor pane
Step-2 Cliked on "Source" on the Menu bar 
Step-3 Slected "Run Code Analysis"

Error Message: "/Application/Spyder.app/Contents/MacOS/ 
python: No Module named
plynt.__main__; 'plynt' is a package and cannot be directly executed "

**Comment by ccordoba12** [comment]
Hey @ColedanosTX, thanks for reporting. We'll try to fix this in our next release.

@mrclary, could you take a look at this one?

**Comment by ColedanosTX** [comment]
> Hey @ColedanosTX, thanks for reporting. We'll try to fix this in our next release.
> 
> @mrclary, could you take a look at this one?

**Comment by ccordoba12** [comment]
This hasn't been solved, so we need to keep it open to not forget fixing it later.

**Comment by mrclary** [comment]
I can confirm that this issue manifests on 5.0.3 (and possibly earlier). I'll look into it.

**Comment by ccordoba12** [comment]
@ColedanosTX, the fix for this will be included in our 5.1.0 version, to be released at the end of July.

**Comment by ColedanosTX** [comment]
Many thanks for the attention brought to this topic and for the prompt
action. I am impressed how fast you guys tackle this issue.

I also want to thank you all for you actions to improve a step further the
Spyder IDE functionalities and features and to a release very soon a new
version.

With my sincere considerations to all of you,
Thomas Coledanos

**Comment by ccordoba12** [comment]
@ColedanosTX, thanks for your kind words!
