### ISSUE TITLE
An error occured while starting the kernel

### ISSUE THREAD

**Issue by bastieffzeh** [spyder-ide/spyder#15883]
## Description
Starting the kernel when using Spyder via Anaconda Navigator does not work. Numerous forums have been searched, updates installed. The source of the error is unknown.

### What steps will reproduce the problem?

1. uninstall anaconda
2. reinstall anaconda
3. update conda and spyder

### Traceback
```python-traceback
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1497, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\site‑packages\jupyter_client\manager.py", line 337, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\site‑packages\jupyter_client\manager.py", line 286, in pre_start_kernel
self.write_connection_file()
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\site‑packages\jupyter_client\connect.py", line 466, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\site‑packages\jupyter_client\connect.py", line 136, in write_connection_file
with secure_write(fname) as f:
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\contextlib.py", line 117, in __enter__
return next(self.gen)
File "C:\ProgramData\Anaconda3\envs\spyder‑env\lib\site‑packages\jupyter_core\paths.py", line 458, in secure_write
fd = os.open(fname, open_flag, 0o0600)
FileNotFoundError: [Errno 2] No such file or directory: '\\\\nas.tu‑clausthal.de\\win‑home$\\bkl15\\rzconfig\\Anwendungsdaten\\jupyter\\runtime\\kernel‑ecbcb87c98af.json'

## Versions

* Spyder version: 5.0.3 
* Python version: 3.9.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @bastieffzeh thanks for the feedback, that the kernel started you on previous versions? Also, seems like the connection file that you are trying to use is inside network drive?

Any other information is greatly appreciated :)

**Comment by bastieffzeh** [comment]
@dalthviz even with previous versions Spyder did not work. Other users on the same computer have no problems. The file (don't know their background) is supposed to be on a network drive, but is not there.

**Comment by dalthviz** [comment]
@bastieffzeh maybe then is an issue regarding your account accessing the file and the network drive. Are you sure you have access with the account you are running Spyder to the network drive and the file for the connection that should be in that network drive?

If your Windows account doesn't have access to the network drive then there is not much we can do sorry :/ 

Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
