### ISSUE TITLE
Questions about multiple panels in the same plugin (third-party plugin)

### ISSUE THREAD

**Issue by dan123456-eng** [spyder-ide/spyder#15894]
Observation:
Complements with the configuration of widgets in panels
#15757

Hello, how are you?

We have this unique app with 4 panels.

For example, I can place two panels in different places, not within the same DockWidgets, so that they open and close independently.

Without having to set entry_points for each panel.

Similar to Files and Variable Explorer.

![Files](https://user-images.githubusercontent.com/61120620/121926984-ee8a1980-cd14-11eb-9aa8-d74689537d6b.png)
![vexpl](https://user-images.githubusercontent.com/61120620/121926988-efbb4680-cd14-11eb-8840-ebcc6ae764e3.png)

If possible, what is the best way?

**Comment by ccordoba12** [comment]
Hey @dan123456-eng, thanks for reporting. You said

> We have this unique app with 4 panels.
>
> For example, I can place two panels in different places, not within the same DockWidgets, so that they open and close independently.

So you basically have two panes, right?

> Without having to set entry_points for each panel.

If you have two panes, you have declare an entry_point for each, there's no workaround for that. But you can do it in the same package though, as we do with our own panes.

> Similar to Files and Variable Explorer.

Those are independent panes but each one has its own entry_point.

**Comment by ccordoba12** [comment]
Is your code open source? If it's hosted here or in another website, we could take a look at it and give you a hand with the migration to Spyder 5.

**Comment by dan123456-eng** [comment]
> Ei @ dan123456-eng , obrigado por relatar. Você disse
> 
> > Temos este aplicativo exclusivo com 4 painéis.
> > Por exemplo, posso colocar dois painéis em lugares diferentes, não dentro dos mesmos DockWidgets, para que abram e fechem independentemente.
> 
> Basicamente, você tem dois painéis, certo?
> 
> > Sem ter que definir entry_points para cada painel.
> 
> Se você tiver dois painéis, você declarou um entry_point para cada um, não há solução alternativa para isso. Mas você pode fazer isso no mesmo pacote, como fazemos com nossos próprios painéis.
> 
> > Semelhante ao Files and Variable Explorer.
> 
> Esses são painéis independentes, mas cada um tem seu próprio entry_point.

**Comment by dan123456-eng** [comment]
Hello @ccrdoba12! We have 4 panels. I declared entry_point for only one, but now I will declare it for each one, Independently.

**Comment by dan123456-eng** [comment]
Our code is not open source. In the future, it could become open source. But I'm sure my project manager and I can show you the code. Will I try to make the changes mentioned above, and if I can't, can I try to schedule a time to show you the code? Thanks!

**Comment by ccordoba12** [comment]
> Will I try to make the changes mentioned above, and if I can't, can I try to schedule a time to show you the code?

Yeah, that sounds like a good idea. We can have a Zoom call and we can help you to fix this issue on it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
