### ISSUE TITLE
How to install spyder plugins when installed from dmg/.app?

### ISSUE THREAD

**Issue by step21** [spyder-ide/spyder#15901]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I installed Spyder with the MacOS dmg/app. Then I wanted to try some plugins, but even when starting the shipped python and corresponding pip via `./python -m pip` or from within spyder via cellmagic, it seems either unable to install (from within spyder) or installs where it apparently is not used/found (from outside)

### What steps reproduce the problem?

1. Start spyder via dmg/app
2. Try to install plugin in one of the ways above

### What is the expected output? What do you see instead?

I expected to see plugin tabs in Spyder. Instead I do not see it.

### Paste Traceback/Error Below (if applicable)

```python-traceback

%%bash
pip3 install spyder-terminal


Python path configuration:
  PYTHONHOME = '/Applications/Spyder.app/Contents/Resources'
  PYTHONPATH = '/Applications/Spyder.app/Contents/Resources'
  program name = '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
  sys.base_prefix = '/Applications/Spyder.app/Contents/Resources'
  sys.base_exec_prefix = '/Applications/Spyder.app/Contents/Resources'
  sys.executable = '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'
  sys.prefix = '/Applications/Spyder.app/Contents/Resources'
  sys.exec_prefix = '/Applications/Spyder.app/Contents/Resources'
  sys.path = [
    '/Applications/Spyder.app/Contents/Resources',
    '/Applications/Spyder.app/Contents/Resources/lib/python38.zip',
    '/Applications/Spyder.app/Contents/Resources/lib/python3.8',
    '/Applications/Spyder.app/Contents/Resources/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000011b379dc0 (most recent call first):
<no Python frame>
Traceback (most recent call last):

  File "<ipython-input-9-51830e68d79d>", line 1, in <module>
    get_ipython().run_cell_magic('bash', '', 'pip3 install spyder-terminal\n\n')

  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/IPython/core/interactiveshell.py", line 2403, in run_cell_magic
    result = fn(*args, **kwargs)

  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/IPython/core/magics/script.py", line 142, in named_script_magic
    return self.shebang(line, cell)

  File "decorator.pyc", line 232, in fun

  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/IPython/core/magics/script.py", line 245, in shebang
    raise CalledProcessError(p.returncode, cell, output=out, stderr=err)

CalledProcessError: Command 'b'pip3 install spyder-terminal\n\n'' returned non-zero exit status 1.

```

## Versions

* Spyder version: 5.0.4
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt version: 5.12.10
* Operating System name/version: Darwin 19.6.0 / MacOS Catalina

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.24.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  1.6.3 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @step21, thanks for reporting. There are seveval things related to your question:

1. As you discovered, we don't provide pip in our installers to avoid people messing with them by installing other packages and breaking Spyder. The main purpose of our installers is to be very robust and stable, so that people don't suffer by incompatible package versions or broken installations (which is quite common with pip and conda).
2. None of our plugins have been updated to work with Spyder 5 yet.
3. We're investigating how to create a mechanism to install plugins in our installers. That's probably something that won't be available until next year.

**Comment by ccordoba12** [comment]
I'm going to close this issue because there's nothing we can do about it for now.

**Comment by step21** [comment]
Ah ok, thanks for clarifying. That makes sense, also I was not aware that plugins are not compatible with spyder 5.

**Comment by ccordoba12** [comment]
Yeah, the first one will be spyder-terminal, followed by spyder-notebook.
