### ISSUE TITLE
code analysis broken

### ISSUE THREAD

**Issue by jk-vb** [spyder-ide/spyder#15930]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
code analysis is broken. When clicking the button under source, error below occurs 

/Applications/Spyder.app/Contents/MacOS/python: No module named pylint.__main__; 'pylint' is a package and cannot be directly executed

**Comment by andfoy** [comment]
Hi @jk-vb, thanks for reporting this issue, could you please provide more information about the version of the Mac installer that you are using? cc @mrclary

**Comment by jk-vb** [comment]
I'm not sure . It's Spyder.dmg with Spyder.app and an arrow to the Applications folder, it was downloaded within the week . MacOs 10.15.7

**Comment by mrclary** [comment]
@jk-vb , go to the "Spyder" menu in the menubar at the top of your screen and select "About Spyder". The pop-up window should tell you what version of Spyder you are running. Version 5.0.4 is known to have the problem you reported, but it should be fixed in 5.0.5 (see #15905 and #15885).

**Comment by ccordoba12** [comment]
Closing due to lack of response.
