### ISSUE TITLE
Autosave Doesn't Appear to be Autosaving "untitled0.py" Files

### ISSUE THREAD

**Issue by JoeMarino2021** [spyder-ide/spyder#15940]
When I open a file and look in the `autosave` folder, I see the autosave function at work.  The folder has a copy of my file that I am working on, and can recover it if Spyder crashes.

When I save an `untitled0.py` file, I also see a copy of the file in the autosave folder, now with its new name and ready for recovery if Spyder crashes.

However, when the file stays in its `untitled0.py` state, not saved for the first time, no backup is ever found in the autosave folder.  Why aren't `untitled0.py` files backed up?  I left a never saved file open in Spyder once, thinking it was being autosaved.  I came back the next day to save it, and Spyder crashed.  I didn't worry, expecting to find the backup ready for me.

I would request that `untitled0.py` files be backed up even before they are saved for the first time.  Sometimes I work on a file for a while before I feel like I have something worth keeping.  At that point I will think up a name and save the file.  I always thought those `untitled0.py` files were being backed up; they are not.  Or, are they supposed to be, and my installation is faulty?

My version is Spyder 4.2.1.  I will be soon updating to the latest version of Spyder (I update my software every 3 to 6 months). 
 Thank you for reading my submission.

**Comment by JoeMarino2021** [comment]
Spyder installed via Anaconda.

## Dependencies
### Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.4 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.1 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.1 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

### Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.19.2 (OK)
pandas >=1.1.1                  :  1.2.1 (OK)
scipy >=0.17.0                  :  1.6.0 (OK)
sympy >=0.7.3                   :  1.7.1 (OK)

**Comment by steff456** [comment]
Hi @JoeMarino2021,

Can you please update to 4.2.5 and see if the behavior persists?

Thanks for reporting!

**Comment by ccordoba12** [comment]
@JoeMarino2021, we don't save untitled files for now because they are not real files on disk. However, we're planning to save them by default in the future, as discussed on issue #13736.

For now, we recommend you to save any file you consider important to avoid this problem in the future.

**Comment by JoeMarino2021** [comment]
I've read the linked issue twice over.  I must be missing the part about autosaving fresh files.  Unless autosaving is being replaced by "quick saving".

I don't think autosave should deviate significantly from it's behavior in any other Windows app.  The reason why every Windows app follows the "File-Edit" menu options paradigm (with "Help" being the menu at the far right) is because it's considered good programming practice to greet users with the familiar.  That's why Control-C is always copy, Control-V is always paste.  Any app that deviates from this will frustrate users.  Users expect common app features to behave in the same way across all apps, no matter how disparate the apps are.

Microsoft Excel, for example, will autosave "Book 1.xlsx" files.  Autosave works the same way in all apps that have it (I don't know of any that refuse to autosave fresh files because they "are not real files on disk"), and choosing to deliberately not implement autosave in the same way could lead to potential confusion or unexpected results.  Is it impossible that after 15 minutes of programming, a power failure or other calamity might strike while still working on an "untitled0.py" file?

Also, frequently having to save files just to avoid possibly losing something that turns into a valuable file will litter the hard disk and Most Recently Used files with meaningless entries.  Why would the user be asked to maintain their file systems and prune their MRU lists?  Can one even remove individual items from the MRU in Spyder?  "Just save your file" seems to miss the whole point of having an autosave feature.  "Just don't let your house catch fire" can help you if the sprinkler system doesn't reach the second bedroom, but why wouldn't you offer a sprinkler system to customers that provides full coverage?

Thank you, Stephannie, for your suggestion to try 4.2.5.  I will give the latest version of Spyder a try in the next few days (unless you are implying that specifically version 4.2.5 will give the desired results) and see if it implements autosave in the expected manner.  I will report back if it does or does not.  I also urge the Spyder team to reconsider the closing of this issue and make autosave work the same as it does in all other apps.

**Comment by ccordoba12** [comment]
> Unless autosaving is being replaced by "quick saving".

Quick saving means "autosaving of untitled files", yes.

> I don't think autosave should deviate significantly from it's behavior in any other Windows app.

I understand your point, but for now we're swamped with several other things. You're welcome to help us though.

> Thank you, Stephannie, for your suggestion to try 4.2.5. I will give the latest version of Spyder a try in the next few days (unless you are implying that specifically version 4.2.5 will give the desired results)

Unfortunately, that's still not available in Spyder 5, sorry.

**Comment by JoeMarino2021** [comment]
How might I help?  I am an OK programmer and can maybe get you close if not all the way to production code.  If you can show me all the places where the autosave is currently implemented, and where the code for "new file" is (so I can start triggering an autosave of the new file), so I don't have to dig for it myself, I can see if I am up to the task.  I see autosaving new files to be much easier than the "quick saving" which requires user dialog changes, as well.  Or, just tell me an efficient way to dig for the autosave function code.  I guess I would also need to know where "save" and "save as" were, so I can start autosaving the file under the new name.

The answer "we are swamped" is much more palatable to me.  That makes a lot more sense.  Spyder is a labor of love, and I hope some day it also becomes lucrative for you, as well.  Each one of you has another life, full of time demands, and taking on the Spyder project is an incredible contribution you make to the rest of us, often without enough appreciation.  Let me express my appreciation, then, at this opportunity for the wonderful IDE you have created.  The variable explorer alone, is worth the price of admission.  After working in R Studio for R, not having the variable explorer would make programming Python painful, perhaps too painful.  I was so happy to finally come across the Spyder IDE.

So, if I can help, I'd be willing to give it a try.  I am an OK programmer, like I said before (I am an ME, not a computer science major), but maybe I can do something to help.  So, let me know.

Good luck squashing all of the bugs!  The upcoming new logo looks really cool, too.
