### ISSUE TITLE
[Enhancement] Support XButton1 and XButton2

### ISSUE THREAD

**Issue by maurerle** [spyder-ide/spyder#15948]
## Enhancement Description

My Mouse has two extra buttons, Forward and backward (for example in a browser).
The related Keyboard-Events are XButton1 (Back) and XButton2 (Forward).

I'd expect them to issue the same event as the ALT+Left or ALT+Right Key-Combination does.
This would improve source code browsing a lot.

Thanks!

**Comment by steff456** [comment]
Hi @maurerle,

Have you tried to add this combination under `Preferences > Shortcuts`, you can bind those keys to do whatever you want. Please try it and let me know how it goes.

**Comment by maurerle** [comment]
Hi, this didn't work out.
The MouseButtons are currently not recognized by Spyder

A Code Example of the requested functionality can be seen here in a Python QT Browser:
https://github.com/qutebrowser/qutebrowser/blob/4c479bb4ab9a25276ea9045c99b690dc925dd345/qutebrowser/browser/eventfilter.py#L247

**Comment by skjerns** [comment]
I think this would be great! I would also love to use my extra mouse buttons for prev/next cursor position

**Comment by ccordoba12** [comment]
@skjerns, this doesn't seem hard to implement. Do you want to give it a try?
