### ISSUE TITLE
"Replace all" in selection

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#15941]
Is this doable? Currently I need to repeatedly press Enter, replacing one by one - and when on last match within selection, it'll jump down the file for next match despite it not being in selection -- [demo](https://puu.sh/HS4UB/1a23aae717.mp4). 

Ideally I can just search a string in the selection and replace it all with one hotkey.

**Comment by steff456** [comment]
Hi @OverLordGoldDragon,

In which version of Spyder are you encountering this behavior?

**Comment by OverLordGoldDragon** [comment]
4; I see it is in 5, nice.

I'd prefer that Enter would by default execute "In selection", or that pressing Tab would allow iterating over the options just as it allows to jump to "Replace with", this way I could select "In selection" without mouse. But it's not as important - feel free to close.

**Comment by steff456** [comment]
Are you in the latest release of Spyder 4? It is 4.2.5, please try it in that version.

Great! Thanks for the insight, if you want, please describe the idea and open an issue in the ux-improvements repo were we will discuss some ui/ux changes.
