### ISSUE TITLE
search in a big file is quite slow

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#15957]
macos 1.15
spyder 5.0.1

I have a file about 10000 lines,
when search some keywords in file,
if you type a keyword that does not exist, spyder will be very slow with a lag about 3-5s.

**Comment by andfoy** [comment]
Hi @fayeshine, thanks for opening this issue. However, this is a known issue that we are tracking here: https://github.com/spyder-ide/spyder/issues/15471
