### ISSUE TITLE
AttributeError in snippets extension

### ISSUE THREAD

**Issue by MJV1989** [spyder-ide/spyder#15960]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I have no clue as I am a beginner. Hopefully, someone else understands what might have gone wrong.

QTextCursor::setPosition: Position '147' out of range
QTextCursor::setPosition: Position '147' out of range
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/extensions/snippets.py", line 52, in wrapper
    return f(self, *args, **kwargs)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/extensions/snippets.py", line 241, in _process_text
    self.insert_text(text, line, column)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/editor/extensions/snippets.py", line 383, in insert_text
    text_node_tokens = list(text_node.tokens)
AttributeError: 'NoneType' object has no attribute 'tokens'

**Comment by ccordoba12** [comment]
Hey @MJV1989, thanks for reporting. Could you let us know what text you introduced in the editor that generated this error?

**Comment by MJV1989** [comment]
Hi @ccordoba12, I believe I was writing the following when this happened:

# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

animals = {'a' : 'aardvark', 'b' : 'baboon', 'c' : 'coati'}

animals['d'] = ['donkey']
animals['d'].append('dog')
animals['d'].append('dingo')

def biggest(aDict):
    '''
    
    Parameters
    ----------
    aDict : A dictionary where all the values are lists.

    Returns
    -------
    The key with the largest number of values associated with it.

    '''
    if aDict == {}:
        return None
    else:
        return max(aDict, key = lambda x : len(aDict[x]))

**Comment by ccordoba12** [comment]
Thanks for your help @MJV1989! We'll fix this in our next version (5.1.0), to be released at the end of the month.
