### ISSUE TITLE
Allow more recent Parso versions

### ISSUE THREAD

**Issue by algent-al** [spyder-ide/spyder#15962]
currenctly the requirement for parso module is version 0.7.0

From the [changelog](https://github.com/davidhalter/parso/blob/master/CHANGELOG.rst#071-2020-07-24) it is only a bug fix release.

```
0.7.1 (2020-07-24)

    Fixed a couple of smaller bugs (mostly syntax error detection in Grammar.iter_errors)

This is going to be the last release that supports Python 2.7, 3.4 and 3.5.
```

**Comment by andfoy** [comment]
Hi @algent-al, right now we depend on a specific Parso version in order to fix a specific Jedi version, I don't remember the specific details, maybe @ccordoba12 can give you a more detailed explanation about this.

**Comment by ccordoba12** [comment]
We will allow Spyder to work with more recent versions of Jedi and Parso in our next version (5.1.0), to be released at the end of the month.
