### ISSUE TITLE
Spyder crashed and deleted all files inside the current directory 

### ISSUE THREAD

**Issue by RezaKakooee** [spyder-ide/spyder#15975]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi, I was working from early morning on some codes with Spyder, but have not pushed the updated code into my remote repo. 
My spyder crashed and removed all files/folders inside the current directory. I have a Windows machine and checked my recycle bin. Nothing is there!
Would you please let me know how can I recover the files? I hope there is a solution for that!!
Thanks.

### What steps reproduce the problem?

1. This is the first time such a thing happened to me

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code
```

## Versions

* Spyder version: 4
* Python version: 3.8
* Qt version: 3.1
* PyQt version: PyQt5
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)

```

**Comment by steff456** [comment]
Hi @RezaKakooee,

It seems you opened the internal console pane, don't worry this is a tool that we use for debugging Spyder. You can safely close it via de hamburger menu or in the application menus in `View>Panes>Internal console`. 

Thanks for reporting!

**Comment by RezaKakooee** [comment]
Dear Stephannie,
Many thanks for your reply. But this was not my problem. My problem was that Spyder crashed and deleted all my files inside the current directory. 
I tried a couple of ways yesterday to recover my python files. In the end, I was able to recover my files by a recovery software for Windows. If someone is interested to know the name of the software, please let me know.

**Comment by steff456** [comment]
What were you doing when Spyder crashed?

**Comment by RezaKakooee** [comment]
deleting a log file by `Spyder`'s `File Explorer` panel.

**Comment by steff456** [comment]
Do you remember which log file?

**Comment by RezaKakooee** [comment]
Sure, I am using `avalanche` package. It generates a logfile. So, I was deleting that one.

**Comment by ccordoba12** [comment]
Closing because this probably no longer applies to our latest version.
