### ISSUE TITLE
Highlight function calls

### ISSUE THREAD

**Issue by niekwit** [spyder-ide/spyder#15982]
Is it possible to add an option to highlight function calls (as in RStudio)?

**Comment by steff456** [comment]
Hi @niekwit,

Can you please post here some screenshots so we can understand better your idea?

**Comment by niekwit** [comment]
Here is an example with highlighting on:
![](https://github.com/niekwit/CRISPR-tools/blob/master/img/function_highlight.png)


And off:
![](https://github.com/niekwit/CRISPR-tools/blob/master/img/no_function_highlight.png)

**Comment by steff456** [comment]
Thanks for the examples, we are working towards adding a new highlighting backend to Spyder that will enable this. We hope to have it for Spyder 6.

Thanks for opening this issue!
