### ISSUE TITLE
error with qdarstyle.palette i think

### ISSUE THREAD

**Issue by guillaumer36** [spyder-ide/spyder#15997]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
plt.subplot(211)
plt.plot(dateint,L365C,color='tab:blue',label='Chevtogne')
plt.plot(dateint,L365H,color='tab:orange',label='Halleux')
plt.legend()
plt.ylim(0.4,0.95)
plt.ylabel('NDVI [-]')
plt.xlabel('Temps [années]')
plt.title('Ajustement double logistique', fontsize=12, color='grey', loc='left', style='italic')

**Comment by ccordoba12** [comment]
If the error is with QDarkstyle, please close Spyder, open the Anaconda Prompt (or a system terminal) and run there

    conda install qdarkstyle=2.8.1

**Comment by ccordoba12** [comment]
Closing due to lack of response.
