### ISSUE TITLE
Monaco fonts are not supported on Ubuntu in spyder5

### ISSUE THREAD

**Issue by zysNLP** [spyder-ide/spyder#15990]
## Problem Description

As title, monaco fonts can be used in win10 spyder5 but why not work in ubuntu spyder5?

## Versions

* Spyder version: 5.0.3
* Python version: 3.6.8
* Qt version: 
* PyQt version: 
* Operating System name/version: ubuntu16.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @zysNLP, thanks for reaching out, could you please provide screenshots with the state that you are seeing?

**Comment by zysNLP** [comment]
In spyder, @andfoy you can find fonts in Tools>>Preferences>>Appearance>>Fonts>>Plain text.  If you download monaco font and installed in your computer then "Plain text" here can find "Monaco" to choose. but in ubuntu system I can't find this font. Sorry but I can't upload screenshots for you. Can you please make it by yourself?

**Comment by ccordoba12** [comment]
@zysNLP, did you properly install that font on Linux? If not, Spyder won't be able to find it.

**Comment by zysNLP** [comment]
@ccordoba12 
I have downloaded and installed the monaco in my ubuntu16.04 system. But spyder still not find this font in the "Plain text" list. Do you find it in your spyder?  Could you please upload an screenshots please? Thank you.

**Comment by ccordoba12** [comment]
Sorry, we don't have time to test this. But Spyder doesn't do anything special other than getting the monospaced fonts installed in your system.

**Comment by zysNLP** [comment]
@ccordoba12 But spyder does not install monaco font in plain text in ubuntu I don't know why.
