### ISSUE TITLE
Spyder fancy help uses greek characters on Windows 10

### ISSUE THREAD

**Issue by rfetick** [spyder-ide/spyder#15991]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder``
* [ ] ~~Could not reproduce inside ``jupyter qtconsole``~~ (not console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/) (-> used `conda update --all`)
    * [ ] ~~Tried the other applicable steps from the Troubleshooting Guide~~
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder (5.0.3) help panel appears using greek characters instead of roman (usual) ones. This issue only appears with the fancy help switched on, the correct (roman) font is used as expected when switching to raw docstring.

OS: Windows 10

Environment: miniconda

### What steps reproduce the problem?

1. Open Spyder
2. Display help on any function or class

### What is the expected output? What do you see instead?

Roman characters are expected for Spyder's fancy help, as it is for all my computer.

### Paste Traceback/Error Below (if applicable)

(not applicable, no traceback)

## Versions

* Spyder version: **5.0.3**
* Python version: **3.9.5**
* Qt version: **5.9.7**
* PyQt version: **5.9.2**
* Operating System name/version: **Windows 10**

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.3;<2.1.0 :  2.0.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.5.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by andfoy** [comment]
Hi @rfetick, thanks for opening this issue. Could you please provide a screenshot that shows the aforementioned issue description?

**Comment by rfetick** [comment]
Here is the issue when turning on the fancy text for the help section. When turning fancy text off, everything is fine.

![spyder_fancy_text](https://user-images.githubusercontent.com/32675073/125045521-5f66ec00-e09d-11eb-826f-8b7984af1a9c.PNG)
![spyder_raw_text](https://user-images.githubusercontent.com/32675073/125045529-6130af80-e09d-11eb-8164-0644d6030ef9.PNG)

**Comment by ccordoba12** [comment]
@rfetick, this could be caused by the rich text font you currently have selected in our Preferences:

![imagen](https://user-images.githubusercontent.com/365293/125149060-417ca400-e0fc-11eb-8042-04b297c780de.png)

Please go there and try to select a different font to see if that helps.

**Comment by rfetick** [comment]
Hello,

The rich text font was `Comic Sans MS` by default, and that caused the greek characters issue. I switched to another font (`Consolas`) and now that works just fine!
Thank you!

Romain

**Comment by ccordoba12** [comment]
I really don't know what happened in your case but I'm glad you were able to solve it.
