### ISSUE TITLE
Spyder tab in menu bar will not show Preferences...  option

### ISSUE THREAD

**Issue by jezur** [spyder-ide/spyder#16002]
### What steps will reproduce the problem?

Big Sur 11.2.3
spatialindex using brew
This happens when I open Spyder.

I wanted to change the default Python environment but the Preferences... option was not available in the 'Spyder' tab in the menu bar. I had to click the environment icon in lower bar of the window to see the prompt "Change deafult environment in Preferences..." to finally make it work.

**Comment by ccordoba12** [comment]
Hey @jezur, thanks for reporting. This is a known issue and we'll try to fix it in a future release.
