### ISSUE TITLE
Splash screen can take a lot of space in low resolution screens

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#16006]
When starting Spyder in my laptop screen (1366 x 768) the splash looks like this (kind of big):

![image](https://user-images.githubusercontent.com/16781833/125324449-374ae780-e340-11eb-8de1-9f15903007e4.png)

However in my secondary screen (1920×1080) the splash looks better:

![image](https://user-images.githubusercontent.com/16781833/125323370-fe5e4300-e33e-11eb-8372-53702b7cef7d.png)

**Comment by ccordoba12** [comment]
Thanks for reporting @dalthviz. @juanis2112 will take care of it.
