### ISSUE TITLE
Feature request: Expose pdb "u" and "d" commands to user

### ISSUE THREAD

**Issue by matheger** [spyder-ide/spyder#16013]
pdb provides the "u" and "d" commands to step up and down through the stack when debugging. This works in spyder too, but is completely hidden from the user - there are no buttons in the toolbar, and no keyboard shortcut definitions. To me this seems like vital functionality that should be mirrored within spyder as well.

**Comment by impact27** [comment]
I think this would be covered by https://github.com/spyder-ide/spyder/pull/11186
It would show you the full stack and you could click on it to go up/down by multiple levels

**Comment by matheger** [comment]
> 
> 
> I think this would be covered by #11186
> It would show you the full stack and you could click on it to go up/down by multiple levels

You're right, that's exactly what I was looking for (even better, in fact.) Will this be integrated into the program soon?

**Comment by impact27** [comment]
Well I hope, but in the meantime you can always use git to checkout this branch if you know how to do this kind of things. I'll update the PR when #15922 is merged. I'll reopen this issue as it is not solved yet and we will close it when #11186 is merged.
