### ISSUE TITLE
1)import plt will lead crash.2) When I open project, issue occur.

### ISSUE THREAD

**Issue by XiFengxiaoxu** [spyder-ide/spyder#16016]
### What steps will reproduce the problem?

* IF import matplotlib.pyplot as plt, run any code in plt and close the Spyder, when I open the Spyder IDE again, the operation interface will pop up, but it will crash immediately.
* I have to delete the file in C:\Users\msi\.spyder-py3 to get back to normal.

* When I successfully opened spyder and opened an existing project, this error occurred

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\spyder\pkgs\spyder\plugins\projects\plugin.py", line 129, in <lambda>
    triggered=lambda v: self.open_project())
  File "D:\spyder\pkgs\spyder\plugins\projects\plugin.py", line 402, in open_project
    project_type_class = self._load_project_type_class(path)
  File "D:\spyder\pkgs\spyder\plugins\projects\plugin.py", line 813, in _load_project_type_class
    config.read(fpath)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\configparser.py", line 696, in read
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\configparser.py", line 1014, in _read
UnicodeDecodeError: 'gbk' codec can't decode byte 0xab in position 204: illegal multibyte sequence
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.24.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.5 (OK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @XiFengxiaoxu, you said:

> IF import matplotlib.pyplot as plt, run any code in plt and close the Spyder

Please go to the menu

    Tools > Preferences > IPython console > Graphics > Graphics backend

select there the `Automatic` option, close Spyder and start it again. Perhaps your problem will be solved by that.

> When I successfully opened spyder and opened an existing project, this error occurred

Please post the full path to one your projects so we can try to reproduce this problem on our side.

**Comment by XiFengxiaoxu** [comment]
Thanks for your answer @ccordoba12 

> select there the Automatic option,close Spyder and start it again. Perhaps your problem will be solved by that.

I have tried it and the problem still exists.

> Please post the full path to one your projects so we can try to reproduce this problem on our side.

Path: E:\pycode\learn_myself

**Comment by ccordoba12** [comment]
> I have tried it and the problem still exists.

Could you post a screenshot of what you're seeing? I don't understand very well what's happening in your case.

> Path: E:\pycode\learn_myself

Ok, then could you tell what's the main language in your computer? I mean, are you using Windows in English or a different language?

**Comment by XiFengxiaoxu** [comment]
This time  I only creat project, the crash happend.

https://user-images.githubusercontent.com/50860885/125737326-9ef2f9c9-6dae-405e-b842-4208b8822284.mp4

 the main language in my computer is Simplified Chinese

**Comment by XiFengxiaoxu** [comment]
Additional information：
If I did not create the project, only import plt , run some code , close Spyder and start it again , no crash occurred.

**Comment by XiFengxiaoxu** [comment]
@ccordoba12 
I might know the reason of the crash and the open project error. In this project, I created a file named matplotlib.py. 

 This may be the crux of the problem

**Comment by ccordoba12** [comment]
> This may be the crux of the problem

Yeah, that could be really the cause of it. What happens when you rename that file to something else?

**Comment by XiFengxiaoxu** [comment]
Everything is back to normal. The way to find out the reason is that when I switched to Jupyter, I couldn't import matplotlib.pyplot. Unlike Jupyter, Spyder can be imported normally, but the problem occurs after closing the IDE. This is an interesting phenomenon for me, and I may not be able to understand it as a beginner.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know things are working as expected now.
