### ISSUE TITLE
spyder 5.0.5 Kernel- connect

### ISSUE THREAD

**Issue by falahfakhri-Iraq** [spyder-ide/spyder#16019]
### What steps will reproduce the problem?
spyder 5.0.5, python 3.7, windows 10

the kernel couldn't connect and I got the following messages while trying up to restart the kernel. 

Restarting kernel...
 
C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python37\lib\site-packages\ipykernel\kernelbase.py:495: RuntimeWarning: coroutine 'Kernel.poll_control_queue' was never awaited
  asyncio.run_coroutine_threadsafe(self.poll_control_queue(), control_loop.asyncio_loop)

**Comment by ccordoba12** [comment]
Hey @falahfakhri-Iraq, thanks for reporting. Please install our latest version of spyder-kernels by opening a system terminal and running there

    pip install spyder-kernels==2.0.5

That should solve your problem.

**Comment by falahfakhri-Iraq** [comment]
Dear @ccordoba12 
Unfortunately not, and I converted to python 3.9, and spyder 5.0.5, now facing up another problem, I already posted it, waiting for solution.

Thanks a lot for your patience with me.

**Comment by ccordoba12** [comment]
Closing as a duplicate of issue #16029.
