### ISSUE TITLE
matplotlib fails to run

### ISSUE THREAD

**Issue by richiesh** [spyder-ide/spyder#16028]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
import numpy as np
import matplotlib.pyplot as plt
T = np.linspace(0 , 2 * np.pi, 1024)
plt.axes(polar = True)
plt.plot(T, 1. - np.sin(T),color="r")
plt.show()

**Comment by juanis2112** [comment]
Hello @richiesh. Please provide more information about the issue you are having. What is the error that you are seeing?

**Comment by juanis2112** [comment]
Closing due to lack of response
