### ISSUE TITLE
QtWebKit issue prevents Spyder 2.2.5 from opening

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1602]
_From [brec...@gmail.com](https://code.google.com/u/114277718751439330783/) on 2013-10-13T21:01:51Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Running CentOS 6.4
2. Install spyder from source (2.2.5)
3. Run spyder What is the expected output? What do you see instead? Expect to see the IDE load, instead there is an error:
Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in \<module>
    start_app.main()
  File "/usr/lib/python2.6/site-packages/spyderlib/start_app.py", line 72, in main
    from spyderlib import spyder
  File "/usr/lib/python2.6/site-packages/spyderlib/spyder.py", line 106, in \<module>
    from spyderlib.plugins.inspector import ObjectInspector
  File "/usr/lib/python2.6/site-packages/spyderlib/plugins/inspector.py", line 32, in \<module>
    from spyderlib.widgets.browser import WebView
  File "/usr/lib/python2.6/site-packages/spyderlib/widgets/browser.py", line 11, in \<module>
    from spyderlib.qt.QtWebKit import QWebView, QWebPage
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/QtWebKit.py", line 10, in \<module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named QtWebKit What version of the product are you using? On what operating system? 2.2.5 and CentOS 6.4 

Please provide any additional information below

. qtwebkit is installed, but the bindings don't seem to be.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1602_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-10-14T00:12:42Z_

You have to install the package PyQt4-webkit with yum.

**Comment by spyder-issues-migrator** [comment]
_From [brec...@gmail.com](https://code.google.com/u/114277718751439330783/) on 2013-10-14T10:56:03Z_

Thanks, worked like a charm.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T18:11:15Z_

Thanks Joseph for the help!

**Status:** Invalid

**Comment by jmkrieger** [comment]
I am using Ubuntu 16.10, PyQt4-webkit cannot be found, it´s possible that this package no longer more in the repositories? And how I get an alternative or a PPA for this?

**Comment by jitseniesen** [comment]
Ubuntu's bug report is at https://bugs.launchpad.net/ubuntu/+source/spyder/+bug/1620300

**Comment by jmkrieger** [comment]
Thanks! I have found this report already and I hoped to find a better answer here ...
Of course, I added the universe repository of the Xenial update and execute:
`sudo add-apt-repository deb http://archive.ubuntu.com/ubuntu xenial universe` and then
`sudo apt update` &
`sudo apt install python-qt4=4.11.4+dfsg-1build4 python-qt4-sql=4.11.4+dfsg-1build4`
Too bad that Cannoncial deleted this packages in the yakkety repository ...

**Comment by ccordoba12** [comment]
That was not a decision taken by Ubuntu devs but Debian ones instead.
