### ISSUE TITLE
Feature request: easy switch between virtual environment

### ISSUE THREAD

**Issue by mscheltienne** [spyder-ide/spyder#16021]
## Problem Description

Maybe I am mistaken, but the only way to my knowledge to change the virtual environment is to go in:

>     Settings > Python interpreter > Use the following python interpreter

and change the location/path to the python.exe file.

This is not very handy and doesn't allow fast, easy change between virtual environments. 

My spyder installation, via pip, is on the global parent python installation; while my virtual environments have `spyder-kernels` installed, via pip,. to allow the console to work with a given environment. But changing between my venv is really annoying. 

Adding an option in the drop-down menu of the console, or in the right-click menu; to directly change the python interpreter (even only in a new console) would be much simpler than going to the settings every time.

For a more advance solution, having a virtual env manager like the python path manager which let you register your venv in advance would be even simpler, as you get rid of the step where you have to specify the path to the venv.

**Comment by ccordoba12** [comment]
Hey @mscheltienne, thanks for the suggestion. We plan to implement this in a future release as discussed on issue https://github.com/spyder-ide/ux-improvements/issues/10.

So I'm closing this one in favor of that.
