### ISSUE TITLE
Graphic backend

### ISSUE THREAD

**Issue by falahfakhri-Iraq** [spyder-ide/spyder#16029]
### What steps will reproduce the problem?

Getting the followoing problem, 
CommError: Can't make a request to a closed comm

Trying up to change the backend getting it, I changed to python 3,9 anaconda

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\preferences\widgets\configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 110, in apply_changes
    self.apply_callback()
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\preferences\api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\api\preferences.py", line 104, in wrapper
    func(opts)
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 451, in apply_plugin_settings
    client_backend_not_inline = [
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 452, in <listcomp>
    client.shellwidget.get_matplotlib_backend() != inline_backend
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 350, in get_matplotlib_backend
    return self.call_kernel(
  File "C:\Users\FALAH FAKHRI\miniconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 550, in __call__
    raise CommError("The comm is not connected.")
spyder_kernels.comms.commbase.CommError: The comm is not connected.
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.9.1
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.25.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  51.0.0.post20201207 (OK)
sphinx >=0.6.6                :  4.1.1 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @falahfakhri-Iraq, please open the Anaconda Prompt, run there the following command

    conda list

and post its output here.

**Comment by falahfakhri-Iraq** [comment]
Dear @ccordoba12 
Thanks a lot for your kindness and patience with me, following is the result of $ conda list

# Name                    Version                   Build  Channel
absl-py                   0.13.0                   pypi_0    pypi
affine                    2.3.0                    pypi_0    pypi
alabaster                 0.7.12                   pypi_0    pypi
anyio                     2.2.0            py39hcbf5309_0    conda-forge
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               20.1.0           py39hb82d6ee_2    conda-forge
arrow                     1.1.1                    pypi_0    pypi
astroid                   2.6.2                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.5.5                    pypi_0    pypi
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.0                    pypi_0    pypi
binaryornot               0.4.4                    pypi_0    pypi
black                     21.6b0                   pypi_0    pypi
bleach                    3.3.1              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py39h2bbff1b_1003
ca-certificates           2021.7.5             haa95532_1
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py39haa95532_0
cffi                      1.14.4           py39hcd4344a_0
chardet                   3.0.4           py39haa95532_1003
click                     8.0.1                    pypi_0    pypi
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3           py39haa95532_0
conda-package-handling    1.7.2            py39h8cc25b3_1
console_shortcut          0.1.1                         4
cookiecutter              1.7.3                    pypi_0    pypi
cryptography              3.3.1            py39hcd4344a_0
cycler                    0.10.0                   pypi_0    pypi
debugpy                   1.3.0            py39h415ef7b_0    conda-forge
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713                 pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flake8                    3.8.4                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
gdal                      3.3.1                    pypi_0    pypi
google-auth               1.33.0                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      2.10                       py_0
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        4.6.1            py39hcbf5309_0    conda-forge
inflection                0.5.1                    pypi_0    pypi
intervaltree              3.1.0                    pypi_0    pypi
ipykernel                 6.0.2            py39h832f523_0    conda-forge
ipython                   7.25.0           py39h832f523_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.9.2                    pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                    pypi_0    pypi
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hcbf5309_0    conda-forge
jupyter_server            1.4.1            py39haa95532_0
jupyterlab                3.0.16             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.6.1              pyhd8ed1ab_0    conda-forge
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   23.0.1                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.6.0                    pypi_0    pypi
libsodium                 1.0.18               h8d14728_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py39hb82d6ee_0    conda-forge
matplotlib                3.4.2                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
menuinst                  1.4.16           py39h2bbff1b_0
mistune                   0.8.4           py39hb82d6ee_1004    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
mypy-extensions           0.4.3                    pypi_0    pypi
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py39hcbf5309_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.5.1                    pypi_0    pypi
notebook                  6.4.0              pyha770c72_0    conda-forge
numpy                     1.19.5                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.0                    pypi_0    pypi
pandoc                    2.14.0.3             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2                    pypi_0    pypi
parso                     0.7.0                    pypi_0    pypi
path                      16.0.0                   pypi_0    pypi
pathspec                  0.8.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.3.1                    pypi_0    pypi
pip                       21.1.3           py39haa95532_0
pluggy                    0.13.1                   pypi_0    pypi
powershell_shortcut       0.0.1                         3
poyo                      0.5.0                    pypi_0    pypi
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
protobuf                  3.17.3                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0                    pypi_0    pypi
pycosat                   0.6.3            py39h2bbff1b_0
pycparser                 2.20                       py_2
pydocstyle                6.1.1                    pypi_0    pypi
pyflakes                  2.2.0                    pypi_0    pypi
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pylint                    2.9.3                    pypi_0    pypi
pyls-black                0.4.7                    pypi_0    pypi
pyls-spyder               0.3.2                    pypi_0    pypi
pynacl                    1.4.0                    pypi_0    pypi
pyopenssl                 20.0.0             pyhd3eb1b0_1
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt5                     5.12.3                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.17.3           py39hb82d6ee_2    conda-forge
pysocks                   1.7.1            py39haa95532_0
python                    3.9.1                h6244533_2
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-jsonrpc-server     0.4.0                    pypi_0    pypi
python-language-server    0.36.2                   pypi_0    pypi
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1                    pypi_0    pypi
pywin32                   228              py39he774522_0
pywin32-ctypes            0.2.0                    pypi_0    pypi
pywinpty                  0.5.7            py39haa95532_0
pyzmq                     22.1.0           py39he46f08e_0    conda-forge
qdarkstyle                3.0.2                    pypi_0    pypi
qstylizer                 0.2.0                    pypi_0    pypi
qtawesome                 1.0.3                    pypi_0    pypi
qtconsole                 5.1.1                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
rasterio                  1.2.6                    pypi_0    pypi
regex                     2021.7.6                 pypi_0    pypi
requests                  2.25.0             pyhd3eb1b0_0
requests-oauthlib         1.3.0                    pypi_0    pypi
rope                      0.19.0                   pypi_0    pypi
rsa                       4.7.2                    pypi_0    pypi
rtree                     0.9.7                    pypi_0    pypi
ruamel_yaml               0.15.80          py39h2bbff1b_0
scikit-image              0.18.2                   pypi_0    pypi
scipy                     1.7.0                    pypi_0    pypi
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
setuptools                51.0.0           py39haa95532_2
six                       1.15.0           py39haa95532_0
sniffio                   1.2.0            py39hcbf5309_1    conda-forge
snowballstemmer           2.1.0                    pypi_0    pypi
snuggs                    1.4.7                    pypi_0    pypi
sortedcontainers          2.4.0                    pypi_0    pypi
sphinx                    4.1.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
spyder                    5.0.5                    pypi_0    pypi
spyder-kernels            2.0.5                    pypi_0    pypi
sqlite                    3.33.0               h2a8f88b_0
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py39haa95532_0
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                      pypi_0    pypi
textdistance              4.2.1                    pypi_0    pypi
three-merge               0.1.1                    pypi_0    pypi
tifffile                  2021.7.2                 pypi_0    pypi
tinycss2                  1.1.0                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tornado                   6.1              py39hb82d6ee_1    conda-forge
tqdm                      4.54.1             pyhd3eb1b0_0
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                  pypi_0    pypi
tzdata                    2020d                h14c3975_0
ujson                     4.0.2                    pypi_0    pypi
urllib3                   1.25.11                    py_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  2.1.3                    pypi_0    pypi
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.36.1             pyhd3eb1b0_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39h2bbff1b_0
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
yaml                      0.2.5                he774522_0
yapf                      0.31.0                   pypi_0    pypi
zeromq                    4.3.4                h0e60522_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11               h62dcd97_4

**Comment by ccordoba12** [comment]
You have a mix of `defaults`, `conda-forge` and `pip` packages, which is a not a good idea because packages from those different sources are binary incompatible.

Unfortunately, to fix this problem now you need to reinstall Anaconda. Please see the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that properly.

**Comment by falahfakhri-Iraq** [comment]
Dear @ccordoba12 
Unfortunately this complicated the issue, now I couldn't install anaconda, and spyder as well. I got this error while uninstall the miniconda, or anaconda

![image](https://user-images.githubusercontent.com/66899805/126448239-add82b3c-8bd3-4edb-b466-1bc8892e5eea.png)

**Comment by ccordoba12** [comment]
Please post the output of `conda list` again to see how you installed Spyder.

**Comment by falahfakhri-Iraq** [comment]
Dear @ccordoba12 

I really appreciate your patience with me, simultaneously I'm also trying up different solution, 

I have removed everything, and some folders have been removed manually, 

python 3.9.6 under windows os 64 bit has been installed, and then spyder 5.0.5 installed as well, 

conda hasn't been invoked at all, since only pip has been applied to install all the required libraries, 

But still in all the history from the start point so far the problem of restart the kernel, following is the error, 

Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 125, in poll_thread
    self.poll_one()
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 145, in poll_one
    self._comm_close(msg)
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 245, in _comm_close
    self.close(comm_id)
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 105, in close
    return super(FrontendComm, self).close(comm_id)
  File "C:\Users\FALAH FAKHRI\AppData\Local\Programs\Python\Python39\lib\site-packages\spyder_kernels\comms\commbase.py", line 173, in close
    self._comms[comm_id]['comm'].close()
KeyError: '7d8e38e4ead511eb9566645d86e7b048'


Hope to find out the solution of restart kernel,  instead of restarting spyder every now and then.

Many thanks

**Comment by ccordoba12** [comment]
Making Spyder work with a custom installation is even harder than with Anaconda, so we don't support it. I only have one advice for you, that maybe could not work. Please downgrade ipykernel with the following command: `pip install ipykernel==6.0.2`.

If that doesn't work, please use our Windows installer, which is very robust and stable and shouldn't have this problem. You can download it from here:

https://github.com/spyder-ide/spyder/releases

After that, please connect it to your current Python installation by following [this FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) in our docs.

**Comment by falahfakhri-Iraq** [comment]
Hi @ccordoba12 

I have used spyder last version spyder == 5.1.0 , until today, the problem of connecting kernel has occurred again, I found that this version was already yanked, I came back to the last version 5.0.5, I faced again the same problem, but I through out my searching today I found one solution of downgrade the tornado ==4.5.3, which was the already exist, Thus I upgrade tornado ==6.1 and it, works fine now, hopefully to get release the last version of spyder ==5.0.1, which is very light version.

**Comment by ccordoba12** [comment]
Hey @falahfakhri-Iraq, you said

> Thus I upgrade tornado ==6.1 and it, works fine now

I'm glad the kernel is finally working fine for you, thanks to that fix.

> hopefully to get release the last version of spyder ==5.0.1, which is very light version.

Thanks for the suggestion. We'll see if we can include it in a future version.
