### ISSUE TITLE
v5.0.5 fail: `conda install spyder-notebook -c spyder-ide`

### ISSUE THREAD

**Issue by ludwa6** [spyder-ide/spyder#16038]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
...

## Problem Description
Following [this page in docs](https://docs.spyder-ide.org/current/plugins/notebook.html) for instructions, i ran this command in my terminal:
        `conda install spyder-notebook -c spyder-ide` 
Then rebooted Spyder, but the "Notebook" option does not appear at bottom of menu View:Panes as promised.

### What steps reproduce the problem?

1. in Terminal, run `conda update spyder` to ensure latest version (5.0.5)
2. in Terminal, run `conda install spyder-notebook -c spyder-ide` 
3. reboot Spyder
4. check menu /View:Panes to check for "Notebook" item at bottom of menu

### What is the expected output? What do you see instead?
Per step #4 above, according to [this page in docs](https://docs.spyder-ide.org/current/plugins/notebook.html), i should see the item "Notebook" at bottom of that View:Panes menu, but it's not there (last item is "internal Console")

## Versions
* Spyder version: 5.0.5 None
* Python version: 3.8.8 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Darwin 17.7.0

### Dependencies

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.25.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  4.1.1 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by ludwa6** [comment]
PS to my last:  Seeing as how spyder_notebook exists in my running environment, i decided to try `import spyder_notebook` in Spyder's Console, and here's the traceback, in case that helps:

```
import spyder_notebook
Traceback (most recent call last):

  File "/var/folders/hc/46157fbs5t1cscm8c38y3fd80000gn/T/ipykernel_48864/1627363730.py", line 1, in <module>
    import spyder_notebook

  File "/Users/walterludwick/opt/anaconda3/lib/python3.8/site-packages/spyder_notebook/__init__.py", line 11, in <module>
    from spyder_notebook.notebookplugin import NotebookPlugin as PLUGIN_CLASS

  File "/Users/walterludwick/opt/anaconda3/lib/python3.8/site-packages/spyder_notebook/notebookplugin.py", line 26, in <module>
    from spyder.config.main import CONF

ImportError: cannot import name 'CONF' from 'spyder.config.main' (/Users/walterludwick/opt/anaconda3/lib/python3.8/site-packages/spyder/config/main.py)
```

**Comment by ccordoba12** [comment]
Hey @ludwa6, thanks for reporting. Unfortunately, Spyder-notebook is not compatible with Spyder 5 yet. We'll try to update it in the next couple of months.

**Comment by ludwa6** [comment]
Thanks @ccordoba12 : i didn't know about this issue on the spyder-notebook tracker (didn't know it had its own repo, in fact -duh! :-), so i've [posted a link from this one over there](https://github.com/spyder-ide/spyder-notebook/issues/360#issuecomment-882396763).  Am very keen for this fix, so if y'all want a tester when it lands in beta, i'll be happy to serve.  Força, Team Spyder!   /walt
