### ISSUE TITLE
Deactivating code completion leads to loss of menu option and outline explorer

### ISSUE THREAD

**Issue by mluerig** [spyder-ide/spyder#16035]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After a fresh os/anaconda/spyder reinstall I started spyder and deactivated code completion (central option in the menu, forgot how it's called and I can). then, upon reloading spyder, this box was still unchecked, but ALL other code completing and linting options were checked and active. checking and unchecking the central code completion option again inactivated all code completion options. another spyder restart later, the menu section "code completion" is gone, and so is the outline pane - no option/checkbox to bring it back

potentiall related to this? https://github.com/spyder-ide/spyder/issues/15631

### What steps reproduce the problem?

as described above

### What is the expected output? What do you see instead?

as described above

### Paste Traceback/Error Below (if applicable)

```python-traceback

    > spyder
    Pruned plugin: outline_explorer
    Missing requirement: completions
    Restart plugins pruning by REQUIRES check

```

## Versions

* Spyder version:  spyder                    5.0.5            py37haa95532_2
* Python version: python                    3.7.10               h6244533_0
* Qt version:  qt                        5.9.7            vc14h73c81de_0
* PyQt version: pyqt                      5.9.2            py37h6538335_2
* Operating System name/version: win 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @mluerig,

This is a known bug and we are working towards fixing it for our next version, Spyder 5.1.0. If the configuration page is not present in preferences, then code completion should be off. In the case you want to bring it back, you'll need to reset spyder doing `spyder --reset`, it is the only way for now. 

Thanks for reporting!
