### ISSUE TITLE
Showing dpendencies error

### ISSUE THREAD

**Issue by thpnick688** [spyder-ide/spyder#16037]
### What steps will reproduce the problem?

Hi, I have just updated spyder into the latest version 5.0.5. But I receive error message that I need to update jsonschema into 3.2.0. 
I use pip install jsonschema at terminal and the result shows that jsonschema 3.2.0 has alreday installed. 
Yet, if I go to Help -> Dependencies... to check, my jsonschema is still 3.0.1

Please see the below screenshot 
<img width="799" alt="屏幕快照 2021-07-17 下午9 50 25" src="https://user-images.githubusercontent.com/47145936/126083895-4cd1c3a7-06d5-4512-81ef-39920cb0f48d.png">
<img width="873" alt="屏幕快照 2021-07-17 下午9 49 21" src="https://user-images.githubusercontent.com/47145936/126083903-d0310483-ef06-4065-a6ca-d3cc611adb41.png">
<img width="492" alt="屏幕快照 2021-07-17 下午9 48 19" src="https://user-images.githubusercontent.com/47145936/126083908-dc80f9a2-88f0-4c8e-9be3-05cf06b7e6c2.png">

**Comment by ccordoba12** [comment]
Hey @thpnick688, thanks for reporting. To update `jsonschema` you need to run the following command

    pip install --upgrade jsonschema

You were missing the `--upgrade` option.

**Comment by thpnick688** [comment]
Hi @Carlos
     I have tried your way, and the results are the same, The terminal
results show me that I have already installed the latest version of
jsonschema, but spyder doesn't recognize it. The anaconda environment also
shows me that I have installed jsonschema 3.2.0.

**Comment by thpnick688** [comment]
> Hey @thpnick688, thanks for reporting. To update `jsonschema` you need to run the following command
> 
> ```
> pip install --upgrade jsonschema
> ```
> 
> You were missing the `--upgrade` option.

Hi, @ccordoba12. To update, I tried your method by adding `--upgrade` option, it still doesn't solve the problem. Eventually, I removed Anaconda3 completely from my system and reinstalled it. This solves the problem. However, I still don't understand what is the cause of it. Thank you
