### ISSUE TITLE
Enhancement: specify environment in kernel error message

### ISSUE THREAD

**Issue by ntjess** [spyder-ide/spyder#16033]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In keeping with "explicit is better than implicit", I would suggest an enhancement to the error message received when starting an ipython console in a different environment than spyder is installed. Currently the message is

```
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.0.1 and < 2.1.0). Without this module is not possible for Spyder to create a console for you.
```

I assumed "your python environment" had to do with where `spyder` was running, not where the interpreter path was configured. Simply installing `spyder-kernels` into the active environment solved the problem.

### What steps reproduce the problem?
Open an IPython console without `spyder-kernels` installed in that environment

### What is the expected output? What do you see instead?
Error described above occurs, but it would be helpful to explicitly mention the failing environment instead, something like:

```
Python environment `my-env` doesn't have the `spyder-kernels` module...
```

## Versions

* Spyder version: 5.0.5
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

(should be irrelevant for the question)

**Comment by juanis2112** [comment]
@ntjess  thanks for reporting this. This sounds like a good idea! I think we can do this. @ccordoba12 what do you think?

**Comment by dalthviz** [comment]
@ccordoba12 could this be already covered with https://github.com/spyder-ide/spyder/pull/17033 ?

**Comment by ccordoba12** [comment]
Yep, that's correct. Closing this one then.

@ntjess, please update to our latest version (5.3.1) to get the fix for this.
