### ISSUE TITLE
Check Dependencies for spyder 5.0.5

### ISSUE THREAD

**Issue by suipz** [spyder-ide/spyder#16036]
### What steps will reproduce the problem?

After started 5.0.5, the following error message was showed: 

You have missing dependeccies!

Mandatory:
rtree >= 0.9.7

However, it's installed in fact.

**Comment by suipz** [comment]
![20210718_spyderIssue](https://user-images.githubusercontent.com/51112398/126054311-12315a00-5fff-4c71-b19a-85c46324f394.JPG)

**Comment by suipz** [comment]
![image](https://user-images.githubusercontent.com/51112398/126054318-b6d28c92-2268-4ec5-b729-de2be7a69dbf.png)

**Comment by suipz** [comment]
![image](https://user-images.githubusercontent.com/51112398/126054328-ee62af72-356d-4d08-90a6-d29c0d299bca.png)

**Comment by ccordoba12** [comment]
Hey @suipz, thanks for reporting. This is a known issue but it is an installation issue and not a problem with Spyder.

I have a question for you: how did you install Spyder?

**Comment by suipz** [comment]
I used the following command to install it.

**Comment by suipz** [comment]
BTW, when update anaconda, I got the following warning message. I am not sure it's related to this issue.

Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/noarch::decorator-5.0.9-pyhd8ed1ab_0, conda-forge/noarch::networkx-2.3-py_0
  - conda-forge/noarch::decorator-4.4.2-py_0, conda-forge/noarch::networkx-2.6.1-pyhd8ed1abdone

**Comment by ccordoba12** [comment]
Ok, please open the Anaconda Prompt and post the output of the following command here:

    conda list

**Comment by suipz** [comment]
I got the following list of packages installed. 

(py38) C:\Users\***>conda list
# packages in environment at C:\Users\***\AppData\Local\Continuum\anaconda3\envs\py38:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0    anaconda
absl-py                   0.12.0                   pypi_0    pypi
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py38_1
anaconda-client           1.7.2              pyhd8ed1ab_1    conda-forge
anaconda-project          0.10.1             pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               20.1.0           py38h294d835_2    conda-forge
arrow                     1.1.1              pyhd8ed1ab_0    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
astroid                   2.6.2            py38haa244fe_0    conda-forge
astropy                   4.2.1            py38h294d835_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.5.5              pyh44b312d_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
bcrypt                    3.2.0            py38h294d835_1    conda-forge
beautifulsoup4            4.9.3              pyhb0f4dca_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
bitarray                  2.0.1            py38h294d835_0    conda-forge
bkcharts                  0.2                      py38_0    anaconda
black                     21.7b0             pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl    anaconda
bleach                    3.3.1              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.3.3            py38haa244fe_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py38h347fdf6_3    conda-forge
brotlipy                  0.7.0           py38h294d835_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.2                    pypi_0    pypi
certifi                   2021.5.30        py38haa244fe_0    conda-forge
cffi                      1.14.6           py38hd8c33c5_0    conda-forge
chardet                   4.0.0            py38haa244fe_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.1            py38haa244fe_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
comtypes                  1.1.10           py38haa244fe_0    conda-forge
conda-pack                0.6.0              pyhd3deb0d_0    conda-forge
console_shortcut          0.1.1                         4
contextlib2               21.6.0             pyhd8ed1ab_0    conda-forge
cookiecutter              1.6.0                 py38_1000    conda-forge
cryptography              3.4.7            py38hd7da0ea_0    conda-forge
curl                      7.77.0               h789b8ee_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.24          py38h885f38d_0    conda-forge
cytoolz                   0.11.0           py38h294d835_3    conda-forge
dask                      2021.7.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.7.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
debugpy                   1.3.0            py38h885f38d_0    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
distributed               2021.7.0         py38haa244fe_0    conda-forge
docutils                  0.17.1           py38haa244fe_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
enum34                    1.1.10           py38h32f6830_2    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fastcache                 1.1.0            py38h294d835_2    conda-forge
filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
flake8                    3.8.4                      py_0    conda-forge
flask                     2.0.1              pyhd8ed1ab_0    conda-forge
flatbuffers               1.12                     pypi_0    pypi
freetype                  2.10.4               h546665d_1    conda-forge
fsspec                    2021.7.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38haa244fe_3    conda-forge
gast                      0.4.0                    pypi_0    pypi
get_terminal_size         1.0.0                h38e98db_0    anaconda
gevent                    21.1.2           py38h294d835_0    conda-forge
glob2                     0.7                        py_0    conda-forge
gmpy2                     2.1.0b5          py38hb63f22f_0    conda-forge
google-auth               1.30.1                   pypi_0    pypi
google-auth-oauthlib      0.4.4                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
greenlet                  1.1.0            py38h885f38d_0    conda-forge
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1    anaconda
icu                       58.2             vc14hc45fdbb_0  [vc14]  anaconda
idna                      3.1                pyhd3deb0d_0    conda-forge
imagecodecs-lite          2019.12.3        py38h347fdf6_3    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        4.6.1            py38haa244fe_0    conda-forge
importlib_metadata        4.6.1                hd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.0.2            py38h43734a8_0    conda-forge
ipython                   7.25.0           py38h43734a8_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.3              pyhd3deb0d_0    conda-forge
isort                     5.9.2              pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd8ed1ab_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.17.2           py38haa244fe_1    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9b               vc14h4d7706e_1  [vc14]  anaconda
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter                   1.0.0            py38haa244fe_6    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38haa244fe_0    conda-forge
jupyterlab                2.2.0                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    anaconda
jupyterlab_widgets        1.0.0              pyhd8ed1ab_1    conda-forge
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keyring                   23.0.1           py38haa244fe_0    conda-forge
kiwisolver                1.3.1            py38hbd9d945_1    conda-forge
krb5                      1.19.1               hbae68bd_0    conda-forge
lazy-object-proxy         1.6.0            py38h294d835_0    conda-forge
libarchive                3.5.1                h8686738_1    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libcurl                   7.77.0               h789b8ee_0    conda-forge
libiconv                  1.15             vc14h29686d3_5  [vc14]  anaconda
liblapack                 3.9.0                     8_mkl    conda-forge
liblief                   0.11.5               h0e60522_0    conda-forge
libllvm9                  9.0.1                hab3b255_3    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_3    conda-forge
libssh2                   1.9.0                h680486a_6    conda-forge
libtiff                   4.2.0                hd0e1b90_0
libxml2                   2.9.10               hb89e7f3_3    anaconda
libxslt                   1.1.33               h65864e5_2    conda-forge
llvmlite                  0.36.0           py38h57a6900_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.3            py38h292cb97_0    conda-forge
lz4-c                     1.9.3                h8ffe710_0    conda-forge
lzo                       2.10             vc14h0a64fa6_1  [vc14]  anaconda
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1            py38h294d835_0    conda-forge
matplotlib                3.4.2            py38haa244fe_0    conda-forge
matplotlib-base           3.4.2            py38heae8d8c_0    conda-forge
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.17           py38haa244fe_0    conda-forge
mistune                   0.8.4           py38h294d835_1004    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
mkl-service               2.3.0            py38h196d8e1_0
mkl_fft                   1.3.0            py38h347fdf6_1    conda-forge
mkl_random                1.1.1            py38h47e9c7a_0    anaconda
mock                      4.0.3            py38haa244fe_1    conda-forge
more-itertools            8.8.0              pyhd8ed1ab_0    conda-forge
mpc                       1.1.0             h7edee0f_1009    conda-forge
mpfr                      4.0.2                h62dcd97_1    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.2            py38hbd9d945_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
mypy_extensions           0.4.3            py38haa244fe_3    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py38haa244fe_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
networkx                  2.3                        py_0    conda-forge
nltk                      3.6.2              pyhd8ed1ab_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.4.0              pyha770c72_0    conda-forge
numba                     0.53.1           py38h99fac5f_1    conda-forge
numexpr                   2.7.3            py38h4c96930_0    conda-forge
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.18.5           py38hc3f5095_0
numpydoc                  1.1.0                      py_1    conda-forge
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openpyxl                  3.0.7              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1k               h8ffe710_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.0               pyhd8ed1ab_0    conda-forge
pandas                    1.3.0            py38h60cbd38_0    conda-forge
pandoc                    2.14.0.3             h8ffe710_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
paramiko                  2.7.2              pyh9f0ad1d_0    conda-forge
parso                     0.7.0                      py_0
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
path                      16.0.0           py38haa244fe_0    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib                   1.0.1            py38haa244fe_4    conda-forge
pathlib2                  2.3.6            py38haa244fe_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.0            py38hca74424_0    anaconda
pip                       20.2.4                   py38_0    anaconda
pkginfo                   1.7.1              pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py38haa244fe_4    conda-forge
ply                       3.11                       py_1    conda-forge
pooch                     1.4.0              pyhd8ed1ab_0    conda-forge
powershell_shortcut       0.0.1                         3
poyo                      0.5.0                      py_0    conda-forge
prometheus_client         0.11.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.19             pyha770c72_0    conda-forge
prompt_toolkit            3.0.19               hd8ed1ab_0    conda-forge
protobuf                  3.17.2                   pypi_0    pypi
psutil                    5.8.0            py38h294d835_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
py-lief                   0.11.5           py38h885f38d_0    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
pycosat                   0.6.3           py38h294d835_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycurl                    7.43.0.6         py38hdf897c8_1    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0            py38hcb5f9af_0    conda-forge
pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
pygments                  2.9.0              pyhd8ed1ab_0    conda-forge
pylint                    2.9.3              pyhd8ed1ab_0    conda-forge
pyls-black                0.4.6              pyh9f0ad1d_0    conda-forge
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py38h31c79cd_2    conda-forge
pyodbc                    4.0.31           py38h885f38d_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py38ha925a31_4    anaconda
pyreadline                2.1             py38haa244fe_1003    conda-forge
pyrsistent                0.17.3           py38h294d835_2    conda-forge
pysocks                   1.7.1            py38haa244fe_3    conda-forge
pytables                  3.6.1            py38h153c448_3    conda-forge
pytest                    6.2.4            py38haa244fe_0    conda-forge
python                    3.8.10               hdbf39b2_7
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-jsonrpc-server     0.4.0              pyh9f0ad1d_0    conda-forge
python-language-server    0.36.2             pyhd8ed1ab_0    conda-forge
python-libarchive-c       3.1              py38haa244fe_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py38h347fdf6_3    conda-forge
pywin32                   300              py38h294d835_0    conda-forge
pywin32-ctypes            0.2.0           py38haa244fe_1003    conda-forge
pywinpty                  1.1.3            py38hd3f51b4_0    conda-forge
pyyaml                    5.1.2            py38hfa6e2cd_0    conda-forge
pyzmq                     22.1.0           py38h09162b1_0    conda-forge
qdarkstyle                3.0.2              pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.0              pyhd8ed1ab_1    conda-forge
qt                        5.9.7            vc14h73c81de_0  [vc14]  anaconda
qtawesome                 1.0.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.1.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
regex                     2021.7.6         py38h294d835_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
rope                      0.19.0             pyhd8ed1ab_0    conda-forge
rsa                       4.7.2                    pypi_0    pypi
rtree                     0.9.7            py38h8b54edf_1    conda-forge
ruamel_yaml               0.15.87          py38he774522_0    anaconda
scikit-image              0.18.2           py38h60cbd38_0    conda-forge
scikit-learn              0.24.2           py38h5d5d464_0    conda-forge
scipy                     1.7.0            py38he847743_0    conda-forge
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
seaborn-base              0.11.1             pyhd8ed1ab_1    conda-forge
send2trash                1.7.1              pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py38haa244fe_3    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.6.1              pyh44b312d_0    conda-forge
sip                       4.19.25          py38h885f38d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
sortedcollections         2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sphinx                    4.1.1              pyh6c4a22f_0    conda-forge
sphinxcontrib             1.0                      py38_1    anaconda
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_0    conda-forge
sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
spyder                    5.0.5            py38haa244fe_0    conda-forge
spyder-kernels            2.0.5            py38haa244fe_0    conda-forge
sqlalchemy                1.4.21           py38h294d835_0    conda-forge
sqlite                    3.36.0               h8ffe710_0    conda-forge
statsmodels               0.12.2           py38h347fdf6_0    conda-forge
sympy                     1.8              py38haa244fe_0    conda-forge
tbb                       2020.2               h2d74725_4    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.5.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.10.1           py38haa244fe_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
textdistance              4.2.1              pyhd8ed1ab_0    conda-forge
threadpoolctl             2.2.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2019.7.26.2              py38_0    conda-forge
tinycss2                  1.1.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.10               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.0.4              pyhd8ed1ab_0    conda-forge
tomlkit                   0.7.2            py38haa244fe_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h294d835_1    conda-forge
tqdm                      4.61.2             pyhd8ed1ab_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typed-ast                 1.4.3            py38h294d835_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     4.0.2            py38h885f38d_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
watchdog                  0.10.4           py38haa244fe_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
widgetsnbextension        3.5.1            py38haa244fe_4    conda-forge
win_inet_pton             1.1.0            py38haa244fe_2    conda-forge
win_unicode_console       0.5             py38h32f6830_1001    conda-forge
wincertstore              0.2             py38haa244fe_1006    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.12.1           py38h294d835_3    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                1.4.4              pyhd8ed1ab_0    conda-forge
xlwings                   0.24.3           py38haa244fe_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.1.7            vc14h4cb57cf_1  [vc14]  anaconda
yapf                      0.31.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_0    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.5.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda
zope                      1.0                      py38_1    anaconda
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.4.0            py38h294d835_0    conda-forge
zstd                      1.4.9                h6255e5f_0    conda-forge

**Comment by ccordoba12** [comment]
You have a mix of `defaults`, `conda-forge` and `pip` packages in your environment, which is a not a good idea because packages from those different sources are incompatible.

Please recreate your environment by running the following commands

    conda create -n spyder-env -c conda-forge python=3.8 spyder
    conda activate spyder-env
    spyder

and let us know if the error still appears.

**Comment by Kochise** [comment]
> packages from those different sources are incompatible.

My Lord...

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by suipz** [comment]
@ccordoba12 

I am really sorry for the late response.
After created the new env and installed packages from conda-forge only, it's no problem for spyder 5.0.5.
Thanks a lot for your help.
