### ISSUE TITLE
spyder 2.2.5 freezes with netCDF4-python

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1604]
_From [gregoire...@gmail.com](https://code.google.com/u/113056724190589709787/) on 2013-10-14T10:00:45Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 >>> from netCDF4 import Dataset

\>>> d = Dataset(path_to_netcdf,'f') What is the expected output? What do you see instead? The expected output is a netCDF4.Dataset instance. Spyder is freezing. What version of the product are you using? On what operating system? Python 2.7, Spyder 2.2.5 and 2.2.4, netCDF4-python version 1.0.6 on Ubuntu 12.04.3 x64 (VirtualBox). 

Please provide any additional information below

. When spyder is freezing, here is the console output:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/monitor.py", line 571, in run
    self.update_remote_view()
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/monitor.py", line 452, in update_remote_view
    remote_view = make_remote_view(ns, settings, more_excluded_names)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/monitor.py", line 72, in make_remote_view
    more_excluded_names=more_excluded_names)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/externalshell/monitor.py", line 61, in get_remote_data
    excluded_names=excluded_names)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 237, in globalsfilter
    filters=filters))
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 202, in is_supported
    if not is_editable_type(value):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 115, in is_editable_type
    return get_color_name(value) not in (UNSUPPORTED_COLOR, CUSTOM_TYPE_COLOR)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 104, in get_color_name
    np_dtype = get_numpy_dtype(value)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 40, in get_numpy_dtype
    return obj.dtype.type
  File "netCDF4.pyx", line 1850, in netCDF4.Dataset.__getattr__ (netCDF4.c:23759)
KeyError: 'dtype'

Trying the code outside spyder is working well. But in spyder, it freezes.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1604_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T18:16:37Z_

I'll check it out.

**Labels:** Cat-VariableExplorer MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [gregoire...@gmail.com](https://code.google.com/u/113056724190589709787/) on 2013-10-14T22:38:06Z_

FYI, a workaround is to create a class like this:

from netCDF4 import Dataset

\>>> class DDataset()
       def __init__(self,fp):
           self.inputNC = Dataset(fp,('r')

\>>> d = DDataset(path_to_netcdf)

\>>> d.inputNC

\>>> d.inputNC.variables


The above is working well.

Greg

**Comment by spyder-issues-migrator** [comment]
_From [gregoire...@gmail.com](https://code.google.com/u/113056724190589709787/) on 2013-10-31T04:45:18Z_

I just found that spyder is not freezing when I close the Variable explorer window.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T12:52:51Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [char...@allderman.com](https://code.google.com/u/112014818981355098318/) on 2013-12-18T23:41:10Z_

Thank you gregoire...@gmail.com, closing the Variable explorer also works for me. I am running pythonxy 2.7.5.2 on win7.

**Comment by spyder-issues-migrator** [comment]
_From [b3r...@gmail.com](https://code.google.com/u/112948162440843436688/) on 2014-04-21T04:53:21Z_

For me, a call to numpy's function arange() after creating the netcdf file caused Spyder to freeze:

from netCDF4 import Dataset
rootgrp = Dataset('test.nc', 'w', format='NETCDF4')
arange(10)

Closing the variable explorer solved the problem as well for me. I am running Spyder 2.2.5 with Python 2.7 on Ubuntu 12.04. Thanks!

**Comment by spyder-issues-migrator** [comment]
_From [dallas.m...@gmail.com](https://code.google.com/u/110563883795311213368/) on 2014-06-27T08:45:13Z_

Confirm this bug with netCDF4 and the worksaround to close the variable explorer window.

**Comment by spyder-issues-migrator** [comment]
_From [Sigm...@gmail.com](https://code.google.com/u/115381755524459545400/) on 2014-07-14T10:25:56Z_

Thanks for the info was having same issue and would not have linked it to the variable explorer panel.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-07-15T22:44:58Z_

I'm not seeing this freeze in 2.3.0 while using Anaconda. Could anyone update and test again?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-06T10:14:14Z_

I don't know how, but this seems to be fixed in Spyder 2.3 (according to my tests in Win 32 and 64). So please update.

**Status:** Fixed

**Comment by malapradej** [comment]
Gregoires method above using a class works for me, although some things needed to be changed. The `def init(self,fp):` should be `def __init__(self,fp):` and `self.inputNC = Dataset(fp,('r')` should be `self.inputNC = Dataset(fp,'r')` and adding `d = False` at the end of the script.

**Comment by ccordoba12** [comment]
@malapradej, please update to Spyder 2.3.4. I was unable to reproduce this error in that version.
