### ISSUE TITLE
please help i need to make the data read it vertically

### ISSUE THREAD

**Issue by itsjustjavier** [spyder-ide/spyder#16063]
![image](https://user-images.githubusercontent.com/87825410/126679566-8df1b075-d66c-4a60-a8de-56fa1842e1ca.png)
this is the excel 

![image](https://user-images.githubusercontent.com/87825410/126679616-4fff672a-9b92-490c-811f-b5eeb5b40b58.png)
pretty much i need to find a code to make it read the row of dividends vertically but it just read horizontally!

much help needed tyvm! :)

**Comment by ccordoba12** [comment]
Hey @itsjustjavier, thanks for opening this issue. Unfortunately, this a place to report internal problems in Spyder, not to get help about programming issues.

There are better places for that, such as Stackoverflow:

https://stackoverflow.com/
