### ISSUE TITLE
Spyder 5.0.5 Missing Dependencies

### ISSUE THREAD

**Issue by kikiloverafa** [spyder-ide/spyder#16065]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After launching spyder, saw the following error.
![image](https://user-images.githubusercontent.com/9371073/126733578-ec27aeb2-ee90-4ea5-9ebd-d4f9b622edc9.png)

### What steps reproduce the problem?

1. Updating Anaconda to 2021.05 version
2. Updating Python to 3.8.5
3. Updating spyder to 5.0.5

### What is the expected output? What do you see instead?
In anaconda command prompt, pip shows that jedi, parso are installed (correct version). For pyls, I'm unable to get 0.36.2 installed. Also, I found that pip and conda shows different version of jedi and parso. Why is spyder not detecting the versions shown in pip list?
![image](https://user-images.githubusercontent.com/9371073/126733823-b6462f9d-e8b5-4c72-bb23-2b1a4ae09a40.png)
![image](https://user-images.githubusercontent.com/9371073/126733867-a0972f37-7055-4534-b8ac-d2b3d9a84c14.png)
![image](https://user-images.githubusercontent.com/9371073/126734818-969ef2a2-3b68-4f93-8ac5-73a5eda5fde9.png)
![image](https://user-images.githubusercontent.com/9371073/126734864-47dd1068-4c5d-4d65-a1c3-78bbdbcbd716.png)

## Versions

* Spyder version: 5.0.5
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: windows 10 19042.1110

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  None (NOK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.5.2 (NOK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.31.7 (NOK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by ccordoba12** [comment]
Hey @kikiloverafa, it seems you're mixing pip and conda packages in your environment, which is not good because those packages are incompatible.

The only way to solve this problem is by reinstalling Anaconda. Please follow the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to understand how to properly do that.

In the future, please avoid installing packages with pip as much as you can, and only update Spyder using conda.

**Comment by ccordoba12** [comment]
Another thing I forgot to mention is that if you encounter similar problems in the future, you could use our Windows installer instead:

https://github.com/spyder-ide/spyder/releases

That's self-contained, so it's not possible to break or corrupt it. After installing it, you can connect it to your Anaconda installation by following the instructions described in [our FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer).
