### ISSUE TITLE
Spyder Network Interruptions

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1607]
_From [SexyPant...@gmail.com](https://code.google.com/u/113427216918732013272/) on 2013-10-14T21:39:04Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Starting Spyder on a Windows platform while using wireless. What is the expected output? What do you see instead? Expected output is normal operation of network services. Said services suffer occasional interruption. What version of the product are you using? On what operating system? Latest as provided by Python(x,y) 

Please provide any additional information below

. Traced problem to a thread that Spyder was running: "wlanapi". Why does Spyder need wireless networking access? Is it snooping channels without user permissions?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1607_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-29T09:55:17Z_

We just need to open sockets for interprocess communication.

**Status:** WontFix

**Comment by spyder-issues-migrator** [comment]
_From [SexyPant...@gmail.com](https://code.google.com/u/113427216918732013272/) on 2014-10-29T16:04:20Z_

It's been over a year, the problem still persists with intermittent network interruptions due to the access of 'wlanapi'.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T11:27:20Z_

Sorry about the problems but we don't access wlanapi directly. Maybe it's an issue with Python and its sockets implementation.

It's really out of our hands...

**Comment by Searinox** [comment]
Another occurrence on my side. I have two machines and oddly it's only happening on one machine. What is happening is that while Spyder is running, the program triggers the WiFi network scan every 10 seconds, and that causes large spikes ~800ms. Process Monitor is showing that the main python.exe instance is polling several things including HKLM\SYSTEM\CurrentControlSet\services\TCPIP and TCPIP6 \Interfaces and triggering WiFi network scans.
