### ISSUE TITLE
Don't display hovers on strings, comments or objects without docstrings

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#16079]
When I move my array it shows the following descriotion for each part of the code.

![image](https://user-images.githubusercontent.com/62394093/126927046-15f80a45-cedd-4d49-9dc6-fb0c5cd00f6f.png)

How can I disable it?

**Comment by ccordoba12** [comment]
Hey @seyeeet, thanks for reporting. This is a bug because we shouldn't try to display that information (which is called a hover in Spyder) on strings or comments.

We'll fix it in our next version (5.1.0), to be released at the end of the month.
