### ISSUE TITLE
Can't delete variable

### ISSUE THREAD

**Issue by Mike100000** [spyder-ide/spyder#16072]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Can't remove variable in Python after trying to create variable name of type integer.

**Comment by ccordoba12** [comment]
Hey @Mike100000, thanks for reporting. I have two questions for you to start with:

* What's your Spyder version? You can check that in the menu `Help > About Spyder`.
* How did you install it (Anaconda, pip or our Window or Mac installer)?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
