### ISSUE TITLE
How can I save and load the spydata file with the code?

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#16076]
I want to save and load the workspace data. But I only can load and save by hand, and I don't know how to do that with the python code. How can I do?

## Versions

* Spyder version:  5.0.5
* Python version: 3.9.5
* Qt version: 1.9.0
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @Vincent0706, thanks for reporting. Please see issue #13601 for an explanation on how to do that.
