### ISSUE TITLE
[15148:20872:0725/203653.969:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

### ISSUE THREAD

**Issue by besbesmany** [spyder-ide/spyder#16077]
I failed to open spyder from anaconda or from start up menu
I uninstall antivirus and open firewall but not working
I rest spyder from cmd and from start menu
also delete .spyder folder from user/.spyder

I update spyder and anaconda and try alot of codes
`conda uninstall pyqt`
`conda uninstall sip`

`conda install sip`
`conda install pyqt`
`conda upgrade spyder`

what should I do exactly to open spyder 

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by besbesmany** [comment]
any help please I want to run spyder

**Comment by ccordoba12** [comment]
Hey @besbesmany, thanks for reporting. I have a couple of questions for you:

* Do you have a VPN in your computer?
* What is your Windows version?

**Comment by besbesmany** [comment]
thank you sir for reply
I don't have VPN 
I have laptop with windows 10 home version 20H2
connected wireless with my home router

I had mcafee but I remove it

**Comment by ccordoba12** [comment]
Ok, then please open the Anaconda Prompt, run the following command there

    conda list

and post the output here.

**Comment by besbesmany** [comment]
(gpum) C:\Users\legion>conda list
# packages in environment at C:\Users\legion\.conda\envs\gpum:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                     eigen
absl-py                   0.13.0           py38haa95532_0
aiohttp                   3.7.4            py38h2bbff1b_1
alabaster                 0.7.12             pyhd3eb1b0_0
anyio                     2.2.0            py38haa95532_2
appdirs                   1.4.4                      py_0
argh                      0.26.2                   py38_0
argon2-cffi               20.1.0           py38h2bbff1b_1
arrow                     0.13.1                   py38_0
astor                     0.8.1            py38haa95532_0
astroid                   2.6.5            py38haa95532_0
astunparse                1.6.3                      py_0
async-timeout             3.0.1            py38haa95532_0
async_generator           1.10               pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     21.2.0             pyhd3eb1b0_0
autopep8                  1.5.6              pyhd3eb1b0_0
awscli                    1.20.5                   pypi_0    pypi
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
bcrypt                    3.2.0            py38he774522_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     19.10b0                    py_0
blas                      1.0                         mkl
bleach                    3.3.1              pyhd3eb1b0_0
blinker                   1.4              py38haa95532_0
botocore                  1.21.5                   pypi_0    pypi
brotlipy                  0.7.0           py38h2bbff1b_1003
ca-certificates           2021.7.5             haa95532_1
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2021.5.30        py38haa95532_0
cffi                      1.14.6           py38h2bbff1b_0
chardet                   3.0.4           py38haa95532_1003
click                     8.0.1              pyhd3eb1b0_0
cloudpickle               1.6.0                      py_0
colorama                  0.4.3                    pypi_0    pypi
configparser              5.0.2                    pypi_0    pypi
console_shortcut          0.1.1                         4
cookiecutter              1.7.2              pyhd3eb1b0_0
coverage                  5.5              py38h2bbff1b_2
cryptography              3.4.7            py38h71e12ea_0
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24          py38hd77b12b_0
decorator                 5.0.9              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713                   py_0
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3                      py38_0
flake8                    3.9.0              pyhd3eb1b0_0
future                    0.18.2                   py38_1
gast                      0.4.0                      py_0
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.18                   pypi_0    pypi
google-auth               1.33.0             pyhd3eb1b0_0
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
google-pasta              0.2.0                      py_0
grpcio                    1.36.1           py38hc60d5dd_1
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10               pyhd3eb1b0_0
imagesize                 1.2.0              pyhd3eb1b0_0
importlib-metadata        3.10.0           py38haa95532_0
importlib_metadata        3.10.0               hd3eb1b0_0
inflection                0.5.1            py38haa95532_0
intel-openmp              2021.3.0          haa95532_3372
intervaltree              3.1.0                      py_0
ipykernel                 5.3.4            py38h5ca1d4c_0
ipython                   7.22.0           py38hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
isort                     5.9.2              pyhd3eb1b0_0
jedi                      0.17.2           py38haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_2
jmespath                  0.10.0                   pypi_0    pypi
jpeg                      9b                   hb83a4c4_2
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                3.2.0                      py_2
jupyter-packaging         0.7.12             pyhd3eb1b0_0
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.7.1            py38haa95532_0
jupyter_server            1.4.1            py38haa95532_0
jupyterlab                3.0.14             pyhd3eb1b0_1
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.6.1              pyhd3eb1b0_0
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.2              pyhd3eb1b0_0
keyring                   23.0.1           py38haa95532_0
kiwisolver                1.3.1                    pypi_0    pypi
lazy-object-proxy         1.6.0            py38h2bbff1b_0
libiconv                  1.15             vc14h29686d3_5  [vc14]  anaconda
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.17.2               h23ce68f_1
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libxml2                   2.9.12               h0ad7f3c_0
libxslt                   1.1.34               he774522_0
lxml                      4.6.3            py38h9b66d53_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markdown                  3.3.4            py38haa95532_0
markupsafe                1.1.1            py38he774522_0
matplotlib                3.4.2                    pypi_0    pypi
mccabe                    0.6.1                    py38_1
mistune                   0.8.4           py38he774522_1000
mkl                       2021.3.0           haa95532_524
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.0            py38h277e83a_2
mkl_random                1.2.2            py38hf11a4ad_0
msys2-conda-epoch         20160418                      1
multidict                 5.1.0            py38h2bbff1b_2
mypy_extensions           0.4.3                    py38_0
nbclassic                 0.2.6              pyhd3eb1b0_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.1.0            py38haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
notebook                  6.4.0            py38haa95532_0
numpy                     1.21.1                   pypi_0    pypi
numpy-base                1.20.3           py38hc2deb75_0
numpydoc                  1.1.0              pyhd3eb1b0_1
oauthlib                  3.1.1              pyhd3eb1b0_0
opencv-python             4.5.3.56                 pypi_0    pypi
openssl                   1.1.1k               h2bbff1b_0
opt_einsum                3.3.0              pyhd3eb1b0_1
packaging                 21.0               pyhd3eb1b0_0
pandas                    1.3.0                    pypi_0    pypi
pandocfilters             1.4.3            py38haa95532_1
paramiko                  2.7.2                      py_0
parso                     0.7.0                      py_0
pathspec                  0.7.0                      py_0
pathtools                 0.1.2                    pypi_0    pypi
peppercorn                0.6                      pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.3.1                    pypi_0    pypi
pip                       21.1.3           py38haa95532_0
pluggy                    0.13.1           py38haa95532_0
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.11.0             pyhd3eb1b0_0
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.17             pyh06a4308_0
protobuf                  3.17.2           py38hd77b12b_0
psutil                    5.8.0            py38h2bbff1b_1
ptyprocess                0.7.0              pyhd3eb1b0_2
pyasn1                    0.4.8                      py_0
pyasn1-modules            0.2.8                      py_0
pycodestyle               2.6.0              pyhd3eb1b0_0
pycparser                 2.20                       py_2
pydocstyle                6.1.1              pyhd3eb1b0_0
pyflakes                  2.2.0              pyhd3eb1b0_0
pygments                  2.9.0              pyhd3eb1b0_0
pyjwt                     2.1.0            py38haa95532_0
pylint                    2.9.5            py38haa95532_1
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.4.0            py38h62dcd97_1
pyopenssl                 20.0.1             pyhd3eb1b0_1
pyparsing                 2.4.7              pyhd3eb1b0_0
pyqt                      5.9.2            py38ha925a31_4
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyreadline                2.1                      py38_1
pyrsistent                0.17.3           py38he774522_0
pysocks                   1.7.1            py38haa95532_0
python                    3.8.10               hdbf39b2_7
python-dateutil           2.8.2              pyhd3eb1b0_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-slugify            5.0.2              pyhd3eb1b0_0
pytz                      2021.1             pyhd3eb1b0_0
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
pywinpty                  0.5.7                    py38_0
pyyaml                    5.4.1            py38h2bbff1b_1
pyzmq                     20.0.0           py38hd77b12b_1
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.2              pyhd3eb1b0_0
qtconsole                 5.1.0              pyhd3eb1b0_0
qtpy                      1.9.0                      py_0
regex                     2021.7.6         py38h2bbff1b_0
requests                  2.25.1             pyhd3eb1b0_0
requests-oauthlib         1.3.0                      py_0
rope                      0.19.0             pyhd3eb1b0_0
rsa                       4.7.2              pyhd3eb1b0_1
rtree                     0.9.7            py38h2eaa2aa_1
s3transfer                0.5.0                    pypi_0    pypi
scipy                     1.7.0                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
send2trash                1.5.0              pyhd3eb1b0_1
sentry-sdk                1.3.0                    pypi_0    pypi
setuptools                52.0.0           py38haa95532_0
shortuuid                 1.0.1                    pypi_0    pypi
sip                       4.19.13          py38ha925a31_0
six                       1.16.0             pyhd3eb1b0_0
smmap                     4.0.0                    pypi_0    pypi
sniffio                   1.2.0            py38haa95532_1
snowballstemmer           2.1.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
sphinx                    4.0.2              pyhd3eb1b0_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.0.5            py38haa95532_2
spyder-kernels            2.0.5            py38haa95532_0
sqlite                    3.36.0               h2bbff1b_0
subprocess32              3.5.4                    pypi_0    pypi
tensorboard               2.4.0              pyhc547734_0
tensorboard-plugin-wit    1.6.0                      py_0
tensorflow                2.3.0           mkl_py38h8c0d9a2_0
tensorflow-base           2.3.0           eigen_py38h75a453f_0
tensorflow-estimator      2.5.0              pyh7b7c402_0
termcolor                 1.1.0            py38haa95532_1
terminado                 0.9.4            py38haa95532_0
testpath                  0.5.0              pyhd3eb1b0_0
text-unidecode            1.3                        py_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss                   0.4             pyhd3eb1b0_1002
toml                      0.10.2             pyhd3eb1b0_0
torch                     1.8.1                    pypi_0    pypi
torch-nightly             1.0.0.dev20190325          pypi_0    pypi
torchvision               0.9.1                    pypi_0    pypi
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.61.2                   pypi_0    pypi
traitlets                 5.0.5              pyhd3eb1b0_0
typed-ast                 1.4.3            py38h2bbff1b_1
typing-extensions         3.10.0.0             hd3eb1b0_0
typing_extensions         3.10.0.0           pyh06a4308_0
ujson                     4.0.2            py38hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.6             pyhd3eb1b0_1
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wandb                     0.11.0                   pypi_0    pypi
watchdog                  1.0.2            py38haa95532_1
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py38_1
werkzeug                  1.0.1              pyhd3eb1b0_0
wheel                     0.36.2             pyhd3eb1b0_0
whichcraft                0.6.1              pyhd3eb1b0_0
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2                      py38_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py38he774522_1
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
yarl                      1.6.3            py38h2bbff1b_0
zeromq                    4.3.3                ha925a31_3
zipp                      3.5.0              pyhd3eb1b0_0
zlib                      1.2.11               h62dcd97_4

(gpum) C:\Users\legion>

**Comment by besbesmany** [comment]
![1](https://user-images.githubusercontent.com/35992924/127035557-aaac6075-998a-40c6-9073-9a301fb2cfed.png)

**Comment by ccordoba12** [comment]
You have a mix of pip and conda packages in your environment, which is really bad because packages from those sources are incompatible.

Please download and install Spyder using our Windows installer, which you can download from here:

https://github.com/spyder-ide/spyder/releases

Then connect it to your `gpum` environment by following the instructions in [our FAQ](https://docs.spyder-ide.org/5/faq.html#using-packages-installer). That should solve your problem.

**Comment by besbesmany** [comment]
I installed spyder 5.05 for windows
It lunches the green window till this image then nothing open after that
what should I do please help

![3](https://user-images.githubusercontent.com/35992924/127191535-5fd968ad-f3aa-4358-b158-a685ef37b477.png)

**Comment by ccordoba12** [comment]
Ok, then please open the Anaconda Prompt and create a clean environment with Spyder

    conda create -n spyder-env python=3.8 spyder
    conda activate spyder-env
    spyder

If Spyder still hangs, press `Ctrl+C` in the console. That should generate an error that you can paste here to see what's happening in your case.

**Comment by besbesmany** [comment]
it stoped at the same green window I show before
no error generated

![1](https://user-images.githubusercontent.com/35992924/127322848-8150b206-8d22-44b4-990e-2ae4f4605e8d.png)

**Comment by ccordoba12** [comment]
This is definitely a problem with your computer. Probably the firewall that comes with Windows is blocking inter-process communications and that's what's causing the errors in Spyder and Jupyter.

**Comment by besbesmany** [comment]
if I reinstall anaconda this will solve problems?

**Comment by ccordoba12** [comment]
Perhaps, but I'm not really sure. However, that's your next option before digging into the Windows firewall.

**Comment by laza2** [comment]
I have experienced the same problem recently. Reinstalling anaconda did not work for me. What did work was just resetting preferences  with:

```
spyder --reset
```

and then running Spyder again. I don't know why it fixed it but everything is working fine now. 
If it means something, this problem occurred after installing Windows 10 2021-07 20H2 update.

**Comment by ccordoba12** [comment]
Thanks a lot for chiming in @laza2!

@besbesmany, plesae let us know if that works for you.

**Comment by besbesmany** [comment]
Hello Sir 
Thank you for your help and time with me
I reinstalled windows , everything is fine now
i think the problem form enabling opencv tensorflow gpu then trying to enable pytorch gpu 
they both conflict my laptop

**Comment by ccordoba12** [comment]
Ok, I'm really glad you were able to solve this problem.
