### ISSUE TITLE
Kernel needs version 2.0.5 as interpreter path is using Python 3.9.6 (but issue to install kernel)

### ISSUE THREAD

**Issue by vernhow** [spyder-ide/spyder#16083]
### Issue Report Checklist

* [ Y ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ Y ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ Y ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ Y ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ Y ] Tried basic troubleshooting (if a bug/error)
    * [ Y  ] Restarted Spyder
    * [ Y ] Reset preferences with ``spyder --reset``
    * [ N ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ Y ] Tried the other applicable steps from the Troubleshooting Guide
* [ Y ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

![image](https://user-images.githubusercontent.com/20274116/127007539-592ea8b6-d72a-4c45-8da2-7bc037ffc144.png)
![image](https://user-images.githubusercontent.com/20274116/127007636-dd33a0b9-5beb-49f6-8cab-d52ed0a2fe1b.png)
## Problem Description
Spyder 5 needed kernel version 2.0.5 pip-installed before being able to use Python 3.9.6 within the IDE. However, during the pip install of the required path. am unable to perform the pip due to SSL error. There are instantly 2 layers of error of which I believe the 1st layer can be fixed. But I need help on the pip install error based on the SSL codes as mentioned below. I can still operate on the default but I don't think its ideal since I'd like to use Python 3.9

### What steps reproduce the problem?

1. Minimise Spyder, go into intended directory <user>/AppData/Local/Programs/Python/Python39
2. execute command in GitBash: _pip install spyder-kernels==2.0.5_ 
3. see error as below: 

```
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))': /simple/spyder-kernels/
Could not fetch URL https://pypi.org/simple/spyder-kernels/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/spyder-kernels/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)'))) - skipping
```
### What is the expected output? What do you see instead?
The expected output would be that the installed kernel package was done successfully. Instead, could not execute the pip install. I see error as described in screenshot instead and per the error since. 

![image](https://user-images.githubusercontent.com/20274116/127009494-c26b7f82-76c3-4ebe-ae46-3c74769908a2.png)

Initial Error for the interpreter is below: 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.0.1 and < 2.1.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels=2.0

or

pip install spyder‑kernels==2.0.*

```

## Versions

* Spyder version: 5.0.5 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.24.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.7 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.0.0 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.4 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.2 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.23 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.2.5 (OK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by ccordoba12** [comment]
Hey @vernhow, thanks for reporting. You said

> Instead, could not execute the pip install. I see error as described in screenshot instead and per the error since.

This is not a problem with Spyder but with pip. Here you can find a way to work around it:

https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi

However, if you still have this problem, please open a question StackOverflow or an issue on pip:

https://github.com/pypa/pip
