### ISSUE TITLE
Failed to build arch

### ISSUE THREAD

**Issue by shuo1990** [spyder-ide/spyder#16089]
### What steps will reproduce the problem?

  ERROR: Failed building wheel for arch
Failed to build arch
ERROR: Could not build wheels for arch which use PEP 517 and cannot be installed directly
WARNING: Ignoring invalid distribution -illow (c:\users\shuo zhang\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\shuo zhang\anaconda3\lib\site-packages)

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.5
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.19.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.2 (OK)
pygments >=2.0                 :  2.7.2 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  1.0.1 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.3.2 (OK)
numpy >=1.7                    :  1.21.1 (OK)
pandas >=0.13.1                :  1.2.5 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.6.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @shuo1990, thanks for reporting. Could you let us know how you got the error above?

It's unclear to me how this is related to Spyder.

**Comment by shuo1990** [comment]
Hi, Carlos.

When I supposed to install 'arch' package by pip3 install arch.

The error message is shown as followed:

 Building wheel for arch (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\shuo zhang\anaconda3\python.exe' 'c:\users\shuo zhang\anaconda3\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\SHUOZH~1\AppData\Local\Temp\tmpd7fz6h0r'
       cwd: C:\Users\Shuo Zhang\AppData\Local\Temp\pip-install-r39vo2z4\arch_4ae45e77dabc4cd492f811fe711777b5
  Complete output (142 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\arch
  copying arch\conftest.py -> build\lib.win-amd64-3.8\arch
  copying arch\typing.py -> build\lib.win-amd64-3.8\arch
  copying arch\_version.py -> build\lib.win-amd64-3.8\arch
  copying arch\__init__.py -> build\lib.win-amd64-3.8\arch
  creating build\lib.win-amd64-3.8\arch\bootstrap
  copying arch\bootstrap\base.py -> build\lib.win-amd64-3.8\arch\bootstrap
  copying arch\bootstrap\multiple_comparison.py -> build\lib.win-amd64-3.8\arch\bootstrap
  copying arch\bootstrap\_samplers_python.py -> build\lib.win-amd64-3.8\arch\bootstrap
  copying arch\bootstrap\__init__.py -> build\lib.win-amd64-3.8\arch\bootstrap
  creating build\lib.win-amd64-3.8\arch\compat
  copying arch\compat\numba.py -> build\lib.win-amd64-3.8\arch\compat
  copying arch\compat\pandas.py -> build\lib.win-amd64-3.8\arch\compat
  copying arch\compat\statsmodels.py -> build\lib.win-amd64-3.8\arch\compat
  copying arch\compat\__init__.py -> build\lib.win-amd64-3.8\arch\compat
  creating build\lib.win-amd64-3.8\arch\covariance
  copying arch\covariance\kernel.py -> build\lib.win-amd64-3.8\arch\covariance
  copying arch\covariance\__init__.py -> build\lib.win-amd64-3.8\arch\covariance
  creating build\lib.win-amd64-3.8\arch\data
  copying arch\data\utility.py -> build\lib.win-amd64-3.8\arch\data
  copying arch\data\__init__.py -> build\lib.win-amd64-3.8\arch\data
  creating build\lib.win-amd64-3.8\arch\tests
  copying arch\tests\test_compat.py -> build\lib.win-amd64-3.8\arch\tests
  copying arch\tests\test_data.py -> build\lib.win-amd64-3.8\arch\tests
  copying arch\tests\test_examples.py -> build\lib.win-amd64-3.8\arch\tests
  copying arch\tests\test_tester.py -> build\lib.win-amd64-3.8\arch\tests
  copying arch\tests\__init__.py -> build\lib.win-amd64-3.8\arch\tests
  creating build\lib.win-amd64-3.8\arch\unitroot
  copying arch\unitroot\cointegration.py -> build\lib.win-amd64-3.8\arch\unitroot
  copying arch\unitroot\unitroot.py -> build\lib.win-amd64-3.8\arch\unitroot
  copying arch\unitroot\_engle_granger.py -> build\lib.win-amd64-3.8\arch\unitroot
  copying arch\unitroot\_phillips_ouliaris.py -> build\lib.win-amd64-3.8\arch\unitroot
  copying arch\unitroot\_shared.py -> build\lib.win-amd64-3.8\arch\unitroot
  copying arch\unitroot\__init__.py -> build\lib.win-amd64-3.8\arch\unitroot
  creating build\lib.win-amd64-3.8\arch\univariate
  copying arch\univariate\base.py -> build\lib.win-amd64-3.8\arch\univariate
  copying arch\univariate\distribution.py -> build\lib.win-amd64-3.8\arch\univariate
  copying arch\univariate\mean.py -> build\lib.win-amd64-3.8\arch\univariate
  copying arch\univariate\recursions_python.py -> build\lib.win-amd64-3.8\arch\univariate
  copying arch\univariate\volatility.py -> build\lib.win-amd64-3.8\arch\univariate
  copying arch\univariate\__init__.py -> build\lib.win-amd64-3.8\arch\univariate
  creating build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\array.py -> build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\cov.py -> build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\exceptions.py -> build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\io.py -> build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\testing.py -> build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\timeseries.py -> build\lib.win-amd64-3.8\arch\utility
  copying arch\utility\__init__.py -> build\lib.win-amd64-3.8\arch\utility
  creating build\lib.win-amd64-3.8\arch\vendor
  copying arch\vendor\property_cached.py -> build\lib.win-amd64-3.8\arch\vendor
  copying arch\vendor\__init__.py -> build\lib.win-amd64-3.8\arch\vendor
  creating build\lib.win-amd64-3.8\arch\__future__
  copying arch\__future__\reindexing.py -> build\lib.win-amd64-3.8\arch\__future__
  copying arch\__future__\_utility.py -> build\lib.win-amd64-3.8\arch\__future__
  copying arch\__future__\__init__.py -> build\lib.win-amd64-3.8\arch\__future__
  creating build\lib.win-amd64-3.8\arch\data\binary
  copying arch\data\binary\__init__.py -> build\lib.win-amd64-3.8\arch\data\binary
  creating build\lib.win-amd64-3.8\arch\data\core_cpi
  copying arch\data\core_cpi\__init__.py -> build\lib.win-amd64-3.8\arch\data\core_cpi
  creating build\lib.win-amd64-3.8\arch\data\crude
  copying arch\data\crude\__init__.py -> build\lib.win-amd64-3.8\arch\data\crude
  creating build\lib.win-amd64-3.8\arch\data\default
  copying arch\data\default\__init__.py -> build\lib.win-amd64-3.8\arch\data\default
  creating build\lib.win-amd64-3.8\arch\data\frenchdata
  copying arch\data\frenchdata\__init__.py -> build\lib.win-amd64-3.8\arch\data\frenchdata
  creating build\lib.win-amd64-3.8\arch\data\nasdaq
  copying arch\data\nasdaq\__init__.py -> build\lib.win-amd64-3.8\arch\data\nasdaq
  creating build\lib.win-amd64-3.8\arch\data\sp500
  copying arch\data\sp500\__init__.py -> build\lib.win-amd64-3.8\arch\data\sp500
  creating build\lib.win-amd64-3.8\arch\data\vix
  copying arch\data\vix\__init__.py -> build\lib.win-amd64-3.8\arch\data\vix
  creating build\lib.win-amd64-3.8\arch\data\wti
  copying arch\data\wti\__init__.py -> build\lib.win-amd64-3.8\arch\data\wti
  creating build\lib.win-amd64-3.8\arch\tests\bootstrap
  copying arch\tests\bootstrap\test_block_length.py -> build\lib.win-amd64-3.8\arch\tests\bootstrap
  copying arch\tests\bootstrap\test_bootstrap.py -> build\lib.win-amd64-3.8\arch\tests\bootstrap
  copying arch\tests\bootstrap\test_multiple_comparison.py -> build\lib.win-amd64-3.8\arch\tests\bootstrap
  copying arch\tests\bootstrap\__init__.py -> build\lib.win-amd64-3.8\arch\tests\bootstrap
  creating build\lib.win-amd64-3.8\arch\tests\covariance
  copying arch\tests\covariance\test_covariance.py -> build\lib.win-amd64-3.8\arch\tests\covariance
  copying arch\tests\covariance\__init__.py -> build\lib.win-amd64-3.8\arch\tests\covariance
  creating build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\cointegration_data.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\test_dynamic_ols.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\test_engle_granger.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\test_fmols_ccr.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\test_phillips_ouliaris.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\test_unitroot.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  copying arch\tests\unitroot\__init__.py -> build\lib.win-amd64-3.8\arch\tests\unitroot
  creating build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_arch_in_mean.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_base.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_distribution.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_forecast.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_mean.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_moment.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_recursions.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_rescale.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_variance_forecasting.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\test_volatility.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  copying arch\tests\univariate\__init__.py -> build\lib.win-amd64-3.8\arch\tests\univariate
  creating build\lib.win-amd64-3.8\arch\tests\utility
  copying arch\tests\utility\test_array.py -> build\lib.win-amd64-3.8\arch\tests\utility
  copying arch\tests\utility\test_cov.py -> build\lib.win-amd64-3.8\arch\tests\utility
  copying arch\tests\utility\test_io.py -> build\lib.win-amd64-3.8\arch\tests\utility
  copying arch\tests\utility\test_timeseries.py -> build\lib.win-amd64-3.8\arch\tests\utility
  copying arch\tests\utility\test_utility.py -> build\lib.win-amd64-3.8\arch\tests\utility
  copying arch\tests\utility\__init__.py -> build\lib.win-amd64-3.8\arch\tests\utility
  creating build\lib.win-amd64-3.8\arch\tests\unitroot\data
  copying arch\tests\unitroot\data\__init__.py -> build\lib.win-amd64-3.8\arch\tests\unitroot\data
  creating build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\dfgls.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\dickey_fuller.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\engle_granger.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\kpss.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\phillips_ouliaris.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\zivot_andrews.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\unitroot\critical_values\__init__.py -> build\lib.win-amd64-3.8\arch\unitroot\critical_values
  copying arch\py.typed -> build\lib.win-amd64-3.8\arch
  copying arch\data\binary\binary.csv.gz -> build\lib.win-amd64-3.8\arch\data\binary
  copying arch\data\core_cpi\core-cpi.csv.gz -> build\lib.win-amd64-3.8\arch\data\core_cpi
  copying arch\data\crude\crude.csv.gz -> build\lib.win-amd64-3.8\arch\data\crude
  copying arch\data\default\default.csv.gz -> build\lib.win-amd64-3.8\arch\data\default
  copying arch\data\frenchdata\frenchdata.csv.gz -> build\lib.win-amd64-3.8\arch\data\frenchdata
  copying arch\data\nasdaq\nasdaq.csv.gz -> build\lib.win-amd64-3.8\arch\data\nasdaq
  copying arch\data\sp500\sp500.csv.gz -> build\lib.win-amd64-3.8\arch\data\sp500
  copying arch\data\vix\vix.csv.gz -> build\lib.win-amd64-3.8\arch\data\vix
  copying arch\data\wti\wti.csv.gz -> build\lib.win-amd64-3.8\arch\data\wti
  copying arch\tests\unitroot\data\zivot-andrews.csv -> build\lib.win-amd64-3.8\arch\tests\unitroot\data
  UPDATING build\lib.win-amd64-3.8\arch/_version.py
  set build\lib.win-amd64-3.8\arch/_version.py to '5.0.1'
  running build_ext
  building 'arch.univariate.recursions' extension
  C:\Users\Shuo Zhang\AppData\Local\Temp\pip-build-env-hrqj1hju\overlay\Lib\site-packages\setuptools\dist.py:697: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for arch
Failed to build arch
ERROR: Could not build wheels for arch which use PEP 517 and cannot be installed directly
WARNING: Ignoring invalid distribution -illow (c:\users\shuo zhang\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\shuo zhang\anaconda3\lib\site-packages)

Kind regards,

Shuo


This email originated from TU Dublin. If you received this email in error, please delete it from your system. Please note that if you are not the named addressee, disclosing, copying, distributing or taking any action based on the contents of this email or attachments is prohibited.

Is ó OT Baile Átha Cliath a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa ríomhphost nó sna hiatáin seo.

________________________________

**Comment by ccordoba12** [comment]
Ok, I understand your problem now. The thing is there are no Arch packages for Python 3.8 and Window 64-bit, so that's why pip tries to build it, as you can see here:

https://pypi.org/project/arch/#files

Please inform the Arch developers about that (it was probably something they missed):

https://github.com/bashtage/arch

To solve it in the meantime, please install Arch in another environment with Python 3.9. To do that, please close Spyder, open the Anaconda Prompt and run the following commands:

    conda create -n py39 python=3.9 spyder-kernels numpy scipy pandas statsmodels
    conda activate py39
    pip install arch

After that, please follow the instructions in [our FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) to connect that env to Spyder.

Let us know if that works for you.

**Comment by shuo1990** [comment]
Hi, Carlos.

Thank you. I installed it. But the 'arch' package cannot be imported. The code was as followed with errors:

from arch import arch_model
Traceback (most recent call last):

  File "<ipython-input-1-f7e7e7ccf968>", line 1, in <module>
    from arch import arch_model

ModuleNotFoundError: No module named 'arch'

Kind regards,

Shuo


This email originated from TU Dublin. If you received this email in error, please delete it from your system. Please note that if you are not the named addressee, disclosing, copying, distributing or taking any action based on the contents of this email or attachments is prohibited.

Is ó OT Baile Átha Cliath a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa ríomhphost nó sna hiatáin seo.

________________________________

**Comment by ccordoba12** [comment]
I'm glad that you were finally able to install it. About the failure to import it, did you follow the instructions I mentioned in this sentence?

> After that, please follow the instructions in [our FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) to connect that env to Spyder.

**Comment by shuo1990** [comment]
Thank you Carlos.

It works, but brings another new problem.

For example, seaborn and matplotlib modules cannot work in the new kernel, by following that instruction.

Kind regards,

Shuo


This email originated from TU Dublin. If you received this email in error, please delete it from your system. Please note that if you are not the named addressee, disclosing, copying, distributing or taking any action based on the contents of this email or attachments is prohibited.

Is ó OT Baile Átha Cliath a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa ríomhphost nó sna hiatáin seo.

________________________________

**Comment by ccordoba12** [comment]
In what way Matplotlib and Seaborn don't work?

**Comment by shuo1990** [comment]
Hi, Carlos.

I changed the python preference in the following figure, and restarted kernel. Arch can be imported.

But due to the restarted kernel, Matplotlib and Seaborn cannot work.

[cid:e65b3ffb-07a8-4bb4-80df-82b7d68ae906]

Kind regards,

Shuo



________________________________

**Comment by ccordoba12** [comment]
You need to install those packages in your environment. You can do by opening a terminal and running there:

    conda activate py39
    conda install matplotlib seaborn

That should solve your problem.

**Comment by shuo1990** [comment]
Thank you so much, Carlos.

All my problems are solved.

Kind regards,

Shuo


This email originated from TU Dublin. If you received this email in error, please delete it from your system. Please note that if you are not the named addressee, disclosing, copying, distributing or taking any action based on the contents of this email or attachments is prohibited.

Is ó OT Baile Átha Cliath a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa ríomhphost nó sna hiatáin seo.

________________________________

**Comment by shuo1990** [comment]
By the way, Carlos, the sklearn can be imported.

[cid:1fe8eaac-9451-4e86-bc30-d0d64d0f0563]

The errors of code in anaconda prompt is as followed:

(base) C:\Users\Shuo Zhang>conda activate py39

(py39) C:\Users\Shuo Zhang>conda install sklearn
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - sklearn

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Kind regards,

Shuo


This email originated from TU Dublin. If you received this email in error, please delete it from your system. Please note that if you are not the named addressee, disclosing, copying, distributing or taking any action based on the contents of this email or attachments is prohibited.

Is ó OT Baile Átha Cliath a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa ríomhphost nó sna hiatáin seo.

________________________________

**Comment by shuo1990** [comment]
Hi, Carlos. Thank you.

It seems that my kernel has some problem as follows:

Traceback (most recent call last):
File "C:\Users\Shuo Zhang\anaconda3\Scripts\spyder-script.py", line 10, in
sys.exit(main())
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
mainwindow.main()
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3651, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3526, in run_spyder
main.setup()
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 843, in setup
from spyder.plugins.console.plugin import Console
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\plugins\console\plugin.py", line 29, in
from spyder.utils.environ import EnvDialog
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\utils\environ.py", line 19, in
from spyder.plugins.variableexplorer.widgets.collectionseditor import (
File "C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionseditor.py", line 39, in
from spyder_kernels.utils.nsview import (
ImportError: cannot import name 'DataFrame' from 'spyder_kernels.utils.nsview' (C:\Users\Shuo Zhang\anaconda3\lib\site-packages\spyder_kernels\utils\nsview.py)

I cannot open the spyder now.

Kind regards,

Shuo


This email originated from TU Dublin. If you received this email in error, please delete it from your system. Please note that if you are not the named addressee, disclosing, copying, distributing or taking any action based on the contents of this email or attachments is prohibited.

Is ó OT Baile Átha Cliath a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa ríomhphost nó sna hiatáin seo.

________________________________

**Comment by shuo1990** [comment]
Hi, Carlos.

Sorry for the troubles I brought you. But thank you somuch for your skills and patience.

I have sorted out all the concerns.

Kind regards,

Shuo



________________________________

**Comment by ccordoba12** [comment]
Closing because this issue was solved.
