### ISSUE TITLE
Not allowed dictionary key

### ISSUE THREAD

**Issue by Mike100000** [spyder-ide/spyder#16094]
Can't set list as a dictionary key. Please make so the interpreter will display "'list' type can't be set as a dictionary key.'"

**Comment by dalthviz** [comment]
Hi @Mike100000 I'm not totally sure to follow what you say. Could you explain a little bit more your usage context (as well as providing some executable code example that can help us reproduce the issue you are having in our side)? Also, some more info about your setup (Spyder version, Python version, dependencies, OS, etc) will be appreciated.

Without more info is quite difficult for us to help you, sorry :/
