### ISSUE TITLE
Not exactly a new issue, but..... Conda Install 5.0.5

### ISSUE THREAD

**Issue by Tunneller** [spyder-ide/spyder#16096]
I've been struggling to install spyder v 5.0 for a while now. Lots of updating. I've just discovered this list of issues and it looks like my installation problem, in some sense, might already have ben solved: I found a closed issue where a certain combination of updating and resetting did the trick for that user. Meanwhile, 48 hrs after typing the command "conda install spyder=5.0.5" then this is still running:

![image](https://user-images.githubusercontent.com/18357401/127347416-86d6277a-9de7-44a9-9e70-6dcd8aaaa667.png)

My question is whether I should kill conda's attempt to resolve the conflict? In some sense I don't mind keeping it running if it will eventually solve it. Or will conda never in fact succeed, so kill it now?

**Comment by ccordoba12** [comment]
Hey @Tunneller, thanks for reporting. Please try

    conda update anaconda

and then

    conda install spyder=5.0.5

That should solve your problem.

**Comment by Tunneller** [comment]
Hi Carlos, appreciate the prompt reply, but I’ve done that a few times. Also

 

conda update –force conda

 

conda update –all

 

and a few others that I forget.

 

I see some other options in case #15273 that I have not tried, however, where you solved that users problem. 

 

I’m trying to decide whether to try those steps there or keep this program running for another while.

 

Regards, John

**Comment by ccordoba12** [comment]
If `conda update anaconda` doesn't work, I'm afraid you'll have to reinstall Anaconda, sorry.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
