### ISSUE TITLE
How do I get rid of this vertical line in the editor?

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#16128]
![image](https://user-images.githubusercontent.com/5112397/127951305-7253017c-c6ff-4c76-ad32-5ad8136a6466.png)

**Comment by leavor** [comment]
![image](https://user-images.githubusercontent.com/1759365/127972652-11ccc45e-dd12-48ac-8b80-0ec15c8ac4d4.png)

**Comment by A-Pai** [comment]
终于搞定了，还是同胞给力，谢谢

**Comment by leavor** [comment]
How do you use version 5.0, when I use version 5.0, I always report an error #15340

**Comment by ccordoba12** [comment]
@A-Pai, this is where that option is placed in Spyder 5

![imagen](https://user-images.githubusercontent.com/365293/128107754-05c2a21c-5fd1-48c6-826b-773bff5e76aa.png)

**Comment by ccordoba12** [comment]
> How do you use version 5.0, when I use version 5.0, I always report an error #15340

@leavor, I think that problem is caused because you have a Windows user name with Chinese characters. Sorry for not having looked at it yet.
