### ISSUE TITLE
Spyder debugging keyboard shortcuts on a Mac

### ISSUE THREAD

**Issue by dkaisersmsu** [spyder-ide/spyder#16122]
### What steps will reproduce the problem?

I am running Spyder 5.0.5 with macOS Big Sur version 11.5.1 on a Late 2013 Mac Pro.

I have updated both Anaconda and Spyder.

The keyboard shortcuts on the Debug and other menus are not working.  I have tried resetting them and remapping them.  Neither worked.

**Comment by ccordoba12** [comment]
Hey @dkaisersmsu, thanks for reporting. Could you try to remap them by going to the menu

    Tools > Preferences > Keyboard shortcuts

and try again?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
