### ISSUE TITLE
5.1.0: `black` formatter duplicates part of the last line and breaks any code it formats

### ISSUE THREAD

**Issue by ba-tno** [spyder-ide/spyder#16123]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When using `black` as a formatter the last line of a file is duplicated when the formatter is run.

### What steps reproduce the problem?

1. Start Spyder 5.1.0
2. In Tools -> Preferences -> Completion and linting -> Code style and formatting select `black` as the formatter
3. Run the formatter on a piece of code (Source -> Format file or selection with Black)

### What is the expected output? What do you see instead?
**Expected**: The file is formatted with the `black` formatter, no code is added.  
**Actual**: The file is formatted, but part of the last line is duplicated on a new line at the end (see GIF below):

![spyder](https://user-images.githubusercontent.com/52008464/127899236-a5c58ff1-0d94-4030-a667-344edcc4bb17.gif)

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 5.1.0 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0                         :  1.4.0 (OK)
chardet >=2.0.0                              :  4.0.0 (OK)
cloudpickle >=0.5.0                          :  1.6.0 (OK)
cookiecutter >=1.6.0                         :  1.7.3 (OK)
diff_match_patch >=20181111                  :  20200713 (OK)
intervaltree                                 :  None (OK)
IPython >=7.6.0                              :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0                        :  0.18.0 (OK)
jsonschema >=3.2.0                           :  3.2.0 (OK)
keyring >=17.0.0                             :  23.0.1 (OK)
nbconvert >=4.0                              :  6.1.0 (OK)
numpydoc >=0.6.0                             :  1.1.0 (OK)
paramiko >=2.4.0                             :  2.7.2 (OK)
parso >=0.7.0;<0.9.0                         :  0.8.2 (OK)
pexpect >=4.4.0                              :  4.8.0 (OK)
pickleshare >=0.4                            :  0.7.5 (OK)
psutil >=5.3                                 :  5.8.0 (OK)
pygments >=2.0                               :  2.9.0 (OK)
pylint >=2.5.0                               :  2.9.6 (OK)
pyls_spyder >=0.4.0                          :  0.4.0 (OK)
pylsp >=1.2.0;<1.3.0                         :  1.2.0 (OK)
pylsp_black >=1.0.0                          :  None (OK)
qdarkstyle =3.0.2                            :  3.0.2 (OK)
qstylizer >=0.1.10                           :  0.2.1 (OK)
qtawesome >=1.0.2                            :  1.0.3 (OK)
qtconsole >=5.1.0                            :  5.1.1 (OK)
qtpy >=1.5.0                                 :  1.9.0 (OK)
rtree >=0.9.7                                :  0.9.7 (OK)
setuptools >=49.6.0                          :  57.4.0 (OK)
sphinx >=0.6.6                               :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0                :  2.1.0 (OK)
textdistance >=4.2.0                         :  4.2.1 (OK)
three_merge >=0.1.1                          :  0.1.1 (OK)
watchdog                                     :  2.1.3 (OK)
zmq >=17                                     :  22.1.0 (OK)

# Optional:
cython >=0.21                                :  0.29.24 (OK)
matplotlib >=2.0.0                           :  3.4.2 (OK)
numpy >=1.7                                  :  1.19.3 (OK)
pandas >=1.1.1                               :  1.3.1 (OK)
scipy >=0.17.0                               :  1.7.1 (OK)
sympy >=0.7.3                                :  1.8 (OK)

# Spyder plugins:
spyder.plugins.completion.plugin 5.1.0       :  5.1.0 (OK)
spyder.plugins.outlineexplorer.plugin 5.1.0  :  5.1.0 (OK)
spyder.plugins.projects.plugin 5.1.0         :  5.1.0 (OK)
spyder.plugins.variableexplorer.plugin 5.1.0 :  5.1.0 (OK)

```

**Comment by ba-tno** [comment]
I see that `pylsp_black >=1.0.0` is missing, but don't understand why. I've ran `conda install spyder-kernels=2.1` in the environment I use with Spyder.

**Comment by ccordoba12** [comment]
@ba-tno, thanks for reporting. How did you install Spyder?

**Comment by ba-tno** [comment]
> @ba-tno, thanks for reporting. How did you install Spyder?

With the standalone installer. Before this I had 5.0.5 installed, I just ran the installer of 5.1.0 "over" 5.0.5.

**Comment by ccordoba12** [comment]
Ok, this is very strange because it seems `pylsp_black` was not included in our installer. I'll take a look at it and try to fix it in 5.1.1, to be released as soon as I can.

**Comment by ba-tno** [comment]
Thanks! 

Just for the sake of completion: I just tried installing `pylsp_black` in my conda environment with `pip install python-lsp-black`, but that didn't change anything.

**Comment by alandema** [comment]
To add in this issue, the same problem was happening to me. I've installed Spyder via pip over an installation of Spyder 4.2.5.

**Comment by alandema** [comment]
I'm still having this problem in 5.1.1 with black or autopep8.

**Comment by ba-tno** [comment]
> I'm still having this problem in 5.1.1 with black or autopep8.
> Windows 10, Python 3.9.5, installed spyder via pip.

Did you reset the spyder preferences? I had a similar issue where I rolled back after the 5.1.0 release to an earlier version and the formatter problem remained until I reset the spyder preferences. Maybe that solution works in your case too?

**Comment by alandema** [comment]
> > I'm still having this problem in 5.1.1 with black or autopep8.
> > Windows 10, Python 3.9.5, installed spyder via pip.
> 
> Did you reset the spyder preferences? I had a similar issue where I rolled back after the 5.1.0 release to an earlier version and the formatter problem remained until I reset the spyder preferences. Maybe that solution works in your case too?

Hello. Sorry for my late response.

Yes, I tried to reset the settings. I also tried to reinstall Spyder and reinstall the miniconda with a fresh installation of Spyder.
None of these worked.
