### ISSUE TITLE
Spyder 5.1.0 crashes on startup (macOS)

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#16126]
Spyder 5.1.0 (both the non-lite and lite standalone macOS apps) crashes instantly when I open it.

As soon as I opened the Spyder app, I saw a dialog box that looked like this:

```
+-------------------------------------------------+
|           Spyder Error                          |
|                                                 |
|       (Open Console)   (Terminate)              |
+-------------------------------------------------+
```

When I clicked "Open Console", the macOS "Console" app opened, with refreshing logs, which were not specific to Spyder.

Is this a known bug?  Thanks.

**Comment by jsh9** [comment]
My macOS version: 10.15.7

**Comment by ccordoba12** [comment]
Hey @jsh9, thanks for reporting.Yes, this is known bug: #16117.

I'll try to release 5.1.1 with a fix as soon as possible,

**Comment by jsh9** [comment]
Thanks!
