### ISSUE TITLE
5.1.0 Spyder Error

### ISSUE THREAD

**Issue by Lynchez** [spyder-ide/spyder#16120]
I just updated 5.1.0 . As it opens, it gives an error as Spyder Error and offers two options. Open console or terminate.

<img width="1440" alt="Ekran Resmi 2021-08-02 15 42 25" src="https://user-images.githubusercontent.com/45340773/127863781-42743c54-d2dd-4297-ade1-4dc460077313.png">

**Comment by ccordoba12** [comment]
Hey @Lynchez, thanks for reporting. I'd say this problem is related to issue #16117, so I'm going to close it in favor of that one.

Please update as soon as we release version 5.1.1 (hopefully later today) and let us know if the problem persists.

**Comment by mhdmyz** [comment]
> Please update as soon as we release version 5.1.1 (hopefully later today) and let us know if the problem persists.

any news on this?

**Comment by ccordoba12** [comment]
Working on it. It should be released later today or tomorrow.

**Comment by mhdmyz** [comment]
Thanks!
