### ISSUE TITLE
Editor and IPythonConsole object has no attribute 'get_description'


### ISSUE THREAD

**Issue by hofsaess** [spyder-ide/spyder#16136]
### What steps will reproduce the problem?

* Installing spyder v5.1.0 from pip
* start spyder from commandline
* After starting spyder I get following message:

<class 'spyder.plugins.editor.plugin.Editor'>: 'Editor' object has no attribute 'get_description'
Traceback (most recent call last):
  File "/home/hofsaess/scripts37/swe/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 924, in setup
    description = plugin_instance.get_description()
AttributeError: 'Editor' object has no attribute 'get_description'
<class 'spyder.plugins.ipythonconsole.plugin.IPythonConsole'>: 'IPythonConsole' object has no attribute 'get_description'
Traceback (most recent call last):
  File "/home/hofsaess/scripts37/swe/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 924, in setup
    description = plugin_instance.get_description()
AttributeError: 'IPythonConsole' object has no attribute 'get_description'

# Mandatory:
atomicwrites >=1.2.0                         :  1.4.0 (OK)
chardet >=2.0.0                              :  4.0.0 (OK)
cloudpickle >=0.5.0                          :  1.6.0 (OK)
cookiecutter >=1.6.0                         :  1.7.2 (OK)
diff_match_patch >=20181111                  :  20200713 (OK)
intervaltree >=3.0.2                         :  3.1.0 (OK)
IPython >=7.6.0                              :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0                        :  0.17.2 (OK)
jsonschema >=3.2.0                           :  3.2.0 (OK)
keyring >=17.0.0                             :  23.0.1 (OK)
nbconvert >=4.0                              :  6.0.7 (OK)
numpydoc >=0.6.0                             :  1.1.0 (OK)
parso >=0.7.0;<0.9.0                         :  0.7.0 (OK)
pexpect >=4.4.0                              :  4.8.0 (OK)
pickleshare >=0.4                            :  0.7.5 (OK)
psutil >=5.3                                 :  5.8.0 (OK)
pygments >=2.0                               :  2.8.1 (OK)
pylint >=2.5.0                               :  2.7.4 (OK)
pyls_spyder >=0.4.0                          :  0.4.0 (OK)
pylsp >=1.2.0;<1.3.0                         :  1.2.0 (OK)
pylsp_black >=1.0.0                          :  None (OK)
qdarkstyle =3.0.2                            :  3.0.2 (OK)
qstylizer >=0.1.10                           :  0.1.10 (OK)
qtawesome >=1.0.2                            :  1.0.2 (OK)
qtconsole >=5.1.0                            :  5.1.0 (OK)
qtpy >=1.5.0                                 :  1.9.0 (OK)
rtree >=0.9.7                                :  0.9.7 (OK)
setuptools >=49.6.0                          :  56.0.0 (OK)
sphinx >=0.6.6                               :  3.5.4 (OK)
spyder_kernels >=2.1.0;<2.2.0                :  2.1.0 (OK)
textdistance >=4.2.0                         :  4.2.1 (OK)
three_merge >=0.1.1                          :  0.1.1 (OK)
watchdog >=0.10.3                            :  1.0.2 (OK)
xdg >=0.26                                   :  0.27 (OK)
zmq >=17                                     :  22.0.3 (OK)

# Optional:
cython >=0.21                                :  0.29.23 (OK)
matplotlib >=2.0.0                           :  3.4.1 (OK)
numpy >=1.7                                  :  1.20.2 (OK)
pandas >=1.1.1                               :  1.2.3 (OK)
scipy >=0.17.0                               :  1.6.2 (OK)
sympy >=0.7.3                                :  None (OK)

# Spyder plugins:
spyder.plugins.completion.plugin 5.1.0       :  5.1.0 (OK)
spyder.plugins.outlineexplorer.plugin 5.1.0  :  5.1.0 (OK)
spyder.plugins.projects.plugin 5.1.0         :  5.1.0 (OK)
spyder.plugins.variableexplorer.plugin 5.1.0 :  5.1.0 (OK)

**Comment by ccordoba12** [comment]
Hey @hofsaess, thanks for reporting. We'll fix this in our next version (5.1.1) to be released as soon as we can.
