### ISSUE TITLE
How can I install kite？

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#16132]
How can I install kite？“Kite is temporarily unavailable” for a long time

https://www.kite.com/kite-is-temporarily-unavailable/?source=download

**Comment by ba-tno** [comment]
Have you tried going to https://www.kite.com/ or in Spyder go to Tools -> Install Kite completion engine?

**Comment by A-Pai** [comment]
> Have you tried going to https://www.kite.com/

Have you tried going to https://www.kite.com/ ---it is  “Kite is temporarily unavailable” 
 in Spyder go to Tools -> Install Kite completion engine?--I have no “Install Kite completion engine”

**Comment by ba-tno** [comment]
That's odd. I could press the "Download for free" button just now, but now I also get the unavailable page.
What version of Spyder do you have? In 5.0.5 I have this entry in my menu:

![image](https://user-images.githubusercontent.com/52008464/128035017-50ce7715-c60b-45a8-8122-4a83f4b76e2d.png)

**Comment by ccordoba12** [comment]
Kite won't be available for now, sorry. They have to figure out some internal things and hopefully it will available again in the future (but that's not certain).

**Comment by Itotutona** [comment]
If you use arch linux, you can install copilot without downloading it on www.kite.com

`yay -S kite`

When follow the instructions and install the plugin in the marketplace of the editor
