### ISSUE TITLE
Can the preference be stored？

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#16131]
Can the preference be stored？when I change a pc,it is convenient to set the preference

**Comment by ba-tno** [comment]
Preferences of Spyder are stored in the home folder under the `.spyder-py3` folder. On windows that is: `c:\Users\your_username\.spyder-py3\`.

I have moved this folder across machines with the exact same Spyder versions without any (noticeable) issues.

**Comment by ccordoba12** [comment]
Thanks @ba-tno for your help! That's right, you can copy that folder and drop it in the same location in another computer and you'll have the same settings.
