### ISSUE TITLE
How can I enlarge the font in help pane？

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#16139]
How can I enlarge the font in help pane？The default is too small

**Comment by dalthviz** [comment]
Hi @A-Pai for that you can change the rich font settings size (inside the preferences dialog: `Appearance > Fonts > Rich font > Size`):

![image](https://user-images.githubusercontent.com/16781833/128186295-0b53e508-b55d-4b6e-b0af-671885118bd3.png)
