### ISSUE TITLE
Links to 5.1.1 release installers aren't working.

### ISSUE THREAD

**Issue by ghost711** [spyder-ide/spyder#16152]
### What steps reproduce the problem?

1. Try to download either the Mac or Windows installer at: `https://github.com/spyder-ide/spyder/releases/tag/v5.1.1`

### What is the expected output? What do you see instead?

Expect to download the installer, but taken to file not found page.

**Comment by ghost711** [comment]
Working now. Closing.

**Comment by ccordoba12** [comment]
Yeah, they take like 20 min or half an hour to be generated and uploaded to our Releases page.
