### ISSUE TITLE
h5py package not avilable -- using ascii conversion

### ISSUE THREAD

**Issue by MuhammadRRahman** [spyder-ide/spyder#16156]
### What steps will reproduce the problem?

I have reinstalled Anaconda and Spyder recently on my macOS (M1). Now, whenever trying to execute any code, the following line shows up and the kernel restars without completing the eecution:

h5py package not avilable -- using ascii conversion

I tried:

- brew install h5py
- brew install cython

Also I uninstalled and then reinstalled anaconda and spyder. But couldn't fix the issue.
Any help will be highly appreciated.

**Comment by ccordoba12** [comment]
Hey @MuhammadRRahman, thanks for reporting. It seems you're trying to mix Homebrew and Anaconda packages, which is a recipe for disaster (as you discovered).

My only recommendation is for you to untangle that mess and use only one of those alternatives.
