### ISSUE TITLE
Spyder 5.1.1 Win10 never launches after splash screen

### ISSUE THREAD

**Issue by dflateau** [spyder-ide/spyder#16158]
## Problem Description
* Spyder 5.1.1 crashes on launch after the splash screen with Win 10 and Anaconda (actually, I never see the icon in my task bar). No other message or action occurs. 
* Previously, my 5.0.1 installation worked fine. There are no installation errors.
* I've tried uninstalling Spyder 5 completely, and reinstalling 5.1.1  in a few different places on my disks, with no luck.
* Restarting between installation attempts.
* Running the installer with administrator privledges had no effect.
* I've checked the CPR page, and tried every Spyder 5-applicable suggestion there with results

### What steps reproduce the problem?

1.  Launching Spyder 5.1.1 from its shortcut in the Start Menu

* Spyder version: 5.1.1
* Python version: (whatever version comes with 5.1.1)

**Comment by dflateau** [comment]
to add, I was able to get Spyder to launch in Windows Explorer by right-clicking Spyder.launch.pyw and choosing Edit with Spyder. The IDE launched, but this was in the console:

`Traceback (most recent call last):
  File "spyder.launch.pyw", line 34, in <module>
    from spyder.app.start import main
  File "pkgs\spyder\app\start.py", line 34, in <module>
    import zmq
  File "pkgs\zmq\__init__.py", line 125, in <module>
    from zmq import backend
  File "pkgs\zmq\backend\__init__.py", line 32, in <module>
    raise original_error from None
  File "pkgs\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "pkgs\zmq\backend\select.py", line 32, in select_backend
    mod = import_module(name)
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "pkgs\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (pkgs\zmq\backend\cython\__init__.py)`

**Comment by ccordoba12** [comment]
Hey @dflateau, thanks for reporting. I have on question for you: did you manually add your Anaconda installation directory to the `PYTHONPATH` environment variable in your system?

I think that's the only way this error can be triggered.

**Comment by dflateau** [comment]
Thanks for the quick reply. I haven't set the `PYTHONPATH` environment variable, but because of roaming profile problems, I have manually set the paths.py file for jupyter in my conda environments to make sure it bypasses using roaming profile paths (and just uses the local path). This worked for Spyder 5 versions previously, as well as Spyder 4. Not sure if that's the problem or not, though.

**Comment by ccordoba12** [comment]
> I have manually set the paths.py file

What do you mean by this? I don't know how that works.

> Not sure if that's the problem or not, though.

Yeah, I think that's messing with our installer, but I'd like to better know how it works.

**Comment by dflateau** [comment]
In Anacdona (not Spyder's custom python install), I have the base environment as well as all other environments' (here i.e. "environment1") C:\Anaconda3\envs\environment1\lib\site-packages\jupyter_core\paths.py to include this alteration to the code therein:

`def jupyter_runtime_dir():
    """Return the runtime dir for transient jupyter files.

    Returns JUPYTER_RUNTIME_DIR if defined.

    The default is now (data_dir)/runtime on all platforms;
    we no longer use XDG_RUNTIME_DIR after various problems.
    """
    env = os.environ

    if env.get('JUPYTER_RUNTIME_DIR'):
        #return env['JUPYTER_RUNTIME_DIR']
        return os.path.join(r"C:\Anaconda3\envs\environment1\share\jupyter","")

    #return pjoin(jupyter_data_dir(), 'runtime')
    return os.path.join(r"C:\Anaconda3\envs\environment1\share\jupyter","")
`

I'm not sure if this Anaconda mod would have any effect on Spyder when using its own python environment (which is selected in preferences). But the same error does pop up using Spyder's python on from an Anaconda env.

**Comment by ccordoba12** [comment]
Ok, that shouldn't be the cause of the problem (as far as I can tell). But could you disable that change and try again?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
