### ISSUE TITLE
Mac app - Matplotlib does not work with Canopy

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1615]
_From [breed...@gmail.com](https://code.google.com/u/105348566576685241380/) on 2013-10-21T15:55:48Z_

Spyder Version:  2.2.5
Python Version:  2.7.5
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.3 on Darwin
pyflakes >=0.5.0:  0.5.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.0 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

1. Install Spyder via the disk image (DMG)
2. Select a new interpreter via Preferences -> Console -> Advanced Settings -> Use the following Python interpreter -> (path to Enthought Canopy interpreter)
3. import matplotlib.pylab as plt
4. plt.plot([0,1],[0,1]) What is the expected output? What do you see instead? I expect to see a figure window pop up with a simple plot in it. The dock has a bouncing rocket icon, but the plot window never shows up. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1615_

**Comment by spyder-issues-migrator** [comment]
_From [breed...@gmail.com](https://code.google.com/u/105348566576685241380/) on 2013-10-21T13:57:01Z_

I forgot to mention that I restarted Spyder in between steps 2 and 3.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-21T14:39:54Z_

I thought I had solved this in 2.2.3. I'll check it out for our next release.

**Summary:** Mac app - Matplotlib does not work with Canopy  \<span class="oldvalue"> (was: Matplotlib does not work with Canopy) \</span>  
  **Labels:** MS-v2.3 OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T12:41:47Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:37:36Z_

**Labels:** -MS-v2.3.1 MS-v2.4

**Comment by ccordoba12** [comment]
I think this is solved now, but I'll verify it for our next release.

**Comment by ccordoba12** [comment]
Ok, I tested things with the lastest Canopy, and everything seems to be working correctly now.
