### ISSUE TITLE
Ugly tabs and path, unresponsive to themes

### ISSUE THREAD

**Issue by Phlya** [spyder-ide/spyder#16178]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The tabs with files look ugly and the same in both light and dark theme. Nothing ugly about the filepath above them, but it also looks the same in both light and dark themes, and so barely readable in the latter.

![image](https://user-images.githubusercontent.com/2895034/128643595-58140c0f-15ad-4ec1-bc19-a78602be0247.png)

## Versions

* Spyder version: 5.0.5
* Python version: 3.8.0
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Linux 5.4.0-80-generic, Ubuntu 20.04.2

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.8.3 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.1 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by steff456** [comment]
Hi @Phlya,

Can you explain to me what settings do you have in Spyder that result in this style of the tabs so I can try to reproduce it on my end?

**Comment by Phlya** [comment]
I'm not sure what to answer, I can check if you have any ideas where to look? I don't think I changed any setting at all to be honest...

**Comment by steff456** [comment]
How did you installed Spyder?

**Comment by Phlya** [comment]
Using conda, from conda-forge.

**Comment by steff456** [comment]
Can you update to 5.1.1 and let me know if you are seeing the tabs the same?

**Comment by Phlya** [comment]
I can't :( I thought I had the latest version... I get an error when running `mamba install -c conda-forge spyder==5.1.1`:

`- package python-language-server-0.36.2-pyhd3eb1b0_0 requires pycodestyle >=2.6.0,<2.7.0, but none of the providers can be installed`

**Comment by Phlya** [comment]
I created a new environment and installed 5.1.1 - then it's fine... I actually kept it in a separate environment with nothing else, just to avoid such problems, but conda is annoying sometimes.

**Comment by steff456** [comment]
Ok! I'm glad to hear that, I'm thinking that maybe you have an outdated dependency on the previous environment. The important part is that we could fix your issue.

If you encounter why it was broken please reopen this issue and let us know.

Thanks for reporting!
