### ISSUE TITLE
spyder is super Laggy - Version 5.0s

### ISSUE THREAD

**Issue by Jabed-Akhtar** [spyder-ide/spyder#16181]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I tried all versions after 4.0, why are all so slow. It wastes lots of time...

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.0. till 5.0.5
* Python version:  3.6.13
* Qt version: 3.1
* PyQt version: 
* Operating System name/version: Ubuntu 20.04.2 LTS

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Aegis1863** [comment]
I have similar situation, I don't know whether as same as you.
It usually start not smooth  when I have typed about more then 50 lines code. 
And It must jam typing at a high frequency when any lines warning.

**Comment by ccordoba12** [comment]
Hey @Jabed-Akhtar, thanks for reporting. We're aware of the sluggishness issues in our editor and we'll try to fix them before the year ends. For now, please read the comments on issue #15631 for possible workaround until we do that.

Perhaps the most crucial one is disabling folding by going to the menu

    Source > Show code folding

**Comment by ccordoba12** [comment]
I'm going to close this issue in favor of #15631 so that we have all tips about this problem in one place. If you have more comments, please post them there.
