### ISSUE TITLE
"Format file or selection with Autopep8" cause the code to be misplaced

### ISSUE THREAD

**Issue by Godsix** [spyder-ide/spyder#16180]
### What steps reproduce the problem?

1. select a python source file that contains comments "# ..."
![捕获](https://user-images.githubusercontent.com/10581915/128652127-51bb3583-dc9a-42c7-bd73-7fb10996b640.PNG)

2. click Source -> Format file or selection with Autopep8
![image](https://user-images.githubusercontent.com/10581915/128652351-546375fb-5598-43f7-aa0e-1b2c1d79c424.png)

3.  It will cause the code to be misplaced
![捕获2](https://user-images.githubusercontent.com/10581915/128652176-ea611cae-7fb2-4a6a-ae14-026e806b0542.PNG)
4.The bug appear after **version 5.1.0**,it's OK at **version 5.0.5**

**Comment by zariiii9003** [comment]
This also happens when formatting with black

**Comment by onerozer** [comment]
I am also having the same problem.
Autopep8 and black doesn't matter, it incorrectly changes the code.

Version : 5.1.1
Python 3.7.9 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Windows 10

**Comment by steff456** [comment]
Hi @Godsix, @zariiii9003 and @onerozer, 

Can you all send me a code example that is showing the error? I'm trying to reproduce this with a simple script and the error doesn't show up.

**Comment by onerozer** [comment]
Hi @steff456 ,
You can see it in the attached screenrecording.
This error happens even with the simplest code. 

https://user-images.githubusercontent.com/14151240/128976788-0a300a9e-8702-4792-86e6-bfee53135f13.mp4

https://user-images.githubusercontent.com/14151240/128978287-31b14277-f521-481b-847b-7cc5a3fb5b50.mp4

**Comment by steff456** [comment]
Thanks for the videos! We will take a look at this issue to fix it in one of our next releases.

**Comment by ccordoba12** [comment]
@onerozer, thanks for the videos. I was able to reproduce this problem and will try to fix it in our next release (5.1.2), to be released shortly.
