### ISSUE TITLE
Interaction improvement of spyder and pyqt

### ISSUE THREAD

**Issue by YongYahn** [spyder-ide/spyder#16188]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When using pyqt designer in anaconda for GUI analysis, using spyder as code editing, can the right mouse button go directly to the callback function module of the button like matlab gui? I hope that spyder and pyqt designer can communicate in real time. In addition, I hope that in spyder When drawing a curve in, the image is a figure in the pop-up window, how to set it?

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.5
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: win 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @YongYahn, thanks for reporting. You said:

> I hope that spyder and pyqt designer can communicate in real time.

Unfortunately, that's out of the scope for Spyder, sorry. That's because we're focused on scientific programming and not on developing applications with PyQt.

> When drawing a curve in, the image is a figure in the pop-up window, how to set it?

What do you mean by this? You mean that you'd like to see Matplotlib plots displayed in a separate window?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
