### ISSUE TITLE
Outline pane not displaying classes and functions

### ISSUE THREAD

**Issue by iiscleap** [spyder-ide/spyder#16198]
### What steps will reproduce the problem?

When I open a python file, The outline pane used to show the list of all functions and classes defined in that file and it was easy to navigate through the file by clicking on the function/class names. But now, I don't see the functions and class names in the outline pane, just the file name. It is no longer helpful.

**Comment by dalthviz** [comment]
Hi @iiscleap thank you for the feedback. Could you give us some more information regarding your setup as is described in the issue template (Spyder version, dependencies, operative system, python version, etc)? Without that is difficult for us to help you. Besides that, we fixed some issues regarding the LSP and the outline in our latest release (`5.1.1`) so if you are not using Spyde with that version updating and trying again could be worthy. Let us know :)

**Comment by jml17** [comment]
Hi @iiscleap, I had the same issue and found that you can get them to re-appear by clicking the Outline pane menu button (the three horizontal lines), and enabling/checking "Display variables and attributes". Doing this causes everything (functions, classes, cells) to re-appear. I'm not sure why this is disabled by default.

I had another issue that clicking on items within the Outline no longer takes you to that spot in the code, but that's a separate issue - which I'm about to open myself.

**Comment by dalthviz** [comment]
Hi @jml17 are you using the latest Spyder version available? If no, could you check if even with the `Display variables and attributes` disable the outline show the functions, classes, cells, etc information with our latest release (`5.1.1`)? Let us know!

**Comment by jml17** [comment]
Hi @dalthviz, I believe it was `5.0.5` since last I checked that was the latest release available via Anaconda. I will check again once I'm able to go to `5.1.1`.

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by caseminario** [comment]
I am running Spyder 5.1.5 on a MacOS Catalina 10.15.7 and having the issue that I do not see any classes/functions details (other than the filename) when using the Outline pane

**Comment by dalthviz** [comment]
Hi @caseminario, could you try to update to Spyder 5.2.2 and check if the issue persists? Let us know!

**Comment by caseminario** [comment]
> Hi @caseminario, could you try to update to Spyder 5.2.2 and check if the issue persists? Let us know!

HI @dalthviz, thanks for your quick response and apologies for my slow response! I run Spyder 5.1.5 under Anaconda 1.9.12 and have multiple environments set up. I was able to get the functionality I wanted (seeing the classes/functions details (other than the filename) when using the Outline pane) using another -- less cluttered --  environment. So. it must have been some sort of dependencies issue, however, I can't tell which one(s). For now, I'm ok with switching to the environment where Spyder 5.1.5 seems to work well for me. This summer, I will likely delete my entire/current Anaconda installation, upgrade it, and re-install all the dependencies including Spyder 5.2.2. THANKS again for your help!!

**Comment by dalthviz** [comment]
Glad to hear that you managed to make things work on your setup @caseminario :+1: Also, just in case, to check the latest Spyder release you can go to https://github.com/spyder-ide/spyder/releases For example, a couple of days ago we released Spyder 5.3.0 :)

Also, is quite possible that to get the latest version you will need to use the conda-forge channel (so creating a env to setup the latest Spyder in the future could be a good idea).
