### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by aeyanashraf** [spyder-ide/spyder#16191]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm trying to run a code which basically is a Pretrained CNN (VGG16 - imagenet) used for semantic segmentation using Random Forest. It pops  An error ocurred while starting the kernel . I have tried everything but no solution . 

### Paste Traceback/Error Below (if applicable)

```python-traceback
An error ocurred while starting the kernel
2021󈚬󈚮 23:22:09.403494: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance‑critical operations: AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021󈚬󈚮 23:22:09.842137: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 2349858816 exceeds 10% of free system memory.
2021󈚬󈚮 23:22:10.433700: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 2349858816 exceeds 10% of free system memory.
```

## Versions

* Spyder version: 5.0.5
* Python version: 3.8.11
* Qt version: 5.9.7
* PyQt version: 1.9.0
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by ccordoba12** [comment]
Hey @aeyanashraf, thanks for reporting. I have one question for you:

Are you able to run your code in JupyterLab or Jupyter notebook?

If not, I'd say this problem is not related to Spyder.

**Comment by aeyanashraf** [comment]
> Hey @aeyanashraf, thanks for reporting. I have one question for you:
> 
> Are you able to run your code in JupyterLab or Jupyter notebook?
> 
> If not, I'd say this problem is not related to Spyder.

It does not run on Jupyter Notebook. Kernel keeps dying again and again. It has anything to do with the fact I have a Ryzen 3600 and not the standard Intel .

**Comment by ccordoba12** [comment]
I really don't know, sorry. But since this is not an issue with Spyder, we can't help you with it here.
