### ISSUE TITLE
Enhancement request: Consider migration to the latest Qt 5

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#16194]
This is not a bug report.  

Please consider evolving the Spyder IDE's Qt 5 interface to be up-to-date.  On the current Ubuntu base, this is 5.15.4.  I realise that this would be a somewhat of a nuisance API change - larger consequences?  Perhaps, this is not an issue on MacOS and Windows?

My current issue is that at Seti Breakthrough Listen, we are becoming significant Gnu Radio users.  The ```apt``` packages in question are ```gnuradio``` plus supporting package dependencies.  Gnu Radio and the Qt 5 design utilities are based on Qt 5.15.x but spyder requires a version < 5.13.  I understand that changings APIs is a large effort.

My current work-around is to confine spyder to a Miniconda build and this seems to allow both Qt 5 user worlds to exist with their different versions of Qt 5.  The Seti BL packages, I manage with ```pip --user ...``` so that they stay out of the Miniconda directory tree.

I can keep doing this.  But, is there any thought to upgrading the Qt 5 API in use for spyder?

**Comment by ccordoba12** [comment]
I'm going to close this issue in favor of #12829 because we're centralizing the discussion about 5.15 there.
