### ISSUE TITLE
No windows with GraphicsWindow

### ISSUE THREAD

**Issue by Michelino15** [spyder-ide/spyder#16208]
### What steps will reproduce the problem?

I am a MacOS user; when I try to use the ezgraphics.GraphicsWindow() command, the window icon appears on the bar, but I cannot open it. I learnt that it is a common problem, but none of the solutions I read about worked for me. They suggested changing the Graphics settings in the Spyder preferences, but I only got that now the command always restarts the kernel. The only time it worked (I don't know how), Spyder crashed. Can you help me? Thank you!

**Comment by ccordoba12** [comment]
Hey @Michelino15, thanks for reporting. What's `ezgraphics`?

**Comment by Michelino15** [comment]
Hi @ccordoba12 , thank you for your help. ezgraphics is a module I installed, and that allows making simple drawings (they suggested it in a Python textbook I found to learn to program). GraphicsWindow is a command that creates a top-level window. It works correctly as I use it in the Terminal, but it doesn’t when I try using it in Spyder, so it must be a problem inside the IDE, i think.

**Comment by ccordoba12** [comment]
Ok, thing should work if you go to the menu

    Tools > Preferences > IPython console > Graphics

and in the `Backend` option select `Tkinter`.

After that you should be asked to restart your kernel. If you don't, you're probably using an old Spyder version, so simply close Spyder and start it again.

Please let us know if it works for you.

**Comment by Michelino15** [comment]
Hi Carlos,
Thank you very much for your help and time. I will surely remember your
suggestion in case I should need it in a future situation. Fortunately, I
was able to solve my issue in another way. Basically, when used in Spyder,
the window generated by the program GraphicsWindow() immediately closes,
and you need to digit the command win.wait() to prevent it from
disappearing. At first, I didn't take this solution into account, even
though it was actually written in the textbook I'm using, because the
command Graphics.Window() worked anyways if used in the Terminal, and so I
thought the command win.wait() wasn't essential. In the end, it turned out
it was.
I'm sorry for the loss of time I may have caused you, but I hope that this
little problem of mine can be useful to others in time.
Thank you!
Michele from Italy

Il giorno lun 16 ago 2021 alle ore 17:45 Carlos Cordoba <
***@***.***> ha scritto:

**Comment by ccordoba12** [comment]
Hey Michele, I'm glad you were able to find a fix for your problem. Thanks for letting us know about it.
