### ISSUE TITLE
Permanently undock some panes?

### ISSUE THREAD

**Issue by shuai-zhou** [spyder-ide/spyder#16216]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
This is related to #10649
I am using Spyder 5.0.5. I used multiple monitors and undocked the var explorer pane and console pane on separated monitors. But when I close the var explorer and console pane or reboot, they are automatically re-docked to the main window. Are there options to permanently undock var explorer and console panel to separate monitors?

**Comment by ccordoba12** [comment]
Hey @shuai-zhoum, thanks for reporting. You said:

> But when I close the var explorer and console pane or reboot, they are automatically re-docked to the main window.

I took a look at the problem with rebo

**Comment by shuai-zhou** [comment]
@ccordoba12 
`if we don't dock them back in the interface, how are users supposed to displayed them again?`
Thanks for your clarification. Yes, it makes sense to re-dock the "var explorer" and "console" (or maybe other panes) to the main window when closing those panes without closing the main window.

Just want to clarify that what I want is to undock "var explorer" and "console" (or maybe other panes) to my separate monitors so I have an entire monitor for the main window for coding, and keep this layout after my computer reboots (that is what I mean "permanently", i.e., every time I open Spyer, there is the main window for coding on one monior, and the un-docked "console" and "var explorer" on separete monitors).

Anyway, looking forward to the new version. Thanks.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification. That's what I plan to implement in 5.2.0, i.e. the ability to restore undocked panes after Spyder starts again.
