### ISSUE TITLE
How to disable automatic invocation of the "Help" window?

### ISSUE THREAD

**Issue by ma-sadeghi** [spyder-ide/spyder#16220]
Is there a way to disable the automatic invocation of the "Help" window? (so that it only shows up if Ctrl+I is pressed)

Thanks!

**Comment by steff456** [comment]
Hi @ma-sadeghi,

Can you please give me a concrete example? If you don't want to have the pane open in Spyder you can go to `View > Panes > Help` and check that it is not checked.

**Comment by ma-sadeghi** [comment]
Thanks for getting back to me.

Sorry if I wasn't clear. I do want to have the Help pane, but I don't necessarily want Spyder to show the docstrings as soon as I start typing. Currently, as soon as I start typing in the IPython console, Spyder tries to show me the related docstrings, which slows things down a bit. Manually, I can trigger the docstrings mechanism using Ctrl+I, but currently, it seems that's the automatic default behavior. Here's a GIF recording of what I mean:

![uPQ2UCfZro](https://user-images.githubusercontent.com/14086031/129638719-ca579f7b-2890-4351-b087-05707dcf09c2.gif)

**Comment by steff456** [comment]
Now I understand you better, there's indeed an option to turn off this behavior. You just need to go and uncheck the option in `Preferences > Help > Automatic connections > IPython Console`. You can also see if it is happening for the editor and uncheck it in the same place. 

Hope this makes your workflow more light! Please let me know if you are able to change the option :)

**Comment by ma-sadeghi** [comment]
Great thanks!
