### ISSUE TITLE
Auto Complete Not working

### ISSUE THREAD

**Issue by jagan-2002** [spyder-ide/spyder#16227]
### What steps will reproduce the problem?

I updated spyder and when i created a new project the autocomplete feature stopeed working

**Comment by steff456** [comment]
Hi @jagan-2002,

Can you please upload a gif or a video showing us the behavior you are having? Also, which version of Spyder are you using currently?

Thanks for reporting!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
