### ISSUE TITLE
how can I switch to a new virtual environment in spyder？

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#16235]
I have create a new virtual environment，but how can I switch to the new virtual environment in spyder？

**Comment by marekkolman** [comment]
I think you should install spyder in that new environment and then run spyder from there

**Comment by ccordoba12** [comment]
Hey @A-Pai, thanks for reporting. This is answered in our docs:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
