### ISSUE TITLE
The starting of spyder is always very slow, how about using a binary/executable file?

### ISSUE THREAD

**Issue by 1900011604** [spyder-ide/spyder#16231]
[Feature Request]

It seems that Spyder starts by running a python program (as the shortcut leads to the `python.exe` installed) which is much slower than compiled language like C/C++, loading it takes about 10s, how about using a binary/executable file? We can change a python file into an executable file by [pyinstaller](https://www.pyinstaller.org/).

**Comment by ccordoba12** [comment]
Hey @1900011604, thanks for the suggestion. Unfortunately, Spyder itself is a Python program, so we can't change it to use a compiled language like C/C++.

It's correct that we could use Pyinstaller to package it as a single executable, but Spyder would still be using Python behind the scenes.

Finally, we are aware that Spyder takes too much time to start and have some plans to decrease it in the next months. Some improvements on that front went into our 5.1.1 version too (in case you're not using it, you'll see them once you update to it).

**Comment by ccordoba12** [comment]
I'm going to close this issue because there's nothing we can do about it.

**Comment by 1900011604** [comment]
Thanks! As the 5.1.1 version has not merged into conda, I will wait for the improvements.
