### ISSUE TITLE
I can not switch back to base environment

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#16245]
I have created a new environment named “b20”，I can switch to b20 and restart kernel，but when I switch back to base environment，the kernel can not start. I am using Anaconda3-2021.05-Windows-x86_64
![image](https://user-images.githubusercontent.com/5112397/130044514-a22438e8-e469-4ac4-8e71-840281d7a497.png)

https://user-images.githubusercontent.com/5112397/130044540-a25e1202-72bb-4cf8-80b4-0e480077eb89.mp4

**Comment by ccordoba12** [comment]
Hey @A-Pai, thanks for reporting. That error happens sometimes and we don't know how to fix.

If you have problems restarting the kernel, please try to open a new console instead. You can do that from the menu

    Consoles > New console

or from the Options menu (the one you're clicking in the video on the right).

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
