### ISSUE TITLE
Maximum character line slightly wrong

### ISSUE THREAD

**Issue by andprosoft** [spyder-ide/spyder#16248]
In Spyder 5.1.1, the maximum character line is slightly moved to the left, so that is does cross the characters at the maximum allowed position:

![len_80_spyder5](https://user-images.githubusercontent.com/79669161/130124885-03b7801a-0c4f-4f7e-ae62-b9298bdb46ca.png)

Same line of code in Spyder 3.3.6, maximum character line is displayed correctly:

![len_80_spyder3](https://user-images.githubusercontent.com/79669161/130124957-c5f782b2-9e57-4ec3-b0b4-7c36bc92e263.png)

**Comment by andprosoft** [comment]
Hi @ccordoba12 , thanks for the info.

Do you know maybe, where to look in the code?

**Comment by ccordoba12** [comment]
It could be in `spyder/plugins/editor/widgets/codeeditor.py` (not really sure though).

**Comment by sphh** [comment]
Well, I also noticed this and already wanted to open a new issue,but there were more pressing issues and now @andprosoft beat me to it!

**Comment by rhkarls** [comment]
I'd be happy to submit a PR with a simple fix for this if no one else is on it (@andprosoft ?)

**Comment by andprosoft** [comment]
@rhkarls No problems, go for it! ;)
