### ISSUE TITLE
Issue with starting kernel while attempting to use different interpreter for new python packages

### ISSUE THREAD

**Issue by cktdev** [spyder-ide/spyder#16251]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am new-ish to Spyder (and python), and am trying to install a new package (openpyxl) that is not native in Spyder. I have installed openpyxl, confirmed it is working in terminal (I am on a mac), pointed to the correct directory for the custom Python Interpreter, but get the following complaint from the console when booting: 

> An error ocurred while starting the kernel
> Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.
> 
> You can install it by running in a system terminal:
> 
> conda install spyder‑kernels=2.1
> 
> or
> 
> pip install spyder‑kernels==2.1.*

I run this command in terminal, but to no avail. Not sure how to resolve this.

### What steps reproduce the problem?

1. Booting Spyder from the custom interpreter
2. 
3. 

### What is the expected output? What do you see instead?
A working console

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.1
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Mac Mojave 10.14.6

### Dependencies

```
PASTE DEPENDENCIES HERE
```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.1 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)

**Comment by cktdev** [comment]
Okay, did a lot more reading and have a little more understanding of the situation I'm in. While in the spyder-env in terminal I ran:
`conda install spyder‑kernels=2.1`
as requested and got:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder‑kernels=2.1

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I followed that website which recommended I just run: 
`conda install spyder-kernels`

but that yielded the same error. Hmmm....

**Comment by steff456** [comment]
Hi @cktdev,

Can you please let me know in which way did you installed Spyder? Our preferred method if you are on macOs or Windows are our installers available here: https://github.com/spyder-ide/spyder/releases/tag/v5.1.1. Then you can add any dependency you need in another environment and link Spyder's Python Interpreter as stated in these instructions: https://docs.spyder-ide.org/current/faq.html#using-existing-environment

Please let me know if this helps, you can also try to reinstall Spyder in a clean environment and please remember to don't mix pip packages with conda, it can yield to damaging your environment.

**Comment by cktdev** [comment]
Hi Steff, 
I installed Spyder via the .dmg direct from spyder's website: 
https://github.com/spyder-ide/spyder/releases/latest/download/Spyder.dmg

Two your second point: yes, this is what I did. When I link to this new environment, the console would not launch and it gave me the error pasted above (Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed). It seems I can't do anything to get rid of that error.

To your third point "reinstall Spyder in a clean environment", I don't know what that means. Spyder seems to work fine, when it's linked to "default environment" (wherever that is). It's when I point to a the custom environment with the new Python package (openpyxl) in it, the problem starts. When I run Python direct in terminal in this custom envronment, everything runs fine, including `import openpyxl`.

Thanks for the reply and the help.

**Comment by steff456** [comment]
I see what is happening, which version of Spyder-kernels did you installed on your custom environment?

**Comment by ccordoba12** [comment]
@cktdev, this problem happens because (unfortunately) there are no conda packages for spyder-kernels 2.1 yet in Anaconda (they take some time to upload new versions).

However, you can create a conda environment from conda-forge (which is set of conda packages maintained by the community). For that, please use the following command:

    conda create -n py39 -c conda-forge openpyxl spyder-kernels=2.1

Notice the `-c conda-forge` there. That's what tells conda to use conda-forge. After that, connect Spyder to your `py39` environment from our Preferences.

Let us know if that works for you.

**Comment by cktdev** [comment]
That worked, thank you!!!

The catch: I was hit with a dialogue box warning about missing dependencies (rtree). Sure enough, I checked `conda list` and rtree is indeed not installed. 

Since py39 is a new environment (and I am new to Python), is it critical I install rtree with `conda install rtree` before trying `pip install rtree`? In my reading to try to solve this issue I saw that mixing conda and pip is not advised. So does this mean this py39 environment you helped me create only supports `conda install`? There are other packages I would like to install (e.g. numpy, pandas), so some advise here would be greatly appreciated. 

Thanks again!

**Comment by ccordoba12** [comment]
> That worked, thank you!!!

Great to know!

> The catch: I was hit with a dialogue box warning about missing dependencies (rtree)

I don't understand how you're getting that warning now and not before. Did you also install Spyder (besides openpyxl and spyder-kernels) in your py39 environment?

**Comment by cktdev** [comment]
I'm a little confused by your question. I installed Spyder via the .dmg direct from spyder's website:
https://github.com/spyder-ide/spyder/releases/latest/download/Spyder.dmg

This was a month or so ago. In preferences I then changed the Python interpreter to point to this new py39 directory (instead of "Default") as per:
https://docs.spyder-ide.org/current/faq.html#using-existing-environment
I did nothing else with my original Spyder install. Why would I install Spyder again? How would I install it _in_ my py39 directory?

**Comment by ccordoba12** [comment]
So the missing `rtree` dependency is displayed by our dmg installer after you changed you selected your py39 environment in preferences?

**Comment by cktdev** [comment]
That is correct. When I launch Spyder (Mac app from .dmg install), it pops up with a dialogue box warning of missing rtree depencies. This is the same Spyder app I've been using for the last month or so. As mentioned, rtree is missing in the new py39 environment you helped me create, so I guess I should install rtree.

Since py39 is a new environment (and I am new to Python), is it critical I install rtree with `conda install rtree` before trying `pip install rtree`? In my reading to try to solve this issue I saw that mixing conda and pip is not advised. So does this mean this py39 environment you helped me create only supports conda install? There are other packages I would like to install (e.g. numpy, pandas), so some advise here would be greatly appreciated.

**Comment by ccordoba12** [comment]
Ok, if you installed Spyder using our DMG installer, then there's no solution for the rtree problem you mentioned because it's self-contained and you can't change any packages on it.

The only thing I don't understand is how you're using it in Mojave (other people have mentioned it doesn't start for them there). I say it because you shouldn't see this error when using Catalina or Big Sur.

**Comment by cktdev** [comment]
Fair enough, regarding operating system differences.

However, since I'm pointing the Spyder interpreter to the custom enviroment py39 that you help me setup, can't I just `conda install rtree` in the py39 environment?

Also, I'm new here so any guidance on conda install rtree vs. pip install rtree vs. conda-forge rtree is appreciated.

**Comment by ccordoba12** [comment]
> However, since I'm pointing the Spyder interpreter to the custom enviroment py39 that you help me setup, can't I just conda install rtree in the py39 environment?

Sorry for the late response, but yes, you can. But the commands for that need to be

    conda activate py39
    conda install -c conda-forge rtree
