### ISSUE TITLE
can not connect to kernel

### ISSUE THREAD

**Issue by bowenbelongstonature** [spyder-ide/spyder#16254]
## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by steff456** [comment]
Hi @bowenbelongstonature,

Can you please add more information of the error that is appearing to you? Also, if you can add some screenshots it will be great!

Thanks for reporting!

**Comment by bowenbelongstonature** [comment]
> Hi @bowenbelongstonature,
> 
> Can you please add more information of the error that is appearing to you? Also, if you can add some screenshots it will be great!
> 
> Thanks for reporting!

I have Anaconda3 on my 64-bit Windows 10. I've installed Python3.7 as the base environment. For this base Python3.7, Spyder3.3.6 works well. 
Then I changed the platform to 32-bit by _set CONDA_FORCE_32BIT=1_ and I created a new Python2.7 envionment, and activated it by _activated python27_. After these, I tried to install Spyder for Python2.7 through _conda install spyder_, but this installed Spyder3.2.3 just cannot connect to kernel.

**Comment by bowenbelongstonature** [comment]
![图片1](https://user-images.githubusercontent.com/69409026/130583932-b5437732-b0ea-4541-9119-82fa01f5cbae.png)
![图片2](https://user-images.githubusercontent.com/69409026/130583937-9c0cc3d9-936b-4d68-b5eb-fda4dd20eeab.png)

**Comment by bowenbelongstonature** [comment]
> Hi @bowenbelongstonature,
> 
> Can you please add more information of the error that is appearing to you? Also, if you can add some screenshots it will be great!
> 
> Thanks for reporting!

I attach two screenshots as another comments
