### ISSUE TITLE
IPython incompatible error with canopy

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1625]
_From [iban...@gmail.com](https://code.google.com/u/110030004076630146924/) on 2013-10-30T02:30:33Z_

Spyder Version:  2.2.5
Python Version:  2.7.5
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.3 on Darwin
IPython >=0.13  :  1.1.0 (OK)
matplotlib >=1.0:  1.3.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.5.0:  0.5.0 (OK)
pylint >=0.25   :  1.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
sympy >=0.7.0   :  0.7.3 (OK) 

What steps will reproduce the problem?

1. Install Spyder via the disk image (DMG)
2. Preferences -> Console -> Advanced Settings -> Use the following Python interpreter -> (path to Enthought Canopy interpreter)
3. Restart Spyder
4. Interpreters -> Open an IPython console What is the expected output? What do you see instead? Expected an IPython console to open, instead got this message "Your IPyhton frontend and kernel versions are incompatible!! We're sorry but we can't create an IPython console for you" 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1625_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-11-03T05:12:38Z_

I verified this a couple of days ago. I'll have to investigate why we can't detect IPython under Canopy (that's why the message is shown). Thanks for reporting and for your interest in Spyder.

**Status:** Accepted  
  **Labels:** MS-v2.3 Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T12:53:07Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:53:13Z_

**Labels:** -MS-v2.3.1 MS-v2.4

**Comment by ccordoba12** [comment]
This was solved in 2.3.5.2
