### ISSUE TITLE
Outline pane is automatically shown when editor is maximized

### ISSUE THREAD

**Issue by newyorker123** [spyder-ide/spyder#16265]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I click the maximize current pane on the top tool bar to maximize editor, the outline pane automatically shown on the right side. But in the view option, the outline is actually not checked. I have to first check the outline option(nothing happens), then check it again to close the outline pane.
 
<img width="1440" alt="截屏2021-08-23 下午5 03 20" src="https://user-images.githubusercontent.com/43869995/130421441-2ce52a98-8e8a-4fbd-a355-5ce8f5027e94.png">

 

### What steps reproduce the problem?

1. click the maximize current pane to maximize editor
2. the outline pane is shown on the right side
3. 

### What is the expected output? What do you see instead?
Outline pane not shown.
Or at least the outline option should be checked when shown. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.1 (also happen in 5.0.5)
* Python version: 3.8.8
* Qt version: 
* PyQt version: 
* Operating System name/version: Mac BigSur

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @newyorker123,

When you hit maximize the editor, it will open by default the outline on the right side. What is weird is that the pane is not checked on the menu, we will look into to add the fix in our future releases.

Thanks for reporting!

**Comment by ccordoba12** [comment]
I propose to hide the last three actions of the Outline plugin (i.e. Unlock, Undock and Close) and show another one called `Do not show when the editor is maximized`. In addition, in case users would like to recover this functionality, they'd need to go to `View > Panes > Outline` to show it again. But for that, we need to update the Outline state in that menu when the editor is maximized (see https://github.com/spyder-ide/spyder/pull/19448#pullrequestreview-1109685546 for more context).

**Comment by JohnRobson** [comment]
Removing the "file path" above the tabs would be good to save screen space. The full path is already shown when the mouse is over the tab, so, this static "file path" info is unnecessary.
