### ISSUE TITLE
Upgraded to Spyder 5.0.5, spyder.ini keeps resetting

### ISSUE THREAD

**Issue by battaglia01** [spyder-ide/spyder#16262]
### Issue Report Checklist

* [✅] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [✅] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [✅] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [✅] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [✅] Tried basic troubleshooting (if a bug/error)
    * [✅] Restarted Spyder
    * [✅] Reset preferences with ``spyder --reset``
    * [✅] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [✅] Tried the other applicable steps from the Troubleshooting Guide
* [✅] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just upgraded from Spyder 5.0.0 to Spyder 5.0.5, and upon starting the program, it totally resets my spyder.ini. Once it has replaced it, Spyder then seems to think that the current spyder.ini is "good" and subsequent program launches don't cause any further reset. For whatever reason, it doesn't think my old spyder.ini from Spyder 5.0.0 is "good" in this way and if it's there then it will reset.

Is there some way to use my existing spyder.ini with the new version of Spyder, or at least auto-merge the settings from it? Or is there some setting in spyder.ini that needs to be set to not have it auto-reset like this?

### What steps reproduce the problem?

1. Upgrade from Spyder 5.0.0 to 5.0.5
2. Launch the program w/ the spyder.ini from Spyder 5.0.0
3. spyder.ini is replaced with a default version

### What is the expected output? What do you see instead?
I would like for it to use my existing spyder.ini in the new version, or auto-update it if need be

## Versions

* Spyder version: 5.0.5 None
* Python version: 3.9.5 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.22.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=1.0                  :  2.9.5 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  20.0.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.3.4 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.0 (OK)
scipy >=0.17.0                :  1.6.2 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @battaglia01, thanks for reporting. Please upload your spyder.ini file so we can take a look at it.

**Comment by battaglia01** [comment]
Apologies for this, looks like the problem was on my end - my original spyder.ini had somehow gotten overwritten. Looks like it's alright.
