### ISSUE TITLE
Spyder not added to Windows 10 start menu on miniconda install

### ISSUE THREAD

**Issue by jennirinker** [spyder-ide/spyder#16271]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [na] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [na] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [na] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Windows 10, miniconda3 (conda 4.10.3).

I keep spyder in a separate environment to prevent conflicts. Recently purged and recreated my spyder environment due to broken conflicts from 5.0 release, and now I do not have access to a Spyder icon in the start menu. This is inconvenient, because I cannot pin it to the start menu or taskbar so I must always launch a conda terminal and activate spyder before launching.

I tried pinning the `spyder.exe` executable to my start menu, but it doesn't work (Perhaps because Windows tries to launh the exe in a normal command window?) A picture of my Anaconda folder in the start menu is below.

![billede](https://user-images.githubusercontent.com/11503804/130599347-233cb812-ca0b-4a6c-b0e7-bf8208537455.png)

### What steps reproduce the problem?

1. Create a new python 3.9 environment.
2. Install spyder using `conda install spyder`
3. No start menu icon appears

### What is the expected output? What do you see instead?

I would like a start menu icon to be able to add to my task bar.

### Paste Traceback/Error Below (if applicable)

N/A

## Versions

* Spyder version: 5.1.1
* Python version: 3.9.6
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 Enterprise 21H1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.10.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)

```

**Comment by steff456** [comment]
Hi @jennirinker,

Can you please update to version 5.1.5 and let me know if the error persists?

**Comment by steff456** [comment]
Hi @jennirinker,

Have you tried to install Spyder directly from our Windows installer? The link is available here: https://github.com/spyder-ide/spyder/releases/tag/v5.1.1. Can you please uninstall and reinstall to see if it works?

**Comment by andprosoft** [comment]
Hi @jennirinker,

can you please also check, if there is a directory called ${DISTRIBUTION_NAME} in the start menu, where Spyder 5 is located? This is the issue I experience (see #16250 and ContinuumIO/anaconda-issues#12582).

**Comment by jennirinker** [comment]
@steff456 The standalone installer worked, so this issue must be particular to the installation via conda. You can choose whether you want to leave it open as a reminder that the conda version doesn't work as expected, or close if you want to just refer users to the Windows installer.

@andprosoft I did not have your issue when installing via the terminal. Because I have a working installation now, i don't plan on further debugging.

**Comment by ccordoba12** [comment]
Hey @jennirinker, to make Spyder appear in the Windows start menu when using Miniconda, you need to install the `menuinst` package:

    conda install menuinst

**Comment by ccordoba12** [comment]
Perhaps you need to reinstall Spyder after doing that too.
