### ISSUE TITLE
kernel not starting and high CPU usage on Apple M1

### ISSUE THREAD

**Issue by JulesLePrince** [spyder-ide/spyder#16274]
## Problem Description
When launching Spyder on MacBook Pro with apple M1. The consol tries to connect to the kernel without succeeding and the CPU usage of symptomsd and python are uncommonly high (from 80% to 180%) 

### What steps reproduce the problem?

1. launch Spyder

## Versions

* Spyder version:  5.1.1
* Python version: tested on 3.9.5 Internal / 3.9.6 custom
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: macOS 11.5.2

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.1 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

<img width="671" alt="Screenshot 2021-08-24 at 23 33 08" src="https://user-images.githubusercontent.com/31992334/130693016-cc34d35b-d5cd-4aa6-8a95-d7295c06ee08.png">

<img width="434" alt="Screenshot 2021-08-24 at 23 35 02" src="https://user-images.githubusercontent.com/31992334/130693188-a59eff2f-f8fa-495d-8878-2f75984d1447.png">

**Comment by dalthviz** [comment]
Hi @JulesLePrince thank you for the feedback! Could you try to launch Spyder from the terminal using the flag `--debug-info verbose` and put here the logs generated? Maybe there some clue regarding what is happening could appear. Let us know!

**Comment by ccordoba12** [comment]
Also, how did you install Spyder?

**Comment by JulesLePrince** [comment]
@dalthviz tanks for helping me, I pasted all the consol output but I think what might interest you is at the end.

- [pastebin consol output](https://paste.ubuntu.com/p/6KZJbdRtbw/)

**Comment by impact27** [comment]
@dalthviz I would say the best would be to profile spyder. If I am not mistaken `symptomsd` is related to crash reporting. Do you have a crash report window open?

The easiest way of profiling spyder is to clone from github an then running from the spyder folder:

`python -m cProfile -o out.prof bootstrap.py`

**Comment by dalthviz** [comment]
Thanks for the suggestions @impact27 ! @JulesLePrince let us know if you can profile Spyder to get more info and if you see any crash report while experiencing the high CPU usage (maybe checking the OS logs could be worthy to see if any message appears).

**Comment by ccordoba12** [comment]
I'd say you have a program blocking your internet traffic. Or perhaps this is caused by a VPN.

**Comment by JulesLePrince** [comment]
@ccordoba12 It could make sense since I started facing these issues after working on web requests with python and using Charles proxy and other proxies. However my proxy setting is disabled and I don't think a vpn, which I do not know is running, is redirecting the traffic since my Mac shows the ip of my router when using stuff like whatismyip.com or whatever. 
I am not aware of a program blocking the traffic, but it may be. How could I know if there is one ?

**Comment by JulesLePrince** [comment]
@impact27 No crash window opens. When cloning from the GitHub I get exactly the same problem 

```
julesleprince@Jules-MacBook-Pro spyder % python3 -m cProfile -o out.prof bootstrap.py
Executing Spyder from source checkout
*. Patched sys.path with /Users/julesleprince/clone/spyder
*. Patched sys.path with /Users/julesleprince/clone/spyder/external-deps/spyder-kernels
*. Patched sys.path with /Users/julesleprince/clone/spyder/external-deps/qdarkstyle
*. Patched sys.path with /Users/julesleprince/clone/spyder/external-deps/python-lsp-server
*. Installing PyLSP locally
warning: no files found matching 'versioneer.py'
*. Declaring completion providers
*. PyQt5 is detected, selecting
*. Imported Spyder 6.0.0.dev0 - Revision c6bf7de37, Branch: master
    [Python 3.9.6 64bits, Qt 5.12.10, PyQt5 5.12.3 on Darwin]
*. Running Spyder
Bootstrap completed in 00:00:00.6592
```

**Comment by JulesLePrince** [comment]
@dalthviz the OS logs seem pretty normal : 

```
Aug 30 23:06:27 Jules-MacBook-Pro com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.org.spyder-ide.33293983.33294006(501)> [17788]
Aug 30 23:06:28 Jules-MacBook-Pro Spyder[46535]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```

**Comment by impact27** [comment]
Maybe something messed up your localhost? You can check your /etc/hosts file that localhost is 127.0.0.1

**Comment by JulesLePrince** [comment]
I'm an absolute noob when concerning server and hosting, here is what I found : 

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

What port does Spyder kernel use? Maybe some other service is interfering with it?

**Comment by JulesLePrince** [comment]
Just desperately tried to reboot my computer (which I never do since new Mac chip manages power consumption well in sleep mode). It took more time than usual to reboot (dunno why) but Spyder restarted working. 
Sometimes I don't try to understand. However I think this could show that a task on my computer is doing shit and could do it again. I will try to inspect the tasks that are running. Anyway thanks a lot for your support and your patience :)

**Comment by ccordoba12** [comment]
> Anyway thanks a lot for your support and your patience :)

No worries. Glad you were able to sort this problem out.
