### ISSUE TITLE
AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'

### ISSUE THREAD

**Issue by DoRmAmMu1997** [spyder-ide/spyder#16278]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @DoRmAmMu1997 could you give us more information regarding your issue (OS, Python version, Spyder version, dependencies version, steps to reproduce the issue, etc)? Without more information there is not much we can do to help you, sorry :/

**Comment by ccordoba12** [comment]
This is a problem with the latest jupyter-client (i.e. version 7.0 or higher). For now, please downgrade to jupyter_client 6.1.12.

This will be fixed in our next version (5.1.2), to be released shortly.
