### ISSUE TITLE
Plots DPI Scaling setting keeps reversing

### ISSUE THREAD

**Issue by some-guy1** [spyder-ide/spyder#16297]
### What steps will reproduce the problem?

Using 4K resolution with graphics set to automatic.  Matplotlib windows are generated at a very small size.  

If I change resolution in 
Preferences->IPYthon console->Graphics->resolution

to much larger value e.g. 200 DPI, the matplotlib plots are readable and look good.  

However, when I close spyder and reopen it, despite the setting still being 200dpi, all matplotlib windows are again displayed at a very small scale.  Current fix is to change 200 to 70, click apply, change 70 to 200, click apply.  <-- every time I open spyder

**Comment by dalthviz** [comment]
@juanis2112 @some-guy1 I was able to reproduce this :+1:

Just in case @some-guy1 for the workaround you can also change the value from 200 to 199 and again to 200 and then click `Apply` and/or `Ok`
