### ISSUE TITLE
Variable Explorer Shows Works For Only One Script

### ISSUE THREAD

**Issue by asgardee** [spyder-ide/spyder#16294]
### What steps will reproduce the problem?

Steps to Reproduce:
1. Create/Open a simple script script (Eg. "folder1/Test1.py")
2. Run script
3. Create/Open a new simple script script (Eg. "folder2/Test2.py")
4. Run new script

Personal Troubleshooting Steps:
In the above steps, I found that Spyder only shows the variables in the first script. I have tried:
- Switching the working director to "folder2"
- Deleting the orinial script ("Test1.py")
- Restarting Spyder

Notes:
- Both scripts have variables to show (pandas data frames primarily)
- Both scripts in my case share a root folder ("projects/folder1/Test1.py" and "projects/folder2/Test2.py")

**Comment by ccordoba12** [comment]
Hey @asgardee, thanks for reporting. Could you post a video or animated gif of the problem you're seeing? I really don't understand what's happening in your case.

You can create animated gifs using the [Licecap](https://www.cockos.com/licecap/) program.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
