### ISSUE TITLE
Spyder object exploer fails to open objects without a built in viewer.

### ISSUE THREAD

**Issue by Roweboat02** [spyder-ide/spyder#16300]
### Issue Report Checklist

* [y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [y] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [y] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [y] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [y] Tried basic troubleshooting (if a bug/error)
    * [y] Restarted Spyder
    * [y] Reset preferences with ``spyder --reset``
    * [n] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/) (##Should this be removed or edited now that the recommended instillation method is the standalone installer?)
    * [y] Tried the other applicable steps from the Troubleshooting Guide
* [y] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Objects without built in viewers fail to open from the variable explorer. Arrays, and python built-ins all work as expected. After trying, a buffering symbol spins infinitely in the top right of the variable explorer. Spyder gives no help on solving this error.
****(I know it says explicitly not to report on GitHub, but I'm like 90% convinced this is a spyder standalone issue. Even if it's not, spyder giving no errors or indication on the source of the problem IS a spyder problem, so that has to be fixed regardless)

![image](https://user-images.githubusercontent.com/81272472/131220408-b9375da1-6f29-4587-86a5-e8a6f85a749e.png)
that message appears when I try to open a chess.Board object from the python-chess module
![image](https://user-images.githubusercontent.com/81272472/131220452-3acd9fea-8134-40f6-a4b1-71e8d1e52300.png)
That appears when I try to open the class shown below.
```
class Test:
    def __init__(self):
        self.interger = 1
```
The spyder internal console provides no feedback or errors and the IPython provides none as well. The problem exists when the object is created in the both IPython console and the code editor. I have tried updating spyder and qt5 and essentially anything else that I could think of that would have an impact on this. I have reset and deleted everything to do with spyder already, this is essentially as fresh an install of python and spyder I could get after fixing a couple dependency issues already.

I'm aware the issue is almost definitely in the fact that I have the spyder standalone version, I originally had anaconda, but I was having a lot of dependency issues with anaconda (trying to install spyder 5 broke my instillation, after fixing that updating tensorflow also broke my instillation ect. ect.)

Thanks in advanced.

### What steps reproduce the problem?

1. Create a class or import one without a built in viewer
2. Open the class in the variable explorer

### What is the expected output? What do you see instead?
Ideally I would like to see the object explorer window pop up and let me see the internal variables to objects, but instead the error window pops up.

### Paste Traceback/Error Below (if applicable)
Internal console does not output anything.
This is the only error I get (pretty non-descript, hey?)
![image](https://user-images.githubusercontent.com/81272472/131220940-e1ddd466-f943-4915-99bc-381ef503b297.png)

## Versions
* Spyder version: 5.1.1 None
* Python version: 3.7.9 64-bit (#### Spyder says this, despite me not having python 3.7 installed. I have 3.9.6. and it says I have 3.9.6 in the bottom right of spyder. The standalone was installed when I only had 3.9.6 installed and I have set the default interpreter to 3.9.6. The only python version in my path is 3.9.6. I don't know if this is connected, if I'm not understanding something or if this should be an issue all to its ownself. If python 3.7 is expected/required, I have not seen this stated anywhere.)
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.3 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)

```

**Comment by steff456** [comment]
Hi @Roweboat02,

I'm unable to reproduce this issue, can you please upload a gif/video to see if I'm doing the steps as you are doing?

**Comment by Roweboat02** [comment]
@steff456 The shortest series of steps were essentially just, (in the Ipython console),
```
import chess
a = chess.Board()
```
Then double click on a in the variable explorer.

I would upload a video, but I have since given up. All the time I would have spent on coding in the last week was spent on triage, fixing bugs and trying to get spyder to somewhat work. Thanks anyways, I appreciate it.

If anyone ever ends up here from a search engine, the only solution I can offer is it seems spyder stand alone is not quite where it needs to be yet. So for the time being, uninstalling, gritting your teeth and dealing with anaconda is the best path if you want to keep using spyder.
