### ISSUE TITLE
VCRUNTIME140_1.dll not Found

### ISSUE THREAD

**Issue by Imoh-mfon** [spyder-ide/spyder#16313]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
The code execution cannot proceed because VCRUNTIME140_1.dll not found after installing Spyder. How do i get this resolved
![Capture](https://user-images.githubusercontent.com/3820813/131393037-aa22c68c-e57b-4758-a33d-367101e7a9ae.PNG)

**Comment by ccordoba12** [comment]
Hey @Imoh-mfon, thanks for reporting. I'm going to ask @dalthviz to chime in here because he knows the solution to this problem.

**Comment by dalthviz** [comment]
This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/14897. @Imoh-mfon maybe you can try this: https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954

**Comment by ccordoba12** [comment]
Thanks @dalthviz for your help! I'm going to close this one in favor of #14897.

**Comment by Imoh-mfon** [comment]
Excellent solution. It solved the challenge, thank you so much for the support
