### ISSUE TITLE
Git Integration No longer Working in Spyder 5.0.5?

### ISSUE THREAD

**Issue by AldoMaine** [spyder-ide/spyder#16310]
### What steps will reproduce the problem?

Recently had to do a fresh anaconda install based on Python 3.8 and it came with Spyder 5.0.5.  (Windows 10)
In the Spyder Project pane, I used to be able to RMB and select "Commit" to update my git repo.  This option is no longer there.   
I can run the Git Gui from Windows and I installed the git package from conda to no avail.

**Comment by steff456** [comment]
Hi @AldoMaine,

Can you please upload a screenshot with the error you are seeing? Also, if you can upgrade to Spyder 5.1.1 and let us know if the error persists

Thanks for reporting!

**Comment by AldoMaine** [comment]
![Image 1](https://user-images.githubusercontent.com/11415077/131499445-49d8d0ec-dacc-42ae-bef7-07d32ac33f68.png)
This is the context menu I get when I RMB on the Python folder (also the root of my only git repo).  I believe I should see "Commit" in the context menu.

**Comment by AldoMaine** [comment]
Created a clean python 3.9.6 environment and installed Spyder 5.1.1
I am now seeing the expected context menu entries.   
![Image 2](https://user-images.githubusercontent.com/11415077/131540225-78d14061-da42-4d25-9ae6-cd2af11e700f.png)

**Comment by steff456** [comment]
Great! I'm glad we could solve your issue! Since you could fix it with the latest version I'm going to close this issue. Thanks for reporting!
