### ISSUE TITLE
No Output on Spyder iPython Console

### ISSUE THREAD

**Issue by Imoh-mfon** [spyder-ide/spyder#16325]
![No Output](https://user-images.githubusercontent.com/3820813/131561179-f68e1432-5854-4319-9915-a835ce6acf43.PNG)

Spyder version information
* Spyder version: 5.1.1 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

a. I am not getting an output, see what I am getting: 
runfile('C:/Users/Akan/Exercises/untitled0.py', wdir='C:/Users/Akan/Exercises')
b. What should I do to correct this?

**Comment by ccordoba12** [comment]
Hey @Imoh-mfon, you need to evaluate your function if you want to see any output in the console.

In other words, you need to add to your code

```python
hello()
```
