### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by gperez1404** [spyder-ide/spyder#16345]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
it is hard to connect Spyder with ArcGIS desktop these days. The old ArcGIS product runs under python 2.7 and it is not possible to select any python 2.7 as interpreter using Spyder 4 o later. 

It is not easy to isntall spyder 3 using ANACONDA.

**Comment by ccordoba12** [comment]
Hey @gperez1404, thanks for reporting. You said

> he old ArcGIS product runs under python 2.7 and it is not possible to select any python 2.7 as interpreter using Spyder 4 o later

I don't know how you're trying to connect Spyder to the Arcgis interpreter, but this is not correct. The only thing you need to do is to install spyder-kernels in Arcgis with pip and then select its interpreter in the menu

    Tools > Preferences > Python interpreter

Thar's better described in our docs:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

and it works even with our latest version (5.1.3).

**Comment by ccordoba12** [comment]
Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
