### ISSUE TITLE
The help can't always get the right python documentation

### ISSUE THREAD

**Issue by Vincent0706** [spyder-ide/spyder#16355]
I found a problem:
when I use ctrl+I to search for the information about the function or others, the spyder always can't find the right information. I must input full path in the help bar. I think this make this function a little inconvenient. Whether or not can improve this?

![image](https://user-images.githubusercontent.com/82581024/132037970-b116e498-6417-46f6-a16b-4c67ada78215.png)
![image](https://user-images.githubusercontent.com/82581024/132037998-4f4d71cc-12a0-4b86-a3bc-163a9ae2dc8f.png)
![image](https://user-images.githubusercontent.com/82581024/132038048-0efc13e5-6f25-46eb-98f1-524adc713019.png)
![image](https://user-images.githubusercontent.com/82581024/132038073-c34a9a82-f258-4f33-be6b-07692372d127.png)

* Spyder version: 5.1.2 None
* Python version: 3.9.5 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
Hey @Vincent0706, thanks for reporting. This is a known isuue and we'll try to fix it in a future version.

For now there's nothing you can do about it, sorry.
