### ISSUE TITLE
Quick navigation does not work

### ISSUE THREAD

**Issue by Leohanhart** [spyder-ide/spyder#16354]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I cant you quick navigation on the library pannel. if i click on a function the screen does not move to that section. 
This works on all the other files or if i coppie the code to an other file it also works but after saving the quick navigation fails. 

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Leohanhart** [comment]
Look forward to your reaction

**Comment by juanis2112** [comment]
Hi @Leohanhart thanks for reporting. Can you please fill on the versions requested in the template? We need to know the following in order to address your issue:

Spyder version:
Python version:
Qt version:
PyQt version:
Operating System name/version:

**Comment by juanis2112** [comment]
Closing due to lack of response
