### ISSUE TITLE
Outline explorer seeing impported symbols from relative import with tuple syntax

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#16352]
### What steps will reproduce the problem?

I have a django project that does some imports as follows:

```python
from .models import Marksheet, MarkType, ProjectAssignment, Project, StudentReport
from .forms import (
    MarksheetListForm,
    ProjectAssignmentForm,
    FinalizeMarksForm,
    ProjectCopySourceForm,
    ProjectAssignmentFilter,
    BulkMarksheetsImportForm,
    BulkTurnitinImportForm,
    BulkUploadMinervaAssignmentForm,
)
from .tables import BaseTable, MarkColumn, ProjectTable, AllProjectTable
```

In 5.1.2 nearly all of these symbols are correctly suppressed in the outline explorer EXCEPT for the import from .forms.

It's not as simple as the tuple syntax in the import as I also have the following lines which are all correctly suppressed:

```python
from phys_utils.views import (
    IsStaffViewMixin,
    IsSuperuserViewMixin,
    MultiFormMixin,
    FormListView,
)
from phys_utils.response import PDF_TemplateResponse, CSV_TemplateResponse
```

So it seems like it is a combination of both the relative package import and the tuple syntax. 

Unfortunately, black is rath fond of the tuple formatting of the long import :-) !

**Comment by ccordoba12** [comment]
Hey @gb119, thanks for reporting. I'll take a look at this one for 5.2.0 (hopefully it won't be too hard to solve).
