### ISSUE TITLE
runfile() got an unexpected keyword argument 'current_namespace'

### ISSUE THREAD

**Issue by davidRFB** [spyder-ide/spyder#16376]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I execute the debbuger a typerror appears :  TypeError: runfile() got an unexpected keyword argument 'current_namespace'
When I execute the file normally the script works fine. 

I saw that this problem was fixed in spyder4.1. however, I am using the last version of spyder. Recently reinstalled. 

### What steps reproduce the problem?

1. Click the debugger button 
2. 
3. 

### What is the expected output? What do you see instead?
Enter to debugger mode

### Paste Traceback/Error Below (if applicable)

```python-traceback
debugfile('/home/david/Documents/Dorian/PythonClass/bacdive/temp.py', wdir='/home/david/Documents/Dorian/PythonClass/bacdive')
Traceback (most recent call last):

  File "/tmp/ipykernel_20181/737198206.py", line 1, in <module>
    debugfile('/home/david/Documents/Dorian/PythonClass/bacdive/temp.py', wdir='/home/david/Documents/Dorian/PythonClass/bacdive')

  File "/home/david/anaconda3/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py", line 589, in debugfile
    enter_debugger(

  File "/home/david/anaconda3/lib/python3.8/site-packages/spyder_kernels/customize/spyderpdb.py", line 773, in enter_debugger
    debugger.run(code)

  File "/home/david/anaconda3/lib/python3.8/site-packages/spyder_kernels/customize/spyderpdb.py", line 716, in run
    super(SpyderPdb, self).run(cmd, globals, locals)

  File "/home/david/anaconda3/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)

  File "<string>", line 1, in <module>

TypeError: runfile() got an unexpected keyword argument 'current_namespace'

```

## Versions

* Spyder version: 5.0.5            py38h06a4308_2 
* Python version: 3.8
* Qt version:   5.12.9               hda022c4_4    conda-forge
* PyQt version: pyqt                      5.12.3           py38h578d9bd_7    conda-forge

* Operating System name/version: Ubuntu 18.04

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.10.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @davidRFB, thanks for reporting. Please update to our 5.1.3 version (already available in conda-forge) to get the fix to this problem.

If you're mixing conda and conda-forge packages, please create a new environment for Spyder 5.1.3 because conda and conda-forge packages are binary incompatible. You can do that with the following commands:

    conda create -n spyder-env -c conda-forge spyder
    conda activate spyder-env
    spyder

**Comment by ccordoba12** [comment]
Let us know if that works for you.

**Comment by davidRFB** [comment]
Everything works fine !! 

Thank you very much
