### ISSUE TITLE
Auto save files before running

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#16374]
Hi Spyder team,

In Spyder 4, the Python files are automatically saved when I clicked "run".  This is gone in Spyder 5.

Is there a way to bring back this feature?  (Or has this become configurable somewhere?  I don't seem to be able to find it.)

Thanks!

**Comment by steff456** [comment]
Hi @jsh9,

Indeed we removed that behavior in Spyder 5, @ccordoba12 there's an option for this?

**Comment by ccordoba12** [comment]
This is working fine for me on Linux. A couple of questions for you @jsh9:

* Are you running untitled files? I mean, files that you haven't saved to disk yet? In that case, we can run those files without asking the user to save them (that was a very requested feature).
* What operating system are you using?

**Comment by ccordoba12** [comment]
@steff456, I don't understand how you were able to reproduce this. Could you post an animated gif of the process you followed?

**Comment by jsh9** [comment]
Hi @ccordoba12 , I was not running untitled files.  Instead, I ran saved `.py` files: I opened them from the hard drive, made changes, and clicked "run", and they were not saved.

I was using macOS Catalina.

**Comment by ccordoba12** [comment]
Then I think this is a problem in Mac only because I can't reproduce it on Linux.

**Comment by steff456** [comment]
@ccordoba12 what I understood @jsh9 is that he wants to go back to saving the file if he presses `run`. I'm not sure if we completely removed that behavior or if there is a way to set that option in preferences.

**Comment by ccordoba12** [comment]
Oh, I see what you mean. Well, that option is here:

![imagen](https://user-images.githubusercontent.com/365293/133287178-7c26b47d-a68f-406b-af4f-35fb28f81853.png)

@jsh9, is it activated for you and still Spyder is not saving files before running them?

**Comment by jsh9** [comment]
Yes, I'm seeing this option now (I didn't know where to find this option before).  I guess the default was changed from "yes" (in Spyder 4) to "no" (in Spyder 5).

**Comment by jsh9** [comment]
I'm closing this issue because it isn't actually a bug.
