### ISSUE TITLE
Editor becomes sluggish when displaying errors

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#16384]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The whole program becomes so slow after some time, that it is not even possible to save the file and close Spyder.

This is obviously related to how many errors are displayed beside the line numbers.

If I start the program, it gives you a snappy response, even if errors are displayed, but after some time the editor becomes sluggish. The main Spyder process uses 100% of one CPU core. If I manage to modify my code to be error-free, the sluggish response goes away - until the next error is displayed. The high CPU load appears after the errors are displayed beside the line numbers but before they are displayed in the flag area near the scrollbar.

Sometimes if you make an edit, which causes a lot of errors, Spyder does not respond at all. Then it is not even possible to save the file and close Spyder. When that happens I watched the system monitor and found not only that the main Spyder process uses 100% of one CPU core but also its memory consumption increases continuously.

## Set-up

I have only two panes open:
- Editor, split horizontally to show two files. (The behaviour described above appears if I have the same file shown in both editors. I don't know for sure, if it also appears if two different files are shown.)
- Outline

## Preferences

My settings from `Completion and linting` are as follows (only the active items are shown).
- General
    [x] Enable code completion
    [x] Show completion details
    [x] Show completions on the fly
    [x] Enable Language Server Protocol server
    [x] Enable text snippets provider
- Linting
    [x] Enable basic linting
    [x] Underline errors and warnings
- Introspection
    [x] Enable Go to definition
    [x] Follow imports when going to a definition
    [x] Show calltips
- Code style and formatting
    [x] Show vertical line at that length (79)
    [x] Enable hover hints
- Docstring style
- Advanced
- Other languages
    - [None]
- Snippets
    - [Default]

## Additional Information

See also #15631. The PR #16206 improved the situation quite a lot.

## Versions

* Spyder version: 5.1.3
* Python version: 3.8.10 64-bit
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Linux Mint 20.2

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  57.5.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.2 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @sphh, thanks for opening this issue and the detailed info on how to reproduce this error.

I'm also observing this problem with a file that has a lot of linting warnings. I'll try to fix it and release 5.1.4 asap because it adds way too much sluggishness to the editor.

**Comment by ccordoba12** [comment]
Hey @sphh, I just released 5.1.4. Please try it and let us know how it works for you.

I tested it as much as I could and it seems to be working much better than before.

**Comment by sphh** [comment]
Thanks @ccordoba12 for the quick fix. So far, Spyder never stopped working. Sometimes it is still slow for a short period, but it always recovered and got back to the original speed. So far so good!!

**Comment by ccordoba12** [comment]
> Sometimes it is still slow for a short period, but it always recovered and got back to the original speed

Yeah, I also noticed that odd behavior and wonder why that's the case. But good new is that Spyder's editor appears to not be slowing down anymore.
