### ISSUE TITLE
Help pane won't go away

### ISSUE THREAD

**Issue by lukecherveny** [spyder-ide/spyder#16382]
### What steps will reproduce the problem?

The help pane keeps reappearing when Spyder reopens. If I close it when it's a quadrant, it comes back when Spyder restarts. If I unlock panes, attach the help pane to the console pane so it is a tab and center focus on the console, then when Spyder restarts the focus is on the help pane.

tl;dr: I hate the help pane and don't want to see it

**Comment by dalthviz** [comment]
Hi @lukecherveny thanks for the feedback! I was able to reproduce this.

@ccordoba12 is this an expected behavior?

**Comment by ccordoba12** [comment]
Hey @lukecherveny, @dalthviz, this is a duplicate of issue #15331. We'll try to fix it in our next release.
