### ISSUE TITLE
kernel failer when fiiting model

### ISSUE THREAD

**Issue by MansMayaki** [spyder-ide/spyder#16393]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I tried to fit a tensorflow model using GPU. the kernel keep dying

**Comment by ccordoba12** [comment]
Hey @MansMayaki, thanks for reporting. This is most likely not a problem with Spyder but with your code.

Since you didn't provide more details, we can't help you more, sorry.

**Comment by ccordoba12** [comment]
The most probable cause is lack of ram or maybe an incorrect detection of your gpu.
