### ISSUE TITLE
Modal dialog post resolution rescale locks up Spyder

### ISSUE THREAD

**Issue by GroovyGeek** [spyder-ide/spyder#16390]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When Spyder detects a monitor resolution change it pops up a modal dialog prompting a Spyder restart.  When this dialog is triggered after a laptop shutdown the modal dialog is in the background, hidden behind the main Spyder window and locks up all of Spyder.  The only way to resolve is to force terminate and restart Spyder.

### What steps reproduce the problem?

1.  Connect laptop to an external monitor with resolution different from that of the built-in monitor
2.  Launch Spyder and leave it running
3.  Shut down laptop and disconnect from the external monitor
4. Wake up laptop and log back in - Spyder is now frozen with no means to acknowledge the modal resolution rescaling dialog other than a forced termination and restart

### What is the expected output? What do you see instead?

Modal dialog is in the foreground, or the dialog is not modal.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.5 but also present in 4.2.5
* Python version: 3.8.10
* Qt version: 
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @GroovyGeek, thanks for reporting. We'll try to fix this in our next version (5.2.0), to be released next month.
