### ISSUE TITLE
Cursor Stuck in Select 

### ISSUE THREAD

**Issue by 1ea4ez7z6** [spyder-ide/spyder#16394]
### What steps will reproduce the problem?

I have been encountering an extremely troublesome problem - my cursor gets stuck in select mode. The effect is that if I click once, any time from there on out that I move my cursor, it is selecting text, which leads to all kinds of headaches. This problem only happens in Spyder. It happens in the code editor and the console alike. I have tried resetting Spyder to factory defaults and updating to the latest version, (Spyder 5.0.5), but the problem persists. I am running Ubuntu 20.04.3 LTS.

**Comment by ccordoba12** [comment]
Hey @1ea4ez7z6, thanks for reporting. I don't understand your problem very well. Please record a video or animated gif so we can see what's happening in your case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
