### ISSUE TITLE
Spyder hangs during (before) startup

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1640]
_From [joostdel...@gmail.com](https://code.google.com/u/113970803338771488720/) on 2013-11-11T04:32:21Z_

Spyder Version:  2.2.3
Python Version:  2.7.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes 0.5.0     :  None (OK)
pep8 >=0.6         :  None (NOK)
IPython >=0.13;<1.0:  0.13.2 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.1.3 (OK)
matplotlib >=1.0   :  1.3.0 (OK)
sympy >=0.7.0      :  0.7.3 (OK)
pylint >=0.25      :  0.28.0 (OK) 

What steps will reproduce the problem?

 1. install winpython distribution 
2. start spyder from either .exe in main winpython dir, or bat in scripts 3. What is the expected output? What do you see instead? Instead of startup of Spyder, app hangs in dos-box. 

Please provide any additional information below

. Win7, 64bit. Problem started after some time. No admin privs. 

\<ctrl>-c gives a traceback:
Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "D:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\spyderli
b\start_app.py", line 70, in main
    if not lock.lock():
  File "D:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\spyderli
b\utils\external\lockfile.py", line 153, in lock
    pid = readlink(self.name)
  File "D:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\site-packages\spyderli
b\utils\external\lockfile.py", line 89, in readlink
    fObj = _open(os.path.join(filename,'symlink'), 'rb')
  File "D:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\ntpath.py", line 73, i
n join
    elif isabs(b):
  File "D:\WinPython-64bit-2.7.5.3\python-2.7.5.amd64\lib\ntpath.py", line 58, i
n isabs
    return s != '' and s[:1] in '/\\'
KeyboardInterrupt

Uncommenting most stuff in start_app, foregoing the lock-file stuff, to just:
    options, args = get_options()
    from spyderlib import spyder
    spyder.main()
fixes the problem.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1640_

**Comment by spyder-issues-migrator** [comment]
_From [huth.a...@gmail.com](https://code.google.com/u/107947503986383242548/) on 2013-12-04T16:08:04Z_

I have been having the same issue with Spyder 2.2.0. Also Win7 x64, also using WinPython-32-bit-2.7.5.1 for 4-5 months with no issues. I had not been able to start the program normally for over a week. The machine is powered down nightly. Seems a continue on line 158 of lockfile.lock was causing an infinite loop:

143            try:
144                symlink(str(os.getpid()), self.name)
145            except OSError, e:
...
151                if e.errno == errno.EEXIST:
152                    try:
153                        pid = readlink(self.name)
154                    except OSError, e:
155                        if e.errno == errno.ENOENT:
156                            # The lock has vanished, try to claim it in the
157                            # next iteration through the loop.  
158                            continue

Having also read 1453 and 1441 I looked in my user directory for the spyder.lock folder but didn't find it. Only when I looked into the above call to readlink() did I see that the value being sent to readlink was:
u'C:\WinPython-32bit-2.7.5.1\settings\.spyder2\spyder.lock'

Having located the spyder.lock folder, I deleted it, and am now able to run Spyder as before.

This problem is NOT for lack of pywin32; WinPython-32bit-2.7.5.1 is distributed with pywin32 version 218.

**Comment by goanpeca** [comment]
Seems like an old issue, closing @ccordoba12 ?

**Comment by ccordoba12** [comment]
Sure.

**Comment by ccordoba12** [comment]
Let's mark this one as a duplicate of issue #2363 to investigate the suggestion provided in the second comment.
