### ISSUE TITLE
Update features page with profiler screenshot

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1641]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-11-11T13:58:25Z_

contrebasse: there's nothing about the profiler plugin in the feature section : https://code.google.com/p/spyderlib/wiki/Features

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1641_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-11-11T11:00:26Z_

issue #822 has been merged into this issue.

**Cc:** pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-11-13T06:04:54Z_

issue #822 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-11-13T06:05:56Z_

**Owner:** ccordoba12  
  **Cc:** -pierre.raybaut  
  **Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-04T15:44:33Z_

**Labels:** -MS-v2.3 MS-v2.3.1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-17T18:52:50Z_

**Labels:** -MS-v2.3.1 MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-25T22:25:09Z_

**Labels:** -Easy

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:07:53Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2014-10-31T15:46:14Z_

http://www.cockos.com/licecap/

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:10:53Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
This doesn't make sense now that we are on Github.
