### ISSUE TITLE
%debug magic does not work repeatably for untitled files

### ISSUE THREAD

**Issue by madphysicist** [spyder-ide/spyder#16417]
### What steps reproduce the problem?

1.  Create a simple file with a single cell with like this:
    ```
    #%% define foo
    def foo(bar):
        x = ['a']
        for i in range(100):
            x.append(i + 3)
        return x
    ```

2. Execute the file using the green arrow:
    ```
    runfile('.../test.py', wdir='...')
    ```

3. Place a breakpoint in line 4:
    ![image](https://user-images.githubusercontent.com/4617010/133154988-7add913e-f8e1-4330-85ff-65aee56b301b.png)

4. Run a `%debug` magic on `foo` with any argument:
    ![image](https://user-images.githubusercontent.com/4617010/133155073-55f32d81-2b73-4a7f-bcc5-c06c59964e87.png)

    Enters debugging normally:
    ![image](https://user-images.githubusercontent.com/4617010/133155246-31447d69-de4d-45ba-a88b-cf220b5b1841.png)

5. Quit debugging (or step through) and try again

    ![image](https://user-images.githubusercontent.com/4617010/133155442-5bd7f462-e959-483c-8249-e7f3b74bf52d.png)
    ![image](https://user-images.githubusercontent.com/4617010/133155499-561c85b8-4a88-4f25-9458-5591cdaa1768.png)

    Only "s" appears to work, and pressing "c" ignores the breakpoint entirely:

    ![image](https://user-images.githubusercontent.com/4617010/133155629-14788800-717b-4eae-b876-4aa213f26b04.png)

## Expected Behavior

I expect `%debug` to work twice, especially when I don't modify the file.

## Attempted solutions:

1. Rerun the file:
    ![image](https://user-images.githubusercontent.com/4617010/133160634-4295270d-5c20-48b0-81ff-79ae01d49252.png)
    Does not work
2. Modify the file, save it, then rerurn and attempt to debug. Output shows that the modification propagated to the `foo` in the console:
    ![image](https://user-images.githubusercontent.com/4617010/133160974-1ba63e2b-e9f0-41a4-8595-085a63c1ddbf.png)
    ![image](https://user-images.githubusercontent.com/4617010/133160923-d7247644-8527-4ab6-bc07-54a42ff69875.png)
    Does not work.
3. Clear all variables. Does not work.
4. Restart kernel (or IDE). That works as expected every time. But doesn't seem like that's a very good solution.

## Comment

The reason that I mention cells in the example is that ideally, I would like to reload my code by running the cell rather than the entire file. The files I have at the moment are sort of like notebooks that I am using the cell functionality to run. I would love not to have to reload the entire file (mush less the kernel), every time I made a change just to the function I'm trying to debug.

## Versions

* Spyder version: 4.1.5
* Python version: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.22.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.8.1 (OK)
pylint >=1.0                   :  2.7.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.0.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  20.0.0 (OK)

# Optional:
cython >=0.21                  :  0.29.23 (OK)
matplotlib >=2.0.0             :  3.3.4 (OK)
numpy >=1.7                    :  1.20.1 (OK)
pandas >=0.13.1                :  1.2.4 (OK)
scipy >=0.17.0                 :  1.6.2 (OK)
sympy >=0.7.3                  :  1.8 (OK)
```

**Comment by steff456** [comment]
Hi @madphysicist,

Thanks for reporting, I was able to reproduce this issue. @impact27, do you know why this is happening?

**Comment by madphysicist** [comment]
@steff456 Thanks for confirming. I always have a lingering doubt that I missed something stupid in the docs or configuration when I post bug reports.

**Comment by impact27** [comment]
It looks like the breakpoints are broken for unsaved files. Can you reproduced for a saved file?

**Comment by madphysicist** [comment]
@impact27 the file was saved in this example. I used the name `untitled0.py` out of laziness, but it was on disk in my documents folder as indicated in the output.

**Comment by impact27** [comment]
I can't reproduce with the latest 5.x

**Comment by impact27** [comment]
To solve this for unsaved files, we could remove the last two lines of https://github.com/spyder-ide/spyder-kernels/blob/master/spyder_kernels/customize/namespace_manager.py , but that would mean the files stay cached forever

**Comment by madphysicist** [comment]
@ccordoba12 Thank you!

**Comment by ccordoba12** [comment]
@impact27 was the one who really fixed this one.

**Comment by madphysicist** [comment]
@impact27 thank you for the fix. I look forward to using it
