### ISSUE TITLE
Add code signing to macOS installer

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#16414]
We should add code signing to the macOS application and/or DMG file.

**Comment by juanis2112** [comment]
I would like to set up a meeting to work on this @mrclary and @ccordoba12. Can you tell me when does it fit better for both of you?

**Comment by mrclary** [comment]
I'm available 
* Mon 9/20 from 2-3pm PDT
* Tues 9/21 after 12pm PDT
* Wed 9/22 from 2-3pm PDT
* Thurs 9/23 all day
* Fri 9/24 before 3pm PDT

**Comment by mrclary** [comment]
https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
