### ISSUE TITLE
run cell can not open 

### ISSUE THREAD

**Issue by Yahia18** [spyder-ide/spyder#16418]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
run cell can not open

**Comment by steff456** [comment]
Hi @Yahia18,

Can you please elaborate on what problem did you encounter in Spyder? Can you please give me the details on how to reproduce it and in what version of Spyder are you working on?

Thanks for reporting!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
