### ISSUE TITLE
Spyder now needs admin rights to open

### ISSUE THREAD

**Issue by ModernShrub** [spyder-ide/spyder#16426]
Hi,
I have an issue regarding spyder. I had installed spyder usong Anaconda, and it used to run without any admin permissions. Even after updating Anaconda, conda and Spyder, it used to run properly. But after installing Norton, spyder and Anaconda need admin permissions. Admin permission was required after about a month after installing Norton. I have no idea how to reproduce this. I have tried uninstalling and installing and resetting Spyder. Nothing worked. Please help

**Comment by ccordoba12** [comment]
Hey @ModernShrub, thanks for reporting. Unfortunately, this is not a problem with Spyder, but an issue with your computer setup,so we can't help you.

My only advice would be to un install Norton, which is the one causing the problem.
