### ISSUE TITLE
no button for pausing in the debug mode?

### ISSUE THREAD

**Issue by seyeeet** [spyder-ide/spyder#16430]
Sorry if I am wrong. But in spyder 5.1.5 I cannot find a button to pause the debugging after running it!
can you please let me know how I can pause the debugging?

**Comment by ccordoba12** [comment]
Hey @seyeeet, thanks for reporting. Please post a screenshot of what you're seeing because I don't understand very well your problem.

**Comment by seyeeet** [comment]
in other APIs when we start debuging we can pause it. in spyder unless we have a check point we cannot pause the debugging
e.g. figure below shows the pausing ability in vscode
![aa](https://user-images.githubusercontent.com/62394093/133913723-65953ff2-b4a3-442d-934c-5928b8bc7f25.png)

**Comment by ccordoba12** [comment]
Yeah, that's not possible in Spyder and we don't have plans to implement it for now. I mean, I don't know how that could work in our debugger, sorry.
