### ISSUE TITLE
Enhancement: Adding a Watchlist plugin to Spyder (code available)

### ISSUE THREAD

**Issue by rear1019** [spyder-ide/spyder#16438]
I have opened this issue to explore if the Spyder developers and users are interested in adding a Watchlist plugin to Spyder. We have developed such a plugin and are willing to upstream it.

What is a Watchlist? This is a functionality some IDEs offer while debugging code. A Watchlist is related to the display of all variables accessible in the current scope (aka Variable Explorer in Spyder). But there is an important distinction: A Watchlist consists of a _user-definable_ list of _expressions_. These expressions are evaluated after a debugger step and the result of the evaluation is displayed. See the screencast below.

Features:
* List of expressions can be edited at any time
* Expressions can be added by several means (toolbar buttons, right click menu, double clicking at the end of the list, drag & drop of text)
* Existing entries can be changed (double click)
* The value of an expression is shown in bold font if its value changes after a debugger step

Notes:
* PyCharm seems to call this functionality "Watches", see #14629
* Its best to wait until #15922 is merged before adding the plugin. Initially, it has been developed against Spyder v4.2.x and ported to v5.0.5. We could add the plugin without #15922, however, at some point it should be ported to the API provided by #15922 anyway.

https://user-images.githubusercontent.com/33811443/133749289-14d56e84-129f-4683-9ab0-bcc762c3f126.mp4

**Comment by marekkolman** [comment]
@rear1019 Great job! I'd love to have this in my Spyder. When I develop a code, I spend 80% of my time in debug so this would really help with productivity.

What are the supported data types in the *Value* column? Could it be e.g. *pd.Series*, or just the native python data types?

**Comment by rear1019** [comment]
The Watchlist is not data type aware (see below for reason). The _Value_ column does not support features known from the Variable Explorer, such as editing or plotting of variables.

It is possible to use any data type inside the expression: The _Value_ column is determined by the stringified result of the evaluation of the corresponding _Expression_ column. In terms of Python code: `value = str(eval(expression, globals, locals))`.

**Comment by rear1019** [comment]
@ccordoba12 Sorry for the long time without any response. Unfortunately, we couldn’t work on upstreaming the plugin… The good news: Now we can.

The plugin is now available in the branch `watchlist` in our forked repositories of Spyder and spyder-kernels [1][2]. Feel free to try it out (there is one known issue, see https://github.com/procitec/spyder/commit/438141f04f2dda542d947bfab96516084547b47b). At your liking, we can proceed either following way:
* The plugin is integrated into Spyder (i.e. as a built-in plugin).
* The plugin is published as an external plugin. Note that the plugin requires some additions to `spyder_kernels`. They should by part of the “official” `spyder_kernels` package in order to ease the plugin’s installation.


[1] https://github.com/procitec/spyder
[2] https://github.com/procitec/spyder-kernels

**Comment by ccordoba12** [comment]
> Sorry for the long time without any response

No problem, I know everybody is busy!

> Unfortunately, we couldn’t work on upstreaming the plugin… The good news: Now we can.

That's great news!

> The plugin is published as an external plugin. Note that the plugin requires some additions to spyder_kernels. They should by part of the “official” spyder_kernels package in order to ease the plugin’s installation.

I like this alternative the most because we already have too much to maintain. I reviewed your changes to spyder-kernels and they seem good. Please open a PR with them so we can see how to integrate them.

**Comment by rear1019** [comment]
@ccordoba12 We have prepared the Watchlist plugin to be released as an external plugin. There is still a minor issue which can be ignored for now. As of now I think it’s actually an issue in Spyder; I will look into it and come back.

Please let me know if https://github.com/spyder-ide/spyder-kernels/pull/381 will be accepted. I understand that this PR is a critical patch. Strictly speaking the patch is not required for the Watchlist plugin, however, it’s very nice to have and the Variable Explorer benefits as well. Once the status of the PR is decided, I will make a PR for changes in `spyder-kernels` which are definitely required (as mentioned before).

**Comment by ccordoba12** [comment]
> We have prepared the Watchlist plugin to be released as an external plugin.

Thanks for letting us know about it!

> Please let me know if https://github.com/spyder-ide/spyder-kernels/pull/381 will be accepted

Yes, it will. I've just been busy preparing our 5.3.1 release, but I'll take a look at ti afterwards. In the meantime, I'll ask the developer that designed our debugger to take a look at it.

**Comment by rear1019** [comment]
The Watchlist plugin is now available on PyPI [1]

[1] https://pypi.org/project/spyder-watchlist/

**Comment by rear1019** [comment]
> Congratulations @rear1019!! That's awesome!
> 
> To let the Spyder community know about your plugin, I think it'd be great if you'd like to write a short blog post about it in our [blog](https://www.spyder-ide.org/blog/). As you can see, we haven't published anything in a long time, but this could be a pretty good opportunity to kick start it again. After that, we could promote it in our Twitter account as well.
> 
> What do you say?

We are happy to write a blog post. I will contact you in the course of the next week to get things going.

**Comment by ccordoba12** [comment]
Great! Looking forward to it.

**Comment by rear1019** [comment]
Closing: The Watchlist plugin is now available on PyPI.

[1] https://pypi.org/project/spyder-watchlist/
