### ISSUE TITLE
[BUG] 5.1.5 Variable Explorer : new variables not showing up

### ISSUE THREAD

**Issue by Kochise** [spyder-ide/spyder#16437]
Spyder 5.1.5, Windows 10

Behavior :
-

When **debugging** code, new variables do not show up in the Variable Explorer's table, even when clicking the 'Refresh variables' button.

Works when playing with the console when **NOT debugging** code, though.

Expected :
-

New variables appearing in real-time in the Variable Explorer's table when **debugging** code.

**Comment by ccordoba12** [comment]
Hey @Kochise, please post a simple code that generates this problem and, if possible, also upload a video or animated gif that shows the error.

**Comment by Kochise** [comment]
Here we go...
![Spyder_5 1 5_debug_variable_explorer](https://user-images.githubusercontent.com/23077417/133973908-4d94da0f-fd66-4727-98a6-61827a848bf0.gif)

**Comment by rear1019** [comment]
Private variables (any variable starting with an underscore) are hidden by default. This also applies to the console (try entering `_a = 10` there). Uncheck "Exclude private variables" in the options menu of the Variable Explorer to make these variables visible.

**Comment by Kochise** [comment]
@rear1019 Seriously... Thanks.

![Spyder_5 1 5_debug_variable_explorer_exclude](https://user-images.githubusercontent.com/23077417/133993533-8eaed1d0-c005-40b5-ad03-53c73ef7fe90.gif)

**Comment by Kochise** [comment]
FP = False Positive
