### ISSUE TITLE
Spyder 5.1.3 standalone installation not available from command line

### ISSUE THREAD

**Issue by adin786** [spyder-ide/spyder#16440]
## Problem Description
I've installed Spyder standalone on Windows, as recommended by [the installation guide](https://docs.spyder-ide.org/current/installation.html).  I can run Spyder from the start menu, or it's shortcut, but can't run `spyder` using the command line or anaconda prompt, in either the base env or with an activated virtual environment.  
- I can't see an easy way to add spyder to the system path, as it seems to normally launch from some kind of python script rather than a batch file or .exe.
- I have my conda setup with existing virtual environments.  I'm following the [this faq section](https://docs.spyder-ide.org/5/faq.html#using-existing-environment) on how to use spyder with virtual environments.

Does the standalone version of spyder not work this way?  I wanted to have a single installation of spyder, outside of my conda install and switch between my conda environments by just changing Spyder's default interpreter each time... or ideally by activating the conda env and launching it with the `spyder` command from anaconda prompt (as I can do with vscode for example).

### What steps reproduce the problem?

1. Install Spyder standalone version
2. Create conda environment, activate it
3. Run `spyder` from anaconda prompt

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What is the expected output? What do you see instead?
I'm expecting Spyder to launch when the `spyder` command is run from the command line

### Paste Traceback/Error Below (if applicable)
At the anaconda prompt:
```cmd
(my_env) C:\...path... > spyder
'spyder' is not recognized as an internal or external command,
operable program or batch file.
```

## Versions
* Spyder version: 5.1.3 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies
None

**Comment by juanis2112** [comment]
Hi @adin786 thanks for reporting this. Unfortunately the Standalone version of spyder doesn't work by running "spyder" in your command line. It has to be done via the entry on the menu or the shortcut. 
However, you can use Spyder with any conda environment by changing Spyder's default interpreter as you mentioned.
Please let me know if there is anything else I can help with.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
