### ISSUE TITLE
Installing latest Spyder from conda-forge rather than anaconda/main?

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#16459]
I've already noted in a couple of other (closed: https://github.com/spyder-ide/spyder/issues/15707) issues (e.g. https://github.com/ContinuumIO/anaconda-issues/issues/12429) that the latest version of Spyder is very tardily updated on the Anaconda main channels (so for e.g. [5.0.5 anaconda/main](https://anaconda.org/main/spyder) vs [5.1.5 anaconda/conda-forge](https://anaconda.org/conda-forge/spyder)).

Is there any reason why installing from conda-forge preferentially is a bad idea?

**Comment by steff456** [comment]
Hi @durack1,

We actually are recommending to install Spyder from the conda-forge channel, to get the latest versions, the important thing is that all your extra dependencies are also installed using the conda-forge channel. In this way, you will not have incompatible binaries in one environment. Also, we have installers for macOS and Windows as another option.

Hope this helps!

**Comment by durack1** [comment]
@steff456 thanks for the clarity, it will solve the long-standing issue of having to wait for the Anaconda `main` to be updated, which in my experience has been many months..
