### ISSUE TITLE
 you may need to restart the kernel to use updated packages.
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by jekwupeter** [spyder-ide/spyder#16452]
### What steps will reproduce the problem?

Im a newb in programming. I wanted to change coding environment because i thought my conda environment was corrupted. 

I decided to download spyder IDE and install. After installation i cant seem to install packages.
Im getting this error

pip install python-nmap
Note: you may need to restart the kernel to use updated packages.
The filename, directory name, or volume label syntax is incorrect.

**Comment by ccordoba12** [comment]
Hey @jekwupeter, thanks for reporting. Please see this FAQ in our docs to understand how to install packages that don't come with it:

http://docs.spyder-ide.org/current/faq.html#dropdown-11

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
