### ISSUE TITLE
python turtle graphics not responding

### ISSUE THREAD

**Issue by Zeina90** [spyder-ide/spyder#16455]
### Issue Report Checklist

* [ y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [y ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [y ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [y ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [y ] Tried basic troubleshooting (if a bug/error)
    * [ y] Restarted Spyder
    * [ y] Reset preferences with ``spyder --reset``
    * [y ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ y] Tried the other applicable steps from the Troubleshooting Guide
* [y ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

when running the script below for the first time it runs correctly. but when I re-run it, python turtle graphics window not responding, 
### What steps reproduce the problem?

1. import turtle
2. bob=turtle.Turtle()
3. print(bob)
4. for i in range(4):
      bob.fd(100)
      bob.lt(90)

turtle.mainloop()

### What is the expected output? What do you see instead?
expected window with a drawing
instead: not responding window

### Paste Traceback/Error Below (if applicable)

```python-traceback

runcell(0, 'E:/Python/mypolygon.py')
Traceback (most recent call last):

  File "E:\Python\mypolygon.py", line 9, in <module>
    bob=turtle.Turtle()

  File "C:\Users\zeina\anaconda3\envs\spyder\lib\turtle.py", line 3814, in __init__
    RawTurtle.__init__(self, Turtle._screen,

  File "C:\Users\zeina\anaconda3\envs\spyder\lib\turtle.py", line 2558, in __init__
    self._update()

  File "C:\Users\zeina\anaconda3\envs\spyder\lib\turtle.py", line 2661, in _update
    self._update_data()

  File "C:\Users\zeina\anaconda3\envs\spyder\lib\turtle.py", line 2647, in _update_data
    self.screen._incrementudc()

  File "C:\Users\zeina\anaconda3\envs\spyder\lib\turtle.py", line 1293, in _incrementudc
    raise Terminator

Terminator
```

## Versions

* Spyder version: 5.0.5
* Python version: 3.9
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                :  4.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by steff456** [comment]
Hi @Zeina90,

Can you please update to Spyder 5.1.5 and try again? It is working as expected on my end.

**Comment by oijqws** [comment]
I have same issue here. Is there a better way to use turtle?
![image](https://user-images.githubusercontent.com/38936048/188054284-1cde0257-a580-4469-9f89-bb870433244c.png)

import turtle
p = turtle.Pen()
p.forward(100)
p.left(90)

**Comment by ccordoba12** [comment]
@oijqws, you need to select the Tkinter graphics backend by going to the menu

    Tools > Preferences > IPython console > Graphics > Graphics backend

Then you need to close Spyder and reopen it again.

**Comment by dalthviz** [comment]
Hi @oijqws maybe this wiki page could help: https://github.com/spyder-ide/spyder/wiki/How-to-run-turtle-scripts-within-Spyder

**Comment by ccordoba12** [comment]
Closing due to lack of response.
