### ISSUE TITLE
Installation fails for MacOs M1 miniforge

### ISSUE THREAD

**Issue by ms003** [spyder-ide/spyder#16463]
I have installed miniforge for running tensorflow on MacOS M1 from here:https://github.com/apple/tensorflow_macos/issues/153

I have created , activated environment but this does not seem to support spyder.
When I try to install with conda install -c conda-forge spyder it returns spyder is not available

and when I try to install by pip3 install spyder
it returns error
ERROR: Could not find a version that satisfies the requirement pyqtwebengine<5.13 (from spyder) (from versions: 5.14.0, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4)
ERROR: No matching distribution found for pyqtwebengine<5.13 (from spyder)

Is there to fix this?

**Comment by ccordoba12** [comment]
Hey @ms003, thanks for reporting. Unfortunately, Spyder can't be run natively in m1 chips because some of its dependencies haven't been compiled for that platform.

This problem will be solved in conda-forge in a couple of months. With pip, I can't say because we don't have control over that.

**Comment by ccordoba12** [comment]
I'm going to close this issue because this is not something we can solve here, it needs to be addressed in conda-forge.

Just be patient and try again at the end of October or November.
