### ISSUE TITLE
Kernel restarting with importing TensorFlow

### ISSUE THREAD

**Issue by my-hawary** [spyder-ide/spyder#16462]
### What steps will reproduce the problem?

I tried to run the following code

import tensorflow as tf

the kernel restarted after that.

**Comment by ccordoba12** [comment]
Hey @my-hawary, thanks for reporting. if your error is the same as the one reported you repirted on issue #16461, please follow the instructions on that issue. That's the only way to solve it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
