### ISSUE TITLE
Split window vertically and horizontally are reversed  ( or menu entries are mixed up)

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1647]
_From [chessren...@googlemail.com](https://code.google.com/u/103854681419856887153/) on 2013-11-19T05:59:09Z_

Spyder Version:  2.2.5
Python Version:  2.7.5
Qt Version    :  4.8.4, PySide 1.2.1 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1.Split window horizontally opens a window right after the old window
and not below, as horizontally would imply 2. 3. What is the expected output? What do you see instead? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1647_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-11-19T04:26:05Z_

This is more a terminology problem : you're thinking about the direction of the line splitting the window while the spyder devs thought about the direction of concatenation of the subwindows.

For me it is logical that after spliting vertically, I get one window over the other.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T15:30:27Z_

Yep, the icons are quite clear about the splitting way, even if words can be confusing :-)

**Status:** WontFix

**Comment by lgpage** [comment]
I would very much like this to be re-considered.
The terminology (wording) is wrong and messes me up every time I work with Spyder to give lectures.
In almost all other programs a vertical split is a split window by a vertical line and a horizontal split is a split window by a horizontal line.

I doubt there are many people who would consider window splits in terms of the direction of concatenation of windows.
Most people would consider a window split in terms of the line splitting the windows or in terms of how the windows are stacked.

**Comment by ccordoba12** [comment]
@goanpeca, what do you think?

**Comment by goanpeca** [comment]
@lgpage you are actually advocating for changing the text or?

```
horizontal split (which is more like horizontal divider) != split horizontally
vertical split (which is more like horizontal divider) != split vertically
```
The adverb (word ending in **ly** in this case) express the "under what conditions something is done", in this case the **split**. So split vertically means precisely that, to split in the vertical direction.

**Comment by lgpage** [comment]
@goanpeca fair enough, from a strictly English language point of view it is correct :P
I do, however, think that changing the wording to `horizontal split` and `vertical split` (as you wrote above) would make this a little less ambigious.

What do you think?

**Comment by goanpeca** [comment]
`Horizontal split` is not an action, whereas `Split horizontally` IS an action.

The correct/less ambiguous action would be: **Add/Insert horizontal/vertical divider**.
