### ISSUE TITLE
LSP Python and Kite Stuck at "starting" and "initializing" respectively.

### ISSUE THREAD

**Issue by npvarma** [spyder-ide/spyder#16473]
Python 3.8.10 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Linux 5.4.0-84-generic  (Ubuntu)
Standalone install (no conda)

* Reset to factory settings. 
* Enabled, disabled, uninstalled/installed kite, and installed/uninstalled python language server.
* Restarting from bottom pane does not help. Still stuck at "restarting".

![image](https://user-images.githubusercontent.com/49216377/134446145-ce6de11f-774a-4b68-921a-694d98044698.png)

**Comment by ccordoba12** [comment]
Hey @npvarma, thanks for reporting. This is (most probably) a firewall issue. Please check that your iptables rules (or whatever other firewall you use on Linux) allow traffic in `locahost`.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
