### ISSUE TITLE
runfile() got an unexpected keyword argument 'current_namespace'

### ISSUE THREAD

**Issue by rohitmathur507** [spyder-ide/spyder#16475]
### What steps will reproduce the problem?

Hello All,

Getting the issue of runfile() got an unexpected keyword argument 'current_namespace' while trying to debug a file. So request you all to please help me out on this issue.

Thank You
Rohit Mathur

## Versions

* Spyder version: 4.1.5 
* Python version: 3.6.12
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.7 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.9.0 (OK)
pylint >=1.0                   :  2.9.6 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.1.0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.0.2 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.2.1 (OK)

# Optional:
cython >=0.21                  :  0.29.24 (OK)
matplotlib >=2.0.0             :  3.3.4 (OK)
numpy >=1.7                    :  1.19.2 (OK)
pandas >=0.13.1                :  1.1.3 (OK)
scipy >=0.17.0                 :  1.5.2 (OK)
sympy >=0.7.3                  :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @rohitmathur507, thanks for reporting. Please downgrade IPykernel to version 5 to solve this problem. For that, please close Spyder, open the Anaconda Prompt and run there

    conda install ipykernel=5

Let us know if it works for you.

Also, in the future try not to run `conda update --all` (in case you're doing it) because it introduces this kind of problems.

**Comment by leavor** [comment]
@ccordoba12, I encountered the same problem, as per your suggestion, the problem has been solved. the ipykernel was downgraded from 6.4.1 to 5.3.4
I encountered this problem after upgrading Python from 3.7.9 to 3.8.12

**Comment by rohitmathur507** [comment]
Hi, I deleted my anaconda, and then just installed the latest version of spyder, and that worked for me. 
Thank you very much for your all you support and instant response. 
Also if you help me out in one more issue related to installing of the module in python environment using pip.

So when I am trying to install awscli using pip install awscli, the version it automatically detecting is 1.20.47, but I want to install  awscli==2.20.40. So when I try to install this version using the command pip install awscli==2.20.40, it says "ERROR: Could not find a version that satisfies the requirement awscli==2.2.40" even though the version is actually available publicly. So, it would really be great if you guys could help me on that.

Also, Thank You very much once again for taking time to look into my issue and give an instant response.

Best Regards,
Rohit Mathur

**Comment by leavor** [comment]
@rohitmathur507, as you can see, the latest version is 1.20.47, there is no version you want
![image](https://user-images.githubusercontent.com/1759365/134653473-caac58aa-0fa2-4def-90d4-09cdca8d26a1.png)

**Comment by rohitmathur507** [comment]
Thanks @leavor for the clarity. I'll close the issue now. 
Thanks 👍
