### ISSUE TITLE
How to set up an environment using Spyder on a machine with no internet access and added modules

### ISSUE THREAD

**Issue by aseeley98** [spyder-ide/spyder#16481]
### Issue Report Checklist

* [*] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ *] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [* ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [* ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ *] Tried the other applicable steps from the Troubleshooting Guide
* [ 2/3] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am new to Spyder and I am trying to set up Spyder with added modules on a Windows computer with no internet access. I successfully installed  Spyder by installing it to a disk from a computer with internet access. However, I run into problems when I try to import modules as .whl files. I understand pip is not included with Spyder. I tried using sys/os as well and was not successful in importing the modules. Do I need to completely create my environment with everything on a computer with internet access then clone everything over? Or is there a better and more efficient method? 

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5
* Python version: 3.9
* Qt version: 5
* PyQt version: 
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @aseeley98, thanks for reporting. What are you using to create your environment? Pip or conda?

**Comment by aseeley98** [comment]
Hi, thank you for your email. I used miniconda to create my environment.
But I used both to download modules. (Some modules like tensorflow I could
not download with conda).

The link below under the paragraph titled “Conda Pack” there are directions
that I believe may work. I have not tried it yet, but I am hoping it will
work.

https://www.anaconda.com/blog/moving-conda-environments

Best,

Aaron

**Comment by ccordoba12** [comment]
Yeah, I recommend you using conda-pack for this. Let us know how it goes.

**Comment by aseeley98** [comment]
I was able to pack the environment and load it into my other computer. However, I am having a difficult time connecting Spyder to the environment. After completing step 7 listed in the link [below] I cannot find the .exe file to connect to Spyder. When in the cwd in the anaconda prompt I can see all the modules so I know everything transferred correctly. However, the file is not executable so it can not be used with Spyder.

[https://gist.github.com/pmbaumgartner/2626ce24adb7f4030c0075d2b35dda32](url)

**Comment by ccordoba12** [comment]
What exe file are you exactly referring to?

**Comment by aseeley98** [comment]
I’m referring to the environment I transferred over from my computer either
internet. Conda-pack required me to turn it into an executable file to run
on a windows computer with spyder.

**Comment by ccordoba12** [comment]
And what's the name of the executable?

**Comment by aseeley98** [comment]
the name of the exe is  \conda-unpack.exe

the following code is what I used

cd unpacked-environment
.\Scripts\activate.bat
.\Scripts\conda-unpack.exe

**Comment by ccordoba12** [comment]
Ok, then I can't help you further with this because I don't why that's happening and I haven't used conda-pack.

Please open an issue in their repo to get additional feedback:

https://github.com/conda/conda-pack
