### ISSUE TITLE
jupyter notebook files doesn't render and couldn't execute in Spyder

### ISSUE THREAD

**Issue by ski123786** [spyder-ide/spyder#16513]
### What steps will reproduce the problem?

1) Open a Jupyter notebook in spyder 5.1.5 and observe that the file content is not rendered properly as a notebook in Spyder IDE.

2) Also, there is no provision to execute the Jupyter notebook through Spyder IDE.

* Spyder version: 5.1.5 None
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
Hey @ski123786, thanks for reporting. We have this third-party plugin to render Jupyter notebooks inside Spyder:

https://github.com/spyder-ide/spyder-notebook

However, it doesn't work with Spyder 5 yet, but we hope to update it before the year ends.
