### ISSUE TITLE
Error leads to restarting kernel: related to jupyter.widget - ERROR:traitlets:No such comm target registered: jupyter.widget

### ISSUE THREAD

**Issue by moonj94** [spyder-ide/spyder#16526]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am running a spectrotemporal receptivefield model from MNE. When it gets to the fitting process, it restarts the kernel at 0% completed. When  check the terminal, I get the following error message

`ERROR:traitlets:No such comm target registered: jupyter.widget`

### What steps reproduce the problem?

```
Y=np.random.randn(256,100)
speech=np.random.randn(256,100)
tmin,tmax=0,Y.shape[0]/256
n_delays=int((tmax-tmin)*sfreq)+2
n_splits=3
cv=KFold(n_splits)
n_channels=64
# speech=np.random.randn(256,1)
# Y=np.random.randn(256,64)
rf=ReceptiveField(tmin,tmax,sfreq,feature_names=['envelope'],estimator=1,scoring='corrcoef')
coefs = np.zeros((n_splits, n_channels, n_delays))
scores = np.zeros((n_splits, n_channels))
for ii, (train, test) in enumerate(cv.split(speech)):
    print('split %s / %s' % (ii + 1, n_splits))
    rf.fit(speech[train], Y[train])
    scores[ii] = rf.score(speech[test], Y[test])
    # coef_ is shape (n_outputs, n_features, n_delays). we only have 1 feature
    coefs[ii] = rf.coef_[:, 0, :]
times = rf.delays_ / float(rf.sfreq)

# Average scores and coefficients across CV splits
mean_coefs = coefs.mean(axis=0)
mean_scores = scores.mean(axis=0)

# Plot mean prediction scores across all channels
fig, ax = plt.subplots()
ix_chs = np.arange(n_channels)
ax.plot(ix_chs, mean_scores)
ax.axhline(0, ls='--', color='r')
ax.set(title="Mean prediction score", xlabel="Channel", ylabel="Score ($r$)")
mne.viz.tight_layout()
```

### What is the expected output? What do you see instead?
I expect to see the code run

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.7.10
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: macosx big sur 11.5.1 (20G80)
* MNE version: 0.23.4
### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @moonj94, thanks for reporting. Your code is missing some things so we can't run it in our side. Please provide a simple and reproducible example we can run in our side.

Also, could you test if you can run it in JupyterLab or Jupyter notebook? If that's not the case, then it shouldn't be related to Spyder because we use the architecture as them.

**Comment by moonj94** [comment]
I am not really familiar with jupyer notebook, and I am not sure how it relates to spyder. 

This is really weird. when I run the example script here: https://mne.tools/stable/auto_examples/decoding/receptive_field_mtrf.html#sphx-glr-auto-examples-decoding-receptive-field-mtrf-py, I do not get any issues and get the output that I expect. But when I use my own data and basically the same analysis script the kernel restarts by itself..

**Comment by moonj94** [comment]
@ccordoba12  here is a standalone code:
```

import mne
from mne.decoding import ReceptiveField
from sklearn.model_selection import KFold
from matplotlib import pyplot as plt
import numpy as np
sfreq=256
Y=np.random.randn(256,64)
speech=np.random.randn(256,1)
tmin,tmax=0,Y.shape[0]/256
n_delays=int((tmax-tmin)*sfreq)+2
n_splits=3
cv=KFold(n_splits)
n_channels=64
rf=ReceptiveField(tmin,tmax,sfreq,feature_names=['envelope'],estimator=1,scoring='corrcoef')

# speech=np.random.randn(256,1)
# Y=np.random.randn(256,64)
coefs = np.zeros((n_splits, n_channels, n_delays))
scores = np.zeros((n_splits, n_channels))
for ii, (train, test) in enumerate(cv.split(speech)):
    print('split %s / %s' % (ii + 1, n_splits))
    rf.fit(speech[train], Y[train])
    scores[ii] = rf.score(speech[test], Y[test])
    # coef_ is shape (n_outputs, n_features, n_delays). we only have 1 feature
    coefs[ii] = rf.coef_[:, 0, :]
times = rf.delays_ / float(rf.sfreq)

# Average scores and coefficients across CV splits
mean_coefs = coefs.mean(axis=0)
mean_scores = scores.mean(axis=0)

# Plot mean prediction scores across all channels
fig, ax = plt.subplots()
ix_chs = np.arange(n_channels)
ax.plot(ix_chs, mean_scores)
ax.axhline(0, ls='--', color='r')
ax.set(title="Mean prediction score", xlabel="Channel", ylabel="Score ($r$)")
mne.viz.tight_layout()
```

**Comment by moonj94** [comment]
I think the issue might be with the cross validation because if I just do 
`rf.fit(spech,Y)` without using training/testing then the code works just fine. Not sure what the issue is especially since it is working on the example code.

**Comment by ccordoba12** [comment]
Hey @moonj94, thanks for the reproducible example. You said:

> I am not really familiar with jupyer notebook, and I am not sure how it relates to spyder.

Jupyter and Spyder use the same architecture to run code. So if your code fails to run on Jupyter, it means it's not due to an Spyder error.

> I think the issue might be with the cross validation

Could it then be a problem with MNE? To check, please run your code either using Jupyter or (if you don't feel comfortable with that), in the command line with

    python my_code.py

**Comment by moonj94** [comment]
@ccordoba12 I have tried running the code in terminal python and it gave me a "segmentation fault 11"

**Comment by moonj94** [comment]
Can anyone help with this? @ccordoba12 

I am running a different code for the calculation of spectrotemporal receptive fields (eelbrain toolkit) and the kernel keeps restarting in the middle of the code! I updated jupyer, spyder kernel etc and it did not help at all. Now I am not getting a message that says `ERROR:traitlets:No such comm target registered: jupyter.widget`. I have no idea why the kernel keeps restarting.

**Comment by ccordoba12** [comment]
> I have tried running the code in terminal python and it gave me a "segmentation fault 11"

This means that the problem is not related to Spyder and that's why the kernel is restarting. It could be caused by the way you installed MNE: maybe you used pip to install it in a conda environment?

In any case, we can't help you to solve your problem here because we don't have experience with MNE, sorry. Please report it with that project so you can receive appropriate help about it.

**Comment by moonj94** [comment]
@ccordoba12 Please ignore the segmentation fault 11. That was one time. Please address my new comment. I am able to run on jupyter notebook, but not on Spyder. That suggests that it is a spyder issue.

**Comment by ccordoba12** [comment]
> Now I am not getting a message that says ERROR:traitlets:No such comm target registered: jupyter.widget

If the code you're running always displays this message and then restarts, it means that it can only be run in Jupyter, not in Spyder.

I'm afraid for now there's nothing we or you can do about it, sorry.
