### ISSUE TITLE
Spyder 5.0.5 author verification needed for MacOS 11

### ISSUE THREAD

**Issue by T-Wainwright** [spyder-ide/spyder#16538]
### Issue Report Checklist

* [* ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [* ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When downloaded from the standalone explorer located here: https://www.spyder-ide.org/ the unpackaged app will not run, instead hitting the " "Spyder” cannot be opened because the developer cannot be verified. " error. 

I note a number of the steps to fix the problem focus on the use of Anaconda and Anaconda navigator, and using this as a portal to install the program allows it to work fine. However this defeats the point of having a standalone installer, as anaconda navigator can be extremely heavy and slow to set up at times. Either the author verification issue should be fixed, or the standalone explorer should be removed and no longer advertised on the website.

I note there was a similar issue around a year ago, which appears to have been fixed since it was closed? (So I assume the standalone explorer worked for a bit at least!)

### What steps reproduce the problem?

1.  Download Spyder on MacOS 11 from the standalone explorer located: https://www.spyder-ide.org/
2.  Install Spyder and drop it to applications folder
3.  Run Spyder

### What is the expected output? What do you see instead?
Expected output: the app opens

Actual output: "Spyder” cannot be opened because the developer cannot be verified.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.0.5
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: MacOS 11.6 (Big Sur)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @T-Wainwright, thanks for reporting. We understand this can be a nuisance when installing Spyder, especially for newbies because they probably don't know what do to disable the security settings necessary to install our app.

Right now @mrclary is working on it (see #16490), so hopefully our next version (5.2.0, to be released later this month) won't have this problem.

**Comment by ccordoba12** [comment]
I'm going to close this issue in favor of #16414 because it was reported there for the first time.
