### ISSUE TITLE
Installer-based Spyder does not start on Windows

### ISSUE THREAD

**Issue by giumas** [spyder-ide/spyder#16537]
Using the latest installer, Spyder does not start on Windows. It only shows the splash screen, then nothing else happens. (How to activate the console or debug logging?)

I suspect that it is related to https://github.com/spyder-ide/qtawesome/issues/167 because it works when I change the Untrusted Font Blocking setting (described in https://docs.microsoft.com/en-US/troubleshoot/windows-client/shell-experience/feature-to-block-untrusted-fonts). Unfortunately, the listed solutions in the Microsoft page cannot be applied on the target machines.

**Comment by dalthviz** [comment]
Note: For now fix the fallback to the Spyder 2 icon set so if the icons are not available due to the font load error, Spyder should use the old Spyder 2 icon set which doesn't rely in loading fonts.

**Comment by dalthviz** [comment]
By the way @giumas to debug you can launch the installed Spyder from a terminal running the `Target` specified in the generated shortcut and changing `pythonw.exe` for `python.exe`. It should be something like this (where `<your user>` is the current session user directory):

```

C:\Users\<your user>\AppData\Local\Programs\Spyder\Python\python.exe "C:\Users\<your user>\AppData\Local\Programs\Spyder\Spyder.launch.pyw"

```

If you want even more information you can run it with the `debug-info verbose` flag, so something like this:

```

C:\Users\<your user>\AppData\Local\Programs\Spyder\Python\python.exe "C:\Users\<your user>\AppData\Local\Programs\Spyder\Spyder.launch.pyw" --debug-info verbose

```
