### ISSUE TITLE
error -215 assertion

### ISSUE THREAD

**Issue by Sreevallilikhitha** [spyder-ide/spyder#16535]
### What steps will reproduce the problem?

C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-uzca7qz1\opencv\modules\dnn\src\layers\fully_connected_layer.cpp:181: error: (-215:Assertion failed) srcMat.dims == 2 && srcMat.cols == weights.cols && dstMat.rows == srcMat.rows && dstMat.cols == weights.rows && srcMat.type() == weights.type() && weights.type() == dstMat.type() && srcMat.type() == CV_32F && (biasMat.empty() || (biasMat.type() == srcMat.type() && biasMat.isContinuous() && (int)biasMat.total() == dstMat.cols)) in function 'cv::dnn::FullyConnectedLayerImpl::FullyConnected::run'

**Comment by ccordoba12** [comment]
Since that's the only advice we can give you, I'm going to close this issue.
