### ISSUE TITLE
Spyder won't launch from anaconda navigator or windows

### ISSUE THREAD

**Issue by DarthRevan109** [spyder-ide/spyder#16546]
## Problem Description
Have used Spyder in the past without issues. New computer, installed anaconda navigator and Spyder won't launch. Did everything I saw on previous posts of similar issue (e.g., spyder --reset, uninstalling spyder, uninstalling anaconda and re installing, etc...). Spyder still won't launch.

### What steps reproduce the problem?

1. Attempting to launch Spyder
2. 
3. 

### What is the expected output? What do you see instead?
Spyder should launch

## Versions

* Spyder version: 4.2.5
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: windows/10.0.19042

**Comment by dalthviz** [comment]
Hi @DarthRevan109 if you run Spyder from the Anaconda prompt do you see any traceback? Maybe it could be worthy to create a new env and check if from the new env Spyder launches or to use our [standalone installer](https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe). Let us know !
