### ISSUE TITLE
WTF, 

### ISSUE THREAD

**Issue by Leohanhart** [spyder-ide/spyder#16548]
### What steps reproduce the problem?

1. Reinstall, 2 times 
2. Smashing the computer
3. Filling this form

### What is the expected output? What do you see instead?
- Please fix these focking bugs, I have not time for this. 
- Please stop making big changes and making spyder instabel, I cant work with this shit. 
- Make sure new versions are not disturbing the old versions. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Leohanhart** [comment]
Fixed it,

**Comment by ccordoba12** [comment]
Your language is not acceptable in our community. Therefore, I banned you from participating in our organization for one week.

**Comment by ccordoba12** [comment]
Note: I edited the original message to remove the offensive language.
