### ISSUE TITLE
Spyder crashes on Launch

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1656]
_From [tomricha...@gmail.com](https://code.google.com/u/104754607890612086204/) on 2013-11-26T07:32:21Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Trying to run Spyder from its Start menu shortcut, or via the Python(x,y) launcher, or by running Spyder.bat/Spyder.exe. What is the expected output? What do you see instead? I'm expecting Spyder to launch, but instead all I see is a command prompt window for a fraction of a second. The command prompt window gives the following message: http://i.imgur.com/5mxWNso.jpg What version of the product are you using? On what operating system? I'm not sure what version I'm using - Spyder installed as part of Python(x,y), which is at version 2.7.5.1. My OS is Win7 64-bit. 

Please provide any additional information below

. I'm really, really new to Python and Spyder, so I can't give any useful technical information. Ultimately, I'm trying to use this: https://github.com/thearn/webcam-pulse-detector/blob/master/win_pythonxy.md . 

It's worth mentioning that I already tried to fix the problem myself using this thread: https://code.google.com/p/spyderlib/issues/detail?id=1325 I installed pywin32 and edited lockfile.py to match the code found here: https://code.google.com/p/spyderlib/source/browse/spyderlib/utils/external/lockfile.py#19 Any help you can provide would be greatly appreciated.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1656_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-11-26T05:02:59Z_

Was you screenshot taken after or before editing lockfile.py ? If it was after, could you reinstall a fresh spyder and try again ?

**Comment by spyder-issues-migrator** [comment]
_From [tomricha...@gmail.com](https://code.google.com/u/104754607890612086204/) on 2013-11-27T13:30:41Z_

How would I go about uninstalling my current Spyder before putting a fresh one on?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-12-02T03:58:44Z_

The files should be erased if you reinstall spyder without uninstalling the current version.

**Comment by goanpeca** [comment]
@ccordoba12, seems like something that can be closed...
