### ISSUE TITLE
Cannot activate conda env when created in a path

### ISSUE THREAD

**Issue by jrenardOceanSonics** [spyder-ide/spyder#16562]
### What steps will reproduce the problem?

1 Create a conda environment with the --prefix option, specifying a path rather than an environment name.

2 install spyder-kernel in the environment.

3 Inside the new environment, create an environment variable using: conda env config vars set MY_VAR='HELLO'

4 launch spyder from another conda environment (can be the base environment)

5 change the Python Interpreter to point to the python.exe file in the new environment.
The path is obtained from the command: python -c "import sys; print(sys.executable)"

6 Create a new console or restart the kernel. Spyder outputs the message '<path_to_env>/Scripts/activate' is not recognized as an internal or external command.

```
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:16) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython  -- An enhanced Interactive Python.

Restarting kernel...
 

'C:/<path_to_dir>/.conda/dev_env/Scripts/activate' is not recognized as an internal or external command,
operable program or batch file.
```
7 Check that the environment variable MY_VAR does not exist.

If the environment is created with a name and placed in the default miniconda3/envs directory, there is no issue and the new environment appears directly in the Spyder drop-down menu for the Python interpreter.

### Environment

* Spyder version: 5.1.5 None
* Python version: 3.8.12 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

Installation from miniconda3

**Comment by dalthviz** [comment]
Is the one in the environment either if you restart or create a new Console:

After restart:

![imagen](https://user-images.githubusercontent.com/16781833/137002180-97df8991-0bbb-4a35-85cf-16b2edd7a8b6.png)

With a new Console:

![imagen](https://user-images.githubusercontent.com/16781833/137002231-d023e147-dae8-47e5-b8b5-821793e3211d.png)

**Comment by DereckZhang** [comment]
@ccordoba12 
I met the same problem in `5.3.0`, conda environment created in a path is not properly activated, but conda env in default path(in my case is 'C:\ProgramData\Miniconda3\envs\envname\python.exe') can be properly activated.
Today I update to `5.3.1` and **change none of settings**, the same conda env in default path can't be properly activated! It shows :
```
An error ocurred while starting the kernel
The following argument was not expected: C:/ProgramData/Miniconda3/envs/envname
Run with ‑‑help for more information.
```

I think this problem will nag many people, hope it can be resolved in the near future.

**Comment by ba-tno** [comment]
I have the same issue on 5.3.2. When I start Spyder I'm always greeted with the "An error ocurred while starting the kernel" error in red and the following text:

> The following argument was not expected: C:/Users/username/Miniconda3/envs/env_name
Run with ‑‑help for more information.

What worries me now is that in the past (pre 5.3.2) I could click on "New console" and a new console would start right away (while still printing the text about "the following argument..."). However, now I sometimes need to start 3-4 new consoles before a console actually starts.

**Comment by LiGengLei** [comment]
@ba-tno I have the same issue on 5.3.2.

**Comment by dalthviz** [comment]
Just in case, I was able to reproduce the `The following argument was not expected:` message when using the standalone windows installer with a custom interpreter. Trying to launch multiple times consoles causes at some point the console to start but still printing the error message before the first console prompt:

![imagen](https://user-images.githubusercontent.com/16781833/182427072-2f3ad658-27e1-4d17-bc27-c0c3ceb7590a.png)

![imagen](https://user-images.githubusercontent.com/16781833/182427158-52530832-50b0-4cb1-8071-5ed9b5689a66.png)

Could this error by related with installations for all users (installation with Admin privileges) using either the standalone installer or Anaconda/Miniconda?

**Comment by ba-tno** [comment]
> Could this error by related with installations for all users (installation with Admin privileges) using either the standalone installer or Anaconda/Miniconda?

Just tested: I uninstalled standalone Spyder 5.3.2, which was installed "for all users" (with Admin privileges), and installed it again "just for me" (using the the standalone installer). Now the console starts without error when using a custom interpreter.

I fit matters: my Miniconda is also installed "just for me" in `C:\users\username\Miniconda3`.

**Comment by dalthviz** [comment]
Note: Seems like this issue could be relevant here - https://github.com/mamba-org/mamba/issues/1881 (for the per environment environment variables part of the OP, at least if you are using the standalone installer which uses the micromamba executable to activate envs)
