### ISSUE TITLE
Uncomment issue

### ISSUE THREAD

**Issue by 1tuition** [spyder-ide/spyder#16567]
### What steps will reproduce the problem?

When I comment and uncomment, some dots appear at the start of the line and I always  have to remove them to solve the indentations' error.

**Comment by ccordoba12** [comment]
@1tuition, thanks for reporting. Please upload an animated gif or a video of the behavior you're seeing to better understand your problem. Otherwise it won't be possible for us to help you.

You can create animated gifs using the [Licecap](https://www.cockos.com/licecap/) program.

**Comment by 1tuition** [comment]
Thank you for your quick reply, i had this problem for several days but now that i want to save it it works :)
If the problem occurs again I will post a gif.

**Comment by ccordoba12** [comment]
Ok, no problem. Let us know how it goes.
