### ISSUE TITLE
cannot import name '_typeconv' from 'numba.core.typeconv

### ISSUE THREAD

**Issue by ErnestoAvedillo** [spyder-ide/spyder#16564]
### What steps will reproduce the problem?

Hello

The error code written in the title is the one that I get when I try to work with numba only with spyder. (With python console or other editors is working fine)

import numba as nb
import numpy as np

@nb.njit
def calc (n):
    a= 0.5
    b= 3
    ui_data = np.arange(n)
    for i in np.arange(1,n):
        ui_data [i] = ui_data[i-1] * a + ui_data[i] * b 
    return ui_data

print (calc(100000))

The error that I get is:

runfile('X:/EA/Python/EjerciciosFourier/prueba numba.py', wdir='X:/EA/Python/EjerciciosFourier')
Reloaded modules: numba._version, numba.misc, numba.misc.init_utils, numba.core, numba.core.config, yaml, yaml.error, yaml.tokens, yaml.events, yaml.nodes, yaml.loader, yaml.reader, yaml.scanner, yaml.parser, yaml.composer, yaml.constructor, yaml.resolver, yaml.dumper, yaml.emitter, yaml.serializer, yaml.representer, llvmlite, llvmlite._version, llvmlite.binding, llvmlite.binding.dylib, llvmlite.binding.ffi, llvmlite.binding.common, llvmlite.utils, llvmlite.binding.executionengine, llvmlite.binding.targets, llvmlite.binding.object_file, llvmlite.binding.initfini, llvmlite.binding.linker, llvmlite.binding.module, llvmlite.binding.value, llvmlite.binding.context, llvmlite.binding.options, llvmlite.binding.passmanagers, llvmlite.binding.transforms, llvmlite.binding.analysis, llvmlite.ir, llvmlite.ir.types, llvmlite.ir._utils, llvmlite.ir.values, llvmlite.ir.module, llvmlite.ir.context, llvmlite.ir.builder, llvmlite.ir.instructions, llvmlite.ir.transforms, numba.testing, numba.testing.main, numba.testing.loader, numba.testing._runtests, numba.core.types, numba.core.utils, numba.core.types.abstract, numba.core.types.containers, numba.core.types.common, numba.core.types.misc, numba.core.typeconv, numba.core.typeconv.castgraph, numba.core.errors, numba.core.types.functions, numba.core.types.iterators, numba.core.types.npytypes, numba.core.types.scalars, numba.np, numba.np.npdatetime_helpers, numba.core.types.function_type
Traceback (most recent call last):

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv

ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typeconv\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "X:\EA\Python\EjerciciosFourier\prueba numba.py", line 8, in <module>
    import numba as nb

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules

  File "C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))

ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\Ernesto\AppData\Local\Programs\Python\Python39\Lib\site-packages\numba\core\typeconv\__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\Ernesto\AppData\Local\Programs\Spyder\Python\python.exe

Does any one can help?
Thanks

**Comment by ccordoba12** [comment]
Hey @ErnestoAvedillo, thanks for reporting. How did you install Spyder?

**Comment by ErnestoAvedillo** [comment]
Hello
Just downloaded and installed the  exe file Spyder_64bit_full.exe from https://www.spyder-ide.org/

**Comment by ccordoba12** [comment]
But our installer doesn't  come with Numba. So do you have a separate Python installation in which you installed that package?

**Comment by ccordoba12** [comment]
Ok, for that please follow the instructions posted in our docs:

https://docs.spyder-ide.org/5/faq.html#using-packages-installer

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
