### ISSUE TITLE
Editor  slowing down after a short time of editing

### ISSUE THREAD

**Issue by ttyhpy** [spyder-ide/spyder#16560]
### What steps will reproduce the problem?

recreate the error:
Take a longer source code that you no longer need and 
edit it completely arbitrarily (without it having to make sense)
with longer editing of the source code it happens that the editor needs a longer and longer reaction time to react to inputs.
It seems to depend on the "type" of input technique.
Frequent deleting of many single characters e.g. by backspace, inserting new characters, deleting lines and inserting them elsewhere accelerate this process of slowing down, so that after a short time you get an almost unusable editor.

a) with higher editing speed e.g. by randomly inserting characters, deleting and reinserting other characters
b) by deleting lines and inserting them elsewhere
c) undoing the changes via [ctrl]-Z, 
d) redoing or repeating these change operation by [ctl]-Y 
e) ... and so on and so forth, without using the usual possibilities of the IDE
for text navigation
the system is not usable after 2 minutes.

f) on my system it also happens that the computer has a higher cpu load for a short time, which is also noticeable acoustically, because the fans start up, as if i would train a deeper neural network ;-)

now of course you can change this by your input technique, but
some things have migrated into the spinal cord in such a way that they are anchored there.
So it is not as easy to change these methods as it is to change your software. 
I hope so ;-).

**Comment by ttyhpy** [comment]
hello ccordoba12,

thanks for your help.

i have now installed the spyder ide 5.1.5 via conda-forge.
the installation via the 'ready-to-use' installer was not very successful.

both methods failed to install the spyder kernel in the required version >=2.1; <2.2 in my existing xxx-dev environment without downgrading some packages in the versions below a certain version level, which I could not accept due to a version limitation of the packages I have to use

so i set up a completely new [... reduced] virtual development environment. 
also here it could not be avoided that some packages were obviously downgraded in the versions after the installation of the spyder-kernels [2.1.3].

the editor is now smoother to use. 
the increased cpu-load also occurs in this version, when the kite-engine is used for completion. then all cores are used to more than 50% [... also audible]. 

with very short classes and methods / functions it works reasonably well. 

but sometimes it is confusing when the autocomplete makes suggestions from other source texts that are no longer open. 
but at the same time the ide has difficulties to find the signature of a function directly above the place where you are editing [... even if you see it].
this is only annoying if the source text [... including the comments]... exceeds two hundred lines.

there are the preferences for completion.
normally i don't use the kite-engine.
 
![grafik](https://user-images.githubusercontent.com/92161198/136697633-9da77e3c-2995-4e50-a4d0-373f28338ddc.png)

  
**another strange behavior:**
**[CTRL+.]** resets the console, but now the interpreter doesn't connect anymore. this also happens from the 
- main-menu -> Consoles -> restart console 
- console menu -> [burger] -> restart console

Closing the console via [tab-close[x]] or the [main/console] menu or opening a new console does not show this behavior.
below find the text inside the console after restarting the kernel

Python 3.8.12 | packaged by conda-forge | (default, Sep 29 2021, 19:14:40) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython -- An enhanced Interactive Python.
Restarting kernel...

Task was destroyed but it is pending!
task: <Task pending name='Task-1' coro=<Kernel.poll_control_queue() running at 
C:\Users\xxxxx\anaconda3\envs\py38local-dev\lib\site-packages\ipykernel\kernelbase.py:227> 
wait_for=<future finished result=<future at 0x...state=pending>> 
cb=[_chain_future.<locals>._call_set_state() at C:\Users\xxxxx\anaconda3\envs\py38local-dev\lib\asyncio\futures.py:367]>

**Comment by ccordoba12** [comment]
> the increased cpu-load also occurs in this version, when the kite-engine is used for completion

Unfortunately, Kite is no longer maintained (i.e. the company behind it stopped developing it) and eventually our support for it will be removed. So if you want to avoid that experience, please uninstall it or disable it in Spyder.

> but sometimes it is confusing when the autocomplete makes suggestions from other source texts that are no longer open.
but at the same time the ide has difficulties to find the signature of a function directly above the place where you are editing [... even if you see it].
this is only annoying if the source text [... including the comments]... exceeds two hundred lines.

You need to provide us a simple and reproducible code example that generates the errors you're talking about. Otherwise, it won't be possible for us to fix them.

> another strange behavior:
[CTRL+.] resets the console, but now the interpreter doesn't connect anymore. this also happens from the

That's a totally different error. Please don't mix unrelated errors in the same issue and instead open a new one about it. In here let's keep talking about the editor issues.

**Comment by ttyhpy** [comment]
after:

- env: local-dev-> uninstall, install spyder-kernels from conda-forge -> spyder-kernels 2.1.3
- env: spyder-dev -> spyder-kernels 2.1.3

the editor does not seem to slow down anymore. 
Completion works as expected, with or without Kite enabled.

Since I don't use Kite in my daily work, I removed it completely, as I prefer and as you recommended, because of the uncertainties about future support
