### ISSUE TITLE
Can't display sympy objects

### ISSUE THREAD

**Issue by ilkerhk** [spyder-ide/spyder#16576]
## Problem Description
Wrong print/display of sympy objects 

### What steps reproduce the problem?
1. Execute the followig 3 lines
from sympy import *
A = Symbol('A', real=True, positive=True)
5*A

2. Observe the corrupted rendering of the display 
 (See below image )

## Versions
* Spyder version:  5.0.5
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version:  Kubuntu
![Screenshot_20211012_130851](https://user-images.githubusercontent.com/13827163/136937975-1b50d3a6-af64-4f01-a43b-4fe1ce497176.png)

**Comment by ccordoba12** [comment]
This is fixed in our latest version (5.4.2).
