### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by SyedSRD** [spyder-ide/spyder#16570]
### What steps will reproduce the problem?

1) 'conda create -n myenv spyder-kernels' in miniconda cmd
2)change default env in prefrences
3)restart console

### Traceback
```python-traceback
ERROR:traitlets:Failed to run command:
['C:\\Users\\syed\\AppData\\Local\\Programs\\Spyder\\pkgs\\spyder\\plugins\\ipythonconsole\\scripts\\conda-activate.bat', 'C:/Users/syed/miniconda3/Scripts/activate', 'C:/Users/syed/miniconda3/envs/myenv', 'C:\\Users\\syed\\miniconda3\\envs\\myenv\\python.exe', 'C:\\Users\\syed\\AppData\\Roaming\\jupyter\\runtime\\kernel-233c4e184b74.json']
    PATH='C:\\Users\\syed\\AppData\\Local\\Programs\\Spyder\\pkgs\\PyQt5\\Qt\\bin;C:\\Users\\syed\\AppData\\Local\\Programs\\Spyder\\pkgs\\pywin32_system32;C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Users\\syed\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Python 3.9;C:\\Program Files\\Git\\cmd;C:\\Users\\syed\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\Scripts;C:\\Users\\syed\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\syed\\AppData\\Local\\atom\\bin;C:\\Users\\syed\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Python 3.9;C:\\Users\\syed\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python37\\Scripts;C:\\Users\\syed\\AppData\\Local\\Programs\\Spyder\\pkgs\\numpy\\.libs;C:\\Users\\syed\\AppData\\Local\\Programs\\Spyder\\pkgs\\scipy\\.libs'
    with kwargs:
{'stdin': -1, 'stdout': <_io.TextIOWrapper name='nul' mode='w' encoding='cp1252'>, 'stderr': <codecs.StreamReaderWriter object at 0x000001DFF8418788>, 'cwd': None, 'creationflags': 134217728, 'close_fds': False}

```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by SyedSRD** [comment]
I reinstalled the app and created a new env (spyder-env2) from miniconda prompt  just like before and tried to connect it but it didn't work. whenever I click on restart kernel it wont restart unless I changed it to default env settings.
![image](https://user-images.githubusercontent.com/26276397/136896438-d90fce1c-e79e-4bd0-8923-661f3da0e94c.png)

PS: My old myenv got deleted.

**Comment by ccordoba12** [comment]
What's the version spyder-kernels version you have in `myenv`? Besides, are you using conda-forge?

**Comment by SyedSRD** [comment]
spyder-kernels -2.1.3(it aint allowing me to install 2.0 or 2.2 on my miniconda)
and yes I was only using conda-forge for installing PyQtWebEngine.

**Comment by ccordoba12** [comment]
> and yes I was only using conda-forge for installing PyQtWebEngine.

I don't understand what you mean by this.

Could you post the output of `conda list` here to check how you installed packages in your environment? Thanks!

**Comment by SyedSRD** [comment]
# Name                    Version                   Build  Channel
backcall                  0.2.0              pyhd3eb1b0_0
ca-certificates           2021.9.30            haa95532_1
certifi                   2021.10.8        py39haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
colorama                  0.4.4              pyhd3eb1b0_0
debugpy                   1.4.1            py39hd77b12b_0
decorator                 5.1.0              pyhd3eb1b0_0
ipykernel                 6.4.1            py39haa95532_1
ipython                   7.27.0           py39hd4e2768_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
jedi                      0.18.0           py39haa95532_1
jupyter_client            6.1.12             pyhd3eb1b0_0
jupyter_core              4.8.1            py39haa95532_0
matplotlib-inline         0.1.2              pyhd3eb1b0_2
openssl                   1.1.1l               h2bbff1b_0
parso                     0.8.2              pyhd3eb1b0_0
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       21.2.4           py39haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
pygments                  2.10.0             pyhd3eb1b0_0
python                    3.9.7                h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
pywin32                   228              py39hbaba5e8_1
pyzmq                     22.2.1           py39hd77b12b_1
setuptools                58.0.4           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_0
spyder-kernels            2.1.3            py39haa95532_0
sqlite                    3.36.0               h2bbff1b_0
tornado                   6.1              py39h2bbff1b_0
traitlets                 5.1.0              pyhd3eb1b0_0
tzdata                    2021a                h5d7bf9c_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5              pyhd3eb1b0_0
wheel                     0.37.0             pyhd3eb1b0_1
wincertstore              0.2              py39haa95532_2

**Comment by ccordoba12** [comment]
Closing due to lack of response.
