### ISSUE TITLE
Spyder 5.0.5 keeps changing working directory

### ISSUE THREAD

**Issue by ffviana** [spyder-ide/spyder#16600]
### What steps will reproduce the problem?

I'm running a script several times to process a dataset. The script is part of a project and therfore the working directory should be the project directory. This is the case most of the time. However, sometimes the Working directory changes without any command from my part. The solution I've found so far is to restart spyder or force a os.chdir to the desired path. Reseting the kernel does not solve the issue.

The Working directory has already changed to a subfolder of my project (where the script i'm running is saved) but also to my root directory (ie. c:/users/Admin). I'm working with an environmet which is locateded in one of the subfolders of the latter directory. 

My python version is 3.8.11 and spyder is 5.0.5. I'm working with Windows 10 Pro (Version 21H1)

Find the Environment info below and the code in question afterwords:

#####################################################################

name: PDM_TMS
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anyio=2.2.0=py38haa95532_2
  - appdirs=1.4.4=py_0
  - argh=0.26.2=py38_0
  - argon2-cffi=20.1.0=py38h2bbff1b_1
  - arrow=0.13.1=py38_0
  - astroid=2.6.6=py38haa95532_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.5.4=py_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py38he774522_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.0.0=pyhd3eb1b0_0
  - blosc=1.21.0=h19a0ad4_0
  - bottleneck=1.3.2=py38h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.6=py38h2bbff1b_0
  - cfitsio=3.470=he774522_6
  - chardet=4.0.0=py38haa95532_1003
  - charls=2.2.0=h6c2663c_0
  - click=8.0.1=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=3.4.7=py38h71e12ea_0
  - cycler=0.10.0=py38_0
  - cytoolz=0.11.0=py38he774522_0
  - dask-core=2021.7.2=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=py_0
  - docutils=0.17.1=py38haa95532_1
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.1.0=py38haa95532_0
  - flake8=3.8.4=py_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=2021.7.0=pyhd3eb1b0_0
  - future=0.18.2=py38_1
  - giflib=5.2.1=h62dcd97_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=2.10=pyhd3eb1b0_0
  - imagecodecs=2021.6.8=py38h5da4933_0
  - imageio=2.9.0=pyhd3eb1b0_0
  - imagesize=1.2.0=pyhd3eb1b0_0
  - importlib-metadata=3.10.0=py38haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - inflection=0.5.1=py38haa95532_0
  - intel-openmp=2021.3.0=haa95532_3372
  - intervaltree=3.1.0=py_0
  - ipykernel=5.3.4=py38h5ca1d4c_0
  - ipython=7.18.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.2=pyhd3eb1b0_0
  - jdcal=1.4.1=py_0
  - jedi=0.17.2=py38haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py38haa95532_0
  - jupyter_server=1.4.1=py38haa95532_0
  - jupyterlab=3.1.7=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.7.2=pyhd3eb1b0_0
  - keyring=23.0.1=py38haa95532_0
  - kiwisolver=1.3.1=py38hd77b12b_0
  - lazy-object-proxy=1.6.0=py38h2bbff1b_0
  - lcms2=2.12=h83e58a3_0
  - lerc=2.2.1=hd77b12b_0
  - libaec=1.0.4=h33f27b4_1
  - libdeflate=1.7=h2bbff1b_5
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libtiff=4.2.0=hd0e1b90_0
  - libzopfli=1.0.3=ha925a31_0
  - littleutils=0.2.2=py_0
  - locket=0.2.1=py38haa95532_1
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38he774522_0
  - matplotlib=3.4.2=py38haa95532_0
  - matplotlib-base=3.4.2=py38h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py38_1
  - mistune=0.8.4=py38he774522_1000
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py38h2bbff1b_0
  - mkl_fft=1.3.0=py38h277e83a_2
  - mkl_random=1.2.2=py38hf11a4ad_0
  - mpmath=1.2.1=py38haa95532_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py38_0
  - natsort=7.1.1=pyhd3eb1b0_0
  - nbclassic=0.2.6=pyhd3eb1b0_0
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py38haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - networkx=2.6.2=pyhd3eb1b0_0
  - notebook=6.4.3=py38haa95532_0
  - numexpr=2.7.3=py38hb80d3ca_1
  - numpy=1.20.3=py38ha4e8547_0
  - numpy-base=1.20.3=py38hc2deb75_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py_0
  - openjpeg=2.3.0=h5ec785f_1
  - openpyxl=3.0.7=pyhd3eb1b0_0
  - openssl=1.1.1l=h2bbff1b_0
  - outdated=0.2.0=py_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.1=py38h6214cd6_0
  - pandas-flavor=0.2.0=py_0
  - pandoc=2.12=haa95532_0
  - pandocfilters=1.4.3=py38haa95532_1
  - paramiko=2.7.2=py_0
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pathspec=0.7.0=py_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py38_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py38h4fa10fc_0
  - pingouin=0.3.11=pyhd8ed1ab_0
  - pip=21.2.2=py38haa95532_0
  - pluggy=0.13.1=py38haa95532_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - psutil=5.8.0=py38h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycodestyle=2.6.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.2.0=pyhd3eb1b0_0
  - pygments=2.9.0=pyhd3eb1b0_0
  - pylint=2.9.6=py38haa95532_1
  - pyls-black=0.4.6=hd3eb1b0_0
  - pyls-spyder=0.3.2=pyhd3eb1b0_0
  - pynacl=1.4.0=py38h62dcd97_1
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyrsistent=0.17.3=py38he774522_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.11=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - python_abi=3.8=1_cp38
  - pytz=2021.1=pyhd3eb1b0_0
  - pywavelets=1.1.1=py38he774522_2
  - pywin32=228=py38hbaba5e8_1
  - pywin32-ctypes=0.2.0=py38_1000
  - pywinpty=0.5.7=py38_0
  - pyyaml=5.4.1=py38h2bbff1b_1
  - pyzmq=20.0.0=py38hd77b12b_1
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.2=pyhd3eb1b0_0
  - qtconsole=5.1.0=pyhd3eb1b0_0
  - qtpy=1.9.0=py_0
  - regex=2021.4.4=py38h2bbff1b_0
  - requests=2.25.1=pyhd3eb1b0_0
  - rope=0.19.0=pyhd3eb1b0_0
  - rtree=0.9.7=py38h2eaa2aa_1
  - scikit-image=0.18.1=py38hf11a4ad_0
  - scikit-learn=0.24.2=py38hf11a4ad_1
  - scipy=1.6.2=py38h66253e8_1
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py38haa95532_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.16.0=pyhd3eb1b0_0
  - snappy=1.1.8=h33f27b4_0
  - sniffio=1.2.0=py38haa95532_1
  - snowballstemmer=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=4.0.2=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.0.5=py38haa95532_2
  - spyder-kernels=2.0.5=py38haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - statsmodels=0.12.2=py38h2bbff1b_0
  - tabulate=0.8.9=py38haa95532_0
  - terminado=0.9.4=py38haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=py_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyhb85f177_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tifffile=2021.7.2=pyhd3eb1b0_2
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.10=he774522_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py38h2bbff1b_0
  - tqdm=4.62.0=pyhd3eb1b0_1
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typed-ast=1.4.3=py38h2bbff1b_1
  - typing-extensions=3.10.0.0=hd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - ujson=4.0.2=py38hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=1.0.2=py38haa95532_1
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - wrapt=1.12.1=py38he774522_1
  - xarray=0.19.0=pyhd3eb1b0_1
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlsxwriter=1.4.4=pyhd3eb1b0_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.3=ha925a31_3
  - zfp=0.5.5=hd77b12b_6
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
prefix: C:\Users\Admin\anaconda3\envs\PDM_TMS

#####################################################################

This issue has already led to the accidental deletion of processed data. Please find the code bellow:

```
#%% Import Packeges and Functions

import os
import pickle
import numpy as np
import matplotlib.pyplot as plt
from PDM_TMS_functions import load_mat, load_data, timearray, time2samp, \
                       samp2time, SynchSignals, find_pulse
                       
# to plot in seperate window (will through Warning on first run)                 
%matplotlib qt  
 
# % Define Paths


# wd = os.getcwd()   # Spyder keeps changing wd randomly
os.chdir('C:/Users/Admin/Desktop/FV/Tese/Code')
wd = os.getcwd()

data_path = wd + '/Board Validation/RawData/'
output_path = wd + '/Board Validation/PreprocessedData/'

if not os.path.isdir(output_path):
    os.makedirs(output_path)  
    
# % Get File Paths for subject

FS = 5000   # Sampling rate

# Subject ID
ID = 'PDMTMS_BV07'  

meps_path = (data_path + '{}_meps.bin'.format(ID), 
             data_path + '{}_meps.mat'.format(ID))

mvic_path = (data_path + '{}_mvics.bin'.format(ID), 
             data_path + '{}_mvics.mat'.format(ID))

    
# % Perform MVIC synchtronization

# Load InHouse MVICs
mvic_ih = load_data(mvic_path[0], channels = np.array((2,0,1)), fs = FS,
                                   voltage_gain = 200,reshape = 3)
# Load Biopac MVICs
mvic_bc = load_mat(mvic_path[1])

# Synchronize Signals without dc offset correction
_, mvic_synched = SynchSignals(mvic_ih,mvic_bc,det = False) 

# Plot Synched MVICs

# Creating figure to Plot complete MVICs timeseries
fig,ax = plt.subplots(2,1,sharex=True, figsize=[22,9])

# Ploting Signals before Synch
ax[0].plot(timearray(mvic_ih[1,:], FS, unit='min'),
           mvic_ih[1,:], label = 'InHouse')
ax[0].plot(timearray(mvic_bc, FS, unit='min'),
           mvic_bc, label = 'Biopac')
ax[0].set_title('Before Alignment')
ax[0].set_ylabel('Voltage (\u03BCV)')
fig.legend(loc = 'upper right')

# Ploting Signals after Synch
ax[1].plot(timearray(mvic_synched[1,:], FS, unit='min'),
           mvic_synched[1,:], label = 'InHouse')
ax[1].plot(timearray(mvic_synched[2,:], FS, unit='min'),
           mvic_synched[2,:], label = 'Biopac')
ax[1].set_title('After Alignment')
ax[1].set_ylabel('Voltage (\u03BCV)')
ax[1].set_xlabel('time (min)')

# %% Get MVIC DC OFFSET and Segmente & Synch MVICs

# complete_mvic_snip = (start_MVIC_timeseries,end_MVIC_timeseries) -> time(min)
# timeseries without edge artifact

complete_mvic_snip = (0.198,4.418) 
mvic_snip = ((0.328,0.445),  
             (1.332,1.429),
             (2.296,2.397),
             (3.269,3.365),
             (4.297,4.398))

# Calculate DC offset for both signals 
dc_mvic = np.mean(
           mvic_synched[:, time2samp(complete_mvic_snip[0], FS, unit='min'):
                           time2samp(complete_mvic_snip[1], FS, unit='min')],
                    axis = 1)
    
mvic_offset = dc_mvic[2] - dc_mvic[1]   # DC offset difference

text = 'Offset between systems: {:.2f}'.format(mvic_offset)
print(len(text)*'#' + '\n' + text + '\n' + len(text)*'#')


# % Segment MVICs

mvic_epochs = {}    # Variable to store MVIC epochs

# mvic_snip = ((start_mvic1,end_mvic1),
#                       ,...,
#              (start_mvic2,end_mvic2)) ->time(min)


# Plot and Save Synched and detrended MVIC epochs
fig,ax = plt.subplots(5, figsize=[8,9]) # Creating figure to Plot MVIC epochs

for p in range(len(mvic_snip)):
    snip = mvic_snip[p] # Snip info for epoch 'p'
    # Snip and Synch MVIC epoch 'p'
    tmp = mvic_synched[:,time2samp(snip[0], FS, unit='min'):
                         time2samp(snip[1], FS, unit='min')]
    _, tmp_synched = SynchSignals(tmp,tmp[2,:])
    # Save MVIC epoch 'p' in Dict ('p+1' because python is zero-indexed)
    mvic_epochs['mvic_{}'.format(p+1)] = tmp_synched 
    # Plot synche MVIC epoch 'p'
    ax[p].plot(timearray(tmp_synched[1,:], FS, 's'), 
               tmp_synched[1,:], label = 'InHouse')
    ax[p].plot(timearray(tmp_synched[2,:], FS, 's'),
               tmp_synched[2,:], label = 'Biopac')
    ax[p].set_ylabel('Voltage (\u03BCV)')
    ax[p].set_xlabel('time (s)')
    if p == 0:
        fig.legend(loc = 'upper center')
    

# %% load MEP signals
plt.close('all')    # Close all plots

# Load InHouse MEPs
meps_ih = load_data(meps_path[0], channels = np.array((2,0,1)), fs = FS,
                                    voltage_gain = 200,reshape = 3)
# Load Biopac MEPs
meps_bc = load_mat(meps_path[1])

# Plot Unsynched signals seperately
fig,ax = plt.subplots(2,1, figsize=[22,9]) # Creating figure to Plot complete MEP timeseries

# Plot InHouse signal
ax[0].plot(timearray(meps_ih[1,:], FS, unit='min'),
           meps_ih[1,:], label = 'InHouse')
ax[0].set_title('InHouse')
ax[0].set_ylabel('Voltage (\u03BCV)')
# Plot Biopac Signal
ax[1].plot(timearray(meps_bc, FS, unit='min'),
           meps_bc, label = 'Biopac', color = 'orange')
ax[1].set_title('Biopac')
ax[1].set_ylabel('Voltage (\u03BCV)')
ax[1].set_xlabel('time (min)')


# %% Define MEP reference for first Synch attempt

# ih_snip = InHouse_MEPref_onset -> time(min)
# bc_snip = Biopac_MEPref_onset -> time(min)

ih_snip = 2.5642
bc_snip = 2.6538

delta_snip = 0.001 # timeseries length -> time(min)
# Reference MEP location in both systems
mep_ref_snip = ((ih_snip,ih_snip + delta_snip),  
                (bc_snip,bc_snip + delta_snip))

delta_snip = mep_ref_snip[1][0] - mep_ref_snip[0][0] # Used to align signals

# Inhouse reference MEP snip 
mep_ih_ref = meps_ih[:,time2samp(mep_ref_snip[0][0], FS, unit='min'):
                     time2samp(mep_ref_snip[0][1], FS, unit='min')]
# Biopac reference MEP snip 
mep_bc_ref = meps_bc[time2samp(mep_ref_snip[1][0], FS, unit='min'):
                     time2samp(mep_ref_snip[1][1], FS, unit='min')]

# First Synch attempt
pad, mep_ref_synched = SynchSignals(mep_ih_ref,mep_bc_ref)

# Align signals using first synch info
if delta_snip < 0:  # if Inhouse MEP after Biopac MEP pad biopac timeseries
    meps_bc = np.pad(meps_bc,(abs(time2samp(delta_snip,FS)),0),'edge')
else: # if Inhouse MEP before Biopac MEP pad Inhouse timeseries
    meps_ih = np.pad(meps_ih,((0,0),(time2samp(delta_snip,FS),0)),'edge')
    
if pad < 0: # Similar reasoning to above ifelse but for SynchSignal output
    meps_ih = np.pad(meps_ih,((0,0),(abs(pad),0)),'edge')
else:
    meps_bc = np.pad(meps_bc,(pad,0),'edge')

# Plot Synched signals

fig = plt.figure(figsize=[22,12]) # Creating figure to Plot reference MEP

ax1 = plt.subplot(2,2,1)
ax2 = plt.subplot(2,2,2)
ax3 = plt.subplot(2,1,2)

# Plot reference MEP before Synch
ax1.plot(timearray(mep_ih_ref[1,:], FS, 'ms'),
           mep_ih_ref[1,:], label = 'InHouse', alpha=0.8)
ax1.plot(timearray(mep_bc_ref, FS, 'ms'),
           mep_bc_ref, label = 'Biopac', alpha=0.8)
ax1.set_title('Before Alignment')
ax1.set_ylabel('Voltage (\u03BCV)')
ax1.set_xlabel('time (ms)')
fig.legend(loc = 'upper center')

# Plot reference MEP after Synch
ax2.plot(timearray(mep_ref_synched[1,:], FS, 'ms'),
           mep_ref_synched[1,:], label = 'InHouse', alpha=0.8)
ax2.plot(timearray(mep_ref_synched[2,:], FS, 'ms'),
           mep_ref_synched[2,:], label = 'Biopac', alpha=0.8)
ax2.set_title('After Alignment')
ax2.set_xlabel('time (ms)')
    
ax3.plot(timearray(meps_ih[1,:], FS, 'min'),
         meps_ih[1,:], label = 'InHouse', alpha=0.8)
ax3.plot(timearray(meps_bc, FS, 'min'),
         meps_bc, label = 'Biopac', alpha=0.8)
ax3.set_title('Sycnhronized signals')
ax3.set_ylabel('Voltage (\u03BCV)')
ax3.set_xlabel('time (min)')

# %% Synch MEPs

meps_synch = meps_ih.copy()
# Insure both timeseries have the same size by padding the end of timeseries
if len(meps_synch[0,:] ) >= len(meps_bc):
    meps_bc = np.pad(meps_bc,(0,len(meps_synch[0,:])-len(meps_bc)),'edge')
else:
    meps_synch  = np.pad(meps_synch ,((0,0),
                            (0,len(meps_bc)-len(meps_synch[0,:]))),'edge')

meps_synch[2,:] = np.expand_dims(meps_bc,0) # sabe both signals in same array

bef_pulse = 100 # How much time before pulse for 2nd synch attempt? -> time(ms)
aft_pulse = 100 # How much time after pulse for 2nd synch attempt? -> time(ms)

mep_epoch_snip = (15,45) # Final MEP epoch location -> time(ms)

pulses = find_pulse(meps_synch[0,:]) # Pulse index per MEP
meps_epochs = {} # Varible to save MEP epochs

# Rows and Columns for figure with all MEPs ploted seperately
n_rows = 6
n_cols = 7
# Creating figure to Plot MEPs including Pulse artifact
fig1,ax1 = plt.subplots(n_rows,n_cols,sharex=True, figsize=[26,14])
# Creating figure to Plot MEPs before final Synch to check for invalid MEPs
fig2,ax2 = plt.subplots(n_rows,n_cols,sharex=True, figsize=[26,14])
i = 0
j = 0
unsynched_meps = [] # Varible to identify poorly synched MEPs (some found aut.)
for c in range(len(pulses)):
    p = pulses[c] # Pulse index for MEP 'c'
    # MEP 'c' snip with pulse artifact
    mep = meps_synch[:,int((p-time2samp(bef_pulse, FS, 'ms'))):
                       int((p+time2samp(aft_pulse, FS, 'ms')))]
    _,mep_synch = SynchSignals(mep, mep[2,:]) # 2nd Synch attempt
    
    # Automaticaly identify poorly synched MEPS
    if mep_synch.shape[1] >= 2*time2samp(bef_pulse + aft_pulse, FS, 'ms')-1:
        unsynched_meps += [c]
    p_ = find_pulse(mep_synch[0,:])[0] # Pulse index in synhced MEP
    
    # Insure Synched MEPs have the same size (centered in 'p_')
    if p_ < time2samp(bef_pulse,FS,'ms'):
        pad = int(p_ - time2samp(bef_pulse,FS,'ms'))
        mep_synch = np.pad(mep_synch,((0,0),(abs(pad)+1,abs(pad)+1)),'edge')
        p_ += abs(pad)+1
    mep_synch = mep_synch[:,int((p_-time2samp(bef_pulse,FS,'ms'))):
                            int((p_+time2samp(aft_pulse,FS,'ms')))]
        
    # Plot MEP epochs before final Synch
    ax2[i,j].plot(timearray(mep_synch[1,:], FS, 'ms')-bef_pulse,
                  mep_synch[1,:], label = 'InHouse')
    ax2[i,j].plot(timearray(mep_synch[2,:],FS,'ms')-bef_pulse,
                  mep_synch[2,:], label = 'Biopac')
    ax2[i,j].text(-bef_pulse, np.min(mep[1,:]), str(c+1))
    
    # Snip synched MEP to check for invalid MEPs (amp. < 50 microV)
    mep_ = mep_synch[:,
                int((time2samp(bef_pulse + mep_epoch_snip[0], FS, 'ms'))):
                int((time2samp(bef_pulse + mep_epoch_snip[1], FS, 'ms')))]
    
    # Plot MEP 'c' including Pulse artifact
    ax1[i,j].plot(timearray(mep_[1,:], FS,'ms') + mep_epoch_snip[0],
                 mep_[1,:], label = 'InHouse')
    ax1[i,j].plot(timearray(mep_[2,:], FS, 'ms') + mep_epoch_snip[0],
                 mep_[2,:], label = 'Biopac')
    ax1[i,j].text(mep_epoch_snip[0], np.min(mep_[1,:]),str(c+1))
    
    if j == 0:
        ax1[i,j].set_ylabel('Voltage (\u03BCV)')
        ax2[i,j].set_ylabel('Voltage (\u03BCV)')
        if i == 0:
            fig1.legend(loc = 'upper center')
            fig2.legend(loc = 'upper center') 
    if i == n_rows-1 or (i == n_rows-2 and (j == n_cols-1 or j == n_cols-2)):
        ax1[i,j].set_xlabel('time (ms)')
        ax2[i,j].set_xlabel('time (ms)')
                         
    if i < n_rows and j < n_cols -1:
        j+=1
    elif j == n_cols -1 and i < n_rows -1:
        j  = 0
        i += 1
    meps_epochs['mep_{}'.format(c+1)] = mep_synch

if unsynched_meps != []:
    text = 'Alignment Failed for some MEPs!'
    print(len(text)*'~'+'\n'+text+'\n'+len(text)*'~')

# %% Final Synch and reject meps
# invalid_meps = Varible to identify invalid MEPs

invalid_meps = [6,7,27,32,38]

invalid_mep_keys = [] # Varible to store invalid MEP keys

# Creating figure to Plot Synched MEP epochs
fig,ax = plt.subplots(n_rows,n_cols,sharex=True, figsize=[26,14])
i = 0
j = 0
c = 1
for key in meps_epochs.keys():
    if int(key.split('_')[-1]) in invalid_meps: 
        # skip plot and Synch of invalid MEPs
        if i < n_rows and j < n_cols -1:
            j+=1
        elif j == n_cols -1 and i < n_rows -1:
            j  = 0
            i += 1
        c += 1
        invalid_mep_keys += [key]
        continue
    
    meps = meps_epochs[key]
    mep_ = meps[:,int((time2samp(bef_pulse + mep_epoch_snip[0], FS, 'ms'))):
                  int((time2samp(bef_pulse + mep_epoch_snip[1], FS, 'ms')))]
    _,mep_ = SynchSignals(mep_, mep_[2,:]) # Final MEP synch
    
    # Plot Synched MEP epoch    
    ax[i,j].plot(timearray(mep_[1,:], FS, 'ms') + mep_epoch_snip[0],
                 mep_[1,:], label = 'InHouse')
    ax[i,j].plot(timearray(mep_[2,:], FS, 'ms') + mep_epoch_snip[0],
                 mep_[2,:], label = 'Biopac')
    ax[i,j].text(mep_epoch_snip[0], np.min(mep_[1,:]), str(c))
    
    
    if j == 0:
        ax[i,j].set_ylabel('Voltage (\u03BCV)')
        if i == 0:
            fig.legend(loc = 'upper center')
    if i == n_rows-1 or (i == n_rows -2 and (j == n_cols -1 or j == n_cols -2)):
        ax[i,j].set_xlabel('time (ms)')
    if i < n_rows and j < n_cols -1:
        j+=1
    elif j == n_cols -1 and i < n_rows -1:
        j  = 0
        i += 1
    c += 1
    meps_epochs[key] = mep_ # Save correctly Synched MEPs


# %% Save Preprocessed Data
plt.close('all')
preprocessed_dic = {
    'Info' : {
        'Subject ID' : ID,
        'Sampling Rate' : FS,
        },
    'MVIC epochs' : {
        # saving some information in case preprocessing should be repeated
        'MVIC timeseries window' : complete_mvic_snip, 
        'MVIC windows': mvic_snip, 
        # Usefull Data
        'MVIC DC offset' : mvic_offset,
        'MVIC epochs' : mvic_epochs
        }, 
    'MEP epochs' : {
        # saving some information in case preprocessing should be repeated
        'Reference MEP' : mep_ref_snip,
        'MEP window' : mep_epoch_snip,
        'Unsyched MEPs' : unsynched_meps,
        # Usefull Data
        'Invalid MEPs' : invalid_mep_keys,
        'MEP epochs' : meps_epochs
        }
    }

preprocessed_fname = ID + '_preprocessed.pkl'

outfile = open(output_path + preprocessed_fname, 'wb') # 'wb' for binary file
pickle.dump(preprocessed_dic,outfile,-1) # -1 specifies highest binary protocol
outfile.close()
    
%reset -f

```

**Comment by steff456** [comment]
Great! I'm closing this issue then :)
