### ISSUE TITLE
conda install Spyder 5 conflicts with pytorch

### ISSUE THREAD

**Issue by AlexNguyen124** [spyder-ide/spyder#16604]
### What steps will reproduce the problem?

Installed Anaconda3:
sh Anaconda3-2021.05-Linux-x86_64.sh 
source .bashrc
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia
conda install spyder=5

this is the end the message:

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - argon2-cffi -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - astropy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - bitarray -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - blosc -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - bottleneck -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - brotlipy -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - bzip2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - c-ares -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - cairo -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - cffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - conda-package-handling -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - cryptography -> libgcc-ng -> __glibc[version='>=2.17']
  - cudatoolkit=11.1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - curl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - cython -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - cytoolz -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - dbus -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - expat -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - fastcache -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - ffmpeg -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - fontconfig -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - freetype -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - fribidi -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - gevent -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - glib -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gmp -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - gmpy2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - gnutls -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - graphite2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - greenlet -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gst-plugins-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - gstreamer -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - h5py -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - harfbuzz -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - hdf5 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - icu -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - jbig -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - jpeg -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - kiwisolver -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - krb5 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - lame -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - lazy-object-proxy -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - lcms2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libarchive -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libcurl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libedit -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libev -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libffi -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libgcc-ng -> __glibc[version='>=2.17']
  - libgfortran-ng -> __glibc[version='>=2.17']
  - libiconv -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - libidn2 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - liblief -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libllvm10 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libpng -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libsodium -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libspatialindex -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libssh2 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libstdcxx-ng -> __glibc[version='>=2.17']
  - libtasn1 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libtiff -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libtool -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libunistring -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libuuid -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - libuv -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libwebp-base -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libxcb -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - libxml2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - libxslt -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - llvmlite -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - lxml -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - lz4-c -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - lzo -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - markupsafe -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - matplotlib -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - matplotlib-base -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - mistune -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - mkl-service -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - mkl_fft -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - mkl_random -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - mpc -> libgcc-ng[version='>=7.2.0'] -> __glibc[version='>=2.17']
  - mpfr -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - msgpack-python -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - ncurses -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - nettle -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - ninja -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - numba -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - numexpr -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - numpy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - numpy-base -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - openh264 -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - openssl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pandas -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pango -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - patchelf -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pcre -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pillow -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pixman -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - psutil -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - py-lief -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pycosat -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pycurl -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pyerfa -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pyodbc -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pyqt -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pyrsistent -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pytables -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pytorch -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - pywavelets -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pyyaml -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - pyzmq -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - qt -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - readline -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - regex -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - ruamel_yaml -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - scikit-image -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - scikit-learn -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - scipy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - sip -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - sqlalchemy -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - sqlite -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - statsmodels -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - tbb -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - tifffile -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - tk -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - torchvision -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - tornado -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - typed-ast -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - ujson -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - unixodbc -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - wrapt -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - xz -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - yaml -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zeromq -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zlib -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']
  - zope.interface -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - zstd -> libgcc-ng[version='>=7.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31

## Versions

* Spyder version: 4.2.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.11.0-37-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.22.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.3.0 (OK)
nbconvert >=4.0                 :  6.0.7 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.8.1 (OK)
pylint >=1.0                    :  2.7.4 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.0.3 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                  :  4.0.1 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  0.29.23 (OK)
matplotlib >=2.0.0              :  3.3.4 (OK)
numpy >=1.7                     :  1.20.1 (OK)
pandas >=1.1.1                  :  1.2.4 (OK)
scipy >=0.17.0                  :  1.6.2 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @AlexNguyen124, thanks for reporting. To update Spyder in your base environment, I recommend you to run the following commands

    conda update anaconda
    conda install spyder=5.0.5

After that, please create a new environment to install Pytorch, like this

    conda create -n pytorch-env python=3.8
    conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c nvidia

That will probably avoid the conflicts you're seeing right now (I don't think there's a solution for that).

Finally, you need to connect your env to Spyder by following the instructions in [our FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

Let us know if this works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
