### ISSUE TITLE
Navigator could not chane Environment (Python3.8/Python3.9)

### ISSUE THREAD

**Issue by Hidemichi-Fujiwara** [spyder-ide/spyder#16617]
### What steps will reproduce the problem?

I set Env roots with 2 patterns(Python3.8(base)/Python3.9(New)). Althrough in Navigator I could set 2 Env roots, But I could not change Python version in spyder.
Now, I have no method and no idea to recover.

### Traceback
```python-traceback
  File "C:\Users\870761\Anaconda3\lib\site-packages\spyder\plugins\plots\widgets\figurebrowser.py", line 389, in show_fig_outline_in_viewer
    qdarkstyle.palette.DarkPalette.COLOR_BACKGROUND_NORMAL)
AttributeError: module 'qdarkstyle.palette' has no attribute 'DarkPalette'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}}
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  2.0.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.27.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.1.0 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.10.0 (OK)
pylint >=1.0                   :  2.9.6 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.2 (OK)
qtconsole >=4.6.0              :  5.1.1 (OK)
qtpy >=1.5.0                   :  1.10.0 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.2.0 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.2.1 (OK)

# Optional:
cython >=0.21                  :  0.29.24 (OK)
matplotlib >=2.0.0             :  3.4.3 (OK)
numpy >=1.7                    :  1.21.2 (OK)
pandas >=0.13.1                :  1.3.3 (OK)
scipy >=0.17.0                 :  1.7.1 (OK)
sympy >=0.7.3                  :  1.8 (OK)
```

**Comment by dalthviz** [comment]
Hi @Hidemichi-Fujiwara seems like you are running Spyder from your base env. If you want to use another env within that Spyder instance you can check the Python interpreter option (`Preferences > Python interpreter > Use the following Python interpreter` ) and select there the env you want to use (your `New` env interpreter path). After setting the interpreter preference, launch another Console instance or restart the current ones to use the new interpreter. If you just want to run Spyder from another env be sure you are selecting the appropiate env in the Anaconda Navigator interface.

For more info maybe checking the docs could be useful:
* Running Spyder from a different env using Anaconda Navigator: https://docs.spyder-ide.org/4/faq.html#run-navigator
* Running Spyder with a different existing env/packages: https://docs.spyder-ide.org/4/faq.html#using-existing-environment

Let us know if that helps !
