### ISSUE TITLE
Completion and linting in the editor... (ERROR)

### ISSUE THREAD

**Issue by WolfyRed** [spyder-ide/spyder#16628]
* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Fresh new installation of Spyder in a brand new directory
2. Opening spider
3. This dialogue pops up

### What is the expected output? What do you see instead?

Not seeing this dialogue, apparently.
Instead, I see this:
![image](https://user-images.githubusercontent.com/66114400/138541159-2c4b6693-ec19-41ed-a859-7b89e2cc2fe0.png)

### Paste Traceback/Error Below (if applicable)

That command being put into the Internal Console outputs this:
```
python-traceback
Traceback (most recent call last):
  File "L:\Program Files\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'python' is not defined
```
It also gives me this error instantly right after:
![image](https://user-images.githubusercontent.com/66114400/138541225-c1026b16-b46f-41d5-ac24-0c50e79ef2fe.png)

## Versions

* Spyder version: IDE 5.1.5
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
! Unable to find menu !
```

*Note: changing Python version does NOT WORK, if that's a suggestion then you should know it only runs when I use Python 3.7.\*.
It gives an error if else...~*

**Comment by ccordoba12** [comment]
Closing due to lack of response.
