### ISSUE TITLE
Cannot install spyder 5.1.5 using conda. 

### ISSUE THREAD

**Issue by Telemaharry** [spyder-ide/spyder#16620]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have been using spyder version 5. (cannot remember the last digit) without any issues. Opened spyder this morning, got a prompt to update to spyder 5.1.5. The prompt said I should first update Anaconda using (conda update anaconda) and conda install spyder=5.1.5 to update the spyder. 

I am getting this error:
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.

### What steps reproduce the problem?

1. I updated anaconda and got error message when I try to install spyder==5.1.5
2. I uninstalled anaconda and re-installed anaconda. The current spyder version is now 4.2.5. Debug tool is not still working
3. I installed a standalone version of spyder 5.1.5. It seems to be working fine but I do not have access to libraries I installed using conda. So, I changed the Python Interpreter to "/Users/telemaharry/opt/anaconda3/bin/python" in the standalone spyder. I got the following error message - Python environment or installation doesn't have the spyder‑kernels module. That I should install spyder-kernels=2.1.
4. I checked the Dependencies for the standalone spyder 5.1.5 and the spyder-kernels is 2.1.1

### Paste Traceback/Error Below (if applicable)

```python-traceback
Error message when installing 

(base) telemaharry@Telemas-MBP ~ % conda install spyder=5.1.5
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistenc\ 

  - defaults/osx-64::conda-build==3.21.4=py38hecd8cb5_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 

Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels=2.1

or

pip install spyder‑kernels==2.1.*

![image](https://user-images.githubusercontent.com/84111462/138377502-f987fedb-41a2-49c0-baf6-c03f67fe0a1b.png)

```

## Versions

* Spyder version: 4.2.5
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Big Sur

### Dependencies

```
This is gotten from spyder 4.2.5
# Mandatory:
applaunchservices >=0.1.7       :  0.2.1 (OK)
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.27.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.1.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.1.1 (OK)
qtpy >=1.5.0                    :  1.10.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.2.0 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.2.1 (OK)

# Optional:
cython >=0.21                   :  0.29.24 (OK)
matplotlib >=2.0.0              :  3.4.3 (OK)
numpy >=1.7                     :  1.21.2 (OK)
pandas >=1.1.1                  :  1.3.3 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  1.8 (OK)
```

**Comment by Telemaharry** [comment]
Thank you for the feedback @ccordoba12
After uninstalling and re-installing anaconda several times, I discovered that  I could no longer install an import library I use frequently. So I formatted my system and re-installed macOS Big Sur Version 11.6.

I then installed anaconda and updated anaconda using conda update in my terminal.
Next, I tried to update spyder again but it is would not install. I got a similar error. 

I am currently using spyder 4.2.5 that came with anaconda. But the issue is that debug is not working.

Preferences > Python interpreter is currently set as default. 

I do not understand why spyder-kernels is not updating to spyder‑kernels=2.1

![image](https://user-images.githubusercontent.com/84111462/138538020-b0d5dcb1-abfa-48f4-b3d3-3a2226207556.png)

**Comment by Telemaharry** [comment]
Following the workaround described by @carsten-bruckhaus  solved the problem. I have now installed spyder 5.1.5
Thank you.

**Comment by mattslezak-shell** [comment]
> A workaround that worked for me: Uninstall Spyder from Anaconda Navigator, then install it again in Navigator. This way, Spyder 5.1.5 was installed without any issue. Could also work from terminal, but I did not try.

Thanks for posting.  After waiting for days (like 3-5) and having conda install spyder=5.1.5 fail with conflicting packages everywhere, this worked in about 20m.  Note that various packages will be randomly uninstalled.   Such as pandas, matplotlib, openpyxl, and others.  You'll just have to install them via conda (which actually has no problem installing them quickly after the  uninstall / install Spyder 5.1.5).

**Comment by onyekaugochukwu** [comment]
> > A workaround that worked for me: Uninstall Spyder from Anaconda Navigator, then install it again in Navigator. This way, Spyder 5.1.5 was installed without any issue. Could also work from terminal, but I did not try.
> 
> Thanks for posting. After waiting for days (like 3-5) and having conda install spyder=5.1.5 fail with conflicting packages everywhere, this worked in about 20m. Note that various packages will be randomly uninstalled. Such as pandas, matplotlib, openpyxl, and others. You'll just have to install them via conda (which actually has no problem installing them quickly after the uninstall / install Spyder 5.1.5).

And now, after I have upgraded Spyder and re-installed all the packages, I find that Spyder 5 does not support Sypder Notebooks. How beautiful 😂😂
