### ISSUE TITLE
Found conflicts! Looking for incompatible packages.

### ISSUE THREAD

**Issue by Juan231260** [spyder-ide/spyder#16623]
Yesterday when I opened Spyder, it indicated that there was a new version available, 5.1.5, I followed the instructions, conda update anaconda and conda install spyder 5.15, it marked Found conflicts! Looking for incompatible packages. and began correction for 16 hours and continues, should I folow or abort?

Thank you

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@srvmig, I think you need to remove and reinstall Anaconda again so everything works for you as it was before.

**Comment by ccordoba12** [comment]
Closing because there's nothing we can do about this in our side.
