### ISSUE TITLE
cannot-update-spyder-5-1-5 

### ISSUE THREAD

**Issue by msacs09** [spyder-ide/spyder#16635]
I have spyder installed via Anaconda and when i try to update to latest one i get the following issue

**conda update anaconda
conda install spyder=5.1.5**

```
and gets an error:
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
```

Seem many people r facing similar issue 

https://stackoverflow.com/questions/69704561/cannot-update-spyder-5-1-5-on-new-anaconda-install

**Comment by pjjanas** [comment]
I'm still getting the original error despite doing all that is listed above and on StackOverflow. Please help.

**Comment by ccordoba12** [comment]
@pjjanas, then remove and reinstall the latest Anaconda version. I think that one comes with Spyder 5.1.5 already available.

**Comment by pjjanas** [comment]
> @pjjanas, then remove and reinstall the latest Anaconda version. I think that one comes with Spyder 5.1.5 already available.

Thanks for your reply. I followed this guide cause I was getting another error: https://stackoverflow.com/questions/55527354/the-environment-is-inconsistent-please-check-the-package-plan-carefully

After following on from MF.OX's comment everything worked fine for me and spyder 5.1.5 was installed!
