### ISSUE TITLE
PyLSP fails to initialise documents

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#16642]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
While debugging issue #16641, I had the issue that spyder did not apparently initialise a document. This happened several time but I don't have a good way of reproducing the problem. This is probably a race condition.

What I see is an error in the terminal running pylsp and pylsp not working for one file.

I only see that while running an external pylsp instance.

### What is the expected output? What do you see instead?

I would expect pylsp to not crash. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

2021-10-26 17:21:31,801 Romance Daylight Time - ERROR - pylsp_jsonrpc.endpoint - Failed to handle notification textDocument/didChange: {'textDocument': {'uri': 'file:///C:/Users/quentin.peter/.spyder-py3-dev/temp.py', 'version': 30}, 'contentChanges': [{'text': 'import ce_sizing as cs'}]}
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pylsp_jsonrpc\endpoint.py", line 145, in _handle_notification
    handler_result = handler(params)
  File "c:\programdata\anaconda3\lib\site-packages\pylsp_jsonrpc\dispatchers.py", line 25, in handler
    return method(**(params or {}))
  File "c:\programdata\anaconda3\lib\site-packages\pylsp\python_lsp.py", line 333, in m_text_document__did_change
    workspace.update_document(
  File "c:\programdata\anaconda3\lib\site-packages\pylsp\workspace.py", line 98, in update_document
    self._docs[doc_uri].apply_change(change)
KeyError: 'file:///C:/Users/quentin.peter/.spyder-py3-dev/temp.py'

```

## Versions

* Spyder version: 5.x dev
* Python version: 3.8.5
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.19.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jellyfish >=0.7               :  None (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.4.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.7.2 (OK)
pygments >=2.0                :  2.7.2 (OK)
pylint >=2.5.0                :  2.6.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.3 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.0 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.2.0 (OK)
sphinx >=0.6.6                :  3.2.1 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.2.0.dev0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  0.10.3 (OK)
zmq >=17                      :  19.0.2 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  1.1.3 (OK)
scipy >=0.17.0                :  1.5.2 (OK)
sympy >=0.7.3                 :  1.6.2 (OK)

```

**Comment by ccordoba12** [comment]
Closing due to lack of response.

@impact27, please reopen this if you find a way to reproduce it.
