### ISSUE TITLE
Is Spyder designed to be conda installed in more than one environment?

### ISSUE THREAD

**Issue by Greedquest** [spyder-ide/spyder#16640]
Related:  #1415, https://stackoverflow.com/q/69688113/6609896

A user may want to install a version of spyder in a second environment; in my case it is so that I can upgrade to >=5.1.0 to test out the new lsp which I cannot do in the base environment where spyder is currently installed owing to conflicts.

Now I know I *can* [`conda install spyder`](https://docs.spyder-ide.org/current/installation.html#new-conda-environment) in a new environment. But this is also described as [the naïve approach](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#the-naive-approach) elsewhere in documentation. Ordinarily conda should allow me to install the same package multiple times safely, however since spyder is a full program and needs to store data like preferences in global places like the registry or User's documents, I thought I should check whether multiple installations are:
 1. A design requirement which you actively test.
 2. A design objective in the back of your minds as you develop; so likely to be supported but not rigorously tested.
 3. A thing that might work but use at your own risk.

Since spyder is not contained purely to the conda env directory, I have to conclude it is partly responsible for managing its own presence in the filesystem and deal with multiple installations without the support of the environment manager. Just wondering what the philosophy is on this.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
