### ISSUE TITLE
Kernel restart when creating plots with Matplotlib

### ISSUE THREAD

**Issue by classAction68** [spyder-ide/spyder#16659]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by meistef** [comment]
Similar problem here! I created another issue thread on this, but it was closed immediately by @spyder-bot.

I obtained similar errors as @Eheran1 and some additional ones for 4.2.5. 

I even tried multiple different approaches of installing and updating conda and anaconda. 

My issue related to this post: Continous Kernel error after Spyder 5.1.5. update, even at previous versions (e.g. 5.0.5, 4.2.5) #16668

**Comment by Hawxxer** [comment]
@meistef did not work for me :I
what worked for me (i am using miniconda) installing spyder 5.1.5 from installer and installing spyder kernels package from channel conda-forge.
Looks like a package is not updated? Idk maybe someone else can try

This is my miniconda env from the working one
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
backcall=0.2.0=pyh9f0ad1d_0
backports=1.0=py_2
backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
ca-certificates=2021.10.8=h5b45459_0
certifi=2021.10.8=py39hcbf5309_0
cloudpickle=2.0.0=pyhd8ed1ab_0
colorama=0.4.4=pyh9f0ad1d_0
cycler=0.11.0=pyhd8ed1ab_0
debugpy=1.4.1=py39h415ef7b_0
decorator=5.1.0=pyhd8ed1ab_0
freetype=2.10.4=h546665d_1
icu=68.2=h0e60522_0
intel-openmp=2021.4.0=h57928b3_3556
ipykernel=6.4.2=py39h832f523_0
ipython=7.28.0=py39h832f523_0
ipython_genutils=0.2.0=py_1
jbig=2.1=h8d14728_2003
jedi=0.18.0=py39hcbf5309_2
jpeg=9d=h8ffe710_0
jupyter_client=6.1.12=pyhd8ed1ab_0
jupyter_core=4.9.1=py39hcbf5309_0
kiwisolver=1.3.2=py39h2e07f2f_0
lcms2=2.12=h2a16943_0
lerc=3.0=h0e60522_0
libblas=3.9.0=12_win64_mkl
libcblas=3.9.0=12_win64_mkl
libclang=11.1.0=default_h5c34c98_1
libdeflate=1.8=h8ffe710_0
liblapack=3.9.0=12_win64_mkl
libpng=1.6.37=h1d00b33_2
libsodium=1.0.18=h8d14728_1
libtiff=4.3.0=hd413186_2
libzlib=1.2.11=h8ffe710_1013
lz4-c=1.9.3=h8ffe710_1
matplotlib=3.4.3=py39hcbf5309_1
matplotlib-base=3.4.3=py39h581301d_1
matplotlib-inline=0.1.3=pyhd8ed1ab_0
mkl=2021.4.0=h0e2418a_729
numpy=1.21.3=py39h6635163_0
olefile=0.46=pyh9f0ad1d_1
openjpeg=2.4.0=hb211442_1
openssl=1.1.1l=h8ffe710_0
parso=0.8.2=pyhd8ed1ab_0
pickleshare=0.7.5=py_1003
pillow=8.3.2=py39h916092e_0
pip=21.2.4=py39haa95532_0
prompt-toolkit=3.0.21=pyha770c72_0
pygments=2.10.0=pyhd8ed1ab_0
pyparsing=3.0.4=pyhd8ed1ab_0
pyqt=5.12.3=py39hcbf5309_7
pyqt-impl=5.12.3=py39h415ef7b_7
pyqt5-sip=4.19.18=py39h415ef7b_7
pyqtchart=5.12=py39h415ef7b_7
pyqtwebengine=5.12.1=py39h415ef7b_7
python=3.9.7=h6244533_1
python-dateutil=2.8.2=pyhd8ed1ab_0
python_abi=3.9=2_cp39
pywin32=301=py39hb82d6ee_0
pyzmq=22.3.0=py39he46f08e_0
qt=5.12.9=h5909a2a_4
setuptools=58.0.4=py39haa95532_0
six=1.16.0=pyh6c4a22f_0
spyder-kernels=2.1.3=py39hcbf5309_0
sqlite=3.36.0=h2bbff1b_0
tbb=2021.4.0=h2d74725_0
tk=8.6.11=h8ffe710_1
tornado=6.1=py39hb82d6ee_1
traitlets=5.1.1=pyhd8ed1ab_0
tzdata=2021e=hda174b7_0
vc=14.2=h21ff451_1
vs2015_runtime=14.27.29016=h5e58377_2
wcwidth=0.2.5=pyh9f0ad1d_2
wheel=0.37.0=pyhd3eb1b0_1
wincertstore=0.2=py39haa95532_2
xz=5.2.5=h62dcd97_1
zeromq=4.3.4=h0e60522_1
zlib=1.2.11=h8ffe710_1013
zstd=1.5.0=h6255e5f_0
```

**Comment by ccordoba12** [comment]
This could be a problem with Matplotlib 3.4.3, as @meistef mentioned. Next week, we'll try to get to the bottom of this problem and see if it needs a fix in Spyder.

**Comment by ccordoba12** [comment]
@dalthviz, could you test this on Windows? Thanks!

**Comment by Hawxxer** [comment]
As shown above it works fine with matplotlib 3.4.3 for me but yeah maybe other subversion?

**Comment by ccordoba12** [comment]
@Hawxxer, it could be a problem with the Matplotlib version packaged by Anaconda (you're using conda-forge).

**Comment by Hawxxer** [comment]
I think I tracked it down to freetype library, maybe someone can confirm that.
The version coming with matplotlib is pkgs/main/win-64::freetype-2.11.0-ha860e81_0 
downgrading to version 2.10.4 works for me with matplotlib 3.4.3 from conda channel itself

**Comment by ccordoba12** [comment]
@Hawxxer, could you try to create a plot outside Spyder? For instance in a Jupyter notebook or the terminal version of IPython?

That's just to be extra sure the problem is not caused by us, so I can write an email about what you find to the Anaconda people.

**Comment by Hawxxer** [comment]
Same behaviour for jupyterlab, freetype 2.10.4 works, 2.11.0 not. Don't know how to test ipython directly

**Comment by Eheran1** [comment]
freetype downgrade from 2.11.0 to 2.10.4 solved the issue. To do this:
`conda install freetype=2.10.4`

**Comment by bilalmussa** [comment]
> Similar problem here! I created another issue thread on this, but it was closed immediately by @spyder-bot.
> 
> I obtained similar errors as @Eheran1 and some additional ones for 4.2.5.
> 
> I even tried multiple different approaches of installing and updating conda and anaconda.
> 
> I think the problem has to do with **the newest version of MatplotLib**, because when I install 5.0.5 it works okay, but when I then update the matplotlib package (base and regular to 3.4.3) I get the kernel error.
> 
> Possible solution: **_As soon as I downgrade matplotlib again to 3.3.4. the plotting issue is no longer there._**
> 
> My issue related to this post: Continous Kernel error after Spyder 5.1.5. update, even at previous versions (e.g. 5.0.5, 4.2.5) #16668

Hiya - i gave this a shot and the kernal restarts everytime I use 
ax = plt.gca()

Any suggestions?

**Comment by ccordoba12** [comment]
@bilalmussa, please read the message jus above yours.

**Comment by Bobuwashere** [comment]
Hi,

I'm getting the following error below with freetype 2.10.4 and matplotlib 3.4.4
 
  File "C:\Users\mikta\Documents\KaggleProjects\HowMuchDidItRain\Spyder\aeryys.py", line 39, in <module>
    plt.matshow(corr_mat, fignum=f.number)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2461, in matshow
    ax = fig.add_axes([0.15, 0.09, 0.775, 0.775])

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\figure.py", line 654, in add_axes
    a = projection_class(self, rect, **pkw)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\_api\deprecation.py", line 471, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 634, in __init__
    self.cla()

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 1245, in cla
    self.grid(False)  # Disable grid on init to use rcParameter

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 3064, in grid
    self.xaxis.grid(b, which=which, **kwargs)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axis.py", line 1433, in grid
    self.set_tick_params(which='major', **gridkw)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axis.py", line 856, in set_tick_params
    for tick in self.majorTicks:

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axis.py", line 607, in __get__
    tick = instance._get_tick(major=True)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axis.py", line 2059, in _get_tick
    return XTick(self.axes, 0, major=major, **tick_kw)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axis.py", line 420, in __init__
    super().__init__(*args, **kwargs)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\_api\deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\axis.py", line 123, in __init__
    labelcolor = mpl.rcParams[f"{name}.labelcolor"]

  File "C:\Users\mikta\anaconda3\lib\site-packages\matplotlib\__init__.py", line 708, in __getitem__

KeyError: 'xtick.labelcolor'

**Comment by ccordoba12** [comment]
@Bobuwashere, your error is not related to Spyder nor to the problem discussed here. Please open it in the Matplotlib repository.

**Comment by Mantal123** [comment]
> freetype downgrade from 2.11.0 to 2.10.4 solved the issue. To do this: `conda install freetype=2.10.4`

This problem has been confusing me for a few days, and now it is solved by your help. Thanks!!!

**Comment by whitedear** [comment]
I can add that my spyder kernel is also restarting when doing plt.plot(0,1) in an environment i have created in Miniconda with a textfile.
I dont have this problem if i create a new environment without the textfile and install the packages manually. Using spyder 5.1.5

**Comment by chuckf201** [comment]
I appears that conda update anaconda gives error messages and debug messages. I think that anaconda is at fault.

**Comment by pepo83** [comment]
I have a similar problem:
https://github.com/spyder-ide/spyder/issues/16732

freetype downgrade from 2.11.0 to 2.10.4 solved the issue for me too!
Thanks @Eheran1

**Comment by classAction68** [comment]
I can confirm that downgrading freetype from 2.11.0 to 2.10.4 also seems to have solved the problem for me

**Comment by Earthman12** [comment]
Downgrading freetype from 2.11.0 to 2.10.4 solved the issue for me as well.

**Comment by ccordoba12** [comment]
Hey everyone, thanks for participating. I'm going to leave here (again) the command to solve this problem and then block the issue so that other people can see it when arriving here.

The command is

    conda install freetype=2.10.4
