### ISSUE TITLE
Continous Kernel error after Spyder 5.1.5. update, even at previous versions (e.g. 5.0.5, 4.2.5)

### ISSUE THREAD

**Issue by meistef** [spyder-ide/spyder#16668]
## Problem Description
I recently update my spyder to version 5.1.5 by following these steps:
`conda remove spyder`
`conda remove python-language-server`
`conda update anaconda`
`conda install spyder=5.1.5`

This was proposed by @ccordoba12 in this stackoverflow post: [https://stackoverflow.com/questions/69704561/cannot-update-spyder-5-1-5-on-new-anaconda-install]

The spyder package did update but it no longer allowed me to run a function wherein I make > 10 plots. It would just crash and state `Restarting kernel...` in the IPython console.

I uninstalled anaconda by the following procedure:
1. `conda install anaconda-clean`
2. `anaconda-clean --yes`
3. delete envs and pkgs folders 
4. running the uninstall 
5. delete remaining anaconda folders and backups
6. reboot computer

Aftwards, I reinstalled anaconda via the normal steps. Spyder 4.2.5 works fine, though with older version of specific packages.

I updated anaconda again:
1. `conda update conda`
2. `conda install anaconda=2021.05`

Initially, this seemed to work fine (no kernel errors in 4.2.5), but as soon as I try to update spyder to for example 5.0.5 (which was the version that I used before the initial update to 5.1.5.) with `conda install spyder=5.0.5`, I obtained this error in the terminal:
```Solving environment: failed with initial frozen solve. Retrying with flexible solve.``` and ``` Found conflicts! Looking for incompatible packages.``` 

So, I followed the procedure proposed by Spyder again (when you start spyder):
`conda update anaconda`
`conda install spyder=5.0.5`

Then during the installation of 5.0.5 I got this error: ```The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:  - defaults/win-64::conda-build==3.21.4=py38haa95532_0``` 
But I could continue the installation of 5.0.5 by just pressing y. 

When I then start Spyder 5.0.5 and run my script, it will run the first half and then as soon as it comes to the plotting function it creates this error: ``` AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'``` . Downgrading to 4.2.5 again produces this error again.

This problem has been bugging me for hours and eventhough I really like and love Spyder, this problem is making it impossible for me to use this Python IDE.

This problem is related to this stackoverflow post: [https://stackoverflow.com/questions/69775098/spyder-5-1-5-creates-a-new-kernel-after-running-a-custom-function]

### Paste Traceback/Error Below
The following error could be obtained from 4.2.5 and 5.0.5

```python-traceback

AttributeError: 'SpyderKernelManager' object has no attribute 'kernel'

```

## Versions
* Spyder version: 5.0.5
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  1.0.2 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)

```

**Comment by meistef** [comment]
@spyder-bot This procedure did not resolve the problem.

**Comment by ccordoba12** [comment]
Let's keep discussing about this problem on issue #16659.
