### ISSUE TITLE
The following packages are causing the inconsistency:    - defaults/win-64::conda-build==3.21.4=py38haa95532_0

### ISSUE THREAD

**Issue by tolgayilmaz** [spyder-ide/spyder#16666]
## Problem Description
This problem started shortly after I installed the _tensorflow_ package. When I tried to update Spyder from 4.2.5 that came with the Anaconda Individual Edition (2021-05) to 5.1.5 using `conda update anaconda` and `conda install spyder=5.1.5` shortly after installing _tensorflow_, it gave me the following error message:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::conda-build==3.21.4=py38haa95532_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
```

which lasted for hours without any success, so I had to abort it with Ctrl+C. 

Then, I tried to update Spyder using `pip install spyder==5.1.5`, which seemed to work, so I was actually able to use Spyder 5.1.5 for a while. But when I tried to open Spyder again sometime later, it repeatedly failed to launch.

So, I uninstalled and reinstalled Anaconda, and retried to update Spyder using the `conda update anaconda` and `conda install spyder=5.1.5` commands. But the same thing happened again: found inconsistencies...

So, I uninstalled Anaconda and manually deleted some residual Anaconda-related folders and files on my hard drive (did a Windows search for `**conda**`, `**python**`, and `**spyder**`), and retried the `conda update anaconda` and `conda install spyder=5.1.5` commands. But the same thing happened again: found inconsistencies...

So, I uninstalled Anaconda and manually deleted ALL of the residual Anaconda-related files that I could find on my computer, this time also uninstalled PyCharm and Atom (just in case), and then reinstalled Anaconda (downloading afresh the Anaconda Individual Edition), and then retried the `conda update anaconda` and `conda install spyder=5.1.5` commands. But the same thing is happening again as I write these... I believe it is going to run for hours again without any success. I don't even know how this process is supposed to end. Is it guaranteed to solve the inconsistency problem if given enough time? What does it do if/after it locates all of the inconsistencies? Does it solve them by itself? Or does it only offer you some suggestions? Does knowing the name of the package responsible for the conflict (defaults/win-64::conda-build==3.21.4=py38haa95532_0), reported already at the beginning, help in any way in solving this problem manually?

### What steps reproduce the problem?

1. Uninstall Anaconda
2. Restart computer
3. Manually delete all residual Anaconda-related files in hard drive (searching for `**conda**`, `**spyder**`, and `**python**`)
4. Restart computer
5. Reinstall Anaconda
6. Run `conda update anaconda` and `conda install spyder=5.1.5` to try to upgrade Spyder from 4.2.5 to 5.1.5  

### What is the expected output? What do you see instead?

I'm expecting `conda update anaconda` and `conda install spyder=5.1.5` to update the Spyder 4.2.5 that comes with the latest Anaconda Individual Edition to Spyder 5.1.5. Instead, the second command returns an error message that the environment is inconsistent, a certain `conda-build` package is causing this inconsistency, and so and so forth, a process which lasts forever...

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) PS C:\Users\tolga> conda install spyder=5.1.5
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::conda-build==3.21.4=py38haa95532_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining numpy:   2%|█▎                                                               | 7/357 [00:05<01:33,  3.73it/s]-Examining clyent:   8%|█████                                                          | 29/357 [00:13<02:08,  2.54it/s]\Examining nbclassic:  10%|██████                                                      | 36/357 [00:15<01:47,  2.98it/s]/Examining typing_extensions:  11%|█████▋                                              | 39/357 [00:15<01:09,  4.59it/s]-Examining ipython:  12%|███████▍                                                      | 43/357 [00:16<00:59,  5.30it/s]/Examining multipledispatch:  16%|████████▍                                            | 57/357 [00:19<00:57,  5.20it/s]/Examining python-jsonrpc-server:  18%|████████▍                                       | 63/357 [00:19<00:36,  7.97it/s]\Examining libllvm9:  19%|███████████▌                                                 | 68/357 [00:19<00:32,  9.01it/s]|Examining icu:  21%|██████████████                                                    | 76/357 [00:27<01:49,  2.57it/s]/Examining zeromq:  22%|█████████████▊                                                 | 78/357 [00:27<04:10,  1.11it/s]-Examining libxml2:  24%|██████████████▊                                               | 85/357 [00:27<02:58,  1.52it/s]\Examining win_unicode_console:  26%|█████████████▏                                    | 94/357 [00:28<00:49,  5.28it/s]|Examining attrs:  28%|█████████████████▊                                             | 101/357 [00:29<00:33,  7.65it/s]/Examining pytz:  29%|██████████████████▍                                             | 103/357 [00:29<00:31,  8.13it/s]-Examining paramiko:  29%|█████████████████▋                                          | 105/357 [00:29<00:32,  7.85it/s]|Examining fonttools:  31%|██████████████████                                         | 109/357 [00:30<00:36,  6.80it/s]\Examining mkl_fft:  31%|██████████████████▊                                          | Examining conflict for anaconda anaconda-client conda _anaconda_depends anaconda-project ruamel_yaml anaconda-navigator conda-token conda-build:   1%|▌                                   | 5/357 [22:53<28:19:36, 289.71s/i-


```

## Versions

* Spyder version: 4.2.5 (trying to update to 5.1.5)
* Python version: 3.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro 21H1

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  2.0.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=7.6.0                 :  7.27.0 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  23.1.0 (OK)
nbconvert >=4.0                 :  6.1.0 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.10.0 (OK)
pylint >=1.0                    :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.2             :  0.3.2 (OK)
qdarkstyle >=2.8;<3.0           :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.3               :  5.1.1 (OK)
qtpy >=1.5.0                    :  1.10.0 (OK)
rtree >=0.8.3                   :  0.9.7 (OK)
setuptools >=39.0.0             :  58.0.4 (OK)
sphinx >=0.6.6                  :  4.2.0 (OK)
spyder_kernels >=1.10.2;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.1 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0        :  1.0.2 (OK)
zmq >=17                        :  22.2.1 (OK)

# Optional:
cython >=0.21                   :  0.29.24 (OK)
matplotlib >=2.0.0              :  3.4.3 (OK)
numpy >=1.7                     :  1.21.2 (OK)
pandas >=1.1.1                  :  1.3.3 (OK)
scipy >=0.17.0                  :  1.7.1 (OK)
sympy >=0.7.3                   :  1.9 (OK)
```

**Comment by meistef** [comment]
Dear @tolgayilmaz ,

I have a similar issue with a kernel restarting problem. Curious about the solution.

**Comment by ccordoba12** [comment]
Hey @tolgayilmaz, thanks for reporting. You said

> When I tried to update Spyder from 4.2.5 that came with the Anaconda Individual Edition (2021-05) to 5.1.5 using conda update anaconda and conda install spyder=5.1.5 shortly after installing tensorflow, it gave me the following error message

I posted the solution here

https://stackoverflow.com/questions/69704561/cannot-update-spyder-5-1-5-on-new-anaconda-install

StackOverflow is down at the moment, so I repost the necessary commands below:

    conda remove spyder
    conda remove python-language-server
    conda update anaconda
    conda install spyder=5.1.5

> Then, I tried to update Spyder using pip install spyder==5.1.5

Please don't **ever** do that again. We warn against that everywhere we can because it breaks Spyder in Anaconda. In other words, if you're using Spyder with Anaconda, you must always use conda to install or update it.

**Comment by tolgayilmaz** [comment]
Worked flawlessly and fast. Thanks @ccordoba12!
