### ISSUE TITLE
Missing dates for ChangeLog

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1667]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-12-06T10:50:30Z_

https://code.google.com/p/spyderlib/wiki/ChangeLog I miss release dates in ChangeLog to see how good are we at bugfixing. =)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1667_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T17:48:11Z_

You could get them from our mercurial history. Sorry but I don't have time to do it.

**Comment by ccordoba12** [comment]
This can easily obtained from `git log`.
