### ISSUE TITLE
Error still coming but dependencies have been installed

### ISSUE THREAD

**Issue by gmmkmtgk** [spyder-ide/spyder#16679]
Here is the screenshot 
https://i.postimg.cc/PrMjdj0L/Screenshot-from-2021-10-30-23-29-39.png

You have missing dependencies!

# Mandatory:
jedi =0.17.2 : 0.16.0 (NOK)
parso =0.7.0 : 0.6.2 (NOK)

Please install them to avoid this message.

Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you to install all the listed missing dependencies.

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.

**Comment by ccordoba12** [comment]
Hey @gmmkmtgk, thanks for reporting. You need to run the following commands to have the right versions of those dependencies

    pip install jedi==0.17.2
    pip install parso=0.7.0

Please try that and let us know if it works for you.

**Comment by gmmkmtgk** [comment]
Thanks it worked
