### ISSUE TITLE
Cannot open desidred directory or from the place where I left 

### ISSUE THREAD

**Issue by gmmkmtgk** [spyder-ide/spyder#16682]
Cannot open the desired directory or from the place where I left. Spyder always opens the same file at the start and the location is always home/keshav even I use the terminal to open from /home/keshav/Desktop/AlgoTrading/IndianMarket for example. I have attached a screenshot. In vscode you for example by default it opens from the place were you left your work.

![Screenshot from 2021-10-31 00-19-45](https://user-images.githubusercontent.com/51493190/139555347-5b557f39-5864-4bdf-9fbb-1f7ada23757b.png)

Another isuue
Always getting 
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid
every time after 1 min of opening spyder

**Comment by ccordoba12** [comment]
Please see how our Projects functionality work in our documentation, so you can learn how to get the behavior that you want:

http://docs.spyder-ide.org/current/panes/projects.html

Also, you can create projects from the command line by running

    spyder --project /path/to/my/directory
