### ISSUE TITLE
Cannot open more than one window 

### ISSUE THREAD

**Issue by gmmkmtgk** [spyder-ide/spyder#16683]
In code editors like Vs code for example you can create infinitely many windows but in spyder, you can only open one at a time. Is there any way to do so in spyder if no then will the UX team of spyder planning to incorporate this user enhancement 

![Screenshot from 2021-10-31 00-38-51](https://user-images.githubusercontent.com/51493190/139555670-19051e39-308b-4ac5-bdb4-2f51b3316922.png)
![Screenshot from 2021-10-31 00-39-32](https://user-images.githubusercontent.com/51493190/139555671-3b2080c9-a29f-4bb4-8754-4f06e558705a.png)

There was no option in the file menu so I tried like this 

Spyder is already running. If you want to open a new 
instance, please pass to it the --new-instance option

![Screenshot from 2021-10-31 00-42-13](https://user-images.githubusercontent.com/51493190/139555738-93cf42dd-1bf6-4655-8dbe-51cdbd46569c.png)

What is meant by --new-instance here

**Comment by ccordoba12** [comment]
Please go to the menu

    Tools > Preferences > General > Advanced Settings

and deactivate the option called

    Use a single instance

**Comment by ccordoba12** [comment]
> What is meant by --new-instance here

It's the command line option to create a new Spyder window.

**Comment by ccordoba12** [comment]
Also, please note that this is not a a place to ask general questions about Spyder, but to report errors about it. So, please invest a bit more time searching for answers on the web.
