### ISSUE TITLE
Menu item and shortcut to toggle UPPER and lower case of selected text

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1669]
_From [bwanama...@gmail.com](https://code.google.com/u/114749747116603825948/) on 2013-12-06T16:55:51Z_

## What steps will reproduce the problem?

1. desire to convert from UPPER to lower or vv
2. look in the menu bar under Edit, search issues, wikis and discussion group
3. accept that this feature does not exist

## What is the expected output? What do you see instead?

There is a feature in the menu bar and with a shortcut that allows one to toggle the case of selected text from UPPER to lower case and vv

## What version of the product are you using? On what operating system?

Windows-7 (AMD64)/Xubuntu-13.10 (AMD64)/Ubuntu-13.10 (x86)
Python-2.7.6 (AMD64)
Spyder-2.2.5

## Please provide any additional information below

Here some examples of key combinations from other editors that do the same thing:

editor | UPPER | lower
------ |  ------ | -----
MATLAB | ctr-shift-U | ctrl-U
Notepad++ | ctr-shift-U | ctrl-U
PyDev | ctrl-shift-X | ctrl-shift-Y
Sublime-Text-2 | ctrl-K, ctrl-U | ctrl-K, ctrl-L

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1669_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-12-11T17:38:16Z_

Thanks for reporting. We'll see what we can do about it.

**Labels:** -Priority-Medium Priority-Low MS-v2.4

**Comment by thewhitetulip** [comment]
@goanpeca I would like to work on this one now..

**Comment by gamesbook** [comment]
What is the status of this?  #2601 and #1669 cross-reference each but both are closed?

**Comment by gamesbook** [comment]
Any update on this task?

**Comment by ccordoba12** [comment]
Nop. We'll take a look at it for 3.1 :-)

**Comment by gamesbook** [comment]
Thanks, guys. (Sometimes it **is** just the little things that count.)

**Comment by ccordoba12** [comment]
I think we should follow Matlab's shortcuts here. @goanpeca, what do you think?

**Comment by goanpeca** [comment]
:+1:

**Comment by malliwi88** [comment]
I'm working on it :+1:

**Comment by malliwi88** [comment]
@gamesbook Good news for you

A PR #3629  is waiting for merge. this functionality will come soon.

Thank's for your suggestion for help us to made of Spyder better.

**Comment by ccordoba12** [comment]
This was fixed in PR #3629. Thanks @malliwi88!
