### ISSUE TITLE
my plots in Qt are crashing the kernel. How do I downgrade to the previous version?

### ISSUE THREAD

**Issue by HugoCavalcante** [spyder-ide/spyder#16704]
### What steps will reproduce the problem?

Generate any plots with matplotlib.

Ex: 
from numpy import sin, linspace
from matplotlib.pyplot import plot
x = linspace(0, 6)
y = sin(x)
plot(x,y)

-> Restarting kernel!

**Comment by HugoCavalcante** [comment]
I just updated Spyder to 5.1.5, running the latest version in Windows 10. Installed with Miniconda. I don't know how to revert the installation/upgrade.

**Comment by ccordoba12** [comment]
Hey @HugoCavalcante, thanks for reporting. Please see the last comment on issue #16659 for the solution to this problem.

**Comment by HugoCavalcante** [comment]
Problem solved. Here is a how-to:
conda install freetype=2.10.4

Thanks @ccordoba12 !
