### ISSUE TITLE
Connet create a console

### ISSUE THREAD

**Issue by roy96w** [spyder-ide/spyder#16715]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Met the problem when opening Spyder 5.1.5
"Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.1.0 and < 2.2.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels=2.1"

I tried but didn't work.
 the spyder in conda is work.

The info of Spyder:
* Spyder version: 5.1.5 None
* Python version: 3.9.5 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 21.1.0

**Comment by dalthviz** [comment]
Closing due to lack of response
