### ISSUE TITLE
Remove Kite startup splash screen when Spyder starts

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder#16744]
Kite nagger screen is a BUG as far as I am concerned.  

There is no checkbox to permanently disable the Spyder Startup "Nagger" Screen for Kite. 

Please add a way to get rid of this forever.  I've seen it too many times.   

Where do I disable this permanently ?  

Please post instructions to eliminate it !!

Thank you.  

Richard

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @richdevboston , sorry for the late reply. Could you submit here a screenshot to better undertand what are you talking? Let us know

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by ccordoba12** [comment]
We decided to address this in our next version (5.2.1). So, when you update to it you won't see that dialog anymore.
