### ISSUE TITLE
"Create new project" dialog box button focus is "Cancel" not "Create" 

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder#16745]
When creating a new project in Spyder the default button highlighted is "Cancel", not "Create".

So the user (me) enters the new project information, hits the "Enter" key on the keyboard, and the dialog box disappears without creating the project, because the "Cancel" button is highlighted by default.  So I have to re-enter the information.  

I have trained myself to not use the mouse, and rely on well-designed GUIs to have the proper defaults keyboard shortcuts for the operation at hand, in this case "Create" project.  

Please cleanup this minor usability issue in the next release.  

Thank you. 

Rich

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @richdevboston, thanks for reporting. We'll try to fix this in our next version (5.2.0), to be released in a couple of weeks.
