### ISSUE TITLE
has_been_modified method has two arguments but only one is passed in Preferences

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#16749]
Hello.
"has_been_modified" of api.py has 2 arguments.
https://github.com/spyder-ide/spyder/blob/c5b4291245dc8b0ee71705175023f0fbe0f565c9/spyder/plugins/preferences/api.py#L387-L389

But in the code below, only one is entered. 
https://github.com/spyder-ide/spyder/blob/c5b4291245dc8b0ee71705175023f0fbe0f565c9/spyder/plugins/shortcuts/confpage.py#L64-L66

Thank you.

**Comment by ccordoba12** [comment]
Hey @ok97465, thanks for reporting. We'll try to take a look at this problem after we release 5.2.0 in a couple of weeks.

**Comment by ccordoba12** [comment]
@steff456, could you take a look at this one next week? I noticed it's a serious bug because it doesn't allow to set new shortcuts in Spyder.
