### ISSUE TITLE
plt.plot does not work

### ISSUE THREAD

**Issue by Carl-H-GitHub** [spyder-ide/spyder#16759]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Using plt.plot (and executing) opens a window which crashes immediately

**Comment by ccordoba12** [comment]
Hey @Carl-H-GitHub, thanks for reporting. This is a duplicate of issue #16659.

Please see the last comment there for the solution.
