### ISSUE TITLE
app/tests/test_mainwindow.py::test_runcell_pdb is failing

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#16763]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
 spyder/app/tests/test_mainwindow.py::test_runcell_pdb fails

### What steps reproduce the problem?

1. Create a PR against 5.x
2. Push it
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
I've seen failures related to that test, but I think that's because it's quite flaky, specially on Mac. On Linux and Windows it seems to be working fine.

**Comment by impact27** [comment]
There is a race condition, and it seems that the update to the ipythonconsole plugin triggers the failure consistently for the mac test. This is an issue with qtconsole.
