### ISSUE TITLE
Associating .py files to Spyder on Windows 10

### ISSUE THREAD

**Issue by Denhol1** [spyder-ide/spyder#16770]
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X ] Tried basic troubleshooting (if a bug/error)
    * [X ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Just intalled the standalone version of spyder 5.1.5 on a windows 10 64 bits environment - as recommended on the Spyder web-site. (Not through Anaconda)

Spyder works fine but I cannot seem to find a way to associate .py files to spyder so that (as we other software) a double click on the file would open it in the Spyder IDE.

I have tried to right click on a .py file and tried to find spyder in the "open with" options - no spyder or spyder.exe to be found

I have tried to use the "Choose default applications by file type" - no more luck

I have looked for any option to define file associations in Spyder and found none

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @Denhol1,

I'm not sure why you are unable to set Spyder as the default, @dalthviz do you know why this may be happening?

**Comment by dalthviz** [comment]
Currently the standalone version doesn't support being set as the default program to open files. What we added for the moment is an option from the file explorer context menu to open files with Spyder:
![menu](https://user-images.githubusercontent.com/16781833/140802973-346879fe-59cf-4582-8a30-2aed9258dbfe.png)

Also this could be related to https://github.com/spyder-ide/spyder/issues/3835 and https://github.com/spyder-ide/spyder/issues/15534

**Comment by Denhol1** [comment]
Thanks @dalthviz & @steff456 , I did not see the context menu [headpalm] !!! This works just fine.
