### ISSUE TITLE
Plugin API for AppEngine SDK support

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1678]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2013-12-16T03:51:36Z_

What steps will reproduce the problem?
1. I have to use AppEngine Launcher in addition to Spyder for my Google projects
   1. AppEngine Launcher is outdated up to complete fail to work with recent Python/SDK What is the expected output? What do you see instead? Expected (for the first iteration).
   2. AppEngine panel with buttons - [start/stop server]
   3. Panel is active only when there is app.yaml in "current project" (alternatively on some level of "current directory tree")
   4. AppEngine SDK path is configured

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1678_

**Comment by goanpeca** [comment]
@ccordoba12 I dont undertsand the issue here plus its kinda stale, can we close this?

**Comment by ccordoba12** [comment]
Sure.
