### ISSUE TITLE
AttributeError: 'EvalEnv' object has no attribute 'get'

### ISSUE THREAD

**Issue by codexhammer** [spyder-ide/spyder#16780]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
 After clicking the debug button, it throws this error on the line "import torch_geometric". But, the program works perfectly well if I just run the entire code without debugging line by line.

### To reproduce the problem:

1.  Install torch_geometric with this cmd:     `conda install pyg -c pyg -c conda-forge`
2.  Create a new python file.
3. Type: `from torch_geometric.nn import GCNConv`
4.  Click on debug button

### Paste Traceback/Error Below (if applicable)

![error](https://user-images.githubusercontent.com/19278722/140908902-26108967-4f76-4518-9505-c9984cc0a8d4.png)

## Versions

* Spyder version:  5.1.5
* Python version:  Python 3.9.7 64-bit
* Qt version:  Qt 5.9.7
* PyQt version:   PyQt5 5.9.2 
* Operating System name/version:  Windows 10

**Comment by ccordoba12** [comment]
Hey @codexhammer, thanks for reporting. This seems very strange indeed.

@impact27, could you take a look at this one?

**Comment by codexhammer** [comment]
This isn't a new problem. It's linked with IPython console. Take a look at this page: [](https://blog.csdn.net/July_Wander/article/details/107377533)

(Use Google Translate)
