### ISSUE TITLE
Use single instance selection grayed out in MacOS 12 + Spyder 5.1.5

### ISSUE THREAD

**Issue by yzhao062** [spyder-ide/spyder#16793]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Using the standalone installation of Spyder 5.1.5 on MacOS 12.01 (along with M1 Max), the selection of Use single instance is grayed out.

![image](https://user-images.githubusercontent.com/15079146/141201673-a11ca320-9605-4824-853f-d49a530abd89.png)

I tried to reset Spyder but this does not help. Appreciate any pointers!

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.5 64-bit
* Qt version: 5.12.10
* PyQt version: PyQt5 5.12.3
* Operating System name/version: MacOS 12.01 Darwin 21.1.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.2.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.5 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

**Comment by ccordoba12** [comment]
Hey @yzhao062, thanks for reporting. Mac applications are not supposed to have multiple instances. For example, you can't many instances of App Store or Notes. That's why that option is not available in Mac.

@mrclary, what do you think about this?

**Comment by mrclary** [comment]
I think that the macOS application should not have multiple instances, as @ccordoba12 has explained.

One thing to consider is that when we implement multiple simultaneous projects, we may not need multiple instances for any distribution type. 

Except for multiple projects, what other use cases are there for multiple Spyder instances?

**Comment by yzhao062** [comment]
Thanks for the quick response!
Just want to provide a bit more thoughts on this...I feel the multi-instance on Mac is still helpful. For example, I often run multiple machine learning applications with slightly different parameters in independent instances, so that their variable explorers do not interfere with each other. This has been helpful in my cases, especially the non-distributed programs.

Another thing is somehow I recall it was possible with my old Mac years ago. I am not sure whether it is just because of my poor memory.

Anyway thanks for the feedback, and it would be nice this feature may be considered in the future.

**Comment by ccordoba12** [comment]
> I think that the macOS application should not have multiple instances, as @ccordoba12 has explained.

Right, that's why I disabled that option in our Mac app

> Except for multiple projects, what other use cases are there for multiple Spyder instances?

Yeah, I think there aren't.

**Comment by yzhao062** [comment]
> > I think that the macOS application should not have multiple instances, as @ccordoba12 has explained.
> 
> Right, that's why I disabled that option in our Mac app
> 
> > Except for multiple projects, what other use cases are there for multiple Spyder instances?
> 
> Yeah, I think there aren't.

Thanks for the further clarification. I am just curious what is the specific advantage of disabling it? Is there a specific reason for MacOS? 

I guess either multiple projects (I think nowadays many people are multi-tasking) or tuning within the single project can benefit from it. So I would appreciate it if there is flexibility to choose that. I may be able to revert back to an earlier version.

Anyway, thanks for the work and this information is helpful :)

**Comment by ccordoba12** [comment]
> Just want to provide a bit more thoughts on this...I feel the multi-instance on Mac is still helpful. For example, I often run multiple machine learning applications with slightly different parameters in independent instances

That's why we provide the ability to open multiple IPython consoles by going to the menu `Consoles > New console (default settings)`. In other words, you can open one console for each machine learning model you want to evaluate, and run your code accordingly.

>  so that their variable explorers do not interfere with each other.

The Variable Explorer and Plots panes only display the variables/plots of the console with current focus, so there's no change that they interfere with each other.

> Another thing is somehow I recall it was possible with my old Mac years ago. I am not sure whether it is just because of my poor memory.

As far as I recall, that has never been possible (I've been a casual Mac user since 10.6).

**Comment by yzhao062** [comment]
> > Just want to provide a bit more thoughts on this...I feel the multi-instance on Mac is still helpful. For example, I often run multiple machine learning applications with slightly different parameters in independent instances
> 
> That's why we provide the ability to open multiple IPython consoles by going to the menu `Consoles > New console (default settings)`. In other words, you can open one console for each machine learning model you want to evaluate, and run your code accordingly.
> 
> > so that their variable explorers do not interfere with each other.
> 
> The Variable Explorer and Plots panes only display the variables/plots of the console with current focus, so there's no chance that they interfere with each other.
> 
> > Another thing is somehow I recall it was possible with my old Mac years ago. I am not sure whether it is just because of my poor memory.
> 
> As far as I recall, that has never been possible (I've been a casual Mac user since 10.6).

thanks for the pointers. I will try to use the multi-console features! Looks great at the first glance.
It may be helpful to tag the variable explorer pop-up with the console index. just a thought. 

I think I do not have further questions here. Feel free to close it if that is preferred :) Again, thanks a lot!

**Comment by ccordoba12** [comment]
Ok, closing then.

**Comment by dmilstone** [comment]
The suggested solution, "New Console", is greyed out (see photo) on my MacBook Pro (MacOS 12.6.1, Spyder 5.4.2). The keystroke equivalent is greyed out and selecting the text (not greyed out) does not launch a new console. What now?

I use multiple instances of Spyder in Windows 10. It's useful to me. This seems similar to running several windows simultaneously of Terminal in MacOS? I don't know if those  Terminal windows represent "instances", "consoles" or something else, but they are useful in the same way that multiple instances are useful to me in Windows.

![Screen Shot 2023-02-06 at 11 34 23 AM](https://user-images.githubusercontent.com/40602919/217029811-e9ff26fc-5f36-49a3-946d-9ab5fe058e39.png)
