### ISSUE TITLE
Support for inline defs, ifs, and fors

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1679]
_From [sankey...@gmail.com](https://code.google.com/u/103240522457225808434/) on 2013-12-16T11:32:07Z_

Spyder 2.2.5, Windows 7, python 2.7

One minor bug is whenever I try to type an inline statement such as

for n in range(10): print n

It adds a colon at the end of the line and thinks it should indent. Same goes for inline function defs, ifs, whiles, etc...

I use this kind of thing a lot because it helps line up code and make it readable.

Cheers!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1679_

**Comment by goanpeca** [comment]
We should change the title of this issue, it is misleading.

More like... **Editor incorrectly adds colon and indentation on inline defs, ifs, and fors**

Should I do this sort of things directly? or you want to be asked first @ccordoba12 ?

**Comment by Nodd** [comment]
This is a multi-duplicate:
https://github.com/spyder-ide/spyder/issues/872
https://github.com/spyder-ide/spyder/issues/1417
https://github.com/spyder-ide/spyder/issues/1448
