### ISSUE TITLE
Spyder Notebook

### ISSUE THREAD

**Issue by RPArmstrong** [spyder-ide/spyder#16805]
### What steps will reproduce the problem?

Using Anaconda and all reference material avaliable online I am unable to get spyder 5.1.5 to provide access to the spyder-notebook add-on. Is this a version compatibility issue? I have exhausted stackoverflow forums and all material by Spyder or otherwise. Any suggestions?

**Comment by ccordoba12** [comment]
Hey @RPArmstrong, thanks for reporting. Unfortunately, Spyder-notebook has not been migrated yet to support 5, sorry.

There's some work towards that at the moment (see spyder-ide/spyder-notebook#369). I hope to finish it in a couple of months.

**Comment by RPArmstrong** [comment]
Thank you very much. You saved me from wasting (more) hours trying to get this running! 😊
