### ISSUE TITLE
Unable to start the kernal, unable to install spyder-kernals

### ISSUE THREAD

**Issue by gli-1** [spyder-ide/spyder#16807]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
The Spyder that was installed on Anaconda was unable to be updated due to package conflict. When I installed the standalone Spyder, the console was not functioning, with a message saying: an error ocurred while starting the kernel. I was unable to run conda install spyder-kernels=2.1 because of this warning: Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source. I googled for solution but all attempts failed.

**Comment by ccordoba12** [comment]
Hey @gli-1, thanks for reporting. To solve the problem with Spyder-kernels, please close Spyder, open the Anaconda Prompt (or Terminal.app in Mac) and run the following commands:

    conda remove spyder
    conda remove python-language-server
    conda update anaconda
    conda install spyder-kernels=2.1.3

Some of those commands can show you errors, but that's fine. Simply ignore them and continue with the others.

Let us know if it works for you.

**Comment by SlimShadys** [comment]
> Hey @gli-1, thanks for reporting. To solve the problem with Spyder-kernels, please close Spyder, open the Anaconda Prompt (or Terminal.app in Mac) and run the following commands:
> 
> ```
> conda remove spyder
> conda remove python-language-server
> conda update anaconda
> conda install spyder-kernels=2.1.3
> ```
> 
> Some of those commands can show you errors, but that's fine. Simply ignore them and continue with the others.
> 
> Let us know if it works for you.

I don't know why, but this doesn't work for me.

I've tried all the commands written in the reply above, and the output even says:
```
# All requested packages already installed
```

**Comment by ccordoba12** [comment]
> but then, the console for the standalone Spyder is still not functional.

What do you mean by this?

> but it's still the old Spyder version when I restarted the anaconda navigator.

What happens if you start Spyder from the Anaconda Prompt?

**Comment by R2D2Hud** [comment]
I have this problem with a venv that uses python 3.9.4. However, a different venv that uses python 3.8.11 everything works fine.

**Comment by ccordoba12** [comment]
@R2D2Hud, what problem exactly?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
