### ISSUE TITLE
Disable GPU - hardware accelerator when using Spyder -because it makes the pc hot

### ISSUE THREAD

**Issue by vantienvincent** [spyder-ide/spyder#16822]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder using GPU whenever it lanuches

### What steps reproduce the problem?

1. Install any version 4 or 5 of Spyder
2. Run it

### What is the expected output? What do you see instead?
- expect computer is not hot. but it is heating a lot just by running spyder in idle due to GPU consumption
<img width="217" alt="image" src="https://user-images.githubusercontent.com/25037386/141682492-cccd3bad-bd37-4e6b-8c7f-335b4062d90a.png">
After stopping spyder
<img width="101" alt="image" src="https://user-images.githubusercontent.com/25037386/141682583-2299ab32-6077-4800-8b83-d7872447503c.png">

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
My suggestion is due to qtwebenginne process utilizes CPU which cause heating increases a lot. Please add an option to disable this feature.

Bests,

**Comment by steff456** [comment]
Hi @vantienvincent,

I understand your issue, but sadly we cannot disable QtWebEngine from Spyder because a lot of the plugins use this to work normally. What I think it may help your issue is that our next version will add the ability to turn off some plugins, so maybe you can turn off all the panes you don't actually use making Spyder to consume less resources. 

There's nothing much we can do more than this. Hope this helps and thanks for opening this issue!
