### ISSUE TITLE
Problem after updating spyder to 5.1.5 version

### ISSUE THREAD

**Issue by FandosA** [spyder-ide/spyder#16846]
### What steps will reproduce the problem?

After updating to spyder=5.1.5, spyder doesn't find the basic modules in anaconda such as numpy or matplotlib, but all those pakages are in the anaconda3 folder. What's happening? I just did the next:
 
conda remove spyder
conda remove python-language-server
conda update anaconda (This gave me an error)
conda install spyder=5.1.5
conda activate base
conda update --all

So spyder is updated, but it doesn't find any package, what's happening?

**Comment by dalthviz** [comment]
Hi @FandosA when running `conda update anaconda` what was the error you saw?. Also, are you using some config different from the defaults like a custom interpreter? and are you using your base environment for the installation or a different env for Spyder?

Without any other info there is not much we can do, sorry :/

**Comment by FandosA** [comment]
Hello @dalthviz thank you very much for answering. When I run `conda update anaconda` I get this:

> PackageNotInstalledError: Package is not installed in prefix.                                                                                  
> prefix: C:\Users\andre\anaconda3                                                                                                             
> package name: anaconda

But despite this error, I kept running the other commands I mentioned: `conda install spyder=5.1.5`, `conda activate base` and `conda update --all`, and I didn't get any other error. So now, when I open Spyder, it's updated but when I run a simple python file to plot some points with matplotlib, I get the next error:
> ModuleNotFoundError: No module named 'numpy'

It's like there is no any package, like if anaconda has been uninstalled and I had to install all packages by myself again. Is it clear now?

**Comment by ccordoba12** [comment]
@FandosA, you need to install `numpy` and the other packages you require again with

    conda install numpy matplotlib

They were probably removed when you ran `conda remove spyder` because conda auto-removes packages that were installed as dependencies of others (that's not related to Spyder, it's just the way conda works).

Let us know if that solves the problem for you.

**Comment by FandosA** [comment]
Yes, installing the packages by myself works. The thing is, in my other computer I did the same, but those packages were not removed, so I could run the same file without any problem. I just didn't understand what was happening, but it's ok, I'll install the packages needed by myself. Thank yo very much!

**Comment by ccordoba12** [comment]
> I just didn't understand what was happening

Well, sometimes conda is a mistery (not kidding, it's just hard to predict its outcomes).

> Thank you very much!

No problem and glad things are working for you again.
