### ISSUE TITLE
Closing multiple Spyder instances shows an error from the Editor

### ISSUE THREAD

**Issue by bambosd** [spyder-ide/spyder#16851]
### What steps will reproduce the problem?

closing editors when using multiple instance option
having 4 editors undock +1 dock. this happent when closing all the undock editors.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\djb\anaconda3\lib\site-packages\spyder\plugins\editor\plugin.py", line 2563, in current_editor_cursor_changed
    filename = code_editor.filename
AttributeError: 'NoneType' object has no attribute 'filename'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @bambosd thank you for the feedback! When you say multiple instance option you refer to having unchecked the preference `Use single instance` under `Preferences  > Application > Advanced settings`? Could it be possible for you to record a GIF or video to understand better how the issue is being trigger? Let us know!

**Comment by bambosd** [comment]
yes, i have unchecked the use single instance so i can run multiple editors.
when closing some of the extra editors (3-4) i got this error.

**Comment by dalthviz** [comment]
Checking with the multiple instance option I was able to launch multiple Spyder instances (I tried with 4) and then closing them without any error raising. Is there anything else that causes this error consistently for you @bambosd ? 

Any new info to reproduce this in our side is greatly appreciated, let us know.

**Comment by bambosd** [comment]
@dalthviz  Hello, i wouldn't been able to reproduce the error as of today.
it might be compination of multiple editors and multiple consoles. If happent again i will post you.

**Comment by dalthviz** [comment]
Closing due to lack of response. If the error happens again, please open a new issue with more info to reproduce the error and referencing this issue, thanks!
