### ISSUE TITLE
Restart Kernel Does Not Work

### ISSUE THREAD

**Issue by gkbit** [spyder-ide/spyder#16878]
### What steps will reproduce the problem?

When clicking on 'Restart Kernel', nothing happens. The current kernel keeps running as before.

**Comment by ccordoba12** [comment]
Hey @gkbit, thanks for reporting. I'm going to ask you to open a new issue with all the information requested by the issue template filled because that's what we need to know to properly help you.

You can get that info from the menu `Help > About Spyder`
