### ISSUE TITLE
contenido de archivos eliminados totalmente

### ISSUE THREAD

**Issue by Kamiipico24** [spyder-ide/spyder#16870]
### What steps will reproduce the problem?

I dont know, but in my archive .py all the archive is empty 

### Traceback
```python-traceback
  File "C:\Users\Karen Pico\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2035, in revert
    editorstack.revert()
  File "C:\Users\Karen Pico\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2112, in revert
    self.reload(index)
  File "C:\Users\Karen Pico\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2078, in reload
    txt, finfo.encoding = encoding.read(finfo.filename)
  File "C:\Users\Karen Pico\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 249, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Karen Pico\\Sin título0.py'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Hola @Kamiipico24, gracias por reportar tu error. Muchos de los errores en que el contenido de archivos desaparecía después de trabajar en Spyder fueron arreglados en Spyder 4, que salió en Diciembre del 2019, y tú estás usando la versión 3.3.6.

Si deseas actualizar a nuestra última versión (5.1.5), puedes descargarla desde esta página:

https://github.com/spyder-ide/spyder/releases

También puedes hacerlo a través de Anaconda, pero tal vez no sea posible (o te de muchos problemas) desde una versión tan antigua. En ese caso te recomendaría mejor desinstalar Anaconda y reinstalar la última versión, que también viene con Spyder 5.1.5, desde esta página:

https://www.anaconda.com/products/individual

Déjanos si eso soluciona tu problema.

**Comment by ccordoba12** [comment]
Voy a cerrar este issue porque no recibimos respuesta. Espero que al actualizar a nuestra última no vuelvas a tener este problema.

**Comment by Kamiipico24** [comment]
Disculpe mi respuesta tardia. Le agradezco mucho su atencion y ayuda.

Saludos.
________________________________

**Comment by ccordoba12** [comment]
No te preocupes, no hay problema.
