### ISSUE TITLE
Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x000002A7FA97EFC8>> 

### ISSUE THREAD

**Issue by powlook** [spyder-ide/spyder#16884]
### What steps will reproduce the problem?

I have 2 environments created in  anaconda, one runs tensorflow and one runs pytorch.
Both of these environments run OK in jupyter notebook.
However when I started Spyder from the cmd (Windows 10), with the environment activate (eg. conda activate pytorch), I am able to run execute the libraries in the environment.

However when I switched over to the tensorflow environment and when I launched Spyder from the cmd and when in Spyder app I execute "import tensorflow",
I get the following error message :
 opened dynamic library cudart64_101.dll
Error in callback <bound method AutoreloadMagics.post_execute_hook of <autoreload.AutoreloadMagics object at 0x000002A7FA97EFC8>> (for post_execute):

Note : CUDA is running OK in the tensorflow environment in jupyter notebook.

Please let me know what is the possible issues and how I can resolve it. I am not able to use this environment now due to this issue.

Regards,
PL

**Comment by steff456** [comment]
Hi @powlook,

Can you let me know how did you installed Spyder and tensorflow?

**Comment by powlook** [comment]
Hi Stephanie,

For this environment which was initiated quite some time ago, I install and
re-install tensorflow multiple times as I change the version number. I
tried to use conda to install.
The last update of tensorflow was through Anaconda Navigator. Similarly for
spyder I also installed through Anaconda Navigator.

Regards,
PowLook

**Comment by steff456** [comment]
Can you please try to create a new environment and install both tensorflow and conda with the conda-forge channel to see if the error persists?

```
conda create -n test-tf python=3.9 -c conda-forge
conda activate test-tf
conda install -c conda-forge spyder tensorflow
spyder
```

Let me know if Spyder opens and you have succesfully tensorflow in your environment

**Comment by powlook** [comment]
Hi Stephanie,

OK, will update you.

PL

**Comment by powlook** [comment]
Hi Stephanie,

Yes, I am able to launch Spyder  using the steps you prescribed.
However, I need one more advice from you:
I am not able to detect GPU: I have installed cudatoolkit 10.1.254 using
conda.
When I run the following scripts :
from tensorflow.python.client import device_lib
def get_available_devices():
    local_device_protos = device_lib.list_local_devices()
    return [x.name for x in local_device_protos]
print(get_available_devices())
['/device:CPU:0']
The spyder app is not able to detect GPU.

My other tensorflow environment can detect GPU also with
cudatoolkit 10.1.254
Any advice?

Regards,
PL

**Comment by powlook** [comment]
Hi Stephanie,

For the environment that you asked me to create which I can launch spyder
with tensorflow.
However it cannot detect GPU. For the same environment when I launch
jupyter notebook, it can detect GPU.


PL

**Comment by steff456** [comment]
How are you verifying the GPU inside of Spyder?

**Comment by powlook** [comment]
Hi Stephanie,

Below is a screenshot of the scripts I ran:
[image: image.png]

**Comment by steff456** [comment]
Hi @powlook,

In order for me to see the image I need you to upload it directly via Github, the email attachments are now shown here :(

**Comment by powlook** [comment]
Hi Stephanie,

I managed to resolve the issue.
The problem lies in the Nvidia CUDNN files that we need to add to the
CudaToolkit. Since it is tensorflow 2.6 that was installed they are looking
for the following files
in the toolkit : cudart64_110.dll .... basically looking for toolkit 11.x
files while I only have toolkit  10.x files since my the other environment
uses TF2.1. So I add both the cudNN 11.x files into the toolkit and it is
now able to run. Making sure that cuda runs with tf is a pretty complicated
affair.

Thanks so much for your help.

Regards,
PL

**Comment by steff456** [comment]
I'm really glad that you could fix this error! Thanks for opening the issue and being so responsive.
