### ISSUE TITLE
cannot debug FastAPI

### ISSUE THREAD

**Issue by mikhailo** [spyder-ide/spyder#16894]
### What steps will reproduce the problem?

* Spyder version: 5.1.5 None
* Python version: 3.9.6 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

When trying to call my code containing FastAPI

the execution of

```python
if name == "main":
    uvicorn.run(app, host="0.0.0.0", port=8000)
```

Fails and raises:

    RuntimeError: asyncio.run() cannot be called from a running event loop

Minimum code to be executed: 

```python
from fastapi import FastAPI
import uvicorn

app = FastAPI()


@app.get("/")
async def root():
    return {"message": "Hello World"}


if __name__ == '__main__':
    uvicorn.run(app, port=8080, host='0.0.0.0')
```

Workaround is to execute those lines first:

```python
import nest_asyncio;nest_asyncio.apply()
```

but is solves the problem only partially

This problem does not exit on VSCode nor on PyCharm. Please, solve

**Comment by ccordoba12** [comment]
@mikhailo, thanks for reopening this issue. You said:

> Workaround is to execute those lines first

This is the only possible workaround at the moment because there's already an asyncio event loop running in our consoles. That's how the Jupyter architecture to run code works these days (which we also use), so there's nothing we can do about it.

> but is solves the problem only partially

What do you mean by this?

**Comment by mikhailo** [comment]
> What do you mean by this?
Part of the output is lost. For instance in my project the code makes a C++ call, which generates output normally visible when one makes a regular execution from the command line. 

>This is the only possible workaround
I had to really search in the internet to find this advice as it is quite hidden and not related to FastAPI. I personally know a couple of colleagues who switched from Matlab and initially started to use Spyder. But specifically because of this bug, they switched to VSCode. To avoid loosing potential users in future, why don't you make those lines a part of the permanent solution so that people spent time on development and not on debugging the IDE?

I think the least thing to do is to create Stackoverflow ticket for this problem such that Google directly propose the answer

**Comment by mikhailo** [comment]
> @mikhailo, thanks for reopening this issue. You said:
> 
> > Workaround is to execute those lines first
> 
> This is the only possible workaround at the moment because there's already an asyncio event loop running in our consoles. That's how the Jupyter architecture to run code works these days (which we also use), so there's nothing we can do about it.
> 
> > but is solves the problem only partially
> 
> What do you mean by this?

I have created a Stackoverflow ticket so that others could easily find an answer next time: 
https://stackoverflow.com/questions/70118841/cannot-execute-fastapi-client-code-in-spyder
Could you, please, answer it?

**Comment by ccordoba12** [comment]
> Could you, please, answer it?

No problem, I just answered it.

Since I'd say your problem is solved, I'm going to close this issue.
