### ISSUE TITLE
Python(x,y) + PySide can't run gui file

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1689]
_From [pangeran...@gmail.com](https://code.google.com/u/100279421595817707169/) on 2014-01-08T23:05:47Z_

What steps will reproduce the problem?

 run a file for gui. What is the expected output? What do you see instead? gui shown up but got an error. What version of the product are you using? On what operating system? Windows 8. PySide-1.1.2.win32-py2.7. PySide-1.1.2.win32-py2.7. 

Please provide any additional information below

. First, install Python(x,y)-2.7.5.0.exe. (for all user and choose Recommended).
Run a file in Spyder, got an ImportError : No module named PySide.QtGui.
So I install PySide-1.1.2.win32-py2.7.exe. But still got an error, ImportError: DLL load failed: The specified procedure could not be found.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1689_

**Comment by ccordoba12** [comment]
We don't support PySide anymore, so closing.
