### ISSUE TITLE
Kite not responding in Spyder and error while unchecking/checking Kite provider checkbox preference

### ISSUE THREAD

**Issue by rodosingh** [spyder-ide/spyder#16900]
### What steps will reproduce the problem?

Please help to sole this issue. Kite plugin is there but code completion is not showing.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/preferences/widgets/configdialog.py", line 136, in button_clicked
    configpage.apply_changes()
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 110, in apply_changes
    self.apply_callback()
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 142, in <lambda>
    self._apply_settings_tabs(self.changed_options))
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 170, in _apply_settings_tabs
    self.apply_settings(options)
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/api/preferences.py", line 104, in wrapper
    func(opts)
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/api/plugins/new_api.py", line 528, in apply_conf
    self.after_configuration_update(list(options_set))
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/completion/plugin.py", line 353, in after_configuration_update
    self.register_statusbar_widget(provider_name)
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/completion/plugin.py", line 451, in register_statusbar_widget
    self.statusbar.add_status_widget(currrent_widget)
  File "/home/rodo/anaconda3/envs/rodo_main/lib/python3.8/site-packages/spyder/plugins/statusbar/plugin.py", line 109, in add_status_widget
    raise SpyderAPIError(f'Status widget `{id_}` already added!')
spyder.api.exceptions.SpyderAPIError: Status widget `kite_status` already added!
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.4.0-90-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.1 (NOK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.6.1 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  19.0.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @rodosingh thank you for the feedback. Do you have Kite installed? The thing is their service is unavailable right now so there is not much we can do about that: https://www.kite.com/kite-is-temporarily-unavailable/?source=download

Also, how is the error being trigger for you? Any new info in order to reproduce this is greatly appreciated

**Comment by rodosingh** [comment]
Yeah, so the kite is installed and enabled for Visual Studio Code. But again in the kite app, I can't see that it is enabled for Spyder and there it was instructed to do it manually, specifically by going to preferences and enable code hinting by Spyder. Also I have tried to enable code hinting and suggestions by kite in Preferences section which is in parentheses and it was beforehand mentioned that it's not available. And after checking the required boxes, when I clicked on enable the box or window popped up to put your issue.
And now here I'm.

**Comment by dalthviz** [comment]
I was able to reproduce this @rodosingh (the issue related to the error message).

Regarding Kite completions, could you try to restart the Kite copilot and under settings click on `Redo setup`?

Under the status bar for kite you should see `ready`

**Comment by dalthviz** [comment]
Just in case, related issues: https://github.com/spyder-ide/spyder/issues/16837 https://github.com/spyder-ide/spyder/issues/16458

**Comment by rodosingh** [comment]
Will do and try to update you soon.

**Comment by rodosingh** [comment]
![IMG_20211127_192821.jpg](https://user-images.githubusercontent.com/47246458/143684773-42eebc98-663f-4748-beea-e461586e43f3.jpg)

Above Image is in Kite window. Showing not available.
![IMG_20211127_192858.jpg](https://user-images.githubusercontent.com/47246458/143684801-f17275d8-bc19-4803-85fe-8d636a549771.jpg)

Here it's showing Notify me when Kite can provide missing completions (but is unavailable). And I have done the `Redo Setup` but nothing has happened.

**Comment by rodosingh** [comment]
Could it be that the `jedi` is not installed that's why the autocompletion is not available?

**Comment by rodosingh** [comment]
1. Hey @dalthviz I've solved the error. The problem is due to missing package of `jedi>=0.17.2, <0.19.0`.
2. Just uninstalled the old `jedi` to run the new one.
3. Now working fine.

**Comment by dalthviz** [comment]
Thanks @rodosingh to let us know how you manage to fix the issue with the completions :+1:

**Comment by rodosingh** [comment]
Since my issue was resolved, I'm closing this thread.
