### ISSUE TITLE
Spyder is not opening

### ISSUE THREAD

**Issue by FevziDeniz** [spyder-ide/spyder#16918]
### What steps will reproduce the problem?

Spyder is not lounching when I have python installed in my computer.

**Comment by steff456** [comment]
Hi @FevziDeniz,

How did you installed Spyder and what operating system do you use?

**Comment by sirhc78** [comment]
Same here.
I installed with windows installer 5.1.5 few months ago.
This morning, I installed 5.2 with same method.
Spyder was starting then 1 sec after crashed.
I have done a windows recovery. 5.1.5 is not working anymore, like loading screen not even showing up.

I am back now with 5.0.5 from my previous installation with conda/pip.
I hope I will be able to work on today.

**Comment by rhkarls** [comment]
@sirhc78  Are you using a custom interpreter with the installed Spyder 5.2.0? If so, perhaps you have not updated spyder-kernels to 2.2.0 in that connected environment? There is a bug in 5.2.0 that causes it to crash if not having a compatible spyder-kernels version. That has been fixed and will be included in the next release (https://github.com/spyder-ide/spyder/pull/16895).

**Comment by sirhc78** [comment]
> @sirhc78 Are you using a custom interpreter with the installed Spyder 5.2.0? If so, perhaps you have not updated spyder-kernels to 2.2.0 in that connected environment? There is a bug in 5.2.0 that causes it to crash if not having a compatible spyder-kernels version. That has been fixed and will be included in the next release (#16895).

Yes I am using custom interpreter.
No I usually update spyder-kernels after I launch Spyder. Thank you, it is probably my problem.
I now realize that other bug reports was mentioning Kernel but I thought it was core spyder bug and not well known spyder-kernels to be upgraded.
I will wait next release then.
thany ou

**Comment by steff456** [comment]
Hi @rhkarls and @sirhc78, I'm glad that you could fix this issue! I'm going to leave it open for a little while just in case more people come with the same problem. 

Thanks!

**Comment by victor-sm** [comment]
I had the same problem. Running `pip install spyder-kernels==2.0.0` in terminal while in my activated environment fixed the issue.

However, I got no error message and even starting Spyder in debug mode doesn't show anything. Without this open issue I wouldn't have solved the problem. The issue reporter tool opens for a split second then disappears. Is this a bug?

https://user-images.githubusercontent.com/7871132/144312294-aa5f64fc-6123-4aea-b60b-e8aab676365e.mp4

**Comment by FevziDeniz** [comment]
> 

I am using Windows 10.And I installed it from their own website without using anaconda. @victor-sm shared a video. Same thing happens to me when I change the interpreter with my python.exe

**Comment by rhkarls** [comment]
@FevziDeniz Have you installed `spyder-kernels==2.2.0` in the environment you are connecting to Spyder 5.2.0? Usually, if not having the compatible version of spyder-kernels, Spyder would start and then give an error in the console with instructions to install spyder-kernels. Due to the bug in 5.2.0 Spyder crashes instead making it hard to understand why it happens (what you show in the video @victor-sm). The Spyder team has fixed thus bug and will be included in the next release.

**Comment by FevziDeniz** [comment]
I download a kernel but I do not check its version. I need to check it.Thanks for your help

**Comment by FevziDeniz** [comment]
@rhkarls thank you. That woks fine now.

**Comment by ccordoba12** [comment]
I'm going to reopen this so others can find it until we release our next version (5.2.1) in a few days.

**Comment by ccordoba12** [comment]
Closing because 5.2.1 was released almost a week ago.
