### ISSUE TITLE
Debugger message bug gets printed in the IPython Console

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#16927]
## Problem Description

After starting an IPython Console with the standalon installer on Windows sometimes you get a message at the top regarding the debugger.

Checking seems like this was reported at https://github.com/spyder-ide/spyder/issues/16896#issuecomment-979837635 but I only notice it until now. Not totally sure if this is some sort of warning that needs to be handled/removed or something else @ccordoba12 @impact27 ?

### Paste Traceback/Error Below (if applicable)

```python-traceback

It seems the debugger cannot resolve D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ntpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193

```

## Versions
* Spyder version: 5.2.0 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by impact27** [comment]
In PR https://github.com/spyder-ide/spyder/pull/14025 there was an issue with: 


This version of python seems to be incorrectly compiled
  (internal generated filenames are not absolute).
  This may make the debugger miss breakpoints.
  Related bug: http://bugs.python.org/issue1666807


(Maybe related, we solved that one by skipping it)

**Comment by impact27** [comment]
Do you see any adverse effect while debugging?

**Comment by dalthviz** [comment]
I checked putting some breakpoints in a simple script and seems like the breakpoints work. 

Will check then the logic to skip it. Thanks for the info @impact27 :+1:

**Comment by ccordoba12** [comment]
> Not totally sure if this is some sort of warning that needs to be handled/removed or something else @ccordoba12 @impact27 ?

This message (like the one referenced above by @impact27) is generated by `Pydevd`, a vendored dependency of `debugpy`, which in turn is a dependency of `IPykernel` 6+. We're not using it in our debugger, but it was introduced by the Jupyter team to implement the [Debugger Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/), which is like the LSP but for debuggers.

**Comment by gaotxg** [comment]
This issue still can be reproduced in 5.2.1 Windows standalone installer.
Tested in Windows 10 21H2.

**Comment by dalthviz** [comment]
Hi @gaotxg a new fix was done at https://github.com/spyder-ide/spyder/pull/17050 (will be available with the next release)
