### ISSUE TITLE
Missing mandatory packages does not raise error

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#16935]
### What steps will reproduce the problem?

1. Uninstall a mandatory package, e.g. `jellyfish`
2. Launch Spyder, e.g. via bootstrap
3. No error is raised
4. Dependency widget shows no version installed, but still marks as OK

## Versions

* Spyder version: 5.3.0.dev0 74973f6ff
* Python version: 3.9.7
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.30.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  None (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.4.0.dev0 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.4.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.3.0.dev0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.21.4 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by mrclary** [comment]
In `spyder.utils.programs` the three relevant methods are `is_module_installed`, `get_module_version`, and `get_package_version`. `spyder.dependencies.Dependency.check` calls `is_module_installed` using only the module name.

It appears that `is_module_installed` will never return False for a module that is not installed, when no interpreter is provided.

At the risk of being presumptuous, should we consider reviewing exactly what we expect these functions to do and which, if any, of the flow control and corner cases are obsolete, in order to simplify the logic stream?

**Comment by ccordoba12** [comment]
> It appears that is_module_installed will never return False for a module that is not installed, when no interpreter is provided.

That's (sadly) correct. That regression was introduced in Spyder 5.1.0, due to us not having tests to detect that.

> At the risk of being presumptuous, should we consider reviewing exactly what we expect these functions to do and which, if any, of the flow control and corner cases are obsolete, in order to simplify the logic stream?

I think the logic is working mostly fine. The problem is related to some changes introduced to deal with getting the version of `python-lsp-black`, which is kind of unusual because its module name (`pylsp_black`) is different from its Setuptools distribution one (`python_lsp_black`), but we are assuming both are the same. The last one is used by us to get a package's version when we can't detect it with `modulename.__version__` or `modulename.VERSION`.

I already have a PR for this and I'm planning to ask for your review so you can check that things are working fine with it.
