### ISSUE TITLE
spyder 5.0.5 debuger not working 

### ISSUE THREAD

**Issue by SarahComo** [spyder-ide/spyder#16949]
### What steps will reproduce the problem?

Hi, I'm facing a problem with the spyder debuger.
When I set a breakpoint and then launch the debug mode or just directly launch the debug mode, the console seems to stuck and i can not exucute any function from the debug mode (step, step into, continue...)

I'm running python 3.6.8, spyder 5.0.5, spyder kernel 2.0.5 and IPython 7.16.1.

Could anyone help ?

**Comment by ccordoba12** [comment]
Hey @SarahComo, thanks for reporting. What is your qtconsole version?

**Comment by SarahComo** [comment]
Hey @ccordoba12. I am using qtconsole 5.2.0 version. Thanks for helping.

**Comment by ccordoba12** [comment]
Ok, that's the problem because we made some changes in qtconsole 5.2.0 that are incompatible with previous Spyder versions.

So, please downgrade to qtconsole 5.1.1 and try again. That should fix your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by jruizguillen** [comment]
This solved the issue for me. Thnxs!
