### ISSUE TITLE
Clearing Find textbox in Editor does not trigger update to clear highlighted matches until Editor text changed

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#16948]
## Problem Description

On Spyder 5.x, entirely clearing the find box (either by deleting the last character, or having all of them selected and pressing delete) does not clear the highlights, even when clicking around in the Editor or other panes. Modifying the file text in the Editor is required to trigger a repaint and clear them.

@steff456 first discovered this behavior on PR #16864 and created a helpful GIF showing it:

![find](https://user-images.githubusercontent.com/20992645/144141645-a93f8609-3894-45e7-96b3-fb3988d56b67.gif)

_Originally posted by @steff456 in https://github.com/spyder-ide/spyder/pull/16864#pullrequestreview-819633387_

### What steps reproduce the problem?

1. Enter some text in the Find text box in the Editor's Find and Replace dialog that matches something in the current file
2. Once matches appear, delete the text, either one by one or all at once
3. Click back to the Editor and note that the matches (often the last letter of the deleted word) stay highlighted, until a change is made to the file.

### What is the expected output? What do you see instead?

We would expect that that an update is triggered when the last character is deleted, like with the others, clearing any matches. However, instead, the matches are highlighted indefinitely until the file is edited or the Find & Replace dialog is closed.

## Versions

* Spyder version: 5.1.5 and `5.x`
* Python version: 3.9.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 8.1 x64, macOS

**Comment by impact27** [comment]
Should we do a search with every character change? What I mean is that unless you press « find » I wouldn’t expect the state to really change

**Comment by CAM-Gerlach** [comment]
This seems somewhat orthogonal to the issue at hand, but that is how Spyder and most other applications with a similar inline find (web browsers, editors, etc) have operated for as long as I can remember, allowing you to easily drill down to just the desired results without having to type too much, and with an idle delay that balances performance and responsiveness (that perhaps can be tweaked). I certainly regard it as quite useful.
