### ISSUE TITLE
Add "psutil" to the list of optional dependancies

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1695]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-01-13T05:25:15Z_

Spyder Version:  2.3.0dev (3459+: rc334981bcef6 )
Python Version:  3.3.3
Qt Version    :  4.8.5, PySide 1.2.1 on Linux
IPython >=0.13  :  1.1.0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.6.0:  0.7.3 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK) 

What steps will reproduce the problem?

 1. 2. 3. What is the expected output? What do you see instead? Psutil is used for displaying CPU and memory usage, but this is indicated only in the tooltips in the preference window. 

Please provide any additional information below

. If I understand correctly, the dependenci should not be present on Windows.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1695_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-01-13T09:19:27Z_

Good point.

**Status:** Accepted  
  **Labels:** MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-04T14:49:14Z_

This was fixed by revision 688df661321c

**Status:** Fixed

**Comment by nowox** [comment]
Is it optional yet? I tried to install Spyder from the latest version on GitHub and it still want to install psutil: 

```
install_requires = [
    'rope_py3k' if PY3 else 'rope>=0.9.4',
    'jedi>=0.9.0',
    'pyflakes',
    'pygments>=2.0',
    'qtconsole>=4.2.0',
    'nbconvert',
    'sphinx',
    'pycodestyle',
    'pylint',
    'psutil',
    'qtawesome>=0.4.1',
    'qtpy>=1.1.0',
    'pickleshare',
    'pyzmq',
    'chardet>=2.0.0',
    'numpydoc',
]   
```

**Comment by ccordoba12** [comment]
Not, it's not optional anymore.
