### ISSUE TITLE
with an external monitor the spyder app is scaled up bigger

### ISSUE THREAD

**Issue by nsharan2000** [spyder-ide/spyder#16952]
### What steps will reproduce the problem?

if you connect an external monitor and open spyder app
the app will be scaled up and all icons will look big.
even if i restart the spyder app the issue is persisting
however if I disconnect the monitor before launching the app and connect the monitor after launching the app, it will work properly without scaling up.

**Comment by ccordoba12** [comment]
Hey @nsharan2000, thanks for reporting. Please post a screenshot of how Spyder looks for you to better understand your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
