### ISSUE TITLE
Can't Display GUI

### ISSUE THREAD

**Issue by buunghi** [spyder-ide/spyder#16969]
### What steps will reproduce the problem?

Hi there, I have an issue is that when I run the code on spyder, I'm expecting it to display a gui window, even though the Python app is running,nothing happens. I've tried so many times but it doesnt work. Please help!!!

**Comment by steff456** [comment]
Hi @buunghi,

I don't understand your issue, are you creating a gui window in your code and it is not appearing in Spyder? Have you tried your code on a python interpreter and see if the gui window is created? 

Please post a screenshot, or provide me an example to try to reproduce this in my end. 

Thanks for reporting!

**Comment by ccordoba12** [comment]
Closing due to lack of response.
