### ISSUE TITLE
Opening Preferences results in Error on Spyder 5.2.0

### ISSUE THREAD

**Issue by MuellerSeb** [spyder-ide/spyder#16966]
### What steps will reproduce the problem?

Click on Tools -> Preferences will pop up an error report.

I just reinstalled spyder by:

    pip install -I spyder-terminal spyder
    spyder --reset

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/muellese/.local/lib/python3.8/site-packages/spyder/plugins/preferences/plugin.py", line 276, in <lambda>
    lambda: self.open_dialog(main.prefs_dialog_size))
  File "/home/muellese/.local/lib/python3.8/site-packages/spyder/plugins/preferences/plugin.py", line 256, in open_dialog
    container.create_dialog(
  File "/home/muellese/.local/lib/python3.8/site-packages/spyder/plugins/preferences/widgets/container.py", line 62, in create_dialog
    page.initialize()
  File "/home/muellese/.local/lib/python3.8/site-packages/spyder/plugins/preferences/api.py", line 83, in initialize
    self.setup_page()
  File "/home/muellese/.local/lib/python3.8/site-packages/spyder/api/plugin_registration/_confpage.py", line 71, in setup_page
    plugin_loc_name = PluginClass.get_name()
TypeError: get_name() missing 1 required positional argument: 'self'
```

## Versions

* Spyder version: 5.2.0 
* Python version: 3.8.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.11.0-41-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.6.0                      :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.8.9 (OK)
jsonschema >=3.2.0                   :  4.2.1 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.3.0 (OK)
numpydoc >=0.6.0                     :  1.1.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.8.0 (OK)
pygments >=2.0                       :  2.10.0 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0                 :  1.3.2 (OK)
pylsp_black >=1.0.0                  :  None (OK)
qdarkstyle =3.0.2                    :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.1 (OK)
qtpy >=1.5.0                         :  1.11.3 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  59.5.0 (OK)
sphinx >=0.6.6                       :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0        :  2.2.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
xdg >=0.26                           :  0.27 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.14 (OK)
matplotlib >=2.0.0                   :  3.5.0 (OK)
numpy >=1.7                          :  1.21.4 (OK)
pandas >=1.1.1                       :  1.3.4 (OK)
scipy >=0.17.0                       :  1.7.2 (OK)
sympy >=0.7.3                        :  None (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.1.0 :  1.1.0 (OK)
```

**Comment by MuellerSeb** [comment]
Maybe this comes from `spyder-terminal`?

**Comment by steff456** [comment]
Hi @MuellerSeb,

Yes, this is an error that comes from spyder-terminal that I'm currently working on to do a future release that will be compatible with Spyder>5.2.0. For now please uninstall spyder-terminal, or downgrade to Spyder 5.1.5.

I'm closing this issue, but please follow the spyder-terminal repo to have the update as soon as we finish the update!

**Comment by ethanbb** [comment]
Well, I'm not sure this is the whole story. The error happens in `api/plugin_registration/_confpage.py` when trying to call `PluginClass.get_name()`. This call fails because `get_name` is not a staticmethod or classmethod - it expects to be called on an instance or with an instance as 1st argument.

The spyder-terminal code follows this example, which has `get_name` as an instance method: https://github.com/spyder-ide/plugin-examples/blob/master/spyder-custom-layout/spyder_custom_layout/spyder/plugin.py. The call in `_confpage.py` was added 2 months ago according to blame. So this looks like either a bug that will affect all plugins or a change in the API that needs to be documented.

**Comment by ccordoba12** [comment]
@ethanbb, we introduced a breaking change in our API in 5.2.0 and (unfortunately) we haven't had time to update our examples in the `plugin-examples` repo.

**Comment by ethanbb** [comment]
@ccordoba12 OK, I fixed it locally by turning get_name into a staticmethod - is this the intended fix or are there deeper incompatibilities?

**Comment by ccordoba12** [comment]
> is this the intended fix

Yes, that's what you need to do to fix this.

> or are there deeper incompatibilities?

No, there aren't. That's the only required thing to make your plugins compatible with 5.2.0+
