### ISSUE TITLE
code file version save

### ISSUE THREAD

**Issue by FarhangAmaji** [spyder-ide/spyder#16965]
does spyder support code file version save? 
or is it possible for future they add automatic save version? for example by pressing some combination like ctrl+s, maybe ctrl+ shift + s, it automatically saves a version of code file in same directory with time and some version name?

**Comment by steff456** [comment]
Hi @FarhangAmaji,

Thanks for the request, I would like to know why would you need to have this functionality? Normally git helps a lot with versioning, but I'm curious to know why will you need to save different versions of the same file in the same directory

**Comment by ccordoba12** [comment]
Closing due to lack of response.
