### ISSUE TITLE
AboutToQuit gets eaten with Spyder 5.1.5 and Python 3.9

### ISSUE THREAD

**Issue by torge2** [spyder-ide/spyder#16963]
## Problem Description
AboutToQuit not executed with Spyder 5.15, Python 3.9.8, Qt 5.15.1, PyQt5 5.15.1 (complete installation of Winpython64-3.9.8.0post1.exe). However, working when running from command prompt. 
AboutToQuit executed properly with Spyder 5.15, Python 3.8.9, Qt 5.12.10, PyQt5 5.12.3 (complete installation of Winpython64-3.8.9.exe).

### What steps reproduce the problem?
Run the simple script below and close the window. Observe the terminal. In the correct case you will get "stopping...", in the incorrect case you won' t get "stopping...".

```from PyQt5.QtWidgets import QApplication, QLabel

def stopApplication():
    print ("stopping...")

app = QApplication([])
app.aboutToQuit.connect(stopApplication)
label = QLabel("Hello World!")
label.show()
app.exec_()
```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.8
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

**Comment by steff456** [comment]
Hi @torge2,

I'm unable to reproduce your issue, it is running with the correct case as you can see in the screenshot below,

![image](https://user-images.githubusercontent.com/20992645/144893977-3b428241-222d-4721-b61d-792e24ea6738.png)

Please try updating Spyder to 5.2.0, and let me know if the error persists in this version.

**Comment by torge2** [comment]
Updated to Spyder 5.2.0, Python 3.9.8 64 bit, Qt 5.12.10, PyQt5 5.12.3, Windows 10. Problem remains. 
Still no problem when executing from CMD line.
It may have something to do with the spyder settings: IPython console-->Graphics-->Graphics backend.
I normally change the graphics backend from 'Inline'(Default) to 'Automatic' since I don' t want matplotlib graphs to be displayed in the console window. 
The script it is working with 'Inline', but not with 'Automatic' or 'Qt5' with thes settings.

**Comment by impact27** [comment]
Well that makes sense because the app is then not quitting. The graphic backend uses a QApplication to work so the QApplication will not close.
