### ISSUE TITLE
spyder has stopped working

### ISSUE THREAD

**Issue by Smruti06** [spyder-ide/spyder#16978]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @Smruti06 could you provide us more info regarding your setup (OS, Python version, Spyder version, dependencies, etc)? As well as the way the error triggered for you?

Without more information there is not much we can do sorry :/

**Comment by dalthviz** [comment]
Closing due to lack of response
