### ISSUE TITLE
Spyder closes after launching

### ISSUE THREAD

**Issue by deMalmazet** [spyder-ide/spyder#16989]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just updated to Spyder 5.2.0 with the standalone installer. When I launch Spyder, an issue reporter window appears and the application closes immediately, so I can't see what the issue is. It was working well with the previous version, but now the same problem appears after I downgrade to the previous version. The only way I can use Spyder now is with conda

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.2.0
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi  @deMalmazet thank you for the feedback. Are you using by any chance the interpreter preference? Maybe this is related with #16896

Any other info that helps us reproduce this is greatly appreciated. Let us know!

**Comment by deMalmazet** [comment]
Hi @dalthviz. Thank you for your quick reply. it was indeed related to #16896. I installed spyder-kernels=2.2.0 using pip and it solved the issue.
Sorry, I didn't find this issue when I google for help.

**Comment by dalthviz** [comment]
Glad is working now @deMalmazet :+1:

**Comment by ElFenitz** [comment]
> Hi @dalthviz. Thank you for your quick reply. it was indeed related to #16896. I installed spyder-kernels=2.2.0 using pip and it solved the issue. Sorry, I didn't find this issue when I google for help.

I tried to do the same but it gives me this error:
 Error parsing requirements for pyqt5: [Errno 2] No such file or directory: 'c:\\users\\user\\anaconda3\\lib\\site-packages\\PyQt5-5.15.7.dist-info\\METADATA'
 
 Any fix?

**Comment by ElFenitz** [comment]
> Hi @ElFenitz that seems like an error in your PyQt5 installation. Seems like you are using your base anaconda environment to use Spyder. I would suggest to try to reinstall `pyqt` also be sure you are not mixin pip and conda packages or conda channels on your base env (it should be using conda packages from the default anaconda channel only).

It was indeed, I mixed base environment with a yolo env, deleted all files and reinstalled in separate ones, now its all working fine. Thank you.

**Comment by GaoWeiCHN** [comment]
@ccordoba12 Thanks!  I ran the command `spyder --debug-info verbose --debug-output file` from #10993, and it worked.
