### ISSUE TITLE
Inline Graphic Backend Not Working

### ISSUE THREAD

**Issue by muriloasouza** [spyder-ide/spyder#16998]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The Inline Graphic Backend isn't ploting my graph in the `Plots` tab. I have tried with Automatic, and it works.

### What steps reproduce the problem?

1.  I got a `x` input numpy array with size `(42372, 1034)` and y output numpy array with size `(42372,)`:
2. The following code reproduces the problem:

```
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
cmap_data = plt.cm.Paired
cmap_cv = plt.cm.coolwarm


def plot_cv_indices(cv, x, y, ax, n_splits, lw=10):
    """Create a sample plot for indices of a cross-validation object."""

    # Generate the training/testing visualizations for each CV split
    for ii, (tr, tt) in enumerate(cv.split(X=x, y=y)):
        # Fill in indices with the training/test groups
        indices = np.array([np.nan] * len(x))
        indices[tt] = 1
        indices[tr] = 0

        # Visualize the results
        ax.scatter(
            range(len(indices)),
            [ii + 0.5] * len(indices),
            c=indices,
            marker="_",
            lw=lw,
            cmap=cmap_cv,
            vmin=-0.2,
            vmax=1.2,
        )

    # Plot the data classes and groups at the end
    ax.scatter(
        range(len(x)), [ii + 1.5] * len(x), c=y, marker="_", lw=lw, cmap=cmap_data
    )


    # Formatting
    yticklabels = list(range(n_splits)) + ["class"]
    ax.set(
        yticks=np.arange(n_splits + 1) + 0.5,
        yticklabels=yticklabels,
        xlabel="Sample index",
        ylabel="CV iteration",
        ylim=[n_splits + 1.2, -0.2],
        xlim=[0, 42372],
    )
    ax.set_title("{}".format(type(cv).__name__), fontsize=15)
    return ax

n_splits = 4
tscv = TimeSeriesSplit(n_splits = n_splits, max_train_size = 9593, test_size = 1000)
fig, ax = plt.subplots()
plot_cv_indices(tscv, x, y, ax, n_splits)
```

### What is the expected output? What do you see instead?

Expected output (from Automatic Backend):

![Figure_1](https://user-images.githubusercontent.com/40600889/145673454-0b0118c3-ab48-453b-b26c-2667350395d7.png)

What i see (With Inline Backend in the `Plots` tab):

![Capturar1](https://user-images.githubusercontent.com/40600889/145673478-d07e353c-2d64-4c2a-852b-fafacd22af88.JPG)

## Versions

* Spyder version: 5.2.0
* Python version: 3.8.0
* Qt version: 5.2.1
* PyQt version: 1.11.3
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  4.2.1 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.21.4 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (OK)

```

**Comment by steff456** [comment]
Hi @muriloasouza,

Thanks for giving me a complete case of your issue, when I'm testing this on my end I find two things:

1. With the options in `Preferences > IPython Console > Graphics > Backend` in `inline`, your code outputs me both the plot in the console and in the plots pane,

![image](https://user-images.githubusercontent.com/20992645/145865462-1d6bb830-5374-4efb-bebf-7bf1b035ddbe.png)

Please note that I have the option in the hamburguer menu of the plots pane entitled `Mute inline plotting` unchecked.

2. When I change the option to `automatic`, your code outputs me a new window that has the plot, and it doesn't show anything in the plots pane,

![image](https://user-images.githubusercontent.com/20992645/145865757-04629c3e-440c-43e5-8f36-7f172857a766.png)

Please let me know if this helps with your issue, or if you are using another combination of the settings for me to try it out as well.

**Comment by muriloasouza** [comment]
Hey @steff456 ,

Unchecking `mute inline plotting` solved. Thank you for your help!
