### ISSUE TITLE
Deprecation warnings launching Spyder Ubuntu 20.04

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#16992]
## Problem Description

When launching Spyder from Ubuntu 20.04 in WSLg (Windows System for Linux w/GUI support) messages regarding some python resources appear, saying 0.23ubuntu1 and 0.1.36ubuntu1 are invalid versions and will not be supported in the future

### What steps reproduce the problem?

1. Build Ubuntu 20.04 in Windows w/GUI support
2. Install Python38
3. Install Spyder as pip install spyder==5.2.0
4. Run  spyder from Linux

```
eafpres@LAPTOP-JSLJ8BRD:~$ spyder
/home/eafpres/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/eafpres/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Segmentation fault
```

Note that Spyder runs fine and I have seen no issues there

### What is the expected output? What do you see instead?

No warnings

### Paste Traceback/Error Below (if applicable)

```python-traceback

see above

```

## Versions

* Spyder version: 5.2.0 None
* Python version: 3.8.10 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.10.60.1-microsoft-standard-WSL2

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.1;<1.4.0          :  1.3.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.1 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.4.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.0 (OK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @eafpres thank you for the feedback! Checking a little bit my guess is that these warnings are related to the use of  `pkg_resource.parse_version` when validating the dependencies for Spyder but I'm not totally sure. Maybe if we move from `pkg_resource.parse_version` to `packaging.version.parse` when doing the validation we could prevent them.

What do you think @ccordoba12 ?

**Comment by eafpres** [comment]
FYI, I have found if I run the same code from the command line in Ubuntu, eg: python3 my_code.py I get the same warnings, if that helps you to isolate the source--it is not specific to Spyder

**Comment by dalthviz** [comment]
@eafpres after thinking about this could you try to install spyder under an environment? At the end, as you say, I think this is not specific to Spyder so I'm not totally sure if we can do something in our side, sorry :/

**Comment by dalthviz** [comment]
Closing since this seems not related directly with Spyder
