### ISSUE TITLE
Some SVG images have unnecessary executable permissions

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#16995]
The current master branch (as at commit 9fbbcfa01a128faf7df91d327bddb2841dd0a554) has lots of SVG files in `spyder/images/light` and `spyder/images/dark` with permissions 755 rather than 644.  Fixing this is easy: `chmod a-x spyder/images/light/*.svg spyder/images/dark/*.svg` and then committing the changes.  I'm happy to make a pull request for this if you would like.

**Comment by ccordoba12** [comment]
> I'm happy to make a pull request for this if you would like.

Yes! Thanks a lot for your help with that @juliangilbey!

Please take into account to do your PR against our `5.x` branch and not `master`, so we can include it in one of our future versions in the Spyder 5 series.
