### ISSUE TITLE
Unicode support issues

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#17007]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Paste in the editor
```
𨭎 = 10
𨭎𨭎𨭎𨭎 = 100000000
a = "𨭎"
```
![image](https://user-images.githubusercontent.com/6740194/145827891-5ca638ba-f450-423d-90c7-264b7b9c1587.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @impact27!

On my end I do see the chinese character,

![image](https://user-images.githubusercontent.com/20992645/145866473-34ca0e8c-5bdc-4f52-9091-1e406fa52bb8.png)


I'm not sure if this is a Windows/Linux problem.
