### ISSUE TITLE
Kernel process lingers after closing tab when running different interpreter and Qt5 backend

### ISSUE THREAD

**Issue by NicoHendrickx** [spyder-ide/spyder#17011]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When closing the console using the cross on the tab (ctrl-dot often does not work), the python process is not killed, but lingers around, until Spyder gets restarted. This issue only occurs when you use the Qt5 graphics backend **and** choose a different interpreter from the default Spyder one. 

Both by setting the graphics interpreter to *inline* or installing Spyder in the same environment will alleviate the problem (but is not a solution).

This could (for instance) result into issues when hardware connections are made, as the addresses are not freed up, and reconnection is not possible until Spyder is restarted.

### What steps reproduce the problem?
1. Set Qt5 graphics backend in Spyder.
2. Start a kernel in a non-default interpreter (different conda env).
3. Restart kernel by clicking the cross.

### What is the expected output? What do you see instead?
Expected: underlying python thread is killed. 
Instead: it stays alive

A way to visualise this, would be to initiate a Tk window. You'll see it stays alive after restarting the kernel. NOTE: this is NOT a prerequisite to have the issue occur, just a way to illustrate it.

### Paste Traceback/Error Below (if applicable)
None

## Versions

* Spyder version: 5.2.0 (confirmed issue is also there in 5.1.5)
    * Tried both the standalone version and the conda version. No difference.
* Python version: 3.9.7
* Operating System name/version: Windows 10

**Comment by steff456** [comment]
Hi @NicoHendrickx,

Thanks for reporting, can you explain to me what do you mean by "restart the kernel by clicking the cross"? The cross in the tab of the console will close it, but it won't restart it.

**Comment by NicoHendrickx** [comment]
I closed in a bit on the issue. It's the combination of the non-default interpreter and the *Qt5* graphics backend! When setting the inline graphics backend, this issue does not arise. Would that give a hint as to where the issue might arise?

**Comment by steff456** [comment]
@impact27, do you know why this is hapenning?

**Comment by impact27** [comment]
That is strange, the kernel should be killed after 10 seconds if I am not mistaken. How do you start the kernel exactly?

**Comment by NicoHendrickx** [comment]
@impact27 Thanks for taking a look at this.

So, what I do is the following:
1. Create fresh environment running python 3.9.7 and spyder-kernels, let's call it `test`
2. Install pyqt5 in this environment.
3. Run Spyder (5.2.0, but tried also 5.1.5) in either a different env, or standalone
4. Select `test` python as interpreter in Spyder.
5. Set graphics backend to `Qt5`
6. **Just to show the issue**: start a tk window (the real issue I have is with hardware connections not freeing up)
7. Close the terminal by clicking the cross on the tab.
8. A new kernel will spawn automatically.
9. Old process will stay alive, as can be seen by the presence of the tk window.

Now, when I try this by installing Spyder in the test environment, the issue does not show up, but I would prefer to keep Spyder separated (to avoid pyqt5 version collisions).

Note, I also tried restarting using ctrl+. but this often does not work at all. Just shows `Traceback (most recent call last):`.

**Comment by ccordoba12** [comment]
Hey @NicoHendrickx, thanks a lot for the detailed steps you posted above! With them I was able to reproduce this problem (it seems it only happens on Windows though) and find a solution for it, which will be in our next version.
