### ISSUE TITLE
Code Analysis error in the Windows installer when overwriting installation with a new installer version

### ISSUE THREAD

**Issue by idscd** [spyder-ide/spyder#17025]
### What steps will reproduce the problem?

Starting Code Analysis results in error message.

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Spyder\pkgs\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "C:\Program Files\Spyder\pkgs\pylint\__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "C:\Program Files\Spyder\pkgs\pylint\lint\run.py", line 279, in __init__
    linter.load_default_plugins()
  File "C:\Program Files\Spyder\pkgs\pylint\lint\pylinter.py", line 579, in load_default_plugins
    checkers.initialize(self)
  File "C:\Program Files\Spyder\pkgs\pylint\checkers\__init__.py", line 133, in initialize
    register_plugins(linter, __path__[0])
  File "C:\Program Files\Spyder\pkgs\pylint\utils\utils.py", line 198, in register_plugins
    module.register(linter)
  File "C:\Program Files\Spyder\pkgs\pylint\checkers\unsupported_version.py", line 85, in register
    linter.register_checker(UnsupportedVersionChecker(linter))
  File "C:\Program Files\Spyder\pkgs\pylint\lint\pylinter.py", line 723, in register_checker
    self.msgs_store.register_messages_from_checker(checker)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_definition_store.py", line 39, in register_messages_from_checker
    self.register_message(message)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_definition_store.py", line 44, in register_message
    message.msgid, message.symbol, message.old_names
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_id_store.py", line 44, in register_message_definition
    self.check_msgid_and_symbol(msgid, symbol)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_id_store.py", line 81, in check_msgid_and_symbol
    self._raise_duplicate_symbol(msgid, symbol, existing_symbol)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_id_store.py", line 90, in _raise_duplicate_symbol
    raise InvalidMessageError(error_message)
pylint.exceptions.InvalidMessageError: Message id 'W1601' cannot have both 'apply-builtin' and 'using-f-string-in-unsupported-version' as symbolic name.

```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @idscd, thanks for reporting. We'll try to fix this problem soon.

@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @idscd could you post here a code example that triggers this error for you? Any info in order to reproduce this is greatly appreciated. Let us know!

**Comment by dalthviz** [comment]
Checking a little bit more the error message mentions the `using-f-string-in-unsupported-version` checker which validates that you are not using `f-strings` with Python < 3.6 Do you have some Python < 3.6 installed in your setup @idscd ?

**Comment by ccordoba12** [comment]
Additional notes:

1. This check was added in Pylint 2.12: https://pylint.pycqa.org/en/latest/whatsnew/2.12.html?highlight=py-version#new-checkers
2. It requires setting `py-version` in your `pylintrc`, as shown here: https://github.com/PyCQA/pylint/pull/5139/files#diff-995de72dd4c3040f0ec3191d20d75560c4c3bb7ffb7dc386fc098129552cc1c6

**Comment by idscd** [comment]
Here it is.

***
 """
Python Without Fear. Example 12.1.

Dictionaries and Sets. Personal Phone Book.
A rudimentary database application that keeps track of phone numbers.
"""
from os import system
print('Python Without Fear. Example 12.1.\n Personal Phone Book.')
print()
# Initiate a dictionary.
phone_dict = {}


# Main function.
def main():
    """Prompt for the next command and executes."""
    while True:
        prompt = 'Enter command: 1 - data entry, '
        prompt += '2 - query, 3 - exit >> '
        p_str = input(prompt)
        if not p_str:  # If string is empty, break.
            break
        cmd = int(p_str)
        if cmd == 3:
            break
        if cmd == 1:
            add_entries()
        elif cmd == 2:
            display_entries()


# Add_Entries function prompts for key-values pairs until user wants to exit.
# Adds key-value to dictionary.
def add_entries():
    """Add an entry to a phone book."""
    while True:
        key_str = input('Input name (ENTER to exit): ')
        key_str = key_str.strip()
        if not key_str:  # If key_str empty, return.
            return
        val_str = input('Enter phone number: ')
        val_str = val_str.strip()
        if not val_str:
            return
        phone_dict[key_str] = val_str


# Display_Entries function prompts for name and prints corresponding value.
# Re-prompts if key not found.
def display_entries():
    """Display a value from a phone book."""
    while True:
        key_str = input('Enter name (ENTER to exit): ')
        key_str = key_str.strip()
        if not key_str:  # If string empty, return.
            return
        val_str = phone_dict.get(key_str)
        if val_str:
            print(val_str)
        else:
            print('Name not found. Re-enter.')


main()

print()
system('pause')

 
 
 
 


---------- Original Message ----------

**Comment by idscd** [comment]
No, 3.8.10   

---------- Original Message ----------

**Comment by idscd** [comment]
OK, I went back to Spyder ver. 5.1.5, and all those issues disappeared.

**Comment by dalthviz** [comment]
When running the provided code this is what I'm seeing:

![imagen](https://user-images.githubusercontent.com/16781833/146567466-ade2086d-d360-44fe-a9e8-ef1712db7334.png)

Also, how are you downgrading or updating Spyder @idscd ? Do you uninstall first the previous version you have installed or do you just run the installer of the version you want? Let us know!

**Comment by idscd** [comment]
Now that I'm running 5.1.5 I see similar screen with a few extra warnings about naming conventions.When updating Spyder with new version, I run the new installer on top of previously installed version.I tried the same way with downgrading, but it did not work. So, I had to uninstall Spyder and do a clean 5.1.5 install.   Thank you,Ilya

---------- Original Message ----------

**Comment by dalthviz** [comment]
Thank you for the new info @idscd ! I not totally sure if we had that somewhere in the docs but the thing is that the standalone installer (for the moment) is not uninstalling/checking automatically previous installation so you can end up with errors if you overwrite a previous installation with a new installation.

I would say that the correct procedure to update the Windows standalone installer for the moment is to uninstall first the previous version and then run the new installer. Should we add something regarding this in the docs @ccordoba12 ?

**Comment by ccordoba12** [comment]
> Should we add something regarding this in the docs @ccordoba12 ?

Yep, that's a good idea @dalthviz. But it'd be better if the installer could detect if a previous Spyder installation is in place to inform users that they need to uninstall it before proceeding.

**Comment by dalthviz** [comment]
Note: This could be useful here https://stackoverflow.com/questions/488717/detecting-if-a-program-is-already-installed-with-nsis
