### ISSUE TITLE
Spyder 5.2.1 installs two DLL's for numpy gfortran. Deleting one of those DLL's makes the warning go away.

### ISSUE THREAD

**Issue by Tunneller** [spyder-ide/spyder#17029]
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Installing 5.2.1 via the Windows Download package created two DLL's for numpy gfortran in this folder, one dated Nov 2021 and one dated Dec 2021.

C:\Program Files\Spyder\pkgs\numpy\.libs

That led to an error message when starting Spyder

### What steps reproduce the problem?

1.    Hm.... I didn't. I deleted the older of the two DLL files to see what would happen. Spyder appears to be working just fine.
 
Not exactly the world's worst bug :-) Thanks for the continued support of Spyder.

**Comment by dalthviz** [comment]
Hi @Tunneller thank you for the feedback! When you used the installer for version 5.2.1 did you had a previous version installed? I think we don't have that documented but the installer will overwrite the files in the installation dir but will not remove old files so for a clean installation you need to first uninstall the old version and then install the current one (maybe we should check a way to do this automatically though).

I checked my installed 5.2.1 version and under `.../Spyder/pkgs/numpy/.libs` I only found one `.dll`

Let us know if the above makes things more clear!

**Comment by dalthviz** [comment]
Closing due to lack of response. Probably related to https://github.com/spyder-ide/spyder/issues/17025
