### ISSUE TITLE
Indentation reset after pressing enter

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1703]
_From [m.p.e.be...@gmail.com](https://code.google.com/u/111044622763708421107/) on 2014-01-23T08:01:00Z_

Spyder Version:  2.1.9
Python Version:  2.7.3
Qt Version:      4.8.1, PyQt4 (API v2) 4.9.1 on Linux 

What steps will reproduce the problem?
1. I edit code in the code editor, that is indented (with spaces)
   1. If I press enter and then immediately either arrow up or arrow down, the indentation is reset, i.e. the cursor moves to indentation zero

Would it be very complex to fix the code so that the indentation is preserved even after enter + arrow up/down?

Thank you,
Mathias

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1703_

**Comment by ccordoba12** [comment]
Closing, old bug.
