### ISSUE TITLE
Wrong EOL characters written to file when saving

### ISSUE THREAD

**Issue by yum-yum-in-my-tum-tum** [spyder-ide/spyder#17045]
### Issue Report Checklist
* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
- [Add "Save all files with <eol> EOL characters" option #5365](https://github.com/spyder-ide/spyder/issues/5365) and [Add a way of changing and converting EOL characters between different standards independent of OS #2196](https://github.com/spyder-ide/spyder/issues/2196) suggest the Preferences -> Editor option "On save: convert EOL characters" set to "LF (Unix)" should solve this issue. 
- [EOLs incorrectly switch from LF to CRLF on split editor panes #4304](https://github.com/spyder-ide/spyder/issues/4304): is potentially similar? In that issue also, the selected EOL option was not being recognized for some reason. 
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
- Restarted Spyder, problem persists. Updated conda, Spyder is up to date. Restarted Spyder again, problem persists.
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
- Done, reports that Spyder already up to date

* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am writing a .txt file from a python script in Spyder. I would like the end of line (EOL) character to be a line feed (LF), not a carriage return/line feed (CRLF). I have set the EOL character to LF in Spyder, and there are no "\r"s in my script. When I open the file in Notepad++ to check, it shows CRLF, not LF. Spyder displays the EOL option correctly in the bottom right of the viewer. 
<img src="https://user-images.githubusercontent.com/96306206/146585852-8d19d6a6-6fb5-46a9-9558-7bbedd661a7e.png" 
 width="590" height="32">

### What steps reproduce the problem?
1. Set Spyder Preferences -> Editor -> "On save: convert EOL characters" set to "LF (Unix)"
<img src="https://user-images.githubusercontent.com/96306206/146585740-4f54ed5d-d48e-4d1a-a08d-bc5c21c63cef.png" width=50% height=50%>
2. Set Source -> Convert end of line characters to "Line Feed (Unix)"
<img src="https://user-images.githubusercontent.com/96306206/146585803-7a595cd6-b766-4edd-a8e6-64de9ee983f1.png" width=50% height=50%>
3. Write sample code to a text file
4. Open text file in Notepad++, setting View -> Show symbols -> Show all characters

Sample code:
```
out_file = open('linefeed_fix_test1.txt', 'w')
test_list = ["line1|value1|value2", "line2|value1|value2", "line3|value1|value2", "line4|value1|value2", "line5|value1|value2"]
for i in test_list:
    out_file.write("{}\n".format(i))
out_file.close()
```

### What is the expected output? What do you see instead?
- Expected output: 
<img src="https://user-images.githubusercontent.com/96306206/146583721-38462bbc-0ebf-466b-8a95-a508258d0199.png" width=50% height=50%>

- Actual output: 
<img src="https://user-images.githubusercontent.com/96306206/146583794-8e3560fa-7c2a-4012-8c7d-4aa3354e4076.png" width=50% height=50%>

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)
# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @yum-yum-in-my-tum-tum, thanks for reporting. You're right: we're not setting EOL chars correctly when saving. We'll try to fix that in our next version.

**Comment by yum-yum-in-my-tum-tum** [comment]
@ccordoba12 Awesome, thanks!
