### ISSUE TITLE
Spyder 5 GUI window can't move once it's moved to a secondary display when there are multiple displays on windows 11

### ISSUE THREAD

**Issue by drlakecoder** [spyder-ide/spyder#17044]
I am not sure if this is a Spyder bug or it's a windows 11 bug. But when I moved spyder window to a secondary display (I have three), then I found that I can't ever move that window to any where (e.g. back to the main display). I can undock some of the panels and move those aroudn freely, but the main window seems to be stuck with no way of moving it anywhere. And if you look at the screen capture, those normal buttons for minizmizing/resizing/closing the window (the top right corner) don't show up either. 
anyone else has similar issues? how do we fix it? closing and restarting doesn't help, windows 11 put it right back to where it was.

![image](https://user-images.githubusercontent.com/93505316/146452150-4b87392e-38ab-408e-a47d-7f1cff5e297d.png)

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by drlakecoder** [comment]
Ok, just played with it a bit. I have to change the window pane layout, then the main window becomes normal again and I can move it around.  This feels like a bug, not sure if it's a windows 11 problem or spyder's own issue.

**Comment by ccordoba12** [comment]
It seems a Windows 11 bug, but thanks for reporting and let is know how you fix it.
