### ISSUE TITLE
Breakpoints symbols looks so compact on a high DPI screen. Please release a fix

### ISSUE THREAD

**Issue by soumesh2002** [spyder-ide/spyder#17088]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/53593544/147353942-5c3f165b-d232-40c1-b26f-487a28a5d08a.png">
The breakpoint symbol as well as the arrow mark while debugging feels quite compact. Please change the design. Previously we can easily set the breakpoints towards the left of the line numbers which was quite comfortable. The present update to Spyder makes the breakpoint quite compact, which is visually not so good.
Hope the Spyder team will release a fix for the design.

**Comment by dalthviz** [comment]
Hi @soumesh2002 thank you for the feedback. What Spyder version are you using? Also, could you check if enabling the `Enable autop high DPI scaling` preference helps? In our latest version it is located under `Application > Interface > Screen resolution` section. Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by soumesh2002** [comment]
No change, it is quite uncomfortable for me if I increase my DPI scaling to high resolution, can you give some other fix ?

**Comment by dalthviz** [comment]
@soumesh2002 you could try checking if setting some value at `Set custom high DPI scaling` helps
