### ISSUE TITLE
`KeyError: 'workspace'` when opening a project

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#17097]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Can't open an old project after updating my spyder

### What steps reproduce the problem?

1. Try to open a project

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\kaleb\miniconda\envs\keep\lib\site-packages\spyder\plugins\projects\plugin.py", line 314, in <lambda>
    triggered=lambda v: self.open_project())
  File "C:\kaleb\miniconda\envs\keep\lib\site-packages\spyder\plugins\projects\plugin.py", line 471, in open_project
    project_type_class = self._load_project_type_class(path)
  File "C:\kaleb\miniconda\envs\keep\lib\site-packages\spyder\plugins\projects\plugin.py", line 903, in _load_project_type_class
    project_type_id = config[WORKSPACE].get(
  File "C:\kaleb\miniconda\envs\keep\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'workspace'

```

## Versions

* Spyder version: 5.2.1 None
* Python version: 3.7.12 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @kaleb-keny, thanks for reporting. This was closed incorrectly by our bot but we'll try to fix it in our next version.

In the meantime, please remove the `.spyproject` directory located in your project one, and recreate your project again.

**Comment by kaleb-keny** [comment]
sure will do thank you 🙏🏼
