### ISSUE TITLE
How to remove Kite from Spyder completely

### ISSUE THREAD

**Issue by richlysakowski** [spyder-ide/spyder#17108]
I want to remove all traces of the Kite plugin from Spyder installations completely to prevent it from ever nagging me to install or configure it.  

[![enter image description here][1]][1]
I don't trust it, and I don't want it anywhere on my machine.  

The Kite plugin has a history of being untrustworthy and monitors people's coding activity on their servers and examines one's source code "in order to improve the Kite product".  [https://news.ycombinator.com/item?id=14836653&p=2][2] 

Whether the realtime monitoring from their servers is true or not, I don't want installed it anywhere on my machine.  It is intrusive and interferes with coding.  The Python Language Server gives me all the coding hints and suggestions that I need.  

WHAT I TRIED: 

I tried deactivating it from Spyder Preferences... Advanced dialog box and restarting it (as shown below).  However, this does not remove it completely from the interface or the installation.  It appears on the menu after disabling it.  

WHAT I NEED: 

Remove it from the Spyder v4 and Spyder v5 installer distribution or conda package.  If Kite is willing to make the Kite Team Server completely free open source so anyone can install the AI engine(s) locally completely offline, completely free forever of all monetary charges or obligations, without ever contacting their servers for any reason, then I would let it stay.  I don't want a "freemium" edition installed either.  However, Kite is a commercial product and AFAIK, they have not made their AI code completion server engine(s) free open source.  

Does anyone know how to remove this suspicious and commercial product from the Spyder v4 and Spyder v5 installation and installers, so it never appears in any Spyder edition?

  [1]: https://i.stack.imgur.com/eGjoy.png
  [2]: https://news.ycombinator.com/item?id=14836653&p=2
  [3]: https://i.stack.imgur.com/Z0Io5.png

**Comment by ccordoba12** [comment]
Hey @richlysakowski, thanks for reporting. I'm afraid that other than disabling the Kite support in our preferences, as you said you already did, there's nothing else to do to remove it from Spyder.

As you noticed, we disabled the Kite dialog shown the third time Spyder starts in our 5.2.1 version. And we'll remove all support for it in 5.3.0, to be released in a couple of months. Then you'll have exactly what you want, i.e. an Spyder version completely free from Kite.

**Comment by arashgmn** [comment]
@richlysakowski not sure if it's still relevant, but you can remove kite entirely from your machine as instructed [here](https://help.kite.com/article/68-how-to-uninstall-kite).

**Comment by lattice737** [comment]
> @richlysakowski not sure if it's still relevant, but you can remove kite entirely from your machine as instructed [here](https://help.kite.com/article/68-how-to-uninstall-kite).

Link appears to be dead now

**Comment by ccordoba12** [comment]
@lattice737, our Kite integration was removed in Spyder 5.3.0, released almost a year ago. So, by simply installing any more recent version, you won't see anything related to Kite in Spyder.
