### ISSUE TITLE
Programmatically skipping tests which depend on spyder-boilerplate if it's not installed

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#17104]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

There are two tests which depend on the `spyder-boilerplate` extension being installed and fail if it is not: `spyder/app/tests/test_find_plugins.py::test_find_external_plugins` and `spyder/app/tests/test_mainwindow.py::test_add_external_plugins_to_dependencies`.  The other tests in `test_mainwindow.py` attempt to load `spyder_boilerplate` through the `main_window` fixture, but they pass even in its absence.

In a local test (marked with `CI`, as it's running in an `xvfb-run` context), it is not possible to install the `spyder-boilerplate` extension, so I manually skip these two tests.  I don't know whether it would be as easy to do this programmatically as it was to check for a conda environment.  I imagine one could write some sort of function using `pkg_resources` to check whether the `spyder_boilerplate` package is installed, or some ugly code like the following:

```python
try:
    import spyder_boilerplate
    external_plugin_available = True
    del spyder_boilerplate
except ImportError:
   external_plugin_available = False
```
and then `@pytest.mark.skipif(not external_plugin_available, reason="Need spyder-boilerplate plugin installed")`.

**Comment by ccordoba12** [comment]
> There are two tests which depend on the spyder-boilerplate extension being installed

That plugin is part of our test suite:

https://github.com/spyder-ide/spyder/tree/5.x/spyder/app/tests/spyder-boilerplate

and we install it here before running it:

https://github.com/spyder-ide/spyder/blob/07ea6e9ee60ab77e0b89fb0a0a6998d868a29f9e/.github/scripts/install.sh#L68-L71

So either you do the same on your side, or simply skip those tests.

**Comment by juliangilbey** [comment]
Ah, OK, thanks!
