### ISSUE TITLE
Zen Knit Support?

### ISSUE THREAD

**Issue by contactzen** [spyder-ide/spyder#17112]
https://github.com/Zen-Reportz/zen_knit

Zen-Knit is a formal (PDF), informal (HTML) report generator for data analyst and data scientist who wants to use python. Inspired from Pweave and RMarkdown.

How can I integrate zen_knit into Spyder? Any guidence will be helpful.

**Comment by steff456** [comment]
Hi @contactzen,

I think this integration can be possible after we implement the `run` plugin. For now, it is not possible for us to add it, but we will take a look at this once we build the mechanism for adding new options to run the scripts. 

Thanks for reporting!

**Comment by ccordoba12** [comment]
Hey @contactzen, thanks for your interest in integrating your project with Spyder! You can create your own third-party plugin for this.

We have some docs about it:

http://docs.spyder-ide.org/current/workshops/plugin-development.html

and there's also this repository with some simple examples:

https://github.com/spyder-ide/plugin-examples

Although both are a bit outdated, they should be enough to get you started.

For now I'm going to close this issue but let us know if we can help you with something else.
