### ISSUE TITLE
There is a problem with the style of the interface

### ISSUE THREAD

**Issue by prehonor** [spyder-ide/spyder#17119]
![image](https://user-images.githubusercontent.com/10784632/147730384-85dfc604-01b7-48be-9f19-c269ce4754bf.png)
spider version is 5.2.1 and  pyqt version is 5.15.4 ，can  I change some code to fix it and how ？

**Comment by ccordoba12** [comment]
Hey @prehonor, thanks for reporting. I don't see any problem with your screenshot.

What's exactly the problem that you have?

**Comment by prehonor** [comment]
> Hey @prehonor, thanks for reporting. I don't see any problem with your screenshot.
> 
> What's exactly the problem that you have?

The bar is a bit tall。

**Comment by ccordoba12** [comment]
That's by design: buttons need to have certain size for accessibility standards, so we adjusted the size of our toolbars according to that.

There's already spyder-ide/ux-improvements#41 asking to make that size configurable, but we haven't had time to implement it, sorry.
