### ISSUE TITLE
Introspection settings mixing poorly with __getattr__ and interactive plotting mode?

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1712]
_From [kinnison...@gmail.com](https://code.google.com/u/104685941974947235171/) on 2014-01-29T15:43:12Z_

Spyder Version:  2.3.0beta3
Python Version:  2.7.6
Qt Version    :  4.8.5, PySide 1.2.1 on Linux
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.3 (OK)
pylint >=0.25   :  None (NOK)

I realize the introspection stuff has the potential for side-effects, since nearly everything in Python can be customized.  Simply calling hasattr could trigger who knows what from custom classes.  But I think this issue I'm reporting now is separate from that.  

I encounter the bug if the introspection monitor is enabled and either automatic code completion or display balloon tips are enabled.  Happens in both console types.

Example:

=====================================================
```
import matplotlib.pyplot as plt

class AttrPrefix(object):
    def __init__(self,prefix=None,trace=False):
        self.trace=trace
        if prefix is not None:
            self.prefix=prefix
    def __getattr__(self,attr):
        try:
            return object.__getattribute__(self,attr)
        except:
            pass
        
        try:
            ret=globals()[attr]
            self.prefix()
            return ret
        except Exception as e:
            if not attr.startswith('_'):
                if self.trace:
                    print(e)
                    import traceback
                    traceback.print_stack()
            raise
        
class Fig(AttrPrefix):
    def __init__(self,*args,**kwargs):
        self.fig=None
        self.fig_number=None
        AttrPrefix.__init__(self,*args,**kwargs)
    def prefix(self):
        self.fig=plt.figure(self.fig_number)
        self.fig_number=self.fig.number
        self.fig.clear()


plt.close('all')
f=Fig()
f.plt.plot([1,2])
\# if you manually type the following line, it won't work:
f.plt.bar([1,2],[1,2])

plt.close('all')
f=Fig(trace=True)
f.plt.plot([1,2])
\# if you manually type the following line, it now catches a out of stack space Exception:
f.plt.bar([1,2],[1,2])
'''
\>>> f.plt.out of stack space (infinite loop?)
  File "/home/Josh/anaconda/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/home/Josh/anaconda/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/Josh/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/monitor.py", line 550, in run
    result = eval(command, glbs, lcls)
  File "<string>", line 1, in \<module>
  File "/home/Josh/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/monitor.py", line 346, in get_dir
    obj, valid = self._eval(objtxt)
  File "/home/Josh/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/monitor.py", line 340, in _eval
    return eval(text, ns), True
  File "<string>", line 1, in \<module>
  File "<stdin>", line 21, in __getattr__
'''
```
==================================================================

What I expect is for the figure to redraw and show a bar plot.  But it fails to do so (only if you are typing the command out manually in the console).

I've been exploring the problem for a while, and have hopefully caught a few important clues.  First if of course the caught Exception shown in the example.  The moment I press '.' after plt the problem occurs.  But interestingly, I can eat the Exception and everything almost works correctly.  Just that the figure's canvas no longer updates as expected.  Second clue is that calling plt.draw_if_interactive() fails to redraw.  It seems like the canvas' draw_idle method doesn't update if self._idle is False (at least for FigureCanvasTkAgg).  Instead using plt.draw() does work, but that is hardly interactive.  As to how the Monitor ends up convincing matplotlib canvases that they aren't idle... I'll leave that to someone else to figure out!

This bug is probably rather low priority if this is the only place it comes up.  But I've had plenty of strange issues with matplotlib figures + Spyder (happening across many different versions), some of which seem in ways similar to what I described here (figures not redrawing, figure state getting messed up, different behavior if typed manually) in situations that don't involve me doing anything particularly unusual.  It might at least be worth looking into, just to make sure it isn't causing other more important bugs.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1712_

**Comment by blink1073** [comment]
@ccordoba12, I looked at this for a bit.  I get the same stack trace when using the Tkinter backend, and the Qt backend suffers from similar responsive problems.  The Inline works fine with it, and I can manually update plots just fine within Tkinter and Qt backends.  I'd say this is an obscure edge case where you can't always write your code in an IDE.

I vote to close this one as won't fix.

**Comment by ccordoba12** [comment]
Yep, let's close this one :-) Thanks for taking a look at it!
