### ISSUE TITLE
Spyder doesn't start after installing MNE package, complains about Qt

### ISSUE THREAD

**Issue by Siebenstein83** [spyder-ide/spyder#17136]
I just installed the new Anaconda distribution, and then installed Spyder in the base environment. Works like a charm, although it will say "link image0 hasn't been detected!" if I start from the prompt.

Then, I installed the MNE package (https://mne.tools/stable/install/mne_python.html; version 0.24.1) into a new environment, and in the process a large number of packages got updated, including python. Then, I installed Spyder, but when trying to start it, I get the following error message: 

> Could not load the Qt platform plugin "windows" in "" even though it was found. This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem. Available platform plugins are: direct2d, minimal, offscreen, windows, webgl. 

All packages were installed with conda or mamba, no pip used. 

Base enviroment:
* Spyder version: 5.2.1
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* PyQtWebEngine: not installed

MNE environment:
* Spyder version: 5.2.1
* Python version: 3.9.9
* Qt version: 5.12.9
* PyQt version: 5.12.3
* PyQtWebEngine: 5.12.1

Now one might think that maybe it's the Qt version that isn't compatible with spyder, but on another machine, I have the following environment with a slightly older MNE version (0.23.4) MNE in which Spyder is running:
* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 5.12.9
* PyQt version: 5.12.3
* PyQtWebEngine: 5.12.1

Operating System on both machines is Windows Server 2019 Standard.

Any help appreciated.

**Comment by ccordoba12** [comment]
That creates the environment. But after that, did you run this?

    pip install mne matplotlib

**Comment by Siebenstein83** [comment]
No, I didn't run this. Mne is installed when the environment is created by the above command.

**Comment by Siebenstein83** [comment]
I also created a different environment now, in which I installed mne and matplotlib via pip rather than conda; and then also spyder via pip. Here, I get a different error (not in prompt, but in pythonw pop-up): 

> This application failed to start because no Qt platform could be initialized. Reinstalling the application may fix this problem. Available platform plugins are: direct2d, minimal, offscreen, windows, webgl.

**Comment by ccordoba12** [comment]
> No, I didn't run this. Mne is installed when the environment is created by the command that I posted.

Ok, that's good. Did you also installed Spyder from conda-forge after that?

**Comment by Siebenstein83** [comment]
> Ok, that's good. Did you also installed Spyder from conda-forge after that?

Yes, that's what I did.

**Comment by Siebenstein83** [comment]
The thing that really puzzles me is that Spyder works in the base environment, it's not like qt does not work at all on my system.

**Comment by Siebenstein83** [comment]
Alright, now Spyder is working also in other environments after I removed the QT_PLUGIN_PATH variable from my environment.

**Comment by ccordoba12** [comment]
Ok, great! Closing this then.
