### ISSUE TITLE
Kernel is Always Not Available and Contol Module is not being identified

### ISSUE THREAD

**Issue by ajinkya1211** [spyder-ide/spyder#17138]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by boon66** [comment]
您好，您发的邮件我已收到，谢谢！祝一切顺利！

**Comment by ccordoba12** [comment]
Hey @ajinkya1211, the information you provided is not enough to understand your problem and properly help you. Please describe your problem in more depth and (if possible) post screenshots or videos about it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
