### ISSUE TITLE
debian lintian4py check

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1715]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2014-02-01T08:34:49Z_

Hello, I report here some check done with lintian4py from debian.

This is for the 2.3.0~beta3 version

w: python-spyderlib: hardcoded-errno-value usr/share/pyshared/spyderlib/utils/external/pickleshare.py:100: 2 -> errno.ENOENT
e: python-spyderlib: pyflakes-undefined-name usr/share/pyshared/spyderlib/widgets/externalshell/start_ipython_kernel.py:146: open_in_spyder
e: python-spyderlib: pyflakes-undefined-name usr/share/pyshared/spyderlib/widgets/externalshell/start_ipython_kernel.py:157: get_ipython
e: python-spyderlib: pyflakes-undefined-name usr/share/pyshared/spyderlib/widgets/formlayout.py:275: os
e: python-spyderlib: pyflakes-undefined-name usr/share/pyshared/spyderlib/widgets/formlayout.py:278: QTextEdit
e: python-spyderlib: pyflakes-undefined-name usr/share/pyshared/spyderlib/widgets/formlayout.py:336: QTextEdit
e: python-spyderlib: pyflakes-undefined-name usr/share/pyshared/spyderlib/widgets/formlayout.py:338: os

cheers

Fred

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1715_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-02-07T05:30:28Z_

Thanks Fred, I'll take a look at all those warnings/errors.

**Labels:** Cat-Miscelleneous MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-13T13:48:19Z_

I created a PR for the 4 last errors (missing imports): https://bitbucket.org/spyder-ide/spyderlib/pull-request/42/fix-some-debian-lintian4py-check-missing/diff For the first error I proposed a patch upstream, I don"t know how you want to manage it inside spyder (wait for upstream to update ?): https://github.com/vivainio/pickleshare/pull/1 . Anyway, this is only a readability warning, nothing is broken.

The second one is because spyder adds open_in_spyder to the buildins in spyderlib/widgets/internalshell.py. I didn't look further.

I don't know what to think about the third one. 'get_ipython_dir' is used many times, but 'get_ipython' is not defined anywhere. It is used as a method in spyderlib/widgets/externalshell/monitor.py but that's all.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-15T07:57:49Z_

Thanks Joseph, these are my comments:

1. I think we can patch our internal copy of pickleshare for Error 1. Could you add it to PR 42?

2. I added an "analysis:ignore" comment for both Errors 2 and 3.

   * open_in_sypder is defined in our sitecustomize.py, so it can't be imported but it's expected to be defined in all our interactive sessions (Python and IPython)
   * get_ipython is an internal object defined in every IPython session that holds a lot of things needed for IPython (config options, user namespace, etc).

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-15T12:35:26Z_

1. is fixed.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-15T15:21:03Z_

Ok, thanks.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-18T11:15:28Z_

This issue was updated by revision 22eecf866858 .

**Status:** Fixed

**Comment by Nodd** [comment]
For information, 1. is now fixed upstream: https://github.com/pickleshare/pickleshare/pull/1
