### ISSUE TITLE
Add flag to the Windows installer to allow installation for all users

### ISSUE THREAD

**Issue by darklink87** [spyder-ide/spyder#17154]
There is no documentation for doing a Silent install and adjusting the Installation directory on Windows. The most that I could find online was this https://silentinstallhq.com/spyder-ide-silent-install-how-to-guide/ but it's not enough. By default, a Silent install will only install for the Currnent user and load it into their Local AppData, which causes installation to fail when deployed with MDM solutions like MIcrosoft Intune.

If you run the installer manually, it asks if the application should be available for All Users or just the Current User, so I need an installation flag for All Users which installs to the Program Files directory instead. Combined with the Silent installation flag, this will accomplish what I need.

**Comment by ccordoba12** [comment]
Hey @darklink87, thanks for reporting. This is valid suggestion, so we'll try to address it in the coming months.

**Comment by dalthviz** [comment]
Note: This could be useful here: https://stackoverflow.com/questions/35944305/how-to-install-an-nsis-executable-silently-for-all-users

**Comment by darklink87** [comment]
> Note: This could be useful here: https://stackoverflow.com/questions/35944305/how-to-install-an-nsis-executable-silently-for-all-users

Looks like /S /ALLUSERS=1 does a Silent Installation to the Program Files directory which is exactly what I was looking for. Thanks for that find!

**Comment by dalthviz** [comment]
Awesome @darklink87 ! Glad that worked for you :+1: 

I will close then this one
