### ISSUE TITLE
File open dialog and PyQt5 Widgets HUGE

### ISSUE THREAD

**Issue by cognitivity** [spyder-ide/spyder#17161]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Attempt to open files produces a huge file dialog.
PyQt5 widgets like check boxes, scroll bars, up-down arrows in running programs are all HUGE.

### What steps reproduce the problem?

1. File | Open... yields huge file open selection dialog (fonts, icons, etc.)
2. PyQt5 widgets in running python program (work fine on other Spyder versions) like check boxes, scroll bars, up-down arrows are all HUGE.
3. 

### What is the expected output? What do you see instead?
Normal-sized file open dialog and PyQt5 widgets.  Work fine on other Spyder releases.
![Spyder issues](https://user-images.githubusercontent.com/16745418/148665430-3ccdfc3a-eeef-4061-b4e6-20f78a6205db.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.1.5
* Python version:  3.9.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.29.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.7.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.2 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.10.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.2.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.3 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.3.4 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.9 (OK)

```

**Comment by ccordoba12** [comment]
Hey @cognitivity, thanks for reporting. You said

> File | Open... yields huge file open selection dialog (fonts, icons, etc.)

I don't know why that happens. We simply call the operating system open dialog in Spyder; maybe it's an issue with your high resolution screen

> PyQt5 widgets in running python program (work fine on other Spyder versions) like check boxes, scroll bars, up-down arrows are all HUGE.

Spyder has nothing to do with that, but I think that also has to do with your screen.

We have some options to control that in the menu

    Tools > Preferences > Application > Interface

You can adjust them to see if that helps. If not, you could try to use Spyder with our Windows installer, which has a more recent version of Qt/PyQt5 (that could help). You can download it from here:

https://github.com/spyder-ide/spyder/releases

**Comment by ccordoba12** [comment]
Nice! Glad to hear the problem is solved for you now.
