### ISSUE TITLE
Suggestions on pd.merge

### ISSUE THREAD

**Issue by mIgLLL** [spyder-ide/spyder#17168]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In data manipulation, it's a common step that you need to link two database together. But very oftenly, we will met a problem: you need to merge two database replying on more than one individual symbols. For example, you can link the firms with patent on CUSIP symbols, or just firm's name, but it's better to use them both.

Demand: I have Dataframes "Firm" and "Patent", I want the "Merged" DataFrame.

Firm=pd.DataFrame(np.array([('00001',np.nan,'3000B'),('00002','Banana','2000B')]),columns=['CUSIP','name','market_value'])

Patent=pd.DataFrame(np.array([('00001','Apple','2'),(np.nan,'Banana','3')]),columns=['CUSIP','name','patent_number'])

Merged=pd.DataFrame(np.array([('00001','Apple','3000B','2'),('00002','Banana','2000B','3')]),columns=['CUSIP','name','market_value','patent_number'])

I think an "UPDATE" function is suitable. Here is how it describe: update missing values of same-named variables in master with values from using. If not the same-named, you can just normally merged.

For now, I need to write code like below:
Merged=pd.merge(Firm,Patent[['CUSIP','patent_number']],on=['CUSIP'],how='left',indicator='_merge')
Merged_left=Merged[Merged['_merge']=='left_only']
Merged=Merged[Merged['_merge']=='both']
Merged_left=pd.merge(Merged_left.drop('patent_number',axis=1),Patent.drop('CUSIP',axis=1),how='left',on='name')
Merged=Merged.append(Merged_left)

And of course, I still miss the "Apple" firm name.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @mIgLLL,

It seems you don't have any error with Spyder, rather a problem with pandas. For this, please create an issue in the pandas issue tracker because we are unable to fix it here. 

Thanks for reporting!
