### ISSUE TITLE
Automatic error report, i am ok with such kind of error and having no any issue

### ISSUE THREAD

**Issue by sunnysiddharth231** [spyder-ide/spyder#17179]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @sunnysiddharth231, thanks for reporting. This looks like a duplicate of issue #17178, so I'm going to close it.
