### ISSUE TITLE
No wheels available for Python 3.10 and PyQt 5.12

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#17197]
## Problem Description

Having Spyder runinng on Windows 10 / Python-3.10

The only way that works today Jan 15th seems  Pyside2-5.15.2

![image](https://user-images.githubusercontent.com/4312421/149621575-f283a5b9-bf1e-4531-9c25-c9744749f61b.png)

I don't know if there will be a PyQt5.15 for Python-3.10 on Windows10 any time soon.

### What steps reproduce the problem?

1.   try to make Spyder start on Windows10 / Python-3.10 per all possible means
2. 
3. 

### What is the expected output? What do you see instead?

It starts, If I install pyside2 and recompile Spyder wheel without PyQt dependancy

## Versions

* Spyder version: 5.2.2.dev
* Python version: 3.10.2
* Qt version: 5.15.2
* PyQt version:  NONE , but Pyside2-5.15.2 is ok
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @stonebig, thanks for reporting. Unfortunately, we can't do that because then Spyder won't work for our pip users in other Python versions than 3.10. As you said, you can patch our wheel to make it work with Pyside2, so I don't see why we should make such a drastic change here.

The best we can do is using Pyside2 for Python 3.10 and PyQt5 for older versions, given the lack of PyQt5 wheels for 3.10. I'll try to implement that in our next release.

**Comment by stonebig** [comment]
There is a sort of contradiction to use QtPy, but to put a PyQt dependancy in the wheel. 
maybe shall there be a SpyderPyQt and a SpyderPySide set of wheel ?

**Comment by ccordoba12** [comment]
> but to put a PyQt dependancy in the wheel.

If you install Spyder without PyQt5/PySide2 is totally useless. And users don't need to know about that extra info just to run it. So we need to depend on a Qt binding, and we've always preferred to do it on PyQt5 because it's usually more stable. Please don't insist about this.

> maybe shall there be a SpyderPyQt and a SpyderPySide set of wheel ?

That would introduce even more confusion for what really is an implementation detail that users don't need to care about at all. So I'm totally against it, sorry.

**Comment by athompson673** [comment]
Merge issue with https://github.com/spyder-ide/spyder/issues/12829? It's same net effect to support pyside2 with 5.15 as support 5.15 directly right? (and likely may suffer the same issues as well which prevent 5.15 rn)

**Comment by ccordoba12** [comment]
> Merge issue with #12829?

They are different because they way to solve each one is not the same.

**Comment by ccordoba12** [comment]
@dalthviz, could you test if you can install PyQt5 with pip in a Python 3.10 environment? If not, we definitely need to solve this issue for 5.3.0

**Comment by dalthviz** [comment]
@ccordoba12 I was able to install PyQt5 with pip on a conda env with Python 3.10.2:

<details>

```
# Name                    Version                   Build  Channel
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
black                     22.1.0             pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
click                     8.0.4           py310h5588dad_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1           py310h8a704f9_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
executing                 0.8.2              pyhd8ed1ab_0    conda-forge
ipykernel                 6.9.1           py310hbbfc1a7_0    conda-forge
ipython                   8.0.1           py310h5588dad_2    conda-forge
jedi                      0.18.1          py310h5588dad_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2           py310h5588dad_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mypy_extensions           0.4.3           py310h5588dad_4    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
openssl                   3.0.0                h8ffe710_2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.1                   pypi_0    pypi
python                    3.10.2          hcf16a7b_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pywin32                   303             py310he2412df_0    conda-forge
pyzmq                     22.3.0          py310h73ada01_1    conda-forge
setuptools                60.9.3          py310h5588dad_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
spyder-kernels            2.1.3           py310h5588dad_1    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.1             py310he2412df_2    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2           py310he2412df_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
```

</details>
 
If I do a dev install in that my testing env with the changes at https://github.com/spyder-ide/spyder/pull/16409 Spyder starts (altough I got the rtree missing message due to mixing conda with pip):

![imagen](https://user-images.githubusercontent.com/16781833/158878504-8c2530ec-e3c5-47af-8433-c7050fa1f4ea.png)

**Comment by dalthviz** [comment]
Just in case, I think the unavailable wheels for Python 3.10 are for PyQt <=5.12 on pip. So, installing Spyder which has a dependency on PyQt < 5.13, in Python 3.10 causes the described problem (no way to install Spyder 5.2.2 on Python 3.10 using pip). However https://github.com/spyder-ide/spyder/pull/16409 increases the constraint to PyQt < 5.16 so basically with Spyder 5.3.0 this shouldn't be a problem.

**Comment by ccordoba12** [comment]
> I was able to install PyQt5 with pip on a conda env with Python 3.10.2

This is great news! Thanks for testing!

> Just in case, I think the unavailable wheels for Python 3.10 are for PyQt <=5.12 on pip

Ok, I see. Then I'll close this issue and reference it in PR #16409.
