### ISSUE TITLE
Spyder 5.1.5 and PyQT5 5.12.3 form hangs on exit

### ISSUE THREAD

**Issue by chuckf201** [spyder-ide/spyder#17206]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @chuckf201, thanks for reporting. This information is insufficient for us to help you, sorry. Please fill the details we ask for in the issue template above, so we can better understand your problem. Thanks!

**Comment by chuckf201** [comment]
Code is very basic:
`# -*- coding: utf-8 -*-
"""
Created on Thu Jan 13 09:48:37 2022

@author: monro
"""

import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
class window(QWidget):
   def __init__(self, parent = None):
      super(window, self).__init__(parent)
      self.resize(200,70)
      self.setWindowTitle("PyQt5")
      self.label = QLabel(self)
      self.label.setText("Hello World")
      font = QFont()
      font.setFamily("Arial")
      font.setPointSize(16)
      self.label.setFont(font)
      self.label.move(50,20)
def main():
   app = QApplication(sys.argv)
   ex = window()
   ex.show()
   sys.exit(app.exec_())
if __name__ == '__main__':
   main()
`
* Spyder version: 5.1.5 None
* Python version: 3.8.12 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10
* Anaconda Navigator: 2.1.1
* 
![image](https://user-images.githubusercontent.com/28310563/149851533-78c0a4b8-a7e0-4228-a404-069080f68e7b.png)

I'm seeing Spyder 5.1.5 does not play with PyQT5.12 
I hope you have all you need. I'm new to PyQT5
I can't seem to find a workaround on the web.

**Comment by chuckf201** [comment]
Also, there are no errors. spyder hangs and kernel needs to be rebooted.

**Comment by ccordoba12** [comment]
Please go the menu

    Tools > Preferences > IPython console > Graphics

in the `Backend` option select `Automatic`, then close Spyder and start it again.

If that doesn't help, please comment this line as well

```python
sys.exit(app.exec_())
```

**Comment by chuckf201** [comment]
Backend was already set to automatic.
Commenting out sys.exit does not hang the program but then again it does not run. Returns Ipython prompt without showing a window

**Comment by ccordoba12** [comment]
Ok, I found the problem: please change

```python
sys.exit(app.exec_())
```

to 

```python
app.exec_()
```

That solves the problem for me. The thing is that calling `sys.exit` kills the kernel, so the console hangs and is unable to evaluate more code.

**Comment by chuckf201** [comment]
I know you have a lot on your plate so make mine low priority.
No Fix.
`# -*- coding: utf-8 -*-
"""
Created on Thu Jan 13 09:48:37 2022

@author: monro
"""

import sys
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
class window(QWidget):
   def __init__(self, parent = None):
      super(window, self).__init__(parent)
      self.resize(200,70)
      self.setWindowTitle("PyQt5")
      self.label = QLabel(self)
      self.label.setText("Hello World")
      font = QFont()
      font.setFamily("Arial")
      font.setPointSize(16)
      self.label.setFont(font)
      self.label.move(50,20)
      
def main():
   app = QApplication(sys.argv)
   ex = window()
   ex.show()
   
   app.exec_()
   #sys.exit(app.exec_())
if __name__ == '__main__':
   main()
`

**Comment by ccordoba12** [comment]
Sorry, I'm out of ideas.

**Comment by chuckf201** [comment]
I'll keep at it. I wish I had better troubleshooting tools.

**Comment by chuckf201** [comment]
solved. I added a close function:
`
   def closeEvent(self,event):
       print("closeEvent")
       QApplication.quit()
`
Thanks for your help.

**Comment by ccordoba12** [comment]
Great! I'm glad you were able to find a solution for your problem.
