### ISSUE TITLE
Add spyder-terminal plugin to macOS and Windows installers

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17202]
The macOS installer currently does not incorporate external plugins.
As a first step, attempt to include Spyder Terminal.

**Comment by ccordoba12** [comment]
I think that's a great idea! For now, the only one that it's stable and well maintained (thanks to @steff456) is Spyder-terminal. When Spyder-notebook reaches that level of maturity, we could include it as well.

**Comment by ccordoba12** [comment]
@dalthviz, what do you think about doing the same for the Windows installer?

**Comment by dalthviz** [comment]
Makes sense to me :+1: although in the future maybe we should think in a way for users to install the plugins they want even when using a standalone distribution (some sort of plugin manager that enables the installation of plugins or something like that)

**Comment by mrclary** [comment]
> Makes sense to me 👍 although in the future maybe we should think in a way for users to install the plugins they want even when using a standalone distribution (some sort of plugin manager that enables the installation of plugins or something like that)

I think that would be a great idea. Not sure how to make it work, though, since at present the python packages have to be present in the build environment when the macOS application is bundled. Some time in the future, I should try to install python packages into the Spyder macOS application _after_ it's bundled; if that could work, then it should be pretty straight forward to implement.
