### ISSUE TITLE
Spyder IDE tells me my python version is incorrectly compiled (MAC)

### ISSUE THREAD

**Issue by adityaprakashxx** [spyder-ide/spyder#17201]
I just installed Spyder and the console shows this message:

"This version of python seems to be incorrectly compiled (internal generated filenames are not absolute). This may make the debugger miss breakpoints. Related bug: http://bugs.python.org/issue1666807"

NOTE: I had installed Python a year ago using Atom, but then today, before installing Spyder, I deleted Python and all files related to it. Then, I downloaded latest version of Python from Python's website (3.10.1).

I tried to find a work around for this by going to preferences, Python interpreter, and selecting the interpreter I downloaded, which is named Python IDLE. But, every time I try selecting that, it says invalid file path (/Applications/Python 3.10/IDL

I tried looking this up, but I cannot find something that is beginner-friendly. Can someone help me understand what is causing this?

**Comment by ccordoba12** [comment]
Hey @adityaprakashxx, thanks for reporting. You said:

> I just installed Spyder and the console shows this message

You can safely ignore that message. We'll avoid showing it in our next version (5.2.2), to be released at the end of the week.

> I tried to find a work around for this by going to preferences, Python interpreter, and selecting the interpreter I downloaded, which is named Python IDLE

You need to select the Python executable, not the IDLE one. @mrclary, do you know the path to it inside Python's official macOS installers?

**Comment by andreamoro-git** [comment]
This message has resurfaced with a recent version of spyder

* Spyder version: 5.4.3 b6abc3d30 (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Darwin 21.6.0

**Comment by ccordoba12** [comment]
@andreamoro-git, that's true (see issue #20800). We'll fix this new problem in our next version (5.4.4), to be released in June. In the meantime, I think you can downgrade to 5.4.2 to avoid it.
