### ISSUE TITLE
Vertical line indicating max line length in Editor reverts to default value when Spyder is restarted

### ISSUE THREAD

**Issue by djpine** [spyder-ide/spyder#17223]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The vertical line indicating the maximum line length in the Editor reverts to the default length value after Spyder is restarted.  The (nondefault) value is still correctly displayed in the Preferences panel (Preferences : Completion and linting : code style and formatting : Maximum allowed line length), but is not correctly displayed in the Editor.

### What steps reproduce the problem?

1. Set and reset Maximum allowed line length to different values several times
2. Restarted Spyder several times

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.7
* Qt version: 5
* PyQt version: 5.9.2
* Operating System name/version: macOS Monterey Version 12.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @djpine, thanks for reporting. This is fixed in our latest version (5.2.1), which is not available in Anaconda yet.

I'm sure they'll upload a new version for it soon.
