### ISSUE TITLE
When typing code in spyder version 5 it is lagging so hard!

### ISSUE THREAD

**Issue by RandyChen233** [spyder-ide/spyder#17229]
I recently upgraded from Spyder version 4 to version 5, and all of a sudden when I type stuff in the Spyder editor, it feels extremely laggy: stuff don't show up on the screen as I am typing them. I had no issues at all when using Spyder 4, and my computer has 16 GB of ram and intel i5-9700K GPU, so I don't think it's my computer that's causing the issue. Is there some incompatibility between Windows 10 and Spyder version 5?

**Comment by ccordoba12** [comment]
You can install 5.2.2 by using our Windows or Mac installers:

https://github.com/spyder-ide/spyder/releases/tag/v5.2.2

**Comment by ccordoba12** [comment]
Closing due to lack of response.
