### ISSUE TITLE
I am new to Python & Github. I can´t use pandas on Spyder

### ISSUE THREAD

**Issue by newbieinpython2000** [spyder-ide/spyder#17243]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1.  I create a new scrypt and import pandas as pd
2.  I create a list 
3.  I tried using "pd.Series()" but it doesn't work. (It does in IPython & Google Colab)

### What is the expected output? What do you see instead?
This is the code:

import pandas as pd
Students = ["gino", "ignacio", "loreto"]
pd.Series(Students)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @newbieinpython2000, thanks for reporting. Please post a screenshot of what you see in Spyder and Colab to understand your problem because I don't know what's the result you expect to see in Spyder.

**Comment by newbieinpython2000** [comment]
Thank you for your quick response. 

This what I see in Spyder:
![spyder](https://user-images.githubusercontent.com/98430455/151264041-445f8ba0-6bac-43ee-b23a-aa4ece24f310.jpg)


This is what I see in Colab (this is what I was trying to get on Spyder)
![colab](https://user-images.githubusercontent.com/98430455/151264218-193e3781-d8c3-4c81-9307-44f1d4524fe0.jpg)

**Comment by athompson673** [comment]
Google colab runs an IPython notebook environment whereas spyder by default runs more like running python in a command prompt. When you create the `pd.Series`, and then do nothing with it, IPython assumes you might want to `print` the result, but regular python makes no such assumption (and therefore does not print it out). There is no error here, just a slightly different mode of operation to get used to. You should probably save the result of `pd.Series` to a variable, and call `print` using that variable..

**Comment by ccordoba12** [comment]
@athompson673 is right. You need to change your last line to be

```python
print(pd.Series(Students))
```

to see the same result in Spyder's IPython console that the one you get in Colab.
