### ISSUE TITLE
Cannot uninstall this version of spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1724]
_From [tian.tia...@gmail.com](https://code.google.com/u/109441067378537799957/) on 2014-02-07T02:10:37Z_

Spyder Version:  2.2.5
Python Version:  2.7.3
Qt Version    :  4.8.1, PyQt4 (API v1) 4.9.1 on Linux
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  None (NOK)
rope >=0.9.2    :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
matplotlib >=1.0:  None (NOK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1.Ubuntu software center to remove it and it shows that it is removed.  However, the spyder app is still there
2.Used synaptics to remove and spyder is still not removed 3. What is the expected output? What do you see instead? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1724_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-02-07T05:03:13Z_

There are several important dependencies missing so I really doubt that that version was installed using synaptics. What's the result of this command in a console

which spyder

**Comment by spyder-issues-migrator** [comment]
_From [tian.tia...@gmail.com](https://code.google.com/u/109441067378537799957/) on 2014-02-10T20:32:21Z_

I did not install using synaptics, but I tried to uninstall it using
synaptics.  I had to do a clean wipe of harddrive to get rid of the spyder.
 So for now, the problem is resolved.

**Comment by ccordoba12** [comment]
Closing because this issue is solved according to the OP.
