### ISSUE TITLE
Cannot switch from ipython_console to editor using Keyboard shortcuts

### ISSUE THREAD

**Issue by fractalclockwork** [spyder-ide/spyder#17244]
### What steps will reproduce the problem?

Enter the ipython_console and press ‘Ctrl+Shift+E’.  Rather than switching to the editor, an ‘e’ is typed into the console.  Reassigning the shortcut to another key works around the issue, ie ‘Ctrl+Shift+Y’ allows you switch to the editor from the ipython_console. Tested on Ubuntu.20.04.

## Versions

* Spyder version: 3.3.6 
* Python version: 3.8.10
* Qt version: 5.12.8
* PyQt5 version: 5.14.1
* Operating System: Linux 5.4.0-96-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.15.2 (OK)
psutil >=0.3      :  5.5.1 (OK)
nbconvert >=4.0   :  5.6.1 (OK)
pandas >=0.13.1   :  1.2.2 (OK)
numpy >=1.7       :  1.20.1 (OK)
sympy >=0.7.3     :  1.7.1 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  5.0.3 (OK)
IPython >=4.0     :  7.13.0 (OK)
matplotlib >=2.0.0:  3.3.4 (OK)
pylint >=0.25     :  2.4.4 (OK)
```

**Comment by ccordoba12** [comment]
Hey @fractalclockwork, thanks for reporting. This is no longer a problem in our latest version (5.2.2), released last week. Spyder 3.3.6 was released in July 2019, so it's more than two years old now.

Please update by using either Anaconda or pip in a virtualenv,
