### ISSUE TITLE
Is installing spyder from spyder-ide conda channel recommended?

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder#17242]
Hi,

I noticed that spyder 5.2 is missing from `spyder-ide` conda channel but is present on `conda-forge`. Is `spyder-ide` channel still supported / recommended?

**Comment by ccordoba12** [comment]
No, the spyder-ide channel is not maintained anymore.

**Comment by ccordoba12** [comment]
Please use conda-forge instead.

**Comment by mmagnuski** [comment]
Ok, thanks!

**Comment by Dan-Patterson** [comment]
Clarification please, is ... https://anaconda.org/anaconda/spyder ... still being maintained? albeit, it is slow.

**Comment by ccordoba12** [comment]
Yes, it is, although not by us but by Anaconda, the company.
