### ISSUE TITLE
Doesnt have the Spyder-kernels module or right version DESPITE having it already installed

### ISSUE THREAD

**Issue by alialta2** [spyder-ide/spyder#17257]
### What steps will reproduce the problem?

Windows 10, 64bit
Uninstalled Python, Spyder, Miniconda and deleted temp files & remaining folders (installation folders and appdata).

Installed Spyder and Miniconda. 
Ran the following on Miniconda prompt: 
conda create -n spyder-env -y
conda activate spyder-env
conda install spyder-kernels scikit-learn -y
conda install spyder‑kernels=2.2

Opened Spyder, selected the path to python as: 
C:\Users\<username>\Miniconda3\envs\spyder-env\python.exe

And I still get the error

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @alialta2 thank you for the feedback! For Spyder 5.2.2 you will need to have spyder-kernels 2.2.1 . Could you try running this in your env? :

      conda install spyder-kernels=2.2.1 -c conda-forge

Let us know if that helps!

**Comment by tyers** [comment]
Hi, Is it possible to get this information added [here](https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html#spyder-kernels-not-installed-incompatible) or at least include the required spyder-kernels version in the release notes for each release?
The list of spyder versions listed in that troubleshooting page only covers up to version 5.1.5.
Thanks

**Comment by tyers** [comment]
> 

done: https://github.com/spyder-ide/spyder-docs/issues/307

**Comment by dalthviz** [comment]
Closing due to lack of response. Also, the docs where updated
