### ISSUE TITLE
open/close note

### ISSUE THREAD

**Issue by AffDk** [spyder-ide/spyder#17258]
### What steps will reproduce the problem?

I have some notebooks on my OneDrive so when I try to open them, it does not get access to them and shows "Page not found" and when I try to close them it makes this crash.

### Traceback
```python-traceback
  File "C:\Users\afsamani\Anaconda3\envs\filternet\lib\site-packages\spyder_notebook\notebookplugin.py", line 387, in close_client
    client.shutdown_kernel()
  File "C:\Users\afsamani\Anaconda3\envs\filternet\lib\site-packages\spyder_notebook\widgets\client.py", line 255, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Users\afsamani\Anaconda3\envs\filternet\lib\site-packages\spyder_notebook\widgets\client.py", line 248, in get_kernel_id
    notebook_path = session.get('notebook', {}).get('path')
AttributeError: 'str' object has no attribute 'get'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 404, 'json': {'message': 'Not Found', 'documentation_url': 'https://docs.github.com/rest/reference/issues#create-an-issue'}}
```

## Versions

* Spyder version: 3.3.6 
* Python version: 3.7.4
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.2.0 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.15.1 (OK)
nbconvert >=4.0   :  5.6.0 (OK)
pandas >=0.13.1   :  0.25.1 (OK)
numpy >=1.7       :  1.16.5 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.13 (OK)
qtconsole >=4.2.0 :  4.5.5 (OK)
IPython >=4.0     :  7.8.0 (OK)
matplotlib >=2.0.0:  3.1.1 (OK)
pylint >=0.25     :  2.4.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @AffDk, thanks for reporting. Unfortunately, you're using a very old Spyder version (3.3.6), which we don't support anymore. Besides that, our latest version (5.2.2) doesn't work with Spyder-notebook. But that will be solved in the next couple of months.

So, for now you can't use Spyder-notebook, sorry. Please try again in a couple of months and report back if the problem persists here:

https://github.com/spyder-ide/spyder-notebook

**Comment by AffDk** [comment]
Thanks for the info.
Fine but if I only copy those files somewhere other than oneDrive, at least I can open and close them in spyder-notebook but when they are on the OneDrive, I cannot open them (page not found message) and if I try to close them, the crash occurs.

Best regards
