### ISSUE TITLE
Is there an option to reopen a closed console?

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder#17255]
I accidentaly closed a console that was running computations that take some time. Is there an option to reopen the closed console? (I looked around in the docs and issues to find answer to this but I couldn't)
If not - it might be good idea to ask the user for confirmation (like when one tries to restart the console kernel).

**Comment by dalthviz** [comment]
Hi @mmagnuski thank you for the feedback! Checking we have an option to ask the user for confirmation when closing but I think is not activated by default. To activate it you will need to go to `Preferences > IPython Console > DIsplay > Interface` and check there the `Ask for confirmation before closing` option:

![imagen](https://user-images.githubusercontent.com/16781833/151562516-991da384-462c-45bb-b414-b48e18ed2abb.png)

Let us know if that helps!

**Comment by ccordoba12** [comment]
To complement @dalthviz answer above, I'd like to say that this

> Is there an option to reopen the closed console?

is not possible. When you close a console, its associated kernel is killed. So it's not possible to recover the computations you were running on it.

**Comment by mmagnuski** [comment]
Thanks @dalthviz and @ccordoba12, I'll set this option! 

> When you close a console, its associated kernel is killed. So it's not possible to recover the computations you were running on it.
Thanks, that's what I thought, because CPU usage dropped after I closed the console. But it's good at the same time - I can use this to circumvent the problem with resetting kernel I have. :)
