### ISSUE TITLE
Split Vertical and Horizontally are switched

### ISSUE THREAD

**Issue by RCJoergensen** [spyder-ide/spyder#17269]
### What steps will reproduce the problem?

The two functions "Split Horizontally" and "Split Vertically" are switched. When selecting "Split Horizontally", the screen is split vertically, and when "Split Vertically" is selected, it is split Horizontally. The icon of the corresponding functions is however correct, meaning the icon of the "Switch Horizontally" actually indicates a vertical split and vise versa.

Steps to reproduce:
1) Go to the menu "View" and select category "Windows Layout"
2) Select "Split Horizontally"

OR

1) Right click a tab with a script
2) Select "Split Horizontally"

Expected outcome: The screen is split horizontally

Actual outcome: The screen it split vertically

**Comment by ccordoba12** [comment]
Hey @RCJoergensen, thanks for reporting. We consider this is a matter of expectations (i.e. how everyone understands horizontal and vertical splits).

However, the icons we use for those actions are quite explicit about the resultant behavior:

![imagen](https://user-images.githubusercontent.com/365293/151815238-fffe93cb-7dfc-4087-b3d8-24a2690099fe.png)

so we don't plan to change this.
