### ISSUE TITLE
On save the spinner start but it is not saved

### ISSUE THREAD

**Issue by Mte90** [spyder-ide/spyder#17291]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

![Screenshot_20220203_172501](https://user-images.githubusercontent.com/403283/152385106-2a74f2ec-2fa5-4831-839a-bda9aa0398be.png)

Edit a file and save but there is no feedback of errors (in console or with a window) and the spinner is still moving after minutes.

### Paste Traceback/Error Below (if applicable)
I have the debian package for this one

```python-traceback
>>> /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.10
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version: debian sid

**Comment by Mte90** [comment]
So I had an idea about the issue.
My black installation wasn't working. So my guess is that spyder-ide on save was awaiting an output and was listening also if black was crashing for a missing package.

**Comment by ccordoba12** [comment]
> My black installation wasn't working. So my guess is that spyder-ide on save was awaiting an output and was listening also if black was crashing for a missing package.

Yeah, I think that's basically the problem. Did it get fixed after you updated Black or `python-lsp-black`?

**Comment by Mte90** [comment]
Fixed after update black.

I think that in those cases spyder should show some alerts as I had to check a lot of things to inf the real issue.

**Comment by ccordoba12** [comment]
> Fixed after update black.

Great!

> I think that in those cases spyder should show some alerts as I had to check a lot of things to inf the real issue.

We show a message to tell users that their dependencies are outdated, but unfortunately the latest Black came up with a breaking change after our latest version.

Closing then as this fixed now.
