### ISSUE TITLE
An error ocurred while starting the kernel


### ISSUE THREAD

**Issue by antonio-casares** [spyder-ide/spyder#17296]
### What steps will reproduce the problem?

I use Ubuntu 20.04. 

1. Update Spyder to Spyder 5.5.2 using pip install spyder==5.2.2

2. Open Spyder3 or Spyder 5.2.2

In the console it appears:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/home/acasaressant/.local/lib/python3.8/site‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/home/acasaressant/.local/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/acasaressant/.local/lib/python3.8/site‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/acasaressant/.local/lib/python3.8/site‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/home/acasaressant/.local/lib/python3.8/site‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/home/acasaressant/.local/lib/python3.8/site‑packages/ipykernel/kernelapp.py", line 33, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)

I tried to uninstall Spyder and re-install it, but the problem persists.

## Versions

* Spyder version: 5.2.2 
* Python version: 3.8.10
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.13.0-28-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.13.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.7.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.3.1 (OK)
pylint >=2.5.0                :  2.7.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.7.1 (OK)
sphinx >=0.6.6                :  1.8.5 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  18.1.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.20.1 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.7.0 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @antonio-casares, thanks for reporting. Please create a virtualenv that doesn't use your system packages.

These lines in your error message above

    File "/home/acasaressant/.local/lib/python3.8/site‑packages/ipykernel/kernelapp.py", line 33, in
    from traitlets.utils import filefind
    ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)

show that the ipykernel package in your virtualenv is trying to import the `trailets` one installed by your distro (which seems outdated).

Another option is for you to run

    pip install -U trailets

in your virtualenv.
