### ISSUE TITLE
Jellyfish requirement through bioconda vs conda-forge

### ISSUE THREAD

**Issue by yotamcons** [spyder-ide/spyder#17304]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After installing a fresh conda environment with spyder 5, i get a "You have missing dependencies" popup regarding jellyfish>=0.7.8, even though `conda list jellyfish`  returned i have jellyfish 2.2.10 through the bioconda channel.
After frustrated digging i found out the channel[ bioconda has a package named jellyfish](https://anaconda.org/bioconda/jellyfish) that is different from [the jellyfish package in conda-forge](https://anaconda.org/conda-forge/jellyfish).

Is there a way for the installation of spyder to assert it gets the right package, while still using an environment.yml with bioconda as the highest priority channel (example attached)?

### What steps reproduce the problem?

1. Have bioconda in higher priorety than conda-forge in your channel's list 
2. conda install spyder

Workaround:
`conda install jellyfish -c conda-forge` to explicitly select the right source for bioconda

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.10
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: MacOS 12.1

[environment.yml.txt](https://github.com/spyder-ide/spyder/files/8010318/environment.yml.txt)

**Comment by ccordoba12** [comment]
Hey @yotamcons, thanks for reporting. You said:

> Is there a way for the installation of spyder to assert it gets the right package, while still using an environment.yml with bioconda as the highest priority channel (example attached)?

No, I don't think that's possible. The only solution I see is for you to report this problem to the bioconda maintainers, so they rename their Jellyfish package to something else, so it doesn't get picked up by Spyder.

The other solution is to use conda-forge to install Spyder in a dedicated environment and then use bioconda to install the packages you need from it in another one. Then you can connect Spyder to that environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
