### ISSUE TITLE
Font outside the code quite small in Spyder

### ISSUE THREAD

**Issue by PBerit** [spyder-ide/spyder#17308]
Hi all,

the font outside the code is quite small in Spyder 5.1.5. How can I increase it because it is quite difficult to read. I have attached a screenshot and marked the relevant parts yellow. The font of the code itself is okay. 
<img width="960" alt="Screenshot_Spyder" src="https://user-images.githubusercontent.com/90847641/152830603-9438fa85-ccdb-41ba-bab6-072f5b351470.PNG">

**Comment by steff456** [comment]
Hi @PBerit,

You can go to `preferences > appearance > fonts` and modify them as needed. Let me know if this works.

**Comment by PBerit** [comment]
@steff456: Thanks Steff for your answer. Unfortunately it did not work. While I can adjust the size of the font of the code, the marked fonts in my screenshot remain the same, no matter how I change the options "Plain text" and "Rich text".

**Comment by PBerit** [comment]
@steff456 : Thanks Steff for your answer. What do you mean by modiying my font size in the system preference? Actually the font looks quite normal in every other application except for Spyder. So even if this changed something, it would have side effects on all other applications. So the font should be changed within Spyder. Is this not possible?

**Comment by steff456** [comment]
I think we are using the same as your system, which if you modify then it will change in all other apps, and if the fonts in preference didn't made an effect I think it is not possible to increase/decrease of just those elements right now.

**Comment by steff456** [comment]
Can you let me know what form of installation did you used? I'm also seeing a couple of things off

**Comment by PBerit** [comment]
@steff456: Thanks Steff for your answers. I use Anaconda in Windows Server 2016 and Spyder 5.1.5. I tried to change the options for DPI setting but it did not have any effect.

**Comment by PBerit** [comment]
@steff456 : I just restarted the machine and now it looks good. Thanks for your help and effort Steff. I really appreciate it.
