### ISSUE TITLE
How to change Debug to run in the current console after accidentally closing the settings window when first using Debug?

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder#17306]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi,  
a quick question for now - where is it possible to find the debugger settings where there are options like "run in the current console" etc.? These are the settings that show up in a pop-up window the first time one chooses "Debug" option. I couldn't find where to find these options in [the docs](https://docs.spyder-ide.org/5/panes/debugging.html).  
  
I closed this settings window when it popped up the first time (either via "Cancel" or the "x" button, I don't know which one) because I noticed I wanted to change something before debugging. However, the default options were saved as if the were accepted, and I can't change the debugger to run in the current console now.  

If I go to `Preferences -> IPython console -> debugger tab` I can't find this option. In `Preferences -> Run` I have "execute in current console" selected, the same option is checked if I investigate file-specific run settings. But when I run debugging I get a NameError complaining that a variable is missing, that is present in the current console. 

## Versions
* Spyder version: 5.2.2
* Python version: 3.9.9 64-bit
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Windows 10

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.1 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @mmagnuski, thanks for reporting. You said:

> a quick question for now - where is it possible to find the debugger settings where there are options like "run in the current console" etc.?

They are find in the menu `Run > Configuration per file`. Running and debugging a file share the same settings.

**Comment by ccordoba12** [comment]
You also said:

> But when I run debugging I get a NameError complaining that a variable is missing, that is present in the current console.

Please post that message.

**Comment by mmagnuski** [comment]
@ccordoba12 This is an ordinary NameError claiming that `lfp` variable is undefined. However that variable is defined in the relevant console and the `Run > Configuration per file` is set to execute in the current console, so it looks like this setting is ignored. I will try to reproduce this on a separate computer (and after Spyder restart) later on and will let you know.

**Comment by mmagnuski** [comment]
@ccordoba12 For more context:

below you can see that I have the file set to run in the current console and that the variable is defined in that console:
![spyder_debug_bug_01](https://user-images.githubusercontent.com/8452354/152857260-e703bd2c-8a15-4a30-b9b0-d9d56519d96a.PNG)

after running that file in Debug however I get information that the variable is not defined, as if the console was cleared before running the file in debug mode.
![spyder_debug_bug_02](https://user-images.githubusercontent.com/8452354/152857417-bf8e7b4b-1fd6-46f2-9eee-ea91dd57b67a.PNG)

after exiting the debug mode the variable is still there:
![image](https://user-images.githubusercontent.com/8452354/152857533-caa54a50-3d8d-4310-90f0-0cfd491dffa1.png)
