### ISSUE TITLE
The window layout changes as soon as the application starts

### ISSUE THREAD

**Issue by ayismass** [spyder-ide/spyder#17303]
### What steps will reproduce the problem?

Once I restart Spyder, the window layout will change always.

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.7
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.8.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.27 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.2 (OK)
pandas >=1.1.1                :  1.4.0 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @ayismass, thanks for reporting. Could you post a video of what you mean by this problem? To be honest, I don't understand very well what you're talking about.

**Comment by ayismass** [comment]
Hi,@ccordoba12, thanks for your reply. 
When I open the Spyder, the layout as follows:
![fig1](https://user-images.githubusercontent.com/92130540/152711281-a7c31393-a6ea-46b0-a632-0263a1ef5df2.png)
Then,  I use Ctrl+Shift+F5 to change the layout of Spyder as follows:
![fig2](https://user-images.githubusercontent.com/92130540/152711296-eebf1bb2-4f5f-4567-a992-1bb219854023.png)
but when I restart Spyder, the layout isnt saved successfully, and change like following:
![fig3](https://user-images.githubusercontent.com/92130540/152711306-3dcf9aa3-fdd6-4db5-b480-6cd5d303e8b7.png)

**Comment by ccordoba12** [comment]
Thanks @ayismass! I understand your problem much better now. Although not exactly the same, I think this problem is closely related to issue #16930, so I'm going to close it in favor of that one.

I hope we can fix it in the following months.
