### ISSUE TITLE
How do I take out text cursor indicator

### ISSUE THREAD

**Issue by Griffinov22** [spyder-ide/spyder#17318]
### What steps will reproduce the problem?

Text cursor indicator when it highlights a single letter is throwing me off and I can't edit my code because I end up deleting the whole word!

**Comment by ccordoba12** [comment]
Hey @Griffinov22, thanks for reporting. I don't quite understand what you mean by this.

Could you post a screenshot or, even better, a video about what annoys you? Thanks!

**Comment by Griffinov22** [comment]
Thanks for your quick response too! Much appreciated.

**Comment by ccordoba12** [comment]
I don't understand. That's a screenshot of Notepad, not Spyder. But if the same problem is happening in Spyder, then it means it's an issue with your system because it appears in several applications (not just Spyder).

**Comment by ccordoba12** [comment]
Closing due to lack of response.
