### ISSUE TITLE
using tab to auto-complete

### ISSUE THREAD

**Issue by carlord** [spyder-ide/spyder#17327]
### What steps will reproduce the problem?

he i try to use tab to auto complete a word in ipython console

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/usr/lib/python3.10/site-packages/qtconsole/jupyter_widget.py", line 178, in _handle_complete_reply
    self._complete_with_items(cursor, matches)
  File "/usr/lib/python3.10/site-packages/qtconsole/console_widget.py", line 1072, in _complete_with_items
    self._completion_widget.show_items(cursor, items,
  File "/usr/lib/python3.10/site-packages/qtconsole/completion_widget.py", line 107, in show_items
    point = self._get_top_left_position(cursor)
  File "/usr/lib/python3.10/site-packages/qtconsole/completion_widget.py", line 171, in _get_top_left_position
    point.setY(point.y() + y)
TypeError: setY(self, int): argument 1 has unexpected type 'float'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.10.2
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Linux 5.16.7-200.fc35.x86_64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  21.8.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.2 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.0 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.4                 :  0.9.4 (OK)
setuptools >=49.6.0           :  57.4.0 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.1 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @carlord, thanks for reporting. This is fixed in Qtconsole version 5.2.2 (one of our dependencies), released two months ago and you're using 5.1.1.

Please ask your distro maintainers to update to that version because there's nothing else we can do about it.

**Comment by carlord** [comment]
Your recommendation only lead me to more issues and a broken IDE, from an
annoying issue to a huge issue.

If you'll no help better not reply with an un-tested solution.

**Comment by ccordoba12** [comment]
The solution is tested not only by me but by other users as well, as you can read here:

https://github.com/spyder-ide/spyder/issues/17314#issuecomment-1034801296

Of course, if you used `sudo pip install -U spyder` instead of a virtualenv to update to our latest version, then you broke not only Spyder but also your distro. In that case you should know that one of most harmful things you can do on Linux is to mix pip and distro packages because they are compiled differently and sometimes work differently as well.

Furthermore, I didn't say that you have to update. My only advice was this (and you can read it very clearly in my comment above):

> Please ask your distro maintainers to update to that version because there's nothing else we can do about it.

So if you didn't do that but when ahead and forcibly tried to update, that's up to you, sorry.

**Comment by carlord** [comment]
Thanks for the feedback!
