### ISSUE TITLE
5.2.2 errors when installing optional dependencies

### ISSUE THREAD

**Issue by bakj1979** [spyder-ide/spyder#17324]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After installing Spyder 5.2.2 through conda in a new environment, when I add any optional dependency and restart, LSP will not connect, no conda interpreter is recognised and the console indicated Restarting Kernel (which never restarts). As soon as I remove the optional dependency (e.g. numpy or matplotlib), Spyder works as normal.

I have already tried all the steps set out in this thread without success: https://github.com/spyder-ide/spyder/issues/16765 

### What steps reproduce the problem?

1. install spyder in new conda environment
2. install numpy (or matplotlib) via conda (conda install numpy)
3. restart spyder 

### What is the expected output? What do you see instead?
lsp and kernel connected

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.10
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: MaxOS Monterey

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  8.0.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  22.3.0 (OK)
nbconvert >=4.0               :  6.4.1 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.8.1 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.22.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @bakj1979, thanks for reporting. Please post the exact commands you used to install our 5.2.2 version and to add optional dependencies. That will help us to understand your problem better.

**Comment by bakj1979** [comment]
Hello,

Here is the command to create the new environment with optional dependencies:

conda create -n spyder_env spyder=5.2.2 numpy scipy pandas matplotlib sympy cython

**Comment by ccordoba12** [comment]
Are you using the conda-forge channel? Just checking to be sure.

**Comment by bakj1979** [comment]
Yes, I am using conda-forge.

**Comment by ccordoba12** [comment]
Ok, then please go to this entry in the File menu

![imagen](https://user-images.githubusercontent.com/365293/138761482-598fa96c-13f8-4dde-ae9a-e18ac20a7c69.png)

and select `Verbose`:

![imagen](https://user-images.githubusercontent.com/365293/138761597-e833892d-888c-4e93-99fd-6acf98dde1cc.png)

After Spyder restarts, go to the `Tools > Debug logs` menu

![imagen](https://user-images.githubusercontent.com/365293/138761756-2af03a24-21c6-47bb-8354-1f2ec87a1e83.png)

open those three files and upload them here.

*Note*: The numbers at the end of `server_python` and `transport_python` will be different in your case. Don't worry about it.

**Comment by bakj1979** [comment]
Hi,

When I go to "restart in debug mode" bug mode, spyder does not restart. Then if I restart through Terminal, I do not have "debug logs" as a choice under Tools.

**Comment by ccordoba12** [comment]
> When I go to "restart in debug mode" bug mode

This is strange but you can start Spyder in debug mode on a terminal with this command:

    spyder --debug-info verbose --debug-output file

and then going to `/Users/<your user>/.spyder-py3` to find and upload these files:

    spyder-debug.log
    lsp_logs/server_python_xxxx.log
    lsp_logs/transport_python_xxxx.log

**Comment by bakj1979** [comment]
I'm only getting the debug log, not the other two.
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/8055996/spyder-debug.log)

**Comment by ccordoba12** [comment]
The Language server logs are placed here, according to this log

    /Users/<your user>/.spyder-py3/lsp_logs/server_python_29661.log

without them I'm afraid I can't help you further (the only thing I'm seeing in this log is that server didn't start).

**Comment by bakj1979** [comment]
Here are the missing files.

**Comment by ccordoba12** [comment]
You need to upload them on Github directly, you can't send them via email.

**Comment by bakj1979** [comment]
I should have checked before sending, but both files are empty.

**Comment by ccordoba12** [comment]
> I should have checked before sending, but both files are empty.

That's bad news because (as I said) I can't help you further without additional info.

Do you have PYTHONPATH set somewhere? That could explain the failure (that's my last idea).

**Comment by bakj1979** [comment]
On additional point: Spyder works as expected without the optional dependencies.

So isn’t a bit strange that adding them is causing the issue?

**Comment by bakj1979** [comment]
Do you mean outside of the environment in which I installed Spyder?

(base) ***@***.*** ~ % conda activate finpy_spyder
(finpy_spyder) ***@***.*** ~ % which python
/Users/jeffreybaker/opt/miniconda3/envs/finpy_spyder/bin/python
(finpy_spyder) ***@***.*** ~ % python
Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:38:53) 
[Clang 11.1.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by ccordoba12** [comment]
> So isn’t a bit strange that adding them is causing the issue?

Sure, something seems to be interfering with the Python language server, but without the logs is not possible to know what that is.

> Do you mean outside of the environment in which I installed Spyder?

Yes. Please run `echo $PYTHONPATH` after activating your `finpy_spyder` env to check.

**Comment by bakj1979** [comment]
ECHO $PYTHONPATH is returning a blank line, which I’m guessing is the source of the problem, however I still do not understand how I can run Spyder without the optional dependencies in this case.

**Comment by ccordoba12** [comment]
> ECHO $PYTHONPATH is returning a blank line

That's fine (it'd be a problem if it had returned something).

> however I still do not understand how I can run Spyder without the optional dependencies in this case.

Me neither, but I have no more ideas to offer, sorry. So I'm going to close this issue and wish you good luck trying to find the problem.
