### ISSUE TITLE
Kite plugin not working

### ISSUE THREAD

**Issue by Marc-Dittner** [spyder-ide/spyder#17337]
### What steps will reproduce the problem?

Installed spyder via Anaconda3-2021.11-Windows-x86_64.exe.
The installed Kite via Spyder suggestion fopr installing plugin.
Now via preferences -> Completion and linting -> Advanced -> !Kite options are not showing up!

**Comment by ccordoba12** [comment]
Hey @Marc-Dittner, thanks for reporting. Kite stop being maintained last year and now it's not even available for download. Unfortunately, there's nothing we can do about it because Kite was developed as a commercial product by a company which was acquired by another one.
