### ISSUE TITLE
Spyder freezes when entering in debug mode

### ISSUE THREAD

**Issue by lbosk** [spyder-ide/spyder#17334]
# Problem Description
When launching a debug session (ctrl+F5) the kernel console freezes at the first line

### What steps reproduce the problem?
1. conda create --name newenv python=3.9.5
2. conda activate newenv
3. conda install spyder (5.1.5 and all its dependancies are installed)
4. spyder
5. ctrl-F5 (even from the default empty project)

### What is the expected output? What do you see instead?
The code should be executed and the prompt appear again.
Instead, the console freezes at the first line, the prompt does not appear anymore and you must restart the kernel to have it back again
![Cattura2](https://user-images.githubusercontent.com/84093075/153750439-d1381640-48a6-4399-a05c-833676c2e908.PNG)

I tried with both options "Execute in current console" and "Execute in a dedicated console"

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.5 (but I tryed with different versions 3.8.x and 3.9.x with the same result)
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64-bit

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)

**Comment by lbosk** [comment]
Maybe a further useful information:
My Anaconda base environment has the very same versions of Spyder, Qt, PyQt and all dependancies (only Python differs 5.9.7) and there the problem does not happen.

If I clone the base and downgrade python:
1. conda create --name myclone --clone base
2. activate myclone
3. conda install python=3.9.5
4. spyder
5. ctrl+F5
Now the two environments are apparently identical but the problem does not appear whis way!
(My problem is that I cannot proceed like that because the base environment is so overcrowded of packages that I cannot resolve the environment to install tensorflow)

**Comment by lbosk** [comment]
I probably was able to delimit the problem: it is somewhere in qtconsole-5.2.2
in fact the following command fixes it:
conda install qtconsole=5.1.1

**Comment by ccordoba12** [comment]
Hey @lbosk, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your base environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by danielsvedberg** [comment]
> conda install qtconsole=5.1.1
Just wanted to say thanks and confirm that this worked for me too.

**Comment by HornetGuppy** [comment]
I have ran into same issue (Python 3.8.10 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Windows 10).. I have used standalone windows spyder installer and then connected to my virtual environment. It works when I do F5 it but freezes during debugging mode.
Unfortunately pip install qtconsole==5.1.1 doesnt work either..
What am I missing?

**Comment by ccordoba12** [comment]
@HornetGuppy, this problem should be fixed in our latest version (5.3.2). If you're using an older one, please update.

**Comment by FrankBerthiaume** [comment]
@ccordoba12, Hi, I just installed Spyder 5.3.2 from the windows installer and am unfortunately running in the same problem as @HornetGuppy. I also have Python 3.8.10 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Windows 10. I am running Spyder in my virtual environment, not based on a conda dist. 

 I can run the file with F5 without problem but get stuck at the first line when lunching the debugger. Seems like the update might still has this problem unresolved, thanks!

**Comment by HornetGuppy** [comment]
@ccordoba12 Apologies, forgot to mention my spyder version is indeed 5.3.2 (standalone)

**Comment by ccordoba12** [comment]
@HornetGuppy and @FrankBerthiaume, please wait until 5.3.3 is released next week and try again. We fixed a couple of bugs during the last couple of weeks that could solve your problem.

If the problem persists, please continue the discussion on issue #19174. This issue is quite old and not related to the current bug.

**Comment by HOMGH** [comment]
> I probably was able to delimit the problem: it is somewhere in qtconsole-5.2.2 in fact the following command fixes it: conda install qtconsole=5.1.1

Worked for me. You're a life saver!
Thank youuu.

**Comment by ccordoba12** [comment]
@HOMGH, great! Thanks for letting us know about it.
