### ISSUE TITLE
Ask me to install spyder-kernels, but doesn't work after the installation

### ISSUE THREAD

**Issue by miraboreasumr** [spyder-ide/spyder#17339]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The Python environment or installation whose interpreter is located at

C:\Users\miraboreasu\Miniconda3\envs\spyder‑env\python.exe

doesn't have the spyder‑kernels module or the right version of it installed (>= 2.2.1 and < 2.3.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    conda install spyder‑kernels=2.2
or
    pip install spyder‑kernels==2.2.*

I  tried conda install spyder‑kernels=2.2, but still have this, and reset the IDE, it doesn't work

I would like to say more, I have tried VSCode, Pycharm. I really like Spyder, since it is the one when I just started learning Python back in the old days. But I don't know why this happened, since I used to use prompt in Tools, but now it has gone, anyway, please help me 

### What steps reproduce the problem?

1. Download the latest version from https://www.spyder-ide.org/
2. Use miniconda to create a new environment following https://docs.spyder-ide.org/5/faq.html#using-packages-installer
3. Then when I change the preference and restart the spyder, this happened

### What is the expected output? What do you see instead?

https://ibb.co/3hNH4W3

The Python environment or installation whose interpreter is located at

C:\Users\miraboreasu\Miniconda3\envs\spyder‑env\python.exe

doesn't have the spyder‑kernels module or the right version of it installed (>= 2.2.1 and < 2.3.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    conda install spyder‑kernels=2.2
or
    pip install spyder‑kernels==2.2.*
### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Just download the lastest one today
* Python version: 3.9.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Win10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by steff456** [comment]
Hi @miraboreasumr,

I'm seeing you are using windows, can you try to use our windows installer available here: https://github.com/spyder-ide/spyder/releases/tag/v5.2.2 and see if your problem is resolved?

Please don't forget to uninstall Spyder from conda.

**Comment by miraboreasumr** [comment]
> Hi @miraboreasumr,
> 
> I'm seeing you are using windows, can you try to use our windows installer available here: https://github.com/spyder-ide/spyder/releases/tag/v5.2.2 and see if your problem is resolved?
> 
> Please don't forget to uninstall Spyder from conda.

Hello, I did use the Windows installer.

**Comment by steff456** [comment]
Did you solved the issue you were having with the installer?

**Comment by miraboreasumr** [comment]
> Did you solved the issue you were having with the installer?

Hello, no, I still have the issue even I use the one you provide.

**Comment by steff456** [comment]
Can you follow this video, https://www.youtube.com/watch?v=i7Njb3xO4Fw?

**Comment by miraboreasumr** [comment]
> Can you follow this video, https://www.youtube.com/watch?v=i7Njb3xO4Fw?

steff456, I really appreciate your reply, but that doesn't help. I already said that I follow this video in "What steps reproduce the problem?"

I have spyder-kernels, but spyder IDE still asks me for it
https://ibb.co/3hNH4W3

The problem is still not solved.

**Comment by dalthviz** [comment]
Hi @miraboreasumr could you try to run from an Ananconda Prompt with your `spyder-env` activated the following:

    conda install -c conda-forge spyder‑kernels=2.2.1

Let us know if that helps!

**Comment by ccordoba12** [comment]
Great! Closing this one then.

**Comment by vlasvlasvlas** [comment]
how do you still use this without conda?

pip install doesn't solve it and I'm not using conda

**Comment by dalthviz** [comment]
Hi @vlasvlasvlas, could you describe your setup? Maybe a look to our wiki could be useful to understand better how things work when using Spyder and a specific Python environment/custom interpreter: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

Let us know!

**Comment by zhangsiyu1997** [comment]
pip install spyder-kernels==2.2.1

**Comment by bero4sc** [comment]
I am facing the same issue. My setup is as follows. 
I have installed stand along Spyder 5.4.3 on Windows 11 and Python 3.11 as standalone (stand alone means, I am not using Conda/Anaconda environment). 
Python 3.11 version is installed in "C:/Program Files/Python311"
Spyder is installed in "C:\Program Files\Spyder"

Since Spyder comes with older version of Python which is Python 3.8.10, I changed this from Tools>Python interpreter: Select "Use the following Python interpreter". 

After the Spyder is restarted, the following error pops up:
An error ocurred while starting the kernel
**The Python environment or installation whose interpreter is located at
    C:\Program Files\Python311\python.exe
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.4.0 and < 2.5.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment first (if necessary) and then running in a system terminal:
    conda install spyder-kernels=2.4
or
    pip install spyder-kernels==2.4.*

From Command Prompt, I installed the spyder kernels using the pip install spyder-kernels==2.4.3 as suggested on Spder-IDE website. 
But the errors persists. Can you please help me to resolve this issue?
PS. I tried to go through the wiki page and the youtube videos you have suggested earlier in this thread. But I could not find the solution for this issue.

**Comment by cchi1272** [comment]
can i still use this code below in spder without installing anaconda in my windows to fix the kernel problem?
conda install -c conda-forge spyder‑kernels=2.4.3

**Comment by ccordoba12** [comment]
@cchi1272, that code doesn't work inside Spyder nor without Anaconda or Miniconda. Could you describe what you want to do to see if we can better help you with that?
