### ISSUE TITLE
Dataframes are not viewable in the variable explorer

### ISSUE THREAD

**Issue by mhdmyz** [spyder-ide/spyder#17342]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Dataframes are not viewable in the variable explorer

### What steps reproduce the problem?

1. Double clicking on a dataframe in the variable explorer
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder was unable to retrieve the value of this variable from the console.

The error message was:
An error occured, see the console..

Note: Please don't report this problem on Github, there's nothing to do about it.

```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.10
* Qt version: 
* PyQt version: 
* Operating System name/version: macos 12.2.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by mhdmyz** [comment]
I downgraded to pandas 1.3.5 and the issue was resolved. Seems you need to update Spyder with the latest version of pandas.

**Comment by ccordoba12** [comment]
Hey @mhdmyz, thanks for reporting. Are you using our Mac app along with an external environment?

**Comment by gjain75** [comment]
Have the same issue, dataframes cannot be viewed in variable explorer

**Comment by ccordoba12** [comment]
@mhdmyz, thanks for the confirmation. Then this problem will be fixed in our next version (5.3.0), to be released next month. The thing is at the time we released 5.2.2, Pandas had not released 1.4.0. So the Mac app in 5.3.0 will include it and solve this issue.

@gjain75, you need to downgrade to Pandas 1.3.5, as @mhdmyz mentioned above.

**Comment by gjain75** [comment]
Thanks. Will do. Is there a way I can use engine='pyarrow' for reading CSV files in pandas versions lower than 1.4.0

________________________________

**Comment by ccordoba12** [comment]
I think not, but I'm not really sure.

**Comment by mhdmyz** [comment]
@ccordoba12 Is it clear when Spyder 5.3.0 is going to be released?

**Comment by ccordoba12** [comment]
At the end of the month.

**Comment by Chentir-MT** [comment]
Hello team,
the thread is old but I am still having the same issue:
I have followed all recommendations (installing Spyder directly without going through Anaconda, downgrading pandas...etc) but neither dictionaries nor DataFrames won't open (to be more rigorous: SOME dict and SOME df won't open... with no apparent pattern).

Here is my setting:
 * Spyder version: 5.3.2  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Pandas version: 1.3.5
* Numpy version: 1.23.2
* Operating System: Windows 10

Any advice?

**Comment by DStone79** [comment]
I have a similar issue - I cannot see any dataframes for a project I am working on. I had reviously remove them - how can I get them back please?

[Is there a configuration file or something I should delete maybe?]

**Comment by DStone79** [comment]
Hi Carlos, thank you very much for replying.

I've run the code many times and the data frames never appear in the Variable Explorer. Not even in the variable rows.

They do appear if I debug and step through the code, but they don't if I run the code. Is there not some setting or config I can change to get them back?

Thanks again. Dan

**Comment by ccordoba12** [comment]
Ok, then please open a new issue about the problem, post a simple code that reproduces it and a video that shows what you're seeing in Spyder.
