### ISSUE TITLE
missing dependencies after updating clean install

### ISSUE THREAD

**Issue by mczakk** [spyder-ide/spyder#17355]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After uninstalling and re installing Anaconda I ran spyder 5.1.5 with no errors. 
I ran 'conda update anaconda' to update spyder to version 5.2.2.
now when I run spyder I get the error:
You have missing dependencies
# Mandatory
rtree >=0.9.7 : None (NOK)
 

### What steps reproduce the problem?

1. launching spyder
2. 
3. 

### What is the expected output? What do you see instead?

No error

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Spyder 5.2.2
Python 3.9.7 64-bit | 
Qt 5.12.9 |
 PyQt5 5.12.3 |
 Windows 10 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  None (NOK)
setuptools >=49.6.0           :  59.8.0 (OK)
sphinx >=0.6.6                :  3.5.4 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.27 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  1.9 (OK)

```

**Comment by dalthviz** [comment]
Hi @mczakk seems like somehow now `rtree` is not installed (from the dependencies section posted here, `rtree` version appears as `None (NOK)`. Could you try install it again by running from an Anaconda Prompt with your env activated something like `conda install -c conda-forge rtree`?

Let us know if that helps!

**Comment by mczakk** [comment]
@dalthviz tried that, doesn's seem to do anything!
(base) C:\WINDOWS\system32>conda install -c conda-forge rtree
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


(base) C:\WINDOWS\system32>

output from <conda list> , it seems that rtree is there?:
(base) C:\WINDOWS\system32>conda list
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2021.11                  py39_0
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0
alabaster                 0.7.12                     py_0    conda-forge
anaconda                  custom                   py39_1
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-navigator        2.1.1                    py39_0
anaconda-project          0.10.2             pyhd8ed1ab_0    conda-forge
anyio                     3.5.0            py39hcbf5309_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2          pyh9f0ad1d_1002    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb82d6ee_1    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
astroid                   2.9.3            py39hcbf5309_0    conda-forge
astropy                   5.0.1            py39h5d4886f_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atomicwrites              1.4.0              pyh9f0ad1d_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
autopep8                  1.6.0              pyhd8ed1ab_1    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       py39hde42818_1002    conda-forge
bcrypt                    3.2.0            py39hb82d6ee_2    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
bitarray                  2.3.6            py39hb82d6ee_0    conda-forge
bkcharts                  0.2              py39haa95532_0
black                     21.12b0            pyhd8ed1ab_0    conda-forge
blas                      1.0                         mkl
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.0               h0e60522_0    conda-forge
bokeh                     2.4.2            py39hcbf5309_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.2            py39h5d4886f_5    conda-forge
brotli                    1.0.9                h8ffe710_6    conda-forge
brotli-bin                1.0.9                h8ffe710_6    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1003    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-blosc2                  2.0.4                h09319c2_1    conda-forge
ca-certificates           2021.10.8            h5b45459_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2021.10.8        py39hcbf5309_1    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
cfitsio                   4.0.0                hd67004f_0    conda-forge
chardet                   4.0.0            py39hcbf5309_2    conda-forge
charls                    2.3.4                h39d44d4_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
comtypes                  1.1.11           py39hcbf5309_0    conda-forge
conda                     4.11.0           py39hcbf5309_0    conda-forge
conda-build               3.21.6           py39haa95532_0
conda-content-trust       0.1.3              pyhd8ed1ab_0    conda-forge
conda-env                 2.6.0                         1
conda-pack                0.7.0              pyh6c4a22f_0    conda-forge
conda-package-handling    1.7.3            py39hb3671d1_1    conda-forge
conda-repo-cli            1.0.4              pyhd3eb1b0_0
conda-token               0.3.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contextlib2               21.6.0             pyhd8ed1ab_0    conda-forge
cookiecutter              1.7.3              pyh6c4a22f_1    conda-forge
cryptography              36.0.1           py39h7bc7c5c_0    conda-forge
curl                      7.81.0               h789b8ee_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.27          py39h415ef7b_0    conda-forge
cytoolz                   0.11.2           py39hb82d6ee_1    conda-forge
daal4py                   2021.5.0         py39hefe7e4c_0    conda-forge
dal                       2021.5.0           h0e2418a_796    conda-forge
dask                      2022.2.0           pyhd8ed1ab_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1            py39h415ef7b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20200713           pyh9f0ad1d_0    conda-forge
distributed               2022.2.0         py39hcbf5309_0    conda-forge
docutils                  0.15.2           py39hcbf5309_3    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
fastcache                 1.1.0            py39hb82d6ee_3    conda-forge
filelock                  3.5.0              pyhd8ed1ab_0    conda-forge
flake8                    4.0.1              pyhd8ed1ab_1    conda-forge
flask                     1.1.4              pyhd8ed1ab_0    conda-forge
flit-core                 3.6.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.29.1           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
fsspec                    2022.1.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hcbf5309_4    conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    21.12.0          py39hb82d6ee_0    conda-forge
giflib                    5.2.1                h8d14728_2    conda-forge
glob2                     0.7                        py_0    conda-forge
greenlet                  1.1.2            py39h415ef7b_1    conda-forge
h5py                      3.6.0           nompi_py39hd4deaf1_100    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_103    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       68.2                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2021.11.20       py39hf46ed64_2    conda-forge
imageio                   2.16.0             pyhcf75d05_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        3.10.1           py39hcbf5309_0    conda-forge
importlib_metadata        3.10.1               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 6.9.1            py39h832f523_0    conda-forge
ipython                   7.31.1           py39hcbf5309_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
isort                     5.10.1             pyhd8ed1ab_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.18.1           py39hcbf5309_0    conda-forge
jellyfish                 0.9.0            py39hb82d6ee_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39hcbf5309_7    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py39hcbf5309_0    conda-forge
jupyter_server            1.13.5             pyhd8ed1ab_0    conda-forge
jupyterlab                3.2.9              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.10.3             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
keyring                   23.4.0           py39hcbf5309_2    conda-forge
kiwisolver                1.3.2            py39h2e07f2f_1    conda-forge
krb5                      1.19.2               h20d022d_3    conda-forge
lazy-object-proxy         1.7.1            py39hb82d6ee_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libarchive                3.5.2                hb45042f_1    conda-forge
libblas                   3.9.0              12_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_6    conda-forge
libbrotlidec              1.0.9                h8ffe710_6    conda-forge
libbrotlienc              1.0.9                h8ffe710_6    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libcurl                   7.81.0               h789b8ee_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              12_win64_mkl    conda-forge
liblief                   0.11.5               h0e60522_1    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
libzopfli                 1.0.3                h0e60522_0    conda-forge
llvmlite                  0.38.0           py39ha0cd8c8_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.7.1            py39h4fd7cdf_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.0.1            py39hb82d6ee_1    conda-forge
matplotlib                3.5.1            py39hcbf5309_0    conda-forge
matplotlib-base           3.5.1            py39h581301d_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.18           py39h59b6b97_0
mistune                   0.8.4           py39hb82d6ee_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py39h6b0492b_0    conda-forge
mkl_fft                   1.3.1            py39h0cb33c3_1    conda-forge
mkl_random                1.2.2            py39h2e25243_0    conda-forge
mock                      4.0.3            py39hcbf5309_2    conda-forge
more-itertools            8.12.0             pyhd8ed1ab_0    conda-forge
mpmath                    1.2.1              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.3            py39h2e07f2f_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py39hcbf5309_4    conda-forge
navigator-updater         0.2.1            py39haa95532_0
nbclassic                 0.3.5              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.11             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.2            py39hcbf5309_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
nltk                      3.6.7              pyhd8ed1ab_0    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.4.8              pyha770c72_0    conda-forge
numba                     0.55.1           py39hb8cd55e_0    conda-forge
numexpr                   2.8.1            py39hb80d3ca_0
numpy                     1.21.5           py39ha4e8547_0
numpy-base                1.21.5           py39hc2deb75_0
numpydoc                  1.2                pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openpyxl                  3.0.9              pyhd8ed1ab_0    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py39h2e25243_0    conda-forge
pandoc                    2.17.1.1             h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  2.9.2              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
path                      16.3.0           py39hcbf5309_0    conda-forge
path.py                   12.5.0                        0    conda-forge
pathlib2                  2.3.7.post1      py39hcbf5309_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.2              pyhd8ed1ab_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.0.1            py39ha53f419_1    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
platformdirs              2.5.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39hcbf5309_2    conda-forge
ply                       3.11                       py_1    conda-forge
powershell_shortcut       0.0.1                         3
poyo                      0.5.0                      py_0    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
prompt_toolkit            3.0.27               hd8ed1ab_0    conda-forge
psutil                    5.9.0            py39hb82d6ee_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-lief                   0.11.5           py39h415ef7b_1    conda-forge
pycodestyle               2.8.0              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3           py39hb82d6ee_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycurl                    7.44.1           py39hac1d6b8_1    conda-forge
pydocstyle                6.1.1              pyhd8ed1ab_0    conda-forge
pyerfa                    2.0.0.1          py39h5d4886f_1    conda-forge
pyflakes                  2.4.0              pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pylint                    2.12.2             pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0            py39hb3671d1_0    conda-forge
pyodbc                    4.0.32           py39h415ef7b_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_8    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_8    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_8    conda-forge
pyqtchart                 5.12             py39h415ef7b_8    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_8    conda-forge
pyreadline                2.1             py39hcbf5309_1005    conda-forge
pyrsistent                0.18.1           py39hb82d6ee_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_4    conda-forge
pytables                  3.7.0            py39hbcfe41f_0    conda-forge
pytest                    7.0.1            py39hcbf5309_0    conda-forge
python                    3.9.7                h6244533_1
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py39hcbf5309_0    conda-forge
python-lsp-black          1.1.0              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.3.3              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py39h5d4886f_1    conda-forge
pywin32                   303              py39hb82d6ee_0    conda-forge
pywin32-ctypes            0.2.0           py39hcbf5309_1004    conda-forge
pywinpty                  2.0.2            py39h99910a6_0    conda-forge
pyyaml                    6.0              py39hb82d6ee_3    conda-forge
pyzmq                     22.3.0           py39he46f08e_1    conda-forge
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.2.1              pyhd8ed1ab_0    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtawesome                 1.1.1              pyhd8ed1ab_0    conda-forge
qtconsole                 5.2.2              pyhd8ed1ab_1    conda-forge
qtconsole-base            5.2.2              pyhd8ed1ab_1    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
regex                     2022.1.18        py39hb82d6ee_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rope                      0.22.0             pyhd8ed1ab_0    conda-forge
rtree                     0.9.7            py39h09fdee3_3    conda-forge
ruamel_yaml               0.15.80         py39hb82d6ee_1006    conda-forge
scikit-image              0.19.1           py39h2e25243_0    conda-forge
scikit-learn              1.0.2            py39he931e04_0    conda-forge
scikit-learn-intelex      2021.5.0         py39hcbf5309_1    conda-forge
scipy                     1.8.0            py39hc0c34ad_1    conda-forge
seaborn                   0.11.2               hd8ed1ab_0    conda-forge
seaborn-base              0.11.2             pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.8.0           py39hcbf5309_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.6.1              pyh44b312d_0    conda-forge
sip                       6.5.1            py39h415ef7b_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                ha925a31_3    conda-forge
sniffio                   1.2.0            py39hcbf5309_2    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcollections         2.1.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sphinx                    3.5.4              pyh44b312d_0    conda-forge
sphinxcontrib             1.0              py39haa95532_1
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
sphinxcontrib-websupport  1.2.4              pyhd8ed1ab_1    conda-forge
spyder                    5.2.2            py39hcbf5309_2    conda-forge
spyder-kernels            2.2.1            py39hcbf5309_1    conda-forge
sqlalchemy                1.4.31           py39hb82d6ee_0    conda-forge
sqlite                    3.37.0               h8ffe710_0    conda-forge
statsmodels               0.13.2           py39h5d4886f_0    conda-forge
sympy                     1.9              py39hcbf5309_1    conda-forge
tbb                       2021.5.0             h2d74725_0    conda-forge
tbb4py                    2021.5.0         py39hd0a9cb8_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
terminado                 0.13.1           py39hcbf5309_0    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.2.2              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tifffile                  2022.2.9           pyhd8ed1ab_0    conda-forge
tinycss                   0.4             pyhd8ed1ab_1002    conda-forge
tinycss2                  1.1.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     1.2.2              pyhd8ed1ab_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39hb82d6ee_2    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.5.2            py39hb82d6ee_0    conda-forge
typing-extensions         4.1.1                hd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
ujson                     5.1.0            py39h415ef7b_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_0    conda-forge
unidecode                 1.3.2              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
watchdog                  2.1.6            py39hcbf5309_1    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.2.3              pyhd8ed1ab_0    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whichcraft                0.6.1                      py_0    conda-forge
widgetsnbextension        3.5.2            py39hcbf5309_1    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_3    conda-forge
win_unicode_console       0.5             py39hcbf5309_1002    conda-forge
wincertstore              0.2             py39hcbf5309_1007    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.13.3           py39hb82d6ee_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xlsxwriter                3.0.2              pyhd8ed1ab_0    conda-forge
xlwings                   0.26.2           py39hcbf5309_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.32.0             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zfp                       0.5.5                h0e60522_8    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zope                      1.0              py39haa95532_1
zope.event                4.5.0              pyh9f0ad1d_0    conda-forge
zope.interface            5.4.0            py39hb82d6ee_1    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge

**Comment by dalthviz** [comment]
What happens if you try to `import rtree` from the internal console inside Spyder? What happens if you try to uninstall it and reinstall it? Usually when trying to import when Spyder is unable to detect is version will trigger a traceback regarding some missing .dll but there is not much we can do over the Spyder side to help with that if that is happening sorry :/

**Comment by mczakk** [comment]
`import rtree` :
import rtree
Traceback (most recent call last):

  File "C:\Users\mtc20tfq\AppData\Local\Temp\ipykernel_26784\93875924.py", line 1, in <module>
    import rtree

  File "C:\ProgramData\Anaconda3\lib\site-packages\rtree\__init__.py", line 9, in <module>
    from .index import Rtree, Index  # noqa

  File "C:\ProgramData\Anaconda3\lib\site-packages\rtree\index.py", line 6, in <module>
    from . import core

  File "C:\ProgramData\Anaconda3\lib\site-packages\rtree\core.py", line 75, in <module>
    rt = finder.load()

  File "C:\ProgramData\Anaconda3\lib\site-packages\rtree\finder.py", line 67, in load
    raise OSError("could not find or load {}".format(lib_name))

OSError: could not find or load spatialindex_c-64.dll

What happens if you uninstall and reinstall?
this what caused the problem! I uninstalled/installed Anaconda, which (as of yesterday) comes with Spyder 5.1.5 bundled with it. (this install ran without the rtree error) 
Following the guide on the Spyder website i did 'conda update anaconda' which updated spyder to 5.2.2, and now i have the error

**Comment by dalthviz** [comment]
> What happens if you uninstall and reinstall?

I meant to say to uninstall and reinstall `rtree`, sorry for the confusion there 😅 

Also, could you create a new env and check if the error with `rtree` persists there?:

    conda create -n spyder-env python=3.9 spyder=5.2.2

**Comment by mczakk** [comment]
tried 'conda install rtree -c conda-forge --force-reinstall', still get the error
now trying 'conda create -n spyder-env python=3.9 spyder=5.2.2 -c conda-forge'
did that, activated the environment, started spyder, same result!
I dont really understand this environment business, when i did 'conda activate spyder-env' as instructed in the anaconda prompt, the prompot changed to (spyder-env) C:\WINDOWS\system32>, but when i open it again the prompt has returned to (base)C:\WINDOWS\system32 - am i doing it correctly?

**Comment by mczakk** [comment]
That seems to have worked!!!!!
Many Thanks  Daniel @dalthviz
