### ISSUE TITLE
Console says wrong kernel version but conda says already installed

### ISSUE THREAD

**Issue by Nemi6** [spyder-ide/spyder#17353]
### What steps will reproduce the problem?

Installing a fresh version of Spyder and miniconda, all goes well until I install seaborn on conda. After that I get this consistently, no matter what I follow:

The Python environment or installation whose interpreter is located at
    /Users/oracle/opt/miniconda3/bin/python
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.2.1 and < 2.3.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    conda install spyder‑kernels=2.2
or
    pip install spyder‑kernels==2.2.*

I have tried multiple attempts of this with no success. Can anyone help please?

Thanks,
Steven

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 21.4.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.1 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @Nemi6 sorry to heart that. Are you using the default interpreter in your preferences? (seems like is the base env but just to be sure).

What happens if you try to run `conda install -c conda-forge spyder-kernels=2.2.1` from your terminal with the activated env where your selected interpreter is and launch a new console?

Also could you try to create a new env just with seaborn and spyder-kernels in the right version and use the custom interpreter preference (`Preferences > Python Interpreter > Use the following Python interpreter > <Path to your new interpreter env>`)?

Could you share with us the output of running `conda list` with the env your are using?

Let us know if you have more info or something of the above helps!

**Comment by v84hax** [comment]
> conda install -c conda-forge spyder-kernels=2.2.1

Thanks for this. I was having similar trouble where I have already updated my spyder-kernels using conda, etc. Turns out using the above's code solves it.

**Comment by Nemi6** [comment]
> Hi @Nemi6 sorry to heart that. Are you using the default interpreter in your preferences? (seems like is the base env but just to be sure).
> 
> What happens if you try to run `conda install -c conda-forge spyder-kernels=2.2.1` from your terminal with the activated env where your selected interpreter is and launch a new console?
> 
> Also could you try to create a new env just with seaborn and spyder-kernels in the right version and use the custom interpreter preference (`Preferences > Python Interpreter > Use the following Python interpreter > <Path to your new interpreter env>`)?
> 
> Could you share with us the output of running `conda list` with the env your are using?
> 
> Let us know if you have more info or something of the above helps!

Like the other user the forge 2.2.1 kernels worked - thanks very much for the resolution!
