### ISSUE TITLE
Several modules not found even though properly installed

### ISSUE THREAD

**Issue by RudyL90** [spyder-ide/spyder#17354]
## Problem Description

I have tried installing several packages such as pynput, pyautogui, win32gui and I receive error messages stating that the module has not been found when I import either of these modules.
The installation I did as follows: open cmd in administrator mode and run the command pip install package_name.
The package is found when using pip show package_name.
When running python in cmd and importing the modules from there, it works perfectly. The modules also work in sublime text or other IDEs.

In Spyder I have set the PYTHONPATHMANAGER to the folder in which the modules have been installed.
I have also tried installing modules by other means (wheels), though since I am not very familiar with this I do not know what the difference would have been.

## Versions
* Spyder version: 5.2.2
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt version: PyQt5 5.12.3
* Operating System name/version: Windows 10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  1.9 (OK)

**Comment by dalthviz** [comment]
Hi @RudyL90 thank you for the feedback! Seems like you are using the standalone Windows installer, right? If you want to use custom packages you will need to use the custom interpreter preference and have `spyder-kernels` installed where your custom interpreter is located. For more info about that you can check: https://docs.spyder-ide.org/current/faq.html#using-packages-installer (although the instructions use the anaconda/miniconda distributions and python environment to ilustrate the use of the preference)

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by scrwho** [comment]
Perhaps spider team should consider referring to the environmental variable.

Due to space on my C drive, I installed python and other apps on  other Drive (D) and add the path to environmental variable on Windows. Other app like JupyterLab Desktop works. 

I can't use spider effectively.

**Comment by ccordoba12** [comment]
@scrwho, please read our docs to learn what's the right way to do what you want:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

https://docs.spyder-ide.org/5/faq.html#using-packages-installer

Messing with PATH and PYTHONPATH is just the direct route to disaster, if you ask me.

**Comment by scrwho** [comment]
It's working with the modules now after installing spider-kennel

Thanks a lot
