### ISSUE TITLE
qtpy import overrides pyqt5 import

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#17356]
## Problem Description
It seems that starting spyder and running code in the interactive console overrides imports of  `pyqt`. This can lead to strange issues when running the code somewhere else even using the same environment. In the description below, this is assumed, e.g. running either in spyder interactive terminal or running using `ipython` from the same environment (where `python` can be used to reproduce too) 

Sample, works:
```python
from qtpy import QtCore
QtCore.Signal()
```

Sample 2, works:
```python
from pyqt5 import QtCore
QtCore.pyqtSignal()
```

Sample 3, fails in cmd, works in spyder:
```python
from pyqt5 import QtCore
QtCore.Signal()
```

### What steps reproduce the problem?

1. Run the sample 3 in spyder using *F5*
2. Run the sample 3 from cmd
3. Signal / Slot import will either fail or work.

### What is the expected output? What do you see instead?
This is due the override of `pyqtSignal` with `Signal` in `qtpy.QtCore` I guess. I just dont see this being a consistent bevavior or I dont understand the reasoning.

### Paste Traceback/Error Below (if applicable)
Import error due to `Signal` has been moved to `pyqtSignal` in `pyqt5+`

**Comment by dalthviz** [comment]
Hi @max3-2 thank you for the feedback! I was unable to reproduce this :/ Could you submit a GIF or video to understand better what is happening? Also, could you provide more info about your setup (Spyder version, Python version, QtPy version, OS, etc)? Let us know!

**Comment by max3-2** [comment]
Sorry cant create a screen share since this is a managed device and privately, I do not have a windows machine. To clarify: I create three files containing each of the snippets above and run them from `cmd` and by opening them in spyder and using *Run*. Sample 1 and 2 work both ways, Sample 3 fails in console
```python
Traceback (most recent call last):
  File "C:\Users\elm1rng\Python\sample.py", line 9, in <module>
    QtCore.Signal()
AttributeError: module 'PyQt5.QtCore' has no attribute 'Signal'
```
looking at `pyqt5` namespace this failure is expected. However using spyder this just works. I assume a backend qtpy override of the actual pyqt5 import. Version details are

Python 3.9.10 64-bit | Qt 5.12.10 | PyQt5 5.12.3 | Windows 10

**Comment by ccordoba12** [comment]
I can't reproduce this on Linux

![image](https://user-images.githubusercontent.com/365293/154853065-55c0a9d1-2867-4a6f-a303-08acaaa032dd.png)

@dalthviz, could you do it on Windows?

**Comment by max3-2** [comment]
Can you use `PyQt5` instead of `pyqt5` to get the *basic* import working?

**Comment by ccordoba12** [comment]
No, I can't. The import fails with `pyqt5` because the module can't be found:

![image](https://user-images.githubusercontent.com/365293/154863266-9f338b6d-80ed-4242-80fc-00e9e89e7d30.png)

**Comment by dalthviz** [comment]
I can't reproduce this on Windows:

![imagen](https://user-images.githubusercontent.com/16781833/155007957-cd32c36a-fbf4-4606-82b8-5c07ae76328c.png)

Trying to import `pyqt5` gives me an error:

![imagen](https://user-images.githubusercontent.com/16781833/155008093-e10c6f3d-778c-4102-b6f1-d9af17d6fde4.png)

@max3-2 are you somehow using some other package wrapper besides QtPy that enables you to import PyQt5 as `pyqt5` ?

**Comment by max3-2** [comment]
I will double check bot not that I know of. Strange…
I will check my *virtualenv* maybe something is mixed up there
