### ISSUE TITLE
Spyder 5.1.5 debugging does not work in new environnements (Anaconda3-2021.11-Windows-x86_64.exe)

### ISSUE THREAD

**Issue by tstolarczyk** [spyder-ide/spyder#17350]
Hello,
First thanks for the excellent work of the contributors!

Anaconda3-2021.11-Windows-x86_64.exe
Windows 10

In the context of specific development, after reinstallation of anaconda, I am facing a problem with `spyder `that I reproduce here in a simpler situation.

I have installed `anaconda `from `Anaconda3-2021.11-Windows-x86_64.exe` on Windows 10.
The base environment has `spyder 5.1.5` installed.
I have written a few line script importing `numpy `(1.20.3) and `matplotlib `(3.4.3), with a breakpoint (at "x=").

```
import numpy as np
import matplotlib.pyplot as plt
if __name__ == '__main__':
	x=np.linspace(1,10,10)
	plt.hist(x**2)
```

The script runs, debugging works fine. Same after `conda update --all.`

I create an environment either from the Navigator or by hand from a conda shell (`conda env create –n test_from_shell`, that then appears in the Navigator).

In both created environments I install `spyder `(`conda install spyder`, and `spyder 5.1.5 `gets installed, like in the base), `numpy `(1.21.5) and `matplotlib `(3.5.0), not the same version. 
`spyder-kernels` version is 2.1.3 in all cases, `ipykernel `versions are the same.

In the created environment the script runs correctly, **but the debugging does not work**, i.e. it starts, does not stop at nor reach the breakpoint and cannot be interrupted.
The symptoms are the same as in issue [#17314,](https://github.com/spyder-ide/spyder/issues/17314) and the steps are similar to the ones described in the attached pdf of that issue ([C__Users_jandre_Desktop_Problem_20220208_1900.pdf](https://github.com/spyder-ide/spyder/files/8026710/C__Users_jandre_Desktop_Problem_20220208_1900.pdf)

I have cloned the base environment through a yaml file and I have checked that in the cloned environment the script and the debugging run fine.

1. What is/are the guilty module(s) in the test environments leading to the debugger bug ? How can I find it ? How can this be solved?

2. Could you explain what are the default scripts installed when a new environment is created and why it is not the ones found in the base environment ? Is that expected ?

Thanks a lot

**Comment by ccordoba12** [comment]
Hey @tstolarczyk, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

After that, you can connect Spyder to your other environments by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if that works for you.

**Comment by tstolarczyk** [comment]
Hello, thanks for your quick answer.

I iinstalled Spyder as a "standalone" executable, and selected the python executable (Tools-> Preferences) to point toward a freshly empty created environment.
But the Spyder console cannot be launch without spyder-kernels=2.2
I "conda install spyder-kernels=2.2" in my environment but it fails: there is a huge list of conflicts to be solved....

Did I do something wrong ? Any idea ?

**Comment by kikazahn** [comment]
This worked for me. To avoid conflicts I had to do `conda uninstall spyder spyder-kernels` in my old environment
Also install spyder-kernels from conda-forge: `conda install spyder-kernels -c conda-forge`
Otherwise spyder-kernels 2.2.0 will be installed and they are incompatible with spyder 5.2.2

**Comment by tstolarczyk** [comment]
Yes, I confirm this works once I load the specific spyder-kernels !
In an environment with many older dependencies (e.g. python 3.7) I had to explicit `spyder-kernels=2.2.1` , the version installed in the test environment (otherwise would load 1.x or something).
Thanks a lot ! Now I can continue with my own bugs !

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by iAvicenna** [comment]
This method works however it messes up retrieving values from the console which is not a built-in type. So unfortunately cant display any variable from the console. Any timeline as to when 5.2.2 will be available via anaconda? Thanks and much appreciated.

**Comment by ccordoba12** [comment]
We really don't know because it depends on the Anaconda team and we don't have control over that.

**Comment by FTL-Citepa** [comment]
> This method works however it messes up retrieving values from the console which is not a built-in type. So unfortunately cant display any variable from the console. Any timeline as to when 5.2.2 will be available via anaconda? Thanks and much appreciated.

so it's not a solution

**Comment by Davo36** [comment]
Thanks to the contributors.  I love Spyder.

Just installed Anaconda as a fresh install as I wanted Spyder 5 in an Anaconda environment.  The version in Anaconda is 5.1.5. 

I encountered the debugging problems mentioned above.

So the only choice for me (I don't want to muck around with kernels etc.) is to install a stand alone version of Spyder.

Not sure why Anaconda would include a buggy version.  And then not update it super quick.

**Comment by ccordoba12** [comment]
> Thanks to the contributors. I love Spyder.

Thanks for your kind words @Davo36!

> Not sure why Anaconda would include a buggy version. And then not update it super quick.

We're in conversations with them to see how to sort out this problem. But in the meantime, you either have to use our Mac or Windows apps, or install Spyder from conda-forge.

**Comment by Davo36** [comment]
@ccordoba12 Yes I just installed the stand alone version, I'm using Windows.  It works fine.  Thanks.

**Comment by jacob-bayer** [comment]
This is a major issue. Anaconda still includes Spyder 5.1.5 as its highest version. Can someone from the Spyder team get in touch with Anaconda and have this resolved?

**Comment by ccordoba12** [comment]
> Can someone from the Spyder team get in touch with Anaconda and have this resolved?

We already did. They said they were going to fix it soon, but I think three weeks passed since then.
