### ISSUE TITLE
rtree have installed but still missing rtree

### ISSUE THREAD

**Issue by wjyts1999** [spyder-ide/spyder#17368]
## Problem Description
I have installed rtree == 0.9.7, but when I open spyder, it still prompts me that rtree is missing

## Versions

* Spyder version: 5.1.5
* Python version: 3.8
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: win10

**Comment by ccordoba12** [comment]
Hey @wjyts1999, thanks for reporting. This is a not a problem with Spyder but with the Rtree package, so there's nothing we can do about it, sorry.

If you want to avoid this problem, please use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).

You can also download and install Anaconda. If you already have it installed and you're still seeing this problem, it probably means that you're mixing pip and conda packages, which are incompatible. Please [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to fix that.
