### ISSUE TITLE
Spyder hangs on open Matlab file

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1736]
_From [kevin...@gmail.com](https://code.google.com/u/112620934441955973723/) on 2014-02-21T15:11:03Z_

Spyder Version:  2.3.0beta3
Python Version:  2.7.5+
Qt Version    :  4.8.4, PyQt4 (API v1) 4.10.3 on Linux
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  0.13.2 (OK)
sphinx >=0.6.6  :  None (NOK)
rope >=0.9.2    :  None (NOK)
matplotlib >=1.0:  1.2.1 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?
1. Open File Explorer panel
   1. Navigate to a Matlab (*.m) file.
   2. Double-click it. What is the expected output? What do you see instead? Expected output: Matlab file opens in a new tab of the file explorer so that I can edit it.  (The reason I want to do this is because I am converting some old Matlab code to python/matplotlib, and it's easiest if I can just open a *.m file and do a file/save as *.py.)

Instead of opening the file normally, the Spyder editor doesn't seem to know what to do with the Matlab file. A new tab with the *.m filename appears, with no text visible. The mouse cursor changes to a "please wait..." (spinning circle motif). I can still use the mouse to navigate the Spyder interface, although on at least one occasion I got a "Spyder crashed on last session" message when I returned to the program, and had to run "python spyder --reset" in order to open Spyder after that. 

Please provide any additional information below

. I thought this might be caused by the files having Windows style line endings (the Matlab files were created in Windows.) However, if I simply right-click them and do a copy/paste from my normal file browser (Nemo), and rename the new copy as ".py" then I can open it without any issues in Spyder. So I don't think this is the issue.

I am running Linux Mint 16, Cinnamon, 32 bit.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1736_

**Comment by ccordoba12** [comment]
This should be fixed now in Spyder 3.0
