### ISSUE TITLE
Differences in versions

### ISSUE THREAD

**Issue by pasangk** [spyder-ide/spyder#17378]
I have installed standalone spyder version, which is based on python 3.7.5 but I already have python 3.10.1. It seems that spyder is not functioning interactively with the python already installed on my windows but is functioning completely alone. Can anyone clarify me regarding this? I am a beginner.

**Comment by ccordoba12** [comment]
Hey @pasangk, thanks for reporting. Spyder's installer comes with its own Python version, which is 3.7.5 (as you mentioned above).

If you want to connect other Python installations with that Spyder, please see this FAQ in our documentation:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if that answers your question.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
