### ISSUE TITLE
pandas dataframe is nor properly supportes

### ISSUE THREAD

**Issue by EduardoAlbaizar** [spyder-ide/spyder#17377]
### What steps will reproduce the problem?

Try to copy a dataframe to get the issue reporter.
Try to visualize a dataframe and you will get an error with no popup

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 105, in get_value
    timeout=CALL_KERNEL_TIMEOUT).get_value(name)
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 558, in __call__
    call_dict, call_data, self._comm_id)
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 219, in _get_call_return_value
    call_dict, call_data, comm_id)
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 440, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 496, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
AttributeError: Can't get attribute '_unpickle_block' on <module 'pandas._libs.internals' from 'C:\\Users\\T1006173.GRUPOVIDRALA\\AppData\\Local\\Programs\\Spyder\\pkgs\\pandas\\_libs\\internals.cp37-win_amd64.pyd'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\main_widget.py", line 560, in copy
    self._current_editor.copy()
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1097, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1438, in get_value
    return self.parent().get_value(name)
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1496, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\T1006173.GRUPOVIDRALA\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 117, in get_value
    raise ValueError(msg % reason_other)
ValueError: An error occured, see the console..<br><br>Note: Please don't report this problem on Github, there's nothing to do about it.
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.9.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @EduardoAlbaizar, thanks for reporting. This problem will be fixed in our next version (5.3.0), to be released next month.

In the meantime, please use Pandas 1.3.5 in our external Python interpreters.

**Comment by EduardoAlbaizar** [comment]
Muchas gracias por la rapidez en la respuesta.

Por cierto, me gustaría aportar un par de sugerencias para mejorar la experiencia de usuario en Spyder:

1. Posibilidad de desdoblar en dos o mas paneles la terminal para vigilar más de un kernel. Esto ya se puede hacer con el editor.

2.  Poder deshabilitar cualquier intrusión en pantalla o alteración del layout al escribir código. Los popups emergentes de ayuda son muy molestos y aparecen continuamente. Además según avanza la sesión, su comportamiento se vuelve errático y es realmente molesto. Debería haber una opción similar al F9 de Excel para calcular las celdas y que sólo se revise el texto o se muestre la ayuda cuando se solicita. Igual existe lo que pido pero he sido incapaz de configurarlo a mi gusto.

3. Opción para guardar todas las variables del kernel en un archivo y poder restaurarlas en un nuevo kernel. Sería de muchísima utilidad y me sorprende que no exista este opción.

Muchas gracias y un saludo

Eduardo Albaizar



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ccordoba12** [comment]
> 1. Posibilidad de desdoblar en dos o mas paneles la terminal para vigilar más de un kernel. Esto ya se puede hacer con el editor.

Quieres decir que quisieras tener varias ventanas de la terminal de IPython disponibles para iniciar diferentes ejecuciones en las mismas?

Si es así, podrías explicar mejor porque necesitas esa funcionalidad? Gracias!

> 2.  Poder deshabilitar cualquier intrusión en pantalla o alteración del layout al escribir código.

Eso se puede hacer en Preferencias, específicamente en estas páginas:

![image](https://user-images.githubusercontent.com/365293/154997430-c6e560fe-74df-4e53-abb1-2ee4c30c99c1.png)

![image](https://user-images.githubusercontent.com/365293/154997713-d2f44302-5c14-49eb-9727-c17c96acc7a6.png)

Al deshabilitar las opciones que señalé con las flechas, creo que se eliminan todos los extras que tiene el editor al escribir código.

**Comment by EduardoAlbaizar** [comment]
Hola Carlos,

Gracias por las tips para deshabilitar las ayudas, etc.

Desdoblar paneles
Lo que quisiera hacer es mostrar como corren dos procesos a la vez (consolas 5 y 6  en las imágenes)
Actualmente o muestro una consola o muestro la otra. De esta manera actual no me entero si la consola que está en segundo plano ha dado error.
Tampoco puedo comparar directamente las dos consolas.
Uso Spyder para depurar los programas ya que tras el fallo puedo ver el error ya analizar las variables que lo provocan.
Ejecutado los scripts desde Python directamente puedo monitorizar los dos procesos a la vez pero no permite analizar los problemas si hay un fallo.

***@***.******@***.***
Editor si permite desdoblar en dos o más paneles

***@***.*** ***@***.***


***@***.***Eduardo Albaizar
Process Scientist

Vidrala S.A.
T:   +34 946 719 733
M: +34 626 928 803
www.vidrala.com<http://www.vidrala.com/>

De: Carlos Cordoba ***@***.***>
Enviado el: lunes, 21 de febrero de 2022 17:55
Para: spyder-ide/spyder ***@***.***>
CC: EDUARDO ALBAIZAR MENCHACA ***@***.***>; Mention ***@***.***>
Asunto: Re: [spyder-ide/spyder] pandas dataframe is nor properly supportes (Issue #17377)


### The following email comes from an external source. Be careful with any links or requests ###


  1.  Posibilidad de desdoblar en dos o mas paneles la terminal para vigilar más de un kernel. Esto ya se puede hacer con el editor.

Quieres decir que quisieras tener varias ventanas de la terminal de IPython disponibles para iniciar diferentes ejecuciones en las mismas?

Si es así, podrías explicar mejor porque necesitas esa funcionalidad? Gracias!

  1.  Poder deshabilitar cualquier intrusión en pantalla o alteración del layout al escribir código.

Eso se puede hacer en Preferencias, específicamente en estas páginas:

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F365293%2F154997430-c6e560fe-74df-4e53-abb1-2ee4c30c99c1.png&data=04%7C01%7C%7Cd8ccc1ac24504350bbed08d9f55ae195%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C637810592962816703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=K0q8J3c37IXAjnuZlXSrK1hh2AItvINHKA8XKu0DLT4%3D&reserved=0>

[image]<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F365293%2F154997713-d2f44302-5c14-49eb-9727-c17c96acc7a6.png&data=04%7C01%7C%7Cd8ccc1ac24504350bbed08d9f55ae195%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C637810592962816703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8icCNGjr7d5Uzh0TahIxjcxpfWCmZaIkWXF%2FR%2FB15DU%3D&reserved=0>

Al deshabilitar las opciones que señalé con las flechas, creo que se eliminan todos los extras que tiene el editor al escribir código.

-
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspyder-ide%2Fspyder%2Fissues%2F17377%23issuecomment-1047072106&data=04%7C01%7C%7Cd8ccc1ac24504350bbed08d9f55ae195%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C637810592962816703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=f6lU9yR7bXVKew0PtLFNF%2BAVSORamlL5BNXrHoNVYdo%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALQCSALSN3BXKDSA6F5DERLU4JU5XANCNFSM5O44LLSQ&data=04%7C01%7C%7Cd8ccc1ac24504350bbed08d9f55ae195%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C637810592962816703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=INvLUEYLI%2FqLTSrAAdDs38jmDwDgw1uFvQo4fDCaV0A%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cd8ccc1ac24504350bbed08d9f55ae195%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C637810592962816703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1XN9ktjXtlt8y8H2pstIQ8yYXxyqZD2o8AXr1ovr1%2F4%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cd8ccc1ac24504350bbed08d9f55ae195%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C637810592962816703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=h5dlGSkH%2FXnRXjxTRl6dctznkinoXWpDQtskYhMpHts%3D&reserved=0>.

**Comment by EduardoAlbaizar** [comment]
Desdoblar paneles

Lo que quisiera hacer es mostrar como corren dos procesos a la vez (consolas 5 y 6  en las imágenes)
![image003](https://user-images.githubusercontent.com/48244993/155205721-b86d1d85-1bd9-4c02-8fd4-6d339b1cccfc.png)
![image002](https://user-images.githubusercontent.com/48244993/155205723-babcd1e0-bc4a-4562-83dd-c07827403d0b.png)
![image005](https://user-images.githubusercontent.com/48244993/155205725-8e50620b-1e58-41a9-985a-d40a12293e22.png)
![image004](https://user-images.githubusercontent.com/48244993/155205728-8cc8f6e5-15b4-4425-a832-137fc06c4f0d.png)

Actualmente o muestro una consola o muestro la otra. De esta manera actual no me entero si la consola que está en segundo plano ha dado error.

Tampoco puedo comparar directamente las dos consolas.

Uso Spyder para depurar los programas ya que tras el fallo puedo ver el error ya analizar las variables que lo provocan.

Ejecutado los scripts desde Python directamente puedo monitorizar los dos procesos a la vez pero no permite analizar los problemas si hay un fallo.

 

imagenimagen

Editor si permite desdoblar en dos o más paneles

 

imagen imagen

**Comment by EduardoAlbaizar** [comment]
Ahora voy a abrir el nuevo issue. He andado un poco liado estos días...

**Comment by ccordoba12** [comment]
Ok, gracias!

**Comment by EduardoAlbaizar** [comment]
Buenas tardes Carlos,

Hace algunas semanas instalé la última versión de Spyder y me gustaría darte el siguiente feedback:


  *   Soluciona el problema con pandas dataframe que reporté en su momento. Gracias!
  *   Estoy sufriendo cuelgues del programa de forma habitual y sin motivo aparente.

Esto me ocurre en dos sistemas diferentes y supone un problema enorme!

En mi caso es motivo para desinstalar esta nueva versión y volver a la versión anterior.

Este problema no lo había experimentado con ninguna de las dos versiones (*) que había usado hasta la fecha

Uno de los principales usos que hago de Spyder es para analizar los fallos de un programa que tiene que estar en ejecución de continuo.

Si el que se cuelga es Spyder, me para la aplicación en marcha con lo que es peor el diagnóstico que el potencial problema.

  *   Se echa de menos, ante la falta de depuración de las versiones publicadas, un repositorio con las diferentes versiones de Spyder.

En casos como el que me ocupa sería lógico poder volver a la versión de Spyder que sea estable.

Un saludo

Eduardo


***@***.***

(*) la que instalaba anaconda hace un año y la anterior a la actual sobre la que reporté el problema con pandas df.

***@***.***Eduardo Albaizar
Process Scientist

Vidrala S.A.
T:   +34 946 719 733
M: +34 626 928 803
www.vidrala.com<http://www.vidrala.com/>
Este mensaje se dirige exclusivamente a su destinatario. Su contenido y los documentos anexos representan información CONFIDENCIAL. Si ha recibido este mensaje por error, le rogamos nos lo comunique de forma inmediata por esta misma vía o por teléfono (+34 946719765) y proceda a eliminar la presente comunicación y los anexos de su sistema. El correo electrónico vía Internet no permite asegurar la confidencialidad de los mensajes, ni su integridad o correcta recepción. Vidrala no asume responsabilidad por estas circunstancias. Muchas Gracias. http://www.vidrala.com This message is intended exclusively for its addressee. Its content and any attached document represent CONFIDENTIAL information. If this message has been received in error, please immediately notify us via e-mail or by telephone (+34 946719765) and delete it. Internet e-mail neither guarantees the confidentiality nor the integrity or proper receipt of the messages sent. Vidrala does not assume any liability for those circumstances. Thank you very much. http://www.vidrala.com

**Comment by ccordoba12** [comment]
>  Se echa de menos, ante la falta de depuración de las versiones publicadas, un repositorio con las diferentes versiones de Spyder.

Ese repositorio está en nuestra página de Releases:

https://github.com/spyder-ide/spyder/releases

Allí se pueden descargar todas las versiones previas de Spyder hasta la versión 4.2.0 por medio de nuestros instaladores para Windows y macOS.

**Comment by EduardoAlbaizar** [comment]
Muchas gracias Carlos,

Pude encontrarlo por mi cuenta.
En cualquier caso he visto que puedo descargarlo a través de PIP y me da menos problemas.
Llevo varios meses con la versión 5.3.1 ya que me da estabilidad y no me apetece arriesgar a perderla probando nuevas versiones.

Un saludo

***@***.***Eduardo Albaizar
Process Scientist

Vidrala S.A.
T:   +34 946 719 733
M: +34 626 928 803
www.vidrala.com<http://www.vidrala.com/>

De: Carlos Cordoba ***@***.***>
Enviado el: sábado, 5 de noviembre de 2022 0:20
Para: spyder-ide/spyder ***@***.***>
CC: EDUARDO ALBAIZAR MENCHACA ***@***.***>; Mention ***@***.***>
Asunto: Re: [spyder-ide/spyder] pandas dataframe is nor properly supportes (Issue #17377)


### The following email comes from an external source. Be careful with any links or requests ###


Se echa de menos, ante la falta de depuración de las versiones publicadas, un repositorio con las diferentes versiones de Spyder.

Ese repositorio está en nuestra página de Releases:

https://github.com/spyder-ide/spyder/releases<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspyder-ide%2Fspyder%2Freleases&data=05%7C01%7C%7C5dcd381a37a8423fe4ee08dabebb1620%7C48cbe2043cf14d96b0718e6ca0926b07%7C0%7C0%7C638032008017404701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ZvztcWUwakk2RNAiDkKhXJTC4Cn2Vdmqlykife7Xepw%3D&reserved=0>

Allí se pueden descargar todas las versiones previas de Spyder hasta la versión 4.2.0 por medio de nuestros instaladores para Windows y macOS.

-
