### ISSUE TITLE
Spyder unable to load spyder 3 icon theme.

### ISSUE THREAD

**Issue by C046** [spyder-ide/spyder#17372]
## Problem Description
So, apparently out of the blue spyder decides to not want to work properly/ not load the icons. 

**Things that I have tried so far:** 
I took ownership of the spyder folder and all the contents inside of said folder, so I know its not an ownership type of thing.
2.) I erradicated the spyder IDE from my environment then performed a clean reinstall.
3.) I tried changing python versions thinking maybe its the python version, hell I even tried changing from Pyqt5 to Pyqt6 which ik is ridiculous because why would it be compatible with pyqt6 if its built for pyqt5. 

### What steps reproduce the problem?

1. Open spyder and set icon theme to spyder 3
2. Restart
3. Error occurs, Spyder was unable to load the spyder3 icon theme. That's why its going to fallback to the theme used in Spyder 2
for that, please close this window and start Spyder again.

### What is the expected output? What do you see instead?
A working IDE is what I expected and received garbage.

### Paste Traceback/Error Below (if applicable)

```python-traceback
Spyder was unable to load the spyder3 icon theme. That's why its going to fallback to the theme used in Spyder 2
for that, please close this window and start Spyder again.
```

## Versions

* Spyder version: 5
* Qt version: 5.12.10
* PyQt version: 5.12.3
* SIP version: 6.1.0.dev2104271705
![spyder_ide_1](https://user-images.githubusercontent.com/79424595/154819751-526d5d01-30aa-4ec4-9b03-51d3f3c9f7cb.png)
![spyder_ide_2](https://user-images.githubusercontent.com/79424595/154819754-0d8b380b-55e9-4b3a-9037-bdf64e4c38d7.png)
![spyder_ide_33](https://user-images.githubusercontent.com/79424595/154819755-b0387419-001b-4366-8f79-f58011e0b63b.png)

* Operating System name/version: 10.0.22000 Build 22000

**Comment by ccordoba12** [comment]
Your comment on issue #4280 (reproduced below so you can't delete it):

> If you work for or with the Spyder development team, you should be fuckin fired. You straight up gave him a bullshit answer like Microsoft support does.

is full of insults and abusive words, so it's not going to be tolerated in our community.

Furthermore, that is a violation of our [Code of Conduct](https://github.com/spyder-ide/spyder/blob/master/CODE_OF_CONDUCT.md#our-standards), specifically this part:

> Examples of unacceptable behavior include:
> * Trolling, insulting or derogatory comments, and personal or political attacks

Therefore, I'm going to close this issue and ban you for a month from our organization.
