### ISSUE TITLE
Spyder missing dependencies after adding path to Python Path Manager

### ISSUE THREAD

**Issue by Aman1242** [spyder-ide/spyder#17392]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
````
You` have missing dependencies!

# Mandatory:
nbconvert >=4.0 : None (NOK)

Please install them to avoid this message.

Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you to install all the listed missing dependencies.

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.
```

To remedy I did the following steps after reading about them here [](https://github.com/spyder-ide/spyder/issues/8941) :

pip install nbconvert #used pip instead of conda as conda was returning nothing.


I also did 

import rtree
>>> rtree.__file__
'/Applications/Spyder.app/Contents/Resources/lib/python39.zip/rtree/__init__.pyc'



### What steps reproduce the problem?

1. I put a link to my python site library using the pythonpath manager so it would link yfinance
2. 
3. 

### What is the expected output? What do you see instead?
I don't want to see the error.


### Paste Traceback/Error Below (if applicable)
<!--- Copy from error dialog or View > Panes > Internal Console --->

```python-traceback

You have missing dependencies!

# Mandatory:
nbconvert >=4.0 : None (NOK)

Please install them to avoid this message.

Note: Spyder could work without some of these dependencies, however to have a smooth experience when using Spyder we strongly recommend you to install all the listed missing dependencies.

Failing to install these dependencies might result in bugs. Please be sure that any found bugs are not the direct result of missing dependencies, prior to reporting a new issue.

```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 5.2.1
* Python version: 3.9.5 (this is what spyder is saying it's using but I have installed 3.10.2
* Qt version: 
* PyQt version: 5
* Operating System name/version: Mac OS Monterrey

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @Aman1242 thank you for the feedback! Did the path you added to the Python Path Manager point to an env? If you want oto work with an different interpreter/env than the one that comes with the installer you should use the custom interpreter preference instead of adding paths to the Python Path Manager. If that is the case maybe this could help: https://docs.spyder-ide.org/current/faq.html#using-packages-installer

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
