### ISSUE TITLE
Variables declared in scripts do not show up in the variable explorer.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1739]
_From [royveldh...@gmail.com](https://code.google.com/u/116873003951520047426/) on 2014-02-24T07:03:36Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Simply enter a command in a script, e.g. a = 3
2. Run the script 3. What is the expected output? What do you see instead? I was expecting the variables to show up in the variable explorer, however I cannot find them anywhere, even when I disable all the exclusions. What version of the product are you using? On what operating system? Spyder Version:  2.1.11
Python Version:  2.7.3
Qt Version:      4.8.2, PyQt4 (API v2) 4.9.4 on Windows
Windows:         Windows 7 Enterprise 64-bit, with service pack 1. 

Please provide any additional information below

. I only get variables to show up in the variable explorer, when I declare then in the 'Python 1'-console. I was hoping that I would work in a similar way as MATLAB does, such that any variables declared in a script would automatically show up in the variable explorer.
Thanks in advance for your time.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1739_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-02-24T04:37:57Z_

Please update to our latest stable version (2.2.5) and try again. It's working for me as expected although you have to be aware that not all variables are shown in the variable explorer, just the types mentioned here http://pythonhosted.org/spyder/variableexplorer.html#supported-types

**Comment by spyder-issues-migrator** [comment]
_From [royveldh...@gmail.com](https://code.google.com/u/116873003951520047426/) on 2014-02-25T04:27:53Z_

Hello Ccordoba12,

Thanks for the quick reply. I've upgraded to Spyder 2.2.5 (I do not have administrator rights, so I bootstrapped it), but the problem seems to persist. Coming from a MATLAB background, I have encountered similar problems, if the working directory, was configured in a wrong way. However, I have set the console, the editor, and the working directory all to the same path.
Perhaps, something is wrong in the run-settings?
Also, I have taken a rather unusual path to come to this point. I'm working at a company, and they have a standard python 2.7.2 preinstalled. However, as I need the scientific version, and as I do not have administrator rights, I have installed python for scientists 2.7.3.0 over the old one (thus, without uninstalling the old version)
Might this be a reason for such an issue?
I do not think it is a variable that it is a variable that the variable explorer can not handle, the problem persists, for simple a = 3 commands.


Thanks,

Roy

**Comment by spyder-issues-migrator** [comment]
_From [royveldh...@gmail.com](https://code.google.com/u/116873003951520047426/) on 2014-03-03T05:39:46Z_

Hello everybody,

The problem solved itself, my company issued a windows update to last patch level W764 , and after installation of this update, the variable explorer worked again.

Thanks for the help

**Comment by goanpeca** [comment]
Can we close this then? @ccordoba12

**Comment by ccordoba12** [comment]
Yeah, sure. Please close it.

**Comment by martyca65** [comment]
I had this problem in Python 3.5.  I was able to variable explorer in sypder by doing a view and reset window layout.
