### ISSUE TITLE
Variable explorer and Plots panes simultaneously visible

### ISSUE THREAD

**Issue by caliari-italo** [spyder-ide/spyder#17394]
# Problem Description / Question

Is there a way of moving the Plots pane from
![image](https://user-images.githubusercontent.com/43014124/155529120-357c7275-0d8f-423d-994d-7fd28fa7812b.png)
to
![image](https://user-images.githubusercontent.com/43014124/155526611-650f5704-d826-47d8-9b05-f7980f7778a0.png)
so the Variable Explorer and Plots panes will be visible simultaneously, as presented in the figure from https://www.spyder-ide.org/ web page?

## Versions

* Spyder version: 5.2.2 None
* Python version: 3.8.10 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Linux 5.13.0-30-generic

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.3 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.2 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  None (NOK)

**Comment by rhkarls** [comment]
Try: `View` (on menu bar) -> `Unlock panes and toolbars`. Then drag the plots pane down to the console/history panes to dock it. Finally, go to `View` menu again and lock the panes.

**Comment by caliari-italo** [comment]
Unfortunately, unlocking panes and toolbars only had effect on the upper part of the UI as shown below. 
![image](https://user-images.githubusercontent.com/43014124/155550602-6dadd6c1-a15c-42dd-8fff-c115d78afb66.png)
