### ISSUE TITLE
Autoreload is not working

### ISSUE THREAD

**Issue by phollox-arch** [spyder-ide/spyder#17414]
### What steps will reproduce the problem?

I have activated the autoreload extensions, with a
from module.py import *

for the module I'm currently working on.

This is configured in the startup options of the Python interpreter. Changes are usually propagated inmmediately into the kernel without issues. However, currently is not the case. I see a bug in the console and fix it and re-execute the code and the error still there

**Comment by ccordoba12** [comment]
Hey @phollox-arch, thanks for reporting. We load the `autoreload` extension by default in our kernels, so you don't need to do it with a startup script.

What's your IPython version?
