### ISSUE TITLE
Unable to open Spyder in Ubuntu 20.04

### ISSUE THREAD

**Issue by Anirbanm0101** [spyder-ide/spyder#17418]
I have installed spyder in Ubuntu 20.04 (WSL) using conda forge. But it isn't opening. The error message is given below. 
```
Traceback (most recent call last):
  File "/home/anirban/anaconda3/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libXcursor.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/anirban/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/anirban/anaconda3/lib/python3.9/site-packages/spyder/app/start.py", line 233, in main
    from spyder.app import mainwindow
  File "/home/anirban/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 59, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/anirban/anaconda3/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```
What I understood is that the root of the error is the missing module 'PyQt5.QtWebKitWidgets'.I have searched on the internet for this error and found a lot of people had the same problem before. I tried the solutions provided there. But I am still getting the error. Any suggestion on how to resolve this?

**Comment by ccordoba12** [comment]
Hey @Anirbanm0101, thanks for reporting. You said:

> What I understood is that the root of the error is the missing module 'PyQt5.QtWebKitWidgets'

Nop, that's not the problem. The clue to solve it is at the beginning of the error you got:

    ImportError: libXcursor.so.1: cannot open shared object file: No such file or directory

This means that you don't have installed the Ubuntu package that provides that library.

You can find that here:

https://packages.ubuntu.com/search?searchon=contents&keywords=libXcursor.so.1&mode=exactfilename&suite=impish&arch=any

As you can see, the package name for that library is `libxcursor1`, so you need to install it with

    sudo apt install libxcursor1

In you case you get similar errors about missing libraries, just follow the same procedure.

**Comment by Anirbanm0101** [comment]
Thanks a lot. I installed the missing libraries and spyder is opening now.

**Comment by ccordoba12** [comment]
Great! I'm glad Spyder is working for you now.
