### ISSUE TITLE
Spyder won't start due to removal of soft_unicode from markupsafe package v. 2.1.0

### ISSUE THREAD

**Issue by mattslezak-shell** [spyder-ide/spyder#17420]
Spyder won't start due to removal of soft_unicode from markupsafe package v. 2.1.0

Error message is: `ImportError: cannot import name 'soft_unicode' from 'markupsafe' `

Looking at the latest release of this package https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

You can see that `soft_unicode` needs to be replaced with `soft_str` - that was deprecated but now removed as of the latest version.

The temporary workaround is to use the:

    conda install markupsafe=2.0.1

Or via pip: 

    pip install markupsafe==2.0.1

But since this function is gone, the Spyder code will have to now refer to `soft_str` instead of `soft_unicode`

**Comment by mattslezak-shell** [comment]
Here's the errors that happen before updating the markupsafe package:

**Comment by ccordoba12** [comment]
Thanks for that @mattslezak-shell! It seems this problem is resolved in any version of Jinja2 greater or equal than 3.0.

So please close Spyder, open the Anaconda Prompt and run there

    conda install jinja2=3

That should do the trick, but let us know if it works for you.

**Comment by mattslezak-shell** [comment]
Yes that works without modifying any files, thank you for the solution.  Probably should have Spyder dependencies updated to include that version as well so others don't have an issue.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. If we receive many more errors about this problem, we'll consider on fixing it on our side.
