### ISSUE TITLE
Import matplotlib works fine from the command line, but is not imported inside spyder

### ISSUE THREAD

**Issue by wfeiereisen** [spyder-ide/spyder#17434]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. I freshly installed anaconda and then installed spyder from anaconda.
2. when running python3.9 from the command line "import matplotlib" runs fine and the code produces the expected plot 
3. when running inside spyder "import matplotlib" fails

### What is the expected output? What do you see instead?

I expected a return to the REPL in the IPython console, but I see:
ModuleNotFoundError: No module named 'PIL'  instead

### Paste Traceback/Error Below (if applicable)

```python-traceback

In [5]: import matplotlib
Traceback (most recent call last):

  Input In [5] in <cell line: 1>
    import matplotlib

  File ~/.local/lib/python3.9/site-packages/matplotlib/__init__.py:109 in <module>
    from . import _api, _version, cbook, docstring, rcsetup

  File ~/.local/lib/python3.9/site-packages/matplotlib/rcsetup.py:27 in <module>
    from matplotlib.colors import Colormap, is_color_like

  File ~/.local/lib/python3.9/site-packages/matplotlib/colors.py:51 in <module>
    from PIL import Image

ModuleNotFoundError: No module named 'PIL'

```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Linux 5.4.0-100-generic 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  8.1.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.2 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.7.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.9.3 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.2 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
Hey @wfeiereisen, thanks for reporting. It is unclear if you are using Anaconda or not, but it seems you are.

If that's the case, please open a terminal and run the following command

    rm ~/.local/lib/python3.9

That will remove that directory and most probably fix your problem.

Please do that and let us know if it works for you.

**Comment by wfeiereisen** [comment]
Hi, Thank you, That worked! So that I understand, can you please tell me if ~/.local/lib/python3.9 was some other library that was pre-empting the anaconda-installed library?

**Comment by ccordoba12** [comment]
Yes, that's what was happening, i.e. the Matplotlib present in `~/.local/lib/python3.9` was shadowing the one in Anaconda.

That happens when you install packages using `pip install --user`, so please avoid doing that in the future.
