### ISSUE TITLE
Inconsistent "internal console" Pop up issue

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1743]
_From [stanch...@gmail.com](https://code.google.com/u/100801322819943756539/) on 2014-02-26T07:53:21Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.3
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

1. import any module with functions (eg import matplotlib.pyplot as plt)
2. call non-existent function of imported module via module "nickname" [eg plt.asd( ]
3. Error pops up as soon as you hit the command for left parenthesis (ie entering "plt.asd" works but as soon as i enter "plt.asd(" the error appears What is the expected output? What do you see instead? Expected output is I remain in IPython console, what in fact happens the system switches to the Internal console and prints the following error:

"
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.3.3.2\python-3.3.3.amd64\lib\site-packages\IPython\qt\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\WinPython-64bit-3.3.3.2\python-3.3.3.amd64\lib\site-packages\spyderlib\widgets\ipython.py", line 328, in _handle_object_info_reply
    argspec = getargspecfromtext(doc)
  File "C:\WinPython-64bit-3.3.3.2\python-3.3.3.amd64\lib\site-packages\spyderlib\utils\dochelpers.py", line 197, in getargspecfromtext
    blocks = text.split("\n\n")
AttributeError: 'NoneType' object has no attribute 'split'
" 

Please provide any additional information below

. I have reset all keyboard commands to default.
I use Spyder on two machines (identical Python and Spyder versions) -- on one machine the Internal Console does not pop up, on the other it does when I follow the "procedure" outlined above -- this is despite both machines having the Preferences - General - "Pop up internal console when internal errors appear" box checked. 
I have now unclicked the Pop up internal console on the machine where this error happened and the issue has stopped. However the inconsistency between running Spyder on one machine versus the other one is odd/ unusual.

Let me know if you need more information from me.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1743_

**Comment by goanpeca** [comment]
@ccordoba12  It has been a year now... no more feedback on this issue?
