### ISSUE TITLE
*** ModuleNotFoundError: No module named 'prody'

### ISSUE THREAD

**Issue by Pap8** [spyder-ide/spyder#17441]
### What steps will reproduce the problem?

Ubuntu 19 LTS, Create conda environment with python 3.9, install prody (http://prody.csb.pitt.edu/manual/getprody.html) and try to run .py file in spyder to import prody. Py script runs normally in PyCHarm, jup. notebook.  

Thanks!

**Comment by ccordoba12** [comment]
Hey @Pap8, thanks for reporting. Please read this entry in our docs to understand how to solve your problem:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if thaty solves the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
