### ISSUE TITLE
Custom settings for black autoformat

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#17450]
I wanted to use black autoformatting for some specific purposes only, i.e. disabling most of its functionality and just let it format some specific parts (e.g, whitespace managing and import sorting).

Is there any way to adapt the settings of the `black` instance being used? I could not find a `.toml` file anywhere?

btw: `black` was a really bad choice of name by the authors. try searching for issues with `black` and so much unrelated stuff pops up.

**Comment by rhkarls** [comment]
I'm pretty sure the Spyder plugin respects `pyproject.toml` and the `black` configuration in there. 
See https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-format

You can then place your `pyproject.toml` in the same folder as the file you want to format (see https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#where-black-looks-for-the-file), and run `black`. I just tested with adjusting `line-length` in the toml file, and that works.

Note that `black` in Spyder is not behaving entirely as it should https://github.com/spyder-ide/spyder/issues/17143

PS: I feel the pain re searching issues with common works, if its of help I recently discovered adding `in:title` to the filter (for example, `is:issue is:open in:title black` )

**Comment by ccordoba12** [comment]
> I wanted to use black autoformatting for some specific purposes only, i.e. disabling most of its functionality and just let it format some specific parts (e.g, whitespace managing and import sorting).

In that case, you can select the portion of text you want to auto-format with Black and go to the menu `Source > Format file or selection with Black`. Does that help too?

**Comment by skjerns** [comment]
> > I wanted to use black autoformatting for some specific purposes only, i.e. disabling most of its functionality and just let it format some specific parts (e.g, whitespace managing and import sorting).
> 
> In that case, you can select the portion of text you want to auto-format with Black and go to the menu `Source > Format file or selection with Black`. Does that help too?

perfect! Exactly what I needed :)

**Comment by ccordoba12** [comment]
Auto-sorting of imports needs that functionality added to the Python language server first (as I said in the other issues you posted earlier).

We'll try to implement it in the future.

**Comment by ccordoba12** [comment]
I'm going to close this issue because I think your questions are solved now. But please post here again if you any more info about it.
