### ISSUE TITLE
macOS app: UserWarning: Distutils was imported before Setuptools

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17460]
## Description

The Spyder macOS app shows the following warning in the Internal console for all builds at least after 5.2.2 (I haven't checked earlier versions or builds). This does not manifest for bootstrap from a conda environment for the same Spyder version.

```python
_distutils_hack/__init__.pyc:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
_distutils_hack/__init__.pyc:30: UserWarning: Setuptools is replacing distutils.
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.5
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.5.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.26 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.1 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

**Comment by ccordoba12** [comment]
I think this warning comes from spyder-kernels because we're still using distutils there to check for package versions.

Since that package still supports Python 2 and I wouldn't want to change that in the Spyder 5 series, this would have to wait until Spyder 6 to be fixed. Is that for you?

**Comment by mrclary** [comment]
> I think this warning comes from spyder-kernels because we're still using distutils there to check for package versions.

Hmm. I'm curious why it doesn't show up for bootstrap...

> Since that package still supports Python 2 and I wouldn't want to change that in the Spyder 5 series, this would have to wait until Spyder 6 to be fixed.

No problem. It is, after all, just a warning message and as far as I know there is nothing serious to worry about.

> Is that for you?

Do you mean if I want it assigned to me? That's fine. Did you mean something else?

**Comment by ccordoba12** [comment]
> Do you mean if I want it assigned to me? That's fine. Did you mean something else?

Sorry, I meant if that's ok for you, I mean leaving this for Spyder 6.

**Comment by ccordoba12** [comment]
Closing because no further work is going to be done in the old Mac app.
