### ISSUE TITLE
Find pane does not set focus in text field

### ISSUE THREAD

**Issue by maurerle** [spyder-ide/spyder#17475]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Ctrl+Shift+F does not focus on "Write text to search" anymore, as it did in Spyder 4.
This breaks any useful workflow with it.

The code looks like it should only switch to it, but setting the focus would be useful:
https://github.com/spyder-ide/spyder/blob/aecad5d083369913d5a876c19b69301758a274ce/spyder/config/main.py#L401

Using Alt+Shift+F works as a workaround if the relevant search phrase is marked, but does not work well, if I want to paste from clipboard (as I have to set the focus accordingly with the mouse)

https://github.com/spyder-ide/spyder/blob/aecad5d083369913d5a876c19b69301758a274ce/spyder/config/main.py#L537

With spyder4 Ctrl+Shift+F covered the workflow pretty well

### What steps reproduce the problem?

1. Cursor placed in code
2. Ctrl+Shift+F or Alt+Shift+F does nothing but switching the window, focus stays in code window
3. Ctrl+V pastes into code window

1. Cursor marked code
2. Alt+Shift+F searches for marked code, Ctrl+Shift+F does nothing

### What is the expected output? What do you see instead?

Pressing either sequence should put the cursor focus correctly into the search field

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.7
* Qt version: Qt 5.12.10
* PyQt version:  pyqt
* Operating System name/version: GNU/Linux Debian

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @maurerle, thanks for reporting. You're right about this problem and we'll try to fix it in a future release.
