### ISSUE TITLE
create html file in spyder

### ISSUE THREAD

**Issue by Monica-Xiao** [spyder-ide/spyder#17481]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
hey guys
I am learning Django with python recently and have spyder installed on my computer and solved the Django environment already.
But when I try to follow the step in the tutorial in which an HTML file is created in Pycharm, I have found that I could not find the available HTML template file in spyder. 
There are few answers on the internet or spyder's own website about how to create HTML files. Is that mean spyder does not have this function?
I have searched for days. Really appreciate it if someone could give me some tips.

## Versions
* Spyder 4: 
* Python 3.7: 
* django 3.0.5

**Comment by ccordoba12** [comment]
Hey @Monica-Xiao, thanks for reporting. Spyder is focused on developing Python code, so that's why when you create a new file, you always get a Python one.

However, if yo go to the menu `File > Save as...` and select a given name and set `.html` as its extension, Spyder will show it as an HTML file.

![imagen](https://user-images.githubusercontent.com/365293/158081586-5f923d36-86a3-4351-b62b-63df5360bd52.png)

Let us know if that solves the problem you're having or you need additional help.

**Comment by Monica-Xiao** [comment]
Thank you for the reply
Here is a screenshot from the Django tutorial that I am currently studying. After selecting to create an HTML file, the structure appears automatically. I have tried with your solution, but the file will be blank. 
1. Is it possible to get any existing templates from spyder? 
2.  And is spyder suitable for website development written in python?

![image](https://user-images.githubusercontent.com/54935139/158115262-1f8eb171-0805-44b0-bb67-c5efc981531a.png)

**Comment by ccordoba12** [comment]
> Is it possible to get any existing templates from spyder?

Ok, I see what you mean now. Unfortunately, we don't have templates for html files.

> And is spyder suitable for website development written in python?

Sadly, no. Spyder is designed to do scientific programming, i.e. working with Pandas, Numpy, Sympy, Scipy and Matplotlib.

Let us know if you need any additional help.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
