### ISSUE TITLE
input() not working

### ISSUE THREAD

**Issue by marco-zanin** [spyder-ide/spyder#17484]
### What steps will reproduce the problem?

#Simply running the line below leads to "Spyder has encountered an internal problem".

name = input("Enter your name:")

### Traceback
```python-traceback
  File "/Users/marcozanin/opt/anaconda3/envs/marco-zanin/lib/python3.7/site-packages/qtconsole/base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "/Users/marcozanin/opt/anaconda3/envs/marco-zanin/lib/python3.7/site-packages/spyder/plugins/ipythonconsole/widgets/debugging.py", line 313, in _handle_input_request
    if self._hidden:
AttributeError: 'ShellWidget' object has no attribute '_hidden'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.7.11
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 21.3.0

### Dependencies

```
applaunchservices >=0.1.7    :  0.2.1 (OK)
atomicwrites >=1.2.0         :  1.4.0 (OK)
chardet >=2.0.0              :  4.0.0 (OK)
cloudpickle >=0.5.0          :  2.0.0 (OK)
diff_match_patch >=20181111  :  20200713 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.22.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  6.3.0 (OK)
numpydoc >=0.6.0             :  1.2 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.8.0 (OK)
pygments >=2.0               :  2.11.2 (OK)
pylint >=0.25                :  2.9.6 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.9 (OK)
zmq >=17                     :  22.3.0 (OK)
qdarkstyle >=2.7             :  3.0.2 (OK)
qtawesome >=0.5.7            :  1.0.3 (OK)
qtconsole >=4.6.0            :  5.2.2 (OK)
qtpy >=1.5.0                 :  1.11.2 (OK)
rtree >=0.8.3                :  0.9.7 (OK)
sphinx >=0.6.6               :  1.8.5 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  3.1.1 (OK)
numpy >=1.7                  :  1.17.0 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
sympy >=0.7.3                :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @marco-zanin, thanks for reporting. This error is already fixed in our latest version (5.2.2).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if it works for you.

**Comment by marco-zanin** [comment]
Hi Carlos thanks for your prompt reply. I managed to create a new virtual environment and it works fine. Thanks for your help!

**Comment by ccordoba12** [comment]
Thanks for letting us know about it.

**Comment by ludop1** [comment]
Hey! thank you for the solution, but now when i create a new virtual environment and I import some libraries that i previously downloaded (with pip in the anaconda prompt) they are not available. How can i access them inside the virtual enviroment? thank you very much

**Comment by ccordoba12** [comment]
@ludop1, you have to install them in your new environment. If you need to work with Scikit-learn, for instance, then you have to close Spyder, open the Anaconda Prompt and run there

    conda activate spyder-cf
    conda install -c conda-forge scikit-learn

**Comment by ludop1** [comment]
Hey! thank you for the answer, i managed to re-install my pkgs using 'pip install --target=...' on my new path and it worked perfectly!
