### ISSUE TITLE
Tried 5.1.5 but did not debug; reverted to 4.1.5 then downgraded ipykernel back to 6.2.0

### ISSUE THREAD

**Issue by norbmett** [spyder-ide/spyder#17494]
### What steps will reproduce the problem?

Tried 5.1.5 but it did not debug.  Installed 5.2.2 as an app - but it it is running Python 3.7 (need 3.8).  Reverted back to Spyder 4.1.5 and now received an error

Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.31.1 -- An enhanced Interactive Python.

debugfile('C:/Users/Norb/UCSD_DSE210x/Topic 11-Statistics, Parameter Estimation and Confidence Interval/Topic11_sandbox.py', wdir='C:/Users/Norb/UCSD_DSE210x/Topic 11-Statistics, Parameter Estimation and Confidence Interval')
> c:\users\norb\ucsd_dse210x\topic 11-statistics, parameter estimation and confidence interval\topic11_sandbox.py(2)<module>()
      1 # -*- coding: utf-8 -*-
----> 2 """
      3 Created on Mon Mar  7 05:21:22 2022
      4 
      5 @author: Norb
      
The IDE does not look like Spyder 4.1.5 it still looks like 5.1.5; and the same problem stepping through with 5.1.5 is seen with 4.1.5 (starts debug on a comment)

### Traceback
```python-traceback
  File "C:\Users\Norb\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Norb\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 338, in _handle_input_request
    if self._hidden:
AttributeError: 'ShellWidget' object has no attribute '_hidden'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  2.0.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.31.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.1.0 (OK)
numpydoc >=0.6.0               :  1.2 (OK)
paramiko >=2.4.0               :  2.8.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.11.2 (OK)
pylint >=1.0                   :  2.9.6 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.3 (OK)
qtconsole >=4.6.0              :  5.2.2 (OK)
qtpy >=1.5.0                   :  1.11.2 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.4.0 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.3.0 (OK)

# Optional:
cython >=0.21                  :  0.29.25 (OK)
matplotlib >=2.0.0             :  3.5.1 (OK)
numpy >=1.7                    :  1.20.3 (OK)
pandas >=0.13.1                :  1.4.1 (OK)
scipy >=0.17.0                 :  1.7.3 (OK)
sympy >=0.7.3                  :  1.9 (OK)
```

**Comment by dalthviz** [comment]
Hi @norbmett thank you for the feedback! Seems like the downgrade left your installation somehow broken :/ Could you create a new env using the conda-forge channel, install Spyder 5.2.2 there and check again? For that you can run, from an Anaconda prompt, something like:

```
conda create -n spyder-env python=3.8 spyder=5.2.2 -c conda-forge
```

Let us know if that helps

**Comment by norbmett** [comment]
Daniel,
Thank you for your help.

I ran the command and it created spyder-env (environment); and debugging
began: first error following first statement:

import numpy as np

ModuleNotFoundError: No module named 'numpy'

There is a numpydoc package installed in the environment but not numpy.
Must I specify every package manually?

I appreciate any help you can provide.

Sincerely,
Norn

**Comment by norbmett** [comment]
Daniel,
I tried "conda -install -c conda-forge numpy" and had a little issue: I did not have CMD.exe installed for the new spyder-env and though I was selected to spyder-env, after running the install, numpy did not appear in Navigator.  So, I used Navigator 2.1.2 (circa 2015) to show which packages were not installed, then installed them with Navigator.  I am not sure which channel I was using (i.e., conda or  conda-forge); and, when I click on the "Channels" button next to the Applications on "spyder-env", a window popped up but could not read the content as it was positioned up above my terminal; and, I could not move it down or find on the task bar to move it, and it is positioned where only the bottom is showing the "Cancel" and "Update Channel" buttons.  Other than that, I was able to use Navigator to install numpy and matplotlib and their dependencies (again without knowing if I was getting it from conda or conda-forge).  

I am happy to be able to use Anaconda on my old Windows 7 laptop with Spyder and Jupyter to get through some training.

I appreciate your help very much 

V/R,
Norbert ("Norb") Metternich

**Comment by dalthviz** [comment]
No problem @norbmett glad to help! At the end if you managed to install what you needed and your setup is working then using navigator or the anaconda prompt are just different paths to reach the same goal :)

Also, just in case, you can check the packages you have installed in an env through the Anaconda prompt by activating the env and then running `conda list`. So, for example for the `spyder-env` you create, you can check the packages installed there by running from the Anaconda prompt something like:

    conda activate spyder-env
    conda list

If you are interested into checking more about how to use conda you can check the conda docs: https://docs.conda.io/projects/conda/en/latest/user-guide/getting-started.html
