### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by goshjung** [spyder-ide/spyder#17492]
### What steps will reproduce the problem?

1. anaconda3 navigation run
2. chnaged to virtual environments
3. lunch spyder in th navication
4. Issue reported happened
5. can not save the .py file with error message

### Traceback
```python-traceback
 C:\Users\DL\.spyder-py3\lsp_paths\root_path
Traceback (most recent call last):
  File "C:\Users\DL\anaconda3\envs\CV4\lib\site-packages\spyder\plugins\completion\providers\languageserver\client.py", line 543, in on_msg_received
    handler(resp['params'])
  File "C:\Users\DL\anaconda3\envs\CV4\lib\site-packages\spyder\plugins\completion\providers\languageserver\decorators.py", line 42, in wrapper
    params = req(self, *args, **kwargs)
  File "C:\Users\DL\anaconda3\envs\CV4\lib\site-packages\spyder\plugins\completion\providers\languageserver\client.py", line 582, in initialize
    'rootUri': pathlib.Path(osp.abspath(self.folder)).as_uri(),
  File "C:\Users\DL\anaconda3\envs\CV4\lib\pathlib.py", line 742, in as_uri
    raise ValueError("relative path can't be expressed as a file URI")
ValueError: relative path can't be expressed as a file URI
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.7.11
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  1.8.5 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.21 (OK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by dalthviz** [comment]
Hi @goshjung thank you for the feedback! Could you give us more information about the path your are using as your current working directory? Also do you have an specific file opened when this happens? If you reset your preferences the issue still happens?

Any new info in order to replicate this issue in our side is greatly appreciated. Let us know!

**Comment by goshjung** [comment]
Thanks for replay.
This is closed now.

Supposed the reason is....
To avoid the error, had commented some part of the \lib\pathlib.py temporarily 
 
File "C:\Users\DL\anaconda3\envs\CV4\lib\pathlib.py", line 658, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not NoneType
  File "C:\Users\DL\anaconda3\envs\CV4\lib\pathlib.py", line 658, in _parse_args
    a = os.fspath(a)


def _parse_args(cls, args):
        # This is useful when you don't want to create an instance, just
        # canonicalize some constructor arguments.
        parts = []
        
        for a in args:
            print('a=',a)
            if isinstance(a, PurePath):
                parts += a._parts

            # else: 
            #     a = os.fspath(a)
            #     if isinstance(a, str):
            #         # Force-cast str subclasses to str (issue #21127)
            #         parts.append(str(a))
            #     else:
            #         raise TypeError(
            #             "argument should be a str object or an os.PathLike "
            #             "object returning str, not %r"
            #             % type(a))
        return cls._flavour.parse_parts(parts)
