### ISSUE TITLE
Cycle tabs via Ctrl-PageUp/PageDown

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1749]
_From [minzas...@gmail.com](https://code.google.com/u/100341682938742242760/) on 2014-03-04T06:21:23Z_

Ctrl+Tab cycles through tabs, while Ctrl+PageUp/PageDown stops at last/first tab. This patch changes the behavior: when Ctrl+PageUp is pressed on the last tab, it moves to the first tab, and vice versa.

**Attachment:** [cycle_tabs.patch](http://code.google.com/p/spyderlib/issues/detail?id=1749)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1749_

**Comment by vtraag** [comment]
Related to this, Ctrl+(Shift+)Tab cycles through tabs in order of usage, while Ctrl+PageUp/PageDown cycles through tabs in order of appearance. Cycling through tabs in order of usage is not really useful it seems (you get apparently inexplicable jumps from one tab to another, until you realize it cycles in order of usage).

**Comment by blink1073** [comment]
@vtraag, I disagree that the cycling is not intuitive.  Ideally, the tabs would automatically reorder to preserve "most-recentness", similar to what you get when you hit `Alt+Tab` for most recent processes.  However, I'd argue that most times people are toggling back and forth between two files, regardless of the order they were opened in.  For what its worth, we have the same behaviour as the Sublime Text editor.

**Comment by vtraag** [comment]
Indeed I'm often switching between two files, and then it's useful. The problem starts when you are searching for another file among the ones you have open... Anyway, I'm now just resorting to Ctrl+PageUp/PageDown, which works fine for my purposes.

**Comment by jondo** [comment]
+1 to the patch.

> Ctrl+(Shift+)Tab cycles through tabs in order of usage [...] Cycling through tabs in order of usage is not really useful it seems

I think this _would_ be useful, but for me this also just cycles  in order of appearance (in Spyder 2.3.1 from WinPython-64bit-3.4.2.2.exe).

>  Ideally, the tabs would automatically reorder

No! Sometimes I want to define the order by myself, (see #564).

**Comment by blink1073** [comment]
@jondo, by that I mean *ideally for me*.
