### ISSUE TITLE
spyder automatic alignment

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1750]
_From [hesiyuan...@gmail.com](https://code.google.com/u/111119374578212631612/) on 2014-03-06T03:13:01Z_

Spyder Version:  2.2.4
Python Version:  2.7.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
IPython >=0.13  :  1.1.0 (OK)
matplotlib >=1.0:  1.3.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.5.0:  0.7.3 (OK)
pylint >=0.25   :  1.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2b2 (OK)
sympy >=0.7.0   :  0.7.3 (OK)

hey guys , i had met some problems when i used spyder . when coded some classed which have lots of method to define , and lots of indents(an deep layer relationship ) , it was easy for me to lost my direction  especially mixed with some explanatory notes . 
sometimes i completely  had no idea which layers the code line belong . it drived me crazy .
for example :
```
def morelayers():
    class test(Objective ):
       def __init__(self,parent=None):
       '''
       doc
       '''
       \# explanatory notes ..........
            warning : lost the matched indent
```

are there some good solution for spyder ??

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1750_

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-11T08:14:11Z_

In my system (Spyder 2.3.0beta3, Python 3.3/Anaconda) the autoindent works correctly (I rewrote your example)...

Your code, however, has 3 lines of indent in the `def __init__` line. Autoindent in this case worked ok with 2 spaces or 4 spaces of indent, but if you use tab indenting (i.e. Tools > Preferences > Editor > Advanced Settings > Indentation characters: "Tab") then you're mixing up 3 spaces and tabs, and the editor does get confused with indenting.

**Comment by goanpeca** [comment]
So, is this fixed?

**Comment by ccordoba12** [comment]
Alignment of the next line after a comment is not working as expected. This is a real bug.

**Comment by ccordoba12** [comment]
This was fixed a couple of weeks ago in master.
