### ISSUE TITLE
Spyder 5.2.2 crashes on startup (macOS)

### ISSUE THREAD

**Issue by nayfaan** [spyder-ide/spyder#17501]
### Issue Report Checklist

* [ ✓ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ✓ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ✓ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ✓ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ✓ ] Tried basic troubleshooting (if a bug/error)
    * [ ✓ ] Restarted Spyder
    * [ ✓ ] Reset preferences with ``spyder --reset``
    * [ ✓ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ✓ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ✓ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Cant open spyder 5.2.2 on Mac, basically identical problem as #16126
Spyder installed from the homepage https://www.spyder-ide.org

### What steps reproduce the problem?

1. Open spyder on Mac2. 

### What is the expected output? What do you see instead?

same as #16126

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.6
* Qt version: 
* PyQt version: 
* Operating System name/version: Big Sur 11.6

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @nayfaan thank you for the feedback! I'm not sure how we can get more info to debug this :/ 

@mrclary do you know a way to run the installer mac version from a terminal or make it generate the debug log? Any help here is appreciated :)

**Comment by mrclary** [comment]
@nayfaan @dalthviz 
Okay, normally you can restart Spyder in debug mode from the menu bar File->Restart in debug mode. Of course if Spyder doesn't even finish launching in the first place, then you don't have a menu bar! 😬 

However, you can launch the standalone Spyder macOS app from the command line. Open Terminal and use the following command (replacing your appropriate path to Spyder.app).
```bash
$ /<path>/<to>/Spyder.app/Contents/MacOS/Spyder --debug-info=verbose
```
You can then copy the output from the Terminal and paste it in a comment to this issue.

**Comment by nayfaan** [comment]
was just about to try… but then spyder just started to run normally for no reason… i guess i will do this the next time ot refuses to start

**Comment by dalthviz** [comment]
Thanks @mrclary for the info and then glad is working for you now @nayfaan !

I will leave this open for the moment (in case @nayfaan setup fails again in the near future) however if in the future you experience this again @nayfaan and this issue is closed (after sometime we usually close staled issues) feel free to open another one and put a reference to this one.

**Comment by jesol9** [comment]
Hello, I have the same problem right now and have made the steps you asked for before. Maybe you could help me sort this out? 

This is what i get after as output in the Terminal: 

dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Spyder.app/Contents/Frameworks/libpython3.9.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Spyder.app/Contents/Frameworks/libpython3.9.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by mrclary** [comment]
@jesol9, can you try updating Spyder to the latest version, 5.5.4?

**Comment by jesol9** [comment]
I just downloaded it today through their website. And when i try to open it and get the ''unexpected crash'' it tells me it's the version you mention. 

Is there any other information I can share to make it more clear what the issue is?

**Comment by mrclary** [comment]
@jesol9, okay let's verify a few things first, and hopefully we can resolve this for you.
* Can you provide which version of macOS you are running?
* Are you on macOS Intel or arm64? and did you download the appropriate Spyder version for your architecture?
* Execute the following command in a Terminal and paste the _entire_ contents of the Terminal in your comment.
  ```shell
  $ /<path>/<to>/Spyder.app/Contents/MacOS/Spyder --debug-info=verbose
  ```

**Comment by jesol9** [comment]
Okey, sounds good! 

- My macOS version is: High Sierra 10.13.6
- I'm on Intel Core i5, so I downloaded for Intel and not M1, I assume that was the right one but I very well could be wrong!
- This is all that pops up, and when I run it the same ''Problem report for Spyder''-window opens again.

Jespers-MacBook-Air:~ jesperolsson$ /Applications/Spyder.app/Contents/MacOS/Spyder --debug-info=verbose
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Spyder.app/Contents/Frameworks/libpython3.9.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/Spyder.app/Contents/Frameworks/libpython3.9.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

**Comment by jesol9** [comment]
Okey i see.

I downloaded that version and when I opened it a window poped up that said: 
**Launch error** See the py2app website for debugging launch issues
and then it gave me two options:
- visit website 
- Terminate 

Do you know what the problem might be now?

**Comment by mrclary** [comment]
> Okey i see.
> 
> I downloaded that version and when I opened it a window poped up that said: **Launch error** See the py2app website for debugging launch issues and then it gave me two options:
> 
> * visit website
> * Terminate
> 
> Do you know what the problem might be now?

@jesol9, I'm sorry, I do not know what the issue could be. Unfortunately, we have a very small team of developers and don't have the resources to support macOS versions prior to 11 ☹️. Since the standalone Spyder 5.3.2 did not work, the only other recommendation I can make is to install Anaconda, create a conda environment, and install Spyder from conda-forge. See instructions [here](https://docs.spyder-ide.org/current/installation.html#conda-based-distributions).

**Comment by ccordoba12** [comment]
I think the problem is @jesol9 is using **10.13**

> My macOS version is: High Sierra 10.13.6

and the first Mac version supported by our app was **10.15**.

@jesol9, so unless you update to at least 10.15 you won't be able to use our app.

**Comment by jesol9** [comment]
Hello, 
Thank you so much guys, I'll have to update my Mac then and hope it survive!
