### ISSUE TITLE
Changing conda environments with spyder preferences does not work.

### ISSUE THREAD

**Issue by RolfChung** [spyder-ide/spyder#17504]
Hello,

my goal is to use conda environments in Spyder.
The conda env work fine in Jupyter Lab.

OS: Windows
Python 3.9.7
conda 4.12

I read the doc here:
https://docs.spyder-ide.org/current/faq.html

I did install Spyder with miniconda in base and installed spyder-kernels in the env.
I start Spyder in base and then try to change the env with tools\python interpreter\preferences.

I cannot change the env and get the error.

The code execution cannot proceed zlib.dll was not found.
Reinstalling the program may fix this problem.

Then afterwards I get the message "Invalid file path"

I reinstalled spyder and the file path is correct, I guess.

There are two similar issues here, describing maybe similar problems, but I am missing a solutions?
e.g. https://github.com/spyder-ide/spyder/issues/17380

Is this a version conflict with Python > 3.9
Do I need to install additional packages.
My assumption was that when I install spyder with conda I get all the requirements satisfied.
No fix in the doc.

How can I solve the errors?

**Comment by dalthviz** [comment]
Hi @RolfChung thank you for the feedback! What version of Python are you using in the created env? Could be Python 3.10.0?

Could you create a new env using the conda-forge channel? (I think Python 3.10.2 is not available in the default anaconda channel)

Let us know!

**Comment by ccordoba12** [comment]
This issue is a duplicate of #17380 and we'll try to fix it in a future version (we still don't know why it happens).
