### ISSUE TITLE
Debugger not Function in Spder 5.2.2

### ISSUE THREAD

**Issue by Edward-Chan** [spyder-ide/spyder#17519]
### What steps will reproduce the problem?

I have install the Spyder 5.2.2 by pip.
Python version 3.9.4

1. Add one or two breakpoint to the function (inside the for loop)
2. Click the debug buttom.
3. The code runs as we click the run buttom.

def test(n):
    for i in range(n):
        print("Test : ", i)

test(10) 

below is the output
======================================

Python 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython  -- An enhanced Interactive Python.

debugfile('C:/Users/admin/Documents/debug_test.py', wdir='C:/Users/admin/Documents')
Test :  0
Test :  1
Test :  2
Test :  3
Test :  4
Test :  5
Test :  6
Test :  7
Test :  8
Test :  9

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.4
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.24.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.5.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.10.3 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  60.10.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.0 (OK)
pandas >=1.1.1                :  1.2.4 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Edward-Chan, thanks for reporting. I don't understand what you mean by this problem.

Please create a video or an animated gif with the [Licecap](https://www.cockos.com/licecap/) program and post it here, so we can better understand your problem.

**Comment by dalito** [comment]
```
2. Click the debug buttom.
3. The code runs as we click the run buttom.
```

Step 3. is wrong for debugging. By clicking "run" you run the code without debugger. After you started debugging you have to use the blue icons (or the keyboard). For example, if a breakpoint is set in the loop, you should be able to see that i is incremented after each time you press "Continue execution until next break point" (CTRL+F12).

**Comment by ccordoba12** [comment]
Closing due to lack of response.
