### ISSUE TITLE
Dependencies window only shows external plugin

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17535]
## Description

Bootstrap shows only the external plugin in dependencies window and spyder-terminal works.
macOS app shows all except the external plugin and spyder-terminal does not work.

### What steps will reproduce the problem?

```bash
$ python bootstrap.py --safe-mode
```
<img width="972" alt="Screen Shot 2022-03-23 at 11 55 05 PM" src="https://user-images.githubusercontent.com/9618975/159862378-3a517dd1-9aff-43eb-8ac5-9bb4d9b1d881.png">

macOS app
<img width="1120" alt="Screen Shot 2022-03-23 at 11 57 39 PM" src="https://user-images.githubusercontent.com/9618975/159863458-caa4067b-89b6-4d6c-8662-bae68cde7c19.png">

## Versions

* Spyder version: 5.3.0.dev0 d3abf352f
* Python version: 3.9.10
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7            :  0.2.1 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.4.4 (OK)
numpydoc >=0.6.0                     :  1.2 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0                 :  1.3.2 (OK)
pylsp_black >=1.0.0                  :  1.1.0 (OK)
qdarkstyle =3.0.2                    :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0             :  5.2.2 (OK)
qtpy >=1.5.0                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  60.10.0 (OK)
sphinx >=0.6.6                       :  4.4.0 (OK)
spyder_kernels >=2.2.1;<2.3.0        :  2.3.0.dev0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=2.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.1 :  1.2.1 (OK)
```

**Comment by mrclary** [comment]
Something is wrong with my system, because this manifests on bootstrap of 5.2.2 checkout...

**Comment by dalthviz** [comment]
Just in case, I checked with the Windows installer generated at #17533 and seems like all the dependencies are being shown:

![imagen](https://user-images.githubusercontent.com/16781833/159947854-2d217a00-52a6-4361-b0dc-ed5e8c43ad15.png)

Checking with the latest 5.x https://github.com/spyder-ide/spyder/commit/d3abf352f1fa72507413ca9eeb9c594bc2d5ee3c I also get all the dependencies:

![imagen](https://user-images.githubusercontent.com/16781833/159948329-050b2bc5-56e3-45db-a673-1464b34635d1.png)

Maybe something is happening when parsing/computing the dependencies on MacOS?

**Comment by mrclary** [comment]
Okay, the issue with bootstrap is a non-issue: I was opening the dependencies window before they were computed. If I wait just a little longer or close and reopen the window, the dependencies are there, including spyder-terminal.

However, for the macOS app, the spyder-terminal still does not show up even though it is installed in the application. I'll have to investigate at which commit this manifested to understand what changed.

@dalthviz, I'm hoping that there is something simple like parsing the dependencies, as you suggest.

**Comment by mrclary** [comment]
The issue is isolated to #16651. Updating `py2app` has caused spyder-terminal to stop loading. I'll have to investigate.

**Comment by mrclary** [comment]
It appears that `pkg_resources` does not locate any `entry_points` for _any_ packages which have `.dist-info` files in `python39.zip`. This could be a problem for more than just `spyder-terminal`. I don't think this is directly related to `py2app`; it is a bug/feature of `pkg_resources` since simply copying the `dist-info` file to the `python3.9` directory after app bundling alleviates the issue.

I'll do some more research...

**Comment by mrclary** [comment]
Closing this issue since the primary problem was not a problem.
