### ISSUE TITLE
aaaaaaaaaaaaaaa

### ISSUE THREAD

**Issue by candrafn** [spyder-ide/spyder#17539]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @candrafn I'm closing this since no useful information was given. However, it could be that you are using a really old version of Spyder. The latest Spyder release is 5.2.2 so an update could help you
