### ISSUE TITLE
Error opening spyder-ide from a docker image

### ISSUE THREAD

**Issue by caliari-italo** [spyder-ide/spyder#17542]
Hello everyone

I'm trying to open spyder-ide using TensorFlow gpu docker image but I'm getting the following error...

```
root@350X:/home# spyder
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

I tried reinstalling the application and getting these plugins but had no success in opening spyder.

The Dockerfile used to build the image is:

```
FROM tensorflow/tensorflow:latest-gpu
RUN apt-get update
RUN apt-get install python3-opencv libasound2 -y
RUN pip install --upgrade pip
RUN pip install spyder
RUN pip install numpy
RUN pip install pandas
RUN pip install sklearn
RUN pip install matplotlib
WORKDIR /home
```

and the docker arguments used to start the image are
```
sudo docker run -it \
    --gpus all \
    --env="DISPLAY" \
    --net=host \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $PWD:/home imagename/imagename \
    spyder
```
Any ideas how could I open spyder on the host machine using a docker image ?

**Comment by dalthviz** [comment]
Hi @caliari-italo thank you for the feedback! Not totally sure but maybe running something like `apt-get install libxcb-xinerama0` could help.

Checking a little bit the message seems like reinstalling libxcb helps: https://forum.qt.io/topic/93247/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/8

Let us know if something of the above helps!

**Comment by caliari-italo** [comment]
Unfortunately it didn't worked for me.

I forgot to mention that opening Firefox or xclock was able from the start, if it's of any help.

**Comment by caliari-italo** [comment]
This was very helpful, thanks. Now the spyder-ide starts and crashes a second later, which I consider a big improvement.

The error I receive now is:
```
root@350X:/home# QT_DEBUG_PLUGINS=1
root@350X:/home# spyder
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
[44:44:0324/182406.491713:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

I searched this error and found it was recommended to start the app with the --no-sandbox argument but it generated :
```
root@350X:/home# spyder --no-sandbox
usage: spyder [options] files
spyder: error: unrecognized arguments: --no-sandbox
```

**Comment by dalthviz** [comment]
Nice, some progress! Could you try to set the env var `QTWEBENGINE_DISABLE_SANDBOX=1` before launching Spyder?

Seems like running from root is not possible for Spyder since it uses QtWebEngine, some more info regarding qt applications running from root that use QWebEngine related things: https://forum.qt.io/topic/94721/running-as-root-without-no-sandbox-is-not-supported

**Comment by caliari-italo** [comment]
Thank you very much, @dalthviz 

It worked just fine initiating spyder with:
`env QTWEBENGINE_DISABLE_SANDBOX=1 spyder` insted of just `spyder`

Now spyder-ide can be run directly from a isolated docker image based on tensorflow-gpu

**Comment by dalthviz** [comment]
Awesome! Glad to help and that your setup with docker is working now :+1:

**Comment by skjerns** [comment]
btw, this trick also works when wanting to start Spyder in WSL
