### ISSUE TITLE
Update Spyder to handle newer python-lsp-server (v1.4.0)

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#17550]
## Problem Description

Hi!  https://github.com/python-lsp/python-lsp-server has been upgraded to 1.4.0, but Spyder itself says it can only handle versions less than 1.4.0.  I'm presuming this is on some checklist for resolving at some point, but I couldn't see it.

**Comment by dalthviz** [comment]
Hi @juliangilbey ! I think we will be bumping up the constraint when we release Spyder 5.3.0 (hopefuly next week). Maybe @ccordoba12 has more info about that

**Comment by juliangilbey** [comment]
So exciting! Thanks! (Meanwhile, I'm trying to build pydevd and debugpy for Debian, which is taking a lot of effort!)

**Comment by ccordoba12** [comment]
This will come in 5.3.0, as @dalthviz said.

@juliangilbey, please don't push for things like this next time. We maintain python-lsp-server, qtconsole, python-lsp-black and several projects. Sometimes they need to be released before the next Spyder version and the only way to bump their constraints here is to wait for the next release.

**Comment by juliangilbey** [comment]
OK @ccordoba12, I'll wait patiently next time! Thanks for your ongoing amazing work!

**Comment by ccordoba12** [comment]
Thanks to you too for understanding!

**Comment by dalthviz** [comment]
Just in case, maybe for future releases it could be useful to have an issue to describe the plan that we have regarding a release in terms of for example dependencies version support (as the question here), difficulties being faced, in general things that are implicit to the release but that don't have an issues for the corresponding GitHub milestone. With that, I think, we will let users and contributors know in a more clear way the state of release and we will give them more info about what is going on in terms of the release planning

**Comment by ccordoba12** [comment]
Sure, I think that's a good idea and I was thinking about that too, so that our release manager (which has been you @dalthviz for the last releases) also knows what package versions need to bumped before the release.

I'll open a new issue about it for this release.
