### ISSUE TITLE
IPython kernel error with debugpy 1.6.0

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17552]
`debugpy` was updated to 1.6.0 22 hours ago and is used by `ipykernel` and results in the following error in the IPython Console.
<img width="658" alt="Screen Shot 2022-03-25 at 12 07 33 PM" src="https://user-images.githubusercontent.com/9618975/160185782-6d10a3ef-ab6b-4c67-978e-a0778f396223.png">

This is an evolution of the problem in #16828. I'll provide a fix in a subsequent PR.

**Comment by dalthviz** [comment]
Just in case, checking this with the Windows installer donwloaded from https://github.com/spyder-ide/spyder/pull/17522 I can also see the message (although as console output):

![imagen](https://user-images.githubusercontent.com/16781833/160193948-a1f5827e-7d54-4d9e-8d37-e7534cb4fea2.png)

**Comment by mrclary** [comment]
@dalthviz, why do you think that the kernel starts for the Windows app but not the macOS app? Maybe because the file hasn't been byte compiled (yet?) on Windows? `ntpath.py` vs. `posixpath.pyc`?

**Comment by ccordoba12** [comment]
> why do you think that the kernel starts for the Windows app but not the macOS app?

I think that depends on how quickly the kernel starts. Sometimes the error kernel message is shown, others the console starts and the message is printed later (as in @dalthviz screenshot).
