### ISSUE TITLE
Windows 8.1 Spyder GUI locks up when memory passes "100&#37;"

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1755]
_From [kenra...@gmail.com](https://code.google.com/u/111620485265737384945/) on 2014-03-13T11:33:04Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.4, PySide 1.2.1 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?
1. Just set a loop to fill an array and let it pass 10**9. Machine halts in that the processors stop and the mouse is unresponsive. 2. 3. What is the expected output? What do you see instead? 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1755_

**Comment by spyder-issues-migrator** [comment]
_From [kenra...@gmail.com](https://code.google.com/u/111620485265737384945/) on 2014-03-13T09:37:00Z_

This has happened many times. Wish there was a way to increase memory to physical limit or have Spyder notice that some limit is about to be reached. Seems it is just locking up.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-03-15T08:26:25Z_

I guess not just Spyder but also all your programs lock up when there is no memory available.

I don't think this is going to be easy to implement though

**Status:** HelpNeeded  
  **Labels:** Cat-Miscelleneous

**Comment by goanpeca** [comment]
No feedback for over a year. Closing
