### ISSUE TITLE
Spyder crashes sometimes when inspecting object with LLVM ERROR

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#17571]
## Problem Description

I assigned CTRL+E to inspect items in both the editor and console. When inspecting objects in the console, sometimes spyder crashes with the following error message. It simply exits the process and dissapears. This happens on a Linux server running Debian.

```
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
```

Unfortunately there is no way to replicate it, and no further output happening. If you tell me where to look, I can check.

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                          :  1.4.0 (OK)
chardet >=2.0.0                               :  3.0.4 (OK)
cloudpickle >=0.5.0                           :  1.6.0 (OK)
cookiecutter >=1.6.0                          :  1.7.3 (OK)
diff_match_patch >=20181111                   :  20200713 (OK)
intervaltree >=3.0.2                          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0                        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0                         :  0.17.2 (OK)
jellyfish >=0.7                               :  0.8.9 (OK)
jsonschema >=3.2.0                            :  3.2.0 (OK)
keyring >=17.0.0                              :  21.4.0 (OK)
nbconvert >=4.0                               :  6.0.7 (OK)
numpydoc >=0.6.0                              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0                          :  0.7.1 (OK)
pexpect >=4.4.0                               :  4.8.0 (OK)
pickleshare >=0.4                             :  0.7.5 (OK)
psutil >=5.3                                  :  5.7.2 (OK)
pygments >=2.0                                :  2.7.2 (OK)
pylint >=2.5.0                                :  2.6.0 (OK)
pyls_spyder >=0.4.0                           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0                          :  1.3.2 (OK)
pylsp_black >=1.0.0                           :  1.0.0 (OK)
qdarkstyle =3.0.2                             :  3.0.2 (OK)
qstylizer >=0.1.10                            :  0.2.1 (OK)
qtawesome >=1.0.2                             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0                      :  5.2.1 (OK)
qtpy >=1.5.0                                  :  1.9.0 (OK)
rtree >=0.9.7                                 :  0.9.7 (OK)
setuptools >=49.6.0                           :  50.3.1.post20201107 (OK)
sphinx >=0.6.6                                :  3.2.1 (OK)
spyder_kernels >=2.2.1;<2.3.0                 :  2.2.1 (OK)
textdistance >=4.2.0                          :  4.2.1 (OK)
three_merge >=0.1.1                           :  0.1.1 (OK)
watchdog >=0.10.3                             :  0.10.3 (OK)
xdg >=0.26                                    :  0.27 (OK)
zmq >=17                                      :  22.3.0 (OK)

# Optional:
cython >=0.21                                 :  0.29.21 (OK)
matplotlib >=2.0.0                            :  3.5.1 (OK)
numpy >=1.7                                   :  1.19.2 (OK)
pandas >=1.1.1                                :  1.1.3 (OK)
scipy >=0.17.0                                :  1.8.0 (OK)
sympy >=0.7.3                                 :  1.6.2 (OK)

# Spyder plugins:
spyder_line_profiler.spyder.plugin 0.5.1.dev0 :  0.5.1.dev0 (OK)```

**Comment by dalthviz** [comment]
Hi @skjerns thank you for the feedback! Is there any specific code or set of libraries/packages that when inspected show this error for you? Maybe running Spyder in debug mode could somehow let us get more info about what is happening. To run Spyder in debug mode you can either select the option in `Files > Restart in debug mode` and there select the `Verbose` option (that should generate an `spyder-debug.log` file under the Spyder config folder) or run Spyder from a console/terminal with the flags `--debug-info verbose` (which by default will show the log on the console/terminal).

Let us know running in debug mode gives more info

**Comment by ccordoba12** [comment]
Perhaps this is caused by old system libraries linked by the Qtwebengine conda packages.

In that case, PR #16518 should be the solution to that.

**Comment by skjerns** [comment]
On another note, I installed `llvmlite` via `pip install llvmlite` (as suggested in other forums), and it also seems to have resolved the issue as well. If you want I can uninstall and check in debug mode what the possible problem was?

**Comment by dalthviz** [comment]
Thanks for the new info @skjerns ! I don't think the uninstall is necessary since seems like this is not related with Spyder itself however, could you post here some links to the forums where you find the suggestion for future reference? Thanks again!

**Comment by skjerns** [comment]
cannot reproduce this anylonger, even with `llvmlite uninstalled`

I found the hint here: https://github.com/conda-forge/llvmlite-feedstock/issues/54
