### ISSUE TITLE
How to integrate Github with Spyder?

### ISSUE THREAD

**Issue by teohsinyee** [spyder-ide/spyder#17575]
I want to clone a Github repo and work in Spyder.

**Comment by dalthviz** [comment]
Hi @teohsinyee thank you for the question! Currently there is no way to clone a repository from within Spyder. For the moment, you will need to clone the repo (using on Windows git bash for example or installing git in some way in your system to do the clone) and then make the generated directory a Spyder project.

For more info about the Projects plugin and capabilities you can check our documentation page: https://docs.spyder-ide.org/current/panes/projects.html

Let us know if the info above helps or if you have more questions

**Comment by teohsinyee** [comment]
Thanks @dalthviz , the documentation provided is very helpful and I managed to use Spyder with Github now.
