### ISSUE TITLE
runfile('C:/Users/LucasM/.spyder-py3/temp.py', wdir='C:/Users/LucasM/.spyder-py3') message

### ISSUE THREAD

**Issue by almeidaname** [spyder-ide/spyder#17574]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
![python](https://user-images.githubusercontent.com/102629604/160715045-cb1b7449-1c85-4a5b-bc72-74aafcc588fb.PNG)

* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
to be honest I am new to python and my boss wants me to create a smart schedule where I will be able to match all of our employees with available times with all of our clients to maximize how many patients we can see in a day I don't know where to start so I found online a few stuff and came up with the code in the picture to see if I had a beginning with only 1 patient and 1 client and when I run the code I get the message runfile('C:/Users/LucasM/.spyder-py3/temp.py', wdir='C:/Users/LucasM/.spyder-py3')

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

``

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
