### ISSUE TITLE
Can't run files with space in path via external terminal

### ISSUE THREAD

**Issue by athompson673** [spyder-ide/spyder#17595]
I dumped the cmd being called from spyder.util.programs (line 764ish) with a simple print statement, and nothing seems immediately wrong, but `[WinError 267] The directory name is invalid` is consistently thrown.

Cmd:
> start cmd.exe /K "cd "Y:\Users\aaron\python scripts" && "C:\Users\aaron\python\py39\python.exe" -i "Y:\Users\aaron\python scripts\helloworld.py"" ^&^& exit

I can even separately copy and paste the command into a different terminal (just python inside cmd; no IDE) and call the following without issue:

```
from subprocess import Popen
Popen(r'start cmd.exe /K "cd "Y:\Users\aaron\python scripts" && "C:\Users\aaron\python\py39\python.exe" -i "Y:\Users\aaron\python scripts\helloworld.py"" ^&^& exit', shell=True)
```
Including the `cwd` arg does not make a difference either when using Popen myself, but if I modify spyder.utils.programs.py at line 762 to be:
```
        try:
            # if wdir:
            #     run_shell_command(cmd, cwd=wdir)
            # else:
                run_shell_command(cmd)
```
the problem is solved.

Am I missing something, or does the "cd" command included in the `cmd` string take care of not needing the `cwd` argument? I also cannot figure out why it's an issue for spyder to include `cwd` but not when I do it in a terminal myself...

* Spyder version: 5.3.0 None
* Python version: 3.9.6 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
Hey @athompson673, thanks for reporting. You said

> does the "cd" command included in the cmd string take care of not needing the cwd argument?

It seems it does, so we don't need to pass it again to `run_shell_command`.

@dalthviz, could you test that on Windows to see if that's the case? Thanks!

**Comment by athompson673** [comment]
This seems like it may also affect linux systems at [line 795](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/programs.py#L795)? IDK, I don't have a linux PC handy.

**Comment by mrclary** [comment]
> This seems like it may also affect linux systems at [line 795](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/programs.py#L795)? IDK, I don't have a linux PC handy.

It does not. For Linux systems (lines 770-794), the script file does not include `cd`, but `run_program` does include `cwd`; here `wdir` is not a quoted string. For macOS (lines 795-815), the script does include `cd`, but the `run_shell_command` does not include `cwd` keyword argument.

**Comment by dalthviz** [comment]
@ccordoba12 I was able to reproduce this on Windows. If I run a file that has a space in his path I get the following message: 

![imagen](https://user-images.githubusercontent.com/16781833/161602559-4a02f4c0-7a53-44f5-aa4e-940a2fa4c211.png)

If the file path doesn't have a space it runs as expected

**Comment by mrclary** [comment]
Will it work on windows if there are spaces in `wdir` but we don't quote it? i.e. `cwd='path with space'` instead of `cwd='"path with space"'`. It may be more pythonic to remove `cd` from temporary script and use the `cwd` keyword argument.

**Comment by athompson673** [comment]
> here `wdir` is not a quoted string.

Isn't it? The quotes get added before the OS switching at [line 737](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/programs.py#L737)



> Will it work on windows if there are spaces in `wdir` but we don't quote it? i.e. `cwd='path with space'`

I believe it is *required* to be un-quoted when it is passed as the `cwd` argument to Popen (inside `run_shell_command`) at least on Windows, however it seems like Linux and MacOS scripts may still need `wdir` to be quoted because they are used to build shell commands as strings / shell script. I don't have linux on any of my computers, but I think it needs to be tested.

The linux logic could possibly be simplified as it seems specifying the `"wdir-option"` in the command args as well as passing `wdir` to `run_shell_command` seems redundant like the Windows case.

**Comment by mrclary** [comment]
> > here `wdir` is not a quoted string.
> 
> Isn't it? The quotes get added before the OS switching at [line 737](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/programs.py#L737)

You are correct. I miss-read the code.
 
> > Will it work on windows if there are spaces in `wdir` but we don't quote it? i.e. `cwd='path with space'`
> 
> I believe it is _required_ to be un-quoted when it is passed as the `cwd` argument to Popen (inside `run_shell_command`) at least on Windows, however it seems like Linux and MacOS scripts may still need `wdir` to be quoted because they are used to build shell commands as strings / shell script. I don't have linux on any of my computers, but I think it needs to be tested.
> 
> The linux logic could possibly be simplified as it seems specifying the `"wdir-option"` in the command args as well as passing `wdir` to `run_shell_command` seems redundant like the Windows case.

Yes, I think it most pythonic to use the `cwd` keyword argument wherever possible; it likely requires unquoted string for all platforms, but should be verified. For linux, then, `wdir-option` could be removed and `cd` should be removed from both nt and darwin, with `cwd` added to the darwin case. The temporary file may not be necessary for darwin either, but I'd have to verify the interaction of Terminal.app with the provided `env` keyword for `Popen`...

**Comment by ccordoba12** [comment]
@mrclary, could you give us a hand with this one, since it seems you understand well what needs to be done? Thanks!
