### ISSUE TITLE
Changelog too large to render on Github

### ISSUE THREAD

**Issue by b-a0** [spyder-ide/spyder#17598]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The [changelog](https://github.com/spyder-ide/spyder/blob/master/CHANGELOG.md) has become too large for Github to render. It is still available, but only as a [raw unformatted file](https://raw.githubusercontent.com/spyder-ide/spyder/master/CHANGELOG.md)

### What steps reproduce the problem?

1. Visit the changelog in your browser at: https://github.com/spyder-ide/spyder/blob/master/CHANGELOG.md 

### What is the expected output? What do you see instead?

**Expected output**
A Markdown rendering of the changelog is shown, such as e.g. [on the `3.x.` branch](https://github.com/spyder-ide/spyder/blob/3.x/CHANGELOG.md).

**Actual output**
Github shows a message with a link to the raw file:

> This blob took too long to generate.
> But you can view the raw file

### Suggested remedy
Perhaps you can split the changelog per major version and link to that on every release?

**Comment by ccordoba12** [comment]
Hey @b-a0, thanks for reporting. I'll fix this by creating a new changelog file for older Spyder versions (i.e. Spyder 3 and 2).
