### ISSUE TITLE
Install without green frame / border

### ISSUE THREAD

**Issue by Enesma** [spyder-ide/spyder#17597]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ x ] Restarted Spyder
    * [ x ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Since installing Spyder via Anaconda for the first time I get a green frame around Spyder. I donot see thison my work laptop.
I have tried to remove Anaconda as good as possible, but when trying to install Spyder standalone the frame is still there.
After installation on windows I do not have a short cut in the start menue, I do on the work laptop.
It is all fine on the work laptop and I d onot understand why...

### What steps reproduce the problem?

1. Install Spyder_64bit_full.exe
2. 
3. 

### What is the expected output? What do you see instead?
Installation without the frame, as on my work latop

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.0
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: Win 10

![Screenshot 2022-04-01 230335](https://user-images.githubusercontent.com/51157458/161341003-2ab157e2-11dd-4356-a6fb-ca40279c1034.png)

**Comment by ccordoba12** [comment]
Hey @Enesma, thanks for reporting. I'm sorry but this doesn't seem a problem with Spyder but with your computer. So the only advice I can give you is to google for related problems and try to find the solution elsewhere.

**Comment by Enesma** [comment]
Dear Cordoba, it's not like have not try to find solutions in the world wide web. I believe it has something to do with how you install Spyder and it interacts with Anaconda. I am a bit disappointed, by the advice to "google". Therefore, I have asked the question [here](https://stackoverflow.com/questions/71716906/green-frame-around-spyder-anaconda-interfering) For others, to find it.
