### ISSUE TITLE
Installation of Spyder Breaks Cisco Anyconnect on Ubuntu 12.04

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1760]
_From [srt...@gmail.com](https://code.google.com/u/116317945554208198333/) on 2014-03-21T08:46:32Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?
1. Install Spyder
   1. Use Cisco Anyconnect to connect to a server.
   2. Notice that the connection resets every 2 seconds. What is the expected output? What do you see instead? I expect the VPN to have a constant, stable connection.
      Instead, I see resets every 2 seconds. I duplicated this twice.
      The fix: Uninstall Spyder and reinstall Anyconnect. What version of the product are you using? On what operating system? Ubuntu 12.04
      Cisco Anyconnect 3.0.08057
      Spyder 2.1.9-1 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1760_

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-22T15:45:43Z_

Just to complement the info, how did you install Spyder?
(and why are you using 2.1.9-1 ?)

**Comment by spyder-issues-migrator** [comment]
_From [srt...@gmail.com](https://code.google.com/u/116317945554208198333/) on 2014-03-27T15:19:20Z_

I installed Spyder using ubuntu's software installation tool. I determined
later that restarting the anyconnect services was a workaround. Installing
Spyder should not interfere with VPN.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-16T09:48:57Z_

I really don't know in which way it could interfere with VPNs. But I'm glad you found a workaround.

**Labels:** Cat-Miscelleneous

**Comment by ccordoba12** [comment]
Very old bug, closing.
