### ISSUE TITLE
Installing PyQt5 seems to have busted Spyder. Spyder will not start.

### ISSUE THREAD

**Issue by canoetraveler** [spyder-ide/spyder#17611]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Installing PyQt5 seems to have busted Spyder. Spyder will not start.

I installed PyQt5 by executing 
- pip install pyqt5
- pip install pyqt5-tools

The pyqt5 lib installed correctly and I was able to execute a simple "hello world" python QT gui program from Spyder. 
However, I got an error attempting to install QTDesigner with the pyqt5-tools library. I tried making some changes
to the Windows environemtal path so that QTDesigner.exe could find the needed DLLs, but without success. 
Now, after closing Spyder, it will not start.
To attempt to fix Spyder I issued the following from the Anaconda prompt:
- conda update anaconda
- conda update spyder
- conda install spyder
...several windows reboots ...
Spyder still will not start.

### What steps reproduce the problem?
1.  I have also tryed to start Spyder from the anaconda prompt as suggested in the Spyder troublshooting webpages. 
2. 
3. 

### What is the expected output? What do you see instead?
Spyder simply does not start. No error messages; no nothing.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.something
* Python version:  3.7
* Qt version:         5.something
* PyQt version:      5.something
* Operating System name/version:  Windows 10

# packages in environment at C:\Users\canoe\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2021.11                  py37_0  
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  

For complete conda listing see attached file pylist.txt 
[pylist.txt](https://github.com/spyder-ide/spyder/files/8411865/pylist.txt)

### Dependencies

```
PASTE DEPENDENCIES HERE  --- I wish I could ---
```

**Comment by ccordoba12** [comment]
Hey @canoetraveler, thanks for reporting. It is not possible to run `pip install pyqt5` when using Anaconda to get a more recent version of PyQt5. That's because the package installed by pip and the one provided by Anaconda are binary incompatible.

Since it seems you didn't use an environment before doing that, I'm afraid you'll have to remove and install Anaconda again. Please follow the instructions in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that the right way. The second part of that video also explains how to install packages with pip in a different environment and how to connect it to Spyder.

However, if you don't need the latest features that come with PyQt5, you don't need to do that because Anaconda comes already with that package. That's because it's one of the main Spyder dependencies.

**Comment by canoetraveler** [comment]
Carlos,
Once again, you are a savior. Thank you. I uninstalled both Anaconda and Spyder, then reinstalled Anaconda and appear to be in a good place. 
 
The reason I was trying to install pyqt5 directly is that I had some old routines that use QT4, and the libraries don't load in the latest version of Spyder. Then, when I checked, I saw that the world has moved on to QT5...

Apparently, like most people, I have to learn my lessons that hard way. I will set up environments going forward. Thank you very much for the pointer to the video.

**Comment by ccordoba12** [comment]
No problem. I hope you can migrate your Qt4 code without much effort to Qt5.

If you need help with that, we also develop a compatibility layer called [qtpy](https://github.com/spyder-ide/qtpy). Versions older than 2.0 work for both PyQt4 and 5.
