### ISSUE TITLE
why a usable linux version is not released

### ISSUE THREAD

**Issue by 00burak00** [spyder-ide/spyder#17613]
### What steps reproduce the problem?

1. why a usable linux version is not released

**Comment by ccordoba12** [comment]
Hey @00burak00, thanks for reporting. Unfortunately we don't have the resources to do that at the moment. However, we'll try to do it next year.

**Comment by Lenticular** [comment]
Just to check, does this imply that Spyder 5.3.0 is no longer supported on a Linux-based OS? I'm running Ubuntu 20.04 LTS and installed Spyder with conda from conda-forge today; version 5.3.0 was installed. However, several things seem not to work, so I'd just like to check whether I need to revert to a earlier version?

**Comment by ccordoba12** [comment]
No, it means that we don't have time to create a simple and easy to use installer for Linux.

**Comment by Lenticular** [comment]
Ah, thanks, sorry for the silly question!

**Comment by ccordoba12** [comment]
No worries, I know it was not clear enough from the content.
