### ISSUE TITLE
Spyder how to Schedule python scripts to run in sequence within spyder

### ISSUE THREAD

**Issue by msacs09** [spyder-ide/spyder#17620]
I have multiple python scripts that need to run in sequence. Please advice how I achieve this scheduling within spyder

`I have script1 to run followed by script2 and they need to start everyday 8:00am EST and end/stop at 4:25pm EST only during business days/hours.` I wanted my python scripts to be launched using Spyder based on the schedule.

Thank you for your guidance

**Comment by ccordoba12** [comment]
Hey @msacs09, thanks for reporting. This functionality is not available in Spyder, sorry.

**Comment by ccordoba12** [comment]
Cron? I don't know, it depends on your operating system.
