### ISSUE TITLE
IPython Console Error While Starting the Kernel

### ISSUE THREAD

**Issue by fdarby** [spyder-ide/spyder#17625]
### What steps will reproduce the problem?

2018 HP Envy Ubuntu 20.04
IPython console use spyder5

I installed spyder5 via:
apt-get install spyder
python3 -m pip install --upgrade spyder

I tried using spyder as I do on my Windows desktop and IPython failed to start the kernel (long error message appended).

It may have been because I was missing packages, so I installed all of them with Anaconda with their download file:
bash Anaconda3-2021.11-Linux-x86_64.sh

Unfortunately I still have the same error after adding the packages:

An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 42, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/__main__.py", line 24, in 
start.main()
File "/usr/local/lib/python3.8/dist‑packages/spyder_kernels/console/start.py", line 295, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.8/dist‑packages/ipykernel/kernelapp.py", line 42, in 
from traitlets.utils import filefind
ImportError: cannot import name 'filefind' from 'traitlets.utils' (/usr/lib/python3/dist‑packages/traitlets/utils/__init__.py)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/onlinehelp/widgets.py", line 269, in _continue_initialization
    self.go_home()
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/onlinehelp/widgets.py", line 453, in go_home
    self.set_url(self.home_url)
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/onlinehelp/widgets.py", line 434, in set_url
    self.go_to(url)
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/onlinehelp/widgets.py", line 445, in go_to
    self.webview.load(url)
  File "/usr/local/lib/python3.8/dist-packages/spyder/widgets/browser.py", line 388, in load
    self.focusProxy().installEventFilter(self)
AttributeError: 'NoneType' object has no attribute 'installEventFilter'
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.10
* Qt version: 5.12.8
* PyQt5 version: 5.14.1
* Operating System: Linux 5.13.0-39-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  1.3.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  18.0.1 (OK)
nbconvert >=4.0               :  5.6.1 (OK)
numpydoc >=0.6.0              :  0.7.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.6.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.5.1 (OK)
pygments >=2.0                :  2.3.1 (OK)
pylint >=2.5.0                :  2.13.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.0.0 (OK)
sphinx >=0.6.6                :  1.8.5 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.7 (OK)
xdg >=0.26                    :  0.26 (OK)
zmq >=17                      :  18.1.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by fdarby** [comment]
After reinstalling spider through the conda terminal:

conda update conda
conda install -c anaconda spyder

My package dependencies were fixed and this issue was resolved.

**Comment by dalthviz** [comment]
Thank you for letting us know @fdarby ! Closing as completed

**Comment by fdarby** [comment]
Thanks for closing Daniel! I meant to close when I left the comment.
