### ISSUE TITLE
Black doesn't autoformat code on save

### ISSUE THREAD

**Issue by gsamaras** [spyder-ide/spyder#17636]
## Problem Description

I updated Spyder to the latest version. Now I get a popup "completion and linting in the editor spyder error", like this:

![PXJpR](https://user-images.githubusercontent.com/12050610/162160132-f95f3994-250f-4019-92ce-e993513d1b9d.png)

which I guess prevents Black from operating.

In the preferences I have the box ticked to autoformat code on save via Black, but nothing happens on save. Selecting some code lines and right clicking on the editor has the option for Black disabled (you cannot click on it) - same with the shortcut.

According to this [SO post](https://stackoverflow.com/questions/67609259/completion-and-linting-in-the-editor-for-python-files-will-not-work-during-curre), this might be a firewall problem, but that doesn't apply to me because the firewall options are managed by my organization, and nothing has changed in my Windows 10 desktop.

This broke when I updated Spyder. Can you please help?

## Versions

* Spyder version: 5.3.0
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt version: 5.15.6
* OS version: Windows 10   

### Dependencies

<details><summary>Dependencies</summary>

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
paramiko >=2.4.0                     :  2.10.3 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  61.2.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

</details>

**Comment by ccordoba12** [comment]
Hey @gsamaras, thanks for reporting. How did you update Spyder?

**Comment by gsamaras** [comment]
Hi @ccordoba12. A pop-up appeared when I opened Spyder, I click on it, it downloaded a file, then I run it and it asked me to uninstall Spyder. Then it installed the new version.

That seemed quite odd to me for an update phase, but I clicked on the installation guidelines in the pop-up and it was agreeing to this procedure.

**Comment by ccordoba12** [comment]
Ok, I see, so you used our Windows installer. Do you have other Python installations in your system?

**Comment by gsamaras** [comment]
Hmm I am not sure I understand the question @ccordoba12, but I don't think so. I mean I am not doing anything else rather than the usual stuff (chrome, Microsoft outlook, cmd and git bash).

**Comment by dalthviz** [comment]
@gsamaras from what version of Spyder did you update? Could you reset your preferences and check again? For that you can go to `Tools > Reset Spyder to factory defaults`. Let us know if that helps.

**Comment by gsamaras** [comment]
I don't remember, but definitely I hadn't relaunch Spyder from December 2021.
I didn't change anything, but maybe it remembers some preferences I had used, like which interpreter to use.
That might lead to losing the ability to run stuff, so do you have any other suggestions? Because I'll be able to do that on Thursday, the earliest.

**Comment by dalthviz** [comment]
Maybe you could try running using the `safe-mode` flag to disscard something is happening with your preferences. For that,  if you used the default path for installation, you will need to run from cmd something like this: `C:\Users\<your user dir>\AppData\Local\Programs\Spyder\Python\python.exe "C:\Users\<your user dir>\AppData\Local\Programs\Spyder\Spyder.launch.pyw" --safe-mode` where `<your user dir>` is your home directory/your user directory

**Comment by gsamaras** [comment]
OK, so I tried resetting to factory results, same behavior. I got some warnings, same as when I launched in safe mode (see below).

Then I tried launching in safe mode from cmd, and got:
```
C:\Users\gsamaras>C:\Users\gsamaras\AppData\Local\Programs\Spyder\Python\python.exe "C:\Users\gsamaras\AppData\Local\Programs\Spyder\Spyder.launch.pyw" --safe-mode
fromIccProfile: failed minimal tag size sanity
C:\Users\gsamaras\AppData\Local\Programs\Spyder\pkgs\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\gsamaras\AppData\Local\Programs\Spyder\pkgs\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\gsamaras\AppData\Local\Programs\Spyder\pkgs\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
```
Then Spyder launched, same behavior.

Does that tell you something please @dalthviz?

**Comment by dalthviz** [comment]
Well the `UserWarning` means that somehow there are more files in the installation than expected. Could you manually uninstall Spyder and reinstall it please? Not totally sure how but seems like your previous installation left some files and then reusing the installation directory caused some files appear as duplicated.

Checking on my local installation with the installer I have only `libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll`

Maybe after unistalling you could check if `C:\Users\gsamaras\AppData\Local\Programs\Spyder` is actually empty or doesn't exist and if that is not the case remove it manually.

Let us know if something of the above helps!

**Comment by gsamaras** [comment]
So I deleted everything and started fresh, now all it's good, thanks for your help!
