### ISSUE TITLE
spyder-kernels=2.3

### ISSUE THREAD

**Issue by ricbenmar** [spyder-ide/spyder#17632]
### What steps will reproduce the problem?

Cannot restart a kernel not started by Spyder

I installed Miniconda 

## Versions

* Spyder version: 5.3.0 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
paramiko >=2.4.0                     :  2.10.3 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  61.2.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ricbenmar** [comment]
Trying to read Excel files with Pandas was not possible

**Comment by ricbenmar** [comment]
Trying to read Excel files with Pandas was not possible

**Comment by ccordoba12** [comment]
If you're following this entry in our documentation:

https://docs.spyder-ide.org/5/faq.html#using-packages-installer

please start from the beginning again and change all commands to use this

    conda install -c conda-forge ...

the `-c conda-forge` is the crucial part because it'll use more up to date packages than the ones found by default in Anaconda.

Please do that and let us know if it works for you.

**Comment by ricbenmar** [comment]
I am not sure about what and how to do, I am upset  Enviado desde Correo para Windows De: Carlos CordobaEnviado: miércoles, 6 de abril de 2022 19:04Para: spyder-ide/spyderCC: Ricardo Benito; State changeAsunto: Re: [spyder-ide/spyder] spyder-kernels=2.3 (Issue #17632) If you're following this entry in our documentation:https://docs.spyder-ide.org/5/faq.html#using-packages-installerplease start from the beginning again and change all commands to use thisconda install -c conda-forge ...the -c conda-forge is the crucial part because it'll use more up to date packages than the ones found by default in Anaconda.Please do that and let us know if it works for you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by ccordoba12** [comment]
Sorry, I understand this is frustrating but for now that's the only way to use functionality that doesn't come with our installers.

If you don't understand what to do, I'm afraid you'll have to dedicate more time to learn how Conda and Conda-forge work. Since we don't have documentation for that, I'm afraid you'll have to learn about it by googling it.

**Comment by ricbenmar** [comment]
The current user does not have write permissions to the target environmentThis message I get with spyder intructions to this issue.What can I do?regardsEnviado desde Correo para Windows De: Carlos CordobaEnviado: martes, 12 de abril de 2022 17:40Para: spyder-ide/spyderCC: Ricardo Benito; State changeAsunto: Re: [spyder-ide/spyder] spyder-kernels=2.3 (Issue #17632) if so what do you think is better to download spyder from anaconda or as I have done beforeThe problem is Spyder in Anaconda is quite outdated, so it won't work very well.directly from window inatallerThat one doesn't have the packages you need to read Excel files.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
