### ISSUE TITLE
ipdb prompt doesn't show in the spyder console

### ISSUE THREAD

**Issue by Baoooooooda** [spyder-ide/spyder#17643]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'd like to try the debug tool on the code below:

def func1():
    for i in range(10):
        print(i)

func1()

However, I was not able to see any ipdb prompt "ipdb >" shown on the console to allow me to pursue any further operation.

### What steps reproduce the problem?

1. Select the code and click debug file on the menu bar from spyder
<img width="642" alt="Screen Shot 2022-04-07 at 9 56 28 PM" src="https://user-images.githubusercontent.com/96200884/162355186-4d25ce75-84cd-4ada-a50a-623509e93b44.png">

2. 
3. 

### What is the expected output? What do you see instead?

I expected to see an ipdb promt, but i see nothing. I have to restart the kernel to use spyder.
<img width="642" alt="Screen Shot 2022-04-07 at 9 56 28 PM" src="https://user-images.githubusercontent.com/96200884/162354532-d929dcdc-3685-4485-9335-5fefb14662e5.png">

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
      1 #!/usr/bin/env python3
      2 # -*- coding: utf-8 -*-
----> 3 """
      4 Created on Thu Apr  7 18:47:48 2022
      5 
```

## Versions

* Spyder version: 5.1.5
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: macOS Monterey/12.2.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Baoooooooda, thanks for reporting. This problem is already fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
