### ISSUE TITLE
Entering ?? after list in editor gives error

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1765]
_From [thomson....@gmail.com](https://code.google.com/u/110689693938517381157/) on 2014-03-23T10:22:52Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.4, PySide 1.2.1 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

1. enter some list (e.g., b=range(3))
2. then, in editor enter 'b??', highlight and hit F9 What is the expected output? What do you see instead? Information about b, the same as when you enter 'b??' in the ipython console (note 'b?' works fine in editor with f9). 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1765_

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-23T10:37:52Z_

That's weird, it works for me. Same Spyder version (I'm using 2.3.0dev but I reinstalled 2.2.5 to check), same Python version...

See:

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.4, PySide 1.2.1 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK)

**Comment by spyder-issues-migrator** [comment]
_From [thomson....@gmail.com](https://code.google.com/u/110689693938517381157/) on 2014-03-23T11:43:33Z_

I am in Windows 7...Maybe a platform-specific issue?

**Comment by spyder-issues-migrator** [comment]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-03-23T17:40:00Z_

...Windows 7 here too!

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-03-24T08:53:51Z_

What do you see instead of the information ? An error ? Nothing ?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-03-24T09:02:31Z_

Btw, you can stop reporting many times the same error... There is a problem in the invocation of ipython from the editor, but don't list each function that doesn't work !
Thanks for reporting, though, and for the interest you have in improving spyder.

**Comment by spyder-issues-migrator** [comment]
_From [thomson....@gmail.com](https://code.google.com/u/110689693938517381157/) on 2014-03-25T17:30:31Z_

contrebasse:
\>>>
  File "<ipython-input-10-29bd6582a396>", line 2
    b??
     ^
SyntaxError: invalid syntax

Strangely it works sometimes, doesn't work other times. In some of my files it works, in some it does not! Very odd.

In terms of reporting every error I find being redundant, this is not at all clear to me! Not every failure of execution from the editor is the same (right?). Different functions could have different error etiology, no?

**Comment by goanpeca** [comment]
What is the use case for this?

**Comment by ccordoba12** [comment]
The `x??` syntax is not supported in our Python consoles. It only works on IPython ones. That's probably the problem here.

In any case, we don't plan to support this syntax enhancement in our Python consoles.
