### ISSUE TITLE
IPython console does not work with Micromamba environments

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17665]
### What steps will reproduce the problem?

Using a `micromamba` environment is currently not permitted.

```python
/Users/rclary/Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder/plugins/ipythonconsole/scripts/conda‑activate.sh: line 11: /Users/rclary/opt/micromamba/bin/activate: No such file or directory
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.9.5
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7            :  0.2.1 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  60.10.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
I think this problem happens because micromamba has the code to activate environments in itself. Could you check that?

**Comment by mrclary** [comment]
> I think this problem happens because micromamba has the code to activate environments in itself. Could you check that?

I don't know what you mean by "activate environments in itself".
The essential problem is that Spyder thinks a micromamba environment is a conda environment because it has a conda-meta directory, and therefore uses the conda-activate.sh script. Spyder also assumes that a conda environment will have an activation script `<conda-root>/bin/activate` which I believe is true for conda, miniconda, and mamba, but not true for micromamba.

micromamba environments should still be activated and can be done so using the executable
```
eval "$($MAMBA_EXE shell activate <env path>)"
```

An easy fix in `conda-activate.sh` is:
```
if [[ -e "$CONDA_ACTIVATE_SCRIPT" ]]; then
    # conda, miniconda, mamba
    source $CONDA_ACTIVATE_SCRIPT $CONDA_ENV_PATH
elif [[ -n "$MAMBA_EXE" ]]; then
    # micromamba
    eval "$($MAMBA_EXE shell activate $CONDA_ENV_PATH)"
fi
```

**Comment by ccordoba12** [comment]
> micromamba environments should still be activated and can be done so using the executable

That's what I meant, i.e. that you don't need to invoke an external script to activate envs with micromaba because it can do that by itself.

> An easy fix in conda-activate.sh is

I think that's fine, but I have one suggestion: changing `MAMBA_EXE` for `MICROMAMBA_EXE` because I think both binaries have different names, right?

**Comment by mrclary** [comment]
> I think that's fine, but I have one suggestion: changing `MAMBA_EXE` for `MICROMAMBA_EXE` because I think both binaries have different names, right?

On my installation, micromamba sets `MAMBA_EXE`; there is no `MICROMAMBA_EXE`. I don not have mamba installed, however; will this be different if mamba is installed? I assume not, since micromamba is the same as mamba, just packaged into a single executable...

**Comment by ccordoba12** [comment]
Ok, I see. Then forgot what I said.

But that about Windows?

**Comment by mrclary** [comment]
I'll have to verify on Linux and Windows.

**Comment by mrclary** [comment]
It appears to use the same environment variable on Windows, both `MAMBA_EXE` and `MAMBA_ROOT_PREFIX`.

**Comment by ccordoba12** [comment]
Ok, great! Then I think you're ready to open a PR for this.

**Comment by mrclary** [comment]
While not relevant to this PR, I discovered something nice about micromamba that will be useful in the future implementation of the environment/package manager. Executables in _any_ conda environment (conda, miniconda, mamba, micromamba) can be run directly from micromamba with their environments activated in a single command!
```
micromamba run --prefix=<path to env> <executable> <exec opts> <exec args>
```
This will simplify launching IPython Consoles and obviate the need for `conda-activate.sh`.
