### ISSUE TITLE
saves the result of last execution

### ISSUE THREAD

**Issue by michal-99** [spyder-ide/spyder#17679]
### Spyder remembers the changes from the previous executions

I imported a list, then removed an item and printed.
the first execution worked as it should.
when i executed the code again i got an error: list.remove(x): x not in list. to check i deleted the line to remove the item and to just import and print the list. the list it printed was without the item that was removed in the first execution.

**Comment by ccordoba12** [comment]
Hey @michal-99, thanks for reporting. This doesn't an internal Spyder problem, which this place is meant to be, i.e. to report those kind of problems.

Instead, it seems a general Python programming issue. For that, we recommend you to ask your question in StackOverflow:

https://stackoverflow.com/
