### ISSUE TITLE
Application launch error

### ISSUE THREAD

**Issue by claudioszw** [spyder-ide/spyder#17680]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder doesn't run, not from Anaconda neither by itself. There's a message "application launch error." 

### What steps reproduce the problem?

1. Uninstalled
2. Reinstalled
3. Updated

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
File "C:\Users\claudioszw\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\claudioszw\Anaconda3\lib\site-packages\spyder\app\start.py", line 113, in main
from spyder.config.manager import CONF
File "C:\Users\claudioszw\Anaconda3\lib\site-packages\spyder\config\manager.py", line 636, in 
CONF = ConfigurationManager()
File "C:\Users\claudioszw\Anaconda3\lib\site-packages\spyder\config\manager.py", line 71, in __init__
self._user_config = MultiUserConfig(
File "C:\Users\claudioszw\Anaconda3\lib\site-packages\spyder\config\user.py", line 786, in __init__
self._configs_map[name] = config_class(**new_kwargs)
File "C:\Users\claudioszw\Anaconda3\lib\site-packages\spyder\config\user.py", line 212, in __init__
self._load_from_ini(previous_fpath)
File "C:\Users\claudioszw\Anaconda3\lib\site-packages\spyder\config\user.py", line 333, in _load_from_ini
self.read(fpath, encoding='utf-8')
File "C:\Users\claudioszw\Anaconda3\lib\configparser.py", line 697, in read
self._read(fp, filename)
File "C:\Users\claudioszw\Anaconda3\lib\configparser.py", line 1070, in _read
raise DuplicateSectionError(sectname, fpname,
configparser.DuplicateSectionError: While reading from 'C:\\Users\\claudioszw\\.spyder-py3\\config\\transient.ini' [line 112]: section 'explorer' already exists
```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.1.5            build py39haa95532_1
* Python version:  3.9.7           build     h6244533_1
* Qt version:  5.9.7          build  vc14h73c81de_0
* PyQt version:  5.9.2         build   py39hd77b12b_6
* Operating System name/version: Version Windows	10.0.19044 Build 19044

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @claudioszw, thanks for reporting. It seems your Spyder configuration got corrupted somehow.

To fix this problem, please open the Anaconda Prompt and run there

    spyder --reset

That should fix your problem, but let us know if it does.

**Comment by claudioszw** [comment]
Hi Carlos,
Thank you very much, it worked.
All the best
Claudio

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
