### ISSUE TITLE
TimeStamp index rolling problems

### ISSUE THREAD

**Issue by mIgLLL** [spyder-ide/spyder#17697]
## Problem Description

There is a problem that the rolling function requires the index to be monotonic in the newest version of pandas (1.4.1). It start to require a globally monotonic index for rolling function, which is quite unreasonable for timestamp index. Panel data are used quite commonly! The global monotonic requirement should instead be taken of by " within group monotonic". 

   In the previous version (such as 1.3.5), the code below can work prefectly. But when I update to newest pandas (1.4.1), it doesn't work any more.

sample code:

import pandas as pd

data = pd.date_range(start='1/1/2018', periods=8).to_frame(name='date')
data['symbol'] = 1

data = data.append(data)
data.iloc[8:,1] = 2

data['value'] = 1

## total 16 days ( ValueError: index must be monotonic )
roll_mean = data.groupby('symbol')['value'].rolling('2d').mean()

## only second 8 days ( Only globally monotonic index worked)
roll_mean = data.iloc[8:,:].groupby('symbol')['value'].rolling('2d').mean()

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.5
* Python version: 3.9.12
* Qt version: 5.9.2
* PyQt version: 
* Operating System name/version:  Windows 10 19042.1466
* Pandas version: 1.4.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @mIgLLL, thanks for reporting. This doesn't seem to be a problem with Spyder but with a functionality that changed in Pandas.

So please report your problem here:

https://github.com/pandas-dev/pandas
