### ISSUE TITLE
What are the install arguments for the Windows installer?

### ISSUE THREAD

**Issue by tbates98** [spyder-ide/spyder#17725]
Hello, 

Apologies for not using the template but this isn't an issue with the program itself but rather the installer for Windows.

I work for an organisation that is attempting to package Spyder with Chocolatey for use on Windows 10 Pooled Desktops.
I cannot seem to find a proper list of the silent install arguments for the installer and I am trying to get it to install for all users (Program Files) silently. 

Please could you provide me with the switches for the program or tell me how I could go about doing this? 
So far, the only switch that I can find is "/S" but this installs the program in the user profile which we do not want.

I would greatly appreciate if you could point me in the right direction! 

Kind Regards,

Tom

**Comment by dalthviz** [comment]
Hi @tbates98 that sound quite interesting! About your question, the Windows installer is an NSIS installer so you can use flags suchs as the ones described here: https://nsis.sourceforge.io/Docs/Chapter3.html#installerusage.

I think we discussed something like this at https://github.com/spyder-ide/spyder/issues/17154 and the flag you can try is `/ALLUSERS=1` as described at https://github.com/spyder-ide/spyder/issues/17154#issuecomment-1010189934

Let us know if that helps!

**Comment by ccordoba12** [comment]
@dalthviz, perhaps we should add this info to the installer's Readme file?

https://github.com/spyder-ide/spyder/blob/master/installers/Windows/README.md

**Comment by tbates98** [comment]
Thank you both, that worked a treat! Much appreciated! :)

**Comment by ccordoba12** [comment]
Reopening because we're going to fix this issue by adding the info mentioned above to the installer's Readme.
