### ISSUE TITLE
Spyder fails to restart after selecting Restart from the macOS standalone application menu bar

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17731]
Spyder fails to restart after selecting File->Restart or File->Restart in debug mode from the macOS standalone application menu bar. This does not manifest when launched from conda, pip, or bootstrap. It appears to be an issue with the standalone application only. I'm not sure yet what the underlying issue is.

**Comment by mrclary** [comment]
#17729 may be related.

The OP in that and this issue do not manifest in 5.2.2. Two updates to `py2app` have occurred: #16651 between 5.2.2 and 5.3.0; and #17612 after 5.3.0. Both issues manifest in 5.3.0 and recent local builds, so it is likely that they are both related to the update to `py2app` in #16651.

**Comment by mrclary** [comment]
#17524 manifests both issues. This PR is immediately prior to #16651, so it seems these issues are not related to any updates to `py2app`. Investigation continues...

**Comment by mrclary** [comment]
I've narrowed it down to #16409; it looks like updating `pyqt` is the culprit. I'll check if changing versions will change anything.

**Comment by ccordoba12** [comment]
I think this is the culprit (which was added in that PR):

https://github.com/spyder-ide/spyder/blob/dfb3a5f40405d5e72acaeacd73e20aef12dfeddd/spyder/app/mainwindow.py#L1504-L1532

So, we need to force quit the Mac app because if not it closes with a segfault when using PyQt 5.15

**Comment by mrclary** [comment]
#17732 is a necessary but insufficient fix for this issue.
The core problem seems to be related to the way `pkg_resources` obtains entry points after updating to `py2app=0.28`.
Essentially, Spyder seems to startup just fine, but restarting Spyder from the menubar (launching from a subprocess via `start.py`), `pkg_resources` does not obtain entry points. The traceback can be replicated from the command line. See https://github.com/spyder-ide/spyder/pull/17732#issuecomment-1106717746 and https://github.com/spyder-ide/spyder/pull/17732#issuecomment-1106911615.

**Comment by mrclary** [comment]
Pending feedback from @ronaldoussoren, I think we have two options:
- Migrate to `importlib`. I don't even know if this would fix the problem and it would be a _major_ undertaking. I don't know such plans are being considered down the road, but this seems to be a non-starter for this issue.
- Restart the macOS app using `Spyder.app/Contents/MacOS/Spyder [options]` instead of `Spyder.app/Contents/MacOS/python ...start.py [options]`. This seems the most feasible for this issue.

**Comment by ronaldoussoren** [comment]
I'd always restart using .../MacOS/Spyder. The launcher binary does some extra work to set up the environment correctly and I'm not 100% sure if the .../MacOS/python command gets this right at the moment.

That said, I don't really know that Spyder's Restart menu actually does and have never looked into the state of the art w.r.t restarting a macOS app.

**Comment by mrclary** [comment]
> I'd always restart using .../MacOS/Spyder. The launcher binary does some extra work to set up the environment correctly and I'm not 100% sure if the .../MacOS/python command gets this right at the moment.
> 
> That said, I don't really know that Spyder's Restart menu actually does and have never looked into the state of the art w.r.t restarting a macOS app.

@ronaldoussoren, Thank you for your input! Just for my own information, where is the launcher binary created in the `py2app` source code?
