### ISSUE TITLE
OpenCV: not authorized to capture video (status 0), requesting...

### ISSUE THREAD

**Issue by iMuhammadwaseem** [spyder-ide/spyder#17742]
### What steps reproduce the problem?

1. Installing miniforge's conda version in M1 Macs 
2. Installing spyder via brew
3. Creating a new conda environment with python=3.8
4. Using ```pip install opencv-contrib-python``` to install opencv
5. Change default interpreter environment in spyder to the above conda's environment.
6. importing cv2 and trying to use cv2.VideoCapture(0).

**One more Catch is that, the program was initially running without any issue, I am not sure, but I guess after updating conda it is showing such error**

### Paste Traceback/Error Below (if applicable)

<img width="713" alt="Screenshot 2022-04-24 at 9 42 40 AM" src="https://user-images.githubusercontent.com/85298297/164956286-729a52a8-910a-4497-89df-92ce4ddbcc7b.png">

## Versions

* Spyder version: 5.3.0
* Python version: 3.9.5 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.6
* Operating System name/version: MacOS Monterey (M1 PRO Chip)

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7            :  0.2.1 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  60.10.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @iMuhammadwaseem, thanks for reporting. You can't mix pip and conda/conda-forge packages as you're trying to do in your environment because they are binary incompatible.

Instead, you need to run

    conda install -c conda-forge py-opencv

But before doing that you need to reinstall Miniforge or uninstall all packages that got installed when you ran `pip install opencv-contrib-python`.

**Comment by iMuhammadwaseem** [comment]
Hi,

Thanks for your response.
But I still get the same issue with OpenCV.
It was initially working but all of the sudden just few days back it
stopped working.
Kindly help me.

**Comment by ccordoba12** [comment]
I don't know what can be happening then, sorry.
