### ISSUE TITLE
Help Pane unable to render rich text on Arch Linux

### ISSUE THREAD

**Issue by AchmadFathoni** [spyder-ide/spyder#17751]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Help pane is always empty if Rich Text option is active. This is my first time installing spyder. The Plain Text is working fine. Similar to #8806

### What steps reproduce the problem?

1. Install spyder with `conda create -n spyder-env spyder=5 numpy scipy pandas matplotlib sympy cython -c conda-forge`
2. Activate conda environment and run spyder
3. Choose Rich Text option in hamburger menu at Help pane
4. Input `numpy.array` in object field
5. Hit enter

### What is the expected output? What do you see instead?
Help pane just blink twice with white color(I use dark theme) and then nothing. Also when I open spyder, the helper pane is already empty. I saw the youtube tutorial and there is supposed to be some box titled Usage or something.

## Versions

* Spyder version: 5.3.0
* Python version: 3.10.4
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version:  Linux 5.17.4-arch1-1 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.13.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.0.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.1.0 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.7 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by AchmadFathoni** [comment]
https://user-images.githubusercontent.com/26775746/165132629-28d9a23c-7df7-4997-be95-69de54b23fe0.mp4

**Comment by ccordoba12** [comment]
Thanks for the video @AchmadFathoni! Unfortunately, I can't reproduce your problem (I'm also using Linux and conda-forge).

Could you go to `View > Panes > Online Help` and upload a screenshot of how that pane looks like? Since that pane also uses a web widget to display its content, it'll give a hint of what can be happening in your case.

**Comment by AchmadFathoni** [comment]
@ccordoba12 I use Archlinux, what distro do you use?

**Comment by ccordoba12** [comment]
Thanks for the new video. As I Imagined, this is an issue with Qt's web widgets and not with the Help pane (Qt is the graphical toolkit used by Spyder).

> I use Archlinux, what distro do you use?

I use Kubuntu 20.04. And I think the problem is related to that because probably Arch has newest libraries that are incompatible with those widgets.

For now I think there's nothing to do about it, but this could be fixed once a new version of Qt is released in conda-forge in a couple of weeks.

**Comment by rear1019** [comment]
I am not able to reproduce the error on Arch Linux with updated packages as of today and Spyder from current `5.x` branch. You could try changing the preference `Application => Advanced settings => Rendering engine`.

> * Qt version: 5.12.9
> * PyQt version: 5.12.3

Most recent package versions as of today are 5.15.x on Arch Linux.

**Comment by AchmadFathoni** [comment]
> I am not able to reproduce the error on Arch Linux with updated packages as of today and Spyder from current `5.x` branch. You could try changing the preference `Application => Advanced settings => Rendering engine`.
> 
> > * Qt version: 5.12.9
> > * PyQt version: 5.12.3
> 
> Most recent package versions as of today are 5.15.x on Arch Linux.

That is the Qt version from Spyder help windows which is different from Qt that installed on system-wide. I use conda virtual environment to install Spyder.

**Comment by AchmadFathoni** [comment]
Fixed in last dependency update
```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.5.1 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.2.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.13.9 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.0.1                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.1 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.22.3 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.8.0 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```
