### ISSUE TITLE
Spyder-Notebook + YT: Plot shows on the notebook but not inline

### ISSUE THREAD

**Issue by DQuanR2** [spyder-ide/spyder#17758]
## Problem Description
I am trying to make plots using the [YT-project package](https://yt-project.org/) and Spyder-Notebook. The YT package supports JupyterLab notebooks, and allows to do "inline" plotting. However, when I try to use the nice feature of inline in Spyder, they wont show. 

Some details: The yt-package does not use the matplotlib backend, but `_repr_html_` instead. (I already contacted them). Also, there is a compatibility issue between Spyder+matplotlib and yt, this is solved by downgrading matplotlib to v3.3.3

### What steps reproduce the problem?

1. Install the yt package in the same env as spyder i.g., ```conda install -c conda-forge yt==4.0.2```
2. Make a plot and show it using the yt tools.

### What is the expected output? What do you see instead?
I expect to see the plot inline. Instead I see it in the notebook. 
If I try running the code directly in a spyder console, I see this and output from yt, but no plot  ```<yt.visualization.plot_window.AxisAlignedSlicePlot at 0x7f37186fffa0>```

## Versions

* Spyder version: 4.2.5
* Python version: 3.8.12
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 20.04

**Comment by ccordoba12** [comment]
Hey @DQuanR2, thanks for reporting. I don't understand what you mean by this

> I expect to see the plot inline. Instead I see it in the notebook.

So, you'd like to see the plot in Spyder's Plot pane instead of in the notebook?

**Comment by DQuanR2** [comment]
Yes, sorry I wasn't clear. I would like to see the plots in Spyder Plot pane.

**Comment by ccordoba12** [comment]
Ok, then this is not possible at the moment. According to what you said above:

> If I try running the code directly in a spyder console, I see this and output from yt, but no plot <yt.visualization.plot_window.AxisAlignedSlicePlot at 0x7f37186fffa0>

the Yt plots are not static images, which are the only kind of figures that can be viewed in the Plots pane. Instead, they seem to interactive visualizations that can only be rendered in the notebook.

We're aware of this limitation and we'll try to fix in the next couple of years. But for now there's nothing we can do about it, sorry.

**Comment by DQuanR2** [comment]
I understand. At least now I know what’s possible and what’s not so I can work with that.
Thank you 

D
