### ISSUE TITLE
Not connecting to Kernel due to old Spyder version

### ISSUE THREAD

**Issue by foroogh67** [spyder-ide/spyder#17766]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
#once I open spider it will continue alarming connecting to Kernel!

**Comment by foroogh67** [comment]
thanks,

I use spyder within my anaconda, and I update anaconda using conda update
--all, but still get following error.
[image: image.png]

**Comment by dalthviz** [comment]
Attachments are not uploaded to the GitHub issue tracker when answering with an email @foroogh67 so you will need to upload them from the GitHub interface at https://github.com/spyder-ide/spyder/issues/17766

Usually running `conda update --all` has a high chance of breaking things so I would suggest for you to create a new env from an Anaconda prompt using the conda-forge channel to get the latest Spyder available. For that you can run from an Anaconda prompt something like the following:

    conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.0

Then you should be able to find a shortcut named `Spyder (spyder-env)` which will launch the new Spyder version installed run it from an Anaconda prompt activating the new env created with something like:

    conda activate spyder-env
    spyder

Let us know if the things above helps

**Comment by foroogh67** [comment]
Thank you very much. it works.
Regards,
Foroogh

**Comment by dalthviz** [comment]
Glad it worked for you @foroogh67 I'm closing this then and thank you for letting us know :+1:
