### ISSUE TITLE
Whenever running importing torch, issue reporter pops up.

### ISSUE THREAD

**Issue by khyejin1231** [spyder-ide/spyder#17765]
I am not entirely sure how you can reproduce the problem. All I am doing is 

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
import torch
import transformers as ppb
import warnings

df = pd.read_csv('selecteduser_BERT.csv')

model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

df = df[df['text'].notna()]

tokenized = df['text'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True)))

max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)

padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])

attention_mask = np.where(padded != 0, 1, 0)

import torch

**Comment by ccordoba12** [comment]
Hey @khyejin1231, thanks for reporting. I can't see any error here, so I'm going to close this.

Please open a new issue that includes the error and all the information required in our issue template.
