### ISSUE TITLE
When install numpy

### ISSUE THREAD

**Issue by John36er** [spyder-ide/spyder#17779]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I use Anaconda Prompt to install numpy,occurs error:EnvironmentNotWritableError: 
The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3
How to resolve this problem.Thank you.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.4
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @John36er, thanks for reporting. This error means that you can't install additional packages in Anaconda because you installed it in read-only directory.

There are two solution for it:

1. Start the Anaconda Prompt as Administrator and proceed to install packages on it.
2. Uninstall Anaconda and install it just for your user. That will place it in `C:\Users\<your user>\Anaconda`, that has the right permissions to install additional packages.

Let us know if that works for you.

**Comment by John36er** [comment]
Thank you for your solutions,I resolve my problem following the method one,and I had solved my problem.Thank you again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spyder-ide/spyder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [spyder-ide/spyder] When install numpy (Issue #17779)





 
Hey @John36er, thanks for reporting. This error means that you can't install additional packages in Anaconda because you installed it in read-only directory.
 
There are two solution for it:
  
Start the Anaconda Prompt as Administrator and proceed to install packages on it.
 
Uninstall Anaconda and install it just for your user. That will place it in C:\Users\<your user&gt;\Anaconda, that has the right permissions to install additional packages.
  
Let us know if that works for you.
