### ISSUE TITLE
Crash when trying to open remote kernel

### ISSUE THREAD

**Issue by NH89** [spyder-ide/spyder#17772]
### What steps will reproduce the problem?

Crash occurs when trying to connect to remote kernel
using Python 3.9.7 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Linux 5.10.0-1057-oem on the client, and 
spyder-5.3.0 | spyder-kernels-2.3.0 | python-3.9.12 | Linux ubuntugpugef 5.4.0-104-generic on the server.

Both machines use Conda. The remote kernel is in a user Conda environment, not the base Conda environment.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/hockingsn/miniconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1105, in create_client_for_kernel
    self._create_client_for_kernel(connection_file, hostname, sshkey,
  File "/home/hockingsn/miniconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1935, in _create_client_for_kernel
    shellwidget.check_spyder_kernel()
  File "/home/hockingsn/miniconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 266, in check_spyder_kernel
    self.silent_exec_method(code)
  File "/home/hockingsn/miniconda3/lib/python3.9/site-packages/spyder/plugins/ipythonconsole/widgets/shell.py", line 667, in silent_exec_method
    self._request_info['execute'][msg_id] = self._ExecutionRequest(msg_id,
TypeError: <lambda>() missing 1 required positional argument: 'hidden'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 5.10.0-1057-oem

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (OK)
matplotlib >=2.0.0            :  None (OK)
numpy >=1.7                   :  None (OK)
pandas >=1.1.1                :  None (OK)
scipy >=0.17.0                :  None (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by NH89** [comment]
Could this be related to the contents of the remote kernel's .json file ?
E.g. when launching the kernel on the remote host with the command
`python -m spyder_kernels.console --ip=<ip_addr_of_the_node>`
If the `--ip=<ip_addr_of_the_node>` is omitted, will the .json file lack information required by ssh ?

**Comment by dalthviz** [comment]
Hi @NH89 thank you for the feedback! Could you try to update Spyder on your client machine to use Spyder 5.3.0? For that you will need to use the conda-forge channel. So, to not affect your base env, you should create a new env using only conda-forge packages with something like this:

     conda create -n spyder-env -c conda-forge python=3.9.7 spyder=5.3.0

Let us know if that helps

**Comment by NH89** [comment]
Thank you, that worked.

1) Success when 
(i) both remote host and client have identical conda environments as you specified
(ii) placed the kernel file in:  `/home/<username>/.local/share/jupyter/runtime/`
(iii) kept the automatically generated filename:   `kernel-<processID>.json`
This got to a failed ssh login... so then 
(iv) closed the ssh connection that I had previously had open in the terminal
Then the Spyder connection remote kernel connection worked.

2) also success when 
(i) used the kernel file in a different directory
(ii) changed the filename to :  remote_machine_new.json

Next I will try loading the conda environments with the tools that I need to use. I would like to be able to use the notebook plugin  with a remote kernel, though I understand that plugin is currently unstable with Spyer-5.x . I also need to use PyTorch-Cuda with GPyTorch, Numba, iPyParrallel and mpi4py,  which may constrain the dependencies.

Thanks,
Nick

**Comment by dalthviz** [comment]
Glad is working for you now @NH89 I'm closing this as completed then However, if you have more questions or problems let us know :+1:

Also, just in case, we have some docs regarding the usage of external kernels (local or remote) here: https://docs.spyder-ide.org/current/panes/ipythonconsole.html#using-external-kernels
