### ISSUE TITLE
Add a 72-char vertical line for docstrings

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1778]
_From [robro...@gmail.com](https://code.google.com/u/114002459288016453009/) on 2014-04-03T09:56:39Z_

Just an idea - it would be awesome if Spyder had an additional 72-char vertical line, to mark the maximum number of chars allowed for docstrings.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1778_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-04-16T09:44:29Z_

But how to show it? Only for docstrings?

**Status:** HelpNeeded  
  **Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-04-17T07:49:58Z_

Some editors (like jEdit if I remember well) allow for multiple vertical lines. This would be the easy way but showing it only for docstrings would be neat !

**Comment by goanpeca** [comment]
Docstringa have a 72 char limit? Why?

**Comment by Nodd** [comment]
It's the pep8 recommendation, it is easier to read for big paragraphs. Personally I use 79 everywhere.

**Comment by goanpeca** [comment]
Yes me too.... I (79 for everything)

**Comment by goanpeca** [comment]
Indeed https://www.python.org/dev/peps/pep-0008/#maximum-line-length, I had missed that completely.
