### ISSUE TITLE
Cannot Run Script which has worked before

### ISSUE THREAD

**Issue by LnSHampton** [spyder-ide/spyder#17798]
Open Spyder from the Anaconda screen.
Open the script.
Click the Run button.

Here is the portion of the code that appears to be causing the error.

print('\nOracle Cloud to Access: {} ({})'.format(target_site, 
                                               server[8:server.index('.')]))
if input('Is this correct (Y/N)? ').upper() != 'Y':
    print('Exiting Script . . . ')
    sys.exit()

The 'print' works. It seems the script bombs on the 'if' statement.

Respectfully,
Leon

**Comment by LnSHampton** [comment]
Never mind. I found the solution you posted to my earlier issue. I am good. Thanks for responding so quickly the previous time. You may close this issue.

**Comment by dalthviz** [comment]
Hi @LnSHampton glad you find the solution already :+1: 

Since seems like you solve it, I will close this one but just in case, could you post here the link to the previous issue where you found the solution please @LnSHampton ? Thanks!
