### ISSUE TITLE
Check usage of `pytest-timeout` to prevent some tests from hanging the CI 

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#17815]
See https://pypi.org/project/pytest-timeout/

**Comment by ccordoba12** [comment]
I agree this is important to avoid the many hangs we're having in CIs lately.

**Comment by dalthviz** [comment]
Note: Maybe the script used for the debian package to retry the tests suit isf something fails could be useful too: https://salsa.debian.org/science-team/spyder/-/blob/master/debian/tests/run_pytest.py
