### ISSUE TITLE
Problems with Spyder on Mac with Conda-forge and `applaunchservices`

### ISSUE THREAD

**Issue by nerohmot** [spyder-ide/spyder#17835]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
We want to release a plugin to spyder on conda-forge. 
Our package must be a `noarch` type with the twist that python >= 3.8.
conda-forge insists  and we run `pip check` in the recipe (which makes a lot of sense), however this fails because spyder relays on `applaunchservices` for OSX, but not all it's dependencies are in conda-forge :frowning_face: and thus the check fails as follows: 

![image](https://user-images.githubusercontent.com/3516972/167175197-a5ccc718-c9d1-4891-904c-adbf4fa72f40.png)
 
Fortunately for us, @goanpeca is the conda-forge reviewer, so I asked him if he could approve our feedstock when I do the following in or recipe: 

![image](https://user-images.githubusercontent.com/3516972/167175538-163117f6-c356-4d43-bdab-68c1b92d41d2.png)

This will get me up and running, however the cleaner way would be if we take the `applaunchservices` out of spyder's conda-forge recipe, this way others (like this guy from `PROCITEC` ?) will not have the same problem as us.

All plugins can then enable the normal `pip check` without selectors (and discussions with conda-forge) and once the `applauchservices` work again, then we can enable it again and support for spyder on OSX under CONDA, the plugin recipies don't have to do anything anymore (presumed that the plugins are `noarch`)

Could this be done in the upcomming 5.3.1 release already ?

**Comment by ccordoba12** [comment]
Thanks for reporting @nerohmot! We'll take a look at this in our next release.

**Comment by nerohmot** [comment]
:pray:

**Comment by mrclary** [comment]
@impact27 is looking into this already. This is not a Spyder issue but an `applaunchservices` conda packaging issue, AFIK. See https://github.com/impact27/applaunchservices/issues/1

**Comment by ccordoba12** [comment]
We can fix this on our side by requiring a more recent version of `applaunchservices`.
