### ISSUE TITLE
Autoformat file on save prevents saving files

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#17836]
## Problem Description

Closing a modified file with `Autoformat file on save` active doesn't save the file

### What steps reproduce the problem?

0. Activate `Autoformat file on save`
1. New untitled file
2. Modify file
3. Close file answering yes to save it

### What is the expected output? What do you see instead?

Saved file vs File not saved

**Comment by dalthviz** [comment]
Note: This is probably caused due to closing the file while the the autoformat is being done since the `save` method returns immediately

**Comment by ccordoba12** [comment]
Then you could use a QEventLoop to block the save method until the formatting response returns from the PyLSP.
