### ISSUE TITLE
How to get vars names from variable explorer?

### ISSUE THREAD

**Issue by jesieleo** [spyder-ide/spyder#17866]
I want to get all `var Names` in the `Variable Explorer` as a`list` ,but i dont know how to do it? 
I would appreciate it if you would help me.
<img width="631" alt="捕获" src="https://user-images.githubusercontent.com/90036937/168107788-5860b066-2b80-46b9-bb71-61bcc645f6e5.PNG">

**Comment by dalthviz** [comment]
Hi @jesieleo! For that you could call from the IPython Console something like the following:

```python
list(get_ipython().kernel.get_namespace_view().keys())
```

Not totally sure if there are other methods to achieve something like this but let us know if that helps!

**Comment by jesieleo** [comment]
@dalthviz Thanks a lot, that's exactly what I needed.

> ```python
> list(get_ipython().kernel.get_namespace_view().keys())
> ```

**Comment by dalthviz** [comment]
Awesome @jesieleo glad to here it worked for you. I will then close this one as completed but if you have any other question let us know!
