### ISSUE TITLE
No idea what's wrong

### ISSUE THREAD

**Issue by Lehong-Wang** [spyder-ide/spyder#17867]
### What steps will reproduce the problem?

i don't know what happened.
I just pip installed spyder-kernels 2.3.0, and refreshed the console

### Traceback
A large number of repetitions of:
```python-traceback
Exception in comms call flush_std:
  File "/Users/lhwang/.pyenv/versions/3.10.4/lib/python3.10/site-packages/spyder_kernels/comms/commbase.py", line 340, in _handle_remote_call
    msg_dict = msg['content']
  File "/Users/lhwang/.pyenv/versions/3.10.4/lib/python3.10/site-packages/spyder_kernels/comms/commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](
spyder_kernels.comms.commbase.CommError: No such spyder call type: flush_std
```

## Versions

* Spyder version: 5.3.0 
* Python version: 3.9.5
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Darwin 20.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7            :  0.2.1 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.32.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.5.0 (OK)
nbconvert >=4.0                      :  6.4.5 (OK)
numpydoc >=0.6.0                     :  1.2.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.13.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.0 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.0.1                         :  2.0.1 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  60.10.0 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.0;<2.4.0        :  2.3.0 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.7 (OK)
zmq >=17                             :  22.3.0 (OK)

# Optional:
cython >=0.21                        :  0.29.28 (OK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  1.4.1 (OK)
scipy >=0.17.0                       :  1.8.0 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @Lehong-Wang thank you for the feedback! Quite strange indeed I'm not totally sure what could be happening :/ Are you using the standalone MacOS installer? Could you share with use the `pip list` output of your custom interpreter? Also pinging @mrclary and @impact27 (maybe they could have some ideas)

**Comment by mrclary** [comment]
@Lehong-Wang, in addition to what @dalthviz mentioned, What pyenv environments do you have? At the command line:
```
$ pyenv versions
  system
* 3.10.3 (set by /Users/rclary/.pyenv/version)
  3.10.3/envs/spy-build
  spy-build
```
Can you confirm that the Python interpreter in Spyder correctly points to the environment you are trying to use? I know that there is an issue where selecting the Python interpreter (which may be a symlink) resolves to a path outside the environment. Following is an example of a virtual environment I have called "spy-build".
<img width="1162" alt="Screen Shot 2022-05-13 at 10 48 13 AM" src="https://user-images.githubusercontent.com/9618975/168339518-46227e63-aa82-446c-b937-be7809ce5000.png">

**Comment by ccordoba12** [comment]
@Lehong-Wang, if you updated spyder-kernels while Spyder was running, then you need to close it and open it again. That could solve your problem.

**Comment by Lehong-Wang** [comment]
Hi, Thank you so much for answering my question.
Restarting Spyder did solve the problem! : )  
Sorry about the problem being so dumb.

Also, here is the result of pip list:
`
pip list
Package                                           Version
------------------------------------------------- -----------
aiohttp                                           3.8.1
aiosignal                                         1.2.0
alabaster                                         0.7.12
anyio                                             3.5.0
applaunchservices                                 0.2.1
appnope                                           0.1.3
argon2-cffi                                       21.3.0
argon2-cffi-bindings                              21.2.0
arrow                                             1.2.2
astroid                                           2.11.5
asttokens                                         2.0.5
async-timeout                                     4.0.2
atomicwrites                                      1.4.0
attrs                                             21.4.0
autobahn                                          21.11.1
autopep8                                          1.6.0
Babel                                             2.10.1
backcall                                          0.2.0
beautifulsoup4                                    4.11.1
binaryornot                                       0.4.4
black                                             22.3.0
bleach                                            5.0.0
certifi                                           2021.10.8
cffi                                              1.15.0
chardet                                           4.0.0
charset-normalizer                                2.0.12
click                                             8.1.3
cloudpickle                                       2.0.0
cookiecutter                                      1.7.3
cryptography                                      37.0.2
debugpy                                           1.6.0
decorator                                         5.1.1
defusedxml                                        0.7.1
diff-match-patch                                  20200713
dill                                              0.3.4
docutils                                          0.17.1
entrypoints                                       0.4
executing                                         0.8.3
fastjsonschema                                    2.15.3
flake8                                            4.0.1
frozenlist                                        1.3.0
hyperlink                                         21.0.0
idna                                              3.3
imagesize                                         1.3.0
importlib-metadata                                4.11.3
inflection                                        0.5.1
intervaltree                                      3.1.0
ipykernel                                         6.13.0
ipython                                           7.33.0
ipython-genutils                                  0.2.0
ipywidgets                                        7.7.0
isort                                             5.10.1
jedi                                              0.18.1
jellyfish                                         0.9.0
Jinja2                                            3.1.2
jinja2-time                                       0.2.0
jsonschema                                        4.5.1
jupyter                                           1.0.0
jupyter-client                                    7.3.1
jupyter-console                                   6.4.3
jupyter-core                                      4.10.0
jupyter-server                                    1.17.0
jupyter-server-proxy                              3.2.1
jupyterlab-pygments                               0.2.2
jupyterlab-widgets                                1.1.0
keyring                                           23.5.0
lazy-object-proxy                                 1.7.1
MarkupSafe                                        2.1.1
matplotlib-inline                                 0.1.3
mccabe                                            0.6.1
mistune                                           0.8.4
multidict                                         6.0.2
mypy-extensions                                   0.4.3
nbclient                                          0.6.3
nbconvert                                         6.5.0
nbformat                                          5.4.0
nest-asyncio                                      1.5.5
notebook                                          6.4.11
numpy                                             1.22.3
numpy-stl                                         2.17.0
numpydoc                                          1.3.1
packaging                                         21.3
pandocfilters                                     1.5.0
parso                                             0.8.3
pathspec                                          0.9.0
pexpect                                           4.8.0
pickleshare                                       0.7.5
pip                                               22.1
platformdirs                                      2.5.2
pluggy                                            1.0.0
poyo                                              0.5.0
prometheus-client                                 0.14.1
prompt-toolkit                                    3.0.29
psutil                                            5.9.0
ptyprocess                                        0.7.0
pure-eval                                         0.2.2
pycodestyle                                       2.8.0
pycparser                                         2.21
pydocstyle                                        6.1.1
pyflakes                                          2.4.0
Pygments                                          2.12.0
pylint                                            2.13.8
pyls-spyder                                       0.4.0
pyobjc                                            8.5
pyobjc-core                                       8.5
pyobjc-framework-Accessibility                    8.5
pyobjc-framework-Accounts                         8.5
pyobjc-framework-AddressBook                      8.5
pyobjc-framework-AdServices                       8.5
pyobjc-framework-AdSupport                        8.5
pyobjc-framework-AppleScriptKit                   8.5
pyobjc-framework-AppleScriptObjC                  8.5
pyobjc-framework-ApplicationServices              8.5
pyobjc-framework-AppTrackingTransparency          8.5
pyobjc-framework-AudioVideoBridging               8.5
pyobjc-framework-AuthenticationServices           8.5
pyobjc-framework-AutomaticAssessmentConfiguration 8.5
pyobjc-framework-Automator                        8.5
pyobjc-framework-AVFoundation                     8.5
pyobjc-framework-AVKit                            8.5
pyobjc-framework-BusinessChat                     8.5
pyobjc-framework-CalendarStore                    8.5
pyobjc-framework-CallKit                          8.5
pyobjc-framework-CFNetwork                        8.5
pyobjc-framework-ClassKit                         8.5
pyobjc-framework-CloudKit                         8.5
pyobjc-framework-Cocoa                            8.5
pyobjc-framework-Collaboration                    8.5
pyobjc-framework-ColorSync                        8.5
pyobjc-framework-Contacts                         8.5
pyobjc-framework-ContactsUI                       8.5
pyobjc-framework-CoreAudio                        8.5
pyobjc-framework-CoreAudioKit                     8.5
pyobjc-framework-CoreBluetooth                    8.5
pyobjc-framework-CoreData                         8.5
pyobjc-framework-CoreHaptics                      8.5
pyobjc-framework-CoreLocation                     8.5
pyobjc-framework-CoreMedia                        8.5
pyobjc-framework-CoreMediaIO                      8.5
pyobjc-framework-CoreMIDI                         8.5
pyobjc-framework-CoreML                           8.5
pyobjc-framework-CoreMotion                       8.5
pyobjc-framework-CoreServices                     8.5
pyobjc-framework-CoreSpotlight                    8.5
pyobjc-framework-CoreText                         8.5
pyobjc-framework-CoreWLAN                         8.5
pyobjc-framework-CryptoTokenKit                   8.5
pyobjc-framework-DeviceCheck                      8.5
pyobjc-framework-DictionaryServices               8.5
pyobjc-framework-DiscRecording                    8.5
pyobjc-framework-DiscRecordingUI                  8.5
pyobjc-framework-DiskArbitration                  8.5
pyobjc-framework-DVDPlayback                      8.5
pyobjc-framework-EventKit                         8.5
pyobjc-framework-ExceptionHandling                8.5
pyobjc-framework-ExecutionPolicy                  8.5
pyobjc-framework-ExternalAccessory                8.5
pyobjc-framework-FileProvider                     8.5
pyobjc-framework-FileProviderUI                   8.5
pyobjc-framework-FinderSync                       8.5
pyobjc-framework-FSEvents                         8.5
pyobjc-framework-GameCenter                       8.5
pyobjc-framework-GameController                   8.5
pyobjc-framework-GameKit                          8.5
pyobjc-framework-GameplayKit                      8.5
pyobjc-framework-ImageCaptureCore                 8.5
pyobjc-framework-IMServicePlugIn                  8.5
pyobjc-framework-InputMethodKit                   8.5
pyobjc-framework-InstallerPlugins                 8.5
pyobjc-framework-InstantMessage                   8.5
pyobjc-framework-Intents                          8.5
pyobjc-framework-IOSurface                        8.5
pyobjc-framework-iTunesLibrary                    8.5
pyobjc-framework-KernelManagement                 8.5
pyobjc-framework-LatentSemanticMapping            8.5
pyobjc-framework-LaunchServices                   8.5
pyobjc-framework-libdispatch                      8.5
pyobjc-framework-LinkPresentation                 8.5
pyobjc-framework-LocalAuthentication              8.5
pyobjc-framework-MapKit                           8.5
pyobjc-framework-MediaAccessibility               8.5
pyobjc-framework-MediaLibrary                     8.5
pyobjc-framework-MediaPlayer                      8.5
pyobjc-framework-MediaToolbox                     8.5
pyobjc-framework-Metal                            8.5
pyobjc-framework-MetalKit                         8.5
pyobjc-framework-MetalPerformanceShaders          8.5
pyobjc-framework-MetalPerformanceShadersGraph     8.5
pyobjc-framework-MLCompute                        8.5
pyobjc-framework-ModelIO                          8.5
pyobjc-framework-MultipeerConnectivity            8.5
pyobjc-framework-NaturalLanguage                  8.5
pyobjc-framework-NetFS                            8.5
pyobjc-framework-Network                          8.5
pyobjc-framework-NetworkExtension                 8.5
pyobjc-framework-NotificationCenter               8.5
pyobjc-framework-OpenDirectory                    8.5
pyobjc-framework-OSAKit                           8.5
pyobjc-framework-OSLog                            8.5
pyobjc-framework-PassKit                          8.5
pyobjc-framework-PencilKit                        8.5
pyobjc-framework-Photos                           8.5
pyobjc-framework-PhotosUI                         8.5
pyobjc-framework-PreferencePanes                  8.5
pyobjc-framework-PushKit                          8.5
pyobjc-framework-Quartz                           8.5
pyobjc-framework-QuickLookThumbnailing            8.5
pyobjc-framework-ReplayKit                        8.5
pyobjc-framework-SafariServices                   8.5
pyobjc-framework-SceneKit                         8.5
pyobjc-framework-ScreenSaver                      8.5
pyobjc-framework-ScreenTime                       8.5
pyobjc-framework-ScriptingBridge                  8.5
pyobjc-framework-SearchKit                        8.5
pyobjc-framework-Security                         8.5
pyobjc-framework-SecurityFoundation               8.5
pyobjc-framework-SecurityInterface                8.5
pyobjc-framework-ServiceManagement                8.5
pyobjc-framework-Social                           8.5
pyobjc-framework-SoundAnalysis                    8.5
pyobjc-framework-Speech                           8.5
pyobjc-framework-SpriteKit                        8.5
pyobjc-framework-StoreKit                         8.5
pyobjc-framework-SyncServices                     8.5
pyobjc-framework-SystemConfiguration              8.5
pyobjc-framework-SystemExtensions                 8.5
pyobjc-framework-UniformTypeIdentifiers           8.5
pyobjc-framework-UserNotifications                8.5
pyobjc-framework-UserNotificationsUI              8.5
pyobjc-framework-VideoSubscriberAccount           8.5
pyobjc-framework-VideoToolbox                     8.5
pyobjc-framework-Virtualization                   8.5
pyobjc-framework-Vision                           8.5
pyobjc-framework-WebKit                           8.5
pyparsing                                         3.0.9
PyQt5                                             5.15.6
PyQt5-Qt5                                         5.15.2
PyQt5-sip                                         12.10.1
PyQtWebEngine                                     5.15.5
PyQtWebEngine-Qt5                                 5.15.2
pyrsistent                                        0.18.1
python-dateutil                                   2.8.2
python-lsp-black                                  1.2.1
python-lsp-jsonrpc                                1.0.0
python-lsp-server                                 1.4.1
python-math                                       0.0.1
python-slugify                                    6.1.2
python-utils                                      3.2.0
pytz                                              2022.1
pyzmq                                             22.3.0
QDarkStyle                                        3.0.3
qstylizer                                         0.2.1
QtAwesome                                         1.1.1
qtconsole                                         5.3.0
QtPy                                              2.1.0
requests                                          2.27.1
rope                                              1.0.0
Rtree                                             1.0.0
Send2Trash                                        1.8.0
setuptools                                        62.2.0
simpervisor                                       0.4
six                                               1.16.0
sniffio                                           1.2.0
snowballstemmer                                   2.2.0
sortedcontainers                                  2.4.0
soupsieve                                         2.3.2.post1
Sphinx                                            4.5.0
sphinxcontrib-applehelp                           1.0.2
sphinxcontrib-devhelp                             1.0.2
sphinxcontrib-htmlhelp                            2.0.0
sphinxcontrib-jsmath                              1.0.1
sphinxcontrib-qthelp                              1.0.3
sphinxcontrib-serializinghtml                     1.1.5
spyder                                            5.3.0
spyder-kernels                                    2.3.0
stack-data                                        0.2.0
terminado                                         0.13.3
text-unidecode                                    1.3
textdistance                                      4.2.2
three-merge                                       0.1.1
tinycss2                                          1.1.1
toml                                              0.10.2
tomli                                             2.0.1
tornado                                           6.1
traitlets                                         5.2.0
txaio                                             22.2.1
ujson                                             5.2.0
urllib3                                           1.26.9
vpython                                           7.6.3
watchdog                                          2.1.7
wcwidth                                           0.2.5
webencodings                                      0.5.1
websocket-client                                  1.3.2
widgetsnbextension                                3.6.0
wrapt                                             1.14.1
wurlitzer                                         3.0.2
yapf                                              0.32.0
yarl                                              1.7.2
zipp                                              3.8.0
`

and the version of pyenv:
3.10.4 (set by /Users/lhwang/.pyenv/version)

and the path I did set the correct path to python interpreter.

Thanks,
Lehong

**Comment by mrclary** [comment]
@Lehong-Wang I'm glad it is now working for you!

I'm going to close this issue, but if there are any further complications, you may reopen this issue or open another.
