### ISSUE TITLE
Spyder will not run Python scripts

### ISSUE THREAD

**Issue by Lazeau** [spyder-ide/spyder#17886]
### What steps will reproduce the problem?

I was attempting to use the program MDSPlus with MATLAB R2022a, and needed a compatible version of CPython installed. After some headache, I figured out that I was simply dealing with incompatible versions of Python and MATLAB, and fixed this issue. In the process of doing this, I completely reinstalled Python 3.9.12 and Spyder 5.0.5 via Anaconda3. I have tried updating to Spyder 5.1.5, and encountered this same issue with the same error trace below. Now, when I launch Spyder in either version and attempt to run any script (with the Run button), there is an output in the IPython Console that indicates the script is attempting to run, and the Spyder Issue Report wizard immediately pops up and says that "Spyder has encountered an internal problem!"; this is the wizard I am using to submit this issue report. The following error trace is provided, and I do not understand how I can fix this:

Traceback (most recent call last):
  File "C:\Users\----\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\----\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 267, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\----\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\----\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'

I CAN run Python scripts perfectly fine using the Anaconda Prompt (I currently only have Python installed via Anaconda3, as opposed to before I went through this whole reinstallation process where I had Python 3.8 installed via Anaconda, and Python 3.9 installed on my system but outside Anaconda; I am still a little unfamiliar with how the Python environments on my system play with one another and whether that could be contributing to this problem), and even did some debugging in Spyder so that I could run the script I wanted to test this with. I can update and save code in Spyder and then run via the Anaconda Prompt without issue. The problem I am experiencing seems to be in the interface between the scripts and Spyder's execution of them within the IDE. I am using the latest version of Windows 11 and the Interpreter being used by Spyder under Preferences is correct. Apologies if this report is a little redundant, any help would be appreciated.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\matth\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\matth\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 267, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\matth\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\matth\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.3.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.12.2 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Lazeau, thanks for reporting. This error is already fixed in our latest version (5.3.0).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
