### ISSUE TITLE
Add Debug line functionality to Debug menu and toolbar

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#17888]
So Spyder's menu bar has Run and Debug menus which have items for running/debugging a file and running/debugging a cell, and running the current line, but not debugging the current line. I propose adding this menu item to the Debug menu bar. Similar to running a single line, which pastes the current line into the IPython console and executes, debugging a single line can paste the line into the IPython console prepended with "debug" and thus invoke the debugger for executing the single line of code.

**Comment by ccordoba12** [comment]
@impact27, do you have other ideas about this?

**Comment by ccordoba12** [comment]
I'd just like to avoid that error and simply forbid debugging a line if it's not valid. IPython has a way to check for complete statements with this method called `check_complete` (I think):

https://github.com/ipython/ipython/blob/32c393b6babeb82dab97aa4f2ac73edc358b4ebf/IPython/core/inputtransformer2.py#L633

**Comment by mrclary** [comment]
What about `ast.parse`?

**Comment by mrclary** [comment]
`check_complete` will only return `'complete'`, `'incomplete'`, or `'invalid'`. Would the traceback returned by `ast.parse` be more useful to the user to explain why the code cannot be run?

**Comment by mrclary** [comment]
> I disagree with showing a traceback because users would think it's an error in Spyder. I mean, I doubt people would pay attention to the traceback. They'd probably just read the word `error` at the end and associate it intuitively to a Spyder error.

I completely agree. I think we should "groom" the message. My point was only the tool `check_complete` provides so little information.

> What I propose is that before trying to run `%debug <line>` in the console, we check if the line is complete. If it's not, then we could either:
> 
> * Show a QMessageBox saying that the line can't be debugged because it's not a complete Python statement.
> * Do nothing. That could sound a bit too much, but I guess people would grasp what kind of lines can and can't be debugged.

Yep. I think that's right.

**Comment by mrclary** [comment]
However, to reconsider my previous agreement, the result of "Run selection or current line" for an invalid code line is:
```python
In [1]: print('hello'
  File "/var/folders/5v/28jqvwxs2cd5fj93gvwnykdrqc926z/T/ipykernel_70626/3871997710.py", line 1
    print('hello'
                 ^
SyntaxError: unexpected EOF while parsing
```
Perhaps we want the debug counterpart to behave the same...

**Comment by impact27** [comment]
I agree that "run line" raises a `SyntaxError` so it would make sense that debug line raises one too.

**Comment by ccordoba12** [comment]
I think that's a bug that we should fix. It was reported a long time ago (see issue #4431), but we haven't had time to address it.

@mrclary, if could fix it as part of implementing this feature, it'd be great. If not, I'll try to do it in a future release.

**Comment by mrclary** [comment]
@ccordoba12, after reviewing #4431, I think I understand better what you mean.
* Yes, I think that @CAM-Gerlach's [comment](https://github.com/spyder-ide/spyder/issues/4431#issuecomment-484248467) could be incorporated into the PR for this issue.
* However, for both the Run line and Debug line, after considering the smallest appropriate code block, if there is a legitimate syntax error, I think that an exception should be raised.

**Comment by ccordoba12** [comment]
> Yes, I think that @CAM-Gerlach's https://github.com/spyder-ide/spyder/issues/4431#issuecomment-484248467 could be incorporated into the PR for this issue.

Instead of trying to expand the current selection to reach a valid multi-line statement, I think we should simply check the current line, paste it in the console if valid but incomplete, and generate a new line expecting that it'll be completed eventually.

> However, for both the Run line and Debug line, after considering the smallest appropriate code block, if there is a legitimate syntax error, I think that an exception should be raised.

Agreed.

**Comment by CAM-Gerlach** [comment]
> Instead of trying to expand the current selection to reach a valid multi-line statement, I think we should simply check the current line, paste it in the console if valid but incomplete, and generate a new line expecting that it'll be completed eventually.

This isn't really useful, at least if I understand you correctly. More often than not on such multi-line statements, my cursor is at the _end_ of it (or at least not on the first line), so I'd have to navigate all the way up to the first line and then press the run line shortcut on each line until it gets to the bottom, which is around the same if not more work than just selecting the text (with the KB or mouse) and then pressing the run line shortcut once.

If we're already parsing the AST, it should be fairly straightforward to extract the smallest complete statement from that, no? And we could just issue an error or just run the current line on edge cases, like we already do, for the sake of handling the vast majority of useful ones.
