### ISSUE TITLE
Spyder 5.3 did not install spyder-kernel

### ISSUE THREAD

**Issue by Tunneller** [spyder-ide/spyder#17910]
Only a minor bug, but one that should likely be fixed or at least documented. Using the automated download for spyder 5.3 onto Windows 10 did not install spyder-kernels=2.3 which led to some odd behaviour, that was ultimately resolved with conda install -c conda-forge spyder-kernel=2.3.   

Appreciate the support of Spyder!

T.

**Comment by dalthviz** [comment]
Hi @Tunneller thank you for the feedback! I'm guessing you donwloaded the standalone installer from the 'check updates' dialog right? Just in case, if you are now using the standalone Spyder version, this could be useful: https://docs.spyder-ide.org/current/faq.html#using-packages-installer 

Also, maybe this is related with #17424 

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
