### ISSUE TITLE
Startup run code of IPython is not working when using projects

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#17915]
### What steps will reproduce the problem?

Hello.

This promblem is similar to #16748.
This issue is also occurring in 5.x branch.

Thank you.

## Versions

* Spyder version: 5.4.0.dev0 30e09f8ee
* Python version: 3.9.12
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-110-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                  :  1.4.0 (OK)
chardet >=2.0.0                       :  4.0.0 (OK)
cloudpickle >=0.5.0                   :  2.0.0 (OK)
cookiecutter >=1.6.0                  :  1.7.3 (OK)
diff_match_patch >=20181111           :  20200713 (OK)
intervaltree >=3.0.2                  :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0               :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                 :  0.18.1 (OK)
jellyfish >=0.7                       :  0.8.2 (OK)
jsonschema >=3.2.0                    :  4.4.0 (OK)
keyring >=17.0.0                      :  23.4.0 (OK)
nbconvert >=4.0                       :  6.4.4 (OK)
numpydoc >=0.6.0                      :  1.2 (OK)
parso >=0.7.0;<0.9.0                  :  0.8.3 (OK)
pexpect >=4.4.0                       :  4.8.0 (OK)
pickleshare >=0.4                     :  0.7.5 (OK)
psutil >=5.3                          :  5.8.0 (OK)
pygments >=2.0                        :  2.11.2 (OK)
pylint >=2.5.0                        :  2.9.6 (OK)
pyls_spyder >=0.4.0                   :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                  :  1.4.1 (OK)
pylsp_black >=1.2.0                   :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0             :  3.0.3 (OK)
qstylizer >=0.1.10                    :  0.1.10 (OK)
qtawesome >=1.0.2                     :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0              :  5.4.0.dev0 (OK)
qtpy >=2.1.0                          :  2.1.0 (OK)
rtree >=0.9.7                         :  0.9.7 (OK)
setuptools >=49.6.0                   :  59.5.0 (OK)
sphinx >=0.6.6                        :  4.4.0 (OK)
spyder_kernels >=2.3.0;<2.4.0         :  2.4.0.dev0 (OK)
textdistance >=4.2.0                  :  4.2.1 (OK)
three_merge >=0.1.1                   :  0.1.1 (OK)
watchdog >=0.10.3                     :  2.1.6 (OK)
xdg >=0.26                            :  0.27 (OK)
zmq >=17                              :  22.3.0 (OK)

# Optional:
cython >=0.21                         :  0.29.28 (OK)
matplotlib >=3.0.0                    :  3.5.1 (OK)
numpy >=1.7                           :  1.21.5 (OK)
pandas >=1.1.1                        :  1.4.2 (OK)
scipy >=0.17.0                        :  1.7.3 (OK)
sympy >=0.7.3                         :  1.10.1 (OK)

# Spyder plugins:
spyder_okvim.spyder.plugin 0.0.1.dev0 :  0.0.1-dev0 (OK)
```

**Comment by dalthviz** [comment]
Hi @ok97465 thank you for opening a new issue! We will check this in a future release :+1:

Also I noted that seems like you are using a version of the `spyder-vim` plugin? Could you be interested on submitting a PR to the `spyder-vim` repo so the changes you did to make it compatible with Spyder 5 are there if that is the case? Let us know!

**Comment by ok97465** [comment]
> Also I noted that seems like you are using a version of the spyder-vim plugin? Could you be interested on submitting a PR to the spyder-vim repo so the changes you did to make it compatible with Spyder 5 are there if that is the case? Let us know!

I have created a personal repository([okvim](https://github.com/ok97465/spyder_okvim)) for using Vim on Spyder. Seems like too many changes would be needed to apply this to spyder_vim. I'm sorry.

> I did the test setting as the preference something simple like import os and import os.path as osp though. Any other info to replicate this in our side is greatly appreciated @ok97465

If the startup command is unrelated to the project folder like "import os", it works well.
[#16748](https://github.com/spyder-ide/spyder/issues/16748) But If the startup command loads file in the project folder, it does not work properly only when spyder is started.

**Comment by dalthviz** [comment]
>I have created a personal repository([okvim](https://github.com/ok97465/spyder_okvim)) for using vim key on Spyder. Seems like too many changes would be needed to apply this to spyder-vim. I'm sorry.

Oh I see, I was thinking that you could do a PR replaicing what is currently in the repo with your version (just changing the entrypoint and other related names to use `spyder-vim/SpyderVim/spyder_vim`) and maybe help us maintaing the plugin from that repo but if that not feasible, could be okay if we mention your repo in the issues from the `spyder-vim` repo so users that could be interested in using the plugin with Spyder 5 could check your repo out?

>If the startup command is unrelated to the project folder like "import os", it works well.
https://github.com/spyder-ide/spyder/issues/16748 But If the startup command loads file in the project folder, it does not work properly only when spyder is started.

Does your custom script to run at start has relative imports? Maybe the console is not getting set the project path before running the start script and then is being unable to run it? Will try to check a little bit more to replicate it :+1:

Thanks for the new info @ok97465 !

**Comment by ok97465** [comment]
> Oh I see, I was thinking that you could do a PR replaicing what is currently in the repo with your version (just changing the entrypoint and other related names to use spyder-vim/SpyderVim/spyder_vim) and maybe help us maintaing the plugin from that repo but if that not feasible, could be okay if we mention your repo in the issues from the spyder-vim repo so users that could be interested in using the plugin with Spyder 5 could check your repo out?

My vim has a completely different structure from the spyder vim, so I have to create and upload all the new files. If I do that, my vim has an intermittent error and the bug is often reported on Spyder-ide, which will annoy you. I think it would be better to make the spyder-vim compatible with the spyder 5, and I will try it within next month.

> Does your custom script to run at start has relative imports? Maybe the console is not getting set the project path before running the start script and then is being unable to run it? Will try to check a little bit more to replicate it 

The initial files(import_in_console.py) within the project are as follows:
```python
from numpy import pi
```

Preference > IPython Console > Startup > Run code is below:
```python
from import_in_console import *
```

![Peek 2022-05-22 07-13](https://user-images.githubusercontent.com/22970578/169670657-04805a1c-ebfd-4576-bc37-857b2528404f.gif)

**Comment by dalthviz** [comment]
Thanks for the step by step description @ok97465 ! I was able to reproduce this :+1: Seems like the console when opening a project is not getting the correct working directory set (I'm getting for the first console open with the project my home directory instead):

![imagen](https://user-images.githubusercontent.com/16781833/169879222-2775dfb7-dc4d-48a8-b35d-68de49a6a094.png)

Checking the working directory options I'm seeing this:

![imagen](https://user-images.githubusercontent.com/16781833/169879454-ffd722ba-0e84-4937-ae86-ef767d0ad0ea.png)
