### ISSUE TITLE
Can't finde Option "Do not open recent/last Files"

### ISSUE THREAD

**Issue by nmarc** [spyder-ide/spyder#17927]
Hello, 
i cant't find an option to disable opening the last Files when spyder starts

**Comment by dalthviz** [comment]
Hi @nmarc thank you for the feedback! Currently, I think there is no option to achieve that. Could you describe a little bit more your use case where having that option could make things better? Let us know!

Also, just in case, what do you think @spyder-ide/core-developers ?

**Comment by mrclary** [comment]
This seems like it may be a useful feature that could be added to the Editor's preferences; perhaps included with or after the plugin is migrated to the new api.

**Comment by nmarc** [comment]
I use many different monitors and mostly open several independent (not project related) scripts. The speed of opening a file is very important to me. So I have at least two instances of Spyder open at the same time. Unfortunately, that doesn't work that well. So sometimes I have to switch to other IDEs. ERIC is much faster here.

**Comment by ccordoba12** [comment]
Well, usually IDEs are not the best fit for that because they load a lot of other things besides a single file. I think editors are a better quickly editing files.

For instance, the speed to opening files is one of the reasons people praise Vim so much.

**Comment by CAM-Gerlach** [comment]
To be fair, the per-file load time can sometimes be nearly a full second on my machine; and perhaps half a second to even close a file—particularly given that, such an option seems reasonable, assuming there's someone willing and able to implement it.
