### ISSUE TITLE
getpass echoing

### ISSUE THREAD

**Issue by JAFF-CYBERTHEIF** [spyder-ide/spyder#17929]
# Password_Authenticator
# Instagram @py_coder_wall
# Like | Comment | Share

import getpass
database = {"py_coder_hub":"09876","coderx":"55555"}
username = input("Enter username :")
password = getpass.getpass(prompt="Enter password :",stream=None)
j=0
for i in database.keys():
    if username == i:
        while password != database.get(i) and j<5:
            password = getpass.getpass("Enter password again")
            j=j+1
        break
print ("Verified")    

 
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
getpass.getpass()
 
Echoing

and not showning output

**Comment by ccordoba12** [comment]
Hey @JAFF-CYBERTHEIF, thanks for reporting. Unfortunately, `getpass` doesn't work in Spyder's IPython console.
