### ISSUE TITLE
Problem with open Spyder 4.2.4

### ISSUE THREAD

**Issue by kk0186** [spyder-ide/spyder#17920]
Hi , recently I have problem on debugging in spyder 5.1.1. I have checked online and note that they have some issue on debugging in spyder version 5. I have also tried to install spyder 5.2.2 but still not able to debug so I decided the downgrade to Spyder 4. However, it not working either , so I tired to uninstall Spyder and reinstall spyder 2.4.2 in anaconda. after installed , I cannot open spyder and I got the following message from a pop up window when I tried to launch spyder in Anaconda:

Application spyder launch may have produced errors:
Traceback (most recent call last):
File "C:\Users\user\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 214, in main
mainwindow.main(options, args)
File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3638, in main
mainwindow = create_window(app, splash, options, args)
File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3496, in create_window
main.setup()
File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 788, in setup
from spyder.plugins.console.plugin import Console
File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\console\plugin.py", line 40, in 
from spyder.api.plugins import SpyderPluginWidget
File "C:\Users\user\anaconda3\lib\site-packages\spyder\api\plugins\__init__.py", line 25, in 
from .old_api import SpyderPlugin, SpyderPluginWidget # noqa
File "C:\Users\user\anaconda3\lib\site-packages\spyder\api\plugins\old_api.py", line 22, in 
from spyder.utils.icon_manager import ima
ImportError: cannot import name 'ima' from 'spyder.utils.icon_manager' (C:\Users\user\anaconda3\lib\site-packages\spyder\utils\icon_manager.py)

Any advise on what should I do so that I could open the Spyder again? Much appreciate

**Comment by dalthviz** [comment]
Hi @kk0186! I would suggest you to create a new environment using the conda-forge packages to get the latest Spyder available (Spyder 5.3.0). For that you will need to open an Anaconda prompt and there run something like:

```
conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.0
```

After that to activate the new env `spyder-env` and launch Spyder you can run (also from the Anaconda prompt):

```
conda activate spyder-env
spyder
```

Or use the create shortcut `Spyder (spyder-env)`

Let us know if that helps!

**Comment by ccordoba12** [comment]
Hey @kk0186, thanks for reporting. Sorry that you've had so many issues updating Spyder.

Could you try with our Windows installer? That's much easier to install, so it shouldn't give you problems. You can download it from [here](https://github.com/spyder-ide/spyder/releases).

Let us know if it works for you.

**Comment by kk0186** [comment]
> Hey @kk0186, thanks for reporting. Sorry that you've had so many issues updating Spyder.
> 
> Could you try with our Windows installer? That's much easier to install, so it shouldn't give you problems. You can download it from [here](https://github.com/spyder-ide/spyder/releases).
> 
> Let us know if it works for you.

**Comment by kk0186** [comment]
> Hi @kk0186! I would suggest you to create a new environment using the conda-forge packages to get the latest Spyder available (Spyder 5.3.0). For that you will need to open an Anaconda prompt and there run something like:
> 
> ```
> conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.0
> ```
> 
> After that to activate the new env `spyder-env` and launch Spyder you can run (also from the Anaconda prompt):
> 
> ```
> conda activate spyder-env
> spyder
> ```
> 
> Or use the create shortcut `Spyder (spyder-env)`
> 
> Let us know if that helps!



> Hi @kk0186! I would suggest you to create a new environment using the conda-forge packages to get the latest Spyder available (Spyder 5.3.0). For that you will need to open an Anaconda prompt and there run something like:
> 
> ```
> conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.0
> ```
> 
> After that to activate the new env `spyder-env` and launch Spyder you can run (also from the Anaconda prompt):
> 
> ```
> conda activate spyder-env
> spyder
> ```
> 
> Or use the create shortcut `Spyder (spyder-env)`
> 
> Let us know if that helps!

Thank you very much @dalthviz, I did open the spyder 5, but somehow when I tried to minimise the spyder window , it disappear ( I didn't tried to run anything in spyder yet), when I tried to open it again in anaconda 3 prompt . it shows the follow msg: 
(spyder-env) C:\Users\user>spyder
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\start.py", line 214, in main
    mainwindow.main(options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3638, in main
    mainwindow = create_window(app, splash, options, args)
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3496, in create_window
    main.setup()
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 788, in setup
    from spyder.plugins.console.plugin import Console
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\plugins\console\plugin.py", line 40, in <module>
    from spyder.api.plugins import SpyderPluginWidget
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\api\plugins\__init__.py", line 25, in <module>
    from .old_api import SpyderPlugin, SpyderPluginWidget  # noqa
  File "C:\Users\user\anaconda3\lib\site-packages\spyder\api\plugins\old_api.py", line 22, in <module>
    from spyder.utils.icon_manager import ima
ImportError: cannot import name 'ima' from 'spyder.utils.icon_manager' (C:\Users\user\anaconda3\lib\site-packages\spyder\utils\icon_manager.py)

As I am not  software expertise , so I am not sure if my setting still have any problem. appreciate it if you know what happen in there. Thank you

**Comment by ccordoba12** [comment]
> Thank you very much @ccordoba12, I did able to open the spyder 5 now , and I follow the steps to install the sklearn . 

Great! Glad Spyder is working for you now.

> however, it pop up another msg when I tried to run the script

Unfortunately, Anaconda doesn't come with the corresponding spyder-kernels version to be used with our 5.3.0 version. To account for that you need to follow the instructions in [our video](https://www.youtube.com/watch?v=i7Njb3xO4Fw), but replacing every `conda install` command with `conda install -c conda-forge`.

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by guyonnquan9988-tech** [comment]
by code:pip install --upgrade --force-reinstall spyder,spyder can't start normal, by deduging log,  observing enable_code snippets in section completions,how to do?

**Comment by ccordoba12** [comment]
@guyonnquan9988-tech, if you ran that in a conda environment then you basically broke it. That's because pip and conda packages are binary incompatible, so they can't be mixed in the same environment.

To solve it, I'm afraid you'll have to remove and reinstall Anaconda. And to properly do that, please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) about that (the first part describes in more detail why you can't mix pip and conda packages).

If not, then we recommend you to use our [standalone installer](https://www.spyder-ide.org/download) because pip installations are for experts.
