### ISSUE TITLE
New console opens in home directory, not current project directory

### ISSUE THREAD

**Issue by andreamoro-git** [spyder-ide/spyder#17953]
## Problem Description

The setting "Console directory" does not seem to be working properly anymore. When "The current project directory or user home directory (if no project is active)" is selected, new consoles open on the user home directory

ps. Already tried spyder --reset

* Spyder version: 5.3.0 None
* Python version: 3.9.5 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Darwin 20.6.0

**Comment by ccordoba12** [comment]
Hey @andreamoro-git, thanks for reporting. This problem will be fixed in our next version (5.3.1), to released next week.

For the details, please see pull request #17760.
