### ISSUE TITLE
Command line options don't work.

### ISSUE THREAD

**Issue by jjqtony** [spyder-ide/spyder#17962]
## Problem Description
When I type "Spyder.exe --help" in windows terminal,  no information is displayed and Spyder IDE is not launched.
Whe type "Spyder.exe file.py", Spyder IDE is launched, but file.py is not opened in Spyder editor.

## Versions

* Spyder version:  5.2.2 from winpython 3.10.2
* Operating System name/version:  windows 10/2004

**Comment by ccordoba12** [comment]
Hey @jjqtony, Spyder is not meant to be launched like that, but using instead using an entry on the Windows Start menu.

I don't know if WinPython provides one, but it does, then you should use it.
