### ISSUE TITLE
Unable to do open() / read() function in Spyder

### ISSUE THREAD

**Issue by jaypeeee10** [spyder-ide/spyder#17973]
## Problem Description
Unable to do open() function in Spyder, see sample python code:

myfile = open("C:\\Users\Joann Dayao\Desktop\Python\Python Overall instructions in notepad.txt", "r")
cont = myfile.read()
print(cont)

The output is only below and cannot read contents of the .txt file:

runfile('C:/Users/Joann Dayao/.spyder-py3/temp.py', wdir='C:/Users/Joann Dayao/.spyder-py3')

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

The output is only below and cannot read contents of the .txt file:

runfile('C:/Users/Joann Dayao/.spyder-py3/temp.py', wdir='C:/Users/Joann Dayao/.spyder-py3')

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.0
* Python version: 3.10
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by jaypeeee10** [comment]
Correction on path, it should be below with \\ , but still unable to print the contents of the file
myfile = open("C:\\Users\Joann Dayao\Desktop\Python\Python Overall instructions in notepad.txt", "r")
cont = myfile.read()
print(cont)

**Comment by jaypeeee10** [comment]
Correction on path, it should be below with \\ , but still unable to print the contents of the file
myfile = open("C:\\Users\Joann Dayao\Desktop\Python\Python Overall instructions in notepad.txt", "r")
cont = myfile.read()
print(cont)

**Comment by jaypeeee10** [comment]
Correction on path, it should be below with double \ after C: , but still unable to print the contents of the file
myfile = open("C:\Users\Joann Dayao\Desktop\Python\Python Overall instructions in notepad.txt", "r")
cont = myfile.read()
print(cont)

**Comment by dalthviz** [comment]
Hi @jaypeeee10! If you want to put backslashes to specify your path you will need to pass the path string as a raw string literal (prepending an `r` before the string). So try this:

```python
myfile = open(r"C:\Users\Joann Dayao\Desktop\Python\Python Overall instructions in notepad.txt", "r")
cont = myfile.read()
print(cont)
```

This is not directly related with Spyder but let us know if the above helps!

**Comment by jaypeeee10** [comment]
Hi dalthviz, thank you very much! I've tried to follow this fix by prepending r before the string and my issue resolved!
I have also seen other fix by replacing all backslash to forward slash and it works as well but I'll rather do this solution (prepending r) provided by you since this seems more convenient for me. 
Again thanks very much for helping a beginner like me and apologies since this is not related to spyder issue :) I am enjoying learning python! You may now close this issue.
