### ISSUE TITLE
Variables_explorer to displayed in a tree structure.

### ISSUE THREAD

**Issue by jnasom** [spyder-ide/spyder#17980]
How can VariablesExplorer be displayed in a tree structure?

**Comment by jnasom** [comment]
I want to rewrite a plugin, but I don't know how to do it. I hope to get an answer. Thank you！

**Comment by ccordoba12** [comment]
Hey @jnasom, thanks for reporting. Unfortunately, it's not possible to view variables in a tree structure on Spyder. The best you could do is to use the Object explorer to inspect the namespace of each console, which is described at the end of this section in our docs:

http://docs.spyder-ide.org/current/panes/variableexplorer.html#advanced-functionality

Let us know if that's what you're looking for.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
