### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by JackHeroFly** [spyder-ide/spyder#17991]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```
Hello, spyder5 3.0 how to run two programs at the same time?
## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
You need to open two IPython consoles by going to the menu `Consoles > New console` and running each file in one of them.

**Comment by JackHeroFly** [comment]
> You need to open two IPython consoles by going to the menu `Consoles > New console` and running each file in one of them.

Thanks a lot, but Spyder runs very slowly when you open both consoles. The two consoles seem to interfere with each other, causing Spyder to slow down. So, how to speed up the running of the program when opening two consoles?

**Comment by ccordoba12** [comment]
> So, how to speed up the running of the program when opening two consoles?

That can only be a problem if you have very little RAM in your system (i.e. less than 4 GB). If that's the case for you, the only possible solution is to expand your RAM.
