### ISSUE TITLE
Proble with variable explorer

### ISSUE THREAD

**Issue by Connor9821** [spyder-ide/spyder#17993]
### What steps will reproduce the problem?

using pandas to read file csv creating dataframe, very often is not possible to visualize the dataframe itself in the 'variable explorer'. It appears a message that sais it is impossible to read the dataframe, but it is not occours alwais, it's something that occours in the most of the time and it is particulary diccicoult deal with this proble usign big dataframe. Anyone have any idea how to resolve this problem?

**Comment by Connor9821** [comment]
![image](https://user-images.githubusercontent.com/106152687/170009951-83efcee2-bba9-43ea-8962-02b31296723a.png)

**Comment by ccordoba12** [comment]
Hey @Connor9821, thanks for reporting. You need to provide us with a csv file that generates this error. Otherwise, we won't be able to reproduce on our side.

Also, please let us know what's your Spyder version and how you installed it.

**Comment by jyk4100** [comment]
I have been experiencing similar issue but when using spyder-kernels to connect to kernel running on a remote machine.
Turns out certain versions of pandas will not work with certain versions of spyder-kernel.
For me I was using pandas 1.3.5 with spyder-kernel 2.2.1 and (Spyder 5.2.2) and once I tried to use pandas 1.4.0+ I am getting errors with variable explorer but only with df (dict, list, string works fine).
I suppose your issue might be similar and may worth while trying different versions of pandas / Spyder.

**Comment by Connor9821** [comment]
thanks @jyk4100  for your feedback, unfortunately the problem is still occuring even after I changed the pandas version to `1.3.5`. I don't really know what to do. It is possible that I have to create a spesific envoirement for pandas packages, in anaconda, and define every time the specific directory in spyder ?

**Comment by ccordoba12** [comment]
@Connor9821, I tried with your CSV and it's working fine for me. You need to be sure that the Pandas version used by Spyder and the one of your external environment (it seems you're using one) are 1.4.0 or above. That should solve your problem.

**Comment by Connor9821** [comment]
sorry how can i check it? because if i check by `conda list` it seems to be `pandas 1.4.2` instead if i check with pip it seems to be the `1.3.5` version

**Comment by Connor9821** [comment]
to se the version on spyder i use the command `pd.__version__`

**Comment by ccordoba12** [comment]
> because if i check by conda list it seems to be pandas 1.4.2 instead if i check with pip it seems to be the 1.3.5 version

Well, there's the problem. Please update the pip version to be `1.4.2` as well.

**Comment by Connor9821** [comment]
![pandas version](https://user-images.githubusercontent.com/106152687/170835655-3f5c94d5-fac5-48d0-afd6-8433b0607cfb.png)
now it seems to be updated but it still doesn' work

**Comment by jyk4100** [comment]
@Connor9821 
1. which version of spyder is installed? are you using 5.1.5? have you tried getting updated version of Spyder
2. do you know how to set up conda virtual environment? once you set up a venv you can go to settings/preferences -> python interpreter -> "Use the following Python interpreter" -> point to where your venv is

**Comment by Connor9821** [comment]
@jyk4100  thank you for the advices, i haeve `spyder 5.1.5` and it is the latest version that i can download from anaconda. About the a specifc envoiroment i gonna try now

**Comment by Connor9821** [comment]
unfortunately also with a dedicated envoirement it still doesn't work

**Comment by jyk4100** [comment]
@Connor9821 Have you tried using the "standalone" installer you can get from [here](https://github.com/spyder-ide/spyder/releases/tag/v5.3.1). I have the following setup and it works for me.
1. Spyder 5.3.1 installed through the installer (not through conda)
2. python 3.8.12 python conda venv with pandas 1.4.0

**Comment by Connor9821** [comment]
i have tried this possibility but it appears this.
![kernel](https://user-images.githubusercontent.com/106152687/170839497-5d0aa396-b8b6-4099-a9d7-45e1facfd76f.png)
i have tried to install kernel in the envoirenment but the latest version avaible in anaconda is `2.2.1` enstead of 2.3.0 .

**Comment by Connor9821** [comment]
nervermind i restart spyder and now it works, but the originary problem with the variable explorer is still occours

**Comment by jyk4100** [comment]
@Connor9821 Are you using spyder python pkg or the spyder.exe? have you tried installing spyder.exe on your windows?

**Comment by Connor9821** [comment]
spyder.exe and i have already tried to install in my pc
![installer ](https://user-images.githubusercontent.com/106152687/170839844-d8061400-6587-49e4-a7e4-489eb5a08fbc.png)

**Comment by jyk4100** [comment]
1. Install/open spyder this should be 5.3.1.
2. create new conda env `conda create --name py38 python=3.8`; `source activate py38' ; `conda install pandas=1.4.2`
3. have your spyder use the `py38` venv in the settings "C:\Users\penc9\anaconda3\envs\py38\python.exe"

**Comment by jyk4100** [comment]
also I don't understand what do you mean "spyder 5.1.5 is the latest version" `conda install -c conda-forge spyder=5.3.1`
https://anaconda.org/conda-forge/spyder

**Comment by Connor9821** [comment]
nothing is changed i still can't see the dataframes in the variable explorer and i have done every thing you told to me, but now it appears this
![error](https://user-images.githubusercontent.com/106152687/170875630-6c6825bf-09b2-4be1-bd61-1219cb89e862.png)

**Comment by jyk4100** [comment]
then install those dependencies

**Comment by Connor9821** [comment]
sorry but while i was trying to install the dependencies i found out this
![pandas](https://user-images.githubusercontent.com/106152687/170882281-9d294dd2-2053-4699-8153-4646a8b1b01c.png)
do you know what does it means? it could be this the problem?

**Comment by jyk4100** [comment]
problem is that **you are still using Spyder 5.1.5.** you need to install spyder 5.3.1 and set up a venv with pandas=1.4.0, spyder-kernels=2.3.1 `conda install -c conda-forge spyder-kernels=2.3.1`

**Comment by ccordoba12** [comment]
And you don't even have Pandas installed in the environment where you've Spyder installed.

**Comment by Connor9821** [comment]
ok now i have reinstalled spyder 5.3.1 with python 8.12 and pandas 1.4.0 in the environment  but it still not worked 
![1](https://user-images.githubusercontent.com/106152687/170887980-1b2dc76c-3ab3-498f-a5e6-136716625a8d.png)
![2](https://user-images.githubusercontent.com/106152687/170887987-cf146385-910f-4ebf-8a11-4cb37c4f08c6.png)

**Comment by Connor9821** [comment]
![3](https://user-images.githubusercontent.com/106152687/170888041-99db407f-ba9a-43c6-bcd8-d4705c267e44.png)

**Comment by jyk4100** [comment]
![dd](https://user-images.githubusercontent.com/14896560/170891331-4cbe572f-c198-46cf-a7c2-fab67dfb0cf7.png)

**Comment by ccordoba12** [comment]
@Connor9821, I think you're confusing the environment in which Spyder is installed with one you're running your code. Your last screenshot 

![2](https://user-images.githubusercontent.com/106152687/170887987-cf146385-910f-4ebf-8a11-4cb37c4f08c6.png)

shows that you don't have Pandas installed in your Spyder environment. To do that, you need to close Spyder, open the Anaconda Prompt, activate the Spyder env and install Pandas 1.4.2 on it.

**Comment by Connor9821** [comment]
hello, today i have tried agian to do what you told me but it still doesn't work 
![sys](https://user-images.githubusercontent.com/106152687/170974240-4c0fbc28-c47d-4f7a-9d94-69ee7ca908a9.png)
![panda 2](https://user-images.githubusercontent.com/106152687/170974258-b85fcaae-75f3-418f-823e-e4d791dce846.png)
i have installed pandas 1.4.2 in the specific envoirenment that i called 'data' with python 3.8.12 kernels 2.3.1 but it appears the same issue with the variable explorer.

**Comment by Connor9821** [comment]
and it still occours this 
![dai](https://user-images.githubusercontent.com/106152687/170974637-ec89c2f8-3277-47ee-8d98-bdb1b1951263.png)
i don't know what it means, i have installed pandas froms anaconda promt as you told me

**Comment by Connor9821** [comment]
i don't know if this could be useful but when i try to copy a DataFrame in the variable explorer it apprears a error message 
![copy](https://user-images.githubusercontent.com/106152687/171007822-c35412a1-f93e-47d4-a6b9-d266caf95558.png)
and in the drscription of the error there is this 
`Traceback (most recent call last):
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 102, in get_value
    return self.call_kernel(
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\comms\kernelcomm.py", line 225, in _get_call_return_value
    return super(KernelComm, self)._get_call_return_value(
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 440, in _get_call_return_value
    return self._sync_error(reply['value'])
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 496, in _sync_error
    error_wrapper.raise_error()
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\comms\commbase.py", line 90, in raise_error
    raise self.etype(self)
AttributeError: partially initialized module 'pandas' has no attribute 'Series' (most likely due to a circular import)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\variableexplorer\widgets\main_widget.py", line 567, in copy
    self._current_editor.copy()
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1212, in copy
    obj = self.delegate.get_value(idx)
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1549, in get_value
    return self.parent().get_value(name)
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\widgets\collectionseditor.py", line 1607, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\penc9\AppData\Local\Programs\Spyder\pkgs\spyder\plugins\ipythonconsole\widgets\namespacebrowser.py", line 117, in get_value
    raise ValueError(msg % reason_other)
ValueError: An error occured, see the console..<br><br>Note: Please don't report this problem on Github, there's nothing to do about it.
`

**Comment by ccordoba12** [comment]
I'm sorry but your Anaconda installation seems to be a total mess, so I'd recommend you to remove it and reinstall it again. Please follow the instructions in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that successfully.

Also, please don't run conda commands in our IPython console because it's not meant for that. You always need to run them in the Anaconda Prompt.

**Comment by Connor9821** [comment]
ok i finally manage to use the variable explorer proprerly, i have renstalled anaconda and spyder (after i have cleaned all previous files) and now it seems to work smoothly. Thanks a lot for all yours advices and pacience

**Comment by ccordoba12** [comment]
Great! Glad to hear that Spyder is working again for you.
