### ISSUE TITLE
spyder launch error

### ISSUE THREAD

**Issue by lyjge** [spyder-ide/spyder#18019]
### What steps will reproduce the problem?

error raise DuplicateSectionError(sectname, fpname, configparser.DuplicateSectionError: While reading from 'C:\\Users\\Username\\.spyder-py3\\config\\transient.ini' [line 200]: section 'breakpoints' already exists

### Traceback
```python-traceback
  File "C:\Users\yl7316\Anaconda3\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 445, in _handle_events
    zmq_events = self.socket.EVENTS
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 51, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 63, in _get_attr_opt
    return self.get(opt)
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\zmq\_future.py", line 215, in get
    result = super(_AsyncSocket, self).get(key)
  File "zmq\backend\cython\socket.pyx", line 464, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 135, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: not a socket
Exception in thread Thread-24:
Traceback (most recent call last):
  File "C:\Users\yl7316\Anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\jupyter_client\threaded.py", line 218, in run
    self.ioloop.start()
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\nest_asyncio.py", line 72, in run_forever
    self._run_once()
  File "C:\Users\yl7316\Anaconda3\lib\site-packages\nest_asyncio.py", line 106, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\yl7316\Anaconda3\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\yl7316\Anaconda3\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  2.0.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  8.3.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.4.4 (OK)
numpydoc >=0.6.0               :  1.2 (OK)
paramiko >=2.4.0               :  2.8.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.11.2 (OK)
pylint >=1.0                   :  2.12.2 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.3 (OK)
qtconsole >=4.6.0              :  5.3.0 (OK)
qtpy >=1.5.0                   :  2.0.1 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.4.0 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.3.0 (OK)

# Optional:
cython >=0.21                  :  0.29.28 (OK)
matplotlib >=2.0.0             :  3.5.1 (OK)
numpy >=1.7                    :  1.21.5 (OK)
pandas >=0.13.1                :  1.4.2 (OK)
scipy >=0.17.0                 :  1.7.3 (OK)
sympy >=0.7.3                  :  1.10.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @lyjge ! Could you reset your preferences? For that you can run from an Anaconda prompt `spyder --reset`. This seems related with https://github.com/spyder-ide/spyder/issues/16747 and https://github.com/spyder-ide/spyder/issues/17889

Also, seems like you are using a quite old version of Spyder (the latest version is 5.3.1). If you want to update using anaconda you will need to create a new env using the conda-forge channel running from an Anaconda prompt something like:

```
conda create -n spyder-env -c conda-forge python=3.8 spyder=5.3.1
conda activate spyder-env
spyder
```

Let us know if something of the above helps!

**Comment by lyjge** [comment]
> Hi @lyjge ! Could you reset your preferences? For that you can run from an Anaconda prompt `spyder --reset`. This seems related with #16747 and #17889
> 
> Also, seems like you are using a quite old version of Spyder (the latest version is 5.3.1). If you want to update using anaconda you will need to create a new env using the conda-forge channel running from an Anaconda prompt something like:
> 
> ```
> conda create -n spyder-env -c conda-forge python=3.8 spyder=5.3.1
> conda activate spyder-env
> spyder
> ```
> 
> Let us know if something of the above helps!

Sorry, it seems that this Traceback emerges after I attempted to solve a previous Traceback (resulted in spyder launch failure) which was shown under the title "What steps will reproduce the problem?", where in order to solve the previous Traceback I have deleted file "transient.ini" and then become able to restart spyder, and then a window popped up for error reporting such that I reported like shown in this thread with confusion (two Tracebacks combined reporting). Anyway afterwards I have mannually updated spyder to 5.3.0 by conda install --channel conda-forge "spyder>=5.3". By the way I did not do conda spyder --reset. 

Thanks for the help!

**Comment by dalthviz** [comment]
Thanks for the new info @lyjge ! Seems like you were able to overcome the different issues you faced here, right? I'm closing this one as completed then but if you have any other problem let us know.
