### ISSUE TITLE
Problem with  the installation of spyder 5.2.2

### ISSUE THREAD

**Issue by kk0186** [spyder-ide/spyder#18027]
I am having a debugging problem in my spyder 5.1.5. I tried to install the spyder 5.2.2 in anaconda prompt and it just automatically create  new environment (called spyder-env) and install the spyder 5.2.2. but then, why I tried to open it in anaconda netvigator , it pop up  error window and stated the following:

Traceback (most recent call last):
File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 21, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\user\anaconda3\envs\spyder-env\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\spyder\app\start.py", line 233, in main
from spyder.app import mainwindow
File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\spyder\app\mainwindow.py", line 57, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 28, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

may I know what is the probelm and how to solve it ? thank you

**Comment by ccordoba12** [comment]
Hey @kk0186, thanks for reporting. I have a question for you: did you `pip` use to update Spyder?

**Comment by kk0186** [comment]
> Hey @kk0186, thanks for reporting. I have a question for you: did you `pip` use to update Spyder?

@ccordoba12 Thank you very much for your help again, since anaconda navigator not able to install spyder 5.2 , so I search online someone suggest do this on prompt. I typed the following:

conda create -n spyder-env -c conda-forge python=3.9 spyder=5.2.2

I think i install it in conda forge

**Comment by ccordoba12** [comment]
> I think i install it in conda forge

Yeah and that's fine.

I have another question for you: what's your Windows version? I say it because if it's Windows 8 or older, you couldn't be able to use Spyder.

**Comment by Leilei-astro** [comment]
My system is macOS Monterey 12.2.1 (Apple M1), I also bumped into the error when I tried to open Spyder after installed Anaconda3-2022.05-MacOSX-arm64:
Traceback (most recent call last):
  File "/Users/leilei/Applications/Anaconda/anaconda3/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/leilei/Applications/Anaconda/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/Users/leilei/Applications/Anaconda/anaconda3/lib/python3.9/site-packages/spyder/app/start.py", line 233, in main
    from spyder.app import mainwindow
  File "/Users/leilei/Applications/Anaconda/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 59, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/Users/leilei/Applications/Anaconda/anaconda3/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 27, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

PS: Spyder is my favourite scientific tool. I  hope it can be able to use on Mac M1 system.

**Comment by ccordoba12** [comment]
@Leilei-astro, please remove Anaconda and reinstall it again to fix this problem. Unfortunately, by using pip to update it Spyder, you broke it.

After doing that and then running again

    conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.1

to install our latest version, you also need to run

    conda activate spyder-env
    spyder

to use the version you installed in the `spyder-env` environment.

**Comment by kk0186** [comment]
> > I think i install it in conda forge
> 
> Yeah and that's fine.
> 
> I have another question for you: what's your Windows version? I say it because if it's Windows 8 or older, you couldn't be able to use Spyder.

Mine is Window 11 home edition

**Comment by Leilei-astro** [comment]
@ccordoba12  As you said, I removed anaconda and reinstalled Anaconda3-2022.05-MacOSX-arm64.
I tried `conda create -n spyder-env -c conda-forge python=3.9 spyder=5.3.1`, but there are one error:
PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=5.3.1

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I tried `conda create -n spyder-env -c conda-forge python=3.9 spyder` and created an Spyder, but it cannot work after `conda activate spyder-env`
`spyder`
(Traceback the same error about PyQt5.QtWebEngineWidgets occurred before).

**Comment by Leilei-astro** [comment]
> > it seems I didn't get any chance to use the 5.2.2. for some reason... the reason I do this is because I never got chance to debug my program using spyder 5
> 
> As I said above, after installing Spyder with
> 
> ```
> conda create -n spyder-env -c conda-forge python=3.9 spyder=5.2.2
> ```
> 
> you need to open the Anaconda Prompt and run there these commands
> 
> ```
> conda activate spyder-env
> spyder
> ```
> 
> > As you said, I removed anaconda and reinstalled Anaconda3-2022.05-MacOSX-arm64
> 
> Please uninstall it again and use instead the Intel version instead. That's because Spyder is not working in Conda-forge yet for M1 chips (it will be in a month or so).

Thank you very much. I uninstalled M1 version and reinstalled Intel version, now I can use the Spyder without creating a new env.

**Comment by kk0186** [comment]
> > it seems I didn't get any chance to use the 5.2.2. for some reason... the reason I do this is because I never got chance to debug my program using spyder 5
> 
> As I said above, after installing Spyder with
> 
> ```
> conda create -n spyder-env -c conda-forge python=3.9 spyder=5.2.2
> ```
> 
> you need to open the Anaconda Prompt and run there these commands
> 
> ```
> conda activate spyder-env
> spyder
> ```
> 
> > As you said, I removed anaconda and reinstalled Anaconda3-2022.05-MacOSX-arm64
> 
> Please uninstall it again and use instead the Intel version instead. That's because Spyder is not working in Conda-forge yet for M1 chips (it will be in a month or so).

@ccordoba12 thank you very much for your advise on my specific problem , I did try to run the command and below is what I got from the prompt:

(base) C:\Users\user>conda activate spyder-env

(spyder-env) C:\Users\user>spyder
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 21, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\spyder-env\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\spyder\app\start.py", line 233, in main
    from spyder.app import mainwindow
  File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\spyder\app\mainwindow.py", line 57, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "C:\Users\user\anaconda3\envs\spyder-env\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 28, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

do I miss some of the module which I need to install ? thank you very much

**Comment by dalthviz** [comment]
Just in case, I think that the error appears for M1 machines since in the [defaul anaconda channel `pyqt` 5.15.2 is available](https://anaconda.org/anaconda/pyqt) for the osx-arm64 architecture so if in the installation not only the conda-forge is checked but also the default channel you will get `pyqt` 5.15.2 installed without `pyqtwebengine`

**Comment by ccordoba12** [comment]
Great catch @dalthviz! I'll write the Anaconda people to let them know about it asap.

**Comment by kk0186** [comment]
> > do I miss some of the module which I need to install ?
> 
> No, you haven't. I'm afraid your Anaconda installation is broken and you have to remove and install it again it to fix this problem.
> 
> Please follow the instructions in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to see how do that properly.

thanks both !. I actually uninstalled the anaconda and reinstalled it according to that youtube video before install spyder 5.2.2 but still not working...

**Comment by ccordoba12** [comment]
Hey @kk0186, please open the Anaconda Prompt and run there

    conda activate spyder-env
    conda install -c conda-forge pyqtwebengine

That could solve your problem.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
