### ISSUE TITLE
I have debug problem on both spyder 4 and spyder 5 

### ISSUE THREAD

**Issue by kk0186** [spyder-ide/spyder#18038]
### What steps will reproduce the problem?

recently have a problem on debugging in spyder 4 and spyder 5, Is there any proble on spyder recently ? I have 2 computer and one installed spyder 5 and another one installed spyder 4. but now both cannot debug . the console freeze and show me something lik this:
c:\users\user\sp2\test.py(1)<module>()
----> 1 import pandas as pd
      2 import numpy as np
      3 import pandas_datareader.data as web
      4 import matplotlib.pyplot as plt
      5 import math
      
      
      
Is it because of my computer or is it because spyder having the problem on debugging? Anyone have suggestion on what should I do ? Thanks

### Traceback
```python-traceback
  File "C:\Users\USER\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\USER\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 338, in _handle_input_request
    if self._hidden:
AttributeError: 'ShellWidget' object has no attribute '_hidden'
```

## Versions

* Spyder version: 4.1.5 
* Python version: 3.8.13
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  4.0.0 (OK)
cloudpickle >=0.5.0            :  2.0.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.31.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.4.4 (OK)
numpydoc >=0.6.0               :  1.2 (OK)
paramiko >=2.4.0               :  2.8.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.8.0 (OK)
pygments >=2.0                 :  2.11.2 (OK)
pylint >=1.0                   :  2.12.2 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  3.0.2 (OK)
qtawesome >=0.5.7              :  1.0.3 (OK)
qtconsole >=4.6.0              :  5.3.0 (OK)
qtpy >=1.5.0                   :  2.0.1 (OK)
rtree >=0.8.3                  :  0.9.7 (OK)
sphinx >=0.6.6                 :  4.4.0 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  22.3.0 (OK)

# Optional:
cython >=0.21                  :  0.29.28 (OK)
matplotlib >=2.0.0             :  3.5.1 (OK)
numpy >=1.7                    :  1.21.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.4 (OK)
sympy >=0.7.3                  :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @kk0186, thanks for reporting. This error is already fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
