### ISSUE TITLE
Spyder variable explorer issue

### ISSUE THREAD

**Issue by joaquinchimenti97** [spyder-ide/spyder#18059]
Hi! I have linux, and now i cant use spyder  variable explorer. All was working right until i upgraded spyder, then i had 2 spyder versions at the same time, spyder and spyder3, i tried uninstalling them but no luck there.

Now, when i start spyder i get the following error code: 
IPython 7.13.0 -- An enhanced Interactive Python.

Traceback (most recent call last):

  File "/tmp/ipykernel_4650/3436525850.py", line 1, in <cell line: 1>
    get_ipython().kernel._show_mpl_backend_errors()

AttributeError: 'SpyderKernel' object has no attribute '_show_mpl_backend_errors'

any suggestions? i cannot use the variable explorer (cant find any variable there).
```

**Comment by ccordoba12** [comment]
Hey @joaquinchimenti97, thanks for reporting. I'm going to close your issue because you didn't take the time to fill the information required in our issue template.

Please open a new issue with that info if you want support from us.
