### ISSUE TITLE
spyder-kernels should be spyder_kernels (related to changing Python interpreter since PYTHONPATH doesn't allow site-packages)

### ISSUE THREAD

**Issue by poikilos** [spyder-ide/spyder#18051]
Issue Report Checklist: done

## Problem Description
Sometimes modules are in a site-packages folder (such as ~/.local/lib/python3.9/site-packages if the package was installed using the --user option) not in Spyder's environment. To prevent version conflicts that would be caused by setting PYTHONPATH manually, people need to use a different Python interpreter as described in a Spyder maintainer's answer on <https://stackoverflow.com/questions/63385123/issue-adding-site-packages-directory-to-pythonpath-in-spyder>.

The package name for the target environment is spyder_kernels not spyder-kernels. I understand that pip isn't recommended, but the error specifically says to run "conda install spyder-kernels==2.3" or "pip install spyder_kernels==2.3.*" and so does the documentation. This may seem like a simple problem but it was very difficult to diagnose since I was following the documentation and the package simply didn't exist. After a long time I found the correct name myself via `ls ~/.virtualenvs/spyder/lib/python3.9/site-packages | grep spyder`.

### What steps reproduce the problem?
A. Go to the documentation site and visit <https://docs.spyder-ide.org/current/troubleshooting/common-illnesses.html> or <https://docs.spyder-ide.org/3/installation.html> or possibly other pages.

or 

B.
1. Install spyder in a virtualenv using pip in a virtualenv as per the install documentation <https://docs.spyder-ide.org/3/installation.html>, 
2. Tools, Preferences, set Python interpreter to the system's python such as "/usr/bin/python3".
3. Restart Spyder (since attempting to restart IPython will say Spyder cannot restart a kernels it didn't start).
4. Run a py file.

### What is the expected output? What do you see instead?
The documentation and the error that occurs both say to install the `spyder-kernels` (with a hyphen), which doesn't exist on pip, but the package will only install if named with an underscore rather than a hyphen.

The output should be `spyder_kernels` not `spyder-kernels` for the package name in the pip instructions (I'm not sure what it is named on conda).

## Versions
* Spyder version: 5.3.1 None
* Python version: 3.9.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Linux 5.10.0-9-amd64

### Dependencies
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.5.1 (OK)
keyring >=17.0.0              :  23.5.1 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.3.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.13.9 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.2 (OK)
sphinx >=0.6.6                :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  23.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)

**Comment by ccordoba12** [comment]
Hey @poikilos, thanks for reporting. You said

> This may seem like a simple problem but it was very difficult to diagnose since I was following the documentation and the package simply didn't exist

It seems you are confusing the package name with the module name. The package name is the one you pass to pip to install it (i.e.`pip install spyder-kernels` in this case), whereas the module name is the one that gets installed in your `site-packages` (i.e. `spyder_kernels`). They are not necessarily the same and it's fine that they are not. That's why when you do

    ls ~/.virtualenvs/spyder/lib/python3.9/site-packages | grep spyder

you get `spyder_kernels` and not `spyder-kernels`. However, the last one is our package name on PyPI:

https://pypi.org/project/spyder-kernels

> The documentation and the error that occurs both say to install the spyder-kernels (with a hyphen), which doesn't exist on pip, but the package will only install if named with an underscore rather than a hyphen.

This probably happened because you copy/pasted the command from the error message, which is a bug and was reported already on issue #17425. What you really need to do is type the command directly on your terminal. 

> Sometimes modules are in a site-packages folder (such as ~/.local/lib/python3.9/site-packages if the package was installed using the --user option) not in Spyder's environment
> 2. Tools, Preferences, set Python interpreter to the system's python such as "/usr/bin/python3"

This is a really, really bad practice and you should stop doing it for the following reasons:

1. You're mixing your system Python (i.e. the one provided by your Linux distro) with extra packages installed with pip. The two are compiled differently, so they incompatible for the most part.
2. Installing packages with `pip --user` pollutes any other Python environment in your system, e.g. Conda, pyenv or virtualenv environments.

Instead, please remove `~/.local/lib/python3.9/site-packages` and use only a virtualenv.

**Comment by poikilos** [comment]
No, I'm not getting confused. Installing with the hyphen does not work for me in my version of pip.

**Comment by ccordoba12** [comment]
> No, I'm not getting confused. Installing with the hyphen does not work for me.

Perhaps you're using an old pip version. But I can assure you that using this command

    pip install spyder-kernels

works:

![imagen](https://user-images.githubusercontent.com/365293/170877273-d998b7be-75ff-4c59-955d-44280ea4184b.png)

As I said, perhaps the problem is that you copied/pasted the command from our error message.

**Comment by poikilos** [comment]
The command was typed manually while reading the error, but you're right it was pip's fault, thanks. Strangely the bug was introduced in pip around 22.0.x and went away around 22.1.x:
- pip 20.3.4 works (in a fresh venv) via `pip install`
- pip 22.0.4 fails (system's copy -- in Devuan Chimera, based on Debian Bullseye)
- pip 22.1.1 works (system's copy after `python3 -m pip install --user --upgrade pip setuptools wheel`)

**Comment by ccordoba12** [comment]
> pip 22.0.4 fails (system's copy -- in Devuan 4 Chimera, based on Debian 11 Bullseye)

That's why you should leave your system Python alone and don't trust it even for things like this.

> pip 22.1.1 works (system's copy after python3 -m pip install --user --upgrade pip setuptools wheel)

This is also really awful, as I said, but up to you.

**Comment by poikilos** [comment]
When creating a virtualenv, upgrading these packages (and virtuanenv) first (outside of the virtualenv) is recommended by some guides. IMO if I can just push the delete key once to clean it up it isn't polluting anything. Thanks for the advice, but I'm aware of the impact.
