### ISSUE TITLE
also can not use it

### ISSUE THREAD

**Issue by yuancc12** [spyder-ide/spyder#18080]
hi, i still can not to use it ,i have already uninstall again or create a new environment,but they just write about

Collecting package metadata (current_repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: f
  channel url: https://conda.anaconda.org/f
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by ccordoba12** [comment]
Hey @yuancc12, please follow the instructions posted bu our bot in the other issues you have opened today. Thanks.
