### ISSUE TITLE
Kernel restart when using an image loaded from PIL

### ISSUE THREAD

**Issue by classAction68** [spyder-ide/spyder#18084]
Hello,

I'm returning to an old problem that was experienced when I updated Spyder. In that case ([Kernel restart when creating plots with Matplotlib #16659](https://github.com/spyder-ide/spyder/issues/16659)) the problem was the kernel restarting when trying to make a plot with Matplotlib and was resolved by changing the version of freetype. It was mainly solved by @ccordoba12 .

The exact same problem has now occurred, but instead of Matplotlib being the problem it is trying to do an operation with the image that has been loading. For example, trying to convert into a numpy array or using matplotlib to display the image. The problem is with code that has always worked perfectly (several years) and still works fine on another PC (Spyder 4.0.1. and python 3.7.6).

The version of Spyder 5.1.5 and python is 3.7.4 as in the previous post.

Here is some sample code:

> from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
test = Image.open('348.tif')
plt.imshow(test)
imarray = np.array(test)

Both plt.imshow(test) and imarray... cause the error message "Restarting kernel"

Many thanks!

**Comment by ccordoba12** [comment]
Hey @classAction68, thanks for reporting. This error should be fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you have two options:

1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if that works for you.

**Comment by classAction68** [comment]
Thanks for the response. I tried solution 2, but then I lost all access to my packages (e.g. Numpy, Scipy, PIL etc.).

I can try 1 at a later time, but for now it is not a good time to be installing new things - some important other programs are running.

**Comment by ccordoba12** [comment]
> Thanks for the response. I tried solution 2, but then I lost all access to my packages (e.g. Numpy, Scipy, PIL etc.).

Yeah, you have to reinstall them from Conda-forge:

    conda activate spyder-cf
    conda install -c conda-forge pillow numpy scipy

Sorry for the inconvenience.

**Comment by classAction68** [comment]
Hi, I finally had a chance to try solution 1 and it seems to have indeed solved the problem.

Thanks!
