### ISSUE TITLE
Shortcuts to create and close IPython consoles

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1808]
_From [vp2...@gmail.com](https://code.google.com/u/117711742539253182268/) on 2014-05-04T12:46:13Z_

What steps will reproduce the problem?

 1.  If I am in an Ipython console or in the editor, it would be nice to have a keyboard shortcut to create a new ipython console, rather than having to right click on the console window and then click "Open an IPython Console."
2. Similarly, it would be nice to have a shortcut to close the current IPython console as well. What version of the product are you using? On what operating system? Spyder 2.2.5
Python 2.7.6
Windows 8.1

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1808_

**Comment by spyder-issues-migrator** [comment]
_From [vp2...@gmail.com](https://code.google.com/u/117711742539253182268/) on 2014-05-06T10:21:46Z_

Actually, I just realized you can already create a new Ipython console by pressing ALT-I, then down arrow, enter.  So my enhancement request would be just for a keyboard shortcut to close the current ipython console. (I don't know about other people, but when I'm coding, I often open a new console just to try something out in a fresh session. Then I close it to get back to my original console.  I repeat this process a lot so keyboard shortcuts would help save time.)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-21T11:31:16Z_

We could use Ctrl+T to open consoles and Ctrl+W to close them. This should work for both Python and IPython consoles.

**Summary:** Shortcut to create and close new consoles  \<span class="oldvalue"> (was: Shortcut to create new ipython console) \</span>  
  **Labels:** Cat-Console Easy MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-21T11:31:36Z_

**Summary:** Shortcuts to create and close consoles  \<span class="oldvalue"> (was: Shortcut to create and close new consoles) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-21T11:37:49Z_

issue #1842 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-21T16:03:34Z_

**Summary:** Shortcuts to create and close IPython consoles  \<span class="oldvalue"> (was: Shortcuts to create and close consoles) \</span>  
  **Status:** Accepted  
  **Labels:** -MS-v2.4 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-22T05:20:52Z_

This was fixed in revision 78a20fb003bf

**Labels:** -Cat-Console Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-22T05:21:09Z_

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-22T05:22:14Z_

The new shortcut is Ctrl+T but it's not global, you need to focus the IPython Console for it to have effect.

**Comment by xgqfrms** [comment]
# how to close one spyder console tab

![image](https://user-images.githubusercontent.com/7291672/51982398-d6f9bf80-24d0-11e9-9e65-bd1cf0aa801a.png)

**Comment by xgqfrms** [comment]
https://github.com/spyder-ide/spyder/issues/4524

**Comment by ccordoba12** [comment]
The problem with no close button appearing in the interface will be fixed in Spyder 4.

**Comment by ccordoba12** [comment]
In the meantime I think you can press the mouse wheel down to close tabs.

**Comment by xgqfrms** [comment]
> The problem with no close button appearing in the interface will be fixed in Spyder 4.

so, I have to waiting for spyder 4 upgrade.

![image](https://user-images.githubusercontent.com/7291672/51984833-48d50780-24d7-11e9-891c-fdac2e48fbca.png)

**Comment by xgqfrms** [comment]
> In the meantime I think you can press the mouse wheel down to close tabs.

Yeah, it works. But it still exist another bug, the counter is auto plus when I press mouse wheel down to close one tab, it should counter from 1.

![image](https://user-images.githubusercontent.com/7291672/51985041-dca6d380-24d7-11e9-8d84-b6783db2d78d.png)

**Comment by ccordoba12** [comment]
> so, I have to waiting for spyder 4 upgrade.

Sorry, we're focusing all our energies to get it out as soon as possible.

> But it still exist another bug

That's not a bug, it's just how it works.

**Comment by xgqfrms** [comment]
Anyway, thanks for your time!

**Comment by ccordoba12** [comment]
> so, I have to waiting for spyder 4 upgrade.

Ok, I decided to backport the pull request that added close buttons to our tabs in macOS because you're right, this is a pretty major usability issue.

It'll be available since our 3.3.3 version, to be released this weekend.
