### ISSUE TITLE
Please support IPython 8

### ISSUE THREAD

**Issue by stefaneidelloth** [spyder-ide/spyder#18117]
`spyder 5.3.1 requires ipython<8.0.0,>=7.31.1, but you have ipython 8.4.0 which is incompatible.`

**Comment by ccordoba12** [comment]
Hey @stefaneidelloth, thanks for reporting. For now, the only solution to the problem you posted above is to install the right IPython version to work with Spyder. We'll try to fix this in our next version (5.3.2), to be released in July.

However, as far as I can tell, there's very little gain for Spyder in IPython 8+, so if we're busy with other things, we'll leave that for 5.3.3.
