### ISSUE TITLE
A problem caused by Windows Chinese name account

### ISSUE THREAD

**Issue by yang-yuyan** [spyder-ide/spyder#18131]
## Problem Description
Spyder flashes back after opening the graphical main interface. I did some troubleshooting and found that it could be a problem caused by a Windows Chinese name account name. 

### What steps reproduce the problem?

1. Launch Spyder(5.3.1, in spyder-env) under my Chinese name account and it will flash back when loading the main interface.
2. Switch to the English name account, Spyder starts normally.
3. But under Chinese name account, I can normally launch spyder(5.1.5) in the base environment.

There are some version differences between the two environments.

## Versions(spyder-env)

* Spyder version: 5.3.1
* Python version: 3.9.13
* Qt-main version: 5.15.3
* qt-webengine version: 5.15.4
* PyQt version: 5.15.4
* pyzmq version: 20.0.0
* Operating System name/version: Windows 10

## Versions(base)

* Spyder version: 5.1.5
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt version: 5.9.2
* pyzmq version: 19.0.2
* Operating System name/version: Windows 10

The same problem also occurred in the base environment of spyder 5.1.5 version, but after downgrading pyzmq to 19.0.2, it is normal.
Could you help me? :(

**Comment by ccordoba12** [comment]
Hey @yang-yuyan, thanks for reporting. Please log into your Chinese account, open the Anaconda Prompt and run the following command there:

    spyder --debug-info verbose --debug-output file

That should generate a file called `spyder-debug.log` in the directory where you ran that command. Please upload it here to take a look at the error that makes Spyder crash in your case.

**Comment by yang-yuyan** [comment]
Thanks for the reply! There are some Chinese characters in the documentation because I set the spyder language to Chinese. Hopefully this won't cause you too much trouble.~
[spyder-debug.log](https://github.com/spyder-ide/spyder/files/8850062/spyder-debug.log)

**Comment by ccordoba12** [comment]
Closing due to lack of response.
