### ISSUE TITLE
ZMQ Kernel crash

### ISSUE THREAD

**Issue by sheldonrb** [spyder-ide/spyder#18170]
Spyder refuses to execute a working program. Updated conda from conda-forge on 6-6-2022. Restarting kernel produces crash:

 ERROR:traitlets:Operation not supported

first errors in chain:
File "/home/anaconda3/envs/p309/lib/python3.9/site-packages/jupyter_client/connect.py", line 605, in _create_connected_socket
    sock = self.context.socket(socket_type)
  File "/home/anaconda3/envs/p309/lib/python3.9/site-packages/zmq/sugar/context.py", line 262, in socket
    raise ZMQError(ENOTSUP)
 zmq.error.ZMQError: Operation not supported

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by sheldonrb** [comment]
Carlos,

 I do daily updates on my Python environment, and after a week of spyder not connecting to the kernel, this Monday the update (python? jupyter-client?) fixed the problem. Then on Wednesday, the update broke it again. Then on Thursday, the update (traitlets?) fixed my 3.10 spyder environment, but broke 3.9. I keep one antique non-updated environment to do my programming work, but watch the kernel connection come and go as Python updates roll in from conda-forge. I do a simple 1+1= command in the kernel to see if it is connected, because when it is disconnected it never comes back, and a "reset kernel" command causes a crash involving ZMQ called by jupyter-client. Our IT manager says he has a policy of waiting a month before updating with month-old packages, intentionally avoiding the bleeding edge. Seems like good advice. I realize that spyder and python are volunteer organizations, but it would be nice if they instituted better quality control.

  -yours
Rob
________________________________
