### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by yewen18** [spyder-ide/spyder#18186]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder was working fine until yesterday when I opened it and got an error. 

### What steps reproduce the problem?

1. Open spyder
2. 
3. 

### What is the expected output? What do you see instead?
Not working properly with Spyder

### Paste Traceback/Error Below (if applicable)

```python-traceback

An error ocurred while starting the kernel
The error is:

Traceback (most recent call last):
File "D:\Users\yewen\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole\plugin.py", line 1568, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle,
File "D:\Users\yewen\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 337, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "D:\Users\yewen\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 286, in pre_start_kernel
self.write_connection_file()
File "D:\Users\yewen\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 466, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "D:\Users\yewen\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 136, in write_connection_file
with secure_write(fname) as f:
File "D:\Users\yewen\Anaconda3\lib\contextlib.py", line 119, in __enter__
return next(self.gen)
File "D:\Users\yewen\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 893, in secure_write
win32_restrict_file_to_user(fname)
File "D:\Users\yewen\Anaconda3\lib\site‑packages\jupyter_core\paths.py", line 446, in win32_restrict_file_to_user
sd = win32security.GetFileSecurity(fname, win32security.DACL_SECURITY_INFORMATION)
pywintypes.error: (50, 'GetFileSecurity', 'Die Anforderung wird nicht unterstützt.')

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.12 64-bit
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.3.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)

```

**Comment by steff456** [comment]
Hi @yewen18,

I wanted to know how are you installing Spyder? Are you using the windows installers or are you trying with conda? Please let me know in the case you are using conda if you are using the defaults channel or the conda forge channel.

**Comment by yewen18** [comment]
> Hi @yewen18,
> 
> I wanted to know how are you installing Spyder? Are you using the windows installers or are you trying with conda? Please let me know in the case you are using conda if you are using the defaults channel or the conda forge channel.

hi @steff456,
I installed spyder via anaconda. After installing anaconda, spyder is already showing installed in the main page.

**Comment by yewen18** [comment]
@steff456 Will this error still be resolved?

**Comment by steff456** [comment]
@yewen18 ,the new environment where you are trying to install spyder-kernels uses Python 3.10? Also, why are you removing the python folder from the appdata folder?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
