### ISSUE TITLE
Spyder suddenly can't open it

### ISSUE THREAD

**Issue by nihaoyaya1** [spyder-ide/spyder#18200]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
conda update anaconda
conda update all
conda update spyder

**Comment by dalthviz** [comment]
Hi @nihaoyaya1 usually doing a `conda update all` can break your Spyder installation and often your whole Anaconda installation. I would suggest for you to try to create a new conda env using conda-forge packages For that you can run from an anaconda prompt something like:

        conda create -n spyder-cf -c conda-forge spyder jupyter_client=7.3.1
        conda activate spyder-cf
        spyder

If that doesn't work, I'm afraid that reinstalling the anaconda distribution probably will be needed :/

Also, just in case, you can use our standalone installers if you are on Windows or MacOS available here: https://github.com/spyder-ide/spyder/releases

There is not much we can do over the Spyder side but let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
