### ISSUE TITLE
error en la terminal Ipython "conecting to kernel"

### ISSUE THREAD

**Issue by ztrg** [spyder-ide/spyder#18212]
* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
firstly I'm new i'm taking a programing course and i need to solve this problem

 briefly I think I am not the only one with this problem, previously report a problem with the function or reserved word "input", when reporting it, a "spyder bot" send me to install a new version of both anaconda and spyder, and then I did it, in theory everything went well, until I enter to the new spyder and the terminal does not work,  is all the time " conecting to kernel " and then I already followed all the solutions given in the " issue report checklist " and search for solutions and nothing so i came here again

### What steps reproduce the problem?

1. entering
2. console says "conecting to kernel"
3.  I can edit but I can't run my program

### What is the expected output? What do you see instead?

I see nothing

### Paste Traceback/Error Below (if applicable)

not applicable

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.1
* Python version:  3.10.4
* Qt version:  don't know
* PyQt version:  niether
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ztrg** [comment]
how do i downgrade jupiter_client well what is jupiter_client

**Comment by dalthviz** [comment]
To downgrade jupyter_client (which is a dependency of the spyder-kernels package, the one that handles the console kernel creation) run from an Anaconda prompt with the env you created, following the bot comment activated, this: `conda install -c conda-forge jupyter_client=7.3.1`

**Comment by ztrg** [comment]
me aparece esto

(base) C:\Users\Familia> conda install -c conda-forge jupyter_client=7.3.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |

y sigue cargando

**Comment by dalthviz** [comment]
Activa primero el ambiente que creaste con:

    conda activate spyder-cf

Luego corre el comando para instalar la versión de `jupyter_client`

**Comment by ztrg** [comment]
ok

**Comment by ztrg** [comment]
me aparece esto
  ==> WARNING: A newer version of conda exists. <==
  current version: 4.12.0
  latest version: 4.13.0

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\Familia\anaconda3\envs\spyder-cf

  added / updated specs:
    - jupyter_client=7.3.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jupyter_client-7.3.1       |     pyhd8ed1ab_0          90 KB  conda-forge
    ------------------------------------------------------------
                                           Total:          90 KB

The following packages will be DOWNGRADED:

  jupyter_client                         7.3.3-pyhd8ed1ab_0 --> 7.3.1-pyhd8ed1ab_0


Proceed ([y]/n)?


que debo de hacer lo actualizo o le pongo proceder

**Comment by dalthviz** [comment]
Procede :+1:

**Comment by ztrg** [comment]
oh muchas gracias
si funciono

**Comment by dalthviz** [comment]
Listo :+1: voy a cerrar entonces este issue como un duplicado de #18174
