### ISSUE TITLE
can not use matplotlib and dont know why : ModuleNotFoundError: No module named 'matplotlib

### ISSUE THREAD

**Issue by jayrielle** [spyder-ide/spyder#18220]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Is there a way to install the matplotlib package in side spyder without using anaconda. The spyder app inside of anaconda has not been working for me so i downloaded spyder by itself and have been using that. But now im not sure is spyder has a command prompt to let me download the package

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
Your Python environment or installation doesn't have the matplotlib module installed or it occurred a problem importing it. Due to that, it is not possible for Spyder to create this special console for you.

### Paste Traceback/Error Below (if applicable)

  import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

```python-traceback

PASTE TRACEBACK HERE
if PY2:
    TimeoutError = RuntimeError
    FileNotFoundError = IOError
else:
    TimeoutError = TimeoutError
    FileNotFoundError = FileNotFoundError

if PY2:
    import re
    import tokenize
    def isidentifier(string):
        """Check if string can be a variable name."""
        return re.match(tokenize.Name + r'\Z', string) is not None

    if os.name == 'nt':
        def encode(u):
            """Try encoding with utf8."""
            if isinstance(u, unicode):
                return u.encode('utf8', 'replace')
            return u
    else:
        def encode(u):
            """Try encoding with file system encoding."""
            if isinstance(u, unicode):
                return u.encode(sys.getfilesystemencoding())
            return u
else:
    def isidentifier(string):
        """Check if string can be a variable name."""
        return string.isidentifier()

    def encode(u):
        """Encoding is not a problem in python 3."""
        return u


def compat_exec(code, globals, locals):
    # Wrap exec in a function
    exec(code, globals, locals)


if __name__ == '__main__':
    pass

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by andfoy** [comment]
Hi @jayrielle, thanks for opening this issue, I'll redirect you with @dalthviz and @mrclary, which have more information about our installers.

**Comment by dalthviz** [comment]
Hi @jayrielle , what version of Spyder are you using and from where you did the installation?

Currently, there are two version of the Windows/MacOS installers. One is the `full` one (which comes with a couple of libraries preinstalled like `matplotlib` and other optional dependencies) and one `lite` (which only comes with Spyder). Either way you can use specific packages than the ones available in the installers using the custom interpreter preference. For more info on that you can check our docs: https://docs.spyder-ide.org/current/faq.html#using-packages-installer

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
