### ISSUE TITLE
Problem with the input function

### ISSUE THREAD

**Issue by Apmelqui** [spyder-ide/spyder#18249]
### What steps will reproduce the problem?

I just installed Anaconda, oppened Spyder and a simple input function like m = input("Please, enter first number: ") do not work.

I also can't install scikit-learn on another created environment.

An suggestion to solve this issue?

Thank you very much.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\apmel\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\apmel\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\apmel\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\apmel\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by Apmelqui** [comment]
I've tried that, but then I get the following message while restarting the kernel:

An error ocurred while starting the kernel
The Python environment or installation whose interpreter is located at
    C:\Users\apmel\miniconda3\envs\adriano‑env\python.exe
doesn't have the spyder‑kernels module or the right version of it installed (>= 2.3.0 and < 2.4.0). Without this module is not possible for Spyder to create a console for you.

You can install it by activating your environment (if necessary) and then running in a system terminal:
    conda install spyder‑kernels=2.3
or
    pip install spyder‑kernels==2.3.*

___________________
But when I type conda install spyder‑kernels=2.3, I get the following message:

(adriano-env) C:\Users\apmel>conda install spyder‑kernels=2.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder-kernels=2.3

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

__________________________
Then, going to this page: https://anaconda.org/conda-forge/spyder-kernels
and trying al those commands:
conda install -c conda-forge spyder-kernels
conda install -c conda-forge/label/broken spyder-kernels
conda install -c conda-forge/label/cf201901 spyder-kernels
conda install -c conda-forge/label/cf202003 spyder-kernels
conda install -c conda-forge/label/beta spyder-kernels

I get this message on Spyder terminal:
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython  -- An enhanced Interactive Python.
Cannot restart a kernel not started by Spyder
Cannot restart a kernel not started by Spyder
Cannot restart a kernel not started by Spyder
Cannot restart a kernel not started by Spyder
Cannot restart a kernel not started by Spyder

__________________

Please, what do I have to do to fix it?

Thank you so much.

**Comment by ccordoba12** [comment]
> I've tried that, but then I get the following message while restarting the kernel

I'm afraid you'll have to reinstall from conda-forge all packages you need for development in your spyder-cf environment, like this:

    conda activate spyder-cf
    conda install -c conda-forge pandas matplotlib scikit-learn

and other packages you need.

**Comment by Apmelqui** [comment]
Thank you ccordoba12!

I think it worked now.

I'm in my second year of software engineering.

Is it recommended to use the standalone version or the one with the Anaconda?

Thank you very much for your help.

**Comment by Apmelqui** [comment]
Thank you very much, Carlos.

It worked now.
