### ISSUE TITLE
Interactive plots and related features very slow

### ISSUE THREAD

**Issue by dinsmoro** [spyder-ide/spyder#18244]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Interactive plots and related features (UI, X/Y data for the cursor) are very slow (unusable). 

Issue only occurs with Matplotlib's pcolormesh when it is the top layer; if I layer a new axis over a pcolormesh and plot a line the UI and X/Y data pts work in real-time - though they aren't relevant for the pcolormesh plot. If I plot multiple pcolormesh plots the lag gets worse. A single plot is roughly usable with patience, multiple pcolormesh plots plotted at once is unusable.

The task manager shows a python process goes to 100% on 1 thread when the mouse is over the plots - when not interacting with them they drop to idle.

Was not always the case, but not sure what Spyder (and other related interactive plot packages) I had before I updated to the latest.

### What steps reproduce the problem?

1. Plot a pcolormesh plot

### What is the expected output? What do you see instead?

Smooth interactive plots.

## Versions

* Spyder version: 5.3.1 None
* Python version: 3.9.7 64-bit
* Qt version: 5.15.3
* PyQt5 version: 5.15.4
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.0 (OK)
keyring >=17.0.0              :  23.6.0 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.1 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  62.3.3 (OK)
sphinx >=0.6.6                :  5.0.1 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.20.3 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by rhkarls** [comment]
I'm not sure if this will help, but have you tried updating `matplotlib` to `3.5.2` (latest)? There was a PR included in that release (https://github.com/matplotlib/matplotlib/pull/22691) which solved some performance issues with cursor data and `pcolormesh`.

**Comment by ccordoba12** [comment]
Thanks for chiming in @rhkarls!

@dinsmoro, please update and let us know if it works for you.

**Comment by dinsmoro** [comment]
I was rolling with `matplotlib` `3.5.1` so updated to `3.5.2` via the forge and that did indeed fix it! Not a Spyder issue at all - thanks for pointing me to the fix!
