### ISSUE TITLE
failed matplotlib import

### ISSUE THREAD

**Issue by Mech-Mon** [spyder-ide/spyder#18259]
### What steps will reproduce the problem?

Tried to install matplotlib. Failed as above.
(venv) mon@rPi4:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
(venv)

Spyder 4.2.1
Python 3.9.2 32-bit | Qt 5.15.2 | PyQt5 5.15.2 | Linux 5.15.32-v7l+ 

tried:
https://numpy.org/devdocs/user/troubleshooting-importerror.html

sudo apt-get install libatlas-base-dev
pip3 uninstall numpy  # remove previously installed version
apt install python3-numpy

https://forums.raspberrypi.com/viewtopic.php?t=328451
sudo pip install virtualenv
virtualenv venv
source ./venv/bin/activate
pip install matplotlib
pip install rpi.gpio

### Traceback
```python-traceback
  File "/usr/lib/python3/dist-packages/traitlets/traitlets.py", line 535, in get
    value = obj._trait_values[self.name]
KeyError: 'banner'

During handling of the above exception, another exception occurred:

RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xd
```

## Versions

* Spyder version: 4.2.1 
* Python version: 3.9.2
* Qt version: 5.15.2
* PyQt5 version: 5.15.2
* Operating System: Linux 5.15.32-v7l+

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  4.0.0 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.0.2 (OK)
IPython >=7.6.0                 :  7.20.0 (OK)
jedi >=0.17.2                   :  0.18.0 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
keyring >=17.0.0                :  22.0.1 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
parso >=0.7.0                   :  0.8.1 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.8.0 (OK)
pygments >=2.0                  :  2.7.1 (OK)
pylint >=1.0                    :  2.7.2 (OK)
pyls >=0.36.2;<1.0.0            :  0.36.2 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.3.0             :  0.3.0 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  1.0.2 (OK)
qtconsole >=5.0.1               :  5.0.2 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
setuptools >=39.0.0             :  52.0.0 (OK)
sphinx >=0.6.6                  :  3.4.3 (OK)
spyder_kernels >=1.10.1;<1.11.0 :  1.10.2 (OK)
textdistance >=4.2.0            :  4.2.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  1.0.2 (OK)
xdg >=0.26                      :  0.27 (OK)
zmq >=17                        :  20.0.0 (OK)

# Optional:
cython >=0.21                   :  None (NOK)
matplotlib >=2.0.0              :  None (NOK)
numpy >=1.7                     :  1.19.5 (OK)
pandas >=1.1.1                  :  None (NOK)
scipy >=0.17.0                  :  None (NOK)
sympy >=0.7.3                   :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @Mech-Mon, thanks for reporting. You're mixing your Linux distro packages with the ones you installed in your virtualenv. Unfortunately, that's a really bad practice because these packages are compiled differently and that's the source of your problem.

I understand that you're doing this because you're using a RaspberryPI. However, the best you can is avoiding that altogether and use Conda instead.

For that, please download [Miniconda](https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-aarch64.sh), install it and afterwards run

    conda create -n my_env -c conda-forge spyder matplotlib
    conda activate my_env
    spyder

I think that's the best you can do to use both Spyder and Matplotlib in your computer.

**Comment by ccordoba12** [comment]
I'm going to close this because it's not a Spyder problem and we don't have time to give additional feedback other than what I already told you.

**Comment by Mech-Mon** [comment]
Thank you,I was aware of Anaconda, but not miniconda.

Regards,
Mon
