### ISSUE TITLE
Spyder Crashes When Starting ('module' object has no attribute 'randint')

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1827]
_From [henrie.j...@gmail.com](https://code.google.com/u/101009980078739936341/) on 2014-05-22T16:07:10Z_

What steps will reproduce the problem?

 1. Install WinPython 3.3.5.0 64-bit with Spyder
2. Use spyder normally for a few days
3. Open spyder.exe 

What is the expected output? What do you see instead?

 I expect to see the Spyder loading graphic and then have the program open.

Instead, a small command-prompt-style window flashes briefly, then closes, then nothing happens.  I was able to catch the text on the window with a screenshot.  It says:
Traceback (most recent call last):
  File "spyder", line 2, in \<module>
    from sypderlib import start_app
  File "C:\WinPython\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\site-pacages\spyderlib\start_app.py", line 8, in \<module>
    import random
  File "C:\WinPython\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\Scripts\random.py", line 2, in \<module>
    x = random.randint(1,10);
Attribute Error: 'module' object has no attribute 'randint' What version of the product are you using? On what operating system? I can't open Spyder to check the specific version, but it came with WinPython-64bit-3.3.5.0.

Windows 7 64-bit. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1827_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-23T11:29:53Z_

Maybe a dumb question, but did you somehow add a new module in your pythonpath called "random" ?

random is a standard python library, it may have been overriden somehow. It looks like a problem with WinPython rther than spyder.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-05-24T06:42:48Z_

To solve this problem please open a Windows terminal (i.e. cmd.exe) and run this command on it:

spyder --reset

then try to start Spyder again.

If this doesn't work, I think you'll have to ask in the WinPython mailing list about it.

**Comment by goanpeca** [comment]
No more feedback on this after a year?, I would say it is closable

**Comment by ccordoba12** [comment]
Yep, let's do it.
