### ISSUE TITLE
cant find what i want

### ISSUE THREAD

**Issue by gamerzacc0** [spyder-ide/spyder#18270]
### What steps will reproduce the problem?

i cant find terminal in spyder 5, i would want to get helped

**Comment by gamerzacc0** [comment]
Spyder-terminal sir, I did check it online and got the result, after doing
it as it says it is not in my panes section where it should be.

**Comment by ccordoba12** [comment]
You have two options to use Spyder-terminal:

1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder spyder-terminal
        conda activate spyder-cf
        spyder

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Ok, I assume things are working as expected for you now. So I'm going to close this issue.
