### ISSUE TITLE
Spyder Kernels2

### ISSUE THREAD

**Issue by DBozkurtian96** [spyder-ide/spyder#18307]
### What steps will reproduce the problem?

Installed Anaconda, clean. Says I have the wrong version of spiderkernels (2.3), is expecting a version between 2.1 and < 2.2.

Nothing has worked. I've spent several hours on this. Not able to debug anything. 

And I can't see anything in the variable explorer.

Finally, I can't stop the debugger. It just hangs after stopping it. Any help is appreciated!

**Comment by dalthviz** [comment]
Hi @DBozkurtian96 ! Please create a new env using the conda-forge channel to get the latest Spyder that uses spyder-kernels >= 2.3.1. For that you can run from an Anaconda prompt (if you are running from Windows) or a terminal:

```
conda create -n spyder-cf -c conda-forge spyder

```

If you use Windows or MacOS you can also try Spyder from our standalone installers available at our release page: https://github.com/spyder-ide/spyder/releases/latest

Let us know if something of the above helps!

**Comment by DBozkurtian96** [comment]
Thanks Daniel. In the meantime, I saw that I needed to upgrade to a newer
version of Spyder (conda install -c conda-forge spyder==5.2.2), since my
debugger wasn't working correctly (btw, this is true on *EVERY *machine I
installed the latest Anaconda on). So I'm in the middle of that now. If
that doesn't work, I'll try your suggestion.

Boz

**Comment by dalthviz** [comment]
Closing due to lack of response
