### ISSUE TITLE
Conda update makes a problem with Spyder

### ISSUE THREAD

**Issue by mimik003** [spyder-ide/spyder#18318]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Update of packages with conda console command lines makes a problem with Spyder

**Comment by andfoy** [comment]
Hi @mimik003, it seems that this issue does not contain neither the reproduction steps nor the environment information required to do an appropriate assessment of the situation. We invite you to fill the required information.
