### ISSUE TITLE
Input() problem

### ISSUE THREAD

**Issue by Hestio1** [spyder-ide/spyder#18319]
Hi everyone,

I have a problem with the input() function with Spyder, it doesn't work and it then blocks the program (I can write and click but when I try to launch code, even code that was working before now doesn't)
I tried with a simple x=input() but it doesn't work

I used the anaconda's 5.1.5 version of Spyder and then after uninstalling it I tried the standalone version 5.3 present on the website
But none seems to work with the input() function

Is there a way to fix this problem ? I really need to use this function.

Thanks in advance

**Comment by andfoy** [comment]
Hi @Hestio1, thanks for reaching out! Fortunately, this is a known problem which has many duplicates now, such as https://github.com/spyder-ide/spyder/issues/18317, we invite you to see the answers there regarding the resolution of this issue
