### ISSUE TITLE
Environment Update Not Working

### ISSUE THREAD

**Issue by PythonCodingGitHubUser** [spyder-ide/spyder#18324]
### What steps will reproduce the problem?

I can't update the python interpreter. In navigator, it says 5.1.5 but when I open Spyder, it shows 3.9. The problem with this is that the bot told me that I needed to update my Spyder to run 'opened' files. I wrote the files in IDLE and am trying to open them in Spyder. They won't even run and a traceback isn't given. All I get is 'Python encountered an internal error' at the top of an issue reporter

**Comment by andfoy** [comment]
Hi @PythonCodingGitHubUser, thanks for reaching out, could you please provide the traceback that is generated when you try to execute a file?

**Comment by PythonCodingGitHubUser** [comment]
There isn't any traceback, the file doesn't even run. I just get the issue reporter window. I was told by a bot that I had to update and I did but now I'm having a different problem.

**Comment by PythonCodingGitHubUser** [comment]
> There isn't any traceback, the file doesn't even run. I just get the issue reporter window. I was told by a bot that I had to update and I did but now I'm having a different problem.

I have the updated spyder and it shows 5.1.5 on the navigator but when I click on spyder and open it, it still shows 3.9. I've been on a wild goose chase trying to find out how to update my Interpreter or environment or whatever it's called for 2 hours but still nothing.

**Comment by PythonCodingGitHubUser** [comment]
@andfoy could you help me out with updating the interpreter?

**Comment by PythonCodingGitHubUser** [comment]
status:Awaiting Followup

**Comment by andfoy** [comment]
Are you using Anaconda defaults or conda-forge?

**Comment by PythonCodingGitHubUser** [comment]
I think it's defaults since I don't know what conda-forge is

**Comment by PythonCodingGitHubUser** [comment]
It's called Anaconda.Navigator

**Comment by andfoy** [comment]
Let's try this: 

1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
3. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:<br>`conda create -n spyder-cf -c conda-forge spyder jupyter_client=7.3.1`<br>`conda activate spyder-cf`<br>`spyder`

**Comment by andfoy** [comment]
Are you using Windows?

**Comment by andfoy** [comment]
Please try with the installer and let us know if it works for you

**Comment by PythonCodingGitHubUser** [comment]
> Let's try this:
> 
> 1. Use our Windows or Mac installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
> 2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:`conda create -n spyder-cf -c conda-forge spyder jupyter_client=7.3.1``conda activate spyder-cf``spyder`

I already did this three times. Also, I clicked on the 5.3.1 update and it gives me 5.1.5

**Comment by PythonCodingGitHubUser** [comment]
> Please try with the installer and let us know if it works for you

Do it again?

**Comment by PythonCodingGitHubUser** [comment]
also, for your second suggestion, it says packages not found

**Comment by andfoy** [comment]
Are you using this link? https://github.com/spyder-ide/spyder/releases/download/v5.3.1/Spyder.dmg

Could you please try uninstalling all your Spyder instances, including conda environments?

**Comment by PythonCodingGitHubUser** [comment]
I don't know what those are. Should I uninstall anaconda nav completely?

**Comment by PythonCodingGitHubUser** [comment]
and yes i'm using that link

**Comment by PythonCodingGitHubUser** [comment]
then reinstall?

**Comment by andfoy** [comment]
Yes, please install Spyder using the installer and Anaconda without Spyder

**Comment by PythonCodingGitHubUser** [comment]
> Yes, please install Spyder using the installer and Anaconda without Spyder

what do you mean by "and anaconda without spyder"?

**Comment by PythonCodingGitHubUser** [comment]
also, I'm using the link you sent to install spyder. Not anaconda. Is that right?

**Comment by PythonCodingGitHubUser** [comment]
I just installed spyder

**Comment by andfoy** [comment]
> also, I'm using the link you sent to install spyder. Not anaconda. Is that right?

Yes, that is to install Spyder and to ensure that conda packages do not interfere with it. 

> what do you mean by "and anaconda without spyder"?

Reinstalling your Anaconda distribution: https://docs.conda.io/en/latest/miniconda.html

**Comment by PythonCodingGitHubUser** [comment]
One sec, I just noticed something. when I get the install pop=up, it says spyder-5.3.1 and py-3.9.5
that's my problem right there. Internal is still on 3.9

**Comment by PythonCodingGitHubUser** [comment]
...and you want me to install this right?


Miniconda3 macOS Intel x86 64-bit bash
--


[Miniconda3 macOS Intel x86 64-bit bash](https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-MacOSX-x86_64.sh)

**Comment by PythonCodingGitHubUser** [comment]
@andfoy I have installed spyder. is there a next step?

**Comment by PythonCodingGitHubUser** [comment]
it works now

**Comment by PythonCodingGitHubUser** [comment]
can i download anaconda again?

**Comment by andfoy** [comment]
> can i download anaconda again?

Yes, just make sure not to install Spyder from anaconda
