### ISSUE TITLE
Errors when debugging with remote kernel

### ISSUE THREAD

**Issue by shankyemcee** [spyder-ide/spyder#18330]
Hi,

I am working on a similar problem as this post(https://github.com/spyder-ide/spyder/issues/3587#issue-184727853) and all the comments are helpful. But for my use case I would like to debug my python script locally with a python kernel hosted on a cloud server, and I get similar issues:

This command failed to be executed because an error occurred while trying to get the file code from Spyder's editor. The error was:

An exception has occurred, use %tb to see the full traceback.

OSError: [Errno 22] Invalid argument: '....'

For reference, I am using windows with spyder 5.3.1 and I am connecting to a remote linux kernel having python 3.7. The steps I followed to set it up using Mobaxterm:

login to your remote server, create your python environment there and start your python kernel using the following line:
python -m spyder_kernels.console --ip=127.0.0.1 -f=./remotemachine.json
(Note: ip address should can also be localhost)

Open another local terminal in mobaxterm and enter:
ssh -L ::<control-port from remotemachine.json @

Copy the generated remotemachine.json file to your local system, open spyder, click on connect to existing kernel:
enter the remotemachine.json path in Connection File,
in hostname put the ,
in username enter the for your cloud server,
in port put 22(default ssh port on mobaxterm),
and enter the password for remote server login.

And it should connect then. After these steps I am able to send simple command line functions, but not able to debug the file. Is there any new support added for this already?

Thanks.

**Comment by dalthviz** [comment]
Hi @shankyemcee thank you for the feedback! I think this is not possible at the moment :/ but maybe @ccordoba12 or @impact27 could have some ideas?

**Comment by impact27** [comment]
It should work now as you describe, but you have to make sure the version of spyder-kernels matches the version on spyder. I am working on a pr to use the control channel for debugging which should be more reliable, but because this won’t work with python 2.7, it won’t be available before spyder 6. Can you confirm the version on spyder you are using and the version of spyder-kernels on the remote server?

**Comment by shankyemcee** [comment]
I am using spyder 5.3.1 on my system and spyder_kernels 2.3.1 on both the remote server and my own system. To me the error looks like its trying to look for the file in the remote system, but I am trying to debug it on my own system. Basically I just want to use the compute resources and packages on the remote server, but all file access and debugging should happen on my own system.

**Comment by impact27** [comment]
Si the way it works is that spyder sends the content of the editor to the remote kerne. I’ll have a look to see if I can reproduce

**Comment by ccordoba12** [comment]
@shankyemcee, you posted above:

> An exception has occurred, use %tb to see the full traceback.

Please write %tb in the IPython console and post the contents shown afterwards here so we can take a look at them.

**Comment by shankyemcee** [comment]
Output of %tb:

Traceback (most recent call last):

  File "/project/6027213/shankar5/envs/lit/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py", line 512, in get_file_code
    file_code = frontend_request(blocking=True).get_file_code(

  File "/project/6027213/shankar5/envs/lit/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 557, in __call__
    return self._comms_wrapper._get_call_return_value(

  File "/project/6027213/shankar5/envs/lit/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 440, in _get_call_return_value
    return self._sync_error(reply['value'])

  File "/project/6027213/shankar5/envs/lit/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 496, in _sync_error
    error_wrapper.raise_error()

  File "/project/6027213/shankar5/envs/lit/lib/python3.8/site-packages/spyder_kernels/comms/commbase.py", line 90, in raise_error
    raise self.etype(self)

OSError: [Errno 22] Invalid argument: '/project/6027213/shankar5/envs/lit/C:/Users/Dell G7 User 2/Documents/PROJECTS/vision_transformer/vision_transformer/vit_jax/main.py'

Here '/project/6027213/shankar5/envs/lit/' is where I hosted the remote kernel and 'C:/Users/Dell G7 User 2/Documents/PROJECTS/vision_transformer/vision_transformer/vit_jax/main.py' is the file on my system I am trying to debug

**Comment by impact27** [comment]
When you press debug, what exactly appears in your console? do you have `debugfile("'/project/6027213/shankar5/envs/lit/C:/Users/Dell G7 User 2/Documents/PROJECTS/vision_transformer/vision_transformer/vit_jax/main.py'", ...)`?

**Comment by impact27** [comment]
I have tried:
 - install spyder-kernels 2.3.1 on a remote machine
 - install spyder 5.3.1 on my machine
 - launch spyder-kernels with `python3 -m spyder_kernels.console`
 - copy the connection file at `/home/debian/.local/share/jupyter/runtime`
 - Connect on my local machine with "Connect to an existing kernel"
 - create a file on my desktop containing `print(0)` and a breakpoint
 - press debug on spyder

With that, the bebugging starts normally.

**Comment by impact27** [comment]
I think I found it, it is a problem of windows vs linux paths:

```
IPdb [5]: os.path.abspath("C:/Users")
Out  [5]: '/home/debian/spyder-kernels/C:/Users'
```

**Comment by impact27** [comment]
@shankyemcee Could you check if https://github.com/spyder-ide/spyder-kernels/pull/389 solves the issue?

**Comment by impact27** [comment]
On the remote machine:
`git clone https://github.com/spyder-ide/spyder-kernels.git`
`cd spyder-kernels`
`git fetch origin pull/389/head:remote_path_fix`
`git checkout remote_path_fix`
`pip install .`

**Comment by shankyemcee** [comment]
Hi,
 I followed your steps and re hosted the kernel from the remote server, but I am no longer able to connect my spyder ide to the Kernel on remote server.

**Comment by impact27** [comment]
That is strange, could you give me the steps you follow to launch and connect, and the exact error you see?

**Comment by shankyemcee** [comment]
Hi,

I refreshed the connections, and it appears to be working. But one problem is that I don't know which line is executing. For example here is the screenshot of when i used debugging with remote kernel:

![remote_kernel](https://user-images.githubusercontent.com/30503832/174857787-1dfecf6b-8dc8-4052-a66f-e96b2c8a784f.JPG)

and here is a screenshot with debugging in local kernel:

![image](https://user-images.githubusercontent.com/30503832/174857906-6f197527-722a-4658-8a08-688470020228.png)

The arrow is missing in remote kernel connection. Can this be added? Thanks.

**Comment by impact27** [comment]
spyder-ide/spyder-kernels#389 has been updated, can you try again?

**Comment by shankyemcee** [comment]
Thankyou, it's working brilliantly! Would this update be directly available through the next spyder_kernels release through conda or pip?

**Comment by impact27** [comment]
Yes it should if we have time to merge it, otherwise the next one

**Comment by shankyemcee** [comment]
Sounds good, Thanks a lot for all your help!

**Comment by ccordoba12** [comment]
We need this open so we don't forget to address it.
