### ISSUE TITLE
imported seaborn but still getting module not found

### ISSUE THREAD

**Issue by jayrielle** [spyder-ide/spyder#18342]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
can not import seaborn as sns

### What steps reproduce the problem?

1. import seaborn as sns 
2. run 
3. modulenotfound error

### What is the expected output? What do you see instead?
no error when importting

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

  File "C:\Program Files\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\jayri\untitled0.py", line 1, in <module>
    import seaborn as sns

ModuleNotFoundError: No module named 'seaborn'

```

## Versions

* Spyder version: 5.3.1
* Python version: 3.8.10 64 bit
* Qt version: 5.15.3
* PyQt version: 5.15.16
* Operating System name/version: Windows 10

Requirement already satisfied: seaborn in c:\programdata\miniconda3\lib\site-packages (0.11.2)
Requirement already satisfied: scipy>=1.0 in c:\programdata\miniconda3\lib\site-packages (from seaborn) (1.8.1)
Requirement already satisfied: numpy>=1.15 in c:\programdata\miniconda3\lib\site-packages (from seaborn) (1.22.4)
Requirement already satisfied: pandas>=0.23 in c:\programdata\miniconda3\lib\site-packages (from seaborn) (1.4.2)
Requirement already satisfied: matplotlib>=2.2 in c:\programdata\miniconda3\lib\site-packages (from seaborn) (3.5.2)
Requirement already satisfied: pillow>=6.2.0 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (9.1.1)
Requirement already satisfied: pyparsing>=2.2.1 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (3.0.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (1.4.3)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (4.33.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\miniconda3\lib\site-packages (from matplotlib>=2.2->seaborn) (0.11.0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\miniconda3\lib\site-packages (from pandas>=0.23->seaborn) (2022.1)
Requirement already satisfied: six>=1.5 in c:\programdata\miniconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=2.2->seaborn) (1.16.0)
### Dependencies

```
PASTE DEPENDENCIES HERE
```# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.1 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.9 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.3.2 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.1 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.8 (OK)
zmq >=22.1.0                         :  23.0.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.2 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)

**Comment by ccordoba12** [comment]
Hey @jayrielle, thanks for reporting. Did you follow the [instructions in our documentation](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) to connect our Windows installer with a Miniconda environment?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
