### ISSUE TITLE
ValueError: setting an array element with a sequence

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1838]
_From [paul.ver...@gmail.com](https://code.google.com/u/105561724810104387298/) on 2014-05-29T07:35:44Z_

Spyder Version:  2.3.0beta2
Python Version:  3.3.3
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.6.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
pylint >=0.25   :  1.0.0 (OK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1838_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-05-29T06:43:20Z_

Could you add more informations please ? Right now it is impossible to do anything with this bug report. The part "

What steps will reproduce the problem?

" is very important.

The little I understand from the title seems to indicate that the problem is not linked with spyder.

**Comment by goanpeca** [comment]
We should close this one @ccordoba12

**Comment by ccordoba12** [comment]
Yes.
