### ISSUE TITLE
Numpy 1.23.0 breaks autocompletion and makes the tests fail

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#18407]
With numpy 1.23 installed, autocompletion does not work in the editor for numpy (`np.` + `<tab>` doesn't do anything on my mac)

This causes the tests to fail, see:
https://github.com/spyder-ide/spyder/runs/7018273169?check_suite_focus=true
https://github.com/spyder-ide/spyder/runs/7018273253?check_suite_focus=true
https://github.com/spyder-ide/spyder/runs/7018273354?check_suite_focus=true

I can reproduce on my machine. The test pass with numpy 1.21 but fail with 1.23

**Comment by dalthviz** [comment]
Just in case this seems like an issue with Jedi: https://github.com/davidhalter/jedi/issues/1864
