### ISSUE TITLE
The link to download Spyder for win donwloads Spyder 3

### ISSUE THREAD

**Issue by michaelsheidaei** [spyder-ide/spyder#18429]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by michaelsheidaei** [comment]
https://github.com/spyder-ide/spyder/releases/tag/v5.3.1 the link downloads version 3 instead of 5.3.1

**Comment by ccordoba12** [comment]
Hey @michaelsheidaei, thanks for reporting. I don't understand what you mean. Could you post a screenshot of what you're seeing in your computer?

**Comment by michaelsheidaei** [comment]
its downloading version 3 

not the version 5.3.1

![image](https://user-images.githubusercontent.com/71117303/175568987-370fd79f-ae43-46cc-a7a9-0d68a893ef12.png)

**Comment by michaelsheidaei** [comment]
![image](https://user-images.githubusercontent.com/71117303/175569468-fe9e0a75-435c-422a-a49f-6a94c3f835e1.png)

**Comment by ccordoba12** [comment]
Hey @michaelsheidaei, that means that you have previously downloaded Spyder and your file downloader is renaming new downloads to not overwrite the previous ones.

**Comment by michaelsheidaei** [comment]
It installed spyder 3.1 on my laptop

**Comment by michaelsheidaei** [comment]
![image](https://user-images.githubusercontent.com/71117303/175815107-867166af-2501-4865-933f-1b7938d3534c.png)

**Comment by michaelsheidaei** [comment]
![image](https://user-images.githubusercontent.com/71117303/175815129-80764332-41bd-41c9-8820-5d8c58d98a2a.png)

**Comment by ccordoba12** [comment]
It seems you have an old Spyder installation. So, you need to find it and remove it. After that, you need to run the installer you downloaded before.

**Comment by michaelsheidaei** [comment]
Carlos, I am not being rude but do you even understand English? 

when I click the link on the Spyder website or on Git, instead of downloading version 5.X.X its downloading version 3.X.X
do you understand?  I sent the pictures to you to show you that there is something wrong and you keep insisting I am wrong.

Its downloading version 3.X.X and I installed it because its what it downloaded. Do you understand?

**Comment by michaelsheidaei** [comment]
Oh just to be clear, I am trying to install Windows version

**Comment by jitseniesen** [comment]
Windows is saving the link as `Spyder_64bit_full_3.exe` but that does not mean that it is Spyder 3. The file is called `Spyder_64bit_full.exe`, but presumably you already have a file of that name in the same folder, so Windows gives it a different name in order to preserve the file that you already have.

Spyder 3 was not released as an .exe file.

What Carlos says is that you have Spyder 3 installed at the moment. When you download the new file, it does not replace the existing Spyder 3. So you first need to remove your existing Spyder 3 installation and then run the installer.
