### ISSUE TITLE
Spyder console unresponsive after long running training tasks

### ISSUE THREAD

**Issue by mfruzan** [spyder-ide/spyder#18433]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by mfruzan** [comment]
I use Spyder 5.1.5 on windows 10 and connect to cloud ubuntu GPU instance via spyder_kernels 2.3.1, when i increase number of epochs in a deep learning model, when training finishes, Ipython console is un-responsive and i have to close the console and reopen existing console, is there anyway to fix this problem?
Many Thanks

**Comment by dalthviz** [comment]
Hi @mfruzan thank you for the feedback! Could you update Spyder on your local machine to see if that helps? For that, if you are using the Anaconda distribution, you will need to create a new env using the conda-forge channel. So from an Anaconda prompt run something like:

```
conda create -n spyder-cf -c conda-forge spyder
conda activate spyder-cf
spyder
```

To install Spyder 5.3.1 or the latest Spyder to test you can also donwload the standalone Windows installer at our release page: https://github.com/spyder-ide/spyder/releases/latest

Let us know if something of the above helps!

**Comment by mfruzan** [comment]
I installed Spyder 5.3.1, but problem still exists. Could it be related to a setting in windows 10 (powershell ssh.exe) that controls timeout? 
Many Thanks

**Comment by dalthviz** [comment]
Thanks for the info @mfruzan , then I'm not sure what could be happening, sorry :/ 

Pinging @ccordoba12 and @impact27 (maybe them have some other ideas in order to debug this)

**Comment by mfruzan** [comment]
We fixed the problem by updating ClientAliveInterval, TCPKeepAlive and ClientAliveCountMax at Linux server (where spyder_kernel is running. )

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. Closing then.
