### ISSUE TITLE
Console Problem

### ISSUE THREAD

**Issue by LnSHampton** [spyder-ide/spyder#18447]
### What steps will reproduce the problem?

You want the steps documented in 50 characters?   

## Versions

* Spyder version: 5.3.1 
* Python version: 3.10.4
* Qt version: 5.15.3
* PyQt5 version: 5.15.4
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.0 (OK)
keyring >=17.0.0              :  23.5.1 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.3.1 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.2 (OK)
sphinx >=0.6.6                :  5.0.1 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by LnSHampton** [comment]
Hello,
I had a problem running Spyder from within Anaconda weeks ago. I reported the issue and was given a fix by creating a separate Anaconda session that invoked Spyder. So far, so good.
Now, however, Spyder has a problem displaying output on the Console. I cannot duplicate it at will, unfortunately, but it occurs oftern.

For example, I have a series of Python statements such as these:

num_of_cards = int(input('Input the number of cards:\n'))
prompt = '> '

for n in range(1,num_of_cards+1):
    print(f'The term for card #{n}:')
    new_term = input(prompt)
    print(f'The definition for card #{n}:')
    new_defn = input(prompt)

When I run that code here is what displays on the console:

Input the number of cards:
3
The term for card #1:
> T1
The definition for card #1:
> D1
The term for card #2:
> T2
The definition for card #2:
> D2
The term for card #3:
> T3
The definition for card #3:> 

Amazingly the problem reproduced for me on the last line.

Notice the last prompt and that the '>' followed the colon ':' rather than appear on a NEW LINE as it did for the previous iterations.

This behavior does not always occur. It appears SPORATICALLT and is very annoying. 

Generally, I restart the Kernel and clear all variables, but that is no guarantee the problem will not reappear.

**Comment by ccordoba12** [comment]
Hey @LnSHampton, thanks for reporting. To fix that problem, please see this comment: https://github.com/spyder-ide/spyder/issues/17710#issuecomment-1147657707

To update qtconsole you need to close Spyder, open the Anaconda prompt and run there:

    conda activate spyder-cf
    conda install -c conda-forge qtconsole=5.3.1
