### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by SutodaIbraham** [spyder-ide/spyder#18465]
### What steps will reproduce the problem?

i'll wirte a django application
but as i run views.py, i get the error  'Module not found'
it means the class in my models.py
the model.py is saved on same path with views .py

**Comment by steff456** [comment]
Hi @SutodaIbraham,

Please give me the information on what platform are you running Spyder, what version are you using and method of installation. Also, please provide me with an example and an explanation on what error message are you seeing in Spyder.

Thanks for reporting!

**Comment by Mte90** [comment]
It is using django so he can't run the file views.py but need to run the django server to execute the code, probably this is the reason about it as from that file can't find the app itself.

**Comment by ccordoba12** [comment]
Thanks for the insight @Mte90! Hopefully this will help the original poster and other people that find this error.

For now I'm going to close this issue since it's quite old.
