### ISSUE TITLE
How to use already installed modules and environments with Spyder on Windows?

### ISSUE THREAD

**Issue by haravena** [spyder-ide/spyder#18480]
### What steps will reproduce the problem?

pip list
Note: you may need to restart the kernel to use updated packages.
C:\Program Files\Spyder\Python\python.exe: No module named pip

I have just installed Spyder 5.3.1, but it seems I have missing all the moduled installed...I do not know how to run again ...could be posible to return to the previous version ?

## Versions

* Spyder version: 5.3.1 
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.1 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.9 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.3.2 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.1 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.8 (OK)
zmq >=22.1.0                         :  23.0.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.2 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by dalthviz** [comment]
Hi @haravena thank you for the feedback! Seems like you are using Spyder from the standalone installer version on Windows. The installer doesn't come with `pip` so to install or use packages already installed in a python environment you will need to use the custom interpreter preference. For more details about how to achieve that you can check the FAQ page entries on our documentation: https://docs.spyder-ide.org/current/faq.html#using-existing-environment https://docs.spyder-ide.org/current/faq.html#using-packages-installer and 

Let us know if that helps!

**Comment by dalthviz** [comment]
@haravena seems like you attached an image. However, you will need to directly post it at https://github.com/spyder-ide/spyder/issues/18480 (email attachments get lost in the GitHub interface). Thanks!

Also, just in case the path to put is the one pointing to the Python executable (`python.exe`) that has access to your packages. However, after we get the image or path you are trying maybe we could check was is happening in your case

**Comment by haravena** [comment]
Ok I See Daniel

I have put this path:
C:/Users/harav/anaconda3/pythonw.exe

I get this message from the Terminal:
"No es posible reiniciar un núcleo que no fue iniciado por Spyder"

Thanks

**Comment by haravena** [comment]
Thanks Daniel,

Unfortunately it is not working for me.

!An error occurred while starting the kernel
The following argument was not expected:
C:/Users/harav/anaconda3/envs/spyder‑packages
Run with ‑‑help for more information."

What can I do ?...uninstall everything and start with an older version of
Spyder mayb could help?

**Comment by dalthviz** [comment]
I would then suggest as you say to try to uninstall the standalone Spyder installation and install it again. Also, from where did you downladed that version?

Another approach could be to directly install spyder in the new env that was created. For that, from an Anaconda prompt, run something like this:

```
conda activate spyder-packages
conda install -c conda-forge spyder
spyder
```

With that you will install and launch Spyder from the created env

**Comment by haravena** [comment]
I have downloaded from https://github.com/spyder-ide/spyder/releases

**Comment by dalthviz** [comment]
No problem @haravena , glad to hear that now Spyder is working for you :+1:

Regarding the error running your code, what version of `yfinance` are you using? The latest one from what I can see is 0.1.72. Maybe you need to update it? Also, there is an issue about `json.decoder.JSONDecodeError` here: https://github.com/ranaroussi/yfinance/issues/764#issue-941000623 (I guess you need to install at least `yfinance` 0.1.62 to prevent decoding errors).

**Comment by dalthviz** [comment]
Awesome, glad everything is working now for you :+1: 

I will close this issue then but if you have any other questions or comments regarding Spyder let us know!

**Comment by haravena** [comment]
Sure!, thanks again!
