### ISSUE TITLE
Unknown Problem

### ISSUE THREAD

**Issue by ellbatman** [spyder-ide/spyder#18515]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

I opened up spyder and then the issue window popped up. Not sure what happened.

**Comment by ccordoba12** [comment]
Hey @ellbatman, thanks for reporting. Please post the error you're seeing here.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
