### ISSUE TITLE
Cannot launch Spyder from Anaconda (New)

### ISSUE THREAD

**Issue by thomastskng** [spyder-ide/spyder#18525]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I cannot launch Spyder from latest version of Anaconda.  Also tried uninstall and re-install Anaconda at least 5 times. Still seeing the same application launch error. 

Also followed this [https://github.com/spyder-ide/spyder/issues/15438](url) . Tried `spyder --reset` and also 
`conda update anaconda`
`conda install spyder=5.1.5`

Still getting the same application launch error. 

### What steps reproduce the problem?

1. Installed latest version Anaconda3-2022.05-Windows-x86_64.exe
2. Launch Anaconda Navigator
3. Launch Spyder 5.1.5

### What is the expected output? What do you see instead?
Expected to be open Spyder but see Application Launch Error:

Application spyder launch may have produced errors
Exit code: 1

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Application spyder launch may have produced errors
Exit code: 1
```

## Versions

* Spyder version: 5.1.5
* Python version: 3.9.12
* Qt version: 
* PyQt version: 
* Operating System name/version: Window 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @thomastskng, thanks for reporting. Unfortunately, Spyder is broken or semi-broken in Anaconda 2022.05. We informed already to the Anaconda team about that serious problem, but nothing has happened so far.

So, foe now you have two options to keep using Spyder:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by thomastskng** [comment]
a

**Comment by thomastskng** [comment]
hi @ccordoba12 , sorry for delayed reply. Which is the recommended way for installing Spyder, 1) via anaconda or 2) window standalone installer ? Because i used option 2 (window standalone installation) before and ran into an issue whereby I cannot double click and open up the dataframe in variable explorer within spyder and i was advised to install spyder via anaconda. 

Second question: for your step 2 above, what is the purpose of Create a new environment with conda-forge packages ? 
Thrid question: I am confused because you asked me to install the window standalone spyder and then open the Anaconda Prompt and run the following commands above. So, I shall install both the window standalone spyder PLUS anaconda ?
