### ISSUE TITLE
my spyder crashed

### ISSUE THREAD

**Issue by Wendyyyy70** [spyder-ide/spyder#18568]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
 i want to run a file and it crashed and i cannot open it any more but i upgrade the version  andthen i couldopen it but it stll connecting to kernel, i dont know what todo next

**Comment by dalthviz** [comment]
Closing due to lack of response
