### ISSUE TITLE
import cv2 in debug mode error

### ISSUE THREAD

**Issue by AlexWang1900** [spyder-ide/spyder#18581]
### What steps will reproduce the problem?

debug a script with a line:
import cv2

ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation

but running it is fine

## Versions

* Spyder version: 5.3.1 
* Python version: 3.9.7
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.15.0-40-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=3.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.23.0 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by andfoy** [comment]
Hi @AlexWang1900, thanks for reaching out, could you please provide more information about how did you installed both Spyder and OpenCV?

**Comment by AlexWang1900** [comment]
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi

I install spyder using: conda install spyder = 5.3.1
I install opencv-python using :pip install opencv-python

**Comment by andfoy** [comment]
Hi @AlexWang1900, thanks for the reply, it seems that this is indeed an issue, given that https://github.com/spyder-ide/spyder/issues/18638 also reports it, let me try to reproduce it

**Comment by andfoy** [comment]
I can reproduce this issue on my local setup. I'm invoking @impact27 since he might have a better understanding about this?

![imagen](https://user-images.githubusercontent.com/1878982/178596548-fdc96cea-bfa1-4d0d-a784-656f24bef5aa.png)

**Comment by impact27** [comment]
I can reproduce. a workaround is: `pip install "opencv-python<4.6" `
