### ISSUE TITLE
Spyder fails to launch from linux substyem using conda:     match = self._regex.search(version) TypeError: expected string or bytes-like object  

### ISSUE THREAD

**Issue by enrico1193** [spyder-ide/spyder#18596]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Error when trying to open spyder from linux subsystem 

### What steps reproduce the problem?

1. open linux terminal with conda env
2. digit "spyder"'
3. error in launching the app  

### What is the expected output? What do you see instead?
Spyder opens

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last): 
File "/home/anfuso/miniconda3/bin/spyder", line 11, in <module>                                                           
sys.exit(main())                                                  
File "/home/anfuso/miniconda3/lib/python3.8/site-packages/spyder/app/start.py", line 223, in main                         
from spyder.app import mainwindow                                                                                     
File "/home/anfuso/miniconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 43, in <module> requirements.check_qt()                                        
File "/home/anfuso/miniconda3/lib/python3.8/site-packages/spyder/requirements.py", line 47, in check_qt                   
if parse_version(actual_ver) < parse_version(required_ver):                                                           
File "/home/anfuso/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 120, in parse_version          
return packaging.version.Version(v)                                                                                   
File "/home/anfuso/miniconda3/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/version.py", line 264, in __init__ 
match = self._regex.search(version)                                                                                 
TypeError: expected string or bytes-like object     
```

## Versions

* Spyder version: 5.0.5 (even with 5.1.5 is not working)
* Python version: 3.8.2
* Qt version: 5.12.9
* PyQt version: 5.12.3
* Operating System name/version: Ubuntu 20.04 LTS

### Dependencies

```
PASTE DEPENDENCIES HERE
```
```
see attachment for conda list
``` 
[conda-list.txt](https://github.com/spyder-ide/spyder/files/9076059/conda-list.txt)

**Comment by ccordoba12** [comment]
Hey @enrico1193, thanks for reporting. This error could be fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you need to create a new environment with conda-forge packages. For that, please close Spyder, open a terminal and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if that works for you.

**Comment by enrico1193** [comment]
Hi Carlos,
thanks for your fast reply. At the end I remove miniconda3 and install anaconda3 using the .sh file available in the anaconda website. Apparently it fixed the problem! Thanks!

Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Carlos Cordoba ***@***.***>
Inviato: Saturday, July 9, 2022 6:47:29 PM
A: spyder-ide/spyder ***@***.***>
Cc: enrico1193 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [spyder-ide/spyder] Spyder fails to launch from linux substyem using conda: match = self._regex.search(version) TypeError: expected string or bytes-like object (Issue #18596)


Hey @enrico1193<https://github.com/enrico1193>, thanks for reporting. This error could be fixed in our latest version (5.3.1).

Since it's still not available in Anaconda, you need to create a new environment with conda-forge packages. For that, please close Spyder, open a terminal and run the following commands there:

    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder


Let us know if that works for you.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by cliffordkleinsr** [comment]
do a pip install pip show pyqt5==5.12.3 then followed by pip install pyqtwebengine==5.12.1
5.12.1
