### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ayush595** [spyder-ide/spyder#18600]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
there are nothing error

**Comment by ccordoba12** [comment]
Hey @ayush595, thanks for reporting. It seems you're using a very old Spyder version. To use our latest one (5.3.1) you have two options:

1. Use our Windows or Mac installers, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder
