### ISSUE TITLE
openCV module not found

### ISSUE THREAD

**Issue by avijit-89** [spyder-ide/spyder#18638]
### What steps will reproduce the problem?

I am trying to run a simple program to access my webcam and capture an image. While I can access it from the terminal but I have got a lot of problems in Spyder to do so. I have tried installing the library with miniconda but then I get the kernel error.

## Versions

* Spyder version: 5.3.1 
* Python version: 3.9.5
* Qt version: 5.15.2
* PyQt5 version: 5.15.6
* Operating System: Darwin 21.5.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7            :  0.3.0 (OK)
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.5.1 (OK)
keyring >=17.0.0                     :  23.5.1 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.3.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0                       :  2.13.9 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.0 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  62.3.2 (OK)
sphinx >=0.6.6                       :  4.5.0 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.1 (OK)
textdistance >=4.2.0                 :  4.2.2 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.8 (OK)
zmq >=22.1.0                         :  23.0.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.2 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by steff456** [comment]
Hi @avijit-89,

How are you installing Spyder? In case you are installing via conda, do you have a dedicated environment for Spyder or are you installing everything you need in the same environment?

**Comment by andfoy** [comment]
I think this is related to https://github.com/spyder-ide/spyder/issues/18581

**Comment by avijit-89** [comment]
Hi @steff456 ,

Thanks for responding. 
I had first installed Spyder with dmg installer from the Spyder's [weblink](https://www.spyder-ide.org). Installed opencv via pip but it didn't work. Later, I installed openCV through miniconda, then anaconda but it didn't work. I also tried download the opencv module via pip but, it didn't work. 
Also, I had created an environment called spyder-env and activated it. OpenCV was installed via conda within this environment. I could see that in Anaconda navigator. But, I couldn't figure out what went wrong. I thought it might have to do with PYTHONPATH and version but nothing worked out well when I tried to select another version. And then I started getting this kernel error.

@andfoy - Thanks. It seems to be a bit different issue then mine. I am not debuggin. It's just not working.

**Comment by steff456** [comment]
Did you tried all of these options in the same environment?

**Comment by steff456** [comment]
Can you please try to create a new conda environment, and install everything you need using pip? Also, please install spyder-kernels as explained in this FAQ, https://docs.spyder-ide.org/current/faq.html#using-packages-installer so you can connect this environment to Spyder.

The steps for creating the new environment are:

```
conda create -n myenv-pip
conda activate myenv-pip
pip install opencv-python
```

Please don't forget that we don't recommend mixing pip with conda installing because it can result in damages on particularly complex dependencies. So in this new environment given that you need to install opencv using pip, please use only pip with all the other dependencies you may need.

Hope this helps with your issue!

**Comment by avijit-89** [comment]
@steff456 

I followed your commands. It still doesn't work. 
However, this time I did not get the kernel error but a warning was highlighted as mentioned below:

    
    import cv2
ModuleNotFoundError: No module named 'cv2'
**Warning
It seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.**

I don't know, is it because I am using macOS??

**Comment by avijit-89** [comment]
FInally, it worked after I uninstalled everything from miniconda, python3.9 and python related folders inside the framework folder except python 2.7 (which is macos default). 

Following would installed via the terminal
1. Installed Homebrew and cleanedup
2. Python3 - brew install python
3. created the python environment named pyenv inside a directory other than /opt and I made sure this time I install all packages within this
4. installed the numpy, opencv-python etc packages via pip
5. installed spyder via terminal - pip install spyder

Viola! It works fine as I wanted. 

Thanks for the support guys.

**Comment by Ildaron** [comment]
> FInally, it worked after I uninstalled everything from miniconda, python3.9 and python related folders inside the framework folder except python 2.7 (which is macos default).
> 
> Following would installed via the terminal
> 
> 1. Installed Homebrew and cleanedup
> 2. Python3 - brew install python
> 3. created the python environment named pyenv inside a directory other than /opt and I made sure this time I install all packages within this
> 4. installed the numpy, opencv-python etc packages via pip
> 5. installed spyder via terminal - pip install spyder
> 
> Viola! It works fine as I wanted.
> 
> Thanks for the support guys.

good job
