### ISSUE TITLE
New feature request

### ISSUE THREAD

**Issue by Ubaldo79** [spyder-ide/spyder#18645]
Perhaps it is something already existing and I don't know how to use them, but I was thinking to add the following feature.

Imagine that you are working on a certain area of your code (say around line 1000). 
Then you realize that the the changes you are doing affect the code elsewhere (say around line 500), but then you have to make another change around line 200. 

On your way back, you may have forgotten where you were, so it could be useful to add some sort of marker so you can easily find your way back. I am aware of Alt + arrows feature, which is handy, but having the opportunity of adding markers would be even better. 
At the moment I am using the debuggers "red dots" to mark where I was. 
By adding a debugger point, I have a cyan mark on the scroll window, that help me to remember where I was. 
The problem is that the debugger dots disappear on save along with the cyan markers. 

![image](https://user-images.githubusercontent.com/10845685/178594730-b9aed05b-74d4-4c15-99ba-5df63849bb6c.png)

**Comment by ccordoba12** [comment]
Hey @Ubaldo79, thanks for reporting. I think what you want if a bookmarks functionality in Spyder.

That's already reported on issue #910. We'll try to implement it in the future.
