### ISSUE TITLE
OK, now help() works,  but matplotlib cannot be found even though it shows up in help() modules.  Here is the error message:

### ISSUE THREAD

**Issue by tlmurd64** [spyder-ide/spyder#18678]
OK, now help() works,  but matplotlib cannot be found even though it shows up in help() modules.  Here is the error message:
File "C:\Users\tlmur\.spyder-py3\solar_system_3d.py", line 9, in <module>
    import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

_Originally posted by @tlmurd64 in https://github.com/spyder-ide/spyder/issues/18659#issuecomment-1183787432_

**Comment by mmagnuski** [comment]
How did you install Spyder? Are you sure matplotlib is installed in the spyder environment or in the environment that Spyder is using (if it is not the same)?
If you installed Spyder via the standalone installer and want to install additional packages take a look at this: https://docs.spyder-ide.org/current/faq.html#using-packages-installer

If you created a separate conda environment for Spyder (like in the linked issue) and want to install matplotlib there you'd have to:
1. open the terminal
2. activate the conda env with spyder (for example `conda activate spyder-cf`)
3. install the desired package (fro example `conda install matplotlib`)

**Comment by dalthviz** [comment]
Closing due to lack of response
