### ISSUE TITLE
Crash: `f.write()` when `f` is open

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#18696]
If `file.py` is an open tab in Spyder, and we aren't currently focused on it, then

```python
with open('file.py', 'w') as f:
    f.write("stuff")
```
crashes Spyder 5.3.0 on Windows 10. Is this a known issue? If not, I'll try to give an MRE with the latest Spyder.

**Comment by impact27** [comment]
Maybe https://github.com/spyder-ide/spyder/issues/18520? Do you have more info about the crash?

**Comment by OverLordGoldDragon** [comment]
Unsure on #18520, but I couldn't consistently reproduce it, and how quickly I was tabbing inside of Spyder seemed to have something to do with it. The tabbing has also caused crashes other times. I notice that Spyder seems to be bothered by anything involving large bodies of text and them being edited or viewed quickly.

I'll reopen if I have steps to reproduce.
