### ISSUE TITLE
Figures can't show in spyder when the following message appeared: 

### ISSUE THREAD

**Issue by charitio-tam** [spyder-ide/spyder#18710]
The sysetm returns this messages: "Figures now render in the Plots pane by default. To make them also appear inline in the Console, uncheck "Mute Inline Plotting" under the Plots pane options menu."

![error](https://user-images.githubusercontent.com/94624111/179469012-916963bf-e56a-48cc-81f0-68913121a328.png)
Where is the "Mute Inline Plotting" located in spyder version 4.1.4 on windows 10 platform?
From the diagram=> fig, (ax1, ax2) = pyplot.subplots(1,2) : cannot plot the diagram in spyder, Please help! Thanks so much!

**Comment by ccordoba12** [comment]
Hey @charitio-tam, thanks for reporting. That option is available here:

![imagen](https://user-images.githubusercontent.com/365293/180012770-32db5e01-ce6b-4287-a478-b42969b432aa.png)
