### ISSUE TITLE
PIL module not working

### ISSUE THREAD

**Issue by saschazb** [spyder-ide/spyder#18725]
### What steps will reproduce the problem?

I updated Pillow 9.0.1 to Pillow 9.2.0 for another project and now I can't use plt.savefig() because AttributeError: module 'PIL' has no attribute 'Image'. I tried to add this line to my code because I saw that it could solve this kind of problem, but it didn't work: from PIL import Image.
My python version is 3.9.12, so from what I read, it should work with the Pillow version. Does somebody have an idea on how to solve my problem? Thank you!

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/commbase.py", line 340, in _handle_remote_call
    return_value = self._remote_callback(
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/frontendcomm.py", line 271, in _remote_callback
    return super(FrontendComm, self)._remote_callback(
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/commbase.py", line 353, in _remote_callback
    return self._remote_call_handlers[call_name](
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/console/kernel.py", line 165, in get_namespace_view
    view = make_remote_view(ns, settings, EXCLUDED_NAMES)
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py", line 672, in make_remote_view
    'type':  get_human_readable_type(value),
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py", line 523, in get_human_readable_type
    elif isinstance(item, PIL.Image.Image):
  File "/home/szbernier/anaconda3/lib/python3.9/site-packages/spyder_kernels/utils/lazymodules.py", line 55, in __getattr__
    return getattr(self.__spy_mod__, name)
AttributeError: module 'PIL' has no attribute 'Image'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.18.0-394.el8.x86_64

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @saschazb, thanks for reporting. What command did you use to update to Pillow 9.2.0?

**Comment by saschazb** [comment]
I used python3 -m pip install --upgrade Pillow. I solved the problem by downgrading the version of Pillow back to 9.0.1 by following the instructions on this page. https://stackoverflow.com/questions/5226311/installing-specific-package-version-with-pip

**Comment by ccordoba12** [comment]
> I used python3 -m pip install --upgrade Pillow

Ok, I imagined that. The thing is you can't mix pip and conda binary packages (like Pillow, Numpy or Pandas) because they are incompatible. And the error you posted above is a typical consequence of that (I tried to reproduce it on my end just with Conda packages and I was unable to).

> I solved the problem by downgrading the version of Pillow back to 9.0.1

Ok, for next time please don't use pip but instead create a new environment and install the packages that you need there along with spyder-kernels from Conda-forge, like this:

    conda create -n myenv -c conda-forge pillow spyder-kernels

Afterwards, you need to follow the instructions in our docs to connect Spyder to that environment:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
