### ISSUE TITLE
Unable to see dataframe value

### ISSUE THREAD

**Issue by mahmoodn** [spyder-ide/spyder#18737]
Hi
I have seen similar posts about not being able to see the value of a dataframe in the variable explorer. However, those belong to old versions of Pandas or Spyder. With the following specifications

Spyder 5.2.0
Pandas 1.4.2

I get this error `spyder was unable to retrieve the value of this variable from the console `

![image](https://user-images.githubusercontent.com/11626212/179808157-1e161662-2f00-4e74-a8ae-46fad626bd89.png)

Any idea about that?

**Comment by mahmoodn** [comment]
OK. I installed 5.3.2 from scratch and it is now fine. Closing the issue...

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
