### ISSUE TITLE
restart kernel unexpectedly on linux- fail with exception access violation on windows- when high number of iterations

### ISSUE THREAD

**Issue by angelinasyrri** [spyder-ide/spyder#18747]
Hi! I have been using spyder standalone (5.3.2) interface with python (3.10) both on my windows machine and also on my windows machine, with a similar setup. In both machines, I have encountered the same problem:
I am running an iterative calculation. For fewer samples everything seems to work fine, however, when I repeat the run for a higher number of samples, in my windows machine I get the following error (at the end of the text). 

At the beginning I thought that the issue might be related with Julia and Windows (I am using Julia 1.5.4 and running power flow calculations calling julia though this command :pp.timeseries.run_timeseries(net_flex, time_steps = range(0, n_timesteps_peak),run = pp.runpm_ac_opf,continue_on_divergence=True, delta=1e-16).
However, when I repeated the run on my Linux machine again the iteration stopped at around the 60% of the scheduled period again, without any error and the only message was 'restarting kernel'. 
Then I thought that it might be an issue with memory or something related to spyder since I saw some other issues with restarting the kernel after many iterations.

Any help would be more than welcome!!

Dependencies

# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.7.2 (OK)
keyring >=17.0.0                     :  23.6.0 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0;<3.0                  :  2.14.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  63.1.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.2;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.3.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)

ERROR that appears on my windows machine:
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x2d016c5 -- is_ir_node at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:493 [inlined]
jl_serialize_value at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:570
in expression starting at none:0
is_ir_node at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:493 [inlined]
jl_serialize_value_ at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:570
jl_serialize_value_ at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:766 [inlined]
jl_serialize_value_ at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:767
jl_serialize_value_ at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:531 [inlined]
jl_serialize_value_ at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:700
jl_serialize_value_ at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:528 [inlined]
jl_compress_ir at /cygdrive/c/buildbot/worker/package_win64/build/src\dump.c:2601
cache_result at .\compiler\typeinfer.jl:122
typeinf at .\compiler\typeinfer.jl:67
typeinf_edge at .\compiler\typeinfer.jl:484
abstract_call_method at .\compiler\abstractinterpretation.jl:419
abstract_call_gf_by_type at .\compiler\abstractinterpretation.jl:111
abstract_call_known at .\compiler\abstractinterpretation.jl:904
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_apply at .\compiler\abstractinterpretation.jl:635
abstract_call_known at .\compiler\abstractinterpretation.jl:704
abstract_call at .\compiler\abstractinterpretation.jl:926
abstract_call at .\compiler\abstractinterpretation.jl:911
abstract_eval at .\compiler\abstractinterpretation.jl:1005
typeinf_local at .\compiler\abstractinterpretation.jl:1270
typeinf_nocycle at .\compiler\abstractinterpretation.jl:1326
typeinf at .\compiler\typeinfer.jl:12
typeinf_ext at .\compiler\typeinfer.jl:570
typeinf_ext at .\compiler\typeinfer.jl:601
jfptr_typeinf_ext_24535.clone_1 at C:\Users\angel\AppData\Local\Programs\Julia 1.5.4\lib\julia\sys.dll (unknown line)
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2214 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398 [inlined]
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1691 [inlined]
jl_type_infer at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:296
jl_generate_fptr at /cygdrive/c/buildbot/worker/package_win64/build/src\jitlayers.cpp:290
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1964
jl_compile_method_internal at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:1931 [inlined]
_jl_invoke at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2224 [inlined]
jl_apply_generic at /cygdrive/c/buildbot/worker/package_win64/build/src\gf.c:2398
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1691 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:674
jl_f__apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:688 [inlined]
jl_f__apply_latest at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:724
#invokelatest#1 at .\essentials.jl:710 [inlined]
invokelatest at .\essentials.jl:709
jl_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\julia.h:1691 [inlined]
do_apply at /cygdrive/c/buildbot/worker/package_win64/build/src\builtins.c:674
_pyjlwrap_call at C:\Users\angel.julia\packages\PyCall\7a7w0\src\callback.jl:28
unknown function (ip: 00000180f363cc94)
pyjlwrap_call at C:\Users\angel.julia\packages\PyCall\7a7w0\src\callback.jl:44
unknown function (ip: 0000017eb42b0b4f)
unknown function (ip: 0000017eb41f41f9)
unknown function (ip: 0000017eb41f4062)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyThreadState_Get at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalCode at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalCode at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicode_GetLength at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicode_GetLength at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalCode at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalCode at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicode_GetLength at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicode_GetLength at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyErr_ChainExceptions at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyList_SetSlice at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_GC_Malloc at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicodeWriter_Finish at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyOS_getsig at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyIter_Send at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyInit__asyncio at C:\Users\angel\AppData\Local\Programs\Python\Python310\DLLs_asyncio.pyd (unknown line)
PyInit__asyncio at C:\Users\angel\AppData\Local\Programs\Python\Python310\DLLs_asyncio.pyd (unknown line)
PyInit__asyncio at C:\Users\angel\AppData\Local\Programs\Python\Python310\DLLs_asyncio.pyd (unknown line)
Py_NewReference at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyContext_NewHamtForTests at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyContext_NewHamtForTests at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyArg_CheckPositional at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalCode at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalCode at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicode_GetLength at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyUnicode_GetLength at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyEval_EvalFrameDefault at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyFunction_Vectorcall at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyVectorcall_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
PyObject_Call at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
Py_GetLocaleconvNumeric at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
Py_RunMain at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
Py_RunMain at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
Py_Main at C:\Users\angel\AppData\Local\Programs\Python\Python310\python310.dll (unknown line)
unknown function (ip: 00007ff74be3122f)
BaseThreadInitThunk at C:\windows\System32\KERNEL32.DLL (unknown line)
RtlUserThreadStart at C:\windows\SYSTEM32\ntdll.dll (unknown line)
Allocations: 8686054464 (Pool: 8681434739; Big: 4619725); GC: 2697

Windows fatal exception: access violation

Main thread:
Current thread 0x00001a80 (most recent call first):
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\julia\core.py", line 215 in setattr
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\opf\run_powermodels.py", line 87 in _call_pandamodels
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\opf\run_powermodels.py", line 34 in _runpm
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\runpm.py", line 134 in runpm_ac_opf
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\control\run_control.py", line 180 in _evaluate_net
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\control\run_control.py", line 218 in control_implementation
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\control\run_control.py", line 298 in run_control
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\timeseries\run_time_series.py", line 126 in run_time_step
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\timeseries\run_time_series.py", line 321 in run_loop
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\pandapower\timeseries\run_time_series.py", line 349 in run_timeseries
File "c:\users\angel...\development\python_scripts\performance_assessment_monte_carlo_greek_dso_net.py", line 1359 in
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\spyder_kernels\py3compat.py", line 356 in compat_exec
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 469 in exec_code
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 611 in exec_file
File "C:\Users\angel...\development\work_env_spyder\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 524 in runfile
File "C:\Users\angel\AppData\Local\Temp\ipykernel_11812\249685542.py", line 1 in <cell line: 1>

**Comment by ccordoba12** [comment]
Hey @angelinasyrri, thanks for reporting. Could you try to run your code on JupyterLab or a Jupyter notebook? If your code also fails there, it means the problem is not with Spyder.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by angelinasyrri** [comment]
Hi @ccordoba12! Sorry for the late response, I was away on holiday. Indeed, it is not a matter of the spyder interface. It is a memory issue as it seems, therefore I will split my problem:) Thanks for the feedback!

**Comment by ccordoba12** [comment]
Hey @angelinasyrri, no problem. Let us know if you need additional help after that.
