### ISSUE TITLE
Memory leak when closing editor or console tabs

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#18764]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Every time a tab is closed, the code editor is not removed from memory.
The full list of added object can be seen here: (Executed in the internal console)
```
>>> objgraph.show_growth(limit=1000)
tuple                         37021      +120
dict                          68206       +58
QShortcut                       280       +42
Shortcut                        254       +42
list                          74018       +38
method                         1774       +32
cell                          12439       +26
QColor                          247       +26
function                      63060       +24
SpyderAction                    559       +23
weakref                       12590       +21
QTimer                          105       +16
QTextBlock                      498       +10
QTextCharFormat                  86        +9
QBrush                           28        +7
QPen                             28        +7
QAction                         162        +5
set                            4836        +3
QMutex                           15        +3
FoldingRegion                   344        +3
partial                         694        +2
QMenu                            22        +2
QComboBox                        10        +2
QTextCursor                      12        +2
QScrollBar                       12        +2
IntervalTree                      9        +2
QStaticText                       8        +2
SortedDict                        9        +2
SortedList                        9        +2
builtin_function_or_method     5421        +1
Signals                          35        +1
Context                          37        +1
diff_match_patch                  6        +1
Property                         88        +1
QThread                          13        +1
QWidget                          89        +1
QHBoxLayout                     103        +1
QFont                            24        +1
LineNumberArea                    6        +1
PythonSH                          6        +1
QObject                           6        +1
QTextDocument                     7        +1
QPoint                            6        +1
CallTipWidget                     7        +1
QBasicTimer                       7        +1
ToolTipWidget                     5        +1
TextDecorationsManager            5        +1
CompletionWidget                  7        +1
HTMLDelegate                      5        +1
Future                           13        +1
Handle                           20        +1
QtKillRing                        5        +1
KillRing                          5        +1
CodeEditor                        4        +1
TextHelper                        4        +1
PanelsManager                     4        +1
EdgeLine                          4        +1
IndentationGuide                  4        +1
FoldingPanel                      4        +1
DelayJobRunner                    4        +1
DebuggerManager                   4        +1
DebuggerPanel                     4        +1
ClassFunctionDropdown             4        +1
ScrollFlagArea                    4        +1
DocstringWriterExtension          4        +1
QEventLoop                        4        +1
EditorExtensionsManager           4        +1
SnippetsExtension                 4        +1
CloseBracketsExtension            4        +1
Index                             4        +1
IndexHandle                       4        +1
OutlineExplorerProxyEditor        4        +1
patch_obj                         3        +1
CloseQuotesExtension              4        +1
TextDecoration                    4        +1
PropertyHandle                    4        +1
Node                            357        +1
FoldingStatus                     4        +1
Interval                        496        +1
PythonWorker                      3        +1
```

A lot of these objects, including `LineNumberArea` and `Shortcut`, are linked with `CodeEditor`. The question is therefore why the code editor is never removed. One can inspect the reference graph with `objgraph`:
![completion_widget](https://user-images.githubusercontent.com/6740194/180153268-e3465126-7135-49a8-aa95-1aa0f00c0385.png)
The problem is therefore that the parent of each new `CompletionWidget` is set to the main window and never removed.
It makes more sense to have the `CodeEditor` as a parent, but that only displaces the problem, as the new shortest chain is:
![completion_plugin](https://user-images.githubusercontent.com/6740194/180153646-7fb3a374-1fe9-44c3-9cf3-f710c4ba5eb7.png)
`CompletionPlugin.requests` grows indefinitely.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by impact27** [comment]
I digged a bit more and found two other sources of CodeEditor leaks:
This one is the expected graph, but the CodeEditor is never removed. This can be solved by calling `editor.setParent(None)` in `EditorStack.close_file`
![CodeEditor2](https://user-images.githubusercontent.com/6740194/180170597-e1df18e1-45e6-4a82-a7e7-0915c32bf26a.png)
The other one shows that the shortcut list is never emptied:
![CodeEditor4](https://user-images.githubusercontent.com/6740194/180170670-f1e6b027-3aa2-4f04-8c16-502bed072e47.png)

**Comment by ccordoba12** [comment]
Hey @impact27, thanks a lot for taking a look at this issues! About what you said:

> The other one shows that the shortcut list (_shortcut_data) is never emptied:

Is it not be possible to clear that on `EditorStack.close_file` as well?

**Comment by impact27** [comment]
Alternatively we could use weakref. 
So:
 - Set CompletionWidget parent to None
 - Set CodeEditor parent to None
 - Use weakref in requests
 - unregister the shortcuts
