### ISSUE TITLE
Help pane unable to render rich text on macOS app

### ISSUE THREAD

**Issue by hawkiyc** [spyder-ide/spyder#18776]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I have an issue with the help pane in rich text, similar to #17751, but on macOS 12.4.

### What steps reproduce the problem?

1. I apologize for not knowing when and how the help pane is not working normally in rich text.
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.2
* Python version: 3.8.13
* Qt version: 5.9.7 
* PyQt version: 5.9.2
* Operating System name/version: macOS 12.4

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.7.2 (OK)
keyring >=17.0.0                     :  23.7.0 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0;<3.0                  :  2.14.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  63.2.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.2;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.3.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @hawkiyc, thanks for reporting. This problem could be caused because you're mixing pip and conda packages.

To try to fix it, please create a new environment with conda-forge packages. For that, close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Let us know if it works for you.

**Comment by hawkiyc** [comment]
Hi @ccordoba12 ,

Thank you for your prompt reply.

I want to clarify that I prefer only to install one IDE on my device. Hence, in my case, I installed spyder via dmg file from your website. After that, I pip installed spyder-kernels in each env, so I can turn on my spyder and tune in different env without opening anaconda or pressing the command line in Terminal. 

Therefore, I would like to confirm that I shall have spyder in each env, not changing env within spyder?

I appreciate your kind help and looking forward to your answer.

Sincerely,

Gavin

**Comment by dalthviz** [comment]
Just in case, I think this could be related with the installer signing process and something that @mrclary was experiencing too and which most probably is affecting panes that use QWebWidgets

**Comment by hawkiyc** [comment]
Hi @dalthviz 

Okay, I see. I will have some tests in the following days if I have time. Anyway, I will let you know if I have the test results.

Sincerely,

Gavin

**Comment by mrclary** [comment]
Yes, I'm certain that this is related to the new code signing.
I've reopened #18679 to rebuild the release artifact with codesign fixes.

**Comment by mrclary** [comment]
@hawkiyc, new artifacts are now up for 5.3.2 which should resolve your issue. Just download either Spyder.dmg again as you did before. I've already downloaded it and verified, but please let me know if everything is working for you. Thanks for your patience and sorry for any inconvenience 😄 .
