### ISSUE TITLE
ZMQError when starting Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1880]
_From [mr.world...@gmail.com](https://code.google.com/u/100725460776817262673/) on 2014-07-03T06:06:56Z_

Spyder Version:  2.3.0rc
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.6 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 

Please provide any additional information below

. An error ocurred while starting the kernel
‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑
ZMQError Traceback (most recent call last)
E:\Anaconda\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py in ()
185 ipk_temp = IPKernelApp.instance()
186 ipk_temp.config = kernel_config()
‑‑> 187 ipk_temp.initialize()
global ipk_temp.initialize = >
188 
189 # Grabbing the kernel's shell to share its namespace with our

E:\Anaconda\lib\site‑packages\IPython\kernel\zmq\kernelapp.py in initialize(self=, argv=None)

E:\Anaconda\lib\site‑packages\IPython\config\application.pyc in catch_config_error(method=, app=, *args=(None,), **kwargs={})
90 """
91 try:
‑‑‑> 92 return method(app, *args, **kwargs)
method = 
app = 
args = (None,)
kwargs = {}
93 except (TraitError, ArgumentError) as e:
94 app.print_help()

E:\Anaconda\lib\site‑packages\IPython\kernel\zmq\kernelapp.py in initialize(self=, argv=None)
433 self.init_session()
434 self.init_poller()
‑‑> 435 self.init_sockets()
self.init_sockets = >
436 self.init_heartbeat()
437 # writing/displaying connection info must be *after* init_sockets/heartbeat

E:\Anaconda\lib\site‑packages\IPython\kernel\zmq\kernelapp.py in init_sockets(self=)
298 # atexit.register(context.term)
299 
‑‑> 300 self.shell_socket = context.socket(zmq.ROUTER)
self.shell_socket = undefined
context.socket = >
global zmq.ROUTER = 6
301 self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
302 self.log.debug("shell ROUTER Channel on port: &#37;i" &#37; self.shell_port)

E:\Anaconda\lib\site‑packages\zmq\sugar\context.pyc in socket(self=, socket_type=6)
141 if self.closed:
142 raise ZMQError(ENOTSUP)
‑‑> 143 s = self._socket_class(self, socket_type)
s = undefined
self._socket_class = 
self = 
socket_type = 6
144 for opt, value in self.sockopts.items():
145 try:

E:\Anaconda\lib\site‑packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.socket.Socket.__cinit__ (zmq\backend\cython\socket.c:2481)()

ZMQError: Connection refused

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1880_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-25T01:24:48Z_

This problem is usually generated by an antivirus. Please try to deactivate or uninstall it and run it again.

**Summary:** ZMQError when starting Spyder  \<span class="oldvalue"> (was: Everytime starting Spyder) \</span>  
  **Labels:** Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ukpokemo...@googlemail.com](https://code.google.com/u/101196988284824864293/) on 2014-09-12T05:14:41Z_

copied from the about Spyder box
Spyder 2.3.0
Python 2.7.7 32bits, Qt 4.86, PyQtw(API v2) 4.10.4 on windows

I have just installed iPython anaconda and get an almost identical error when I start Spyder.  I uninstalled the anti-virus and disabled the firewall on this Windows XP machine but it made no difference. iPython notebook also crashes when I try to open a new notebook. It has a more extensive error message but the crash results in teh cmd window closing before I can make a copy. I do not have the slightest idea what the error message is telling me to do to fix the issue.

error report in Spyder's IP Console pane.
.....snip....same as above ... snip
C:\Anaconda\lib\site‑packages\zmq\sugar\context.pyc in socket(self=, socket_type=6)
135 if self.closed:
136 raise ZMQError(ENOTSUP)
‑‑> 137 s = self._socket_class(self, socket_type)
s = undefined
self._socket_class = 
self = 
socket_type = 6
138 for opt, value in self.sockopts.items():
139 try:

C:\Anaconda\lib\site‑packages\zmq\backend\cython\socket.pyd in zmq.backend.cython.socket.Socket.__cinit__ (zmq\backend\cython\socket.c:2481)()

ZMQError: Connection refused

**Comment by spyder-issues-migrator** [comment]
_From [gavin.bu...@gmail.com](https://code.google.com/u/108503837424157770981/) on 2014-10-02T01:46:06Z_

I've had this problem persistently on my Windows 7 64bit laptop. It's intermittent in that usually after about 4 or 5 attempts to start an ipython shell in spyder it eventually works. This happens independently of the anti-virus being on or off, of the firewall being on or off and nothing shows up in the Windows event log.

Eventually, after reading abit about what changed between Windows XP and 7, I tried changing the default range of ports that zmq.socket.py uses to establish the connection between console and kernel. As shipped, this is the same as the range of ports used by Windows Vista,7,8,8.1 for dynamic connections (49152-65535). I've changed zmq/sugar/socket.py  bind_random_port to read:

    def bind_to_random_port(self, addr, min_port=32768, max_port=49151, max_tries=100): 

That has seemed (on the basis of a short testing time) to have cured the problem. I'd speculate that in some cases Windows allocates enough ports in the dynamic range to make it difficult for ipython to find a spare port, by switching it to a different range, the chances of getting a port that is free goes up.

**Comment by awan1** [comment]
^ this works on my win8.1 64bit laptop, thanks!

**Comment by goanpeca** [comment]
@ccordoba12, is this something to address in zmq, ipython issues?

**Comment by ccordoba12** [comment]
Not IPython but [pyzmq](https://github.com/zeromq/pyzmq). Using the fantastic Github interface, I submitted a PR with Gavin's suggestion.

Let's see what @minrk thinks about it :-)

**Comment by ccordoba12** [comment]
Thanks a lot noticing @goanpeca!! It went totally unnoticed to me ;-)

**Comment by minrk** [comment]
Does this problem affect any Windows later than XP? If so, what version(s)?

**Comment by ccordoba12** [comment]
@minrk, according to @gb119 above: Windows Vista, 7, 8, 8.1

**Comment by minrk** [comment]
I must have read it backwards, I thought using that range *shouldn't* be a problem on those systems. That's definitely the range where the port should come from on those systems.

**Comment by minrk** [comment]
Ah, I believe this is already fixed by zeromq/pyzmq#651, which should be released as pyzmq-14.6 soon.

**Comment by goanpeca** [comment]
:+1:

**Comment by gb119** [comment]
Great - if I get a chance I can try it out on my laptop which I know suffers from this problem.

**Comment by ccordoba12** [comment]
Thanks @minrk!! Glad to know you already tackled this problem :-)

**Comment by ccordoba12** [comment]
@gb119, any confirmation on this one? Was it fixed by the latest pyzmq?

**Comment by gb119** [comment]
Yes - sorry forgot to report it all seemed good now. Thanks for fixing !

**Comment by ccordoba12** [comment]
This was not an issue in Spyder itself, but I'm glad it's fixed now.
