### ISSUE TITLE
"Spyder was unable to retrieve the value of variable...", variable  type is GeoDataFrame

### ISSUE THREAD

**Issue by 1Dodeo1** [spyder-ide/spyder#18807]
### What steps will reproduce the problem?

Hello
I read file using geopandas.read_file(), GeoDataFrame variable appeared in variable explorer. After dobule clicking on it I get error with message 
"Spyder was unable to retrieve the value of variable.. An error occured, see the console..".
 But console is empty. I have already read similar topic (https://github.com/spyder-ide/spyder/issues/15998) and added path to my packages (packages to proper kernel) through PYTHONPATH manager. But it did not solve the problem. By the way with DataFrame from pandas all works properly

## Versions

* Spyder version: 5.3.2  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.7.2 (OK)
keyring >=17.0.0                     :  23.6.0 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0;<3.0                  :  2.14.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  63.1.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.2;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.3.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @1Dodeo1, thanks for reporting. For this to work we'd need to add Geopandas and all its dependencies to our standalone installers, which would make them too big for common usage.

@dalthviz, @mrclary, how do you think we could solve this?

**Comment by mrclary** [comment]
> Hey @1Dodeo1, thanks for reporting. For this to work we'd need to add Geopandas and all its dependencies to our standalone installers, which would make them too big for common usage.
> 
> @dalthviz, @mrclary, how do you think we could solve this?

This should be resolved with the Environment Manager we have planned for the future. In addition to creating/managing external environments, it will allow users to install packages (from a predefined list) into Spyder's runtime environment, specifically for extending Variable Explorer.

Before the Environment Manager is available, however, the only options that I can think of for resolving this would be:

1. Adding geopandas to the full version Spyder installer. As @ccordoba12 mentioned, this will make Spyder too large for common use.
2. Add pip to the Spyder installer and provide instructions on how to add packages to Spyder's runtime environment. This would essentially be alpha testing what the Environment Manager would do, but it would require that the user be experienced enough to do it. This would be highly experimental and we could not guarantee that the user would not break Spyder (though the user could just re-install to fix).

I think option 2 is feasible for advanced users. I have been experimenting with it myself but I have not gotten far enough along yet to know whether it will work. I might be able to have something more substantial in the next few weeks, though.

**Comment by ccordoba12** [comment]
> Add pip to the Spyder installer and provide instructions on how to add packages to Spyder's runtime environment. This would essentially be alpha testing what the Environment Manager would do, but it would require that the user be experienced enough to do it.

This is not a planned feature for the Environment Manager. That will only handle external envs, not the Spyder env itself. Furthermore, installing more packages on this env won't be possible until we use Conda/Mamba to build our installers. That's because it'd be the best way to ensure the Spyder env is not broken when installing other packages on it.

**Comment by mrclary** [comment]
I suppose, then, there isn't really anything we can do about this issue anytime soon.

**Comment by ccordoba12** [comment]
Yeah, unfortunately, I think so too.

@1Dodeo1, the only solution to your problem for now is to download Anaconda/Miniconda and install Geopandas and Spyder from Conda-forge by opening the Anaconda Prompt and running

    conda create -n myenv -c conda-forge spyder geopandas

After that, you always need to start Spyder by opening the Anaconda Prompt and running

    conda activate myenv
    spyder
