### ISSUE TITLE
kernel?????????

### ISSUE THREAD

**Issue by amelia-pompilio** [spyder-ide/spyder#18847]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @amelia-pompilio , without any more info is quite difficult to help, sorry :/ If this was sent from the Spyder interface then I would suggest you to update (a quite out of date Spyder version could allow sending an issue without any content I think).

Not sure the Spyder version you are using but the current one is 5.3.2. If you need help to do the update let us know you setup characteristics (OS, Python version, Spyder version, way Spyder was installed, etc).

**Comment by dalthviz** [comment]
Closing as invalid since no further info was provided
