### ISSUE TITLE
Annoying Issue reporter window pops up every time I try to run code. 

### ISSUE THREAD

**Issue by wisefool01** [spyder-ide/spyder#18868]
## I typed in the following code:

```
# -*- coding: utf-8 -*-
"""
Created on Fri Jul 29 16:16:52 2022

@author: arafa
"""
alphabet = 'abcdefghijklmnopqrstuvwxyz'
newMessage = ' '
message = input('Please enter a message: ')
key = input('Enter a key (1-26): ')
key = int(key)

for character in message:
    if character in alphabet:
        position = alphabet.find(character)
        newPosition = (position + key) % 26
        newCharacter = alphabet[newPosition]
        newMessage += newCharacter
    else:
        newMessage += newCharacter

print('Your new message is:', newMessage)
```

Then I simply clicked on the 'Run' button. 

I didn't even intend to submit a bug report. However, everytime I click run, this issue reporter window is popping up. It's really annoying.  

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\arafa\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\arafa\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\arafa\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\arafa\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.6.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by wisefool01** [comment]
Thanks. That fixed it.

Do I need to use Anaconda Prompt every time to open Spyder, or can I use Anaconda Navigator as well?

**Comment by dalthviz** [comment]
You can use the shortcut that is created to launch Spyder from the env. From the start menu you should be able to type `Spyder (spyder-cf)` and then the shortcut should be listed:

![startmenu](https://user-images.githubusercontent.com/16781833/182218762-26ec36cf-8bb6-4430-a67b-674a17014df2.png)

I think you can also select the env from where you launch Spyder with Anaconda Navigator:

![imagen](https://user-images.githubusercontent.com/16781833/182219268-8d755734-f193-43ea-9d41-e392d2998c45.png)

Then you should be able to see the correct card for Spyder (Spyder 5.3.2):

![imagen](https://user-images.githubusercontent.com/16781833/182219365-c015be72-a03b-4226-b167-83d7568646f4.png)

**Comment by wisefool01** [comment]
> You can use the shortcut that is created to launch Spyder from the env. From the start menu you should be able to type `Spyder (spyder-cf)` and then the shortcut should be listed:
> 
> ![startmenu](https://user-images.githubusercontent.com/16781833/182218762-26ec36cf-8bb6-4430-a67b-674a17014df2.png)
> 
> I think you can also select the env from where you launch Spyder with Anaconda Navigator:
> 
> ![imagen](https://user-images.githubusercontent.com/16781833/182219268-8d755734-f193-43ea-9d41-e392d2998c45.png)
> 
> Then you should be able to see the correct card for Spyder (Spyder 5.3.2):
> 
> ![imagen](https://user-images.githubusercontent.com/16781833/182219365-c015be72-a03b-4226-b167-83d7568646f4.png)

Thanks for the detailed explanation! Both of the ways work.
