### ISSUE TITLE
Create conda-based standalone application

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#18870]
Making conda-based standalone applications for macOS, Windows, and Linux is desirable to facilitate installing/uninstalling third-party plugins.

**Comment by mrclary** [comment]
@jaimergp, given your work on napari/napari, would you be willing to discuss with me some of the issues you ran into and how you resolved them?

Also pinging @dalthviz.

**Comment by jaimergp** [comment]
Sure! Let me know what you need to know :)

The napari docs have some info:

- https://napari.org/dev/developers/packaging.html
- NAP-2: https://napari.org/dev/naps/2-conda-based-packaging.html#

That's probably a good start.

**Comment by mrclary** [comment]
@jaimergp, thanks for being willing to share.

The Spyder project currently creates a standalone application bundle for macOS using `py2app` (I'm the principle maintainer). However, I think Spyder and Napari developers share similar motivations for building standalone applications based on `conda`.

I find two types of release artifacts for macOS: pkg and zip. The package installer (pkg) installs a local conda environment and napari-\<ver\>.app. This application bundle is a wrapper for a shell script that references the local conda environment. The zip artifact is just a disk image (dmg) containing napari.app and appears to be standalone (python and necessary packages are contained inside the application bundle).
- Can you explain why there are two different application types? FYI, the standalone application bundle crashes on launch.
<details><summary>traceback</summary>

```
Traceback (most recent call last):
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 453, in <module>
    sys.exit(main())
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 449, in main
    _run()
  File "napari.app/Contents/Resources/app/napari/__main__.py", line 214, in _run
    from napari import Viewer, run
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "napari.app/Contents/Resources/app/napari/_lazy.py", line 48, in __getattr__
    submod = import_module(
  File "napari.app/Contents/Resources/Support/Python/Resources/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "napari.app/Contents/Resources/app/napari/viewer.py", line 8, in <module>
    from .components.viewer_model import ViewerModel
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/components/__init__.py", line 19, in <module>
    from .layerlist import LayerList
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/components/layerlist.py", line 9, in <module>
    from ..layers import Layer
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/__init__.py", line 11, in <module>
    from .base import Layer
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/base/__init__.py", line 1, in <module>
    from .base import Layer, no_op
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/layers/base/base.py", line 26, in <module>
    from ...utils.key_bindings import KeymapProvider
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/utils/key_bindings.py", line 46, in <module>
    from ..settings import get_settings
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/settings/__init__.py", line 5, in <module>
    from ._base import _NOT_SET
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/settings/_base.py", line 18, in <module>
    from ._yaml import PydanticYamlMixin
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/settings/_yaml.py", line 9, in <module>
    from ._fields import Version
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/settings/_fields.py", line 6, in <module>
    from ..utils.theme import available_themes
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app/napari/utils/theme.py", line 335, in <module>
    _install_npe2_themes(_themes)
  File "napari.app/Contents/Resources/app/napari/utils/theme.py", line 325, in _install_npe2_themes
    import npe2
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/__init__.py", line 8, in <module>
    from ._dynamic_plugin import DynamicPlugin
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_dynamic_plugin.py", line 19, in <module>
    from ._plugin_manager import PluginManager
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_plugin_manager.py", line 30, in <module>
    from ._command_registry import CommandRegistry
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/_command_registry.py", line 10, in <module>
    from .manifest import utils
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/__init__.py", line 2, in <module>
    from .schema import ENTRY_POINT, PluginManifest
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/schema.py", line 19, in <module>
    from .contributions import ContributionPoints
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/__init__.py", line 2, in <module>
    from ._contributions import ContributionPoints
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/_contributions.py", line 11, in <module>
    from ._widgets import WidgetContribution
  File "napari.app/Contents/Resources/app_packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "napari.app/Contents/Resources/app_packages/npe2/manifest/contributions/_widgets.py", line 14, in <module>
    class WidgetContribution(BaseModel, Executable[Widget]):
  File "pydantic/main.py", line 188, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 413, in pydantic.typing.resolve_annotations
TypeError: __init__() got an unexpected keyword argument 'is_class'
```
</details>

- How does the package installer create the napari-\<ver\>.app bundle? Is it already in the pkg file or is it created locally? Where is the code for this (I don't see it in `conda_bundle.py`)?

**Comment by jaimergp** [comment]
> Can you explain why there are two different application types?

`napari` is transitioning from Briefcase-based bundles (.zip containing a DMG) to constructor-based ones (.pkg). In the transition phase, both are available. The ones I am focused on are the PKGs; the DMGs will be eventually removed.

> How does the package installer create the napari-<ver>.app bundle?

This serves the role of a shortcut, so the main installation is somewhat hidden but the user can easily find it via the .app icon. It's created dynamically at install time:

- `constructor` will bundle a `conda-standalone` executable which will, in turn, contain a library called `menuinst`. 
- `menuinst` is the library used by Anaconda to create the shortcuts on Windows, but I rewrote it to support Linux and MacOS. 
- If a package distributes a JSON file under `$PREFIX/Menu`, then a shortcut will be created using those instructions. 
- None of this is upstreamed/released yet, so we build off a fork (uploaded to the `napari/label/bundle_tools` channel).

**Comment by mrclary** [comment]
> `napari` is transitioning from Briefcase-based bundles (.zip containing a DMG) to constructor-based ones (.pkg). In the transition phase, both are available. The ones I am focused on are the PKGs; the DMGs will be eventually removed.

Aahh, that make sense.

> This serves the role of a shortcut, so the main installation is somewhat hidden but the user can easily find it via the .app icon. It's created dynamically at install time:
> 
> * `constructor` will bundle a `conda-standalone` executable which will, in turn, contain a library called `menuinst`.
> * `menuinst` is the library used by Anaconda to create the shortcuts on Windows, but I rewrote it to support Linux and MacOS.
> * If a package distributes a JSON file under `$PREFIX/Menu`, then a shortcut will be created using those instructions.
> * None of this is upstreamed/released yet, so we build off a fork (uploaded to the `napari/label/bundle_tools` channel).

- So, the `_conda.exe` executable file contains `menuist`?
- Is there a reason why you need `menuist` for macOS and Linux? These should just need to create "folders" with the appropriate structure and files. Can't this be accomplished with a script run by the pkg installer?
- Couldn't `micromamba` accomplish the same thing as `_conda.exe`?

**Comment by jaimergp** [comment]
> So, the _conda.exe executable file contains menuist?

Yes. And some patches not present in the regular conda. See [here](https://github.com/conda-forge/conda-standalone-feedstock).

> Is there a reason why you need menuist for macOS and Linux? These should just need to create "folders" with the appropriate structure and files. Can't this be accomplished with a script run by the pkg installer?

Well, sure, every operation in the installer can be done with a script after all. But since it's the same operation for _every_ installer, I added those features to `menuinst`. That way you don't have to figure out all the details about environment activation across OSs, icons, etc.

> Couldn't micromamba accomplish the same thing as _conda.exe?

Yes, as long as it reimplements the logic for Linux/OSX. Right now it only support the old-style, Windows-only menu config files.

**Comment by mrclary** [comment]
@jaimergp, Thanks for your clarifications! It looks like the easiest way for me to proceed with Spyder is to leverage your work by using `constructor` from the napari conda-forge channel. I'll take a stab at it, but I'm sure I'll have more questions in the future.

**Comment by mrclary** [comment]
@jaimergp, I cannot seem to find the source code for `napari-menu`; can you provide a link?

**Comment by jaimergp** [comment]
It just contains this file
https://github.com/napari/napari/blob/main/resources/conda_menu_config.json

It needs to be placer under $PREFIX/Menu, but you need the new menuinst, constructor fork, patched conda-standalone, and so on.

**Comment by mrclary** [comment]
@jaimergp, it appears that constructor from napari/label/bundle_tools does not support specifying an existing environment for the `extra_env`. I see you're actively working in fcp.py, so is this departure from standard constructor behavior intentional or is this transitory?

**Comment by jaimergp** [comment]
It should :/ It's what we are using for our CI, currently using extra_envs. See [here](https://github.com/napari/packaging/blob/7ac4206ce7664064c8efc41a2e0873bf091028a2/build_installers.py#L237-L262).

**Comment by mrclary** [comment]
@jaimergp, I'm sorry, perhaps I wasn't clear. I meant the `environment`, as opposed to the `specs`, keyword to the `extra_env` item.

The offending lines of code are `fcp._main:381-392`, in the `constructor` package, retrieved from napari/label/bundle_tools conda channel. It does not match the code in the master branch of [jaimergp/constructor](https://github.com/jaimergp/constructor), so I don't know which branch it was built from.
```python
    for env_name, env_config in extra_envs.items():
        if verbose:
            print("Solving extra environment:", env_name)
        extra_envs_precs[env_name] = _solve_precs(
            f"{name}+{env_name}", version, download_dir, platform,
            channel_urls=env_config.get("channels") or channel_urls,
            channels_remap=env_config.get("channels_remap", channels_remap),
            specs=env_config["specs"],
            menu_packages=env_config.get("menu_packages", menu_packages),
            environment=None, environment_file=None, verbose=verbose,
            conda_exe=conda_exe
        )
```
in `_main`, `_solve_precs` is called, passing `env_config["specs"]` (`specs` may not exists) and _not_ passing `environment` or `environment_file`. Indeed, attempting to pass an environment name rather than specifications for an extra environment results in `KeyError: 'specs'`.

**Comment by jaimergp** [comment]
Ah, yes, sorry, now I see what you mean. The implementation found in the `bundle_tools` variants were the minimum ones needed for `napari`. Most of it has made it to `conda/constructor` upstream already, but there's no package in anaconda.org.

You could just pip install it from the github tarball though, and cross your fingers :D 

The reason I am not using `main` yet is because it lacks the menuinst shortcuts supports, and that will take longer to land...

**Comment by mrclary** [comment]
> Ah, yes, sorry, now I see what you mean. The implementation found in the `bundle_tools` variants were the minimum ones needed for `napari`. Most of it has made it to `conda/constructor` upstream already, but there's no package in anaconda.org.
> 
> You could just pip install it from the github tarball though, and cross your fingers :D
> 
> The reason I am not using `main` yet is because it lacks the menuinst shortcuts supports, and that will take longer to land...

I see. So if `conda/constructor`'s main branch has most of the changes already, I can just work from that. But what do you recommend for `menuinst`? Is `napari/label/bundle_tools` okay for that still, or should I work from work from your fork's master branch? I assume that `napari/label/bundle_tools` is still okay for `conda-standalone`.

**Comment by jaimergp** [comment]
The problem with the menuinst-related features is that it requires code on `constructor` too 😬  So right now you have to choose between using `environment` in your `extra_envs` or fancy multi-platform shortcuts :D

**Comment by mrclary** [comment]
I can do without `environment` in `extra_envs`. I'm just trying to see what may or may not work for Spyder. If `bundle_tools` only has the minimum variants required for `napari`, then I may want to avoid that channel. In which case, I can take `constructor` from its main branch (or some branch from your fork?), `menuinst` from ... (which branch do you recommend?), and `conda-standalone` from ... (maybe `bundle_tools` is okay for this one?)

**Comment by jaimergp** [comment]
I'd say stick to the `bundle_tools` family for the first prototype. By the time you have something working I might need to move `napari` to upstream (sometime in September), at least some parts, and you'll get the benefits for free :)

**Comment by mrclary** [comment]
@jaimergp, I'm still confused about how `napari-menu` works. I've included files in the Menu directory as extra files in the package installer and they get installed in the appropriate Menu directory in the installed environment when the package installer is run, but `menuinst` still doesn't create the application. So, I am assuming that the Menu directory in the installed environment prefix must be placed there by a conda package. I'm still not clear on how this is done for napari. I don't see where you build the `napari-menu` package or its feedstock. Please advise.

**Comment by mrclary** [comment]
Okay, so I figured out the menu packaging issue.

**Comment by mrclary** [comment]
@jaimergp, is there a way to further customize the bundle launch script (`.../Contents/MacOS/App`)?
As far as I can see, `menuinst` configuration is limited to `activate` and `command` directives.

**Comment by jaimergp** [comment]
What kind of customization do you need? I'd expect that any custom code can be provided as a separate script anyway. Maybe the menu package can also ship its own little shell script that gets installed to `$CONDA_PREFIX/bin` and then you link the menu item to that script? Would that work?

**Comment by mrclary** [comment]
> What kind of customization do you need? I'd expect that any custom code can be provided as a separate script anyway. Maybe the menu package can also ship its own little shell script that gets installed to `$CONDA_PREFIX/bin` and then you link the menu item to that script? Would that work?

All I need is to add a single line command _before_ environment activation.

```shell
#!/bin/bash

eval "$(/bin/bash -l -c "declare -x")"  # this must be before environment activation

eval "$("{conda_exe}" {activate} "{self.menu.prefix}")"

{command}
```

I don't know if there are any issues with using a symlink for the launch script in the application bundle. However, the launch script may depend on install-time environment variables, such as the root conda prefix and conda environment prefix.

It seems to me that building the script with `MacOSMenuItem._command` is the best thing to do, but just allow further control over its contents. Perhaps a new item, `script`, for the configuration json in which the developer can provide a path to a template file or multiline string directly. This template or multiline string could reference certain variables that `menuinst` recognizes, e.g. `{{ ROOT_PREFIX }}` or `{{ PREFIX }}` (or whatever, similar to `{{ MENU_DIR }}`).

I suppose this would preclude using the same script for all platforms, so maybe the `script` item is only valid under the `platform` items? Maybe taking precedence over an existing `command` item at the top level? Or maybe the developer just has to use separate configuration jsons for each platform if this level of customization is desired.

**Comment by jaimergp** [comment]
I see! Some kind of preactivation logic would make sense.

Before we talk about extend the [menuinst schema](https://github.com/conda-incubator/ceps/pull/8/files) though, let's see if we can make it work via other means. Two options to consider:

* The `activate` option is available there for your convenience, but I guess one can always switch it off and then build the whole script logic from scratch. Do we have enough info at runtime to recreate the activation command? I think we do.
* Another option would be to use conda activation scripts (those that go under `activate.d`), but maybe by then it's too late? 

Let me know what you think!

**Comment by mrclary** [comment]
> I see! Some kind of preactivation logic would make sense.
> 
> Before we talk about extend the [menuinst schema](https://github.com/conda-incubator/ceps/pull/8/files) though, let's see if we can make it work via other means.

This seems prudent.

> * The `activate` option is available there for your convenience, but I guess one can always switch it off and then build the whole script logic from scratch. Do we have enough info at runtime to recreate the activation command? I think we do.

This would be fine for me. I suppose we would have to make a few changes to `MacOSMenuItem._command` and we could not necessarily use the same configuration json for all platforms?

**Comment by jaimergp** [comment]
Yes, you are not forced to use a multiplatform JSON if you don't want. It's offered as a possibility so having menu items does not force packages to become non-noarch builds.

**Comment by mrclary** [comment]
@jaimergp, I have discovered another issue with respect to macOS integration. Keyboard shortcuts and function key assignment (for touchbars) established in macOS preferences are not respected. This is resolved by creating a symbolic link `Contents/MacOS/python` that points to `$PREFIX/bin/python`, and using _this_ python to start the application.

For example:
```
/Users/rclary/Applications/Spyder.app
└── Contents
    ├── Info.plist
    ├── MacOS
    │   ├── Spyder
    │   └── python -> /Users/rclary/Library/spyder-5.4.0.dev0/envs/spyder-5.4.0.dev0/bin/python
    ├── PkgInfo
    └── Resources
        └── spyder.icns
```
Where the application executable, `Spyder`, is:
```bash
#!/bin/bash
eval "$("/Users/rclary/Library/spyder-5.4.0.dev0/_conda.exe" shell.bash activate "/Users/rclary/Library/spyder-5.4.0.dev0/envs/spyder-5.4.0.dev0")"
$(dirname $BASH_SOURCE)/python /Users/rclary/Library/spyder-5.4.0.dev0/envs/spyder-5.4.0.dev0/bin/spyder "$@"
```

It seems to me that this symbolic link should be created by `menuinst` as standard behavior (or at least an option). This is how `python.app` (via `pythonw`) works. Can this be included in your merge requests to `menuinst`?

**Comment by jaimergp** [comment]
What if you add `python.app` as a dependency for your the package shipping your menuinst metadata, and then have the shortcut use `$PREFIX/pythonw` to launch the entry point? Does that fix it? I think this would be equivalent to what `napari`'s workaround is using.

**Comment by mrclary** [comment]
The issue does show up in napari. One could use `pythonw` (which just links to `python.app/Contents/MacOS/python`, which just links to `/bin/python`), but then `python.app` gets integrated to the macOS, not the user application. Application shortcuts in macOS preferences would have to use python.app rather than the user's application and "python" will show up in the menubar instead of the user's app name.

The reason is that the _final_ application bundle executable is inside `python.app`. This is fine for most commandline python applications because you _want_ "python" to integrate to macOS. For the user's application, we just need to apply the same _technique_, i.e. have python executable "appear" to originate from inside the user's application bundle.

The two screencasts illustrate.

Unadulterated napari does not integrate shortcuts in macOS preferences...
![integration](https://user-images.githubusercontent.com/9618975/190185946-712b721e-14e9-4e5c-ba01-fc3ebc27a12a.gif)

Modified napari has improved integration with macOS...
![integration-2](https://user-images.githubusercontent.com/9618975/190186313-b7bc1a53-e12b-4477-b26d-599a96271c57.gif)

**Comment by jaimergp** [comment]
This is super informative @mrclary, I'll look into it this week!

**Comment by mrclary** [comment]
@jaimergp, I notice that your fork of `constructor` claims no support for `post_install` or `pre_install` (https://github.com/jaimergp/constructor/blob/master/CONSTRUCT.md) but nevertheless I can provide a post install script that successfully runs. However, there appears to be limited variable substitution. The only ones available for the post install script that I can find are:
- `__PKG_NAME_LOWER__`
- `__NAME__`
- `__VERSION__`
- `__CHANNELS__`
- `__WRITE_CONDARC__`
- `__SHORTCUTS__`

Unfortunately, the most important information the package installer should provide to a post-install script is the locations of the environments produced (`__NAME_LOWER__` I think?). For my application, I can reconstruct it for narrow cases, but of course this won't work in more general cases.

**Comment by jaimergp** [comment]
I think in the fork you still have `$PREFIX`, `%PREFIX%` on Linux / Windows and `$2/__NAME_LOWER__` on MacOS. This has been improved significantly in some of the recent PRs, too. In `main`, you won't need to infer PREFIX on MacOS.

**Comment by mrclary** [comment]
> I think in the fork you still have `$PREFIX`, `%PREFIX%` on Linux / Windows and `$2/__NAME_LOWER__` on MacOS. This has been improved significantly in some of the recent PRs, too. In `main`, you won't need to infer PREFIX on MacOS.

I don't know about the fork, I've only been using what is on napari/label/bundle_tools channel (ver 4.0b2); `__NAME_LOWER__` does not appear to work. However, if the main branch has `PREFIX` provided for macOS, then that should work. When will that propagate to napari/label/bundle_tools? Is that a nightly?

**Comment by mrclary** [comment]
@jaimergp, BTW, thank you so much for your help on this. You've done a lot of work getting this working for napari and the Spyder team is benefitting from that.
