### ISSUE TITLE
'>' not supported between instances of 'Counter' and 'Counter'

### ISSUE THREAD

**Issue by Gadoli** [spyder-ide/spyder#18875]
### What steps will reproduce the problem?

Comparing two instances of Counter
Works on LeetCode though

**Comment by ccordoba12** [comment]
Hey @Gadoli, thanks for reporting. I don't understand what you mean by this bug, but it doesn't seem related to Spyder.

Please provide a clearer description of what mean by this and how it generates an error in Spyder. Otherwise, I'm afraid I'll have to close it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
