### ISSUE TITLE
i used this command and it fixed but when I again start spyder the same problem will be arise

### ISSUE THREAD

**Issue by Dhananjay17728** [spyder-ide/spyder#18907]
i used this command and it fixed but when I again start spyder the same problem will be arise

_Originally posted by @Dhananjay17728 in https://github.com/spyder-ide/spyder/issues/18906#issuecomment-1202558391_

**Comment by dalthviz** [comment]
Hi @Dhananjay17728 you need to activate the created env and launch Spyder from it to use the correct updated version of Spyder. For more info about how to launch Spyder check this comment: https://github.com/spyder-ide/spyder/issues/18868#issuecomment-1201612787

**Comment by dalthviz** [comment]
Closing due to lack of response
