### ISSUE TITLE
ipdb> AttributeError: "'builtin_function_or_method' object has no attribute 'fourcc'"

### ISSUE THREAD

**Issue by Ash-S** [spyder-ide/spyder#18903]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
ipdb> AttributeError: "'builtin_function_or_method' object has no attribute 'fourcc'"

### What steps reproduce the problem?
1. cap = cv2.VideoCapture(0)
2. cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter.fourcc('Y','1','6',' ')) 
3. cap.set(cv2.CAP_PROP_CONVERT_RGB, 0)
4. cap.set(cv2.CAP_PROP_FORMAT, -1)

### What is the expected output? What do you see instead?
raw data out

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 2.7
* Qt version: 
* PyQt version: 
* Operating System name/version:  WIN10

### Dependencies

IPython >=4.0;<6.0:  5.7.0 (OK)
cython >=0.21     :  0.28.2 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Ash-S, thanks for reporting. We don't support Spyder 3 anymore, so please update to our latest version (5.3.2) and try again.

Since it's still not available in Anaconda, you have two options:

1. Use our Windows installer, which you can find [here](https://github.com/spyder-ide/spyder/releases).
2. Create a new environment with conda-forge packages. For that, please close Spyder, open the Anaconda Prompt and run the following commands there:

        conda create -n spyder-cf -c conda-forge spyder
        conda activate spyder-cf
        spyder

Please do that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Ash-S** [comment]
Hi @ccordoba12 Thanks for your prompt response. sorry, I couldn't check it on time.
Thanks for your suggestions. I'd proceed with it and let you know the result. Thanks.

**Comment by ccordoba12** [comment]
No worries. Let us know if my suggestions work for you.

**Comment by Ash-S** [comment]
Hi @ccordoba12 I newly installed Spyder5.3.2. but while running an opencv python application, it shows **"ModuleNotFoundError: No module named 'cv2'"**
Please suggest~
![image](https://user-images.githubusercontent.com/11657541/183814210-05f79f73-f996-4902-b2a3-d2aaf466385b.png)

**Comment by ccordoba12** [comment]
Please read [these instructions](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) to understand how to proceed. And replace `conda install` by `conda install -c conda-forge` there because the Anaconda packages are quite outdated.

**Comment by Ash-S** [comment]
Hi @ccordoba12 yes, i tried to follow the instructions you suggested and replace 'conda install' by 'conda isntall -c conda-forge'. Installed 'opencv-python' using the same but still showing the same 'No module names cv2'.
