### ISSUE TITLE
Panes size is changed at Spyder start

### ISSUE THREAD

**Issue by cg-mayrhofer** [spyder-ide/spyder#18915]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
 At start the sizes of the Spyder panes is changed. That means every time I need to resize the editor window and the area righthand of the editor. I can create and load a window layout but the default layout that is loaded at the start of Spyder has the incorrect sizes (but the correct pane layout). 

Below the desired layout: 

![grafik](https://user-images.githubusercontent.com/77964479/182541043-e43899ea-d323-4151-a0b7-4dd79dc578b6.png)

This is, what I see after starting Spyder: 

![grafik](https://user-images.githubusercontent.com/77964479/182541181-b2a303bb-fc48-4284-8586-da557469e0f8.png)

I have some errors when starting Spyder with the `spyder` command from Anaconda but have no idea if this has something to do with my problem. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) PS C:\Users\SMA> spyder
fromIccProfile: failed minimal tag size sanity
C:\ProgramData\Miniconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
[3744:1356:0803/083607.142:ERROR:service_utils.cc(157)] --ignore-gpu-blacklist is deprecated and will be removed in 2020Q4, use --ignore-gpu-blocklist instead.
[3744:16160:0803/083607.143:ERROR:service_utils.cc(157)] --ignore-gpu-blacklist is deprecated and will be removed in 2020Q4, use --ignore-gpu-blocklist instead.
ERROR:asyncio:Exception in callback AddThreadSelectorEventLoop._handle_select([5420], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([5420], [])>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 579, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 591, in _handle_event
    callback()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 570, in _handle_events
    zmq_events = self.socket.EVENTS
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 55, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 67, in _get_attr_opt
    return self.get(opt)
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\_future.py", line 259, in get
    result = super().get(key)
  File "zmq\backend\cython\socket.pyx", line 476, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: not a socket
ERROR:asyncio:Exception in callback AddThreadSelectorEventLoop._handle_select([5720, 5704, 5428, 5884, 5940], [])
handle: <Handle AddThreadSelectorEventLoop._handle_select([5720, 5704, 5428, 5884, 5940], [])>
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 579, in _handle_select
    self._handle_event(r, self._readers)
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 591, in _handle_event
    callback()
  File "C:\ProgramData\Miniconda3\lib\site-packages\tornado\platform\asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\eventloop\zmqstream.py", line 570, in _handle_events
    zmq_events = self.socket.EVENTS
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 55, in __getattr__
    return self._get_attr_opt(upper_key, opt)
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\sugar\attrsettr.py", line 67, in _get_attr_opt
    return self.get(opt)
  File "C:\ProgramData\Miniconda3\lib\site-packages\zmq\_future.py", line 259, in get
    result = super().get(key)
  File "zmq\backend\cython\socket.pyx", line 476, in zmq.backend.cython.socket.Socket.get
  File "zmq\backend\cython\socket.pyx", line 137, in zmq.backend.cython.socket._check_closed
zmq.error.ZMQError: not a socket
(base) PS C:\Users\SMA>

```

## Versions

* Spyder version: 5.3.1
* Python version: 3.9.7
* Qt version: 5.15.4
* PyQt version: 5.15.7
* Operating System name/version: Win 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0                 :  1.4.0 (OK)
chardet >=2.0.0                      :  4.0.0 (OK)
cloudpickle >=0.5.0                  :  2.0.0 (OK)
cookiecutter >=1.6.0                 :  1.7.3 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.4.0 (OK)
keyring >=17.0.0                     :  23.4.0 (OK)
nbconvert >=4.0                      :  6.4.4 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.8.1 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.11.2 (OK)
pylint >=2.5.0                       :  2.12.2 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0                 :  1.4.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.2 (OK)
qstylizer >=0.1.10                   :  0.1.10 (OK)
qtawesome >=1.0.2                    :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  0.9.7 (OK)
setuptools >=49.6.0                  :  61.2.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.1;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.2.1 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.6 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  3.5.1 (OK)
numpy >=1.7                          :  1.22.3 (OK)
pandas >=1.1.1                       :  None (NOK)
scipy >=0.17.0                       :  1.7.3 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_unittest.unittestplugin 0.5.0 :  0.5.0 (OK)

**Comment by cg-mayrhofer** [comment]
Might be related to #17650

**Comment by dalthviz** [comment]
Also, regarding the `zmq.error.ZMQError: not a socket`, I think that is related most probably with the version of jupyter_client you have. However, if you update Spyder that will also update spyder-kernels and in turn require a version of jupyter_client that doesn't show that error (jupyter_client 7.3.4 I think)

**Comment by cg-mayrhofer** [comment]
I updated Spyder with `conda install -c conda-forge spyder=5.3.2` and the rezize issue seems to be fixed. 
I am not sure but the update was not available when I created this issue... Anyway, this is solved now.

**Comment by prof7bit** [comment]
Still the same issue with 5.5.0 (exact same symptom as described by the OP)

Please reopen this issue!

* Spyder version: 5.5.0  (pip)
* Python version: 3.10.12 64-bit
* Qt version: 5.15.3
* PyQt5 version: 5.15.6
* Operating System: Linux-5.15.0-89-generic-x86_64-with-glibc2.35

**Comment by dalthviz** [comment]
Hi @prof7bit as with the original OP you are also seeing a traceback of errors related with `zmq.error.ZMQError: not a socket`? Or just the panes size change? If the later is the case, could you open a new issue with the details of the behavior you are experiencing (screenshots, GIF or some video) as well as the details on how did you install Spyder? Let us know!

**Comment by prof7bit** [comment]
I do not see any tracebacks in the console, only a warning:

````
$ spyder
fromIccProfile: failed minimal tag size sanity
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: v0.9.4.4-ds-git20220108-9023143f8b93 is an invalid version and will not be supported in a future release
  warnings.warn(
````
(it really ends after the opening bracket)

But the actual symptom in the UI looks exactly like in the OP:

The leftmost pane will become larger (on every app start) and the remaining panes are shrinked proportionally, total window size remains unchanged.

original:
![1](https://github.com/spyder-ide/spyder/assets/1401589/fe3237f3-8aed-4a64-bc93-bcd4870b0578)

1st restart:
![2](https://github.com/spyder-ide/spyder/assets/1401589/826386c8-e729-4989-b26f-703068095f1a)

2nd restart:
![3](https://github.com/spyder-ide/spyder/assets/1401589/920b1cff-3f90-44db-8982-56b5462048ed)

3rd restart:
![4](https://github.com/spyder-ide/spyder/assets/1401589/553c646d-41bf-4cea-8441-be103a314eb7)

---

I do NOT believe (my intuition is telling me this) that OP's traceback has anything to do with it. He changed and updated more than one thing before reporting it fixed, but his original visible UI symptom looks exactly like mine: 

Left pane growing and remaining panes shrinking proportionally.

To me it seems the left pane (or one of the tabs inside) does not want to accept the saved size or is applying the size wrongly and the other panes have no other choice than shrinking because they don`t fit into the remaining space. They seem to apply something from the saved layout because their size proportions remain correct, but they are forced to shrink. The left pane also seems to use the saved size in some way as a starting point, but then always add additional width to the already existing saved width.

**Comment by ccordoba12** [comment]
@dalthviz, I think this is caused because we're saving the layout after closing all plugins, which doesn't save it as expected in some situations.

**Comment by dalthviz** [comment]
Oh I see, I have not been able to reproduce this (at least on Windows) but maybe then is worthy to create a new issue related only to the pane size behavior @ccordoba12 @prof7bit ?

**Comment by ccordoba12** [comment]
> Oh I see, I have not been able to reproduce this (at least on Windows)

I've seen it frequently (but not all the time) when you have several consoles opened. And I think the problem is related to what I mentioned above, but I'm not really sure.

> but maybe then is worthy to create a new issue related only to the pane size behavior

Agreed. Please create one.

**Comment by dalthviz** [comment]
Opened issue #21596 to keep tracking the pane size change behavior :+1:
