### ISSUE TITLE
error about  afunction:input()

### ISSUE THREAD

**Issue by parhoun** [spyder-ide/spyder#18945]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
x1=input("salam")
print(x1)

this code doesn t work

**Comment by dalthviz** [comment]
Hi @parhoun , this seems like a duplicate of https://github.com/spyder-ide/spyder/issues/17616

There is an explanation of what to do at https://github.com/spyder-ide/spyder/issues/17616#issuecomment-1088750490 Let us know if that helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
