### ISSUE TITLE
Spyder version updated on anaconda.... but out of date already

### ISSUE THREAD

**Issue by Dan-Patterson** [spyder-ide/spyder#18967]
Anaconda default finally provided a much awaited update for those of us that cant use other means or channels to keep up with Spyder.

Version 5.2.2 (2022-01-21)   is now available via the main/default channel

current version 5.3.2 

Progress is being made but still leaving people in the dark as to what the criteria are for updates to be more timely.

[anaconda cloud community](https://community.anaconda.cloud/) 
    is totally useless to find out anything regarding Spyder (there are numerous threads, largely unanswered)

[anaconda issues](https://github.com/ContinuumIO/anaconda-issues/issues) 
    likewise useless

and a recent issue has commented on the problem, as some are aware
      [recent issue regarding spyder updates](https://github.com/ContinuumIO/anaconda-issues/issues/13001)

I know that you probably don't have any answers, but I will give a go anyway.

Regards

**Comment by NIST-Goldstein** [comment]
I have been trying to update/install from 5.1.5 to either 5.2.2 or 5.3.1 but after hours of no movement with either version am searching for some help.   We need some help with updating Anaconda.  Thanks for the links above, more help will be appreciated.

**Comment by NIST-Goldstein** [comment]
Thanks for getting back to me Carlos:

5.3.2 seems to be working well in the spyder-env that I created.  I would like to get it updated in the base environment as well but at least am able to debug in this other env.

Cordially,
Allen Goldstein
NIST
206-276-7347 (mobile)
***@***.***

**Comment by ccordoba12** [comment]
Ok, please try in your base env

    conda update anaconda
    conda install spyder=5.2.2

If that doesn't work, or conda gets stuck trying to resolve conflicting dependencies, then try

    conda remove spyder
    conda install spyder=5.2.2

**Comment by NIST-Goldstein** [comment]
T tried the basic install but was not brave enough to do the remove first.

I will give it a shot when I get a moment from debugging.

Cordially,
Allen Goldstein
NIST
206-276-7347 (mobile)
***@***.***

**Comment by NIST-Goldstein** [comment]
Hey Carlos:

I was reading some of you responses on the github issues, you are awesome:

I'm in the process of removing spyder from the base install and while doing that was looking up an issue I was having in the spyder-env install.  It is issue #15998 Spyder was unable to retrieve the value from the console.

After some research I see that the Pandas version did affect this for some users.  I note that my pandas in the base env was 1.4.2 and was removed when I removed Spyder.  Pandas in the spyder-env was never installed.

Do you know what version of Pandas is needed with spyder to make the variable browser function?

Cordially,
Allen Goldstein
NIST
206-276-7347 (mobile)
***@***.***

From: Goldstein, Allen R. (Fed)
Sent: Wednesday, August 10, 2022 12:02 PM
To: spyder-ide/spyder ***@***.***>; spyder-ide/spyder ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [spyder-ide/spyder] Spyder version updated on anaconda.... but out of date already (Issue #18967)

T tried the basic install but was not brave enough to do the remove first.

I will give it a shot when I get a moment from debugging.

Cordially,
Allen Goldstein
NIST
206-276-7347 (mobile)
***@***.******@***.***>

**Comment by NIST-Goldstein** [comment]
I was able to install Spyder=5.3.2 in the base environment after removal, but I am having the issue reported in https://github.com/spyder-ide/spyder/issues/13582 (this is in both environments).

Some folks had success with older pandas versions.  I will note that removing and spyder removed pandas (and alot of other items like numpy) but installing it did not replace pandas.

**Comment by ba-tno** [comment]
> but installing it did not replace pandas.
What does this mean? Could you please mention which commands you are using (`conda install...` etc...) that lead to your situation?

**Comment by NIST-Goldstein** [comment]
> What does this mean? Could you please mention which commands you are using (conda install... etc...) that lead to your situation?

> conda remove spyder
> conda install spyder=5.3

This removed pandas (and some other libraries).  The conda install spyder did not replace pandas or the other libs...  But I think we are on a tangent here.  It did install spyder 5.3 but now I'm onto another issue.

**Comment by ba-tno** [comment]
You can install pandas again after you install spyder with `conda install pandas`

**Comment by NIST-Goldstein** [comment]
>You can install pandas again after you install spyder with conda install pandas

Already done, but as I say, this is a tangent and not related to the issue.  The issue is that the only way to update Spyder in Anaconda seems to be to remove it first.  Unfortunately removing it also removes other libs that I may have wanted!

**Comment by ba-tno** [comment]
Sorry, I misunderstood the issue. With the limited information it's hard to say what the issue might be that you're running into.  Perhaps it's better to open a new issue with all the details included.

**Comment by Dan-Patterson** [comment]
With all the side traffic on this issue, the main concern is that Anaconda doesn't update to the current version.
Some of us don't have the option of using any other method or avenue of installation.  I am stuck with updating from the "defaults" channel and spyder's installers, conda-forge or pip installs aren't an option because of my upstream restrictions.

Something has happened in the last year or so to how Anaconda updates their packages and other avenues of notification, as I cited above, are useless.  @ccordoba12 I will close this, since it appears things are out of everyone's hands.  Best regards.

**Comment by ccordoba12** [comment]
> Something has happened in the last year or so to how Anaconda updates their packages

Yeah, we don't know what happened to them, but their support is terrible these days.

> @ccordoba12 I will close this, since it appears things are out of everyone's hands

Sure, no problem with that. And thanks for letting us know that at least it was updated to a more recent version.

**Comment by NIST-Goldstein** [comment]
I concur, it is an Anaconda problem, not a spyder problem
