### ISSUE TITLE
IPython ignore "Open IPython console here"

### ISSUE THREAD

**Issue by divideconcept** [spyder-ide/spyder#19003]
## Problem Description

When right-clicking a project folder and clicking "Open IPython console here", an IPython console is created.
But then when typing `pwd`, I always get the home/user directory instead of the current project directory.

### What steps reproduce the problem?

1. Right-click a project folder and click "Open IPython console here"
2. Type `pwd` in the IPython console

### What is the expected output? What do you see instead?

I see the home/user directory instead of the current project directory.
Reproducible both on macOS and Windows.

```

## Versions

* Spyder version: 5.3.2
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS 12, Windows 10

**Comment by ccordoba12** [comment]
I'll take care of this. This error was probably introduced by the changes I made to improve how we handle the current working directory.

**Comment by Thetoan1** [comment]
> ## Mô tả vấn đề
> Khi nhấp chuột phải vào thư mục dự án và nhấp vào "Mở bảng điều khiển IPython tại đây", bảng điều khiển IPython sẽ được tạo. Nhưng sau đó khi gõ `pwd`, tôi luôn nhận được thư mục chủ / người dùng thay vì thư mục dự án hiện tại.
> 
> ### Những bước tái tạo vấn đề?
> 1. Nhấp chuột phải vào thư mục dự án và nhấp vào "Mở bảng điều khiển IPython tại đây"
> 2. Nhập `pwd`vào bảng điều khiển IPython
> 
> ### Sản lượng dự kiến ​​là gì? Thay vào đó, bạn nhìn thấy gì?
> Tôi thấy thư mục chủ / người dùng thay vì thư mục dự án hiện tại. Có thể sao chép cả trên macOS và Windows.
> 
> ```
> 
> ## Versions
> 
> * Spyder version: 5.3.2
> * Python version: 
> * Qt version: 
> * PyQt version: 
> * Operating System name/version: macOS 12, Windows 10
> ```

pep-0654.rst

**Comment by Thetoan1** [comment]
CAM-Gerlach:pep-654-add-python-version

**Comment by Thetoan1** [comment]
Toan11

**Comment by Thetoan1** [comment]
#pep-0654.rst
