### ISSUE TITLE
py3compat.py problem

### ISSUE THREAD

**Issue by alexandrehorst** [spyder-ide/spyder#19007]
File "C:\Users\horstmann\Anaconda3\envs\spyder-cf\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

**Comment by dalthviz** [comment]
Hi @alexandrehorst , could you share here the information of your setup (OS, Spyder version, Python version, dependencies version, way you installed Spyder, etc)? Also where you running or working with some specific package when this happened?

Seems like this could be related with https://github.com/spyder-ide/spyder/issues/18342

Without any further info there is not much we can do to help, sorry :/

**Comment by alexandrehorst** [comment]
Hi Dalth, I solved this problem 5 min ago. It was a data format problem in my code. Thanks.

**Comment by hilalkaa** [comment]
Hello,
I have the same problem, I installed Spyder with anaconda , and using Python 3.9.12 and Spyder 5.3.3.

**Comment by dalthviz** [comment]
Hi @hilalkaa , please open a new issue with all the details of your setup (OS, packages dependencies versions, etc) and the steps to reproduce the error (example code that triggers the error, actions and order to do them to see the message error, etc). Let us know!
