### ISSUE TITLE
显示数据时看不全表格头部信息啊 

### ISSUE THREAD

**Issue by GZDXGeorge** [spyder-ide/spyder#19030]
### What steps will reproduce the problem?

When I try to see what my dataFrame data is,the columns 
of the data table couldn't be shown at all,at most half of the height of the characters.

**Comment by ccordoba12** [comment]
Hey @GZDXGeorge, thanks for reporting. Is the problem you're reporting similar to what's described on issue #18165?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by GZDXGeorge** [comment]
But which kind of response I had missed?I have reinstall it many times.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Carlos ***@***.***&gt;; 
发送时间: 2022年8月28日(星期天) 上午7:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [spyder-ide/spyder] 显示数据时看不全表格头部信息啊  (Issue #19030)





 
Closing due to lack of response.
