### ISSUE TITLE
Spyder Does Not Restart Kernel

### ISSUE THREAD

**Issue by kaleb-keny** [spyder-ide/spyder#19033]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Normally I can restart a kernel doing the combination of `ctrl + .`
This works fine for windows but does not do anything on linux ubuntu. Note that clicking manually under console restart kernel does work.

### What steps reproduce the problem?

1. `Ctrl + .`

### What is the expected output? What do you see instead?
Restarts kernel

### Paste Traceback/Error Below (if applicable)

```
NA
```

## Versions

* Spyder version: 5.2.2 None
* Python version: 3.7.13 64-bit
* Qt version: 5.12.1
* PyQt5 version: 5.12
* Operating System: Linux 5.15.0-46-generic
* 
### Dependencies

```
NA
```

**Comment by ccordoba12** [comment]
Hey @kaleb-keny, thanks for reporting. I think that keyboard shortcut is taken by your desktop environment. So you need to change it on it in order to have effect in Spyder.

**Comment by kaleb-keny** [comment]
🤔 is this linux specific, i remember i used to use that shortcut combination on windows without having to configure it?
if yes can you point me please to how to configure it, is this outside spyder you mean?

**Comment by ccordoba12** [comment]
[This](https://github.com/spyder-ide/spyder/issues/18839#issuecomment-1198524500) is a comment of a previous user which describes what they did to fix the problem. Let us know if it works for you.

**Comment by kaleb-keny** [comment]
thank you

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
