### ISSUE TITLE
Console looses focus while typing debugging commands on it

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#19042]
When debugging on the latest master, the console looses focus. To reproduce:
`%debug print()`
`s`
`s`
Every time the debugger is interacted with, the focus is stolen by the editor.

**Comment by impact27** [comment]
I found the `Maintain focus in the editor` option to solve the issue

**Comment by impact27** [comment]
But it is a bit strange that by default, if I type something in the debugger, the focus goes to the editor and doesn't stay in the console

**Comment by ccordoba12** [comment]
You're totally right @impact27! Thanks a lot for noticing and fixing it.
