### ISSUE TITLE
OSError: Library not loaded libomp

### ISSUE THREAD

**Issue by sjp00** [spyder-ide/spyder#19069]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi there, when I am trying to import forecasting models from the darts package I get the following error;

OSError: dlopen(/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

  

### What steps reproduce the problem?

1. I have installed the package darts successfully, however if I try import by: from darts.models import ExponentialSmoothing, I get an error. This occurs for all models, not just exponential smoothing. 
2. I have tried installing homebrew and using brew install libomp but that has not fixed the problem.
3. I have updated everything and uninstalled and reinstalled all the packages but nothing works.

### Paste Traceback/Error Below (if applicable)

```python-traceback

File "/var/folders/51/7qn6p5813zd3dw8p2c_t3btr0000gn/T/ipykernel_41355/3838417146.py", line 1, in <module>
    from darts.models import ExponentialSmoothing

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/darts/models/__init__.py", line 63, in <module>
    from darts.models.forecasting.gradient_boosted_model import LightGBMModel

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/darts/models/forecasting/gradient_boosted_model.py", line 13, in <module>
    import lightgbm as lgb

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/basic.py", line 110, in <module>
    _LIB = _load_lib()

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/basic.py", line 101, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)

  File "/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: dlopen(/Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so, 0x0006): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /Users/sp/opt/anaconda3/envs/augustrush/lib/python3.9/site-packages/lightgbm/lib_lightgbm.so
  Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)


```

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.12 64-bit
* Qt version: Qt 5.15.2
* PyQt version: PyQt5 5.15.7
* Operating System name/version: macOS Monterey version 12.3

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.2.1 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.9.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @sjp00, thanks for reporting. It seems the `lightgbm` package depends on `libomp`, but it can't find it in your system because it's not installed.

According to [this page](https://www.mathworks.com/help/coder/ug/install-openmp-library-on-macos-platform.html), you can install it with [Homebrew](https://brew.sh/). Let us know if that works for you.

**Comment by sjp00** [comment]
> Hey @sjp00, thanks for reporting. It seems the `lightgbm` package depends on `libomp`, but it can't find it in your system because it's not installed.
> 
> According to [this page](https://www.mathworks.com/help/coder/ug/install-openmp-library-on-macos-platform.html), you can install it with [Homebrew](https://brew.sh/). Let us know if that works for you.

Hi @ccordoba12, I have tried to do this and unfortunately it still does not work. I am new to all of this so not sure if I have done it correctly or if it is installed in the right directory? Below is the information of my libomp installation. I linked it to the 11.1 version because I read a few posts that said this was the way it worked for them. I have tried with the latest version and it still does not work. The result I get in Spyder is same as in my original post. I am very confused, I have emailed the darts package team and they do not know what is wrong and all of the fixes I have come across do not seem to work. 

Last login: Wed Aug 17 10:06:34 on ttys000
(base) sp@MacBook-Pro-3 ~ % conda activate aug
(aug) sp@MacBook-Pro-3 ~ % brew install libomp
Warning: libomp 14.0.6 is already installed.
The currently linked version is: 11.1.0
(aug) sp@MacBook-Pro-3 ~ % brew info libomp
libomp: stable 14.0.6 (bottled)
LLVM's OpenMP runtime library
https://openmp.llvm.org/
/opt/homebrew/Cellar/libomp/11.1.0 (9 files, 1.3MB) *
  Poured from bottle on 2022-08-16 at 16:07:15
/opt/homebrew/Cellar/libomp/14.0.6 (7 files, 1.6MB)
  Poured from bottle on 2022-08-16 at 09:40:17
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libomp.rb
License: MIT
==> Dependencies
Build: cmake ✔
(aug) sp@MacBook-Pro-3 ~ %

**Comment by ccordoba12** [comment]
Ok, please try to create a symlink between the `libomp.dylib` file located somewhere in `/opt/homebrew/Cellar/libomp/11.1.0` and one of this locations:

    Reason: tried: '/usr/local/opt/libomp/lib/libomp.dylib' (no such file), '/usr/local/lib/libomp.dylib' (no such file), '/usr/lib/libomp.dylib' (no such file)

so that `lightgbm` can find it.

(Please google how to create symlinks in a terminal to understand what that's all about. I don't have time to explain you that, sorry, because this is not a Spyder problem).

**Comment by ccordoba12** [comment]
Closing due to lack of response.
