### ISSUE TITLE
IPython console tab complete popup not accessible to mouse-click

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1908]
_From [wsu...@gmail.com](https://code.google.com/u/115225145614373588440/) on 2014-07-24T17:07:14Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  None (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.0.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. Open IPython console
2. Create some object \<someobject> which has attributes
3. Type "<someobject>." and press \<tab> to see popup list of options
4. Observe popup does respond to mouse scroll wheel
5. Click to select an entry OR click on the scrollbar (click anywhere, really)
6. Observe popup disappear

Normal python consoles do support mouse-clicks on tab complete popups. IPython consoles appear to lack this support.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1908_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-24T23:25:56Z_

I'm not seeing this problem on Linux. I'll check it on Windows tomorrow but please try to update Spyder to its 2.3.0 version to see if the problem persists.

**Labels:** OpSys-Windows Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [wsu...@gmail.com](https://code.google.com/u/115225145614373588440/) on 2014-08-27T13:11:32Z_

Just upgraded ->2.3.0 and yes, the issue persists. It must be a Windows-specific issue. Strange only IPython console is affected.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:57:49Z_

issue #2038 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:58:04Z_

**Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:10:53Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by vidartf** [comment]
I've just proposed a fix/workaround in jupyter/qtconsole#93.

**Comment by ccordoba12** [comment]
Thanks a lot for this! Closing as this is an upstream bug.
