### ISSUE TITLE
spyder-kernels missing in venv error

### ISSUE THREAD

**Issue by AndrewTsao** [spyder-ide/spyder#19127]
Hi, guys,

Why `spyder&45;kernels` here, not `spyder-kernels`. 

https://github.com/spyder-ide/spyder/blob/c0f446e0b0d46ccc9a99ee99163d6c668314a6bd/spyder/plugins/ipythonconsole/widgets/main_widget.py#L71

when I copy the tip in my terminal to install spyder-kernels, show errors below.

```bat
(.venv) U:\spyder>pip install spyder‑kernels==2.2.*
ERROR: Invalid requirement: 'spyder‑kernels==2.2.*'
```

**Comment by ccordoba12** [comment]
Hi @AndrewTsao, thanks for reporting. What Spyder version are you using?

I say it because the error you're reporting should be fixed in our latest version (5.3.2), but it seems you're using an older one.

**Comment by AndrewTsao** [comment]
Thanks for your reply.

You are right, I installed an old version 5.2.2, Because of I use python 3.6. 

I installed an new spyder 5.3.2. But I changed Python intepreter in Perference dialog box.  The Ipython Console is blank. I tested Python 3.6 and Python 3.8 virtualenvs.

Maybe another bug?

**Comment by ccordoba12** [comment]
@AndrewTsao, I don't understand what you mean by this

>  The Ipython Console is blank

Please post a screenshot to see what's happening in your case.
