### ISSUE TITLE
a problem with numpy.

### ISSUE THREAD

**Issue by lwq-star** [spyder-ide/spyder#19155]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have updated spyder to version 5.3.2, but there seems to be a problem with numpy.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "C:\Users\A1827\AppData\Local\Temp\ipykernel_1656\3185795297.py", line 1, in <cell line: 1>
    import rasterio

  File "D:\Application\anaconda\lib\site-packages\rasterio\__init__.py", line 17, in <module>
    from rasterio._base import gdal_version

  File "rasterio\_base.pyx", line 1, in init rasterio._base

  File "rasterio\_shim.pyx", line 1, in init rasterio._shim

AttributeError: module 'numpy' has no attribute 'dtype'

```

## Versions

* Spyder version: 5.3.2
* Python version: 3.9.13
* Qt version:  5.15.2
* PyQt5 version: 5.15.7
* Operating System name/version: windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.14.0 (OK)
keyring >=17.0.0              :  23.8.2 (OK)
nbconvert >=4.0               :  6.4.5 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.7.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  65.2.0 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.3.2;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.4.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.23.2 (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by dalthviz** [comment]
Hi @lwq-star thank you for the feedback! I think you need to update/reinstall `numpy`. As you can check in your list of optional dependencies `numpy` is showing a `NOK` (which means that the dependencies is somehow faulty). Probably if you try to run something like `import numpy` you will also get some traceback.

Could it be that when updating you mixed packages channels? Could you submit here the output of running `conda list` with the conda environment you are working activated?

Probably a way to prevent errors could be to create a new conda environment using only the conda-forge channel and installing there Spyder and the dependencies you need. From the traceback seems like you are using `rasterio` so you should run something like the following from an Anaconda prompt:

    conda create -n spyder-cf -c  conda-forge python=3.9.13 spyder rasterio
    conda activate spyder-cf
    spyder

Let us know if something of the above helps!

**Comment by lwq-star** [comment]
Yes, you are correct. I uninstalled numpy and then reinstalled it with no problem.
