### ISSUE TITLE
Spyder debugging doesn't work on Windows with Spyder standalone version and Tkinter graphics backend

### ISSUE THREAD

**Issue by rycoolcat** [spyder-ide/spyder#19174]
### What steps will reproduce the problem?

After Pressing Ctrl+F5 to start debugging, the following line appears in the console: !continue
But nothing happens. The console appears frozen and has to be restarted.

## Versions

* Spyder version: 5.3.2  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.7.2 (OK)
keyring >=17.0.0                     :  23.6.0 (OK)
nbconvert >=4.0                      :  6.5.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.12.0 (OK)
pylint >=2.5.0;<3.0                  :  2.14.4 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0             :  5.3.1 (OK)
qtpy >=2.1.0                         :  2.1.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  63.1.0 (OK)
sphinx >=0.6.6                       :  5.0.2 (OK)
spyder_kernels >=2.3.2;<2.4.0        :  2.3.2 (OK)
textdistance >=4.2.0                 :  4.3.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.0 (OK)

# Optional:
cython >=0.21                        :  0.29.30 (OK)
matplotlib >=3.0.0                   :  3.5.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.8.1 (OK)
sympy >=0.7.3                        :  1.10.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @rycoolcat, thanks for reporting. I really don't know what could causing your problem.

@impact27, do you have ideas about this?

**Comment by impact27** [comment]
What code are you debugging? I can reproduce with an infinite loop, for example:
```
import time
if False:
    a = 1 # Put a breakpoint here
while True:
    time.sleep(1)
```
Here the debugger would never reach the breakpoint, and the program would never stop.

**Comment by rycoolcat** [comment]
@impact27 Thanks for the  example. In my case, it doesn't really matter, what code I try to debug: even a single-line "hello-world" won't get its breakpoint reached.

**Comment by ccordoba12** [comment]
@rycoolcat, please try again after Spyder 5.3.3 is released next week and let us know. We fixed a couple of bugs in the last weeks that could solve this problem.

**Comment by HornetGuppy** [comment]
@ccordoba12 the issue seems to persist with 5.3.3 (Python 3.8.10 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Windows 10)

**Comment by impact27** [comment]
What happens if you try to interrupt the console (ctrl + c)?

**Comment by impact27** [comment]
Could you also try to enable/disable a few of the debugger settings to see if something disables this issue? (In preferences > iPython console > debugger)

**Comment by HornetGuppy** [comment]
When interrupted it froze after 'Exception in Tkinter callback' message, tried disabling options in debugger preferences but unfortunately did not make any difference..

**Comment by impact27** [comment]
What if you use another backend? ( preferences > iPython console > graphics > backend) and select inline or qt5

**Comment by impact27** [comment]
Also could you post the full error message you see?

**Comment by ccordoba12** [comment]
@dalthviz, could check what happens when you activate the Tkinter backend on our Windows application and then start a debugging session?

**Comment by HornetGuppy** [comment]
@impact27 switching to inline or qt5 seems to be working..thanks for the suggestion

**Comment by dalthviz** [comment]
Just in case, using the Tkinter backend and cliking Enter after entering debug mode causes the IPdb prompt to get stock. If I try to interrupt the kernel I got:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\dalth\AppData\Local\Programs\Spyder\pkgs\tkinter\__init__.py", line 1889, in __call__
    try:
KeyboardInterrupt
```

Checked with a conda based installation and seems like this issue doesn't happen there. As suggested by @impact27 a workaround for this is to change the graphics backend from Tkinter to something else (inline, qt5).

**Comment by ccordoba12** [comment]
Thanks @dalthviz for checking that. Could you run the same test in a Pyenv where all packages are installed with pip? It needs to be a Pyenv and a not a Conda env to check the Tkinter packages provided by other vendors (the conda ones seem ok according to what you said).

**Comment by ccordoba12** [comment]
When looking for an old issue, I found out that this problem was reported before on issue #17523, and we came to the same conclusion: the problem is the Tkinter backend.

So I'm closing this issue in favor of that one.
