### ISSUE TITLE
how to debug a server program

### ISSUE THREAD

**Issue by leavor** [spyder-ide/spyder#19186]
## Problem Description
Debug a server program, debug not work
For example breakpoints in callback functions, breakpoints will not work

![image](https://user-images.githubusercontent.com/1759365/186828607-2bf01ed0-bc7f-4dd0-a4e3-71814028518c.png)

## Example Code
```python
# -*- coding: utf-8 -*-
"""
created on: Fri Aug 26 11:19:08 2022
author: levor
"""
from dash import Dash, dcc, html, Input, Output,callback
import numpy as np
import pandas as pd
import plotly.express as px
app = Dash(__name__)

app.layout = html.Div([
    html.Button(
        'Click',
        id='update_figure',
        style={
            'width':'200px',
            'height':'50px',
            'marginTop':'40px',
            'marginLeft':'50px',
        }
    ),
    html.Br(),
    dcc.Graph(id='graph',config={'displayModeBar': False})
])

server = app.server

@callback(
    Output('graph','figure'),
    Input('update_figure','n_clicks'),
)
def click_update_figure(nclick):
    """
    callback function
    """
    data_x = list('ABCDE')
    data_y = np.random.randint(0,high=100,size=5)
    df = pd.DataFrame({'x':data_x,'y':data_y})
    fig = px.bar(df,x='x',y='y',width=480,height=340)
    return fig
if __name__ == '__main__':
    app.run_server(host='0.0.0.0', port=9000, debug=True)
```
Debug (Ctrl+F5) the code, open web "http://127.0.0.1:9000/", click button, breakpoint not work
## Versions
* Spyder version: 5.3.1 None
* Python version: 3.9.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.23.1 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by dalthviz** [comment]
Hi @leavor thank you for the feedback! I was checking and seems like you will need to set the breakpoints using the `breakpoint()` built-in (since the app doesn't run in the Spyder main thread) and also without setting the `debug=True` kwarg.

With that, each time I clicked the button on the browser the IPdb prompt showed over Spyder:

![imagen](https://user-images.githubusercontent.com/16781833/186974041-0284eb7d-4743-4ae9-9dda-d4bd50e2afbd.png)

Calling `continue` (`c`) from the IPdb prompt builds the graph in the browser and started showing again the server log

Let us know if that helps!

**Comment by leavor** [comment]
> Hi @leavor thank you for the feedback! I was checking and seems like you will need to set the breakpoints using the `breakpoint()` built-in (since the app doesn't run in the Spyder main thread) and also without setting the `debug=True` kwarg and using the normal run action (`F5` or the green arrow in the toolbar)
> 
> With that, each time I clicked the button on the browser the IPdb prompt showed over Spyder:
> 
> ![imagen](https://user-images.githubusercontent.com/16781833/186974041-0284eb7d-4743-4ae9-9dda-d4bd50e2afbd.png)
> 
> Calling `continue` (`c`) from the IPdb prompt builds the graph in the browser and started showing again the server log
> 
> Let us know if that helps!

it works, thank you!
