### ISSUE TITLE
Folders will disappear from the Pythonpath manager when they are deleted, but remain in `sys.path`

### ISSUE THREAD

**Issue by rjyunis** [spyder-ide/spyder#19182]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Folders will disappear from the PYTHONPATH manager when they are deleted, but remain in sys.path. 

As far as I know, that means there is no way to remove that value from your sys.path until you re-create the directory and remove it from the manager. 

### What steps reproduce the problem?

1. Add a folder via PYTHONPATH manager
2. Delete the folder
3. Restart Spyder
4. Confirm it has disappeared from the manager
5. Confirm it is still present in sys.path
6. Add the folder back
7. Restart Spyder 
8. Confirm the folder has returned to the manager

### What is the expected output? What do you see instead?

I would expect that the folder remains in the manager, but it does not. Maybe also a message saying that a user-defined PYTHONPATH addition no longer exists with a prompt to remove or update it. 

### Paste Traceback/Error Below (if applicable)

n/a

## Versions

* Spyder version: 5.3.2
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10

### Dependencies

n/a

**Comment by ccordoba12** [comment]
Hey @rjyunis, thanks for reporting. We'll take of this in our next major version (Spyder 6) because we plan to improve our support PYTHONPATH manager significantly in that version.

**Comment by ccordoba12** [comment]
This should be fixed now in our latest version (5.5.0), so please update.
