### ISSUE TITLE
a=input("No")
print(a**0.5)

### ISSUE THREAD

**Issue by Sruffy** [spyder-ide/spyder#19193]
### What steps will reproduce the problem?

i cant run the output kernel as it shows internal error

**Comment by ccordoba12** [comment]
Hey @Sruffy, thanks for reporting. This problem is fixed in our latest version available in Anaconda. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2
