### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by MstFox8** [spyder-ide/spyder#19209]
### What steps will reproduce the problem?

import time
pin = str(input("Enter a pin: "))
ftime = time.time()
testpin = "0000"
for _ in range(9999):
    testpin = str(testpin)
    testpin.ljust(4,"0")
    if testpin == pin:
        time = round(time.time() - ftime, 2)
        print(f"It's finished. It only took {time} seconds")
        break
    else:
        testpin = int(testpin)
        testpin += 1

**Comment by rhkarls** [comment]
There has been some issues with the `input()` function for some older versions of Spyder. What version of Spyder are you running? If you are running Spyder from the Anaconda distribution, update to the latest available there which is 5.2.2. Close Spyder, open the Anaconda Prompt and run this command: `conda install spyder=5.2.2`. If you are using the installers or conda-forge the latest is 5.3.2.

**Comment by ccordoba12** [comment]
@MstFox8, please follow @rhkarls advice and you'll be fine.
