### ISSUE TITLE
After opening the spyder5.32 operation interface, spyder5.32 automatically closes

### ISSUE THREAD

**Issue by hongweiao** [spyder-ide/spyder#19213]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I downloaded and installed spyder5.3.2, but when opening spyder it shows the interface for a few seconds and then disappear.
![a9eccdf1981125c953f510196e93563](https://user-images.githubusercontent.com/112298604/187079160-d484dd1a-bdc7-4499-a41b-199a105e7285.jpg)

### What steps reproduce the problem?

1. open the spyder
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.2
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version: windows11

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @hongweiao, thanks for reporting. How did you install Spyder?

**Comment by hongweiao** [comment]
@ccordoba12 Hi! thank your replying! I downloaded the Installation package from this wedsite https://www.spyder-ide.org/ and I just followed the step to install the spyder

**Comment by ccordoba12** [comment]
Ok, no problem, that's fine. Please download our latest version (5.3.3), which was released yesterday, to see if that helps.

You can find it here:

https://github.com/spyder-ide/spyder/releases

**Comment by ccordoba12** [comment]
Closing due to lack of response.
