### ISSUE TITLE
"Scroll past the end" is not translated correctly in French (Editor)

### ISSUE THREAD

**Issue by NotaCS** [spyder-ide/spyder#19232]
Hi, thanks for the great work you are doing with Spyder!

I don't know if it's OK to post this here, but I was thinking of a feature that would improve user experience (or at least mine haha):
it would be nice if it were possible to scroll down past the last line in the editor so that the last line can be in the middle of the screen. This can usually be achieved by adding a lot of empty lines on the script, but because I use the "autoPEP8 formatting on save" option, these empty lines are automatically removed.

That's just an idea, feel free to ignore me.
Have a nice day!

**Comment by ccordoba12** [comment]
Hey @NotaCS, thanks for your kind words! You said:

> it would be nice if it were possible to scroll down past the last line in the editor so that the last line can be in the middle of the screen

This option is already available, but it's disabled by default. To enable it you need to go to the menu

    Tools > Preferences > Editor > Display

and the enable it:

![image](https://user-images.githubusercontent.com/365293/187475818-769137d0-1224-40d3-96b0-dc360495ea0d.png)

Let us know if it works for you.

**Comment by NotaCS** [comment]
Ooooh, yes thank you for the swift and on-point answer!

I missed that option when I looked for it, sorry.
Just so you know, I'm using the French UI and the translation for that option is a little confusing: it's written "Faites défiler la fin", which would translate to "Scroll the end". I would replace it with "Défiler après la fin", or "Faire défiler au-delà du bas de page" (clearer but a little bit wordy, that's French for you...).

But now it works exactly as I hoped it would, that's great!
Cheers,
Victor

**Comment by NotaCS** [comment]
Sure, that's fine by me, I'll be glad to give a hand!

**Comment by ccordoba12** [comment]
I just saw that you updated that translation. Thanks for your help @NotaCS!

**Comment by NotaCS** [comment]
Glad I could be of help!
Anyways, there is no one perfect translation for this kind of thing. It's always hard to translate brief, concise English into French without writing a whole paragraph.

**Comment by ccordoba12** [comment]
Right, we have a similar problem in Spanish.
