### ISSUE TITLE
self._show_prompt(prompt, newline=False, separator=False)TypeError: _show_prompt() got an unexpected keyword argument 'separator'

### ISSUE THREAD

**Issue by desmondzvinamano** [spyder-ide/spyder#19247]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @desmondzvinamano, thanks for reporting. This problem is fixed in the latest Spyder version available in Anaconda. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2
