### ISSUE TITLE
Spyder internal error

### ISSUE THREAD

**Issue by arpanbanerjee** [spyder-ide/spyder#19246]
### What steps will reproduce the problem?

1. Open Spyder
2. Open new file
3. write the following code: 
	num_of_visitors = input()
4. save the file. I used the name RecordBreakingDays.py
5. Run the file. The Issue Reporter pops up saying Spyder has encountered an internal problem.

**Comment by ccordoba12** [comment]
Hey @arpanbanerjee, thanks for reporting. This problem is fixed in the latest Spyder version available in Anaconda. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2
