### ISSUE TITLE
doesnt fuckign wrok fix it iodots

### ISSUE THREAD

**Issue by SkyGamer911** [spyder-ide/spyder#19262]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by SkyGamer911** [comment]
hello nigger?

**Comment by ccordoba12** [comment]
Closing because this is empty. Please refrain from delivering insults for next time or you'll be banned from our organization for a week.

**Comment by SkyGamer911** [comment]
I meant go fuck yourself nigger. Like a blackfaced African scummy dumbass
Slaves was a good thing. You niggers will never be like white normal
people. You clean my toilet and mop my floor 🤣😅🤣

tor. 1. sep. 2022, 14:23 skrev Carlos Cordoba ***@***.***>:
