### ISSUE TITLE
unexpectes error

### ISSUE THREAD

**Issue by Alejandro58581** [spyder-ide/spyder#19300]
### What steps will reproduce the problem?

When I try to compile a simple code using a re(regular expresion) library the issue reporter shows this window

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\alega\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\alega\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\alega\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\alega\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2413, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.4.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.1 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by Alejandro58581** [comment]
![image](https://user-images.githubusercontent.com/82003215/188294567-c65e9d31-3181-4e3b-a76e-04c21ec65ea9.png)
I can´t update spyder, something goes wrong

**Comment by Alejandro58581** [comment]
Also when I tried to update spyder and got the same error I closed the anaconda prompt and opened anaconda do not open anymore

**Comment by ccordoba12** [comment]
@Alejandro58581, this is the full error you're getting in the Anaconda Prompt?

**Comment by Alejandro58581** [comment]
No. But the next line said that the process will take time and if want  to exit press Ctrl+C, i stopped the update because after 20 minutes nothing had happened and my laptop started to had performance problems.

After this anaconda doesn't open and have to use the windows search to open spyder or Jupiter.

Also the original message error seems to be caused by a input sentence but I don't know what to do.

Sorry for my english and my null programming skills.

**Comment by ccordoba12** [comment]
> No. But the next line said that the process will take time and if want to exit press Ctrl+C, i stopped the update because after 20 minutes nothing had happened and my laptop started to had performance problems.
>
> After this anaconda doesn't open and have to use the windows search to open spyder or Jupiter.

Ok, it seems you're installation is broken now, so please remove and reinstall Anaconda following the instructions in [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs).

> Also the original message error seems to be caused by a input sentence but I don't know what to do.

To fix it you only need to update Spyder.

> Sorry for my english and my null programming skills.

Don't worry about it, you write quite clear English.

**Comment by Alejandro58581** [comment]
I uninstall and install anaconda but is the same. I have to open spyder with the windows search because anaconda doesn't open and a window on spyder says that I need to update to the version 5.2.2 again

I feel frustrated.

**Comment by ccordoba12** [comment]
I understand, but did you follow the instructions in our video to uninstall and reinstall? That could help you.

**Comment by Alejandro58581** [comment]
Hello again.

After following the steps and uninstall and install are the same. Anaconda doesn´t open and spyder wants to update to the 5.2.2 version. I execute the command:

`conda install spyder=5.2.2`

But after executing for an hour and saying `Examinating for conflict package ..` there are some screenshots:
![image](https://user-images.githubusercontent.com/82003215/188519605-982314c1-925f-45d1-b7c3-1f853e4f3762.png)
![image](https://user-images.githubusercontent.com/82003215/188519630-8df528ff-4d6e-4f95-842d-11be7686cbab.png)
![image](https://user-images.githubusercontent.com/82003215/188519654-7ef01240-8371-42c2-bd27-79d7edbec041.png)
![image](https://user-images.githubusercontent.com/82003215/188519700-4b550edf-6862-4466-9586-27a35a2e4c76.png)

There are more but with the same message

Thanks for your help

**Comment by ccordoba12** [comment]
Did you run

    conda update anaconda

before running

    conda install spyder=5.2.2

?

**Comment by Alejandro58581** [comment]
Thanks for you patience carlos it's worked. Anaconda doesn't open yet but I can use the windows search bar. 

Thank you so much

**Comment by ccordoba12** [comment]
Great! I'm really glad you were able to finally make Spyder work.
