### ISSUE TITLE
intractive mode problem

### ISSUE THREAD

**Issue by hasusb** [spyder-ide/spyder#19308]
### What steps will reproduce the problem?

num1=int(input("the first no.:"))
num2=int(input("the second no.:"))
c=num1*num2
print("multiplication of two no.s.:",c)

not shown in intractive mode

**Comment by hasusb** [comment]
num1=int(input("the first no.:"))
num2=int(input("the second no.:"))
c=num1*num2
print("multiplication of two no.s.:",c)

it was not shown in intractive mode

**Comment by ccordoba12** [comment]
Hey @hasusb, thanks for reporting. This problem is fixed in our latest version available in Anaconda. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2
