### ISSUE TITLE
Please Help!!!!!

### ISSUE THREAD

**Issue by Satoshi-Nakamoto69** [spyder-ide/spyder#19316]
### What steps will reproduce the problem?

I am trying to run a simple program... please help me fix spyder? I have tried everything

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\Mitchell\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Mitchell\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\Mitchell\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\Mitchell\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by Satoshi-Nakamoto69** [comment]
This did not work?

**Comment by ccordoba12** [comment]
Hey @Satoshi-Nakamoto69, what do you mean by that?

**Comment by Satoshi-Nakamoto69** [comment]
I am currently unable to use Spyder; when I ran those commands in the
terminal (through anaconda navigator), it executed, completed, and said
done, but then inside of anaconda navigator, the Spyder application didn't
say 5.2.2.

I still keep getting the same problem when I try to run my code. I can run
the code on any other IDE such as replit or visual studio code, but for
some reason, Spyder seems to be inoperable.

I have tried uninstalling and reinstalling and going all the way into the
AppData files to ensure no remnants were left over after the uninstall.
Still, even that did not resolve the issue with a fresh install.

I just don't know what else to try. I'm looking for help troubleshooting
this further because I want to understand the issue better and be able to
use the Spyder IDE.

Any help you can provide will be much appreciated,

**Comment by Satoshi-Nakamoto69** [comment]
Sure thing, I appreciate your support

when I run "conda update anaconda" on my desktop, I get this

[image: image.png]

This seems like a permissions issue

I don't have any unique configurations in my win 11 environment that I'm
aware of

[image: image.png]

Let me additionally share this:

Spyder was working fine even without being 5.2.2, but I don't know what
changed that caused the IDE to start throwing this error on every single
run iteration

    Traceback (most recent call last):
  File
"C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py",
line 138, in _dispatch
    handler(msg)
  File
"C:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py",
line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File
"C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py",
line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback,
password=msg['content']['password'])
  File
"C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\console_widget.py",
line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'

[image: image.png]

Notice that the code should run fine; it works on replit and visual studio
code

I would like to be able to utilize Spyder, so I'm willing to try pretty
much anything to get this resolved

My instructor stated I needed to uninstall both Anaconda Nav and Spyder and
then only reinstall Spyder by itself at this link:
https://www.spyder-ide.org/

I have not tried this yet

Please advise,

**Comment by ccordoba12** [comment]
@Satoshi-Nakamoto69, unfortunately you can't send images to Github via email. Instead, you need to upload them directly here by dragging and dropping them when writing your messages.

**Comment by Satoshi-Nakamoto69** [comment]
ahh, sorry, just uploaded the three images from the previous correspondence

![unnamed (1)](https://user-images.githubusercontent.com/55071104/188628563-91a6b342-1d42-4025-8ccf-9376ac52b123.png)
![unnamed](https://user-images.githubusercontent.com/55071104/188628570-d8e79421-f40a-4705-99a7-cd4938aed3e9.png)
![unnamed (2)](https://user-images.githubusercontent.com/55071104/188628574-dba180db-cb0a-4641-aca4-334f41c31e5d.png)

**Comment by Satoshi-Nakamoto69** [comment]
Hello,

Just wondering if there is any update on this? I submitted several images
as a follow-up. Please let me know if there is anything you would like me
to try next.

**Comment by ccordoba12** [comment]
Sorry for the delay, I was busy with other things. From your second screenshot (the Powershell one), it seems you only ran

    conda update anaconda

but you didn't run

    conda install spyder=5.2.2

If that's the case, please run that command, post the screenshot here and try again.

**Comment by Satoshi-Nakamoto69** [comment]
No worries, thank you for following up. 

I ran the second statement and received the following output from Powershell:

![Screenshot 2022-09-11 134330](https://user-images.githubusercontent.com/55071104/189543928-4f96f222-107a-485c-af4c-76e71b9a1eba.png)

After this finished, I opened Spyder from the Anaconda Navigator and tried to run my program again; moreover, it still will not run despite anything wrong with the code and displays the same internal error message I screenshotted before. 

What I found interesting is that when I open Spyder, it still comes up and prompts me to update Spyder to 5.2.2, even though that was what the above-listed statement in PowerShell was supposed to achieve.

**Comment by Satoshi-Nakamoto69** [comment]
Also, do you mind re-opening this ticket since the fix the bot suggested isn't working and this is still an ongoing thread? It currently says closed, but the issue wasn't actually resolved.

**Comment by ccordoba12** [comment]
> Also, do you mind re-opening this ticket since the fix the bot suggested isn't working and this is still an ongoing thread?

I'm sorry but this is not our problem, it's a problem with Anaconda, and we're trying to help you in good faith. Since I don't have more time for this and I don't know what happens with your installation, I recommend you to report this issue with the Anaconda team and see if they can help you:

https://github.com/ContinuumIO/anaconda-issues

Finally, you can sort out this by downloading and installing our Windows, application, which you can find here:

https://github.com/spyder-ide/spyder/releases

That doesn't have the bug with input and won't give you further troubles.

**Comment by Satoshi-Nakamoto69** [comment]
Carlos, I understand what you're saying, but the issue specifically only
occurs within Spyder? It literally says "SPYDER has encountered an internal
problem". I have not had any issues with Anaconda..

Is there no one else that can help troubleshoot this?

Also, are you suggesting that I will need to uninstall Anaconda Navigator
and all of the system files associated with it before installing Spyder
alone? If so, is there a documented process for this that I can find
somewhere on your support pages?

Moreover, it doesn't make sense that your bot auto closes issues after
saying to run the commands when the commands in PowerShell don't work, and
then you just follow up with "it's not your issue"... if it's truly not
your issue why not just have the bot state that it's an issue with Anaconda
and then issue the process to the user so that they can still use Spyder...
