### ISSUE TITLE
image0 error when running newest version of Spyder on Ubuntu Anaconda Env

### ISSUE THREAD

**Issue by shasha-aiq** [spyder-ide/spyder#19325]
### What steps will reproduce the problem?

Not sure what the issues is. I used conda install spyder-terminal -c spyder-ide and then launched spyder. This issue reporter interface popped up and now I'm filling it out. 

Original issue was Image0 error when trying to update spyder3 to spyder5 (the latest version) - everything crapped out and there was no support online so I've had to create a new environment with an older version of spyder. 

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/home/shasha/anaconda3/envs/dl_env/lib/python3.8/site-packages/spyder_terminal/widgets/main_widget.py", line 303, in __wait_server_to_start
    self.create_new_term(give_focus=False)
  File "/home/shasha/anaconda3/envs/dl_env/lib/python3.8/site-packages/spyder_terminal/widgets/main_widget.py", line 360, in create_new_term
    self, self.port, path=path, font=self.font.family(),
AttributeError: 'NoneType' object has no attribute 'family'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.8.10
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.4.0-124-generic

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  8.4.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.15.0 (OK)
keyring >=17.0.0              :  23.9.0 (OK)
nbconvert >=4.0               :  7.0.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.2 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.6.0 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.4.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=17                      :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.23.0 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @shasha-aiq, thanks for reporting. If you want to use Spyder-terminal, you need to install that package and Spyder from Conda-forge, like this

    conda create -n spyder-env spyder spyder-terminal
    conda activate spyder-env
    spyder

Let us know if that works for you.

**Comment by shasha-aiq** [comment]
When I do

“conda create -n spyder_env spyder spyder-terminal”

I get a Packages not found error: Spyder-terminal

Any other suggestions please?


—
Shasha Yeung

Biomedical Engineering, PhD.
AIQ Australia Pty Ltd
Email: ***@***.******@***.***>
Phone: +61-455-572-254
Website: www.aiq-solutions.com




On Sep 6, 2022, at 12:39 AM, Carlos Cordoba ***@***.******@***.***>> wrote:



Hey @shasha-aiq<https://link.edgepilot.com/s/7531736a/ij96i4nNek2lwklUIt1GyQ?u=https://github.com/shasha-aiq>, thanks for reporting. If you want to use Spyder-terminal, you need to install that package and Spyder from Conda-forge, like this

conda create -n spyder-env spyder spyder-terminal
conda activate spyder-env
spyder


Let us know if that works for you.

**Comment by ccordoba12** [comment]
> I get a Packages not found error: Spyder-terminal
> 
> Any other suggestions please?

It seems you're introducing the package name capitalized. Please write the command without any capital letter.

**Comment by shasha-aiq** [comment]
Thanks for the suggestion. Issues wasn’t with a capital, this command fixed it for me:

conda create -n spyder_env -c conda-forge python=3.8.10 spyder=5.1.5 spyder-terminal





On Sep 6, 2022, at 12:56 PM, Carlos Cordoba ***@***.******@***.***>> wrote:



I get a Packages not found error: Spyder-terminal

Any other suggestions please?

It seems you're introducing the package name capitalized. Please write the command without any capital letter.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. It's good to know that Spyder is working for you now. although you should be able to use a more recent version.

**Comment by ccordoba12** [comment]
Closing because this solved now.
