### ISSUE TITLE
Python version 3.4 required, which was not found in the Registry

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1932]
_From [jr_lor...@stny.rr.com](https://code.google.com/u/101963565883901711330/) on 2014-08-12T15:30:35Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1.New install of Python 3.4 64 Bit on Windows 7 SP1
2.When installing Spyder 3.4 64 bit I get the error that the registry entry for Python 3.4 not found. 3. 

What is the expected output? What do you see instead?

 System desktop unresponsive. BRS What version of the product are you using? On what operating system? Window 7 64bit sp1 AMD quad 3.6, 8g of memory 
Python 3.4.1, Spyder-2.3.0.win-amd-py64-py3.4.exe 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1932_

**Comment by spyder-issues-migrator** [comment]
_From [jr_lor...@stny.rr.com](https://code.google.com/u/101963565883901711330/) on 2014-08-12T13:33:40Z_

PS Python works ok.

**Comment by spyder-issues-migrator** [comment]
_From [jr_lor...@stny.rr.com](https://code.google.com/u/101963565883901711330/) on 2014-08-13T10:55:50Z_

I uninstalled Python and re-installed with a fresh copy.
Spyder now installed correctly.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-13T11:00:08Z_

Ok, great!

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [android....@gmail.com](https://code.google.com/u/100864648954163226526/) on 2015-02-07T04:20:46Z_

I have the same problem.  I have Python3.4.2 and spyder-amd64 2.3.2.

**Comment by rilut** [comment]
I have the same problem too
I have Python 3.4.0 and spyder-2.3.2.amd64-py3.4

**Comment by ccordoba12** [comment]
@stonebig could you check this one please? I don't know if it's a problem with our installers...

**Comment by stonebig** [comment]
Hi @rilut 

Looking at your  description of your configuration:

You are double bleeding edge installation: 3.4.3rc1 + Windows 10 

# Checking if the SPyder installer is the issue 
You must try the same thing with Christoph Gohlke similar installer:
- download the 64 bit packages of Winpython 2014-12 release:
http://sourceforge.net/projects/stonebig.u/files/Do_It_Yourself/Winpython_2014-12/basedir34/packages.win-amd64.zip/download
- unzip it, 
- pick and install the `spyder-2.3.2.amd64-py3.4.exe` that was in it.

==> If it works, we may conclude spyder-provided installer has a problem.

If it doesn't work either, you may consider experimenting with a .whl package from Christoph Gohlke:
- download spyder from http://www.lfd.uci.edu/~gohlke/pythonlibs/#spyder 
- place it in `c:\toto` directory (for example)
- install it via `pip install c:\toto\spyder‑2.3.2‑py2.py3‑none‑any.whl`

==> If it works, we may conclude spyder-provided installer should shift to `.whl` format.

If it doesn't work either...., you may then inquire for us to see if Windows10 has a chance to work:
- try install a recent Anaconda or a recent Winpython,
- check if it works better.


==> If it works, we may conclude Windows 10 is a pain in the installers.

==> If it doesn't work, we may conclude that this `Windows 10 TP` has a problem.

**Comment by stonebig** [comment]
Python 3.4.3 final is out.

**Comment by rilut** [comment]
@stonebig Thanks, I updated to 3.4.3 final

![spyder-github](https://cloud.githubusercontent.com/assets/1331389/6387466/24c368ca-bdbe-11e4-938d-e1cbfea95860.PNG)
The github installer failed to install

![spyder-zip](https://cloud.githubusercontent.com/assets/1331389/6387467/24d4d89e-bdbe-11e4-965c-abd56f6136ca.PNG)
The zip one installed successfully (yes, I haven't get Spyder to run because I hadn't satisfy its dependencies).

By the way, yesterday I also installed NumPy & SciPy with Gohlke's installer (.exe installer because it's an old November 2014 installer) and they work just fine
