### ISSUE TITLE
if elif progrme

### ISSUE THREAD

**Issue by madanenikalyan** [spyder-ide/spyder#19326]
### What steps will reproduce the problem?

age=int(input("Enter the age: "))
if (age>=18);
print("You are eligible to drive)

**Comment by ccordoba12** [comment]
Hey @madanenikalyan, thanks for reporting. This problem is fixed in our latest version available in Anaconda. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2

**Comment by madanenikalyan** [comment]
Thank you sir /madam
