### ISSUE TITLE
Spyder hangs when trying to save a new Cython file if "Autoformat files on save" is selected

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#19344]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Saving a new Cython file causes Spyder to hang when autoformat on save is selected, with both autopep8 and black formatters.

### What steps reproduce the problem?

1. Reset spyder (`spyder --reset`)
2. Open spyder
3. Open preferences and select "Autoformat files on save"
4. Open a new file (Ctrl-N)
5. Type a Cython script; I used:
```python
cdef dummy():
    pass
```
7. Try to save the file, for example as `testing.pyx`.

### What is the expected output? What do you see instead?

Would expect it to save.  Instead, the save hangs (spinning dots icon above editing window just keeps spinning).  It can only be stopped by closing the editing window and saying "No" to the question of saving changes.

Interestingly, the same thing happens if saving a blank file as `untitled0.pyx`, but not if saving the above file as `untitled0.py`.  There is no problem if an existing `.pyx` file is opened and saved.

## Versions

* Spyder version: 5.3.3
* Python version: 5.10.6 (on Debian), bundled Python on macOS
* Qt version: 
* PyQt version: 
* Operating System name/version: Debian GNU/Linux testing; macOS Catalina

**Comment by dalthviz** [comment]
Hi @juliangilbey thanks for the feedback and steps! Just in case, I was able to reproduce this on Windows with the standalone installer for Spyder 5.3.3 too.

We will check a fix for this in a future release :+1:

**Comment by juliangilbey** [comment]
Pleasure! It took a while to track it down, but I got there...

**Comment by dalthviz** [comment]
Just in case, I was checking and seems like this is related to https://github.com/spyder-ide/spyder/issues/16166

**Comment by juliangilbey** [comment]
> Just in case, I was checking and seems like this is related to #16166

Good spot! And thanks for fixing.
