### ISSUE TITLE
Load local module dependencies on remote kernel

### ISSUE THREAD

**Issue by korbcode** [spyder-ide/spyder#19348]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I connected Spyder to an existing remote kernel on a Ubuntu EC2 Instance. This worked. I can run code in this console.

However, the module I run tries to import other custom modules from the module directory. This gives an ModuleNotFoundError.

Already asked here: https://stackoverflow.com/questions/73565579/spyder-5-loading-custom-modules-on-existing-remote-kernel

### What steps reproduce the problem?

1. Run module that imports local module dependencies
2. Do the same run in Remote Kernel Console
3. More specifically, run main.py of the follwing two modules:

#main.py:
from custom_utils import calc_score
if __name__ == '__main__':
    print(calc_score(2))
#end of main.py

#custom_utils:
def calc_score(x):
    y = (x^3 -2 ) / 1.5
    return y
#end of custom_utils

### What is the expected output? What do you see instead?
#Expected / Local: 
runfile('C:/dev/local_repo/main.py', wdir='C:/dev/local_repo')
2.0

#Instead / Remote Kernel:
runfile('C:/dev/local_repo/main.py', wdir='C:/dev/local_repo')
Working directory C:/dev/local_repo doesn't exist.

Traceback (most recent call last):

File "/home/ubuntu/.local/lib/python3.10/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
exec(code, globals, locals)

File "/home/ubuntu/C:/dev/local_repo/main.py", line 6, in <module>
from custom_utils import calc_score

ModuleNotFoundError: No module named 'custom_utils'

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.3.0
* Python version: Python 3.9.13 64-bit
* Qt version: Qt 5.15.2
* PyQt version: PyQt5 5.15.7
* Operating System name/version: Windows 10

### Dependencies

# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.15.0 (OK)
keyring >=17.0.0              :  23.8.2 (OK)
nbconvert >=4.0               :  7.0.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0                :  2.15.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.2 (OK)
qtpy >=2.0.1                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  58.1.0 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.3.0;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.4.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=17                      :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.3 (OK)
numpy >=1.7                   :  1.23.2 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  None (NOK)

**Comment by ccordoba12** [comment]
Hey @korbcode, thanks for reporting. You need to copy/paste local modules that you're importing in your code to the remote machine for it to work. I think there's little we could about it in Spyder because it's the way Python works.

Please try that and let us know if it works for you.
