### ISSUE TITLE
`flush_std` is spamming Spyder-kernels

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#19355]
## Problem Description
There is a `flush_std` message sent to the kernel every second, preventing the kernel from going to sleep. I think given that this solves a minor issue, only flushing after the execution is done would be sufficient. I worry that this behaviour negatively impacts spyder energy performances.

The alternatives are:
 - only flush after execution
 - poll during execution every X seconds

I would be in favour of the first approach, but what do you think @spyder-ide/core-developers ?

**Comment by ccordoba12** [comment]
> I would be in favour of the first approach

I'm ok with that.

I have a couple of questions about this:

1. Should we address this in the `5.x` branch? It seems important enough for that, right?
2. Could this be causing issue #19026?

**Comment by dalthviz** [comment]
Could removing the calls for `flush_std` cause things that keep running and generate output to not show the output in the console? Like the server log of a flask app for example?

If that is unrelated then :+1: 

It could be interesting to understand why that was working like that (calling repetitly `flush_std`) 🤔 but indeed seems like either way the current approach is not a correct one and could be quite resource intensive.

**Comment by impact27** [comment]
It is possible some things will not be printed if this is changed unless a command is run. Not the python code but c code could be writing to the underlying cout instead of using the sockets

**Comment by impact27** [comment]
The idea would be to flush the underlying cout and cert at the end of every commands instead of every second like now

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder/pull/19411 fixes this but only for master. i could make a light version for 5.x. what do you think @ccordoba12

**Comment by ccordoba12** [comment]
>  i could make a light version for 5.x. what do you think @ccordoba12

That would be great. Thanks for thinking about it @impact27!
