### ISSUE TITLE
Alt key pressed moves focus to the scrollbar (the left one) when focused on auto complete

### ISSUE THREAD

**Issue by cw9000** [spyder-ide/spyder#19372]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
My end goal is to be able to use my KDE shortcut alt+m to trigger a down event while the auto-complete box is open
so that I can choose/browse the auto-complete box.  I use the alt+m shortcut in all applications for down, and even use it successfully in spyder when just typing in the editor.

However when I trigger the auto-complete box then try to go down in the list with alt+m, as soon as I hit the "alt" key the box disappears and I see the focus go to the first scrollbar to the right (seems to be the "scroll-to" scrollbar).  I then have to remind myself of that, then backspace and trigger the auto-complete again, and then use the actual "down arrow" key.  Yes, yes, first world problems.

So the problem is that the "alt" key loses the focus of the auto-complete box.

### What steps reproduce the problem?

1. in the editor, trigger the auto-complete box
2. hit the "alt" key

### What is the expected output? What do you see instead?

I expect the auto-complete box to stay visible and have focus when I hit the alt key
so that when I go to hit alt+m I can browse the auto-complete list

What I see instead is the auto-complete box disappears and I see the scrollbar highlighted.

## Versions

* Spyder version: 5.3.2
* Python version: 3.9.12 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Opensuse Leap 15.3   kernel: linux 5.16.11-lp153.11-default 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.9.1 (OK)
keyring >=17.0.0              :  23.8.2 (OK)
nbconvert >=4.0               :  6.5.3 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  5.1.1 (OK)
spyder_kernels >=2.3.2;<2.4.0 :  2.3.2 (OK)
textdistance >=4.2.0          :  4.3.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.3 (OK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.9.0 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @cw9000, thanks for reporting. I also noticed this small regression and I agree with you that we can handle the case of pressing modifier keys such as `Alt`, `Shift` and `Ctrl` more gracefully when the completion widget is visible.

We'll take a look at it for our next version (5.4.0), to be released next month.
