### ISSUE TITLE
Opened tabs backup?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#19373]
I accidentally opened Spyder 3 in a wrong conda environment which reset configs and deleted open tabs. I restored from `.spyder-py3/config/backups`, but that didn't restore the tabs:

<img src="https://user-images.githubusercontent.com/16495490/189270951-f823a676-0481-4d35-b787-1e136018c9d8.png" width="600">

Can they be restored? If not, I'd like to request this feature. I had many tabs open in a specific order, and I've lost them to other bugs in the past.

**Comment by ccordoba12** [comment]
I think tabs are saved in `transient.ini-<version>.bak`. So please take a look at that file and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
