### ISSUE TITLE
How to automatically update docstrings when changing function signature?

### ISSUE THREAD

**Issue by Ubaldo79** [spyder-ide/spyder#19386]
This is not really an issue, but rather a question. 

I am wondering if there is a way to automatically update the docstring when changing function (or class or method) signature.

For example, say that I have

```
def foo(param1, param2):
    """Just an example.

    Parameters
    ------------
    param1: float
        First parameter
    param2: float
       Second parameter
    """
    return param1+param2
```

and I change the signature to `foo(param1, paramB)`, I wish a method to automatically update the docstring as it follows

```
def foo(param1, paramB):
    """Just an example.

    Parameters
    ------------
    param1: float
        First parameter
    paramB: TYPE
       DESCRIPTION HERE
    """
    return param1+param2
```

Is it possible?

**Comment by ccordoba12** [comment]
Hey @Ubaldo79, thanks for reporting. I'm sorry but we don't support that functionality.
