### ISSUE TITLE
Add search functionality for keyboard shortcuts

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1940]
_From [a.molcha...@gmail.com](https://code.google.com/u/105109847022035150285/) on 2014-08-20T15:02:47Z_

What steps will reproduce the problem?

 1. try to search for shortcuts in shortcuts configuration menu What version of the product are you using? On what operating system? v 2.2.5

Description:
Please, add shortcuts search (in shortcuts configuration menu) the way it is done in Kate (or maybe better, for example, to be able to search for combinations and keywords separately).

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1940_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:42:37Z_

**Summary:** Add search functionality for keyboard shortcuts   \<span class="oldvalue"> (was: Search for shortcuts ) \</span>  
  **Labels:** Cat-Settings MS-v2.4

**Comment by ccordoba12** [comment]
This shouldn't be that hard to implement @blink1073 :-)
