### ISSUE TITLE
I can't enter any input

### ISSUE THREAD

**Issue by Blurzh** [spyder-ide/spyder#19420]
### What steps will reproduce the problem?

All the programs I'm trying to run having inputs produce me the same errors over and over again.

I looked for the solution in internet and got to run:

 conda create -n spyder-cf -c conda-forge spyder
 conda activate spyder-cf
 spyder

In my still little programming knowlegde I think that's leading me to create a new enviroment, where I can run the inputs, but I'd prefer not to have to create a enviroment everytime I close it, or, better, to understand why this is happening and learn to fix it.

How can I solve this problem and what is happening? 

Thanks in advance :)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\sergi\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\sergi\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\sergi\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 512, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\sergi\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2422, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.2.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.0 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  61.2.0 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.28 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by Blurzh** [comment]
The same error keeps appearing. So now what?

**Comment by dalthviz** [comment]
Hi @Blurzh did you closed Spyder before running the commands above?

Also, since I think now a more recent version is available from the Anaconda default channel, try these commands (again close any Spyder instance open and then from an Anaconda prompt run them):

    conda update anaconda
    conda install spyder=5.3.3

If that doesn't help, takes to much time to complete or shows that conflicts were found, please try to create a new environment with the conda-forge channel running from an Ananconda prompt something like:

    conda create -n spyder-cf -c conda-forge python=3.9 spyder=5.3.3
    conda activate spyder-cf
    spyder

After that you should be able to launch Spyder from the created environment by either searching the shortcut created from the Windows Start menu looking for `Spyder (spyder-cf)` or running from an Anaconda prompt:

    conda activate spyder-cf
    spyder

Let us know if the info above helps!

**Comment by Blurzh** [comment]
Thanks a lot! 

Yeah, I finally solved the problem myself with that same solution you gave me: creating a new enviroment and using it (Spyder (spyder-cf)). After that everything is fine.

So, my question now is: 

- This launcher, Spyder (spyder-cf), didn't exist in my computer before? 
- Is it an independent part of Spyder that I created with an specific version?
- If that's the case, should I guess I can create as many enviroments as I please in my PC to work simultaneously with all of them?

Again, thanks a lot for your help :)

**Comment by Blurzh** [comment]
Great! That's an amazing answer :)

Thanks so much. I'm just starting in Spyder, and don't know much about programming yet, so it's really good to get to know how things work.
