### ISSUE TITLE
Crashing right in the beginning

### ISSUE THREAD

**Issue by Arcusgaldan** [spyder-ide/spyder#19440]
### What steps will reproduce the problem?

I simply ran a code which I used to run in older versions of Spyder/Anaconda. I tried commenting whole sections of it, but neverthless it crashes, without error codes or something like this. When I run this same code in CMD it runs flawlessly. 

And it's not only this code, but pretty much every code I have in my codebase. I recently changed computers and had to install Anaconda, which gave me a newer version and this bug.

Libraries used (not important since even when commenting my import lines it still crashes): numpy, pandas, Tkinter, timeit and datetime.

My Tkinter asks for the files (askopenfilenames) and it crashes afterwards, but even when I comment this section it crashes. After I select my files it should prompt an Input to two dates, but even when I comment this section it crashes. So basically it crashes no matter what.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\INFO\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\INFO\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 267, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\INFO\anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 516, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\INFO\anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2413, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.0.0 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.4.0 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.14.5 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2           :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=0.5.7             :  1.0.3 (OK)
qtconsole >=5.0.3             :  5.3.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.8.3                 :  0.9.7 (OK)
setuptools >=39.0.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.0.1;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3;<2.0.0      :  1.0.2 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by Arcusgaldan** [comment]
When I try to run "conda update anaconda" it gives me:

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\INFO\anaconda3
  package name: anaconda

And I purposely downgraded my spyder from 5.2.2 to 5.0.0 prior to reporting this issue while trying to fix it. So 5.2.2 gives me the same bug.

**Comment by dalthviz** [comment]
Hi @Arcusgaldan , could you post here the `conda list` output of the env where you have Spyder installed and from where you are running, please?

**Comment by Arcusgaldan** [comment]
Hello @dalthviz, of course!

**This is the conda list on my venv:**

# packages in environment at C:\Users\INFO\anaconda3\envs\TestePython:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
bottleneck                1.3.5           py310h9128911_0
bzip2                     1.0.8                he774522_0
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.6.15       py310haa95532_0
et_xmlfile                1.1.0           py310haa95532_0
intel-openmp              2021.4.0          haa95532_3556
libffi                    3.4.2                hd77b12b_4
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0           py310h2bbff1b_0
mkl_fft                   1.3.1           py310ha0764ea_0
mkl_random                1.2.2           py310h4ed8f06_0
numexpr                   2.8.3           py310hb57aa6b_0
numpy                     1.23.1          py310h6d2d95c_0
numpy-base                1.23.1          py310h206c741_0
openpyxl                  3.0.10          py310h2bbff1b_0
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.3           py310hd77b12b_0
pip                       22.1.2          py310haa95532_0
pyparsing                 3.0.9           py310haa95532_0
python                    3.10.4               hbb2ffb3_0
python-dateutil           2.8.2              pyhd3eb1b0_0
pytz                      2022.1          py310haa95532_0
setuptools                63.4.1          py310haa95532_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.39.2               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
tzdata                    2022c                h04d1e81_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2             py310haa95532_2
xlrd                      2.0.1              pyhd3eb1b0_0
xz                        5.2.5                h8cc25b3_1
zlib                      1.2.12               h8cc25b3_3

**This is the conda list on my base environment, which also bugs**

# packages in environment at C:\Users\INFO\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0
alabaster                 0.7.12             pyhd3eb1b0_0
anaconda-client           1.11.0           py39haa95532_0
anaconda-navigator        2.2.0            py39haa95532_0
anyio                     3.5.0            py39haa95532_0
argh                      0.26.2           py39haa95532_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
arrow                     1.2.2              pyhd3eb1b0_0
astroid                   2.11.7           py39haa95532_0
asttokens                 2.0.5              pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     21.4.0             pyhd3eb1b0_0
autopep8                  1.5.6              pyhd3eb1b0_0
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backports                 1.1                pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py39h2bbff1b_1
beautifulsoup4            4.11.1           py39haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     22.6.0           py39haa95532_0
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blosc                     1.21.0               h19a0ad4_1
bottleneck                1.3.5            py39h080aedc_0
brotlipy                  0.7.0           py39h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.6.15        py39haa95532_0
cffi                      1.15.1           py39h2bbff1b_0
chardet                   4.0.0           py39haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
click                     8.0.4            py39haa95532_0
cloudpickle               2.0.0              pyhd3eb1b0_0
clyent                    1.2.2            py39haa95532_1
colorama                  0.4.5            py39haa95532_0
conda                     4.14.0           py39haa95532_0
conda-build               3.22.0           py39haa95532_0
conda-content-trust       0.1.3            py39haa95532_0
conda-env                 2.6.0                haa95532_1
conda-package-handling    1.8.1            py39h8cc25b3_0
conda-repo-cli            1.0.5            py39haa95532_0
conda-token               0.4.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              37.0.1           py39h21b164f_0
cytoolz                   0.11.0           py39h2bbff1b_0
debugpy                   1.5.1            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.4              pyhd3eb1b0_0
docutils                  0.18.1           py39haa95532_3
entrypoints               0.4              py39haa95532_0
executing                 0.8.3              pyhd3eb1b0_0
filelock                  3.6.0              pyhd3eb1b0_0
flake8                    3.9.0              pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
future                    0.18.2           py39haa95532_1
glib                      2.69.1               h5dc1a3c_1
glob2                     0.7                pyhd3eb1b0_0
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
hdf5                      1.10.6               h1756f20_1
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      3.3                pyhd3eb1b0_0
imagesize                 1.4.1            py39haa95532_0
importlib-metadata        4.11.3           py39haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
inflection                0.5.1            py39haa95532_0
intel-openmp              2021.4.0          haa95532_3556
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.15.2           py39haa95532_0
ipython                   8.4.0            py39haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jedi                      0.17.2           py39haa95532_1
jinja2                    2.11.3             pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jpeg                      9e                   h2bbff1b_0
json5                     0.9.6              pyhd3eb1b0_0
jsonschema                4.4.0            py39haa95532_0
jupyter_client            7.3.5            py39haa95532_0
jupyter_core              4.10.0           py39haa95532_0
jupyter_server            1.18.1           py39haa95532_0
jupyterlab                3.4.4            py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.10.3             pyhd3eb1b0_1
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
keyring                   23.4.0           py39haa95532_0
lazy-object-proxy         1.6.0            py39h2bbff1b_0
lerc                      3.0                  hd77b12b_0
libarchive                3.6.1                hebabd0d_0
libclang                  12.0.0          default_h627e005_2
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_4
libiconv                  1.16                 h2bbff1b_2
liblief                   0.11.5               hd77b12b_1
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libtiff                   4.4.0                h8a3f274_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.2                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
lzo                       2.10                 he774522_2
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
markupsafe                2.0.1            py39h2bbff1b_0
matplotlib-inline         0.1.6            py39haa95532_0
mccabe                    0.6.1            py39haa95532_2
menuinst                  1.4.18           py39h59b6b97_0
mistune                   0.8.4           py39h2bbff1b_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py39h2bbff1b_0
mkl_fft                   1.3.1            py39h277e83a_0
mkl_random                1.2.2            py39hf11a4ad_0
mock                      4.0.3              pyhd3eb1b0_0
msys2-conda-epoch         20160418                      1
mypy_extensions           0.4.3            py39haa95532_1
mysql-connector-python    8.0.30                   pypi_0    pypi
navigator-updater         0.2.1                    py39_1
nbclassic                 0.3.5              pyhd3eb1b0_0
nbclient                  0.5.13           py39haa95532_0
nbconvert                 6.4.4            py39haa95532_0
nbformat                  5.3.0            py39haa95532_0
nest-asyncio              1.5.5            py39haa95532_0
notebook                  6.4.12           py39haa95532_0
numexpr                   2.8.3            py39hb80d3ca_0
numpy                     1.23.2                   pypi_0    pypi
numpy-base                1.21.5           py39hca35cd5_3
numpydoc                  1.4.0            py39haa95532_0
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.4                    pypi_0    pypi
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.7.0                      py_0
pathlib                   1.0.1              pyhd3eb1b0_1
pathspec                  0.9.0            py39haa95532_0
pcre                      8.45                 hd77b12b_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.2.0            py39hdc2b20a_1
pip                       22.1.2           py39haa95532_0
pkginfo                   1.8.2              pyhd3eb1b0_0
platformdirs              2.5.2            py39haa95532_0
pluggy                    1.0.0            py39haa95532_1
ply                       3.11             py39haa95532_0
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.14.1           py39haa95532_0
prompt-toolkit            3.0.20             pyhd3eb1b0_0
psutil                    5.9.0            py39h2bbff1b_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pure_eval                 0.2.2              pyhd3eb1b0_0
py-lief                   0.11.5           py39hd77b12b_1
pycodestyle               2.6.0              pyhd3eb1b0_0
pycosat                   0.6.3            py39h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pydocstyle                6.1.1              pyhd3eb1b0_0
pyflakes                  2.2.0              pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyjwt                     2.4.0            py39haa95532_0
pylint                    2.14.5           py39haa95532_0
pyls-black                0.4.6                hd3eb1b0_0
pyls-spyder               0.3.2              pyhd3eb1b0_0
pynacl                    1.5.0            py39h8cc25b3_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py39haa95532_0
pyqt                      5.9.2            py39hd77b12b_6
pyqt5-sip                 12.11.0          py39hd77b12b_0
pyrsistent                0.18.0           py39h196d8e1_0
pysocks                   1.7.1            py39haa95532_0
pytables                  3.6.1            py39h56d22b6_1
python                    3.9.12               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39haa95532_0
python-jsonrpc-server     0.4.0                      py_0
python-language-server    0.36.2             pyhd3eb1b0_0
python-libarchive-c       2.9                pyhd3eb1b0_1
python-slugify            5.0.2              pyhd3eb1b0_0
pytz                      2022.1           py39haa95532_0
pywin32                   302              py39h2bbff1b_2
pywin32-ctypes            0.2.0           py39haa95532_1000
pywinpty                  2.0.2            py39h5da7b33_0
pyyaml                    6.0              py39h2bbff1b_1
pyzmq                     23.2.0           py39hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 1.0.3              pyhd3eb1b0_0
qtconsole                 5.3.2            py39haa95532_0
qtpy                      2.2.0            py39haa95532_0
requests                  2.28.1           py39haa95532_0
rope                      0.22.0             pyhd3eb1b0_0
rtree                     0.9.7            py39h2eaa2aa_1
ruamel_yaml               0.15.100         py39h2bbff1b_0
send2trash                1.8.0              pyhd3eb1b0_1
setuptools                63.4.1           py39haa95532_0
sip                       4.19.13          py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sniffio                   1.2.0            py39haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.1              pyhd3eb1b0_0
sphinx                    5.0.2            py39haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.0.0            py39haa95532_1
spyder-kernels            2.0.5            py39haa95532_0
sqlite                    3.39.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
terminado                 0.13.1           py39haa95532_0
testpath                  0.6.0            py39haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss                   0.4             pyhd3eb1b0_1002
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py39haa95532_0
tomlkit                   0.11.1           py39haa95532_0
toolz                     0.11.2             pyhd3eb1b0_0
tornado                   6.2              py39h2bbff1b_0
tqdm                      4.64.0           py39haa95532_0
traitlets                 5.1.1              pyhd3eb1b0_0
typing-extensions         4.3.0            py39haa95532_0
typing_extensions         4.3.0            py39haa95532_0
tzdata                    2022c                h04d1e81_0
ujson                     5.4.0            py39hd77b12b_0
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.11          py39haa95532_0
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
watchdog                  1.0.2            py39haa95532_1
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
websocket-client          0.58.0           py39haa95532_4
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.5.2            py39haa95532_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
winpty                    0.4.3                         4
wrapt                     1.14.1           py39h2bbff1b_0
xz                        5.2.5                h8cc25b3_1
yaml                      0.2.5                he774522_0
yapf                      0.31.0             pyhd3eb1b0_0
zeromq                    4.3.4                hd77b12b_0
zipp                      3.8.0            py39haa95532_0
zlib                      1.2.12               h8cc25b3_3
zstd                      1.5.2                h19a0ad4_0

Thank you for your attention!

**Comment by dalthviz** [comment]
Could you try again doing `conda install spyder=5.2.2` on you base env and provide the `conda list` output from  there?

Also, if the issue keeps raising, could you create a new env using the conda-forge channel? For that you, run from the Anaconda prompt something like:

    conda create -n spyder-cf -c conda-forge python=3.9 spyder=5.3.3

Then you can launch Spyder from the created shortcut on the Start menu (you can search for `Spyder (spyder-cf)` there), or running from an Anaconda prompt:

    conda activate spyder-cf
    conda spyder

Let us know if that helps!

**Comment by Arcusgaldan** [comment]
Interesting, re-upgrading to 5.2.2 apparently made it work again. I assumed it wouldn't work because I had already uninstalled conda and installed again. But now it's working, so thank you very much for your time!
