### ISSUE TITLE
New Project not getting created

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1947]
_From [kathuria...@gmail.com](https://code.google.com/u/115193285664075498931/) on 2014-08-27T05:07:31Z_

Spyder Version:  2.3.0
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Darwin
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK) 

What steps will reproduce the problem?

 1. Install Spyder on Macbook Air MD760HN/B, running OS X Mavericks
2. Create a project from 'File' option in menubar at top
3. The window disappears before even selecting the default workspace folder for the first time 

What is the expected output? What do you see instead?

 refer point 3 above 

Please provide any additional information below

. Tried creating a project for the first time. On being prompted 'The current workspace has not been configured yet. Do you want to do this now?', clicked 'Yes'. The new window for selecting folder disappeared after few seconds.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1947_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-27T06:13:58Z_

Thanks for reporting. We'll try to fix it in our 2.3.2 release.

**Labels:** MS-v2.3.2 Cat-ProjectExplorer

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:07:53Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-01T06:57:10Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
Projects are being reworked right now by @goanpeca, so we are leaving this for our next major release.
