### ISSUE TITLE
spyder 2.3 ipython console startup code or file not working

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1948]
_From [sergio.c...@gmail.com](https://code.google.com/u/104661479660248330338/) on 2014-08-27T10:39:44Z_

Spyder Version:  2.3.0
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.2.1 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.2 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. Go to Tools->Preferences->Ipython_console startup tab, provide a startup script in "run a file" or a startup command in "run code". Apply and save changes.
2. Open a new ipython console

(e.g., tried with a startup file or startup code including a mere print statement.)

What is the expected output? 

Startup file should be executed. If it includes a mere print statement for testing, something should be printed.

What do you see instead?

Provided code or file is not run. In fact if the code includes a mere print statement, nothing is printed.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1948_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:22:43Z_

**Labels:** MS-v2.3.3 Cat-IPythonConsole

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:22:35Z_

Things are run before the kernel is started and so no printed strings are shown. There is no problem with that :-)

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:28:16Z_

Sorry, it was not "the kernel" but "the frontend" in the last phrase.

**Comment by HamsterHuey** [comment]
I think this is still a valid bug. It does not have anything to do with whether there is a print statement or not. At least on my install of latest version of Spyder 2.3.2, I either have a startup file containing:
    import numpy as np
    import pandas as pd
etc.

None of these imports are actually reflected in the iPython console once Spyder has started. Similarly, if I don't use a startup file in the Spyder settings (Ipython Console -> Startup), but instead select the "Run Lines" option, and enter "import numpy as np, import pandas as pd", again, none of these modules are imported on startup.

This used to work fine in the past. I hope this helps.

Thanks for all the great work on Spyder.

**Comment by ccordoba12** [comment]
Ok, thanks for pointing out. Reopen it then to investigate it further.

**Comment by dallasmasters** [comment]
Confirm similar behavior, but I only get this for import numpy or import matplotlib or import pandas (not saying there aren't others). Other modules are loaded if put in a startup file or on the "run lines" directive.

**Comment by ccordoba12** [comment]
I know what's the problem with this one. I'll fix it for 2.3.4

Thanks for insisting with it :-)

**Comment by HamsterHuey** [comment]
Glad to hear that! Thanks for all the hard work on Spyder! :)
