### ISSUE TITLE
Add support for other file types [improvement suggestion]

### ISSUE THREAD

**Issue by Ubaldo79** [spyder-ide/spyder#19515]
I think it would be good enough to include e.g. highlight syntax for common extensions used when developing python packages, such as .`rst`, .`toml`, .`md`. 

What do you think?

**Comment by ccordoba12** [comment]
Hey @Ubaldo79, thanks for reporting. We already have support for Rest and Markdown files, and several other file types through the Pygments library. That support is not very good but it'll be improved once we can integrate the Pysyntect library we developed for this:

https://github.com/spyder-ide/pysyntect

**Comment by Ubaldo79** [comment]
Ok! Good to know. Mind that one has the "format on save" option on, then spyder hangs.  ;-) 
I think there should be an open issue for this.

**Comment by ccordoba12** [comment]
That's already fixed. The change will be part of Spyder 5.4.0, to be released next month.
