### ISSUE TITLE
SVG icons are blurry after update to 5.3

### ISSUE THREAD

**Issue by julie-jch** [spyder-ide/spyder#19520]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

This is how my spyder looked before updating to 5.3 
![image](https://user-images.githubusercontent.com/90422532/191310573-d893e2f8-d37a-4b3c-a12c-1fb8c5243f82.png)

Here is a generated image

![image](https://user-images.githubusercontent.com/90422532/191311558-6cfb5791-7b08-449a-85dc-63afe63a7ad8.png)

This is what the text looks like, you can see each line is perfect no overlap.
![image](https://user-images.githubusercontent.com/90422532/191311782-1254ea9d-144c-4256-b65a-560a08b5f17a.png)

This is what I get now after updating to 5.3. Same setting but icons and taskbars are huge, text is use, the icons are blurry
![image](https://user-images.githubusercontent.com/90422532/191312469-46234f70-e5f1-407f-bce6-64cd2e9d1aa5.png)

Here is the same image generated, but not its really blurry
![image](https://user-images.githubusercontent.com/90422532/191312621-c13d606f-9512-497c-956e-1e1daf6c31c7.png)

I can toggle/lower the text size but this does noting for the huge panels and blurriness. 
![image](https://user-images.githubusercontent.com/90422532/191313216-2b71d0f5-9646-4bb1-904d-9fc5be697856.png)

You also note, when I highlight a line of text, as in line 6, the number overlaps. I'm not sure how to fix this issue

Things I've done to help
1. So far I reverted to ```conda install --revision=9``` this doesn't help
2. Restarted my device
3. I've noted in another environment which I have not updated spyder (the one i used to generate the images above) everything looks fine.

## Versions

<! * Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Linux 5.4.0-124-generic

![image](https://user-images.githubusercontent.com/90422532/191315097-bbaedd87-f01d-43a0-a3f5-80faaec4f370.png)

![image](https://user-images.githubusercontent.com/90422532/191315195-84c8ae47-2d5b-4b9c-8873-1f7d867f09b1.png)

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @julie-jch, thanks for reporting. You said:

> This is what I get now after updating to 5.3. Same setting but icons and taskbars are huge, text is use, the icons are blurry
> ![image](https://user-images.githubusercontent.com/90422532/191312469-46234f70-e5f1-407f-bce6-64cd2e9d1aa5.png)

I think the size of icons and toolbars is the right one, specially compared to the font size you're using in the editor. As an example, this is how Spyder looks for me (on Linux too):

![image](https://user-images.githubusercontent.com/365293/191411961-b848eacc-ebef-4a11-9037-74d5123971e9.png)

----

On this screenshot is specially clear that icons were way too small for you before:

> ![image](https://user-images.githubusercontent.com/90422532/191311558-6cfb5791-7b08-449a-85dc-63afe63a7ad8.png)

We didn't design Spyder to look like that. So we're not planning to change it, sorry. Again, this is how it looks for me:

![image](https://user-images.githubusercontent.com/365293/191412824-0aacbc14-2255-4260-9da8-7acc76f4c6f6.png)

**Comment by ccordoba12** [comment]
However, you're correct that the icons are blurry. Thanks for pointing that out (we didn't notice it because we don't develop on 4k monitors).

We'll fix that problem in our next version (5.4.0), to be released next month.

**Comment by ccordoba12** [comment]
Sorry, I missed these comments of yours:

> This is what the text looks like, you can see each line is perfect no overlap.
> You also note, when I highlight a line of text, as in line 6, the number overlaps. I'm not sure how to fix this issue

I can reproduce this error with the `elusiveicons` font you're using:

![image](https://user-images.githubusercontent.com/365293/191415726-a954ab39-f7bb-4087-9a40-0ab6be4a561d.png)

@impact27, could you take a look at it? I thought it was fixed, but it seems it's still an issue for some fonts.

**Comment by impact27** [comment]
I can't reproduce this with `elusiveicons` on mac. The numbers are not well aligned because this is not a monospaced font, but the highlighting puts the number at the correct position.

**Comment by ccordoba12** [comment]
> The numbers are not well aligned because this is not a monospaced font

Ok, thanks a lot for checking this so quickly. I didn't know `elusiveicons` is not a monospaced font (although Qt detects it as such). Any idea if there's a way to improve that?

**Comment by impact27** [comment]
This is what I have with `elusiveicons`:
<img width="25" alt="Screenshot 2022-09-21 at 07 07 45" src="https://user-images.githubusercontent.com/6740194/191418901-4408c446-6756-4c4d-97dd-8439566daf8a.png">
We could remove it from the list of options maybe?

**Comment by ccordoba12** [comment]
> We could remove it from the list of options maybe?

That's a good idea but it doesn't seem easy or even possible. So, let's leave it like that.
