### ISSUE TITLE
spyderlib.utils.external overrides modules for script execution

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1952]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-09-02T03:10:28Z_

Spyder Version:  2.4.0dev (4077: rc834f104cb5c )
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.1 on Linux
pyflakes >=0.5.0:  0.5.0 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
jedi >=0.8.0    :  0.8.1-final0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.3.0 (OK) 

What steps will reproduce the problem?

 1. Install path.py from pip
2. Type in the console or execute a script:
import path
print(path.__file__) 

What is the expected output? What do you see instead?

 The printed path is [...]/spyderlib/utils/external/path.pyc, while I expect to get the module installed on the system. Spyder should not change the execution environment for scripts at all.

Please provide any additional information below

.
The path.py module in spyder is outdated, that's how I discovered the problem.
The problem is the same when launched via 'spyder' or 'bootstrap.py'

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1952_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:07:56Z_

**Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:18:07Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by Nodd** [comment]
Hey, thanks for fixing this !

**Comment by ccordoba12** [comment]
You're welcome :-)
