### ISSUE TITLE
I have now both downgraded and updated but none if it helps, still same issueThanks for reporting. To fix this error, please close Spyder, open the Anaconda Prompt and run the following commands there:<br><br>`conda update anaconda`<br>`conda install spyder=5.2.2`

### ISSUE THREAD

**Issue by 35trokes** [spyder-ide/spyder#19557]
Thanks for reporting. To fix this error, please close Spyder, open the Anaconda Prompt and run the following commands there:<br><br>`conda update anaconda`<br>`conda install spyder=5.2.2`

_Originally posted by @spyder-bot in https://github.com/spyder-ide/spyder/issues/19556#issuecomment-1255139057_

**Comment by ccordoba12** [comment]
Hey @35trokes, thanks for reporting. If our solution doesn't work for you, please report your problem to the Anaconda team here:

https://github.com/ContinuumIO/anaconda-issues

Unfortunately, this is an issue with Anaconda, not with Spyder, and the commands we tell users to run are the only solution we know to solve it.

**Comment by ccordoba12** [comment]
You could also download and install our Windows or Mac installer, which doesn't have this problem. You can find them here:

https://github.com/spyder-ide/spyder/releases

**Comment by 35trokes** [comment]
Thank you very much for your reply :) I have spyder installed separately
which works, but I can only install pygame on the anaconda version but not
use it for the most basic coding. So I have standalone which can do basic
coding and numpy, turtle etc but no pygame, and the anaconda can do pygame
but no basic coding 😅

All the best,
Bertram

**Comment by ccordoba12** [comment]
Sorry to hear that. Then, if you're unable to update Spyder, I'm afraid you'll have to wait until Anaconda releases a new version, which will have a more recent Spyder version without this error.
