### ISSUE TITLE
Wrong E275 warning if keyword is at the end of a line

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#19565]
## Problem Description

As reported in https://github.com/PyCQA/pycodestyle/issues/1102, Spyder is wrongly reporting `E275` (https://www.flake8rules.com/rules/E275.html) warnings when a keyword is located at the end of a line.

This is occurring with `pycodestyle 2.9.1`, in which E275 checking was added.

```python
# -*- coding: utf-8 -*-
try:
    xabs = [
        abs(x) for x in
        [1, -2, 3, -4]
        ]
except Exception:
    pass
else:
    pass

import pycodestyle
sut = pycodestyle.StyleGuide()
results = sut.input_file(filename=__file__)
print(results)
```

![image](https://user-images.githubusercontent.com/10170372/191849076-51c1b1a7-2d4b-4525-aaf5-0688a37e9b16.png)

The problem seems to be related with how `end-of-line characters` are handled before sending them to pycodestyle. I currently use `Carriage return and line feed (Windows)`, but there is no such False warning if I use `Line feed (UNIX)` end-of-line characters.

On the opposite, if I use `Carriage return (Mac)`, then I get even more False positives.

![image](https://user-images.githubusercontent.com/10170372/191850855-487d6630-c096-4725-b120-3ea747d7b231.png)

## Versions

* Spyder version: 5.3.0.dev0 b563ebda0
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

**Comment by jnsebgosselin** [comment]
I've updated to the latest commit on the 5.x branch (https://github.com/spyder-ide/spyder/commit/84d1b6ca0) and I still get false E275 positives when using `CRLF (Windows)` end-of-line characters.

**Comment by dalthviz** [comment]
I see, thanks for the testing @jnsebgosselin ! Not totally sure, but maybe to fix this some changes at the [`python-lsp-server`](https://github.com/python-lsp/python-lsp-server) will need to be done then @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, we probably need to replace Windows line endings to Linux ones in the PyLSP before passing the file to Pycodestyle.
