### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by soroosh12** [spyder-ide/spyder#19574]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by soroosh12** [comment]
when i want to run some codes in kernel print a error and that is keyboard intrupted

**Comment by soroosh12** [comment]
when i want to run some codes in kernel print a error and that is keyboard intrupted

**Comment by dalthviz** [comment]
Hi @soroosh12 could you share an screenshot of the behavior you are experiencing? Also, could you describe your setup (Spyder version, Python version, OS, etc) and the steps to experience this behavior? Without further information there is not much we can do, sorry :/

**Comment by dalthviz** [comment]
Closing due to lack of response and information to reproduce the problem
