### ISSUE TITLE
spyder python3 configuration

### ISSUE THREAD

**Issue by arv2103** [spyder-ide/spyder#19576]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by arv2103** [comment]
i don't exactly know what happened here it was work but eventually it's not running the code

**Comment by ccordoba12** [comment]
Hey @arv2103, thanks for reporting. Please post the error report you're getting so you can better understand what's happening in your case.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
