### ISSUE TITLE
crash of interactive console when using Qt

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1959]
_From [pieter.e...@gmail.com](https://code.google.com/u/104992064869212583354/) on 2014-09-09T17:05:20Z_

The interactive console crashes after running a simple script several times with F5. The script does not crash when running with F9 or CTRL-ENTER.

A minimal example script is:

import qttest
nmon=qttest.monitorCount()
print('system has &#37;d monitor(s)' &#37; nmon)

with the file qttest:

\# -*- coding: utf-8 -*-

from PyQt4 import QtGui
r=QtGui.QApplication.startingUp()
print('QtGui.QApplication.startingUp() &#37;s'  &#37; r)
if r:
    print('starting QApplication' )
    _applocalqt = QtGui.QApplication([])
    _qd=QtGui.QDesktopWidget()
else:
    print('get QDesktopWidget()')         
    _qd=QtGui.QDesktopWidget()
        
def monitorCount():  
    """ Return monitor count """
    nmon=_qd.screenCount()
    return nmon

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1959_

**Comment by spyder-issues-migrator** [comment]
_From [pieter.e...@gmail.com](https://code.google.com/u/104992064869212583354/) on 2014-09-10T15:33:43Z_

The issue does not appear (for this test script) when using PySide instead of PyQt4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T17:04:51Z_

I think you can't mix PyQt and PySide in the same process. So if you are running Spyder with PySide, you can't use PyQt4 in your scripts and vice-versa.

I'll check out if that's the case.

**Labels:** Cat-Console MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-04T10:32:32Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
This is not an issue in PyQt4 either. The most probable cause is that you're mixing PySide and PyQt4 in your code.
