### ISSUE TITLE
[Question]: moving from Win10 to MacOs X. Where the preference are stores?

### ISSUE THREAD

**Issue by ubaldot** [spyder-ide/spyder#19608]
I guess there should be some sort of `.spyderrc` somewhere on my windows PC, but I don't know where. 
I guess that to move all my preferences, it is enough to copy them somewhere in my new MacBook Pro.
What are these preferences files? And where shall copy them? 
Can someone help me please?

Many thanks.

**Comment by ccordoba12** [comment]
Hey @ubaldot, thanks for reporting. Spyder settings are saved in `C:\Users\<your user>\.spyder-py3\config\spyder.ini` on Windows and `/Users/<your user>/.spyder-py3/config` on Mac.
