### ISSUE TITLE
Spyder crashes when the IPython console is disabled

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#19610]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I had to restart my desktop environment through a reboot. Spyder was running at that time with one file not saved.

After the restart, I started Spyder from the start menu. It showed me the file recovery dialog, I agreed to the recovery and then Spyder exited. When I tried it again, the recovery dialog was not displayed. (_Where would I now find the recovered file?_), but Spyder still did not start.

I then started Spyder from the terminal with `spyder --debug-info verbose --debug-output file`. The [spyder-debug.log](https://github.com/spyder-ide/spyder/files/9645589/spyder-debug.log) (with the traceback spliced in) is attached.

### What is the expected output? What do you see instead?

Please see [spyder-debug.log](https://github.com/spyder-ide/spyder/files/9645589/spyder-debug.log)

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/spyder/api/widgets/menus.py", line 225, in _render
    section, before_section = next(iter_sections)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/start.py", line 252, in main
    mainwindow.main(options, args)
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/mainwindow.py", line 1956, in main
    mainwindow = create_window(MainWindow, app, splash, options, args)
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/utils.py", line 300, in create_window
    main.post_visible_setup()
  File "/usr/local/lib/python3.8/dist-packages/spyder/app/mainwindow.py", line 1057, in post_visible_setup
    plugin.on_mainwindow_visible()
  File "/usr/local/lib/python3.8/dist-packages/spyder/plugins/mainmenu/plugin.py", line 86, in on_mainwindow_visible
    menu._render()
  File "/usr/local/lib/python3.8/dist-packages/spyder/api/widgets/menus.py", line 246, in _render
    raise SpyderAPIError(
spyder.api.exceptions.SpyderAPIError: You're trying to introduce some sections before others that don't have any actions. This is the list of (section, before_section) that's failing to be added:

[('documentation_section', 'support_section'), ('support_section', 'external_documentation_section')]
```

## Versions

* Spyder version: 5.3.3
* Python version: 3.8.10
* Qt version: 5.15.2 (?)
* PyQt version: 5.15.7
* Operating System name/version: Linux Mint 20.3

### Dependencies

N/A.

**Comment by sphh** [comment]
After calling `spyder --reset`, spyder started without any error message. (I still have the old configuration, if that is needed …)

**Comment by ccordoba12** [comment]
Hey @sphh, thanks for reporting. I'm going to close this because it's already solved.

**Comment by sphh** [comment]
Is this solved, because of `spyder --reset` or because of a commit?

**Comment by sphh** [comment]
I compared the `.config/spyder-py3/config/spyder.ini` file and found the culprit:

If I run `spyder --reset` and then set
```ini
[ipython_console]
enable = False
```
I can reproduce the above error on my installation!

@ccordoba12: Does this qualify this issue to be reopened?

**Comment by ccordoba12** [comment]
Yeah, I tested this locally and you're right, Spyder crashes with this error if the IPython console is disabled.

**Comment by sphh** [comment]
:bow:
