### ISSUE TITLE
MacOS standalone installer PR build failing

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#19618]
Seems like something is making the MacOS build fail on PRs as for example https://github.com/spyder-ide/spyder/pull/19617 https://github.com/spyder-ide/spyder/actions/runs/3129391951/jobs/5078662547

Checking the logs at the end, after the packages recipes are all checked, you can see the following:

```
*** filtering dependencies ***
15400 total
48 filtered
201 orphaned
15352 remaining
Error: Process completed with exit code 1.
```

Not totally sure what could be happening but just in case pinging @mrclary

**Comment by ccordoba12** [comment]
Fixed by PR #19620.
