### ISSUE TITLE
Bug: FileDialog: Profiler Save/Load does not make File-Extension (.Result) clear

### ISSUE THREAD

**Issue by maurerle** [spyder-ide/spyder#19633]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The expected extension of the file is unclear if i try to load or save a profiling result.
This could be improved by providing better information, saving the file with extension if no extension was given and/or allowing to select "any file extension" in the save dialog.

This error was found on Gnome and its one of many filedialog integration things, but maybe this can be improved in the future :)

### What steps reproduce the problem?

1. Save Profile/Load Profile
2. See that there is no file extension in the save dialog
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Python 3.10.4 64-bit | Qt 5.15.2 | PyQt5 5.15.6 | Linux 5.10.0-18-amd64 

![image](https://user-images.githubusercontent.com/25026204/192582489-dd368abf-f27c-4d96-8244-b0d9eca6c643.png)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @maurerle thank you for the feedback! Could this be related with #18684 ? And if so, maybe a similar approach as in https://github.com/spyder-ide/spyder/pull/17790 could be implemented for this?
