### ISSUE TITLE
problem with running code

### ISSUE THREAD

**Issue by nora3060** [spyder-ide/spyder#19645]
### What steps will reproduce the problem?

handler(msg)
return super(DebuggingWidget, self)._handle_input_request(msg)
self._readline(msg['content']['prompt'], callback=callback,
TypeError: _show_prompt() got an unexpected keyword argument 'separator'

**Comment by ccordoba12** [comment]
Hey @nora3060, did the above commands finished without errors? Or did you have problems with them?

**Comment by nora3060** [comment]
I don't have errors in my commands. When I run my code, I see the window "issue reports"

**Comment by nora3060** [comment]
I installed it again, and now it is working :) Thank you so much!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
