### ISSUE TITLE
Segmentation fault while execute 3d tensor multiplication with PyTorch

### ISSUE THREAD

**Issue by hawkiyc** [spyder-ide/spyder#19664]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* Please note I update spyder via dmg file
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Error of Segmentation Fault pops out while executing 3d tensor multiplication, yet, everything is fine for 2d tensor. At first, I thought it resulted from PyTorch for Mac MPS accelerating. However, 3d tensor multiplication is totally fine in Jupyter Lab. 

Please check the following screenshots for more details.
![截圖 2022-09-30 14 46 25](https://user-images.githubusercontent.com/76748651/193210495-981b652b-39e2-40b3-a18e-c3e3edb183a6.jpg)
![截圖 2022-09-30 14 51 25](https://user-images.githubusercontent.com/76748651/193210471-12c2c1f4-f23d-4e21-84ee-48b9e583d422.jpg)

### What steps reproduce the problem?

1. import pytorch
2. create 2 torch.tensor object(3d)
3. execute tensor multiplication

### What is the expected output? What do you see instead?

1. the result of tensor multiplication
2. segmentation fault

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Please note that I install spyder via dmg file and tuning into different python env with spyder-kernels
* Spyder version: 5.3.3
* Python version: 3.8.13 
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: macOS Monterey 12.6.1

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.14.0 (OK)
keyring >=17.0.0                     :  23.8.2 (OK)
nbconvert >=4.0                      :  7.0.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  65.3.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.4.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

###my python env
[終端機輸出記錄.txt](https://github.com/spyder-ide/spyder/files/9681766/default.txt)

**Comment by dalthviz** [comment]
Hi @hawkiyc thank you for the feedback! Checking your Python env seems like you installed PyTorch using pip? Could it be possible for you to create an env using the conda-forge channel to install all of the packages? Let us know if that helps!

**Comment by hawkiyc** [comment]
> Hi @hawkiyc thank you for the feedback! Checking your Python env seems like you installed PyTorch using pip? Could it be possible for you to create an env using the conda-forge channel to install all of the packages? Let us know if that helps!

Dear @dalthviz ,

I have re-installed PyTorch via conda, and it seems to work fine now. 

Appreciate your kind assistance.

Cheers,

hawkiyc
