### ISSUE TITLE
Spyder freezes when loading large matlab files

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1968]
_From [spacego...@gmail.com](https://code.google.com/u/110291340883920610461/) on 2014-09-16T07:42:21Z_

What steps will reproduce the problem?

 import numpy as np
from scipy.io import loadmat
dst='D:\data'
data=loadmat(dst)
tdata=data['TData']

data.mat is a matlab .mat file which is over 20MB. Those codes are pretty much fluent in IPython. But when I execute them within Spyder2, even use the Ipython console, the Spyder will be freezed immediately.It freezes for maybe 20 seconds, then continues normally for a few more keystrokes and freezes again, making it unusable.

How could I solve this problem?

**Attachment:** [2.png](http://code.google.com/p/spyderlib/issues/detail?id=1968)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1968_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-16T12:39:58Z_

Steven, could you take a look at this? I don't have big Matlab files to test.

Maybe the problem is the auto-refresh feature of the Variable Explorer, as reported in issue #1958 .

**Summary:** Spyder freezes when loading large data sets  \<span class="oldvalue"> (was: The Spyder2 freezes when loading large data sets) \</span>  
  **Cc:** steven.s...@gmail.com  
  **Labels:** MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-16T12:40:54Z_

issue #1969 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [spacego...@gmail.com](https://code.google.com/u/110291340883920610461/) on 2014-09-16T18:20:17Z_

Thank you very much for your help. issue #1958 's solution do solve this problem.
However, I like variable explorer pretty much. This is especially useful when dealing with large data sets. Matlab's variable explorer is available even when I load some variables bigger than 3GB. Is there any other solution for me?

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-16T20:28:41Z_

I'll take a look.  By the way Carlos, you can create mat files from numpy arrays using scipy.io.savemat.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-17T03:52:35Z_

@-spacegoing: Great to know! You don't need to worry aobut disabling the auto-refresh option. That doesn't disable the Variable Explorer. The only thing it does is preventing Spyder to try to update the Variable Explorer every two seconds (which is quite costly for big data, as we are discovering). However, you can press the refresh button to update it any time you want. It's the first button to the right from top to bottom in the Variable Explorer, with two opposed arrows.

@-Steven: Good to know :)

**Labels:** -Cat-SpyderGUI -MS-v2.4 Cat-VariableExplorer MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-17T18:31:39Z_

Here's what I tried on Windows 7 using the latest master:

```
from scipy.io import savemat, loadmat
import numpy as np
test = np.ones(1e7)
savemat('test.mat', dict(test=test))  # this file is 78MB
del test
data = loadmat('test.mat')
test = data['test']
test.dtype

dtype('<f8')
```

I now have an array of size (1, 1e7) called `test` in my variable explorer

Now, if I try and *interact* with an array of that size, whether created using 
np.ones(1e7) or through the save/loadmat, Spyder freezes.

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-17T18:32:59Z_

Actually, it did eventually load the array editor for the 1x1e7 array.

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-17T18:34:13Z_

@-spacegoing, what datatype(s) are in that mat file?

**Comment by spyder-issues-migrator** [comment]
_From [spacego...@gmail.com](https://code.google.com/u/110291340883920610461/) on 2014-09-17T20:04:15Z_

I really appreciate you efforts. Many thanks!
Typically matlab cell style is stored in that mat file.
Thank you!

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-18T04:17:57Z_

Yep, that's the problem:

```
from scipy.io import savemat, loadmat
import numpy as np
test = np.ones(1e7)
savemat('test.mat', dict(test=(dict(test=test))))  # this file is still 78MB
del test
data = loadmat('test.mat')
test = data['test']  # here we hang
```

loadmat treats cell types as 'O' object types.  The above works when I make the array size 1e3, but Spyder does not like the larger 'O' arrays.  I'll have to do more digging.

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-18T19:13:22Z_

By the way, if you just drag the file created above ('test.mat') from your system File Manager into the Variable Explorer, it imports nicely as a `utils.iofuncs.MatlabStruct` type, and can be interacted with as usual from the console.  You can also press the import button in the Variable Explorer and get the same result.

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-18T19:14:31Z_

Carlos, is the above solution good enough since this is a corner case, or do you think this warrants further digging?

**Comment by spyder-issues-migrator** [comment]
_From [spacego...@gmail.com](https://code.google.com/u/110291340883920610461/) on 2014-09-19T04:05:56Z_

Dear steven,

really good job! I really appreciate it.

Two more suggestion. In matlab's editor, you might press shift+Enter when you alter a variable name to apply the change to all the references. And the matlab's editor also have a 'smart indent' function to help you format your code more easily.

I think those two functions help me a lot when I developing matlab code. I will be really happy to see those functions in Spyder's future version!

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-09-19T04:16:44Z_

@-spacegoing, I think you'll find that Spyder's editor does a fine job of managing indentation *while* you are writing the code, for instance when you hit Enter it usually knows where to start the next line.
As far as global renaming of variables and other refactorings, that sounds like a great target for a `SpyderPlugin` using the `rope` library.  You might want to mention it on the mailing list to gauge general interest. http://rope.sourceforge.net/

**Comment by spyder-issues-migrator** [comment]
_From [spacego...@gmail.com](https://code.google.com/u/110291340883920610461/) on 2014-09-19T05:18:48Z_

Thank you very much for your advise^_^ They are really helpful!

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-09-19T16:55:46Z_

There is already the Issue `#415` about refactoring.

It is not possible to create a smart indent feature in python because contrary to matlab, in python indentation matters, so the only way to know how to indent is to know how the program has to work. Onlt the developper knows this !
If you want to correct some indentation inaccuracies (like multi-line expressions) you can use autopep8. I made a plugin for spyder: https://github.com/Nodd/spyder_autopep8

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-01T16:46:00Z_

Sorry Steven (regarding your comment `#12`), what was the solution here?

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-11-01T18:56:58Z_

The solution was to use the Import Wizard, which handles MAT files in a more sane manner than the standard `loadmat`.  The question was whether handling this edge case warrants further digging into the way the Variable Explorer handles larger variables.  I can't seem to tease out *where* the variables are actually loaded by the Variable Explorer, since this starts treading on the inter-process voodoo part of Spyder.  If you point me in the right direction I can investigate further.

**Comment by spyder-issues-migrator** [comment]
_From [pauldur...@gmail.com](https://code.google.com/u/114809488004188207176/) on 2014-11-11T17:27:53Z_

I've also found spyder (v.2.3.1) "freezing" when I load relatively large variables from netcdf files - it's something which really makes using spyder interactively quite impossible.

I'd be more than happy to provide more information/data/examples here if it would be helpful in isolating the issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-12T06:35:58Z_

@-pauldurack: Thanks for your offering, it's very valuable. Please open another issue and upload an example data set you're seeing freezes with. This issue was about matlab files, and it's already solved.

**Summary:** Spyder freezes when loading large matlab files  \<span class="oldvalue"> (was: Spyder freezes when loading large data sets) \</span>  
  **Status:** WontFix  
  **Labels:** -MS-v2.3.2

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:48:48Z_

issue #1326 has been merged into this issue.

**Comment by durack1** [comment]
@ccordoba12 I've also experienced the same slow down/non-responsiveness when loading ~large matrices from netcdf files (using the `UV-CDAT` package with `Spyder 3.0.0b1` installed)..

What information do you need to get to the bottom of this issue?

**Comment by ccordoba12** [comment]
@durack1, as I said a couple of comments above, we need example data to test and fix this issue. But please open a new issue for that.

**Comment by durack1** [comment]
@ccordoba12 thanks for the prompt, new issue outlined at #2748
