### ISSUE TITLE
internal problem

### ISSUE THREAD

**Issue by benceahaver** [spyder-ide/spyder#19692]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
%reset #in the command line, before I just ran a script and I wanted to clear all the variables. 
I also tried to restart kernel but I received again the message of internal problem.

**Comment by ccordoba12** [comment]
Hey @benceahaver, thanks for reporting. This problem is fixed in a more recent Spyder version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2

If that doesn't work or take too much time, please run

    conda remove spyder
    conda install spyder=5.3.3
