### ISSUE TITLE
import circle doesn't work and console section say "It seems you're trying to use a module that doesn't come with our installer."

### ISSUE THREAD

**Issue by Mohibul-Islam-Sazib** [spyder-ide/spyder#19708]
### What steps will reproduce the problem?

from circle import Circle

circles = [ Circle(0, 0, 4), Circle(4, 2, 1) ]

for circle in circles:
    print("         Info:", circle)
    print("         Area: {:.2f}".format(circle.area()))
    print("Circumference: {:.2f}".format(circle.circumference()))
    print()

if circles[0] == circles[1]:
    print("Circles are equal.\n")
else:
    print("Circles are not equal.\n")

## Versions

* Spyder version: 5.3.3  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.1.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.14.0 (OK)
keyring >=17.0.0                     :  23.8.2 (OK)
nbconvert >=4.0                      :  7.0.0 (OK)
numpydoc >=0.6.0                     :  1.4.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.1 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0                 :  1.5.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.1.10                   :  0.2.1 (OK)
qtawesome >=1.0.2                    :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0             :  5.3.2 (OK)
qtpy >=2.1.0                         :  2.2.0 (OK)
rtree >=0.9.7                        :  1.0.0 (OK)
setuptools >=49.6.0                  :  65.3.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.3.3;<2.4.0        :  2.3.3 (OK)
textdistance >=4.2.0                 :  4.4.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  23.2.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.5.3 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.4.3 (OK)
scipy >=0.17.0                       :  1.9.1 (OK)
sympy >=0.7.3                        :  1.11 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Mohibul-Islam-Sazib, thanks for reporting. I have a couple of questions for you:

1. Where is your `circle.py` file located? Please note that it needs to be placed next to the file where you're importing it or else you'll get the ImportError you're seeing now.
2. Are you using a Spyder project for your code?

**Comment by dalthviz** [comment]
Just in case, I think the files definition for this exercise are available here: https://gist.github.com/nomicos/941f1a9f6ef816d5e795bf6758eb20fe (note that there you have a `circle.py` and a `main.py` files, and you need to have both files to run the code on the `main.py` file)

**Comment by Mohibul-Islam-Sazib** [comment]
> Just in case, I think the files definition for this exercise are available here: https://gist.github.com/nomicos/941f1a9f6ef816d5e795bf6758eb20fe (note that there you have a `circle.py` and a `main.py` files, and you need to have both files to run the code on the `main.py` file)

I have tried this link of 2 separate code. First one work but I don't understand which I should type on print section to show the result. Second one doesn't work and show same error on my console which is "It seems you're trying to use a module that doesn't come with our installer". Can you please explain why second one don't work on my Spyder and which way the second will be running.

**Comment by dalthviz** [comment]
Are you running the code from the files or just copy-pasting it on the console? Basically, the `circle.py` has inside a class definition and the `main.py` uses that class definition by importing the `circle.py` module and prints a result.

To be able to run the code, you need to create locally `circle.py` and `main.py` in the same directory then use Spyder to open `main.py` and finally use `F5` or click the green arrow in the Spyder toolbar while the current file open inside Spyder is `main.py`

Seems like the issue here is not directly related with Spyder but the way you are trying to run the code. If you still have issues please upload a .gif or video here to check how are you running the code so we could provide further guidance.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
