### ISSUE TITLE
gg

### ISSUE THREAD

**Issue by sharkliao1122** [spyder-ide/spyder#19709]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
#輸入變數
name1 = input()
age = input()
years = input()

#計算
age_new = int(age) + int(years)

#輸出結果
sentence = "Hi " + name1 + "! " + "In " + years + " " + "will be " + str(age_new)

**Comment by ccordoba12** [comment]
Hey @sharkliao1122, thanks for reporting. This problem is fixed in a more recent Spyder version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2

If that fails or takes too much time, you need to run

    conda remove spyder
    conda install spyder=5.3.3
