### ISSUE TITLE
input doesnt work

### ISSUE THREAD

**Issue by yigiteksi07** [spyder-ide/spyder#19711]
### What steps will reproduce the problem?

using input code sends me to issue reporter almost always like this
test2word = input("Tell me your age: ")
test2num = int(test2word)
print("Wow! Your age is ", test2num)

**Comment by yigiteksi07** [comment]
self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
it shows this on details

**Comment by ccordoba12** [comment]
Hey @yigiteksi07, thanks for reporting. This problem is fixed in a more recent Spyder version. Please update by closing Spyder, opening the Anaconda Prompt and running there

    conda update anaconda
    conda install spyder=5.2.2

If that takes too much time or doesn't work for you, you need to the following commands instead

    conda remove spyder 
    conda install spyder=5.3.3
