### ISSUE TITLE
Spyder for dedicated environment works from anaconda prompt and [well, almost] works from standalone shortcut

### ISSUE THREAD

**Issue by Tunneller** [spyder-ide/spyder#19715]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ X Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 5.3.3 launches fine from base anaconda environment, also launches fine if I launched from command line while inside an activated new environment. Spyder also launches fine if I uses the standalone shortcut and use the default settings. 

However, if I change the python interpreter to point to, say,
`C:/Users/johnl/anaconda3/envs/Flask/python.exe`
i.e. use the python in the new activated environment then the kernel refuses to start with "An error ocurred while starting the kernel: The system cannot find the path specified". It does not say what that path is, and I can't find the path in the log file. It hangs.

However, if I click Ctrl-T or otherwise launch a new console then it does not say "An error ocurred..." instead it just says "The system cannot find the path specified", and now it happily gives me a [1]: prompt. Everything works fine (in particular, I am in the new environment). Sometimes [cannot consistently repeat?] if I wait long enough I will get a [1]: prompt even in the original bad console.

It seems unfair to ask you guys to debug my conda environment, where doubtless the problem lies, but can you give any hints? E.g. does it write anywhere the name of the path that it had been looking for? [I cannot find in the logs]. Consider that I can get a working system, then is there something I can print (sys.modules, etc) that might identify what is missing.

### What steps reproduce the problem?

1.  Fresh installation of spyder 5.3.3 
2.  Conda to create new environment
3.  Install a gazilillon packages, some with conda -c intel and some with pip [sorry, I know....]
4.  Start spyder from shortcut

### What is the expected output? What do you see instead?
Expected kernel to start

### Paste Traceback/Error Below (if applicable)

An error ocurred while starting the kernel
The system cannot find the path specified.

## Versions
Python 3.9.13 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Windows 10 
```
Package                       Version
----------------------------- -----------
alabaster                     0.7.12
anaconda-client               1.11.0
anaconda-navigator            2.3.1
anyio                         3.6.1
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.6.6
atomicwrites                  1.4.1
attrs                         21.4.0
autopep8                      1.6.0
Babel                         2.10.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.2
beautifulsoup4                4.11.1
binaryornot                   0.4.4
black                         22.8.0
bleach                        5.0.1
brotlipy                      0.7.0
certifi                       2022.6.15
cffi                          1.15.1
chardet                       4.0.0
click                         8.0.3
cloudpickle                   1.6.0
clyent                        1.2.2
colorama                      0.4.4
conda                         22.9.0
conda-build                   3.22.0
conda-content-trust           0.1.3
conda-package-handling        1.8.1
conda-repo-cli                1.0.4
conda-token                   0.4.0
conda-verify                  3.4.2
cookiecutter                  2.1.1
cryptography                  37.0.1
cvxopt                        1.3.0
cycler                        0.11.0
debugpy                       1.6.3
decorator                     5.0.9
defusedxml                    0.7.1
diff-match-patch              20200713
docutils                      0.18.1
entrypoints                   0.4
fastjsonschema                2.16.2
filelock                      3.6.0
flake8                        4.0.1
fonttools                     4.25.0
future                        0.18.2
glob2                         0.7
idna                          2.10
imagesize                     1.4.1
importlib-metadata            4.11.4
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.16.0
ipython                       7.33.0
ipython-genutils              0.2.0
ipywidgets                    8.0.2
isort                         5.10.1
jaraco.classes                3.2.2
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        3.0.1
jinja2-time                   0.2.0
json5                         0.9.6
jsonschema                    4.16.0
jupyter_client                7.3.5
jupyter_core                  4.11.1
jupyter-server                1.19.1
jupyterlab                    3.4.8
jupyterlab-pygments           0.2.2
jupyterlab-server             2.10.3
jupyterlab-widgets            3.0.3
keyring                       23.9.3
kiwisolver                    1.3.2
lazy-object-proxy             1.7.1
libarchive-c                  2.9
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.6
mccabe                        0.6.1
menuinst                      1.4.18
mistune                       2.0.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
more-itertools                8.14.0
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.2.1
nbclassic                     0.4.4
nbclient                      0.6.8
nbconvert                     7.1.0
nbformat                      5.6.1
nest-asyncio                  1.5.6
notebook                      6.4.12
notebook-shim                 0.1.0
numexpr                       2.8.3
numpy                         1.23.1
numpydoc                      1.4.0
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.5.0
paramiko                      2.11.0
parso                         0.8.3
pathspec                      0.10.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.1.2
pkginfo                       1.8.3
platformdirs                  2.5.2
pluggy                        1.0.0
ply                           3.11
prometheus-client             0.14.1
prompt-toolkit                3.0.31
psutil                        5.9.0
ptyprocess                    0.7.0
pycodestyle                   2.8.0
pycosat                       0.6.3
pycparser                     2.21
pydocstyle                    6.1.1
pyflakes                      2.4.0
Pygments                      2.13.0
PyJWT                         2.3.0
pylint                        2.9.6
pyls-spyder                   0.4.0
PyNaCl                        1.5.0
pyOpenSSL                     22.0.0
pyparsing                     3.0.9
PyQt5                         5.15.7
PyQt5-sip                     12.11.0
PyQtWebEngine                 5.15.4
pyrsistent                    0.18.1
PySocks                       1.7.1
python-dateutil               2.8.2
python-lsp-black              1.2.1
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.5.0
python-slugify                6.1.2
pytoolconfig                  1.2.2
pytube                        12.1.0
pytz                          2022.1
pywin32                       302
pywin32-ctypes                0.2.0
pywinpty                      2.0.2
PyYAML                        6.0
pyzmq                         23.2.0
QDarkStyle                    3.0.3
qstylizer                     0.2.2
QtAwesome                     1.1.1
qtconsole                     5.3.2
QtPy                          2.2.1
requests                      2.25.1
rope                          1.3.0
Rtree                         1.0.0
ruamel-yaml-conda             0.15.100
Send2Trash                    1.8.0
setuptools                    58.0.4
sip                           6.6.2
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.3.3
spyder-kernels                2.3.3
terminado                     0.16.0
text-unidecode                1.3
textdistance                  4.5.0
three-merge                   0.1.1
tinycss2                      1.1.1
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
tornado                       6.2
tqdm                          4.62.3
traitlets                     5.4.0
typing_extensions             4.1.1
ujson                         5.4.0
Unidecode                     1.3.6
urllib3                       1.26.11
watchdog                      2.1.9
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.4.1
whatthepatch                  1.0.2
wheel                         0.37.1
widgetsnbextension            4.0.3
win-inet-pton                 1.1.0
wincertstore                  0.2
wrapt                         1.12.1
yapf                          0.32.0
zipp                          3.6.0
```
### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  7.1.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.23.1 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by Tunneller** [comment]
Hmmm. Related to #19194 perhaps. That discusses how the first console gets different treatment to subsequeny consoles

**Comment by Tunneller** [comment]
Actually, looks identical to #17252. That issue is flagged as "closed" but I dont see the resolution??

**Comment by dalthviz** [comment]
Hi @Tunneller thank you for the feedback and checking related issues! The message regarding the `"An error ocurred while starting the kernel: The system cannot find the path specified"` message just happens when launching the standalone installer Spyder version with a custom interpreter, right? Did you install the Spyder standalone version just for your user or for all users on your machine?

**Comment by Tunneller** [comment]
I installed spyder with conda. I do not recall being asked about users.  The only "user" with a .spyder-py3 subfolder is me. So if I had to guess then I would say it was installed just for me.

If I launch spyder by typing C:\Users\johnl\anaconda3\Scripts\spyder.exe then everything works perfectly. The odd behaviour is when launching spyder from the Windows Start Menu. Looking at the definition in the Startup folder, the command to initiate is
 
C:\Users\johnl\anaconda3\pythonw.exe C:\Users\johnl\anaconda3\cwp.py C:\Users\johnl\anaconda3 C:\Users\johnl\anaconda3\pythonw.exe C:\Users\johnl\anaconda3\Scripts\spyder-script.py

If I type that command then spyder does this wierd only-working-in-not-the-first-console.

For both ways of launching then I printed sys.path and they were identical

**Comment by Tunneller** [comment]
I checked sys.path for all of the directories and they are all valid ** except ** one of them is null: ''

**Comment by dalthviz** [comment]
Could it be possible for you to create a new env, install Spyder there, and use the shortcut for that new env Spyder installation and see if the problem is still happening?

**Comment by Tunneller** [comment]
I had been thinking along the same lines... I installed Spyder into the same env. It works with default interpreter and the desired interpreter but I suppose that is not a surprise as they are the same. Then I created an "empty" new conda env and installed Spyder there and it could use both default and "dedicated" python interpreters.

Suitably emboldened, I removed spyder from base environment (which turned my python into 3.9.7, which was odd) so I then reinstalled conda-forge spyder and installed python 3.9.13 and for good luck did conda update conda and ....

:-(

Same thing: when launched as 
`C:\Users\johnl\anaconda3\pythonw.exe C:\Users\johnl\anaconda3\cwp.py C:\Users\johnl\anaconda3 C:\Users\johnl\anaconda3\pythonw.exe C:\Users\johnl\anaconda3\Scripts\spyder-script.py`

then if a non-default interpreter is chosen then the first console dies but opening a second console from the hamburger menu is just fine. [In this last case, as before, it says a path can't be found but there is no mention in the debug.log what is that path which is missing.

I read somewhere about pywin32 causing this kind of conda-second-console behaviour so I also reinstalled pywin32. Did nothing. Mystery: (a) what is the missing path and (b) why does it kill the first console but not subsequent ones.

I guess I have a few workarounds.... But frustrating not to be able to solve.

**Comment by dalthviz** [comment]
Thank you for the new info @Tunneller ! Did you had previously mixed conda channels in your base env (installing Spyder from conda-forge while the rest of the env is using packages from the default channel)? Could it be that having mixed packages on your base env causes this?

Could you check the differences between the Spyder shortcut on your base env and the one created with the new env where using custom interpreters works for you? 

Any new info to understand what is happening here is greatly appreciated!

**Comment by dalthviz** [comment]
Closing due to lack of response
