### ISSUE TITLE
PYTHONPATH not seen by Spyder after updating to 5.3.3?

### ISSUE THREAD

**Issue by mmagnuski** [spyder-ide/spyder#19724]
Hi,

I've just updated Spyder to version 5.3.3 (I had 5.0.something previously IIRC). Now packages that I had accessible via PYTHONPATH in Spyder previously are no longer found (importing them fails). The PYTHONPATH contents are seen from the console that I start Spyder from (`echo %PYTHONPATH%` lists the contents correctly), but `os.environ['PYTHONPATH']` in Spyder console gives `KeyError: 'PYTHONPATH'`. This happens in the first console I have in Spyder, but the problem persists after restarting the console or opening another one.
I can add the paths I need to sys.path of course, but it would be nice if that worked like it used to. Maybe this is related to #19194?

**Comment by mmagnuski** [comment]
Ok, I noticed now that under Tools there is `PYTHONPATH manager`, where I can import paths. I think it would be nice if either PYTHONPATH was imported by default the first time Spyder is run, or if there was some kind of information that the way PYTHONPATH is handled has changed.

**Comment by mrclary** [comment]
@mmagnuski and @dalthviz, this is not related to #18942 (which was not reproducible) but _is_ related to #19194, as @mmagnuski supposed.

@ccordoba12 was planning to close #19194 and open a different PR after our discussion about this issue (I think we have notes on HackMD). The bottom line is that `PYTHONPATH` will be imported by default. We'd have to follow up with @ccordoba12 to see if that will make it into 5.4.0, but I think the plan was that it would.

**Comment by ccordoba12** [comment]
> We'd have to follow up with @ccordoba12 to see if that will make it into 5.4.0, but I think the plan was that it would.

Yeah, I'm planning to work on that during the weekend.
