### ISSUE TITLE
exit() lets the kernel die

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1974]
_From [robert.p...@mykolab.com](https://code.google.com/u/113841535926527526275/) on 2014-09-19T02:23:28Z_

I hope this is the right issue tracker for my problem:

I am using WinPython. When I am creating a new script with the command exit(), and run it within Spyder, this command kills the kernel:

"""
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.
"""

What's the right way to stop a script in this runtime environment?

My workaround so far is to encapsulate the code into a 'main' function and use 'return' inside.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1974_

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-09-19T02:11:49Z_

exit() is used to terminate python, so this is the intended behavior: https://docs.python.org/2/library/sys.html#sys.exit You can also put your code inside a "if" block, but using functions is generally the right thing to do.

**Comment by spyder-issues-migrator** [comment]
_From [robert.p...@mykolab.com](https://code.google.com/u/113841535926527526275/) on 2014-09-19T05:13:57Z_

So do I have to rewrite every (3rd party) script containing exit() that I want to run within Spyder? Doesn't exit() just throw an exception that should be cought be the runtime environment?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-09-19T16:58:51Z_

You can catch it yourself in your code if you need. It is bad practice to use exit() in libraries, raising an useful exception is way better.
I'm against including this in spyder because right now it does the documented thing. I'm not even sure it's possible to do since the exception should be caught inside IPython itself.

**Comment by spyder-issues-migrator** [comment]
_From [robert.p...@mykolab.com](https://code.google.com/u/113841535926527526275/) on 2014-09-22T00:12:59Z_

In http://mail.scipy.org/pipermail/ipython-dev/2014-September/015019.html , Carlos Córdoba suggested to catch the expression via
    def f(): pass, get_ipython().ask_exit = f

.However, this causes the script not to stop at exit. I am now using
    def f(): raise Exception("Found exit()")
instead.

This closes this issue for me.

(Could Spyder catch this exception, s.t. the script is stopped in a more quiet way?)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:38:51Z_

**Status:** Done

**Comment by jondo** [comment]
@zbyna Here [your advice](https://github.com/spyder-ide/spyder/issues/2183#issuecomment-76406158) does not work, because your `app` is a `QApplication`, which I don't have.

**Comment by zbyna** [comment]
So sorry, I thought that the matter could be  that script was not finished correctly (as in my case with QApp) and the kernel died b/c of attempt to run the script twice. I have tried simple script and exit(0)
closes console, but when I add
``` python
from sys import exit
```
console is not closed. From my python beginner's point of view it is strange :smile:

**Comment by jondo** [comment]
For the record, I have listed several variants how Spyder users can deal with this [on stackoverflow](https://stackoverflow.com/a/25928378/1389680).

**Comment by ccordoba12** [comment]
Thanks a lot for that!
