### ISSUE TITLE
Spyder not responding

### ISSUE THREAD

**Issue by Vinodhini12** [spyder-ide/spyder#19759]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder is not responding , I even tried resetting the spyder

### What steps reproduce the problem?

1. after i tried to install spyder 5.3.3, and it showed that conflicts were found
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 3.10
![Uploading Untitled.jpg…]()

* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 11

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by Vinodhini12** [comment]
![Untitled](https://user-images.githubusercontent.com/69148519/194764420-278a685c-157d-49ba-a24f-bcc8bfd85380.jpg)

**Comment by Vinodhini12** [comment]
![Screenshot 2022-10-09 204016](https://user-images.githubusercontent.com/69148519/194764510-6fd3cf71-fbd6-400d-96f5-3dd313a58db5.jpg)

**Comment by Vinodhini12** [comment]
![Screenshot 2022-10-09 204332](https://user-images.githubusercontent.com/69148519/194764675-fb2cbbca-471c-40cf-999e-e1a445d4af82.jpg)
![Screenshot 2022-10-09 204428](https://user-images.githubusercontent.com/69148519/194764707-d2043f63-4b5e-44f5-b0a0-5bc76b8bc449.jpg)

**Comment by ccordoba12** [comment]
Hey @Vinodhini12, thanks for reporting. Please open the Anaconda Prompt and run there

    conda activate spyder-cf
    conda list

and post the output here.

Also, what command are you using to update Spyder?

**Comment by Vinodhini12** [comment]
the command i was using to update spyder was conda update spyder=5.3.3

**Comment by MohamadThabet** [comment]
I am not sure if this is still relevant. I was able to fix this by upgrading to spyder 6 and using python 3.11.1
