### ISSUE TITLE
mysqlconnector installer not working

### ISSUE THREAD

**Issue by Vinodhini12** [spyder-ide/spyder#19760]
(base) C:\Users\Roshini>conda install -c anaconda mysql-connector-python
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - mysql-connector-python -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by ccordoba12** [comment]
Hey @Vinodhini12, thanks for reporting. This part of your error message

> Specifications:
>
>    mysql-connector-python -> python[version='>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']
>
> Your python: python=3.9

means that `mysql-connector-python` is not available for Python 3.9. That's why you can't install it.

So the solution is to create an environment with Python 3.7 and install it there:

    conda create -n myenv python=3.7 mysql-connector-python spyder-kernels

The last package will allow you to use that environment from Spyder, as described in our documentation:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

**Comment by ccordoba12** [comment]
If you have additional problems or questions on how to install packages with conda, we recommend you to post them in:

https://github.com/ContinuumIO/anaconda-issues

That's because this place is meant to report internal problems related to Spyder.

**Comment by Vinodhini12** [comment]
how can i installl packages in this env??

**Comment by ccordoba12** [comment]
You need to always open the Anaconda Prompt and run there

    conda activate myenv
    conda install <name-of-package-to-install>

**Comment by Vinodhini12** [comment]
yah i did installed, but when i import it in spyder python it is showing module not found

**Comment by Vinodhini12** [comment]
mysql-connector-python is the package i need to install
It is also in the conda list
