### ISSUE TITLE
Spyder 3.2.3 doesn't start

### ISSUE THREAD

**Issue by buonotech** [spyder-ide/spyder#19798]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I launch spyder from Anaconda suite in a specific environment, It doesn't start: Exit code: 139
In other environments with different version of spyder there is no problem.

### What steps reproduce the problem?

1. Launch Spyder from Anaconda console
2. 
3. 

### What is the expected output? What do you see instead?
Spyder running. I get just an error message.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.3
* Python version: 3.6.13
* Qt version: 5.9.7
* PyQt version: 
* Operating System name/version: Linux Mint 20

### Dependencies

I'm not able to open Spyder
```
PASTE DEPENDENCIES HERE
```

**Comment by buonotech** [comment]
Hi,
I've tried to install the new versione of Spyder, but I got a message saying "Spyder==5.3.3 Cannot be installed on this environment".

**Comment by dalthviz** [comment]
Oh I see, that's probably because of your Python version on that env (3.6.11). I think the latest Spyder release that supports Python 3.6 is 5.2.2

Could you try to update to Spyder 5.2.2?

Let us know if you are able to update to that version

**Comment by buonotech** [comment]
Unluckily I get the same error message.

I was making another attempt: I re-created the environment with another name installing the different packages. 
Spyder 5.2.2 was installed automatically by Conda, but when I launch it I got this:


>Traceback (most recent call last):
File "/home/xap/anaconda3/envs/Cazzaso3/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 29, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
>
>The above exception was the direct cause of the following exception:
>
>Traceback (most recent call last):
File "/home/xap/anaconda3/envs/Cazzaso3/bin/spyder", line 11, in 
sys.exit(main())
File "/home/xap/anaconda3/envs/Cazzaso3/lib/python3.8/site-packages/spyder/app/start.py", line 233, in main
from spyder.app import mainwindow
File "/home/xap/anaconda3/envs/Cazzaso3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 57, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/home/xap/anaconda3/envs/Cazzaso3/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 37, in 
raise QtModuleNotInstalledError(
qtpy.QtModuleNotInstalledError: The QtWebEngineWidgets module was not found. It must be installed separately as PyQtWebEngine.

**Comment by dalthviz** [comment]
Could you try creating or modifying your envs specifing also the `pyqt` version to be <=5.9.2? I think `pyqtwebengine` is also not available for Python 3.6 and it is needed for `pyqt` >=5.12

**Comment by buonotech** [comment]
Hi,
at the moment in the first environment pyqt version was already 5.9.2 therefore it isn't working yet.
In the new environment created, I changed the version in 5.9.2 and now when I launch Spyder it starts regularly.

**Comment by dalthviz** [comment]
Seems like you managed to create then an env which works with Python 3.6 and Spyder 5.2.2 :+1:

Regarding your initial env with Python 3.6, maybe if you can get some traceback we could check it but otherwise there isn't much we can do, sorry :/

**Comment by dalthviz** [comment]
Closing since no other info was provided
