### ISSUE TITLE
using python 2.7.6.1 backspace, delete, carriage return stopped working

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1980]
_From [tammyx...@gmail.com](https://code.google.com/u/101910058599936005390/) on 2014-09-22T18:19:23Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.1.0 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.2.1 (OK) 

What steps will reproduce the problem?

 1.Run python xy
2.Open spyder
3.Open .py file and try using backspace/delete/return 

What is the expected output? What do you see instead?

 Nothing occurs when those three keys are pressed 

Please provide any additional information below

. Started occurring within past three days

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1980_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:37:53Z_

No idea but it seems really weird.

**Status:** Invalid

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:38:11Z_

Try to update to 2.3.1

**Comment by VagishAdhav** [comment]
Why this is invalid? facing same issue.
