### ISSUE TITLE
sphinx is misplaced in install_requires

### ISSUE THREAD

**Issue by yurivict** [spyder-ide/spyder#19812]
[here](https://github.com/spyder-ide/spyder/blob/master/setup.py#L242)

Sphinx is a documentation generating software. It should be in build_requires, not in install_requires.

**Comment by ccordoba12** [comment]
Hey @yurivict, thanks for reporting. Unfortunately, that's not correct. Sphinx is what powers the rich viewer for docstrings we have in our Help pane, which is described here:

http://docs.spyder-ide.org/current/panes/help.html

**Comment by ccordoba12** [comment]
By the way, that's easily testable by removing Sphinx from your current env and then running Spyder. Then you'd have noticed that we actually call Sphinx internally.
