### ISSUE TITLE
Spyder doesn't open on MyBinder

### ISSUE THREAD

**Issue by fomightez** [spyder-ide/spyder#19832]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description** & **Steps to Reproduce**

## Problem Description

Spyder never opens in MyBinder sessions launched from this repo presently. 

When the sessions opens and you double click on the Spyder icon on the left side of the screen it doesn't open like it should. Splash screen never comes up and there is no indication though. You just wait forever for nothing, it seems.

### What steps reproduce the problem?

1.  Try opening Spyder in sessions launched from https://mybinder.org/v2/gh/spyder-ide/spyder/master?urlpath=%2Fdesktop (which is the default link on the main page and uses the last commit ([Oct 11](https://github.com/spyder-ide/spyder/commits/master/binder)) by default.). Spyder FAILS to open in the session. It just hangs forever with the splash screen never coming up. No error is shown.

3. If you try launching with the previous commit, Spyder still opens by double-clicking on the icon in such sessions. The splash screen comes up after several seconds and Spyder opens. STILL WORKS using Aug 29th version at https://github.com/spyder-ide/spyder/commit/a3f49fa9ba51f40e6fe1e8d52768265b1da2f21f. The link to launch is:
https://mybinder.org/v2/gh/spyder-ide/spyder/a3f49fa9ba51f40e6fe1e8d52768265b1da2f21f?urlpath=%2Fdesktop

### Underlying cause?

It seems like the change was small in the binder directory, and so there is a chance it is something else **and not simply what was changed there**? I'm not quite sure. I only tried the October 11th commit (actually did it specifically, as well, and not just default) and the August 29th ones because that was only changes showing when I clicking into the binder directory.     

I did note someone else did make an issue post a few days ago saying they were seeing Spyder not opening, but that seemed to get sorted.

**Comment by dalthviz** [comment]
Hi @fomightez thanks for the feedback! Checking seems like an error is being raised at launch:

![imagen](https://user-images.githubusercontent.com/16781833/195916427-0bd7f8b6-dcd5-483e-b987-3489d60f5e85.png)

Could this be related with the changes done on the `bootstrap.py`  script recently @ccordoba12 @mrclary ? Maybe we need to change the shortcut to use the home directory as working directory so `spyder` is available as a module?

**Comment by fomightez** [comment]
I did try running that in the terminal, too. I should have added that since I did see that error. But I did that before I saw the old ones were working, and so I didn't know if I was on the right or wrong path there.  
*In theory*, your idea sounds good. However, I still don't see what broke it in the last couple of weeks, and so it's hard to say.  It seemed to work running in the Desktop before and I'm not seeing what would have changed to alter that.

**Comment by mrclary** [comment]
I'm not very familiar with Binder. How do you access it? Where is "the default link on the main page"? How do you build the image for an arbitrary commit or branch?
I tried building it [here](https://github.com/spyder-ide/spyder/pull/15761#issuecomment-1279385574), but it fails to build/launch.

**Comment by fomightez** [comment]
The `launch binder` badge features on the main page right below 'Project status' [here](https://github.com/spyder-ide/spyder#project-status).

To build for specific commits or branches go to the form [here](https://mybinder.org/) and fill it out. Where 'Git ref' is you can specify branch name or commit SHA.

**Comment by mrclary** [comment]
> The `launch binder` badge features on the main page right below 'Project status' [here](https://github.com/spyder-ide/spyder#project-status). It equates to the same link I placed above.

Aahh! okay, thanks.

> To build for specific commits or branches go to the form [here](https://mybinder.org/) and fill it out. Where 'Git ref' is you can specify branch name or commit SHA.

Yeah, I tried that and it didn't work... do you have a screen shot of a filled out form that yields a successful build?

**Comment by fomightez** [comment]
Which branch do you want?

**Comment by mrclary** [comment]
I tried 5.x

**Comment by fomightez** [comment]
Should be https://mybinder.org/v2/gh/spyder-ide/spyder/5.x?urlpath=%2Fdesktop ?

**Comment by mrclary** [comment]
It starts a JupyterLab application, not a desktop with a Spyder shortcut

**Comment by fomightez** [comment]
Yes, the default form is for general usage. There's other tricks. You want:  
https://mybinder.org/v2/gh/spyder-ide/spyder/5.x?urlpath=%2Fdesktop

**Comment by mrclary** [comment]
> Should be https://mybinder.org/v2/gh/spyder-ide/spyder/5.x?urlpath=%2Fdesktop ?

Nope, I get https://mybinder.org/v2/gh/spyder-ide/spyder/5.x
What am I doing wrong?

**Comment by mrclary** [comment]
So I have to manually add `?urlpath=Fdesktop`?

**Comment by fomightez** [comment]
Yes.

**Comment by mrclary** [comment]
@fomightez, thanks for your help. I got binder working. I hid our comments just to keep this issue discussion cleaner.

**Comment by mrclary** [comment]
@dalthviz, you are correct; the offending PR is #19742.
There are two issues:
- The recent changes to `bootstrap.py` for detecting changes to/from the master branch use `spyder` utilities. Since the import occurs before `install_dev_repos`, it is implicitly assumed that `spyder` is already installed, which is not the case for the Binder environment. This may also be a problem for other developer environments under certain circumstances.
- The recent changes to `bootstrap.py` have an explicit reference to `'spyder'` as the assumed repository name. Since Binder places the repository contents directly into the home directory, the repository name is not `'spyder'` but `'jovyan'`.

Possible solution:
Remove dependence of `spyder` in `bootstrap.py` prior to invocation of `install_dev_repos`
- Reference to the repository name (`DEVPATH.name`) should be obtained from `install_dev_repos`
- Use `subprocess` directly to invoke `git` instead of `find_git` and `run_program`
- The `boot_branch.txt` file should be placed in the repository at the top level instead of Spyder's configuration directory, and it will have to be `.gitignore`d

**Comment by ccordoba12** [comment]
@fomightez, could you explain why having Spyder work on Binder is so important to you? For us is very limited and kind of slow sometimes.

**Comment by fomightez** [comment]
@ccordoba12 Sorry, I somehow had missed your question about the importance until now. **Big thing is it avoids the, 'Works on my machine' dilemma.**  I like it because for trying things out or suggesting others to try things out, it's useful as a way that doesn't involve installing anything. Hence there's no chance they'll mess up their system just trying something. And the Spyder offering on Binder is a full IDE with PyQt working well.Therefore, some endeavors that don't work in a default MyBinder session can be easily done.

**Comment by jitseniesen** [comment]
As an additional data point, I tried to run Spyder via Binder yesterday because I wanted to show some Python in a lecture and the computers in the lecture halls don't have Python installed. Since it does not work, I will have to use notebooks (which is not an big issue for my lecture). This is the error message in my case, which suggests that the fault may be on our end:
```
Traceback (most recent call last):
File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgitpuller/handlers.py", line 79, in get
    gp = GitPuller(repo, repo_dir, branch=branch, depth=depth, parent=self.settings['nbapp'])
File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgitpuller/pull.py", line 78, in __init__
    raise ValueError(f"Branch: {self.branch_name} -- not found in repo: {self.git_url}")
ValueError: Branch: Solutions -- not found in repo: https://github.com/juanis2112/Spyder-Workshop
```

**Comment by ccordoba12** [comment]
Thanks for the feedback @jitseniesen. I'll take a look at improving Binder next week as described on issue #19902.

But how did you launch Binder? It seems our Binder-environments repo, right?

**Comment by fomightez** [comment]
> . Since it does not work,

@jitseniesen You can use the August 29th commit. Just not the very current stuff. I posted [the launch link](https://mybinder.org/v2/gh/spyder-ide/spyder/a3f49fa9ba51f40e6fe1e8d52768265b1da2f21f?urlpath=%2Fdesktop) in full glory at the top of this. You just have to get your students to use that one.  [yellkey](https://www.yellkey.com/) could be used to get it to them on the fly if you don't want to post it because it won't be the long-term solution.

**Comment by jitseniesen** [comment]
@fomightez Thanks for the info. 

@ccordoba12 I don't know how binder works, I simply clicked on the link on https://www.spyder-ide.org/ which points to https://hub.mybinder.turing.ac.uk/user/spyder-ide-binder-environments-ch8fkb1b/git-pull?repo=https%3A%2F%2Fgithub.com%2Fjuanis2112%2FSpyder-Workshop&urlpath=desktop%2F&branch=Solutions . Perhaps that URL is outdated? 

I did not realize that this issue was actually already closed. Having binder run a stable release as described in #19902 would be perfect for my use case.

**Comment by fomightez** [comment]
@jitseniesen , you can adapt the link I gave you to still do the nbgit-pull, too. I'll try to get back here and edit this to add it. The Jupyter/Binder community provides a form for generating the links [here](https://jupyterhub.github.io/nbgitpuller/link). You need to click on the 'Binder' tab on the right.

The link you posted that reads `https://hub.mybinder.turing.ac.uk/user/spyder-ide-binder-environments-ch8fkb1b/git-pull?repo=https%3A%2F%2Fgithub.com%2Fjuanis2112%2FSpyder-Workshop&urlpath=desktop%2F&branch=Solutions` was a particular temporary session launched via the mybinder service. The specific session expires and then the old link to that particular instance won't work. You have to go through the main mybinder link to get served a new session.

**Comment by jitseniesen** [comment]
I added the above issue to the website repo so that we don't forget to update the binder link.
