### ISSUE TITLE
Feedback about auto-update mechanism for installers

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#19868]
Before releasing 5.4.0, I'd like for us to address two issues with this new mechanism:

1. Spyder can't be closed quickly after startup because the thread that checks for updates takes too much time to complete and we wait for it to finish before closing. Is there a way to simply kill that thread? If that's not possible, I think we could start it with a timer that waits a minute or two after Spyder starts to check for updates. That would work similarly to the way we check for dependencies.
2. I think we should only show the status bar widget that handles updates for our Windows and Mac installers. We have multiple ways to install Spyder and I think in those cases that widget would be of little value to users.

**Comment by dalthviz** [comment]
@ccordoba12 I was checking this and I think the updates also have a timer already but with a lower timeout. Should I increase it? Currently for the updates the timer is set to 3000 while for the dependencies is set to 10000

**Comment by ccordoba12** [comment]
> Currently for the updates the timer is set to 3000 while for the dependencies is set to 10000

Ok, then I think we should increase it to 30000 or perhaps even 60000. If Spyder has been running for at least that amount of time, it means users are already invested on using it for a long session.
