### ISSUE TITLE
Unable to launch Spyder from `bootstrap.py` on Windows

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#19865]
## Problem Description

A traceback appears when launching Spyder from `bootstrap.py`. This happened to me will try to check locally https://github.com/spyder-ide/spyder/pull/19855

Seems like is related with the subprocess that calls git to check the branch info. ~I guess on Windows instead of `"/usr/bin/env"` we need to use `"cmd.exe"` or something similar?~

Edit:

Just in case, seems like on Windows something like the following works:

```python
result = subprocess.run(
        ["git.cmd", "merge-base", "--fork-point", "master"], shell=True
    )
```

### What steps reproduce the problem?

Try to run Spyder from the `bootstrap.py` script on Windows

### What is the expected output? What do you see instead?

Spyder launching, instead a traceback

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "E:\Acer\Documentos\Spyder\Spyder otros\carlos\spyder\bootstrap.py", line 83, in <module>
    result = subprocess.run(
  File "C:\Users\dalth\anaconda3\envs\spyder-dev\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\dalth\anaconda3\envs\spyder-dev\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\dalth\anaconda3\envs\spyder-dev\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado


```

**Comment by sylvain-bougnoux** [comment]
yes same issue, seems to be introduced by @mrclary

Author:			Ryan Clary <9618975+mrclary@users.noreply.github.com>
Date:			2 days ago (15-10-22 00:24:04)
Commit hash:	ac6d16b010386849ee121cb5096be0fbad477d08
Child:			0198e709
Parent:			50ca5f7f

**Comment by ccordoba12** [comment]
@dalthviz was faster and already submitted a PR!

**Comment by ccordoba12** [comment]
Sorry, this was my bad too because I merged @mrclary's PR without waiting for @dalthviz to review it.
