### ISSUE TITLE
Spyder 5.3.3 IPython-console not properly doing `input()` on Mac

### ISSUE THREAD

**Issue by a2-c-martin** [spyder-ide/spyder#19888]
## Problem Description
In spyder 5.3.3 the execution of input() on silicon Macs does not work properly
->spyder 5.2.2 is working perfect

### What steps reproduce the problem?

```python
while True:
    print(input("Enter something:"))
```

### What is the expected output? What do you see instead?

EXPECTED:
```
Enter something:1
1

Enter something:1
1

Enter something:1
1
```

WHATS HAPPENING:

```
Enter something:1
1Enter something:
111
```

### Paste Traceback/Error Below (if applicable)
no errors

## Versions

* Spyder version: 5.2.2
* Python version: 3.9
* Qt version: 5.15.2
* PyQt version: PyQt5 5.15.7
* Operating System name/version: MacOS 12.5.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @a2-c-martin, thanks for reporting. I thought this was fixed already, but we'll take a look at it.

@mrclary, could you check if you're getting the same problem on Mac? Thanks!

**Comment by a2-c-martin** [comment]
Dear Carlos

Thank you!
Today we had This issue on 3 Machines: apple m1 and MacBook Air M2. So i thought this seems remarkable.
Finally I installed spyder 5.2.2 in a new Anaconda environment. This one works properly.:)
Regards
Martin

Am 19.10.2022 um 17:58 schrieb Carlos Cordoba ***@***.***>:

﻿

Hey @a2-c-martin<https://github.com/a2-c-martin>, thanks for reporting. I thought this was fixed already, but we'll take a look at it.

@mrclary<https://github.com/mrclary>, could you check if you're getting the same problem on Mac? Thanks!

**Comment by mrclary** [comment]
I tested on 
Okay, I can confirm the following running from **bootstrap** on the latest 5.x commit:
- this issue _does_ manifest on macOS 12.6 (Intel)
- this issues _does not_ manifest on my Windows 10 or Ubuntu 20.04 VM

Note that the number of successful input handlings can vary. I found as little as 2 and as many as 14 in some cases.

Race condition of some kind?

![issue-19888](https://user-images.githubusercontent.com/9618975/196801993-7ef53c41-cab4-4e59-b3d5-6911f763ae0f.gif)

**Comment by ccordoba12** [comment]
@mrclary, could you check if removing this `if` and leaving the line below fixes the problem on Mac?

https://github.com/spyder-ide/spyder/blob/4db6cd0c78cf2c8c147ffa6bd3786f8e027bb2ce/external-deps/qtconsole/qtconsole/console_widget.py#L2486-L2487

**Comment by mrclary** [comment]
> @mrclary, could you check if removing this `if` and leaving the line below fixes the problem on Mac?
> 
> https://github.com/spyder-ide/spyder/blob/4db6cd0c78cf2c8c147ffa6bd3786f8e027bb2ce/external-deps/qtconsole/qtconsole/console_widget.py#L2486-L2487

That does solve the issue!
