### ISSUE TITLE
Error when opening Spyder

### ISSUE THREAD

**Issue by jcarag-personal** [spyder-ide/spyder#19892]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Internal error encountered when opening Spyder that causes an error box to constantly open.

**Comment by jcarag-personal** [comment]
Additional detail: iPython console unresponsive, seems to be stuck "Connecting to kernel..."

**Comment by dalthviz** [comment]
Hi @jcarag-personal , could you share your setup (OS, Python version, Spyder version, way you installed Spyder, etc)? Also, could you share the message or what the error box looks like? Without further info there is not much we can do, sorry :/

**Comment by texadactyl** [comment]
@dalthviz 
Github needs a count-down clock so that some of these issue reports can be tagged appropriately and closed when it appears that the issuer originator has lost interest for one reason or another!

**Comment by ccordoba12** [comment]
Agreed. There is a Github action (I think it's called probot) that can perform those things but we haven't had time to set it up.

Also, I'm going to close this to due lack of response from the original poster.

**Comment by dalthviz** [comment]
Thanks @texadactyl for the feedback! Indeed, some automatization to close, or at least to ping someone to check the issue, could be worthy. If you have any idea or more info on how we can improve this issue handling situation (like using a bot as @ccordoba12 mentioned) let us know!
