### ISSUE TITLE
Add  option "Copy to clipboard" for matplotlib figures

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#199]
_From [dimitri....@gmail.com](https://code.google.com/u/112741511649297883635/) on 2010-04-13T06:36:42Z_

What is the expected output? 

In the interatic console , plot(arange(4)), select the figure 1 widget as 
the active one, hit CNTRL + C to copy the figure to the clipboard for 
further processing, e.g in word,...

A similar function was implemented in Matlab What version of the product are you using? On what operating system? 1.1.0beta1 

Please provide any additional information below

. A suggestion for coding it I found on the web somewhere: 

first some help function first :

def env(name): 
    return os.environ.get( name, '' ) 

def getHomeDir(): 
    if sys.platform != 'win32': 
        return os.path.expanduser( '~' ) 
 
    homeDir = env( 'USERPROFILE' ) 
    if not valid(homeDir): 
        homeDir = env( 'HOME' ) 
        if not valid(homeDir) : 
            homeDir = '&#37;s&#37;s' &#37; (env('HOMEDRIVE'),env('HOMEPATH')) 
            if not valid(homeDir) : 
                homeDir = env( 'SYSTEMDRIVE' ) 
                if homeDir and (not homeDir.endswith('\\')) : 
                    homeDir += '\\' 
                if not valid(homeDir) : 
                    homeDir = 'C:\\' 
    return homeDir 

Add the following code to the widget where your figure canvas is embedded , 
class MatplotlibFigure(PluginWidget) in fugure.py

        self.cb = None #will be used for the clipboard 
        self.tempPath = getHomeDir() 
        self.tempPath = os.path.join(self.tempPath,'tempMPL.png')
        self.mpl2ClipAction = QtGui.QAction("Save to Clipboard",  self) 
        self.mpl2ClipAction.setShortcut("Ctrl+C") 
        self.addAction(self.mpl2ClipAction) 
                  
QtCore.QObject.connect(self.mpl2ClipAction,QtCore.SIGNAL("triggered()"), 
self.mpl2Clip) 
 
    def mpl2Clip(self): 
        try: 
            self.canvas.fig.savefig(self.tempPath) 
            tempImg = QtGui.QImage(self.tempPath) 
            self.cb = QtGui.QApplication.clipboard() 
            self.cb.setImage(tempImg) 
        except: 
            print 'Error copying figure to clipboard' 
            errorMsg = "Sorry: &#37;s\n\n:&#37;s\n"&#37;(sys.exc_type, sys.exc_value) 
            print errorMsg 
\#        savefig(fname, dpi=None, facecolor='w', edgecolor='w', 
\#        orientation='portrait', papertype=None, format=None, 
\#        transparent=False): 
 
I hope this helps

Regards,

Dimitri

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=199_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-02T07:51:19Z_

**Summary:** Add  option "Copy to clipboard" for matplotlib figures  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T13:28:41Z_

**Labels:** Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:09:31Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T12:57:07Z_

I think this probably worked for the old Spyder 1.0, but not now

**Status:** WontFix

**Comment by superlou** [comment]
Was this closed "won't fix" because of a project scope issue or simply that nobody was available to work on it? This would be really helpful for quick presentations.

**Comment by goanpeca** [comment]
@superlou this option is available via the new `Plots` panel on Spyder 4.0.0 to be released in a couple of weeks.

You can test the beta5 from here https://anaconda.org/spyder-ide/spyder/files using conda

**Comment by superlou** [comment]
Great timing, thanks! I'll check it out.
