### ISSUE TITLE
Quick improvements and fixes to run Spyder on Binder

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#19902]
Our Binder integration is broken or semi-broken right now. In yesterday's developer meeting we agreed to do the following quick steps to improve it:

* [x] Update `spyder-stable` branch in Binder-environments - https://github.com/spyder-ide/binder-environments/tree/61157cebbabfb15825a96497f16bc0d2afaea155
* [x] Update our docs to point to that branch- PR https://github.com/spyder-ide/spyder-docs/pull/336
* [ ] Add a new section to our Readme with a `launch|binder` button to that branch and remove the current button - PR https://github.com/spyder-ide/spyder/pull/19936
* [ ] Add a new instruction to our release instructions so that we don't forget to update our Binder images after each release - https://github.com/spyder-ide/spyder/pull/19936

spyder-stable branch binder link: https://mybinder.org/v2/gh/spyder-ide/binder-environments/spyder-stable?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252FSpyder-Workshop%26urlpath%3Ddesktop%252F%26branch%3Dmaster

**Comment by dalthviz** [comment]
Should we merge #19750 before proceding with the Binder-environments branch update @ccordoba12 ?

**Comment by ccordoba12** [comment]
Good idea, please do @dalthviz.

**Comment by dalthviz** [comment]
Done :+1:
