### ISSUE TITLE
spyder variable  explore columns too narrow

### ISSUE THREAD

**Issue by nankaimy** [spyder-ide/spyder#19911]
spyder5.2.2 variable  explore columns too narrow

![image](https://user-images.githubusercontent.com/7699602/197378891-b02e7a10-4dae-41e1-87cf-b9c3121bb4ec.png)

how to fix this ?

**Comment by dalthviz** [comment]
Hi @nankaimy thank you for the feedback. Could check if changing the preferences at `Preferences > Application > Interface > Screen resolution` help? Also, what happens if you click the header? Let us know!

**Comment by nankaimy** [comment]
Preferences > Application > Interface > Screen resolution not help

**Comment by nankaimy** [comment]
i installed the  Anaconda3-2022.10-Windows-x86_64.exe, its spyder is 5.2.2

**Comment by nankaimy** [comment]
but the spyder 5.3.3 is normal

**Comment by dalthviz** [comment]
So the columns space is okay with Spyder 5.3.3 right @nankaimy ? If that is the case then I will suggest you to stick with your Spyder 5.3.3 installation. However to understand better if this could be related with PyQt version you have installed, could you share your installation details (Spyder version, Python version, dependencies versions, SO, etc)? Let us know

**Comment by nankaimy** [comment]
the columns space is okay with Spyder 5.3.3 is right

**Comment by nankaimy** [comment]
Package                       Version
----------------------------- --------------------
absl-py                       1.3.0
alabaster                     0.7.12
anaconda-client               1.8.0
anaconda-navigator            2.3.2
anaconda-project              0.11.1
anyio                         3.6.2
aplus                         0.11.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.12.12
astropy                       5.1
atomicwrites                  1.4.1
attrs                         22.1.0
Automat                       20.2.0
autopep8                      1.6.0
Babel                         2.10.3
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
backports.tempfile            1.0
backports.weakref             1.0.post1
bcrypt                        3.2.2
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bitarray                      2.6.0
bkcharts                      0.2
black                         22.10.0
blake3                        0.3.1
bleach                        5.0.1
bokeh                         2.4.3
boto3                         1.25.2
botocore                      1.28.2
Bottleneck                    1.3.5
bqplot                        0.12.36
branca                        0.5.0
brotlipy                      0.7.0
cached-property               1.5.2
cachetools                    5.2.0
certifi                       2022.9.24
cffi                          1.15.1
chardet                       5.0.0
charset-normalizer            2.1.1
click                         8.1.3
cloudpickle                   2.2.0
clyent                        1.2.2
colorama                      0.4.6
colorcet                      3.0.1
commonmark                    0.9.1
comtypes                      1.1.14
conda                         22.9.0
conda-build                   3.22.0
conda-content-trust           0.1.3
conda-pack                    0.7.0
conda-package-handling        1.9.0
conda-repo-cli                1.0.20
conda-token                   0.4.0
conda-verify                  3.4.2
constantly                    15.1.0
contourpy                     1.0.5
cookiecutter                  2.1.1
cryptography                  38.0.2
cssselect                     1.1.0
cupy-cuda101                  9.6.0
cvxpy                         1.2.1
cx-Oracle                     7.0.0
cycler                        0.11.0
Cython                        0.29.32
cytoolz                       0.12.0
daal4py                       2021.6.0
dask                          2022.10.0
datashader                    0.14.2
datashape                     0.5.4
datatable                     1.1.0a0+pr3346.2187
debugpy                       1.6.3
decorator                     5.1.1
defusedxml                    0.7.1
diff-match-patch              20200713
dill                          0.3.6
distributed                   2022.10.0
dnspython                     2.2.1
docutils                      0.16
ecos                          2.0.10
entrypoints                   0.4
et-xmlfile                    1.0.1
etils                         0.8.0
exceptiongroup                1.0.0
fastapi                       0.85.1
fastjsonschema                2.16.2
fastrlock                     0.8
filelock                      3.8.0
flake8                        4.0.1
Flask                         1.1.2
flatbuffers                   2.0.7
flit_core                     3.7.1
fonttools                     4.38.0
frozendict                    2.3.4
fsspec                        2022.10.0
future                        0.18.2
gensim                        4.2.0
glob2                         0.7
greenlet                      1.1.3.post0
h11                           0.14.0
h5py                          3.7.0
HeapDict                      1.0.1
holoviews                     1.15.1
httptools                     0.5.0
hvplot                        0.8.1
hyperlink                     21.0.0
idna                          3.4
imagecodecs                   2022.9.26
imageio                       2.22.0
imagesize                     1.4.1
importlib-metadata            5.0.0
importlib-resources           5.10.0
incremental                   22.10.0
inflection                    0.5.1
iniconfig                     1.1.1
intake                        0.6.6
intervaltree                  3.0.2
ipydatawidgets                4.3.2
ipykernel                     6.16.2
ipyleaflet                    0.17.2
ipympl                        0.9.2
ipython                       7.33.0
ipython-genutils              0.2.0
ipyvolume                     0.5.2
ipyvue                        1.8.0
ipyvuetify                    1.8.4
ipywebrtc                     0.6.0
ipywidgets                    8.0.2
isort                         5.10.1
itemadapter                   0.7.0
itemloaders                   1.0.6
itsdangerous                  2.1.2
jaraco.classes                3.2.2
jax                           0.3.23
jaxlib                        0.3.7
jdcal                         1.4.1
jedi                          0.18.1
jellyfish                     0.9.0
Jinja2                        2.11.3
jinja2-time                   0.2.0
jmespath                      1.0.1
joblib                        1.2.0
json5                         0.9.5
jsonschema                    4.16.0
jupyter                       1.0.0
jupyter-client                7.3.4
jupyter-console               6.4.4
jupyter_core                  4.11.1
jupyter-server                1.18.1
jupyterlab                    3.5.0
jupyterlab-pygments           0.2.2
jupyterlab-server             2.10.3
jupyterlab-widgets            3.0.3
keyring                       23.9.3
kiwisolver                    1.4.4
lazy-object-proxy             1.8.0
libarchive-c                  4.0
llvmlite                      0.39.1
locket                        1.0.0
lxml                          4.9.1
lz4                           4.0.2
Markdown                      3.4.1
MarkupSafe                    1.1.1
matplotlib                    3.6.1
matplotlib-inline             0.1.6
mccabe                        0.6.1
menuinst                      1.4.19
mistune                       0.8.4
mkl-service                   2.4.0
modin                         0.16.1
more-itertools                9.0.0
Mosek                         10.0.25
mpmath                        1.2.1
msgpack                       1.0.4
multipledispatch              0.6.0
munkres                       1.1.4
mypy-extensions               0.4.3
navigator-updater             0.3.0
nbclassic                     0.4.5
nbclient                      0.5.13
nbconvert                     6.4.4
nbformat                      5.7.0
nest-asyncio                  1.5.6
networkx                      2.8.7
nltk                          3.6.7
nose                          1.3.7
notebook                      6.5.1
notebook_shim                 0.2.0
numba                         0.56.3
numexpr                       2.8.3
numpy                         1.21.6
numpydoc                      1.5.0
olefile                       0.46
openpyxl                      3.0.10
opt-einsum                    3.3.0
osqp                          0.6.2.post5
packaging                     21.3
pandas                        1.5.0
pandocfilters                 1.5.0
panel                         0.14.0
param                         1.12.2
paramiko                      2.11.0
parsel                        1.6.0
parso                         0.8.3
partd                         1.3.0
pathspec                      0.10.1
patsy                         0.5.3
pep8                          1.7.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.3
pkginfo                       1.8.3
pkgutil_resolve_name          1.3.10
platformdirs                  2.5.2
plotly                        5.10.0
pluggy                        1.0.0
ply                           3.11
prettytable                   3.4.1
progressbar2                  4.1.1
prometheus-client             0.15.0
prompt-toolkit                3.0.31
Protego                       0.2.1
psutil                        5.9.3
ptyprocess                    0.7.0
py                            1.11.0
pyarrow                       9.0.0
pyasn1                        0.4.8
pyasn1-modules                0.2.7
pybind11                      2.10.0
pycodestyle                   2.8.0
pycosat                       0.6.4
pycparser                     2.21
pyct                          0.4.6
pycurl                        7.45.1
pydantic                      1.10.2
PyDispatcher                  2.0.5
pydocstyle                    6.1.1
pyecharts                     1.9.1
pyerfa                        2.0.0.1
pyflakes                      2.4.0
Pygments                      2.13.0
PyJWT                         2.6.0
pylint                        2.15.5
pyls-spyder                   0.4.0
pymongo                       3.6.1
pymssql                       2.2.5
PyNaCl                        1.5.0
pyodbc                        4.0.34
pyOpenSSL                     22.1.0
pyparsing                     3.0.9
PyQt5                         5.12.3
PyQt5_sip                     4.19.18
PyQtChart                     5.12
PyQtWebEngine                 5.12.1
pyrsistent                    0.18.1
PySocks                       1.7.1
pytest                        7.2.0
python-dateutil               2.8.2
python-dotenv                 0.21.0
python-lsp-black              1.0.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.3.3
python-slugify                6.1.2
python-utils                  3.3.3
pythreejs                     2.4.1
pytoolconfig                  1.2.2
pytz                          2022.5
pyviz-comms                   2.2.1
PyWavelets                    1.3.0
pywin32                       303
pywin32-ctypes                0.2.0
pywinpty                      2.0.9
PyYAML                        6.0
pyzmq                         24.0.1
QDarkStyle                    3.0.2
qdldl                         0.1.5.post2
qstylizer                     0.2.2
QtAwesome                     1.2.1
qtconsole                     5.2.2
QtPy                          2.2.1
quadprog                      0.1.11
queuelib                      1.6.2
regex                         2022.9.13
requests                      2.28.1
requests-file                 1.5.1
rich                          12.6.0
rope                          1.4.0
Rtree                         1.0.1
ruamel-yaml-conda             0.15.80
s3transfer                    0.6.0
scikit-image                  0.19.3
scikit-learn                  1.0.2
scikit-learn-intelex          2021.20220920.101120
scipy                         1.9.3
Scrapy                        2.7.0
scs                           3.2.0
seaborn                       0.10.1
Send2Trash                    1.8.0
service-identity              18.1.0
setuptools                    65.5.0
simplejson                    3.17.6
sip                           6.7.2
six                           1.16.0
smart-open                    6.2.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcollections             2.1.0
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spyder                        5.2.2
spyder-kernels                2.2.1
SQLAlchemy                    1.4.42
starlette                     0.20.4
statsmodels                   0.13.2
sympy                         1.11.1
TA-Lib                        0.4.24
tables                        3.7.0
tabulate                      0.9.0
TBB                           0.2
tblib                         1.7.0
tenacity                      8.1.0
terminado                     0.17.0
testpath                      0.6.0
text-unidecode                1.3
textdistance                  4.5.0
threadpoolctl                 3.1.0
three-merge                   0.1.1
tifffile                      2022.10.10
tinycss2                      1.2.1
tldextract                    3.4.0
toml                          0.10.2
tomli                         2.0.1
tomlkit                       0.11.6
toolz                         0.12.0
tornado                       6.1
tqdm                          4.64.1
traitlets                     5.5.0
traittypes                    0.2.1
Twisted                       22.8.0
twisted-iocpsupport           1.0.2
typing_extensions             4.4.0
ujson                         5.5.0
unicodedata2                  14.0.0
Unidecode                     1.3.6
urllib3                       1.26.11
uvicorn                       0.19.0
vaex                          4.14.0
vaex-astro                    0.9.2
vaex-core                     4.14.0
vaex-hdf5                     0.13.0
vaex-jupyter                  0.8.0
vaex-ml                       0.18.0
vaex-server                   0.8.1
vaex-viz                      0.5.4
w3lib                         1.22.0
watchdog                      2.1.9
watchfiles                    0.18.0
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              1.4.1
websockets                    10.3
Werkzeug                      2.1.2
wheel                         0.37.1
widgetsnbextension            4.0.3
win-inet-pton                 1.1.0
win-unicode-console           0.5
wrapt                         1.14.1
xarray                        2022.10.0
xlrd                          2.0.1
XlsxWriter                    3.0.3
xlwings                       0.27.15
xyzservices                   2022.9.0
yapf                          0.32.0
zict                          2.2.0
zipp                          3.10.0
zope.interface                5.5.0

**Comment by nankaimy** [comment]
Spyder version, Python version, dependencies versions

**Comment by nankaimy** [comment]
if  the spyder 5.3.3  is  build in Anaconda3-2022.10-Windows-x86_64.exe is prefered

**Comment by dalthviz** [comment]
Seems like you Spyder 5.2.2 installation is using PyQt5 5.12.x, not totally sure but probably your Spyder 5.3.3 installation is using PyQt5 5.15.x ? Maybe that is what is causing the difference between your Spyder 5.2.2 installation and the one with Spyder 5.3.3

I think there is not much we can do from the Spyder side to help, but if you have more info let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
