### ISSUE TITLE
Debug toolbar is enabled for non-Python files (e.g.:  .trp)

### ISSUE THREAD

**Issue by dan123456-eng** [spyder-ide/spyder#19920]
## Problem Description

Python files:
![im](https://user-images.githubusercontent.com/61120620/197600548-10712cd1-f467-4269-a8be-cadc4e4428c7.png)
Other files:
![im2](https://user-images.githubusercontent.com/61120620/197600720-a2afd80e-81bb-4634-b0f5-c0c896a4741a.png)
### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.3.2
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows10

**Comment by dalthviz** [comment]
Hi @dan123456-eng thank you for the feedback! Spyder only supports debugging Python so that's way the button is greatout for non-python files.

I'm not totally sure if there is something we can do about that but just in case pinging @ccordoba12 and @impact27 (maybe they could give a better explanation fo this behavior)

**Comment by ccordoba12** [comment]
> Spyder only supports debugging Python so that's way the button is greatout for non-python files.

Yeah, that's basically the reason.

> I'm not totally sure if there is something we can do about that

Well, we could try to support the [Debug adapter protocol](https://microsoft.github.io/debug-adapter-protocol/) for other languages, but I don't think our own Python debugger would work well with it. In any case, this is not in our roadmap for the future.

@dan123456-eng, could you explain why you'd like to see this functionality in Spyder?

**Comment by dan123456-eng** [comment]
hi @dalthviz, @ccordoba12 and @impact27 thanks for feedbeck!

**Comment by dan123456-eng** [comment]
There was a doubt. If the Run current cell, Go to next and Run selection or current line buttons would not be abilitated after Run file?
![run](https://user-images.githubusercontent.com/61120620/199067688-941af21f-1a92-47a5-9e33-e05249070130.png)

**Comment by ccordoba12** [comment]
So, you mean that you're seeing the run buttons as enabled for files that are not Python? Unfortunately, that's not what I'm seeing on my end:

![imagen](https://user-images.githubusercontent.com/365293/199123255-74fb9421-b8bc-4282-a6d1-4a1c9519174a.png)

However, we're showing most debugger buttons as enabled, as can be seen in my screenshot. That's already fixed in `master` and it'll be part of Spyder 6.

**Comment by dan123456-eng** [comment]
Hello @ccordoba12 sorry! Buttons are not enabled for external languages here. I asked if it would be strange if the buttons only enabled but did not debug for external languages.

**Comment by dan123456-eng** [comment]
> However, we're showing most debugger buttons as enabled, as can be seen in my screenshot. That's already fixed in and it'll be part of Spyder 6.`master`

Wonderful, very good.

**Comment by dan123456-eng** [comment]
> So, you mean that you're seeing the run buttons as enabled for files that are not Python? Unfortunately, that's not what I'm seeing on my end:

Hello @ccordoba12 sorry! Buttons are not enabled for external languages here. I asked if it would be strange if the buttons only enabled but did not debug for external languages.

**Comment by ccordoba12** [comment]
> I asked if it would be strange if the buttons only enabled but did not debug for external languages.

You're right, that's strange and it's actually a user interface bug. However, since it's already fixed and the fix will be part of Spyder 6, I don't know if it's ok for you to close this issue.

**Comment by dan123456-eng** [comment]
hello @ccordoba12  can close the issue. thank you so much for the dedication.

**Comment by ccordoba12** [comment]
Closing then. Thanks a lot also for your interest and contributions to make Spyder better.
