### ISSUE TITLE
Switch to editor keyboard shortcut not working in 5.3.3

### ISSUE THREAD

**Issue by starstorms9** [spyder-ide/spyder#19928]
### Issue Report Checklist

* [ x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ n/a ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x ] Tried basic troubleshooting (if a bug/error)
    * [ x ] Restarted Spyder
    * [ x ] Reset preferences with ``spyder --reset``
    * [ x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The ctrl+shift+e keyboard shortcut for switching focus to the editor pane appears broken in 5.3.3. I've asked online and others have had the same issue as well and it appears to be specific to this version change:

https://stackoverflow.com/questions/73818754/switch-to-editor-pane-shortcut-not-working-in-spyder-5-x

### What steps reproduce the problem?

1. Open Spyder 5.3.3 with an editor and any other pane open (ipython console, graph pane, etc)
2. While another pane is selected (ie the ipython console with ctrl+shift+i )
3. Hit ctrl+shift+e to switch to the editor pane, nothing will happen

### What is the expected output? What do you see instead?
Expect to select the editor pane but instead nothing happens. No errors or other issues, simply no action seems to be taken. Can still switch to other panes using keyboard shortcuts but specifically can't get to the editor pane.

I have tried the following and none have had any impact: changing the key binding, restarting spyder, restarting system, resetting spyder to default, reinstalling spyder, and trying to use the shortcut from any other pane.

## Versions
This appears to be specific to 5.3.3 and works fine in previous versions. After reproducing the issue in 5.3.3 I downgraded to both 5.2.2 and 5.3.2 (via conda-forge) and in both of those versions the shortcut works as expected.

* Spyder version: 5.3.3
* Python version: 3.9.13
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Win 10 Build 19044.2130

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.2;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.0 (OK)
numpy >=1.7                   :  1.23.1 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)


```

**Comment by ccordoba12** [comment]
Hey @starstorms9, thanks for reporting. This was a regression in 5.3.3, but it'll be fixed in our next version (5.4.0), to be released at the end of the week or next week.
