### ISSUE TITLE
Problem updating spyder version 5.3.3

### ISSUE THREAD

**Issue by Juan231260** [spyder-ide/spyder#19933]
When I opened Spyder, it indicated that there was a new version available, 5..3.3, I followed the instructions, 
conda update anaconda
 and conda install spyder 5.3.3.
 it marked Found conflicts! Looking for incompatible packages. and began correction for 16 hours and still continues. 

Thanks in advance for your help.

(base) PS C:\Users\Juan> conda install spyder=5.3.3
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining backports:   0%|▊                                                                                                                                                                                 | 2/424 [00:00<00:58,  7.21it/s]\Examining munkres:   1%|█▋                                                                                                                                                                                  | 4/424 [00:00<00:58,  7.21it/s]|Examining intervaltree:   6%|██████████▎                                                                                                                                                                   | 25/424 [00:04<01:03,  6.24it/s]-Examining werkzeug:   8%|███████████████                                                                                                                                                                   | 36/424 [00:06<00:45,  8.53it/s]/Examining kiwisolver:   9%|███████████████▊                                                                                                                                                                | 38/424 [00:06<01:41,  3.81it/s]-Examining tblib:  15%|███████████████████████████▎                                                                                                                                                         | 64/424 [00:12<00:47,  7.56it/s]\Examining holoviews:  19%|█████████████████████████████████▊                                                                                                                                               | 81/424 [00:20<02:21,  2.43it/s]|Examining stack_data:  21%|████████████████████████████████████▌                                                                                                                                           | 88/424 [00:27<08:36,  1.54s/it]\Examining notebook:  23%|████████████████████████████████████████▎                                                                                                                                         | 96/424 [00:29<03:13,  1.70it/s]/Examining wincertstore:  24%|█████████████████████████████████████████▌                                                                                                                                   | 102/424 [00:34<02:46,  1.93it/s]/Examining itsdangerous:  26%|████████████████████████████████████████████▍                                                                                                                                | 109/424 [00:35<01:40,  3.15it/s]|Examining pywinpty:  28%|█████████████████████████████████████████████████▋                                                                                                                               | 119/424 [00:39<02:02,  2.48it/s]|Examining liblief:  29%|██████████████████████████████████████████████████▊                                                                                                                               | 121/424 [00:39<01:19,  3.83it/s]/Examining lz4:  39%|██████████████████████████████████████████████████████████████████████▊                                                                                                               | 165/424 [00:51<01:05,  3.94it/s]/Examining plotly:  40%|██████████████████████████████████████████████████████████████████████▉                                                                                                            | 168/424 [00:51<00:54,  4.70it/s]-Examining icc_rt:  44%|██████████████████████████████████████████████████████████████████████████████                                                                                                     | 185/424 [00:58<01:15,  3.18it/s]\Examining dask:  45%|█████████████████████████████████████████████████████████████████████████████████▌                                                                                                   | 191/424 [01:10<00:41,  5.58it/s]-Examining win_unicode_console:  45%|██████████████████████████████████████████████████████████████████████████▊                                                                                           | 191/424 [01:12<00:41,  5.58it/s]\Examining tabulate:  47%|███████████████████████████████████████████████████████████████████████████████████                                                                                              | 199/424 [01:12<02:49,  1.33it/s]|Examining ipykernel:  48%|███████████████████████████████████████████████████████████████████████████████████▊                                                                                            | 202/424 [01:12<02:47,  1.33it/s]/Examining boto3:  51%|████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                       | 218/424 [01:26<01:49,  1.88it/s]/Examining hvplot:  52%|████████████████████████████████████████████████████████████████████████████████████████████▍                                                                                      | 219/424 [01:28<03:48,  1.11s/it]/Examining snowballstemmer:  53%|██████████████████████████████████████████████████████████████████████████████████████████▏                                                                               | 225/424 [01:29<02:01,  1.63it/s]/Examining cfitsio:  54%|████████████████████████████████████████████████████████████████████████████████████████████████▌                                                                                 | 230/424 [01:29<00:52,  3.67it/s]\Examining mock:  57%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                                             | 242/424 [01:30<00:25,  7.11it/s]/Examining jupyter:  58%|████████████████████████████████████████████████████████████████████████████████████████████████████████                                                                          | 248/424 [01:30<00:16, 10.56it/s]|Examining statsmodels:  61%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 260/424 [01:36<01:07,  2.42it/s]/Examining inflection:  64%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                               | 271/424 [01:40<01:10,  2.18it/s]/Examining typing-extensions:  65%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                                           | 274/424 [01:42<00:57,  2.59it/s]\Examining dask-core:  66%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                            | 278/424 [01:42<00:53,  2.74it/s]|Examining pyviz_comms:  66%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                                           | 279/424 [01:42<00:34,  4.24it/s]|Examining python-snappy:  67%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                         | 283/424 [01:45<00:30,  4.63it/s]|Examining regex:  68%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                          | 287/424 [01:45<01:01,  2.24it/s]\Examining pyjwt:  68%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                         | 288/424 [01:45<01:00,  2.24it/s]|Examining tqdm:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                               | 312/424 [01:54<01:11,  1.56it/s]|Examining sphinxcontrib-devhelp:  74%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                          | 315/424 [01:55<00:44,  2.44it/s]|Examining pyyaml:  75%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                            | 320/424 [01:59<01:05,  1.58it/s]\Examining m2w64-libwinpthread-git:  76%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                                       | 322/424 [02:00<00:54,  1.88it/s]|Examining scikit-image:  78%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                      | 329/424 [02:02<00:36,  2.61it/s]/Examining future:  79%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                     | 335/424 [02:09<01:25,  1.04it/s]/Examining tornado:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                  | 342/424 [02:10<00:24,  3.31it/s]|Examining parsel:  82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                | 347/424 [02:11<00:30,  2.55it/s]-Examining qt:  85%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                            | 359/424 [02:24<01:10,  1.08s/it]|Examining diff-match-patch:  86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                        | 364/424 [02:25<00:32,  1.83it/s]|Examining olefile:  87%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                       | 368/424 [02:26<00:22,  2.49it/s]\Examining pip:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                  | 381/424 [02:31<00:21,  1.98it/s]/Examining unidecode:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 383/424 [02:33<00:23,  1.75it/s]\Examining wcwidth:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 394/424 [02:54<01:09,  2.31s/it]/Examining toml:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 417/424 [03:00<00:02,  3.40it/s]\Examining pyparsing:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 421/424 [03:00<00:00,  5.28it/s]/Examining conflict for jinja2 backports idna lazy-object-proxy munkres backports.tempfile pyct cython sphinxcontrib-applehelp google-resumable-media cycler intake qstylizer decorator sphinxcontrib-jsmath gensim arrow python-slugify xlwi|

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @Juan231260 thank you for the feedback! Are you using Spyder from your base environment? I think to install Spyder 5.3.3 in your base conda environment you will need to first remove your current Spyder version (`conda remove spyder`) and then reinstall Spyder (`conda install spyder=5.3.3`). _**Take into account that removing Spyder from your base env probably will remove also other packages so be careful if you want to try this option**_

If you want to install Spyder 5.3.3 but you don't want to change your base environment you could create a new conda environment and install there specifically Spyder 5.3.3.

You can also disable the check for updates functionality for the moment by going to `Preferences > Application > Advanced settings > Check for updates on startup`

Let us know if the info above helps!

**Comment by Juan231260** [comment]
Still examining conflicts, 34% done and 39 hours remaining, should i abort or wait?Fear break something interrupting process.

**Comment by dalthviz** [comment]
You can just stop the process, I believe that will not break anything since no actuall installation/uninstallation of packages is happening (conda is just trying to run its solver figuring out what are the incompatibilities between your env and the request package)

**Comment by nankaimy** [comment]
i meet the same problem too

**Comment by Juan231260** [comment]
Finally installed in a new environment, each time i need reinstall package missing in that new env.

**Comment by BokusEddy** [comment]
I encountered the same problem updating to Spyder5.3.3. As previously mentioned here, I removed Spyder (conda remove Spyder), then installed again (conda install Spyder=5.3.3). This worked for me.

**Comment by dalthviz** [comment]
Just in case, Spyder 5.4.2 is now available from the anaconda channel: https://anaconda.org/anaconda/spyder/files?version=5.4.2

**Comment by nankaimy** [comment]
> Just in case, Spyder 5.4.2 is now available from the anaconda channel: https://anaconda.org/anaconda/spyder/files?version=5.4.2


can find it support python3.7

**Comment by dalthviz** [comment]
Hi @nankaimy checking, yes, I think the latest releases 5.4.1 and 5.4.2 that are now available from the anaconda channel are only for Python 3.8+. The latest release available for Python 3.7 is still 5.3.3, sorry for the confusion there 😅

**Comment by dalthviz** [comment]
Closing this as completed but just in case, currently Spyder 5.4.3 is available from the default anaconda channel. Also, for more info about the different ways Spyder can be installed you can check the Spyder docs page: https://docs.spyder-ide.org/current/installation.html
