### ISSUE TITLE
Pressing TAB key generates error on Spyder Editor Pane

### ISSUE THREAD

**Issue by mfatih7** [spyder-ide/spyder#19946]
Hello

In order to increase the indent, I am selecting some part of code and pressing the TAB key.
Spyder freezes as shown in the video below.

best regards

[screen-capture.webm](https://user-images.githubusercontent.com/58260582/198829169-e9e6d46a-ce7e-446e-b412-31706857e254.webm)

**Comment by mfatih7** [comment]
When Ctrl+1 is used to same problem occurs

**Comment by ccordoba12** [comment]
Hey @mfatih7, thanks for reportind and sorry for the late reply. Could you update your video in another format (e.g. mp4)? I can't view it on Firefox.

Besides, in case you didn't do it before, please go at the end of your video to the menu `Help > About Spyder` to check how you installed it and what versions you're using.

**Comment by mfatih7** [comment]
Hello @ccordoba12

![image](https://user-images.githubusercontent.com/58260582/200584107-5f7c258f-9d82-4c89-a357-788ec30dc18e.png)


https://user-images.githubusercontent.com/58260582/200584184-fc62712e-3aa0-4d70-a192-ee66562f8a22.mp4

**Comment by ccordoba12** [comment]
So does Spyder simply freeze after you press the Tab key?

**Comment by mfatih7** [comment]
I don't strictly prefer one to the other.

**Comment by ccordoba12** [comment]
Ok, but did you enable this option in our Preferences?

![imagen](https://user-images.githubusercontent.com/365293/201485227-23391497-2b23-47c6-85d6-b27809fcee75.png)

That could be the cause of your problem.

**Comment by mfatih7** [comment]
I have not changed it. 
"4 spaces" is selected.

**Comment by ccordoba12** [comment]
Ok, another issue could be that your code is using tabs instead of spaces. Is that the case?

**Comment by mfatih7** [comment]
When I press TAB once and move the cursor to the left with arrow keys I can see 4 spaces inserted.

**Comment by ccordoba12** [comment]
Right, but what I'm asking you is if the file you're trying to edit in Spyder is indented with tabs instead of spaces.

**Comment by mfatih7** [comment]
When I inspect the lines causing the error I observe that some lines have TABs(not 4 spaces)
Besides Spyder Editor, I used a text comparison program to merge code.
This must not generate error.

**Comment by ccordoba12** [comment]
> When I inspect the lines causing the error I observe that some lines have TABs

Ok, that's good to know.

> This must not generate error.

Agreed, but Spyder can't work very well with Tabs. So my suggestion is for you to go the menu `Source > Fix indentation`, which should convert all tabs in your file to spaces.

Let us know if it works for you.

**Comment by mfatih7** [comment]
I tried choosing tabulations.
It didn't help sadly

**Comment by ccordoba12** [comment]
Yeah, that won't help either. You need to switch from tabs to spaces, as I mentioned above, for Spyder to work properly.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
