### ISSUE TITLE
Cannot read from console?

### ISSUE THREAD

**Issue by SvenGeier** [spyder-ide/spyder#19941]
### What steps will reproduce the problem?

Open spyder and in the interactive console type 

In[1]: n=input("Enter exponent:")

(or  find a line like this in a currenty-open file and press f9 on it or enter it as a single line in a new file and f5 it - same result)

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\sgeier\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\sgeier\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\debugging.py", line 278, in _handle_input_request
    return super(DebuggingWidget, self)._handle_input_request(msg)
  File "C:\Users\sgeier\Anaconda3\lib\site-packages\qtconsole\frontend_widget.py", line 516, in _handle_input_request
    self._readline(msg['content']['prompt'], callback=callback, password=msg['content']['password'])
  File "C:\Users\sgeier\Anaconda3\lib\site-packages\qtconsole\console_widget.py", line 2413, in _readline
    self._show_prompt(prompt, newline=False, separator=False)
TypeError: _show_prompt() got an unexpected keyword argument 'separator'
```

## Versions

* Spyder version: 5.1.5 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.4.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.3.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by SvenGeier** [comment]
Ooof. Downgrading ipython to upgrade spyder? Seriously? - I expect this kind of nonsense in Linux. In Windows I've gotten used to *someone* making sure the distributed components actually work together. [rolling eye emoji]

======================================================
(base) C:\Users\sgeier>conda update anaconda
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

Retrieving notices: ...working... done

(base) C:\Users\sgeier>conda install spyder=5.2.2
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\sgeier\Anaconda3

  added / updated specs:
    - spyder=5.2.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-build-3.22.0         |   py39haa95532_0         541 KB
    flake8-4.0.1               |     pyhd3eb1b0_1         118 KB
    ipython-7.31.1             |   py39haa95532_1        1024 KB
    jellyfish-0.9.0            |   py39h2bbff1b_0          46 KB
    jupyter_client-7.3.4       |   py39haa95532_0         216 KB
    m2-msys2-runtime-2.5.0.17080.65c939c|                3         3.0 MB
    m2-patch-2.7.5             |                2          89 KB
    pycodestyle-2.8.0          |     pyhd3eb1b0_0          41 KB
    pyflakes-2.4.0             |     pyhd3eb1b0_0          60 KB
    python-lsp-server-1.3.3    |     pyhd3eb1b0_0          43 KB
    qtconsole-5.2.2            |     pyhd3eb1b0_0          92 KB
    spyder-5.2.2               |   py39haa95532_1         9.4 MB
    spyder-kernels-2.2.1       |   py39haa95532_0         115 KB
    ------------------------------------------------------------
                                           Total:        14.7 MB

The following NEW packages will be INSTALLED:

  jellyfish          pkgs/main/win-64::jellyfish-0.9.0-py39h2bbff1b_0 None
  m2-msys2-runtime   pkgs/msys2/win-64::m2-msys2-runtime-2.5.0.17080.65c939c-3 None
  m2-patch           pkgs/msys2/win-64::m2-patch-2.7.5-2 None

The following packages will be UPDATED:

  conda-build                         3.21.8-py39haa95532_2 --> 3.22.0-py39haa95532_0 None
  flake8                                 3.9.2-pyhd3eb1b0_0 --> 4.0.1-pyhd3eb1b0_1 None
  jupyter_client     pkgs/main/noarch::jupyter_client-6.1.~ --> pkgs/main/win-64::jupyter_client-7.3.4-py39haa95532_0 None
  pycodestyle                            2.7.0-pyhd3eb1b0_0 --> 2.8.0-pyhd3eb1b0_0 None
  pyflakes                               2.3.1-pyhd3eb1b0_0 --> 2.4.0-pyhd3eb1b0_0 None
  python-lsp-server                      1.2.4-pyhd3eb1b0_0 --> 1.3.3-pyhd3eb1b0_0 None
  spyder                               5.1.5-py39haa95532_1 --> 5.2.2-py39haa95532_1 None
  spyder-kernels                       2.1.3-py39haa95532_0 --> 2.2.1-py39haa95532_0 None

The following packages will be SUPERSEDED by a higher-priority channel:

  qtconsole          pkgs/main/win-64::qtconsole-5.3.2-py3~ --> pkgs/main/noarch::qtconsole-5.2.2-pyhd3eb1b0_0 None

The following packages will be DOWNGRADED:

  ipython                              8.4.0-py39haa95532_0 --> 7.31.1-py39haa95532_1 None

**Comment by ccordoba12** [comment]
We still don't have official support for IPython 8, hence the downgrade. We'll try to add it in our next version, to be released at the end of the year.
