### ISSUE TITLE
Editor jumps to the end of file when saving with autoformat-on-save switched on

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#19958]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

This is superficially similar to the previous issue on the editing window jumping (#19939) but is probably simpler.  When I save a file with autoformat-on-save switched on (I'm using the black formatter), the cursor and editing window often jump to the end of the file if the file was reformatted.  I'm guessing that this is some sort of default behaviour when reloading a file?

I could try to reproduce this and make a screencast so you can see the behaviour if that would help!

### What is the expected output? What do you see instead?

It would be great if the cursor stayed in roughly the same place in the file (say the same line number), even if it's impossible to keep it in the same logical position in the file.

## Versions

* Spyder version: 5.3.3  (pip)
* Python version: 3.10.8 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Linux 6.0.0-2-amd64

**Comment by juliangilbey** [comment]
Ah, I realise that it's actually tied in with #19939 - sorry.  On save, the cursor jumps to the end of the file but the window stays in the same position; it's when hitting any key that the screen then jumps.  It would be good if the cursor didn't jump.

**Comment by ccordoba12** [comment]
Hey @juliangilbey, thanks for reporting! I'm surprised no one has noticed this bug before (I did some months ago but haven't had time to fix it). I agree it's similar to #19939 but this is specifically related to auto-formatting.

> It would be good if the cursor didn't jump.

Agreed, this is the ideal solution. We'll see if we can implement it for our next version, i.e. the one after 5.4.0, which is almost ready.

**Comment by juliangilbey** [comment]
I guess the "ideal" thing to do would be to save (in memory) the location of the cursor with respect to the AST before saving, then reposition the cursor at the same place in the AST after saving. But that may be too difficult.
