### ISSUE TITLE
Cannot upgrade to 5.3.3 from Anaconda Navigator, or by using Conda (Anaconda base environment)

### ISSUE THREAD

**Issue by scrappydog1958** [spyder-ide/spyder#19965]
### What steps will reproduce the problem?

If I try to upgrade to 5.3.3 using Anaconda Navigator it fails. If I try to use the terminal and the conda commands, it also fails. Only way I can get 5.3.3 is as stand alone

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.13
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @scrappydog1958 , if you want to install Spyder 5.3.3 through conda, you will need to create a new environment. To do that, you can run something like the following from an Anaconda prompt:

```
conda create -n spyder-533 python=3.10 spyder=5.3.3
```

Then you will need to either activate the env and launch from it Spyder by running on an Anaconda prompt something like:

```
conda activate spyder-533
spyder
```
or check in your start menu for the shortcut that should have been created with the name `Spyder (spyder-533)` 

Let us know if the info above helps!

**Comment by yanyu2015** [comment]
thx so much! I waste one day to update the 5.3.3, but all ways have failed. The way you provide works.
A new problem is that when I install pkg either on an Anaconda prompt or in spyder, after pkg installed, the spyder crashed( be busy and cannot click).
on an Anaconda prompt
```
conda install pandas
```
in spyder 
```
!pip install pyarrow
```
Notice that when I‘m installing pkg, the spyder 5.3.3 is open.
After close spyder and restart it, it works well.
Pkg installation is a frequent action, so it may not be so convenient.

**Comment by scrappydog1958** [comment]
Fantastic!!!!! worked like a charm. A thousand thanks sir. So happy I joined Github

Thank you,

Thomas

**Comment by dalthviz** [comment]
Glad it worked for you @scrappydog1958 !

In your case @yanyu2015 if you are constantly installing packages I would suggest you to always do it with the anaconda prompt and using the conda-forge channel (adding to your installation command the `-c conda-forge` flag). After installing new packages, if Spyder is running, you will need to restart the IPython console kernel inside Spyder or start a new IPython console inside Spyder to be able to use them

**Comment by yanyu2015** [comment]
@dalthviz It works well now. The above phenomenon may be due to the large dataset I used at the time.

**Comment by dalthviz** [comment]
Awesome @yanyu2015 ! I will close this as completed then :+1:

**Comment by scrappydog1958** [comment]
Now that spyder 5.4 is out how do you change your commands tomorrow to upgrade?

Thanks,

Thomas
