### ISSUE TITLE
Current Spyder demo via MyBinder doesn't have Web browser working in easy to launch way

### ISSUE THREAD

**Issue by fomightez** [spyder-ide/spyder#19966]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Current Spyder demo via MyBinder doesn't have qutebrowser working. I see [here](https://github.com/spyder-ide/binder-environments/commit/4bb089d9d8d8907215d1d20f98c9cc3cd2c30826) that qutebrowser was removed and a simple web browser in PyQt was added. Is opening from inside Spyder meant to be the way to trigger opening this simple browser?    
[This addition to `binder/Desktop/Web browser.desktop`](https://github.com/spyder-ide/binder-environments/commit/4bb089d9d8d8907215d1d20f98c9cc3cd2c30826#diff-53fa3bd0f2546908f8389551686abffec9e2b5447bd86d3ffb9d7406c2466a5a) makes me think it should be registered somehow or a desktop icon added?:

```text
[Desktop Entry]
Version=1.0
Type=Application
Name=Web Browser
Exec=/bin/bash -c "exec ${HOME}/binder/web_browser/start.py"
# FIXME: Don't hardcode Path?
Icon=/home/jovyan/binder/web_browser/browser.png
Path=/home/jovyan/Desktop
````

By 'Current Spyder demo via MyBinder', I mean the one linked to with the `launch binder` badge on the main Spyder GitHub repo page presently. [Here](https://github.com/spyder-ide/spyder).

Right now the URL there is:
https://mybinder.org/v2/gh/spyder-ide/binder-environments/spyder-stable?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252FSpyder-Workshop%26urlpath%3Ddesktop%252F%26branch%3Dmaster

What is that addition meant to update? 

Trying `Web browser` under `Applications` doesn't open it. (Also right clicking on the desktop and selecting 'Web Browser' under 'Applications' doesn't work.

### What steps reproduce the problem?

1. Launch the Binder demo and try to open `Web browser` under applications
2. Pointing Spyder at `binder/web_browser/start.py` and running that **triggers the web browser to open**. (So the added browser does indeed work.) Is that the only intended route to launch the browser now?
3. Running `exec ~/binder/web_browser/start.py` in a terminal also starts the web broswer.

### What is the expected output? What do you see instead?

Browser should open from `Web browser` under `Applications` but doesn't.

## Versions

Commit [818622ca863bf1618269910eaef47fe061e2c925](https://github.com/spyder-ide/binder-environments/commit/818622ca863bf1618269910eaef47fe061e2c925) of [binder-environments](https://github.com/spyder-ide/binder-environments)

**Comment by dalthviz** [comment]
Hi @fomightez thank you from the feedback! What link are you using to launch the binder instance? I tried the [master branch binder-environments link](https://mybinder.org/v2/gh/spyder-ide/binder-environments/master?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252Fspyder%26urlpath%3Ddesktop%252F%26branch%3Dmaster%26depth%3D500) and seems like the image needed an update. After waiting a some time, the launched vm instance has the web browser icon and I'm able to launch a browser clicking on it:

![binder](https://user-images.githubusercontent.com/16781833/199628215-e9b22a0a-3464-4827-a62c-f3011b5dca53.gif)

Any other info to check if there are issues still with the binder setups will be greatly appreciated, let us know!

**Comment by fomightez** [comment]
I'm using the one on the main Spyder GitHub repo page presently. [Here](https://github.com/spyder-ide/spyder).

Right now the URL is:
https://mybinder.org/v2/gh/spyder-ide/binder-environments/spyder-stable?urlpath=git-pull%3Frepo%3Dhttps%253A%252F%252Fgithub.com%252Fspyder-ide%252FSpyder-Workshop%26urlpath%3Ddesktop%252F%26branch%3Dmaster

**Comment by dalthviz** [comment]
Thanks for the new info! So I guess you expected to have with the binder link in the README an instance with the Web browser icon instead of the shortcut to launch a specific Spyder workshop page in the browser, right?

Maybe we should provide in the Spyder README instead of just one binder link a set of binder links? Something like master, 5.x, and spyder-stable + workshop or at least spyder-stable (but with just the browser icon) and spyder-stable + workshop? What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
> Maybe we should provide in the Spyder README instead of just one binder link a set of binder links? Something like master, 5.x

Yeah, I think that's a very good idea. Could you take care of this?

> and spyder-stable + workshop or at least spyder-stable (but with just the browser icon) and spyder-stable + workshop?

I think we can simply add a "Web browser" to `spyder-stable` image. I'll take care of that.

**Comment by ccordoba12** [comment]
> I think we can simply add a "Web browser" to spyder-stable image. I'll take care of that.

I just took care of it.

**Comment by fomightez** [comment]
Yes, sorry. I just expected to have some way to use the web browser in what launched from the main Spyder GitHub repo page. When qutebrowser was taken away, it broke it in the one that was being linked on the main page.
