### ISSUE TITLE
Unable to change the interface colors despite saving them in the preferences.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#1996]
_From [amlor...@asu.edu](https://code.google.com/u/101556776150124661841/) on 2014-10-05T00:57:45Z_

Spyder Version:  2.3.0rc
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.6 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1996_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:21:54Z_

What do you mean by

"Also plot output into an external window with matplotlib seems to have disappeared as a function :("

If you're using IPython, the default is to print to the console but you can change that in

Tools > Preferences > IPython console > Graphics > Backend

**Summary:** Unable to change the interface colors despite saving them in the preferences.  \<span class="oldvalue"> (was: Two issues: I seem to be unable to change the interface colors despite saving them in the preferences. Also plot output into an external window with matplot lib seems to have disappeared as a function :() \</span>  
  **Status:** Accepted  
  **Labels:** Cat-Settings MS-v2.4

**Comment by ccordoba12** [comment]
@goanpeca, this one is for you after PR #2861 is merged.

**Comment by ccordoba12** [comment]
This is already fixed.
