### ISSUE TITLE
conda not recognised as an internal command

### ISSUE THREAD

**Issue by Vinodhini12** [spyder-ide/spyder#19974]
Actual Behavior
conda reset spyder
'conda' is not recognized as an internal or external command,
operable program or batch file.

Python version (python --3.9)
OS (Windows)

**Comment by ccordoba12** [comment]
Hey @Vinodhini12, thanks for reporting and sorry for the late reply. Are you trying to run the `conda` command in Spyder's IPython console?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
