### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ghaffariali** [spyder-ide/spyder#19985]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I have installed Spyder from ArcGis Python Package but still I cannot get it to open.

**Comment by ccordoba12** [comment]
Hey @ghaffariali, thanks for reporting. Please communicate to the ArcGIS community about it because we don't even know what Spyder version they distribute.
