### ISSUE TITLE
inserting line break in code line does not align well on next line

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2001]
_From [12w13d2...@gmail.com](https://code.google.com/u/114540585018913879598/) on 2014-10-09T08:54:59Z_

Spyder Version:  2.3.1
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
IPython >=0.13  :  1.2.1 (OK)
matplotlib >=1.0:  1.4.0 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
pep8 >=0.6      :  None (NOK)
psutil >=0.3    :  None (NOK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  1.6 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  None (NOK) 

What steps will reproduce the problem?

 1.move cursor into any valid python line e.g.(^ marks the cursor) "foo(bar1,^bar2,bar3)"
2.hit enter key 

What is the expected output? What do you see instead?

 expected (first bars are vertical aligned):
"foo(bar1,
     bar2,bar3)"

current result (unaligned arguments. maybe 17 spaces off)
"foo(bar1,
                     bar2,bar3)" 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2001_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T15:13:29Z_

Thanks for reporting

**Labels:** MS-v2.3.3 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:18:08Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
@blink1073, could you take a look at this one? I think you worked on something like this for the last of your PRs merged on bitbucket.

**Comment by blink1073** [comment]
On it.

**Comment by blink1073** [comment]
Actually I think I already fixed this one, I did a few experiments in the editor and it has the desired behavior.

**Comment by blink1073** [comment]
Case in point:

```python
        def foo(bar1,bar2,bar3)

        def foo(bar1,
                bar2,bar3)
```

**Comment by goanpeca** [comment]
Can we close this then?

**Comment by ccordoba12** [comment]
@goanpeca, have you tested it yourself? I haven't closed this one because I haven't had time to verify that everything is working as expected.

**Comment by goanpeca** [comment]
Well the example in the description works fine for me as @blink1073 pointed out (in master)

**Comment by Nodd** [comment]
It work for me on these simple examples but sometimes I still get wrong indentation. I wasn't able to recreate an example though, i'll try to do it next time it happens (it's quite rare).

**Comment by goanpeca** [comment]
Yes, for me as well sometimes it fails, but when that happens I will open a new issue, for THIS issue which uses the simple example it seems to work, so closing?

**Comment by Nodd** [comment]
Alright, closing.
