### ISSUE TITLE
Interactive plot windows freeze

### ISSUE THREAD

**Issue by ReneLoh** [spyder-ide/spyder#20034]
Hi,

when a matplotlib plot window opens (using the Gt5 backend), the plot window freezes after my first interaction with it. For example, I click on "save", the save-file-manager opens, but then it instantly closes again and the plot window is frozen.

It does not happen when I run the script in a normal terminal. There, the interactive plot window works just fine, so I figured it must be Spyder related.

Spyder 5.2.2
Python 3.7.15 64-bit 
IPython 7.31.1
Qt 5.15.2 
PyQt5 5.15.7 
Linux 5.4.0-131-generic
Matplotlib 3.5.3

System: Ubuntu 18.04.5

### What steps reproduce the problem?

Open Spyder, run

```
import matplotlib.pyplot as plt

fig, axs = plt.subplots()
```

### Paste Traceback/Error Below (if applicable)
No error message.

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.5.3 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @ReneLoh thank you for the feedback! Could this be related to https://github.com/spyder-ide/spyder/issues/19551?

Could you see if installing the latest version of Spyder helps? (Spyder 5.4.0)

Let us know if something of the above helps!

**Comment by ReneLoh** [comment]
> Hi @ReneLoh thank you for the feedback! Could this be related to #19551?
> 
> Could you see if installing the latest version of Spyder helps? (Spyder 5.4.0)
> 
> Let us know if something of the above helps!

Hi @dalthviz, sorry for the late response, did not expect to get an answer that soon.
how can I install this Spyder version?
I am using anaconda and tried "conda update spyder", but it would only give me version 5.2.2.
I also tried "conda install spyder=5.4.0", but it cannot find the package. It says:
"PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=5.4.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
"

**Comment by dalthviz** [comment]
Thank you for the new info @ReneLoh ! I would suggest for testing proposes to create a new conda environment with packages from the conda-forge channel (so you can try the latest Spyder version). For that you can do something like the following from a terminal (the env will need to be created with at least Python 3.8):

``` 
conda create -n spyder-cf -c conda-forge python=3.8 spyder=5.4.0 matplotlib
conda activate spyder-cf
spyder
```

Let us know if the issue persists using the latest Spyder release

**Comment by dalthviz** [comment]
Awesome! Glad to hear that using the latest release helped with this @ReneLoh ! And yes, I would suggest you then to work in that environment (being sure to use the conda-forge channel to install any other packages needed) :+1:
