### ISSUE TITLE
Compability with python 3.11 from conda-forge

### ISSUE THREAD

**Issue by arturdaraujo** [spyder-ide/spyder#20032]
## Problem Description
The spyder team is probably aware but there is a compatibility problem with python 3.11 from conda-forge. I'm using miniforge. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) conda create -n py311_standard python=3.11 spyder=5.4 

Collect all metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package spyder-5.4.0-py310h5588dad_0 requires python_abi 3.10.* *_cp310, but none of the providers can be installed

```

**Comment by ccordoba12** [comment]
Hey @arturdaraujo, thanks for reporting. This really doesn't depend on us, but on the Conda-forge migration of packages to support Python 3.11.

You need to be patient because that process takes two or three months, perhaps even more.
