### ISSUE TITLE
numpy is not eing imported 

### ISSUE THREAD

**Issue by ishansemalty07** [spyder-ide/spyder#20045]
when entered command import numpy the command is not working

**Comment by ccordoba12** [comment]
Hey @ishansemalty07, thanks for reporting. I have some questions for you:

1. How did you install Spyder?
2. How did you install Numpy?
3. Are you using Windows, Linux or macOS?

Also, please take a look at the following entries in our docs to see if you can solve your problem after reading them:

https://docs.spyder-ide.org/current/faq.html#using-packages-installer
http://docs.spyder-ide.org/current/faq.html#using-existing-environment

Let us know if they work for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
