### ISSUE TITLE
解决虚拟环境使用时包错误关闭打不开spyder

### ISSUE THREAD

**Issue by zmh12345678** [spyder-ide/spyder#20046]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
在终端打开该虚拟环境
查看报错的包
把报错的包卸载并且重新下载
注意包的版本
然后重启spyde即可

**Comment by ccordoba12** [comment]
请看一下我们的视频

https://www.youtube.com/watch?v=Ul79ihg41Rs

安装指南。

http://docs.spyder-ide.org/current/installation.html

和其他文件

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
https://docs.spyder-ide.org/current/faq.html#using-packages-installer

来了解你如何解决你的问题。

如果不知道你的Spyder和Python版本，以及你使用的操作系统，我们就不可能给你提供额外的帮助。谢谢你的理解。

注意：此信息已自动从英文翻译成中文
