### ISSUE TITLE
Spyder opens then immediately closes

### ISSUE THREAD

**Issue by Nathan-Thomas-Han** [spyder-ide/spyder#20048]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder fails to load properly. It opens briefly for a couple of seconds but closes immediately. This is true whether I open Spyder independently or whether from Anaconda. There is an error message when I open it from Anaconda prompt. I tried the solutions (such as trying to open Spyder in a new environment) in this previous issue #https://github.com/spyder-ide/spyder/issues/16982 because I get a similar error message.

### What steps reproduce the problem?
Opening Spyder

### What is the expected output? What do you see instead?
Expect to see Spyder opening.

### Paste Traceback/Error Below (if applicable)

link image0 hasn't been detected!
C:\Users\natha\anaconda3\lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)

## Versions

* Spyder version: 5.2.2
* Python version: 3.9.13
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @Nathan-Thomas-Han, thanks for reporting. Please uninstall Anaconda and reinstall it again following the instructions i [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs). I think that should solve your problem.

**Comment by Nathan-Thomas-Han** [comment]
Hey Carlos, thanks for responding so quickly. I followed the instructions in the video but I still encountered the same problem and I got this error message instead:

```
(spyder-env) C:\Users\natha>spyder
fromIccProfile: failed minimal tag size sanity
Bad address (D:\bld\zeromq_1629967000004\work\src\epoll.cpp:100)
Traceback (most recent call last):
  File "C:\Users\natha\.conda\envs\spyder-env\lib\asyncio\windows_events.py", line 439, in select
    self._poll(timeout)
RuntimeError: <_overlapped.Overlapped object at 0x000001C5F1260420> still has pending operation at deallocation, the process may crash
Bad address (D:\bld\zeromq_1629967000004\work\src\epoll.cpp:100)
Bad address (D:\bld\zeromq_1629967000004\work\src\epoll.cpp:100)
```

**Comment by ccordoba12** [comment]
Ok, this could be an issue with your antivirus or firewall. Please disable them temporarily and try again.

**Comment by Nathan-Thomas-Han** [comment]
Hey Carlos, thanks for your timely responses. After looking around for a bit, it seems that the issue seemed to be coming from my use of a VPN. Spyder runs fine after I've resetted the winsock.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by Date-format-busted** [comment]
@Nathan-Thomas-Han https://hygraph-irritated.github.io/rajesh/
