### ISSUE TITLE
frozen console.

### ISSUE THREAD

**Issue by jeanj14** [spyder-ide/spyder#20054]
### What steps will reproduce the problem?

When I closed the window, the console started to freeze. I could not interact with it anymore. I am struggling to do anything with it. It won't show me any output.

**Comment by ccordoba12** [comment]
Hey @jeanj14, thanks for reporting. I guess you created a Matplotlib plot and the console froze when you close it. Is that correct?

**Comment by jeanj14** [comment]
Not matplotlib but tkinter. I was making a program that stored dictionaries
and the console froze completely. Luckily i fixed the problem, all I had to
do was reinstall Anaconda. Thanks for the response really appreciate it.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it! Closing then.
