### ISSUE TITLE
Blues installin on Linux Mint, never got it working

### ISSUE THREAD

**Issue by russ-hensel** [spyder-ide/spyder#20052]
When I open Spyder in either windows or linux ( mint ) it tells me about
spyder 5.4: this has been true for many weeks. 

*On windows anaconda says it can upgrad to the same version I am running
( ).  But it cannot because I am already running it.  No hint of 5.4

* So finally on a mint machine running 5.2.1 ( no anaconda, previusly i used
sudo to install anaconda and that was the end of that install of mint) 
I followed the link: https://github.com/spyder-ide/spyder/releases/latest/download/Spyder_64bit_full.exe
and got a windows version!

So I got wise and went to  Spyder 5.4.0 Latest: at https://github.com/spyder-ide/spyder/releases/
and downloaded: Linux (CentOS 7+): Linux-x86_64.sh (Experimental) -- and experiment that
did not go well.

Then I ran the shell script ( linux mint )

I accepted the default location, something around:
     root@bulldog:~/.local/Spyder-5.4.1.dev0/bin# 

*Bad idea, making things root and hidden just makes it hard to work on or even
see.

*No menu option to run came up on my system.

* Readme says: "Linux and macOS: find it under `bin`, next to this file.     
* Windows: navigate to `Scripts`, next to this file."   >>>>>  if it were only there

* In unmodified installations, this _should_ be enough to launch `spyder`, but sometimes you will
need to activate the `conda` environment to ensure all dependencies are importable.   
>>>>> and how do you do that activate conda

* eventually I ran conda install spyder and got a spyder under "bin" it runs a bit then
blows out to the terminal.

* checked the install dir, about 4 gigs.  as a superuser I deleted it all.  Still have
my older somewhat defective 5.2.1 on the linux machine.  

I do have another linux machine with mint, it installed anaconda, it suggests 5.4, but cannot
install it.  Perhaps I will have another go at anaconda on this linux machine.

Lots of complaining, but I appreciated how much effort it must take to maintain this project.
I am sure you do not wish your users to have an experience like the above.

Russ  Hensel 

-- I know this is not quite in the format of a bug report but has information I need to share.  If it should
be posted else where, then where? Thanks.

**Comment by PhilipYip1988** [comment]
I'd recommend using Mambaforge over Anaconda to install Spyder as the base environment in Anaconda has lots of old packages and the Anaconda team are generally very slow to release updates to Spyder... Mambaconda also uses the mamba package manager which addresses many issues experience with the conda package manager. 

In either case you should install Anaconda or Mambaconda using the .sh script **and make sure you activate the base environment during installation** (no unfortunately is the default option).

You will then need to create a new environment and install Spyder in it. In the case of Mambaforge use. For Anacnda you will need to use conda in place of mamba:

```
mamba create -n spyder-cf
mamba activate spyder-cf
mamba install -c conda-forge spyder
mamba install -c conda-forge cython seaborn scikit-learn sympy openpyxl xlrd xlsxwriter lxml sqlalchemy
```

P.S. if it helps, I documented my install of Spyder on both Ubuntu Linux and Windows 11:
https://github.com/PhilipYip1988/python-tutorials/tree/main/001_install

**Comment by russ-hensel** [comment]
ccordoba12:

I was not root, and did not use sudo. I just ran the script from my user Downloads directory.  But the installer choose the location root@bulldog:~/.local/Spyder-5.4.1.dev0/bin#, do not know why, it did give me a chance to change directory, but I thought the installer might know what is what, in any case why choose a hidden directory?  Currently the machine has neither anaconda or conda, not sure how i got the spyder.  At some point I may try an anaconda install, will surely not use sudo.

In any case since it was an experiment I thought you might like someone to try it.  Clearly  not as robust as you want it.

You need not solve my problem I have an older version of spyder 5 with a broken outline, and several others working better and
that is all I need for now.

I hope  the info will be useful to improve the installer.

Russ

 
PhilipYip1988:

Thanks I will try once I have recovered, mentally from this, and have a few hours to spend.  Guess I should not get
so near the bleeding edge, even if the message box on spyder encourages me to do it.

Again, thanks.

still Russ
