### ISSUE TITLE
How can I install M1 version of spyder (5.4.0) through terminal

### ISSUE THREAD

**Issue by river7816** [spyder-ide/spyder#20059]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hey, I learnt about spyder teams released new spyder 5.4.0, and also released experimental spyder for M1. I use miniconda, how can I installed M1 version through my terminal. For now, I use `conda install spyder=5.4.0` and I am not sure the verison I installed is intel version or M1 version.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.0
* Python version: 3.10
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @river7816, thanks for reporting. Are you using Conda-forge to install packages?

**Comment by river7816** [comment]
> Hey @river7816, thanks for reporting. Are you using Conda-forge to install packages?

Yeah, I am using `conda install -c conda-forge spyder=5.4.0` and I installed successfully, but I am not sure which version (M1 version or intel version) I am installed.

**Comment by ccordoba12** [comment]
You need to run

    conda list

and see if the packages that appear there have the `arm64` suffix attached to them. That means that you're using M1 packages.

**Comment by river7816** [comment]
So you mean if I want to install spyder=5.4.0 M1 version with `conda install -c conda-forge spyder=5.4.0`, it will automactically chose the version I want to installed. and I have checked my `conda list`, there's no `arm64` there, only
`spyder                    5.4.0           py310hbe9552e_0    conda-forge
spyder-kernels            2.4.0           unix_pyhd8ed1ab_1    conda-forge`

**Comment by ccordoba12** [comment]
> it will automactically chose the version I want to installed

Yeah, I think it does.

> there's no arm64 there

Spyder and Spyder-kernels are a pure Python packages, so they're not compiled for a specific architecture. So you need to check that string for any package in your environment.

**Comment by river7816** [comment]
okay, tks
