### ISSUE TITLE
How can I highlight searched words using Ctrl+F

### ISSUE THREAD

**Issue by sangheumcho** [spyder-ide/spyder#20065]
### What steps will reproduce the problem?

I am using Spyder 5.3.3.
In the previous version, it was possible to highlight searched words by Ctrl+F, however, it seems that the feature is gone in this version.

Do I miss something?

Thank you.

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.12 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by maurerle** [comment]
Can't reproduce using Spyder 5.4

1. Double click on any word, wait one second - all occurances of this word are highlighted
2. Strg+F, type word - all occurances of search word are highlighted

So it might help to update to the latest version - when it is released on conda?

**Comment by sangheumcho** [comment]
Do you mean this one?
![image](https://user-images.githubusercontent.com/36200030/202264734-7c242ca1-626d-4c95-a452-eed6a02f6c61.png)

Well, it seems the feature that I am looking for, but in the previous version, it was nicer like this.

![image](https://user-images.githubusercontent.com/36200030/202265116-e370978b-1af5-4eaa-95c7-50011799f4b6.png)

Then, I would change my question that can I customize the color?

**Comment by ccordoba12** [comment]
Hey @sangheumcho, thanks for reporting. Words are highlighted by default now with a grey color and that color can't be turned on/off as before. Furthermore, that color can't be adjusted because it was carefully selected to match our current syntax highlighting themes.
