### ISSUE TITLE
Update Ananconda

### ISSUE THREAD

**Issue by bmaungklang** [spyder-ide/spyder#20072]
### What steps will reproduce the problem?

Dear anyone who may can help me;

Kindly help me to update my Spyder in Ananconda
I try to input "conda update ananconda"
but the result show as below;
conda install ananconda
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

Note: you may need to restart the kernel to use updated packages.

PackagesNotFoundError: The following packages are not available from current channels:

  - ananconda

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
What should I do next ?

Warm regards,
Poppy Buris

**Comment by maurerle** [comment]
Conda normally reminds you to run `conda update -n base -c defaults conda ` if an update is available.

So this should work.
Please have in mind, that this issue tracker is about the Python IDE Spyder and not about conda :wink:

**Comment by bmaungklang** [comment]
@ccordoba12  Thank you very for your help!!
I put function as you said but still stuck in update spyder 5.3.3 
it's take too long about 3 hours still not finish yet.
![image](https://user-images.githubusercontent.com/113984605/202726854-b95f2f0d-fb0b-4ed3-a899-30d41aa12d92.png)

Do you know how to correct it? Sorry for my weakness.

Regards, Poppy

**Comment by ccordoba12** [comment]
@bmaungklang, in order to update Spyder, you need to close it, open the Anaconda Prompt (there's an entry for it in the Windows Start menu) and then run there

    conda install spyder=5.3.3

In the future, you need to run all `conda` commands in the Anaconda Prompt, not directly in Spyder.

**Comment by bmaungklang** [comment]
Dear @ccordoba12  Carlos

It keeps spinning like this 1 day more already.
![image](https://user-images.githubusercontent.com/113984605/202902663-94000534-39c9-48b0-905a-73aa03e9b753.png)
Do you have more recommendation sorry for my poor programming skill.

Regards, Pop Buris

**Comment by ccordoba12** [comment]
Don't worry Pop Buris, this is not your fault. It's actually a known problem with conda.

Then please run this command first

    conda remove spyder

and after it finishes, then you should be able to run

    conda install spyder=5.3.3

The first command will uninstall several packages because they are related to Spyder. But you can reinstall them after the last command.

**Comment by bmaungklang** [comment]
Dear @ccordoba12  

Thank you very much, it works !!
![image](https://user-images.githubusercontent.com/113984605/202916618-eda77d34-9408-4d7b-aac3-666547b814ce.png)
Finally, yeah
Can I add more question about when run coding after finish the result show in console.
Can I save the result in console after it done? because I ran TuckER and let computer awake for a few day and need to run next dataset but I can't dare to close the previous console that already done. 
:( It's ok if you can't help. I just want try to find a way to finish my work with advisor.

Warm regards,
Pop

**Comment by ccordoba12** [comment]
> Thank you very much, it works !!

Great! I'm really you were able to finally update Spyder.

> Can I save the result in console after it done?

Yes, it's possible. But I saw you open another issue about that, so I'll answer your question there.

**Comment by ccordoba12** [comment]
I'm going to close this issue since it's solved now.
