### ISSUE TITLE
Can't install Spyder via Anaconda Navigator

### ISSUE THREAD

**Issue by Dongxy1** [spyder-ide/spyder#20076]
After I downloaded the standalone Spyder, the Spyder in Anaconda Navigator was automatically uninstalled. And when I tried to reinstall via Anaconda Navigator, it took such a long time. How can I fix this?

* Spyder version: 
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: MacOS 12.0.1

![image](https://user-images.githubusercontent.com/51010970/202469017-c3f478a4-f8c7-48c6-8721-ba43971421cc.png)

**Comment by ccordoba12** [comment]
Hey @Dongxy1, thanks for reporting. We can't help you with this problem in Navigator, but you can install Spyder again by opening a terminal and running there

    conda update anaconda
    conda install spyder=5.3.3

Let us know if it works for you.

**Comment by Dongxy1** [comment]
> conda install spyder=5.3.3

Thank you for your reply! But I think these commands don't work for me. I just run this in the base, do I need to activate some environment to run it?

**Comment by ccordoba12** [comment]
I don't know. Did you install Spyder in another environment besides base?

**Comment by Dongxy1** [comment]
> I don't know. Did you install Spyder in another environment besides base?

I downloaded form https://www.spyder-ide.org/

**Comment by ccordoba12** [comment]
Ok, that will install a Spyder version which is independent of the one that comes with Anaconda.

But coming to what you said before

> But I think these commands don't work for me. I just run this in the base,

Why didn't the commands I mention work for you?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
