### ISSUE TITLE
How to save console result after run TuckER iteration finish

### ISSUE THREAD

**Issue by bmaungklang** [spyder-ide/spyder#20087]
### What steps will reproduce the problem?

Dear anyone;

Please help to guide me how to save the result after I run iteration about 250-500 training completed ?
I left computer open for a few day and finish then I could not save result and run the next dataset because the recent data traing will gone.

Regards, Pop

**Comment by ccordoba12** [comment]
Hey @bmaungklang, to save all results you run in the IPython console (i.e. inputs and outputs), you need to run the following command directly on it before running your code:

    %logstart -o

This should create a file called `ipython_log.py` in the console's current working directory (you can check that directory by running the command `%pwd` before `%logstart -o`).

When you want to stop recording results, you need to run

    %logoff

Here you can find more help about this command:

https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-logstart

Please try that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response. Hope the ideas I gave you were useful to solve your issue.
