### ISSUE TITLE
Find is not case sensitive

### ISSUE THREAD

**Issue by 1rdsk1** [spyder-ide/spyder#20086]
### Issue Report Checklist

* [Y] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

## Problem Description
When I search through a directory  for a specific word with for example first letter capitalized,  the result includes all instances of that word irrepsective of capitalisation.

### What steps reproduce the problem?
Use search>find in files on menu

### What is the expected output? 
all files containing word irrespective of capitalisation
What do you see instead?
just files with word with exactly same capitalisation

```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 5
* Python version: 3.8
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10

### Dependencies
na

**Comment by dalthviz** [comment]
Hi @1rdsk1 thank you for the feedback! To run case-sensitive searches with the Find in Files pane, you need to toggle the case-sentive option:

![image](https://user-images.githubusercontent.com/16781833/202802586-0908f8fd-2f3a-4068-a0f0-82140ba95423.png)

To check the functionality avaiable for the Find in Files pane or anyother pane you can check: https://docs.spyder-ide.org/current/panes/

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
