### ISSUE TITLE
the shortcut of hiding the Outline pane

### ISSUE THREAD

**Issue by yanyu2015** [spyder-ide/spyder#20102]
version spyder 5.3.3
press `Ctrl + Shift + O` can  show the Outline pane
but press `Ctrl + Shift + O` again, can not hide the Outline pane.

**Comment by ccordoba12** [comment]
Hey @yanyu2015, thanks for reporting. Unfortunately, this is not how our pane shortcuts work.

* If a pane (e.g. the Outline) is hidden, then `Ctrl+Shift+O` shows it, as you noticed.
* But if it's already visible, then the shortcut gives focus to the pane. Users take advantage of that behavior to switch between the editor and IPython console all the time.

Please check issue https://github.com/spyder-ide/ux-improvements/issues/73 for further thoughts about this issue.

**Comment by ccordoba12** [comment]
> What about pressing the same shortcut to close it when focus to the pane?

That's a good idea but it could be very annoying for unaware users if they press a shortcut by mistake twice.

> Another way is too float the outline pane on the main IDE when it is unlock, not to cover it when I click on the editor.

That's already possible for any plugin by going to its Options menu (the one with three horizontal lines on the top right) and clicking `Undock`:

![imagen](https://user-images.githubusercontent.com/365293/203359218-aa2ad890-30a5-48fd-9b5d-5beef73a135a.png)

**Comment by yanyu2015** [comment]
> That's a good idea but it could be very annoying for unaware users if they press a shortcut by mistake twice.

My suggestion is under the condition that the current cursor is already in the pane, because there is no shortcut for this case currently, so mistake can't happen.

> That's already possible for any plugin by going to its Options menu (the one with three horizontal lines on the top right) and clicking Undock:

Yes, it can be undock and float, however, if I move the cursor to the editor(in a py file), then the outline pane will be hide and I need to click the window again to show it. Can it be float always?

**Comment by ccordoba12** [comment]
> My suggestion is under the condition that the current cursor is already in the pane, because there is no shortcut for this case currently, so mistake can't happen.

If you had read issue https://github.com/spyder-ide/ux-improvements/issues/73, then you'd see that I suggested `Alt+Shift+C` as a shortcut to close any pane. If you agree with the idea, or have another suggestion, please post it there (this is my last message on this issue so we can continue the discussion there).

> Can it be float always?

No, that's not possible, sorry.
