### ISSUE TITLE
spyder crashes when starting up

### ISSUE THREAD

**Issue by bldrake** [spyder-ide/spyder#20112]
Python 3.9.13 (main, Aug 25 2022, 18:29:29) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin

The available OpenGL surface format was either not version 3.2 or higher or not a Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.
fromIccProfile: failed minimal tag size sanity

### What steps reproduce the problem?

1. open a command window
2. type: /Users/bd111/opt/anaconda3/bin/spyder

### What is the expected output? What do you see instead?
Expected behavior is that Spyder would launch with
the latest code in the edit pane, console pane, etc.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
An error ocurred while starting the kernel
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/usr/local/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 303, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.10/site‑packages/ipykernel/kernelapp.py", line 51, in
from .ipkernel import IPythonKernel
File "/usr/local/lib/python3.10/site‑packages/ipykernel/ipkernel.py", line 20, in
from .eventloops import _use_appnope
File "/usr/local/lib/python3.10/site‑packages/ipykernel/eventloops.py", line 12, in
from packaging.version import Version as V
ModuleNotFoundError: No module named 'packaging'
Traceback (most recent call last):
File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
exec(code, run_globals)
File "/usr/local/lib/python3.10/site‑packages/spyder_kernels/console/__main__.py", line 24, in
start.main()
File "/usr/local/lib/python3.10/site‑packages/spyder_kernels/console/start.py", line 303, in main
from ipykernel.kernelapp import IPKernelApp
File "/usr/local/lib/python3.10/site‑packages/ipykernel/kernelapp.py", line 51, in
from .ipkernel import IPythonKernel
File "/usr/local/lib/python3.10/site‑packages/ipykernel/ipkernel.py", line 20, in
from .eventloops import _use_appnope
File "/usr/local/lib/python3.10/site‑packages/ipykernel/eventloops.py", line 12, in
from packaging.version import Version as V
ModuleNotFoundError: No module named 'packaging'

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 21.6.0

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @bldrake, thanks for reporting. It seems you have another Python installation in your system that it's interfering with the Anaconda one.

Removing these directories should solve your problem

    /usr/local/lib/python3.10
    /usr/local/Cellar/python@3.10

(for the second one perhaps you need to Homebrew).

**Comment by ccordoba12** [comment]
Let us know if works for you.

**Comment by bldrake** [comment]
Hello Carlos,

I did as you suggested: "brew uninstall --ignore-dependencies ***@***.***"
This worked!

Thank you for your help.
Barry

________________________________________

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
