### ISSUE TITLE
'from odbAccess import *'  used; unable to detect undefined names (pyflakes E)

### ISSUE THREAD

**Issue by akhilpraka** [spyder-ide/spyder#20111]
![Screenshot (1)](https://user-images.githubusercontent.com/118907536/203558867-a4e2ea23-0876-45af-84ac-6da2238b4223.png)
kindly help me to fix this. not sure what is missing.

**Comment by ccordoba12** [comment]
Hey @akhilpraka, thanks for reporting. This is not an error, it's a warning. To learn more about it, please read this

https://stackoverflow.com/questions/50439309/spyder-ide-complaining-about-unable-to-detect-undefined-names

If you want to disable it, please add a `noqa` inline comment, like this:

```python
from odbAccess import *  # noqa
```
