### ISSUE TITLE
Runfile raising syntax error when a dictionary is passed as an argument

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [spyder-ide/spyder#20114]
## Problem Description
I am running a script for which I have to give an argument in the format of a dictionary inside a string (i.e. `"{'key1': 'value1', "key2': 'value2'}"`). This works perfectly fine when running it normally on the terminal. It gives a syntax error when running it with spyder.

### What steps reproduce the problem?

1. Have a script that requires an argument with argparser in the following format ` "{'key': 'value'}"`, for example `"{'pass_id': '092219_02022'}"`
2. Test the script by running it on the terminal (e.g. `python3 main.py "{'pass_id': '092219_02022'}"`)
3. Go to spyder --> run tab --> configuration per file --> Click on command line options, and add the argument `"{'pass_id': '092219_02022'}"`
4. Click Run button on spyder IDE

### What is the expected output? What do you see instead?
I would expect the program to run without a problem. However, a syntax error is raised. I have tried changing the quotes in the argument in several ways but still not working.

### Paste Traceback/Error Below (if applicable)

```python-traceback
runfile('/home/miguel/gitlab_projects/offline-trigger/main.py', args='"{'pass_id': '000493_KR00P'}"', wdir='/home/miguel/gitlab_projects/offline-trigger')
  Input In [5]
    runfile('/home/miguel/gitlab_projects/offline-trigger/main.py', args='"{'pass_id': '000493_KR00P'}"', wdir='/home/miguel/gitlab_projects/offline-trigger')
                                                                             ^
SyntaxError: invalid syntax

```

## Versions

* Spyder version: 5.1.5
* Python version: 3.8.12 64-bit
* Qt version: Qt 5.12.1
* PyQt version: PyQt5 5.12
* Operating System name/version: Linux 5.14.0-1054-oem

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  3.0.4 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.2 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.1.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.2 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<2.10.0        :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.2;<1.3.0          :  1.2.4 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.2 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.1.1;<2.2.0 :  2.1.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.19.0 (OK)
pandas >=1.1.1                :  1.4.1 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (OK)
```

**Comment by ccordoba12** [comment]
Hey @Miguel-LlamasLanza, thanks for reporting. It seems we need to escape single and/or double quotes in command line arguments for your use case to work. We'll try to take a look at that in a future release.

**Comment by Miguel-LlamasLanza** [comment]
Indeed, based on your answer, I checked that just escaping the quotes works. A workaround is to escape these characters manually, i.e. in my case writing (in the configuration per file) `\'{"pass_id": "092219_02022"}\'`.
In this case I escaped the single quotes but I guess it would work the other way as well.

I assume it is a very specific use-case which maybe it is not worth putting much time to tackle it. If this i the case I suggest that when the error is raised, a message suggesting to escape the quotes is included together with the raised error (maybe also link to this issue?).

**Comment by jitseniesen** [comment]
I tested this with the current development version, and it seems to work now. It got probably fixed incidentally with the changes in the runner. The quotes in the runfile invocation are now handled currently. In the example above, I get:
```
%runfile /home/jitse/tmp/dict-script.py --args '"{'"'"'pass_id'"'"': '"'"'092219_02022'"'"'}"' --wdir
```
Thus, I am closing this report. I don't think it's necessary to find out exactly where this got fixed.

**Comment by ccordoba12** [comment]
Thanks for checking this @jitseniesen!
