### ISSUE TITLE
Spyder 5.4 update for Anaconda OSX Py 3.11, when?

### ISSUE THREAD

**Issue by sarscov2** [spyder-ide/spyder#20139]
### Issue Report Checklist
* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * x[ ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Could someone from the Spyder team kindly provide a date for updating Spyder v5.4 onto Anaconda for OSX 13 with Python 3.11?

### What steps reproduce the problem?
The error message I keep getting is,

1. Your installed version is: not available
2. - spyder -> python[version='2.7.|3.5.|3.6.|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.']

That <3.11.0a0 is the issue.

### What is the expected output? What do you see instead?

A release date for Spyder 5.4 on Conda for Python 3.11

### Paste Traceback/Error Below (if applicable)

```python-traceback

spyder -> python[version='2.7.|3.5.|3.6.|>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|3.4.']
```

## Versions

* Spyder version: 5.4
* Python version: 3.11
* Qt version: 
* PyQt version: 
* Operating System name/version: OSX 13

### Dependencies

New conda environment installation NA
```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @sarscov2, thanks for reporting. Unfortunately, we have no influence on when packages are updated in Anaconda. To ask about that, please open an issue on this repository:

https://github.com/ContinuumIO/anaconda-issues

However, if you need to use Spyder along with Python 3.11 urgently, you can download our Mac app for 5.4.0 from here:

https://github.com/spyder-ide/spyder/releases/tag/v5.4.0

then use your the following command to create a new environment for Python 3.11

    conda create -n spyder-env -c conda-forge python=3.11 spyder-kernels

and finally connect Spyder to that environment by following these instructions:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment
