### ISSUE TITLE
Debugger is broken

### ISSUE THREAD

**Issue by StaticKling** [spyder-ide/spyder#20152]
### What steps will reproduce the problem?

Set a breakpoint in the code and click on the debug file button. The code execution/ debugger will not go past the first line of code and it does nothing. The app freezes until the Console is trashed/ new one started.

Step over doesnt work, step into doesnt work. Nothing works except the stop button, which only prints a --KeyboardInterrupt-- messsage to the console.

**Comment by ccordoba12** [comment]
Hey @StaticKling, thanks for reporting. This may be due to many factors and previous Spyder versions. So, please update Spyder to our latest version by closing it, opening the Anaconda Prompt or a terminal and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda). Then try again.

If that doesn't work, please report back.

**Comment by StaticKling** [comment]
Hi there, Sorry for the delay... I am limited to 5.1.1 or 5.2.2 due to compatibility with other packages in the environment (cloned from ArcGIS Pro, for use with ArcGIS). From what I gathered from other people that I work with, the debugger isn't working for them either and does the same stalling when started.

I tried 5.3.3 in a standalone install through anaconda, but it still wont debug. It also rendered the environment broken for ArcGIS so even if it did, I would be able to use it.

**Comment by ccordoba12** [comment]
> I tried 5.3.3 in a standalone install through anaconda, but it still wont debug

Ok, please update a simple code that doesn't work for you and upload a video showing the behavior you're seeing so we can get a better sense of what's happening in your case.

**Comment by StaticKling** [comment]
I can't get 5.3.3 installed in the environment anymore after a couple hours of trying (using conda, esri's conda, and Anaconda) and there comes a time when one has to call it a loss and move on. I had to recreate the base environments after it corrupted originally and it's becoming more of headache.  I'll wait for esri to verify the 5.3.3 version and try it again but for now, it's not happening.
