### ISSUE TITLE
Matplotlib interactive figure window not showing plots as expected

### ISSUE THREAD

**Issue by ycwang-hello** [spyder-ide/spyder#20158]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. **Settings**: Preferences -> IPython console -> Graphics -> Graphics backend set to "Automatic"
2. Start a "New console (default settings)"
3. Execute the following lines (one by one):
```
In [1]: import matplotlib.pyplot as plt
In [2]: plt.figure() # make a figure; a figure window should appear
In [3]: plt.plot([1, 0], [0, 1]) # plot something on the EXISTING figure
```

### What is the expected output? What do you see instead?
**Expected**: the line generated by `plt.plot([1, 0], [0, 1])` should be shown in the figure window.

**Actual behavior**: the line does not appear.

### Comparison with other consoles
`jupyter qtconsole`: the figure is shown inline, but here we have set "Graphics backend" to "Automatic" so that the figure should be shown in a separate window.

**Directly using IPython console in e.g. Anaconda prompt**: Without running `plt.ion()`, the figure is never shown until `plt.show()` is run.

In the console in Spyder, I would expect that no `plt.ion()` should be executed (as I never used it, and the figure window worked as I expected in some previous versions of Spyder).

## Versions

* Spyder version: 5.3.3
* Python version: 3.10.6
* Qt version: 5.15.6
* PyQt version: 5.15.7
* Operating System name/version: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  7.2.3 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.3 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.2.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.23.1 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @ycwang-hello, thanks for reporting. This seems to be a bug in Matplotlib because I can reproduce the problem you mentioned in its 3.5.2 version (like the one you have), but not in 3.6.2.

So, please close Spyder, update Matplotlib in the Anaconda Prompt and try again.

**Comment by ycwang-hello** [comment]
Updating Matplotlib does resolves the problem. Thank you!
