### ISSUE TITLE
how to stop creating new frame in plot pane for each matplotlib.pyplot command?

### ISSUE THREAD

**Issue by DanCodigaMWRA** [spyder-ide/spyder#20166]
This is not a bug report or a feature request, I don't think. It's more of a usage help question. If creating an issue here isn't the right way to get help, my apologies in advance-- direct me to where I should ask.

I would like to be able to add graphic items to an existing figure in a frame of the plots pane, without a new frame appearing there each time I execute a matplotlib.pyplot command.

I undock the plot pane (which btw, other than the confusion I am describing here, I find very helpful!) and run this code:

```
import matplotlib.pyplot as plt
plt.figure()

```
At this point there is no frame in the plot pane yet. 
(Not sure why-- for this first `plt.figure()` command I guess I would need to do `plt.show()` to make it appear?)

Anyway, then I do `plt.axes() ` and now there is a frame in the plot pane:

![image](https://user-images.githubusercontent.com/15674260/206276331-9bbb7986-6faf-41b3-a5d3-6d8d23f9ad52.png)

Then I do `plt.plot(range(10))` with the intent to insert a line in to the existing frame.
However, what happens is not as intended-- a second frame appears in the plot pane:

![image](https://user-images.githubusercontent.com/15674260/206276645-99bbdb02-7238-4ab2-ad54-d0822a827732.png)

Next I want to add a text item to the existing frame so I run `plt.text(0.5,0.5,'Text Item')` and once again, contrary to my goal, a new (third) frame appears withiin the plot pane (showing only the text item in it):

![image](https://user-images.githubusercontent.com/15674260/206277182-9e005275-788f-4b87-b64c-2e291457cb8f.png)

So the bottom line is that apparently I am not properly understanding how to control when `plt.show()` does or doesn't execute. 

I searched the issues and saw a lot of questions about turning inline plots on and off but this topic seems different.
I also looked at the documentation for the plots pane and didn't find info that would help me out on this.

Thanks in advance to anybody who can bring me up to speed on this!

 * Spyder version: 5.4.0  (conda)
* Python version: 3.8.13 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows 10

DEPENDENCIES
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.11.0 (OK)
nbconvert >=4.0               :  7.2.5 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.12.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.7 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.1 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.0 (OK)
numpy >=1.7                   :  1.23.3 (OK)
pandas >=1.1.1                :  1.5.0 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  None (NOK)

**Comment by dalthviz** [comment]
Hi @DanCodigaMWRA , are you runnig directly from the console or line by line, right? I think you need to run all the lines at the same time to properly setup the plot. So try running something like this (after importing previously `matplotlib.pyplot`):

```python
plt.figure()
plt.plot(range(10))
plt.text(0.5,0.5,'Text Item')
```

Doing that I'm able to get a single plot:

![image](https://user-images.githubusercontent.com/16781833/206324551-5b523133-4d7a-486b-96a1-939e2c40e1e7.png)

If you are running from the Console to add a new line to write code in the same prompt you can use `Ctrl + Enter`:

![image](https://user-images.githubusercontent.com/16781833/206324824-305a48b3-a746-4e0d-99f7-8b581f8ee5a4.png)

If you want to run the code from the Editor maybe a check to the cells definition could be useful: https://docs.spyder-ide.org/current/panes/editor.html#code-cells

Let us know if the info above helps!

**Comment by DanCodigaMWRA** [comment]
Appreciate the quick response @dalthviz. Yes, if I group the three commands together and enter them as a group, all the items appear on the same frame-- just as you have shown. And thanks for the tip about Cntrl-Enter, to be able to group commands before executing them.

However, in day to day work I need to be able to not only (1) run commands directly from the console line by line, but also (2) run cells, (3) run groups of lines in existing files that I have selected (using mouse right-click "run selection or current line), and of course (4) run scripts.

I find that when running scripts there is no issue-- that is, only one frame within the plot pane will be generated. As expected.

However, I commonly am stepping through code that builds a complex plot, which involves functions and code from multiple different files. Even using cells and Cntrl-Enter I think there is really no practical way for me to group all the commands so they can be run at one time. So what ends up happening is the multiple frames situation that I have described.

This makes it very hard to troubleshoot and debug my plotting code, as you can imagine. The work-around is that basically the main way for me to work is #4 above, run the entire script, and then look at the final output. I can't step through the code to isolate and analyze a subset of it. Makes my work a lot less efficient.

I may be the only one who gets bogged down by this issue, but it seems like perhaps others might benefit from a way to get around it?

I guess unless you teach me some other way to get past it, perhaps I am making a feature request after all:

The ability to apply 'hold' to the present figure in the plots pane, so that the next time a matlplotlib.pyplot command is executed, the plots pane will NOT generate a new figure/frame. Making it work this way as the default would be the best, in my opinion; if one wanted the other behavior, which currently occurs, one could maybe choose that as an alternate/non-default option.

Thoughts?

**Comment by dalthviz** [comment]
Oh I see, maybe [`plt.ioff`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ioff.html) could be useful then. With it, running individual lines will not show a plot. After setting up the plot, you will need to run [`plt.ion`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.ion.html#matplotlib.pyplot.ion) and then [`plt.show`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.show.html#matplotlib.pyplot.show) to see the plot being worked on.

Let us know if the info above helps!

**Comment by DanCodigaMWRA** [comment]
Okay those could really help-- I think we are getting closer, maybe. 

Working from the commandline, I see now that I can turn off interactive mode with `plt.ioff()`, then run a series of `plt ` commands, and no figure will appear yet in the plots pane-- but, as desired, all the commands will have been run on a single figure which I then can view by 'plt.show()'. So that's good!

However, once I have done `plt.show()`, if I try to then add other items to the existing figure by executing additional `plt` commands, they each generate a new frame within the plots pane. 

I tried `plt.ioff()` again, after `plt.show()` and before trying to add more items to the figure, but it didn't solve the problem-- I found that it made me able to run a series of `plt` commands but when I then used `plt.show()` to view the results, a new/additional frame was created in the plots pane.

Maybe I am missing something basic here but it seems to boil down to needing a way to be able to run `plt` commands that add to an existing figure which is already visible in the plot pane (without having an additional new frame in the plots pane automatically generated). 

Without this capability I'm really limited, because I often need to view the plot at various stages along the way as I am adding items to it. It is inefficient for me to add all the items to the plot first, then use `plt.show()` to see them only at the end after they are all included-- I need to see the figure after each stage of including another group of them.

**Comment by dalthviz** [comment]
In that case I think you need to save a reference to the figure and after calling `plt.show` call again `plt.figure` using the num `kwarg` to set the current plot to the plot you were working on. So for example you could run in different lines:

```python
plt.ioff()
```

```python
fig1 = plt.figure()
```

```python
plt.axes()
```

```python
plt.show()
```

And then to keep working with the same figure run:

```python
plt.figure(num=fig1)
```

Besides the suggestion above I think there is not much we can do on the Spyder side :/ Basically the behavior you were experiencing is the way Matplotlib works with the inline backend an the interactive option on (after each console prompt show the plot being worked on). The plots pane only shows the plots that matplotlib is generating.

Hopefully the info above helps you to improve your workflow with Matplotlib and Spyder :)

**Comment by DanCodigaMWRA** [comment]
Okay this helps a lot. I am definitely getting closer.

Just to recap, this is my goal (working from the command line interactively): 
Keep just one figure window in the plots pane, 
continue to periodically add groups of artists to it, 
stop after adding each group, to inspect the figure
-- all without creating a second figure window in the plots pane.

This example shows the closest I can get:

First I run `plt.ioff()` and then I can run the commands to create the plot and put the first group of artists on it (though it's not yet visible):
```
plt.figure()
plt.axes()
plt.plot(range(10))
plt.text(0.5,0.8,'Text item')
```

Next, I get the number of the current figure, and then make the figure visible (must be done in this order, or steps below won't work-- correct?):
```
fnum = plt.gcf()
plt.show()
```
(I choose to use `plt.gcf() `here, instead of` fnum = plt.figure()` up above as would be more like what you suggested in your example, because usually the call to `plt.figure()` is part of a bunch of code cut-pasted out of a script and it's inconvenient to edit any of it.)

Now I have one figure in the plots pane, with the first group of artists on it. I can inspect it. 

Then to add a second group of items to the existing figure, I do `plt.figure(num=fnum)` first, and then the commands to add them, 
```
plt.plot(range(6,-6,-1))
plt.text(0.1,0.2,'Second text item')
```
followed by `plt.show()`.

Now the figure appears, with both groups of elements on it, in the plots pane, and I can stop and inspect it. So that's good.

However, what actually happened is that the first frame in the plots pane was not added to. Instead it was left there, and a second/new frame was generated, which shows both groups of elements on it. 

It would be better if each time I added a group of elements to the plot, no new frame was added in the plots pane and instead the existing frame was added to. But it seems this isn't possible--so I'll have an extra frame in the plots pane for each group of artists I want to add, I guess-- correct?

Other suggestions welcome!

**Comment by dalthviz** [comment]
I think you got the general idea :+1: I don't think the extra frame is avoidable, but hopefully the suggestions above improved a little bit your workflow with Spyder :)

**Comment by DanCodigaMWRA** [comment]
Yes. I'm in a more comfortable place now. 

Just to confirm though, there is no command I can execute at the commandline in the ipython console that would delete one of the frames within the plots pane, correct? The only way to do this is to click the 'delete' (trashcan) button on the plots pane, right?

**Comment by dalthviz** [comment]
As far as I know there is not such a command sorry :/

 To delete the current plot you could also use the Plots pane shortcut for the delete action (`Ctrl + W`). To use it, you need to have the focus on the Plots pane since `Ctrl + W` is also the shortcut to close the current tab on the Console pane. You can change the application shortcuts by going to `Tools > Preferences > Keyboard shortcuts` and there search for `plots`).

**Comment by DanCodigaMWRA** [comment]
ok thanks @dalthviz !
