### ISSUE TITLE
spyder and python 3.11

### ISSUE THREAD

**Issue by enricopisoni** [spyder-ide/spyder#20208]
Dears
I would like to know when spyder for python 3.11, in conda, will be available.
I tried now to 'conda install' spyder in a python 3.11 virtual environment, but it seems not possible
Thanks
Bests
Enrico

can you please

**Comment by ccordoba12** [comment]
Hey @enricopisoni, thanks for reporting. We really don't know when that's going to happen because it's basically up to Anaconda to decide when they upload packages for new Python versions.

In the meantime, the best we can suggest you is to run the following commands:

    conda create -n py311 -c conda-forge python=3.11 spyder-kernels
    conda activate py311
    conda install -c conda-forge pandas matplotlib scikit-learn <put on this line any other package that you need to use>

    conda deactivate py311
    conda create -n spyder-env -c conda-forge python=3.10 spyder
    conda activate spyder-env
    spyder

and then follow [our guide](http://docs.spyder-ide.org/current/faq.html#using-existing-environment) to connect Spyder to the `py311` environment.

Hope that helps.

**Comment by enricopisoni** [comment]
Thanks @ccordoba12 for your reply!
I tried, but it seems I cannot install spyder kernels
belwo the error I get
thanks for your help
Enrico

***

conda install spyder-kernels
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - spyder-kernels -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

**Comment by ccordoba12** [comment]
The list of commands I posted above or the link to our docs don't include `conda install spyder-kernels`, so I don't understand what you mean.

**Comment by enricopisoni** [comment]
Dear @ccordoba12 

sorry, could be I misunderstood

but I saw you wrote: "conda create -n py311 -c conda-forge python=3.11 spyder-kernels"
and then I run the command, I get an error message on 'spyder-kernels'

but could be I am doing something wrong, so sorry to ask again

Bests
Enrico

**Comment by ccordoba12** [comment]
> but I saw you wrote: "conda create -n py311 -c conda-forge python=3.11 spyder-kernels"

Yes, that's the command I wrote.

> and then I run the command, I get an error message on 'spyder-kernels'

Sorry but the command you ran was

    conda install spyder-kernels

which is part of [your comment](https://github.com/spyder-ide/spyder/issues/20208#issuecomment-1357335361) above.

**Comment by enricopisoni** [comment]
sorry, it was my fault, now it works ;-) !
thanks a lot for your help
have a nice day, Enrico!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
