### ISSUE TITLE
Hi @larajan67,

### ISSUE THREAD

**Issue by kiajfaty** [spyder-ide/spyder#20200]
Hi @larajan67,
I had a hard time trying to replicate your issue but I could make it work. So I have my development environment in python 3.8, also I created another environment in python 2.7 where I installed the three packages that you mention with spyder-kernels which I found to be the tricky part. So, this is the step-by-step commands that I used and worked without having that error in the IPython console. 

```
conda create -n py2 python=2.7
conda activate py2
conda install -c conda-forge geopandas
```

The last command will install the three packages `georasters, rasterio, geopandas`

```
pip install spyder-kernels
```
Afterwards I opened a Spyder and connected the kernel with the executable of the environment `py2`. I could load a sample dataset and see it on the variable explorer.

![image](https://user-images.githubusercontent.com/20992645/90075636-836e5180-dcc3-11ea-817d-f2bd544006b3.png)

Hope you can work with your code as well and please let me know if these instructions helped in any further way

_Originally posted by @steff456 in https://github.com/spyder-ide/spyder/issues/13510#issuecomment-673146645_

**Comment by ccordoba12** [comment]
Hey @kiajfaty, I don't understand why you opened this issue but it seems to simply replicate a comment from an old one.

Since you didn't add any additional context about what this is about, I'm going to close it.
