### ISSUE TITLE
internal problem 

### ISSUE THREAD

**Issue by b-asma** [spyder-ide/spyder#20211]
### What steps will reproduce the problem?

I recently installed anaconda in ubuntu 20.04 then  updated the spyder but ran into this problem for my first use of the spyder IDE. The spyder editor is launched and the Issue reporter window appears with this internal problem description:

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

In addition, the terminal also displays this message:   fromIccProfile: failed minimal tag size sanity

### Traceback
```python-traceback
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
```

## Versions

* Spyder version: 5.4.0  (conda)
* Python version: 3.8.15 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-52-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.11.0 (OK)
nbconvert >=4.0               :  7.2.6 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.8 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.1 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.0 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.18.5 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.5.3 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @b-asma, thanks for reporting. How did you update Spyder in Anaconda? In other words, we need to know the command you used for that because that could be the cause of this problem:

> RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

This other problem

> In addition, the terminal also displays this message: fromIccProfile: failed minimal tag size sanity

is really a warning so you can ignore it.

**Comment by b-asma** [comment]
Hey @ccordoba12, Thank you so much for your answer.

I updated the spyder using this command:
`conda update spyder`

Then the problem is resolved when i change the environment to spyder-env, 

The worning : `fromIccProfile: failed minimal tag size sanity` still appeared but spyder run normally

Best regards

**Comment by ccordoba12** [comment]
> Then the problem is resolved when i change the environment to spyder-env

What do you mean by this? Did you have Spyder installed in another environment called spyder-env? Or did you change to that env in

    Preferences > Python interpreter

?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
