### ISSUE TITLE
TkAgg backend unresponsive window on Linux and OS X

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2022]
_From [dive...@gmail.com](https://code.google.com/u/101061052488374976516/) on 2014-10-23T07:55:23Z_

Spyder Version:  2.3.1
Python Version:  3.4.2
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.3.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1. Change backend to TkAgg in Spyder preferences, and restart Spyder
2. Run the following on the Spyder Console (not IPython): plt.plot([0, 1]) 

What is the expected output? What do you see instead?

 The window appear, but it is empty (on Linux), or has a spinning wheel (on OS X) or says "Not Responding" (on Windows 7, 8). What version of the product are you using? On what operating system? This bug is quite general. The above details refer to a clean install of Ubuntu Linux and Anaconda 2.0.1. But the same bug happens using Python 3.4 under Windows 7,8 and Mac OS X.

The problem was also reported in issue #1926 using Mac OS X and Python 2.7. I open here a new bug because it seems to affect nearly every Spyder installation and not just Anaconda on OS X as originally reported.

Under Windows the bug is present both using WinPython and Anaconda. This show the problem is not specific to Anaconda.

Moreover, using the Python console *outside* Spyder does not show the bug. This shows that the bug is limited to Spyder itself and not matplotlib (example below for the console)

import matplotlib as mpl
mpl.rcParams['backend'] = 'TkAgg'
import matplotlib.pyplot as plt
plt.ion()
plt.plot([0,1],[0,1]) 

Please provide any additional information below

. If I change the backend back to Qt4Agg in Spyder preferences, the plot appears normally. This show that the bug has nothing to do with my configuration.

The plot also appears with TkAgg if I type plt.pause(1). This is the same command I use to show a plot in an unresponsive windows during debugging with Spyder.

I am trying to use the 'TkAgg' backend as a workaround for the major long-standing issue #1831 , which makes Spyder basically unusable with Python 3 under Windows. So using IPython or the Qt4Agg backend are not an option for me, until issue #1831 is resolved.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2022_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-23T14:10:16Z_

I confirm the problem. I really don't know what could be happening....

**Status:** Accepted  
  **Labels:** MS-v2.3.2 Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [dive...@gmail.com](https://code.google.com/u/101061052488374976516/) on 2014-10-24T02:18:27Z_

Good. Thanks for checking @-ccordoba12

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-31T15:07:53Z_

**Labels:** -MS-v2.3.2 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:19:50Z_

issue #1926 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T19:33:48Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T10:39:37Z_

issue #2103 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T18:46:16Z_

**Labels:** -MS-v2.3.4 MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T21:30:08Z_

This issue was closed by revision 764249a1443a .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [dive...@gmail.com](https://code.google.com/u/101061052488374976516/) on 2015-02-11T07:33:43Z_

Unfortunately I see no changes in this bug under Windows, with Python 3 and either Anaconda or WinPython.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-16T06:56:00Z_

Yes, you're right. Too bad because I read an old blog post from Pierre and even he doesn't know how to fix this.

The only thing we can do is to definitely fix the Qt4Agg backend. But I'll do that in 2.3.4 because right now I don't know how to do that either.

**Summary:** TkAgg backend unresponsive window on Linux and OS X  \<span class="oldvalue"> (was: TkAgg backend unresponsive window on Linux, OS X and Windows) \</span>

**Comment by tacaswell** [comment]
Sorry to bump a very old issue, but I would not expect tkagg to work with in the context of spyder as it require two GUI toolkits to gracefully co-exist in one process.

Calling `plt.pause(1)` explicitly runs the Tk event loop for a second.  In the case of `plt.ion()` it is relying on the tk event loop being spun every so often.  It appears hung because this never happens (and would require spyder to implement a version of `PyOS_InputHook` for foreign (not Qt) GUI event loops.
