### ISSUE TITLE
regarding import sklearn 

### ISSUE THREAD

**Issue by Akashshankar96** [spyder-ide/spyder#20222]
### What steps will reproduce the problem?

regarding import sklearn ImportError: No module named 'sklearn.__check_build._check_build'
___________________________________________________________________________
Contents of C:\Users\91805\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\__check_build:
_check_build.cp311-win_amd64.pyd__init__.py               __pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.

## Versions

* Spyder version: 5.4.0  (pip)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment]
Hey @Akashshankar96, thanks for reporting. I have a question for you: how did you install Spyder?

**Comment by Akashshankar96** [comment]
I have installed directly from spider ide.org

**Comment by ccordoba12** [comment]
Ok, then please remove this directory

    C:\Users\91805\AppData\Local\Programs\Python

and follow [the instructions in our documentation](https://docs.spyder-ide.org/5/faq.html#using-packages-installer) to connect Spyder to an external environment that has Scikit-learn installed on it.

One important remark you need to take into account is that you need to replace

    conda install -c conda-forge ...

on every command that starts with

    conda install ...

Let us know if it works for you.

**Comment by Akashshankar96** [comment]
But I'm not using Anaconda..  how do I do this process

**Comment by ccordoba12** [comment]
You need an external Python environment to be able to use Scikit-learn, and we recommend to use a Anaconda for that because it's more robust and less prone to break.

Please watch the video part of the link in our documentation I posted I above to learn how to do that.

**Comment by Akashshankar96** [comment]
I have did what ever you said . I removed directory  import sklearnTraceback (most recent call last):   File "C:\Users\91805\AppData\Local\Temp\ipykernel_8120\2440152408.py", line 1, in <cell line: 1>    import sklearn ModuleNotFoundError: No module named 'sklearn'  WarningIt seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.Sent from Mail for Windows From: Carlos CordobaSent: Tuesday, December 20, 2022 9:38 PMTo: spyder-ide/spyderCc: Akash_sh_ar; MentionSubject: Re: [spyder-ide/spyder] regarding import sklearn (Issue #20222) Ok, then please remove this directoryC:\Users\91805\AppData\Local\Programs\Pythonand follow the instructions in our documentation to connect Spyder to an external environment that has Scikit-learn installed on it.One important remark you need to take into account is that you need to replaceconda install -c conda-forge ...on every command that starts withconda install ...Let us know if it works for you.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by ccordoba12** [comment]
> I have did what ever you said . I removed directory

Sure, and after removing that directory, you need to follow the instructions in our documentation, as I said above. So, please do that.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Akashshankar96** [comment]
Thank you for your response. And my solution is resolved now thanks

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by Akashshankar96** [comment]
Thank you for your support!
