### ISSUE TITLE
Spyder stops working properly after I've been using it for about an hour?

### ISSUE THREAD

**Issue by lokon100** [spyder-ide/spyder#20228]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After I've been working on my code for an hour or two sometimes Spyder will stop letting me clear my variables or restart the kernel? It shows the line in the console that it's doing it but nothing happens. Sometimes it also just won't run the code when it's doing that. There isn't an error message or anything it just doesn't wanna work. Otherwise it acts fine, lets me do whatever I want in the console and deleting the variables ect.
I installed it for the first time last Monday, and reinstalled it on Friday (it is now Monday again :)), and did the update for conda and reset the preferences.
Closing and reopening it fixes the issue.
If I run spyder --reset it returns an error

### What steps reproduce the problem?

1. Open your code and work on it for a bit
2. Try to clear the variables
3. Have the variables not clear and not be able to type into the console/sometimes not be able to run code.
4. Run spyder --reset

### What is the expected output? What do you see instead?

Expected output is being able to use variable explorer/the console/run code

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "C:\Users\Skye\AppData\Local\Temp\ipykernel_18696\197947205.py", line 1, in <cell line: 1>
    spyder --reset

NameError: name 'spyder' is not defined

```
## Versions
* Spyder version: 5.4.0 (standalone)
* Python version: 3.8.20 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 11

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.0.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree                         :  None (OK)
IPython >=7.31.1;<8.0.0              :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.1 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.0 (OK)
keyring >=17.0.0                     :  23.9.3 (OK)
nbconvert >=4.0                      :  7.2.3 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
paramiko >=2.4.0                     :  2.11.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.3 (OK)
pygments >=2.0                       :  2.13.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.5 (OK)
pylint_venv >=2.1.1                  :  2.3.0 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                 :  1.6.0 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.2.1 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  65.5.1 (OK)
sphinx >=0.6.6                       :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0        :  2.4.0 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog                             :  2.1.9 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.32 (OK)
matplotlib >=3.0.0                   :  3.6.2 (OK)
numpy >=1.7                          :  1.22.4 (OK)
pandas >=1.1.1                       :  1.5.1 (OK)
scipy >=0.17.0                       :  1.9.3 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @lokon100, thanks for reporting. I think this is related to the code you're running in Spyder more than to an internal problem on our side. However, in order to test that, you need to give us a simple code example that reproduces your problem for us to check it and see how to address this issue. Other than that, there's little we can about this.

You also said:

> Run spyder --reset

That command is meant to be run in a system terminal, not in our IPython console. So, please try to do that and see if it helps.

**Comment by ccordoba12** [comment]
> That command is meant to be run in a system terminal, not in our IPython console. So, please try to do that and see if it helps.

Sorry, I just saw that you're using our standalone version. In that case, you need to go to the menu

    Tools > Reset Spyder to factory defaults

to reset our settings.

**Comment by lokon100** [comment]
This is what I have been running:
[stats_question_mark.txt](https://github.com/spyder-ide/spyder/files/10279826/stats_question_mark.txt)
[stats_functions.txt](https://github.com/spyder-ide/spyder/files/10279830/stats_functions.txt)
[stats_variables.txt](https://github.com/spyder-ide/spyder/files/10279832/stats_variables.txt)
[config.txt](https://github.com/spyder-ide/spyder/files/10279859/config.txt)

However it has been having this issue since a little bit after I started working on it:
[message(1).txt](https://github.com/spyder-ide/spyder/files/10279843/message.1.txt)

It imports information from a csv (originally) or xlsx (started doing that yesterday) file and kicks out stats.
[bookings(test).csv](https://github.com/spyder-ide/spyder/files/10279847/bookings.test.csv)


I did _Tools > Reset Spyder to factory defaults_ and the code that worked previous now returned, and I've never got an error that looks like this before:

```
Traceback (most recent call last):

  File "C:\Program Files\Spyder\pkgs\spyder_kernels\customize\spydercustomize.py", line 469, in exec_code
    exec_fun(compile(ast_code, filename, 'exec'), ns_globals, ns_locals)

  File "C:\Program Files\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\skye\dropbox\cre8ive files\python\booking stats\stats_question_mark.py", line 13, in <module>
    from stats_variables import bookings_csv, bookings_tuples, name, studio_name, studio_type, week_names, weekday, weekend # analysis:ignore

  File "C:\Users\Skye\Dropbox\Cre8ive Files\Python\Booking Stats\stats_variables.py", line 63, in <module>
    created_raw, date_raw, duration_raw, names_all, studios_all, complete_raw, days_prev_raw = version_1_import(file_location)

  File "C:\Users\Skye\Dropbox\Cre8ive Files\Python\Booking Stats\stats_functions.py", line 56, in version_1_import
    for col in file:

  File "csv.py", line 110, in __next__

  File "csv.py", line 97, in fieldnames

  File "encodings\cp1252.py", line 23, in decode

UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 700: character maps to <undefined>


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Program Files\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\skye\dropbox\cre8ive files\python\booking stats\stats_question_mark.py", line 82, in <module>
    average_calc = round((dur_sum / count), 1)

ZeroDivisionError: division by zero
```

**Comment by ccordoba12** [comment]
Sorry but it seems your code has some errors that you need to fix first before we can test it on our side. Let us know when you managed to fix them to take a look at this again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
