### ISSUE TITLE
Issue importing and using pandas

### ISSUE THREAD

**Issue by TomerGadol** [spyder-ide/spyder#20235]
### What steps will reproduce the problem?

attempting to import pandas library and\or attempting to use dataframes with pandas

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    return_value = self._remote_callback(
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 270, in _remote_callback
    return super(FrontendComm, self)._remote_callback(
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 194, in get_namespace_view
    view = make_remote_view(ns, settings, EXCLUDED_NAMES)
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\utils\nsview.py", line 688, in make_remote_view
    'type':  get_human_readable_type(value),
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\utils\nsview.py", line 542, in get_human_readable_type
    text = get_type_string(item)
  File "C:\Users\tomer\anaconda3\lib\site-packages\spyder_kernels\utils\nsview.py", line 511, in get_type_string
    if isinstance(item, pd.DataFrame):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.9.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.24.0 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @TomerGadol, thanks for reporting. This could be due to an installation issue with Pandas. To check that, please open the Anaconda Prompt and run there

    conda list

and post the results here.

**Comment by TomerGadol** [comment]
> Hey @TomerGadol, thanks for reporting. This could be due to an installation issue with Pandas. To check that, please open the Anaconda Prompt and run there
> 
> ```
> conda list
> ```
> 
> and post the results here.

Here it is:

(base) C:\Users\tomer>conda list
# packages in environment at C:\Users\tomer\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0
absl-py                   1.2.0                    pypi_0    pypi
accelerate                0.12.0                   pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
alabaster                 0.7.12             pyhd3eb1b0_0
albumentations            1.3.0                    pypi_0    pypi
altair                    4.2.0                    pypi_0    pypi
anaconda-client           1.11.0           py39haa95532_0
anaconda-navigator        2.3.0            py39haa95532_0
analytics-python          1.4.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     3.5.0            py39haa95532_0
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0
arrow                     1.2.3            py39haa95532_0
astroid                   2.11.7           py39haa95532_0
asttokens                 2.0.5              pyhd3eb1b0_0
atomicwrites              1.4.0                      py_0
attrs                     22.1.0           py39haa95532_0
autopep8                  1.6.0              pyhd3eb1b0_1
babel                     2.9.1              pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
backoff                   1.10.0                   pypi_0    pypi
backports                 1.1                pyhd3eb1b0_0
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0
backports.tempfile        1.0                pyhd3eb1b0_1
backports.weakref         1.0.post1                  py_1
bcrypt                    3.2.0            py39h2bbff1b_1
beautifulsoup4            4.11.1           py39haa95532_0
binaryornot               0.4.4              pyhd3eb1b0_1
black                     22.6.0           py39haa95532_0
bleach                    4.1.0              pyhd3eb1b0_0
blinker                   1.5                      pypi_0    pypi
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotlipy                  0.7.0           py39h2bbff1b_1003
bzip2                     1.0.8                he774522_0
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cairo                     1.16.0            h63a05c6_1001    conda-forge
camelot-py                0.10.1             pyhd8ed1ab_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h2bbff1b_2
chardet                   4.0.0           py39haa95532_1003
charset-normalizer        2.0.4              pyhd3eb1b0_0
clean-fid                 0.1.31                   pypi_0    pypi
click                     8.0.4            py39haa95532_0
clip                      1.0                      pypi_0    pypi
cloudpickle               2.0.0              pyhd3eb1b0_0
clyent                    1.2.2            py39haa95532_1
colorama                  0.4.5            py39haa95532_0
commonmark                0.9.1                    pypi_0    pypi
conda                     22.11.1          py39hcbf5309_1    conda-forge
conda-build               3.22.0           py39haa95532_0
conda-content-trust       0.1.3            py39haa95532_0
conda-env                 2.6.0                haa95532_1
conda-package-handling    1.9.0            py39h8cc25b3_1
conda-repo-cli            1.0.24           py39haa95532_0
conda-token               0.4.0              pyhd3eb1b0_0
conda-verify              3.4.2                      py_1
console_shortcut          0.1.1                         4
contourpy                 1.0.6            py39h1f6ef14_0    conda-forge
cookiecutter              1.7.3              pyhd3eb1b0_0
cryptography              38.0.1           py39h21b164f_0
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
debugpy                   1.5.1            py39hd77b12b_0
decorator                 5.1.1              pyhd3eb1b0_0
defusedxml                0.7.1              pyhd3eb1b0_0
diff-match-patch          20200713           pyhd3eb1b0_0
dill                      0.3.6            py39haa95532_0
distro                    1.8.0                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.18.1           py39haa95532_3
eigen                     3.4.0                h2d74725_0    conda-forge
einops                    0.4.1                    pypi_0    pypi
entrypoints               0.4              py39haa95532_0
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 0.8.3              pyhd3eb1b0_0
expat                     2.5.0                h1537add_0    conda-forge
fastapi                   0.85.0                   pypi_0    pypi
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.6.0              pyhd3eb1b0_0
flake8                    4.0.1              pyhd3eb1b0_1
flit-core                 3.6.0              pyhd3eb1b0_0
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py39ha55989b_1    conda-forge
freetype                  2.12.1               ha860e81_0
ftfy                      6.1.1                    pypi_0    pypi
future                    0.18.2           py39haa95532_1
gdown                     4.5.1                    pypi_0    pypi
gettext                   0.21.1               h5728263_0    conda-forge
ghostscript               0.7                      pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
glib                      2.74.1               h12be248_1    conda-forge
glib-tools                2.74.1               h12be248_1    conda-forge
glob2                     0.7                pyhd3eb1b0_0
google-auth-oauthlib      0.4.6                    pypi_0    pypi
gradio                    3.3.1                    pypi_0    pypi
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
h11                       0.12.0                   pypi_0    pypi
hdf5                      1.12.2          nompi_h2a0e4a3_100    conda-forge
httpcore                  0.15.0                   pypi_0    pypi
httpx                     0.23.0                   pypi_0    pypi
huggingface-hub           0.9.1                    pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      2.10                     pypi_0    pypi
imageio                   2.22.0                   pypi_0    pypi
imageio-ffmpeg            0.4.7                    pypi_0    pypi
imagesize                 1.4.1            py39haa95532_0
importlib-metadata        4.11.3           py39haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
inflection                0.5.1            py39haa95532_0
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
intervaltree              3.1.0              pyhd3eb1b0_0
ipykernel                 6.15.2           py39haa95532_0
ipython                   7.31.1           py39haa95532_1
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.5              pyhd3eb1b0_1
isort                     5.9.3              pyhd3eb1b0_0
jedi                      0.18.1           py39haa95532_1
jellyfish                 0.9.0            py39h2bbff1b_0
jinja2                    2.11.3             pyhd3eb1b0_0
jinja2-time               0.2.0              pyhd3eb1b0_3
jpeg                      9e                   h2bbff1b_0
json5                     0.9.6              pyhd3eb1b0_0
jsonmerge                 1.8.0                    pypi_0    pypi
jsonschema                4.16.0           py39haa95532_0
jupyter_client            7.4.7            py39haa95532_0
jupyter_core              4.11.2           py39haa95532_0
jupyter_server            1.18.1           py39haa95532_0
jupyterlab                3.5.0            py39haa95532_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_server         2.10.3             pyhd3eb1b0_1
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
k-diffusion               0.0.1                    pypi_0    pypi
keyring                   23.4.0           py39haa95532_0
kiwisolver                1.4.4            py39h1f6ef14_1    conda-forge
kornia                    0.6.7                    pypi_0    pypi
krb5                      1.20.1               h6609f42_0    conda-forge
lazy-object-proxy         1.6.0            py39h2bbff1b_0
lcms2                     2.14                 h90d422f_0    conda-forge
lerc                      3.0                  hd77b12b_0
libarchive                3.6.1                hebabd0d_0
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libclang                  12.0.0          default_h627e005_2
libcurl                   7.86.0               h68f0423_2    conda-forge
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_6
libglib                   2.74.1               he8f3873_1    conda-forge
libhwloc                  2.8.0                h039e092_1    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblief                   0.11.5               hd77b12b_1
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.20.2               h12be248_0    conda-forge
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h6c2663c_0
libssh2                   1.10.0               h680486a_3    conda-forge
libtiff                   4.4.0                h8a3f274_2
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.4                h2bbff1b_0
libwebp-base              1.2.4                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
libzlib                   1.2.13               hcfcfb64_4    conda-forge
linkify-it-py             1.0.3                    pypi_0    pypi
lmdb                      1.3.0                    pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_1
m2-msys2-runtime          2.5.0.17080.65c939c               3
m2-patch                  2.7.5                         2
markdown-it-py            2.1.0                    pypi_0    pypi
markupsafe                2.0.1            py39h2bbff1b_0
matplotlib-base           3.6.2            py39haf65ace_0    conda-forge
matplotlib-inline         0.1.6            py39haa95532_0
mccabe                    0.7.0              pyhd3eb1b0_0
mdit-py-plugins           0.3.1                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
menuinst                  1.4.19           py39h59b6b97_0
mistune                   0.8.4           py39h2bbff1b_1000
mkl                       2022.1.0           h6a75c08_874    conda-forge
monotonic                 1.6                      pypi_0    pypi
msys2-conda-epoch         20160418                      1
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy_extensions           0.4.3            py39haa95532_1
navigator-updater         0.3.0            py39haa95532_0
nbclassic                 0.4.8            py39haa95532_0
nbclient                  0.5.13           py39haa95532_0
nbconvert                 6.4.4            py39haa95532_0
nbformat                  5.5.0            py39haa95532_0
nest-asyncio              1.5.5            py39haa95532_0
notebook                  6.5.2            py39haa95532_0
notebook-shim             0.2.2            py39haa95532_0
numpy                     1.23.5                   pypi_0    pypi
numpydoc                  1.5.0            py39haa95532_0
oauthlib                  3.2.1                    pypi_0    pypi
omegaconf                 2.2.3                    pypi_0    pypi
opencv                    4.6.0            py39h104de81_2
opencv-python             4.6.0.66                 pypi_0    pypi
opencv-python-headless    4.6.0.66                 pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openpyxl                  3.0.10           py39ha55989b_2    conda-forge
openssl                   1.1.1s               hcfcfb64_1    conda-forge
orjson                    3.8.0                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.5.2            py39h2ba5b7c_0    conda-forge
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.8.1              pyhd3eb1b0_0
parso                     0.8.3              pyhd3eb1b0_0
pathlib                   1.0.1              pyhd3eb1b0_1
pathspec                  0.9.0            py39haa95532_0
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.45                 hd77b12b_0
pcre2                     10.40                h17e33f8_0    conda-forge
pdfminer.six              20221105           pyhd8ed1ab_0    conda-forge
pdftopng                  0.2.3            py39h3210058_3    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.2.0            py39hdc2b20a_1
pip                       22.2.2                   pypi_0    pypi
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
pkginfo                   1.8.3            py39haa95532_0
platformdirs              2.5.2            py39haa95532_0
pluggy                    1.0.0            py39haa95532_1
ply                       3.11             py39haa95532_0
poppler                   22.04.0              hb57f792_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
powershell_shortcut       0.0.1                         3
poyo                      0.5.0              pyhd3eb1b0_0
prometheus_client         0.14.1           py39haa95532_0
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0
protobuf                  3.19.5                   pypi_0    pypi
psutil                    5.9.0            py39h2bbff1b_0
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2
pudb                      2022.1.2                 pypi_0    pypi
pure_eval                 0.2.2              pyhd3eb1b0_0
py-lief                   0.11.5           py39hd77b12b_1
pyarrow                   9.0.0                    pypi_0    pypi
pyasn1-modules            0.3.0rc1                 pypi_0    pypi
pycodestyle               2.8.0              pyhd3eb1b0_0
pycosat                   0.6.4            py39h2bbff1b_0
pycparser                 2.21               pyhd3eb1b0_0
pycryptodome              3.15.0                   pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pydeck                    0.8.0b3                  pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pydocstyle                6.1.1              pyhd3eb1b0_0
pydub                     0.25.1                   pypi_0    pypi
pyflakes                  2.4.0              pyhd3eb1b0_0
pygments                  2.11.2             pyhd3eb1b0_0
pyjwt                     2.4.0            py39haa95532_0
pylint                    2.14.5           py39haa95532_0
pyls-spyder               0.4.0              pyhd3eb1b0_0
pympler                   1.0.1                    pypi_0    pypi
pynacl                    1.5.0            py39h8cc25b3_0
pyopenssl                 22.0.0             pyhd3eb1b0_0
pyparsing                 3.0.9            py39haa95532_0
pypdf2                    2.11.1             pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py39hd77b12b_0
pyqt5-sip                 12.11.0          py39hd77b12b_0
pyqtwebengine             5.15.7           py39hd77b12b_0
pyrsistent                0.18.0           py39h196d8e1_0
pysocks                   1.7.1            py39haa95532_0
python                    3.9.13               h6244533_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python-fastjsonschema     2.16.2           py39haa95532_0
python-libarchive-c       2.9                pyhd3eb1b0_1
python-lsp-black          1.2.1            py39haa95532_0
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0
python-lsp-server         1.5.0            py39haa95532_0
python-multipart          0.0.5                    pypi_0    pypi
python-slugify            5.0.2              pyhd3eb1b0_0
python_abi                3.9                      2_cp39    conda-forge
pytorch-lightning         1.7.7                    pypi_0    pypi
pytz                      2022.1           py39haa95532_0
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywin32                   305              py39h2bbff1b_0
pywin32-ctypes            0.2.0           py39haa95532_1000
pywinpty                  2.0.2            py39h5da7b33_0
pyyaml                    6.0              py39h2bbff1b_1
pyzmq                     23.2.0           py39hd77b12b_0
qdarkstyle                3.0.2              pyhd3eb1b0_0
qstylizer                 0.1.10             pyhd3eb1b0_0
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_4
qtawesome                 1.0.3              pyhd3eb1b0_0
qtconsole                 5.3.2            py39haa95532_0
qtpy                      2.2.0            py39haa95532_0
qtwebkit                  5.212                h3ad3cdb_4
qudida                    0.0.4                    pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
resize-right              0.0.2                    pypi_0    pypi
rfc3986                   1.5.0                    pypi_0    pypi
rich                      12.5.1                   pypi_0    pypi
rope                      0.22.0             pyhd3eb1b0_0
rtree                     0.9.7            py39h2eaa2aa_1
ruamel.yaml               0.16.12          py39h2bbff1b_3
ruamel.yaml.clib          0.2.6            py39h2bbff1b_1
scipy                     1.9.3                    pypi_0    pypi
semver                    2.13.0                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1
sentry-sdk                1.9.9                    pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                65.5.0           py39haa95532_0
shortuuid                 1.0.9                    pypi_0    pypi
sip                       6.6.2            py39hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.2.0            py39haa95532_1
snowballstemmer           2.2.0              pyhd3eb1b0_0
sortedcontainers          2.4.0              pyhd3eb1b0_0
soupsieve                 2.3.2.post1      py39haa95532_0
sphinx                    5.0.2            py39haa95532_0
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0
spyder                    5.3.3            py39haa95532_0
spyder-kernels            2.3.3            py39haa95532_0
sqlite                    3.40.0               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
starlette                 0.20.4                   pypi_0    pypi
streamlit                 1.13.0                   pypi_0    pypi
tabula-py                 2.6.0                    pypi_0    pypi
tabulate                  0.9.0              pyhd8ed1ab_1    conda-forge
tb-nightly                2.11.0a20220926          pypi_0    pypi
tbb                       2021.7.0             h91493d7_1    conda-forge
tensorboard               2.10.1                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
terminado                 0.13.1           py39haa95532_0
test-tube                 0.7.5                    pypi_0    pypi
testpath                  0.6.0            py39haa95532_0
text-unidecode            1.3                pyhd3eb1b0_0
textdistance              4.2.1              pyhd3eb1b0_0
three-merge               0.1.1              pyhd3eb1b0_0
tinycss                   0.4             pyhd3eb1b0_1002
tk                        8.6.12               h2bbff1b_0
tokenizers                0.12.1                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py39haa95532_0
tomlkit                   0.11.1           py39haa95532_0
toolz                     0.12.0           py39haa95532_0
torch                     1.12.1                   pypi_0    pypi
torch-fidelity            0.3.0                    pypi_0    pypi
torchdiffeq               0.2.3                    pypi_0    pypi
torchmetrics              0.9.3                    pypi_0    pypi
torchvision               0.13.1                   pypi_0    pypi
tornado                   6.2              py39h2bbff1b_0
tqdm                      4.64.1           py39haa95532_0
traitlets                 5.1.1              pyhd3eb1b0_0
transformers              4.22.1                   pypi_0    pypi
typing-extensions         4.4.0            py39haa95532_0
typing_extensions         4.4.0            py39haa95532_0
tzdata                    2022.4                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.4.0            py39hd77b12b_0
unicodedata2              15.0.0           py39ha55989b_0    conda-forge
unidecode                 1.2.0              pyhd3eb1b0_0
urllib3                   1.26.12          py39haa95532_0
urwid                     2.1.2                    pypi_0    pypi
urwid-readline            0.13                     pypi_0    pypi
uvicorn                   0.18.3                   pypi_0    pypi
validators                0.20.0                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
wandb                     0.13.3                   pypi_0    pypi
watchdog                  2.1.6            py39haa95532_0
wcwidth                   0.2.5              pyhd3eb1b0_0
webencodings              0.5.1            py39haa95532_1
websocket-client          0.58.0           py39haa95532_4
websockets                10.3                     pypi_0    pypi
whatthepatch              1.0.2            py39haa95532_0
wheel                     0.37.1             pyhd3eb1b0_0
widgetsnbextension        3.5.2            py39haa95532_0
win_inet_pton             1.1.0            py39haa95532_0
wincertstore              0.2              py39haa95532_2
winpty                    0.4.3                         4
wrapt                     1.14.1           py39h2bbff1b_0
xz                        5.2.8                h8cc25b3_0
yaml                      0.2.5                he774522_0
yapf                      0.32.0                   pypi_0    pypi
zeromq                    4.3.4                hd77b12b_0
zipp                      3.8.0            py39haa95532_0
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h19a0ad4_0


This issue seems to have resolved itself since then, pandas is working as intended.

**Comment by TomerGadol** [comment]
Thanks for the detailed explanation! I now understand that I made a giant mess with my python installation.
Honestly, I've only taken 1 course in python and I've been following internet tutorials since so I didn't know about virtual environments and how important it is to compartmentalize the packages.

If a specific package is not available on conda but on conda-forge, can I mix these 2?

At the moment everything works but I'll probably uninstall and reinstall Anaconda soon anyway.

**Comment by ccordoba12** [comment]
>  a specific package is not available on conda but on conda-forge, can I mix these 2?

Nop because, for instance, Numpy and Pandas packages for conda and conda-forge are binary incompatible, which means that they were compiled differently.

So, we recommend you to install everything from conda-forge because it has much more packages than conda.

> At the moment everything works but I'll probably uninstall and reinstall Anaconda soon anyway.

Ok, good to know. I'm going to close this issue then.
