### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2'   Warning It seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.

### ISSUE THREAD

**Issue by MaheshkumarGovind** [spyder-ide/spyder#20230]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @MaheshkumarGovind, thanks for reporting. I don't understand what's the problem you want to report because you didn't post any information here.

Please follow the instructions mentioned in the webpage that is shown after clicking in the link present in the warning you mentioned. That will allow you to use Spyder with cv2.

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
