### ISSUE TITLE
Pip Spyder Not Starting due to Qt5 ImportError

### ISSUE THREAD

**Issue by UxuginPython** [spyder-ide/spyder#20244]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports *May be related to #6985*
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related) *N/A*
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/) *N/A - Installed with Pip*
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I try to start Spyder installed with Pip, it throws an `ImportError` relating to Qt. However, installing with DNF works correctly. DNF installs Spyder 5.3.1.

### What steps reproduce the problem?

1. Install Spyder with `pip3 install spyder`
2. Try to start Spyder

### What is the expected output? What do you see instead?
I expect Spyder to launch correctly. Instead, I get the error below.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/home/redacted/.local/bin/spyder", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/redacted/.local/lib/python3.11/site-packages/spyder/app/start.py", line 248, in main
    from spyder.app import mainwindow
  File "/home/redacted/.local/lib/python3.11/site-packages/spyder/app/mainwindow.py", line 57, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redacted/.local/lib/python3.11/site-packages/qtpy/QtWebEngineWidgets.py", line 28, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: /home/redacted/.local/lib/python3.11/site-packages/PyQt5/Qt5/lib/libQt5WebEngineCore.so.5: undefined symbol: _ZNSt12out_of_rangeC1EPKc, version Qt_5

```

## Versions

* Spyder version: 5.4.0
* Python version: 3.11.0
* Qt version: 5.15.7
* PyQt version: 5.15.6
* Operating System name/version: Fedora 37 KDE

### Dependencies

Spyder won't launch, so I can't use Help > Dependencies. However, installing with DNF works correctly, so here are the dependencies from that:

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  8.5.0 (NOK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.10.0 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  6.4.5 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.4 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.1 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.6.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.0 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.22.0 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.8.1 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by Dan-Patterson** [comment]
did you see
IPython >=7.31.1;<8.0.0       :  8.5.0 (NOK)
Did you try to fix this dependency error?

**Comment by UxuginPython** [comment]
@Dan-Patterson I did see that, and a popup comes up when I launch the DNF version of Spyder. I downgraded the package with Pip, but I could not get DNF to do it as the Fedora repos no longer provide a compatible version and I could not find an RPM on pkgs.org. The error persists after downgrading Pip, and the DNF version still has the dependency error. Unfortunately, DNF Spyder automatically installs IPython 8.5 though DNF, and I cannot remove this without also removing Spyder. The error with Pip Spyder persists regardless of whether DNF IPython is installed. I have not successfully solved either the dependency error or the `ImportError` regardless of the DNF and Pip versions of IPython. TL;DR: Downgrading Pip IPython doesn't fix either error. I can't downgrade DNF IPython. Removing DNF IPython also removes DNF Spyder and doesn't fix the `ImportError`.

**Comment by ccordoba12** [comment]
Hey @UxuginPython, thanks for reporting. It seems you're mixing packages installed using pip with those provided by Fedora. Unfortunately, that's a recipe for disaster because they are binary incompatible and most probably the source of the error you're facing.

Therefore, my recommendation is for you to remove this directory 

    /home/redacted/.local/lib/python3.11

and instead install Spyder in a virtualenv by following the instructions in our documentation 

http://docs.spyder-ide.org/current/installation.html#using-pip

Let us know if it works for you.

**Comment by UxuginPython** [comment]
I've never used virtualenvs before, but I think I did it correctly. In the virtualenv, Spyder starts correctly and the dependency error does not occur. Here are the dependencies in the virtualenv:
```# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.7 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.9 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0          :  1.6.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  62.6.0 (OK)
sphinx >=0.6.6                :  5.3.0 (OK)
spyder_kernels >=2.4.0;<2.5.0 :  2.4.0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.0 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.24.0 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```
It seems very likely that there's no actual issue with Spyder and I just messed it up by accidentally mixing packages.

**Comment by ccordoba12** [comment]
> In the virtualenv, Spyder starts correctly and the dependency error does not occur

Great! Thanks for letting us know about it.

> It seems very likely that there's no actual issue with Spyder and I just messed it up by accidentally mixing packages.

Agreed. Now you need to remember that since virtualenvs are isolated Python environments, you have to install on them any additional package you want to use on Spyder (e.g. Numpy, Pandas or Matplotlib). In other words, you can't use the packages you already have installed on Fedora.

**Comment by ccordoba12** [comment]
I'm going to close this issue since I consider it's solved on our side.
