### ISSUE TITLE
Add folders with subfolders with path manager

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2024]
_From [spacego...@gmail.com](https://code.google.com/u/110291340883920610461/) on 2014-10-26T06:02:34Z_

Spyder Version:  2.3.0rc
Python Version:  2.7.7
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.6 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What is the expected output? What do you see instead?

 In Matlab, user has an option to add folders with subfolders to the search path. Does Spyder has the same functionality?

Thanks!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2024_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T14:53:27Z_

If you add a folder, you don't need to add subfolders to your path. The only thing you need to do is to add an empty __init__.py file to every subfolder. Then you can call modules in your subfolders just using import statements, like this

from folder.subfolder.subsubfolder import myfunction

I really don't know if it's a good for Spyder to add those files in behalf of the user.

Steven, what do you think?

**Cc:** steven.s...@gmail.com  
  **Labels:** MS-v2.4 Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [steven.s...@gmail.com](https://code.google.com/u/118403364018775626054/) on 2014-11-19T04:04:20Z_

I agree with your assessment Carlos.  Adding nested folders to the Python path defeats the purpose of the Python package/subpackage system.

**Comment by goanpeca** [comment]
@ccordoba12, closing?

**Comment by ccordoba12** [comment]
Yep :-)
