### ISSUE TITLE
Consider a different icon for "no matches" in Find/Replace

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#20255]
As a followup to PR #20049 , we might want to consider a different icon for "no matches" in the find/replace widget, and perhaps shift the "Bad Expression" icon to match. 

Currently, they use the following (per @ccordoba12 ):

**Warning**
![warning icon](https://user-images.githubusercontent.com/365293/201726370-02fd59e6-dcbf-4236-abad-632078b7e8bc.png)

**Error**
![error icon](https://user-images.githubusercontent.com/365293/201726561-5c51cb95-9762-452b-a75d-c803ce30895c.png)

This matches the icons used for warnings and errors in the Editor linting panel and Code Analysis pane, etc., treating no matches as a warning, and a regex syntax error as an error.

However, we might want to reconsider, as at least to me, the "warning" icon, :warning: i.e. "alert", to me implies there's something wrong with the expression I typed, whereas a red circled :x: is actually closer, if anything, to the symbology I'd expect if no matches were found, with the red X meaning "no" or "none".

No matches being found doesn't necessarily implied something was wrong with what the user typed, it instead might be either a positive or negative outcome for users. Quite often, I use it to check for uses of things I'm changing, have deprecated or I otherwise want to make sure don't exist in a certain file. Or, things I'm just not entirely sure whether they are in there or not, and just want to check.

Instead, to send a clearer and less ambiguous message, as well as avoid any confusion with the usage elsewhere with the "warning" and "error" semantics that this doesn't directly parallel (at least with "warning"), I'd suggest choosing a different icon to indicate "no match", such as a ~~yellow~~ orange or strong grey :no_entry: symbol, i.e. the Material Design icon "Do not disturb", or perhaps the :no_entry_sign: ("Block") icon, which carries more of the implication of nothing being found as opposed to being a warning/problem with the user's entry, as the parallel to the warning symbol elsewhere could imply.

![image](https://user-images.githubusercontent.com/17051931/209415114-58e69e7b-b398-4d25-8c0d-d1d0048c24a4.png)

**Comment by ccordoba12** [comment]
> I'd suggest choosing a different icon to indicate "no match", such as a yellow or strong grey :no_entry: symbol, i.e. the Material Design icon "Do not disturb", or perhaps the :no_entry_sign: ("Block") icon

I agree with using the first icon but I'm not so sure about the color. I mean, a grey color could imply a "disabled" state, which is not what we want to convey. And we don't use yellows in [our palette](py). We have oranges, greens and blues. So, perhaps we should use an orange?

**Comment by CAM-Gerlach** [comment]
Oh, yeah orange works—I was just thinking of yellow since that's the normal color of the :warning: icon.
