### ISSUE TITLE
py3compat.py problem 

### ISSUE THREAD

**Issue by hilalkaa** [spyder-ide/spyder#20267]
## Problem Description
1) When I try to run maze.py (I attached) I receive the following error :  File "/Users/hilalkatirci/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)
2) I also receive the same error when I try to run the following script:
#importing module
import stemgraphic
data=[3.3, 4.8, 8.2, 3.5, 10.2,
5.6,	5.3,	7.2, 4.1, 7.1, 
4.5,	7.1,	3.1,	6.4,	5.3,
4.4,	6.1,	3.9,	6.5,	6.1,
7.6,	5.8,	4.5,	4.2,	4.5,
4.3,	5.2, 5.4,	6.4,	8.7] 

#calling stem_graphic with required pa
#data and scale

stemgraphic.stem_graphic(data,scale=10)

### What steps reproduce the problem?

1. running the script
2. 
3. 

PASTE TRACEBACK HERE

``` Traceback (most recent call last):

1)  File "/Users/hilalkatirci/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/Users/hilalkatirci/Desktop/AI/src0/maze.py", line 220, in <module>
    sys.exit("Usage: python maze.py maze.txt")
SystemExit: Usage: python maze.py maze.txt

2)Traceback (most recent call last):

  File "/Users/hilalkatirci/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "/Users/hilalkatirci/Desktop/AI/src0/stem.py", line 10, in <module>
    import stemgraphic

ModuleNotFoundError: No module named 'stemgraphic'

## Versions


* Spyder version: 5.3.3
* Python version: Python 3.9.12 64-bit
* PyQt version: PyQt5 5.15.7
* Operating System name/version: MacOS 13.1

### Dependencies
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)

[maze.pdf](https://github.com/spyder-ide/spyder/files/10306961/maze.pdf)

@dalthviz Thanks!

**Comment by stonebig** [comment]
the error message specifies "No module named 'stemgraphic'"... maybe try "pip import stemgraphic" ?

**Comment by ccordoba12** [comment]
Hey @hilalkaa, thanks for reporting. I agree with what @stonebig said: you need to be sure to have the `stemgraphic` module installed for your code to work.

**Comment by hilalkaa** [comment]
I installed Spyder with Anaconda , should I still use pip install? And also, I get the same error when I try to run maze.py as well, py3compat.py creates problem in many cases, these are just two examples.

**Comment by ccordoba12** [comment]
> I installed Spyder with Anaconda , should I still use pip install?

Yes, you need to install it with pip because it's not available as a conda package.

> And also, I get the same error when I try to run maze.py as well, py3compat.py creates problem in many cases, these are just two examples.

`py3compat.py` has no issues, it just appears in what is called the "stack trace" of the error, i.e. the series of called instructions that end up in an error. Python errors are read from the bottom up, i.e. starting from their last line and then going up. That's why both @stonebig and I noticed that your error has to do with the lack of the `stemgraphic`.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by Kavya1807** [comment]
please help!
when i try to run my ANN-LR.py i geting an error

 File "C:\Users\kavya\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\project\kidney 2\code 3.6\ann-lr.py", line 8, in <module>
    import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

**Comment by Kavya1807** [comment]
even though i installed all required packages @ccordoba12 pls help me

**Comment by ccordoba12** [comment]
@Kavya1807, please check this entry in our documentation:

https://docs.spyder-ide.org/5/faq.html#using-packages-installer

You should be able to solve your problem after reading it.

**Comment by Kavya1807** [comment]
Ok sir i check it out...

**Comment by ccordoba12** [comment]
Your error shows that you're still using the Python interpreter from our Windows application. So, it seems you haven't followed our documentation correctly.

**Comment by Kavya1807** [comment]
@ccordoba12  sir whether i have to upgrade python interpreter?

**Comment by ccordoba12** [comment]
It's not possible to update or change the Python interpreter that comes with our Windows application. However, you can use any Python version you want (as long as it's equal or greater than 3.7) in your external interpreter.

**Comment by Kavya1807** [comment]
@ccordoba12  Sir, what is the solution? How can I get rid of the error?

**Comment by Kavya1807** [comment]
@stonebig sir I checked documentation not able to solve sir
