### ISSUE TITLE
Conda is not recognised as an internal command

### ISSUE THREAD

**Issue by Vinodhini12** [spyder-ide/spyder#20283]
I was trying to install mysql-connector-python package through my anaconda prompt but i ended up getting error as:

'"C:\users\admin\anaconda\anaco\condabin\...scripts\conda.exe"'is not recognised as an internal or external command, operable program or batch file
![WhatsApp Image 2022-12-31 at 12 44 44](https://user-images.githubusercontent.com/69148519/210128746-c4cc6146-37dd-49d6-9a6e-dc9518da0a5d.jpeg)

**Comment by ccordoba12** [comment]
Hey @Vinodhini12, thanks for reporting. It seems that, unfortunately, your Anaconda installation is broken now and you need to reinstall it. Please follow the instructions in the second part of [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to do that the right way.

Besides that, there's no more we can do to help you, sorry.
