### ISSUE TITLE
Wrong Line Numbers Show

### ISSUE THREAD

**Issue by Aegis1863** [spyder-ide/spyder#20308]
I found some wrong display of line numbers, one number sandwiched between other numbers.
I used different DPI scaling and different language version and had the same problem.

windows 11
spyder version: 5.4.1 (from anaconda)
Python version: 3.9.15

![image](https://user-images.githubusercontent.com/46989391/210711424-a43c06cc-137f-4c7f-b12c-06dcef4dedbc.png)
![image](https://user-images.githubusercontent.com/46989391/210712516-3419ca66-7cc1-4e04-a8c1-4c4f0835c04a.png)

**Comment by ccordoba12** [comment]
Hey @Aegis1863, thanks for reporting. This problem is usually caused by the font you're using in the editor.

Please select a different font (e.g. Consolas if you're on Windows) and try again.

**Comment by Aegis1863** [comment]
@ccordoba12 

Thanks for your suggestion, yes I am using win11, but I tried to change to Consolas or other fonts and restart spyder, the problem still exists like picture below, maybe I should reinstall spyder, or wait for the next update.

![image](https://user-images.githubusercontent.com/46989391/210945857-bbf4eff8-5440-408f-b295-948067380081.png)

**Comment by ccordoba12** [comment]
Ok, then maybe this is an issue with fractional scaling, either on Windows or in Spyder.

What DPI scaling are you using on both Windows and Spyder?

**Comment by Aegis1863** [comment]
15.6 inches screen, 
2560×1440 resolution, 
DPI is about 188
1.5 DPI scaling in windows and 1.1 scaling in spyder

**Comment by ccordoba12** [comment]
Ok, then please try to

* Match the scaling used in both Windows and Spyder.
* If that doesn't work, use an integer value for the scaling in Spyder (e.g. 2 or 3, etc).

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by zhu-jz** [comment]
The problem is from spyder 5.3.0.

The reason is that there are lines with non English characters (e.g. Chinese characters)

It can be reproduced by pasting the following codes into the editor:

`
# -*- coding: utf-8 -*-

# chinese comments
# 中文注释0
# 中文注释1
# 中文注释2

import os

os.getcwd()`

![image](https://user-images.githubusercontent.com/5400130/215045644-7311f388-b04c-4bf7-ba80-4cf5223e50cb.png)

**Comment by ccordoba12** [comment]
@zhu-jz, I can't reproduce this problem with the code you provided. Please use a different in the editor and try again.

**Comment by Aegis1863** [comment]
The problem has been resolved by reinstalling anaconda

**Comment by TBSenseo** [comment]
I have a very long source code (I am unlikely allowed to share it), where the source code lines keep counting upwards even so the line is wrapped over. The displayed line numbers also end prematurely. When placing the cursor into any line after the wrapping, it shows a different line number than the line number displayed before:
![image](https://user-images.githubusercontent.com/50355793/231104461-9f154a5c-596a-4a9e-acfa-4e7b1b6c3b52.png)
Is there a defect in the skipping of the lines following wrap overs for the line numbers display component?
