### ISSUE TITLE
Clear Profiler command [Feature request]

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#20323]
I've got a `times` plot, where

```python
times = []
for i in range(800):
    t0 = timeit.default_timer()
    func()
    times.append(timeit.default_timer() - t0)
```
that looks like

<img src="https://user-images.githubusercontent.com/16495490/211159370-7223fa2f-96ae-479e-a01a-063e94a25fed.png" width="400">

so I would like to gather data only over the higher region. I could terminate at `i=600` to fix fast execution there, but not before `i=300`. Something like `spyder.profiler.clear_data()` would work. Or any other suggestion? (and yes I'm not using `timeit` with Spyder profiler, only one or the other)

**Comment by OverLordGoldDragon** [comment]
I'll add that this is low-priority and I've so far always found a workaround, just an idea if it can be implemented easily.

**Comment by dalthviz** [comment]
Hi @OverLordGoldDragon I'm not totally sure to follow what you are trying to achieve but, what is the workaround you have found?

**Comment by OverLordGoldDragon** [comment]
I'm saying that in a code like this

```python
for i in range(1000):
   do_stuff()
```

`do_stuff()` will run for much longer for certain `i` than others. My "workaround" is just to make it so that `do_stuff()` no longer behaves this way. I don't know if there's actually any legitimate `do_stuff()` that behaves that way, so this may be totally a non-issue, feel free to close.

**Comment by OverLordGoldDragon** [comment]
Seems like a non-issue at this point, but feel free to reopen.
