### ISSUE TITLE
Context menu edit opens new instance in standalone Spyder

### ISSUE THREAD

**Issue by thangleiter** [spyder-ide/spyder#20328]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
With the standalone installer, using the context menu in Windows 11 to open a file in Spyder opens a new instance instead of opening a new tab in the editor of an existing instance.

### What steps reproduce the problem?

1. 'Edit in Spyder' in explorer

### What is the expected output? What do you see instead?
Expected: file opening in already open instance.
Instead: New instance opens.

## Versions

* Spyder version: 5.4.1
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Spyder thinks Windows 10, but actually Windows 11 22H2

**Comment by ccordoba12** [comment]
Hey @thangleiter, thanks for reporting. Could you open Spyder, then the Windows task manager and let us what's the command shown there that it's associated to the Spyder process?

That will help us to see if we're still checking for the right command when detecting if there's a previous Spyder instance running in the system.

**Comment by ccordoba12** [comment]
Pinging @dalthviz about this one again.

**Comment by dalthviz** [comment]
I was able to reproduce this :+1:

**Comment by ccordoba12** [comment]
Ok, thanks @dalthviz! I think the problem is in the `is_spyder_process` function, present in the `utils/programs.py` module. Perhaps the problem is that `psutil` changed the way it returns command line arguments.

**Comment by dalthviz** [comment]
Just in case, I was unable to reproduce this after installing Spyder 5.4.2 and removing the `SPYDER_DEV` env var from my current user. Checking, I had the `SPYDER_DEV` env var set as `True` as on of my Windows user env variables (not totally sure from where that env var got set in the first place since I think is only set when running from `bootstrap.py` and that should not be permanently set, right? 🤔 )

**Comment by thangleiter** [comment]
> Just in case, I was unable to reproduce this after installing Spyder 5.4.2 and removing the `SPYDER_DEV` env var from my current user. Checking, I had the `SPYDER_DEV` env var set as `True` as on of my Windows user env variables (not totally sure from where that env var got set in the first place since I think is only set when running from `bootstrap.py` and that should not be permanently set, right? 🤔 )

For completeness, I have no such environment variable and I have been able to reproduce this on different systems with different Windows versions.

**Comment by ccordoba12** [comment]
Thanks for the extra information @thangleiter. We'll try to reproduce this problem in other systems then.

**Comment by dalthviz** [comment]
Note: I'm still unable to reproduce this :/ Tried with Spyder 5.4.3 but the context menu option opens files in the already running instance for me

**Comment by thangleiter** [comment]
Hi @dalthviz, prompted by your comment I also tried it again, and it works! Spyder 5.4.3 just for completeness, but more likely the reason is that since the beginning of this year, I reinstalled Windows ;)

I'll try to give it another go on other systems that I didn't reset, but will close for now :)

**Comment by thangleiter** [comment]
For completeness, on my other Windows system it's still an issue (also 5.4.3). I also don't have an `SPYDER_DEV` environment variable there. But since it seems like it's not an issue for a clean install (hopefully a clean `conda` would be enough, but I don't want to go through that right now ;)), I don't think it's worth spending more of your time on.
