### ISSUE TITLE
Fix on dot completion leads to dot replacement

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#20331]
on this 2023-01-08 early morning master of 5.X  https://github.com/spyder-ide/spyder/commit/da661ccfe2f0355459f4e18f87d22337e4cd36dc

the dot completion works again, but if we validate a choice, the dot is replaced also, if we don't type a first letter of the world choosen

![GIF_dot_completion_20230108](https://user-images.githubusercontent.com/4312421/211188586-740ab7f2-c9ff-4016-89bf-3feb5a264c4e.gif)

**Comment by ccordoba12** [comment]
Good catch @stonebig! Thanks a lot for testing my fix on PR #20298.

I just checked that dot completions were working again, not that selecting one of them introduced the right text. I'll fix this right away.

**Comment by stonebig** [comment]
spend hour on trying to find where to fix... but truly couldn't.

**Comment by juliangilbey** [comment]
Hi @ccordoba12! This probably isn't quite the right place to ask this, but if you're going to release 5.4.2 to fix this, which depends on an as-yet-unreleased version of python-lsp-server (handling the newer pydocstyle), please could you release that first and update the spyder dependencies?

**Comment by ccordoba12** [comment]
Yep, that's the plan.
