### ISSUE TITLE
Spyder GUI window disappears when changing monitors

### ISSUE THREAD

**Issue by jmoraispk** [spyder-ide/spyder#20344]
## Problem Description

When I closed spyder using one monitor that was virtually above my main screen and then connected a different monitor that was virtually at the left of my main screen, I noticed the spyder window going to some place above my main monitor, and this makes the spyder window impossible to see or reach.

_Resetting Spyder with "spyder --reset" works_, but that command seems an overkill it also deletes a bunch of other useful configurations, like the configured shortcuts.

Possibly related issues: #1672 

### What steps reproduce the problem?

The problem seems related with changing screens:

1. Connect your machine (say laptop) to a monitor and setup that screen (in software) to be above your main screen such that when your mouse moves past the top edge of your main screen, it enters that screen.
2. Open spyder. Move window to new screen. Close spyder.
3. Setup the screen again (in software again) to be on the left (or right, or bottom) of your main screen.
4. Open Spyder again.

### What is the expected output? What do you see instead?

I'd expect Spyder to open in one of the available screen. Instead, Spyder tries to open on the screen that was previously above our main screen and cannot be seen.

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.10.8 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

**Comment by ccordoba12** [comment]
Hey @jmoraispk, thanks for reporting. This is a serious issue indeed, so we'll try to solve it in our 5.4.3 version, to be released at the beginning of March.

@dalthviz, what do you think we could do about this? How could we detect if the region where Spyder was placed before disconnecting a previous monitor is actually visible?

**Comment by dalthviz** [comment]
I'm not totally sure what we could do about this or the correct approach for this, maybe we could try to detect the virtual screen geometry changing as ypu say but I don't know if corner cases will appear where such detection is unreliable (like with the HDPI screens issues). Also, maybe as a workaround for this, using the `Win + Arrow Keys` shortcuts that you can use to position windows could be useful to see again the Spyder application window.

**Comment by ccordoba12** [comment]
Note: After a bit of thought, I think we could use [`QGuiApplication.screenAt`](https://doc.qt.io/qt-5/qguiapplication.html#screenAt) to detect if Spyder is placed in a visible screen and move it to the primary one if that's not the case.

However, that requires bumping our Qt/PyQt versions, so I think it's better to leave this for Spyder 6.

**Comment by jmoraispk** [comment]
> I'm not totally sure what we could do about this or the correct approach for this, maybe we could try to detect the virtual screen geometry changing as you say but I don't know if corner cases will appear where such detection is unreliable (like with the HDPI screens issues). Also, maybe as a workaround for this, using the `Win + Arrow Keys` shortcuts that you can use to position windows could be useful to see again the Spyder application window.

Hey @dalthviz , I tried this and it didn't work. I guess Windows doesn't have a contingency for this behavior, and the win + arrows is just moving spyder window in that invisible screen, I assume. If there is a shortcut to bring the window to the main screen, that would likely work as a workaround, yes.

**Comment by dalthviz** [comment]
Thank you for the info @jmoraispk ! After trying a little bit I was able to reproduce this and seems like a way to workaround the problem is to use the snap window feature. So try to drag and drop any other window application you have available to take for example half of the window space and then Windows will let you choose any other window application to set it to use the other half of the screen. If you then select the Spyder application window (which appears as a blank screen) it will show up. That Windows feature looks something like this:

![snap](https://user-images.githubusercontent.com/16781833/214381384-fba7bad3-8cc9-4a08-97f6-5a949b895a2f.png)

After selecting the Spyder application window:

![snap2](https://user-images.githubusercontent.com/16781833/214381841-b7105add-1fb2-4944-94df-70a9007a2314.png)

**Comment by erwanp** [comment]
Thanks @dalthviz
