### ISSUE TITLE
Add missing methods (or functions) to the outline in a different color (red). 

### ISSUE THREAD

**Issue by nadapez** [spyder-ide/spyder#20349]
(Feature request)

When clicking in the missing method in the outline, add corresponding boiler plate code and jump to that place in the editor. (Like red links in wikipedia)

That way looking at the outline you can tell what methods must be yet implemented and also you can create the boiler plate for that.

More in depth:

Sometimes I like to write the high level methods of a class, that methods relaying in other methods which I didn't write yet. That way I can have the big picture in mind and I don't rely on other designing tools like UML or whatever. My code functions itself in a way as my guide.

But after writing the high level methods and looking for the missing ones, is not so strait to do it from the code. It would be nice to see them all in one place, and also an easy access to writing the implementations.

**Comment by dalthviz** [comment]
Hi @nadapez thank you for the feedback! Not totally sure if I'm getting your idea right but seems like the `Show special comments` option from the Outline pane could be useful? Basically if you add a comment starting like `# ----` it will show up in the Outline pane. As an example, the following code:

```python
def test_1():
    # ---- TODO: test_1
    pass

def test_2():
    # ---- TODO: test_2
    pass
```

Looks something like this:

![image](https://user-images.githubusercontent.com/16781833/214453861-79ced8d2-6613-417a-8f11-2742139ecc9e.png)

When having the `Show special comments` toggled and you click the `Expand all` button and you can select the entry to put the cursor at that position.

For more info about the Outline pane options you can check: https://docs.spyder-ide.org/current/panes/outline.html

For the boilerplate part, maybe using the code snippets config could be useful? You can setup custom ones in the preferences:

![image](https://user-images.githubusercontent.com/16781833/214454701-06f80ac3-0f61-4042-8bb9-f9ffa59a6df7.png)

For more info on that you can check: https://docs.spyder-ide.org/current/panes/editor.html?highlight=code%20snippets#code-completion.


Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
