### ISSUE TITLE
Error on opening Spyder

### ISSUE THREAD

**Issue by jhmorse** [spyder-ide/spyder#20356]
### What steps will reproduce the problem?

Had Anaconda and Spyder installed, was prompted to upgrade.
Uninstalled Spyder from inside Anaconda portal. Prompted to upgrade Anaconda. Upgraded. Installed Spyder from new portal. Launched Spyder. Error occurred.

### Traceback
```python-traceback
Error on reading from the event loop self pipe
loop: <ProactorEventLoop running=True closed=False debug=False>
Traceback (most recent call last):
  File "C:\Users\jomors\Anaconda3\lib\asyncio\windows_events.py", line 453, in finish_recv
    return ov.getresult()
OSError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jomors\Anaconda3\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "C:\Users\jomors\Anaconda3\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\jomors\Anaconda3\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
```

## Versions

* Spyder version: 5.3.3  (conda)
* Python version: 3.8.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @jhmorse, thanks for reporting. To fix this error you need to close Spyder, open the Anaconda prompt and run there

    conda update python

then start Spyder again.

That should do the trick, but let us know if it works for you.

**Comment by jhmorse** [comment]
Hi Carlos,

 

Thank you for responding so quickly! I was afraid this would go into some black hole, so I am sincerely appreciative of the response.

 

I ended up uninstalling Spyder through the Anaconda portal, then uninstalled Anaconda from the Windows control panel. Then after a fresh install of Anaconda and Spyder, the only issue I had was Spyder was not pointing to my Python install but had direction for fixing it:

 



 

I ran the pip install, and that seemed to resolve it! 

 

I believe what happened here is I had previously installed Anaconda/Spyder, then subsequently installed Python 3.9 and 3.10. I was not using Spyder after those installs, so never ran into the issue (I was using R-Studio). I am starting a college course, though, and will be using Spyder lots over the next 3 months. Providing this for general information as to potential issues for future users. Hoping all is resolved for me now.

 

Thank you!

John

**Comment by ccordoba12** [comment]
Hey @jhmorse, I'm glad you were able to solve your problem. We generally recommend using Anaconda, but it's fine if you use pip too.

The problem in this case was with a specific version of Python 3.8. That's you didn't it see it with 3.9 or 3.10.

**Comment by jhmorse** [comment]
Hi,

 

I know you’ve closed this, but hoping this is an easy question. I have python 3.9 and 3.10 installed. I seem to have Spyder pointing at python 3.10, but apparently that is not a conda environment. 

*	Running Powershell prompt form Anaconda portal, and typing python gives me 3.9.13
*	Opening Windows PowerShell direct from Windows and typing python returns 3.10.4
*	I also see Python 3.10.4 at the top of the console window in Spyder
*	I can not run “conda” from inside the console window or powershell, and receive a message that it is not a conda environment

 

How do I make python 3.10 a conda environment?

 

Thank you,

John
