### ISSUE TITLE
Code analysis and tooltips are not displayed in Ubuntu

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2036]
_From [abmsch...@gmail.com](https://code.google.com/u/108879214943523030834/) on 2014-11-02T08:18:58Z_

Spyder Version:  2.3.1
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
IPython >=0.13  :  2.3.0 (OK)
matplotlib >=1.0:  1.4.2 (OK)
pandas >=0.13.1 :  0.15.0 (OK)
pep8 >=0.6      :  1.5.7 (OK)
psutil >=0.3    :  None (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  1.6 (OK)
pylint >=0.25   :  1.3.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.0   :  0.7.5 (OK) 

What steps will reproduce the problem?

 As I start spyder, the problem is already there. I found no fix. 

What is the expected output? What do you see instead?

 Attached is a screen shot of this phenomena: when hovering the mouse pointer over the GUI buttons or the Code Analysis alert symbols, the text box is correctly displayed but text is somehow not rendered...

Best regards,
Scheer

![2014-11-02_spyder-error](https://cloud.githubusercontent.com/assets/365293/6653877/3149baae-ca70-11e4-8897-ed2169961f06.png)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2036_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T14:44:10Z_

What's your Ubuntu version?

**Labels:** Cat-SpyderGUI MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-01T06:56:14Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
I don't know what that theme is. I only can confirm that using the default Ubuntu themes (Ambiance and Radiance), this is not a problem.

**Comment by goanpeca** [comment]
I am having the same problem! and it appeared suddenly

**Comment by goanpeca** [comment]
Ok, so I made some testing.

On ubuntu I installed a new conda environment for python 3.4, installed pyqt and then executed spyder from latest master in bootstrap mode:

# Case 1: Previous version of pyqt

```bash
conda create -n py3 python=3.4 pyqt=4.10.4
source activate py3
python bootstrap.py
```
**Toolstips seem to work fine**

### Version and main components
* Spyder Version:  3.0.0dev 80b1c8b
* Python Version:  3.4.3
* Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.4 on Linux

### Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  None (NOK)
IPython >=3.0   :  None (NOK)
zmq >=13.0.0    :  None (NOK)
pandas >=0.13.1 :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
psutil >=0.3    :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  None (NOK)
pylint >=0.25   :  None (NOK)

# Case 2: Latest version of pyqt
```bash
conda create -n py3 python=3.4 pyqt=4.11.3
source activate py3
python bootstrap.py
```

**Tooltips are not working...** :cry: 

### Version and main components

* Spyder Version:  3.0.0dev 80b1c8b
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

### Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  None (NOK)
IPython >=3.0   :  None (NOK)
zmq >=13.0.0    :  None (NOK)
pandas >=0.13.1 :  None (NOK)
sphinx >=0.6.6  :  None (NOK)
psutil >=0.3    :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  None (NOK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
I don't how the Unity shell fixes tooltips background color. I mean, in the default installation and without changing a single thing, tooltips are dark brown, and in that case Spyder text on them is white.

But people that report this problem (like yourself :-) show screentshots where that color is light yellow. I see that (besides changing the stock theme), you seem to be using a different wallpaper. What happens when you revert to the default wallpaper?

Finally, given that you're able to reproduce this bug, please try to solve it ;-)

**Comment by goanpeca** [comment]
I will have a look... but so far I was working on Py3 to avoid it :smile_cat:

**Comment by ccordoba12** [comment]
Just for the record, the only solution right now is to use the `Gtk` Qt theme. Any other theme shows this problem.

**Comment by ftpronk** [comment]
I get the same issue in OpenSUSE 13.2 running KDE, so I doubt it's an Ubuntu/Unity issue.

What about changing the QToolTip colours?  Or make them configurable?
http://doc.qt.io/qt-4.8/qtooltip.html#details

**Comment by ccordoba12** [comment]
@ftpronk, what's your KDE version?

**Comment by ftpronk** [comment]
Hi there!
My KDE version is 4.14.2.
F.

**Comment by ccordoba12** [comment]
Please select a different Qt theme to see if that helps. You can change your theme in

    Tools > Preferences > General

**Comment by ftpronk** [comment]
Everything but the GTK+ theme gives me a yellow tooltip background, making the white information text unreadable.  As for the GTK+ theme, as the background colour is blue, the text comes out fine.

**Comment by goanpeca** [comment]
@ccordoba12 I think we need to define a QStyleSheet that loads specifically for ubuntu to handle the tooltips and updates on style change (I think I know how to fix this now)

**Comment by ccordoba12** [comment]
@goanpeca, if you want to but the current fix works just fine.

**Comment by goanpeca** [comment]
ok :+1:

**Comment by goanpeca** [comment]
What is the current fix?

**Comment by ccordoba12** [comment]
Set Gtk as the default theme and don't allow to change it in Ubuntu and all other Gtk-based Linux desktops (like XFCE).

**Comment by goanpeca** [comment]
That does not seem like a fix at all!

**Comment by ccordoba12** [comment]
My excuses: :-p

1. The other themes are not that different from the Gtk one.
2. I didn't have time to solve this the right way.
3. Not having tooltips is a big issue for our users.

So I took that shortcut.

**Comment by goanpeca** [comment]
That is why I said I think I know how to fix it for good ;-)

**Comment by btekgit** [comment]
Please note the reason that the code analysis window is not readable is because display in a yellow background with white fonts. May be some  knows in which file the color configurations for windows styles are.

**Comment by bubaelperro** [comment]
Have the same issue in Fedora 23
My Qt windows style is GTK+
spyder 2.3.9 with python 2.7

With anaconda distribution on python 3.5 it works fine
