### ISSUE TITLE
Cannot connect to remote (docker) kernel using SSH

### ISSUE THREAD

**Issue by degel123** [spyder-ide/spyder#20377]

**Comment by ccordoba12** [comment]
I guess you figured it out that you need to match the Spyder and Spyder-kernels versions for a successful connection to take place. But just in case, I wanted to let you know that.

**Comment by dhamelse** [comment]
> I guess you figured it out that you need to match the Spyder and Spyder-kernels versions for a successful connection to take place. But just in case, I wanted to let you know that.

HI, I'm also trying to use Spyder in a Docker container. When you say "match the Spyder and Spyder-kernels versions", do you mean all four packages (2 on remote, 2 on local) need to be the same version? Or is there a specific pair?
