### ISSUE TITLE
Response in the console is very slow

### ISSUE THREAD

**Issue by gustafp68** [spyder-ide/spyder#20379]
Spyder IDE 5.1.5
Python 3.9.12 64-bit | Qt 5.9.7 | PyQt5 5.9.2 | Windows 10 
Installation is made through the company installation portal, where spyder is part of the Anaconda 3, v2.1.14 (64 bit) package.
Further comments to issue #20362:
I have now tried to execute the same in the jupyterLab console and notebook, and there everything runs fast there. 1+1 in the Spyder console took 5 seconds, while in the jupyterLab environment it was "instantaneous". The jupyterLab was installed together with Spyder when installing the Anaconda 3 package.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

Please post to this issue if the problem persists with our 5.3.3 version. Also, this could be caused by your antivirus, firewall or VPN, so please disable them and try again.
