### ISSUE TITLE
Is it possible to DEBUG the code from remote kernel in Spyder?

### ISSUE THREAD

**Issue by degel123** [spyder-ide/spyder#20385]
Hi, I manage to connect to remote kernel (inside Docker Container) using SSH. Is it possible to debug this code too? I could have an  exact copy of Python code on my local machine but I don't know how to set it up :( Did you try this?

**Comment by ccordoba12** [comment]
Yes, it is possible. You don't need your code to be somewhere in the remote machine, but you need to install all the libraries it depends on it it.

Let us know if you can make it work.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
