### ISSUE TITLE
`\r` doesn't overwrite print()

### ISSUE THREAD

**Issue by mahmoodn** [spyder-ide/spyder#20388]
Hi
It seems that the `\r` for overwriting the print line doesn't work in the IPython console.

```
In [18]: import time
    ...: for i in range(100):
    ...:     if i % 10 == 0:
    ...:         print(i, end='\r')
    ...:         time.sleep(1)
    ...:     i += 1
    ...: print()
0102030405060708090
```
However, the same code works fine in bash terminal.
System information is:

Spyder IDE 5.3.2
Python 3.10.6 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Linux 5.15.0-58-generic

**Comment by ccordoba12** [comment]
Hey @mahmoodn, thanks for reporting. Unfortunately, our IPython console doesn't support many ANSI escape codes, which is the cause of this problem.

This is a [known issue](https://github.com/jupyter/qtconsole/issues/350) and we'll try to fix it in the future.
