### ISSUE TITLE
Pressing `Tab` key for code completion repeats previous text with IPython 8.8+

### ISSUE THREAD

**Issue by physici** [spyder-ide/spyder#20393]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [?] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When using TAB in the IPython console, auto completion repeats the previously entered characters. E.g. in case a variable should be assigned the result of a function call then autocomplete repeats the variable and the equals-sign before inserting the result of the autocomplete.

### What steps reproduce the problem?

1. import any module, e.g. pandas as pd
2. enter "test = pd.con"
3. press TAB for completion (pd.concat)
4. completion will return "test = pd.concat" resulting in the line "test = test = pd.concat"

![2023-01-18_07-45-52](https://user-images.githubusercontent.com/15417017/213104251-cb857abb-12cd-4f61-b765-5c1907c0a827.gif)

### What is the expected output? What do you see instead?

The completed line should read "test = pd.concat", not "test = test = pd.concat"

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.1
* Python version: 3.10.9
* IPython version: 8.8.0
* Qt version: 
* PyQt version: 
* Operating System name/version: Win10 22H2

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @physici, thanks for reporting. Did you change any option in

    Preferences > IPython console > Advanced settings

from its default values?

Also, what's your IPython version? You didn't attach it to your report above.

**Comment by physici** [comment]
I've updated the bug report: IPython version 8.8.0.

I've also tried it with a different setup. The problem doesn't show up with the following configuration:
Python 3.10.6
Spyder 5.4.0
IPython 7.3.4

Advanced Settings for the IPython-Console:
Jedi -> off
Greedy -> off
Autocall -> off
Symbolic math -> off
Prompts: empty
Window adjustments -> On

**Comment by ccordoba12** [comment]
Note: This probably needs to be solved in Qtconsole.

**Comment by physici** [comment]
I've downgraded to IPython 8.7.0 as suggested and it solves the issue for me as well.

**Comment by juliangilbey** [comment]
Unfortunately, the Spyder 5.4.2 macOS version on GitHub has IPython 8.8.0 bundled with it, so exhibits this bug.

**Comment by stymbhrdwj** [comment]
I am still experiencing this bug with IPython 8.10.0 as well

**Comment by ccordoba12** [comment]
Hi @krassowski, sorry for the ping but I saw you are involved in many completion PRs on IPython lately. So, I'd like to ask you: is this something we need to address in Qtconsole? Or is it going to be fixed in a future release in IPython?

**Comment by krassowski** [comment]
Happy you pinged me. The fix was already merged: https://github.com/ipython/ipython/pull/13943
