### ISSUE TITLE
Small inconsistency in license file

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#20417]
A minor matter.

The `README.md` file says:
```
*Copyright © 2009–2023 [Spyder Project Contributors](
https://github.com/spyder-ide/spyder/graphs/contributors)*

*Some source files and icons may be under other authorship/licenses; see
[NOTICE.txt](https://github.com/spyder-ide/spyder/blob/master/NOTICE.txt).*
```
but the `LICENSE.md` file says:
```
Copyright (c) 2009- Spyder Project Contributors and others (see AUTHORS.txt); the spyder/images dir and some source files under other terms (see NOTICE.txt)
```
It would be good if they said exactly the same thing as each other!

Though the `AUTHORS.txt` file hasn't been updated in about 4 years, it still seems up-to-date.  The only information contained in it that does not also appear in `LICENSE.md` is:
* The original Spyder author (Pierre) and the current maintainer (Carlos)
* The reference to the contributors on GitHub.

**Comment by ccordoba12** [comment]
Thanks for reporting @juliangilbey. We'll drop the last copyright year in our Readme because it's the simplest thing to do.
