### ISSUE TITLE
Variable Explorer View Not on Top of Main Window on Linux

### ISSUE THREAD

**Issue by PhilipYip1988** [spyder-ide/spyder#20414]
### Variable Explorer View Not on Top of Main Window on Linux

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Variable Explorer View Not on Top of Main Window on Linux. It is impossible to view a variable and type in the script editor with Spyder maximised on Linux.

### What steps reproduce the problem?

1.  Create a variable a = [1, 2, 3]
2.  Open it in the Variable Explorer
3.  Click on the Script Editor
4.  Spyder MainWindow is now on top of the Variable View
6. Unlike a MatPlotLib Figure, the Variable View has no icon on the Gnome Panel so can't be seen again without minimising Spyder

### What is the expected output? What do you see instead?

On Windows the Variable View is always on top of the main Window.

Variable View is shown:

![img1](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202023-01-21%2010-05-25.png)

Script Editor is clicked, obscuring the Variable View on Linux:

![img2](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202023-01-21%2010-05-32.png)

It is not possible to view the Variable View and type in code using the full screen like it is on Windows:

![img3](https://raw.githubusercontent.com/PhilipYip1988/bugsubmissions/main/Screenshot%20from%202023-01-21%2010-05-55.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.2
* Python version: 3.11.0
* Qt version: 5.15.6
* PyQt version: 5.15.7
* Operating System name/version: Linux 6.1.6-200-fc37.x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.7.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.7 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.9 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  6.0.0 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.24.1 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @PhilipYip1988, thanks for reporting. Unfortunately, this is not something we can control in Spyder because it's handled by your [window manager](https://en.wikipedia.org/wiki/Window_manager?oldformat=true). On Windows I guess the manager always places the Variable Explorer viewers on top of the main window, but on Linux that's not the case.

So, you have to get used to the way Linux works in this regard because there's nothing we can do to change it.

**Comment by bessman** [comment]
Most desktop environments have an option to keep a certain window on top even when it loses focus. It is usually called something like "Always on top". For example, Ubuntu 20.04 with Gnome 3.30:
![Screenshot from 2023-01-23 10-52-17](https://user-images.githubusercontent.com/1999462/214010941-d6e3018f-170f-48c2-9e1b-338a811bd2d4.png).

**Comment by PhilipYip1988** [comment]
> Most desktop environments have an option to keep a certain window on top even when it loses focus. It is usually called something like "Always on top". For example, Ubuntu 20.04 with Gnome 3.30: ![Screenshot from 2023-01-23 10-52-17](https://user-images.githubusercontent.com/1999462/214010941-d6e3018f-170f-48c2-9e1b-338a811bd2d4.png).

Thanks, I didn't know about that context menu, that does the trick. It works also on Fedora 37 and Ubuntu 23.04.
