### ISSUE TITLE
DLL loading fails in some package imports when using separate conda environment

### ISSUE THREAD

**Issue by pierre-haessig** [spyder-ide/spyder#20433]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports. Related issues are:
    * #15881 (but more focused on the easiness of switching environment in the UI)
    * #18486: perhaps the same issue, but discussion got stalled. Also the discussion gets confused about whether a separate env is used or not. In the present issue, it's about *separate* environment.
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda). → *Was a fresh install*.
* [x] Could not reproduce inside ~jupyter qtconsole~ ipython (in cmd.exe Windows shell).
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/): *the problem appears in a fresh miniforge install*
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm using Spyder under Windows to run Python code from a separate Python/conda environment, based on the Wiki instructions in section [Working with other environments and Python installations](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#working-with-other-environments-and-python-installations). E.g. this involves selecting as a custom interpreter the `python.exe` found in that environment folder.

* Notice that I'm *not* following the recommendation of the Notes section (*“While Spyder should work fine without it, ensuring the Python minor version (3.6, 3.7, 3.8, etc) in Spyder's environment matches that in your working environment, if practicable, will minimize the chance of any issues.”*), because I run Spyder in Python 3.10 and I need lower Python versions for some packages I install.

**The problem**: I'm getting **import errors** when loading *some* packages when using Spyder's IPython console running the dedicated environment. I have two computers which have two different environments (3.7 vs 3.9). Each case yields an error with different packages, but both messages mention apparently similar **DLL loading errors**.

* numpy import error in Python 3.7 console/environment (Matplotlib also affected, but importing openturns is fine):
`ImportError: DLL load failed: Le module spécifié est introuvable.` (or in English `The specified procedure could not be found.`)
* openturns import error in Python 3.9 console/environment (but importing numpy is fine):
`ImportError: DLL load failed while importing _common: La procédure spécifiée est introuvable`

(See full stacktraces below. Also, the stacktrace when importing h5py reported in #18486 looks simular.)

I believe that the issue comes from an **improper activation of the conda environment** by Spyder because:
- all these import works fine when run in a standalone ipython console, after having run `conda activate myenv`
- there are differences in the Windows `PATH`  variable (as observed with the `%env` magic) between standalone IPython versus Spyder's IPython.

Also, conda's doc on [Managing environments/§Activating an environment](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#activating-an-environment) specifically mentions the importance of `PATH`:
> Activation entails two primary functions: adding entries to PATH for the environment and running any activation scripts that the environment may contain. These activation scripts are how packages can set arbitrary environment variables that may be necessary for their operation.  [...]
> If environments are not active, libraries won't be found and there will be lots of errors. HTTP or SSL errors are common errors when the Python in a child environment can't find the necessary OpenSSL library.

### What steps reproduce the problem?

1. Install a fresh miniforge base 3.10 environment on Windows 10
2. Install Spyder in that base environment (conda install, from conda-forge channel)
3. Create a dedicated conda env with Python 3.9 or 3.7. Install numpy, openturns, ipython  [...] + spyder-kernels in that dedicated env
4. Run Spyder from base environment (using the automatically created Windows menu launcher) and set a custom Python interpreter to be the one in the dedicated 3.7/3.9 environement. Restart Spyder (cause just restarting the IPython console lead to another failure, perhaps a separate minor bug).
5. Try `import xxx` for one of the problematic packages, like openturns for Python 3.9 env

### What is the expected output? What do you see instead?

Import should run fine, but gets `ImportError` message indicating with DLL loading problem.

### Traceback/Error Below

Import error with `numpy` in a Python 3.7 environment:

```import numpy
Traceback (most recent call last):

  File "C:\Users\i43680\AppData\Local\miniforge3\envs\3.7-MatlabOT\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray

  File "C:\Users\i43680\AppData\Local\miniforge3\envs\3.7-MatlabOT\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides

  File "C:\Users\i43680\AppData\Local\miniforge3\envs\3.7-MatlabOT\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (

ImportError: DLL load failed: Le module spécifié est introuvable.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\i43680\AppData\Local\Temp\ipykernel_25424\2172125874.py", line 1, in <module>
    import numpy

  File "C:\Users\i43680\AppData\Local\miniforge3\envs\3.7-MatlabOT\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core

  File "C:\Users\i43680\AppData\Local\miniforge3\envs\3.7-MatlabOT\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)

ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\i43680\AppData\Local\miniforge3\envs\3.7-MatlabOT\python.exe"
  * The NumPy version is: "1.21.6"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: Le module spécifié est introuvable.
```

Import error with `openturns` in a Python 3.9 environment:

```import openturns
Traceback (most recent call last):

  Cell In[5], line 1
    import openturns

  File ~\miniforge3\envs\3.9-matlab\lib\site-packages\openturns\__init__.py:49
    from .common import *

  File ~\miniforge3\envs\3.9-matlab\lib\site-packages\openturns\common.py:15
    from . import _common

ImportError: DLL load failed while importing _common: La procédure spécifiée est introuvable.
```

## Versions

Issue was observed with a fresh [miniforge](https://github.com/conda-forge/miniforge/#download) install with:
- Spyder installed in the base Python 3.10 conda environment
- Scientific packages of interests in a dedicated 3.9 (or 3.7 on another machine) conda environment (plus spyder-kernels)

* Spyder version: 5.4.2 (from conda-forge)
* Python version:
    * Python env which runs Spyder: 3.10.8 (base conda env)
    * Python env I'd like to run in the IPython console : 3.9.15 (or 3.7 on another machine)
* Qt version: 5.15.6
* PyQt version: 5.15.7
* Operating System name/version: Windows 10

### Dependencies

All dependencies are fine but all optional dependencies are missing (cython, numpy...):

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<9.0.0       :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.12.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  None (NOK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by pierre-haessig** [comment]
To be more specific about the `PATH` difference (as observed with `%env` IPython magic):

In a standalone IPython after `conda active 3.9-matlab`, PATH is:
`'C:\\Users\\Pierre\\miniforge3\\envs\\3.9-matlab;C:\\Users\\Pierre\\miniforge3\\envs\\3.9-matlab\\Library\\mingw-w64\\bin;C:\\Users\\Pierre\\miniforge3\\envs\\3.9-matlab\\Library\\usr\\bin;C:\\Users\\Pierre\\miniforge3\\envs\\3.9-matlab\\Library\\bin;C:\\Users\\Pierre\\miniforge3\\envs\\3.9-matlab\\Scripts;C:\\Users\\Pierre\\miniforge3\\envs\\3.9-matlab\\bin;C:\\Users\\Pierre\\miniforge3\\condabin;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files\\MATLAB\\R2022a\\bin;C:\\Program Files\\MATLAB\\R2020b\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\TortoiseGit\\bin;C:\\Users\\Pierre\\AppData\\Local\\Microsoft\\WindowsApps;.'`

In Spyder's embedded IPython run from the corresponding interpreter (`C:/Users/Pierre/miniforge3/envs/3.9-matlab/python.exe`), PATH is:
`'C:\\Users\\Pierre\\miniforge3;C:\\Users\\Pierre\\miniforge3\\Library\\mingw-w64\\bin;C:\\Users\\Pierre\\miniforge3\\Library\\usr\\bin;C:\\Users\\Pierre\\miniforge3\\Library\\bin;C:\\Users\\Pierre\\miniforge3\\Scripts;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files\\MATLAB\\R2022a\\bin;C:\\Program Files\\MATLAB\\R2020b\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\TortoiseGit\\bin;C:\\Users\\Pierre\\AppData\\Local\\Microsoft\\WindowsApps'`

In Spyder's embedded IPython, the PATH corresponds to the base environment rather than the dedicated env.

**Comment by pierre-haessig** [comment]
I tried the following workaround which didn't work.

I've created the following `.bat` file which can run python after activating the proper environment (base on SO question https://stackoverflow.com/questions/42602024/windows-shortcut-to-run-python-script-in-anaconda-command-prompt).

```
echo off

CALL  %userprofile%\miniforge3\Scripts\activate.bat 3.9-matlab
python

echo on 
```

However, in Spyder preferences, the file dialog to select a custom Python interpreter specifically wants a `.exe` file.

Also, even if Spyder had accepted a `.bat` as the interpreter, the above script may still not work because it seems just capable of launching an interactive python console, but cannot pass arguments to run for example a Python scripts (e.g. to launch IPython).

**Comment by ccordoba12** [comment]
Hey @pierre-haessig, thanks for reporting. You said

> Run Spyder from base environment (using the automatically created Windows menu launcher)

I think this problem happens because when Spyder is launched in this way, it can't find the `conda` executable to activate our IPython consoles because it's not in your PATH. So, you have two options to solve it

1. Open the Miniforge prompt and start Spyder from it.
2. Add the directory where conda is placed to your PATH. It should be `C:\Users\Pierre\miniforge3\condabin`, but if that doesn't work, please add `C:\Users\Pierre\miniforge3\Scripts`.

Let us know if that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by sx0charlene** [comment]
I have the same error. Any update on this case? I don't have miniforge3 folder

**Comment by pierre-haessig** [comment]
Hi @sx0charlene , @ccordoba12 closed the ticket because I didn't provide more details (I'm not a daily Spider user and moved to other topics), but, sure, the issue may still exist.

If you can investigate @ccordoba12's propositions https://github.com/spyder-ide/spyder/issues/20433#issuecomment-1406005772, that would probably help.

**Comment by parmeshgajjar** [comment]
> Hey [@pierre-haessig](https://github.com/pierre-haessig), thanks for reporting. You said
> 
> > Run Spyder from base environment (using the automatically created Windows menu launcher)
> 
> I think this problem happens because when Spyder is launched in this way, it can't find the `conda` executable to activate our IPython consoles because it's not in your PATH. So, you have two options to solve it
> 
> 1. Open the Miniforge prompt and start Spyder from it.
> 2. Add the directory where conda is placed to your PATH. It should be `C:\Users\Pierre\miniforge3\condabin`, but if that doesn't work, please add `C:\Users\Pierre\miniforge3\Scripts`.
> 
> Let us know if that works for you.

I am getting a similar error in a Spyder iconsole, when loading the pytorch package. It works in a normal console, but not Spyder's iconsole. 

I launched Spyder from command prompt from the right environment. In addition I've tried adding the two directories to the path. 

Error i get in full is:

`import torch
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[10], line 1
----> 1 import torch

File ~\miniconda3\envs\pytorch-dev\Lib\site-packages\torch\__init__.py:431
    429     if USE_GLOBAL_DEPS:
    430         _load_global_deps()
--> 431     from torch._C import *  # noqa: F403
    434 class SymInt:
    435     """
    436     Like an int (including magic methods), but redirects all operations on the
    437     wrapped node. This is used in particular to symbolically record operations
    438     in the symbolic shape workflow.
    439     """

ImportError: DLL load failed while importing _C: A dynamic link library (DLL) initialization routine failed.`

**Comment by pierre-haessig** [comment]
@parmeshgajjar, I'm not working with Spyder under Windows these days. All I can say is that the key stage for going forward on this issue it to make it well reproducible. For this, perhaps you can reformulate your observations

> I am getting a similar error in a Spyder iconsole, when loading the pytorch package. It works in a normal console, but not Spyder's iconsole.
> I launched Spyder from command prompt from the right environment. In addition I've tried adding the two directories to the path.

as a sequence of "steps to reproduce", like I did in the original description, but taking into account the suggestion of @ccordoba12 in his [comment](https://github.com/spyder-ide/spyder/issues/20433#issuecomment-1406005772) to manipulate the PATH variable.
