### ISSUE TITLE
Variables do not update in spyder. MAJOR ERRORS

### ISSUE THREAD

**Issue by BaylorBrangers** [spyder-ide/spyder#20440]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi, I am having massive errors with running code in spyder/anaconda. I have errors in all code that is currently being run, however I am not getting any error messages. Basically, if i run the same function multiple times, spyder stops updating variables and they become locked in. The error is quite easy to reproduce. At first I thought it might be an issue with tensorflow, but now after running some very basic code I am seeing the same issues. I am completely freaking out because I do not know how deep this issue runs. 

### What steps reproduce the problem?

1. Running the any code that uses loops more than one iteration
2. 
3. 

### What is the expected output? What do you see instead?
The same values 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Python 3.7.16 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Linux 5.15.0-58-generic 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @BaylorBrangers, thanks for reporting. This kind of errors usually appear when you mix pip and conda packages. That's a really bad practice because they are binary incompatible.

To test that, please open a terminal and run the following commands there:

    conda create -n spyder-env python=3.9 spyder
    conda activate spyder-env
    spyder

I'm almost sure if you run something in the Spyder instance that opens after the last command, you won't get any errors.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
