### ISSUE TITLE
1

### ISSUE THREAD

**Issue by pablobolta** [spyder-ide/spyder#20447]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Closing because this is empty. This indicates that you're a really old Spyder version (probably 3.2 or 3.1), so please update following the instructions in our [installation guide](http://docs.spyder-ide.org/current/installation.html).
