### ISSUE TITLE
have missing dependencies,nconvert

### ISSUE THREAD

**Issue by clarayy** [spyder-ide/spyder#20451]
have missing dependencies,nconverthave missing dependencies,nconverthave missing dependencies,nconverthave missing dependencies,nconvert

**Comment by ccordoba12** [comment]
Hey @clarayy, thanks for reporting. Please let us know the following information:

* What's your Spyder version?
* How did you install Spyder?

Without answers to those versions, I'm afraid we won't be able to help you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
