### ISSUE TITLE
Color scheme "Background" color should affect whole background of editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2045]
_From [lylemoff...@gmail.com](https://code.google.com/u/106799417827709519816/) on 2014-11-12T02:17:52Z_

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.1 on Darwin
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.3.0 (OK) 

What steps will reproduce the problem?

 1. Open:  Preferences > Syntax coloring
2. Select the current color scheme's tab
3. Select the color box for the item "Background" and change the color to something noticeably different from white (#ffffff).
4. Click "Apply" or "OK" 

What is the expected output? What do you see instead?

 -- Expected --
The entire background of the editor should change to match the selected color. This is the area between the number column and the scroll-bar, below the tabs area, and above the status bar. 

-- Actual --
Only the background(s) of printed characters is altered. The remaining area is left white (#ffffff). 

Please provide any additional information below

. The behavior of the "Background" field should either affect the whole background, or their needs to be separate option. Without this change, the dark themes (Monokai, Zenburn, Spyder/Dark) are practically unusable. Even if they were readable, the unchanged white background defeats the purpose of having a dark theme.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2045_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-12T10:15:28Z_

**Status:** Duplicate  
  **Mergedinto:** 2028

**Comment by MilkshakeForReal** [comment]
agreed man
