### ISSUE TITLE
Preferences does not work properly

### ISSUE THREAD

**Issue by vineetgupta086** [spyder-ide/spyder#20463]
Go to Tools > Preferences.
This will first generate an error which can be ignored. Doing the same thing the second time will open the Preferences window and will function properly. Now closing this, and reopening Preferences third time will generate a new error given below.

You can no longer access your Preferences for the current session. You'll need to reopen Spyder environment.

**Comment by ccordoba12** [comment]
Hey @vineetgupta086, thanks for reporting. Unfortunately, the information you provided is not enough for us to help you.

If you're seeing a window like this after the error happens

![imagen](https://user-images.githubusercontent.com/365293/216402405-4213e539-335d-4589-bc51-4b19128282d0.png)

please fill the information required on it and press the `Submit to Github` button.

If not, please open a new issue where you fill the information required in our issue template (i.e. Spyder, Python and Qt/PyQt versions and operating system). And also post a screenshot of the error you're seeing there.
