### ISSUE TITLE
Generating new plots always overrides currently selected plot

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#20474]
Consider the following code:

```
import matplotlib.pyplot as plt, time
for i in range(100):
    plt.figure()
    plt.plot([0, 1, i])
    plt.show()
    time.sleep(0.1)
```

Every time a new plot is generated, it is selected in the plots panel. If you want to look at a plot, you must wait untill all the plots are generated.

It would be great if, when you select a plot, the selected plot is not replaced by a newly plotted plot.

**Comment by dalthviz** [comment]
Checked locally and that makes sense to me :+1: What do you think @spyder-ide/core-developers ?

**Comment by CAM-Gerlach** [comment]
Generally makes sense to me in that particular case, but my concern is that if a user had a fair number of plots and had some older plot selected from well before they executed their code, they might expect Spyder to still open their present plot automatically and not see/realize new plots had been added, and either go looking for their plot and not be sure where to find it, or think the previous plot was their new plot—especially if the plots pane was not visible initially when they ran their plotting code.

To more carefully fix the specific problem presented without running into these issues, we could suppress switching to a new plot only if a selection was made after the current code started executing. I.e., if I run my code and then select a particular plot, it is not overridden, but if I just happened to have a plot selected at some point prior, then still show the new plots until I actively select something else.

If that's too difficult to implement or is still not enough, an alternative would be disabling switching to a different plot when the plot pane is visible (i.e. not hidden, and on the currently active tab in a panel) and a plot is selected, which would not be always quite so obvious, but more so than if it were not active or hidden.

**Comment by impact27** [comment]
What I implemented in https://github.com/spyder-ide/spyder/pull/20475 is:
If the user does nothing, select the last plot
If a plot is selected during execution, do no replace it so that the user can look at it
If a new plot is created after executing (first plot after a new execution) select this one and start scrolling again until the user selects a plot

**Comment by ccordoba12** [comment]
> To more carefully fix the specific problem presented without running into these issues, we could suppress switching to a new plot only if a selection was made after the current code started executing

I think what @impact27 did fulfills this requirement, right @CAM-Gerlach?

**Comment by CAM-Gerlach** [comment]
Yup, that seems to precisely match the desired behavior I proposed. Thanks @impact27 and @ccordoba12 !
