### ISSUE TITLE
DOAN MINH THANH

### ISSUE THREAD

**Issue by 01101986** [spyder-ide/spyder#20501]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @01101986, thanks for reporting. It seems you're using a very old Spyder version. So, most probably your problem is fixed in our latest version available. Please update by closing Spyder and then removing and reinstalling Anaconda.
