### ISSUE TITLE
Suggestion: Show which line of code is currently executing

### ISSUE THREAD

**Issue by skalierer** [spyder-ide/spyder#20508]
Would it be possible to see which line of code is currently executing? E.g. by mouseovering the small square in the top right of the console windows that indicates that the script is running? I'm working with pretty long .py scripts which is why my files are already filled with loads of print() commands to indicate that important intermediate steps have been reached, however, life would be easier if I could see the exact line that's currently executing.

Maybe that's not feasible because some programs probably execute thousands of lines of code per second which makes it impossible to track which line it is now in (in my bubble on the other hand I have single lines that can take a very long time - hundreds of them). Thanks so much in any case for giving this a thought.

**Comment by ccordoba12** [comment]
Hey @skalierer, thanks for reporting. Unfortunately, that's not possible because (as far as I know) Python doesn't provide that functionality.
