### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode generated by pyreadline

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2051]
_From [zdpos...@gmail.com](https://code.google.com/u/103328487118799990906/) on 2014-11-16T14:27:20Z_

Hello,

I am getting and error message in console just after start-up of spyder:

Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:38:22) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
Failed calling sys.**interactivehook**
Traceback (most recent call last):
  File "C:\Python34\lib\site.py", line 426, in register_readline
    readline.read_history_file(history)
  File "C:\Python34\lib\site-packages\pyreadline\rlmain.py", line 165, in read_history_file
    self.mode._history.read_history_file(filename)
  File "C:\Python34\lib\site-packages\pyreadline\lineeditor\history.py", line 82, in read_history_file
    for line in open(filename, 'r'):
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 899: character maps to <undefined>
>>> 

Restarting console does not helps - this error message appears after every restart (of console or whole application)
Removing configuration directory does not helps.

I am using Python 3.4.1 32bit on Windows 7 64bit Pro.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2051_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-16T15:35:43Z_

Thanks for your interest in improving Spyder. I have two questions for you:

1. Does your Windows account name contains non-ascii characters?

2. Did you run some commands containing non-ascii chars before this problem?

**Labels:** Cat-Console MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [zdpos...@gmail.com](https://code.google.com/u/103328487118799990906/) on 2014-11-17T07:33:26Z_

1. No, just there are just ascii characters
2. No, this output is shown immediately after starting of current git version of spyder (2.4.0dev b0c125b8b453).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T14:31:43Z_

After looking closely at your report error, I noticed that the problem is with pyreadline, not with Spyder.

I really don't know how to help you with this one. Perhaps uninstalling pyreadline could help you to avoid this error.

**Summary:** UnicodeDecodeError: 'charmap' codec can't decode generated by pyreadline  \<span class="oldvalue"> (was: UnicodeDecodeError: 'charmap' codec can't decode) \</span>  
  **Labels:** -MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [zdpos...@gmail.com](https://code.google.com/u/103328487118799990906/) on 2014-11-19T13:29:02Z_

I tried to uninstall pyreadline (2.0) and error disappeared.
But pyreadline is required by ipython[1]. At the moment I upgrade ipython (by "pip install --upgrade ipython") and it installed pyreadline automatically (and the error is back ;-) ).

[1] http://ipython.org/ipython-doc/2/install/install.html#windows

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-20T10:07:09Z_

Apparently your error was reported before: https://github.com/pyreadline/pyreadline/issues/30 Unfortunately, pyreadline seems stalled now.

Please notice that pyreadline is only necessary to run the terminal version of ipython, but not the version used by Spyder. So you have to decide which one you want to use more.

I'm going to leave this one open in case other people find this error.

**Labels:** -Cat-Console Cat-Miscelleneous

**Comment by goanpeca** [comment]
This issue has been stale for a while, I am closing it.
