### ISSUE TITLE
ERROR:zygote_linux.cc(646)] write: Broken pipe (32) on launch

### ISSUE THREAD

**Issue by alansill** [spyder-ide/spyder#20533]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ N/A ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Starting spyder fails with the following message:

(spyder-env) login-20-26:$ spyder
fromIccProfile: failed minimal tag size sanity
[43528:43528:0100/000000.066693:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
Trace/breakpoint trap (core dumped)

### What steps reproduce the problem?

1. Installation using a fresh miniconda as per the installation guide on a CentOS 8.3 Linux cluster:

  conda create -c conda-forge -n spyder-env spyder numpy scipy pandas matplotlib sympy cython

2. conda activate spyder-env

3. Start spyder as above.

### What is the expected output? What do you see instead?

Expect spyder will launch. get the spash screen, but then the error below

### Paste Traceback/Error Below (if applicable)

```

[46140:46140:0100/000000.568636:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)

```

## Versions

* Spyder version: 5.4.2
* Python version: 3.11.0
* Qt version: 5.15.6
* PyQt version: 5.15.7
* Operating System name/version: CentOS 8.3

conda list | grep -i "spyder\|qt\|python" 
gives:

ipython                   8.10.0             pyh41d4057_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7          py311ha74522f_3    conda-forge
pyqt5-sip                 12.11.0         py311hcafe171_3    conda-forge
pyqtwebengine             5.15.7          py311ha10a086_3    conda-forge
python                    3.11.0          he550d4f_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-lsp-black          1.2.1              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.7.1                hd8ed1ab_0    conda-forge
python-lsp-server-base    1.7.1              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.0              pyhd8ed1ab_0    conda-forge
python_abi                3.11                    3_cp311    conda-forge
qt-main                   5.15.6               h602db52_6    conda-forge
qt-webengine              5.15.4               h325cec9_3    conda-forge
qtawesome                 1.2.2              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.0              pyha770c72_0    conda-forge
qtpy                      2.3.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
spyder                    5.4.2           py311h38be061_0    conda-forge
spyder-kernels            2.4.2           unix_pyhd8ed1ab_0    conda-forge

### Dependencies

(N/A as spyder won't launch)

**Comment by alansill** [comment]
Update: The problem seems to be with the web widgets. By laucning spyder with thte --debug-info verbose, I see that the messages immediately preceding the crash on startup are the following:

```2023-02-14 10:24:43,379 [DEBUG] [spyder.utils.registries] -> Registering <spyder.api.widgets.toolbars.MainWidgetToolbar object at 0x153fd0d4b880> (main_toolbar) under context __global for plugin help
2023-02-14 10:24:43,379 [DEBUG] [spyder.utils.registries] -> Registering <spyder.api.widgets.toolbars.MainWidgetToolbar object at 0x153fd0d4ba30> (('corner_toolbar',)) under context __global for plugin help
2023-02-14 10:24:43,379 [DEBUG] [spyder.utils.registries] -> Registering <spyder.api.widgets.menus.MainWidgetMenu object at 0x153fd0d4bbe0> (options_menu) under context __global for plugin help
[21920:21920:0100/000000.480899:ERROR:zygote_linux.cc(646)] write: Broken pipe (32)
Trace/breakpoint trap (core dumped)
```

Lauching spyder with the --no-web-widgets option allows it to start up successfully.

**Comment by dalthviz** [comment]
Hi @alansill thank you for the feedback! If the ` --no-web-widgets` option helps to workaround this then I think this could be related with https://github.com/spyder-ide/spyder/issues/20358 The fix for that will be availble in the next Spyder release (v5.4.3).

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
