### ISSUE TITLE
Attach sha256sum for installers

### ISSUE THREAD

**Issue by Martin15135215** [spyder-ide/spyder#20536]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

## Problem Description

In the release page there is no sha256sum of the installers

### What is the expected output? What do you see instead?

It would be nice to have also the sha256sum -> example how it is in the release page from notepad++ https://github.com/notepad-plus-plus/notepad-plus-plus/releases/tag/v8.4.9

**Comment by ccordoba12** [comment]
Hey @Martin15135215, thanks for reporting. You said:

> It would be nice to have also the sha256sum

Could you try to make your case a bit stronger? If this is the only reason you're requesting this, I'm afraid we won't do it because we have a lot more pressing things to do.

**Comment by Martin15135215** [comment]
My only reason is, to have a security check, so that i am sure that the installer was not changed. However i am not in a hurry. This could be an low priority task.

**Comment by ccordoba12** [comment]
Ok, thanks for the additional info.

@mrclary, what do you think about this one for Spyder 6? Perhaps we could generate the sha256 sums for the installers on Github actions and attach them to the release message?

**Comment by mrclary** [comment]
Hmm. I don't know that much about checksums, but my understanding is that proper code signatures should obviate the need for checksums. Currently, the macOS standalone installer and the new conda-based installer for macOS are codesigned, so I don't think checksums are needed.

I believe the conda-based installer (i.e. `constructor`) also allows for code signature for Windows, but I don't know if it has been properly implemented. I also do not know what, if any, code signing possibilities there are for Linux. Perhaps @jaimergp could comment.

**Comment by ccordoba12** [comment]
> Hmm. I don't know that much about checksums, but my understanding is that proper code signatures should obviate the need for checksums.

Right. But this could be as simple as running `echo sha256sum <installer> > <installer-name>-<sha256sum>.txt` on CIs and then upload that file to the release artifacts.

Until we have time to do this for Windows and Linux (see below), I think we should try to.

> I believe the conda-based installer (i.e. constructor) also allows for code signature for Windows

Ok, that's a task for @dalthviz, but perhaps after we release Spyder 6.

> I also do not know what, if any, code signing possibilities there are for Linux.

I don't think so because I doubt we'll be able to publish this package as a Snap or something similar.

**Comment by ccordoba12** [comment]
Yep, sounds good to me.

**Comment by jaimergp** [comment]
Windows signing is implemented but getting the required certificated involves quite some paperwork, or so I've heard. See https://github.com/conda-forge/miniforge/issues/201
