### ISSUE TITLE
spyder does not connect to remote kernel

### ISSUE THREAD

**Issue by vevefu** [spyder-ide/spyder#20559]
## Problem Description
I am trying to connect to a remote kernel following the steps as in: https://docs.spyder-ide.org/current/panes/ipythonconsole.html#using-external-kernels
1.) launch kernel on remote server
2.) copy kernel .json file to local computer
3.) using the spyder Consoles to connect to kernel

I tried to connect using my password or an ssh key (.rsa), both did not work. Spyder gets stuck in an endless loop of "Secsh channel xx open FAILED: Connection refused: Connect failed"

I saw that there are two issues ([#18315](https://github.com/spyder-ide/spyder/issues/18315) and #[17772](https://github.com/spyder-ide/spyder/issues/17772)), which describe a similar problem and which were both fixed by updating spyder and spyder_kernels on both machines. I tried this as well but it did not fix my problem. Also using 
`spyder --debug-output terminal`
as in [#20170](https://github.com/spyder-ide/spyder/issues/20170) did not work. Any ideas about what I did wrong?

* Spyder version:   5.3.3
* spyder-kernels:   2.3.3
* Python version:   3.10.9

**Comment by ccordoba12** [comment]
Hey @vevefu, thanks for reporting. According to a quick googling, this seems to be a problem with the SSH server you're trying to connect to:

https://serverfault.com/questions/480208/strange-output-on-ssh-tunneling-output-failed-connect-failed-connection-timed

https://unix.stackexchange.com/questions/458967/ssh-channel-xx-open-failed-connect-failed-open-failed

So, I doubt there's something we can do about it in Spyder.

Let us know if that info is helpful.

**Comment by vevefu** [comment]
Thank you @ccordoba12! I contacted the host of the server. we could not figure out what the problem was, but found a work-around in using x2go and starting spyder directly from the server. I am therefore closing this issue:)

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. And glad that you were able to use Spyder at the end.
