### ISSUE TITLE
Setting "Automatically remove trailing spaces when saving files" cause "Final newline missing" message

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2056]
_From [zdpos...@gmail.com](https://code.google.com/u/103328487118799990906/) on 2014-11-18T16:47:45Z_

Option (Preferences -> Editor -> Advanced settings:) "Automatically remove trailing spaces when saving files" removes also last line in python script.

This cause that static code analyse rise issue [C0304] Final newline missing.

I use Spyder 2.4.0dev (b0c125b8b453:4272) on Windows 7 64bit.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2056_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-11-18T14:23:23Z_

Thanks for reporting and for your interest in fixing Spyder. I'll fix this problem in of our next releases.

**Labels:** MS-v2.3.3 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-01T07:16:09Z_

I can't reproduce this error. Setting "Automatically remove trailing spaces when saving files" does not remove the last line.

Could you give us an example file that is causing you this problem?

Also please tell us what your Spyder version is.

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by spyder-issues-migrator** [comment]
_From [zdpos...@gmail.com](https://code.google.com/u/103328487118799990906/) on 2015-02-01T09:10:22Z_

I tested current revision that it works as expected.
So this was somehow fixed in meantime. You can close this issue.

**Comment by FXLab91** [comment]
I just had the exact same problem using Spyder 3.14
