### ISSUE TITLE
Feature request: Setting working directory (and maybe more) with "magic" comments

### ISSUE THREAD

**Issue by ycwang-hello** [spyder-ide/spyder#20573]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In some cases, I may want to set the working directory for some files (overwriting the default settings). Is it possible to add the feature of "magic" comments (or something like that) so that I can declare the working directory (only) for this file? (Also, I think magic comments might also be useful if one wants to overwrite other settings when running a file. But for changing the working directory, I think Spyder only needs to detect the magic comment and change the `wdir` of function `runfile`.)

## Versions

* Spyder version: 5.3.3

**Comment by ccordoba12** [comment]
Hey @ycwang-hello, thanks for reporting. You said:

> Is it possible to add the feature of "magic" comments (or something like that) so that I can declare the working directory (only) for this file?

You have two options for this:

1. Select the current working directory you want to use for your file in the menu entry `Run > Configuration per file`:

    ![image](https://user-images.githubusercontent.com/365293/220806546-21ad8255-c07d-4ad7-a999-ba7524ee9923.png)

2. Use the `%cd` magic in your file, like this:

    ![image](https://user-images.githubusercontent.com/365293/220806653-df5cb0e5-dc77-4f17-bf91-770795bd318e.png)

    However, that will be flagged as an error (as can be seen in the screenshot above) because it's not valid Python code.

**Comment by ccordoba12** [comment]
Besides those possibilities, which are specific to Spyder, we recommend you to use instead the [`os.chdir`](https://docs.python.org/3/library/os.html#os.environb) function because you'll be able to run your code in and out of Spyder.

**Comment by ccordoba12** [comment]
Let us know if that answer your question.

**Comment by ycwang-hello** [comment]
Thanks! That answers my question.
