### ISSUE TITLE
Scaling issue with a monitor

### ISSUE THREAD

**Issue by anuragsodhi** [spyder-ide/spyder#20585]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
1. Scaling issue 

### What steps reproduce the problem?

1.  Browse tabs button shows very big file names and unscrollable list that is just cutoff due to size
2.  Same issue with "Code analysis" warnings, too big size so unable to read them
3. Sometime the LSP warnings disappear and need to restart LSP server 

I have enabled auto high DPI, as without that the interface is just huge with small icons. 

Laptop is 4k resolution with 200% zoom and the attached monitor is ultrawide with 3440×1440
### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.2
* Python version: 3.7.15
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @anuragsodhi thank you for the feedback! Maybe the preferences for the screen resolution could help here? You can find them in `Preferences > Application > Screen resolution`. Could you try selecting the `Enable auto high DPI scaling` option?

Let us know if that helps!

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by anuragsodhi** [comment]
Hi Sorry i was away, can we reopen this,. Yes I am using Enable auto high DPI scaling option

**Comment by dalthviz** [comment]
Hi again @anuragsodhi , no problem, we can reopen this :+1: What about checking the other options in the `Screen resolution` config section? Maybe a specific custom scaling value could help? Let us know!

**Comment by anuragsodhi** [comment]
I have tried all options same issue. Just to clarify, the icons are of correct dpi when i open the spyder and drag on monitor. The issues starts if the laptop sleeps or i disconnect and reconnect monitor. To resolve i have to drag the spyder back to laptop screen and maximize and then drag back to monitor and it fixes things again.

![image](https://user-images.githubusercontent.com/6956109/232931568-3fa0f418-382f-45e3-a463-478b806f1afc.png)

![image](https://user-images.githubusercontent.com/6956109/232931435-ba2720ef-89bd-4529-b742-4f49dc6be7df.png)

**Comment by ccordoba12** [comment]
I think I know how to fix this. We'll try to do it in our next version (5.4.4), to be released in June.

**Comment by HumpyBlumpy** [comment]
I think I have the same issue.
I have a 4k laptop connected to a 1920*1080 external monitor.
Using windows 11 with 200% scaling on the laptop and 100% on the monitor. 
Only way to get spyder to show up properly is to open it with monitor disconnected and then connect monitor.

**Comment by bramson** [comment]
I have this issue too.  None of the options in Preferences affects the jumbo font and spacing in most UI elements.  Moving the app window between monitors also does not change anything.

The Spyder info says:
* Spyder version: 5.5.1  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

But actually it's Windows 11 (unfortunately).

**Comment by dalthviz** [comment]
@ccordoba12 should we close this one or #12990 ? Seems like both refer to issues with the font being big when using multiple monitors with different monitor scales configs

**Comment by GitKia1392** [comment]
Bro reopen this one that one is a ripoff man.
