### ISSUE TITLE
When opening spyder, window of "new Spyder version" and "Kite" always occur

### ISSUE THREAD

**Issue by congmingyige** [spyder-ide/spyder#20611]
### Issue Report Checklist

Open Spyder several times, and the windows also occur.

## Problem Description

When opening spyder, window of "new Spyder version" and "Kite" always occur.

### What steps reproduce the problem?

1. Open Spyder several times, and the problems also happen.
2. I know that the operation "conda update install" may works, but it may happen when new version happens.
3. I search in website about whether some settings fix them, but I can't find any solution.

### What is the expected output? What do you see instead?
No windows occur when opening spyder.

### Paste Traceback/Error B
![image_1461](https://user-images.githubusercontent.com/20537566/222089869-cb2c39d7-fb5e-4e74-8cad-6d9bc78443e1.png)
![image_1463](https://user-images.githubusercontent.com/20537566/222090013-5c7faa1c-8a6e-4d3c-a855-304677a7d51a.png)

## Versions

* Spyder version: 5.2.2
* Python version: 3.7.12
* Qt version: 
* PyQt version: 5.15.7
* Operating System name/version:

**Comment by ccordoba12** [comment]
Let us know if this works for you.

**Comment by congmingyige** [comment]
> 

Thanks for replying.

For “new spyder version", not chooing the ”checking for update" doesn't work, “Tools > Preferences > Application > Advanced settings“ works.

![图片](https://user-images.githubusercontent.com/20537566/222178523-db4ecb71-0c08-4fa4-bebc-7e45230612aa.png)

For ”Kite", using new spyder version,
conda update anaconda
conda install spyder=5.3.3

may occur: ImportError: cannot import name 'environmentfilter' from 'jinja2’
conda install jinja2==3.0

**Comment by ccordoba12** [comment]
> For “new spyder version", not chooing the ”checking for update" doesn't work, “Tools > Preferences > Application > Advanced settings“ works.

Yeah, we're aware of that. But that problem is fixed in our latest version (5.4.2), which unfortunately is not available in Anaconda yet.

> For ”Kite", using new spyder version,
conda update anaconda
conda install spyder=5.3.3
>
>may occur: ImportError: cannot import name 'environmentfilter' from 'jinja2’
conda install jinja2==3.0

Ok, so that means that you were able to successfully update Spyder?

**Comment by congmingyige** [comment]
> 

Yes. It's ok now. Thanks.
Kite problem was also mention several days ago, https://github.com/spyder-ide/spyder/issues/20594 (**_maybe happend recently_**), and startup problem was mention in  https://github.com/spyder-ide/spyder/issues/16466, which I did not realized.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us about it.

Closing this issue then.
