### ISSUE TITLE
Startup on M2 Max

### ISSUE THREAD

**Issue by japjit** [spyder-ide/spyder#20614]
### What steps will reproduce the problem?

Just need to start spyder on a M2 Max with the beta 13.3.2 macos

### Traceback
```python-traceback
Traceback (most recent call last):
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 85, in wrapper
    self._ready.set_result(None)
asyncio.exceptions.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "qtconsole/manager.pyc", line 27, in poll
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/restarter.py", line 143, in poll
    self.kernel_manager.restart_kernel(now=True, newports=newports)
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "nest_asyncio.pyc", line 90, in run_until_complete
  File "asyncio/futures.pyc", line 201, in result
  File "asyncio/tasks.pyc", line 256, in __step
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 548, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 30, in wrapped
    raise e
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/utils.py", line 27, in wrapped
    return loop.run_until_complete(future)
  File "nest_asyncio.pyc", line 90, in run_until_complete
  File "asyncio/futures.pyc", line 201, in result
  File "asyncio/tasks.pyc", line 256, in __step
  File "/Applications/Spyder.app/Contents/Resources/lib/python3.9/jupyter_client/manager.py", line 88, in wrapper
    self._ready.set_exception(e)
asyncio.exceptions.InvalidStateError: invalid state
```

## Versions

* Spyder version: 5.4.2 93124668b (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.4.0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.1.0 (OK)
cloudpickle >=0.5.0                  :  2.2.0 (OK)
cookiecutter >=1.6.0                 :  2.1.1 (OK)
diff_match_patch >=20181111          :  20200713 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0              :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0                :  0.18.2 (OK)
jellyfish >=0.7                      :  0.9.0 (OK)
jsonschema >=3.2.0                   :  4.17.3 (OK)
keyring >=17.0.0                     :  23.13.1 (OK)
nbconvert >=4.0                      :  7.2.8 (OK)
numpydoc >=0.6.0                     :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.8.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.4 (OK)
pygments >=2.0                       :  2.14.0 (OK)
pylint >=2.5.0;<3.0                  :  2.15.10 (OK)
pylint_venv >=2.1.1                  :  None (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                 :  1.7.1 (OK)
pylsp_black >=1.2.0                  :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0            :  3.0.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.2.1                    :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0             :  5.4.0 (OK)
qtpy >=2.1.0                         :  2.3.0 (OK)
rtree >=0.9.7                        :  1.0.1 (OK)
setuptools >=49.6.0                  :  66.0.0 (OK)
sphinx >=0.6.6                       :  5.1.1 (OK)
spyder_kernels >=2.4.2;<2.5.0        :  2.4.2 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  2.2.1 (OK)
zmq >=22.1.0                         :  24.0.1 (OK)

# Optional:
cython >=0.21                        :  0.29.33 (OK)
matplotlib >=3.0.0                   :  3.6.3 (OK)
numpy >=1.7                          :  1.24.1 (OK)
pandas >=1.1.1                       :  1.5.2 (OK)
scipy >=0.17.0                       :  1.10.0 (OK)
sympy >=0.7.3                        :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2 :  1.2.2 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment]
Hey @japjit, thanks for reporting. I don't know what's happening in your case, but we'll try to get to the bottom of it.

@mrclary, could you take a look at this one?

**Comment by mrclary** [comment]
Unfortunately, I cannot reproduce the issue.
However, I am running with Ventura 13.2.1 on an M1 chip, not 13.3.2 beta.

* Spyder version: 5.4.2 93124668b (standalone)
* Python version: 3.9.14 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.3.0

@japjit, would you be willing to test our new experimental installer (https://github.com/spyder-ide/spyder/releases/download/v5.4.2/EXPERIMENTAL-Spyder-5.4.2-macOS-x86_64.pkg)?
You will have to delete or rename the existing standalone Spyder application (located either `~/Applications/Spyder.app` or `/Applications/Spyder.app`).
This installer will replace the existing standalone dmg installer when we release Spyder 6.0.0. I don't know what the timeline is for macOS 13.3.2 release, but it may align closely with Spyder 6.0.0alpha or 6.0.0.

**Comment by japjit** [comment]
Will do and report back Cheers, JapjitOn Mar 3, 2023, at 3:47 PM, Ryan Clary ***@***.***> wrote:﻿
Unfortunately, I cannot reproduce the issue.
However, I am running with Ventura 13.2.1 on an M1 chip, not 13.3.2 beta.

Spyder version: 5.4.2 9312466 (standalone)
Python version: 3.9.14 64-bit
Qt version: 5.15.2
PyQt5 version: 5.15.7
Operating System: Darwin 22.3.0

@japjit, would you be willing to test our new experimental installer (https://github.com/spyder-ide/spyder/releases/download/v5.4.2/EXPERIMENTAL-Spyder-5.4.2-macOS-x86_64.pkg)?
You will have to delete or rename the existing standalone Spyder application (located either ~/Applications/Spyder.app or /Applications/Spyder.app).
This installer will replace the existing standalone dmg installer when we release Spyder 6.0.0. I don't know what the timeline is for macOS 13.3.2 release, but it may align closely with Spyder 6.0.0alpha or 6.0.0.

**Comment by japjit** [comment]
Same error -
Traceback (most recent call last):
File
"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py",
line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File
"/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py",
line 87, in _run_code
exec(code, run_globals)
File
"/Users/japjit/Library/Python/3.9/lib/python/site‑packages/spyder_kernels/console/__main__.py",
line 22, in
from spyder_kernels.console import start
File
"/Users/japjit/Library/Python/3.9/lib/python/site‑packages/spyder_kernels/console/start.py",
line 21, in
import ipykernel
File
"/Users/japjit/Library/Python/3.9/lib/python/site‑packages/ipykernel/__init__.py",
line 5, in
from .connect import * # noqa
File
"/Users/japjit/Library/Python/3.9/lib/python/site‑packages/ipykernel/connect.py",
line 11, in
import jupyter_client
ModuleNotFoundError: No module named 'jupyter_client'
Cheers, Japjit

**Comment by mrclary** [comment]
@japjit, that looks like a different error than the OP. Nevertheless, the new installer is clearly not working either. Since both standalone Spyder 5.4.2 and the new installer Spyder 5.4.2 are both working for me on macOS 13.2.1 (M1), I can only conclude that it must be either the M2 chip (less likely) or macOS 13.3.2 beta (more likely).

Unfortunately, without access to this system, I cannot debug it. IMHO, I think this issue may actually require updates to Jupyter (ipykernel, jupyter_client).

**Comment by japjit** [comment]
Seems like it might have to do with install dependencies version mismatches. Cheers, JapjitOn Mar 3, 2023, at 9:19 PM, Ryan Clary ***@***.***> wrote:﻿
@japjit, that looks like a different error than the OP. Nevertheless, the new installer is clearly not working either. Since both standalone Spyder 5.4.2 and the new installer Spyder 5.4.2 are both working for me on macOS 13.2.1 (M1), I can only conclude that it must be either the M2 chip (less likely) or macOS 13.3.2 beta (more likely).
Unfortunately, without access to this system, I cannot debug it. IMHO, I think this issue may actually require updates to Jupyter (ipykernel, jupyter_client).

**Comment by ccordoba12** [comment]
@japjit, it seems you have another Python version in

    /Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework

which is interfering with our experimental installer. So, please remove it and try again.

**Comment by mrclary** [comment]
@ccordoba12, nice catch! I don't know why that would interfere with our experimental installer. I'd have to inspect the shortcut created and see the installer logs.
@japjit, can you run the following in the terminal?
```
$ ls -al ~/Applications/Spyder.app/Contents/MacOS/
```

**Comment by japjit** [comment]
After removing the Xcode python dir everything started working. I went back
to brew installed spyder and that is working as well. Thanks all!

Cheers, Japjit

**Comment by mrclary** [comment]
Thanks @ccordoba12. @japjit I'm glad things are working for you now.
