### ISSUE TITLE
textdistance >=4.2.0 :None(NOK)

### ISSUE THREAD

**Issue by cocokame** [spyder-ide/spyder#20615]
### What steps will reproduce the problem?

I installed spyder using 'pip install spyder'.
But I got an error message below.
#Mandatory:
textdistance >=4.2.0 :None (NOK)

I confirmed dependencies using pipdeptree and I use textdistance ver 4.2.0.

 - spyder-kernels [required: >=2.2.0,<2.3.0, installed: 2.2.0]
    - cloudpickle [required: Any, installed: 2.2.1]
    - ipykernel [required: >=5.3.0, installed: 5.5.6]
      - ipython [required: >=5.0.0, installed: 7.16.3]
        - backcall [required: Any, installed: 0.2.0]
        - colorama [required: Any, installed: 0.4.5]
        - decorator [required: Any, installed: 5.1.1]
        - jedi [required: >=0.10,<=0.17.2, installed: 0.17.2]
          - parso [required: >=0.7.0,<0.8.0, installed: 0.7.1]
        - pickleshare [required: Any, installed: 0.7.5]
        - prompt-toolkit [required: >=2.0.0,<3.1.0,!=3.0.1,!=3.0.0, installed: 3.0.36]
          - wcwidth [required: Any, installed: 0.2.6]
        - pygments [required: Any, installed: 2.14.0]
        - setuptools [required: >=18.5, installed: 59.6.0]
        - traitlets [required: >=4.2, installed: 4.3.3]
          - decorator [required: Any, installed: 5.1.1]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.16.0]
      - ipython-genutils [required: Any, installed: 0.2.0]
      - jupyter-client [required: Any, installed: 7.1.2]
        - entrypoints [required: Any, installed: 0.4]
        - jupyter-core [required: >=4.6.0, installed: 4.9.2]
          - pywin32 [required: >=1.0, installed: 305]
          - traitlets [required: Any, installed: 4.3.3]
            - decorator [required: Any, installed: 5.1.1]
            - ipython-genutils [required: Any, installed: 0.2.0]
            - six [required: Any, installed: 1.16.0]
        - nest-asyncio [required: >=1.5, installed: 1.5.6]
        - python-dateutil [required: >=2.1, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - pyzmq [required: >=13, installed: 25.0.0]
        - tornado [required: >=4.1, installed: 6.1]
        - traitlets [required: Any, installed: 4.3.3]
          - decorator [required: Any, installed: 5.1.1]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.16.0]
      - tornado [required: >=4.2, installed: 6.1]
      - traitlets [required: >=4.1.0, installed: 4.3.3]
        - decorator [required: Any, installed: 5.1.1]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.16.0]
    - ipython [required: >=7.6.0, installed: 7.16.3]
      - backcall [required: Any, installed: 0.2.0]
      - colorama [required: Any, installed: 0.4.5]
      - decorator [required: Any, installed: 5.1.1]
      - jedi [required: >=0.10,<=0.17.2, installed: 0.17.2]
        - parso [required: >=0.7.0,<0.8.0, installed: 0.7.1]
      - pickleshare [required: Any, installed: 0.7.5]
      - prompt-toolkit [required: >=2.0.0,<3.1.0,!=3.0.1,!=3.0.0, installed: 3.0.36]
        - wcwidth [required: Any, installed: 0.2.6]
      - pygments [required: Any, installed: 2.14.0]
      - setuptools [required: >=18.5, installed: 59.6.0]
      - traitlets [required: >=4.2, installed: 4.3.3]
        - decorator [required: Any, installed: 5.1.1]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.16.0]
    - jupyter-client [required: >=5.3.4, installed: 7.1.2]
      - entrypoints [required: Any, installed: 0.4]
      - jupyter-core [required: >=4.6.0, installed: 4.9.2]
        - pywin32 [required: >=1.0, installed: 305]
        - traitlets [required: Any, installed: 4.3.3]
          - decorator [required: Any, installed: 5.1.1]
          - ipython-genutils [required: Any, installed: 0.2.0]
          - six [required: Any, installed: 1.16.0]
      - nest-asyncio [required: >=1.5, installed: 1.5.6]
      - python-dateutil [required: >=2.1, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - pyzmq [required: >=13, installed: 25.0.0]
      - tornado [required: >=4.1, installed: 6.1]
      - traitlets [required: Any, installed: 4.3.3]
        - decorator [required: Any, installed: 5.1.1]
        - ipython-genutils [required: Any, installed: 0.2.0]
        - six [required: Any, installed: 1.16.0]
    - pyzmq [required: >=17, installed: 25.0.0]
  - textdistance [required: >=4.2.0, installed: 4.5.0]
  - three-merge [required: >=0.1.1, installed: 0.1.1]
    - diff-match-patch [required: Any, installed: 20200713]
  - watchdog [required: >=0.10.3, installed: 2.3.1]
yapf==0.32.0

Could you tell me how to solve this problem?

### Traceback
```python-traceback
Traceback (most recent call last):
  File "c:\users\kchika\.pyenv\pyenv-win\versions\3.6.8\lib\site-packages\spyder\plugins\editor\widgets\codeeditor.py", line 1942, in finish_code_folding
    folding_panel.update_folding(self._folding_info)
AttributeError: 'CodeEditor' object has no attribute '_folding_info'
```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.6.8
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.3 (OK)
jedi >=0.17.2;<0.19.0         :  0.17.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.1 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.7.1 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0                :  2.13.9 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.1.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  None (NOK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.3.1 (OK)
zmq >=17                      :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  None (NOK)
numpy >=1.7                   :  1.19.5 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @cocokame thank you for the feedback! Seems like this could be related with https://github.com/spyder-ide/spyder/issues/19514 However, the Spyder version that has the fix doesn't support Python 3.6 :/

I would suggest to update Spyder and your Python version. Is that possible for you?

Let us know if the info here helps!

**Comment by cocokame** [comment]
Thank you for your valuable comment.
I have updated the python version and resolved this error.

Thank you very much for your kind reply.

**Comment by dalthviz** [comment]
Awesome! Happy to hear that you were able to update and fix the issue 🎉 

I will close this as a duplicate then
