### ISSUE TITLE
Newer versions of spyder wont launch.

### ISSUE THREAD

**Issue by Rebbma** [spyder-ide/spyder#20627]
Error code when launching spyder on versions after spyder 5.1.5. Both launching from the anaconda navigator or command lines produce the same error. Most recent version of Sypder that works is spyder 5.1.5, qt-5.9.7, pyqt-5.9.2, spyder-kernels-2.1.3

```python-traceback

Traceback (most recent call last):
File "/home/user/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/home/user/anaconda3/lib/python3.9/site-packages/spyder/app/start.py", line 248, in main
from spyder.app import mainwindow
File "/home/user/anaconda3/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 57, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/home/user/anaconda3/lib/python3.9/site-packages/qtpy/QtWebEngineWidgets.py", line 29, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libpci.so.3: cannot open shared object file: No such file or directory

```

* Spyder version: 5.3.3
* Python version: 3.9.13
qtconsole              5.3.2
qt-main                  5.15.2               
qt-webengine       5.15.9         
qtawesome           1.2.2            
qtconsole              5.3.2            
qtpy                       2.2.0            
qtwebkit               5.212       
* PyQt version: 5.15.7
* Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.153
      Architecture: x86-64

Problem also occurred on linux bullseye.

**Comment by dalthviz** [comment]
Hi @Rebbma thank you for the feedback! Could you check if running Spyder with the flag `--no-web-widgets` helps? Let us know!

**Comment by Rebbma** [comment]
I still get the same error.

**Comment by dalthviz** [comment]
Maybe this https://stackoverflow.com/a/56972113 post could be useful @Rebbma . Let us know if the command there helps!

**Comment by Rebbma** [comment]
Still getting the same error, unfortunately.

**Comment by anorreyv** [comment]
HI I am having the same issues with Spyder not launching. I did try all of the above steps already. Is there anything else you can think of? I have a colleague with the same issue as well. Next thing I'll try is uninstalling and reinstalling.

**Comment by ccordoba12** [comment]
@anorreyv, are you using Linux and having a similar error than the one reported by @Rebbma? If not, then please open a new issue about it, fill the requested information and post there the error you're getting (if any).

**Comment by ccordoba12** [comment]
@Rebbma, please open a terminal and run

    sudo apt install libpci3

That should solve your problem.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
