### ISSUE TITLE
Sporatic tkinter functionality (mostly the lack thereof)

### ISSUE THREAD

**Issue by XOnanoSmartfoam** [spyder-ide/spyder#20684]
## Problem Description
Spyder recently has stopped playing nice with tkinter functions. I have used tkinter GUI to select files/folders for data processing for many years. Recently I have found that Spyder will not open the tkinter windows when prompted. 

Here is an example of a function that has worked without issue for quite a while and continues to work without problems in PyCharm:

```
def select_folder(title="Model for Prediction", folder=".", master=None):
    """
    Display a box to select a folder.

    If a folder is selected the folder path is returned, otherwise `None` is returned.

    :param string title:
        The title to be displayed on the box. Defaults to 'Select file'.
    :param string folder:s
        The initial folder to open. Defaults to '.'.
    :param App master:
        Optional guizero master which the popup will be placed over. Defaults
        to `None`.
    :return:
        The path of folder selected or `None`.
    """
    if not os.path.isdir(folder):
        utils.error_format("The folder '{}' specified for select_folder does not exist.".format(folder))
        folder = "."
    
    
    return filedialog.askdirectory(title=title, initialdir=folder, parent=None if master is None else master.tk)
```

Spyder doesn't display any errors it just sits waiting to run. I either have to restart Spyder or the kernal to move forward. On occasion when I restart the kernel it will pop-up the tkinter window just before I get the notice that it is 

### What steps reproduce the problem?

1. Run filedialog function to select file or folder
2. Not always repeatable

### What is the expected output? What do you see instead?
I expect to have a window pop-up with the option to select a folder. This function works with every other IDE that I use including PyCharm and Jupyter. 

## Versions
* Spyder version: 5.4.2
* Python version: 3.10.9
* Qt version: 5.15.2
* PyQt version: 5.15.9
* Operating System name/version: Windows 11 / 22H2

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.1 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.9.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.9 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  3.0.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.16.1 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.5.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
zmq >=22.1.0                  :  25.0.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.3 (OK)
numpy >=1.7                   :  1.24.2 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  None (NOK)

```

**Comment by ccordoba12** [comment]
Hey @XOnanoSmartfoam, thanks for reporting. Please notice that your code example is not reproducible because:

* There's no `utils.error_format` import (I guess that could be replaced by a `print`, but still).
* There's no `filedialog` imported on it.

So, please fix that and let us know when you do it.

**Comment by XOnanoSmartfoam** [comment]
I have imported all of the required packages and call the function later on in my script. The baffling thing is my code has worked in the past in Spyder and works with other IDEs like PyCharm and Jupyter every time but hasn't been working in Spyder very often as of late.

**Comment by ccordoba12** [comment]
I'm sorry but without a reproducible code example we won't be able to check what's wrong on our side. So, please post one.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
