### ISSUE TITLE
Spyder bug has permanently deleted all my files

### ISSUE THREAD

**Issue by cyiannaki** [spyder-ide/spyder#20706]
## Problem Description
While trying to delete multiple files through the Files window in spyder, it prompted me if i want to save an open file which I definitely did not select for deleting. It would not allow me to save it in my usual folder which also happens to be the startup folder that spyder uses. So i saved the file on my desktop and then when I was prompted to delete the selected files. I clicked on cancel since something wasn't right and I was shocked to find out that my startup directory with all my work, was permanently deleted due to some stupid bug. I know i did not make a mistake since it would be impossible to select the startup directory when i was already in that folder, selecting the files to delete. This is a massive fuck up from the spyder ide since i could not restore the deleted file using testdisk. I hope you guys can provide an answer to this since it is unacceptable and unheard of for an IDE to trip itself and permanently delete the whole project folder. 
 ***Update - i've managed to get a screenshot of spyder randomly loosing an opened file "analysis8.py". I believe this was the same thing that happened before deleting all my files.

### What steps reproduce the problem?
I do not plan on reproducing to avoid making it more difficult to recover the files.

### What is the expected output? What do you see instead?
All my data was deleted

### Paste Traceback/Error Below (if applicable)
This doesnt work

## Versions
I am using Spyder  with Python  in 

* Spyder version: 5.15.7
* Python version: 3.7.15
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Ubuntu 22.10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.14.0 (OK)
keyring >=17.0.0              :  23.8.2 (OK)
nbconvert >=4.0               :  7.0.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.5.0;<1.6.0          :  1.5.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.2;<5.4.0      :  5.3.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  65.3.0 (OK)
sphinx >=0.6.6                :  4.3.2 (OK)
spyder_kernels >=2.3.3;<2.4.0 :  2.3.3 (OK)
textdistance >=4.2.0          :  4.4.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  23.2.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.5.3 (OK)
numpy >=1.7                   :  1.21.6 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```
![Screenshot from 2023-03-19 10-41-56](https://user-images.githubusercontent.com/10268607/226170180-701138e8-e47d-4afc-9f80-df74da7cc7aa.png)

**Comment by dalthviz** [comment]
Closing as superseded by #21659
