### ISSUE TITLE
Left sidebar not showing errors/warnings

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [spyder-ide/spyder#20710]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I create a new file, the left side bar is not showing the errors and warnings. It however shows for some of the old files (not all). I have realised this today, and I updated to Spyder 5.4.2 about a week ago.
The corresponding option of `enable basic linting` is active.

If I ran the code analysis tool, the code is analysed, giving the errors and warnings, but they are not shown on the sidebar. 

### What steps reproduce the problem?

1. Click on New file
2. Write a line with obviously wrong syntaxis like `import numpy as from numpy if from import`

### What is the expected output? What do you see instead?
I would expect the errors to appear on the left sidebar. 
No error appears.

## Versions

* Spyder version: 5.4.2  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.14.0-1057-oem

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.10.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  2.4.2 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.33 (OK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @Miguel-LlamasLanza thank you for the feedback! Could you check if, in the `Source` menu, the `Show code style warnings` entry is checked?

![warnings](https://user-images.githubusercontent.com/16781833/226489957-dd5c33f5-7fc1-4044-8895-c509732acf04.png)

Also, could you try restarting the LSP by clickin over the `LSP: Python` entry in the status bar and then clicking the `Restart Python Language Server` action?

![restart](https://user-images.githubusercontent.com/16781833/226489966-2c70c078-dc72-4dfa-a44b-318f83d74f89.png)

Let us know if something of the above helps!

**Comment by Miguel-LlamasLanza** [comment]
The `Show code style warnings` entry is checked.
I restarted the LSP, and it was not solved. 
Also I restarted spyder in debug mode and I did not see anything strange (but I don't know much about what it should show). Tell me if you want me to post it here.

Note: When I open spyder, I get the `fromIccProfile: failed minimal tag size sanity`, but I ignore it, as suggested in other threads (' it's just a warning and you can simply ignore because it doesn't affect Spyder')

**Comment by Miguel-LlamasLanza** [comment]
Yes. 
Unfortunately, I had an issue (unrelated to spyder) and I had to do a fresh installation of Ubuntu. On this fresh Ubuntu, the new conda and spyder installation went correctly, and the issue with the 'code style warnings and errors' is not happening anymore.

However, I have a backup of the anaconda3 directory, where I can find the environment directory where spyder was installed. Maybe the information in this directory could help to find what was the issue, and under which conditions this happened. However, since I am not an expert, I would need you to tell me which files I could look at (or send to you) that could help you. Maybe, if you point me to the location where the user configuration of spyder is saved, I can have a look and send you the important information.

Sorry for the unexpected bad news.

**Comment by dalthviz** [comment]
Oh I see, and not bad news at all! Glad to hear that linting inside Spyder is working again!

I think if a clean installation helped then the issue most probably was related with some combination of packages versions instead of the specific config you have. From what version did you did the update to Spyder 5.4.2 in your old installation? I think at some point in Spyder 5.0.x or 5.1.x some changes where done to the LSP related packages which maybe was causing troubles in your installation after doing the update to 5.4.2 🤔

If a clean install made things work then there is not much else we can do, so I think we can close this. What do you think @Miguel-LlamasLanza ?
