### ISSUE TITLE
Fast environment switching [feature request]

### ISSUE THREAD

**Issue by bessman** [spyder-ide/spyder#20717]
# Feature request

I switch environments frequently. Currently, this involves going via Tools > Preferences > Python interpreter, selecting the one I want from a drop-down list, closing Preferences, and finally starting a new console. I would like a more convenient way to do this.

Here is a mock-up of how it could work:
![image](https://user-images.githubusercontent.com/1999462/226848596-d1f5348a-250f-46fd-8a3f-8b76d5dd9ed8.png)

**Comment by dalthviz** [comment]
Hi @bessman thank you for the feedback! In fact this is something we are working on at https://github.com/spyder-ide/spyder/pull/20421 and have been discussed at https://github.com/spyder-ide/ux-improvements/issues/10 . The new menu will be available for Spyder 6 :)

Let us know if the info above clarifies the feature plan a little bit!

**Comment by bessman** [comment]
That's exactly what I had in mind! Sorry for the duplicate, I did try to search but missed it somehow.

I'll be looking forward to this feature in Spyder 6!
