### ISSUE TITLE
Missing documentation: what to do if make install develop command takes a long time to execute (workaround with compiled_requirements.txt)

### ISSUE THREAD

**Issue by mck-abhishekmishra** [spyder-ide/spyder#20720]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
`make install` command usually takes long time to complete, which is mitigated when we use `compiled_requirements.txt` instead. We don't have this step documented and hence new developer has to spend lot of time on troubleshooting.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @mck-abhishekmishra, thanks for reporting. This is not a Spyder problem (we don't use `make install` nor we have `compiled_requirements.txt`). So, I'm going to ask you to open an issue for it in the project's development website that you're trying to build.
