### ISSUE TITLE
Cannot launch Spyder 5.4.2 on Windows11

### ISSUE THREAD

**Issue by PPSoCal** [spyder-ide/spyder#20760]
<img width="671" alt="Screenshot 2023-04-01 022144" src="https://user-images.githubusercontent.com/129587122/229277763-121e4f6b-07ee-4f8b-be8c-6a3aa7a58bb0.png">

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.2
* Python version: 3.10.10
* Qt version: 
* PyQt version: 5.15.7
* Operating System name/version: Windows 11

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @PPSoCal, thanks for reporting. Please open the Anaconda prompt, run there

    spyder --degug-info verbose --debug-output file

and upload here the file called `spyder-debug.log` that is placed in the same directory where you ran the command above.

**Comment by PPSoCal** [comment]
Hi,

I opened anaconda prompt and ran the above code.  Still not working unfortunately.  I am also new to Python, though.
<img width="573" alt="Screenshot 2023-04-04 203442" src="https://user-images.githubusercontent.com/129587122/229975854-144f4d0d-e67d-4e89-b2fc-9631a2af68a7.png">

**Comment by PPSoCal** [comment]
Actually when I type python in anaconda prompt, it says Python 3.10.9 instead of 3.10.10

**Comment by ccordoba12** [comment]
@PPSoCal, the command you need to run in the Anaconda Prompt is this one:

    spyder --degug-info verbose --debug-output file

**Comment by ccordoba12** [comment]
Closing due to lack of response.
