### ISSUE TITLE
Spyder 5.4.3 launched with administrative rights through auto-updater

### ISSUE THREAD

**Issue by roteiro** [spyder-ide/spyder#20774]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just used the autoupdater to update to Spyder 5.4.3 und launched Spyder directly through the installer at the end of the installation process. It seemed to me that it was launched with administrative rights.

I noticed because I use a third party program to modify my keyboard layout which is not effective in applications which are launched with administrative rights and it was not effective after lauching spyder.
Closing Spyder and restarting, everything is back to normal, so seems only a problem if launched through the installer.

### What steps reproduce the problem?

1.  Update Spyder from 5.4.2 to 5.4.3 through the in program updater and launch Spyder through the installer and at the end of the installation

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  5.4.3
* Python version: 3.8.10 64 bit
* Qt version: 5.15.2
* PyQt version: PyQT 5.15.9 
* Operating System name/version: Win 10 x64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree                                     :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.1.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.6.1 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog                                         :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.34 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2             :  1.2.2 (OK)

```

**Comment by ccordoba12** [comment]
Hey @roteiro, thanks for reporting. You said:

> I just used the autoupdater to update to Spyder 5.4.3 und launched Spyder directly through the installer at the end of the installation process.

Ok, so the good news is that our auto-update mechanism is working as expected, which is great.

> It seemed to me that it was launched with administrative rights.

This is a probably a consequence of requiring admin privileges to perform the update. So, I guess after the update Spyder is launched with the same privileges.

> Closing Spyder and restarting, everything is back to normal, so seems only a problem if launched through the installer.

Ok, that's good to know too. But this issue is still something we should try to address.

**Comment by ccordoba12** [comment]
@dalthviz, could you take a look at this one?

**Comment by dalthviz** [comment]
Note: Maybe this could help here? https://github.com/notepad-plus-plus/notepad-plus-plus/blob/546745fe344be6050aa207ccb36821ca3cf52bf3/PowerEditor/installer/nsisInclude/tools.nsh#L18-L27
