### ISSUE TITLE
Loading of old third-party plugins in Spyder 6

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#20776]
Do we still need the code in https://github.com/spyder-ide/spyder/blob/401ee997c4fc0eeba8fab1c4fdaa05cb1c43d1e1/spyder/app/mainwindow.py#L778 and further?

This code tries to load plugins like `spyder-unittest`, even if they are already loaded in the block just above ("Instantiate external Spyder 5 plugins"). The attempt to load `spyder-unittest` as an old third-party plugin silently fails and it does not seem to affect Spyder. However, there is some black magic going on in [spyder/otherplugins.py](https://github.com/spyder-ide/spyder/blob/master/spyder/otherplugins.py) which leaves a mock object in `sys.modules`; that smells iffy. This seems to somehow interfere with the tests that I am adding in spyder-ide/spyder-unittest#197, so I had to monkey patch Spyder to remove the loading of old third-party plugins in Spyder.

I don't know of any working "old third-party plugins" (I think this refers to plugins from Spyder 4), so how about removing that code? I think that this is the only place that uses `spyder/otherplugins.py` so we can remove that file too.

**Comment by ccordoba12** [comment]
> I don't know of any working "old third-party plugins" (I think this refers to plugins from Spyder 4)

Right, I think so too.

> so how about removing that code? I think that this is the only place that uses spyder/otherplugins.py so we can remove that file too.

Good idea. Will do right away.
