### ISSUE TITLE
Strange error for numpy's mean

### ISSUE THREAD

**Issue by 3zhang** [spyder-ide/spyder#20784]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
See code:

```
import numpy as np

a = np.array([1,2,3])

a.mean()
Out[3]: 2.0
[SpyderKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "D:\miniconda3\envs\backup\lib\site-packages\ipykernel\kernelbase.py", line 409, in dispatch_shell
    await result
  File "D:\miniconda3\envs\backup\lib\site-packages\ipykernel\kernelbase.py", line 798, in inspect_request
    reply_content = self.do_inspect(
  File "D:\miniconda3\envs\backup\lib\site-packages\ipykernel\ipkernel.py", line 555, in do_inspect
    bundle = self.shell.object_inspect_mime(
  File "D:\miniconda3\envs\backup\lib\site-packages\IPython\core\interactiveshell.py", line 1838, in object_inspect_mime
    return self.inspector._get_info(
  File "D:\miniconda3\envs\backup\lib\site-packages\IPython\core\oinspect.py", line 738, in _get_info
    info_dict = self.info(obj, oname=oname, info=info, detail_level=detail_level)
  File "D:\miniconda3\envs\backup\lib\site-packages\IPython\core\oinspect.py", line 838, in info
    if info and info.parent and hasattr(info.parent, HOOK_NAME):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

There's no error when running in command line. So it is spyder related.

## Versions

* Numpy version: 1.24.2
* Spyder version: 5.4.2
* Python version: 3.10.10
* Qt version: 5.15.8
* PyQt version: 2.3.1
* Operating System name/version: Windows 11

**Comment by ccordoba12** [comment]
Hey @3zhang, thanks for reporting. This is an error in IPython, not in Spyder and it'll be fixed in its next version.

For now, please downgrade IPython to its 8.7.0 version by opening the Miniconda Prompt and running there with the commands:

    conda activate backup
    conda install ipython=8.7.0

If you used Conda-forge to create your environment, you need to change the last command to be

    conda install -c conda-forge ipython=8.7.0

**Comment by 3zhang** [comment]
> Hey @3zhang, thanks for reporting. This is an error in IPython, not in Spyder and it'll be fixed in its next version.
> 
> For now, please downgrade IPython to its 8.7.0 version by opening the Miniconda Prompt and running there with the commands:
> 
> ```
> conda activate backup
> conda install ipython=8.7.0
> ```
> 
> If you used Conda-forge to create your environment, you need to change the last command to be
> 
> ```
> conda install -c conda-forge ipython=8.7.0
> ```

I rolled back to 8.10.0 and it works.
