### ISSUE TITLE
Running terminal commands in Spyder's IPython

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#20795]
I notice I can run `conda install` from within Spyder's IPython console, among other things like `pwd`. But not everything is supported, e.g. [`youtube-dl`](https://github.com/ytdl-org/youtube-dl/), which is a `.exe`.

Is there a way to do this, like a list of commands somewhere I can append custom commands to? If it would be easy to implement, I'd like it considered a feature request, but it's very low priority.

**Comment by dalthviz** [comment]
Hi @OverLordGoldDragon, thanks for the feedbacl! Not totally sure but maybe what you are looking for is the [`!` magic](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-sc)? With that you can call a command and get its output. For example, I have the `dot` command which is not recognized initially but adding `!` I can get the help info about it:

![image](https://user-images.githubusercontent.com/16781833/231600203-e2909166-2572-4f70-9360-c6b335212972.png)

Let us know if the info above helps!

**Comment by OverLordGoldDragon** [comment]
Ahh gaps in my basic knowledge strike again.

Does Spyder have a "cool stuff you can do with Spyder" page, with short tricks like this? I think that'd be really neat.

**Comment by dalthviz** [comment]
> Does Spyder have a "cool stuff you can do with Spyder" page, with short tricks like this?

I think the Spyder docs have a page related with the IPython console but there we only link to the IPython documentation from what I saw :thinking: https://docs.spyder-ide.org/current/panes/ipythonconsole.html . There is also the FAQ page (https://docs.spyder-ide.org/current/faq.html) but maybe a more specific page for Spyder usage tips could be worthy?

**Comment by ccordoba12** [comment]
There's also basic help about IPython in the Spyder's menu `Help > IPython documentation`.
