### ISSUE TITLE
Spyder internal error

### ISSUE THREAD

**Issue by leskin** [spyder-ide/spyder#20793]
### What steps will reproduce the problem?

I had simply started spyder when the error occurred. An internal error occurred due to the content variable being undefined in line 331 of container.py when spyder was checking for updates

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\hakom\AppData\Local\pypoetry\Cache\virtualenvs\snofox-OV6lvsi--py3.11\Lib\site-packages\spyder\plugins\application\container.py", line 331, in _check_updates_ready
    msg = header + content + footer
                   ^^^^^^^
UnboundLocalError: cannot access local variable 'content' where it is not associated with a value
```

## Versions

* Spyder version: 5.4.2  (pip)
* Python version: 3.11.1 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.8
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                     :  1.4.1 (OK)
chardet >=2.0.0                          :  5.1.0 (OK)
cloudpickle >=0.5.0                      :  2.2.1 (OK)
cookiecutter >=1.6.0                     :  2.1.1 (OK)
diff_match_patch >=20181111              :  20200713 (OK)
intervaltree >=3.0.2                     :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0                  :  8.9.0 (OK)
jedi >=0.17.2;<0.19.0                    :  0.18.2 (OK)
jellyfish >=0.7                          :  0.9.0 (OK)
jsonschema >=3.2.0                       :  4.17.3 (OK)
keyring >=17.0.0                         :  23.13.1 (OK)
nbconvert >=4.0                          :  7.2.9 (OK)
numpydoc >=0.6.0                         :  1.5.0 (OK)
paramiko >=2.4.0                         :  3.0.0 (OK)
parso >=0.7.0;<0.9.0                     :  0.8.3 (OK)
pexpect >=4.4.0                          :  4.8.0 (OK)
pickleshare >=0.4                        :  0.7.5 (OK)
psutil >=5.3                             :  5.9.4 (OK)
pygments >=2.0                           :  2.14.0 (OK)
pylint >=2.5.0;<3.0                      :  2.15.10 (OK)
pylint_venv >=2.1.1                      :  2.3.0 (OK)
pyls_spyder >=0.4.0                      :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0                     :  1.7.1 (OK)
pylsp_black >=1.2.0                      :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0                :  3.0.3 (OK)
qstylizer >=0.2.2                        :  0.2.2 (OK)
qtawesome >=1.2.1                        :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0                 :  5.4.0 (OK)
qtpy >=2.1.0                             :  2.3.0 (OK)
rtree >=0.9.7                            :  1.0.1 (OK)
setuptools >=49.6.0                      :  67.0.0 (OK)
sphinx >=0.6.6                           :  6.1.3 (OK)
spyder_kernels >=2.4.2;<2.5.0            :  2.4.2 (OK)
textdistance >=4.2.0                     :  4.5.0 (OK)
three_merge >=0.1.1                      :  0.1.1 (OK)
watchdog >=0.10.3                        :  2.2.1 (OK)
zmq >=22.1.0                             :  25.0.0 (OK)

# Optional:
cython >=0.21                            :  None (NOK)
matplotlib >=3.0.0                       :  None (NOK)
numpy >=1.7                              :  1.24.1 (OK)
pandas >=1.1.1                           :  1.5.3 (OK)
scipy >=0.17.0                           :  None (NOK)
sympy >=0.7.3                            :  None (NOK)

# Spyder plugins:
spyder_line_profiler.spyder.plugin 0.3.1 :  0.3.1 (OK)
spyder_unittest.unittestplugin 0.5.1     :  0.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @leskin, thanks for reporting and sorry for the inconvenience. This is fixed in our latest version (5.4.3), so please update to it.

**Comment by leskin** [comment]
Chris:

Thanks for the quick reply! You beat me to the punch. I updated to 5.4.3 and was going to check that file location to see if I could work up a fix but glad to hear it is already fixed! Spyder is an awesome product.  Keep up the good work and I’ll try to find some time to help with some bug fixes in the future.

//Leo

____________________________________________
Leo D. Eskin, Ph.D.
President/CEO
Cogent Science, LLC
13401 Chestnut Oak Drive
Darnestown, MD  20878
Phone:   +1 703 929-5500
FAX:     +1 240 206-3273
SkypeIN: +1 301 358-5201
Skype:   leskin1
***@***.*** ***@***.***>
www.cogentscience.net

 <http://www.cogentscience.net/>The information contained in this communication may be confidential,
is intended only for the use of the recipient named above, and may be legally privileged.
If the reader of this message is not the intended recipient, you are hereby notified that
any dissemination, distribution, or copying of this communication, or any of its contents,
is strictly prohibited.  If you have received this communication in error, please
re-send this communication to the sender and delete the original message and any
copy of it from your computer system.  Thank you.

**Comment by ccordoba12** [comment]
Great! Thanks for your interest in contributing to Spyder.
