### ISSUE TITLE
Incorrect line numbers displayed after line wrapping in the source code editor

### ISSUE THREAD

**Issue by TBSenseo** [spyder-ide/spyder#20802]
I have a very long source code (I am unlikely allowed to share it), where the source code lines keep counting upwards even so the line is wrapped over. The displayed line numbers also end prematurely. When placing the cursor into any line after the wrapping, it shows a different line number than the line number displayed before:
![image](https://user-images.githubusercontent.com/50355793/231104461-9f154a5c-596a-4a9e-acfa-4e7b1b6c3b52.png)
Is there a defect in the skipping of the lines following wrap overs for the line numbers display component?

The info about my Spyder version (Installed and updated with pip starting from a standard Python distribution):
![image](https://user-images.githubusercontent.com/50355793/231104921-7054f499-e335-4c82-957a-cd00f17880b6.png)

_Originally posted by @TBSenseo in https://github.com/spyder-ide/spyder/issues/20308#issuecomment-1502917160_

**Comment by dalthviz** [comment]
Hi @TBSenseo thank you for the feedback! I think I was able to reproduce this! The wrap lines feature is doing something strange with the line number panels indeed!

We will try to fix this in a future release :+1:
