### ISSUE TITLE
Non-sticky Var Explorer

### ISSUE THREAD

**Issue by MPaaske** [spyder-ide/spyder#20865]
### What steps will reproduce the problem?

Running code.

Before I updated to Spyder 5.4.3 I had a stick Var Explorer, but now, it flushes all Vars when the code is done running. I would like my Sticky Var Explorer back please. :)

![Spyder Var Sticky 01](https://user-images.githubusercontent.com/30037748/234060593-1fa3c976-43d7-42d9-ac92-0da63c87c1b0.JPG)

As shown the Var Explorer is loaded when the program is running (in debug mode here)

![Spyder Var Sticky 02](https://user-images.githubusercontent.com/30037748/234060598-0f509fae-7f52-4451-8911-299c15d7a23f.JPG)

And when the code terminates, it flushes the Var Explorer and its no longer possible to see the Var values..
![Spyder Var Sticky 03](https://user-images.githubusercontent.com/30037748/234060599-e1e40157-f18b-417a-803f-d06930305131.JPG)

## Versions

* Spyder version: 5.4.3  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree                                     :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.1.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.6.1 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog                                         :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.34 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2             :  1.2.2 (OK)
```

**Comment by MPaaske** [comment]
Hey Carlos

I tried adding some images, hopes this helps.

**Comment by ccordoba12** [comment]
@MPaaske, unfortunately it's not possible to attach files to your Github replies via email. Instead, you need to drag and drop your images here.

**Comment by MPaaske** [comment]
![Spyder Var Sticky 03](https://user-images.githubusercontent.com/30037748/234317576-b55350fa-b266-4f34-9d96-ab2af6863d30.JPG)
![Spyder Var Sticky 01](https://user-images.githubusercontent.com/30037748/234317589-65c22a22-415b-4f5d-a3b0-dda7c2a24402.JPG)
What I'm looking for, is for the Var values "stick" with the final values of the Vars (like in the image above), even when the code is done running, at this moment, it flushes the Var Explorer and there's no data left. At this moment I only get to examen the Var Values in the Explorer when the code is actively running.
![Spyder Var Sticky 02](https://user-images.githubusercontent.com/30037748/234317594-e753a2cd-9eaa-4c67-877b-d08d3a67a734.JPG)

**Comment by ccordoba12** [comment]
So, what you're saying is that the Variable explorer is not updated after you run a file? Instead, that happens only when you're debugging it?

**Comment by MPaaske** [comment]
> 

Yes.

**Comment by ccordoba12** [comment]
Ok, I'd suggest to go to the menu

    Tools > Reset Spyder to factory defaults

and try again. That could solve your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
