### ISSUE TITLE
Spyder doesn't read ipython_config.py?

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2087]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2014-12-14T17:21:28Z_

I setup the following to enable autoreload in that file, but it doesn't seem to take effect:

c.InteractiveShellApp.extensions = ['autoreload']
c.InteractiveShellApp.exec_lines = ['&#37;autoreload 2']

Specifically, this is set in C:\WinPython-64bit-2.7.9.1\settings\.ipython\profile_default\ipython_config.py

However, this works at the iPython console inside Spyder:

In [1]: &#37;load_ext autoreload

In [2]: &#37;autoreload 2

Perhaps that isn't the right file to put these in - if not, where?

Spyder Version:  2.3.2
Python Version:  2.7.9
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2087_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-15T09:06:57Z_

We do try to read IPython settings, so I don't know what's happening in this case. I'll take a look at this one for 2.3.3.

**Summary:** Spyder doesn't read ipython_config.py?  \<span class="oldvalue"> (was: Spyder doesn't read C...\settings\.ipython\profile_default\ipython_config.py?) \</span>  
  **Labels:** Cat-IPythonConsole MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T20:19:28Z_

This is working as expected for me on Linux.

Please bring the issue with the WinPython guys to see what they think about it. It's probably a mismatch with the place IPython thinks its config settings are stored.

**Status:** WontFix  
  **Labels:** -MS-v2.3.3

**Comment by endolith** [comment]
I have this too, with Python 2.7.10, IPython 2.4.1, Spyder 2.3.5.2, installed using Python(x,y)-2.7.10.0.  If I open IPython QT or IPython shortcuts, it loads future division, for instance, but the IPython window inside Spyder doesn't load any of my config.
