### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Lee706** [spyder-ide/spyder#20879]
Hello Professor! I have also encountered the same problem. May I ask what the solution is? thank you very much 

_Originally posted by @dalthviz in https://github.com/spyder-ide/spyder/issues/15925#issuecomment-888107565_

**Comment by Lee706** [comment]
OverflowError                             Traceback (most recent call last)
<ipython-input-140-c2eff747db17> in <module>()
      1 #调整超参数
      2 data_df = data_df.astype('float64')
----> 3 tuned_parameters = hyperparameter_tuning(model_type, x_train, y_train, num_of_folds, scaler_option, n_iter=1, random_state=0, verbose=1)

<ipython-input-2-6f83a2b0689d> in hyperparameter_tuning(tag, x_train, y_train, num_of_folds, scaler_option, n_iter, random_state, verbose)
    997         y_train_ = y_train.reshape(y_train.shape[0],)
    998 
--> 999         model.fit(x_train_, y_train_)
   1000 
   1001         tuned_parameters = add_key_to_params(tag, model.best_params_)

C:\Users\Lee\.conda\envs\py36\lib\site-packages\sklearn\utils\validation.py in inner_f(*args, **kwargs)
     61             extra_args = len(args) - len(all_args)
     62             if extra_args <= 0:
---> 63                 return f(*args, **kwargs)
     64 
     65             # extra_args > 0

C:\Users\Lee\.conda\envs\py36\lib\site-packages\sklearn\model_selection\_search.py in fit(self, X, y, groups, **fit_params)
    839                 return results
    840 
--> 841             self._run_search(evaluate_candidates)
    842 
    843             # multimetric is determined here because in the case of a callable

C:\Users\Lee\.conda\envs\py36\lib\site-packages\sklearn\model_selection\_search.py in _run_search(self, evaluate_candidates)
   1633         evaluate_candidates(ParameterSampler(
   1634             self.param_distributions, self.n_iter,
-> 1635             random_state=self.random_state))

C:\Users\Lee\.conda\envs\py36\lib\site-packages\sklearn\model_selection\_search.py in evaluate_candidates(candidate_params, cv, more_results)
    785                                     more_results=None):
    786                 cv = cv or cv_orig
--> 787                 candidate_params = list(candidate_params)
    788                 n_candidates = len(candidate_params)
    789 

C:\Users\Lee\.conda\envs\py36\lib\site-packages\sklearn\model_selection\_search.py in __iter__(self)
    290                 n_iter = grid_size
    291             for i in sample_without_replacement(grid_size, n_iter,
--> 292                                                 random_state=rng):
    293                 yield param_grid[i]
    294 

sklearn\utils\_random.pyx in sklearn.utils._random.sample_without_replacement()

OverflowError: Python int too large to convert to C long

**Comment by dalthviz** [comment]
Hi @Lee706 ,  I think this problem goes beyond Spyder so there is not much we can do to help from the Spyder side, sorry :/ However, searching a little bit, maybe this SO post could be helpful: https://stackoverflow.com/a/64901335

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing since is not directly related with Spyder
