### ISSUE TITLE
Spyder 3.7 not working on MacOS

### ISSUE THREAD

**Issue by Dexter010** [spyder-ide/spyder#20883]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @Dexter010 could you provide more info about your setup (Spyder version, way you installed Spyder, dependencies, etc) as well as a more specific description of the error you are experiencing? Without such information there is not much we can do to help, sorry :/

Let us know if you can share more info with us!
