### ISSUE TITLE
False Code Analysis Errors (pyflakes e) when using lambda

### ISSUE THREAD

**Issue by loewenm** [spyder-ide/spyder#20897]
## Problem Description

IDE's _code analysis_ suggests an "undefined name/variable" when said name is used within a lambda function.

This is not a runtime error that presents the code from executing. In fact, the code works perfectly. This is a simple error flag from the IDE's _code analysis_ feature.

### What steps reproduce the problem?

1.  Use the following python code in the IDE.
2.  Look along the right-side of the code for a little red dot indicating a code analysis error (i.e. right next to the lambda function).
3.  Code analysis error should state that a previously stated variable name is undefined (i.e. ffill_cols)

`
ffill_cols = [
        'CSHFDQ',
        'CSHOQ',
        'DLTTQ',
        'DPQ',
        'PPENTQ',
        'PSTKQ',
        'MIBTQ',
        ]

interpolated_values = data.groupby('GVKEY', group_keys=False).apply(lambda group: group[ffill_cols].interpolate(method='linear')).copy()
`

### What is the expected output? What do you see instead?

No code analysis error flag.

### Paste Traceback/Error Below (if applicable)

N/a

## Versions

* Spyder version: 5.4.1
* Python version: 3.8.16
* Qt version: n/a
* PyQt version:  n/a
* Operating System name/version: Windows 11

**Comment by ccordoba12** [comment]
Hey @loewenm, thanks for reporting. I can't reproduce this error on my side. I don't get any error related to the `ffill_cols` variable in the editor.

Could you update to our latest version (5.4.3) and try again? Thanks!

**Comment by loewenm** [comment]
Upgraded to v5.4.3 and checked, unfortunately it's still there.

![image after upgrading to spyder v5_4_3](https://user-images.githubusercontent.com/19495222/236922616-c91f0030-58ec-41a5-8d2f-3358db767bdb.png)

I have that line of code inside a very basic function.

This is strange...

**Comment by ccordoba12** [comment]
> This is strange...

Agreed. Could you post the entire code of your `clean_compustat_data` (as plain text) function here? That way I could check it on my side.

**Comment by loewenm** [comment]
My apologies [ccordoba12](https://github.com/ccordoba12) - I was away after opening this issue.

I've included a cleaned-up basic version of this file to this message that includes the error pyflakes code analysis error.

--- Code ---
```
def clean_compustat_data(data):
    
    # Interpolate fields where appropriate
    ffill_cols = [
        'col1',
        'col2',
        ]
    interpolated_values = data.groupby('GVKEY', group_keys=False).apply(lambda group: group[ffill_cols].interpolate(method='linear')).copy()

    del ffill_cols, interpolated_values

    return interpolated_values

#%% Main
if __name__ == '__main__':
    print('Hello world!')

```
--- End Code ---

Please let me know if you see this error when copy/pasting this into the Spyder IDE. Thank you.

**Comment by ccordoba12** [comment]
@loewenm, thanks for your answer. I was able to reproduce your problem:

![imagen](https://github.com/spyder-ide/spyder/assets/365293/efeea59a-a145-48a2-b492-05492e328d8b)

but the problem is not the `lambda`, is the `del` statement on line `13`. If I comment it, then the errors disappear:

![imagen](https://github.com/spyder-ide/spyder/assets/365293/6c137898-2f07-434a-8259-d449700b7a3d)

If really need that statement, then you can add a `# noqa` comment next to the lines with errors so that Spyder doesn't display them:

![imagen](https://github.com/spyder-ide/spyder/assets/365293/c5b4af0b-421d-4c0a-92c0-a73d2e6caa8c)

Let us know if we can help you with something else.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
