### ISSUE TITLE
Spyder Python 3 Mac app crashes on startup on OS X 10.9.5

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2089]
_From [pauldur...@gmail.com](https://code.google.com/u/114809488004188207176/) on 2014-12-16T22:31:57Z_

Spyder Version:  2.3.2
Python Version:  3.4.1
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.1 on Darwin
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.3 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK) 

What steps will reproduce the problem?

 1. Download spyder-2.3.2-py3.4.dmg, open image file and drag Spyder app into /Applications directory
2. Click Spyder to start
3. When Spyder window appears OS X crash reporter appears - and python never seems to load in the Spyder instance 

What is the expected output? What do you see instead?

 

Please provide any additional information below

. I'd be happy to provide more diagnostic information if required

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2089_

**Comment by spyder-issues-migrator** [comment]
_From [pauldur...@gmail.com](https://code.google.com/u/114809488004188207176/) on 2014-12-16T19:33:08Z_

And here is the problem report console entry:

Process:         Spyder [9500]
Path:            /Applications/Spyder.app/Contents/MacOS/Spyder
Identifier:      Spyder
Version:         ???
Code Type:       X86-64 (Native)
Parent Process:  Spyder [9494]
Responsible:     Spyder [9494]
User ID:         40336

Date/Time:       2014-12-16 19:32:17.565 -0800
OS Version:      Mac OS X 10.9.5 (13F34)
Report Version:  11
Anonymous UUID:  2E061593-5750-6A57-3BCB-B5BC97CCD229

Sleep/Wake UUID: 8E82AEFD-61C8-4030-9B8D-D16BDB1681DE

Crashed Thread:  Unknown

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00007fff5fc01028

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000e  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000 r8 : 0x0000000000000000 r9 : 0x0000000000000000 r10 : 0x0000000000000000 r11 : 0x0000000000000000 r12 : 0x0000000000000000 r13 : 0x0000000000000000 r14 : 0x0000000000000000 r15 : 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0x00007fff5fc01028
  
Logical CPU:     6
Error Code:      0x00000014
Trap Number:     14


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 24966
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro8,2, BootROM MBP81.0047.B27, 4 processors, Intel Core i7, 2.3 GHz, 8 GB, SMC 1.69f4
Graphics: Intel HD Graphics 3000, Intel HD Graphics 3000, Built-In, 512 MB
Graphics: AMD Radeon HD 6750M, AMD Radeon HD 6750M, PCIe, 1024 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353237334448302D4348392020
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1333 MHz, 0x80CE, 0x4D34373142353237334448302D4348392020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xD6), Broadcom BCM43xx 1.0 (5.106.98.100.22)
Bluetooth: Version 4.2.7f3 14616, 3 services, 23 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: Crucial_CT960M500SSD1, 960.2 GB
Serial ATA Device: MATSHITADVD-R   UJ-8A8
USB Device: FaceTime HD Camera (Built-in)
USB Device: Hub
USB Device: BRCM2070 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Hub
USB Device: IR Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.1

**Comment by spyder-issues-migrator** [comment]
_From [gentoo...@gmail.com](https://code.google.com/u/114905753294657218971/) on 2014-12-18T04:36:07Z_

Same problem here. OS X 10.9.5, Spyder 2.3.2 
Python 3.4.1 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.1 on Darwin

Thanks in advance,
Matteo

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-18T13:30:39Z_

Thanks for reporting. Are your macs 32 or 64 bits?

**Labels:** Cat-IPythonConsole MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [gentoo...@gmail.com](https://code.google.com/u/114905753294657218971/) on 2014-12-18T22:47:33Z_

Hi, I have the same  model of MacBook and same OSX version, so I can reply. It's 64 bits.

**Comment by spyder-issues-migrator** [comment]
_From [pauldur...@gmail.com](https://code.google.com/u/114809488004188207176/) on 2014-12-31T15:48:09Z_

ccordoba12 did you require any additional information here?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T14:24:32Z_

I really don't know what's happening. I tried the app in a Mac 10.9.5 and it starts just fine. The only failure is that it's not possible to open Python nor IPython consoles.

I'll see what I can do about it for 2.3.3

**Summary:** Spyder Python 3 Mac app crashes on startup on OS X 10.9.5  \<span class="oldvalue"> (was: Spyder2.3.2-py3 crashes on startup on OS X 10.9.5) \</span>

**Comment by spyder-issues-migrator** [comment]
_From [laur...@laurentroger.com](https://code.google.com/u/112341471159472376007/) on 2015-01-24T03:09:26Z_

Save for me OSX 10.8.5

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T20:30:30Z_

**Labels:** -MS-v2.3.3 MS-v2.3.4

**Comment by ccordoba12** [comment]
Let's merge this one with #2171
