### ISSUE TITLE
Feature Request: Option to Hide the Status Bar

### ISSUE THREAD

**Issue by 500apes** [spyder-ide/spyder#20917]
Using sypder on a small laptop requires maximising the usable screen area. Can there be an  option added to disable the Status Bar to help achieve this?

**Comment by dalthviz** [comment]
Hi @500apes thank you for the feedback! Just in case, have you tried to use the `Fullscreen mode` (`View > Fullscreen mode` or `F11`). If that still is not enough, for the moment something you can do to manually hide the statusbar is running from the internal console pane something like: `spy.window.statusBar().hide()`. To show again the statusbar, you will need to run from the internal console pane something like: `spy.window.statusBar().show()`

Let us know if the info above helps! Also, what do you think about this @spyder-ide/core-developers ?

**Comment by 500apes** [comment]
That worked great - Thank you! 

I know it doesn't seem like much but on a small laptop every bit of working space helps

**Comment by ccordoba12** [comment]
A way to permanently disable the status bar is by going to the menu

    Tools > Preferences > Plugins

and disabling the `Status bar` plugin:

![image](https://github.com/spyder-ide/spyder/assets/365293/0c592ba0-904f-484d-b9c2-7c73615d66e6)
