### ISSUE TITLE
PyQt5.QtWebEngineWidgets 

### ISSUE THREAD

**Issue by gulcanyildiz** [spyder-ide/spyder#20911]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by dalthviz** [comment]
Hi @gulcanyildiz , could it be possible for you to share your setup info (OS, Python version, Spyder, PyQt version, installation method, etc)? Without more information there is not much we can do besides suggesting you to check if you have the latest Spyder version installed (5.4.3) and to give it a check to the Spyder troubleshooting guide: https://docs.spyder-ide.org/current/troubleshooting/index.html

Let us know if something of the above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
