### ISSUE TITLE
Cannot use Python3.9 in Spyder on Ubuntu 20.04

### ISSUE THREAD

**Issue by eafpres** [spyder-ide/spyder#20939]
## Problem Description

I have Ubuntu 20.04 in WSL2 under Windows 11 Pro.  I have installed both Python3.8 and Python3.9.  Typically I use update-alternatives to set the default Python version.  I am trying to run Spyder and use Python3.9. Although Python3.9 is configured as the default, Spyder launches with Python3.8. I have tried to change the Python Interpreter path to my Python3.9 directory, but then I get a series of dependency missing issues when it tries to connect to the kernel, and I cannot use it.  Running Spyder from the Linux terminal works fine, but it is in Python3.8.  

If I use which Python3.9 in Linux, it shows /usr/bin/python3.9; likewise if I use which Python3.8, it shows /usr/bin/Python3.8.  

If I put /usr/bin/Python3.9 in the IPython interpreter field in Spyder Preferences, I get things like this:

![image](https://github.com/spyder-ide/spyder/assets/30508983/a878a681-3e0e-4551-9de5-e34387cf2443)

Note that I would rather it just used Python3.9.  On previous installs on other machines this was not a problem. I'm unclear why this is happening in this instance.

### What steps reproduce the problem?

1.  In Ubuntu 20.04:
```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt update
sudo apt install python3.9
sudo update alternatives  --install /usr/bin/python python /usr/bin/python3.8 1
sudo update alternatives --install/usr/bin/python python /usr/bin/python3.9 2
sudo update-alternatives --config python
choose the option to use python 3.9
python
Python 3.9.16 (main, Dec  7 2022, 01:11:51)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
quit()
```
2. spyder
![image](https://github.com/spyder-ide/spyder/assets/30508983/92931314-8ca7-4fee-91f8-7cbed3e6179b)

3. Tools > Preferences > Python interpreter > use the following Python interpreter: /usr/bin/python3.9 OK
4. File > Quit
5. spyder
![image](https://github.com/spyder-ide/spyder/assets/30508983/533ea30f-8892-427b-9be8-cf21096615a9)

Note that in both cases above, it shows Python 3.9.16 in the lower bar, but is using 3.8.10 in the console

### What is the expected output? What do you see instead?

Either (A) run spyder and it uses Python3.9, or (B) not get dependency errors trying to set the interpreter via Preferences

### Paste Traceback/Error Below (if applicable)

```python-traceback

see above

```

## Versions
Python 3.8.10 64-bit 
Qt 5.12.8 
PyQt5 5.14.1 
Linux 5.15.90.1-microsoft-standard-WSL2 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  3.0.4 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20230430 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  3.2.0 (OK)
keyring >=17.0.0                                 :  18.0.1 (OK)
nbconvert >=4.0                                  :  7.4.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.6.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.5 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.17.4 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.3 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.3 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.7.2 (OK)
sphinx >=0.6.6                                   :  7.0.1 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
xdg >=0.26                                       :  0.28 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.23.5 (OK)
pandas >=1.1.1                                   :  2.0.1 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  None (NOK)
```
As a final note, by the way, the debian installer installs a 3.x version of Spyder...

**Comment by eafpres** [comment]
I should add, than when I run spyder, I get:
eafpres@EAFLLCML:~$ spyder
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid

Also, even when just using the default interpreter, it takes a really long time for spyder to connect to the kernel and become active

**Comment by eafpres** [comment]
Update--I was able to "solve" this by:

$python3.9 -m pip install spyder

I still get the:
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid

on startup

**Comment by ccordoba12** [comment]
> If I put /usr/bin/Python3.9 in the IPython interpreter field in Spyder Preferences, I get things like this:

That shows that you're mixing system packages (i.e. those provided by your Linux distro) with others installed with pip, which is a bad practice given that the two sets are incompatible.

So, I'd recommend you to remove `/home/eafpress/.local/lib/python3.9` (and `/home/eafpress/.local/lib/python3.8`, if you have it as well) and use virtualenvs instead (as described in [our documentation](http://docs.spyder-ide.org/current/installation.html#using-pip)). That's a much better way to work because you'll still be able to use your system Python (as it seems that you want to) but in a completely isolated environment (i.e. you'll have to install everything with pip, instead of mixing pip and system packages).

> Update--I was able to "solve" this

Ok, that's good to know.

> I still get the:
> libpng warning: bKGD: invalid
> libpng warning: bKGD: invalid
> 
>on startup

That's just a warning, so you can safely ignore it.

**Comment by ccordoba12** [comment]
I'm going to close this issue since there's no much else we can do about it.
