### ISSUE TITLE
Spyder presents many problems when i install anaconda in D disk

### ISSUE THREAD

**Issue by david021903** [spyder-ide/spyder#20956]
Hello, may problems were encountered:

When creating a new env in anaconda and installing spyder, at launch of spyder installing errors appears, sayingthat some dependencies were not installed, also the last eror was trying to install python=3.7 since following anaconda prompot, mysql-connector needed such requiements, i couldn't install it again for internal conda errors,i tried to restart my pc and this roblem was encountered (Spyder is broken)

![image](https://github.com/spyder-ide/spyder/assets/86127726/56a63115-9f14-4c87-b9c5-6de0ded2020f)

**Comment by dalthviz** [comment]
Hi @david021903 , could you try to create a conda environment using the Anaconda prompt and running there something like: `conda create -n spyder-df -c conda-forge python=3.7 spyder mysql-connector-python` 

Then, to launch Spyder, you can activate the new env and run from the Anaconda prompt something like:

    conda activate spyder-df 
    spyder

Also, after creating the env, you should be able to launch Spyder from a menu shortcut. For that, click the start menu and search for `Spyder (spyder-df)`

Let us know if creating a new env helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
