### ISSUE TITLE
Feature Request: Add option to lock window/pane layout

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2096]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2014-12-29T14:22:36Z_

There should be an option to lock the window (panel, pane, widget, whatever you want to call it) layout so that accidental click-and-drag actions do not move windows around.

The most common case, at least for me, is going up to close a tab on the editor and accidentally moving it somewhere else.

If someone shows me where to look, I might be able to patch in this feature. I'd probably just add a checkmark menu item to the View menu.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2096_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-01T13:50:50Z_

I agree, I myself messed the layout up by clicking and dragging too quickly in our input panes.

**Labels:** MS-v2.3.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-08T15:14:59Z_

**Labels:** -MS-v2.3.3 MS-v2.4

**Comment by dougthor42** [comment]
Adding comment so that I get notifications and so that I can find my issues/comments more easily.

**Comment by goanpeca** [comment]
I already had this worked out. 

@ccordoba12 agrees on putting this option under the `close current pane` in the View menu? and adding this off by default?
