### ISSUE TITLE
Syntax highlight new Python 3.10 statements is missing

### ISSUE THREAD

**Issue by TBSenseo** [spyder-ide/spyder#20963]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I started to use the new structural pattern matching statement that is introduced with Python 3.10 (See https://docs.python.org/3.10/whatsnew/3.10.html#pep-634-structural-pattern-matching), I noticed that the syntax highlighting of the "match" and the "case" part is not right. I think the Spyder components should be updated to support the new Python 3.10 statements.

### What steps reproduce the problem?

Take an existing Python script or make a new one and insert 
```python
import time as tm

for idx in range(5):
	match idx:
		case 0:
			print('First phase')
		case 1:
			print('Second phase')
		case 2:
			print('Taking a break')
			tm.sleep(3)
		case 3:
			print('Third phase')
		case _:
			print(f'{idx}-th phase')

``` 

### What is the expected output? What do you see instead?

The expected output is that in the code "match" and "case" and "_" are highlighted the same as the usual statements like "class" and "if". Currently they are highlighted as if they were variable names.

## Versions

* Spyder version: 5.4.3  (pip)
* Python version: 3.10.11 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
No special dependencies this time.
```

**Comment by ccordoba12** [comment]
Hey @TBSenseo, thanks for reporting. You're totally right, we need to add those new builtins to our syntax highlighter code.

We'll do that for our next version (5.4.4), to be released in a couple of weeks.

**Comment by ccordoba12** [comment]
One additional comment about what you said:

> The expected output is that in the code "match" and "case" and "_" are highlighted the same as the usual statements like "class" and "if"

We can't highlight `_` because that can be used as a variable name. Furthermore, you can see that it was not highlighted differently in the code you posted above.
