### ISSUE TITLE
Inspecting dataframes in the debugger is much faster than doing it in the IPython console

### ISSUE THREAD

**Issue by AmerM137** [spyder-ide/spyder#20962]
Hello,

First I would like to thank the Spyder dev team for their great work maintaining Spyder.

## Problem Description

I've been using Spyder for 4+ years and it has always had some "lag" in the built-in console after submitting code. It's more noticeable when trying to get the representation of a dataframe even when the pandas display settings are adjusted appropriately for truncation (example: see only the first 25 rows of a large dataframe). I know that the console has to print the text and what not, but it seems that the amount of lag is disproportional to the amount of text printed, particularly when comparing it to running ipython in a stand-alone terminal.

While using Spyder, I recently started using ipdb more for debugging code as my projects have grown larger, and I've noticed a significant reduction in response time while in the debugger. If I have a dataframe df that I want to see the representation of, it would take (~) 200 ms to show the output of the df in the built in console while it's basically instant in the debugger console. Basically, every action in the debugger feels much more responsive. It's significant enough to notice without putting any numbers to it.

I am running this on a beefy workstation with an Intel i9-10980XE that boosts to 4.5ghz+. I also notice this on my gaming pc which is running an overclocked 11900k running at 5ghz all cores.

### What steps reproduce the problem?

1. Start Spyder and run some simple script with a few functions that return a dataframe or any object that has a rich repr in ipython
2. Inspect the object using the built in console, just calling the object itself should give an indication of the latency involved
3. Set breakpoint in one of the functions to debug the inner scope, once inside ipdb, call the object again and notice the significant speed up in the console display

In addition, trying the same thing in the standalone jupyter qtconsole outside Spyder, it feels much faster and much more responsive. Just fire up a qtconsole session from the native shell and you notice the reduced response time.

For me, the main value add for Spyder is the interactive editor<-->console workflow. To be honest, I don't have time to figure out how to recreate the same thing in VSCode/Neovim/etc. However, any time I am in one of those editors, I cannot but notice the significant speedup in the python console compared to Spyder.

Is this something that can be looked into? Why would the debugger console be much more responsive? Can the same level of responsiveness be achieved with the built-in qtconsole?

## Versions
* Spyder version: 5.4.3  (conda)
* Python version: 3.10.9 64-bit
* Qt version: 5.15.4
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.0 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.0.2 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.11.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.16.0 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.0.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.0.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.2 (OK)
pygments >=2.0                                   :  2.13.0 (OK)
pylint >=2.5.0,<3.0                              :  2.15.3 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.3 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.0 (OK)
rtree >=0.9.7                                    :  1.0.0 (OK)
setuptools >=49.6.0                              :  67.4.0 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.3.1 (OK)
zmq >=22.1.0                                     :  24.0.1 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.6.2 (OK)
numpy >=1.7                                      :  1.23.3 (OK)
pandas >=1.1.1                                   :  1.5.0 (OK)
scipy >=0.17.0                                   :  1.9.1 (OK)
sympy >=0.7.3                                    :  None (NOK)

**Comment by ccordoba12** [comment]
Hey @AmerM137, thanks for reporting and your kind words about Spyder! You said:

> Start Spyder and run some simple script with a few functions that return a dataframe or any object that has a rich repr in ipython

Could you post a script example that displays this problem? That way we could test it on our side and better understand what's happening.

> Inspect the object using the built in console, just calling the object itself should give an indication of the latency involved

What operation are you using to inspect the dataframe? Just `df.head()`? Or something else?

> For me, the main value add for Spyder is the interactive editor<-->console workflow. To be honest, I don't have time to figure out how to recreate the same thing in VSCode/Neovim/etc. However, any time I am in one of those editors, I cannot but notice the significant speedup in the python console compared to Spyder.

I understand your frustration. The difference between Spyder and other editors/IDEs is that we have several pieces of code that run after each execution in the console to update the Variable Explorer, the current working directory, etc. And I think one or more of those things are responsible for the lag you're observing.

> Is this something that can be looked into?

Yeah, we'll take a look at it. The most important thing for us to be able to reproduce your problem locally, so we can investigate it.

> Why would the debugger console be much more responsive?

No idea. Actually, that's really surprising to me.

@impact27, do you know what could be happening here?

> Can the same level of responsiveness be achieved with the built-in qtconsole?

I don't think so because Qtconsole is way simpler and doesn't have all the integrations I mentioned above. But we can definitely try to improve the situation.

**Comment by AmerM137** [comment]
Here you go @ccordoba12

#%%

import itertools as it

import numpy as np
import pandas as pd

rng = np.random.default_rng()

#%%

size = 10000
categories = ["cat1", "cat2", "cat3", "cat5", "cat6", "cat7", "cate8", "cat9", "cat10"]
c1 = lambda: rng.normal(size=size)
c2 = lambda: rng.integers(0, 999, size=size)
c3 = lambda: rng.choice(categories, size=size)
label_fn = lambda x: f"col{x}"

d1 = {label_fn(i): c1() for i in range(15)}
d2 = {label_fn(i): c2() for i in range(15, 30)}
d3 = {label_fn(i): c3() for i in range(30, 45)}

# typical working dataframe with many numerical columns as well as string/categorical columns
df1 = pd.DataFrame(d1|d2|d3)

#%%

def func(df):
    """the func body does not matter here, we just need
    some function to use for the breakpoint"""
    
    mean = df.mean()
    stats = df.describe()
    # let's debug this code
    breakpoint()
    pivot = df1.groupby('col40')
    agg = pd.DataFrame(
        {"mean": pivot["col0"].mean(),
         "sum": pivot["col10"].sum(),
         "cat_stat": pivot["col15"].max(),
         })
    return agg

#%% Replicating the lag

# simply call df1 in the console
df1
df1.head()
df1.tail()
df1.max()
df1.info()

# break into debugger and do the same
# debugger is noticeably faster in displaying dataframes
func(df1)
df1
df1.head()
df1.tail()
df1.max()
df1.info()
mean
stats

# the faster the single threaded performance of the PC the less noticeable it is
# it's much more noticeable on an older laptop for example
# any native ipython/qtconsole session running in cmd/powershell feels more responsive

**Comment by ccordoba12** [comment]
@dalthviz, could you give me a hand to check this on Windows? Thanks!

**Comment by dalthviz** [comment]
Maybe I'm testing this in a wrong way but I was not able to reproduce (or maybe there is lag but I'm not being able to notice it 🤔). I checked running the code with Spyder 5.4.4 from a conda env with Python 3.10 and pandas 1.5.0 from conda-forge:

![debug](https://github.com/spyder-ide/spyder/assets/16781833/e00c8bf1-ef31-4dc6-9525-138f7ada7a3b)

 Env details:

<details>

```
# packages in environment at C:\Users\dalth\anaconda3\envs\spyder-cf-544-310-150:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
astroid                   2.15.6          py310h5588dad_0    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
atomicwrites              1.4.1              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
autopep8                  2.0.2              pyhd8ed1ab_0    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2           py310h8d17308_1    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
black                     23.7.0          py310h5588dad_1    conda-forge
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
brotli-python             1.0.9           py310h00ffb61_9    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_3    conda-forge
chardet                   5.1.0           py310h5588dad_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
click                     8.1.6           win_pyh7428d3b_0    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
cookiecutter              2.3.0              pyh1a96a4e_0    conda-forge
cryptography              41.0.3          py310h6e82f81_0    conda-forge
debugpy                   1.6.8           py310h00ffb61_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
diff-match-patch          20230430           pyhd8ed1ab_0    conda-forge
dill                      0.3.7              pyhd8ed1ab_0    conda-forge
docstring-to-markdown     0.12               pyhd8ed1ab_0    conda-forge
docutils                  0.20.1          py310h5588dad_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
flake8                    6.0.0              pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.76.4               h12be248_0    conda-forge
glib-tools                2.76.4               h12be248_0    conda-forge
gst-plugins-base          1.22.5               h001b923_0    conda-forge
gstreamer                 1.22.5               hb4038d2_0    conda-forge
icu                       72.1                 h63175ca_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagesize                 1.4.1              pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
inflection                0.5.1              pyh9f0ad1d_0    conda-forge
intel-openmp              2023.2.0         h57928b3_49496    conda-forge
intervaltree              3.1.0              pyhd8ed1ab_1    conda-forge
ipykernel                 6.25.1             pyh6817e22_0    conda-forge
ipython                   8.14.0             pyh08f2357_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     5.12.0             pyhd8ed1ab_1    conda-forge
jaraco.classes            3.3.0              pyhd8ed1ab_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jellyfish                 1.0.0           py310h87d50f1_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonschema                4.19.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1           py310h5588dad_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
keyring                   24.2.0          py310h5588dad_0    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lazy-object-proxy         1.9.0           py310h8d17308_0    conda-forge
libblas                   3.9.0              17_win64_mkl    conda-forge
libcblas                  3.9.0              17_win64_mkl    conda-forge
libclang                  16.0.6          default_heb8d277_1    conda-forge
libclang13                16.0.6          default_hc80b9e7_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.76.4               he8f3873_0    conda-forge
libhwloc                  2.9.2           nocuda_h15da153_1008    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libjpeg-turbo             2.1.5.1              hcfcfb64_0    conda-forge
liblapack                 3.9.0              17_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libsqlite                 3.42.0               hcfcfb64_0    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.3.1                hcfcfb64_0    conda-forge
libwebp-base              1.3.1                hcfcfb64_0    conda-forge
libxml2                   2.11.4               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py310h8d17308_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mistune                   3.0.0              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
mypy_extensions           1.0.0              pyha770c72_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.7.3              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.7.3              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.7.3              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.2              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
numpy                     1.25.2          py310hd02465a_0    conda-forge
numpydoc                  1.5.0              pyhd8ed1ab_0    conda-forge
openssl                   3.1.2                hcfcfb64_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    1.5.0           py310h1c4a608_0    conda-forge
pandoc                    3.1.3                h57928b3_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
paramiko                  3.3.1              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pathspec                  0.11.2             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.5           py310h8d17308_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycodestyle               2.10.0             pyhd8ed1ab_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydocstyle                6.3.0              pyhd8ed1ab_0    conda-forge
pyflakes                  3.0.1              pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pylint                    2.17.5             pyhd8ed1ab_0    conda-forge
pylint-venv               3.0.2              pyhd8ed1ab_0    conda-forge
pyls-spyder               0.4.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py310h635b8f1_2    conda-forge
pyqt                      5.15.9          py310h1fd54f2_4    conda-forge
pyqt5-sip                 12.12.2         py310h00ffb61_4    conda-forge
pyqtwebengine             5.15.9          py310he49db7d_4    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.12         h4de0772_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.18.0             pyhd8ed1ab_0    conda-forge
python-lsp-black          1.3.0              pyhd8ed1ab_0    conda-forge
python-lsp-jsonrpc        1.0.0              pyhd8ed1ab_0    conda-forge
python-lsp-server         1.7.4              pyhd8ed1ab_0    conda-forge
python-lsp-server-base    1.7.4              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.1              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytoolconfig              1.2.5              pyhd8ed1ab_0    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pywin32                   304             py310h00ffb61_2    conda-forge
pywin32-ctypes            0.2.2           py310h5588dad_0    conda-forge
pyyaml                    6.0             py310h8d17308_5    conda-forge
pyzmq                     25.1.0          py310hcd737a0_0    conda-forge
qdarkstyle                3.1                pyhd8ed1ab_0    conda-forge
qstylizer                 0.2.2              pyhd8ed1ab_0    conda-forge
qt-main                   5.15.8              h2c8576c_12    conda-forge
qt-webengine              5.15.8               h5b1ea0b_0    conda-forge
qtawesome                 1.2.3              pyhd8ed1ab_0    conda-forge
qtconsole                 5.4.3              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.4.3              pyha770c72_0    conda-forge
qtpy                      2.3.1              pyhd8ed1ab_0    conda-forge
referencing               0.30.2             pyhd8ed1ab_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rich                      13.5.1             pyhd8ed1ab_0    conda-forge
rope                      1.9.0              pyhd8ed1ab_0    conda-forge
rpds-py                   0.9.2           py310h87d50f1_0    conda-forge
rtree                     1.0.1           py310h1cbd46b_2    conda-forge
setuptools                68.0.0             pyhd8ed1ab_0    conda-forge
sip                       6.7.11          py310h00ffb61_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sphinx                    7.1.2              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.4              pyhd8ed1ab_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_2    conda-forge
spyder                    5.4.4           py310h5588dad_0    conda-forge
spyder-kernels            2.4.4           win_pyh7428d3b_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tbb                       2021.10.0            h91493d7_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
textdistance              4.5.0              pyhd8ed1ab_0    conda-forge
three-merge               0.1.1              pyh9f0ad1d_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.12.1             pyha770c72_0    conda-forge
tornado                   6.3.2           py310h8d17308_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.7.0           py310h00ffb61_0    conda-forge
unidecode                 1.3.6              pyhd8ed1ab_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
vc                        14.3                h64f974e_17    conda-forge
vc14_runtime              14.36.32532         hfdfe4a8_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
watchdog                  3.0.0           py310h5588dad_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
whatthepatch              1.0.5              pyhd8ed1ab_0    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wrapt                     1.15.0          py310h8d17308_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yapf                      0.40.1             pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zstd                      1.5.2                h12be248_7    conda-forge
```

</details>

**Comment by ccordoba12** [comment]
The lag could have been done due to issue #20639, which was fixed precisely in Spyder 5.4.4.

@AmerM137, could you update to that version and try again?

**Comment by AmerM137** [comment]
I updated to the latest version and I think the issue has been fixed. Maybe I am a bit sensitive to it but it feels much improved in 5.4.4. Thanks guys.

**Comment by ccordoba12** [comment]
No problem and thanks for letting us know that the issue is fixed for you now.

And don't worry, the lag was significant enough to be noticeable.
