### ISSUE TITLE
Stop kernel by ctrl+C but occur the'concurrent.futures._base.TimeoutError'and 'ensure_async(self._kill_kernel(restart=restart))'

### ISSUE THREAD

**Issue by Junda-Wong** [spyder-ide/spyder#20975]
### What steps will reproduce the problem?

I used the ctrl+c to stop the kernel execution but these errors occurred. How to solve that? python:3.6.13, tendorflow-gpu2.6.0,gpu:rtx4070 laptop, win11, spyder5.0.5. I also wrote 'import tensorflow.compat.v1' and 'compat.v1.disable_eager_execution' but no 'disable_v2_behavior'.

Thanks!

### Traceback
```python-traceback
Traceback (most recent call last):
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\manager.py", line 425, in _async_finish_shutdown
    self._async_wait(pollinterval=pollinterval), timeout=waittime / 2
  File "D:\anaconda3\envs\tf2\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "D:\anaconda3\envs\tf2\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "D:\anaconda3\envs\tf2\lib\asyncio\tasks.py", line 180, in _step
    result = coro.send(None)
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\manager.py", line 79, in wrapper
    raise e
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\manager.py", line 71, in wrapper
    out = await method(self, *args, **kwargs)
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\manager.py", line 488, in _async_shutdown_kernel
    await ensure_async(self.finish_shutdown(restart=restart))
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "D:\anaconda3\envs\tf2\lib\site-packages\nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "D:\anaconda3\envs\tf2\lib\asyncio\tasks.py", line 180, in _step
    result = coro.send(None)
  File "D:\anaconda3\envs\tf2\lib\site-packages\jupyter_client\manager.py", line 430, in _async_finish_shutdown
    await ensure_async(self._kill_kernel(restart=restart))
TypeError: _kill_kernel() got an unexpected keyword argument 'restart'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.6.13
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  7.16.1 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.1.0 (OK)
nbconvert >=4.0               :  6.0.7 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=1.0                  :  2.9.6 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  2.0.1 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=39.0.0           :  58.0.4 (OK)
sphinx >=0.6.6                :  4.4.0 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
zmq >=17                      :  22.2.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=2.0.0            :  3.2.2 (OK)
numpy >=1.7                   :  1.19.2 (OK)
pandas >=1.1.1                :  None (NOK)
scipy >=0.17.0                :  1.5.2 (OK)
sympy >=0.7.3                 :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @Junda-Wong thank you for the feedback! This seems like a duplicate of https://github.com/spyder-ide/spyder/issues/16762 You will need to update Spyder to be >= 5.2.0 or downgrade to `jupyter_client` 6

Let us know if the info above helps!

**Comment by Junda-Wong** [comment]
> Thanks.But the Spyder >=5.2 requests the python version>=3.8, but mine is 3.6. I need to use the pip/conda to install a higher version Spyder mandatorily?

I also found another problem today. The console had no response  when I clicked the restart kernel, if I needed to end up the current task. Sometimes, variable would remain even I click the 'clear variable' button.

**Comment by Junda-Wong** [comment]
> Hi @Junda-Wong thank you for the feedback! This seems like a duplicate of #16762 You will need to update Spyder to be >= 5.2.0 or downgrade to `jupyter_client` 6
> 
> Let us know if the info above helps!

I just modified the jc to 6.1.7. Because the aforementioned problem is accidental, I need to use for a period of time and give feedback. And, could I invite you to give me some ideas on above restart kernel problem? Thanks! XD

**Comment by dalthviz** [comment]
> I just modified the jc to 6.1.7. Because the aforementioned problem is accidental, I need to use for a period of time and give feedback. And, could I invite you to give me some ideas on above restart kernel problem? Thanks! XD

Awesome, glad to hear that you were able to workaround the problem by downgrading `jupyter_client`! Regarding the restart not totally sure but maybe it could also be an issue that was solved in a more recent release. If you have any more info let us know!

**Comment by Junda-Wong** [comment]
@dalthviz After I degraded the jc, I have not met that error again. BUT the problem 'restart kernel no response' still remains. It will occurs possibly after running a tensorflow .py file or half-stopping. The results are: restart kernel no response, no error report either. But restart kernel will success if I don't run the .py file, or specifically, don't run with tensorflow. I guess there's some conflicts of versions of tensorflow-gpu and spyder also jc. Now my solution is: to open a new console when I meet above issue.

**Comment by dalthviz** [comment]
Oh I see thank you for the info @Junda-Wong :+1: I think there is not much we can do or suggest but maybe running Spyder on debug mode could give more info. To run Spyder in debug mode you can run it with the `--debug-info verbose` flag

**Comment by dalthviz** [comment]
Closing due to lack of response
