### ISSUE TITLE
Data-frame viewing in Variable Explorer doesn't work for 5.4.3 (for 5.4.2 it does)

### ISSUE THREAD

**Issue by royser1984** [spyder-ide/spyder#20979]
Changing pandas version does not fix.

I downgraded to spyder 5.4.2 and it solved. 

Installed versions:
python 3.9.7
pandas 1.3.5
miniconda

**Comment by ccordoba12** [comment]
Hey @royser1984, thanks for reporting. Are you seeing any errors when you're trying to open a Dataframe with Spyder 5.4.3?

If that's the case, could you post them here? Thanks!

**Comment by pmateosmasa1** [comment]
Hi I have faced the problem. It looks like you need to reindex the dataframe to see it by using df.reindex(). Hope this helps to solve the issue

**Comment by ccordoba12** [comment]
@pmateosmasa, thanks for chiming in. Let's hope your advice has helped @royser1984 with the reported problem.

I'm going to close this issue because we didn't get a reply.
