### ISSUE TITLE
Low priority: Spyder-6.0.0a1install for Linux --> 404

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#21048]
https://github.com/spyder-ide/spyder/releases/download/v6.0.0/Spyder-6.0.0a1-Linux-x86_64.sh
===> 404

**Comment by ccordoba12** [comment]
Hey @texadactyl, thanks for reporting. Installers for all OSes are being built right now:

https://github.com/spyder-ide/spyder/actions/runs/5325104307

It takes around 30 min for them to be up, so please be patient.

**Comment by texadactyl** [comment]
I jumped the gun, eh?  (:

**Comment by ccordoba12** [comment]
Haha, seems like it! But it should be working now, so please check again.

**Comment by texadactyl** [comment]
Windows installer is there. MacOS and Linux --> 404.

**Comment by ccordoba12** [comment]
I checked and they are working now. I think you need to reload the page because the links I added at the beginning were not the right ones.

**Comment by ccordoba12** [comment]
The releases page, I meant. Did you get an email about the alpha release?

**Comment by texadactyl** [comment]
Yes. The links there is what I have been using.

**Comment by texadactyl** [comment]
You might want to put out a correction email to everyone on the alpha distribution and tell them the releases page is what folks should use if they want to be alpha testers.

**Comment by ccordoba12** [comment]
Thanks for the suggestion. I didn't know people got emails about our releases, so we'll try to be more careful about  links in them in the future.

For this one I wasn't sure about the installers URLs because it's the first time we generate them for Spyder 6. So I hope people jump to the releases page for the right links.
