### ISSUE TITLE
Spyder crashes when launching after Windows standalone installation

### ISSUE THREAD

**Issue by looka231** [spyder-ide/spyder#21074]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

^ can not use anaconda or connect to internet with the computer I am installing on

## Problem Description
I have followed the installation instructions for the Spyder Window (standalone) installer. I have installed the latest python before as well. Tried installing and reinstalling Spyder for local and for everyone option and it still instantly crashes when launching. It keeps giving me this compatibility check error and then crashes

"Unfortunately, the library that Spyder-terminal use to create terminals is failing to work in your system. Therefore, this plugin will be deactivated. This usually happens on Windows 7 Systems. If that's the case, please consider updating to newer windows version"

even though I am on Windows 10 pro. I used the same installation process on my personal laptop and Spyder launched with no problems. Please help

### What steps reproduce the problem?

1. Install latest python
2. Install Spyder windows (standalone) installer
3. Launch Spyder

### What is the expected output? What do you see instead?
Spyder launches but immediately crashes without displaying the gui

### Paste Traceback/Error Below (if applicable)

```python-traceback

fromIccProfile: failed minimal tag size sanity
Traceback (most recent call last):
 File "C:\Program Files\Spyder\Spyder.launch.pyw", line 35, in <module>
   main()
 File "C:\Program Files\Spyder\pkgs\spyder\app\start.py", line 256, in main
   mainwindow.main(options, args)
 File "C:\Program Files\Spyder\pkgs\spyder\app\mainwindow.py", line 1823, in main
   mainwindow = create_window(MainWindow, app, splash, options, args)
 File "C:\Program Files\Spyder\pkgs\spyder\app\mainwindow.py", line 203, in on_mainwindow_visible
   self.layouts.on.on_mainwindow_visible()
 File "C:\Program Files\Spyder\pkgs\spyder\plugins\layout\plugin.py", line 908, in create_plugins_menu
   action.setChecked(plugin.dockwidget.isVisible())
AttributeError: 'NoneType' object has no attribute 'isVisible'
Qprocess: Destroyed while process ("C:\\Program Files\\Spyder\\Python\\pythonw.exe") is still running.

```

## Versions

* Spyder version: 5.4.3 (Windows Standalone)
* Python version: 3.11.4 (64-bit)
* Qt version: 5.15.2
* PyQt version: 5.15.9
* Operating System name/version: Windows 10 Pro

**Comment by MariaKrivova** [comment]
> ### Issue Report Checklist
> * [x]  Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
> * [x]  Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
> * [ ]  Reproduced the issue after updating with `conda update spyder` (or `pip`, if not using Anaconda)
> * [ ]  Could not reproduce inside `jupyter qtconsole` (if console-related)
> * [x]  Tried basic troubleshooting (if a bug/error)
>   
>   * [x]  Restarted Spyder
>   * [ ]  Reset preferences with `spyder --reset`
>   * [ ]  Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
>   * [x]  Tried the other applicable steps from the Troubleshooting Guide
> * [x]  Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below
> 
> ^ can not use anaconda or connect to internet with the computer I am installing on
> 
> ## Problem Description
> I have followed the installation instructions for the Spyder Window (standalone) installer. I have installed the latest python before as well. Tried installing and reinstalling Spyder for local and for everyone option and it still instantly crashes when launching. It keeps giving me this compatibility check error and then crashes
> 
> "Unfortunately, the library that Spyder-terminal use to create terminals is failing to work in your system. Therefore, this plugin will be deactivated. This usually happens on Windows 7 Systems. If that's the case, please consider updating to newer windows version"
> 
> even though I am on Windows 10 pro. I used the same installation process on my personal laptop and Spyder launched with no problems. Please help
> 
> ### What steps reproduce the problem?
> 1. Install latest python
> 2. Install Spyder windows (standalone) installer
> 3. Launch Spyder
> 
> ### What is the expected output? What do you see instead?
> Spyder launches but immediately crashes without displaying the gui
> 
> ### Paste Traceback/Error Below (if applicable)
> ```
> fromIccProfile: failed minimal tag size sanity
> Traceback (most recent call last):
>  File "C:\Program Files\Spyder\Spyder.launch.pyw", line 35, in <module>
>    main()
>  File "C:\Program Files\Spyder\pkgs\spyder\app\start.py", line 256, in main
>    mainwindow.main(options, args)
>  File "C:\Program Files\Spyder\pkgs\spyder\app\mainwindow.py", line 1823, in main
>    mainwindow = create_window(MainWindow, app, splash, options, args)
>  File "C:\Program Files\Spyder\pkgs\spyder\app\mainwindow.py", line 203, in on_mainwindow_visible
>    self.layouts.on.on_mainwindow_visible()
>  File "C:\Program Files\Spyder\pkgs\spyder\plugins\layout\plugin.py", line 908, in create_plugins_menu
>    action.setChecked(plugin.dockwidget.isVisible())
> AttributeError: 'NoneType' object has no attribute 'isVisible'
> Qprocess: Destroyed while process ("C:\\Program Files\\Spyder\\Python\\pythonw.exe") is still running.
> ```
> 
> ## Versions
> * Spyder version: 5.4.3 (Windows Standalone)
> * Python version: 3.11.4 (64-bit)
> * Qt version: 5.15.2
> * PyQt version: 5.15.9
> * Operating System name/version: Windows 10 Pro

I have the same issue. Looking forward to upgrades.

**Comment by MariaKrivova** [comment]
I have the same issue. Looking forward to upgrades.

**Comment by ccordoba12** [comment]
Thanks @MariaKrivova. We're sorting out the last details for that version, so hopefully it'll be available at the beginning of next week.
