### ISSUE TITLE
Spyder isn't launching on Windows

### ISSUE THREAD

**Issue by gitmartiin** [spyder-ide/spyder#21098]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder isn't launching on Windows with AMD Ryzen 7 5825U (16 Core)

### What steps reproduce the problem?

1. starting the application
2. 
3. 

### What is the expected output? What do you see instead?
Expected would be launching Spyder.
No output, nothing happens except the Error in the "Ereignisanzeige" in Windows.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

Microsoft Windows [Version 10.0.19045.3086]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\martin.hassler\AppData\Local\Programs\Spyder>python Spyder.launch.pyw
Traceback (most recent call last):
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\Spyder.launch.pyw", line 34, in <module>
    from spyder.app.start import main
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\spyder\app\start.py", line 46, in <module>
    import zmq
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\zmq\__init__.py", line 136, in <module>
    from zmq import backend
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\zmq\backend\__init__.py", line 31, in <module>
    raise original_error from None
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\zmq\backend\__init__.py", line 26, in <module>
    _ns = select_backend(first)
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\zmq\backend\select.py", line 31, in select_backend
    mod = import_module(name)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (
ImportError: cannot import name '_device' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\Users\martin.hassler\AppData\Local\Programs\Spyder\pkgs\zmq\backend\cython\__init__.py)

C:\Users\martin.hassler\AppData\Local\Programs\Spyder>

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: newest release (on 07.04.2023)
* Python version: newest release 3.11
* Qt version: 
* PyQt version: 
* Operating System name/version: Win10 Pro 22H2 64bit

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```
Ereignisanzeige Windwos at start try:

Name der fehlerhaften Anwendung: pythonw.exe, Version: 3.8.10150.1013, Zeitstempel: 0x608fe38b
Name des fehlerhaften Moduls: atio6axx.dll, Version: 31.0.12044.50003, Zeitstempel: 0x6423d329
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0000000000131cc2
ID des fehlerhaften Prozesses: 0x2f8c
Startzeit der fehlerhaften Anwendung: 0x01d9ae74f6b53cdc
Pfad der fehlerhaften Anwendung: C:\Users\martin.hassler\AppData\Local\Programs\Spyder\Python\pythonw.exe
Pfad des fehlerhaften Moduls: C:\WINDOWS\System32\DriverStore\FileRepository\u0390034.inf_amd64_d8f20db8ffe0563b\B390155\atio6axx.dll
Berichtskennung: 8df9d35c-13b4-4112-bc0e-a55f05b4e20a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by ccordoba12** [comment]
Hey @gitmartiin, thanks for reporting. Do you have other Python installations in your system? I say it because they could be interfering with the Spyder installation.

**Comment by gitmartiin** [comment]
Hi @ccordoba12 thanks for the reply. 
No I have only installed Python 3.11 and then Spyder.

**Comment by ccordoba12** [comment]
And did you install Python 3.11 in `C:\Program files` and afterwards some packages with pip in a terminal?

**Comment by gitmartiin** [comment]
Yes, installed in C:\Program Files but nothing installed via pip in terminal that I know of.

**Comment by gitmartiin** [comment]
Hi @ccordoba12  I have found the error. :)
It seems, that Spyder has indeed some system requirements, that are not listed on your homepage. In fact I just installed Microsoft Visual C++ 2010 x64 Redistributable - 10.0.40219 and Microsoft Visual C++ 2010 x86 Redistributable - 10.0.40219 and now Spyder is launching and (on the first view) works.
The actual MV C++ 2015-2022 Redistributable isn't enough.

**Comment by ccordoba12** [comment]
> Hi @ccordoba12 I have found the error. :)

That's great! Thanks for letting us know about it. However, those redistributables should be part of your system. I don't understand why you had to install them manually.

I also want to say that I understand better your problem now. You posted that you tried to start our app with the command:

    C:\Users\martin.hassler\AppData\Local\Programs\Spyder>python Spyder.launch.pyw

By doing that, you're using your Python 3.11 version to try to start our application, which comes with Python 3.8. And that in turn causes the mix of packages compiled for those two different Python versions (which are incompatible) and it generates  the crash you reported.

The thing is you don't need to start Spyder in that way. Instead, you need to go the Windows Start menu, look for the Spyder entry on it and click it. Then you shouldn't observe any errors with Spyder.

Let us know if that works for you.

**Comment by gitmartiin** [comment]
No problem,
I know how to start an application correct with just klicking on it. Just to give you more information I also tried to open via terminal, so I could report more than: "won't open by klicking".

My laptop is less than two months old and the 2010 Redistributables are no longer on it, only 2015-2022. With them, klicking the icon works.

Thanks for supporting.
