### ISSUE TITLE
Python interpretor for PyFlakes

### ISSUE THREAD

**Issue by sharon92** [spyder-ide/spyder#21097]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The Editor shows me an error from PyFlakes relating to the new match case syntax in python 3.10.
In my Preferences --> Console I have selected my venv 3.11 and installed pyflakes on my python environment, but apparently it still uses the python 3.8.10 that comes with spyder.

![image](https://github.com/spyder-ide/spyder/assets/51754340/98a3fdbb-4031-43f2-8eb7-fa75883561a2)

![image](https://github.com/spyder-ide/spyder/assets/51754340/33a6b7c9-3f84-48d1-b926-970d1839acac)

### What steps reproduce the problem?

1.  Select Python 3.11 in preferences
2.  Write a match-case semantics 

### What is the expected output? What do you see instead?
in the code analysis traceback it even says its using venv:

Using venv: C:\Entwicklung\SMS-Tools\env311\Scripts
************* Module MeshClasses._nodestrings
E0001:syntax-error: 81,19: Parsing failed: 'invalid syntax (<unknown>, line 81)'

### Paste Traceback/Error Below (if applicable)

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please do not use it to run your code

>>> Uncaught ReferenceError: spyder_terminal is not defined
Uncaught ReferenceError: spyder_terminal is not defined
Uncaught ReferenceError: spyder_terminal is not defined
Uncaught ReferenceError: spyder_terminal is not defined

```python-traceback



```

## Versions

* Spyder version: 5.4.3  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree                                     :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.11.2 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  3.1.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.14.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.6.1 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.3 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog                                         :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.34 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2             :  1.2.2 (OK)

```

**Comment by ccordoba12** [comment]
Hey @sharon92, thanks for reporting. This requires to update the Python version we use in our installers from 3.8 to 3.10 or higher. This is planned and already done for Spyder 6, to be released before the end of the year. Unfortunately, we won't be able to do it for Spyder 5 because it's not an easy task.

However, there's a workaround you can use for now and that's to add a comment of the form `#noqa` next to the line that shows the error in Spyder, like this:

![image](https://github.com/spyder-ide/spyder/assets/365293/68c7be5a-9031-466b-ad83-89a971935a04)

**Comment by sharon92** [comment]
@ccordoba12 thank you for the tip!
