### ISSUE TITLE
je ne peux plus ouvrir de consoles

### ISSUE THREAD

**Issue by anoukandre** [spyder-ide/spyder#21110]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @anoukandre, thanks for reporting. It seems you're using a very old Spyder version (probably five years old or more). So, please install a more recent version by following the instructions in [our documentation](http://docs.spyder-ide.org/current/installation.html).
