### ISSUE TITLE
Spyder 6.0.0a1 - New line (ctrl-enter) in console runs cell instead

### ISSUE THREAD

**Issue by mg3146** [spyder-ide/spyder#21129]
In Spyder 5, I would use ctrl-enter to create a new line in the console (for multiline code).  However, I can't seem to figure out how to do that in Spyder 6.  Instead, Ctrl-Enter seems to be running a cell of code (the editor keyboard shortcut).

**Comment by ccordoba12** [comment]
Hey @mg3146, thanks for reporting. You said:

> In Spyder 5, I would use ctrl-enter to create a new line in the console (for multiline code).

You mean that you typed `Ctrl+Enter` in the console, right? If that's the case, I can reproduce your error and it's a bug. We'll try to fix it in alpha2.

**Comment by ccordoba12** [comment]
Sorry, I can see now that you said exactly that (I read your message too fast!).

**Comment by mg3146** [comment]
FYI - Ctrl-Shift-Enter seems to make a new line
