### ISSUE TITLE
Can't launch Spyder in Windows 11 with WSL2

### ISSUE THREAD

**Issue by muriloasouza** [spyder-ide/spyder#21120]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In Windows 11, i have installed WSL2 (Ubuntu 22.04.2), then proceeded to install miniconda inside WSL2 and created a new conda environment. After that, i install Spyder using `conda install spyder`, but when i try to launch it, i get this error:

![Img](https://github.com/spyder-ide/spyder/assets/40600889/6ab699d8-02b6-4989-a986-5a5282b40695)

### What steps reproduce the problem?

1. Install WSL2 in Windows 11;
2. Install Miniconda in WSL2;
3. Create a fresh conda environment and install Spyder in it.

### What is the expected output? What do you see instead?

Expect Spyder to launch, but got this error:

```
(tf) root@LDSPUFPE3:/mnt/c/Users/ldsp_# spyder
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, minimal, minimalegl, offscreen, vnc, webgl, xcb.

Aborted
```

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.3
* Python version: 3.9.17
* Qt version: Not really sure, there are too many qt related stuff i get from `conda list`. Here's a pic:
![Img](https://github.com/spyder-ide/spyder/assets/40600889/4acb199e-4610-46cf-a4a4-813b366d50d1)

* PyQt version: 5.15.7
* Operating System name/version: Windows 11 with WSL2 (Ubuntu 22.04.2) 

### Dependencies
Can't launch Spyder, so i can't copy the dependencies.

**Comment by ccordoba12** [comment]
Hey @muriloasouza, thanks for reporting. I don't think you'll be able to start Spyder as `root` in your system because graphical applications can't be started while you're `root`.

Instead, please log in as a regular user and try again. Let us know if that works for you.

**Comment by muriloasouza** [comment]
Hello @ccordoba12, i have reinstalled WSL and now with a regular user i am having this problem:

```
(tf) ldsp@LDSPUFPE3:/mnt/c/Windows/system32$ spyder
Traceback (most recent call last):
  File "/home/ldsp/miniconda3/envs/tf/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/ldsp/miniconda3/envs/tf/lib/python3.9/site-packages/spyder/app/start.py", line 252, in main
    from spyder.app import mainwindow
  File "/home/ldsp/miniconda3/envs/tf/lib/python3.9/site-packages/spyder/app/mainwindow.py", line 46, in <module>
    from qtpy.compat import from_qvariant
  File "/home/ldsp/miniconda3/envs/tf/lib/python3.9/site-packages/qtpy/compat.py", line 18, in <module>
    from .QtWidgets import QFileDialog
  File "/home/ldsp/miniconda3/envs/tf/lib/python3.9/site-packages/qtpy/QtWidgets.py", line 14, in <module>
    from PyQt5.QtWidgets import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

![img](https://github.com/spyder-ide/spyder/assets/40600889/474338ae-780d-4a52-a0ff-758b6f6b0ea9)

**Comment by ccordoba12** [comment]
> i have reinstalled WSL and now with a regular user i am having this problem:

Did you also install Xorg in WSL to be able to run graphical applications?

**Comment by muriloasouza** [comment]
@ccordoba12 Thanks, following your advice i found some tutorial in how to do that. That fixed the issue.

Unfortunately, i found this is to be a bit complicated to make it work for the average user (like me), too many steps to make Spyder run in WSL.

**Comment by omersayli** [comment]
A solution that worked for me is this
i) Open command prompt
ii)  run first, "wsl --update" ,  then "wsl --shutdown"
then open it back.


https://github.com/microsoft/WSL/issues/7950#issuecomment-1021203652
