### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by ccmswu** [spyder-ide/spyder#21123]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

AttributeError: 'module' object has no attribute 'UTC'
AttributeError: 'module' object has no attribute 'UTC'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.18
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Hey @ccmswu, thanks for reporting. I'm afraid you're using a very old Spyder version. So, I'm afraid you'll have to remove and reinstall Anaconda to get a working version again.

That's described in detail in [our documentation](http://docs.spyder-ide.org/current/installation.html).
