### ISSUE TITLE
Spyder does not launch after Anaconda Navigator upgrade

### ISSUE THREAD

**Issue by nibor10** [spyder-ide/spyder#21124]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After the latest anaconda update to Anaconda Navigator 2.4.2, spyder did not launch anymore. Selecting spyder from the Anaconda Navigator home-screen results in a pop-up window:

> Application launch error | Application spyder launch may have produced errors. Exit code: 3221225477

![image](https://github.com/spyder-ide/spyder/assets/139369383/237e4e25-7d2f-449c-921f-ff15f1683599)

I uninstalled Anaconda according to the [documentation](https://docs.anaconda.com/free/anaconda/install/uninstall/) and installed the previously running version from the [archive](https://repo.anaconda.com/archive/Anaconda3-2023.03-1-Windows-x86_64.exe). The error remains and was not resolved. Creating a new spyder env didn't work. Starting spyder from CMD does not launch spyder and also does not show the error window from the Anaconda Navigator. 
All other packages from Anaconda Navigator (JupyterLab, ...) run smoothly, before and after fresh installation.

Since the fresh install of Anaconda Navigator I cannot update anymore:

```Python
(base) C:\Users\[username]>conda update anaconda

PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\tools\Anaconda3
  package name: anaconda
```

### What steps reproduce the problem?

I could not reproduce the error with another PC running on Win10.

## Versions

* Spyder version: 5.4.1
* Python version: 3.10.9
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 11 Pro Version 10.0.22621 Build 22621

**Comment by nibor10** [comment]
Hi Carlos, thanks for reaching out!If I run the command in the anaconda prompt, basically nothing happens. After a few seconds the command line skips back to base, but spyder does not show up, nor an error message appears. Cheers On 12 Jul 2023 18:38, Carlos Cordoba ***@***.***> wrote:
Hey @nibor10, thanks for reporting. Please open the Anaconda Prompt, then run
spyder

and post here any errors you see in the terminal after doing that. Thanks!

**Comment by ccordoba12** [comment]
Did you use pip to install or update Spyder in your base environment?

**Comment by nibor10** [comment]
I used `conda update anaconda` regularly and avoid `pip` installations. Spyder reminded me of updates in the past, but I don't force to install new versions and wait for the implementation with the general conda update command.

**Comment by ccordoba12** [comment]
> I used `conda update anaconda` regularly and avoid `pip` installations

Ok, that's really good.

Let's create a new environment for Spyder then to see if that allows you to start it. For that, open the Anaconda Prompt again and run these commands:

    conda create -n spyder-env -c conda-forge spyder
    conda activate spyder-env
    spyder

Hopefully that will solve your problem.

**Comment by ccordoba12** [comment]
Ok, then please run these commands to see if we can get more information about this problem:

    conda activate spyder-env
    spyder --debug-info verbose

After that, please post here the output (if any) printed to the terminal.

**Comment by nibor10** [comment]
The prompt successfully switches to the spyder enviroment, but the debug-info does not print anything.

**Comment by Lugle29** [comment]
I encounter the same problem. All the steps I found so far didn't work and I don't get any error messages or debug info instead of the error code from anaconda. Is there any solution found yet?

**Comment by ccordoba12** [comment]
@nibor10, do you still have the same problem?

**Comment by nibor10** [comment]
Yes, I do.

**Comment by nibor10** [comment]
@ccordoba12 I updated everything with `conda update anaconda` and now spyder starts again. 
Thank you very much for your time!
