### ISSUE TITLE
LSP status crashes after reset, code logic error

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/spyder#21127]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

LSP status crashes after resetting spyder

### What steps reproduce the problem?

1. Reset spyder
2. Click on LSP status (spinning)
3. Error message

This error stills in the master branch. I'm going to create a PR for this on 5.x. Let me know if its ok, thanks.

### What is the expected output? What do you see instead?

The test for None is done after applying string function. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "../site-packages/spyder/plugins/completion/providers/languageserver/widgets/status.py", line 70, in show_menu
    language = self.current_language.lower()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'lower'
```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.4 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Linux 5.19.0-46-generic

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @dpizetta, long time no see! Thanks for reporting and also for your PR fixing this. We'll include it in our next version (5.4.4), to be released next week.

**Comment by dpizetta** [comment]
Thanks @ccordoba12.  Always nice to work with you guys!
