### ISSUE TITLE
Running from IDE prints nothing

### ISSUE THREAD

**Issue by mahmoodn** [spyder-ide/spyder#21135]
Hi
Using Spyder 5.3.2, I see that the code inside the editor prints no information, but when I run the commands in the interpreter, it is fine.
See the image please:
![image](https://github.com/spyder-ide/spyder/assets/11626212/ccc3db72-0878-41aa-8435-827e39b28979)
Any idea on how to fix that?

**Comment by ccordoba12** [comment]
Hey @mahmoodn, thanks for reporting. You said:

> Using Spyder 5.3.2, I see that the code inside the editor prints no information

For things to be printed to the console when running a file, you need to use the `print` statement. In your case, you need change the last line of your code to

```python
print(msft.get_shares_full())
```

> but when I run the commands in the interpreter, it is fine.

That's the way the console works: to facilitate rapid code inspection and iteration, it doesn't require using `print`. But when running files, you need to.

To finish, I'd like to say that this is not a special Spyder requirement, it's how Python works. If you run your file in a system terminal (i.e. cmd.exe) with `python shares.py`, you'll see that you also need to use `print` to see something printed on it.
