### ISSUE TITLE
Cannot open Spyder through Anaconda

### ISSUE THREAD

**Issue by jxiaoct** [spyder-ide/spyder#21170]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
My Anaconda stuck at loading application so I uninstalled and reinstalled it. However, I cannot open Spyder through it after then.

### What steps reproduce the problem?

1. Tried uninstalled and reinstalled for a couple of times but failed still.
2. 
3. 

### What is the expected output? What do you see instead?
The Spyder opened for a second and immediately closed. 

### Paste Traceback/Error Below (if applicable)
C:\Users\jxiao\AppData\Local\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
"class": algorithms.Blowfish,
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Traceback (most recent call last):
File "C:\Users\jxiao\AppData\Local\anaconda3\Lib\asyncio\windows_events.py", line 444, in select
self._poll(timeout)
RuntimeError: still has pending operation at deallocation, the process may crash
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)
Bad address (C:\ci\zeromq_1616055400030\work\src\epoll.cpp:100)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.3
* Python version:  3.11.3
* Qt version: 
* PyQt version: 5.15.7
* Operating System name/version: Win10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @jxiaoct, thanks for reporting. Unfortunately, this is not a problem we can help you with here because it seems caused by some package in Anaconda itself (we don't have a relationship with Anaconda other than they distributing Spyder).

Instead, please download our [Windows installer](https://github.com/spyder-ide/spyder/releases) and let us know if it works for you.

**Comment by jxiaoct** [comment]
Hi @ccordoba12 
I uninstalled Anaconda and download and installed Spyder using the link you provided, unfortunately the problem still exists. Spyder interface showed for a sec but immediately closed. Any idea what can I do next step?

**Comment by ccordoba12** [comment]
@jxiaoct, you need to remove Anaconda and then start Spyder from our Windows installer. That should solve your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
