### ISSUE TITLE
how to change font size or margin of the header of vairable explorer?

### ISSUE THREAD

**Issue by areur3ady** [spyder-ide/spyder#21199]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
variable explorer default setting for the font and margin of the table header makes it difficult to see the header clearly.

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
![无标题](https://github.com/spyder-ide/spyder/assets/20264900/1927a475-63fe-41e9-8a0c-24acdc1c59cb)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @areur3ady, thanks for reporting. Could you update to PyQt 5.15 and try again? You didn't mention how you installed Spyder so I can't tell you exactly how to do it. But other users reported that doing that fixed this problem.

**Comment by ccordoba12** [comment]
Ok, but this problem should be fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

Let us know if that works for you.
