### ISSUE TITLE
spyder autocompletion will fail in nested modules

### ISSUE THREAD

**Issue by jcbritobr** [spyder-ide/spyder#21200]
Hello

Python 3.11.4 64-bit | Qt 5.15.2 | PyQt5 5.15.9 | Linux 6.4.6-200.fc38.x86_64 (x86_64) 
spyder 5.4.4 linux

When using some nested functions and modules, autocomplete will fail
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(..)
ax. #%% after, here autocomplete will fail
```

**Comment by ccordoba12** [comment]
Hey @jcbritobr, thanks for reporting. This is a known limitation of Python's auto-completion machinery (see issue #2162) and we'll try to improve it in Spyder 6 (but I don't know if we'll have time for it).

In the meantime, you can add typing information to your `fig, ax` statements, as described here:

https://stackoverflow.com/a/62478431/438386

That will give you the expected auto-completions for both `fig` and `ax`. Please try that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
