### ISSUE TITLE
dsgsdgfdhfdhbfdbfdbfd

### ISSUE THREAD

**Issue by snehasavarapu** [spyder-ide/spyder#21209]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
 asvzdfhdfjtygky

**Comment by dalthviz** [comment]
Closing this since is empty, see https://github.com/spyder-ide/spyder/issues/21208#issuecomment-1663027588
