### ISSUE TITLE
Config page for Shortcuts always shows shortcuts in black regardless of interface theme

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21206]
## Problem Description

Seems like now the setted shortcuts are being displayed in black always regardless of the interface theme:

![image](https://github.com/spyder-ide/spyder/assets/16781833/d6804756-6337-402f-9f04-062db0aee75d)

Discovered this while checking #10990

### What steps reproduce the problem?

1.  Open the preferences dialog
2.  Go to the `Keyboard shortcuts` page
3.  The setted shortcuts appear with black text instead of white when using the dark theme

### What is the expected output? What do you see instead?

Be able to see the setted shortcuts

## Versions

* Spyder version: 6.0.0.dev0 50fdce980 (conda)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
I'll take a look at this because I'll probably introduced this error in #21101 (it's working fine for me on Linux though).

**Comment by ccordoba12** [comment]
Leaving for alpha3 because I don't have my Windows virtual machine with me these days, so I can't use it to fix it.

**Comment by ccordoba12** [comment]
I just saw that this is a problem with the dark theme and it happens on Linux too. So I'll take a look at it for alpha2.
