### ISSUE TITLE
feature request: add search bar in preference setting 

### ISSUE THREAD

**Issue by areur3ady** [spyder-ide/spyder#21223]
please add a search bar in preference to make it easier to use, thx

**Comment by ccordoba12** [comment]
Hey @areur3ady, thanks for reporting. Unfortunately, this is not so easy to do and we don't have the resources to address it right now. So, I really don't know when we'll have time to implement it.

Besides, this request was reported before on issue #1780, so I'm going to close it in favor of that one.
