### ISSUE TITLE
Issue with the anaconda and spyder

### ISSUE THREAD

**Issue by prathamvbhat** [spyder-ide/spyder#21230]
## Problem Description
This version of python seems to be incorrectly compiled
(internal generated filenames are not absolute).
This may make the debugger miss breakpoints.
Related bug: http://bugs.python.org/issue1666807

### What steps reproduce the problem?

1. I installed anaconda latest version
2. spyder installed separately

### What is the expected output? What do you see instead?
I got the reqired output but with that i get this too:
This version of python seems to be incorrectly compiled
(internal generated filenames are not absolute).
This may make the debugger miss breakpoints.
Related bug: http://bugs.python.org/issue1666807

## Versions

* Spyder version: 5
* Python version: 3.11
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 11

**Comment by ccordoba12** [comment]
Hey @prathamvbhat, thanks for reporting. This problem was already fixed in our latest version (5.4.4), which is not part of Anaconda yet.

You can safely ignore it because that message is harmless and doesn't affect Spyder in any way.
