### ISSUE TITLE
Error when running a file

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21238]
## Problem Description

Tried running a file and instead I got the error report dialog. The error ocurred while I was checking #21160

### What steps reproduce the problem?

* Not totally sure, maybe running a file which was runned  in a previous session (?)
  * Also, not long ago, I saved a run config, maybe that could be part of the reason why the error raised?

### What is the expected output? What do you see instead?

No error

### Paste Traceback/Error Below (if applicable)

```python-traceback
Traceback (most recent call last):
  File "C:\Users\dalth\AppData\Local\spyder-6\envs\spyder-runtime\lib\site-packages\spyder\plugins\run\container.py", line 207, in run_file
    first_execution = exec_params['first_execution']
KeyError: 'first_execution'
```

## Versions

* Spyder version: 6.0.0a1 0d7fb757 (standalone)
* Python version: 3.9.16 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
@dalthviz, did you try to run a file that you had previously run in alpha1?

The problem is the `first_execution` was removed from the run config  parameters on PR https://github.com/spyder-ide/spyder/pull/20762, so that should cause this problem.

**Comment by dalthviz** [comment]
Oh I see! I'm not totally sure, it is quite possible since I think the file that I tried to run was the `temp.py` file that opens and that I usually use to run example code from issues 🤔 

Should we close this one then @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yep, I think that's fine. If you run `spyder --reset` you shouldn't see this problem again.
