### ISSUE TITLE
Incorrect syntax highlighting of the words "match" and "case" outside of match/case structures

### ISSUE THREAD

**Issue by nukamoi** [spyder-ide/spyder#21239]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

New syntax highlighting of "match" and "case" in Spyder 5.4.4 highlights those words in the wrong contexts (as well as in the correct contexts). Example in screenshot below: 'match' on line 55 is highlighted when I believe it should not be.

![image](https://github.com/spyder-ide/spyder/assets/141940373/72156db2-e0d8-46e1-8dc4-8c23536b72bf)

### What steps reproduce the problem?

1. open Spyder in dark mode (I did not check light mode)
2. open new .py file
3. typing the words "match" or "case" in the IDE (not iPython console) causes the incorrect syntax highlighting (e.g. an object attribute 'self.case' has both "self" and "case" highlighted -- "self" correctly, "case" incorrectly).

Problem persists with all syntax highlighting themes
(Preferences > Appearance > Syntax Highlighting Themes)

### What is the expected output? What do you see instead?

Expected no highlighting of the words "match" and "case" outside of proper match/case structures.

### Paste Traceback/Error Below (if applicable)

N/A

## Versions

* Spyder version: 5.4.4  (conda)
* Python version: 3.11.3 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.19044-SP0

### Dependencies

I'm quite certain these won't matter, but here they are anyway!
```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.0 (OK)
chardet >=2.0.0                                                             :  4.0.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  1.7.3 (OK)
diff_match_patch >=20181111                                                 :  20200713 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.1 (OK)
jellyfish >=0.7                                                             :  0.9.0 (OK)
jsonschema >=3.2.0                                                          :  4.17.3 (OK)
keyring >=17.0.0                                                            :  23.13.1 (OK)
nbconvert >=4.0                                                             :  6.5.4 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.0 (OK)
pygments >=2.0                                                              :  2.15.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.16.2 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.0.2 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.2 (OK)
qtpy >=2.1.0                                                                :  2.2.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  67.8.0 (OK)
sphinx >=0.6.6                                                              :  5.0.2 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.2.1 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  2.1.6 (OK)
zmq >=22.1.0                                                                :  25.1.0 (OK)

# Optional:
cython >=0.21                                                               :  None (NOK)
matplotlib >=3.0.0                                                          :  3.7.1 (OK)
numpy >=1.7                                                                 :  1.24.3 (OK)
pandas >=1.1.1                                                              :  1.5.3 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.11.1 (OK)

```

**Comment by ccordoba12** [comment]
Hey @nukamoi, thanks for reporting. You're right about this and we'll try to fix it in our next version (5.5.0), to be released in a couple of months.

**Comment by ptth222** [comment]
I am still experiencing this on 5.5.5. It is kind of intermittent. I can trigger it consistently by typing a colon on the same line.


```
re_match = "asdf"           # Not highlighted
if re_match == "asdf":      # Highlighted
    pass

```

**Comment by ccordoba12** [comment]
@ptth222, you're right. Please open a new issue about it so we don't forget to address it in a future release.

**Comment by ptth222** [comment]
Opened #22305.
