### ISSUE TITLE
Geting pandas.DataFrame variable

### ISSUE THREAD

**Issue by validiom** [spyder-ide/spyder#21243]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Loading a DataFrame from csv, I'm unable to visualing variable in variable explorer.

    for __, col in self.df.iteritems():
  File "/home/validiomande/anaconda3/envs/mlpy3/lib/python3.9/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'iteritems'

**Comment by ccordoba12** [comment]
Hey @validiom, thanks for reporting. This problem is fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the following commands:

    conda activate mlpy3
    conda install spyder=5.4.3
