### ISSUE TITLE
Removal of keyboard shortcut causes errors to be thrown

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2125]
_From [thevp...@gmail.com](https://code.google.com/u/114967603654191624717/) on 2015-01-20T23:56:05Z_

Spyder Version:  2.3.2
Python Version:  3.4.1
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.14.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.4.0 (OK) 

What steps will reproduce the problem?

1. Go to Keyboard Shortcuts (Tools -> Preferences --> Keyboard Shortcuts)
2. Pick a shortcut of your choice and select the blank value for all shortcut modifiers
3. Double-click on "Key" column for that shortcut, and select a random character.
4. Press "OK", and verify that the shortcut has been "removed" by checking the menus (In my case, I first tested the removal of the shortcut for "Quit", and the character I chose was "0". The option under File-->Quit showed that there was no shortcut to that command.) 

What is the expected output? What do you see instead?

 An error message should pop-up, stating that this is an invalid choice. Or, the command item should be removed completely. However, Spyder accepts the options but starts throwing errors and becomes unstable, throwing errors described in the section below. Also, at this point, I cannot re-define the shortcut - any choices made will be cleared as soon as another box is pressed. Only way to make things stable again is to press "restore keyboard shortcuts". 

Please provide any additional information below

Errors produced in console after the problem is created and the Keyboard Shortcuts menu is opened in the Preferences window.

```
AttributeError: 'int' object has no attribute 'modifiers'
'int' object has no attribute 'modifiers'
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\plugins\shortcuts.py", line 158, in data
    return to_qvariant(Key.MODIFIERNAMES[key.modifiers[0]])
AttributeError: 'int' object has no attribute 'modifiers'
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\plugins\shortcuts.py", line 160, in data
    return to_qvariant(Key.MODIFIERNAMES[key.modifiers[1]])
AttributeError: 'int' object has no attribute 'modifiers'
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\plugins\shortcuts.py", line 162, in data
    return to_qvariant(Key.MODIFIERNAMES[key.modifiers[2]])
AttributeError: 'int' object has no attribute 'modifiers'
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\plugins\shortcuts.py", line 164, in data
    return to_qvariant(Key.KEYS[key.key])
AttributeError: 'int' object has no attribute 'key'
```

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2125_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:04:00Z_

**Labels:** MS-v2.3.4 Cat-Settings

**Comment by ccordoba12** [comment]
Just for you to notice it @blink1073 :-)
