### ISSUE TITLE
PYMC3 Issue

### ISSUE THREAD

**Issue by Bose-Priya** [spyder-ide/spyder#21254]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am trying to use the PYMC3 module in Anaconda. I added the package to the Anaconda Navigator software to ensure I could import it into Spyder. I tried to use the first example code from the website below,  where I was trying to replicate the linear regression model. However, when I tried to do this in Spyder, the code hangs and then nothing happens. This seems to be a Spyder problem because I was able to run the same code in Juyter Notebook super quickly. Why is it hanging? I am using Spyder 5.4.3, and the following modules: 

### What steps reproduce the problem?

1. Take the linear regression example code from: https://www.pymc.io/projects/docs/en/v5.7.2/learn/core_notebooks/pymc_overview.html. 
2. Use the following packages for Spyder 5.4.3: arviz 0.16.0, pandas 1.5.3, matplotlib.pyplot 3.7.1, numpy 1.25.2, and pymc 5.6.1.
3. Press Run.

### What is the expected output? What do you see instead?
The expected output is a progress bar after the first few status messages, and then a plot. However, I just see the status messages and nothing else. No other output is given. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.3
* Python version: 3.10.12 64-bit
* Qt version:  5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 11

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.25.2 (OK)
pandas >=1.1.1                                   :  1.5.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  None (NOK)

```

**Comment by Bose-Priya** [comment]
UPDATE: This command works if I use 500 draws instead of 1000. However, it should work with 1000 draws as well. I'm not sure why this is, or how to fix it.

**Comment by dalthviz** [comment]
Hi @Bose-Priya thank you for the feedback! I was able to get the progress bar after the initial message but also got some other messages about `g++`:

![image](https://github.com/spyder-ide/spyder/assets/16781833/7b08c303-0ed5-40f1-9532-66b78fa4adbf)

To do the test I created an env with the packages versions provided in the description, so running something like the following inside an Anaconda Prompt to create a `spyder-df-pymc` environment and launching Spyder from it:

```
conda create -n spyder-df-pymc python=3.10 spyder=5.4.3 arviz=0.16.0 pandas=1.5.3 matplotlib=3.7.1 numpy=1.25.2 pymc=5.6.1
conda activate spyder-df-pymc
spyder
```    

Regarding the initial warning messages that I got:

```
WARNING (pytensor.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain` 
WARNING (pytensor.configdefaults): g++ not detected!  PyTensor will be unable to compile C-implementations and will default to Python. Performance may be severely degraded. To remove this warning, set PyTensor flags cxx to an empty string.
WARNING (pytensor.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
```

I was able to remove them by closing Spyder and running `conda install m2w64-toolchain` (inside the Anaconda prompt with env activated)

Besides the above, I noticed that in the example code a graphic is generated and some config for the inline backend is done so maybe checking the preferences to see if you have the `Inline` backend selected could be worthy (for that check `Preferences > IPython Console > Graphics > Graphics backend`)

Also note that from inside Spyder to see the `idata` info you will need to do something like `idata["posterior"]` or getting the respective key for the `idata` section you want to check.

Finally, a preview of the last piece of code where a sampling algorithm is manually defined and a progress bar is shown:

![image](https://github.com/spyder-ide/spyder/assets/16781833/3040b35e-c63c-4cda-a982-c86add37c56b)

Just in case, the full code that I was running inside the IPython console:

```python
import arviz as az
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%config InlineBackend.figure_format = 'retina'
# Initialize random number generator
RANDOM_SEED = 8927
rng = np.random.default_rng(RANDOM_SEED)
az.style.use("arviz-darkgrid")
# True parameter values
alpha, sigma = 1, 1
beta = [1, 2.5]

# Size of dataset
size = 100

# Predictor variable
X1 = np.random.randn(size)
X2 = np.random.randn(size) * 0.2

# Simulate outcome variable
Y = alpha + beta[0] * X1 + beta[1] * X2 + rng.normal(size=size) * sigma
fig, axes = plt.subplots(1, 2, sharex=True, figsize=(10, 4))
axes[0].scatter(X1, Y, alpha=0.6)
axes[1].scatter(X2, Y, alpha=0.6)
axes[0].set_ylabel("Y")
axes[0].set_xlabel("X1")
axes[1].set_xlabel("X2");
import pymc as pm

print(f"Running on PyMC v{pm.__version__}")
basic_model = pm.Model()

with basic_model:
    # Priors for unknown model parameters
    alpha = pm.Normal("alpha", mu=0, sigma=10)
    beta = pm.Normal("beta", mu=0, sigma=10, shape=2)
    sigma = pm.HalfNormal("sigma", sigma=1)

    # Expected value of outcome
    mu = alpha + beta[0] * X1 + beta[1] * X2

    # Likelihood (sampling distribution) of observations
    Y_obs = pm.Normal("Y_obs", mu=mu, sigma=sigma, observed=Y)

with basic_model:
    # draw 1000 posterior samples
    idata = pm.sample()

with basic_model:
    # instantiate sampler
    step = pm.Slice()

    # draw 5000 posterior samples
    slice_idata = pm.sample(5000, step=step)
```

Seems like things are working from my side but let us know if the info above helps!

**Comment by Bose-Priya** [comment]
Hello @dalthviz!

I appreciate the quick feedback and advice! I tried to do what you said, but when I tried to run the same pymc code (aside from the last basic_model with loop), my spyder is still hanging. I have been running the code for about 20 minutes or so, and still only have the following output. 

`Running on PyMC v5.6.1
Auto-assigning NUTS sampler...
Initializing NUTS using jitter+adapt_diag...
Multiprocess sampling (4 chains in 4 jobs)
NUTS: [alpha, beta, sigma]`

I did install the m2w63-toolchain package into my new spyder environment, but I still can't get past the hang. I copied and pasted all the code that you used to create the new environment and the installation of the toolchain package.

Thanks,
@Bose-Priya

**Comment by dalthviz** [comment]
Are you trying to run the code as a whole file? How are you running the code? I was checking and indeed running the code as a file seems like stuck sometimes 🤔 However, if you want to run it as a whole file, I think you will need to put the code in an `.ipy` (so the `%config` magic can be recognized) and run it using `Run cell` (`Ctrl + Enter` or clicking the ![image](https://github.com/spyder-ide/spyder/assets/16781833/b22048ee-5395-4af3-97d2-626383f84c92) button).

Also, seems like setting the Editor option to paste the cell execution contents helps in case you are running the code from a file. To enable that you can go to `Preferences > Editor > Run code > Copy full cell contents to the console when running code cells`:
  
![image](https://github.com/spyder-ide/spyder/assets/16781833/95532884-c3d8-4c85-bbf8-044282cc86dc)

Following the steps above I'm avaible to see the progress bar running the code multiple times so let us know if something of the above helps!

![image](https://github.com/spyder-ide/spyder/assets/16781833/f47dca44-a0b4-4728-af2f-81633bc64d43)

**Comment by dalthviz** [comment]
Closing due to lack of response
