### ISSUE TITLE
Compatibility of Spyder standalone 5.4.4 with Windows Server 2016

### ISSUE THREAD

**Issue by GastaoDM** [spyder-ide/spyder#21258]
I tried to install Spyder standalone 5.4.4 with Windows Server 2016 in a VPS and got the following error.
![Windows 2016 - error](https://github.com/spyder-ide/spyder/assets/54849336/57038566-565c-4e21-b3fa-c014063f97de)

**Comment by dalthviz** [comment]
Hi @GastaoDM thank you for the feedback! Just adding some tracebility here: Issue opened following comments from https://github.com/spyder-ide/spyder/issues/19079

**Comment by ccordoba12** [comment]
@dalthviz and @mrclary, I think we should remove Spyder-terminal from our installers given that it's unmaintained and the inability of disable it right now.

**Comment by dalthviz** [comment]
Just in case, as a workaround in the meantime and if is it okay for @GastaoDM to use an alpha version, we have a differen Windows installer for the [6alpha1 release](https://github.com/spyder-ide/spyder/releases/tag/v6.0.0a1). I think it doesn't come with the spyder-terminal plugin so the error in the screenshot should not happen
