### ISSUE TITLE
Error when reloading pythonnet code in Spyder IDE

### ISSUE THREAD

**Issue by ARa2of** [spyder-ide/spyder#21269]
## Problem Description

Hello, 

I have used Spyder for years without issues. However, after getting a new laptop and reinstalling Spyder, I encountered problems with pythonnet.

Code that imports pythonnet modules like clr works on first run, but fails on reload with the error "RuntimeError: Failed to initialize Python.Runtime.dll".

As suggested in https://github.com/pythonnet/pythonnet/pull/2079, I adjusted Pythhonnet code when importing clr which fixed the reload issue.

However, this then surfaces another error on reload - "AttributeError: module 'clr' has no attribute 'AddReference'".

I have tried this with multiple versions of Anaconda, Miniconda, and Spyder but observe the same reloading issue.

Interestingly, the code works flawlessly when run in other IDEs like PyCharm, VSCode, and Visual Studio.

In Spyder, I have to restart the kernels everytime to avoid this error. 

A similar error has been also reported [here](https://github.com/pythonnet/pythonnet/issues/2099#issuecomment-1461278093 ) for Spyder. 

It seems to be an isolated problem with reusing pythonnet in Spyder. I would appreciate any suggestions on how to resolve the reload errors when importing clr. Let me know if any other details would be helpful.

### Paste Traceback/Error Below (if applicable)
```python-traceback
Traceback (most recent call last):

  File ~\AppData\Local\miniconda3\Lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File e:\TEST\python test\TEST_2023.py:15
    clr.AddReference('OSIsoft.AFSDK')

AttributeError: module 'clr' has no attribute 'AddReference'

```

## Versions

* Spyder version: 5.4.4
* Python version: 3.11.4
* Qt version (qt-main):  5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Windows 10 Pro

**Comment by dalthviz** [comment]
Hi @ARa2of thank you for the feedback! Could it be that disabling the UMR functionality could help here? For that you can go to `Preferences > Python interpreter > User Module Reloades (UMR)` and uncheck the `Enable UMR` checkbox or a `pythonnet` to the exclusion list (`Set UMR excluded (not reloaded) modules`). Also, is there an example script that you could share with us to reproduce this locally?

Any other info in order to better understand what could be happening here is greatly appreciated. Let us know!

**Comment by ARa2of** [comment]
> Hi @ARa2of thank you for the feedback! Maybe disabling the UMR functionality could help here? For that you can go to `Preferences > Python interpreter > User Module Reloades (UMR)` and uncheck the `Enable UMR` checkbox or add `pythonnet` to the exclusion list (`Set UMR excluded (not reloaded) modules`). Also, is there an example script that you could share with us to reproduce this locally?
> 
> Any other info in order to better understand what could be happening here is greatly appreciated. Let us know!

Disabling UMR has actually solved the problem! You are a star. Thanks a lot, I have been trying for a week! 

I assume it is worth mentioning this in the documents (or it might be mentioned but I missed it). 

Thanks for the great work and for Spyder!

**Comment by dalthviz** [comment]
Awesome, glad to know that things are working for you now! Just in case, I think the relevant doc entry related to the UMR functionality is available at https://docs.spyder-ide.org/current/panes/ipythonconsole.html?highlight=umr#reload-changed-modules
