### ISSUE TITLE
TclError: can't invoke 'tk' command: application has been destroyed

### ISSUE THREAD

**Issue by APWatsonDBA** [spyder-ide/spyder#21263]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
"TclError: can't invoke 'tk' command: application has been destroyed,"
When I run my ttkbootstrap program on the IDE, I get this error message but when I run it on the Anaconda cmd prompt it works. 
I noticed that it started when I updated to Spyder 5.4.3 so I went back to 5.4.1 but I am now going through the same thing. It even affects other files with just tkinter programs.

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?
a ttkbootstrap GUI

### Paste Traceback/Error Below (if applicable)

TclError: can't invoke 'tk' command: application has been destroyed

 the traceback below comes from a regular tkinter program but after I ran the ttkbootstrap it now applies to all other files
```python-traceback

Traceback (most recent call last):
  File "C:\Users\arlet\anaconda3\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "c:\users\arlet\documents\python scripts\from syper ide\pythonandsql\pdfdataextractsqlguiv2.py", line 140, in lstvalueslabels
    combobox = ttk.Combobox(window,values=tuplecbo,width=25,font=("Times New Roman",14))
  File "C:\Users\arlet\anaconda3\lib\site-packages\ttkbootstrap\style.py", line 4941, in __init__
    func(self, *args, **kwargs)
  File "C:\Users\arlet\anaconda3\lib\tkinter\ttk.py", line 702, in __init__
    Entry.__init__(self, master, "ttk::combobox", **kw)
  File "C:\Users\arlet\anaconda3\lib\site-packages\ttkbootstrap\style.py", line 4960, in __init__
    ttkstyle = Bootstyle.update_ttk_widget_style(
  File "C:\Users\arlet\anaconda3\lib\site-packages\ttkbootstrap\style.py", line 5050, in update_ttk_widget_style
    builder_method(builder, widget_color)
  File "C:\Users\arlet\anaconda3\lib\site-packages\ttkbootstrap\style.py", line 1215, in create_combobox_style
    arrowsize=self.scale_size(12),
  File "C:\Users\arlet\anaconda3\lib\site-packages\ttkbootstrap\style.py", line 1116, in scale_size
    winsys = self.style.master.tk.call("tk", "windowingsystem")
_tkinter.TclError: can't invoke "tk" command: application has been destroyed

```

## Versions

* Spyder version: 5.4.1
* Python version: 3.10.9
* Qt version: Qt 5.15.2
* PyQt version: PyQt5 5.15.7
* Operating System name/version: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.12.2 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.5.4 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0;<3.0           :  2.16.2 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.2 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.2 (OK)
qtpy >=2.1.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.6.3 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.3 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=22.1.0                  :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.7.0 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.0 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)

```

**Comment by dalthviz** [comment]
Hi @APWatsonDBA thank you for the feedback! Coudl you share with us an example script to run? Maybe updating Spyder caused the `ttkbootstrap` package or others to get updated/change versions causing the issue?

Any other info in order to reproduce this is greatly appreciated. Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
