### ISSUE TITLE
Request: copy entire line with CTRL+C and no selection

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#21264]
Many code editors, such as Visual Studio Code, Sublime Text, any JetBrain IDE, etc, will copy an entire line of code if you press Ctrl+C with the cursor on a line but nothing selected. I find this very useful and use it all the time. It would be nice to have this in Spyder, perhaps as a settable preference in Preferences/Editor, not the least because it is in muscle memory and I keep trying to do it over and over!

**Comment by dalthviz** [comment]
Hi @rlabbe thank you for the feedback! Seems like a reasonable feature to me :+1: Checking a little bit seems like the implementation of such a feature would be related with the following method: https://github.com/spyder-ide/spyder/blob/e65455692bc249fb88eeb56fe61e7181851f48c3/spyder/plugins/editor/widgets/base.py#L473-L479

Also, what do you think about the feature @spyder-ide/core-developers ?

**Comment by ccordoba12** [comment]
It seems reasonable to me and not so hard to implement. So I'd say we should do it.

**Comment by jitseniesen** [comment]
I like it, maybe we can do the same with CTRL+X? Though that seems to be implemented differently.

**Comment by dalthviz** [comment]
In case of the `cut` functionality I think the change will need to be done at https://github.com/spyder-ide/spyder/blob/e65455692bc249fb88eeb56fe61e7181851f48c3/spyder/plugins/editor/widgets/codeeditor/codeeditor.py#L1867-L1877

Checking seems like VSCode offers that functionality so it could be nice to have it :+1:

**Comment by ccordoba12** [comment]
> Checking seems like VSCode offers that functionality so it could be nice to have it 👍

How does it work in VSCode?

**Comment by dalthviz** [comment]
Same principle I would say. If you don't have a selection, the current line under the cursor gets cut (it's removed and put in the clipboard):

![cut](https://github.com/spyder-ide/spyder/assets/16781833/e3a18847-8236-4cac-b8bc-1c0b1da0b5cc)

**Comment by The-Ludwig** [comment]
Hello! Is there already a PR for this feature?
I am REALLY interested in this feature! :)

**Comment by ccordoba12** [comment]
No, we haven't had time to work on it, sorry.

**Comment by dalthviz** [comment]
Would you like to help implementing it @The-Ludwig ?

**Comment by The-Ludwig** [comment]
@dalthviz, yes very much so! If somebody gives me a hint at where to start (I already see some suggestions in this thread), I am happy to get started on this!

**Comment by The-Ludwig** [comment]
@ccordoba12 @dalthviz 
I got it working! Thanks for tipping me off to the right files! 
PR is #22480.

I have to say I was pleasantly surprised how easy it was to get a whole dev-setup for spyder to work, congrats for this level of maintainability! 

The PR mimics the behaviour of e.g. VSCode almost perfectly, except when it comes to pasting the copied/cut line again into the editor. There we need to modify `CodeEditor.paste`, which is a bit over my level of understanding this codebase. 
The problem basically is, that we need to remember if the current clipboard was cut/copied with no selection, and if so, then we always insert the content on the line above (as opposed to at the current cursor position, which could be the middle of the line). Further discussion over at the #22480 ?

**Comment by dalthviz** [comment]
Awesome! Thank you @The-Ludwig for wokring on this! And yep, I think we can further discuss details and possible follow up work over #22480 :+1:
