### ISSUE TITLE
Spyder 6.0.0a1 conda install - environment fails to solve issue and potential fix

### ISSUE THREAD

**Issue by chris-vecchio** [spyder-ide/spyder#21285]
## Versions
- Python version: 3.11.4
- IPython version: 8.14.0
- Operating System name/version: Windows 10 Pro 21H2
- Conda version: 23.5.2

## Issue
The conda install instructions for Spyder 6.0.0a1 are as follows:

```conda install -c conda-forge/label/spyder_dev -c conda-forge spyder=6.0.0a1```

Running this command returns an Unsatisfiable Error. The returned error message is below:

```
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/win-64::__win==0=0
  - spyder=6.0.0a1 -> ipython[version='>=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0'] -> __linux
  - spyder=6.0.0a1 -> ipython[version='>=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0'] -> __win

Your installed version is: not available
```

Given that I have IPython version 8.14.0 installed, this error message seemed strange.

As a test, I used Anaconda's new libmamba solver to see if it would give the same result. I went with the libmamba solver as Anaconda said it could succeed where the current solver fails. After installing the libmamba solver, I ran the following command:

```conda install -c conda-forge/label/spyder_dev -c conda-forge spyder=6.0.0a1 --solver=libmamba```

and received the following error message:

```
LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides spyder-kernels >=3.0.0b1,<3.0.0b2 needed by spyder-6.0.0a1-py311h6f0a7d0_0

Could not solve for environment specs
The following package could not be installed
└─ spyder 6.0.0a1**  is uninstallable because it requires
   └─ spyder-kernels >=3.0.0b1,<3.0.0b2 , which does not exist (perhaps a missing channel).
```

The libmamba solver reports that it's the spyder-kernels version availability that's an issue and there might be a channel missing. I looked up spyder-kernels on Anaconda.org and found a label that would provide the required version of spyder-kernels: ```spyder_kernels_rc```.

I then retried the install command with the added spyder_kernels_rc label:

```
conda install -c conda-forge/label/spyder_dev -c conda-forge/label/spyder_kernels_rc -c conda-forge spyder=6.0.0a1 --solver=libmamba
```
and the environment solved successfully and I was able to install Spyder 6.0.0a1.

Just reporting in case anyone else has a similar issue or if the documentation needs to be updated. I am very aware that it could be something about my setup that caused it as well. Let me know if you need any other information.

**Comment by dalthviz** [comment]
Hi @chris-vecchio thank you for the feedback! Indeed, I think you need to use the `conda-forge/label/spyder_dev` and `conda-forge/label/spyder_kernels_rc` channel specifications to install Spyder 6 alpha versions with conda.

I think the [Spyder 6.0.0alpha1 release page has some instructions to install it using conda (under the `Advanced installation section`)](https://github.com/spyder-ide/spyder/releases/tag/v6.0.0a1). However, seems like those are missing the `conda-forge/label/spyder_kernels_rc` channel specification :thinking: Seems like we need to update that!

Also, seems like some notes regarding the package being available in the Anaconda distribution are being mentioned there but I think those don't apply for alphas. What do you think @ccordoba12 ?

**Comment by chris-vecchio** [comment]
Thanks @dalthviz! I appreciate the reply! I LOVE Spyder so I am just happy I could even help in a tiny way.

**Comment by ccordoba12** [comment]
> Also, seems like some notes regarding the package being available in the Anaconda distribution are being mentioned there but I think those don't apply for alphas. What do you think @ccordoba12 ?

You're right @dalthviz. I'll fix the notes right away.

**Comment by ccordoba12** [comment]
>  I appreciate the reply! I LOVE Spyder so I am just happy I could even help in a tiny way.

Thanks for opening this issue and for your kind words @chris-vecchio! Happy to know you enjoy using Spyder!!

I updated the installation instructions to include the missing label and remove some comments about waiting for Spyder 6 alphas to appear in the defaults channel. So, I think we can close this issue now.
