### ISSUE TITLE
Spyder application launch error

### ISSUE THREAD

**Issue by dirtpawTW** [spyder-ide/spyder#21283]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder``
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I am unable to start Spyder on a clean install of Windows 11 and Anaconda Navigator. When I try to start Spyder from the Anaconda Prompt Console, nothing happens for three seconds and then the console jumps to the next line ready for the next command. If I try to launch Spyder from Anaconda Navigator, I get the error mentioned below.

### What steps reproduce the problem?

1. Installed latest version Anaconda3-2023.07-2-Windows-x86_64.exe following the installation guide
2. Open Anaconda Prompt
3. Create a new environment for Spyder with ``conda create -c conda-forge -n spyder-env spyder``
4. Activate the new environment ``conda activate spyder-env``
5. Launch Spyder ``spyder``

### What is the expected output? What do you see instead?

Spyder should launch.

Nothing happens for three seconds and then the console jumps to the next line ready for the next command.

### Paste Traceback/Error Below (if applicable)

```python-traceback

A new Anaconda Navigator window opens showing:
Application launch error
Application spyder launch may have produced errors.
Exit code: 3221225477

```

## Versions

* Spyder version: 5.4.4
* Python version: 3.11.4
* Qt version: 5.15.8 (qt-main)
* Qt version: 5.4.3 (qtconsole)
* PyQt version: 5.15.9
* Operating System name/version: Windows 11 Pro 22H2
* Conda version: 23.7.3

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @dirtpawTW, thanks for reporting. Please open the Anaconda Prompt and run there:

    conda activate spyder-env
    spyder --debug-info verbose --debug-output file

and upload here a file called `spyder-debug.log` that should be created in the same directory where you ran the commands above.

That will give us more information about why Spyder is failing to launch in your system.

**Comment by dirtpawTW** [comment]
Hello @ccordoba12 ,

thank you for your quick response.
I'm a bit embarrassed about this now, but I was able to solve the problem (after 5 days of trying). I uninstalled all programs based on Python (QGIS, GIMP, etc.) for all users of the computer and then installed Anaconda first and then the other programs again.

Now it looks like everything is working fine again.

Note: before that, I executed the command you mentioned and the file was empty.

**Comment by ccordoba12** [comment]
No worries, that's fine. The most important thing is that you Spyder is working for you again.

**Comment by Lugle29** [comment]
Hello @dirtpawTW, I encounter the same problem like you and get the same error code, hence I would like to try out your solution but how do I know, which programs are based on Python?

**Comment by dirtpawTW** [comment]
Hi @Lugle29, I opened the C:\ directory and searched for Python using the search bar.

**Comment by Lugle29** [comment]
Thank you very much for the fast response. Unfortunately uninstalling/deleting every other python program is not working for me.

**Comment by dragi86** [comment]
hi all, im having exact same issues and did the following:

1) https://docs.spyder-ide.org/current/installation.html - followed these instructions and when launching spyder via the new environment on Anaconda or via the Anaconda prompt, SPyder DID NOT run successfully. Anaconda navigatr gave me the usual error: Exit code 3221225477

2) Before 1) I removed all python related files as well and had no Anaconda or Python-related application installed on my Windows machine.

3) Ran conda `activate spyder-env` and ` spyder --debug-info verbose --debug-output file` and got an empty log file ...

Im really stuck with this and the issue happedned following a recent Windows upgrade ... this is extremely inconvenient. Any feedback and help is apprecaited team.. Thank you.

**Comment by ccordoba12** [comment]
@dragi86, what output do you see when you run Spyder from the Anaconda prompt with the following commands?

    conda activate spyder-env
    spyder --reset
    spyder

**Comment by sjm2278** [comment]
Anybody get this to work? I uninstalled and reinstalled spyder and anaconda but I'm still getting the same error code.

**Comment by llancruzz** [comment]
First => Update Anaconda and Spyder

conda update conda
conda update anaconda
conda update spyder

Second => Create a New Environment

conda create -n spyder-env python=3.9 spyder
conda activate spyder-env
spyder

Note: It worked for me after uninstall all program related to ananconda, then install it again and do this 2 process above.
