### ISSUE TITLE
test_get_user_environment_variables fails in autopkgtest/schroot environment

### ISSUE THREAD

**Issue by bdrung** [spyder-ide/spyder#21297]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The spyder 5.4.4+ds-1 test suite fails when running inside an autopkgtest environment:

```
=================================== FAILURES ===================================
_____________________ test_get_user_environment_variables ______________________

    def test_get_user_environment_variables():
        """Test get_user_environment_variables function"""
        # All platforms should have a path environment variable, but
        # Windows may have mixed case.
        keys = {k.lower() for k in get_user_environment_variables()}
> assert "path" in keys
E AssertionError: assert 'path' in {'_', 'debuginfod_urls', 'home', 'lc_ctype', 'pwd', 'shlvl'}

spyder/utils/tests/test_environ.py:42: AssertionError
_________________________________ test_environ _________________________________

environ_dialog = <spyder.utils.environ.UserEnvDialog object at 0x7ff4e3e3b400>
qtbot = <pytestqt.qtbot.QtBot object at 0x7ff4e39caad0>

    def test_environ(environ_dialog, qtbot):
        """Test the environment variables dialog."""
        environ_dialog.show()
        assert environ_dialog

        # All platforms should have a path environment variable, but
        # Windows may have mixed case.
        keys = {k.lower() for k in environ_dialog.get_value()}
> assert "path" in keys
E AssertionError: assert 'path' in {'_', 'debuginfod_urls', 'home', 'lc_ctype', 'pwd', 'shlvl'}

spyder/utils/tests/test_environ.py:64: AssertionError
=============================== warnings summary ===============================
```

Full test log: https://autopkgtest.ubuntu.com/results/autopkgtest-mantic/mantic/amd64/s/spyder/20230829_120749_03021@/log.gz

Ubuntu bug: https://bugs.launchpad.net/ubuntu/+source/spyder/+bug/2033518

### What steps reproduce the problem?

Running something similar to the spyder code does not contain the PATH variable:

```
$ env -i bash -l -c env | sort
DEBUGINFOD_URLS=https://debuginfod.ubuntu.com/
PWD=/tmp/autopkgtest.wq0cE8/build.3Mr/real-tree
SHLVL=0
_=/bin/env
```

Using the code from the master branch (as of 2023-08-30) did not fix the issue:

```
$ cat user-env.sh
#!/bin/bash -i
unset HISTFILE
/bin/bash -l -c "/usr/bin/python3 -c 'import os; print(dict(os.environ))'"
$ env -i ./user-env.sh
{'PWD': '/home/myuser', 'SHLVL': '1', '_': '/usr/bin/python3', 'LC_CTYPE': 'C.UTF-8'}
```

I can also reproduce it in a schroot.

## Versions

* Spyder version: 5.4.4+ds-1
* Python version: 3.11.4-5
* Qt version: 5.15.10+dfsg-3
* PyQt version: 5.15.9+dfsg-2
* Operating System name/version: Ubuntu 23.10 (mantic)

**Comment by ccordoba12** [comment]
Hey @bdrung, thanks for reporting. It seems in very constrained environments (like the one you're using to test Spyder), the `PATH` env var is not available.

@mrclary, perhaps we could use a more fundamental variable for the test in Posix systems, like `SHLVL`?

**Comment by ccordoba12** [comment]
This

    $ env -i bash -l -c env | sort

shows `PATH` on my Linux desktop, so I don't know why it doesn't in your env.

**Comment by bdrung** [comment]
In the chroot there is no `~/.bashrc` or `~/.inputrc`.

**Comment by mrclary** [comment]
> Hey @bdrung, thanks for reporting. It seems in very constrained environments (like the one you're using to test Spyder), the `PATH` env var is not available.
> 
> @mrclary, perhaps we could use a more fundamental variable for the test in Posix systems, like `SHLVL`?

We could do that.
But I'm curious why `PATH` is in the OP environment but not picked up by `get_user_environment_variables`. The intention of `get_user_environment_variables` is to obtain the environment variables that the user would have when opening an interactive shell. If `get_user_environment_variables` does not faithfully report these values under certain circumstances, I'd like to investigate how to correct for that.

**Comment by bdrung** [comment]
Why do you call bash with an empty environment?

**Comment by mrclary** [comment]
> Why do you call bash with an empty environment?

Spyder modifies `os.environ` for some internal operations and, by default, `subprocess` will inject `os.environ` into subprocesses. Therefore, in order to faithfully obtain environment variables that a user would have in an interactive (login) shell, a subprocess should be launched with an empty environment (`env={}`) but source interactive and login startup files (`-i` and  `-l`).
