### ISSUE TITLE
Update Jedi dependency upper bound

### ISSUE THREAD

**Issue by AdamWill** [spyder-ide/spyder#21296]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [-] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [-] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [-] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder currently sets an upper bound on its jedi dependency of 0.19.0, in several files - `binder/environment.yml`, `external-deps/python-lsp-server/pyproject.toml`, `requirements/main.yml`, `setup.py` and `spyder/dependencies.py` at least. Upstream lsp, which is where this dependency comes from I believe, [bumped it to 0.20.0 recently](https://github.com/python-lsp/python-lsp-server/pull/416) with the note that there "don't seem to be any breaking changes". spyder should probably inherit this bump so it can be used with jedi 0.19.

### What steps reproduce the problem?

1. Try and install spyder with jedi 0.19.

### What is the expected output? What do you see instead?

It fails, but it should be allowed.

## Versions

This is present in current git head and all supported branches.

**Comment by AdamWill** [comment]
I'd send a PR for this, but I couldn't find an explanation of the procedure for bumping a dependency that comes from lsp like this.

**Comment by ccordoba12** [comment]
Hey @AdamWill, thanks for reporting and for the offer to help.

> I'd send a PR for this, but I couldn't find an explanation of the procedure for bumping a dependency that comes from lsp like this.

That's right, we don't have one, but the procedure is like this:

* Open a PR against our `5.x` branch (our maintenance one), so this can be part of our next version (5.5.0).
* Synchronize our `python-lsp-server` subrepo, as described [here](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md#making-contributions-that-depend-on-pull-requests-in-python-lsp-server-or-qtconsole) (use the last command on that section). That will update the dependency in `external-deps/python-lsp-server/pyproject.toml`.
* Bump our Jedi requirement to `>=0.17.2,<0.20` in the other files you mentioned (`binder/environment.yml`, `requirements/main.yml`, `setup.py` and `spyder/dependencies.py`).

That should do it, but let me know if you have other questions about this process.

**Comment by musicinmybrain** [comment]
> That should do it, but let me know if you have other questions about this process.

I think I’ve done it correctly…
