### ISSUE TITLE
Codesign hangs on macOS installer

### ISSUE THREAD

**Issue by mrclary** [spyder-ide/spyder#21302]
## Problem Description

During the macOS installer build, `constructor` attempts to replace the code signature in the standalone conda executable and hangs.
```
/Users/rclary/.conda/constructor/osx-64/package_root/spyder-6/conda.exe: replacing existing signature
```

I cannot reproduce this issue locally and it appears to afflict only CI. The certificates and secrets for the repository are correct as they are successfully used for other codesigning events in this repository.

I suspect that a gui prompt is presented, causing the appearance of hanging.
<img width="436" alt="Screenshot 2023-09-03 at 6 55 07 PM" src="https://github.com/spyder-ide/spyder/assets/9618975/5701a3c5-07ff-4885-a346-9108f626badd">
I can simulate this locally by removing
```
security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $KEY_PASS $KEYCHAIN
```
from [installers-conda/certkeychain.sh](https://github.com/spyder-ide/spyder/blob/007d8d4bba20309eeb580cfd2c88bbf31e66cabd/installers-conda/certkeychain.sh#L81).

However, this issue does not manifest for our other codesigning events that use the same mechanism for gui prompt suppression. Furthermore, this has worked in the past, e.g. Spyder 6.0.0alpha1 release.

Interestingly, [napari/packaging](https://github.com/napari/packaging/blob/main/.github/workflows/make_bundle_conda.yml) does not use this mechanism (or any mechanism that I can see) for gui prompt suppression with `constructor` codesign events and does not appear to have this issue. @jaimergp, do you have any insight on this?

**Comment by jaimergp** [comment]
Check [this block](https://github.com/napari/packaging/blob/d3190186a258898475e64ede12d39a8e255f2e55/.github/workflows/make_bundle_conda.yml#L372-L377). In my case it didn't hang though, it errored out.

**Comment by mrclary** [comment]
> Check [this block](https://github.com/napari/packaging/blob/d3190186a258898475e64ede12d39a8e255f2e55/.github/workflows/make_bundle_conda.yml#L372-L377). In my case it didn't hang though, it errored out.

Thanks @jaimergp, but I have the same [block](https://github.com/spyder-ide/spyder/blob/007d8d4bba20309eeb580cfd2c88bbf31e66cabd/.github/workflows/installers-conda.yml#L182-L187), the absence of which results in an error for me as well rather than hang.

**Comment by ccordoba12** [comment]
> Furthermore, this has worked in the past, e.g. Spyder 6.0.0alpha1 release.

Nop, it hasn't. Code signing was disabled for that release.

So, could we disable it again for alpha2? It seems this is going to take you some time to solve, so that way we could continue finish that release and continue with alpha3.

**Comment by jaimergp** [comment]
> > Check [this block](https://github.com/napari/packaging/blob/d3190186a258898475e64ede12d39a8e255f2e55/.github/workflows/make_bundle_conda.yml#L372-L377). In my case it didn't hang though, it errored out.
> 
> Thanks @jaimergp, but I have the same [block](https://github.com/spyder-ide/spyder/blob/007d8d4bba20309eeb580cfd2c88bbf31e66cabd/.github/workflows/installers-conda.yml#L182-L187), the absence of which results in an error for me as well rather than hang.

Hm, I'd use the tmate action to log in in the CI server after the failure and investigate, then. I haven't seen this in macOS, but I did get some lack-of-user-interaction hangs with menuinst and I was able to debug using that method. I guess you can also throw in some `sudo` here and there and see what happens. The runners should have auto-sudo though, so it shouldn't be hanging 🤔  Maybe it's prompting for the certificate password?

**Comment by mrclary** [comment]
> Nop, it hasn't. Code signing was disabled for that release.

Aarg. I forgot about that. 

> So, could we disable it again for alpha2? It seems this is going to take you some time to solve, so that way we could continue finish the release and continue with alpha3.

Yeah, we better do that. I'll submit a PR.

**Comment by mrclary** [comment]
> > > Check [this block](https://github.com/napari/packaging/blob/d3190186a258898475e64ede12d39a8e255f2e55/.github/workflows/make_bundle_conda.yml#L372-L377). In my case it didn't hang though, it errored out.
> 
> > 
> 
> > Thanks @jaimergp, but I have the same [block](https://github.com/spyder-ide/spyder/blob/007d8d4bba20309eeb580cfd2c88bbf31e66cabd/.github/workflows/installers-conda.yml#L182-L187), the absence of which results in an error for me as well rather than hang.
> 
> 
> 
> Hm, I'd use the tmate action to log in in the CI server after the failure and investigate, then. I haven't seen this in macOS, but I did get some lack-of-user-interaction hangs with menuinst and I was able to debug using that method. I guess you can also throw in some `sudo` here and there and see what happens. The runners should have auto-sudo though, so it shouldn't be hanging 🤔  Maybe it's prompting for the certificate password?

Yeah, I'll have to play around some more with it. Thanks for your input.
