### ISSUE TITLE
Conda manager: merge install/remove columns

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2130]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T03:53:04Z_

Spyder Version:  2.4.0dev (4711+: rb5a5ef2bb4d5 )
Python Version:  3.4.2
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.3 (OK)
jedi >=0.8.1    :  0.8.1-final0 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK) 

What steps will reproduce the problem?

 

What is the expected output? What do you see instead?

 There are currently two separate columns for isntall and remove. These actions are mutually exclusive, so they could be merged into one to gain some horizontal space and lower the interface clutter. The different icons with different colors sould be more thn enough to distinguish between the two actions.

Please provide any additional information below

.
Looks like I can't add labels to the issue, this is not a bug but a possible improvement.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2130_

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T01:50:08Z_

Hi, 

So if I understand correctly, you say there should only be 3 columns, so that when there is a package that is installable it should  display the install button, but if it is install the button should be to remove?

\# not installed package
name | description | R | U | D |

\# installed package
name | description | I | U | D |

Cheers

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T02:07:29Z_

Yes exactly !

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:11:13Z_

**Labels:** MS-v2.4 Cat-Miscelleneous

**Comment by goanpeca** [comment]
Working on this from next week!

**Comment by Nodd** [comment]
Relocated to https://github.com/spyder-ide/conda-manager/issues/4
