### ISSUE TITLE
Conda manager: Closing spyder while installing packages

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2131]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T03:56:04Z_

Spyder Version:  2.4.0dev (4711+: rb5a5ef2bb4d5 )
Python Version:  3.4.2
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.3 (OK)
jedi >=0.8.1    :  0.8.1-final0 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK) 

What steps will reproduce the problem?

 1. Install some package
2. Close spyder while the installation is running 

What is the expected output? What do you see instead?

 There should at least be a "are you sure ?" kind of warning when closing spyder. I didn't have the time to check if the installation continued correctly in the background, but if it is not the case it can potentially break anaconda.

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2131_

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T01:51:42Z_

True, I should add a warning asking if they want to leave.

I do not thinks it is likely that anything will be broken, because the package is only listed as correctly installed at the end, so if something went wrong in the middle is like it has not been installed at all (I have had this situation)

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T02:11:15Z_

What about updates then ? At some point conda has to remove the old one and put the new one instead, so if it stops here the package might be broken. I admit these are only suppositions here, but somehow it doesn't look safe...

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:12:00Z_

**Labels:** Cat-Miscelleneous MS-v2.4

**Comment by goanpeca** [comment]
Working on this from next week!

**Comment by Nodd** [comment]
Relocated to https://github.com/spyder-ide/conda-manager/issues/3
