### ISSUE TITLE
자료구조 2주차

### ISSUE THREAD

**Issue by futurevibe** [spyder-ide/spyder#21314]

**Comment by dalthviz** [comment]
Hi @futurevibe ! Seems like the submitted issue is empty. Could you provide some more info about your setup and the specific issue you are experiencing? Also, be sure to be using the latest Spyder release (Spyder 5.4.5). If that is not the case I would suggest to try to update Spyder and see if the issue persists.

For more info you can check the Spyder docs troubleshooting guide: https://docs.spyder-ide.org/current/troubleshooting/index.html

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
