### ISSUE TITLE
Menu bar entries are too close to each other

### ISSUE THREAD

**Issue by chguw** [spyder-ide/spyder#21326]
## Problem Description
The menu bar entries are too close to each other, it looks like a sentence but not entries.

This is what it looks like compare to VSCode:

![2023-09-12_133137](https://github.com/spyder-ide/spyder/assets/6346659/b22b3109-29ea-4c67-a42c-a7412723e024)

![2023-09-12_133440](https://github.com/spyder-ide/spyder/assets/6346659/a5b37d82-f19c-4f2f-8ebc-85c151cfb83d)

## Versions

* Spyder version:  5.4.5
* Python version: 3.8.10
* Qt version: 5.15.2
* PyQt version: 5.15.9
* Operating System name/version: Win10 22H2

**Comment by ccordoba12** [comment]
Hey @chguw, thanks for reporting. I agree this is a problem and we'll try to fix it in Spyder 6, to be released before the end of the year.
