### ISSUE TITLE
Conda manager: Installing multiple packages

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2132]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T04:00:26Z_

Spyder Version:  2.4.0dev (4711+: rb5a5ef2bb4d5 )
Python Version:  3.4.2
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.3 (OK)
jedi >=0.8.1    :  0.8.1-final0 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 Currently each action is separate. To isntall multiple packages you have do install one, wait for isntallation, install another, wait for installation... A better workflow would be that instead of installing right away, clicking on a button would mark the package to be installed, then a button "apply" would have to be clicked in order to actually do the install, allowing to select multiple packages before applying.

Please provide any additional information below

.
I don't know if it is possible to both install and remove packages at once. If it is not possible, packages to remove should be inistalled first, then the pachages to install would be installed, to avoid removing a dependancy.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2132_

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T01:56:40Z_

Hi again,

Yes, this has been considered as well, but for this first iteration was left out as it would raise too many maintenance issues.I think that mixing actions would be too much, I would rather have a select button at the beginning of each row and a apply to all workflow (remove all, install all for now). 

But this again raises many dependency issues, you can choose to install two packages, but depending on the order they get installed, something might break if the second package depends on an inferior version. 

I would rather create conda recipes (a metapackage like anaconda) on binstar for common use cases in Spyder.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T02:15:44Z_

About mixed actions, another option is to disable uninstalls if an install button has been pressed, and vice-versa. A checkbox could be simpler though.

About dependancies, when using the command line you can ask to install or update many packages in one command, and conda checks the new state as a whole. It should be possible to do the same via the api ?

I'm not sure if binstar recipes are easily discoverable. But a recipe containing all the optional dependancies for spyder could be useful.

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T02:20:14Z_

About dependencies, not sure if conda is smart enough... for instance

conda install package_1=1.1, package_2=2.3

if package_2 has as dependency package_1=1.0, then I do not know what will happen here... package_1 is not installed, or it is and then it gets downgraded so package_2 works?

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T02:21:34Z_

Binstar recipes WILL be easily discoverable, because the Spyder Binstar channel will be  active by default, so you will be able to see the recipes right away, and of course tutorial and other stuff might help on this. do you have a general setup in mind for an specific branch?

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T03:44:45Z_

By optional dependencies I meant stuff like rope, pep8, flake, jedi, sphinx, sympy...

Other than that I guess that the default install in anaconda already coverts most needs.

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T04:32:23Z_

I think in this case it would work much better if we included it as a Spyder specific recipe, which would get listed in the CondaPackageManager... similar to how anaconda gets listed. We can call it additional-spyder ... so it gets listed on the first packages

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-23T18:27:07Z_

**Labels:** MS-v2.4 Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:12:26Z_

**Labels:** -Cat-SpyderGUI Cat-Miscelleneous

**Comment by goanpeca** [comment]
Working on this from next week!

**Comment by Nodd** [comment]
Relocated to https://github.com/spyder-ide/conda-manager/issues/2
