### ISSUE TITLE
Tests seems to be passing but fail

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#21322]
Tests seems to be passing but fail. If you go to the detail of the tests, failing tests come back with a little green check somehow.

For example : https://github.com/spyder-ide/spyder/actions/runs/6132598053/job/16643637158?pr=21320

Under "run test" I get:
```
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
[90](https://github.com/spyder-ide/spyder/actions/runs/6132598053/job/16643637158?pr=21320#step:15:91)
======================== 8 warnings, 1 error in 19.75s =========================
```

But the test has a little green check???

**Comment by impact27** [comment]
If I read this correctly, even the tests on master are not passing:

https://github.com/spyder-ide/spyder/actions/runs/6080113293/job/16494479819

```
===== 4 failed, 142 passed, 1157 skipped, 9 warnings in 1985.60s (0:33:05) =====
```

**Comment by ccordoba12** [comment]
Thanks for noticing this @impact27. I don't understand why the CI workflows are not failing but will check that.

**Comment by impact27** [comment]
@ccordoba12 some of the tests are fixed in https://github.com/spyder-ide/spyder/pull/21323

**Comment by ccordoba12** [comment]
Thanks @impact27! I'll merge it right away.

**Comment by impact27** [comment]
@ccordoba12 should this be closed now that https://github.com/spyder-ide/spyder/pull/21330 is merged?

**Comment by ccordoba12** [comment]
Not yet because our tests are still failing on master. In #21330 I fixed what you reported and our tests on `5.x`.

So, I'll close this issue once everything is green again. I'm working on that in PR #21102.
