### ISSUE TITLE
Conda manager: confirmation popup

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2133]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-23T04:03:31Z_

Spyder Version:  2.4.0dev (4711+: rb5a5ef2bb4d5 )
Python Version:  3.4.2
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.3 (OK)
jedi >=0.8.1    :  0.8.1-final0 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.0 (OK) 

What steps will reproduce the problem?

 1. 2. 3. 

What is the expected output? What do you see instead?

 Right now the confirmation popup is divided in 4 parts, similar to conda command line interface. Most of the time the same package appear in multiple sections. I think it doesn't work well with a gui, I would expect a table indicating for each package what action will be performed (uninstall, unlink, download...).

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2133_

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-01-23T01:57:38Z_

Agreed, good idea :), will put it on my todo list

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:13:00Z_

**Labels:** MS-v2.4 Cat-Miscelleneous

**Comment by goanpeca** [comment]
Working on this from next week!

**Comment by Nodd** [comment]
Relocated in https://github.com/spyder-ide/conda-manager/issues/1
