### ISSUE TITLE
Add link to Sphinx documentation from Preferences related to docstring

### ISSUE THREAD

**Issue by PanderMusubi** [spyder-ide/spyder#21359]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In Preferences / Editor / Advanced settings / Docstring type the user can chose from three types, being Numpy, Google and Sphinx.

### What steps reproduce the problem?

1. Open Preferences / Editor / Advanced settings
2. Look at Docstring type there are two links to documentation between brackets for Numpy and Google, but a link for Sphinx is missing.

![Screenshot from 2023-09-20 23-13-44](https://github.com/spyder-ide/spyder/assets/198964/e30362b1-e551-452a-a70e-fd8d740658df)

### What is the expected output? What do you see instead?

Between brackets should be `(Numpy, Google or Sphinx)` with on Sphinx the link https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

### Paste Traceback/Error Below (if applicable)
n/a

## Versions
* Spyder version: 5.4.5  (pip)
* Python version: 3.10.12 64-bit
* Qt version: 5.15.3
* PyQt5 version: 5.15.6
* Operating System: Linux-6.4.6-76060406-generic-x86_64-with-glibc2.35

### Dependencies
```# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  4.0.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree >=3.0.2                                                        :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  3.2.0 (OK)
keyring >=17.0.0                                                            :  23.5.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.0 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.4 (OK)
qtpy >=2.1.0                                                                :  2.4.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  59.6.0 (OK)
sphinx >=0.6.6                                                              :  7.2.6 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog >=0.10.3                                                           :  3.0.0 (OK)
xdg >=0.26                                                                  :  0.27 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  None (NOK)
numpy >=1.7                                                                 :  1.21.5 (OK)
pandas >=1.1.1                                                              :  1.3.5 (OK)
scipy >=0.17.0                                                              :  1.8.0 (OK)
sympy >=0.7.3                                                               :  None (NOK)```

**Comment by ccordoba12** [comment]
Hey @PanderMusubi, this is a valid point, thanks for bringing it up. We'll address it in our next version (5.5.0), to be released next month.

**Comment by PanderMusubi** [comment]
@ccordoba12 thanks! Two related question I would like to ask before making feature requests for it.

1) With https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html and using type hints, it is no longer needed to write parameter type and return type in the docstring. That is extracted automatically by Sphinx from the method header. Would it be well received to create a feature request that in the preferences can be chosen that Ctrl+Alt+D generates a docstring template without parameter type and return type? The benefit is that the user don't has to remove those from the generated template manually like is now the case. This option should only be available when Sphinx is chosen as docstring type. Perhaps also for the Numpy and Google docstring type when the possibility exists that these can be extacted from the type hinting, but I don't know that.

2) A feature request that the generated docstring does not start and end with `"""` but with `'''`. This is a style choice that is that makes the source code look more relaxed. It is accepted by all well-known linters and document generation tools.

**Comment by ccordoba12** [comment]
> Would it be well received to create a feature request that in the preferences can be chosen that Ctrl+Alt+D generates a docstring template without parameter type and return type?

The problem with that is that `autodoc` requires importing the module you're working on to do its job (there's a warning about it in the webpage you referenced). So, I doubt that would work for simple scripts, i.e. those that are not actual software projects and don't use Sphinx for its documentation. In addition, running `autodoc` could be time consuming for large projects.

> The benefit is that the user don't has to remove those from the generated template manually like is now the case.

Could you post a screenshot about it so we better understand what you mean by this? Thanks!

> A feature request that the generated docstring does not start and end with """ but with '''.

I think this is a valid request and we can implement it without too much troubles. So, please open a new issue about it.

**Comment by PanderMusubi** [comment]
Yes, here is the screenshot showing the lines that should not be generated.

![Screenshot from 2024-04-30 09-11-45](https://github.com/spyder-ide/spyder/assets/198964/ff4ef095-143b-4dbf-a15d-aa6c7c46f11e)

Shall I make a separate issue for this?

For the second question, please see https://github.com/spyder-ide/spyder/issues/22042 and https://github.com/spyder-ide/spyder/issues/22043
