### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by jingobelll** [spyder-ide/spyder#21361]
## Problem Description
Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed (>= 2.2.0 and < 2.3.0). Without this module is not possible for Spyder to create a console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels=2.2

or

pip install spyder‑kernels==2.2.*

The spyder kernel has already been 2.2.0 version but still shows the error

already tried upgrading and resetting, but nothing works

## Versions

* Spyder version: 5.2.1
* Python version: 3.7.09
* Qt version: 5.12.10
* PyQt version: 5.12.3
* Operating System name/version:  Win 10

**Comment by ccordoba12** [comment]
Hey @jingobelll, thanks for reporting. You need to install the right version of Spyder-kernels in the external environment you're trying to connect to in

    Tools > Preferences > Main interpreter

If you're doing that in the same environment where Spyder is installed, then you won't see any effect.

Let us know if that's clear to you or you need additional help.

**Comment by jingobelll** [comment]
Thank you for your reply.
How can I check whether I installed the kernel in the same environment where Spyder is installed 
and how to install kernels in the external environment.
Thank you!

**Comment by ccordoba12** [comment]
In order to help you with that, please go to the menu

    Tools > Preferences > Main interpreter

and post a screenshot of it so I can take a look at your interpreter configuration.

**Comment by jingobelll** [comment]
![image](https://github.com/spyder-ide/spyder/assets/145687686/10007a02-55c8-4d3a-addd-b4dbb8898ce6)

Spyder works under the default option but does not work under the chosen interpreter.

**Comment by ccordoba12** [comment]
Ok, no problem. Then you need to close Spyder, open a terminal and run the following command there:

    C:/Users/FA110/AppData/Local/Programs/Python/Python36/python.exe -m pip install spyder-kernels==2.2.*

After starting Spyder again you shouldn't see the message you reported above.

**Comment by jingobelll** [comment]
I followed your steps 
![image](https://github.com/spyder-ide/spyder/assets/145687686/b4900c0c-72dc-4f19-8d74-bd35365923da)
but it still has the same problem as I mentioned first
Then I deleted the site package in the Roaming folder and reinstalled spyder-kernels
![image](https://github.com/spyder-ide/spyder/assets/145687686/03900f82-32f0-4cf8-8da3-06573c687203)
And it shows errors like this
![image](https://github.com/spyder-ide/spyder/assets/145687686/43717f3a-ccbe-4f2f-a545-19fedddfd7cd)

**Comment by jingobelll** [comment]
Now I have installed Spyder version 5.4.5
![image](https://github.com/spyder-ide/spyder/assets/145687686/6239a557-5a94-438f-b09a-4682a4a73931)
the same problem as the first, then I tried your steps.
It shows
![Uploading image.png…]()

**Comment by ccordoba12** [comment]
Thanks for the updates @jingobelll! About your comments:

> Now I have installed Spyder version 5.4.5

I'm afraid you'll have to install again Spyder 5.2.2, which was the last version to support Python 3.6. That's why you're getting the last error you reported above.

> And it shows errors like this

I think this is a progress and it shouldn't be that hard to solve once you have 5.2.2 again. I think this command should do the trick:

    C:/Users/FA110/AppData/Local/Programs/Python/Python36/python.exe -m pip install -U ipython prompt-toolkit

**Comment by jingobelll** [comment]
I reinstalled Spyder 5.2.1. which is the version I installed at first. 
It shows the error as this 
![image](https://github.com/spyder-ide/spyder/assets/145687686/7d0c6e39-644e-485c-9705-2bbdf250eb6d)
Then I tried your command  
![image](https://github.com/spyder-ide/spyder/assets/145687686/d3cf49f5-3d09-4186-afcf-5a727655292b)
It does not work, still shows the same error

Therefore I installed Spyder 5.2.2 as you said
Same problem as the beginning
![image](https://github.com/spyder-ide/spyder/assets/145687686/3e48d66f-dd16-401a-913b-018650d8c27f)
![image](https://github.com/spyder-ide/spyder/assets/145687686/8e17e7a7-183a-489e-b45d-d0ecfcdd4ad4)
Still does not work

**Comment by ccordoba12** [comment]
Ok, then close Spyder, run this command:

> C:/Users/FA110/AppData/Local/Programs/Python/Python36/python.exe -m pip install prompt-toolkit==3.0.28

and try again.

If that still fails, change the `28` at the end by `27`, `26`, `25`, etc, to see if you find a prompt-toolkit version that really works with Python 3.6 (that's the package that's giving this error and it's not our fault).

**Comment by jingobelll** [comment]
![image](https://github.com/spyder-ide/spyder/assets/145687686/24e76fa6-e307-4f67-914d-4533699f65c1)

I found this version works for Python 3.6.
But still fails

**Comment by ccordoba12** [comment]
Closing due to lack of response.
