### ISSUE TITLE
Sklearn can not be used

### ISSUE THREAD

**Issue by lshays1066** [spyder-ide/spyder#21370]
I install the spyder from anaconda
My Spyder version is 5.4.3
I can see package Scikit-learn are installed when I use conda list command, but when I import it in Spyder, it always remind "sklearn is not a pakage', how shall I solve the issue?

**Comment by lshays1066** [comment]
today I try to use below commond to create the environment, and also link the intepreter to my-env
conda create -n my-env -c conda-forge spyder-kernels scikit-learn
after restart the kernal, sklearn package can be correctly imported but matplotlib package can not be loaded anymore. and when I use conda list, I can not see the package in my-env. Then I try to install myplotlib, after successfully installed, I found sklearn package is not working again.
In Jupyter which is also installed from Anaconda, it works well for both scikit-learn and matplotlib.

**Comment by lshays1066** [comment]
Thanks for help, unfortually still has problem here.
I use follow steps as you guided:
conda create -n my-env -c conda-forge spyder-kernels
conda activate my-env
and in the my-env, 
conda install scikit-learn matplotlib
when I use conda list, I can see both packages are installed
however, after I link this intepreter in spyder preferences, and restart the kernal, then it report kernal start errors:
"An error ocurred while starting the kernel"

**Comment by ccordoba12** [comment]
Ok, sorry to hear that. Please post here the error you're seeing now to see how to help you with it.

**Comment by lshays1066** [comment]
Erros copy is here:
![image](https://github.com/spyder-ide/spyder/assets/145950044/0b053f7e-c3bc-42c0-8deb-d5a42772e09f)
by the way, when I try to use conda install scikit-learn matplotlib for package installation, it reminds below:
![image](https://github.com/spyder-ide/spyder/assets/145950044/8be7f2bb-4f7c-4317-9acd-7e9c4bd35d36)

**Comment by ccordoba12** [comment]
> Erros copy is here:

Please copy the entire error and paste it here. I need to see it in full to give you proper support.

> by the way, when I try to use conda install scikit-learn matplotlib for package installation, it reminds below:

That's because the command you need to run needs to be

    conda install -c conda-forge matplotlib scikit-learn

after running

    conda activate my-env

I'm sorry, that was an oversight in my [comment](https://github.com/spyder-ide/spyder/issues/21370#issuecomment-1735960429) above.

Please recreate your environment again because the one you created is actually broken.

**Comment by lshays1066** [comment]
Funny thing. I try to create environment with 
conda install -c conda-forge matplotlib scikit-learn
it works now for both packages, but pandas is missing, then I remove the env and create a new env again using:
conda create -n my-env -c conda-forge spyder-kernels
conda activate my-env
conda install -c conda-forge matplotlib scikit-learn pandas
then scikit-learn package can not be recognized again in spyder

**Comment by ccordoba12** [comment]
Closing due to lack of response.
