### ISSUE TITLE
Custom environment not populating into Spyder. 

### ISSUE THREAD

**Issue by alexsorenson11** [spyder-ide/spyder#21373]
## Problem
I have been attempting to install a custom environment into Spyder. I have successfully created the environment in anaconda using the "conda env create -f" command in anaconda prompt. I open the preferences tab and go to the python interpreter, I select the "use the following python interpreter" button and click on the drop down, but the environment has not been recognized by Spyder. I verified that the environment was created both in anaconda prompt and in anaconda navigator. I see the full list of packages that I expect from the installation except Spyder itself. 

## Attempts to Fix
I have attempted to restart both programs and my computer. I have tried running different versions of anaconda and Spyder. I have also tried downloading the independent version of Spyder. I also attempted to download Spyder through the custom environment, but my computer did not recognize it as a runnable app. 
I feel as though I have tried everything and I am completely stuck. Please help!

## Versions
* Spyder version: 5.4.5
* Python version: 3.11.8
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 Education

**Comment by ccordoba12** [comment]
Hey @alexsorenson11, thanks for reporting. Please post the location of your Anaconda or Miniconda installation in your system to better understand what could be the cause of your problem.

**Comment by alexsorenson11** [comment]
C:\Users\asorenson\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)

The environment is pathed as follows: C:\Users\asorenson\Desktop\ImageAnalysis\Environment

**Comment by ccordoba12** [comment]
Thanks @alexsorenson11!

> C:\Users\asorenson\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)

This is the Anaconda's entry in the Start Menu, but I need to know where you installed Anaconda. If you can't easily find it, please open the Anaconda Prompt, run there

    conda activate base
    conda info

and post the output of the last command here.

**Comment by alexsorenson11** [comment]
Thank you for your reply! I was actually able to get it to work. If anyone else comes across this issue, The environment was saving in my "appdata" folder rather than the ".conda" folder so Spyder was not able to pull the file directly. I ended up mapping to the file directly from spyder (after installing) rather than from anaconda.

**Comment by ccordoba12** [comment]
Ok, glad to know you managed to solve this problem. And thanks for letting us know about it!
