### ISSUE TITLE
Spyder 6.0.0a2 splash screen text says version 5

### ISSUE THREAD

**Issue by ilayn** [spyder-ide/spyder#21404]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)

## Problem Description
Pip installed version 6.0.0a2 splash screen image still has version 5 text in it.

![image](https://github.com/spyder-ide/spyder/assets/1303842/1b3d0355-8bfb-451a-b145-5281c81629dd)

## Versions

* Spyder version: 6.0.0a2  (pip)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.19045-SP0

**Comment by dalthviz** [comment]
Hi @ilayn thank you for the feedback! Just in case, I think the related file that needs to change is https://github.com/spyder-ide/spyder/blob/master/spyder/images/splash.svg (I think we usually use something like Inkscape to edit)

**Comment by ilayn** [comment]
Ah OK. By the way just out of curiosity I opened the image in an editor and apparently the original uncropped stock photo is still embedded in the splash image.

 The image size can be significantly reduced if the stock photo image is cropped absolutely and not soft-clipped as is now. I don't know if this image makes it into the actual binary but just wanted to mention it.

**Comment by dalthviz** [comment]
Oh thank you for the info on that! What do you think @ccordoba12 ? Maybe is there a reason for the stock photo to be just soft-clipped?

**Comment by ccordoba12** [comment]
> What do you think @ccordoba12 ? Maybe is there a reason for the stock photo to be just soft-clipped?

I don't know why that's the case but I'll ask @conradolandia to take a look at it.

**Comment by conradolandia** [comment]
I'll take care of it.
