### ISSUE TITLE
Some shortcuts are not working

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2140]
_From [mgili...@gmail.com](https://code.google.com/u/100252948182499758458/) on 2015-01-26T04:29:06Z_

Spyder Version:  2.3.2
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  None (NOK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  0.9.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.1.0 (OK) 

What steps will reproduce the problem?

 1. put the cursor on some line on editor and press Ctrl + 1 for comment the line (work)
2. after the line is in the comment press Ctrl + 5 and this doesn't work 

What is the expected output? What do you see instead?

 press Ctrl + 5 should be uncomment the comment line What version of the product are you using? On what operating system? linux kubuntu 14.04

more shortcuts that doesn't work is:

Ctrl+Alt+Shift+Left | last edit location
Ctrl+Alt+Right      | next cursor position
Ctrl+Alt+Left       | previous cursor position

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2140_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:19:55Z_

**Summary:** Some shortcuts are not working  \<span class="oldvalue"> (was: some shortcut doesn't work) \</span>  
  **Labels:** MS-v2.3.4 Cat-Settings

**Comment by ccordoba12** [comment]
`Ctrl+5` is used to remove block comments, i.e. comments of the form

    #==============================================================================
    # 
    #==============================================================================

`Ctrl+1` is used to comment *and* uncomment a line, so there is no problem here. The other shortcuts you suggest are going to be added in pull request #2217.

**Comment by felixsc1** [comment]
I  just had the same problem in Spyder 3.2.6
Solution: You have to search in the settings if the key combination is already mapped to something else, and change this. Otherwise it won't work without giving an error. 
Would be good if spyder checked if there are duplicates and warn the user.
