### ISSUE TITLE
Cannot Interact with the Spyder IDE at all

### ISSUE THREAD

**Issue by cbarron100** [spyder-ide/spyder#21400]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I was connected to a 4kK monitor and that caused some problems with the scaling. I tried to solve that with the usual method of going to preferences and then changing the appearence to normal. Which didn't work this time. So I restarted the IDE but the problem with the scaling persited. So After that I tried to restore the settings to default but that caused a larger problem where I cannot even interact with the Spyder IDE.

<img width="960" alt="image" src="https://github.com/spyder-ide/spyder/assets/147157266/03145d11-d46d-46d6-9578-c24b839bbc0b">

All I can do with it is hover over the Icon and see a white window.

### What steps reproduce the problem?

1. Uninstall and reinstall
2. The same but with anaconda
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

spyder                    5.4.3           py311haa95532_1
python                    3.11.5               he1021f5_0

I have Windows 11.

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @cbarron100, thanks for reporting. Please open the Anaconda Prompt and run there

    spyder --reset

Then Spyder again.

That should solve your problem, but let us know if it does.

**Comment by cbarron100** [comment]
It worked!! Thank you :)

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
