### ISSUE TITLE
 Error using cv2 library in Spyder.

### ISSUE THREAD

**Issue by DanielaMatasova** [spyder-ide/spyder#21412]
### What steps will reproduce the problem?

Since I updated the cv2 library to version 4.8.1, I am unable to run my code in Spyder that utilizes this library. When attempting to execute the code, the following error message appears:   error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3940: error: (-215:Assertion failed) func != 0 in function 'cv::hal::resize'
Steps to Reproduce the Issue:

I updated the cv2 library to version 4.8.1.

I opened Spyder and loaded my code that uses the cv2 library.

When attempting to run the code, the above-mentioned error message is displayed.

Expected vs. Actual Behavior:

I expected my code with cv2 library version 4.8.1 to work without any issues. However, the actual behavior includes the error message "error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:3940: error: (-215:Assertion failed) func != 0 in function 'cv::hal::resize'."

Versions and Environment:

cv2 Library Version: 4.8.1

Spyder Version: Python 3.9

Operating System: Windows 10 Home, version: 22H2

Thank you for your assistance in resolving this issue.

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 343, in _handle_remote_call
    return_value = self._remote_callback(
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\comms\frontendcomm.py", line 267, in _remote_callback
    return super(FrontendComm, self)._remote_callback(
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\comms\commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\console\kernel.py", line 189, in get_namespace_view
    view = make_remote_view(ns, settings, EXCLUDED_NAMES)
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\utils\nsview.py", line 677, in make_remote_view
    'type':  get_human_readable_type(value),
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\utils\nsview.py", line 528, in get_human_readable_type
    elif isinstance(item, PIL.Image.Image):
  File "C:\Users\Danka\anaconda3\lib\site-packages\spyder_kernels\utils\lazymodules.py", line 55, in __getattr__
    return getattr(self.__spy_mod__, name)
AttributeError: module 'PIL' has no attribute 'Image'
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.13
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.14.5 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.4.1 (NOK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.26.0 (OK)
pandas >=1.1.1                :  1.4.4 (OK)
scipy >=0.17.0                :  1.9.1 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

**Comment by dalthviz** [comment]
Hi @DanielaMatasova thank you for the feedback! So seems like you are using Spyder from an anaconda installation. How did you do the cv2 update? Are you using only the anaconda base environment or maybe you set up some new Python environment only to work with cv2. Seems like doing the update messed up the base environment of your conda installation. From the traceback section of your report you can see the error `AttributeError: module 'PIL' has no attribute 'Image'` which maybe could be related with the OpenCV error message :thinking:

Any other info in order to understand your setup is appreciated in order to better understand if the error comes from Spyder itself. Let us know!

**Comment by dalthviz** [comment]
Closing due to lack of response
