### ISSUE TITLE
You have missing dependencies! : jellyfish >=0.7 : None (NOK)

### ISSUE THREAD

**Issue by jolo2486** [spyder-ide/spyder#21421]
## Problem Description
When starting spyder from terminal in new conda environment, I get an error box with the message:

```
You have missing dependencies!

# Mandatory:
jellyfish >=0.7 : None (NOK)

Please install them to avoid this message.
``` 

### What steps reproduce the problem?
1. `$ conda create -n envname python=3.8.16`
2. `$ conda install spyder`
3. `$ spyder`

### What is the expected output? What do you see instead?
Spyder starting without complaints. Instead I get the above error.

## What I have tried
```
$ conda list | grep jelly
jellyfish                 2.2.10               h6bb024c_1    bioconda
```

`spyder --reset`

`conda update spyder`

### Reinstalled/downgraded jellyfish via different approaches/versions:
```
conda install jellyfish=2.2.6
```
same problem
```
conda install jellyfish # upgrades to 2.2.10 again
```
same problem
```
conda uninstall jellyfish
```
this removed spyder for me (?)

After reinstalling spyder again, I tried
```
conda install jellyfish=1.0.1
```
since this was the latest that had the channel name 'pkgs/main' instead of 'bioconda'

Then it works! and all dependencies listed as mandatory are 'OK'. But upgrading again to the latest jellyfish
```
conda install jellyfish=2.2.10
```
breaks it again.

__Update1:__ I have also tried to remove the environment, install a new one with spyder=5.4.2. and 5.3.3. It installs the same jellyfish version (2.2.10), and the same problem appears again.

__Update2:__ Are these actually the same libraries (description sounds related but very different), since they are the difference between error and no error:

[bioconda/jellyfish](https://anaconda.org/bioconda/jellyfish)

[conda-forge/jellyfish](https://anaconda.org/conda-forge/jellyfish)

## Versions
* Spyder version: 5.4.3 (also with 5.4.2 and 5.3.3)
* Python version: 3.8.16
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Ubuntu 22.04.3
* Conda version: 23.9.0

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  None (NOK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
xdg >=0.26                                       :  0.27 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  None (NOK)
numpy >=1.7                                      :  None (NOK)
pandas >=1.1.1                                   :  None (NOK)
scipy >=0.17.0                                   :  None (NOK)
sympy >=0.7.3                                    :  None (NOK)
```

**Comment by dalthviz** [comment]
Hi @jolo2486! I think the problem comes from the channel priority you have in your setup. As you mentioned in the OP you are getting a `jellyfish` package (from the bioconda channel) which is not the `jellyfish` package Spyder depends on and expects (ehich is available from the conda-forge channel for example). To workaround that without messing with your local conda channels config maybe try to create the new env using [the `--override-channels` flag and the `--channel`/`-c` flags](https://docs.conda.io/projects/conda/en/latest/commands/create.html#Channel%20Customization), so something like:

    conda create -n envname -c conda-forge --override-channels python=3.8.16

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response

**Comment by rjavierch** [comment]
To complement the solution here, what has worked for me is `conda install conda-forge::jellyfish`. Also if an specific version is needed, check [https://anaconda.org/conda-forge/jellyfish](https://anaconda.org/conda-forge/jellyfish)
