### ISSUE TITLE
Add support for running DocTest

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2144]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2015-01-27T19:21:34Z_

Doctest is a useful built-in library in Python.

I would find it very useful if Spyder could run doctest on the active editor file.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2144_

**Comment by spyder-issues-migrator** [comment]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2015-01-27T16:26:29Z_

I've actually already started making a plugin for this. It can be found at: https://github.com/dougthor42/spyder-doctest-plugin It's still pretty basic, but it works for the most part. I think it has issues if the code has to wait for user input at any point, but it's a start.

You can take a look at the docs on the github page to see what I have planned for it.

To install:
\-----------
Download doctestgui.py and p_doctest.py (also test_doctestgui.py if you want to run doctestgui.py stand-alone). Put doctestgui.py (and test_doctestgui.py) into 
...\site-packages\spyderplugins\widgets\
and put p_doctest.py into
...\site-packages\spyderplugins\

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-30T14:32:31Z_

I think this is too specialized to belong to Spyder properly, but it's just fine for a third party plugin.

We are going to improve how to install this kind of plugins in 2.4.

I'll let you know when that happens, so you can distribute your plugin more easily.

**Summary:** Add support for running DocTest  \<span class="oldvalue"> (was: Add support for running DocTest on editor file) \</span>  
  **Labels:** MS-v2.4 Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2015-02-03T12:47:01Z_

Thanks Carlos, that sounds good to me.

**Comment by dougthor42** [comment]
Adding comment so that I get notifications and so that I can find my issues/comments more easily.

**Comment by Nodd** [comment]
For information I started some time ago a plugin to run nosetests/pytets : https://github.com/Nodd/spyder_unittesting
If correctly configured it should run doctests too (but on a whole project, not on the current file)

**Comment by goanpeca** [comment]
@jitseniesen I think this is related to your work on spyder-unittest

**Comment by jitseniesen** [comment]
This issue was moved to spyder-ide/spyder-unittest#44
