### ISSUE TITLE
Magic to toggle post-mortem debugging

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#21459]
I often need to switch between `post_mortem=True` and `post_mortem=False`. Appending `post_mortem=1` or `0` to `runfile` in command line helps, but it's still not ideal, particularly if I switch between files to run.

Request: something like `%pdb post_mortem 1` sets `post_mortem=True` for _all_ files, and `0` makes it fall back to per-file configurations.

Not a priority issue, just a nice-to-have. (Maybe it's already there, but I've not seen in [docs](https://docs.spyder-ide.org/5/panes/debugging.html)).

**Comment by ccordoba12** [comment]
The magic is called `%debug`. So, if there's an error in your code and after that you run `%debug`, you'll start debugging that error.

Let us know if that's what you really need to add it to our docs.

**Comment by ccordoba12** [comment]
However, that magic broken in IPython 8.15, so you'll need to downgrade to version 8.14.0 to see how it works (that problem will be fixed in our next version, 5.5.0, to be released next week).

**Comment by OverLordGoldDragon** [comment]
Wow, I can step in _after_ an exception, without all the prior setup?? I've wanted this, but thought no way it's a thing.

So, it's actually [%pdb](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pdb), and it works exactly as desired.

<hr>

**Off-topic**: 

At this point it's on me to look into this stuff, but again I'd have found it tremendously helpful for a Spyder "Tips & Tricks" page. Here's what I have in mind.

`Help > IPython documentation > Quick reference` is a good format, and it itself is OK. (Maybe it'd be "good" if it didn't... [cut off?](https://i.stack.imgur.com/jQrw2.png)) I'm also aware of `Spyder tutorial` - but that's too basic. The problem with most references is clutter with basic stuff. "Well, `%pdb` is basic!" Right, what's basic, what's advanced, who cares for what! Not easy. 

For me, I just installed Spyder some 4(?) years ago, did basically no tutorial reading, and figured out everything on the fly. I thought of checking guides, and did a few times, but it was either too cluttered with basics, or all-in-one with irrelevant stuff I didn't need. The `Quick reference` seems to get it, it groups by sections and is concise. But as I used Spyder, I didn't think "this comes from IPython, that comes from LSP" - to me it's just Spyder (with obvious exceptions like matplotlib, conda). You could say, that's my problem! And that's fair. But I think such a "Tips & Tricks" page is doable and would be helpful, and maybe one day I'll find the time to make one.

**Comment by OverLordGoldDragon** [comment]
Yeah it's cut off, it's `%quickref`. It's not organized past the cutoff unfortunately, could use a "Debugging" section.

What'd get my attention is, something like `Type "%quickref" for helpful tips.` alongside the 

```
Python 3.11.4 | packaged by conda-forge | (main, Jun 10 2023, 17:59:51) [MSC v.1935 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 8.14.0 -- An enhanced Interactive Python.
```

I get it's an entire extra line. Or maybe ... 

```
Type "copyright", "credits" or "license" for more information, "%quickref" for helpful tips.
```
Think that's bearable! More generally it could be `%spytips`, and that'd be like

```
%quickref - IPython tips
%blah - matplotlib tips
...
```
Dunno what portion of users think same, just my thought.
