### ISSUE TITLE
libGL error: MESA-LOADER: failed to open swrast

### ISSUE THREAD

**Issue by sitadrost** [spyder-ide/spyder#21450]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
To get rid of a number of vague, recurring error messages, possibly related to package incompatibilities, I recently decided to uninstall Miniconda, and install Anaconda instead. This seems to have worked alright, but I'm now getting a new error (see below), each time I start Spyder, and then again when I create my first Matplotlib plot in that session.

The error indicates a missing driver, so resolving it might be as simple as installing the appropriate package (a quick internet search suggests installing mesa-utils). However, despite the error messages, nothing seems to be wrong really. So now I'm wondering: should I do something about this error, or can I safely ignore it?

### What steps reproduce the problem?

1. Start Spyder from the command line (error message appears in terminal)
2. Load Matplotlib, create first plot (same error message appears in Spyder)

### What is the expected output? What do you see instead?
Expected: no error message. 
Actual output: error message (but no problems apart from that)

### Paste Traceback/Error Below (if applicable)

Error message in terminal window:
```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast

```
Error message in Spyder (same):
```
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

## Versions

* Spyder version: 5.4.3
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.7
* Operating System name/version: Ubuntu 22.04 (Linux 6.2.0-35-generic)

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
xdg >=0.26                                       :  0.27 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @sitadrost, thanks for reporting. The Anaconda packages for Linux that Spyder depends on are not very good, so I recommend you to create an environment with Conda-forge ones instead and try again.

For that, please open a terminal and run there:

    conda create -n spyder-env -c conda-forge python=3.11 spyder
    conda activate spyder-env
    spyder

Let us know if that works for you.

**Comment by sitadrost** [comment]
Hi @ccordoba12 , thanks a lot for that, I'll give that a try. That's funny though, I just moved to Anaconda to get rid of all these incompatibiliy issues with conda-forge

**Comment by sitadrost** [comment]
Great, looks like that worked, thanks again!

Just to make sure: would it be a good idea to stick to conda-forge for any packages that I install into this new environment? If so, I think I'll do a fresh install again, and move back to Miniconda. Feels a bit pointless to have this huge Anaconda base environment if I'm not going to use it.

**Comment by ccordoba12** [comment]
> Great, looks like that worked, thanks again!

No prob, glad to know the problem had an easy solution.

> Just to make sure: would it be a good idea to stick to conda-forge for any packages that I install into this new environment?

Yes, that's correct. Conda-forge and Anaconda packages have some incompatibilities, so it's better to stick to a single channel when installing packages in your env.

That's probably what caused your frustrations before. Furthermore, you should avoid using pip in your env too, unless the package you want to use is not available in Conda-forge.
