### ISSUE TITLE
Disabling one completion and linting provider prevents showing completions

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21462]
## Problem Description

Disabling a completion provider prevents showing completions even if there are still more providers enabled

### What steps reproduce the problem?

1.  Go to `Preferences > Completion and Linting` and uncheck `Enable Fallback Provider`
2.  Try to get completions from the Editor (it doesn't work)
3.  Check again the `Enable Fallback Provider` from the preferences
4.  Completions from the Editor start working again

#### Preview 

![providers](https://github.com/spyder-ide/spyder/assets/16781833/0ae1bbab-9038-4ff3-96d8-d5f9f9da3f84)

### What is the expected output? What do you see instead?

To be able to disable an individual provider without affecting getting completions from other providers

## Versions

* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
I think this is serious enough to warrant delaying 5.5.0 for a few days so we try to fix it.
