### ISSUE TITLE
I cant install pip

### ISSUE THREAD

**Issue by createwow** [spyder-ide/spyder#21474]
### What steps will reproduce the problem?

It seems like you deleted 'pip install' from Spyder/Python. Why?

I need to install some packages, how do I do it?

## Versions

* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree                                                                :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.4.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.1.2 (OK)
sphinx >=0.6.6                                                              :  7.1.2 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog                                                                    :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.24.4 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)
```

**Comment by GitKia1392** [comment]
Hello

**Comment by GitKia1392** [comment]
So you need to go into run cmd.exe as Administrator. Type in, sfc /scannow
It will take a while, 
IF it said it repaired the files, try rebooting and installing Pip again
IF it said that It found none STILL reboot and try again
IF it said that it Couldn't RUN SFC then these are your choices:
Either go into the CBS.logs folder and scroll down to see the errors and google them. IF you have a secondary computer WITH a USB at least 1 GB then boot the secondery PC, go into the CBS.logs folder again and COPY the folder into the USB, perform a bootdown. PLUG the  USB out and PUT it in your MAIN pc and go into the cbs logs folder on the C:\ drive then in the folder do CRTL + A, BACKSPACE or DELETE; then minimize the folder and go into the CBS logs folder you copied from the 2nd pc and open the 2nd ery CBS logs and copy and paste into the MAIN one. Run it again as Administrator.

IF it said it repaired the files, try rebooting and installing Pip again:
if it still doesn't work use DISM /Online /Cleanup-Image /CheckHealth

Reach out to me tomorrow on 1st of nov

Cya

**Comment by ccordoba12** [comment]
Hey @createwow, thank for reporting. You said:

> It seems like you deleted 'pip install' from Spyder/Python. Why?

Because users could install with pip any Python package in the same environment used by Spyder, which would lead to numerous and simple ways to break it. The reason we created our installers and promote them over other installation media is precisely because they are self contained and can't be easily broken. That's also why we're not planning to change that policy.

If you want other packages that don't come with our installers, please follow these instructions in our documentation:

https://docs.spyder-ide.org/5/faq.html#using-packages-installer

**Comment by GitKia1392** [comment]
So you need to go into run cmd.exe as Administrator. Type in, sfc /scannow
It will take a while, 
IF it said it repaired the files, try rebooting and installing Pip again
IF it said that It found none STILL reboot and try again
IF it said that it Couldn't RUN SFC then these are your choices:
Either go into the CBS.logs folder and scroll down to see the errors and google them. IF you have a secondary computer WITH a USB at least 1 GB then boot the secondery PC, go into the CBS.logs folder again and COPY the folder into the USB, perform a bootdown. PLUG the  USB out and PUT it in your MAIN pc and go into the cbs logs folder on the C:\ drive then in the folder do CRTL + A, BACKSPACE or DELETE; then minimize the folder and go into the CBS logs folder you copied from the 2nd pc and open the 2nd ery CBS logs and copy and paste into the MAIN one. Run it again as Administrator.

IF it said it repaired the files, try rebooting and installing Pip again:
if it still doesn't work use DISM /Online /Cleanup-Image /CheckHealth

Cya
