### ISSUE TITLE
Python 3.12.0 Not working with the IPython shell

### ISSUE THREAD

**Issue by GitKia1392** [spyder-ide/spyder#21473]
It is not working. When I try to reboot the shell it says that apparently I need to install IPython. **I DID. I did the thing it told me with Powershell** then I go into the **Python312** folder I find TONS of other IPython related folders and subfolders. But still i'd still like to use the latest version. Simply cannot get it to work. 

> Thanks @ccordoba12 for your old help 

Regards
Kiamehr
E: kiamehr13922014@gmail.com

**Comment by ccordoba12** [comment]
Hey @GitKia1392, thanks for reporting. Could you post a screenshot of the error you mentioned so we can better understand your problem? Thanks!

**Comment by GitKia1392** [comment]
M

**Comment by GitKia1392** [comment]
no i ment like the shell  wont work not importing.
