### ISSUE TITLE
spyder kernel error

### ISSUE THREAD

**Issue by Roony0708** [spyder-ide/spyder#21479]
### What steps will reproduce the problem?

i installed spyder IDE also  i have latest python verson 3.12 but the spyder is showing"an error ocurred while starting the kernel" even if i have the spyder kernel showing in my pip list as "spyder kernel = 2.4.4" and if i am trying to run the pip install in spyder ide terminal it is showing error of no matching distributation found for spyder but in my windows terminal i have installed the spyder kernel.
please give me any suggertion how do i fix it..

## Versions

* Spyder version: 5.4.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22621-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                                                        :  1.4.1 (OK)
chardet >=2.0.0                                                             :  5.2.0 (OK)
cloudpickle >=0.5.0                                                         :  2.2.1 (OK)
cookiecutter >=1.6.0                                                        :  2.3.0 (OK)
diff_match_patch >=20181111                                                 :  20230430 (OK)
intervaltree                                                                :  None (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1 :  8.12.2 (OK)
jedi >=0.17.2,<0.19.0                                                       :  0.18.2 (OK)
jellyfish >=0.7                                                             :  1.0.0 (OK)
jsonschema >=3.2.0                                                          :  4.19.0 (OK)
keyring >=17.0.0                                                            :  24.2.0 (OK)
nbconvert >=4.0                                                             :  7.8.0 (OK)
numpydoc >=0.6.0                                                            :  1.5.0 (OK)
paramiko >=2.4.0                                                            :  3.3.1 (OK)
parso >=0.7.0,<0.9.0                                                        :  0.8.3 (OK)
pexpect >=4.4.0                                                             :  4.8.0 (OK)
pickleshare >=0.4                                                           :  0.7.5 (OK)
psutil >=5.3                                                                :  5.9.5 (OK)
pygments >=2.0                                                              :  2.16.1 (OK)
pylint >=2.5.0,<3.0                                                         :  2.17.5 (OK)
pylint_venv >=3.0.2                                                         :  3.0.2 (OK)
pyls_spyder >=0.4.0                                                         :  0.4.0 (OK)
pylsp >=1.7.4,<1.8.0                                                        :  1.7.4 (OK)
pylsp_black >=1.2.0,<3.0.0                                                  :  1.3.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                                                   :  3.1 (OK)
qstylizer >=0.2.2                                                           :  0.2.2 (OK)
qtawesome >=1.2.1                                                           :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                                                    :  5.4.3 (OK)
qtpy >=2.1.0                                                                :  2.4.0 (OK)
rtree >=0.9.7                                                               :  1.0.1 (OK)
setuptools >=49.6.0                                                         :  68.1.2 (OK)
sphinx >=0.6.6                                                              :  7.1.2 (OK)
spyder_kernels >=2.4.4,<2.5.0                                               :  2.4.4 (OK)
textdistance >=4.2.0                                                        :  4.5.0 (OK)
three_merge >=0.1.1                                                         :  0.1.1 (OK)
watchdog                                                                    :  3.0.0 (OK)
zmq >=22.1.0                                                                :  25.1.1 (OK)

# Optional:
cython >=0.21                                                               :  3.0.2 (OK)
matplotlib >=3.0.0                                                          :  3.7.2 (OK)
numpy >=1.7                                                                 :  1.24.4 (OK)
pandas >=1.1.1                                                              :  2.0.3 (OK)
scipy >=0.17.0                                                              :  1.10.1 (OK)
sympy >=0.7.3                                                               :  1.12 (OK)

# Spyder plugins:
spyder_terminal.terminalplugin 1.2.2                                        :  1.2.2 (OK)
```

**Comment by Roony0708** [comment]
Yes, it is installed

**Comment by ccordoba12** [comment]
Sure, I understand that. But I'm asking you how you installed it: did you download it from [python.org](https://www.python.org/)? Or did you use Anaconda/Miniconda instead? Or something else?

**Comment by Roony0708** [comment]
I installed it directly from python .org, after that I changed the default
python of Spyder to python 3.12  interpreter because spyder has 3.8 version
then after changing it started showing kernel error and saying to install
kernel either through conda or using pip I aslo installed the kernel
version which is 2.4.4 but it still showing error I also uninstall python
as well as spyder and re install both but same was the situation.

**Comment by Roony0708** [comment]
Also another fact is I tried to install pycharm also but in pycharm
everything is working fine and the python interpreter 3.12 is also working
in it not showing any error then why spyder having kernel problem

**Comment by ccordoba12** [comment]
> I installed it directly from python .org

Ok, and where did you install it? In `C:\Program Files` or a similar directory?

**Comment by Roony0708** [comment]
I installed it in C;/ program files
And when I am opening my command prompt and typing python it is showing
version of 3.12 and I then check pip using pip list there it is showing
spyder kernels 2.4.4 then also it is showing kernel error and one more
point that I was working fine when I installed spyder for first time all
codes was executing with python version 3.12 but then when I opened it
another time it started showing kernel error.

**Comment by ccordoba12** [comment]
> I installed it in C;/ program files

Ok, that means that you're affected by issue #20968, which we don't know how to fix yet.

For now the workaround for that problem is to open a terminal as Administrator and run there again

    pip install spyder-kernels==2.4.4

Let us know if that works for you.

**Comment by Roony0708** [comment]
I used this command 'pip install spyder-kernels==2.4.4' several times
always it says requirements satisfied,but I found the solution of kernel
error I uninstall both spyder and python 3.12 and install Anaconda their i
launch spyder there also it was showing same kernel error but then I opened
ipython conda terminal and I used 'conda install spyder' and I closed
spyder IDE and when I again opened it it worked fine.

**Comment by ccordoba12** [comment]
> I used this command 'pip install spyder-kernels==2.4.4' several times

Then open a terminal as a your regular user and run there

    pip uninstall spyder-kernels

And after open a new terminal as Admistrator and run again:

    pip install spyder-kernels=2.4.4

**Comment by ccordoba12** [comment]
Closing due to lack of response.
