### ISSUE TITLE
Suggestion to be able to open Polars dfs from the Variable Explorer tab

### ISSUE THREAD

**Issue by Chuck321123** [spyder-ide/spyder#21486]
### Issue Report Checklist

All checklists checked.

## Problem Description

I saw a post from December 2022 mentioning this, but would be very nice to be able to open polars data frames in the variable explorer as polars is rapidly increasing in popularity.

## Versions

* Spyder version: 5.4.5
* Python version: 3.11.6
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
Hey @Chuck321123, thanks for reporting. We are aware of that and will try to do it after releasing Spyder 6, which is consuming all our time right now.

Since this was reported before on issue #20281, I'm going to close it in favor of that.
