### ISSUE TITLE
经常 毫无预兆的关闭

### ISSUE THREAD

**Issue by BranChai** [spyder-ide/spyder#21516]
spyder4.5或者5.0，如果打开时间过长，经常毫无预兆的关闭，没有任何提示

**Comment by BranChai** [comment]
我使用的操作系统是win10，使用python的版本是3.9和3.10

**Comment by BranChai** [comment]
是的，你是对的，我使用的是“spyder4.5”和“spyder5.0”，我使用“pip install spyder”安装，发生错误时没有任何提示，只是当使用spyder较长时间时就会关闭，没有任何提示，我也不知道什么原因

**Comment by dalthviz** [comment]
I would suggest you to try to be sure you are running the latest Spyder release (5.5.0). Also, to get further debug info you can run Spyder in debug mode. For that go to `File > Restart in debug mode` and select `vebose`. That should record errors tha could be happening and maybe are causing Spyder to crash/close unexpectedly inside a `spyder-debug.log` file at `C:\Users\<your user>\.spyder-py3\spyder-debug.log`

**Comment by GitKia1392** [comment]
WE ARE IN AMERICA NOT ASIA TRY TO USE GOOGLE TRANSLATE.

Thanks for understanding that we're not in china

**Comment by ccordoba12** [comment]
@GitKia1392, please don't be rude with other users. We don't have problems with using Google translate and try help them if they don't comfortable speaking English.

**Comment by GitKia1392** [comment]
> @GitKia1392, please don't be rude with other users. We don't have problems with using Google translate and try to help them if they don't comfortable speaking English.

Ok sorry

Sorry Regards

**Comment by BranChai** [comment]
有了新的issues       https://github.com/spyder-ide/spyder/issues/21930
