### ISSUE TITLE
Variable explorer issue

### ISSUE THREAD

**Issue by JAFF-CYBERTHEIF** [spyder-ide/spyder#21531]
Unable to view Local variables of callables in variable explorer

![Uploading Screenshot 2023-11-16 101731.png…]()

**Comment by ccordoba12** [comment]
Hey @JAFF-CYBERTHEIF, thanks for reporting. It seems you're using a very old Spyder version (probably Spyder 3), which is not supported anymore.

So, we recommend you to install a more recent version by following the instructions in our documentation:

http://docs.spyder-ide.org/current/installation.html

**Comment by JAFF-CYBERTHEIF** [comment]
Hey @ccordoba12, I'm currently using Spyder IDE 5.1.5. Any chance you could help me find a solution? Thanks!

**Comment by ccordoba12** [comment]
Sorry, 5.1.5 is also quite old by now. Your problem is probably fixed in our latest version available in Anaconda (5.4.3). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

Let us know if it works for you

**Comment by JAFF-CYBERTHEIF** [comment]
I've upgraded to Spyder 5.5 but still I'm facing the same issue.
![Variable exlorer issue](https://github.com/spyder-ide/spyder/assets/63846848/08790c56-5120-4dcf-a0ff-fb75e07ef1a0)

**Comment by ccordoba12** [comment]
@JAFF-CYBERTHEIF, I understand your problem better now. The default behavior of the Variable Explorer is to display global variables only.

If you want to display local variables (i.e. those inside a function), you need to set a breakpoint in your code, so Spyder stops when running your function.

The simplest way to do that is by adding the `breakpoint()` call in any function you want to stop and inspect its variables. For instance, to display the local variable in the following function:

```py
def square(x):
    y = x ** 2
    return y
```

I need to add a breakpoint before the `return`

```py
def square(x):
    y = x ** 2
    breakpoint()
    return y
```

Then, when running this code, Spyder will stop at the `breakpoint` call and you'll be able to see the value of `y` in the Variable Explorer.

Let us know if that works for you.

**Comment by JAFF-CYBERTHEIF** [comment]
@ccordoba12 , Thanks for your support. Now I can view the local variables in variable explorer using the breakpoint(). 
Thank you😊

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by GitKia1392** [comment]
Us?
