### ISSUE TITLE
TYPE: Request: Add a background task for updates

### ISSUE THREAD

**Issue by GitKia1392** [spyder-ide/spyder#21543]
So in Spyder 6.00.00 we need a background task that whenever Spyder isn't running it shall detect whenever there is an update it should Auto-Update Spyder and then whenever its finished it should pop-up a prompt sayin oh like "A NeW SpYdEr VeRsIoN CaMe OuT V123456.5"  
> @ccordoba12 set this to Enhancement or Request type Issue

Thanks

**Comment by ccordoba12** [comment]
Hey @GitKia1392, thanks for reporting. We already do that but only when Spyder starts.

For now we think that's enough, but thanks for the suggestion.

**Comment by GitKia1392** [comment]
No A backround task not on startup. I'm talking about a **BACKGROUND** task.
