### ISSUE TITLE
No module named pip and Error for opencv

### ISSUE THREAD

**Issue by kaythinzarphu** [spyder-ide/spyder#21551]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.5
* Python version: 3.11.5
* Qt version: 
* PyQt version: 
* Operating System name/version: Window

### Dependencies

```
PASTE DEPENDENCIES HERE
```
pip install opencv-python
Note: you may need to restart the kernel to use updated packages.
C:\Users\scas\AppData\Local\Programs\Spyder\Python\python.exe: No module named pip

I installed spyder and python under the same directory.
In my spyder console : 
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython 8.12.2 -- An enhanced Interactive Python.

C:\Users\scas>pip install opencv-python
Requirement already satisfied: opencv-python in c:\users\scas\appdata\roaming\python\python311\site-packages (4.8.1.78)
Requirement already satisfied: numpy>=1.21.2 in c:\users\scas\appdata\roaming\python\python311\site-packages (from opencv-python) (1.25.2)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip

I restarted the spyder but I got the error

runfile('D:/python/Enhance/untitled0.py', wdir='D:/python/Enhance')
Traceback (most recent call last):

  File ~\AppData\Local\Programs\Spyder\pkgs\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File d:\python\enhance\untitled0.py:8
    import cv2 as cv

ModuleNotFoundError: No module named 'cv2'

Important
It seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.

**Comment by ccordoba12** [comment]
Hey @kaythinzarphu, thanks for reporting. Please follow the following instructions in our documentation to connect Spyder to your Python installation:

https://docs.spyder-ide.org/5/faq.html#using-packages-installer

Let us know if it works for you.

**Comment by kaythinzarphu** [comment]
Thank you
________________________________

**Comment by ccordoba12** [comment]
Closing because it seems the issue was solved.
