### ISSUE TITLE
Multiple versions of variable viewer window can be opened

### ISSUE THREAD

**Issue by bajhuman** [spyder-ide/spyder#21558]
The Spyder variable explorer allows you to open a variable window even if that same variable is already open. Is there any plan to implement the variable window (i.e. a dataframe) as a singleton instance. This would undoubtably be very welcome and increase productivity. At the moment it is possible to be looking at an old version of a variable without knowing.

* Spyder version: 5.4.5
* Python version: 3.9.0
* Qt version: 
* PyQt version: 5.15.9
* Operating System name/version: Windows

**Comment by dalthviz** [comment]
Hi @bajhuman thank you for the feedback! I'm not aware of a plan for restricting the possibility of opening multiple editor dialogs /variable windows instances for the same variable 🤔 What do you think @spyder-ide/core-developers ?

Also, related to the editor dialog displaying an old version of a variable, a new feature was recently added to the editors dialogs to refresh their content (https://github.com/spyder-ide/spyder/pull/21312) which should improve that situation (that new feature will be part of Spyder 6).
