### ISSUE TITLE
Test `test_pdb_comprehension_namespace` failing with Python 3.12

### ISSUE THREAD

**Issue by juliangilbey** [spyder-ide/spyder#21570]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

This was reported to Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056530
The test runs the following script in the debugger:
```
locals = 1
x = [locals + i for i in range(2)]
```
It steps 4 times and then expects `i` to equal 0.  Unfortunately, in Python 3.12, the debugger steps through script faster.  This may be due to inlining of comprehensions: https://docs.python.org/3/whatsnew/3.12.html#pep-709-comprehension-inlining
As a result, only 2 steps are needed to get to `i` being 0.

I think it may be sufficient to check for the Python version and specify the number of steps needed.

Here's a suggestion: replace these lines
https://github.com/spyder-ide/spyder/blob/19a39793ca712227ec520c769e298711477ed0fa/spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py#L1872-L1875
with something like:
```python
    PY312_OR_GREATER = sys.version_info[:2] >= (3, 12)

    # steps into the comprehension
    comprehension_steps = 2 if PY312_OR_GREATER else 4
    for i in range(comprehension_steps):
        with qtbot.waitSignal(shell.executed):
            shell.pdb_execute("s")
    assert "Error" not in control.toPlainText()
```
(And the constant would be placed at the start of the file.)

Unfortunately, I don't yet have enough packages built for Python 3.12 to be able to test it myself yet, so I'm not making it a PR at this point.  I'll update this report when I do.

**Comment by ccordoba12** [comment]
Hey @juliangilbey, thanks for reporting and providing a solution to this issue. Could you install Spyder in a Python 3.12 virtualenv from pip and try your fix? That way we could include it in our next version (5.5.1), to be released soon.

**Comment by juliangilbey** [comment]
Yes, this does seem to work. Now submitting a PR for it.
