### ISSUE TITLE
Left pane size changes when starting Spyder

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21596]
I do not see any tracebacks in the console, only a warning:

````
$ spyder
fromIccProfile: failed minimal tag size sanity
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: v0.9.4.4-ds-git20220108-9023143f8b93 is an invalid version and will not be supported in a future release
  warnings.warn(
````
(it really ends after the opening bracket)

But the actual symptom in the UI looks exactly like in the OP _(#18915)_:

The leftmost pane will become larger (on every app start) and the remaining panes are shrinked proportionally, total window size remains unchanged.

original:
![1](https://github.com/spyder-ide/spyder/assets/1401589/fe3237f3-8aed-4a64-bc93-bcd4870b0578)

1st restart:
![2](https://github.com/spyder-ide/spyder/assets/1401589/826386c8-e729-4989-b26f-703068095f1a)

2nd restart:
![3](https://github.com/spyder-ide/spyder/assets/1401589/920b1cff-3f90-44db-8982-56b5462048ed)

3rd restart:
![4](https://github.com/spyder-ide/spyder/assets/1401589/553c646d-41bf-4cea-8441-be103a314eb7)

---

I do NOT believe (my intuition is telling me this) that OP's traceback has anything to do with it. He changed and updated more than one thing before reporting it fixed, but his original visible UI symptom looks exactly like mine: 

Left pane growing and remaining panes shrinking proportionally.

To me it seems the left pane (or one of the tabs inside) does not want to accept the saved size or is applying the size wrongly and the other panes have no other choice than shrinking because they don`t fit into the remaining space. They seem to apply something from the saved layout because their size proportions remain correct, but they are forced to shrink. The left pane also seems to use the saved size in some way as a starting point, but then always add additional width to the already existing saved width.

````
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy

$ plasmashell --version
plasmashell 5.24.7


````

_Originally posted by @prof7bit in https://github.com/spyder-ide/spyder/issues/18915#issuecomment-1840964335_

Edit: Extra setup info:

* Spyder version: 5.5.0 (pip)
* Python version: 3.10.12 64-bit
* Qt version: 5.15.3
* PyQt5 version: 5.15.6
* Operating System: Linux-5.15.0-89-generic-x86_64-with-glibc2.35

**Comment by ccordoba12** [comment]
As I said in https://github.com/spyder-ide/spyder/issues/18915#issuecomment-1841292751, I think I know what's happening in this case: we're not saving the window layout before closing all plugins.

I'll submit a PR to fix that for Spyder 6.
