### ISSUE TITLE
Profiler pane not showing results

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21590]
## Problem Description

Unable to see code profiling results. Also seems like there some sort of widget under the Profiler pane file combobox selector.

### What steps reproduce the problem?

1. Try to profile a file via the menu (`Run > Run profiler`)

### What is the expected output? What do you see instead?

Expected to see the profiler result as a tree instead the empty pane message persists

### Behavior preview:

![profiler](https://github.com/spyder-ide/spyder/assets/16781833/2ffcfa49-302c-42b9-8479-1a48408398d2)

## Versions

* Spyder version: 6.0.0.dev0 0d4f2045e (conda)
* Python version: 3.9.17 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.19045-SP0

**Comment by dalthviz** [comment]
Note: Seems like PR #21555 fixed the UI issue releated with the combobox

**Comment by danielhrisca** [comment]
still happens with spyder 6.0.0b2

**Comment by dalthviz** [comment]
@ccordoba12 could it be worthy to check/update the proposed fix for this done at PR #21713 ?

**Comment by ccordoba12** [comment]
Yeah, that's a very good idea! (I forgot about that pull request).

Could you review it so we can merge it before 6.0 final? Thanks!

**Comment by danielhrisca** [comment]
I can confirm this being solved in 6.0.0b3
