### ISSUE TITLE
Connecting to remote seConnecting to remote server not workingrver not working

### ISSUE THREAD

**Issue by HitachiAIL** [spyder-ide/spyder#21604]
I followed all the steps here: 
http://docs.spyder-ide.org/current/panes/ipythonconsole.html?highlight=ssh#connect-to-a-remote-kernel

But then, when I import the json, it fails to start, and pop the "issue reporter" window.

I have been connecting to remote serve using this approach in the past (almost 1yr ago), but I have no idea why it fails now.

**Comment by ccordoba12** [comment]
Hey @HitachiAIL, thanks for reporting. You said:

> But then, when I import the json, it fails to start, and pop the "issue reporter" window.

Please use that window to post your issue here on Github. It contains all the information we need to help you.

Unfortunately, your current report contains almost no useful information, so I'm going to close it.
