### ISSUE TITLE
Minor, linux: taskbar icon is generic wayland "W" rather than the spyder icon

### ISSUE THREAD

**Issue by callegar** [spyder-ide/spyder#21619]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder does not get its application icon right in taskbar and application title bar in Linux Wayland. The generic "W" logo that is used for wayland application is used instead.

### What steps reproduce the problem?

1. Install Spyder on a Linux distribution (tested on Manjaro) using a virtual env and pip
2. Launch Spyder from the command line
3. See Spyder opening and working correctly. However the taskbar icon is a W and there is also a W in the left corner of the title bar.
4. Hovering with the mouse on the taskbar tells that the application is "Python", not "Spyder"

### What is the expected output? What do you see instead?

Spyder should get its own icon on the task bar to make it immediately recognizable. App name delivered by hovering on the task bar should be "Spyder", not "Python"

### Paste Traceback/Error Below (if applicable)

Not applicable 

## Versions

Python 3.11.6 64-bit | Qt 5.15.2 | PyQt5 5.15.10 | Linux 6.6.7-1-MANJARO (x86_64) 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.5.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.20.0 (OK)
keyring >=17.0.0                 :  24.3.0 (OK)
nbconvert >=4.0                  :  7.12.0 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.6 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.3 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.3.0 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.1.0 (OK)
setuptools >=49.6.0              :  69.0.2 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.6.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
xdg >=0.26                       :  0.28 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.6 (OK)
matplotlib >=3.0.0               :  3.8.2 (OK)
numpy >=1.7                      :  1.26.2 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @callegar, thanks for reporting. We'll try to take a look at this problem in a future version.

**Comment by callegar** [comment]
I have looked a bit into the issue. If my understanding is correct, this is a hard to solve issue, being ultimately due to a limitation in the Wayland protocols as reported in https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/52.
Wayland breaks Qt `setWindowIcon` (https://bugreports.qt.io/browse/QTBUG-101427) and currently pretends that every GUI application has a `.desktop` file. Unfortunately python applications installed with `pip` or `pipx` don't get any. Maybe just drop this until Wayland catches up with other platforms, Win, MacOs and the aging X11. Alternatively as a showstopper it could be Spyder itself to check for its own desktop file in `.local/share/application` and propose to write one if it is missing and it is possible to do so.

**Comment by ccordoba12** [comment]
> Alternatively as a showstopper it could be Spyder itself to check for its own desktop file in .local/share/application and propose to write one if it is missing and it is possible to do so.

That's not easy to do with pip alone and it'd be hard to implement for different Spyder's installed in several envs.

But the good news is that we're going to have a Linux installer based on conda packages for Spyder 6. That will come with its own desktop file, which will solve this issue according to what you said. Even if Spyder is a regular Python package, if you really want a smooth application experience, I think you'll need to use our installers in the future. It's fine if you don't, of course, but then you'll have to put up with annoyances like this one.

Since that's the best the we could do in the min term, I'm going to close this issue as "won't fix".

**Comment by callegar** [comment]
Perfectly OK not to fix. When I reported the issue, I did not know the cause yet, so sorry for the noise. My gratitude in advance should you have the occasion to interact with the Wayland developers to advocate their following up with the plan to provide a protocol extension to make `setWindowIcon` work as it does in the other platforms.

**Comment by ccordoba12** [comment]
Sorry, I don't have time for that. But you're welcome to reference this comment when talking to the Wayland developers to let me know that we fully embrace a way to make `setWindowIcon` work as in Xorg.
