### ISSUE TITLE
version 3.3 crashed in environment 'Devito'

### ISSUE THREAD

**Issue by ahmed-elbassiony** [spyder-ide/spyder#21618]
updating anaconda to 2.5.x, then on a pre-installed environment 'Devito' open spyder which happen to be an older version 3.3.x, then it crashes and keep opening crash window.

**Comment by GitKia1392** [comment]
uhh just update...

**Comment by ccordoba12** [comment]
Hey @ahmed-elbassiony, thanks for reporting. At this point Spyder 3 is not maintained anymore. Please update to our latest version by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

If that doesn't work, I'm afraid you'll have to remove Anaconda and install a more recent version of it.
