### ISSUE TITLE
matplotlib plots only appear inline

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2163]
_From [ja...@get.it](https://code.google.com/u/108711460352964009752/) on 2015-02-06T15:18:23Z_

Spyder Version:  2.3.2
Python Version:  3.4.2
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Darwin
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  2.3.1 (OK)
zmq >=2.1.11    :  14.4.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1.  When I produce a matplotlib plot, it only appears in line.  The problem persists even if I go to Preferences > iPython console > graphics > backend and change it from inline to automatic (which should produce a separate window of the plot that allows for interactive features like zooming). 2. 3. 

What is the expected output? What do you see instead?

 The matplotlib plot should appear as a separate pop out window with interactive features; instead, it only appears inline, even if I change the appropriate settings. 

Please provide any additional information below

. I am using the Anaconda distribution.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2163_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-06T18:20:54Z_

You need to restart the kernel, or close the current console and open a new one for the changes to take effect.

Does that fix your problem?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-08T10:30:09Z_

I'm almost sure the problem is what I mentioned, so I'm closing this one. Thanks for your interest in Spyder.

Another way to change backens is using the matplotlib magic, e.g.

    %matplotlib inline

**Status:** Invalid

**Comment by Vasu-Gupta1** [comment]
Restarting the kernel from Consoles->Restart kernel  and executing the code again surely helped. 
Thank you.
