### ISSUE TITLE
Missing Dependencies Cannot be Restricted by Bug Fixes

### ISSUE THREAD

**Issue by JohnRobson** [spyder-ide/spyder#21651]
This "Missing Dependencies" Error Alert on Spyder IDE could be restricted to only the first "2-digits" of the version number, like, for version: "X.Y.Z", should restrict "X.Y", but keep "Z" free. 

https://ibb.co/VBDnm5G

Usually, the LAST Digit on a version number is just a Bug Fix. So ALL these dependencies should be:

jedi: <0.20
qdarkstyle: <3.3
qtconsole: <5.6

And pylsp should be checked the version 1.9 and if restricted to: <1.10

**Comment by ccordoba12** [comment]
Hey @JohnRobson, thanks for reporting. You said:

> Usually, the LAST Digit on a version number is just a Bug Fix.

That's right, but the crucial part is the "usually" in your sentence. Throughout the years we've noticed that that's not always the case. So, we don't plan to change our way to detect dependencies.

If you're using Spyder on Linux through your package manager, we recommend you to install it with Anaconda or pip in a virtualenv instead. It's much more reliable and you won't have any problems with dependencies.
