### ISSUE TITLE
Warnings in the console with the Brain2 library

### ISSUE THREAD

**Issue by winterdrops** [spyder-ide/spyder#21652]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Hi dear Spyder users,
Whenever I run a code in Spyder ide, I get the warning below. It doesn't matter whether I use Brian2 library or another, I constantly get this error. Pls help me, it is very annoying. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Output from spyder call 'get_namespace_view':
WARNING    Active device does not have an attribute 'size', ignoring this. [brian2.devices.device]
WARNING    Active device does not have an attribute 'size', ignoring this. [brian2.devices.device]

Output from spyder call 'get_var_properties':
WARNING    Active device does not have an attribute 'size', ignoring this. [brian2.devices.device]
WARNING    Active device does not have an attribute 'size', ignoring this. [brian2.devices.device]
```

## Versions

* Spyder version: 5.4.3
* Python version: 3.9
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 pro

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for letting us know about it @jmrfox and sorry for the late reply @winterdrops. We'll try to fix this in Spyder 6, to be released in a couple of months or less.
