### ISSUE TITLE
Spyder can't find Python in the registry

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2165]
_From [android....@gmail.com](https://code.google.com/u/100864648954163226526/) on 2015-02-07T07:28:50Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1.Install python 3.4.2 AMD 64
2.Install sypder 2.3.2 AMD 64 3. 

What is the expected output? What do you see instead?

 Installation of the spyder. Error message regarding registry
settings. Screenshot attached. What version of the product are you using? On what operating system? Spyder 2.3.2 AMD 64. I am using windows 7 64bit, sp1. 

Please provide any additional information below

. I am not able to manually enter the python path and the installation
forlder either. Python works fine.  I

**Attachment:** [spyder-error.png](http://code.google.com/p/spyderlib/issues/detail?id=2165)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2165_

**Comment by spyder-issues-migrator** [comment]
_From [android....@gmail.com](https://code.google.com/u/100864648954163226526/) on 2015-02-07T04:33:22Z_

Uninstalling and reinstalling python 3.4.2 did not work either. Spyder 2.3.2
is a fresh install.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-07T16:02:34Z_

We don't do anything special with our installers, so I don't know what could be causing this error.

In any case, just installing Spyder after Python won't get you too far. Spyder depends in a lot of other Python modules to be really usable.

I'd sincerely recommend you to use a Scientific Python distribution, instead of the procedure you're trying to follow. Please read our docs about it: http://pythonhosted.org/spyder/installation.html#installing-on-windows-xp-vista-7-8

**Summary:** Spyder can't find Python in the registry  \<span class="oldvalue"> (was: spyder 2.3.2 amd 64 doesn't install with python amd 64) \</span>  
  **Labels:** OpSys-Windows

**Comment by ccordoba12** [comment]
Closing as this is too old now and haven't heard of it again.

**Comment by Data-Scientist-I** [comment]
I had similar issues. My finding: although my computer is 64 bits, the Python version I installed is 32 bit.
I solved this by switching to a diff version of the Spyder installation exe file.
