### ISSUE TITLE
Spyder interprets other keys as down arrow

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2166]
_From [jdjen...@eng.ucsd.edu](https://code.google.com/u/118134596718107831597/) on 2015-02-07T15:57:56Z_

Spyder Version:  2.3.1
Python Version:  2.7.9
Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.3.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

Occasionally Spyder begins to treat other keystrokes as though they were the down arrow, including other direction arrow keys and letter keys. It may be that it can happen other keys besides down arrow, and that it has just happened to be the problem key in my case. I have had to close and restart Spyder (using the mouse, since keyboard input is taken as a down arrow). Once it begins, it isn't entirely consistent; some fraction of keystrokes are interpreted correctly. It's not a system-wide issue, because other applications work fine in the meantime. 

Unfortunately, I have no idea how to reproduce this sporadic problem. 

This is on Ubuntu 14.04. 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2166_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-07T15:57:02Z_

I use Spyder daily to develop Spyder itself, and I haven't seen something like this error.

Perhaps it's related to the program or programs you're running in Spyder, I don't know :-)

**Comment by spyder-issues-migrator** [comment]
_From [jdjen...@eng.ucsd.edu](https://code.google.com/u/118134596718107831597/) on 2015-02-07T16:15:42Z_

The only program I run within Spyder, as far as I know, is the IPython console. And this is an issue with the entire application, including the main editing window; it's not just within the IPython console.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-07T17:29:22Z_

I meant the source code you evaluate in Spyder :-)

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by justinmathew7** [comment]
I get this strange behavoir quite frequently. It seems to only happen after there is a high level of memory usage. The only way I can solve it is by re-starting spyder.
