### ISSUE TITLE
Text extraction from store bills use pytesract 

### ISSUE THREAD

**Issue by Basavanagoud** [spyder-ide/spyder#21674]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

```
# -*- coding: utf-8 -*-
"""
Created on Tue Jan  2 20:01:59 2024

@author: PMC
"""

import pytesseract 
import PIL.Image
import re
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime

def process_image(image_path):
    text = pytesseract.image_to_string(PIL.Image.open("F:\project 360 digitmg\Invoice.jpg"))
    print(text) 
    cleaned_text = " ".join(text.split())
    return cleaned_text

def extract_information(cleaned_text): 
    bill_date_pattern = r'B11\] No\s*:\s*(\S+).Dt\s:\s*(\d{2}/\d{2}/\d{4})' 
    bill_no_pattern = r'Vou, No\s*:\s*(\S+)'
    item_patterns = r'(\d+)\)\s*(.+?)\s(\d+)\s*(\d+\.\d+)\s*(\d+\.\d+)'
    item_matches = re.findall(item_patterns, cleaned_text)
    
    bill_date_match = re.search(bill_date_pattern, cleaned_text)
    bill_no_match = re.search(bill_no_pattern, cleaned_text)
    
    bill_date = datetime.strptime(bill_date_match.group(2), '%d/%m/%Y').date() if bill_date_match else None 
    bill_no_raw = bill_no_match.group(1) if bill_no_match else None 
    bill_no = int(''.join(filter(str.isdigit, bill_no_raw))) if bill_no_raw else None
    
    data = [
        {'Bill_Date': bill_date, 'Bill_No':bill_no, 'Product_Name':match[1], 'Quantity': int(match[2]),'Price': float(match[4])}
        for match in item_matches
    ] 
    return data

def save_to_database(data, engine, table_name='billing_details'):
    df = pd.DataFrame(data)
    df.to_sql(table_name, con=engine, if_exists='replace', index=False)

def main():
    image_path = "F:\project 360 digitmg\Invoice.jpg"
    cleaned_text = process_image(image_path)
    data = extract_information(cleaned_text)
    engine = create_engine('mysql+pymysql://root:basava8660@localhost/text_extraction')

    try:
        save_to_database(data, engine)
        with engine.connect() as connection:
            sql_query = "SELECT * FROM billing_details;"
            details = pd.read_sql_query(sql_query, con=engine)
            print(details)
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    main()
```

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

```
runfile('F:/project 360 digitmg/untitled2.py', wdir='F:/project 360 digitmg')
  File <unknown>:61
    main()
    ^
SyntaxError: invalid non-printable character U+00A0
```

I am getting these error if I run the code and output should be extracted text it should be in SQL as it's connection is given but it's not showing anything 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 3.11.3
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by rhkarls** [comment]
Does this code run outside of Spyder? 

Also make sure to either use forward-slash (/), double-backsladh (\\) or raw strings (e.g. image_path = r"F:\project 360 digitmg\Invoice.jpg") when using strings to represent paths on Windows.

**Comment by ccordoba12** [comment]
Hey @Basavanagoud, thanks for reporting. Did you copy your code, or parts of it, from a web page?

**Comment by Basavanagoud** [comment]
I have copied the code

**Comment by ccordoba12** [comment]
Closing due to lack of response. Hopefully you managed to solve this error.
