### ISSUE TITLE
Spyder forgets custom python environment after each run

### ISSUE THREAD

**Issue by SireneNova** [spyder-ide/spyder#21693]
### What steps will reproduce the problem?

1. Create a new python environment in anaconda prompt
2. Activate anaconda environment
3. install new library in environment such as pythonnet
4. install spyder-kernels
5. open spyder IDE and set the python interpreter to the custom environment from step 1 and 2
6. run the script calling the new module installed in environment (like pythonnet) (it works the first time)
7. run the script again without restarting the kernel (get an error that module is not found/not correct. directory is changed back to default/base.)
8. restart kernel and run (works again)

I don't want to have to restart the kernel every time I run in an environment. It makes no sense that a different python interpreter would be used than the one set in the IDE preferences. 

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.20.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.8.0 (OK)
numpy >=1.7                                      :  1.26.3 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  1.11.4 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

**Comment by GitKia1392** [comment]
Well then don't create a new environment every single time(maybe save it) and auto load it into Spyder

> Try that

Thanks

**Comment by SireneNova** [comment]
What do you think my question was? What are you reading where it says I create a new environment every time? One environment is saved in Spyder and it is not used after clicking "run" unless the kernel is refreshed. This is described plainly and in detail above. Visual Studio does not have this issue, and I have switched to that.

**Comment by mrclary** [comment]
@SireneNova, I'm a Spyder core developer. I'm sorry that you are having this issue with Spyder; you should not have to restart the kernel and the custom environment you specified should persist. I see that you are using Spyder 5.4.3. Would you be willing to update to our latest stable version (5.5.0) and see if you still have the same problem? I would also recommend using our standalone installer:
https://github.com/spyder-ide/spyder/releases/download/v5.5.0/Spyder_64bit_full.exe

**Comment by SireneNova** [comment]
@mrclary Thank you Ryan, I'll try that and get back to you on how it goes. Installing outside of the Anaconda prompt takes special permissions where I'm working, so I'll try the prompt first.

**Comment by GitKia1392** [comment]
Ok calm down @SireneNova, and plus, we are humans(at least i hope so) so we make mistakes, And @mrclary then if ur a "Spyder core developer"(no offense)  then u should know it was like issued in Spyder 6.0.0; I bet @ccordoba12 would 100% know

**Comment by CAM-Gerlach** [comment]
@SireneNova thanks so much from me as well (another Spyder core developer) for your detailed issue report and agreeing to take the time to test this with the newest stable release. You'll want to update to our latest stable Spyder kernels version in the environment you're using as well (Spyder will give you the command to run in your Anaconda prompt on launching the kernel if its outdated). And we also appreciate your calm and measured response to the other user's less than kind comments :)

@GitKia1392 As another Spyder core developer, I would like to remind you to please be kind and respectful when commenting here, ensure you carefully read and understand issues before posting a claimed "solution", and refrain from unnecessarily aggressive, dismissive and uncivil remarks toward others, particularly users like @SireneNova who take the time to submit a detailed issue report with a reproducible example, and core developers like @mrclary who spend hundreds if not thousands of hours of their volunteer time for free to maintain Spyder and help users like you. Thanks.

**Comment by ccordoba12** [comment]
Just to be clear, I second @CAM-Gerlach 's and @mrclary 's comments here.

**Comment by SireneNova** [comment]
@mrclary It looks like the reported issue is indeed resolved in 5.5. It didn't install from the prompt, but your link to the standalone installer worked. When switching environment preferences, spyder needs to be restarted for it to register the change, but after that, it remembers the settings, and I don't have to refresh the kernel. Thanks all for the help and your work on this!

**Comment by mrclary** [comment]
@SireneNova, you are welcome. I'm glad everything is working for you now.

**Comment by CAM-Gerlach** [comment]
> When switching environment preferences, spyder needs to be restarted for it to register the change, but after that, it remembers the settings, and I don't have to refresh the kernel. 

You certainly shouldn't be needing to restart Spyder just to change the working environment to start new kernels in; it _should_ just work if you start a new kernel after changing the setting. Does that not work? It seems to work fine for me on Windows, at least with my testing. If not, could you confirm the behavior you are getting? Thanks!

**Comment by SireneNova** [comment]
@CAM-Gerlach Restarting the kernel works too :). This is not a problem to do. It is a bit non-obvious, so having a note in the settings might be helpful in general to have, such as "kernel may need to be restarted for changes to take affect the first time".

**Comment by mrclary** [comment]
@SireneNova, I'm closing this issue now. If the issue recurs, please feel free to reopen.
