### ISSUE TITLE
Bug: Unexpected type 'float' when clicking in Spyder preferences

### ISSUE THREAD

**Issue by dan123456-eng** [spyder-ide/spyder#21694]
### What steps reproduce the problem?

1. Just click on preferences in the Spyder toolbar.

### Paste Traceback/Error Below (if applicable)
Traceback (most recent call last):

**File "C:\\Users\\dan-s\\miniconda3\\envs\\ciermag-develop\\Lib\\site-packages\\spyder\\widgets\\helperwidgets.py", line 216, in sizeHint**

return QSize(doc.idealWidth(), doc.size().height())

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

TypeError: arguments did not match any overloaded call:

QSize(): too many arguments

QSize(w: int, h: int): argument 1 has unexpected type 'float'

QSize(a0: QSize): argument 1 has unexpected type 'float'

## Versions

Spyder version: 5.5.0
Python version: Python 3.12
Qt version: n/a
PyQt version: PyQt5= 5.15.10
Operating System name/version: Windows10 and Ubuntu

**Comment by dan123456-eng** [comment]
```
One of the possible solutions implemented is the code below, where the height and width 
values are converted to integers.

    def sizeHint(self, option, index):
        options = QStyleOptionViewItem(option)
        self.initStyleOption(options, index)

        doc = QTextDocument()
        doc.setHtml(options.text)
        doc.setTextWidth(options.rect.width())

        return QSize(int(doc.idealWidth()), int(doc.size().height()))
```

**Comment by ccordoba12** [comment]
Hey @dan123456-eng, thanks for reporting and also for providing a fix for this! We'll include it in our next version (5.5.1), to be released soon.

**Comment by dan123456-eng** [comment]
> Hey @dan123456-eng, thanks for reporting and also for providing a fix for this! We'll include it in our next version (5.5.1), to be released soon.

Thank you
