### ISSUE TITLE
Anaconda3 spyder launch causes segmentation fault: 11

### ISSUE THREAD

**Issue by rss81** [spyder-ide/spyder#21712]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm trying to run spyder from Anaconda3 on a 2010 macbook pro running High Sierra.  I keep getting this segmentation fault: 11 error.  The docs say Anaconda supports High Sierra 13.6 and above.  I'm running the most recent version of Anaconda Nav 2.5.2 and spyder 5.4.3  

Should I be trying to install older versions or is there another way to fix this

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @rss81, thanks for reporting. Unfortunately, we can't help you with this because it depends entirely on the packages provided by Anaconda. In other words, it's not a Spyder problem.

So, we recommend you to post your problem in this repo:

https://github.com/ContinuumIO/anaconda-issues/

There the Anaconda team should give you support to solve your problem.
