### ISSUE TITLE
Internal Console does not maintain Show/Hide state across sessions

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2173]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2015-02-12T18:30:31Z_

Summary:
\--------
The internal console does not maintain its show/hide state upon startup.

Spyder Version:  2.3.2
Python Version:  2.7.6
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
zmq >=2.1.11    :  14.0.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2 (OK)
rope >=0.9.2    :  0.10.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4.1 (OK)
coverage >=0.25 :  3.7.1 (OK)
pylint >=0.25   :  1.0.0 (OK)

To Reproduce:
\-------------
1. Load Spyder
2. Enable display of Internal Console via View -> Panes -> Internal Console
3. Close Spyder
4. Load Spyder again
5. Go to menu item View -> Panes -> Internal Console. Notice that it is checked, but no internal console is displayed.

Expected Output:
\----------------
Upon step 4, the internal console should be displayed in the area with all the other consoles

Actual Output:
\--------------
Upon step 4, no internal console is displayed. However, the menu item is still checked.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2173_

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-02-13T09:39:07Z_

Hi Doug, 

I have noticed this behavior before, and I think It might have gotten fixed in the development version.

Can you check for this?

Install mercurial (hg) and run

`hg clone https://goanpeca@bitbucket.org/spyder-ide/spyderlib spyder`

got to the folder after download

`cd spyder`

and then run in bootstrap mode and check if you experience the same issue

`python bootstrap.py`

Cheers

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-13T12:12:51Z_

This is not a bug, it's a decision I took before 3.0 based on feedback I received during SciPy 2013.

This was what people told me:

1. They were sent to the Internal Console because of an internal bug.

2. That console remained opened and focused from then onwards.

3. People used that console to evaluate code, which was a disaster because that console doesn't run in a external process and so heavy computations block the entire interface.

4. After some time people noted the problem and moved to the Python or IPython consoles.

5. When an internal bug occurred again, people entered this cycle again.


So now we hide the internal console on restarts. However, if you start Spyder with our bootstrap.py script, like this

    python bootstrap.py

we don't hide it. My rationale is that bootstrap is used to do development, so in this case you don't want the internal console to be automatically hidden because you are (most probably) debugging something :-)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-13T12:13:16Z_

Sorry, I decided this before 2.3.0

**Comment by spyder-issues-migrator** [comment]
_From [doug.t...@gmail.com](https://code.google.com/u/107157864673511712940/) on 2015-02-13T12:16:18Z_

Ok cool, intentional behavior.

So then the bug is that the Menu Item "View -> Panes -> Internal Console" remains checked even though the console is intentionally hidden on restart.

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2015-02-13T12:36:28Z_

Exactly!, that is why I suggested you check this with the dev version. 

I noticed this behavior not only with the internal console, but with all the dockwidgets (panels) after setting a custom layouts.

**Comment by dougthor42** [comment]
Adding comment so that I get notifications and so that I can find my issues/comments more easily.

**Comment by goanpeca** [comment]
@dougthor42 not sure which commit it was, but I think @ccordoba12 fixed this here

https://github.com/spyder-ide/spyder/blob/master/spyderlib/spyder.py#L1238
