### ISSUE TITLE
Editor pop-up menu unreadable black background

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2174]
_From [cstark...@gmail.com](https://code.google.com/u/108904972813835652563/) on 2015-02-14T12:10:20Z_

Please note that reporting bugs from Spyder's help menu ("?" > "Report
issue...") will fill version details for Spyder, Python and Qt in this description for you. 

What steps will reproduce the problem?

 1. Modify Spyder editor syntax coloring prefs 2. 3. 

What is the expected output? What do you see instead?

 Pop-up menu should have white background /or/ invert against text colors in pop-up.
Instead, background is black, text is black, pop-up commands thus unreadable What version of the product are you using? On what operating system? Spyder 2.3.2 for Python 3.4 on Mac OS 10.10 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2174_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-15T15:20:15Z_

Could you post a screenshot please? I really don't understand what you mean.

**Comment by ccordoba12** [comment]
Closing because of lack of further info
