### ISSUE TITLE
Ubuntu Spyder

### ISSUE THREAD

**Issue by lamgezer** [spyder-ide/spyder#21747]
## Description

**What steps will reproduce the problem?**

1. Start Spyder from the app in Ubuntu 18.04.6
2. IDE will open, but "Connecting to kernel" will stay on
3. Spyder terminal will not open

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression
TypeError: object list can't be used in 'await' expression

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.9
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.14.0 (OK)
pandas >=0.13.1  :  1.1.5 (OK)
numpy >=1.7      :  1.19.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.17.2 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  7.16.3 (OK)
pylint >=0.25    :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
Hey @lamgezer, thanks for reporting. I'm afraid you're using a very old version of Spyder which is not supported anymore.

To start working with our latest version (5.5.0), which shouldn't have any issues, you need to:

* Remove the current version you're using with `sudo apt-get remove spyder`
* Install 5.5.0 with pip in a virtualenv or using Anaconda. Both options are described in detail in [our documentation](http://docs.spyder-ide.org/current/installation.html).
