### ISSUE TITLE
Breakpoint in thread function not hit

### ISSUE THREAD

**Issue by laiki** [spyder-ide/spyder#21744]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In my application I can't set a breakpoint in a thread worker function and get the log message 

> 2024-01-30 11:04:33.325 | DEBUG    | spyder_kernels.customize.spyderpdb:preloop:592 - Could not get breakpoints from the frontend.

I created a minimal reproducer to test setting a breakpoint in a threads worker function, which also is not hitted, but unfortunatelly it does not provided the above spyder_kernel message.
I guess using breakpoints in threaded applications should be possible, so I'm creating this ticket for further analysis

I installed Spyder using pip and have upgraded it to the latest version by `pip install --upgrade spyder spyder-kernels`

### What steps reproduce the problem?
set the breakpoint inside the workers while loop and start the debug session, will not stop the process at the breakpoint

```
from threading import Thread
import queue
from loguru import logger


#%% globals
QUEUE_1 = queue.Queue() 
QUEUE_2 = queue.Queue() 

#%% functions
def worker():
    global QUEUE_1
    global QUEUE_2
    while True:
        value = QUEUE_1.get()
        logger.debug(f"worker value: {value}")
        value += 1
        QUEUE_2.put(value)
        
        if 10 == value:
            break
    return

def main():
    global QUEUE_1
    global QUEUE_2

    thread = Thread(target=worker)    
    thread.start()
    
    value = 0
    while True:
        QUEUE_1.put(value)
        value = QUEUE_2.get()
        logger.debug(f"main value: {value}")
        if 10 == value: break
    thread.join()
    return

#%%
if __name__ == '__main__':
    logger.remove()
    logger.add('threading.log', level='DEBUG', watch=True)
    main()
```

### What is the expected output? What do you see instead?

debugger should stop execution inside worker thread, instead execution finishes while reaching the end of the process

### Paste Traceback/Error Below (if applicable)

```python-traceback



```

## Versions

* Spyder version: 5.5.0
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt version: PyQt5 5.15.10
* Operating System name/version: Linux 6.2.0-37-generic (x86_64)  -- (Ubuntu 22.04.3 LTS) 

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  1.7.3 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.15.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0            :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0       :  1.2.1 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.0,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.0.0 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
xdg >=0.26                       :  0.27 (OK)
zmq >=22.1.0                     :  25.1.0 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.1 (OK)
numpy >=1.7                      :  1.24.3 (OK)
pandas >=1.1.1                   :  2.1.3 (OK)
scipy >=0.17.0                   :  1.11.3 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @laiki, thanks for reporting. This is a known limitation, i.e. our debugger doesn't work very well with threaded applications.

What happens if you set a breakpoint with code by adding a `breakpoint()` call to the line you want to stop in in your thread?

**Comment by laiki** [comment]
Hi @ccordoba12 thanks for the hint. Using the function `breakpoint()` works :)

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
