### ISSUE TITLE
MY ICONS HAVE GONE !!

### ISSUE THREAD

**Issue by toni-hernandez** [spyder-ide/spyder#21758]
![Spyder IDE](https://github.com/spyder-ide/spyder/assets/158570946/76684dad-560e-47fb-8586-cc8b5c5486ff)

Hi !!

I need your help becacuse I've lost some icons/buttons from my Spyder IDE. As you can see I have no icon for: "Run current cell", "Run current cell and go to the next one" and "Run selection or current line".

I've try everything I have seen in forums, I have tried reinstalling, etc. But it's still the same.

Please, ¿ have you any idea about this  issue ? ( Thanks in advance )

**Comment by GitKia1392** [comment]
Uhh @toni-hernandez, that's real weird. Try going into the folder where yo installed spyder and see if there is a `spyder.ico` thing in there. if not then it's corrupted or missing. if it IS there then go to another pc and install spyder and find spyder.ico and stuff, put it into a USB an paste it in there; if you don't have another one(i mean pc) then i give u the files/icons' that are missing from MY installation.

Best,
Kiamehr

**Comment by GitKia1392** [comment]
@ccordoba12 could you pls close this issue as @toni wont respond

> Hope this closes

Best,
<Github User GitKia1392, 1020540038344541392>

**Comment by ccordoba12** [comment]
Hey @toni-hernandez, thanks for reporting and sorry for the late reply. Are those the only icons missing from your installation? Or are there any others?

**Comment by GitKia1392** [comment]
COME ON CLOSE IT BRO U CAN SEE HE'S GONE AFK OK.

**Comment by ccordoba12** [comment]
@GitKia1392, our internal norm is to wait for a week after a core developer answers an issue before closing it.

Also, as we have told you before, please be respectful of other users in this space. This the second time we've said you this, so if you want to keep participating here, I recommend you to change your attitude.

**Comment by GitKia1392** [comment]
Ok sorry but um its been 2 weeks...

**Comment by ccordoba12** [comment]
Closing due to lack of response.
