### ISSUE TITLE
A monitor scale change was detected pop up screen, couldn't close this screen. 

### ISSUE THREAD

**Issue by xywust2014** [spyder-ide/spyder#21765]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I run a program for 4 days using Spyder (3.10). The results are done and I want to save the final output data. However, I encountered an pop-up screen that "A monitor scale change was detected. We recommend restarting Spyder to ensure that it is properly displayed. If you don't want to do that, please be sure to activate the option". I couldn't close this pop-up screen.The only way to close this is to click on the Restart now. 

My question is that after my program finishes, is there anyway that I could access my final result variable from the anaconda prompt or somewhere else? I am desperately need the final output. As long as I could have access to this final result variable, I am good. I am afraid that I will lose my variables from here since I have deadlines.

Thank you very much for your help and I really appreciate it. 

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by xywust2014** [comment]
It is Spyder (Python 3.10).

**Comment by ccordoba12** [comment]
Hey @xywust2014, thanks for reporting and sorry for the inconvenience. You said:

> My question is that after my program finishes, is there anyway that I could access my final result variable from the anaconda prompt or somewhere else? I am desperately need the final output.

Unfortunately, it's not possible, sorry.

Please be sure to update to our latest version (5.4.3 if you're in Anaconda or 5.5.1 otherwise) because this problem should be fixed in it. To update you need to close Spyder, open the Anaconda Prompt or a system terminal, and run there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
