### ISSUE TITLE
The Newest Update Version, installed today, is not opening

### ISSUE THREAD

**Issue by me-suzy** [spyder-ide/spyder#21778]
The Newest Update Version, installed today, is not opening. Version 5

I updated and installed directly from the program, because a pop-up appeared asking me if I wanted to install the newest version.

Ok, I downloaded it, it installed. I try to open it, the image of the program appears, but suddenly it closes. Intitializing....

And if I look in the Task Manager window, the program does not appear, so it means that it has not opened.

I have windows 11, laptop

I check the .exe, seems that  **spyder.exe**  is missing from  install folder **C:\Program Files\Spyder\Python** .
Maybe this is why onlye the Intro launch is opening, but there is no .exe

**Comment by ccordoba12** [comment]
It's this one: https://github.com/spyder-ide/spyder/releases/download/v5.5.0/Spyder_64bit_full.exe

**Comment by emolmar** [comment]
I also have a problem with 5.5.1. Edge says "Spyder_64bit_5.5.1.exe isn't commonly downloaded. Make sure you trust Spyder_64bit_5.5.1.exe before you open it." After I downloaded it with another browser, the antivirus blocked the installer.
Version 5.5.0 works correctly,

**Comment by ccordoba12** [comment]
@emolmar, the installers are built exactly in the same way in every version. Unfortunately, we can't control what Edge and your antivirus report or do, sorry.

**Comment by ccordoba12** [comment]
Hopefully you managed to solve this issue but I'm going to close it due to lack of response.
