### ISSUE TITLE
Standalone installers for 6.0 alpha4 are incorrectly named and Mac installer failed to build

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#21776]
* I left the assets for Windows and Linux as they were uploaded by Github actions, instead of downloading, renaming and uploading them again myself with the right names.
* About the Mac installer you can see this: https://github.com/spyder-ide/spyder/actions/runs/7824722718/job/21348477707
* I hid the section about the installers in the release message until this is solved.

@mrclary, please take a look at this one.

**Comment by ccordoba12** [comment]
> How would you like to proceed? Shall I submit a pull request and we can release an alpha5?

I agree with submitting a PR if changes in our code are necessary to fix these issues. But I'd prefer (if possible) that you upload new assets with the right names because that should be enough for alpha4.

**Comment by mrclary** [comment]
> I agree with submitting a PR if changes in our code are necessary to fix these issues. But I'd prefer (if possible) that you upload new assets with the right names because that should be enough for alpha4.

Okay, I'll submit a PR to be included in the next release. For alpha4, I'll build macOS locally and upload correct name. For Windows and Linux, I'll re-upload with correct name.
