### ISSUE TITLE
When using the scientific_startup, module QtCore.QString is not found

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#2178]
_From [MattBRow...@gmail.com](https://code.google.com/u/117210463431928454928/) on 2015-02-16T11:47:03Z_

Spyder Version:  2.2.5
Python Version:  2.7.6
Qt Version    :  4.8.6, PyQt4 (API v1) 4.10.4 on Linux
pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=0.13  :  1.2.1 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  None (NOK)
matplotlib >=1.0:  1.3.1 (OK)
pylint >=0.25   :  None (NOK) 

What steps will reproduce the problem?

 1.Set the console startup script to default scientific_startup.py
2.from PyQt4 import QtCore
3.print QtCore.QString.fromUtf8("20 °C") 

What is the expected output? What do you see instead?

 expected: 20 °C
actual output: AttributeError: 'module' object has no attribute 'QString' 

Please provide any additional information below

. Using the default console startup script gives the expected output with no problems
-Thanks!

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2178_

**Comment by spyder-issues-migrator** [comment]
_From [MattBRow...@gmail.com](https://code.google.com/u/117210463431928454928/) on 2015-02-16T08:48:52Z_

By the way, using the default python startup is no problem for me, so my workflow is not really affected by this. Spyder is a great product, thanks for developing it!

**Comment by spyder-issues-migrator** [comment]
_From [MattBRow...@gmail.com](https://code.google.com/u/117210463431928454928/) on 2015-02-16T11:07:38Z_

I have now learned that the QString module doesn't exist in python 3, and this is likely related to my problem. Note that the python version Spyder uses for me is 2.7.6, and I haven't installed some python3 versions of other libraries that I use in my program. So, it seems that the 2.7 libraries are being used for some modules while the 3.4 libraries are being used for PyQt4. . . maybe? Hope that helps!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-02-16T11:37:48Z_

Could you update to Spyder 2.3.2 and test again? 2.2.5 is unmaintained now.

**Summary:** When using the scientific_startup, module QtCore.QString is not found  \<span class="oldvalue"> (was: when using the scientific_startup, module QtCore.QString is not found) \</span>  
  **Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [MattBRow...@gmail.com](https://code.google.com/u/117210463431928454928/) on 2015-02-16T14:10:48Z_

I upgraded to 2.3.2, but get the same behavior

**Comment by ccordoba12** [comment]
This is not relevant anymore, now that we moved to support only API#2
