### ISSUE TITLE
kernel issue not connecting

### ISSUE THREAD

**Issue by japintandia** [spyder-ide/spyder#21786]
### What steps will reproduce the problem?

Not connecting my kernel. so my program is not showing output.please help me.

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

### Environment

<details><summary>Environment</summary>

```

```
</details>

**Comment by ccordoba12** [comment]
Hey @japintandia, thanks for reporting. Could you post a screenshot of what you're seeing in Spyder so that we can better understand your problem? Thanks!

**Comment by Abhinav-IIRS** [comment]
@ccordoba12 Hi, I am facing a similar issue when connecting to a remote kernel. The connecting to kernel popup keep on rotating while the connection is not established. I start the kernel in a remote workstation (with miniconda installed) using the command `python -m spyder_kernels.console`. Following which a json file is created that I transfer to my local system. I run spyder in my local system (with anaconda) in an environment named Env. I use anaconda prompt to activate the environment and launch spyder. The connection to remote kernel in spyder is made through 'connect to an existing kernel' option after filling the details of username and password for ssh connection.
I have observed anaconda prompt log showing error whenever I try to connect to remote kernel. The error shown is ` Failed to connect to 192.168.2.28:22: BadHostKeyException('192.168.2.28', <paramiko.ecdsakey.ECDSAKey object at 0x000002B09336CCA0>, <paramiko.ecdsakey.ECDSAKey object at 0x000002B093345FA0>)`

Earlier, the remote workstation had CentOS 7 installed, it is replaced with Ubuntu 20.04 after failure of disks. Does it mean that the host keys were changed and the connection could not be established? Thanks for your help.

**Comment by ccordoba12** [comment]
> Does it mean that the host keys were changed and the connection could not be established? Thanks for your help.

Probably. Please try to use/generate (if possible) new keys to see if that fixes the problem.

**Comment by Abhinav-IIRS** [comment]
I have cleaned my known host keys and made a connection using command prompt. After this the connection to the kernel was successful. Thank you for the advice.

**Comment by ccordoba12** [comment]
@Abhinav-IIRS, great! Thanks for letting us know about it.

Since we didn't hear back from @japintandia, I'm going to close this issue due to lack of response.
