### ISSUE TITLE
It's not clear what some actions in the new Options menus of Variable Explorer editors do

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#21824]
* This is a follow-up of #21666.
* I think the addition of Options menus to our editors is a fantastic idea. But after reviewing them manually, I think we could improve the names of some of its actions to make it clearer what they do.
* In particular, I'm talking about `Format`, which we could rename to `Set format for floating point numbers` (or something like that). Furthermore, we could add a descriptive text to the dialog that opens after clicking on it with a link to the format syntax that users can set there.
* Another option that I find difficult to understand is `Column min/max`. Just by reading that text, I don't understand what it does. And I tried to enable/disable it in a simple dataframe and I didn't see any difference.

**Comment by ccordoba12** [comment]
> or `Set format for floats...`, with the three dots indicating that a dialog will follow.

I like this suggestion because it works better for a menu entry (I know mine was too long).

> The best description I can come up with is "Assign colours by column", but I don't think that is very clear either.

Yeah, that seems hard to explain with the action text alone. We could also say `Assign colors by column min/max`, but in other languages that could translate to a very long text (e.g. in Spanish it'd be `Asignar colores según el max/min de cada columna`).

> This requires a fuller explanation elsewhere, either in a tooltip or in our documentation.

Since tooltips in menus are not an expected UI element, that's perhaps not an option. And improving our docs is a good idea but the interface should be easy enough to grasp on its own.

> We can also consider removing that option. I can imagine situations where it could be useful but I'm not sure how much it is actually used, and it is hard to find out what it does.

Yeah, that's another option but I wouldn't like to remove current functionality because I'm sure some users rely on it and wouldn't be happy about it.

**Comment by jitseniesen** [comment]
A more radical idea is not to have the options (hamburger) menu, but instead have a toolbutton like :wrench: . That button opens up a dialog with a text field for the format string for floating point numbers and two checkbuttons, one for turning on/off the background colour and one for the column min/max option. The advantage is that we can use a bit more text in a dialog window and we can also add tooltips. However, this is quite a big thing to do before 6.0.

**Comment by ccordoba12** [comment]
> A more radical idea is not to have the options (hamburger) menu, but instead have a toolbutton like 🔧 

This is a very good idea! @CAM-Gerlach, what do you think?

> However, this is quite a big thing to do before 6.0.

I could give you a hand with it after we release beta1.

**Comment by PhilipYip1988** [comment]
I think the col min/max applies the background color independently for each pd.Series:

<img width="482" alt="img001" src="https://github.com/spyder-ide/spyder/assets/56493395/7246f9a1-28d6-455e-861e-100da3a55712">

Or across the pd.DataFrame wide:

<img width="482" alt="img002" src="https://github.com/spyder-ide/spyder/assets/56493395/d0e1cd7f-f9e7-47da-ac1c-dcc333646699">

The subtle difference can be seen in the DataFrame above.

It might be better to have a dropdown box with something like:

background color applied via: ['series', 'dataframe']

<img width="482" alt="img003" src="https://github.com/spyder-ide/spyder/assets/56493395/246bd8fb-2bda-4d3f-9906-123089890bac">

**Comment by jitseniesen** [comment]
Here is a (non-functional) mock-up of what a dialog window can look like. I put the new toolbar button to the left of the refresh button, where the button for setting the format used to be. 

My main doubt is whether I should combine the two groups ("Background color" and "Coloring algorithm") in one group with three options.

If this looks promising, then I can implement the functionality and submit a PR so that we can start fine tuning the text and the graphics layout. What do you think?

https://github.com/spyder-ide/spyder/assets/7941918/aee17993-202e-4362-86ef-b86e1c1354fb

**Comment by ccordoba12** [comment]
This looks really nice, thanks @jitseniesen! My only suggestion is to leave the current Options menu and add this as an action called `Additional preferences`.

That way we would maintain consistency with the other editors and we could also add a `Close` action (with a shortcut) to that menu later on to solve issue #21814.
