### ISSUE TITLE
sys.exit(0)  is a false error

### ISSUE THREAD

**Issue by kandel3** [spyder-ide/spyder#2183]
sys.exit(0) can be used to indicate successful completion, in contrast to, for example, sys.exit(1)

Spyder 2.3.2 shows this an error (see attached screenshot)

![Screenshot](https://cloud.githubusercontent.com/assets/1521589/6312452/97972d5c-b93e-11e4-96ec-eb703417aec8.png)

**Comment by ccordoba12** [comment]
But the error is not reported by our code, so I don't understand where *our* error is.

**Comment by jondo** [comment]
Maybe this is another case where Spyder could try to catch an exception thrown by `exit`, as in issue #1974?

**Comment by zbyna** [comment]
@jondo I had problem with kernel quitting but it was not caused by sys.exit.
This helped me:
``` python
app.aboutToQuit.connect(app.deleteLater)
```
For details please see: #1558

**Comment by ccordoba12** [comment]
@kandel3, what is the expected behavior for Spyder in this case?

**Comment by kandel3** [comment]
sys.exit(0) should not display an error message. I don't like the red text and Traceback.

**Comment by ccordoba12** [comment]
This is not an error generated by Spyder (as can be clearly seen in your screenshot).

To run this code without errors, you need to press F6 and select

    Execute in an external System terminal

There `sys.exit(0)` will have the effect you expect.
