### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by tk41c** [spyder-ide/spyder#21831]
### What steps will reproduce the problem?

from sgnlp.models.ufd.utils import parse_args_and_load_config
from sgnlp.models.ufd.train import train
import json

cfg = parse_args_and_load_config("json file directory")
train(cfg)

Above is the code i got from the sgnlp ufd's documentation to train the ufd model on a custom dataset. As this is my first time training a pre trained NLP im not sure what im doing wrong but i keep getting the error:
 
 File ~\anaconda3\envs\myenv\lib\encodings\cp1252.py:23 in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3: character maps to <undefined>

I have tried many solutions but none of them have worked. 

Is there something im doing wrong? 

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  1.7.3 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.15.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  6.5.4 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.2.0 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.0.0 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  23.2.0 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.7.2 (OK)
numpy >=1.7                                      :  1.24.3 (OK)
pandas >=1.1.1                                   :  2.0.3 (OK)
scipy >=0.17.0                                   :  1.11.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

**Comment by tk41c** [comment]
> Hey @tk41c, thanks for reporting. You said:
> 
> > I have tried many solutions but none of them have worked.
> > Is there something im doing wrong?
> 
> I'm not really sure but I have a quick question for you about this. In this line
> 
> ```
> cfg = parse_args_and_load_config("json file directory")
> ```
> 
> what's the real path that you're using for `json file directory`? I mean, could you post it here to check it?

Hi @ccordoba12 this is my filepath "C:/Users/tony k/anaconda3/envs/myenv/Lib/site-packages/sgnlp/models/ufd/config/ufd_config_train.json"

**Comment by tk41c** [comment]
Hi @ccordoba12 I managed to solve the error by specifying the encoding (UTF-8) in https://github.com/aisingapore/sgnlp/blob/83fb17170ec06436f58cd2758b6824b0d8c160a8/sgnlp/models/ufd/utils.py#L151

Thank you for your help.

**Comment by ccordoba12** [comment]
Ok, great! Thanks for letting us know about it.
