### ISSUE TITLE
Regarding the Silent Command line customization for changing the Install Location

### ISSUE THREAD

**Issue by metaad** [spyder-ide/spyder#21841]
### Issue Report Checklist

* [ Yes] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ Yes] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ NA] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ NA] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [NA ] Tried basic troubleshooting (if a bug/error)
    * [ NA] Restarted Spyder
    * [ NA] Reset preferences with ``spyder --reset``
    * [ NA] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ NA] Tried the other applicable steps from the Troubleshooting Guide
* [ NA] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
While installing the Application we are able to change the install location in GUI.
But when we are trying to install the application using command line we are not able to change the install location for the application
"C:\Temp\Working\Spyder_64bit_full1.exe" /S /allusers is working fine.

### What steps reproduce the problem?

1. /D="c:\test 1" 
2. /d="c:\test 1"
3. /DIR="c:\test 1"
4. /dir="c:\test 1"
5. /APPDIR="c:\test 1"
are not working and did not find any guide regarding this issue.
### What is the expected output? What do you see instead?

I would like to change the install location during command line silent installation to my desired path/folder

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.5.0 and 5.5.1 
* Operating System name/version:  Windows 10 and windows 11

**Comment by dalthviz** [comment]
Hi @metaad thank you for reaching out! Could it be possible for you to try with `/INSTDIR=` instead of `/D=` ? Let us know if that helps!
