### ISSUE TITLE
Variable Explorer Refreshing

### ISSUE THREAD

**Issue by sangheumcho** [spyder-ide/spyder#21840]
Spyder IDE 

The Scientific Python Development Environment | Spyder-IDE.org 

Python 3.11.5 64-bit | Qt 5.15.2 | PyQt5 5.15.7 | Windows 10 

This is my Spyder version.

If I click the variable refreshing button, then the screen seems to go to the middle of the list, while I just want to stay on the particular part of the list that I am looking at.

Can it stay on the part that I am looking at though I click the refresh button of the variable explorer?

**Comment by dalthviz** [comment]
Hi @sangheumcho thank you for the feedback! I'm not totally sure to follow what you mean, sorry! Could it be possible for you to share here a screen record video/GIF to better understand what do you mean? Also, could you post here the Spyder version info that comes from clicking the `Copy version info` from the Spyder About dialog? Let us know!

**Comment by ccordoba12** [comment]
I think what @sangheumcho meant is what was already reported on issue #21508: restore the vertical scrollbar position after the Variable explorer is refreshed or updated.

Given that they are basically the same feature request, I'm going to close this issue in favor of that one.
