### ISSUE TITLE
`menuinst` `Exception: Nothing to do:` traceback when installing Spyder 6.0.0a4 on Windows

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21855]
## Problem Description

I was trying to setup a new conda env with Spyder 6.0.0a4 on Windows and got a traceback related with `menuinst`. Spyder is still able to launch from the anaconda prompt but I think no shortcut was created 🤔 

### What steps reproduce the problem?

1. Run the following to create an env:

```cmd
conda create -n spyder6_test -c conda-forge python=3.11
conda activate spyder6_test
conda install -c conda-forge/label/spyder_dev -c conda-forge/label/spyder_kernels_rc -c conda-forge spyder=6.0.0a4
```

### What is the expected output? What do you see instead?

No traceback error and shortcut creation to launch Spyder from the env created. Instead I got a traceback related with `menuinst` after conda installed Spyder

### Paste Traceback/Error Below (if applicable)

```traceback
Executing transaction: \ menuinst Exception
Traceback (most recent call last):
  File "C:\Users\dalth\anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 267, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\Users\dalth\anaconda3\lib\site-packages\menuinst\__init__.py", line 75, in install
    _install(path, remove, prefix, mode='user', root_prefix=root_prefix)
  File "C:\Users\dalth\anaconda3\lib\site-packages\menuinst\__init__.py", line 48, in _install
    ShortCut(m, sc).create()
  File "C:\Users\dalth\anaconda3\lib\site-packages\menuinst\win32.py", line 318, in create
    raise Exception("Nothing to do: %r" % self.shortcut)
Exception: Nothing to do: {'name': 'Spyder 6 ({{ ENV_NAME }})', 'description': 'Scientific PYthon Development EnviRonment', 'icon': '{{ MENU_DIR }}/spyder.{{ ICON_EXT }}', 'activate': False, 'terminal': False, 'command': [''], 'platforms': {'win': {'desktop': True, 'app_user_model_id': 'spyder.Spyder', 'command': ['{{ PREFIX }}/pythonw.exe', '{{ PREFIX }}/Scripts/spyder-script.py']}, 'linux': {'Categories': ['Development', 'Science'], 'command': ['{{ PREFIX }}/bin/spyder', '$@'], 'StartupWMClass': 'Spyder'}, 'osx': {'precommand': 'pushd "$(dirname "$0")" &>/dev/null', 'command': ['./python', '{{ PREFIX }}/bin/spyder', '$@'], 'link_in_bundle': {'{{ PREFIX }}/bin/python': '{{ MENU_ITEM_LOCATION }}/Contents/MacOS/python'}, 'CFBundleName': 'Spyder 6', 'CFBundleIdentifier': 'org.spyder-ide.Spyder', 'CFBundleVersion': '6.0.0a4'}done
```

## Versions

* Spyder version: 6.0.0a4  (conda)
* Python version: 3.11.8 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0              :  1.4.1 (OK)
chardet >=2.0.0                   :  5.2.0 (OK)
cloudpickle >=0.5.0               :  3.0.0 (OK)
cookiecutter >=1.6.0              :  2.6.0 (OK)
diff_match_patch >=20181111       :  20230430 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1  :  8.22.2 (OK)
jedi >=0.17.2,<0.20.0             :  0.19.1 (OK)
jellyfish >=0.7                   :  1.0.3 (OK)
jsonschema >=3.2.0                :  4.21.1 (OK)
keyring >=17.0.0                  :  24.3.1 (OK)
nbconvert >=4.0                   :  7.16.2 (OK)
numpydoc >=0.6.0                  :  1.6.0 (OK)
paramiko >=2.4.0                  :  3.4.0 (OK)
parso >=0.7.0,<0.9.0              :  0.8.3 (OK)
pexpect >=4.4.0                   :  4.9.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.9.8 (OK)
pygments >=2.0                    :  2.17.2 (OK)
pylint >=2.5.0,<3.1               :  2.16.2 (OK)
pylint_venv >=3.0.2               :  3.0.3 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0            :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0        :  2.0.0 (OK)
pyuca >=1.2                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0         :  3.2.3 (OK)
qstylizer >=0.2.2                 :  0.2.2 (OK)
qtawesome >=1.3.0                 :  1.3.0 (OK)
qtconsole >=5.5.1,<5.6.0          :  5.5.1 (OK)
qtpy >=2.4.0                      :  2.4.1 (OK)
rtree >=0.9.7                     :  1.2.0 (OK)
setuptools >=49.6.0               :  69.1.1 (OK)
sphinx >=0.6.6                    :  7.2.6 (OK)
spyder_kernels >=3.0.0b4,<3.0.0b5 :  3.0.0b4 (OK)
superqt >=0.6.1,<1.0.0            :  0.6.1 (OK)
textdistance >=4.2.0              :  4.5.0 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  4.0.0 (OK)
zmq >=22.1.0                      :  25.1.2 (OK)

# Optional:
cython >=0.21                     :  None (NOK)
matplotlib >=3.0.0                :  None (NOK)
numpy >=1.7                       :  None (NOK)
pandas >=1.1.1                    :  None (NOK)
scipy >=0.17.0                    :  None (NOK)
sympy >=0.7.3                     :  None (NOK)

```

**Comment by ccordoba12** [comment]
@mrclary, please takea look at this one.

**Comment by mrclary** [comment]
@dalthviz, can you confirm the `conda` and `menuinst` versions in your base environment?

**Comment by dalthviz** [comment]
Seems like I have `conda` 23.7.4 and `menuinst` 1.4.19:

![image](https://github.com/spyder-ide/spyder/assets/16781833/f73c12d8-a513-458f-8d38-c161edce10c7)

**Comment by mrclary** [comment]
> Seems like I have `conda` 23.7.4 and `menuinst` 1.4.19:

That would explain it, then. Updating to `menusint >= 2.0` and `conda >= 23.11` in the base environment will resolve the issue.

**Comment by dalthviz** [comment]
Oh I see, then is there some way we could alert this to users when installing? Maybe we need to explain that constraints regarding the base conda env in the Spyder 6.0.0a4 GitHub release installation instructions?

**Comment by mrclary** [comment]
> Oh I see, then is there some way we could alert this to users when installing? Maybe we need to explain that constraints regarding the base conda env in the Spyder 6.0.0a4 GitHub release installation instructions?

I'm not sure. @jaimergp, do you know if a menu yaml can constrain the `menuinst` version? How can updates to menu yaml for `menuinst` >= 2.0 enforce this constraint in the base environment since `menuinst` is not necessarily in the install environment?

**Comment by ccordoba12** [comment]
This really serious because users with old `menuinst` versions won't have menu entries on Windows in Spyder 6 due to this.

Perhaps we could try to detect if they have `menuinst < 2.0` in their base env in our recipe to use the old `menu.json` file? Could that be possible @mrclary?

**Comment by jaimergp** [comment]
I think there's a `__conda` virtual package you might be able to leverage in the package shipping the JSON.

**Comment by mrclary** [comment]
Without `__conda` available, there is no way to prevent Spyder 6 from being installed conditioned on the conda version. Doing anything in the post-link script can only affect what we do with the shortcut.

Options if `menuinst < 2.0` is discovered by the post-link script:
1. Remove `spyder-menu.json`. Spyder would still install, but the shortcut would not be created. This is the easiest thing to do. We can try to print a warning message that advises users to update conda or menuinst, but I don't know if conda will relay stdout from the post-link script or suppress it.
2. Include a copy of the old menu.json file in the feedstock and rename or remove the unnecessary file conditioned on the version of menuinst.

**Comment by ccordoba12** [comment]
I prefer option 2. because it's hard to expect that people will read a single message among a lot of other (not so informative) output. Besides, they can install Spyder through Navigator, which won't allow them to see a message like that.

**Comment by mrclary** [comment]
According to the [docs](https://docs.conda.io/projects/conda-build/en/latest/resources/link-scripts.html), post-link scripts should:
> * Not depend on any installed or to-be-installed conda packages.
> * Depend only on simple system tools such as rm, cp, mv, and ln.
>
> The scripts should not write to stdout or stderr unless an error occurs, but they may write to $PREFIX/.messages.txt, which is shown after conda completes all actions.

In order to detect menuinst version, I'll have to assume the base environment python executable is available 🤞🏼

**Comment by ccordoba12** [comment]
Fixed by https://github.com/conda-forge/spyder-feedstock/pull/161.
