### ISSUE TITLE
My Python 3.11 is not responding when launch Spyder with Anaconda latest version

### ISSUE THREAD

**Issue by kimsiang02** [spyder-ide/spyder#21886]
### Issue Report Checklist

* [✔] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ✔] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [✔ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ✔] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ✔] Tried basic troubleshooting (if a bug/error)
    * [✔ ] Restarted Spyder
    * [ ✔] Reset preferences with ``spyder --reset``
    * [ ✔] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ✔] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Same issue with the (My Python 3.11 is not responding #21779 https://github.com/spyder-ide/spyder/issues/21779 )
![image](https://github.com/spyder-ide/spyder/assets/80630257/41670424-7f13-4eb5-b3dc-a334ab82a372)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.3
* Python version: 3.11
* Qt version: 5.4.2
* PyQt version: 
* Operating System name/version: Win 10

### Dependencies

```
PASTE DEPENDENCIES HERE
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.20.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  3.0.3 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  2.0.0 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.2.2 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  None (NOK)
numpy >=1.7                                      :  1.26.4 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  None (NOK)
sympy >=0.7.3                                    :  None (NOK)

**Comment by kimsiang02** [comment]
![image](https://github.com/spyder-ide/spyder/assets/80630257/41670424-7f13-4eb5-b3dc-a334ab82a372)

**Comment by kimsiang02** [comment]
Pardon me if i late reply, im malaysian might having time zone issue.

**Comment by ccordoba12** [comment]
Hey @kimsiang02, thanks for reporting. As I said on that issue:

Please try to disable your antivirus, firewall and/or VPN and try again. Those could be interfering with Spyder in unexpected ways and causing this problem.

Let us know if that works for you.

**Comment by kimsiang02** [comment]
I have checked and antivirus and firewall all has been disabled

**Comment by kimsiang02** [comment]
alright thanks
