### ISSUE TITLE
can't run win_post_install from pip

### ISSUE THREAD

**Issue by mikofski** [spyder-ide/spyder#2188]
please add this snippet to spyder_win_post_install.py to mimic bdist_wininst. I cribbed it from pywin32_post_install.py. Thanks!

    try:
        # When this script is run from inside the bdist_wininst installer,
        # file_created() and directory_created() are additional builtin
        # functions which write lines to Python23\pywin32-install.log. This is
        # a list of actions for the uninstaller, the format is inspired by what
        # the Wise installer also creates.
        file_created
        is_bdist_wininst = True
    except NameError:
        is_bdist_wininst = False # we know what it is not - but not what it is :)
        def file_created(file):
            pass
        def directory_created(directory):
            pass
        def get_root_hkey():
            try:
                winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE,
                               root_key_name, 0, winreg.KEY_CREATE_SUB_KEY)
                return winreg.HKEY_LOCAL_MACHINE
            except OSError, details:
                # Either not exist, or no permissions to create subkey means
                # must be HKCU
                return winreg.HKEY_CURRENT_USER

    try:
        create_shortcut
    except NameError:
        # Create a function with the same signature as create_shortcut provided
        # by bdist_wininst
        def create_shortcut(path, description, filename,
                            arguments="", workdir="", iconpath="", iconindex=0):
            import pythoncom
            from win32com.shell import shell, shellcon

            ilink = pythoncom.CoCreateInstance(shell.CLSID_ShellLink, None,
                                               pythoncom.CLSCTX_INPROC_SERVER,
                                               shell.IID_IShellLink)
            ilink.SetPath(path)
            ilink.SetDescription(description)
            if arguments:
                ilink.SetArguments(arguments)
            if workdir:
                ilink.SetWorkingDirectory(workdir)
            if iconpath or iconindex:
                ilink.SetIconLocation(iconpath, iconindex)
            # now save it.
            ipf = ilink.QueryInterface(pythoncom.IID_IPersistFile)
            ipf.Save(filename, 0)

        # Support the same list of "path names" as bdist_wininst.
        def get_special_folder_path(path_name):
            import pythoncom
            from win32com.shell import shell, shellcon

            for maybe in """
                CSIDL_COMMON_STARTMENU CSIDL_STARTMENU CSIDL_COMMON_APPDATA
                CSIDL_LOCAL_APPDATA CSIDL_APPDATA CSIDL_COMMON_DESKTOPDIRECTORY
                CSIDL_DESKTOPDIRECTORY CSIDL_COMMON_STARTUP CSIDL_STARTUP
                CSIDL_COMMON_PROGRAMS CSIDL_PROGRAMS CSIDL_PROGRAM_FILES_COMMON
                CSIDL_PROGRAM_FILES CSIDL_FONTS""".split():
                if maybe == path_name:
                    csidl = getattr(shellcon, maybe)
                    return shell.SHGetSpecialFolderPath(0, csidl, False)
            raise ValueError("%s is an unknown path ID" % (path_name,))

**Comment by ccordoba12** [comment]
I'm afraid you're going to need to create a pull request, because this *snippet* is too big and somethings seem to be repeated with our code.

**Comment by mikofski** [comment]
This snippet checks if spyder is being installed from a bdist_wininst .exe archive on a Windows machine or something from else, eg pip. It checks for several attributes that are available when using bdist_wininst ie `file_created`, `create_shortcut()` and `get_special_folder_path()` and if it doesn't find them, creates dummy functions that do the same thing.

**Comment by ccordoba12** [comment]
I understand now, but please do a pull request for this.

**Comment by ccordoba12** [comment]
Could you also comment what's the exact problem that your snippet solves? Is it that you can't install Spyder on Windows using pip because of the lack of it?

**Comment by mikofski** [comment]
On Windows, if user installs spyder using pip, then tries to run the win_post_install script, to add the start menu shortcuts which are quite nice, especially for less savvy, terminal-phobic users which spyder is a good choice for (ie: MATLAB converts), the user will get a nasty traceback because some of the module level attributes are only available when this script is part of a bdist_wininst

**Comment by mikofski** [comment]
Would it be okay to make [pywin32](http://sourceforge.net/projects/pywin32/) a depndency on Windows systems? maybe something else already depends on pywin32?

**Comment by ccordoba12** [comment]
@mikofski, unfortunately nothing else depends on `pywin32` :-(

**Comment by mikofski** [comment]
Does this mean that it can't be pulled? We can do it without pywin32, by using ctypes on ole32.dll and shell32.dll, which are both part of standard library, but it's modicum more work and I think most Windows users will already have Mark Hammond's pywin32 package.

**Comment by ccordoba12** [comment]
Your pull request can be merged without problems because you added a message about `pywin32` being required to run our post install script.

So if it's not found, the script will fail but people will know why :-)

**Comment by mikofski** [comment]
Great, let me know if there's anything else you need.
