### ISSUE TITLE
Connect errors without specific handling triggered while doing a check for updates to our error report dialog

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21882]
> > Most probably a generic exception is due to an internal Spyder error. So, we need to connect this to our error report dialog. But since the code related to updates diverged significantly between 5.x and master, I think it's better to leave this for master.
> 
> Should an issue be open for that or maybe and issue tracking that already exists @ccordoba12 ?
> 
_Originally posted by @dalthviz in https://github.com/spyder-ide/spyder/pull/21868#discussion_r1520498446_

Connect catched Exceptions that are not shown in a dialog when checking for updates to the Spyder error report dialog

**Comment by ccordoba12** [comment]
@mrclary, could you take care of this one?
