### ISSUE TITLE
Plugin for Unittest, nose would be helpful.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#219]
_From [Kriss.Kr...@gmail.com](https://code.google.com/u/107526939039474200048/) on 2010-05-13T13:29:44Z_

A plugin for running unittests or nose on the current source code would be
very helpful for test driven development. 

At the moment you have to manually run the tests in interactive or external
console. A similar option is available for example in pyscripter. For an
optimal workflow one would need to run the tests by pressing a key and get
feedback with a green/red symbol and optionally the error message in case
the test fails.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=219_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-04-15T07:26:06Z_

Anyone is welcome to develop it. As Kriss says, it would be really really helpful

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-04-19T08:13:19Z_

issue #633 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ispma...@gmail.com](https://code.google.com/u/114408377892021802753/) on 2011-04-19T10:46:48Z_

How hard would be do do a plugin for that? What is necessary?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-18T00:28:40Z_

**Status:** ContributorNeeded

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T13:37:35Z_

**Labels:** Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [yarikop...@gmail.com](https://code.google.com/u/106463979469591360865/) on 2011-11-19T21:01:45Z_

probably a useless comment but: I have decided to look into spyder again (saw post on planet scipy) and immediately asked myself either it could replicate the simple nose.el I am using within emacs and find extremely useful to troubleshoot one test among many without reverting to manual crafting of cmdline for nosetests to be ran in the terminal

so please just take this as a vote toward higher priority for this wishlist

Cheers

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:10:39Z_

**Status:** HelpNeeded  
  **Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [david.ve...@gmail.com](https://code.google.com/u/108342766018366950755/) on 2013-08-30T04:28:49Z_

Just like to mention issue #1543 in this context as well ( https://code.google.com/p/spyderlib/issues/detail?id=1543 ).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-10-14T18:14:15Z_

issue #1605 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2014-06-30T10:15:06Z_

Plugin structure:

1. GUI - runs as Spyder thread, executes runner
2. Runner - discovers and executes tests

I can see the main problem is separation between runner and Spyder. Runner should run in separate process, to avoid messing with Spyder internals, and there is not known way to pass Qt signals from Runner back to GUI. So the only way I know is to parse Runner output in GUI thread. If there are already parsers for unittest output (or at least for Test Anything Protocol) then the action list is:

1. Create GUI
2. Create subprocess with piped output
3. Parse output in real-time
4. Update GUI

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-07-02T07:15:06Z_

I started such a plugin but didn't have time to finish it: https://github.com/Nodd/spyder_unittesting It is based on spyder's profiler plugin.

Too many ideas, too little time...

**Comment by goanpeca** [comment]
This is being developed as a plugin in a separate repo https://github.com/spyder-ide/spyder-unittest/

@ccordoba12 since this is not directly tied to this repo, can we just close it?

**Comment by ccordoba12** [comment]
Yep.
