### ISSUE TITLE
Trojan warning after download Spyder 5.5.3 Spyder_64bit_lite.exe

### ISSUE THREAD

**Issue by somera** [spyder-ide/spyder#21904]
## Problem Description

After downloading Spyder_64bit_lite.exe my Windows 11 shows

![image](https://github.com/spyder-ide/spyder/assets/8334250/8a39bed8-e9a8-4601-b1bc-11afdbf5c3f6)

**Comment by ccordoba12** [comment]
Hey @somera, thanks for reporting. Our Windows installer doesn't contain a trojan. It's simply a false alarm of your antivirus that you can ignore.

**Comment by DummyTheGoat** [comment]
What
