### ISSUE TITLE
Update French translations for 2.3.3

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2190]
@SylvainCorlay or @Nodd, can you help me with this one? The sooner it'd be the better because this is the last thing to do before releasing 2.3.3

Please remember to submit the PR against the **2.3** branch, and not against master.

**Comment by ccordoba12** [comment]
Hey guys, any update on this one? I need to release as soon as possible so that 2.3.3 can be included in Ubuntu 15.04.

**Comment by SylvainCorlay** [comment]
No worries I can do it tonight. Unless Joseph jumps in earlier!

**Comment by ccordoba12** [comment]
Great, thanks Sylvain!
