### ISSUE TITLE
Release 5.5.4

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21936]
This is an issue to track changes regarding dependencies done for the new Spyder 5.5.4 release.

* New/updated dependencies:
     * `qtawesome` >=1.3.1,<1.4.0 (see #21939)
     * `python-lsp-server` >=1.11.0,<1.12.0 + `pylint` >=3.1,<4 (see #21942)

**Comment by bnavigator** [comment]
Would you consider to also backport the changes for pylint 3.1, please?

**Comment by ccordoba12** [comment]
@bnavigator, what changes are you referring to?

**Comment by ccordoba12** [comment]
If you can submit a PR here and another one in pylsp to do that until Monday or Tuesday, then we can include it in 5.5.4.
