### ISSUE TITLE
Spyder doesnt remember settings upon zooming out in the editor on new pc (Windows 11)

### ISSUE THREAD

**Issue by Chuck321123** [spyder-ide/spyder#21932]
### Issue Report Checklist

Checklist checked

## Problem Description

So I got a new pc and installed Spyder. However, Spyder is not able to remember my settings when i zoom out in the editor on windows 11. Upon closing and restarting it goes back to standard (but other settings are remembered).

### What steps reproduce the problem?

Dont know. Maybe using windows 11?

### What is the expected output?

That it remembers that i have zoomed out in the editor

## Versions
* Spyder version: 5.5.3  (conda)
* Python version: 3.12.2 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-11-10.0.22631-SP0

**Comment by ccordoba12** [comment]
Hey @Chuck321123, hope you figured this one out by yourself. But the zoom settings are just temporary. If you want to permanently see bigger text in the Editor and console, you need to go to `Preferences > Appearance` and select a bigger font size.
