### ISSUE TITLE
Can't delete files

### ISSUE THREAD

**Issue by 671620616** [spyder-ide/spyder#2193]
I am unable to delete a file using `os.remove()`.  It throws the following exception:

```python
In [6]: os.remove('Tools_')
Traceback (most recent call last):

    File "<ipython-input-6-d959ae30d275>", line 1, in <module>
      os.remove('Tools_')

WindowsError: [Error 5] Access is denied: 'Tools_'
```

even though my user is an admin and Spyder has been run as an admin.
The directory 'Tools_' is in the current working directory, is a Spyder project, and not passworded.

Computer specs:
Windows 8.1
Intel Celeron CPU 900@2.20GHz
2GB RAM
x64bit, x32 spyder & Anaconda install (64 bit install was causing problems with numpy)
Spyder version 2.3.2
iPython qtconsole version 2.3.1

The problem is very repeatable, happens every time with removing a file.

**Comment by stonebig** [comment]
could you check via `os.listdir('Tools_')` that you are looking at the right absolute path ?

**Comment by 671620616** [comment]
`os.listdir('Tools_')` returned `['.spyderproject', 'cmd_schedule.py']` which is correct.  I'm fairly sure I have the right absolute path.
Also I noticed that I can't delete anything at all while Spyder is open - not even from the Windows file explorer.

**Comment by ccordoba12** [comment]
This is not an Spyder error. `os.remove` doesn't let you remove directories, just files, as can be read in [its help](https://docs.python.org/2/library/os.html#os.remove).

Just use `os.rmdir` or `os.removedirs`

**Comment by 671620616** [comment]
Even with `os.rmdir` I get the same error:

```python
In [12]: os.rmdir('Tools_')
Traceback (most recent call last):

    File "<ipython-input-5-d959ae30d275>", line 1, in <module>
      os.rmdir('Tools_')

WindowsError: [Error 5] Access is denied: 'Tools_'
```

**Comment by ccordoba12** [comment]
Sorry to hear it, maybe `os.removedirs` or [shutil.rmtree](https://docs.python.org/2/library/shutil.html#shutil.rmtree) can help.

But as I said before, this is not a Spyder bug, so we can't help you any further.

**Comment by 671620616** [comment]
Ok - I'll try with `shutil`.  Thanks for the help!
