### ISSUE TITLE
after start no window

### ISSUE THREAD

**Issue by khmenne** [spyder-ide/spyder#21944]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When you start, the Spyder image appears and all modules are loaded. After that, no screen appears anymore.
How can I determine what's going on?
greeting
Karl Heinz

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.5.3
* Python version: 3.11.5
* Qt version: 
* PyQt version: 
* Operating System name/version: W11

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @khmenne, thanks for reporting. How did you install Spyder? Did you use Anaconda, our own installer or pip?

**Comment by khmenne** [comment]
I install it with installer from website

**Comment by khmenne** [comment]
As additional information, everything was going well but from one day to the next this effect occurred. I don't know what I did.

**Comment by ccordoba12** [comment]
> I install it with installer from website

But the version you reported above for Python is 3.11.5. So, do you have an additional Python installation in your system?

**Comment by khmenne** [comment]
yes i dont delete older versions

**Comment by ccordoba12** [comment]
Ok, that could be the problem in this case. Could you remove this directory (if it's available in your system)

    C:\Users\<your user>\AppData\Roaming\Python\

and try again?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
