### ISSUE TITLE
Spyder Crashed and is not restarting 

### ISSUE THREAD

**Issue by shidehnaderi** [spyder-ide/spyder#2194]
Got the good old 'Spyder crashed during last session' error, while I was trying to multi thread.
Tried  'python -c "from spyderlib.spyder import main; main()" --reset'
but it doesn't appear to be working. Gives the same error again. Tried manually removing stuff from .Spyder, still no result. 
![error](https://cloud.githubusercontent.com/assets/5849423/6332063/f823de04-bb37-11e4-80c9-7c596ef97df3.png)

**Comment by 671620616** [comment]
Happened to me some time ago-
I went into the source and had to comment out some bit of code (naturally I can't remember which) but it had been creating a temporary file in the .Spyder directory and not deleting it, causing problems on startup.

**Comment by shidehnaderi** [comment]
I can't access the code to make changes though.

**Comment by stonebig** [comment]
maybe try a reboot first ?

**Comment by shidehnaderi** [comment]
Didn't find a fix so I re-installed anaconda but before that I removed EVERYTHING Spyder related. Did a re-install before hand without completely cleaning Spyder left-overs, didn't work. '
All works now.
