### ISSUE TITLE
I got these messsage

### ISSUE THREAD

**Issue by jaime719** [spyder-ide/spyder#21940]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by jaime719** [comment]
raceback (most recent call last):

  File ~/anaconda3/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/expenses.tracker.py:67
    main()

  File ~/expenses.tracker.py:17 in main
    print(expense)

  File ~/expense.py:17 in __repr__
    return f"Expense, {self.name}, {self.category}, ${self.amount:.2f}"

ValueError: Unknown format code 'f' for object of type 'str'

**Comment by jaime719** [comment]
Someone can help me out with these error

**Comment by ccordoba12** [comment]
Hey @jaime719, thanks for reporting. I think the problem is this part of your f-string:

    ${self.amount:.2f}

Most probably `self.amount` is not a number in your code (i.e. an integer or float in your code) but a string. And that's why Python can't get two decimals of a string to print it along with your other attributes (i.e. `self.name` and `self.category`).

Let us know if that helps you to solve this problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
