### ISSUE TITLE
Do not translate `Commit` in context menu of Files/Projects

### ISSUE THREAD

**Issue by LucyJimenez** [spyder-ide/spyder#21959]
To maintain consistency and clarity in the Spyder IDE, it's crucial to prevent the translation of the word "Commit." This term holds universal significance in version control systems and must remain consistent across all language versions of the software. Therefore, it's recommended to implement measures to ensure that "Commit" is not subject to translation in any localized versions of Spyder.

**Comment by ccordoba12** [comment]
Thanks @LucyJimenez for reporting. We'll fix this for Spyder 6, to be released in a couple of months.
