### ISSUE TITLE
Non-recognized command message when running code that gives a traceback with a custom interpreter set on Windows (IPython Console) 

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#21960]
## Problem Description

An error message/output appears the first time a console executes something:

![image](https://github.com/spyder-ide/spyder/assets/16781833/c1d66c82-3f90-41ee-ad61-c812eea53aab)

### What steps reproduce the problem?

1. Set a custom interpreter (probably one that has a space in its path)
2. Launch a new console (to make it use the new custom interpreter)
3. Run some code (for example type `a` and execute that)

### What is the expected output? What do you see instead?

Only the traceback should be seen, instead, also a error message related with a command being unrecognized is seen (maybe related with the custom interpreter activation process failing?):

### Paste Traceback/Error Below (if applicable)

```python-traceback
"C:/Program" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
```

## Versions

* Spyder version: 5.5.4rc1  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

**Comment by ccordoba12** [comment]
@dalthviz, I was unable to reproduce this one, so please work on it to see if you manage to solve it.

However, I have a couple of recommendations:

* I made some changes to the code that activates envs with Micromamba in PR #21947 (I thought they were necessary to deal with envs in directories with spaces). So, you can check if reverting them fixes the problem.
* You can try to activate the envs with Conda instead of Micromamba to see if that prevents the problem. While trying to reproduce this bug, I found some odd issues with Micromamba (not this error though) but not with Conda.

**Comment by ccordoba12** [comment]
Another thing that could be significant in this case (i.e. the reason why I was unable to reproduce this) is if you installed Spyder in `C:\Program files` (I always install it for the current user).

If that's case, then you could check if Micromamba is correctly quoted everywhere is called.

**Comment by dalthviz** [comment]
I think the issue comes from the micromamba path indeed since my install is for all user and then micromamba is used from `C:\Program files\Spyder\...` . I will give this a check :+1:

Also, thinking about this, I remembered that I did in the past some fixes for this at https://github.com/spyder-ide/spyder/pull/20758 but I guess #21947 fixes some other things, right?

**Comment by ccordoba12** [comment]
> Also, thinking about this, I remembered that I did in the past some fixes for this at https://github.com/spyder-ide/spyder/pull/20758 but I guess https://github.com/spyder-ide/spyder/pull/21947 fixes some other things, right?

It simply added more quotes here and there to the `conda-activate.bat` script in order to deal with directories with spaces.
