### ISSUE TITLE
IPython consoles are not named correctly when connecting to existing kernels and passing the full kernel path

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/spyder#2197]
It seems that ipython console names don't contain the kernel number anymore, making it more difficult to connect multiple consoles to the same kernel. This is true in both the `2.3` and the master `branch`.

**Comment by ccordoba12** [comment]
I know, I decided to remove that *feature*. I think very few people understood what those numbers meant.

We could revert that in 2.3.4, by letting people adding the feature to rename each console. But I'm not sure about it.

**Comment by SylvainCorlay** [comment]
Gotcha.
Another issue then is that the when you *still* connect to the same console via the connection file, the number used for the console name is now different (and therefore the suffix letter in the console name is unnecessary).

**Comment by ccordoba12** [comment]
I think it's working as expected. I get

* Terminal 1/A
* Terminal 1/B
* Ternimal 1/C

when I connect several consoles to the kernel of Terminal 1. That's how it worked before and what I'm seeing on Linux in master.

**Comment by ccordoba12** [comment]
Could you post an screenshot of what you're seeing?

**Comment by SylvainCorlay** [comment]
I get 
- Terminal 1/A
- Terminal 2/A
while I am connected to the same kernel in both consoles. See the screenshots bellow. 

![console1a](https://cloud.githubusercontent.com/assets/2397974/6431999/21a6e6b8-c010-11e4-8b8e-f1da9d083146.png)
![console2a](https://cloud.githubusercontent.com/assets/2397974/6432002/2a5dfd32-c010-11e4-9a49-11f62bcbb41b.png)
