### ISSUE TITLE
Spyder wants to update 5.5.1->5.5.3, but conda wants to downgrade 5.5.1->5.3.1

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#21979]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder``
The issue is related to updating with conda ...

## Problem Description
I am experiencing inconsistencies w.r.t. attempts to update from 5.5.1->5.5.3

### What steps reproduce the problem?
1. Open Spyder with "Check for updates at startup" enabled
2. After some time Spyder suggests: Spyder 5.5.3 is available! ...
3. Performing a "conda update --all", will not perform the upgrade, instead it produces (amongst others):
'''
The following packages will be downloaded:
    ....
    spyder-5.3.1               |   py39hf3d152e_0        12.0 MB  conda-forge
    spyder-kernels-2.3.3       |   py39hf3d152e_0         108 KB  conda-forge
    ...
The following packages will be SUPERSEDED by a higher-priority channel:
    ...
  spyder-kernels     conda-forge/noarch::spyder-kernels-2.~ --> conda-forge/linux-64::spyder-kernels-2.3.3-py39hf3d152e_0
    ...
The following packages will be DOWNGRADED:
    ...
  spyder                               5.5.1-py39hf3d152e_0 --> 5.3.1-py39hf3d152e_0
    ...
'''
### What is the expected output? What do you see instead?
I did expect an upgrade to the version proposed by the Spyder IDE, i.e., 5.5.3, instead conda wants to downgrade to 5.3.1.
I have not attempted to force the new version with "conda install -c conda-forge spyder=5.5.3", because I have never needed to do such things.

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.9.18 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Linux-6.7.8-lp155.2.g08a1e2c-default-x86_64-with-glibc2.31

### Dependencies
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.18.1 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.3 (OK)
jsonschema >=3.2.0               :  4.21.1 (OK)
keyring >=17.0.0                 :  25.0.0 (OK)
nbconvert >=4.0                  :  7.16.3 (OK)
numpydoc >=0.6.0                 :  1.7.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.4 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.1 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  69.2.0 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.1 (OK)
textdistance >=4.2.0             :  4.5.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.0 (OK)
xdg >=0.26                       :  0.28 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  3.0.10 (OK)
matplotlib >=3.0.0               :  3.8.3 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.1 (OK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  1.12 (OK)

**Comment by ccordoba12** [comment]
Hey @xaverm, thanks for reporting. You said

> Performing a "conda update --all", will not perform the upgrade

Using `conda update --all` is usually not a good idea because when it tries to update all packages, it can lead to downgrading others (as you found out).

What we recommend is to update specific packages instead, i.e. the ones you actually want updates for. In Spyder's case, the update command needs to be

    conda install -c conda-forge spyder=5.5.3 

By the way, that's the command you probably saw in the same message that informed you that a new update was available.

If you still want to use `conda update --all`, then please report this problem to the conda team on this repository:

https://github.com/conda/conda

because we can't help you with that, sorry.

**Comment by xaverm** [comment]
@ccordoba12
Sorry for continuing this: Yes, `conda install -c conda-forge spyder=5.5.3` is suggested from within the IDE ... yet ... I'm not sure if this is related, but after following this advice, spyder is now confused about its dependencies.

As you can see from the original post, I had

### Mandatory dependencies:
keyring >=17.0.0 : 25.0.0 (OK)

After pinning `spyder>=5.5.3` in `/conda-meta/pinned`, I now do indeed have
```
conda list | grep spyd
spyder                    5.5.3            py39hf3d152e_0    conda-forge
```
**but** now spyder IDE claims
### Mandatory dependencies:
keyring >=17.0.0                 :  None (NOK)

even though in this environment I have
```
~>conda list | grep key
keyring                   25.1.0             pyha804496_0    conda-forge
```
Even more so, rolling back the spyder version with `conda install -c conda-forge spyder=5.5.1` does not undo this issue anymore?!

**Comment by ccordoba12** [comment]
> but now spyder IDE claims
Mandatory dependencies:
keyring >=17.0.0 : None (NOK)

This is a problem with the `keyring` Conda-forge package that we're trying to solve at the moment (see https://github.com/conda-forge/admin-requests/pull/974 for the details). Please ignore it in the meantime.
