### ISSUE TITLE
Spyder Directory

### ISSUE THREAD

**Issue by Damien6345** [spyder-ide/spyder#21971]
Hello

Is it possible to change the temporary directory, which by default is C:\Users\XXXXX\\.spyder3 at C:\Users\XXXXX\documents\\.spyder3 ?

Thanks to all

**Comment by ccordoba12** [comment]
Hey @Damien6345, thanks for reporting. You said:

> Is it possible to change the temporary directory

Yes, it is. You need to start from the command line with the command

    spyder --conf-dir C:/Users/XXXXX/documents/.spyder3

to use that directory other directory for your settings.

Let us know if that works as expected for you.

**Comment by Damien6345** [comment]
Hello

Thank you for your reply.
I've made some progress, and I've achieved what I want by modifying the spyder.ini file directly, i.e. changing the language, setting another default directory for the new files, i.e. in my case C:\Users\admin\Documents instead of C:\Users\admin .
Here are two things I'd like to know for my Windows computer rooms:
- Is it possible for all new user sessions to use the same pre-customised .ini file with the same configuration, which would be different from the default configuration, for example, when a new user logs on to the machine, so that for example the language defined does not revert to the default language, and the same goes for the default directory?
- Is it possible to change the default opening behaviour of Spyder and temp.py which is stored by default on C:\Users\admin\.spyder-py3\temp.py 
 
Thanks

**Comment by ccordoba12** [comment]
> Is it possible for all new user sessions to use the same pre-customised .ini file with the same configuration, which would be different from the default configuration, for example, when a new user logs on to the machine, so that for example the language defined does not revert to the default language, and the same goes for the default directory?

Yes, you need to place a `spyder.ini` file with your desired options (it doesn't need to be a copy of your user `spyder.ini`, just the ones that you want to customize) in one of the directories listed by the command:

    spyder --paths

We haven't tested that too much, but it should do the trick.

> Is it possible to change the default opening behaviour of Spyder and temp.py which is stored by default on C:\Users\admin.spyder-py3\temp.py

Users can change it by going to the menu `Tools > Preferences` and then

    Editor > Advanced settings > Edit template for new files

but I think we don't have a way to change it for all users in a network.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
