### ISSUE TITLE
NameError: name '' not defined

### ISSUE THREAD

**Issue by manethedane** [spyder-ide/spyder#21987]
### What steps will reproduce the problem?

Define a function, eg:

```python
def gaussian_likelihood(mu,sigma2,x):
    n = float(len(x))
    first = 1/((2*np.pi*sigma2)**(n/2))
    then = (-(n/2*sigma2)*(np.mean(x)-mu)+np.var(x))
    lik = first*np.exp(then)
    return(lik)
```

Then attempt to execute the function in console, eg: 

```python
x = np.array([1,2,4,0]) 
gaussian_likelihood(0.34,np.var(x),x)
```

Will get NameError: name 'gaussian_likelihood' is not defined. 

Code works fine when run by other people/devices. 

## Versions

* Spyder version: 5.5.1  (conda)
* Python version: 3.11.5 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.0 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20200713 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.0.1 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.5.0 (OK)
paramiko >=2.4.0                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.8.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=2.5.0,<3.1              :  2.16.2 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.2 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.0.1 (OK)
setuptools >=49.6.0              :  68.0.0 (OK)
sphinx >=0.6.6                   :  5.0.2 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.2.1 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  2.1.6 (OK)
zmq >=22.1.0                     :  25.1.2 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.8.0 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.1.4 (OK)
scipy >=0.17.0                   :  1.12.0 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @manethedane, thanks for reporting. I have a quick question for you: did you define your `gaussian_likelihood` function in the console and then run your other code from the editor?

**Comment by manethedane** [comment]
Hi, no I defined my function in the editor and ran the other code from the
console. That's what I've always been doing with other files and it's never
been a problem.
Thanks for the quick response.

**Comment by ccordoba12** [comment]
Ok, thanks for clarification. Could you upload a screenshot to see how you're running your code?

Please be aware that you can't send images via email. Instead, you need to drag and drop them directly here, on the Github website.

**Comment by ccordoba12** [comment]
Thanks @manethedane! Although it's not visible, I think you the first command you ran in the console was

```python
import numpy as np
```

If that was the case, then it means you didn't run the code you have in the editor before trying to call `gaussian_likelihood` in the console. And that's why you're getting this error.

So, all you need to do before running

```python
x = np.array([1,2,4,0]) 
gaussian_likelihood(0.34,np.var(x),x)
```

is pressing `F5` or clicking on the Run button in our main toolbar (i.e. the green play button). That will load your editor code in the console so you can experiment with it there.

Let us know if that solves the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
