### ISSUE TITLE
Please help me?

### ISSUE THREAD

**Issue by garawaa** [spyder-ide/spyder#21985]
Hello brothers!
I'm trying to implement a custom json editor for my pyside6 app using pyside6's codeeditor example: https://doc-snapshots.qt.io/qtforpython-6.2/examples/example_widgets__codeeditor.html. But I can't add code folding column right of number column. I just wanted to add code folding for brace pairs. I am beginer in pyside6 so it seems difficult for me.

**Comment by ccordoba12** [comment]
Hey @garawaa, thanks for reporting. This is a place to report errors about Spyder, not to ask help about PySide, sorry.

For that we recommend you to post your question in StackOverflow:

https://stackoverflow.com/
