### ISSUE TITLE
Histogram plots with log scale not being properly displayed for inline plotting

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [spyder-ide/spyder#21992]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When using matplotlib.pyplot.hist function, the histogram bars are not contained within the axes if using inline plotting and log scale, while it is when using automatic plotting (not inline). It occurs no matter which axis you put with log scale (x or y).
I realised this using version 5.5.1 (although I remember seeing it with a previous version, but I cannot remember which one). I updated to 5.5.4 and the problem is still there.

### What steps reproduce the problem?

1. Execute this simple code snippet, with inline plotting mode
```
import matplotlib.pyplot as plt
import numpy as np

plt.hist(np.random.randint(0, 10, 100))
plt.yscale('log')
```
 

### What is the expected output? What do you see instead?
What we could expect (which occurs when not inline plotting is used):
![image](https://github.com/spyder-ide/spyder/assets/64196642/0d923215-9cfc-48dd-82ff-c676f519eaa9)

What occurs:
![image](https://github.com/spyder-ide/spyder/assets/64196642/b9ffa8a2-d049-4f11-a978-ac8b7224be31)

I fixed the seed so you can see that the data within the axis is well plotted, but it "overflows" outside of the axis

## Versions

* Spyder version: 5.5.4  (conda)
* Python version: 3.10.13 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Linux-6.5.0-26-generic-x86_64-with-glibc2.35

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                 :  1.4.1 (OK)
chardet >=2.0.0                      :  5.2.0 (OK)
cloudpickle >=0.5.0                  :  3.0.0 (OK)
cookiecutter >=1.6.0                 :  2.5.0 (OK)
diff_match_patch >=20181111          :  20230430 (OK)
intervaltree >=3.0.2                 :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1     :  8.21.0 (OK)
jedi >=0.17.2,<0.20.0                :  0.19.1 (OK)
jellyfish >=0.7                      :  1.0.1 (OK)
jsonschema >=3.2.0                   :  4.21.1 (OK)
keyring >=17.0.0                     :  24.3.0 (OK)
nbconvert >=4.0                      :  7.16.0 (OK)
numpydoc >=0.6.0                     :  1.6.0 (OK)
parso >=0.7.0,<0.9.0                 :  0.8.3 (OK)
pexpect >=4.4.0                      :  4.9.0 (OK)
pickleshare >=0.4                    :  0.7.5 (OK)
psutil >=5.3                         :  5.9.0 (OK)
pygments >=2.0                       :  2.17.2 (OK)
pylint >=3.1,<4                      :  3.1.0 (OK)
pylint_venv >=3.0.2                  :  3.0.3 (OK)
pyls_spyder >=0.4.0                  :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0               :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0           :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0            :  3.2.3 (OK)
qstylizer >=0.2.2                    :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0             :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0             :  5.5.1 (OK)
qtpy >=2.1.0                         :  2.4.1 (OK)
rtree >=0.9.7                        :  1.2.0 (OK)
setuptools >=49.6.0                  :  68.2.2 (OK)
sphinx >=0.6.6                       :  7.2.6 (OK)
spyder_kernels >=2.5.1,<2.6.0        :  2.5.1 (OK)
textdistance >=4.2.0                 :  4.5.0 (OK)
three_merge >=0.1.1                  :  0.1.1 (OK)
watchdog >=0.10.3                    :  4.0.0 (OK)
xdg >=0.26                           :  0.28 (OK)
zmq >=24.0.0                         :  25.1.2 (OK)

# Optional:
cython >=0.21                        :  None (NOK)
matplotlib >=3.0.0                   :  3.8.0 (OK)
numpy >=1.7                          :  1.26.3 (OK)
pandas >=1.1.1                       :  2.1.4 (OK)
scipy >=0.17.0                       :  1.11.4 (OK)
sympy >=0.7.3                        :  None (NOK)

# Spyder plugins:
spyder_notebook.notebookplugin 0.5.1 :  0.5.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Miguel-LlamasLanza, thanks for reporting. Quick question for you: are you using the SVG format of inline figures?

**Comment by Miguel-LlamasLanza** [comment]
Yes. I see that by using the PNG format, this issue does not appear.
Also (with SVG format) the same issue appears when using xlim and ylim commands of matplotlib, which is probably related.

**Comment by ccordoba12** [comment]
I thought so. The problem is that we're using the SVG from Qt (the graphical toolkit on which Spyder is built) to render Matplotlib SVG plots. And Qt doesn't support the full SVG spec, only a subset of it.

We discovered that a long time ago (see issue #9987) but haven't had time to fix it. For now, please switch to PNG and subscribe to that issue in case you want to know when it's fixed.
