### ISSUE TITLE
Cant start spyder

### ISSUE THREAD

**Issue by CDorian** [spyder-ide/spyder#2200]
I have just installed through Python(x,y) and can't even start spyder. It opens a console window then it quickly closes then does nothing else.

I am on Windows 8.1, 64bit..

**Comment by SylvainCorlay** [comment]
If you try starting spyder from the command line (first start `cmd` and then type `spyder`), the console window will not close and you should be able to give us a meaningful error message.

**Comment by CDorian** [comment]
I didnt get a chance to do that, but I uninstalled everything including all python installs and I reinstalled Python(x,y) and now it seems to work.

Thanks for getting back to me, Its all working now
