### ISSUE TITLE
Spyder calls discrete graphics on Windows

### ISSUE THREAD

**Issue by nitro122** [spyder-ide/spyder#22004]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder IDE randomly call DGPU. I cant open it without it calling the dedicated nividia card. 

## What steps reproduce the problem?

1. simply open spyder 

### What is the expected output? What do you see instead?
I would the spyder to not unnecessarily call the DGPU a

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 11

### Dependencies

```
PASTE DEPENDENCIES HERE
```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.20.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.2.2 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  25.1.2 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.8.0 (OK)
numpy >=1.7                                      :  1.26.4 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  1.11.4 (OK)
sympy >=0.7.3                                    :  1.12 (OK)

**Comment by ccordoba12** [comment]
Hey @nitro122, thanks for reporting. Please close Spyder, open the Anaconda Prompt and run there

   spyder --reset

and try again.

Let us know if that helps.

**Comment by nitro122** [comment]
hey @ccordoba12 , thankyou for your reply. I ran spyder --reset but unfortunately the issue still remains.

**Comment by ccordoba12** [comment]
Then I don't know what happens because our default option is to not use the GPU in our interface but software acceleration instead.

You can check that by going to the menu `Tools > Preferences` and then

    Application > Advanced settings > Rendering engine

**Comment by nitro122** [comment]
i checked it out. it says 'Desktop'. It call it at very random intervals. For instance when opening spyder the nvidia gpu indicator would light up and then switch off. This will playout until i close both spyder and anaconda. Hence believe it might be a bug
![SAVE_20240420_093120](https://github.com/spyder-ide/spyder/assets/167356796/6bf044a7-ed0b-4aa6-91fc-4a8f53be3c6f)

**Comment by nitro122** [comment]
hey @ccordoba12 , I changed it to 'software'. But the indicator still turns on and off at random intervals when Spyder is open . Could it be a bug? Or are there any other settings I should change.

**Comment by ccordoba12** [comment]
You need to restart Spyder doing it. Did you do that?

**Comment by nitro122** [comment]
Yes, it did prompt me to restart Spyder.

**Comment by ccordoba12** [comment]
Sorry, then I'd say this is not a Spyder problem. Sure, when you open Spyder the GPU is enabled, but Spyder depends on about 100 libraries (between direct and indirect dependencies), so any of them could be enabling it.

Sorry but for now I'm going to close this issue because I don't have additional feedback to give you. But if you gather more info about this, please post it here and I'll reopen it to continue the discussion.

**Comment by hippie68** [comment]
What does "Desktop" mean in this context? It is not self-explanatory to the average user.

**Comment by nitro122** [comment]
> Sorry, then I'd say this is not a Spyder problem. Sure, when you open Spyder the GPU is enabled, but Spyder depends on about 100 libraries (between direct and indirect dependencies), so any of them could be enabling it.
> 
> Sorry but for now I'm going to close this issue because I don't have additional feedback to give you. But if you gather more info about this, please post it here and I'll reopen it to continue the discussion.

Hi @ccordoba12 ,
Thank you very much. I got it working

**Comment by ccordoba12** [comment]
@hippie68, that's the terminology used by Qt. You can read more about it [here](https://doc.qt.io/qt-5/windows-requirements.html).

@nitro122, that's great! How did you manage to fix it?

**Comment by nitro122** [comment]
> @hippie68, that's the terminology used by Qt. You can read more about it [here](https://doc.qt.io/qt-5/windows-requirements.html).
> 
> @nitro122, that's great! How did you manage to fix it?

I installed the Standalone Spyder.
