### ISSUE TITLE
Suggestion: option to select interpreter when opening new console

### ISSUE THREAD

**Issue by Miguel-LlamasLanza** [spyder-ide/spyder#22020]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice

## Problem Description (Suggestion)

In order to open a kernel that uses a different python interpreter (e.g. a different conda environment), we need to go to preferences, change the python interpreter from the default one to another one. Then we can open a new python console with this interpreter for the kernel. We then need to switch back to the default interpreter in the preferences, so that new consoles will be opened with the default interpreter.

I suggest to have an option (in the menu that appears by clicking on the three lines of the top right of the console)  to open a new console with a specific interpreter instead of the default, to avoid doing all that was mentioned before. 

**Ideally**, it would be nice to have an option to choose between available conda environments, but I understand this might be quite difficult to ensure for each type of installation. Also ideally, the name of the console could tell to which environment it corresponds.

**Comment by pyZerrenner** [comment]
There seems to be a PR #20421 that implements a menu to start a console with a specific interpreter, but apparently it did not make its way to the main release yet.

(Also I just made my own similar suggestion #22022, not realising that this new issue was posted.)

**Comment by endolith** [comment]
Can conda environment be incorporated into the "Configuration per file" dialog?  So you can say which environment a particular file should be run in, and then it always is?

![image](https://github.com/spyder-ide/spyder/assets/58611/384c80cd-d91b-41f1-be9e-fd788802505d)

**Comment by dalthviz** [comment]
Hi there, sorry for the late response! Just in case, indeed PR #20421 kind of solves this issue. That work and some improvements to it that have been done/are being done like https://github.com/spyder-ide/spyder/pull/22200 will be part of Spyder 6. If you want to check the funtionality done at #20421 you can install the latest Spyder 6 beta release (see the Spyder GitHub release page at https://github.com/spyder-ide/spyder/releases?q=pre-release&expanded=true)

**Comment by dalthviz** [comment]
> Can conda environment be incorporated into the "Configuration per file" dialog? So you can say which environment a particular file should be run in, and then it always is?

I would say that idea is more closely related with #22022 (quite an interesting idea though :))

**Comment by dalthviz** [comment]
@ccordoba12 should we close this as solved by #20421 or maybe use #22200 to close this?

**Comment by Miguel-LlamasLanza** [comment]
Hi, thank you for your answers. I have not had the time to update and test
the new feature mentioned in the issue and PR that you linked. But the
solution given seems to address my request, so this issue can probably be
closed if it's released already.
Thank you.
Miguel

**Comment by dalthviz** [comment]
Closing as solved by https://github.com/spyder-ide/spyder/pull/20421 and https://github.com/spyder-ide/spyder/pull/22200

**Comment by endolith** [comment]
> > Can conda environment be incorporated into the "Configuration per file" dialog? So you can say which environment a particular file should be run in, and then it always is?
> 
> I would say that idea is more closely related with #22022 (quite an interesting idea though :))

Should I file a separate feature request now that the environment stuff has been implemented?

**Comment by ccordoba12** [comment]
@endolith, do you think issue #22022 doesn't cover your request?

**Comment by endolith** [comment]
> @endolith, do you think issue #22022 doesn't cover your request?

Sorry yes, that sounds like the same thing
