### ISSUE TITLE
Cannot install spyder 6.0.0a5 on Ubuntu 23.10 on raspberry pi

### ISSUE THREAD

**Issue by Chuck321123** [spyder-ide/spyder#22031]
## Problem Description
So i tried installing the newest version of spyder with both pip and conda without any luck on both.
This is what i get when installing with conda:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - spyder=6.0.0a5

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-aarch64
  - https://conda.anaconda.org/conda-forge/noarch

```

* Spyder version: 6.0.0a5
* Python version: 3.12.1
* Qt version: 
* PyQt version: 
* Operating System name/version: Ubuntu 23.10 - Raspberry pi

**Comment by ccordoba12** [comment]
Hey @Chuck321123, thanks for reporting. Unfortunately, our alphas are not available in any platform for Python 3.12 (when we started to release them we didn't have support for 3.12 and now it's not easy to change that).

But you can easily test it on your Raspberry Pi if you create an env with Python 3.11.
