### ISSUE TITLE
Windows: something is preventing "File" and "Edit" menus being clicked

### ISSUE THREAD

**Issue by cjrh** [spyder-ide/spyder#2204]
See this screencast:

![spyder-menu-bug](https://cloud.githubusercontent.com/assets/480395/6382695/94666c0e-bd96-11e4-8dc1-94d9d8166e8a.gif)

When hovering over the File and Edit menu items (and the left half of the Search menu item), the item does not raise, and clicking on it doesn't open the menu. However, once opening the menu items further to the right, by hovering over left the File and Edit menus also open.

This kind of problem is described [here](http://qt-project.org/forums/viewthread/9043/) and is apparently due to some widget being parented by MainWindow incorrectly.  I have not yet found which widget is causing this.

**Comment by blink1073** [comment]
@cjrh, are you using any third party plugins?

**Comment by cjrh** [comment]
Nope, this is raw HEAD.

**Comment by cjrh** [comment]
It would be good to know whether this happens on another Windows machine or not.  Apparently (according to the link I posted) Mac and linux are unaffected by the parenting issue.

**Comment by cjrh** [comment]
I checked Spyder 2.3.2: this **does not occur**. So it is def introduced recently as I suspected.

**Comment by ccordoba12** [comment]
It's probably a problem with our new use of signals and slots. Are you using PySide or PyQt4?

**Comment by cjrh** [comment]
Both. I'm working though the history on master now.  I'll find the commit eventually.

**Comment by cjrh** [comment]
The problem first occurs in the master branch in 29c927df7d96a8fd3d891e4bb7011894cd414010

**Comment by blink1073** [comment]
I'd guess `self.tour = tour.AnimatedTour(self)` is the offending [line](https://github.com/spyder-ide/spyder/commit/29c927df7d96a8fd3d891e4bb7011894cd414010#diff-e13742a2ff2d16fb2f96574ff7b24a5cR919).

**Comment by cjrh** [comment]
In `tour.py` if we change this:

```python
class AnimatedTour(QWidget):
    """ """

    def __init__(self, parent):
        QWidget.__init__(self, parent)

        self.parent = parent

```
to this
```python
class AnimatedTour(QWidget):
    """ """

    def __init__(self, parent):
        QWidget.__init__(self, None)

        self.parent = parent

```
The menu problem is resolved.  We can't just pass in `None`, because the mainwindow (parent) *is still required* inside `AnimatedTour` further down for some signal stuff.

**Comment by blink1073** [comment]
Shouldn't the tour be a Dialog or a Dock?

**Comment by cjrh** [comment]
I don't know Qt well enough to comment on that.

**Comment by blink1073** [comment]
That was more of a question for Carlos  :smile:

**Comment by blink1073** [comment]
Oh and I do see this behaviour on Linux.

**Comment by cjrh** [comment]
Ok interesting.   Good to know.  I was too lazy to check 😴

**Comment by goanpeca** [comment]
Oops, this one is on me. I will try to get this fixed.

**Comment by goanpeca** [comment]
@cjrh can you add this to the `def __init__ ` of the `AnimatedTour` class?

I just want to check that it works in windows before making the PR

`self.setAttribute(Qt.WA_TransparentForMouseEvents)`

**Comment by cjrh** [comment]
That works 👍

**Comment by goanpeca** [comment]
Cool thanks for checking, will make the PR

**Comment by goanpeca** [comment]
@ccordoba12 should the tour (lets call it widget) be a dockwidget/plugin? I guess the idea of having a plugin is to set some preferences for it. Any preference that we would want to set in the tours that you can think of?

**Comment by ccordoba12** [comment]
@goanpeca I can't think of any preferences right now. Let's leave it as widget until someone asks for Preferences :-)

**Comment by goanpeca** [comment]
Ok
