### ISSUE TITLE
Gráfico 

### ISSUE THREAD

**Issue by Nilzonherrera12** [spyder-ide/spyder#22062]
Perfecto. Calcularemos el valor futuro para cada trimestre y luego graficaremos esos valores. Aquí está el código para hacerlo:

```python
import matplotlib.pyplot as plt

# Datos
P = 2400  # Cuotas trimestrales
PV = 10000  # Pago inicial
TEM = 0.035  # Tasa efectiva mensual
n = 18  # 18 pagos trimestrales en 4 años y medio

# Cálculo de la tasa de interés periódica
i = (1 + TEM)**(1/3) - 1

# Función para calcular el valor futuro en cada trimestre
def calcular_valor_futuro(trimestre):
    return P * (((1 + i)**trimestre - 1) / i) + PV * (1 + i)**trimestre

# Calcular el valor futuro para cada trimestre
trimestres = range(1, n + 1)
valores_futuros = [calcular_valor_futuro(trimestre) for trimestre in trimestres]

# Graficar
plt.figure(figsize=(10, 6))
plt.plot(trimestres, valores_futuros, marker='o', linestyle='-')
plt.title('Evolución del valor futuro de la propiedad')
plt.xlabel('Trimestre')
plt.ylabel('Valor Futuro ($)')
plt.grid(True)
plt.show()
```

Este código calculará el valor futuro de la propiedad para cada trimestre y luego graficará cómo varía este valor a lo largo del tiempo. ¿Te gustaría ver el gráfico?

**Comment by ccordoba12** [comment]
Hola @Nilzonherrera12, este issue parece que no tiene que ver con Spyder. Y este sitio web está diseñado para reportar problemas sobre el mismo.

Por tanto, Si el código que colocaste arriba genera algún error en Spyder, por favor dejánoslo saber para poder arreglarlo. De lo contrario, tendremos que cerrar este issue.

**Comment by ccordoba12** [comment]
Voy a cerrar este issue dado que no obtuve respuesta a mi comentario anterior.
