### ISSUE TITLE
Debugging keyboard shortcuts in Spyder 6 editor

### ISSUE THREAD

**Issue by nassimbnm** [spyder-ide/spyder#22069]
## Problem Description

When debugging in Spyder 6 pre-release, keyboard shortcuts to debug like continue and step are not working in the editor, since their buttons were moved into the Debugging Pane.

Debug keyboard shortcuts do work when the Debugging Pane has focus, but once executed the editor pane receives the focus back, so the user has to click back and forth between debugging and editing which is not convenient.

Similarly, it is very useful to debug in the IPython Console pane while using the keyboard shortcuts, but it has the same issue.

If this issue could be fixed before the official release of Spyder 6 would be great and very appreciated.

**Comment by nassimbnm** [comment]
Solved in 6.0.0b3

**Comment by ccordoba12** [comment]
Hey @nassimbnm, thanks for opening this issue and sorry for replying until now (it slipped off our radar). Thanks also for letting us know that the Debugger shortcuts are working as expected again.
