### ISSUE TITLE
Spyder's WM_CLASS is empty, resulting in unexpected behavior for task managers

### ISSUE THREAD

**Issue by rubenvb** [spyder-ide/spyder#2207]
I experience unwanted behavior from KDE's icon-only task manager, which groups the Spyder window with Mathematica for some reason. There is definitely a bug on their end, but the fact that WM_CLASS for the Spyder window is empty is also not good and giving this property a decent value may very well work around the issue.

Link to KDE bug report containing more information: https://bugs.kde.org/show_bug.cgi?id=344515

**Comment by eikehein** [comment]
I'm the upstream KDE developer who's handling the above ticket. It looks like WM_CLASS winds up empty when Spyder is run against Python 3; the Python 2-powered Fedora package puts "Spyder" and is fine. Current GitHub against Python 3.4: Not so.

**Comment by rubenvb** [comment]
For Arch packages at least, both Spyder under Python 2.7 and 3.4 have empty WM_CLASS. It seems Fedora fixes it in their package.

**Comment by eikehein** [comment]
There's no relevant patch in their package tree at least: http://pkgs.fedoraproject.org/cgit/spyder.git/tree/

But this is a pretty complex matrix of Spyder version, Python version, PyQt version and Qt version. E.g. regardless of whether Spyder is running against Python 2 or 3, it could be using either PyQt 4 or 5 to use Qt 4 or 5 - so the bug could also be in PyQt, or, albeit unlikely, even in Qt.

I don't have enough time to dig that deep though so at that point it's more efficient to hand this off to you Spyder folks :).

**Comment by ccordoba12** [comment]
Ok, no problem. What do we need to do to set WM_CLASS?

**Comment by eikehein** [comment]
Qt should fill it in for you for the app's main window from the QApplication metadata. Can you look into whether you have forking codepaths in Spyder somewhere where something like setApplicationName (or similar) might wind up forgotten, or the window is created differently, ...?

**Comment by ccordoba12** [comment]
We are not using setApplicationName when creating the window, so that should be the cause of this problem ;-) I'll fix it for our next bugfix release.

**Comment by eikehein** [comment]
Thanks! If you mention the commit in this ticket I'll test on this end.

**Comment by ccordoba12** [comment]
Sure, I'll do that!

**Comment by ccordoba12** [comment]
@eikehein I used `xprop` to verify that our WM_CLASS is set correctly now. Please test it yourself to see if everything is right :-)

**Comment by eikehein** [comment]
Tested (sorry for the long wait), looks fine now!

**Comment by ccordoba12** [comment]
Great!!
