### ISSUE TITLE
request: smaller debugger

### ISSUE THREAD

**Issue by Galedon1** [spyder-ide/spyder#22090]
Right now the debugger is pretty big - even in its smallest form it takes about 1/3 of the window height and about 1/5 of its width (for my monitor). 
However sometimes I only want that 5 buttons to jump through breakpoints and watch variable explorer and console - these 2 panes usability lowers significantly due to the size of the debugger. I would love to put it for example below the project explorer but it is so wide that it destroys my layout, or just between the variable explorer and the console but only as a small toolbar, not the big window. 

## Versions
* Spyder version: 6.0.0a5  (pip)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

Windows version is being read incorrectly - its Windows 11 Pro, version 10.0.22631

### Dependencies
```
# Mandatory:
atomicwrites >=1.2.0              :  1.4.1 (OK)
chardet >=2.0.0                   :  5.1.0 (OK)
cloudpickle >=0.5.0               :  2.2.1 (OK)
cookiecutter >=1.6.0              :  2.1.1 (OK)
diff_match_patch >=20181111       :  20230430 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1  :  8.13.2 (OK)
jedi >=0.17.2,<0.20.0             :  0.18.2 (OK)
jellyfish >=0.7                   :  0.11.2 (OK)
jsonschema >=3.2.0                :  4.21.1 (OK)
keyring >=17.0.0                  :  23.13.1 (OK)
nbconvert >=4.0                   :  7.4.0 (OK)
numpydoc >=0.6.0                  :  1.5.0 (OK)
paramiko >=2.4.0                  :  3.2.0 (OK)
parso >=0.7.0,<0.9.0              :  0.8.3 (OK)
pexpect >=4.4.0                   :  4.8.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.9.5 (OK)
pygments >=2.0                    :  2.15.1 (OK)
pylint >=3.1,<4                   :  3.2.0 (OK)
pylint_venv >=3.0.2               :  3.0.2 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0            :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0        :  2.0.0 (OK)
pyuca >=1.2                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0         :  3.2.3 (OK)
qstylizer >=0.2.2                 :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0          :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0          :  5.5.1 (OK)
qtpy >=2.4.0                      :  2.4.1 (OK)
rtree >=0.9.7                     :  1.0.1 (OK)
setuptools >=49.6.0               :  65.5.0 (OK)
sphinx >=0.6.6                    :  7.0.1 (OK)
spyder_kernels >=3.0.0b5,<3.0.0b6 :  3.0.0b5 (OK)
superqt >=0.6.1,<1.0.0            :  0.6.1 (OK)
textdistance >=4.2.0              :  4.5.0 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  3.0.0 (OK)
zmq >=24.0.0                      :  25.1.0 (OK)

# Optional:
cython >=0.21                     :  0.29.35 (OK)
matplotlib >=3.0.0                :  3.7.3 (OK)
numpy >=1.7                       :  1.24.3 (OK)
pandas >=1.1.1                    :  2.0.2 (OK)
scipy >=0.17.0                    :  1.10.1 (OK)
sympy >=0.7.3                     :  1.12 (OK)

```

**Comment by ccordoba12** [comment]
Hey @Galedon1, thanks for reporting and your feedback on our new Debugger pane.

Quick question for you: would you prefer to see the previous debugger toolbar (i.e. the one in Spyder 5 next to the run buttons) to control the debugger?

**Comment by Leohanhart** [comment]
FYI: I think the Debugger is perfectly fine, I use it at least 700X a week and I see no problem at all. I think this guy should a just his screen or buy a bigger one. 

I even have no clue where this dude is talking about. Can he Load up a picture so he can show what he ment? The debugger is 3% of the screen right? 
![image](https://github.com/spyder-ide/spyder/assets/23247070/d098fa5f-95f4-4e7f-aa3b-466570693dd6)

**Comment by ccordoba12** [comment]
@Leohanhart, @Galedon1 is using Spyder 6.0 alpha5 (as can be seen in the attached information to the original post). And in that version we removed most debugger buttons from our main toolbar and moved them to a new debugger pane:

![imagen](https://github.com/spyder-ide/spyder/assets/365293/f74be3f4-092e-4de9-a7c0-4926f75ff98c)

But since you're heavier user of our debugger, I'd like to ask you what you think about that design.

**Comment by Galedon1** [comment]
Thank you for quick answer. It would be nice to have an opportunity to toggle the old debug buttons in the toolbar, but the smaller debug pane will do the job as well. 
@Leohanhart just to explain the layout, this is the minimal size of the debugger:
![obrázek_2024-05-20_074020319](https://github.com/spyder-ide/spyder/assets/115783433/1acdb7b8-f008-418e-897f-ba2f962f7ea9)

**Comment by ccordoba12** [comment]
Thanks @Galedon1 for the visual explanation. What happens if you hide the breakpoints panel? Does that fix the problem for you?

**Comment by ccordoba12** [comment]
This should be fixed now in beta2 because the debugger doesn't have a min width now.
