### ISSUE TITLE
Spyder for Linux is missing the "minimize" button in the dataframe viewer tab

### ISSUE THREAD

**Issue by Chuck321123** [spyder-ide/spyder#22099]
## Problem Description
So, the Spyder UI in Linux seem to be a bit different compared to the UI on Windows. For example, the "minimize" and "fullscreen" options are missing in the dataframe viewer. Would be nice to add these buttons to linux as well.

### What steps reproduce the problem?
Open up a dataframe

### What is the expected output?
That i see the minimize button, as well as the fullscreen button next to "X".

## Versions

* Spyder version: 5.5.4
* Python version: 3.12.1
* Qt version: 5.15.8
* PyQt version: 5.15.9
* Operating System name/version: Linux 6.5.0-1015-raspi (aarch64)

**Comment by bessman** [comment]
The presence of the window minimize button is controlled by your window manager, not individual applications.

**Comment by ccordoba12** [comment]
Yep, I was about to say that. I also use Linux (specifically KDE) and there I can see the minimize button on the dataframe viewer:

![imagen](https://github.com/spyder-ide/spyder/assets/365293/33b07b1f-fee0-45b3-b066-97e065e1f61a)

@Chuck321123, the solution is for you to install and use a different window manager (perhaps you're using one that is too minimalistic).

**Comment by ccordoba12** [comment]
I'm going to close this issue because it's really not related to Spyder.
