### ISSUE TITLE
Icons as vector graphics to support retina displays

### ISSUE THREAD

**Issue by wigging** [spyder-ide/spyder#2210]
Is it possible to replace the toolbar icons and other icons in Spyder with vector graphics?  This would allow the icons to be independent of screen resolution.  Such icons would look great on high resolution displays as well as standard displays.  The current icons are png which do not scale with screen resolution so they don't look good on high-res screens found on the iMac and MacBook Pro.  I can provide new icons in SVG, EPS and PDF formats if the gui in Spyder supports these file types.

**Comment by ccordoba12** [comment]
Pinging @goanpeca because he is very interested on this

**Comment by goanpeca** [comment]
True, I am very interested in this :), in theory Qt supports svg BUT depending on the distribution used, compiled versions might not support SVG (I think anaconda has some issues on this area)

@SylvainCorlay you were looking at font awesome... what happened with that?

@wigging you had already made some progress on this area? there was some work started in #950

any ideas plans suggestions we can start from?

Cheers

**Comment by SylvainCorlay** [comment]
@goanpeca , yes I started playing with this. 

My plan for a PR was to create a new theme where I would
- only use bitmaps, for the reasons you explained earlier.
- mostly generate these bitmaps from font-awesome (and font-mfizz for things like the python language logo.)
- and follow the rule of having only monochromatic icons (no shadow, or gradient etc...)
As some people will want to keep the old theme because they like it, we could keep it around. 

Implementation-wise, I would rather use the font-awesome icon names even for the old scheme icons which I would rename. I found it was more convenient when I started coding.

**Comment by wigging** [comment]
I would like to emphasize the use of vector graphics so the icons will look sharp on high resolution monitors.  If you use Spyder on these displays, the icons look fuzzy and unprofessional.  You can provide new icons as bitmaps, but you're still going to have the issues I mentioned earlier.  I'm more familiar with designing iOS and Mac apps, where if you don't use vector assets then you can provide a png image in different sizes to support retina displays.  For example, an image name icon.png (32x32 px) would also be provided at 2x resolution as icon@2x.png.  Depending on the screen, the gui will choose the 2x or the 1x version.  If you can't use vector icons in Spyder, can PyQt use low resolution images for standard displays while using a higher resolution image for newer displays?

**Comment by SylvainCorlay** [comment]
Actually, by using the font-awesome font itself, we could get around the limitation of qt with vector graphics. 

I just came across https://github.com/gamecreature/QtAwesome/blob/master/QtAwesome/QtAwesome.h. 

We could use this as an inspiration.

**Comment by goanpeca** [comment]
Hey this is pretty cool, and would be just as easy to port to PyQt... :) :+1:

**Comment by ccordoba12** [comment]
Yes!! and it's also MIT licensed, so we won't have problems with that too :-)

**Comment by goanpeca** [comment]
OK will do the port next week

**Comment by wigging** [comment]
I agree with @SylvainCorlay with the Font Awesome approach.  It would look great on retina screens.  I've used it for websites with no issues.  The only problem is when you need a custom icon that isn't available on Font Awesome.  For that, you can use IcoMoon https://icomoon.io to import your own vectors to make a custom font.

**Comment by SylvainCorlay** [comment]
@goanpeca I already started playing with it. Although it is likely I will not complete the whole thing this week. Let me know what you prefer.

**Comment by goanpeca** [comment]
Well if you already started then maybe you should continue and finish :), I have not looked at it yet ;), I was planning on making it a module and uploading it to PyPi

**Comment by SylvainCorlay** [comment]
@wigging, you can already take a look at https://github.com/spyder-ide/pyqtawesome (and the provided example), it enables any font-based icon set, and currently embeds [Font Awesome](http://fortawesome.github.io/Font-Awesome/) and [Elusive Icons](http://elusiveicons.com/). It is very easy to dynamically load other iconic fonts, hence I will probably create a custom font with spyder-specific things.

**Comment by wigging** [comment]
@SylvainCorlay Can you provide instructions in the PyQtAwesome README on how to run the example?  I'm not familiar with PyQt, most of my Python work deals with numerical computations and data analysis.

**Comment by goanpeca** [comment]
@wigging, you just need to open the example from wthin Spyder and run it. Assuming you have installed Qt4, then it should display a QWidget with some buttons already using the icons.

**Comment by flying-sheep** [comment]
hey guys, you’ve missed something. there already is a standard mechanism for icons in Qt.

i describe the advantages in #2230.

it should be easy to use the SVG version of the fontawesome icons as freedesktop-style icon theme (aka give them certain names and throw them into a directory), bundle them in the QResource folder `':/icons'`, and be done.

**Comment by ccordoba12** [comment]
This was fixed by PR #2260

**Comment by flying-sheep** [comment]
Why is breeze not there? It’s honestly the best and most complete symbolic icon set.

**Comment by ccordoba12** [comment]
Because it's GPL so we can't distribute with Spyder. We'd need to create a separate package to distribute it and we don't have time for that, sorry.

**Comment by flying-sheep** [comment]
“Not there” refered to “inkscape-open-symbols”, not spyder.

**Comment by ccordoba12** [comment]
Ok, sorry, I misread your comment.

**Comment by SylvainCorlay** [comment]
Fonts for icons have some advantages over SVGs.

- They are built with less vector primitives than svgs and type renderers tend to be super good at rendering them fast.
- They tend to be designed for pixel perfection at small sizes, which is good for low-resolution screens and dense UIs such as IDEs.
- They are popular on the web for good and historical reasons and using font-awesome in spyder gives spyder a more similar feel to e.g. jupyter.

**Comment by PanderMusubi** [comment]
Thanks @flying-sheep, I +1'ed your proposal.

On icon fonts, most of these icon fonts also offer their icon set as a font files.

Another one worth mentioning is https://materialdesignicons.com/

**Comment by ccordoba12** [comment]
And with the latest version of QtAwesome, Spyder has access to all Material Design icons (which are 3000+), so I don't think we're going to consider other icon sets in the near future.
