### ISSUE TITLE
Scaling Issues at higher resolutions

### ISSUE THREAD

**Issue by Fusion-Tech-05** [spyder-ide/spyder#22101]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When running spyder, everything does not scale correctly to my higher resolution screen causing issues where the icons are very small and are sometimes overlapping each other, text often overlaps other text and is cammed very close towards other text and images will be overlapped or overlap other elements.

### What steps reproduce the problem?
How to reproduce.
 -- Run spider on a higher resolution screen such as a 4k screen. With default configuration these issues exist.

### What is the expected output? What do you see instead?
Intended Outcome versus Actual Outcome:
Intended:
 -- I intend for everything to look correct and not overlap each other or hide/obscure other elements of the text
Actual Outcome:
 -- Things are hidden, obscured, clumped too close together, or overlapping due to them not scaling to move out of the way of other 
     elements.

Versions:
Spyder: 5.4.3
Python: 3.11.7 64bit
PyQt5 Version: 5.15.10
Operating System name/Version: Windows 10

![image](https://github.com/spyder-ide/spyder/assets/87595770/da47e23d-2ed1-4b83-ad3a-c7d8eac52fad)

**Comment by dalthviz** [comment]
Hi @Fusion-Tech-05 thank you for the report! Could it be possible for you to update to the latest release (6.0.2 currently) and check again? To get the latest release you would need to install Spyder from the conda-forge channel or you could also use our installers (available over the Spyder repo GitHub release page: https://github.com/spyder-ide/spyder/releases/tag/v6.0.2).

Let us know if updating helps!

**Comment by Fusion-Tech-05** [comment]
Yeah, this appeared to fix all the issues I had with overlapping and odd scaling, thanks.

**Comment by Fusion-Tech-05** [comment]
Thanks for fixing this.

**Comment by Fusion-Tech-05** [comment]
The UI is a bit bigger than what I'm used too, but it is all working as expected.
