### ISSUE TITLE
Update to spyder=5.5.1

### ISSUE THREAD

**Issue by Saint-Julio** [spyder-ide/spyder#22122]
### What steps will reproduce the problem?

conda update anaconda
conda install spyder=5.5.1

## Versions

* Spyder version: 5.4.3  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                             :  1.4.0 (OK)
chardet >=2.0.0                                  :  4.0.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.5.0 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.1.0 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.20.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.1 (OK)
jellyfish >=0.7                                  :  1.0.1 (OK)
jsonschema >=3.2.0                               :  4.19.2 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.10.0 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
paramiko >=2.4.0                                 :  2.8.1 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.0 (OK)
pygments >=2.0                                   :  2.15.1 (OK)
pylint >=2.5.0,<3.0                              :  2.16.2 (OK)
pylint_venv >=2.1.1                              :  2.3.0 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.0.2 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.2 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.4.2 (OK)
qtpy >=2.1.0                                     :  2.4.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  68.2.2 (OK)
sphinx >=0.6.6                                   :  5.0.2 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.4.4 (OK)
textdistance >=4.2.0                             :  4.2.1 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  2.1.6 (OK)
zmq >=22.1.0                                     :  24.0.1 (OK)

# Optional:
cython >=0.21                                    :  None (NOK)
matplotlib >=3.0.0                               :  3.8.0 (OK)
numpy >=1.7                                      :  1.26.4 (OK)
pandas >=1.1.1                                   :  2.1.4 (OK)
scipy >=0.17.0                                   :  1.11.4 (OK)
sympy >=0.7.3                                    :  1.12 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Saint-Julio, thanks for reporting. Could you describe what's exactly your problem?

Are the commands you posted not working? Id so, what's the issue you're faced with?

**Comment by Saint-Julio** [comment]
Thanks, Carlos.

I was able to perform the update by trying
different ideas not provided in the video.

I have resolved the "Python update" issue.

Carlos, I have no Python experience other
than the class of "Python for Engineers"
and therefore, I have one question:

"How do you 'print' two parameters as
two separate columns to allow me to take
the output information as 2 columns into
Excel for plotting y versus x. For instance,
here are two temperatures columns data in
format ###.# where the symbol # stands
for "decimal place":

T_C          T_F
   0.0        32.0
100.0      212.0

I will guess that the Python code would look
as follows:
___

print()
print("T_C          T_F")
print.format(###.#      ###.#) T_C_Data,T_F_Data
print()

___

Carlos, the symbol "___" is three instances of the
single symbol "_" intended to indicate that it is a
blank line not intended to be part of the Python
statrements being sough as the "guessed response"
to my inquiry.

Carlos, I have experience in Fortran and Mathcad Prime
software which may serve you in the preparation of your
response this "Python print" commands inquiry. Also, I
have a Master of Science in Mechanical Engineering with
interest in thermo-structural analysis and desgn of turbo-
machineries.

Thanks,

Julio C. Banks, BSMET, MSME, PE
Solutions Consultant
"Doing Business by the Book"

Port Saint Lucie, Florida USA

e-mail: ***@***.******@***.***>

P Please consider the environment before printing this email.

"Education is a better safeguard of liberty than a standing army"
Edward Everett

________________________________


     From: Carlos Cordoba < ***@***.******@***.***> >
      Sent: Monday, May 27, 2024, 9:32 AM
         To: spyder-ide/spyder < ***@***.******@***.***> >
         Cc: Saint-Julio < ***@***.******@***.***> >; Mention < ***@***.******@***.***> >
Subject: [spyder-ide/spyder] Update to spyder=5.5.1 (Issue #22122)

Hey @Saint-Julio<https://github.com/Saint-Julio>, thanks for reporting.
Could you describe what's exactly your problem?
Are the commands you posted not working?
If so, what's the issue you're faced with?

-

**Comment by ccordoba12** [comment]
> I have resolved the "Python update" issue.

Ok, that's great!

> Carlos, I have no Python experience other
than the class of "Python for Engineers"
and therefore, I have one question:

I'd love to help you with that but, unfortunately, I'm very busy with other things, sorry.
