### ISSUE TITLE
Is there a dot app file for Spyder on Mac OS

### ISSUE THREAD

**Issue by ahmedshaaban1** [spyder-ide/spyder#22135]
## Problem Description

Do you have any idea if there is a .app file for Spyer? I installed Anaconda on Mac OS, and I did find Anaconda-Navigator.app, but I did not find .app for spyder or the other installed application. I just found binary files anaconda/bin/, and those binary files are not the .app files. Thanks

### What is the expected output? What do you see instead?

I expected to find Spyder.app, but I did not. 

* Spyder version:   5.4.3
* Python version:  3.11.4 64-bit
* Qt version:  5.15.2 
* PyQt version: 5 5.15.7
* Operating System name/version: Darwin 20.6.0

**Comment by ccordoba12** [comment]
Hey @ahmedshaaban1, thanks for reporting. At the moment there's no app directory (it's actually a directory, not a file) for Spyder when you install it with Anaconda.

However, I think it will be when Spyder 6 is available in a month or so.

**Comment by ahmedshaaban1** [comment]
This is a good news. Thanks.
