### ISSUE TITLE
Show absolute and relative (to the current file in Editor) images in Object inspector

### ISSUE THREAD

**Issue by nicoguaro** [spyder-ide/spyder#2213]
First, congratulations for the excellent job done with spyder.

The ``Object inspector`` is really useful when you want to see the documentation of some functions. It would be really useful if one can show images (as sphinx does) in it.

**Comment by ccordoba12** [comment]
@blink1073 I think you solved this one in one of the last PRs merged on Bitbucket, right?

**Comment by blink1073** [comment]
Yep, in this [PR](https://bitbucket.org/spyder-ide/spyderlib/pull-request/12/add-ability-to-re-trigger-docstring-while/diff) we added the ability to view images in the current directory.  I'm pretty sure absolute paths to images always worked.

**Comment by nicoguaro** [comment]
I just tried _absolute paths_ to images. It worked for images from internet but not locally, at least in Windows. I tried different ways of giving the absolute path... but didn't succeed.

```Python
def absolute_path_test():
    r"""Test for image rendering in Object inspector.
    
    Math rendering
    
    .. math::
            \sin\left(\frac{1}{x}\right)
     
    This is an image from internet

    .. image:: https://upload.wikimedia.org/wikipedia/commons/d/d2/Sine_one_period.svg 
    
    This is a local file
    
    .. image:: D:/lena512.png    

    """
```

**Comment by blink1073** [comment]
@nicoguaro, absolute paths must be URIs, in this case:  `file:///D:/lena512.png`.  See http://en.wikipedia.org/wiki/File_URI_scheme.

**Comment by nicoguaro** [comment]
@blink1073, it works, thanks!! I couldn't find that information in the documentation of Sphinx, though :-/.  I will be waiting for the option of relative paths then :).

**Comment by ccordoba12** [comment]
Ok, I think this is solved in master.
