### ISSUE TITLE
Spyder: An error ocurred while starting the kernel. Cannot run conda install spyder-kernels=2.4. 

### ISSUE THREAD

**Issue by ctravell** [spyder-ide/spyder#22138]
I set up a virtual environment with python 3.7.9 Spyder runs on 3.11 and I changed the interpreter to 3.7.9. I am using Anaconda3 The console in Spyder shows the following error message: "An error ocurred while starting the kernel You can install it by activating your environment first (if necessary) and then running in a system terminal: You can install it by activating your environment first (if necessary) and then running in a system terminal: conda install spyder-kernels=2.4"

I therefore activated my virtual environment in the Anaconda Prompt and entered conda install spyder-kernels=2.4.

However I get : "failed

UnsatisfiableError: The following specifications were found to be incompatible with the existing python installation in your environment:

Specifications:

spyder-kernels=2.4 -> python[version='>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.12,<3.13.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']
Your python: python=3.7.9

If python is on the left-most side of the chain, that's the version you've asked for. When python appears to the right, that indicates that the thing on the left is somehow not available for the python version you are constrained to. Note that conda will not change your python version to a different minor version unless you explicitly specify that."

I also tried running "conda install spyder-kernels=2.4" outside my virtual environment

Not sure what needs to be done from there. Help really appreciated.

**Comment by ccordoba12** [comment]
Hey @ctravell, thanks for reporting. You said:

> I set up a virtual environment with python 3.7.9 Spyder runs on 3.11 and I changed the interpreter to 3.7.9.

I think your best bet to have this setup working is by installing Spyder-kernels with pip. You can do that by closing Spyder, opening the Anaconda Prompt, activating your environment and running there the command

    pip install spyder-kernels==2.4.4

But, as you probably know, that will only work if you haven't installed other packages with conda in that env, because you can't mix pip and conda packages.

Let us know if that helps you to solve this problem.

**Comment by ctravell** [comment]
Thank you for your reply.
I created a new environment with "conda create --name Credit_process2 -c anaconda python=3.7.9" and then ran "pip install spyder-kernels==2.4.4".  This generated the error below. It looks like Spyder doesn't like this python version. Anaconda was originally installed with python 3.11 and Spyder runs on it. I thought Spyder could run an a different python version and process code with another python interpreter version. Looks like the Spyder kernel doesn't really like this. Just my guess as I quite new here. Really appreciate any further help/advice.

ERROR: Ignored the following versions that require a different python version: 3.0.0 Requires-Python >=3.8; 3.0.0b3 Requires-Python >=3.8; 3.0.0b4 Requires-Python >=3.8; 3.0.0b5 Requires-Python >=3.8; 3.0.0b6 Requires-Python >=3.8; 6.17.0 Requires-Python >=3.8; 6.17.1 Requires-Python >=3.8; 6.18.0 Requires-Python >=3.8; 6.18.1 Requires-Python >=3.8; 6.18.2 Requires-Python >=3.8; 6.18.3 Requires-Python >=3.8; 6.19.0 Requires-Python >=3.8; 6.19.1 Requires-Python >=3.8; 6.19.2 Requires-Python >=3.8; 6.19.3 Requires-Python >=3.8; 6.19.4 Requires-Python >=3.8; 6.20.0 Requires-Python >=3.8; 6.20.1 Requires-Python >=3.8; 6.20.2 Requires-Python >=3.8; 6.21.0 Requires-Python >=3.8; 6.21.1 Requires-Python >=3.8; 6.21.2 Requires-Python >=3.8; 6.21.3 Requires-Python >=3.8; 6.22.0 Requires-Python >=3.8; 6.23.0 Requires-Python >=3.8; 6.23.1 Requires-Python >=3.8; 6.23.2 Requires-Python >=3.8; 6.23.3 Requires-Python >=3.8; 6.24.0 Requires-Python >=3.8; 6.25.0 Requires-Python >=3.8; 6.25.1 Requires-Python >=3.8; 6.25.2 Requires-Python >=3.8; 6.26.0 Requires-Python >=3.8; 6.27.0 Requires-Python >=3.8; 6.27.1 Requires-Python >=3.8; 6.28.0 Requires-Python >=3.8; 6.29.0 Requires-Python >=3.8; 6.29.1 Requires-Python >=3.8; 6.29.2 Requires-Python >=3.8; 6.29.3 Requires-Python >=3.8; 6.29.4 Requires-Python >=3.8
ERROR: Could not find a version that satisfies the requirement ipykernel<7,>=6.23.2; python_version >= "3" (from spyder-kernels) (from versions: 4.0.1, 4.0.2, 4.0.3, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.2.2, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 4.5.2, 4.6.0, 4.6.1, 4.7.0, 4.8.0, 4.8.1, 4.8.2, 4.9.0, 4.10.0, 4.10.1, 5.0.0b1, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.2.0, 5.2.1, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.5.0, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 6.0.0a0, 6.0.0a1, 6.0.0a2, 6.0.0a3, 6.0.0a4, 6.0.0a5, 6.0.0a6, 6.0.0b0, 6.0.0rc0, 6.0.0rc1, 6.0.0rc2, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.1.0, 6.2.0, 6.3.0, 6.3.1, 6.4.0, 6.4.1, 6.4.2, 6.5.0, 6.5.1, 6.6.0, 6.6.1, 6.7.0, 6.8.0, 6.9.0, 6.9.1, 6.9.2, 6.10.0, 6.11.0, 6.12.0, 6.12.1, 6.13.0, 6.13.1, 6.14.0, 6.15.0, 6.15.1, 6.15.2, 6.15.3, 6.16.0, 6.16.1, 6.16.2)
ERROR: No matching distribution found for ipykernel<7,>=6.23.2; python_version >= "3"

**Comment by ccordoba12** [comment]
Ok, then please try running:

    pip install spyder-kernels==2.4.3

That should work.

**Comment by ctravell** [comment]
Thanks.  Your first solution of running pip in the environment actually worked with pip install spyder-kernels==2.4.*
Not sure why the * made the difference

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
