### ISSUE TITLE
in last version of Spyder, I faced with pyflakes E when import numpy or etc. libraries, how to fix it?

### ISSUE THREAD

**Issue by MRSS1979** [spyder-ide/spyder#22146]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @MRSS1979 sorry for the late response! I'm not totally sure if I'm understanding what you are experiencing could it be possible for you to share with us the info related with your setup (Spyder version, OS, packages information, etc). Also, maybe a look to the Spyder docs page related with linting and completions could be worthy: https://docs.spyder-ide.org/current/panes/editor.html#linting-and-code-style

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
