### ISSUE TITLE
Release 5.5.5

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#22158]
This is an issue to track pending changes and questions for the new Spyder 5.5.5 release.

* New/updated dependencies:
   * `spyder-kernels` >= 2.5.2,<2.6.0 (to get matplotlib 3.9.0 compatibility fix)

**Comment by ccordoba12** [comment]
I forgot that we need to release Spyder-kernels 2.5.2 for this. See https://github.com/conda-forge/spyder-kernels-feedstock/pull/104 about that (it should be available in Conda-forge in a couple of hours).
