### ISSUE TITLE
rope breaks object inspector?

### ISSUE THREAD

**Issue by masasin** [spyder-ide/spyder#2215]
After doing `sudo pip3 install rope_py3k`, the editor object inspector no longer shows any headings.

Without doing this, the editor object inspector simply does not work.

I am on Ubuntu 14.10, using Spyder 2.3.0 under Python 3.4.2 and IPython 3.

**Comment by ccordoba12** [comment]
Please update to Spyder 2.3.3. We fixed this problem a long time ago.
