### ISSUE TITLE
Cannot run Numpy 1.21.6 with Python 3.7.9 while documentation says it they are compatible

### ISSUE THREAD

**Issue by ctravell** [spyder-ide/spyder#22152]
I am running anaconda3 and created an environment with python 3.7.9.
When I run  "import numpy as np; print(np.__version__)" in Spyder I get the error below. However I see online that both versions should be compatible. 

Really appreciate some help as I am quite new here. Thanks in adance

import numpy as np
print(np.__version__)
Traceback (most recent call last):

  File "C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
    from . import multiarray

  File "C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides

  File "C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (

ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "C:\Users\ctravell\AppData\Local\Temp\ipykernel_3084\1924369680.py", line 1, in <module>
    import numpy as np

  File "C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\lib\site-packages\numpy\__init__.py", line 150, in <module>
    from . import core

  File "C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
    raise ImportError(msg)

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\python.exe"
  * The NumPy version is: "1.21.5"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed: The specified module could not be found.

The system cannot find the path specified.
C:\Users\ctravell\AppData\Local\anaconda3\envs\Credit_process2\lib\site-packages\numpy\__init__.py:148: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, see http://github.com/IntelPython/mkl-service
  from . import _distributor_init

**Comment by dalthviz** [comment]
Hi @ctravell !  Is this error happening only with Spyder or if you try to run the version check code from the Python interpreter it runs without issue?

Did a quick check and although numpy 1.21.6 has wheels for Python 3.7 I think the actual numpy version that supports Python 3.7 is more like numpy 1.18+ or 1.19+ For more details you can check the numpy NEP 29 deprecation policy: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
