### ISSUE TITLE
Warning message on the first console that is open

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#22181]
## Problem Description

A warning message appears on the first console that is launched when Spyder starts (at least on my Windows setup while checking the Spyder 6 beta2 rc0 installer - https://github.com/spyder-ide/spyder/actions/runs/9573557891):

![image](https://github.com/spyder-ide/spyder/assets/16781833/b1c2bfd0-1f0d-48a4-aabb-956a6d8a68de)

```
C:\Users\dalth\AppData\Local\spyder-6\envs\spyder-runtime\Lib\threading.py:1045: UserWarning: Parent poll failed.  If the frontend dies,
                the kernel may be left running.  Please let us know
                about your system (bitness, Python, etc.) at
                ipython-dev@scipy.org
  self.run()
```

### What steps reproduce the problem?

1. Launch Spyder 

### What is the expected output? What do you see instead?

Initial console launched when Spyder starts not showing any warning message

## Versions

* Spyder version: 6.0.0b2.dev174  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by dalthviz** [comment]
Note: Seems like this could be related with #8205 (also an still open issue was created at IPython https://github.com/ipython/ipython/issues/11727 +5 years ago) and the actual warning is still being generated over `ipykernel`: https://github.com/ipython/ipykernel/blob/d4a8703593cbe5d82bc955d68543dc623f5b4510/ipykernel/parentpoller.py#L113-L121

Seems like adding the warning text to the [`is_benign_error` method over Spyder](https://github.com/spyder-ide/spyder/blob/da6396b713eddf552288053fdf0f9bcf0cfe14db/spyder/plugins/ipythonconsole/widgets/client.py#L505-L537) is not enough to ignore the warning and instead either a check needs to be added over QtConsole at [the `_handle_stream` method from the `FrontendWidget` class](https://github.com/jupyter/qtconsole/blob/6d9a98657e6dfeae5d50ca08f8e3ea439a818dc8/qtconsole/frontend_widget.py#L570) or make the Spyder `ShellWidget` class reimplement that method so a check to ignore the warning a not show it can be added.

What do you think @ccordoba12 ?

**Comment by ccordoba12** [comment]
Is it possible to add some code to spyder-kernels to hide that warning?

If not, then I think the best solution is to override `_handle_stream` in `ShellWidget` until we have time to provide a fix upstream.

**Comment by dalthviz** [comment]
From a quick check maybe further customizing the outstream class could help?:

* https://github.com/spyder-ide/spyder-kernels/blob/67954aef9106fccd327f3c803f081076c4b8364b/spyder_kernels/console/start.py#L169-L170
* https://github.com/spyder-ide/spyder-kernels/blob/67954aef9106fccd327f3c803f081076c4b8364b/spyder_kernels/console/outstream.py

Particulary de `_flush` method (I think over there is where the stream message is formated and is being send): 
* https://github.com/ipython/ipykernel/blob/d4a8703593cbe5d82bc955d68543dc623f5b4510/ipykernel/iostream.py#L663

**Comment by ccordoba12** [comment]
Ok, sounds good to me.
