### ISSUE TITLE
Error "openseespy.opensees"

### ISSUE THREAD

**Issue by Karmugilan1997** [spyder-ide/spyder#22205]
### What steps will reproduce the problem?

I can't able to execute from openseespy.opensees import *
It showing No module named 'opensees' even after I installed through windows command prompt

## Versions

* Spyder version: 5.5.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.4 (OK)
jsonschema >=3.2.0            :  4.22.0 (OK)
keyring >=17.0.0              :  25.2.1 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.0 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.8 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.3 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0        :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.2.0 (OK)
setuptools >=49.6.0           :  70.0.0 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.2,<2.6.0 :  2.5.2 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.1 (OK)
zmq >=24.0.0                  :  26.0.3 (OK)

# Optional:
cython >=0.21                 :  3.0.10 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @Karmugilan1997, thanks for reporting. Please read our documentation about how to connect Spyder to external environments:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

That should help you to solve this problem, but let us know if it doesn't.

**Comment by Karmugilan1997** [comment]
Despite installing the required openseespy, I'm facing the same issue.

Please take a look at the attachment.

Could you help me to fix this?

![Screenshot 2024-06-29 215646](https://github.com/spyder-ide/spyder/assets/173756975/e9f4b0db-d95f-45ab-97c2-948bcf552f7d)
![Screenshot 2024-06-29 215016](https://github.com/spyder-ide/spyder/assets/173756975/4a2b3de6-9610-43c6-a157-aaf0b4586792)

**Comment by Karmugilan1997** [comment]
I'm hoping to hear back from you.

**Comment by ccordoba12** [comment]
@Karmugilan1997, please close Spyder and start it again. That should solve your problem.

**Comment by Karmugilan1997** [comment]
Yeah...I tried that, but I'm facing the same error again.

**Comment by Karmugilan1997** [comment]
I've included the output from Anaconda Prompt for you.....

# packages in environment at C:\Users\Karmugilan\.conda\envs\openseespy:
#
# Name                    Version                   Build  Channel
asttokens                 2.4.1                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
ca-certificates           2024.3.11            haa95532_0
cloudpickle               3.0.0                    pypi_0    pypi
colorama                  0.4.6            py39haa95532_0
comm                      0.2.2                    pypi_0    pypi
debugpy                   1.8.1                    pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0
exceptiongroup            1.2.1                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
importlib-metadata        7.2.1                    pypi_0    pypi
importlib_metadata        7.0.1                hd3eb1b0_0
ipykernel                 6.29.4                   pypi_0    pypi
ipython                   8.18.1                   pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jupyter-client            8.6.2                    pypi_0    pypi
jupyter_client            8.6.0            py39haa95532_0
jupyter_core              5.7.2            py39haa95532_0
libsodium                 1.0.18               h62dcd97_0
matplotlib-inline         0.1.7                    pypi_0    pypi
nest-asyncio              1.6.0            py39haa95532_0
openssl                   3.0.14               h827c3e9_0
packaging                 24.1                     pypi_0    pypi
parso                     0.8.4                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003
pip                       24.0             py39haa95532_0
platformdirs              4.2.2                    pypi_0    pypi
prompt-toolkit            3.0.47                   pypi_0    pypi
psutil                    6.0.0                    pypi_0    pypi
pure_eval                 0.2.2              pyhd3eb1b0_0
pygments                  2.18.0                   pypi_0    pypi
python                    3.9.19               h1aa4202_1
python-dateutil           2.9.0post0       py39haa95532_2
pywin32                   306                      pypi_0    pypi
pyzmq                     26.0.3                   pypi_0    pypi
setuptools                69.5.1           py39haa95532_0
six                       1.16.0             pyhd3eb1b0_1
spyder-kernels            2.5.2                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
stack-data                0.6.3                    pypi_0    pypi
stack_data                0.2.0              pyhd3eb1b0_0
tornado                   6.4.1            py39h827c3e9_0
traitlets                 5.14.3           py39haa95532_0
typing-extensions         4.12.2                   pypi_0    pypi
typing_extensions         4.11.0           py39haa95532_0
tzdata                    2024a                h04d1e81_0
vc                        14.2                 h2eaa2aa_1
vs2015_runtime            14.29.30133          h43f2093_3
wcwidth                   0.2.13                   pypi_0    pypi
wheel                     0.43.0           py39haa95532_0
zeromq                    4.3.5                hd77b12b_0
zipp                      3.19.2                   pypi_0    pypi

**Comment by ccordoba12** [comment]
Well, as you can see from the list, `openseespy` is not installed in your environment. And that's why you're getting the error you reported, which is a valid one.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
