### ISSUE TITLE
Unable to get Spyder render in Rich Text

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2221]
Hi ,

I installed Spyder from source in Ubuntu 14.04.2 LTS.  I get the following message:

**WARNING: unable to build documentation because Sphinx is not installed
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /usr/local/bin/spyder3 to 755
changing mode of /usr/local/bin/spyder_win_post_install.py to 775
running install_data
running install_egg_info
Removing /usr/local/lib/python3.4/dist-packages/spyder-2.4.0dev.egg-info
Writing /usr/local/lib/python3.4/dist-packages/spyder-2.4.0dev.egg-info**

I do have Sphinx installed on my machine.  When I run the following command: 
sudo apt-get install sphinxsearch
I get the following message saying that Sphinx is already installed.
**Reading package lists... Done
Building dependency tree       
Reading state information... Done
sphinxsearch is already the newest version.
The following packages were automatically installed and are no longer required:
  docutils-common docutils-doc fonts-mathjax ipython ipython-qtconsole
  libamd2.3.1 libapr1 libaprutil1 libcamd2.3.1 libccolamd2.8.0 libcholmod2.1.2
  libjs-jquery libjs-mathjax libjs-sphinxdoc libjs-underscore libpgm-5.1-0
  libserf-1-1 libsvn1 libumfpack5.6.2 libzmq3 mercurial mercurial-common pep8
  pyflakes pylint python-astroid python-dateutil python-decorator
  python-docutils python-egenix-mxdatetime python-egenix-mxtools python-jinja2
  python-logilab-common python-markupsafe python-matplotlib python-numpy
  python-psutil python-pygments python-pyparsing python-roman python-rope
  python-scipy python-simplegeneric python-sphinx python-spyderlib
  python-support python-svn python-tz python-zmq python3-decorator
  sphinx-common sphinx-doc
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.**

Can someone please tell me which package I am missing?

**Comment by ccordoba12** [comment]
That's not the right command to install sphinx, it is

    sudo apt-get install python-sphinx

or

    sudo apt-get install python3-sphinx

In any case, if sphinx is not found in your system, the installation doesn't fail (as your error message proves). It just doesn't build our documentation.
