### ISSUE TITLE
Matemáticas 

### ISSUE THREAD

**Issue by AndyGS-lang** [spyder-ide/spyder#22211]
import matplotlib.pyplot as plt

# Datos de las ecuaciones en la sección 4 con procedimientos
equations = [
    r"$\lim_{{x \to 0}} \left( \frac{1}{x} \right)$",
    r"Al aproximarse x a 0, \frac{1}{x} tiende a +\infty o -\infty",
    r"\rightarrow \infty",
    "",
    r"$\lim_{{x \to 5}} \left( \frac{x^2 - 25}{x + 5} \right)$",
    r"Factorizamos el numerador: x^2 - 25 = (x - 5)(x + 5)",
    r"\rightarrow \lim_{{x \to 5}} \left( \frac{(x - 5)(x + 5)}{x + 5} \right) = \lim_{{x \to 5}} (x - 5)",
    r"\rightarrow 0",
    "",
    r"$\lim_{{x \to 1}} \left( \frac{\sqrt{x} - 1}{x - 2} \right)$",
    r"Sustituimos directamente x = 1:",
    r"\rightarrow \frac{\sqrt{1} - 1}{1 - 2} = \frac{0}{-1}",
    r"\rightarrow 0",
    "",
    r"$\lim_{{x \to 1}} \left( \frac{x^3 + 1}{x - 1} \right)$",
    r"Factorizamos el numerador: x^3 + 1 = (x + 1)(x^2 - x + 1)",
    r"\rightarrow \lim_{{x \to 1}} \left( \frac{(x + 1)(x^2 - x + 1)}{x - 1} \right)",
    r"Sustituyendo directamente x = 1:",
    r"\rightarrow \frac{(1 + 1)(1^2 - 1 + 1)}{1 - 1} = \frac{2}{0}",
    r"\rightarrow \infty",
    "",
    r"$\lim_{{x \to 2}} \left( \frac{x^3 + 3x^2 - 10x}{2x - 5} \right)$",
    r"Factorizamos el numerador: x^3 + 3x^2 - 10x = x(x + 5)(x - 2)",
    r"\rightarrow \lim_{{x \to 2}} \left( \frac{x(x + 5)(x - 2)}{2x - 5} \right)",
    r"Sustituyendo directamente x = 2:",
    r"\rightarrow \frac{2(2 + 5)(2 - 2)}{4 - 5} = \frac{0}{-1}",
    r"\rightarrow 0",
    "",
    r"$\lim_{{x \to 0}} \left( \frac{10x}{2x + 5} \right)$",
    r"Simplificamos y sustituimos directamente:",
    r"\rightarrow \frac{10 \cdot 0}{2 \cdot 0 + 5} = \frac{0}{5}",
    r"\rightarrow 0",
    "",
    r"$\lim_{{x \to 1}} \left( \frac{\sqrt{x} - 1}{x - 1} \right)$",
    r"Usamos la regla de L'Hôpital:",
    r"\rightarrow \lim_{{x \to 1}} \left( \frac{\frac{d}{dx} (\sqrt{x} - 1)}{\frac{d}{dx} (x - 1)} \right)",
    r"\rightarrow \lim_{{x \to 1}} \left( \frac{\frac{1}{2\sqrt{x}}}{1} \right)",
    r"\rightarrow \frac{1}{2}"
]

# Crear una figura
fig, ax = plt.subplots(figsize=(10, 12))

# Ocultar ejes
ax.axis('off')

# Añadir las ecuaciones
for i, eq in enumerate(equations):
    ax.text(0.1, 1 - i*0.05, eq, fontsize=14, va='top', ha='left')

# Ajustar el diseño y mostrar la imagen
plt.tight_layout()
plt.show()

**Comment by ccordoba12** [comment]
Voy a cerrar el issue porque no obtuve respuesta mi pregunta anterior.
