### ISSUE TITLE
No console output

### ISSUE THREAD

**Issue by IR21-cyber** [spyder-ide/spyder#22221]
### What steps will reproduce the problem?

No output on the IPython Console when running the script using print() to produce the output

## Versions

* Spyder version: 5.5.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.4 (OK)
jsonschema >=3.2.0            :  4.22.0 (OK)
keyring >=17.0.0              :  25.2.1 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.0 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.8 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.3 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0        :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.2.0 (OK)
setuptools >=49.6.0           :  70.0.0 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.2,<2.6.0 :  2.5.2 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.1 (OK)
zmq >=24.0.0                  :  26.0.3 (OK)

# Optional:
cython >=0.21                 :  3.0.10 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @IR21-cyber, thanks for reporting. Could you post the script you're running which fails to produce output? In case it's too complex, please post the simplest version you can of it.

That will help us to reproduce your problem on our side. Otherwise we won't be able to help you.

**Comment by IR21-cyber** [comment]
Hi @ccordoba12, thank you for your reply. Actually I figured it out yesterday. I had this lines at the beginning of my script: 
# Clear the console
try:
     s = sys.winver
     os.system("cls")
except:
     os.system("clear")
     
and after I disabled them, everything worked. But I think it is a little bit weird, that the output on the console was cleared after running the script since the lines were placed at its beginning. 

Can you give any advice how am I supposed to clear the console before running the script?

**Comment by ccordoba12** [comment]
@IR21-cyber, ok, I understand better your problem now. You said:

> Can you give any advice how am I supposed to clear the console before running the script?

The mechanism we offer for that is to run the script in a dedicated console. To do that, you need to go to the menu

    Run > Configuration per file

and select `Run file with custom configuration` and then `Execute in a dedicated console`. That will always clear the console before running your code.

That should solve your problem, but let us know if it is what you're looking for.

**Comment by IR21-cyber** [comment]
@ccordoba12 it works, thank you very much for your help!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
