### ISSUE TITLE
Spyder2.3.3 Code completion breaks

### ISSUE THREAD

**Issue by BlackZ** [spyder-ide/spyder#2223]
Hi everyone,

first of all, a big thank you for developing this great spyder IDE. It is by far my weapon of choice and I enjoyed diving into python a lot more thanks to it. 

Now to my problem, which I am assuming is on my machine, but I cannot figure it out so I hope you guys can help me:

I just installed spyder 2.3.3 on a fresh ubuntu trusty installation and also installed jedi and rope with pip.

However, when I try to use auto completion (e.g. for the module time) I get the following error message from the internal console:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/utils/introspection/plugin_manager.py", line 58, in _handle_incoming
    self._threads[name].wait()
KeyError: PyQt4.QtCore.QString(u'rope')

I already tried to debug this error myself by adding basic "prints" in the file, but in my oppionion the key should be present. What I did find however was that I had to use the python3 print with the (). Is that something you forced, or does my system try to use python3 for some reason?

I hope this is the correct place to state such an individual problem and maybe someone can help me.

Edit: I just tried updating my spyder in my VM running Ubuntu precise and I get the same error. I installed spyder2.3.3 from source there since the pip installer would not work (threw the error:
error: option --single-version-externally-managed not recognized).

Am I missing something that I must do before code completion works?

**Comment by blink1073** [comment]
Hi @BlackZ, can you try changing that line in the file to `self._threads[str(name)].wait()`?

**Comment by BlackZ** [comment]
Hi @blink1073, I just tested it and it seems to work when I add the str conversion to the following line (result=..) as well:

        self._threads[str(name)].wait()
        if self.result:
            return
        result = self._threads[str(name)].result

Thanks a lot! Is this a general bug or is something fishy with my python installation?

**Comment by ccordoba12** [comment]
@blink1073 do you want to do a PR based on what @BlackZ reported?

**Comment by blink1073** [comment]
Yep, forthcoming.

**Comment by blink1073** [comment]
@BlackZ, there was nothing weird about your setup, other than the fact that `PyQt4` was not converting the `QString` values to `str` for you in your particular version.

**Comment by BlackZ** [comment]
@blink1073 thanks a lot, that is good to know. Hope the report was of help, keep up the good work!

**Comment by blink1073** [comment]
It was, and thanks!
