### ISSUE TITLE
Using miniconda env creates a bad CPU type error with macOS installer in M1 laptops

### ISSUE THREAD

**Issue by jameslparks** [spyder-ide/spyder#22233]
### What steps will reproduce the problem?

I have installed miniconda to create new environments which i can successfully. The spyder python interpreter also recognises the environment when restarting the kernel but whenever i attempt to run some code i get the message below.

I am using a macOS M3 system and installed syper through the Spyder_arm64.dmg. Sypder all works fine when not attempting to use other environments. 

/Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/plugins/ipythonconsole/scripts/conda-activate.sh: line 12: /Applications/Spyder.app/Contents/Resources/lib/python3.10/spyder/bin/micromamba: Bad CPU type in executable

## Versions

* Spyder version: 5.5.5 bef1bdcdc (standalone)
* Python version: 3.10.11 64-bit
* Qt version: 5.15.11
* PyQt5 version: 5.15.10
* Operating System: macOS-14.5-arm64-arm-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.25.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.0.4 (OK)
jsonschema >=3.2.0               :  4.22.0 (OK)
keyring >=17.0.0                 :  25.2.1 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.3 (OK)
pylint_venv >=3.0.2              :  None (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0           :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.2 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  65.5.0 (OK)
sphinx >=0.6.6                   :  5.1.1 (OK)
spyder_kernels >=2.5.2,<2.6.0    :  2.5.2 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  4.0.1 (OK)
zmq >=24.0.0                     :  26.0.3 (OK)

# Optional:
cython >=0.21                    :  3.0.10 (OK)
matplotlib >=3.0.0               :  3.9.0 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.13.1 (OK)
sympy >=0.7.3                    :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment]
Hey @jameslparks, thanks for reporting. Quick question, just to be sure: did you use our M1 installer for Spyder? Or the Intel one?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by jameslparks** [comment]
Sorry for the delayed response. Yes I did definitely use the M1 installer for spyder

**Comment by ccordoba12** [comment]
Ok, thanks for the confirmation. That's what I thought.

@mrclary, are we packing the right micromamba executable in our M1 installer for that architecture?

**Comment by mrclary** [comment]
> Ok, thanks for the confirmation. That's what I thought.
> 
> @mrclary, are we packing the right micromamba executable in our M1 installer for that architecture?

Indeed we are _not_ sending the correct micromamba for arm64. This was an oversight when we added the arm64 builds for our 5.x standalone installer.

**Comment by ccordoba12** [comment]
Thanks @mrclary for the confirmation.

@jameslparks, we'll fix this issue in our next version (5.5.6), to be released in a week or two.

**Comment by jameslparks** [comment]
@ccordoba12 is the 5.5.6 version release available yet? thanks

**Comment by ccordoba12** [comment]
Yes, it is. Sorry for the delay, we were quite busy preparing Spyder 6.0 and forgot about 5.5.6. But it'll be released tomorrow.
