### ISSUE TITLE
Spyder crashes on startup. Segmentation fault: fromIccProfile: failed minimal tag size sanity 

### ISSUE THREAD

**Issue by xaverm** [spyder-ide/spyder#22239]
Spyder 5.5.5 does not start anymore.
It crashes immediately after startup with two lines of err msg.:
```
fromIccProfile: failed minimal tag size sanity
Segmentation fault (core dumped)
```
Usually, when reporting, I list all of my config details here as from out of spyder - but as I wrote, it does not even start. 

Any help please!?

**Comment by xaverm** [comment]
One additional comment: If I generate a new environment and only install spyder directly after that, Spyder will still generate
`fromIccProfile: failed minimal tag size sanity`
but it does not crash after that ...?

**Comment by xaverm** [comment]
Yet another comment:
Setting up a new environment step-wise, the `segfault` of spyder happens after this `conda install` step

```
## Package Plan ##
  environment location: /home/xxxxx/.anaconda3/envs/sp
  added / updated specs:
    - mayavi

The following NEW packages will be INSTALLED:
  mayavi             conda-forge/linux-64::mayavi-4.8.2-py39hbf58f9e_3
  mesalib            conda-forge/linux-64::mesalib-24.1.3-h3ac77ca_0

The following packages will be DOWNGRADED:
  ffmpeg                             7.0.1-gpl_h3589c0a_102 --> 6.1.1-gpl_he2f97eb_114
  vtk                             9.3.1-qt_py39h1234567_200 --> 9.3.0-osmesa_py39h1234567_100
  vtk-base                        9.3.1-qt_py39h1234567_200 --> 9.3.0-osmesa_py39h1234567_100
  vtk-io-ffmpeg                   9.3.1-qt_py39h1234567_200 --> 9.3.0-osmesa_py39h1234567_100
```
Rolling back before that install, the `segfault` is gone again.
Forcing a `mayavi=4.8.1` install after that instead, there is no `segfault`.
So maybe there is some issue with `mayavi / mesalib / ffmpeg / vtk` (?)
This is about as far as my lame mileage gets me ...

Any help?

**Comment by ccordoba12** [comment]
Hey @xaverm, thanks for reporting. The problem could be with VTK because I saw they're trying to transition to Qt6 and Spyder 5 is not ready for it.

My suggestion for you is to install Spyder in a different environment by running:

    conda create -n spyder-env spyder python=3.11
    conda activate spyder-env
    spyder

Then you can connect that Spyder to your `sp` env by following the procedure described in our documentation:

http://docs.spyder-ide.org/current/faq.html#using-existing-environment

That would prevent the segfaults you're having and allow you to continue working with your current env.

**Comment by xaverm** [comment]
@ccordoba12 Thx. for getting back to me.

Ok. since the last revision without spyder segfaulting did have a `vtk=9.2.6`, I'll pin the environment to that version and will keep also `mayavi=4.8.1` (which seems to force the qt update if updated by itself(?)). That seems to keep a running status, even if I do `conda update --all` after that and even if I stick with just one environment.

This is not really a mind-soothing situation ;-) ... anyway, are you guys having a rough plan when Spyder will cope with newer qt versions?

**Comment by ccordoba12** [comment]
> This is not really a mind-soothing situation ;-) ... anyway, are you guys having a rough plan when Spyder will cope with newer qt versions?

We should be able to support Qt6/PyQt6 next year. Spyder 6 will come with initial (but not default) support for it, but we still have to run our test suite against that version, which could take a couple of months to make it pass.

> Edit: B.t.w.: Which are the recommended versions of the (many ... :-( ) qt packages that one should keep, such as to have spyder not get into trouble with them?

Spyder works best with PyQt5 5.15.

But I think you'd do much better by following [my recommendation](https://github.com/spyder-ide/spyder/issues/22239#issuecomment-2217909631) above, i.e. have Spyder in a separate env and connect it to the envs you want to work with.

That would be much easier in Spyder 6 because we'll have a new submenu in the `Consoles` menu to open a console for any env you want.

**Comment by ccordoba12** [comment]
One question for you @xaverm: is it ok to close this issue given that you managed to solve your problem?

**Comment by NelsonUpenn** [comment]
I run MacOS14.5 (latest). Today I downloaded and installed Anaconda. Then 
conda update --all
Then
conda list
returns:
spyder                    5.5.1           py312hca03da5_3  
(I will paste the entire listing below, but for now I will point out that vtk is not installed.)
Then I asked at the command line for:
spyder
which gives the error:
===
The available OpenGL surface format was either not version 3.2 or higher or not a Core Profile.
Chromium on macOS will fall back to software rendering in this case.
Hardware acceleration and features such as WebGL will not be available.
fromIccProfile: failed minimal tag size sanity
/opt/anaconda3/bin/pythonw: line 3: 72922 Segmentation fault: 11  /opt/anaconda3/python.app/Contents/MacOS/python "$@"
===
I have no environments, just installed Anaconda out of the box. 

This is disturbing. I did not quite follow the advice above, so could you offer a very explicit suggestion?

Thank you P Nelson
=====FULL OUTPUT OF CONDA LIST
$ conda list
# packages in environment at /opt/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2024.06         py312_openblas_2  
abseil-cpp                20230802.0           h313beb8_2  
aiobotocore               2.12.3          py312hca03da5_0  
aiohttp                   3.9.5           py312h80987f9_0  
aioitertools              0.7.1              pyhd3eb1b0_0  
aiosignal                 1.2.0              pyhd3eb1b0_0  
alabaster                 0.7.16          py312hca03da5_0  
altair                    5.0.1           py312hca03da5_0  
anaconda-anon-usage       0.4.4           py312hd6b623d_100  
anaconda-catalogs         0.2.0           py312hca03da5_1  
anaconda-client           1.12.3          py312hca03da5_0  
anaconda-cloud-auth       0.5.1           py312hca03da5_0  
anaconda-navigator        2.6.1           py312hca03da5_2  
anaconda-project          0.11.1          py312hca03da5_0  
annotated-types           0.6.0           py312hca03da5_0  
anyio                     4.2.0           py312hca03da5_0  
aom                       3.6.0                h313beb8_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
applaunchservices         0.3.0           py312hca03da5_0  
appnope                   0.1.3           py312hca03da5_1001  
appscript                 1.1.2           py312h80987f9_0  
archspec                  0.2.3              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0          py312h80987f9_0  
arrow                     1.2.3           py312hca03da5_1  
arrow-cpp                 14.0.2               hc7aafb3_1  
astroid                   2.14.2          py312hca03da5_0  
astropy                   6.1.0           py312ha86b861_0  
astropy-iers-data         0.2024.6.3.0.31.14 py312hca03da5_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
async-lru                 2.0.4           py312hca03da5_0  
atomicwrites              1.4.0                      py_0  
attrs                     23.1.0          py312hca03da5_0  
automat                   20.2.0                     py_0  
autopep8                  2.0.4              pyhd3eb1b0_0  
aws-c-auth                0.6.19               h80987f9_0  
aws-c-cal                 0.5.20               h80987f9_0  
aws-c-common              0.8.5                h80987f9_0  
aws-c-compression         0.2.16               h80987f9_0  
aws-c-event-stream        0.2.15               h313beb8_0  
aws-c-http                0.6.25               h80987f9_0  
aws-c-io                  0.13.10              h80987f9_0  
aws-c-mqtt                0.7.13               h80987f9_0  
aws-c-s3                  0.1.51               h80987f9_0  
aws-c-sdkutils            0.1.6                h80987f9_0  
aws-checksums             0.1.13               h80987f9_0  
aws-crt-cpp               0.18.16              h313beb8_0  
aws-sdk-cpp               1.10.55              h313beb8_0  
babel                     2.11.0          py312hca03da5_0  
bcrypt                    3.2.0           py312h80987f9_1  
beautifulsoup4            4.12.3          py312hca03da5_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     24.4.2          py312hca03da5_0  
blas                      1.0                    openblas  
bleach                    4.1.0              pyhd3eb1b0_0  
blinker                   1.6.2           py312hca03da5_0  
blosc                     1.21.3               h313beb8_0  
bokeh                     3.4.1           py312h989b03a_0  
boltons                   23.0.0          py312hca03da5_0  
boost-cpp                 1.82.0               h48ca7d4_2  
botocore                  1.34.69         py312hca03da5_0  
bottleneck                1.3.7           py312ha86b861_0  
brotli                    1.0.9                h80987f9_8  
brotli-bin                1.0.9                h80987f9_8  
brotli-python             1.0.9           py312h313beb8_8  
brunsli                   0.1                  hc377ac9_1  
bzip2                     1.0.8                h80987f9_6  
c-ares                    1.19.1               h80987f9_0  
c-blosc2                  2.12.0               h7df6c2f_0  
ca-certificates           2024.7.2             hca03da5_0  
cachetools                5.3.3           py312hca03da5_0  
cctools                   949.0.1             hc179dcd_26  
cctools_osx-arm64         949.0.1             h69e4071_26  
certifi                   2024.7.4        py312hca03da5_0  
cffi                      1.16.0          py312h80987f9_1  
cfitsio                   3.470                h7f6438f_7  
chardet                   4.0.0           py312hca03da5_1003  
charls                    2.2.0                hc377ac9_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.1.7           py312hca03da5_0  
cloudpickle               2.2.1           py312hca03da5_0  
colorama                  0.4.6           py312hca03da5_0  
colorcet                  3.1.0           py312hca03da5_0  
comm                      0.2.1           py312hca03da5_0  
conda                     24.5.0          py312hca03da5_0  
conda-build               24.5.1          py312hca03da5_0  
conda-content-trust       0.2.0           py312hca03da5_1  
conda-index               0.5.0           py312hca03da5_0  
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0  
conda-pack                0.7.1           py312hca03da5_0  
conda-package-handling    2.3.0           py312hca03da5_0  
conda-package-streaming   0.10.0          py312hca03da5_0  
conda-repo-cli            1.0.88          py312hca03da5_0  
conda-token               0.5.0              pyhd3eb1b0_0  
constantly                23.10.4         py312hca03da5_0  
contourpy                 1.2.0           py312h48ca7d4_0  
cookiecutter              2.6.0           py312hca03da5_0  
cryptography              42.0.5          py312hd4332d6_1  
cssselect                 1.2.0           py312hca03da5_0  
curl                      8.7.1                h02f6b3c_0  
cycler                    0.11.0             pyhd3eb1b0_0  
cyrus-sasl                2.1.28               h9131b1a_1  
cytoolz                   0.12.2          py312h80987f9_0  
dask                      2024.5.0        py312hca03da5_0  
dask-core                 2024.5.0        py312hca03da5_0  
dask-expr                 1.1.0           py312hca03da5_0  
datashader                0.16.3          py312hca03da5_0  
dav1d                     1.2.1                h80987f9_0  
debugpy                   1.6.7           py312h313beb8_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713           pyhd3eb1b0_0  
dill                      0.3.8           py312hca03da5_0  
distributed               2024.5.0        py312hca03da5_0  
distro                    1.9.0           py312hca03da5_0  
docstring-to-markdown     0.11            py312hca03da5_0  
docutils                  0.18.1          py312hca03da5_3  
entrypoints               0.4             py312hca03da5_0  
et_xmlfile                1.1.0           py312hca03da5_1  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.6.2                h313beb8_0  
filelock                  3.13.1          py312hca03da5_0  
flake8                    7.0.0           py312hca03da5_0  
flask                     3.0.3           py312hca03da5_0  
fmt                       9.1.0                h48ca7d4_1  
fonttools                 4.51.0          py312h80987f9_0  
freetype                  2.12.1               h1192e45_0  
frozendict                2.4.2           py312hca03da5_0  
frozenlist                1.4.0           py312h80987f9_0  
fsspec                    2024.3.1        py312hca03da5_0  
gensim                    4.3.2           py312hd77ebd4_0  
gettext                   0.21.0               h13f89a0_1  
gflags                    2.2.2                h313beb8_1  
giflib                    5.2.1                h80987f9_3  
gitdb                     4.0.7              pyhd3eb1b0_0  
gitpython                 3.1.43          py312hca03da5_0  
glib                      2.78.4               h313beb8_0  
glib-tools                2.78.4               h313beb8_0  
glog                      0.5.0                h313beb8_1  
greenlet                  3.0.1           py312h313beb8_0  
grpc-cpp                  1.48.2               hc60591f_4  
gst-plugins-base          1.14.1               h313beb8_1  
gstreamer                 1.14.1               h80987f9_1  
gtest                     1.14.0               h48ca7d4_1  
h5py                      3.11.0          py312haac6407_0  
hdf5                      1.12.1               h05c076b_3  
heapdict                  1.0.1              pyhd3eb1b0_0  
holoviews                 1.19.1          py312hca03da5_0  
hvplot                    0.10.0          py312hca03da5_0  
hyperlink                 21.0.0             pyhd3eb1b0_0  
icu                       73.1                 h313beb8_0  
idna                      3.7             py312hca03da5_0  
imagecodecs               2023.1.23       py312h75b721f_1  
imageio                   2.33.1          py312hca03da5_0  
imagesize                 1.4.1           py312hca03da5_0  
imbalanced-learn          0.12.3          py312hca03da5_1  
importlib-metadata        7.0.1           py312hca03da5_0  
incremental               22.10.0            pyhd3eb1b0_0  
inflection                0.5.1           py312hca03da5_1  
iniconfig                 1.1.1              pyhd3eb1b0_0  
intake                    0.7.0           py312hca03da5_0  
intervaltree              3.1.0              pyhd3eb1b0_0  
ipykernel                 6.28.0          py312hca03da5_0  
ipython                   8.25.0          py312hca03da5_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.8.1           py312hca03da5_0  
isort                     5.13.2          py312hca03da5_0  
itemadapter               0.3.0              pyhd3eb1b0_0  
itemloaders               1.1.0           py312hca03da5_0  
itsdangerous              2.2.0           py312hca03da5_0  
jaraco.classes            3.2.1              pyhd3eb1b0_0  
jedi                      0.19.1          py312hca03da5_0  
jellyfish                 1.0.1           py312h15d1925_0  
jinja2                    3.1.4           py312hca03da5_0  
jmespath                  1.0.1           py312hca03da5_0  
joblib                    1.4.2           py312hca03da5_0  
jpeg                      9e                   h80987f9_1  
jq                        1.6                  h1a28f6b_1  
json5                     0.9.6              pyhd3eb1b0_0  
jsonpatch                 1.33            py312hca03da5_1  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.19.2          py312hca03da5_0  
jsonschema-specifications 2023.7.1        py312hca03da5_0  
jupyter                   1.0.0           py312hca03da5_9  
jupyter-lsp               2.2.0           py312hca03da5_0  
jupyter_client            8.6.0           py312hca03da5_0  
jupyter_console           6.6.3           py312hca03da5_1  
jupyter_core              5.7.2           py312hca03da5_0  
jupyter_events            0.10.0          py312hca03da5_0  
jupyter_server            2.14.1          py312hca03da5_0  
jupyter_server_terminals  0.4.4           py312hca03da5_1  
jupyterlab                4.0.11          py312hca03da5_0  
jupyterlab-variableinspector 3.1.0           py312hca03da5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         2.25.1          py312hca03da5_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jxrlib                    1.1                  h1a28f6b_2  
keyring                   24.3.1          py312hca03da5_0  
kiwisolver                1.4.4           py312h313beb8_0  
krb5                      1.20.1               hf3e1bf2_1  
lazy-object-proxy         1.10.0          py312h80987f9_0  
lazy_loader               0.4             py312hca03da5_0  
lcms2                     2.12                 hba8e193_0  
ld64                      530                 hb29bf3f_26  
ld64_osx-arm64            530                 hac4b543_26  
ldid                      2.1.5                h20b2a84_3  
lerc                      3.0                  hc377ac9_0  
libaec                    1.0.4                hc377ac9_1  
libarchive                3.6.2                h62fee54_3  
libavif                   0.11.1               h80987f9_0  
libboost                  1.82.0               h0bc93f9_2  
libbrotlicommon           1.0.9                h80987f9_8  
libbrotlidec              1.0.9                h80987f9_8  
libbrotlienc              1.0.9                h80987f9_8  
libclang                  14.0.6          default_h1b80db6_1  
libclang13                14.0.6          default_h24352ff_1  
libcurl                   8.7.1                h3e2b118_0  
libcxx                    14.0.6               h848a8c0_0  
libdeflate                1.17                 h80987f9_1  
libedit                   3.1.20230828         h80987f9_0  
libev                     4.33                 h1a28f6b_1  
libevent                  2.1.12               h02f6b3c_1  
libffi                    3.4.4                hca03da5_1  
libgfortran               5.0.0           11_3_0_hca03da5_28  
libgfortran5              11.3.0              h009349e_28  
libglib                   2.78.4               h0a96307_0  
libiconv                  1.16                 h80987f9_3  
liblief                   0.12.3               h313beb8_0  
libllvm14                 14.0.6               h7ec7a93_3  
libmamba                  1.5.8                haeffa04_2  
libmambapy                1.5.8           py312h1c5506f_2  
libnghttp2                1.57.0               h62f6fdd_0  
libopenblas               0.3.21               h269037a_0  
libpng                    1.6.39               h80987f9_0  
libpq                     12.17                h02f6b3c_0  
libprotobuf               3.20.3               h514c7bf_0  
libsodium                 1.0.18               h1a28f6b_0  
libsolv                   0.7.24               h514c7bf_1  
libspatialindex           1.9.3                hc377ac9_0  
libssh2                   1.11.0               h3e2b118_0  
libthrift                 0.15.0               h73c2103_2  
libtiff                   4.5.1                h313beb8_0  
libwebp-base              1.3.2                h80987f9_0  
libxml2                   2.10.4               h0b34f26_2  
libxslt                   1.1.37               h80987f9_1  
libzopfli                 1.0.3                hc377ac9_0  
linkify-it-py             2.0.0           py312hca03da5_0  
llvm-openmp               14.0.6               hc6e5704_0  
llvmlite                  0.43.0          py312h313beb8_0  
locket                    1.0.0           py312hca03da5_0  
lxml                      5.2.1           py312h50ffb84_0  
lz4                       4.3.2           py312h80987f9_0  
lz4-c                     1.9.4                h313beb8_1  
lzo                       2.10                 h1a28f6b_2  
markdown                  3.4.1           py312hca03da5_0  
markdown-it-py            2.2.0           py312hca03da5_1  
markupsafe                2.1.3           py312h80987f9_0  
matplotlib                3.8.4           py312hca03da5_0  
matplotlib-base           3.8.4           py312hd77ebd4_0  
matplotlib-inline         0.1.6           py312hca03da5_0  
mccabe                    0.7.0              pyhd3eb1b0_0  
mdit-py-plugins           0.3.0           py312hca03da5_0  
mdurl                     0.1.0           py312hca03da5_0  
menuinst                  2.1.1           py312hca03da5_0  
mistune                   2.0.4           py312hca03da5_0  
more-itertools            10.1.0          py312hca03da5_0  
mpmath                    1.3.0           py312hca03da5_0  
msgpack-python            1.0.3           py312h48ca7d4_0  
multidict                 6.0.4           py312h80987f9_0  
multipledispatch          0.6.0           py312hca03da5_0  
mypy                      1.10.0          py312h80987f9_0  
mypy_extensions           1.0.0           py312hca03da5_0  
mysql                     5.7.24               ha71a6ea_2  
navigator-updater         0.5.1           py312hca03da5_0  
nbclient                  0.8.0           py312hca03da5_0  
nbconvert                 7.10.0          py312hca03da5_0  
nbformat                  5.9.2           py312hca03da5_0  
ncurses                   6.4                  h313beb8_0  
nest-asyncio              1.6.0           py312hca03da5_0  
networkx                  3.3             py312hca03da5_0  
nltk                      3.8.1           py312hca03da5_0  
notebook                  7.0.8           py312hca03da5_2  
notebook-shim             0.2.3           py312hca03da5_0  
numba                     0.60.0          py312hd77ebd4_0  
numexpr                   2.8.7           py312h0f3ea24_0  
numpy                     1.26.4          py312h7f4fdc5_0  
numpy-base                1.26.4          py312he047099_0  
numpydoc                  1.7.0           py312hca03da5_0  
oniguruma                 6.9.7.1              h1a28f6b_0  
openjpeg                  2.4.0                h0ed58ac_2  
openpyxl                  3.1.2           py312h80987f9_0  
openssl                   3.0.14               h80987f9_0  
orc                       1.7.4                hdca1487_1  
overrides                 7.4.0           py312hca03da5_0  
packaging                 23.2            py312hca03da5_0  
pandas                    2.2.2           py312hd77ebd4_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
panel                     1.4.4           py312hca03da5_0  
param                     2.1.1           py312hca03da5_0  
parsel                    1.8.1           py312hca03da5_0  
parso                     0.8.3              pyhd3eb1b0_0  
partd                     1.4.1           py312hca03da5_0  
patch                     2.7.6             h1a28f6b_1001  
pathspec                  0.10.3          py312hca03da5_0  
patsy                     0.5.6           py312hca03da5_0  
pcre2                     10.42                hb066dcc_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    10.4.0          py312h80987f9_0  
pip                       24.0            py312hca03da5_0  
pkce                      1.0.3           py312hca03da5_0  
pkginfo                   1.10.0          py312hca03da5_0  
platformdirs              3.10.0          py312hca03da5_0  
plotly                    5.22.0          py312h989b03a_0  
pluggy                    1.0.0           py312hca03da5_1  
ply                       3.11            py312hca03da5_1  
prometheus_client         0.14.1          py312hca03da5_0  
prompt-toolkit            3.0.43          py312hca03da5_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
protego                   0.1.16                     py_0  
protobuf                  3.20.3          py312h313beb8_0  
psutil                    5.9.0           py312h80987f9_0  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
py-cpuinfo                9.0.0           py312hca03da5_0  
py-lief                   0.12.3          py312h313beb8_0  
pyarrow                   14.0.2          py312h8604a13_0  
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pybind11-abi              5                    hd3eb1b0_0  
pycodestyle               2.11.1          py312hca03da5_0  
pycosat                   0.6.6           py312h80987f9_1  
pycparser                 2.21               pyhd3eb1b0_0  
pyct                      0.5.0           py312hca03da5_0  
pycurl                    7.45.2          py312h02f6b3c_1  
pydantic                  2.5.3           py312hca03da5_0  
pydantic-core             2.14.6          py312hf0e4da2_0  
pydeck                    0.8.0           py312hca03da5_2  
pydispatcher              2.0.5           py312hca03da5_3  
pydocstyle                6.3.0           py312hca03da5_0  
pyerfa                    2.0.1.4         py312ha86b861_0  
pyflakes                  3.2.0           py312hca03da5_0  
pygments                  2.15.1          py312hca03da5_1  
pyjwt                     2.8.0           py312hca03da5_0  
pylint                    2.16.2          py312hca03da5_0  
pylint-venv               3.0.3           py312hca03da5_0  
pyls-spyder               0.4.0              pyhd3eb1b0_0  
pyobjc-core               10.1            py312h80987f9_0  
pyobjc-framework-cocoa    10.1            py312hb094c41_0  
pyobjc-framework-coreservices 10.1            py312hdd8dd1f_0  
pyobjc-framework-fsevents 10.1            py312hca03da5_0  
pyodbc                    5.0.1           py312h313beb8_0  
pyopenssl                 24.0.0          py312hca03da5_0  
pyparsing                 3.0.9           py312hca03da5_0  
pyqt                      5.15.10         py312h313beb8_0  
pyqt5-sip                 12.13.0         py312h80987f9_0  
pyqtwebengine             5.15.10         py312h313beb8_0  
pysocks                   1.7.1           py312hca03da5_0  
pytables                  3.9.2           py312h905a39b_0  
pytest                    7.4.4           py312hca03da5_0  
python                    3.12.4               h99e199e_1  
python-dateutil           2.9.0post0      py312hca03da5_2  
python-dotenv             0.21.0          py312hca03da5_0  
python-fastjsonschema     2.16.2          py312hca03da5_0  
python-json-logger        2.0.7           py312hca03da5_0  
python-libarchive-c       2.9                pyhd3eb1b0_1  
python-lmdb               1.4.1           py312h313beb8_0  
python-lsp-black          2.0.0           py312hca03da5_0  
python-lsp-jsonrpc        1.1.2              pyhd3eb1b0_0  
python-lsp-server         1.10.0          py312hca03da5_0  
python-slugify            5.0.2              pyhd3eb1b0_0  
python-snappy             0.6.1           py312h313beb8_0  
python-tzdata             2023.3             pyhd3eb1b0_0  
python.app                3               py312h80987f9_0  
pytoolconfig              1.2.6           py312hca03da5_0  
pytz                      2024.1          py312hca03da5_0  
pyviz_comms               3.0.2           py312hca03da5_0  
pywavelets                1.5.0           py312ha86b861_0  
pyyaml                    6.0.1           py312h80987f9_0  
pyzmq                     25.1.2          py312h313beb8_0  
qdarkstyle                3.2.3              pyhd3eb1b0_0  
qstylizer                 0.2.2           py312hca03da5_0  
qt-main                   5.15.2              h0917680_10  
qt-webengine              5.15.9               h2903aaf_7  
qtawesome                 1.2.2           py312hca03da5_0  
qtconsole                 5.5.1           py312hca03da5_0  
qtpy                      2.4.1           py312hca03da5_0  
queuelib                  1.6.2           py312hca03da5_0  
re2                       2022.04.01           hc377ac9_0  
readline                  8.2                  h1a28f6b_0  
referencing               0.30.2          py312hca03da5_0  
regex                     2023.10.3       py312h80987f9_0  
reproc                    14.2.4               h313beb8_2  
reproc-cpp                14.2.4               h313beb8_2  
requests                  2.32.2          py312hca03da5_0  
requests-file             1.5.1              pyhd3eb1b0_0  
requests-toolbelt         1.0.0           py312hca03da5_0  
rfc3339-validator         0.1.4           py312hca03da5_0  
rfc3986-validator         0.1.1           py312hca03da5_0  
rich                      13.7.1          py312hca03da5_0  
rope                      1.12.0          py312hca03da5_0  
rpds-py                   0.10.6          py312hf0e4da2_0  
rtree                     1.0.1           py312hca03da5_0  
ruamel.yaml               0.17.21         py312h80987f9_0  
ruamel_yaml               0.17.21         py312h80987f9_0  
s3fs                      2024.3.1        py312hca03da5_0  
scikit-image              0.23.2          py312hd77ebd4_0  
scikit-learn              1.4.2           py312hd77ebd4_1  
scipy                     1.13.1          py312ha409365_0  
scrapy                    2.11.1          py312hca03da5_0  
seaborn                   0.13.2          py312hca03da5_0  
semver                    3.0.2           py312hca03da5_0  
send2trash                1.8.2           py312hca03da5_0  
service_identity          18.1.0             pyhd3eb1b0_1  
setuptools                69.5.1          py312hca03da5_0  
sip                       6.7.12          py312h313beb8_0  
six                       1.16.0             pyhd3eb1b0_1  
smart_open                5.2.1           py312hca03da5_0  
smmap                     4.0.0              pyhd3eb1b0_0  
snappy                    1.1.10               h313beb8_1  
sniffio                   1.3.0           py312hca03da5_0  
snowballstemmer           2.2.0              pyhd3eb1b0_0  
sortedcontainers          2.4.0              pyhd3eb1b0_0  
soupsieve                 2.5             py312hca03da5_0  
sphinx                    7.3.7           py312hca03da5_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.10          py312hca03da5_0  
spyder                    5.5.1           py312hca03da5_3  
spyder-kernels            2.5.0           py312hca03da5_0  
sqlalchemy                2.0.30          py312h80987f9_0  
sqlite                    3.45.3               h80987f9_0  
stack_data                0.2.0              pyhd3eb1b0_0  
statsmodels               0.14.2          py312ha86b861_0  
streamlit                 1.32.0          py312hca03da5_0  
sympy                     1.12            py312hca03da5_0  
tabulate                  0.9.0           py312hca03da5_0  
tapi                      1100.0.11            hf6daf3e_2  
tbb                       2021.8.0             h48ca7d4_0  
tblib                     1.7.0              pyhd3eb1b0_0  
tenacity                  8.2.3           py312hca03da5_0  
terminado                 0.17.1          py312hca03da5_0  
text-unidecode            1.3                pyhd3eb1b0_0  
textdistance              4.2.1              pyhd3eb1b0_0  
threadpoolctl             3.5.0           py312h989b03a_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tifffile                  2023.4.12       py312hca03da5_0  
tinycss2                  1.2.1           py312hca03da5_0  
tk                        8.6.14               h6ba3021_0  
tldextract                3.2.0              pyhd3eb1b0_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     2.0.1           py312hca03da5_1  
tomlkit                   0.11.1          py312hca03da5_0  
toolz                     0.12.0          py312hca03da5_0  
tornado                   6.4.1           py312h80987f9_0  
tqdm                      4.66.4          py312h989b03a_0  
traitlets                 5.14.3          py312hca03da5_0  
truststore                0.8.0           py312hca03da5_0  
twisted                   23.10.0         py312hca03da5_0  
typing-extensions         4.11.0          py312hca03da5_0  
typing_extensions         4.11.0          py312hca03da5_0  
tzdata                    2024a                h04d1e81_0  
uc-micro-py               1.0.1           py312hca03da5_0  
ujson                     5.10.0          py312h313beb8_0  
unicodedata2              15.1.0          py312h80987f9_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
unixodbc                  2.3.11               h1a28f6b_0  
urllib3                   2.2.2           py312hca03da5_0  
utf8proc                  2.6.1                h80987f9_1  
w3lib                     2.1.2           py312hca03da5_0  
watchdog                  4.0.1           py312h80987f9_0  
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1           py312hca03da5_2  
websocket-client          1.8.0           py312hca03da5_0  
werkzeug                  3.0.3           py312hca03da5_0  
whatthepatch              1.0.2           py312hca03da5_0  
wheel                     0.43.0          py312hca03da5_0  
widgetsnbextension        3.6.6           py312hca03da5_0  
wrapt                     1.14.1          py312h80987f9_0  
wurlitzer                 3.0.2           py312hca03da5_0  
xarray                    2023.6.0        py312hca03da5_0  
xlwings                   0.31.4          py312hca03da5_0  
xyzservices               2022.9.0        py312hca03da5_1  
xz                        5.4.6                h80987f9_1  
yaml                      0.2.5                h1a28f6b_0  
yaml-cpp                  0.8.0                h313beb8_1  
yapf                      0.40.2          py312hca03da5_0  
yarl                      1.9.3           py312h80987f9_0  
zeromq                    4.3.5                h313beb8_0  
zfp                       1.0.0                h313beb8_0  
zict                      3.0.0           py312hca03da5_0  
zipp                      3.17.0          py312hca03da5_0  
zlib                      1.2.13               h18a0788_1  
zlib-ng                   2.0.7                h80987f9_0  
zope                      1.0             py312hca03da5_1  
zope.interface            5.4.0           py312h80987f9_0  
zstandard                 0.22.0          py312h1a4646a_0  
zstd                      1.5.5                hd90d995_2

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by NelsonUpenn** [comment]
Actually I did respond by email, asking whether there was a plan to fix this issue some time soon. I cannot recommend Spyder to my students unless it works out of the box.

**Comment by xaverm** [comment]
@ccordoba12 Oops. Away from github for just a "split sec." ;) Yes. Fine to close.

Keep this fantastic project running!

**Comment by NelsonUpenn** [comment]
Hello xaverm
I'm not sure I understand. Is the issue actually resolved? What is the resolution? I cannot recommend Spyder to the class I will teach unless it, and the Anaconda distribution, works on mac.
P Nelson

**Comment by xaverm** [comment]
@NelsonUpenn Just don't worry about this issue, i.e., [the one I have reported here](https://github.com/spyder-ide/spyder/issues/22239#issue-2397379174). In contrast to a proper issue report it is ill-documented, because, as described, Spyder kept crashing before I could collect any relevant info. And yes, it is exactly this issue which is "...actually resolved..." [for me, as stated here](https://github.com/spyder-ide/spyder/issues/22239#issuecomment-2217236000). Very likely, this will not resolve any, potentially even vaguely related, issues which you might have - and for which you should provide a detailed report afresh. That is why @ccordoba12 was perfectly right to close it. 

(On a different note: I'd rather use JupyterLab in class. There are tons of tools using this with interactive / hosted / and what-have-you teaching for a browsers. Spyder is for real science outside of class. And for that we stay away from Cupertino gadgets.)

**Comment by NelsonUpenn** [comment]
Thank you.

> On Aug 10, 2024, at 7:02 AM, xaverm ***@***.***> wrote:
> (On a different note: I'd rather use JupyterLab in class. There are tons of tools using this with interactive / hosted / and what-have-you teaching for a browsers. Spyder is for real science outside of class. And for that we stay away from Cupertino gadgets.)
** Yes, I agree, and you said it very well. Indeed I do prefer Spyder for my research.

P Nelson
