### ISSUE TITLE
internal error 

### ISSUE THREAD

**Issue by tengzikun** [spyder-ide/spyder#22241]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Press run and error happened. did not happen when i used VSC to run the same code.

**Comment by ccordoba12** [comment]
Hey @tengzikun, thanks for reporting. Could you post a simple version of the code you're trying to run in Spyder?

Otherwise I'm afraid we won't be able to help you, sorry.

**Comment by tengzikun** [comment]
Hi ccordoba12. I appreciate your kind reply and attention for this matter. The code is rather simple - using python and pandas library to read a series of csv files and identify the matched entries.  The code works perfectly on VSC, just not spyder

As its my company's code, i can only show u the general picture:
import os
import pandas as pd
from datetime import datetime
 
def parse_datetime(datetime_str):
    # Function to parse datetime from string
    # (Unchanged from the original code)
 
    # ... (Unchanged code)
 
def create_matching_records_csv(csv_files, vehicle_numbers):
    # Function to create matching records CSV
    # (Unchanged from the original code)
 
    # ... (Unchanged code)
 
def main():
    # Main function to prompt for input and process CSV files
    # (Unchanged from the original code)
 
    directory = r'path_to_directory'  # Replace with the actual directory path
    vehicle_numbers_input = input("Enter vehicle IU numbers separated by ';': ")
    vehicle_numbers = vehicle_numbers_input.split(';')
 
    csv_files = [os.path.join(directory, file) for file in os.listdir(directory) if file.endswith('.csv')]
 
    create_matching_records_csv(csv_files, vehicle_numbers)
 
if __name__ == "__main__":
    main()

**Comment by ccordoba12** [comment]
Ok, thanks and sorry for the late reply. What's your Spyder version? And what operating system you're using?

**Comment by ccordoba12** [comment]
I think this problem is fixed in our latest version available in Anaconda (5.5.1). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).
