### ISSUE TITLE
Spyder 6.0.0b2 consoles fail to start with micromamba

### ISSUE THREAD

**Issue by BjornFJohansson** [spyder-ide/spyder#22240]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

![image](https://github.com/spyder-ide/spyder/assets/9726401/3b6afbba-bf77-4c16-a38b-7d46c234f3ce)

### What steps reproduce the problem?

1.  Install spyder 6.0.0b1 or b2
2. Install the recommended spyder-kernels
3. 

### What is the expected output? What do you see instead?

Kernel does not start

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 6.0.0b1  (conda)
* Python version: 3.10.12 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Linux-6.5.0-41-generic-x86_64-with-glibc2.35

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                   :  3.9.5 (OK)
asyncssh >=2.0.0,<3.0.0           :  2.14.1 (OK)
atomicwrites >=1.2.0              :  1.4.1 (OK)
chardet >=2.0.0                   :  5.2.0 (OK)
cloudpickle >=0.5.0               :  3.0.0 (OK)
cookiecutter >=1.6.0              :  2.6.0 (OK)
diff_match_patch >=20181111       :  20230430 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1  :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0             :  0.19.1 (OK)
jellyfish >=0.7                   :  1.0.4 (OK)
jsonschema >=3.2.0                :  4.20.0 (OK)
keyring >=17.0.0                  :  25.2.1 (OK)
nbconvert >=4.0                   :  7.14.1 (OK)
numpydoc >=0.6.0                  :  1.7.0 (OK)
parso >=0.7.0,<0.9.0              :  0.8.3 (OK)
pexpect >=4.4.0                   :  4.8.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.9.7 (OK)
pygments >=2.0                    :  2.17.2 (OK)
pylint >=3.1,<4                   :  3.2.5 (OK)
pylint_venv >=3.0.2               :  3.0.3 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0            :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0        :  2.0.0 (OK)
pyuca >=1.2                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0         :  3.2.3 (OK)
qstylizer >=0.2.2                 :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0          :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0          :  5.5.2 (OK)
qtpy >=2.4.0                      :  2.4.1 (OK)
rtree >=0.9.7                     :  1.2.0 (OK)
setuptools >=49.6.0               :  68.1.2 (OK)
sphinx >=0.6.6                    :  7.3.7 (OK)
spyder_kernels >=3.0.0b6,<3.0.0b7 :  3.0.0b6 (OK)
superqt >=0.6.1,<1.0.0            :  0.6.7 (OK)
textdistance >=4.2.0              :  4.6.2 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  4.0.1 (OK)
xdg >=0.26                        :  0.28 (OK)
yarl >=1.9.4                      :  1.9.4 (OK)
zmq >=24.0.0                      :  25.1.2 (OK)

# Optional:
cython >=0.21                     :  None (NOK)
matplotlib >=3.0.0                :  None (NOK)
numpy >=1.7                       :  1.26.2 (OK)
pandas >=1.1.1                    :  None (NOK)
scipy >=0.17.0                    :  None (NOK)
sympy >=0.7.3                     :  None (NOK)
```

**Comment by BjornFJohansson** [comment]
Downgrading spyder-kernels produces the expected result:

![image](https://github.com/spyder-ide/spyder/assets/9726401/3f707021-57b7-4c76-957d-081076016b0d)

**Comment by BjornFJohansson** [comment]
Downgrading to 5.55 works for now.

![image](https://github.com/spyder-ide/spyder/assets/9726401/387d8b40-b34e-43af-8c5e-e10fc3e82f4c)

**Comment by ccordoba12** [comment]
Hey @BjornFJohansson, thanks for reporting. This indeed seems a very serious problem.

What's your Mamba version?

**Comment by BjornFJohansson** [comment]
I use micromamba!
```
(bjorn311) bjorn@bjorn-ThinkPad-T450s:~$ micromamba --version
1.5.8
```

**Comment by ccordoba12** [comment]
> I use micromamba!

Aha, that was the missing bit! We'll address it before releasing 6.0 final (most probably in rc1, not beta3).

**Comment by ccordoba12** [comment]
Notes:

* I think to solve this we need to specify the micromamba args to redirect stdout and stdrerr (if `find_conda` finds micromamba) here:

    https://github.com/spyder-ide/spyder/blob/7783e34d898b686f89f0b3523b2ea565b1372724/spyder/plugins/ipythonconsole/utils/kernelspec.py#L133-L141

    (`--no-capture-output` works with Mamba and Micromamba).

* Those args are listed in this PR: https://github.com/mamba-org/mamba/pull/1438

**Comment by mrclary** [comment]
`--no-capture-output` or `--live-stream` works with `mamba` and `conda`. `micromamba requires `--attach ""`.
