### ISSUE TITLE
Spyder 3.2.6

### ISSUE THREAD

**Issue by Legendery-Wither** [spyder-ide/spyder#22255]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\Anaconda\New folder\A.N\envs\Spyder\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\Anaconda\New folder\A.N\envs\Spyder\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "E:\Anaconda\New folder\A.N\envs\Spyder\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
      File "E:\Anaconda\New folder\A.N\envs\Spyder\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 212, in _handle_execute_reply

Traceback (most recent call last):

Traceback (most recent call last):
  File "E:\Anaconda\New folder\A.N\envs\Spyder\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

Traceback (most recent call last):
  File "E:\Anaconda\New folder\A.N\envs\Spyder\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.13
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.4.0 (OK)
pycodestyle >=2.3:  2.8.0 (OK)
pygments >=2.0   :  2.11.2 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  4.4.0 (OK)
rope >=0.9.4     :  0.22.0 (OK)
jedi >=0.9.0     :  0.18.0 (OK)
nbconvert >=4.0  :  6.0.7 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  5.2.2 (OK)
IPython >=4.0    :  5.8.0 (OK)
pylint >=0.25    :  2.9.6 (OK)

```

**Comment by ccordoba12** [comment]
Hey @Legendery-Wither, thanks for reporting. Unfortunately, Spyder 3 is not maintained anymore, so you need to update to a more recent version. 

This problem is fixed in our latest version available in Anaconda (5.5.1). Please update by closing Spyder, opening the Anaconda Prompt and running there the commands mentioned in [our documentation](http://docs.spyder-ide.org/current/installation.html#updating-with-anaconda).

If that doesn't work, I'm afraid you'll have to remove and reinstall Anaconda.

**Comment by Legendery-Wither** [comment]
But i need a specific version of spyder for a school purpose

**Comment by ccordoba12** [comment]
Are you only using a school computer? I'm asking because if you're able to use a computer at home, you could install a more recent Spyder version there. Of course, there are many changes between versions 3.2.6 and 5.5.1, but the fundamentals are the same.

**Comment by Legendery-Wither** [comment]
But i need version 3.2.6 as for school purpose as they preffered this
version as best for praticising

**Comment by ccordoba12** [comment]
Ok, I understand. Let's see if we can make it work.

Please open the Anaconda Prompt (search for it in the Start menu) and run the following commands there:

    conda activate Spyder
    conda install qtconsole=4.2
    spyder

That should fix the error you posted, but more errors could appear after that. If that's the case, please post them here too.

**Comment by Legendery-Wither** [comment]
Ok, I'll do that.

**Comment by Legendery-Wither** [comment]
That worked but spyder is not opening

**Comment by Legendery-Wither** [comment]
It worked but spyder is not opening

**Comment by ccordoba12** [comment]
Ok, is there any error in the Anaconda Prompt when you start Spyder?

**Comment by Legendery-Wither** [comment]
Not at all! Problem is on Spyder after it was opened

**Comment by ccordoba12** [comment]
Ok, and what's the error?

**Comment by Legendery-Wither** [comment]
Not at all!

**Comment by ccordoba12** [comment]
I don't understand what you mean but I repeat my question: what's the error you are seeing now?

**Comment by Legendery-Wither** [comment]
Nah ..leave it ...I have uninstalled and installed latest version...I was
irritated and got mad so I uninstalled...Thank you for your cooperation 😊😊

**Comment by ccordoba12** [comment]
Ok, that's really good! Thanks for letting us know about it.
