### ISSUE TITLE
IPython does not work with brewed or virtualenv Python(s) in MacOSX

### ISSUE THREAD

**Issue by santjaqo** [spyder-ide/spyder#2227]
I am using a brewed 2.7 Python in Yosemite. I installed the new Spyder 2.3.3 version from the github dmg. I cannot use IPython in Spyder when I point to the executable of the brewed Python in Preferences>Console>Advanced Settings>Python executable. The following is the path I am using:   

/usr/local/bin/python 

Pointing to an activated virtualenv Python executable does not work either. The IPython console does not start. In both cases I receive the following error message instead:

'An error ocurred while starting the kernel'

Could you please help me out to set Spyder to work in my Mac?

**Comment by sessionstart** [comment]
The solution is?

**Comment by ccordoba12** [comment]
If you're using Spyder 3.0, you need to install `ipykernel` in your virtualenv.
