### ISSUE TITLE
Open File / File explorer does not show the files selected in the filter

### ISSUE THREAD

**Issue by mluerig** [spyder-ide/spyder#22272]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

File explorer wont show the files I selected in the file filter - even with an empty filter.

### What steps reproduce the problem?

1. Go to Preferences > Files
2. Edit the filter 
3. Click on Open File

### What is the expected output? What do you see instead?

I don't see any files (except for some reason it just shows R scripts), just folders. Only when I click "Show all" or "Python" I see the scripts I'm looking for

## Versions

* Spyder version: 5.5.5 / 6-dev
* Python version: 3.9 / 3.10
* Qt version: 
* PyQt version: 
* Operating System name/version: Ubuntu 22.04

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @mluerig thank you for the feedback! Could this be related with #22248 ? We have already merged a fix for it (PR #22270) and will be available in the next Spyder 5.x release (5.5.6).

Let us know if the info above helps!

**Comment by mluerig** [comment]
Hi @dalthviz - it looks like it could be related. I'll try the new release when it's out!

**Comment by dalthviz** [comment]
Hi again @mluerig just in case Spyder 5.5.6 was released. We are still pending do the conda-forge recipe update but you should be able to install it using either pip or the installers: https://github.com/spyder-ide/spyder/releases/tag/v5.5.6

Any feedback is appreciated!
