### ISSUE TITLE
Shortcut to run cells on Mac is not working

### ISSUE THREAD

**Issue by cherlihy** [spyder-ide/spyder#2228]
for running a snipet of code, it seems the mac version is not working. 
ctrl + enter deletes the code in mac. and thats what software suggests. Am I am missing something? or there is not hot key for mac.
Thanks,
C.

**Comment by ccordoba12** [comment]
Please report at least your Spyder version. Besides, what does it mean *what the software suggests*?

**Comment by ccordoba12** [comment]
Another question: have you tried to use `Cmd+Enter` instead of `Ctrl+Enter`?

**Comment by ccordoba12** [comment]
Thanks for reporting. I know what you mean now :-)

I'll fix it in 2.3.5

**Comment by cherlihy** [comment]
Great; thanks !

**Comment by ccordoba12** [comment]
No problem. Just to clarify, now `Ctrl+Enter` works to run cells, but also `Cmd+Enter` does it. I couldn't remove it, hope it's fine for you ;-)

**Comment by jiehu567** [comment]
Hi, Spyder is amazing tool!
I really thank you so much for this tool.
The hot key (shortcut) seems not working on 2.3.8 too, I tried to set and there's options like mod1, mod2, mod3, and key, but each there's only one key and I can not set as "cmd + enter"

How should I set? Tyvm

**Comment by ccordoba12** [comment]
Unfortunately there's no way to change that shortcut to something else. This seems like a regression because I try to set it to be `cmd+enter` in 2.3.5 :-)

I'll see what's happening here ;-)

**Comment by Pseud0n1nja** [comment]
After updating spyder 3.3, cmd +enter stopped working for running the cell where cursor lies, though it works for the selection. Please help. Tried hard coding and what not but nothing works even resetting to defaults several times

**Comment by Pseud0n1nja** [comment]
furthermore cmd+enter highlights the adjacent word

**Comment by jnsebgosselin** [comment]
Please open a new issue about this. Do not forget to include your OS, PyQt, At and Spyder version. Thank you.
