### ISSUE TITLE
Shift+Tab is not present

### ISSUE THREAD

**Issue by Tyrn** [spyder-ide/spyder#2229]
Neither Shift+Tab nor its functionality (show function signature?) is present. In Preferences->Keyboard shortcuts there are just Shift+Ctrl+Tab and Ctrl+Tab, nothing else. Reset to default values applied.

Spyder 2.3.2
Python 3.4.3 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.3 on Linux

**Comment by ccordoba12** [comment]
@Tyrn, there are two things I'd like to say:

1. `Shift+Tab` is not part of `Preferences > Keyboard Shortcurs` because it's a fixed shortcut (i.e. it can't be changed).
2. What's exactly the function of which you can't the signature? 

@blink1073, could you check this one (given that you created the `Shift+Tab` functionality)?

**Comment by blink1073** [comment]
I can confirm that introspection is not working with Spyder 2.3.3 Python 3.4.3 64bit using Anaconda on Linux.  I'll take this one.

**Comment by ccordoba12** [comment]
Great!! Thanks a lot ;-)

**Comment by blink1073** [comment]
It works fine in the latest master using the same setup.

**Comment by blink1073** [comment]
I tested with:

```python
import numpy as np
np.zeros(a,<SHIFT+TAB>)
```

**Comment by ccordoba12** [comment]
I don’t remember to have changed anything about it. Maybe |git bisect| 
(or is it |git blame|?) can help here.

El 10/03/15 a las 10:43, Steven Silvester escribió:

> I tested with:
>
> import  numpyas  np
> np.zeros(a,<SHIFT+TAB>)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/spyder-ide/spyder/issues/2229#issuecomment-78081231>.
>
​

**Comment by blink1073** [comment]
The ability to use Shift+Tab was a PR on Bitbucket and might not have been in the 2.3.2 release. https://bitbucket.org/spyder-ide/spyderlib/pull-request/12/add-ability-to-re-trigger-docstring-while/diff#chg-spyderlib/plugins/inspector.py.

**Comment by ccordoba12** [comment]
Upsy daisy, I didn't remember that ;-) I didn't backport that pull request to the 2.3 branch, so this functionality won't be available until our next major release (i.e. 2.4).

Sorry for directing you in the wrong direction @Tyrn.

**Comment by ccordoba12** [comment]
No, wait. I just saw the Changelog for **2.3.0** and there is a mention to `Shift+Tab`, so if it's not working on 2.3.3 is a regression.

**Comment by ccordoba12** [comment]
Can you confirm @blink1073?

**Comment by blink1073** [comment]
What am I confirming?  It works in the latest master and not in 2.3.3, if that's what you mean.

**Comment by ccordoba12** [comment]
Sorry @blink1073, you're right. I misunderstood you :-)

@Tyrn, you need to press `Shift+Tab` as @blink1073 pointed in an example above, i.e. after a comma or in blank space. That will give the signature again at any moment while writing the args of function or method.
