### ISSUE TITLE
Master has issues when plotting graphs through matplotlib in Python consoles

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2231]
Hi,

I recently downloaded Spyder 2.4.0dev from GitHub and I am seeing the following problem.

import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0,90,10)
y = np.sin(x)
plt.figure()
plt.plot(x,y,'o')
plt.show()

I don't see the plot.  It seems like it never created it.

Best Regards

**Comment by ccordoba12** [comment]
Are you using the Python or the IPython console?

**Comment by s0r2637** [comment]
I am using the Python console.

Srini

**Comment by ccordoba12** [comment]
What platform you're working on? What's your matplotlib backend?

**Comment by s0r2637** [comment]
I am running on Ubuntu 14.04. Matplotlib backend is 1.3.1.

Srini

**Comment by ccordoba12** [comment]
I don't know what can be happening, but please try to use the IPython console instead. It has much better support for matplotlib.

**Comment by s0r2637** [comment]
I wanted to know first if you see the same problem.  Also, Spider 2.2.5
works fine.

Srini

**Comment by ccordoba12** [comment]
Yes, you're right!! This is a real bug :-)

**Comment by s0r2637** [comment]
Hi,

Did you get a chance to figure out the problem?  If not, I wanted to know
if I can install Spyder 2.3.3 from GitHub.  If so, how do I clone Spyder
2.3.3 version in particular?

Best Regards,
Srini

**Comment by ccordoba12** [comment]
git checkout v2.3.3

**Comment by s0r2637** [comment]
Hi Carlos,

Is the problem fixed now?  I have another issue with Spider 2.3.3 and
Matplotlib 1.5.1. When I set pde.set_trace (), I am not able to use
Matplotlib within the Python console inside Spyder.  Is it always meant to
be that way?  Fyi, I am using Ubuntu 14.04 LTS and Python 2.7.6

Srini

Srini

**Comment by ccordoba12** [comment]
Yes, that's an old problem and we haven't found the way to fix it yet.

**Comment by s0r2637** [comment]
I am confused.  Which problem are you talking about?  Is it related problem
I mentioned to you in the previous email?

Srini

**Comment by ccordoba12** [comment]
Not being able to create plots while you're in debugging mode.
