### ISSUE TITLE
Trato de todas las formas de instalar un plugin, pero no se ve en el ide luego de instalarlo,

### ISSUE THREAD

**Issue by hectorgm26** [spyder-ide/spyder#22318]
### What steps will reproduce the problem?

I'm having trouble installing the unit testing plugin for the spyder ide. I install it by pip, and it tells me installation successful, but when I open the ide, it is not seen in the program. It also does not appear in the ide options to enable it. I have the latest version of the IDE, I don't know what else to do

## Versions

* Spyder version: 5.5.5  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.4 (OK)
jsonschema >=3.2.0            :  4.22.0 (OK)
keyring >=17.0.0              :  25.2.1 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.0 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.8 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.3 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0        :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.2.0 (OK)
setuptools >=49.6.0           :  70.0.0 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.2,<2.6.0 :  2.5.2 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.1 (OK)
zmq >=24.0.0                  :  26.0.3 (OK)

# Optional:
cython >=0.21                 :  3.0.10 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12.1 (OK)
```

**Comment by ccordoba12** [comment]
Hola @hectorgm26, gracias por reportar este problema. Lastimosamente no es posible usar Spyder-unittest con nuestro instalador de Windows.

Esto se debe a que nuestro instalador es completamente auto-contenido, por lo que no permite la instalación de ningún otro paquete adicional. Con ello prevenimos que los usuarios puedan alterar los contenidos del instalador, lo que usualmente lleva a que Spyder deje de funcionar correctamente. Esa es la experiencia de la mayoría de los usuarios en Anaconda u otros métodos de instalación, por lo que decidimos evitarla en nuestros instaladores.

Sin embargo, estamos trabajando para que en el futuro sea posible instalar plugins de Spyder (como Spyder-unittest o Spyder-notebook) en el instalador. Esa funcionalidad debería estar disponible en Spyder 6.1 o a más tardar 6.2, que serán lanzados el próximo año.

**Comment by hectorgm26** [comment]
But I was able to install it by pip install at the time. Only it never worked, and I realized it was because it was installed in Python 3.8. However, I use the current version 3.12. I actually changed the interpretation of python in the spyder ide, I tried uninstalling the plugin to install it again. But it always gave an error and the ide stuck. I had to delete the folder where the plugin is installed, then uninstall the ide, restart spyder to its default values, and despite having done all that, I install it again, now, making sure I install it in python 3.12, I get the message existing installation pip, I restart spyder, but I don't see the unit test plugin installed, or anything.

**Comment by ccordoba12** [comment]
> But I was able to install it by pip install at the time. Only it never worked, and I realized it was because it was installed in Python 3.8. However, I use the current version 3.12

The problem is Spyder can't use plugins installed in environments different from the one in which it's installed. It can use any other package through the IPython console, but not Spyder plugins.

As I said, we're aware of this limitation and are working to solve it in the future. In the meantime, there's nothing you can do about it, sorry.

(By the way, I speak Spanish natively, my previous message was not auto-translated by an AI agent).
