### ISSUE TITLE
Spyder silent installer not working

### ISSUE THREAD

**Issue by zarif98** [spyder-ide/spyder#22329]
It seems like the directory input does not work at all. It makes an install log and installs the application in another directory anyways. On another machine, it seems to install it really fast but not in the directory that I requested.

Is there a reason why it's doing this?
![image (8)](https://github.com/user-attachments/assets/e69b700d-ac4f-45d5-8e9d-3803b316625d)

**Comment by ccordoba12** [comment]
Hey @zarif98, thanks for reporting.

@dalthviz, can you give @zarif98 an additional hand with this? Thanks!

**Comment by dalthviz** [comment]
@zarif98 seems like you are trying to use the flags with a Spyder 6 installer? The thing is that the Spyder 6 installer, although I think is build using NSIS, it's generated via a different method than the Spyder 5 installers. Spyder 6 installers are generated using a package called `constructor`. A quick search over their issue tracker shows that they have some issues with the `/D` and `/S` flags. For more info you can check: https://github.com/conda/constructor/issues/813

Let us know if the info above helps!

**Comment by ccordoba12** [comment]
@mrclary, could you take a look at this issue to see if we can submit a PR to Constructor to fix this problem?

This is important because many organizations use our installer in batch mode to easily install Spyder in multiple computers.

**Comment by mrclary** [comment]
@zarif98, can you copy and paste the contents of the resulting `install.log` to this issue?
`/S /D=D:\Spyder\6.0` should work. I suspect that either `D:\Spyder\6.0` is not an empty directory or the installer does not like installing to another drive.

For example, the following works as expected for me with our latest 6.0.0rc1 release:
```
C:\Users\rclary\Downloads\Spyder-Windows-x86_64.exe /S /D=C:\Users\rclary\Desktop\spyder-6
```
Note that the `spyder-6` directory _does not exist_ prior to this execution. The installer will create this directory. If the target directory already exists and is not empty, then you will get an `install.log`. For example, when I tried the following
```
C:\Users\rclary\Downloads\Spyder-Windows-x86_64.exe /S /D=C:\Users\rclary\Desktop
```
I got the following result:
<details><summary>install.log</summary>

```bash=
Call: 3115
SetFlag: 13=6
SetFlag: 2=0
Delete: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp"
CreateDirectory: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp" (0)
CreateDirectory: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp" created
SetFlag: 2=0
Call: 847
Jump: 864
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
Jump: 1357
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 12=256
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll"
File: wrote 12288 to "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll"
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll"
File: skipped: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll" (overwriteflag=1)
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll"
File: skipped: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll" (overwriteflag=1)
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll"
File: skipped: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll" (overwriteflag=1)
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll"
File: wrote 14848 to "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll"
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll"
File: skipped: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll" (overwriteflag=1)
Jump: 1607
Jump: 1617
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll"
File: skipped: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll" (overwriteflag=1)
Call: 3115
SetFlag: 13=6
File: overwriteflag=1, allowskipfilesflag=0, name="C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll"
File: skipped: "C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll" (overwriteflag=1)
Call: 1211
settings logging to 1
logging set to 1
SetFlag: 1=0
Jump: 1223
Call: 153
Jump: 167
Call: 843
settings logging to 1
logging set to 1
SetFlag: 2=0
Call: 847
Jump: 864
Jump: 881
Call: 885
SetFlag: 2=0
SetFlag: 2=1
Jump: 975
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
Jump: 1039
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
SetFlag: 2=0
Call: 885
SetFlag: 2=0
SetFlag: 2=1
Section: "Install"
settings logging to 1
logging set to 1
Call: 1721
settings logging to 1
logging set to 1
Jump: 1725
Jump: 1725
DetailPrint: ::error:: Directory 'C:\Users\rclary\Desktop' is not empty, please choose a different location.
MessageBox: 2097200,"Directory 'C:\Users\rclary\Desktop' is not empty,
please choose a different location."
Aborting: ""
Delete: DeleteFile("C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\System.dll")
Delete: DeleteFile("C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\UAC.dll")
RMDir: RemoveDirectory("C:\Users\rclary\AppData\Local\Temp\nsj50A2.tmp\")
```
</details>

 Note the `::error::` near the end of the log.

**Comment by zarif98** [comment]
Hmmm I'm not generating an install.log file and I ensured that the folder was not there when I did the install.

![image](https://github.com/user-attachments/assets/ad259aae-0c19-43ad-96ee-bde275607988)

**Comment by mrclary** [comment]
> Hmmm I'm not generating an install.log file and I ensured that the folder was not there when I did the install.

In this case you are using our Spyder 5 installer. This is completely different from our Spyder 6 installer, which you used in the original post. Do you want to install Spyder 5 or Sypder 6? Note that our Spyder 6 installer, while available, has not yet been officially released; we've only published a release candidate 6.0.0rc1.

**Comment by mrclary** [comment]
> Hmmm I'm not generating an install.log file and I ensured that the folder was not there when I did the install.

It looks like the install of Spyder 5 worked as expected, by the way.

**Comment by zarif98** [comment]
Sorry for the late response @mrclary but I didn't realize I was using Spyder 5. Is there to have the silent install working with Spyder 5 then? I just assumed Spyder 6 was already readily available from the Spyder ide website.

**Comment by mrclary** [comment]
> Sorry for the late response @mrclary but I didn't realize I was using Spyder 5. Is there to have the silent install working with Spyder 5 then?

```
"Spyder_64bit_full.exe" /S
```
Silent installation worked for me. However, it will install for all users. I could not get it to install into an arbitrary directory in silent mode, however; it seems `/D=C:\Spyder` is ignored.

**Comment by zarif98** [comment]
Hmmm could that be resolved? @mrclary

**Comment by mrclary** [comment]
Unfortunately, I don't know anything about the NSIS installer for Windows that we use for Spyder 5. @ccordoba12 @dalthviz, is this something that can be resolved?

**Comment by dalthviz** [comment]
So I would say as a summary that:

* When using Spyder 5 installers (the executable file should named something like `Spyder_64bit_full.exe`) for silent install you can use `/S`. If you need to setup the installation path you need to use `/INSTDIR=<path where things should be installed>`. Also, here some issues where the flags the installer can use were discused: https://github.com/spyder-ide/spyder/issues/22260 and https://github.com/spyder-ide/spyder/issues/21841 and further info about the flags the installer accepts at https://github.com/spyder-ide/spyder/blob/5.x/installers/Windows/README.md

* When using Spyder 6 installers (the executable file is named with something like `Spyder-Windows-x86_64.exe`) for silent installs you can use `/S`. If you need to setup the installation path you can use `/D=<path where things should be installed>`. However, you need to take into account that the path where things will be installed shouldn't exists otherwise the installation will fail. This installation fail then can happen if you try to install multiple times the installer with the `/S` flag (since you are trying to install using the same default installation path) or if you try to install passing the same path with the `/D` flag multiple times.

Let us know if the info above helps @zarif98 !

**Comment by mrclary** [comment]
Thanks @dalthviz!

**Comment by mrclary** [comment]
I'm closing this issue, assuming that @dalthviz's comment resolved the issue. @zarif98, if this is not the case and you have further information to report, please reopen.
