### ISSUE TITLE
Editor raises TypeError

### ISSUE THREAD

**Issue by sbyrnes321** [spyder-ide/spyder#2232]
This error occurs in the Ubuntu 14.10 repository versions of Spyder, both Python 2 and Python 3, i.e.

Spyder version 2.3.0
Python 3.4.2 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.2 on Linux --- or --- Python 2.7.8 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.2 on Linux

Steps to reproduce:

* Open a blank file in the editor
* Copy the following two lines into the editor
```
from scipy.interpolate import RegularGridInterpolator
fn = RegularGridInterpolator()
```
* On the next line, type ``fn()``. When I type the third character (open parenthesis), the internal console pops up with the following error:
```
>>> Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/editor.py", line 433, in show_object_info
    signature = getsignaturefromtext(doc_text, obj_name)
  File "/usr/lib/python3/dist-packages/spyderlib/utils/dochelpers.py", line 178, in getsignaturefromtext
    sigs_1 = re.findall(oneline_re + '|' + multiline_re, text)
  File "/usr/lib/python3.4/re.py", line 206, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

This might be related to #1722 but doesn't seem to be related to the Object inspector ... at least it didn't go away when I told the Object Inspector to ignore the editor in preferences.

**Comment by ccordoba12** [comment]
I think this was fixed in 2.3.1 or 2.3.2. Please update and test again.

**Comment by ccordoba12** [comment]
I tested your example and this is not a problem in 2.3.3.

**Comment by sbyrnes321** [comment]
Thank you!!

**Comment by ccordoba12** [comment]
You're welcome :-)
