### ISSUE TITLE
Object Inspector is not showing "No documentation available" for objects without docstring

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2234]
It seems Jedi returns `<no docstring>` instead of an empty string for objects without docstring. This prevents the Object Inspector to show the *No documentation available* warning page.

**Comment by ccordoba12** [comment]
@blink1073, can you take a look at it?

**Comment by blink1073** [comment]
Here's what I see (which was part of my last PR on Bitbucket), which I think is preferable since it at least shows some information about the function.

![screenshot from 2015-03-13 08 35 55](https://cloud.githubusercontent.com/assets/2096628/6639240/fed9bd40-c95b-11e4-98eb-6afa254acb5d.png)

**Comment by Nodd** [comment]
Maybe ```No documentation available.``` would be better than ```<no docstring>``` which looks too computer-y. A full sentence (even without a verb) is nicer than an html opening tag...

**Comment by blink1073** [comment]
<fine>
