### ISSUE TITLE
There are different outcomes between "Run current cell" and "Run selection or current line."

### ISSUE THREAD

**Issue by Ppop799** [spyder-ide/spyder#22340]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
There are different outcomes between "Run current cell" and "Run selection or current line."

### What steps reproduce the problem?

1. 
![螢幕擷取畫面 2024-08-10 154213](https://github.com/user-attachments/assets/33cbfae9-acf9-4d59-a4f0-2eac585e4fce)

2. 
3. 

### What is the expected output? What do you see instead?
![螢幕擷取畫面 2024-08-10 154238](https://github.com/user-attachments/assets/4afa9319-1fbb-4945-9842-f1dbf43fb8fd)
![螢幕擷取畫面 2024-08-10 154315](https://github.com/user-attachments/assets/45f1ea9a-c0a9-4081-b774-b582ad8b3215)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by dalthviz** [comment]
Hi @Ppop799 the behavior you are seeing is expected. There a couple fo things to take into account but basically when running things like a cell definiton you run the whole code inside it while when you run the current line or selection only that gets run. However, an important thing you need to take into account when using both ways of running things is that at the end both are affecting the same variables namespace. So, if you keep running things over the same console (unless you create a new console, reset the console variables or restart the console kernel) is like you are running code secuencialy. In other words, running first the cell and then the `num1.index(64)` line via the run selection function is equivalent to running in a single cell the following code:

```python
num1 = [1,2,3,4,5,6,7]
num2 = [9,64,11,12,13]

num1.append(77)
print(num1)

num1.extend(num2)
print(num1)

num1.index(64)
print(num1.index(64))

num1.insert(6, 888)
print(num1)

num1.pop()
print(num1)

num1.index(64)
print(num1.index(64))
```  

![image](https://github.com/user-attachments/assets/781adbda-c1d0-4692-90d5-498f8d1e8bcc)

For more info about cell and selection run context/functionality you can check https://docs.spyder-ide.org/current/panes/editor.html#running-code

Let is know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
