### ISSUE TITLE
Error when running Spyder with Python 2 and PyQt5

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#2235]
My PyCharm complains loudly about [this](https://github.com/spyder-ide/spyder/blob/master/spyderlib/plugins/__init__.py#L164) line.

I don't have PyQt5 so this doesn't affect me but I thought I'd nevertheless bring it to attention.

**Comment by ccordoba12** [comment]
What does PyCharm says about it? That is not Python 3 compatible?

**Comment by ccordoba12** [comment]
Any updates on this one?

**Comment by Nodd** [comment]
Yes, super without arguments is not supported in python2. I found no webpage explicitly stating that it has not been implemented in python2, but it can be deduced from these links:
https://docs.python.org/3.0/whatsnew/3.0.html#builtins
https://www.python.org/dev/peps/pep-3135/
https://docs.python.org/3/library/functions.html#super
https://docs.python.org/2.7/library/functions.html#super

Finally, running this in python3 works but fails in python2:
```
class A(object):
    def __init__(self):
        super().__init__()
A()
```
I guess that so far, PyQt5 users also use python3...

**Comment by ccordoba12** [comment]
We only have been able to run Spyder with PyQt5 under Python 3, but this should be fixed for beta1.

**Comment by ccordoba12** [comment]
@Nodd, can you help me to solve this one? Given that you're able to run Spyder with PyQt5 and Python 2, I'd really appreciate it.

**Comment by ccordoba12** [comment]
@Nodd, I figured it out at the end. You were right, it was easy enough :-)

**Comment by Nodd** [comment]
I'm too late !
