### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Rimpelio** [spyder-ide/spyder#22375]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I can't open the spyder program, the truth is that it's been 3 hours and it's a little frustrating, I had an environment to run a code that I had on another computer, it should be noted that the code ran fine on the other computer, the code entered a bug, force close and now I can't open it.

**Comment by ccordoba12** [comment]
Hey @Rimpelio, thanks for reporting. It seems you're using a very old Spyder version (3.2 or 3.3), which is not supported anymore. Please update to our latest version (5.5.1 in Anaconda, 5.5.5 outside it) and try again.

Let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
