### ISSUE TITLE
Check reason why Sphinx upper constraint is needed to make the splash screen work on Windows

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#22374]
## Problem Description

Follow up for #22353 and #22370. It could be nice to properly determine why using sphinx >=7.4.0 causes troubles with the splash screen showing its image on Windows and hopefully remove the upper constraint

**Comment by mrclary** [comment]
It seems that sphinx was not the only factor with the OP. pillow must also be installed for the splash screen to render properly. I don't understand this.

So installing Spyder from the installer, with `sphinx < 7.4.0` and `pillow` included via `matplotlib-base`, there is no issue.

However, installing Spyder by itself, e.g. `conda create -n test python=3.11 spyder=6.0.0.rc2`, results in the bad splash screen.

The splash screen renders correctly:
* If the environment is activated first, e.g. `conda run -n test spyder`. Shortcuts do not activate the environment, as doing so creates a flashing cmd window. @jaimergp and I are unable to fix this.
* OR if the environment `Library\bin` is in the `PATH` environment variable. This is added to `PATH` when the environment is activated.
* OR if `pillow` is installed and `sphinx < 7.4.0`.

I suspect that Qt requires something in `Library\bin` and that the combination of `sphinx < 7.4.0` and `pillow` either obviates the need for whatever is in `Library\bin` or alters Qt's search paths to include `Library\bin`.

**Comment by ccordoba12** [comment]
I think this issue will affect mainly our Windows conda-forge users because Anaconda can take several months to update to 6.0. That's why it doesn't seem so serious to me (we don't have many installations through conda-forge).

> OR if the environment Library\bin is in the PATH environment variable. This is added to PATH when the environment is activated.

Is it not possible to add directories to `PATH` in a shortcut? For that perhaps we could use a batch/ps1 script instead of calling a Python script directly.

> I suspect that Qt requires something in Library\bin and that the combination of sphinx < 7.4.0 and pillow either obviates the need for whatever is in Library\bin or alters Qt's search paths to include Library\bin.

Yeah, most probably Qt is linked against a third-party library necessary to render the splash screen. And those libraries are placed in `Library\bin` by conda, but not added by default to PATH by Windows, hence the need to do that manually or activate the env.

**Comment by ccordoba12** [comment]
> Is it not possible to add directories to PATH in a shortcut? For that perhaps we could use a batch/ps1 script instead of calling a Python script directly.

Or we could `Library\bin` to `os.environ` in that script too.

**Comment by mrclary** [comment]
> Is it not possible to add directories to `PATH` in a shortcut? For that perhaps we could use a batch/ps1 script instead of calling a Python script directly.

Yes, this is what activating the environment does. The issue with that is any batch script in the shortcut results in the flashing cmd window.

> Or we could add `Library\bin` to `os.environ` in that script too.

We could explore this as well, but perhaps adding it in our `start.py` for Windows+conda if it's not there already.

**Comment by ccordoba12** [comment]
> We could explore this as well, but perhaps adding it in our start.py for Windows+conda if it's not there already.

That's a good idea too. We could check if `sys.executable` is in a conda env and then add `Library\bin` to PATH if it's not already there.

**Comment by mrclary** [comment]
It works! #22404

**Comment by mrclary** [comment]
I would leave this issue open, even after merging #22404, until we determine what new lower and upper (if any) constraints we want for `sphinx`

**Comment by ccordoba12** [comment]
> It works! https://github.com/spyder-ide/spyder/pull/22404

That's great, thanks @mrclary! Do you want to include that fix in 6.0.0?

> I would leave this issue open, even after merging https://github.com/spyder-ide/spyder/pull/22404, until we determine what new lower and upper (if any) constraints we want for sphinx

But I thought an upper constraint on Sphinx was not necessary if `Library\bin` is in PATH, according to what you said above:

> > OR if the environment Library\bin is in the PATH environment variable. This is added to PATH when the environment is activated.

**Comment by mrclary** [comment]
> That's great, thanks @mrclary! Do you want to include that fix in 6.0.0?

I would recommend including it in 6.0.0 so that we have one less issue potentially opened by users. But it's up to you.

> But I thought an upper constraint on Sphinx was not necessary if `Library\bin` is in PATH, according to what you said above:

That is correct. The upper limit on `sphinx` is not needed anymore. I just didn't know how you wanted to factor this. I could revert the upper limit in #22404, or we could do so when we reassess the lower constraint and group all changes to sphinx constraints into one PR. I'm happy to do whatever you think is best.

**Comment by ccordoba12** [comment]
> I could revert the upper limit in https://github.com/spyder-ide/spyder/pull/22404

Yeah, please do that. If the upper constraint is not really necessary, we can remove it before the 6.0.0 release.

> we could do so when we reassess the lower constraint and group all changes to sphinx constraints into one PR. I'm happy to do whatever you think is best.

I think it's better to leave that for later because it's not critical (however, the upper constraint would limit the available Sphinx version in all envs where Spyder is installed).

**Comment by mrclary** [comment]
> Yeah, please do that. If the upper constraint is not really necessary, we can remove it before the 6.0.0 release.

Done.
