### ISSUE TITLE
Not able to push another python file in the same directory to Github in Pycharm

### ISSUE THREAD

**Issue by MoodJyothirmai** [spyder-ide/spyder#22373]
<img width="343" alt="Git Push" src="https://github.com/user-attachments/assets/87918b75-d290-45ce-a9f2-6c478014ef8a">

Process I have followed are as follows:
Step 1: Created a parent directory Day1_08082024 under src directory and added one Python file named Lab_001.py
Step 2: Next, Shared the project on Github successfully
Step 3: Created one more Python file in the same directory Day1_08082024 with named Lab_002.py
Step 4: Not able to push to Github

Any solution would be helpful. Thanks!

**Comment by dalthviz** [comment]
Hi @MoodJyothirmai are you using Spyder at some point in your workflow? From the info provided seems like you are using Pycharm so I would say there is not much we can do to help you sorry :/

**Comment by dalthviz** [comment]
Closing due to lack of response and since it is not related with Spyder
