### ISSUE TITLE
Preserve size in status bar widgets

### ISSUE THREAD

**Issue by RafiKueng** [spyder-ide/spyder#2238]
this is only a very minor visual bug, that is most probably not important for other people, but it really distracts me..

could you make the status bar (bottom bar) have fixed field sizes? my cpu usage usually hovers around 8-12%, always jumping between one and two digit, making the whole status bar move a little bit to the left.. and catching my attention.. changing numbers are ok, shifting layout is to much..

Since it probably just me, I'll try to have a look at it if I got some more time..

**Comment by ccordoba12** [comment]
If you could look at this one, the better ;-)

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, please work on this one.

**Comment by goanpeca** [comment]
Maybe this is a good opportunity to implement something like what VS code does in the status bar.

Clicking on this widgets allows to modify the setting they display.

Also they are in general too big, so we could try to also reduce the size and make them more compact.

<img width="1440" alt="screen shot 2017-01-16 at 12 44 43 pm" src="https://cloud.githubusercontent.com/assets/3627835/21993587/948e6c36-dbe9-11e6-9773-8c1addeff0cd.png">
