### ISSUE TITLE
SyntaxErrors with Python 3.2

### ISSUE THREAD

**Issue by Arfrever** [spyder-ide/spyder#2239]
```
$ python3.2 -m compileall -fq spyderlib spyderplugins
*** Error compiling 'spyderlib/plugins/layoutdialog.py'...
  File "spyderlib/plugins/layoutdialog.py", line 155
    if to_text_string(text) == u'':
                                 ^
SyntaxError: invalid syntax

*** Error compiling 'spyderlib/pygments_patch.py'...
  File "spyderlib/pygments_patch.py", line 72
    yield pos, Text, u'\n'
                         ^
SyntaxError: invalid syntax

*** Error compiling 'spyderplugins/widgets/condapackagesgui.py'...
  File "spyderplugins/widgets/condapackagesgui.py", line 53
    def sort_versions(versions=(), reverse=False, sep=u'.'):
                                                         ^
SyntaxError: invalid syntax

```

**Comment by ccordoba12** [comment]
Are these all errors you found?

**Comment by blink1073** [comment]
The unicode literal was added in 3.3:  https://www.python.org/dev/peps/pep-0414/

**Comment by Nodd** [comment]
The first one should be ``` if not to_text_string(text):```

**Comment by ccordoba12** [comment]
I'll fix the error in `pygments_patch` for *2.3.4*. The others were introduced by @goanpeca.

But I think we should just drop support for 3.2 for *2.4* because very few people are running Spyder there (that I know of).

@spyder-ide/core-developers, what do you think?

**Comment by blink1073** [comment]
I say dump it!  Matplotlib dropped 3.2 support recently.  I've been trying to get scikit-image to drop it...

**Comment by goanpeca** [comment]
I am :+1: on dumping it!

**Comment by goanpeca** [comment]
But I will fix it nevertheless. The package manager has some issues right now besides that, and will get fixed soon. I am normally only testin py2.7 and py3.4 on linux and 3.3 on win (what i can get install with anaconda)

**Comment by stonebig** [comment]
anaconda can't get install 3.4 on win ?

**Comment by goanpeca** [comment]
I rephrase... I normally use: Lin (2.7, 3.4) and on win (2.7, 3.3, 3.4)

**Comment by ccordoba12** [comment]
@goanpeca, don't worry about it. I'm going to follow @blink1073 advice and drop support for Python 3.2 (and 2.6 too) in our next major release. Since your contributions are planned for that release, you don't need to fix those `u'` cases.

It doesn't make sense to try to support versions which we are not able to test easily, but thanks @Arfrever for letting us know about the problem in `pygments_patch`

**Comment by Nodd** [comment]
:+1: for dropping 2.6 and 3.2. It is coherent with the compatibility with Qt5, new-types signals... Spyder is getting some fresh air !
