### ISSUE TITLE
importing a newly installed module in updated Spyder/Python

### ISSUE THREAD

**Issue by JackStBees** [spyder-ide/spyder#22398]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have updated to Spyder 5.5.6 and "import serial" gives the ModuleNotFoundError message.
I've reinstalled pyserial with "conda install pyserial" from the Anaconda Prompt terminal and tried to follow the help in the wiki "Working with packages and environments in Spyder" (The most common problem: Using newly-installed packages inside Spyder), but no luck.

I think there might be a problem with my environment.  How do I know what environment pyserial was installed in?

### What steps reproduce the problem?

1.  
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback
import serial
Traceback (most recent call last):

  Cell In[1], line 1
    import serial

ModuleNotFoundError: No module named 'serial'


Important
It seems you're trying to use a module that doesn't come with our installer. Check this FAQ in our docs to learn how to do this.
 

```

## Versions

* Spyder version:  5.5.6
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt version: 5.15.11
* Operating System name/version: Windows 10 (AMD64)

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
importlib_metadata >=4.6.0    :  8.4.0 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.1.0 (OK)
jsonschema >=3.2.0            :  4.23.0 (OK)
keyring >=17.0.0              :  25.3.0 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  6.0.0 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.6 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0        :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.3.0 (OK)
setuptools >=49.6.0           :  73.0.1 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.2,<2.6.0 :  2.5.2 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.2 (OK)
zmq >=24.0.0                  :  26.2.0 (OK)

# Optional:
cython >=0.21                 :  3.0.11 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.13.2 (OK)

```

**Comment by dalthviz** [comment]
Hi @JackStBees seems like you are using Spyder from the standalone installers right? If that is the case, you will need to set as Spyder interpreter the one of the env where you installed `pyserial`. For more info, you can check the FAQ entry `How do I install Python packages to use within Spyder if I downloaded Spyder from the standalone installers?` over the Spyder doc page: https://docs.spyder-ide.org/current/faq.html#using-spyder

Let us know if the info above helps!

**Comment by JackStBees** [comment]
Thanks for your very fast response.
The problem was to do with the conda environments, which I did not understand at all.
I got to the bottom of it with help from https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/02-working-with-environments/index.html, which was very helpful.
It's all working now.
Regards...   Jack
________________________________
