### ISSUE TITLE
The text "Run code" does not fit in the button (partially visible) at the Step №3 "IPython Console" of Introduction tour

### ISSUE THREAD

**Issue by 0bs01ete** [spyder-ide/spyder#22409]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The text "Run code" does not fit in the button (partially visible) at the **Step №3 "IPython Console"** of Introduction tour (**Help** --> **Show tour**).
After button was clicked the text become is fully visible.

### What steps reproduce the problem?

1. After installation and the first launch of the program there is a modal window with Introduction tour
2. Go to **_Step №3_** of Introduction tour

OR

1. Run the program
2. Choose **Help** --> **_Show tour_**
3. Go to **_Step №3_** of Introduction tour

### What is the expected output? What do you see instead?
**Expected Result:** the text of the button **_Run code_** fits within the button
![image](https://github.com/user-attachments/assets/5298ee1f-676a-4d01-bfef-370d62b14e19)

**Actual Result:** the text does not fit in the button
![image](https://github.com/user-attachments/assets/97a182ab-c14d-4466-a2e6-d128df152952)

## Versions

* **Spyder version:** 5.5.1
* **Python version:** 3.12.3
* **Qt version:** 5.15.13
* **PyQt version:** 5.15.10
* **Operating System name/version:** Kubuntu 24.04.1 LTS x86_64

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
intervaltree >=3.0.2             :  3.0.2 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  0.10.0 (OK)
jsonschema >=3.2.0               :  4.10.3 (OK)
keyring >=17.0.0                 :  24.3.1 (OK)
nbconvert >=4.0                  :  6.5.3 (OK)
numpydoc >=0.6.0                 :  1.6.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.8 (OK)
pygments >=2.0                   :  2.17.2 (OK)
pylint >=2.5.0,<3.1              :  3.0.3 (OK)
pylint_venv >=3.0.2              :  3.0.2 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.10.0,<1.11.0           :  1.10.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.2 (OK)
qtawesome >=1.2.1                :  1.2.3 (OK)
qtconsole >=5.5.1,<5.6.0         :  5.5.1 (OK)
qtpy >=2.1.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.2.0 (OK)
setuptools >=49.6.0              :  68.1.2 (OK)
sphinx >=0.6.6                   :  7.2.6 (OK)
spyder_kernels >=2.5.0,<2.6.0    :  2.5.0 (OK)
textdistance >=4.2.0             :  4.6.0 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  3.0.0 (OK)
xdg >=0.26                       :  0.28 (OK)
zmq >=22.1.0                     :  24.0.1 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  3.6.3 (OK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  None (NOK)
scipy >=0.17.0                   :  1.11.4 (OK)
sympy >=0.7.3                    :  1.12 (OK)
```

**Comment by dalthviz** [comment]
Hi @0bs01ete thank you for the report! I was unable to reproduce this (however I used Windows and Spyder 6.0.2 installed from our installers to check):

![image](https://github.com/user-attachments/assets/4626a7ca-e1b4-4f60-baf3-45cfd38ff301)
![image](https://github.com/user-attachments/assets/f3f69bb4-974a-4be1-b71e-cc37a0c22b68)

Could it be possible for you to check if this is still happening with the latest release (Spyder 6.0.2)? You could do the check installing our Linux installer available over the Spyder GitHub release page: https://github.com/spyder-ide/spyder/releases/latest

Let us know if using a more recent Spyder version helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
