### ISSUE TITLE
How do we add a "Ctrl+enter" shortcut for F9 (W7 - anaconda)

### ISSUE THREAD

**Issue by mayouf** [spyder-ide/spyder#2240]
Any idea how to set "Ctrl+enter" instead of F9 to run the current line cursor ?

When I try to set it in "preference"

**Comment by mayouf** [comment]
When I try to set it, it just proposes the Alt, Shift and Ctrl keys separately for shorcuts.

To replace F9, the same, only one key is proposed ? What if I want to set a shortcut like this: Ctrl+A+Enter" ???

Sorry if my question seems stupid, It's been a while im trying to figure it out !!!

thanks,

![spyder shorcut](https://cloud.githubusercontent.com/assets/5865600/6643722/faecca6c-c9ae-11e4-8e51-440575b3d195.png)

**Comment by ccordoba12** [comment]
This is not possible. `Ctrl+Enter` is a fixed shortcut, and it's used to evaluate a cell, which is a portion of a file defined between comments of the form `#%%`. Something like

    #%%
    print("a")

    #%%
