### ISSUE TITLE
autocompletion editor

### ISSUE THREAD

**Issue by mayouf** [spyder-ide/spyder#2241]
Can someone help me pls ??

Is it possible to use the autocompletion in the editor ? the console works fine.

Spyder is amazing, and im sure this functionality is here but i cant find it !!

![autocompletion here](https://cloud.githubusercontent.com/assets/5865600/6644336/49ffc902-c9b3-11e4-83e8-1082042b8bd5.png)

**Comment by blink1073** [comment]
Hi @mayouf.  The editor does not know about variables in the console.  You must define the variable in the editor to get completion on it.

**Comment by ccordoba12** [comment]
Of course. If you write

    a = "kjb"

in the Editor, before writing

print a.

you'll get the same completions as in the console.
