### ISSUE TITLE
Windows Installer link broken in webpage

### ISSUE THREAD

**Issue by kelseymclagan** [spyder-ide/spyder#22417]
Went to download using the Windows installer and I am getting a 404 error. is the link broken now?

**Comment by ccordoba12** [comment]
Hey @kelseymclagan, thanks for reporting. We're going to replace our current webpage with a new, completely redisgned one in a few hours. That page will have the right links to download Spyder for all operating systems.

Let us know if it works for you later today or tomorrow. In the meantime you can download Spyder from here: https://github.com/spyder-ide/spyder/releases/tag/v6.0.0

**Comment by ccordoba12** [comment]
This is fixed now, so I'm going to close this issue.
