### ISSUE TITLE
Traceback color handling and definition need improvements

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#22412]
## Problem Description

Seems like the IPython console traceback color got more difficult to read due to most probably the changes done over https://github.com/jupyter/qtconsole/pull/608 or https://github.com/jupyter/qtconsole/pull/611 Further work to properly pass a correct syntax style could be needed over the Spyder side and/or also be able to change the bold format vs bright color interpretation ANSI code interpretation.

### What is the expected output? What do you see instead?

Spyder 5 (5.5.6)

![image](https://github.com/user-attachments/assets/62575ec1-ce0a-49ee-b8fa-6f28e478bfe7)

Spyder 6 (6.0.0rc3 installer generated as part of Spyder 6.0.0 release step)

![image](https://github.com/user-attachments/assets/4029c42f-0f2a-4bad-838e-d102e0ec9456)

## Versions

* Spyder version: 6.0.0rc3.dev73  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by Klevente12** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
