### ISSUE TITLE
Installers for 6.0.0 release come with 6.0.0rc2

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#22416]
## Problem Description

Tried installing Spyder from the generated Windows installer from the 6.0.0 release but seems like when building it the Spyder version that ends up as part of the spyder-runtime env is 6.0.0rc2

Checking the action that generated the installers I see that the env ends up solving 6.0.0rc2 although `spyder=6.0.0` is being requested:

* Windows:
   - https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592842459#step:14:136
   - https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592842459#step:14:429 
* Linux:
   - https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592842226#step:14:147
   - https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592842226#step:14:522
* macOS:
   - https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592841911#step:14:137
   - https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592841911#step:14:445

Maybe is related with having still having `conda-forge/label/spyder_dev` and `conda-forge/label/spyder_kernels_rc` as channels (https://github.com/spyder-ide/spyder/actions/runs/10677525658/job/29592842459#step:7:7)? 🤔 

### What is the expected output? What do you see instead?

See over the about dialog that spyder 6.0.0 was installed instead I see 6.0.0rc2

**Comment by ccordoba12** [comment]
This is really serious and I was afraid something like that could happen because we haven't run the installer workflows with a stable version.

@mrclary, could you take a look at this asap?

**Comment by mrclary** [comment]
I'll replace release assets asap with those from a patch on my fork. Then I'll submit a PR for a permanent fix.

**Comment by ccordoba12** [comment]
Great! Thanks a lot @mrclary!

> Then I'll submit a PR for a permanent fix.

Ok, please remember to submit that PR against `master` and not `6.x` (from now on we'll do backports and not forward-ports between branches).
