### ISSUE TITLE
Spyder 6: Debugging buttons missing from the main toolbar

### ISSUE THREAD

**Issue by ensbana** [spyder-ide/spyder#22434]
Love the new design in Spyder 6! However I'd like to have the debugging buttons, e.g. "Run current line", "Step into function", "Run until next breakpoint", back on the toolbar. 

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
This is more like a feature request. I'd like to have the debugging buttons, e.g. "Run current line", "Step into function", "Run until next breakpoint", back on the toolbar. 

### What steps reproduce the problem?

1. Installing Spyder 6 
2. Launch Spyder 6
3. Notice the buttons in question are missing from the toolbar

### What is the expected output? What do you see instead?

ibid.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 6.0.0
* Python version: 3.11.9
* Qt version: 5.15.8
* PyQt version: 5.15.9
* Operating System name/version: Windows 10 (AMD64)

### Dependencies

```
PASTE DEPENDENCIES HERE
```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.4.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.3.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  73.0.1 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.1 (OK)
yarl >=1.9.4                     :  1.9.7 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.0 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)

**Comment by ccordoba12** [comment]
Hey @ensbana, thanks for reporting. You said:

> Love the new design in Spyder 6!

Glad you liked it!

> However I'd like to have the debugging buttons, e.g. "Run current line", "Step into function", "Run until next breakpoint", back on the toolbar.

You probably noticed that we moved those buttons to the new `Debugger` pane. But I agree with you that having them in our main toolbar would be nice for those accustomed to use them from there.

My idea is to add them to a toolbar that would be hidden by default but that users could enable in the menu `View > Toolbars`. That's to not have repeated functionality in two places and a too crowded toolbar. Is that ok for you?

**Comment by tlstevenson** [comment]
> Hey @ensbana, thanks for reporting. You said:
> 
> > Love the new design in Spyder 6!
> 
> Glad you liked it!
> 
> > However I'd like to have the debugging buttons, e.g. "Run current line", "Step into function", "Run until next breakpoint", back on the toolbar.
> 
> You probably noticed that we moved those buttons to the new `Debugger` pane. But I agree with you that having them in our main toolbar would be nice for those accustomed to use them from there.
> 
> My idea is to add them to a toolbar that would be hidden by default but that users could enable in the menu `View > Toolbars`. That's to not have repeated functionality in two places and a too crowded toolbar. Is that ok for you?

I had the same desire, especially so I can easily view the variable explorer while navigating my debug session without crowding my screen. I like your proposed solution!

**Comment by ensbana** [comment]
> My idea is to add them to a toolbar that would be hidden by default but that users could enable in the menu `View > Toolbars`. That's to not have repeated functionality in two places and a too crowded toolbar. Is that ok for you?

That sounds great! And thanks for the prompt reply.

Basically when I debug with Spyder I interract with four things:
- The code
- The Variable Explorer
- The debugging buttons
- The console (only sometimes, when I want to experiment with something mid-debugging)

It's nice to have those things visible all at once during debugging. For now I've found a partial solution: moving the Debugger pane down, next to the Console pane. That's way I have three of the things I need most always readey.

**Comment by ccordoba12** [comment]
I'm going to leave this for 6.0.2 because it turned out to be harder than I thought.

**Comment by ensbana** [comment]
> I'm going to leave this for 6.0.2 because it turned out to be harder than I thought.

Would it be easier to allow the users to have more control over the size of the panes? I'm happy with having three panes on top of each other, if I can reduce the size of the debugging pane. Right now Spyder does not let me change it too much from the default. 
![Screenshot 2024-09-13 085830](https://github.com/user-attachments/assets/b55b26e2-050e-4af8-af74-e4e226e4b49f)

**Comment by ccordoba12** [comment]
That's already been reported and we'll to address it in 6.0.2 as well.

**Comment by EBurtonRod** [comment]
> My idea is to add them to a toolbar that would be hidden by default but that users could enable in the menu `View > Toolbars`. That's to not have repeated functionality in two places and a too crowded toolbar. Is that ok for you?

I can totally understand these concerns, and your proposal to have a hidden-by-default toolbar would solve the problem for me.  But based on the kind of data analysis coding that I tend to do, I just thought I should explain one specific reason *why* a user might want to have at least the "Stop debugging" button on the main toolbar:
- The new debugger pane seems great for more complicated debugging (luckily, I haven't needed to use it yet, but I know I will in the future!) but probably 90% of the time I start the debugger, I actually just want to run a script up to a particular point, then stop and have a look at my variables. To do this, I set a breakpoint and run my script:
  - Previously, I could just hit the "Stop debugging" button on the main toolbar; then I could look at the values of my variables in the Variable Explorer, which is the pane I have visible nearly all the time (because it's great).
  - Now, to do this I have to click on the Debugger pane, then click "Stop debugging", then click on the Variable Explorer again.

Clearly, it's not the biggest problem in the world, but I just thought I'd mention it. I don't know whether many other users feel the same...

Anyway, keep up the good work!

**Comment by FugroEgger** [comment]
v6.0.1
The new debug toolbar is missing the "Stop Debug" Icon.  It only contains "Debug File, Debug Cell, Debug selection/cell"
Please add the Stop button again to the toolbar. 
Start and Stop debugging are the most important functions for my to be available in the main menu bar.

as reference, the Debug Toolbar can be activated under menu View\Toolbars

**Comment by egazioglu** [comment]
v6.0.1 We also can't pass the command line arguments with CTRL + F5. Only way to debug with arguments is to press CTRL + F6, click custom configuration and expand the window, copy your argument from the "Advanced settings" part, and then change the "Run this file in:" to Debugger from "IPython console" and then paste your arguments to the "command line options" again. And that is frustrating. @ccordoba12

**Comment by ccordoba12** [comment]
The buttons that control the debugger (next, continue, stop, etc) will be shown automatically in the Debug toolbar since 6.0.2, to be released next week (see the gif in PR #22702 for how things will look).

**Comment by prateekjjw001** [comment]
May I ask what was the need to move the debug buttons from the top? Seems to have unnecessarily caused issues

**Comment by ccordoba12** [comment]
> May I ask what was the need to move the debug buttons from the top?

Because they are available in the new Debugger pane. But the buttons were restored to the main toolbar in 6.0.2, as I mentioned in the comment just above yours.

**Comment by Kofi-Codrington** [comment]
@ccordoba12 Thanks for including the debugging buttons in 6.0.2. This is a major part of what makes spyder the best python IDE
