### ISSUE TITLE
Spyder 6.0.0 release commit cc7434f does not launch

### ISSUE THREAD

**Issue by bessman** [spyder-ide/spyder#22444]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder 6.0.0 installed from PyPI does not launch on Ubuntu 20.04. 6.0.0rc2 launches fine.

I did a git bisect to find the breaking commit, and it's cc7434f. Yes, this one:

```diff
-version_info = (6, 0, "0rc3")
+version_info = (6, 0, 0)
```

No, I don't know how that's possible.

Every commit before it launches fine. Every commit after launches fine. cc7434f does not launch. It hangs indefinitely. When killed with ^C, the error message is:

```python
 Traceback (most recent call last):
  File "~/applications/spyder/venv/bin/spyder", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/applications/spyder/spyder/app/start.py", line 285, in main
    mainwindow.main(options, args)
  File "~/applications/spyder/spyder/app/mainwindow.py", line 1364, in main
    app = create_application()
          ^^^^^^^^^^^^^^^^^^^^
  File "~/applications/spyder/spyder/app/utils.py", line 298, in create_application
    app.set_font()
  File "~/applications/spyder/spyder/utils/qthelpers.py", line 824, in set_font
    self.set_monospace_interface_font(app_font)
  File "~/applications/spyder/spyder/utils/qthelpers.py", line 842, in set_monospace_interface_font
    QFontMetrics(plain_font).xHeight() != x_height
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

### What steps reproduce the problem?

1. git clone https://github.com/spyder-ide/spyder
2. cd spyder
3. pip install -e .
4. git checkout v6.0.0
5. spyder <-- This hangs indefinitely.
6. git checkout master
7. spyder <-- Launches OK.

### What is the expected output? What do you see instead?

Expected: spyder launches
Actual: The 'spyder' terminal command hangs

### Paste Traceback/Error Below (if applicable)

After killing spyder with ^C:

```python
 Traceback (most recent call last):
  File "~/applications/spyder/venv/bin/spyder", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "~/applications/spyder/spyder/app/start.py", line 285, in main
    mainwindow.main(options, args)
  File "~/applications/spyder/spyder/app/mainwindow.py", line 1364, in main
    app = create_application()
          ^^^^^^^^^^^^^^^^^^^^
  File "~/applications/spyder/spyder/app/utils.py", line 298, in create_application
    app.set_font()
  File "~/applications/spyder/spyder/utils/qthelpers.py", line 824, in set_font
    self.set_monospace_interface_font(app_font)
  File "~/applications/spyder/spyder/utils/qthelpers.py", line 842, in set_monospace_interface_font
    QFontMetrics(plain_font).xHeight() != x_height
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

```

**Comment by ccordoba12** [comment]
Hey @bessman, thanks for reporting. When placed in commit https://github.com/spyder-ide/spyder/commit/cc7434f722f5908617117f8dfd91fd6a966908ab, please run

    spyder --reset

and try again. Let us know if that works for you.

**Comment by bessman** [comment]
After running `spyder --reset` it launches OK. Sorry, I realize I checked the box that says I've done that but obviously I hadn't :disappointed:

Still, is that expected? Should this be closed or is there an issue still?

**Comment by ccordoba12** [comment]
It seems you had some old Spyder config that was hanging it somehow. But I think it's not worth it to take a deeper a look at that because it'd be hard to debug.

Good thing is that Spyder is working again for you.
