### ISSUE TITLE
Spyder 6.0.0 has a bad window size on wayland

### ISSUE THREAD

**Issue by Firestar-Reimu** [spyder-ide/spyder#22446]
when I open spyder in the terminal it says:

```
Could not find the Qt platform plugin "wayland" in ""
```

and the preferences look like this:

![image](https://github.com/user-attachments/assets/42dcf6c6-5d5b-45b4-a577-fb8a2d803b66)

Although the Editor looks fine on my 2560x1600 screen, the notebook looks awful (very small)

![image](https://github.com/user-attachments/assets/7231ee59-2080-43b8-b307-c1624b06841e)

**Comment by ccordoba12** [comment]
Hey @Firestar-Reimu, thanks for reporting. This is a duplicate of issue #21980, which you already opened.

We'll try to fix it in a future release.
