### ISSUE TITLE
Chinese characters displayed as variant (Japanese) glyphs on Spyder

### ISSUE THREAD

**Issue by Firestar-Reimu** [spyder-ide/spyder#22445]
First, I use ArchLinux and I installed Source Han Sans CN/HK/JP/KR/TW

And I also installed CJK fonts from Windows, such as SimSun and Microsoft YaHei (by copying them to `/usr/share/fonts` and `fc-cache -fv`)

I have edited `/etc/fonts/conf.d/64-language-selector-prefer.conf` as in [this](https://wiki.archlinux.org/title/Localization/Simplified_Chinese?rdfrom=https%3A%2F%2Fwiki.archlinux.org%2Findex.php%3Ftitle%3DLocalization%2FSimplified_Chinese_%28%25E7%25AE%2580%25E4%25BD%2593%25E4%25B8%25AD%25E6%2596%2587%29%26redirect%3Dno) so that Source Han Sans CN is the default and first font in all CJK characters like this (CN is in front of JP):

```
fc-match -s | grep 'Source Han Sans'
SourceHanSansCN-Regular.otf: "Source Han Sans CN" "Regular"
SourceHanSansJP-Regular.otf: "Source Han Sans JP" "Regular"
SourceHanSansKR-Regular.otf: "Source Han Sans KR" "Regular"
```

but it seems that Spyder does not follow this rule (this issue does not happen in other editor and apps like vscode/kate/firefox/vim)

![image](https://github.com/user-attachments/assets/57be3641-0e72-43af-af2e-2f7f34b24b12)

for example, the correct Chinese glyph is "切"：

![image](https://github.com/user-attachments/assets/8cfd7c41-3e1d-43f7-b285-a57c7c710da4)

**Comment by ccordoba12** [comment]
Hey @Firestar-Reimu, thanks for reporting. I really don't understand how we can address this problem because it seems related to the fonts that you're using and the way you configured them in your system.

But I have a quick question for you: Does it happen with other monospace fonts?

**Comment by Firestar-Reimu** [comment]
Almost all monospaced fonts do not have CJK characters, so this issue happen with other monospace fonts.

![image](https://github.com/user-attachments/assets/cd0f3558-0ff8-468f-ba1c-024c15a8b5b0)

for example, you can see that the latin characters use jetbrains mono, but the CJK characters use multiple Chinese/Japanese fonts.

**Comment by ccordoba12** [comment]
> First, I use ArchLinux and I installed Source Han Sans CN/HK/JP/KR/TW
>
> And I also installed CJK fonts from Windows, such as SimSun and Microsoft YaHei (by copying them to /usr/share/fonts and fc-cache -fv)
>
> I have edited the first comment so that you can see what font I use.

But this is not related to Spyder but to your setup.

> Almost all monospaced fonts do not have CJK characters, so this issue happen with other monospace fonts.

I understand that's frustrating, but I don't see how we could solve this problem in Spyder.

**Comment by Firestar-Reimu** [comment]
> it seems that Spyder does not follow this rule (this issue does not happen in other editor and apps like vscode/kate/firefox/vim)

How do you set the fallback fonts, python or qt?

**Comment by ccordoba12** [comment]
> How do you set the fallback fonts, python or qt?

The problem is that when Spyder is installed through Conda-forge, it comes with its own set of Xorg packages. So you probably need to re-set those fonts in the filesystem structure of your env (e.g. in `~/miniconda3/envs/spyder-dev/etc`).

I'm not sure if that really solves the problem, but it should.

**Comment by Firestar-Reimu** [comment]
Thanks, this solve the problem, edit `/home/firestar/.miniconda/share/fontconfig/conf.avail/64-language-selector-prefer.conf` like this

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <alias>
        <family>sans-serif</family>
        <prefer>
            <family>Source Han Sans CN</family>
        </prefer>
    </alias>
    <alias>
        <family>serif</family>
        <prefer>
            <family>Source Han Serif CN</family>
        </prefer>
    </alias>
    <alias>
        <family>monospace</family>
        <prefer>
            <family>Source Han Sans CN</family>
        </prefer>
    </alias>
</fontconfig>
```

Then do this:

```
ln -s /home/firestar/.miniconda/share/fontconfig/conf.avail/64-language-selector-prefer.conf /home/firestar/.miniconda/etc/fonts/conf.d/64-language-selector-prefer.conf
```

Then the fonts will be good:

![image](https://github.com/user-attachments/assets/2d2c60aa-1bcd-4994-8421-73d2c58e7b0d)

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by Firestar-Reimu** [comment]
Is this not good that spyder uses its own font config and not the system config?

**Comment by ccordoba12** [comment]
That's a consequence of how conda envs are packaged on Linux because they are close to be a virtual machine, i.e. they are (for the most part) separate from the host operating system where they are installed.

So, there's nothing we can do about it.
