### ISSUE TITLE
`spyder` in Prompt window works differently

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#22452]
Before, entering `spyder` would "bind" Spyder to the Miniforge Prompt (or Anaconda Powershell Prompt), but now the terminal is freed up and I can keep entering commands and spawning more `spyder`s... Is this intended?

**Comment by ccordoba12** [comment]
> Is this intended?

Yes, this is the new behavior due to multiple changes to the Spyder 6 conda package to integrate it better with the host operating system as a proper desktop application.
