### ISSUE TITLE
Can IPython console appearance be customized? (Spyder 6.0.0)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#22456]
I preferred 5's fonts, particularly for errors with brighter red

![image](https://github.com/user-attachments/assets/c8fdf986-d7a2-4687-a3b1-76041991c6c9)

Not a big deal, just wondering.

**Comment by PhilipYip1988** [comment]
I think this relates to this issue. [#22412 Traceback color handling and definition ](https://github.com/spyder-ide/spyder/issues/22412)

**Comment by ccordoba12** [comment]
@PhilipYip1988 is right. We're in the middle of improving syntax highlighting for tracebacks in the console. And that will be fixed in 6.0.2, to be released in a month or so.
