### ISSUE TITLE
Cannot import Scipy modules

### ISSUE THREAD

**Issue by Stretch97** [spyder-ide/spyder#2246]
## Description

* *What steps will reproduce the problem?*
1. Run a script with "import scipy.optimize", or any other scipy module.

* *What is the expected output? What do you see instead?*

Expected output: quiet import without any error messages

Observed output:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/(username)/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 680, in runfile
    execfile(filename, namespace)
  File "/Users/(username)/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)
  File "/Users/(username)/Desktop/generic_script.py", line 8, in <module>
    import scipy.optimize
ImportError: No module named scipy.optimize

* *Please provide any additional information below*

I can avoid the problem by simply running "import scipy.optimize" at the console, prior to running the script that calls "import scipy.optimize" in the same console.

In case it matters, I am using the full 64-bit version of Enthought Canopy python.  I built spyder from source using Canopy. 

## Version and main components

* Spyder Version:  2.3.3
* Python Version:  2.7.6
* Qt Version    :  4.8.5, PySide 1.2.2 on Darwin

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  2.4.1 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.0 (OK)
jedi >=0.8.1    :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  0.25.1 (OK)

**Comment by ccordoba12** [comment]
Really weird issue. i don't know what can be happening in this case.

**Comment by Stretch97** [comment]
Can you (or anyone else) reproduce this issue?  I have the problem on both my home computer and work computer.  Both of them are macs with Enthought Canopy.

**Comment by Nodd** [comment]
I can't reproduce it under Linux.
Did you change the python interepreter or is it the same as spyder ?

**Comment by Stretch97** [comment]
Well, I upgraded to 2.3.4 and deleted my ~/.spyder2/ preferences directory.  The problem is gone now.   Sorry for the trouble.
