### ISSUE TITLE
Seeing issues in installing gdal

### ISSUE THREAD

**Issue by abumuttalib** [spyder-ide/spyder#22467]
Traceback (most recent call last):

  Cell In[2], line 1
    get_ipython().run_line_magic('conda', 'install gdal')

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\site-packages\IPython\core\interactiveshell.py:2480 in run_line_magic
    result = fn(*args, **kwargs)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\site-packages\IPython\core\magics\packaging.py:30 in wrapper
    return func(*args, **kwargs)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\site-packages\IPython\core\magics\packaging.py:128 in conda
    conda = _get_conda_like_executable("conda")

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\site-packages\IPython\core\magics\packaging.py:53 in _get_conda_like_executable
    match = re.search(

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\__init__.py:176 in search
    return _compile(pattern, flags).search(string)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\__init__.py:294 in _compile
    p = _compiler.compile(pattern, flags)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_compiler.py:745 in compile
    p = _parser.parse(p, flags)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_parser.py:989 in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_parser.py:464 in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_parser.py:872 in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_parser.py:464 in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_parser.py:548 in _parse
    code = _escape(source, this, state)

  File C:\ProgramData\spyder-6\envs\spyder-runtime\Lib\re\_parser.py:447 in _escape
    raise source.error("bad escape %s" % escape, len(escape))

error: bad escape \P

## Versions

* Spyder version: 6.0.0  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.4.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.3.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  73.0.1 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.1 (OK)
yarl >=1.9.4                     :  1.9.7 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.0 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```
 

Doing it all for the first time so not sure if it is really an issue or there is something more needed from my side.

**Comment by dalthviz** [comment]
Hi @abumuttalib thank you for the report and sorry for the late response! So basically you are trying to install from conda-forge gdal using a Spyder installation from our installers, righ? I'm not totally sure if we support that 🤔 What do you think @ccordoba12 @mrclary ?

In the meantime, I would suggest you to update to the latest Spyder release (6.0.2) and also give a check to the Spyder docs FAQ page: https://docs.spyder-ide.org/current/faq.html#using-spyder

Let us know if the info above helps!

**Comment by mrclary** [comment]
@abumuttalib,
I see that you are trying to install `gdal` into Spyder's runtime environment from the IPython Console. I **highly** recommend not doing this as this could cause issues for Spyder. The recommended practice is to create a separate environment and point Spyder to use that environment.

From an Anaconda prompt or Miniconda prompt, not Spyder's IPython Console:
```bash
conda create -n my-env spyder-kernels gdal
```

**Comment by dalthviz** [comment]
Closing due to lack of response
