### ISSUE TITLE
i have tried to  run my project in spyder but it doesnot  display anything it says run only runfile('C:/Users/luela/untitled1.py', wdir='C:/Users/luela') please help me what can be the problem

### ISSUE THREAD

**Issue by luelagebre** [spyder-ide/spyder#22469]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @luelagebre, thanks for reporting. You need to print something in your code to see a result in the console.

For instance, if you run this code

```python
1+1
```

you will only see the `runfile` command. However, if you run

```python
print(1+1)
```

then you'll see `2` in the console.

Let us know if that helps you to solve your problem.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
