### ISSUE TITLE
ndarray of text does not display correctly in variable explorer

### ISSUE THREAD

**Issue by PhilipYip1988** [spyder-ide/spyder#22466]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Create an ndarray:

```python
import numpy as np
mosaic = np.array([['a', 'b'],
                   ['c', 'd']])
```

### What steps reproduce the problem?

1. Create ndarray of text values
2.  Open in variable explorer
3. strings are empty

### What is the expected output? What do you see instead?

![1](https://github.com/user-attachments/assets/b33a8708-65e1-4b1f-9bab-d7d2a797c9a8)

There is an empty array, the text should display in it.

![2](https://github.com/user-attachments/assets/ae279928-9483-4caa-9f06-6d40ee1abc2e)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 6.0.0  (standalone)
* Python version: 3.11.9 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.26100-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.5 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.0.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.4.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.27.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.3.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.0.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.2.7 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  73.0.1 (OK)
sphinx >=0.6.6                   :  8.0.2 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.1 (OK)
yarl >=1.9.4                     :  1.9.7 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.0 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @PhilipYip1988, thanks for reporting. I was able to reproduce this problem and we'll try to fix it in a future version.

**Comment by jitseniesen** [comment]
I tried to bisect and I think this issue may be caused by PR #20473 by myself, so I will try to fix it.

**Comment by jitseniesen** [comment]
I think I figured out what is going on: Spyder uses `format(..., 's')` to convert array elements to strings. Here, this returns something that looks like an `str` but it is actually a different type:
```
>>> import numpy as np
>>> mosaic = np.array([['a', 'b'],
...                    ['c', 'd']])
>>> format(mosaic[0,0], 's')
'a'
>>> isinstance(format(mosaic[0,0], 's'), str)
True
>>> type(format(mosaic[0,0], 's'))
<class 'numpy.str_'>
```
That seems to confuse the Qt widget that displays the array. PR should be arriving soon.

**Comment by PhilipYip1988** [comment]
Just updated to 6.0.1 and it looks much better. 

However it still says *ndarray object of numpy module* in the variable explorer (red) instead of:

```python
np.array([[a, b],
          [c, d]])
```

Also I can double click into a text field for example the *a* and edit the text to *abcde* (shown in blue). When I click out of the field, it reverts to the original value. This means Save and Close (shown in green) cannot be used:

<img width="960" alt="spyder6 0 1b" src="https://github.com/user-attachments/assets/fc07ebef-2ce5-4705-888d-ced544b77ea4">

**Comment by jitseniesen** [comment]
> However it still says _ndarray object of numpy module_ in the variable explorer (red)

Spyder 5 did the same, but I agree that we can do better. This is a separate issue so I opened a new one in order to stay organized: #22570.

> Also I can double click into a text field for example the _a_ and edit the text to _abcde_ (shown in blue). When I click out of the field, it reverts to the original value.

This reflects how numpy works:

```
>>> import numpy as np
>>> arr = np.array([['a','b'],['c','d']])
>>> arr[0,0] = 'abcde'
>>> arr
array([['a', 'b'],
       ['c', 'd']], dtype='<U1')
```

The reason is that `arr` is an array of strings of length 1 and longer strings are (apparently) truncated. This is pretty confusing and it took me a while to figure it out. However, I don't know what we should do about it.
