### ISSUE TITLE
Where is `Fit plot to window`? (Spyder 6.0.0)

### ISSUE THREAD

**Issue by OverLordGoldDragon** [spyder-ide/spyder#22471]
It was a fix to #13900, was it removed? (The new `Fit plot to the panel size` must be re-applied to every new image)

**Comment by ccordoba12** [comment]
> It was a fix to https://github.com/spyder-ide/spyder/issues/13900, was it removed?

Yes, it was removed.

> (The new Fit plot to the panel size must be re-applied to every new image)

What do you mean by that? Every new image should be automatically fit to the Plots pane size after it's created. If that's not the case for you, please post a video of what you're seeing to better understand your problem.

**Comment by OverLordGoldDragon** [comment]
> Every new image should be automatically fit to the Plots pane after it's created

That's the problem explored in #13900, the resampling causes blur. See e.g. the OP https://github.com/spyder-ide/spyder/issues/13900#issue-712656206

**Comment by OverLordGoldDragon** [comment]
> only when high DPI is enabled

I'm still using normal scaling

> I'll try to solve it in 6.0.2.

Glad to hear. Well, as that's in months and this and #22461 are high priority for me, I'll be using Spyder 5 for now.
