### ISSUE TITLE
Spyder 6.0.0 standalone on Windows 10: "An error occurred while starting the kernel" (miniconda3)

### ISSUE THREAD

**Issue by A-Infor** [spyder-ide/spyder#22479]
### Issue Report Checklist

* [✔️] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [✔️] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [❌] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [❌] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* […] Tried basic troubleshooting (if a bug/error)
    * [✔️] Restarted Spyder
    * [❌] Reset preferences with ``spyder --reset``
    * [❌] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [❌] Tried the other applicable steps from the Troubleshooting Guide
* [✔️] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. install Spyder 6.0.0 standalone on Windows 10;
2. need to install additional packages not part of the standalone version;
3. follow the instructions of the FAQ video on https://docs.spyder-ide.org/current/faq.html under "Q: How do I install Python packages to use within Spyder if I downloaded Spyder from the standalone installers?".

Which instructions?
The video https://www.youtube.com/watch?v=i7Njb3xO4Fw tells to do the following, which I did:

1. download https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe;
2. install for all users on C:\ProgramData\miniconda3
3. conda create -n spyder-env -y
4. conda activate spyder-env
5. conda install spyder-kernels scikit-learn -y
6. change Spyder default interpreter, pointing to C:\ProgramData\miniconda3

Commands that I run on my Anaconda Prompt (miniconda3):

1. conda create -n spyder-env -y
7. conda activate spyder-env
8. conda install spyder-kernels scikit-learn -y
9. conda install spyder-kernels nltk -y
10. pip install nltk
11. conda install spyder-kernels=3.0.*
12. conda install spyder-kernels=3.0
13. conda install -c conda-forge spyder-kernels=3.0.*
14. pip install spyder-kernels==3.0.*

### What is the expected output? What do you see instead?

- **Expected:** just do a simple pip install and get back to programming;

- **What I see instead:** an unwanted error message that does not have my consent for existing on my computer.
![image](https://github.com/user-attachments/assets/4e4fc81e-f70f-47dc-b000-a18875c6cb9a)

I did not ask for an error and I disauthorize my computer from giving me an error
![e9f5614b9937e4fef8a1ba6e0a35a41d7a417855801d33c53aa3928639cf4355_1-4137993528](https://github.com/user-attachments/assets/79ae3d1c-e9a5-4be2-ba28-8866f929c063)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by PhilipYip1988** [comment]
Anaconda test packages for use with the Anaconda Python distribution and as a consequence their packages are normally outdated 6 months behind the community channel... At present, the community ```conda-forge``` channel is updated to version 3.0.0, meanwhile the commercial Anaconda channel ```anaconda``` is only at 2.5.0. Miniconda defaults to the ```anaconda``` channel when unspecified:

[conda-forge spyder kernels 3.0.0](https://anaconda.org/conda-forge/spyder-kernels)

[conda spyder kernels 2.5.0](https://anaconda.org/anaconda/spyder-kernels)

When making your Miniconda environment, you need to make sure your using the community channel, ```conda-forge``` ideally for all packages, otherwise its going to default to the anaconda channel (and give you an older, unsupported version of the package). Remove the mixed channel conda-environment:

```
conda env remove -n spyder-env
```

And create the following conda-forge env:

```
conda create -n spyder-env -c conda-forge spyder-kernels scikit-learn nltk
```

Then retry.

**Comment by A-Infor** [comment]
Fine. I ran the following commands:

1. conda env remove -n spyder-env
2. conda create -n spyder-env -c conda-forge spyder-kernels scikit-learn nltk
3. conda activate spyder-env

Then I tried to set up the Python interpreter inside Spyder:

1. First I tried , `C:\ProgramData\miniconda3\python.exe` and it gave me the same error.
2. Then I tried `C:\Users\Anderson\.conda\envs\spyder-env\python.exe`, and stopped getting errors.

Everything OK?

Thank you very much.

**Comment by chris-vecchio** [comment]
So you are saying that you didn't ask or authorize your computer to give you an error, thus it shouldn't? This issue should be added to the list of the funniest Github issues in history. (Sorry Spyder maintainers I couldn't help myself. Feel free to delete.)
> I did not ask for an error and I disauthorize my computer from giving me an error ![e9f5614b9937e4fef8a1ba6e0a35a41d7a417855801d33c53aa3928639cf4355_1-4137993528](https://private-user-images.githubusercontent.com/67929816/366037937-79ae3d1c-e9a5-4be2-ba28-8866f929c063.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjk0ODYsIm5iZiI6MTcyNjA2OTE4NiwicGF0aCI6Ii82NzkyOTgxNi8zNjYwMzc5MzctNzlhZTNkMWMtZTlhNS00YmUyLWJhMjgtODg2NmY5MjljMDYzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDE1Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNDAzMGIxNzExNzI1ZmJjOWM4ZmU3NTc4ZTVkNTQwNDNjMTJjMTlhMGI2OTA4ZTQ4ZGY3NDZmNDQxZGQ2MzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8vklmgm_mJ054tX3l6G7ZuOWzrS3wdPCHStmex_Q-w)

**Comment by ccordoba12** [comment]
> Thank you very much.

Thanks for letting us know about it @A-Infor. I'm going to close this issue then.
