### ISSUE TITLE
Can't launch Spyder through anaconda after trying to install jupyter package 

### ISSUE THREAD

**Issue by robram945** [spyder-ide/spyder#22482]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Tried to install jupyter package using "conda install spyder-notebook -c conda-forge" and now cannot open spyder

### What steps reproduce the problem?

1. Launching anaconda
2. Trying to launch spyder 
3. 

### What is the expected output? What do you see instead?
Spyder just does not open get error code 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
Traceback (most recent call last):
File "/Users/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/anaconda3/lib/python3.12/site-packages/spyder/app/start.py", line 25, in 
import ctypes
File "/Users/anaconda3/lib/python3.12/ctypes/__init__.py", line 8, in 
from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/anaconda3/lib/python3.12/lib-dynload/_ctypes.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_CFBundleGetVersionNumber'
```

## Versions

* Spyder version: 5.51
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by robram945** [comment]
python version:  3.12.4
qt version: qt-main                   5.15.2 
pyqt version: 2.4.1
operating system: os

**Comment by PhilipYip1988** [comment]
You are attempting to install a ```conda-forge``` (community channel) package into the Anaconda base Python environment which uses the ```anaconda``` (commercial channel). 

The commercial channel is a limited set of packages, repackaged by Anaconda for use in their Anaconda base Python environment. The Anaconda base Python environment should generally be used "as is" with limited updates to the ```conda``` package manager and ```anaconda-navigator```. Installation of community channel packages into the base Python environment, generally results in instabilities. 

You should reinstall Anaconda and create a new Python environment (subinstallation of Python), with ```spyder-notebooks``` and the optional dependencies (seaborn installs, numpy, pandas and matplotlib, pyqt is needed for the interactive qt backend for matplotlib plots and the other dependencies are needed for pandas to read/write to various formats):

```
conda create -n spyder-env -c conda-forge python spyder spyder-notebook cython seaborn pyarrow sympy openpyxl xlrd xlsxwriter lxml sqlalchemy tabulate pyqt
```

**Comment by ccordoba12** [comment]
Closing due to lack of response.
