### ISSUE TITLE
spyder not connecting to kernel

### ISSUE THREAD

**Issue by Theguywithstrangename** [spyder-ide/spyder#22498]
So i downloaded the jupyter notebook and also installed a library named cadquery on my Ubuntu 22.04 and all of a sudden, whole system of the spyder went down cause it could not find the kernel. and now i find out that all you have to do is just download your kernel and add it manually or just add some remote kernel(I don't know anything about it, new to this whole system). so here is the link to it:
https://anaconda.org/conda-forge/spyder-kernels/files
```

**Comment by Zaf4** [comment]
This happened to me with spyder 6

**Comment by Theguywithstrangename** [comment]
hello again friend.
I just deleted the whole spyder ide from my system. i was having spyder 6 too. so just open the .lcoal  file in your system and delete them then install it again. i also noticed that there was my older version of spyder in there as another file.  another point that i want to notice is that it started as i installed the cadquery library.

**Comment by ccordoba12** [comment]
Hey @Theguywithstrangename, thanks for reporting and sorry for the late reply. Were you able to solve your problem at the end?

**Comment by Theguywithstrangename** [comment]
hello @ccordoba12 sorry for the late reply. i actually bruteforced the whole problem and it worked(delete the whole files and reinstalled them). BTW a friend told me that my problem was mostly due to not running the code on VENV.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
