### ISSUE TITLE
access control

### ISSUE THREAD

**Issue by jon1enforce** [spyder-ide/spyder#22491]
what about an implementation of access control, via landlock and unveil?
Is it allowed to me, to adapt your source for a access control demonstration?
I need such an application like spyder to demonstrate something:
https://github.com/jon1enforce/python_access_control/

Is it allowed? The MIT license allows just an adaptation, i guess. But i want to demonstrate it like as a kind of a fork of yours.

**Comment by ccordoba12** [comment]
> what about an implementation of access control, via landlock and unveil?

I don't understand very well what you mean by this, but we're not planning to add something like that to Spyder. 

> Is it allowed to me, to adapt your source for a access control demonstration?

Yes, it is. You can use our source code in any way you want.

**Comment by jon1enforce** [comment]
ok, thanks - - i just looking for an example

**Comment by jon1enforce** [comment]
> I don't understand very well what you mean by this, but we're not planning to add something like that to Spyder.<

landlock and unveil is used-to restrict the access to local data, so the data created, is only used by spyder and not for other apps on the machine. It is used to protect apps from itself. And also used if multiple users are participated, as boundary.

**Comment by jon1enforce** [comment]
what about a feature to turn off potential spyware? Like websocket access. A fork without websocket?
python_lsp.py
# Copyright 2017-2020 Palantir Technologies, Inc.
