### ISSUE TITLE
TypeError: 'method' object is not connected: self.timer.timeout.disconnect(self.show_time)

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2249]
## Description

* *What steps will reproduce the problem?*
1. Run a program more than once

* *What is the expected output? What do you see instead?*
I see this traceback in the internal console:
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/externalshell/pythonshell.py", line 279, in closeEvent
    ExternalShellBase.closeEvent(self, event)
  File "/usr/lib/python3.4/site-packages/spyderlib/widgets/externalshell/baseshell.py", line 209, in closeEvent
    self.timer.timeout.disconnect(self.show_time)
TypeError: 'method' object is not connected
```
* *Please provide any additional information below*

The error is not shown when I run the program the first time, and is then shown once for each additional run.
Each program are independant: if I get the traceback on one program then run another one, there is no error the first time the second program is run, then there is another error for each additional run. 

## Version and main components

* Spyder Version:  2.4.0dev
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by ccordoba12** [comment]
I'll check this error after I release 2.3.4. This is a consequence of moving to the new style for slots and signals, so the stable branch (2.3) is not affected by it.

**Comment by eliedl** [comment]
Hi! im getting the same error (i.e. TypeError: 'method' object is not connected) when running a matplotlib 3D animation embed in PyQt5 GUI. Could anyone help ?
