### ISSUE TITLE
IPython 3.0 is showing a deprecation warning in the Internal Console

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2250]
## Description

* *What steps will reproduce the problem?*
1. Start spyder

* *What is the expected output? What do you see instead?*
I see this warning in the internal console:
```
/usr/lib/python3.4/site-packages/IPython/nbformat/current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
```
* *Please provide any additional information below*

Is it because I have IPython 3.0 ?

## Version and main components

* Spyder Version:  2.4.0dev
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by ccordoba12** [comment]
Thanks @Nodd. We'll fix it when updating the minimal required IPython to be **3.0+**

**Comment by indranilsinharoy** [comment]
I think this needs to be fixed ASAP (I don't mean to be demanding, rather I just wanted to emphasize that this bug is crippling my ability to work in Spyder). In my case, it is becoming a big problem to use the IPython console. Every time I try to use/write a the first parenthesis of a Python function in the IPython console within Spyder, the control switches to the "Spyder Internal Console" that shows the above error.  For example, here is what I have to do to reproduce the error:


```Python
Python 2.7.3 on win32 -- IPython 3.0.0

In [1]: np.array(
```
 
So, I just typed `np.array(` into the IPython console, and immediately the control switches to the internal spyder console that shows the following message:

```Python
>>> C:\Python27\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
ERROR: 3rd party plugin import failed for `p_condapackages`
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\otherplugins.py", line 53, in get_spyderplugins_mods
    __import__(name)
  File "C:\Python27\lib\site-packages\spyderplugins\p_condapackages.py", line 23, in <module>
    from spyderplugins.widgets.condapackagesgui import (CondaPackagesWidget,
  File "C:\Python27\lib\site-packages\spyderplugins\widgets\condapackagesgui.py", line 46, in <module>
    import conda_api_q
ImportError: No module named conda_api_q
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\qt\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\ipython.py", line 339, in _handle_inspect_reply
    signature = self.get_signature(content)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\ipython.py", line 266, in get_signature
    line = self._control.get_current_line_to_cursor()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\mixins.py", line 360, in get_current_line_to_cursor
    return self.get_text(self.current_prompt_pos, 'cursor')
AttributeError: 'IPythonControlWidget' object has no attribute 'current_prompt_pos'
```

.... and I get this every try to call/write a function! This is of course very problematic, and I have to resort to opening a secondary QtConsole independent of Spyder.



My Environment:
* 64-bit Python installation from EPD (not Canopy)
* I have installed Spyder separately (and I have been using Spyder for almost 2 years now without much problem), as it is not distributed with EPD.

Thanks very much.

**Comment by goanpeca** [comment]
@indranilsinharoy, you are using the development version?

**Comment by indranilsinharoy** [comment]
Hi @goanpeca thanks very much for your response. No, I am pretty sure I am not using a development version. I downloaded the Spyder version 2.3.4 (spyder-2.3.4.win-amd64-py2.7.exe) from https://github.com/spyder-ide/spyder/releases. I updated IPython to 3.0 later on.

Thanks.

**Comment by stonebig** [comment]
I confirm the issue, but it is apparently there also on a spyder2.3.3.
Spyder2.3.3, Python 2.7.9 64 bit windows, Qt 4.8.6, PyQt (APIv2) 4.11.3, numpy 1.9.2, pandas 0.16.rc1

**Comment by stonebig** [comment]
same on python3.3

**Comment by stonebig** [comment]
same on my yesterday winpython beta build, which was not with spyder 2.3.3:
````
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:44:40) [MSC v.1600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

In [1]: import numpy as np

In [2]: np.array(
````


````
`Console interne de Spyder

Il s'agit d'une console de débogage
utilisée par Spyder pour signaler des erreurs
internes ou pour inspecter les entrailles de
l'application avec les commandes ci-dessous :
  spy.app, spy.window, dir(spy)

Ne l'utilisez pas pour exécuter votre propre code.

>>> D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\pandas\rpy\__init__.py:8: FutureWarning: The pandas.rpy module is deprecated and will be removed in a future version. We refer to external packages like rpy2, found here: http://rpy.sourceforge.net
  "like rpy2, found here: http://rpy.sourceforge.net", FutureWarning)
D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\matplotlib\cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\IPython\qt\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\ipython.py", line 339, in _handle_inspect_reply
    signature = self.get_signature(content)
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\ipython.py", line 266, in get_signature
    line = self._control.get_current_line_to_cursor()
  File "D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\spyderlib\widgets\mixins.py", line 360, in get_current_line_to_cursor
    return self.get_text(self.current_prompt_pos, 'cursor')
AttributeError: 'IPythonControlWidget' object has no attribute 'current_prompt_pos'
D:\WinPython\basedir34\build\winpython-3.4.3.amd64_build4\python-3.4.3.amd64\lib\site-packages\skimage\filter\__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
````

**Comment by stonebig** [comment]
I must add:
- spyder interna l console is showing trash, but spyder Ipython qt console seems to work

**Comment by stonebig** [comment]
curiosity, now I retry to blow up on my latest beta, and all is ok.....
Just before I tried
````
np.array([1,2,3]) # without having imported numpy as np first
import numpy as np2
np2.array([1,2,3])
````

**Comment by stonebig** [comment]
@indranilsinharoy  can you try the same procedure as in my picture ?

**Comment by indranilsinharoy** [comment]
@stonebig @goanpeca I uninstalled spyder-2.3.3, restarted my machine and installed spyder 2.3.4. However, I am still seeing the problem.

```python
>>> C:\Python27\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
ERROR: 3rd party plugin import failed for `p_condapackages`
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\otherplugins.py", line 53, in get_spyderplugins_mods
    __import__(name)
...
```

Not sure why it is looking for conda packages! 

Quite interestingly, in a different machine in which I am using Anaconda distribution with Spyder 2.3.3 and IPython 3.0, I don't see the error!

**Comment by stonebig** [comment]
There seems to be a parameter file left by your former `Anaconda` installation, that your Ipython in `C:\Python27` is trying to rely on.
maybe have a look on parameter files:
-  in `C:\ProgramData\jupyter`
- or in a `.ipython` directory somewhere in `c:\users`

**Comment by stonebig** [comment]
Reading the code in `https://github.com/spyder-ide/spyder/blob/master/spyderlib/otherplugins.py`.

Did you share a same default 'my personal python programs`directory between spyder for Python 2.7 and a former Anaconda spyder ?

**Comment by indranilsinharoy** [comment]
@stonebig Thanks for the response. I had installed Anaconda once in this machine. However I had uninstalled it long time back. 

"Did you share a same default 'my personal python programs`directory between spyder for Python 2.7 and a former Anaconda spyder ?"

I don't think so. However, I will try to find out based on your clues.

"There seems to be a parameter file left by your former Anaconda installation, that your Ipython in C:\Python27 is trying to rely on. Maybe have a look on parameter files:

in C:\ProgramData\jupyter
or in a .ipython directory somewhere in c:\users"

Couldn't find one.

Thanks.

**Comment by indranilsinharoy** [comment]
Also, it seems like there are two issues here ... I manually deleted the files `p_condapackages.py`, `p_condapackages.pyc` and `p_condapackages.pyo` from the `spyderplugins` directory. Now I don't get the error message `ERROR: 3rd party plugin import failed for `p_condapackages``

However, I still get the following error message (in the Spyder's Internal Console)

```Python
>>> C:\Python27\lib\site-packages\IPython\nbformat\current.py:19: UserWarning: IPython.nbformat.current is deprecated.

- use IPython.nbformat for read/write/validate public API
- use IPython.nbformat.vX directly to composing notebooks of a particular version

  """)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\qt\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\ipython.py", line 335, in _handle_inspect_reply
    signature = self.get_signature(content)
  File "C:\Python27\lib\site-packages\spyderlib\widgets\ipython.py", line 262, in get_signature
    line = self._control.get_current_line_to_cursor()
  File "C:\Python27\lib\site-packages\spyderlib\widgets\mixins.py", line 360, in get_current_line_to_cursor
    return self.get_text(self.current_prompt_pos, 'cursor')
AttributeError: 'IPythonControlWidget' object has no attribute 'current_prompt_pos'
```

**Comment by stonebig** [comment]
so now, maybe try in a "normal" console, the
````
np.array([1,2,3]) # without having imported numpy as np first
import numpy as np2
np2.array([1,2,3])
````
then if it works, retry in Ipython console.
(I don't clearly guess how your current state sorted itself on my PC, but it did)

**Comment by indranilsinharoy** [comment]
@stonebig There is no problem if I type the above code in normal Python console (within Spyder). But the problem exist in the IPython console.

**Comment by stonebig** [comment]
You don't have jedi package I hope ? If so, remove it

**Comment by indranilsinharoy** [comment]
@stonebig I don't have jedi package.

**Comment by Nodd** [comment]
There is a switch in spyder's preferences to jump to the internal console in case of errors. It should be disabled by default, but maybe it is checked for you ?
Since the message is only a warning, it wouldn't bother you anymore and we would have more time to fix it properly.

As I understand, the message only warns that the deprecated API may be removed sometime in the future, it should leave us some time.

**Comment by indranilsinharoy** [comment]
@Nodd Thank you very much. I have unchecked it, and I don't experience the "switch". Helps a lot!!!

**Comment by cheneave** [comment]
@ccordoba12 Same problem occurs on my computer.
If I use the master brunch on git hub and run it with python bootstrap.py, everything is OK. But if I use "python setup.py install" command to install it to python path then run it with spyder.bat, the problem occurs.
