### ISSUE TITLE
Many shortcuts not showing in Preferences

### ISSUE THREAD

**Issue by athompson673** [spyder-ide/spyder#22516]
## Problem Description

Many Keyboard shortcuts are not available in the Preferences pane and can only be edited by opening "\.spyder-py3\config\spyder.ini". Particularly many from the editor context are missing.

### What steps reproduce the problem?

1.  Open preferences > keyboard shortcuts
2.  Search for "show in external file explorer": (it's not there)
3.  Open "spyder.ini"
4.  Search for "show in external file explorer": (it's there)
5.  With spyder closed, set shortcut for "show in external file explorer": (I use "Ctrl+e")
6.  Try to use "show in external file explorer" shortcut: (it works)

I've done some poking around the code, but can't fully follow why some are registered and some not. I suspect it may be due to moving things to the plugin API?

Here's a way I've come up with to determine which commands are not represented:

in the "Internal Console":
```python3
from spyder.config.manager import CONF
ini_commands = set([x[0]+"/"+x[1] for x in list(CONF.iter_shortcuts())])
settings_commands = spy.window.get_plugin("shortcuts").get_shortcut_data()
settings_commands = set([x[1]+"/"+x[2].lower() for x in settings_commands])
for x in ini_commands - settings_commands: print(x)  # 61 commands show not having a settings entry
```

### What is the expected output? What do you see instead?

I would expect all shortcuts to show up in the settings window to be editable without closing spyder and manually editing spyder.ini If there are some which are not editable, I would prefer they still be shown in the shortcuts dialog but not be editable (grayed-out).

## Versions

* Spyder version: 6.0.0
* Python version: 3.11.4
* Qt version: 
* PyQt version: 
* Operating System name/version: Win10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @athompson673, thanks for reporting and letting us know about this regression. We'll try to take a look at it in 6.0.3, to be released in a few weeks.
