### ISSUE TITLE
bgtbhgbgthbghbtghtb

### ISSUE THREAD

**Issue by OlavGroenseth** [spyder-ide/spyder#22525]
yvcgvcdyvcbdcv
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @OlavGroenseth, thanks for reporting. It seems you're using a very old Spyder version (3.2), which is not supported anymore.

Please download a more recent version, as described in our documentation:

http://docs.spyder-ide.org/current/installation.html
