### ISSUE TITLE
Update French translations for 2.3.4

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2252]
@SylvainCorlay or @Nodd, could you help me with this one? As always, please remember to do the PR against the **2.3** branch.

This is going to be the last release of the **2.3** branch. I was hoping **2.3.3** to be the last one, but we needed this release to fix a couple of issues with Jedi, and some bugs that I had had in my todo list for a long time :-)

**Comment by ccordoba12** [comment]
Hey guys, I really need your help here. Only three sentences need to be updated, so the amount of work is very small.

I need to release this ASAP because of the new Anaconda release that's going to happen really soon ;-)

**Comment by SylvainCorlay** [comment]
No worries. I will do this real quick.

**Comment by ccordoba12** [comment]
Thanks man! Really appreciate it!
