### ISSUE TITLE
How do I disable the 'runfile (...)' expression when running a python script from Spyder?

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2254]
Whenever I run a python script from Spyder (v2.2.5), I see the 'runfile(...)' expression.  How can I suppress this?  I am using Spyder 2.2.5 on Ubuntu 14.04.2 LTS

**Comment by ccordoba12** [comment]
`runfile(...)` is the Python command that lets us run your file. It can't be suppressed because we need to evaluate it in our Python/IPython consoles to evaluate your file on them.

Why do you want to suppress it?

**Comment by ccordoba12** [comment]
Closing because of lack of response. We really can't do anything about this one.

**Comment by Assaye** [comment]
It is also boring to see such long text in the output

**Comment by awscarcarre** [comment]
Hi,

Maybe this is not what you're exactly asking, but if you CTRL+Return (Run Cell), instead of F5 (Run), you'll get rid of the "runfile('C:/Users/.../.spyder-py3/temp.py', wdir='C:/Users/..." line in the output. 

Carlos.

**Comment by carlosicc** [comment]
Hi,

Maybe this is not what you're exactly asking, but if you CTRL+Return (Run Cell), instead of F5 (Run), you'll get rid of the "runfile('C:/Users/.../.spyder-py3/temp.py', wdir='C:/Users/..." line in the output.

Carlos.

**Comment by seyyidahmet** [comment]
Hey, 

I know that issue is closed but I found this helpful link https://stackoverflow.com/a/56778708/10864317 where you can hide the runfile command for good. May be there are still people who are annoyed by it.

**Comment by jondo** [comment]
Just an observation: Spyder newbies keep thinking that this runfile message is an error, see e.g. #4658 or https://stackoverflow.com/questions/44767914/spyder-runfile-wdir-error/ .
It also happens to the first year students I'm teaching.

**Comment by ccordoba12** [comment]
Thanks @jondo for mentioning that.

@impact27, thoughts about this?

**Comment by impact27** [comment]
It wouldn't be difficult to run it with `hidden=True`, but I like that I know in which console the file was run. Also that alows me to run it again by using the console history.
If we hide it, the console will be unresonsive until the script finishes, but no indication that something is happening will be shown. That sound much more like a bug than what is described here.
Also, there could be a stiuation where a seemingly pristine console is filled with variables from a previous run, but no indication is given.
I think the current situation is preferable.

**Comment by ccordoba12** [comment]
Perhaps we could add an option to hide it and also activate the stop button in that case? I think that would cover most of drawbacks of hiding `runfile` that you mentioned above.

**Comment by jondo** [comment]
To help people to understand that the message is not an error, maybe
`runfile('/Users/MacobJiller/untitled1.py', wdir='/Users/MacobJiller')`
should print
`Running the script '/Users/MacobJiller/untitled1.py' in working directory '/Users/MacobJiller'.`
instead, or in this case maybe even
`Running the script '/Users/MacobJiller/untitled1.py' in local working directory.`
, to avoid the redundant path (which can be long).
Of course, one would lose repeatability of the call (which I personally wouldn't miss).
