### ISSUE TITLE
No module named 'menuinst'

### ISSUE THREAD

**Issue by Ciaran1981** [spyder-ide/spyder#22565]
## Problem Description
Upon almost finishing an install in a new conda env (nothing else in there) the following (see traceback) is returned and spyder does not install, claiming menuinst is not installed. 

Of course I installed menuinst and reran, but got the same message. I have tried clearing the cache etc and rerunning but still the same. 

### What steps reproduce the problem?

1. conda create -n 'test'
2. mamba install spyder

### Paste Traceback/Error Below (if applicable)

```python-traceback

ERROR conda.core.link:_execute(701): An error occurred while installing package 'conda-forge::spyder-6.0.1-py312h7900ff3_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::spyder-6.0.1-py312h7900ff3_0
location of failed script: /home/ciaran/anaconda3/envs/test/bin/.spyder-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'menuinst'

return code: 1

()

```

**Comment by mrclary** [comment]
@Ciaran1981, thanks for reporting. Are you running on Windows, macOS, or Linux?

**Comment by ccordoba12** [comment]
@Ciaran1981, this was solved by https://github.com/conda-forge/spyder-feedstock/pull/188, so I'm going to close this issue.

Thanks for taking the time to report this error.

**Comment by Ciaran1981** [comment]
> @Ciaran1981, thanks for reporting. Are you running on Windows, macOS, or Linux?

Linux
