### ISSUE TITLE
`SpyderCodeRunner._debugger_exec` error when starting the debugger from Spyder 6.0.1

### ISSUE THREAD

**Issue by RobertDL** [spyder-ide/spyder#22574]
### What steps will reproduce the problem?

I upgraded to version 6.0.1. 
When starting the debugger and continuing the debugging, I get the message TypeError: SpyderCodeRunner._debugger_exec.<locals>.debug_exec() missing 1 required positional argument: 'loc'

## Versions

* Spyder version: 6.0.1  (conda)
* Python version: 3.11.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.9.3 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.17.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  4.0.0 (OK)
cloudpickle >=0.5.0              :  2.2.1 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20230430 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  7.0.1 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.20.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.18.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.19.2 (OK)
keyring >=17.0.0                 :  23.13.1 (OK)
nbconvert >=4.0                  :  7.10.0 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.3 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  5.9.0 (OK)
pygments >=2.0                   :  2.15.1 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.3 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.0,<5.7.0         :  5.6.0 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  68.2.2 (OK)
sphinx >=0.6.6                   :  7.3.7 (OK)
spyder_kernels >=3.0.0,<3.1.0    :  3.0.0 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.2 (OK)
yarl >=1.9.4                     :  1.11.1 (OK)
zmq >=24.0.0                     :  24.0.1 (OK)

# Optional:
cython >=0.21                    :  None (NOK)
matplotlib >=3.0.0               :  None (NOK)
numpy >=1.7                      :  1.26.4 (OK)
pandas >=1.1.1                   :  2.2.2 (OK)
scipy >=0.17.0                   :  None (NOK)
sympy >=0.7.3                    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Hey @RobertDL, thanks for reporting. Please post a simple code example that generates this problem along with a video or animated gif that displays the problem in Spyder.

Without that, I'm afraid we won't be able to help you because we need a way to reproduce your problem.

**Comment by RobertDL** [comment]
Hey Carlos,
The problem is not related to specific code. It seems to be linked to the upgrade of Spyder.
The problem occurs with any code.
I removed Spyder and reinstalled it, without success.
What I find strange: the icons at the top are different from what I was used to. The debugging seems to be by cell, whereas I was used to stepping through the code. It appears the debugger changed?
I added a small video showing the phenomenon.



Van: Carlos Cordoba ***@***.***>
Verzonden: woensdag 25 september 2024 19:14
Aan: spyder-ide/spyder ***@***.***>
CC: RobertDL ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [spyder-ide/spyder] ERROR WHEN STARTING THE DEBUGGER FROM SPYDER 6.0.1 (Issue #22574)


Hey @RobertDL<https://github.com/RobertDL>, thanks for reporting. Please post a simple code example that generates this problem along with a video or animated gif that displays the problem in Spyder.

Without that, I'm afraid we won't be able to help you because we need a way to reproduce your problem.

-

**Comment by ccordoba12** [comment]
> What I find strange: the icons at the top are different from what I was used to. The debugging seems to be by cell, whereas I was used to stepping through the code. It appears the debugger changed?

This is not correct, but I understand the confusion. The buttons in the main toolbar are only used to start the debugger or go into a recursive debugger. And the buttons that control the debugger were moved to the Debugger pane:

![image](https://github.com/user-attachments/assets/77285a25-607a-4bce-a113-bbb1a5abbe10)

> I added a small video showing the phenomenon.

Thanks! But you can't send videos or images via email. You need to upload them directly here, Could you upload it again?

**Comment by RobertDL** [comment]
https://github.com/user-attachments/assets/aad4104b-aac5-412d-885e-2d3a1fb9a3e8

Simple clicking twice on the icon

**Comment by ccordoba12** [comment]
Thanks @RobertDL for the video!

@impact27, are the `Debug file` and `Debug cell` buttons meant to work when a debugging session is active? If so, then we should fix this bug (not sure if here or in spyder-kernels). If not, we should disable them in that case (which I think is an easy fix).

**Comment by impact27** [comment]
The recursive debugger is expected. I fixed it in https://github.com/spyder-ide/spyder-kernels/pull/506

**Comment by ccordoba12** [comment]
Hey @c-martineau, you need to update Spyder to fix this error. If you're using Anaconda, please close Spyder, open the Anaconda Prompt and run there:

    conda install spyder=6.0.3

If you're using our standalone installer, you need to go to the menu entry `Help > Check for updates` and follow the instructions afterwards.

**Comment by c-martineau** [comment]
Thank you, it fixed the bug !
