### ISSUE TITLE
error in version prompt

### ISSUE THREAD

**Issue by jb2444** [spyder-ide/spyder#22578]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @jb2444, thanks for reporting. It seems you're using a very old Spyder version, which is not supported anymore.

Please uninstall it and install a more recent one by following our documentation:

http://docs.spyder-ide.org/current/installation.html
