### ISSUE TITLE
Cannot get Spyder to start

### ISSUE THREAD

**Issue by tjhendrickson** [spyder-ide/spyder#2258]
Hello,

I installed Spyder (via Anaconda) approximately 2 weeks ago without much trouble. Just recently I attempted to open Spyder, but have had extreme difficulties opening it. Each time it appears as if it will load and then it doesn't do anything. When I attempt opening it again I get a message recommending that I perform the command "spyder --reset" do reset thing. I have done and the error still persists. I have extensively searched comments/documentation regarding errors, but nothing has seemed to work for me. I suspected that it has something to do with my anaconda installation, so I have attempted to perform the following commands "conda install ipython -qtconsole" and "conda install -f pyzmq". Unfortunately I get an immediate traceback (see attached), and the problems persist. 

What do I do?

-Tim Hendrickson 

![2015-03-18 13_20_32-anacondatraceback jpg - notepad](https://cloud.githubusercontent.com/assets/7429880/6716202/b0092740-cd71-11e4-9a6a-53c0e6e61fe4.png)

![2015-03-18 13_22_16-anacondatraceback jpg - notepad](https://cloud.githubusercontent.com/assets/7429880/6716224/ddb7c994-cd71-11e4-8835-08f00aa60b9e.png)

**Comment by ccordoba12** [comment]
It seems you have PsychoPy2, which is messing with your Anaconda installation. My recommendation would be to uninstall it and your problems should go away.

**Comment by tjhendrickson** [comment]
That did the trick. Thanks!
