### ISSUE TITLE
Banner not shown when there are many files open in the Editor at startup

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#22593]
Turns out if you have ~ 10 tabs open the IPython banners disappear. If it is less then they show up. 

Weird. This is not the behavour of Spyder 5x since I always had that many tabs

_Originally posted by @beew in https://github.com/spyder-ide/spyder/issues/22440#issuecomment-2377597035_

**Comment by beew** [comment]
Thank you for opening a new bug. I was about to do it but you beat me to it.
