### ISSUE TITLE
logarithm codes

### ISSUE THREAD

**Issue by lizzybear2005** [spyder-ide/spyder#22615]
### What steps will reproduce the problem?

when i am trying to get logarithm in my code it will not show up and it is just marked as an unindetified word. How can i make the function come back, i was able to have it som time ago, but now it will not show up

## Versions

* Spyder version: 5.5.6  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.22631-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
importlib_metadata >=4.6.0    :  8.4.0 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.1.0 (OK)
jsonschema >=3.2.0            :  4.23.0 (OK)
keyring >=17.0.0              :  25.3.0 (OK)
nbconvert >=4.0               :  7.16.4 (OK)
numpydoc >=0.6.0              :  1.7.0 (OK)
paramiko >=2.4.0              :  3.4.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.4 (OK)
pexpect >=4.4.0               :  4.9.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  6.0.0 (OK)
pygments >=2.0                :  2.18.0 (OK)
pylint >=3.1,<4               :  3.2.6 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0        :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0    :  2.0.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2.3 (OK)
qstylizer >=0.2.2             :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0      :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0      :  5.5.2 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.3.0 (OK)
setuptools >=49.6.0           :  73.0.1 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.2,<2.6.0 :  2.5.2 (OK)
textdistance >=4.2.0          :  4.6.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  4.0.2 (OK)
zmq >=24.0.0                  :  26.2.0 (OK)

# Optional:
cython >=0.21                 :  3.0.11 (OK)
matplotlib >=3.0.0            :  3.7.5 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.13.2 (OK)
```

**Comment by ccordoba12** [comment]
Hey @lizzybear2005, thanks for reporting. Please post the code you're trying to run in Spyder to better understand your problem.

Otherwise, I'm afraid we won't be able to help you.

**Comment by lizzybear2005** [comment]
hey, i will send screenshots of my problem. unfortunatly my code is in norwegian, but the functions are in english, so it shouldnt be a problem..¨
<img width="390" alt="problem 1" src="https://github.com/user-attachments/assets/0490e3a5-4b88-481c-adcb-6d71532b50cd">
<img width="466" alt="problem 2" src="https://github.com/user-attachments/assets/557bd224-57ee-4973-ab15-d3486ae967d4">

**Comment by ccordoba12** [comment]
Ok, thanks for the screenshot. You need to import `log` in order to use it in your program (in old versions of Spyder that was not the case, but now it's required).

To do that, please add the following at the beginning of your file (i.e. before `def f(x):`)

```python
from math import log
```

That should solve your problem.

**Comment by lizzybear2005** [comment]
Thank you very much for your help!!, I managed to get the right answer now:)

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
