### ISSUE TITLE
Can't upgrade Spyder because Spyder downgraded from 5.5.1 when I import an environment yml file created ion Spyder 5.1.5

### ISSUE THREAD

**Issue by DRG01** [spyder-ide/spyder#22613]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The following lines in my environment yml file seems to cause Spyder version=5.5.1 to revert back to Spyder version=5.1.5 after I import the environment in the otherwise upgraded Spyder in Anaconda

### What steps reproduce the problem?

1.   
  - spyder=5.1.5=py39haa95532_1
  - spyder-kernels=2.1.3=py39haa95532_0
  - 

### What is the expected output? What do you see instead?
I expect Spyder to be upgraded and stay upgraded after I imported the environment file

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @DRG01, thanks for reporting. You said

> The following lines in my environment yml file seems to cause Spyder version=5.5.1 to revert back to Spyder version=5.1.5 after I import the environment in the otherwise upgraded Spyder in Anaconda
>
> spyder=5.1.5=py39haa95532_1
> spyder-kernels=2.1.3=py39haa95532_0

You're right, those lines install Spyder 5.1.5 in your environment. So, you either need to remove them or update your env specification to include a more recent Spyder version. Those are your two options.

Since this is not a Spyder problem nor is there anything we can do to solve it, I'm going to close this issue.
