### ISSUE TITLE
not downloading module

### ISSUE THREAD

**Issue by cyberspeed1** [spyder-ide/spyder#22624]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Hey @cyberspeed1, thanks for reporting. It seems you're using a very old Spyder version (probably 3.2 or even older), which is not supported anymore.

Please update to a more recent version by following the instructions in our documentation:

http://docs.spyder-ide.org/current/installation.html
