### ISSUE TITLE
Global Run preset default values reappear after restart

### ISSUE THREAD

**Issue by Matthew-Copping** [spyder-ide/spyder#22649]
After modifying the default behaviour and restarting spyder the original default configuration reappears along side my changed version. As a result my changes are not used. 

Print screens of steps:
![grafik](https://github.com/user-attachments/assets/be658961-90ae-4b8e-9d3d-f31bf26e9ea4)

restart spyder
![grafik](https://github.com/user-attachments/assets/7c032580-6360-4f37-88b8-a1c724ff9c1e)

Original settings have reappeared
![grafik](https://github.com/user-attachments/assets/33b53f97-0de5-4fac-b05e-b2a2ade6ed03)

The settings that i would like now appear under this. 
![grafik](https://github.com/user-attachments/assets/1c5b690c-ab53-49d7-b450-ea68659c17d4)

I am not able to get my code to run from the current directory after restarting spyder (version 6.0.1).

Update: 
After further investigation, I am unable to get my code to run from the current working directly under any circumstance. Running my script always resets the current directory to my home directory. regardless of the settings in global presets.

**Comment by ccordoba12** [comment]
Hey @Matthew-Copping, thanks for opening this issue and your detailed description of the problem. I was able to easily reproduce it with it.

We'll try to fix this bug in our 6.0.3 version, to be released in a few weeks.

**Comment by ccordoba12** [comment]
Closing as fixed by #22928.
