### ISSUE TITLE
Error Starting the Kernel

### ISSUE THREAD

**Issue by AGoh2019** [spyder-ide/spyder#22641]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
On startup, IPython Console shows this error message - "chap" is not recognised as an internal or external command, operable program or batch file.

**Comment by ccordoba12** [comment]
Hey @AGoh2019, thanks for reporting. Are you using Mamba or micromamba 2.0+ in your base environment?

**Comment by AGoh2019** [comment]
I can't tell which one I am using?
--- Andrew Goh
 

    On Monday, 7 October 2024 at 02:27:24 am SGT, Carlos Cordoba ***@***.***> wrote:  
 
 


Hey @AGoh2019, thanks for reporting. Are you using Mamba or micromamba 2.0+ in your base environment?

**Comment by ccordoba12** [comment]
You need to open the Miniforge Prompt (I guess that's what you're using; if not, then the equivalent to it) and then run

    mamba --version

or

    micromamba --version

if that fails.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
