### ISSUE TITLE
"TODO" should not be labeled with checkmark

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#2264]
Currently in the editor, lines starting with "TODO" get marked with a checkmark at the left border.

I am associating a checkmark with "done", i.e. the opposite of "todo" ;-)
So I suggest to replace this checkmark, e.g. by a red square.

**Comment by ccordoba12** [comment]
Probably something for @SylvainCorlay and @goanpeca to be aware of, now that they are working on a new icon set for Spyder.

**Comment by hal98x** [comment]
I like that the symbol is added, but I like this convention change that is suggested. I would make the symbol a red flag if possible but really anything other than a check that is not similar to a breakpoint would be good.

**Comment by ccordoba12** [comment]
@SylvainCorlay, could you take a look at this one please?

**Comment by SylvainCorlay** [comment]
Sorry I missed this one. Will look at it.

**Comment by jondo** [comment]
The wrong image "![todo.png](https://user-images.githubusercontent.com/21648/45368785-bb0a8580-b5e4-11e8-8490-2eaeb92ecf2b.png)" is [todo.png](https://github.com/spyder-ide/spyder/blob/master/spyder/images/editor/todo.png). I don't know whether you also want to change [todo_list.png](https://github.com/spyder-ide/spyder/blob/master/spyder/images/editor/todo_list.png) ("![todo_list.png](https://user-images.githubusercontent.com/21648/45368886-f2793200-b5e4-11e8-968d-05f07b4638bf.png)").

**Comment by ccordoba12** [comment]
@jondo, what do you mean? I don't understand your comment.

**Comment by jondo** [comment]
Sorry for the noise. I just gave the pathnames of the wrong images, in case someone wants to edit the files.

**Comment by ccordoba12** [comment]
A check mark is usually meant to denote TODO:

https://www.google.com/search?q=todo+icon&client=ubuntu&hs=In9&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwib3K2gubPdAhXPu1MKHYuVBMEQ_AUICigB&biw=1440&bih=766

**Comment by jondo** [comment]
In your examples, I see the unresolved TODOs depicted as empty checkboxes (or empty circles). Only the resolved ones get the check mark.

**Comment by jondo** [comment]
I know. Would ![flag](https://user-images.githubusercontent.com/21648/45613552-0b5f6880-ba67-11e8-92f9-d6fa2beea98c.png) be OK (if resized from 16x16 to 12x12, and without shadow)?
Source: http://p.yusukekamiyamane.com/icons/search/fugue/icons/flag.png. The About dialog of Spyder 3.3.1 says that other icons were already taken from that "CC BY 3.0" source.

**Comment by ccordoba12** [comment]
We'd prefer icons present in FontAwesome, which can be loaded with our little QtAwesome library.

**Comment by jondo** [comment]
This would be the flag from https://fontawesome.com/icons/flag?style=solid then, in red color.

**Comment by ccordoba12** [comment]
Ok, that should do it. But I think you need to use the just released QtAwesome 0.5 to have support for that.

So please do this for master and not 3.x because it'll require increasing the minimal QtAwesome version we need.

**Comment by jondo** [comment]
>  I think you need to use the just released QtAwesome 0.5

The flag was already available in FontAwesome 4.7, [just looking different](https://fontawesome.com/v4.7.0/icon/flag), and [it wasn't new there](https://fontawesome.com/v4.7.0/whats-new/). So perhaps it's already supported by QtAwesome < 0.5?
But it would need a different icon prefix than in FontAwesome 5.

**Comment by ccordoba12** [comment]
If the flag is in FontAwesome 4.7, then you can do a PR against 3.x

**Comment by jondo** [comment]
Fine! However:
After some thought, I'd prefer an unchecked checkbox symbol, like in [FA 4.7](https://fontawesome.com/v4.7.0/icon/square-o) and [FA 5](https://fontawesome.com/icons/square?style=regular), in the same color as the current checkmark. It looks less aggressive than a red flag. Would this also be acceptable?

**Comment by ccordoba12** [comment]
That looks find in a TODO list, but I don't know how well is going to look for us. I'd prefer a non-filled check circle:

https://fontawesome.com/icons/check-circle?style=regular

In any case, it's clear that this requires more discussion, so it needs to go to Spyder 4.

**Comment by jondo** [comment]
OK, the circle https://fontawesome.com/icons/circle?style=regular also looks good to me (though I'd still prefer the checkbox, as it reminds of a checkbox gui widget).

(There is also https://fontawesome.com/v4.7.0/icon/circle-o, but no problem to skip Spyder 3.x.)

**Comment by ccordoba12** [comment]
Yep, probably the checkbox is better because we already use filled circles for breakpoints.

**Comment by jondo** [comment]
I just launched Spyder 4 from the master branch for the first time, and it seems the old TODO labels are not working any more. Can you confirm? Well, at least the breakpoints are labeled correctly.

**Comment by ccordoba12** [comment]
@jondo, you're right, those marks are not working. Please open an issue about it.
