### ISSUE TITLE
Error Starting the Kernel

### ISSUE THREAD

**Issue by Dr-yangyangzhang** [spyder-ide/spyder#22653]
I use Spyder 6.01 on WIN 64. When I lunch Spyder it says:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Yesterday I uninstall and reinstall Spyder and the problem disappeared. But today it shows up again.

**Comment by ccordoba12** [comment]
Hey @Dr-yangyangzhang, thanks for reporting. I have some questions for you:

1. How did you install Spyder?
2. Did you install it in `C:\Program Files`?
3. Could you post a screenshot of the problem you're having?

Your answers will help us to better understand your problem.

**Comment by Dr-yangyangzhang** [comment]
@ccordoba12 
1. I download the .exe file from spyder website.
2. No. I use the default setting which is `C:\Users\yangyangzhang\AppData\Local\spyder6`
3. Attached.
![spyder_6_error](https://github.com/user-attachments/assets/f345843d-9a42-48cd-aa4d-a92ee234d719)

**Comment by ccordoba12** [comment]
Thanks for the answers @Dr-yangyangzhang! You said:

> No. I use the default setting which is C:\Users\yangyangzhang\AppData\Local\spyder6

But do you have Anaconda or Miniconda installed in `C:\Program Files`? It's fine if you do, but I need to know that.

**Comment by Dr-yangyangzhang** [comment]
@ccordoba12 I used to have either miniconda or Anaconda installed but now I uninstalled them all. (Try to fix this issue). So no I don't have either of these two installed. Now I use a python from python.org (manually installed)

**Comment by ccordoba12** [comment]
> Now I use a python from python.org (manually installed)

Ok, and that's installed in `C:\Program Files`?

**Comment by ccordoba12** [comment]
Ok, thanks for checking. And did you install spyder-kernels in that Python installation?

**Comment by Dr-yangyangzhang** [comment]
@ccordoba12 I fixed this problem by manually set the python interpreter to the one I am using now. Still this is a very strange issue because I tried the same method( set the python interpreter manually) but it didn't work. Somehow today it works.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it @Dr-yangyangzhang. I'm going to close this issue then, but feel free to post a comment again if the problem appears again.
