### ISSUE TITLE
Add option to set IPython Console completion widget size

### ISSUE THREAD

**Issue by allthedata** [spyder-ide/spyder#2265]
## Description

Would it be possible to have an option to increase the size of the tab completion popup in the IPython console? Because of [this](https://github.com/spyder-ide/spyder/issues/1908) bug that is preventing scrolling using the mouse for me in Windows, and the recent update to IPython that changed tab completion to display fully qualified names (`a.b.c` instead of just `c`), often the last part of the name is not visible, making tab completion pretty unusable right now.

## Version and main components

* Spyder Version:  2.3.3
* Python Version:  2.7.8
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
jedi >=0.8.1    :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.3.1 (OK)

**Comment by ccordoba12** [comment]
Could you post a screenshot to see what you mean for *fully qualified names* please?

Also, we can't modify this on the Spyder side. But I could create a PR for the IPython project if I understand your problem better.

**Comment by allthedata** [comment]
Sure, that would be great. I mean that it displays `matplotlib.backends.backend_qt5agg.Figure` instead of `Figure`. Also, the IPython Notebook has a larger completion widget than Spyder does. Though I just realized that for now I can go to Preferences and change the setting to use plain text instead of the completion widget in Spyder.

![picture1](https://cloud.githubusercontent.com/assets/6295582/6810877/561cbf6c-d23a-11e4-8663-a21ceadf0747.png)

**Comment by ccordoba12** [comment]
Thanks a lot fore the screenshot. @takluyver, is this a known issue? Do you plan to fix it for 3.1?

**Comment by takluyver** [comment]
@Carreau thinks it's a known issue, but I can't find an open issue for it. We'd probably accept a fix.

**Comment by ccordoba12** [comment]
@takluyver, I can give it a try. Any pointers on where to start looking?

**Comment by takluyver** [comment]
Sorry for the delay responding to this. There are two approaches you could look at:

1. Making the completer popup adapt to the width of the things listed. The completion widget code is here: https://github.com/jupyter/qtconsole/blob/master/qtconsole/completion_widget.py

2.  Making the completions only include the part after the last dot, instead of the whole qualified name. This might be trickier - the completion code needs some rehashing, and I'm meaning to get round to it. The relevant code is probably here: https://github.com/ipython/ipython/blob/master/IPython/core/completer.py

**Comment by ccordoba12** [comment]
A fix for this was submitted in jupyter/qtconsole#93, to be released in QtConsole 4.2.

So I'm closing this bug because it can't be solved directly in Spyder.
