### ISSUE TITLE
Windows Layout 

### ISSUE THREAD

**Issue by rfeir** [spyder-ide/spyder#22669]
Any time I select some windows layouts, all the windows go away. This has been the case since the 6.0 update.

**Comment by ccordoba12** [comment]
Hey @rfeir, thanks for reporting. Do you mean that you have some undocked panes, then apply a layout and they disappear?

**Comment by rfeir** [comment]
No, all panes completely disappear. I would have to select each individually to show again. Not just an undocked editor.

**Comment by ccordoba12** [comment]
Ok, please post a video of what you're seeing so we can try to reproduce your problem on our side.

**Comment by rfeir** [comment]
I began a recording in which I downgraded and upgraded and now it works. Strange, because that's not the first time I've done that, but oh well.

**Comment by ccordoba12** [comment]
No problem. I'll leave this open for a while in case the problem shows up for you again.

**Comment by ccordoba12** [comment]
Closing due to lack of response. Hopefully the problem didn't resurfaced for you again.
