### ISSUE TITLE
Move Conda Package Manager to its own repo

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2267]
Before releasing our first beta, I think we should move the conda plugin to its own repo, under the *spyder-ide* organization of course.

This would have several adantages:

1. The plugin could evolve at its own pace. Right now it hasn't seen more activity after being merged.
2. We would avoid headaches with Linux and MacPorts packagers. They also release packages for our betas, and most probably would patch Spyder to remove the plugin if we included in beta1.
3. The plugin would have its own Issues and Wiki, which would be really useful.
4. We wouldn't need to release (as part of Spyder) the big files on which the plugin relies (I mean all the json files present in `spyderplugins/data`).

I'll try to have our new infrastructure to install external plugins ready for beta1, but most surely it'll be there for beta2.

@goanpeca, what do you think?

**Comment by goanpeca** [comment]
@ccordoba12 actually I have always wanted to do this so fine by me.

So.. you create the repo and give me admin rights so I can start uploading it?

Should we make it a namespace package? or a package on its own that adds a hook and registers as a plugin for spyder?

**Comment by ccordoba12** [comment]
Great! I'm really glad you agree with me ;-) I thought you were going to be opposed to the idea because it sounds like we are not giving enough credit to your work.

But as I said before, I think your plugin is really important and it's going to be game changer for Spyder **3.0** (yes, after a lot of thought, I decided to move to 3.0)

So what would you like as the repo name?

----

> Should we make it a namespace package? or a package on its own that adds a hook and registers as a plugin for spyder?

I think it should be its own package, so that it can be used outside Spyder.

**Comment by goanpeca** [comment]
Hahaha, thankfully I am beyond puberty so the credit issue should not be a problem ;-)

Hmmmm well, actually I dont have a clear idea on the name for the repo, or the package... hmmm
`condamanager` `conda-manager` `conda-installer`, `conda-gui` ?

**Comment by ccordoba12** [comment]
Well, GH is a (powerful) way to get programming jobs by showing off what you can do, so it's better to ask these things with *pies de plomo* ;-)

I think `conda-manager` is fine. We could change it later if you want.

**Comment by goanpeca** [comment]
ok `conda-manager

**Comment by goanpeca** [comment]
Actually this gives me more freedom to quickly check the problems with qt5 plus some additional functionality... 

Side comment, I am having some issues with pyside, because apparently it does not include https support... and fetching the continuum (now) requires https.... any thoughts on that?

**Comment by ccordoba12** [comment]
PySide is not supported by Continuum anymore. Since `conda-manager` is going to live outside Spyder, you can just drop support for PySide.

----

Do you want to give someone else admin access?

**Comment by goanpeca** [comment]
@Nodd, (and you of course :p )

**Comment by goanpeca** [comment]
Are we dropping support for pyside as well?

**Comment by ccordoba12** [comment]
Ok. No problem for me because I'm the owner of the organization (so I have admin access for all repos under it).

----

> Are we dropping support for pyside as well?

Nop, you need to ckeck under `conda-manager` if Spyder is running with PySide, and avoid loading it if Spyder does.

**Comment by goanpeca** [comment]
Ok, I will still provide pyside support, I will just have to download stuff with urlib2 or requests, instead of Qt, and it should be fine.

**Comment by ccordoba12** [comment]
Ok, the repo is ready! Since we missed beta1 for March 15th, I was thinking to move it to April 15th and reduce our beta count in one.

So please try to move the plugin and make the corresponding PR here as soon as possible ;-)

**Comment by goanpeca** [comment]
Ok, I will move it now, so we can get over with this ASAP, and maybe you get some pressure to have the plugins infrastructure ready ;-p

**Comment by Nodd** [comment]
That's a good idea to separate it from stock spyder:
* it's completely useless if you're not using Anaconda
* it can be run standalone without spyder

It's also a good opportunity to check if a package can be installed as standalone while having a part in a namespace package (just to load the main module). It would be very nice for future plugin devs.

**Comment by goanpeca** [comment]
@Nodd I am working on that basically. Basically when you install... the setup.py

**Comment by Nodd** [comment]
Then you don't need to declare that it's a namespace package ? If not, is there a risk that the previous files in ```spyderplugins``` could be erased when installing conda-manager ?

**Comment by goanpeca** [comment]
I will have to test, I would not expect that to happen though

**Comment by ccordoba12** [comment]
@goanpeca, I saw that you moved the plugin to the conda-manager repo already. Do you want to do a PR to remove it from here? Or do you prefer me to do it?

**Comment by goanpeca** [comment]
I just copy pasted... not working right now :p, but sure I have all files anyway so feel free to give proper burial to my child ;-)

**Comment by ccordoba12** [comment]
Ok, so to remove the plugin I deleted these files so far:

* external-py2/conda_api_q.py
* external-py3/conda_api_q.py
* spyderplugins/p_condapackages.py
* spyderplugins/widgets/condapackagesgui.py
* spyderplugins/data

Is there anything missing @goanpeca?

**Comment by goanpeca** [comment]
Yes images inside `images`

**Comment by ccordoba12** [comment]
Which ones?

**Comment by goanpeca** [comment]
Anything that starts with `conda_`, should be clear ;-)
