### ISSUE TITLE
Windows version didn't show kernel enviornoment

### ISSUE THREAD

**Issue by hawkiyc** [spyder-ide/spyder#22674]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I am using spyder on my Mac, Windows, and Linux devices. The spyder on Linux is installed in conda base environment, the others are standalone versions. Spyder can show the running environment on Linux and Mac, but not on Windows.

![截圖 2024-10-15 16 56 13](https://github.com/user-attachments/assets/9a8f6b44-8fbb-4bb5-8455-98833174ffd8)
Running env showed correctly on Mac
![截圖 2024-10-15 16 57 50](https://github.com/user-attachments/assets/9a9ee04f-6a57-44f1-a5bd-b0944f222994)
Running env showed correctly on Linux
![截圖 2024-10-15 16 59 06](https://github.com/user-attachments/assets/0d189306-c005-4a74-86a2-d1a1aa60a8f6)
It only shows conda and python version no matter what env you are running

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

It would be great if the Windows version also showed the environment name, like the Linux and Mac versions.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 5.4.0
* Python version: Python 3.8.10
* Qt version: 5.15.2
* PyQt version: PyQt5 5.15.7
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @hawkiyc, thanks for reporting. This problem should be fixed in 6.0.1, released three weeks ago.

Please update and let us know if that's the case for you.

**Comment by hawkiyc** [comment]
Hi @ccordoba12 ,

I cannot update to 6.0.1 with the update interface, so I reinstalled 6.0.1. Yes, the env indeed shows correctly. But there is another bug. In the previous spyder, you can click the env shown on the button and change env easily. But now you have to change env in the preference setting.

![截圖 2024-10-17 09 53 35](https://github.com/user-attachments/assets/46252575-fbfa-41ab-906f-6ba24a89cec2)

**Comment by hawkiyc** [comment]
> > Yes, the env indeed shows correctly.
> 
> Great! Thanks for letting us know about it.
> 
> > But there is another bug. In the previous spyder, you can click the env shown on the button and change env easily. But now you have to change env in the preference setting.
> 
> We think that functionality is not so important in Spyder 6 because you can open a console for specific environment by going to the menu `Consoles > New console in environment`. Please try that and let us know if you still think that we should restore the ability to change environments from the status bar.

Hi @ccordoba12 , oh, I see. As there is no bug for now, I will close this issue. But I think change env from status bar is a good feature, and it will be great if you can bring it back. Cheers.

**Comment by ccordoba12** [comment]
> But I think change env from status bar is a good feature, and it will be great if you can bring it back. Cheers.

Ok, thanks for your feedback. I'll open another issue for that.
