### ISSUE TITLE
Check update process for 6.0.2 with a rc (6.0.2rc1)

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#22685]
Given that the changes in PR #22598 are not so simple, I think we should manually check the update process is working as expected.

For that, I propose the following:

* With the nightly installers for the day before, click on the `Check for updates...` menu entry after the `6.0.2rc1` Github release is published but before the installers are generated. This should give no error and offer no update either.
* After the installers are uploaded, and also using the nightly installers, check the update process between them and rc1 is working.

@mrclary, are there other checks you think we should run before releasing 6.0.2?

**Comment by mrclary** [comment]
@ccordoba12, I think that is the best we can do. I don't think anything else needs to be tested.

I think that we'll need to coordinate our check for update with the Github release since we will have a short time window in which to test it:
* Linux: < 5min
* macOS: ~8-12min
* Windows: ~27min

Perhaps a zoom/discord call? If everyone installs the latest nightly before the call, then we can be ready to test the check-for-update as soon as @dalthviz publishes the release while on the call.

**Comment by ccordoba12** [comment]
> Perhaps a zoom/discord call? If everyone installs the latest nightly before the call, then we can be ready to test the check-for-update as soon as @dalthviz publishes the release while on the call.

Agreed, that's a good idea. What do you think @dalthviz?

**Comment by dalthviz** [comment]
Just in case 6.0.2rc1 is now available over PyPI (https://pypi.org/project/spyder/6.0.2rc1/) and also created the PR to update the conda-forge recipe (https://github.com/conda-forge/spyder-feedstock/pull/195)

**Comment by dalthviz** [comment]
So GitHub release for 6.0.2rc1 was created (https://github.com/spyder-ide/spyder/releases/tag/v6.0.2rc1) and manual testing for the improvements to the update mechanism were successful :tada: So I would say this should be closed now, right @ccordoba12 @mrclary ?

**Comment by mrclary** [comment]
I'm double-checking the update process, so standby...

**Comment by mrclary** [comment]
Okay, everything looks good on my end. rc1 updated successfully.

**Comment by ccordoba12** [comment]
I can confirm that the update proceeded without problems on Linux.

@dalthviz, could you check that on Windows? If things are working as expected, then close this issue.
