### ISSUE TITLE
gives error i am student  please help 

### ISSUE THREAD

**Issue by zeyserra22** [spyder-ide/spyder#22707]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
ıt gives an errorbwhen ı want to "in" and "out" for any operation. ı press the (left) "alt" and enter" key to do "print" but it gives an error

**Comment by ccordoba12** [comment]
Hey @zeyserra22, thanks for reporting. Could you post a screenshot of what you're seeing in Spyder?

That will help us better understand your problem.

**Comment by zeyserra22** [comment]
![Ekran Görüntüsü (1)](https://github.com/user-attachments/assets/1469b096-d880-4d11-858f-0cfcb127884d

**Comment by ccordoba12** [comment]
Thanks for the screenshot. To be able to read the error you're having, please click on the button `Show details` that appears in the window that says there's an error in Spyder.

After that, copy the contents of the error that appears there and post it here.

**Comment by zeyserra22** [comment]
of course

Carlos Cordoba ***@***.***>, 23 Eki 2024 Çar, 18:22 tarihinde
şunu yazdı:

**Comment by ccordoba12** [comment]
@zeyserra22, if you attached another screenshot to your last email, then I'm afraid you'll have to drag and drop it directly on Github again. That's because Github doesn't allow to send file attachments on email answers, sorry.

**Comment by zeyserra22** [comment]
![Ekran Görüntüsü (2)](https://github.com/user-attachments/assets/3838ca10-f768-4632-9a4d-42304cd10eed)
 hi this is second ss

**Comment by ccordoba12** [comment]
Ok, thanks for your patience. Now, please do the following:

* Copy the code you wrote in the `temp.py` file and paste it in another editor outside Spyder (for example, Notepad or Word).
* Then go to the menu entry `Tools > Reset Spyder to factory defaults` and click `Yes`.
* After that, start Spyder again.
* Finally, paste in Spyder the code you copied to the other editor and try to run it again.

Hopefully, that should solve the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by zeyserra22** [comment]
merhaba geçici bir çözüm buldum tesekkur ederim yardım  için

18 Kas 2024 Pzt 02:12 tarihinde Carlos Cordoba ***@***.***>
şunu yazdı:
