### ISSUE TITLE
Full screen mode for each subwindow

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2270]
Currently we can't do a full screen to editors, we can dock the subwindow out of spyder, it would be great if we could just do a maximize a particular window within spyder itself so while working on the code we can maximize the window & then restore its state while debugging

**Comment by goanpeca** [comment]
I do not understand. The editor can be maximized in spyder as any of the other widgets.

Editor can also be opened in a new window in case you work with multiple monitors.

**Comment by thewhitetulip** [comment]
I didn't find the option to maximize the editor, I am trying to say we can maximize the editor `inside` spyder's main window, in eclipse we can do a `ctrl+m` and it maximizes the editor.

What I am trying to say is ability to `maximize` or `minimize` any `view`, 
![screenshot from 2015-03-25 17 50 12](https://cloud.githubusercontent.com/assets/6261877/6824341/6c585a42-d317-11e4-8b72-70c3af4b5640.png)

In this screenshot, I can't minimize the object inspector window to a size less than the current one, it would be nice to minimize it entirely.

>Editor can also be opened in a new window
Frankly I didn't know about this feature, but it works only in the case when you have multiple monitors

**Comment by goanpeca** [comment]
There is a button that says maximize current pane in the toolbar, and it does precisely that

**Comment by thewhitetulip** [comment]
Okay, will it be a good idea to add another button along right next to the two buttons (next to the object inspector text), the close and detach buttons, it would be intuitive for a user to want to do a full screen from that button instead from the main toolbar, what do you think?

**Comment by goanpeca** [comment]
Sure, seems reasonable, please open a new issue to start a clean discussion there on an actual issue.

Please use a meaningful title

**Comment by thewhitetulip** [comment]
Okay

**Comment by vikashal** [comment]
> There is a button that says `maximize current pane` in the main toolbar, and it does precisely that.
> 
> From your screen shot is the first button of the first toolbar in the left

Thanks
