### ISSUE TITLE
Can't launch Spyder on Mac (Anaconda) - Segmentation fault: 11" message

### ISSUE THREAD

**Issue by singhsaurabhaiims** [spyder-ide/spyder#22701]
### Issue Report Checklist 

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I used Spyder5 with Anaconda on my Mac.
It stopped working on 20 October, 2024. I am trying running Spyder5 but I have this "Segmentation fault: 11" message.

### What steps reproduce the problem?

1. When launching
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

(base) saurabhsingh@Saurabhs-MacBook-Pro ~ % spyder
fromIccProfile: failed minimal tag size sanity
2024-10-21 11:28:08.284 python[4594:94937] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-21 11:28:08.284 python[4594:94937] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
/opt/anaconda3/bin/pythonw: line 3:  4594 Segmentation fault: 11  /opt/anaconda3/python.app/Contents/MacOS/python "$@"

```

## Versions

* Spyder version: 5.5.1
* Python version: 3.12.4
* Qt version: 5.15.2
* PyQt version: 5.15.10
* Operating System name/version: macOS Sequoia 15.0.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

[Problem Details and System Configurations.pdf](https://github.com/user-attachments/files/17458155/Problem.Details.and.System.Configurations.pdf)

<img width="290" alt="Application Launch Error" src="https://github.com/user-attachments/assets/3ae28e68-6928-4e2a-91b3-67719d262957">

**Comment by ccordoba12** [comment]
Hey @singhsaurabhaiims, thanks for reporting. Please open a terminal, run there

    conda update python.app

and try again.

Let us know if that works.

**Comment by singhsaurabhaiims** [comment]
Hey,

I have tried again conda update python.app but it is already installed.

```
(spyder) saurabhsingh@Saurabhs-MacBook-Pro ~ % conda update python.app
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

# All requested packages already installed.

(spyder) saurabhsingh@Saurabhs-MacBook-Pro ~ % spyder
fromIccProfile: failed minimal tag size sanity
2024-10-21 20:05:11.911 python[9637:152776] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-21 20:05:11.912 python[9637:152776] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
/opt/anaconda3/envs/spyder/bin/pythonw: line 3:  9637 Segmentation fault: 11  /opt/anaconda3/envs/spyder/python.app/Contents/MacOS/python "$@"
```

**Comment by singhsaurabhaiims** [comment]
Hey, after looking into ticket https://github.com/spyder-ide/spyder/issues/20753. I also tried following commands:-

```
conda remove --force-remove python.app
conda install python.app
```
-----------------------------
```
(spyder) saurabhsingh@Saurabhs-MacBook-Pro ~ % conda remove --force-remove python.app

## Package Plan ##

  environment location: /opt/anaconda3/envs/spyder

  removed specs:
    - python.app


The following packages will be REMOVED:

  python.app-3-py39h46256e1_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(spyder) saurabhsingh@Saurabhs-MacBook-Pro ~ % conda install python.app
Channels:
 - defaults
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/spyder

  added / updated specs:
    - python.app


The following NEW packages will be INSTALLED:

  python.app         pkgs/main/osx-64::python.app-3-py39h46256e1_1 


Proceed ([y]/n)? y


Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(spyder) saurabhsingh@Saurabhs-MacBook-Pro ~ % spyder   
fromIccProfile: failed minimal tag size sanity
2024-10-21 21:33:59.165 python[14325:228475] +[IMKClient subclass]: chose IMKClient_Legacy
2024-10-21 21:33:59.165 python[14325:228475] +[IMKInputSession subclass]: chose IMKInputSession_Legacy
/opt/anaconda3/envs/spyder/bin/pythonw: line 3: 14325 Segmentation fault: 11  /opt/anaconda3/envs/spyder/python.app/Contents/MacOS/python "$@"
```

**Comment by ccordoba12** [comment]
I don't know what's happening because the latest version of `python.app` should fix the problem.

@cbouss, do you know what's happening in this case?

**Comment by cbouss** [comment]
@singhsaurabhaiims would you be able post the output of `conda list` of the affected environment?
I see in your first comment a reported version of python 3.12.4, while the python.app you updated is for python 3.9.

**Comment by singhsaurabhaiims** [comment]
@cbouss I have checked the environment and attached 
[spyder env_configuration.pdf](https://github.com/user-attachments/files/17485563/spyder.env_configuration.pdf)


```
(spyder) saurabhsingh@Saurabhs-MacBook-Pro ~ % python3 -V  
Python 3.9.20
```

**Comment by ccordoba12** [comment]
@singhsaurabhaiims, in case you haven't been able to solve your problem, please run the following commands to create an environment with conda-forge packages:

    conda create -n new-spyder-env -c conda-forge spyder=5
    conda activate new-spyder-env
    spyder

That should solve your problem, but let us know if it does.

**Comment by ccordoba12** [comment]
@AhmetOsmanoglu3402, according to the translation I got from DeepL your message is not polite at all. Please stop posting those messages or you'll be banished from our organization for a preventive amount of time.

**Comment by singhsaurabhaiims** [comment]
My spyder is working now thank you @ccordoba12 @cbouss 
<img width="1280" alt="Screenshot 2024-11-26 at 8 33 00 AM" src="https://github.com/user-attachments/assets/9d6044fe-cb3e-4b51-831f-b61b526e817e">

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
