### ISSUE TITLE
The menu title is incorrect

### ISSUE THREAD

**Issue by int0x09** [spyder-ide/spyder#22714]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Tools - Preferences - Code completion and syntax checking - Code style and formatting, "Line length" - "Maximum allowed rows" should be "... Maximum columns"
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by int0x09** [comment]
ver 5.5.6

**Comment by ccordoba12** [comment]
Hey @int0x09, thanks for reporting. It seems that's an error of the Chinese translation of the Spyder interface because no such text is present in English:

![imagen](https://github.com/user-attachments/assets/2fff3469-b10d-4cd6-9fdd-0ad5833d79bd)

Could you confirm if that's the case?

**Comment by int0x09** [comment]
"Maximum allowed line length"--->"Maximum allowed columns"

**Comment by ccordoba12** [comment]
@int0x09, so do you have this problem only with the Chinese version of Spyder?

**Comment by ccordoba12** [comment]
Closing due to lack of response.
