### ISSUE TITLE
Will there be a Russifier?

### ISSUE THREAD

**Issue by EliteRunner** [spyder-ide/spyder#22719]
I downloaded version 6.01 and there I had to roll back English to the old one

**Comment by ccordoba12** [comment]
Hey @EliteRunner, thanks for reporting. Unfortunately, it doesn't depend on us that Spyder is available in Russian. For that we rely on the help and good will of our team of Russian translators.

Sadly, for Spyder 6 they haven't lent us a hand to translate the many new and changed strings for that version, so we had to disable Russian as an available language for the interface.

If you'd like to help, you can join the Spyder project [in Crowdin](https://crowdin.com/project/spyder), the platform we use for translations, and help us with that. I think a lot of people will appreciate to see Spyder back in Russian again.
