### ISSUE TITLE
Cannot launch spyder using Mac

### ISSUE THREAD

**Issue by Ecoface** [spyder-ide/spyder#22715]
## Problem Description
I cannot launch the sypder using Anaconda. This is my first time to launch using my new Macbook. It produces the error like this :
/opt/anaconda3/bin/pythonw: line 3:  7169 Segmentation fault: 11  /opt/anaconda3/python.app/Contents/MacOS/python "$@"

![Image](https://github.com/user-attachments/assets/3bc25a22-3e46-4f4f-9a03-86503e10d966)

## Versions

* Spyder version: 5.5.1
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version:

**Comment by dalthviz** [comment]
Hi @Ecoface thank you for the report! I think this could be related with https://github.com/spyder-ide/spyder/issues/22144 Could you give that issue a check and see if any of the comments there helps? Probably, one that could worth a try is https://github.com/spyder-ide/spyder/issues/22144#issuecomment-2322154894

Let us know if the info above helps!

**Comment by dalthviz** [comment]
Closing due to lack of response
