### ISSUE TITLE
Custom environment not populating into Spyder

### ISSUE THREAD

**Issue by ceci3095** [spyder-ide/spyder#22712]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder IDE
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/) --> I use miniforge
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have been trying to use a custom environment in Spyder IDE. I successfully created the environment in Miniforge using the command "conda create --name myenv" in the Miniforge prompt. When I open the Preferences tab and navigate to the Python interpreter, I select the "Use the following Python interpreter" option and click the dropdown menu, but Spyder does not recognize my new environment. I can see the complete list of other environments with the exception of the new one.

## Attempts to Fix
there is a similar question in this channel, where the problem was that the env was created in Appdata and not in .conda but my env is indeed in .conda

Plus I restarted my computer, miniforge and Spyder. I have updated Spyder too. 

## Version
Spyder version: 6.0.1
Python 3.11.9 64-bit | Qt 5.15.8 | PyQt5 5.15.9 
Windows 11 Education

**Comment by ccordoba12** [comment]
Hey @ceci3095, thanks for reporting. You said:

> I successfully created the environment in Miniforge using the command "conda create --name myenv" in the Miniforge prompt

If the command you used to create your environment was `conda create --name myenv`, then it's an empty environment. And since it doesn't contain Python, then it's not shown in `Preferences > Main Interpreter` because Spyder can't work with it.

So, you can make your env available in Spyder by running these additional commands in the Miniforge prompt:

    conda activate myenv
    conda install python spyder-kernels=3

Let us know if that solves the problem for you.

**Comment by ceci3095** [comment]
Thank you! It works now

**Comment by ccordoba12** [comment]
Great! Glad things are working for you know.
