### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [spyder-ide/spyder#22732]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In https://github.com/spyder-ide/spyder/blob/5f4c5cd326ff3b2bbf7b96b95d9ad787aa2c0bb5/spyder/plugins/explorer/widgets/explorer.py#L1322 there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhanded exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, or any exception is raised from an `except:` clause, it will not propagate on as expected.

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

### What steps reproduce the problem?

Inspect source code.

### What is the expected output? What do you see instead?

Avoid return in finally.

## Versions

master branch

**Comment by ccordoba12** [comment]
Hey @iritkatriel, thanks for noticing this issue in our code and reporting it. We'll address it in our 6.0.2 version, to be released this week.
