### ISSUE TITLE
About spyder

### ISSUE THREAD

**Issue by Jenzzz** [spyder-ide/spyder#2273]
## Description

* *What steps will reproduce the problem?*
main menu    Help -> About Spider...

* *What is the expected output? What do you see instead?*
Expected output: I suppose is should be 2010 - 2015
I believe there is a typo in the Copyright year, 2010 - 1015. 

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.3
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  2.4.1 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
jedi >=0.8.1    :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
pylint >=0.25   :  1.4.1 (OK)

**Comment by Nodd** [comment]
Thanks, it was fixed in a465b2a345484aeb6f09deaf100570b30af8e8f1
