### ISSUE TITLE
An error occurred while starting the kernel

### ISSUE THREAD

**Issue by AGoh2019** [spyder-ide/spyder#22733]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
'chcp' is not recognised as an internal or external command, operable program or batch file

**Comment by ccordoba12** [comment]
Hey @AGoh2019, thanks for reporting. That's a problem with mamba or micromamba 2, so please downgrade to mamba/micromamba 1.5 and try again.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by AGoh2019** [comment]
"That's a problem with mamba or micromamba 2, so please downgrade to mamba/micromamba 1.5 and try again."

How do I downgrade to micromamba 1.5 for Spyder? Or can't you folks provide a patch.
Regards,
--- Andrew Goh
 

    On Monday, 18 November 2024 at 07:07:57 am SGT, Carlos Cordoba ***@***.***> wrote:  
 
 


Closing due to lack of response.

**Comment by ccordoba12** [comment]
It depends on how you installed Spyder and in what circumstances you found the error you reported. Since you provided no details in your initial post, I assumed it was related to mamba/micromamba 2.0.

So, please provide those details to give you better support.

**Comment by AGoh2019** [comment]
Hi, 
On start up, I get this message - "The console I/A shows this message - An error occurred while starting the kernel. 'chcp' is not recognised as an internal or external command, operable program or batch file'. Not connected to console.
--- Andrew Goh
 

    On Sunday, 24 November 2024 at 09:45:25 pm SGT, Carlos Cordoba ***@***.***> wrote:  
 
 


It depends on how you installed Spyder and in what circumstances you found the error you reported. Since you provided no details in your initial post, I assumed it was related to mamba/micromamba 2.0.

So, please provide those details to give you better support.
