### ISSUE TITLE
Connecting to a IPython console

### ISSUE THREAD

**Issue by sungengyi** [spyder-ide/spyder#22743]
### What steps will reproduce the problem?

I'm trying to connect to a remote spyder kernel. I have downloaded the kernel json file to local. This error occurs when I tried to connect to an existing connection.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\sunge\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1097, in create_client_for_kernel
    self._create_client_for_kernel(connection_file, hostname, sshkey,
  File "C:\Users\sunge\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\plugin.py", line 1924, in _create_client_for_kernel
    shellwidget.check_spyder_kernel()
  File "C:\Users\sunge\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 265, in check_spyder_kernel
    self.silent_exec_method(code)
  File "C:\Users\sunge\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole\widgets\shell.py", line 629, in silent_exec_method
    self._request_info['execute'][msg_id] = self._ExecutionRequest(msg_id,
TypeError: __new__() missing 1 required positional argument: 'hidden'
```

## Versions

* Spyder version: 5.0.5 
* Python version: 3.8.8
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  2.6.0 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0               :  8.12.2 (OK)
jedi =0.17.2                  :  0.17.2 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.3.1 (OK)
nbconvert >=4.0               :  7.10.0 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso =0.7.0                  :  0.7.0 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.15.1 (OK)
pylint >=1.0                  :  3.2.7 (OK)
pyls >=0.36.2;<1.0.0          :  0.36.2 (OK)
pyls_black >=0.4.6            :  0.4.6 (OK)
pyls_spyder >=0.3.2;<0.4.0    :  0.3.2 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.2 (OK)
qtawesome >=1.0.2             :  1.3.1 (OK)
qtconsole >=5.1.0             :  5.5.1 (OK)
qtpy >=1.5.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=39.0.0           :  75.1.0 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.0.4;<2.1.0 :  2.0.5 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  4.0.1 (OK)
zmq >=17                      :  25.1.2 (OK)

# Optional:
cython >=0.21                 :  3.0.10 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.24.3 (OK)
pandas >=1.1.1                :  1.5.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.13.2 (OK)
```

**Comment by sungengyi** [comment]
**Context:**    
I'm connecting to a spyder kernel running via a proxy server. I first logged in on the **login** node, then I ssh myself to the **gpu** node where I actually have my repository.     

**Solutions I tried**   
1. I added the proxy to my config file in ~/.ssh/config which looks like    
```bash
Host gpu
  HostName gpu
  User username
  ProxyJump login
  IdentityFile ~/.ssh/id_rsa

Host login
  HostName login
  IdentityFile ~/.ssh/id_rsa
  User username
```
This fixed my problem with remote connection on VSCode, but I still prefer Spyder. I tried reconnecting following the steps: [https://docs.spyder-ide.org/current/panes/ipythonconsole.html](url). Did not work for me.

2. I found a similar solution where I set up a ssh tunnel by `ssh -L 8888:username@login:22 username@gpu` [https://stackoverflow.com/questions/68106564/spyder-connect-to-remote-kernel-via-proxy](url). I checked port 8888 is listening and ran the cmd as administrator. I logged into **gpu**, then I re-tried with **connecting to an existing console** with hostname as localhost, port as 8888. This is the error message I got.
![image](https://github.com/user-attachments/assets/30c687d0-62b0-4b77-827a-e970d224d408)

I will keep looking into this. Please let me know what other methods I can try. Thanks!

**Comment by ccordoba12** [comment]
Hey @sungengyi, thanks for reporting. You're using a very old Spyder version (5.0.5), which has the bug you reported.

Please update to Spyder 5.5.6 and try again. Also, don't forget to update to spyder-kernels 2.5.2 in your remote machine to correctly establish the connection.

Let us know if that solves the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
