### ISSUE TITLE
How to correctly upgrade the built-in Python version of Spyder ?

### ISSUE THREAD

**Issue by int0x09** [spyder-ide/spyder#22740]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. I want to upgrade my Python version to a newer version. How do I do it correctly? thank you.
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  ver5.5.6 
* Python version:    python 3.8.10
* Qt version: 
* PyQt version: 
* Operating System name/version:  windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @int0x09, thanks for reporting. Unfortunately, that's not possible.

If you want to use a more recent Python version with our standalone installers, I'm afraid you'll have to install Spyder 6.0.1, which comes with Python 3.11.

**Comment by int0x09** [comment]
thanks.

Sypder6.0.1 is to fat, I prefer  spyder5.5.6.
