### ISSUE TITLE
Can not report issue from dev version

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2275]
```
Traceback (most recent call last):
  File "/home/joseph/prog/spyder.git/spyderlib/spyder.py", line 2273, in report_issue
    full, short = versions['revision'].split(':')
ValueError: need more than 1 value to unpack
```
It looks like this code is for mercurial and has no been updated for git: https://github.com/spyder-ide/spyder/blob/master/spyderlib/spyder.py#L2270

**Comment by ccordoba12** [comment]
I'll take a look at it, although I did update the code to work with git.

**Comment by Nodd** [comment]
You at least forgot to update the comment ;)

**Comment by ccordoba12** [comment]
Mmmh, I see what's happening now! :-)
