### ISSUE TITLE
Freeze when opening external terminal

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2276]
If I try to open an external terminal, spyder freezes and no terminal opens. I have to use ```kill -9``` to terminate it (a simple kill is not enough).

I can launch a script in an external terminal without any problem.

**Comment by ccordoba12** [comment]
What do you mean then by

> If I try to open an external terminal

And are you on master or on 2.3.4?

**Comment by ccordoba12** [comment]
Sorry, are you on Windows or Linux?

**Comment by Nodd** [comment]
Oh sorry, I'm on master branch on Linux.
The command is in the menu *Tools > Open a terminal*

**Comment by ccordoba12** [comment]
Ok, I'll take a look at it for beta1

**Comment by ccordoba12** [comment]
I can't reproduce this problem.

Could you test again? I merged PR #2247 some days ago that could help to solve this problem.

**Comment by Nodd** [comment]
It works on another machine, I'll have to retry on the machine which had a problem.

**Comment by manipuladordedados** [comment]
Maybe it's a bug in the script externalconsole.py
@ccordoba12 My fix is for programs.py

**Comment by ccordoba12** [comment]
This is working fine for me :-) Please reopen if you find the cause.
