### ISSUE TITLE
Spyder stops running by creating a simple data frame

### ISSUE THREAD

**Issue by mayouf** [spyder-ide/spyder#2283]
Hi every one,

I got a weird behavior with my spyder. 

I got a w7 pc with 16 gb of ram and a 125 gb ssd. I use only python console, no ipython at all.

I 've been testing some stuff with the panel from pandas. And I don't know why, my spyder keeps freezing every time I do this code below : 
 
import pandas as pd
from numpy.random import randn

x=randn(4,6)
x=pd.DataFrame(randn(4,6))

I had to retart my spyder each time, then it displays this message error and I need to open a new python console window to code again, because the '>>>' is not available. 

>>> Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\mickael\Anaconda\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\Users\mickael\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 571, in run
    self.update_remote_view()
  File "C:\Users\mickael\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 452, in update_remote_view
    remote_view = make_remote_view(ns, settings, more_excluded_names)
  File "C:\Users\mickael\Anaconda\lib\site-packages\spyderlib\widgets\externalshell\monitor.py", line 77, in make_remote_view
    collvalue=settings['collvalue'])
  File "C:\Users\mickael\Anaconda\lib\site-packages\spyderlib\widgets\dicteditorutils.py", line 164, in value_to_display
    return ', '.join(list(value.columns))
TypeError: sequence item 0: expected string, numpy.int64 found

But I already run this code before and it worked well. i did not change any configuration in the meanwhile.

Cheers

Mayouf.k

**Comment by mayouf** [comment]
It got really crazy for me, no way to use spyder,,,,even if I restart spyder. 
So upgraded pandas from 0.14 to 0.16 version with a "pip install --upgrade pandas".
It didn't work again. Then I did a "conda update spyder". I started spyder again....it worked !!!

But i wonder why it had that behavior...

**Comment by ccordoba12** [comment]
Yes, this error was fixed in Spyder 2.3.2. By the way, you shouldn't mix conda and pip packages, that could lead you to hard to debug problems.

**Comment by mayouf** [comment]
Thanks for letting us know about the bug and the tips about conda and pip package.

**Comment by ccordoba12** [comment]
@mayouf, the new pandas version is now available through conda.

Besides, my advise is directed to packages that are directly available through conda and that come with C and/or Fortran extensions. Using `pip` to install Python-only packages is a good strategy :-)
