### ISSUE TITLE
Spyder can't open files with spaces from the Windows Explorer

### ISSUE THREAD

**Issue by ilpresidente51** [spyder-ide/spyder#22844]
### What steps will reproduce the problem?

When double-clicking on a .py file in Windows 10 Explorer, Spyder 6 is opened, but the file is not opened

## Versions

* Spyder version: 6.0.2  (standalone)
* Python version: 3.11.10 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
aiohttp >=3.9.3                  :  3.10.10 (OK)
asyncssh >=2.14.0,<3.0.0         :  2.18.0 (OK)
atomicwrites >=1.2.0             :  1.4.1 (OK)
chardet >=2.0.0                  :  5.2.0 (OK)
cloudpickle >=0.5.0              :  3.1.0 (OK)
cookiecutter >=1.6.0             :  2.6.0 (OK)
diff_match_patch >=20181111      :  20241021 (OK)
github >=2.3.0                   :  2.4.0 (OK)
importlib_metadata >=4.6.0       :  8.5.0 (OK)
intervaltree >=3.0.2             :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1 :  8.29.0 (OK)
jedi >=0.17.2,<0.20.0            :  0.19.1 (OK)
jellyfish >=0.7                  :  1.1.0 (OK)
jsonschema >=3.2.0               :  4.23.0 (OK)
keyring >=17.0.0                 :  25.5.0 (OK)
nbconvert >=4.0                  :  7.16.4 (OK)
numpydoc >=0.6.0                 :  1.8.0 (OK)
parso >=0.7.0,<0.9.0             :  0.8.4 (OK)
pexpect >=4.4.0                  :  4.9.0 (OK)
pickleshare >=0.4                :  0.7.5 (OK)
psutil >=5.3                     :  6.1.0 (OK)
pygments >=2.0                   :  2.18.0 (OK)
pylint >=3.1,<4                  :  3.3.1 (OK)
pylint_venv >=3.0.2              :  3.0.4 (OK)
pyls_spyder >=0.4.0              :  0.4.0 (OK)
pylsp >=1.12.0,<1.13.0           :  1.12.0 (OK)
pylsp_black >=2.0.0,<3.0.0       :  2.0.0 (OK)
pyuca >=1.2                      :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0        :  3.2.3 (OK)
qstylizer >=0.2.2                :  0.2.3 (OK)
qtawesome >=1.3.1,<1.4.0         :  1.3.1 (OK)
qtconsole >=5.6.1,<5.7.0         :  5.6.1 (OK)
qtpy >=2.4.0                     :  2.4.1 (OK)
rtree >=0.9.7                    :  1.3.0 (OK)
setuptools >=49.6.0              :  75.3.0 (OK)
sphinx >=0.6.6                   :  8.1.3 (OK)
spyder_kernels >=3.0.1,<3.1.0    :  3.0.1 (OK)
superqt >=0.6.2,<1.0.0           :  0.6.7 (OK)
textdistance >=4.2.0             :  4.6.2 (OK)
three_merge >=0.1.1              :  0.1.1 (OK)
watchdog >=0.10.3                :  5.0.3 (OK)
yarl >=1.9.4                     :  1.16.0 (OK)
zmq >=24.0.0                     :  26.2.0 (OK)

# Optional:
cython >=0.21                    :  3.0.11 (OK)
matplotlib >=3.0.0               :  3.9.2 (OK)
numpy >=1.7                      :  2.1.2 (OK)
pandas >=1.1.1                   :  2.2.3 (OK)
scipy >=0.17.0                   :  1.14.1 (OK)
sympy >=0.7.3                    :  1.13.3 (OK)
```

**Comment by dalthviz** [comment]
I think I was able to reproduce this with a file which has spaces in its name, @ilpresidente51 does the filename that you are trying to open has spaces in its name or path? Let us know!

**Comment by ilpresidente51** [comment]
You are right, the problem occurs when there is a space in the file name or in its path.

**Comment by Merlin820** [comment]
I also have this issue. Can confirm it happens when the path has spaces, but the same file opens as expected when the path does not have spaces. (Apologies if this is unnecessary/redundant, I'm brand new to using Github and Spyder.)

**Comment by ccordoba12** [comment]
Hey @Merlin820, thanks for the confirmation. We'll try to take a look at this issue in 6.0.4, to be released at the end of next month.

**Comment by ccordoba12** [comment]
@mrclary, could you take a look at this one?

**Comment by mrclary** [comment]
I've discovered the underlying issues is that the registry command does not quote the input argument, e.g. `%1` instead of `"%1"`. Unfortunately, this will require a fix by `menuinst`.

**Comment by ccordoba12** [comment]
Thanks @mrclary! Do you know how to fix that in `menuinst`?

**Comment by mrclary** [comment]
I've submitted conda/menuinst#290 and inquired about a possible permanent solution. However, I have also discovered a workaround and applied it in conda-forge/spyder-feedstock#212. A new build for 6.0.3 should fix the problem.

**Comment by ccordoba12** [comment]
> However, I have also discovered a workaround and applied it in https://github.com/conda-forge/spyder-feedstock/pull/212.

Great! Thanks for your help with that.

> A new build for 6.0.3 should fix the problem.

You mean a new build of the installers? Mmhh, that would cause us to lose our current number of downloads, which I don't like too much. So, I'd prefer to leave it for 6.0.4.

**Comment by mrclary** [comment]
> > A new build for 6.0.3 should fix the problem.
> 
> You mean a new build of the installers? Mmhh, that would cause us to lose our current number of downloads, which I don't like too much. So, I'd prefer to leave it for 6.0.4.

No, I mean just a new build for 6.0.3 on conda-forge. Of course this fix will not propagate to our installers until 6.0.4 is released.

Although, we could consider looking at new builds in our update manager, not just new versions?
