### ISSUE TITLE
Run selection disappeared.

### ISSUE THREAD

**Issue by sangheumcho** [spyder-ide/spyder#22849]
Hi. It seems like the "run selection" is disappeared in the preference - keyboard shortcuts.

* Spyder version: 6.0.1

Could you restore the function?

Thank you.

**Comment by ccordoba12** [comment]
Hey @sangheumcho, thanks for reporting. This is a duplicate of issue #22516 and we'll try to fix it in our next version (6.0.3), to be released at the end of the month.
