### ISSUE TITLE
Copying from Spyder and pasting into LibreOffice displays strange comments

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2285]
I'm on Ubuntu 14.04 and I just tested this on the latest Spyder (commit 43825ba).

Copy some code from Spyder, then paste it into LibreOffice, and it'll have strange comments.  I believe it should just be copying text to the clipboard.

![screenshot from 2015-03-29 20 14 08](https://cloud.githubusercontent.com/assets/6614695/6889683/3387543e-d650-11e4-8121-4ea72dc2d399.png)

**Comment by Nodd** [comment]
I have the same problem. A workaround is to paste with no formatting, but it should work out of the box.

I think that the problem comes from metadata that is either incorrectly set or incorrectly read.

**Comment by ccordoba12** [comment]
Does this happens when copying from the Editor or from our consoles?

I really don't understand why this is happening. We'll need to investigate further to see if we are changing/adding things when copying.

**Comment by Garrett-R** [comment]
@ccordoba12, sorry, I forgot to say it happens from the editor, and does not happen when copying from the console.
