### ISSUE TITLE
No highlight of py3 files

### ISSUE THREAD

**Issue by mesti90** [spyder-ide/spyder#22854]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Py3 files are not among the supported text file, and I cannot higlight the syntax there

## Versions

* Spyder version: 6.0.2
* Python version: 3.11.10 64-bit
* Qt version: 5.15.8
* PyQt version: 5,15,
* Operating System name/version: Linux Mint 21.3 Linux 5.15.0-122-generic x86_64

**Comment by ccordoba12** [comment]
Hey @mesti90, thanks for reporting. As far as I know, `py3` is not a regular Python file extension. That's why is not supported in Spyder.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
