### ISSUE TITLE
Disable icons in menus on Mac OS X

### ISSUE THREAD

**Issue by cbrnr** [spyder-ide/spyder#2289]
Most OS X apps do not include icons in their menus. It would be nice to have an option to disable icons on Mac OS X (maybe this should even be the default behavior).

**Comment by goanpeca** [comment]
Hi @cle1109 can you post a couple of images of how spyder looks in your setup, and how another "normal"applications look? just to get the feeling of the issue?

Cheers

**Comment by cle1109** [comment]
Sure! Here are some Spyder menus:

![spyder-mac-00](https://cloud.githubusercontent.com/assets/4377312/6915623/e0b8aa4a-d795-11e4-9dac-741d4e91bd61.jpg)
![spyder-mac-01](https://cloud.githubusercontent.com/assets/4377312/6915627/ebd0455a-d795-11e4-805a-2f6b0766b0ab.jpg)
![spyder-mac-02](https://cloud.githubusercontent.com/assets/4377312/6915631/f191566e-d795-11e4-89c5-73d79112b4ce.jpg)

Menus of real/native Mac applications look more like this:
![excel-mac-00](https://cloud.githubusercontent.com/assets/4377312/6915640/111476c4-d796-11e4-9494-fff2d5c687ac.jpg)
![excel-mac-01](https://cloud.githubusercontent.com/assets/4377312/6915641/141177c8-d796-11e4-8748-46bf91f14dab.jpg)
![finder-mac-00](https://cloud.githubusercontent.com/assets/4377312/6915645/171b052e-d796-11e4-9a6c-7acd167f898a.jpg)
![finder-mac-01](https://cloud.githubusercontent.com/assets/4377312/6915646/19ef7988-d796-11e4-92f3-3f9227a5419c.jpg)

Note that sometimes there are exceptions to the rule (last image, places actually do have icons in the menu), but I think Spyder would look best without icons.

**Comment by goanpeca** [comment]
Seems reasonable, what do you think @ccordoba12?

**Comment by ccordoba12** [comment]
We just need to disable icons for menus on Mac, period :-) There is no need to add an option for this.

As @cle1109 rightly points out, icons in menus are not part of Mac applications at all, so we need to follow that convention too.

**Comment by goanpeca** [comment]
Good! 

since I do not work on a Mac (although I could make the PR) I think is better that someone with access to one takes this one, right?

**Comment by tienhv** [comment]
Hi,
How could I enable icons in Mac, because without icons, Spyder3 looks ugly and broken, like this
<img width="209" alt="screenshot 2016-09-29 14 28 28" src="https://cloud.githubusercontent.com/assets/9072983/18954211/3015280e-8652-11e6-9736-874b404f5088.png">

**Comment by goanpeca** [comment]
Hi @tienhv, this is a Qt Bug to the best of our knowledge :-|, but we are working on a fix for this.

**Comment by cbrnr** [comment]
@goanpeca I assume you mean the weird indents? Because Mac programs generally do not have icons in their menus.

**Comment by tienhv** [comment]
@goanpeca yes, and I also comment out line 2924 and 2925 of app/mainwindow.py and still no icons.

**Comment by goanpeca** [comment]
@cbrnr yes the weird indents, its sort of a Qt bug, we have a fix for it... but its a hack to overcome the bug, so we are not super happy BUT at least it will make it look nice :-)

**Comment by tienhv** [comment]
@goanpeca so is it possible to bring back the icons, if yes, how to do it? I found line 2924 and 2925 of app/mainwindow.py which should be commented out, and anything else?

**Comment by goanpeca** [comment]
No, that is not the fix we are talking about. I meant a fix to disable the weird indents as 

>Because Mac programs generally do not have icons in their menus.

prevails here

**Comment by ccordoba12** [comment]
@goanpeca, please don't reopen issues that are already closed.They are added referenced from other issues and added to our Changelog.

This was correctly fixed by us, other thing is that this is a Qt bug. So we need another issue for this and #3484 seems the right one.
