### ISSUE TITLE
Open last closed shortcut (Ctrl+Shift+T) does not work

### ISSUE THREAD

**Issue by thangleiter** [spyder-ide/spyder#22912]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The Open last closed file shortcut in the editor does not work in Spyder 6.

### What steps reproduce the problem?

1. Open file
2. Close the file
3. Press `ctrl+shift+T`

## Versions

* Spyder version: 6.0.2 (conda), but also with the installer
* Python version:  3.12.7 64-bit
* Qt version: 5.15.8
* PyQt version: 5.15.9
* Operating System name/version: Linux 6.11.2-4-MANJARO (x86_64) , Windows 10

**Comment by dalthviz** [comment]
Hi @thangleiter thank you for the report! I was able to reproduce this. We will give this a check in a future release :+1:

**Comment by jitseniesen** [comment]
I actually looked at the code for this shortcut earlier today in the context of #22564 but I did not notice the bug. I will write a quick PR while everything is still fresh in my mind.

**Comment by dalthviz** [comment]
Awesome! Thanks @jitseniesen !
