### ISSUE TITLE
Change main package inside spyder, from spyderlib to spyder

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2292]
Is there any reason to keep the name `spyderlib` as the main package inside spyder?

If no, why not change it to spyder @ccordoba12 ?

**Comment by ccordoba12** [comment]
This is essentially a duplicate of issue #1320. The main purpose of moving the major version to 3.0 is precisely to do this change (and also a bit of reorganization).

**Comment by goanpeca** [comment]
Great :-)
