### ISSUE TITLE
Rejecting the Update to Spyder 6.02

### ISSUE THREAD

**Issue by RussT-n8** [spyder-ide/spyder#22932]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Rejecting the update to Spyder 6.02 from the start (clicking "NO") results in the error. 

I am running Spyder from Anaconda and Spyder 6.02 is not yet available as an update for the Environment so I am rejecting the update in this  this environment. 

I have already successfully accepted the update outside Anaconda.

**Comment by ccordoba12** [comment]
Hey @RussT-n8, thanks for reporting. This error in fixed in our latest version (6.0.2), so please update to it in case you haven't done it yet (it's not quite clear if you already did).
