### ISSUE TITLE
Anaconda 2.2 update causes Spyder to crash on KDE based Linux distros

### ISSUE THREAD

**Issue by wigging** [spyder-ide/spyder#2294]
After installing the latest version of Anaconda 2.2 on a Linux machine, I could not launch Spyder or other python applications that used Qt for the gui.  I received the following error:

![screenshot](https://cloud.githubusercontent.com/assets/6828967/6942748/97b943c8-d857-11e4-925d-f7615fe92ab4.png)

In the `/usr/bin/qtconfig` I had to change the **GUI Style** to anything other than **Oxygen** to make Spyder launch and use other qt applications.

After making the above changes, everything in Spyder works fine except clicking on the **File explorer** tab causes the entire application to crash.

![screen9](https://cloud.githubusercontent.com/assets/6828967/6942981/114a645a-d859-11e4-9d0b-dc05039e06d1.png)

The error from the crash is another `symbol lookup error`:

![screen10](https://cloud.githubusercontent.com/assets/6828967/6943063/9660b540-d859-11e4-8524-f8d96823a84c.png)

The **Object inspector** and **Variable explorer** tabs work fine.

**Comment by Nodd** [comment]
I suppose it's linked to this comment: https://github.com/spyder-ide/spyder/pull/2281#issuecomment-88255168

**Comment by ccordoba12** [comment]
This problem is directly related to the Qt version shipped by Anaconda, and it doesn't have anything to do with Spyder per se.

@wigging, it seems that the changing styles option is not enough. So I'm going to compile and provide a new Qt version for Anaconda, tailored specifically to work with KDE based distros.  i'll create a special Binstar channel to upload it, and I'll let you know when it's ready here (hopefully tomorrow :-)

**Comment by ccordoba12** [comment]
@wigging, we (i.e. Continuum) updated our Qt and PyQt packages yesterday to solve this problem (without changing styles or using a special Binstar channel).

Just run

    conda update pyqt

and let us know if now things work for you :-)

**Comment by wigging** [comment]
@ccordoba12 The `pyqt` update fixed the problems I was having with Spyder on Linux.  Everything is working now.

**Comment by ccordoba12** [comment]
Glad it works for you know. It took like three or four days to find the error ;-)
