### ISSUE TITLE
Line numbers misaligned when zooming and scrolling

### ISSUE THREAD

**Issue by dnowacki** [spyder-ide/spyder#2296]
In the Sypder 2.3.4 editor on OS X (10.10.2), line numbers can become misaligned with the highlighted line of text when scrolling. When scrolling down, they become progressively misaligned. After scrolling so the line is off the page and then scrolling up, they are again properly aligned (until scrolling back down again).

After scrolling down to line 100:
![screen shot 2015-04-02 at 09 26 52](https://cloud.githubusercontent.com/assets/7505077/6964779/6f966a74-d91a-11e4-87e9-55ac9323ff37.png)

After scrolling past line 100 until it is off screen, then back up to line 100:
![screen shot 2015-04-02 at 09 29 12](https://cloud.githubusercontent.com/assets/7505077/6964822/c1327b20-d91a-11e4-9e16-997e7983aa6a.png)

**Comment by goanpeca** [comment]
Hi, some questions

Scrolling with mouse? with arrow? with...? Can you test different options and list results on each?

Thanks

**Comment by dnowacki** [comment]
Hi, scrolling with mouse via scrollbar, mouse with wheel, and with arrow key on keyboard all have the same result. After more testing, a better generalization of the issue is: **lines close to the bottom of the editor window are misaligned with their line numbers**.

**Comment by Nodd** [comment]
Do you have a retina display ? It may be something like a roundoff error when computing pixel size, or something like that...

**Comment by dnowacki** [comment]
Yes, this is on a Retina iMac.

**Comment by ccordoba12** [comment]
I don't know how we could fix this because no one in the dev team has a Retina display Mac to test and fix this problem.

**Comment by dnowacki** [comment]
OK, understood. Please let me know if I can help by running any tests, etc. Also I'll point out that the issue can also cause cell mode dividers to overlap with text.
![screen shot 2015-04-03 at 09 40 19](https://cloud.githubusercontent.com/assets/7505077/6982884/7801e226-d9e5-11e4-9273-6097f84f0bce.png)

**Comment by Nodd** [comment]
We need more donations ;)

**Comment by ccordoba12** [comment]
I know! I'll work on setting things through NumFocus after I release beta1 ;-)

**Comment by kouichi-c-nakamura** [comment]
I noticed the same issue! Spyder 2.3.4 on Yosemite. It looks to me that the font used for the line numbers does not change according to the Font setting for the Editor. Each font has slightly different height, so this might be related to the issue.

**Comment by ccordoba12** [comment]
@kouichi-c-nakamura, that's a very good point! I'll see how we define the font for the line number area.

**Comment by ccordoba12** [comment]
Just for the record in case people come to this issue: The misalignment between line numbers and code only shows for the **Monaco** font. That's why we changed the default font to **Menlo**.
