### ISSUE TITLE
Cannot stop executing when runing a flask app with debug=True

### ISSUE THREAD

**Issue by haming** [spyder-ide/spyder#2298]
All the packages are newest, on windows8
![2015-04-03_223419](https://cloud.githubusercontent.com/assets/7751806/6983571/19a7e032-da52-11e4-9863-17f83eb36c3b.png)
Already click the stop button, but it did't stop.
Code to repeat the issue

    from flask import Flask
    app = Flask(__name__)
    app.run(debug=True)

**Comment by ccordoba12** [comment]
This is a bug. I already noticed it but haven't had time to fix it.
