### ISSUE TITLE
IPython preference "Automatically load Pylab and Numpy Modules" not followed

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#2299]
## Description

* *What steps will reproduce the problem?*

1. Start Spyder, ensure that the option Ipython->Graphics->Automatically load Pylan and NumPy modules is set
2. Attempt to use any of the numpy/pylab functions without manually importing or using %pylab in ipython shell.

* *What is the expected output? What do you see instead?*
Functions should be loaded into current namespace and available for use, instead get name 'x' us not defined. Issuing %pylab, or importing modules manually works as expected.

* *Please provide any additional information below*
Seems to be the same on both Linux and Win64, I think Spyder 2.3.3 was ok.

The startup banner for IPython shell reads:

Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

Populating the interactive namespace from numpy and matplotlib

Which suggest it is getting the options and detecting matplotlib ok etc.
## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks a lot for reporting. I'll take a look at it for 3.0beta1.

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 2.3.5 (to be released in one week :-). Thanks for your patience.
