### ISSUE TITLE
cannot be used

### ISSUE THREAD

**Issue by 1zhengli1** [spyder-ide/spyder#23004]
EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\anaconda3

**Comment by ccordoba12** [comment]
Hey @1zhengli1, thanks for reporting. How did you get this error? When you were trying to update Spyder?

If that was the case, you need to open an Admin system terminal (i.e. `cmd.exe`) to run the command that will do the update.

Let us know if that solves the problem for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
