### ISSUE TITLE
Help needed to make a plugin work for spyder 6.*

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#23013]
I have made a plugin for spyder, which I’ve been using in spyder 5.* for years. I need help to make it work for spyder 6.*.

I’m not a programmer nor expert, I don’t know how to debug a plugin (I wrote scripts to process data usually). I’m hoping someone can point out what’s wrong, or some instruction or guidance I can follow. I’ve tried to start Spyder from the command line, and no useful message.

Plugin url: [https://github.com/gepcel/ihelper](https://github.com/gepcel/ihelper)

What’s plugin for?

There’s a useful function of spyder called “inspect current object”, which works differently for editor and ipython console. Sometimes, with a function or object, after `Ctrl + I`, I can’t get help information from editor, but can from ipython console. So I often need to copy some code to ipython console to get a help information, and go back to editor to work on. As a data scientist, I need this quite often.

So what this plugin mainly does is to find out the current object in editor and request help from `help pane`, pretend it’s a request from ipython console. And regist this to spyder plugin , add an entry to keyboard shortcut, and show in status bar.

**Comment by dalthviz** [comment]
Hi @gepcel thank you for reaching out and sorry for the late response! Indeed there are some changes minimum that a plugin needs to do to be able to launch with Spyder 6 (as example of changes required you could check some PRs for external plugins like https://github.com/spyder-ide/spyder-line-profiler/pull/87). Besides that, changes where done to the Editor so maybe that could be causing some troubles for your plugin too 🤔

I'm not totally sure what the specific problem could be for you plugin but if you can share a traceback or something similar maybe we could be able to at least point you into the right track for a fix. To get such a traceback maybe you will need to launch Spyder in debug mode. So from a terminal/cmd launch Spyder with the `debug-info` flag (`spyder --debug-info verbose`). You could also launch Spyder in debug mode from the Spyder GUI by using the `Restart in debug mode` option (`File > Restart in debug mode`).

Let us know if the info above helps/you have more debug information from your plugin!

**Comment by gepcel** [comment]
Thanks. 
Indeed, there's the same issue with [spyder-line-profiler/pull/87](spyder-line-profiler/pull/87), I've made the same [changes commits](https://github.com/gepcel/ihelper/commit/fd3e5afa60292d93a871fb044b5e666ce41013bf). But there are still other problems.

1. Inside Spyder preferences, this plugin shows up in the `Plugins` page, but not in the `Keyboard shortcuts` page. 
2. But there used to be one in the `Keyboard shortcuts` page, so I can assign a shortcut to it.
3. There is no show-up in the status bar.  There used to be a status showing that the plugin loads up.


[spyder-debug.log](https://github.com/user-attachments/files/17838907/spyder-debug.log)


<img src="https://github.com/user-attachments/assets/a3a162b4-90b4-4880-b36c-18117feeb5eb" width=600px >

**Comment by gepcel** [comment]
Updates:

Now the status bar works. Still unable to register shortcut, so I don't know if the plugin works or not.

**Comment by gepcel** [comment]
@dalthviz Hi, sorry to bother. I appreciate some help here.

After trying fixing and some imitating, the plugin partially works. Now by clicking either the statusbar or the toolbar, the plugin works. But I registered an entry into `Keyboard shortcuts` page of preferences, assigned it to a shortcut key (Alt+G for example), but nothing happens after pressing the shortkey.

The shortcut registering code was mainly [7 lines](https://github.com/gepcel/ihelper/blob/3e6c959e1a2d2b369d5b3f55aa9f342d6301f247/ihelper/spyder/plugin.py#L59C1-L65C10). Would you mind take a look what I'm doing wrong?

<img src="https://github.com/user-attachments/assets/a42a04f9-ff0f-4a3c-bd03-a1b7a8d2afa8" width=580px>

**Comment by dalthviz** [comment]
Thinking about this a little bit more, maybe this is not related with #23024 and what is needed is passing to the action creation method something like `context=Qt.ApplicationShortcut` 🤔 Could you give it a try to that too please?

**Comment by gepcel** [comment]
Passing `context=Qt.ApplicationShortcut` to the action creation method works, but it's on another computer. I'll double-check it when I'm back in the office.

**Comment by ccordoba12** [comment]
@gepcel, do you want your shortcut to work globally, i.e. when pressed anywhere in Spyder? Or only when a specific plugin has focus, e.g. the Editor?

**Comment by gepcel** [comment]
The shortcut only need to work when the Editor has focus.

**Comment by gepcel** [comment]
> Thinking about this a little bit more, maybe this is not related with #23024 and what is needed is passing to the action creation method something like `context=Qt.ApplicationShortcut` 🤔 Could you give it a try to that too please?

Passing `context=Qt.ApplicationShortcut` works. Thank you very much.

**Comment by ccordoba12** [comment]
@gepcel, that makes your shortcut work globally, but it's the best you can do using our current API. In the future, we'll try to add an API to register shortcuts just for the editor.
