### ISSUE TITLE
Problem with compilation of coding in Python , please helpe me 

### ISSUE THREAD

**Issue by Japanidze** [spyder-ide/spyder#23035]
# -*- coding: utf-8 -*-
from kivy.app import App
from kivy.lang import Builder
from kivy.uix.boxlayout import BoxLayout
from kivy.properties import StringProperty
from kivy.uix.button import Button

# Kivy язык для описания интерфейса
KV = '''
<MyBl>:
    orientation: 'vertical'  # Добавляем ориентацию
    Label:
        font_size: '30sp'
        text: root.data_label
    Button: 
        text: "Поиск по названию"
        bold: True
        background_color: (0, 1, 0.8, 1)  # Используем RGBA формат
        size_hint: (1, 0.5)
        on_press: root.callback()
'''

class MyBl(BoxLayout):
    data_label = StringProperty('Hello, Kivy!')  # Начальный текст

    def callback(self): 
        print("Поиск по названию")

class MyApp(App):
    def build(self):
        return Builder.load_string(KV)  # Загружаем интерфейс из строки KV

    def on_stop(self):
        print("Приложение остановлено.")

if __name__ == '__main__':
    MyApp().run()

**Comment by Japanidze** [comment]
File "C:\Users\sergu\source\repos\дораб1.py\дораб1.py\дораб1.py.py", line 16
    data_label = StringProperty('�����������')  # Corrected string
                                     ^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
Для продолжения нажмите любую клавишу . . .

**Comment by ccordoba12** [comment]
Hey @Japanidze, thanks for reporting. It seems this is a problem with Kivy and not with Spyder, so please report it here:

https://github.com/kivy/kivy
