### ISSUE TITLE
not installing on Mac 

### ISSUE THREAD

**Issue by lewisturner729** [spyder-ide/spyder#23041]
<img width="1412" alt="Screenshot 2024-11-21 at 14 26 28" src="https://github.com/user-attachments/assets/07a19afa-8cf2-4e81-8378-6f7e225e1632">

<img width="1412" alt="Screenshot 2024-11-21 at 14 26 28" src="https://github.com/user-attachments/assets/71168e23-b98d-4b16-9033-623ca1f20bc4">

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @lewisturner729, thanks for reporting. I have a couple of questions for you to better understand your problem:

1. What's your macOS version?
2. Do you have an Intel or M1/M2, etc chip?

**Comment by lewisturner729** [comment]
Hi there, 

Thanks for replying, I’m on OS 15.1.1 running intel core i5

**Comment by lewisturner729** [comment]
Hi Carlos

Thank you, I did actually try both and they both came up with the same error, however an anaconda technician suggested I enter in some commands in the Mac terminal which has fixed the issue

Many thanks,

Lewis

**Comment by ccordoba12** [comment]
Great! Could you let us know what fixed the problem for you?

Maybe that could be useful for others.

**Comment by ccordoba12** [comment]
Thanks! It seems you didn't have own permissions over several files in your user home directory, which are necessary to run the installer.

That's really odd but fortunately you found someone that came up with that idea (it didn't occur to me).
