### ISSUE TITLE
execution lag in python console of Spyder environment using windows 7 x64 Anaconda

### ISSUE THREAD

**Issue by remcmurry** [spyder-ide/spyder#2304]
This issue seems very similar to the one discussed in issues #1611 and #1714.

i am running a dell with windows 7 AMD64
Anaconda   2.2.0
Python        3.4.3
matplotlib    1.4.3
pandas        0.15.2
statsmodels 0.6.1
numpy         1.9.2

I am mostly running code from cells in the console.  some cells seem to case some amount of lag in execution and I end up having to hit return a few times to see results. as the session progresses I gets progressively worse.  It seems like the lag adds up as a problem cell is run more times.  after a while it can get to having to hit return well over 20 times to see a graph or get a result summary printed to the console.  This looks a lot like the issue(s) mentioned above. I have tried updating anaconda using their method from the FAQ section on the Continuum Analytics website.

I seem to mostly have problems in cells that have plotting commands mostly matplotlib.pyplot
other major modules i have imported when this occurs are pandas statsmodels  and numpy

I'm sorry if this is a repeat of a previous issue ... the ones above are the only ones i could find.

thanks,

Robbie

**Comment by ccordoba12** [comment]
This seems more related to issue #1831. Are you generating plots as part of the run you're running?

**Comment by remcmurry** [comment]
Thanks for the update, good luck in finding any solutions. I will follow along in the #1831 thread for future news.

**Comment by ccordoba12** [comment]
Ok, closing this one then.

**Comment by remcmurry** [comment]
that is fine

Cheers

Robert (Robbie) McMurry
Assistant Development Engineer, Western Cooling Efficiency Center
Minister, Davis Bike Collective (Bike Forth)
remcmurry@gmail.com
mobile: (575) 323 4561
