### ISSUE TITLE
Debugger does not use global presets to run in console's namespace

### ISSUE THREAD

**Issue by Arthanor** [spyder-ide/spyder#23052]
I recently updated Spyder to 6.0.1 and have the following issue:
My configuration for the debugger and regular ipython console are set like this:
![image](https://github.com/user-attachments/assets/58b78414-c663-4665-82e4-ff36b81aa159)

However, when debugging a file, what gets executed in the console is: 

`%debugfile 'Path/To/File.py' --wdir`

instead of doing like when running a file and keeping my variables:

`%runfile 'Path/To/File.py' --wdir --current-namespace`

Manually adding the `--current-namespace` to the wrong command does make it work properly.

**Comment by ccordoba12** [comment]
Hey @Arthanor, thanks for reporting. This is basically the same problem as the one reported in issue #22496, in the sense that we're passing the global or per file debugging options set by users to the `debugfile` command.

We'll try to fix that in our 6.0.4 version, to be released at the beginning of next year.
