### ISSUE TITLE
`REQUIRED.app` is installed by Spyder macOS installer

### ISSUE THREAD

**Issue by rkr8** [spyder-ide/spyder#23062]
## Problem Description
Apple Silicon Installer of Spyder installs application "REQUIRED.app"

### What steps reproduce the problem?

1. Downloaded Spyder installer from official website [https://www.spyder-ide.org/download?os=mac&arch=arm64](https://www.spyder-ide.org/download?os=mac&arch=arm64)
2. Installed Spyder using installer
3. Strange application "REQUIRED.app" is installed alongside Spyder

### Problem
Hey everyone! I’ve just installed the Spyder IDE (MacOS, Apple Silicon Installer) from the official website and noticed that it also installed another application with the name "REQUIRED.app" in $HOME/Applications alongside Spyder.app. I didn’t information about it on the Issues page, so I was wondering: What is REQUIRED.app actually for and is it supposed to be there? It doesn’t have any Icon or description, and i think it’s also not signed.

Thank you in advance!

**Comment by acaihello** [comment]
it is appeared on my laptop(Ubuntu LTS24.04)

**Comment by ccordoba12** [comment]
Hey @rkr8, thanks for reporting. I have a quick question for you: does that app show up for you in Spotlight?

**Comment by ccordoba12** [comment]
@mrclary, do you know if we install an extra app alongside the Spyder one?

**Comment by rkr8** [comment]
Hi @ccordoba12, thank you for the fast reply! Yes, it shows up in Spotlight also:
<img width="578" alt="image" src="https://github.com/user-attachments/assets/8addc9fc-02a7-4bac-a69e-e1dcd00775bf">

From the checksum it seems that the binary inside of it
`$HOME/Applications/REQUIRED.app/Contents/MacOS/required`
is the same as:
`$HOME/Applications/Spyder 6.app/Contents/MacOS/spyder-6`

**Comment by mrclary** [comment]
This is the result of the second shortcut listed in `spyder-menu.json`. This was my mistake in that I thought the reset Spyder shortcut would only be created on Windows. When I tested this change, I did not notice this error. 

Nevertheless, this issue will be fixed with conda-forge/spyder-feedstock#204. Until then, this application is harmless and can be deleted.

My apologies for the inconvenience.

**Comment by mrclary** [comment]
When conda-forge/spyder-feedstock#204 is merged (a new build to Spyder 6.0.2), then any new updates to Spyder 6.0.2 will not have this problem. Additionally, I believe that users with the old build will see the application removed upon updating to the next Spyder version when it is released.

**Comment by ccordoba12** [comment]
@rkr8, thanks for checking. As @mrclary, you can simply ignore or remove that app until we release 6.0.3.

@mrclary, thanks for your promptly reply! And glad you know you already worked on a fix for this.
