### ISSUE TITLE
Enhancement: Add restart functionality to spyder.

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2306]
This is somehow related to #1921.

The idea is that it would be great to be able to restart spyder from within spyder so that if a new library has been installed (lets say using conda or pip or apt or whatever package manager) we could offer some way to do this automatically.

I guess somewhere along the lines of http://stackoverflow.com/questions/15221361/how-to-restart-pyqt4-application

This would allow to have an updates available button message etc... but that is another issue

**Comment by goanpeca** [comment]
Another way of doing this without changing spyder code too much, would be to have a helper Application that would handle the restart on behalf of Spyder directly and we could add this as a script when installing spyder (spyder_restarter.bat, spyder_restarter.exe) that would get called before closing spyder with a handle to the process ID (of the current spyder being closed), then this helper application would get fired from a QProcess wityh some flags

`spyder_restarter --pid PID`

This new process... (pure python... qt or bash or whatever we find appropriate) would run and wait for the PID to get killed to ensure spyder closed succesfully, and only then it would re run spyder.

We would need to cache in environment (I guess) how spyder was run the first time, to make sure to pass the same flags on restart (if this is something we would like to have)

**Comment by Nodd** [comment]
Good idea. It will help test plugins, too, since spyder has to be restarted quite a lot.

**Comment by goanpeca** [comment]
@nodd Which approach do you like best, or you would favor?

**Comment by Nodd** [comment]
No idea !

**Comment by ccordoba12** [comment]
This is easy to implement when you're a single instance because Spyder's PID is associated with the `spyder.lock` file (present in `~/.spyder`). This file is used to check if there's an open instance so users can't open a new one.

However, we also offer the possibility to run multiple instances, and in that case this restart functionality would be harder to implement.

**Comment by goanpeca** [comment]
Well I dont think it is a problem the way I am doing it (I am doing it now...)

I am storing the PID and the `sys.argv` for the `bootstrap.py` and the `start_app.py` and when clicking the restart option I call an external pythons script stored in scripts... (`python_restart.py`) and pass the PID and the args as a string, so that script monitors the PID, and when closed it launches spyder in the exact way it was originally launched.

If you happend to restart an instance that was not called with the --new-instance flag, then I could always pass this flag no matter what to make sure it restarts?

**Comment by ccordoba12** [comment]
Try to keep it simple for starters :-) Make it work for the single instance case and then we can see what we can do with the multiple instances one.

**Comment by Nodd** [comment]
Are there (common) cases where spyder is launched from another application via a python call ? Is it the case for the anaconda launcher for example ?

**Comment by goanpeca** [comment]
Well the launcher is not using python anymore so that is not a case 

http://continuum.io/blog/new-launcher

**Comment by Nodd** [comment]
Dropping a dependency on python for a program about python looks a bit weird :) (don't tell anyone @ccordoba12 !).
To go on with my remark, maybe the restart feature should be disabled if spyder is not launched via `spyder`, `spyder3` or `bootstrap.py`. Or maybe I'm too picky and it's a corner case that we can ignore.

**Comment by goanpeca** [comment]
I dont think is a strict problem, because we can check what python spawned the spyder app, and use the exact same one to restart... (I could have run spyder from within spyder.... and it should work...)

**Comment by goanpeca** [comment]
And yes you are always too picky (but that is a feature as they say...)

**Comment by goanpeca** [comment]
Ok, so in windows is working :), have to check on linux now

**Comment by goanpeca** [comment]
This addition would eventually allow to run the configuration options of spyder inside spyder... for example

Reset spyder config from the GUI, would first reset spyder and then restart... etc...

**Comment by Nodd** [comment]
Good idea. We could catch problems on startup (or while loading the config) and offer to reset them. I always wondered if a basic user knows how to run `spyder --reset ` on windows...

**Comment by goanpeca** [comment]
Well. spyder creates two icons in windows... run Spyder... and the other is reset settings

**Comment by goanpeca** [comment]
Implemented by #2312
