### ISSUE TITLE
Custom shortcut `Alt+Shift+Return` doesn't work

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#23072]
I assigned a shortcut key `Alt+Shift+Return` to `run cell and advance`, but it doesn't work, even after restarting spyder. 

I also tried to assign the same shortcut to other functions, but it doesn't work either.

I tried to launch spyder with `--debug-info verbose --debug-output file`, nothing happened after pressing the shortcut key.

Another shortcut key `Ctrl+Alt+Return` works as expected, but only after restarting spyder.

* Spyder version: 6.0.2  (conda)
* Python version: 3.10.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Windows-10-10.0.22631-SP0

![image](https://github.com/user-attachments/assets/8f7f21e9-d1a6-4bbf-a0c0-18b01ae43a2d)

**Comment by ccordoba12** [comment]
Hey @gepcel, thanks for reporting. I was able to reproduce your problem in 6.0.2 and I can confirm that it's fixed by the work I'm doing in PR #23024, which will be part of 6.0.3.
