### ISSUE TITLE
Enhancement: Add check for updates and allow for autoupdating inside spyder

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2307]
It would be very good to have a check for updates button under the `help` menu (i guess).

Also this check could be run on startup so the user gets a notification when an update is available and offer the install update option.

Now to handle the update we could:

1. need a restart method for spyder (#2306), 

2. If using conda or anaconda we could run the StandAlone PackageManager with a flag to update spyder which would update spyder and on finish it would relaunch it and close itself.

3. We could play with some task handling specific to each OS (seems to complicated..~!)

Comments?

**Comment by Nodd** [comment]
Looks interesting. That would help decreasing bug reports from outdated versions of spyder.

**Comment by goanpeca** [comment]
Indeed! one of my major concerns with this

**Comment by ccordoba12** [comment]
This is a good idea indeed! Perhaps the simplest thing to do to solve this one would be to use the Github API to check for the latest release and report that in a `QMessageBox` to our users.

The only thing is that I wouldn't like to rely on `requests` for that. So if you could use `urllib` or other standard lib module would be better.

**Comment by goanpeca** [comment]
Great :), 

Just out of curiosity why not relying on requests?

**Comment by Nodd** [comment]
To not add another dependency I guess. And marking it as optional would defeat the feature which is more oriented towards debutant users.

**Comment by ccordoba12** [comment]
@Nodd seems to read my mind!! Yeap, that's exactly my thinking on `requests` for this.

**Comment by Nodd** [comment]
`import telepathy`, the last version added quite a lot of new features !

**Comment by goanpeca** [comment]
Ok, so on this one, the github api has some rate limits, right now it is 60... so if someone opens and closes spyder more than 60 times, the api would complain about it.

**Comment by ccordoba12** [comment]
The rate limit restarts every hour. So for this to happen, users should open and close Spyder every minute ;-)

This also means that these checks shouldn't be applied when `DEV == True`.

**Comment by goanpeca** [comment]
Implmeneted in #2321
