### ISSUE TITLE
Python console stops running after first execution

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2308]
## Description

* *What steps will reproduce the problem?*

    1. enter anythong that raises an exception in the standard python console, like `1/0`

* *What is the expected output? What do you see instead?*
The python interpreter stops running, I have to chick on the green arrow to restart it.

* *Please provide any additional information below*
Here is what I see in the console once it has stopped:
```
Python 2.7.9 (default, Dec 11 2014, 04:42:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: integer division or modulo by zero
>>> 
```
There is nothin in the internal console

## Version and main components

* Spyder Version:  3.0.0dev 
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.0.0 (OK)
zmq >=13.0.0    :  14.5.0 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by Nodd** [comment]
Actually, just pressing enter stops the interpreter, no need for an exception.

**Comment by goanpeca** [comment]
Indeed I am getting the same on a similar configuration

**Comment by ccordoba12** [comment]
I can't reproduce this error using the latest Anaconda.

**Comment by ccordoba12** [comment]
@Nodd and @goanpeca, I think you'll have to help me to find its cause :-)

**Comment by SylvainCorlay** [comment]
Similar problem here: the python interpreter crashes on any code execution.

**Comment by ccordoba12** [comment]
@SylvainCorlay, on which platform, Qt and Python versions?

**Comment by SylvainCorlay** [comment]
## Version and main components

* Spyder Version: 3.0.0dev 47daafb
* Python Version: 2.7.9
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies
```
pyflakes >=0.5.0:  0.5.0 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.1.0 (OK)
zmq >=13.0.0    :  14.6.0 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.1.0 (OK)
``
