### ISSUE TITLE
folium will not load

### ISSUE THREAD

**Issue by APDude** [spyder-ide/spyder#23095]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
folium only loads when I open Anaconda Navigator directly. If I try to open it through the terminal it will not load.

**Comment by ccordoba12** [comment]
Hey @APDude, thanks for reporting. What do you mean exactly by that? Does Folium fails to load in Spyder when you start it from the terminal?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by APDude** [comment]
Yes, when I open spyder via the mac terminal in the correct conda environment and import follies spyder says that there is no such package even though anaconda states that follies is a package that has been downloaded to the environment. However if I open spyder after opening anaconda and then go to the right environment spyder will recognize follies. Any thoughts?

**Comment by APDude** [comment]
follium

**Comment by ccordoba12** [comment]
Ok, but do you also have Spyder in the environment where follium is installed?

**Comment by APDude** [comment]
Thanks for responding.

Good question, yes Spyder is installed in the environment in question

Victor Barton
***@***.***

**Comment by ccordoba12** [comment]
Ok, then please activate that environment and run there

    spyder --reset
    spyder

That should solve your problem.

**Comment by APDude** [comment]
Thanks Carlos!
Victor Barton
***@***.***

**Comment by ccordoba12** [comment]
Great! Glad to know the problem is solved for you now.
