### ISSUE TITLE
variable explorer disappear 

### ISSUE THREAD

**Issue by asmahamam** [spyder-ide/spyder#23112]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I can't see the different variables in the debugger the tables won't appear

**Comment by ccordoba12** [comment]
Hey @asmahamam, thanks for reporting. Please post a screenshot that displays your problem so we can better understand it.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
