### ISSUE TITLE
Spyder does start, but GUI is invisible

### ISSUE THREAD

**Issue by sitadrost** [spyder-ide/spyder#23113]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I start Spyder, the Spyder splash screen appears, and the Spyder icon appears in my Ubuntu dock panel, but the Spyder GUI doesn't appear. I can right-click the Spyder icon, and see that there's a window active _somewhere_, but I can't see this window anywhere (ALT-TAB shows little black square).

Checking the `DISPLAY` variable for Spyder (PID = 78689 here) gives this:
```
$ cat -e "/proc/78689/environ" | sed 's/\^@/\n/g' | grep DISPLAY
WAYLAND_DISPLAY=wayland-0
GNOME_SETUP_DISPLAY=:1
DISPLAY=:0
```

Possibly related: yesterday I ran Spyder remotely, through an ssh X11 session (ssh -Y). Could this have messed up something?

### What steps reproduce the problem?

1. Start Spyder from a terminal window, `spyder &`

### What is the expected output? What do you see instead?
Expected output: Spyder starts, GUI appears
Actual output: Spyder starts, but there's no GUI

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 6.0.2
* Python version: 3.12.6
* Qt version: 5.15.8 (`qt-main`)
* PyQt version: 5.15.9
* Operating System name/version: Ubuntu 24.04

### Dependencies

```
PASTE DEPENDENCIES HERE
Sorry, can't access the GUI
```

EDIT: After rebooting Ubuntu, the Spyder GUI does open, but it's not quite the GUI I was used to: it opens a temporary script file, and a sidebar saying "latform = xcb", see the attached screenshot. I never really paid any attention to this, but I'm guessing xcb isn't the default platform for Spyder?
![Screenshot from 2024-11-29 13-54-13](https://github.com/user-attachments/assets/6f59df39-b032-49f3-840f-2ec1ea2febe6)

**Comment by ccordoba12** [comment]
Hey @sitadrost, thanks for reporting. You said:

> After rebooting Ubuntu, the Spyder GUI does open, but it's not quite the GUI I was used to: it opens a temporary script file,

That's the file Spyder opens by default when creating a new project (see below).

> and a sidebar saying "latform = xcb", see the attached screenshot.

That's a Spyder project. I don't know how, but it seems you created a Spyder project in a directory called `latform = xcb` without realizing it.

> I never really paid any attention to this, but I'm guessing xcb isn't the default platform for Spyder?

I don't understand what you mean by this. But you can restore Spyder to its default settings by going to the menu entry `Tools > Reset Spyder to factory defaults`.

**Comment by ccordoba12** [comment]
I'm going to close this issue because it doesn't have a problem we need to address.

**Comment by sitadrost** [comment]
Perfect, that worked! No idea when and how I created this Spyder project, but I'm glad Spyder's back to normal, thanks!
