### ISSUE TITLE
'NoneType' is not iterable in introspection/fallback_plugin.py

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2313]
## Description

* *What steps will reproduce the problem?*
1.
2.
3.

* *What is the expected output? What do you see instead?*
```
Traceback (most recent call last):
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/utils/introspection/plugin_manager.py", line 342, in _introspection_complete
Traceback (most recent call last):
threads  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/utils/introspection/plugin_manager.py", line 342, in _introspection_complete
    result = self.plugins['fallback'].get_definition(info)
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/utils/introspection/fallback_plugin.py", line 72, in get_definition
    if '.' in token:
TypeError: argument of type 'NoneType' is not iterable
    result = self.plugins['fallback'].get_definition(info)
  File "/usr/local/anaconda/lib/python2.7/site-packages/spyderlib/utils/introspection/fallback_plugin.py", line 72, in get_definition
    if '.' in token:
TypeError: argument of type 'NoneType' is not iterable
```
* *Please provide any additional information below*
I was casually editing a python script, the error happened right after a copy-paste.
I just noticed that spyder is not up to date, maybe it has already been corrected.

## Version and main components

* Spyder Version:  2.3.3
* Python Version:  2.7.9
* Qt Version    :  4.8.5, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
jedi >=0.8.1    :  0.8.1-final0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.2.1 (OK)

**Comment by goanpeca** [comment]
Also having this issue... completion in Master seems to be kinda of broken... it takes too long (when it works) @blink1073

**Comment by blink1073** [comment]
Yikes!  I'm on it.
