### ISSUE TITLE
Spyder auto replace `#%%` with `# %` when  create new script file from template.

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#23152]
### What steps reproduce the problem?

1. Edit template for new files like:

```
#%% imports
import os
import numpy as np

#%%

```
2. Press `Ctrl+N` to create a new file, the new file is empty, the template doesn't work.
3. Close the current file, a new file is created automatically from the template, but auto replacing `#%%` with `# %`. Results like:

```
# % imports
import os
import numpy as np
# %

```
* Spyder version: 6.0.2  (conda)
* Python version: 3.9.15 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.19045-SP0

**Comment by gepcel** [comment]
`#%%%%` works, thanks.

**Comment by ccordoba12** [comment]
@dalthviz, perhaps we should change the template to use f-strings instead?

**Comment by ccordoba12** [comment]
Ok, I haven't thought about it. If users still would need to escape one symbol or another in order to add it to the template, then I think it's not worth it to move it to another string replacement method.
