### ISSUE TITLE
Display object name in DataFrame editor

### ISSUE THREAD

**Issue by CharlesVellutini** [spyder-ide/spyder#2315]
- View several DataFrames on the Variable Explorer's browser
- Very easy to get confused on which DataFrame is which as their names are not displayed on the browser

--> Need to display respective object names in each browser window

![sans titre](https://cloud.githubusercontent.com/assets/11884206/7084614/5781acea-df6f-11e4-9ac2-1a7818acb564.png)

**Comment by goanpeca** [comment]
@CharlesVellutini seems like a good idea.

Want to give it a try?

Take a look here -> https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/dataframeeditor.py

**Comment by goanpeca** [comment]
@dhoegh, you worked on this right? Maybe you can take a look as well?

**Comment by CharlesVellutini** [comment]
Thanks for the feedback. In all honesty, I don't think I have the skills for this, being mostly a modest Spyder user! 
Also, my idea was in fact that all objects, not only DataFrames, could benefit from this feature.
Thanks again for all your great work.

**Comment by ccordoba12** [comment]
The name is not shown for DataFrames only, so it seems a simple fix :-)
