### ISSUE TITLE
Internal console completions are very difficult to read in dark mode

### ISSUE THREAD

**Issue by athompson673** [spyder-ide/spyder#23196]
## Problem Description

light mode: 
![image](https://github.com/user-attachments/assets/fd5c0a06-4993-47a7-99f2-d4c03705218a)

dark mode:
![image](https://github.com/user-attachments/assets/27b5f542-4483-4e20-8fee-b55b03221bd6)

## Versions

* Spyder version: 6.1.0a1.dev0  (pip)
* Python version: 3.12.7 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.11
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @athompson673, thanks for reporting. I've noticed this problem too and we'll try to fix it in our next version (6.0.3), to be released next week.
