### ISSUE TITLE
The control debugger buttons are hidden from the main toolbar when code is executed

### ISSUE THREAD

**Issue by tony-pythony** [spyder-ide/spyder#23208]
Hello Friends!

Thank you for the wonderful Spyder. I noticed a few UI or workflow changes - or flaws - with the Version 6 (and, may be, would like to start a discussion.)

**Debug buttons**
  From the release of V.6, the debug buttons are not always visible. Debug-function is one of the most used functions, it shouldn't be hidden, instead it should always be visible and accessible - no matter, what window or dialog is displayed. Like the Run-button, too. 
With the Version 6.0.0, "just" the button "start debug" button is displayed on the main window. The other debug buttons are hidden in the debug-pane (similar to the variable explorer). That makes it impossible to, f.e., "run debug until next line" and observe the change of variables at the same time without switching the windows. 

This has been addressed in V. 6.0.2 with making the other debug buttons appear dynamically, when starting the Debug-mode. In my case, I see a constant disappearing and reappearing of all the buttons, when I click on, f.e., "run until next break point", while running a lengthy function-block. This makes it distracting and in case of fast successive clicking, some clicks are lost because the button is not visible at such moments. More over, I unwillingly clicked another button of the button pane, because it moved under my cursor just in the moment I clicked. As solution I have to disable all the other buttons. 
Proposals:
- make the core function buttons always visible and accessible. It's a core functionality.
- let the user decide what buttons to show / make the toolbar buttons customizable. I don't need "run cell", yet it's using up the real estate on the toolbar. 
- let the user decide, where the buttons are positioned & displayed / positions & order of the buttons. Keep that position at all circumstances.

**Immediate and automatic opening of the variables after one left-click.** 
When using a mouse, one click is select, double-click means execution. This usage pattern gets broken, if one click immediately opens up a new window with variable explorer. Especially for me, I like to select a variable and keep it selected, so I visually can locate it after scrolling and checking other variable's value. While I understand the comfort of one-click-execution, this breaks the whole mouse usage-pattern. I just want to select it, now it opens it.
Proposals:
- let the user decide, whether one-click opens or selects. This can be implemented in the preferences/variable explorer.

**Fixed layout of preferences/settings dialogue**
I feel a discomfort using preferences/settings dialogue. I think the reason is the fixed size of the dialogue's elements. While the preferences-window by itself can be resized, the content elements on the right side do not change their sizes. This makes me feel strange. I don't know why. May be, the layout's proportions get visually broken and so my visual-brain, too. 
Proposals:
- may be there's a way to make the positions and sizes relative to the preference-window / not fixed?

What do you think?

Best wishes, 
tony.

**Comment by Ignasijus** [comment]
True. Debugging in Spyder 6 is completely messed up. I can add that I was not able to change debugging shortcuts in the Preferences window. Had to switch back to version 5.

**Comment by athompson673** [comment]
The buttons hiding during execution of a current line definitely seems like a bug. I generally appreciate resizable windows, but the settings content is relatively fixed, and it would be a lot of effort with not much reward to make custom resizing behavior for every page. I somewhat agree on the double click aspect of the variable explorer, however you can easily select an item with the arrow keys once the pane has focus.

**Comment by ccordoba12** [comment]
> The buttons hiding during execution of a current line definitely seems like a bug.

And thanks for contributing a fix for that @athompson673!

> I generally appreciate resizable windows, but the settings content is relatively fixed, and it would be a lot of effort with not much reward to make custom resizing behavior for every page.

Correct. Plus, we followed the Ubuntu settings UI for this:

![imagen](https://github.com/user-attachments/assets/a8fc4d97-c29a-4a39-be3c-68ff71123621)

And I see it more as a personal preference.

> I somewhat agree on the double click aspect of the variable explorer, however you can easily select an item with the arrow keys once the pane has focus.

This was already reported in #22524 and it'll be fixed in 6.0.4, to be released in a few weeks. I agree that now is not intuitive how to select a row while before it was very simple. So, we'll add an extra button to each row that will select it when clicked.
