### ISSUE TITLE
Spyder not going through all breakpoints

### ISSUE THREAD

**Issue by carlosloslas** [spyder-ide/spyder#2323]
Hi all, 

edit.: After testing more functions and in various ways I have narrowed it down to just the return commands on the functions. Is this a particular option in the preferences?

This may be quite difficult to try and replicate, but I have no idea how this is happening, or how to solve it.

I am running a number of python programes on spyder. In order to try and understand some of the errors in them I am using the awesome breakpoint feature. Strangely It seems to ignore some of the breakpoints completely.
This is quite obvious when I place a breakpoint inside a for loop and spyder seems to stop only once if any when I debug the file.

Has anybody else heard of, or come across anything similar?
Thanks in a lot in advance.

I enclose my conda and system specs.
```
Current conda install:

             platform : osx-64
        conda version : 3.10.1
  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
``` 
Model Name:	MacBook Pro (15-inch, Mid 2012)
Processor Name:	Intel Core i7
Memory:	8 GB
System Version:	OS X 10.10.3 (14D131)
Kernel Version:	Darwin 14.3.0
Boot Volume:	Macintosh HD
```

**Comment by ccordoba12** [comment]
I think you need to use the *Step into* button to remain in the loop.

**Comment by carlosloslas** [comment]
Hola Carlos, 

Thanks for the reply even with the issue closed. 
I closed it since I found a website with a detailed explanation on the basic commands of the debug method managed to work around the issues. 
At the moment everything seems to be working fine, but every now and then it starts being a bit unstable. I will reinstall it in the near future, since I think I have changed things which probably shouldn't have touched, but I think that its the best way to learn!

Thanks again for the reply
Best regards/ Un cordial saludo

**Comment by ccordoba12** [comment]
No prob, please let us know if you encounter more problems with our debugging support. We are planning to improve it by the end of the year :-)

Y gracias por usar Spyder!!

**Comment by carlosloslas** [comment]
@ccordoba12 
Buenos dias!
Update on the issue.
Spyder is skipping breakpoints in reasonably long for or while loops and then gives an ```UnpicklingError: invalid load key, 'C'.```  in the Internal console. 

I have seen similar ```UnpicklingError```s in forums but i haven't called or touched anything to do with the Python ```Pickle``` module

Thanks in advance,
Un cordial saludo

**Comment by ccordoba12** [comment]
Please paste here an example that's giving you that error so we can test it in our side :-)

**Comment by carlosloslas** [comment]
Hola Carlos, 

Sorry for the late reply I handed in my dissertation yesterday I have had incredibly busy days for the past two weeks. 
Unfortunately I am not able to isolate the error, since it was happening when I was running one of the  functions in my dissertation project, and my knowledge on Spyder is limited... : S
I just wanted to  notify it here and in the event of somebody encountering something similar there would be some kind of prior idea on the subject. : )

Thanks for everything
Hope that the next version of Spyder is even better than the current...if its even possible!

**Comment by ccordoba12** [comment]
It will be, that's for sure!! There are already several minor but cool improvements, and more important things are in the making ;-)

Take a look at

https://github.com/spyder-ide/spyder/wiki/Beta-version-changelog

from time to time to read about them.

----

Y finalmente, felicitaciones por tu tesis!!
