### ISSUE TITLE
When using ipython console, running a file should have an option of specificying "-i" option

### ISSUE THREAD

**Issue by gauravkumar37** [spyder-ide/spyder#2324]
When running a file in ipython's console, the command which currently gets executed is
%run "filename"
This does not preserve the globals() already defined in the interpreter.

Provide an option in the run configuration to preserve the global variables which would in-turn run the command
%run -i "filename"

**Comment by ccordoba12** [comment]
We use our own `runfile` function, not the `%run` magic to run a file in our IPython consoles. How `%run` works is not in our control, but in the hands of IPython devs.

However, I don't think preserving the globals() is a good idea to add for an option to `runfile`. But using `%run -i` is always possible.

**Comment by gauravkumar37** [comment]
I noticed that spyder uses `runfile` when running in an IPython console launched by it. However, if we connect to an external IPython console, it uses `%run` method. Is this deviation intended?

**Comment by ccordoba12** [comment]
You're right. The problem is that `runfile` is not defined for external kernels because we add that function to the `builtins` of each console with our own `sitecustomize` file.

So we need to rely on `%run` to keep things working for external kernels.
