### ISSUE TITLE
Spyder 2.3.4: I keep getting a "Reloaded modules:" warning

### ISSUE THREAD

**Issue by gsmafra** [spyder-ide/spyder#2325]
Hello

Since I updated Spyder I am getting these messages everytime I try to compile a script with an import a second time.

For example, when running 2x a script that simply imports theano I get this message:

> Reloaded modules: theano.scalar, theano.gof.callcache, theano.gof.optdb, theano.scan_module.scan, theano.tensor.extra_ops, theano.tensor.io, theano.tensor.shared_randomstreams, theano.tensor.opt, theano.tensor.nnet.Conv3D, theano.compile.monitormode, theano.tensor.blas, theano.tensor.type, cutils_ext, theano.gradient, theano.compile.profilemode, theano.gof.compiledir, theano.gof.type, theano.tests.main, theano.misc.cpucount, theano.scan_module.scan_op, theano.gof.null_type, theano.compile, theano.tensor.utils, theano.tensor.blas_scipy, theano.misc.ordered_set, theano.gof.opt, theano.tests, theano.tensor.nlinalg, lazylinker_ext.lazylinker_ext, theano.tensor, theano.compile.builders, theano.compile.debugmode, theano.tensor.nnet, theano.compile.io, theano.gof.utils, theano.gof.destroyhandler, theano.tensor.nnet.ConvTransp3D, theano.scan_module.scan_opt, theano.misc, theano.compile.function_module, theano.gof.graph, theano.tensor.subtensor, theano.tensor.blas_c, theano.compat.python2x, theano.gof.cutils, theano.misc.windows, theano.tensor.nnet.conv, theano.scan_module.scan_utils, theano.compat.six, theano.tensor.basic, theano.configparser, theano.gof, theano.gof.fg, theano.configdefaults, theano.tensor.sharedvar, theano.gof.toolbox, theano.scan_module.scan_views, theano.tensor.blas_headers, theano.printing, theano.tensor.elemwise_cgen, theano.gof.link, theano, theano.scalar.sharedvar, theano.gof.vm, lazylinker_ext, theano.compile.ops, theano.gof.unify, theano.tensor.elemwise, theano.tensor.nnet.nnet, theano.compile.function, theano.tensor.type_other, theano.gof.cc, theano.tensor.sort, theano.version, theano.scalar.basic, theano.tensor.nnet.ConvGrad3D, theano.tests.unittest_tools, theano.tensor.xlogx, theano.tensor.var, cutils_ext.cutils_ext, theano.gof.compilelock, theano.compile.mode, theano.compile.sharedvalue, theano.misc.safe_asarray, theano.compile.pfunc, theano.tensor.nnet.sigm, theano.gof.lazylinker_c, theano.gof.sched, theano.misc.strutil, theano.scalar.basic_scipy, theano.gof.cmodule, theano.compat, theano.gof.op, theano.updates, theano.tensor.opt_uncanonicalize, theano.scan_module, theano.tensor.raw_random, theano.compile.profiling

That only happens when using Spyder's runfile. I already tried execfile() and python xxx.py and I get no warnings

So, anyone knows how to suppress it?

Running on:
Python 2.7.8
Anaconda 2.1.0 (64-bit)
IPython 2.2.0
Windows 7

**Comment by Nodd** [comment]
Have a look in the *Console* section of the preferences, in the *Advanced* tab. You can either disable the message or the UMR completely.

**Comment by gsmafra** [comment]
Thank you, solved

**Comment by ccordoba12** [comment]
It's better for you to disable the message, the UMR is quite useful to reload your own code.

**Comment by Nodd** [comment]
I'd argue that the best way is to always run in a new dedicated console.

**Comment by mattandersoninf** [comment]
How do i disable the UMR? I can;t find the preferences mentioned above

**Comment by Ritesh96Soni** [comment]
Go to Tools -> Preferences -> Python Interpreter and you will find User Module Reloader.

**Comment by z1314520cz** [comment]
Thank you and i solved the problem too.

**Comment by holyprince** [comment]
Thank you and it is very useful for me to avoid open new python console.
For my spyder 2.3.8, the UMR path is  Tools->Console->Advaned setting and on the last tab is UMR disable.

**Comment by nicolajbky** [comment]
In my Spider 3.2.8 it is 
Tools -> Prefenrences -> Python interpreter ->  User Module Reloader (UMR)

**Comment by MadhavJadhav1** [comment]
thanks for solution

**Comment by Angad-Boparai** [comment]
it works, thank you!

**Comment by spikelucky** [comment]
is there any drawback to just ignoring the message? I don't really want to disable the message in general and always starting a new console get tedious when you just trying a few quick changes and therefore rerunning it frequently. That red color just burns my eyes lol. But seriously is there any detriment to having reload a molule?

**Comment by ccordoba12** [comment]
@spikelucky, you said:

> is there any drawback to just ignoring the message?

No, you can safely ignore it (it just reports that your code was successfully reloaded and it's running the latest version available in the editor).

> That red color just burns my eyes lol.

Agreed. Could you open an issue about it so we don't forget to change it for a better looking color later?

> But seriously is there any detriment to having reloaded a molule?

As I said, it's just an informative message. The detriment is that you (inadvertently) could be using an old version in the console, which could give different results from the ones you expect.
