### ISSUE TITLE
Feature Request / Clarification

### ISSUE THREAD

**Issue by Shaunakde** [spyder-ide/spyder#2326]
Hello,
Currently in Ubuntu if I drag a file into the console - it produces the following path: 
file:///home/shaunak/caffe/data/cifar10/data_batch_1.bin

However this is not directly readable by open. Thus if I take the filename with input and use the drag drop feature, I cant read it.

In Canopy on windows this worked without issue. Perhaps this feature can be implemented?

**Comment by goanpeca** [comment]
Which console? python/ipython?

**Comment by Shaunakde** [comment]
Python

**Comment by goanpeca** [comment]
So it works as you expect in the iptyhon console?

**Comment by Shaunakde** [comment]
I will have to try it and get back to you. I don't have a computer near me
for the next 8 hours. I'll email back soon.

**Comment by goanpeca** [comment]
@Shaunakde ???

**Comment by Shaunakde** [comment]
Hey, I replied to the earlier post.

So iPython works as expected across platforms. I also did a but of checking
and this seems to be a ubuntu trait. It was not the case on Centos 6.5

Thanks for the time.

On Sun, Apr 19, 2015 at 5:51 PM, Gonzalo Peña-Castellanos <
notifications@github.com> wrote:

> @Shaunakde <https://github.com/Shaunakde> ???
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2326#issuecomment-94270771>.
>



-- 
Shaunak De
http://shaunak.de/

**Comment by goanpeca** [comment]
:+1:  no prob!
