### ISSUE TITLE
Cannot type backslash \ in console or editor in Mac: get ¥ instead

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [spyder-ide/spyder#2329]
I could not find any information about this issue in the Internet, so it could possibly be only due to my environment. I'm using Spyder 2.3.4 on Mac OSX 10.10.3, and I can't type backslash sign \ in console or editor. In my environment, Option + ¥ is assigned to backslash and it always works for other applications, but not for Spyder; In Spyder it'll insert ¥ instead. Character code for \ and ¥ is mixed up in Japanese version of Windows and this has been a well known issue since the Ice Age. But this problem is strange because 1. I'm using Mac, 2. It's OK for other applications. I wonder if anyone experienced the same issue. At the moment I have to copy and paste \ from other text editors.

**Comment by ccordoba12** [comment]
This is (most) probably a problem with the graphical library used by Spyder (i.e. with Qt).

I don't know what we could do to help you though :-(

**Comment by kouichi-c-nakamura** [comment]
Bingo! You're brilliant.

*Backslash is converted to YEN SIGN on Qt for Mac with JIS keyboard.*
https://bugreports.qt.io/browse/QTBUG-10543

I also found a post-hoc workaround for this.

  1. Download **Karabinar** at https://pqrs.org/osx/karabiner/index.html.en. (You need to allow Karabinar to control your computer via **System Preference > Security & Privacy > Privacy> Accessibility**)
  2. Launch Karabinar and choose the **Change Key**  pane.
  3. Type "**change yen**" into the query box just below the top.
  4. Tick **For Japanese** > **Change Yen(¥) Key** > **JIS Yen(¥) to Backslash(\)** (except virtual machine, X11, RDC).

Now I can't really type the ¥ sign, but I can type the \ (backslash) sign in Spyder console.

**Comment by ccordoba12** [comment]
Ok, I'm really glad you were able to find a solution for your problem!! Kudos to you ;-)
