### ISSUE TITLE
^M in git diff on Ubuntu

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#2330]
I've edited a file with Spyder and now `git diff` shows red ^M at the end of lines. I am pretty sure that spyderlib/spyder.py has Windows line feeds (why?) and that Spyder shows CRLF mode.

Why the marks? git 1.9.1

``` diff
diff --git a/spyderlib/spyder.py b/spyderlib/spyder.py
index ddff947..6560250 100644
--- a/spyderlib/spyder.py
+++ b/spyderlib/spyder.py
@@ -2738,6 +2738,15 @@ def initialize():

     return app

+# --- Generic Plugin API^M
+^M
+class SpyderWeb(object):^M
+    """^M
+    Wiring internal Spyder components together^M
+    """^M
+    appname = 'spyder'^M
+    version = __version__^M
+    plugins = []^M

 class Spy(object):
     """
@@ -2756,6 +2765,8 @@ class Spy(object):
     def versions(self):
         return get_versions()

+# --/ Generic Plugin API^M
+^M
```

**Comment by ccordoba12** [comment]
Most of us (the core devs) use Spyder to develop Spyder. And Spyder doesn't preserve line endings, it just uses the same ones as those of its host operating system.

Personally I think that `git` trying to correct line endings is too much for a VCS, so I think this is not of crucial importance.

**Comment by Nodd** [comment]
This is of crucial importance when using any VCS, line endings modification is a change like any other character.

What I don't understand is if it's git or spyder's "fault". @techtonik on what platform did you edit the file ?

**Comment by ccordoba12** [comment]
But Spyder only changes line endings of those lines that were modified, not of the entire file :-) Else all our diffs would be completely unreadable!

I think this is Spyder's fauit, but `hg` didn't complain about it.

**Comment by goanpeca** [comment]
https://help.github.com/articles/dealing-with-line-endings/

**Comment by techtonik** [comment]
Looks like does ^M stands for CR. I don't know why git highlights ^M only on edited lines. I see that the whole file is in CRLF linefeeds. So it is a bug in git or some desired behaviour? What I am concerned about is that it may be a warning that it will commit something weird as a result.

**Comment by joelostblom** [comment]
I believe you can close this issue as not directly related to spyder. I encountered it in a file that was created with spyder on windows, which I was editing on linux in either spyder or vim (which both seem to preserve line endings in the file's original/predominant format).

Creating files with spyder on linux does not have the `^M` line endings showing up in `gitt diff`. In the end, I got rid of all the existing `^M` by running `dos2unix <filename>` to replace all windows carriage return line endings with linux style line feeds.

There are also options to set how git handles line endings as pointed out by @goanpeca and discussed on SO [here](http://stackoverflow.com/questions/1889559/git-diff-to-ignore-m#7180812) and [here](http://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf/20653073#20653073).

**Comment by techtonik** [comment]
I tend to switch between Thonny and IPython nowadays, and I don't know if Git/Spyder still exhibit this bug, so let's reopen this when it becomes actual for somebody.
