### ISSUE TITLE
The Chinese input method blocks the input content.

### ISSUE THREAD

**Issue by Deng-Guangyong** [spyder-ide/spyder#23313]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Problem: When I enter Chinese in the Editor, the Chinese input method candidate box blocks the input content.

<span style="color:green;">Solution:</span> CodeEditor overloads the QPlainTextEdit inputMethodQuery method:
```python
def inputMethodQuery(self, query):
    """Reimplement Qt method"""
    if query == Qt.ImInputItemClipRectangle:
        cursor_rect = self.cursorRect()
        margins = self.viewportMargins()
        cursor_rect.moveTopLeft(cursor_rect.topLeft() + QPoint(margins.left(), margins.top()))
        return cursor_rect
    
    return super(CodeEditor, self).inputMethodQuery(query)
```

### What steps reproduce the problem?

1. Enter Chinese in Editor.
2. 
3. 

### What is the expected output? What do you see instead?

The Chinese input method candidate box should be displayed under the cursor.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  6.0.3
* Python version: 3.11.10
* Qt version: 
* PyQt version: 
* Operating System name/version:  windows 11

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Hey @Deng-Guangyong, thanks for reporting and providing a fix for this! We'll include it in our next version (6.0.4), to be released in a few weeks.
