### ISSUE TITLE
Spyder unable to start as unable to link python kernel

### ISSUE THREAD

**Issue by vegaonline** [spyder-ide/spyder#2338]
## Description

* *What steps will reproduce the problem?*
1. Running spyder from terminal.
2.
3.

* *What is the expected output? What do you see instead?*
The spyder UI hangs and then root kernel dies.

* *Please provide any additional information below*
I tried to startup spyder (installed from Anaconda in OpenSUSE13.2 64 bit) from  a terminal. Suddenly it started linking console and then reports kernel dies.

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
If you installed Anaconda 2.2, please run this command

    conda update pyqt

and try again. That should fix your problem.

**Comment by ccordoba12** [comment]
Closing because of lack of respone
