### ISSUE TITLE
SublimeText-like file switching widget

### ISSUE THREAD

**Issue by d1manson** [spyder-ide/spyder#2340]
In Sublime Text, you press Ctrl-P to get an intelligent, fast switching between open files/files in the current folder.  See [here](http://sublime-text-unofficial-documentation.readthedocs.org/en/latest/file_management/file_management.html).

I find myself trying to use this shortcut in Spyder, and then get annoyed when I have to click through little buttons at the top of the editor.

I imagine that this tool is reasonably straightforward to implement as it's fairly stand alone.

**Comment by goanpeca** [comment]
@d1manson sure, something that seems worth implementing. Do you want to give it a try?

Right now it would conflict with the Print command, so I guess some discussion is needed.

@ccordoba12, @blink1073, @Nodd

**Comment by Nodd** [comment]
There already is `Ctrl+E` for this, but in master I get in the internal console:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 643, in open_filelistdialog
    dlg.edit_file.connect(self.set_stack_index)
AttributeError: 'function' object has no attribute 'connect'
```

**Comment by d1manson** [comment]
Ah thanks, I didn't know about that dialogue - it *does* work for me. Although it's not quite as slick as Sublime's it's a massive improvement over clicking on tabs!  Thanks

**Comment by goanpeca** [comment]
Me neither... wow.. we really need to document this!

We could make it more slick... want to tackle that @d1manson ?

**Comment by Nodd** [comment]
THere should be an entry in the file menu to make it more discoverable. I heard about it by a comment froom @ccordoba12 in an issue quite recentely. And I forgot about it until I saw this !

@d1manson what would make it slicker ?

**Comment by d1manson** [comment]
Well, it's already pretty good.  But, for extra slickness (to copy Sublime)...
* I'd like to be able to use up/down keys on the list while the filter box has the focus.
* When filtering, the matched text should be highlighted in the list.
* Whichever item in the list is currently selected should be brought to the front of the editor (but if you Esc out of the dialogue rather than hitting Enter you revert back to where you were).
* The list should be sorted based on recent usage (or at least alphabetically, right now I'm not sure if it's sorted on anything in particular).
* Most importantly - the shortcut should be available in all contexts, not just when the editor has the focus.

I'm not too keen on volunteering for this as I've not done any work on Spyder or with Qt.  But I might have a look at some point this week and see if it's something I could do in a few hours.

**Comment by goanpeca** [comment]
@d1manson sounds like you have a plan :-), you should give it a try, we can provide guidance where needed, and we are always looking for new contributors :smile_cat:

**Comment by ccordoba12** [comment]
@Nodd, I can reproduce the bug you reported. I'll fix it later today :-)

But let's leave as an enhancement to improve our widget to be closer the SublimeText one

**Comment by d1manson** [comment]
I have already started working on this (including bugfix). 
https://github.com/d1manson/spyder/blob/file-switcher/spyderlib/widgets/editor.py 

I'll submit a pull request later today I think.

**Comment by ccordoba12** [comment]
Great!! A couple of suggestions:

1. I don't mind with changing the shortcut to `Ctrl+P` and making it global. I doubt that shortcut is used quite often right now, so I don't think changing it to another action would cause major headaches.
2. You can take our current widget and modify it as you want.
3. Don't forget fuzzy matching. [Here](https://github.com/seatgeek/fuzzywuzzy) it is a library to do that :-)

**Comment by ccordoba12** [comment]
But fuzzy matching can come later in another PR, it's just so that you keep it in mind.

**Comment by goanpeca** [comment]
:+1:

**Comment by Nodd** [comment]
`Ctrl+P` is often used as *Print*, but a file browser is a more important feature for an IDE.

**Comment by goanpeca** [comment]
I agree, we should give priority to the file browser.
