### ISSUE TITLE
qtpy in Spyder org?

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/spyder#2342]
Would it make sense to move qtpy into the Spyder organization?
Spyder could simply have a shim for it. Both qtawesome and conda-manager already depend on it.

**Comment by ccordoba12** [comment]
Yes, I was thinking that too, but it depends on @goanpeca's wishes.

How the shim would work for Spyder?

**Comment by goanpeca** [comment]
@ccordoba12 for me its fine, the repo is ready so I can just transfer ownership to spyder-ide.

Not sure what you mean... (How the shim would work for Spyder?)

**Comment by Nodd** [comment]
@ccordoba12 suggested to change the name, because it's easy to confuse it with pyqt. Some not so good suggestions:
PythonQts ?
QtsPython ?
CutiePy ?
QutiePy ?

**Comment by SylvainCorlay** [comment]
SpyQt ? :smile:

**Comment by SylvainCorlay** [comment]
In any case, qtpy already is on pypi and might have other users. We should weight this before renaming it to something else.

**Comment by ccordoba12** [comment]
@goanpeca, it's your choice if you want to leave your current name or pick up another. I need your decision before creating the repo.

My suggestion: `qt4py`: still simple, a bit more compelling, but harder to confuse with `pyqt` :-)

**Comment by goanpeca** [comment]
:worried: :sweat_drops: :sweat:

**Comment by Nodd** [comment]
`qt4py` looks like it's for Qt4 only. It's hard to find a good name... `PyCute` ? (PySide and PyQt are both Py-something)

**Comment by goanpeca** [comment]
I know!! numbers just add to the confusion... QtPy sounds so lovely :-) and [friendly](http://www.urbandictionary.com/define.php?term=cutie+pie)

**Comment by SylvainCorlay** [comment]
@goanpeca did not know this one :)

**Comment by goanpeca** [comment]
Well.. that was the whole point of the name.... it had a punch to it

**Comment by ccordoba12** [comment]
@goanpeca, what's you final decision about this one? It's ok if you prefer to leave `qtpy` as the package name :-)

**Comment by goanpeca** [comment]
qtpy it is :-), should I transfer the ownership ?

**Comment by ccordoba12** [comment]
Ok, the repo is up and ready. I'd prefer if you transfer the ownership to the Spyder development team, but for that I'd like to follow first what project Jupyter does, as stated in

https://github.com/jupyter/jupyter_notebook/blob/master/COPYING.md

**Note**: Please close this issue when you finish the transfer

**Comment by goanpeca** [comment]
@ccordoba12 sure no prob, but, you want me to change the license to include something ... or ???

**Comment by ccordoba12** [comment]
I think you should move it as it is now. Then we should add something like that Jupyter file to all projects under the Spyder organization :-)

**Comment by goanpeca** [comment]
Moved

**Comment by SylvainCorlay** [comment]
Great! Do you guys want to use qtpy in Spyder rather than duplicating it?

**Comment by goanpeca** [comment]
I can make the move if you agree

**Comment by ccordoba12** [comment]
I wouldn't like to depend on an external dependency, especially for this. I mean, if it's not installed Spyder wouldn't even start!

But I'd like to use `qtpy` internally. What if we copy `qtpy` contents to `spyderlib/qt` and update them every time a new `qtpy` version is released?

**Comment by SylvainCorlay** [comment]
Or use a submodule, and update the commit number of qtpy when qtpy is released.
