### ISSUE TITLE
Show warning in editor when nested loops use the same variable names as outer loop

### ISSUE THREAD

**Issue by cmeeren** [spyder-ide/spyder#2346]
I would like a yellow exclamation mark on the line of an inner `for` loop if I accidentally iterate using the same variable names as an outer `for` loop. For example:

```python
for some_var in iterable:
    # lots of code
    for some_var in another_iterable:  # whoops, I want a warning here
    # more code
```
Nested iteration using the same variable names might be useful for some purposes, but in my own experience (I'm not primarily a coder, but a physicist) this is simply an error that's difficult to debug. I suggest that this should be an option in the preferences.

**Comment by Nodd** [comment]
This kind of things should be integrated to the libraries that spyder uses for checking code correctness. In this case I'd say pylint.

**Comment by goanpeca** [comment]
Agree, this is a way too specific change

**Comment by cmeeren** [comment]
Ok, I didn't know how this was implemented. I'll try pylint then.

**Comment by Nodd** [comment]
For reference, here is the link to the pylint feature request: https://bitbucket.org/logilab/pylint/issue/530/warning-when-nested-loops-use-the-same
