### ISSUE TITLE
Add shortcuts to move to next/previous line in the Editor

### ISSUE THREAD

**Issue by goyou** [spyder-ide/spyder#2347]
Hello !
There's already the 'next word' and 'previous word' keyboard-shortcuts in Spyder ( Ctrl+Right and Ctrl+Left ).
There should be the same behavior but "vertically".

I think the "horizontal" jump is easily implemented : seek for "space"' character, then jump cursor to the position just after it.
If so, it would be easy to implement vertical jump : just seek for an empty line instead of a "space".

I sought these functions in the /spyderlib/wigets/editor.py and editortools.py, because I thought I could do it myself but actually I couldn't find them.

**Comment by ccordoba12** [comment]
I think @blink1073 is working on it along with the Emacs keybindings, right?

**Comment by blink1073** [comment]
Yep, I'll make these the non-emacs keybindings.

**Comment by ccordoba12** [comment]
I think moving to next and previous **empty** lines are that not that useful, but moving to next and previous lines are going to be implemented as part of PR #2217.
