### ISSUE TITLE
Combobox to choose Matplotlib backend

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2348]
Currently the matplotlib backend is set via a QLineEdit. Since the possible values are a few and well defined, a combobox is more appropriate.

Bonus points if only the available backends are shown (but it depends on the active interpreter ?).

**Comment by Nodd** [comment]
Same for ETS Toolkit, I guess.

**Comment by goanpeca** [comment]
Which are the valid options? and how to check from the valid options which ones are enabled?

**Comment by ccordoba12** [comment]
@goanpeca, we already have this for the IPython console. Check out its *Graphics/Backend* tab on *Preferences* to see what @Nodd wants. Right now we are only testing for available backends on the same interpreter that Spyder is running on, but that could be improved.

About ETS: I think there are only two possible options: `qt` and `wx`, so I don't think we need a combobox for that ;-)

**Comment by Nodd** [comment]
@ccordoba12 Exactly! I didn't notice that it was already used by IPython.

About ETS, having a QLineEdit for 2 options is more silly than having a combobox. :tongue: Other options are a checkbox (which would be confusing) or 2 radio buttons, which would work well too. In any case it's not a big deal, only a minor improvement.

**Comment by goanpeca** [comment]
Even though I this is not terribly urgent, I do agree with @Nodd that even if only 2 options, we should change them to comboboxes.

**Comment by ccordoba12** [comment]
`wx` doesn't work on Python 3, so I don't think we need a combobox for that entry

**Comment by Nodd** [comment]
In that case this options should be hidden under python3, and use a combobox under python2. :smile:

**Comment by ccordoba12** [comment]
As @goanpeca established: *help-wanted*. I really think the QLineEdit is just fine. Besides, I don't know if ETS is working on Python 3.

**Comment by Nodd** [comment]
:+1:

**Comment by ccordoba12** [comment]
I'm going to solve this one as part of solving #2471 (by limiting the number of backends we support).
