### ISSUE TITLE
Source menu actions remain active with all files closed

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2351]
Source menu actions remain active with all files closed, so calling (clicking) any of these actions will result in errors as can be seen in the following image.

![image](https://cloud.githubusercontent.com/assets/3627835/7295735/580717f0-e9b9-11e4-93ca-1f81eb551b1b.png)

Maybe when the last tab (file) is closed a call to disable these actions should be emitted...

**Comment by Nodd** [comment]
If https://github.com/spyder-ide/spyder/issues/2302 is implemented by always having an opened file, it would solve this issue too.

**Comment by goanpeca** [comment]
Yep
