### ISSUE TITLE
Variable Explorer does not show sets

### ISSUE THREAD

**Issue by stuppie** [spyder-ide/spyder#2355]
IPython >=0.13  :  3.0.0 (OK)
matplotlib >=1.0:  1.3.1 (OK)
pandas >=0.13.1 :  0.13.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
psutil >=0.3    :  2.2.1 (OK)
pyflakes >=0.6.0:  0.8.1 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  0.7.6 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
Spyder 2.3.2
Python 3.4.0 64bits, Qt 4.8.6, PyQt4 (API v2) 4.10.4 on Linux

Steps to reproduce:

> x = {'a','b','c'}
> Look in variable explorer. No variable named x appears

Expected behavior:
show 'x' in variable explorer

Also:

xlist1 = [{'a','b','c'}] 
does not work, while,
xlist2 = ['foo',{'a','b','c'}]
does. 
![screenshot-xlist2 - list 2 elements](https://cloud.githubusercontent.com/assets/5470131/7310537/a15c737c-e9e2-11e4-89b5-4d595648d2a8.png)
The str representation looks good, but it it getting thr wrong length

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll see what we can do about it.
