### ISSUE TITLE
Project explorer context menu misses "Copy..." option

### ISSUE THREAD

**Issue by bilderbuchi** [spyder-ide/spyder#2358]
The context menu for a file in the project explorer has a Delete, Rename, and Move option, but not a Copy option, which seems like an inadvertant omission, and would be good to have.

On Spyder 2.3.4.

**Comment by goanpeca** [comment]
Projects will be revamped completely, but I will take note

**Comment by ccordoba12** [comment]
Agreed, let's close it.
