### ISSUE TITLE
Spyder fails to start because of problems with lockfile

### ISSUE THREAD

**Issue by chepyle** [spyder-ide/spyder#2363]
Starting spyder from the windows command prompt by typing `spyder` results in the following error:

```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\spyder-script.py", line 2, in <module>
    start_app.main()
  File "C:\Anaconda\lib\site-packages\spyderlib\start_app.py", line 79, in main
    if not lock.lock():
  File "C:\Anaconda\lib\site-packages\spyderlib\utils\external\lockfile.py", line 174, in lock
    kill(int(pid), 0)
UnicodeEncodeError: 'decimal' codec can't encode characters in position 0-3: invalid decimal Unicode string
```

Despite un/reinstalling Anaconda, the problem persists

Anaconda 2.2.0 distribution/ Win7 64bit

**Comment by Nodd** [comment]
Try to reset spyder's preferences, you should have a shortcut for this action in the start menu.

**Comment by chepyle** [comment]
Thanks for the fast response, clicking the link in the start menu doesn't
resolve the issue, and manually typing in `python spyder-script.py --reset`
at the command prompt results in the same error message.

**Comment by Nodd** [comment]
Strange, since this error is linked to a file stored in the spyder's preferences folder. I'm afraid I won't be able to help you any further, you'll have to wait for someone more knowledgeable....
As additional information, what python version do you use, and dou you to have Unicode characters in your username ?

**Comment by chepyle** [comment]
I'm using in python 2.7.9, and my user id has no Unicode characters.  Thanks again for looking into it so quickly, I'll continue to investigate on my end.

**Comment by chepyle** [comment]
Ha, the preferences reset wasn't working, but deleting the `spyder.lock` folder in my `.spyder2` user folder did the trick.  Thank you for identifying the preferences folder as the source of the problem!

**Comment by Nodd** [comment]
Good to see that your problem is solved !

Still, not resetting `.spyder2` is a bug on its own. When you ran it from the console, there was no error message ?

**Comment by chepyle** [comment]
Entering `python spyder-script.py --reset` in the cmd console gave the same error as trying to start spyder.

**Comment by ccordoba12** [comment]
This is a problem I've seen several times on Windows, so we need to fix it.

I work on it for 2.3.5.

**Comment by milindsmart** [comment]
When this problem occurred for me, neither any of the fixes suggested, nor the new version worked. 

What did work was https://github.com/spyder-ide/spyder/issues/2858#issuecomment-165913997 .. For future reference.
