### ISSUE TITLE
Use Transifex as a translation platform

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2365]
So @ccordoba12 gave a little nudge to take a look at [transifex](transifex.com) for translations and I am adding it here so maybe there can be some questions/answers about it if any.

I already created an organization, and I think it could help improving outreach by having mor translations (which might also be part of the website eventually)

If you all @spyder-ide/core-developers consider this would help, then maybe you should consider signing in, and handing your handles over so I can make you managers/coordinators/reviewers... etc 

Cheers

**Comment by goanpeca** [comment]
@manipuladordedados can you join as well?

**Comment by manipuladordedados** [comment]
@goanpeca yes, looks promising
