### ISSUE TITLE
Figure Save dialog looses focus. 

### ISSUE THREAD

**Issue by chrisjcameron** [spyder-ide/spyder#2373]
## Description
- _What steps will reproduce the problem?_
- Set iPython graphics to "automatic"
- Create a matplotlib figure
- Choose Save Figure on figure viewer.
- Text for file name can be highlighted but typed characters go the the active spyder editor. 
- _What is the expected output? What do you see instead?_
  Would expect to be able to type the name of the file in the save dialog
- _Please provide any additional information below_
  ## Version and main components
- Spyder Version:  2.3.4
- Python Version:  2.7.9
- Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin
## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.3   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

**Comment by goanpeca** [comment]
If I try to set this to automatic, no figure viewer pops up. Thoughts @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
It does for me. The figure pops up in a matplotlib figure manager and not in the plots plugin.

You need to restart the console for the change to take effect though.

**Comment by ccordoba12** [comment]
This is not something we can solve here.

**Comment by goanpeca** [comment]
>You need to restart the console for the change to take effect though.

Ahhhh ok :-p 

Can you replicate this issue?

**Comment by jnsebgosselin** [comment]
> > You need to restart the console for the change to take effect though.
> 
> Ahhhh ok :-p
> 
> Can you replicate this issue?

If I understand the issue correctly, it is working as expected for me.


![save_figure](https://user-images.githubusercontent.com/10170372/69765928-d9a26100-1143-11ea-9fc0-d0436235b0e3.gif)
