### ISSUE TITLE
Rename Object Inspector plug-in

### ISSUE THREAD

**Issue by SylvainCorlay** [spyder-ide/spyder#2376]
I am not sure if Object Inspector is the right name for the inline help / documentation plug-in. What do you think?

**Comment by ccordoba12** [comment]
Yes, I totally agree. I was thinking to rename it to *Help*. I haven't done it because I'm not sure if we should rename it in the code too.

What do you think? @goanpeca, @blink1073, @Nodd?

**Comment by goanpeca** [comment]
I would prefer renaming it in the code as well, it would be better in the long run...

**Comment by blink1073** [comment]
*Help*, I need somebody!  *Help*, not just anybody!  *Heeeeeeeeeelp*.

(Yes, I agree)

**Comment by goanpeca** [comment]
Someone is happy...

**Comment by Nodd** [comment]
I agree on renaming UI and code !

**Comment by bilderbuchi** [comment]
"Documentation" may be more appropriate, becaus that's what it displays (docstrings, function signature).
