### ISSUE TITLE
Spyder can't switch lines of code when those two lines are the last two in the file

### ISSUE THREAD

**Issue by 22csnyder** [spyder-ide/spyder#2379]
Spyder (Python2.7)

Should be an easy fix.

If you try to use alt+arrows to switch two lines of code in a .py file, the will not switch iff the two lines are the last two lines of code (counting empty lines)

-Chris

**Comment by ccordoba12** [comment]
@blink1073, could you take a look at this one?

**Comment by blink1073** [comment]
On it.
