### ISSUE TITLE
Are there commands that I can issue to restart a Python console from Spyder (I am using Spyder 2.3.4 on Ubuntu 14.04) 

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2380]
Hi,

I want to, by default, restart the Python console whenever I run a Python script.  I want to do that in order clean the slate before running the code.  Currently I kill the current Python console and restart manually.  Is there a way I can implement the two actions successively through commands?  I appreciate your help in advance.

Srini

**Comment by goanpeca** [comment]
Are you running a script? why not press F6 and make spyder always use a new python interpreter?

**Comment by s0r2637** [comment]
Yes.  How can I avoid manually pressing F6 and simply add an equivalent
command at the top of my script.

Srini

**Comment by Nodd** [comment]
F6 is for configuring the launch of your script. Here you can set the script to run in a dedicated console, restarted each time you run with F5.
Given what you said it's exactly what you need.

Also in spyder's setting you can set wich mode to use by default.

**Comment by s0r2637** [comment]
Thanks.

I see I can set  Python to run in a new console each time I issue F5.
However, the scientific startup script does not run when a new Python
console is run.  So I have to reload all the standard modules: scipy,
numpy, matplotlib, etc.

I hope you understand what I am talking about.

Srini

**Comment by Nodd** [comment]
You should import them in your script then.
