### ISSUE TITLE
Disable post-crash popup in dev mode

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2381]
OK, I have this friend of mine who develops spyder and spyder plugins and sometimes this makes spyder crash. And this friend of mine is annoyed to have a popup reminding him of his previous failure, so he'd like to know if you would be in favor of disabling this in dev mode (when running `bootstrap.py`) ?
The actual problem is that it slows down testing and disrupts the coding flow.

**Comment by goanpeca** [comment]
hehe :+1:

**Comment by blink1073** [comment]
:+1: gor my friend too

**Comment by ccordoba12** [comment]
It should be an easy fix, I'll do it this afternoon.

**Comment by ccordoba12** [comment]
Done when you start Spyder with `boostrap.py` :-)

**Comment by Nodd** [comment]
My friend says thank you!
