### ISSUE TITLE
Cells should stop at end of block

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2384]
Cells are highlighted from start to the next cell marker. This doesn't work well with indented blocks, where the cell continues outside the block. Here is an example where I added comments to show where the cell begins and where it ends:

```
class A:
    #%%
    def a(self):
        pass

    #%% MyCell
    def b(self):
        pass
    # MyCell should end after this line

class C:
    # MyCell ends after this line
    #%%
    def d(self):
        pass
```

**Comment by ccordoba12** [comment]
@SylvainCorlay?

**Comment by SylvainCorlay** [comment]
Hey, The behavior that I am seeing is the one I expect (I think that we agree it is not a bug).  At the moment cells are an arbitrary division of the code set by the user and are independent of semantic meaning of code (scope etc..). 

@Nodd which kind of behavior would you want exactly?

**Comment by Nodd** [comment]
I agree that it's not a bug, but I think it could be an improvement.

Actually I would like the cell to be defined only inside a bloc of code, So if it"s define in `class A` only code in `Class A` should be highlighted (same for functions...).
What I'm not sure yet is if it should follow the indentation of the code after the cell title or if it should use the title's indentation. It would be different for `Cell2` in this example:
```
class A:
    # %% Cell1
    pass

class A:
# %% Cell2
    pass
```

With the current behavior I have to use cell markers to mark the end of the previous cells. It's not that bad of course but it could be avoided.

**Comment by SylvainCorlay** [comment]
I see.
- Although this would require more parsing, and only be valid for Python (we might want to cover Julia at some points)
- Besides, the former Matlab users that I see around me tend to keep around (along with their source code) some long scripts that are more some kind of *block-notes* than actual run-able scripts. (Almost like a paste bin). This is where they use the "run cell" feature. I fear that trying to be too smart about parsing these could be detrimental.

**Comment by Nodd** [comment]
Right, I only thought about python, it won't work as well in other languages. Still, cells could stop on brackets or `end` keywords as well.

If users use cells as block notes to run a cell it is necessary that it stops at the end of the block, otherwise it would (and will) do many unhealthy things:

```
def func(a,b):
    # %% Bad cell
    a += b
func(c, d)
```
If you run `Bad cell`, what is the expected behavior ?

**Comment by SylvainCorlay** [comment]
Hum, indentation error I guess.

**Comment by ccordoba12** [comment]
I'm -1 about adding new rules to decide when to end a cell.

I think what we have now is quite clear: you need to put cell dividers to decide where a cell starts and where it ends.

Further logic would mean to define a kind of heuristics that for some people can be reasonable, but not so much for others.

**Comment by Nodd** [comment]
Alright, it was just a suggestion !

**Comment by ccordoba12** [comment]
It's fine :-) It just would things much more complex and most probably not all people would discover our hidden heuristics ;-)

**Comment by Nodd** [comment]
This kind of things could be added by plugins but I think it would require monkeypatching or at least heavily depend on spyder's internals, on both case that's not very healthy.
Currently cells work like in Matlab, this is good enough.
