### ISSUE TITLE
Can't report issue on master with PyQt5

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2385]
I get the traceback:
```
Traceback (most recent call last):
  File "/home/joseph/prog/spyder.git/spyderlib/spyder.py", line 2367, in report_issue
    url.addEncodedQueryItem("body", quote(issue_template))
AttributeError: 'QUrl' object has no attribute 'addEncodedQueryItem'
```
`addEncodedQueryItem` is obsolete: http://doc.qt.io/qt-5/qurl-obsolete.html. It should still be available though, I don't know why I don't have it.

This is with Qt and PyQt v5.4.1 and python 3.4.3 on arch linux.

**Comment by ccordoba12** [comment]
@goanpeca, could you investigate this given that you looked at it last time?

**Comment by Nodd** [comment]
Oh, I assigned you because I thought that you were the Qt5 guy.

**Comment by goanpeca** [comment]
Sure i think it should be easy to solve
