### ISSUE TITLE
ipython kernel does not launch -- "connecting to the kernel" message , Yosemite

### ISSUE THREAD

**Issue by GiGonzal** [spyder-ide/spyder#2387]
## Description

Ipython kernel does not launch. There is a message: "connecting to the kernel" and Ipython does not pop up.
- _What steps will reproduce the problem?_
- Run spider from either terminal or the launcher
- Open an ipython console
- _What is the expected output? What do you see instead?_
  An ipython console is the expected output. However, I see a window with a message "connecting to kernel" and it keeps trying apparently.
- _Please provide any additional information below_
  Mac book pro mid-2012, Yosemite 10.10.3
  I've tried to uninstall Anaconda by deleting its folder, and also all the spyder folders, but then, after downloading and re-installing a new version of Anaconda, the problem remains the same.
  I also started to experience this problem with Maverick, the previous OSx version.

No other error messages are raised.
## Version and main components
- Spyder Version:  2.3.4
- Python Version:  2.7.9
- Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin
## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.6.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by cornelius80** [comment]
I too am encountering the same problem of python failing to launch.
I have the same hardware and OS specifications as stated by GiGonzal except for the fact that I am running my codes in a virtual environment with python version 3.4.

**Comment by ccordoba12** [comment]
Could you focus the *Python* console, look for a tab called **Kernel** and see if there are any errors printed there?

**Comment by GiGonzal** [comment]
When I open a Python console (on Spyder), the Kernel tab shows the following info, but there is no a clear error printed there - as far as I can tell.

Message:

NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-20572.json

**Comment by jingpengwu** [comment]
I have the same issue. Due to this issue, I can not launch spyder. But I can use ipython in terminal!

**Comment by Globulle** [comment]
Same issue with the following Linux installation:
`Python 2.7.10 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.4 on Linux`

**Comment by Jeriane22** [comment]
It is very odd, two day ago, the kernel connection worked well and I don't know why today I can not launch spyder (whichever version -2.3.6 or -2.3.7 it is...). Did I make a mistake by quitting spyder unproperly ? or anything else ?
I have the same configuration as previsous :
 Python 2.7.10 64bits, Qt 4.8.6, PyQt4  4.11.3 on Linux

**Comment by garyspatterson** [comment]
I'm having the exact same issue here. All worked fine yesterday; today Spyder can't connect to kernel, with error message "Could not find u'kernel-1525.json' in .../Library/Jupyter/runtime".  

@Jeriane22 did you ever figure it out?

**Comment by icam0** [comment]
I'm having the exact samen problem on El capitan and the newest spyder and iPython

**Comment by antonfisher108** [comment]
I fixed a similar problem by disabling AVG Antivirus while starting the kernel.

**Comment by JeffFletcher58** [comment]
I've been struggling with this issue for two days.  I've tried every suggestion that I found on the web, to no avail.  Today I tried "conda update spyder".  Now Spyder works again...

**Comment by ccordoba12** [comment]
@JeffFletcher58, this could be caused because of a mismatch between Spyder and IPython/Jupyter. Sorry that you have passed through that.

We hope to improve a lot our integration with IPython in Spyder 3.0 with the work we're doing in pull request #2878.

**Comment by ganong123** [comment]
+1 for this bug (I had this issue too).

**Comment by jjm0022** [comment]
Having the same issue currently and I've tried all of the suggested fixes to no avail. 
I've tried with spyder 2.3.8 and 2.3.9 and like all of the others ipython works fine inside terminal.
I'm using OSX 10.10.5

**Comment by antonfisher108** [comment]
Have you tried disabling your firewall before running Spyder?

**Comment by garry-antonio** [comment]
My kernel used to be active before.
I tried to do a factory reset - no luck
I tried instruction on alternative restart - no luck

I temporary disabled my Kaspersky Virus protection on PC start
Restart my PC
Open python tool - Now my kernel is up and running.

It got to be on my Kaspersky settings.

**Comment by JRevati** [comment]
Having the same issue, Ubuntu 14.04, IPython 5.0.1, spyder 2.2.5.
This issue occurred specifically after installing jupyter 1.0
Tried all the solutions and no use!

**Comment by ccordoba12** [comment]
@JRevati, you should also remove your apt-get installed Spyder to avoid possible conflicts :-)

And I'm glad to hear that Spyder 3.0 solved this problem for you!! Yay!

**Comment by ccordoba12** [comment]
Closing, as this seems solved in Spyder 3.0 ;-)
