### ISSUE TITLE
Move helper widgets to helperwidgets.py

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2389]
Refactor the code in charge of the [Check for updates PR](#2321), to move the CheckMessageBox to `helperwidgets.py` file.

Refactor code from the [arraybuilder ](https://bitbucket.org/spyder-ide/spyderlib/pull-request/98/add-array-matrix-helper-in-editor-and)  to move the ToolTip to `helperwidgets.py` file.

**Comment by ccordoba12** [comment]
+1 from me :-)

**Comment by goanpeca** [comment]
Yep, this was a reminder ;-), from me to me hehe
