### ISSUE TITLE
Current EOL status is displayed incorrectly after changing it

### ISSUE THREAD

**Issue by ssoloff** [spyder-ide/spyder#2392]
## Description

After changing the EOL for a file, both the associated menu item and status bar panel do not correctly display the new EOL.
- _What steps will reproduce the problem?_
  1. Open a file with Windows EOL.  (This bug can be reproduced with any initial EOL.  I simply chose one to make the reproduction steps concrete.)
  2. Select **Source > Convert end-of-line characters > Line feed (UNIX)**.
- _What is the expected output?_
  - The **Source > Convert end-of-line characters > Carriage return and line feed (Windows)** menu item is **unchecked**.
  - The **Source > Convert end-of-line characters > Line feed (UNIX)** menu item is **checked**.
  - The **End-of-lines** status bar panel displays **LF**.
- _What do you see instead?_
  - The **Source > Convert end-of-line characters > Carriage return and line feed (Windows)** menu item is **checked**.
  - The **Source > Convert end-of-line characters > Line feed (UNIX)** menu item is **checked**.
  - The **End-of-lines** status bar panel displays **CRLF**.
- _Please provide any additional information below_
  - The menu item continues to display the incorrect EOL until Spyder is restarted.
  - The status bar panel is updated with the correct EOL if you open any menu (e.g. File) and then close it.
  - The status bar panel is updated with the correct EOL if Spyder loses focus and subsequently regains it (e.g. ALT+TAB to a different window and then ALT+TAB back).
  - The status bar panel is updated with the correct EOL after saving the file.
## Version and main components
- Spyder Version:  2.3.4
- Python Version:  3.4.3
- Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Windows
## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by ssoloff** [comment]
Created PR #2393 for this issue.  Please see my comments in part (3) of the commit message regarding the quality of that portion of this fix.  I'm sure there's a better way to do it.

**Comment by ccordoba12** [comment]
Thanks for the bug report and the pull request. I hope to review it soon :-)
