### ISSUE TITLE
Unable to reset settings from the Main Window

### ISSUE THREAD

**Issue by dezember** [spyder-ide/spyder#2401]
Hi,

I have tried reseting the User interface i.e. windows layout from view but I cannot get back to original. 
I have removed the Spyder-Py2.app and reinstalled it but it doesn't restore to default. Also, I have tried using Anaconda but still the same problem. 
![screen shot 2015-05-04 at 6 39 11 pm](https://cloud.githubusercontent.com/assets/10142508/7457520/59bcde9a-f28d-11e4-8195-37f2049c153e.png)

Any suggestion on proper removal of Spyder or setting it to default. Thanks.

**Comment by goanpeca** [comment]
Have you tried running from a console

`spyder --reset` 

?

**Comment by dezember** [comment]
Yes, I did give a try from iPython console and python console and termina,. 

It states, 'name spyder not defined.'

**Comment by Nodd** [comment]
It should be run from a shell, not from python. Alternatively you can delete manually `~/.spyder`, this is exactly what the command above does.

**Comment by dezember** [comment]
Thanks @Nodd . 

rm -f ~/.spyder worked perfectly.

**Comment by ccordoba12** [comment]
This is a complaint I've heard several times lately, so I think it's something we should solve for 3.0.

The idea is to provide a menu entry (under `Tools`?) to let users easily come back to factory settings after a restart.

@goanpeca, would you mind to take a look at it?

**Comment by goanpeca** [comment]
Sure :+1:

**Comment by goanpeca** [comment]
So... the plan would be.

The restart method in `spyder.py` should have a named parameter by default `reset=False`, so that it can pass an extra argument to `restart_app.py` where we can first reset and then restart spyder.

Also I think we could have a soft reset and a hard reset, because some people cannot get spyder fixed when running reset, sometimes they need to fully erase `.spyder`

**Comment by ccordoba12** [comment]
> The restart method in spyder.py should have a named parameter by default reset=False, so that it can pass an extra argument to restart_app.py where we can first reset and then restart spyder.

+1

> Also I think we could have a soft reset and a hard reset

Nop, the problem @dezember was having is that he couldn't call `spyder --reset` because our Mac app can't be called from the console like that. So he needed to remove `~/.spyder2`by hand.

**Comment by goanpeca** [comment]
ok

**Comment by goanpeca** [comment]
I would really like to start working on some PRs, but I really would like to get the gitattributes issue solved soon....

**Comment by ccordoba12** [comment]
We're basically waiting for @SylvainCorlay, who asked to not do it before we merge the FontAwesome PR :-)

**Comment by Anand-s-cmd** [comment]
Thanks, it is working.

spyder --reset
