### ISSUE TITLE
Monospaced unicode output on Spyder-Py2 Windows

### ISSUE THREAD

**Issue by cclauss** [spyder-ide/spyder#2403]
We are building a cross-platform chess game and we want to take advantages of unicode chess characters to show the user a text representation of the game...
```python
# -*- coding: utf-8 -*-
from __future__ import (absolute_import, division, print_function, unicode_literals)
import os, sys

fmt = '''
         PYTHONIOENCODING:   {}
   sys.getdefaultencoding(): {}
sys.getfilesystemencoding(): {}
      sys.stdout.encoding:   {}
      sys.stderr.encoding:   {}

      New Game     
–––––––––––––––––––
  a b c d e f g h  
8 ♜ ♞ ♝ ♛ ♚ ♝ ♞ ♜ 8
7 ♟ ♟ ♟ ♟ ♟ ♟ ♟ ♟ 7
6 ◦ • ◦ • ◦ • ◦ • 6
5 • ◦ • ◦ • ◦ • ◦ 5
4 ◦ • ◦ • ◦ • ◦ • 4
3 • ◦ • ◦ • ◦ • ◦ 3
2 ♙ ♙ ♙ ♙ ♙ ♙ ♙ ♙ 2
1 ♖ ♘ ♗ ♕ ♔ ♗ ♘ ♖ 1 ◀
  a b c d e f g h'''

print(fmt.format(os.getenv('PYTHONIOENCODING', None),
                 sys.getdefaultencoding(),
                 sys.getfilesystemencoding(),
                 sys.stdout.encoding, sys.stderr.encoding))
```
On a Mac, selecting the "Menlo" font in `Preferences-->Console-->Display-->Font` allows the unicode board to appear with proper monospacing. Of the 10 console fonts available in Spyder-Py2 on the Mac, only Menlo displayed the unicode board with proper monospacing.

We could not find a font in Spyder-Py2.exe for Windows that delivered the same monospacing.

__Is there a trick to properly print the chess board above in monospacing in Windows either in the built-in Spyder console or by doing Run into an external System terminal?__

**Comment by ccordoba12** [comment]
It seems (as you found) that that depends on the font used. We don't ship with any fonts included in our installers.

**Comment by ccordoba12** [comment]
We really can't do anything about this one, sorry.
