### ISSUE TITLE
Don't ask to confirm exit on default untitled files

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2413]
This is certainly debatable, but I don't think Spyder should ask you for confirmation before closing a default new file that hasn't even been edited.

If you open Spyder, hit New File, then immediately close it, you get:

![modified](https://cloud.githubusercontent.com/assets/6614695/7508818/fbac96be-f43b-11e4-8809-70272e4508aa.png)

But this message is almost certainly not helpful.   This proposed behavior is what LibreOffice and Gedit do.

**Comment by Nodd** [comment]
We don't want you to leave spyder, that's all ! :smile: 
:+1:

**Comment by ccordoba12** [comment]
It seems @goanpeca is going to solve this issue :-)

**Comment by goanpeca** [comment]
Well now that I am working with the editor, it made sense...
