### ISSUE TITLE
Add shortcut to open last closed tab

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2415]
Ok, I'm being a bit spoiled with this feature request and Spyder is already insanely awesome.

It would be nice to have a keyboard shortcut to re-open the last tab(s) you just closed.  This would be like Firefox or Chromium where you just hit CTL+SHIFT+T a couple times when you mistakenly close some tabs.

**Comment by thewhitetulip** [comment]
@ccordoba12 @goanpeca I would like to work on this!

**Comment by Garrett-R** [comment]
Heyo!

**Comment by goanpeca** [comment]
@thewhitetulip cool, need some pointers?  @Garrett-R, how far in the history you had in mind? I guess the limit will be the same as we currently store in the last opened files?

**Comment by thewhitetulip** [comment]
Yes, I need some pointers..

**Comment by thewhitetulip** [comment]
What I have in mind is that there will be a function which is triggered when we click the close button, I can get the tab object and store it somewhere, maybe a sqlite file or a plain file and then open a new tab with the same file name, that way we can open the tab even after spyder is closed and opened again. I don't know where to start though

**Comment by Garrett-R** [comment]
@goanpeca, good question.  Maybe imitate Firefox?  The default limit seems to be 10 tabs.  I'd guess it would be very rare for someone to need the 11th closed tab.

I also think the history can be flushed between sessions as in Firefox.

**Comment by thewhitetulip** [comment]
we can keep unlimited last closed tabs as well :D

**Comment by thewhitetulip** [comment]
Submitted a pull request: https://github.com/spyder-ide/spyder/pull/2610

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, please rebase PR #2611 in top of 3.x and finish the work of @thewhitetulip :-)

**Comment by thewhitetulip** [comment]
👍

**Comment by mariacamilaremolinagutierrez** [comment]
@ccordoba12 I already did the rebase in top of 3.x after cloning @thewhitetulip 's spyder fork. However I am not sure how to update the PR because I don't have permissions on his repo. I can't push onto it so that the PR is updated. Also, his PR is like this:

![image](https://cloud.githubusercontent.com/assets/3608776/19840735/3458c61e-9ecb-11e6-8764-7b36357ab830.png)

So we'll need to change master and replace it with 3.x

**Comment by goanpeca** [comment]
@mariacamilaremolinagutierrez just take his work and recreate it on a new PR made by you. That is the easiest ;-)

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, as @goanpeca said, after rebasing please keep pushing to the same branch (i.e. `last_open_tab`) and when you're done, just push that branch to your fork, and then create a PR with it :-)

**Comment by mariacamilaremolinagutierrez** [comment]
@goanpeca @ccordoba12 Awesome, I just did that then, I didn't know I could push other people branches to my repos, that's so cool!

**Comment by ccordoba12** [comment]
Yep, that's great!! I've done that several times already ;-)

**Comment by goanpeca** [comment]
:-)

**Comment by thewhitetulip** [comment]
If you need write access to my repo I'd be happy to give you :-)

**Comment by ccordoba12** [comment]
Don't worry @thewhitetulip, she already solved the problem :-)
