### ISSUE TITLE
After enter to get hanging indent, you need 2 undos

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2416]
Type `my_func(x=5,` and the press <kbd>ENTER </kbd>.  

Spyder very awesomely puts you at the correct indentation level.

If you hit <kbd>Ctrl</kbd>+<kbd>Z</kbd>, you expect it to undo the <kbd>ENTER</kbd> but it actually take 2 undos.  It kind of throws off your flow...

(I'm on Ubuntu 14.04 if that matters)

**Comment by definite-purple** [comment]
This appears to be fixed?

**Comment by ccordoba12** [comment]
Ok, let's close it then.
