### ISSUE TITLE
Less real estate for line number column

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2418]
This is a nitpick so feel free to close.

I think the line number column on the left should get less real estate on the screen.  That column seems to be sized to fit a two digit number when we only have single digit line numbers and it gets resized to fit a 3 digit number when we have 2 digit line numbers.

![single_digit](https://cloud.githubusercontent.com/assets/6614695/7509646/42726cac-f448-11e4-9416-b96dbca1fdce.png)

![double_digit](https://cloud.githubusercontent.com/assets/6614695/7509647/48a1e378-f448-11e4-8917-41c10dfd5a67.png)

This starts eating up valuable real estate when working with multiple panels on a laptop.

**Comment by Nodd** [comment]
The additional column is for breakpoints, warning  and TODO markers.

**Comment by goanpeca** [comment]
I do not think we are really doing any fix here as @Nodd points out this extra space serves an specific purpose.

What we could do is add an option in the preferences to show/hide the breakpoints section of the lines numbers, if the user chooses to. Right now there is only an option for Show/hide line numbers

**Comment by Nodd** [comment]
Yeah, we could add an option for the magin.

**Comment by Garrett-R** [comment]
Right, sorry, I totally forgot about those...

**Comment by goanpeca** [comment]
@ccordoba12 should we add an option for this?

**Comment by ccordoba12** [comment]
Nop, I don't think so. This is the first request of this kind I've seen in all my time with Spyder, so we'll be essentially adding an option for one person :-)

**Comment by goanpeca** [comment]
:+1:
