### ISSUE TITLE
Shortcuts for splitting and closing panels

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2419]
Another kind of spoiled feature request from a huge Spyder fan:  it would be nice to have shortcuts to split the panel in the editor instead of having to hit the `Options` button, then `Split horizontally` each time.

And also a shortcut for closing the panel.

**Comment by Nodd** [comment]
Be more than a fan: become a contributor ! :wink: 

I rarely use splitted editor, but why not.

**Comment by Garrett-R** [comment]
Haha, good point!  Well, I contribute to Pandas which I believe is upstream of Spyder...

**Comment by goanpeca** [comment]
@Garrett-R you should give it a try

**Comment by ccordoba12** [comment]
+1 from me, both to add shortcuts for those actions and to receive a PR from @Garrett-R ;-)

**Comment by Garrett-R** [comment]
Uh oh, sorry to let you guys down, but I don't think I'm going to, even though I know it's lame to ask for all this stuff, then not help out. :worried:  I just think I can contribute to the free software movement more efficiently by working on Pandas which is more similar to what I do at work.  They also have a whopping 1200+ issues!

**Comment by goanpeca** [comment]
This is an easy fix so you should really give it atry

**Comment by Nodd** [comment]
I totally understand that you can't contribute to every software you use! The fix itself may not be complicated but understanding how and where it should be done, following the code style, updating the PR after each comment, all this takes time.
Go go pandas Go !

**Comment by Garrett-R** [comment]
:+1:

**Comment by goanpeca** [comment]
I understand it as well :-), no pressure there @Garrett-R 

I will put this in my bucket list, this means I will probably take care of it anywhere between a week or a couple of months....

**Comment by Garrett-R** [comment]
Cool, thanks!
