### ISSUE TITLE
Zoom should not be associated with a file

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2420]
Currently, the zoom level in the editor is not a global zoom level or even a panel zoom level, but rather each zoom level is associated with a file.

Say you have 10 tabs open you're working with.  And you decide you'd like bigger font, so you hit <kbd>Ctrl</kbd><kbd>+</kbd> a few times, but then you switch files and suddenly the font is small again.  You have to do this for all 10 files.

I think the zoom level should be stored for a given panel or just a global zoom level (global for the editor).  I personally like the panel zoom levels, because you could have one panel you're mostly working in with bigger font, and then a secondary panel with small font.  Like this:

![split_fonts](https://cloud.githubusercontent.com/assets/6614695/7521201/e1f35860-f4a0-11e4-8fd5-227a9548b7ce.png)

**Comment by Nodd** [comment]
:+1: for a global zoom.
By "panel zoom levels", you mean when the editor is splitted ?

**Comment by goanpeca** [comment]
I can take a look at this... should be an easy fix.

**Comment by Garrett-R** [comment]
@Nodd, exactly.  I also added a screenshot to clarify.  Not sure if that panel-zoom is more useful to others than a global-zoom, but just an idea.

**Comment by goanpeca** [comment]
@ccordoba12 you agree with this?

**Comment by goanpeca** [comment]
@Nodd I think the per "panel" will be harder cause we do not keep track of splits, and splits are done recursively one on top of each subsequent spliter. Maybe we should keep track of this...

**Comment by goanpeca** [comment]
@Garrett-R we can implement all options, per editor, per panel, or global... now the question @spyder-ide/core-developers is if we should add options to control this behavior?

We could have: 

- [ ] Use global zoom for all editor stacks
- [ ] Use zoom per split stack

**Comment by ccordoba12** [comment]
I **don't** agree with this. `Ctrl++` and `Ctrl+-` work like in browsers, i.e. they are temporary and they work on a per page (file, in our case) basis.

If you want to increase the font size of every file, that's very easy: just go to

    Preferences > Editor

and select a bigger point for your current font :-)

**Comment by ccordoba12** [comment]
@goanpeca, thanks for understanding :-) We don't need to add option after option for these kind of things, just tell users how things work in Spyder.

**Comment by goanpeca** [comment]
True, I completely forgot about the font size :smile:

**Comment by Garrett-R** [comment]
I know the issues already closed and I don't want to waste your guys' time, so feel free to just ignore my rebuttal here. :stuck_out_tongue_winking_eye: 

Actually, I was aware of the ability to set global zoom through `preferences`.  It just seemed like surprising behavior when I use CTL+mousewheel to zoom in (say I'm leaning back fruther from the screen, or I've gone down to a single panel), and then I switch tabs and suddenly the font gets smaller.

Browsers are different I think you open different websites, you might open a website with tiny text and then one with huge text, so "per-domain zoom settings" are ideal.  But for code, I can't think of any situation where someone is flipping between two files and they desire `fileA.py` to be in one font size and `fileB.py` to be in a different font size.

Hmm... interesting, I see Qt Creator (my favorite C++ IDE) has CTL+mousewheel control global zoom-level, while Code::Blocks, Geany, Eric and Ninja IDE have it controlling per-file zoom.  Wow, I'm kind of surprised....

**Comment by vasselai** [comment]
Sorry to necro this discussion, but I am not sure whether it makes sense for me to open a new issue about this. I mean, it totally makes sense that if one wants to zoom in for all files, one should just go there and change the font size in the preferences. The problem, however, is that Spyder does not allow anymore one to define different font sizes for Editor and Console. The consequence is that if one uses Spyder in a big wide monitor and wants to increase the Editor's font accordingly, the font for the console becomes just huge.

Could you guys consider a way of solving that? Should I put a new issue asking to check for this?

Thanks!

**Comment by ccordoba12** [comment]
@goanpeca, what do you think? I don't know what we could do about it from the user experience point of view.

**Comment by goanpeca** [comment]
Hmmm me neither need to think about it

**Comment by jnsebgosselin** [comment]
I think that could be a good idea to be able to set the font size and family independently for the Editor and the Console. Basically, we could take the same layout as for the font preference in "Genenal" and put it under "Editor" and "IPython console" instead. 

Font size in General should not be related  to the font of the Editor and the IPython console in my opinion, but to the font of the UI. It is more coherent with other options found on this panel such as `Qt windows style` and `Icon style`.

**Comment by jnsebgosselin** [comment]
@vasselai  That being said, one quick solution for this could be to set the font in the preferences so that it looks good in the Editor and Ctrl- in the console to reduce the font of the console.

**Comment by LouisAsh** [comment]
Thanks you all for taking the issue into consideration. I do think that allowing such customizations to be different for the editor and for the console could be pretty helpful. Specially in the age of big resolutions.

@jnsebgosselin That is precisely what I have been doing. Whenever I start Spyder, I go there to the console and Zoom out with Ctrl -. That is exactly what made me come here to talk about this: I thought that if the program allows me to zoom in or out the font size to different levels in the console and in the editor, it could be easy-ish to allow them have different levels at the start state.

**Comment by vasselai** [comment]
Thanks you all for taking the issue into consideration. I do think that allowing such customizations to be different for the editor and for the console could be pretty helpful. Specially in the age of big resolutions.

@jnsebgosselin That is precisely what I have been doing. Whenever I start Spyder, I go there to the console and Zoom out with Ctrl -. That is exactly what made me come here to talk about this: I thought that if the program allows me to zoom in or out the font size to different levels in the console and in the editor, it could be easy-ish to allow them have different levels at the start state.

By the way, annother option would be to have "zoom level" as a different parameter from "font size".

**Comment by jnsebgosselin** [comment]
I think a new issue should be opened for this since it is a different problem than the one described in the OP.

**Comment by ccordoba12** [comment]
Yes, @vasselai, please open a new issue for your concern.
