### ISSUE TITLE
Qt4's WebKit removal in Debian/Ubuntu

### ISSUE THREAD

**Issue by picca** [spyder-ide/spyder#2421]
Hello guyes,

since the unfreeze of Debian :), we started to prepare the next release.
I just got this bug report [1] of pyqt4 removal.

can you tell me if spyder is qt5 ready ?

thanks a lot

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=784613

**Comment by Nodd** [comment]
The master branch has Qt5 support (feel free to try it!), but we're still finding little bugs here and here. It should be ready for the next debian version.

**Comment by picca** [comment]
> The master branch has Qt5 support (feel free to try it!), but we're still finding little bugs here and here. It should be ready for the next debian version.


thanks for the informatin.
have you done something for guidata and guiqwt ?

**Comment by Nodd** [comment]
I think that [guidata](https://github.com/PierreRaybaut/guidata) and [guiqwt](https://github.com/PierreRaybaut/guiqwt) are not maintained anymore. :(

**Comment by ccordoba12** [comment]
@picca, why QtWebkit is going to be removed for Qt4?

**Comment by ccordoba12** [comment]
This is not a proper issue, so I'm closing it.

I think this should have gone in our mailing list because it's just asking for info :-)

**Comment by perezmeyer** [comment]
Qt4's QtWebkit will be removed in Debian Stretch, yes.
