### ISSUE TITLE
Selecting line numbers from the side areas with pointer potentially buggy?

### ISSUE THREAD

**Issue by macjas** [spyder-ide/spyder#2422]
I'm not sure if this is a bug or just something broken in my local install. But every time, I try to select a line from the editor's side areas, it randomly selects a few line numbers above. 

To elaborate, if I select line 13, line 9 gets highlighted, selecting line 20 highlights line 13. I know this is a minor issue but somewhat frustrating as I am so used to using my mouse pointer to select lines from the sidebar (I'm a regular R user switching to Python/Pandas/Scikit-Learn.

My system:
Thinkpad T430 Laptop w/ Win 7 64bit
Using the latest distribution of Anaaconda

**Comment by Nodd** [comment]
I can't reproduce this problem (Linux, Qt5)

@goanpeca I think  you did this, any idea ?

**Comment by goanpeca** [comment]
Me neither :s .... no idea what might be happening...

**Comment by macjas** [comment]
Hmmm maybe its my local environment then. Strange.... I even tried re-installing the entire Anaconda repo.

**Comment by goanpeca** [comment]
Can you try running from the master and see if the behavior is in master as well in your config?

**Comment by macjas** [comment]
Sorry, how do I do that? :) I'm really very new to Sypder and Python in general!

**Comment by goanpeca** [comment]
Ah ok, can you take a look in the wiki [here](https://github.com/spyder-ide/spyder/wiki/Dev%3A-Github-Workflow) and read the users part?

You need to have git installed. [Look here ](http://git-scm.com/book/en/v2/Getting-Started-Installing-Git)

And you need to work in the command line/shell (windows/unix)

**Comment by macjas** [comment]
Actually, I just noticed that the problem disappears when I open a new blank file. However, on a medium sized file (around 200 lines), the problem re-appears :). 

Okay, give me sometime to go through the users part on the Spyder wiki and I'll get back to you..

**Comment by goanpeca** [comment]
:+1:

**Comment by macjas** [comment]
Okay, so I installed Spyder using one of the installers on the master fork. It seems to have solved the problem. Not sure if there was some incompatibility with my laptop system from installing Spyder from Conda vs from here. In any case, I'm happy!

**Comment by goanpeca** [comment]
:+1:

**Comment by ccordoba12** [comment]
@macjas, I think you were just using an old Spyder version :-)
