### ISSUE TITLE
can't find pylint installed as python3-pylint

### ISSUE THREAD

**Issue by pijyoi** [spyder-ide/spyder#2427]
Under Fedora, package python3-pylint installs itself as /usr/bin/python3-pylint.
Spyder 2.3.4 however only looks for "pylint" in PYLINT_PATH and get_pylint_version().

**Comment by goanpeca** [comment]
Seems like an easy fix @pijyoi, want to give it a try?

**Comment by ccordoba12** [comment]
@pijyoi, are you sure that the executable is called `python3-pylint` and not `pylint3`?

**Comment by ccordoba12** [comment]
Don't worry, I verified that's the case :-)

**Comment by ccordoba12** [comment]
This fix will be released as part of Spyder 3.0, in a couple of months. Thanks for reporting :-)
