### ISSUE TITLE
crash with "unknown string format" editing in-place in variable explorer

### ISSUE THREAD

**Issue by dmd** [spyder-ide/spyder#2435]
Start Spyder. Enable preferences > variable explorer > display > always edit in-place.

In a console:
```
from dateutil.parser import parse
x=parse('2015-01-01')
```
In variable explorer, double-click the value of x and make an edit. Spyder will crash.

**Comment by ccordoba12** [comment]
I don't know what Spyder version you're using, but `Always edit in-place` is not available anymore (I think since Spyder 2.3.2).

However, your report help to fix a problem with dates in master :-)

**Comment by dmd** [comment]
Sorry, I was using the version that's in the Ubuntu 14.04 repo.

**Comment by ccordoba12** [comment]
No biggie ;-) Ubuntu versions are always outdated.
