### ISSUE TITLE
Use a single font for all panes

### ISSUE THREAD

**Issue by kigawas** [spyder-ide/spyder#2438]
![image](https://cloud.githubusercontent.com/assets/4182346/7614120/53c58622-f9c7-11e4-8033-7b63248ca13f.png)

Just like the image above, I want to change the font in the right side to some better fonts( now it is hard to read), how should I do that?

**Comment by Nodd** [comment]
AFAIK the font comes from the Qt theme.
Are you on widows, Linux, Mac ? Which spyder version ? You can create a bug report with these informations automatically by using the Help menu, and copy-paste the content here.

**Comment by ccordoba12** [comment]
Just go to the **Editor** entry on the left to select a different font. You can configure a different font for every pane, but perhaps that's too much :-)

@Nodd, @goanpeca, what do you think?

**Comment by ccordoba12** [comment]
I mean, should we use a single font for all panes?

**Comment by babykiss4ever** [comment]
@Nodd @ccordoba12 
I use Spyder's latest version on **Windows 8.1 with Anaconda**.

I had a experience in developing Qt application so I can recognize that is the default Qt font( which perhaps use the **default font for plain text** on the responding platform ). 

So in next versions could there be a setting to configure the IDE's GUI font just like IDEA?
