### ISSUE TITLE
Spyder does not make global constants declared in a module accessible when importing the module

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#2442]
## Description

* *What steps will reproduce the problem?*

1. I created a module with a few definitions and a few constants as global variables
2. when I import the module, I can only access the definitions but none of the constants I defined
3. When I go to Python interpreter in Ubuntu, the constants are accessible through the module. 

 What is Spyder doing on top of the Python intepreter is beyond me.  I have seen numerous such odd-ball cases where running the code in a Python interpreter outside of Sypder works fine, but the same code breaks when run inside Spyder.  I also noticed the same problem in an IPython console.  

* *What is the expected output? What do you see instead?*

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.6
* Qt Version    :  4.8.6, PyQt4 (API v1) 4.10.4 on Linux

## Optional dependencies

pyflakes >=0.5.0:  None (NOK)
pep8 >=0.6      :  None (NOK)
IPython >=1.0   :  None (NOK)
zmq >=2.1.11    :  14.0.1 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  None (NOK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
pylint >=0.25   :  1.4.3 (OK)

**Comment by Nodd** [comment]
What exactly do you mean by "access"? autocompetion? execution in a python console?

**Comment by s0r2637** [comment]
What I mean by access is that is that I cannot use the usual dot (.)
convention to access a global constant defined inside a module.  The dot
(.) convention only works for a subroutine defined inside that module.
Hope this helps.

Srini

**Comment by ccordoba12** [comment]
Please provide a simple example module that is showing the error you're describing, so we can test it and fix it in our side :-)

**Comment by goanpeca** [comment]
@s0r2637  any feedback?

**Comment by s0r2637** [comment]
Thanks for reminding me.  I moved on over this problem.  I will reproduce
this problem, if it still exists with the latest version of Spyder, and let
you know my results.

Srini

**Comment by Nodd** [comment]
Closing for lack of response, feel free to reopen it if needed.
Be aware that due to the dynamic aspect of python, the autocompletion can not always find an object's type so it can not list it's methods or attributes. This is a know problem, and even if there are progress on this it will never be perfect.
