### ISSUE TITLE
Ubuntu 14.04 + Spyder 2.3.4 + Python 3.4: IPython not available

### ISSUE THREAD

**Issue by cordman** [spyder-ide/spyder#2447]
I have just installed Spyder 2.3.4. on my Ubuntu 14.04 x64 machine using "pip3 install" since I am not using anaconda. In former versions I was working with Python 2.7 and had the option to start an IPython shell on the startup. But I can't find this option in the newest version anymore.

At first, I thought my question is related to this question (http://stackoverflow.com/questions/21936277/ipython-not-available-in-spyder) but "sympy" and "ipython" are installed correctly:

```bash
cord@laptop:~$ sudo pip3 install --upgrade ipython
Requirement already up-to-date: ipython in /usr/local/lib/python3.4/dist- packages
Cleaning up...
cord@laptop:~$ sudo pip3 install --upgrade sympy
Requirement already up-to-date: sympy in /usr/local/lib/python3.4/dist-packages
Cleaning up...
cord@laptop:~$ 
```

Btw: IPython is working in version 3.1.0.

Does anyone have an idea why it is not working?

Cheers Cord

**Comment by ccordoba12** [comment]
You need to go to the menu

    View > Panes

and select the

    IPython terminal

entry to activate it. Maybe it's just hidden :-)

**Comment by cordman** [comment]
It is not available in my menu. Any hints?

Cheers
Cord

Am 22.05.2015 um 21:09 schrieb Carlos Cordoba:

**Comment by ccordoba12** [comment]
The other possibility is that you don't have it installed on your system. To have it on Ubuntu and Python 3, you need to install this package:

    sudo apt-get install ipython3-qtconsole

**Comment by cordman** [comment]
This was the missing link. Now it works!

I only had "ipython3" installed and did not know that it has to be
"ipython3-qtconsole". Is this mentioned somewhere?

Thanks anyway!!


Am 25.05.2015 um 20:26 schrieb Carlos Cordoba:

**Comment by ccordoba12** [comment]
You're welcome ;-)

**Comment by ccordoba12** [comment]
Sorry, I forgot to answer to this:

> Is this mentioned somewhere? 

Yes, it's mentioned in our installation docs here:

http://pythonhosted.org/spyder/installation.html#recommended-modules
