### ISSUE TITLE
Spyder crashes using Variable Explorer with BeautifulSoup

### ISSUE THREAD

**Issue by kekel** [spyder-ide/spyder#2448]
I am suspecting that the IDE crashes due to Variable Explorer trying to show an object of class 'bs4.element.NavigableString' derived from a "fairly" large HTML document. See reproducible example below. When the last line of code executes, the IDE freezes and needs to "force quit"/killed and restarted. However, commenting out the last line, it executes fine. 

I further suspect that it can have something to do with the way the "NavigableString" works, and the following quote might shed some light on it for someone familiar with the inner workings of the Variable Explorer: 
> "If you want to use a NavigableString outside of Beautiful Soup, you should call unicode() on it to turn it into a normal Python Unicode string. If you don’t, your string will carry around a reference to the entire Beautiful Soup parse tree, even when you’re done using Beautiful Soup. This is a big waste of memory."
> From http://www.crummy.com/software/BeautifulSoup/bs4/doc/

Indeed, converting to a regular string and it works fine.

```
import urllib
from bs4 import BeautifulSoup

markup = "<html><head><title>My Title</title></head><body></body></html>"
soup = BeautifulSoup(markup)
print(type(soup.title.string))
print(soup.title.string)
str_ok = soup.title.string

url = "http://en.wikipedia.org/wiki/List_of_Python_software"
content = urllib.request.urlopen(url).read()
soup = BeautifulSoup(content)
print(type(soup.title.string))
print(soup.title.string)
str_not_ok = soup.title.string
```

On Mac OS X Yosemite (10.10.3) with Spyder 2.3.4 using Python 3.4.3 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.3 on Darwin. Basically a clean install of Anaconda with all the packages updated.

**Comment by kekel** [comment]
Thank you so much for the fast fix @ccordoba12 !

**Comment by ccordoba12** [comment]
No problem ;-) Freezes and crashes are very serious issues for us!

**Comment by Millow** [comment]
@ccordoba12
I am using Spyder and I have the same exact issue, don't know if I should post here or create a new one, so I'll try here first.

So, I have some code, if I run it without going in the variable explorer, it works perfectly. But, some of the variables are NavigableString, if I open the Variable Explorer, it crashes instantly. My only solution for now is to manually delete the variables prior to opening the Explorer.

Have a good day

**Comment by ccordoba12** [comment]
This will be fixed in 3.2.5, not released yet.

**Comment by Ares8947** [comment]
@ccordoba12  I used the Latest edition Anaconda2018.12  Spyder3.3.2,python 3.7.1
The same mistake happened.
Open BeautifulSoup Result in Variable Explorer,
The Spyder crashed.

Code:

from bs4 import BeautifulSoup
from urllib.request import urlopen
import re
import random
import urllib

base_url = 'https://baike.baidu.com'
temp = '网络爬虫'
new_his = urllib.parse.quote(temp)
new_url = base_url + '/item/' + new_his + '/5162711'
html = urlopen(new_url).read().decode('utf-8')
soup = BeautifulSoup(html,features='lxml')
new_soup = soup.find('h1').get_text()
sub_urls = soup.find_all('a',
                         {'target':'_blank',
                         'href':re.compile('/item/(%.{2})+$')})

Open sub_urls or soup，
But I enter variable in Ipython concole，it can work.

**Comment by ccordoba12** [comment]
Please open a new issue about it.
