### ISSUE TITLE
can't run stuff i can run fine from terminal

### ISSUE THREAD

**Issue by eflister** [spyder-ide/spyder#2449]
installed py-spyder-2.3.4 from macports, but it can't run stuff that i can run fine from terminal:

```
In [1]: import picos;picos.tools.available_solvers()
Out[1]: ['cvxopt', 'mosek7']

In [2]: runfile('/Users/eflister/sima/examples/workflow.py', wdir='/Users/eflister/sima')
Traceback (most recent call last):

  File "<ipython-input-2-4b36baecec87>", line 1, in <module>
    runfile('/Users/eflister/sima/examples/workflow.py', wdir='/Users/eflister/sima')

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/Users/eflister/sima/examples/workflow.py", line 20, in <module>
    import sima

  File "sima/__init__.py", line 7, in <module>
    from sima.sequence import Sequence

  File "sima/sequence.py", line 68, in <module>
    from sima.motion._motion import _align_frame

  File "sima/motion/__init__.py", line 5, in <module>
    from .motion import MotionEstimationStrategy, ResonantCorrection

  File "sima/motion/motion.py", line 14, in <module>
    from . import _motion as mc

ImportError: cannot import name _motion
```

**Comment by ccordoba12** [comment]
This line (and the following in your traceback)

    File "sima/__init__.py", line 7, in <module>

seem to indicate that you have the `sima` package (or a package called `sima`) in the same directory as your `workflow.py` example.

That seems to be the most probable cause of your problem because it seems that `sima` dir doesn't contain everything to be expected in the real sima package.

**Comment by eflister** [comment]
the situation is that i have a pip-installed sima, but they neglected to include their examples directory in that distribution, so i also have a git repository clone in order to have workflow.py.  that sima directory definitely includes everything.  outside of spyder, it works fine.
```
~/sima/examples$ python workflow.py
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/skimage/filter/__init__.py:6: skimage_deprecation: The `skimage.filter` module has been renamed to `skimage.filters`.  This placeholder module will be removed in v0.13.
  warn(skimage_deprecation('The `skimage.filter` module has been renamed '
TIFF filenames:
...
```

**Comment by ccordoba12** [comment]
Closing because it doesn't seem a Spyder problem

**Comment by eflister** [comment]
what makes you say that?  it works fine in terminal, and doesn't work in spyder.

**Comment by ccordoba12** [comment]
It's probably because you're using Spyder Python Path manager to add the sima directory (which doesn't contain the sima package) to `sys.path`. Or something like that, I don't know.

Sorry, but this seems a problem that only occurs with your setup.

**Comment by eflister** [comment]
i just installed stuff with pip in a terminal.  if it works in terminal, shouldn't it work in spyder?

**Comment by ccordoba12** [comment]
Ok, then tell us a step by step procedure to test this, starting with `pip install <the package you're using>` and ending with a reproducible example of the code you're trying to run in Spyder.

**Comment by Nodd** [comment]
In the first run you're in the directory `/Users/eflister/sima`, while in the second one you're in `~/sima/examples`. Try to run both of them from the same directory.
