### ISSUE TITLE
frequent import errors that are resolved by restarting spyder

### ISSUE THREAD

**Issue by eflister** [spyder-ide/spyder#2450]
previously thought it was a winpython issue, but now think it might be spyder itself:

https://github.com/winpython/winpython/issues/96

**Comment by ccordoba12** [comment]
You said in your WinPython report:

> i had a winpython setup with a bunch of stuff installed to run https://pypi.python.org/pypi/sima, which worked.

So if things worked correctly without a second WinPython installation, I don't understand how this is a Spyder bug :-)

I mean, if things haven't worked initially then I'd say this could be our problem. But that's not the case, so this seems to be a problem with WinPython and/or the sima package.

**Comment by eflister** [comment]
as described, things work for a while, but then i start getting those import errors.  restarting spyder resolves it for a while.  this applies to each installation -- my original impression that new installations broke old ones was wrong.

**Comment by ccordoba12** [comment]
Sorry for not being able to give you more help :-(
