### ISSUE TITLE
Spyder dies when running code while debugging

### ISSUE THREAD

**Issue by Success2014** [spyder-ide/spyder#2453]
This happened many times while I was debugging using Spyder.
Sometimes I can type in code in the IPython Console above the ipdb> arrow, then everything seems to be frozen.
Nothing got printed out. After that, I can still type in codes. However, nothing can be executed.
I tried enter button, exit debug button, run button, etc. I could only type in codes.
At last, the only thing I could do is restart the kernel.

Spyder shouldn't allow the user to type in code above the ipdb> arrow.

**Comment by ccordoba12** [comment]
Ideally, you shouldn't use `ipdb` to enter code, just debug commands (like `b` or `c`). That's because `ipdb` doesn't accept arbitrary Python code.

**Comment by Success2014** [comment]
Same thing happened just now. Check the attached pictures.

![capture](https://cloud.githubusercontent.com/assets/7728287/7892747/a49923f4-061c-11e5-96ca-1b3d5f1bcd05.PNG)
![capture1](https://cloud.githubusercontent.com/assets/7728287/7892748/a499ad2e-061c-11e5-8758-e1ee918ca1d0.PNG)

**Comment by ccordoba12** [comment]
Could you post an example of the code you're trying to debug that is causing this error?

**Comment by JohnSmizz** [comment]
I encountered the same issue... 
When writing code, eg displaying a pandas dataframe (pandas_df.tail()) in the ipdb command line, and, remarkably, evne when just copy-pasting code that was displayed by the ipdb debugger above (as part of trace).

I am running Anaconda Python 3.4 with Spyder 2.3.8

**Comment by goanpeca** [comment]
Closing then @ccordoba12 ?
