### ISSUE TITLE
spyder does not intelligent indent at the second comma

### ISSUE THREAD

**Issue by Houinside** [spyder-ide/spyder#2454]
## Description

* *What steps will reproduce the problem?*
It do happen when type in the follow block in spyder editor.
```
matrix_A = [[1,2,3,4],
            [2,3,4,5],
[3,4,5,6]]
```

* *What is the expected output? What do you see instead?*
Well, the expected output is
```
matrix_A = [[1,2,3,4],
            [2,3,4,5],
            [3,4,5,6]]
```

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.3
* Qt Version    :  4.8.1, PyQt4 (API v2) 4.9.1 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  0.6.1 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.6.0 (OK)
pygments >=1.6  :  1.4 (NOK)
pandas >=0.13.1 :  0.16.1 (OK)
sphinx >=0.6.6  :  1.1.3 (OK)
psutil >=0.3    :  None (NOK)
rope >=0.9.2    :  0.9.2 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  0.25.0 (OK)

**Comment by blink1073** [comment]
@Houinside, where are you hitting `Return`.  If it paste this and hit `Return` between the last two lists, they are aligned (on the latest development version).

```python
matrix_A = [[1,2,3,4],
            [2,3,4,5], [3,4,5,6]]
```

```python
matrix_A = [[1,2,3,4],
            [2,3,4,5],
            [3,4,5,6]]
```

**Comment by ccordoba12** [comment]
Closing because of lack of response
