### ISSUE TITLE
Report issue... redirecting to code.google

### ISSUE THREAD

**Issue by rudregues** [spyder-ide/spyder#2459]
Spyder Version:  2.3.0
Python Version:  3.4.0
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.2.1 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.1.0 (OK)

The funcionality <code>right click -> Report issue...</code> is redirecting to https://code.google.com/p/spyderlib/issues instead of https://github.com/spyder-ide/spyder/issues/new

**Comment by ccordoba12** [comment]
Please update to our latest Spyder version (**2.3.4**), which has a fix for this problem.
