### ISSUE TITLE
Plugin: Make a terminal plugin for use on Linux with Terminado

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2461]
This is a request I received at SciPy Latin America.

Having a terminal as part of an IDE is quite handy, for example to do git commits or start/stop OS services. Projects like Geany have one, and it was mentioned to me that that's one of the main reasons people prefer it over Spyder :-)

We should try to use an external project (e.g. [qbash](https://github.com/olitheolix/qbash)) to do this, probably as an external plugin.

**Note**: Issue #306 has some discussion about this too.

**Comment by goanpeca** [comment]
@thewhitetulip this is something you are still willing to go for?

**Comment by thewhitetulip** [comment]
Yes, I am, but I am not getting time out of work. I can squeeze some time in later this month though.

**Comment by Nodd** [comment]
It would fit nicely as a plugin, as it's just a widget with a few connections to spyder internals.

**Comment by thewhitetulip** [comment]
Yes, @Nodd also another thing that makes it more suitable as a plugin is that the project this is going to be based on is a GPL2 licensed, so we can't really use it in spyder directly. I will ask for assistance when I start working on it, probably this month end.

**Comment by goanpeca** [comment]
This would be very easy to do now with the plugins interface.

I created a [repo](https://github.com/spyder-ide/spyder.qbash)

**Comment by ccordoba12** [comment]
@goanpeca, I renamed it to `spyder.terminado` because the idea is to embed Terminado (not QBash), as we've talked about :-)

**Comment by goanpeca** [comment]
Ahh ok :-)

**Comment by ccordoba12** [comment]
It's easier for us because Terminado provides terminals for the Jupyter notebook.

So it's a project that's going to be well maintained in the future :-)

**Comment by goanpeca** [comment]
Agree :+1:

**Comment by ccordoba12** [comment]
This is going to be developed by @andfoy in an external plugin.
