### ISSUE TITLE
Failure to preserve Matplotlib backend when using symbolic math

### ISSUE THREAD

**Issue by FredJames32** [spyder-ide/spyder#2463]
## Description

Mac OSX. Spyder IPython console initially did inline graphics. But after I checked "Preferences/IPython console/Advanced Settings/Use symbolic math", whenever I launched Spyder anew, plots were in separate window. So, I had to a "% matplotlib inline" if I wanted inline charts. This was the case even though "Preferences/IPython console/Graphics/Backend/Inline" was set. Then, I realized that if I unchecked "Preference/.../Use symbolic math", then Spyder and new IPython console plot inline by default.

* *What steps will reproduce the problem?*
1.
2.
3.

* *What is the expected output? What do you see instead?*

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. I'll take a look at it to see what we can do about it.

**Comment by FredJames32** [comment]
I further noticed that if you are in inline plot mode and import sympy and call sympy.init_session() from IPython console, then you loose the inline mode and plots pop up in separate windows.

**Comment by FredJames32** [comment]
I further noticed that if you are in inline plot mode and import sympy and call sympy.init_session() from IPython console, then you loose the inline mode and plots pop up in separate windows.
