### ISSUE TITLE
Add support for .editorconfig

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2464]
I think it would be a good idea to add native support for editor config using the already existing [python module](https://github.com/editorconfig/editorconfig-core-py). We could bundle the module within spyder in the `external-py...` dirs

I know we could add this as a plugin for spyder, but I think having built-in support would  give Spyder more visibility perhaps?

http://editorconfig.org/#download

**Comment by ccordoba12** [comment]
I think @techtonik was interested on this too.

**Comment by techtonik** [comment]
Duplicate of #2336. =)

**Comment by Nodd** [comment]
I think it fits well as a core functionnality, more than a plugin.
Closing since it's a duplicate.
