### ISSUE TITLE
No Notification of Running Instance

### ISSUE THREAD

**Issue by jpiersol** [spyder-ide/spyder#2466]
If spyder is already running in single instance mode, attempting to run "spyder" again just terminates the new process without notification. A simple notification, "Spyder is already running," would be helpful for troubleshooting (consider running spyder locally, then trying to open it in VNC, and not being able to understand why the process is terminating).
____________________________________

My apologies if I haven't submitted this request in the proper venue; I'm not a frequent contributor to Spyder or open-source projects in general. Let me know if there's a better way.

**Comment by ccordoba12** [comment]
You're right, and I've thinking to add a warning for a long time :-)

I'll try to address it for 2.3.5.
