### ISSUE TITLE
Style Analysis via pep8 appears to no longer work in v2.3.4

### ISSUE THREAD

**Issue by dougthor42** [spyder-ide/spyder#2472]
### Summary:
Style analysis via pep8 appears to no longer work in Spyder 2.3.4.

----
### Steps to Reproduce:

1. Open a new blank python file in Spyder 2.3.4.
2. Verify the following settings in Editor -> Code Introspection/Analysis -> Analysis:
  1. Code analysis (pyflakes) is **un**checked
  2. Style analysis (pep8) is **checked**
  3. Radio button "Perform analysis when saving file and every 2500ms" is selected.
3. Type anything, say "sdfjhsdlgh", onto the 1st line of the new file. I've chosen to write a string with the spyder version.
4. Make sure to *not* have a newline at the end of the file (trying to get W292 error to appear).
5. Notice that the analysis triangle is **not** displayed: ![image](https://cloud.githubusercontent.com/assets/5386897/8011685/9e76f246-0b6f-11e5-891a-ac528f17b017.png)

##### Now try it in Spyder 2.3.2:
The analysis icon is displayed correctly: ![image](https://cloud.githubusercontent.com/assets/5386897/8011689/aa44454c-0b6f-11e5-9e5b-ca972582be1f.png)

----
### Details:
In Spyder 2.3.2 with pep8 v1.6.2, the Style Analysis plugin worked just fine. Updating to Spyder 2.3.4 and still using pep8 v1.6.2, it appears to not work any more. The best way to show this is with pictures:

**Spyder 2.3.2:**
![code analysis spyder 2 3 2](https://cloud.githubusercontent.com/assets/5386897/8011500/085e4c4c-0b6e-11e5-9143-1983b94032c0.png)

**Spyder 2.3.4:**
![code analysis spyder 2 3 4](https://cloud.githubusercontent.com/assets/5386897/8011517/2e17d232-0b6e-11e5-9e1e-e09ea7080e37.png)

In these images, you can see

1. That I'm looking at the same file
2. that my settings for introspection/analysis are the same
3. the spyder "About" dialog

Yes, the large images also have pyflakes turned on. However, this does not change the result (the file I was working on has no pyflake issues :-P )

**Please let me know if there is anything you'd like me to check to help you debug this issue.**

Thanks guys!

----
#### Versions:
Spyder Version:  2.3.4
Python Version:  3.4.3
Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

IPython >=1.0   :  3.0.0 (OK)
coverage >=0.25 :  3.7.1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.6.0:  0.9.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
zmq >=2.1.11    :  14.5.0 (OK)

**Comment by dougthor42** [comment]
Oh, I just checked it in Spyder 3.0.0dev, pulled 2015-06-05 18:06 UTC (11:06am PDT). Everything appears to be work fine.

I guess I should have checked that before posting. Sorry!

**Comment by ccordoba12** [comment]
@Nodd, this mean we need to update pep8 on 2.3 too?

**Comment by ccordoba12** [comment]
I can't reproduce this error on the stable branch. Things are working just fine :-)

**Comment by dougthor42** [comment]
> I can't reproduce this error on the stable branch.

Interesting... I'll try to see if there's something else going on (if I remember to :-P ). I was checking it with a pretty clean install of WinPython and Spyder, but there may have been something I missed.
