### ISSUE TITLE
Allow sorting by column of Keyboard Shortcuts.

### ISSUE THREAD

**Issue by dougthor42** [spyder-ide/spyder#2475]
It would be convenient if we could sort the Keyboard Shortcuts by column.

It would make it a lot easier to see if a given key is already used. For example, I could see all the items that are bound to F12 just by scrolling down to F12.

It was pretty easy to add, only having to change the plugins/shortcut.py module. I'll submit a PR soon, once I figure out how to do it... :-P

**Comment by goanpeca** [comment]
@dougthor42 do you think that sorting is still needed taking into account that now there will be the ability to search?

![image](https://cloud.githubusercontent.com/assets/3627835/7842178/ce2deffa-04a1-11e5-903e-85229702e279.png)

**Comment by Nodd** [comment]
Looking at the screenshot, I'd put the search bar below the table (but over the reset button). Most important things should be first.

**Comment by goanpeca** [comment]
:+1:

**Comment by dougthor42** [comment]
Having the search will be a big help, but I'm not sure if it will remove the need for sorting.

I'll wait and see if I like it without sorting. If I don't, I'll figure to a way to add it. :-)

Also, :+1: for search bar below table.

**Comment by ccordoba12** [comment]
I think there's no much need for sorting now, but if you want to do it @dougthor42 (again ;-), you're welcome to.
