### ISSUE TITLE
Spyder and Psychopy

### ISSUE THREAD

**Issue by tjhendrickson** [spyder-ide/spyder#2477]
Hello,

I am trying to get psychopy (a python based stimulus presentation program) working along with spyder. I read that I should add the psychopy path to the pythonpath manager in spyder. This has worked for me previously, however it no longer works. This the error code that I get. Any help would be excellent!
![2015-06-09 15_37_01-spyder python 2 7](https://cloud.githubusercontent.com/assets/7429880/8069062/86d075a8-0ebd-11e5-90e4-6e91307d6ffb.jpeg)

**Comment by ccordoba12** [comment]
It seems you need to update IPython or pyzmq to make things work again.

**Comment by tjhendrickson** [comment]
And how would I do that on a windows machine?

**Comment by ccordoba12** [comment]
How did you install Spyder and IPython?

**Comment by tjhendrickson** [comment]
I installed it through Python(x,y).

**Comment by ccordoba12** [comment]
Then please report this problem with them. I think for Python(x,y) you need to uninstall your current version and install its latest one.

Sorry for not being of more help, but this is clearly an installation problem instead of a Spyder one.
