### ISSUE TITLE
Align boxes for different lines in preferences dialog

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2481]
The following image displays the look of the preferences dialog (master). The idea is to use a QGridLayout to align for example, the first three options that include comboboxes.

![image](https://cloud.githubusercontent.com/assets/3627835/8109515/70e78326-1057-11e5-811f-952093682e23.png)

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by Nodd** [comment]
`QFormLayout` is more appropriate, but the difference is subtle: on some platforms the labels are left aligned and on others the label are right aligned, and `QFormLayout` takes care of it.
I know 2 problems with this layout: it is limited to 2 columns, and keeps the margins for hidden widgets, which creates lines of unequal heights. But neither should be a problem here.

**Comment by ccordoba12** [comment]
+1 from me too.

**Comment by goanpeca** [comment]
@Nodd thanks for pointing me to that layout, but I think that it would look weird to have some things alignes to the left and some others to the right. Since many of these options involve several widgets to the right, I will stick to the GridLayout.

Should be a fast fix, it really bugs me how it looks... it looks ugly!!!

**Comment by goanpeca** [comment]
@spyder-ide/core-developers 

So, I thought it was simpler, cause the helpers for comboboxes already create inside the label, so I added a couple of arguments, to pass along the related labels and any intermediate additional space. I could also, potentially pass the options in comboboxes of related comboboxes so that the width of the actual combobox is also uniform (to the maximum content). So far it would look like this... 

![pref](https://cloud.githubusercontent.com/assets/3627835/8170651/957adc8e-13b2-11e5-8b27-3caead99f09b.png)

**Comment by goanpeca** [comment]
Or we could just stretch the comboboxes, so all comboboxes reach the same place.

```python
Qt windows style |                                     |
Icon theme |                                           |
Language |                                             |
```

**Comment by goanpeca** [comment]
I can also make it look something like this....

![image](https://cloud.githubusercontent.com/assets/3627835/8178140/f7fd881c-140b-11e5-92b6-9826debc689c.png)

@Nodd, @SylvainCorlay?

**Comment by Nodd** [comment]
2nd one looks better !

**Comment by SylvainCorlay** [comment]
+1 for the second screenshot.
