### ISSUE TITLE
Configure memory usage

### ISSUE THREAD

**Issue by pburns001** [spyder-ide/spyder#2483]
## Description can't determine how to configure memory spyder can use

* *What steps will reproduce the problem?*
1.
2.
3.

* *What is the expected output? What do you see instead?*

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.1.0 (OK)
zmq >=2.1.11    :  14.6.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
This doesn't have any relevant info. Closing.
