### ISSUE TITLE
{{{ }}} as cell delimiters

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2487]
Enhancement idea: add `# {{{` and `# }}}` as cell delimiters.
These markers are sometimes used in a language agnostic way to mark blocks of code. I encountered it in pyopencl for example.

**Comment by goanpeca** [comment]
@SylvainCorlay ?

**Comment by ccordoba12** [comment]
I don't have a problem with this, but right now separators need to be associated to a specific file type.

Look how this is implemented in the `CELL_LANGUAGES` variable of `utils/sourcecode.py`.

**Comment by goanpeca** [comment]
This will most likely change with the source code refactoring, as each new language will define some class variables (I assume) like.

```python
CELLS_ENABLED = True
CELLS_DELIMITERS = (('{{{', '}}}'), )   
```

**Comment by Nodd** [comment]
you wouldn't need `CELLS_ENABLED`, an empty `CELLS_DELIMITERS` should be fine.

**Comment by goanpeca** [comment]
Sure, something like that :-)  (early brainstorming)

**Comment by SylvainCorlay** [comment]
@Nodd , would you want this to match like parentheses, for nested cells?
```Python
# {{ the big picture cell
   
    # {{ Some detail in a look you may run separately

    # }}
# }} 
```

**Comment by goanpeca** [comment]
@SylvainCorlay I think that would be too much... the cells functionality how it is make enoguh sense to me, but I would like to hear from @Nodd on actual use cases...

**Comment by SylvainCorlay** [comment]
I think that in swift, they match the comments `/*` and `*/` like parentheses.

>Unlike multiline comments in C, multiline comments in Swift can be nested inside other multiline comments. You write nested comments by starting a multiline comment block and then starting a second multiline comment within the first block. The second block is then closed, followed by the first block:
```swift
/* this is the start of the first multiline comment
/* this is the second, nested multiline comment */
this is the end of the first multiline comment */
```
Nested multiline comments enable you to comment out large blocks of code quickly and easily, even if the code already contains multiline comments.

**Comment by Nodd** [comment]
Nested cell has the same problem that was raised in #2384 and we decided against it because it would be too unfamiliar to users.

The use case for `# {{{` is just that it is sometimes used to group blocs of code, which is equivalent to our cells. I've never seen them nested, actually.

**Comment by ccordoba12** [comment]
We don't plan to implement this, sorry.
