### ISSUE TITLE
Spyder crashes when displaying DataFrames with duplicate column names in the Variable Explorer

### ISSUE THREAD

**Issue by muellerth** [spyder-ide/spyder#2491]
Hi,
I have the problem that Spyder crashes when I try do display a Pandas DataFrame in the Spyder variable explorer. The problem only occurs, if there are duplicate columns in the DataFrame. Example:

![2015-06-17 15_50_05-spyder python 2 7](https://cloud.githubusercontent.com/assets/12936726/8208575/9a5a8f86-1508-11e5-962c-fec6a2f8ccfe.png)

Now, double clicking on the variable "new_df" in the variable explorer leads to a crash of Spyder.

My software versions are:

Sypder 2.3.4
Pandas 0.16.2
Iphyton 3.1.0

Best regards

**Comment by ccordoba12** [comment]
A simpler example to test

```python
import pandas as pd
df = pd.DataFrame([[1,2],[3,4],[5,6]], columns=['a','a'])
```
