### ISSUE TITLE
Windows Python 3 installers are not creating Start Menu entries nor desktop shortcut

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2493]
After almost two days of long debugging hours, I just found that this is caused by these Python bugs:

* http://bugs.python.org/issue22103
* http://bugs.python.org/issue21354

So we'll have to wait until a new Python 3 version is released.

Pinging @humitos, who reported this problem to me through Twitter.

**Comment by ccordoba12** [comment]
I'll try to include the patch present in the second bug in Anaconda, so I can fix these installers for our next release.

**Comment by ccordoba12** [comment]
Unfortunately since Spyder 3.0 we won't be able to generate the same kind of Windows installers that we've been releasing so far.

That's because those installers are not able to install other Python packages as dependencies, and Spyder 3.0 already needs several dependencies.

There's still the possibility to generate self-contained Windows installers (see issue #2648), but someone will have to help us with that :-)

**Comment by goanpeca** [comment]
@ccordoba12 I can look into it, do we have an issue to track this, or should we open an issue?

**Comment by ccordoba12** [comment]
See issue #2648 for self-contained installers.

As I said, the simple installers we've providing up to Spyder 2.3 won't be possible for Spyder 3 because they don't pull any dependency.
