### ISSUE TITLE
Crash on opening bracket

### ISSUE THREAD

**Issue by ilevkivskyi** [spyder-ide/spyder#2494]
What steps will reproduce the problem?

1. Edit a script in editor
2. Press open bracket '(' and close bracket ')' keys quickly at a position right after another opening bracket
3. First Spyder freezes for few seconds and then crashes silently, without any error message. This however happens not every time, sometimes it just freezes for 3-4 seconds.

What version of the product are you using? On what operating system?
Spyder 2.3.4
Python 3.4.0 64bits, Qt 4.8.6, PySide 1.2.2
LinuxMint 17.1

**Comment by blink1073** [comment]
@ilevkivskyi, this appears to be working in the latest development version of Spyder.  You can either install from [source](https://pythonhosted.org/spyder/installation.html#installing-or-running-directly-from-source) or wait for the impending 2.3.5 release.

**Comment by ilevkivskyi** [comment]
OK, thank you for good news.
