### ISSUE TITLE
No such file or directory: '/usr/local/lib/python2.7/site-packages/spyderlib/mac_stylesheet.qss'

### ISSUE THREAD

**Issue by elvierde** [spyder-ide/spyder#2497]
After successfully upgrading to spyder-2.3.5 using pip, spyder will not start and complain about the missing file.
Tried with the --reset option: no change.
Current solution: copy the `mac_stylesheet.qss` file from the git repository into the `/usr/local/lib/python2.7/site-packages/spyderlib/ directory`. After copying the file, spyder is fully functional.

OS X Yosemite 10.10.3
python 2.7.10

**Comment by ccordoba12** [comment]
Thanks for reporting. I'll make a new release to fix ASAP.
