### ISSUE TITLE
NotImplementedError: Writing as Excel with a MultiIndex is not yet implemented.

### ISSUE THREAD

**Issue by Owojori** [spyder-ide/spyder#2498]
## Description
I get the following error: when I run the example in the 

 raise NotImplementedError("Writing as Excel with a MultiIndex is "
NotImplementedError: Writing as Excel with a MultiIndex is

* *What steps will reproduce the problem?*
1.temp_df = table.xs(manager, level=0)
   
2.temp_df.to_excel(writer,manager)
3.

* *What is the expected output? What do you see instead?*
I expect to see it create an excel sheet called output with the data I asked t to write.

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
This is not a Spyder error, it seems to be a Pandas one. Please open a new issue here

https://github.com/pydata/pandas/issues
