### ISSUE TITLE
Run command does not execute current script when using unittest

### ISSUE THREAD

**Issue by jalumley** [spyder-ide/spyder#2499]
Consider the two below files using unittest:
## test1.py

``` python
import unittest

def fun(x):
    return x + 1
class MyTest(unittest.TestCase):
    def test(self):
        print "test = test1.py"
        self.assertEqual(fun(3), 4)

if __name__=='__main__':
    unittest.main()
```
## test2.py

``` python
import unittest
# content of test_sample.py
def func(x):
    return x + 1

def test_answer():
    assert func(3) == 6

if __name__=='__main__':
    unittest.main()
```

If I load both files into Spyder then make test1.py the active window, I can execute the test via the 'run' button or f5. This will give the following output:

runfile('C:/Users/YE91224/Desktop/test2.py', wdir='C:/Users/YE91224/Desktop')
.test = test1.py

---

Ran 1 test in 0.000s

OK

In [11]:

If I then switch window and execute the second unittest (script) via pressing the run button or F5 the behaviour is not as expected.  In fact it will still run the old file, not the new active window.  Even if I make changes to the active / open file, then press F5/run the untittest that executes is still the old unittest from the previous script, not the current test.

Spyder Version:  2.3.1
Python Version:  2.7.8
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
IPython >=0.13  :  2.2.0 (OK)
pygments >=1.6  :  1.6 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
matplotlib >=1.0:  1.4.0 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
There's now a plugin to run tests in Spyder. Hopefully it fixes this problem.
