### ISSUE TITLE
matplotlib gives import error after update.

### ISSUE THREAD

**Issue by ForeverTangent** [spyder-ide/spyder#2500]
## Description

* *What steps will reproduce the problem?*
1.  Update Anaconda
2.  Load Python/Spyder script using mathplotlib
3.  Run Script

* *What is the expected output? What do you see instead?*
Expected:
Mathplotlib to load and run without issue.

Actual:
Get the following:

  File "//anaconda/lib/python3.4/site-packages/matplotlib/mathtext.py", line 63, in <module>
    import matplotlib._png as _png

ImportError: dlopen(//anaconda/lib/python3.4/site-packages/matplotlib/_png.so, 2): Library not loaded: @loader_path/../../../libpng15.15.dylib
  Referenced from: //anaconda/lib/python3.4/site-packages/matplotlib/_png.so
  Reason: image not found

* *Please provide any additional information below*

It was fine before I ran the update today, now it is not.

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  3.4.3
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies

pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by Nodd** [comment]
You have to update libpng and/or matplotlib in anaconda.
(Btw this is not a spyder problem at all).

**Comment by goanpeca** [comment]
Then we should close it @Nodd (dont be shy ;-) )

**Comment by Nodd** [comment]
Yeah, but I always find that "not my problem, closing" is a bit harsh to newcomers. I'm too kind for my own good !

**Comment by goanpeca** [comment]
Hahaha, fine!

**Comment by Nodd** [comment]
I reported it to anaconda, now I can close it. @ForeverTangent if you still have any problem with this please use the link above.
