### ISSUE TITLE
decoding Unicode is not supported'

### ISSUE THREAD

**Issue by Temmplar** [spyder-ide/spyder#2503]
return self.dispatch_line(frame)
  File "/home/george/anaconda/lib/python2.7/bdb.py", line 67, in dispatch_line
    self.user_line(frame)
  File "/home/george/anaconda/lib/python2.7/pdb.py", line 158, in user_line
    self.interaction(frame, None)
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 492, in interaction
    self.notify_spyder(frame) #-----Spyder-specific-------------------------
  File "/home/george/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 432, in notify_spyder
    fname = unicode(fname, "utf-8")
TypeError: ('Bad input argument to theano function with name "/home/george/anaconda/lib/python2.7/site-packages/nolearn/lasagne/base.py:264"  at index 1(0-based)', 'decoding Unicode is not supported')

Original code:

    def notify_spyder(self, frame):
        if not frame:
            return
        fname = self.canonic(frame.f_code.co_filename)
        if sys.version[0] == '2':
            fname = unicode(fname, "utf-8")
            try:
                fname = unicode(fname, "utf-8")
            except TypeError:
                pass
        lineno = frame.f_lineno
        if isinstance(fname, basestring) and isinstance(lineno, int):
            if osp.isfile(fname) and monitor is not None:
                monitor.notify_pdb_step(fname, lineno)

Made modification:

    def notify_spyder(self, frame):
        if not frame:
            return
        filename = self.canonic(frame.f_code.co_filename)
        if sys.version[0] == '2':
            try:
                filename = unicode(filename, "utf-8")
            except TypeError:
                pass
        lineno = frame.f_lineno
        if isinstance(filename, basestring) and isinstance(lineno, int):
            if osp.isfile(filename) and monitor is not None:
                monitor.notify_pdb_step(filename, lineno)

Please confirm, if it's OK, anyway it worked fine after this.

**Comment by ccordoba12** [comment]
What's your Spyder version?

**Comment by ccordoba12** [comment]
I think this was fixed in **2.3.5.2**. Could you update and confirm?

**Comment by Temmplar** [comment]
2.3.4. O.K. I will update then, and inform you if I found this issue again. Thank you for your help.

**Comment by ccordoba12** [comment]
I'm sure this was fixed in 2.3.5.2. Closing :-)
