### ISSUE TITLE
mac 10.8.5 crash when start spyder

### ISSUE THREAD

**Issue by choupachupss** [spyder-ide/spyder#2505]
Hi,

With dmg 2.3.5.2 for py2.7
Try 
- launch with spyder.app
- ```spyder --reset``` and remove folder ```.spyder2```

I have a crash.

With terminal way, i have that return :
```Illegal instruction: 4```

Sound like a compilation problem.

Best regards.

**Comment by ccordoba12** [comment]
Sorry, but we stopped supporting versions less than Mac 10.9 in our app. That's the cause of your problem.

All Python scientific packages (or wheels) are compiled in Mavericks, and that makes our job of creating the app far more easier than what it was before. So we had to move on to only support Mavericks or Yosemite.

I added a note about it in our installations docs:

http://pythonhosted.org/spyder/installation.html#the-easy-way

**Comment by choupachupss** [comment]
ok.

I need compile your app with 10.8.5 with 2.5.2 for have the fix of this issue [#2157](https://github.com/spyder-ide/spyder/issues/2157).

This issue was not fix in 2.3.4.

How can i do that ?

**Comment by ccordoba12** [comment]
I really don't understand what's causing issue #2157 on Mac, so it's probably not solved on 2.3.5.2 (if it continues to appear).

The instructions to create the app are here: https://github.com/spyder-ide/mac-application, but they are tailored to work on Mac 10.9 or higher.

I'm sorry to say that If you want to create the app in Mac 10.8, you're on your own. I don't have time to help you with that :-)

**Comment by choupachupss** [comment]
It's mysterious, yes.

Just :
hombrew install
python2.7.9 
ipython3 with all dependency
all spyder depency

Download
Spyder dmg app

And just link ipython, python and python site packages
for replace python and ipython in spyder 
create that issue.

So even i upgrade my mac to 10.9 and try spyder 2.5.2, i will have the same issue ?
So even i succes create mac app to 10.8.5 and try spyder 2.5.2, i will have the same issue ?

How can i install some pip lib depency (cf opencv, request ....) and run/debug with spyder ?
