### ISSUE TITLE
disappearance of pylab

### ISSUE THREAD

**Issue by stevenokimbrough** [spyder-ide/spyder#2506]
## Description

**What steps will reproduce the problem?**

1. import matplotlib.pylab
2. 
3. 

**What is the expected output? What do you see instead?**
I expect the import will work and make the module available. In Spyder I get:
import matplotlib.pylab
Traceback (most recent call last):

  File "<ipython-input-2-1d30b9aee20b>", line 1, in <module>
    import matplotlib.pylab

  File "/Applications/anaconda/lib/python3.4/site-packages/matplotlib/pylab.py", line 231, in <module>
    import matplotlib.finance

  File "/Applications/anaconda/lib/python3.4/site-packages/matplotlib/finance.py", line 38, in <module>
    from matplotlib.collections import LineCollection, PolyCollection

  File "/Applications/anaconda/lib/python3.4/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases

  File "/Applications/anaconda/lib/python3.4/site-packages/matplotlib/backend_bases.py", line 56, in <module>
    import matplotlib.textpath as textpath

  File "/Applications/anaconda/lib/python3.4/site-packages/matplotlib/textpath.py", line 22, in <module>
    from matplotlib.mathtext import MathTextParser

  File "/Applications/anaconda/lib/python3.4/site-packages/matplotlib/mathtext.py", line 63, in <module>
    import matplotlib._png as _png

ImportError: dlopen(/Applications/anaconda/lib/python3.4/site-packages/matplotlib/_png.so, 2): Library not loaded: @loader_path/../../../libpng15.15.dylib
  Referenced from: /Applications/anaconda/lib/python3.4/site-packages/matplotlib/_png.so
  Reason: image not found

In qtconsole I get:

import matplotlib.pylab
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-1d30b9aee20b> in <module>()
----> 1 import matplotlib.pylab

/Applications/anaconda/lib/python3.4/site-packages/matplotlib/pylab.py in <module>()
    229 # make mpl.finance module available for backwards compatability, in case folks
    230 # using pylab interface depended on not having to import it
--> 231 import matplotlib.finance
    232 
    233 from matplotlib.dates import date2num, num2date,
/Applications/anaconda/lib/python3.4/site-packages/matplotlib/finance.py in <module>()
     36 from matplotlib.dates import date2num
     37 from matplotlib.cbook import iterable, mkdirs
---> 38 from matplotlib.collections import LineCollection, PolyCollection
     39 from matplotlib.colors import colorConverter
     40 from matplotlib.lines import Line2D, TICKLEFT, TICKRIGHT

/Applications/anaconda/lib/python3.4/site-packages/matplotlib/collections.py in <module>()
     25 import matplotlib.artist as artist
     26 from matplotlib.artist import allow_rasterization
---> 27 import matplotlib.backend_bases as backend_bases
     28 import matplotlib.path as mpath
     29 from matplotlib import _path

/Applications/anaconda/lib/python3.4/site-packages/matplotlib/backend_bases.py in <module>()
     54 
     55 import matplotlib.tight_bbox as tight_bbox
---> 56 import matplotlib.textpath as textpath
     57 from matplotlib.path import Path
     58 from matplotlib.cbook import mplDeprecation

/Applications/anaconda/lib/python3.4/site-packages/matplotlib/textpath.py in <module>()
     20 from matplotlib.ft2font import FT2Font, KERNING_DEFAULT, LOAD_NO_HINTING
     21 from matplotlib.ft2font import LOAD_TARGET_LIGHT
---> 22 from matplotlib.mathtext import MathTextParser
     23 import matplotlib.dviread as dviread
     24 from matplotlib.font_manager import FontProperties

/Applications/anaconda/lib/python3.4/site-packages/matplotlib/mathtext.py in <module>()
     61 
     62 import matplotlib.colors as mcolors
---> 63 import matplotlib._png as _png
     64 ####################
     65 

ImportError: dlopen(/Applications/anaconda/lib/python3.4/site-packages/matplotlib/_png.so, 2): Library not loaded: @loader_path/../../../libpng15.15.dylib
  Referenced from: /Applications/anaconda/lib/python3.4/site-packages/matplotlib/_png.so
  Reason: image not found

**Please provide any additional information below**
This happened before. I reinstalled/updated Anaconda and then things were fine, for awhile.
Awfully weird. Help!!!

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
This is not a Spyder problem. To fix it you need to run

    conda update qt
    conda update matplotlib

**Comment by stevenokimbrough** [comment]
Thanks! It worked.

Do I need to run conda update routinely?

On Sun, Jun 28, 2015 at 10:52 AM, Carlos Cordoba <notifications@github.com>
wrote:

> This is not a Spyder problem. To fix it you need to run
>
> conda update qt
> conda update matplotlib
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2506#issuecomment-116288451>.
>



-- 
Steven O. Kimbrough, Professor
University of Pennsylvania
The Wharton School
565 Jon M. Huntsman Hall
3730 Walnut Street
Philadelphia, PA  19104-6340 USA
Tel: 215-898-5133
Fax: 215-898-3664
Home page at Wharton:
  Official page: https://opimweb.wharton.upenn.edu/profile/36/
  Unofficial page:  http://opim.wharton.upenn.edu/~sok/
Email: kimbrough@wharton.upenn.edu

**Comment by ccordoba12** [comment]
Well, conda update doesn't update all packages. The problem you reported 
was generated because Continuum updated a core library (libpng) that 
affected several other important ones (like qt). But it's quite uncommon 
for these problems to appear on Anaconda.

**Comment by stevenokimbrough** [comment]
Again, thanks so much. Very helpful.

On Sun, Jun 28, 2015 at 1:52 PM, Carlos Cordoba <notifications@github.com>
wrote:

> Well, conda update doesn't update all packages. The problem you reported
> was generated because Continuum updated a core library (libpng) that
> affected several other important ones (like qt). But it's quite uncommon
> for these problems to appear on Anaconda.
>
> El 28/06/15 a las 10:12, stevenokimbrough escribió:
> > Thanks! It worked.
> >
> > Do I need to run conda update routinely?
> >
> > On Sun, Jun 28, 2015 at 10:52 AM, Carlos Cordoba
> > <notifications@github.com>
> > wrote:
> >
> > > This is not a Spyder problem. To fix it you need to run
> > >
> > > conda update qt
> > > conda update matplotlib
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <https://github.com/spyder-ide/spyder/issues/2506#issuecomment-116288451
> >.
> > >
> >
> >
> >
> > --
> > Steven O. Kimbrough, Professor
> > University of Pennsylvania
> > The Wharton School
> > 565 Jon M. Huntsman Hall
> > 3730 Walnut Street
> > Philadelphia, PA 19104-6340 USA
> > Tel: 215-898-5133
> > Fax: 215-898-3664
> > Home page at Wharton:
> > Official page: https://opimweb.wharton.upenn.edu/profile/36/
> > Unofficial page: http://opim.wharton.upenn.edu/~sok/
> > Email: kimbrough@wharton.upenn.edu
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/spyder-ide/spyder/issues/2506#issuecomment-116289420
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2506#issuecomment-116303732>.
>



-- 
Steven O. Kimbrough, Professor
University of Pennsylvania
The Wharton School
565 Jon M. Huntsman Hall
3730 Walnut Street
Philadelphia, PA  19104-6340 USA
Tel: 215-898-5133
Fax: 215-898-3664
Home page at Wharton:
  Official page: https://opimweb.wharton.upenn.edu/profile/36/
  Unofficial page:  http://opim.wharton.upenn.edu/~sok/
Email: kimbrough@wharton.upenn.edu
