### ISSUE TITLE
"Go to definition" not working

### ISSUE THREAD

**Issue by shendric** [spyder-ide/spyder#2509]
Using "go to definition" in right-click menu does not jump to the selected code though it is resolved. It neither works for a class/function in the same or an external file. 

This issue occurs for me in version 2.5.3.2, previous installation 2.3.4 does not have this problem. 

My system: 
Windows 7 64bit
Python 2.7 64bit (WinPython 2.7.9.1)
Python 2.5.3.2 manually installed with Windows executable.

**Comment by blink1073** [comment]
Hi @shendric, would you mind selecting `Help -> Optional dependencies...`, then click `Copy to clipboard` and post here?

**Comment by shendric** [comment]
IPython >=1.0   :  2.3.1 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.2 (OK)
pandas >=0.13.1 :  0.16.1 (OK)
pep8 >=0.6      :  1.5.7 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pygments >=1.6  :  2.0.1 (OK)
pylint >=0.25   :  1.4.0 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
zmq >=2.1.11    :  14.4.1 (OK)

**Comment by blink1073** [comment]
Hmm, I can't reproduce, but I'm OSX.

**Comment by shendric** [comment]
For me it was also an issue in 2.3.3, but 2.3.4 fixed it.

**Comment by shendric** [comment]
I also installed jedi 0.9 (which was missing) but no change for the "go to definition".

**Comment by ccordoba12** [comment]
@shendric, so what you're saying is that this is a regression in **2.3.5.2** against **2.3.4**?

**Comment by shendric** [comment]
@ccordoba12, yes it is a regression

**Comment by ccordoba12** [comment]
I can't reproduce this problem with Anaconda on Windows, so maybe this is a problem with your installation or with WinPython.

**Comment by ajholyoake** [comment]
@shendric did you ever manage to get this working? I have just upgraded to 2.3.6 from 2.3.2, and Go to definition does not work for me in any circumstance?

Are there spyder debugging guidelines to workout where the call is failing?

**Comment by ccordoba12** [comment]
@ajholyoake, since you're also using WinPython, please report this problem here:

https://github.com/winpython/winpython

**Comment by ajholyoake** [comment]
Cheers, Carlos.

**Comment by ajholyoake** [comment]
Just for reference - I solved this by deleting spyderlib and spyderplugins in the site-packages directory and re-installed from pip.

**Comment by shendric** [comment]
@ajholyoake I have now installed spyderlib 2.3.7 with Jedi 0.8.1 and it is working properly

**Comment by debvrat** [comment]
Hi,

I get the same issue. 
I have Spyder 4.0.1 on Anaconda 4.8.2 with Python 3.7.4. 
I use Windows 10.

Ctrl+G does not work for me, neither does clicking on the 'Go to Definition' option. 
I have to restart Spyder sometimes to make it work (magically).

Note that my default Spyder version with Anaconda was some 3.x. 
I updated Spyder using the Navigator's UI, as explained [here](https://stackoverflow.com/a/51880798).
