### ISSUE TITLE
Pandas Panel(s) are not supported in the Variable Explorer

### ISSUE THREAD

**Issue by scls19fr** [spyder-ide/spyder#2510]
Hello,

try in IPython inside Spyder

```
>>> #from pandas.io import data, wb
>>> from pandas_datareader import data, wb # pip install pandas_datareader
>>> panel = data.DataReader(['MSFT', 'GOOG', 'AAPL'], 'yahoo')
>>> panel
```

This panel doesn't appears in variables explorer.

```
>>> df_adj_close = panel['Adj Close']
```

`df_adj_close` appears in variables explorer.

Kind regards

**Comment by ccordoba12** [comment]
We don't have support for panels, just DataFrames and Series.

@dhoegh, how hard would it be to add support for them? Could you help us with that?

**Comment by dhoegh** [comment]
I haven't worked worked with panels, so I don't know. I do not have time for looking into the issue. By looking in the documentation panel is described as a three dimensional container, see:http://pandas.pydata.org/pandas-docs/stable/dsintro.html. This means it is not straight forward and some inspiration from the three dimensional array viewer could probably be used.

**Comment by scls19fr** [comment]
Maybe you should consider to display "slice" of Panel (ie DataFrame)

    panel.loc[:, :, "MSFT"]

    panel.loc["Adj Close", :, :]

    panel.loc[:, "2015-07-01", :]

see http://pandas.pydata.org/pandas-docs/stable/indexing.html

    panel.loc[item_indexer,major_indexer,minor_indexer]

Ideally panel editor should provide a way to define if slice are given as item, major_index or minor_index

**Comment by dhoegh** [comment]
This is exactly how the 3d array viewer works does a slice always produced a dataframe?

**Comment by scls19fr** [comment]
I think so but maybe @jreback or @wesm can confirm or infirm this.

**Comment by jreback** [comment]
``Panels`` can be easily converted to multi-index frames. This is a flattened version of a ``Panel``.

```
In [8]: pd.set_option('max_rows',10)

In [9]: panel.to_frame()
Out[9]: 
                        Open        High         Low       Close     Volume   Adj Close
Date       minor                                                                       
2010-01-04 AAPL   213.429998  214.500023  212.380001  214.010025  123432400   28.718094
           MSFT    30.620001   31.100000   30.590000   30.950001   38409100   26.769336
2010-01-05 AAPL   214.599985  215.589994  213.250034  214.379967  150476200   28.767737
           MSFT    30.850000   31.100000   30.639999   30.959999   49749600   26.777984
2010-01-06 AAPL   214.379967  215.229986  210.749977  210.969995  138040000   28.310151
...                      ...         ...         ...         ...        ...         ...
2015-06-30 GOOG   526.020020  526.250000  520.500000  520.510010    2217200  520.510010
           MSFT    44.709999   44.720001   43.939999   44.150002   35214100   44.150002
2015-07-01 AAPL   126.900002  126.940002  125.989998  126.599998   30128600  126.599998
           GOOG   524.729980  525.690002  518.229980  521.840027    1961000  521.840027
           MSFT    44.459999   45.230000   44.099998   44.450001   28337200   44.450001

[3085 rows x 6 columns]
```

If you want to slice, then ``Panel``s follow the same semantics, e.g. if you specifiy for an indexer a scalar value then you would get a ``DataFrame``

e.g.

```
In [11]: panel.iloc[0]
Out[11]: 
                  AAPL        GOOG       MSFT
Date                                         
2010-01-04  213.429998         NaN  30.620001
2010-01-05  214.599985         NaN  30.850000
2010-01-06  214.379967         NaN  30.879999
2010-01-07  211.750000         NaN  30.629999
2010-01-08  210.300020         NaN  30.280001
...                ...         ...        ...
2015-06-25  128.860001  538.869995  46.029999
2015-06-26  127.669998  537.260010  45.650002
2015-06-29  125.459999  525.010010  45.040001
2015-06-30  125.570000  526.020020  44.709999
2015-07-01  126.900002  524.729980  44.459999

[1383 rows x 3 columns]

In [12]: panel.iloc[:,0]
Out[12]: 
            Open        High         Low       Close     Volume  Adj Close
AAPL  213.429998  214.500023  212.380001  214.010025  123432400  28.718094
GOOG         NaN         NaN         NaN         NaN        NaN        NaN
MSFT   30.620001   31.100000   30.590000   30.950001   38409100  26.769336

In [13]: panel.iloc[:,:,0]
Out[13]: 
                  Open        High         Low       Close     Volume   Adj Close
Date                                                                             
2010-01-04  213.429998  214.500023  212.380001  214.010025  123432400   28.718094
2010-01-05  214.599985  215.589994  213.250034  214.379967  150476200   28.767737
2010-01-06  214.379967  215.229986  210.749977  210.969995  138040000   28.310151
2010-01-07  211.750000  211.999966  209.050032  210.580027  119282800   28.257821
2010-01-08  210.300020  211.999966  209.059965  211.980019  111902700   28.445687
...                ...         ...         ...         ...        ...         ...
2015-06-25  128.860001  129.199997  127.500000  127.500000   31816700  127.500000
2015-06-26  127.669998  127.989998  126.510002  126.750000   42111000  126.750000
2015-06-29  125.459999  126.470001  124.480003  124.529999   48911400  124.529999
2015-06-30  125.570000  126.120003  124.860001  125.430000   43849800  125.430000
2015-07-01  126.900002  126.940002  125.989998  126.599998   30128600  126.599998

[1383 rows x 6 columns]
```

multi-indexers / lists will produce a shape based on what you are sub-selecting, e.g.

```
In [14]: panel.iloc[0,0]
Out[14]: 
AAPL    213.429998
GOOG           NaN
MSFT     30.620001
Name: 2010-01-04 00:00:00, dtype: float64

In [15]: panel.iloc[0,0,0]
Out[15]: 213.42999800000001

In [16]: panel.iloc[[0,1],0,0]
Out[16]: 
Open    213.429998
High    214.500023
Name: AAPL, dtype: float64

```

note that these are all consistent with numpy slicing semantics

**Comment by scls19fr** [comment]
Just some code to create a sample Panel without relying on `pandas_datareader`

    items = ['Open', 'High', 'Low', 'Close']
    minor_axis = ['AAAA', 'BBBB', 'CCCC']
    periods = 5
    panel = pd.Panel(np.random.random((len(items), periods, len(minor_axis))), items=items,
        major_axis=pd.date_range('1/1/2000', periods=periods),
        minor_axis=minor_axis)

Panel4D can be construct using

    labels = ['Label1','Label2']
    items = ['Item1', 'Item2']
    periods = 5
    minor_axis = ['A', 'B', 'C', 'D']
    p4d = pd.Panel4D(np.random.random((len(labels), len(items), periods, len(minor_axis))),
               labels=labels,
               items=items,
               major_axis=date_range('1/1/2000', periods=periods),
               minor_axis=minor_axis)

but I don't think that Spyder variables editor support hyper-cubes (Numpy arrays with more than 3 dimensions)

    a = np.random.random((2,3,4,5))

**Comment by Prikers** [comment]
As `panels `are being [deprecated ](http://pandas.pydata.org/pandas-docs/version/0.20/whatsnew.html#deprecate-panel) from `pandas`, is it worth adding support for them now? Maybe this issue could be closed.

**Comment by ccordoba12** [comment]
We could consider to support `xarray`'s then. What do you say @Prikers?

**Comment by Prikers** [comment]
Yes that would make sense! 
I can give it a try next week. Should I open a new issue for `xarray` support or we use this one as a reference?

**Comment by goanpeca** [comment]
@Prikers awesome, I think its better to open a new issue :-), you can also tag this issue for reference on that new issue.
