### ISSUE TITLE
Index column of Pandas DataFrame should be visible all the time

### ISSUE THREAD

**Issue by scls19fr** [spyder-ide/spyder#2512]
Hello,

Index of Pandas DataFrame should be in a frozen pane in variable explorer

![capture d ecran 2015-07-02 a 22 36 20](https://cloud.githubusercontent.com/assets/109167/8487256/20e02cec-210b-11e5-853e-b1cc924f66de.png)
![capture d ecran 2015-07-02 a 22 36 30](https://cloud.githubusercontent.com/assets/109167/8487259/226be470-210b-11e5-8ad5-8cedc575288a.png)

Kind regards

**Comment by ccordoba12** [comment]
I can take a look at this one. Don't know if it's possible in Qt though :-)

**Comment by bilderbuchi** [comment]
also, why are the columns so unnecessarily wide? seems to waste an awful lot of space :-/

**Comment by ccordoba12** [comment]
@andfoy, please work on this one. The idea is to make the first column of our DataFrame viewer fixed when people scroll to left and right.

The file you need to work on is `spyder/widgets/variableexplorer/dataframeeditor.py`.

And here you can find how to do it in Qt:

http://doc.qt.io/qt-5/qtwidgets-itemviews-frozencolumn-example.html

**Comment by scls19fr** [comment]
Thanks

**Comment by ccordoba12** [comment]
You're welcome! Thanks a lot for this great suggestion :-)
