### ISSUE TITLE
DataFrames with headers that contain BOM utf-8 data are freezing/crashing Spyder (in Python 2)

### ISSUE THREAD

**Issue by kapoost** [spyder-ide/spyder#2514]
I've found that reason of Variable explorer crashes might be BOM gibberish (for example: '\xef\xbb\xbf') that appears at beginning of first column name. It is invisible for df.columns but appears when I call df.columns[0]. For some reason pd.read_csv() doesn't strip this.

**Workaround is always check name using df.columns[0] & changing it before using Variable explorer**

**Comment by ccordoba12** [comment]
@kapoost, thanks for creating this issue. On question: what do you mean exactly by

> changing it before using Variable explorer

How do we need to change it?

**Comment by kapoost** [comment]
As I've mentioned - it is only workaround so basically I'm doing it like this:
```python
in: a = pd.read_csv('/Users/kapoost/Downloads/Datausage-9.csv') #this csv starts with BOM
in: a.columns #would not show any problem but...
out: Index([u'﻿Agency', u'Advertiser', u'Country', u'SegmentsGroup', u'Impressions', u'Revenue', u'Leads', u'Clicks'], dtype='object')
in: a.columns[0] #this will show the source of our crashes
out: '\xef\xbb\xbfAgency'
in: a.columns = ['Agency', 'Advertiser', 'Country', 'SegmentsGroup', 'Impressions', 'Revenue', 'Leads', 'Clicks'] #manual overwrite names of columns will erase BOM element. This DataFrame would not cause problem with Variable explorer :)
```
this gives me DataFrame without faulty name of first column so  Spyder don't crashes when I'm opening Variable explorer and browsing data in visual mode :)

I think that simplest solution would be correcting read_csv() But I've found that it is old unresolved issue: https://github.com/pydata/pandas/issues/4793

**Comment by ccordoba12** [comment]
@kapoost, I'm using the file mentioned in this comment: https://github.com/pydata/pandas/issues/4793#issuecomment-25310750 to test this problem. I can reproduce it in Python 2 but not in Python 3 (in case you're interested).

I think I know how to fix it :-)
