### ISSUE TITLE
Code analysis underlines all matches of "unused local variable"

### ISSUE THREAD

**Issue by Garrett-R** [spyder-ide/spyder#2520]
In the code below the editor correctly underlines `result` since it's assigned to, but never used.  It incorrectly underlines part of `get_result()`.

![wrong_underlining](https://cloud.githubusercontent.com/assets/6614695/8517235/872b1ca4-2373-11e5-9448-50f4d450174f.png)

**Comment by goanpeca** [comment]
Hi @Garrett-R, thanks for reporting this, indeed a small visual bug, we need to improve(or implement?) the regex.

Cheers

**Comment by ccordoba12** [comment]
I think `pyflakes` (the library we use to provide this functionality) is not able to tell what's the unassigned variable in lines like the one you provided.

We'll have to see if that has changed in later versions, or use a replacement for it :-)

**Comment by luihp** [comment]
This is still present in 3.3.4

**Comment by ccordoba12** [comment]
This is not an issue anymore in our master branch. So the fix will be present in Spyder 4, to be released later in 2019.
