### ISSUE TITLE
python3.4 console dies after first command

### ISSUE THREAD

**Issue by DSLituiev** [spyder-ide/spyder#2525]
installed latest dev version. [ debugging is hardly possible with `ipython`](https://github.com/spyder-ide/spyder/issues/2395). and unfortunately the plain python console dies after first command, e.g. 

    print('hello')

**Comment by DSLituiev** [comment]
the same with the `python2.7.6`
installed with `pip3`

**Comment by ccordoba12** [comment]
What operating system are you using?

**Comment by ccordoba12** [comment]
Closing because this is a duplicate of issue #2308.
