### ISSUE TITLE
Spyder 2.3.5.2 crashes on OS X 10.10.4

### ISSUE THREAD

**Issue by kvico** [spyder-ide/spyder#2529]
Spyder 2.3.4 without problems on OS X 10.10.4. But Spyder 2.3.5.2 crashes, see crash log 
https://gist.github.com/9adaafa42060db42f268

Any idea to prevent this?

**Comment by ccordoba12** [comment]
Please post your dump in a gist so it can be easily readable

**Comment by kvico** [comment]
Gist with Spyder 2.3.5.2 crash log https://gist.github.com/9adaafa42060db42f268.git

**Comment by kvico** [comment]
Added gist link to my initial comment.

**Comment by durack1** [comment]
@ccordoba12 @kvico I've just tested `spyder 2.3.5.2` on `OS X 10.10.4` and everything works fine for me..

**Comment by ccordoba12** [comment]
@durack1, are you using the app that comes with our dmg installer? Because that's the problem here :-)

**Comment by durack1** [comment]
@ccordoba12, yep that's exactly what I'm using..

**Comment by ccordoba12** [comment]
@durack1, good to know!

@kvico, I don't see anything relevant in your gist, sorry. It seems to be a threading issue with sip, but I haven't seen this error before :-(

**Comment by durack1** [comment]
@kvico is this still an issue with `Spyder 2.3.7`? If not I suggest it's closed..

**Comment by ccordoba12** [comment]
I tested our dmg's in 10.10.5 and they're working fine :-)

**Comment by durack1** [comment]
@ccordoba12 I can also confirm `2.3.7` works on a bunch of my independent `OS X 10.10.5` installs..

**Comment by ccordoba12** [comment]
Great! Thanks for the confirmation :-)
