### ISSUE TITLE
Must press Enter multiple times for interpreter to execute command

### ISSUE THREAD

**Issue by kyleellefsen** [spyder-ide/spyder#2534]
This bug exists in spyder 2.3.5.2 and in spyder 3.0.0.dev0, which I installed from the github source code today.  I'm running Python 3 (the bug is not as bad in python 2, but still exists) and Windows 7.  If I run the following code in a new python interpreter inside Spyder by highlighting the code and pressing F9, I have to press Enter multiple times for a plot to be displayed.

```python
# Part 1
import sys
from PyQt4.QtGui import QApplication
app = QApplication(sys.argv)

#Part 2
import pylab
import numpy as np
a=[i for i in np.arange(10000000)]  #this slows down code execution
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)
pylab.grid()
pylab.plot(x, y)
```

However, if I only run Part 2 of the code, a plot is displayed.  Something about being inside PyQt4s event loop prevents all the code from being run.

**Comment by ccordoba12** [comment]
We are aware of this bug, it's a duplicate of issue #1831, so I'm closing this one

I've spent at least 40 hours trying to fix it, but it's very, very tricky to do it. For now, please use the IPython console, which doesn't have this problem

**Comment by kyleellefsen** [comment]
I can't use the IPython console because I need to run the 

```python
sys.exit(app.exec_())
```
command to allow my PyQt4 GUI event loop to run while leaving the interpreter open.  The command doesn't freeze my interpreter in the regular python console inside Spyder.  When I run a PyQt4 app in ipython outside of spyder, it runs the PyQt4 event loop fine without that line.  It's only inside Spyder, inside ipython where I need that line, and it freezes my interpreter.

**Comment by kyleellefsen** [comment]
I figured out a fix to the frozen interpreter.  In Spyder, if you go to Tools->Preferences->IPython console->Graphics->Graphics backend->backend and change from 'Inline' to 'Automatic', the console no longer tries to display Qt apps inline and everything works perfectly.  

I wish I had known this years ago...

**Comment by ccordoba12** [comment]
Great!! we're going to change this setting for our next version :-)
