### ISSUE TITLE
Unable to open traceback links in the editor

### ISSUE THREAD

**Issue by JimHokanson** [spyder-ide/spyder#2535]
I'm using Spyder 2.3.4, Python 3.4.3 64 bit

When I run a file and get an error some files are printed in the traceback as File "..\path\to\file.py"

The first one is usually the full path and subsequent files have this abbreviation (the '..').

Clicking on the abbreviated file paths does not open the editor to the file from which that error was thrown.

**Comment by ccordoba12** [comment]
Please give us a reproducible example that we can use to test and solve this problem in our side.

**Comment by JimHokanson** [comment]
It turns out that this problem comes from adding relative paths to the Python path.

We frequently have the following directory structure:
```
/root_folder
   /examples
   /my_package
```

In the examples we have scripts that do:
   ```python
   import sys
   sys.path.append('..')

   import my_package

   if __name__ == '__main__':
       #call the package code
   ```

Although I've had discussions with others as to whether or not this is the best practice ...
Regardless, it seems like the issue could be solved by calling os.path.abspath on the file link (I think ...)

The actual code to reproduce this unfortunately involves some directory structure and I'm not sure how to best share that type of code. I've shared a zip of this code at:
https://drive.google.com/file/d/0B7to9gBdZEyGck96Uk5CU3J2d1k/view?usp=sharing
Alternatively, the code to cause this type of error is relatively trivial ...

```python
#file_to_run.py
import sys, os
sys.path.append('..')
#sys.path.append(r"C:\D\repos\python\spyder_error")
#print(os.path.abspath('..'))

import my_package.file_with_error as f

if __name__ == '__main__':
    f.cause_error()

#/my_package/file_with_error.py
def cause_error():
    a = 1
    value = a() #first error that came to mind :)
```
    

Running "file_to_run.py" throws the following error:
```
Traceback (most recent call last):
  File "C:\D\repos\python\spyder_error\examples\file_to_run.py", line 15, in <module>
    f.cause_error()
  File "..\my_package\file_with_error.py", line 8, in cause_error
    value = a() 
TypeError: 'int' object is not callable
```

Clicking on the second link does not open file_with_error.py as I would like.

**Comment by Nodd** [comment]
`1/0` is an easier error to use for testing :smile:

**Comment by ccordoba12** [comment]
Old bug, hopefully is fixed now.
