### ISSUE TITLE
Behaviour of load_matlab (scipy.utils.iofuncs) differs between windows and linux versions

### ISSUE THREAD

**Issue by smbergman** [spyder-ide/spyder#2541]
Hi. I reported this issue using the built-in functionality in Spyder (Help -> Report Issue) and was eventually told to report it again here.

I have encountered an inconsistency between the Windows and Ubuntu Linux versions of Spyder2 in the implementation of the load_matlab function inside spyderlib.utils.iofuncs module.

Spyder Version:  2.3.0
Python Version:  3.4.0
Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Linux
pyflakes >=0.6.0:  0.8.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.2.1 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  1.2.1 (OK)
rope >=0.9.2    :  None (NOK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  None (NOK)
pylint >=0.25   :  1.1.0 (OK)

What steps will reproduce the problem?
1. Create a matlab *.mat  file containing a structure within a structure using commands IN MATLAB
```
dataset = {}
dataset.temperature = {}
dataset.temperature.info = 'Some temperature timeseries'
dataset.temperature.data = [13,14,13.8,13.3]
dataset.pressure = {}
dataset.pressure.info = 'A pressure timeseries'
dataset.pressure.data = [998,999,1000,999]
save('sample_dataset.mat','dataset')
```

2. Run the following lines of code in Spyder2 (windows and linux)

```
from spyderlib.utils.iofuncs import load_matlab

infile = 'sample_dataset.mat'

xx = load_matlab(infile)
# Print the info
print(xx[0]['dataset']['temperature']['info'])
print(xx[0]['dataset']['temperature']['data'][0,0])
```
3. Result is that it works in Windows, but it does not work in linux

What is the expected output? What do you see instead?
I expected to see the same kind of response at the console as what I saw in Windows. Instead, it shows me:
     TypeError: tuple indices must be integers, not str

Please provide any additional information below.
I think this bug has something to do with the way the loaded file is indexed. If I did the following:
```
print(xx[0]['dataset'][0]['info'])
print(xx[0]['dataset'][0]['data'])
```
Then I can see the information I have put under the 'temperature' structure in the matlab file. So it looks like the information is just not stored under a key called 'temperature'.

**Comment by ccordoba12** [comment]
@blink1073, can you take a look at this one?

**Comment by blink1073** [comment]
I tried it with Octave 3.2 on Ubuntu 12.04, and it works as expected.  We're never going to get mat files 100% right.

**Comment by ccordoba12** [comment]
@smbergman, please update Spyder and Octave to have this right :-)

@blink1073, did you use `master` or `2.3`?
