### ISSUE TITLE
Incorrect link embedded in the "Report Bug" feature

### ISSUE THREAD

**Issue by smbergman** [spyder-ide/spyder#2542]
Hello,

In Spyder2, if you use the Help -> Report a Bug feature, you are still taken to the code.google.com...... website.

Should it not be Reporting the bug directly at
https://github.com/spyder-ide/spyder/issues/new
??

**Comment by bilderbuchi** [comment]
Can't reproduce this, on Spyder 2.3.5.2, that menu item takes me to this issue tracker.

**Comment by ccordoba12** [comment]
@smbergman, please update your Spyder version. This was fixed in 2.3.3 if I recall correctly, so you have to be running an older version.
