### ISSUE TITLE
Problems changing working directory in spyder and ipython

### ISSUE THREAD

**Issue by taylorsansom** [spyder-ide/spyder#2543]
I have some shared libraries (*.so) that were created from old Fortran subroutines using f2py. I would like to import these libraries in either the spyder ide or ipython but I cannot change my working directory. 

I have tried 
>>>%cd /path/to/libraries
>>>os.chdir('/path/to/libraries') 

and manually navigating to the folder and clicking 'Set as current console's working directory. When I type pwd it shows me the correct path but when I %ls it shows me the contents of C:/ which is the global working directory:

In [2] pwd
Out[2]: u'F:\\home\\tsansom\\Projects\\PyTxBLEND\\Subroutines'

In [3] ls
 Volume in drive C is OSDisk
 Volume Serial Number is AEE1-8C46

 Directory of C:
05/19/2015  06:59 AM    <DIR>          {4bb8218c-aebf-4113-882f-b10ae15c8218}
11/04/2014  11:57 AM           729,990 AcroProInstall.log
04/15/2015  01:04 PM    <DIR>          AMD
07/15/2015  08:11 AM    <DIR>          Anaconda
07/01/2015  02:19 PM               700 animationtest.py
.....
07/02/2015  02:34 PM    <DIR>          Windows
06/09/2015  07:53 AM    <DIR>          workspace
              11 File(s)        810,350 bytes
              17 Dir(s)   6,032,433,152 bytes free

When I try to import the .so files it says 'No module named ___'. I have added the path to the environmental variable PYTHONPATH but that didn't work either. 

os.listdir('.') will show the correct files but I have no way to import them.

Please help! Thanks.

**Comment by ccordoba12** [comment]
This was fixed in 2.3.5, so closing.
