### ISSUE TITLE
Pweave support?

### ISSUE THREAD

**Issue by naught101** [spyder-ide/spyder#2548]
http://www.mpastell.com/pweave/ - Pweave is a literate programming tool, like Knitr or Sweave - basically it lets you write a latex/rst/markdown file, and embed python snippets within the file, and then compile the file into a document that includes content generated from the python snippets.

It'd be really cool to have Pweave support in Spyder - in a similar way to how RStudio has Knitr support.

**Comment by magdalenat** [comment]
Hi, I'm upvoting request for that feature... I'm using RStudio with R and Knitr, so such solution in Python IDE will be desirable.

**Comment by mpastell** [comment]
Hi,
I have been working on merging and  adding fixes to Pweave and improving the documentation last week. It would be great to add the option to publish scripts directly from Spyder.

See here for the script format:
http://mpastell.com/pweave/pypublish.html

I could also add support for publishing documents that use the Spyder cell mark up. But I guess it would require some extending to define chunk options? 

The next release will also include markdown input format similar to R markdown. This already included in current master. You can have a look at the test document for info about markup: https://github.com/mpastell/Pweave/blob/master/tests/readers/markdown_reader.mdw .

**Comment by ccordoba12** [comment]
@mpastell, thanks for your interest in integrating Pweave with Spyder. It seems a very interesting project, and markdown support makes it even more interesting!!

I'd like support for it would be added as a third-party plugin, with its own dedicated pane to show Pweave scripts rendered as html pages (and PDF files, if you also add integrate pdf.js into this pane :-). You can take a look at these projects about how to do that:

https://github.com/spyder-ide/spyder.line_profiler
https://github.com/spyder-ide/spyder.memory_profiler

As part of this plugin, you could add an entry in our *Run* menu, called something like *Run as Pweave script* or *Run with Pweave*, which would call `pypublish` under the hood and show the results in the Pweave pane. That entry could also have its own keyboard shortcut for easy calling :-)

Unfortunately, we don't have to do this, but we can help you with developing this new plugin if you have doubts about the process.

**Comment by ccordoba12** [comment]
@goanpeca, we should write a simple document in our wiki about developing third-party plugins. Do you have some time to do it?

**Comment by goanpeca** [comment]
I agree about the document, BUT, we need to make menu entry addition more streamlined.... so that the plugin api includes some way of doing this easily.

**Comment by mpastell** [comment]
@ccordoba12 Thanks for the pointers. Adding a Pweave plug in sounds like a good idea. I'm not sure if I will have time to do it, but I will definitely look into it. I just added support for publishing scripts with cell mark up. 

So using current Pweave master running:

```
pypublish cell_script.py
```
should produce a nice HTML output.

**Comment by goanpeca** [comment]
@mpastell if you have questions in the process please ask, I will be more than willing to help you get the plugin going :-)

**Comment by mpastell** [comment]
Thanks!

@abukaj any thoughs on this?

**Comment by abukaj** [comment]
Well, I am unfamiliar with Spyder plugin API, and not much more competent as its user, so I am afraid that at the moment I can not be very helpful. :-(

**Comment by mpastell** [comment]
@goanpeca some documentation for third party plugins would be a good start :)

**Comment by goanpeca** [comment]
@mpastell will get to it on this week

**Comment by lgallindo** [comment]
What is the status on this?

**Comment by Nodd** [comment]
Well, there is now some (sparse) documentation on how to create plugins: https://github.com/spyder-ide/spyder/wiki/Writing-Plugins

**Comment by ccordoba12** [comment]
@rlaverde is going to work on a new external plugin called `spyder-reports` that will have Pweave and Stitch as backends to write reports.

This is the repo for this plugin

https://github.com/spyder-ide/spyder-reports

and it'll be availlable in a couple of months.

Please direct your suggestions and/or comments to that repo now :-)

**Comment by ccordoba12** [comment]
@rlaverde has created the first working Pweave integration here:

spyder-ide/spyder-reports#8

Yay!!
