### ISSUE TITLE
Refactor code to handle light mode as a separate class

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2551]
Currently the code inside `spyder.py` is a bit convoluted because `if not light` appears in a lot of places.

This change would make the code easier to read and maintain, and still keep the light mode in case there is people still using it.

**Comment by ccordoba12** [comment]
We should put a date to this one. I'd prefer to have it for 3.0, to test things very well and don't add possibly disruptive changes in 3.1.

Thoughts @goanpeca?

**Comment by goanpeca** [comment]
I will add this to my todo list, should be quite fast to do, so I will do it tonight, so we can move on with fast things first. We still have a pending hangout to go over projects, let me know when ;-)

**Comment by ccordoba12** [comment]
> We still have a pending hangout to go over projects, let me know when ;-)

Yep, I know, but please focus first on issue #2555, so we can release beta1.

**Comment by ccordoba12** [comment]
I finally decided to remove light mode. See PR #2874 for my reasons.
