### ISSUE TITLE
Share code with gtabview

### ISSUE THREAD

**Issue by scls19fr** [spyder-ide/spyder#2553]
Hello,

I'm looking for a way to use variable editor as a standalone viewer (or editor) for Numpy Arrays and Pandas DataFrame.
Like https://github.com/wavexx/gtabview
Is there a way to do it ?

Kind regards

See also: https://github.com/wavexx/gtabview/issues/7

**Comment by ccordoba12** [comment]
Not at the moment, sorry.

**Comment by Prikers** [comment]
I think this has been done through #3873 from @dalthviz

**Comment by ccordoba12** [comment]
Quite right @Prikers!
