### ISSUE TITLE
Spyder keeps crashing after pip package install

### ISSUE THREAD

**Issue by alexcordover** [spyder-ide/spyder#2554]
I tried to install the yahoo-finance package via pip. It successfully installed, but Spyder now crashes every time before it is opened. I tried resetting settings etc to no avail. Additionally, I am unable to uninstall the yahoo-finance package. It returns UTF-8 encoding errors that it can't decode certain bytes. I've not had problems with other implementations of Python with this package.

**Comment by ccordoba12** [comment]
This doesn't seem to be a Spyder problem but an installation one. I don't know how we could help here.

**Comment by ccordoba12** [comment]
I'm sorry but I'm going to close this one. It really seems an installation problem.

**Comment by alexcordover** [comment]
I believe it was. I did a clean install and spyder (and the installation of
the package) worked as expected.
