### ISSUE TITLE
Main window is bigger than screen size, after a first start in Mac and KDE

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2555]
This is the issue we discussed in person. Just as a reminder for you @goanpeca :-) I'm almost sure this was introduced after the new layouts PR.

This is how it looks for me in KDE, which is really bad.

![seleccion_002](https://cloud.githubusercontent.com/assets/365293/8814025/bfe2c81a-2fcd-11e5-8a97-ec1e736f5882.png)

Please take a look at this one ASAP because I want this fixed for beta1 ;-)

You can test this with

    python bootstrap.py --test

**Comment by goanpeca** [comment]
Is this also happening on win/linux?

**Comment by ccordoba12** [comment]
@goanpeca, it doesn't happen in Ubuntu, but the size of the Object Inspector is about 3/4 of the vertical screen size, so the IPython console looks too small.

**Comment by ccordoba12** [comment]
Windows shows the same problem as Ubuntu: the vertical size of our Python and IPython consoles is really small after a fresh start:

![seleccion_001](https://cloud.githubusercontent.com/assets/365293/8834828/4e60aebe-307c-11e5-9948-2186cdda0872.png)

I think the problems are related to the ones with KDE and Mac, except that (most probably) Windows and Ubuntu window managers prevent the window to overflow the screen.

**Comment by goanpeca** [comment]
I found the bug and is fixed in  #2559
