### ISSUE TITLE
Viewing variables in debug mode with the Variable Explorer is crashing Spyder

### ISSUE THREAD

**Issue by twd000** [spyder-ide/spyder#2557]
I'm having a problem in Spyder 2.2.5 (Python 2.7)
Using Anaconda distribution 

When I try to view/edit any variable type in the Variable Explorer that opens a separate window, that window immediately reports (Not Responding).  I have to kill the process and start over.
```python
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 21 16:24:03 2015

@author: tyler.davis
"""

tDog = ('breed','poodle')
lDog = list(tDog)
sDog = str(lDog)
```

I can view/edit sDog in the Variable Explorer, but any attempt to open/edit/view lDog or tDog opens the separate window that immediately freezes.  I understand that tuples are immutable, but I need to expand them because they are too long to display in the Variable Explorer window and are truncated with an ellipsis.

**Comment by goanpeca** [comment]
@twd000 spyder is currently in version 2.3.5, can you please update and check if the problems still persists in the newest version?

Cheers

**Comment by twd000** [comment]
Unfortunately 2.2.5 is the latest distribution that is approved/available on my corporate network.  If I can point to a bugfix that corrects this error, I could make an argument to our IT department to make 2.3.5 available to us.  Is there a bugfix/change list I can search?  Thanks

**Comment by twd000** [comment]
I found this changelog https://github.com/spyder-ide/spyder/blob/2.3/CHANGELOG.md, but any issue I click takes me to a 404 error page.  Is there another location to link detailed descriptions of the changes?

**Comment by ccordoba12** [comment]
@twd000, I fixed the links to issues and PRs in our Changelog. It seems Github changed the way they handle internal markdown links, so that's why those links were broken.

Also, didn't you post this problem to StackOverflow? There you mentioned that trying to view tuples was crashing Spyder only on **debugging**. Is this the case with this problem too?

Finally, 2.2.5 is more than two years old and is not maintained anymore. We're not going to solve this problem for that version.

**Comment by twd000** [comment]
Thanks for fixing the links; it works now.

I have only tested this feature using debugging mode.  I need to be able to view the contents of large tuples and lists during code execution.

I have a Help Ticket in to my IT Dept to update Anaconda/Spyder

**Comment by twd000** [comment]
I confirmed that this issue only occurs in debug mode.  If I pass the variables out from a function, I can view tuples and view/edit lists just fine via the pop-up windows in Variable Explorer.

**Comment by ccordoba12** [comment]
I ran your example code (present in your first comment) on debug mode, and using our latest stable version (i.e. 2.3.5.2) with Anaconda.

For me everything is working as expected, i.e. you can open and inspect tuples in a new window without problems.

So the only thing you need to do is to update Spyder. One thing that you perhaps are not aware of is that you **don't** need admin privileges to install Anaconda. You can just install it in your Users dir without problems, that's one of its main advantages :-)
