### ISSUE TITLE
add option "don't check line <79 chars" in "check PEP8 compliance" in Preferences

### ISSUE THREAD

**Issue by ilrico** [spyder-ide/spyder#2558]
PEP8 rule "line < 80 char" shouldn't be so strict (a line 82 is ok/better in most situation)
so we should be able do turn off PEP8 line-length check if needed

**Comment by bilderbuchi** [comment]
related: #2359

**Comment by ccordoba12** [comment]
Oh yeah! Closing as duplicate of issue #2359
