### ISSUE TITLE
Python console is not handling raw_input correctly on Windows

### ISSUE THREAD

**Issue by Travis42** [spyder-ide/spyder#2562]
Command Window causes raw_input() to malfunction

**What steps will reproduce the problem?**
1. program contains x = raw_input('> ')
   print 'You typed ', x
2. execution from command window produces nothing, user presses enter
3. output is >You typed 
   (exits)

**What is the expected output? What do you see instead?**
In Powershell, the program works as it should, but in Command Window within Spyder, it gets the order backward, expecting input before any prompt is displayed on the screen.

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.5.2 
- Python Version: 2.7.6
- Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
## Optional dependencies

```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. Please try to use an IPython console to see if things work as expected there.

**Comment by Travis42** [comment]
I will...right after I figure out how to import data/commands from the
command line (argv).  I've looked for how to do this for hours.  I realize
that Spyder is designed for best use with ipython, but I'm just a beginner
user at the moment, doing pre-defined lessons.

Travis

**Comment by ccordoba12** [comment]
Closing because the Python console is going to be removed in Spyder **3.2**.

Please see issue #4524 for our reasons to do this.
