### ISSUE TITLE
Enhancement: add option to "clear all" variables before running script

### ISSUE THREAD

**Issue by stsievert** [spyder-ide/spyder#2563]
I can define a variable in the console and have that same variable be available in script; the equivalence of Matlab's `clear all` isn't an option in preferences.

That is, at the IPython prompt I can define `a = 10`. Then if my script contains one line,

``` python
# script.py
print(a) # prints 10 even though `a` is not defined *in script*
```

It'd certainly be nice to disable that behavior. Other interpreters (e.g., default Python, IPython's `%run`) don't have this behavior enabled -- it throws `NameError: name 'a' is not defined`. Matlab has this feature where it reads variables defined from the variable explorer (and not the script) but it can be easily disabled with `clear all`. In Spyder, it requires a clever hack to "clear all".
### Proposed solution

Under "Run preferences" or in Spyder preferences > Run, I propose an option to enable/disable the equivalent of Matlab's "clear all". I propose the wording/default option be something like "[x] Variables in script must be defined in script. Otherwise, variables must be defined in Variable Explorer."
### Current hack

In the settings under IPython console > Startup, I have enabled a file to be run whenever I run a file. That file consists of a script to clear all the variables (which I found [here](http://scientificcomputingco.blogspot.com/2013/10/python-spyder-clear-workspaceshell.html)):

``` python
def clear_all():
    """Clears all the variables from the workspace of the spyder application."""
    gl = globals().copy()
    for var in gl:
        if var[0] == '_': continue
        if 'func' in str(globals()[var]): continue
        if 'module' in str(globals()[var]): continue

        del globals()[var]
if __name__ == "__main__":
    clear_all()
```

**Details:** I'm running Spyder 2.3.5.2

**Comment by ccordoba12** [comment]
Two things:

1. You can clean your namespace quite easily in IPython by running the `%reset` magic.
2. The option called `Execute in a new dedicated Python console` (which you can get when pressing F6) always run your code in a clean interpreter, every time.

Do we need to offer our users something else than that? I mean, when you run your code in the current Python or IPython console, it's assumed that it's going to pick up whatever values that are present there :-)

**Comment by scottsievert** [comment]
When I'm developing mathematical algorithms, I like to run my script (clearing all variables beforehand) and then using the console to interactively explore the variables I defined. For example, if I have the script

```python
from pylab import *

x = linspace(0, 1)

figure()
plot(x, x**2)
show()
```

I like to make sure I'm clearing all variables beforehand *and* interactively explore my data by typing `plot(x, x**3); show()` at the IPython prompt. This behavior is the default for %run and it's a plus for people converting from Matlab. Maybe have the dedicated Python console give you an IPython prompt after it's finished running your script? Maybe an option to use %run instead?

**Comment by scottsievert** [comment]
IPython has `%run <file>`, a feature which allows script/prompt variables to work like Matlab's `clear all` was inserted at the top of the script. I would much appreciate a preference to enable `%run` and know others would as well.

If we included a preference for `%run`, we'd be closer to emulating the Matlab experience with `clear all`. We would also be closer to emulating how IPython works in the wild (where people like me use `%run`).

I know when I was introducing a labmate to Python with Spyder, one of the first features he looked for was the equivalent of Matlab's `clear all`.

**Comment by sho-87** [comment]
This would be extremely useful, and I miss the clear all feature from matlab when working in spyder.

I find that when I'm iterating through a script and making changes to it, code bugs can creep in where it retains old values and uses them for a new run of the program. Most of the time I just want to clear the entire namespace every time I run my script so it can start fresh, and I know that any values in my current namespace exist because of the current version of my code, which makes everything much easier to debug

**Comment by ccordoba12** [comment]
@blink1073, could you add some light here? How exactly `clear all` in Matlab works? Sorry, but I was (mostly) a Mathematica user before moving to Python ;-)

**Comment by blink1073** [comment]
I have no light to shed, sorry.  I have forgotten as much about Matlab as I can.



—

**Comment by scottsievert** [comment]
I can shed some light! 

In essence, Matlab's `clear all` clears the namespace before running a script. By default, when a Matlab script is run it can pull variables previously defined from the variable explorer. `clear all` clears the variable explorer and deletes all variables previously defined by the user (but keeps global default functions/variables).

By contrast, `%run` runs a script in a clean *local* namespace. It then, in essence, does `from script import *`, importing all functions and variables to be available from the prompt. This allows exploring the variables from the prompt but prevents pulling variables from the variable explorer.

**Comment by Nodd** [comment]
The functionality is there for python consoles (always run in a new interpreter and enable the interaction after execution). It's only missing for IPython, where restarting the interpreter each time is not an option.

I don't understand how %run works. After the script has run, how dos IPython know if you want to access to the previousely declared variable of from the local namespace ?

**Comment by ccordoba12** [comment]
I think this is very valuable to have, so I'll implement it for 3.0.

**Comment by robinvanemden** [comment]
See https://gist.github.com/scottsievert/8655158355b7155b2dd8

At the IPython prompt, %reset clears everything -- it's like you're starting up the shell again. This way works and has to be manually run at the IPython prompt.

If you want to do it every run, at the very top of your script insert

    from IPython import get_ipython
    get_ipython().magic('reset -sf')

**Comment by ccordoba12** [comment]
@andfoy, please work on this one.

The idea is to add an option to the Run options in

    Preferences > Run

and also in

    Run > Configure

that after selecting it will clear the namespace of IPython consoles (and only IPython consoles).

It's important that we have this for 3.1 given that we don't have time to deactivate the Python Console on Windows, and that that console is very broken in that OS.

**Comment by ccordoba12** [comment]
Almost ;-) Let's make this option the first one below **General settings**

**Comment by ccordoba12** [comment]
And please also change its wording to

    Clear all variables before execution (IPython consoles)
