### ISSUE TITLE
QT_API keywords seem not tested the same way per Matplotlib

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#2564]
hi,

playing with PyQt5 and `gr`, I discover some issues with Matplotlib:
- they check QT_API='PyQt5'
- Spyder checks QT_API='pyqt5'.

https://github.com/matplotlib/matplotlib/blob/714d18788320325d0bff75184f62d472f67ceb91/lib/matplotlib/backends/qt_compat.py

==> Would it be possible to align on  Matplotlib ?

(or testing `QT_API.lower()`)

**Comment by ccordoba12** [comment]
I don't know what you mean by `gr`, but in the top file you referenced you can find this

```python
ETS = dict(pyqt=(QT_API_PYQTv2, 4), pyside=(QT_API_PYSIDE, 4),
           pyqt5=(QT_API_PYQT5, 5))
# ETS is a dict of env variable to (QT_API, QT_MAJOR_VERSION)
# If the ETS QT_API environment variable is set, use it, but only
# if the varible if of the same major QT version.  Note that
# ETS requires the version 2 of PyQt4, which is not the platform
# default for Python 2.x.
```

**Comment by ccordoba12** [comment]
So the env variable is called `pyqt5`, not `PyQt5`, which means that we're using the right variable. Besides, we selected that variable because it's the same one used by IPython.

**Comment by stonebig** [comment]
hum, ok, I understand better.
But I don't find where you use the API_NAME dictionnary to transform `os.environ['QT_API'] in spyder code base
 `QT_API = API_NAME[QT_API_ENV]`

**Comment by stonebig** [comment]
ok stupid me, at the end of the dico...  closing

**Comment by ccordoba12** [comment]
Just for the record, this is done in Spyder here

https://github.com/spyder-ide/spyder/blob/master/spyderlib/qt/__init__.py#L16

**Comment by stonebig** [comment]
Yes, my eyes missed the characters `[API]` the end of the line.
Sorry for the noise, it's not easy for me to guess which part is not playing well with PyQt5.
