### ISSUE TITLE
IPython kernel crashes after some plotting in pylab mode

### ISSUE THREAD

**Issue by pakwah** [spyder-ide/spyder#2568]
Error message:

It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

This happens irregularly and I am not sure about the reason. It usually happens when I've plotted multiple plots in different windows/figures and start closing some of them. I've tried plotting a lot of graphs one by one, closing the interactive window every time and the crash does not occur.

Any idea?

**Comment by ccordoba12** [comment]
Sorry, no idea :-( But please let us know your:

1. Python version
2. IPython version
3. Operating system
4. Spyder version
5. Matplotlib version

**Comment by pakwah** [comment]
Python 3.4.3.amd64
Ipython 3.2.0
Windows 8.1 Enterprise
Spyder 2.3.5.2
Matplotlib 1.4.3

Thanks

**Comment by arunkpe** [comment]
I have the same issue as pakwah. Except, I am on Windows 10. The error is very cryptic. Is this resolved?

**Comment by Waffleboy** [comment]
Having the same error. Occurs on 

python 3.5
ipython 4.0.3
spyder 2.3.8
matplotlib 1.5.1

**Comment by ccordoba12** [comment]
Please update to Spyder 3.0.2 and try again. It should be fixed now.
