### ISSUE TITLE
Can't search and replace some characters.

### ISSUE THREAD

**Issue by elwood168** [spyder-ide/spyder#2570]
I wanted to change a whole series of lists into tuples. I could not find and replace [ and ] to ( and ) respectively "square brackets and curly brackets". In the end, I copied it into Word and replaced them, and then pasted back.

**Comment by Nodd** [comment]
Be sure to uncheck the `entire words` option, these characters are not considered as words themselves (maybe it could be changed, this is often counter-intuitive).
