### ISSUE TITLE
Create wheels for Spyder

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#2574]
I would like to be able to create a wheel from spyder master git.

It should be possible, as Christoph Gohlke does it (http://www.lfd.uci.edu/~gohlke/pythonlibs/#spyder)

Unfortunately, the default spyder tree doesn't permit.

````>python setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
````

**Comment by ccordoba12** [comment]
Maybe that's because we're using `distutils` instead of `setuptools` in `setup.py`. I'll look into it.

**Comment by stonebig** [comment]
thanks.

**Comment by stonebig** [comment]
The "basic" wheel method suggested by Christoph Gohlke is to add an `import setuptools` at beginning. 

the wheel creation nevertheless fails on my Windows because of über-tricky colorama error messages in "\ansitowin32.py".

Spyder-ide project providing a wheel on its betas would definitely help

**Comment by stonebig** [comment]
another associated problem is that spyder wheel cannot be prepared on a Windows Python3.4 environment. 

step to reproduce
- be on windows
- be either in Python 3 or in Python 2
- add `import setuptools' at beginning of setup.py file (to allow wheel creation)
- then run `python setup.py sdist bdist_wheel`:
  - success on Python 2.7
  - failure on Python 3.4, with obscure messages in colorama (a python 2 / python 3 subtility)
````
copying scripts\spyder.bat -> build\scripts-3.4
running build_doc
Traceback (most recent call last):
  File "setup.py", line 272, in <module>
    cmdclass=CMDCLASS)
  File "\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)  File "\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()  File "\lib\site-packages\wheel\bdist_wheel.py", line 175, in run
    self.run_command('build')
  File "\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "\lib\distutils\command\build.py", line 126, in run
    self.run_command(cmd_name)
  File "\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 148, in run
    setup_command.BuildDoc.run(self)
  File "\lib\site-packages\sphinx\setup_command.py", line 141, in run
    if not color_terminal():
  File "\lib\site-packages\sphinx\util\console.py", line 58, in color_terminal
    colorama.init()
  File "\lib\site-packages\colorama\initialise.py", line 31, in init
    wrap_stream(orig_stdout, convert, strip, autoreset, wrap)
  File "\lib\site-packages\colorama\initialise.py", line 61, in wrap_stream
    convert=convert, strip=strip, autoreset=autoreset)
  File "\lib\site-packages\colorama\ansitowin32.py", line 68, in __init__
    convert = on_windows and not wrapped.closed and not on_emulated_windows and
is_a_tty(wrapped)
ValueError: underlying buffer has been detached


````

**Comment by ccordoba12** [comment]
As I said, we need to move from `distutils` to `setuptools` for this to work correctly. And that is not only a matter of adding

    import setuptools

to our `setup.py` script. What it really means is to rewrite `setup.py` in terms of `setuptools`.

However, I think you can use `pip` to auto-generate a wheel when you do

    pip install .

(at least that gives me a wheel on Linux).
