### ISSUE TITLE
segfault when unmaximizing editor pane

### ISSUE THREAD

**Issue by jlutgen** [spyder-ide/spyder#2578]
## Description
- _What steps will reproduce the problem?_
1. Start Spyder with default settings. Note that the outline pane is not visible.
2. Click in editor pane to give it the focus. 
3. Maximize current pane (editor) using toolbar or keyboard shortcut.
4. Now both the editor pane AND the outline pane are visible. This is interesting, but OK. (Note that in the View->Panes menu, "Outline" is not checked, however.)
5. Undock the outline pane so it is now a floating window.
6. Close the floating outline pane.
7. Unmaximize the current pane (editor) using toolbar or keyboard shortcut. Crash!
- _What is the expected output? What do you see instead?_
  Expect: current pane should be unmaximized, restoring Spyder to original default layout.
  Instead: crashes with segmentation fault on Mac, unknown application error on Windows.
- _Please provide any additional information below_

I can reproduce this crash in the following environments:
- Spyder 2.3.4 (Homebrew, Python 2.7.10) on Mac OS 10.10.4
- Spyder 2.3.4 (Anaconda, Python 2.7.10) on Windows 7
- Sypder 2.3.5.2 (Anaconda, Python 2.7.10) on Mac OS 10.10.4

It does _not_ occur in Spyder 2.3.0 (Python 2.7.8, Linux).

[Crash logs](https://gist.github.com/jlutgen/149a7cf38c8bf9db6cd2)
## Version and main components
- Spyder Version:  2.3.4
- Python Version:  2.7.10
- Qt Version    :  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  None (NOK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.4.4 (OK)

**Comment by ccordoba12** [comment]
Thanks for the detailed bug report. This seems a bug in Qt, the graphical library we use to build Spyder.

We'll see what we can do about it.

**Comment by goanpeca** [comment]
I think it may be a bit more convoluted... because of the way we handle the maximize/unmaximize of docks...

**Comment by ccordoba12** [comment]
Ok, thanks for the info. Let's leave it for 3.0 then.

**Comment by goanpeca** [comment]
I can take a look at this one... and it would be a good place to discuss the way it is done, cause I think we can make it less error prone.

**Comment by ccordoba12** [comment]
Ok, thanks ;-)

**Comment by bsquire0128** [comment]
I am having a similar issue when I am opening a dictionary of lists of lists, as I open the panes in the object viewer it crashes with a segmentation fault.

**Comment by Nodd** [comment]
@bsquire0128 The result is also a segfault but what's causing it is very different. Please open a new issue stating your problem. Use the Help menu to automatically fill a new issue with informations about your environment.

**Comment by ccordoba12** [comment]
Please open a new issue if this is still a problem in Spyder 3.0 (although I haven't heard of something like this :-).
