### ISSUE TITLE
Autoparens appear when autocompleting in the import section

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2581]
Autoparens is a great addition, but it should not be applied everywhere, such as whem importing something....

For example if I have this and then press `Tab` in this case (* denotes cursor location)

```python
from spyderlib.qt.QtGui import QToolButton, QToolT*
```

We get

```python
from spyderlib.qt.QtGui import QToolButton, QToolTip()
```

Which is not very helpful....

Any thoughts @blink1073?

**Comment by blink1073** [comment]
Hmm, that's a tricky one.  What if we only apply it if there is an `=` sign in the line?

**Comment by goanpeca** [comment]
I would rather make some helper function in the order of...

`is_import_statement()`

So you would know you are inside an import statement..?

**Comment by goanpeca** [comment]
This would be very useful for other cases, like auto formatting import statements

**Comment by blink1073** [comment]
I'm not sure how to do that for import continuation lines like:

```python
from IPython import (
   blah, blah2, blah3
```

**Comment by goanpeca** [comment]
can we do a lookup of the `import` word in the previous lines?

**Comment by blink1073** [comment]
Oh, duh, we're already checking for imports, this is actually simple then.



—

**Comment by goanpeca** [comment]
:+:
