### ISSUE TITLE
Feature Request: command + arrow keys

### ISSUE THREAD

**Issue by breedlun** [spyder-ide/spyder#2586]
In the editor, when the user presses command (on a mac) and one of the arrow keys, the cursor goes to the far left, far right, top, or bottom of the document.  This is common among mac applications, and I presume you get the same behavior on Linux and Windows if you use the control key.  

In the python console, on the other hand, when the user presses command (on a mac) and one of the arrow keys, the cursor moves only part way to the far left or far right.   Is it possible to make the console consistent with the editor and the majority of mac applications?

**Comment by goanpeca** [comment]
Hi @Stretch97, you mean the python console or the ipython console, or borh?

**Comment by Stretch97** [comment]
I was referring to the plain python console, as I don't use the iPython console much, but I suppose it would not hurt to add it to the iPython console too.

**Comment by AlJohri** [comment]
+1 This would be a really nice feature. Mac doesn't have the `Home` or `End` keys like windows so ⌘← and ⌘→ are the usual alternative. Although `Ctrl-A` and `Ctrl-E` also work on the command line and python/ipython shells.

**Comment by ccordoba12** [comment]
Closing because the Python console is going to be removed in Spyder **3.2**.

Please see issue #4524 for our reasons to do this.
