### ISSUE TITLE
Run cell and advance doesn't work on 2.3, Object inspector doesn't work on 2.2 (Both solved)

### ISSUE THREAD

**Issue by SandboChang** [spyder-ide/spyder#2588]
Hi, first sorry for the long post. I am new to Python and Spyder, it would be great if I can get some insights about some maybe easy to solve problems I am facing before I can move on to learn more.

Just started to use Python on Fedora Scientific 22, got Spyder running and really like it.
However, on trying to switch to Python 3.4 (it used 2.7 by default) there were two problems.

1. Run cell and advance doesn't work (nor just run cell)
I used to click shift enter for execution
However I realized that by moving from Spyder 2.2 to Spyder 2.3.5, 
clicking shift-enter returned nothing. Nor clicking the run cell icon did anything.
By moving back to 2.2 I was able to get the run cell functioning again.

    At first I thought it was my Linux machine's individual issue.
Then I worked on another Windows machine and got WinPython which also had Spyder 2.3,
the same happened and shift-enter wasn't doing anything.
Maybe I actually missed out some settings?

2. Object inspector doesn't work
On moving back from 2.3 to 2.2 on Fedora, the object inspector then quitted working.
It was able to automatically detect my functions like [array] or [input], but now it doesn't show anything at all. And then it is stuck at console, changing it to editor, then clicking variable explorer, coming back to object inspector it fell back to console again.

Any thoughts are appreciated.

**Comment by goanpeca** [comment]
@SandboChang thanks for reporting.

@SylvainCorlay can ypu take a look?

**Comment by ccordoba12** [comment]
Thing are working fine here, both on Windows and Linux. Cells are working with `Shift+Enter` and the Object Inspector is returning help for local functions.

@SandboChang, please run in a terminal:

    spyder --reset

and try again to see if that helps.

**Comment by SandboChang** [comment]
Thanks for the check, I shall be doing the reset on both. Both were however having unaltered setting as they a clean install.

I shall return to report for the updates.

On Aug 3, 2015 9:50 AM, Carlos Cordoba <notifications@github.com> wrote:
Thing are working fine here, both on Windows and Linux. Cells are working with `Shift+Enter` and the Object Inspector is returning help for local functions.

@SandboChang, please run in a terminal:

    spyder --reset

and try again to see if that helps.

---

**Comment by SandboChang** [comment]
I tried the reset, plus trying to install WinPython with Spyder one yet another computer.
Then I wiped my Linux machine (still testing distros) and put on a plain Fedora Workstation.
Installing Spyder 2.2 everything works, then I went to the bitbucket, install the 2.3 by running
[code]sudo python setup.pu install[/code]
It runs the installation, I opened again the Spyder it became 2.3, but then shift enter no longer works.

One thing I spotted was it was still running Python 2.7 instead of the Python 3.4 I hoped it would.
May I know if I mis-configured something?

**Comment by SandboChang** [comment]
I think I finally found one reason............

In 2.3.5.x, I have to HIGHLIGHT the comments I want to run before hitting shift-enter.
In 2.2, it wasn't necessary and shift-enter runs everything.
So I call this solved (or is there a way to make 2.3 behave like 2.2 for this?)

**Comment by ccordoba12** [comment]
You don't need to select a cell to run it, so that's odd.

I'm closing this because you said both problems are solved.
