### ISSUE TITLE
Spyder project renames/creates folders by removing first letter of imported directories

### ISSUE THREAD

**Issue by ktritz** [spyder-ide/spyder#2595]
## Description

**What steps will reproduce the problem?**

1. Right-click in project explorer, import existing directory 'test'
2. Close Spyder
3. Reopen Spyder

**What is the expected output? What do you see instead?**
Expect to see the 'test' directory in the project explorer.
Instead, see 'est' in the project explorer and 'est' folder created in the parent directory.

**Please provide any additional information below**
The project is located on a linux system mapped to a Windows drive.
Weirdly, if I then open spyder on the linux system, I see 't' in the project explorer, and a corresponding 't' folder has been created.

If I delete 't' from the project explorer and the disk, and then import 'test' it acts as expected on the Linux system when I close then reopen Spyder.

Then going back to Windows, opening Spyder shows the 'test' folder that was imported in the Linux version, closing and then reopening Spyder on Windows again shows the wrong behavior with 'est' appearing in the project explorer and an 'est' folder created in the parent directory.

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 2.7.9
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. Projects are going to be completely rewritten in our next version.
