### ISSUE TITLE
Call tips and auto completion tips go out of screen on a second monitor

### ISSUE THREAD

**Issue by cy18** [spyder-ide/spyder#2596]
![1](https://cloud.githubusercontent.com/assets/13564252/9120711/ec261c9e-3c4b-11e5-963d-38a58a399936.png)
![2](https://cloud.githubusercontent.com/assets/13564252/9120712/ec29b304-3c4b-11e5-9dc8-9898002f4abb.png)
I have two monitors and it only happens when the window is in the second monitor.

**Comment by ccordoba12** [comment]
I don't know how Qt handle other monitors. Seems tricky to fix.

**Comment by cy18** [comment]
@ccordoba12 I tried to fix it but I can not even found where the call tips is handled. It seems they are handled in https://github.com/spyder-ide/spyder/blob/df0b2ec50e3981c7157592eaec2b866f1c9c6b86/spyderlib/widgets/calltip.py#L194?
But nothing is printed after I added print(screen_rect) or debug_print(screen_rect). I added a raise Exception() after here and there are no exception raised.
What is the proper way to print some debug information when developing spyder? And do you know where the call tips is handled?
Maybe I missed something that the call tips is handled there but my modification is not effective?

**Comment by ccordoba12** [comment]
All `print`'s are redirected to the Internal console, so please take a look there.

**Comment by goanpeca** [comment]
@cy18 Inside Spyder go to `View` menu `panes` and then `Internal console`
