### ISSUE TITLE
Cannot change between UI tabs on OSX

### ISSUE THREAD

**Issue by joshburnett** [spyder-ide/spyder#2598]
## Description

**What steps will reproduce the problem?**

1. Start Spyder via python bootstrap.py
2. Try to change between Console, History Log, IPython Console, Object Inspector, Variable Explorer, etc.
3. The tab selectors now look like this:  
![image](https://cloud.githubusercontent.com/assets/12973799/9127414/9b1b2ef6-3c88-11e5-87e4-1e9523b6b623.png)  
...and the tabs have not changed state.
4. If I change to a different app, and then change back to Spyder, the originally-selected tab and the last-selected tab will be highlighted, like so (IPython console tab initially selected, then clicked on Console, and then History log):  
![image](https://cloud.githubusercontent.com/assets/12973799/9127433/fad33172-3c88-11e5-8462-931b214fe2d3.png)  
But the UI is still showing the IPython console tab.

I can get a particular tab to show up if I first hide the pane and then make it visible again via the View > Panes menu items.

## Version and main components

* Spyder Version: 3.0.0b1 
* Python Version: 2.7.10
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.2.0 (OK)
zmq >=13.0.0    :  14.7.0 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.4    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by blink1073** [comment]
I see the same thing.  @goanpeca:

```bash
 $ git bisect bad
e042cfc9a153baa91101f41aa52ff4cb1c6dee4f is the first bad commit
commit e042cfc9a153baa91101f41aa52ff4cb1c6dee4f
Author: Gonzalo Peña <goanpeca@gmail.com>
Date:   Sun Apr 26 23:08:33 2015 +0200

    Add drag support for dockwidgets sharing same position

:040000 040000 86292e5630d8b9371a6d8ce2cb9595fe376b9a9d 468580d4e3247fd8eede540d113a524c7dacc622 M	spyderlib
```

**Comment by goanpeca** [comment]
Hmmm ... I need a mac! :s

**Comment by ccordoba12** [comment]
I thought that was the case too. @goanpeca, this needs to be fixed for beta2.
