### ISSUE TITLE
Shortcut to toggle case

### ISSUE THREAD

**Issue by thewhitetulip** [spyder-ide/spyder#2601]
Ctrl + U = convert selected case to upper
Ctrl + shift + u = covert selected case to lower

**Comment by ccordoba12** [comment]
Someone will have to implement it :-)

**Comment by thewhitetulip** [comment]
I can implement but I just can't understand how spyder works, I went through the entire codebase, I want to also work on the issue about reopening last tabs, if @goanpeca or you can guide me, I'll submit a PR as soon as possible.

**Comment by Nodd** [comment]
This is a duplicate of #1669, I'll close this one.
Working with the editor is quite complicated because there is a lot of code around it, but the functionality itself is not that hard. You have to understand how QTextCursor works in Qt first, however.

**Comment by gamesbook** [comment]
What is the status of this?  #2601 and #1669 cross-reference each but both are closed?
