### ISSUE TITLE
Import issue running bootstrap.py from Spyder console

### ISSUE THREAD

**Issue by paulogrady** [spyder-ide/spyder#2603]
Hi,

I've recently forked Spyder and would like to make some mods locally etc. I've tried running `bootstrap.py` from Spyder in a console but I run into import issues (I've tried both *current* and *dedicated* interpreters). In particular, the Spyder console fails to load the development version of `spyderlib` even after including the dev version's path in `os.path` (as `bootstrap.py` does) and changing the working directory to the `spyderlib` parent directory. 

However, there is no issue when the script is run outside Spyder, i.e. `/usr/bin/python -u -i /home/paul/github/spyder/bootstrap.py` runs from the command line & Spyder's external terminal.

Any idea what's going on here? I know that Spyder uses an external shell widget to setup consoles/interpreters, which may be affecting things.

Thanks,

Paul.

Error:
```
Executing Spyder from source checkout
Traceback (most recent call last):
  File "/home/paul/github/spyder/bootstrap.py", line 103, in <module>
    from spyderlib.utils.vcs import get_git_revision
ImportError: cannot import name get_git_revision
>>> 
```
**Note:** that `get_git_revision` exists in my development version of `spyderlib` but not my installed version.

**Comment by ccordoba12** [comment]
Please use a regular (operating system) terminal to run `bootstrap.py`. That's how all core developers run Spyder from the git repo.

We don't have time, nor we are interested, in making `bootstrap.py` work inside Spyder. I hope you understand.
