### ISSUE TITLE
%matplotlib in iPython console

### ISSUE THREAD

**Issue by barrosv** [spyder-ide/spyder#2604]
I'm getting "invalid syntax" error when trying to use "%matplotlib inline" when using the Spyder editor and it shows up when trying to execute the editor in an iPython console. 

I know %matplotlib and other %magic subcommands are installed; I can execute the code just fine when using the iPython gtconsole, but it won't execute in Spyder.

Any thoughts? Thanks.
![screen shot 2015-08-09 at 7 32 35 pm](https://cloud.githubusercontent.com/assets/10642522/9157500/19a83a74-3ece-11e5-9e87-d0435dd04461.png)

**Comment by SylvainCorlay** [comment]
`%matplotlib inline` is an IPython magic and is not valid Python syntax.

If you ran this code by selecting the code and running it into the IPython console (using F9-run selection for example) it would run , however the "run" and "debug" buttons use a expect valid Python code.
