### ISSUE TITLE
Panels not dragging in 3.0.0 dev

### ISSUE THREAD

**Issue by johnml1135** [spyder-ide/spyder#2606]
When working in Spyder 3.0.0 dev, I when I drag the panels from either the top bar or the bottom tab nothing happens.  To move them I have to undock them with the resize (double-box) button and then I can move them.  There is no visual feedback when the panel would snap into the proper location.  Basically, there are work-arounds, but it is pretty unintuitive.

System:
-Windows 7
-WinPython-64bit-3.4.3.5Qt5.exe with Sypder dev 3.0.0

**Comment by ccordoba12** [comment]
You can move panes that are tabbed next to each other by dragging and dropping their tabs to the left or to the right. Unfortunately, this doesn't work for panes placed in different tabs.

@goanpeca, do you think there's something we can do to improve the situation? Like grabbing from a pane tittle to move to another position?

**Comment by goanpeca** [comment]
This should be working, but I guess the user did not realized that panes are `locked` by default?

**Comment by ccordoba12** [comment]
Oh yeah! I forgot that! ;-)

@johnml1135, you just need to go to

    View > Lock panes

to unlock them, and then reorganize them as you want.

We decided to lock panes by default to avoid accidental mouse dragging's, which was quite frequent and annoying.

**Comment by johnml1135** [comment]
Thanks for the explanation.  It makes sense now.

**Comment by goanpeca** [comment]
And we need to put this clear in `UPPERCASE` somewhere in the docs ;-) ! cause it might come and bite us again in the future
