### ISSUE TITLE
python crashes while switching the windows layouts with 'Lock panes' on

### ISSUE THREAD

**Issue by mickeydonkey** [spyder-ide/spyder#2607]
e.g. Spyder crashes when i tried to use Matlab layouts. currently I bypass this problems by unselecting 'Lock panes' first, then change the layouts.

**Comment by ccordoba12** [comment]
Questions:
1. What's your Python version?
2. What operating system are you using?
3. How did you install Spyder?

For next time, please use the menu entry under

     Help > Report issue...

to report a bug. That entry gives us all this information (and more) as part of the report.

----

@goanpeca, this one is yours ;-)

**Comment by goanpeca** [comment]
Got it

**Comment by ccordoba12** [comment]
Closing because of lack of response. We don't even know which operating system was using the OP.
