### ISSUE TITLE
Inline images copied from IPython can't be pasted in Word

### ISSUE THREAD

**Issue by johnml1135** [spyder-ide/spyder#2609]
I made a plot in the IPython console and when I right click and select "Copy Image," I cannot then paste it into a Word doc.  I can work around it by saving the image and then placing it in the Word doc.

Code sample:
import matplotlib.pylab as plt
plt.plot([1,2,3,2])

System:
Windows 7
WinPython-64bit-3.4.3.5Qt5.exe
Spyder 3.0.0dev

**Comment by ccordoba12** [comment]
We'll see what we can do about it

**Comment by ccordoba12** [comment]
We'll see what we can do about it

**Comment by johnml1135** [comment]
I am using the latest winpython build (winpython-64bit-3.4.3.6Qt5_rc.exe on Oct 26th) and I can now copy and paste inline images.  I don't know if something back in IPython was fixed in the intermediate time...  In any case, it is working fine now.

**Comment by johnml1135** [comment]
I found that the error was fixed with Jupiter QtConsole 4.1 (https://github.com/jupyter/qtconsole/issues/48)
