### ISSUE TITLE
Fix version detection on the Dependencies dialog

### ISSUE THREAD

**Issue by flying-sheep** [spyder-ide/spyder#2612]
The optional dependencies pane tells me that `rope==0.9.4-1` is installed, and that this wouldn’t satisfy `rope>=0.9.4`.

That’s wrong, so please fix your version comparison function.

**Comment by ccordoba12** [comment]
You're totally right, this is a bug.

**Comment by ccordoba12** [comment]
This is really bad. It's preventing `rope` from being used to do completions!

I'll fix it myself.
