### ISSUE TITLE
Use $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by flying-sheep** [spyder-ide/spyder#2613]
do not create dotfiles in my `$HOME`, but instead use [`appdirs`](https://pypi.python.org/pypi/appdirs/1.4.0) to get the proper config file location.

**Comment by ccordoba12** [comment]
We already have discussed this with you, and we told you already we're not going to follow the XDG standard.

**Comment by flying-sheep** [comment]
oh we did? sorry!

i searched, but i didn’t find it.

**Comment by flying-sheep** [comment]
hmm, could you give me a link? i can’t find it!

**Comment by blink1073** [comment]
https://github.com/spyder-ide/spyder/issues/2230

**Comment by flying-sheep** [comment]
ah, thanks! quite the tangent there huh?

but re-reading it all, i still only saw one argument:

> Another reason for IPython to finally not go with XDG (and the most important one for me) is that is harder to point people to where configuration files reside, in a simple and multi-platform way.

which i replied to with

> yes, i know! my point is that it’s a valid point for them, as they actually do have to point people to the config file on a regular basis, unlike us who point people to the settings dialog instead.

and got no response. so i assumed i convinced you :wink: 

and to add to that: it’s really not difficult to say “if you’re on linux, go to `~/.config/spyderlib/`, if you’re on windows go to `%appdata%\spyderlib\`, and if you’re on OSX, go to `~/Library/Application Support/spyderlib`”.

**Comment by flying-sheep** [comment]
so since i’ve not heard anything in response to my arguments i’m going to assume i convinced you?

you forgot to reopen this :wink:

**Comment by ccordoba12** [comment]
There is #2629 open already, so we don't need to reopen this one.

**Comment by flying-sheep** [comment]
OK, thanks. this one has the more correct title, though
