### ISSUE TITLE
Cell execution fails when second cell line is comment and has accents

### ISSUE THREAD

**Issue by silicium14** [spyder-ide/spyder#2618]
I use spyder 2.3.5.2 on windows 8.1 64bit

I can execute a cell like this :

``` python
#%% Some Text
# Some Text
print('Test text')
```

I can't execute a cell like this :

``` python
#%% Some Text
# Here is a letter with an accent : é
print('Test text')
```

**Comment by stonebig** [comment]
@silicium14 : you may add a screenshot or copy/paste of the error, to help resolution.

Which Python version do you use ? I don't see your error, if I understood it well, on Python 3.4

![spyder_accent](https://cloud.githubusercontent.com/assets/4312421/9283321/27d6dcf0-42d3-11e5-9182-e08376683d89.GIF)

**Comment by silicium14** [comment]
Hi @stonebig 
Here is a screenshot of my spyder window.
![image](https://cloud.githubusercontent.com/assets/13800015/9288559/bbdd5c02-434c-11e5-8d66-4b7f2c9c72f2.png)

When I hit CTRL+Enter (or use menu to execute cell) on the first cell, the cell is executed. When I put the text cursor on the second cell  an hit CTRL+Enter (or use menu to execute cell), nothing happens. There is no error message displayed, I just see that the cell is not executed because nothing is added to the IPython console / the IPython command counter is not incremented.

I use Windows 8.1 64bit, Anaconda3 64bit 2.1.0, spyder 2.3.5.2, Python 3.4 64bit.
Here is the output of  ```sys.version``` from the IPython console inside spyder:
```python
'3.4.1 |Anaconda 2.1.0 (64-bit)| (default, Sep 24 2014, 18:32:42) [MSC v.1600 64 bit (AMD64)]'
```

Here is the content of the python file in my screenshot:
```python
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 15 12:49:56 2015

@author: Julien
"""
#%% Some Text
# Some Text
print('Test text')

#%% Some Text
# Here is a letter with an accent : é
print('Test text')
```

**Comment by stonebig** [comment]
ok, the good news is that:
- it works ok under Spyder-3.0.0b1
- Carlos apparently knows what the bug is

![spyder3_accent](https://cloud.githubusercontent.com/assets/4312421/9288787/db69d7dc-4359-11e5-95c6-8eee842c4f53.GIF)

**Comment by ccordoba12** [comment]
I'll take a look at this one for our next stable release. Thanks for the screenshots, by the way.

**Comment by silicium14** [comment]
Ok, good news :)

I just downloaded WinPython and I have the same behaviour as you @stonebig  with WinPython's spyder 2.3.5.2: no problem with accent.

If it may help, here are the versions displayed at the bottom of "About spyder" window in both cases (screenshot).
* WinPython 3.4.3.5

![image](https://cloud.githubusercontent.com/assets/13800015/9289420/682ed78e-436f-11e5-9582-937009fd85fe.png)

* Anaconda 2.1.0 (64-bit) (as up to date with ```conda update --all``` at 2015 august 15th)

![image](https://cloud.githubusercontent.com/assets/13800015/9289431/e43c6bb6-436f-11e5-82f8-507c171a3675.png)

**Thank you for the answers**

**Comment by ccordoba12** [comment]
This seems to be an issue with PyQt4. It'll probably get fixed after we update it in Anaconda to its latest stable version.

**Comment by goanpeca** [comment]
This is no longer relevant. Closing
