### ISSUE TITLE
Spyder fails to start on light mode because of check_updates code

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#2619]
when launching spyder_light on Python3.4/PyQt5.5.0/Jupyter4/spyder-3.0.0dev, i get this strange error:

````
Traceback (most recent call last):
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3103, in main
    mainwindow = run_spyder(app, options, args)
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 2999, in run_spyder
    main.post_visible_setup()
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 1308, in post_visible_setup
    self.check_updates()
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 2900, in check_updates
    self.check_updates_action.setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'setDisabled'
````

on a side-note, I would be happy if the check_update was disabled per default

**Comment by stonebig** [comment]
the problem goes away if I un-clicked the "check for updates" via a Spyder normal session

**Comment by ccordoba12** [comment]
@goanpeca, please take a look at this one. It should be an easy fix :-)

**Comment by goanpeca** [comment]
Will do!

@stonebig I understand, but the idea of the check for updates is to drive the community into the newest version possible, we receive a lot of questions from people still in 2.2.x ....

Disabling it by default really does not help in this direction.

**Comment by ccordoba12** [comment]
I agree with @goanpeca, but I also understand @stonebig, given that he is a packager. Let's leave for another issue though.

**Comment by goanpeca** [comment]
ok

**Comment by stonebig** [comment]
can you pinpoint me the line of code to change if iI want to have the other default initial behavior in my case ? it's not clear to me.

**Comment by goanpeca** [comment]
Should be this one

https://github.com/spyder-ide/spyder/blob/master/spyderlib/config/main.py#L199

**Comment by stonebig** [comment]
thanks!

**Comment by goanpeca** [comment]
:+1:
