### ISSUE TITLE
Problem when launching Spyder

### ISSUE THREAD

**Issue by DaBosc** [spyder-ide/spyder#2620]
Hello,

I am working on Mac, and I did install Python 3.4, and Anaconda 3, in order to work with Spyder. 
Everything was working great, but I did something wrong and I did uninstall Anaconda. Therefore, I have installed Anaconda again, but now I cannot launch Spyder anymore. 
I did also try to launch it directly from the bin directory, but it gives the following error message:
" configparser.DuplicateSectionError: While reading from '/Users/.spyder2-py3/spyder.ini' [line 492]: section 'color_schemes' already exists logout ".
Can you help me on this issue please?

Thank you.

**Comment by ccordoba12** [comment]
@DaBosc, just open a terminal and run this command

    spyder --reset

That should fix your problem :-)

**Comment by ccordoba12** [comment]
Closing because that should definitely fixed the problem.
