### ISSUE TITLE
Spyder should start using six + any custom Qt/Py2/Py3 compatibility layer.

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2621]
Currently spyder uses its own [compatibility layer](https://github.com/spyder-ide/spyder/blob/master/spyderlib/py3compat.py) for Py2 and Py3.

It would be a good idea to make use of [six](https://bitbucket.org/gutworth/six) which is a more standard way of handling this compatibility + any specific functions needed to handle PyQt/Py2/Py3 issues.

@spyder-ide/core-developers?

**Comment by ccordoba12** [comment]
I really prefer our own module, it's simple and light weight. Last time I checked, `six` supported up to Python 2.4, which is just too much. IPython also has its own compat module too, so that's a less compelling reason to do the move. 

Besides (and I'm not going to get tired of repeating it), *if it's not broken, please don't fix it* ;-) We don't know what bugs we could introduce by doing this switch, and I'm not willing to fix any of them :-)

**Comment by Nodd** [comment]
`six` is widely used but it makes python3 code compatible with python2. Now http://python-future.org/ does the reverse: you write python3 code which is compatible with python2, which is better on the long run.

That said I agree with @ccordoba12 that it should not be touched now. This compatibility layer includes touchy things like bytes/strings compatibility, it's quite easy to break things. External modules could have been used from the beginning but it's history now.

In a few years when python2 is really not used anymore the compatibility layer should be completely removed.

**Comment by ccordoba12** [comment]
Thanks for the wise words @Nodd. I really missed them during your time away from the project!! :-)

That's my main concern really: that moving to another compatibility library could introduce or re-introduce subtle unicode/bytes bugs that usually take me hours or days to fix.

I also suggested Pierre to use `six` when we were about to move to Python 3, but he decided against it and instead created `py3compat`. So now we have to live with that decisions (which is not that bad after all: one less dep :-)

----

@goanpeca, I hope you're ok with me closing this issue. We really have much more important things to care about than trying to revert a decision which such a huge impact on stability.

**Comment by goanpeca** [comment]
Sure, but I will open it again eventually :smirk:

**Comment by Nodd** [comment]
> Thanks for the wise words @Nodd.

You're welcome ! It's nice to hear that my answers are appreciated.

> I really missed them during your time away from the project!! :-)

I can't say I'm completely back. I can file or comment a few issues from work, but I can't do actual programming at home right now.

**Comment by goanpeca** [comment]
Hehe, we are really glad you can jump in on the issues!, do not worry about the work at this point, we got your back covered!

**Comment by ccordoba12** [comment]
+1 to what @goanpeca said. Please continue contributing in our discussions. As I said, that's very well received :-)
