### ISSUE TITLE
Multiple untitled files generate at close

### ISSUE THREAD

**Issue by H0R5E** [spyder-ide/spyder#2625]
Hi, I'm running version 2.3.5.2 using Anaconda Py27 for windows 7 64bit.

I have a problem where when I close spyder I get a long (possibly infinite) chain of untitled windows to close. Basically, each time I say I don't want to save it a new one appears.

I seem to be able to get round it by pressing cancel and then closing again, but its a bit annoying.

**Comment by LeoWelter** [comment]
I'm still seeing the same behaviour on Spyder 4.0.1, Python 3.6.7 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Linux 5.3.0-26-generic
