### ISSUE TITLE
Show current file in file browser

### ISSUE THREAD

**Issue by naught101** [spyder-ide/spyder#2628]
It would be nice to have a menu item to show the current file in the file explorer (move to directory, select file), ideally in the context menu.

**Comment by ccordoba12** [comment]
Good suggestion.

**Comment by goanpeca** [comment]
@naught101 can you elaborate a bit more on how this would work and use cases?

Cheers :-)

**Comment by naught101** [comment]
@goanpeca: basically, if you have a file open, and click "show current file in file browser", it would change the file browser's displayed directory to the directory containing the file (obviously this would not be available for unsaved files), and then select/highlight the file.
