### ISSUE TITLE
Use XDG_CONFIG_HOME for config directory on Linux

### ISSUE THREAD

**Issue by naught101** [spyder-ide/spyder#2629]
According to: http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

use `$XDG_CONFIG_HOME`, or if that is not set, use `~/.config/` as the base directory (e.g. `~/.config/spyder`)

**Comment by goanpeca** [comment]
We will be implementing this for Spyder 3.0

@flying-sheep

**Comment by flying-sheep** [comment]
oh great! out of curiosity: what changed your opinion?

compare also #2613

**Comment by goanpeca** [comment]
We changed our mind ?

**Comment by ccordoba12** [comment]
We took a vote among @spyder-ide/core-developers and I was the only one wanting to keep things as they were.

**Comment by flying-sheep** [comment]
i hope my arguments in #2613 are sufficient to convince you after the fact :smile:
