### ISSUE TITLE
Garbage characters in file list when "sort files according to full path" is off.

### ISSUE THREAD

**Issue by jlutgen** [spyder-ide/spyder#2630]
## Description

When "sort files according to full path" is turned off (Preferences->Editor->Display->Interface), garbage characters appear in the drop-down file list in the editor pane and in the tooltips that pop up when hovering over editor tabs.

Confirmed on Windows, Mac, and Linux. The garbage characters are somewhat more numerous in Linux.

On Mac and Windows, I'm seeing something like this:

<img width="262" alt="mac-dropdown" src="https://cloud.githubusercontent.com/assets/6889876/9391753/7fdf3880-472d-11e5-8494-bf5cbbc35f16.png">

<img width="191" alt="mac-tooltip" src="https://cloud.githubusercontent.com/assets/6889876/9391757/88e0d45c-472d-11e5-8c72-d81e19ff16d9.png">

And here's the behavior on Linux:

<img width="231" alt="linux-dropdown" src="https://cloud.githubusercontent.com/assets/6889876/9391756/86b90dac-472d-11e5-8424-4a7c3336033b.png">
## Version and main components
- Spyder Version: 2.3.5.2 
- Python Version: 2.7.10
- Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0:  0.9.0 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.6.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

```

**Comment by goanpeca** [comment]
Thanks for reporting! will look into it

**Comment by ccordoba12** [comment]
This is very old and was reported afterwards.
