### ISSUE TITLE
Spyder interface font can't show (linux system)

### ISSUE THREAD

**Issue by wqshen** [spyder-ide/spyder#2631]
![fff](https://cloud.githubusercontent.com/assets/12339722/9400987/eb377f02-47fa-11e5-817f-898c4dbe97f4.PNG)

I install anaconda 2.3 in the Red Hat. And then when i launch spyder in the xshell, 
the font can not show, and some info appeared in the xshell,
     QFont::setPointSize: Point size <= 0 (-2), must be greater than 0

How to fix it ?

Thank you

**Comment by ccordoba12** [comment]
I've never seen this bug. It seems a problem with the fonts you have selected in your system.

**Comment by ccordoba12** [comment]
Maybe running in a terminal

    spyder --reset

and trying again could help.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
