### ISSUE TITLE
Dragging a file into the editor (drageEnterEvent) throws TypeError

### ISSUE THREAD

**Issue by StefanD986** [spyder-ide/spyder#2632]
When I drag a file from the Finder (the OSX file browser) into the spyder window the Internal Console pops up and throws:

``` python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/spyderlib/widgets/editor.py", line 1785, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable
```

Maybe related to issue #2032 (closed no too long ago)? 

My configuration:
Spyder 3.0.0dev
Mac OSX 10.10.5

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 3.1 (the fix is already o master).
