### ISSUE TITLE
Extra "PYTHONPATH manager" menu item after loading saved session

### ISSUE THREAD

**Issue by jlutgen** [spyder-ide/spyder#2635]
On Mac, a duplicate "PYTHONPATH manager" menu entry is created each time you load 
a saved session (Spyder 2.3.5.2 and 3.0.0b1).

This does not happen on Windows or Linux.

<img width="269" alt="screen shot 2015-08-23 at 1 55 03 pm" src="https://cloud.githubusercontent.com/assets/6889876/9430182/58b393a8-49a0-11e5-9df9-e9ddc8765b5d.png">
## Version and main components
- Spyder Version: 2.3.5.2 
- Python Version: 2.7.10
- Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.4 (OK)

```

**Comment by goanpeca** [comment]
Hehe, thats a funny bug...

**Comment by goanpeca** [comment]
Are we deprecated sessions in favour of projects... or are we leaving both options... in case you want a session to be selfcontained in a single session file @ccordoba12. 

I see use cases for both options (projects and sessions)

**Comment by ccordoba12** [comment]
For now we're going to leave only projects, which will save and restore sessions by default. So all menu entries for sessions must be removed.

**Comment by goanpeca** [comment]
But what if I am am working on a version control project and I am working on several branches at a time, having different sessions for different branches would be helpful as a single project dir would not cover this case... (same project dir but many branches..)

On Branch 1 (session 1) I have X files open and on Branch 2 (session 2) I have another set of files....

**Comment by ccordoba12** [comment]
Let's start with the simplest thing first, i.e. projects are equivalent to sessions. Later we can see if sessions can be restored or not.

However, having these two similar concepts as part of Spyder can be really confusing for people (even if valuable for power users). 

Besides, I haven't seen other IDEs using both sessions and projects.

**Comment by goanpeca** [comment]
We no longer support sessions. Closing
