### ISSUE TITLE
Problems with filename extension for saved sessions 

### ISSUE THREAD

**Issue by jlutgen** [spyder-ide/spyder#2636]
A couple of issues with the default filename presented to the user when doing "Save session and quit...":

### Mac (Yosemite, 10.10.5)

Spyder 2.3.5.2: the default is `Untitled.session.tar.session.tar.session.tar.session.tar.session.tar`.

Spyder 3.0.0b1: the default is `Untitled.session.tar.session.tar`.

Also, if I accept the default and click "Save", I am presented with a rather confusing Mac OS message, as shown below:

<img width="395" alt="screen shot 2015-08-23 at 2 03 39 pm" src="https://cloud.githubusercontent.com/assets/6889876/9430340/47c545ae-49a6-11e5-8ffe-8e27285b4bd9.png">

### Linux (Lubuntu 14.10)

When saving a session, the save dialog gives no indication that I should use the `.session.tar` extension (the file type filter in the save dialog lists only "Spyder session", and the "Name" field is empty). 

Saving a session as `mysession` creates a valid tar file (because this is Linux!), but when I restart Spyder and try to load that session, I can't do it,  because `mysession` does not show up in the "open file" dialog (again, the only choice in the file type filter drop-down is "Spyder session", so there is no way to change it to "all files").

### Windows

No such problems; if the user enters `mysession` as the filename when saving a session, the session is saved as `mysession.session.tar`, and then there is no problem loading the session later.

**Comment by ccordoba12** [comment]
Right now this functionality is not that good (as you're already noticed), but we don't consider important to fix it because it'll be completely changed in Spyder 3.0.

Sessions will be vastly improved when our new projects facilities have the ability to automatically save and restore them.

**Comment by ccordoba12** [comment]
Sessions will be removed as part of #3377, they really never worked correctly.
