### ISSUE TITLE
After restarting spyder the PYTHONPATHs entries get replaced with path-s relative to the project location

### ISSUE THREAD

**Issue by nad2000** [spyder-ide/spyder#2637]
Behaviour observe with Spyder 2.3.5.2 
Not  with 2.2.5

Steps to reproduce:
0. a project located in **baseA/dirA**
1. add a path using PYTHONPATH manager: **baseB/dirB**
![screenshot from 2015-08-24 14 14 02](https://cloud.githubusercontent.com/assets/177266/9431719/7bbc3c58-4a6b-11e5-9754-657847213e4b.png)
2. close and reopen spyder
3. open PYTHONPATH manager. The path got replaced with **baseA/dirB**
![screenshot from 2015-08-24 14 14 36](https://cloud.githubusercontent.com/assets/177266/9431726/8aafde68-4a6b-11e5-8ed9-27e186e645b5.png)

**Comment by nad2000** [comment]
I have tried to create the environment under the project  base directory **baseA**: **baseA/testenv27**. After restarting spyder that resulted in an unpredictable substitution: **baseA/dirA/v27/...**
![screenshot from 2015-08-24 14 31 24](https://cloud.githubusercontent.com/assets/177266/9431852/70bd9534-4a6d-11e5-8740-fa1b7d6ed704.png)

**Comment by ccordoba12** [comment]
Thanks for reporting, we'll see what we can do about it.

**Comment by ccordoba12** [comment]
Closing because we handle projects differently in Spyder 3.
