### ISSUE TITLE
PySide can not be used on 2.3

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#2649]
If PyQt4 is not installed, `sip` is also unavailable, so import fails earlier that a try/except block that sets PySide as a fallback.

**Comment by ccordoba12** [comment]
This bug has been present for a long time. The exact same code is in `master` and nobody has noticed it before :-)

I guess very few people is using Spyder with PySide then.

**Comment by Nodd** [comment]
> I guess very few people is using Spyder with PySide then.
In Linux at least, lots of packages depends on python-pyqt4, si it tends to be installed along pyside. And in Anaconda PySide is not supported anymore (but still installable if I recall correctly).
So even people using pyside have pyqt and sip installed.

**Comment by techtonik** [comment]
@ccordoba12 majority of people who are trying Spyder, don't know how to report bugs for it. And nobody would care to go through Github registration to report bug in a product they couldn't even start. These are all Windows users, who are not in open source at all.

I am reporting it only because I obscured this behavior in a class of students who are still using IDLE to learn Python.
