### ISSUE TITLE
Use Page up/down keys (and a modifier?) to browse a long result in the console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#265]
_From [mproel...@googlemail.com](https://code.google.com/u/105494983286078857315/) on 2010-08-06T02:04:06Z_

Hi,

I would like to have the abiliy to "browse" in the console with the keyboard. Just one simple example, considering the following code:

device = something()
device.connect()
result = device.getDecodingResult()

\<run and interact the code>
now you want to introspect the result and it gives you something like:
\>>> result
'start#0.1125#56895#-5656#stop'
\>>> \<now you want to know how long is the string until the second separator>
with the mouse you can select it copy and paste it. So far so good. It would be nice to be able to move the cursor up in the console, to copy the string with the keyboard. 
It could, for instance, realized by the following.
The up-key gives the last commands you tiped, very useful and necessary, but it could be done, that the up-key only gives the last command if you are with the cursor at the position:
\>>> |
Now if you go one position left you are at
\>>>| and from there the up/down key could be used to move the cursor up and down. If you want to go back you just have to press return (as implemented yet) or when paste a string it is pasted automatically to >>> | (as implemented yet).

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=265_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-02T10:42:01Z_

**Summary:** Use Page up/down keys (and a modifier?) to browse a long result in the console  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:07:33Z_

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:09:12Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T13:01:27Z_

**Labels:** MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-09-21T11:20:04Z_

This is usually done by pressing "Shift+PageUp" and "Shift+PageDown". Very good suggestion by the way :)

**Labels:** Easy

**Comment by ccordoba12** [comment]
This is not needed now :-)
