### ISSUE TITLE
Saving documents in the editor does not always write changes to disk.

### ISSUE THREAD

**Issue by chrisjcameron** [spyder-ide/spyder#2660]
## Description
Changes to document are not saved to disk when document is saved (Especially when Spyder crashes)

**What steps will reproduce the problem?**

1. Make changes to python script.
2. Save document.
3. Kill Spyder (to simulate a crash)
4. Reopen document, note missing changes that were not written to disk.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
One question: If Spyder is closed correctly, is the file saved correctly?

**Comment by chrisjcameron** [comment]
I can't reproduce this today. I will keep an eye on this behavior and reopen if I have any more detail. It saves fine normally. I can verify that changes are made to files immediately by inspecting with another editor, so I don't see why there should be any issue with saved data loss from crashing.
