### ISSUE TITLE
Conda package manager is packed in 2.3.6 win32 distribution leading to errors

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#2661]
https://bitbucket.org/spyder-ide/spyderlib/downloads/spyder-2.3.6.win32-py2.7.exe contains p_condapackages.py which leads to the error #2657.

@ccordoba12 how do you build the package?

**Comment by ccordoba12** [comment]
This is probably cause by an stalled file in my working directory. I'll fix it in 2.3.7.

**Comment by techtonik** [comment]
If the packaging procedure could be done by a separate script from a clean checkout, it is possible to test the build from CI.

**Comment by ccordoba12** [comment]
I'll be sure to start from a clean clone before creating the installers. Thanks for reporting @techtonik :-)

**Comment by techtonik** [comment]
No problemo. Ping me when new installer is ready. =)

**Comment by ccordoba12** [comment]
Ok, I hope to do a new release today :-)
