### ISSUE TITLE
Variable explorer does not show variables and crashes when buttons on side pressed

### ISSUE THREAD

**Issue by cvanheer** [spyder-ide/spyder#2664]
## Description

**What steps will reproduce the problem?**

1. Changing the variable explorer preferences in the spyder preferences
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
When I change any settings in the variable explorer Spyder crashes. When I run any script I cannot see any of the variables in the environment. It is empty. I have tried re-installing anaconda and spyder and neither works. 

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
Are you using 10.10 or 10.11 by any chance?

**Comment by ccordoba12** [comment]
Closing because of lack of response.

If you're using 10.10 or 10.11, this problem could be fixed by an Anaconda update in a couple of weeks.

**Comment by Nodd** [comment]
> Are you using 10.10 or 10.11 by any chance?
I see that this question comes back often. Is it possible to include this information in the bug template ?

**Comment by ccordoba12** [comment]
Yes, I think it's possible :-) Could you open an issue about it so I don't forget to do it?

**Comment by Nodd** [comment]
Well I could, but I don't even know what 10.10 and 10.11 refer to exactly... Is it the Darwin version ?
