### ISSUE TITLE
Add run cell (and run cell advance) to right click prompt

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#2674]
Please consider adding the right click "run cell" and "run cell and advance" prompt to Spyder 3.0 - it's something I'm really missing in the current beta1!

**Comment by ccordoba12** [comment]
Will do for beta2 :-)

**Comment by durack1** [comment]
Great! Oh and while I'm pushing my luck, what are the chances code folding will be in beta2??

**Comment by ccordoba12** [comment]
Hopefully @goanpeca will add code folding for beta3 :-)

**Comment by goanpeca** [comment]
Ok, I will make a plan for code folding, I will need to break in the fixes that neet to be done before it happens.
