### ISSUE TITLE
Multiline search and replace doesn't replace

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#2675]
## Description

**What steps will reproduce the problem?**
1. Activate search & replace widget
2. With regular expression mode engaged, search for a multiline pattern (e.g. \n\n\n)
3. Enter some text to replace the expression, hit replace/find button.

**What is the expected output? What do you see instead?**

You would expect the multiline search pattern to be replaced with the replacement text. Instead, no replacement is made.

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.6 
- Python Version: 2.7.9
- Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows
## Optional dependencies

```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
We'll take a look about this one after releasing 3.0 because it's not too critical :-)

**Comment by goanpeca** [comment]
Indeed this is not working for `replace` or for `replace all`

<img width="702" alt="Screen Shot 2019-11-27 at 21 38 28" src="https://user-images.githubusercontent.com/3627835/69772568-46c2f000-115e-11ea-8656-3c6407185695.png">
