### ISSUE TITLE
Slow execution of blocks in the Python console

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder#2678]
The script below runs in about 0.05 seconds when executed with F5 or from the command line. If I run the script using CTRL-ENTER or I select the code and use F9 the running time is about 4 seconds.

``` python
import time
import numpy as np

#%%
aa=[]
t00=time.time()
pp=np.arange(40)
for ii,p in enumerate(pp):
    for k in range(8):
        for i in range(4):
            q=[p, k, i]
            aa.append(np.sum(q))

dt=time.time()-t00
print('test: %.3f [s]' % (dt, ) )
```

**Comment by ccordoba12** [comment]
What's your Spyder version?

**Comment by eendebakpt** [comment]
I have just tested with spyder 2.3.6 (python3). The problem is still present, although less severe. In the code below the first block takes much more time when executed with ctrl-enter then the second block.

``` python
import time
import numpy as np
#%%
aa=[]
t00=time.time()
pp=np.arange(40)
for ii,p in enumerate(pp):
    for k in range(8):
        for i in range(4):
            q=[p, k, i]
            aa.append(np.sum(q))

dt=time.time()-t00
print('test: %.3f [s]' % (dt, ) )

#%%
def test():
    aa=[]
    t00=time.time()
    pp=np.arange(40)
    for ii,p in enumerate(pp):
        for k in range(8):
            for i in range(4):
                q=[p, k, i]
                aa.append(np.sum(q))
    
    dt=time.time()-t00
    print('test: %.3f [s]' % (dt, ) )    
    
    
test() 
```

**Comment by ccordoba12** [comment]
This is not a high priority because the IPython console doesn't have this problem. Please use that console instead :-)

**Comment by ccordoba12** [comment]
The Python console is going to be removed in Spyder 4. Please use the IPython console instead.

**Comment by paulmattheww** [comment]
@ccordoba12 -- how do you set the default such that you hit "CTRL+ENTER" to run code on the IPN console instead of the regular Python one? Can't find it in preferences.

**Comment by ccordoba12** [comment]
There won't be a need for that since Spyder 3.2 because the Python console will be removed in that version.

For previous versions there's no such option. Code is run in the console that has focus.
