### ISSUE TITLE
"Close all files" hangs Spyder

### ISSUE THREAD

**Issue by Diti24** [spyder-ide/spyder#2680]
## Description

**What steps will reproduce the problem?**

1. Try file close all

 

**What is the expected output? What do you see instead?**
Close all files but spyder hangs

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  None (NOK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  None (NOK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  0.25.1 (OK)

```

**Comment by ccordoba12** [comment]
According to what you reported on issue #2679, it seems you're using pyzo to run Spyder, and that's most probably what's causing the error.

Please use a more standard distribution, like Anaconda:

http://continuum.io/downloads.html

**Comment by H0R5E** [comment]
I'm have the same problem using the same version packaged with Anacoda, Python 2.7.

**Comment by ccordoba12** [comment]
I'll see what's happening about this one for 2.3.7

**Comment by ccordoba12** [comment]
I can confirm the bug. Sorry for closing it too quickly @Diti24 :-)
