### ISSUE TITLE
Strange editor autocompletion

### ISSUE THREAD

**Issue by Diti24** [spyder-ide/spyder#2681]
## Description

**What steps will reproduce the problem?**
1. Create a dummy package like this just to have something simple to play with, all listed files can be empty:
   myPackage/
   myPackage/util2
   myPackage/util2/util3File.py
   myPackage/util2/util2File.py
   myPackage/util2/**init**.py
   myPackage/util2/util1File.py
   myPackage/util1
   myPackage/util1/util3File.py
   myPackage/util1/util2File.py
   myPackage/util1/**init**.py
   myPackage/util1/util1File.py
   myPackage/util3
   myPackage/util3/util3File.py
   myPackage/util3/util2File.py
   myPackage/util3/**init**.py
   myPackage/util3/util1File.py
   myPackage/**init**.py
2. add the folder where the myPackage is located to the python path using the PATH_MANAGER
3. try to edit some import statements using the autocompletion of the user
   i.e. 
   from myPackage.util1 import util1File
   from myPackage.util1 import util2File

**What is the expected output? What do you see instead?**
I would expect the autocompletion works always however it works just for the first import statement

**Please provide any additional information below**
What is interesting and strange is that if I add a statment like this
import myPackage.util2 
at the begining i.e. not in the "from" form it seems that the auto completion works again in all lines.
## Version and main components
- Spyder Version: 2.3.6 
- Python Version: 3.4.3
- Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Linux
## Optional dependencies

```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  0.25.1 (OK)

```

**Comment by goanpeca** [comment]
@blink1073?

**Comment by blink1073** [comment]
I can't reproduce with the master branch:

<img width="516" alt="screen shot 2015-09-11 at 8 17 51 am" src="https://cloud.githubusercontent.com/assets/2096628/9815694/a49304cc-585d-11e5-9857-e83d40262596.png">

**Comment by blink1073** [comment]
Note this only works because these files are imported in the `__init__` files in the subpackage.

**Comment by Diti24** [comment]
You are right if you use some other packages like skimage or numpy it seems to work.
I tried to add the following initializations to my "dummy" package into the 
myPackage/__init__.py file:
from . import util
from . import util1
from . import util2
from . import util3

but this doesn't help. So I suppose my dummy package is wrong, since numpy, skimage and others work as expected.
On the otherhand if I do import mypackage then afterward if I do tab completion into the ipython console it works as expected but not in the editor...
![errore1](https://cloud.githubusercontent.com/assets/9540432/9846390/344b6f0c-5ad2-11e5-9079-7e557cda3599.png) What m I missing or doing wrong?

**Comment by blink1073** [comment]
The IPython console has the advantage of being able to evaluate everything, and in general can offer better introspection.

**Comment by ccordoba12** [comment]
Closing as this is a very old issue.
