### ISSUE TITLE
Figures don't show when using qt backend on Mac

### ISSUE THREAD

**Issue by amnona** [spyder-ide/spyder#2682]
When trying to use the qt backend for ipython (select via preferences), matplotlib figures don't show.
They work fine when using the "Automatic" backend instead.
This is not a general qt problem since calling "PyQt4.QtGui.QInputDialog.getInt(None,'a','b')" works.
The problem seems to be that figures are opened in the background but do not respond to events. When i call figure() and then plot(rand[5]), the figure doesn't show up (the window hides below and is empty). However, if i then call "PyQt4.QtGui.QInputDialog.getInt(None,'a','b')", the figure updates and i see the plot but cannot interact with it.
I am using spyder on mac osX 10.10.4 (Yosemite)
* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
How did you install Spyder?

**Comment by amnona** [comment]
Via anaconda

**Comment by ccordoba12** [comment]
Thanks for reporting. This is not a problem with Spyder but with Anaconda.

Fortunately I discovered the source of the problem, and right now I'm working to fix it. I'll let you know here when the fix is ready :-)

**Comment by ccordoba12** [comment]
The problem has been resolved in Anaconda. To get the fix please open a terminal and run this command:

    conda update ipython
