### ISSUE TITLE
IPython kernel crashes when using Qt dialogs in IPython Automatic backend in Mac

### ISSUE THREAD

**Issue by amnona** [spyder-ide/spyder#2683]
When using the automatic backend mode for the ipython console, opening a qt dialogue crashes the console.
steps:

```python
import PyQt4
PyQt4.QtGui.QInputDialog.getInt(None,'a','b')
```

and I get a "python quit unexpectedly." window with Ignore/Report/Reopen
(this also happens with a custom Qt GUI i'm working on instead of getInt)

(working on max OS X Yosemite 10.10.4
## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
This is not our fault. To run `PyQt4` code you need to select the right backend for the job. In Mac, this backend is **not** *Automatic* but *Qt*.

Besides setting a backend through our Preferences, you can also do it in an IPython console with this command:

    %matplotlib qt

or with this other

    %gui qt
