### ISSUE TITLE
Applications directory link is broken in Spyder 2.3.6 dmg's

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#2684]
As noted above - the executable works great, just the installer/dmg needs a tweak

**Comment by ccordoba12** [comment]
What tweak? Sorry, I don't understand :-s

Also, what version of Mac are you using?

**Comment by durack1** [comment]
Sorry I should have been more clear..

`OS X version: 10.10.5`

So the `Applications` icon within the installer is not correctly linked to `/Applications` on the machine, and consequently when trying to "install" spyder using the mounted `*.dmg` it doesn't work as expected.

And this is what I get:
![spyder2 3 6_dmg-applicationsdirissue](https://cloud.githubusercontent.com/assets/3229632/9773680/876b2494-56f8-11e5-859e-3649477a1016.jpg)

**Comment by ccordoba12** [comment]
Ok, I see what you mean. I'll try to fix it for 2.3.7.

**Comment by durack1** [comment]
@ccordoba12 just for completeness, the same issue is also apparent on `OS X version: 10.11.GM`

**Comment by ccordoba12** [comment]
I found the error and I'll fix it once I release dmg's for Spyder 2.3.7.

**Comment by durack1** [comment]
@ccordoba12 great, I can confirm that this is fixed in spyder-2.3.7-py2.7.dmg

**Comment by ccordoba12** [comment]
Great! Thanks for the confirmation @durack1 :-)
