### ISSUE TITLE
pulp package

### ISSUE THREAD

**Issue by achand11** [spyder-ide/spyder#2688]
## Description

**What steps will reproduce the problem?**

1. import pulp
x=pulp.LpVariable("x",lowBound=0)
y=pulp.LpVariable("y",lowBound=0)
problem=pulp.LpProblem("A simple maximization objective",pulp.LpMaximize)
problem+=3*x+2*y,"Objective function"
problem+=2*x+y <=100,"1st Constraint"
problem +=x+y<=80,"Second Constraint"
problem +=x<=40,"Third Constraint"
problem.solve()

2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies
```
IPython >=1.0   :  3.2.0 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  None (NOK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

```

**Comment by achand11** [comment]
I get error pulp package not available. Please let me know how I can install Pulp for spyder

**Comment by ccordoba12** [comment]
I'm sorry but this is not a Spyder bug. I haven't heard of that package, but according to his website, all you need to do is

    pip install pulp

in a terminal (i.e. `cmd.exe`)
