### ISSUE TITLE
Can't restart kernel or open a new console from spider

### ISSUE THREAD

**Issue by pichaio** [spyder-ide/spyder#2697]
## Description

**What steps will reproduce the problem?**

1. On IPython console, select restart kernel or open a new console.

**What is the expected output? What do you see instead?**
Kernel restarted or a new ipython console opened. Instead the following error appears.

Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
File "/Users/pichai/anaconda/lib/python3.4/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 175, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "/Users/pichai/anaconda/lib/python3.4/site‑packages/IPython/__init__.py", line 48, in 
from .terminal.embed import embed
File "/Users/pichai/anaconda/lib/python3.4/site‑packages/IPython/terminal/embed.py", line 16, in 
from IPython.core.interactiveshell import DummyMod
File "/Users/pichai/anaconda/lib/python3.4/site‑packages/IPython/core/interactiveshell.py", line 31, in 
from pickleshare import PickleShareDB
File "/Users/pichai/anaconda/lib/python3.4/site‑packages/pickleshare.py", line 41, in 
from path import path as Path
File "/Users/pichai/anaconda/lib/python3.4/site‑packages/path.py", line 122, in 
__version__ = pkg_resources.require('path.py')[0].version
TypeError: 'NoneType' object is not callable

**Please provide any additional information below**
I just updated all the apps (ipython-notebook to 4.0.4, ipython-qtconsole to 4.0.1 and Spider to 2.3.6) from the Launcher app. Then the problem occured.
Then I tried updating all packages using cmd conda update --all. Everything went fine. But the problem still persists.

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
This is the same problem as issue #2679, so I'm closing this one as a duplicate.
