### ISSUE TITLE
Spyder stop working when creating a small pandas.DataFrame in its IPython console

### ISSUE THREAD

**Issue by hankes-garden** [spyder-ide/spyder#2700]
I'm using the following installation:
Spyder2.3.6
Python 2.7.8 |Anaconda 2.3.0 (64-bit)| (default, Jul  2 2014, 15:12:11) [MSC v.1500 64 bit (AMD64)]
IPython 4.0.0

Each time I try to create a small pandas.DataFrame in IPython console, the IDE just stops working  for a long time without any response (it seems that it is executing this simple code for a really long time)
for a long time without any response.

For example, the following code can produce this bug:

In [1]: import pandas as pd
In [2]: import numpy as np
In [3]: df = pd.DataFrame(np.arange(12).reshape(3, 4)

**Comment by ccordoba12** [comment]
Thanks for reporting. This was already reported on issue #2654 and it'll be fixed in 2.3.7.
