### ISSUE TITLE
Open File Dialogue Incorrect Path

### ISSUE THREAD

**Issue by H0R5E** [spyder-ide/spyder#2704]
##  Description

The open file dialogue does not use the working directory path, instead using the path of the active file.

## What steps will reproduce the problem?

* Install Spyder 2.3.6 from Anaconda
* Start Spyder
* Select File -> Open... 
  
## What is the expected output? What do you see instead?

I expect the Open File dialogue to open at the working directory path, but instead it opens on the path of the currently selected file in the editor. The tooltip for the working directory path explicitly says the file explorer should correspond to the path set there.

![open_file](https://cloud.githubusercontent.com/assets/5088535/9988159/7af64630-604e-11e5-9bcd-6b6b41fc42b0.PNG)

**Comment by ccordoba12** [comment]
This is not a bug, just the default option. To change this behavior, please go to

    Tools > Preferences > Global working directory > Open file

and select the option called

    the global working directory

**Comment by H0R5E** [comment]
OK, thanks. Maybe the behaviour has changed since a previous version I am using.


Sorry for wasting your time!

Sent from Yahoo Mail on Android

**Comment by ccordoba12** [comment]
No problem :-)
