### ISSUE TITLE
MDSplus with Spyder

### ISSUE THREAD

**Issue by igoroleg** [spyder-ide/spyder#2707]
I am running Spyder coming with the Anaconda distribution on Mac. I had to install an extra package MDSplus. I can import and use the module in the terminal, but Spyder wouldn't load the module returning the error "Error importing MDSplus package: dlopen(libTreeShr.dylib, 6): image not found". PYTHONPATH was modified to let Python find the package: "../anaconda/lib/python2.7/site-packages".

**Comment by Nodd** [comment]
If you had to modify PYTHONPATH, there is something wrong with your installation. Also adding a relative path (starting with `../`) will cause you problems if you change you working directory. That may be the case here.

**Comment by igoroleg** [comment]
@Nodd This is true, MDSplus is a 3rd party package and does not come with Anaconda, hence all the trouble. The problem has just been solved. MDSplus requires an env. variable to be defined DYLD_LIBRARY_PATH="/usr/local/mdsplus/lib". The variable has to be defined in the environment where Spyder is being launched. So, the solution was to run Spyder from terminal rather than using the Anaconda's Launcher, making sure that DYLD_LIBRARY_PATH is defined.
