### ISSUE TITLE
Spyder crashes when closing editors in the variable explorer

### ISSUE THREAD

**Issue by paddyriyer** [spyder-ide/spyder#2708]
Whenever I click variable explorer the UI crashes on OS X El Capitan after clicking OK or cancel on the window pop-up. Attached is the screen shot.
<img width="497" alt="screenshot 2015-09-22 15 57 05" src="https://cloud.githubusercontent.com/assets/4563776/10034087/a178c3c4-6142-11e5-9e41-2733f7db5eb0.png">
<img width="975" alt="screenshot 2015-09-22 15 57 17" src="https://cloud.githubusercontent.com/assets/4563776/10034088/a19590e4-6142-11e5-8964-109e806ffad8.png">

**Comment by paddyriyer** [comment]
Any updates on this issue.

**Comment by ccordoba12** [comment]
Probably a Qt issue. Sorry, but none of us is using 10.11 right now.

**Comment by ycchuang** [comment]
It's wired that pressing the 'x' at the upper-left corner of the window won't lead to the crash.
You can temporarily press 'x' instead of "OK" or "cancel" for preventing the crash.^^

**Comment by paddyriyer** [comment]
@ycchuang I am not using Windows but using Mac. I don't see 'x' at the upper left corner.

**Comment by StefanD986** [comment]
Still present in Spyder 2.3.8
Can we (=affected users) provide anything that helps to fix the problem?

**Comment by ccordoba12** [comment]
Please update to our latest dmg (in case you're not using it). That could help to solve the problem.

**Comment by StefanD986** [comment]
I am using the latest dmg (Commit 01063bb), but the problem is still present.

**Comment by ccordoba12** [comment]
Sorry to hear that. I updated PyQt4 to its latest release hoping that 
that would solve this and other problems, but it seems that's not the case.

The only solution for El Capitan users appears to be to wait until 
Spyder 3 is released (in a couple of months), or revert back to Yosemite.

I know it's frustrating, but I hope you understand there's nothing else 
we can do about this in our side.

**Comment by ccordoba12** [comment]
This should be solved now in Spyder 3.0 because it uses Qt5.
