### ISSUE TITLE
IPython console error when trying to use SymPy

### ISSUE THREAD

**Issue by daniel-234** [spyder-ide/spyder#2709]
## Description

**What steps will reproduce the problem?**

1. Opening an IPython Console
2. 
3. 

**What is the expected output? What do you see instead?**
I should see a console ready for input. 

Instead I see:
```
An error ocurred while starting the kernel
Traceback (most recent call last):
  File "C:\Users\Dani\Anaconda3\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 169, in 
    ipk_temp.config = kernel_config()
  File "C:\Users\Dani\Anaconda3\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 119, in kernel_config
    lines = sympy_config(mpl_backend)
UnboundLocalError: local variable 'mpl_backend' referenced before assignment
```

**Please provide any additional information below**
I have Anaconda installed as default Python installation. At the beginning it was working well. 
I noticed some problems last days, as I opened Spyder after I already had some Jupyter Notebooks open and running in a separate virtual environment. 
Now my IPython console is not working, while the normal console is working correctly. 

![ipython console error message](https://cloud.githubusercontent.com/assets/10324072/10042938/3acd7cf2-61ef-11e5-873f-9c5dede586b5.jpg)

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by petebachant** [comment]
I am getting a similar error on Linux (all libs updated as of today via conda). This occurs when restarting an existing or opening a new IPython console. It does not occur on a fresh restart of Spyder.

```bash
An error ocurred while starting the kernel
Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
File "/home/pete/anaconda3/lib/python3.4/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 175, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "/home/pete/anaconda3/lib/python3.4/site‑packages/IPython/__init__.py", line 48, in 
from .terminal.embed import embed
File "/home/pete/anaconda3/lib/python3.4/site‑packages/IPython/terminal/embed.py", line 16, in 
from IPython.core.interactiveshell import DummyMod
File "/home/pete/anaconda3/lib/python3.4/site‑packages/IPython/core/interactiveshell.py", line 31, in 
from pickleshare import PickleShareDB
File "/home/pete/anaconda3/lib/python3.4/site‑packages/pickleshare.py", line 41, in 
from path import path as Path
File "/home/pete/anaconda3/lib/python3.4/site‑packages/path.py", line 123, in 
__version__ = pkg_resources.require('path.py')[0].version
TypeError: 'NoneType' object is not callable
```

**Comment by ccordoba12** [comment]
Thanks for reporting. I'll take a look at it for 2.3.7

**Comment by ccordoba12** [comment]
@petebachant, your error is totally different from the one reported by @daniel-234. Please **don't** mix things for next time. It just makes me waste my time :-)

Please refer to issue #2679 for a fix.

**Comment by petebachant** [comment]
My fault, sorry!

**Comment by nicholas-roy** [comment]
I had the exact issue as daniel-234 and was able to fix it by going to Spyder -> Preferences -> Console -> External Modules and changing the "Qt-python bindings library selection: " to "Default Library"

Hope that helps!
