### ISSUE TITLE
Copy text misses last highlighted character in IPython console

### ISSUE THREAD

**Issue by chrisjcameron** [spyder-ide/spyder#2710]
## Description
Copying highlighted text from the iPython console fails to capture last highlighted character.

**What steps will reproduce the problem?**

1. Copy text from Spyder iPython console using keyboard shortcut or context menu. 
2. Paste into editor or another program.
3. Note the last character is missing.

**What is the expected output? What do you see instead?**

I would expect all the text to be copied.

**Please provide any additional information below**

Copy (Raw Text) does not have this issue. 

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  1.0.0 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  3.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by chrisjcameron** [comment]
Looking over the marked duplicates, it seems to happen on Mac OS X and Ubuntu.

**Comment by rubennj** [comment]
This issue is coming from the qtconsole: jupyter/qtconsole#48

It is quite anoying BTW!

**Comment by ccordoba12** [comment]
@rubennj, thanks for letting us know that this is an upstream bug :-)

**Comment by bergtholdt** [comment]
the fix is simple and obvious:

in frontend_widget.py, def copy(self): (around line 208)

change this
```
                was_newline = text[-1] == '\n'
                if not was_newline: # user doesn't need newline
                    text = text[:-1]
```
to this
```
                was_newline = text[-1] == '\n'
                if was_newline: # user doesn't need newline
                    text = text[:-1]
```

if someone could format a pull request. I'm in a rush right now.

**Comment by ccordoba12** [comment]
I'll do it @bergtholdt, thanks a lot for your contribution! :-)

**Comment by ccordoba12** [comment]
Thanks to @bergtholdt help, this was fixed in jupyter/qtconsole#59.

It'll be released in qtconsole 4.1, so there's nothing else for us to do but wait for it :-)

**Comment by chrisjcameron** [comment]
This issue is indeed resolved with the last update.

**Comment by stonebig** [comment]
hi. small comment: I don't see it in today master tree on Windows.

**Comment by ccordoba12** [comment]
@stonebig, this was not fixed in Spyder but in qtconsole, so please be sure that you're using the latest qtconsole package.

**Comment by stonebig** [comment]
yes, I was on qtconsole 4.2.0
