### ISSUE TITLE
Restart kernel for IPython console changes Enter behavior

### ISSUE THREAD

**Issue by silentquasar** [spyder-ide/spyder#2711]
When I first launch Spyder, I can enter a command in the IPython Console using the Enter key. However, if for some reason I have to restart the kernel, when the new kernel starts, Enter now inserts a line break (I get the continuation '...:'). Shift+enter then can be used to execute the command. This is fairly annoying.

Environment:
- python 2.7.10
- spyder 2.3.6
- ipython 4.0.0
- Windows 7 x64 Miniconda install

**Comment by ccordoba12** [comment]
Closing as a duplicate of issue #2696.

**Comment by silentquasar** [comment]
Glad I could contribute details. =)
