### ISSUE TITLE
Fail to import FreeCAD

### ISSUE THREAD

**Issue by Pinnacleman** [spyder-ide/spyder#2714]
Hi,

I'm having problem importing FreeCAD from Spyder python/ipython consoles. It always failed with error:
ImportError: DLL load failed: The specified procedure could not be found. But I can import FreeCAD from an independent python console.

Since FreeCAD package is located on another drive, I have to tweak sys.path and append the FreeCAD package location to the sys.path. After the tweak, FreeCAD can be imported from an independent python console while failed with above error when importing from consoles in Spyder.

I searched web and found that this may be a long standing issue, which may be partially solved for Spyder. 

My system: Sypder installed with Anaconda and just updated to 2.3.6. I'm running Windows 7 64-bit. Python version is 2.7.8.

Thanks,

John

**Comment by ccordoba12** [comment]
I don't know how to help you, sorry.

**Comment by Nodd** [comment]
Try to modify the path at the top of your script:
```
import sys
sys.path.append("/path/to/freecad")
```
This may not be the best solution, but it should work.

**Comment by ccordoba12** [comment]
Closing as this is not a Spyder bug.
