### ISSUE TITLE
Object Inspector textfield not editable after inspecting an object

### ISSUE THREAD

**Issue by rthouvenin** [spyder-ide/spyder#2715]
To reproduce:

 1. Open spyder
 2. Type some valid python in the editor, e.g. `import time`
 3. Move the text cursor on a python object and press <kbd>Ctrl+I</kbd> to see the object documentation in the object inspector

The documentation (if available) is displayed as expected, but the text field of the Object Inspector becomes not editable. The dropdown arrow next to it disappears and it is not possible to type in the text field.

The problem does not occur when pressing <kbd>Ctrl+I</kbd> from the console. Moreover, once the text field is not editable and one inspects an object from the console, the text field becomes editable again.

I reproduce the issue in Spyder 2.7 and 3.0.0dev.

**Comment by rthouvenin** [comment]
If I understood correclt, the code doing this is in inspector.py:

    def source_changed(self, index=None):
        if self.source_is_console():
            # Console
            self.combo.show()
            self.object_edit.hide()
            self.show_source_action.setEnabled(True)
            self.auto_import_action.setEnabled(True)
        else:
            # Editor
            self.combo.hide()
            self.object_edit.show()
            self.show_source_action.setDisabled(True)
            self.auto_import_action.setDisabled(True)

It looks like this is the intended behavior, more than a bug. Can someone explain why?

**Comment by ccordoba12** [comment]
That's right: it's the intended behavior because we can't introspect objects present in the Editor without knowing their exact position on it (i.e. row and column)

So the field is active only when you introspect objects in the console because there we can just import the object and call for its `__doc__` attribute.

**Comment by rthouvenin** [comment]
Ah ok. I understand the limitation but I had never thought of typing an editor variable in the text field, only a full path. But it is true that it would be confusing that in one case (editor) you have to type a full path and the other (console) you don't. Thanks, closing the issue.
