### ISSUE TITLE
Enhancement: Different level of cell comment

### ISSUE THREAD

**Issue by spacegoing** [spyder-ide/spyder#2719]
I have a suggestion. Like in emacs' org mode, if u write * it means root level, ** means *'s children namely the second level, **** means the third etc.  Can we have a feature like this:

#%% Outer loop

    #%%% inner loop1
        do something

    #%%% inner loop2

        #%%%% inner inner loop3
            do something

        do something

When you select the parent level, all its descendants level will be activated. this feature would be really helpful when developing.

Also, it would be nice if the comment in different level have different color like in emacs

**Comment by ccordoba12** [comment]
It seems too complex for my taste, and not easy to make it work right.

**Comment by spacegoing** [comment]
@ccordoba12 Never mind. But would u plz tell me in which file u implement the cell comment function? May be I can do something fit my own taste:P

**Comment by Nodd** [comment]
For reference, we had a discussion about a similar thing in #2384.

**Comment by goanpeca** [comment]
I am :-1: on this

**Comment by spacegoing** [comment]
Anyway not interested. I don't use spyder anymore.
