### ISSUE TITLE
Spydata import error - Corrupted installation or a real issue?

### ISSUE THREAD

**Issue by asraelis** [spyder-ide/spyder#2723]
## Description
Cannot reload spydata file ==> "Import data - Unable to load 'F./...' Error message: 'charmap' codec can't decode byte 0x9d in position 372: character maps to"

**What steps will reproduce the problem?**

1. I am running spyder 2.3.5.2 on win7x64 
2. Variable Explorer ==> "Save data as" 
3. Variable Explorer ==> "Import data" 

**What is the expected output? What do you see instead?**
I want to reload the variables from a certain session. 
In the containing folder a *.pickle and two *_000?.npy files are created.

**Please provide any additional information below**
I have a version of spyder on my laptop running on win10 spyder 2.3.6 where the export and import is working.
There I can open the *.spydata file.

## Version and main components
Spyder was installed with Anaconda.

* Spyder Version: 2.3.5.2 
* Python Version: 3.4.3
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies
```
pyflakes >=0.6.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.2.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```
BR stephan

**Comment by ccordoba12** [comment]
Please give us a simple and reproducible test file we can use to fix this problem in our side

**Comment by asraelis** [comment]
Hey  ccordoba12,

The thing is it is not actually the excecuted script which generates this issue. The problem occurs everytime I am importing a *.spydata file. It seems that the saving of the variables by clicking on "save data as" on my desktop (where the problem occurs) is working since I am able to open stored *.spydata files on my laptop for instance.

BR stephan

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification :-)

**Comment by asraelis** [comment]
The issue dissappeared by updating to spyder 2.3.7 with conda gui

BR Stephan

**Comment by ccordoba12** [comment]
Great to know.
