### ISSUE TITLE
Windows: Workspace placed on rootdir loses pathinformation

### ISSUE THREAD

**Issue by Tillsten** [spyder-ide/spyder#2726]
This is quite a strange bug, i created a workspace under `D:\` and imported a existing directory into it (`matplotlib`). Now everytime i restart spider is lose the first char of the directory name, after three restarts it is now `plotlib` and doesnt work anymore.  Cause is properly forgetting to use raw string with windows paths.

**Comment by ccordoba12** [comment]
This is a very strange bug indeed. We'll what we can do about it.

**Comment by Tillsten** [comment]
This Bug is quite old, i saw it already some year ago, but was working on networkdrives and blamed that. Now i am seeing the same on my local drives. What is quite irritating is that these wrong directorys are created too.

**Comment by goanpeca** [comment]
Additional to this, the new version of Spyder removed the concept of workspaces and introduced a new concept of projects.

**Comment by ccordoba12** [comment]
@goanpeca, please don't forget to remove milestones when closing issues :-)
