### ISSUE TITLE
Spyder stuck one of the previous states

### ISSUE THREAD

**Issue by Temmplar** [spyder-ide/spyder#2727]
Hello,
Spyder doesn't remember the previous state i.e. if when I have three edit panels opened at the start and I close one, then I close Spyder, at the next start Spyder loads the three panels state again, thus I guess it stuck on a previous state and can't save the new states.
Thank you,
George

**Comment by Nodd** [comment]
Try to reset spyder's preferences. On windows there is a shortcut in the start menu, or you can use the command `spyder --reset` in a terminal.

**Comment by ccordoba12** [comment]
This was already fixed in `master` and will be released in Spyder 3.0.

Sorry but we don't plan to fix it in the 2.3 series :-(

**Comment by Temmplar** [comment]
@Nodd Thank you the reset helped.
@ccordoba12 thank you, but this is a new problem, but it has been solved with reset.
