### ISSUE TITLE
Add the default format in dataframe editor to user preferences

### ISSUE THREAD

**Issue by benjello** [spyder-ide/spyder#2728]
The default format should be defined at out of the widget as [asked here](http://stackoverflow.com/questions/32438504/spyder-dataframe-editor-format?rq=1).

**Comment by ccordoba12** [comment]
Just for clarification: what do you mean by default format?

**Comment by benjello** [comment]
I would like to use the format %.10g instead  the format %.3g which is the default as can be seen in the picture below (from [here] (http://stackoverflow.com/questions/32438504/spyder-dataframe-editor-format?rq=1))


![image](https://cloud.githubusercontent.com/assets/1175927/10225528/81c6cf26-6863-11e5-87da-502ccd077172.png)

**Comment by goanpeca** [comment]
@benjello what we could do is add an entry in `spyder.ini`, so that the value used is remembered from then on on every other dataframe until changed.

I do not think that this should go in the preferences as it is very specific, and preferences should be general settings.

**Comment by benjello** [comment]
Good for me

**Comment by alexpetralia** [comment]
Was this ever resolved? I don't see a `spyder.ini`in the Anaconda folder.

**Comment by ccordoba12** [comment]
Pinging @jitseniesen, in case he wants to look at this one. It shouldn't be that hard to implement :-)

**Comment by randomgambit** [comment]
hello everyone. thanks for your great work! is this fixed already?

**Comment by Nodd** [comment]
No it's not, we're working for spyder 3.0 right now.
