### ISSUE TITLE
Find in files default include and exclude values should be empty!

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2730]
The find in files default exclude and include values should be empty? And offer a better way that having a predetermined list of defaults, like a pop up table or something more friendly for a GUI

include = .pyw?$|.ipy$|.txt$|.rst$
exclude = .pyc$|.pyo$|.orig$|.hg|.svn|\bbuild\b

![image](https://cloud.githubusercontent.com/assets/3627835/10229534/4f170d86-683e-11e5-9d62-e231d6053baa.png)

I was bitten by this by not finding stuff in a file named `build.py` due to the nature of the exclude list. I would take the build out at least.

@spyder-ide/core-developers ideas?

**Comment by ccordoba12** [comment]
I think we should use something like [grin](https://github.com/while0pass/grin) for more sensible defaults and better results.

**Comment by Nodd** [comment]
In the meantime, maybe replace `\bbuild\b` by `build` ?
