### ISSUE TITLE
spyder won't start

### ISSUE THREAD

**Issue by gitperson** [spyder-ide/spyder#2731]
Hello.

I've installed python xy 2.7.10 and when starting Spyder, the console appears for a split second and then disappears and Spyder never opens. I've tried reinstalling python xy, erasing the old Python 27 folder, updating my environment variable paths and deleting the spyder.ini files (all recommendations I've seen for this potential problem) and nothing has worked. I still have the same problem. Am desperate to get this working but can't find any other advice online. Can anyone provide some direction or potential solutions?

**Comment by ccordoba12** [comment]
Please open a terminal (i.e. `cmd.exe`), and run this command

    spyder --show-console

then try to see if there are any errors printed there. If that's the case, please write them here.

**Comment by gitperson** [comment]
I get the following.


![capture](https://cloud.githubusercontent.com/assets/14935024/10251497/550fabb6-68ee-11e5-8620-d3d34c5625b2.PNG)

**Comment by ccordoba12** [comment]
I think this is fixed by running

    easy_install pydicom

In any case, I'm closing this issue because it's not a Spyder problem, but a problem with Python XY, sorry :-)

**Comment by gitperson** [comment]
Thank you. This was the problem and solution.

**Comment by ccordoba12** [comment]
Glad Spyder is back normal for you now! ;-)

**Comment by AsifAhmad100** [comment]
Hello everyone

I have been using spyder for several months but suddenly it got stuck and cannot start from anywhere.
I have reinstalled anaconda but the problem still persists...
Whenever i enter the spyder command i get the following error

![capture](https://cloud.githubusercontent.com/assets/20512109/16908236/cab6cf2e-4c7e-11e6-9024-2fd236aa0c8c.JPG)

Please help me with this problem.........

**Comment by Nodd** [comment]
@AsifAhmad100 Please create a new issue with your specific problem, indicating your spyder and python versions, OS... (Just fill the provided template when creating the issue).

**Comment by rmterminator** [comment]
Hello, I am having this issue and I am not sure about what to do T.T
![spyder](https://cloud.githubusercontent.com/assets/18745956/17133347/32dda3cc-5358-11e6-8474-5201aa2d5315.PNG)

**Comment by Nodd** [comment]
@rmterminator Your issue is completely different, as shown by the last line of the error message. In your case you have to install `sympy` ( @ccordoba12 it's a hard dependency now ? )

**Comment by ccordoba12** [comment]
Nop, it isn't. This seems to me like a setuptools problem.

**Comment by rmterminator** [comment]
@Nodd  @ccordoba12  Thank you guys so much,  my problem is solved

**Comment by erictham** [comment]
Sometimes it happens due to parsing error in the .spyder.ini file. Delete the file.

**Comment by Shivu1042** [comment]
try this. It should work.
conda update --all
conda update spyder

**Comment by imma17** [comment]
i face this issue when i tried easy_install pydicom

![image](https://cloud.githubusercontent.com/assets/26846878/24584009/612f02b4-1790-11e7-9a01-fb91de7d0e60.png)

Can advise me? Thank you very much!

**Comment by navakatou** [comment]
I have the following 

albertnava@nava:~$ spyder --show-console
Traceback (most recent call last):
  File "/usr/bin/spyder", line 2, in <module>
    from spyderlib import start_app
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 13, in <module>
    from spyderlib.config import CONF
  File "/usr/lib/python2.7/dist-packages/spyderlib/config.py", line 433, in <module>
    subfolder=SUBFOLDER, backup=True, raw_mode=True)
  File "/usr/lib/python2.7/dist-packages/spyderlib/userconfig.py", line 111, in __init__
    self.load_from_ini()
  File "/usr/lib/python2.7/dist-packages/spyderlib/userconfig.py", line 150, in load_from_ini
    self.read(self.filename())
  File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
    self._read(fp, filename)
  File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: /home/albertnava/.spyder2/.spyder.ini
	[line 549]: 'editor/save/auto_set_to'


So If you could help with this problem. 
Thank you so much

**Comment by janheindejong** [comment]
Hi all, 

I have similar problem. After running spyder --show-console, I get the following: 

C:\Users\39798>spyder --show-console
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2220, in run_spyder
    main.setup()
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 946, in setup
    from xy.config import DOC_PATH as xy_doc_path
  File "C:\Python27\lib\site-packages\xy\config.py", line 40, in <module>
    CONF = UserConfig('xy', defaults=DEFAULTS, version=__version__, subfolder='.xy')
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 110, in __init__
    if version != self.get_version(version):
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 130, in get_version
    return self.get(self.DEFAULT_SECTION_NAME, 'version', version)
  File "C:\Python27\lib\site-packages\xy\userconfig.py", line 269, in get
    value = cp.ConfigParser.get(self, section, option, raw=self.raw)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 811, in get
    d)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 384, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 397, in _interpolate_some
    rawval = parser.get(section, option, raw=True, fallback=rest)
TypeError: get() got an unexpected keyword argument 'raw'

Any ideas on how to fix this?

**Comment by ccordoba12** [comment]
@janheindejong, you're using a very old version of Spyder. Please to our latest version and try again.

**Comment by abhishek-karande** [comment]
AttributeError: module 'html5lib.treebuilders' has no attribute '_base'
im having this error while launching spyder3

**Comment by ccordoba12** [comment]
@abhishek-karande, please read my last comment. Simply updating Spyder will fix this problem,

**Comment by tusharsingh62** [comment]
![screenshot from 2017-10-23 21 23 50]  ( https://user-images.githubusercontent.com/28837107/31898983-1a8fbaa8-b838-11e7-8077-9254d1b30e6d.png )
I got this error while entering the command 'pip install qtconsole'

**Comment by ccordoba12** [comment]
Pip is for experts, please use Anaconda.
