### ISSUE TITLE
Source nevigation shortcuts does not work when the source toolbar is closed

### ISSUE THREAD

**Issue by hankes-garden** [spyder-ide/spyder#2735]
When the source toolbar is closed, the shortcut assigned for source navigation is not working.

**Comment by ccordoba12** [comment]
What do you mean by *source navigation*? and what shortcut is that?

**Comment by hankes-garden** [comment]
Hi, @ccordoba12 ,

I mean the function for jumping between the code, like the "Go to the previous curse position" or "Go to last edit location".

The shortcut of these functions seems to be fine when the source toolbar is open, but if the source toolbar is closed (which is quite common for a small-screen user like me), the shortcuts do not wok any more.

**Comment by jnsebgosselin** [comment]
@ccordoba12 This is an old bug and I was not able to reproduce it, are you?

**Comment by ccordoba12** [comment]
I don't have time to test it but I trust your word for it.
