### ISSUE TITLE
Spyder hangs when creating an empty DataFrame on Python 2

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#2744]
This was reported on our mailing list by @pblelloch (I think). The code to generate the crash is:

```python
import pandas as pd
p=pd.DataFrame()
```

**Comment by ktownv** [comment]
I applied the fix to 2.3.7 and it worked for p=pd.DataFrame().   However, if you do:

p = pd.Timestamp(2015,11,12)

it still hangs

**Comment by ktownv** [comment]
This appears to be a problem with pandas 0.17.0.

>>> import pandas as pd
>>> p = pd.Timeseries(2015, 11, 12)
>>> p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pandas\tslib.pyx", line 339, in pandas.tslib.Timestamp.__repr__ (pandas\tslib.c:9660)
AttributeError: 'int' object has no attribute 'freqstr'

can fix in dicteditorutils.py by adding the following to value_to_display (along with the appropriate import statements at the top)

    if isinstance(value, Timestamp):
        return str(value)

however you might want to consider wrapping that function in a try block, as other objects may come along that crash it.

**Comment by ccordoba12** [comment]
@ktownv, thanks a lot for the suggestion! I'll apply it for 2.3.8 :-)
