### ISSUE TITLE
could  2.3.7  run on windows10 32bit ? 

### ISSUE THREAD

**Issue by cheny8907** [spyder-ide/spyder#2745]
I download anaconda ,spyder is 2.3.5 ,it works OK.
Then  I update all packages using "conda update --all",and spyder is updated to 2.3.7
Then when I run spyder ,it says "this version could not run on your machine"(just the meaning ,because i use a chinese version windows , the message is chinese)
My PC is windows10 32bit

**Comment by ccordoba12** [comment]
It should work if it was working before ;-)

Could you post an screenshot of the message you're seeing? I know it's in Chinese but I doubt it's generated by Spyder, so I don't know where it's coming from :-)

**Comment by cheny8907** [comment]
Thank you for your reply .Here is the screenshot
![image 1](https://cloud.githubusercontent.com/assets/11814698/10354481/d820ae8a-6d92-11e5-983f-5d7dfc0e82ee.jpg)

**Comment by eroicaleo** [comment]
Hi ccordoba12,

I am running spyder 2.3.7 in a windows7 32bit machine through anaconda. And I am seeing the similar issue as cheny8907.
spyder works fine for 2.3.6, but give me an error message when I run 2.3.7:
"/AppData/Local/Continuum/Anaconda/Scripts/spyder.exe: Bad file number"

Hi cheny8907,

If you want to revert back to 2.3.6, you could do:

```
conda remove spyder spyder-app
conda install spyder=2.3.6 spyder-app=2.3.6
```

**Comment by cheny8907** [comment]
Hi eroicaleo,
When I revert back to 2.3.6,it works.thank you

**Comment by cheny8907** [comment]
After I install pyside,it works fine
