### ISSUE TITLE
Auto-completion in spyder editor

### ISSUE THREAD

**Issue by muellerth** [spyder-ide/spyder#2751]
Hello, 

I have a problem with the auto completion in spyder. For example, in the Ipython console the following code leads to a suggestion of available commands:

![2015-10-09 12_19_05-ipython console](https://cloud.githubusercontent.com/assets/12936726/10391570/12ebc9e4-6e80-11e5-8c16-5c19efd19bfd.png)

Doing the same in the spyder-editior, nothing happens by pressing tab or ctrl+space. But when typing "np.", the auto completion works properly.

At the moment I use:
Sypder 2.3.7
Ipython 4.0.0
numpy 1.10
rope 0.9.4

but the issue was the same with: 
Sypder 2.3.5.2
Ipython 3.2.1
numpy 1.9.2
rope 0.10.2

Best regards!

**Comment by Nodd** [comment]
This is normal. In the console, the interpreter knows everything about the variable, while in the editor the program must guess from the code what type is the variable, which rope doesn't do very well. You can try to install jedi to improve this.
