### ISSUE TITLE
ipython console does not connect to kernel

### ISSUE THREAD

**Issue by amrit-poudel** [spyder-ide/spyder#2757]
This is related to issue #2754 , which is not resolved yet.

I tried changing the python executable in the advanced console setting, but that did not work.

I obviously tried changing the python interpreter after I made changes to the advanced console.

I am not sure what is going on.

**Comment by ccordoba12** [comment]
Please don't open new issue, just reopen the previous one.

**Comment by amrit-poudel** [comment]
Ok. sorry.
