### ISSUE TITLE
Enhacement: include SQLKit in spyder 

### ISSUE THREAD

**Issue by jamartinh** [spyder-ide/spyder#2764]
Hello, it would be very useful to include the sqlkit utilities into spyder.

Please see below:

* http://sqlkit.argolinux.org/index.html

**Comment by ccordoba12** [comment]
I'm sorry but Spyder is an IDE, not a package manager :-) So we're not going to implement this feature.

However, you can use [conda](http://conda.pydata.org/docs/) to create a package for SQLKit yourself, which then you could import from Spyder :-)

**Comment by jamartinh** [comment]
HI, I am afraid this is a misunderstanding.

SQLKit is a collection of GUI components to allow python IDEs to work
easily with data in SQL databases.  There are tons of IDEs with such a
feature.

So I don't really understand the point on closing this.

Best,
Jose




2015-10-13 17:04 GMT+02:00 Carlos Cordoba <notifications@github.com>:

> I'm sorry but Spyder is an IDE, not a package manager :-) So we're not
> going to implement this feature.
>
> However, you can use conda <http://conda.pydata.org/docs/> to create a
> package for SQLKit yourself, which then you could import from Spyder :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2764#issuecomment-147742962>.
>



-- 
/ .- .-.. .-.. / -.-- --- ..- / -. . . -.. / .. ... / .-.. --- ...- .
José Antonio Martín H. (PhD)           E-Mail: jamartinh@fdi.ucm.es
Computer Science Faculty               Phone: (+34) 91 3947650
Complutense University of Madrid       Fax: (+34) 91 3947527
C/ Prof. José García Santesmases,s/n   28040 Madrid, Spain
web: http://www.dacya.ucm.es/jam/
LinkedIn: http://www.linkedin.com/in/jamartinh (Let's connect)
.-.. --- ...- . / .. ... / .- .-.. .-.. / .-- . / -. . . -..

**Comment by ccordoba12** [comment]
Sorry, i thought you meant we should distribute it with Spyder.

I took a quick look at it and it seems to use PyGtk, which is incompatible with the toolkit we use (Qt).

I'll leave this issue open in case someone wants to tackle this because I don't think we're going to do something about it, sorry. We have a lot of other things to do first :-)

**Comment by jamartinh** [comment]
Yes I know, too many things.

Thanks for leaving it open, perhaps I can find some time to start working
on this line.

Best,
Jose

2015-10-13 22:01 GMT+02:00 Carlos Cordoba <notifications@github.com>:

> Sorry, i thought you meant we should distribute it with Spyder.
>
> I took a quick look at it and it seems to use PyGtk, which is incompatible
> with the toolkit we use (Qt).
>
> I'll leave this issue open in case someone wants to tackle this because I
> don't think we're going to do something about it, sorry. We have a lot of
> other things to do first :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2764#issuecomment-147835412>.
>



-- 
/ .- .-.. .-.. / -.-- --- ..- / -. . . -.. / .. ... / .-.. --- ...- .
José Antonio Martín H. (PhD)           E-Mail: jamartinh@fdi.ucm.es
Computer Science Faculty               Phone: (+34) 91 3947650
Complutense University of Madrid       Fax: (+34) 91 3947527
C/ Prof. José García Santesmases,s/n   28040 Madrid, Spain
web: http://www.dacya.ucm.es/jam/
LinkedIn: http://www.linkedin.com/in/jamartinh (Let's connect)
.-.. --- ...- . / .. ... / .- .-.. .-.. / .-- . / -. . . -..

**Comment by ccordoba12** [comment]
I gave some thought to this and we're definitely not interested in having support for SQLKit as part of Spdyer.

However, once Spyder 3.0 is released, you could develop an external, third-party plugin to support it if you want.
