### ISSUE TITLE
[Help]plugin installation

### ISSUE THREAD

**Issue by alabd14313** [spyder-ide/spyder#2768]
Hi!
Please help me, How to install plugins(autopep8 - line_profiler- memeory_profiler) in spyder.
I'm using arch linux and it's official spyder packages. Installation via pip has error in compatible version.

**Comment by ccordoba12** [comment]
The infrastructure in Spyder is not yet ready to do make this possible. I hope we can make it possible in Spyder 3.0 beta2 :-) but first we need to merge pull request #2362.
