### ISSUE TITLE
"run cell" does not work for a new ipython console until it has executed something else.

### ISSUE THREAD

**Issue by simonm3** [spyder-ide/spyder#2773]
Clicking "run cell" normally runs the cell in the ipython console.

With a new ipython console then nothing happens. However if you type something in the ipython console such as "a" and <enter>. Then click "run cell" and it works fine.

**Comment by ccordoba12** [comment]
I can't reproduce this bug. These are the steps I'm following:

1. Start Spyder
2. Create a new file with a cell in it.
3. Press *Run cell* (or `Shift+Enter`). The cell is ran.
4. Open a new IPython console.
5. Get back to the Editor
6. Press `Ctrl+Enter` again. Everything is working normally.

I think you're not going back to the Editor after opening a new console, and that's why you can't run cells.

**Comment by simonm3** [comment]
I have existing file open with cells are marked with #%% and highlighted in
yellow when selected.
Open a new console.
Click on the cells in the file and they highlight in yellow
 Press the "execute cell and move to next cell" button. The next cell is
now yellow but nothing appears in the ipython window.
Type anything in the ipython window and try the exec cell and move on. This
time it works.

Have updated to 2.3.7 and tried in python2 and python3. Have also turned
off my auto exec file in preferences and made no difference.

**Comment by ccordoba12** [comment]
Please tell us

1. What operating system are you on
2. What's your Python, Qt and PyQt versions.

**Comment by ccordoba12** [comment]
Info of point 2. is reported in

    Help > About Spyder

**Comment by simonm3** [comment]
[image: Inline images 1]
windows 10
Also if i click on the ipython console when it opens then it works fine. No
need to actually enter anything just a click.
But if I leave the cursor on the editor and click the run cell key then it
does not get sent to the ipython console.

**Comment by simonm3** [comment]
python 3.4.3 64 bit. qt 4.8.6, pyqt api v2 4.10.4. windows 10

**Comment by ccordoba12** [comment]
I'm afraid to tell you that we haven't tested Spyder on Windows 10.

If you're using Anaconda, there are some promising news. Qt and PyQt are 
going to be updated in a couple of weeks, which could fix these 
problems, but we don't know for sure.

If that's not the case, you should have to live with these bugs until 
Spyder 3.0 (expected by the end of the year :-)

**Comment by ccordoba12** [comment]
Is this fixed for you after upgrading to PyQt 4.11.4?

**Comment by simonm3** [comment]
yes
