### ISSUE TITLE
Spyder crashes on Windows 8

### ISSUE THREAD

**Issue by Antoniya** [spyder-ide/spyder#2775]
Hi, i am new to the python. While typing spyder command in command prompt, it doesnt respond mostly and sometimes the following dialog box appears.
![capture](https://cloud.githubusercontent.com/assets/15181640/10564317/8891a2c8-75af-11e5-9a64-76eaa59e4c93.PNG)
 it says the spyder crashed during last session. By refering others issues also i tried to start it but i couldnt and i am using windows 8 , downloaded 64 bit installer. Is there any solution for it?

**Comment by ccordoba12** [comment]
If you're new to Python, it's better for you to install a scientific Python distribution, like Anaconda or WinPython, which comes with Spyder and all the libraries it needs to function properly.

Please follow our installation instructions to do so:

http://pythonhosted.org/spyder/installation.html

**Comment by Antoniya** [comment]
I installed from Anaconda distribution only,http://continuum.io/downloads from this one

**Comment by ccordoba12** [comment]
Ok, then please open a terminal (i.e. `cmd.exe`), run this command

    spyder --reset

then this command

    spyder --show

and finally take a screenshot of the contents shown in the console and upload it here. That will help us to understand what's happening in your case.

**Comment by Antoniya** [comment]
I just uninstalled it again. I will install it now and notify you about the
progress.Thank you.

**Comment by ccordoba12** [comment]
Sorry, the second command is

    spyder --show-console

**Comment by Antoniya** [comment]
![spydercapture](https://cloud.githubusercontent.com/assets/15181640/10564548/c01330dc-75b8-11e5-9cc4-3bb54e828865.PNG)
This is the result of that execution of the command that you gave.

**Comment by ccordoba12** [comment]
Why are you using a console for Administrators? Please use a regular 
console and report back.

**Comment by Antoniya** [comment]
Hi , i downloaded 32 bit installer, spyder window started. I dont know why
64 doesnt supported eventhough my laptop is 64 bit os windows 8. And thanks
for help.

**Comment by ccordoba12** [comment]
Ok, I'm glad that you finally solved the problem :-)

**Comment by Antoniya** [comment]
☺

**Comment by benbendemo** [comment]
Hi,I run across the same problem with Antoniya.And my cmd execution is:

![spyder-show-console](https://cloud.githubusercontent.com/assets/4705587/18572830/3721206e-7bf1-11e6-9487-bb05fffca3e4.png)

I can use Anaconda/spyder well before,why suddenly "ImportError: cannot import name Process" came out?

**Comment by benbendemo** [comment]
@ccordoba12 hi,can you help figure this?really appreciate your work.

**Comment by ccordoba12** [comment]
Sorry, but I really don't know what can be happening in your case.

**Comment by Nodd** [comment]
@benbendemo Do you have a file in your PYTHONPATH named `multiprocessing.py` ? It would shadow python's module and make this error.
Also your error is completely unrelated to the initial report, please create a new one if you wish to continue talking about it, thanks.
