### ISSUE TITLE
Editor and IPython different code completion tool working

### ISSUE THREAD

**Issue by Temmplar** [spyder-ide/spyder#2781]
Editor window: if I write the a dot after any of pandas's object or after the pandas itself the editor drops up the object's methods as it usual, but sometimes writes no more information in the object inspector window.
Ipython windows: no methods after the dot, but shows all parameters/properties after I wrote manually the method's name.

Other: In preferences I set IPython to automatic import numpy/matplotlib, but always get error message:
'''Traceback (most recent call last):

  File "<ipython-input-2-3d5db3454687>", line 1, in <module>
    numpy.mean([1,2])

NameError: name 'numpy' is not defined
'''

**Comment by ccordoba12** [comment]
1.  > Ipython windows: no methods after the dot, but shows all parameters/properties after I wrote manually the method's name.

    This is a limitation of the libraries we use to do code completion on the Editor. We are investigating if we can improve the situation in the future on issue #2162.

2. Automatic imports only work for the IPython console and not for the Editor. However, that option was not working correctly in previous Spyder versions, so I'd advise you to update to our 2.3.7 version.

**Comment by Temmplar** [comment]
@ccordoba12 
> 1. This is a limitation of the libraries we use to do code completion on the Editor. 
> We are  investigating if we can improve the situation in the future on issue #2162.
Thank you, I am looking forward to this future option.
> Of course I tried it in IPython console, thus I will update and retry.

**Comment by Temmplar** [comment]
@ccordoba12 
**Update:** After the updating to 2.3.7:
```numpy.sum([1,2,3])
Traceback (most recent call last):

  File "<ipython-input-5-0b30bf70dda7>", line 1, in <module>
    numpy.sum([1,2,3])

NameError: name 'numpy' is not defined
```

**Comment by ccordoba12** [comment]
I'll check out. A couple of questions:

1. What operating system are you working on?
2. What's your Python version?

**Comment by Temmplar** [comment]
@ccordoba12 
Sorry for the insufficient info.
1. Ubuntu 14.04 LTS 64-bit
2. Python 2.7.10

**Comment by Temmplar** [comment]
@ccordoba12 
UPDATE: Thank you, spyder reinstall + numpy,matplotlib reinstall solved the problem
Thank you!

**Comment by ccordoba12** [comment]
Super!
