### ISSUE TITLE
Spyder freezes on assigning a fits table data

### ISSUE THREAD

**Issue by elinor-lev** [spyder-ide/spyder#2783]
## Description

Apfter successfully importing a fits table with pyfits, Spyder freezes (100% CPU) when assiging the table data to a variable.
**What steps will reproduce the problem?**

1. open spyder
2. Run these lines:

```python
from astropy.io import fits as pyfits
f = pyfits.open('morphtable.fits')
tbdata = f[1].data
```

**What is the expected output? What do you see instead?**
expect to have a new ndarray tbdata contain 500 lines and 300 columns and get prompt back after few seconds.
Instead do not get prompt back, CPU runs at 100% and memory allocation gets increased.
Even if it occasionally manages to assign it, Spyder runs very slowly afterwards (few seconds after just hit 'enter').

**Please provide any additional information below**
This works perfectly from a simple ipython console outside spyder.
This only happens in MAC OSX 10.10.5, it worked fine in another spyder installation on Linux.

## Version and main components

* Spyder Version: 2.3.7 
* Python Version: 2.7.10
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.16.2 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
A couple of questions:

1. Could you upload somewhere a `fits` file to test this use case in our side?
2. `tbdata` should be an `ndarray` or a subclass of it?

**Comment by Nodd** [comment]
Also, could you try closing the variable explorer pane ?

**Comment by elinor-lev** [comment]
Closing the variable explorer indeed solved the issue! Thanks!

I attach it here just in case.

**Comment by ccordoba12** [comment]
@elinor-lev, It seems Github doesn't receive attachments. Could you upload it somewhere else?

**Comment by elinor-lev** [comment]
Sure, you can find it here:
https://www.dropbox.com/s/gz1t0jkeu61jddk/morphfile.fits?dl=0

**Comment by ccordoba12** [comment]
Thanks :-)
