### ISSUE TITLE
search cursor error help

### ISSUE THREAD

**Issue by gitperson** [spyder-ide/spyder#2796]
I recently installed ArcGIS 10.3.1 (previously had 10.1 installed) and I am trying to run a script in Spyder 2.7 that has always worked and getting the below error: 
"Traceback (most recent call last):

  File "<ipython-input-4-95832f8a9f6d>", line 1, in <module>
    perimCur = arcpy.SearchCursor(subwatSubPath + subwatPerimsSub[i])

  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\arcpy\arcpy\__init__.py", line 1179, in SearchCursor
    return gp.searchCursor(dataset, where_clause, spatial_reference, fields, sort_fields)

  File "C:\Program Files (x86)\ArcGIS\Desktop10.3\arcpy\arcpy\geoprocessing\_base.py", line 359, in searchCursor
    self._gp.SearchCursor(*gp_fixargs(args, True)))

RuntimeError: ERROR 999999: Error executing function."

I've tried reinstalling both ArcGIS and Spyder xy, but am still getting the same errors. After looking online, I can't find a solution, although I suspect it may be a path issue. Can anyone help me identify the problem?
I don't know if this is related, but when I import from the spatial analyst module by calling "from arcpy.sa import *" I get a warning that states "unable to detect undefined names".

**Comment by ccordoba12** [comment]
I'm sorry but this is clearly an error with ArcGis, not with Spyder, so we can't help you with this.

I'm closing this issue because of that.
