### ISSUE TITLE
Add "Open an iPython console" to Consoles drop-down

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#2797]
Please consider adding the "Open an iPython console" to the Console drop-down in Spyder 3.0 - it's something I'm really missing in the current beta1!

**Comment by ccordoba12** [comment]
Could you post a screenshot of what you want exactly?

**Comment by durack1** [comment]
Sure, so the screengrab and composite below should explain what I was hoping for - behavior more similar to Spyder2 in the upcoming Spyder3..
![151104_spyder3_ipythonconsolerequest](https://cloud.githubusercontent.com/assets/3229632/10954365/cc05d74a-8301-11e5-8821-9adeb09bb013.png)
I also have some comments regarding the drop-down ordering and how things could be rearranged to make it more intuitive.. But that's another issue..

**Comment by ccordoba12** [comment]
The menu entry doesn't appear because you don't have the right IPython/Jupyter version installed in your system.

Spyder 3 only works with IPython equal or greater than 3.0 or Jupyter qtconsole equal or greater than 4.0. Please take a look at

    Help > Optional Dependencies

to see what versions you have installed.

**Comment by durack1** [comment]
@ccordoba12 looks to me like it's a duplicate of https://github.com/spyder-ide/spyder/issues/2699 - I have `iPython 3.0.0` installed but Spyder shows `3.0.0 (NOK)`
