### ISSUE TITLE
Graphs or plots dont show

### ISSUE THREAD

**Issue by cyrilfurtado** [spyder-ide/spyder#2804]
## Description

**What steps will reproduce the problem?**

1. create any graph
2. do plt.show() nothing turns up
3. It used to work earlier

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Mac OS X
Docking of windows should be intutive

## Version and main components

* Spyder Version: 2.3.7 
* Python Version: 2.7.10
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
I don't understand what you're doing exactly. Please paste the code you're trying to run and tell us if you're using the Python or IPython console.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
