### ISSUE TITLE
Run cell buttons or shortcuts are not working

### ISSUE THREAD

**Issue by bubbalouie747** [spyder-ide/spyder#2806]
Neither the spyder interface buttons, nor the hotkeys, are functioning for the 'run current cell', 'run current cell and go to the next one', or 'run again last line'. I am using the latest Spyder interface with Python 3.4 on a Mac iOS X Yosemite. 

Run settings are set to the current .py document, and 'execute in current python or ipython console' is selected.

**Comment by ccordoba12** [comment]
I don't know how to help you because I can't reproduce this problem.

Please tell us at least what's your Spyder version and how you installed Spyder.

**Comment by ccordoba12** [comment]
This seems a duplicate of issue #2773.
