### ISSUE TITLE
Twitter API connect issues and other auth problems with Spyder and iPython

### ISSUE THREAD

**Issue by lyndbacon** [spyder-ide/spyder#2809]
I'm running Spyder 2.3.7 and iPython 4.0.0 as part of the distros Anaconda and Anaconda3 on Ubuntu 14.04 LTS.  The following code works with the Twitter search API  in iPython outside of Spyder, and in a python (but not iPython) console in Spyder, and using an Enthought Canopy distro.  But it doesn't work in iPython in Spyder.  The last statement causes the iPython session in Spyder to hang:

``` python
import twitter

def oauth_login():
    # XXX: Go to http://twitter.com/apps/new to create an app and get values
    # for these credentials that you'll need to provide in place of these
    # empty string values that are defined as placeholders.
    # See https://dev.twitter.com/docs/auth/oauth for more information
    # on Twitter's OAuth implementation.

    CONSUMER_KEY = 'XXXX'
    CONSUMER_SECRET = 'XXXX'
    OAUTH_TOKEN = 'XXXX'
    OAUTH_TOKEN_SECRET = 'XXXX'

    auth = twitter.oauth.OAuth(OAUTH_TOKEN, OAUTH_TOKEN_SECRET,
                               CONSUMER_KEY, CONSUMER_SECRET)

    twitter_api = twitter.Twitter(auth=auth)
    return twitter_api

WORLD_WOE_ID=1

world_trends=twitter_api.trends.place(_id=WORLD_WOE_ID)
```

When using iPython in Spyder, the last statement never returns, it just hangs the console session.  I have a similar problem when trying to connect to a remote MongoDB db.  In this case I can't authenticate a connection.  pymongo just gives up after a bit.  But I can for the same server using iPython outside of Spyder, and using a Enthought Canopy distro.  I don't have these problems when running Anacond iPython in Spyder on a Macbook Pro running OS X 10.11.1.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this for our next major release (i.e. Spyder 3.0).

**Comment by goanpeca** [comment]
I don't think this still applies. Closing.
