### ISSUE TITLE
tkinter treeview gives delayed events

### ISSUE THREAD

**Issue by adolfomaron** [spyder-ide/spyder#2811]
I am learning to use tkinter Treeview and tried to run an example found in the web. The code tries to react to a doble click on the tree. But the event passed to the callback function seems to be that corresponding to the previous doublé click so that you have to doublé click twice on a node to get the correct answer. The code is as follows:

import tkinter as tk
from tkinter import ttk
import time

class App:
    def __init__(self):
        self.root = tk.Tk()
        self.tree = ttk.Treeview()
        self.tree.pack()
        for i in range(10):
            self.tree.insert("", "end", text="Item %s" % i)
        self.tree.bind("<Double-1>", self.OnDoubleClick)
        self.root.mainloop()

    def OnDoubleClick(self, event):
        self.root.update_idletasks()
        item = self.tree.identify('item',event.x,event.y)
        print("you clicked on", self.tree.item(item,"text"),event.x,event.y)
        
if __name__ == "__main__":
    app = App()

**Comment by ccordoba12** [comment]
I'm very sorry, but this is not a Spyder bug or problem, so this is not the appropriate place to ask for help :-)

That's why I'm closing this bug. Besides, I don't have the expertise to tell how to solve it ;-)
