### ISSUE TITLE
Vista hanging

### ISSUE THREAD

**Issue by SamSxty** [spyder-ide/spyder#2816]
Can someone please direct me to the post on Vista?

I loaded WinPython 3.4.3.6 32 bit, loaded it to a flash drive and it worked in Win 7 however it hangs in Vista.  All I get is waiting circle icon.

Are there special instructions for running it in Vista, I haven't programmed in 20 years and want to try to use it in a safe manner so I found this package.  Eclipse was giving me a headache however even on Win 7 it takes a while to load from my flash stick.

I have Vista on a Dell Core Duo.  Even the IDLE that came with the package doesn't load.

Thanks for any help.  If there is a post that addresses this please direct me to it, I ran a search and found nothing on the 3.4.3 version, some posts on 2.7 versions.

**Comment by ccordoba12** [comment]
@stonebig?

**Comment by SamSxty** [comment]
Not sure what stonebig is.
I was able to get Spyder working on my Vista computer but not through the flash drive.  Are there path settings to allow it to run from a flash drive? or something to put into spyder.ini?

**Comment by ccordoba12** [comment]
@stonebig is the maintainer of WinPython. Please report this problem here:

https://github.com/winpython/winpython/issues

because it's not a Spyder bug but a WinPython one.

**Comment by stonebig** [comment]
hi @SamSxty,

Vista is probably no more supported by something.

You may have more luck trying  3.3.5.0 or down to 3.3.2.3
