### ISSUE TITLE
'import sitecustomize' failed; use -v for traceback with spyder 2.3.7 start

### ISSUE THREAD

**Issue by weitongwei** [spyder-ide/spyder#2818]
CentOs6.7,  python 2.7.10,
spyder 2.3.7 installed through pip.
Spyder always start with console error "'import sitecustomize' failed; use -v for traceback".
And run scripts give "NameError: name 'runfile' is not defined"

I tried stopping iptables sevice and setting SELINUX to permission.  But errors stay.

**Comment by ccordoba12** [comment]
This is a problem with Matplotlib 1.5, as reported in issue #2793.

It's going to be fixed in Spyder 2.3.8.

**Comment by weitongwei** [comment]
I see. Thanks.
