### ISSUE TITLE
Spyder won't connect to kernel / iPython console

### ISSUE THREAD

**Issue by garyspatterson** [spyder-ide/spyder#2821]
Since my laptop crashed (for unknown reason) last night, Spyder has not been able to connect to a kernel. I am getting this error:

raise IOError("Could not find %r in %r" % (filename, path)) IOError: Could not find u'kernel-1809.json' in ['.', '~/Library/Jupyter/runtime']

(The name of the json file changes each time I attempt to launch an iPython console.)

This does not seem to be related to the matplotlib 1.5 issue, that I have seen elsewhere on here - it is using 1.4.3.

iPython (version 4.0.0) runs fine from the command line.

Mac 10.10.1 (Yosemite). Spyder 2.3.7. Python 2.7.10 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.3 on Darwin

**Comment by garyspatterson** [comment]
UPDATE:

** Further update **

I deleted all files under the .spyder2/ folder in my user directory, reopened Spyder, and it was able to connect to an iPython console. So far, so good. Trouble is, when I added a path to the PYTHONPATH manager (so I could import external modules, such as nltk), I am back to getting the same error.

**Comment by ccordoba12** [comment]
You shouldn't do that. Please see this answer on how to use an external interpreter:

http://stackoverflow.com/questions/19795469/importing-arcpy-module-into-anacondas-spyder/19813292#19813292

**Comment by ccordoba12** [comment]
Closing, as this is not an Spyder bug :-)
