### ISSUE TITLE
Add Deque support on Variable Explorer

### ISSUE THREAD

**Issue by lkettle** [spyder-ide/spyder#2824]
![deque not showing](https://cloud.githubusercontent.com/assets/14791604/11317125/69ddfde0-8fef-11e5-9db5-426e054fb1b4.png)

Note that although I am working with the deque, it is not showing in variable explorer.
## Version and main components
- Spyder Version: 2.3.7 
- Python Version: 2.7.10
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux
## Optional dependencies

```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by lkettle** [comment]
I hit reset variables etc many times.  It never showed on any run.

**Comment by Nodd** [comment]
Deque are not supported by the variable explorer. You can show the name and type (but not the content) by enabling the unknown variables in the options.

**Comment by goanpeca** [comment]
@nodd we should at least support the additional collections in Python, besides they all follow a standard structure. We need a more flexible and extendable way of handling different things in the Variable explorer

**Comment by maurerle** [comment]
This old issue can not be reproduced.
The deque is shown in variable explorer:
![image](https://user-images.githubusercontent.com/25026204/165855842-773c5712-71b8-472a-9154-192f247711e0.png)

This issue can be closed.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
