### ISSUE TITLE
Spyder crash caused by ConfigParser.py

### ISSUE THREAD

**Issue by rjclement** [spyder-ide/spyder#2827]
Using Spyder installed as part of PythonXY package, on Windows 7_64.  Spyder crashes during initialization as the result of a TypeError (error trace shown below).   Print of the conf_file indicates it is in utf_8 format.  An identical error occurs when starting the PythonXY front-end and a similar error in another package was also found in another post (https://github.com/pubs/pubs/issues/27).  However Python (v2.7.10) can be started from the command line and other packages installed as part of PythonXY are not affected. Removal and re-installation (including .xy and .spyder2 folders and files in user sub directry)  did not resolve the problem.

    Traceback (most recent call last):
      File "C:\Python27\Scripts\xyhome.pyw", line 20, in <module>
        from xy import xyhome
      File "C:\Python27\lib\site-packages\xy\xyhome.pyw", line 60, in <module>    
        from xy.config import (CONF, STARTUP_PATH, LOG_PATH, PLUGINS, XY_VERSION,
      File "C:\Python27\lib\site-packages\xy\config.py", line 40, in <module>
        CONF = UserConfig('xy', defaults=DEFAULTS, version=__version__, subfolder='.xy')
      File "C:\Python27\lib\site-packages\xy\userconfig.py", line 110, in __init__
        if version != self.get_version(version):
      File "C:\Python27\lib\site-packages\xy\userconfig.py", line 130, in get_version
        return self.get(self.DEFAULT_SECTION_NAME, 'version', version)
      File "C:\Python27\lib\site-packages\xy\userconfig.py", line 266, in get
        self.set(section, option, default)
      File "C:\Python27\lib\site-packages\xy\userconfig.py", line 332, in set
        self.__save()
      File "C:\Python27\lib\site-packages\xy\userconfig.py", line 167, in __save
        self.write(conf_file)
      File "C:\Python27\lib\ConfigParser.py", line 407, in write
        fp.write("[%s]\n" % section)
    TypeError: must be unicode, not str

**Comment by ccordoba12** [comment]
What's your Spyder version?

**Comment by rjclement** [comment]
Taken from the spyder.ini file the version is either:

	version = '15.1.0'
	current_version = 2.3.5.2




On 23/11/2015 16:21, Carlos Cordoba wrote:
> What's your Spyder version?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2827#issuecomment-158985397>.
>


-- 
The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by rjclement** [comment]
I was able to obtain a working re-installation by deleting the C:\Python27 directory and the associated sub-directories left by non-pythonxy installed packages.  No registry changes were made and the Windows environment PATH settings were left as I had set them.

**Comment by wavemaking** [comment]
rjclement, Do you have an idea which package/file actually caused the problem? Did you remove many?

I have exactly the same problem here with spyder not starting and the same stack trace.

I have many updated packages compared to a default PythonXY installation. I'd rather not start completely from scratch.

**Comment by rjclement** [comment]
Sorry, I didn't keep a record of the packages.  I know there were some solar radiation modules (pyephemeral, pysolar or something like that).  Another one that caught my eye was actually called configparser.  The one that I suspect may have been the cause was mpltools which had a dependency on the configobj package.  Unfortunately I didnt try and remove these packages one at a time to try and identify the culprit.

**Comment by wavemaking** [comment]
Well, I figured it out myself. It was the xy package itself. I think this is part of PythonXY (as I cannot find it e.g. on pypi). All works well if I simply rename the package. Not sure if that bring trouble somewhere else, but we'll see...

**Comment by rjclement** [comment]
Odd, because I had uninstalled and reinstalled pythonxy (and also removed the ".xy" folder that it had created).  Also, when I ran spyder direct from command line I had the same error, and I didn't think that spyder had a dependency on pythonxy.   Anyway, I'm still not sure I am any clearer on the cause of the problem.

**Comment by gasuperdev** [comment]
'Fixed' by overriding `ConfigParser.RawConfigParser.write` in `xy.UserConfig` with.

```Python
    def write(self, fp):
        """Write an .ini-format representation of the configuration state."""
        if self._defaults:
            fp.write("[%s]\n" % cp.DEFAULTSECT)
            for (key, value) in self._defaults.items():
                fp.write("%s = %s\n" % (key, str(value).replace('\n', '\n\t')))
            fp.write("\n")
        for section in self._sections:
            fp.write("[%s]\n" % unicode(section, 'utf-8'))
            for (key, value) in self._sections[section].items():
                if key == "__name__":
                    continue
                if (value is not None) or (self._optcre == self.OPTCRE):
                    key = " = ".join((key, str(value).replace('\n', '\n\t')))
                fp.write("%s\n" % unicode(key, 'utf-8'))
            fp.write(unicode("\n", 'utf-8'))
```

That is, made explicit calls to unicode in what were lines 407, 414 and 415 of ConfigParser.py (and referencing `DEFAULTSECT` as `cp.DEFAULTSECT`).

Should probably move the string `'utf-8'` out to module level constant and try and get around referencing private (single '_') attributes of `ConfigParser.RawConfigParser`.

**Comment by ccordoba12** [comment]
@gasuperdev, please report your fix to the PythonXY developers. Thanks :-)

**Comment by YishGene** [comment]
This can be solved, if you are interested in a full reinstall, by manually deleting the Python27 directory in C: (worked for me, Windows 7 64 bit).

**Comment by dchap27** [comment]
@gasperdev, that fix worked with me. I hope things don't screw up
