### ISSUE TITLE
Spyder Does Not Launch

### ISSUE THREAD

**Issue by dadashek** [spyder-ide/spyder#2830]
Relatively new installation of Anaconda, try to launch Spyder, a command window opens and then it hangs and closes. 

Spyder was working fine for awhile.

**Comment by ccordoba12** [comment]
Please open a terminal and run this command:

    spyder --show-console

to see if there are some errors reported there.

**Comment by shubhanshu-gupta** [comment]
Hi,

Even I tried that. And I got the following series of errors on terminal. I have also checked for paths in my environment variables, and I guess they are rightly setup to F:\PythonIDE;F:\PythonIDE\Scripts;F:\PythonIDE\Library\bin;C:\Users\Shubhanshu\AppData\Roaming\npm 
Now, how should I proceed ahead with rectifying the error?
![image](https://cloud.githubusercontent.com/assets/4374028/11467066/c5e51938-976b-11e5-8b07-9c74382ba6cf.png)

**Comment by daqu3650** [comment]
I am also having issues launching Spyder, I figured I should report this error in the same thread.

Problem: Spyder fails to launch after update to Spyder 2.3.7

System Setup:
Windows 7 Professional (X64)
Python 3.4.3-4
Conda 3.18.6
Spyder 2.3.7

Steps Taken: Updated Spyder from Anaconda launcher. Spyder failed to open. Followed thread on /ContinuumIO/anaconda-issues#296 to determine that Spyder wanted PySide or PyQt4. Followed prompts and triage to point of running "conda install pyqt", which required me to update Python to 3.4.3-4 (did so).

Actions and Responses:
Launch Spyder from Anaconda Launcher - Goes through process (app launch box appears, cmd window opens, Spyder 2 loading box gets to "Loading editor"), then it stops.
Launch Spyder from cmd - Goes through process to "Loading editor", then dialogue appears saying "Python.exe has stopped working". Problem details at bottom of post.
launch "spyder --show-console" from cmd - same as before, no error information appears in console.

I will continue to triage on my own for the next few days, but I thought you should have an update on my process.

Thanks for your support!


Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	0.0.0.0
  Application Timestamp:	563e4f4d
  Fault Module Name:	QtGui4.dll
  Fault Module Version:	4.8.7.0
  Fault Module Timestamp:	56555f22
  Exception Code:	c0000005
  Exception Offset:	00000000004447af
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	43ff
  Additional Information 2:	43ffe1035ebd992cb94ffbbb38eb8c22
  Additional Information 3:	be27
  Additional Information 4:	be273b33c1a9b514f1e0a0b5564795cc

**Comment by ilovepandas** [comment]
I have identical issue to daqu3650.  Followed same step and similar results:

'python.exe has stopped working'

As above nothing appears in the console when launching spyder --show-console.

The text at the bottom of the Spyder load screen is always 'Loading IPython console...'

If I select 'Debug the program' in visual studio, I see if this means anything:

'Unhandled exception at 0x00000000645647AF (QtGui4.dll) in python.exe: 0xC0000005: Access violation reading location 0x0000000000000000.'

The call stack is:

>	QtGui4.dll!00000000645647af()	Unknown
 	QtGui4.dll!000000006458d616()	Unknown
 	QtGui.pyd!000007fec62c67b2()	Unknown
 	QtGui4.dll!000000006456483e()	Unknown
 	QtGui4.dll!0000000064590eb4()	Unknown
 	QtGui.pyd!000007fec62c63a8()	Unknown
 	QtGui4.dll!000000006458e9ce()	Unknown
 	QtGui.pyd!000007fec62cdd82()	Unknown
 	python34.dll!000000001db300ed()	Unknown
 	python34.dll!000000001dba481b()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba8918()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba8918()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba869c()	Unknown
 	python34.dll!000000001db1ab8d()	Unknown
 	python34.dll!000000001dae87e1()	Unknown
 	python34.dll!000000001db00c7d()	Unknown
 	python34.dll!000000001dae87e1()	Unknown
 	python34.dll!000000001db4b827()	Unknown
 	python34.dll!000000001db4770f()	Unknown
 	python34.dll!000000001dae87e1()	Unknown
 	python34.dll!000000001dba40e4()	Unknown
 	python34.dll!000000001dba488e()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba869c()	Unknown
 	python34.dll!000000001db1ab8d()	Unknown
 	python34.dll!000000001dae87e1()	Unknown
 	python34.dll!000000001dba443b()	Unknown
 	python34.dll!000000001dba6cde()	Unknown
 	python34.dll!000000001dba8918()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba869c()	Unknown
 	python34.dll!000000001dba898d()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba869c()	Unknown
 	python34.dll!000000001dba898d()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba8918()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba8918()	Unknown
 	python34.dll!000000001dba4881()	Unknown
 	python34.dll!000000001dba6c39()	Unknown
 	python34.dll!000000001dba869c()	Unknown
 	python34.dll!000000001dba8a3e()	Unknown
 	python34.dll!000000001dbe2863()	Unknown
 	python34.dll!000000001dbe3f35()	Unknown
 	python34.dll!000000001dbe5101()	Unknown
 	python34.dll!000000001dbe5cf3()	Unknown
 	python34.dll!000000001da8cdea()	Unknown
 	python34.dll!000000001da8d707()	Unknown
 	python.exe!000000001c8211ae()	Unknown

Any help would be much appreciated!

**Comment by R2Mark** [comment]
I'm having a similar problems starting Spyder.  In my case Spyder will start occassionally, but not consistently.  I have more trouble staring Spyder via the Anaconda links, but even starting from a command prompt with "spyder --show-spyder" does not always work.  When it does not start, I get a message stating that Spyder is already running, (see below).  I don't see how that can be though since Spyder was shut down normally the last time it was run, and was the very first thing I tried to start the next time the computer was turned on.

[py27] C:\Users\Ron>spyder --show-console
Spyder is already running. If you want to open a new
instance, please pass to it the --new-instance option

I'm running on Windows 7 Ultimate, (x64).  Python and Spyder version info is as follows:

pyqt                      4.11.4                   py27_4    defaults
python                    2.7.10                        4    defaults
pytz                      2015.7                   py27_0    defaults
pywin32                   219                      py27_1    defaults
pyzmq                     14.7.0                   py27_1    defaults
qt                        4.8.7                     vc9_5  [vc9]  defaults
qtconsole                 4.1.1                    py27_0    defaults
spyder                    2.3.8                    py27_0    defaults
spyder-app                2.3.8                    py27_0    defaults

**Comment by ccordoba12** [comment]
Closing because this bug is too old now.
