### ISSUE TITLE
Dicom plugin error in bootstrap.py

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#2836]
Having just pulled the latest master I'm getting the below error in the `bootstrap.py` script? Are others seeing this?
```
0x. Enforcing parent console (Windows only)
04. Executing spyder.main()
ERROR: 3rd party plugin import failed for `spyplugins.io.dicom`
Traceback (most recent call last):
  File "C:\Users\Dave\Code\spyder\spyderlib\otherplugins.py", line 74, in _import_plugin
    module = loader.load_module(name)
AttributeError: 'NoneType' object has no attribute 'load_module'
ERROR: 3rd party plugin import failed for `spyplugins.io.dicom`
Traceback (most recent call last):
  File "C:\Users\Dave\Code\spyder\spyderlib\otherplugins.py", line 74, in _import_plugin
    module = loader.load_module(name)
AttributeError: 'NoneType' object has no attribute 'load_module'
Bootstrap completed in 00:00:01.5320
```

**Comment by goanpeca** [comment]
What python version ?

**Comment by ccordoba12** [comment]
`dicom` was renamed to `dcm`. You just need to run:

    rm -R spyplugins/io/dicom

(or the Windows equivalent) to make the error go away :-)

----

@goanpeca, we need to add simple check in `_import_plugin` to avoid this error in the future. Could you take care of it?

**Comment by goanpeca** [comment]
@ccordoba12 Yep, will do, why was it renamed?

**Comment by ccordoba12** [comment]
@PierreRaybaut renamed it. I think he did it because the Python module to work with Dicom files changed its name.

**Comment by ccordoba12** [comment]
@goanpeca, could you do the PR tomorrow? I need this for beta2 ;-)

**Comment by goanpeca** [comment]
Give me a sec, will do it now

**Comment by ccordoba12** [comment]
Ok, thanks!

**Comment by PierreRaybaut** [comment]
@goanpeca, @ccordoba12 : I renamed the "dicom" to "dcm" to be coherent with the HDF5 plugin (package name fits the extension name, not the Python library name or the full format name) and above all to fix the ``AttributeError`` occuring in the plugin itself (when it tried to import ``dicom`` [the DICOM library], it was actually importing ``spyplugins.io.dicom`` instead... I think this bug has been there for a long time!).

**Comment by dhirschfeld** [comment]
Thanks @ccordoba12 - with the git tools installed that command worked just fine on windows!
