### ISSUE TITLE
After restarting Spyder PYTHONPATH changes to the list of identical entries self-referencing the project.

### ISSUE THREAD

**Issue by maciek-j** [spyder-ide/spyder#2839]
Observed on Spyder 2.2.5 and 2.3, Python 2.7.6 64bit Ubuntu Linux 14.04

I create to projects Test_1 and Test_2.
I set PYTHONPATH by right-clicking on Test_1 and choosing PYTHONPATH manager to the following state:
![screenshot from 2015-12-02 09 29 12](https://cloud.githubusercontent.com/assets/16114430/11526006/ba1f1c6c-98d7-11e5-9801-747eece0e5ca.png)
So I add several entries. After I restart Spyder and check PYTHONPATH of Test_1 (again by PYTHONPATH manager), I read:
![screenshot from 2015-12-02 09 30 00](https://cloud.githubusercontent.com/assets/16114430/11526027/d769585a-98d7-11e5-981d-aba5dca11235.png)
so all entries change to self referencing "Test_1"

**Comment by ccordoba12** [comment]
Closing because handle projects in Spyder 3.
