### ISSUE TITLE
Comments with # become illegible

### ISSUE THREAD

**Issue by dgoldsb** [spyder-ide/spyder#2842]
Since updating to Python 3.5.0 (Anaconda 2.4.0), any time I comment a line only a small selection of the characters in that line are displayed. Capital letters, vowel and non-letters are always omitted, but the remaining characters are not always displayed either. Initially I thought this was an option (to make comments more compact), but after browsing the options/google and asking around a bit it seems like it could be a bug?

**Comment by ccordoba12** [comment]
Could you post a screenshot of your problem and also tell us what platform are you working on?

**Comment by dgoldsb** [comment]
Of course! Platform is windows 10, images show what a line looks like commented and uncommented.

![image](https://cloud.githubusercontent.com/assets/14276775/11547402/c17debc4-9953-11e5-95d4-5ecf6ab8dbd1.png)
![image](https://cloud.githubusercontent.com/assets/14276775/11547410/d1d9be62-9953-11e5-80c9-82a4dd9aa66d.png)

**Comment by ccordoba12** [comment]
This clearly seems like a bug, but unfortunately i don't know why is happening :-s

What happens if you use a theme for the Editor with a white background?

**Comment by dgoldsb** [comment]
It is the same in all syntax highlighting themes, that is why initially I figured it was a new feature :-p

**Comment by ccordoba12** [comment]
Ok, thanks for checking that out :-) I'll work on it as soon as I can.

**Comment by goanpeca** [comment]
Is this still relevant @ccordoba12 ?

**Comment by ccordoba12** [comment]
I don't think so. No one else reported something like this afterwards.
