### ISSUE TITLE
Spyder won't connect to kernel / IPython console after switching to an external interpreter

### ISSUE THREAD

**Issue by icam0** [spyder-ide/spyder#2844]
So I just freshly installed th spyder dmg from this repository. When i switch to my standard python interpreter (/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7) however, the console keeps giving the message: Connecting to kernel. 

Things I have checked & run:

- I can run ipython from terminal
- I can use the iPython console in PyCharm using the SAME interpreter
- pip install jupyter -U
- I can import IPython from the regular 'console' in spyder.

I am currently on OS X el capitan.

**Comment by ewjoachim** [comment]
Backlink : I had this issue plus another one in #2846, in which I provide a workaround, it that helps.

**Comment by icam0** [comment]
Thanks, will look into it!

**Comment by ccordoba12** [comment]
Right now you need to have IPython and PyQt installed in your external interpreter for this to work.

In 3.0 this will be reduced to just having `ipykernel` installed, and we'll inform our users about it :-)
