### ISSUE TITLE
Comment out lines according to indentation

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2845]
# Description

Commented lines are commented always on column 0, no matter what the indent. This results in the fold detector "incorrectly" detecting a fold where lines are commented out. Although not really an issue I would suggest to adapt the code to comment lines (Comment/Uncomment Ctl+1) to put the '#' on the indented level. This would allow for much cleaner code (this is my opinion) and would eliminate this 'bug'.

**Comment by benjello** [comment]
I strongly support this addition. I enjoy very much spyder but the way it deals with comment is very annoying. May be you should consider also changing the shortcut to Ctrl-/ like in many other editors (atom, vscode, etc)

**Comment by ccordoba12** [comment]
This feature is (most probably) going to be addressed in Spyder 4.0

----

> May be you should consider also changing the shortcut to Ctrl-/

I don't think we're going to do that but you could easily change it in Spyder 3.1.
