### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by FrancisBurger** [spyder-ide/spyder#2848]
Somehow my I think Kernel broke... I uninstalled and then reinstalled Spyder 2.7 (Win 8.1) but the error is the same...
I hava no idea how to fix it.
The console says something like that:

'import sitecustomize' failed; use ‑v for traceback
Traceback (most recent call last):
File "C:\Users\name\Anaconda\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 186, in 
ipk_temp.config = kernel_config()
..... and so on

**Comment by ccordoba12** [comment]
Please update Spyder to 2.3.8 to see if that fixes the problem for you.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
