### ISSUE TITLE
Transform the Global Directory toolbar into a panel/plugin

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2849]
# Description
- The global directory toolbar is an odd duck with respect to the other toolbars.
- If working with the keyboard only and between different folders/projects, having to use the mouse to get to the toolbar is annoying
- Having a shortcut to get the focus of a toolbar seems like the wrong approach.
# Implementation

Mke the Global Directory a plugin panel (panes) and give it a `Ctrl+Shift+G` shortcut.

**Comment by goanpeca** [comment]
@Nodd , @ccordoba12 

@PierreRaybaut also it would be nice to hear your thoughts :-)

**Comment by ccordoba12** [comment]
+1 from me, as we have talked before with @goanpeca :-)

**Comment by PierreRaybaut** [comment]
As a developer, I don't have any objection regarding this change except that one must be cautious before/when creating a new global shortcut (is it really necessary? are there any side effects?).

As a user, I never use the Global Directory toolbar, so... I don't have any opinion on this, unless you take the time to list the use cases. Is it necessary to create a new plugin or adding a new shortcut to the Console (or to the IPython console) would suffice? (that is if you use the Global Directory from an already existing plugin)

**Comment by goanpeca** [comment]
@PierreRaybaut thanks for the feedback.

1. I would need to check on sideeffects on different OS just to be sure. Is it really necessary? Yes, all core panes for spyder (except the internal console) provide a shortcut, so it is a matter of coherence
1.  I sometimes use, sometimes I don't, depends on the workflow, but what is very frustrating in a "mouseless" environment is not being able to access the global working directory (toolbar) with a shortcut. That completely breaks the workflow.
1. The change is also more of a correctness issue; the global working directory is a hacked toolbar that has an entry in preferences (which was limited to panes ..) which feels simply wrong, and I believe adds to confusing a lot of users.
1. We are implementing a mode where dockwidget titlebars can be hidden, status bar can be hidden, and all toolbars can be hidden, and loosing the global directory seems like a no go and also reinforces the idea that it being a toolbar is the wrong way of doing it.
1. Users that dont directly use the global working directory still like to see what the GWD is, but it being a toolbar forces the users to always have that toolbar on, and in the process loose vertical real state.
1. Having as a workaround being able to access a toolbar with a shortcut is bad UI/UX design so this is not an option.

**Comment by goanpeca** [comment]
Probably needs rethinking
