### ISSUE TITLE
Add a goto line option in the editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#285]
_From [mproel...@googlemail.com](https://code.google.com/u/105494983286078857315/) on 2010-08-12T02:49:34Z_

Hi,

a goto line option for the editor would be very useful (+ shurtcut). This could help when debugging a file for instance. The pdb lists the line of the file where a breakpoint is encountered. That's why it would be useful to have the possibility of a goto line feature.
In addition would it be possible to highlight these breakpoint information and have a link to jump to the line in the editor (as it is done with the tracebacks)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=285_

**Comment by spyder-issues-migrator** [comment]
_From [mproel...@googlemail.com](https://code.google.com/u/105494983286078857315/) on 2010-08-12T08:09:06Z_

Hi,

and maybe add an option to preferences, that a goto command creates an entry to the goto previous cursor position, that when going to a line, you can go back to the previous position with CTRL+ALT+LEFT.
Maybe some users wouldn't like to have this behaviour, therefore an extra option could be useful

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-17T10:33:07Z_

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-20T11:00:51Z_

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-09-04T00:48:05Z_

issue #326 has been merged into this issue.

**Comment by Vaderv** [comment]
was this feature added ? 
Thank you
