### ISSUE TITLE
Reorganize repo: Move repo level scripts into /utils

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2851]
https://github.com/spyder-ide/spyder/repo/utils

**Comment by ccordoba12** [comment]
Just `/utils`, right?

**Comment by ccordoba12** [comment]
I mean, if `/` is the root of the repo :-)

**Comment by goanpeca** [comment]
Yes.... are you doing this ?

**Comment by ccordoba12** [comment]
I don't have much time right now. Could you do it?

**Comment by goanpeca** [comment]
Sure

**Comment by ccordoba12** [comment]
Closing, as we thinking to move most script out of the repo.
