### ISSUE TITLE
Spyder Debugging

### ISSUE THREAD

**Issue by freundzi** [spyder-ide/spyder#2857]
Hi, 
I'm new to spyder, so I'm sorry if the questions are silly, but this are things I couldn't find answers to yet -
1. Is there a way in the debugging to display the variables in the callback function, the same as in matlab ?
2. how can I tell , while debugging, if the console is busy ?
3. Is there a way to start the debugger at a certain line and not at the beginning of the file ?
4. How can I debug a function, that i call from the console ?
Thanks !

**Comment by ccordoba12** [comment]
My answers:

1. I don't know what you mean exactly by this. Could you clarify it a bit?
2. There's no way to tell if it's busy or not. We plan to fix that in a future release.
3. You need to set a breakpoint to do that (by double clicking on the line number area on a non-empty line). Then when you start your debugging session, the debugger will jump to your first breakpoint.
4. If you defined your function in the console itself, there's no way to debug it. Else you can call it on the debugger, as when calling it in the console.

**Comment by freundzi** [comment]
Thank you for the answers !
I'll try to be more specific. I am referring to the questions in the first post:
Q1. suppose I have the following code stored in the script temp.py
def Ziv ( x, y):
    print x+y
    
def callZiv():
    z=20
    zz=30
    Ziv (z,zz)    
    
callZiv()

I have a breakpoint in the function Ziv in the line print x+y. I want to know who called the function , and also wants to view variables values currently in the caller function(like zz). In matlab, you can see the entire call stack in a listbox, and you can select to change your scope, to the scope of any of the caller functions in the stack, and then the variable explorer will show you the values in the caller function you selected. This is very useful.

Q4. I mean for example, to debug a function in a script. Consider  again the example from Q1, 
I want to be able to write in the console :
callZiv ()
and if I have a breakpoint in print x+y, the debugger will stop. (When I try this the function is called in normal mode and not in debug mode, and the breakpoint is not activated). Is there a way to call the function in debug mode from the console ?
 
Thank you. sorry for many words, I hope it is more clear now.

**Comment by goanpeca** [comment]
@freundzi it would really help on our side, if you could style your comments using Github markdown.

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

Thanks

**Comment by ccordoba12** [comment]
@freundzi, thanks for the detailed answers. My answers:

For **Q1.**

1. You asked

    > I want to know who called the function

    I think this is not possible in Python. At least, I'm not aware of that functionality.

2. You also asked

    > [I] want to view variables values currently in the caller function(like zz)

    For that to happen you need to set a breakpoint inside `callZiv`, not in `Ziv`. When the debugger reaches that breakpoint, you need to focus our Variable Explorer, and you'll see what the values of `z` and `zz` are.

For **Q4.**: I think you're looking for something similar to `keyboard` in Matlab. There are some things like that in Python, but they don't work very well in Spyder.

**Comment by ccordoba12** [comment]
Also for **Q4**: there's no way to automatically enter a debugging session after creating a breakpoint and running a file.

In Python, running and debugging are two different operations, and can't be combined at all.

**Comment by Nodd** [comment]
For question 1 and 2, introspection capabilities from python should provide the information, but I don't know how in practice.

**Comment by Nodd** [comment]
For example: http://stackoverflow.com/questions/7272326/introspect-calling-object

But be aware that it can be implementation dependant. I'm not sure that it will work outside of CPython. See https://docs.python.org/3/library/inspect.html#inspect.currentframe

**Comment by ccordoba12** [comment]
Closing, as this was a request for help more than bug per se.

**Comment by wcipriano** [comment]
Cordoba, the debugger don't stop when the breakpoint is marked in the other file (not main file) that is called from the main. 
It is a bug ?
Or we can fit this behavior by changing configs ?
