### ISSUE TITLE
Flushing stoud in Spyder

### ISSUE THREAD

**Issue by jhcsu** [spyder-ide/spyder#2860]
Perhaps this is not an 'issue' (maybe it's even 'desired behavior'), but then again maybe it is.

If I have a simple program 

    import time
    print "start"
    time.sleep(3)
    print "done"
and run it in Spyder, I get a three second delay, and then see "start" and "done" printed virtually simultaneously.

However if I run this program in iPython directly (outside of Spyder), or using `python` from the command line, I see "start", a three second delay, and then "done".  For me, at least, this is the desired behavior.

I'm aware I can force the issue in Spyder using `import sys; sys.stdout.flush()` after the `print`.  However, without modifying my programs to insert the flush command, is there a way to get this same behavior in Spyder?

For what it's worth, calling `python -u` should do the same thing (but I'm not sure that helps here...)

**Comment by jhcsu** [comment]
I will add that I'm using Spyder 2.3.7 on OS X 10.10.5.

**Comment by ccordoba12** [comment]
@minrk, something about this can be done in qtconsole?

**Comment by jhcsu** [comment]
Ah, I should have tried it by opening qtconsole directly... indeed, that's where the issue is.  Technically, that's just qtconsole's behavior (not necessarily a bug).  Still, if there was a workaround that would benefit Spyder users, I'd love to hear about it.

**Comment by minrk** [comment]
I have a fix in mind that is rising in urgency that I'll try to get to this week or next. It should only require changes in `ipykernel`. There isn't a good workaround that I know of.

**Comment by ccordoba12** [comment]
@minrk, thanks a lot for letting us know about it :-)

Closing this then as it's not a Spyder bug.

**Comment by minrk** [comment]
ipython/ipykernel#85 is the PR
