### ISSUE TITLE
Problems with Turtle

### ISSUE THREAD

**Issue by Paste35** [spyder-ide/spyder#2865]
I just downloaded the latest version of SPYDER: 2.3.8 I had wanted to test out the turtle graphics, but when I typed in this code: import turtle
t = turtle.Pen()
for x in range(100):
        t.forward(x)
        t.left(90) 
and tried to save, an error popped up, saying:
 Unable to save script 'spiral.py'
Error message:
[Errno 30] Read-only file system: '/Volumes/Spyder/spiral.py'

Also should I have put the code in the lefthand box? If you can figure this problem out, then thank you in advance!

**Comment by Nodd** [comment]
You have to save the file in another directory, because you can't write a file where you tried to save it.
