### ISSUE TITLE
Animation problem with blit

### ISSUE THREAD

**Issue by maimonid** [spyder-ide/spyder#2869]
Hello, I'm new to GitHub (and somewhat to python). I'm not sure but I report what seems to be an issue for me. I am using Python 3.5.1 32bits Qt 4.8.7, PyQt4 (API v2) 4.11.4 on windows,  with the spyder I-python console 2.3.8, comming from the Anaconda installation which I have downloaded some days ago.
I have exactly the sames installations on my desktop computer and my leptop, and I have tried to run the attached python code taken from the Pyplot animation examples. On the desktop computer (native 32bit), it runs without problem, but on the leptop (native 64 bit), the animation does not work, unless I set the "blit" option to False in the animation.funcAnimation function (and then, the animation is somewhat slow). Attached is the code.

[double_pendulum_animation.txt](https://github.com/spyder-ide/spyder/files/62934/double_pendulum_animation.txt)

**Comment by ccordoba12** [comment]
You need to change the matplotlib backend to run animations, with

    %matplotlib qt5

in an IPython console.

Sorry for the (very) late response.
