### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by wombatonfire** [spyder-ide/spyder#2870]
Hi Spyder Team,

First, let me thank you for such a great tool! I am a happy Spyder user who got it as part of WinPython distribution. While I feel comfortable with English UI, I can think of other Russian-speaking users who would like to see localized interface.

So I wonder if you accept alternative localizations? If that is the case I will be happy to contribute.

**Comment by ccordoba12** [comment]
Yes, of course we accept them :-) You need to load the file called `spyderlib.pot`, located in `spyderlib/locale` and load it in a program to do translations (like `poedit` on Linux).

Currently we have translations for Spanish, French and Portuguese.

**Comment by wombatonfire** [comment]
That's great! Thank you for pointing to the `spyderlib.pot` file. I examined existing `.po` files in `spyderlib/locale/[es|fr|pt_BR]` but didn't notice the template. I was thinking about using pygettext.py to generate it from source.

**Comment by burrbull** [comment]
I partially translated spyderlib to Russian.
But I'm not professional translator, so:

https://drive.google.com/open?id=0B2MlVBZIcddKUS03NmpMb3kzNzg

**Comment by ccordoba12** [comment]
@burrbull, please create a translation file and a pull request to add it to our source tree

**Comment by ccordoba12** [comment]
This is already done. Closing.
