### ISSUE TITLE
Hide completion widget when scrolling up and down

### ISSUE THREAD

**Issue by carlosloslas** [spyder-ide/spyder#2871]
Hi all, 

Firstly well done for an awesome idea that i use a lot and has helped me code lots in python!

Going into the matter of this issue, i was coding the other day and i noticed that the completion boxes where floating as i would scroll to check the correct function to complete to. I am not sure if this is a feature or a bug. If its a feature so that you see the options as you scroll to check i would be good if the options didn't disappear. If its a bug and the box shouldn't move at all i thought i would report it. I enclose a figure of the matter.

Finally, does anybody have any suggestions as to how to help more than by just 'complaining' about what one has found not to be working as expected. I am not new to programming but mostly as a user.

![screen shot 2015-12-13 at 10 06 50](https://cloud.githubusercontent.com/assets/10100481/11840962/2e70f57c-a3fa-11e5-84c5-d217bdc91b5c.png)

**Comment by ccordoba12** [comment]
Are you using two monitors?

**Comment by carlosloslas** [comment]
No its all in my laptop, 
As for version of spyder and python i just checked that it is still happening nd took the screenshot bellow.

![screen shot 2015-12-16 at 15 27 42](https://cloud.githubusercontent.com/assets/10100481/11843414/c995474c-a409-11e5-82ff-55d68a25ab04.png)

**Comment by carlosloslas** [comment]
This problem isn't stopping me using Spyder or Python, so if i can not be replicated straightaway there isn't much point in having an open issue. I just thought to have it recorded somewhere in case this was something that hadn't been encountered before. And help, in a small way, with the development of a great project.

**Comment by ccordoba12** [comment]
I don't understand too well what you're doing. Could you give us a step by step way to reproduce your problem?

**Comment by carlosloslas** [comment]
Sorry should have added this at the top. Thankfully Spyder is quite good so I forget how issues should be reported.

1 In a new script, define a simple function:
```
def mysum(a,b):
    return a+b
```
2 Go down enough lines so that the script is long enough to scroll up and down. 

3 At the end, type ```m``` for 'mysum', and press tab. As the box with the list of options is displayed, scroll script up. 

The box will remain in the same position relative to the editor window, the scrip and the contents of the box move. As far as I think, the box shouldn't move up as I scroll; or the contents of the box should not change as I scroll. 

I hope this helps @ccordoba12

**Comment by ccordoba12** [comment]
Thanks for the detailed description. Now I understand what's happening :-)

The easiest solution would be hide the completion widget on scroll up/down events. Would that be ok for you?

**Comment by ccordoba12** [comment]
@dalthviz, please take care of this issue as part of PR #9897. The idea is that if the completion widget is currently visible and you scroll up or down with the mouse wheel, then we need to hide it.
