### ISSUE TITLE
variables missing in nest loop operations

### ISSUE THREAD

**Issue by hareyakana** [spyder-ide/spyder#2872]
grid=400
    P1=[]

    for i in range(grid+1):
        P1.append(i/grid)

    x=[]
    y=[]
    z=[]

    for j in range(len(P1)):
        for k in range(len(P1)):
            for l in range(len(P1)):
                if P1[j] + P1[k] + P1[l] == 1.0:
                    x.append(P1[j])
                    y.append(P1[k])
                    z.append(P1[l])

I'm making a ternary grid and I noticed that some of the coordinates were missing. I'm pretty sure the condition is right and I get random coordinates missing when I construct with different grid size

for example in a 400 grid size, an example of a missing coordinates were as below:-

    ....
    0.5025,0.29,0.2075
    0.5025,0.2975,0.2
    0.5025,0.3,0.1975
    ....

(0.5025,0.2925,0.205) and (0.5025,0.295,0.2025) were missing. Is this as intended?? Have tried both python console and python console both giving the same results

**Comment by goanpeca** [comment]
@hareyakana is this related to spyder?

Missing from where??
