### ISSUE TITLE
iPython Console "Connecting to kernel" error - Windows 7; Python 3.5.1 

### ISSUE THREAD

**Issue by alexedstrom** [spyder-ide/spyder#2880]
I'm upgrading to python 3.5.1 from python 2.11. I previously had a working build of Spyder for 2.x but now in upgrading to 3.5.1, I'm having trouble with the continuously loading kernel that's come up for others.

I've removed all previous 2.x python installs and am building from the ground up using pip (and wheel files as needed). 

Here are my components:
IPython >=1.0      :  4.0.1 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  1.5.2 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.10.3 (OK)
sphinx >=0.6.6     :  1.3.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.1.0 (OK)

I've also attempted to implement some fixes described by #2844 but became a bit lost in differences between windows/unix file path locations (couldn't find site-packages windows equivalent, this is probably unix only). 

I should also add, there's no trouble using ipython from the command line and, if it wasn't clear, I'm not using Anaconda, Python(x,y), or any other installers outside of wheel files.

**Comment by ccordoba12** [comment]
I think you'd be better by using Anaconda or WinPython, really :-)

This error could be a series of things, so it's hard for us to provide you with more, specially if you're using a not so standard installation (I know things should work with `pip` but that's not usually the case for scientific packages).

**Comment by alexedstrom** [comment]
thanks for the quick reply. I'll give it a whirl.
