### ISSUE TITLE
Make .spyderproject a textfile

### ISSUE THREAD

**Issue by nerdoc** [spyder-ide/spyder#2887]
Just as idea for an enhancement: *~/.spyderproject* now is a binary file that is inpossible to read by humans, less to manipulate.
This would add the benefit of manipulating it manually, and track changes when checked in into a VCS.

Old, binary versions of the file could be read by spyder and converted/written as text/UTF8 at startup/opening of a project, leaving a message to the user that this was done.

**Comment by ccordoba12** [comment]
That's the plan ;-) @goanpeca, another one for you!

**Comment by goanpeca** [comment]
@nerdoc , we are completely revamping how projects are handled in spyder, so the old style of projects is going away, Part of the revamping includes what you propose :+1:

**Comment by nerdoc** [comment]
Okaydokay! Cuhl. ;-)
