### ISSUE TITLE
Spyder wont launch after spyer --reset

### ISSUE THREAD

**Issue by ladale** [spyder-ide/spyder#2889]
Context: windows Vista, python (x,y) 2.7.5.

I get the following error when running Spyder from the command line:
![capturer](https://cloud.githubusercontent.com/assets/11996724/12049585/32d21c46-aee9-11e5-9405-cc9f01fd3f81.JPG)

**Comment by ccordoba12** [comment]
This is a problem with PythonXY, not with Spyder. Please talk to its developers about it.

**Comment by ccordoba12** [comment]
I've heard from some users that you can solve this problem by doing

    pip uninstall xy

Other than that we can't help you to solve this problem, sorry.
