### ISSUE TITLE
Tabs in the editor ...

### ISSUE THREAD

**Issue by Ademir-Francisco-da-Silva** [spyder-ide/spyder#2892]
Please include a option for the next version, if it is possibel of course, to order tabs in the editor as my way, i mean random way ..., thanks.

**Comment by goanpeca** [comment]
duplicate

**Comment by Ademir-Francisco-da-Silva** [comment]
Em 31/12/2015 15:09, Gonzalo Peña-Castellanos escreveu:
>
> duplicate
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/spyder-ide/spyder/issues/2892#issuecomment-168223886>.
>

What you mean with duplicate? I cannot put my tabs in my desired order 
because after that the Spyder just put in its own order, this is it ..., 
if you know how please just answer this email and show me how ...


-- 
Ademir Francisco da Silva
Skype  ...: Ademir_Francisco_da_Silva
[ CMC ] God will do me justice



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by ccordoba12** [comment]
@Ademir-Francisco-da-Silva, for next time please don't open several issues commenting about the same problem, and wait for us to respond to you on the same issue you opened. Your behavior, even if playful, costs us time and attention for the project, so I hope you won't repeat it again.

@goanpeca, for next time please be more clear about the reasons for closing an issue. Just saying something like

> Closing this issue as a duplicate of issue #1170 

it's better than just saying `duplicate`.

**Comment by Ademir-Francisco-da-Silva** [comment]
Carlos,

Ok, lets go to the facts ...

I have opened several issues because I do not received satisfactory 
answer about my question ... Simple like that ... So for me, sounded 
like a disrespect ... and by the way, I am not a playful guy but I know 
how to play this kind of game too ... I do not intend to ask more 
questions because I found there a environment totally aggressive and 
this kind of behavior is disgusting and of course I do not accept this 
kind of attitude ... ( My only intention was help all you but instead I 
found 2 clows there ) ...
Unfortunately, my thought about your project is worst after my first 
contact ... You definitely have to choose better yours coworkers, don't you?

Sorry by have written to you only the truth, This is it ... Dude, I wish 
you a nice day ...

Cheers,


Ademir

PS.: Of course this is my last contac with you ( or all of you ) ... A 
hug, farewell ...

Em 03/01/2016 22:04, Carlos Cordoba escreveu:
>
> @Ademir-Francisco-da-Silva 
> <https://github.com/Ademir-Francisco-da-Silva>, for next time please 
> don't open several issues commenting about the same problem, and wait 
> for us to respond to you on the same issue you opened. Your behavior, 
> even if playful, costs us time and attention for the project, so I 
> hope you won't repeat it again.
>
> @goanpeca <https://github.com/goanpeca>, for next time please be more 
> clear about the reasons for closing an issue. Just saying something like
>
>     Closing this issue as a duplicate of issue #1170
>     <https://github.com/spyder-ide/spyder/issues/1170>
>
> it's better than just saying |duplicate|.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/spyder-ide/spyder/issues/2892#issuecomment-168556689>.
>


-- 
Ademir Francisco da Silva
Skype  ...: Ademir_Francisco_da_Silva
[ CMC ] God will do me justice



---
Este email foi escaneado pelo Avast antivírus.
https://www.avast.com/antivirus

**Comment by ccordoba12** [comment]
@Ademir-Francisco-da-Silva, it really seems you *don't* know how to play this game. No one was aggressive to you, both @goanpeca and @Nodd just failed to give you the proper context about why they closed the issues you opened (as I said above). And instead of waiting for them to do that, you just opened more issues about it, which just makes them (and me) waste our time.

I think you're the aggressive and disrespectful person here by saying things like:

> My only intention was help all you but instead I found 2 clows there

or

> Unfortunately, my thought about your project is worst after my first contact ... You definitely have to choose better yours coworkers, don't you?

I know @goanpeca and @Nodd for several years, and they've never treated any user or me the way you treated us in this email.

Thankfully, you said we'll never have to treat with you again.
