### ISSUE TITLE
FreeCAD and Spyder

### ISSUE THREAD

**Issue by Klogg96** [spyder-ide/spyder#2898]
I have been trying like mad to import FreeCAD ... I cannot seem to get it to work. I have installed Spyder via an anaconda install package.

     D:\Users\Name>conda info
     Current conda install:

                 platform : win-64
            conda version : 3.19.0
      conda-build version : 1.18.1
           python version : 2.7.11.final.0
         requests version : 2.8.1
         root environment : C:\Program Files\Anaconda  (read only)
      default environment : C:\Program Files\Anaconda
         envs directories : D:\Users\Name\.conda\envs
                            D:\Users\Name\envs
                            C:\Program Files\Anaconda\envs
            package cache : D:\Users\Name\.conda\envs\.pkgs
                            D:\Users\Name\envs\.pkgs
                        C:\Program Files\Anaconda\pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

I dont mean to be VERBOSE ... at the bottom of this list is my Conda Packages List.

FreeCAD imports from the console (cmd - python - import FreeCAD). The console sys.path list is as follows:

    C:\Program Files\Anaconda\python27.zip
    C:\Program Files\FreeCAD 0.15\bin
    C:\Program Files\Anaconda\DLLs
    C:\Program Files\Anaconda\lib
    C:\Program Files\Anaconda\lib\plat-win
    C:\Program Files\Anaconda\lib\lib-tk
    C:\Program Files\Anaconda
    C:\Program Files\Anaconda\lib\site-packages
    C:\Program Files\Anaconda\lib\site-packages\Sphinx-1.3.1-py2.7.egg
    C:\Program Files\Anaconda\lib\site-packages\cryptography-1.0.2-py2.7-win-amd64.egg
    C:\Program Files\Anaconda\lib\site-packages\win32
    C:\Program Files\Anaconda\lib\site-packages\win32\lib
    C:\Program Files\Anaconda\lib\site-packages\Pythonwin
    C:\Program Files\Anaconda\lib\site-packages\setuptools-18.5-py2.7.egg

from Spyder I get:

    C:\Program Files\Anaconda\lib\site-packages\spyderlib\utils\external
    C:\Program Files\Anaconda\python27.zip
    C:\Program Files\FreeCAD 0.15\bin
    C:\Program Files\Anaconda\DLLs
    C:\Program Files\Anaconda\lib
    C:\Program Files\Anaconda\lib\plat-win
    C:\Program Files\Anaconda\lib\lib-tk
    C:\Program Files\Anaconda
    c:\program files\anaconda\lib\site-packages\sphinx-1.3.1-py2.7.egg
    c:\program files\anaconda\lib\site-packages\setuptools-18.5-py2.7.egg
    C:\Program Files\Anaconda\lib\site-packages
    C:\Program Files\Anaconda\lib\site-packages\cryptography-1.0.2-py2.7-win-amd64.egg
    C:\Program Files\Anaconda\lib\site-packages\win32
    C:\Program Files\Anaconda\lib\site-packages\win32\lib
    C:\Program Files\Anaconda\lib\site-packages\Pythonwin
    C:\Program Files\Anaconda\lib\site-packages\IPython\extensions
    D:\Users\Name\.ipython

When Import FreeCAD is executed in Spyder I get the typical:

    ImportError: DLL load failed: The specified procedure could not be found.
    
But what is even more weird is that when I use help() in the Spyder Console ...
First I type:

    help> module cad
    no Python documentation found for module cad

Then I type:

    help> modules

    <I get a list of modules including FreeCAD and FreeCADGui>

Then I type:

    help> modules cad
    
    Here is a list of matching modules.  Enter any module name to get more help.
    
    FreeCAD 
    FreeCADGui   

I do not understand why I cannot import FreeCAD... I have messed with PYTHONPATH and added near every sub directory in FreeCAD. I have also tried to append via sys.path ... Nothing seems to work. It appears to me I have done everything I know how to do. Could someone give me some pointers on where to go from here? Thanks so much for the help.

--- Total Packages List ---

    D:\Users\Name>conda list
    # packages in environment at C:\Program Files\Anaconda:
    #
    _license                  1.1                      py27_1    defaults
    alabaster                 0.7.6                    py27_0    <unknown>
    anaconda                  2.4.1               np110py27_0    defaults
    anaconda-client           1.2.1                    py27_0    defaults
    argcomplete               1.0.0                    py27_1    <unknown>
    astropy                   1.0.6               np110py27_0    defaults
    babel                     2.1.1                    py27_0    <unknown>
    backports-abc             0.4                       <pip>
    backports.ssl-match-hostname 3.4.0.2                   <pip>
    backports_abc             0.4                      py27_0    defaults
    beautifulsoup4            4.4.1                    py27_0    <unknown>
    bitarray                  0.8.1                    py27_1    <unknown>
    blaze                     0.8.3                     <pip>
    blaze-core                0.8.3                    py27_0    <unknown>
    bokeh                     0.10.0                   py27_0    <unknown>
    boto                      2.38.0                   py27_0    <unknown>
    bottleneck                1.0.0               np110py27_0    <unknown>
    bzip2                     1.0.6                     vc9_2  [vc9]  <unknown>
    cdecimal                  2.3                      py27_1    <unknown>
    cffi                      1.2.1                    py27_0    <unknown>
    clyent                    1.2.0                    py27_0    defaults
    colorama                  0.3.3                    py27_0    <unknown>
    comtypes                  1.1.2                    py27_0    <unknown>
    conda                     3.19.0                   py27_0    defaults
    conda-build               1.18.1                   py27_0    <unknown>
    conda-env                 2.4.5                    py27_0    defaults
    configobj                 5.0.6                    py27_0    <unknown>
    console_shortcut          0.1.1                    py27_1    <unknown>
    cryptography              1.0.2                    py27_0    <unknown>
    curl                      7.45.0                    vc9_0  [vc9]  <unknown>
    cycler                    0.9.0                    py27_0    defaults
    cython                    0.23.4                   py27_0    <unknown>
    cytoolz                   0.7.4                    py27_0    <unknown>
    datashape                 0.4.7               np110py27_1    <unknown>
    decorator                 4.0.4                    py27_0    <unknown>
    docutils                  0.12                     py27_1    <unknown>
    enum34                    1.0.4                    py27_0    <unknown>
    fastcache                 1.0.2                    py27_0    <unknown>
    flask                     0.10.1                   py27_1    <unknown>
    freetype                  2.5.5                     vc9_0  [vc9]  <unknown>
    funcsigs                  0.4                      py27_0    <unknown>
    gevent                    1.0.1                    py27_0    <unknown>
    gevent-websocket          0.9.3                    py27_0    <unknown>
    greenlet                  0.4.9                    py27_0    <unknown>
    grin                      1.2.1                    py27_2    <unknown>
    h5py                      2.5.0               np110py27_4    <unknown>
    hdf5                      1.8.15.1                  vc9_4  [vc9]  defaults
    idna                      2.0                      py27_0    <unknown>
    ipaddress                 1.0.14                   py27_0    <unknown>
    ipykernel                 4.1.1                    py27_0    <unknown>
    ipython                   4.0.1                    py27_0    defaults
    ipython-genutils          0.1.0                     <pip>
    ipython-notebook          4.0.4                    py27_3    <unknown>
    ipython-qtconsole         4.0.1                    py27_4    <unknown>
    ipython_genutils          0.1.0                    py27_0    <unknown>
    ipywidgets                4.1.0                    py27_0    <unknown>
    itsdangerous              0.24                     py27_0    <unknown>
    jdcal                     1.0                      py27_0    <unknown>
    jedi                      0.9.0                    py27_0    <unknown>
    jinja2                    2.8                      py27_0    <unknown>
    jpeg                      8d                        vc9_0  [vc9]  <unknown>
    jsonschema                2.4.0                    py27_0    <unknown>
    jupyter                   1.0.0                    py27_1    defaults
    jupyter-client            4.1.1                     <pip>
    jupyter-console           4.0.3                     <pip>
    jupyter-core              4.0.6                     <pip>
    jupyter_client            4.1.1                    py27_0    <unknown>
    jupyter_console           4.0.3                    py27_0    <unknown>
    jupyter_core              4.0.6                    py27_0    <unknown>
    launcher                  1.0.0                         4    <unknown>
    libpng                    1.6.17                    vc9_1  [vc9]  <unknown>
    libsodium                 1.0.3                         0    <unknown>
    libtiff                   4.0.6                     vc9_1  [vc9]  defaults
    llvmlite                  0.8.0                    py27_0    defaults
    lxml                      3.4.4                    py27_0    <unknown>
    markupsafe                0.23                     py27_0    <unknown>
    matplotlib                1.5.0               np110py27_0    defaults
    menuinst                  1.3.1                    py27_0    defaults
    mistune                   0.7.1                    py27_0    <unknown>
    msvc_runtime              1.0.1                     vc9_0  [vc9]  defaults
    multipledispatch          0.4.8                    py27_0    <unknown>
    nbconvert                 4.0.0                    py27_0    <unknown>
    nbformat                  4.0.1                    py27_0    <unknown>
    networkx                  1.10                     py27_0    <unknown>
    nltk                      3.1                      py27_0    <unknown>
    node-webkit               0.10.1                        0    <unknown>
    nose                      1.3.7                    py27_0    <unknown>
    notebook                  4.0.6                    py27_0    <unknown>
    numba                     0.22.1              np110py27_0    defaults
    numexpr                   2.4.4               np110py27_0    <unknown>
    numpy                     1.10.1                   py27_0    <unknown>
    odo                       0.3.4                    py27_0    <unknown>
    openpyxl                  2.2.6                    py27_0    <unknown>
    openssl                   1.0.2d                    vc9_0  [vc9]  <unknown>
    pandas                    0.17.1              np110py27_0    defaults
    path.py                   8.1.2                    py27_1    defaults
    patsy                     0.4.0               np110py27_0    <unknown>
    pep8                      1.6.2                    py27_0    <unknown>
    pickleshare               0.5                      py27_0    <unknown>
    pillow                    3.0.0                    py27_1    <unknown>
    pip                       7.1.2                    py27_0    <unknown>
    ply                       3.8                      py27_0    <unknown>
    psutil                    3.3.0                    py27_0    defaults
    py                        1.4.30                   py27_0    <unknown>
    pyasn1                    0.1.9                    py27_0    <unknown>
    pycosat                   0.6.1                    py27_0    <unknown>
    pycparser                 2.14                     py27_0    <unknown>
    pycrypto                  2.6.1                    py27_3    <unknown>
    pycurl                    7.19.5.1                 py27_1    <unknown>
    pyflakes                  1.0.0                    py27_0    <unknown>
    pygments                  2.0.2                    py27_0    <unknown>
    pyopenssl                 0.15.1                   py27_1    <unknown>
    pyparsing                 2.0.3                    py27_0    <unknown>
    pyqt                      4.11.4                   py27_4    defaults
    pyreadline                2.1                      py27_0    <unknown>
    pytables                  3.2.2               np110py27_1    <unknown>
    pytest                    2.8.1                    py27_0    <unknown>
    python                    2.7.11                        0    defaults
    python-dateutil           2.4.2                    py27_0    <unknown>
    pytz                      2015.7                   py27_0    defaults
    pywin32                   219                      py27_1    <unknown>
    pyyaml                    3.11                     py27_2    <unknown>
    pyzmq                     14.7.0                   py27_1    <unknown>
    qt                        4.8.7                     vc9_5  [vc9]  defaults
    qtconsole                 4.1.1                    py27_0    defaults
    requests                  2.8.1                    py27_0    <unknown>
    rope                      0.9.4                    py27_1    <unknown>
    scikit-image              0.11.3              np110py27_0    <unknown>
    scikit-learn              0.17                np110py27_1    defaults
    scipy                     0.16.0              np110py27_0    <unknown>
    setuptools                18.5                     py27_0    defaults
    simplegeneric             0.8.1                    py27_0    <unknown>
    singledispatch            3.4.0.3                  py27_0    <unknown>
    sip                       4.16.9                   py27_2    defaults
    six                       1.10.0                   py27_0    <unknown>
    snowballstemmer           1.2.0                    py27_0    <unknown>
    sockjs-tornado            1.0.1                    py27_0    <unknown>
    sphinx                    1.3.1                    py27_0    <unknown>
    sphinx-rtd-theme          0.1.7                     <pip>
    sphinx_rtd_theme          0.1.7                    py27_0    <unknown>
    spyder                    2.3.8                    py27_0    defaults
    spyder-app                2.3.8                    py27_0    defaults
    sqlalchemy                1.0.9                    py27_0    <unknown>
    ssl_match_hostname        3.4.0.2                  py27_0    <unknown>
    statsmodels               0.6.1               np110py27_0    <unknown>
    sympy                     0.7.6.1                  py27_0    <unknown>
    tables                    3.2.2                     <pip>
    tk                        8.5.18                    vc9_0  [vc9]  <unknown>
    toolz                     0.7.4                    py27_0    <unknown>
    tornado                   4.3                      py27_0    defaults
    traitlets                 4.0.0                    py27_0    <unknown>
    ujson                     1.33                     py27_0    <unknown>
    unicodecsv                0.14.1                   py27_0    <unknown>
    werkzeug                  0.11.2                   py27_0    defaults
    wheel                     0.26.0                   py27_1    <unknown>
    xlrd                      0.9.4                    py27_0    <unknown>
    xlsxwriter                0.7.7                    py27_0    <unknown>
    xlwings                   0.5.0                    py27_0    defaults
    xlwt                      1.0.0                    py27_0    <unknown>
    zeromq                    4.1.3                     vc9_1  [vc9]  <unknown>
    zlib                      1.2.8                     vc9_2  [vc9]  <unknown>

**Comment by ccordoba12** [comment]
I'm sorry but we don't have time to help you debug this problem, so I'm closing this issue.
