### ISSUE TITLE
Outline entries parsed incorrectly when cell comments (#%%) in class definition

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#2899]
Env:
Python 2.7.11 64bits, Qt 5.4.1, PyQt5 5.4.1 on Darwin

Class methods are parsed incorrectly if there is a cell comment (#%%) preceding the method definition line.

![image](https://cloud.githubusercontent.com/assets/11516238/12087603/402a3e08-b30f-11e5-84ed-f085471792f2.png)

However, it works fine for normal functions outside the class definition:
![image](https://cloud.githubusercontent.com/assets/11516238/12087652/adc3051c-b30f-11e5-9e94-75f209262e15.png)

**Comment by goanpeca** [comment]
Tried with

```python
class Test:
# %% Test 1
    def f1(self):
        pass


# %% Test 2
    def f2(self):
        pass

    def f3(self):
        pass
```

And I get 

<img width="237" alt="Screen Shot 2019-11-28 at 11 57 56" src="https://user-images.githubusercontent.com/3627835/69823258-5d0c9280-11d6-11ea-928e-0c4ce3217ead.png">


Which looks ok. Closing.
