### ISSUE TITLE
variable with all capital letters does not show in workspace

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#290]
_From [anthonyd...@gmail.com](https://code.google.com/u/110869215659572095163/) on 2010-08-12T12:13:45Z_

If you load Spyder, and enter a variable in the Interactive console, where the variable name has all caps, it will not show up in the Workspace window.  

For example entering the following at the commandline: TESTVAR = 2
will not show up in the workspace, although testvar = 2 will show up.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=290_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-08-12T10:38:32Z_

That's because there is an option to hide this kind of variable which should be (according to Python official guidelines) a global variable in an imported module (imported with the non-recommended statement "from foobar import *".
Anyway to show these variables, just tick the option "show upper case [something]" (context menu)

**Status:** Invalid

**Comment by matipezo** [comment]
I suppose you already solved your problem, but for the people searching for this issue (as I was a few minutes ago) here is the answer. 
In Spyder go to 'Tools<Preferences<Variable Explorer<Filter' and turn off the 'Exclude all-uppercase references' option.
Hope this might help the upcoming friends. Best regards!!
![image](https://user-images.githubusercontent.com/111547600/215864480-a87870c3-80b7-4063-842b-09a117ccec3b.png)
