### ISSUE TITLE
Console hangs after matplotlib call

### ISSUE THREAD

**Issue by windancert** [spyder-ide/spyder#2903]
I've recently upgraded from an older version to Spyder 3.0.0dev (as shipped by WinPython 2.7.10.3) and noticed that the regular console hangs when I give the following commands

    >>> import matplotlib.pyplot as plt
    >>> plt.plot(range(5))
    [<matplotlib.lines.Line2D object at 0x000000001A0C8470>]
    >>> 1+1

This did not hang the console in the previous version of Spyder and also doesn't happen when I use the IPython console.

**Comment by ccordoba12** [comment]
This problem was fixed in Spyder 3.0.0 beta2. Please update to that version, or ask WinPython maintainers to do it in their issue tracker:

https://github.com/winpython/winpython

**Comment by windancert** [comment]
:+1:
