### ISSUE TITLE
Find/Replace selection only

### ISSUE THREAD

**Issue by Gh0str1d3r** [spyder-ide/spyder#2906]
I would suggest to add a feature to find/replace text only in a highlighted selection of the current file, similar to the find/replace function in kwrite:

![image](https://cloud.githubusercontent.com/assets/4189493/12122566/e59f11ca-b3a9-11e5-9671-2d350085c029.png)

**Comment by rlaverde** [comment]
This is duplicated of #358

**Comment by ccordoba12** [comment]
Thanks!
