### ISSUE TITLE
Modified file flag ('*') disappears from tab in the Editor

### ISSUE THREAD

**Issue by wombatonfire** [spyder-ide/spyder#2907]
If we open and edit several files and then perform 'Save as' for **one** of them, 'modified' flag ('*') after the filename will disappear for **all** files, even unsaved ones. It reappears if we switch to the tab with unsaved file.

This does not happen for newly created files and during simple 'Save' procedure.

Spyder 3.0.0dev
Python 2.7

**Comment by wombatonfire** [comment]
And another scenario and the same strange behavior:

If we create (but not save) several files, modify one of them and do 'Save as' for it, '\*' will appear for unmodified files.

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, this is a hard one so you don't need to have it ready for next week. In two weeks would be fine :-)

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, @dalthviz solved this one as part of PR #3715, so please don't work on it.
