### ISSUE TITLE
Automatically set working directory in console

### ISSUE THREAD

**Issue by cle1109** [spyder-ide/spyder#2910]
The current behavior of the current working directory text field in the menu bar might be confusing, especially to beginners and/or people coming from MATLAB. Currently, the working directory is not automatically updated in the console when the working directory is changed in the menu bar (either by directly entering a new path, or navigating up, or by choosing a specific directory). Instead, the user has to click the dedicated "Set as current console's working directory" button.

I suggest to change this behavior such that changes in the working directory set in the menu bar are always automatically propagated to the current (or even all) console.

**Comment by dzosz** [comment]
I added the changes. This fix does exactly what you said, but more improvements are needed. Now "Set current cwd" button is sort of deprecated/useless. Sort of, because user still can change the cwd in console by typing os.chdir('xxx') and cause desynchronization but we shouldn't worry about this. 
Old button can be removed or replaced with "Change to project directory" (if available). What are your thoughts about this?

**Comment by cle1109** [comment]
I agree that the button could be removed. It would be great if the synchronization also worked in the other direction, i.e. if you cd in the console, the directory should automatically be updated in the interface. In other words, the directory you see in the interface should always be the cwd.

**Comment by ccordoba12** [comment]
> I agree that the button could be removed

I'll remove it for beta3

> It would be great if the synchronization also worked in the other direction

I think this could confuse users: you could `cd` to another directory just to check some files, and then rerun your current script, which could need some data files located in the directory you set in our toolbar.

**Comment by cle1109** [comment]
> I think this could confuse users: you could cd to another directory just to check some files, and then rerun your current script, which could need some data files located in the directory you set in our toolbar.

I don't know which behavior is more confusing. I'd prefer a 2-way synchronization, that way I always see the cwd in the toolbar. In your example, you would have to `cd` back before running the script.

**Comment by kings9** [comment]
Hi Carlos,
I am using spyder 3.2.4.Its regarding the working directory.Its working fine as expected ,only question I have when I reopen the spyder it changes(not the working directory I was working on).Is it expected.How can I set the current working directory as default working directory.
Best Regards,
Kingshuk

**Comment by ccordoba12** [comment]
Please see in

    Tools > Preferences > Current working directory
