### ISSUE TITLE
Ipython console always immediately crashes in Spyder

### ISSUE THREAD

**Issue by gnucci** [spyder-ide/spyder#2911]
Sorry if this style is incorrect; I can't seem to get back to the window that showed the correct submission style.

Windows 10
Python 2.7.11 
Spyder 2.3.8
Anaconda 2.1.0 (64-bit)| (default, Dec  7 2015, 14:10:42) [MSC v.1500 64 bit (AMD64)]
iPython 4.0.1

Every time I launch Spyder, the iPython console immediately crashes, printing the following message every 1-2 seconds: 

"It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console."

I have looked for similar issues, but haven't made any progress. I can run in the standard Python console fine.

Thanks for any suggestions.

**Comment by ccordoba12** [comment]
Please focus the **Python** console, look for a **Kernel** tab and see if there are any errors printed there.

**Comment by gnucci** [comment]
Hello,

Thanks for the quick reply! I reinstalled Anaconda from scratch, and the issue was still there last night, but this morning, it seems to have disappeared, and I can no longer recreate it.

Cheers!
