### ISSUE TITLE
Change keybinding for re-running last script

### ISSUE THREAD

**Issue by johandicap** [spyder-ide/spyder#2912]
When your python script grows beyond a single file, you often want to re-run the last (main) script instead of the current file that you are working on. On Windows, the default keyboard shortcut for this is "Ctrl+F6", which on many keyboards requires two hands to type and therefore is inefficient for an often-used action.

At the same time, the Run menu entry "Configure..." is bound to "F6". This menu entry is in most cases only used __once__, i.e. in the beginning of development to set the desired run settings. And here, the menu even pops up by itself at first execution, so the shortcut isn't needed for this.

I therefore suggest swapping these two keyboard shortcuts, so that "Re-run last script" becomes "F6" and "Configure..." (Run Settings) becomes "Ctrl+F6" on Windows. (I do not have the other platforms in front of me, so I do not know how the change would be implemented there.)

**Comment by ccordoba12** [comment]
I think it's a very good suggestion. @Nodd and @goanpeca, what do you think about it?

**Comment by goanpeca** [comment]
:+1:

**Comment by Nodd** [comment]
:+1:
The change will be visible for new configurations only, right ?

**Comment by ccordoba12** [comment]
@Nodd, yep. New shortcuts will be shown in the `Run` menu.
