### ISSUE TITLE
Problems with changing keyboard shortcuts on Mac

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#2915]
Spyder 3.0.0b2 
Python 2.7.11 64bits, Qt 5.4.1, PyQt5 5.4.1 on Darwin

Problem 1: 
When I tried to change a shortcut to "Command + R" on Mac, the dialog showed "Ctrl + R", which is confusing because "Ctrl" is not "Command" on Mac (nevertheless, the shortcut was successfully set to "Command + R").
![image](https://cloud.githubusercontent.com/assets/11516238/12214271/396bf360-b6c8-11e5-8132-b14d8b89a903.png)

Problem 2:
After I successfully changed the shortcut, the following error still occurred in the Spyder Internal Console:

```python
Traceback (most recent call last):
  File "/Users/shenggao/anaconda/lib/python2.7/site-packages/spyderlib/plugins/shortcuts.py", line 793, in <lambda>
    lambda i1, i2, opt='': self.has_been_modified(opt))
  File "/Users/shenggao/anaconda/lib/python2.7/site-packages/spyderlib/plugins/configdialog.py", line 404, in has_been_modified
    self.changed_options.add(option)
TypeError: unhashable type: 'list'
```

**Comment by AlJohri** [comment]
When changing a keyboard shortcut (namely the comment from ⌘1 to ⌘/), Spyder shows "Ctrl" instead. 

After clicking "Ok" to change the shortcut, the entire program crashes with the following crash report: https://gist.github.com/AlJohri/fbc3b678dab328f98167#file-crash_report-txt

Upon restarting Spyder, unlike @ShenggaoZhu, my shortcut was not set successfully.

- `echo $(sw_vers -productName) $(sw_vers -productVersion)` Mac OS X 10.11.1
- `python --version` Python 3.5.1
- `pip freeze | grep spyder` spyder==3.0.0b2
- `brew list --versions | grep qt5` pyqt5 5.5.1, qt5 5.5.1_2

**Comment by AlJohri** [comment]
For the time being, I edited my spyder.ini file to use `Ctrl+/` instead of `Ctrl+1`.

Running `grep "toggle comment" ~/.spyder-py3/spyder.ini`, shows:

>editor/toggle comment = Ctrl+/

Works great :)

**Comment by ccordoba12** [comment]
@AlJohri, Cmd+/ can't be introduced as a shortcut now. We only allow Modifiers+letter or Modifiers+number as allowed shortcuts. Sorry but we can't cover the whole spectrum of keys to ease maintenance for us :-)

This will prevent your crash.

**Comment by AlJohri** [comment]
@ccordoba12 thanks for the fix!

I understand where you're coming from. What is your preferred comment shortcut?

`⌘ + /` is pretty ubiquitous on Macs such as on Sublime Text, Atom, Jupyter Notebook, etc.

**Comment by ccordoba12** [comment]
Please open a new issue about your request (i.e. being able to assign 
Cmd+/ for comments)
