### ISSUE TITLE
Spyder always switches back to IPython kernel from IPyhton console

### ISSUE THREAD

**Issue by Temmplar** [spyder-ide/spyder#2918]
For me a bit uncomfortable, that if I work with a task in the Console and switch to IP console and then back, then Spyder always switch to the IPython kernel tab in the Console instead of the previously used Console task/tab.

**Comment by ccordoba12** [comment]
Thanks for reporting, this will be fixed in Spyder 3.0 beta3.

**Comment by ccordoba12** [comment]
Sorry, this will be fixed once pull request #2878 is merged
