### ISSUE TITLE
Add "run selection" icon.

### ISSUE THREAD

**Issue by ahed87** [spyder-ide/spyder#2920]
Hi,
an enhancement idea triggered by issue [#2490](https://github.com/spyder-ide/spyder/issues/2490)
a small (or large) suggestion related to this area would be to add one run icon.
I quite often select a piece of code and use the right-click -> "run selection or current line".
When doing that I typically have made the selection with keys, scrolled a bit with the mouse and that's when I miss an icon to press to run the selected area. I quite often end up pressing the regular run-icon when I really want to run a selection, since it's soo much easier than doing the right-click, especially if that area is out of focus in the editor.

I have no strong opinions of how such an icon would look like (like today's run with an 's' in it?), and were it should be placed (inbetween current run and runcell icons?).

**Comment by SylvainCorlay** [comment]
@ahed87 FYI you can already use the F9 keyboard shortcut.

**Comment by ccordoba12** [comment]
Yep, that's the way to run selections. We already have too many run buttons, so I don't think we're going to add one more.

**Comment by ahed87** [comment]
No worries it was an enhancement suggestion, however I work on 2 different computers (both windows and not overly old) and on one of them F9 works and on the other it doesn't - so I guess there could be more than me missing out on F9?

**Comment by ShenggaoZhu** [comment]
@ahed87 I am also a heavy user of the nice "run selection" function, and I prefer using keyboard shortcuts than clicking buttons. However I don't like the default ``F9`` shortcut, as I have to press ``fn + F9`` on Mac for that (I don't want to change my Mac settings to use Function keys as standard keys in order to press ``F9`` directly)... So I ended up changing the shortcut of "run selection" to another keybinding (``Cmd+T``)...

**Comment by ahed87** [comment]
Thanks for the push on shortcuts, and I do use them quite frequently - probably could use them more in spyder, anyways I still would use an icon if it was there - it's a conveniece matter.
I'm taking the liberty to close this one to avoid further pollution to the issue list.
