### ISSUE TITLE
Add a switch button to transfer between "Find text" widget and "Replace text" widget

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#2921]
Spyder 3.0.0b2 
Python 2.7.11 64bits, Qt 5.4.1, PyQt5 5.4.1 on Darwin

An idea of enhancement:

**The problem:**

During coding, one may usually first try to "Find" some text, and then if necessary, "Replace" what has been found. Users would appreciate an easy way to convert the "Find text" widget into a "Replace text" widget.

However in the current Spyder, if the "Find text" widget is focused (the cursor flashing in the search text box), you can not activate the "Replace text" widget directly from there via the shortcut or even the menu "Search -> Replace text". You will have to move the focus to the Editor first (e.g., by clicking the Editor) in order to activate the "Replace text" widget, which is inconvenient.

(An interesting sidenote of asymmetry: if the "Replace text" widget is activated and the Editor is focused, and you try the "Find text" command via the shortcut or menu, the "Replace text" widget will be unchanged rather than transferring to the "Find text" widget -- which might be reasonable though...)

**The suggestion:**

Add a switch button or a dropdown list to the "Find text" widget and "Replace text" widget to easily transfer from one to the other. The inspiration comes from Xcode:

<img src="https://cloud.githubusercontent.com/assets/11516238/12229436/a252f502-b882-11e5-9a9a-2c90ed1eb5aa.png"  width="50%">

<img src="https://cloud.githubusercontent.com/assets/11516238/12229323/91cd629a-b881-11e5-88f4-ff55e5903627.png"  width="50%">

<img src="https://cloud.githubusercontent.com/assets/11516238/12229448/b5ddb40e-b882-11e5-8c61-7ca0fa6499b2.png"  width="50%">

Besides, the current "Find text" widget still has lots of space to hold another button:
![image](https://cloud.githubusercontent.com/assets/11516238/12229398/3189d052-b882-11e5-8e96-c13855943bda.png)

What do you think?

**Comment by ShenggaoZhu** [comment]
To make things even simpler, we can directly use the current "Replace text" widget for both "Find" and "Replace" (so no need to separate these two commands, reducing configuration and shortcuts...). 

![image](https://cloud.githubusercontent.com/assets/11516238/12230965/efa7d80c-b88e-11e5-8b2a-46be6b91fe18.png)

1. Very frequently, these two commands are used together. So this will save the trouble of transferring from one widget to the other.

2. The current "Replace text" widget is not too large to affect the space of the Editor.

3. Hopefully this will not be too difficult to implement.

4. Eclipse (PyDev) is already using this combined widget for "Find":
![image](https://cloud.githubusercontent.com/assets/11516238/12230978/05871d0e-b88f-11e5-8ab4-53937aa1abd3.png)

**Comment by oscargus** [comment]
The keyboard bindings work for switching from the find text with 3.3 so I believe that this can be closed (unless there is some interest in changing the GUI).

**Comment by ccordoba12** [comment]
Thanks for looking into this @oscargus!
