### ISSUE TITLE
Raise exception on console stop

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2922]
## Description

**What steps will reproduce the problem?**
1. Stop or kill a running process in a python console

**What is the expected output? What do you see instead?**
The program stops correctly, but without any information about where it was when it stopped. This information would be useful to debug hanging or long running programs. In a standard console hitting `ctrl+C` would raise a `keyboardInterrupt` showing the full stack trace, while in spyder stopping the program is done silently.

**Please provide any additional information below**
## Version and main components
- Spyder Version: 3.0.0dev 
- Python Version: 3.5.1
- Qt Versions: 5.5.1, PyQt5 5.5.1 on Linux
## Dependencies

```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=3.0      :  4.0.0 (OK)
zmq >=13.0.0       :  15.1.0 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
numpy >=1.7        :  1.10.2 (OK)
sphinx >=0.6.6     :  1.3.3 (OK)
psutil >=0.3       :  3.3.0 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
sympy >=0.7.3      :  None (NOK)
pylint >=0.25      :  1.5.2 (OK)

```

**Comment by ccordoba12** [comment]
Interesting idea, but I don't know how it could be implemented...

**Comment by Nodd** [comment]
I have the same interrogation ! Is it possible to send a virtual ctrl+C to the console ?

**Comment by ccordoba12** [comment]
Closing because the Python console is going to be removed in Spyder **3.2**.

Please see issue #4524 for our reasons to do this.
