### ISSUE TITLE
anaconda channel: Rebuild qt5 [linux] needed due to icu54->icu56

### ISSUE THREAD

**Issue by zeehio** [spyder-ide/spyder#2924]
While using spyder beta from your [anaconda channel](https://anaconda.org/spyder-ide) I found that I could not `from PyQt5 import QtCore` because `ImportError: libicui18n.so.54: cannot open shared object file: No such file or directory`. It seems that you already provide `libicui18n.so.56` so I believe that rebuilding qt5 should fix the issue (or stating a versioned dependency on icu==54.1).

If there is a specific place to report issues related to your anaconda channel please point me to it, as I have not been able to find it.

Thanks for your time.

**Comment by ccordoba12** [comment]
i think you need to run

    conda install -c spyder-ide icu==56.1

to fix that problem.

**Comment by zeehio** [comment]
icu 56.1 was automatically installed but PyQt5 requested (did not find) icu 54.1.

I could workaround this issue by installing icu==54
.1 from the @ccordoba12 channel.

**Comment by zeehio** [comment]
My mistake. I am deeply sorry to have made you spent time on this issue.

Apparently doing `conda install  -c https://conda.anaconda.org/spyder-ide qt5 pyqt5 spyder` will not install `qt5` if there is another channel (in my case I had tested `mmcauliffe` in the past) providing the same qt5 version and it is already installed or downloaded in the root environment.

At least I learnt how to `conda-build qt5` several times and some things from conda.

Again, my sincere apologies.

**Comment by ccordoba12** [comment]
Not a problem, glad you figured it out the issue :-)

In any case, it's important for us to know that we need to pin the icu version used to compile Qt5 in its conda recipe.
