### ISSUE TITLE
Is the IPython Console using Tornado?

### ISSUE THREAD

**Issue by Diti24** [spyder-ide/spyder#2925]
## Description

**What steps will reproduce the problem?**

1. Trying the hello world example of Tornado
http://www.tornadoweb.org/en/stable/
or just these few lines of code

```python
import tornado.ioloop
import tornado.web

class MainHandler(tornado.web.RequestHandler):
    def get(self):
        self.write("Hello, world va")

def make_app():
    return tornado.web.Application([
        (r"/", MainHandler),
    ])

if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
```

**What is the expected output? What do you see instead?**
I would expect this can be run inside spyder in the ipython console
What happens is that I get the following error:

```
RuntimeError: IOLoop is already running
```

when the
tornado.ioloop.IOLoop.current().start()
is executed

**Please provide any additional information below**
Running this directly like
ipython test.py will work without errors

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.4.3
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.1 (OK)
zmq >=2.1.11       :  15.1.0 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
pandas >=0.13.1    :  0.16.2 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.3.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  0.25.1 (OK)

```

**Comment by ccordoba12** [comment]
@minrk, is it possible to run Tornado apps in zmq-based apps?

**Comment by blink1073** [comment]
Yep: https://github.com/zeromq/pyzmq/blob/master/examples/eventloop/asyncweb.py

**Comment by minrk** [comment]
Yup, this should work fine. The only issue is that `start` has already been called. Since the IOLoop is already running, the example is fully setup when you call `app.listen()`.

**Comment by Diti24** [comment]
I tried to ommit the last line i.e.
``` tornado.ioloop.IOLoop.current().start() ```
In this case I will not get an error but if I try to connect to localhost:8888 it will not work. So something seems not to work as expected.

I tried to run the test in a Python console in Spyder, in that case it will work also.

It is not a huge problem at all, i can use the python console instead of the ipython.

BTW. I discovered just now that the debugger is much more usable when a python console is used instead of an ipython console, i.e. tab autocomplation, command history, F9 is working... that's great!!! Maybe this is something which could be explained to all comments regarding "poor" usability while debugging.

**Comment by ccordoba12** [comment]
I can't reproduce this error on Python 2 nor 3, using Tornado 4 nor 3. So this has to be a problem with your setup.

About usability and debugging: all the missing things in the IPython Console you mention are caused by limitations of the kernel-based architecture of IPython/Jupyter. So it's not really our fault, but we have plans to improve the situation in a future Spyder release (not 3.0 though).

**Comment by Diti24** [comment]
I know I red about it. I wanted just mention this, because other people may benefit from this meanwhile.
Thanks
