### ISSUE TITLE
Editor: "move line up/down" commands broken when moving past a blank line

### ISSUE THREAD

**Issue by joshburnett** [spyder-ide/spyder#2927]
## Description

**Proper behavior:**
1. Place cursor on a line with some text on it, **where the next line also contains text:**
   ![initial conditions 1](https://cloud.githubusercontent.com/assets/12973799/12326901/77b996f4-baa1-11e5-9b6f-d8ab37839212.png)
2. Execute the 'move line down' command (not in the menu, but I have a keyboard shortcut assigned to it)
3. Observe that the original line has now swapped places with the line after it:
   ![proper result](https://cloud.githubusercontent.com/assets/12973799/12326917/957e7768-baa1-11e5-9447-ca7aa046c20e.png)

**Improper behavior:**
1. Place cursor on a line with some text on it, **where the next line is blank:**
   ![initial conditions 2](https://cloud.githubusercontent.com/assets/12973799/12326976/e1bf6862-baa1-11e5-8767-0c24c2b3c6c1.png)
2. Execute the same 'move line down' command
3. Observe that the cursor simply moves to the next line, and doesn't move any text:
   ![improper result](https://cloud.githubusercontent.com/assets/12973799/12327006/0e69a882-baa2-11e5-89b0-b4b566a067a4.png)
## Version and main components
- Spyder Version: 3.0.0b1 
- Python Version: 2.7.10
- Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Windows
## Optional dependencies

```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.2.0 (OK)
zmq >=13.0.0    :  14.7.0 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
rope >=0.9.4    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

**Comment by ccordoba12** [comment]
@andfoy, please work on this one. The shortcuts to move lines up and down are `Alt+Up` and `Alt+Down` respectively.

In my tests, only `Alt+Down` is failing to move a line down when a blank line is below it.
