### ISSUE TITLE
workspace does not support object arrays

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#293]
_From [anthonyd...@gmail.com](https://code.google.com/u/110869215659572095163/) on 2010-08-13T10:38:33Z_

It would be useful if numpy object arrays could be viewed.  For example, in the workspace a list of datetime.datetime objects can be viewed, although the same list as an array cannot be viewed.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=293_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-02T10:51:29Z_

This is no longer an issue in Spyder 2. The variable explorer shows numpy arrays just fine

**Status:** WontFix

**Comment by reshusinghhh** [comment]
![screenshot from 2018-02-15 18-35-26](https://user-images.githubusercontent.com/18489140/36257971-0c679328-127f-11e8-976d-772ead9664bd.png)
The current version is Spyder 2.3.8 
The Scientific PYthon Development EnviRonment 

Object arrays are currently not supported. Should I upgrade the spyder version?

**Comment by ccordoba12** [comment]
No, sorry, they are still not supported.

**Comment by farzadhallaji** [comment]
i had the same problem in spyder 3.2.6
![screenshot from 2018-02-27 11-18-54](https://user-images.githubusercontent.com/16305486/36716583-1052ed5e-1bb0-11e8-85f6-9c8642b42eba.png)

**Comment by reshusinghhh** [comment]
Will it be resolved ?

**Comment by farzadhallaji** [comment]
in spyder 3.2.6 are not supported but in spyder 3.1.2 are supported

**Comment by farzadhallaji** [comment]
> Will it be resolved ?
in spyder 3.2.6 are not supported but in spyder 3.1.2 are supported

**Comment by farzadhallaji** [comment]
I found that It's Work but Variable Explorer don't show this correctly 
![20](https://user-images.githubusercontent.com/16305486/36718038-9a9e9b8e-1bb5-11e8-8b01-e670ad40fa01.png)

**Comment by TariniMohanty** [comment]
I have the same issue.. even though it's displaying correctly in console variable explorer is something we need to look for. I am using spyder 3.2.6.

**Comment by adnanarsahd** [comment]
:::[Solved]-Example for Testing:::(just 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
dataset = pd.read_csv('Salary_Data.csv')                         _in your case right name of your file_
X=dataset.iloc[:,:-1].values                                               _this will convert dataframe to object_
df = pd.DataFrame(X)

**Comment by Darshu1510** [comment]
It will be resolved after you convert the X and y dataset into the same datatypes and then you would be able to access it.
![catagoricaldata](https://user-images.githubusercontent.com/22795045/40886191-37013680-6751-11e8-8666-37d852d5aa17.jpg)
