### ISSUE TITLE
Spyder not loading, error message

### ISSUE THREAD

**Issue by trodaway** [spyder-ide/spyder#2931]
When I launch Spyder I get an error message, which quickly appears for a matter of milliseconds, and then nothing.
![screenshot 8](https://cloud.githubusercontent.com/assets/16726937/12367890/fd723caa-bbdd-11e5-8120-cb3f4a89f742.png)

I have tried uninstalling and reinstalling multiple times but with no success.
I'm using Python(x,y) 2.7.10.0 which I have downloaded from http://python-xy.github.io/downloads.html

Any advice appreciated - thanks in advance!

**Comment by ccordoba12** [comment]
I think to fix that error you need to run in a terminal

    easy_install pydicom

**Comment by trodaway** [comment]
Did as you said and still got an error, with 'pydicom' being replaced by 'sympy>=0.7.0', so I repeated it with that. Now works, thank you!
