### ISSUE TITLE
Animation errors when interacting with new Python console

### ISSUE THREAD

**Issue by sbitzer** [spyder-ide/spyder#2936]
I have experienced the following bug:

I configured execution of a Python script, which will run an animation (matplotlib.animation.FuncAnimation), such that it executes in a new dedicated Python console and I can interact with the Python console after execution. When I then ran the script, a figure popped up which showed no animation, though. Instead, the console reported KeyErrors (one per frame, I guess, see also attached file [anim_errors.txt](https://github.com/spyder-ide/spyder/files/94529/anim_errors.txt)) and Spyder in some cases even crashed and had to be restarted. When I deselected the option to interact with the script after execution the animation ran fine and no errors occurred.

I guess this is no major issue, but it can be annoying when Spyder crashes unexpectedly, because you added an animation to your plot.

Versions:
Spyder 2.3.8 
Python 3.5.1 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux
IPython >=1.0      :  4.0.1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.3.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Please upload a simple and reproducible example of your code, so we can test it in our side.

**Comment by sbitzer** [comment]
I replied to your comment via email and expected the reply to show up here. Is this how it is supposed to work? Anyway my reply was:

On my side, for example, matplotlib's animated double pendulum (http://matplotlib.org/examples/animation/double_pendulum_animated.html) generates the described errors.

**Comment by ccordoba12** [comment]
The Python console is going to be removed in Spyder 3.2, so we're not going to work more on it, sorry.
