### ISSUE TITLE
Running Parallel hangs in spyder IPython console, but works in a dedicated python 

### ISSUE THREAD

**Issue by thequackdaddy** [spyder-ide/spyder#2937]
Folks,

I wnated to bring your attention to this [issue](http://stackoverflow.com/questions/34821877/joblib-parallel-hanging-on-windows):

When I run a bit of code in the IPython console from within spyder, my Parallel code hangs. 

But when I run it from a dedicated console, no problems. 

Any ideas? 

Thanks!

**Comment by thequackdaddy** [comment]
So I think I've sorted through most of this. I think when you run runfile(), the wdir changes the directory for the instance, but the parallel slaves might not have their directory updated. Thus, you get this sort of behavior.

**Comment by stonebig** [comment]
There is something around the same subject just posted on StackOverflow.

http://stackoverflow.com/questions/34821877/joblib-parallel-runing-through-spyder-hanging-on-windows

**Comment by ccordoba12** [comment]
@thequackdaddy, I don't understand how/if we could fix this problem on the Spyder side.

You can prevent `runfile` setting the wdir by going to the menu entry

    Run > Configure

(or pressing **F6**) and unchecking the *Working directory* box. The run configuration is saved for each file, so Spyder remembers it after restarts.

Does that help?

**Comment by thequackdaddy** [comment]
I think I agree.

Generally, if you have the IPython working directory as something, and
runfile with a Parallel instruction in another directory, you'll likely get
this problem.

I guess this is really more of "don't do that" solution and less of a
programmable fix.

I'm not sure if it's worth keeping this open. Feel free to close. Something
of a learning issue for me here.

Thanks!

On Monday, January 18, 2016, Carlos Cordoba <notifications@github.com>
wrote:

> @thequackdaddy <https://github.com/thequackdaddy>, I don't understand
> how/if we could fix this problem on the Spyder side.
>
> You can prevent runfile setting the wdir by going to the menu entry
>
> Run > Configure
>
> (or pressing *F6*) and unchecking the *Working directory* box. The run
> configuration is saved for each file, so Spyder remembers it after restarts.
>
> Does that help?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/2937#issuecomment-172639178>.
>


-- 
Peter Quackenbush
pquack@gmail.com

**Comment by ccordoba12** [comment]
Ok, I'll close this issue but I'll add my last comment as an answer to the SO question, just for future reference.
