### ISSUE TITLE
Spyder crashes on startup with pyqt 4.11.4

### ISSUE THREAD

**Issue by vdude8** [spyder-ide/spyder#2938]
After a recent set of updates to my environment, I was having issues loading up Spyder on my 64-bit Windows 10 machine. After some messing around, I figured out that when pyqt 4.11.4 is installed, Spyder is unable to start, and crashes at the splash screen (Windows states that "python.exe" is not responding). Downgrading back to pyqt 4.10.4 resolved the issue.

I tested this condition in a new conda environment with only Python 3.4.4, Scipy 0.16, Spyder 2.3.8, and all dependencies for those three packages.

**Comment by ccordoba12** [comment]
Does your problem happen even with the latest version of pyqt4? I mean, after you run

    conda update pyqt

?

**Comment by vdude8** [comment]
When I perform that command, pyqt gets updated to 4.11.4. Hence, I'm presuming that's the latest version?

**Comment by ccordoba12** [comment]
> Hence, I'm presuming that's the latest version?

Yes, it is.

I think this problem would be fixed by reinstalling Anaconda, but I'm not entirely sure.

Could you try that in a test account instead of your main one?

**Comment by vdude8** [comment]
Yup, it seems like reinstalling Anaconda fixed the problem. I'm also a little confused because Python 3.5.1 is installed in this new user, while my normal user doesn't update past 3.4.4. Perhaps there's a different package that's prohibiting this update and somehow interacting with pyqt.

Oh well, I guess this isn't a Spyder bug. Thanks for your help!

**Comment by ccordoba12** [comment]
> I'm also a little confused because Python 3.5.1 is installed in this new user, while my normal user doesn't update past 3.4.4

This happens because conda updates to the latest version available in each *major* Python version. That's why conda updates from 2.7.9 to 2.7.10, instead of jumping to 3.4 or 3.5.
