### ISSUE TITLE
Difficult to change already assigned keyboard shortcuts in 3.0

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#2941]
I want to change the bindings to run the dugger. For example, I want debug step over to be F10. But that is assigned to aprofiler action. In 2.3.8 I would change it to F10, then scroll down to the profiler, and change that to CTRL+F10. Easy peasy.

In 3.0 you now get a dialog box. I enter F10, and it won't accept it because of the conflict with the profiler setting. Of course, if I try to set the profiler setting first I can't do that either. So I'm forced to find some keybinding that isn't use, choose that one, then go change the profile to F10, then come back and change the debug setting to the actual value I want. This is very nonoptimal.

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.0, and it'll be improved even more in 3.1 :-)
