### ISSUE TITLE
Basic Documentation for third party plugins 

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#2944]

**Comment by Nodd** [comment]
Added some docs:
https://github.com/spyder-ide/spyder/wiki/User-plugins
https://github.com/spyder-ide/spyder/wiki/Writing-Plugins
It's very basic and inspired from the old googlecode site: http://web.archive.org/web/20141228215028/https://code.google.com/p/spyderlib/wiki/SpyderPlugins

**Comment by ccordoba12** [comment]
Thanks @Nodd!!

**Comment by ccordoba12** [comment]
This can be improved once we merge the `split-plugins` branch.

**Comment by ccordoba12** [comment]
Moving to spyder-docs.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-docs #88](https://github.com/spyder-ide/spyder-docs/issues/88) via [**ZenHub**](https://www.zenhub.com/)
