### ISSUE TITLE
chortcuts changing doesn't work

### ISSUE THREAD

**Issue by AlexLuya** [spyder-ide/spyder#2947]
I tried to change two shortcuts:

       editor.......toggle comment.......Ctrl(Mod3)+Blackslash
       editor.......code completion......Shift(Mod3)+Space

but after restart spyder,press,

       Ctrl+Backslash             Nothing happended
       Ctrl+Space                 Space got input

 What is the problem here?

**Comment by goanpeca** [comment]
@AlexLuya can you provide more information regarding the spyder version you are using, OS... etc ?

**Comment by AlexLuya** [comment]
@goanpeca Ubuntu 14.04 64bit + Spyder 2.3.8 is used in my laptop

**Comment by ccordoba12** [comment]
This is already fixed in Spyder 3.0 (not released yet). It will be released in a couple of months, sorry for the inconvenience in the meantime :-)

**Comment by AlexLuya** [comment]
Thanks,it is a long time,any workaround?
