### ISSUE TITLE
Version 3.0.0b2 segfaults when pressing Ctrl-I

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#2949]
Spyder version 3.0.0b2, as well as the current HEAD, crashes with a segmentation fault when I press Ctrl-I to view the documentation of some function. It does not crash if the cursor is on some name without documentation. This is on Anaconda (just updated) with Python 3.5 on Debian Linux. Spyder version 3.0.0b1 works fine.

The core dump looks similar to https://github.com/ContinuumIO/anaconda-issues/issues/272 : I checked the top five frames and they are the same (except for pointers and path names).

Spyder dependencies:

```
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
nbconvert >=4.0    :  4.1.0 (OK)
numpy >=1.7        :  1.10.2 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  3.4.1 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
```

Conda info:

```
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/jitse/misc/anaconda3  (writable)
  default environment : /home/jitse/misc/anaconda3
     envs directories : /home/jitse/misc/anaconda3/envs
        package cache : /home/jitse/misc/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by jitseniesen** [comment]
I think this was introduced in commit b27bf72e576e6f0aedec9cb097ba3f73248e1957; the previous commit does not segfault. 

If in the faulty commit, I replace line 210 in spinxify,py, which reads `sphinx_app.build(None, [rst_name])`, by `return warning('Sphinx skipped')`, then the segfault also disappears.

I do not know how to proceed.

**Comment by stonebig** [comment]
I have no crash with version https://github.com/spyder-ide/spyder/commit/0bb07e05a051f0f0e903733ccef907caabcc8815 on winpython 3.4Qt4/3.4Qt5/3.5Qt4 

I did avoid Spyder re-generating the documentation at the install  time, and I have Sphinxx 1.3.4 now.

````
try:
    if PY3:
        import this_is_nonsense  # stonebig makes it fails on python3
    from sphinx import setup_command
````

**Comment by ccordoba12** [comment]
@stonebig, do you think we shouldn't include documentation in our wheels? Why?

**Comment by stonebig** [comment]
I couldn't get sphinx working on my vs2010-less Python 3.4.

So I downloaded the source github + avoided using sphinx, in hope the existing documentation was preserved in the source tree.

maybe I miss-interpret and really lost a documentation that way?

**Comment by ccordoba12** [comment]
Don't worry about this issue, I think it only happens on Linux, and it seems to be triggered by a problem in our Qt shim, not by Sphinx.

**Comment by ccordoba12** [comment]
@jitseniesen, I can't reproduce your bug, sorry.

Besides, the fix you proposed would make the Object Inspector unusable.

**Comment by jitseniesen** [comment]
@ccordoba12 Maybe I'm doing something wrong; it is all quite new to me. Below are the steps I used to try to make a clean environment. I get the crash on two machines, one running Debian testing and one running CentOS 6.7.

```
$ conda create --name spyder-dev --channel https://conda.anaconda.org/spyder-ide python=3.5 spyder
$ source activate spyder-dev
$ git clone https://github.com/spyder-ide/spyder.git
$ cd spyder
$ python bootstrap.py -- --reset
$ python bootstrap.py 
Executing Spyder from source checkout
Revision 7bae783, Branch: master
01. Patched sys.path with /home/jitse/spyder-crash/spyder
02. PyQt4 is detected, selecting
03. Imported Spyder 3.0.0dev
    [Python 3.5.1 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux]
04. Executing spyder.main()
Bootstrap completed in 00:00:03.9362
```

Then write 'print' at the bottom of the file in the editor and press Ctrl-I.

Related may be that on the Debian machine, but not on the CentOS machine, the IPython console is stuck in "Connecting to kernel"; I had not noticed this before.

The 'fix' I mentioned was not meant as a fix. I mentioned it in the hope that it would help people fix the bug. Sorry for not making that clear.

**Comment by jitseniesen** [comment]
The issue has disappeared in the mean time on my Debian computer (possibly because I updated something but it will be hard to figure out what). However, it persists on my CentOS computer. 

One interesting detail that I noted today: On the CentOS computer, I get a segfault if I run spyder using `python bootstrap.py` in a git cloned directory, regardless of whether I use the v3.0.0b2 revision or the current head revision. However, when I run spyder v3.0.0b2 installed via conda, Ctrl-I works fine.

This led me to study `bootstrap.py` in more detail. The critical line is line 140, `versions = get_versions(reporev=False)`, in the fragment reproduced below.

```python
# Checking versions (among other things, this has the effect of setting the
# QT_API environment variable if this has not yet been done just above)
from spyderlib import get_versions
versions = get_versions(reporev=False)
print("03. Imported Spyder %s" % versions['spyder'])
print("    [Python %s %dbits, Qt %s, %s %s on %s]" % \
      (versions['python'], versions['bitness'], versions['qt'],
       versions['qt_api'], versions['qt_api_ver'], versions['system']))
```

If I comment out that line, and the following print statements that use the result, then Ctrl-I works. If I don't comment out that line, then Ctrl-I leads to a segfault. If I don't comment out that line, but move the line `from spyderlib.app import start` from further down bootstrap.py so that it is just above the get_versions line, then Ctrl-I works fine again.

I'm afraid the whole issue still leaves me stumped. It seems the import statements have a side effect (see also the reference to QT_API in the comment just above the get_versions line), but I don't know enough on how import works in Python. Any hints would be welcome, but I'm glad that at least I found a work-around for my personal use (and nobody else seems to be suffering from this issue).

**Comment by ccordoba12** [comment]
Thanks a lot for digging further in this problem @jitseniesen :-) It's really appreciated!!

I think the problem is `get_versions` is placed in a module where a Qt import also happens to be, and that's messing `Ctrl+I`.

**Comment by ccordoba12** [comment]
@jitseniesen, is this still an issue for you? I mean, even after we have moved to use `qtpy`?

**Comment by jitseniesen** [comment]
Ah, I forgot about this. The issue disappeared, both for the dev branch and for Spyder 3.0.0b2 installed via Anaconda. I don't know what actually resolved it, perhaps some package that I updated, but I'm going to close.
