### ISSUE TITLE
windows 7 64 spyder-v3.0.0b2: Project Explorer: File New Module - issue - No Save..Related No Complie on run

### ISSUE THREAD

**Issue by HBDunn** [spyder-ide/spyder#2950]
Suspects
 1) Platform setup missing some default Config value (user problem)
 2) .spyderproject file is byte encoded is this normal? below(encoding problem)
 3) install setup problem

.spyderproject file:

 }q(Urelated_projectsq]qUrelative_pythonpathq]UnameqX㄀㄀㄀PyqUopenedqu.

Can use main menu to open new "untitled0" module then save to project directory ok.

Sorry if this is my fault - spent a few hours trying to resolve without any reinstall as development coding can't see more delay.

module base

alabaster==0.7.7
astroid==1.3.8
Babel==2.2.0
cffi==1.4.2
characteristic==14.3.0
colorama==0.3.6
cryptography==1.1.2
cssselect==0.9.1
decorator==4.0.6
docutils==0.12
enum34==1.1.1
functools32==3.2.3.post2
guppy==0.1.10
idna==2.0
ipaddress==1.0.15
ipykernel==4.2.2
ipython==4.0.3
ipython-genutils==0.1.0
jedi==0.8.1
Jinja2==2.8
jsonschema==2.5.1
jupyter-client==4.1.1
jupyter-core==4.0.6
logilab-common==1.1.0
lxml==3.4.4
MarkupSafe==0.23
matplotlib==1.4.3
memory-profiler==0.37
mistune==0.7.1
nbconvert==4.1.0
nbformat==4.0.1
numpy==1.10.1
objgraph==2.0.1
pandas==0.17.1
path.py==8.1.2
pep8==1.6.2
pickleshare==0.6
pockets==0.3
psutil==3.2.2
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.14
PyEVTK==1.0.0
pyflakes==1.0.0
Pygments==2.1
pylint==1.4.4
Pympler==0.4.2
pyOpenSSL==0.15.1
pyparsing==2.0.3
PyQt4==4.11.4
PySide==1.2.4
python-dateutil==2.4.2
*python-qt5==0.2.0* home build for python 2.7
					out of root directory import
					to modules in spyder IDE *OK*
pytz==2015.7
pywin32==219
pyzmq==14.7.0
QtAwesome==0.2.0
qtconsole==4.1.1
QtPy==0.1.3
queuelib==1.4.2
rope==0.10.2
rope-py3k==0.9.4.post1
scikit-learn==0.17
scipy==0.16.0
Scrapy==1.0.3
service-identity==14.0.0
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.3.4
sphinx-rtd-theme==0.1.9
sphinxcontrib-napoleon==0.4.3
spyder==3.0.0b2
sympy==0.7.6.1
tabulate==0.7.5
traitlets==4.1.0
Twisted==15.5.0
w3lib==1.13.0
wheel==0.26.0
XlsxWriter==0.7.7
zmq==0.0.0
zope.interface==4.1.2

**Comment by ccordoba12** [comment]
Projects are in the process of being reworked completely in Spyder 3.0. Please don't use them in the meantime.

I'm closing this issue because we don't plan to fix bugs for the old way we have to define and handle projects.
