### ISSUE TITLE
JavaScript Alert - Could not load the image

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#2953]
On the latest master I'm seeing the below messagebox when I run `bootstrap.py`
![image](https://cloud.githubusercontent.com/assets/881019/12540068/25e56fb0-c34d-11e5-8729-fb45ae207bb1.png)

interestingly, clicking `OK` segfaults Python for me whereas closing the dialog with the `X` lets me proceed with no further (apparent) issues

**Comment by ccordoba12** [comment]
Are you using the branch on PR #2878?

**Comment by dhirschfeld** [comment]
That was on master. I can't seem to repro it on my home PC though so not quite sure what's going on. Will try to debug further and get back to you...

**Comment by dhirschfeld** [comment]
It appears to be something to do with running from a network share - perhaps some sort of permissions issue. If I map the network drive the problem goes away so I'll close this as I don't think there's anything to be fixed on spyder's side.
