### ISSUE TITLE
spyder internal console attribute error

### ISSUE THREAD

**Issue by deltasun** [spyder-ide/spyder#2956]
Hi everybody,

when starting Spyder i get the following error:
AttributeError: 'module' object has no attribute 'phymen_usage'

even if i close the console, the message keeps popping up. 
Despite that, Spyder seems to work, but of course i cannot proprerly work with this message popping up again and again.

The problem has come out after I tried to install some python package (graph-tool, that i even tried to remove without any change in the spyder error). But I really don't see how it could be related.

thank you

**Comment by ccordoba12** [comment]
I don't know why that error appears on Spyder, but you can deactivate internal errors reporting errors by going to

    Tools > Preferences > General > Debugging

and unchecking the option called

    Pop up internal console when internal errors appear
