### ISSUE TITLE
installing github master with setuptools 19.6.1 + pip 8.0.2 hints two issues

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#2962]
error: option --single-version-externally-managed not recognized

normalizing '3.0.0dev' to '3.0.0.dev0'

````
`  Running setup.py install for spyder ... error
    Complete output from command D:\WinPython\basedir34\build\winpython-3.4.4.am
d64\python-3.4.4.amd64\python.exe -u -c "import setuptools, tokenize;__file__='C
:\\Users\\famille\\AppData\\Local\\Temp\\pip-e8xpdyi_-build\\setup.py';exec(comp
ile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __fi
le__, 'exec'))" install --record C:\Users\famille\AppData\Local\Temp\pip-qpsv625
t-record\install-record.txt --single-version-externally-managed --compile:
    D:\WinPython\basedir34\build\winpython-3.4.4.amd64\python-3.4.4.amd64\lib\si
te-packages\setuptools\dist.py:285: UserWarning: Normalizing '3.0.0dev' to '3.0.
0.dev0'
      normalized_version,
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
Command "D:\WinPython\basedir34\build\winpython-3.4.4.amd64\python-3.4.4.amd64\p
ython.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\famille\\AppDa
ta\\Local\\Temp\\pip-e8xpdyi_-build\\setup.py';exec(compile(getattr(tokenize, 'o
pen', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install
--record C:\Users\famille\AppData\Local\Temp\pip-qpsv625t-record\install-record.
txt --single-version-externally-managed --compile" failed with error code 1 in C
:\Users\famille\AppData\Local\Temp\pip-e8xpdyi_-build
````

**Comment by ccordoba12** [comment]
@stonebig, could you clearer? I don't understand what's the error and what we need to do to solve it :-)

**Comment by stonebig** [comment]
well, the error disappeared when retrying... I thought this "--single-version-externally-managed" was coming from spyder, but it looks now more a 'frehs' pip/setuptools issue (playing with new pip and setuptools).

closing.

**Comment by stonebig** [comment]
one of the  pip guys did inquire, and beleive the problem is in Spyder setup.py around `cmdclass=CMDCLASS`

 see https://github.com/pypa/pip/issues/3439#issuecomment-177653149

**Comment by ccordoba12** [comment]
What command are you trying to run? Please start with that :-)

**Comment by stonebig** [comment]
it was `pip install https://github.com/spyder-ide/spyder/archive/master.zip`

**Comment by xavfernandez** [comment]
Hello, to reproduce the issue:

    wget https://github.com/spyder-ide/spyder/archive/master.zip
    # and in a fresh venv (tested on python 2.7 / 3.4)
    pip install -U sphinx pip setuptools
    pip install master.zip --no-deps
    # error: option --single-version-externally-managed not recognized
    pip uninstall sphinx -y
    pip install master.zip --no-deps
    # success

**Comment by stonebig** [comment]
hi @xavfernandez , why this `--no-deps` Don't install package dependencies. ? It's a bit voluntary breaking isn't it ?

**Comment by xavfernandez** [comment]
It's only to make the failure faster :)

**Comment by stonebig** [comment]
ok, but does it proves anything ?

**Comment by xavfernandez** [comment]
Using the installed project without its dependencies has reason to fail.
Installing without its **dependencies** has no reason to fail, installing without its **build dependencies** (also known as setup_requires) has reason to fail.

So let's make it all simpler:

    # and in a fresh venv (tested on python 2.7 / 3.4)
    pip install -U sphinx pip setuptools
    pip install https://github.com/spyder-ide/spyder/archive/master.zip
    # error: option --single-version-externally-managed not recognized
    pip uninstall sphinx -y
    pip install https://github.com/spyder-ide/spyder/archive/master.zip --no-deps
    # success (the --no-deps is needed here so that sphinx is not reinstalled before spyder)

**Comment by stonebig** [comment]
thanks @xavfernandez , I understand now your point.
I'll close the issue for now, supposing the problem doesn't happen in normal use-case.
