### ISSUE TITLE
Find in files results disappear when search path loses focus

### ISSUE THREAD

**Issue by rthouvenin** [spyder-ide/spyder#2963]
When doing a search in the "Find in files" panel, the panel seems to have a bug in the signal handling.

When I open the panel with no item in the search path combo box, the field is pre-filled with the current working directory or the previously searched path. But as soon as I click on the search field to type what I want to search, the search path field is emptied. So even if I was fine with the pre-filled value I have to re-select it. This is the first problem (minor).

Then when I select one item from the combo box (or type one), the search is automatically triggered and results are displayed. If I then try to click on the results (or anywhere else actually) **without validating the entry in the search path field** (with Enter key), the search path field is emptied, and the search results refreshed, that is: emptied also. This is the second problem.
It took me a while to figure out that I have to press Enter to be able to read the search results.

This happens in latest Spyder 3.0.0dev, from what I remember it was working fine in Spyder 2.

I tried to have a look at the code in `findinfiles.py`, but got a bit lost in all the signals emitted by the different components. From what I could understand, I think that when the search path entry is not validated and loses focus, a signal is emitted that will cause the field to be reset with a default value of None and eventually re-run the search. Since the path is now empty, the search has no result and the results box is emptied. It is likely I think that the two problems are related.
I can try to have a better look if someone can give me some pointers or explanation of who emits what signal and when.

**Comment by andfoy** [comment]
@ccordoba12 I think this Issue should be closed since the conflicting combo box was removed on #4056

**Comment by ccordoba12** [comment]
Please add this issue to the list of issues solved by PR #4056 instead.

At the end, that PR is going to solve this issue (even if it does that by removing its cause :-)
