### ISSUE TITLE
Parenthesis highlight in the Editor is inconsistent

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#2965]
## Description

**What steps will reproduce the problem?**
1. Write in a new file: `a=(")")`
2. Put the cursor at the end of the line, observe that the last parenthesis is highlighted in red
3. Put the cursor in the middle of `)"`, observe that the first parenthesis and the one in the string are highlighted in green.

**What is the expected output? What do you see instead?**
The parenthesis highlighter picks up the parenthesis inside the string.

**Please provide any additional information below**
## Version and main components
- Spyder Version: 3.0.0dev 
- Python Version: 3.5.1
- Qt Versions: 5.5.1, PyQt5 5.5.1 on Linux
## Dependencies

```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
nbconvert >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
numpy >=1.7        :  1.10.4 (OK)
sphinx >=0.6.6     :  1.3.4 (OK)
psutil >=0.3       :  3.3.0 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  None (NOK)
pylint >=0.25      :  1.5.4 (OK)

```

**Comment by david340804** [comment]
bump

**Comment by bcolsen** [comment]
@david340804 I guess not many people are using brackets in strings. 

If you or anyone else wants to take a shot at fixing this the current bracket matching is done here:

https://github.com/spyder-ide/spyder/blob/f0a2ea73cac22d7658299706cd90c5226f0d1311/spyder/plugins/editor/widgets/base.py#L462-L467

This code could be replaced by a calling to some newer logic similar to this function from editor utils:

https://github.com/spyder-ide/spyder/blob/0ca590f47d323a0b6e23f71e24d026add37e8800/spyder/plugins/editor/utils/editor.py#L743-L749

Don't know if that would work but it looks like a great starting place.
