### ISSUE TITLE
Variable explorer gives an error when copying values

### ISSUE THREAD

**Issue by mvkrdndm** [spyder-ide/spyder#2968]
write code then f8 for analyse with pep8 then come to convention part (the warning about missing doc string or any warning right click then select history and program shut down itself

also noticed now in variable explorer same thing happens when i right click and copy value program crashes

*winpython 3.4 with qt5  x64
*well i am newbie to python and spyder but looks like bug
*spyder version 3.0 dev # #

**Comment by ccordoba12** [comment]
Please describe a clear *step by step* procedure to reproduce your problem. For example, I don't understand what you mean by

> right click then select history

What history?

**Comment by mvkrdndm** [comment]
i switch back to 2.3.8 now it works   pylint version 1.5.4 now on spyder 2.3.8 (working one)
old one was pylint version 1.5.1  on spyder 3.0.0.dev0   ( not working ) it was broken maybe pylint was outdated it came by packaged from winpython so i did not checked sorry for disturbition.

problem was i could not copy values from variable explorer.this pic belongs to version 2.3.8 for demonstration porpose ,in version spyder 3.0.0 dev0 there was also  history there

![spydercrash](https://cloud.githubusercontent.com/assets/16892782/12875848/f12813cc-cdfb-11e5-99f2-39d09085846f.png)

**Comment by mvkrdndm** [comment]
today i installed **spyder 3.0.0b2**

IPython >=3.0      :  4.1.1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
numpy >=1.7        :  1.10.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=13.0.0       :  15.2.0 (OK)

Again same thing it does not copy value from variable explorer and in console says:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyderlib\widgets\variableexplorer\collectionseditor.py", line 1069, in copy
    clipboard.setText('\n'.join(clipl))
TypeError: sequence item 0: expected str instance, int found
