### ISSUE TITLE
Profiling hangs/freezes Spyder

### ISSUE THREAD

**Issue by bilderbuchi** [spyder-ide/spyder#2976]
Hi!

When trying to profile a script in Spyder, it hangs (permanently afaict) in the "sorting data" stage, as soon as I use an external (read: non-stdlib) package.

Repro code:
```
# import itertools  # works OK
import requests  # hangs
# import matplotlib.pyplot as plt  # hangs
# import numpy  # hangs
``` 

I'm using Anaconda on Windows 8.1

* Spyder Version: 2.3.8 
* Python Version: 3.5.1
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Windows

```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1 (OK)
IPython >=1.0      :  4.0.3 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this problem for our next major release (i.e. Spyder 3.0).

**Comment by bilderbuchi** [comment]
thank you. :-)

**Comment by dingdinglhz** [comment]
I think I might have the same issue.

**Comment by ccordoba12** [comment]
Sorry but I'm unable to reproduce this problem in Spyder 3.0 beta3. Please report back after Spyder 3.0 final is released (in a couple of weeks) to let us know if this problem was fixed for you too :-)

**Comment by NGJROMO** [comment]
Got the same problem, will let you know if Spyder 3.0 fixes this issue for me

**Comment by NGJROMO** [comment]
And I can confirm that the issue disappears when upgrading to 3.0 beta3. Good work guys.

I Updated by typing:

```
conda update qt pyqt
pip install --pre -U spyder
```

**Comment by ccordoba12** [comment]
Ok, thanks for the confirmation @NGJROMO!

**Comment by bilderbuchi** [comment]
Thanks for confirming! (I'm not on 3.0 beta, yet)
