### ISSUE TITLE
Tab doesn't insert spaces if cursor is next to a word in a comment

### ISSUE THREAD

**Issue by dacoex** [spyder-ide/spyder#2977]
Using latest WinPython and the shipped spyder 3.0.0dev:

After entering a code annotation, e.g.

`#FIXME`

it is not possible to enter 4 spaces using tab key.

Only after hitting space key once, tab works.

**Comment by ccordoba12** [comment]
Tab is also used to do code completions, so if you don't add a space after `#FIXME` it won't work.

However, trying to trigger code completions on comments doesn't make sense. @blink1073, what do you think about this?

**Comment by blink1073** [comment]
I'd say it does make sense to have tab completions in comments, but do not feel strongly one way or the other.  We could default to a tab if there are no valid completions.

**Comment by dacoex** [comment]
Another more user centric option would be:

Insert the comment with tab then hit CTRL+1 to comment.

This could simply be added to the docs.

**Comment by ccordoba12** [comment]
Completions on comments is going to be fixed in a future Spyder release (probably 3.2)
