### ISSUE TITLE
QTextCursor::setPosition: Position '16786' out of range 

### ISSUE THREAD

**Issue by slehar** [spyder-ide/spyder#2979]
## Description

This is a continuation of issue #1392 I have found a test case that reproduces the problem _almost_ reliably, hopefully this might help us converge on the problem. It is a program that tests indexed images, reading their pixel values and printing to the IPython terminal. The source code and image follow.

[QTextCursorError.py.gz](https://github.com/ipython/ipython/files/125144/QTextCursorError.py.gz)

![burrindx](https://cloud.githubusercontent.com/assets/4096048/12954602/46c919be-cfed-11e5-94fd-abf849379989.png)

**What steps will reproduce the problem?**

To reproduce the problem:

[1]: Run the program, move your cursor around in the image, observe (x,y) coordinates printed continuously on the IPython command line.

[2]: Move the image window to a different location

[3]: In the IPython console type some text, preferably meaningful text like "dir()"

[4]: Move your cursor around in the image again.

**What is the expected output? 

A continuous output of coordinates on the IPython command line

x= 14, y=  8, pixel=  0
x= 14, y=  8, pixel=  0
x= 14, y=  8, pixel=  0
x= 15, y=  8, pixel=  0
x= 14, y=  8, pixel=  0
x= 14, y=  8, pixel=  0
x= 14, y=  8, pixel=  0

What do you see instead?**

Repeat steps 2-4 and eventually step 4 will produce the error

QTextCursor::setPosition: Position '13547' out of range
QTextCursor::setPosition: Position '13619' out of range
QTextCursor::setPosition: Position '13691' out of range
QTextCursor::setPosition: Position '13763' out of range
QTextCursor::setPosition: Position '13811' out of range
QTextCursor::setPosition: Position '13835' out of range
QTextCursor::setPosition: Position '13907' out of range
...

appearing back in the console window (where I typed "spyder&" to launch spyder) whenever you move the mouse in the image.

So the problem seems to involve a loss of synch between the window coordinates or something.

[QTextCursorError.py.gz](https://github.com/spyder-ide/spyder/files/125174/QTextCursorError.py.gz)
![burrindx](https://cloud.githubusercontent.com/assets/4096048/12954995/0997f6f8-cfef-11e5-95fe-4e7a40d1cc2d.png)
**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.7 
- Python Version: 2.7.10
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.1.0 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.2 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
This is an error in qtconsole, and it's fixed already.
