### ISSUE TITLE
Add feature that shows vertical lines to help identifying indentation structure

### ISSUE THREAD

**Issue by webcsm** [spyder-ide/spyder#2987]

**Comment by ccordoba12** [comment]
There is already an option under the menu entry

    Source > Show blank spaces

that helps with indentation.

Unfortunately, adding vertical lines is not an easy task, so we're not planning to do it right now.

**Comment by webcsm** [comment]
I totally understand. Thanks for your quick reply.

**Comment by webcsm** [comment]
I saw that you have a number of issues there. Do you accept help with PRs? I might help with something.

**Comment by ccordoba12** [comment]
Sure, help is always welcome!

Issues in `wishlist` are things we think are interesting but that we don't plan to implement ourselves.

**Comment by chandu8542** [comment]
@ccordoba12 . IS there any update on adding vertical line feature to demarcate the code indentation? After  3-4 level of indentation, we are lost in adjusting indentation.

**Comment by ccordoba12** [comment]
We'll take a look at this for Spyder 4. Sorry, but it's not possible to add it to Spyder 3 because it requires several internal changes.

**Comment by zizzipupp** [comment]
Slightly off-topic, sorry, but when is Spyder 4 scheduled for release?

**Comment by ccordoba12** [comment]
During the last quarter of this year.

**Comment by Wurtzinator** [comment]
@ccordoba12 

Will the indentation line be implemented anytime soon or are there other extensions?
I love Spdyer, but I really need  the indentation lines as a newbie :D

**Comment by ccordoba12** [comment]
It's already in beta1.

**Comment by LovLearn** [comment]
Hello @ccordoba12 ,
Could you please give me the direction on how to have find beta1 and have it set up? I am new to spyder. Thanks.

**Comment by Dodelo** [comment]
> Hello @ccordoba12 ,
> Could you please give me the direction on how to have find beta1 and have it set up? I am new to spyder. Thanks.

In case you're still interested: look over here https://github.com/spyder-ide/spyder/releases/tag/v4.0.0b1

**Comment by abhijit1990** [comment]
still not added

**Comment by vivalaelectro** [comment]
> still not added

I see the feature in Spyder IDE 5.4.3. The option
```
Source > Show indent guides
```
must be activated to show the vertical lines.

**Comment by ccordoba12** [comment]
That's right @vivalaelectro. We haven't enabled this feature by default because it still has some issues that we hope to solve in Spyder 6.
