### ISSUE TITLE
Simple Outline with Tree Architecture

### ISSUE THREAD

**Issue by arita291** [spyder-ide/spyder#2988]
Example:  Show 3 levels of tree in outline, and parsing is done with simple syntax:
    zz.xxx.yyy   (1.1.)

+#1.------------------Title 1
   +#1.1-------------------Ttitle 1.1
       +#1.1.2 ----------------Titlte 1.1.2

Reasons: sometimes we have a very long code file, having collapsing tree would be good
to jump into the right piece of code.

2.) For performance reason, manual update of outline.

**Comment by ccordoba12** [comment]
Sorry, I don't think we're going to implement this. Moving through a long file is going to be improved in Spyder 3.0 thanks to a function and file switcher, very similar to the Sublime text one.

For reference, see section **3** of this post:

http://filipminev.com/post/14262857223/9-reasons-you-must-install-sublime-text-2-code

**Comment by Nodd** [comment]
Have you looked at the outline pane ? It already has a tree architecture (not with numbered titles though).

I feel obligated to mention that the recommended way of structuring code is via functions or class, not with comment headers. Sometimes the problem is in the files, not in the IDE :smile:
