### ISSUE TITLE
Add tests for op plugins

### ISSUE THREAD

**Issue by simonm3** [spyder-ide/spyder#2989]
I have tried to create an io plugin. It loads correctly and works if I run my own tests; and I have set the four variables FORMAT_X. However it never calls the save or load functions. 

I have checked the source code for spyder and added some logging and it looks to me as if iofunctions save and load are never actually called. Has the interface changed? Or have I missed something - in which case is there a working example of a simple IO plugin for a common file format?

**Comment by Nodd** [comment]
Sorry for answering this late... Plugin management has evolved a lot recently, which spyder version are you using ?
I just added some very basic documentation about plugins (valid for spyder v3.0.0beta3 onwards):
* https://github.com/spyder-ide/spyder/wiki/User-plugins
* https://github.com/spyder-ide/spyder/wiki/Writing-Plugins

**Comment by simonm3** [comment]
2.3.8.

I still cannot get it to work. Tests fine as a standalone but could not get
it to integrate with spyder.

Simon

**Comment by Nodd** [comment]
Try to put your `io_*.py` file in the spyderplugins directory (alongside these files: https://github.com/spyder-ide/spyder/tree/v2.3.8/spyderplugins).

**Comment by simonm3** [comment]
That is where it was.

Taking the example of the DICOM plugin I am not sure what this is supposed
to do. I donwload a dicom file and open it in spyder then I just see
garbled text. If I delete the dicom plugin and restart spyder it does the
same. I am guessing the plugin is supposed to format it in a different way
perhaps just show the text elements?

I added some messages to your source code that confirm the plugins are
loading when spyder starts but the "load" functions do not seem to get
called when a file is opened.

Simon

**Comment by ccordoba12** [comment]
@simonm3, if I'm not mistaken you need to install pydicom for that plugin to work.

**Comment by Nodd** [comment]
That doesn't explain why his plugin doesn't work.

Do you see your xtension when running this in the internal console:

```python
import spyderlib.app.spyder
print(spyderlib.app.spyder.IMPORT_EXT)
```

**Comment by simonm3** [comment]
ImportError: No module named 'spyderlib.app'??

Though I am pretty sure it is loaded because I edited the spyder source to
put some logging statements in and it shows in my log that they are loaded.
The problem is that the save/load functions are not called.

**Comment by Nodd** [comment]
Sorry, this is with master. Try with `spyderlib.spyder`.
`IMPORT_EXT` stores which extensions can be loaded by the variable explorer. Maybe your module was imported but not taken in account in spyder.

**Comment by simonm3** [comment]
Yes it shows up in there. However......my extension is for ipynb. I note
that ipynb is already in the list of extensions on file/saveas. Can my
extension override that?

**Comment by Nodd** [comment]
I have no idea :disappointed: I worked a bit on the loading part of IO plugins but I don't know how they are used afterwards.
One thing to test is to change temporarily the extension to `.myipynb` for example (both the file and in code), and check if it works.

**Comment by simonm3** [comment]
OK tried that. It is loaded in the list of extensions.

I looked at the spyder source code a few months ago to try and figure this
out and it seemed to me that the bit that calls the extension function
"load" is never called - I put logging statements in there and they are not
fired. Does it actually work with other IO extensions?

Simon

**Comment by Nodd** [comment]
I don't know if others work, I never use them...

**Comment by ccordoba12** [comment]
Closing because this is too old now.
