### ISSUE TITLE
Crash report related to find & replace all 

### ISSUE THREAD

**Issue by muratabur** [spyder-ide/spyder#2990]
Did a find + replace all which crashed the system. Was able to reproduce locally several times.

> Ctrl + H
> Find: 0010
> Replace: '0010'

Replace one by one works, replace all gives a seg fault

**Comment by oscargus** [comment]
I've tried a number of combinations here, assuming that the single ticks are somehow involved. I have not managed to create any type of issue with it, so I believe that this has been solved through other changes.

**Comment by goanpeca** [comment]
Thanks for checking @oscargus
