### ISSUE TITLE
Zoom not working when using only CodeEditor

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#2994]
Hi,
I am using CodeEditor from spyderlib.widgets.sourcecode.codeeditor.
Everything works fine except the three "zoom" commands from the popup menu do nothing. The problem can be reproduced if one runs the above py file, which starts a test for the CodeEditor class.
I cannot find an easy fix. Please advise.
The very last command ("run selection or current line") doesn't work either but I don't need it.
Thanks!
Konstantin
**version** = '3.0.0dev', python 2.7.10, Qt 4.8.7, PyQt 4.11.4

**Comment by ccordoba12** [comment]
Those options emit Qt signals that are handled by our Editor plugin. That's why they don't work only by themselves.

If you want to change this behavior, you can send us a pull request that implement things in CodeEditor itself.

**Comment by kklmn** [comment]
Ah, now I see the handlers in Editor, somehow I overlooked them. Thanks for the tip!
