### ISSUE TITLE
Variable explorer - Sequence break with wrong mapping

### ISSUE THREAD

**Issue by feiyingplus** [spyder-ide/spyder#2995]
the Name, Type, Size mapped wrong to each other after click each label name ( for order by), only the first python execution get the correct value. next time need to delete all content in variable explorer and re-run the code. 
please refer to the attached document for detail screen-shot.
[Spyder issue - Variable explorer .docx](https://github.com/spyder-ide/spyder/files/137574/Spyder.issue.-.Variable.explorer.docx)

**Comment by jitseniesen** [comment]
Thanks for the report. Here is how I can reproduce it. 

Give the following commands in the console:
```python
a = 'b'
x = [1, 2]
integers = list(range(1, 151))
evens = [n for n in integers if n % 2 == 0]
```
Open the variable explorer (everything looks fine). In the variable explorer, click on `Type` to sort that column. The variable explorer now says that `x` has length 150. In fact, `x` has length 2. The value is displayed correctly.
