### ISSUE TITLE
Interactive mode doesn't work in in Spyder Ipython

### ISSUE THREAD

**Issue by ualsbombe** [spyder-ide/spyder#2996]
Dear developers

I was directed to this list from the mne-python community: https://github.com/mne-tools/mne-python/issues/2909#issuecomment-185885136

The issue is that the block argument in mne.epochs.plot_epochs doesn't halt the programme as intended. (it should implement this:         plt_show(show, block=block))

The mne-developers suspect it to be a spyder issue, but admittedly I only have the problem when using the ipython interpreter and not the python interpreter

```
epochses = []

for i in range(len(positions)):
    input_file = './3_epochs/' + positions[i] + '_eog_auto_cleaned-epo.fif'
    epochs = mne.read_epochs(input_file)
    mne.epochs.plot_epochs(epochs, picks=[0], block=True) ## only MISC010
    epochses.append(epochs)
    output_file = './4_cleaned_epochs/' + positions[i] + \
                '_manually_cleaned-epo.fif'
    epochs.save(output_file)
```

Anaconda: 2.5.0
Python: 2.7.11
IPython: 4.0.3
Spyder: 2.3.8
mne: 0.11.0
matplotlib: 1.5.1

**Comment by stfnrpplngr** [comment]
I am having the same problem:

Anaconda custom (64-bit)| (default, Jul 20 2017, 12:30:02) [MSC v.1900 64 bit (AMD64)]
Python 3.6.2 
IPython 6.1.0
Spyder 3.2.3
Matplotlib: 2.0.2
MNE: 0.15.dev0

**Comment by ccordoba12** [comment]
@stfnrpplngr, please deactivate our Matplotlib integration in

    Preferences > IPython console > Graphics > Activate support

That should fix this problem.
