### ISSUE TITLE
Ignore Last Opened Files on Start up

### ISSUE THREAD

**Issue by AlJohri** [spyder-ide/spyder#2998]
I was trying to figure out how to ignore the last opened files on start up since I saw an option in the code `ignore_last_opened_files`. I couldn't find any settings or preferences that would enable this.

The spyder.ini has several similar options related to working directories but not related to the files opened at startup.

```
spyder.ini
7:check_updates_on_startup = False
112:pythonstartup/default = True
126:pythonstartup/custom = False
138:pythonstartup = /Users/johria/.pyenv/versions/3.5.1/lib/python3.5/site-packages/spyderlib/scientific_startup.py
147:startup/run_file =
154:startup/run_lines =
161:startup/use_run_file = False
348:startup/use_last_directory = False
357:startup/use_fixed_directory = True
358:startup/fixed_directory = /Users/johria/Development
```

I ended up changing the line `self.editor = Editor(self, ignore_last_opened_files=True)` within `spyderlib/spyder.py`.

Is there a better approach?

**Comment by ccordoba12** [comment]
We haven't thought about offering that option to our users, and I don't know if it worth the effort.

@goanpeca, what do you think?

**Comment by goanpeca** [comment]
I don't even understand the problem :-p

**Comment by ccordoba12** [comment]
I think @AlJohri doesn't want any file open by default when he closes and opens Spyder again.

**Comment by fergalm** [comment]
I was just googling how to set this option.  I'm often working on multiple projects. When I start spyder to work on Project2, it's disorientating to see a bunch of files from Project1 get loaded automatically.

**Comment by ccordoba12** [comment]
@fergalm, your problem was solved in Spyder 3 with our revamped Projects support: if you create two Spyder projects for each of your work projects, then each one will maintain its own list of open files that will be restored when you open the same project again.

**Comment by fergalm** [comment]
Thanks, I'll have to try it out. This issue should probably be removed from the wishlist at https://github.com/spyder-ide/spyder/milestone/24
