### ISSUE TITLE
add cpu usage at the window corner

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#3002]
There's a memory usage in the window, can we add the cpu usage as wekk?

**Comment by goanpeca** [comment]
This functionality is already implemented in Spyder, check the preferences.

![image](https://cloud.githubusercontent.com/assets/3627835/13241188/c638872a-d9b6-11e5-97bc-415e23d26a4b.png)

**Comment by ccordoba12** [comment]
@fayeshine, you need the `psutil` package installed in your system for Spyder to show cpu show along with memory usage.
