### ISSUE TITLE
LG

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#3004]
I can not find the file "myapp.log" at current directory：

import logging
logging.basicConfig(level=logging.DEBUG,
                format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
                datefmt='%a, %d %b %Y %H:%M:%S',
                filename='myapp.log',
                filemode='w')
logging.debug('This is debug message')
logging.info('This is info message')
logging.warning('This is warning message')

**Comment by ccordoba12** [comment]
I'm sorry but this not a Spyder bug or problem, but instead a problem with your code. So I'm closing this issue.

You could ask about coding problems in a website called StackOverflow.

**Comment by A-Pai** [comment]
@ccordoba12 but I can find the file "myapp.log" if I use IDLE,so I think there is no error with my code

**Comment by Nodd** [comment]
This is a duplicate of #2572, see there for more informations.
