### ISSUE TITLE
Getting "Spyder already running" warning when it's not

### ISSUE THREAD

**Issue by 4c656554** [spyder-ide/spyder#3005]
## Description of your problem

On windows 7 I get a 

**What steps will reproduce the problem?**
1. Open sypder from cmd (spyder.bat)
2. Close (pressing X in rop right)
3. Attempt to open spyder again (cmd spyder.exe or .bat)

**What is the expected output? What do you see instead?**

I expect spyder to open I get this (which does work if I open a new instance)

```
Spyder is already running. If you want to open a new
instance, please pass to it the --new-instance option
```

**Please provide any additional information below**

This is not a show-stopping issue. It seems as though the lockfile mechanism isn't being properly released. I'm not sure how to "wipe the slate".
## Versions and main components
- Spyder Version: 2.5.3.2
- Python Version: 2.7.10
- Operating system: Windows 7
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0   :  2.4.1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

Many thanks for a great application.

**Comment by 4c656554** [comment]
Note. This persists even after a reboot.

**Comment by ccordoba12** [comment]
Please update Spyder to 2.3.8 and try again.

**Comment by 4c656554** [comment]
Thanks. The issue persists though (also the spyder.exe was removed - I launched using spdyer.bat).

I upgraded using `pip install spyder --upgrade `

**Comment by bobjuanson** [comment]
I am encountering this issue as well. It persists through reboot. I have upgraded spyder and it continues.

I believe it started because I attempted to launch spyder through the dashboard, and it did not respond. I then launched it from console and encountered the issue.

Any suggestions on how to resolve this?

**Comment by ccordoba12** [comment]
You need to look for a directory called `.spyder2` in your `Users\<your account>` directory, the find a file called `spyder.lock` and remove it.

**Comment by allanzelener** [comment]
Just ran into this issue with Spyder 3. The directory with the `spyder.lock` file now seems to be `<home dir>/.config/spyder[-py3]`.

**Comment by equaeghe** [comment]
(Spyder 3.0.2 on Linux) The lock file seems to be a symlink to some other file. I encountered this issue and the symlink was broken. So a check to find out whether this symlink is broken may need to be performed.

**Comment by ccordoba12** [comment]
We'll improve our detection algorithm in Spyder 3.1. This is implemented in pull request #3659.

**Comment by feresm** [comment]
I could not find neither spyder.lock nor .spyder2 directory. So I am stuck.

**Comment by ccordoba12** [comment]
@feresm, open a terminal and run

    cd ~/.spyder

or
    ~/.spyder-py3

in case your running Spyder with Python 3, then

    rm -f spyder.lock

and finally start Spyder again.

**Comment by feresm** [comment]
Thanks Carlos, but I had already solved the issue. Let me tell what I did as it can help others. I use anaconda and I discovered that when you update spider it does not remove the previous versions. Then, I removed them and reinstalled the version 3.0.2 rebooted and it worked. Maybe a coincidence, maybe not. Anyway, I am using python 2.7 (mac) and none f the directories you listed before in this thread existed (or I did not find them). thx again.

**Comment by equaeghe** [comment]
Hit this issue again with spyder 3.0.2.

**Comment by ccordoba12** [comment]
As the milestone clearly states, this was fixed in Spyder 3.1, so please update.

**Comment by charanjitpabla** [comment]
This is happening to me. I am running spyder 3.3.4 version under anaconda3. Any help?

**Comment by jeromemaleski** [comment]
I just had this problem after updating spyder. I deleted .spyder2-py3 in my user directory and this fixed my problem.

**Comment by biazzotto** [comment]
Same problem here:
```
Spyder is already running. If you want to open a new
instance, please pass to it the --new-instance option
```
Spyder 4.1.3
Python 3.7.6
Windows 10
 from Anaconda, using conda-forge repository

**Comment by pawansutar** [comment]
run command spyder - - reset on anaconda prompt

**Comment by Cemalbc** [comment]
> Same problem here:
> 
> ```
> Spyder is already running. If you want to open a new
> instance, please pass to it the --new-instance option
> ```
> 
> Spyder 4.1.3
> Python 3.7.6
> Windows 10
> under Anaconda 3, using conda-forge repository

I met the same problem. I use command in anaconda prompt: spyder --new-instance. Hope this problem will be fixed.

**Comment by spri902** [comment]
@60south @jogareau @ccordoba12 
I am having the same issue. Spyder 5.3.2 Ubuntu 20.04. Every time I open Spyder the spyder.lock file is created (naturally). It doesn't get removed when the session is ended however.  This was causing Ubuntu to hang and ultimately preventing ssh back into the machine. Now I have to remove the spyder.lock file after each session.

**Comment by ccordoba12** [comment]
@spri902, could you open a new issue and better describe your problem? It seems to be different from this one because your connecting through SSH to a remote machine and then starting Spyder.

**Comment by spri902** [comment]
@ccordoba12  Yep, will do
