### ISSUE TITLE
Can not change font size anyway!

### ISSUE THREAD

**Issue by T800GHB** [spyder-ide/spyder#3007]
## Description
When i open spyder, the font in editor and ipython console will always keep very small.
I can change it by preferences or file in ./spy2-3
**What steps will reproduce the problem?**

1. linux mint 17.3
2. anaconda3-2.2~2.5
3. type "spyder" in terminal.

**What is the expected output? What do you see instead?**
![2016-02-25 21 34 48](https://cloud.githubusercontent.com/assets/5126190/13321172/6e18bba6-dc08-11e5-85e0-562200c9769a.png)

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.7 
* Python Version: 3.5.0 or 3.4.3
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
IPython >=1.0      :  4.0.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.2.2 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  14.7.0 (OK)

```

**Comment by ccordoba12** [comment]
I don't know what's happening, sorry.

**Comment by ccordoba12** [comment]
Closing because this doesn't seem a problem related to Spyder.
