### ISSUE TITLE
DataFrame editor should do a stable sort

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3010]
I am using Spyder 2.3.5.2 from WinPython-64bit-3.4.3.5.

I noticed that clicking column headers in the DataFrame editor does not sort the table [in a stable way](https://en.wikipedia.org/wiki/Sorting_algorithm#Stability). This especially means that one cannot reach a hierarchical sorting.

**Comment by ccordoba12** [comment]
I don't understand what you mean. Please post examples about what problem are you seeing and what's the expected output, as it's explicitly demanded in our issue template.

Also, for next time, please don't dismiss the template contents. That saves us a lot of time.

**Comment by jondo** [comment]
> please don't dismiss the template contents

You are right. Strangely, I cannot come up with a small example. I will reopen this when I find an example again.

**Comment by jondo** [comment]
Ok, I've got it now:

- Define `df = pd.DataFrame([[2,14],[2,13],[2,16],[1,3],[2,9],[1,15],[1,17],[2,2],[2,10],[1,6],[2,5],[2,8],[1,11],[1,1],[1,12],[1,4],[2,7]])`
- Open df in the DataFrame editor.
- Try to sort hierarchically. For this, click the header of column '1', then the header of column '0'.

Expected result: df is hierarchically sorted by the columns '0' and '1'.

Observed result: Within the value '2' of column '0', the values of column '1' have become unsorted again.

Interestingly, the hierarchical sorting works for smaller DataFrames, e.g. when `[1,17]` is removed from the above example.

**Comment by jitseniesen** [comment]
I think this is quite easy to implement by using telling DataFrame.sort to use mergesort (which is stable) in the dataframe editor. A potential problem is that mergesort has a higher memory cost according to the [numpy manual](http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.sort.html), but I don't think that's likely to be an issue for us.

**Comment by ccordoba12** [comment]
PR coming? ;-)

**Comment by Nodd** [comment]
@ccordoba12 Admit it, it's an automated answer ! ;o)
