### ISSUE TITLE
Crash when ShellBaseWidget.flush() is called during Qt paint event processing

### ISSUE THREAD

**Issue by uentity** [spyder-ide/spyder#3017]
## Description of your problem

Application crashes when something gets printed into error stream during some widget's paint event processing.

**What steps will reproduce the problem?**

Problem is hard to reproduce, but I can explain it. Suppose you're in process of drawing some Qt widget (in my case it's pyqtgraph's `CurveItem`). And, for example, some calculations produce warning that gets printed to overrided error stream. So, `InternalShell.stderr_avail()` is called which subsequently calls `ShellBaseWidget.flush()`, which, in turn, calls `QCoreApplication.processEvents()` and application crashes in this point and Qt is printing messages that infinite repaint is detected.

I think that `QCoreApplication.processEvents()` reissue paint event processing while previous paint isn't finished and we fall into the same loop again and again.

Why `QCoreApplication.processEvents()` is called? If I comment it out, everything runs fine without crashes and infinite repaint loops (next invoke of `repaint()` is enough for me to correctly display warning message in internal console)

**What is the expected output? What do you see instead?**
Warning (or error) message in internal console without crashing.
## Versions and main components
- Spyder Version: 2.3.7, but I think applicable to 2.3.8 as well
- Python Version: 2.7.10
- Operating system: Linux

**Comment by uentity** [comment]
Update: `self.repaint()` should also be removed in order to prevent segfault.

**Comment by ccordoba12** [comment]
Please post a code example that we can run in our side to test and fix your problem.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
