### ISSUE TITLE
DataFrame editor should first sort up, then down

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3020]
## Description of your problem

When clicking a column header in the DataFrame editor, the column is sorted from high to low. A second click sorts it from low to high. Since sorting from low to high is needed much more often, the effects of the first and the second click should be reversed.

**What steps will reproduce the problem?**

1. Open a Pandas DataFrame in the editor.
2. Click on a column header.

**What is the expected output?**
The DataFrame column is sorted s.t. the lowest value is on top.

**What do you see instead?**
The DataFrame column is sorted s.t. the lowest value is on bottom.

**Please provide any additional information below**
N/A

## Versions and main components

* Spyder Version: 2.3.5.2 from WinPython-64bit-3.4.3.5.
* Python Version: 3.4.3
* Operating system: Windows 7 64-bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0   :  3.2.1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.6.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

**Comment by jitseniesen** [comment]
I think the code was actually supposed to first sort up, then down, just as suggested here; look at the little triangle in the column header of the data frame editor.
