### ISSUE TITLE
No console (python/ipython) in spyder from software-center (ubuntu 14.04)

### ISSUE THREAD

**Issue by kratzert** [spyder-ide/spyder#3028]
## Problem: No (active) console (python/ipython) in Spyder

I recently installed spyder from the Ubuntu 14.04 Software-Center (because I can't install anaconda for other reasons). Not I have the following problem:
- spyder starts without any issues but there is neither an python console nor an ipython console loading. When I try to open one by 'right-click' and open new console a new console is opening but the console is not loading correctly. (no python header etc) and the little blue/yellow symbol is turning gray. When I try to open an ipython console basically nothing happens.

Under Preferences -> Console -> Advanced Settings I checked the "Use the following Python interpreter" to /usr/bin/python (this is also the output from 'which python' in the terminal)

I have only an internal console window opened. But there I have the problem that I can't import all packages correctly. 'import cv2' works for example but 'import caffe' doesn't.
When I start python from the terminal both work perfectly and I can run any opencv/caffe script without problems.

So I think I have something misslinked within spyder but I could not figure out what.

### Update: Installation from Terminal
I also tried the following: Removing via Software-Center -> then sudo apt-get install spyder
When I then start spyder from terminal, I have basically the same problem. But in the terminal I get the following Warning printed:
`frederik@frederik-desktop:~$ spyder
/usr/local/lib/python2.7/dist-packages/IPython/qt.py:13: ShimWarning: The `IPython.qt` package has been deprecated. You should import from qtconsole instead.
  "You should import from qtconsole instead.", ShimWarning)
/usr/local/lib/python2.7/dist-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
  "You should import from traitlets.config instead.", ShimWarning)
`
Does this help?

## Versions and main components
I have spyder 2.2.5 and using python 2.7.6, all optional dependencies are installed (see below).
pyqt version is 4.10.4, sip 4.15.5 and qt 4.8.6

IPython >=0.13  :  4.1.2 (OK)
matplotlib >=1.0:  1.5.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pylint >=0.25   :  1.1.0 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  0.7.6.1 (OK)

Any help would be wonderful! As caffe is running perfectly from terminal's python I think getting to start the ipython/python console in spyder will fix the import error of caffe in spyder

**Comment by ccordoba12** [comment]
Sorry, we don't support Spyder 2.2.5 anymore.
