### ISSUE TITLE
matplotlib may create 2 windows when run through spyder

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#3030]
The following script (doublewindow.py) creates 2 windows when launched from the run icon in a ipython console, ie runfile(...). When it is launched from the same console using "%run -i doublewindow.py" it runs fine, ie only one window is open as expected. I could track down the issue from the call to plt.ishold(). If you comment this single line, both runs create a single window. PS: use "%matplotlib wx" first.

```
import matplotlib.pyplot as plt
         
from matplotlib.backends.backend_wx import FigureCanvasWx as FigureCanvas
from matplotlib.figure import Figure

import wx
  
class MyPanel(wx.Panel):
  def __init__(self, parent):
    wx.Panel.__init__(self, parent)
    self.figure = Figure()
    self.canvas = FigureCanvas(self, -1, self.figure)
    self.axes = self.figure.add_subplot(111)
        
if __name__ == "__main__":
  if not 'app' in locals() or app==None: app= wx.App()
  frm = wx.Frame(None,-1,'Test')
  MyPanel(frm)
  frm.Show()
  plt.ishold()  ### <-------------------- issue is here
  #app.MainLoop()
```
It occurs with spyder 2.3.8 and 1 week ago dev version.
All my libraries are the last ones (matplotlib,wx,ipython...). I use python 2.7 (win32) on windows 7.
Thanks.

**Comment by ccordoba12** [comment]
I can reproduce this bug, but it's a problem that we can solve ourselves. This is a bug in the `qtconsole` package that we just embed in Spyder.

So please report this problem here:

https://github.com/jupyter/qtconsole

**Comment by sylvain-bougnoux** [comment]
Actually I **cannot** reproduce the bug pasting this code on a "jupyter qtconsole" (and uncommenting "#app.MainLoop()"). Only one window pops-up. 

How do you know it is from qtconsole, how can I justify it for this group?

Thanks. My qtconsole is 4.2.0.

**Comment by ccordoba12** [comment]
I reproduced it in qtconsole on Linux :-) But maybe this is not a bug on Windows, I don't know.

**Comment by sylvain-bougnoux** [comment]
Would you tell me how to generate the bug on a qt-console, the qt-console guys asked for it :-)
What does `runfile(...)` is translated to? Because within spyder `%run -i doublewindow.py`works.
