### ISSUE TITLE
Create a Remote Procedure Call helper

### ISSUE THREAD

**Issue by blink1073** [spyder-ide/spyder#3033]
This will be used for pylint, pep8, and introspection.
- Create a QProcess with the executable of the current project, adding spyder and the appropriate dependencies (e.g. jedi) to the path. 
- Use ZMQ to pass pickled objects to a remote procedure call.
- The remote end imports the desired modules(s) and performs the remote procedure calls, returning the result over the ZMQ socket pair.

```
RemoteClient(executable, dependencies, imports)
    onReply(request_number, result)
    send(func_name, *args, **kwargs)  # returns a request number
RemoteServer(imports, server_port, client_port)
```

**Comment by ccordoba12** [comment]
Two things about this:

1. Pyflakes needs to be called like this too :-)
2. Fortunately all these packages work on both Python 2 and 3 at the same time (so importing from a Python 2 installation in a Python 3 remote process won't be a problem). The only missing piece was `rope` but its next version will be Python 3 compatible too.

**Comment by ccordoba12** [comment]
@goanpeca, this is what you wanted :-)

**Comment by goanpeca** [comment]
:-)
