### ISSUE TITLE
WinPython 'spyder' launcher will fail with spyder 3.0.0beta3

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3038]
recent WinPython "spyder" launcher icon will fail, as they were launching 
````
python.exe -m spyderlib.start_app %*
````

Keeping a working `spyderlib.start_app` until spyder 3.1 would be kind, to smooth the transition for existing installed base of WinPython

Next Winpython will of course point to 'spyder.exe' executable.

**Comment by ccordoba12** [comment]
I think you could patch Spyder in WinPython, and add that entry point instead of leaving that work to us :-)

I'm sorry but you are packaging and distributing Spyder betas and dev versions, and until a final release is done, you know that there's no guarantee of an stable API.

Worst of all is that there are even more disrupting changes to come in beta4 (like renaming `spyderlib` to `spyder`)

**Comment by stonebig** [comment]
and how is now launch spyder-reset ? I see the icon but no executable

**Comment by ccordoba12** [comment]
There's a menu entry in

    Tools > Reset Spyder to factory defaults

**Comment by stonebig** [comment]
on some old install base, spyder gui was failing, so the command line option of --reset was nice.

**Comment by ccordoba12** [comment]
It's still there, what we don't provide now is Windows Startup menu entry.

**Comment by stonebig** [comment]
ok, I will patch accordingly, just in case. thanks. any guess date for final beta 3 ? you seem very close

**Comment by stonebig** [comment]
ok, now WinPython will be insensitive to change from `spyderlib` to `spyder`.

I didn't understood the full change that was coming. no problem

**Comment by ccordoba12** [comment]
Again, thanks a lot for understanding!

> any guess date for final beta 3 ? you seem very close

Most probably for next weekend :-) I still need to release new Qt4 packages in Anaconda that could be installed side by side with Qt5, to help Mac people with bug #2724.
