### ISSUE TITLE
Spyder crash with "too many files open" message

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3041]
## Description

**What steps will reproduce the problem?**

1. Open spyder
2. Live your life
3. Return to spyder: it's gone

**What is the expected output? What do you see instead?**
I've never seen the crash, because each time I was on another desktop when it happened. I had this problem around 4 times in less than a week. This problem appeared last week, considering the rate at which I upgrade spyder on this computer the problem is no more than say 3 weeks old.

Here is the message I get in the console:
```
We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nError loading services.\n"
KSambaShare: Could not find smb.conf!
We got some errors while running 'net usershare info'
"Can't load /etc/samba/smb.conf - run testparm to debug it\n"
QProcessPrivate::createPipe: Cannot create pipe 0x3d42978: Too many open files
Unhandled Python exception
fish: 'spyder3' terminated by signal SIGABRT (Abandon)
```
I don't know why it complains about smb, and I don't know if it's related. All the files I open are on the machine itself.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0dev 
* Python Version: 3.5.1
* Qt Versions: 5.5.1, PyQt5 5.5.1 on Linux

## Dependencies
```
pyflakes >=0.6.0:  1.0.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
numpy >=1.7     :  1.10.4 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
psutil >=0.3    :  4.0.0 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Could you bisect it?

**Comment by ccordoba12** [comment]
@blink1073, I think this could be caused by your async PR. I say it because:

1. I started Spyder with `SPYDER_DEBUG=3` and I now I see a constant stream of messages while Spyder is doing nothing:

        finished jedi True
        finished fallback True
        Initialized fallback
        Initialized jedi
        finished rope True
        Initialized rope
        finished rope True
        finished jedi True
        finished fallback True
        finished fallback False

   and the stream goes on and on.

2. I followed the PID's related to `plugin_server`'s and we are destroying and creating servers every once in a while, but I don't think that's necessary.

**Comment by blink1073** [comment]
The zmq version I'm working on will address this.  I've got the client/server parts done, and just need to integrate it.  The first PR will just replace the introspection parts, which should be ready by this weekend.

**Comment by ccordoba12** [comment]
Ok, thanks for addressing this so quickly! As you said, please focus for now only on introspection, so we can release beta3 next weekend too :-)

Then on beta4 you can move pyflakes, pep8, etc to this mechanism.

**Comment by Nodd** [comment]
For information the error message varies:

```
We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nError loading services.\n"
KSambaShare: Could not find smb.conf!
We got some errors while running 'net usershare info'
"Can't load /etc/samba/smb.conf - run testparm to debug it\n"

(process:23390): GLib-ERROR **: Creating pipes for GWakeup: Trop de fichiers ouverts

fish: 'spyder3' terminated by signal SIGTRAP (Déroutement de suivi/point d'arrêt)
```

```
We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nError loading services.\n"
KSambaShare: Could not find smb.conf!
We got some errors while running 'net usershare info'
"Can't load /etc/samba/smb.conf - run testparm to debug it\n"
QProcessPrivate::createPipe: Cannot create pipe 0x3d42978: Too many open files
Unhandled Python exception
fish: 'spyder3' terminated by signal SIGABRT (Abandon)
```

```
We got some errors while running testparm "Load smb config files from /etc/samba/smb.conf\nError loading services.\n"
KSambaShare: Could not find smb.conf!
We got some errors while running 'net usershare info'
"Can't load /etc/samba/smb.conf - run testparm to debug it\n"
No node found for item that was just removed: QUrl("file:///data/libs.git/JML/python/Avenant_RAMHY/analyse_seq_ui.ui")
No node found for item that was just removed: QUrl("file:///data/libs.git/JML/python/Avenant_RAMHY/build.bat")
Unhandled Python exception
fish: 'spyder3' terminated by signal SIGABRT (Abandon)
```

```
(process:8370): GLib-ERROR **: Creating pipes for GWakeup: Trop de fichiers ouverts

fish: 'spyder3' terminated by signal SIGTRAP (Déroutement de suivi/point d'arrêt)
```
