### ISSUE TITLE
Crash when running Spyder on Windows 10

### ISSUE THREAD

**Issue by Mark531** [spyder-ide/spyder#3042]
I was using Spyder on Windows 7 then I upgraded to Windows 10. The shortcuts to run Spyder have disappeared so I ran this command from Anaconda's Scripts directory:

python.exe spyder-script.py

But I get a crash when the splash screen appears. Maybe it's not the right command?

## Versions and main components

* Spyder Version:3.5
* Python Version:3.5
* Operating system:Windows 10

**Comment by ccordoba12** [comment]
You should be able to run

    spyder

from a terminal. Is that not working for you?

**Comment by Mark531** [comment]
No, it is not working for me.

**Comment by ccordoba12** [comment]
Then your installation is broken. Please try to uninstall and reinstall again.

**Comment by Mark531** [comment]
But all I did was upgrade the OS. If you're using Windows, could you tell me the command that is associated with the Spyder shortcut?

**Comment by ccordoba12** [comment]
The menu shortcut calls the `spyder` command.

I think the best you can do is a full re-installation. I know it's painful but you'd avoid fighting with problems like this for several hours.

**Comment by Mark531** [comment]
You were right, I reinstalled Anaconda and the command spyder did run Spyder. Though, after creating another environment and activating it, the "spyder" command crashes again, It's enough to deactivate the environment to be able to run Spyder again. How do you manage Conda environments with Spyder?

**Comment by ccordoba12** [comment]
Spyder shouldn't have a problem with conda envs. Could post the crashing message?

**Comment by Mark531** [comment]
The only message I get is "python.exe has stopped working" during the splash screen. Maybe the errors are saved into a log file?

**Comment by Mark531** [comment]
Is it possible to report a bug?

**Comment by ccordoba12** [comment]
This is a bug report, sorry for not answering before :-)

To see the error Spyder is generating, please run it like this

    spyder --show-console

**Comment by Mark531** [comment]
Unluckily, Spyder crashes before opening its console, so I can't see the message. Well, could you please give me the procedure to report a bug? I'll detail the steps required to reproduce the crash.

**Comment by ccordoba12** [comment]
The `--show-console` prevents Spyder from automatically closing the terminal from which it was started (and it only works on Windows). It doesn't have to do with Spyder Python or IPython consoles :-)

So, if some error is printed on the terminal Spyder was started (with the command `spyder --show-console`) please post it here.

**Comment by Mark531** [comment]
No, no error is shown on the Windows terminal either.

**Comment by ccordoba12** [comment]
Are there any error messages reported by Windows when it displays the message about `python.exe` crashing?

**Comment by Mark531** [comment]
No, as I said, the only message is "python.exe has stopped working". Maybe it would be best for you to reproduce the crash. The procedure is simple: create a 3.4 Python environment, activate it, then run Spyder.

**Comment by ccordoba12** [comment]
Does this problem also happen with Python 3.5? I think there are some 
problems with 3.4 that are not present in 3.5.

**Comment by Mark531** [comment]
No, when I activate the Python 3.5 environment, Spyder runs fine. But the 3.5 version is the main version, so maybe the issue is linked with the additional Python environments (and not the version of Python itself).

**Comment by ccordoba12** [comment]
No, there were some problems with Qt (the graphical library used by Spyder) and Python 3.4. But I think they were solved recently.

In your 3.4 environment, please run

    conda update qt pyqt

and try again :-)

**Comment by Mark531** [comment]
I tried your advice and it worked fine! Spyder opened normally in my Python 3.4 environment.

Thanks for your help. You can consider this point closed.

**Comment by ccordoba12** [comment]
I'm really glad!! :+1:

**Comment by markm00001** [comment]
Hi, I have been having similar issues with launching spyder in a py2.7 venv. Finally solved it using multiple threads of the posted issue. It seems that you need to tweak the update above so that pyqt version to use is 4.10.4 (use install separately to change this after the generic update suggested above)

**Comment by blackshirt** [comment]
I have this similar problem too, i was using Win 7 Ultimate 32bit OS..

C:\Users\****>conda update qt pyqt
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at E:\Progfiles\Miniconda3:
#


C:\Users\*****>conda info
Current conda install:

               platform : win-32
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : E:\Progfiles\Miniconda3  (writable)
    default environment : E:\Progfiles\Miniconda3
       envs directories : E:\Progfiles\Miniconda3\envs
          package cache : E:\Progfiles\Miniconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Windows/7 Wi
ndows/6.1.7600



when i run spyder, through cmd or start menu, i get notification window if python has stopped working.
There are not any debug information 


Any help apreciate

**Comment by werner-rammer** [comment]
I ran into the same issue of spyder crashing at startup. I tried to upgrade or uninstall/install of spyder, but to no avail. After stumbling about #2858, I tried to upgrade my PyQt; I use pip, and according to http://pyqt.sourceforge.net/Docs/PyQt5/installation.html

`pip install --upgrade pyqt5`

did the trick for me.

**Comment by gnaaromat** [comment]
Same issue here with anaconda python 3.5.2
spyder simply crashed without any output
tried upgrading my pyqt5 - seems pip just removed and reinstalled the same version again (5.8.1) and afterwards spyder exits with
```
 ImportError: No module named 'PySide'
Traceback (most recent call last):
  File "C:\Users\Michael\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\Michael\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\Michael\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Users\Michael\Anaconda3\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
  File "C:\Users\Michael\Anaconda3\lib\site-packages\qtpy\__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

bummer. PySide cannot be installed since it depends on python 2.7. Lets try reinstalling spyder again
```
conda uninstall spyder
conda install spyder
```

bummer. Still the same.

```
conda update --prefix C:\Users\gnaaromat\Anaconda3 anaconda
.........
The following packages will be DOWNGRADED due to dependency conflicts:

    scipy:    0.19.0-np111py35_0 --> 0.18.1-np111py35_1
    spyder:   3.1.3-py35_0       --> 3.1.2-py35_0
```

Nothing. Instead of reinstalling anaconda a third time now I chose to try a different pyqt5 version. 5.8.1 obviously didnt work.

All versions below 5.8 cause spyder to simply crash while 5.8 and up causes the "No Qt bindings could be found" to appear.

The windows logs are fairly inconclusive.. Anyone any ideas?

**Comment by ccordoba12** [comment]
If you're mixing pip and conda packages, you most probably broke your installation. Please uninstall and reinstall Anaconda again.

**Comment by jibraniqbal666** [comment]
![capture](https://user-images.githubusercontent.com/30576574/31587189-92d7d56a-b1f6-11e7-9393-3187303f65a3.PNG)
Getting this error on newly installed spyder 3.2.3.  i am using miniconda.

**Comment by thesilentpsycho** [comment]
For the message "python.exe has stopped working" while starting Spider:-
Launch your anaconda-navigator. Update Spider
![image](https://user-images.githubusercontent.com/13063226/32625421-2762b08c-c5b2-11e7-9d1f-c98452442dab.png)

**Comment by hinafirdaus** [comment]
I am using spyder through winpython when I tried to save the current work in .py the error message displayed "python has stopped working". This same message showed up when I was using Anaconda and whenever I tried to save my work or use python more than 1hr suddenly it will show "python has stopped working". I need to build my project and I am dealing with this problem from past 2 months. Please give me a solution or an alternative to easily use the spyder for machine learning in disease datasets pleaseeeee....

**Comment by jibraniqbal666** [comment]
try VSCode. you can embed your anaconda python environment into it. I am also dealing with this issue in spyder.

**Comment by ccordoba12** [comment]
@hinafirdaus, please open a new issue about your problem so we can help you to solve it.

**Comment by Marshallmaxiao** [comment]
I just had the same issue, with Spyder 3.2.8, Anaconda 3.5, Python 3.6 and Windows 10. I fixed it by running anaconda prompt as admin and run
`conda upgrade --all`

**Comment by swaroopbayya** [comment]
It happened for me but it is fixed now. Just reset the spyder settings by going to anaconda navigator file location. Hope it helps.

**Comment by dorcas-pixel** [comment]
> It happened for me but it is fixed now. Just reset the spyder settings by going to anaconda navigator file location. Hope it helps.

how do you do it
