### ISSUE TITLE
How to add a recursive list of paths in the PYTHONPATH manager

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#3048]
## Description

**What steps will reproduce the problem?**

I want to know if Spyder provides the ability to add a recursive list of folders/directories in the PYTHONPATH manager.  
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0   :  None (NOK)
pep8 >=0.6         :  None (NOK)
pygments >=1.6     :  1.6 (OK)
IPython >=1.0      :  1.2.1 (OK)
zmq >=2.1.11       :  14.0.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.2.2 (OK)
psutil >=0.3       :  2.2.1 (OK)
rope >=0.9.2       :  None (NOK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pylint >=0.25      :  1.4.3 (OK)

```

**Comment by ccordoba12** [comment]
> I want to know if Spyder provides the ability to add a recursive list of folders/directories in the PYTHONPATH manager.

No, it doesn't, and there is no need for that. When you add your topmost directory to PYTHOPATH, you can import what's beneath it by using the following syntax:

```python
from topdir.subdir.subsubdir import foo
```

For this to happen, the only thing you need to do is adding empty files called `__init__.py` (notice the two underscores to both sides) to `topdir`, subdir and `subsubdir`. That's all :-)

**Comment by Nodd** [comment]
In python3 you don't need empty `__init.py__` anymore. I don't remember which version exactly.
