### ISSUE TITLE
Environment variable required to start pyqt5 spyder (QT_QPA_PLATFORM_PLUGIN_PATH)

### ISSUE THREAD

**Issue by zeehio** [spyder-ide/spyder#3050]
## Description of your problem

**What steps will reproduce the problem?**

1. `conda create -n myenvironment -c https://conda.anaconda.org/spyder-ide spyder pyqt5`
2. `source activate myenvironment`
3. `QT_API=pyqt5  spyder`

**What is the expected output? What do you see instead?**
I expect spyder to start using pyqt5. Instead I see:

    This application failed to start because it could not find or load the Qt platform plugin "xcb".

    Reinstalling the application may fix this problem.
    Aborted

I can workaround the issue starting spyder like this:

`QT_API=pyqt5 QT_QPA_PLATFORM_PLUGIN_PATH=${CONDA_ENV_PATH}/lib/qt5/plugins/platforms spyder`

Is there any way to fix this to get rid of `QT_QPA_PLATFORM_PLUGIN_PATH`? I was thinking of adding this somewhere right before pyqt5 is imported, but it seems a conda-specific solution...:

```python
if ("QT_QPA_PLATFORM_PLUGIN_PATH" not in os.environ.keys() and
        "CONDA_ENV_PATH" in os.environ.keys()):
    os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = os.path.join(
        os.environ["CONDA_ENV_PATH"], "lib", "qt5", "plugins", "platforms")
```

## Versions and main components

* Spyder Version: 3.0.0b2
* Python Version: 3.5.1
* Operating system: Linux Mint 17.3 Updated

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=3.0      :  4.0.2 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
numpy >=1.7        :  1.10.4 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.3.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=13.0.0       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
@zeehio, thanks for reporting. This is really a problem with the Qt4 packages present in Anaconda. We're working to make Qt4 and Qt5 installable side by side, see conda/conda-recipes#616.

New Qt4 packages will be available in a couple of weeks that will work without problems with the Qt5 packages provided in the `spyder` Anaconda channel.

**Comment by ccordoba12** [comment]
In the mean you can run

    conda remove qt pyqt

to run Spyder with PyQt5

**Comment by iurisegtovich** [comment]
I had an issue that seems to match what happened here
But in my case the solution was to "sudo rm -rf user/anaconda3" and reinstall it with "bash anaconda....sh", because i had previously installed it using sudo ("sudo bash anaconda....sh")
