### ISSUE TITLE
I can not find the file "myapp.log" at current directory

### ISSUE THREAD

**Issue by A-Pai** [spyder-ide/spyder#3051]
import logging
logging.basicConfig(level=logging.DEBUG,
                format='%(asctime)s %(filename)s[line:%(lineno)d] %(levelname)s %(message)s',
                datefmt='%a, %d %b %Y %H:%M:%S',
                filename='myapp.log',
                filemode='w')
logging.debug('This is debug message')
logging.info('This is info message')
logging.warning('This is warning message')

**Comment by Nodd** [comment]
Hello, thanks for the report. Sadly you're not the only one with this problem, and it has already been reported in #2572.
I'll close this one as a duplicate.
