### ISSUE TITLE
Spyder 3.0.0b2 revives old copy/paste bug #2710

### ISSUE THREAD

**Issue by chrisjcameron** [spyder-ide/spyder#3052]
An issue described in #2710 has cropped up again in Spyder 3.0.0b2

## Description

**What steps will reproduce the problem?**

What steps will reproduce the problem?

Copy text from Spyder iPython console using keyboard shortcut or context menu.
Paste into editor or another program.
Note the last character is missing.

What is the expected output? What do you see instead?

I would expect all the text to be copied.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0b2 
* Python Version: 2.7.11
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Darwin

## Dependencies
```
pyflakes >=0.5.0   :  0.8.1 (OK)
pep8 >=0.6         :  1.5.6 (OK)
pygments >=1.6     :  1.6 (OK)
IPython >=3.0      :  4.1.2 (OK)
zmq >=13.0.0       :  14.3.0 (OK)
qtconsole >=4.0    :  4.0.1 (OK)
pandas >=0.13.1    :  0.14.0 (OK)
numpy >=1.7        :  1.8.1 (OK)
sphinx >=0.6.6     :  1.2.2 (OK)
psutil >=0.3       :  2.1.1 (OK)
rope >=0.9.4       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.5 (OK)
pylint >=0.25      :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
This is not a Spyder bug, but a bug in qtconsole (the package that we integrate in Spyder to provide the IPython console).

Please update qtconsole to version **4.2** (you're currently using **4.0.1**). That will solve the problem :-)
