### ISSUE TITLE
Ctrl+I doesn't seem to work on the editor on current tree on Windows 

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3053]
## Description of your problem

**What steps will reproduce the problem?**

1. open spyder
2. type "print" in the editor then Ctrl+I
3. the help window becomes blank
4. type "print" in the qtconsole of spyder then Ctrl+I
5. the help window shows the description of print function

**is it normal nothing shows up at step 3?**

## Versions and main components

* Spyder Version: tree of  2015-03-11 19h00 GMT
* Python Version: 3.4
* Operating system: Windows 7 64bit , Python 3.4.1

## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.18.0rc2 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pyflakes >=0.6.0:  1.1.0 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.2.0 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.6 (OK)
sympy >=0.7.3   :  1.0 (OK)

**Comment by stonebig** [comment]
it was ok with beta2 in previous WinPython ... I'm a little lost on the root cause of this

**Comment by stonebig** [comment]
hum, either I just mistaken, either it works again with latest comit... strange

**Comment by ccordoba12** [comment]
Great! We changed the internals of our completion machinery (in pull request #3049), so that could be the reason why this is working again! :-)

**Comment by stonebig** [comment]
On the other end, starting the new spyder:
- failed today (it was alongside the old, could there be a relationship ?)
- doesn't restart (i see a pythonw process pending) .
- after killing pythonw, it's okay again, except there is nothing in the qtconsole..

Any suggestion to get the qtconsole back ?
Is there a conflict with jupyter-qtconsole ?

**Comment by stonebig** [comment]
It seems a pythonw process continues to run when I stop (red cross on top right) a Spyder_launched_with_async_server, on Windows

**Comment by RobertPeetsalu** [comment]
This bug is still in production though it appears to be closed. Should I make a new issue?

I'm using Spyder 3.1.2 with Python 3.6.0 launched through latest Anaconda and I'm reproducing the exact same steps that are in the bug description.

**Comment by CoderCoderCoder** [comment]
Same problem with 3.1.4 on MacOS 10.12.5. Spyder installed through Anaconda. Initially it worked, but then suddenly I have exactly the same problems:
- "Editor" help window remains blank
- the input area is disabled
- "Automatic import" checkbox is greyed out

For "Console" everything works fine.
Code autocompletion also doesn't work anymore (e.g. typing a "." after a class doesn't show any methods. 

Please help, thanks.

**Comment by CoderCoderCoder** [comment]
I have the same problem. Initially everything worked without any problems, then suddenly the "Editor" help window just remained blank. I even reinstalled Spyder (through Anaconda) - same probs.

Spyder version 3.1.4.

In the "Console" help window everything works fine. The editor code auto-completion also stopped working.

Please help.

**Comment by CoderCoderCoder** [comment]
OK, I solved this problem by myself. Uninstalled Jedi 0.10.2, installed Jedi 0.9.0.
To bad that this is only visible in Spyder 3.1.3 (I have installed the previous version by testing what happens then), it thrown the warning about Jedi version mismatch. In Spyder 3.1.4 there is no such warning.

**Comment by adithyavarambally** [comment]
did you use both python wheel and source of jedi
@CoderCoderCoder

**Comment by adithyavarambally** [comment]
@CoderCoderCoder it didnt work for me tho

**Comment by endolith** [comment]
Problem has returned in 3.3.1

**Comment by arnav1307** [comment]
Same even i am facing the same problem
