### ISSUE TITLE
Spyder  leaves one pythonw process running, if stopped too early

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3063]
## Description of your problem

**What steps will reproduce the problem?**

1. On Windows 7 / Python3, Start Spyder after #3049
2. Stop it
3. on the process console, you see one pythonw process still running

**What is the expected output? What do you see instead?**

no more pythonw  process, but in fact there is still one running

**Please provide any additional information below**

I can get crashes or empty spyder_qtconsole, when I start again spyder, or not.
If I do another Start/Stop of Spyder, a second pythonw shadow process remains running next to the previous one.

## Versions and main components

* Spyder Version: yesterday after #3049
* Python Version: 3.4.1 64bit 
* Operating system: Windows 7 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
@blink1073, I can confirm this problem. Could you take a look at it?

**Comment by blink1073** [comment]
Yep, but maybe not until this weekend.

**Comment by ccordoba12** [comment]
No problem ;-)

**Comment by blink1073** [comment]
I'm not sure what could be happening here.  When I start spyder on Win 7, six processes are created.  Killing the main process leaves four processes open, three of which close after 10 seconds (as expected).  I also added a debug print to file to verify that they are closing.  I don't know what the phantom process could be.

**Comment by stonebig** [comment]
hum, I may retry on today trunk. what PyQt do you use @blink1073 ?

**Comment by blink1073** [comment]
PyQt 4.11.4, Anaconda Python 2.7.11, Windows 7.

**Comment by stonebig** [comment]
I only live in Python3.4+ ... could it have an influence on this bug ?

**Comment by blink1073** [comment]
I don't think so, since I see the same problem as you on Python 2.7.

**Comment by stonebig** [comment]
ah, sorry. I thought you didn't have the phantom process.

**Comment by stonebig** [comment]
as your patched added an async process, I would have supposed it was this one

**Comment by blink1073** [comment]
I tried "return"ing before I even create any `QProcess`es, and the phantom persists.

**Comment by stonebig** [comment]
and the expected number of process when spyder is running is right ? in beta 2 i have 2 python.exe, 1 pythonw.exe and 1 spyder.exe. that is 4 , not 5.

**Comment by blink1073** [comment]
I'm not sure about the expected behavior on beta2, I use OSX normally.  AFAIK beta3 should be adding three extra python.exe processes for the three introspection plugins.

**Comment by blink1073** [comment]
But I've demonstrated that those three are behaving as intended.

**Comment by stonebig** [comment]
do you still see the phantom if other instropection plugins are disabled ?

**Comment by stonebig** [comment]
the python"w" process that is phantom is supposing to be of a gui, isn't it ?  so not of any plugin ?

**Comment by stonebig** [comment]
also, I wrote that I tested just after Async integration, but the bug may be something else, committed before.

**Comment by stonebig** [comment]
hum, it looks to me the problem may have been  there at least at the commit before 'Async Server' integration. and code completion was not working in the editor already, giving in the error console a message:
````
>>> Traceback (most recent call last):
  File "D:\WinPython\basedir34\build\winpython-64bit-3.4.x.2\python-3.4.4.amd64\lib\site-packages\spyderlib\utils\introspection\manager.py", line 119, in handle_response
    if (response.get('request_id', None) != id(self.info)):
AttributeError: 'int' object has no attribute 'get'
````

**Comment by stonebig** [comment]
there is also this message that appears each first time I try the async version:

![maybe_async_effect](https://cloud.githubusercontent.com/assets/4312421/14059212/27a36884-f33b-11e5-9299-5158a79cda12.GIF)

**Comment by stonebig** [comment]
now I don't have the pythonww process... I did unchecked then recheck the "console/instropection/activate the monitor" 
I notice I have two lines of "editor/instrospection/real time analysis" 
![maybe_not_async_effect](https://cloud.githubusercontent.com/assets/4312421/14059726/47110616-f34c-11e5-9be9-1b0897036bbd.GIF)

maybe having pep8/pylint/rope/jedi together is a bad configuration ?

**Comment by stonebig** [comment]
ok, in a reproducible way:
- the process that remains is a process that takes initialy 24 seconds to start,
- spyder is long stabilized and showing qt console.

If I stop spyder before 24 seconds, this slow-starting process is never killed.

If I kindly wait 24+ seconds before killing spyder, all processes are stopping.

**Comment by blink1073** [comment]
I tried it with the v3.0beta2 git tag and still saw the phantom process, still digging.

**Comment by blink1073** [comment]
Same with v3.0beta1

**Comment by blink1073** [comment]
Looks like it goes as far back as 2.3.6, before that and I can't get spyder to load at all.

**Comment by blink1073** [comment]
I believe this is the `ExternalPythonShellWidget` causing this behavior, since it is started using a `QProcess`, may be started as `pythonw.exe`, and doesn't have a heartbeat timeout the way the introspection widgets have.

**Comment by stonebig** [comment]
I'm not annoyed anymore by these issue, not sure of the reason (maybe Windows 10 is hidding me details)... I'm closing it to spare developper cycles for more important issues
