### ISSUE TITLE
Allow users to configure PEP8 options

### ISSUE THREAD

**Issue by ghost** [spyder-ide/spyder#3064]
## Description of your problem

I would like to have a GUI option in the  Tools->Preferences->Editor menu in Spyder so as to increase maximum line length in Spyder Editor and enforce remaining PEP8 standards
**What steps will reproduce the problem?**
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Pls. also refer to comment by Carlos in the below link: 
http://stackoverflow.com/questions/26426689/python-how-to-tell-spyders-style-analysis-pep8-to-read-from-a-setup-cfg-or-inc
## Versions and main components
- Spyder Version: 2.3.8
- Python Version:2.7
- Operating system:Windows
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by gamesbook** [comment]
Is there a workaround for those of us still on 2.3.8?

**Comment by gamesbook** [comment]
@ccordoba12  Thanks.  I think the answer is to upgrade.  Can you confirm that if I remove my current version and use:
```
sudo pip install -U spyder
```
that all my settings and configuration will remain intact?

**Comment by ccordoba12** [comment]
Sure, unless you're updating from a very old version (i.e. Spyder 2.3.x).

**Comment by gamesbook** [comment]
@ccordoba12   2.3.8 is specifically the version that I referenced in my post above.  Is there an upgrade path for that?

**Comment by ccordoba12** [comment]
You can copy `~/.spyder2{-py3}` to `~/.config/spyder{-py3}`, and then start our latest version, but I can assure that things will work without problems.

**Comment by jennirinker** [comment]
This doesn't seem to be resolved yet (I'm on version 3.3.3), but in case people need a workaround, the method posted [here in the comments](https://stackoverflow.com/questions/26426689/how-to-tell-spyders-style-analysis-pep8-to-read-from-a-setup-cfg-or-increase-ma/26435067#26435067) worked for me:  
1. Set the line length in the editor preferences to your new value (doesn't change pep8, just puts line in right place)  
2. Find your pycodestyle.py file in your environment's directory (mine was in Lib/site-packages) and change `MAX_LINE_LENGTH` to the right value.  
3. If necessary, close and reopen Spyder.

**Comment by ccordoba12** [comment]
It'll be fixed in Spyder 4.

**Comment by gamesbook** [comment]
@jennirinker  I cannot understand your abbreviated code path "Lib/site-packages" - can you post an example of a complete path?

**Comment by jennirinker** [comment]
Sorry, my bad. Here is the path for me (miniconda installed for local user, spyder installed in a separate environment called "spyder"):  
`C:\Users\rink\AppData\Local\Continuum\miniconda3\envs\spyder\Lib\site-packages\pycodestyle.py`

If you have spyder installed in your default environment, I would guess the pycodestyle file would be here:  
`C:\Users\rink\AppData\Local\Continuum\miniconda3\Lib\site-packages\pycodestyle.py`

**Comment by gamesbook** [comment]
@jennirinker  Thanks; unfortunately that does not help me as my Spyder is installed via a Linux package manager.

**Comment by jennirinker** [comment]
@gamesbook Does the Anaconda docs not help with finding your path location? For example, [this page](https://docs.anaconda.com/anaconda/user-guide/tasks/integration/python-path/)?

**Comment by gamesbook** [comment]
@jennirinker I am not using anaconda.

**Comment by jennirinker** [comment]
@gamesbook Ah, then I probably can't help you further, unfortunately. Don't have experience with non-Anaconda spyder. If you've followed the instructions on that page and tried `which python` in your terminal (or maybe `which spyder`) and that doesn't work, then I'm out of ideas. :(

**Comment by bcolsen** [comment]
@gamesbook on linux:

`locate pycodestyle.py`

will find the path
