### ISSUE TITLE
location of sphinxify.py

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#3068]
In WinPython **2.7.10.3**:
  sphinxify.py is in \spyderlib\utils\inspector
In WinPython **3.5.1.2**:
  sphinxify.py is in \spyderlib\utils\help

Why?
In both cases spyderlib.__version__ = '3.0.0dev'

If I want sphinxify.py from spyderlib, how should I better import it given its location may vary?

Thanks!

**Comment by ccordoba12** [comment]
WinPython is packaging Spyder 3.0 betas (not the final release). Somewhere along the way (after beta2 I think) we decided to rename the *Object Inspector* pane to *Help*, and so we also changed `utils/inspector` to `utils/help`.
