### ISSUE TITLE
Problem using arrow keys in editor?

### ISSUE THREAD

**Issue by bluephoton** [spyder-ide/spyder#3070]
This is fatal! As I use spyder editor for sometime, some how right and left arrow keys get reversed. when I click right arrow it takes me left and when i click left it take me right. Sometimes I can't even move at all within line only jump from line to line. I notices that when I close the document and open it it will start to work as expected again.

**Comment by ccordoba12** [comment]
Why did you dismiss the issue template? I'm going to close this issue and ask you to open a new one with the information present in the template correctly supplied.

**Comment by bluephoton** [comment]
Sorry, not familiar with it, how do i get the template?

**Comment by bluephoton** [comment]
I see, I just clicked from help->report an issue and this doesn't provide a template. will create new one...

**Comment by ccordoba12** [comment]
Please open the issue directly here on Github. Then you'll see the template :-)

**Comment by bluephoton** [comment]
yup, working on it :)
