### ISSUE TITLE
Memory usage not appearing

### ISSUE THREAD

**Issue by rchurt** [spyder-ide/spyder#3074]
## Description of your problem
Hello,
I've recently noticed that in the bottom-right corner of the Spyder window, there's no value for the memory usage.
<img width="381" alt="screen shot 2016-03-21 at 11 56 26 am" src="https://cloud.githubusercontent.com/assets/14302923/13930945/52e72e76-ef5e-11e5-8420-39b3cbdb5bc8.png">

When I look in Spyder at the dependencies (see below), it says that ```psutil``` is not installed, but I know that it is:
<img width="416" alt="screen shot 2016-03-21 at 12 11 53 pm copy" src="https://cloud.githubusercontent.com/assets/14302923/13931072/e12e7c02-ef5e-11e5-8a9f-e37c87d23479.png">

As a comparison, ```numpy```, which _does_ show up in the spyder dependencies as being installed, is installed in exactly the same directory as ```psutil```:

<img width="416" alt="screen shot 2016-03-21 at 12 11 53 pm" src="https://cloud.githubusercontent.com/assets/14302923/13931121/0dfa957c-ef5f-11e5-96f4-fc48d08f9875.png">

Any idea why my other packages are being recognized, but ```psutil``` isn't?

Thanks

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 3.5.1
* Operating system: OSX 10.11.3

## Dependencies
IPython >=3.0   :  4.1.2 (OK)
matplotlib >=1.0:  1.5.1 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.18.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  None (NOK)
pyflakes >=0.6.0:  1.1.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  1.0 (OK)
zmq >=13.0.0    :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll see what we can do to fix this problem.

**Comment by ccordoba12** [comment]
Maybe you installed them in a different environment.

I'm sorry but I don't think this is a Spyder problem but more an installation one. So I'm closing this issue.
