### ISSUE TITLE
IPython console not starting/showing

### ISSUE THREAD

**Issue by manney** [spyder-ide/spyder#3075]
Hi all,

I'm experiencing problems with Spyder and the IPython console since I installed in my Windows 10 environment.  I've just made sure that Syder and all of the supporting libraries are up to date as per PIP.  As per another issue in here, I've started Spyder with "--show-console" to see if any errors were not being shown.  There are no errors showing up in the console.

**What steps will reproduce the problem?**

1. Start Spyder

**What is the expected output? What do you see instead?**

In my other installs of Spyder on Linux, the IPython console just works.  In this Windows install, I'm seeing nothing but a blank gray area where the console should be.  Please see the attached PNG.

![spyder-ipython](https://cloud.githubusercontent.com/assets/2373600/13931731/a8e8f39a-ef72-11e5-892c-8e218aff88d6.png)

Thanks for any help you can give me.  :)

* Spyder Version: 2.3.8 
* Python Version: 2.7.10
* Qt Versions:  4.8.5, PySide 1.2.2 on Windows

## Optional dependencies
```
pyflakes >=0.5.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
sphinx >=0.6.6     :  1.3.6 (OK)
rope >=0.9.2       :  0.10.3 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  0.7.6 (OK)
pylint >=0.25      :  1.5.5 (OK)

```

**Comment by ccordoba12** [comment]
Sorry, we don't support PySide anymore, please PyQt. Also, please update your Qt version to 4.8.7.

**Comment by manney** [comment]
Thank you, sir.  Since I've moved to PyQt4, it's now working.
