### ISSUE TITLE
Autoformat with YAPF

### ISSUE THREAD

**Issue by carlthome** [spyder-ide/spyder#3076]
The PEP hints are great, but it would be neat to be able to auto format code selections, the entire current file, or the entire current project with [yapf](https://pypi.python.org/pypi/yapf).

**Comment by Nodd** [comment]
It's possilble with autopep8, but you have to install a plugin: https://github.com/spyder-ide/spyder.autopep8
It works only in master branch.

A plugin can be done for yapf too.

**Comment by carlthome** [comment]
Cool. Looking forward to Spyder 3. :+1:

**Comment by carlthome** [comment]
Cool. Looking forward to Spyder 3. :+1:
