### ISSUE TITLE
Spyder is freezing on Linux when scrolling a lot

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3080]
## Description

**What steps will reproduce the problem?**

Spyder has some hard freeze, I can do nothing apart killing it completely. It happened once when scrollong a lot.
I'll try to get more debug infos but I wanted to report the bug first.
The problem happened on two different computer (both with arch linux).
## Version and main components
- Spyder Version: 3.0.0dev 
- Python Version: 3.5.1
- Qt Versions: 5.5.1, PyQt5 5.5.1 on Linux
## Dependencies

```
pyflakes >=0.6.0:  1.1.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1.3 (OK)
qtconsole >=4.0 :  4.2.0 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
numpy >=1.7     :  1.10.4 (OK)
sphinx >=0.6.6  :  1.3.6 (OK)
psutil >=0.3    :  4.0.0 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
No one else has reported this bug in quite some time. It was probably a Qt issue, so closing :-)
