### ISSUE TITLE
ImportError: No module named 'google'

### ISSUE THREAD

**Issue by porvakanti** [spyder-ide/spyder#3081]
## Description of your problem

**What steps will reproduce the problem?**

1. Install Python 3.5
2. Run 'pip install google' command and verify the google module is present
3. Install Anaconda 3.5
4. Try to run a sample code with this line: from google import search
5. Error: ImportError: No module named 'google'

**What is the expected output? What do you see instead?**
The import should work fine as the google module was installed

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.5
* Python Version: 3.5
* Operating system: Windowns 7
![spyder-error](https://cloud.githubusercontent.com/assets/7094302/14002930/80ead0c8-f14f-11e5-8a4d-495ffa91bd59.jpg)
![googlemodule](https://cloud.githubusercontent.com/assets/7094302/14002932/80eb7226-f14f-11e5-847c-c4971568aa53.jpg)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Anaconda comes with its own Python version inside it, so you don't need to install Python 3.5 first.

What you need to do is uninstall everything, install *only* Anaconda, and then call `pip install google` from the command, as you just did.

After that things should work as expected :-)

**Comment by porvakanti** [comment]
Thank you cordoba! I will try as you suggested.

**Comment by porvakanti** [comment]
Hi Cordoba. The issue fis fixed. Thank you!

**Comment by mohosin16103308** [comment]
Hello,I try 
pip install google .But In Spyder Python 3.7 .It's not working.
Would pls let me know.Is there any other way to fix this issue.
from google.cloud import language.Error Message is given below : 
Traceback (most recent call last):
  File "<ipython-input-9-4a37730905af>", line 1, in <module>
    from google.cloud import language

ModuleNotFoundError: No module named 'google'
