### ISSUE TITLE
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>

### ISSUE THREAD

**Issue by porvakanti** [spyder-ide/spyder#3083]
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder
2. Run the attached code
3. Im getting the URLError

**What is the expected output? What do you see instead?**
Expected output is two csv files with the list of URLs and text. I get the following error instead:
`URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:645)>`

**Please provide any additional information below**
I ran the same code with BMW in the parameter in place of ExxonMobil. I could successfully generate the csv files.

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 3.5.0
* Operating system: Windows 7

[google.txt](https://github.com/spyder-ide/spyder/files/188092/google.txt)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Maybe this is fixed if you install openssl with

    conda install openssl

**Comment by porvakanti** [comment]
Hi cordoba,
Do I have to run the command from Anaconda/Scripts location?

**Comment by ccordoba12** [comment]
Sorry, but this doesn't seem to be an Spyder error, but a problem with the program you're trying to run. You should google about it to see if you find a solution.

Because of that I'm closing this issue.

**Comment by porvakanti** [comment]
Sure Cordoba,
Thank you for your insights! Much appreciated.
