### ISSUE TITLE
Spyder display "project error" on terminal when start.

### ISSUE THREAD

**Issue by daherk2** [spyder-ide/spyder#3085]
## Description

**What steps will reproduce the problem?**

1. when I type on Terminal "spyder"
2. it echo me "project error" 
3. and program runs normaly.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  14.4.1 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.15.0 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  2.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.4.2 (OK)
sympy >=0.7.3      :  1.0 (OK)
pylint >=0.25      :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
I think this happens because you have the wrong version of rope, one of our code completion libraries.

How did you install Spyder?

**Comment by daherk2** [comment]
I installed spyder by "pip install spyder".
I think I managed remove the bug... I removed the numpy library, I restarted the machine, and then i installed again numpy.
It works well!

**Comment by ccordoba12** [comment]
Ok, good to know :-)
