### ISSUE TITLE
Cannot open/save files from gui (QFileDialog issue) on the Win8. 

### ISSUE THREAD

**Issue by m-gorbulsky** [spyder-ide/spyder#3088]
The code below worls fine in the PyCharm and from the console, but crashes in the Spyder with:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)
  File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Projects/SpyderWorkSpace/test/test.py", line 23, in <module>
    window = MainWindow()
  File "C:/Projects/SpyderWorkSpace/test/test.py", line 18, in **init**
    PyQt4.QtGui.QFileDialog.DontUseNativeDialog)
TypeError: QFileDialog.getOpenFileName(QWidget parent=None, QString caption=QString(), QString directory=QString(), QString filter=QString(), QString selectedFilter=None, QFileDialog.Options options=0): argument 5 has unexpected type 'NoneType'

see also [Cannot open/save files from gui: QFileDialog issue. #960 ](https://github.com/spyder-ide/spyder/issues/960#issuecomment-198019955)

```python
# region sample code:

import sys
import PyQt4.QtGui
import PyQt4.QtCore

class MainWindow(PyQt4.QtGui.QMainWindow):
    def **init**(self, parent=None):
        PyQt4.QtGui.QMainWindow.**init**(self, parent)
        PyQt4.QtGui.QFileDialog.getOpenFileName(None,
                                                'Test',
                                                'c:\',
                                                '',
                                                None,
                                                PyQt4.QtGui.QFileDialog.DontUseNativeDialog)

if **name** == "**main**":
    app = PyQt4.QtGui.QApplication(sys.argv)

window = MainWindow()

sys.exit(app.exec_())
```
- Spyder Version: 2.3.8
- Python Version: 2.7.11
- Operating system: Windows 8.1
# endregion
```

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pyflakes >=0.5.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by goanpeca** [comment]
I do not think this is relevant
