### ISSUE TITLE
Spyder-App python version is not updated

### ISSUE THREAD

**Issue by vijayan-n** [spyder-ide/spyder#3091]
## Description

**What steps will reproduce the problem?**
1. Spyder-App Python version still shows 3.4 in the taskbar and dashboard
2. 
3. 

**What is the expected output? What do you see instead?**
Spyder (Python 3.5)

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.8 
- Python Version: 3.5.1
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux
## Optional dependencies

```
pyflakes >=0.6.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
Are you using Anaconda?

**Comment by vijayan-n** [comment]
yes... anaconda 4.0

**Comment by vijayan-n** [comment]
For your Information, it is functioning properly and the iPython console is of the latest version.
The only problem is with the display. Attaching the screenshot below for your reference.
![image](https://cloud.githubusercontent.com/assets/12871236/14263179/c1984278-fad6-11e5-87d8-ec01113adf47.png)
P.S. The title bar is displaying the name properly => Spyder (Python 3.5)

**Comment by ccordoba12** [comment]
Thanks for the screenshot, now I understand your problem :-)

I don't know where it could be coming from...

**Comment by vijayan-n** [comment]
Okay! I just wanted to bring it to your notice.
There's no functional backlog.
So, you could consider this as a low priority issue...

(P.S. I have installed only Anaconda of Python 3.5. So, am not sure about Spyder-App corresponding to Python 2.7, if concurrently run)

Thank You!

**Comment by ccordoba12** [comment]
`spyder-app` was deprecated in Anaconda.
