### ISSUE TITLE
Error opening IPython Console on Windows 10 Education because of path.py error

### ISSUE THREAD

**Issue by ckaldemeyer** [spyder-ide/spyder#3094]
## Description of your problem

**What steps will reproduce the problem?**

1. Install newest Anaconda Python distribution (Anaconda 3.5) for WinX64
2. Open Spyder
3. Look at the place where normally the IPython console shows up

**What is the expected output? What do you see instead?**
An IPython console.

Instead I get the following error:

An error ocurred while starting the kernel
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AttributeError: module 'pkg_resources' has no attribute 'DistributionNotFound'
Traceback (most recent call last):
File "C:\Users\Cord\Anaconda3\lib\site‑packages\path.py", line 123, in 
__version__ = pkg_resources.require('path.py')[0].version
AttributeError: module 'pkg_resources' has no attribute 'require'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\Cord\Anaconda3\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 183, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "C:\Users\Cord\Anaconda3\lib\site‑packages\IPython\__init__.py", line 49, in 
from .terminal.embed import embed
File "C:\Users\Cord\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 16, in 
from IPython.core.interactiveshell import DummyMod
File "C:\Users\Cord\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 31, in 
from pickleshare import PickleShareDB
File "C:\Users\Cord\Anaconda3\lib\site‑packages\pickleshare.py", line 41, in 
from path import path as Path
File "C:\Users\Cord\Anaconda3\lib\site‑packages\path.py", line 126, in 
except pkg_resources.DistributionNotFound:
AttributeError: module 'pkg_resources' has no attribute 'DistributionNotFound'

**Please provide any additional information below**

## Versions and main components

* Spyder Version:2.3.8
* Python Version:3.5
* Operating system: Windows 10 X64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. Could you open a terminal (i.e. `cmd.exe`), and run this command?

    conda update path.py

That should fix your problem :-)

**Comment by ckaldemeyer** [comment]
Hi Carlos! Yes, this fixed my problem! Thanks!

**Comment by ccordoba12** [comment]
That means that you probably don't have the latest Anaconda version :-) Please make sure of that because the latest version is Anaconda 4.0 (which was released last week).

**Comment by ckaldemeyer** [comment]
I have 4.0.5. installed.

**Comment by ckaldemeyer** [comment]
According to `conda --version`

**Comment by ccordoba12** [comment]
I see. You're probably not aware of the differences between conda and Anaconda:

1. conda is a package manager, i.e. it's a program that let's you install, update and remove packages from your system.
2. Anaconda is scientific Python distribution, i.e. it's a collection of scientific packages based on Python that uses conda to install them in your system.

So the two are different things and have different versions and release schedules :-)

**Comment by ckaldemeyer** [comment]
You're right, I wasn't aware of that! Thanks for your advice.

I used the latest Anaconda installer from today: https://www.continuum.io/downloads so it should be the newest, I guess!?

**Comment by ccordoba12** [comment]
Yep, that's the newest Anaconda

**Comment by Nodd** [comment]
I guess it's too late, but to update anaconda you don't have to reinstall it completely. Just use the command `conda update anaconda`.

**Comment by ckaldemeyer** [comment]
It was a bare installation to check how everything works on Windows (for my students) so I didn't have to reinstall everything. Thanks anyway!

**Comment by ckaldemeyer** [comment]
I had the same issue now several times. Sometimes the execution of the "spyder reset script" works and sometimes it doesn't.

What's the cause for this error? And is there and long-term fix?

Cheers
Cord

**Comment by ccordoba12** [comment]
Let me see if I understand you correctly: is this error still happening for you with the latest Anaconda?

**Comment by ckaldemeyer** [comment]
> Let me see if I understand you correctly: is this error still happening for you with the latest Anaconda?

Yes, but only occasionally and I don't understand why ;-)

**Comment by Nodd** [comment]
It's a path.py bug fixed in its master branch recently, I don't think there is a stable release including it yet.

**Comment by ckaldemeyer** [comment]
Do you mean the path package (https://github.com/jaraco/path.py)?

I am not familiar with their release cycles or workflow. Does it make sense to convince them to merge back into the master?

**Comment by Nodd** [comment]
It should be fixed in the last path.py version.
