### ISSUE TITLE
Can existing files be added to a Spyder project?

### ISSUE THREAD

**Issue by jandyman** [spyder-ide/spyder#3099]
I'm trying to add an existing source file to a Spyder project. I cannot figure out how. Is it even possible? Is Project Explorer a common used tool or is it somewhat of an "orphan"?

1. Open a new workspace
2. Create a new project
3. Look for ways to import/add an existing file.

* Spyder Version: 3.0 beta
* Python Version: 3.5.1
* Operating system: Mac El Capitan

**Comment by goanpeca** [comment]
@jandyman thanks for your input. 

Projects is being reworked as part of the 3.0 release but it is note yet fully implemented in current beta. PRs are on the way.

**Comment by jandyman** [comment]
Excellent and thanks for the prompt reply. I'll use other techniques until a PR.

- Andy

**Comment by ccordoba12** [comment]
This will be solved as part of #3377. Our new projects are attached to a directory, so you need to add files to a project, you just add them to the directory.

**Comment by JoshuaC3** [comment]
If I am creating a python package with the following file structure:

```
antigravity
├── antigravity.py
└── test_antigravity.py
```

Where should I create the project? Under, above or level with antigravity?

**Comment by ccordoba12** [comment]
> Where should I create the project? Under, above or level with antigravity or antigravity itself?

You should select the top most `antigravity` directory to be the root of your project.

> Also, what is intended to go in the project folder? Is it the test dir as well?

That depends on what you want, but usually tests are part of the project too.

----

All of this would be clearer and more intuitive than it is now, when we introduce template projects (in Spyder 4). Thanks for your patience until then.

**Comment by JoshuaC3** [comment]
I was worried you would say this,
> That depends on what you want
The Template Projects sounds great. For now a best practice doc/cheat-sheet might be very useful. 
Many thanks
