### ISSUE TITLE
Failure to launch on Mac OS X after upgrade to 3.0.0b2

### ISSUE THREAD

**Issue by tobydavies** [spyder-ide/spyder#3104]
## Description of your problem

Attempted to upgrade to v3.0.0b2 in order to fix Issue #2724, following the steps described in the comment [here](https://github.com/spyder-ide/spyder/issues/2724#issuecomment-190788309). After following those steps, Spyder fails to launch, giving a 'Python crashed unexpectedly' error.

**What steps will reproduce the problem?**

1. Upgrade Spyder and PyQt, following [these steps](https://github.com/spyder-ide/spyder/issues/2724#issuecomment-190788309).
2. Launch Spyder, either from command line or Anaconda Launcher.

**What is the expected output? What do you see instead?**

Expected is an instance of Spyder. Instead get a 'Python quit unexpectedly' dialog, and a command line output '/Users/username/anaconda/bin/python.app: line 3: 87074 Bus error: 10'. Launching via Anaconda Launcher GUI gives same result. Rolling back to 2.3.8 works fine again, though Issue #2724 persists.

**Please provide any additional information below**

During rollback to 2.3.8, conda gives warning messages

Warning: 4 possible package resolutions (only showing differing packages):
  - qtawesome-0.3.2-py27_0.tar.bz2, qtpy-1.0-py_0.tar.bz2
  - qtawesome-0.3.2-py_0.tar.bz2, qtpy-1.0-py_0.tar.bz2
  - qtawesome-0.3.2-py27_0.tar.bz2, qtpy-1.0-py27_0.tar.bz2
  - qtawesome-0.3.2-py_0.tar.bz2, qtpy-1.0-py27_0.tar.bz2

Do not know if this is relevant...

## Versions and main components

* Spyder Version: 3.0.0b2
* Python Version: 2.7.11 via Anaconda 4.0.0
* Operating system: Mac OS X 10.11.3

## Dependencies

These obtained after rollback to 2.3.8:
IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  0.7.2 (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Is there something printed in the terminal before the crash occurs?

**Comment by tobydavies** [comment]
Nothing other than the
`'/Users/username/anaconda/bin/python.app: line 3: 87074 Bus error: 10'`
message when the crash occurs.

**Comment by ccordoba12** [comment]
This is going to be definitely solved when we release Spyder 3.0 with Anaconda 4.1 at the end of the month :-)
