### ISSUE TITLE
IPython console fails to start in Spyder

### ISSUE THREAD

**Issue by tombardo** [spyder-ide/spyder#3106]
## Description of your problem

When starting spyder the iPython console is unable to connect to kernel. The console displays:

```
'import sitecustomize' failed; use -v for traceback
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)
```

**What steps will reproduce the problem?**
1. Installed Anaconda 4.0
2. Start Spyder

**What is the expected output? What do you see instead?**
Expect to see an iPython console, instead see perpetual spinning wheel that indicates "Connecting to kernel..."

**Please provide any additional information below**
The only modifications I have done is to move shortcuts around in the Windows start menu. I have tried resetting the spyder settings and deleting the .spyder2 and .ipython folders with no success. Eventually the python console is functional and I can import IPython there. I can also start an iPython console from the windows command line.
## Versions and main components
- Spyder Version: 2.3.8
- Python Version: 2.7.11
- Operating system: Windows 7 x64
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
What happens when you run in a terminal

    jupyter qtconsole

? Do you see the same problem?

**Comment by tombardo** [comment]
@ccordoba12 Yes, I see the same problem. The console hangs and nothing comes up.  Any ideas?

**Comment by tombardo** [comment]
@ccordoba12 Eventually an error pops up:

`Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)`

and I get a message that python.exe has stopped working, asking me if I want to debug.

**Comment by ccordoba12** [comment]
@minrk, this seems to be a problem with pyzmq. Do you know something about it?

@tombardo, what happens if you run in a terminal

    conda install pyzmq=14.7.0

and try again with

    jupyter qtconsole

?

**Comment by tombardo** [comment]
@ccordoba12 That fixed it. Spyder and jupyter qtconsole now work appropriately. Thanks a lot.

**Comment by zandywill** [comment]
I have the same problem, but this did not fix it for me.  When I start Spyder, it will not connect to the kernel and the kernel panel gives me the error of ''import sitecustomize' failed; use -v for traceback'.

**Comment by minrk** [comment]
@ccordoba12 my guess is that pyzmq+libzmq got mixed up (common cause: upgrade libzmq without rebuilding pyzmq).

**Comment by ccordoba12** [comment]
So this could be a problem with Anaconda?

**Comment by ccordoba12** [comment]
Closing, as this is a very old problem.
