### ISSUE TITLE
Hello Dev team, I have a question, i'm actually trying to upload an image on spyder using html but how do I retrieve the images to display when I'm running? When I use sublime my images appear because i'm able to go into the folder and pull the images, but how would I do the same thing when I'm doing it in Python spyder? 

### ISSUE THREAD

**Issue by POPii1** [spyder-ide/spyder#3107]
## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I'm sorry but I don't understand your question. Besides, this site is to report Spyder bugs and not to ask questions :-(

Please post your question here instead:

https://groups.google.com/forum/#!forum/spyderlib
