### ISSUE TITLE
spyder cann't connect the ipython console on ubuntu14.04LTS

### ISSUE THREAD

**Issue by xzqjack** [spyder-ide/spyder#3108]
## Description of your problem

Spyder cann't connect the ipython console on ubuntu 14.04 LTS, and show the below

>   "You should import from ipykernel or jupyter_client instead.", ShimWarning)
> /usr/local/lib/python2.7/dist-packages/IPython/config.py:13: ShimWarning: The `IPython.config` package has been deprecated. You should import from traitlets.config instead.
>   "You should import from traitlets.config instead.", ShimWarning)
> NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
> To exit, you will have to explicitly quit this process, by either sending
> "quit" from a client, or using Ctrl-\ in UNIX-like environments.
> To read more about this, see https://github.com/ipython/ipython/issues/2049
> To connect another client to this kernel, use: --existing kernel-15479.json
> [TerminalIPythonApp] WARNING | Subcommand `ipython qtconsole` is deprecated and will be removed in future versions.
> [TerminalIPythonApp] WARNING | You likely want to use `jupyter qtconsole`... continue in 5 sec. Press Ctrl-C to quit now. 

Running `ipython console` will show the below and jupter qtconsole will work instead of ipython console.

> /usr/local/lib/python2.7/dist-packages/IPython/kernel/**init**.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.

**What steps will reproduce the problem?**
1. reinstall ipython by uninstall and install with pip
2. reinstall jupter by uninstall and install with pip
3. reinstall spyder by uninstall and install with pip

**What is the expected output? What do you see instead?**
Spyder can connect the ipython console in spyder and works

**Please provide any additional information below**
Spyder can connect python consolo and works well. 
Running `ipython` and `jupyter qtconsole` in terminal work well. 
## Versions and main components
- Spyder Version:2.3.8
- Python Version:2.7
  *IPython Version: 4.1.2
- Operating system:Ubuntu14.04 LTS
## Dependencies

IPython >=0.13  :  4.1.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
pep8 >=0.6      :  1.4.6 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pylint >=0.25   :  1.1.0 (OK)
rope >=0.9.2    :  0.9.2 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  0.7.6.1 (OK)

Thanks in advance!

**Comment by ccordoba12** [comment]
Please run

    spyder --reset

and try again

**Comment by LaoAnchor** [comment]
@ccordoba12  i have run `spyder --reset` and spyder reset all settings to defaults. But the problem still exist. Here are the screenshot.
![2](https://cloud.githubusercontent.com/assets/13688178/14453345/cff6d302-00c6-11e6-87aa-bb27a89ff740.png)
![1](https://cloud.githubusercontent.com/assets/13688178/14453351/d933158e-00c6-11e6-8e73-319259b75e6b.png)
By the way, i have tried reinstalling spyder again.

**Comment by ccordoba12** [comment]
Please update to Spyder 3.0.2. This problem should be fixed now in that version.

**Comment by Algabri** [comment]
@ccordoba12  
I get the same issue
the reason,  I updated python2.7.6 to 2.7.12
I remove spyder 2 and installed 3, this needs to install everything 
please help me to fix it
