### ISSUE TITLE
Auto select the only IPython or Python console after startup

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#3109]
When I first start Spyder and try to run a file, a dialog pops up with the complaint:

> No Python console is currently selected to run XXX.py.
> 
> Please select or open a new Python console and try again.

Since I have only one IPython console open and no Python console, I think it will be great if Spyder can automatically select that only IPython console for me and run the file...

I guess many users would have only one IPython or Python console open after starting Spyder, 
so it can be a very convenient feature for Spyder to auto select the only IPython or Python console after startup.

**Comment by ccordoba12** [comment]
This is going to be solved by PR #2878.
