### ISSUE TITLE
Add spell checker for docstrings

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#311]
_From [tim.mich...@gmail.com](https://code.google.com/u/117399810383525443135/) on 2010-08-24T07:21:12Z_

Hello,
there is a library that supports spellchecking of docstrings: http://www.language-binding.net/pydsc/pydsc.html Would be nice to have this feature in Spyder.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=311_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-17T13:06:10Z_

**Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:09:22Z_

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-29T04:30:54Z_

**Status:** ContributorNeeded

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:08:44Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:16:30Z_

**Status:** HelpNeeded

**Comment by goanpeca** [comment]
The link to the library seems to no work, I do not think this is going to happen.
