### ISSUE TITLE
Console panel resizing itself as new console tabs are opened

### ISSUE THREAD

**Issue by discardthree** [spyder-ide/spyder#3116]
I just changed from Windows to Mac, and I'm noticing a behaviour in Spyder on Mac that I don't think I saw while using Spyder on Windows.  Sorry if this is a duplicate or otherwise irrelevant, I tried a few searches but didn't find anything.

## Problem description
It seems like the Console pane's width enforces some 'minimum mandatory size' which changes based on the number of console tabs currently open.  Specifically, it's trying to ensure that the Console pane is always wide enough to show all the tabs.  As I open new tabs, the Console pane is growing to accommodate, and I can't manually resize it to be any smaller.

I wondered if this was supposed to be a 'feature' rather than a 'bug', but
1. Once you've opened several consoles, it really does get pretty ridiculous (see second screenshot), and
2. I don't see why the console space would be 'protected' like this when the editor isn't.

I may be wrong, but I thought that on Windows the Console pane was handled the same as the Editor pane, which doesn't change size when new tabs are opened and uses scroll buttons on the tab bar if there are too many tabs to display.

## Screenshots
For example, here's the console pane after opening 3 dedicated consoles.  (Before starting I set it to about a third of the screen width.)
<img width="1278" alt="spyder-bug-report-1" src="https://cloud.githubusercontent.com/assets/10099583/14508373/22aa9a10-0195-11e6-815c-9327b2b5832b.png">

And here it is after opening a couple more.
<img width="1279" alt="spyder-bug-report-2" src="https://cloud.githubusercontent.com/assets/10099583/14508706/c575692c-0196-11e6-84fc-8148bb1eff3c.png">
I have the ability to pull the divider further left but not further right.  Notice how there are buttons for scrolling through the editor tabs (although without any markings on them, which is perhaps also an issue?), it's only the console that has this funny behaviour.

**What steps will reproduce the problem?**
1. Close all panes except the Editor and Console, and have them displayed side by side (not popped out).  Drag the divider so that the Console panel is just a few inches wide. 
2. Open some number of console windows.
3. See if the Console pane has enlarged itself, and see if you can move it to make the editor larger and the console smaller.

**What is the expected output? What do you see instead?**
I assume the desired behaviour is for the Editor and Console panes to handle tabs the same way.  See screenshots to see what happens instead.

## Versions and main components

* Spyder Version: 2.3.8 (came with Anaconda)
* Python Version:  Python 2.7.11  (Anaconda 4.0.0 (x86_64))
* Operating system: Mac OS X 10.11.3

For what it's worth, the About window in Spyder also says:
Python 2.7.11 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Dependencies
IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  1.5.5 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by goanpeca** [comment]
@discardthree thanks for reporting. This is definitely not a feature, and probably is a Mac related thing only. We will explore how to correct this, ok?

Cheers :-)

**Comment by discardthree** [comment]
Sounds good.  Thanks for all your work on this project, I've been using Spyder for about 5 years and will keep using it even if I have to moderate the tab situation a little bit. ;)  Let me know if there's anything I can do to provide more information.

**Comment by ccordoba12** [comment]
@discardthree, thanks a lot for your detailed report. Quick question: does it happen the same with the IPython console?

**Comment by discardthree** [comment]
Yes, I just tried and it does.  By the way, I opened more tabs this time to see if it would hit some limit.  When the editor pane is about 1.5" wide and can't shrink anymore, the whole window size extends to the right so the console pane can grow in that direction.  Well, at least it doesn't crash. :wink:
