### ISSUE TITLE
Problem with syntax highlighting for reStructured text 

### ISSUE THREAD

**Issue by solarjoe** [spyder-ide/spyder#3117]
Using the directive `:math:`test`` breaks the coloring of reSt files.
I am not sure if this is limited to this directive.

Sometimes text not in backticks is colored (green), sometimes the whole document.
After saving the document the syntax highlighting sometimes changes, sometimes for the
better, sometimes for the worse.

**What steps will reproduce the problem?**
1. Add some sections and a bit of text to the document.
2. Do not copy the tag mentioned above to a document, write it.
3. Once the two backticks appear, they turn green. Correct so far.
4. Insert text in between, now sometimes the "math" gets colored. Also fine.
5. Add text after the second backtick. Is also colored.
6. Add text on a new line. Is also colored.
7. Sometimes the text before the math tag is colored on saving.

Could this be related if there are double backticks in the text before?

**Versions and main components**
- Spyder Version: 3.0.0dev
- Python Version: 3.4.4 64-bit
- Operating system: Windows 7, 64-bit

**Comment by solarjoe** [comment]
I just took a look at utils/syntaxhighlighters.py and saw that the highlighting for reSt seems to be based on Pygments. Is this a Pygments bug then?

**Comment by ccordoba12** [comment]
It could be, yes. The problem with rest is that you have to parse the entire file (instead of a single line) to have the right highlighting.

**Comment by solarjoe** [comment]
It seems that this is not related to `:math:`, rather to the backticks. 
(Pygments code for string highlighting in [markup.py](https://bitbucket.org/birkenfeld/pygments-main/src/ef81d4814bc6b6894cc054b3b66bb2dcbf79add9/pygments/lexers/markup.py?at=default#markup.py-239))

This should be a very basic feature in Pygments, so I guess the issue is with Spyder.
If you have rough directions for me on where this could be fixed I can give it a try.

**Comment by ccordoba12** [comment]
@solarjoe, thanks for your offer to help us :-)

Our syntax highlighting facilities are present in this file:

https://github.com/spyder-ide/spyder/blob/master/spyderlib/utils/syntaxhighlighters.py

**Comment by goanpeca** [comment]
We have not received more input on this issue. I would close this @ccordoba12
