### ISSUE TITLE
Auto-generated code header in Spyder can cause code to fail

### ISSUE THREAD

**Issue by guygriffiths** [spyder-ide/spyder#3125]
## The automatically generated header in spyder doesn't check for invalid escape sequences

In Spyder on Windows, upon startup, a file named ".temp.py" is created with some header text of the form:

```
"""
Spyder Editor

This temporary script file is located here:
C:\Users\x-user\.spyder2\.temp.py
"""
```

If one of the directories in the default path begins with an x and is not followed by a valid hexadecimal sequence, the code will fail with the error:

`ValueError: invalid \x escape`

**What steps will reproduce the problem?**

1. Start a fresh session of Spyder on WIndows with a username starting xxx (or similar)

Spyder should either escape the backslashes in the path, or use slashes in their place when generating the header code

## Versions and main components

* Spyder Version: 2.2.5
* Python Version: 2.7
* Operating system: Windows 7

**Comment by Nodd** [comment]
Your version is very out-of-date, please update it. This bug is corrected in the last version.
