### ISSUE TITLE
Project Explorer filename filter (minor)

### ISSUE THREAD

**Issue by Winand** [spyder-ide/spyder#3128]
WinPython-64bit-3.5.1.3

If one checks `Show all files` menu item, then edits filter with `Edit filename filters...` filter is set again, though `Show all files` is still checked.

P. S. also by default Spyder in WinPython-64bit-3.5.1.3 doesn't include some filename filters which it used to unclude in previous versions: `.pyx`, `.ini`. Maybe some others. Don't know if it's a Spyder's issue.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll see what we can do about this for Spyder 3.0.

**Comment by Winand** [comment]
Also there's a problem with Project Explorer font setting. It changes but the internal console gives:
```
Traceback (most recent call last):
  File "D:\andray\Software\WinPython-32bit-3.4.4.2\python-3.4.4\lib\site-packages\spyderlib\plugins\projectexplorer.py", line 129, in change_font
    self.set_plugin_font(font)
TypeError: set_plugin_font() takes 1 positional argument but 2 were given
```
When I've opened the font dialog once again, default (Consolas) font was selected
