### ISSUE TITLE
Is there a way to modify the main window title?

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder#3129]
We are working in a multi-user environment with multiple instances of spyder opened. It would be convenient to show the session name (or any string) in the window title. Is there already a method to to this? If not, I can add a command line option to enable this.

**Comment by goanpeca** [comment]
Hi @eendebakpt, could you elaborate a bit more?

**Comment by peendebak** [comment]
Right now the title of my spyder window is `Spyder (Python 3.4)`. I would like to be able to set this (from either the command line or using a script) to something like `Spyder (Python 3.4): current user "Pieter"`

**Comment by goanpeca** [comment]
I meant context for 
>multi-user environment with multiple instances of spyder opened

Not the actual implementation (that I understood)

I fail to see how this "work environment works"

@ccordoba12 ?

**Comment by ccordoba12** [comment]
@peendebak and @eendebakpt, we're glad to accept a pull request to help you improve your workflow (although as @goanpeca said, we don't understand too well how that works :-).

Command line options are defined here:

https://github.com/spyder-ide/spyder/blob/master/spyderlib/app/cli_options.py

and the window title is set here:

https://github.com/spyder-ide/spyder/blob/master/spyderlib/app/spyder.py#L432

**Comment by Nodd** [comment]
Would it help to add the current focused filename in the title ?

Otherwise I guess that a plugin coud be made to fit your specific need. They are revamped for spyder 3.0 and it should be easier to manage them.

**Comment by eendebakpt** [comment]
I just added a PR which add an option to the command line. Making a plugin might also be an options, but I guess this is more work (and the documentation at https://github.com/spyder-ide/spyder/wiki/SEP-5:-Core-Extension-Plugins is quite sparse)

**Comment by Nodd** [comment]
Right now the plugin documentation is nonexistent. :disappointed: 
If you're interested, you can look at https://github.com/spyder-ide/spyder.example for an example, or at other spyder.* repos in https://github.com/spyder-ide/.
