### ISSUE TITLE
split vertically and split horizontally are mixed up

### ISSUE THREAD

**Issue by mjkrause** [spyder-ide/spyder#3130]
## Description

**What steps will reproduce the problem?**

1. Open the Editor in Spyder
2. have one window open in the Editor
3. in the Editor, use the icon on the top right corner, click it to get the pull-down, and execute "split vertically"

**What is the expected output? What do you see instead?**
I expected the window to be split vertically after the execution. Instead, the window is split horizontally

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.5.1
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
I don't think we're going to change this. There's no chance that all people agree on what split *vertically* and *horizontally* means, but the icons associated with each icon are very clear.

**Comment by mjkrause** [comment]
Okay, I don't have any doubts about the semantics of vertical vs.
horizontal, but I see what you mean. It seems like it depends on whether
you're in the vim or the emacs camp...

http://english.stackexchange.com/questions/293520/split-horizontally-or-vertically-which-one-is-which

Cheers,
Michael


On Thu, Apr 21, 2016 at 11:01 AM, Carlos Cordoba <notifications@github.com>
wrote:

> I don't think we're going to change this. There's no chance that all
> people agree on what split *vertically* and *horizontally* means, but the
> icons associated with each icon are very clear.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/issues/3130#issuecomment-213039806>
>



-- 
*Bad programmers worry about code. Good programmers worry about data
structures and their relationships.*
— Linus Torvalds

**Comment by goanpeca** [comment]
@mjkrause I think the best is to use a different wording that is straightforward.

Split vertically = Verb + Adverb = Split in the vertical direction
Vertical Split = adjective + noun = Split in the horizontal direction  

So maybe the wording could be: Add vertical division, Add horizontal division

**Comment by mjkrause** [comment]
@goanpeca that sounds like a good solution, although overall I consider it a minor issue
