### ISSUE TITLE
Spyder does not recognize PyQt5 for Python 3.5.1 on Windows 10 64bit

### ISSUE THREAD

**Issue by Skylion007** [spyder-ide/spyder#3131]
## Description of your problem

**What steps will reproduce the problem?**

1.  Install PyQt5 via pip
2.  Install spyder via pip
3. launch spyder

**What is the expected output? What do you see instead?**
I expect Spyder to work properly with the latest version of PyQt5. I believe PyQt5 support has been with Spyder for a while if I am not mistaken.

PS C:\Users\Skylion\Desktop\maldump2> spyder
Traceback (most recent call last):
  File "C:\Users\Skylion\AppData\Local\Programs\Python\Pytho
 <module>
    from PySide import __version__  # analysis:ignore
ImportError: No module named 'PySide'

During handling of the above exception, another exception oc

Traceback (most recent call last):
  File "C:\Users\$USER\AppData\Local\Programs\Python\Pytho
n check_qt
    from spyderlib import qt
  File "C:\Users\$USER\AppData\Local\Programs\Python\Pytho
 <module>
    raise ImportError("Spyder requires PySide or PyQt to be
ImportError: Spyder requires PySide or PyQt to be installed

**Please provide any additional information below**

## Versions and main components

* Spyder Version: latest from Pip
* Python Version: Python 3.5.1
* Operating system: Windows 10 64bit

## Dependencies
PyQt5

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
You need to install Spyder beta to make it work with PyQt5. For that you need to run

    pip install --pre spyder
