### ISSUE TITLE
Why I can't input Captical letter in Spyder

### ISSUE THREAD

**Issue by clyyuanzi** [spyder-ide/spyder#3132]
## Description

**What steps will reproduce the problem?**
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.8 
- Python Version: 2.7.11
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.0 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
What is a Captical letter?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
