### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by SCICN** [spyder-ide/spyder#3134]
## About support Chinese

Hello! I want upload Chinese translation but I don't know how to do it. 

And localization files in [https://github.com/SCICN/zh_translation](url)

Thanks!

**Comment by ccordoba12** [comment]
@SCICN, thanks a lot for wanting to improve Spyder! Unfortunately it seems you translated our stable branch, i.e. Spyder 2.3.8 or a lower version but we need you to translate our future version, i.e. Spyder 3.0.

But don't worry, this is not much of a problem ;-) To add your translation to our source tree you need to

1. Follow our Development guide:

  https://github.com/spyder-ide/spyder/wiki/Dev%3A-Github-Workflow

  to clone our repository in Github and create a git branch on it.

2. Add you translation under the `spyderlib/locale` directory.

3. Update your translation files to use the most recent `spyderlib.pot` file.

4. Commit your work to your branch and create a pull request so we can merge it.
 
If you have any doubts about this process, please let us know about it :-)

**Comment by ccordoba12** [comment]
Closing because (sadly) there was no response from @SCICN.
