### ISSUE TITLE
iPython console stucks at connecting to console. 

### ISSUE THREAD

**Issue by yleng** [spyder-ide/spyder#3135]
## Description

**What steps will reproduce the problem?**
1. I start Spyder, ipython console stucks at connecting to console. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
I am using Mac and Python 2.7. 
## Version and main components
- Spyder Version: 2.3.8 
- Python Version: 2.7.10
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.1 (OK)
zmq >=2.1.11       :  15.1.0 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.3.0 (OK)
rope >=0.9.2       :  0.10.2 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  1.4.4 (OK)

```

**Comment by ccordoba12** [comment]
This should be fixed in Spyder 3, please update.
