### ISSUE TITLE
Spyder Won't Launch 

### ISSUE THREAD

**Issue by jdweaver** [spyder-ide/spyder#3138]
## Description of your problem

**What steps will reproduce the problem?**

1. Open Anaconda Launcher
2. Find Syper, "click" Run 
3. executable script window appears
4. Sypder doesn't launch

**What is the expected output? What do you see instead?**
Expect to see Spyder launch screen and for spyder to load 

**Please provide any additional information below**
ran the following with "show console" and "reset" command, get the same error (see below). 

![image](https://cloud.githubusercontent.com/assets/8146643/14839100/e5016d22-0bdc-11e6-99d7-c362d1adfe48.png)

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7.11
* Operating system: windows 10 64big

## Dependencies
Anaconda Stack

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Could you run in a terminal

    spyder --reset

and try again?

**Comment by mtkilic** [comment]
I have the same issue. I open Anaconda Launcher and right next to Spyder, update button shown. After I updated. And try to click spyder to Launch nothing comes up. I have version 2.3.8. I am using Mac

**Comment by mtkilic** [comment]
@ccordoba12 @jdweaver Thank you spyder --reset worked! 

First reset your laptop/PC, after that open terminal and type  `spyder --reset`

**Comment by jdweaver** [comment]
Same issue :(

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Wed, Apr 27, 2016 at 8:22 AM -0700, "Carlos Cordoba" <notifications@github.com<mailto:notifications@github.com>> wrote:


Could you run in a terminal

spyder --reset


and try again?

-

**Comment by mtkilic** [comment]
@jdweaver make sure you updated to latest version first. Then reset your PC, before opening Anaconda or Spyder, open your terminal and do` spyder --reset` After that try to open spyder. It should work, because it looks like we had exact same issue. Good luck!

**Comment by ccordoba12** [comment]
@jdweaver, could you upload somewhere (e.g. as a gist) or send me directly (my email is under my Github user page) this file

     C:\Users\jdweaver\.spyder2\spyder.ini

?

That would really help me to debug and solve this problem :-)

**Comment by Nodd** [comment]
This is a recurring problem. We should catch the exception, warn the user and asks if he wants to reset the settings and restart spyder. I thinnk that it should be done even if we find the root of the problem, because spyder should be able to start even if the .ini is corrupted.

**Comment by jdweaver** [comment]
@ccordoba12 
I was able run spyder --reset but it still isn't resolving the issue. 

I'm also not seeing the spyder.ini file, it looks like it might gotten removed from the spyder reset...
I'll send you the other file it might be 

![image](https://cloud.githubusercontent.com/assets/8146643/14899136/8a656576-0d3f-11e6-8570-af954313fe8a.png)

**Comment by jdweaver** [comment]
@mtkilic was updated...i had to re-update my BIOS yesterday and now the reset worked but I'm still getting the same behavior. I click on the Spyder app directly or through the Anaconda Navigator and it looks like Spyder will load, but then it doesn't *sad panda*

**Comment by jdweaver** [comment]
@ccordoba12 So I think I figured it out. There was an issue where some additional string got added to my spyder.ini file. 
![image](https://cloud.githubusercontent.com/assets/8146643/14906377/a735682e-0d6f-11e6-9e87-d4cf0f07b71c.png)

I followed the path: C:\Users\<username>\.spyder2\spyder.ini and edited the file. I removed the end string "curso" and then was able to launch Spyder. 

Not sure how that string got in the .ini file...but it seems to be working now.

**Comment by ccordoba12** [comment]
@jdweaver, glad to know you solved the problem :-)

**Comment by KeithBrodie** [comment]
Just in case it helps, I installed clean python 3.5 from python.org on Windows 10, then pip installed spyder.  It failed silently.   I then pip installed PyQT5, uninstalled and reinstalled spyder - and it works.

**Comment by Apurva018** [comment]
Spyder doesn't launch what to do

**Comment by abhinav19792** [comment]
Try giving firewall access to python and check environment variables.

**Comment by SagarPohekar** [comment]
Guys,
I have observed the same problem:
Solution: Uninstall PyQt and then uninstall the SIP package
Reinstall above package but in following sequence:
#1 SIP
#2 PyQt4/5

**Comment by MBiagio** [comment]
I have the same problem. Spyder looks like it is going to launch and then doesn't. I tried spyder --reset, but it does nothing. This was a newly re-installed version after it didn't work the first time either.

Unfortunately I have no idea how to do what you said Sagar?

**Comment by axil** [comment]
@MBiagio I had the same problem, `pip install pyqt5` helped.

**Comment by MBiagio** [comment]
I don't know what pip install is, or what pyqt5 is. But I tried running spyder from the terminal and it worked.

**Comment by VT-SCM** [comment]
@axil this worked for me.

**Comment by ccordoba12** [comment]
This is going to be fixed in our 3.2.5 version. Thanks for your patience.

**Comment by salmanozi** [comment]
I downloaded anaconda recently and since then I couldn't lunch spyder, though I have an existing spyder in winpython before downloading anaconda as a result of the difficulty I am experiencing the winpython was uninstalled yet when I attempt opening spyder the old one comes up and prevent me from accessing new/fresh console, below is the error or respond that comes up when try to open from the only existing spyder page

File "C:\Anaconda\lib\site-packages\spyder\plugins\editor.py", line 1711, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "C:\Anaconda\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\suleiman abdullahi\\.spyder-py3\\template.py'

**Comment by obluesky** [comment]
I have no clue what pip install pyqt5 is but it solved my problem. Thanx @axil !

**Comment by obluesky** [comment]
I have no clue what pip install pyqt5 is but it worked for me! Thanx @axil

**Comment by ayofolaposy** [comment]
I had the same problem with Spyder 3.2.3 and upgraded to 3.2.6 but nothing worked. I ran pip install pyqt5 from the terminal and then launched Spyder from Anaconda and it worked! Thanks everyone for sharing!

**Comment by Pechi77** [comment]
I have the same issue, If I try `spyder --reset` I get this error `C:\Users\PA5027251>spyder --reset
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 3, in <module>
    import spyder.app.start
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 7, in <module>
    import socket
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 49, in <module>
    import _socket
ImportError: DLL load failed: Access is denied.` pls help

**Comment by haolle** [comment]
I think my spyder 3.2.7 worked fine before, but it refuses to start today. so I upgrade it to 3.2.8, it still doesn't start. It shows "start circle", and then nothing happens. I run (Win7) "spyder3.exe --reset", but doesn't help.
Hoe to fix the issue? Where to find log information to identify issue? Thanks.

**Comment by anitakh1** [comment]
spyder is not opening from anaconda prompt. i tried spyder --reset but it gave this error
""
_C:\Users\ND_Londhe\Anaconda2\lib\site-packages\dicom\__init__.py:53: UserWarning:
This code is using an older version of pydicom, which is no longer
maintained as of Jan 2017.  You can access the new pydicom features and API
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org
for more information.

  warnings.warn(msg)
Traceback (most recent call last):
  File "C:\Users\ND_Londhe\Anaconda2\Scripts\spyder-script.py", line 6, in <module>
    from spyder.app.start import main
  File "C:\Users\ND_Londhe\Anaconda2\lib\site-packages\spyder\app\start.py", line 27, in <module>
    from spyder.utils.external import lockfile
  File "C:\Users\ND_Londhe\Anaconda2\lib\site-packages\spyder\utils\external\lockfile.py", line 22, in <module>**_
    import psutil
  File "C:\Users\ND_Londhe\AppData\Roaming\Python\Python27\site-packages\psutil\__init__.py", line 137, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\ND_Londhe\AppData\Roaming\Python\Python27\site-packages\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: DLL load failed: %1 is not a valid Win32 application.""

i am running two environments on windows 10. writing spyder on prompt gives me this error.
""
C:\Users\ND_Londhe\Anaconda2\lib\site-packages\dicom\__init__.py:53: UserWarning:
This code is using an older version of pydicom, which is no longer
maintained as of Jan 2017.  You can access the new pydicom features and API
by installing `pydicom` from PyPI.
See 'Transitioning to pydicom 1.x' section at pydicom.readthedocs.org
for more information.
  warnings.warn(msg)
Traceback (most recent call last):
  File "C:\Users\ND_Londhe\Anaconda2\Scripts\spyder-script.py", line 6, in <module>
    from spyder.app.start import main
  File "C:\Users\ND_Londhe\Anaconda2\lib\site-packages\spyder\app\start.py", line 27, in <module>
    from spyder.utils.external import lockfile
  File "C:\Users\ND_Londhe\Anaconda2\lib\site-packages\spyder\utils\external\lockfile.py", line 22, in <module>
    import psutil
  File "C:\Users\ND_Londhe\AppData\Roaming\Python\Python27\site-packages\psutil\__init__.py", line 137, in <module>
    from . import _pswindows as _psplatform
  File "C:\Users\ND_Londhe\AppData\Roaming\Python\Python27\site-packages\psutil\_pswindows.py", line 16, in <module>
    from . import _psutil_windows as cext
ImportError: DLL load failed: %1 is not a valid Win32 application.""

i followed many posts but my problem is not getting rectified. i can't reinstall anaconda as i have many things installed on this. pl help me.

**Comment by anitakh1** [comment]
moreover i wrote >>conda install -f spyder. error is 
""
Solving environment: failed
NotWritableError: The current user does not have write permissions to a required path.
  path: C:\C:\Users\ND_Londhe\Anaconda2\pkgs\urls.txt""

**Comment by SHIVAMGUPTA24** [comment]
![screenshot from 2018-04-17 20-12-43](https://user-images.githubusercontent.com/25953315/39095860-fc32a64a-4664-11e8-877a-dd098aaf4ed1.png)
![screenshot from 2018-04-17 20-12-29](https://user-images.githubusercontent.com/25953315/39095861-fc8d627e-4664-11e8-9251-79da78a57c53.png)
dont know what happened .

**Comment by abhishekagrawal02** [comment]
spyder --reset  doesn't work.
pip install pyqt5  worked.

**Comment by pjk645** [comment]
When I installed tensorflow via conda it killed spyder's ability to launch. 
Versions:
Windows 7 Enterprise
Python 3.6.5
conda 3.5.4
Installer: Anaconda3_5.2.0-Windows-x86_64.exe
tensorflow 1.8.0-py36_1

After installing tf, when I tried to run spyder, it would open two instances of pythonw.exe for about ten seconds while an hour glass appeared net to the mouse. Then the instances disappeared silently and no instance of the spyder gui appeared. I tried resetting spyder as mentioned above and that didn't do it.

I think it is due to tensorflow downgrading pyqt from 5.9.2 to 5.60-py36_2 because after I uninstalled and reinstalled tf, I ran >conda update pyqt and spyder started working again. The update took pyqt from 5.6.0-py36_2 to 5.6.0-py36_5 and now spyder works. It also downgraded sip from 4.19.8-py36h6538335_0 to 4.18-py36_1.

I didn't want to open a new issue, because it seems related to the above issues and also because I was able to hack a solution. However, hopefully this helps future users.

**Comment by LA1824** [comment]
I have been getting this window, but the spyder interface is not loading up.
Anaconda Navigator 1.8.7
Spyder 3.2.8
Windows 10 64-bit
It seems the spyder is running, but it doesn't show on screen.
Tried everything reset, installing pyqt5, show console, re-installation, spyder upgrade.
Tried opening it with terminal and it doesn't throw any error, rather it showed me the same screen attached image.
![loading editor problem](https://user-images.githubusercontent.com/33568902/42010152-f5bee024-7aaa-11e8-9e76-963e5870a2c9.png)

**Comment by rb1990** [comment]
I have the same identical problem of @LA1824 . This is the error that I get (i guess is the same one). Can someone please help us? I really don't know what to do. I am trying to solve this problem for days. We got the window like if it is opening but then nothing appear on the screan. help us, please. P.s. I've also tried to install with different permission, but I'm still getting the same error.
![cattura](https://user-images.githubusercontent.com/40750862/42147015-e96da802-7e0e-11e8-9c38-6f27c077bccd.PNG)

**Comment by ccordoba12** [comment]
@rb1990, you have two Python installations and it seems you're mixing pip and conda packages, which is a recipe for disaster. My advice is for you to remove both Anaconda and your other Python installation, reinstall Anaconda and try again.

**Comment by rb1990** [comment]
Sorry @ccordoba12 how you can tell I have two Python installations? Cause I've been trying to remove everything and download again, but it's still not working. Thanks

**Comment by ccordoba12** [comment]
Look at the first two or three lines in your screenschot: you have a `site-packages` in `...\roaming\python\python3.6`. It's not another Python installation (I thought it was); it's the installation directory used of `pip install --user`.

**Comment by rb1990** [comment]
cause I tried to run "pip install pyqt5" as a user in the anaconda prompt as they said here, but still didn't work.

**Comment by ccordoba12** [comment]
I can see that. But there's no need to do that because Anaconda comes with pyqt already. That's what probably led to the fatal mix of conda and pip packages.

Look, it's clear you don't understand what you're doing. Simply remove that pip directory and try again.

**Comment by rb1990** [comment]
I've just uninstalled and cleaned everything. Reinstalled and this is the same error. I need to find out what's "keyerror: 'context' " mean. If someone can please help me. Please @LA1824 let me know if you've found a solution. @ccordoba12 Of course I don't know what I am doing, that's why I am asking if someone can please help me. I'm new with these things. Sorry :)
![cattura](https://user-images.githubusercontent.com/40750862/42195601-ff4e2440-7ebc-11e8-899b-3f4943b7d491.PNG)

**Comment by ccordoba12** [comment]
> Of course I don't know what I am doing

What I meant is that you'r blindly copy/pasting commands without understanding their purpose. And that's really bad.

Please try now:

    conda install -f zeromq pyzmq

and try again.

**Comment by rb1990** [comment]
@ccordoba12 I know, you're right and thanks for helping. Anyway, still the same identical error :( It seems no matter what I do, but it's still giving me the same problem :(
![cattura](https://user-images.githubusercontent.com/40750862/42196118-953ef5f4-7ebf-11e8-94e5-d4c93b827fe2.PNG)

**Comment by rohitgupta** [comment]
Hi,
When i try to Launch Spyder 3.2.8 from terminal and Anaconda i can see it is Launching and running but unable to see window.

I have tried even resetting spyder --rest but no luck.

When i am trying with terminal getting below error.

Please help.

rohit@rohit-H55M-S2:~$ spyder
<spyder.otherplugins._ModuleMock object at 0x7f340a1b2400>: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
Traceback (most recent call last):
  File "/home/rohit/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1086, in setup
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
Segmentation fault (core dumped)

**Comment by rb1990** [comment]
My issue was related to an antivirus getting in the way. I just uninstalled "malwarebytes" and then install again Anaconda.

**Comment by luolitao** [comment]
@rohitgupta https://github.com/spyder-ide/spyder/issues/7415

**Comment by jayrawatrj** [comment]
is any one got a perfect solution for this problem beacause i have the same problem

**Comment by jayrawatrj** [comment]
@LA1824 did u get the solution??

**Comment by ArunSha** [comment]
Hey guys, while trying to run spyder i get the following error:

**Traceback (most recent call last):
File "C:\Anaconda\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Anaconda\lib\site-packages\spyder\app\start.py", line 190, in main
from spyder.app import mainwindow
File "C:\Anaconda\lib\site-packages\spyder\app\mainwindow.py", line 92, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\Anaconda\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name**


Any help in this matter would be much appreciated

**Comment by ccordoba12** [comment]
@ArunSha, this is most probably an installation issue. So my recommendation for you is to uninstall and reinstall Anaconda again.

**Comment by LA1824** [comment]
Nope @jayrawatrj

**Comment by jayrawatrj** [comment]
I have already tried but didn’t work

Sent from Mail for Windows 10

**Comment by ArunSha** [comment]
@ccordoba12  tried reinstalling anaconda, even tried older version. spyder just won't launch.

**Comment by ccordoba12** [comment]
@ArunSha, please open an Anaconda Prompt, run there

    conda install qt=5.6* pyqt=5.6* sip=4.18*

and try again.

**Comment by jayrawatrj** [comment]
Tried this method but still have the same issue

Sent from Mail for Windows 10

**Comment by ArunSha** [comment]
Okay I am a beginner in Machine Learning and this software is already taking out all the fun out of it. So my spyder was not working and i tried reinstalling. 


However now Anaconda Navigator doesnt launch. This is the error i get when I run it

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 22,
in <module>
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\Anaconda\lib\site-packages\anaconda_navigator\utils\__init__.py", lin
e 15, in <module>
    from qtpy.QtGui import QIcon
  File "C:\Anaconda\lib\site-packages\qtpy\QtGui.py", line 21, in <module>
    from PyQt5.QtGui import *
ImportError: DLL load failed: The specified procedure could not be found.

Could someone please help me figure out what is wrong ? Please

**Comment by ShmuelAmpofo** [comment]
spyder --reset  

Didn't work on my Linux

instead 
----------------------------------
uninstall and re insatlled spyder  in anaconda and  it works.

**Comment by inlee12** [comment]
spyder does not launch with anaconda navigator but launch when I use in command at terminal mode

(base) C:\Users\islee>spyder
Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
   QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
   QT_SCREEN_SCALE_FACTORS to set per-screen factors.
   QT_SCALE_FACTOR to set the application global scale factor.

**Comment by krimobe** [comment]
I have a similar issue. 
Windows 7 x84
4 GB Ram
CPU: Intel (R) Core i5 2.5GHz
Python 3.7.0
conda 4.5.11
Installer: Anaconda3-5.3.1-Windows-x86

![image](https://user-images.githubusercontent.com/6544368/48940962-d7e30380-ef19-11e8-8779-514be9032096.png)


I have tried reinstalling Anaconda several times. 
I have run spyder --reset. 
I have removed spyder.lock files/folders. 
I have downgraded the packages qt,sip,pyqt to qt-5.62,sip-4.18.1,pyqt-5.6.0
I have tried conda install -f zeromq pyzmq
I have tried changing the socket.py file in the zmq package 
From previous posts it seems that it might be my anti-virus, however I am working on a company computer which runs McAfee anti-virus which I do not have the possibility to disable.
So is there a work around? 

Kind regards
Kristian

**Comment by SarpJeet** [comment]
It took my whole night but unable to launch spyder through anaconda. It's bad experience.

**Comment by SHIVAMGUPTA24** [comment]
change pyqt5 file version might work

**Comment by cankadir** [comment]
Downgrading Spyder worked for me.

**Comment by thejipsess** [comment]
For me the issue was due to my keras installation as I installed the required keras-gpu packages before installing Spyder, to solve: create a fresh environment, install spyder and finally install keras as follows within the Anaconda Prompt:

1) _conda create -n environmentName_
2) _activate environmentName_
3) WITHIN THE ANACONDA NAVIGATOR: install spyder (I guess '_conda install -c anaconda spyder_' in the Prompt should work as well)
4) _conda install -c conda-forge keras-gpu_ (or if you don't have CUDA and want to use cpu for calculations use '_conda install -c conda-forge keras_' instead

I recommend testing the setup before adding additional packages and if adding them, ensure to close spyder and anaconda before doing so

**Comment by priyanka176** [comment]
> @ArunSha, please open an Anaconda Prompt, run there
> 
> ```
> conda install qt=5.6* pyqt=5.6* sip=4.18*
> ```
> and try again.

**Comment by Yasine001** [comment]
I had the same issue, but it worked for after reseting :
`spyder --reset`

**Comment by charanjitpabla** [comment]
Hello,

I am getting this message when opening spyder in linux terminal:

Spyder is already running. If you want to open a new 
instance, please pass to it the --new-instance option

What do I do to fix this?

**Comment by kouassives** [comment]
I have a similar issue:
double click
C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)\Reset Spyder Settings (memoire).lnk

**Comment by cecidip** [comment]
@ccordoba12 if i do spyder --reset it tells:
/Users/cecidip/anaconda3/bin/pythonw: line 3: /Users/cecidip/anaconda3/python.app/Contents/MacOS/python: No such file or directory
 ?? 
I  had spyder 3.3.5 and i did "conda update spyder" then i went to anaconda to launch, it didnt. But i had the option to update it.... even if i just did, so i did "update" but it actually downdated it back to 3.3.5 ... and still wont launch.

**Comment by ccordoba12** [comment]
@cecidip, please run

    conda install -f python.app

That should fix your problem.

**Comment by cecidip** [comment]
conda install -f python.app did it, thanks !

**Comment by dk-raghu** [comment]
## Experience installing Anaconda
* I did several trials of install and un-install Anaconda (I was just interested in launching Spyder) as a novice user of Python
* Browsed internet over and over again 
* Used "conda" and "pip" several times
* Finally I un-installed the anti-virus software on my Laptop
* Un-installed Anaconda and re-installed it again and then launced Spyder FINALLY !!!!
* Works now for me

**Comment by ccordoba12** [comment]
> Finally I un-installed the anti-virus software on my Laptop

This was (most probably) the critical step.

**Comment by Asgharzade** [comment]
> @ccordoba12 @jdweaver Thank you spyder --reset worked!
> 
> First reset your laptop/PC, after that open terminal and type `spyder --reset`

Thanks dude! I was about to lose my mind on this Spyder issue. You made my day!

**Comment by rafaeldoug** [comment]
_Start Menu/Anaconda*/Reset Spyder Settings_ can works.

**Comment by mharis0014** [comment]
> @ArunSha, please open an Anaconda Prompt, run there
> 
> ```
> conda install qt=5.6* pyqt=5.6* sip=4.18*
> ```
> 
> and try again.

My spyder was not launching. i uninstalled spyder tried this command on anaconda prompt and reinstalled spyder. Now spyder launches for 4-5 seconds and then ends. This is happening. please solve my problem i am a last year student and i have to do a lot of work on spyder

**Comment by Ashish2000M** [comment]
I am also facing this error

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 201, in main
    from spyder.app import mainwindow
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 52, in <module>
    requirements.check_qt()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt
    import qtpy
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by dssangan** [comment]
Uninstall following:
spyder, pyqt5, sip
Try installing the following:
latest spyder, sip
Pyqt5 < 5.13

and try pip install --upgrade jupyter_client
I was missing few imports and updating jupyter worked for me for latest spyder 4.1.4

**Comment by gohkokhan** [comment]
`pip install pyqtwebengine` this works for me

**Comment by vamsichaitanya1202** [comment]
> 
> 
> `pip install pyqtwebengine` this works for me

Yes this works for me too. Thank you.

**Comment by purang2** [comment]
> Could you run in a terminal
> 
> ```
> spyder --reset
> ```
> 
> and try again?

you genius.

**Comment by hbshrestha** [comment]
I tried `pip install PyQtWebEngine` followed by `pip install PyQt5==5.11.3`.
Finally, I was able to launch Spyder in my system.

**Comment by 4c656554** [comment]
I had this issue after copying a huge amount of text into the IPython console, so much so that I had to force close Spyder.

`E.g. [1]:  a = "<huge amount of .. text>"`

To fix I had to find the history.py and delete the `E.g. [1]:  a = "<huge amount of .. text>"` line.

On windows located: `C:/Users/<Username>/.spyder-py3/history.py`
