### ISSUE TITLE
Spyder frozen when using dype kwarg

### ISSUE THREAD

**Issue by Numlet** [spyder-ide/spyder#3139]
## Description of your problem
The whole of Spyder gets frozen when I run the following lines,
**What steps will reproduce the problem?**

1. import numpy as np
2. my_data=np.genfromtxt(path_to_my_file,delimiter="\t",skip_header=1,dtype='str')
3. 

**What is the expected output? What do you see instead?**

I should get an array with the values in the file. I get that output when running that code in Ipython by using the command line. However, when running it in Spyder, it gets frozen. 

**Please provide any additional information below**

In Spyder, If I do not include the **kwarg dtype='str' it reads the file and do not get frozen, so I think that it is the cause of the problem.

## Versions and main components

* Spyder Version:2.3.8.
* Python Version: Python 2.7.10 | 64-bit
* Operating system:CentOS release 6.7 (Final)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0   :  4.0.1 (OK)
matplotlib >=1.0:  1.5.1 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  3.3.0 (OK)
pyflakes >=0.5.0:  1.0.0 (OK)
pygments >=1.6  :  2.1 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  15.1.0 (OK)

**Comment by Nodd** [comment]
What is the size of the array you're trying to load ?
Is it still freezing if you close the variable explorer ?

**Comment by Numlet** [comment]
The shape is about (80,7) so the size will be around 600
I have just closed the variable explorer and now it is working. Thank you!
Is there any way of having the variable explorer opened and still run the code? I don't use the variable explorer much but it could be helpful.

**Comment by ccordoba12** [comment]
@Numlet, I think is that you're using a Numpy array with strings (I mean, your dtype is a str). But this problem was fixed in Spyder 2.3.9.

Could you upload a simple file to pass to `np.genfromtxt` to test things in our side?

**Comment by Nodd** [comment]
Disabling the automatic update for the variable explorer and update manually should work.
Or updating spyder, as @ccordobat said.

**Comment by Numlet** [comment]
[test_file.txt](https://github.com/spyder-ide/spyder/files/242168/test_file.txt)

Hi, 

Here is a test file with the same structure of the file that I am trying to upload. 
I am not currently using the variable explorer so the problem is solved for me, but I will let you know if everything is solved when I update spyder to 2.3.9.  

Thanks for your help!

**Comment by ccordoba12** [comment]
This was fixed in commit 3a52851, which is part of version **2.3.9**, so a simple update will fix this ;-)
