### ISSUE TITLE
Search for backslash (\) sign

### ISSUE THREAD

**Issue by Winand** [spyder-ide/spyder#3141]
WinPython-32bit-3.4.4.2

When searching for a line continuation sign (\) it disappears from the find textbox when I try to go to the _next_ result. Going _backwards_ works fine.

**Comment by Winand** [comment]
The problem is within this function:
```
#\widgets\comboboxes.py:114
def add_current_text(self):
	"""Add current text to combo box history (convenient method)"""
	text = self.currentText()
	if osp.isdir(text):
		if text[-1] == os.sep:
			text = text[:-1]
	self.add_text(text)
```

**Comment by ccordoba12** [comment]
Thanks for looking into this one. I'll try to fix it for Spyder 3.0 beta4 :-)

**Comment by Nodd** [comment]
I think we should completely remove the magic here, since it doesn't work in every case. If the user wants to search for a filename without a backslash at the end, he can remove it himself.

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.

**Comment by rlaverde** [comment]
Should all the "magic" be removed, or just add a condition to avoid removing "\" or "/"?
