### ISSUE TITLE
spyder fails when trying to do subplots with matplotlib

### ISSUE THREAD

**Issue by Alan-g-s** [spyder-ide/spyder#3142]
I tried to do a plot using annotated and verified python code from online, using matplotlib and the plot appears but none of the lines do, but when I run the code in Idle it works perfectly. I would expect a scientific development environment to be able to plot using matplotlib.

**What steps will reproduce the problem?**

1. download the following file:
[matplotlibbugtest.py.zip](https://github.com/spyder-ide/spyder/files/241042/matplotlibbugtest.py.zip)
2. open in spyder and use python 2.7 with matplotlib installled. 

**What is the expected output? What do you see instead?**
Run it, plot appears but with no data.
3.open and run in idle, it works. 

**Please provide any additional information below**

## Versions and main components

* Spyder Version:2.2.5
* Python Version:2.7
* Operating system:linux/ubuntu

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by Nodd** [comment]
You have an old version of spyder, this bug migth have been corrected in the last version. Try to update it and check if the problem persists.
