### ISSUE TITLE
Add checkboxes to PYTHONPATH manager to switch on/off paths

### ISSUE THREAD

**Issue by Winand** [spyder-ide/spyder#3143]
One should use `PYTHONPATH manager` instead of messing around with `sys.path` in Spyder, right?
Then could you enhance its functionality so I can switch on-off paths like this:
![image](https://cloud.githubusercontent.com/assets/53390/14910063/d416981c-0df2-11e6-8392-8ca4ad96b73f.png)
If I want to test the same code with different versions of the same library it's not very handy to completely remove an item from the list and then add it again

**Comment by ccordoba12** [comment]
Thanks for reporting. It's a good idea but unfortunately we don't have time to implement it.

**Comment by ccordoba12** [comment]
Sorry, as you noticed, this is a duplicate of issue #1105.
