### ISSUE TITLE
Auto completion does not work anymore

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3144]
## Description of your problem

**What steps will reproduce the problem?**

1.   After I import  import numpy as np
2.  np.   autocompletion does not work anymore
3. 

**What is the expected output? What do you see instead?**
nothing happens

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.5.2
* Python Version: 2.7
* Operating system: WIn7 64bits

## Dependencies
IPython >=1.0   :  3.2.1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please update to Spyder 2.3.9 and try again :-)

**Comment by ccordoba12** [comment]
Closing because of lack of response
