### ISSUE TITLE
Spyder doesn't work with Qt 5.6

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3145]
## Description of your problem

**What steps will reproduce the problem?**

1. pip install PyQt5.6 on Windows 7 64 / Python3.5 32 bit
2. instal spyder master from github
3. launch spyder

**What is the expected output? What do you see instead?**
spyder doesn't start well (but i see the initial splash screen).
Looking for a log of error but I don't find it

**Please provide any additional information below**
Did someone tried  this already ? Is it supposed to work ?

## Versions and main components

* Spyder Version:spyder-3.0.0.dev0 of April 29th
* Python Version: 3.5.1 32 bit 
* Operating system: Windows 7 64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by stonebig** [comment]
````
Traceback (most recent call last):
  File "winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 24, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\spyderlib\app\spyder.py", line 3128, in main
    mainwindow = run_spyder(app, options, args)
  File "winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\spyderlib\app\spyder.py", line 3014, in run_spyder
    main.setup()
  File "winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\spyderlib\app\spyder.py", line 838, in setup
    from spyderlib.plugins.help import Help
  File "winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\spyderlib\plugins\help.py", line 21, in <module>
    from qtpy.QtWebEngineWidgets import QWebEnginePage
  File "winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 28, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named 'PyQt5.QtWebKitWidgets'
````

**Comment by stonebig** [comment]
maybe the issue similar to this (and so PyQt5.6.0 issue ?): https://www.riverbankcomputing.com/pipermail/pyqt/2016-April/037406.html

**Comment by stonebig** [comment]
curoisluy, launching from python REPL, I get no error in QtPy, so line 28 should not be raised.
````
>>> from PyQt5.QtWebEngineWidgets import QWebEnginePage

>>> from PyQt5.QtWebEngineWidgets import QWebEngineView

>>> from PyQt5.QtWebEngineWidgets import QWebEngineSettings
````

**Comment by stonebig** [comment]
this may be the core issue:
````
ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created
````

**Comment by stonebig** [comment]
so, If I had a line "from qtpy.QtWebEngineWidgets import QWebEnginePage" in app/spyder.py line 91
````
#stonebig
from qtpy.QtWebEngineWidgets import QWebEnginePage
#==============================================================================
# Create our QApplication instance here because it's needed to render the
# splash screen created below
#==============================================================================
from spyderlib.utils.qthelpers import qapplication
MAIN_APP = qapplication()
````

I get further

**Comment by jitseniesen** [comment]
Issue #3073 is also about QtWebKitWidgets (but on a Mac); the solution there was to downgrade qt5 to version 5.5.

**Comment by stonebig** [comment]
that is not an option for me, as on Windows + Python3.5, I got only PyQt5.6.0.

**Comment by stonebig** [comment]
I feel bad reading https://wiki.qt.io/Porting_from_QtWebKit_to_QtWebEngine.

Fix seems not so simple

**Comment by stonebig** [comment]
I can comment with a "#":
- the 2 lines of "setLinkDelegationPolicy" and "ClickedLink" in plugin/help.py (line  481)
- the 1 line of "ClickedLink" in widgets/browser.py (line 263) but spyder do something then stop.

**Comment by stonebig** [comment]
File "D:\WinPython\basedir35\buildQt5\winpython-32bit-3.5.x.4\python-3.5.1\lib\site-packages\spyderlib\utils\qthelpers.py", line 242, in create_action
    action.triggered.connect(triggered)
TypeError: decorated slot has no signature compatible with triggered(bool)

**Comment by ccordoba12** [comment]
A pull request is coming to fix several problems we're having with Qt 5.6. They will be fixed for Spyder 3.0 beta3 :-)

**Comment by Nodd** [comment]
Heh, I just upgraded my system, and :bomb: ! Any news ?

**Comment by ccordoba12** [comment]
A PR is coming :-)

**Comment by davidovitch** [comment]
You can work around it by compiling PyQt 5.5.1 (I have the entire Qt 5.6 family installed system wide) and installing it in a virtual environment (downgrading my system Qt installation is too complex). On the bright side: now I know how to install multiple versions of PyQt in different virtualenvs :-)

 I've looked here for inspiration:
* https://www.metachris.com/2016/03/how-to-install-qt56-pyqt5-virtualenv-python3/
* http://stackoverflow.com/questions/1961997/is-it-possible-to-add-pyqt4-pyside-packages-on-a-virtualenv-sandbox
* http://stackoverflow.com/questions/19856927/how-to-install-sip-and-pyqt-on-a-virtual-environment
* https://github.com/pypa/pip/issues/579

**Comment by stonebig** [comment]
ok
