### ISSUE TITLE
Spyder is freezing in OSX

### ISSUE THREAD

**Issue by lxkain** [spyder-ide/spyder#3148]
## Description of your problem

**What steps will reproduce the problem?**

0. for the beta, "git pull" (May 2, 2016)
1. start spyder via "python bootstrap"
2. let it sit idle for more than 2 minutes but less than one hour

**What is the expected output? What do you see instead?**
Expected: Continue working
Instead: it locks up (beach ball)

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0dev
* Python Version: 3.4
* Operating system: OSX 10.11.4

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by lxkain** [comment]
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.18.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.2.0 (OK)
pyflakes >=0.6.0:  1.1.0 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.4.1 (OK)
sympy >=0.7.3   :  1.0 (OK)

(I pulled the latest sources again today)

**Comment by ccordoba12** [comment]
Are you using Qt4 or Qt5?

**Comment by lxkain** [comment]
Qt4 through anaconda, thank you!

**Comment by ccordoba12** [comment]
This should be solved once we move to Qt5 with Anaconda 4.1. Thanks for your patience :-)

**Comment by ccordoba12** [comment]
Anaconda 4.1 will be released at the end of the month.
