### ISSUE TITLE
Error after typing open paren "(" in editor

### ISSUE THREAD

**Issue by rlow0** [spyder-ide/spyder#3149]
## Description of your problem

Spyder displays an error when I type an open paren "(" in the editor

**What steps will reproduce the problem?**
1. Activate "display balloon tips" option in the editor preferences.
2. Type an open paren in the editor "("

**What is the expected output? What do you see instead?**
Spyder activates the internal console and displays this error message:

``` python
Traceback (most recent call last):
  File "~/anaconda/lib/python3.5/site-packages/spyderlib/utils/introspection/plugin_manager.py", line 356, in _introspection_complete
    self._handle_pending()
  File "~/anaconda/lib/python3.5/site-packages/spyderlib/utils/introspection/plugin_manager.py", line 312, in _handle_pending
    self._post_message('')
  File "~/anaconda/lib/python3.5/site-packages/spyderlib/utils/introspection/plugin_manager.py", line 432, in _post_message
    statusbar = self.editor_widget.window().statusBar()
AttributeError: 'SpyderDockWidget' object has no attribute 'statusBar'
```
## Versions and main components
- Spyder Version: 2.3.8
- Python Version: 3.5.1
- Operating system: OS X 10.10.4
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
```

**Comment by ccordoba12** [comment]
Could you post what you were trying to complete when this error appeared?

**Comment by rlow0** [comment]
It actually happens after typing any open paren in the editor. It can follow any text. Doesn't matter if it's a valid completion (e.g. "print") or not (e.g. "fffff"). Can even be on a blank line by itself.

I also see the same error after typing a period ".". In this case, it only happens when the period follows an invalid completion. E.g. error typing "x." if `x` hasn't been defined. No error if it has. Or error on "import foo." if there's no module `foo`. No error on "import theano.", which exists. Whereas the open paren error depended on the 'display balloon tips' setting being true, the error when typing a period seems to depend on the 'automatic code completion' setting being true.

I also see the same error when typing a tab following other text. E.g. typing "pri" followed by a tab autocompletes to "print" and generates the error. Also happens when pressing tab after statements that have no valid autocompletion, e.g. "ffff". The tab error seems to happen independently of any editor settings. The editor autocompletes and generates an error both happen even if I turn autocompletion off.

**Comment by immersinn** [comment]
I see this issue as well when the editor pane is separated from the main spyder application window.

**Comment by ccordoba12** [comment]
Thanks @immersinn, that's good to know. @dalthviz, could you work on this one, please?

**Comment by dalthviz** [comment]
Hi everyone. I followed the steps, in the current version of Spyder (`3.0.1`), and no error message appears. I suggest you to update Spyder to the current version. If you are using Anaconda, you can use the command `conda update spyder` or if you are using pip you can use `pip install -U spyder`. Also is important to take into account that the version `2.3.8` isn´t in maintainance, so it won´t recive more updates.

Additionally is important to know that for the proper function of the editor separated of the main Spyder application window, you have to select the gear in the right-top corner of the editor and then select the option `New window`:

![newwindow](https://cloud.githubusercontent.com/assets/16781833/20311902/84d9504e-ab1f-11e6-91d5-f764a803e075.png)

**Comment by ccordoba12** [comment]
Please follow @dalthviz advice :-)
