### ISSUE TITLE
Spyder can't save/import numpy array within dictionary

### ISSUE THREAD

**Issue by wagne134** [spyder-ide/spyder#3152]
It appears numpy is unable to save/import any data set with a dictionary that contains a numpy array.

**What steps will reproduce the problem?**
1. import numpy
2. define a dictionary that contains a numpy array
3. hit the "Save data as..." button and save your data
4. import the data

**What is the expected output? What do you see instead?**
You should see the dictionary you defined, but instead nothing is imported.  If you look at the original data immediately after saving, you'll also notice that the dictionary containing the array is now empty.

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 
- Python Version: 2.7
- Operating system: Windows 7
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
Can you please be a bit more specific? How do you define the dictionary? Which format are you saving the data as? Also, what is your Spyder version?

**Comment by ccordoba12** [comment]
Most probably a numpy array inside a dictionary is not pickable. But we'll see what we can do for a future version :-)

**Comment by goanpeca** [comment]
```python

import numpy as np
arr = np.array([1,2,4])
dic = {'test': arr}
```

I tried with this and it works
