### ISSUE TITLE
Is there multiple line dedent shortcut?

### ISSUE THREAD

**Issue by Kiminaka** [spyder-ide/spyder#3153]
I tried to find it but I can't really find it.. 

Thanks!

**Comment by goanpeca** [comment]
Hi @Kiminaka,

What do you mean exactly?

**Comment by Nodd** [comment]
Maybe what you look for is select the lines and press shift+tab ?

**Comment by ccordoba12** [comment]
Yes, `Shift+Tab` is dedent shortcut in Spyder :-)
