### ISSUE TITLE
additional clipboard pastes found in random locations

### ISSUE THREAD

**Issue by rshpeley** [spyder-ide/spyder#3158]
## Description of your problem

**What steps will reproduce the problem?**
1. occurs randomly but the trigger seems to happen after I copy a code segment from the editor pane and paste it to the python console
2. afterwards it occurs also for cut/pastes within the editor pane, but I can't guarantee that it always occurs afterwards
3. does not seem to occur for multiline cut/pastes

**What is the expected output? What do you see instead?**
I get the pasted text where expected (in the console or the editor), and also sometimes get multiple (one or more) copies pasted randomly in the current document.

**Please provide any additional information below**
I'm using both python 2.7.11 and 3.4.4, but up till now have only noticed the behaviour in 2.7.11.
## Versions and main components

Managed by conda in two environments for the two python versions. Both environments are quite large -- around 90 packages.
- Spyder Version: 3.0.0b2
- Python Version: 2.7.11/ 3.4.4
- Operating system: mint 17.3
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

2.7.11
IPython >=3.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.5.1 (OK)
numpy >=1.7        :  1.10.4 (OK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.4       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=13.0.0       :  15.2.0 (OK)

3.4.4
IPython >=3.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.5.1 (OK)
numpy >=1.7        :  1.10.4 (OK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=13.0.0       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Could you post a video showing the problem? I'm not sure I'm understading correctly what's happening in your case. Thanks :-)

**Comment by rshpeley** [comment]
Hi Carlos,

This issue was happening on a gpu workstation in our university lab and I won't be back there for a few days. Since this problem occurs only occasionally I may not be able to capture it on video. I can however at this moment clarify the problem more. 

The problem occurs in both python 2 and 3.

On further use there appears to be no sequence between the python console or editor pane of any significance. The errant pastes just occur randomly (in position and time) in the edited document. I'll do some tests to see if I can confirm that pasting text into a python terminal causes that text to be pasted randomly into the editor. I can confirm that pasting text in the editor does occasionally cause random pastes in the same edited document.

I may have noticed the same issue in the RStudio editor, but haven't been able to confirm it. I'm installing a similar environment on my home computer now and will see if I can replicate the problem.

I would suspect an errant keyboard or keyboard driver, but the errant pastes occur at random positions in the document. Those pastes would have to occur at the current cursor position if it were a low level (keyboard or driver) problem.

btw, I'm thoroughly enjoying spyder. It's a great bit of code...

**Comment by buzjwa** [comment]
This is happening to me too. I though I was getting sloppy until I realized this happens only in Spyder. 

## Version and main components

* Spyder Version: 2.3.9 
* Python Version: 2.7.6
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Linux

## Optional dependencies
```
IPython >=1.0      :  5.0.0 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.3.1 (OK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.4.6 (OK)
psutil >=0.3       :  1.2.1 (OK)
pyflakes >=0.5.0   :  0.8.1 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  1.1.0 (OK)
qtconsole >=4.0    :  None (NOK)
rope >=0.9.2       :  0.9.2 (OK)
sphinx >=0.6.6     :  1.2.2 (OK)
zmq >=2.1.11       :  14.0.1 (OK)

```

**Comment by ccordoba12** [comment]
Please use Spyder 3 with PyQt5 and try again. Closing for now.
