### ISSUE TITLE
Disambiguate Editor tabs

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#3160]
## Description of Feature Request

When I'm editing a django project I often find that I'm editing similar named files in multiple apps. Although spyder's editor tells me which file I'm editing - models.py, views.py, it gets a bit confusing to see which app each models.py or views.py (etc) tab belongs too.

It would be nice if there was an option that when two files of the same name, but different paths were opened, spyder would add sufficient levels of directory to disambiguate the two files in the tab label - possibly using ellipses to show only the unique part and file name - e.g.

appA/models.py | appB/models.py | appA...index.html | appB...index.html 

Probably this should be dynamic in the sense that opening or closing one of te tabs would cause all the tabs to adjust their appearance.

**Comment by ccordoba12** [comment]
I'll fix this one for Spyder 3.0 beta4. I already have some code on how to do it :-)

**Comment by ccordoba12** [comment]
@dalthviz, I'll tell how to work on this one in our meeting :-)
