### ISSUE TITLE
Cannot open preferences when a file named "new.py" is in the working folder

### ISSUE THREAD

**Issue by goyou** [spyder-ide/spyder#3164]
## Description of your problem

**What steps will reproduce the problem?**

1. Create a python script and name it new.py
2. Click on tools->preferences

**What is the expected output? What do you see instead?**
I expect the preferences dialog to appear, instead are coming tracebacks in the internal consoles linked to the new.py file.

## Versions and main components

* Spyder Version: 2.2.5
* Python Version: 2.7.6
* Operating system: Linux

**Comment by mariacamilaremolinagutierrez** [comment]
I was not able to reproduce this error in the latest version of spyder:

![image](https://cloud.githubusercontent.com/assets/3608776/19634861/d0d6d492-9983-11e6-966a-15e6b863dad8.png)

I was able to open the preferences window. 

@ccordoba12 I think this one should be closed.

**Comment by ccordoba12** [comment]
Thanks @mariacamilaremolinagutierrez :-)
