### ISSUE TITLE
IPython Console doesn't work after kernel restart

### ISSUE THREAD

**Issue by chrisjsewell** [spyder-ide/spyder#3169]
## Description

After restarting the kernel of the IPython Console, attempting to run code no longer works, since pressing the Return key opens a new line of the same cell rather than running the code (i.e. as if you were pressing ctrl+Return).

**What steps will reproduce the problem?**

1. Open IPython Console
2. Select 'Restart kernel'
3. Enter code in first cell and press return key

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.9 
* Python Version: 2.7.11
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
IPython >=1.0      :  4.2.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
pandas >=0.13.1    :  0.16.2 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
psutil >=0.3       :  4.1.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  None (NOK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. Your problem was reported before in issue #2696, so I'm closing this one :-)

**Comment by chrisjsewell** [comment]
cheers
