### ISSUE TITLE
issue with shortcuts

### ISSUE THREAD

**Issue by peendebak** [spyder-ide/spyder#3175]
If I go to Tools->Preferences I get an error that is triggered by `assert key in self.Keys` from `shortcuts.py` (this is spyder 2.3.9, for current master I cannot find the same line, but the same issue might be there, see below). The problem is a key that has the string representation `Shift+Alt+PgUp`.

In  [`shortcuts.py` line 45] (https://github.com/spyder-ide/spyder/blob/master/spyderlib/plugins/shortcuts.py#L45) the keystrings are defined, but `PgUp` is not one of them. There is a key named `PageUp` though.
In the Spyder code the key `PgUp` is also used (see [`main.py`](https://github.com/spyder-ide/spyder/blob/ef38c3837b4a08ee26435efff4d180e762f0cc00/spyderlib/config/main.py#L315).

Should we use `PgUp` or `PageUp`? In either case, it might be good to make the code reading the keys from the configuration more robust and emit a warning instead of generating an error.

**Comment by Nodd** [comment]
:+1: for a warning instead of an error.

PgUp may depend on the platform. Which one do you use ?

**Comment by peendebak** [comment]
Python 3.5.1 64 bits, on Windows

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Shortcuts are going to be introduced in a different (and much simpler) way for Spyder 3.0, so we don't plan to fix this one for Spyder 2.3.9.

Please reopen this issue if it's not fixed after we release 3.0 (in about a month :-)
