### ISSUE TITLE
Editor tabs height bloated in OS X (2.3.7 -> 2.3.8)

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3179]
There is a curious artifact that crept into the `2.3.8` dmg version of Spyder, the size of the tabs for files being edited became much larger. This is true on both `OS X 10.10` and `OS X 10.11` versions.

Spyder 2.3.7:
![160524_spyder2p3p7](https://cloud.githubusercontent.com/assets/3229632/15524668/4725970a-21d9-11e6-8056-00c9296ed5b6.png)
Spyder 2.3.8:
![160524_spyder2p3p8](https://cloud.githubusercontent.com/assets/3229632/15524672/4d5716c6-21d9-11e6-8333-15511a20cddd.png)

It'd be great if these extra pixels can be found and reclaimed in the active editor window.

**Comment by ccordoba12** [comment]
I really don't know how to fix this, but I understand it's annoying.

**Comment by durack1** [comment]
@ccordoba12 I wonder whether `2.3.9` could have a DMG created and I'll report whether it is still an issue in the latest release - I did create an existing issue for this #3172

**Comment by ccordoba12** [comment]
I noticed your other issue. I'll respond about it there :-)

**Comment by jnsebgosselin** [comment]
@goanpeca is this issue still relevant?

**Comment by goanpeca** [comment]
Let me check

**Comment by goanpeca** [comment]
@jnsebgosselin I think this issue is no longer relevant

<img width="265" alt="Screen Shot 2019-06-26 at 17 14 49" src="https://user-images.githubusercontent.com/3627835/60218767-f0135c00-9835-11e9-977f-b061ad100702.png">

Should we close it @ccordoba12 ?

**Comment by durack1** [comment]
@jnsebgosselin @ccordoba12 @goanpeca I have the following on Spyder 3.3.3 on MacOS 10.14.5, so yep, I think it's good to close
![Screen Shot 2019-06-26 at 4 07 36 PM](https://user-images.githubusercontent.com/3229632/60220955-a2debc80-982c-11e9-9193-a0ca02c6715d.png)

**Comment by jnsebgosselin** [comment]
Awesome, thank you for checking @durack1 !
