### ISSUE TITLE
plain/rich  text font take no effect

### ISSUE THREAD

**Issue by sunshe35** [spyder-ide/spyder#3180]
when i use **spyder 3.0.0dev**, and make configuration through 
 **" tools - preferences - general - appearance  - fonts"**   and have make a change of **both plain text fonts** and **rich text fonts** through the **size**  opthion , but I see no change.

**Comment by ccordoba12** [comment]
Please update your Spyder git clone (or pip installation). This was fixed some weeks ago :-)
