### ISSUE TITLE
Show signature to the right of the completion widget

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3181]
From #2980.
This is what it looks like in IntelliJ:
![image](https://cloud.githubusercontent.com/assets/18707623/15240191/d67a5996-1922-11e6-92af-b68e17a2c4d1.png)

**Comment by ccordoba12** [comment]
This is not doable as shown here but as it's done in RStudio: the calltip widget (which is in charge of rendering signatures) can be shown next to the completion widget, for the select entry on it :-)

It shouldn't be that hard to implement :-)

**Comment by Nodd** [comment]
Having a tooltip only makes it harder to select the correct function, because you'd have to select each entry and wait for the tooltip. Even if the tooltip is instantaneous, it doesn't give an overview of all the possible calls. Signature-wise, it's as if the completion tooltip displayed one line at a time.
Why is it not doable ? We can get the information for the tooltip anyway, so why not in the completion list ?

**Comment by ccordoba12** [comment]
@dalthviz, this is a clearer image from RStudio:

![Selección_007](https://user-images.githubusercontent.com/365293/61937205-9dd96e00-af8e-11e9-913c-8ddcfcaa05e5.png)

The idea is that after selecting an entry in the completion widget, we should show its calltip to the right, with its signature and the first line of its docstring (if the info is available, of course).
