### ISSUE TITLE
Add signature on autocompletion

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3182]
From #2980.

> np.histog + Select histogram2d in pop list + Alt
> --> Write down in editor: histogram2d(x, y, bins=10, range=None, normed=False, weights=None)

Note that adding an open parenthesis for methods automatically was rejected (https://github.com/spyder-ide/spyder/issues/680#issuecomment-129665894), but maybe it would fine with a modifier ?

**Comment by ccordoba12** [comment]
This depends on solving issue #3180 first.

After that we can make that a left mouse click over the calltip widget automatically writes the signature on the Editor.

**Comment by goanpeca** [comment]
Is this something we still want to provide @ccordoba12 ?

<img width="492" alt="Screen Shot 2019-11-25 at 14 00 17" src="https://user-images.githubusercontent.com/3627835/69569589-f3994380-0f8b-11ea-8891-30baec3e87ca.png">
