### ISSUE TITLE
Show documentation for entries in the Edito completion widget automatically in the Help plugin

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3184]
From #2980.

> 1) np.histog + Select histogram2d in pop list + space
> --> Switch automatically the Right Side panel to Object inspector
> + show the following info about np.histogram2d
> + Pop list is maintained
> BUT "histogram2d " is NOT written in the Editor
> ---> Allow to investigate function by using pop up by staying in the editor

I think using space for this will interfere with normal typing (see discussion in the original issue). After thinking a bit about this I think that a shorcut is no even necessary, the help widget could display the highlighted entry automatically as long as it's done asynchronously.

**Comment by ccordoba12** [comment]
@Nodd, things are done asynchronously already (using threads), so there's no problem with that :-)

We could add an option to do this but I don't agree with it to be on by default. I've seen other IDEs doing it (like Wing IDE or IEP) and find it very annoying.

**Comment by ccordoba12** [comment]
Closing because I don't think this is worth it.
