### ISSUE TITLE
"New -> Module..." menu not saving the new module file to the disk

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#3186]
## Description

**What steps will reproduce the problem?**

1. In the Project explorer or File explorer, right click to pop up the context menu, and then select menu "New -> Module...". 
2. The "New module" dialog shows up for the user to input the module file name, say "a.py". After clicking the Save button on the dialog, the module file "a.py" is not saved to the disk. Also, in the Editor, a new tab is opened for the new module with the default name "untitled0.py", rather than "a.py".
3. If you edit and try to save the new module, the "Save file" dialog pops up and requires to input the module name again.

**What is the expected output? What do you see instead?**

I would expect that the new module to be saved to the disk, and the Editor shows the new module with the correct name.

**Please provide any additional information below**

It seems this problem exists for other versions of Spyder as well.

## Version and main components

* Spyder Version: 3.0.0dev 
* Python Version: 2.7.11
* Qt Versions: 5.5.1, PyQt5 5.5.1 on Darwin

## Dependencies
```
pyflakes >=0.5.0:  1.0.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
numpy >=1.7     :  1.11.0 (OK)
sphinx >=0.6.6  :  1.3.3 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
psutil >=0.3    :  3.4.2 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  1.5.2 (OK)

```

**Comment by Nodd** [comment]
Thanks for the reports.
Please note that the status of Projects in spyder is a bit chaotic, we planned to remake it for 3.0 but it looks like it won't be ready.
