### ISSUE TITLE
Spyder refuses to save an empty file from the template

### ISSUE THREAD

**Issue by ShenggaoZhu** [spyder-ide/spyder#3189]
## Description

**What steps will reproduce the problem?**

1. Select the main menu "File -> New file..." to create a new file/module. The new file is based on the template and is almost empty.
2. Without editing the new file, the main menu "File -> Save" is found to be disabled, and I can not directly save the file by the shortcut "Ctrl + S".
3. If I do want to save this empty file (e.g., an empty \_\_init\_\_.py), I have to go through the menu "File -> Save as...", or edit the new file first (adding a space is enough...).

**What is the expected output? What do you see instead?**

I think I can understand Spyder's current behavior, but it's not very intuitive to me, and it's different from most text editors. I would expect Spyder to allow saving an empty new file directly.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0dev 
* Python Version: 2.7.11
* Qt Versions: 5.5.1, PyQt5 5.5.1 on Darwin

## Dependencies
```
pyflakes >=0.5.0:  1.0.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1 (OK)
qtconsole >=4.0 :  4.1.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
numpy >=1.7     :  1.11.0 (OK)
sphinx >=0.6.6  :  1.3.3 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
psutil >=0.3    :  3.4.2 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
pylint >=0.25   :  1.5.2 (OK)

```

**Comment by Nodd** [comment]
This was a fix for when you create a new file and close spyder or run a script with autosave activated, it asks if you want to save the new file even if nothing was modified. So an annoying behaviour was replaced by another annoying behaviour, arguably less annoying.
A more optimal fix would be to add a flag to mark if a file was created from a template and not modified, and check it on autosave and save before closing.

**Comment by ccordoba12** [comment]
@ShenggaoZhu, the only thing you need to do save a new file is to modify it somehow (e.g. by introducing a blank space and then removing it).

I don't think we're going to fix this one, unless you want to submit a PR to do it :-)

**Comment by ShenggaoZhu** [comment]
Thank you @Nodd @ccordoba12 for the explanation! I understand the situation now. 

The current behavior is not that annoying, so it's not a big issue. I will try to submit a PR for this later (when I find the time...) Meanwhile, maybe you can close this issue now so as to keep the issues area clean?
