### ISSUE TITLE
Spyder freezes when trying to print to file large arrays

### ISSUE THREAD

**Issue by vzocca** [spyder-ide/spyder#3194]
## Description of your problem

**What steps will reproduce the problem?**

I am running Keras and trying to print out the weights of the neural net layers. When the array is very large (about 3-4MB file) spyder freezes.

You could use the model from this example: https://github.com/fchollet/keras/blob/master/examples/cifar10_cnn.py
(cut down the epochs to 1, or it will run forever)

I am printing the files in this way (you can use either print >> f1, or f1.write, both will have problems). model is the keras model. If I do not use numpy.set_printoptions(threshold='nan') then I have no problem (but it will truncate my output)

```
index = 0
numpy.set_printoptions(threshold='nan')
for layer in model.layers:
  filename = "conv_layer_" + str(index)
  f1 = open(filename, 'w+')
  f1.write(repr(layer.get_weights()))
  #print >> f1, repr(layer.get_weights())
  f1.close()
  print filename + " has been opened and closed"
  index = index+1
```

I ran it with the console option and got this error:

> > > /Applications/Anaconda/anaconda/lib/python2.7/site-packages/nbformat/current.py:19: UserWarning: nbformat.current is deprecated.
- use nbformat for read/write/validate public API
- use nbformat.vX directly to composing notebooks of a particular version
  
  """)
  Traceback (most recent call last):
  File "/Applications/Anaconda/anaconda/lib/python2.7/site-packages/spyderlib/widgets/ipython.py", line 668, in auto_refresh_namespacebrowser
    self.namespacebrowser.refresh_table()
  File "/Applications/Anaconda/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/namespacebrowser.py", line 326, in refresh_table
    communicate(sock, "refresh()")
  File "/Applications/Anaconda/anaconda/lib/python2.7/site-packages/spyderlib/utils/bsdsocket.py", line 107, in communicate
    return read_packet(sock)
  File "/Applications/Anaconda/anaconda/lib/python2.7/site-packages/spyderlib/utils/bsdsocket.py", line 74, in read_packet
    SZ, socket.MSG_WAITALL)
  File "/Applications/Anaconda/anaconda/lib/python2.7/site-packages/spyderlib/utils/bsdsocket.py", line 31, in temp_fail_retry
    return fun(*args)
  KeyboardInterrupt
## Versions and main components
- Spyder Version: 2.3.8
- Python Version: 2.7
- Operating system: MacOS
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.0.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.3.0 (OK)
pyflakes >=0.5.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  14.7.0 (OK)

**Comment by Nodd** [comment]
Try to disable the variable explorer.
Also could you give some minimal code to reproduce this error ?

**Comment by vzocca** [comment]
I edited my comment to show how to replicate it.

**Comment by vzocca** [comment]
UPDATE: Closing the variable explorer window did the trick, it is not freezing anymore.

**Comment by Nodd** [comment]
There is clearly a problem with the variable explorer. This issue is a recurring one.

**Comment by goanpeca** [comment]
I think this has been solved already @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, this problem only applied to the old Python console.
