### ISSUE TITLE
Test stand alone widgets in application

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3195]
Move/copy adapt all tests or stand alone widgets to a separate tests folder using pytest-qt.

**Comment by Nodd** [comment]
We should still keep `if __name__ == "__main__":` parts, that's useful for debugging or developing.
But for automated testing I agree that pytest is way better.

**Comment by goanpeca** [comment]
@Nodd yes, they should stay, :-)

**Comment by Nodd** [comment]
Ah no, I forgot to test it. You and your shiny new toys ! :smile:

**Comment by goanpeca** [comment]
Yes its empty :-p haha, dude I am trying to bring everything I am learning (and I have found valuable) into the project :-p. 

Yapf is coming soon, get ready

**Comment by Nodd** [comment]
We still didn't homogenize the whitespaces and you want to use Yapf ? Run, you fools !
More seriousely, last time I tried yapf my impression was that some modifications were good pep8 wise but hindered lisibility. I think that "A Foolish Consistency is the Hobgoblin of Little Minds" applies here.

**Comment by goanpeca** [comment]
the idea of yapf is dont waste time worrying about style but use a tool thta does this and keeps the style consistent across the codebase. At the end is about being efficient with the littke time we have and is also about helping contributors.

**Comment by ccordoba12** [comment]
@dalthviz, please start to work on this one for 3.1.4. This will increase our coverage and also allow Linux distros (e.g. Debian) to run our simple widget tests in their servers.

Later we can start adding more complete tests for each widget :-)
