### ISSUE TITLE
PyQt5 is not recognized by spyder but can be imported from the terminal

### ISSUE THREAD

**Issue by ilayn** [spyder-ide/spyder#3199]
## Description of your problem

**What steps will reproduce the problem?**

1. Either from the apt `python3-pyqt{4,5}`or via `pip` or via building from source PyQt4/5 is installed. 
2. Then via `sudo pip3 install spyder`, spyder is installed (currently 2.3.9 is fetched)
3. `spyder3` command is entered but instead requirements are not satisfied exception is raised.

**What is the expected output? What do you see instead?**

I'm having some confusion about which platform of QT is required and where Spyder looks at for PySide or PyQt. I've basically tried the apt versions and building both versions 4 and 5. But somehow none of them makes the spyder recognize pyqt. Here is an example exception generated by Spyder initialization and proof that Python recognizes PyQt5. 

![zzz](https://cloud.githubusercontent.com/assets/1303842/15779861/1d79c156-299f-11e6-95dc-9cadd356e5d3.png)

**Please provide any additional information below**
Despite the error message that says PyQt4 is needed, the reason I've switched to ..qt5 is that I've read on a post that [PySide support is dropped and officialy pyqt5 is supported](https://groups.google.com/forum/#!topic/spyderlib/s2L5NHSkm68) (though I'm ready to accept that I might have misunderstood the whole point) However, version 4 trials ended up in the same result anyways. 

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 3.5.1
* Operating system: Linux Mint 17.3 XFCE
* QT Version : 5.6 (but didn't work with older versions too hence I've switched everything to the newest)
* PyQt5 Version : 5.2.1

The path to PyQt5 is 

    /usr/lib/python3/dist-packages/PyQt5/

## Dependencies
N/A

**Comment by ccordoba12** [comment]
You need to install Spyder with

    pip install --pre -U spyder

to use it with PyQt5. Our stable version (2.3.9) only supports PyQt4 and PySide.

**Comment by ilayn** [comment]
Ah that's great to know. Now I got 3.0.0b2, it still doesn't work as the screenshot below but at least version-wise it is clear. 

![zzz](https://cloud.githubusercontent.com/assets/1303842/15798485/8b6cc64a-2a3a-11e6-87e5-54a813bd9794.png)

Speaking of which, thanks a lot for your efforts for bringing spyder to us!
