### ISSUE TITLE
cannot run spyder /  ImportError: No module named QtWebKit

### ISSUE THREAD

**Issue by benyaminpy** [spyder-ide/spyder#3200]
hey everyone.
i installed spyder about 6 month ago from APT-GET ,  and during 6 month it worked perfectly.
today i tried to run it and resume , but it not start's!

i tried to run spyder from terminal , but it seems missed the Qtwebkit module , 
**it show's a pop up contain this text=>**

**""""**
Spyder crashed during last session.
If Spyder does not start at all and before submitting a bug report, please try to reset settings to defaults by running Spyder with the command line option '--reset':
python spyder --reset
Warning: this command will remove all your Spyder configuration files located in '/home/MyUserName/.spyder2').
If restoring the default settings does not help, please take the time to search for known bugs or discussions matching your situation before eventually creating a new issue here. Your feedback will always be greatly appreciated.
**""""**
**after that i tried to install pyqtwebkit libraries and i do install all of that libs!
but it's still dead!

also it show's this , in the terminal=>**
**"""**
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2346, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 2234, in run_spyder
    main.setup()
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 773, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python2.7/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/findreplace.py", line 261, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python2.7/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named QtWebKit
**"""**

i installed all qtwebkit libraries.
i have to going to crazy :|
anyone had same problem?  or have any solution?

*** Spyder Version: 2 and 3
* Python Version: 2.7 / 3.4.3
* Operating system: Debian Kali GNU Linux 32**

**Comment by ccordoba12** [comment]
This is a Debian problem. They removed the QtWebKit module because it's insecure. You should try to update Spyder to a new version using your package manager to see if Debian developers have fixed this problem by patching Spyder.

If there's no new version, please open a bug in Debian bug tracker because (unfortunately) there 's nothing we can do about this one, sorry :-(

**Comment by benyaminpy** [comment]
aaah. ok
i really hate other python ide's :(
i'll miss spyder.
thank you for replay

**Comment by jitseniesen** [comment]
This has already been reported to the Debian bug tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826042 . Perhaps you can get spyder back by downgrading python-qt4: go to http://snapshot.debian.org/package/python-qt4/4.11.4%2Bdfsg-1/#python-qt4_4.11.4:2b:dfsg-1 , download the package for your computer and install it (this worked for me for another program that needs webkit). The alternative is to install Spyder outside the Debian system.

**Comment by manns** [comment]
@ccordoba12: I would appreciate if spyder stayed in the Debian repositories because it is my favorite Python IDE. Even if you cannot do anything about it, I would appreciate if you elaborated a bit on the state of things. 

Looking at the tracker, I found issue #2421, in which @nodd commented over a year ago that spyder qt5 support "should be ready for the next debian version". Has such a qt5 compatible version been released so that it can be packaged? If no does the master branch run stable with qt5 or is there any release that can run without webkit?

**Comment by ccordoba12** [comment]
> Has such a qt5 compatible version been released so that it can be packaged?

Spyder 3.0 beta3 is the latest released (but unstable) version that is compatible with Qt5.

> If no does the master branch run stable with qt5

Master runs with Qt5 without problems. It still has some issues though, but it works fine for most things :-)

**Comment by bulak** [comment]
Use 3.0.0 with Qt5. It works.

**Comment by Johnnyboycurtis** [comment]
I found a fix for Python 2 on Ubuntu using `sudo apt-get install python-pyqt`

**Comment by manns** [comment]
Yes, the issue seems to be fixed now. 
Spyder is usable again on Debian unstable.

**Comment by endolith** [comment]
@Johnnyboycurtis That didn't work for me on Ubuntu with Python 3.

```
~> spyder3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python3/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python3/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named 'PyQt4.QtWebKit'
```

**Comment by ccordoba12** [comment]
@endolith, it doesn't work on Ubuntu 16.10.

Please use Anaconda for now. Spyder 3.1 or 3.0.2 will be available in Ubuntu 17.04 for sure.

**Comment by Johnnyboycurtis** [comment]
What I've done in the past for Python 2/3 is install Spyder 2, then upgrading the Spyder library through pip, such as sudo pip install spyder --upgrade. I'm not an Anaconda person so installing libraries as needed is usually my process on all the machines I work on.

**Comment by ccordoba12** [comment]
> I don't use Anaconda

That's fine, and we're forcing you guys to use Anaconda. But we have to give some advice if your Linux distribution intentionally breaks Spyder.
