### ISSUE TITLE
making WebEngine part of PyQt5.6.0 wheel work

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3202]
As stated here https://github.com/spyder-ide/spyder/pull/3198#issuecomment-223792597 , PyQt5.6 is now supported but the WebEngine part, the help windows, doesn't, because of malformed wheel.

Question:
- what files should be moved manually to get it working ?

**Comment by ccordoba12** [comment]
What do you see printed in the terminal when Spyder is started?

**Comment by stonebig** [comment]
nothing, wherever I look:
- dos window from which I launch spyder,
- console,
- other windows.

Like if it was just not connected (or shown).

**Comment by stonebig** [comment]
oups! side-papercut, if you "launch execute in current interpreter while looking at the console tab, spyder hangs.

**Comment by ccordoba12** [comment]
I'm closing this one because it's not our fault and we can't do anything about it.

**Comment by stonebig** [comment]
After eating my bad soup "binary PyQt installer":
-  I have QtDesigner and QtLinguist back, ....
- but trunck spyder with trunk qtpy fails (not even the welcome spyder splash screen image)

**Comment by ccordoba12** [comment]
Spyder needs to be updated to work with qtpy master. Please use `qtpy` 1.0.2 for now, it should work without problems :-)

**Comment by stonebig** [comment]
Well, today I have hard time finding somethig that work. maybe Ipython5.0b4 with its "win_unicode_console" is creating issues for Spyder

**Comment by ccordoba12** [comment]
But we're embedding qtconsole in Spyder, not IPython directly....
