### ISSUE TITLE
Spyder won't launch

### ISSUE THREAD

**Issue by yyan162** [spyder-ide/spyder#3203]
Sir,

I have problems launching Spyder and when I tried to manually open Spyder by using Anaconda Prompt by typing 'spyder', the following message shows up:

[https://mail.google.com/mail/u/0/?ui=2&ik=373a072bf7&view=fimg&th=15522aabe387d34c&attid=0.1&disp=emb&realattid=ii_15522aa6227bfd2e&attbid=ANGjdJ8IKMZBRPx3SplZkUn5cGGWQwHUUL6YNLZMJUQPO5cglRiVKvvK8OjPoxhJ7ZkhDQl1T01JUYhSXWqumYWIgWi_eCXMinelCtRjv6DviT32xijPx7PVGgUrhIM&sz=w896-h720&ats=1465165536992&rm=15522aabe387d34c&zw&atsh=1](url)

> File "C:\Anaconda2\Scripts\spyder-script.py" line 1 in <module> from spyderlib import start_app

> File "C:\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 13, in  <module> from spyderlib.config import CONF

> File "C:\Anaconda2\lib\site-packages\spyderlib\config.py", line 736, in <module> subfolder = SUBFOLDER, backup = True, raw_mode = True>

> File "C:\Anaconda2\lib\site-packages\spyderlib\userconfig.py", line 215, in __init__.selfload_from_ini()

> File "C:\Anaconda2\lib\site-packages\spyderlib\userconfig.py", line 260, in load_from_ini self.readfp<configfile>

> File "C:\Anaconda2\lib\ConfigParser.py", line 324, in readfp

> File "C:\Anaconda2\lib\ConfigParser.py", line 546, in _read raise e ConfigParser.ParsingError: File contains parsing errors: C:\Users\MYName\.spyder2\spyder.ini [line 374]: u'editor/f'

## Versions and main components

* Spyder Version: the latest
* Python Version: 2.7
* Operating system: Win 7

PS: while I have no problem launching Python 3.5 environment, but my root environment (python 2.7) and one particular python 2.7 environments are experiencing this problem. I have tried to click the 'reset spyder' thing and it hasn't worked. Please advise.

Kind regards,
B

**Comment by ccordoba12** [comment]
Please remove the file called `C:\Users\MYName.spyder2\spyder.ini` and try again. That should fix your problem :-)

**Comment by YCTMZJL** [comment]
Same Problem, Same Solution.

**Comment by ccordoba12** [comment]
This problem was fixed in Spyder 3.1. Do you have an older version?
