### ISSUE TITLE
start_ipython_kernel.py will fail when using an external interpreter

### ISSUE THREAD

**Issue by alcrene** [spyder-ide/spyder#3208]
## Description of your problem

On development version Spyder 3.0.0b3, the script `spyderlib/widgets/externalshell/start_ipython_kernel.py` will fail if the variable `external_interpreter` (set on line 66) is `True`. The reason is that in this case `backends` is never set, but is still called on line 95.

**What steps will reproduce the problem?**

1. Install Spyder in a new virtual environment
```
pyvenv --system-site-packages
pip install --pre -U spyder
```
2. In Tools->Preferences->Console->Advanced Settings, change the python interpreter to another one (I chose one from another virtual environment)
3. Restart the IPython console

**What is the expected output? What do you see instead?**
The IPython console doesn't load and displays the error message
```
Traceback (most recent call last):
File "/home/alex/usr/venv/spyder/lib64/python3.4/site‑packages/spyderlib/widgets/externalshell
/start_ipython_kernel.py", line 189, in 
ipk_temp.config = kernel_config()
File "/home/alex/usr/venv/spyder/lib64/python3.4/site‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 95, in kernel_config
if backends[backend_o] == 'inline':
UnboundLocalError: local variable 'backends' referenced before assignment`
```
**Please provide any additional information below**
I'm not convinced simply changing the executable should even set `external_interpreter` to `True`, but since I know nothing of the internals to Spyder, I can't really comment on that.

Simply changing line 69 from
`if backends[backend_o] == 'inline':`
to
`if mpl_installed == 'inline':`
fixed the issue for me.

## Versions and main components

* Spyder Version:  Spyder 3.0.0b3
* Python Version: Python 3.4.1, IPython 4.2.0
* Operating system: OpenSUSE LEAP 42.1

## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
numpy >=1.7     :  1.11.0 (OK)
pandas >=0.13.1 :  None (NOK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.2.0 (OK)
pyflakes >=0.6.0:  1.2.3 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.6 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.4.3 (OK)
sympy >=0.7.3   :  1.0 (OK)

**Comment by Nodd** [comment]
Thanks for the report, it has already been reported in #3206. Just a bit too late :smile:
