### ISSUE TITLE
Edited syntax coloring preferences are not applied or saved

### ISSUE THREAD

**Issue by yulkang** [spyder-ide/spyder#3211]
## Description

**What steps will reproduce the problem?**

1. Go to Preferences -> Syntax coloring -> Edit selected
2. Change the color in Highlight -> Occurrence
3. Press OK twice

**What is the expected output? What do you see instead?**

I expect the occurrence colors to change in the editor, but I don't see the change. When I go the Syntax coloring section again, I find that the change is lost.

**Please provide any additional information below**

Spyder: 3.0.0b3

## Version and main components

* Spyder Version: 3.0.0.dev0 
* Python Version: 2.7.11
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0:  1.1.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1.3 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
pandas >=0.13.1 :  0.18.0 (OK)
numpy >=1.7     :  1.11.0 (OK)
sphinx >=0.6.6  :  1.4.1 (OK)
rope >=0.9.4    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
psutil >=0.3    :  4.1.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.5.4 (OK)

```

**Comment by jitseniesen** [comment]
As a further data point, I tried to reproduce this but failed, but my environment is almost the opposite: Spyder 3.0.0.dev0 (Commit: c8b76e9), Python 3.5.1 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux.

**Comment by yulkang** [comment]
In case it helps... I use OS X 10.11.5 on MacBook Pro retina 15 in. Please let me know if you need other information.

**Comment by ccordoba12** [comment]
I also fail to reproduce it on Linux, we'll see on Mac

**Comment by ccordoba12** [comment]
I just tested this issue using master and a Mac, and I failed to reproduce it too.

I think this was fixed along the way, I don't remember in which beta :-)

**Comment by TeaPearce** [comment]
I'm having this issue as well. I can 'edit selected' to change between bold and italics, but when modifying colours, pressing OK twice closes the preferences box, doesn't give me a chance to hit 'apply', and changes aren't put through. python 3.6.2 macos sierra spyder 3.2.3.

**Comment by dandawg** [comment]
I'm having a similar issue to @TeaPearce. I try to change the color of one of the "Highlight" texts on the "Syntax Coloring" section (after clicking "Edit Selected" to get to the edit window). I'm allowed to edit the color by selecting from the color wheel, but the preferences window closes altogether when I hit OK (as if it's crashing). I installed spyder 3.2.3 two weeks ago through the Anaconda package, and I'm using Mac 10.12.6.

**Comment by TeaPearce** [comment]
@dandawg I finally realised that the confirmation box with 'apply' was being opened, just was weirdly displayed behind the spyder editor window so I didn't see it. Maybe it's the same for you?

**Comment by dandawg** [comment]
Yeah, looks like after clicking OK, the "apply" window was immediately sent behind the main spyder window. This gave the illusion that it was closed. Once I found it and clicked apply there, my color changes stayed.

**Comment by ccordoba12** [comment]
@TeaPearce, could open a new issue about the problem you found and its solution? That way we can fix it in a future release.

**Comment by shimmeringvoid** [comment]
I just encountered this problem with Spyder 2.3.5.2 on Ubuntu 15.10.  Not only didn't the change I specified take hold, other changes did occur that then couldn't be changed back.  And most frustratingly, the RESTORE DEFAULTS option seemed to have no effect.

**Comment by ccordoba12** [comment]
I think you need to press Apply first. Please see the @TeaPearce comment above.

**Comment by shimmeringvoid** [comment]
I did press Apply. Perhaps too many times!   ;-)

**Comment by statchaitya** [comment]
Not working for me either. No matter how many times I apply. No hidden windows or anything of that sort. When I apply and press Ok and then again go back to Tools -> Preferences -> .., the change is lost.

Windows x64, Python 3.5.2, Anaconda 4.1.1 64 bit. Spyder version 2.3.9
