### ISSUE TITLE
No spyder3.0.0b3 in conda linux-64 channel

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3213]
It seems there is no `linux-64` version of `spyder=3.0.0b3` available in the [conda channel](https://anaconda.org/spyder-ide/spyder/files):
```
[duro@ocean ~]$ conda create -n spyder3 -c spyder-ide spyder==3.0.0b3
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
Error:  Package missing in current linux-64 channels: 
  - spyder ==3.0.0b3
```

**Comment by ccordoba12** [comment]
I'm sorry but we're in a bit of a hurry right now. I'll create packages for beta4, to be released in a couple of days.

Thanks for understanding :-)
