### ISSUE TITLE
Pylint report not jumping to line

### ISSUE THREAD

**Issue by TWAC** [spyder-ide/spyder#3219]
## Description

**What steps will reproduce the problem?**
1. Run static code analysis
2. Click on a line in the static code analysis window

**What is the expected output?**
Editor selecting the correct line.

**What do you see instead?**
Editor not moving the selected line.
(It does however select the correct file tab.)

**Please provide any additional information below**
It starts working if I add this slot to load:
```diff
--- a/spyderlib/plugins/editor.py
+++ b/spyderlib/plugins/editor.py
@@ -1641,6 +1641,7 @@ class Editor(SpyderPluginWidget):
 
     @Slot(bool)
     @Slot(str)
+    @Slot(str, int, str)
     @Slot(str, int, str, object)
     def load(self, filenames=None, goto=None, word='', editorwindow=None,
              processevents=True):
```

## Version and main components
* Spyder Version: 3.0.0b3 
* Python Version: 3.4.4
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Windows

 ## Dependencies

```text
pyflakes >=0.6.0:  1.2.3 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pygments >=1.6  :  2.1.3 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
pandas >=0.13.1 :  None (NOK)
numpy >=1.7     :  None (NOK)
sphinx >=0.6.6  :  1.4.3 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  None (NOK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.5.6 (OK)
```

**Comment by Nodd** [comment]
I saw this problem when working on plugins, but I wasn't sure if the problem was on my side or in spyder. Thanks for the report !

**Comment by ccordoba12** [comment]
Thanks a lot for the fix!
