### ISSUE TITLE
Slow spyder execution

### ISSUE THREAD

**Issue by breedlun** [spyder-ide/spyder#3220]
## Description

**What steps will reproduce the problem?**

1. Type anything in the python console
2. Hit enter.

**What is the expected output? What do you see instead?**
It takes roughly 5 seconds to give me the result.  

**Please provide any additional information below**

I have installed Spyder 2.3.9 using pip on enthought canopy, on a mac running OS X 10.10.5.

I have reinstalled canopy, reinstalled spyder, deleted my ~/.spyder2 folder, and the problem remains.

When I pull up a python console from the command line or I use the iPython console in Spyder, I do not have this problem.  (When I type anything and hit enter I get a response nearly immediately.)

Also, I have installed Spyder 2.3.9 using pip on enthought canopy on a different mac running OS X 10.8, and I do not have this problem there.

## Version and main components

* Spyder Version: 2.3.9 
* Python Version: 2.7.9
* Qt Versions:  4.8.7, PySide 1.2.2 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  4.0.0 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.0.1 (OK)
pandas >=0.13.1    :  0.16.2 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
psutil >=0.3       :  3.2.1 (OK)
rope >=0.9.2       :  0.10.3 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
I'm sorry but we don't support PySide anymore. Does it happen the same with Anaconda (which comes with PyQt4)?

**Comment by breedlun** [comment]
Oh, wow, I was not aware of that you stopped supporting PySide.  I have had other issues with Anaconda, and my company has bought into Canopy.  I will look into installing PyQt4.  Last I checked, it did not appear easy.

**Comment by ccordoba12** [comment]
You could wait until Spyder 3.0 is released (in a couple of weeks) and use PyQt5 instead. There are wheels available already, so it should be very easy to install now :-)

**Comment by Nodd** [comment]
Just to be more precise, PySide is not *officially* supported. PRs are accepted and it should run fine in most cases. Maybe we'll support PySide2 once it's stable.

**Comment by breedlun** [comment]
Ok.  I will wait until Spyder 3.0 is released and use PyQt5.  Thanks for the suggestion.

**Comment by breedlun** [comment]
I found out how to make the problem go away, but then I run into another bug.  I was using Qt4Agg as my matplotlib backend because the TkAgg backend has problems with Spyder, where the figure window size cannot be resized correctly (see ticket #1651).  However, if I use TkAgg anyways, then the 5 second wait after hitting enter at the console goes away.  

Hopefully both of these issues will disappear when I switch to PyQt5 and Spyder 3.0.
