### ISSUE TITLE
Editor loses cursor focus after running cell when IPython console is detached

### ISSUE THREAD

**Issue by amccaugh** [spyder-ide/spyder#3221]
## Description of your problem

Normally, when all the Spyder panes are in a single window, running a cell (ctrl-enter) produces the desired output in the IPython console and leaves the cursor in the editor window.  This way, when you run a cell, you can immediately continue working in the editor window.

When I detach the editor window -- so that it floats in its own window -- and then run a cell, this behavior changes.  When detached, after you hit ctrl-enter in the editor pane, it dumps the cursor into the ipython console panel.  So after you hit ctrl-enter and start typing, the text appears directly in the console.  This is cumbersome because often after you run a cell, you'd like to modify the cell slightly, and you are stuck using the mouse to bring the cursor back to the detached editor window manually.

To make this clear graphically, these two setups produce different behavior for the cursor focus:

![2016-06-11 14_39_55-spyder python 2 7](https://cloud.githubusercontent.com/assets/2075083/15987355/84c648ea-2fe2-11e6-935f-9d11fb493b78.png)
![2016-06-11 14_40_18-spyder - editor](https://cloud.githubusercontent.com/assets/2075083/15987354/84c5ff48-2fe2-11e6-9713-6cad9b542925.png)
## Versions and main components
- Spyder Version:  2.3.8
- Python Version:  2.7
- Operating system: Windows 7
## Dependencies

I have not intentionally modified these after a fresh install

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. I don't know how to fix this problem because when panes are detached is like they were different windows.

We'll see what we can do about it for a future release :-)

**Comment by mchijmma** [comment]
Hello, 

Having the same issue here. Is there any solution?

This can be kind of annoying when having your IPython console in a different monitor. 

Best regards.

**Comment by 93chanle** [comment]
Hi,

unfortunately I'm having the same issue. I'm looking forward to a solution soon!

Best regards,

**Comment by Adlinga** [comment]
Same story, gentlemen

**Comment by tommycollins1** [comment]
wow, I have the same issue in 2022 - welcome to the future!

**Comment by tommycollins1** [comment]
My apologies, Carlos I didn't mean to be annoying. I was just shocked to see that the problem has been sticking around for so long. It has been six years without solving or any conversation about it. 

Do you have any idea how it might be solved? I have found, whenever I undock a pane, and running code line-by-line, my cursor will move to the console - - all I can do is redock the pane. 

I really appreciate what you and the Open Collective do, many thanks!

**Comment by ccordoba12** [comment]
> It has been six years without solving or any conversation about it.

We simply haven't had time to take a look at this.

> I have found, whenever I undock a pane, and running code line-by-line, my cursor will move to the console - - all I can do is redock the pane.

Yep, that's still the case in our latest version (5.3.0), even after some changes I made to make the focus really stay in the editor (but not for undocked panes).

> I really appreciate what you and the Open Collective do, many thanks!

Thanks for your support!

**Comment by Alecampoy** [comment]
Same problem here, both with version 4.1.5 and 5.1.5. Installed with conda. When editor undocked, after running a cell the cursor moves to the terminal

Cheers
