### ISSUE TITLE
Spyder 3.0 Beta 3 crashing or freezing because of zmq problems

### ISSUE THREAD

**Issue by kintz8** [spyder-ide/spyder#3223]
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder 3.0 b3, code for a bit.
2. Close laptop lid
3. Open laptop lid a few hours later
4. Observe spinning color wheel and unresponsive application.

**What is the expected output? What do you see instead?**
Spyder should let me continue working as before. Instead, it is frozen and must be force quit to continue.

**Please provide any additional information below**

[spyder crash.txt](https://github.com/spyder-ide/spyder/files/314084/spyder.crash.txt)

## Versions and main components

* Spyder Version: 3.0.0dev0
* Python Version: 3.5.1 64 bits
* Operating system: OSX 10.11.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by Nodd** [comment]
Looks like a problem with threads and zmq. @blink1073 ?

**Comment by blink1073** [comment]
Looks that way.  Note for self: http://stackoverflow.com/a/32051472

**Comment by ccordoba12** [comment]
We need to solve this for Beta4. It also affects Linux.

**Comment by impact27** [comment]
I have a similar problem: After launching spyder 3.0.0b3 it freezes after a handful of minutes.
Also for some reason I have three QtWebEngineProcess appearing on my OSX dock.
I tried to find out where this was coming from and my investigations gave the following:
-execute "python3 -m pdb bootstrap.py"
-ctrl + c when app crashes
-the result is displayed in the internal console of spyder (Even though the app is frozen for some reason)
-As I can't copy-paste (frozen app), I took a screenshot

![error](https://cloud.githubusercontent.com/assets/6740194/16050997/becde5d2-3255-11e6-80ff-053d34e7715b.png)

**Comment by impact27** [comment]
I still have the same issue with Spyder 3.0 Beta 4. The keyboard interrupt was caused by me trying to get an error message out of the program.

**Comment by danipoak** [comment]
I just wanted to chime in that I am having this same problem now on beta 4. It doesn't look like there has been a fix yet but it also looks like the issue is listed as closed. I'd love to provide any more details if they are needed.

**Comment by ccordoba12** [comment]
Hi,

This is fixed in beta5, please update :-)


Cheers,
Carlos
