### ISSUE TITLE
modalSession has been exited prematurely

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3224]
When using `Spyder 2.3.8` from the Anaconda channel, when I select:

```
python | about python
```

I receive the following error in the calling console:

```
2016-06-14 12:31:36.120 python[6165:937196] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
```

The host environment is:

```
OS X 10.11.5
Anaconda2
```

**Comment by ccordoba12** [comment]
It doesn't seem critical but thanks for reporting :-)

**Comment by durack1** [comment]
@ccordoba12 nope not critical at all.. But the sound of a bug being squished is kinda satisfying..

**Comment by ccordoba12** [comment]
Closing because Spyder 2.3 is not supported anymore.
