### ISSUE TITLE
Access to Vim Keybindings Plugin for 3.0.0Beta3

### ISSUE THREAD

**Issue by john9631** [spyder-ide/spyder#3225]
I am a current vim user and I'd like to move to Spyder in preference to PyCharm.  I am running 3.0.0b3.

Is it possible to get access to the current vim plugin and instructions on installation and activation? 

I did attempt installation by cloning @Nodd 's project and installing but at this point I don't appear to have an active Vim mode and I'm not sure what I should do next.

```
git clone https://github.com/Nodd/spyder.vim
sudo python setup.py install
```
Please advise what actions I should take.

**Comment by Nodd** [comment]
The new plugin architecture wasn't ready for 3.0.0b3, you need to use spyder master branch to make it work right now. The easier way to test it is to clone the spyder repo and start spyder with `bootstrap.py`.

Feel free to make as many suggestions, bug reports, feature requests, PRs as you want ! I'll migrate the plugin to the spyder-ide organization soon, in the meantime you can use my repo.

**Comment by john9631** [comment]
So git clone https://github.com/spyder-ide/spyder
will close the spyder master branch.  

How do I integrate your repository into it and bootstrap.py?

As you can tell, I'm missing a big part of how the two things fit together.  Also, should I do it, will the keybindings etc be vim based or will there be something to change within the Spyder gui?

**Comment by Nodd** [comment]
Yes, `bootstrap.py` runs `Spyder 3.0.0.dev0`. This is the name of the dev branch for 3.0.

Simply installing `spyder_vim` should enable the plugin in spyder: on stasrtup spyder checks `sys.path` and loads as plugin any package starting with `spyder_`.

The vim plugins is minimalist: it adds a line edition widget at the bottom of the editor. Pressing `Esc` will give focus to this widget, and you can enter vim commands like `a` or `:wq`. The plugin is still in alpha version, so only a few commands are implemented. See https://github.com/Nodd/spyder.vim/blob/master/spyder_vim/vim.py#L71 for the shortcuts and https://github.com/Nodd/spyder.vim/blob/master/spyder_vim/vim.py#L187 for the commands starting with `:`. The names of the methods are the shortcuts.

**Comment by Nodd** [comment]
I did the switch, the main repo is now https://github.com/spyder-ide/spyder.vim.

**Comment by john9631** [comment]
Thanks Joseph,

I'll test them and let you know of any issues I find or points of confusion.  I'll post at the spyder.vim repository.

**Comment by Nodd** [comment]
Tell me if you manage to get it running ! And file a report if you don't !

**Comment by john9631** [comment]
Yes its running and I tried a couple of things yesterday.  I'll run through your implemented commands and post if I spot any issues.
