### ISSUE TITLE
running_in_mac_app() function doesn't work

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#3229]
I want to be able to run spyder as a .app under OSX to be able to "open with" from the finder.

But I don't want to bundle everything in an app, as I want to be able to organize my modules with brew and pip.

Therefore I created a minimal app bundle and copied the spyder executable inside.

My problem is that the function running_in_mac_app() doesn't detect that I am running an app.
the `__file__` variable in https://github.com/spyder-ide/spyder/blob/master/spyderlib/config/base.py#L397 has a value of "/usr/local/lib/python3.5/site-packages/spyderlib/config/base.py"
(so no Spyder.app)

I therefore had to change the following two lines to `sys.platform == "darwin"` to make my app work:
https://github.com/spyder-ide/spyder/blob/master/spyderlib/app/spyder.py#L3054
https://github.com/spyder-ide/spyder/blob/master/spyderlib/utils/qthelpers.py#L73

While I understand that my use case is probably not representative of the majority of the users, is that something you would consider modifying? 

I tried dropping the `__file__` condition but then the OSX 10.7 hack makes the app crash:
https://github.com/spyder-ide/spyder/blob/master/spyderlib/app/spyder.py#L1246

**Comment by ccordoba12** [comment]
Sorry, we build app bundles ourselves following these instructions:

https://github.com/spyder-ide/mac-application

and `running_in_mac_app()` works exactly for our use case.

----

I'd say you should follow those instructions too, but don't add to the app all the additional modules that we do (like pandas and matplotlib)

**Comment by ccordoba12** [comment]
Closing because we don't plan to do anything about this.

@impact27, you can easily patch Spyder to have the behavior that you want :-)
