### ISSUE TITLE
Deprecation warning from IPython 5.0.0b4

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3231]
## Description of your problem

**What steps will reproduce the problem?**

1. Ipython 5.0.0b4
2. start spyder 3.0.0b3
3. 

**What is the expected output? What do you see instead?**
`DEPRECATED: IPython.core.usage.default_gui_banner is deprecated and will be removed`
![spyder300b](https://cloud.githubusercontent.com/assets/4312421/16170225/e0ce7fcc-354b-11e6-9013-59c813d1efe3.PNG)

by comparison, on same environnment, qtconsole doesn't have the problem:
![spyder300b2](https://cloud.githubusercontent.com/assets/4312421/16170248/a75a3e9c-354c-11e6-913b-a70f2233eb07.PNG)

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.0.0b3
* Python Version:3.4.4
* Operating system:Windows7

## Dependencies
 
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.2rc2 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.18.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
pyflakes >=0.6.0:  1.2.3 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.6 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.4.4 (OK)
sympy >=0.7.3   :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting it @stonebig!

So I see you finally managed to get Spyder running again :-) Nice!

**Comment by stonebig** [comment]
yes, going back to standard 3.0.0b3.
