### ISSUE TITLE
Add "step into my code" option to the debugger

### ISSUE THREAD

**Issue by JohnRobson** [spyder-ide/spyder#3232]
Dear developers,

Bug: There is a bug in "Debug": I set up break points (bps) in 2 files (A & B,  same directory), "A" stop in the bp line and a "step into" calls a function into file "B", this function has several bps, but no one is respected (bp only works in file A, not in file B).

If I remove the bps from A, Spyder doesn't stop into file B bps.

Suggestions: There are several commands for pdb / ipdb (https://docs.python.org/3/library/pdb.html)

1) unt(il) [lineno] is very useful to run a loop without step inside (think about big loops).

I suggest that this command stops in the Next Line After the Loop or stops in the Next Break Point (or both).

2) "step into my code" (from PyCharm) "helps skip stepping into library sources and keep focused on your own code", very useful to avoid enter into functions from python and other modules.

3) "ipdb" is colorized only if manually called "import ipdb; ipdb.set_trace()", the highlights are very useful in a debug process.

4) will be very nice to see the variable values directly in the code editor (like comments beside the variables) [screenshot](https://s31.postimg.org/kbna9dla3/2016_06_18_17_26_58.png)

5) in the "Variable explorer" add a new column "#" to sort by Declaration order (is useful to see the variables sorted by creation order)

Thank you very much for doing one of the best Python IDEs.

ps.: I'm using version 2.3.9 in ArchLinux.

John

**Comment by ccordoba12** [comment]
> will be very nice to see the variable values directly in the code editor (like comments beside the variables)

This is not possible.

> in the "Variable explorer" add a new column "#" to sort by Declaration order (is useful to see the variables sorted by creation order)

I don't know how this could implemented, sorry.

**Comment by ccordoba12** [comment]
> "ipdb" is colorized only if manually called "import ipdb; ipdb.set_trace()", the highlights are very useful in a debug process.

This was already implemented.
