### ISSUE TITLE
import cv2 not working in spyder

### ISSUE THREAD

**Issue by dECRISES** [spyder-ide/spyder#3236]
## Description of your problem

import cv2 is not working in spyder.
It is working in terminal and also in anaconda terminal but while importing cv2 in ipython console in spyder, it shows following:

In [1]: import cv2
     ...:

It shows nothing else and becomes irresponsive.

## Versions and main components

* Python Version: Python 2.7.11 :: Anaconda 4.0.0 (64-bit)
* Operating system:Windows 10

## Dependencies

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
This seems to be the same issue as #2696. It'll be fixed by PR #2878 in Spyder 3.0 :-)

**Comment by jmokoistinen** [comment]
I have the same problem in Spyder 3.0.0. I am using python 3.5 through anaconda. On normal terminal from ubuntu 16.04 I can import cv2, but from spyder cannot.
