### ISSUE TITLE
Unable to see Float16 in Spyder Variable Explorer

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3237]
## Description of your problem

**What steps will reproduce the problem?**

1. v= np.zeros((5,5), dtype=np.float16)
2.   In  Variable click on v to see inside the table, an Error saying Float16 is not supported.

**What is the expected output? What do you see instead?**
We can see Float32 and Float64,  Float16 is useful, especially
for neural network (Google even uses Float8 .... !!)

Able to see Float16, Float8 in Variable Explorer.

## Versions and main components

* Spyder Version:  Spyder 2.3.5.2 
* Python Version: Python 2.7.10 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Windows
* Operating system:  Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
@arita37 thanks for your report. Your Spyder is a bit out of date: the latest stable version is 2.3.9, but the issue still persists in that version. We should be able to add support for float16. However, I can't find anything about float8; is there any documentation about this type?

**Comment by arita37** [comment]
Hello,

Am using WinPython.
Is there a way to update Spyder without messing all my installed package in WinPython ?


Thanks

On 22 Jun 2016, at 17:47, Jitse Niesen <notifications@github.com> wrote:

@arita37 thanks for your report. Your Spyder is a bit out of date: the latest stable version is 2.3.9, but the issue still persists in that version. We should be able to add support for float16. However, I can't find anything about float8; is there any documentation about this type?

―

**Comment by ccordoba12** [comment]
@jitseniesen, we define our list of supported types for the Variable Explorer:

https://github.com/spyder-ide/spyder/blob/master/spyderlib/config/base.py#L343

I think you shouldn't have much problem in adding and testing that we can show `float16` arrays too :-)

**Comment by jitseniesen** [comment]
> Am using WinPython. Is there a way to update Spyder without messing all my installed package in WinPython ?

I'm not using WinPython so I don't know. @stonebig do you know?

**Comment by stonebig** [comment]
I woud try:
- copy/paste Winpython directory (the winpython-copy is a backup, if all goes wrong, ziping it would do also)
- start "Winpython Command Prompt", and
````
pip install qtpy
pip uninstall spyder
pip install spyder
````

WinPython2.7 is no longer maintained, so it's theorical suggestion
