### ISSUE TITLE
Remove miniconda install from AppVeyor

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#3243]
I just noticed that miniconda is available on AppVeyor, so there is no need to reinstall it and complicate builds there.
http://www.appveyor.com/docs/installed-software#python

**Comment by ccordoba12** [comment]
Those versions are quite outdated. It's better for us to handle installation of it.

**Comment by techtonik** [comment]
Why do you need `latest` instead of `stable`?

**Comment by Nodd** [comment]
To catch bugs from new versions in advance.

**Comment by techtonik** [comment]
As if Qt bugs are not enough. =)
