### ISSUE TITLE
Missing docs on debugging crashes

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#3244]
Old web-site had docs on how to debug crashes like https://github.com/spyder-ide/spyder/issues/2567 and I could find them right now.

http://web.archive.org/web/20141229073439/http://code.google.com/p/spyderlib/wiki/HowToDebugQtCrash
http://web.archive.org/web/20141229081549/http://code.google.com/p/spyderlib/wiki/HowToDebugDeadlock

**Comment by Nodd** [comment]
Here you go, good old copy-paste (maybe needs some updates?):
https://github.com/spyder-ide/spyder/wiki/How-to-debug-PyQt-PySide-internal-crashes-%28segfaults%29-affecting-Spyder
https://github.com/spyder-ide/spyder/wiki/How-to-debug-Spyder-deadlock-freeze-hang

**Comment by techtonik** [comment]
I'd prefer this to be present on Spyder website, because Github wikis are overburdened with space ship interface controls.

**Comment by Nodd** [comment]
Is the website still updated ? I didn't check it since months...
But I expect developers who want to debug spyder to look at github first.
If the interface is bothering you, you can clone the wiki repo and render it locally: https://github.com/spyder-ide/spyder.wiki.git

**Comment by techtonik** [comment]
Site is dead - https://github.com/spyder-ide/website/issues/2
