### ISSUE TITLE
Installation causes Spyder and Navigator to break

### ISSUE THREAD

**Issue by ganong123** [spyder-ide/spyder#3245]
## Description of your problem

I just tried to upgrade from Spyder 2.3.7 to Spyder 3.0.0-b3 and now Spyder won't launch, nor will Navigator. I looked for another issue to comment on, but couldn't find anything so opening a new issue here.

**What steps will reproduce the problem?**

1. At terminal, upgrade spyder
```
Macintosh:~ ganong$ conda update qt pyqt
Macintosh:~ ganong$ conda install -c spyder-ide spyder==3.0.0b3
```
2.  At terminal, run spyder
```
Macintosh:~ ganong$ spyder
```

**What is the expected output? What do you see instead?**
From the command line
```

Traceback (most recent call last):
  File "//anaconda/bin/spyder", line 3, in <module>
    start_app.main()
  File "//anaconda/lib/python2.7/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "//anaconda/lib/python2.7/site-packages/spyderlib/spyder.py", line 88, in <module>
    from spyderlib.qt.QtGui import (QApplication, QMainWindow, QSplashScreen,
  File "//anaconda/lib/python2.7/site-packages/spyderlib/qt/QtGui.py", line 10, in <module>
    from PyQt4.Qt import QKeySequence, QTextCursor  # analysis:ignore
ImportError: cannot import name QKeySequence
```

**Please provide any additional information below**
When I try to launch anaconda navigator it fails to launch (no error message).

## Versions and main components

* Spyder Version: 3.0.0-b3
* Python Version: Python 2.7.11 :: Anaconda custom (x86_64)
* Operating system: Mac OS X El Capitan

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Can't right now since python IDE won't launch.

**Comment by ganong123** [comment]
Finally, what should I do now? How can I uninstall 3.0.0-b3 and revert to my old version of spyder?

**Comment by Nodd** [comment]
What is your qtpy version ? I think the minimum you need is 1.0.2.

**Comment by ccordoba12** [comment]
You're certainly not using Spyder 3.0 beta3 because the `spydelib.qt` module was removed between in beta3.

`spyderlib.start_app` also doesn't exist in beta3. It seems you have an older beta, but to know which one is impossible for us to tell :-)

**Comment by ganong123** [comment]
OK, I will try to figure this out on my own and re-open if I can't figure it out.
