### ISSUE TITLE
Regex is not fully functional when using to find&replace

### ISSUE THREAD

**Issue by martinwk** [spyder-ide/spyder#3249]
I want to use the following regex
`\["([a-z_]*)"\]`
and want to replace it with 
`.\1`
to change pars["delta_s"] to pars.delta_s or similar. This does work on some lines but not on all. The regular expression is met, but somehow Spyder fails to actual replace the string. More importantly, when clicking Replace/find the cursor does not (always) jump to the next hit but skips one hit. If then replace/find is clicked again it jumps bakc to the one it skipped before

**Comment by thierryBottaro** [comment]
I tested 3 versions of Spyder. from 2.3.8 to the  3.0.0beta 4 
I can very nicely reproduce the bug : 

1) take a file in editor with some lines like : 
aaabbbccc
aaabbbccc
aaabbbccc
aaabbbccc
aaabbbccc

2) make a find&replace with "regexp" activated
search field= a(.*)b
replace field = "ab" (or whatever, this is not changing anything)

3) click on "replace/find"

it find very nicely the next pattern occurence. but does NOT replace it... it just replaces the next occurence. So every 2nd occurence is replaced. And if you click "replace All", it works perfectly (but I got once a freeze for some seconds of Spyder... that's not reproducible.)

I really don't think it is a complicated bug to correct, it just search twice to replace once.

**Comment by haicen** [comment]
I am also having this issue. The regex identifies the correct lines I want to replace, but it will not modify them in any way.

**Comment by ccordoba12** [comment]
@andfoy, please work on this one. It seems simple to fix :-)

**Comment by haicen** [comment]
Thanks for the update, but I am still having issues with certain pattern matching. I was hoping to do some pattern matching to find blank lines with groups of 4 spaces, indicating lines with tabs but no content. I was trying to automate conformity of pep8 rule W293. Other regex patterns match, and are replaced. However attempting to match something like "`(\s{4})+\n`" finds the text correctly, but replacement does not do anything.

Like I said, I was able to get regex replacement to work on other patterns, just not this one.

I really appreciate you guys looking into this.

**Comment by ccordoba12** [comment]
@haicen, please open a new issue about that particular pattern so we can address it in another release ;-)
