### ISSUE TITLE
After sudden laptop battery fail, the (properly saved) file being edited was corrupted

### ISSUE THREAD

**Issue by capitanevs1066** [spyder-ide/spyder#3250]
## The problem
I was working in spyder on a py file, already saved (let's say 300 lines).
I launched such a script (which was using multiprocessing module), and few minutes later (the computation was tough) my laptop turned off suddenly (some battery fail).

When I restarded my OS again, the file I was workin on was completely full of NULL characters!
The other files which were opene in the editor at the shutdown time are still ok.

I have no tried to "simulate" the issue again (I can't remove the battery, for instance).

## Versions and main components

* Spyder Version: 2.3.8 (shipped with anaconda)
* Python Version: 2.7
* Operating system: 10 (upgraded from 8.1)

**Comment by Nodd** [comment]
I suppose it's because the file as saved in the disk cache but not on the disk itself. I don't know if spyder can do anything about it, maybe flush the file on save ?

**Comment by capitanevs1066** [comment]
Hi. I don't get the sense. When should a file be written on the disk if not at the "save" and "save as" command? If you open a file, save it, then terminate spyder, the file is properly saved, as one expect it to be.

**Comment by Nodd** [comment]
I mean that it can be an OS problem: the file can be written on the disk cache only. This is transparent for the user, except in case of power failure, where the cache content is lost. This is just a supposition.
We can't really do anything about power failures. The only advice I can give you is to use a versioning tool like mercurial or git to minimize losses in case of problems.
