### ISSUE TITLE
Symbolic math not working

### ISSUE THREAD

**Issue by dtenorio** [spyder-ide/spyder#3255]
Hello,

I am unable to see a LateX-style printout when using sympy in an IPython console in Spyder (Python 3.5), even though I already have 'Use symbolic math' checked in the Preferences. How can I fix this? Let me know what info i need to provide.

Thank you.

**Comment by ccordoba12** [comment]
Questions:

1. What's your Sympy version?
2. Do you have Latex installed?

**Comment by dtenorio** [comment]
Installing LaTeX solved the problem - silly me!

Thank you!
