### ISSUE TITLE
Pweave syntax highlighting

### ISSUE THREAD

**Issue by jmackie4** [spyder-ide/spyder#3258]
It would be really nice to have [Pweave](http://www.mpastell.com/pweave/docs.html) syntax highlighting supported in the spyder editor; i.e. support for highlighting only code chunks. Ignoring everything else. 

Currently, editing a *.texw or *.mdw file in spyder just renders everything in horrible plain white text. The ability to run chunks within spyder, ala RStudio + Rmarkdown, stops me resorting to a dedicated text editor (e.g. atom + [the weave plugin](https://atom.io/packages/language-weave)).

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-reports #6](https://github.com/spyder-ide/spyder-reports/issues/6) via [**ZenHub**](https://www.zenhub.com/)
