### ISSUE TITLE
Error with debugfile file and user names on Windows

### ISSUE THREAD

**Issue by Kilimanjaro-Serengeti** [spyder-ide/spyder#3259]
debugfile('C:/Users/Malawi/'Salmon/untitled1.py', wdir='C:/Users/Malawi/'Salmon')
  File "<ipython-input-20-20e5bbd9a307>", line 1
    debugfile('C:/Users/Malawi/'Salmon/untitled1.py', wdir='C:/Users/Malawi/'Salmon')
                                     ^
SyntaxError: invalid syntax

**Comment by ccordoba12** [comment]
Is your user name: `'Salmon` with an apostrophe there?

**Comment by ccordoba12** [comment]
Closing because of lack of response. Besides, I think this was already fixed in Spyder 3.1
