### ISSUE TITLE
IPython console can't connect to kernel, sticking on "Connecting to kernel..." message

### ISSUE THREAD

**Issue by bumjjoony** [spyder-ide/spyder#3262]
I know many users have gone through the same problem already. I searched all answers in the web and tried all the remedies including the following, but didn't work at all.

- reinstall anaconda3 several times;
- update pyzmq;
- downgrade matplotlib 1.5.1 to 1.4.3;
- deactivate antivirus and firewall software;
- Reset Spyder Settings
- etc.

I'm using Spyder 2.3.8, Python 3.5.1 64 bits on Windows 8.

If you know any other remedy, please let me know.

FYI. In the Console>Kernel tab, the message is:

NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.
To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.
To read more about this, see https://github.com/ipython/ipython/issues/2049
To connect another client to this kernel, use:
    --existing kernel-5948.json  (<- I can't find this file in the '.ipython\profile_default\security' folder.)

**Comment by ccordoba12** [comment]
This is going to be fixed in Spyder 3.0. Thanks for your patience :-)
