### ISSUE TITLE
Spyder cannot be launched by Anaconda Prompt 

### ISSUE THREAD

**Issue by yyan162** [spyder-ide/spyder#3263]
## Description of your problem
Hi,

I am having problems launching Spyder from Anaconda, whenever I type 'spyder' on prompt, the following message shows up:

```
Traceback <most recent call last>:
File "C:\Anaconda2\Scripts\spyder-script.py", line 2, in <module> start_app.main()
File "C:\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in main from spyderlib import spyder
File "C:\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 48, in <module> requirements.check_qt()
File "C:\Anaconda2\lib\site-packages\spyderlib\requirements.py", in line 50, in check_qt %(qt_infos['pyqt']+qt_infos['pyside']))
File "C:\Anaconda2\lib\site-packages\spyderlib\requirements.py", in line 25, in show_warning raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
PyQt4 4.6 + (or PySide 1.2.0+) is required.
```
I could still launch spyder by clicking its icon, but numpy scipy etc cannot be found and when I tried to pip install them, it says:

`Requirement already satisfied...`

Jupyter Notebook for Python2 is also having problems loading the external libraries.

My Spyder for python 3.5 is working perfectly fine.

I also cannot launch Anaconda Navigator via neither anaconda prompt and clicking the bottom.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 2.7
* Operating system: Win 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  None (NOK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

```

Many thanks for your help.

Kind regards,
yyan162

**Comment by ccordoba12** [comment]
This seems to be an installation problem and not a problem with Spyder itself. You don't need two different installations of Anaconda to be able to work with Python 2 and 3 at the same time.

Please learn how to use conda environments to do things in the right way:

http://conda.pydata.org/docs/using/envs.html

**Comment by yyan162** [comment]
I did, they were working just fine between the two environments.
