### ISSUE TITLE
Text not visible in new file switcher in KDE

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3274]
## Description

**What steps will reproduce the problem?**

1. Ctrl+P

**What is the expected output? What do you see instead?**
I expect to see the text, but instead I see part of the first character and a white rectangle:
![spyder](https://cloud.githubusercontent.com/assets/506348/16517938/7ab376b8-3f80-11e6-8149-e4c8945fa74c.png)

**Please provide any additional information below**
Entering text changes the first letter displayed but it still not possible to see the full text.

## Version and main components

* Spyder Version: 3.0.0.dev0
* Python Version: 3.5.1
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux (KDE)

## Dependencies
```
pyflakes >=0.6.0 :  1.2.3 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.0 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.1.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by ccordoba12** [comment]
I think this only happens on the latest KDE, so moving to 3.1 for now
