### ISSUE TITLE
Print all keyboard shortcuts to cheatset

### ISSUE THREAD

**Issue by timmie** [spyder-ide/spyder#3275]
Spyder has may good shortcuts. But they are well hidden in the preferences dialogue

**Tools --> Preferences --> Keyboard shortcuts?**

Solution:
add a print (to PDF) function to the keyboard settings so that users can have these open on a separate file while learning the programme.

References:
https://code.google.com/archive/p/spyderlib/issues/578
https://github.com/spyder-ide/spyder/issues/578

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 3.0.dev
- Python Version: 2.7
- Operating system: linux, ubuntu mint 17.3
## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.0.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  3.3.0 (OK)
pyflakes >=0.5.0 :  1.0.0 (OK)
pygments >=2.0   :  2.0.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  0.7.6.1 (OK)

**Comment by goanpeca** [comment]
Would a shortcut to display a summary of shortcuts help? Like Ubuntu when leaving pressed the "windows" key

![image](https://cloud.githubusercontent.com/assets/3627835/16533965/022b2944-3fa2-11e6-9433-cb6b07b5fb9d.png)

**Comment by timmie** [comment]
@goanpeca This would be perfect!

**Comment by goanpeca** [comment]
@rlaverde

**Comment by rlaverde** [comment]
I'm working in this issue, this is the current state, any opinions? improvements? Which shortcut will display the dialog?

![shortcuts_draft](https://cloud.githubusercontent.com/assets/2024217/17218874/eee4d2aa-54ae-11e6-94ae-f7c595ac10d2.png)

**Comment by ccordoba12** [comment]
@rlaverde, this is really nice!

Just a couple of comments:

1. The Pylint and Profiler sections look too big, but other than that, I like it very much!
2. Please test this in other platforms to see how it looks,
3. This list should be printable somehow. I mean, we could add a *Print* button to the dialog and a printable representation associated with it. @goanpeca, what do you think?

**Comment by goanpeca** [comment]
Hi @rlaverde, thanks for working on this :-)

@ccordoba12 on your comments:

1. Yes, hmmm maybe if the column rows are smaller than the max allowed, we could add a stretch (`layout.addStretch`), so that they line up and dont waste space

2. I can see how it looks on windows and OSX as soon as @rlaverde has a PR

3. That is a great idea :-p, but Probably we would need to reformat the content?, maybe for another PR cause it might need some extra tweaking?

**Comment by timmie** [comment]
@ccordoba12 as initial requester I would be happy with the quick display. Maybe saving as image file. But well formatted printing is not needed if let's say WIN+F1 brings this panel up very quickly.

**Comment by cybervigilante** [comment]
What I could use, but don't see in the displayed shortcuts, is Insert Cell Below, which I constantly use to experiment with things, get info, or correct an error in the cell above

**Comment by ccordoba12** [comment]
Cells are simply created by comments of the form `#%%`, so I don't think that needs a shortcut.
