### ISSUE TITLE
Running individual lines with v3.0

### ISSUE THREAD

**Issue by jmackie4** [spyder-ide/spyder#3276]
In versions 2.* I could run a single line via the "run selection" keyboard shortcut. 

I've moved to version 3.0.0 beta3 and seem to have lost this feature. All "run" shortcuts just execute the highlighted cell regardless.

## Versions and main components

* Spyder Version: 3.0.0 beta3 (with PyQt5 5.5.1)
* Python Version: 3.5.1 (64 bit)
* Operating system: Ubuntu 16.04 LTS

## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
numpy >=1.7     :  1.11.1 (OK)
pandas >=0.13.1 :  0.18.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.3.0 (OK)
pyflakes >=0.6.0:  1.2.3 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.6 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
rope >=0.9.4    :  0.10.3 (OK)
sphinx >=0.6.6  :  1.4.4 (OK)
sympy >=0.7.3   :  1.0 (OK)

**Comment by jitseniesen** [comment]
@jmackie4 That's strange. For me, F9 runs only the selected line, not the whole cell. What if you use "Run selection" in the "Run" menu?

**Comment by jmackie4** [comment]
Works fine from the "Run" menu.

**Comment by ccordoba12** [comment]
It's working for me too. No idea why is failing for you ;-)

**Comment by Nodd** [comment]
Maybe check the shortcuts in the preferences ?

**Comment by jmackie4** [comment]
So it turned out my machine didn't like the F9 shortcut, and my preferred replacement (CTRL+RETURN) didn't work either. Choosing another shortcut does allow running selections. Is it an issue my end that CTRL+RETURN doesn't work for running selections, or is this an existing shortcut that can't be overridden?

**Comment by ccordoba12** [comment]
> Is it an issue my end that CTRL+RETURN doesn't work for running selections, or is this an existing shortcut that can't be overridden?

`Ctrl+Return` is harcoded in Spyder and it's used to run cells (portions separated by comments of the form `#%%`), so it can't be overridden.

**Comment by Nodd** [comment]
Spyder should check that the shortcut is available when setting a new one or when loading the config file. Easier said than done, I know…

**Comment by ccordoba12** [comment]
Spyder does check repeated shortcuts in Preferences. We should add there checks for fixed shortcuts :-)

**Comment by jmackie4** [comment]
I get that the fixed shortcuts are to accommodate matlab users, but for those of us coming from Rstudio ctrl+return executes lines. Might be nice to be able to opt out of fixed shortcuts...

**Comment by ccordoba12** [comment]
> Might be nice to be able to opt out of fixed shortcuts

Sorry, not possible with our current design :-)
