### ISSUE TITLE
Support IPython.embed in IPython console

### ISSUE THREAD

**Issue by nevion** [spyder-ide/spyder#3279]
## Description of your problem

**What steps will reproduce the problem?**
1. Put "from IPython import embed; embed()"
2. observe through interactive command line usage, the shell is half-broken: history, pretty printing of last results, tab completion and more are not working.
3. 

**What is the expected output? What do you see instead?**
A shell configuration (tab-completion, history, pretty printing of last result) comparable to starting IPython in the command line, running the same script, where configuration is applied correctly.

**Please provide any additional information below**
## Versions and main components
- Spyder Version:3
- Python Version: 3.5.1
- Operating system: windows/linux
## Dependencies

IPython

**Comment by ccordoba12** [comment]
Sorry, but we can't support embedding IPython into a qtconsole session (nor in our Python consoles, for that matter :-).

The two consoles (terminal and Qt based) are very different internally (they use different libraries and technologies), so we can't have one embedded in another.

**Comment by nevion** [comment]
@ccordoba12 I helped fixed fix embed (make it recursive/callable from within IPython)... please don't close the issue out right until we've assessed it more.  I use it as the best python debugger around.

Maybe you could shine some light as to where the problem is?  Already sounds like you're aiming at the Qt shell.  Where does this implementation live?

**Comment by ccordoba12** [comment]
Of the top of my head:

1. IPython.embed uses readline for history browsing and code completion. That of course will change in IPython 5.0 with prompt_toolkit, but still QtConsole uses none of those libraries for the job.
2. QtConsole uses the Jupyter kernel-based architecture (not used by IPython, but also used by the Notebook and Jupyter console). I haven't seen this architecture to play well with embedded IPython sessions. I tried it a couple of years ago, and back then QtConsole complained that it couldn't embed the session. Now it seems too work, but some output is printed to the terminal where QtConsole was started (like `ls`), and plots don't work.

----

What you're trying to do to improve debugging is not the right solution. I think the best one is to create a kernel that talks to a Pdb instance. But that's for Spyder 4.0 ;-)

**Comment by ccordoba12** [comment]
> Already sounds like you're aiming at the Qt shell

That's what we use in our plugin called *IPython console*.

**Comment by nevion** [comment]
I disagree Pdb is the right solution - it doesn't have the power of analysis of environment that IPython does.  The embed call works anywhere and setting up persistent conditional breakpoints is very easy - which always helps me diagnose troublesome code faster/better.  Believe me, I've had years to think and practice this through and IPython is superior as a debugging shell to all the others (esp the ones who didn't work at all for me) .  I really don't see why it shouldn't be, despite it not being the focus of the shell.  It's just so good/complete, it passed up the special purpose debuggers, too.

Regarding your point 2 above, yes that happened/started working as a side effect of my fixes.  I'll have to sit down and see if anything stands out.

Can you list the paths to files of interest, maybe some line ranges too?

**Comment by ccordoba12** [comment]
> I disagree Pdb is the right solution - it doesn't have the power of analysis of environment that IPython does

I said Pdb *kernel*. So things will work like in regular IPython session, but the session will be powered by a Pdb kernel (like when you use the notebook with an R kernel or a Julia kernel).

Since Pdb can evaluate any Python code (when passed to it in a certain way, I don't remember the details), I think that's almost all that we need because Pdb can access the namespace of the currently inspected stack frame. The most important thing to solve is how to make Matplotlib plots to work with that kernel :-)

> Can you list the paths to files of interest, maybe some line ranges too?

This is not a problem with Spyder, but with Qtconsole (we simply integrate it in Spyder). You can start by running in a terminal

    jupyter qtconsole

and then evaluate on it

```python
from IPython import embed; embed()
```

and see how to *fix* it.

However, I think that's a dead end.

**Comment by ccordoba12** [comment]
Closing as we can't do anything about this on the Spyder side.
