### ISSUE TITLE
Make `pip` accessible via the menu

### ISSUE THREAD

**Issue by ChristianKleineidam** [spyder-ide/spyder#3280]
I used added a new package via `pip` on the Windows 10 command line. Unfortunately it installs the package to a different version of Python than the one that Spyder uses. It would be helpful if there would be an option in the menu to run pip that runs it, so that the installed package is directly useable via Spyder.

**Comment by ccordoba12** [comment]
Take a look at:

https://github.com/spyder-ide/conda-manager

It also supports pip. it will be available since Spyder 3.0 as an external plugin :-)

**Comment by Nodd** [comment]
@ccordoba12 AFAIK conda-manager can list and remove packages installed with pip, but can not (yet ?) install them itself.

**Comment by goanpeca** [comment]
@Nodd yes, correct, it will be handled in the next version
