### ISSUE TITLE
QApplication is used from QtGui instead of QtWidgets in app/spyder.py

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#3282]
The following lines in `initialize()` in `spyderlib/app/spyder.py` (dev version, revision 48c96725) look rather suspicious to me:
```python
    #----Monkey patching PyQt4.QtGui.QApplication
    class FakeQApplication(QApplication):
        """Spyder's fake QApplication"""
        def __init__(self, args):
            self = app  # analysis:ignore
        @staticmethod
        def exec_():
            """Do nothing because the Qt mainloop is already running"""
            pass
    from qtpy import QtGui
    QtGui.QApplication = FakeQApplication
```
After the transition to qt5, QApplication resides in QtWidgets, so should the final line be `QtWidgets.QApplication = FakeQApplication`? I don't know the reason why this code is included, so I can't do more than flag up the issue.

**Comment by ccordoba12** [comment]
Thanks for noticing @jitseniesen! I'll take a look at it :-)
