### ISSUE TITLE
different results running python from terminal and Spyder

### ISSUE THREAD

**Issue by ilkerhk** [spyder-ide/spyder#3283]
## Description of your problem
Getting an error for a script that runs from terminal without any issues

**What steps will reproduce the problem?**
1. Install anaconda, cvxopt
2.  Run below 3-line code in spyder
from cvxopt import *
P, q = normal(1,1), normal(1, 1)
u = lapack.gels(P, q)

**What is the expected output? What do you see instead?**
Expected output is nothing. Spyder giving error. Running from terminal runs as expected.

**Please provide any additional information below**
Isn't spyder supposed to be same as running the script (Assuming  the same interpreter) ? I don't know what might be  the difference running script from terminal and spyder?  Spyder gives error  : 
   u = lapack.gels(P, q)
   ValueError: -10

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 3.5.2
* Operating system: Opensuse Linux
Anaconda 4.1.1

## Dependencies
cvxopt

thank you.

**Comment by jitseniesen** [comment]
Yes, I would have expected the results to be the same. The python path may be different. I think you can check that the same lapack library is used as follows: 
* In the terminal, give the commands  `from cvxopt import *; print(lapack)`.
* Do the same in Spyder. 
* Compare the results.

There are also some options in the Spyder preferences which may cause a difference (check the Python or IPython tab, depending on how you run the commands in Spyder).

If none of this helps to resolve your problem, can you please specify exactly what you mean by "running in spyder" and "running from the terminal"? In particular, for both cases, do you use a Python and IPython console?

For your information, I get the same error with Python, IPython, Spyder using Python, and Spyder using IPython. Here is the output from python:
```
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from cvxopt import *
>>> P, q = normal(1,1), normal(1, 1)
>>> u = lapack.gels(P, q)

Intel MKL ERROR: Parameter 5 was incorrect on entry to DGELS.

Intel MKL ERROR: Parameter 10 was incorrect on entry to DGELS .
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: -10
```
For some reason, the MKL errors are suppressed in Spyder, but the ValueError is still the same.

**Comment by ilkerhk** [comment]
Thanks for the reply. They give same response to print(lapack), also I couldn't manage to solve issue after playing preferences. 
I am sending a screenshot which compares ipython console from bash and within Spyder showing different results mentioned in OP.

By the way this same error was fixed previously downgrading cvxopt "conda install cvxopt=1.1.8=py35_0". After this downgrade both Spyder and ipython console were behaving as expected. However this time it didn't fix in Sypder but fixed in ipython console. Can the reason be some sort of caching ? 

thanks...

![screenshot](https://cloud.githubusercontent.com/assets/13827163/16709929/5d8f61ce-45ec-11e6-9034-07d20ed76d20.jpg)

**Comment by jitseniesen** [comment]
Thanks for the extra information. I can now reproduce it. Unfortunately, I don't see what could be causing it, so I can't help you further at the moment. :disappointed:

**Comment by ilkerhk** [comment]
I realized when I downgrade cvxopt to built 35_0 it is automatically installing OPENBLAS as alternative to MKL. When I uninstall MKL Sypder works fine.  This leads me to the guess that even if cvxopt depends on OPENBLAS,  Spyder still using MKL.  Anyways I removed MKL and now it seems OK...
Thanks again for quick replies...
