### ISSUE TITLE
Feature request: option to not echoing the code in ipython console when running code selections or cells. 

### ISSUE THREAD

**Issue by ilkerhk** [spyder-ide/spyder#3284]
A behavior similar to "echo off" would be great when running code selections or cells. 

Longer version:  I am trying to simulate behavior of a "notebook", by creating a script containing several code cells and running each with control+enter. In each run however it prints all the code on the console which decreases readability of the actual outputs (prints and plots etc). So It would be great to have an option to disable echoing the lines of the codes into the console.  

P.S. Personally,  I find this type of notebook better than jupyter/mathematica style notebooks. I also like it more than matlab implementation because of two reasons: one with dual pane I can work on this test-bed notebook simultaneously, and secondly inline plots.
Thanks and keep up the good work...

**Comment by ccordoba12** [comment]
The lines are not just echoed to the console, they are printed there to be evaluated :-)

**Comment by ilkerhk** [comment]
I dont know how this new feature can be made or possible.. Is it not possible to communicate with the console other than pasting? 
If that is the case may be current cell wrapped into a temporary script something like running-cell-no5.py? For  me it is better to see one line instead of tens of lines.

**Comment by ccordoba12** [comment]
Closing as we don't plan to work on a solution for this, sorry.

**Comment by aabuaish** [comment]
I know this post is old. However, can we disable echoing of python code to the console? has such a feature been implemented?
