### ISSUE TITLE
"Quit Spyder" menu entry doesn't work in 3.0.0b4 (OS X 10.11)

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3288]
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder 3.0.0beta4 (anaconda installation on OS X 10.11.5)
2. Attempt to close using toolbar `python | Quit Spyder option`
3. Nothing happens

## Versions and main components

* Spyder Version: 3.0.0beta4
* Python Version: Python 2.7.11 |Continuum Analytics, Inc.| (default, Dec  6 2015, 18:57:58)
* Operating system: OS X 10.11.5

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.9.2 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
What is your PyQt version?

**Comment by durack1** [comment]
@ccordoba12 here you go, `PyQT 5.6`:
![spyder300b4](https://cloud.githubusercontent.com/assets/3229632/16843662/05fc0ec2-4997-11e6-845d-a2980bea10f6.png)

**Comment by JuanCab** [comment]
I can confirm the same problem using the same configuration (except under Python 3.5 64 bit on OS X).  Cmd-Q doesn't work either, looks like the menu item may not be connected to the command to quit.

**Comment by amccaugh** [comment]
Can also confirm this is an issue for me.  Using Python 2.7 64 bit on OS X, with PyQt version 5.6
