### ISSUE TITLE
IPython prompt doesn't take into account modifications to an imported functions

### ISSUE THREAD

**Issue by h4k1m0u** [spyder-ide/spyder#3290]
## Description of your problem
I' m not sure this is really a spyder bug, as it's caused in fact by the `IPython` prompt included with it. I have a python function that I import on the `IPython` prompt normally (`import <name-of-module>`) and execute that function. Then, I modify the function and save the edited python script. But, the modifications are not taken into account even if I re-import the module again. The only way to make `IPython` consider the modifications is by closing the python prompt and opening another one.

**What steps will reproduce the problem?**

1. First I import the needed function/module on the `IPython` prompt (bottom-right corner).
2. If I modify the script and save it (and even re-import the modified function).
3. The modifications are not taken into account until I close the `IPython` prompt and and I open a new console (right click > Open a new console).

**What is the expected output? What do you see instead?**
I expected that if I imported the needed function, the modifications should be taken into account without having to close the prompt and opening another one. A simple re-import of the module/function should be enough.

**Please provide any additional information below**
None.

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 2.7.11 (Installed with Anaconda)
* Operating system: Windows 7 (64bits)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.4.3 (OK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
You need to run your file with **F5** for your modifications to take place. Spyder has the logic to do this, but the only to make this happen is by running your file again :-)

**Comment by h4k1m0u** [comment]
@ccordoba12 This file is actually just a module (a list of functions) with no `__main__` inside. So I need just a way to make the prompt consider the new modifications. Also, using **F5** doesn't really fix the problem I'm facing.
