### ISSUE TITLE
F9 does not auto advance when it's at the last line

### ISSUE THREAD

**Issue by LaDilettante** [spyder-ide/spyder#3293]
## Description of your problem

**What steps will reproduce the problem?**

When the cursor is at the last line of code, F9 will execute that line but does not advance to a new (blank) line

**What is the expected output? What do you see instead?**

F9 should always advance to the new blank line given the interactive data analysis workflow. I expect to be able to write new line of code, hit F9 to execute and advance to a new line at the same time. (Rstudio also has this behavior).

Currently, the analyst has to write, hit Enter to advance to a new line, then after a while go back to execute all the lines that have just been written. The third step is unnecessary and breaks the workflow.

## Versions and main components

* Spyder Version: 3.0 beta
* Python Version: 2.7
* Operating system: Ubuntu 14.04

**Comment by ccordoba12** [comment]
Just to be clear: what you're asking us to do is to make **F9** to create a new, empty line when the cursor is at the last line of a file?

**Comment by LaDilettante** [comment]
Yes! And thanks so much for making F9 auto-advance. It single-handedly convert me to use Spyder regularly.

**Comment by jitseniesen** [comment]
Makes sense to me, though maybe we should change it to: make **F9** create a new, empty line when the cursor is at the last line of a file, _if that line is non-empty_.

That should not make a difference in the situation that you are thinking of, where you are writing a script and executing it at the same time. 

However, when you are executing line-by-line a script that is already written (which is the situation we were thinking of when implementing the auto-advance), you probably don't want extra lines added to it when you hit **F9** too often.

**Comment by LaDilettante** [comment]
@jitseniesen That's even better!

**Comment by ccordoba12** [comment]
@jitseniesen, could you work on this one?
