### ISSUE TITLE
Pressing Ctrl+P twice opens file switcher twice

### ISSUE THREAD

**Issue by pitrou** [spyder-ide/spyder#3297]
## Description of your problem

**What steps will reproduce the problem?**

1. Press Ctrl-P
2. Press Ctrl-P again

**What is the expected output? What do you see instead?**

The first Ctrl-P opens the selection pop up. The second Ctrl-P should (preferably) close it while open, or at least do nothing. Instead, it seems a second pop up is opened over the first one (you then have to press Esc twice to close both of them).

## Versions and main components

* Spyder Version: Spyder 3.0.0.dev0 (from `spyder-ide` conda channel)
* Python Version: 3.5.2
* Operating system: Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting @pitrou! I verified that the error is present in master.

**Comment by Nodd** [comment]
You need to focus dockwidgets more often than closing them. The popup on the other hand in constantly being shown and hidden, so I feel it's a more natural choice to toggle it with the shortcut.

**Comment by ccordoba12** [comment]
> I feel it's a more natural choice to toggle it with the shortcut

I agree with @Nodd on this one. Pressing Ctrl+P should toggle the switcher between visible and hidden.
