### ISSUE TITLE
Spyder Launching Problem

### ISSUE THREAD

**Issue by AsifAhmad100** [spyder-ide/spyder#3299]
Hello everyone

I have been using spyder for several months but suddenly it got stuck and cannot start from anywhere.
I have reinstalled anaconda but the problem still persists...
Whenever i enter the spyder command i get the following error

![capture](https://cloud.githubusercontent.com/assets/20512109/16910951/8be23b1e-4c90-11e6-8a2e-30bcecd07292.JPG)

Please help me with this problem.........

## Versions and main components

* Spyder Version:     Anaconda-2.0.1-Windows-x86

* Operating system: Windows 8.1 64 bit

**Comment by Nodd** [comment]
The last anaconda version is 4.1.1, you've indicated 2.0.1 so it's really outdated. Also you didn't provide the spyder version itself (try `conda list spyder`).
In any case the best advice I can give you is to update your spyder version. You'll get all the new features and bug corrections.

**Comment by AsifAhmad100** [comment]
Dear Nodd , thank you very much for your reply

but I reinstalled another version, python (x,y) 2.7.10.0 and tried to launch spyder and got the following error

![capture2](https://cloud.githubusercontent.com/assets/20512109/16924078/51b2cc1e-4cd2-11e6-96ae-736f770c35c3.JPG)

Then i reset spyder but still i get the same error 
How can i fix this problem...

**Comment by AsifAhmad100** [comment]
Spyder resetting worked............

Problem SOlved....................
