### ISSUE TITLE
Enter Key Not Work After Restarting Kernel 

### ISSUE THREAD

**Issue by myhlivecom** [spyder-ide/spyder#3301]
My environment is:
Windows 10 64-bit build 10586
Python 3.5.2 | Anaconda custom (64-bit)
IPython 5.0.0
Spyder 2.3.8

I found a problem in Spyder IPython console: if you restart the IPython kernel of the Spyder console window by e.g., Ctrl+., then you will not able to run Python code by pressing Enter key in the console. Please fix this bug.

**Comment by Nodd** [comment]
Thanks for your report. This problem is already know, as you can see in #2696. It will be fixed in the next release.
