### ISSUE TITLE
ImportError: cannot import name CONF

### ISSUE THREAD

**Issue by tokey66363** [spyder-ide/spyder#3303]
## Description of your problem
i tried to run spyder from terminal ,report errors:
"from spyderlib.config import CONF 
ImportError: cannot import name CONF"

**What steps will reproduce the problem?**

1. downloaded spyder-3.0.0b2 from https://bitbucket.org/spyder-ide/spyderlib/downloads/
2. unzip spyder-3.0.0b2.zip , cd pyder-3.0.0b2, python2.7 setup.py install
 
**Please provide any additional information below**
"import spyderlib.config"  works

## Versions and main components

* Spyder Version: spyder-3.0.0b2
* Python Version: python2.7.9
* Operating system:  centos6.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
Do you get the same error with the latest version (3.0.0b4)?

**Comment by ccordoba12** [comment]
Please run

    pip install --pre spyder

to update Spyder to its latest beta (which is `beta4`). Source installations (i.e. `python setup.py install`) are not supported anymore, unless you install all our dependencies by hand.

**Comment by tokey66363** [comment]
@jitseniesen  @ccordoba12 Thanks for the fast reply.
I updated Spyder to  3.0.0b4, but still can't run spyder ,an error ocurred
"Segmentation fault (core dumped)"
