### ISSUE TITLE
FakeVim

### ISSUE THREAD

**Issue by Zaharid** [spyder-ide/spyder#3304]
Hi,

I noticed you are adding some preliminary vim style editing in the upcoming release of Spyder. I was wondering if it would be feasible to use something like FakeVim:

https://github.com/hluk/FakeVim

This works very well in QtCreator, and does neat things like reading the default .vimrc file,  allowing search or block text selection.

Thanks.

**Comment by ccordoba12** [comment]
This is very interesting, thanks for letting us know about it. However, the Vim integration is provided by an external plugin:

https://github.com/spyder-ide/spyder.vim

So please report this issue there ;-)
