### ISSUE TITLE
Can't seem to use T4Agg matplotlib backend

### ISSUE THREAD

**Issue by dasalz1** [spyder-ide/spyder#3311]
## Description of your problem
I am trying to integrate a matplotlib graph with Tkinter, but it seems that using the TkAgg backend creates an unresponsive window. I am using the newest version of anaconda and newest version of spyder on windows 10.

Code:
import matplotlib
matplotlib.use('TkAgg')

from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
from matplotlib.backend_bases import key_press_handler
from matplotlib import pyplot
import numpy
import matplotlib

import Tkinter

window = Tkinter.Tk()
window.wm_title('Graph in GUI')

x = numpy.linspace(1,1000,999)
y = numpy.linspace(1, 1000, 999)

figure = pyplot.figure()
pyplot.plot(x, y, 'bo-')
canvas = FigureCanvasT4Agg(figure, master = window)
canvas.show()
canvas.get_tk_widget().pack(side = Tkinter.TOP, fill = Tkinter.BOTH, expand = 1)

toolbar = NavigationToolbar2T4Agg(canvas, window)
toolbar.update()
canvas._tkcanvas.pack(side = Tkinter.TOP, fill = Tkinter.BOTH, expand = 1)

def button_press(event):
    key_press_handler(event, canvas, toolbar)
    
canvas.mpl_connect('key_press_event', button_press)

def _quit():
    window.quit()
    window.destroy()

button = Tkinter.Button(master = window, text = 'Quit', command =_quit)
button.pack(side = Tkinter.BOTTOM)

Tkinter.mainloop()

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: Python 2.7
* Operating system: Windows 10
* Anaconda Version: 1.2.2

## Dependencies

IPython >=1.0      :  4.1.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with Anaconda, i.e. TkAgg can't be used with Anaconda on Windows.

As far as I know, there's no one working to fix this problem :-/
