### ISSUE TITLE
search/replace backslash in code Editor. Backslash disapears.

### ISSUE THREAD

**Issue by thierryBottaro** [spyder-ide/spyder#3316]
**What steps will reproduce the problem?**

1. "Ctrl + F" (or "Ctrl + H")
2. type \ in the search box
3. type F3

**What is the expected output? What do you see instead?**
I would expect that the next \ is searched/replaced.
instead, the \ disapear from the search box, which stop the search.

## Versions and main components

* Spyder Version: 3.0.0dev  (Oh, I though I had a regular version !)
* Python Version: 3.5.1 64bit
* Operating system: Windows 7 64bit

## Dependencies
I have a bad dependency : jedi 0.9 is too high according to the dependency checker
jedi; >=0.8.1;<0.9.0 ; installed=0,9;  (Experimental) Editor's code completion, go-to-definition and help

**Comment by Nodd** [comment]
Thank you for your report ! There is alredy an existing issue about it (#3141) so I'll close this one.
