### ISSUE TITLE
No shortcuts displayed for plugins

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3321]
Now that #3300 reenables correct plugin loading, I notice that shortcuts are not displayed in the menus for some plugins. For me the shortcut is shown for breakpoints, but not for pylint or profiler. The 3 of them have configurable shorcuts, and I noticed no difference between the declarations.

For my other external plugins which use fixed shortcuts, the shortcuts are not displayed either.

BTW API-wise, in both cases it feels strange to define the actions separately from the shortcuts.

**Comment by NGJROMO** [comment]
Hi,

Found your post when I could not find the profiler in Spyder after upgrading to 3.0.0b4. Is there any way, right now, that I can still use the shortcuts that you mention?

**Comment by ccordoba12** [comment]
@NGJROMO, the profiler was not packaged as part of beta4. This was our mistake, and it was already fixed in #3300 :-)

**Comment by NGJROMO** [comment]
Right, thanks for the quick answer. I'll look forward to it coming back in beta5 then. Any ETA for that or do you recommend downgrading to beta3 if I need the profiler?

**Comment by ccordoba12** [comment]
@Nodd, I'm not seeing this problem on Linux. Could you post your installation details?

**Comment by jitseniesen** [comment]
I also don't see a problem with pylint or profiler. For external plugins with fixed shortcuts: they are displayed if the shortcut is configured in `utils.qthelpers.create_action()`, as done [here](https://github.com/jitseniesen/spyder.unittest/blob/067a528bf3b2dc52b19053a0a6d8fa24712eaafd/spyder_unittesting/unittesting.py#L66), but I can't get it to work using `config.gui.fixed_shortcut()`, see e.g. [here](https://github.com/jitseniesen/spyder.unittest/blob/afb3cb3988612b1446bf1d8c805f768c827a4da2/spyder_unittesting/unittesting.py#L71). In fact, the first method seems cleaner anyway.
