### ISSUE TITLE
no attribute 'PYQT_VERSION'

### ISSUE THREAD

**Issue by lxkain** [spyder-ide/spyder#3326]
## Description of your problem

**What steps will reproduce the problem?**

1. upgrade to latest conda packages
2. git pull latest spyder code (Revision ddec622)
3. python bootstrap.py

**What is the expected output? What do you see instead?**

Expecting boot splash, instead:

$ python bootstrap.py 
Executing Spyder from source checkout
Revision ddec622, Branch: master
01. Patched sys.path with /Users/kain/spyder
02. PyQt4 is detected, selecting
Traceback (most recent call last):
  File "bootstrap.py", line 140, in <module>
    versions = get_versions(reporev=False)
  File "/Users/kain/spyder/spyderlib/__init__.py", line 86, in get_versions
    'qt_api_ver': qtpy.PYQT_VERSION,
AttributeError: 'module' object has no attribute 'PYQT_VERSION'

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3beta
* Python Version: 3.5
* Operating system: OSX

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by Nodd** [comment]
You need to update qtpy.

**Comment by lxkain** [comment]
Upgrading from 1.0.2 -> 1.1.1 fixed it, thank you. Thank you for a great editor!
