### ISSUE TITLE
Drag and drop from OS file explorer is not working

### ISSUE THREAD

**Issue by dacoex** [spyder-ide/spyder#3327]
## No drag & drop / no function linking

**What steps will reproduce the problem?**

1. conda install -c spyder-ide spyder==3.0.0b4
2. open Spyder
3. try drag&drop a file from Windows explorer into the editor
4. inside any file, CTRL+mounseclick on a function to jump to its definiton

**What is the expected output? What do you see instead?**

for (3): file is not loaded in the editor
for (4): the jump to the definition doe not occur

**Please provide any additional information below**

## Versions and main components

* Spyder Version: see above, 3.0.0beta
* Python Version: 3.5
* Operating system: Windows 7

## Dependencies

```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting this problem. I noticed it too and I don't know when this stopped to work ;-)

We'll fix for beta5.

**Comment by dacoex** [comment]
I just saw you scipy talk. Man, you guys rock! Virtual environment management in spyder. Keep up your good work & spirit!

**Comment by ccordoba12** [comment]
Thanks!

**Comment by dacoex** [comment]
confirm solved in v3 beta 5
