### ISSUE TITLE
It seems the kernel died unexpectedly. Use 'Restart kernel' to continue using this console.

### ISSUE THREAD

**Issue by sumitvasie** [spyder-ide/spyder#3328]
I wrote a code just to read an image and display it on to the highgui window. But i get this "Kernel died unexpectedly " everytime.
I also tried to run the code from python console from the terminal but it says 
"
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /home/sumit/Documents/Software/Opencv3.0.0/opencv-3.0.0/modules/highgui/src/window.cpp, line 279
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /home/xyz/Documents/Software/Opencv3.0.0/opencv-3.0.0/modules/highgui/src/window.cpp:279: error: (-215) size.width>0 && size.height>0 in function imshow
"
My platform of work is :
* Spyder Version:2.3.9
* Python Version:2.7
* Operating system:ubuntu 16.04
* Opencv 3.0.0
Kindly provide any solution in this issue.

**Comment by ccordoba12** [comment]
This seems an error with your program, not with Spyder.

**Comment by ccordoba12** [comment]
> I also tried to run the code from python console from the terminal but it says

This is clearly an error with your program or with the way you compiled OpenCV.

Sorry, but since this is not a Spyder error, I'm closing this issue.

**Comment by sumitvasie** [comment]
i changed my opencv to 2.4.9 . I ran the code:: 
import cv2
Inputimg = cv2.imread("test.png",0)
cv2.imshow("InputImg",Inputimg)
cv2.waitKey(0)

when i ran the code it runs successfully but only once. I cannot close my imshow window.
I forcefully closed the window. When again i ran the code it says "KERNEL DIED UNEXPECTEDLY, RESTART KERNEL".
Dont know whats going on.
