### ISSUE TITLE
Spyder 2.3.8, runs wrong tab

### ISSUE THREAD

**Issue by IVIUPPET** [spyder-ide/spyder#3341]
Hi,

Just reporting that I have had spyder run the first tab when running code for the first time, regardless of which tab is selected.  this didn't bother me too much

But more recenlty I am noticing it runs the tab open in a window not selected (my library full of functions on the other screen) instead of the one I am selecting which is the main body of my program. If I click the intended window/tab repeatedly then hit run, sometimes it runs the correct program, other times, it still runs the library open in the other window. 
![image](https://cloud.githubusercontent.com/assets/11202315/17369884/0e9c5e8e-5968-11e6-95c5-5fdff1345269.png)

**Comment by ccordoba12** [comment]
Closing because Spyder 2.3 is not supported anymore.

**Comment by sayboltm** [comment]
Which is a shame because this version works better than the latest 3.1.3 and much better than 3.1.2 which never shows variables. 3.1.3 shows variables sometimes when in debug mode, but then they stay out of date, leading to confusion.
