### ISSUE TITLE
iPython cell magics not working, Spyder 3 beta

### ISSUE THREAD

**Issue by oguzhanogreden** [spyder-ide/spyder#3343]
I can not get various cell magics to work. It seems that iPython console does not notice that if I enter a newline after an empty line, it should run the input. For instance see the example [here.](http://ipython.readthedocs.io/en/stable/interactive/magics.html?highlight=cell%20magic#cellmagic-script). I have also tried `%%capture` and that did not work either.

**What steps will reproduce the problem?**
1. Running the example above in iPython console.

**What is the expected output? What do you see instead?**

Since this is a cell magic, I expect the console to allow me to write multiline code and whenever I enter two newlines, second newline should execute (as is with Python's control flow tools). However it keeps on expecting input.
## Versions and main components
- Spyder Version: 3.0.0.dev0
- Python Version: Python 2.7.12 64 bits
- Operating system: Windows 10
## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

I would like to note that I am willing to try and locate (and perhaps fix) this issue myself. In case someone can reproduce this and think this can be handled by someone who's willing to get familiar with Spyder's code base, please feel free to guide me to relevant part of the source!

**Comment by ccordoba12** [comment]
We'll take a look at this one after we release 3.0 :-)

**Comment by ccordoba12** [comment]
Closing because nobody else has reported this bug.

**Comment by stsmall** [comment]
Hi,
I thought I would ask  @oguzhanogreden about this issue since I am also having the same problem he posted above. To reiterate, when I type a magic command, e.g., %%cython, spyder does not recognize the 2nd new line as execute and continues to wait for input.
I am running spyder 3.2.3 in python 3.6
thank you
