### ISSUE TITLE
Spyder 3.0.0b4 does not scale properly with 4K display

### ISSUE THREAD

**Issue by rhenley** [spyder-ide/spyder#3347]
## Description of your problem

**What steps will reproduce the problem?**

1.  Have 4K display
2.  Install Python from winpython or anaconda
3.  Have Qt5, PyQt5, and spyder3
4. Start Spyder

**What is the expected output? What do you see instead?**
Spyder does not scale properly with the dpi and text is unreadably small

**Please provide any additional information below**
I've been using spyder for a very long time, recently I bought a razer blade stealth and spyder has been pretty much unusable for me due to scaling issues. I've tried multiple distributions as well as installing and trying linux. Seems to just be an issue of spyder+4K display

## Versions and main components

* Spyder Version: 3.0.0b4
* Python Version: 3.5.2
* Operating system: Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting, but this was already fixed in pull request #3333 and it will be part of beta5 :-)
