### ISSUE TITLE
Feature suggestion:  add option to turn scroll cells in editor off

### ISSUE THREAD

**Issue by siyideng** [spyder-ide/spyder#3348]
Currently if there are multiple cells in the source file (created with #%%) and a cell has focus, then scrolling will become cell-based instead of line-based. This is becoming really counterintuitive and hard to keep focus, especially if you have long cell sections. Please at least add an option to turn this "feature" off.

**Comment by ccordoba12** [comment]
There is already an option to turn on/off cell highlighting in

    Tools > Preferences > Editor > Highlight current cell
