### ISSUE TITLE
I can't connect to vcXsrv server

### ISSUE THREAD

**Issue by adonese** [spyder-ide/spyder#3349]
I've tried to use Bash instead of Command Line on Spyder but Spyder by default set the command line to be the default shell, and there is no way to specify others.  So I've tried to launch Bash from CMD --which work just fine-- but it didn't work when I did it on Spyder.

It'd be great if you let users to select what the shell that they want to use by specifying it's directory, i.e., ``C:\Windows\System32\bash.exe``.

The error I got when I launched the bash from cmd on Spyder is ``ERROR 0x80070057``

**Comment by ccordoba12** [comment]
Bash is not supported in the console provided by Spyder on Windows, and I doubt it ever will.
