### ISSUE TITLE
Code Completion for function parameters doesn't work in IPython Console (3.0.0b4)

### ISSUE THREAD

**Issue by tschoenf** [spyder-ide/spyder#3350]
## Description of your problem

When calling a function in an IPython console, code completion does not work inside the function brackets.

**What steps will reproduce the problem?**
1. Write any function call inside an IPython console.
2. Inside the function brackets, try code completion (with TAB or CTRL+SPACE) for any function parameter.

**What is the expected output? What do you see instead?**
Instead of showing possible completions of the started code snippet, nothing happens.

**Please provide any additional information below**

In the latest stable release, this issue does not occur. Also, this seems to be a problem only with IPython. In the normal python console, completion works just fine.
## Versions and main components
- Spyder Version: 3.0.0b4
- Python Version: 3.5.2
- Operating system: Windows 7
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by goanpeca** [comment]
This does not apply anymore. Closing.
