### ISSUE TITLE
Spyder not opening because of problems with spyder.lock

### ISSUE THREAD

**Issue by KirkLab** [spyder-ide/spyder#3351]
This issue happened abruptly, and I have no idea what caused it to occur.  spyder has ceased to open from anaconda for me.  when I try to launch it, the icon highlights in the dock, but then no window for spyder opens.  I tried using "spyder --reset" from the command line, and cmd returns that "spyder is already running".  when i tried to kill spyder/python from cmd (and all child instances as well) computer shows no record of either running.  The only way I have been able to open the spyder IDE is by running spyder --new-instance from cmd.  

I have uninstalled, and reinstalled, anaconda twice to try and fix this.  Same thing keeps happening with the spyder IDE after reinstallation.  

Does anyone have any ideas on what would have caused this?  Any thoughts on what to do to fix (given that uninstalling hasn't worked)???

**Comment by ccordoba12** [comment]
To solve this problem, please go to your `Users` directory on Windows/Mac, or your `home` directory on Linux, locate a folder called `.spyder2` (notice the dot at the beginning of it) and delete it.

That should fix your problem :-)

**Comment by ccordoba12** [comment]
Note to self: a solution to this problem is making `spyder --reset` to delete `spyder.lock`, something that (I think) we are not doing at the moment.

**Comment by KirkLab** [comment]
deleting '.spyder2' fixed it! Thanks!  I deleted all remaining files after uninstalling; I don't know why it didn't catch this folder.  

spyder is the best ide ever.

**Comment by armarvin** [comment]
I am running OSX El Capitan and Spyder 2.3.9.  I am having the same problem as described by KirkLab.  I do not seem to have a folder named .spyder2 so that fix is not working.  Could the problematic file be located elsewhere?  Thank you.

**Comment by ccordoba12** [comment]
No, it's not. .spyder2 is not a file, is a directory, and in your case 
it should be located in

      /Users/<name>/.spyder2

or

/Users/<name>/.spyder2-py3

if you are using Python 3. Here <name> is your user name.

**Comment by ggarcia0610** [comment]
Hi @ccordoba12,

I also have a problem launching the spyder IDE.
When I run spyder on my terminal, I get below message:
#spyder 
Spyder: cannot connect to X server

Below is my spyder version along with python running under Linux CentOS 6.8.
I have read some articles about this issue but still couldn't fix the problem.

[] Troubleshooting done:
- ran spyder then I get this message (Spyder: cannot connect to X server)
- ran spyder --reset then same message I get (Spyder: cannot connect to X server)
- ran spyder --new-instance then same message I get (Spyder: cannot connect to X server)
- Uninstall then re-install spyder
- removed .spyder2 directory that's being created when I ran spyder command.


=== spyder and python version ===
# conda list spyder
# packages in environment at /usr/local/anaconda2:
#
Using Anaconda Cloud api site https://api.anaconda.org
spyder                    2.3.9                    py27_0


# python --version
Python 2.7.12 :: Anaconda 4.1.1 (64-bit)

# python3 --version
Python 3.6.3


Thank you in advance for the help.

**Comment by danmachen** [comment]
I have the same issue running in Windows. here is what i have observed.

1 - I delete .spyder folder (& hence subfolder spyder.lock) from /user/home drive.
2 - On running spyder.exe afterwards the same .spyder folder is created with a subfolder called spyder.lock each time.
3 - How can I prevent spyder.lock from being created on execution?

**Comment by MinakshiGIMT** [comment]
After uninstalling and installing again I have not able to open Anaconda and Spyder IDE in my Windows 8 machine. Can anybody help ?
