### ISSUE TITLE
Use a typographic web font for Outline Explorer icons

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#3358]
@goanpeca and me are dissatisfied with the current icons for classes, methods and functions that appear in the code completion widget and also in the file switcher dialog. They don't render very well and are hard to read.

One possible solution is to use a typographic web font to replace those icons by the letters provided by that font. So in the same way as we do now, we could have the following letters instead of our current icons:
- **f** for functions
- **C** for classes
- **M** for modules
- **m** for methods
- **--** or **p** for private methods

This is a list of pretty awesome web fonts to use:

http://www.awwwards.com/20-best-web-fonts-from-google-web-fonts-and-font-face.html

See for example _Fontin_ there :-)

---

@SylvainCorlay, can we make this work in QtAwesome or `icon_manager`?

**Comment by SylvainCorlay** [comment]
I think that it would mostly be in `icon_manager`. In the choice of the font, we will need to be careful about pixel perfection at small sizes.

**Comment by ccordoba12** [comment]
@SylvainCorlay, could you work on this and have a prototype for next week or two weeks at most? I think Spyder 3.0 is looking pretty good, and this will improve things even more :-)

**Comment by ccordoba12** [comment]
Here are some fonts that look good at small sizes:

https://fonts.google.com/?selection.family=Baloo+Da|Black+Ops+One|Fredoka+One|Righteous&category=Display

The name of my preferred fonts is in the URL :-)

**Comment by SylvainCorlay** [comment]
Hi all, I will do this next week.

**Comment by ccordoba12** [comment]
Thanks Sylvain!

**Comment by ccordoba12** [comment]
Hey @SylvainCorlay, how is this one going? I plan to release beta7 (the last beta for 3.0) at the end of the week.

After that I'll only accept translation updates before releasing 3.0 final :-)

**Comment by ccordoba12** [comment]
This is going to be fixed when we add a dark theme, so I'm closing it as a duplicate of issue #2350.
