### ISSUE TITLE
Spyder window reset not working

### ISSUE THREAD

**Issue by KirkLab** [spyder-ide/spyder#3360]
## Description of your problem
I played around with the window settings in Spyder, and now that I'm trying to revert back to the default window settings, when I go to View -> Reset window layout, nothing happens; the windows do not revert back to the default setting.  

**What steps will reproduce the problem?**
N/A
1. 
2. 
3. 

**What is the expected output? What do you see instead?**
N/A

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 3.5
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
This was fixed already in Spyder 3.0beta4. For now you just need to run in a terminal

    spyder --reset

to go back to the defaults.
