### ISSUE TITLE
new file default line endings regardless of OS

### ISSUE THREAD

**Issue by scienceopen** [spyder-ide/spyder#3361]
## Want ability to force line ending selection on newly created files

**What steps will reproduce the problem?**

1. create new file on Windows
2. new file has DOS line endings
3. people on Mac and Linux get confused and git commits of code have needless line ending conversion commits

## Versions and main components

* Spyder Version: 2.3.9 and 3.0.0dev
* Python Version: 3.5, 2.7
* Operating system: Windows 10, Linux

**Comment by Nodd** [comment]
Git can be configured to manage line endings correctly. This parameter can be changed when installing git on windows, and it does the right thing by default.
It would be even more surprising for lots of users on windows if windows convetions where not respected.

**Comment by scienceopen** [comment]
I suppose--I like to be able to execute on Linux by 
./myfile.py

but if it has windows line endings, I get a bizarre error message. 

So I will use insert into my repos a
.gitattributes
containing
```
*.py text eol=lf
```
