### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by LarryC42** [spyder-ide/spyder#3364]
On high DPI screens navigator is mostly unusable.  In Spyder it can be configured fairly well with the exception of the Object Inspector.  On each launch you have to zoom in multiple times to make the screen readable.

Variable explorer the headings get chopped cut off.  They're readable though.

Even more interesting, when Spyder is moved from a high DPI screen to a normal DPI screen, it retains the original settings.

I've attached what object inspector looks like.  It would be nice 1) if the zoom was remembered or 2) there were a hot key to zoom in.

None of these issues render it unusable, just cumbersome in those cases.

![objectinspector](https://cloud.githubusercontent.com/assets/5050690/17831774/9e6f75cc-66c0-11e6-95f0-b236bd3affa5.png)

**Comment by Nodd** [comment]
We need more informations to help you, as stated in the issue template. The easiest way to do it is to open a new issue from spyder's help menu. Thanks.

**Comment by ccordoba12** [comment]
This is already fixed in master and will be part of Spyder 3.0
