### ISSUE TITLE
Error Occurs for one user but not another - TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by JLRSLK** [spyder-ide/spyder#3371]
This short piece of code works fine on my computer (Spyder - version 2.3.9) but not my colleagues (Spyder -version 2.3.8). It also works on the command line on my colleagues computer:

import os 

FilePath = r'P:\PT\PT-8\PT-81\Team\enewlyn\Delete Test'

os.chdir(FilePath)
os.remove("ChangedFile.csv")
print("File Removed!")

#####

runfile('C:/Users/enewlyn/untitled1.py', wdir='C:/Users/enewlyn')
Traceback (most recent call last):

  File "<ipython-input-40-da67d77dbecd>", line 1, in <module>
    runfile('C:/Users/enewlyn/untitled1.py', wdir='C:/Users/enewlyn')

  File "C:\Users\enewlyn\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 698, in runfile
    os.chdir(wdir)

TypeError: 'str' object is not callable

**Comment by Nodd** [comment]
Can you try to update you colleague's version maybe ?

**Comment by JLRSLK** [comment]
Updating did fix the issue.  Thanks.

**Comment by ccordoba12** [comment]
Good to know!!
