### ISSUE TITLE
Auto-Completion issues in Anaconda Python 2.7

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3372]
## Description of your problem
Just after installation of Anaconda Python 2.7, for win64 bits,
launching Spyder, Auto-completion does not work.

Setup is Python 2.7.12 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Windows

**What steps will reproduce the problem?**
1.  Just installed  Anaconda Python 2.7, for win64 bits,

**What is the expected output? What do you see instead?**
SOLUTION
https://github.com/ContinuumIO/anaconda-issues/issues/768

Install JEDI 0.8.1

pip install jedi=0.8.1

## Versions and main components

* Spyder Version:  2.3.9
* Python Version: 2.7
* Operating system:
Python 2.7.12 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Jedi 0.9.0 support was added for Spyder 3.0 only. Sorry, but we can't make it work for Spyder 2.3.9 because of technical limitations.
