### ISSUE TITLE
spyder tutorial does not show images

### ISSUE THREAD

**Issue by culinovic** [spyder-ide/spyder#3373]
Spyder 2.3.9 installd via Anaconda 4.1.6 64bit on Windows 10 64bit
does not show images in Spyder tutorial launched via "Help"->"Spider tutorial" in Object Inspector.
It shows only question mark icon in frame, in place of image.

**Comment by ccordoba12** [comment]
This was fixed in master already and will be part of Spyder 3.0.

Sorry for the hassle ;-)
