### ISSUE TITLE
%matplotlib osx is ignored

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#3375]
## Description of your problem

**What steps will reproduce the problem?**
1. plot anything with matplotlib
   -displayed inline
2. type in the ipython console : `%matplotlib osx` and replot
   -displayed inline
3. type in the ipython console : `%matplotlib osx` and replot
   -displayed in a window

**What is the expected output? What do you see instead?**

Why Do I need to type `%matplotlib osx` twice?

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 3b5
- Python Version: Python 3.5.2 64bits, Qt 5.5.1, PyQt5 5.5.1 on Darwin
## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I think that backend is going to be removed (if not already) in Matplotlib, sorry.

**Comment by impact27** [comment]
Ok sure but I have the same issue with qt5:
% matplotlib qt5 doesn't work, I have to do it twice!
I will check that again

**Comment by impact27** [comment]
It is still the case. Should I open a new Issue?

```
import matplotlib.pyplot as plt
%matplotlib qt5
plt.plot(range(10))
#Diplayed in windows
```

```
import matplotlib.pyplot as plt
plt.plot(range(10))
#Diplayed inline
%matplotlib qt5
plt.plot(range(10))
#Diplayed inline
%matplotlib qt5
plt.plot(range(10))
#Diplayed in windows
```

**Comment by ccordoba12** [comment]
Yep, this is still the case and there's an issue about it (#4002)
