### ISSUE TITLE
New Features:  Save Session, Save Spydata

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3378]
It would be very very useful to add those simple features

1) Save Session WITHOUT exiting Spyder  (so we can just add a file we want).
    Just a "Save Session"

2) Option to Save Session + Spydata into a single file:  
    We can reload the full work at later time easily or transfer the work to another session/persons/....

3) Ability to save the memory of IPtyhon session (ie functions loaded in memory) along with data.
    So, a full complete session can be serialized/reload after (like a sleep mode).

Thanks very much for maintaining Spyder, the most useful project on earth...

**Comment by ccordoba12** [comment]
Session saving is already implemented as part of PR #3377. Saving spydata is for a future release, but we are aware it'd be really useful :-)
