### ISSUE TITLE
Spyder dont start | Win 10 fresh python 3.5.2 install

### ISSUE THREAD

**Issue by DPSB** [spyder-ide/spyder#3379]
## Description of your problem
IDE does not start 
**What steps will reproduce the problem?**

1. Take a Win 10 x64 PC
2. Install python 3.5.2
3. Install spyder via administrative cmd
("python -m pip install -pre spyder)
4. Installation will fail, because you have to upgrade pip
5. Upgrade it and remove old spyder content
6. ("python -m pip uninstall spyder")
7. Accept with "y"
9. Install spyder via administrative cmd
("python -m pip install -pre spyder)
10. After Installation is done (installation finished successfull), enter "spyder" to open IDE

*What is the expected output? What do you see instead?**
-> Nothing happens, IDE not starting

**Please provide any additional information below**
!!FIX!!
1. Uninstall spyder via administative cmd
("python -m pip uninstall spyder")
2. Accept with "y"
3. Install pyqt5
("python -m pip install pyqt5")
4. Install spyder
("python -m pip install --pre spyder")

I used the "--pre" option because last stable version cant be installed. 
(because pyside does not support python 3.5)

## Versions and main components
* Spyder Version:3.0.0.b5
* Python Version: 3.5.2
* Operating system:Win 10 Home x64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This is all documented in our [README](https://github.com/spyder-ide/spyder/blob/master/README.md) and our [Release page](https://github.com/spyder-ide/spyder/releases)

1. Our wheels don't install the PyQt5 wheel because Spyder can work with both PyQt4 or PyQt5.
2. You need to use `pip install --pre spyder` to install our beta version.
