### ISSUE TITLE
DatetimeIndex types are not visible in the Variable Explorer

### ISSUE THREAD

**Issue by surfmaverick** [spyder-ide/spyder#3380]
### snippet

import pandas as pd
rng = pd.date_range('10/1/2016', periods=25, freq='bq')
### end snippet

**Matrix above is not violable in variable explorer.**
## Description

**What steps will reproduce the problem?**
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.9 
- Python Version: 3.5.1
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  3.4.2 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by ccordoba12** [comment]
@jitseniesen, maybe you want to take a look at this one :-)

**Comment by jitseniesen** [comment]
@surfmaverick This type is not supported by the variable explorer, and by default such variables are not shown. You can change that by clicking on the settings button (cogwheel icon) in the variable explorer and turning off 'Exclude unsupported types', but you won't get a lot of information.

Adding support for it shouldn't be too hard. It is basically an array of time stamps and we can display time stamps in the variable explorer. Feel free to have a go at it yourself. If you wait for us to fix it, it may take a while :-)
