### ISSUE TITLE
Spyder 3.0.0b5 crashes when choosing layout

### ISSUE THREAD

**Issue by vmuriart** [spyder-ide/spyder#3382]
## Description of your problem
`Spyder 3.0.0b5` crashes when choosing layout other than *Spyder default layout*. 
**What steps will reproduce the problem?**

1. Click View
2. Window Layout
3. Matlab Layout

**What is the expected output? What do you see instead?**
Expect a new layout. Instead spyder crashes, and upon restart it still has the old layout. 

**Please provide any additional information below**

![error_layout](https://cloud.githubusercontent.com/assets/13303020/18039234/a01fa112-6d55-11e6-8f27-d4b280e31302.PNG)

## Versions and main components

* Spyder Version: 3.0b5
* Python Version: 2.7.11
* Operating system: Windows 8.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by vmuriart** [comment]
This might be helpful, below is the error output when run from cli. 

`QWindowsWindow::setGeometry: Unable to set geometry 2402x1027+0+23 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1027+0+23 (frame: 8, 31, 8, 8, custom margin: 0, 0, 0, 0, minimum size: 2402x349, maximum size: 16777215x16777215).`

**Comment by vmuriart** [comment]
Issue seems to be resolved in  `v3.0beta6`

**Comment by ccordoba12** [comment]
Really glad to hear it!! One thing less to worry about :-)
