### ISSUE TITLE
Breakpoint bullets and TODO checkmarks displayed one line too high

### ISSUE THREAD

**Issue by wtheis** [spyder-ide/spyder#3384]
## Description

**What steps will reproduce the problem?**
1. Install spyder3.0.0b6
2. Generate a break point by double-clicking on line number in editor
3. And/or Type '# TODO something' into an editor line

**What is the expected output? What do you see instead?**

A bullet point and checkmark, respectively, should appear next to the line number _n_.
Instead it appears at line number (_n - 1_), i.e. one line higher up than expected.

**Please provide any additional information below**
## Version and main components
- Spyder Version: 3.0.0.dev0 
- Python Version: 3.5.1
- Qt Versions: 5.6.0, PyQt5 5.6 on Windows
## Dependencies

```
pyflakes >=0.6.0 :  1.1.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.1 (OK)
qtconsole >=4.2.0:  4.2.0 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
pandas >=0.13.1  :  0.18.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by wtheis** [comment]
To clarify:
The actual break point where the debugger stops is in the correct line (as double-clicked and highlighted in the editor when double-clicking). Only the bullet point is displayed incorrectly.

**Comment by ccordoba12** [comment]
Thanks for reporting. Since this is a minor bug, we're going to leave it for 3.1 :-)

**Comment by wtheis** [comment]
It also impacts on the warning and error icons. If you hover over these the tool tip with details is not displayed. Instead you have to hover over the space below the icon. Once you know, it's only a minor irritation but some users might not be able to figure out that the tool tip is available. 
(Is the first release version 3.1?)

**Comment by jitseniesen** [comment]
This issue does not appear on my computer (Spyder beta6, Python 3.5.2 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux Debian installed via Anaconda), so it may be specific to Qt5 and/or windows.

**Comment by ccordoba12** [comment]
> Is the first release version 3.1?

Nop, 3.1 will come after 3.0.

3.0 is about to be released and 3.1 will come in about 3 months.

**Comment by hahanbyul** [comment]
Is this issue solved? It didn't happen when I used older version, but the latest spyder still seems to suffer same problem.

**Comment by ccordoba12** [comment]
Nop, it hasn't.

**Comment by lmeyn** [comment]
Still an issue in Spyder 3.2.0, Anaconda Python 3.6.1 64bits, Qt 5.6.2, PyQt5 5.6 on Darwin.
The icons are half a line too high.

**Comment by ccordoba12** [comment]
@lmeyn, I think this is going to be fixed in 3.2.1. Please let us know if that's the case.

**Comment by jondo** [comment]
Is this still an issue on the master branch? But be aware of #7963 for testing.

**Comment by ccordoba12** [comment]
This was completely rewritten in Spyder 4, so it's probably not an issue anymore.
