### ISSUE TITLE
Spyder cannot start with Anaconda 64 bit Python = 3.4

### ISSUE THREAD

**Issue by yw5aj** [spyder-ide/spyder#3388]
## Description of your problem

**What steps will reproduce the problem?**

1. Create a new environment with `conda create -n py34 python=3.4 anaconda`
2. Start spyder by first do `activate py34` and then entering `spyder`

**What is the expected output? What do you see instead?**
Expected: spyder starts
What I saw: `python.exe has stopped working`

**Please provide any additional information below**
I tried to do `spyder --show-console` but nothing comes up (just a line `(py34) C:\Users\shwang spyder --show-console` haning there)

## Versions and main components

* Spyder Version: 2.3.9
* Python Version: 3.4.5
* Operating system: Windows 10 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by yw5aj** [comment]
Well... Upgrading to Spyder 3.0.0 beta6 worked for now :)

**Comment by goanpeca** [comment]
@ccordoba12

**Comment by ccordoba12** [comment]
This is a known error in Anaconda with Qt and Python 3.4 on Windows, so it's not really a Spyder problem.

Because of that I'm closing this issue :-)
