### ISSUE TITLE
can't connect to X server

### ISSUE THREAD

**Issue by cchu08** [spyder-ide/spyder#3389]
## Description of your problem
Everytime I run spyder from the command line it keeps giving me this error: "Spyder: cannot connect to X server"
**What steps will reproduce the problem?**

1. ~$ spyder
2.  Spyder: cannot connect to X server

I'm running Python 3.5 Anaconda on Windows Subsystem for Linux (Bash on Ubuntu on Windows)

**Comment by ccordoba12** [comment]
That's not a supported platform by us, sorry :-(

So you're on your own to make things work. Here are some tips to do it:

http://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/

**Comment by Khalilsqu** [comment]
It is working fine for me, just use 

better run run commands from cmd or powershell,
`bash`
`export DISPLAY=:0.0`
then type
`spyder`

i recommend using xming, 

I also installed anaconda distribution, so, spyder was already packed in.

my sys is windows 10. I am using WSL

**Comment by sylviankahane** [comment]
spyder with python 2.7 works.

spyder with python 3.x, a.k.a spyder3 does not, complains that the server (Xming) dors dot support Xinput 2
