### ISSUE TITLE
RuntimeError when using outline and split code editor

### ISSUE THREAD

**Issue by jpoeppel** [spyder-ide/spyder#3390]
## Description of your problem

I get a (non-critical since I can still continue working) `RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted` when right-clicking an item in the outline, when I previously split the editor and then closed the panel again. (I also got  `RuntimeError: wrapped C/C++ object of type BaseTabs has been deleted` once when doing similar steps as outlined below but I cannot reproduce that consistently now.)

**What steps will reproduce the problem?**
1. Open spyder (for me it does not matter if I have open files in my last sessions or not)
2. Create/open a file if none is open
3. Split editor (horizontally for me)
4. Close 2nd editor panel
5. Right click on a file in the outline section (I did have the outline section there at startup)

**What is the expected output? What do you see instead?**

I would expect to see nothing, but instead I get the mentioned error. The context menu on right-click does however appear, so I do not see/experience any negative effect of this bug

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 3.0.0b6
- Python Version: 2.7.6
- Operating system: Ubuntu 14.04.5 LTS
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.8.1 (OK)
matplotlib >=1.0 :  1.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.13.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. If this is not critical, we're going to leave it for 3.1 :-)

**Comment by jpoeppel** [comment]
I think that is fine. As I've said, I have not encountered any problems, appart from the fact that the error is printed in the internal console.
