### ISSUE TITLE
Add "Duplicate and rename" context option to the file explorer

### ISSUE THREAD

**Issue by goyou** [spyder-ide/spyder#3391]
Hello,
I think right-clicking on a file in the file explorer should provide an option "duplicate" which creates a copy of the file and : 
- let the user choose the name for the new file
OR
- just add "_copy" to the end of the filename.
I do open a file browser when I want to do so... this is not really important but usability will be improved.

Yours truly.

**Comment by Nodd** [comment]
Another way to do it is to open the file in spyder and use "Save as..." to save it with another name.
What is your use case for duplicating files multiple times ? This kind of copy pasting is usually bad practice (with reason!) when coding. I don't feel like this feature would be used much.

**Comment by ccordoba12** [comment]
It's not a bad idea because maybe you want to create a copy of a data file to work with it without fearing to destroy/alter its contents.

Unfortunately we don't have time to do it right now, maybe for 3.1 :-)

**Comment by jitseniesen** [comment]
This is related to PR #3362 (Save copy as).

**Comment by Nodd** [comment]
Ah yes, it makes more sense for data.

**Comment by goyou** [comment]
Yes it is exactly the same as 3362,  furthermore "save copy as ..." is more clear than my idea.
