### ISSUE TITLE
Imported Cython module, module has no attribute x

### ISSUE THREAD

**Issue by hendiol** [spyder-ide/spyder#3393]
## Description of your problem
Running a python (.py) file in spyder which imports a compiled cython module (.pyx) gives the error: AttributeError: module 'cy_0' has no attribute 'integrate'
While running the same file in the console works fine

**What steps will reproduce the problem?**

1. Complie .pyx file with setup file (in external console)
2. Run .py file (in spyder)

**What is the expected output? What do you see instead?**
Expected: No error message as in Terminal, the result of the cython function
Instead: AttributeError: module 'cy_0' has no attribute 'integrate'

**Please provide any additional information below**
Files:

setup.py:

```python
from distutils.core import setup
from Cython.Build import cythonize
setup(
    ext_modules = cythonize("cy_0.pyx")
)
```

cython (cy_0.pyx):

```cython
cdef double f(double x) except? -2:
    return x**2-x

cpdef double integrate_f(double a, double b, int N):
    cdef int i
    cdef double s, dx
    s = 0
    dx = (b-a)/N
    for i in range(N):
        s += f(a+i*dx)
    return s * dx

def integrate(l,h,N):
    return integrate_f(l,h,N)
```

run.py:

```python
import cy_0 as c
print (c.integrate(1,3,10))
```

## Versions and main components

* Spyder Version: Spyder 3.0.0.dev0 
* Python Version: Python 3.5.1 64bit
* Operating system: OS X 10.11.6

## Dependencies
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.2.0 (OK)
pyflakes >=0.6.0:  1.2.3 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.6 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.4.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting, we'll take a look at it for 3.1.

**Comment by hendiol** [comment]
with these steps the problem does not occur:
1. Edit files in Spyder
2. Compile .pyx in external console (python setup.py build_ext --inplace)
3. restart Spyder
4. run.py in spyder and console works fine

so restarting spyder solves the problem, but is not really suitable

**Comment by Nodd** [comment]
How do you run your script ? in the current console or do you restart one each time you urn your script ?

**Comment by hendiol** [comment]
I am running it in the current console

**Comment by Nodd** [comment]
If you run in the current console, the python process is not restarted, and modules are not reloaded. Try to restart the python console, it should fix your problem.
I advise you to run your script in a dedicated console to be sure that it starts fresh each time. You can change this in the run options (Ctrl+F6 by default).

**Comment by hendiol** [comment]
Thanks Nodd,
yes restarting/ open a new console solves the problem. 
Also your advise solves the problem. 
I used Cython the first time and explored this issue, with own written pure python (.py) files that are imported (ok this are no compiled modules) i don't experienced this issue (that reloading is necessary).

So now someone else has to decide if this is an Issue for upcoming versions or not.

**Comment by Nodd** [comment]
This is not an issue, just how python works.
By default spyder is configured for running single scripts and interactive use. The option you're talking about is running in a dedicated console (where the interpreter is restarted each time). You can set it as default in the preferences.
Another option is to enable the User Module Reloader in the preferences, in Console > Advanced options. It works most of the time.
