### ISSUE TITLE
%edit magic can't create a new file

### ISSUE THREAD

**Issue by dstrozzi** [spyder-ide/spyder#3394]
## Description of your problem

From an ipython prompt in Spyder, editing a non-existent file gives an error.  It would be great if this just created a new, blank file.  If there's a way to do this, or different command, I couldn't find it.

**What steps will reproduce the problem?**
1. Open ipython console in spyder
2. type "edit foo.py" in a directory with no file foo.py

**What is the expected output? What do you see instead?**

This isn't an issue but a feature request maybe.  I'd like an editor window with a blank file to open.  Instead I get an error.

**Please provide any additional information below**
## Versions and main components

Using Anaconda distribution
- Spyder Version: 2.3.9
- Python Version: 3.5.2
- Operating system: Windows 7
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for the suggestion. We'll see what we can do about it :-)

**Comment by dstrozzi** [comment]
OK, thanks!  It's not a big deal, just an annoying bump in workflow.
