### ISSUE TITLE
Sypder 3.0.0 crashes on OS X 10.11.6 after browsing with firefox

### ISSUE THREAD

**Issue by hendiol** [spyder-ide/spyder#3396]
## Description of your problem

Spyder 3. crashes often after browsing on websites with firefox. The programm is frozen and Mac shows the rainbow ball. A hard close of spyder solves the problem (using closing immedaitly in the dock or killing the process in the taskmanager) and afterwards restarting.

**What steps will reproduce the problem?**
1.  Coding / Running stuff in spyder
2. Browsing with firefox
3. Spyder is frozen **sometimes**

**What is the expected output? What do you see instead?**
May it is related to more complex websites, but I can't figure out that. The problem does not occur every time using firefox only sometimes (may about every third time switching back from firefox to spyder).
Expected: No problems when switching between the two programs
Instead: get frozen spyder app

**Please provide any additional information below**
## Versions and main components
- Spyder Version: Spyder 3.0.0.dev0 
- Python Version: Python 3.5.1 64bit
- Operating system: OS X 10.11.6
- Qt 5.6.0, PyQt5 5.6 on Darwin
- Firefox 48.0.2
## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.2.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.2.0 (OK)
pyflakes >=0.6.0:  1.2.3 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  1.5.6 (OK)
qtconsole >=4.0 :  4.2.1 (OK)
rope >=0.9.4    :  0.9.4-1 (OK)
sphinx >=0.6.6  :  1.4.1 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)

**Comment by ccordoba12** [comment]
Very odd bug. I doubt we can address it in any way, sorry.
