### ISSUE TITLE
wrong content

### ISSUE THREAD

**Issue by AronSwan** [spyder-ide/spyder#3397]
"help(random.randrange)
Help on method randrange in module random:

randrange(start, **stop=None,** step=1, _int=<class 'int'>) method of random.Random instance
    Choose a random item from range(start, stop[, step]).

This fixes the problem with randint() which includes the
    endpoint; in Python this is usually not what you want."

Function signature is wrong.The **correct** **one** should be randrange(**start=None,**stop,step=1)

**Comment by jitseniesen** [comment]
In fact, the function signature in the help precisely matches the signature in the Python source code: https://hg.python.org/cpython/file/3.5/Lib/random.py#l177

I can see that this is confusing, as semantically it's the start parameters that is optional. However, in Python compulsory parameters have to go before optional parameters, so it is not allowed to have the signature randrange(start=None,stop,step=1). 

I do not see what Spyder can do about this. If you type `help(random.randrange)` in Python (outside Spyder), you get the same.

**Comment by AronSwan** [comment]
Thank you for your reply,I'm a beginner of Python,sorry to bother you.




------------------ 原始邮件 ------------------
发件人: "Jitse Niesen";<notifications@github.com>;
发送时间: 2016年9月3日(星期六) 晚上11:13
收件人: "spyder-ide/spyder"<spyder@noreply.github.com>; 
抄送: "周超"<919519954@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [spyder-ide/spyder] wrong content (#3397)




In fact, the function signature in the help precisely matches the signature in the Python source code: https://hg.python.org/cpython/file/3.5/Lib/random.py#l177
 
I can see that this is confusing, as semantically it's the start parameters that is optional. However, in Python compulsory parameters have to go before optional parameters, so it is not allowed to have the signature randrange(start=None,stop,step=1). 
 
I do not see what Spyder can do about this. If you type help(random.randrange) in Python (outside Spyder), you get the same.

**Comment by jitseniesen** [comment]
> Thank you for your reply,I'm a beginner of Python,sorry to bother you.

Don't worry about it, everybody was a beginner once.
