### ISSUE TITLE
Problem with imshow

### ISSUE THREAD

**Issue by Sudeshna1509** [spyder-ide/spyder#3399]
I took a pic from webcam and am facing problem while importing it,an error occurs which states:
 error: (-215) size.width>0 && size.height>0 in function cv::imshow
I downloaded a picture and while working with it i don't get the same problem.

**Comment by ccordoba12** [comment]
This seems a problem with OpenCV, not with Spyder. I'm sorry but we can't help because we don't know what is happening in this case.
