### ISSUE TITLE
ctrl + left click on empty line causes the a bunch of error to show up

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3400]
## Description of your problem
ctrl + left click is used to jump to definition
but if you by mistake do it on empty line, the internal console shows up and shows:
`Traceback (most recent call last):
  File "/home/tal/anaconda3/envs/pic/lib/python3.5/site-packages/spyderlib/utils/introspection/plugin_manager.py", line 351, in _introspection_complete
    result = self.plugins['fallback'].get_definition(info)
  File "/home/tal/anaconda3/envs/pic/lib/python3.5/site-packages/spyderlib/utils/introspection/fallback_plugin.py", line 72, in get_definition
    if '.' in token:
TypeError: argument of type 'NoneType' is not iterable
`

A bigger problem is that once you do it the editor and the ipython shell are no longer connected, so hitting f5 will result the following error message box to show up:
`No Python console is currently selected to run myfile.py.

Please select or open a new Python console and try again`

**What steps will reproduce the problem?**

1. click ctrl + lift click on an empty line in the editor

**What is the expected output? What do you see instead?**
not to crush...

**Please provide any additional information below**
sometimes you need to ctrl click it twice to produce the error
the main problem is that the editor losses the connection to the ipython

## Versions and main components

* Spyder Version: 2.3.8 and 2.3.9
* Python Version: 3.5.2
* Operating system: ubuntu linux 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.1.0 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by talkaminker** [comment]
Ok, here is a fix:
in the function spyderlib/utils/introspection/fallback_plugin.py # get_definition
add in the beginning after
`token = info.obj`
this line:
`if token is None:
    return 
`

**Comment by jitseniesen** [comment]
Thanks for your report. I can reproduce this with Spyder 2, but it looks like the issue has already been fixed exactly as you suggested in revision 2805955. Download Spyder 3.0 beta 6 to get the fix, or wait for the stable release.
