### ISSUE TITLE
django 1.10.1-py35_0 is downgraded (SUPERCEDED) to 1.9.5-py35_0 on 3.0.0 beta6 install

### ISSUE THREAD

**Issue by rshpeley** [spyder-ide/spyder#3401]
## Description of your problem
When installing spyder 3.0.0 beta6 after installing django 1.10.1-py35_0, django is superceded to 1.9.5-py35_0 when running conda install -c qttesting qt pyqt.

**What steps will reproduce the problem?**

1. install django 1.10.1 from conda in python 3.5.2 environment
2. follow install steps on git spyder 3.0.0 beta6 page for conda install
3. run conda install -c qttesting qt pyqt --> downgrades django

**What is the expected output? What do you see instead?**
I wanted django 1.10.1 and got 1.9.5 afterwards.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0 beta6
* Python Version: 3.5.2
* Operating system: mint 17.3 kde

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.6 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by Nodd** [comment]
The command that downgrades django is not related to spyder, so the problem is likely to be elsewhere. Maybe ask the anaconda team or the maintainers of the `qttesting` channel ?

**Comment by ccordoba12** [comment]
Strange error indeed. Let's hope this is fixed when Continuum officially releases packages for Qt 5 :-)

**Comment by rshpeley** [comment]
@Nodd, I got the command from the install instructions for spyder beta6. Since spyder 3.0.0b6 needs qttesting for its install the problem also belongs to spyder. I don't expect the devs to fix the problem since it resides elsewhere, but the docs can be updated to reflect a downgrade issue as a heads up to beta testers.

These are the packages affected from my install. There are likely others.
```
The following packages will be SUPERCEDED by a higher-priority channel:
    django:           1.10.1-py35_0      conda-forge --> 1.9.5-py35_0          
    hdf4:             4.2.12-0           conda-forge --> 4.2.12-0              
    icu:              56.1-4             conda-forge --> 54.1-0                
    jpeg:             9b-0               conda-forge --> 8d-1                  
    libtiff:          4.0.6-6            conda-forge --> 4.0.6-2               
    libxml2:          2.9.4-0            conda-forge --> 2.9.2-0               
    xerces-c:         3.1.4-2            conda-forge --> 3.1.4-0           
```
