### ISSUE TITLE
Update spyder description in google forum

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/spyder#3402]
Here's what it say now:

> This is the discussion group of Spyder (previously known as Pydee), a free open-source Python development environment providing MATLAB-like features in a simple and light-weighted software, available for Windows XP/Vista/7, GNU/Linux (official packages are available for Debian, Ubuntu, archlinux, Fedora, Gentoo or openSUSE) and MacOS X.

> Spyder is part of spyderlib, a Python module based on PyQt4, pyflakes, rope and sphinx providing powerful PyQt4 widgets like source code editors, Python console (easy to embed in your own application: see this example) or GUI-based dictionary, lists/tuples and NumPy array editors.

> The Spyder's official website is here.

Lots of things have changed since it was written. I don't know who has the right to change it. @ccordoba12 ?

**Comment by ccordoba12** [comment]
I'm fine to replace that text, but I don't have time to come up with something right now.

Could you provide the text you would like to see there instead of the current one?

**Comment by Nodd** [comment]
Simple is better:

> This is the discussion group of Spyder, a free open-source Python development environment providing MATLAB-like features in a simple and light-weighted software, available for Windows, GNU/Linux and MacOS X.
> The Spyder official website is here<>. Spyder development happens on Github <https://github.com/spyder-ide/spyder>

I don't know what to put for the official website, since it looks like https://spyder-ide.github.io/ is not up yet.

**Comment by goanpeca** [comment]
@Nodd we own http://www.spyder-ide.org, and right now it points to the github repo. When the site is on teh site will be there.

**Comment by Nodd** [comment]
Ah right, you're the website boss !

**Comment by ccordoba12** [comment]
Ok, this is done now.

**Comment by Nodd** [comment]
Thanks ! The official website will be added when it's ready.

**Comment by ccordoba12** [comment]
Yep, sure! @goanpeca, please ping me about it :-)
