### ISSUE TITLE
Error when opening project and cancelling

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#3403]
## Description of your problem

**What steps will reproduce the problem?**

1. Click `Project > Open Project ...`
2. Click `Cancel` in the "Open project" window

**What is the expected output? What do you see instead?**

I get an error window saying "is not a Spyder project!". Instead, I expect nothing to happen.

## Versions and main components

* Spyder Version: 3.0 beta 6
* Python Version: 3.5
* Operating system: Linux

**Comment by zhangwise** [comment]
This problem still appears in Spyder 3.01 with Python 2.7.12.
I tried to open a project created using previous version (2.3.8) of Spyder, but there is message of  "is not a Spyder project!" and actually import nothing.

**Comment by ccordoba12** [comment]
@zhangwise, old projects (i.e. projects created with Spyder 2.3 and below) are not supported anymore. You need to create a new project instead :-)

**Comment by MCilento93** [comment]
I wrote a project in Spyder 3, now I can't open the project with Spyder 4.
Is correct like this or maybe there is something wrong?

**Comment by ccordoba12** [comment]
Hey @MCilento93, there was an error when opening projects but we fixed it in our latest version (4.1.5). If you don't have that version, please update to it.
