### ISSUE TITLE
Spyder renders numpydoc style parameters wrong

### ISSUE THREAD

**Issue by adler-j** [spyder-ide/spyder#3404]
In earlier versions of Spyder (up until a few weeks ago, so I'd guess this may be due to some dependency change) `NumpyDoc` style parameter lists rendered well.

For example, the following

``` python
def myfun(x):
    """Call function

    Parameters
    ----------
    x : `int`
        x is an integer
    """
    pass
```

Rendered properly in the Object inspector as (something like)

**x** : int
&nbsp;&nbsp;&nbsp;&nbsp;x is an integer

With some recent change, it now renders as

**x**
: int
&nbsp;&nbsp;&nbsp;&nbsp;x is an integer

This change has been comming through on all machines that I have done `pip --update` on lately, regardless of OS (both windows and Ubuntu). The change showed both in `2.3.8` and in the recent `2.3.9` version.

**Comment by ccordoba12** [comment]
Thanks for reporting, we'll take a look at this one after we release Spyder 3.0 :-)

**Comment by ccordoba12** [comment]
This is caused by Sphinx itself. Nothing we can do about it, sorry.

**Comment by adler-j** [comment]
Have you created an issue with Sphinx or should I do that?

**Comment by ccordoba12** [comment]
Please do that, we haven't created an issue with them.
