### ISSUE TITLE
Cannot create Shift+Del as a shortcut for delete line

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3405]
## Description of your problem

shift+del doesn't work as a shortcut
A very common shortcut (default in sublime and jupyter notebook) for deleting a line is shift +del. changing the shortcut doesn't work
**What steps will reproduce the problem?**
1. change the shortcut for delete line to shift delete
2. try to delete a line
3. it doesn't work

**Please provide any additional information below**
I think shift del should be the default, I think it is the default in sublime and almost every other ide. but ctrl D is also common, so who knows...
## Versions and main components

I tried it on both linux, windows, 3.0 and 2.3.8 and 2.3.9
- Spyder Version:both 3.0.0dev (I took it today from the git) and the stable 2.3.9
- Python Version:2.7
- Operating system:  tested windows and linux
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
for 2.3.9
IPython >=1.0      :  5.1.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  4.3.0 (OK)
pyflakes >=0.5.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  14.7.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. I don't know if we can make a shortcut composed of modifiers only.

@goanpeca, is this possible in Qt?

**Comment by goanpeca** [comment]
It should be possible :-|, I will take this after 3.0

**Comment by talkaminker** [comment]
well, adding this to codeeditor@keyPressEvent
```
        elif shift and key == Qt.Key_Delete:
            self.delete_line()
```
works

**Comment by jitseniesen** [comment]
> well, adding this to codeeditor@keyPressEvent [...] works

Is it possible to use `config_shortcut()` so that the user can change the shortcut?

**Comment by ccordoba12** [comment]
@jitseniesen, yes, there are two things here:

1. We are not using `config_shortcut` for this shortcut
2. I think our shortcuts dialog doesn't admit a sequence like `Shift+Del`, but that should be an easy fix :-)

**Comment by ccordoba12** [comment]
@malliwi88, this one is easy, please work on it :-)

**Comment by malliwi88** [comment]
That's right @ccordoba12 `config_shortcut` has been used only define shortcuts on Spyder plugins, but in this case, our function `delete line` is just defined on widget/editor and It just doesn't have access to `register_shortcuts` function, Which I think might be the most appropriate solution.

**Comment by ccordoba12** [comment]
@andfoy, please work on this one.

**Comment by andfoy** [comment]
@ccordoba12 I have problems trying to define a custom shortcut in the Configuration window, after I press the keys that conform the shortcut and then press Cancel or Accept, Spyder crashes with seg fault.

**Comment by andfoy** [comment]
Ctrl+D is deleting characters and lines.
