### ISSUE TITLE
Project explorer window is empty in Spyder 3.0.0b6

### ISSUE THREAD

**Issue by jobar8** [spyder-ide/spyder#3410]
## Description of your problem
I have recently upgraded spyder 3.0.0b4 to 3.0.0b6 and in the process the content of the project explorer window has disappeared.

**What do you see instead?**
The project explorer window is empty and the address bar with the button to select the workspace next to it has gone.

## Versions and main components

* Spyder Version: 3.0.0b6
* Python Version: 2.7
* Operating system: Windows 10

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Projects have been rewritten almost from scratch. The old workspaces are gone and now you need to create a project from the `Projects` menu in the main window. After you do that, the project explorer will show a file tree view of your current project.

Sorry for the inconveniences, but we don't plan to support the workspaces concept in Spyder 3.0.

**Comment by jobar8** [comment]
OK.
Thanks a lot for the explanation.

**Comment by ccordoba12** [comment]
No prob :-) Hope you enjoy our new projects support.
