### ISSUE TITLE
loading Mnist dataset: kernel keeps dying unexpectedly

### ISSUE THREAD

**Issue by Roboball** [spyder-ide/spyder#3411]
loading Mnist dataset leads to chrash of IPhython console 
error message:  kernel keeps dying unexpectedly

Code:
`from`` sklearn.datasets import ``fetch_mldata`
`mnist`` = fetch_mldata('MNIST original', ``data_home=".")`
`print`` "finish load MNIST dataset"``

**Comment by ccordoba12** [comment]
Not a problem anymore in Spyder 3.0, but thanks for reporting :-)
