### ISSUE TITLE
python xy spyder not launching

### ISSUE THREAD

**Issue by june8070** [spyder-ide/spyder#3413]
I've installed python xy 2.7.10 and when starting Spyder, the console appears for a split second and then disappears and Spyder never opens.dont know what to do ......need help:-(

* Python Version:python xy 2.7.10
* Operating system:windows xp

**Comment by ccordoba12** [comment]
Please run in a terminal (i.e. `cmd.exe`) this command

    spyder --reset

and post its results.

**Comment by june8070** [comment]
![image](https://cloud.githubusercontent.com/assets/22145411/18545414/f77dd85c-7aed-11e6-9c54-83330979c03c.png)

**Comment by june8070** [comment]
![image](https://cloud.githubusercontent.com/assets/22145411/18545482/34371e52-7aee-11e6-9a9c-2524c1bb8a83.png)

**Comment by ccordoba12** [comment]
I can tell you some things from your screenshot:

1. Windows XP is not supported anymore, sorry.
2. You're using Anaconda and not Python XY
3. You don't need to start Spyder from its installation directory. You should be able to start Spyder from your user directory.

In any case, problem 1. is unfixable for you, sorry :-/

**Comment by azraaziz** [comment]
I got this. Any advancements, please?
![screenshot](https://user-images.githubusercontent.com/44118595/220821406-8d77b0d2-c96d-460b-8de3-8ac535d11dd5.png)
