### ISSUE TITLE
Can't change Run Selection keyboard shortcut from F9 to Cmd + Shift + Enter

### ISSUE THREAD

**Issue by hueykwik** [spyder-ide/spyder#3415]
## Description of your problem

**What steps will reproduce the problem?**
1. Preferences -> Keyboard Shortucts
2. Select run selection
3. Change to Shift Cmd Enter
4. Select a line in a Python script
5. Hit Shift Cmd Enter

**What is the expected output? What do you see instead?**
The line runs. 
Instead, the line doesn't run. 

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 2.3.9
- Python Version: 3.5
- Operating system: Mac OS X 10.11.6
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.3.0 (OK)
pyflakes >=0.6.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
We're going to fix this in Spyder 3.1 (there are several other similar issues like this one already :-)
