### ISSUE TITLE
spyder hangs after plotting a few FacetGrids

### ISSUE THREAD

**Issue by hueykwik** [spyder-ide/spyder#3416]
## Description of your problem

**What steps will reproduce the problem?**
1.  Write a script that loads the first six plots of https://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.FacetGrid.html
2. Run the script in the IPython console

**What is the expected output? What do you see instead?**
Plots show up in the IPython console and then I can continue working. This works! However, I don't expect the entire application to hang.

I get this warning message as well:
/Users/hkwik/anaconda/envs/py35/lib/python3.5/site-packages/matplotlib/tight_layout.py:222: UserWarning: tight_layout : falling back to Agg renderer
  warnings.warn("tight_layout : falling back to Agg renderer")

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 2.3.9
- Python Version: 3.5
- Operating system: Mac OS X 10.11.6
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0 : 4.2.0 (OK)
jedi >=0.8.1;<0.9.0: 0.9.0 (NOK)
matplotlib >=1.0 : 1.5.1 (OK)
pandas >=0.13.1 : 0.18.1 (OK)
pep8 >=0.6 : 1.7.0 (OK)
psutil >=0.3 : 4.3.0 (OK)
pyflakes >=0.6.0 : 1.2.3 (OK)
pygments >=1.6 : 2.1.3 (OK)
pylint >=0.25 : None (NOK)
qtconsole >=4.0 : 4.2.1 (OK)
rope >=0.9.2 : 0.9.4-1 (OK)
sphinx >=0.6.6 : 1.4.1 (OK)
sympy >=0.7.3 : 1.0 (OK)
zmq >=2.1.11 : 15.2.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting, I'll take a look at it after we release Spyder 3.0 :-)

**Comment by ccordoba12** [comment]
This was probably caused because Spyder 2.3 was not working correctly on Mac. However Spyder should be working normally.

Please update and test again. If the problem persists, reopen this issue.
