### ISSUE TITLE
IPython console: help window hijacks `?` keypress

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#3419]
Simply typing a `?` next to a function will automatically popup the help window. Sometimes I want the spyder help menu, but not always and the previous behaviour of explicitly having to press `Ctrl-I` allowed me to control this.

There also appears to be a bug in the help whereby when typing a `?` next to a function from my library causes an exception in the internal console which then prevents any help being displayed.
```python-traceback
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\dev\packages\spyder\spyder\widgets\ipythonconsole\namespacebrowser.py", line 188, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\dev\packages\spyder\spyder\widgets\ipythonconsole\shell.py", line 229, in handle_exec_method
    self._kernel_reply = ast.literal_eval(data['text/plain'])
TypeError: 'NoneType' object is not subscriptable
```

**Note:** I haven't managed to repro this yet with a function not in my library but I will post back if I can

![image](https://cloud.githubusercontent.com/assets/881019/18535640/4f5980c6-7b39-11e6-9bce-39e9ba36a603.png)

## Dependencies
```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by dhirschfeld** [comment]
NB: This is on the very latest git master

**Comment by ccordoba12** [comment]
Ok, I'll disable `?` then ;-)

**Comment by ccordoba12** [comment]
@dhirschfeld, thanks a lot for testing these new changes so quickly. Please let me know if you find other issues down the road ;-)

**Comment by dhirschfeld** [comment]
Not a problem - the least I can do! Thanks for all the hard work making spyder better! :)
