### ISSUE TITLE
Error connecting to Kernel

### ISSUE THREAD

**Issue by KrishnaMahi** [spyder-ide/spyder#3425]
![untitled](https://cloud.githubusercontent.com/assets/19369107/18554492/14769342-7b82-11e6-9482-843f515ea8c7.jpg)
Spyder isn't getting connected to kernel. Rectify this problem

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed in #2878, and it'll be part of Spyder 3.0.
