### ISSUE TITLE
Spyder is opening black DOS windows now

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3427]
## Description of your problem

**What steps will reproduce the problem?**

1. spyder dev of 2016-09-15
2. start spyder on Windows 10
3. spyder start , but a side-python-screen (process) appears

**What is the expected output? What do you see instead?**

the black side window/process is new, is it a consequence of new ipython connexion method ?

I would suppose maybe we don't want to see it

**Please provide any additional information below**

## Versions and main components

* Spyder Version: github 2016-06-15
* Python Version: 3.4
* Operating system: Windows 10

![spyder-20160915](https://cloud.githubusercontent.com/assets/4312421/18606264/0b2c74d0-7cab-11e6-9fbb-d2351efca19f.PNG)

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0b4 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.0rc1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
What happens if you open more IPython consoles?

**Comment by ccordoba12** [comment]
I know how to fix this one, it's just a matter of using `pythonw` to start IPython kernels.

**Comment by stonebig** [comment]
3 Ipython consoles ==> 3 black DOS windows

**Comment by ccordoba12** [comment]
Yep, just what I imagined. Thanks for checking it @stonebig :-)

**Comment by ilayn** [comment]
I can confirm this behavior on Windows 10, Windows 3.6 

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
@stonebig, could you show the full title of cmd window open by Spyder? Right now I can only see up to `winpython-64bit-3.4.x.5\...`

**Comment by stonebig** [comment]
![spyder-20160921](https://cloud.githubusercontent.com/assets/4312421/18698121/ed96743c-7fc7-11e6-9817-3f686b451023.PNG)

**Comment by ccordoba12** [comment]
@stonebig, I think there's a bug in `jupyter-client` that prevents me to fix this.

Could you locate this line:

https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/launcher.py#L123

and change it to

    proc = Popen(cmd, shell=True, **kwargs)

to see if the cmd window goes away?

**Comment by stonebig** [comment]
testing now ....

**Comment by ccordoba12** [comment]
I have a different fix now. Please help me test PR # 3442 :-)

**Comment by stonebig** [comment]
greuuuh... looking at the other fix now

**Comment by ccordoba12** [comment]
Sorry, sorry :-p

**Comment by stonebig** [comment]
it works too. still even for a new  kernel, having it (announced) dying once is quite a short timeout (3  seconds ?)

**Comment by stonebig** [comment]
by the way, on Python 3.4 / Windows, you are under PyQt5.6  or PyQt5.5 ?

**Comment by ccordoba12** [comment]
5.6, don't know what's happening with the new kernel dying but I don't think it's that serious ;-)

**Comment by stonebig** [comment]
it's just a papercut, but you see the "death" at every new kernel, and that gives a (false) feeling of instability

**Comment by ccordoba12** [comment]
I'll take a look at it for Spyder 3.1. Please open a new bug so we don't forget about it :-)
