### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#3430]
I just released 3.0beta7, the last beta for Spyder 3.0. So now it has come the time to update our translations for the final 3.0 release (at last!!).

This is a call to all our translators to update their respective translations. Please create separate pull requests for each language.
- French
  - @Nodd
  - @SylvainCorlay
- Japanese
  - @sohnishi
- Portuguese (Brazilian)
  - @manipuladordedados
- Russian
  - @burrbull
  - @Qlogin
- Spanish
  - @ccordoba12
  - @goanpeca

---

**Important note**: I can only wait for you until **September 21** for your updates. I need to release Spyder 3.0 that day. I hope you can make it!

Thanks all for your help and cooperation ;-)

**Comment by wtheis** [comment]
I am wondering whether a German translation (down the line, I'm not volunteering for next week) would have a sufficient impact on broadening the userbase to make it worth the effort. Do you have any numbers regarding anaconda installations and spyder usage by country?

**Comment by goanpeca** [comment]
Hi @wtheis I dont think we have enough stats for that but any new translation definitely has a positive impact on the spyder user base :-)

**Comment by ccordoba12** [comment]
Nop, sorry. But there's no rush to send a *new* translation, this is just for current translations.

You can send a German translation whenever you like, and I'll release a minor version of Spyder (e.g. 3.0.1) to include it :-)

**Comment by Qlogin** [comment]
Hello, @ccordoba12! There are some mismatches in translation template. May be you will update 'spyder.pot' file to prevent its changes in each PR.

**Comment by ccordoba12** [comment]
Will do for beta8, and will give you some extra days to finish the translations :-) Sorry for not noticing before, silly me!

**Comment by ccordoba12** [comment]
@Qlogin and others, I just updated our translation files. I really don't have time to release a new beta, so please update your translations based on the files on master.

Thanks :-)

**Comment by ccordoba12** [comment]
And you have until Friday to update your translations :-) I'll release 3.0 final on Saturday.

**Comment by ccordoba12** [comment]
@Qlogin added some missing strings to be translated, so you need to rebase or merge your efforts with master to update your translations.

Thanks :-)

**Comment by ccordoba12** [comment]
Ok, I'm moving this to 3.0.1 (to be released in two or three weeks) to give more time to our translators.

@manipuladordedados, the Portuguese translation is the most outdated one. If you don't update it by 3.0.1, I'm going to disable it. This doesn't mean a removal, just disabling it from our Preferences until you update it.

@PierreRaybaut, could you help me with the French translation? It shouldn't take that much time because you update it some months ago :-)

@sohnishi, I hope you have time to update the Japanese translation by then :-)

@Qlogin, I fixed some errors which were preventing us to get all translation strings. So there are more strings to translate, but unfortunately (as said before) I have to release Spyder today, so please update the Russian translation for 3.0.1.

**Comment by manipuladordedados** [comment]
@ccordoba12, Sorry for the delay.
Check the pull requests.

**Comment by ccordoba12** [comment]
Thanks a lot for the quick response. Your update will be part of 3.0 (not 3.0.1 :-)

**Comment by ccordoba12** [comment]
Hey guys, sorry I missed this in 3.0.1. But we need your help now, for 3.0.2 :-)

This is (most probably) the version that's going to be added to the next version of Ubuntu (17.04), so we'd like you to help us to maintain very good translations for the languages you speak.

**Important recommendation**: Please do your pull requests against the `3.x` branch, not `master`. That's because `3.x` is our maintenance branch now, and we create new releases from it instead of from `master`.

You have until Friday to send us your corresponding pull requests. Thanks a lot for your help!

**Comment by ccordoba12** [comment]
@Qlogin and @manipuladordedados, please don't forget to send us your pull requests. You're the most active translators :-)

**Comment by Qlogin** [comment]
@ccordoba12 done

**Comment by ccordoba12** [comment]
Ok, last call for French translations: @stonebig, could you help us with updating them? I'd need a PR from you today to release 3.0.2, else I'll disable them because they are too outdated.

**Comment by ccordoba12** [comment]
Most translations have been updated for 3.0.2. Thanks a lot for your help!!
