### ISSUE TITLE
Default file extension should be .py instead of empty

### ISSUE THREAD

**Issue by ilayn** [spyder-ide/spyder#3436]
## The default file type is empty in the save dialogs

**What steps will reproduce the problem?**

1. Open any document and use save as dialog
2. if there exists any remove the extension
3. Click save

**What is the expected output? What do you see instead?**

The expected outcome (I think) the file should be save with a defauly .py extension instead of no-extension state. 

**Please provide any additional information below**

You can see from the screenshot possible extension recommendation windows is also empty

![zzzz](https://cloud.githubusercontent.com/assets/1303842/18669359/ef8a8c5c-7f3a-11e6-916c-67c92516d09d.PNG)

## Versions and main components

* Spyder Version: 3.0.0b7
* Python Version: 3.6
* Operating system: Win10

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Well, we extended the Editor in Spyder 3.0 so that it can handle any type of file (instead of just Python). That's why we think it's better not to offer any default extension when saving files.

**Comment by ilayn** [comment]
That makes sense indeed but then there is no need for the "Save as type" dialog I think.

**Comment by goanpeca** [comment]
>That makes sense indeed but then there is no need for the "Save as type" dialog I think.

Could you explain

**Comment by ilayn** [comment]
In the screenshot above, there is an empty save as type pulldown menu with no options. If I understand @ccordoba12 correctly, we would have an empty choice by default. However, assume that I do have a choice and it wouldn't hurt if I can just select from a list for pyc, rst, py files. 

This wouldn't change any defaults but still can accomodate for quick access to file types

**Comment by ilayn** [comment]
My main issue (well, first world problems :) ) is that save dialog opens and the untitled0.py is selected then I type something and hit enter without the file extension. Then of course from code completion to syntax coloring everything turns off. 

So I manually find the file add the extension to the file and then reopen it in spyder. I was wondering if this can be a bit easier on the punisment of user stupidity like myself.

**Comment by goanpeca** [comment]
I think we can enable the save as combobox then :-), definitely an enhancement

**Comment by ilayn** [comment]
My inner laziness thanks you 😄

**Comment by goanpeca** [comment]
This is one issue you can start to work on @malliwi88.

**Comment by malliwi88** [comment]
Hello 


I have [This Pull request](https://github.com/spyder-ide/spyder/pull/3517) for solve this Issue ;) @ilayn, @goanpeca

**Comment by goanpeca** [comment]
@malliwi88 I have made my initial comments on the PR

**Comment by ilayn** [comment]
A late thank you to all involved!!
