### ISSUE TITLE
Cannot  run a script in IPython console with Spyder-3.0.0b7 

### ISSUE THREAD

**Issue by fieldcoil** [spyder-ide/spyder#3443]
## Description of your problem
I updated my Spyder to 3.0.0b7 today because I'm very happy that issue# 2696 has been fixed! However, I got the error message "NameError: name 'runfile' is not defined" when I run a script in Spyder.

**What steps will reproduce the problem?**

1. install/update Spyder 3.0.0b7 via command: pip install --pre -U spyder
2. launch Spyder and open a python script
3. click "run" icon

**What is the expected output? What do you see instead?**
The script should run without error. But I got an error message: NameError: name 'runfile' is not defined

**Please provide any additional information below**
I found that the sub-folder "spyder/utils/site/" is missed, where the file "sitecustomize.py" should be in. I manually created a folder "site" and copied two files from the git repository. Then relaunch Spyder. Everything is fine.

## Versions and main components

* Spyder Version: 3.0.0b7
* Python Version: 2.7.9
* Operating system: Mac OS X 10.11.06

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.18.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5a1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed in #3438 :-)
