### ISSUE TITLE
Exiting the debugger

### ISSUE THREAD

**Issue by sasimon** [spyder-ide/spyder#3449]
Whenever I try to exit the debugger on 2.3.9 and Python 3.5, I see an In [number] prompt, but there is an ipdb> prompt right below it. I cannot see a way to exit the debugger so that the next command I type will be in the In prompt directly. I believe this may be a bug in Spyder.

**Comment by ccordoba12** [comment]
I think this is fixed in Spyder 3.0 (which will come out in some of hours :-), please test again when that version comes out and let us know what happens :-)

**Comment by ccordoba12** [comment]
Closing because of lack or response.
