### ISSUE TITLE
Interactive tour freezes spyder on Windows

### ISSUE THREAD

**Issue by martinfiers** [spyder-ide/spyder#3452]
## Description of your problem

The interactive tour seems to 'hang' the spyder window when closing the tour.

**What steps will reproduce the problem?**
1. Start spyder (from master): python bootstrap.py
2. Run the interactive tour (Help --> Interactive tours --> Introduction tour)
3. Close the tour at any point.

**What is the expected output? What do you see instead?**

Expected: you can continue working with spyder. Instead, window focus is lost, and the window totally freezes. I need to kill the python process in the process explorer.

**Please provide any additional information below**

This only happens on Windows. On Linux, it seems to work fine. Additionally, the 'interact: True' that you can provide when creating tours will not work on Windows (i.e., you can't interact with spyder during the tour), whereas this works on Linux.
## Versions and main components
- Spyder Version: master
- Python Version: 2.7 (PyQt 5.6.0) and 3.5 (PyQt 4.11.4 and 5.6.0 tested)
- Operating system: Windows 7
## Dependencies

Not relevant I think, but pasting for python 2.7: 
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in 3.0.1 :-)

**Comment by goanpeca** [comment]
Oops, yes, Qt5 is making the tour behave in a weird fashion :-|

**Comment by martinfiers** [comment]
Thanks for looking at this. To add a bit of information: it also happens with Qt4 (not only Qt5). Seems to work with PySide.

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, this is a very ugly bug. Please investigate how to solve it :-)
