### ISSUE TITLE
ImportError with create_app.py

### ISSUE THREAD

**Issue by xxblx** [spyder-ide/spyder#3454]
## Description of problem

Hello, 

I installed spyder 3.0.0 on macOS Sierra 10.12 with pip. Spyder start's from terminal fine. 

I want to add Spyder to launchpad. So I tried to create app file for adding them to Applications.

I run create_app.py and got an error

```
Air-Oleg:spyder-3.0.0 xxblx$ python3 create_app.py py2app
Traceback (most recent call last):
  File "create_app.py", line 30, in <module>
    from spyder.config.main import EDIT_EXT
ImportError: cannot import name 'EDIT_EXT'
```

## Steps to reproduce

1. Download spyder-3.0.0 sources
2. python3 setup.py build
3. python3 create_app.py py2app

## Versions and main components

* spyder 3.0.0

* macOS Sierra 10.12

* Python 3.5.2 from Anaconda bundle

* py2app 0.10

## Dependencies

```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by tienhv** [comment]
I have the same issue on mac os 10.11, other configurations are the same.

**Comment by ccordoba12** [comment]
I haven't had time to update `create_app.py`, that's why it's broken.

However, the process to create our apps is a lot more than just running `python create_app.py py2app`. If you really want to do this yourselves, please follow the instructions present in:

https://github.com/spyder-ide/mac-application
