### ISSUE TITLE
upload 3.0.0 to conda

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3455]
I don't know if you are the guys but could you upload to the newest 3.0.0 python not only to pip but also to conda.

Thanks!

**Comment by ccordoba12** [comment]
I thought this was going to be done yesterday. Hopefully it's there tomorrow :-)

**Comment by wtheis** [comment]
Still not available via conda.

Would you consider uploading a copy locally to install via
`conda install -c spyder-ide spyder==3.0.0`
or similar?

**Comment by talkaminker** [comment]
it is available. BUT you have to install
`conda install qt=5.*`
manually and see what are the conflicts that you get.
I got conflict with the previous spyder (which is them `conda remove spyder`) and another useless library

**Comment by brylie** [comment]
When trying to install Qt 5.x, I got the following message:

> conda install qt=5.*
UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda-navigator -> pyqt 4.*
  - qt 5.*

Uninstalling anaconda-navigator allowed me to install Qt 5.x (I hope other things don't break).

**Comment by talkaminker** [comment]
They have fixed it. now anaconda-navigator can be updated as well

**Comment by Jessime** [comment]
What is the proper way to proceed after you get:

```
conda install qt=5.*
Fetching package metadata .......
Solving package specifications: ....
UnsatisfiableError: The following specifications were found to be in conflict:
  - qt 5.*
Use "conda info <package>" to see the dependencies for each package.
```

Do I have to remove qt4? It's a dependency for a lot of other packages.

**Comment by brylie** [comment]
Try running the command again today. `anaconda-navigator` with Qt 5.x support was just released. Otherwise, try:

```
conda remove anaconda-navigator
conda update qt pyqt
conda install spyder
conda install anaconda-navigator
```

**Comment by Jessime** [comment]
I actually didn't have `anaconda-navigator` installed. I had to do 

```
conda remove qt
conda install qt=5.*
```

then reinstall everything that depended on qt (including spyder). But everything worked out.

**Comment by lxkain** [comment]
the idea of uninstalling qt v4, and then reinstalling worked for me, too.

**Comment by ccordoba12** [comment]
This is fixed now.
