### ISSUE TITLE
Feature Request: Clear Console After Kernel Restart

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#3458]
The previous behaviour of spyder was to clear the console after a kernel restart whereas now it simply prints a `Restarting kernel...` and a horizontal line but leaves the full history in the console:
![image](https://cloud.githubusercontent.com/assets/881019/18818996/f88bd3da-83ca-11e6-92a0-00851b93b7b2.png)

Whilst this may sometimes be desirable, at other times the history of the previous session is simply noise and makes it difficult to determine where the output from the new session started. This would be less of an issue if there were a way to clear the console manually but the `%clear` magic just scrolls down and doesn't actually clear the contents of the console. 

It would be nice if there were a configuration setting so you could choose whether or not to clear the console after a kernel restart.

**Comment by ccordoba12** [comment]
So `%clear` is not working on Windows? And does this happen only after a kernel or always?

**Comment by dhirschfeld** [comment]
`%clear` doesn't work before or after a kernel restart and I don't think it ever has for me
![image](https://cloud.githubusercontent.com/assets/881019/18829326/16abdf1e-841f-11e6-91da-7333f8cc11b6.png)

It's probably a behaviour inherited from the qtconsole:
![image](https://cloud.githubusercontent.com/assets/881019/18829374/516d386e-841f-11e6-9610-cdc07588a4d0.png)
