### ISSUE TITLE
Make File Explorer language agnostic and expose minimal api

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3460]

**Comment by ccordoba12** [comment]
There's nothing Pythonic about the File Explorer, as far as I remember :-)

**Comment by goanpeca** [comment]
Yes there is... plus the decoupling is part of making the API. We have the Run behavior, and the create behavior (modules and packages)

**Comment by ccordoba12** [comment]
Oh right. I didn't remember those ;-)

**Comment by goanpeca** [comment]
Luckily if we just focus on those its super easy to do and extend :-)

**Comment by ccordoba12** [comment]
We don't plan to work on this, sorry.
