### ISSUE TITLE
Autocomplete on Variables

### ISSUE THREAD

**Issue by orbitzhan** [spyder-ide/spyder#3462]
## Autocomplete on Variables

**What steps will reproduce the problem?**
1. it works if I use the library like ogr
   ![1](https://cloud.githubusercontent.com/assets/13759823/18855297/2c0c4244-8484-11e6-81aa-9ef84d3c27b8.jpg)
2. it didn't work if I use the variables
   ![31](https://cloud.githubusercontent.com/assets/13759823/18855342/7fb231e2-8484-11e6-81a3-1417ac64d41b.jpg)

**What is the expected output? What do you see instead?**
what i expect is that when i use the vs code and its plugins.
![21](https://cloud.githubusercontent.com/assets/13759823/18855256/e867c0c2-8483-11e6-8383-fc83f76599bb.jpg)

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 2.3.9
- Python Version: 2.7.12
- Operating system: windows7
- Anaconda Version: 4.1.1
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  1.6.4 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
This should be fixed in Spyder 3.0. Please update and try again :-)

**Comment by malliwi88** [comment]
Hi @orbitzhan, It solved your issue?

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by ali1100** [comment]
I have the Same problem
any help will be appreciated
