### ISSUE TITLE
3.0.0 in conflict with anaconda-navigator?

### ISSUE THREAD

**Issue by yulkang** [spyder-ide/spyder#3465]
## Description of your problem

**What steps will reproduce the problem?**

1. Open Terminal. Optionally switch to the conda virtual environment to install Spyder 3 with
`source activate spyder3`

2. Run:
`$ conda install -c spyder-ide spyder==3.0.0`

**What is the expected output? What do you see instead?**
I expected spyder 3.0.0 to be installed. I get the following instead:

```
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ....

The following specifications were found to be in conflict:
  - anaconda-navigator -> pyqt 4.*
  - anaconda-navigator -> python 3.4*|3.5*
  - spyder ==3.0.0

```

**Please provide any additional information below**

## Versions and main components

* Spyder Version: Trying to install 3.0.0. Currently have 2.3.9.
* Python Version: 2.7
* Operating system: Mac OS X Sierra (10.12)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.2.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  4.3.0 (OK)
pyflakes >=0.5.0   :  1.2.3 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.4.1 (OK)
sympy >=0.7.3      :  1.0 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by goanpeca** [comment]
Hi @yulkang thanks for reaching out, this will be fixed with the new release of Navigator coming tomorrow

**Comment by ccordoba12** [comment]
Closing then, as this is not a Spyder bug :-)
