### ISSUE TITLE
Spyder shows hour glass for one second then aborts start.

### ISSUE THREAD

**Issue by ollemonster** [spyder-ide/spyder#3466]
## Description of your problem

**What steps will reproduce the problem?**

1. open cmd, change directory to c:\python27\Scripts
2. run pip install -U spyder
3. try to run c:\python27\Scripts\spyder.exe from either explorer or cmd

**What is the expected output? What do you see instead?**
I expect some kind of user interface to come up.
Instead I see the hourglass for one second and then nothing more happens.

**Please provide any additional information below**
I use Python 2.7.12, Windows 7, I am administrator on the machine. I am not 100% sure I was running the cmd as admin when I ran the pip install but it reported thet installation as successful.
I have tried this on two different machines with the same versions of windows, python and spyder.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 2.7.12
* Operating system: windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please run Spyder from cmd like this

    spyder --show-console

and print the output here (if any :-)

**Comment by ollemonster** [comment]
Here you can see how it looks. First a normal start, then the one with show-console

C:\Python27\Scripts>spyder.exe

C:\Python27\Scripts>spyder --show-console

C:\Python27\Scripts>

**Comment by ollemonster** [comment]
I tried starting a cmd in admin mode, running pip uninstall spyder and then pip install -U spyder.
It did not improve the situation unfortunately.

**Comment by ollemonster** [comment]
I should also say, I did not have Spyder installed previously.

**Comment by ccordoba12** [comment]
I'm sorry but we can't help you if there's no more information available. I know you can't provide it, so this leaves both you and us in a dead end.

My only recommendation for you is to download and install Anaconda. That should work :-)

http://continuum.io/downloads.html

**Comment by msouff** [comment]
Got this same problem on a Windows 7 machine. I run spyder, it shows loading icon for one second and then does nothing.
