### ISSUE TITLE
Crash after addition of package

### ISSUE THREAD

**Issue by jsrhu** [spyder-ide/spyder#3467]
Addition of path to "ib" package using PYTHONPATH manager caused Spyder to crash after restart

Steps To Reproduce:
1. Install IbPy API
2. Add path to machine's Python site packages
3. Restart Spyder

Running <code> python spyder --reset </code> or any permutation of "spyder" yields:
<code>"python: can't open file 'spyder': [Errno 2] No such file or directory"</code>

* Spyder Version: 2.3.8
* Python Version: 2.7
* Operating system: OSX 10.11.6

**Comment by ccordoba12** [comment]
The way to reset spyder is by running:

    spyder --reset

You don't need to add `python` in front of it.

**Comment by jsrhu** [comment]
I forgot to mention that I have run the command with and without the <code>python</code> prefix and the terminal result is <code>-bash: spyder: command not found</code>.

I have also attempted to reinstall spyder by running <code>pip uninstall spyder</code> then the Spyder 2.3.8 dmg .

**Comment by jsrhu** [comment]
I managed to get Spyder working once again by executing <code>rm -r .spyder2</code> in my home folder where the config files were located

**Comment by ccordoba12** [comment]
:+1:
