### ISSUE TITLE
Cannot connect to existing ipython kernel after upgrading to 3.0

### ISSUE THREAD

**Issue by huyiqun** [spyder-ide/spyder#3472]
## Description of your problem

**What steps will reproduce the problem?**

From `connect to an existing kernel` and paste the kernel address obtained from `%connect_info` from another python program

**What is the expected output? What do you see instead?**
Expected to successfully connect. Instead see error message from internal console:

WARNING:root:kernel died: 3.00172996521
Traceback (most recent call last):
  File "/Users/h/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 898, in create_client_for_kernel
    password)
  File "/Users/h/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 1407, in _create_client_for_kernel
    kernel_client.load_connection_file()
  File "/Users/h/anaconda2/lib/python2.7/site-packages/jupyter_client/connect.py", line 417, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'--existing /Users/h/Library/Jupyter/runtime/kernel-200d2980-48d4-4c4a-a956-10c0249f01d0.json'

**Please provide any additional information below**
Spyder 2.3.9 is running just fine. After upgraded to spyder 3.0, this error occurred.

## Versions and main components

* Spyder Version: 3.0
* Python Version: 2.7.12
* Operating system: OS X (same from windows 7)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Where did you run `%connect_info`? In a notebook?

**Comment by huyiqun** [comment]
I have tried with notebook, qtconsole and atom (hydrogen).

**Comment by ccordoba12** [comment]
And where are exactly placed your kernel json files? I mean, in which directory?

**Comment by huyiqun** [comment]
I did not manually place them I think. `%connect_info' shows that it is at `/Users/h/Library/Jupyter/runtime/kernel-200d2980-48d4-4c4a-a956-10c0249f01d0.json` and I checked it is indeed there.
