### ISSUE TITLE
Some issues when connectiing to external kernels

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#3478]
I'm using mac
1.at before, when I put kernel-100.json in the kernel folder, I can type 100 in connect existing kernel and got connected. But when I updated to 3.0, when I type 100, it said that cannot find the kernel file.

2.when I connect to a remote kernel it says that the namespacebrowser cannot refresh since the entity namespacebrowser is None, I need to comment these several code to avoid the bug

**Comment by ccordoba12** [comment]
> when I put kernel-100.json in the kernel folder

What is your kernel folder?

**Comment by fayeshine** [comment]
@ccordoba12 
````
./.ipython/profile_default/security/kernel-100.json
./Library/Jupyter/runtime/kernel-100.json
```

**Comment by ccordoba12** [comment]
Ok, thanks :-) The first one doesn't work anymore because it's used by IPython 3.0 or less and we don't support those versions anymore.

The second one should work, so that's a bug in Spyder :-)

**Comment by ccordoba12** [comment]
I consider this is a duplicate of Issue #3472. That's why I'm closing it :-)
