### ISSUE TITLE
Spyder starts with an empty window with PyQt 5.7

### ISSUE THREAD

**Issue by golanguage** [spyder-ide/spyder#3479]
## Description of your problem
Using PIP install a spyder on win server 2012 R2 on vmware
First start, only show a empty window,.
When right-click on the window, pop up a correct right button menu list.
Can represent.
**What steps will reproduce the problem?**

1.  download and install python3.5, pyqt5.7, wrapt(http://www.lfd.uci.edu/~gohlke/pythonlibs/)
2.  pip install spyder 3
3. from a remote desktop session, start a  command window, print python mainwindows.py 

**What is the expected output? What do you see instead?**
show a debug info:
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions
Failed to load opengl32sw.dll (The specified module could not be found.)
Failed to load and resolve WGL/OpenGL functions.

And show a empty main window.

**Please provide any additional information below**
python qtconsole is work.

## Versions and main components

* Spyder Version:3.0.0
* Python Version:python3.5.2 64
* Operating system:Win2012R2 on VMware

## Dependencies
PyQt5.7

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by golanguage** [comment]
Hi, I read https://github.com/spyder-ide/spyder/issues/3332
download opengl32sw-64.7z from http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/
and decompress it to C:\Users\myname\AppData\Local\Programs\Python\Python35.

now it print :
Failed to load libEGL (The specified module could not be found.)
QWindowsEGLStaticContext::create: Failed to load and resolve libEGL functions

But I can see the spyder whole window now!

So, may our install pack can include it.

**Comment by golanguage** [comment]
Looks like it is pyqt5.7 issue.
It didn't install libegl.dll and libeglv2.dll.
I copy them to python3.5, spyder can startup without any complain.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.

**Comment by melsophos** [comment]
I can confirm this bug on Linux too. Downgrading to PyQt 5.6 (with pip) works well.

**Comment by ccordoba12** [comment]
@melsophos, so the problem is related to PyQt 5.7?

**Comment by melsophos** [comment]
Yes I think so since Spyder works well upon downgrading. I mainly wanted to confirm that it happens also for Linux and stress the solution for other users.

**Comment by ccordoba12** [comment]
Thanks a lot for the confirmation. This means that we need to check what's happening with PyQt 5.7 and fix it as soon as possible :-)

**Comment by ccordoba12** [comment]
@melsophos, the real problem behind this is that (it seems) PyQt 5.7 doesn't come with the necessary OpenGL libraries to run correctly.

As @golanguage said

> It didn't install libegl.dll and libeglv2.dll

Unfortunately, that's something that Spyder can do nothing about :-/
