### ISSUE TITLE
Spyder not launching

### ISSUE THREAD

**Issue by DrBwts** [spyder-ide/spyder#3481]
Win7, x64, conda 4.2.9

 Upgraded to Spyder 3 which wouldnt launch & gave the following traceback..

> (C:\Anaconda2) C:\Users\nr16508>spyder
> Traceback (most recent call last):
>   File "C:\Anaconda2\Scripts\spyder-script.py", line 2, in <module>
>     start_app.main()
>   File "C:\Anaconda2\lib\site-packages\spyderlib\start_app.py", line 114, in mai
> n
>     from spyderlib import spyder
>   File "C:\Anaconda2\lib\site-packages\spyderlib\spyder.py", line 155, in <modul
> e>
>     from spyderlib.utils.environ import WinUserEnvDialog
>   File "C:\Anaconda2\lib\site-packages\spyderlib\utils\environ.py", line 17, in
> <module>
>     from spyderlib.widgets.dicteditor import DictEditor
>   File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditor.py", line 39
> , in <module>
>     from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
>   File "C:\Anaconda2\lib\site-packages\spyderlib\widgets\dicteditorutils.py", li
> ne 61, in <module>
>     required_version=PANDAS_REQVER)
>   File "C:\Anaconda2\lib\site-packages\spyderlib\dependencies.py", line 70, in a
> dd
>     installed_version)]
>   File "C:\Anaconda2\lib\site-packages\spyderlib\dependencies.py", line 32, in _
> _init__
>     self.installed_version = programs.get_module_version(modname)
>   File "C:\Anaconda2\lib\site-packages\spyderlib\utils\programs.py", line 238, i
> n get_module_version
>     mod = __import__(module_name)
>   File "C:\Anaconda2\lib\site-packages\pandas\__init__.py", line 25, in <module>
> 
>     from pandas import hashtable, tslib, lib
>   File "pandas\src\numpy.pxd", line 157, in init pandas.tslib (pandas\tslib.c:10
> 5420)
> ValueError: numpy.dtype has the wrong size, try recompiling

So I reinstalled Spyder 2.3.8 (my previous version which was working fine) & now that gives the above traceback as well.

So now I cant do anything with Spyder :(

**Comment by Nodd** [comment]
The problem is with pandas or numpy, I suppose one of those was updated at the same time as spyder. Try updating both of them.

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with a wrongly installed Numpy.

Running

    conda install -f numpy

should fix it.
