### ISSUE TITLE
no session-history available in ipdb

### ISSUE THREAD

**Issue by lxkain** [spyder-ide/spyder#3482]
## Description

**What steps will reproduce the problem?**

1. debug a problem in an ipython console using ipdb
2. write any command, like "l"
3. hit the up-arrow

**What is the expected output? What do you see instead?**
Expected is to see "l" again. Instead the up/down arrow keys are ignored.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by lxkain** [comment]
Some research turned up that this is a problem with ipdb and qtconsole that is simply inherited. Hopefully they will fix it upstream.

**Comment by ccordoba12** [comment]
Yep, that's true :-)
