### ISSUE TITLE
Still only showing Spyder 2.3.9 in coda forge, 3.0 not available?

### ISSUE THREAD

**Issue by dartdog** [spyder-ide/spyder#3483]
## Description of your problem

**What steps will reproduce the problem?**

1. Just ran conda install spyder got Spyder 2.3.9 conda-forge ??? On Ubuntu 16.04 (64) with Anaconda 3.5 base
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by goanpeca** [comment]
Yes, sorry we need to update that recipe, will do today

**Comment by ccordoba12** [comment]
conda-forge is a community channel and not the official way to deliver conda packages.

Spyder is already in the default channels, so please pick it up from there until we find time to update our feedstock.

**Comment by dartdog** [comment]
Since I have added conda -forge how do I tell conda to select from conda instead? I just entered conda install Spyder and it defaulted to conda-forge

**Comment by ccordoba12** [comment]
It should be

     conda install -c defaults spyder

**Comment by dartdog** [comment]
Thanks!
