### ISSUE TITLE
sys.stdin

### ISSUE THREAD

**Issue by PedroMTQ** [spyder-ide/spyder#3488]
I've tried using the function sys.stdin in my script however while the script keeps running without returning any error, it won't let me input anything.
I've tried my code in "idle" and it was functional.
example code:

import sys
for i in sys.stdin:
    seq= i.strip()
    if seq == seq[::-1]:
        print ("sim")
    else:
        print("nao")

**Comment by ccordoba12** [comment]
Are you using the Python or the IPython console?

**Comment by PedroMTQ** [comment]
Ahah thanks.Didn't know I had to write it on the console and it would reply on the iPython console....
Started learning a few weeks ago and never encountered this.

**Comment by ccordoba12** [comment]
Ok.
