### ISSUE TITLE
Failed to open "/etc/machine-id": No such file or directory

### ISSUE THREAD

**Issue by alexbovet** [spyder-ide/spyder#3496]
Hi,

Thank you for this great application

After upgrading to spyder 3.0.0 from conda on my Ubuntu 14.04.5 LTS, it crashes at startup with the following message:

>  D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
  D-Bus not built with -rdynamic so unable to print a backtrace

This is easily fixed by creating a symlink:
ln -s /var/lib/dbus/machine-id /etc/machine-id

But it might be better to make spyder look in /var/lib/dbus as well?

**Comment by ccordoba12** [comment]
Thanks for reporting. Spyder doesn't depend directly on dbus, that's just a dependency of Qt5 in the conda ecosystem.

However, I just checked that this problem doesn't occur anymore with the latest dbus packages present in Anaconda. I think you're using an old dbus version (probably from the `qttesting` channel :-)

**Comment by prusswan** [comment]
I resolved this by installing `systemd` (not a default on 14.04)

**Comment by MaxiReglisse** [comment]
same problem on an old debian wheezy (7.11).
installing <systemd> solved the problem.

**Comment by ajmalafsal122** [comment]
sudo ln -s /var/lib/dbus/machine-id /etc/machine-id
