### ISSUE TITLE
Kernel died, restarting (repeats until stopped)

### ISSUE THREAD

**Issue by ro3c** [spyder-ide/spyder#3503]
## Description of your problem

**What steps will reproduce the problem?**

1. start spyder
2. 
3. 

**What is the expected output? What do you see instead?**
Kernel died, restarting 
Kernel died, restarting
Kernel died, restarting
Kernel died, restarting
Kernel died, restarting...

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0
* Python Version: 3.5
* Operating system: OSX 10.12 (Sierra)

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ro3c** [comment]
Added information

Fatal Python error: Py_Initialize: can't initialize sys standard streams
AttributeError: module 'io' has no attribute 'OpenWrapper'

Current thread 0x00007fffb326a3c0 (most recent call first):

**Comment by ccordoba12** [comment]
It seems you have a module called `io` somewhere in your PYTHONPATH or as part of a package you installed before installed Spyder.

Please try to install Spyder in a clean virtual or conda environment and try again.

**Comment by ccordoba12** [comment]
Well, what I said in my last message is basically what this Python bug says:

https://bugs.python.org/issue21202

So, there's nothing we can do in Spyder to solve it, sorry.

**Comment by ro3c** [comment]
Uninstalled and reinstalled in the same environment  and a clean one. Both seem to have fixed the problem.  io wasn't in the PYTHONPATH. I haven't figured out where it came from yet.

**Comment by ccordoba12** [comment]
Ok, glad to know you were able to solve this problem!

**Comment by ro3c** [comment]
Thanks for your help, and your time.
