### ISSUE TITLE
Scrolling up in IPython Console isn't easy during code execution

### ISSUE THREAD

**Issue by mat2py** [spyder-ide/spyder#3504]
When a code which contains lots of print statements is running it is not possible to scroll up through the output in the console as it always jumps back to the bottom when a new line is printed

I would expect it to act like the normal Linux console where, if you scroll up during code execution, you can scroll up normally and new printed lines simply add to the bottom but are hidden until you scroll back down. When you fully scrolled down then the screen moves down to accommodate the new lines that are printed.

This is an issue because, with very large scripts, I want to check things as they are running. 

You can sort of get the desired behaviour by holding the scroll bar on the right with the mouse and oscillating it up and down slightly so it jumps back up to where you are reading each time a new line is printed
- Spyder Version: Spyder 3.0.0.dev0
- Python Version: 2.7.12 64bit, Qt 5.6.0, PyQt5 5.6 on linux
- Operating system: Ubuntu 15.10

Maybe it's the same outcome as [this](https://github.com/spyder-ide/spyder/issues/3281) issue, that it's due to Qt and you guys can't do anything but I thought I'd submit it anyway, just in case you can

**Comment by malliwi88** [comment]
Hi @mat2py  

I check your issue with code presented on #3281 (Actually closed).

The code works fine :+1: 
![seleccion_009](https://cloud.githubusercontent.com/assets/5307894/19772230/2d3fe008-9c2b-11e6-9efd-48a03905f81f.png)

Please check your conda environment.

## Additional details
* Linux wallas-pc 4.4.0-2-deepin-amd64 #1 SMP Deepin 4.4.6-4 (2016-07-01) x86_64 GNU/Linux
* Python Version: 2.7.12 64bit, Qt 5.6.0, PyQt5 5.6
* Spyder (3.0.1,  3.0.1-dev0, 4.0.0-dev0)

## Dependences
> jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by mat2py** [comment]
Hey @malliwi88 , that issue you reference is a different and unrelated issue.

That issue: When running a script and you're at the end of the window, the window should keep scrolling down to see all the text as it is printed but that doesn't always happen

This issue: When running a script and you're NOT at the end of the window, it keeps jumping to the bottom when new stuff is printed, even though you're trying to read something that is higher up in the window

**Comment by malliwi88** [comment]
@mat2py  the link on 

> Maybe it's the same outcome as [this](https://github.com/spyder-ide/spyder/issues/3281) issue....

redirect to https://github.com/spyder-ide/spyder/issues/3281, in short, it is no longer important.

Could you give us some code that presents the problem? so we can help you.

**Comment by mat2py** [comment]
It isn't the same as that issue! Please read my comment above which explains the difference (they're opposite issues).

Literally any code will cause what I explained to happen as it is the way it has been designed. FOr example:

```
import time
for i in range(0,1000):
    time.sleep(0.5)
    print(i)
```

Try to scroll up in the middle of that code running (for example if you wanted to see an earlier output)

**Comment by malliwi88** [comment]
Hi @ccordoba12 

Unfortunately, this seems not to be within my domain for the case of the Ipython console that I believe built Carlos

However, I believe that what is said [here][1] could solve the problem

Precisely the problem has been touched as Issue by Ipython (https://github.com/ipython/ipython/issues/2172)

Finally, I would like to mention that this problem is not only present in our console of Ipython, but with all.

I do not know what you think about it @ccordoba12


[1]:<https://github.com/minrk/ipython_extensions/blob/master/extensions/disable_autoscroll.py>

**Comment by ccordoba12** [comment]
This is something that needs to be solved in qtconsole.

**Comment by mat2py** [comment]
Any progress on this issue? The [roadmap](https://github.com/spyder-ide/spyder/wiki/Roadmap) suggests that the V3.2.1 milestone will be released in June 2017 (this month) but I'm not sure how accurate that milestone and roadmap are.

**Comment by ccordoba12** [comment]
No progress, sorry.

**Comment by randomgambit** [comment]
guys this is indeed a bit annoyting, because then I cannot check my code while it is running... thanks!

**Comment by jnsebgosselin** [comment]
@ccordoba12 I'll take care of this one.I have almost a working solution already.

**Comment by ccordoba12** [comment]
Thanks @jnsebgosselin! Those are great news!!

I have thought for years how to solve this but haven't came up wit good ideas to do it.
