### ISSUE TITLE
How to disable automatic search for updates at startup?

### ISSUE THREAD

**Issue by randomgambit** [spyder-ide/spyder#3505]
Hello,

I am using the latest version of Anaconda and every time I start `Spyder 3` on my windows machine, I get an error message saying unable to connect to the internet, make sure the connection is working properly.

I am behind a firewall, and this error is rather annoying cause it make the kernel crash a couple of time before I get this error message and I am able to start coding.

Is it possible to disable this automatic update feature?

Many thanks!

**Comment by goanpeca** [comment]
Hi @randomgambit you can disable this in the Advanced section of the general preferences

**Comment by ccordoba12** [comment]
@goanpeca, should we disable this feature by default? I mean, it can be problematic and/or annoying (as this example shows :-)

**Comment by goanpeca** [comment]
We could ask on first startup if the user wants to opt int for this.

**Comment by jitseniesen** [comment]
It would also be good if we could fix the kernel crash ...

**Comment by ccordoba12** [comment]
I think we should disable checking for updates by default then :-)

**Comment by Nodd** [comment]
Disabling it by defaolt would be effectively the same as removing it, because only a few people change options.  The idea was to avoid bug reports from users using old versions. It should be possible to disable the check from the popup window however, so that users not wanting it can disable it easily.

**Comment by stonebig** [comment]
Even if I changed the default, at first Spyder opening, there is a connexion attempt (because the init file is not yet created ?).

**Comment by ccordoba12** [comment]
Closing because we're going to take action on this one.

**Comment by ukreddy-erwin** [comment]
How to disable this through command prompt or any setting on the system for windows.

**Comment by ukreddy-erwin** [comment]
Is there any machine specific file where it can be applied to all the users in the machine?
