### ISSUE TITLE
Error in executing Machine learning Algorithms

### ISSUE THREAD

**Issue by dashsantosh** [spyder-ide/spyder#3514]
# Error-
**return self.decode(bytes, 'strict')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 37: ordinal not in range(128)**
![error in ml programs](https://cloud.githubusercontent.com/assets/14981657/19211756/cdfb3606-8d61-11e6-983c-03edfa76e6fa.png)

**Comment by ccordoba12** [comment]
Sorry, but this is an error in the `nltk` package or in the way you're using it.

Since this is not a Spyder error, I'm closing this issue :-)
