### ISSUE TITLE
Spyder 3.0 does not start on windows 10

### ISSUE THREAD

**Issue by Rabijns** [spyder-ide/spyder#3515]
I'm using python(x,y). However, it comes with an older Spyder release (version 2.??). 
So I tried using pip to upgrade.

The steps I followed are:

1. use the way mentioned on the spyder website, being "pip install --update spyder". This results in an error, saying that --update does not exist. (potentially a small error on the website??)
2. use :"pip install --upgrade spyder".  This seems to work. A lot of packages are also upgraded, some other packages removed.

When I select spyder in the windows start menu, the splash screen appears (allowing to confirm it is indeed spyder 3 and not the old one that is starting). The splash screen disappears again, but spyder 3 does not start.
The windows task manager shows 3 processes with the name "pythonw.exe (32 bit)" running.

If I try to start Spyder 3 a second time, the following happens:

1. splash screen appears
2. additional warning srceen appears, telling me that spyder crashed during the last session and asking to do a "python spyder --reset".
3. If I click ok, the splash screen appears again. At the bottom, I can see some modules/ parts are loaded. The last one mentioned before the splash screen disappears, is "loading Ipython console".
Again, three processes "pythonw.exe (32 bit)" are running, but no spyder 3.

Additional things I tried:

1. Running Spyder 3 via anaconda works, but anaconda unfortunately caused other issues, so was removed again. (and computer completely cleaned to remove all hidden traces of anaconda.)
2. I tried the proposed "python spyder --reset": no solution
3. I have a screen calibration tool, which is also called spyder 3. I unloaded it, as you never know there could be a naming conflict. No improvement. 
4. Starting Spyder (light): no splash screen, no warnings or alarm, but also no result.
5. starting Ipython  console from the windows start menu: this works, even if I have two windows "IPython QT Console" (a dos style box) with 3 warnings, and "Jupyter QtConsole" with the working python console.

I noticed that a Spyder log file is created. You can find it attached below.

Technical info:

- Python(x,y)-2.7.10.0
- windows10 pro  anniversary update installed -64 bit
- Python 2.7.10
- intel I5-3570, 16GB RAM

Issue might be the same as #3509, but #3509 does not provide the necessary info to be sure.

[spyder_crash.log.txt](https://github.com/spyder-ide/spyder/files/518198/spyder_crash.log.txt)

**Comment by ccordoba12** [comment]
> Running Spyder 3 via anaconda works, but anaconda unfortunately caused other issues

Sorry, but that's the only Python distribution we currently support. For other distributions (e.g. PythonXY and WinPython) you need to report errors with them.

And, as you said, Spyder is working with Anaconda. Sorry to hear that Anaconda is causing you other issues, but unfortunately, we can't help you with that :-)

**Comment by Rabijns** [comment]
Thanks for the reaction.
I'm somewhat surprised by your answer, saying that you only support Anaconda. Python(x,y) is mentioned as a way to get Spyder on the main Spyder page on Github. (together with anaconda and winpython)
I understand that you have plenty of work with Spyder itself and cannot deal with the different distribution packages. I'll see if I can find a solution somewhere else.

**Comment by ccordoba12** [comment]
> I'm somewhat surprised by your answer, saying that you only support Anaconda

It's true that PythonXY and WinPython come with Spyder, but they are independent projects, with their own maintainers and issue trackers. And among the two, I'd recommend you to use WinPython because it's better maintained and more up to date.

The error you report with PythonXY has been reported before, and it's really due to the fact that PythonXY hasn't been updated in quite some time.

We support Anaconda because we know how it works very well and also because Continuum supports Spyder development.

**Comment by LA1824** [comment]
I have been getting this window, but the spyder interface is not loading up.
Anaconda Navigator 1.8.7
Spyder 3.2.8
Windows 10 64-bit
It seems the spyder is running, but it doesn't show on screen.
Tried everything reset, installing pyqt5, show console, re-installation, spyder upgrade.
Tried opening it with terminal and it doesn't throw any error, rather it showed me the same screen attached image.
![loading editor problem](https://user-images.githubusercontent.com/33568902/42009906-eef532f8-7aa9-11e8-90e3-95dfde1f2f6c.png)

**Comment by pehua** [comment]
Hello, I have the same problem with spyder3 with winpython.
Anyone that can help?


![image](https://user-images.githubusercontent.com/41135285/42610578-99ebdd06-8568-11e8-82e8-f66ba00be5ca.png)

thanks.
