### ISSUE TITLE
Spyder hangs with big numpy structured arrays

### ISSUE THREAD

**Issue by harryhobson** [spyder-ide/spyder#3518]
## Description

**What steps will reproduce the problem?**

1. run the following (may need to increase num_entries to notice problem) 

    ```python
    import numpy as np
    num_entries = 1000
    my_data = np.zeros(num_entries, dtype=[('ID','f8'),('param1','f8',5000)])
    ``` 
2. wait for variable to appear in 'variable explorer'

**What is the expected output? What do you see instead?**
`my_data` should appear in variable explorer and allow me to continue working. Although the variable eventually appears, spyder frequently hangs and sometimes if I wait I receive seg faults.

**Please provide any additional information below**
Using an exclusion rule to remove the var from the variable explorer stops the hanging.

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 2.7.12
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by jitseniesen** [comment]
Thank you for the report. I can confirm the problem. Spyder can deal gracefully with big(ish) arrays, but not in this case.
