### ISSUE TITLE
Warning message on start

### ISSUE THREAD

**Issue by kuo000** [spyder-ide/spyder#3521]
## Description of your problem
I recently upgraded spyder to version 3 in my virtual Python environment (simply using `pip install -U spyder`). Now upon launching spyder, I always see the following warning:

> void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "Project explorer" under id 124

Though this has not affected anything I can notice, I was wondering what this warning is about and how to make it go away.

**What steps will reproduce the problem?**

1. In my Python virtual environment, launch spyder with `spyder` at a command-line terminal.

**What is the expected output? What do you see instead?**
I expected nothing printed on the terminal output (which was the case before I upgraded spyder). A warning message is printed instead.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 2.7.12
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I think this is harmless. It's just that we are using the same action in two different places in our menus :-)
