### ISSUE TITLE
No more refresh button in variable explorer in Spyder 3.0.0

### ISSUE THREAD

**Issue by Halipster** [spyder-ide/spyder#3523]
I can't find a way of manually refreshing the variable explorer in Spyder 3.0.0 while a script is running. I used to use the refresh button to monitor the progresses of time consuming scripts without the need of manually add a print(i, "/", N) in any loop or so. Could we have it back ?

**Comment by ccordoba12** [comment]
In 3.0 we changed how the Variable Explorer is connected to the IPython Consoles, so refreshing it is not possible anymore while the kernel is running a computation.

So I'm afraid to say that this feature is not coming back, sorry :-/

**Comment by Halipster** [comment]
Ok. I think I will change my habits then. It probably was bad habits anyway. Thanks for improving Spyder by the way.

**Comment by ccordoba12** [comment]
Thanks for understanding ;-)
