### ISSUE TITLE
Ctrl+C have different behaviour in console

### ISSUE THREAD

**Issue by Alexander-Minyushkin** [spyder-ide/spyder#3525]
## Description of your problem

Context menu in console suggest that Ctrl+C can be used to copy text. However during execution of command Ctrl+C will abort execution, without copying of selected text.

**What steps will reproduce the problem?**

1. Select text in console while no command running. Press Ctrl+C. On Ctrl+V selected text is available.
2. Run long command in console. Select text in console. Press Ctrl+C.  Execution aborted. Selected text not available on Ctrl+V

**What is the expected output? What do you see instead?**
Either copy text in both cases or don't copy text on Ctrl+C but abort execution if any.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: Python 2.7.12 64bits, Qt 5.6.0, PyQt5 5.6
* Operating system: Windows

**Comment by ccordoba12** [comment]
If you're executing something, then `Ctrl+C` tries to abort a computation. That's hard coded so (unfortunately) we can't change it.

What you can do while a computation is running is using the context menu entry to copy text, instead of pressing `Ctrl+C` :-)
