### ISSUE TITLE
after pressing F9 on line does not position on new line in ipython console

### ISSUE THREAD

**Issue by kkonevets** [spyder-ide/spyder#3526]
## Description

**What steps will reproduce the problem?**
1. select variable with mouse and press F9, try to press on other variable if not reproducing, then pres on the first one
   ![screenshot from 2016-10-12 15 39 01](https://cloud.githubusercontent.com/assets/16817116/19310356/b3d680c8-909a-11e6-8cc3-588f8ebd914c.png)
2. mfybe a problem with arrays and data frames
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
## Version and main components
- Spyder Version: 3.0.0 
- Python Version: 3.5.2
- Qt Versions: 5.6.0, PyQt5 5.6 on Linux
## Dependencies

```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by malliwi88** [comment]
Hi @kkonevets 

![seleccion_010](https://cloud.githubusercontent.com/assets/5307894/19784272/c2ef53b6-9c5a-11e6-9fd3-4d5b6c7eb207.png)

This does not seem to be a problem in version 3.0.1. I recommend you update your spyder.

Anyway, thanks for your report this allows us to make even better spider :+1:

**Comment by kkonevets** [comment]
Hi!
Thank u for reply.
Yeah, it works but not always. I don't know, maybe cause I use Linux, Ubuntu 14.04
I have the same error on latest version 4 from github.

⁣​

На 27 окт. 2016 г., 23:35, в 23:35, William Javier Trigos Guevara <notifications@github.com> написал:п>Hi @kkonevets

**Comment by malliwi88** [comment]
Yeah @kkonevets, ït's possible, some days ago I had a similar problem with Xubuntu 15.10. So I'm on 16.04 now. 

Please, let know us, how are you with this issue when you change your version. I will be careful of your response .

Thanks for your report, have you a nice day.

**Comment by ccordoba12** [comment]
This is too old to be applicable now.
