### ISSUE TITLE
Variable explorer table needs a horizontal scroll bar

### ISSUE THREAD

**Issue by roger-** [spyder-ide/spyder#3530]
On Spyder 3.0.0 double clicking on a variable in the variable explorer brings up a table view with all of the variable's properties/elements. If the "Value" field is big there's no way to scroll horizontally to see everything.

**Comment by goanpeca** [comment]
Hi @roger- could you paste a screenshot?

**Comment by Nodd** [comment]
You need to make the column wider to be able to scoll the view.
As for spyder it should be possible to adapt the size to the content automatically

**Comment by roger-** [comment]
@goanpeca 
Sure, see this:
![capture](https://cloud.githubusercontent.com/assets/1389709/19348675/19c97d86-911d-11e6-98cb-b698449ffe51.PNG)

@Nodd
Yes, you're right that the scroll bar does show up when you manually adjust the column width. I do feel like this should be automatically done.

**Comment by joaoppc** [comment]
I would like to work on this Issue

**Comment by ccordoba12** [comment]
Please do. Just remember to do it against our master branch.

**Comment by dalthviz** [comment]
Checking this with the latest Spyder (5.3.0). Seems like this is not an issue anymore:

![imagen](https://user-images.githubusercontent.com/16781833/168893592-64c774be-77d5-4e02-955b-36387aa3b9e5.png)

And also the `resize rows/columns to contents` actions are available:

![resize](https://user-images.githubusercontent.com/16781833/168893972-26639f20-9e0e-4297-b828-3c8cc77d21cb.png)

Should we close this one @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yep, I can confirm this is no longer an issue.
