### ISSUE TITLE
Spyder problems on OS X.

### ISSUE THREAD

**Issue by danche354** [spyder-ide/spyder#3536]
HI, when I use Spyder IDE, I come across some problems.
1.  Why can not choose 'Monaco' font for editor? There are only 5 fonts for choose... 
2. When split the code with '#%%', the highlight was not continuous. It was not comfortable.
   <img width="489" alt="2016-10-14 8 32 20" src="https://cloud.githubusercontent.com/assets/11846497/19371795/d1fc6f78-91e8-11e6-81f4-8b69d4cd3b24.png">
3. Why strange character was appeared in python console when starting it before '>>>'?
   <img width="383" alt="2016-10-14 8 33 31" src="https://cloud.githubusercontent.com/assets/11846497/19371866/6bc5a7f0-91e9-11e6-8596-cec8a6312848.png">
## Versions and main components
- Spyder Version: 3.0.0
- Python Version: 3.5.2
- Operating system: OS X EI Captian

**Comment by ccordoba12** [comment]
What are your Qt and PyQt versions?

**Comment by danche354** [comment]
@ccordoba12 
Qt 5.6.0
PyQt5 5.6 on Darwin

**Comment by ccordoba12** [comment]
I'm sorry but we can't help you with this problem. I have no idea where it could be coming from :-/
