### ISSUE TITLE
Spyder fails to launch because of Unicode errors in create_kernel_spec

### ISSUE THREAD

**Issue by eunsoo** [spyder-ide/spyder#3553]
## Spyder Launch Error

When I run spyder on command line, I got error message like below.

> Traceback (most recent call last):   File
> "/home/park/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py",
> line 2998, in main
>     mainwindow = run_spyder(app, options, args)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py",
> line 2902, in run_spyder
>     main.setup()   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py",
> line 1153, in setup
>     self.setup_layout(default=False)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py",
> line 1414, in setup_layout
>     self.setup_default_layouts('default', settings)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py",
> line 1593, in setup_default_layouts
>     widget.toggle_view(True)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py",
> line 677, in toggle_view
>     self.create_new_client(give_focus=False)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py",
> line 886, in create_new_client
>     self.connect_client_to_kernel(client)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py",
> line 903, in connect_client_to_kernel
>     km, kc = self.create_kernel_manager_and_kernel_client(connection_file)   File
> "/home/park/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py",
> line 1276, in create_kernel_manager_and_kernel_client
>     kernel_manager._kernel_spec = self.create_kernel_spec()   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py",
> line 1256, in create_kernel_spec
>     uv = to_text_string(v)   File "/home/park/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py",
> line 136, in to_text_string
>     return unicode(obj) UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 73: ordinal not in range(128)

**I have tried**
1. Reinstall using "pip install spyder"
2. Reinstall using "conda install spyder"
3. On the command line "spyder --reset" 

**Version Information**(
- Spyder Version: 3.0
- Python Version: 2.7.12
- Operating system: Ubuntu 14.04
- Anaconda Version : 4.2.0

How do I fix it. If you give me some ideas, I can really appreciate for this.

Thanks.

**Comment by jitseniesen** [comment]
@eunsoo, as was asked on #3127, could you please include the output of running

    printenv

in a terminal (i.e. in bash or zsh :-) For some reason, a non-ascii character (perhaps Hangul) has crept in. 

If you can switch to Python 3, that might turn out to help, as Python 3 is generally better with non-ascii characters.

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, please work on this one. To reproduce it, please create a conda environment with all Spyder dependencies in a directory with non-ascii chars (e.g. `/tmp/añño`), and run Spyder from it.

I think that would reproduce this problem, but if not, please let me know about it :-)

**Comment by mariacamilaremolinagutierrez** [comment]
@ccordoba12 I was not able to reproduce the error, I was trying several configurations. But only until now I realized all this time I was using python 3.5, so I am going to install it again with python 2.7

**Comment by ccordoba12** [comment]
Ok, thanks :-)

**Comment by mariacamilaremolinagutierrez** [comment]
I was able to reproduce it by naming the conda environment with a non-ascii character:

![image](https://cloud.githubusercontent.com/assets/3608776/19870178/78c99b40-9f7d-11e6-905b-0cd8d98b65c9.png)

I will find out later today how to fix that

**Comment by ccordoba12** [comment]
This means that Python itself doesn't even work when installed in a non-ascii dir on Unix systems, but that's not directly related to the original problem :-/

We'll discuss about this in our meeting, please work on your other issue instead :-)
