### ISSUE TITLE
Crash at launching

### ISSUE THREAD

**Issue by araoux** [spyder-ide/spyder#3554]
Hi,

Since I upgraded to Ubuntu 16.10, Spyder won't start. When I try to launch it, I get the following message:

> Spyder crashed during last session.
> 
> If Spyder does not start at all and before submitting a bug report, please try to reset settings to defaults by running Spyder with the command line option '--reset':
> python spyder --reset
> 
> Warning: this command will remove all your Spyder configuration files located in '/home/raoux/.spyder2-py3').
> 
> If restoring the default settings does not help, please take the time to search for known bugs or discussions matching your situation before eventually creating a new issue here. Your feedback will always be greatly appreciated.

And in the terminal:

> (python3:7342): Gtk-WARNING **: Theme directory base/ of theme oxygen has no size field

I tried rebooting, uninstalling, and so on, nothing has worked.

Ubuntu 16.10
Python3.5
Spyder3

Thanks in advance for your help!

A. R.

**Comment by ccordoba12** [comment]
How did you update Spyder? With pip, conda or using apt-get?

**Comment by araoux** [comment]
Yes, with apt and pip.
The same message for spyder and spyder3.

**Comment by golanguage** [comment]
Same bug on my Ubuntu16.10

**Comment by vdyashin** [comment]
@araoux , @golanguage , @Holoratte 
Had the same problem. I just closed IDE and it did not start. 

_I managed to understand how to solve it only by accident. I am new in Ubuntu, Python. So, please be sure that by repeating this guide you will not hurt your system._

Solved by installing PyQt5 (which is recommended for successful installation.)
`sudo pip3 install PyQt5`.

And please let me know if it worked out for you.

**Comment by vdyashin** [comment]
@araoux , @golanguage , @Holoratte 
Had the same problem. I just closed IDE and it did not start. 

_I managed to understand how to solve it only by accident. I am new in Ubuntu, Python. So, please be sure that by repeating this guide you will not hurt your system._

Solved by installing PyQt5 (which is recommended for successful installation.)
`sudo pip3 install PyQt5`.

And please let me know if it worked out for you.

**Comment by araoux** [comment]
Thanks for the tip. However, it is still not working for me.

**Comment by ccordoba12** [comment]
Please use [Anaconda](http://continuum.io/downloads.html) to install Spyder, it should be better than using the PyQt5 packages because of issue #3520.

**Comment by ccordoba12** [comment]
@Holoratte, the problem with QtWebkit is an Ubuntu problem. They broke Spyder by removing that module, so you can't use Spyder from `apt-get` for now :-)

**Comment by ccordoba12** [comment]
Closing because this is a Debian/Ubuntu problem because they decided to intentionally break Spyder.

**Comment by sbyrnes321** [comment]
ubuntu / debian issue is at: https://bugs.launchpad.net/ubuntu/+source/spyder/+bug/1620300

**Comment by yashyks** [comment]
sir I am facing problem of 
Attribute error: ' module' object has no attribute '_base'
