### ISSUE TITLE
Spyder 3 can't inspect values through the variable explorer while debugging

### ISSUE THREAD

**Issue by yucheng90** [spyder-ide/spyder#3555]
When I debug a script using IPython console in spyder 3.0.0, I can see my variables listed in the variable explorer but when I try to inspect any variable there is an error message pops up. I think inspecting variables (especially DataFrame) while debugging was doable in spyder 2.3.8. I also tried debugging in Python console and there was no error message and I can check (double click) any variable through the variable explorer.

**What steps will reproduce the problem?**
The attached screenshot shows my script file and the error message.

**Please provide any additional information below**
![screenshot](https://cloud.githubusercontent.com/assets/16459229/19504564/db072ce4-95ed-11e6-939d-0089ac13c9e7.png)
## Versions and main components
- Spyder Version: 3.0.0
- Python Version: 2.7.11
- Operating system: Win 8
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.18.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. The error message is quite clear: this is still not supported yet, and probably it won't be until Spyder 4.0 :-)

**Comment by ccordoba12** [comment]
The thing is we internally changed how Spyder interacts with IPython kernels, so inspecting variables while debugging is not so easy anymore :-)

**Comment by AndyCash1** [comment]
I understand this question has been answered, but this issue is a show stopper for me.  The ability to easily inspect and visualize variables like dictionaries and dataframes while debugging is the main reason why I use the Spyder IDE over others.  Thus, I will continue to use Spyder 2.3.9 for now.

I would be curious to understand the logic behind this decision, and what the timeframe for it's implementation in Spyder 3.X is.  Thank you.

**Comment by ccordoba12** [comment]
@AndyCash1, we decided to restructure the way we create and connect to IPython kernels to make that process much more robust. In Spyder 2.3 it was very, very brittle and so we had lots of complaints about it.

We'll try to restore this in Spyder 3.1 but I can't make promises about it.

**Comment by gilgtc** [comment]
I completely agree with @AndyCash1. Sure it is always a good idea to fix issues but not at the expense of removing one of the most important tools for debugging.

**Comment by asmwarrior** [comment]
@camendoza94 I also need this feature while debugging under Spyder 3.1.2. If you remove Python console in Spyder 3.2, do you restore this feature in Spyder 3.2?

**Comment by ccordoba12** [comment]
You're right. We'll fix this in Spyder 3.2

**Comment by CharlesVellutini** [comment]
Hi, glad this will be fixed in 3.2. To us too, this is a critical feature. Closely related to issue #4013 I think.

**Comment by AndyCash1** [comment]
Excellent, happy to hear this feature will be put back in.

**Comment by mmartini-usgs** [comment]
Yes, please fix this.  Spyder was sweet when the variable inspection was working.

**Comment by ccordoba12** [comment]
This is going to be fixed in Spyder 3.2 (to be released in two months or so).

**Comment by Davo36** [comment]
Oh man, thanks, can't wait.  As others have said, I think the debugger and the ability to examine variables are one of the most important things in Spyder.

**Comment by daofeng2007** [comment]
Is there any alternative IDE that currently has this feature?

**Comment by ccordoba12** [comment]
> Is there any alternative IDE that currently has this feature?

Not that I know of. But good place to ask for the competition, eh? ;-)

**Comment by CharlesVellutini** [comment]
@daofeng2007 Spyder 2.3.9 is great and has this feature. Strongly recommended until Spyder 3.2 is out (which, I understand will have this feature back).

**Comment by daofeng2007** [comment]
@CharlesVellutini Thanks man. I just downgrade to Spyder 2.3.9. It's really a remedy for my hard day.

**Comment by krameris** [comment]
I agree that this should be given priority. This feature is critical for my work.

**Comment by ccordoba12** [comment]
This is basically solved in PR #4202. We just need to add tests to it.

**Comment by nehalahri** [comment]
I am facing simmilar issue. Nothing is visible in variable explorer. 
Can someone help me in installing Spyder 2.3.9. 
I tried downloading zip file from https://pypi.python.org/pypi/spyder/2.3.9 and followed instruction to install. But application crashes when I try to launch. Am I missing anything ?

**Comment by Davo36** [comment]
Hi nehalahri, I have the Anaconda distribution.  I have 2 machines that I downgraded to 2.3.9.  And I had to do it differently on each one!

The first I used anaconda commands to remove the current version of spyder and install 2.3.9:

conda remove spyder
conda install sypder=2.3.9

This worked for my desktop but not my laptop.  For that, I used the Anaconda Navigator program.  If you launch that, then, for each app you can start, there is a little settings wheel in the top right of the box around the app.  Click on that and choose to install a specific version. 

Best of luck.

Can't wait for 3.2....

**Comment by nehalahri** [comment]
Thanks Davo36, 
I found another fix which is working for me. I am using python console now and then change display options on variable explorer it refreshes variable to display and all variable are visible on variable explorer. Apart form this way of refreshing variable explorer everything is working smoothly.

**Comment by JoshuaC3** [comment]
How can I update to 3.2? The in IDE pdate only check up to 3.1.4. Thanks

**Comment by ccordoba12** [comment]
It has not been released yet. It will be in a week or two.

**Comment by amehrish** [comment]
Hi, Can you please confirm if this has now been fixed in the new release 3.2.1? I am currently using 2.3.9 because of the debugger issue.

**Comment by CharlesVellutini** [comment]
Hi all,

I just tested it and it works for me. Debugging functionalities back to normal in v3.2.1
Thanks a lot for your great work.
Charles

De : amehrish [mailto:notifications@github.com]
Envoyé : vendredi 1 septembre 2017 16:17
À : spyder-ide/spyder <spyder@noreply.github.com>
Cc : Charles Vellutini <charles.vellutini@ecopa.com>; Mention <mention@noreply.github.com>
Objet : Re: [spyder-ide/spyder] Spyder 3 can't inspect values through the variable explorer while debugging (#3555)


Hi, Can you please confirm if this has now been fixed in the new release 3.2.1? I am currently using 2.3.9 because of the debugger issue.

**Comment by ccordoba12** [comment]
@CharlesVellutini, thanks for testing!

**Comment by amehrish** [comment]
Thank you Charles and Carlos! Appreciate it.
