### ISSUE TITLE
whenever you press enter on `for x in xs]`, it adds a colon

### ISSUE THREAD

**Issue by jkabrg** [spyder-ide/spyder#3556]
## Problem description

Whenever there's a multiline list comprehension where the last line ends in `for x in xs]`, and you press enter on the end of the last line, it adds a colon.

**How to reproduce the problem**

Enter the following into Spyder
```
[x
for x in xs]
```
then press enter on the last line; it should add a colon.

**Expected output**

No colon.

## Versions and main components

* Spyder Version: 2.3.8

## Dependencies
IPython >=1.0      :  4.0.1 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  3.3.0 (OK)
pyflakes >=0.6.0   :  1.0.0 (OK)
pygments >=1.6     :  2.0.2 (OK)
pylint >=0.25      :  1.4.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.1.0 (OK)

**Comment by jitseniesen** [comment]
This should be fixed in Spyder 3.0 (see PR #3177) so I suggest you upgrade. Feel free to re-open the issue if the problem persists for you.
