### ISSUE TITLE
Auto completion balloon hides after time (opportunity to tweak)

### ISSUE THREAD

**Issue by vdyashin** [spyder-ide/spyder#3557]
## Description

**What steps will reproduce the problem?**

0. Turn on the autocompletion and ballons in Preferences-->Editor (if you do not use it for some reason).
1. For example, type `map` in the Editor or IPython console. (do not hit Enter or anything else)
2. Then add an opening parenthesis: `map(`. You should see a balloon with function help (agrs etc).
3. If you do not hold your cursor on that balloon it will be hidden after a couple of seconds.

**What is the expected output? What do you see instead?**
I expected to have an opportunity to tweak the time after help balloon is hidden (for example, never hide the autocompletion balloons while writing arguments of a function) in Preferences. 

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
numpy >=1.7      :  1.11.0 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for rerporting. This is going to be fixed in #3296.

**Comment by vdyashin** [comment]
@ccordoba12 sorry have not seen that.

**Comment by ccordoba12** [comment]
No worries ;-)
