### ISSUE TITLE
For a Pandas Serie containing NaN, Spyder IPython console is "flud" by error message

### ISSUE THREAD

**Issue by thierryBottaro** [spyder-ide/spyder#3558]
let's assume mySerie is containing a NaN value.
When I type "mySerie.to_csv(" then the following error message is written at the prompt, forbidding me to write any further. 
I guess the "mySerie" is getting somehow evaluated by the Help or the auto-completion.
I tried to disable the automatic Help, it did not change anything

## Reproducing the problem 
in IPython console, execute this line :
`import pandas as pd
mySerie = pd.Series([1,2,3]).diff()`

execution "mySerie" result to this output : 
`C:\Program Files\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\pandas\core\format.py:2087: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e8).any()
C:\Program Files\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\pandas\core\format.py:2088: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) &
C:\Program Files\WinPython-64bit-3.4.4.1\python-3.4.4.amd64\lib\site-packages\pandas\core\format.py:2089: RuntimeWarning: invalid value encountered in greater
  (abs_vals > 0)).any()
Out[74]: 
0   NaN
1     1
2     1
dtype: float64
`

typing (without executing) `mySerie.to_csv(` will trigger the same error message. It is hard to write a complete command due to this.

## Versions and main components
I installed WinPython-64bit-3.4.4.1 which is officially including : 
* Spyder Version:
spyder3.0b4+  (but it is still frustrating to see only 3.0.0dev in the About dialog)
* Python Version:
3.4.4 64 bits
* Operating system:
Win 7, 64bit

## Dependencies
IPython >=3.0      :  4.1.1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)   <== possible source of problem  ?
matplotlib >=1.0   :  1.5.1 (OK)
numpy >=1.7        :  1.10.4 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.6.0   :  0.9.2 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  1.5.4 (OK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.4       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=13.0.0       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
This was fixed in Spyder 2.3.9 and it's also fixed in Spdyer 3.0, please update :-)
