### ISSUE TITLE
add feature to do auto-completion without casesensitivity

### ISSUE THREAD

**Issue by kalbhairab** [spyder-ide/spyder#3559]
please make auto complete without case sensitivity

**Comment by goanpeca** [comment]
Hi @kalbhairab we will work on it for a next release :-)

**Comment by jpoeppel** [comment]
I think this might be related to #3385, as a fuzzy search would most likely be case insensitive, would it not?

**Comment by malliwi88** [comment]
Working on it. @goanpeca

**Comment by goanpeca** [comment]
:+1:

**Comment by malliwi88** [comment]
Hi @kalbhairab 

Could you give us details about What or Why you looking for this feature?
One explicit example for evaluating your request? please.

**Comment by goanpeca** [comment]
@kalbhairab we already have an option for doing this if you go to preferences, editor and introspection section, there is a checkbox 

Have you used that yet?

<img width="734" alt="screen shot 2016-11-11 at 10 25 19 am" src="https://cloud.githubusercontent.com/assets/3627835/20219850/2e342490-a7f9-11e6-808d-951ed56ee92d.png">
