### ISSUE TITLE
Permanently visible index column in DataFrame viewer

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3562]
I notice the following in the DataFrame viewer:

When scrolling down, the row of column names (df.columns) stay permanently visible.
However, when scrolling right, the index column (df.index) scrolls off to the left. It should be kept visible instead.

(This was previously discussed at https://groups.google.com/forum/#!topic/spyderlib/oWi3Rls_rAo .)

I am using WinPython-64bit-3.5.2.2, with
- Spyder Version: 3.0.0b5
- Python Version: 3.5.2
- Operating system: Windows 7 64-Bit

For dependency info see [spyder-dependencies.txt](https://github.com/spyder-ide/spyder/files/540976/spyder-dependencies.txt)

**Comment by jitseniesen** [comment]
This sounds like a good idea to me. The report is still applied to the current version (3.0.1).

This may be useful: http://doc.qt.io/qt-5/qtwidgets-itemviews-frozencolumn-example.html

**Comment by ccordoba12** [comment]
This was solved in Spyder 3.1
