### ISSUE TITLE
Docks confusion when pressing undocking button

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3563]
Some feedback from a lecture @jitseniesen gave recently (October 2016)

> Somebody complained that the dock window interface is confusing; the undock button looks like it would maximize, and he got confused with the undocked window because it does act like a normal window does (this is on Linux)

**Comment by ccordoba12** [comment]
But what we could do about it? Forbid undocking?

**Comment by goanpeca** [comment]
I am just uploading feedback that we received, I have not give too much thought about it, but we had a PR that hid the docks title bar, which might be a good solution ;-)

**Comment by ccordoba12** [comment]
Yep, I agree. But that one was yours and you finally closed it :-p

**Comment by goanpeca** [comment]
Yes I know, I was not happy with how it was going, but I still have it in the back of my head.

**Comment by ccordoba12** [comment]
This is going to be fixed by PR #3824.
