### ISSUE TITLE
Create requirements file to ease introduction to development and testing

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3573]
http://conda.pydata.org/docs/using/envs.html

**Comment by rlaverde** [comment]
Could I create a requirements.txt for using with pip? Although pip is not currently supported, some people prefer to install spyder that way.

**Comment by ccordoba12** [comment]
Sure, go ahead @rlaverde! Our pip dependencies are listed in `setup.py` and our conda ones in `conda.recipe/meta.yaml`

**Comment by goanpeca** [comment]
:+1:, we also need to update wiki, so we can guide new devs when starting with Spyder :-)

**Comment by rlaverde** [comment]
How we should manage testing dependencies? Another requirements file?

**Comment by goanpeca** [comment]
Either we have two requirement files, or just one.. cause if you are developing you need to do testing anyway....

**Comment by goanpeca** [comment]
I would rather not pollute the already very polluted root of the repo, besides the idea is to have some easy to use cli script ti create envs... so I prefer creating a script that does something like

`spyder-dev -t conda -p 2.7`

And that would create a new conda env for testing spyder on python 2.7, or update it if it already exists with the needed dependencies

**Comment by rlaverde** [comment]
But using yaml, and requirements.txt will be more standard, that script will depend of that files? of will have dependencies inside it?

I don't think pip is better, is just a little more pythonic :stuck_out_tongue_closed_eyes:

**Comment by goanpeca** [comment]
who cares about standard.. we want dev to be easy and fast

**Comment by rlaverde** [comment]
But the script just will call conda o pip; and It'll be easy to update dependencies, only need to run` conda env export > environment.yml` and `pip freeze > requirements.txt`

**Comment by goanpeca** [comment]
sure i will just let me do this one :-p

**Comment by malliwi88** [comment]
@goanpeca or @ccordoba12  Which version of zmq you have?

**Comment by goanpeca** [comment]
I will be working on this @malliwi88, please work on the assigned issues https://github.com/spyder-ide/spyder/issues/assigned/malliwi88

**Comment by rlaverde** [comment]
@goanpeca I want to work in this issue

I think this could be addressed in a simple way, a `requirements.txt` file:

```
rope>=0.9.4
jedi>=0.9.0
pyflakes
pygments>=2.0
qtconsole>=4.2.0
nbconvert
sphinx
pep8
pylint
psutil
qtawesome>=0.4.1
qtpy>=1.1.0
pickleshare
pyzmq
chardet>=2.0.0
numpydoc
```

that could be installed using conda or pip:

`$ conda install --file requirements.txt`

`$ pip install -r requirements.txt`

**Comment by ccordoba12** [comment]
+1 from me if you want to work on this one @rlaverde. We should also have `test-requirements.txt` or something like that.

**Comment by rlaverde** [comment]
Where that files should live? a `requirements` folder in the spyder root?
```
requirements/requirements.txt
requirements/test-requirements.txt
```

Could I also try to change continuum integrations to use this files? (At the moment when adding or changing a dependency it has to be changed in a lot of places)

**Comment by ccordoba12** [comment]
@goanpeca, what do you say?

**Comment by ccordoba12** [comment]
Usually requirement files are added below the root of the repo. Please proceed like that for now.

**Comment by ccordoba12** [comment]
But don't touch our CIs. They can't be easily moved to use those files.

**Comment by goanpeca** [comment]
on the root of the repo are fine, making a folder for just 2 files is not really rsaving much
