### ISSUE TITLE
Error when connecting to external kernels

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#3583]
qt 4.8.7 does not have this bug, but qt5.6 with mac will have
```
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> WARNING:traitlets:kernel died: 3.0032799243927
Traceback (most recent call last):
  File "/Users/HWJ/anaconda3/lib/python3.5/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Users/HWJ/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 182, in _handle_execute_reply
    self.set_namespace_view_settings()
  File "/Users/HWJ/anaconda3/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 68, in set_namespace_view_settings
    settings = to_text_string(self.namespacebrowser.get_view_settings())
AttributeError: 'NoneType' object has no attribute 'get_view_settings'
```

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.0.1, please update :-)

**Comment by fayeshine** [comment]
@ccordoba12 sorry but I was meeting this bug in spyder 3.0.1, please recheck it

**Comment by ccordoba12** [comment]
But what code are trying to run when you get that message?

**Comment by ccordoba12** [comment]
And for the next time, please don't dismiss the information we ask in our issue template :-) (like Spyder version, dependencies, etc)

**Comment by fayeshine** [comment]
@ccordoba12 , I was using anaconda, updated everything to the latest. I was just trying to connect to a remote kernel, and this error message came out. However, I can connect to a remote kernel using qt 4.8.7.

**Comment by ccordoba12** [comment]
@fayeshine, were you trying to connect to a kernel through ssh?

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, an easy one for you :-) Please enclose these two lines

https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/ipythonconsole/namespacebrowser.py#L182-L183

inside a `if self.namespacebrowser is not None:` :-)
