### ISSUE TITLE
how do user Plugins Define default shortcuts

### ISSUE THREAD

**Issue by chrisgee** [spyder-ide/spyder#3584]
## Description of your problem

The default Parameter in register_shortcut does not exist anymore. What is the intended way to define those defaults for external Plugins? Shipped Plugins have them defined in the config default. I currently use CONF.get_default for this purpose. This does not seem nice.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 2.7.
* Operating system: osx 10.10

**Comment by jitseniesen** [comment]
For Spyder 3.0, external plugins are supposed to use fixed shortcuts; see #3254.

**Comment by ccordoba12** [comment]
Let's merge this one with #3254 and continue the discussion there :-)
