### ISSUE TITLE
Editor grabs focus when opening files at startup

### ISSUE THREAD

**Issue by chrisgee** [spyder-ide/spyder#3585]
## Description of your problem

**What steps will reproduce the problem?**
1. In spyder open a couple of files in editor
2. Close spyder and restart
3. 

**What is the expected output? What do you see instead?**
 After the main window appears, it is grabbing focus for each file that is reopened from the previous session. In addition each of these files is put to the front of the editor window. 

Reopening files in a thread is a good idea to reduce startup time. However, at the moment this is not effective, as the user will not be able to do anything (neither in spyder nor in any other application) until all files are loaded.

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 4.0.0dev 858193f
- Python Version: 2.7.12
- Operating system: osx 10.10

**Comment by chrisgee** [comment]
... more over, the files are opend twice if a project was active (I guess first spyder opens it's list and then later the project) -> should this be put in a separate issue?

**Comment by ccordoba12** [comment]
Thanks for reporting. I opened an issue about files being opened twice at startup when a project is active. We'll fix this problem in 3.0.2.

I don't know what to do about this one though. It seems a problem when you have a lot of files opened in your last session (30, 50?), but nobody has complained about it before :-)

**Comment by jitseniesen** [comment]
I think even with a handful of files it's slightly annoying though it wasn't annoying enough for me to complain about.

**Comment by ccordoba12** [comment]
I think the solution would be to prevent our `load` function to steal focus at startup. Let's assign one of our juniors to it :-)

**Comment by chrisgee** [comment]
OK. Maybe I am too impatient … ;-) and maybe there is something wrong with my setup.

Anyway I can see the files open one by one (about 1-2 per second). Don’t know if others observe the same. Since I am developing a plugin, restart spyder frequently, 10 seconds waiting for my 10 files to open (20 when I have a project active) is getting on my nerves…

I imagine the quick fix would be, to not put each newly opened file on the front tab (e.g. open the one that was front last time first, then add tabs in the background without setting the focus). A way to speed up things may be to skip parsing each file (at least an outline is generated for each while loading) and deferr that to the moment the user switches to the file…. what do you think?

Cheers,
C.
> On 24 Oct 2016, at 03:55, Carlos Cordoba <notifications@github.com> wrote:
> 
> Thanks for reporting. I opened an issue about files being opened twice at startup when a project is active. We'll fix this problem in 3.0.2.
> 
> I don't know what to do about this one though. It seems a problem when you have a lot of files opened in your last session (30, 50?), but nobody has complained about it before :-)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Christoph Gohle
christoph@gohle.org
