### ISSUE TITLE
DataFrame viewer should use custom index name

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3591]
I have used [pandas.DataFrame.rename_axis](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.rename_axis.html) to give a DataFrame's index a better name.

Now I would suggest that the index column of the DataFrame viewer should also display this new name on top of the index column, instead of constantly just displaying "Index".

(My current environment is described in #3562.)

**Comment by Prikers** [comment]
I think this can be closed following @dalthviz work in #3873 
:+1: for the multiindex dataframe explorer!

**Comment by ccordoba12** [comment]
Thanks for noticing it @Prikers!
