### ISSUE TITLE
IMK Stall detected

### ISSUE THREAD

**Issue by andrewwowens** [spyder-ide/spyder#3594]
## Description of your problem

Receiving the following error - 

"2016-10-24 14:36:34.593 python[2070:94840] IMK Stall detected, _please Report_ your user scenario in rdar://problem/16792073 - (imkxpc_windowLevelWithReply:) block performed very slowly (1.50 secs)"

**What steps will reproduce the problem?**
1. Command line launch spyder Spyder 3.0.1from Mac Terminal on OSX Yosemite
2. Open an existing .py file from a local directory
3. View the terminal for the error report

**What is the expected output? What do you see instead?**

Expected Output: no issues reported regarding file opening/manipulation.

Inside the terminal: 
"2016-10-24 14:36:34.593 python[2070:94840] IMK Stall detected, _please Report_ your user scenario in rdar://problem/16792073 - (imkxpc_windowLevelWithReply:) block performed very slowly (1.50 secs)"

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 3.0.1
- Python Version: 2.7
- Operating system: Yosemite v10.10.5
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I don't know what this error means, sorry :-/

Does it cause any visible problems with Spyder?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
