### ISSUE TITLE
connexion to remote kernel

### ISSUE THREAD

**Issue by steven1909** [spyder-ide/spyder#3597]
## Description of your problem

When i connect to a remote Kernel (with a kernel-json file), my spyder working directory has to contain the json file otherwise i have a message which explain that the kernel doesn't exist.

For example :

if i store my json file in "C:\user\tutu" and my python working directory is "C:\user\toto" i have an error message. I have to change my working directory to "C:\user\toto" to connect to the remote kernel.

It's not a big problem and maybe it's not a bug, but i don't understand why it's important to change the local directory because i work on a remote working directory.

Thanks a lot for your great work,

Steven

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  4.0.3 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pyflakes >=0.5.0   :  1.0.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  4.1.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Please update, this is fixed in Spyder 3.0.1 :-)
