### ISSUE TITLE
Spyder2 projects not importable to Spyder3

### ISSUE THREAD

**Issue by mayou36** [spyder-ide/spyder#3598]
My problem is simple:

1. Launch Spyder3
2. Import project (workspace) created under Spyder2

Instead, an error pops up saying that this is not a  Spyder-project.

As Spyder3 is the official update in pip of Spyder2, compatibility for projects should be a must-have.

## Versions and main components

* Spyder Version: 3
* Python Version: 2.7
* Operating system: Ubuntu 16.04 64x

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.4.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Unfortunately projects were semi-broken in Spyder 2, so they were rewritten from scratch in Spyder 3 with a different format.

And this new format is not compatible with the old one, sorry :-/
