### ISSUE TITLE
Spyder does not start when launching from navigator

### ISSUE THREAD

**Issue by nikrao** [spyder-ide/spyder#3600]
## Description of your problem

I updated the conda navigator to the latest version, and spyder does not start at all. To see what's happening, in the terminal when I type 

```
spyder --show-console
```

I get the following:

```
Traceback (most recent call last):
File "/Users/raon/anaconda2/bin/spyder", line 4, in <module>
import spyder.app.start
File "/Users/raon/anaconda2/bin/spyder.py", line 2, in <module>
from spyderlib import start_app
ImportError: No module named spyderlib
```

I tried pip install spyderlib, and I get

```
Could not find a version that satisfies the requirement spyderlib (from versions: )
No matching distribution found for spyderlib
```

ANy idea what's up?

**Comment by goanpeca** [comment]
@ccordoba12

**Comment by ccordoba12** [comment]
I don't know what happens with this one, this is just an installation error :-)

@nikrao, if you are new to Python, please try to uninstall and install Anaconda again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
