### ISSUE TITLE
Unable to install any python package

### ISSUE THREAD

**Issue by rohitshinsei** [spyder-ide/spyder#3605]
## Description
I'm unable to install any package in Spyder using pip with Windows 8.1. For example while installing package
!pip install time
getting the following output:
Collecting time
  Could not find a version that satisfies the requirement time (from versions: )
No matching distribution found for time

Tried the pip command with various packages, result is same :-(
**What steps will reproduce the problem?**

1. !pip install time
2. !easy_install time

**What is the expected output? What do you see instead?**
I want to install the package, but not getting success for any one.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  2.4.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.4.3 (OK)

```

**Comment by ccordoba12** [comment]
Please don't try to do this inside Spyder and use a proper terminal (i.e. cmd.exe) instead.

Spyder is not designed to let users install packages inside it yet.
