### ISSUE TITLE
Issues with Pyroot

### ISSUE THREAD

**Issue by hareyakana** [spyder-ide/spyder#3610]
## Description of your problem

Only able to run a script containing pyroot once and forced to open new IPython window to run the srcipt again. It was the same problem when trying with the native python in spyder

**What steps will reproduce the problem?**
1. Run a script containing pyroot module once/
2. trying to run the script the second time will run into this error

**What is the expected output? What do you see instead?**
 File "C:\root_v5.34.36\bin\ROOT.py", line 215, in **getattr**
    klass = _root.MakeRootClass( attr, cls )

TypeError: requested class 'ROOT::**file**' does not exist

**Please provide any additional information below**
It looks like someone has discuss this issue before on 
https://root.cern.ch/phpBB3/viewtopic.php?t=21397
## Versions and main components
- Spyder Version: 3.0.0 (32-bit)
- Python Version: 2.7
- Operating system: Windows 10
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This seems related to #3586, so closing in favor of that one.
