### ISSUE TITLE
Spyder freeze and crash when there is a Python error 

### ISSUE THREAD

**Issue by hagaishalev** [spyder-ide/spyder#3613]
## Description of your problem

**What steps will reproduce the problem?**
1.  Upgrade to Anaconda 4.2.0/Spyder 3.0.1 (or Spyder 3.0.0)
2.  Run some Python script with an error
3. In some of the times the Spyder shows the error but freeze and say that the program stop responding. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
In order to solve the issue I had to downgrade to Anaconda 4.1.1/Spyder 2.3.9
## Versions and main components
- Spyder Version: 3.0.1/ 3.0.0
- Python Version: 3.5.2
- Operating system: windows 7 64bit
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please use the IPython console. The Python console will be disabled in Spyder 3.1 on Windows because of this kind of problems.
