### ISSUE TITLE
Spyder 3 Icons are huge - DPI scaling?

### ISSUE THREAD

**Issue by crawforc3** [spyder-ide/spyder#3614]
## Description of your problem
Spyder 3 GUI scaling is off. Icons are huge. This was supposedly fixed in 3.0.1 I thought?

![screenshot from 2016-10-28 09-41-36](https://cloud.githubusercontent.com/assets/8405957/19814624/d5ea33f2-9cf3-11e6-8669-58fdeb8db2a7.png)

**What steps will reproduce the problem?**

1. Running Spyder from CLI
2. Running spider from Anaconda Navigator

**What is the expected output? What do you see instead?**
I expect the icons to be normal sized. Instead, I see icons that appear to be enlarged.

**Please provide any additional information below**
 Possibly due to a DPI scaling?

## Versions and main components

* Spyder Version: 3.0.1 (Anaconda distribution )
* Python Version: 3.5.2
* Operating system: Ubuntu 16.04.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.4.2 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This error will be fixed in Spyder 3.0.2 :-)
