### ISSUE TITLE
No attribute 'version' error of IPython kernel when importing pandas automatically

### ISSUE THREAD

**Issue by kigawas** [spyder-ide/spyder#3616]
## Description

**What steps will reproduce the problem?**
1. Install latest numpy and pandas via Anaconda
2. Open Spyder (3.0.1)

**What is the expected output? What do you see instead?**
It should have started the IPython kernel, yet failed.

**Please provide any additional information below**
When importing pandas in IPython or Python REPL in an external shell, no such an error.
When importing pandas in internal Python REPL built in Spyder, error prompted.

External IPython shell:

``` python
In [1]: %paste
from pandas.compat.numpy import *

## -- End pasted text --

In [2]: np.version
Out[2]: <module 'numpy.version' from 'C:\Users\Lumit\Anaconda\lib\site-packages\numpy\version.pyc'>

In [3]: np.version.short_version
Out[3]: '1.11.0'
```

This is the traceback of Python console.
Internal shell:

``` python
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lumit\Anaconda\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "C:\Users\Lumit\Anaconda\lib\site-packages\pandas\compat\numpy\__init__.py", line 10, in <module>
    _np_version = np.version.short_version
AttributeError: 'module' object has no attribute 'version'
```

IPython kernel shell when booting:

``` python
Traceback (most recent call last):
  File "C:\Users\Lumit\Anaconda\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\Lumit\Anaconda\lib\site-packages\spyder\widgets\externalshell\monitor.py", line 495, in run
    self.update_remote_view()
  File "C:\Users\Lumit\Anaconda\lib\site-packages\spyder\widgets\externalshell\monitor.py", line 379, in update_remote_view
    remote_view = make_remote_view(ns, settings)
  File "C:\Users\Lumit\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 480, in make_remote_view
    more_excluded_names=more_excluded_names)
  File "C:\Users\Lumit\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\utils.py", line 459, in get_remote_data
    supported_types = get_supported_types()
  File "C:\Users\Lumit\Anaconda\lib\site-packages\spyder\config\base.py", line 370, in get_supported_types
    from pandas import DataFrame, Series
  File "C:\Users\Lumit\Anaconda\lib\site-packages\pandas\__init__.py", line 22, in <module>
    from pandas.compat.numpy import *
  File "C:\Users\Lumit\Anaconda\lib\site-packages\pandas\compat\numpy\__init__.py", line 10, in <module>
    _np_version = np.version.short_version
AttributeError: 'module' object has no attribute 'version'
```
## Version and main components
- Spyder Version: 3.0.1 
- Python Version: 2.7.12
- Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Windows
## Dependencies

```
jedi >=0.8.1     :  0.8.1 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.0.0 (OK)
numpy >=1.7      :  1.11.0 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.6.2 (OK)
pyflakes >=0.5.0 :  0.9.2 (OK)
pygments >=2.0   :  2.0.2 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  0.7.6 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. It seems a problem with Pandas `0.19.0`.

----

@dalthviz, please take a look at this one. The report is not clear, but it seems to imply that users can't import Pandas in our Python and IPython consoles when upgrading to Pandas `0.19.0`.

**Comment by kigawas** [comment]
@ccordoba12
Any other information do you need?

**Comment by ccordoba12** [comment]
Let us get things clear: so you updated Pandas, started Spyder, then tried to do an `import pandas` in our Python and IPython consoles, and got that error? Is that right?

**Comment by kigawas** [comment]
Not exactly. 

When opening Spyder it tried to import pandas automatically and raised such an error which resulted in IPython kernel's dying.

After uninstalling pandas, Spyder can boot normally because it doesn't try to import pandas anymore.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification. Now, how did you try to *import pandas automatically*?

**Comment by kigawas** [comment]
Let's check the long traceback above. 

The higher level's trace shows that Spyder's variable explorer widget does this automatically when it detects pandas dependency.

I guess that's why Spyder tried to import pandas in the kernel's bootstrap phase.

**Comment by ccordoba12** [comment]
Yes, I can see that, but did you modify some Spyder configuration options to import pandas automatically or not?

**Comment by kigawas** [comment]
Nope. Everything remains default. (Tried to reinstall and reset all settings)

**Comment by ccordoba12** [comment]
Ok, thanks. Things are clearer now :-)

**Comment by kigawas** [comment]
I guess there might be a module naming *np* shadows *np* in `from pandas.compat.numpy import *`.

**Comment by dalthviz** [comment]
Hi, I install the latest version of pandas and numpy with conda and everything seems find. The only thing that maybe is strange is that the version of numpy that I install is `1.11.2`, not `1.11.0`

Here the IPython console in Spyder 3.0.1 with python 2.7 that shows the import:

![image](https://cloud.githubusercontent.com/assets/16781833/19841531/41edd250-9edb-11e6-9f5d-9ece31b77134.png)

**Comment by ccordoba12** [comment]
@dalthviz, what if you try only

    import pandas

in the IPython console? Please also try with the Python console to double check :-)

**Comment by dalthviz** [comment]
yep, no errors:

![image](https://cloud.githubusercontent.com/assets/16781833/19841643/bbf5bb8e-9edc-11e6-9b61-a56228471b0f.png)
![image](https://cloud.githubusercontent.com/assets/16781833/19841647/d24823f4-9edc-11e6-804b-ea5620e80671.png)

Maybe is the version `1.11.0 ` that makes the error to happen?, @kigawas can you try to update numpy to version `1.11.2` and tell us if the error is still there?

**Comment by kigawas** [comment]
Already upgraded, still raise same error.

Dependencies:
```
jedi >=0.8.1     :  0.8.1 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.0.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.6.2 (OK)
pyflakes >=0.5.0 :  0.9.2 (OK)
pygments >=2.0   :  2.0.2 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  0.7.6 (OK)

```

**Comment by ccordoba12** [comment]
What if you run in a terminal these commands:

    conda install -f numpy
    conda install -f pandas

?

**Comment by dalthviz** [comment]
Also you restarted Spyder after the upgrade?

**Comment by kigawas** [comment]
Unfortunately it still complained about this error.

**Comment by dalthviz** [comment]
And what if you run in a terminal this command to reinstall Spyder:

```
conda install -f spyder
```

?

**Comment by ccordoba12** [comment]
Nobody else has complained about this problem, so i think it's an installation issue.

Sorry, but since there's nothing else we can do about this issue, I'm closing it.

**Comment by bhilburn** [comment]
For what it's worth, after installing `pandas` and `spyder` using `dnf` on Fedora24, I see this exact same problem, and `spyder` fails to launch.
