### ISSUE TITLE
Enhancement: ipython notebook inside Spyder

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder#3617]
## Versions and main components

* Spyder Version: 3, qt5
* Python Version:
* Operating system:
## Dependencies
It would be nice if Spyder can create and edit ipython notebook like in PyCharm. This could be a plugin for Spyder.

PS: Can any developer help to me to a template for hello-world plugin for Spyder? I cannot find any resources. Thank you.

**Comment by ccordoba12** [comment]
Having notebooks inside Spyder would be nice. We're thinking how to do it, but not as part of Spyder itself (as a third-party plugin instead). That's why I'm closing this issue.

----

Here is a third-party plugin that can help you to get started :

https://github.com/spyder-ide/spyder-unittest

**Comment by jitseniesen** [comment]
I added this to the wiki page [Plugin ideas](https://github.com/spyder-ide/spyder/wiki/Plugin-ideas).
