### ISSUE TITLE
Removing a project deletes also the files on the disk

### ISSUE THREAD

**Issue by mayou36** [spyder-ide/spyder#3618]
When removing a Spyder project within the project explorer, not only is the project deleted but also all files contained in the HDD without any warning about that. This is surely not the behavior one expects, as in Spyder 2 the deletion of files had to be explicitly selected. Other project/versioning software usually also has the Spyder 2 behavior regarding project deletion.

**What steps will reproduce the problem?**
1. Create a project, either new or from an existing directory
2. Delete the project

**What is the expected output? What do you see instead?**
The **Project** created by Spyder should be removed. But not all the other files contained in the project-directory.

**Please provide any additional information below**
I understand that this case may be wanted sometimes. But it surely should not be the default behavior. What would otherwise be the proper way to just delete a project (NOT the files)?
My proposal would be to either:
- change the behavior of the deletion function to only delete the Spyder-project or
- **explicitly** state that this will also delete ALL the files **from the disk**

## Versions and main components
- Spyder Version: 3.0.1
- Python Version: 2.7
- Operating system: Ubuntu 16.04 64x
## Dependencies

I think deps don't matter here

Best,
Mayou

**Comment by ccordoba12** [comment]
Thanks for reporting. We simply didn't consider the use case you reported.

----

@rlaverde, please work on this one. The idea is to change the behavior of the *Delete* action from the context menu of the Project Explorer when users do a right click on the project directory (i.e. the first row in the explorer).

In this case, *Delete* must

1. Remove the underlying `.spyproject` directory
2. Close the project and return to the interface without a project.
3. Add a warning to the dialog shown when *Delete* is selected, saying that the project will be deleted but that the files are going to be preserved on disk.

Please also make all of this work when users press the *Del* keystroke.

**Comment by goanpeca** [comment]
@ccordoba12 should we ask if the files want to be deleted as well ? or not

**Comment by ccordoba12** [comment]
I'm not sure, but it sounds like a good idea (although it shouldn't be the default one).

However, to make things more explicit (and not only dependent on the context menu entry), I think we should add a *Delete Project* entry to our *Projects* menu. What do you think?

**Comment by goanpeca** [comment]
>I'm not sure, but it sounds like a good idea (although it shouldn't be the default one).

Agreed lets ask but default should be No, so that accidental enters would also yield no.

>However, to make things more explicit (and not only dependent on the context menu entry), I think we should add a Delete Project entry to our Projects menu. What do you think?

:+1:

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one instead. Given that issue #3616 seems to be not much of a problem, and you're around, please work on it :-)
