### ISSUE TITLE
No .py extension in file name when saving

### ISSUE THREAD

**Issue by blaylockbk** [spyder-ide/spyder#3625]
## Description of your problem
Spyder used to automatically add the .py extension when saving a script. It doesn't do this anymore, and that's annoying.

**What steps will reproduce the problem?**

1. create and save a new script or save a file using "save as"

**What is the expected output? What do you see instead?**
I'm expecting the file to save as a .py file. But it doesn't add any extension.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1
* Python Version: 2.7.12
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed in PR #3580 and it'll be part of Spyder 3.0.2 :-)
