### ISSUE TITLE
Spyder won't start because of "ValueError: unknown locale: UTF-8" in macOS

### ISSUE THREAD

**Issue by rodri981** [spyder-ide/spyder#3627]
##I cannot get my spyder app running.
## I installed IRAF yesterday and ever since spyder won't start when I type the command in the terminal.
##Here's a screenshot of what i get:
![screen shot 2016-10-31 at 7 10 42 pm](https://cloud.githubusercontent.com/assets/23175158/19865858/3b919612-9f9e-11e6-9c79-56b2d4748a23.png)

**Comment by ccordoba12** [comment]
For now, please follow this advice:

http://pythonhosted.org/spyder/installation.html#id3

We'll fix this error for good in Spyder 3.1 :-)

**Comment by ccordoba12** [comment]
@malliwi88, this one is easy. Please add a try/except here:

https://github.com/spyder-ide/spyder/blob/master/spyder/config/base.py#L268

and make `locale_language = DEFAULT_LANGUAGE` in the except part.
