### ISSUE TITLE
Edit context menu appears only for utf-8 files in project explorer

### ISSUE THREAD

**Issue by tsadowski** [spyder-ide/spyder#3631]
## Description of your problem

I created a new project from an existing folder. Some .py-files in the Project explorer had an "Edit" context menu, others only an "Open" context menu. Drag and drop into the editor would also not work. 

A short look in the sources revealed that in explorer.py line 261:
def create_file_manage_actions
only utf encoded files are accepted as editable. 

I have no problem with this behavior but it should be easy to find in the documentation. 

**What steps will reproduce the problem?**

1. Create a .py file with ANSI encoding and try the context menu

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 3.5.2
* Operating system: Win 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
An easy one for you @rlaverde :-)

**Comment by ccordoba12** [comment]
I can't reproduce this. @tsadowski, could you send us a simple file that's failing for you?

**Comment by ccordoba12** [comment]
Don't worry about it, I found how to reproduce this error.
