### ISSUE TITLE
OS-X: Spyder seg faults at startup

### ISSUE THREAD

**Issue by maak** [spyder-ide/spyder#3633]
## Description of your problem

Spyder crashes at startup. There is a note about conflicting Qt installations in the log. Perhaps this is relevant.

**What steps will reproduce the problem?**

1. Install using Anaconda
2. Open spyder from commandline

**What is the expected output? What do you see instead?**
I expect Spyder to open successfully. Instead, I see the loading dialog, then the application crashes.

**Please provide any additional information below**

> objc[65569]: Class QCocoaPageLayoutDelegate is implemented in both /Users/me/anaconda/lib/libQt5PrintSupport.5.6.0.dylib and /usr/local/lib/QtGui.framework/Versions/4/QtGui. One of the two will be used. Which one is undefined.
> objc[65569]: Class QCocoaPrintPanelDelegate is implemented in both /Users/me/anaconda/lib/libQt5PrintSupport.5.6.0.dylib and /usr/local/lib/QtGui.framework/Versions/4/QtGui. One of the two will be used. Which one is undefined.
> /Users/me/anaconda/bin/python.app: line 3: 65569 Segmentation fault: 11  /Users/me/anaconda/python.app/Contents/MacOS/python "$@"

Conflicting Qt installations may be an issue?
## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 2.7.12 :: anaconda custom
* Operating system: OSX 10.10.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Sorry, application does not launch so I cannot obtain this data.

**Comment by ccordoba12** [comment]
Just remove the Qt4 version you have in

    /usr/local/lib/QtGui.framework/Versions/4/

**Comment by maak** [comment]
Doing so confuses things further:
Traceback (most recent call last):
  File "/Users/me/anaconda/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/Users/me/anaconda/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/Users/me/anaconda/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 78, in <module>
    from qtpy.compat import from_qvariant
  File "/Users/me/anaconda/lib/python2.7/site-packages/qtpy/compat.py", line 15, in <module>
    from qtpy.QtWidgets import QFileDialog
  File "/Users/me/anaconda/lib/python2.7/site-packages/qtpy/QtWidgets.py", line 23, in <module>
    from PyQt4.QtGui import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/PyQt4/QtGui.so, 2): Library not loaded: /usr/local/lib/QtGui.framework/Versions/4/QtGui
  Referenced from: /usr/local/lib/python2.7/site-packages/PyQt4/QtGui.so
  Reason: image not found

**Comment by JessicaS11** [comment]
I also had this problem. I think the issue is that your system is looking for python packages in multiple locations and finding them (probably thanks to the use of multiple python package managers and consequent updates to PYTHONPATH). Try $unset PYTHONPATH and then running spyder from the command line. Once I did this, spyder started up no problems.

**Comment by ccordoba12** [comment]
Thanks @JessicaS11, this could be most probably the case: having both Anaconda and Homebrew or MacPorts installed in your system.

**Comment by GuidoPagano** [comment]
Hi @JessicaS11 and @ccordoba12,

I have exactly the same problem. My spyder launches, but then crashes showing Segmentation fault with the error message:

`/Applications/anaconda3/bin/pythonw: line 3: 60194 Segmentation fault: 11  /Applications/anaconda3/python.app/Contents/MacOS/python "$@"
`
I have both MacPorts and brew installed. Is that the problem? I already tried to `unset PYTHONPATH` but it didn't solved the problem. Before `echo $PYHTONPATH` would return `/sw/lib/root` now it is empty.

Below are my spyder and python packages. Any suggestions? Thanks!

```
conda list spyder

# Name                    Version                   Build  Channel
spyder                    4.1.3            py36h9f0ad1d_0    conda-forge/label/main
spyder-kernels            1.9.1            py36h9f0ad1d_0    conda-forge/label/main

conda list python

# Name                    Version                   Build  Channel
antlr4-python3-runtime    4.7.1                    pypi_0    pypi
ipython                   7.15.0           py36h9f0ad1d_0    conda-forge/label/main
ipython_genutils          0.2.0                      py_1    conda-forge/label/main
python                    3.6.10          h4334963_1011_cpython    conda-forge/label/main
python-dateutil           2.8.1                      py_0    conda-forge/label/main
python-jsonrpc-server     0.3.4              pyh9f0ad1d_1    conda-forge/label/main
python-language-server    0.31.9           py36h9f0ad1d_0    conda-forge/label/main
python.app                1.3              py36h37b9a7d_1    conda-forge/label/main
python_abi                3.6                     1_cp36m    conda-forge/label/main
```

**Comment by GuidoPagano** [comment]
Actually after executing `conda update all`, I update the following packages 

`The following packages will be UPDATED:

  cython             pkgs/main::cython-0.29.17-py36h0a4402~ --> conda-forge/label/main::cython-0.29.19-py36h0130604_0
  icu                                 pkgs/free::icu-54.1-0 --> conda-forge/label/main::icu-64.2-h6de7cb9_1
  pyqt                 pkgs/main::pyqt-5.6.0-py36h655552a_6 --> conda-forge/label/main::pyqt-5.12.3-py36haa9e2f4_3
  qt                                  pkgs/free::qt-5.6.2-2 --> conda-forge/label/main::qt-5.12.5-h514805e_3`

And now I get the following error:

`This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

I installed Qt via qt.io/download-qt-installer but I still get the same error.

Any suggestions? Thanks!

**Comment by ashwin-h** [comment]
i created a new conda environment with
```
onda create --name uquant python=3.11
```
Then
```
conda activate uquant
```
```
 conda install spyder=5.4.3
```

With this i am able to start spyder
