### ISSUE TITLE
Spyder flashes, but won't open

### ISSUE THREAD

**Issue by jedisom** [spyder-ide/spyder#3634]
## Problem Description
I've been using python(x,y) for a while with python 2.x, and decided to change to python 3.4 and Spyder without python(x,y).  After the installation process (as far as I could do it based on instructions online) I have a Spyder desktop icon, but when I click on it, it flashes with the Spyder information rectangle that normally shows while it's loading, but it disappears again in less than a second and Spyder never opens.  Can someone help me figure out what's going wrong?  Based on the advice of [this issue](https://github.com/spyder-ide/spyder/issues/2731) I ran `spyder --show-console` in the command prompt and got the following output:

`Traceback (most recent call last):
  File "C:\Python34\Scripts\spyder", line 3, in <module>
    start_app.main()
  File "C:\Python34\lib\site-packages\spyderlib\start_app.py", line 115, in main
    spyder.main()
  File "C:\Python34\lib\site-packages\spyderlib\spyder.py", line 2278, in main
    app = initialize()
  File "C:\Python34\lib\site-packages\spyderlib\spyder.py", line 2134, in initia
lize
    rope_patch.apply()
  File "C:\Python34\lib\site-packages\spyderlib\rope_patch.py", line 131, in app
ly
    from rope.contrib import codeassist
  File "C:\Python34\lib\site-packages\spyderlib\utils\external\rope\contrib\code
assist.py", line 9, in <module>
    from rope.contrib import fixsyntax
  File "C:\Python34\lib\site-packages\spyderlib\utils\external\rope\contrib\fixs
yntax.py", line 29
    except exceptions.ModuleSyntaxError, e:
                                       ^
SyntaxError: invalid syntax`

## Versions and main components

* Spyder Version: spyder-2.3.8.win-amd64-py3.4.exe
* Python Version: 3.4.4
* Operating system: Windows 7

**Comment by ccordoba12** [comment]
You incorrectly installed `rope` for Python 2 in Python 3. Instead of the `rope` package, you need to install `rope_py3k`.

Besides, Spyder 2.3 is not supported by us anymore. Please update to Spyder 3.0 with

    pip install -U spyder

**Comment by jedisom** [comment]
Awesome thanks!  I pip installed rope_py3k and updated Spyder.  It's now opening and working.

**Comment by TMR-6** [comment]
I have a similar problem, I've installed LMFIT and Syper doesn't launch anymore.

![anaconda](https://cloud.githubusercontent.com/assets/23632166/20480314/dae9df12-afd9-11e6-9689-2adc6f903420.PNG)

**Comment by ccordoba12** [comment]
@TMR-6, this error was fixed a long time ago. Please update Spyder to its latest version (3.0.2) to get it fixed.

**Comment by paulmattheww** [comment]
Hi all,
I have this issue as well, although it appears for different reasons than what has already been addressed.  Spyder flashes then disappears, leaving this message:

![image](https://user-images.githubusercontent.com/10945237/32343932-2a841b8c-bfd3-11e7-80a2-a9ced8f1969a.png)
