### ISSUE TITLE
Variable explorer should display the value of numpy.int64 variables

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3638]
Execute
```
import numpy
j = numpy.int64(17)
```
.

Now `j` shows up in the variable explorer, but the Value column displays `class 'numpy.int64`. It should display the value `17` instead.

(My current environment is described in #3562.)

**Comment by ccordoba12** [comment]
@dalthviz, an easy one for you. Please make that all numeric Numpy types appear in the Variable Explorer :-)
