### ISSUE TITLE
IPython Console Not Working

### ISSUE THREAD

**Issue by Ada323** [spyder-ide/spyder#3643]
## Description of your problem

I just upgraded to the latest version of spyder, and since then my IPython console hasn't been working properly. Whenever I try to run a file, I get some version of this in the console:

"runfile('/Users/MollyGelsey/.spyder-py3/temp.py', wdir='/Users/MollyGelsey/.spyder-py3')"

instead of the expected output. I'm fairly new to coding and I haven't been able to figure out how to fix this problem myself. Please help!

## Versions and main components

* Spyder Version: 3.1
* Python Version: 3.5.2
* Operating system: OSX El Capitan 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
If that's the only thing that appears in the IPython console, that's because you're printing anything in your code, so no output is generated :-)

**Comment by Ada323** [comment]
You're absolutely right -- apologies for not testing more thoroughly before posting this. When I tried another file with just a few print statements everything worked perfectly. Looks like I made some mistakes in the code I'd been trying unsuccessfully to run before, which is why nothing was printing. Thanks so much for the quick response!

**Comment by ccordoba12** [comment]
No worries, all of us have been there: at the beginning of this journey to learn programming :-)
