### ISSUE TITLE
Autocompletion on Python consoles is crashing in master

### ISSUE THREAD

**Issue by malliwi88** [spyder-ide/spyder#3645]
@rlaverde 

Using tab key for completion on python console, I see this

![seleccion_012](https://cloud.githubusercontent.com/assets/5307894/19971674/b7d1756a-a1ad-11e6-949f-54aebc7725b5.png)

It's related with your lastest PR or Devs?

**Comment by goanpeca** [comment]
@rlaverde this is yours

**Comment by rlaverde** [comment]
yes, my fault, I introduced that error, It can't be assumed that editor will have `linenumber` attribute

I will revert that line to:
`point.setX(point.x()+self.textedit.get_linenumberarea_width())`

The long term solution should be to create a more general function that will return the total width of panels, and should call panels that have been register in the editor.

**Comment by goanpeca** [comment]
Yes, agreed!
