### ISSUE TITLE
Make shortcuts in the Editor to be the same as the ones in the IPython console

### ISSUE THREAD

**Issue by PAGWatson** [spyder-ide/spyder#3646]
## Description of your problem
If I do Ctrl+D on my Mac in the Spyder editor window, I expect this to act like "Delete" on a PC and delete one character to the right of the cursor, or delete text I have highlighted. Instead, if I have not highlighted any text, it deletes the whole word to the right of the cursor. If I have highlighted text from left to right, it deletes the word to the right of the highlighted section. (If I have highlighted text from right to left, it deletes the highlighted text as expected. Ctrl+D also works as expected in the ipython console.)

**What steps will reproduce the problem?**

1. Place cursor in text in the Spyder editor.
2. Type Ctrl+D.
3. 

**What is the expected output? What do you see instead?**
Described above.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 2.7.11
* Operating system: Mac OS El Capitan 10.11.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.18.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.1.0 (OK)
pyflakes >=0.5.0 :  1.1.0 (OK)
pygments >=2.0   :  2.1.1 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.0 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.3.5 (OK)
sympy >=0.7.3    :  0.7.6.1 (OK)

**Comment by ccordoba12** [comment]
`Ctrl+D` is assigned in Spyder to delete a line in Windows/Linux. The equivalent command in Mac is `Cmd+D`.

**Comment by PAGWatson** [comment]
Sorry if I was not clear. I do not want to delete a line, just one character to the right of my cursor, or text that I have highlighted, using the same Ctrl+D command that will work in other Mac applications (I don't want to have to remember special key combinations for Spyder). I don't see any good reason for Ctrl+D behaving differently, and not in an intuitive way, in Spyder than in other applications on Macs.

**Comment by ccordoba12** [comment]
You can remap those shortcuts by going to

    Preferences > Keyboard shortcuts

In Mac you will find the current mapping by default

    Delete -> Del
    Kill next word -> Ctrl+D

So you can change them to suit your needs :-)

----

However, this let me thinking that we should use in the Editor the same shortcuts defined the IPython console (which can be reconfigured) for consistency.

**Comment by goanpeca** [comment]
>However, this let me thinking that we should use in the Editor the same shortcuts defined the IPython console (which can't be reconfigured) for consistency.

Is this something that we can ask for over Jupyter?

**Comment by ccordoba12** [comment]
We would have to do it ourselves because qtconsole is in maintenance mode now :-)

**Comment by goanpeca** [comment]
>We would have to do it ourselves because qtconsole is in maintenance mode now :-)

Meaning nothing new can be added?

**Comment by PAGWatson** [comment]
OK thanks very much, that sorted it out. Sorry, it hadn't occurred to me that this would be set as a keyboard shortcut. I'll close this issue now.

**Comment by ccordoba12** [comment]
Please leave it open, we're thinking to improve things for our next release :-)

**Comment by PAGWatson** [comment]
OK, sorry, didn't know the etiquette :-S

**Comment by ccordoba12** [comment]
No worries :-)

**Comment by ccordoba12** [comment]
Let's close this one in favor of #11679.
