### ISSUE TITLE
"%reset -s" is giving an error in the IPython console

### ISSUE THREAD

**Issue by arman00** [spyder-ide/spyder#3647]
## Description of your problem
When I type '%reset -s' to clear all the variables, instead it prints error message and does not clear all the variables. However, '%reset' works without any issue. Also, this only happens with spyder versions 3.0.0b7 or above. With 3.0.0b6 and below it works without any issue.

**What steps will reproduce the problem?**
The command %reset -s (and I choose y)
or just type %reset -sf (to force yes)

**What is the expected output? What do you see instead?**
Expected behavior is to clear all the variables.
Instead, below error message is printed in the Internal console, and the variables in the variable explorer are not cleared. Also, after this, any command in the IPython console prints the same error message, and new variables never display in the variable explorer.

>>> Traceback (most recent call last):
  File "c:\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
Traceback (most recent call last):
  File "c:\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "c:\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 188, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "c:\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 227, in handle_exec_method
    properties = ast.literal_eval(data['text/plain'])
TypeError: 'NoneType' object is not subscriptable
    handler(msg)
  File "c:\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 188, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "c:\winpython-64bit-3.5.2.2\python-3.5.2.amd64\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 224, in handle_exec_method
    view = ast.literal_eval(data['text/plain'])
TypeError: 'NoneType' object is not subscriptable

**Please provide any additional information below**
However, '%reset' works without any issue.
Also, this only happens with spyder versions 3.0.0b7 or above. With 3.0.0b6 and below it works without any issue.

## Versions and main components

Spyder Version: 3.0.1
Python Version: 3.5.2
Operating system: Windows 7 64-Bit
IPython: 5.1.0

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by arman00** [comment]
The same error happens also if run "get_ipython().magic('reset -sf')", both in the console and within a script.

**Comment by ccordoba12** [comment]
Thanks, we'll fix this error in Spyder 3.0.2 :-)

**Comment by arman00** [comment]
I installed Spyder 3.0.2, but unfortunately this error still persists.
I am using Qt4 graphics backend in the IPython console, which is not the default one. Perhaps it works fine with Qt5 but not Qt4.

**Comment by ccordoba12** [comment]
There's no way this error is still present. We cover thoroughly the lines that could generate it, so I think it should be a different error.

Please open a new issue and paste the error you're getting now.

**Comment by arman00** [comment]
Thanks. I found out the actual reason of this error. If it is really a bug I can open a new issue, please let me know.

It only happens when I use "from IPython import get_ipython". For version 3.0.0b6 and below, I think I had to import this to be able to use "get_ipython().magic('reset -sf')" (I import this and define a reset function in the starting script to be able to call it from all of my scripts, could not find a more practical solution to clear all the variables at the start of a script). So now I delete that import line and I am still able to call my __reset__() function. It seems that get_ipython is now imported by default in IPython console, although the code analysis in the editor warns that 'get_ipython' is an undefined name.

**Comment by ccordoba12** [comment]
> If it is really a bug I can open a new issue

Glad you found the cause of this error. And yes, please open a new issue. I'm curious to see what error you're getting in this case.

> It seems that get_ipython is now imported by default in IPython console

It's part of the IPython namespace when you create any console (not just in Spyder). That's why you can run your reset function even when you get warning in the Spyder Editor.

If you want to run script in and out of IPython, you should define your function like this:

```python
def reset():
    try:
        get_ipython().magic('reset -sf')  #analysis:ignore
    except NameError:
        pass
```

The `analysis:ignore` comment prevents the Editor to show a warning about `get_ipython`, and the try/except block prevents an error in pure Python because `get_ipython` is missing.
