### ISSUE TITLE
Edit menu shortcuts are invisible

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3648]
On Macos with the latest dev version, shortcuts for the edit menu are not visible

<img width="229" alt="screen shot 2016-11-03 at 3 39 36 pm" src="https://cloud.githubusercontent.com/assets/3627835/19982277/d679059a-a1db-11e6-9aac-7f62f5824fac.png">

**Comment by ccordoba12** [comment]
They are disabled because you need to have something selected for Copy and Cut, and also something to make a Redo.

I don't see a problem with that :-)

**Comment by goanpeca** [comment]
No, I mean there is no shortcut! What is the shortcut for Indent? or for toggel Uppercase

**Comment by ccordoba12** [comment]
Ohhh, is it for all menus or just the Edit one?

**Comment by goanpeca** [comment]
Only edit :-|
