### ISSUE TITLE
IPython no longer printing to python console

### ISSUE THREAD

**Issue by EngineerNate** [spyder-ide/spyder#3652]
Hi All, I apologize if this is the wrong place to put this, I couldn't find anywhere else to ask.

Configuration:
Spyder 3.0.1
Python 3.5.2
Win 10

Issue:
I have a script that uses multiprocessing pools to submit a large number of Abaqus analyses to be solved in parallel. The script uses subprocess.call and multiprocessing pools with the map function. Previously, when I ran the script, the output from the command line wouldn't be printed to the IPython console but it was visible if I tabbed over to the python console it was linked to. After the update, I don't get anything until the process finishes and none of the console output from Abaqus is displayed, just the final returncodes for each subprocess worker. As a solution for now, I've switched to running the script in the python console, which works as expected (console output is printed as it is created by the subprocess program, final returncodes etc for all of the workers are printed at final completion time).

Was this change intentional or is there a setting I need to flip to get my output back if I run in IPython?

**Comment by ccordoba12** [comment]
In Spyder 3.0 we don't connect to IPython kernels through the Python console but directly to them. That's the reason of this change, and there's no setting to change it.

@minrk or @takluyver, is there a way to make multiprocessing messages to be printed directly in qtconsole?

**Comment by EngineerNate** [comment]
Thanks for the information. For now, I was able to fix the situation by switching to imap. I am not actually using any of the variables inside the python script (it is simply an easy and platform independent way to avoid having to make excessively complicated shell/batch/powershell scripts to do my jobs for me). I don't get the full console output of the subprocess, but the completion outputs of the multiprocessing pool are printed as they arrive. This is actually somewhat cleaner than printing both this and the output from the outside functions being called.

**Comment by ccordoba12** [comment]
Ok, closing then :-)
