### ISSUE TITLE
Inspecting values in debugging is not supported in IPython console

### ISSUE THREAD

**Issue by CodingThinking** [spyder-ide/spyder#3657]
Hi All, I apologize if this is the wrong place to put this, I couldn't find anywhere else to ask.

Configuration:
Spyder 3.0.1
Python 3.5.2
Win 10

Issue:
When I debug a script in a IPython console, I can't inspect any value in variable explorer as I can do in spyder 2.3.9, and a msg will come out saying Inspecting values in debugging is not supported in IPython console.  I can see this variable in the variable explorer, but when I double click on it, it won't come out and says a error msg as issue title. I think this is a very good function  and I want to know if it will return.

**Comment by ccordoba12** [comment]
That's correct. Inspecting values while debugging is not supported in the IPython console for Spyder 3.0.

It'll be reactivated in the future, but right now there's nothing you can do about it :-)
