### ISSUE TITLE
conflicts with PyQt4 and Mayavi

### ISSUE THREAD

**Issue by CodingThinking** [spyder-ide/spyder#3658]
Configuration:
Spyder 3.0.1
Python 3.5.2
Win 10

Issue:
I need to use mayavi, but it needs PyQt4. I install a PyQt4 4.11, the spyder won't start any longer even if I uninstall the PyQt4

**Comment by ccordoba12** [comment]
You can create a conda environment with PyQt4 and Mayavi, like this

    conda create -n myenv ipykernel mayavi

then use that environment from Spyder, by selecting its Python executable in

    Preferences > Python Interpreter > Python executable

That's the best way to use Mayavi right now.
