### ISSUE TITLE
raw_input is not working on Spyder consoles

### ISSUE THREAD

**Issue by gdiaczok** [spyder-ide/spyder#3662]
## Description
trying to run python 2.7 script in spyder3.  worked Ok in spyder2.  interactive raw_input( ) doesn't display in console window on initial instance.  hit enter and output progresses and stops again after 2 or 3 inputs.  can't get CNTRL 5 to start debug.  further frustration, I can't get spyder2 reinstall using anaconda.   HELP!

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.1 
* Python Version: 2.7.11
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.0 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Are you talking about evaluating expressions with `raw_input` in a Python or IPython console?

**Comment by gdiaczok** [comment]
I use raw_input('Some user message:') in my python 2.7 script to communicate with the Python console.  With spyder 2 I could input values in the console and and python would continue.  The same code with spyder 3, no annunciation happens in the console unless a hit enter first, but then a blank input is read by python.  For multiple subsequent raw_input() sometimes the input string appears and sometimes not.  I've unloaded and re-installed python 2.7 and spyder 3 twice using anaconda.  never had this problem before using anaconda python/spyder in 2 1/2 years.

**Comment by gdiaczok** [comment]
Entered a response as comment on github.  wasn't expecting an email.  I'll use email in future.

I use raw_input('some message: ') to request an input from the spyder console.  The first message after initiating run, doesn't appear.  hitting enter enters a blank to the python 2.7 script.  subsequent raw_input() statements sometimes appear and sometimes not.  tried reinstalling twice.  I've used anaconda and python 2.7 and spyder 2 for 2 1/2 years, never a problem.  first attempt with spyder 3, and it doesn't work.  

Ant ideas?

Greg




Original message

**Comment by ccordoba12** [comment]
Unfortunately the Python Console has a lot of problems on Windows, the main one being the one you're reporting: that you need to press Enter several times to evaluate commands.

What happens if you use the IPython Console instead?

**Comment by gdiaczok** [comment]
Same problem.

How do i re-install spyder 2 using conda?  i'm aware there is an uninstall and install option set, but what is spyder called in the conda call, spyder3, spyder-3, ...?  I haven't been able to guess it.

Greg
  


Original message

**Comment by gdiaczok** [comment]
Carlos

I've been able to "remove" spyder 3 and "install" spyder 2 using anaconda commands.  I'm impressed with the anaconda environment, it just works.  tried two other installers with no useful results.  I'm off to get my previous operating environment working.  I was grateful for your response to make me aware there was an inherent fault with spyder 3 and get back to spyder 2.

Thanks,
Greg



Original message

**Comment by ccordoba12** [comment]
This has to be an issue with Qt, I think. We haven't touched anything related to raw_input in Spyder 3.0.

**Comment by gdiaczok** [comment]
I was disappointed I didn't see any problem on the github blog re: sypder 3.0 immaturity with windows.  I need to learn how to set up and operate in an alternate conda environment for major updates.

Let me know when the spyder 3 integrated environment gets fixed.  I think spyder is the most useful IDE for python and, for my usage, the easiest to navigate and develop code.  

Thanks,
Greg



Original message

**Comment by ccordoba12** [comment]
No more work is going to be done on the Python console, and it'll be deactivated on Windows since Spyder 3.2.

Please use the IPython console instead.

**Comment by nbonacchi** [comment]
Just in windows I hope...
The ability to run modules using F5 in a new dedicated python console and interact with it later is one of the main reasons I love spyder. Ît's simple and clean to run tests on specific modules and debug your code in parts, running stuff in its own 'clean' environment is also important. I guess that if the IPython console had the same option it would be fine. Please consider this before removing the functionality.

**Comment by ccordoba12** [comment]
@nbonacchi, it's going to be removed for all OSes in Spyder 4, but we'll move all its functionality to the IPython console before removing it. I can assure that :-)
