### ISSUE TITLE
spyder doesn't start , using python(x,y)

### ISSUE THREAD

**Issue by gaurav-samsung** [spyder-ide/spyder#3666]
## Description of your problem

i have installed python(x,y). When i click on spyder, the console comes up for a brief instance, but goes away in a flash. 

when i do spyder --show-console, i get this message: 'failed to create process'

please advise what to do.
thanks,

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: ?
* Python Version: 2.7
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
PythonXY hasn't been updated in a long time, so we can't help you with this error.

We sincerely recommend you to change to WinPython or Anaconda, which are better maintained.
