### ISSUE TITLE
Installation of Spyder 3.0.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by ckaldemeyer** [spyder-ide/spyder#3667]
## Description of your problem

How can I install the latest version of Spyder under Ubuntu 16.04?

**What steps will reproduce the problem?**

The current version of [Spyder][1] from the official ubuntu sources is 2.3.8 which is outdated since meanwhile version 3.0.1 exists.

In the Linux installation instructions it is referred to the latest debian package if the Ubuntu package is outdated which is not working in my case.

What's the easiest way to install the newest version of Spyder on Ubuntu 16.04?

  [1]: https://pythonhosted.org/spyder/installation.html

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 3.5
* Operating system: Ubuntu 16.04 64 Bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
You can run

    pip install -U --user spyder

or install the Anaconda Python distribution (which comes with Spyder, among a bunch of other packages).

**Comment by ckaldemeyer** [comment]
Hi Carlos,

thanks for your answer. But how can I start Spyder when it has been installed with pip?

Best
Cord

**Comment by ccordoba12** [comment]
You need to open a terminal and run

    spyder

or you can also launch it from Unity because I'm almost sure we install a desktop file that will allow that.

**Comment by ccordoba12** [comment]
Or

    spyder3

if you installed Spyder for Python 3.

**Comment by ckaldemeyer** [comment]
That was also my first guess but it's not working and throws up an error:

Here's what I did:

1. Installation:

		cord@cord-Laptop:~/Programmierung/oemof$ sudo pip install -U --user spyder
		The directory '/home/cord/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
		The directory '/home/cord/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
		Collecting spyder
		  Downloading spyder-3.0.1-py3-none-any.whl (3.4MB)
		    100% |████████████████████████████████| 3.4MB 419kB/s 
		Requirement already up-to-date: pep8 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: qtconsole>=4.2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pickleshare in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pylint in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: sphinx in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: psutil in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: nbconvert in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: jedi in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pyflakes in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: qtawesome in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: rope-py3k in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pyzmq in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pygments>=2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: qtpy>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: ipykernel>=4.1 in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: jupyter-client>=4.1 in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: jupyter-core in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: traitlets in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: isort>=4.2.5 in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
		Requirement already up-to-date: six in /usr/lib/python3/dist-packages (from pylint->spyder)
		Requirement already up-to-date: astroid<1.5.0,>=1.4.5 in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
		Requirement already up-to-date: mccabe in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
		Requirement already up-to-date: snowballstemmer>=1.1 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: imagesize in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: babel!=2.0,>=1.3 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: docutils>=0.11 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: alabaster<0.8,>=0.7 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: Jinja2>=2.3 in /usr/lib/python3/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: nbformat in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: mistune!=0.6 in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: entrypoints in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: ipython>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: tornado>=4.0 in /usr/local/lib/python3.5/dist-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: ipython-genutils in /usr/local/lib/python3.5/dist-packages (from traitlets->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: decorator in /usr/local/lib/python3.5/dist-packages (from traitlets->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: lazy-object-proxy in /usr/local/lib/python3.5/dist-packages (from astroid<1.5.0,>=1.4.5->pylint->spyder)
		Requirement already up-to-date: wrapt in /usr/local/lib/python3.5/dist-packages (from astroid<1.5.0,>=1.4.5->pylint->spyder)
		Requirement already up-to-date: pytz>=0a in /usr/local/lib/python3.5/dist-packages (from babel!=2.0,>=1.3->sphinx->spyder)
		Requirement already up-to-date: MarkupSafe in /usr/lib/python3/dist-packages (from Jinja2>=2.3->sphinx->spyder)
		Requirement already up-to-date: jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python3.5/dist-packages (from nbformat->nbconvert->spyder)
		Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.3 in /usr/local/lib/python3.5/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: simplegeneric>0.8 in /usr/local/lib/python3.5/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: setuptools>=18.5 in /home/cord/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: pexpect; sys_platform != "win32" in /home/cord/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: wcwidth in /usr/local/lib/python3.5/dist-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: ptyprocess>=0.5 in /home/cord/.local/lib/python3.5/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Installing collected packages: spyder
		Successfully installed spyder-3.0.1

2. Start

		cord@cord-Laptop:~/Programmierung/oemof$ spyder
		Traceback (most recent call last):
		  File "/home/cord/.local/bin/spyder", line 7, in <module>
		    from spyder.app.start import main
		ImportError: No module named 'spyder'

3. Trying with "spyder3":

		cord@cord-Laptop:~/Programmierung/oemof$ spyder3
		Die Anwendung »spyder3« ist momentan nicht installiert. Sie können sie durch folgende Eingabe installieren:
		sudo apt install spyder3
		cord@cord-Laptop:~/Programmierung/oemof$ 

Btw: I want to use Spyder only with Python3.

How can I fix the error?

**Comment by ckaldemeyer** [comment]
The sudo-H option and a re-install brings up the same result:

		cord@cord-Laptop:~/Programmierung/oemof$ sudo -H pip install --upgrade --no-deps --force-reinstall -U --user spyder
		Collecting spyder
		  Using cached spyder-3.0.1-py3-none-any.whl
		Installing collected packages: spyder
		  Found existing installation: spyder 3.0.1
		    Uninstalling spyder-3.0.1:
		      Successfully uninstalled spyder-3.0.1
		Successfully installed spyder-3.0.1
		cord@cord-Laptop:~/Programmierung/oemof$ spyder
		Traceback (most recent call last):
		  File "/home/cord/.local/bin/spyder", line 7, in <module>
		    from spyder.app.start import main
		ImportError: No module named 'spyder'

**Comment by ccordoba12** [comment]
Please uninstall spyder from apt-get first and try again

    sudo apt-get remove spyder

**Comment by ckaldemeyer** [comment]
I did that but nothing was installed.

Then I uninstalled spyder using pip and reinstalled it again:

		cord@cord-Laptop:~$ sudo -H pip uninstall spyder
		Cannot uninstall requirement spyder, not installed
		cord@cord-Laptop:~$ sudo -H pip install -U --user spyder
		Collecting spyder
		  Using cached spyder-3.0.1-py3-none-any.whl
		Requirement already up-to-date: pickleshare in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: qtconsole>=4.2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: rope-py3k in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pyflakes in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: jedi in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: qtawesome in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: nbconvert in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pygments>=2.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: psutil in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: sphinx in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pep8 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pyzmq in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: qtpy>=1.1.0 in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: pylint in /usr/local/lib/python3.5/dist-packages (from spyder)
		Requirement already up-to-date: traitlets in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: jupyter-client>=4.1 in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: ipykernel>=4.1 in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: jupyter-core in /usr/local/lib/python3.5/dist-packages (from qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: six in /usr/lib/python3/dist-packages (from qtawesome->spyder)
		Requirement already up-to-date: jinja2 in /usr/lib/python3/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: entrypoints in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: nbformat in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: mistune!=0.6 in /usr/local/lib/python3.5/dist-packages (from nbconvert->spyder)
		Requirement already up-to-date: imagesize in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: docutils>=0.11 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: snowballstemmer>=1.1 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: alabaster<0.8,>=0.7 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: babel!=2.0,>=1.3 in /usr/local/lib/python3.5/dist-packages (from sphinx->spyder)
		Requirement already up-to-date: astroid<1.5.0,>=1.4.5 in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
		Requirement already up-to-date: isort>=4.2.5 in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
		Requirement already up-to-date: mccabe in /usr/local/lib/python3.5/dist-packages (from pylint->spyder)
		Requirement already up-to-date: ipython-genutils in /usr/local/lib/python3.5/dist-packages (from traitlets->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: decorator in /usr/local/lib/python3.5/dist-packages (from traitlets->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: ipython>=4.0.0 in /usr/local/lib/python3.5/dist-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: tornado>=4.0 in /usr/local/lib/python3.5/dist-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: MarkupSafe in /usr/lib/python3/dist-packages (from jinja2->nbconvert->spyder)
		Requirement already up-to-date: jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python3.5/dist-packages (from nbformat->nbconvert->spyder)
		Requirement already up-to-date: pytz>=0a in /usr/local/lib/python3.5/dist-packages (from babel!=2.0,>=1.3->sphinx->spyder)
		Requirement already up-to-date: wrapt in /usr/local/lib/python3.5/dist-packages (from astroid<1.5.0,>=1.4.5->pylint->spyder)
		Requirement already up-to-date: lazy-object-proxy in /usr/local/lib/python3.5/dist-packages (from astroid<1.5.0,>=1.4.5->pylint->spyder)
		Requirement already up-to-date: setuptools>=18.5 in /root/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: pexpect; sys_platform != "win32" in /root/.local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: simplegeneric>0.8 in /usr/local/lib/python3.5/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.3 in /usr/local/lib/python3.5/dist-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: ptyprocess>=0.5 in /root/.local/lib/python3.5/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Requirement already up-to-date: wcwidth in /usr/local/lib/python3.5/dist-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
		Installing collected packages: spyder
		Successfully installed spyder-3.0.1
		cord@cord-Laptop:~$ spyder
		Die Anwendung »spyder« ist momentan nicht installiert. Sie können sie durch folgende Eingabe installieren:
		sudo apt install spyder
		cord@cord-Laptop:~$ 

Now, no executable seems to be found which is weird :/

Any ideas? Sorry, if I am a bit dumb...

**Comment by ckaldemeyer** [comment]
I have now tried another approach via Anaconda (Python3/64 Bit).

But when I start Spyder via:

    cord@cord-Laptop:~$ .anaconda3/bin/spyder

It looks like **it as you can see here: http://pasteboard.co/pwxeSsurj.png

So I looked for all files, caches, etc. from remaining installations and deleted them e.g. everything spyder-related that's not within the anaconda3-folder.

But still the same result..

And if I reset the spyder settings in the menu, the following messages get written on the terminal:

    cord@cord-Laptop:~$ *** Reset Spyder settings to defaults ***
    removing: /home/cord/.config/spyder-py3/onlinehelp
    removing: /home/cord/.config/spyder-py3/spyder.ini
    removing: /home/cord/.config/spyder-py3/temp.py
    removing: /home/cord/.config/spyder-py3/template.py
    removing: /home/cord/.config/spyder-py3/history.py
    removing: /home/cord/.config/spyder-py3/history_internal.py
    removing: /home/cord/.config/spyder-py3/workingdir
    removing: /home/cord/.config/spyder-py3/.ropeproject
    removing: /home/cord/.config/spyder-py3/langconfig
    removing: /home/cord/.config/spyder-py3/spyder.lock

During the restart, the spyder "Start Window" at first seems to have the right size (according to my screen resolution) but after a few seconds it gets big as the menus (see the screenshots above).

To me it looks as spyder gets aligned to a lower screen resolution such as 800 * 600.

Any hints?

**Comment by ckaldemeyer** [comment]
I created a new user account, signed on and did a fresh install of anaconda. But it still leads to the same result. So to me it looks as this is an error/bug with spyder on Ubuntu 16.04.

Any hints?

**Comment by ckaldemeyer** [comment]
I'll create a new issue as this is obsolete..

**Comment by skidzo** [comment]
dont use
`pip install -U spyder`
with Anaconda

with Anaconda you have to wait until the packes are released from Continuum Analytics...

when are they releasing Qt 5.7 and PyQt5.7 and the new QtCharts for Anaconda? On Mac and Linux, there were missing Binaries, when I last tried, at least under Windows and MacOS X El Capitan

**Comment by ccordoba12** [comment]
Anaconda is going to support Qt 5.6 during this year and probably the next one.
