### ISSUE TITLE
spyder segfaults on exit

### ISSUE THREAD

**Issue by elegantandrogyne** [spyder-ide/spyder#3668]
## Description of your problem

spyder segfaults on exit instead of exiting gracefully
**What steps will reproduce the problem?**

1. make a script called spyder3
`#! /usr/bin/env python3`
`from spyder.app import start`
`start.main()`

2. `chmod +x spyder3` then `./spyder3`
3. close spyder (by closing the window, choosing File>Quit or sending SIGTERM, i.e. `pkill spyder3`)

**What is the expected output? What do you see instead?**
should exit gracefully (i.e. python returns 0) - I get a segfault instead, python exits with code 139

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 3.5.2+
* Operating system: Debian stretch/sid amd64

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0+git14-ga40e185 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
What are your Qt and PyQt versions?

**Comment by elegantandrogyne** [comment]
python3-pyqt5: 5.7+dfsg-2+b1
qt5 (packages: libqt5core5a, libqt5gui5): 5.7.1~20161021+dfsg-5

**Comment by ccordoba12** [comment]
It seems you're on Debian experimental. Do you have QtWebEngine installed as part of Qt5? Sorry, but I don't know the exact name of the package on Debian :-)

**Comment by elegantandrogyne** [comment]
python3-pyqt5.webkit: 5.7+dfsg-2+b1 (without it spyder would raise 
ImportError)

I'm on testing/unstable, which is actually much more stable than 
experimental :). I tested on another machine with Debian testing: 
installed spyder3 (also v3.0.1) from pip, and Python as well as the Qt 
framework and bindings from distro's repo. Problem exists as well.

Spyder 3.0.1 for python2.7 also segfaults.

**Comment by ccordoba12** [comment]
I think this was fixed in the latest Debian packages.

**Comment by elegantandrogyne** [comment]
OK indeed on 3.1.2.
