### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by hofsaess** [spyder-ide/spyder#3669]
## Description of your problem

Hi I working with linux mint 17 64 bit,  after updating the following libs

libcuda1-352-updates (352.63-0ubuntu0.14.04.1) to 367.57-0ubuntu0.14.04.1
libcurl3 (7.35.0-1ubuntu2.9) to 7.35.0-1ubuntu2.10
libcurl3-gnutls (7.35.0-1ubuntu2.9) to 7.35.0-1ubuntu2.10
libcurl3-nss (7.35.0-1ubuntu2.9) to 7.35.0-1ubuntu2.10
libcurl3:i386 (7.35.0-1ubuntu2.9) to 7.35.0-1ubuntu2.10
libpq5 (9.3.14-0ubuntu0.14.04) to 9.3.15-0ubuntu0.14.04

I can't start spyder:

**What is the expected output? What do you see instead?**
[1110/095452:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[1110/095452:ERROR:nss_util.cc(839)] After loading Root Certs, loaded==false: NSS error code: -8018
Segmentation fault (core dumped)

I tried a uninstll and reinstall direct from git and also from pip.

Nothing is working.

Any ideas?

* Spyder Version: 4 and 3 both tested
* Python Version: 2.7
* Operating system: linux 64 bit

## Dependencies

not working, cant open a gui

**Comment by jitseniesen** [comment]
This looks similar to #3520. It's speculated to be a problem between PyQt 5.7 and graphic card driver, so I guess it's your libcuda update causing the problems.

**Comment by hofsaess** [comment]
Ok,

what i had is a lot of running QtWebEngineProcess. 
Is it useful to switch to pyqt 5.6?

**Comment by hofsaess** [comment]
so after trying different things spyder is running?

I installed the NVIDIA-Linux-x86_64-361.42 driver and qt5.6 and pyqt5.7.

After that is running again.

**Comment by rihun** [comment]
Hi hofsaess

I also face the same kind of problem.

After upgrade the keras I found my spider is not open.
It shows Segmentation Fault(Core Dumped)
I use Gigabyte GEforce GTX 1080 GPU card.

Please help me how I can solve it
