### ISSUE TITLE
Profiler is not showing time units 

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#3672]
As it is mentioned in this Stackoverflow post

http://stackoverflow.com/q/40509525/438386

our profiler is not showing the time units spent in every function or method call (e.g. seconds, minutes, etc). We really need to add them to make things clearer for our users.

@malliwi88, please work on this one.

**Comment by malliwi88** [comment]
@ccordoba12 Working on it

**Comment by ccordoba12** [comment]
Ok, the idea is just to add a unit (be it secs or milisecs) to the `Time` column of our profiler. So please investigate what the units reported by the Profiler are, and then just change that column name accordingly.

**Comment by ccordoba12** [comment]
@malliwi88, this is very easy. Please submit a PR tomorrow about it.

**Comment by malliwi88** [comment]
@ccordoba12 #3735 

Now profiler is showing time units. I think that maybe it is necessary to do a little cleaning to the profiler, I found a lot of code not functional inside profiler.

The final result looks like this:
![spyder 3 1 0 dev0 python 3 5 _001](https://cloud.githubusercontent.com/assets/5307894/20584001/8cdc3d4e-b1bc-11e6-9ef9-09f3b0b90436.png)

Any suggestions or corrections are welcome.
