### ISSUE TITLE
Autoindentation not working in first line

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#3680]
Autoindentation doesn't work at the first line

**What steps will reproduce the problem?**

1. Write something that should be autoindented in the first line of a file
`def example():`
2. press Enter

**What is the expected output? What do you see instead?**
next line should e indented but It isn't

This error is making some test to fail, https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/sourcecode/tests/test_autoindent.py#L60

I think It could be solved changing this line https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/sourcecode/codeeditor.py#L1716

**Comment by ccordoba12** [comment]
This was fixed in PR #3680.
