### ISSUE TITLE
PEP 528 / 529 seems to have no beneficial effect on Python-3.6.0b3 / Spyder

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#3684]
## Description of your problem

trying "!dir" in Spyder console, hoping for the best as there may be some "utf-8" standardization thanks to PEP 528 / 529 
**What steps will reproduce the problem?**

1. "!dir"
2. 
3. 

**What is the expected output? What do you see instead?**
normal (french) character display

instead I see usual unperfection
![pep_528-529_where_are_you](https://cloud.githubusercontent.com/assets/4312421/20240181/5bf917fe-a912-11e6-95e8-e65fcb9a8845.PNG)

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.0dev of November 4th
* Python Version: 3.6.0b3
* Operating system: Windows 10 64 bit version 1607 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I think this should be discussed with the IPython/Jupyter developers because Spyder doesn't control used in the IPython console.

**Comment by stonebig** [comment]
ok, I raised a similar issue on Jupyterlab.

**Comment by ccordoba12** [comment]
There's nothing we can do about this one, sorry.
