### ISSUE TITLE
spyder 3.0.0 check for updates, pop up window , links (Releases , Installation) dont work

### ISSUE THREAD

**Issue by nc33** [spyder-ide/spyder#3688]
## Description
spyder 3.0.0 -Help- check for updates- pop up window links (Releases , Installation) and OK button do not work
**What steps will reproduce the problem?**

1. Install Spyder in Win 10 via Anaconda3(64 bit) package
2. click >help-check for updates- pop up window opens
3. try to click on links >Releases page or Installation instructions

**What is the expected output? What do you see instead?**
Releases ..expected = open Spyder Releases web page  
Installation instructions..expected=open Installation instructions web page
actual= nothing happens
**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```
![pop up](https://cloud.githubusercontent.com/assets/23253534/20252397/bd05f9d0-a9ef-11e6-9cbb-7eb39066cacf.jpg)

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in Spyder 3.0.2.
