### ISSUE TITLE
How to remember the configurations of connecting to remote kernel?

### ISSUE THREAD

**Issue by AlexLuya** [spyder-ide/spyder#3689]
Hello,
       I can update that remote kernel josn manually,but how to remember the configurations(remote kernel json file location,host,ssh key file location,password) of connectiong to remote kernel?Then I don't need to configure it manually every time.

**Comment by ccordoba12** [comment]
There's no option to do that right now, but it's an interesting suggestion. We'll work on it for a future Spyder version :-)

**Comment by jiagengliu** [comment]
Second that; it's a hassle typing everything again each time since I am connecting through SSH. Maybe add a "save password" option, too.

**Comment by ccordoba12** [comment]
This will be available since our 4.0beta2 version.
