### ISSUE TITLE
Cannot run file from editor, have to type code manually in Python (not IPython) console

### ISSUE THREAD

**Issue by tranquockhue** [spyder-ide/spyder#3690]
I installed gTTS. I've been testing it for a while. At first, there was output when I ran the file from the editor with IPython. Then, I couldn't do it anymore. I have to type the code manually into Python (not IPython) console to make it work. I've checked the network usage in Task Manager, seems that only when I type the code into Python console, there is Python's network usage  
The code is simple:

```
import gtts

tts = gtts.gTTS(text='hello', lang='en') 
tts.save=("F:/Desktop/testmp3")
```

**What is the expected output? What do you see instead?**
A MP3 file but I see nothing
**Please provide any additional information below**

* Spyder Version: 3.0.1
* Python Version: 3.5
* Operating system: Windows 10 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
How did you install this `gtts` package? And what does it do?

**Comment by tranquockhue** [comment]
[https://github.com/pndurette/gTTS](url)
This is gTTS package. It's a text-to-speech(TTS) package which uses Google Translate TTS.
The first time after I installed the package, it worked flawlessly. But after a while using it, then the script didn't make a result (it actually ran, but no desirable result) when I ran from editor. I had to put every single line of scrips into the Python console. 
By the way, I have used pip to re-install the package for 2 times, and nothing has changed.

**Comment by ccordoba12** [comment]
@dalthviz (our Windows guy!) please review this one :-)

**Comment by tranquockhue** [comment]
I test with Python IDLE, at least it has worked. 
So now I will code the script with Spyder, then copy and paste onto the IDLE.
Btw, hope you guys to find out this bug soon
:D

**Comment by ccordoba12** [comment]
I still don't understand what happens in your case. Could you post a step by step description of your problem? Thanks :-)

**Comment by tranquockhue** [comment]
It's really hard to explain by words (You haven't used gTTS package before, have you?)
Btw, hope you can spend your time, so I can make a Skype or Teamviewer with you.

**Comment by dalthviz** [comment]
Hi @tranquockhue, I have tried the code that you give us and I can generate a MP3 file (when you reproduce it says `hello`), the only thing that maybe its different from the example code that you give is that I put `.mp3` to the creation path of the file:

```
import gtts
tss=gtts.gTTS(text="hello", lang="en")
tss.save("C:/Users/Daniel/Desktop/testmp3.mp3")
```
Also, how are you running the file?, you selected the code that you want to run and then pressed `F9`? or you use `F5`? both of the options worked for me. Here some examples of the output that I resive in the IPython Console:

![image](https://cloud.githubusercontent.com/assets/16781833/20466559/8e93c70e-af43-11e6-8f3b-dcc155777bed.png)

Where `runfile...` its shown when you use the `F5` option (or directly click in the play button in the main window), and the other output when you select in the editor the code you want to run and then press `F9` (or rigth click and `Run selection or current line` ).

Maybe can you reset the preferences in Spyder and try again to run the code from the editor? (Go to `Tools -> Reset Spyder to factory defaults`). Or try changing the path where you want to save the MP3 file. 

Also try another way to import the gTTS with something like this:

```
from gtts import gTTS
tss=gTTS(text="hello", lang="en")
tss.save("C:/Users/Daniel/Desktop/testmp3.mp3")
``` 
Try this options and describe the result :)

**Comment by tranquockhue** [comment]
Ahhh sorry my typo. I forgot " . " in this post.
By the way, it doesn't work. Seem no network activity from Python when I checked it in Task Manager. 
I have tried resetting Spyder" and changing MP3 path.
I use the same script, but with Python IDLE (I installed Anaconda, so I have both Spyder and Python IDLE), then it works.

**Comment by dalthviz** [comment]
Um it's really strange. And if you run another script, something like `print ("Hello")`, the console shows some activity? or it stays the same (without network activity)?

**Comment by tranquockhue** [comment]
Everything else is well. I use some other packages like OpenCV, PyOCR/PyTesseract, Numpy, blah blah, all is well except gTTS. I've also checked firewall settings, everything is okay.

**Comment by tranquockhue** [comment]
Seem that mp3.save from gTTS doesn't work. When I work with it inside IDLE, there is a delay when the package send and receive data from Google servers. But when I work with it inside Spyder, there is no delay!

**Comment by tranquockhue** [comment]
lol How weird it is! After 3 days not using Spyder now I try again and it works! Btw, I hope you will follow this problem because I'm not sure if it works temporarily or not. I will report you guys soon!

**Comment by dalthviz** [comment]
Actually a really strange error. If it appears again, please let us know. :)

**Comment by ccordoba12** [comment]
Yep, please repopen this issue if the error appears again.
