### ISSUE TITLE
bug forwarder from Debain

### ISSUE THREAD

**Issue by picca** [spyder-ide/spyder#3691]
Hello here a bug from a Debian user
Hi,

I'm running Debian testing and have installed Spyder3 from unstable (as there is currently no testing version of spyder3). When trying to run it, I got this error:
$ spyder3
Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/lib/python3/dist-packages/spyder/requirements.py", line 41, in check_qt
    actual_ver = qtpy.PYQT_VERSION
AttributeError: module 'qtpy' has no attribute 'PYQT_VERSION'

It turns out that, although qtpy does not have PYQT_VERSION, it does have __version__ which seems to return the pyqt version. Changing the line above to actual_ver = qtpy.__version__ makes it work. I don't know if this is a quirk of installing the unstable version in testing or just a bug from the switch from qt4 to qt5, but I thought you may want to know.

Regards,
Keziah Milligan

**Comment by ccordoba12** [comment]
Thanks for reporting. You need to update `qtpy` to **1.1.0** or a higher version to fix this error :-)

If the Debian version is older than that, please ask the Debian maintainers to update it.
