### ISSUE TITLE
Turtle always crashes in Spyder in Anaconda (Mac OS Sierra)

### ISSUE THREAD

**Issue by ben-dent** [spyder-ide/spyder#3693]
## Description of your problem

When running a python program that uses turtle, the turtle window will not automatically pop up and then will crash when made the focus. I am using Mac OS Sierra

**What steps will reproduce the problem?**

1. Running a python program that uses turtle 
**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5.2
* Operating system: Mac OS Sierra

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
What toolkit does turtle use? Tk, Qt or Wx?

**Comment by ben-dent** [comment]
Hi, I'm not sure, how can I find out which toolkit it uses?

**Comment by ben-dent** [comment]
Actually uses Tk

**Comment by ccordoba12** [comment]
You need to run this in an IPython console to activate support for Tk (before running your turtle code):

    %gui tk

Please test and let us know if it work for you :-)

If you want to set this change permanently, you can go to

    Tools > Preferences > IPython Console > Graphics > Graphics Backend

and select Tk there.

**Comment by ccordoba12** [comment]
Sorry, the name of the backend in Spyder preferences is `Tkinter`, not `Tk` :-)

**Comment by ben-dent** [comment]
Thanks, that seems to have solved the problem 👍 :)

**Comment by ccordoba12** [comment]
Great!

**Comment by frankbexxx** [comment]
Hi, I'm new here, and I have the same problem, but with windows 10.

What should be the solution?

thank you.

**Comment by frankbexxx** [comment]
running, I've tried Qt5 and star working.

thanks anyway
