### ISSUE TITLE
gi.Gtk clashes with Spyder Matplotlib support in IPython Console

### ISSUE THREAD

**Issue by mobando** [spyder-ide/spyder#3697]
## gi.Gtk clashes with Matplotlib support

The problem is caused by following code.
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
```
If [Spyder Preferences > IPython Console > Graphics > Support for graphics (Matplotlib) > Activate support] is selected, and the snippet is run in the IPython console, then it freezes and cannot be stopped.The IPython console has to be closed and restarted.

The code works properly when run from either the Python Console or from normal instances of Python/IPython in the Linux terminal.

## Versions and main components
* Spyder Version: 3.0.1
* Python Version: 2.7.12
* Operating system: Debian Testing (Stretch)
* IPython Version: 5.1.0

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I think you need to run first in an IPython console this code

    %gui gtk3

to activate support for it (before running your code :-).

Or you can select as backend `Gtk3` in

    Preferences > IPython Console > Graphics > Graphics Backend

**Comment by mobando** [comment]
If `Backend` is set to `Automatic`, then `%gui gtk3` throws an error in the Ipython terminal:
```
In [1]: %gui gtk3  
ERROR:root:Cannot activate multiple GUI eventloops
```

Selecting `Gtk3` as backend works fine, thank you!

Is this the expected behavior of the graphics support, though?

**Comment by ccordoba12** [comment]
The `Automatic` option selects either the `Qt` or `Qt5` backends depending on which version of Qt Spyder is running. We choose to call it `Automatic` because we can set it according to the Qt version used by Spyder.

If you want to use `%gui gtk3` in a console, just select the `Inline` backend.

> Is this the expected behavior of the graphics support, though?

Well, you have to activate the right graphics backend to be able to work with it. This is a requirement to run a graphical application inside another one (in this case, Spyder :-).
