### ISSUE TITLE
Spyder 3.0 : File Explorer not refreshing on time

### ISSUE THREAD

**Issue by simonzcaiman** [spyder-ide/spyder#3698]
## I just recently updated my Spyder from 2 to 3. And I realized that the new file explorer is not as reactive as before.  

**What steps will reproduce the problem?**

1. Go to any directory that have any sub folders in it
2. Rename the folder and press ENTER(Or Delete any folder/item )
3. Now you won't see the the name changed or the removed file is gone
4. However, if you press parent folder button on the top, now you see the changes have been updated to the file explorer

**What is the expected output? What do you see instead?**
I remember Spyder 2 did not have such problem. Whenever I do some renaming or deleting files , the file explorer instantly reflects my changes. 

**Please provide any additional information below**
nan

## Versions and main components

* Spyder Version:3.0
* Python Version:3.5
* Operating system:Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I don't see that problem. Are you using PyQt4 or PyQt5?

**Comment by simonzcaiman** [comment]
I'm currently using PyQt4. Just switched to PyQt5 and now the problem is gone. Thank you so much! Amazing works :)
