### ISSUE TITLE
Create a get_words method in introspection utils

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3704]
Create a generic function that finds all words in a given source code file (language agnostic)

here
https://github.com/spyder-ide/spyder/blob/master/spyder/utils/introspection/utils.py

To filter out letters or tokens we could use the information stored on pygments.

So that we can make inline completions on word type (like VS CODE does).

We need to write test for a couple of different files (c, C++, python, R, HTML, CSS)

**Comment by ccordoba12** [comment]
But that's what the fallback completer is doing right now, isn't it?

**Comment by goanpeca** [comment]
Nope, not for EVERY word... only for special words

**Comment by malliwi88** [comment]
Hello @goanpeca  @ccordoba12 

I have been working on code completion widget.

* Now, I have a change for activating code completion  widget always a user input and suggestions exists (key event deferent to modifier events)
* An interesting thing is happening (three different behavioral on the widget) as you can see in the gif below

![bug-widgetcompletion](https://cloud.githubusercontent.com/assets/5307894/20452744/4bf93128-addf-11e6-8119-d5f383d58835.gif)

It can be associated with the three actual plugins  (Jedi, Rop, fallback ) **fight for completion task** for same user input text.

I'm planning to have a first PR with this changes.

I think that we are in a good way for having a better code completion feature, thanks for your fantastic suggestions @ccordoba12, @goanpeca
