### ISSUE TITLE
F8 shortcut for static code analysis does not work

### ISSUE THREAD

**Issue by bdrung** [spyder-ide/spyder#3705]
## Description

**What steps will reproduce the problem?**

Open a file with spyder and press F8.

**What is the expected output? What do you see instead?**

I expect that the static code analysis is executed and the result is shown in the corresponding window. Instead nothing happens.

**Please provide any additional information below**

`spyder_pylint.pylint.Pylint.run_pylint()` is not executed when F8 is pressed despite `self.register_shortcut()` being called in `spyder_pylint.pylint.Pylint.register_plugin()` on startup.

## Version and main components

* Spyder Version: 3.0.1 
* Python Version: 3.5.2+
* Qt Versions: 5.6.1, PyQt5 5.7 on Ubuntu 16.10

## Dependencies
```
pyflakes >=0.6.0 :  1.2.3 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  None (NOK)
nbconvert >=4.0  :  None (NOK)
pandas >=0.13.1  :  0.17.1 (OK)
numpy >=1.7      :  1.11.1rc1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
rope >=0.9.4     :  None (NOK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.2.0 (OK)
matplotlib >=1.0 :  1.5.2rc2 (OK)
pylint >=0.25    :  1.5.6 (OK)
```

**Comment by ccordoba12** [comment]
It's working for me :-/

**Comment by bdrung** [comment]
Can you give me some hints where in the code I have to trace the keypress (to see where it fails)?

**Comment by danuker** [comment]
I am not sure if this is a related case, or a different bug, but it seems to break in this case:
1. Manually paste a file path to analyze into the Static code analysis pane
2. Click Analyze
3. Click the file in the editor
4. Press F8

This leads to some weird state, where the file path box is blank, but the "Analyze" button is enabled. Clicking "Analyze" throws an error.
Clicking the arrow next to the file path box only shows the files analyzed with F8, but not the ones manually pasted in.

**Comment by bdrung** [comment]
I retested spyder 3.2.6+dfsg1-2 on Ubuntu 18.04 and F8 works there as expected. So I am closing this ticket.

@danuker Your issue looks like a different problem. Please open a separate ticket.
