### ISSUE TITLE
Spyder won't start on Windows 7

### ISSUE THREAD

**Issue by ZahlGraf** [spyder-ide/spyder#3710]
## Description of your problem
**What steps will reproduce the problem?**

On command line I enter: spyder --show-console

**What is the expected output? What do you see instead?**

It shows a small loading image. First I can read "Initializing" then "Loading Help..." but afterwards the image disappears and the spyder process is stopped. Nothing happens then.
There is no output at the console: No error message, no text that could help.

Also "spyder --reset" did not work and even "spyder --help" does not show anything.

## Versions and main components

* Spyder Version: I don't know (help does not show up). I installed it with pip today, to I think it is the most recent version.
* Python Version: 2.7.11 (64 bit)
* Operating system: Windows 7 (64 bit)

One thing to mention here: I do not have a specific distribution of python, I just installed plain python 2.7 and installed some packages with pip (for example PyQt5, matplotlib, ...)

## Dependencies
...

**Comment by ccordoba12** [comment]
Do you have an Nvidia or AMD graphics card in your computer?

**Comment by ZahlGraf** [comment]
Oh sorry, I missed to give you my hardware configuration:
Intel i7-4770k
32 GiB Ram
NVIDIA GeForce GTX 680

**Comment by ccordoba12** [comment]
Ok, it seems you're affected by a bug in pyqt5 5.7 wheels, as it's described in issue #3520. That issue is about Linux, but I'm almost sure this is the same problem for Windows.

For the time I recommend you to either downgrade pyqt5 to 5.6 or install Anaconda instead.

**Comment by ZahlGraf** [comment]
I uninstalled PyQt5 and switched to PyQt4 and now Spyder starts.
