### ISSUE TITLE
no keyboard responding for spyder 

### ISSUE THREAD

**Issue by kyuusaku** [spyder-ide/spyder#3713]
I installed the python env by using `Anaconda 4.2.0 (64-bit)`. 
But cannot use spyder. 
There is no keyboard responding for spyder.

Any ideas for this problem?

* Spyder Version: 3.0.1
* Python Version: 2.7.12
* Operating system: ubuntu 16.04

**Comment by ccordoba12** [comment]
What do you mean by

> There is no keyboard responding for spyder.

**Comment by kyuusaku** [comment]
Hi, @ccordoba12 

The error is 

```
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
Qt: Failed to compile a keymap!
Current XKB configuration data search paths are: 
/home/lab/anaconda2/lib
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
```

I `export QT_XKB_CONFIG_ROOT=/usr/ share/X11/xkb` to solve this problem. It works.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it :-)

**Comment by esason** [comment]
hi,
I have the same problem.
I installed the python env by using Anaconda 4.3.0 (64-bit).
There is no keyboard responding for spyder.

this is the error that i get:
=====
Qt: XKEYBOARD extension not present on the X server.
Qt: Could not determine keyboard configuration data from X server, will use hard-coded keymap configuration.
Qt: Failed to compile a keymap!
Current XKB configuration data search paths are: 
/home/eliyahus/Program_Files/python/anaconda/anaconda2/lib
Use QT_XKB_CONFIG_ROOT environmental variable to provide an additional search path, add ':' as separator to provide several search paths and/or make sure that XKB configuration data directory contains recent enough contents, to update please see http://cgit.freedesktop.org/xkeyboard-config/ .
=====

I made this export: export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
but than got another problem - i don't get the letter that i want to type.
getting the same error ...
=====
Qt: XKEYBOARD extension not present on the X server.
=====

I am login with a vncserver to ubuntu 14.04.
can someone help?

regards,
Eli.

**Comment by twmacro** [comment]
@esason, I also observed this behavior of having incorrect key mappings. It's not Spyder-specific though, it is (as I understand it) a disconnect between older X servers and QT5 in general. The best discussion I could find on this is here: [https://bugreports.qt.io/browse/QTBUG-44938](https://bugreports.qt.io/browse/QTBUG-44938). That posting may offer a workaround for you ... or, maybe you can do something similar to what I did:

In my case, I experienced this problem using the OpenText Exceed 14 server on a Windows 7 machine to log into a Linux machine. The fix for me was literally to click on the XKEYBOARD extension in the Exceed program: Tools->Configuration->X Server Protocol->Extensions. I hope newer servers have this turned on by default.

Good luck!

**Comment by maogewudi007** [comment]
@esason  me too. I had also faced this problem.

**Comment by esason** [comment]
hi, 
I fix some of the problems, but no all of them.
now, spyder is respond to my keyboard correctly,
but it still mention the next error:
```
QXcbConnection: Failed to initialize XRandr
Qt: XKEYBOARD extension not present on the X server.
```
1) I uninstall tightvncserver and install vnc4server
2) export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
   as mentioned before.

it seems that the problem is reletaed to vncserver issues - how to configure a vnc server which supports xkeyboard extention...

**Comment by maogewudi007** [comment]
@esason Thanks for your response. Now, I use the pycharm to replace the spyder.  PyCharm can been used in the vnc situation.

**Comment by jiqiujia** [comment]
Before open spyder
`export XKB_DEFAULT_RULES=base`
following https://bugreports.qt.io/browse/QTBUG-44938

**Comment by scivision** [comment]
I found the only way to type in Spyder over VNC was to use TurboVNC client, even the things above didn't work for must with TightVNC, but I could type with TurboVNC.  I was using Ubuntu 16.04 on both ends.

**Comment by athlonshi** [comment]
For those using Exceed X Server, you may also need to change Xconfig setting. Go to Xconfig --> Settings --> Protocol... --> Extensions -->  check XKEYBOARD and save the settings.

**Comment by Oreki47** [comment]
I'm using TightVNC with Ubuntu 14.04.
It works on my machine with:
export XKB_DEFAULT_RULES=base
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
The set rules has to come first.

**Comment by xgniu** [comment]
I'm using Xmanager5. After the two export actions, the keyboard was responding but had incorrect mappings. Then I did the following: Xconfig->Default Profile->Properties->Advanced->X Extensions-> check the 'XKEYBOARD'. It worked.

**Comment by XueDx** [comment]
@xgniu I faced this problem about a mouth ago, I fix it following yours, thx.

**Comment by AbNeil** [comment]
Hello,
I am using ssh to connect to my server. When i type spyder in the terminal it gives me the following error

QXcbConnection: Could not connect to display 
Aborted (core dumped)

I tried uinstalling and reinstalling spyder but all of no use. I even tried XKB_DEFAULT_RULES=base but no success.
Does anybody have an idea what's going wrong.

**Comment by ccordoba12** [comment]
@AbNeil, you need to create a ssh tunnel to your X remote server to start Spyder there. That's not easy (I don't even remember how that's done).

Please use VNC or something like that to do it.

**Comment by arutema47** [comment]
I got the same problem in ubuntsu 14.04.

I did 
export QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb
export XKB_DEFAULT_RULES=base
to solve the problem.

**Comment by popina1994** [comment]
I have got the same issue. 
I am using Ubuntu 16.04 as OS and tight VNC server. I 
I have tried with @arutema47's approach, but the problem remains. Any other ideas?

**Comment by ValueQuant** [comment]
Hi All,
Any update on the above issue. I am using Ubuntu 16.04.4 LTS (Xenial Xerus) on Amazon AWS instance (AMI-  https://aws.amazon.com/marketplace/pp/B07MGHCWTB?qid=1556607966309&sr=0-5&ref_=srh_res_product_title) and facing the same issue.
Have tried everything mentioned above but spyder is still not mapping right keys. 
Other editors on the system (e.g. gedit etc.) are correctly working and mapping correct keys to the display.

**Comment by vr308** [comment]
> I'm using Xmanager5. After the two export actions, the keyboard was responding but had incorrect mappings. Then I did the following: Xconfig->Default Profile->Properties->Advanced->X Extensions-> check the 'XKEYBOARD'. It worked.

@xgniu - having the same use with incorrect key mapping even after setting the rules. Where do I find Xconfig? I am using TightVNC..

**Comment by sitadrost** [comment]
Hi all,

I'm facing the same issue: incorrect key mapping in Spyder when running through VNC (TightVNC on the server side, RealVNC on the client side). I've installed Spyder4 (with Python 3.7) under Miniconda3, on Ubuntu 20.04. Other applications work fine.

Should I switch to a different VNC-server? And if so, which one would you recommend?
Or should I try this Xconfig->Default Profile->Properties->Advanced->X Extensions-> check the 'XKEYBOARD' ? In that case, where do I find Xconfig?

Many thanks!
Sita
