### ISSUE TITLE
different between spyder and python in terminal

### ISSUE THREAD

**Issue by zhanghan328** [spyder-ide/spyder#3720]
## Description of your problem
![6239a9335826955468832cd8f76b6bc7](https://cloud.githubusercontent.com/assets/16316669/20488099/c7613b9a-b040-11e6-9e6f-2eaf63bfc2ad.jpg)
I could import tensorflow perfectly in terminal but in spyder2.7 there are mistakes above:
Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH. 
I want to ask why it is different?  What i should do ? Thanks!
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.7
* Python Version: 2.7.12
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
That's because Spyder reads your environment variables only if you start from a terminal.
