### ISSUE TITLE
DataFrame viewer should display tooltips for truncated column headers

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3721]
When a DataFrame with long column names is viewed, the column names are truncated. It would be useful to have the full column names displayed as tooltips when pointing at them.

I my case, I have got many columns with long names, so I want to avoid pressing the Resize button to keep the data compact.

(Seen in WinPython-64bit-3.5.2.3 with "Spyder 3.1.0.dev0".)

**Comment by ccordoba12** [comment]
Thanks for the suggestion. We'll try to work on it for Spyder 3.2.

**Comment by ccordoba12** [comment]
@malliwi88, please work on this one.

**Comment by malliwi88** [comment]
Working on this, I already made rebase/merge 3.x, according to your suggestion #3611. @ccordoba12 :+1:

**Comment by malliwi88** [comment]
@jondo 

You could provide a code or capture to take as an example of a problem case?, Please.
I think that it would have a base case to illustrate this new feature in the future.

Thanks

**Comment by jondo** [comment]
The screenshot shows part of a DataFrame with over 400 columns. The highlighted column has the long name `QC_CAQ_RMSE_0_95_Percentile_Long_MW_MESSWERT`. It would be great to have this name displayed as column header tooltip.
![screenshot](https://cloud.githubusercontent.com/assets/21648/20917954/d50167c0-bb94-11e6-88e0-b9666b69004f.png)

**Comment by ccordoba12** [comment]
@camendoza94, please work on this one.

The idea is that after putting the mouse over a column name, a tooltip be shown with the full column's name. For this you need to work on this file

    spyder/widgets/variableexplorer/dataframeeditor.py

**Comment by Prikers** [comment]
I think this can be closed following @dalthviz work in #3873
![image](https://user-images.githubusercontent.com/20270441/31576481-0057eb3a-b0fc-11e7-9688-54a393fad965.png)

**Comment by goanpeca** [comment]
Fixed by https://github.com/spyder-ide/spyder/pull/3873
