### ISSUE TITLE
spyder-ide conda channel doesn't appear up-to-date

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#3723]
I've just tried to update to `Spyder 3.0.2` using conda:
```
conda update spyder
```
And it seems that the spyder-ide Anaconda channel hasn't been updated beyond the `3.0.0b7` release: https://anaconda.org/spyder-ide/spyder/files

Is this expected to be updated regularly with new releases - or do you have another channel that you're hosting updates on?

**Comment by ccordoba12** [comment]
We only use our own Anaconda channel to distribute betas. Final releases are distributed through the official Continuum channels.

Please be patient. I'm sure Continuum will update Spyder in a couple of days :-)

**Comment by durack1** [comment]
@ccordoba12 ok, I was under the impression that the channel `(-c spyder-ide)` was the best place to look..

It seems the continuum channel lists version `3.0.0` (Sept 24 2016) at the moment: https://docs.continuum.io/anaconda/pkg-docs

It's a pity that there is such a lag in the system, I've just been getting the upgrade nag screen for a couple of days, and went to upgrade using conda and there just wasn't the updated package there

**Comment by ccordoba12** [comment]
`3.0.0` is the version that comes with Anaconda 4.2 (the latest version of Anaconda), but `3.0.1` is already in Continuum channels, and `3.0.2` is soon going to be :-)
