### ISSUE TITLE
"Spyder update" message box cannot be interacted with

### ISSUE THREAD

**Issue by wlter** [spyder-ide/spyder#3724]
## Description

The "Spyder updates" message box which informs about new versions (currently 3.0.2) cannot be interacted with:
- cannot click the "Release" link
- cannot click the "Installation Instructions" link
- cannot click the "OK" button
- can only close the box with "X"
box will reappear on each restart

**What steps will reproduce the problem?**

1. Restart spyder (with new version available)

**What is the expected output? What do you see instead?**

Interaction should work, or the box chould only appear once at least.

**Please provide any additional information below**

I've had this problem with 3.0.0->3.0.1 before and "solved" it via update.

## Version and main components

* Spyder Version: 3.0.1 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
We're aware of this bug. It was fixed in Spyder 3.0.2 :-)

**Comment by wlter** [comment]
Thanks! :-)

**Comment by edmondja** [comment]
<img width="416" alt="capture d ecran 2017-03-13 a 20 14 24" src="https://cloud.githubusercontent.com/assets/11833428/23871222/c10e78f2-0829-11e7-9bd4-6fb88df3ba8d.png">
<img width="411" alt="capture d ecran 2017-03-13 a 20 14 33" src="https://cloud.githubusercontent.com/assets/11833428/23871223/c1231c3a-0829-11e7-8b91-7b5f454b65e0.png">

No !

**Comment by ccordoba12** [comment]
The message is quite clear: you need to install Jedi 0.9 because 0.10 is still not supported

**Comment by edmondja** [comment]
Yes yes , my bad !

**Comment by ccordoba12** [comment]
Sorry, I posted my response after you deleted your last message. I didn't want to be obnoxious :-p

**Comment by edmondja** [comment]
Lol no problem, thats what i have understood :) (at least you help people quickly !)
