### ISSUE TITLE
Problem displaying high res with spyder 3.0.2

### ISSUE THREAD

**Issue by bfovez** [spyder-ide/spyder#3728]
Spyder 3.0.2 does not display properly on high res screen. Like using Qt4. I downgraded to 3.0.1 in order to use it comfortably.

## Version and main components

* Spyder Version: 3.0.1 
* Python Version: 2.7.12
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
We disabled by default because of many complaints. But you can enable it in

    Preferences > General > Enable high DPI scaling
