### ISSUE TITLE
Define tabulation width in term of spaces instead of pixels

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#3729]
In PR #3663 I assume that tabulation width will be always 4 spaces, and indentation could look wrong depending of `tab_stop_width` value,  I think this could be improved defining it in spaces instead of pixels

I suggest:

- change:   
/config/main.py
`
'tab_stop_width': 40,
`
to
`
'tab_stop_width_spaces': 4,`

- use tab_stop_width_spaces in `fix_indent` calculations

- and set tab stop using space width
`
self.setTabStopWidth('tab_stop_width_spaces * self.editor.fontMetrics().width(' '))
`

**Comment by ccordoba12** [comment]
Please don't forget to reference the issues you open from your PRs :-)

**Comment by rlaverde** [comment]
@ccordoba12 It's ok to do this change? any suggestions? I'll work on it

**Comment by ccordoba12** [comment]
Yeah, please go for it! I haven't touched our support for tabs in a long time, so it'd be really nice to improve it (given that we already offer it :-)
