### ISSUE TITLE
[warn] kq_init: detected broken kqueue

### ISSUE THREAD

**Issue by lxkain** [spyder-ide/spyder#3730]
## Description of your problem

**What steps will reproduce the problem?**

1. Start 3.0.2 on OSX from the terminal
2. 
3. 

**What is the expected output? What do you see instead?**
Expected silent startup. Instead I see:
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Please provide any additional information below**
Obviously this is a very minor issue, and I'm only reporting it here in case it points to another more serious problem. Thank you for a great project!

## Versions and main components

* Spyder Version:
* Python Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Could you run in a terminal

    export EVENT_NOKQUEUE=1

and try again?

**Comment by lxkain** [comment]
That fixes it, yes.

**Comment by ccordoba12** [comment]
I took that from here: https://github.com/tmux/tmux/issues/475#issuecomment-231527324

It seems you need to update libevent to fix those errors :-)

**Comment by lxkain** [comment]
OK, seems like it's harmless, thanks for the background.

**Comment by ccordoba12** [comment]
No prob :-)

**Comment by CoderCoderCoder** [comment]
Fixed by "brew reinstall libevent"

**Comment by themanutdmaniac** [comment]
@ccordoba12 
the same issue crops up even though i followed all your steps...:(

**Comment by themanutdmaniac** [comment]
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by petersgiles** [comment]
@goanpeca closed my issue referring me here
 see (https://github.com/ContinuumIO/anaconda-issues/issues/4535) for my System information

--- 
@themanutdmaniac I am having the same experience.

I typed this in the terminal and it didn't change anything

```
export EVENT_NOKQUEUE=1
```

also did these based on reading other related issues

```
brew update
brew reinstall libevent
brew install --HEAD tmux
```

but no change

**Comment by ccordoba12** [comment]
The warning is harmless. Please ignore it.

**Comment by amendelo** [comment]
same issue as others.  Hopefully they have an anaconda update that fixes this issue. 

I tried typing "export EVENT_NOKQUEUE=1" into terminal when i clicked terminal via Anaconda's environment. While this issue is harmless, it is quite common and annoying that you get this error every time python loads.

**Comment by Neven47** [comment]
Thank you, it fixed it.

**Comment by ghltshubh** [comment]
Though harmless it is still irritating. And I am getting 
`Failed to compute left/right minimum bearings for "GB18030 Bitmap"`
along with it afterwards. Can't find it's permanent solution.

**Comment by x-R4y** [comment]
`export EVENT_NOKQUEUE=1` did not work for me either. 
Neither did libevent reinstallation, update or anaconda reinstallation.. 
is there anything left to try? 
Also, does the error cause any substantial dysfunction or can it be disregarded?

**Comment by mabovo** [comment]
Thank you, it fixed it.
