### ISSUE TITLE
QUESTION - install packages into spyder.app (spyder-3.0.2-py3.5.dmg)

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder#3734]
## Description of your problem

In spyder.app accquired from spyder-3.0.2-py3.5.dmg, is it possible to install new packages, for example pandas? If yes, how to do it? Below are outputs when I tried executing command inside Ipython panel.
``
In[7]: !pip install pandas
/bin/sh: /usr/local/bin/pip: /Applications/Spyder-Py2.app/Contents/MacOS/python: bad interpreter: No such file or directory
``
Thank you.
## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5
* Operating system: Mac
* Mac DMG distribution

**Comment by ccordoba12** [comment]
Some things about your question:

1. No, it's not possible to install new packages in our Mac app.
2. Pandas comes with the app.
3. You can use the app with packages installed in a different Python interpreter. You can select a new interpreter in `Preferences > Main interpreter`
