### ISSUE TITLE
crashes on start via RDP [solution!]

### ISSUE THREAD

**Issue by swharden** [spyder-ide/spyder#3736]
## Description of your problem

**What steps will reproduce the problem?**

1. install plain python 3.5.2
2. `pip install pyqt5 spyder`
* spyder launches fine locally
* spyder will not launch over remote desktop

**What is the expected output? What do you see instead?**
* Over remote desktop, spyder crashes with the error at the bottom of the page.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5.2
* Operating system: Windows 10

![image](https://cloud.githubusercontent.com/assets/4165489/20584047/052e36b2-b1bd-11e6-8f26-9f7c8899a2fc.png)

**Comment by swharden** [comment]
Looks like this is identical to https://github.com/spyder-ide/spyder/issues/3332

**Comment by swharden** [comment]
Also happens in winpython-64-3.5.2.3Qt5
Similar to issue https://github.com/winpython/winpython/issues/427

**Comment by swharden** [comment]
HINT TOWARD FIX: The same version of spyder works fine over remote desktop when I use the [anaconda distribution](https://www.continuum.io/downloads). Maybe a person more savvy than me can compare the two libraries. According to `pip list` it doesn't seem Qt was installed with pip.

**Comment by swharden** [comment]
# RESOLVED!
1. download opengl32sw.dll from [the QT downloads page](http://download.qt.io/development_releases/prebuilt/llvmpipe/windows/)
2. place it in `C:\Program Files\Python35\Lib\site-packages\PyQt5\Qt\bin`

I can now load spyder in windows 10 through remote desktop using a generic python installation after pip installing pyqt5 and spyder.

**Comment by swharden** [comment]
I guess it's still not "resolved" until the developers allow this to happen automatically upon install...

**Comment by ccordoba12** [comment]
This is a problem with the PyQt5 wheels, not our problem because we really can't do anything about it. 

As you said, you have to install `opengl32sw.dll` in `C:\Program Files\Python35\Lib\site-packages\PyQt5\Qt\bin`, and that's a directory owned by PyQt5, not Spyder.

**Comment by djconly85** [comment]
Not sure if this should be opened as a separate issue, but when I remote log-in and try to launch Spyder, I get the message "LoadLibrary failed with error 126: The module could not be found”.

I tried @swharden's steps of downloading opengl32sw.dll and placing it in ~\Lib\site-packages\PyQt5\Qt\bin, but in my PyQt5 folder I do not see the "Qt" subfolder.

I tried placing the DLL directly in the PyQt5 folder, but that did not fix an issue.

FYI, I'm using Spyder 4.1.1 and I do not experience this error when I launch Spyder locally (i.e., not through a remote connection).

A [link to my issue on StackOverflow](https://stackoverflow.com/questions/60859558/error-loadlibrary-failed-with-error-126-the-module-could-not-be-found-when-la) has more information.

**Comment by SilentProwler** [comment]
Since I was unable to get pass LoadLibrary 126 error using the solutions provided online and on here, I stepped back and realized the obvious workaround. The errors occurs when you open the program while you're using a remote session, right? The obvious solution is to launch the program while a remote session is not in progress. To do this while you're remoting, you should create a batch script to launch the program but make sure to include a time delay before that (I used 'timeout 10 /nobreak' to do so). Run the batch script and, before your program launchs, disconnect from RDP. After enough time passes for the program to launch, you can reconnect to RDP and your program will be up and ready.
