### ISSUE TITLE
Spyder still won't launch after installing anaconda2, Qt missing?

### ISSUE THREAD

**Issue by Tuzi12** [spyder-ide/spyder#3740]
Try to launch spyder through anaconda prompt, error occurs:

**(C:\Program Files (x86)\Anaconda2) C:\Users\...>spyder
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.**

* Spyder Version:
* Python Version: 2.7
* Operating system: windows 10

I did not know Spyder version comes with anaconda2

**Comment by Tuzi12** [comment]
just checked that spyder version is 3.0.0

**Comment by ccordoba12** [comment]
Please run this in a terminal

    qmake -query

and post the output here

**Comment by Tuzi12** [comment]
@ccordoba12 The result as below after ran the query: 


Microsoft Windows [Version 10.0.14393]

C:\Program Files (x86)\Anaconda2>qmake -query
QT_SYSROOT:
QT_INSTALL_PREFIX:C:/Users/ray/qt5-x86-2.7/envs/_build/Library
QT_INSTALL_ARCHDATA:C:/Users/ray/qt5-x86-2.7/envs/_build/Library
QT_INSTALL_DATA:C:/Users/ray/qt5-x86-2.7/envs/_build/Library
QT_INSTALL_DOCS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/doc
QT_INSTALL_HEADERS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/include/qt
QT_INSTALL_LIBS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/lib
QT_INSTALL_LIBEXECS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/bin
QT_INSTALL_BINS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/bin
QT_INSTALL_TESTS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/tests
QT_INSTALL_PLUGINS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/plugins
QT_INSTALL_IMPORTS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/imports
QT_INSTALL_QML:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/qml
QT_INSTALL_TRANSLATIONS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/translations
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/examples
QT_INSTALL_DEMOS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/examples
QT_HOST_PREFIX:C:/Users/ray/qt5-x86-2.7/envs/_build/Library
QT_HOST_DATA:C:/Users/ray/qt5-x86-2.7/envs/_build/Library
QT_HOST_BINS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/bin
QT_HOST_LIBS:C:/Users/ray/qt5-x86-2.7/envs/_build/Library/lib
QMAKE_SPEC:win32-msvc2008
QMAKE_XSPEC:win32-msvc2008
QMAKE_VERSION:3.0
QT_VERSION:5.6.0

**Comment by Tuzi12** [comment]
@ccordoba12  After I installed Anaconda2, there is no shortcut or navigator in the start menu, I searched around and added a bat file for those shortcuts to appear. bat file contains three lines:

"C:\Program Files (x86)\Anaconda2\pythonw.exe" -E -s "C:\Program Files (x86)\Anaconda2\Lib\_nsis.py" addpath
"C:\Program Files (x86)\Anaconda2\pythonw.exe" -E -s "C:\Program Files (x86)\Anaconda2\Lib\_nsis.py" mkdirs
"C:\Program Files (x86)\Anaconda2\pythonw.exe" -E -s "C:\Program Files (x86)\Anaconda2\Lib\_nsis.py" mkmenus

**Comment by Tuzi12** [comment]
C:\Program Files (x86)\Anaconda2>conda --version
conda 4.2.9

C:\Program Files (x86)\Anaconda2>conda update conda
PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in C:\Program Files (x86)\Anaconda2

**I searched for the solution, someone said to run conda update -all** but mine says conda package is not installed, what's the matter? I certainly can check the version. Really confusing..

**Comment by ccordoba12** [comment]
Please uninstall your previous Anaconda and install it again just your user (instead of for all users). That should fix your problem.

**Comment by Tuzi12** [comment]
@ccordoba12  I uninstalled everything and cleared the path related to Python 2 & 3, reinstall Anaconda3 (cos I thought the issue might be the previous python2 comes with the pythonXY, so I installed python3 instead this time), selected ONLY ME as the user. But the problem still persists: 

 **Failed to start because it could not find or load the Qt platform plugin "windows" in ""**

this time, i can do the ' conda update --all ' , but nothing fixed it :(
my current conda info as below: 

Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : C:\Users\JJJ\Anaconda3  (writable)
    default environment : C:\Users\JJJ\Anaconda3
       envs directories : C:\Users\JJJ\Anaconda3\envs
          package cache : C:\Users\JJJJ\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

Noticed the config file is None, should this be a problem?

**Comment by Tuzi12** [comment]
since I am already moved to Python3, i think i will give Winpython a go to see whether it works.

**Comment by ccordoba12** [comment]
Could you post again the output of

    qmake -query

? Thanks.

**Comment by Tuzi12** [comment]
@ccordoba12  I installed Winpython and there is no problem to open the spyder. Since it is the spyder that I want to use, I will stick to Winpython for the time being. 

Thank you very much for your time and help.

**Comment by ccordoba12** [comment]
Ok, glad you were able to solve your problems :-)

**Comment by dbowmans46** [comment]
I know this issue is closed, but I had a similar problem with Anaconda 3, version 4.3.8 on Windows 7 x64.  

I was able to solve the problem by creating an environment variable named `QT_QPA_PLATFORM_PLUGIN_PATH` to the path `.\Anaconda3\Library\plugins\platforms\` .

**Comment by juandpineiro** [comment]
Thanks dbowmans46. That worked for me.

**Comment by pabloazurduy** [comment]
awsome  @dbowmans46  I was using spyder in windows server, and I ran into the same problem. Thanks !!

**Comment by abk7251** [comment]
Hello 
i DID everything stated above set  QT_QPA_PLATFORM_PLUGIN_PATH   to  path .\Anaconda3\Library\plugins\platforms.  
Now this error is showing.Please help
![image](https://user-images.githubusercontent.com/10489891/29933845-b682bc4c-8e96-11e7-819f-5d56d9732d8e.png)

**Comment by SadeghNK** [comment]
I got this issue after installing spyder-terminal plugin for spyder using `pip install spyder-terminal`.
the environment variable `QT_PLUGIN_PATH` was already in my system variables, pointing to `.\Anaconda3\Library\plugins\`
I just changed it to `.\Anaconda3\Library\plugins\platforms\` , and spyder is working again and the pluging is also installed.

**Comment by rafi138** [comment]
After use this command "conda update conda" on anaconda prompt , this problem had been solved . I noticed that it also try to fix the variable path
