### ISSUE TITLE
Kernel console/window  disappeared！

### ISSUE THREAD

**Issue by Euniceu** [spyder-ide/spyder#3743]
## Description of your problem

**What steps will reproduce the problem?**

1. I update Spyder from 2* to 3*, I found the Kernel window usually next to the Python 1 window is disappeared. 

**What is the expected output? What do you see instead?**
How can I find it back ?

**Please provide any additional information below**
![image](https://cloud.githubusercontent.com/assets/17468922/20612847/38923e44-b2f9-11e6-99a7-8b989b6f1797.png)

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: Win 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
It won't come back, sorry. We removed kernels as Python consoles in order to make IPython consoles more stable and robust.

The previous way to start kernels was really brittle and so prone to failure.

**Comment by Euniceu** [comment]
But there is something wrong with it, or maybe I hasn't used to it. 
The "print" results is shown in Kernel window before, but now I can not watch the results the code printed out. Where should I find the showing setting?

**Comment by ccordoba12** [comment]
Please post the code that's not working for you now.

**Comment by Euniceu** [comment]
` print ('... building the model')`
All the print code is not showing up in process.
