### ISSUE TITLE
IPython console missing

### ISSUE THREAD

**Issue by TheTinka** [spyder-ide/spyder#3744]
Hello,
since I have updated my sypmy yesterday the IPython console is missing. I'm neither able to choose it in the menu.
I tried to update IPython and qtconsoles

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5
* Operating system: Windows 7

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.0.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)

Thanks in advance.

**Comment by ccordoba12** [comment]
It's probably hidden. Please go to

    View > Panes

to see if it's there or not.

**Comment by TheTinka** [comment]
Unfortunatly not...
![spyder](https://cloud.githubusercontent.com/assets/22595315/20631118/52b71dda-b335-11e6-9c1e-29a09d355f5b.PNG)

**Comment by ccordoba12** [comment]
Please go to

    Help > Dependencies

and post a screenshot with the contents of our Dependencies dialog.

**Comment by TheTinka** [comment]
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.0.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)

**Comment by ccordoba12** [comment]
Please be sure to also install pyzmq and pygments.

**Comment by TheTinka** [comment]
The installation stops at this point (see attachement). It just doesn't do anything
![spyder](https://cloud.githubusercontent.com/assets/22595315/20635021/b8547774-b357-11e6-99ec-a461a0431034.PNG)

**Comment by ccordoba12** [comment]
I don't understand what happens, but this is really a problem in your system and not with Spyder :-/

**Comment by TheTinka** [comment]
okay... then I have a lot of problems.. 
Thank you anyway.

**Comment by ccordoba12** [comment]
Ok, good luck with that.
