### ISSUE TITLE
Cannot interact with update prompt

### ISSUE THREAD

**Issue by salvioner** [spyder-ide/spyder#3745]
Upon opening Spyder v3.0.1 i am prompted a small window which tells that v3.0.2 is available. When i click on the download link nothing happens. When i click on the "OK" button i get no reaction too. The only way to close the window is with the "X" close button of Windows

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 
`Python 2.7.12 |Anaconda custom (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v
.1500 64 bit (AMD64)] on win32`
* Operating system: Windows 8.1 64bit

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Sorry about this annoying problem. It was fixed in 3.0.2 (so after you update to that version, you won't see this problem again :-).
