### ISSUE TITLE
Menu view/toolbar has empty contents

### ISSUE THREAD

**Issue by ahed87** [spyder-ide/spyder#3746]
on my installs with spyder 3.0.1 and 3.0.2 the menuoption for toolbars is not showing.

the installs are fresh anaconda installs on windows 64-bit, and then an upgrade of spyder.
I think it worked with the 3.0.0, since I did change the toolbars on one computer,
but that is no longer possible.

did not directly find this mentioned anywhere - if it is a duplicate just close.

**Comment by ccordoba12** [comment]
This is right. I don't know what happened with that menu.

@dalthviz, please solve this one.

**Comment by ahed87** [comment]
just tried to paste the added code into my qthelpers.py,
and the menu content was back.
Thanks!!
