### ISSUE TITLE
Bad window size in spyder.ini prevents Spyder from showing

### ISSUE THREAD

**Issue by swharden** [spyder-ide/spyder#3748]
## Description of your problem

**What steps will reproduce the problem?**

1. enable dual monitors. move spyder to the right monitor. exit spyder.
2. disable the right monitor. (or connect over remote desktop)
3. load spyder.
- _alternatively, just edit your .spyder-py3/spyder.ini and `set window/position = (4134, 197)`_

**What is the expected output? What do you see instead?**
I expect to see spyder, but the window cannot be seen anywhere on the screen.

## Poor fix:
`I could spyder --reset`, but that loses lots of settings I spent a long time to set up.

## Best FIX (a developer should do this):
The last used window position is stored in my user folder /.spyder-py3/spyder.ini
Set the window position to a sane x,y pair like (100,100):
`window/position = (100, 100)`
It would be great if spyder could detect the width of the desktop, and if the window position X is greater than this width it decreases the number to compensate.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5.2
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this for Spyder 3.1.

@dalthviz, please work on this one.

**Comment by dalthviz** [comment]
Hi @swharden as you are using Windows, for now, you can try to use the snapping shortcuts of Windows to work around the problem. Having Spyder as your current window use `Windows Key + left arrow` or `Windows Key + right arrow`. This will help you to find the main window of Spyder.
