### ISSUE TITLE
Problem when we try to read csv files

### ISSUE THREAD

**Issue by saikrishnaanudeep** [spyder-ide/spyder#3751]
## Description of your problem

**What steps will reproduce the problem?**

1. when tried to read a csv file using pandas
2. while initiating it shows multiple times that kernel is died, then it starts after some time
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:latest
* Python Version:2.7
* Operating system:windows 10
![spyder issue](https://cloud.githubusercontent.com/assets/24197018/20644930/7483e1c2-b417-11e6-8bac-e47f7cfd9a10.jpg)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting this problem. Please post the file you're trying to read from somewhere, so we can take a look at it :-)

**Comment by saikrishnaanudeep** [comment]
hii,

I'm attaching the file I'm trying to read and the picture of the error I'm
getting. It read the file once, I'm facing the problem when i tried to do
it again. I think there is a problem with some lines of code in spyder.
Thanks in advance.

Regards,
Krishna

**Comment by ccordoba12** [comment]
That's not possible via email. You need to upload it somewhere on the Internet.

**Comment by saikrishnaanudeep** [comment]
This forum isn't allowing csv files to be attached. I'm attaching the picture of the error I'm getting. It read the file once, I'm facing the problem when i tried to do it again. I think there is a problem with some lines of code in spyder. Thanks in advance.
![spyder issue](https://cloud.githubusercontent.com/assets/24197018/20656868/dd362fbc-b4fe-11e6-8301-128a6750cca3.jpg)

**Comment by ccordoba12** [comment]
I'm afraid this image is not enough to address your problem (besides, you already posted it above). We need the file you're trying to read to understand what happens with it.

**Comment by saikrishnaanudeep** [comment]
Since I couldn't attach csv files here, I'm compressing it into a zip file and attaching. Please, unzip to see actual file. Thank you.
[axisbank.zip](https://github.com/spyder-ide/spyder/files/615438/axisbank.zip)

**Comment by goanpeca** [comment]
After 3 year and python 2.7 support coming to an end soon, this is probably not relevant anymore. Closing.
