### ISSUE TITLE
Redefined hotkeys are not displayed in menu

### ISSUE THREAD

**Issue by sergiokapone** [spyder-ide/spyder#3755]
## Description of your problem
Redefined hotkeys are not displayed in menu

**What steps will reproduce the problem?**

1. Redefine 'Transform to lowercase' ('Transform to uppercse' ) from default to say 'ctrl + [' ('ctrl + ]' ).
2. Apply new hotkeys
3. In the menu I see again default hotkeys, but functionality assigned to new hotkeys

**What is the expected output? What do you see instead?**

In menu I want to see new assignements for hotkeys

**Please provide any additional information below**

---
## Versions and main components

* Spyder Version: 3.0.2
* Python Version: python-3.6.0b4.amd64 (with WinPython distribution)
* Operating system: Win10, 1607, 14393.447

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please take a look at what's happening here.
