### ISSUE TITLE
Variable explorer should show variables of type pandas.indexes.base.Index

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#3758]
Define a variable via

```
import pandas
dfi = pandas.DataFrame([[1, 2]], columns=['A','B']).columns
```

Now `dfi` should be displayed in the variable explorer.

I am currently using WinPython-64bit-3.5.2.3 with Spyder 3.1.0.dev0 and Pandas 0.19.1.

**Comment by ccordoba12** [comment]
It's possible to convert Index'es to Numpy arrays and show them using our Array viewer.

We'll work on it for Spyder 3.2 :-)

**Comment by jondo** [comment]
*thumbs up*
