### ISSUE TITLE
How to install Spyder to a directory and make it portable?

### ISSUE THREAD

**Issue by fusion809** [spyder-ide/spyder#3767]
Hi,

I'd like to make a portable distribution of Spyder for Linux. Specifically I'd like to install Spyder to `/AppDir/usr`. I've run `python setup.py install --prefix=/AppDir/usr` but when I move this directory elsewhere it fails to launch as it is using absolute paths (as opposed to relative paths). Is there a way to compile Spyder so that it will use relative paths as opposed to absolute paths and hence be portable? 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I have asked a question at [StackOverflow](http://stackoverflow.com/questions/40880324/how-does-one-get-python-setup-py-install-to-use-relative-paths-when-it-comes-to) to this effect.

**Comment by ccordoba12** [comment]
Sorry, we haven't consider nor we are interested in this possibility.
