### ISSUE TITLE
Spyder 3.0.2 upgrade via pip in Windows 10 not working

### ISSUE THREAD

**Issue by cwhanse** [spyder-ide/spyder#3769]
Attempted to upgrade to Spyder 3.0.2 from 3.0.0 using

pip install --update spyder

pip runs to completion without error, but spyder 3.0.0 continues to launch even after resetting Spyder settings and rebooting.

I successfully upgraded to Spyder 3.0.2 using

conda update qt pyqt
conda update spyder

After resetting Spyder settings and rebooting, Spyder 3.0.2 launches.

python 2.7.10
conda 4.2.0
Spyder 3.0.0 installed by current anaconda2-4.2.0 distribution

**Comment by ccordoba12** [comment]
Did you use pip within conda?

**Comment by cwhanse** [comment]
Not sure I understand your question.  I use pip from the command line provided by opening the Anaconda Prompt console window.  That console runs .../Anaconda2/scripts/activate.bat when it opens.

**Comment by ccordoba12** [comment]
Please don't mix pip and conda packages. I think you broke your Anaconda installation by doing it.

Please reinstall Anaconda, and update Spyder with

    conda update spyder

**Comment by pawarpooja** [comment]
Hello @ccordoba12 , sir I tried to install pillow using conda and it shows that the packages are already installed
![img](https://user-images.githubusercontent.com/29332279/34476225-d5ca8be6-efb4-11e7-8c07-08301c7b554d.png)
But when I run the import pil  command, it is giving an error message.
Also spyder is not allowing to update packages using pip..
Can you please tell me the solution if possible?

**Comment by dbEst88** [comment]
for some reason my channels got mixed up and i cant use the conda command anymore, I have to use pip, somewhere in the conda config info there is an option to use pip that you can set to true or false, but the spyder update with pip is 
pip install --upgrade spyder

**Comment by dbEst88** [comment]
yea, I just ran it, was operating with spyder4 and now it runs spyder5
pip install --upgrade spyder
