### ISSUE TITLE
Error when hit 'run file' button in debug mode

### ISSUE THREAD

**Issue by luciansmith** [spyder-ide/spyder#3771]
## Description of your problem

I usually run things in Spyder so that it goes into debug mode when it hits a snag.  Often, after I find and fix the problem, I'll then hit the nice green 'run file' button.  Nothing happens.  Then I remember I'm in debug mode, hit the blue square 'Stop Debugging' button, and I'm immediately taken to the regular Python console to be told there's an error.  Going back to the iPython window shows the 'runfile' line, and if I hit 'return', it will then execute that line and run the file.

**What steps will reproduce the problem?**
Enter this program into the editor window:

```python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 20 15:02:52 2016

@author: lpsmith
"""

import numpy
numpy.doesnotexist()
```

Hit the green 'run file' button with an active IPython window open.  Say that you want it to enter debugging mode if it encounters an error.  Something like the following shows up in the IPython window:

```
runfile('/Users/lpsmith/test.py', wdir='/Users/lpsmith', post_mortem=True)
****************************************
Entering post mortem debugging...
****************************************
> /Users/lpsmith/test.py(10)<module>()
      6 @author: lpsmith
      7 """
      8 
      9 import numpy
---> 10 numpy.doesnotexist()


ipdb> 
```

Now edit the file or imagine you've edited the file and hit the 'run file' button again.  Nothing happens.  Also, you can no longer type anything into the IPython window.

Now hit the square 'stop debugging' button.  You'll be taken to the regular console window with errors like the following:

```python-traceback
Traceback (most recent call last):
  File "/Applications/anaconda/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/Applications/anaconda/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 180, in _handle_execute_reply
    exec_count = msg['content']['execution_count']
KeyError: 'execution_count'
```

You can ignore those errors and switch back to the IPython window, where you'll see:

runfile('/Users/lpsmith/test.py', wdir='/Users/lpsmith', post_mortem=True)

with the cursor waiting at the end of the line.  You can hit 'return' and it'll run the file.

**What is the expected output? What do you see instead?**

What would be nice is if hitting the 'run file' button did some sort of 'continue' in debug mode.  But barring that, I would like a normal error message somewhere, instead of freezing the IPython console.

**Please provide any additional information below**

## Versions and main components

Spyder verson 3.0.2 (and earlier), Python 2.7, MacOS 10.11.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting and for detailed information about how to reproduce this bug.

@mariacamilaremolinagutierrez, please work on this one.

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, I moved this one to 3.2
