### ISSUE TITLE
"Kernel died, restarting..." repeats when I open the Spyder.

### ISSUE THREAD

**Issue by SunYiLun** [spyder-ide/spyder#3773]
## Description of your problem

**What steps will reproduce the problem?**

1. "Kernel died, restarting..." repeats many times until it runs properly
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:spyder3.0.1
* Python Version:python2.7
* Operating system:win7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.0.2. Please update to that version to get the fix :-)

**Comment by SunYiLun** [comment]
Thank you, it works :-)
