### ISSUE TITLE
Wrong Output

### ISSUE THREAD

**Issue by tanmaythakar4** [spyder-ide/spyder#3782]
## Description of your problem
I delete some printing statement from my project .still the kernel is printing those statement.

**What steps will reproduce the problem?**

1.  
2. 
3. 

**What is the expected output? What do you see instead?**
It should not print these statement .

**Please provide any additional information below**

## Versions and main components

* Spyder Version: spyder 3.0.0
* Python Version: 3.5 
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
There's too little for us to help you, but probably the problem is caused because you haven't reevaluated your code.

Just press F5 to do it :-)
