### ISSUE TITLE
Create new windows when undocking all plugins

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#3790]
There are two improvements I'd like to see for new Editor windows

1. Make their toolbar to be exactly the same as the one present in the main window (except for the working directory toolbar, which we don't need to show in new windows).
2. When the Editor plugin is undocked, we must close it and show a new window instead. For that we need to connect a new method to the topLevelChanged signal of its QDockWidget:

    http://doc.qt.io/qt-4.8/qdockwidget.html#topLevelChanged

@dalthviz, please work on this in two different PRs. Please start with point 1. which is easier, and then move to 2.

**Comment by silentquasar** [comment]
I look forward to this as I'd like to split my screen between a web page and the Spyder editor without the rest of the gui using up space. Thanks for working on it!
