### ISSUE TITLE
Using spyder or ipython from a different user account gives permission errors

### ISSUE THREAD

**Issue by sprague252** [spyder-ide/spyder#3792]
## Description of your problem

**What steps will reproduce the problem?**

1. Install anaconda (mine was on a mac). I installed in /Applications so it would be available to all users.
2. Execute spyder or ipython from a different username than the installed account
3. There is a crash due to permission errors.

**What is the expected output? What do you see instead?**
Spyder or ipython crashes with permission errors.

**Please provide any additional information below**

I fixed this issue with the following commands:

chmod go+r anaconda/lib/python2.7/site-packages/numba-0.28.1+0.gfe99fbc.dirty-py2.7-macosx-10.6-x86_64.egg-info/*

chmod go+r anaconda/lib/python2.7/site-packages/llvmlite-0.13.0-py2.7.egg-info/*

Please note that these chmod commands must be run from the directory containing the anaconda directory by the owner of the anaconda directory (and subdirectories).  Also note that on my computer the owner was root:wheel, so I ran the chmod commands with sudo.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: Python 2.7.12 :: Anaconda custom (x86_64)
* Operating system: Mac OS X version 10.11.6 (15G1108)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for letting us know about it, but the problem is present in Numba and LLVMLite, so they're not related to Spyder, and we can't do anything to fix it.

**Comment by sprague252** [comment]
It might be nice to post instructions for a work-around.  I appreciate all your work on spyder.  It is a great product!

-Mark
