### ISSUE TITLE
netCDF4 does not function in Spyder (Windows)

### ISSUE THREAD

**Issue by Linimie** [spyder-ide/spyder#3797]
When trying to import netCDF4 in spyder, it does not function. I have managed to fix the h5py issue myself but than other error messages appear: 

_import netCDF4
Traceback (most recent call last):

  File "<ipython-input-8-f731da2de255>", line 1, in <module>
    import netCDF4

  File "C:\Python27\lib\site-packages\netCDF4\__init__.py", line 5, in <module>
    from ._netCDF4 import __doc__, __pdoc__

ImportError: cannot import name __pdoc__

import pdoc

import netCDF4
Traceback (most recent call last):

  File "<ipython-input-10-f731da2de255>", line 1, in <module>
    import netCDF4

  File "C:\Python27\lib\site-packages\netCDF4\__init__.py", line 5, in <module>
    from ._netCDF4 import __doc__, __pdoc__

ImportError: cannot import name __pdoc___

This causes me to be unable to work with NC files locally and that is a big issue for my research.
I have Spyder 2.3.5.2 and Python2.7.10 32bits on windows 10(home edition)
For hours I have tried to google for a solution but I cannot find anything the actually solves this problem

Could somebody please help me out?

Dependencies:
IPython >=1.0   :  2.4.1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
sympy >=0.7.3   :  1.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

**Comment by ccordoba12** [comment]
This seems an installation problem with netCDF4, so it's not related to Spyder.

How did you install netCDF4?

**Comment by Linimie** [comment]
through easy_install netCDF4 in my windows shell. I have also tried pip install netCDF4 after uinstalling the previous version through easy_install, but the same problems occur

**Comment by ccordoba12** [comment]
I'm sorry but we can't help you with this because the problem is not related to Spyder.

I'd recommend you to install the Anaconda Python distribution and try again.
