### ISSUE TITLE
Spyder Update dialog broken links, OK button doesn't work

### ISSUE THREAD

**Issue by ijstokes** [spyder-ide/spyder#3799]
## Description of your problem

<img width="419" alt="screen shot 2016-12-07 at 1 23 17 pm" src="https://cloud.githubusercontent.com/assets/293525/20980917/85120f52-bc80-11e6-88cf-f18829f23217.png">

None of the links work and I can't dismiss the dialog with the OK button.  Only the "close window" red button in the top left will get rid of it.

**What steps will reproduce the problem?**

1. Anaconda 4.2
2. Spyder 3 started from the command line

**What is the expected output? What do you see instead?**

Links should open in browser
OK button should dismiss dialog

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: Python 2.7
* Operating system: OS X 10.11.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Hey @ijstokes, thanks for reporting. This problem was fixed in Spyder 3.0.2, so please update to that version to get the fix.
