### ISSUE TITLE
Spyder does not use the virtual environment interperter

### ISSUE THREAD

**Issue by bloodymeli** [spyder-ide/spyder#3816]
## Description of your problem

**What steps will reproduce the problem?**

1. activate the virtual enviroment "workon cv" for opencv
2. I start spyder from the command line "spyder"
3.  write "import cv2"

**What is the expected output? What do you see instead?**
I get an error "ImportError: No module named cv2".
When I type python in the command line of the cv environment (after step 1) the import command complete successfully. Furthermore, when I manually point spyder to the right binary file in the /.virtualenv/cv/... folder, it correctly loads the module using "import cv2".

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.02
* Python Version: 2.7
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.0 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
You have two options:

1. Change the interpreter used for Spyder consoles to point to your virtualenv Python executable in `Preferences > Python interpreter`
2. Install Spyder in your virtualenv and start it from there.

We recommend option 1. because it's easier to apply :-)

**Comment by bloodymeli** [comment]
Thanks for the prompt response.
I was under the impression that if I start spyder in the virtual
environment than it correctly loads the corresponding python and modules.
It actually worked this way for a little while.
(see also:
http://stackoverflow.com/questions/30170468/how-to-run-spyder-in-virtual-environment).
Does spyder supports such command line loading in the virtual environments?
Is there a way to avoid the necessary restart of spyder  any time after
changing the interpreter?

Best,
Eli

**Comment by ccordoba12** [comment]
> I was under the impression that if I start spyder in the virtual environment than it correctly loads the corresponding python and modules.

Yes, it does, as long as your interpreter in `Preferences > Python interpreter` is the default one.

**Comment by bloodymeli** [comment]
Hi,

Well, I guess this is the issue I'm trying to report:
The interpreter is set as described. Spyder is activated from the command
line when the relevant virtual  environment is activated.  However, the
system interpreter is user rather than the environment interpreter.


On 10 Dec 2016 01:29, "Carlos Cordoba" <notifications@github.com> wrote:

I was under the impression that if I start spyder in the virtual
environment than it correctly loads the corresponding python and modules.

Yes, it does, as long as your interpreter in Preferences > Python
interpreter is the default one.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spyder-ide/spyder/issues/3816#issuecomment-266151591>,
or mute the thread
