### ISSUE TITLE
F1 shortcut is hard-coded

### ISSUE THREAD

**Issue by luwei0917** [spyder-ide/spyder#3818]
## Description of your problem
Instead binding to Spyder documentation, I want to bind F1 to run.

**What steps will reproduce the problem?**

1. open keyboard shortcuts
2. rind run, bind to F1, apply, Ok.
3. restart

**What is the expected output? What do you see instead?**
Expected F1= run.
see F1= Spyder documentation. 

**Please provide any additional information below**

## Versions and main components

* Spyder Version:Spyder 3.0.2 
* Python Version:
* Operating system:
Python 3.5.2 64bits, Qt 5.7.0, PyQt5 5.7 on Darwin 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
@andfoy, please work on this one. The idea is to make the F1 shortcut configurable instead of hard-coded in our interface (as it is right now).
