### ISSUE TITLE
Spyder.app can't find ipykernel module in external interpreters

### ISSUE THREAD

**Issue by markobudinich** [spyder-ide/spyder#3819]
## Description of your problem
Short version: 
In Spyder App 3.0.2, changed Python interpreter to /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/python3 and IPython console does not start. ipykernel is installed for this interpreter.

Long version:
I started recently to work with spyder in scientific computing. Until now, I've used mainly Jupyter notebooks / ipython console in MacOSX El Capitan. I have a macport install of python3.5. I installed spyder 2.3.8 using macports but IPython console showed the "shift-enter" issue. I then installed spyder 3.0.1 from macports, but then I had problems with PyQt5 (I have version 5.6 installed). I also tried using pip but I got the same problem.

Finally, I got Spyder.app and changed the interpreter to /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/python3 and IPython console can't connect to kernel. I went to several threads here with similar issues, but as far as I understood, the problem was solved for 3.0.2
 
Any ideas?
Thanks in advance
Marko

**What steps will reproduce the problem?**

1. Install Spyder.app 3.0.2
2. Change Python interpreter to /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/python3

**What is the expected output? What do you see instead?**
When starting from terminal:
Dec 10 14:20:48  Spyder[16298] <Notice>: Traceback (most recent call last):
Dec 10 14:20:48  Spyder[16298] <Notice>:   File "/Applications/Spyder.app/Contents/Resources/lib/python3.5/spyder/utils/ipython/start_kernel.py", line 223, in <module>
Dec 10 14:20:48  Spyder[16298] <Notice>:     main()
Dec 10 14:20:48  Spyder[16298] <Notice>:   File "/Applications/Spyder.app/Contents/Resources/lib/python3.5/spyder/utils/ipython/start_kernel.py", line 196, in main
Dec 10 14:20:48  Spyder[16298] <Notice>:     from ipykernel.kernelapp import IPKernelApp
Dec 10 14:20:48  Spyder[16298] <Notice>: ImportError: No module named 'ipykernel'

**Please provide any additional information below**
ipykernel is installed. From ipython console:

Python 3.5.2 (default, Oct 11 2016, 15:01:29) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import ipykernel

In [2]: ipykernel.version_info
Out[2]: (4, 5, 2)

* Spyder Version: 3.0.2
* Python Version: 3.5.2 (from macports)
* Operating system: OSX

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
But did you have ipykernel installed in your external interpreter, the one in `/opt`?

**Comment by markobudinich** [comment]
Yes, there is:

$ ls /opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/
__init__.py	_version.py	connect.py	embed.py	heartbeat.py	ipkernel.py	kernelbase.py	parentpoller.py	resources	zmqshell.py
__main__.py	codeutil.py	datapub.py	eventloops.py	inprocess	jsonutil.py	kernelspec.py	pickleutil.py	serialize.py
__pycache__	comm		displayhook.py	gui		iostream.py	kernelapp.py	log.py		pylab		tests

From python console in Spyder App:
>>> import ipykernel
>>> ipykernel.version_info
(4, 5, 2)

**Comment by ccordoba12** [comment]
Spyder.app is not maintained anymore, sorry.
