### ISSUE TITLE
sig_new_file error when converting notebook to script

### ISSUE THREAD

**Issue by ReportMort** [spyder-ide/spyder#3823]
## Description

**What steps will reproduce the problem?**

1. Right-Click on an .ipynb file > Click on "Convert To Python Script"

**What is the expected output? What do you see instead?**

I expected to see a .py file generated based on the notebook, but instead received the following error in the internal console:

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\site-packages\spyder\widgets\explorer.py", line 568, in convert_notebooks
    self.convert_notebook(fname)
  File "C:\Program Files\Anaconda2\lib\site-packages\spyder\widgets\explorer.py", line 559, in convert_notebook
    self.parent_widget.sig_new_file.emit(script)
AttributeError: 'Projects' object has no attribute 'sig_new_file'
```

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 2.7.12
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, this is a simple one for you :-)

**Comment by andfoy** [comment]
@ccordoba12 I tried to reproduce the error, but the conversion worked successfully

**Comment by ccordoba12** [comment]
@andfoy, did you do the conversion from the Project explorer instead of the File Explorer?
