### ISSUE TITLE
Improve icons in the File explorer

### ISSUE THREAD

**Issue by thierryBottaro** [spyder-ide/spyder#3825]
Icons in the File explorer aren't anymore populated/updated

**What steps will reproduce the problem?**

1. Fresh install WinPython 3.5.2.3QT5 
2. open Spyder, 
3. activate the File Explorer

I get that : 
![](https://cloud.githubusercontent.com/assets/15816165/20972749/31d1f076-bc96-11e6-90bf-f45f977407d0.png)

but in previous version, I had that (icons are the same as in window explorer)
![](https://cloud.githubusercontent.com/assets/15816165/20972804/60e4a4e4-bc96-11e6-9923-d66c3b191e11.png)

* Spyder Version: 3.1.0.dev0
* Python Version: 3.5
* Operating system: Win 7 enterprise

Winpython maintainer (stonebig) did reproduce the problem, see issue : https://github.com/winpython/winpython/issues/446#issuecomment-266191173

**Comment by ccordoba12** [comment]
Sorry, we decided to unify our theme to display always the same kind of icons instead of taking some from the operating system.

**Comment by thierryBottaro** [comment]
Sorry but that's a bit short !
It would be OK if I get more than 2 icons: one for folder, one for "other".
I had difficulty to understand why I had "file" icon in the middle of my folders... The explanation is that the Symbolic Links to folder has a "file" icon, but is sorted among the folders. Really not intuitive. 
To my point of view, it is a clear regression. 
in engineering, we keep saying : "never change a running system". Previous behaviour was perfect, why change it. Only Spyder developers can appreciate the theme unification

**Comment by ccordoba12** [comment]
Sorry if I was too blunt. We can look at the issue with symbolic links and also at using a wider range of icons to disambiguate file types (but using the icons from the FontAwesome project and not the ones from the operating system).

Please open an issue for each of these problems :-)

**Comment by ImportanceOfBeingErnest** [comment]
I just updated to Spyder 3.1 and found the same strange behaviour of all icons in the file explorer suddenly being the same. 

I find the answer "we decided to unify our theme to display always the same kind of icons instead of taking some from the operating system" pretty unconstructive. Having the same icons as in the operating system is a great feature and from a user's perspective there is absolutely no reason whatsoever to give this up. For the 1% of users who rate visual design higher than usablility one may of course put a different icon theme in, but surely not as default.

So what is the latest version that still has the default system icons in the file explorer, such that I can revert back to it until I've found a less usability-ignorant IDE for python?

**Comment by ccordoba12** [comment]
We're no going to revert to using the operating system icons, sorry. As i said, we plan to use the icons FontAwesome has for different file types.

**Comment by ccordoba12** [comment]
@andfoy, please work on this one using the `file-*-o` icons present in FontAwesome.

**Comment by ccordoba12** [comment]
Also, you need to detect the file type of a symlink and use the right icon for it.

**Comment by ccordoba12** [comment]
@andfoy, please stop what you're doing and focus on solving this issue.

**Comment by thierryBottaro** [comment]
I rapidly read the merge, and I haven't seen anything concerning symlinks.

I still doubt that we might be happy to replace icons user is used to (which we might call "unified theme experience for user") by open-source "unified theme along operating systems for multi-platform programer"...

**Comment by ccordoba12** [comment]
> I rapidly read the merge, and I haven't seen anything concerning symlinks.

We verified that symlinks have the same icon as the file the point to, as long as they preserve extensions.

> I still doubt that we might be happy to replace icons user is used to

We're following the lead of other IDEs and editors in this regard (e.g. Sublime and VSCode). Besides, we want to be able to control the color and appearance of these icons to easily define completely dark themes (something we're working on for Spyder 4).
