### ISSUE TITLE
Add a command line option to load projects

### ISSUE THREAD

**Issue by eendebakpt** [spyder-ide/spyder#3830]
Is there an option to load a specific project with command line options? Or, alternatively, specify a  different set of configuration files? The reason is that we are working with multiple users on the same account, and we do not want to have our projects and settings mixed.

We already have different spyder versions installed using environments (with conda, windows), but these different spyder versions all use the same configuration files.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5
* Operating system: windows

**Comment by ccordoba12** [comment]
We could easily add an command line option to load a different project, but I'm a bit reluctant to add another one to load different config settings.

Why is not possible for you to let your users use different accounts?

**Comment by eendebakpt** [comment]
The reason is that there are several instruments (hardware) connected to the machine and we do not want to disconnect these instruments. Logging out and into a different account would disconnect the hardware. 
A command line option to load a specific project would be great. If needed I can look into the code myself, but I am not very familiar with the spyder codebase.

**Comment by ccordoba12** [comment]
@andfoy, please work on this one.

**Comment by arita37** [comment]
In Spyder 2.3.9, I tried this code to load a session from script / commande Line, it seems not working :

```
from spyderlib import start_app
main1= start_app.main()
main1.load_session('D:/_devs/Python01/project27/test_folio_elvis_test01_.session.tar')

```

MainWindow has a method load_session.

Also there is this method :
from spyderlib.utils.iofuncs import load_session

Am not how to get access to the mainWindow object by command line....

**Comment by andfoy** [comment]
@ccordoba12 Do we add both functions? i.e., Load a project file and configuration files?

**Comment by ccordoba12** [comment]
Nop, just to load a project for now.
