### ISSUE TITLE
Connect Spyder 3.0 to Ipython Python 2.7 

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3838]
Is it a way to launch Spyder 3.0 (under Python 3.4 install) and Connect the interpreter to IPython Python 2.7 ?
It sounds strange, but practical reasons are:
    1) Benefits of Spyder new features (ie 3.xxxxx)
   2) Needs to develop under Python 2.7 because some essential packages are only on Python 2.7 (C++ based package).

Any kind of potential problems ?

**Comment by ccordoba12** [comment]
You can change your interpreter in to point to Python 2.7 in

    Preferences > Python interpreter > Python executable

There shouldn't be any problems even if you're using Python 3 to run Spyder.

However, Spyder 3.0 works in Python 2 and 3 without problems :-)

**Comment by arita37** [comment]
Thanks.

Do you run regression tests of Spyder 3.0 on Python 2.7 ?

Thahnks

**Comment by ccordoba12** [comment]
Sure:

https://travis-ci.org/spyder-ide/spyder

**Comment by arita37** [comment]
ok, Thanks.
For people, reading this thread:
you can install SPyder on Anaconda 2 by   
conda update Spyder
