### ISSUE TITLE
Spyder dmesg for total loading speed control

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#3844]
Spyder is slow to load.

**What is the expected output? What do you see instead?**
I want to see how much time it took for Spyder to load. I don't see anything.

## Versions and main components

* Spyder Version: 2
* Python Version: 2
* Operating system: Any

## Detailed stuff

http://pydev.blogspot.com.by/2016/11/python-import-world-anti-pattern.html
Spyder also imports everything. It does make sense to import everything to test for missing symbols, but doesn't make sense to import Qt and friends to just process the options. Although Spyder had the `--light` option, the control over its speed is not enough.

What could be done to make this aspect more interesting:

(Help|About|?) -> (Debug|Development|About) -> (Loaded in|Speed|Log|dmesg)

UI that shows graph of loaded components with user requests to load or deny loading and show footprint of user's choice (expected and actual), caching the load process if underlying resources don't change (scons-style).

**Comment by ccordoba12** [comment]
Sorry Anatoly but Spyder 2 is not supported anymore. Spyder 3 loads faster than before thanks to PyQt5.
