### ISSUE TITLE
Dialog box Notifying of an Updated version of Spyder Does not allow me to click "OK" or update. 

### ISSUE THREAD

**Issue by smarti9701** [spyder-ide/spyder#3846]
## Description

**What steps will reproduce the problem?**

1. open spyder
2. let it automatically prompt that an updated version exists
3. attempt to click on any link or the "OK" button in the dialog box

**What is the expected output? What do you see instead?**
unresponsive box

**Please provide any additional information below**
I have also updated spyder to 3.0.2 via the anaconda prompt; however, when i restart Spyder the same behavior occurs and I am still on version 3.0.0

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
> I have also updated spyder to 3.0.2 via the anaconda prompt; however, when i restart Spyder the same behavior occurs and I am still on version 3.0.0

I don't understand what happens in your case because you say you updated to the latest version but you're still in the old one. Please be sure to use 3.0.2 because it was in that version that the dialog problem you are reporting was fixed.

**Comment by pwoosam** [comment]
@smarti9701 The update may have had errors.
Here is the solution to the issue I've had updating from 3.0.0 to 3.0.2:

In order to properly update, run a command prompt or powershell window with admin privileges. Then make sure to read what messages comes up. I had a message saying that it could not remove a non-existing file easy-install.pth.

So I just made an empty file:
C:\Users\monke\Anaconda3\Lib\site-packages\easy-install.pth
Then pip install -U spyder again from an elevated prompt.

**Comment by smarti9701** [comment]
I found out what the problem was. I had updated Spyder; however, I needed to update Conda, which I did through the command prompt. After I did that, then I re-updated Spyder, and it worked. 

Thank you all for the awesome assistance.

**Comment by ccordoba12** [comment]
@smarti9701, thanks for letting us know about it :-)
