### ISSUE TITLE
 'self' not defined in DataFrameView.update_section_height()

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#3848]
@andfoy I think you may need to add `self` here: https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/variableexplorer/dataframeeditor.py#L486

It would be good to test the resize functionality afterwards to make sure it works :)

**Comment by ccordoba12** [comment]
@andfoy, please work on @jitseniesen's suggestions :-)

**Comment by andfoy** [comment]
Such a simple mistake! Sorry! Now it should be corrected in PR #3852, also I've tested it and it works like a charm :)
