### ISSUE TITLE
Spyder fails to start on Ubuntu 16.10: No module named 'PyQt4.QtWebKit'

### ISSUE THREAD

**Issue by Atalanttore** [spyder-ide/spyder#3851]
## Description of your problem

**What steps will reproduce the problem?**

1. Install `spyder3` on a new Ubuntu 16.10 system.
2. Open terminal
3. Type `spyder3` and press Enter.

**What is the expected output? What do you see instead?**
~$ spyder3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python3/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python3/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named 'PyQt4.QtWebKit'

**Please provide any additional information below**

## Versions and main components

* Spyder Version: [2.3.8](http://www.ubuntuupdates.org/package/core/yakkety/universe/base/spyder3)
* Python Version: [3.5.1-4](http://www.ubuntuupdates.org/package/core/yakkety/main/base/python3)
* Operating system: Ubuntu 16.10 x64

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

No chance. Spyder3 doesn't start at all.

Regards,

Ettore

**Comment by ccordoba12** [comment]
Spyder was deliberately broken by Debian/Ubuntu maintainers when they removed the `PyQt4.QtWebKit` module from their repositories and didn't even care to patch Spyder for this.

We can't do anything about this, so our recommendation to you is to download and install the Anaconda Python distribution:

http://continuum.io/downloads.html

**Comment by Atalanttore** [comment]
Thanks for the workaround hint.

I've created a [bug report on Launchpad](https://bugs.launchpad.net/ubuntu/+source/spyder/+bug/1650805) for this problem.

Regards,

Ettore
