### ISSUE TITLE
Add fuzzy function/class search shortcut

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3855]
Similar to the ctrl+p shortcut that fuzzy search filenames, it will be nice to steal two more shortcuts from sublime:
ctrl+r: same as ctrl+p and writing @ (which will the fuzzy searches function/classes in the current file)
ctrl+shift+r: same as ctrl+r but project and open-files wise (searches for functions in the whole project and the currently open files)

(at least the ctrl+r one is very simple, sublime implements it exactly as ctrl+p and writing @ - so that the search bar has @ in the beginning)
what do you think?

**Comment by ccordoba12** [comment]
This is a good idea. Unfortunately, `Ctrl+R` is reserved for *Find & Replace*.

What about `Ctrl+Alt+P`? Then you could change it to `Ctrl+R` in Preferences :-)

**Comment by talkaminker** [comment]
That would be awesome

**Comment by ccordoba12** [comment]
@andfoy, please work on this one.

There's already a shortcut associated to `Ctrl+Alt+P` (to show/hide the Project Explorer). So you need to remove it and associate instead to show our file switcher and add a `@` at the beginning of it.
