### ISSUE TITLE
Go to line doesn't correspond to the correct file

### ISSUE THREAD

**Issue by mariacamilaremolinagutierrez** [spyder-ide/spyder#3857]
Lines to jump to and filenames are saved in different dictionaries. After reloading spyder they don't correspond to their initial ones.

**Comment by ccordoba12** [comment]
Let's merge first the focus PR and then you'll work on this one :-)

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one. This refers to lines and filenames saved when Spyder is closed and reopened again.
