### ISSUE TITLE
Extra selections should be ordered

### ISSUE THREAD

**Issue by pwoosam** [spyder-ide/spyder#3859]
##### This is more of a suggestion:
Extra selections dict in base.py is a dictionary, but an OrderedDict may be a better option.
Using an ordered dictionary would allow some selections to take precedence over others, ensuring that the last selection added to extra selections is the one which is highlighted.

This would be a solution to [issue 7](https://github.com/spyder-ide/spyder-vim/issues/7) in spyder-vim.

## Versions and main components

* Spyder Version: latest
* Python Version: 3.5.2
* Operating system: Windows 10

**Comment by pwoosam** [comment]
Here is somewhere in Spyder where the same issue occurs:
1. Search for a word which is a part of another word (selection)
2. Place the cursor on the larger word (extra_selections)
![find](https://cloud.githubusercontent.com/assets/18713517/21308935/fa02e908-c590-11e6-89ee-3a5c55944923.PNG)
![error](https://cloud.githubusercontent.com/assets/18713517/21308949/058b0404-c591-11e6-8415-0849b7d822b4.PNG)

#### Expected output:
![correct](https://cloud.githubusercontent.com/assets/18713517/21309120/cf789ba0-c591-11e6-87db-1cb2ce3d0754.PNG)

**Comment by ccordoba12** [comment]
Please go for it. We're glad to receive a PR for this and also improve the state of spyder-vim :-)
