### ISSUE TITLE
spyder terminates after runtime error

### ISSUE THREAD

**Issue by JPelda** [spyder-ide/spyder#3865]
## Description

**What steps will reproduce the problem?**

1. Run any program that causes an error.
2. 
3. 

**What is the expected output? What do you see instead?**
Spyder terminates unvoluntary.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.2 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by JPelda** [comment]
Solved the problem by resetting spyder: conda --reset spyder

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it :-)
