### ISSUE TITLE
New feature : Create shortcut Launch for a project

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3869]
Sometimes, we need to work with many projects :  
Ability to create a shortcut Launch for Spyder + a Specific project would be useful in Project Menu
'Create Project Shortcut on desktop'

It allows : 
   Launch project directly by shortcut.
   Sometimes the list of recent project can be empty....

(If possible, we can add General config for a project...).

Thanks for your contribution of Spyder.

**Comment by ccordoba12** [comment]
For Spyder 3.1 we added the command line option `--project` to start Spyder on a specific project, like this

    spyder --project <path/to/your/project>

With this option you can create as many shortcuts as you want.

It's not easy for us to create shortcuts for all the operating systems we support (Window, Linux and Mac), so I think you're going to do it yourself with this new option :-)

**Comment by ccordoba12** [comment]
> Sometimes the list of recent project can be empty....

When does this happen for you? This is very odd...

**Comment by arita37** [comment]
Yes,...
I tried to reproduce the operations, but could not make it done again
(When it happens again (if any), I will put the exact steps...).

Besides it, having the ability to launch some projects through commande 
line (ie command shortcut)
would be quite useful when working on many projects (sometimes shared 
computer with shared spyder...)

Thanks


Carlos Cordoba wrote:

**Comment by ccordoba12** [comment]
Ok, thanks. I'm going to close this issue then. Please open a new one when you're able to reproduce the Recent Projects menu problem.
