### ISSUE TITLE
Improvement: Spyder launching 6 python interpreters...

### ISSUE THREAD

**Issue by arita37** [spyder-ide/spyder#3870]
On Spyder 3.0.2, launched on anaconda 2 (Python 2.7), Win 64bits, we have 6 python interpreters launched....

(Before in Spyder 2.0, it was only 2...).
Just wondering if all 6 interpreters are necessary....

![image](https://cloud.githubusercontent.com/assets/18707623/21375940/90f13150-c774-11e6-8170-f28f9fcf79d7.png)

For example, Pycharm is just launching 2 (one for Pycharm, one for the Ipython console...)

**Comment by ccordoba12** [comment]
Yes, they are. One is a Python Console we open by default, another one for an IPython console, three for our completion machinery (Jedi, rope and fallback), and the last one is for Spyder itself.

So there you have it: 6 processes :-)

**Comment by arita37** [comment]
Ok, Thanks,
  (before in Spyder 2.3,  it was only 3: 1 default, 1 spyder,  and 1 for Ipython).....
   It worked well (although some functionalities were missing like Project..).

**Comment by ccordoba12** [comment]
Yep, code completions in the Editor worked with threads instead of external processes in 2.3.

However, we switched to a architecture for code completion to make things more stable and to be able to add completion libraries for other languages in the future.
