### ISSUE TITLE
Profiler results full of strange result (decorator-gen-*)

### ISSUE THREAD

**Issue by masfaraud** [spyder-ide/spyder#3872]
## Description of your problem

**What steps will reproduce the problem?**

1. Launching the profiler on a random script.

**What is the expected output? What do you see instead?**
I get a long list after a while (loading all these strange results takes some time).

![profiler](https://cloud.githubusercontent.com/assets/14061753/21381006/233db8b0-c759-11e6-9675-aca493c4b0ed.png)

At the bottom of this list is the expected information I usually get.

**Please provide any additional information below**
For large scripts, it makes the profiler impossible to use.

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: Python 3.5.2 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 
* Operating system: Linux Mint

**Comment by ccordoba12** [comment]
Please update to Spyder 3.0.2 and try again, we don't support Spyder 2.3 anymore.

**Comment by masfaraud** [comment]
Ok, this bug doesn't appear in version 3.0.2.
