### ISSUE TITLE
async and await keywords highlight

### ISSUE THREAD

**Issue by xxblx** [spyder-ide/spyder#3875]
## Description 

Spyder doesn't highlight **async** and **await** keywords from Python 3.5+ 

**What steps will reproduce the problem?**

1. Open spyder 
2. Enter async or await in editor

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5.2
* Operating system: macOS Sierra 10.12.1

## Dependencies

```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5a1 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this in Spyder 3.1.

@mariacamilaremolinagutierrez, this is an easy one for you, given that you've worked on highlighting of Python words in the past :-)
