### ISSUE TITLE
How to set individual font size for console/editor/etc. panes?

### ISSUE THREAD

**Issue by alexander-rakhlin** [spyder-ide/spyder#3882]
Hi all,

It seems starting from Version: 3.0.0 separate font settings for different panes disappeared. I see it on General tab only. Quite inconvenient.

## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.4.5
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry, it's not possible anymore to set fonts individually for each pane.

We decided to remove this feature because it made quite cumbersome to change font settings for most users (because they had to go from plugin to plugin to do it).

Sorry for the inconvenience.

**Comment by abhiyendra** [comment]
so how do we change the font now or the background as white is not good in the nite

**Comment by ccordoba12** [comment]
That's done in `Preferences > Syntax coloring`

**Comment by kings9** [comment]
How do we change the background color for help(object inspector) window to make it similar with the rest of the panes when all other panes(editor,ipython console) are dark.

**Comment by ccordoba12** [comment]
@kings9, please see #2350.

**Comment by Travis-Barton** [comment]
Increasing the font size of the Files pane would be very helpful. If allowing us to change it ourselves cumbersome, it would be helpful if there were size differences or maybe color differences between folders and files. Or maybe color by file type? My eyes hurt after searching for a file too long.
