### ISSUE TITLE
Menus "File",  "Edit" and "Search" in master not available for mouse click

### ISSUE THREAD

**Issue by sergiokapone** [spyder-ide/spyder#3887]
## Description of your problem

**What steps will reproduce the problem?**

1. Click mouse on menu item "File" or"Edit" or"Search". It does not available.

But if one click on "Source" and then move mose lleft menu items "File",  "Edit" and  "Search" are available.

## Versions and main components

* Spyder Version: 4.0.0dev0
* Python Version: Python 3.4.4amd64 (From WinPython)
* Operating system: Win10.0.14393

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please open this bug in the WinPython issue tracker. We haven't done anything to break those menus, so it has to be a problem with WinPython.

**Comment by ccordoba12** [comment]
Sorry, I didn't notice it that this was happening on master. I apologize for closing this in a rush.

@dalthviz, please investigate what's happening here :-)

**Comment by dalthviz** [comment]
@ccordoba12  what I have found is that something like the described in this [link](https://forum.qt.io/topic/8833/solved-first-menu-on-menubar-not-activating-when-moused-over/11) is happening, where in some point we are creating a widget or object with the main window as a parent, but it is incorrectly placed, however I don't know where we are doing this.

**Comment by dhirschfeld** [comment]
This seems similar to issue #2204 so there may be something to learn from that...

**Comment by ccordoba12** [comment]
I hope @dalthviz PR will fix this error once and for all because it raises our menu bar on top of all other things in the main window.
