### ISSUE TITLE
Cannot connect to existing kernel due to osp.basename

### ISSUE THREAD

**Issue by glymehrvrd** [spyder-ide/spyder#3888]
## Description of your problem

**What steps will reproduce the problem?**

1. In Panel "IPython console", right click and click "Connect to existing console".
2. Click Browse to select a ipython kernel json file, e.g "d:/mykernel.json".
3. Click Ok.

**What is the expected output? What do you see instead?**

Complains that it can not connect to kernel.

**Please provide any additional information below**

I found that spyder failed to connect to an existing ipython kernel, while using command `ipython qtconsole --existing d:/mykernel.json` worked well.

After a little survey into source code `spyder/plugins/ipythonconsole.py`, in method `_create_client_for_kernel` I found this,
```python
        # Verifying if the connection file exists
        try:
            connection_file = find_connection_file(osp.basename(connection_file))
        except (IOError, UnboundLocalError) as e:
            QMessageBox.critical(self, _('IPython'),
                                 _("Unable to connect to "
                                   "<b>%s</b>") % connection_file)
            return
```
I noticed that `osp.basename` removed my kernel file path, which leaded to this error. Once I have removed it, everything works well.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7.10 64bit
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.9.2 (OK)
pandas >=0.13.1  :  0.16.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  0.7.6 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This was already fixed an will be part of Spyder 3.1.
