### ISSUE TITLE
suggestion: shortcut for jumping to next/prev cell

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3889]
When working with cells it is really nice to be able to jump to the next/prev cell
(it should jump to the first line of the cell and not the #%%)

Suggestion is to add a configurable shortcut for that.
Ideally for me, ctrl+up/down but since those are taken, how about ctrl+pageup/pagedown?

Cheers

**Comment by ccordoba12** [comment]
Thanks for the suggestion. This is a duplicate of issue #1833.
