### ISSUE TITLE
Missing plugin folder

### ISSUE THREAD

**Issue by bloodymeli** [spyder-ide/spyder#3890]
## Description of your problem
I'm missing the plugins folder.

**What steps will reproduce the problem?**

Install spyder using pip install.
Upgraded spyder using pip.

**What is the expected output? What do you see instead?**
I expected to see a  ${HOME}/.spyder/plugins/ folder/  . 
But there is no ${HOME}/.spyder folder

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Spyder configuration was moved to

    .config/spyder{-py3}

in Spyder 3.0 to comply with the XDG standard, which was required by several Linux users.
