### ISSUE TITLE
Remove Spyder 2 theme (png icons) for Spyder 4.0

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3894]

**Comment by ccordoba12** [comment]
Please hold on this one because of issue #3843. We're still trying to understand what to do about that one, but we could fallback to the Spyder 2 theme given its severity,

**Comment by goanpeca** [comment]
Yeah, that windows problem is quite nasty :-|.

Even then, maybe we should really considering using SVGs instead of PNGs as fallback so that they scale nicely on different resolutions. Maybe that could be a separate approach?

**Comment by ccordoba12** [comment]
Yep, but then we'd need to create SVGs for all FontAwesome icons we use, and loose the ability to change their colors and orientations as easily as we are doing it right now.

**Comment by goanpeca** [comment]
>Yep, but then we'd need to create SVGs for all FontAwesome icons we use, and loose the ability to change their colors and orientations as easily as we are doing it right now.

Creating them is not really an issue cause we can export all icons used in spyder as svg (everytime they are called...)

Changing their color although a bit more contrived, can be achieved through CSS styling, but we do need to generate the colors as separate SVG files.

**Comment by ccordoba12** [comment]
> Creating them is not really an issue cause we can export all icons used in spyder as svg (everytime they are called...)

So can we do this on the fly? As part of QtAwesome or our `icon_manager` module?

If this is the case, then we should do this for 3.2 ;-)

**Comment by ccordoba12** [comment]
This could be solved in Spyder 5, but closing for now.
