### ISSUE TITLE
Spyder won't start. PyQt4 Webkit

### ISSUE THREAD

**Issue by AndreyBulezyuk** [spyder-ide/spyder#3895]
## Description of your problem

**What steps will reproduce the problem?**

1. Opening Spyder3

**What is the expected output? What do you see instead?**
I get following crash log:

![screenshot at 2016-12-28 17-51-13](https://cloud.githubusercontent.com/assets/19634923/21526680/446d36d2-cd26-11e6-9254-f94fb1296285.png)

`dell@dell-Inspiron-7559:~$ spyder3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 734, in setup
    message=_("Spyder Internal Console\n\n"
  File "/usr/lib/python3/dist-packages/spyderlib/plugins/console.py", line 74, in __init__
    self.find_widget.set_editor(self.shell)
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/findreplace.py", line 260, in set_editor
    from spyderlib.qt.QtWebKit import QWebView
  File "/usr/lib/python3/dist-packages/spyderlib/qt/QtWebKit.py", line 10, in <module>
    from PyQt4.QtWebKit import *  # analysis:ignore
ImportError: No module named 'PyQt4.QtWebKit'
`

**Please provide any additional information below**
I use Ubuntu Mate 16.10. I installed Spyder with "sudo apt-get install spyder3". I tried to install PyQt4 trough Pip3, but it does not really work and neither PyQt4 nor PyQt5 are listed in Pip3 (Pip3 list).

These are my installed packages with version:
`dell@dell-Inspiron-7559:~$ pip3 list
alabaster (0.7.8)
apturl (0.5.2)
Babel (2.3.4)
beautifulsoup4 (4.5.1)
Brlapi (0.6.5)
chardet (2.3.0)
command-not-found (0.3)
cryptography (1.5)
cycler (0.10.0)
decorator (4.0.6)
defer (1.0.6)
distro-info (0.14build1)
docutils (0.12)
html5lib (0.999)
httplib2 (0.9.1)
idna (2.1)
imagesize (0.7.1)
ipython (2.4.1)
jedi (0.9.0)
Jinja2 (2.8)
keyring (9.1)
keyrings.alt (1.1.1)
language-selector (0.1)
launchpadlib (1.10.4)
lazr.restfulclient (0.13.4)
lazr.uri (1.0.3)
lightdm-gtk-greeter-settings (1.2.1)
louis (2.6.5)
lxml (3.6.4)
Mako (1.0.4)
MarkupSafe (0.23)
mate-tweak (16.10.5)
matplotlib (1.5.2rc2)
numexpr (2.6.0)
numpy (1.11.1rc1)
oauth (1.0.1)
onboard (1.3.0)
pandas (0.17.1)
pep8 (1.7.0)
pexpect (4.2.0)
Pillow (3.3.1)
pip (8.1.2)
polib (1.0.7)
psutil (4.2.0)
ptyprocess (0.5.1)
pyasn1 (0.1.9)
pycrypto (2.6.1)
pycups (1.9.73)
pyflakes (1.2.3)
Pygments (2.1.3)
pygobject (3.22.0)
pyparsing (2.1.8)
python-apt (1.1.0b5)
python-dateutil (2.4.2)
python-debian (0.1.29)
pytz (2014.10)
pyxdg (0.25)
PyYAML (3.11)
pyzmq (15.2.0)
reportlab (3.3.0)
requests (2.10.0)
roman (2.0.0)
scipy (0.17.1)
screen-resolution-extra (0.0.0)
SecretStorage (2.3.1)
sessioninstaller (0.0.0)
setproctitle (1.1.8)
setuptools (26.1.1)
simplegeneric (0.8.1)
simplejson (3.8.2)
six (1.10.0)
Sphinx (1.4.8)
spyder (2.3.8)
systemd-python (232)
tables (3.2.2)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
urllib3 (1.15.1)
usb-creator (0.3.3)
wadllib (1.3.2)
wheel (0.29.0)
xkit (0.0.0)
zope.interface (4.2.0)
`

## Versions and main components

* Spyder Version:
* Python Version: 
`dell@dell-Inspiron-7559:~$ python3
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
`

* Operating system: 
`dell@dell-Inspiron-7559:~$ uname -a
Linux dell-Inspiron-7559 4.8.0-32-generic #34-Ubuntu SMP Tue Dec 13 14:30:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

## Dependencies

While writing this issue i got an error: 

![screenshot at 2016-12-28 17-49-00](https://cloud.githubusercontent.com/assets/19634923/21526659/1b948152-cd26-11e6-89ce-b1f29fca1e85.png)

before that error, i tried to install some packages trough synaptic that had similar names to pyqt4 webkit

**Comment by ccordoba12** [comment]
Spyder is currently broken in Ubuntu because they removed the PyQt4 Webkit module (which Spyder uses) and didn't care to patch Spyder for this.

Unfortunately we can't do anything about it, just recommend you to use the Anaconda distribution instead of the official Ubuntu channels to install Spyder.
