### ISSUE TITLE
Py34 support?

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3900]
Question:
What will be the status of Python 3.4 as soons as Python 3.6 is fully supported?

**Comment by ccordoba12** [comment]
We could stop testing on it to move to 3.5 and 3.6.

**Comment by goanpeca** [comment]
The new release of the anaconda distribution (middle/end of January) in theory will do this, so that is the date we should aim for?

**Comment by ccordoba12** [comment]
Yep.
