### ISSUE TITLE
Spyder stopped working and attempt to install package to help failed too

### ISSUE THREAD

**Issue by TheMitchWorksPro** [spyder-ide/spyder#3904]
## Description of your problem

Spyder stopped working.  No error messages.  Nothing.  It worked before (after first installation of Anaconda back in September 2016) and then, clicking the icons for it result in nothing as of some weeks  ago when I tried to use it agian.  No errors.  No working Spyder IDE.  Attempted to run Spyder Reset icon.  Nothing from that either.  

So then I attempted to copy the target of the Spyder reset icon and run it from an Anaconda prompt.  A screenshot from that is provided in the attached file.  Text at bottom led me to believe that maybe I needed to install a package:  either PYQT4 or Pyside.  Anaconda search command did not seem to produce useful results for PYQT4 but Pyside produced a package list that the anaconda show command could produce an install URL.  I then tried to do a dry-run of Pyside install into my Python 3.5 environment and this produced a trace dump with instructions to submit it as an issue.  Word file with screenshot of what happened from Spyder reset, my earlier investigation and a dump of some of the anaconda commands I tried is attached.  Focusing on just the instruction from this effort that led to a trace dump ... see below for the package that had a failed dry-run.  Any help getting Spyder to work would be appreciated but given that this may be hard to reproduce, see my notes below on a package that failed on dry-run that I was hoping might clear it up.  Maybe we can start there ...

**What steps will reproduce the problem?**

1.  Note:  this occurred on a Windows 7 64 bit machine running the latest installation of Anaconda Python.  Environments were created for Python 2.7 and Python 3.5 with Python 3.5 being the default. 
2.  Spyder used to work as Python 3.5
3. Anaconda commands to look into the problem were run from Python 3.5 environment

**What is the expected output? What do you see instead?**
Goal is to get Spyder to work again.  Errors point to possible missing package even though it worked before and mysteriously stopped working.  Please evaluate trade dump provided below for package I did not install due to errors in dry-run of installation

(C:\ProgramFilesCoders\Anaconda3) C:\Users\Mitch>conda install --dry-run --chann
el https://conda.anaconda.org/conda-forge pyside

Package plan for installation in environment C:\ProgramFilesCoders\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0           1 KB  conda-forge
    vc-14                      |                0          985 B  conda-forge
    libiconv-1.14              |           vc14_4         670 KB  conda-forge
    conda-4.2.13               |           py35_0         436 KB  conda-forge
    libxml2-2.9.4              |           vc14_2         3.2 MB  conda-forge
    libxslt-1.1.29             |           vc14_2         452 KB  conda-forge
    pyside-1.2.4               |      py35_vc14_2         5.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        10.3 MB

The following NEW packages will be INSTALLED:

    libiconv:  1.14-vc14_4       conda-forge [vc14]
    libxml2:   2.9.4-vc14_2      conda-forge [vc14]
    libxslt:   1.1.29-vc14_2     conda-forge [vc14]
    pyside:    1.2.4-py35_vc14_2 conda-forge [vc14]
    vc:        14-0              conda-forge

The following packages will be UPDATED:

    conda:     4.2.7-py35_0                  --> 4.2.13-py35_0 conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env: 2.6.0-0                       --> 2.6.0-0       conda-forge

The following packages will be DOWNGRADED due to dependency conflicts:

    qt:        5.6.0-vc14_0                  [vc14] --> 4.8.7-vc14_9
  [vc14]

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\ProgramFilesCoders\Anaconda3  (writable)
    default environment : C:\ProgramFilesCoders\Anaconda3
       envs directories : C:\ProgramFilesCoders\Anaconda3\envs
          package cache : C:\ProgramFilesCoders\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\ProgramFilesCoders\Anaconda3\Scripts\conda-script.py install --dry-run --c
hannel https://conda.anaconda.org/conda-forge pyside`

    Traceback (most recent call last):
      File "C:\ProgramFilesCoders\Anaconda3\lib\site-packages\conda\exceptions.p
y", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramFilesCoders\Anaconda3\lib\site-packages\conda\cli\main.py"
, line 144, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramFilesCoders\Anaconda3\lib\site-packages\conda\cli\main_ins
tall.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramFilesCoders\Anaconda3\lib\site-packages\conda\cli\install.
py", line 398, in install
        common.confirm_yn(args)
      File "C:\ProgramFilesCoders\Anaconda3\lib\site-packages\conda\cli\common.p
y", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'

Additional info file:
[Spyder_StoppedWorkingInvestigation_2016-12-31.docx](https://github.com/spyder-ide/spyder/files/679884/Spyder_StoppedWorkingInvestigation_2016-12-31.docx)

**Comment by jitseniesen** [comment]
Try upgrading Spyder. You have Spyder 2.3.9 and pyqt 5 installed; if I remember correctly, that combination does not work. My guess is that when you installed Anaconda, you had Spyder 2.3 and pyqt 4, which does work. Then at some point, pyqt 5 got installed which breaks Spyder 2.3. Spyder 3.0.0 and later works with pyqt 5.

The dry-run error has nothing to do with Spyder. It seems to originate in conda, so I'd try upgrading conda to resolve that.

If this does not help and you are stuck, it may be easiest to uninstall Anaconda and then re-install everything.

**Comment by TheMitchWorksPro** [comment]
Thanks for getting back to me.  Going to re-deploy my whole environment today (un-install / re-install).  Ahead of this, tried "conda update --all" thinking maybe it was just some kind of issue with needing updating.  That command destroyed my working Python 3.5 environment.  I have posted all messages at the conda/conda on github issues section.  The issue is documented here so it can be looked into:

https://github.com/conda/conda/issues/4160

**Comment by ccordoba12** [comment]
A couple of things:

1. Spyder 3.0 doesn't work with PySide.
2. You shouldn't mix Anaconda and conda-forge packages in the same environment (because they different build specs and so they can't be mixed at all).

I'd suggest you to remove your previous installation, then reinstall Anaconda using its 4.2 version, and finally only update Spyder with

    conda update spyder

**Comment by TheMitchWorksPro** [comment]
I first built my environment 3 months ago.  I used a mix of packages that
were from conda and pip installed attempting to replicate an environment I
used in a "Big Data and Social Analytics" online certificate I took from
MIT.

All worked fine for 3 months.  Now I see that the problem probably occurred
as a result of updates to the environment (I never would have guessed that
using commands to keep my environment up-to-date was dangerous).

As I debug my environment, I am getting into more trouble.

when you export an environment to use as a spec file - you can't just
import it.  you have to clean it up for things in the spec file that conda
create or conda update don't support.  At the bottom are a list of pip
package that you have to install separately as pip installs.  This worked
fine 3 months ago.  It is not working now - one of my commands may have
broken BeautifulSoup4 (claiming it was de-installing and re-installing the
package, but then it left a ghost of both in the environment).

Do you know how to find the source of a pip install if it is not on conda?
Can a pip install be de-installed?

To your point:  conda-forge is not anaconda?  I found a help page online
that suggests mixing and matching pip installs, conda installed packages
and non-conda installed packages can lead to some of the grief I am having
now even though everything worked fine together 3 months ago when I first
set up the environment.

I fixed Spyder twice now, but Anaconda is proving a trickier beast to
tame.  Once broken - the onus is on the user through trial and error
experiments to figure out what will work and often the only recourse seems
to be to rebuild an environment rather than fix it.  :-(

Today begins day 3 of my attempts to fix what worked in September.  Any
input on this would be useful.  Thanks for writing and following up.

Mitch

**Comment by TheMitchWorksPro** [comment]
If anyone has anything helpful to add to my last comment, feel free to add it to this open issue about conda.  I think the comments about Spyder (what this issue is about) were enough to get me past that issue at least.  thanks for all the help so closing this issue.

https://github.com/conda/conda/issues/4165
