### ISSUE TITLE
Two PYTHONPATH entries in result of add_pathlist_to_PYTHONPATH()

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#3907]
While working on the unittest plugin, I found out that the function `add_pathlist_to_PYTHONPATH()` in `spyder.utils.misc` sometimes yields a list with two entries for the `PYTHONPATH` environment variable:
```
>>> from spyder.utils.misc import add_pathlist_to_PYTHONPATH
>>> os.environ = {}
>>> env = ['PYTHONPATH=/lib/orig']
>>> add_pathlist_to_PYTHONPATH(env, ['/lib/newdir'])
>>> env
['PYTHONPATH=/lib/orig', 'PYTHONPATH=/lib/newdir']
```
On the other hand, if `os.environ` has a `PYTHONPATH` entry, then the two entries are combined:
```
>>> os.environ = {'PYTHONPATH': '/lib/in-env'}
>>> env = ['PYTHONPATH=/lib/orig']
>>> add_pathlist_to_PYTHONPATH(env, ['/lib/newdir'])
>>> env
['PYTHONPATH=/lib/newdir:/lib/orig', 'OLD_PYTHONPATH=/lib/in-env']
```
I presume that the correct result for the first call is `['PYTHONPATH=/lib/newdir:/lib/orig']`, but since the function is not documented I am not certain what the intended functionality is.

Is this indeed a bug? If yes, I am happy to fix it.

**Comment by ccordoba12** [comment]
I'll take a look at it, I'm not sure either.

**Comment by goanpeca** [comment]
Hi @dalthviz could you take a look at this one?

**Comment by dalthviz** [comment]
Hi @jitseniesen @ccordoba12 @goanpeca, looking into this I found that there are three elements that calls this function (`widgets/externalshell/pythonshell.py`, `widgets/externalshell/systemshell.py`, and `profilergui.py`).

Now the thing here is that for each element from the variable passed as env parameter to "add_pathlist_to_PYTHONPATH" they get the env variable and values, so even if `PYTHONPATH` doesn't exist, it is posible to set the new environment values in the `QProcessEnvironment()`. A "clear" place where this happens is in the `widgets/externalshell/systemshell.py`:

First it calls the function:
https://github.com/spyder-ide/spyder/blob/3.1.x/spyder/widgets/externalshell/pythonshell.py#L493
```
# Adding path list to PYTHONPATH environment variable
add_pathlist_to_PYTHONPATH(env, pathlist)
```
Then it loops the env variable to get all the env values (the old ones, and the new ones):
https://github.com/spyder-ide/spyder/blob/3.1.x/spyder/widgets/externalshell/pythonshell.py#L522
```
processEnvironment = QProcessEnvironment()
        for envItem in env:
            envName, separator, envValue = envItem.partition('=')
            processEnvironment.insert(envName, envValue)
self.process.setProcessEnvironment(processEnvironment) 
```
However something that seems strange to me is that in the  `widgets/externalshell/systemshell.py` we first loop and then we call "add_pathlist_to_PYTHONPATH".

**Comment by dalthviz** [comment]
Since the `pythonconsole` is going to be removed, and is the only one that uses the list with two entries, the `add_pathlist_to_PYTHONPATH()` will be simplified.

**Comment by goanpeca** [comment]
Can we close this @dalthviz ?

**Comment by dalthviz** [comment]
Sure :+1:
