### ISSUE TITLE
View>Toolbars option doesn't work anymore in version 3.0.2

### ISSUE THREAD

**Issue by tanayz** [spyder-ide/spyder#3910]
## Description

**What steps will reproduce the problem?**

1. Click View --> Click Toolbars (nothing happens)

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.2 
* Python Version: 2.7.12
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  0.8.1 (OK)
pep8 >=0.6       :  1.6.2 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  0.7.5 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. This was already fixed and will be part of Spyder 3.1.
