### ISSUE TITLE
Failed to import data in Variable Explorer on Windows

### ISSUE THREAD

**Issue by glymehrvrd** [spyder-ide/spyder#3917]
## Description of your problem

Import data is not working.

**What steps will reproduce the problem?**

1. In variable explorer, export data as `a.spydata`
2. Import `a.spydata`

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

In source code `spyder/widgets/ipythonconsole/namespacebrowser.py`
```python
    def load_data(self, filename, ext):
        # Wait until the kernel tries to load the file
        wait_loop = QEventLoop()
        self.sig_got_reply.connect(wait_loop.quit)
        self.silent_exec_method(
HERE--->        "get_ipython().kernel.load_data('%s', '%s')" % (filename, ext))
        wait_loop.exec_()
```
I'm using Windows, so `filename` contains backslash, which leads to this error. Escaping should be done here.

It's so hard to find out the solution to this problem... And I think all `silent_execute` is not safe because the same problem could happen.

But weirdly, spyder with python3 works fine.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)]
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Sorry for inconvenience, we didn't test this functionality on Windows. We'll fix it for Spdyer 3.1.

@andfoy, please work on this one.

**Comment by andfoy** [comment]
I tried to reproduce this error on Windows, without any success. Can we have more information about the reproduction scenario?

**Comment by glymehrvrd** [comment]
You must name the saved spydata file `xxx:\a.spydata`, since '\a' will become '\x07' which leads to this error. 
What's more, I'm using PyQt4. Maybe it's not a problem in PyQt5.

## Version and main components

Spyder Version: 3.0.2
Python Version: Python 2.7.10 64-bit
Qt Versions: 4.8.7, PyQt4 4.11.4 on Windows

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.4.3 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.4.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  0.7.6 (OK)

**Comment by andfoy** [comment]
@glymehrvrd Contrary to what we expected, this error was related to write permissions inside the folder where the spydata was located, for instance, the C:\ disk root is a path that have such kind of restrictions.
