### ISSUE TITLE
Spyder : IPython cannot connect to kernel on Debian 8 (jessie) : "Connecting to kernel..."

### ISSUE THREAD

**Issue by sebma** [spyder-ide/spyder#3921]
## Description of your problem
When I run spyder on Debian 8 (jessie), IPython cannot connect to kernel, it waits forever saying:
"Connecting to kernel..."
**What steps will reproduce the problem?**

1. spyder --reset
2. spyder --default
3. LANG=C spyder &

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.6
* Python Version: 2.7.9
* Operating system: Debian 8 (jessie)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0   :  4.1.0rc1 (OK)
jedi >=0.8.1    :  None (NOK)
matplotlib >=1.0:  1.5.3 (OK)
pandas >=0.13.1 :  0.14.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  None (NOK)
pyflakes >=0.5.0:  1.0.0 (OK)
pygments >=1.6  :  2.1.3 (OK)
pylint >=0.25   :  None (NOK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.2    :  0.10.3 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Spyder 2.3.6 is way too old and unmaintained now. Please update to Spyder 3.0.2 and try again.

**Comment by sebma** [comment]
I don't have the admin. rights on this machine.

Can you give me a few spyder or ipython commands in verbose mode (or the like) so I can try and fix the pb. myself ?

**Comment by ccordoba12** [comment]
Then please install the Anaconda Python distribution (or Miniconda in case you have limited space). Those distributions could be installed in your home directory.

> Can you give me a few spyder or ipython commands in verbose mode (or the like) so I can try and fix the pb. myself ?

I'm sorry but this problem can be caused by a lot of things and we never figured it out how to fix it. That's why in Spyder 3 we completely rewrote how Spyder starts and connects to IPython kernels.

**Comment by sebma** [comment]
I'm afraid I won't have enough space.

Do you have any option to set spyder or IPython into verbose mode ?
