### ISSUE TITLE
Go-to-line dialog shows a question mark button that does nothing

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#3925]
@Usama23 reported this bug in a Continuum internal repository. I'm moving it here so we can work on it in the open. According to @Usama23:

**Actual Result:**
   Under the Go to line pop up window, click on Help icon ( ? ). button is clickable but on action perform on click.

**Expected Result**:
   When click on help icon (?), this should open Help related detail page.

![screenshot_28](https://cloud.githubusercontent.com/assets/21064099/21715079/5797d794-d424-11e6-9c7f-9ae5416e74cc.png)

**Comment by ccordoba12** [comment]
@dalthviz, I think the solution is just to remove that question mark button. The dialog is clear enough to add some help about it :-)

**Comment by Usama23** [comment]
@ccordoba12 this Help icon(?) is not even working on "Glueviz" app, if you are focusing on to remove this from "spyder", then it should be remove from "Glueviz" also.

**Comment by ccordoba12** [comment]
Glueviz is a different package and we (in Spyder) don't have any control over its development.

Please open a bug report in Glueviz repository about this problem to see if they want to fix it.
