### ISSUE TITLE
Make code completion work for modules developed as part of a project

### ISSUE THREAD

**Issue by alabd14313** [spyder-ide/spyder#3928]
Hello!

    Spyder Version: Git version (4dev)
    Python Version: 3.6
    Operating system: Arch Linux
It seems PYTHONPATH manager can't load codecompletion for custom folders added in it. It only works for default folder project, not even for folders exist in default project folder.

**Comment by ccordoba12** [comment]
This was fixed in Spyder **3.1.4**.

**Comment by alabd14313** [comment]
Thanks for your attention. but I still have this error.

**Comment by rlaverde** [comment]
Then this is related to #4410, a more robust solution for sending spyder_path to plugins will be implemented in spyder3.2.2
