### ISSUE TITLE
Segmentation fault on closing Sypder3

### ISSUE THREAD

**Issue by robwhalliday** [spyder-ide/spyder#3934]
## Description

**What steps will reproduce the problem?**

1. Start spyder3
2. File | Quit

**What is the expected output? What do you see instead?**
Get segmentation fault message.

**Please provide any additional information below**

It appears to be issue with QT5.   Also note being run on Debian - cat /proc/version - 
Linux version 3.16.0-4-powerpc (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 Debian 3.16.36-1+deb8u1 (2016-09-03)

Ran form within debugger to provide more information on the problem.

 Thread 5 "QDBusConnection" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xb4e46460 (LWP 6377)]
0x0c41c5ec in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/powerpc-linux-gnu/libQt5Core.so.5

(gdb) bt
#0  0x0c41c5ec in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) () from /usr/lib/powerpc-linux-gnu/libQt5Core.so.5
#1  0x09f38af4 in ?? () from /usr/lib/powerpc-linux-gnu/libQt5DBus.so.5
#2  0x09f214a4 in ?? () from /usr/lib/powerpc-linux-gnu/libQt5DBus.so.5
#3  0x0c1b6410 in ?? () from /usr/lib/powerpc-linux-gnu/libQt5Core.so.5
#4  0x0ffc4500 in start_thread (arg=0xb4e46460) at pthread_create.c:335
#5  0x0fd279ac in clone () at ../sysdeps/unix/sysv/linux/powerpc/powerpc32/clone.S:91

(gdb) info threads
  Id   Target Id         Frame 
  1    Thread 0xb7fbe2c0 (LWP 6360) "python3" 0x0ffccb98 in __pthread_cond_wait (cond=0x10fcf4e8, mutex=0x10fcf4d0) at pthread_cond_wait.c:186
  2    Thread 0xb6a4e460 (LWP 6374) "QXcbEventReader" 0x0fd1aec8 in poll () at ../sysdeps/unix/syscall-template.S:84
  3    Thread 0xb60ff460 (LWP 6375) "gmain" 0x0fd1aec8 in poll () at ../sysdeps/unix/syscall-template.S:84
  4    Thread 0xb58ff460 (LWP 6376) "gdbus" 0x0fd1aec8 in poll () at ../sysdeps/unix/syscall-template.S:84
* 5    Thread 0xb4e46460 (LWP 6377) "QDBusConnection" 0x0c41c5ec in QObject::disconnect(QObject const*, char const*, QObject const*, char const*) ()
   from /usr/lib/powerpc-linux-gnu/libQt5Core.so.5
  6    Thread 0xb3955460 (LWP 6380) "python3" 0x0ffccb98 in __pthread_cond_wait (cond=0x88da218, mutex=0x88da200) at pthread_cond_wait.c:186
  7    Thread 0xb2fcb460 (LWP 6381) "python3" 0x0ffccb98 in __pthread_cond_wait (cond=0xb309c160, mutex=0xb309c144) at pthread_cond_wait.c:186
  8    Thread 0xb234f460 (LWP 6382) "Qt bearer threa" 0x0fd1aec8 in poll () at ../sysdeps/unix/syscall-template.S:84
  17   Thread 0xae864460 (LWP 6401) "QFileInfoGather" 0x0ffccb98 in __pthread_cond_wait (cond=0x11a593e8, mutex=0x11a593d0) at pthread_cond_wait.c:186
  18   Thread 0xae064460 (LWP 6402) "QFileInfoGather" 0x0ffccb98 in __pthread_cond_wait (cond=0x11aeba58, mutex=0x11aeba40) at pthread_cond_wait.c:186
  19   Thread 0xad3a4460 (LWP 6403) "QFileInfoGather" 0x0ffccb98 in __pthread_cond_wait (cond=0x11af3a38, mutex=0x11af3a20) at pthread_cond_wait.c:186
  21   Thread 0xac2e4460 (LWP 6418) "python3" 0x0fd2a320 in accept4 (fd=512, addr=..., addr_len=0xac2e37bc, flags=524288)
    at ../sysdeps/unix/sysv/linux/accept4.c:40
  22   Thread 0xabae4460 (LWP 6419) "python3" 0x0fd2a320 in accept4 (fd=512, addr=..., addr_len=0xabae37bc, flags=524288)
    at ../sysdeps/unix/sysv/linux/accept4.c:40
  23   Thread 0xab2a4460 (LWP 6423) "python3" 0x0fd28408 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84
  24   Thread 0xaaaa4460 (LWP 6424) "python3" 0x0fd28408 in epoll_wait () at ../sysdeps/unix/syscall-template.S:84

(gdb) info registers
r0             0x9f38af4	166955764
r1             0xb4e45b70	3034864496
r2             0xb4e4d930	3034896688
r3             0x115ec2b0	291422896
r4             0x0	0
r5             0xb4f08ae0	3035663072
r6             0x0	0
r7             0x94	148
r8             0xb4f06b30	3035654960
r9             0x11a01bc	18481596
r10            0xb4f292e0	3035796192
r11            0xc41c390	205636496
r12            0x28288848	673744968
r13            0x1045a004	272998404
r14            0xb7fff018	3087003672
r15            0xffed2a4	268358308
r16            0xb4e464c0	3034866880
r17            0x9fbdb64	167500644
r18            0xbfffda28	3221215784
r19            0xc1b6250	203121232
r20            0xffef2ec	268366572
r21            0x0	0
r22            0x0	0
r23            0x0	0
r24            0xb4f292f0	3035796208
r25            0xb4e45ce8	3034864872
r26            0x115ec2b0	291422896
r27            0xb4f08ae0	3035663072
r28            0xb15e8fa	185985274
r29            0xc4eb02c	206483500
r30            0xc6a7d04	208305412
r31            0x0	0
pc             0xc41c5ec	0xc41c5ec <QObject::disconnect(QObject const*, char const*, QObject const*, char const*)+604>
msr            0xd932	55602
cr             0x48288842	1210615874
lr             0xc41c39c	0xc41c39c <QObject::disconnect(QObject const*, char const*, QObject const*, char const*)+12>
ctr            0xc41c390	205636496
xer            0x20000000	536870912
orig_r3        0xe	14
trap           0x300	768

## Version and main components

* Spyder Version: 3.0.2 
* Python Version: 3.5.3rc1
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0rc2 (OK)
sphinx >=0.6.6   :  1.4.9 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.5.6 (OK)

```

**Comment by robwhalliday** [comment]
Recent update the python3-pyqt5 appears to have fixed.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it, and glad to know things are working fine for you now :-)
