### ISSUE TITLE
autoindent doesn't work on function defined on the first line of a file

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3941]
## Description of your problem
autoindent doesn't work after enter if the 'def f' is on the first line of a file

**What steps will reproduce the problem?**
1) open new file and save it.
2) write on the first line
`def f():<hit enter here>`

**What is the expected output? What do you see instead?**
This should place a tab on the next line

**Please provide any additional information below**
this only doesn't work if the `def f` is on the very first line 

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: kubuntu 16.04
(everything installed from conda)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in Spyder 3.1 (to be released on January 17 :-).
