### ISSUE TITLE
Error when deleting the file with last focus in a project

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#3942]
**What steps will reproduce the problem?**

1. Open a project
2. Open a  file in the project and keep focus on it
3. Close Spyder
4. Delete the file
5. Open Spyder

**What is the expected output? What do you see instead?**

the editor don't load any files, and throw this error:

```
>>> Traceback (most recent call last):
  File "/home/rlaverde/code/spyder/spyder/plugins/projects.py", line 144, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/home/rlaverde/code/spyder/spyder/plugins/editor.py", line 2635, in setup_open_files
    filenames = self.reorder_filenames(filenames)
  File "/home/rlaverde/code/spyder/spyder/plugins/editor.py", line 2667, in reorder_filenames
    index_first_file = filenames.index(cfname)
ValueError: '/home/rlaverde/code/spyder/spyder/widgets/panels/scrollflag.py' is not in list
```

The error is throw by https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor.py#L2667

I'm not sure how this should be fixed, maybe just catch the error and don't change the focus?

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, please take a look at this one because it corresponds to the code you added in PR #3858.
