### ISSUE TITLE
project switch, new console rather than console restart

### ISSUE THREAD

**Issue by cimbi** [spyder-ide/spyder#3948]
## Description of your problem

Not really a big problem. Just trying to think of a justification for console restart when you switch from one project to another. This creates problems when you want to start calculations on one project and work on another in the meanwhile.

Would it it be better to create a new console instead?

I can create a fork and fix this. Should be pretty easy.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.5.2
* Operating system: Ubuntu 16.04

**Comment by ccordoba12** [comment]
We need to restart our consoles when switching projects to add the project's path to Python's `sys.path`. This allows users to easily import modules they could be developing as part of a project in each console.

If you want to work on two projects at the same time, you could start two Spyder instances instead. For that you need to go to

    Preferences > General > Advanced settings > Use a single instance

and deactivate that option. Then Spyder will open as many instances as you want.

**Comment by cimbi** [comment]
I solved this on my machine by modifying the spyder project plugin function open_project() where I set restart_consoles=False.

Perhaps an option somewhere where the user could set this would be useful. But I guess this is low priority.

Btw. great job on spyder! Very useful.

**Comment by ccordoba12** [comment]
I don't think we're going to add this feature, sorry. As I said, the right thing to do is to start two Spyder instances, each one associated to a different project.
