### ISSUE TITLE
F9 broken in latest git master

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#3949]
Pressing F9 in the editor gives the below traceback in the internal console:
```
>>> Traceback (most recent call last):
  File "C:\dev\packages\spyder\spyder\app\mainwindow.py", line 2415, in execute_in_external_console
    console.execute_code(lines)
TypeError: execute_code() missing 1 required positional argument: 'clear_variables'
```
![image](https://cloud.githubusercontent.com/assets/881019/21878445/18c763e0-d8de-11e6-8151-216783d600db.png)

**Comment by dhirschfeld** [comment]
https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py#L2415
https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/ipythonconsole.py#L848

**Comment by goanpeca** [comment]
@rlaverde please take this one

**Comment by ccordoba12** [comment]
This has to be done against 3.x not master. @rlaverde, please make `clear_variables=False` at the line pointed by @dhirschfeld in `ipythonconsole.py`.
