### ISSUE TITLE
IPython console not completing

### ISSUE THREAD

**Issue by GinoWoz1** [spyder-ide/spyder#3954]
## Description of your problem

**What steps will reproduce the problem?**

1.  Create dataframe
2.  try performing function on date column 
      df['Time'] = pd.to_datetime(df_filtered['Time'])

**What is the expected output? What do you see instead?**

Expected output is to go to the next line, all of my code is "completing" but being stuck in the ipython console without going to the next line. This is the same with a slew of other functions - I will send to microsoft sql database, the database will show the data with a simple query and the ipython console will hang forever never going to the next line.

The only way out of this is to write a "bad" line of code that will error out. This will create a new line.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7
* Operating system: 

![image](https://cloud.githubusercontent.com/assets/17535345/21913353/c92a81fc-d8e0-11e6-92d5-341bceace75d.png)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
Hi @GinoWoz1, sorry for the late response, can you provide a complete code example to replicate the problem? Also, can you list what other functions are not working for you? All the information that you can give us will be greatly appreciated :)

**Comment by ccordoba12** [comment]
@dalthviz, @GinoWoz1 provided an example in bullet 2. of his/her report. Please check it out.

**Comment by dalthviz** [comment]
@ccordoba12 I have tried to run the line, but what is the definition of df_filtered?, is that the dataFrame to be created?

**Comment by ccordoba12** [comment]
Yikes, sorry. @GinoWoz1, please give a complete and reproducible example to work with.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
