### ISSUE TITLE
Wrong latex interpetation

### ISSUE THREAD

**Issue by shimon89** [spyder-ide/spyder#3955]
Since my last Ubuntu update, the interpretation of Tex strings in figures (e.g., in axes labels, titles) is wrong: the string is interpreted, but the wrong symbols appear in places at which tags were inserted. The problem is always reproduced since my last upgrade, in all the Tex strings.

For example, the command  plt.ylabel(r'$a_5$ [cm s$^{-2}$]') makes a weird mixture of arrow and the letters N and e appear instead of the text "-2" in a superscript and a weird symbol appear insted of the subscripted "5". See the screenshot for example. 

![screenshot from 2017-01-13 11-37-36](https://cloud.githubusercontent.com/assets/25099078/21925161/db1995b6-d984-11e6-97ed-3a166f6e0f8a.png)

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.12
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.5.0   :  1.1.0 (OK)
pep8 >=0.6         :  None (NOK)
pygments >=1.6     :  2.1 (OK)
IPython >=1.0      :  2.4.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.6 (OK)
psutil >=0.3       :  3.4.2 (OK)
rope >=0.9.2       :  0.10.2 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  None (NOK)
pylint >=0.25      :  1.5.2 (OK)

```

**Comment by ccordoba12** [comment]
I had this problem too and it doesn't have to do with Spyder. It's problem introduced by some changes to the fonts used by matplotlib to display math. i think it'll be fixed in Ubuntu 17.04.

For now you need to install Latex and run this code to use it

    matplotlib.rc('text', usetex=True)
