### ISSUE TITLE
Add devs to the Appveyor account

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#3961]
## Todo

- [x] spyder
- [x] qtpy
- [x] conda-manager
- [x] loghub
- [x] spyder-unittest
- [x] qtawesome

----

@ccordoba12 it seems that only you can restart the appveyor builds in case of fail.

Could you add the github team in your settings? 

https://ci.appveyor.com/team

<img width="872" alt="screen shot 2017-01-15 at 11 42 46 am" src="https://cloud.githubusercontent.com/assets/3627835/21964325/d44b664e-db17-11e6-9f2a-d872e1408c9a.png">

Or create new roles with the specific permissions?

<img width="934" alt="screen shot 2017-01-15 at 11 44 04 am" src="https://cloud.githubusercontent.com/assets/3627835/21964340/f60b34a8-db17-11e6-8457-88cdcd9423b4.png">

Since this is attached to your personal account (appveyor is the only ci that does this)
https://ci.appveyor.com/project/ccordoba12/spyder/

We should probably create a new appveyor account with username spyder-ide using the issue-migrater login and set the team settings there.

**Comment by ccordoba12** [comment]
Yep, you read my mind because I was thinking to do this right now.

I think it be better to set an org account and use it for all our projects (e.g. I can stop/restart builds in QtAwesome). What do you think?

**Comment by goanpeca** [comment]
>I think it be better to set an org account and use it for all our projects (e.g. I can stop/restart builds in QtAwesome). What do you think?

Yes, I like this. But we need a github username, so the issues migrator one? or We create a spyder-bot or something user?

**Comment by ccordoba12** [comment]
I think the issues migrator would be fine. Let me do it right now.

**Comment by goanpeca** [comment]
We will need to recreate all appveyor integrations after that (and disable the current ones)

**Comment by ccordoba12** [comment]
I created the new account and added @spyder-ide/core-developers and @spyder-ide/3rd-party-admins as administrators. Our juniors will be able to start/restart builds :-)

Besides, I moved `qtpy` to that account. Please do the same for `qtawesome` and the other projects you have under your account.

**Comment by goanpeca** [comment]
:+1:

I will add a checkbox on the top to keep track of projects pending migration before closing this issue

**Comment by goanpeca** [comment]
@ccordoba12 whats the name of the account? it should be named spyder-ide, but https://ci.appveyor.com/spyder-ide/spyder is not working

**Comment by ccordoba12** [comment]
Please preserve the build number when doing the migration :-)

**Comment by ccordoba12** [comment]
It is: https://ci.appveyor.com/project/spyder-ide/spyder (notice the `project` path in between :-)

**Comment by goanpeca** [comment]
Oops

**Comment by ccordoba12** [comment]
Let's finish the migration and then we start build jobs because AppVeyor is hanging when a new project is added.

**Comment by goanpeca** [comment]
Ok

**Comment by ccordoba12** [comment]
I think `spyder-unittest` is the last one.

**Comment by goanpeca** [comment]
Done, I will open an issue to update the badges on the readme of each repo, to keep track of that.

**Comment by ccordoba12** [comment]
I'm doing the one here to see if everything works as expected :-)
