### ISSUE TITLE
two vertical lines (one for docstrings, one for code)

### ISSUE THREAD

**Issue by swharden** [spyder-ide/spyder#3978]
Currently in Preferences/Editor you can only show a single vertical line after a number of characters (79 is common). The [PEP 8 Style Guide for Python Code notes](https://www.python.org/dev/peps/pep-0008/#maximum-line-length) that...

> _... it is okay to increase the nominal line length from 80 to 100 characters ... provided that comments and docstrings are still wrapped at 72 characters._

Therefore, it would be immensely useful to have two configurable vertical lines rather than just one!

**Comment by ccordoba12** [comment]
This feature is already in our master branch and will be part of Spyder 4.0. Unfortunately, we plan to release 4.0 by the end of the year.

**Comment by mhaythornthwaite** [comment]
I have spyder 5 installed and I'm struggling to find this feature in the preferences tab, was this ever added? Thanks in advance!
