### ISSUE TITLE
Crash on initiating class instance in ipython console in spyder

### ISSUE THREAD

**Issue by BeateBier** [spyder-ide/spyder#3980]
## Description of your problem

On initiating a class and running the file in the ipython console I get thrown to the internal console with an error (see section "What is the expected output? What do you see instead?").

**What steps will reproduce the problem?**

I run the following program in the ipython console.
`class Test():`
`      def __init__(self):`
`		self.i = 10`
`		self.phi = 90.`
`
test = Test()`

(Intendations are correct, I just don't know how to write this here.)

**What is the expected output? What do you see instead?**
expected output:
I expect the program to run smoothly and the object `test` to be available in the ipython console.

instead:
The program runs and I get thrown to the internal console which shows the following error message:

> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
>     handler(msg)
>   File "/usr/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/namespacebrowser.py", line 189, in _handle_execute_reply
>     self.handle_exec_method(msg)
>   File "/usr/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/shell.py", line 242, in handle_exec_method
>     properties = ast.literal_eval(data['text/plain'])
> TypeError: 'NoneType' object has no attribute '`__getitem__`'

After that, the ipython console is still working, the `test`-object is available, but after every command, I get thrown back to the internal console with the same error message

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.2 
* Python Version: 2.7.12
* Operating system: OpenSuse 13.2

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.0.0 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.5.7 (OK)
psutil >=0.3     :  2.1.2 (OK)
pyflakes >=0.5.0 :  0.8.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.2.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by BeateBier** [comment]
> After that, the ipython console is still working, the test-object is available, but after every command, I get thrown back to the internal console with the same error message

But the command is executed.

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in Spyder 3.1 (to be released in a couple of hours).
