### ISSUE TITLE
tabs font size is tiny unreadable

### ISSUE THREAD

**Issue by panchekha** [spyder-ide/spyder#3981]
## Description

**What steps will reproduce the problem?**

1. The font size on tabs only and on path bar above the tabs are tiny, impossible to read, do not react to windows font size, do not react to preference font size.

**What is the expected output? What do you see instead?**

Be able to read tabs
**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.2 
* Python Version: 3.4.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.5.4 (OK)


```

**Comment by panchekha** [comment]
![image](https://cloud.githubusercontent.com/assets/20606249/22039495/71d8de8a-dcb4-11e6-8d95-c517211d1979.png)

**Comment by geshter** [comment]
I have the same problem but the proposed solution does not solve it.

Spyder version 3.2.4 and Python 3.6.3

**Comment by hickman-santini** [comment]
Ditto @geshter.  Seems like [https://github.com/spyder-ide/spyder/issues/4316](url) would help, but (you guessed it) I can't read the text in the preferences box. Can anyone help with this issue???

**Comment by csbrace** [comment]
I know I'm a little late, but for me the issue seemed to be an issue with QT itself, which can only be fixed by mucking into the config file and telling it to ignore high DPI scaling. Do I know why? No. But if you ended up on this thread like me, here's the solution: https://stackoverflow.com/a/48141311/11627783

**Comment by Pranay-Git** [comment]
did anyone solved it ? facing the same issue

**Comment by ccordoba12** [comment]
This should be fixed in Spyder 6, to be released in a couple of months. For Spyder 5, you need to play with high dpi options in

    Tools > Preferences > Application > Interface

to see if that helps.
