### ISSUE TITLE
When in replace menu tab key does not cycle through buttons

### ISSUE THREAD

**Issue by martinwk** [spyder-ide/spyder#3991]
I have updated to spyder 3.0.2 and found that pressing <TAB> does not cycle through the different buttons and fields in the replace pane; this used to be the case in the previous version I used (2.something)

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez take a look at this one

**Comment by DStauffman** [comment]
I think this is closely related to https://github.com/spyder-ide/spyder/issues/3674

**Comment by ccordoba12** [comment]
You're right. Closing as a duplicate of issue #3674.
