### ISSUE TITLE
Remove unnecessary newlines in run cell

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#3992]
When running a cell, the cell that is actually ran in the ipython contains 2 redundant newlines in the end.
this is inconvenient  because it reduces the amount of text you see in ipython console.
 here is a fix:
in: `spyder/widgets/sourcecode/base.py `in the function `get_cell_as_executable_code`
instead of 
`return text`
write:
`return text.rstrip()`

This will also remove endlines added by the user which I think is actually a desired behavior anyway (for example, I tend to add newlines just to visually separate between one cell and the next one)

If you think this is good, I can create a pull request with the fix.

Note: right now, the newlines which are in the beginning of the cell are stripped anyway, so removing the trailing newlines just seems natural.

**Comment by ccordoba12** [comment]
I think at least one new line is needed to get the console to evaluate the cell.

But if you make that work, please send us a pull request :-)

**Comment by talkaminker** [comment]
I tested it before opening the issue, it works. I will add a pull request

**Comment by goanpeca** [comment]
@ccordoba12 this should beagainst what branch ?

**Comment by ccordoba12** [comment]
It's a very simple change, so I'd say `3.1.x`.

----

We need to write a guide about how we manage our branches so that it's easier for external contributors to work with us.
