### ISSUE TITLE
Ctrl+F should show the number of appearances in the file as #current/#total

### ISSUE THREAD

**Issue by mariacamilaremolinagutierrez** [spyder-ide/spyder#4001]
For example:

a e i o u **a** e a e i  

Ctrl+F -> "a" 2/3

**Comment by ccordoba12** [comment]
I don't follow exactly what you mean. Could you post a screenshot to see how this looks in other editors/IDEs?

**Comment by mariacamilaremolinagutierrez** [comment]
@ccordoba12 Yeah, absolutely, something like the red circle:

![image](https://cloud.githubusercontent.com/assets/3608776/22127516/28a00650-de6a-11e6-9f1f-af87f8dadb9f.png)

**Comment by ccordoba12** [comment]
Do you want to work on this?

**Comment by mariacamilaremolinagutierrez** [comment]
Yes, I'm assigning it to myself now
