### ISSUE TITLE
renaming a file to change case launches overwrite warning

### ISSUE THREAD

**Issue by swharden** [spyder-ide/spyder#4004]
If you try to rename a file in the _file explorer_ window just to change its case (i.e, `demo02.jpg` to `demo02.JPG`) it thinks you're trying to overwrite a file when you're really not and throws this error

![image](https://cloud.githubusercontent.com/assets/4165489/22115430/f4449062-de3a-11e6-9a2c-35462d1a53e0.png)

**Comment by ccordoba12** [comment]
I think this happens because Windows file system is not case sensitive (in case you're using Windows :-)

**Comment by ccordoba12** [comment]
Closing because of lack of response.
