### ISSUE TITLE
Edit menu items greyed out after update to Spyder 3.1.0

### ISSUE THREAD

**Issue by chipmuenk** [spyder-ide/spyder#4012]
## Description of your problem
After updating to Spyder 3.1.0, all items in the "Edit" dropdown menu are greyed out and unselectable. The keyboard shortcuts (e.g. CTRL-Z, CTRL-C, CTRL-V, ...) do work, however. 
**What steps will reproduce the problem?**

1. Update from version 3.0.1 to 3.1.0 via conda update (including all additional updates requested by conda)
2. Start Spyder, open an arbitrary file
3. Click on "Edit" to see the pulldown menu

**What is the expected output? What do you see instead?**
The entries should be activated, instead they are greyed out and cannot be selected.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.0
* Python Version:  3.5.2
* Operating system: Win7, 64 bit
* PyQt 5.6.0

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
You're totally right. I don't how that happened :-)

@rlaverde, could you take a look at this one and have a PR for today? It doesn't seem like a hard issue. the thing is we have a signal somewhere that activates/deactivates the entries in the Edit menu depending on whether there's text select on the Editor or not.

I think we should remove that signal and make those entries activate all the time.

**Comment by chipmuenk** [comment]
It's a good motivation to learn more keyboard shortcuts :-P
