### ISSUE TITLE
save file doesn't work on new files unless you change them

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#4016]
## Description

**What steps will reproduce the problem?**
1. hit ctrl+N to create a new file
2. hit ctrl+s to save the file

**What is the expected output? What do you see instead?**
I expect for the savefile  prompt to open. Nothing happens

**Please provide any additional information below**
I have to make a change to the new file (like adding a space) in order for the savefile box to appear.
I guess you guys check if the file have changed, and if not, not save it. I think new files should default to being "dirty"

## Version and main components

* Spyder Version: 3.1.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.1.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.3.5 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.1.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Well, you need to change them somehow to save them. At least that's our rationale to make things work like this.

Else you'd be saving a template file and nothing else :-)

**Comment by talkaminker** [comment]
My general rational is that every single editing program on earth does allows you to save just after ctrl+N.

My second rational is that for a year I thought spyder's new file command was broken because I tend to save new files I create because I want to change their name BEFORE I start to write code.

**Comment by goanpeca** [comment]
@ccordoba12 I agree with @talkaminker, a new file should open in `dirty` state

**Comment by ccordoba12** [comment]
Ok, fair enough. @rlaverde, please work on this one.

**Comment by rlaverde** [comment]
> a new file should open in dirty state

that isn't the expected behavior, if you create a new file and then close it (Ctrl+N then Ctrl+W), It will ask if you want to save changes.

**Comment by goanpeca** [comment]
>that isn't the expected behavior, if you create a new file and then close it (Ctrl+N then Ctrl+W), It will ask if you want to save changes.

On close the behavior should be:

Yes, if it is newly created and unchanged we should not ask to save it. If it newly created and changed ask!

On the open interface:

If a newly created one the save action should be available (ctrl+s))

**Comment by talkaminker** [comment]
@rlaverde you are right. hmm.
I guess the correct way is then have a special `new_file` flag. sublime,atom,vscode all do it correctly but I don't know if they special cased this one or solved it in a more elegant way.

**Comment by rlaverde** [comment]
> If a newly created one the save action should be available (ctrl+s))

@goanpeca I haven't think about that, I will change file state to dirty and add a condition to close function.

> I guess the correct way is then have a special new_file flag

This already exists, but the modified state when opening a new file was missing.


Also a quick workaround while we fix it is to press `Ctrl+Shift+S` instead of `Ctrl+S`

**Comment by goanpeca** [comment]
>Ctrl+Shift+S

Yes probably, but Ctrl+S should do, or I would like that behavior.

The behavior should be dont bother me if I did not do anything with a new file, but bother me if I actively want to save an empty one or if I am closing and had already changed a new file content

**Comment by rlaverde** [comment]
> Yes probably, but Ctrl+S should do, or I would like that behavior.

Yes, It was just a workaround for @talkaminker workflow

> I will change file state to dirty and add a condition to close function.

File state shouldn't be dirty (a new file isn't modified) maybe it could change other behaviors, also it will need a new variable just to keep track if the file was just created and didn't modified (`newly_created` is used to keep track if a file was created and didn't save it).

**Comment by goanpeca** [comment]
Ok, maybe we need an extra variable to track that then
