### ISSUE TITLE
Feature request: use the new qt5 WebEngine to render html in ipython console

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#4017]
Originally qtconsole stopped showing html because qt4 WebKit had a shitty support for complex html. Now that qt5 ships with the new WebEngine which as I understand is just chrome in disguise, can the console render html repr of object with `_repr_html_`. Then main motivator is pandas dataframe.

Just a thought.

**Comment by ccordoba12** [comment]
There's already an open issue in qtconsole about this: https://github.com/jupyter/qtconsole/issues/165

There's nothing we can do about it in our side, so it has to be solved in qtconsole instead.
