### ISSUE TITLE
Reopen  -- Add "run selection" icon

### ISSUE THREAD

**Issue by sibojan** [spyder-ide/spyder#4020]
I think this needs to be considered.  Just reoopned this.

ahed87 commented on Jan 10, 2016
Hi,
an enhancement idea triggered by issue #2490
a small (or large) suggestion related to this area would be to add one run icon.
I quite often select a piece of code and use the right-click -> "run selection or current line".
When doing that I typically have made the selection with keys, scrolled a bit with the mouse and that's when I miss an icon to press to run the selected area. I quite often end up pressing the regular run-icon when I really want to run a selection, since it's soo much easier than doing the right-click, especially if that area is out of focus in the editor.

I have no strong opinions of how such an icon would look like (like today's run with an 's' in it?), and were it should be placed (inbetween current run and runcell icons?).

**Comment by ccordoba12** [comment]
@sibojan, I agree with reopening this one. and adding this icon to our Run toolbar.

@mariacamilaremolinagutierrez, please work on this one. Just add the *Run selection* button between *Run current cell and advance* and *Run again last file*.

I think we should also remove *Run settings* which is not so used as the others.

**Comment by sibojan** [comment]
Thank you guys for your support.   **Run Settings** is truly rarely used.  Looking at other popular ODE/lauagues, e.g. Rstudio, Matlab, none of them put the **Run settings** at  the most important place of toolbar. I migrated from R to python,  having been using **Run Selected** quite frequently in the past. I don't think that I am alone on this case.

**Comment by ccordoba12** [comment]
@sibojan, thanks for bringing this to our attention again :-)
