### ISSUE TITLE
Fix CI so the correct branch is used with ciocheck 

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4023]

**Comment by ccordoba12** [comment]
We need to fix this as soon as possible. @goanpeca, do you have time to this weekend? Else I'm going to deactivate ciocheck because it's essentially broken.

**Comment by goanpeca** [comment]
I can do it tomorrow

**Comment by ccordoba12** [comment]
Yes, please! Thanks a lot for doing it :-)

**Comment by goanpeca** [comment]
But, there I will need to add some script to query the github api for the right branch, cause on circle ci for example AFAICT there is no way to get the branch against which a PR was made :-|

**Comment by ccordoba12** [comment]
What about `CIRCLE_BRANCH`?

https://circleci.com/docs/environment-variables/

**Comment by goanpeca** [comment]
If its a fork, it gives you the branch that is being merged, not the branch it is merging against.

**Comment by ccordoba12** [comment]
Ok, no prob :-)

I think this has more priority (for 3.1.1) than starting to test with Python 3.6, so if you could it today, it'd be better.

**Comment by goanpeca** [comment]
Today no way, I am off for the day now is 🍻 ⌚️

**Comment by ccordoba12** [comment]
Ok, then I'll leave 3.1.1 for tomorrow ;-)

**Comment by ccordoba12** [comment]
I'm going to disable ciocheck to release 3.1.1. Please enable it as soon as you can :-)
