### ISSUE TITLE
Intellisense/code completion does not work across scripts

### ISSUE THREAD

**Issue by hendrikvanb** [spyder-ide/spyder#4024]
## Description of your problem
It seems that Spyder's intellisense/code completion does not work across scripts and/or the console within the same project or Spyder session. While one can call the packages imported or variables defined in, for example, *Script1.py* from *Script2.py*, the intellisense/code completion pertaining to those packages and/or variables only works in *Script1.py* and not in *Script2.py*. The intellisense/code completion pertaining to those packages and/or variables also appears to work in the IPython console where the scripts are executed. However, while any packages called or variables defined in the console can be called successfully from either *Script1.py* or *Script2.py*, the intellisense/code completion pertaining to those packages and/or variables will only work in the console.

**What steps will reproduce the problem?**

1.  Create a new project with two scripts, *Script1.py*  and *Script2.py*.
2.  In the IPython console, execute the lines `import matplotlib` and `variable0 = 0`. In *Script1.py*,  write and subsequently run the lines `import pandas` and `variable1 = 0`. In *Script2.py*, write and subsequently run the lines `import numpy` and `variable2 = 0`.
3. Note that the intellisense in the IPython console is "aware" of all three packages (`matplotlib`, `pandas`, and `numpy`) and all three variables (`variable0`, `variable1`, and `variable2`). The intellisense in *Script1.py* is only "aware" of the package `pandas` and the variable `variable1`. The intellisense in *Script2.py* is only "aware" of the package `numpy` and the variable `variable2`.

**What is the expected output? What do you see instead?**
Since all of the packages imported (`matplotlib`, `pandas`, and `numpy`) and variables defined (`variable0`, `variable1`, and `variable2`) can be called from the Ipython console, *Script1.py*, and *Script2.py*, regardless of where they were imported/defined, I would have expected the intellisense/code completion to do the same.  Apparently, it does not.  Is this the intended behaviour, or a bug?

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.0 
* Python Version: 3.5.2 :: Anaconda 4.2.0 (64-bit)
* Operating system: Windows 10 Professional

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> The intellisense in Script1.py is only "aware" of the package pandas and the variable variable1. The intellisense in Script2.py is only "aware" of the package numpy and the variable variable2.

This is the expected behavior, i.e. the Editor and the IPython console use different completion mechanisms and neither is aware of the other. In other words, the Editor doesn't use any libraries/variables defined in a console, and viceversa.

In the Editor we can only offer completions for things that have already been defined/imported in a file. This is even an advantage for you because it will let you avoid creating code that depends on the *current* state of variables/libraries in a console, and that instead will work correctly in any other console or outside of Spyder too.
