### ISSUE TITLE
Inconsistent icon for "Find symbols in file..."

### ISSUE THREAD

**Issue by sound-fx** [spyder-ide/spyder#4030]
## Description of your problem
The "File: Symbol finder..." menu item has an equivalent button on the toolbar and also in a drop down menu under a "sprocket" or "gear" button along the right edge of the Editor pane next to the tabs.  In the first two instances, a '@' icon is associated with the command.  In the latter instance, however, a bullet-list icon is associated with the command -- the same icon that is associated with the "File switcher..." command.

**What steps will reproduce the problem?**

1. Click the "gear" button to the right of the tabs in the Editor pane, at the right edge.
2. Observe in the drop-down menu the two commands "File switcher..." and "Find symbols in file...".
3. In this drop-down menu, both of these commands appear with the same icon -- a bullet-list icon.  This differs from other instances (e.g., under the File menu and on the Toolbar), where the "Find symbols in file..." command has a '@' icon. 

**What is the expected output? What do you see instead?**
I expect the same '@' icon to appear in all three instances of this command.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.0
* Python Version: 2.7.13
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one :-)
