### ISSUE TITLE
How do I install this version

### ISSUE THREAD

**Issue by Chimsom** [spyder-ide/spyder#4032]
I am sorry, I a newbie on this platform, and also with python and spyder

## Description of your problem
following the instructions, I still can't get to install or update the 3.0.0 version
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
What do I do with the downloaded source code file...
Or do I use it to update my spyder version
## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5
* Operating system: Windows 64bits

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Just follow the instructions present in our Readme:

https://github.com/spyder-ide/spyder#installation

**Comment by ccordoba12** [comment]
Ok, I see you're following our instructions. But you don't say how you installed Spyder. Without that info we can't help you further.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
