### ISSUE TITLE
Fontconfig error

### ISSUE THREAD

**Issue by Atcold** [spyder-ide/spyder#4035]
## Description

**What steps will reproduce the problem?**

1. Run `spyder` from *Terminal*, in Ubuntu 16.04.

**What is the expected output? What do you see instead?**

The program opens up, but I get the following error messages:
```
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
```

**Please provide any additional information below**

If I browse the *Plain text font* I get on the terminal the following lines
```
Failed to compute left/right minimum bearings for "decsess.pcf"
Failed to compute left/right minimum bearings for "cursor.pcf"
Failed to compute left/right minimum bearings for "deccurs.pcf"
Failed to compute left/right minimum bearings for "micro.pcf"
```

Here is how the whole looks like.
![odd-font](https://cloud.githubusercontent.com/assets/2119355/22224268/0df60078-e18c-11e6-968d-e4154267ca3d.png)

## Version and main components

* Spyder Version: 3.1.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
@mingwandroid, this looks like a change in the Qt Anaconda packages. Could you give us a hand here? Thanks :-)

**Comment by harryhobson** [comment]
I also get

`Fontconfig error: Cannot load default config file`

but not the 'minimum bearings' warnings

I'm using Anaconda as well. Defaults fonts have changed for me, I'm unsure what they were before the update.

## Version and main components

* Spyder Version: 3.1.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by mingwandroid** [comment]
Yeah I'm on it.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by Atcold** [comment]
Just for completeness, `matplotlib` is complaining about the same thing.

**Comment by mingwandroid** [comment]
`conda update fontconfig` should fix this.

**Comment by harryhobson** [comment]
update fixes message for me.

more info at https://github.com/conda/conda/issues/4416

**Comment by ccordoba12** [comment]
Thanks @mingwandroid for the quick response :-)

**Comment by Atcold** [comment]
@mingwandroid, worked for me as well. Thank you!
Sorry for the late reply, but I caught a flu and got back to my desk only today.
Would you mind sharing the fixing commit hash?

**Comment by Atcold** [comment]
@ccordoba12, oh, thank you. I thought it was all open sourced...
