### ISSUE TITLE
Sorting order of profiler is wrong

### ISSUE THREAD

**Issue by markusr** [spyder-ide/spyder#4039]
## Description of your problem

**What steps will reproduce the problem?**

1. Run the profiler
2. Look at the results

**What is the expected output? What do you see instead?**

![grafik](https://cloud.githubusercontent.com/assets/1866703/22251819/6d414aa4-e24c-11e6-83f3-5b65f4be1c28.png)

I would expect that the ```test_big``` function is the first entry as it takes 10 sec.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.1
* Python Version: 3.5.2 
* Operating system: Ubuntu 16.04

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, please work on this one.

**Comment by adrianschlatter** [comment]
Can confirm in 3.1.4: The sort order of Total Time and Local Time is alphabetical instead of numerical.

**Comment by ccordoba12** [comment]
Thanks, we'll take a look at this after we release Spyder 3.2 (in a couple of weeks).
