### ISSUE TITLE
Spyder becomes unresponsive while loading a large source file

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#404]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2010-10-06T10:32:58Z_

I have a generated python file that contains 2251 classes and is ~37000 lines long.  Spyder takes a long time (a minute or more) to load the file and become responsive and allow editing, etc.  It would be nice if parsing for the outline, syntax checking, etc. on large files was done at low priority in the background so the file could be immediately browsed, searched, and/or edited while the parsing takes place.

What version of the product are you using?  On what operating system?
spyder 2.0.0beta4, Windows XP, python 2.6.1

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=404_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-10-07T13:22:34Z_

I'm not sure it can be done easily but I'll see what I can do.

**Summary:** Spyder becomes unresponsive while loading a large source file  
  **Status:** Accepted  
  **Labels:** -Type-Defect -Priority-Medium Type-Enhancement Priority-Low

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-15T13:23:24Z_

**Labels:** -Priority-Low Priority-Medium Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:14:34Z_

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-15T07:16:23Z_

**Labels:** -Milestone-Release2.1 Milestone-Release2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:49:23Z_

**Labels:** -Milestone-Release2.2 Milestone-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:58:26Z_

**Labels:** -Milestone-v2.2 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:13:52Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-11T08:53:13Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:57:32Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by goanpeca** [comment]
You opened this @blink1073?

**Comment by blink1073** [comment]
I just tried opening a 32000 line file on Windows 7 64 bit and it works much better.

**Comment by ccordoba12** [comment]
@goanpeca, that Steve is not @blink1073, but just a guy that reported a lot of issues a very long time ago and then mentioned that he switched to another IDE.
