### ISSUE TITLE
Create a way to add tests for the whole app

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4041]
This will need a fixture that initializes the app with a basic configuration, and maybe didn't display it (I'm not sure if it will be possible).

This is needed for add test to code like #4031

**Comment by goanpeca** [comment]
We need to display to be able to interact with it

**Comment by ccordoba12** [comment]
@andfoy, this is needed to add a test for PR #3956.

**Comment by andfoy** [comment]
Is this related to integration-like-tests?

**Comment by ccordoba12** [comment]
What do you mean?

**Comment by andfoy** [comment]
I refer if we want to check the interaction between two or more components of the program

**Comment by ccordoba12** [comment]
Yep, we need to add tests for the whole window to check for the interaction of two plugins.

**Comment by ccordoba12** [comment]
I solved this in PR #4106 (at last!)
