### ISSUE TITLE
Cannot connect to IPython kernel in Spyder

### ISSUE THREAD

**Issue by Stephen-X** [spyder-ide/spyder#4046]
## Description of your problem
Spyder cannot connect to IPython kernel. The console will always show "kernel died" or "restarting kernel" if you try to restart.

**What steps will reproduce the problem?**

Just start Spyder in Windows.

**What is the expected output? What do you see instead?**
As described above.
![ipython kernel died](https://cloud.githubusercontent.com/assets/23654800/22277123/f17c36d2-e308-11e6-9264-ed63b5f1a225.png)

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.5.2 (Anaconda custom 64-bit)
* Operating system: Windows 10 64-bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
You need to add a rule to your firewall/antivirus to let Spyder create external processes (needed by our IPython consoles to work).

Here you can find a description of how to do that for Kaspersky:

https://github.com/spyder-ide/spyder/issues/3899#issuecomment-271031485

**Comment by Stephen-X** [comment]
Hi ccordoba12, this is indeed the problem of the antivirus software Kaspersky. Sorry I didn't find that post earlier. However, the solution from https://github.com/spyder-ide/spyder/issues/3899#issuecomment-271031485 is not working with the newest version of Kaspersky (2017). It seems that the kernel will start only when Kaspersky is completely disabled.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. We'll add a warning about Kaspersky in a future release of Spyder ; -)
