### ISSUE TITLE
Scrolling of code is very slow and not responsive enough to be usable

### ISSUE THREAD

**Issue by alvinwng** [spyder-ide/spyder#4047]
## Scrolling of code is very slow and not responsive enough to be usable

**What steps will reproduce the problem?**

Scrolling some code with around 100 lines in the editor panel with the scroll bar produces the problem. I can see the code scrolling line by line to the destination but it takes 1-2 seconds. I tested it on some code with 1200 lines and it would take 8 seconds for this line by line scrolling to reach the bottom of the code.

**What is the expected output? What do you see instead?**

The updating of the screen should follow the mouse cursor fast enough. It should not be updated only one line at a time. This way, the displayed code portion would seriously lag behind the mouse and the scroll bar becomes useless. I had to use the Page Down button instead.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7
* Operating system: Linux debian 4.8.0-0.bpo.2-amd64

## Dependencies

jedi >=0.8.1     :  0.10.0 (OK)
matplotlib >=1.0 :  1.4.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.8.2 (OK)
pandas >=0.13.1  :  0.14.1 (OK)
pep8 >=0.6       :  1.5.7 (OK)
psutil >=0.3     :  2.1.1 (OK)
pyflakes >=0.5.0 :  0.8.1 (OK)
pygments >=2.0   :  2.0.1 (OK)
pylint >=0.25    :  1.3.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.2 (OK)
sphinx >=0.6.6   :  1.2.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Are you using Spyder with Qt4 or Qt5?

**Comment by ccordoba12** [comment]
By the way, I can't see any delay using Qt5. I don't think the problem is in Spyder but in Qt (Qt5 is much faster than Qt4).

**Comment by alvinwng** [comment]
I chose PyQt5 in Qt-Python Bindings for the External modules settings. I tried PyQt4 and PySide and the results are the same. The scrolling of the File explorer and Python console has no problem at all.

**Comment by alvinwng** [comment]
Seems this setting is affecting libraries like Matplotlib? I have the python-pyqt5 package installed on Debian though. Is there some way to explicit set to use Qt5?

**Comment by ccordoba12** [comment]
What file types have the problem? All of them? Or non-Python file types?

**Comment by ccordoba12** [comment]
> Is there some way to explicit set to use Qt5?

For Spyder you can set

    export QT_API=pyqt5

**Comment by alvinwng** [comment]
I just tried this option and the scrolling is still lagging much behind the cursor. Yes, all file types have this problem for the Editor panel.

**Comment by ccordoba12** [comment]
I'm using Kubuntu 16.10 and its Qt5 libraries, so I don't know how else yo help you, sorry.

**Comment by ccordoba12** [comment]
In any case, if the problem also appears in Matplotlib, then it's not related to Spyder per se. So I doubt we can do something to fix it.

**Comment by alvinwng** [comment]
Maybe I'll try to see at which version it starts to break. I have used Spyder 2 for a long time and scrolling does not lag at all. The editor interface looks the same though. But thanks for your help and suggestions.

**Comment by alvinwng** [comment]
I upgraded to python-pyqt5 under Debian unstable (sid) and the scrolling problem was solved. Unfortunately it had to pull many more packages from the unstable repository. But I think the problem is related to using an older version of Qt5 library. I am closing the issue now.
