### ISSUE TITLE
qtpy.PythonQtError: No Qt bindings could be found . qt5 doesn't fix it

### ISSUE THREAD

**Issue by borriquear** [spyder-ide/spyder#4048]
Spyder stop working, I get error the error message :
_Traceback (most recent call last):
  File "/usr/local/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/local/lib/python2.7/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/usr/local/lib/python2.7/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found_

* Spyder Version: '3.1.2'
qt5: stable 5.7.1
* Python Version: Python 2.7.10
* Operating system: macOS Sierra

## Dependencies

Requirement already up-to-date: spyder in /usr/local/lib/python2.7/site-packages
Requirement already up-to-date: pyzmq in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: numpydoc in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: sphinx in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: chardet>=2.0.0 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: pep8 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: qtpy>=1.1.0 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: rope>=0.9.4 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: pygments>=2.0 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: qtconsole>=4.2.0 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: jedi in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: pylint in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: nbconvert in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: pyflakes in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: qtawesome>=0.4.1 in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: pickleshare in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: psutil in /usr/local/lib/python2.7/site-packages (from spyder)
Requirement already up-to-date: snowballstemmer>=1.1 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: Jinja2>=2.3 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: alabaster<0.8,>=0.7 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: docutils>=0.11 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: imagesize in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: babel!=2.0,>=1.3 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: requests>=2.4.0 in /usr/local/lib/python2.7/site-packages (from sphinx->spyder)
Requirement already up-to-date: ipykernel>=4.1 in /usr/local/lib/python2.7/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: jupyter-core in /usr/local/lib/python2.7/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: traitlets in /usr/local/lib/python2.7/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: jupyter-client>=4.1 in /usr/local/lib/python2.7/site-packages (from qtconsole>=4.2.0->spyder)
Requirement already up-to-date: mccabe in /usr/local/lib/python2.7/site-packages (from pylint->spyder)
Requirement already up-to-date: isort>=4.2.5 in /usr/local/lib/python2.7/site-packages (from pylint->spyder)
Requirement already up-to-date: astroid<1.5.0,>=1.4.5 in /usr/local/lib/python2.7/site-packages (from pylint->spyder)
Requirement already up-to-date: configparser; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from pylint->spyder)
Requirement already up-to-date: backports.functools-lru-cache; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from pylint->spyder)
Requirement already up-to-date: pandocfilters>=1.4.1 in /usr/local/lib/python2.7/site-packages (from nbconvert->spyder)
Requirement already up-to-date: bleach in /usr/local/lib/python2.7/site-packages (from nbconvert->spyder)
Requirement already up-to-date: testpath in /usr/local/lib/python2.7/site-packages (from nbconvert->spyder)
Requirement already up-to-date: mistune!=0.6 in /usr/local/lib/python2.7/site-packages (from nbconvert->spyder)
Requirement already up-to-date: nbformat in /usr/local/lib/python2.7/site-packages (from nbconvert->spyder)
Requirement already up-to-date: entrypoints>=0.2.2 in /usr/local/lib/python2.7/site-packages (from nbconvert->spyder)
Requirement already up-to-date: pathlib2; python_version in "2.6 2.7 3.2 3.3" in /usr/local/lib/python2.7/site-packages (from pickleshare->spyder)
Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.3->sphinx->spyder)
Requirement already up-to-date: pytz>=0a in /usr/local/lib/python2.7/site-packages (from babel!=2.0,>=1.3->sphinx->spyder)
Requirement already up-to-date: tornado>=4.0 in /usr/local/lib/python2.7/site-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: ipython>=4.0.0 in /usr/local/lib/python2.7/site-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: decorator in /usr/local/lib/python2.7/site-packages (from traitlets->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: ipython-genutils in /usr/local/lib/python2.7/site-packages (from traitlets->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: enum34; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from traitlets->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: wrapt in /usr/local/lib/python2.7/site-packages (from astroid<1.5.0,>=1.4.5->pylint->spyder)
Requirement already up-to-date: lazy-object-proxy in /usr/local/lib/python2.7/site-packages (from astroid<1.5.0,>=1.4.5->pylint->spyder)
Requirement already up-to-date: html5lib!=0.9999,!=0.99999,<0.99999999,>=0.999 in /usr/local/lib/python2.7/site-packages (from bleach->nbconvert->spyder)
Requirement already up-to-date: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python2.7/site-packages (from nbformat->nbconvert->spyder)
Requirement already up-to-date: scandir; python_version < "3.5" in /usr/local/lib/python2.7/site-packages (from pathlib2; python_version in "2.6 2.7 3.2 3.3"->pickleshare->spyder)
Requirement already up-to-date: backports-abc>=0.4 in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: singledispatch in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: certifi in /usr/local/lib/python2.7/site-packages (from tornado>=4.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: setuptools>=18.5 in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: appnope; sys_platform == "darwin" in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: pexpect; sys_platform != "win32" in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: prompt-toolkit<2.0.0,>=1.0.3 in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: simplegeneric>0.8 in /usr/local/lib/python2.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: functools32; python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from jsonschema!=2.5.0,>=2.4->nbformat->nbconvert->spyder)
Requirement already up-to-date: appdirs>=1.4.0 in /usr/local/lib/python2.7/site-packages (from setuptools>=18.5->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: packaging>=16.8 in /usr/local/lib/python2.7/site-packages (from setuptools>=18.5->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: ptyprocess>=0.5 in /usr/local/lib/python2.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: wcwidth in /usr/local/lib/python2.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.3->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
Requirement already up-to-date: pyparsing in /usr/local/lib/python2.7/site-packages (from packaging>=16.8->setuptools>=18.5->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)

**Comment by ccordoba12** [comment]
Just run

    pip install pyqt5

to install some Python bindings

**Comment by nitinmathur5** [comment]
I am on CentOS 6.8. 
I installed miniconda. When i start spyder, I get the same  error message "qtpy.PythonQtError: No Qt bindings could be found".
I try to install pyqt5 (and pyqt4) using pip install pyqt5
I get the error  "Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5"
Can someone point me, what am i doing wrong ?

[root@fc_10_81_159_122 bin]# spyder
Traceback (most recent call last):
  File "/root/miniconda2/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/root/miniconda2/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/root/miniconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/root/miniconda2/lib/python2.7/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/root/miniconda2/lib/python2.7/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
[root@fc_10_81_159_122 bin]# pip install pyqt5
Collecting pyqt5
  Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5
[root@fc_10_81_159_122 bin]#

**Comment by ccordoba12** [comment]
You shouldn't run `spyder` as root. Why do you need to do that?

**Comment by nitinmathur5** [comment]
Will running it as root cause any issues?

**Comment by jitseniesen** [comment]
According to http://pyqt.sourceforge.net/Docs/PyQt5/installation.html, you need to have Python 3.5 or higher in order to install PyQt5 using pip. But since you use miniconda, you can also try `conda install pyqt5`.

It's best to use root as little as possible, mostly for security reasons, but also because that's how almost all Linux computers are set up - so if there are issues with running spyder as root, we probably don't know about them.

**Comment by ccordoba12** [comment]
@nitinmathur5, you're on your own here. Running graphical apps as root is discouraged in general for security reasons (as @jitseniesen said).
