### ISSUE TITLE
Importing spyder.plugins.editor segfaults

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#4049]
## Description of your problem

**What steps will reproduce the problem?**

1. `python -c "import spyder.plugins.editor"`

**What is the expected output? What do you see instead?**

I get a segmentation fault. I would expect an import never to lead to a segmentation fault.

**Please provide any additional information below**

This is [Debian bug 844601](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844601). Issue #4014 is related.

## Versions and main components

* Spyder Version: Current head, either master branch or 3.x branch. PR #4036 does **not** fix this issue.
* Python Version: 3.6.0 or 3.5.2
* Operating system: Debian Linux

**Comment by jitseniesen** [comment]
The stack trace is the same as listed in #4014. The crash happens in `QFontDatabase::addApplicationFont(QString const&)`, so the fix is probably similar.

Arguably, this issue is not as severe as #4014 because there is less reason for somebody to import `spyder.plugins.editor`.

**Comment by goanpeca** [comment]
@dalthviz could we add a test that tries to import each spyder file as @jitseshows? By recursively going trhough all python files in the spyder folder¿

**Comment by ccordoba12** [comment]
@goanpeca, I think @dalthviz's PR on QtAwesome is enough for now.

**Comment by goanpeca** [comment]
yep
