### ISSUE TITLE
Maximising current pane fails and hangs Spyder 3.1.x

### ISSUE THREAD

**Issue by pbentkowski** [spyder-ide/spyder#4052]
Icon "Maximise current pane" fails in maximising panes. An error prompt pops out instead. I'm running Spyder in Anaconda 3 environment. 

**What I'm doing:**
1. Open Spyder3 in version 3.1 (tested 3.1.0., 3.1.2) as normal 
2. Press "Maximise current pane" icon
3. It fails to open the pane
4. Click the icon again and it fails to return to the previous pane layout.

**Output:**
Instead of a workable pane of my selection an error console prompts displaying this message:
`Traceback (most recent call last):
  File "/home/piotr/anaconda3/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2202, in maximize_dockwidget
    self.last_plugin.dockwidget.toggleViewAction().setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'dockwidget'`

**Additional information**
I downgraded to Spyder 3.0.2 using Anaconda Navigator and maximisation of panes works fine. 

**Sofrware Versions**
I'm running Spyder in Anaconda 3 environment
* Spyder Version: 3.1.0 ; 3.1.2
* Python Version: Python 3.5.2 , Anaconda custom (64-bit)
* Operating system: Linux *ubuntu 14.04, 64-bit 
* Anaconda Version: conda 4.3.8

**Dependencies**:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by goanpeca** [comment]
@mariacamilaremolinagutierrez seems like we need to check `if self.last_plugin is not None` and act accordingly.
