### ISSUE TITLE
Add compatibility with html5lib 0.999999999 (nine digits), potentially fix security problem

### ISSUE THREAD

**Issue by hiccup7** [spyder-ide/spyder#4054]
Spyder 3.1.2 fails pip install with html5lib versions above 0.9999999 (seven digits).  See https://github.com/winpython/winpython/issues/471

There is a potential security problem with the old html5lib 0.9999999 (seven digits).  See https://github.com/mozilla/bleach/issues/229

**Comment by ccordoba12** [comment]
`html5lib` is not one of Spyder dependencies (it comes from nbconvert).

So there's nothing we can't do about it, sorry.
