### ISSUE TITLE
Spyder won't launch on windows 7 after anaconda2 install missing Qt "windows" in "".

### ISSUE THREAD

**Issue by StephenBrikiatis** [spyder-ide/spyder#4055]
I have tried to install the platform a few times now and it continues to result in this error.

The error window is attributed to pythonw.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 2.7.12
* Operating system: Windows 7 Service pack 1

I have seen similar errors that were closed before being resolved asking for the output of `qmake -query` so I will include that as well.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Stephen>qmake -query
QT_SYSROOT:
QT_INSTALL_PREFIX:C:/Users/ray/qt5-x64-2.7/envs/_build/Library
QT_INSTALL_ARCHDATA:C:/Users/ray/qt5-x64-2.7/envs/_build/Library
QT_INSTALL_DATA:C:/Users/ray/qt5-x64-2.7/envs/_build/Library
QT_INSTALL_DOCS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/doc
QT_INSTALL_HEADERS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/include/qt
QT_INSTALL_LIBS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/lib
QT_INSTALL_LIBEXECS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/bin
QT_INSTALL_BINS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/bin
QT_INSTALL_TESTS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/tests
QT_INSTALL_PLUGINS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/plugins
QT_INSTALL_IMPORTS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/imports
QT_INSTALL_QML:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/qml
QT_INSTALL_TRANSLATIONS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/translation
s
QT_INSTALL_CONFIGURATION:
QT_INSTALL_EXAMPLES:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/examples
QT_INSTALL_DEMOS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/examples
QT_HOST_PREFIX:C:/Users/ray/qt5-x64-2.7/envs/_build/Library
QT_HOST_DATA:C:/Users/ray/qt5-x64-2.7/envs/_build/Library
QT_HOST_BINS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/bin
QT_HOST_LIBS:C:/Users/ray/qt5-x64-2.7/envs/_build/Library/lib
QMAKE_SPEC:win32-msvc2008
QMAKE_XSPEC:win32-msvc2008
QMAKE_VERSION:3.0
QT_VERSION:5.6.0

**Comment by ccordoba12** [comment]
Please wait for Anaconda 4.3 (to be released tomorrow) and tray again

**Comment by ccordoba12** [comment]
Closing because this bug is too old.
