### ISSUE TITLE
Windows Spyder opening lot of TCP Ports

### ISSUE THREAD

**Issue by Harlool** [spyder-ide/spyder#4057]
Hi,

This is not an issue in itself but more about information I cannot find after some research.

I would need to know why Spyder (Windows in my case) is opening a lot of TCP ports in listening mode when running.

Thanks in advance.

**Comment by ccordoba12** [comment]
It's because Spyder consoles (both Python and IPython) run on external process and Spyder communicates with them through sockets.

Besides, Spyder creates a server to listen for other instances trying to open files in the main instance with a command like

    spyder /path/to/my/file.py

**Comment by Harlool** [comment]
Thank you for your answer !

Just a little precision, are these ports listening only on the loopback device (localhost) or also on the network?

**Comment by ccordoba12** [comment]
They are only listening on localhost.
