### ISSUE TITLE
Can't update spyder

### ISSUE THREAD

**Issue by nbmehar** [spyder-ide/spyder#4058]
I have installed Anaconda, was trying to update from 3.0.2 to 3.1.2. I typed the command conda update qt pyqt in cmd and when it successfully executed this command, i typed conda update spyder. Both the commands were successfully executed but still spyder was not updated. I run spyder from taskbar. 
![screenshot 38](https://cloud.githubusercontent.com/assets/25382206/22367730/2187cc00-e4a9-11e6-9ea3-d7e21cf128d7.png)
![screenshot 39](https://cloud.githubusercontent.com/assets/25382206/22367731/218f5344-e4a9-11e6-94cb-ddfc6612c1f6.png)
![screenshot 40](https://cloud.githubusercontent.com/assets/25382206/22367732/21955c30-e4a9-11e6-913b-ed7a6a20db53.png)

## Versions and main components

* Spyder Version: 3.0.2
* Python Version:3.5
* Operating system:windows 10

**Comment by ccordoba12** [comment]
What happens if you run it from a terminal with

    spyder

?

**Comment by nbmehar** [comment]
Still doesn't work. Tried to run it with command prompt.

**Comment by shl020** [comment]
Same issue here.

**Comment by cewebst2** [comment]
Same Issue Mac 10.12.2

**Comment by ccordoba12** [comment]
@nbmehar, your initial screenshot shows that you updated Spyder using `pip` but you're using Anaconda. Why did you do that instead of using `conda`?

If you did use `pip` instead of `conda` to update any package that can be installed/updated by `conda`, you most probably screwed up your installation.

So please uninstall Anaconda, remove all its directories (because leftover files will be left by `pip`) and reinstall again. Then try to see if Spyder is updated or not.

**Comment by nbmehar** [comment]
I uninstalled anaconda, downloaded it again and installed it. Now i can't run Spyder. 
![screenshot 46](https://cloud.githubusercontent.com/assets/25382206/22641018/1666860c-ec7b-11e6-887c-3021d1415235.png)

**Comment by ccordoba12** [comment]
@nbmehar, this error is going to be fixed in Anaconda 4.3.1. In the meantime, please do what I said in this comment

https://github.com/spyder-ide/spyder/issues/4087#issuecomment-276907543

to see if that fixes your problem.

**Comment by kings9** [comment]
@ccordoba12 ,I am using Anaconda 3-5.2.0 and I am trying to update my spyder from 3.2.8 to 3.3.0  using  **conda update spyder**. Although its showing the packages are successfully installed but I still see the spyder version is 3.2.8.
