### ISSUE TITLE
Spyder crash - segmentation fault (core dumped), caused when using code introspection

### ISSUE THREAD

**Issue by LeBarbouze** [spyder-ide/spyder#4059]
## Description of your problem

**What steps will reproduce the problem?**

1.  Open following script in Spyder editor
```python
#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 27 13:33:13 2017

@author: joachim
"""


class TestClass(object):

    def __call__(self, *args):
        return self.func(*args)


class TestSubclass(TestClass):

    def __init__(self, var=5):
        self.var = var
        return

    def func(self, testvar):
        if testvar < self.var:
            return 'lesser'
        else:
            return 'greater'


test = TestSubclass(var=5)

# My Spyder crashes when line below is uncommented and I try to press Maj + Tab within parenthesis
# output = test()
```
2. uncomment last line and try to use the Maj + Tab suggestion of arguments

**What is the expected output? What do you see instead?**

I expect to see the following suggestion `test(self, *args)` in the editor part. This is what I see in the ipython console if I leave the last line commented and write it instead in the console.

Instead, Spyder crashes with this in my terminal "Segmentation fault (core dumped) spyder".

**Please provide any additional information below**

It started to crash when I updated to 3.1.2, together with upgrading a number of other packages. However returning to spyder==3.1.0, which I think I was using before (I missed the 3.1.1 upgrade, sorry :), does not solve the problem. Which may indicate that the problem is from another updated package (that allows code introspection, though I don't know how it works).

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.12
* Operating system: ubuntu 16.04 LTS

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
@LeBarbouze I couldn't reproduce the error reported, can we have more information about the crash scenario?
![captura de pantalla de 2017-01-28 16-51-30](https://cloud.githubusercontent.com/assets/1878982/22400126/e566ffd4-e57a-11e6-8dcc-0efb36bee374.png)

**Comment by LeBarbouze** [comment]
Hi, thanks for your reply.

About the crash scenario. The problem appeared after I upgraded Spyder to 3.1.2 (from 3.1.0), altogether with other packages. I am using an Anaconda install, and I upgraded using pip (maybe I shouldn't? I don't know).

Please find below the list of files that were modified on the same day I updated spyder, to depth one in the `anaconda2/lib/python2.7/site-packages/` (sorry for the long list):

```./appdirs-1.4.0.dist-info
./appdirs.py
./appdirs.pyc
./astroid
./astroid-1.4.9.dist-info
./bleach
./bleach-1.5.0.dist-info
./chardet
./chardet-2.3.0.dist-info
./clint.egg-link
./decorator-4.0.11.dist-info
./decorator.py
./decorator.pyc
./docutils-0.13.1.dist-info
./easy-install.pth
./easy_install.py
./easy_install.pyc
./entrypoints-0.2.2.dist-info
./entrypoints.py
./entrypoints.pyc
./html5lib
./html5lib-0.9999999.dist-info
./jinja2
./Jinja2-2.9.4.dist-info
./jupyter_core-4.2.1.dist-info
./jupyter.py
./jupyter.pyc
./matplotlib
./matplotlib-2.0.0.dist-info
./matplotlib-2.0.0-py2.7-nspkg.pth
./mccabe-0.6.1.dist-info
./mccabe.py
./mccabe.pyc
./mpl_toolkits
./nbconvert-5.1.1.dist-info
./nbformat-4.2.0.dist-info
./numpy
./numpy-1.12.0.dist-info
./numpydoc
./numpydoc-0.6.0.dist-info
./packaging
./packaging-16.8.dist-info
./pandocfilters-1.4.1.dist-info
./pandocfilters.py
./pandocfilters.pyc
./pathlib2-2.2.1.dist-info
./pathlib2.py
./pathlib2.pyc
./pkg_resources
./_posixsubprocess.so
./psutil
./psutil-5.0.1.dist-info
./pyflakes-1.5.0.dist-info
./pygments
./Pygments-2.2.0.dist-info
./pylab.py
./pylab.pyc
./pylint
./pylint-1.6.5.dist-info
./pyparsing-2.1.10.dist-info
./pyparsing.py
./pyparsing.pyc
./pytz
./pytz-2016.10.dist-info
./qtawesome
./QtAwesome-0.4.3.dist-info
./qtpy
./QtPy-1.2.1.dist-info
./requests
./requests-2.13.0.dist-info
./scandir-1.4.dist-info
./scandir.py
./scandir.pyc
./_scandir.so
./scikit_learn-0.18.1.dist-info
./setuptools
./setuptools-34.0.2.dist-info
./sklearn
./sphinx
./Sphinx-1.5.2.dist-info
./spyder
./spyder-3.1.2.dist-info
./spyder_breakpoints
./spyder_io_dcm
./spyder_io_hdf5
./spyder_profiler
./spyder_pylint
./subprocess32-3.2.7.dist-info
./subprocess32.py
./subprocess32.pyc
./tables
./tables-3.3.0.dist-info
./testpath
./testpath-0.3.dist-info
./tuna.egg-link
```

The way it crashes is: I open spyder from the terminal, open my script above (as you did in your screenshot), uncomment last line, and then place the cursor within the parenthesis, hit Maj + Tab, and it crashes.

I reseted spyder settings, it crashed. See below my session on the Terminal.

```
joachim@joachim-ThinkPad-13:~$ spyder &
[1] 2974
joachim@joachim-ThinkPad-13:~$ 
[1]+  Erreur de segmentation  (core dumped) spyder
joachim@joachim-ThinkPad-13:~$ 
joachim@joachim-ThinkPad-13:~$ spyder &
[1] 3362
joachim@joachim-ThinkPad-13:~$ *** Reset Spyder settings to defaults ***
removing: /home/joachim/.config/spyder/onlinehelp
removing: /home/joachim/.config/spyder/spyder.ini
removing: /home/joachim/.config/spyder/temp.py
removing: /home/joachim/.config/spyder/template.py
removing: /home/joachim/.config/spyder/history.py
removing: /home/joachim/.config/spyder/history_internal.py
removing: /home/joachim/.config/spyder/workingdir
removing: /home/joachim/.config/spyder/.ropeproject
removing: /home/joachim/.config/spyder/langconfig
removing: /home/joachim/.config/spyder/spyder.lock
Segmentation fault (core dumped)

[1]+  Erreur de segmentation  (core dumped) spyder
```

I don't know what other information could be useful to track the bug down. It seems to be very specific to my environment as you cannot reproduce it (when I do).

**Comment by andfoy** [comment]
@ccordoba12 Is there any problem if @LeBarbouze updated spyder using pip instead of conda?

**Comment by goanpeca** [comment]
it is best to use conda but it should work just fine. I have experienced segfaults with xode completion recently so there is definitely a problem

**Comment by andfoy** [comment]
@goanpeca Why I can't reproduce the error?

**Comment by ccordoba12** [comment]
@LeBarbouze, mixing conda and pip packages is not always a good idea, and that's what probably generated this error because our completion code depends on a compiled library called pyzmq, which is packaged differently in conda and pip.

If you did this in your root environment, I'm afraid you'll have to reinstall Anaconda.

Please fix this mixing and let us know if the error is still there or not.

**Comment by goanpeca** [comment]
@ccordoba12 @andfoy probably in this case it is the problem. But on master I am seeing segfaults with code completion randomly. :-|

**Comment by LeBarbouze** [comment]
@ccordoba12 @andfoy @goanpeca OK, I tried on another computer with a cleaner conda install (the mix with pip is less pervasive), and the bug is not present. I didn't know that installing packages with different managers could lead to such bugs (it is still hard to explain, isn't it? also because the bug only appeared with this very specific example of a subclass calling the superclass __call__ method, which uses in turn a method defined in the subclass; it didn't show up with regular functions, nor with classes without a __call__ method).

Anyways, thank you guys for your help, the Spyder team is very reactive!

**Comment by chuong98** [comment]
I got the same error after installing the ROS package ros_qtc_plugin
as in here : https://github.com/ros-industrial/ros_qtc_plugin/wiki/1.-How-to-Install-(Users)
My system is: Ubunut 16.04, QT 5.6.2, Anaconda Python 2.7.

The error happens after I follow this command: 
 - Add "source /opt/qt57/bin/qt57-env.sh" to the users .bashrc file.

To regain the Spyder, I just remove this line from the bashrc file and " source ~/.bashrc".
The error is very likely due to conflicting with qt57.
Hope this help. 

Hope this help.
