### ISSUE TITLE
Spyder crashes when user interacts with IPython kernel while restarting

### ISSUE THREAD

**Issue by andrewdam** [spyder-ide/spyder#4062]
## Description of your problem

**What steps will reproduce the problem?**

1. Open an IPython console
2. Right click, select restart kernel, and click yes
3. Click around in the IPython console while it says "Restarting kernel..."

**Please provide any additional information below**
Happens consistently and easy to reproduce issue. Already tried resetting Spyder settings.

See screenshot in Google Groups post: https://groups.google.com/forum/?hl=en#!topic/spyderlib/fCwk2MPhhGw

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.13
* Operating system: Windows 7 64-bit

## Dependencies

Will add when I get the chance.

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, please work on this one. This is pretty urgent for us to solve :-)

**Comment by dalthviz** [comment]
Hi @andrewdam are you using PyQt4 in your environment?

**Comment by andrewdam** [comment]
@dalthviz PyQt 4.8.6

**Comment by ccordoba12** [comment]
@andrewdam, this bug doesn't show up in PyQt 5, so we recommend you to update to that version.

Qt/PyQt 4 reached end of life in December 2015, as you can read [here](http://blog.qt.io/blog/2014/11/27/qt-4-8-x-support-to-be-extended-for-another-year/), so there's nothing we can do about this, sorry.
