### ISSUE TITLE
nbconvert problem on linux system

### ISSUE THREAD

**Issue by pkgprateek** [spyder-ide/spyder#4065]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.1 
* Python Version: 3.6.0
* Qt Versions: 5.7.1, PyQt5 5.7.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=0.6:  2.2.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  None (NOK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  None (NOK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  2.0.0 (OK)

```

**Comment by jitseniesen** [comment]
You did not write down what the problem is.

Spyder thinks you do not have nbconvert installed. How did you install Spyder? Did you try installing nbconvert?

**Comment by pkgprateek** [comment]
Yes I checked pacman and it shows nbconvert installed. But the problem is solved, I removed and installed nbconvert with pip again.

**Comment by cyslug** [comment]
Try to reinstall configparser:

conda uninstall configparser
conda install configparser

It worked for me.
