### ISSUE TITLE
Spyder core dumps if an opened variable in variable explorer gets deleted

### ISSUE THREAD

**Issue by talkaminker** [spyder-ide/spyder#4066]
If you run `del someobj` while also viewing this object, spyder will crash with core dump

**What steps will reproduce the problem?**

1. run `myobj = [0,1,2]`
2. open myobj in the variable explorer
3. run `del myobj`
4. click OK in the opened window of myobj
5. spyder will crash now and dump core

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.1.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.3.5 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  4.1.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.
