### ISSUE TITLE
Spyder doesn't start anymore

### ISSUE THREAD

**Issue by TheTinka** [spyder-ide/spyder#4070]
Hello everybody,
after updating Spyder it doesn't start anymore. Trying to do it from the command line I get the following error. (Btw, side effect is that the command 'conda' is  not known anymore?).

I've tried to update spyder again but wasn't able because of the 'side effect'.

* Spyder Version: Not able to see but should be 3.1.2
* Python Version: 3.5.1
* Operating system: Windows 7, 64-bit

Could someone help here please?
Thanks in advance
![fehler](https://cloud.githubusercontent.com/assets/22595315/22403229/1b92856a-e611-11e6-8c6b-f07b7431e745.jpg)

**Comment by ccordoba12** [comment]
If conda is not known anymore, you really broke your Anaconda installation. 

I'd suggest you to reinstall it.
