### ISSUE TITLE
Case sensitive replace does not respect case

### ISSUE THREAD

**Issue by nbroers** [spyder-ide/spyder#4072]
Performing a Replace ("Search -> Replace Text") with "Case Sensitive" selected does not respect case, i.e. text is matched for any combination of upper and lower case characters and replaced with the "Replace with:" text.

To reproduce:

1.  From the menu, select "File -> New file...".
2. Enter the following text: """
Sample text to replace
"""
3. From the menu, select "Search -> Replace Text"
4. Enter the text "sample" in text to look for
5. Enter the text "Should not appear" in text to replace with
6. Ensure "Case Sensitive" is selected / checked / active.
7. Click "Replace / Find"

Expected:  Text should remain as is because "sample" does not match "Sample" in a case sensitive manner.

Instead: The text "sample" is replaced with the replace text "Should not appear".

## Versions and main components

* Spyder Version: Spyder 3.1.2 
* Python Version: Python 3.6.0 32bits, Qt 5.7.1, PyQt5 5.7.1 on Windows 
* Operating system: Windoes

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by nbonacchi** [comment]
Yup, I have the same problem.
