### ISSUE TITLE
Add tests to verify that importing .mat files is working

### ISSUE THREAD

**Issue by jim-gardiner** [spyder-ide/spyder#4076]
Import of .mat file after upgrade to v3.1.2

files saved with 3.1.2 can be opened and saved in 3.1.0. 

![image](https://cloud.githubusercontent.com/assets/24959523/22427598/b897f242-e6fb-11e6-90b4-8560d4db2da3.png)

**Comment by goanpeca** [comment]
@spyder-ide/junior-developers any of you have a working matlab to work on this?

**Comment by andfoy** [comment]
I do!

**Comment by goanpeca** [comment]
the its yours :-p

**Comment by andfoy** [comment]
@jim-gardiner Was the .mat file saved from MATLAB?

**Comment by jim-gardiner** [comment]
No. .mat files are being created and opened using spyder.

**Comment by jim-gardiner** [comment]
an update, 

a full conda update --all seems to have fixed the problem. 

sorry for any confusion.

**Comment by ccordoba12** [comment]
@andfoy, let's take the opportunity to add tests to verify that this is working.

If I'm not mistaken, I think this requires the `scipy` package to be installed.

**Comment by andfoy** [comment]
@ccordoba12 Yes, it needs the `scipy.io` package

**Comment by ccordoba12** [comment]
Ok, please proceed to make the tests then :-)
