### ISSUE TITLE
No Qt bindings could be found -- Spyder Couldn't Start Anymore

### ISSUE THREAD

**Issue by isrugeek** [spyder-ide/spyder#4078]
## Description of your problem

**What steps will reproduce the problem?**

1. i Just Installed Using pip Install Command
2. i have seen some Issues but Not Working For me
3. Tried this too "pip install pyqt5" But it Says Could not find a version that satisfies the requirement pyqt5 (from versions: )
No matching distribution found for pyqt5

**What is the expected output? What do you see instead?**

File "/usr/local/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/local/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/local/lib/python2.7/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/usr/local/lib/python2.7/site-packages/qtpy/__init__.py", line 125, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
**Please provide any additional information below**

## Versions and main components

* Spyder Version: Spyder 3.1.2
* Python Version: 2.7.13
* Operating system: MacOs Sierra 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by goanpeca** [comment]
@isrugeek how did you install qt on OSX?

Have you used conda and the anaconda distribution?

**Comment by isrugeek** [comment]
@goanpeca No i am not Using them i just used pip command

**Comment by goanpeca** [comment]
Well you need to install Qt on you mac via other mechanisms. Pip does not install Qt.

I would strongly advice you used [Anaconda](https://www.continuum.io/downloads#linux)

**Comment by isrugeek** [comment]
@goanpeca Actually i even tried to install Using "pip3 install pyqt5" and 

Successfully installed pyqt5-5.7.1 sip-4.19

**Comment by goanpeca** [comment]
Qt is not PyQt, Qt is the C++ based GUI framework. PyQt is the python wrapper.

**Comment by isrugeek** [comment]
@goanpeca Okay now i am Downloading Anaconda 4.2.0 after all i will tell you the result. 
Thanks Man

**Comment by SCP-173-cool** [comment]
Maybe you can have a try:  `brew install pyqt`

**Comment by ccordoba12** [comment]
`pyqt5` is not available for Python 2. That's why you were getting this message

    No matching distribution found for pyqt5

Unfortunately there's nothing we can do about it, sorry. It was the decision of PyQt5 creator not to provide packages for Python 2.

----

Note: I'm going to close this issue because this is not a Spyder bug and also there's nothing we can do about it. @isrugeek, we wish you good luck with Anaconda :-)

**Comment by geandwor** [comment]
can try 
conda install pyqt
