### ISSUE TITLE
Set workspace button missing on project explorer

### ISSUE THREAD

**Issue by imClot** [spyder-ide/spyder#4080]
## Description of your problem

Since updating to Spyder 3 via conda the set workspace button on the Project explorer pane is missing.

**What steps will reproduce the problem?**

1. Update spyder via conda
2. Open spyder

**What is the expected output? What do you see instead?**
A button to change the workspace, or another way to change it from the default user folder.

**Please provide any additional information below**
Example: https://www.dropbox.com/s/l5lnox6s4k8tnj6/missing%20workspace%20button.png?dl=0

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.5
* Operating system: Windows 10

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
The project explorer was completely rewritten in Spyder 3 and that button is not necessary anymore.

Now you have to create projects using the *New project* entry in the *Projects* menu, and you can switch among projects using the entries in *Projects > Recent projects*.
