### ISSUE TITLE
Add keyboard shortcuts for Source > Next|Previous Warning/Error

### ISSUE THREAD

**Issue by robbuckley** [spyder-ide/spyder#4081]
this might be useful when running through a large list of errors (eg after enabling style analysis)

**Comment by goanpeca** [comment]
Hi @robbuckley what would you suggest? have you seen this feature somewhere else? how does it work over there?

Cheers

**Comment by robbuckley** [comment]
Hi @goanpeca 
i haven't seen it elsewhere. It just struck me that using the menu items for Next/Previous warning/error to run through a large list of issues in order to fix them would be tedious, with the following steps for each one:
- switch from kbd to mouse
- 2 clicks to select the menu item
- move the mouse to the line with the error and click to go into edit mode
- move the mouse to hover over the error triangle to see the tooltip with the error description
- switch back to the kbd to fix the error. 

Rinse/repeat many times. What would be great would be a kbd shortcut that would do the following:

1. move the edit window to the next warning/error
2. give the focus to edit window and place the text cursor on the line with the error /warning
3. display the error until the user starts typing

this would allow a very smooth keyboard-only workflow to fix a bunch of warning/errors. 

Does this make sense? 

cheers
Rob

**Comment by goanpeca** [comment]
Thanks @robbuckley, sure sounds reasonable

**Comment by metaperl** [comment]
I second this request. I suggest CONTROL + RIGHT ARROW to move through them.
