### ISSUE TITLE
Error in "Maximize current pane"

### ISSUE THREAD

**Issue by pnavarre** [spyder-ide/spyder#4084]
## Description of your problem

**What steps will reproduce the problem?**

I use a virtual environment with Python 3.5.3 on Ubuntu 16.04. I install PyQt5 v5.7.1 from pip. This comes with a local copy of Qt (v5.7.1) so it doesn't mess with the Ubuntu Qt.
I compile Spyder 3.1.2 from source in the virtual environment with all necessary dependencies (see below).
Probably unrelated, but I also use nvidia driver which has an issue reported in https://github.com/spyder-ide/spyder/issues/3226. I fix it manually according to the post, using PyOpenGL. 

**What is the expected output? What do you see instead?**
When I press  "Maximize current pane" I expect the editor or console to expand. Instead, I get the following message from Spyder Internal Console:
--------------------
Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "/opt/libs/python3_env/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2202, in maximize_dockwidget
    self.last_plugin.dockwidget.toggleViewAction().setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'dockwidget'
--------------------

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.5.3
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This was already reported and will be fixed in Spyder 3.1.3.
