### ISSUE TITLE
Crash when saving an image in the IPython console

### ISSUE THREAD

**Issue by Pingkun** [spyder-ide/spyder#4088]
Crash when "save image as..." to save a plot in console to overwrite an existing image file.

**What steps will reproduce the problem?**

1. Plot a simple drawing using matplotlib in console
2. Right click the image to save into a file
3. Plot again and right click to "save image as..." to overwrite the file in step 2.

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.5
* Operating system: ubuntu 14.04

**Comment by ccordoba12** [comment]
Fortunately this was fixed with the change made in PR #4109.
