### ISSUE TITLE
MacOS Anaconda/Spyder installation.

### ISSUE THREAD

**Issue by siparast** [spyder-ide/spyder#4089]
I have downloaded the newest version of Anaconda and want to use Spyder. I am having issue regarding installation of Spyder. For some reason the spyder hasn't been installed and the icon for is also some generic logo. I can only open Spyder tru Anaconda and when close is it closes Spyder as well. I would appreciate the help. I am new to Python and have no clue what to do and how to check and install everything and see even if the libraries have been installed.

**Comment by ccordoba12** [comment]
If you can run Spyder then everything was installed correctly.

> the icon for is also some generic logo

There's no solution to that problem right now.

> I can only open Spyder tru Anaconda and when close is it closes Spyder as well

To avoid that I think you have to open a terminal, and run Spyder like this

    spyder &

Then you should be able to close the terminal. If that's not possible, then you need to maintain it open.
