### ISSUE TITLE
UI UHD Bugs

### ISSUE THREAD

**Issue by inferno596** [spyder-ide/spyder#4090]
## Description

**What steps will reproduce the problem?**

1.  Open spyder on windows 10, as installed by anaconda package, on a UHD/4k screen
2. 
3. 

**What is the expected output? What do you see instead?**
Issue 1)
Expected: Readable help tab.
Output: Font too small to read

Issue 2)
Expected: Normal sized icons
Output: Weirdly and annoyingly small icons

**Please provide any additional information below**

Print screen highlighting UI issues
https://i.imgur.com/k1DYZas.png

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by inferno596** [comment]
Sorry, a few other things:
1) The little icons on the right side of the icon bar are too small
2) All the little x boxes throughout the interface are too small
3) Yes I'm using the windows auto-scaling.
4) If it helps, Lyx had near identical problems, if you need details on how they added UHD support, email me at inferno596 (at) gmail.com

**Comment by ccordoba12** [comment]
Go to

    Preferences > General > Appearance

and turn on

    Enable high DPI scaling

**Comment by inferno596** [comment]
Small secondary bug report: you have to close and reopen spyder after enabling this feature before it takes effect when running linux

**Comment by ccordoba12** [comment]
It's true, but we're going to improve this feature in the future.
