### ISSUE TITLE
Spyder does not launch on Win10 / Python 3.5.2 - cmd output blank

### ISSUE THREAD

**Issue by corni86** [spyder-ide/spyder#4107]
Hi,

## Description of your problem
On a new & clean install of Python 3.5.2 with Spyder 3.5.2, Spyder does not launch. I tried several ways of launch Spyder (in the Explorer, in command line) - nothing works. The spyder.exe shows quickly up in the process list and then disappears. I also tried to remove the spyder.lock directory that it creates and the files it contains - but no success.
Interestingly the output if I start spyder from the command line is empty (also if I start with spyder.exe --show-console).

Any ideas?

## Versions and main components
* Spyder Version: 3.1.2
* Python Version: 3.5.2
* Operating system: Win 10

## Installed packages:
alabaster==0.7.9
appdirs==1.4.0
astroid==1.4.9
Babel==2.3.4
bleach==1.5.0
brewer2mpl==1.4.1
chardet==2.3.0
colorama==0.3.7
cycler==0.10.0
decorator==4.0.11
docutils==0.13.1
entrypoints==0.2.2
ggplot==0.11.5
h5py==2.7.0rc2
html5lib==0.9999999
imagesize==0.7.1
ipykernel==4.5.2
ipython==5.2.2
ipython-genutils==0.1.0
ipywidgets==5.2.2
isort==4.2.5
jedi==0.10.0
Jinja2==2.9.5
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.1.0
jupyter-core==4.2.1
Keras==1.2.1
lazy-object-proxy==1.2.2
MarkupSafe==0.23
matplotlib==2.0.0
mccabe==0.6.1
mistune==0.7.3
nbconvert==5.1.1
nbformat==4.2.0
notebook==4.3.2
numpy==1.12.0+mkl
numpydoc==0.6.0
packaging==16.8
pandas==0.19.2
pandocfilters==1.4.1
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
pip-review==0.5.2
prompt-toolkit==1.0.13
protobuf==3.2.0
psutil==5.1.2
ptyprocess==0.5.1
py==1.4.32
pycuda==2016.1.2
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.6.5
pyparsing==2.1.10
pytest==3.0.6
python-dateutil==2.6.0
pytools==2016.2.6
pytz==2016.10
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.2.1
QtPy==1.2.1
remote-ikernel==0.4.5
requests==2.13.0
rope-py3k==0.9.4.post1
scikit-learn==0.18.1
scipy==0.18.1
seaborn==0.7.1
simplegeneric==0.8.1
six==1.10.0
sklearn==0.0
snowballstemmer==1.2.1
Sphinx==1.5.2
spyder==3.1.2
statsmodels==0.8.0rc1
tensorflow-gpu==0.12.1
testpath==0.3
Theano==0.8.2
tornado==4.4.2
traitlets==4.3.1
wcwidth==0.1.7
widgetsnbextension==1.2.6
win-unicode-console==0.5
wrapt==1.10.8

**Comment by ccordoba12** [comment]
Do you have installed PyQt5? Your `pip freeze` list doesn't show it, and without it there's no Spyder.

**Comment by ccordoba12** [comment]
Closing, as the lack of PyQt5 is most probably the error.
