### ISSUE TITLE
Can't change shortcut to run cells

### ISSUE THREAD

**Issue by DejiM** [spyder-ide/spyder#4108]
## Description

**What steps will reproduce the problem?**

1. preferences -> keyboard short cut -> run selection
2. Type alt + enter
3. try to run selected code with alt + enter

**What is the expected output? What do you see instead?**
expect code to run-code doesn't run

**Please provide any additional information below**
Running on a mac Yosemite

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by andfoy** [comment]
As far as I am concerned, I can assign this shortcut on all Operating Systems

**Comment by ccordoba12** [comment]
To expand on what @andfoy said, we think this was fixed when we added `Alt+Enter` as a shortcut to run the previous cell.
