### ISSUE TITLE
%run magic command does not return traceback in Spyder's IPython console

### ISSUE THREAD

**Issue by sapphire008** [spyder-ide/spyder#4116]
Here is a simple script, named test.py

```python
pro(asdf)
print("asdf")
```

When running this script using the magic command `run test.py` typed into Spyder's IPython console, no error traceback is returned in Spyder's Ipython console. However, when running the script using the Spyder's Run button, or launching Ipython conosle on its own, or running through Windows Command Prompt, error tracebacks are properly returned.

This problem was replicated in two Windows 10 machines, both having the latest version of Spyder (Spyder 3.1.2), with Python 3.5.2 |Anaconda 4.2.0 (64-bit)|IPython 5.2.2.

**Comment by chenwang** [comment]
same thing happens to IPython 5.1.0 on my Windows machine.

**Comment by bruot** [comment]
I think this is a problem in qtconsole, see jupyter/qtconsole/issues/140.  It looks like it will be fixed in their next release.

**Comment by ccordoba12** [comment]
@bruot, thanks for letting us know about it.

**Comment by bruot** [comment]
Just tested again: Upgrading qtconsole from 4.2.1 to 4.3.0 solves the problem.

**Comment by ccordoba12** [comment]
Glad to know this is solved.
