### ISSUE TITLE
Python console becomes unresponsive after entering long lines

### ISSUE THREAD

**Issue by HackerzWorkshop** [spyder-ide/spyder#4118]
## Description of your problem
Python console becomes unresponsive after entering long lines in Spyder since version 3
**What steps will reproduce the problem?**

1. build a long list of strings, for example `['a'] * 5000`
2. copy-paste the output into console
3. console becomes very unresponsive, may hang up

**What is the expected output? What do you see instead?**
the console is expected to be responsive as normal

**Please provide any additional information below**
This problem occurs only on spyder > 3 and above, currently using 2.3.9 and having no problems 

## Versions and main components

* Spyder Version: above 3
* Python Version: 3.5
* Operating system: Win 10

## Dependencies
None

**Comment by ccordoba12** [comment]
This bug has been present in the Python console for a long time. However, we don't plan to fix it because the Python console is going to be removed in Spyder 3.2, sorry.
