### ISSUE TITLE
Spyder cannot accept Chinese input

### ISSUE THREAD

**Issue by willhunger** [spyder-ide/spyder#4120]
## Description of your problem

**What steps will reproduce the problem?**

1. When i edit with a django project
2. I try to input Chinese character
3. but i failed

**What is the expected output? What do you see instead?**
When i input a Chinese character,i got Chinese Pinyin on screen.
I use the SougouINPUT

**Please provide any additional information below**

## Versions and main components

* Spyder Version:Spyder 3.12
* Python Version:Python 3.53
* Operating system:ubuntu 16.10
* Python 3.5.2+ 64bits, Qt 5.7.0, PyQt5 5.7 on Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Could you write those characters here?

**Comment by willhunger** [comment]
Of course i can write here
哈哈哈哈

**Comment by jitseniesen** [comment]
Ha ha.

I don't use Sougou but I use fcitx to input pinyin on Debian, which is almost the same as Ubuntu. My experience is that Chinese input does not work in the Anaconda version of Spyder, but it does work in the Debian version of Spyder. Pasting Chinese characters into Spyder always works. It may have something to do with how Qt is packaged.

@willhunger How did you install Spyder?

**Comment by willhunger** [comment]
@jitseniesen
Yes,So do I.
I install Spyder by pip

**Comment by xyl576807077** [comment]
I met the same problem when i wrote comment using chinese

**Comment by willhunger** [comment]
@xyl576807077 
请问现在你是否解决了?

**Comment by xyl576807077** [comment]
@willhunger 
没有解决，已经暂时使用jupyter notebook了

**Comment by willhunger** [comment]
@xyl576807077 我也切换到了vscode

**Comment by wjt-one** [comment]
现在修复好了么？

**Comment by wjt-one** [comment]
@ccordoba12 @jitseniesen  could fix this problem now? it makes work so troublesome.

**Comment by ccordoba12** [comment]
Sorry, none of us are Chinese speakers/users. So we'll wait until a Chinese hacker send us a pull request to fix it.

**Comment by wjt-one** [comment]
@ccordoba12  I also install Japanese input methods(fcitx-anthy),and find the same issue occur.so I think it's a problem about " the Anaconda version of Spyder in Ubuntu 16.04LTS" , which maybe can't accept any other language than english.thanks.

**Comment by t104306033** [comment]
我也有相同的情況！
之前使用ibus框架下的的chewing(新酷音)輸入法可以正常在spyder(anaconda的)下輸入中文。
最近想學拼音輸入法，因此轉戰fcitx框架下的sougou拼音輸入法，便不能正常輸入中文了。
不知道這東西有沒有解？

**Comment by t104306033** [comment]
更新

剛剛測試了一下，在 fcitx框架所有的輸入法都無法鍵入中文。
但是 ibus的新酷音以及拼音都可以正常輸入。

看來這是程式與 fcitx框架不相容的問題。

**Comment by willhunger** [comment]
@t104306033 
问题是fcitx 与所有的Qt5构建的应用都不能兼容

**Comment by willhunger** [comment]
@wit-one
Fctix cannot input any characters except Latino characters to Qt5 Application.
So you can change your input method framework to hack this problem

**Comment by cedarice** [comment]
可以这么解决
首先需要自己编译fcitx-qt5:
安装依赖：sudo apt install cmake extra-cmake-modules fcitx-libs-dev libxkbcommon-dev
克隆或下载最新版的fcitx-qt5: https://github.com/fcitx/fcitx-qt5/releases
然后编译：cmake ./
              make
最后在platforminputcontext文件夹中的libfcitxplatforminputcontextplugin.so复制到anaconda3/plugins/platforminputcontexts/文件夹中，重新启动spyder即可输入中文。
我的系统是Ubuntu 18.04 LTS，Spyder是通过Anaconda安装的。

**Comment by jitseniesen** [comment]
@cedarice 多谢
Based on their comment, it looks like fcitx-qt5 needs to be packaged for conda.

**Comment by ccordoba12** [comment]
That's what I got too. @jitseniesen, do you know what's he/she saying? I could use his/her instructions to package fcitx-qt5 for conda.

**Comment by bcolsen** [comment]
Google Translate seems pretty readable:

Can solve this
First you need to compile fcitx-qt5 yourself:
Installation dependencies: sudo apt install cmake extra-cmake-modules fcitx-libs-dev libxkbcommon-dev
Clone or download the latest version of fcitx-qt5: https://github.com/fcitx/fcitx-qt5/releases
Then compile: cmake ./
Make
Finally in the platforminputcontext folder libfcitxplatforminputcontextplugin.so copied to the anaconda3/plugins/platforminputcontexts/ folder, restart spyder to enter Chinese.
My system is Ubuntu 18.04 LTS. Spyder is installed via Anaconda.

**Comment by ccordoba12** [comment]
Thanks @bcolsen! It seems pretty doable :+1: 

I'll give it a try after we release 3.3

**Comment by bramson** [comment]
I think this is the right place for my problem.  I'm running Spyder from Anaconda running from Bash on Ubuntu on Windows...all the latest versions.  
This version of Spyder does not support Japanese characters in the editor or the console.  
Spyder running from WynPython on Win10 has no trouble (but I can't access the database that way).  
Using Bash inside VS Code the characters are beautiful (but I don't like that IDE).  
I don't know the reason, but there are only 4 supported fonts on the Ubuntu Anaconda version and none of those fonts support Japanese (or Chinese) characters.  

Is this just a matter of installing the proper fonts on my Linux environment? 
Or (as the above indicates) is this a deeper problem with this Spyder distro?

**Comment by shilkazx** [comment]
The fix is not work for me. I am on Archlinux x64,  anaconda 5.1 py36 and spyder 3.2.6 package from anaconda. I've already try a soft link or a hard copy of libfcitxplatforminputcontextplugin.so(Archlinux fcitx-qt5 package) to anaconda/plugins/platforminputcontexts, but seems nothing happend.

**Comment by xiaohongniua** [comment]
I got the same problem, and every time I input one char,it shows two on the screen

**Comment by 1900011604** [comment]
@ccordoba12 It works, thanks!

**Comment by Firestar-Reimu** [comment]
It seems that spyder can input Chinese on Linux (I use fcitx5). I use Archlinux repository and installed spyder by pacman:

https://archlinux.org/packages/community/any/spyder/

https://github.com/archlinux/svntogit-community/blob/packages/spyder/trunk/PKGBUILD

This do not need the python package `fcitx-qt5`.

**Comment by ccordoba12** [comment]
> This do not need the python package fcitx-qt5.

This is only necessary for Anaconda users.

**Comment by JGSphaela** [comment]
Just stumbled across this issue as I wasn't able input Japanese with fcitx in spyder, so I want to write a quick update. The solution below provided by @ccordoba12 still totally works now and solve the issue:

> If not, you need to run
> 
> ```
> conda create -n spyder-env -c conda-forge python=3.9 spyder fcitx-qt5
> conda activate spyder-env
> spyder
> ```

I noticed tho `python=3.9` is not necessary as I successfully install it on Python 3.11. And in my test, a dedicate conda env for spyder, as suggest in @ccordoba12 's code, is really recommended as it can avoid compatible issues.

**Comment by ccordoba12** [comment]
To everyone subscribed to this issue: it'll be fixed in Spyder 6 (to be released before the end of the year) for our Conda packages and also our new Linux installer.
