### ISSUE TITLE
Spyder closes after completing Run settings dialog for a first run.

### ISSUE THREAD

**Issue by martincss** [spyder-ide/spyder#4122]
## Description of your problem
Spyder crashes after using the Run settings dialog for a first time run, on existing or new scripts.

**What steps will reproduce the problem?**

1. In Run preferences, tick the "Always show Run settings dialog on a first file run" box.
2. Attempt to run a script for the first time on the Ipython console.
3. On the Run settings dialog, select "Run in current Ipython console" and confirm.

**What is the expected output? What do you see instead?**
Program does indeed run but the "python.exe has stopped working" window appears and spyder is forced to close.

**Please provide any additional information below**
On the Run preferences, default working directory is the script directory. Spyder does sometimes crash when also modifying the Run preferences. 

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.12
* Operating system: Windows 10

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.1.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by dalthviz** [comment]
Hi @martincss, what is the version of PyQt of your environment?

**Comment by ccordoba12** [comment]
Fortunately this was fixed by pull request #4106, and it was only happennig on PyQt4, according to @dalthviz.
