### ISSUE TITLE
language reset to japanese on reboot

### ISSUE THREAD

**Issue by drammock** [spyder-ide/spyder#4124]
## Description
just updated to current master, running spyder via `bootstrap.py`.  Language gets set to Japanese on every restart of spyder.

**What steps will reproduce the problem?**

1. Open spyder
2. open preferences > general > advanced 
3. set language to English, apply settings, close & re-open spyder
4. open preferences > general > advanced 
5. language will be set to 日本語

**What is the expected output? What do you see instead?**

interface language setting should persist across reboots.  

**additional info**

Note that after setting it to English and rebooting, it loads an English interface, but if I change **any other setting** and click "OK" or "Apply" then it will prompt about needing to reboot in order to change the interface language.

## Version and main components

* Spyder Version: 4.0.0.dev0 65bc403
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.1.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.0+104.g1c8816f (OK)
numpy >=1.7      :  1.12.0.dev0+2af06c8 (OK)
sphinx >=0.6.6   :  1.5a0 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  3.4.2 (OK)
matplotlib >=1.0 :  1.5.1+1643.g0423430 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
@rlaverde, please take a look at this one.

**Comment by drammock** [comment]
thanks @rlaverde !

**Comment by isalirezag** [comment]
i have the same problem, why this happens? and how to solve it?

**Comment by willois** [comment]
Had a similar issue and fixed by changing langconfig in "C:\Users\YOUR NAME\.spyder-py3\langconfig" to "en"

**Comment by MarcoCiafa** [comment]
Had the same problem on Spyder 5.0.0 with Python 3.8.

> Had a similar issue and fixed by changing langconfig in "C:\Users\YOUR NAME.spyder-py3\langconfig" to "en"

This solved the issue.
