### ISSUE TITLE
UnboundLocalError: local variable 'img_path' referenced before assignment

### ISSUE THREAD

**Issue by bdrung** [spyder-ide/spyder#4127]
## Description of your problem

The Ubuntu Error Tracker has been receiving reports about a problem regarding spyder. This problem was most recently seen with package version 3.0.2+dfsg1-2, the problem page at https://errors.ubuntu.com/problem/f4a67211f66fb239047b33781abfae6849af207a contains more details, including versions of packages affected, stacktrace or traceback, and individual crash reports.
If you do not have access to the Ubuntu Error Tracker you can request it at http://forms.canonical.com/reports/.

```python
Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 120, in <module>
    SPLASH = QSplashScreen(QPixmap(get_image_path('splash.svg'), 'svg'))
  File "/usr/lib/python3/dist-packages/spyder/config/base.py", line 212, in get_image_path
    return osp.abspath(osp.join(img_path, default))
UnboundLocalError: local variable 'img_path' referenced before assignment
```

The relevant code (taken from version 3.1.2+dfsg1-1):

```python
def get_image_path(name, default="not_found.png"):
    """Return image absolute path"""
    for img_path in IMG_PATH:
        full_path = osp.join(img_path, name)
        if osp.isfile(full_path):
            return osp.abspath(full_path)
    if default is not None:
        return osp.abspath(osp.join(img_path, default))
```

The problem: When `IMG_PATH` is empty and default is defined, `img_path` is not defined and python will crash.

## Versions and main components

* Spyder Version: 3.0.2+dfsg1-2
* Python Version: 3.5.1-4
* Operating system: Ubuntu 17.04 (zesty)

**Comment by ccordoba12** [comment]
We can fix it in Spyder 3.1.3 and you can backport the error to the Ubuntu packages. Is that fine for you?

**Comment by bdrung** [comment]
Yes, that's fine.

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.
