### ISSUE TITLE
Spyder crashes because of socket initialization errors on Windows

### ISSUE THREAD

**Issue by Niveleee** [spyder-ide/spyder#4132]
I downloaded Anaconda last week and have never been able to load Spyder. The same error message keeps coming up that spyder crashed during last session and to try resetting spyder by "running spyder with the command line option '--reset': python spider --reset." I tried and that doesn't work. Other solutions that I found were to delete the spyder.lock folder and I do but that also doesn't resolve anything and the folder reappears after I try to load Spyder again and nothing happens. I've tried deleting the entire .spyder-py3 folder as that worked for some people but the folder also reappears. 

**What steps will reproduce the problem?**

1. Open up anaconda navigator
2. Doubleclick on spyder 3.1.2 
3. Error message appears that spyder crashed during last session

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Qt Version: 4.2.1
* PyQt Version:
* Operating system: Windows 7 Home Premium

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please open a terminal (i.e. cmd.exe) and run there

    spyder --show-console

Then post the errors printed there on this issue.

**Comment by Niveleee** [comment]
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2989, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2891, in run_spyder
    main = MainWindow(options)
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 494, in __init__
    socket.IPPROTO_TCP)
  File "C:\Users\User\Anaconda3\lib\socket.py", line 144, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [WinError 10106] The requested service provider could not be loaded or initialized

**Comment by ccordoba12** [comment]
It seems your antivirus/firewall is blocking Spyder's attempt to open a socket in your system.

What antivirus/firewall are you using?

**Comment by Niveleee** [comment]
I disabled Norton and tried loading Spyder again and it still doesn't work. I will try uninstalling and reinstalling with Norton disabled and see if it will work then.

**Comment by rickywz** [comment]
I have the same problem.I have solve it.
open a terminal (i.e. cmd.exe) and run there
netsh winsock reset
Then restart computer.
Hope to help you.

**Comment by Niveleee** [comment]
Thank you so much!! That solved the problem!

**Comment by ccordoba12** [comment]
@rickywz, what does

    netsh winsock reset

do?

**Comment by rickywz** [comment]
@ccordoba12 Reset the Winsock directory to restore the network
