### ISSUE TITLE
Non-ascii characters not displayed correctly in Find in files

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#4134]
## Description

**What steps will reproduce the problem?**

1. Write a line containing a non-ascii character in a file, e.g. `str = 'Viva España'`
2. Use 'Find in files' to find that line, e.g. search for `Viva`

**What is the expected output? What do you see instead?**

I would have expected the non-ascii character to be displayed correctly in the "Find in files" pane. Instead I see a hex representation.

The below screenshot hopefully makes it clear. I would have liked to see `España` in the location marked with the red circle.

![Screenshot](https://cloud.githubusercontent.com/assets/7941918/22842699/23b59ba8-efce-11e6-9b94-3edde014a343.png)

## Version and main components

* Spyder Version: 3.2.0.dev0 847ea1a2
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.
