### ISSUE TITLE
Cannot install pyside in anaconda with 2.7 environment

### ISSUE THREAD

**Issue by hannanp9** [spyder-ide/spyder#4136]
## Description of your problem

**What steps will reproduce the problem?**

1. Try installing Pyside package using pip command
2. pip install -U PySide
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
  Failed building wheel for PySide
  Running setup.py clean for PySide
Failed to build PySide
Installing collected packages: PySide
  Running setup.py install for PySide: started
    Running setup.py install for PySide: finished with status 'error'

## Versions and main components

* Spyder Version: 3.1.0
* Python Version: 2.7
* Qt Version: 5.6.2
* PyQt Version: PyQt 5.6.0
* Operating system: MAC OSX (Sierra)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This is a problem with installing PySide so it's not really a Spyder bug.

Besides, Spyder doesn't support PySide anymore, sorry.
