### ISSUE TITLE
I need to hit the "run" button several times(or hit Enter several times) to get the printed result.

### ISSUE THREAD

**Issue by asmwarrior** [spyder-ide/spyder#4137]
## Description of your problem
When I try to run a simple py script by click the "run" button on the toolbar, I see no response, but I have to click the "run" button again to see the result of the first run.

**What steps will reproduce the problem?**

1.  Open the spyder, and create a simple file, which is located in `E:\download\sci\WinPython-64bit-3.5.3.0Qt5\notebooks\untitled0.py`, then type some script such as `print(3)`
2.  Click the "run" button(suppose I use the Python console), I get the Python console like this:

```
>>> runfile('E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks/untitled0.py', wdir='E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks')
>>>
```

Then you can see `3` is **not** printed.
3.  I have to click on the run button again, so that the console becomes like:
```
>>> runfile('E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks/untitled0.py', wdir='E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks')
>>> runfile('E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks/untitled0.py', wdir='E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks')
>>> 
```
so, there is no result again.
4, I have to type `Enter` several times in the Python console, and I get the result like below
```
>>> runfile('E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks/untitled0.py', wdir='E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks')
>>> runfile('E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks/untitled0.py', wdir='E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks')
>>> 
>>> 
>>> 
>>> 
>>> 

3
>>> 

3
>>> 
```

**What is the expected output? What do you see instead?**

I expect when I click the run button, I should gives such result
```
>>> runfile('E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks/untitled0.py', wdir='E:/download/sci/WinPython-64bit-3.5.3.0Qt5/notebooks')
3
>>> 
```
I mean the user prompt should return to the user, so I can type other command or click to run the command again.

**Please provide any additional information below**
This happens in Anoconda python 3.4, python 3.5 version, or Winpython 3.4 or Winpython3.5.

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.4 or 3.5
* Qt Version: installed by the above distributions (either anoconda or winpython)
* PyQt Version: installed by the above distributions (either anoconda or winpython)
* Operating system: Win7 64bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
```
BTW: does this a pipe synchronized issue? Because I think spyder should read the returned value from the Python console, but it looks like the returned value is not shown on the spyder, maybe it is cached?

My "Run setting" is: Execute in current Python or IPython.

**Comment by asmwarrior** [comment]
The tricky thing is: it looks like this may cause by a long file name or a file name with a `-` (dash or hyphen) in a file path.

For example, I restart Spyder, and then I open a simple file which is located under `E:/`, then I don't see this issue. Here is the log

```
>>> runfile('E:/a.py', wdir='E:')
3
>>> runfile('E:/a.py', wdir='E:')
3
>>> runfile('E:/a.py', wdir='E:')
3
>>> runfile('E:/a.py', wdir='E:')
3
>>> runfile('E:/a.py', wdir='E:')
3
>>> runfile('E:/a.py', wdir='E:')
3
>>> 
```
This is: each time I hit the run button, I get the expected result quickly return from the Python console. 

So, do you think this is an issue with how Python or Spyder handle file path?

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a known bug with the Python console, and unfortunately we don't know how to fix it.

Because of this (and other similar errors) we decided to remove the Python console in Spyder **3.2**. So please start to migrate your work to the IPython console.

**Comment by asmwarrior** [comment]
@ccordoba12  thanks for the quick response. But the bad thing is: It looks like debugging the program under IPython works quite badly. I can't add now breakpoints or remove breakpoints when I debugged under IPython, but under Python console, adding bp or removing bp works OK. Any workaround about this breakpoint issue? Does it will be fixed in the Spyder 3.2?

**Comment by ccordoba12** [comment]
> Does it will be fixed in the Spyder 3.2?

Yes, we'll fix that, and I think we could do it for our next release (i.e. **3.1.3**). Could you open a new bug about that so we don't forget to do it? Thanks!

**Comment by asmwarrior** [comment]
OK, so I can't wait for the 3.13. It looks like this bug is already reported #3476, see here [New breakpoints can't be created in the IPython console · Issue #3476 · spyder-ide/spyder](https://github.com/spyder-ide/spyder/issues/3476)

**Comment by ccordoba12** [comment]
Ohh, great. Thanks for reminding me about it :-)

**Comment by asmwarrior** [comment]
Does the fix already arrived in the git master? So I can try it on my WinPython or Anaconda system.

**Comment by ccordoba12** [comment]
Nop, not yet. But we plan to release 3.1.3 next week.

**Comment by asmwarrior** [comment]
OK, so I can wait for the fix, then I will switch back to use IPython console again. Thanks.

**Comment by ccordoba12** [comment]
:+1:
