### ISSUE TITLE
Python 3.6.0 NameError: name 'runfile' is not defined when I try to run a simple script under Python console

### ISSUE THREAD

**Issue by asmwarrior** [spyder-ide/spyder#4138]
## Description of your problem
Here is my testing WinPython-64bit-3.6.0.1Qt5 under Window7.
**What steps will reproduce the problem?**

1.  open spyder
2.  create a simple script, such as `print(1)`
3.  switch to Python console, and hit "run" button of the toolbar
4, I get such message

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> runfile('E:/download/sci/WinPython-64bit-3.6.0.1Qt5/settings/.spyder-py3/temp.py', wdir='E:/download/sci/WinPython-64bit-3.6.0.1Qt5/settings/.spyder-py3')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'runfile' is not defined
>>> 
```

Note that it works OK under IPython console.

**What is the expected output? What do you see instead?**
It should work.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: spyder 3.12
* Python Version: 3.6.0
* Qt Version: bundled with WinPython-64bit-3.6.0.1Qt5
* PyQt Version: bundled with WinPython-64bit-3.6.0.1Qt5
* Operating system: Windows 7 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
```

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

Note this bug does not happens under the WinPython-64bit-3.4.4.6Qt5 and WinPython-64bit-3.5.3.0Qt5 distributions, which have python 3.4 or 3.5 version.

**Comment by ccordoba12** [comment]
Does it work in the IPython console?

**Comment by stonebig** [comment]
On my pc, I do remark indeed it does work on IPython console, and not on "legacy" console.

**Comment by asmwarrior** [comment]
@ccordoba12 In my original post, I did said that it works under IPython console.

**Comment by ccordoba12** [comment]
Sorry, you're right. I didn't see it.

**Comment by ccordoba12** [comment]
I really prefer to not put more resources on the Python console, given its imminent removal, so I'm closing this one, sorry.
