### ISSUE TITLE
Nan value in dataframe editor crash Spyder

### ISSUE THREAD

**Issue by markusr** [spyder-ide/spyder#4139]
## Description of your problem

1. Run the following script:
```
import numpy as np
import pandas as pd

np_array = np.zeros(100)
np_array[10:] = np.nan
dataframe = pd.DataFrame(np_array)
```

2. Go to the Variable explorer
3. Double click on the ```dataframe``` variable
4. Close the table editor window

**What is the expected output? What do you see instead?**
Spyder completely crashes. This is not always reproducible but opening and closing table editor several times triggers the crash.

## Versions and main components

* Spyder Version: 3.1.2
Python 3.5.2 64bits
Qt 5.7.0
PyQt5 5.7
* Operating system: Kubuntu 16.04

## Dependencies

jedi >=0.8.1     :  0.10.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.1.3 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
I can't reproduce this. How did you install PyQt?

**Comment by markusr** [comment]
I don't know how I installed it. All with standard packages and/or pip.

I did some further investigations: 
- The format (in variable explorer) has to be ```%d```. Which I used before for a special dataframe.
- There are exceptions in the internal console.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(self._format % value)
ValueError: cannot convert float NaN to integer
```

**Comment by ccordoba12** [comment]
@jitseniesen, any ideas?

**Comment by jitseniesen** [comment]
Yes, I understand it after markusr's explanation. The error message complains that the format `%d` is for integers and cannot be applied to NaN.

An easy solution for us would be to use the default format (which is `%.3g`) in this case. Would that be acceptable from a user experience point of view?

**Comment by markusr** [comment]
> An easy solution for us would be to use the default format (which is %.3g) in this case. Would that be acceptable from a user experience point of view?

@jitseniesen Are you suggesting that non-NaN values are shown as ```%d``` and NaN values as ```%.3g``` (if  ```%d``` is set as the input format)?

**Comment by jitseniesen** [comment]
Yes

**Comment by markusr** [comment]
This sounds like a good solution. I also gave it some thoughts but I couldn't come up with better solution.

Anyhow better than the application crash...

**Comment by ccordoba12** [comment]
@jitseniesen, could you create a PR against the `3.1.x` branch for this? It seems an easy fix but I fail to understand what we should exactly do to fix it :-)
