### ISSUE TITLE
vertical end-of-line in wrong place

### ISSUE THREAD

**Issue by drammock** [spyder-ide/spyder#4153]
## Description

The setting "show vertical line after XX characters" draws the line in the wrong place, and changing its value does not change line position after clicking "apply" or "OK".

**What steps will reproduce the problem?**

1. open spyder
2. enable vertical line after xx characters
3. set xx to any number other than 77

**What is the expected output? What do you see instead?**
Line should appear after the specified number of characters.
Instead, line appears after 77 characters no matter what setting is used (see screenshot)

![screenshot](https://cloud.githubusercontent.com/assets/1810515/23036128/75fd3e18-f436-11e6-9415-dbb5ec2d5260.png)

**Please provide any additional information below**

My font is set as [Source Code Pro](https://github.com/adobe-fonts/source-code-pro) at size 9.  Changing typeface or pointsize does not appear to fix this, though I only tried a couple fonts and a couple pointsizes.

## Version and main components

* Spyder Version: 4.0.0.dev0 7e9a9bf
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.1.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.0+104.g1c8816f (OK)
numpy >=1.7      :  1.12.0.dev0+2af06c8 (OK)
sphinx >=0.6.6   :  1.5a0 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  3.4.2 (OK)
matplotlib >=1.0 :  1.5.1+1643.g0423430 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.5.5 (OK)

```

**Comment by rlaverde** [comment]
I'm able to reproduce this error, It happens when using python2.7, I will start tracing it

@ccordoba12 Are there any plans for stop supporting python2.7? (maybe after spyder4)

**Comment by ccordoba12** [comment]
In Spyder 5, I think.
