### ISSUE TITLE
"Save as" dialog extremely slow

### ISSUE THREAD

**Issue by Gh0str1d3r** [spyder-ide/spyder#4156]
## Description of your problem

**What steps will reproduce the problem?**

1. With any file open, click "Save As"
2. Try to type a file name
3. 

**What is the expected output? What do you see instead?**

Typing a file name should be a flawless, without any delays and without causing measurable CPU load increase.

**Please provide any additional information below**

Every character takes at least 1 second to appear. CPU load goes to 100% in the process.

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 2.7.12
* Qt Version: 4.8.7 and 5.7.1
* PyQt Version: 4.12
* Operating system: Gentoo Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.3.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.3.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by Gh0str1d3r** [comment]
Some more information: When started from a terminal, spyder outputs the following errors at every character that I type:

kf5.kio.core: Invalid URL: QUrl("f.py")
kf5.kio.core: Invalid URL: QUrl("fi.py")
kf5.kio.core: Invalid URL: QUrl("fil.py")
kf5.kio.core: Invalid URL: QUrl("file.py")
kf5.kio.core: Invalid URL: QUrl("filen.py")
kf5.kio.core: Invalid URL: QUrl("filena.py")
kf5.kio.core: Invalid URL: QUrl("filenam.py")
kf5.kio.core: Invalid URL: QUrl("filename.py")

when I change the existing filename to "filename.py". This only happens if the string ends with ".p" or "py". That is, I have no problem typing anything unless the current string ends with either of those characters.

**Comment by ccordoba12** [comment]
Yep, I noticed that too. We'll fix this in Spyder 3.1.4.

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.

**Comment by rlaverde** [comment]
@ccordoba12 I'm not able to reproduce this error, any hints of how to reproduce it?

I tried with python3.5.2 with pyqt 5.6.0 and 4.11.4, and python2.7 with pyqt 5.6.0

**Comment by gb119** [comment]
I might have a related problem with a regression between 3.1.3 and 3.1.2 on Linux X64, Ananconda 4.3 with updated spyder via conda:
Opening files either from file explorer or menu results in a very very long wait before the new tab in the editor window is activated (the tab is created quick;y, but not brought to the front and given focus for 30 secs to a minute (seems to get worse with more editor tabs open, but perhaps that's just my frustration). There is a similar length of wait after pressing F5 to run the current script and it actually executing.
Reverting back to 3.1.2 (which I had to do as I had some classes to teach!) fixes these problems.

**Comment by ccordoba12** [comment]
@gb119 I haven't seen this problem (and I also use Linux). Do you have some spare time to help us with a `git bisect` to identify the faulty commit?

We can help you with instructions for that in case you need them :-)

**Comment by gb119** [comment]
Hi,
Realistically I won't have time until the weekend (too many undergraduate projects to mark :-( ), but happy to give it a go then. I'm never done git bisect before, but the documentation looks straightforward enough - presumably I need to spin a fresh anaconda environment, checkout spyder, mark the tags 3.1.3 as bas and 3.1.2 as good and go from there?

**Comment by ccordoba12** [comment]
Yep, that's basically it. To start Spyder from its git repo, you need to run

    python bootstrap.py

**Comment by gb119** [comment]
Ok, so I've had a play and now can't reproduce the problem ! Clearly simply posting on github fixes things..... so if it comes back again I'll know how to give you a more useful bug report - so that's all good then.

**Comment by ghisvail** [comment]
I can't reproduce the issue with spyder 3.1.3 on Debian. Perhaps, it would be wise to relax the milestone for this one, since it cannot be reliably triaged at this point.

**Comment by Gh0str1d3r** [comment]
Can I provide any additional information to assist?

**Comment by ccordoba12** [comment]
I can reproduce this bug, but I don't have time to fix it right now, sorry.

So I'm going to move it for 3.2, since it's mostly annoying.

**Comment by ccordoba12** [comment]
Yes, as soon as @dalthviz fixes issue #4191 (hopefully in a couple of days).

**Comment by rlaverde** [comment]
Any hints of how to reproduce this issue?

```
kf5.kio.core: Invalid URL: QUrl("f.py")
kf5.kio.core: Invalid URL: QUrl("fi.py")
```
This warning is raised by KDE input/output framework, maybe updating your KDE/Qt installation could fix this error

**Comment by Gh0str1d3r** [comment]
I'm on Gentoo Linux with all the available updates installed. Specifically, kio is in version 5.37.0 and Qt in version 5.7.1. I believe these are the latest available versions. Please let me know if there is any further information I can provide to track this issue down.

**Comment by ccordoba12** [comment]
@rlaverde, that's the same warning I'm seeing and what makes to save files slow. I think we should run a `git bisect` between 3.0 and 3.1 to detect the commit that introduced this problem.

**Comment by rlaverde** [comment]
>that's the same warning I'm seeing and what makes to save files slow. I think we should run a git bisect between 3.0 and 3.1 to detect the commit that introduced this problem.

Yes, but I can't reproduce it 😞

**Comment by ccordoba12** [comment]
I can, so I'll perform the bisect ;-)

**Comment by ccordoba12** [comment]
Note to self: the source of the problem is PR #3580.
