### ISSUE TITLE
Implement simple indentation fon non-python files

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4157]
As mentioned in #4096 It'll be useful the simple indentation mode:

"the automatic indentation to simply preserve the indentation-level of the previous line, leaving extra-indentation for multi-line expressions to the user."

And as mentioned in #4074 It will be useful for some users to completely deactivate indentation.

**Comment by ccordoba12** [comment]
I think we shouldn't add an options to Preferences for this. We'll simply use simple indentation for non-Python files and automatic indentation for Python ones :-)

@rlaverde, what do you think?

**Comment by rlaverde** [comment]
I was thinking in add an option; although that option was requested due to the errors in _automatic indentation_, and won't be necessary if we continue improving it (I'm planing to reorganize indentation code, and then rewrite some of the logic that is partially broken)

**Comment by ccordoba12** [comment]
> won't be necessary if we continue improving it

Agreed.

> I'm planing to reorganize indentation code, and then rewrite some of the logic that is partially broken

Great! Please focus on that for 3.2 ;-)
