### ISSUE TITLE
Spyder and Anaconda Navigator won't launch!

### ISSUE THREAD

**Issue by dalalkrish** [spyder-ide/spyder#4158]
## Description of your problem
I have Python 3.6.0 :: Anaconda 4.3.0 (64-bit) verion. When I try to launch using the dekstop icon or through the Command Promt, Neither Spyder nor Anaconda launches

The snapshot of the error is as below:
![spyder_error](https://cloud.githubusercontent.com/assets/15665826/23071412/45f9344e-f4fc-11e6-9fcf-02e0c6c74541.PNG)

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
*Anaconda Version: 4.3.0(64-bit)
* Python Version:3.6.0
* Qt Version:
* PyQt Version:
* Operating system: Windows 10(64-bit)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I think this is going to be fixed in the next Anaconda release (4.3.0.1). Please wait until that version is released an try again.

I'm closing this bug because there's nothing we can do to solve it. It has to do with how Anaconda is installed on Windows.

**Comment by sfchoudhury** [comment]
Hi, I am facing same issue while opening Navigator or trying to open Spyder. I have just installed a new version of Anaconda and still the problem lives. I can open anaconda prompt, jupyter notebook but not spyder or anaconda navigator. Could you please comment on what could be the issue. THank you very much
