### ISSUE TITLE
Disable pytest-xdist on circle ci testing

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4160]
This might prevent failing tests for the main window

**Comment by ccordoba12** [comment]
On a closer look, I don't think xdist is having any effect in our test suite because we're not calling it in any way.

So I'm moving this one to 3.1.4 for now :-)

**Comment by ccordoba12** [comment]
I really don't think this is needed after PR #4171 (which I verified is working, yay!!)
