### ISSUE TITLE
IPython console fails to start (Ipython >=6.x)

### ISSUE THREAD

**Issue by epifanio** [spyder-ide/spyder#4170]
## Description of your problem

**What steps will reproduce the problem?**

1. install latest IPython (>=6.x)
2. install spyder (git master)
3. run spyder3

**What is the expected output? What do you see instead?**

The Ipython console should start but instead it fails  with an import error for a missing module:

    ipython.core.utils.quick_guide

which is no more available in latest IPython.

**Please provide any additional information below**

just commenting the offending [line](https://github.com/spyder-ide/spyder/blob/3ea3f8fe6bcbfdec44db708c7895952c9e449205/spyder/widgets/ipythonconsole/shell.py#L91)  gives a working ipython console.

## Versions and main components

* Spyder Version: git master
* Python Version: 3.6
* Qt Version: 5.8
* PyQt Version: 5.7
* Operating system: Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Computer Used for testing not available at the moment of writing, I'll edit the issue once avaialable

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this bug in Spyder 3.1.4.

**Comment by ccordoba12** [comment]
@andfoy, you should surround the line mentioned mentioned by @epifanio with a try/except ImportError. The except part must make `quick_guide` an empty string.
