### ISSUE TITLE
Add a message to the Python console about its removal in Spyder 3.2

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#4172]
@dalthviz, the message should be added before the first prompt (i.e. `>>>`) and should say

> NOTE: The Python console is going to be removed in Spyder 3.2. Please start to migrate your work to the IPython console instead.

**Comment by proetman** [comment]
Hi
Are you going to add an option to "Execute in a new dedicated IPython console"?

We use this current option "Execute in a new dedicated Python console" exclusively for running programs.

**Comment by ccordoba12** [comment]
Yes, we will.
