### ISSUE TITLE
Add our required packages for testing to setup.py

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#4174]
This is needed to allow external packagers (e.g. Debian) to run our test suite in a simple and reproducible way.

For an example of how to do it, please see:

https://github.com/jupyter/notebook/blob/master/setup.py#L156

**Comment by rlaverde** [comment]
I'm not sure if It is the best way to add test dependencies, some people discourage the abuse of `extras_requirements` an prefer [tox](https://tox.readthedocs.io/en/latest/) instead.

What do you think? maybe It'll be better to add tox.ini? although tox [doesn't support ](https://github.com/tox-dev/tox/issues/273) conda enviroments :disappointed:

**Comment by ccordoba12** [comment]
Let's keep it simple for now. We can later consider tox, for now all I want is to have a place (beside our CI config files) to register our test deps.

**Comment by bilderbuchi** [comment]
Wouldn't you use setuptools' `tests_require` for packaging, well, *test* dependencies, instead of `extras_require`?

**Comment by ccordoba12** [comment]
`setuptools` is the devil ;-) I really don't like it, sorry. I still prefer to use `distutils`.

**Comment by bilderbuchi** [comment]
ah, I see.
