### ISSUE TITLE
Spyder crashes (segmentation fault) when saving html output from console

### ISSUE THREAD

**Issue by opi9a** [spyder-ide/spyder#4176]
## Description of your problem

Spyder crashes ("segmentation fault - core dumped") when saving html console output including a chart.

I've replicated on two installations on different machines.

**What steps will reproduce the problem?**

1. run a script from editor, outputting a chart to console, eg 
`plt.plot([1,2,3],[1,3,6])`

2. move focus to console displaying the output and attempt to save with Ctrl-S

3. in dialog box choose location etc, click save.  

**What is the expected output? What do you see instead?**

Application crashes.  On one machine terminal returns "Segmentation Fault, core dumped"

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6.0
* Qt Version: 5.6.2, PyQt5 5.6 on Linux
* PyQt Version: 5.6
* Operating system: Ubuntu 16.04 and Ubuntu 16.10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.1.3. Please update to that version (I just released it a couple of hours ago).

I you're using Anaconda, please wait until new conda packages are available (they should be in a couple of days :-).

**Comment by opi9a** [comment]
Ah!  I have been trying to install the 3.1.3 through Anaconda.  Thanks a lot I'll try in a few days.
