### ISSUE TITLE
Update dialog broken

### ISSUE THREAD

**Issue by joe-hilling** [spyder-ide/spyder#4179]
## Description

**What steps will reproduce the problem?**

1. Open the application when updates are available
2. Update window appears with message Spyder 3.1.3 is available! Dialog is broken.

**What is the expected output? What do you see instead?**

Both hyperlinks ('releases' and 'installation') are disabled in addition to the 'ok' button. Only the 'x' in the top right is functional. See attachment.

**Please provide any additional information below**
Windows 10. Pro.
![update window](https://cloud.githubusercontent.com/assets/3234868/23166468/a6a44d3a-f838-11e6-87f5-5f8e83144d66.PNG)

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. You need to update to Spyder 3.0.2 or newer to get the fix for this error.
