### ISSUE TITLE
Spider blocked at splash screen

### ISSUE THREAD

**Issue by michelecafagna26** [spyder-ide/spyder#4181]
## Description of your problem

**What steps will reproduce the problem?**

1. start spyder

**What is the expected output? What do you see instead?**
spyder remain at the splash screen on "loading outline explorer"

**Please provide any additional information below**
No error is shown, it's simply frozen

## Versions and main components

* Spyder Version: 3
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system: win 10
i've installed Anaconda2-4.3.0.1-Windows-x86_64 installer from www.continuum.io

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please run

    conda update spyder

in a terminal (i.e. cmd.exe), then

    spyder --reset

and try again.

**Comment by michelecafagna26** [comment]
it was the firewall...

thanks anyway!

**Comment by ccordoba12** [comment]
:+1: :+1:

**Comment by imranselim** [comment]
@michelecafagna26 how did you solve the firewall issue to run spyder?

**Comment by michelecafagna26** [comment]
I don't remeber, it was one year ago...  try to check this https://www.dummies.com/computers/pcs/computer-security/how-to-allow-firewall-exceptions-on-your-windows-10-laptop/

**Comment by imranselim** [comment]
I just restarted my PC and that worked. Thanks!
