### ISSUE TITLE
Spyder 3.1.3 won't start. ValueError position %d in history.log

### ISSUE THREAD

**Issue by maxiwu** [spyder-ide/spyder#4183]
## Description of your problem
I have install Anaconda3 4.3.0, then try to launch Spyder 3.1.3 in navigator. It crashes.
I've tried "python spyder --reset", does not resolve the issue.
The message I get from running "spyder --show-console"
Traceback
...\Anaconda3\lib\site-packages\spyder\app\mainwindow.py, line 2989, in main
    mainwindow = run_spyder(app, options, args)
........
........
File "...\Anaconda3\lib\configparser.py", line 401, in before_set "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '$USERPROFILE%'\\.spyder-py3\\history.log at position 12

and I have check, there is no such file in \\.spyder-py3

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please run

    spyder --reset

in a terminal (cmd.exe) and restart Spyder. That should fix your error.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
