### ISSUE TITLE
Feature Requests: Move scripts around editor bar

### ISSUE THREAD

**Issue by simonzcaiman** [spyder-ide/spyder#4188]
## Description of your request

I have several scripts open in the spyder editor. Is that possible to move scripts around in the editor bar? For example, I have 5 scripts open. Now I want to move my first script close to my third script. I tried to use mouse to drag the file and shift it back, but it didn't work. Am I doing something wrong here? Or May I request for this feature? 

Thank you so much. 

## Versions and main components

* Spyder Version:3.1.3
* Python Version:3.5.2
* Qt Version:
* PyQt Version:
* Operating system: Centos 7

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 3.2, to be released in two months or so.

Thanks for your patience.
