### ISSUE TITLE
Update conflict

### ISSUE THREAD

**Issue by charlesfox97** [spyder-ide/spyder#4190]
I'm getting a package conflict that I'm not sure how to resolve.

1) I ran activate py3  (py3 is a python 3 environment)
2) conda update spyder returns "all requested packages already installed.  : spyder 3.1.2
3) conda install spyder=3.1.3 returns "The following specifications were found to be in conflict: python 3.4*, spyder 3.1.3* -> python 2.7"

* Spyder Version: 3.1.3
* Python Version: 3.4.5
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: windows 10

**Comment by ccordoba12** [comment]
Python 3.4 is not supported anymore by Continuum, so no new Python packages of any kind will be created for that version, sorry.

**Comment by jitseniesen** [comment]
To be more explicit, you need to update python with `conda update python` and then you will be able to update spyder.

**Comment by ccordoba12** [comment]
Not exactly @jitseniesen: you'd need to create a new conda environment, then install Python 3.5 or 3.6 on it, and finally install Spyder.
