### ISSUE TITLE
accent (non-unicode) characters not working in editor, python or ipython console

### ISSUE THREAD

**Issue by nbonacchi** [spyder-ide/spyder#4192]
## Description
1. open spyder
2. type the one of the following chars (~ ^ ¨ ´ `)  using a portuguese keyboard (not sure the particular type of keyboard is the problem) 
3. Watch as nothing happens.

Affects editor, python and ipython console. In 3.1.2 also happened but it introduced a space... I thought it would get better and a problem only of the python console that is dying, unfortunately it got worst :( 
the ~ and the ^ are really annoying as they are the bitwise not and xor that I use quite a lot...

I believe that its something to do with modifier/accent keys, usually they need another key right after like 'space' - or need to be presses twice to yield just the char (e.g. á à ä ã â vs ~ ^ ¨ ´ `). did you forget about accents? or is it a specific portuguese keyboard thing?

EDIT: I've been copy-pasting the chars as needed but it's not optimal. I whish I had an N slot clipboard so I didn't have to copy-paste stuff and just paste it...

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This seems like a Qt but. We don't do anything specific about accents.

However, things are working fine for me in a Spanish keyboard. Sorry for not being more helpful.

**Comment by nbonacchi** [comment]
Just upgraded to Qt 5.6.2, still not seing accent chars...

**Comment by ccordoba12** [comment]
As I said, I can't reproduce this error, sorry.

**Comment by nbonacchi** [comment]
I think you can close this... I tested on my laptop with ubuntu 16.04 and could not reproduce... It's probably something funky with my analysis computer... I need to upgrade it from14.04 (as soon as I finish my PhD :P)

**Comment by ccordoba12** [comment]
:+1:

**Comment by bw-mutley** [comment]
This issue is also happening to me with spyder 5.3 and python 10. Accents work under spyder 4, though. This is my QT instalation along spyder 5.3:

```
pyqt                      5.15.7          py310h6a678d5_1
qt-main                   5.15.2               h327a75a_7  
qt-webengine              5.15.9               hd2b0992_4  
qtawesome                 1.0.3              pyhd3eb1b0_0  
qtconsole                 5.2.2              pyhd3eb1b0_0  
qtpy                      2.2.0           py310h06a4308_0  
qtwebkit                  5.212                h4eab89a_4  
```

**Comment by Zincr0** [comment]
Same problem, tested on Spyder 5.3.3 today with PyQt5 5.15.7 and ubuntu 20.04 on a conda enviroment.

**Comment by bw-mutley** [comment]
@Zincr0 I don't know if they will see this one, since it's closed. Start a new one maybe?

**Comment by Zincr0** [comment]
ok, gonna create a new one.
