### ISSUE TITLE
jedi version update

### ISSUE THREAD

**Issue by drammock** [spyder-ide/spyder#4193]
jedi is now on version `0.10.0`, but spyder's dependency list asks for `=0.9.0` rather than `>=0.9.0` so I'm getting dependency warnings on startup.  Have you tested and found that there is actually a problem with `0.10.0`?  If not, could you change the dependency requirement to `>=`?

**Comment by ccordoba12** [comment]
Yes, there are several problems. @bcolsen is trying to fix them in PR #4121.

Our wheels correctly set this requirement to 0.9.0, so I assume you're using conda/conda-forge. Conda-forge has a PR to fix this, so it should be available soon.

However, our conda packages don't have this requirement, so I'll fix that in a couple of days.

**Comment by drammock** [comment]
thanks, I'll downgrade jedi for now then.  FWIW  I'm not using conda or conda-forge, just system python and `python3 bootstrap.py` to launch
