### ISSUE TITLE
Re-running script causes internal error

### ISSUE THREAD

**Issue by drammock** [spyder-ide/spyder#4194]
## Description
if I run a script in its own dedicated console tab, with "interact with the console after running", then I cannot re-run the script without first manually closing the console tab.

**What steps will reproduce the problem?**

1. run a script in it's own dedicated console tab, with the "interact after running" option.
2. try to run it again without first closing the console tab

**What is the expected output? What do you see instead?**
Should see a popup saying "already running in an existing console, do you want to close and re-run?" (or similar, I forget the exact wording of the message).  Instead, the internal console gives this:
```
Traceback (most recent call last):
  File "/home/drmccloy/Builds/spyder/spyder/plugins/editor.py", line 2357, in run_file
    self.re_run_file()
  File "/home/drmccloy/Builds/spyder/spyder/plugins/editor.py", line 2405, in re_run_file
    systerm, post_mortem)
  File "/home/drmccloy/Builds/spyder/spyder/app/mainwindow.py", line 2419, in open_external_console
    python_args=to_text_string(python_args) )
  File "/home/drmccloy/Builds/spyder/spyder/plugins/externalconsole.py", line 515, in start
    if PYQT5:
NameError: name 'PYQT5' is not defined
```

**Please provide any additional information below**
This happens on spyder with Qt5/py3 and also with Qt4/py2, same traceback.

## Version and main components

* Spyder Version: 4.0.0.dev0 7e1ea42
* Python Version: 3.5.2
* Qt Versions: 5.8.0, PyQt5 5.8 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
numpy >=1.7      :  1.11.0 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi =0.9.0      :  0.10.0 (NOK)
psutil >=0.3     :  5.1.3 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
The Python console is going to be removed in Spyder **3.2**, so we're not going to fix more bugs for it, sorry. However, we'll be sure to migrate all its functionality to the IPython console.

Please use the IPython console instead, if possible.
