### ISSUE TITLE
spyder3 crashes while loading on windows 8.1

### ISSUE THREAD

**Issue by pratikhunny** [spyder-ide/spyder#4195]
## Description of your problem
spyder 3 crashes while starting up, this happens while it is in loading editor phase. 
**What steps will reproduce the problem?**

1. download Anaconda3-4.3.0.1-Windows-x86_64.exe for python 3.5
2. install it with recommended settings.
3. open spyder by clicking on its icon.

**What is the expected output? What do you see instead?**
Spyder should open up but instead while loading editor it prompts python has stopped working

**Please provide any additional information below**
while starting up,it goes through initialization and loading help phase but after a minute or so as soon as it reaches loading editor phase it prompts python not working.tried uninstalling and reinstalling but no effect.

## Versions and main components
current conda install:

              platform : win-64
         conda version : 4.3.8
      conda is private : False
     conda-env version : 4.3.8
   conda-build version : not installed
        python version : 3.6.0.final.0
      requests version : 2.12.4
      root environment : C:\Users\user\Anaconda3  (writable)
   default environment : C:\Users\user\Anaconda3
      envs directories : C:\Users\user\Anaconda3\envs
         package cache : C:\Users\user\Anaconda3\pkgs
          channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                         https://conda.anaconda.org/anaconda-fusion/noarch
                         https://repo.continuum.io/pkgs/free/win-64
                         https://repo.continuum.io/pkgs/free/noarch
                         https://repo.continuum.io/pkgs/r/win-64
                         https://repo.continuum.io/pkgs/r/noarch
                         https://repo.continuum.io/pkgs/pro/win-64
                         https://repo.continuum.io/pkgs/pro/noarch
                         https://repo.continuum.io/pkgs/msys2/win-64
                         https://repo.continuum.io/pkgs/msys2/noarch
           config file : C:\Users\user\.condarc
          offline mode : False
            user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/8.1
windows/6.3.9600

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please open a terminal (cmd.exe) and run

    spyder --show-console

then post any errors reported there here. Thanks!

**Comment by ccordoba12** [comment]
Closing because of lack of response.
