### ISSUE TITLE
In Spyder 3.1.3, Ubuntu 16.04, and Python 2.X editor is not working

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4200]
## Description
Hi, I just upgraded Spyder to 3.1.3 through pip.  Now after the upgrade I cannot move my cursor or type anything with my keyboard in the editor.  The Python console is fine
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.1.3 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
Please use Qt/PyQt 5 instead. This clearly seems a Qt bug instead of a Spyder one.

The problem is Qt4 is not maintained anymore, and no new releases are going to be made for it by the company that creates Qt.

**Comment by ccordoba12** [comment]
Packages for Qt5 are available in Ubuntu since 14.04, I think, so you should be fine.

**Comment by s0r2637** [comment]
I am sorry for the lame question.  Actually, I did not have permissions to
write on the files because it was under the 'root' for some reasons.  So,
no problems with Spyder at all.  Sorry for the trouble.

Srini

**Comment by ccordoba12** [comment]
Ohh, I see. No worries then ;-)
