### ISSUE TITLE
cannot run spyder / ImportError: No module named animation

### ISSUE THREAD

**Issue by echuaba** [spyder-ide/spyder#4209]
## Description of your problem

**What steps will reproduce the problem?**

1. I installed spyder through anaconda navigator
2. Try to launch the application but it gives no response
3. Run spyder --show-console in the anaconda terminal:
(C:\Users\Chuanhai.Bai\AppData\Local\Continuum\Anaconda2) C:\Users\Chuanhai.Bai>
spyder --show-console
Traceback (most recent call last):
  File "C:\Users\Chuanhai.Bai\AppData\Local\Continuum\Anaconda2\Scripts\spyder-s
cript.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\Chuanhai.Bai\AppData\Local\Continuum\Anaconda2\lib\site-package
s\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Users\Chuanhai.Bai\AppData\Local\Continuum\Anaconda2\lib\site-package
s\spyder\app\mainwindow.py", line 95, in <module>
    from qtawesome.iconic_font import FontError
  File "C:\Users\Chuanhai.Bai\AppData\Local\Continuum\Anaconda2\lib\site-package
s\qtawesome\__init__.py", line 20, in <module>
    from .animation import Pulse, Spin
ImportError: No module named animation

**What is the expected output? What do you see instead?**
It should start spyder directly

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3                    py27_0
* Python Version: 2.7.13                        0
* Qt Version: 5.6.2                     vc9_3  [vc9]
* PyQt Version: 5.6.0                    py27_2
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please run

    conda install -f qtawesome

to fix this error.

**Comment by echuaba** [comment]
Thanks ccordaba12, i found the same root cause :)

**Comment by ccordoba12** [comment]
:+1:
