### ISSUE TITLE
Spyder debugger doesn't terminate

### ISSUE THREAD

**Issue by titibachie** [spyder-ide/spyder#4214]
Hello all,

I am very new to Spyder and am using Spyder 3.1.2 from Anaconda 4.3.0. I have problems with the Spyder's debugger:
1. I set a breakpoint at the intended command line to check the results.
2. Press cmd+F5: the current frame is alway highlighted at beginning command line. I need to press 'c' or 'continue' on menu to move to the intended command line.
3. If I want to quit debugging by pressing cmd+shift+F12, the debugger doesn't terminate. It runs until the last command.

I really appreciate if anyone help me for this.

Thank you.

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: mac

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by Davo36** [comment]
I have the same issue, but I'm using version 3.3.

Here is my dependcy info:

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
This bug will be solved in Spyder 3.2, sorry for the inconvenience.

**Comment by bcolsen** [comment]
@ccordoba12 I still see this issue on the latest 3.x

debug like this:
```
      4 x = 1
2---> 5 y = 2
      6 z = 3
```
It breaks on line 5 and x is defined but not y

I stop the debug and x, y, and z are defined.

I also have simulation code that runs for a couple minutes.  I put a break point in the first loop and it stopped there. I hit stop and the code continued to the end, originally I though I crashed ipdb

**Comment by ccordoba12** [comment]
I can't reproduce this, sorry.

![seleccion_001](https://user-images.githubusercontent.com/365293/27753145-1ef74e32-5daa-11e7-8289-4b8bb40cc836.png)

**Comment by ccordoba12** [comment]
I put a break point in the `y` line, enter debugging and then press the Stop button.

**Comment by bcolsen** [comment]
I reset to factory and I still get this when I debug:
```
In [1]: debugfile('/home/bcolsen/Documents/python/debug_test.py', wdir='/home/bcolsen/Documents/python')
> /home/bcolsen/Documents/python/debug_test.py(3)<module>()
      1 #!/usr/bin/env python3
      2 # -*- coding: utf-8 -*-
----> 3 x = 1
1     4 y = 2
      5 print("don't run")

> /home/bcolsen/Documents/python/debug_test.py(4)<module>()
      2 # -*- coding: utf-8 -*-
      3 x = 1
1---> 4 y = 2
      5 print("don't run")
      6 z = 3

ipdb> 
ipdb>
```

Then I hit stop  and get this:
```
In [1]: debugfile('/home/bcolsen/Documents/python/debug_test.py', wdir='/home/bcolsen/Documents/python')
> /home/bcolsen/Documents/python/debug_test.py(3)<module>()
      1 #!/usr/bin/env python3
      2 # -*- coding: utf-8 -*-
----> 3 x = 1
1     4 y = 2
      5 print("don't run")

> /home/bcolsen/Documents/python/debug_test.py(4)<module>()
      2 # -*- coding: utf-8 -*-
      3 x = 1
1---> 4 y = 2
      5 print("don't run")
      6 z = 3


ipdb> don't run

ipdb> 

In [2]: y
Out[2]: 2

In [3]: 
```

I did a factory reset as well.  I also noticed that your `ipdb>' prompt is output on the right line.

## Versions and main components

* Spyder Version: 3.x at commit (https://github.com/spyder-ide/spyder/commit/6141665)
* Python Version: 3.6 64-bit
* Qt Version: Qt 5.6.2
* PyQt Version: PyQt5 5.6
* Operating system: Linux

## Dependencies

cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
pycodestyle >=2.3:  None (NOK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by bcolsen** [comment]
I fixed it....

I upgraded IPython
ipython: 5.1.0-py36_0 --> 6.1.0-py36_0

The prompt is still off but I'm not worried

**Comment by ccordoba12** [comment]
Yay!! Really great news!

**Comment by usmanov** [comment]
can't stop debugging 
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@usmanov, you need to update IPython.

**Comment by mmagnuski** [comment]
> can't stop debugging

I think it might have meant that debugging is so good in Spyder that one just cannot stop! :)
