### ISSUE TITLE
An error occurred while starting the kernel.

### ISSUE THREAD

**Issue by senserad** [spyder-ide/spyder#4215]
![Uploading erroranaconda.jpg…]()
## Description of your problem
Till now I was using spyder very smoothly. But Recent update with conda has created this issue. I am using windows 8.1. 

I have tried conda --reset but it didnt worked.
I have tried conda update setuptools still the kernel 

**What steps will reproduce the problem?**

1. updating conda
![Uploading erroranaconda.jpg…]()

**What is the expected output? What do you see instead?**
![Uploading image.png…]()

**Please provide any additional information below**

## Versions and main components

* Spyder Version:2.3.4
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system: win 8.1
* Conda:4.3.13

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please update Spyder to 3.1.3 (its latest version) and try again. That error should be fixed now.
