### ISSUE TITLE
"Unable to connect to the internet" problem

### ISSUE THREAD

**Issue by HHest** [spyder-ide/spyder#4217]
When spyder starts up, or when I check for update, I get this warning. I am behind a company firewall. I do not know how to configure Spyder to know about our proxy.

I installed Spyder via pip install, and I do not have anaconda. From a browser I can get to "https://api.github.com/repos/spyder-ide/spyder/releases" without any problem.

Thank you.

* Spyder Version: 3.1.3
* Python Version: 2.7.13
* Qt Version: 4
* PyQt Version: 4.11.4
* Operating system: Windows 7

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Please go to

    Tools > Preferences > General > Advanced Settings > Check for updates on startup

and disable it.

**Comment by HHest** [comment]
Thanks for that. Just to clarify: I should disable this check on startup, and if I want to update spyder, I should manually run "pip install -U spyder", right?

**Comment by ccordoba12** [comment]
Yeah, if you deactivate that option then you should stop seeing that annoying message. The dialog just informs you that a new version is available, but it won't update it for you, so in any case you need to run `pip install -U spyder` to do it.

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one. The idea is *not* show the message about not being able to connect to the internet if it's not possible to do it.

That will avoid annoying our users, specially the ones that work on environments with restricted connectivity.
