### ISSUE TITLE
spyder blanks out main window after display change in Win7

### ISSUE THREAD

**Issue by Chaos99** [spyder-ide/spyder#4220]
## Description
After certain display events (connecting/disconnecting a second monitor, switching between extended/mirrored display, turning display on/off in sleep mode), the spyder window blanks out with all black color. The editor seems to run fine, as shortcuts still work, right-click menus still appear and even the cursor changes shape when hovering over different areas.

**What steps will reproduce the problem?**

1. Open Spyder, start editing
2. connect a second monitor, switch form mirror to extend displays
3. disconnect the second monitor
(works approx. 1 times out of 5)

or

2. put laptop to sleep mode
3. wake up laptop
(works approx 1 times out of 3)

It might make a difference if the window is minimized or on which desktop it is currently displayed. Not sure.

**Please provide any additional information below**
Win7 on a Lenovo Thinkpad W520
(switches back and forth between accelerated NVIDIA graphics and INTEL chipset graphics )

## Versions and main components

* Spyder Version: All Spyder versions delivered with WinPython3 64bit since mid 2015, now 3.1.2
* Python Version: 3.4, 3.5, 3.6, now 3.6.0
* Qt Version: 4 and 5, now 5.7.1
* PyQt Version: PyQt4 and 5, now PyQt5 5.7.1
* Operating system: Win7 64bit

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by Chaos99** [comment]
As this is probably a QT redraw issue: my best hopes are just for a workaround to manually trigger a UI redraw.

**Comment by ccordoba12** [comment]
Yep, this really seems more like a Qt issue than a Spyder one.

**Comment by jdchristesen** [comment]
I've just had this happen when trying to use Spyder through remote desktop. I can access everything in Spyder, but the main window is completely black.

**Comment by stonebig** [comment]
maybe try with PyQt-5.8.0 on current Winpython-3.6.0.1  beta (or more recent)

**Comment by Chaos99** [comment]
Will try.
But I had this issue with various WinPython releases, so also with older Spyder and Qt versions.
I can also say that Spyder is the only app that shows this. Neither other Qt apps nor even PyQt apps written by me with exactly the installed WinPython/PyQt/Qt version show any similar behavior.
Maybe the bug is within Qt, but only some very special way Spyder is using the framework really makes this visible.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by Chaos99** [comment]
Tried switching the window style in the preferences to force a window update: style change worked (in the preferences window), but still black main window.
Switched to PyQt5.8.1 for testing.

**Comment by Chaos99** [comment]
Tried with 
Spyder 3.1.3 
Python 3.6.0
QT 5.8.0
PyQt5 5.8.1

Still blank window after wake-up from sleep.

**Comment by dalthviz** [comment]
Hi @Chaos99 I couldn't reproduce the bug you report. However, can you try to run spyder from console an see if any error is shown there? you can run from cmd `spyder --show-console` for this.

**Comment by arman00** [comment]
I have the same problem. Spyder main window is completely black when I start Spyder from Remote Desktop Connection. However, if Spyder is already open in the the remote machine, I can use Spyder without this issue. It only happens when I restart through Remote Desktop Connection.

Also, I cmd line arguments do not work on my PC. Running with --show-console, --help, etc. , looks like is not any different from running spyder. Not sure if this is also another bug or not.

Spyder 3.1.4 and 3.2beta
Python 3.5.3
PyQT 5.8.1

**Comment by ccordoba12** [comment]
@arman00, your problem is different to the one discussed here. I think it's caused by PyQt5 wheels, so please try to use Anaconda and try again.

**Comment by ccordoba12** [comment]
The thing is Anaconda comes with a different implementation of Qt web widgets, and that could help to fix this problem.

**Comment by goanpeca** [comment]
@CAM-Gerlach when you have some time could you helps us see if you can reproduce this? Thanks!

**Comment by CAM-Gerlach** [comment]
I do this all the time multiple times a day with Spyder (4) open with multiple different monitors and display changes, for years, and I've never seen this effect at least not on Spyder 4. However, that's on 8.1 and 10, not 7. I don't have a readily available 7 machine to test on anymore with 7 being almost EoL.

**Comment by CAM-Gerlach** [comment]
I would guess this is fixed either with newer Qt/PyQt/QtPy, newer OS, newer Spyder (e.g. opengl rendering options changes) or was something specific to a particular GPU/driver/etc. that can't be easily reprod.
