### ISSUE TITLE
Python Won't Start, HELP!

### ISSUE THREAD

**Issue by TRS0I777** [spyder-ide/spyder#4227]
#Description of your problem

**What steps will reproduce the problem?**

1. Opening Python 
2. Python Crashes before it starts

**What is the expected output? What do you see instead?**
It says to reset Spyder with command line "python Spyder --reset":
![image](https://cloud.githubusercontent.com/assets/26190980/23582142/7e302df6-00e9-11e7-9cad-90a766aebfa6.png)

**Please provide any additional information below**
I have ran the reset command line and removed the all the configuration files, and Spyder won't start still.
I also get this when I run "--show-console"
![image](https://cloud.githubusercontent.com/assets/26190980/23582395/e4d736b2-00ee-11e7-8edb-ea26ed196013.png)
PLEASE HELP ME! I have a project due Monday and I need to edit things
## Versions and main components

* Spyder Version: 4.3.0
* Python Version: 3.6.0
* PyQt Version:
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
Please run in a terminal

    conda update spyder
    conda update ipython

to see of that fixes your problem.

**Comment by TRS0I777** [comment]
I tried with both but no success. This is what I Got for the first command line:
![image](https://cloud.githubusercontent.com/assets/26190980/23582530/e325835c-00f1-11e7-9add-d85df3d211c5.png)

And for the second:
![image](https://cloud.githubusercontent.com/assets/26190980/23582537/0362984e-00f2-11e7-9e7a-af5253a5202c.png)

**Comment by TRS0I777** [comment]
@ccordoba12 
I reinstalled anaconda to be available for my user instead of all users.  I then was able to run the commands but it still won't start.  Any other suggestions if you are not busy?

**Comment by ccordoba12** [comment]
I really don't know what's happening in your case, but the error is not in Spyder but in another package called IPython.

You could try to open the file `...\site-packages\IPython\utils\io.py` and remove/replace or surround with a try/except the line that's giving you problems.

**Comment by TRS0I777** [comment]
@ccordoba12 
Thank you for your time and sorry if I was bothering you.

**Comment by ccordoba12** [comment]
Not a problem, don't worry. I hope you've made Spyder to work with my advice :-)
