### ISSUE TITLE
delete (context="editor", name="delete") keyboard shortcut doesn't work

### ISSUE THREAD

**Issue by cyga** [spyder-ide/spyder#4231]
## Description of your problem

**What steps will reproduce the problem?**

1. go to tools > preferences > keyboard shorcuts
2. assign keyboard shortcut for context = "editor", name = "delete".
    I tried at least: meta+x, meta+q, meta+a, ctrl+y, alt+y.
    meta+a and meta+q works as shortcut for start of line (context = "editor")
3. use assign shortcut in text editor
4. nothing changes

**What is the expected output? What do you see instead?**

1. character after cursor will be deleted

**Please provide any additional information below**

I try to use shortcuts similar to emacs, to edit files using blind method for typing. moving finger to delete button doesn't work for it.
No backspace key binding at all - is it some sort of system limitation?

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.13 64bits
* Qt Version: 5.6.2
* PyQt Version: PyQt5 5.6 on Linux
* Operating system: ubuntu xenial x86_64 4.4.0-57-generic

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to solve this one for Spyder 3.2

**Comment by csabella** [comment]
The shortcut key actually did work, but was only defined to delete selected text.  The change will allow it to delete the character after the cursor if no text is selected.
