### ISSUE TITLE
I run spyder in xshell and win10, xshell login remote ubuntu16.04LTS, spyder can open and use. but  The key to the keyboard is not the corresponding letter.

### ISSUE THREAD

**Issue by whaozl** [spyder-ide/spyder#4236]
![1488967145 1](https://cloud.githubusercontent.com/assets/6327360/23699143/0c6e20d6-0429-11e7-85cf-12e766054961.png)

**Comment by whaozl** [comment]
I run `setxkbmap`,and show `XKB extension not present on localhost:10.0`

**Comment by ccordoba12** [comment]
@mingwandroid, a little help here please :-) I don't know if the error is caused because something is missing in our Qt packages or because the user needs to install a missing X extension.

**Comment by whaozl** [comment]
@ccordoba12 where is X extension? Can you provide a download link or install cmd?

**Comment by mingwandroid** [comment]
I have no idea about this and am too busy to look into it I'm afraid..

**Comment by ccordoba12** [comment]
@mingwandroid, no problem. Thanks for chiming in :-)

**Comment by whaozl** [comment]
sorry,sorry. hahahaha

**Comment by ccordoba12** [comment]
Sorry but this is not a problem with Spyder but with Qt and Xorg. So I'm closing this issue.
