### ISSUE TITLE
AttributeError: module 'scipy' has no attribute 'signal'

### ISSUE THREAD

**Issue by Bern-Alberts** [spyder-ide/spyder#4238]
## Description
"AttributeError: module 'scipy' has no attribute 'signal' ", I get this error each time I want to use scipy.signal
**What steps will reproduce the problem?**
The problem repeats, I had the previous version of Anaconda and it did the same thing, I hoped updating and reinstalling would solve the problem but it did not. 
1. 
2. 
3. 

**What is the expected output? What do you see instead?**
I expected scipy to work.

**Please provide any additional information below**
I realised that "from scipy import *" works. 

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry but this is not a Spyder bug. It's really a bug in Scipy.

That's why I'm closing this issue.

**Comment by jitseniesen** [comment]
> "AttributeError: module 'scipy' has no attribute 'signal' ", I get this error each time I want to use scipy.signal

@Bern-Alberts You are probably not using scipy as it is supposed to be used. 

https://docs.scipy.org/doc/scipy-0.18.1/reference/tutorial/general.html says: Scipy sub-packages need to be imported separately, for example: `from scipy import signal`

**Comment by ccordoba12** [comment]
Thanks @jitseniesen for the clarification :-)

**Comment by Bern-Alberts** [comment]
Thanks :)
