### ISSUE TITLE
Pyautogui locateCenterOnScreen issue

### ISSUE THREAD

**Issue by JWoody95** [spyder-ide/spyder#4240]
The locateCenterOnScreen method of pyautogui has stopped working on my computer. It used to work perfectly but now it won't move the mouse; alos, the code won't raise an error. If it can't find the png file on screen it just carries on. This isn't due to an Error Handling clause it's doing it on it's own.

Any help would be appreciated.

**Comment by ccordoba12** [comment]
I'm sorry but this is not a Spyder bug or error. Please find the right place to report this problem (i.e. the pyautogui issue tracker).
