### ISSUE TITLE
plugins problem

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder#4243]
I cant get the plugins to work in spyder

**What steps will reproduce the problem?**

1. I used conda to install two plugin packages
2. conda-manager
3. line profiler
i dont know how to conect them to spyder cant fined any doc on the subject.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.5
* Qt Version: Qt5
* PyQt Version:
* Operating system:windows 10 64bit

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
* conda-manager is not working right now.
* How did you install line-profiler?

**Comment by boazdori** [comment]
i did conda install line-profiler once done transfered the pkg to the 
C:\Users\user\.spyder-py3\plugins directory mapped the pythonpath to that directory as well

**Comment by ccordoba12** [comment]
The package that you get with `conda install line-profiler` is not a Spyder plugin, and that's why is not working for you.

[spyder-line-profiler](https://github.com/spyder-ide/spyder-line-profiler/) is not released yet, but we hope it will be soon. Sorry for the confusion.
