### ISSUE TITLE
Windows 150% display scaling too big

### ISSUE THREAD

**Issue by Atnas1010** [spyder-ide/spyder#4244]
## Description

**What steps will reproduce the problem?**

1. Set windows to 150% DPI scaling
2. Open Spyder with "Enable high DPI scaling" turned on (as things are too small otherwise)

**What is the expected output? What do you see instead?**
I expected all text and icons to have a size fitting to the chosen scale in windows.
However, the icons in the top row are too large and so is the content of the help window.

Screenshot at 150% scaling:
https://i.imgur.com/uxt7ou7.png

**Please provide any additional information below**
If I use 200% display scaling, things look harmonic. It seems that the top icons and help content use 200% scaling, even at 150% scaling.
Screenshot at 200% scaling:
https://i.imgur.com/TEuk8nP.png

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.6.0
* Qt Versions: 5.8.0, PyQt5 5.8 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
There's nothing we can do about this (as far as I know). It's something handled by Qt, not by Spyder.

But thanks for reporting.
