### ISSUE TITLE
runfile is not defined

### ISSUE THREAD

**Issue by adityaroyal** [spyder-ide/spyder#4250]
'runfile' is not defined in python 2.7

**What steps will reproduce the problem?**

1. I opened my anaconda prompt and I got this message everytime without typing anything
2. I am using python 2.7 for some time but suddenly this error appeared today without updating anything
3. I had tried number of solutions but those did not work for me

**What is the expected output? What do you see instead?**
when I tried
 set SPYDER_DEBUG=2
spyder --show-console I get
'import sitecustomize' failed; use -v for traceback
'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "C:\Users\aditya royal\Anaconda2\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Users\aditya royal\Anaconda2\lib\site-packages\spyder\app\start.py", line 104, in main
    mainwindow.main()
  File "C:\Users\aditya royal\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2955, in main
    or options.optimize)
  File "C:\Users\aditya royal\Anaconda2\lib\site-packages\spyder\utils\windows.py", line 33, in set_attached_console_visible
    return bool(ShowWindow(console_window_handle, flag[state]))
KeyError: 3
**Please provide any additional information below**
I am using python 2.7 and I am getting this error 
I had tried solving my adding the path in my environment variable but the error still there and I also tried stopping my firewall for sometime, I also tried spyder --reset, spyder --default and the problem still persists
## Versions and main components

* Spyder Version:2.7
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system: windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by adityaroyal** [comment]
I had finally found an answer 
Recently I named a file csv.py, I deleted it and everything is fine now

**Comment by ccordoba12** [comment]
Great!!

**Comment by adityaroyal** [comment]
I am still getting the error not in spyder but in anaconda prompt I am getting 'import sitecustomize' failed; use -v for traceback
