### ISSUE TITLE
No master changes

### ISSUE THREAD

**Issue by techtonik** [spyder-ide/spyder#4254]
There seems to be a lot of commits in `master` that are not related to latest 3.1.x release, but master changelog is empty. Is it possible to update it periodically?

https://github.com/spyder-ide/spyder/compare/3.1.x...master

**Comment by ccordoba12** [comment]
You can take a look at the milestone that tracks master right now: https://github.com/spyder-ide/spyder/milestone/23

Or you can use our own [Loghub](https://github.com/spyder-ide/loghub/) to get a more clear view of what's been added or changed. We created Loghub and use milestones heavily to avoid updating our changelog a lot.

**Comment by techtonik** [comment]
That's crazy, but awesome! :D
