### ISSUE TITLE
How to get the Pydaqmx library on Spyder ?

### ISSUE THREAD

**Issue by arcanor23** [spyder-ide/spyder#4255]
## Description of your problem

**What steps will reproduce the problem?**
Trying to run DAqmxconfig.py  on a Windows 10 pc seems to lead to this error ( 2 attempts on 2 different computers)

**What is the expected output? What do you see instead?**
I get this error : 
NotImplementedError: Location of niDAQmx library and include file unknown on win32 - if you find out, please let the PyDAQmx project know
It seems that DAqmxconfig.py only knows the location of the Library on Windows XP/7 but not on 10. Then I tried to replace the default location by the current one but no success so far.

**Please provide any additional information below**
I'm completely new to both spyder on National instrument DAQ cards. So far I've managed to install the Ni DAQ driver but I can't get the Pydaqmx Library on spyder due to this error.

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 2.7.13
* Qt Version:
* PyQt Version:4.2.1
* Operating system: Win 10

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I'm sorry but this is not a Spyder bug and we don't know about the Pydaqmx library to help you (first time I've heard about it).

So I'm closing this issue.
