### ISSUE TITLE
Numpy array copy format

### ISSUE THREAD

**Issue by takumi601** [spyder-ide/spyder#4257]
I frequently do copying float precision Numpy array data from variable explore and pasting it to Excel. 
At this time, the number pasted to Excel is recognized in exponential format, is it specification? 
Can you fix it so that it is recognized in numerical form?

Versions and main components
  Spyder Version: 3.1.3
  Python Version: 3.6
  OS: windows 7 pro

**Comment by ccordoba12** [comment]
Thanks for reporting. @dalthviz, please take a look at this one to see if we can do something about it.

**Comment by takumi601** [comment]
Thank you .
