### ISSUE TITLE
spyder/python crashes after a while of inactivity MacOS 10.12.3

### ISSUE THREAD

**Issue by markushartmann** [spyder-ide/spyder#4261]
1. I installed spyder 3.1.3 with macports and with all its dependencies. 
2. I started spyder with the terminal. 
3. I worked a few hours and than left the program open. 
4. After about an hour the program crashes  (The behaviour is reproduce able on my machine)

Unfortunately jedi is in the wrong version, probably this already is the error? 
But 0.10.0 is the version that macports installs.  

Attached the installed packages regarding python:

`py-sympy_select @0.2_0 (active)
  py27-alabaster @0.7.6_0 (active)
  py27-altgraph @0.13_0 (active)
  py27-appdirs @1.4.3_0 (active)
  py27-appnope @0.1.0_0 (active)
  py27-astroid @1.4.9_0 (active)
  py27-babel @2.3.4_0 (active)
  py27-backports @1.0_0 (active)
  py27-backports-functools_lru_cache @1.2.1_0 (active)
  py27-backports-shutil_get_terminal_size @1.0.0_0 (active)
  py27-backports_abc @0.5_0 (active)
  py27-bottleneck @1.2.0_0 (active)
  py27-cairo @1.10.0_3 (active)
  py27-certifi @2017.01.23_0 (active)
  py27-chardet @2.3.0_0 (active)
  py27-configparser @3.5.0_0 (active)
  py27-cycler @0.10.0_0 (active)
  py27-cython @0.25.2_0 (active)
  py27-dateutil @2.6.0_0 (active)
  py27-decorator @4.0.11_0 (active)
  py27-docutils @0.13.1_0 (active)
  py27-entrypoints @0.2.2_0 (active)
  py27-enum34 @1.1.6_0 (active)
  py27-flake8-mccabe @0.6.1_0 (active)
  py27-functools32 @3.2.3-2_0 (active)
  py27-gnureadline @6.3.3_1 (active)
  py27-h5py @2.6.0_0 (active)
  py27-imagesize @0.7.1_0 (active)
  py27-ipykernel @4.5.2_0 (active)
  py27-ipython @5.3.0_0 (active)
  py27-ipython_genutils @0.1.0_0 (active)
  py27-isort @4.2.5_0 (active)
  py27-jedi @0.10.0_0 (active)
  py27-jinja2 @2.9.5_0 (active)
  py27-jsonschema @2.6.0_0 (active)
  py27-jupyter_client @5.0.0_0 (active)
  py27-jupyter_core @4.3.0_0 (active)
  py27-lazy_object_proxy @1.2.2_0 (active)
  py27-logilab-common @1.3.0_0 (active)
  py27-macholib @1.8_0 (active)
  py27-markupsafe @0.23_0 (active)
  py27-matplotlib @2.0.0_1+cairo (active)
  py27-mistune @0.7.3_0 (active)
  py27-modulegraph @0.14_0 (active)
  py27-monotonic @1.2_0 (active)
  py27-mpmath @0.19_0 (active)
  py27-nbconvert @4.2.0_1 (active)
  py27-nbformat @4.2.0_0 (active)
  py27-nose @1.3.7_0 (active)
  py27-numexpr @2.6.2_0 (active)
  py27-numpy @1.12.0_0+gfortran (active)
  py27-packaging @16.8_0 (active)
  py27-pandas @0.19.2_0 (active)
  py27-parsing @2.2.0_0 (active)
  py27-path @10.1_0 (active)
  py27-pathlib2 @2.2.1_0 (active)
  py27-pep8 @1.7.0_0 (active)
  py27-pexpect @4.2.1_0 (active)
  py27-pickleshare @0.7.4_0 (active)
  py27-pkgconfig @1.1.0_0 (active)
  py27-prompt_toolkit @1.0.9_0 (active)
  py27-psutil @5.1.3_0 (active)
  py27-ptyprocess @0.5.1_0 (active)
  py27-py2app @0.12_0 (active)
  py27-pyflakes @1.5.0_0 (active)
  py27-pygments @2.2.0_0 (active)
  py27-pylint @1.6.5_0 (active)
  py27-pyobjc @3.0.4_0 (active)
  py27-pyobjc-cocoa @3.0.4_1 (active)
  py27-pyqt4 @4.12.0_0 (active)
  py27-pyqt5 @5.8_0
  py27-pyqt5 @5.8_0+webengine (active)
  py27-qtawesome @0.4.4_0 (active)
  py27-qtconsole @4.2.1_0 (active)
  py27-qtpy @1.2.1_0
  py27-qtpy @1.2.1_0+qt5 (active)
  py27-requests @2.13.0_0 (active)
  py27-roman @2.0.0_0 (active)
  py27-rope @0.9.4_0 (active)
  py27-scandir @1.5_0 (active)
  py27-scientific @2.9.4_1 (active)
  py27-scipy @0.18.1_0+gfortran (active)
  py27-setuptools @34.3.1_0 (active)
  py27-simplegeneric @0.8.1_0 (active)
  py27-singledispatch @3.4.0.3_0 (active)
  py27-sip @4.19.1_0 (active)
  py27-six @1.10.0_0 (active)
  py27-snowballstemmer @1.2.0_0 (active)
  py27-sphinx @1.5.3_0 (active)
  py27-spyder-devel @3.1.3_0 (active)
  py27-sympy @1.0_0 (active)
  py27-tables @3.2.3.1_1 (active)
  py27-tornado @4.4.2_0 (active)
  py27-traitlets @4.3.2_0 (active)
  py27-tz @2016.10_0 (active)
  py27-wcwidth @0.1.7_0 (active)
  py27-wrapt @1.10.8_0 (active)
  py27-zmq @16.0.2_0 (active)
  pyflakes_select @0.1_0 (active)
  pylint_select @0.1_1 (active)
  python2_select @0.0_2 (active)
  python27 @2.7.13_0 (active)
  python_select @0.3_7 (active)`

And the error messages in the terminal:

`[laptop:~] user% spyder
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
2017-03-15 11:56:52.009 Python[28464:1833682] *** Assertion failure in -[NSRemoteView informAuxServiceOfSelf], /Library/Caches/com.apple.xbs/Sources/ViewBridge/ViewBridge-280/NSRemoteView.m:3209
2017-03-15 11:56:52.046 Python[28464:1833682] IMKInputSession presentFunctionRowItemTextInputViewWithEndpoint:completionHandler: : *NO* NSRemoteViewController to client, NSError=Error Domain=com.apple.ViewBridge Code=8 "(null)" UserInfo={com.apple.ViewBridge.error.hint=__38-[NSRemoteView _advanceToConfigPhase:]_block_invoke.2462 caught NSInternalInconsistencyException '<NSRemoteView: 0x7fb724785000> failed to rendezvous via aux service' with backtrace (
	0   CoreFoundation                      0x00007fffb3f0de7b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffc8af7cad objc_exception_throw + 48
	2   CoreFoundation                      0x00007fffb3f12b82 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fffb595cd50 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 195
	4   ViewBridge                          0x00007fffc757197d -[NSRemoteView informAuxServiceOfSelf] + 345
	5   ViewBridge                          0x00007fffc7572302 -[NSRemoteView _finishAdvanceToConfigPhaseWithContextID:andServiceViewSize:andOffset:] + 699
	6   ViewBridge                          0x00007fffc75867e6 __38-[NSRemoteView _advanceToConfigPhase:]_block_invoke.2462 + 103
	7   CoreFoundation                      0x00007fffb3e813ec __invoking___ + 140
	8   CoreFoundation                      0x00007fffb3e81271 -[NSInvocation invoke] + 289
	9   ViewBridge                          0x00007fffc75ae52b withHintInProgress + 487
	10  ViewBridge                          0x00007fffc75ae25a __deferNSXPCInvocationOntoMainThread_block_invoke_2 + 233
	11  ViewBridge                          0x00007fffc752fdf2 +[NSViewServiceApplication withHostPID:invoke:] + 46
	12  ViewBridge                          0x00007fffc75ae11d __deferNSXPCInvocationOntoMainThread_block_invoke + 179
	13  ViewBridge                          0x00007fffc75add0a __deferBlockOntoMainThread_block_invoke_2 + 544
	14  CoreFoundation                      0x00007fffb3ea37dc __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	15  CoreFoundation                      0x00007fffb3e847e4 __CFRunLoopDoBlocks + 356
	16  CoreFoundation                      0x00007fffb3e84326 __CFRunLoopRun + 1878
	17  CoreFoundation                      0x00007fffb3e83974 CFRunLoopRunSpecific + 420
	18  HIToolbox                           0x00007fffb364b61e -[IMKInputSessionXPCInvocation invocationAwaitXPCReply] + 606
	19  HIToolbox                           0x00007fffb364dbd0 -[IMKInputSession activate] + 3471
	20  HIToolbox                           0x00007fffb3601c4b IMKInputSessionActivate + 36
	21  HIToolbox                           0x00007fffb3600fdc ActivateInputMethodInstance + 100
	22  HIToolbox                           0x00007fffb35f5a0a utOpenActivateSelectedInputMethodInDoc + 369
	23  HIToolbox                           0x00007fffb35f5874 utOpenActivateAllSelectedIMInDocIterator + 21
	24  CoreFoundation                      0x00007fffb3e46674 CFArrayApplyFunction + 68
	25  HIToolbox                           0x00007fffb342acc8 utOpenActivateAllSelectedIMInDoc + 187
	26  HIToolbox                           0x00007fffb342382c MyActivateTSMDocument + 1910
	27  AppKit                              0x00007fffb1af93f1 -[NSTextInputContext activate] + 284
	28  AppKit                              0x00007fffb23850fe +[NSTextInputContext currentInputContext_withFirstResponderSync:] + 362
	29  AppKit                              0x00007fffb19b79a2 -[NSApplication updateWindows] + 96
	30  AppKit                              0x00007fffb1def777 __38-[NSApplication setWindowsNeedUpdate:]_block_invoke.2372 + 68
	31  CoreFoundation                      0x00007fffb3ea3397 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	32  CoreFoundation                      0x00007fffb3ea3307 __CFRunLoopDoObservers + 391
	33  CoreFoundation                      0x00007fffb3e83f39 __CFRunLoopRun + 873
	34  CoreFoundation                      0x00007fffb3e83974 CFRunLoopRunSpecific + 420
	35  HIToolbox                           0x00007fffb340fa5c RunCurrentEventLoopInMode + 240
	36  HIToolbox                           0x00007fffb340f799 ReceiveNextEventCommon + 184
	37  HIToolbox                           0x00007fffb340f6c6 _BlockUntilNextEventMatchingListInModeWithFilter + 71
	38  AppKit                              0x00007fffb19b55b4 _DPSNextEvent + 1120
	39  AppKit                              0x00007fffb212fd6b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2789
	40  AppKit                              0x00007fffb19a9f35 -[NSApplication run] + 926
	41  libqcocoa.dylib                     0x0000000118b5cf35 qt_plugin_instance + 111093
	42  QtCore                              0x000000010d09dff1 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 417
	43  QtCore                              0x000000010d0a2387 _ZN16QCoreApplication4execEv + 343
	44  QtWidgets.so                        0x00000001104ea580 _ZL23meth_QApplication_exec_P7_objectS0_ + 80
	45  Python                              0x0000000108781f91 PyEval_EvalFrameEx + 29441
	46  Python                              0x000000010877a947 PyEval_EvalCodeEx + 2119
	47  Python                              0x0000000108786d46 fast_function + 118
	48  Python                              0x0000000108781e87 PyEval_EvalFrameEx + 29175
	49  Python                              0x000000010877a947 PyEval_EvalCodeEx + 2119
	50  Python                              0x0000000108786d46 fast_function + 118
	51  Python                              0x0000000108781e87 PyEval_EvalFrameEx + 29175
	52  Python                              0x0000000108786e22 fast_function + 338
	53  Python                              0x0000000108781e87 PyEval_EvalFrameEx + 29175
	54  Python                              0x000000010877a947 PyEval_EvalCodeEx + 2119
	55  Python                              0x000000010877a0f6 PyEval_EvalCode + 54
	56  Python                              0x00000001087a9824 PyRun_FileExFlags + 164
	57  Python                              0x00000001087a935e PyRun_SimpleFileExFlags + 702
	58  Python                              0x00000001087bfb1d Py_Main + 2925
	59  libdyld.dylib                       0x00007fffc93db255 start + 1
), com.apple.ViewBridge.error.description=NSViewBridgeExceptionError}, com.apple.inputmethod.EmojiFunctionRowItem
Segmentation fault`   

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: Python 2.7.13 (default, Dec 18 2016, 05:36:03) 
* Qt Version: '  qt4-mac @4.8.7_4 (active)
  qt5 @5.6.2_0 (active)
  qt5-qt3d @5.6.2_1 (active)
  qt5-qtbase @5.6.2_4+openssl (active)
  qt5-qtcanvas3d @5.6.2_1 (active)
  qt5-qtconnectivity @5.6.2_1 (active)
  qt5-qtdeclarative @5.6.2_1 (active)
  qt5-qtenginio @5.6.2_1 (active)
  qt5-qtgraphicaleffects @5.6.2_1 (active)
  qt5-qtimageformats @5.6.2_3 (active)
  qt5-qtlocation @5.6.2_1 (active)
  qt5-qtmacextras @5.6.2_1 (active)
  qt5-qtmultimedia @5.6.2_1 (active)
  qt5-qtquickcontrols @5.6.2_1 (active)
  qt5-qtscript @5.6.2_1 (active)
  qt5-qtsensors @5.6.2_1 (active)
  qt5-qtserialport @5.6.2_1 (active)
  qt5-qtsvg @5.6.2_1 (active)
  qt5-qttools @5.6.2_2 (active)
  qt5-qttranslations @5.6.2_1 (active)
  qt5-qtwebchannel @5.6.2_1 (active)
  qt5-qtwebengine @5.6.2_1 (active)
  qt5-qtwebsockets @5.6.2_1 (active)
  qt5-qtxmlpatterns @5.6.2_1 (active)
  qt5-sqlite-plugin @5.6.2_1 (active)'

* Operating system: MacOS 10.12.3

## Dependencies

'jedi =0.9.0      :  0.10.0 (NOK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.1.3 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
'

**Comment by ccordoba12** [comment]
It looks like an error in Qt. Sorry for not being more helpful but I don't see anything related to Spyder in the crash report.

You could install the PyQt5 wheels (with `pip install pyqt5`) to see if that helps. Of course, you'd need to remove all macports packages related to Qt5 before doing that.

**Comment by ccordoba12** [comment]
Closing because there's nothing else we can do to help you, sorry.
