### ISSUE TITLE
Spyder freezes while debugging due to wrong internal use of working directory

### ISSUE THREAD

**Issue by mgarbade** [spyder-ide/spyder#4262]
## Description of your problem

**What steps will reproduce the problem?**

1. Start two instances of spyder in parallel with different working directories (not sure if that lead to the error) `spyder --new-instance`
2. Close or crash one of the instances (not sure if related to the error)
3. Now even after restarting the computer and/or spyder I cannot debug my program anymore because spyder keeps immediately (at the first line already). I can however debug programs that are stored in an old working directory (formerly used by the second instance of spyder) --> which is a hint that spyder internally uses the wrong working directory, different from the one that I set under `Browse a working directory`. 
This error is haunting me now for more than an hour :-/

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.7
* Python Version: 2.7
* Qt Version: 4.8.6
* PyQt Version: 4.10.4
* Operating system: Ubuntu 14.04.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by mgarbade** [comment]
Sorry for the late reply.
The actual solution was to delete all config files in the /home/myUser/ directory.
Those were   

    `/home/myUser/.spyder2`

and

    `/home/myUser/.config/spyder` (as far as I remember)
