### ISSUE TITLE
Python 3: Spyder crashes when try to open a Pandas dataframe contained in a list or in a dict

### ISSUE THREAD

**Issue by bparenti** [spyder-ide/spyder#4269]
Hi, I have a problem when I try to open a Pandas dataframe contained in a list or in a dict, Spyder crashes and on terminal I have the follow messages:

**QWidget::repaint: Recursive repaint detected
QPaintDevice: Cannot destroy paint device that is being painted
[1]+  Segmentation Fault Error (core dump created) spyder**

System characteristics:

Python 3.6
Spyder 3.1.2
Anaconda 4.3.0
OS: Ubuntu 16.04 LTS (on Virtual Machine)

The problem doesn't appear with Python 2.7.

Thanks for your support

**Comment by jitseniesen** [comment]
Thanks for the report. Can you please give us step-by-step instructions on how to reproduce the crash? I tried (admittedly not very hard) and I did not get Spyder to crash.

**Comment by bparenti** [comment]
Thanks for your answer!!
An example of code that reproduces the error is the following:

```
import pandas as pd
import numpy as np

list = []

df = pd.DataFrame(np.random.randn(1000, 10), columns=['aaaaaa', 'bbbbbbbb', 'ccccccccc', 'ddddddd', 'eeeeeeeee', 'ffffffffff', 'gggggggggg',\
                                  'hhhhhhhhhhh', 'iiiiiiiiiiiiii', 'jjjjjjjjjjjjjjjjjjjjjjjjjjjjj'])

list.append(df)
```

Before I forgot to specify that I get the error when I try to open the dataframe contained in the list using the Variable Explorer.

Thanks again!

**Comment by jitseniesen** [comment]
I can reproduce the issue on Spyder version 3.1.2 but not on version 3.1.3. Can you please try updating Spyder to version 3.1.3 with the command `conda update spyder`?

**Comment by jitseniesen** [comment]
It looks like PR #4142 (which went into Spyder 3.1.3) merely hid the problem. In the situation described by bparenti the format is set to `None` in [collectionseditor.py:489](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/variableexplorer/collectionseditor.py#L489), which should not happen.

**Comment by bparenti** [comment]
Thanks a lot, I update Spyder to version 3.1.3 and now the problem doesn't appear
