### ISSUE TITLE
DataframeEditor opened with format equal to None

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#4270]
Issue #4269 revealed an underlying problem:  the format of the `DataframeEditor` can be set to `None` in [collectionseditor.py:489](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/variableexplorer/collectionseditor.py#L489). This happens in the following situation:

Give the following commands in the IPython console:

```python
import pandas as pd
import numpy as np

list = []

df = pd.DataFrame(np.random.randn(1000, 10), columns=['aaaaaa', 'bbbbbbbb', 'ccccccccc', 'ddddddd', 'eeeeeeeee', 'ffffffffff', 'gggggggggg',\
                                  'hhhhhhhhhhh', 'iiiiiiiiiiiiii', 'jjjjjjjjjjjjjjjjjjjjjjjjjjjjj'])

list.append(df)
```

Open the variable explorer, click to open the editor for `list` and then click to open a DataframeEditor for `list[0]`.

This issue occurs both in version 3.1.3 and on `master`. It probably does not affect many users because invalid formats are caught after #4142.

**Comment by goanpeca** [comment]
@jitseniesen could you elaborate on this issue, I am not sure I follow what the problem is 🙃

**Comment by goanpeca** [comment]
@jitseniesen 🙃?

**Comment by goanpeca** [comment]
Is this still valid ?

**Comment by jitseniesen** [comment]
Ummm ... I don't remember what the issue was and I don't understand the description I wrote five years ago, so I am closing this.
