### ISSUE TITLE
Variables from scripts not defined in python console and variable explorer

### ISSUE THREAD

**Issue by mauraBrunetti** [spyder-ide/spyder#4274]
## Description of your problem

**What steps will reproduce the problem?**

1. define a script with a variable assignment, nw = 1
2. Execute in current Python console
3. Run the script (with runfile command or F5)

**What is the expected output? What do you see instead?**
The "nw" variable along with the assigned value (1) should appear in the variable explorer. 
If I type 'nw' in the console, I get the following error: 
NameError: name 'nw' is not defined

If I write directly on the console, everything is fine. 

**Please provide any additional information below**
I installed Anaconda navigator 1.4.3 two weeks ago
 
## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Darwin (Mac OS 10.8.5)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
The Python console is going to be removed in Spyder 3.2, so we're not going to fix more bugs about it.

Please use the IPython console instead.
