### ISSUE TITLE
Add option to compare two files (enhancement)

### ISSUE THREAD

**Issue by crazyBaboon** [spyder-ide/spyder#4276]
It would be useful to have an option on the Search menu 'Compare files'

**Comment by ccordoba12** [comment]
Sorry, although useful, we're not going to implement this because there are better tools for the job (e.g. `kdiff3`).

Probably in the future, if we gain git support.

**Comment by chuckf201** [comment]
pycharm has file-compare built-in.
I'd rather see it in spyder.

**Comment by Shuanhong** [comment]
Yeah,I hope this func also,haha

**Comment by costa1111** [comment]
I also hope this would be usefull

**Comment by KennyISHIMURA** [comment]
Comparison tools are essential for IDEs so that users do not have to open other windows.
