### ISSUE TITLE
Option to Disable Blinking Cursor

### ISSUE THREAD

**Issue by ankurkanoria** [spyder-ide/spyder#4277]
Spyder does not respect system keyboard settings, and there seems to be no way to disable the blinking cursor in the editor, integrated consoles, etc. All modern IDEs provide an option to disable cursor blinking; the flashing cursor is known to irritate a lot of developers. (www.jurta.org/en/prog/noblink).

How can one tweak the Spyder settings, configuration files to make this happen?

I'm using: Linux (Ubuntu 16.04), Anaconda 4.3. This issue was also noted by a few developer friends on Windows.

**Comment by ccordoba12** [comment]
> the flashing cursor is known to irritate a lot of developers

First time I've heard this complaint in seven years working in Spyder, so (I'm sorry to say it but) we're not going to implement this.

You're welcome to send us a pull request to implement this though.

**Comment by ankurkanoria** [comment]
@ccordoba12 , can you suggest me where to start if I want to implement this?

**Comment by gerardp** [comment]
@ccordoba12 
Can you reconsider your decision?
All IDE's has this option

Thanks

**Pycharm**
![captura de pantalla 2017-07-15 a las 9 40 17](https://user-images.githubusercontent.com/168353/28237567-ae180216-6942-11e7-9f2a-eaa486b6fa8c.png)

**Visual Studio Code**
![captura de pantalla 2017-07-15 a las 9 43 41](https://user-images.githubusercontent.com/168353/28237569-b7b2c69e-6942-11e7-9578-13841ee5af28.png)

**Sublime text**
`"caret_style": "solid"`

**XCode**
`defaults write -g NSTextInsertionPointBlinkPeriod -int 100000`

Etc.

**Comment by jnsebgosselin** [comment]
![caret_blinking](https://user-images.githubusercontent.com/10170372/28298172-cb3d08c4-6b3f-11e7-818d-b58f3c00cb59.png)

**Comment by jnsebgosselin** [comment]
Meanwhile, you can set this option with a quick hack by adding the line :
```
MAIN_APP.setCursorFlashTime(0)
```
after 

```
from spyder.utils.qthelpers import qapplication, MENU_SEPARATOR
MAIN_APP = qapplication()
```

in file `mainwindow.py` in the Spyder installation folder. For me (Win7 64bit), this file is located in:

C:\Python36\Lib\site-packages\spyder\app

**Comment by Mohassann** [comment]
Actually, this solved my problem! 
https://www.youtube.com/watch?v=J6O5RrN1jd8&t=9s
