### ISSUE TITLE
[Enhancement] Collapsing loops and definitions

### ISSUE THREAD

**Issue by Sbelletier** [spyder-ide/spyder#4278]
Most IDEs for other langages (ex: code blocks, eclipse....) allow to collapse loops and declaration to their first line. When working on a long file (for example a long class declaration), this becomes very convenient as it allows to quickly skim through code for the specific piece you're looking for without scrolling for a needlessly long time.

While this may not be a prioritary enhancement, i think it would contribute to making Spyder an IDE that's comfortable for a developer to use.

**Comment by rlaverde** [comment]
It's already implemented, and will be available in Spyder 4.0 (see #3833).

If you want to test it before the official release you could execute Spyder from the source code.

**Comment by Sbelletier** [comment]
ok thank you ! I'll close the issue.
