### ISSUE TITLE
Spyder 3 using Spyder 2 Icons

### ISSUE THREAD

**Issue by breedlun** [spyder-ide/spyder#4280]
## Description

**What steps will reproduce the problem?**

1. Create a python environment using enthought deployment manager (edm)
2. Install numpy, pyqt, scipy, and matplotlib using edm
3. Install qtawesome and Spyder using pip
4. Launch Spyder.

**What is the expected output? What do you see instead?**

Expected the new Spyder 3 icons.  I got an error message saying, "Spyder was unable to load the Spyder 3 icon theme.  That's why it's going to fallback to the theme used in Spyder 2.  For that, please close this window and start Spyder again."  Once I restarted Spyder 3 I get the Spyder 2 icons, as I was warned I would by the error message.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.13
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Darwin

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.2.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
I really don't understand what's happening but your setup is very specific so it's up to you to figure it out what's happening.

Besides, we don't support PyQt4 on macOS anymore because it hasn't been updated to work with newer versions since 10.10.

**Comment by C046** [comment]
> I really don't understand what's happening but your setup is very specific so it's up to you to figure it out what's happening.
> 
> Besides, we don't support PyQt4 on macOS anymore because it hasn't been updated to work with newer versions since 10.10.

If you work for or with the Spyder development team, you should be fuckin fired.
