### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by KimSoybean** [spyder-ide/spyder#4281]
## Description of your problem

**What steps will reproduce the problem?**

1. when I open it ，it tells me the crashed news,
2. I use cmd.exe and cin  'spyder --show-console'
3. It tells me ' Spyder is already running. If you want to open a new
instance, please pass to it the --new-instance option'

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:4.3.0.1
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system:win10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This problem was fixed in Spyder 3.1, so please update to our latest version (3.1.3 at the moment).

**Comment by KimSoybean** [comment]
I find a txt named SPYDER CRASH ，it tell me news:

Traceback (most recent call last):
  File "C:\Users\26983\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2989, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\26983\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2891, in run_spyder
    main = MainWindow(options)
  File "C:\Users\26983\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 494, in __init__
    socket.IPPROTO_TCP)
  File "C:\Users\26983\Anaconda2\lib\socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
error: [Errno 10106]
