### ISSUE TITLE
closing an ipython console window is slow

### ISSUE THREAD

**Issue by peendebak** [spyder-ide/spyder#4287]
## Description of your problem

**What steps will reproduce the problem?**

1. Open a new console window
2. Close the console window
3. Closing takes about 2-3 seconds

Closing should be much faster. Also opening the console window takes some time, but this is acceptable since opening actually has to do work.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: Python 3.5.2 64bits, Qt 5.5.1, PyQt5 5.5.1 on Linux 
* Operating system: Ubuntu 16.04

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.3 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
sympy >=0.7.3    :  0.7.6.1 (OK)

**Comment by ccordoba12** [comment]
I don't what's happening, most probably a Qt problem. Please try to update to Qt/PyQt 5.6 or newer and try again.

**Comment by peendebak** [comment]
@ccordoba12 The same issue is there in windows. With the qt4 backend the delay is less (but still long). I cannot try a recent version of pyqt since there are no conda packages available.

**Comment by ccordoba12** [comment]
I'm almost sure this is a Qt problem because if it were a Spyder one a lot off people would be complaining about it.

So I'm sorry, but since I think we can't fix it, I'm closing this issue.
