### ISSUE TITLE
Background color of selected statement changes with mouse right click.

### ISSUE THREAD

**Issue by sibojan9** [spyder-ide/spyder#4295]
This behave is very different compared with other commonly used software.
Spyder looks good that the background of selected statements becomes black. 
![snap118](https://cloud.githubusercontent.com/assets/11802171/24237072/31c42562-0f7b-11e7-9314-c8cab6c2a522.jpg)
However, when you continued to right click, the black background disappears, making it difficult to identify what you have selected.
![snap119](https://cloud.githubusercontent.com/assets/11802171/24237090/42ef7fc6-0f7b-11e7-881d-e1de836c7404.jpg)

I am using the lasted WinPython version. It should be Winpython-3.6 
* Spyder Version: 3.1.2
* Python Version: 3.5.3
* Qt Version: 5.7.1
* PyQt Version: 5.7.1
* Operating system: Windows 7

**Comment by ccordoba12** [comment]
What operating system are you using? And Qt version?

Please don't skip that info when filling a bug. It just makes me waste my time because I have to ask you about it again. It's there for a reason :-)

**Comment by sibojan** [comment]
Sorry for that. I do not know how to check the PyQt Version but I am using the latest Winpython distribution. (https://winpython.github.io/)

**Comment by ccordoba12** [comment]
Please go to

    Help > About Spyder

Qt versions are printed at the end.

**Comment by sibojan** [comment]
updated. Thanks.

**Comment by goanpeca** [comment]
I do not think this applies anymore. Closing
