### ISSUE TITLE
empty output and already defined variables for the IPython terminal

### ISSUE THREAD

**Issue by daviddoji** [spyder-ide/spyder#4296]
## Description of your problem
Once started Spyder, there are three variables already defined in the explorer (e, euler_gamma, using_mklfft).
Theses variables produce no output in the Ipython console. Actually, the output of the IPython console shows an empty output for those or any other variables.

**What steps will reproduce the problem?**

1. Open Spyder 3.1.3
2. Click on the IPython terminal
3. Go to the variables explorer 

**What is the expected output? What do you see instead?**
I expected the output of whatever I enter as "In". I can't see nothing instead

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version:
* Operating system: Ubuntu 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please run

    spyder --reset

in a terminal and try again

**Comment by daviddoji** [comment]
That made the trick ;) 
Thanks a lot and my most sincere congratulations for this excellent IDE!

**Comment by ccordoba12** [comment]
:+1: glad that trick solved your problem and thanks for your kind words :-)
