### ISSUE TITLE
'Execute in an external System terminal' not work

### ISSUE THREAD

**Issue by luis-fonseca** [spyder-ide/spyder#4297]
## Description

**What steps will reproduce the problem?**

1. Run >> Configure >> Execute in an external System terminal >> Run

**What is the expected output? What do you see instead?**
I hope the script runs in a terminal, but nothing happens

**Please provide any additional information below**
No LSB modules are available.
Distributor ID: LinuxMint
Description: Linux Mint 18 Sarah
Release: 18
Codename: sarah

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.8.0, PyQt5 5.8.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.2.0 (OK)
matplotlib >=1.0 :  None (NOK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by Sultaneous** [comment]
I am also seeing this behaviour under Fedora 26  in x-windows over ssh.  Instead of spawning a system terminal window, it defaults to the current console.
