### ISSUE TITLE
High memory and cpu temperature after opening spyder

### ISSUE THREAD

**Issue by potholiday** [spyder-ide/spyder#4299]
## Description of your problem

I have seen a high usage of memory and raise in CPU temperature after and while opening spyder. I find these result by comparing it with RStudio's memory and cpu temp output.

**What steps will reproduce the problem?**

Normal
```
Normal CPU temp=43-50 deg cel
Normal Memory=44 perc
```

RStudio

```
Starting time < 2 sec

CPU temp (on starting) = 50-->60 deg cel
CPU temp (after opening) = 45-52 deg cel
CPU temp (after loading 1 mb file)=45-52 deg cel


Memory (on starting)  = 50 per
Memory (after opening) = 50 per
Memory (after loading 1 mb file)=50-51 per

```
Spyder

```
Starting time > 2 sec (

CPU temp (on starting) = 50-->78 deg cel
CPU temp (after opening) = 47-55 deg cel
CPU temp (after loading 1 mb file)=47-55 deg cel


Memory (on starting)  = 57 per
Memory (after opening) = 63 per
Memory (after loading 1 mb file)=64 per
```

## Versions and main components

* Spyder Version:3.1.3
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system: ubuntu 14

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I don't know if you have a memory constrained system, but Spyder doesn't work well on those.

Also, I'm sorry to say it, but we don't have plans to address this because it's not Spyder's fault really, but of the libraries it uses to do code completion in the Editor, and also the IPython kernels it opens to run code.

**Comment by potholiday** [comment]
Yeah I have a pretty small 3GB memory system; so for me every 1 percentage of memory is precious. I really liked spyder its very fast and a complete (for me) ide but high usage of memory is a real concern. I also believe the rise in CPU temperature is also caused by these libraries?

As your reply answers my question I am closing my question and thank you for the quick reply.

Cheers

**Comment by ccordoba12** [comment]
You could try to run Spyder 2.3.9 with PyQt4. That version should consume less resources than the last one. However, you'll miss almost three years of improvements...

> I also believe the rise in CPU temperature is also caused by these libraries?

Probably, but I really don't know.
