### ISSUE TITLE
EOLs incorrectly switch from LF to CRLF on split editor panes

### ISSUE THREAD

**Issue by mwtoews** [spyder-ide/spyder#4304]
I'm using Spyder 3.1.3 on Windows x64 via Anaconda 2.7 to edit some Python source files that use Linux EOLs (LF). The Editor pane that I use is split vertically.

When I open one of these files and set the focus the first split view, the file status at the bottom correctly displays "End-of-lines: LF". However, if I restart Spyder and set the focus to the second split view of the same file, the status incorrectly changes to "CRLF". If I save from the upper view, it is saved LF, and if I save from the lower view, it is saved CRLF.

Here are the best steps I can reproduce the probelem
1. From a native Windows version of Spyder, make sure the Editor pane is split vertically, and open a LF file.
2. Close Spyder. And start it up again to see the same set of file(s) in the Editor panes.

Observe that the upper pane shows and saves the file as LF, and the lower pane shows and saves the same file as CRLF.

## Versions and main components
* Spyder Version: 3.1.3
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Windows

## Dependencies
```pyflakes >=0.5.0 :  1.5.0 (OK)pep8 >=0.6       :  1.7.0 (OK)pygments >=2.0   :  2.2.0 (OK)qtconsole >=4.2.0:  4.2.1 (OK)nbconvert >=4.0  :  5.1.1 (OK)pandas >=0.13.1  :  0.19.2 (OK)numpy >=1.7      :  1.11.3 (OK)sphinx >=0.6.6   :  1.5.2 (OK)rope >=0.9.4     :  0.9.4 (OK)jedi =0.9.0      :  0.9.0 (OK)matplotlib >=1.0 :  2.0.0 (OK)sympy >=0.7.3    :  1.0 (OK)pylint >=0.25    :  1.6.4 (OK)```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it to see what's happening.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
