### ISSUE TITLE
Auto-complete does not work

### ISSUE THREAD

**Issue by haytham** [spyder-ide/spyder#4305]
## Description

**What steps will reproduce the problem?**

1. Use Spyder for some time - so far I can only say it certainly manifests itself when I put my laptop to sleep then turn it back on.

**What is the expected output? What do you see instead?**
I expect to see autocomplete show options when I use either a built in package or something like Pandas.  autocomplete stops working as described above.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by pkgprateek** [comment]
Which operating system are you using?

**Comment by ccordoba12** [comment]
Please see issue #2162. Unfortunately, code completion doesn't work in some cases.

**Comment by DidemnumVex** [comment]
This was working in previous versions of spyder and has stopped working since I updated it recently.  I've seen no other improved functionality and may go back to the previous version.
