### ISSUE TITLE
Third-party plugins should store their options in different files from spyder.ini

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#4306]
The files should be loaded by Spyder during start up.

**Comment by ccordoba12** [comment]
@goanpeca, @jitseniesen, what do you think about this one?

**Comment by jitseniesen** [comment]
I need more info to form an opinion. What is the rationale for this? I guess this is part of a wider overhaul of how plugins handle their configuration.

**Comment by goanpeca** [comment]
Yeah I need more info :-|

**Comment by goanpeca** [comment]
Advantages/Disadvantages @andfoy ?

**Comment by ccordoba12** [comment]
I asked @andfoy to open this issue. The idea is that each plugin has its own config file (e.g. `notebook.ini`, etc.) and that Spyder loads those files and integrates them to Preferences at startup.

This way each plugin would handle its config separately from the rest and could update/change/remove config options without problems.

**Comment by goanpeca** [comment]
Ok sure, but I think that is ok, but then we need to adapt the code a bit

**Comment by ccordoba12** [comment]
Yep, that's the idea for 3.2.

**Comment by goanpeca** [comment]
@could we take this opportunity to add tests to the config module for spyder :-p ?

**Comment by ccordoba12** [comment]
There are some tests already (added by @jitseniesen I think). But sure, we can always increase our coverage ;-)

**Comment by jitseniesen** [comment]
Sounds good to me. Since at present it is not clear how plugins should handle their configuration it's an improvement.

**Comment by ccordoba12** [comment]
Ok, I'll start thinking about a plan so that @andfoy can implement it.

**Comment by leportella** [comment]
@ccordoba12 just some thoughts that me and @jonatasbaldin were discussing on this:

* We thought that for each plugin, the spyder.ini file would add a new session for plugin configuration
* What would happen if 2 plugins change the same config?

Also, if you could provide me with some kind of config that spyder-notebook would be able to change for me to test it, that would be great!

**Comment by goanpeca** [comment]
Split config per plugins has already been implemented in Spyder 4.x
