### ISSUE TITLE
Additional shortcuts are making the outline explorer to appear

### ISSUE THREAD

**Issue by piotrkuzmiak** [spyder-ide/spyder#4307]
## Description of your problem

Pressing Right ALT+o opens Outline pane, though diffrent shortkeys are defined by deafult for this.

**What steps will reproduce the problem?**

1. ALT+o
2. ALT+s
3. 

**What is the expected output? What do you see instead?**

Polish "ó" char is expected while new pane opens.

**Please provide any additional information below**

Solution at the moment is to change default shortcut :)

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: (major=3, minor=5, micro=2, releaselevel='final', serial=0)
* Qt Version: 4.8.7
* PyQt Version: 4.11.4
* Operating system: Windows 7 Enterprise

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by main123** [comment]
could someone look at this bug? we are not able to use Polish language fully ;)

**Comment by ccordoba12** [comment]
Ok, we're going to address this in Spyder 3.2 (to be released in two or three weeks).

**Comment by main123** [comment]
great!
one thing more: as in first post, ALT+s is not a shortcut and still we are not able to use it to enter polish letter "ś";
I'm not sure if anyone looked at this too;

**Comment by Lifandi** [comment]
The problem is still on with 'ś' alt + s

**Comment by michal01473** [comment]
We still can't use ALT+s (ś) in Spyder.

**Comment by podkop** [comment]
Temporary solution for enabling ALT+s (Polish ś): in Preferences / Keyboard shortcuts, clear or change shortcuts for "Save all" in both "editor" and "plots" contexts. By default, "Ctrl+Alt+s" is assigned to both these actions. For some reason, "Right Alt + s" is overrided by "Ctrl+Alt+s".
