### ISSUE TITLE
problems running spyder in Ubuntu 16.04 Python 2.7.x

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4310]
## Description of your problem
I am not able to run spyder.  I have two versions of Python: one through pip and another through anaconda.  This problem I am having in the version through the pip command.  Updating spyder to 3.1.3 gave me the following errors.  Please help

>  File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 2989, in main
>     mainwindow = run_spyder(app, options, args)
>   File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 2893, in run_spyder
>     main.setup()
>   File "/usr/local/lib/python2.7/dist-packages/spyder/app/mainwindow.py", line 872, in setup
>     from spyder.plugins.ipythonconsole import IPythonConsole
>   File "/usr/local/lib/python2.7/dist-packages/spyder/plugins/ipythonconsole.py", line 60, in <module>
>     from spyder.widgets.ipythonconsole import ClientWidget
>   File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/ipythonconsole/__init__.py", line 12, in <module>
>     from .debugging import DebuggingWidget
>   File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/ipythonconsole/debugging.py", line 16, in <module>
>     from qtconsole.rich_jupyter_widget import RichJupyterWidget
>   File "/usr/local/lib/python2.7/dist-packages/qtconsole/rich_jupyter_widget.py", line 14, in <module>
>     from .jupyter_widget import JupyterWidget
>   File "/usr/local/lib/python2.7/dist-packages/qtconsole/jupyter_widget.py", line 19, in <module>
>     from IPython.lib.lexers import IPythonLexer, IPython3Lexer
> ImportError: No module named  lexers

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I think you need to update IPython too to sole this problem.

**Comment by s0r2637** [comment]
Hi Carlos,

I am going nuts with maintaining two sets of Python: one through pip and
another through Anaconda.  Per your suggestion a few weeks back I moved to
Anaconda because a 3d visualization software Mayavi was not working through
pip, probably due to inconsistent dependencies.  However, although Anaconda
solved the Mayavi problem, but I encountered a different problem with boost
bindings.

I installed openni package, and I now I am facing Boost Python argument
error.  Is there anything you can do to resolve this issue with Anaconda.
Anaconda is a little slow to reply compared to you.

Btw, I just did pip install --upgrade ipython[all].  And I still stuck with
the same Spyder error


Srini

**Comment by ccordoba12** [comment]
I don't know about openni, sorry.

`IPython.lib.lexers` is certainly there in IPython 5:

https://github.com/ipython/ipython/blob/5.x/IPython/lib/lexers.py

so I don't know what's happening :-/

**Comment by ccordoba12** [comment]
Sorry, but there's nothing we can do about this because it's not a Spyder bug.

So I'm closing this one.
