### ISSUE TITLE
"unblockcomment" incompatible with "automatically remove trailing spaces"

### ISSUE THREAD

**Issue by llan-ml** [spyder-ide/spyder#4313]
## Description of your problem

**What steps will reproduce the problem?**
For example, there are codes:
"""
import numpy as np

def test():
    return 1

test()
"""
1. Enable the feature "Automatically remove trailing spaces when saving files"
2. blockcomment (ctl+4) the piece of codes above
2. save the file (ctl+s)
3. unblockcomment (ctl+5)

**What is the expected output? What do you see instead?**
The expected output is
"""
import numpy as np

def test():
    return 1

test()
"""
However, we see
“”“
import numpy as np
\# def test():
    return 1
\# test()
”“”
**Please provide any additional information below**
It seems like the enabled feature (removing trailing spaces) removes the newline character when saving the file.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7.12
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.
