### ISSUE TITLE
IPython suspend because ctrl-c in long time iteration

### ISSUE THREAD

**Issue by solo7773** [spyder-ide/spyder#4315]
Spyder 2.3.9
Python 3.5.2.64

The spyder comes with anaoconda3. During the running of a for iteration, I pressed ctrl+c, then the IPython console suspended. This is really annoying. Is it solved in the newer version?

**Comment by ccordoba12** [comment]
That's the normal behavior in the IPython console, so it doesn't need to be fixed.

If you want to copy something from the console while it's running a computation, you need to select it first and then do a mouse right click and select the *Copy* option.
