### ISSUE TITLE
error build  under Fedora 25

### ISSUE THREAD

**Issue by catafest** [spyder-ide/spyder#4318]
## Description of your problem

try to build the last version of Spyder IDE with Fedora 25
this issues is also post into Fedora development 

**What steps will reproduce the problem?**

1.  I got Spyder IDE (the zip  file - I try also with git command) 
2.  I run the commands:
python setup.py build
python setup.py build_doc
python setup.py install 
3.  I try to start the IDE  with command:  spyder

**What is the expected output? What do you see instead?**
[root@localhost spyder-master]# spyder
Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in <module>
    start.main()
  File "/usr/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/lib/python2.7/site-packages/spyder/requirements.py", line 53, in check_qt
    % (qt_infos['pyqt5'] + qt_infos['pyqt']))
  File "/usr/lib/python2.7/site-packages/spyder/requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Failed to import qtpy.
Please check Spyder installation requirements:

qtpy 1.1.0+ and either
PyQt5 5.2+ or
PyQt4 4.6+

**Please provide any additional information below**
Fedora 25 come with a old version of Spyder 2.3.9 

## Versions and main components

* Spyder Version:  

* Python Version: # python
Python 2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.

* Qt Version: # rpm -qa | grep qt

qt5-qtwebchannel-5.7.1-2.fc25.x86_64
qtsoap-2.7-13.fc24.x86_64
qt5-qtsvg-5.7.1-2.fc25.x86_64
phonon-qt5-4.9.0-3.fc25.x86_64
python3-qt5-5.7-4.fc25.x86_64
qt-x11-4.8.7-18.fc25.x86_64
polkit-qt5-1-0.112.0-8.fc25.x86_64
qt-mobility-location-1.2.2-0.23.20140317git169da60c.fc24.x86_64
qt5-qtdeclarative-5.7.1-5.fc25.x86_64
qtile-0.10.6-2.fc25.noarch
poppler-qt5-0.45.0-2.fc25.x86_64
qt5-qttools-libs-help-5.7.1-4.fc25.x86_64
qt5-qtlocation-5.7.1-2.fc25.x86_64
python-qt5-rpm-macros-5.7-4.fc25.noarch
qt-4.8.7-18.fc25.x86_64
qtwebkit-2.3.4-11.fc24.x86_64
qt5-qtbase-common-5.7.1-14.fc25.noarch
qt5-qtserialport-5.7.1-2.fc25.x86_64
qt5-qtquickcontrols-5.7.1-2.fc25.x86_64
qt5-qtx11extras-5.7.1-2.fc25.x86_64
qt5-srpm-macros-5.7.1-1.fc25.noarch
qt5-qttools-libs-designer-5.7.1-4.fc25.x86_64
qt-settings-25-2.fc25.noarch
qt5-qtconnectivity-5.7.1-2.fc25.x86_64
qt5-qtwebkit-5.7.1-2.fc25.x86_64
dbusmenu-qt-0.9.3-0.11.20150604.fc24.x86_64
qt5-qttools-common-5.7.1-4.fc25.noarch
qt5-qtbase-gui-5.7.1-14.fc25.x86_64
sni-qt-0.2.6-7.fc24.x86_64
qt5-qttools-libs-clucene-5.7.1-4.fc25.x86_64
qt5-qtmultimedia-5.7.1-2.fc25.x86_64
qt-common-4.8.7-18.fc25.noarch
qt-mobility-common-1.2.2-0.23.20140317git169da60c.fc24.x86_64
qt5-qtscript-5.7.1-2.fc25.x86_64
qt-mobility-sensors-1.2.2-0.23.20140317git169da60c.fc24.x86_64
qt5-qtxmlpatterns-5.7.1-4.fc25.x86_64
phonon-qt5-backend-gstreamer-4.9.0-1.fc25.x86_64
qt5-qtbase-5.7.1-14.fc25.x86_64
qt5-qtenginio-1.6.2-2.fc25.x86_64
qt5-qtsensors-5.7.1-3.fc25.x86_64
dbusmenu-qt5-0.9.3-0.11.20150604.fc24.x86_64
qt5-qtwebsockets-5.7.1-2.fc25.x86_64
qtscriptbindings-0.2.0-11.fc24.x86_64
 
* PyQt Version: # rpm -qa | grep pyqt
the result is none 

* Operating system:
4.10.8-200.fc25.x86_64 #1 SMP Fri Mar 31 13:20:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by besser82** [comment]
You simply need python2-qtpy and python-qt5 installed…

**Comment by ccordoba12** [comment]
You need to install all Spyder dependencies by hand if you want to install it with

    python setup.py install

They are listed in our Readme.

That's why we recommend to use

    pip install -U spyder

instead because it pulls all our dependencies (except PyQt because Spyder can work with PyQt4 and PyQt5).

**Comment by catafest** [comment]
using Fedora , I install 

`# dnf install python2-QtPy.noarch`

the next error I got is 

`[mythcat@localhost spyder-master]$ spyder 
Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in <module>
    start.main()
  File "/usr/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/usr/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: No module named QtWebKitWidgets`

according to this [issue](http://stackoverflow.com/questions/37876987/cannot-import-qtwebkitwidgets-in-pyqt5) , 

QtWebKit got deprecated upstream in Qt 5.5 and removed in 5.6.

You may want to switch to PyQt5.QtWebEngineWidgets :

**Comment by jitseniesen** [comment]
Did you try installing PyQt5.QtWebEngineWidgets? @besser82 told you to use python-qt5; did you install that? PyQt5.QtWebEngineWidgets should be used if it is available.
