### ISSUE TITLE
The cmd+i isn't working to inspect a function, autocomplete isn't working at all

### ISSUE THREAD

**Issue by jwcunhagit** [spyder-ide/spyder#4320]
## Description

**What steps will reproduce the problem?**

1. select any function and type cmd+i
2. nothing happen
3. type dot after any function nothing happen

**What is the expected output? What do you see instead?**
1st case the help should be opened
2nd case the autocomplete panel should be shown

**Please provide any additional information below**
nothing, so simple like this

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.2.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
Things are working as expected in our tests, so I don't know what's happening in your case, sorry.

**Comment by ccordoba12** [comment]
Closing because I don't know what's happening for you, sorry.
