### ISSUE TITLE
cannot use matplotlib in spyder 3.13 (but code works elsewhere)

### ISSUE THREAD

**Issue by tammie13** [spyder-ide/spyder#4322]
## Description

**What steps will reproduce the problem?**

```
from matplotlib.colors import ListedColormap
X_set, y_set = X_train, y_train
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('red', 'green'))(i), label = j)
plt.title('SVM (Training set)')
plt.xlabel('Age')
plt.ylabel('Estimated Salary')
plt.legend()
plt.show()
```

1. "Kernel died, restarting"
2. 
3. 

**What is the expected output? What do you see instead?**
code works spyder2.3.9(python 2.7)
code works in Jupyter for python 3.5 or python 2.7
Delete and reinstalling matplotlib, or mkl doesn't matter
 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
jedi =0.9.0      :  0.10.0 (NOK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by ccordoba12** [comment]
This code is not complete (e.g. where does `classifier` comes from? What are the values of `X_train, y_train`?)

Without a complete code example we can't reproduce your error.

**Comment by tammie13** [comment]
it's not just this code.  A variety of graphing doesnt work.  This started with Spyder3.13 (didn't have this problem with earlier version.  The problem occured after updating Spyder.  The code is from a Udemy course- it's not an error in the code.  I can send more code that likewise delivers a kernel crash with matplotlib.
[kernel_svm.txt](https://github.com/spyder-ide/spyder/files/891117/kernel_svm.txt)
[Social_Network_Ads.xlsx](https://github.com/spyder-ide/spyder/files/891101/Social_Network_Ads.xlsx)

**Comment by ccordoba12** [comment]
Nobody else has reported this problem. And again, the code is not complete.

**Comment by tammie13** [comment]
![mkl_blas](https://cloud.githubusercontent.com/assets/8825685/24627341/c7e81df6-1871-11e7-8463-da167c4b73e3.PNG)

what is the correction?

**Comment by tammie13** [comment]
what is the correction when the dll is LOCATED where it claims it is not located?

**Comment by tammie13** [comment]
the code (that I sent you and is complete) runs fine on
Spyder (2.7)
Jupyter (2.7, 3.5)
 Sublime Text,  PyCharm, Visual Studio, Wings
In other words, the problem is with the recent update.

**Comment by ccordoba12** [comment]
Yes, but not with Spyder but Numpy. I'm sorry but I don't know what could be causing it.

**Comment by heihaa** [comment]
I have the same issue! Code is fine, hand have worked earlier. But now, when i try to plot, I get the same error message as you. And I have uninstalled Anaconda and reinstalled, issue still the same. Did you find a fix for this issue?

**Comment by heihaa** [comment]
see in this therad: https://github.com/ContinuumIO/anaconda-issues/issues/8561

I unistalled Amplitube and the everything was fine

**Comment by jnsebgosselin** [comment]
Thanks @heihaa for investigating this issue and reporting back your solution, this is much appreciated!
