### ISSUE TITLE
Disappearing variables in variable explorer for list containing first element 'None'

### ISSUE THREAD

**Issue by xcmarvin** [spyder-ide/spyder#4325]
## Description of your problem

When the first element of a given list contains 'None' or 'nan', the list variable disappears from the variable explorer.

**What steps will reproduce the problem?**

1. Create an empty list
2. Append 'None' to the empty list as the first element

**What is the expected output? What do you see instead?**

Initially when an empty list is declared, the list variable can still be seen in the variable explorer. However, once the first element containing 'None' is added to the empty list, the list variable disappears from the variable explorer.

## Versions and main components

Spyder Version: 3.1.2
Python Version: 2.7.13
Operating system: Mac OS 10.12.3

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.2
