### ISSUE TITLE
A file cannot be loaded if path contains a directory name with spaces

### ISSUE THREAD

**Issue by Mathemilda** [spyder-ide/spyder#4327]
## Description of your problem
I run Spyder3 on Ubuntu 16.04. I cannot load a file from a directory if there are spaces in a path to the directory.
**What steps will reproduce the problem?**

1. I changed my working directory on Spyder to the one containing my file, 'data.csv'
2. Imported "pandas" package
3. Typed 
dataset = pd.read_csv('Data.csv') 
and pressed to run my selection.

**What is the expected output? What do you see instead?**

I was supposed to see nothing, but instead I got the following error message:
Data <- read_csv("~/Downloads/data_science/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data.csv")
Error: '~/Downloads/data_science/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/Data.csv' does not exist.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3
* Python Version: 3.5
* Qt Version: 4.8.7
* PyQt Version:  4.11.4
* Operating system: Linux, Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0      :  2.4.1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  3.4.2 (OK)
pyflakes >=0.6.0   :  1.1.0 (OK)
pygments >=1.6     :  2.1 (OK)
pylint >=0.25      :  1.6.5 (OK)
rope >=0.9.2       :  None (NOK)
sphinx >=0.6.6     :  1.3.6 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  15.2.0 (OK)

**Comment by ccordoba12** [comment]
Spyder 2.3 is not supported anymore. Could you update to Spyder 3.1.3 (our latest version) and try again? Thanks!
