### ISSUE TITLE
Spyder issues the following error message when running the IPython console

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4332]
## Description
I am getting the following error message when I use the IPython console inside Spyder
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**
`GLib‑GIO‑Message: Using the 'memory' GSettings backend. Your settings will not be saved or shared with other applications.`

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 2.7.13
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
That seems a warning, possible issued because you're using the Gtk theme of Qt to make Spyder look native in Ubuntu.

Unfortunately, we can't do anything about it because it's probably a Qt issue.
