### ISSUE TITLE
Import Error in Spyder :  No module named CNTK

### ISSUE THREAD

**Issue by arunkumarwa** [spyder-ide/spyder#4333]
## Description of your problem
Hello,
I am trying to run python code which uses CNTK functionality.  The execution stumbles very early unable to find cntk  (ImportError: No module named 'cntk'). I suspect it is a path or env variable issue. 

Inside Spyder:

I have the PYTHONPATH set to:
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Library\bin;
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Scripts
C:\local\CNTK-2-0-beta15-0\cntk\cntk;

Additionally the Path environment variable is set:
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35;
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Library\mingw-w64\bin;
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Library\usr\bin;
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Library\bin;
C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\Scripts;
C:\local\CNTK-2-0-beta15-0\cntk\cntk;

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below** 
Here is what I see in the console, when I run:

runfile('C:/data-files/CNTK/temp.py', wdir='C:/data-files/CNTK')
Traceback (most recent call last):

  File "<ipython-input-1-ae57534010e1>", line 1, in <module>
    runfile('C:/data-files/CNTK/temp.py', wdir='C:/data-files/CNTK')

  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\local\Anaconda3-4.1.1-Windows-x86_64\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 89, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/data-files/CNTK/temp.py", line 12, in <module>
    from cntk import Trainer, cntk_device, StreamConfiguration, learning_rate_schedule, UnitType

ImportError: No module named 'cntk'

## Versions and main components

* Spyder Version:2.3.9
* Python Version: 3.5
* Qt Version: 4.8.7
* PyQt Version:PyQT4(API v2) 4.11.4
* Operating system: Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I'm sorry but this is an installation problem and/or configuration problem with CNTK (which I don't know what it is), so (unfortunately) we can't help you.

**Comment by arunkumarwa** [comment]
Hi Carlos


Appreciate you responding.   I don't disagree it is CNTK / Spyder issue.  But it might help if some of the experts (even yourself) were to give me some pointers.  I am new - havent coded in the last 10 years.


there must be some method in the path and pythonpath variables that makes sypder go resolve dependencies.  I am just looking for that insight.  can you help?


thx

arun


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
