### ISSUE TITLE
cv init failure: Invalid argument

### ISSUE THREAD

**Issue by nowox** [spyder-ide/spyder#4335]
## Description of your problem

1.  Install Spyder from Cygwin with `pip install -e .`
2.  Run Spyder
3.  Read stderr: `: cv init failure: Invalid argument`

How can I run Spyder in debug mode, read the logs or even see where it failed?

## Versions and main components

* Spyder Version: master
* Python Version: 2.7
* Qt Version: 5.4.2-1
* PyQt Version: 4.11.4-1, 5.4.2-1
* Operating system: Cygwin

**Comment by ccordoba12** [comment]
We don't support Cygwin at the moment, sorry. So it's up to you how to solve this.

You can read all debug messages Spyder generates by starting it like this

    SPYDER_DEBUG=3 spyder

**Comment by nowox** [comment]
That's more than I need. Thanks.
