### ISSUE TITLE
Keyboard shortcuts for navigating between Editor / IPython Console not working

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [spyder-ide/spyder#4339]
## Description of your problem
Keyboard shortcuts cntrl+shift+I and cntrl+shift+E for navigating between editor and IPython console window stopped working for me a few days ago. Still not working after upgrading spyder, and even though in my preferences > shortcuts menu they still appear. Also tried clicking "restore to defaults" in keyboard shortcuts menu which also did not help.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.5.2 (Anaconda 4.2.0 64-bit)
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Linux Mint

**Comment by ccordoba12** [comment]
Maybe other program (running at the level of your desktop) is interfering with those shortcuts.

**Comment by ccordoba12** [comment]
Closing because there's nothing we can do about this, sorry.
