### ISSUE TITLE
Connecting to remote kernel on Spyder startup

### ISSUE THREAD

**Issue by ippischtobi** [spyder-ide/spyder#4340]
I frequently work with Spyder (3.1.3) on Windows 10 by connecting to a remote kernel on a Windows server (2012 R2).
This works fine, but I do not want to provide the required information (connection info in json.file, host name, ssh key) each time I connect to the remote kernel. 

Is there a way to automate this process, either by a) tweaking the spyder source code or b) executing a small function in spyder: 

def connect_to_remote_kernel(connection_info = 'C:/kernel-12345.json', ssh_key = 'C:/key.pem', host_name = "user1234@some.server.net:22"):
    some code
    return

It would be great if this process could be automated in a future spyder release.

Cheers, 
Tobi

**Comment by goanpeca** [comment]
@bcolsen what do you think about this?

I have seen some issues on improvements for this

**Comment by bcolsen** [comment]
I think that the real answer here would be to have a connection manager of some sort that remembers previous connections. 

I think something like that will be implemented in with remote editing.
https://github.com/spyder-ide/spyder/issues/3065

We can probably close this.
