### ISSUE TITLE
Spyder crashes when directory is changed.

### ISSUE THREAD

**Issue by sanjogh777** [spyder-ide/spyder#4347]
## Description of your problem

**What steps will reproduce the problem?**

1. When the directory is changed. Everything is latest up to date.

* Operating system: Windows 10.

**Comment by ccordoba12** [comment]
What directory? Could you be more specific?

**Comment by sanjogh777** [comment]
The working directory in which I have saved the csv files.

**Comment by sanjogh777** [comment]
![screenshot 49](https://cloud.githubusercontent.com/assets/26878382/24847778/2ca4de0e-1d91-11e7-8c91-893fc229ad13.png)
When I click the folder for the working directory, spyder crashes.

**Comment by laincortes** [comment]
Yeah, that isn't very useful, since you can't see any "crashing" happening. You could run it since the command prompt and copy the output if it crashes.

**Comment by ccordoba12** [comment]
@sanjogh777, what is your Spyder version?

**Comment by laincortes** [comment]
Can it helps to look at the python and ipython version (s)he is using?

**Comment by sanjogh777** [comment]
I have changed the Spyder version from 3.1.3 to 3.1.2. It's working now.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it!
