### ISSUE TITLE
Spyder crashes on wake, Mac OSX Sierra 

### ISSUE THREAD

**Issue by jrubinstein** [spyder-ide/spyder#4348]
## Description of your problem
I have installed Spyder through Anaconda Navigator. Spyder launches fine, but will crash after sleep/wake. 
I'm on Mac 10.12.1 (16B2657), 2016 Macbook Pro, 16GB 
Spyder 3.1.3 
Python 2.7.13 64bits, Qt 5.6.2, PyQt5 5.6 on Darwin 

It seems to happen every time, I close my lid then re-open after a couple of minutes.

**Comment by ccordoba12** [comment]
This is a know issue. Unfortunately, we don't know how to fix it, sorry.
