### ISSUE TITLE
Spyder do not start in hard way mode

### ISSUE THREAD

**Issue by GermanRR** [spyder-ide/spyder#4350]
## Description of your problem
I am trying to install spyder without conda, following the steps of hard way. The reason is that only with the specified packages of python the size of installation is 493 mb, but with miniconda the size with the same modules is 2.4 gb. The problem is that when I use the command (python bootstrap.py) the program starts the checkout, it says bootstrap completed in... but Python popup windows appears saying that there is a problem with python and needs to be closed.

**What steps will reproduce the problem?**

1. After all packages installed, run the command (python bootstrap.py) gives python crash problem after checkout. The checkout have all the step, and appears to be correct
2. Trying directly with the spyder.exe do not do nothing.
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
I will try the other distributions of spyder, with python x,y and I have the same problem, with WinPython using the Prompt program I obtain the same crash python problem... but with miniconda runs correctly, but I prefer the hard way. I uninstall some packages of my installation to do a downgrade of some packages (like html5lib==0.999) because in miniconda uses this package instead of html5lib==0.999999999 but the same result. 

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.1 v.1900 32 bit
* Qt Version: QtPy==1.2.1
* PyQt Version: PyQt5==5.8.2
* Operating system: Windows 7 Enterprise x64
* List of packages instaled:

alabaster==0.7.10
appdirs==1.4.3
asn1crypto==0.22.0
astroid==1.4.9
Babel==2.4.0
bleach==2.0.0
cffi==1.10.0
chardet==2.3.0
colorama==0.3.7
cryptography==1.8.1
cycler==0.10.0
Cython==0.25.2
decorator==4.0.11
docutils==0.13.1
entrypoints==0.2.2
html5lib==0.999999999
idna==2.5
imagesize==0.7.1
ipykernel==4.6.0
ipython==5.3.0
ipython-genutils==0.2.0
isort==4.2.5
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-client==5.0.1
jupyter-core==4.3.0
lazy-object-proxy==1.2.2
MarkupSafe==1.0
matplotlib==2.0.0
mccabe==0.6.1
mistune==0.7.4
mpmath==0.19
nbconvert==5.1.1
nbformat==4.3.0
numpy==1.12.1
numpydoc==0.6.0
packaging==16.8
pandas==0.19.2
pandocfilters==1.4.1
pep8==1.7.0
pickleshare==0.7.4
pip-review==0.5.3
prompt-toolkit==1.0.14
psutil==5.2.2
pyasn1==0.2.3
pycparser==2.17
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.6.5
pyOpenSSL==16.2.0
pyparsing==2.2.0
PyQt5==5.8.2
python-dateutil==2.6.0
pytz==2017.2
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1
requests==2.13.0
rope-py3k==0.9.4.post1
simplegeneric==0.8.1
sip==4.19.2
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.5.5
spyder==3.1.3
sympy==1.0
testpath==0.3
tornado==4.4.3
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.10.10

I do not know the reason for this crash. Any ideas?
Thank you for the program.

**Comment by ccordoba12** [comment]
> but with miniconda runs correctly, but I prefer the hard way

I'm very sorry to say this, if you want to go *the hard way*, it's up to you to find out what's happening and fix it. This is because *the hard way* is for experts only, i.e. those who have intimate knowledge of all Spyder dependencies.
