### ISSUE TITLE
Spyder keeps loading command prompt with usetex=True set

### ISSUE THREAD

**Issue by necarion** [spyder-ide/spyder#4355]
In Spyder 3.1.1 and 3.1.2, when Pyplot rcparams are set s.t. usetex=True, the ipython console begins rapidly opening and closing new command windows (for about a minute) until the console crashes.  The windows can be stopped by aborting and restarting the console.

**What steps will reproduce the problem?**

1. import matplotlib.pyplot as plt, import numpy as np
2. plt.rc('text',usetex=True)  (or some other method to set usetex=True)
3. fig = plt.figure(), axis = fig.add_subplot, axis.anything

This has happened on three separate computers running different versions of windows 10

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.1, 3.1.2
* Python Version: 2.7.13
* Operating system: Windows 10

## Dependencies
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. Unfortunately, there's nothing we can do about it in Spyder.

Please open an issue in the Matplotlib repo about this:

https://github.com/matplotlib/matplotlib
