### ISSUE TITLE
Significant energy use and heat up on MacBook Pro 15 2016 (macOS Sierra 10.12.4)

### ISSUE THREAD

**Issue by msaadq** [spyder-ide/spyder#4356]
## Description of your problem
I have a MacBook pro 15 2016 model. The machine is able to run powerful softwares very smoothly with no heat up but as soon as I start Spyder on my machine, it starts heating up significantly fast. The computer battery recommender also shows that that Python is using significant energy and battery life reduces significantly even when I don't run any python script and it stays like that till I close Spyder. I am using the Anaconda distribution with python 2.7.13.

<img width="261" alt="screen shot 2017-04-12 at 9 48 50 am" src="https://cloud.githubusercontent.com/assets/11469405/24941684/a5daafa8-1f65-11e7-87dc-01e8a95ed465.png">

**What steps will reproduce the problem?**

1. Open Terminal on MacBook Pro 15 (2016)
2. Type "spyder" to launch it

**What is the expected output? What do you see instead?**
Spyder is supposed to consume as much energy as Jupyter Notebook (Which does not cause any heat up, significant battery loss or warnings) which is not the case here as my battery is losing charge significantly fast with heat up.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: macOS Sierra 10.12.4

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
I don't know what's happening in your case, and without more info, it's hard for me to give appropriate help.

All I can say is that nobody else has reported this problem, so it's probably related to your setup.

**Comment by msaadq** [comment]
Alright. I will try installing it again then.

**Comment by ccordoba12** [comment]
Thanks for understanding. Please reopen this issue if the problem continues.

**Comment by msaadq** [comment]
The problem still persists even after reinstalling. I have even tried the anaconda3, but getting the same heat up.

**Comment by ccordoba12** [comment]
I'm really sorry but I don't know what happens, probably an issue with macOS 10.12.4, but I don't own a Mac to test.

**Comment by NV2019** [comment]
I have a similar problem with using anaconda navigator
