### ISSUE TITLE
Warning message when launch Spyder

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [spyder-ide/spyder#4357]
I just installed Spyder on my laptop.

When I try to activate Spyder, I got the warning message.

`void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "Project explorer" under id 130 
`
I am using Python 2.7.12 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Linux, which should be fine because I can run my Spyder correctly with this setting on another laptop. 

I can neglect the message and go on, but I am wondering what might cause the warning ?

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a harmless warning generated by Ubuntu, and it happens because we have the same action attached to two different menus.

Simply ignore it.
