### ISSUE TITLE
UnicodeEncodeError when entering unicode ellipsis in file editor

### ISSUE THREAD

**Issue by equaeghe** [spyder-ide/spyder#4358]
## Description of your problem

**What steps will reproduce the problem?**

1.  enter … (unicode ellipsis character) in file editor

**What is the expected output? What do you see instead?**

Expected: nothing. Got: internal console opens with error

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/spyder/widgets/editor.py", line 1371, in analyze_script
    finfo.run_code_analysis(run_pyflakes, run_pep8)
  File "/usr/lib64/python3.4/site-packages/spyder/widgets/editor.py", line 208, in run_code_analysis
    source_code = self.get_source_code().encode(enc)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 306: ordinal not in range(128)
```
**Please provide any additional information below**

This ellipsis was entered in the comments

## Versions and main components

* Spyder Version: 3.0.2
* Python Version: 3.4.5
* Qt Version: 5.6.2
* PyQt Version: 5.7.1
* Operating system: Linux

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.10.4 (OK)
pandas >=0.13.1  :  0.16.2 (OK)
pep8 >=0.6       :  1.5.7 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.2.3 (OK)
pygments >=2.0   :  2.1.1 (OK)
pylint >=0.25    :  1.5.6 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this issue in a future Spyder release.

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
I'm unable to reproduce this one:
![captura de pantalla de 2017-07-28 13-11-31](https://user-images.githubusercontent.com/1878982/28730617-866e8dbc-7396-11e7-92db-0030e1a3e617.png)

**Comment by equaeghe** [comment]
I tested again and I don't hit the issue now. However, what changed is that my Qt is now 5.7.1 (probably unimportant) and my pyflakes is 0.8.1 instead of 1.2.3 (probably important; I actually don't know why my distribution downgraded it).

So @andfoy, what is your pyflakes version?

**Comment by ccordoba12** [comment]
Pyflakes has nothing to do with this. It was (most probably) a Qt issue.
