### ISSUE TITLE
why a program can't run in spyder while it can run in terminal ?

### ISSUE THREAD

**Issue by hezhping** [spyder-ide/spyder#4359]
I work in ubuntu 14.04.
Both terminal and spyder IDE share same python Interpreter.
why a program can't run in spyder while it can run in terminal ?
For example, in terminal, I run

```
which nvcc
```

it returns

```
/usr/local/cuda-8.0/bin/nvcc
```

But in spyder, I run

```
import os
os.system('which nvcc')
```

it returns

```
256
```

Why and how to solve such a problem.

**Comment by ccordoba12** [comment]
The right command is

```python
import subprocess
subprocess.check_output('which nvcc', shell=True)
```

I don't know exactly why `os.system` doesn't work in this case, probably because `which` requires a real shell to be run.
