### ISSUE TITLE
Ipython console multithreading does not executed properly

### ISSUE THREAD

**Issue by LMJW** [spyder-ide/spyder#4362]
http://stackoverflow.com/questions/43345482/spyder3-ipython-console-threading-issue

This is the stackoverflow questions, basically, the threading will print all the result at once when the programs finishes but not sequentially if I run the threading program in the ipython console. If I use the python console or idle, it works fine. I suspect  this is the issue for spyder ipython configuration but I am not quite sure how to solve this. My laptop is win 10. I have upgraded my spyder to the latest version and the problem still resisted. 

Thanks in advance for your help.

'''Python 3.5.1 |Anaconda 2.5.0 (64-bit)| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 4.0.3 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.'''

**Comment by ccordoba12** [comment]
Please update your system with

    conda update anaconda
    conda update qt pyqt
    conda update spyder

and try again.

**Comment by LMJW** [comment]
@ccordoba12 
Thanks for the solution you provided. It seems that the problem still exist. One wired thing is that when I was trying to update anaconda, it actually downgrade the spyer from 3.1.3 to 2.3.8.

**Comment by ccordoba12** [comment]
What message do you get when you run this command?

    conda install spyder=3.1.3

**Comment by LMJW** [comment]
Hi ccordoba12,
The error message is:
======
C:\Users\will>conda install spyder=3.1.3
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - spyder 3.1.3*
  - spyder-app -> spyder 2.3.0rc1
Use "conda info <package>" to see the dependencies for each package.

**Comment by ccordoba12** [comment]
Ok, great! Then please run

    conda remove spyder-app

That should remove the package conflict that's blocking you from updating Spyder. Please try it and let me know if it works.

**Comment by LMJW** [comment]
@ccordoba12 
Hi Ccordoba12. It is working correctly now!!!
Thank you very much for the help!

**Comment by ccordoba12** [comment]
Great! Glad to be of help :-)
