### ISSUE TITLE
Double scrollbars in editor (OS X)

### ISSUE THREAD

**Issue by cgjosephlee** [spyder-ide/spyder#4363]
## Description of your problem
When scrolling the codes, the spyder scrollbar will shift left and the OS X original scrollbar show up, therefore two scrollbars at same time.
It's didn't cause any performance issue but annoying.

**What steps will reproduce the problem?**

1. every time scroll the codes in the editor
2. 
3. 

**What is the expected output? What do you see instead?**
suppress the OS X scrollbar, only spyder scrollbars with error notification on it

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7.13 64bit
* Qt Version: 5.71
* PyQt Version: 5.71
* Operating system: OS X 10.11.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  None (NOK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  None (NOK)

![scrollbar](https://cloud.githubusercontent.com/assets/12654602/25030131/82d038c0-20f5-11e7-946c-ff9fb5fb8179.gif)

**Comment by ccordoba12** [comment]
Thanks for reporting. We're aware of this and hope to give more functionality to the Spyder scrollbar in the future.
