### ISSUE TITLE
matplotlib blocking works in dedicated Python console, not in IPython console

### ISSUE THREAD

**Issue by hiccup7** [spyder-ide/spyder#4367]
Example code:
```
import numpy as np
import matplotlib.pyplot as plt

def onclick(event):
    global offset
    offset = event.ydata
    fig.canvas.mpl_disconnect(cid)
    plt.close()
    return

x = np.linspace(0, 2.0 * np.pi, 200)
y = np.sin(x)
fig = plt.figure()
plt.plot(x, y)
plt.title('Mouse left-click on the desired offset')
cid = fig.canvas.mpl_connect('button_press_event', onclick)
plt.show(block=True)

print('Offset =', offset)
```
When Spyder is configured to run this script in a dedicated Python console, it works fine (plot one sine wave, wait for the mouse click, print the y offset selected).

When Spyder is configured to run this script in an IPython console, there is no plot, and there is a runtime error on the last line -- NameError: name 'offset' is not defined.  This is because the desired blocking on the previous line did not block.  Also, when I close the IPython console after running this script, Spyder crashes.

I would like for this example to work correctly in the IPython console because I saw that the Python console will be removed from Spyder 3.2.

* Spyder Version: 3.1.4dev-201703025 that comes with WinPython 3.5.3.1Qt5-64bit
(the same problem happens with Spyder 3.1.2, 3.1.3)
* Python Version: 3.5.3
* Qt Version: 5.8.0
* PyQt Version: 5.8.2 (same problem happens with 5.8.0, 5.8.1)
* matplotlib: 2.0.0
* qtconsole: 4.2.1
* NumPy: 1.11.3
* Operating system: 64-bit Windows 8.1

**Comment by ccordoba12** [comment]
This certainly doesn't work in an IPython console, but if you replace `plt.show(block=True)` for `plt.pause(5)` then it works.

I think that's the best you can get from an IPython console because it always tries to generate plots in interactive mode.

**Comment by hiccup7** [comment]
`plt.pause(5)` is not a good work-around for me.  My complex plots sometimes take me a minute to decide where to mouse-click (a subjective process).  If the pause is less than a minute, the script terminates with an error in this case.  But if I mouse-click in the first 5 seconds, I wait for 55 seconds before the script continues.  I would really like matplotlib's blocking feature to work with IPython.

With the dedicated Python console, I set Spyder's advanced setting to use scientific_startup.py, which includes a call to matplotlib's `ion()` function.  In other words, the dedicated Python console is also using matplotlib's interactive mode, but the blocking works fine.

**Comment by goanpeca** [comment]
@ccordoba12 is this something that needs to be addressed directly in qtconsole?

**Comment by hiccup7** [comment]
@anntzer @tacaswell - Is this issue addressed by a matplotlib commit after the v2.0.0 release?
For example: https://github.com/matplotlib/matplotlib/pull/8185/

**Comment by anntzer** [comment]
I think my PR is unrelated but you can always give it a try...

**Comment by ccordoba12** [comment]
> is this something that needs to be addressed directly in qtconsole?

This is at the level of IPython. Unfortunately, event loop integration is one of trickiest parts of IPython and I'm not really sure what to do in this case. I tried to turn down interactivity (with `plt.ioff()`) and other similar tricks but none worked in this case.

I'll try to come up with a better solution.

**Comment by hiccup7** [comment]
@anntzer - I edited `backend_qt5.py` according to the changes in matplotlib/matplotlib#8185/, but it did not help with this issue.

**Comment by ccordoba12** [comment]
@hiccup7, what about this?

```python
import numpy as np
import matplotlib.pyplot as plt

def onclick(event):
    global offset
    offset = event.ydata
    fig.canvas.mpl_disconnect(cid)
    plt.close()
    return

x = np.linspace(0, 2.0 * np.pi, 200)
y = np.sin(x)
fig = plt.figure()
plt.plot(x, y)
plt.title('Mouse left-click on the desired offset')
cid = fig.canvas.mpl_connect('button_press_event', onclick)
while not 'offset' in locals():
    plt.pause(5)
print('Offset =', offset)
```

This doesn't wait an specific amount of time, but until `offset` acquires a definite value. I think it's equivalent to `block=True`.

**Comment by hiccup7** [comment]
@ccordoba12 - That is a clever work-around.  To minimize CPU and response time, I tested successfully replacing `plt.pause(5)` with `plt.waitforbuttonpress(timeout=-1)`.

Both of these work-arounds produce a false deprication warning by matplotlib v2.0.0.  The user can avoid this by locally applying the edit in matplotlib/matplotlib#8185/.

I am happy with this work-around if it is too difficult to make `plt.show(block=True)` work with IPython.

**Comment by ccordoba12** [comment]
> make plt.show(block=True) work with IPython.

@tacaswell, sorry to bother you, but is that possible?

**Comment by tacaswell** [comment]
`plt.show(block=True)` seems to work in the IPython '5.3.0' with `plt.ion()` not in spyder, I suspect that this may be complicated by being embedded in a larger Qt app who is already running an `exec_` call.  

The function that gets called under the hood is (eventually)

```python
    def mainloop(self):
        # allow KeyboardInterrupt exceptions to close the plot window.
        signal.signal(signal.SIGINT, signal.SIG_DFL)
        global qApp
        qApp.exec_()

```

where `qApp` is gotten through the standard 'is there an app? if not make one, else use it' dance every time we create a qt canvas.  


In the case of 'normal' IPython when we call `plt.show(block=True)` there is not another concurrent call to `exec` going (assuming you are using the prompt toolkit version of IPython, the hook is https://github.com/ipython/ipython/blob/master/IPython/terminal/pt_inputhooks/qt.py ) which lets the event loop run until you type a key.   Hence blocking works (as to IPython/python/prompt_toolkit it just looks like a really long running function).

However, in the case of being embedded in spyder, I suspect that the control is inverted, the qt event loop is always running and every so often it says 'Ah, a keypress, here you go IPython'.  In this case when you try to block, it says "all ready running, next".

 (I am still a bit hazy about process edges here and exactly where what runs, but this is my working theory)

**Comment by hiccup7** [comment]
Since `plt.show(block=True)` seems to work in a stand-alone IPython console, could Spyder use a "dedicated" IPython console (separate process) to solve the problem?  In other words, similar to running in a "dedicated Python console".

**Comment by ccordoba12** [comment]
@tacaswell, I think the problem has to do (somehow) with the Jupyter kernel/frontend architecture. I mean, if you run @hiccup7's original code with `plt.ion()` in `jupyter console` (which is equivalent to terminal IPython, but uses a kernel to run code), you'll get the same result as with Spyder.

@hiccup7, a dedicated IPython console will be the same as a regular IPython console, only associated with a particular file. All our IPython consoles run in a separate process (else any computation will block Spyder completely).

Anyway, since we found a workaround for this problem and it's the best we can do for now, I'm closing this issue.

**Comment by tacaswell** [comment]
Does that mean that there is a qApp running in the fore-ground to run spyder / qt console and there is a second one running in the kernel which own the matplotlib figures (and they don't talk to each other ?!)?

**Comment by ccordoba12** [comment]
Yes, that's correct. Since the kernel runs in a separate process from Spyder, when it runs `%matplotlib qt{5}`, it creates a new qApp to start the corresponding Qt event loop. And from the Spyder side we don't have any control over that qApp.
