### ISSUE TITLE
Problem with using tabs in wordpress 

### ISSUE THREAD

**Issue by rachidshop** [spyder-ide/spyder#4373]
Hello Guys, 
I really need help, when I use tabs with blog slide. in the first tab the slide works fine, but in the second and other tabs is not working but when I reload the page with the second tab it work but other tabs not working, you can see my problem here: http://www.cleanenergies.ma/home-2

I use the visual composer but I also tried to use other tabs plugins I got the same problem. pls tell what I can do to solve this problem?

thanks a lot guys.

**Comment by jitseniesen** [comment]
This has nothing to do with spyder.

**Comment by rachidshop** [comment]
i update the post now u will see the problem that i have.

**Comment by jitseniesen** [comment]
@rachidshop This page is about Spyder, a program for writing and executing Python scripts. It has nothing to do with Wordpress and we do not know anything about Wordpress, so you should ask about your problem elsewhere.
