### ISSUE TITLE
Error with jedi 0.9.0

### ISSUE THREAD

**Issue by GermanRR** [spyder-ide/spyder#4379]
## Description of your problem
It is not a problem, maybe a bug

**What steps will reproduce the problem?**

1. Launch spyder 3 gives me an error due to jedi
2. 
3. 

**What is the expected output? What do you see instead?**
Spyder3 runs correctly but with the advertisement of jedi dependencies

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3 installed with "pip install -U spyder"
* Python Version: 3.6.1 x86
* Qt Version: 5.8 installed with "pip3 install pyqt5"
* PyQt Version: 5.8.2 installed with "pip3 install pyqt5"
* Operating system: Windows 7 x64

## Dependencies

The problem is that after use "pip install -U spyder" the system don't use the last version of ipython, so the spyder don't start. After update ipython, spyder runs correctly but with the advertisement of jedi, due to the update of ipython updates jedi

If I install jedi 0.9.0, spyder don't run, but with 0.10.2 runs correctly but wit the advertisement.

**Comment by ccordoba12** [comment]
Why it doesn't run with 0.9?

**Comment by GermanRR** [comment]
I reinstall jedi 0.9.0. The error are:
raise VersionConflict(dist, req).with_context(dependent_req)pkg_resurces.VersionConflict: (jedi 0.9.0 (c:\....), Requirement.parse('jedi>=0.10'))

Maybe python 3.6.1, needs jedi 0.10

I don't know, but with jedi updated works fine (with the advertisemnet).

Thanks for your software, it is great!

**Comment by GermanRR** [comment]
This advertisement is due in the dependencies list of spyder 3.1.3, all the packages have a >=...and only jedi needs a specific package version.

**Comment by romanet** [comment]
new IPython 6.0.0 requires jedi>=0.10

**Comment by ccordoba12** [comment]
Thanks @romanet for the clarification.

Spyder 3.1.4 will be compatible with Jedi 0.10+ and it'll be released this weekend.

**Comment by ccordoba12** [comment]
@GermanRR, Spyder 3.1.3 is only compatible with Jedi 0.9, that's the reason of us requiring that specific version.
