### ISSUE TITLE
Conda 3.1.3 installation forces downgrade

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#4380]
Attempting to keep my anaconda installation updated leads to a downgrade of `spyder 3.1.3`:
```
[duro@ocean thisDir]$ conda update anaconda
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/user/anaconda2:

The following packages will be UPDATED:

    anaconda: custom-py27_0 --> 4.3.1-np111py27_0

The following packages will be DOWNGRADED due to dependency conflicts:

    spyder:   3.1.3-py27_0  --> 3.1.2-py27_0
```
It'd be great if this was no longer the case with the `v3.1.4` release

**Comment by ccordoba12** [comment]
This is because the latest Anaconda release comes with Spyder 3.1.2, we can't do anything about it.

> It'd be great if this was no longer the case with the v3.1.4 release

For that you have to wait until a new Anaconda version is released.
