### ISSUE TITLE
Spyder 3.1.2 will not launch (Anaconda Distro - Win10 64Bit)

### ISSUE THREAD

**Issue by nsbernar** [spyder-ide/spyder#4381]
## Description of your problem
I installed Anaconda yesterday (4/20/17), since it came with Spyder and that's a program I'm used to for Python.  Opening the Anaconda Navigator, there was a button/tile to launch "spyder 3.1.2", and it would launch a version of spyder.  Unfortunately, it was spyder 1.something, and upon launching it would remind me that there's a new version available, however there was no way to update using the Anaconda Navigator.  

 

I found a tip online that said to use the command prompt and ">pip install --upgrade spyder"

Where I am right now, the internet is terrible so this took a while to get to work (about 10 timeouts).  

Now, when I launch spyder either from the taskbar or from Anaconda Navigator, the launch tile/screen shows up, and now says "spyder 3".  However, it immediately crashes and gives me the error (paraphrased):

"Spyder crashed during last session. .... "try python spyder --reset".

Tried that, didn't help.

Then I went on github and found some similar situations but nothing exactly like mine.
**What steps will reproduce the problem?**

1. Launching spyder from the task bar.
2. Launching spyder from the Anaconda Navigator
3. 

**What is the expected output? What do you see instead?**
Expected output: Spyder 3 launching.

Instead: That same error message mentioned above.

**Please provide any additional information below**

2014 Surface Pro 3 - i5 Processor

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version:5.6.0
* Operating system: WIndows 10 64 bit

Never installed python before so I may be missing something obvious, thanks for any help!

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please simply try

    spyder --reset

and try again

**Comment by nsbernar** [comment]
Hello,

Sorry I forgot to put this in the posting, I had already tried that.

Anything else I can try?

Nathan

**Comment by ccordoba12** [comment]
Please run

    conda update spyder

and try again

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by MonicaSai7** [comment]
When I launch Spyder, while loading editor the error saying "Python not working" pops up.
Even python code is not executing in Jupyter notebook.
I've already tried re-installing anaconda over 10 times. Still the issue is not resolved.

**Comment by nsbernar** [comment]
Idk why I'm in this email chain, please remove me, thank you.
