### ISSUE TITLE
spyder3.1.3 can't support jedi0.10.2

### ISSUE THREAD

**Issue by zeroclyy** [spyder-ide/spyder#4383]
## Description of your problem
When I update Ipython 6.0 ,jdei was updated to 0.10.2. Spyder3.1.3 can't work ,because jedi 0.9.0 is mising. 
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Yes, we are aware of this issue. It'll be fixed in 3.1.4.
