### ISSUE TITLE
Python Turtle lags on Spyder

### ISSUE THREAD

**Issue by vietzerg** [spyder-ide/spyder#4384]
## Description

**What steps will reproduce the problem?**

1. Import `turtle` module.
2. Instruct the turtle to draw something.

**What is the expected output? What do you see instead?**

The Python Turtle Graphic windows popped but minimized at taskbar and when I click on its icon, it freezes. In other words, Windows says:

> Python3 is not responding

**Please provide any additional information below**

Here's the code, just for reference:

```
from turtle import *

pencolor("green")
speed(60)

n = int(input("Number of circles? "))
for i in range(0,n):
    circle(100)
    left(360/n)
```

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
You need to run first

    %gui tk

in an IPython console for `turtle` to work. Or you can change your Graphics backend in

    Tools > Preferences > IPython console > Graphics

so it always uses `Tk` by default.
