### ISSUE TITLE
Spyder 3.0.0 runfile issue

### ISSUE THREAD

**Issue by onlycec** [spyder-ide/spyder#4385]
## Description of your problem
Getting this error 

 runfile('C:/Users/D/'Costa/Google Drive/Certification/Udemy/Machine Learning/ML1.py', wdir='C:/Users/D/'Costa/Google Drive/Certification/Udemy/Machine Learning')
                             ^
SyntaxError: invalid syntax 
I have an apostrophe in my name and the windows folder is structured that way, Is there any way to workaround this , and also fix this in the long term as a lot of people have the apostrophe in their names.

**Comment by ccordoba12** [comment]
Please update to Spyder 3.1.3. This error is already fixed in that version.
