### ISSUE TITLE
cannot see Cursor in Spyder IDE 3.1.3

### ISSUE THREAD

**Issue by ericxuhua** [spyder-ide/spyder#4388]
## Description of your problem

**What steps will reproduce the problem?**

1. Whenever type command in Editor
2. 
3. 

**What is the expected output? What do you see instead?**
I can see Cursor (either as different color or blinking) so I know where I'm typing

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.5
* Qt Version:
* PyQt Version:
* Operating system: Win7, 64bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
This happens when you're trying to edit files that are read-only.
