### ISSUE TITLE
Custom Editor Font

### ISSUE THREAD

**Issue by martmists** [spyder-ide/spyder#4390]
I would really like to see this feature as:

- As far as I'm aware it's not possible to change the font in the editor
- I prefer using fonts with ligatures, such as FiraCode or similar

I'm sure there are others who would also like to see this feature, and I don't see how this is all that hard to add.

**Comment by ccordoba12** [comment]
Fonts for the Editor can be changed in

    Preferences > General > Appearance

Only monospace fonts installed in your system can be used in the Editor.

**Comment by martmists** [comment]
FiraCode is monospaced, yet I don't seem to be able to select it in the `plain font` section, only in the `rich text` portion.

**Comment by martmists** [comment]
Update: Forcing it into Firacode by typing it in the window works, but it unfortunately also applies to the Python and IPython console.

**Comment by ccordoba12** [comment]
The same font is used by all Panes, that's by design.

**Comment by martmists** [comment]
In my opinion it would be nice to be able to use a different font in editor/console, though I'm not sure how others feel about this.
