### ISSUE TITLE
python 3.5 stop working

### ISSUE THREAD

**Issue by mingguichen** [spyder-ide/spyder#4394]
## Description of your problem
I accidentally installed two versions of anaconda3 with python3.5 as the default interpreter. And then my python 3.5 is completely crashed, with an error "python has been stopped working" when you try to start spyder. I am working on Windows 7 x64. Other versions of python including 3.6 (anaconda3-4.2.0) and 2.7 (anaconda2) are working completely normal. All python 3.5, anaconda3 4.0.0 to 4.1.1, are going bad. Please do me a favor to get it work, as python 3.5 is really important for me. Thanks a lot!

**What steps will reproduce the problem?**
1. install one version of anaconda3 with default 3.5 interpreter
2. install another version of anaconda3  also with default 3.5 interpreter

**What is the expected output? What do you see instead?**
python has been stopped working when you start spyder

**Please provide any additional information below**

## Versions and main components
all with default python 3.5, such as anaconda3 4.0.0 to 4.1.1

**Comment by ccordoba12** [comment]
You need to stop installing multiple versions of Anaconda and instead use conda environments.

So please remove all your Anaconda versions  but one and google on how to use conda envs

**Comment by mingguichen** [comment]
thanks for the reply. Right now, I can not start python3.5 anymore, even if I uninstall all the python and reinstall only one anaconda with 3.5. 

Another issue, how could we switch the conda env in spyder gui and scripts? I already searched online a lot, but no promising solution found yet.

**Comment by ccordoba12** [comment]
You need to change your python interpreter for that, in

    Preferences > Python interpreter

**Comment by mingguichen** [comment]
I already tried that, but you will get an error: the spyder is based on a different version, then a lot of dialogs coming out.

Could you please try to find the issues of my python35? Thanks a lot.

**Comment by mingguichen** [comment]
Please see the screenshots.
![python](https://cloud.githubusercontent.com/assets/10821596/25388793/5fc5e72a-2a01-11e7-87d7-5c5f118733c3.png)
![spyder](https://cloud.githubusercontent.com/assets/10821596/25388800/6240a71a-2a01-11e7-984e-3b43f750f958.png)

**Comment by ccordoba12** [comment]
Sorry, I really don't know what's happening in your case. It looks a problem with Qt5, maybe you could try to use Qt4 instead.
