### ISSUE TITLE
Why is the support for the console dropped?

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#4395]
## Description of your problem

I noticed that the Python console will be removed in future Spyder 3.2. May I ask what is the motivation behind this removal?

I personally tried IPython a couple of times but never warmed to it. Maybe I am a singular case. Maybe not. I would love to see the console retained in future releases.

**Comment by ccordoba12** [comment]
I'll create an issue explaining all the reasons we have to drop the Python console. The main ones are:

1. It's broken on Windows.
2. It's unmaintained right now (its creator left the project several years ago).
3. It's confusing for beginners to have two consoles.
4. We are a small project and don't have the time or resources to maintain two consoles.

**Comment by Eric89GXL** [comment]
This is already sufficient (and reasonable) explanation for me at least.

**Comment by denson** [comment]
The console/variable explorer combination are the only reasons I use Spyder.

**Comment by ccordoba12** [comment]
We're not going to remove the IPython, just the Python one, so everything will work as before.
