### ISSUE TITLE
Spyder cannot launch after upgrading to 3.1.4

### ISSUE THREAD

**Issue by superyangtze** [spyder-ide/spyder#4396]
I was using Spyder 3.1.3 on Windows 64 bit OS with Python 3.5 and  PyQt 5.6.0. All worked fine.
Unfortunately after upgrading to version 3.1.4 today, Spyder just cannot launch. It stops at the start-up splash: "Setting up main window...".
I tried `spyder3 --show-console` but no errors showed.
And the command `spyder3 --reset` didn't work.
Please help to solve the problem. Thanks.
Regards!
Robert Young

**Comment by ccordoba12** [comment]
What happens if you downgrade to 3.1.3?

**Comment by superyangtze** [comment]
When I tried to downgrade to version 3.1.3, the program crashed at the start-up splash as well.

**Comment by superyangtze** [comment]
...and sometimes a warning dialog poped up, saying "Spyder crashed during last session." and so on.

**Comment by mayurpande** [comment]
Is there a spyder 3.1.4 for spyder3? As I keep trying to upgrade it and nothing happens. On ubuntu 16.04, it just stay the same.

**Comment by superyangtze** [comment]
Yes. The new version was just released yesterday.

**Comment by ccordoba12** [comment]
Closing because there's no additional info we can use to help you, sorry.
