### ISSUE TITLE
Variable explorer is not updated during code execution

### ISSUE THREAD

**Issue by ElieGouzien** [spyder-ide/spyder#4398]
## Description of your problem

All this apply for the qtconsole only (not the standard python).
The variable explorer completely freezes during code execution since spyder 3.
As highlighted in #3523 it's no more possible to see updates, but even worse it's not possible to explore variables at all.

#### Half-working
1. type `l = [[1, 2, 3], [4, 5, 6]]`
2. open 'l' in the variable explorer.
3. start : 
```python
import time
for _ in range(1000):
    time.sleep(0.5)
```
4. look into the nested list 'l' in the variable explorer.

Note that any change you make from the variable explorer is discarded if you interrupt the console execution.

#### Not-working
1. type `l = [[1, 2, 3], [4, 5, 6]]`
2. start : 
```python
import time
for _ in range(1000):
    time.sleep(0.5)
```
3. double click on 'l' in the variable explorer : nothing happens.

### What is the expected output? What do you see instead?
I would expect to be able to interact with the variable explorer even during a computation (and better, with up-to-date values), as in spyder 2 or the python console.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.4
* Qt Version: 5.2.1
* PyQt Version: 5.2.1
* Operating system: Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

## Possible solutions
I've tried to find a solution but I don't have the necessary knowledges about Qt and IPython kernels.
Here is a review of what I've found (perhaps more on the possibility to have auto-refresh back).

Starting from [this nice enhancement proposal for Ipython](https://github.com/ipython/ipython/issues/9354) (that would actually be great to have as option in spyder), I've [found](https://gist.github.com/takluyver/8c25dcf1f175159b0c741207a6dda94a) this way  to interact with running python program (linux specific) : 

1. run %connect_info and find the kernel in htop
2. launch in the qtconsole
```python
import signal
import time

def handle_sigint(signo, frame):
    print(globals())

signal.signal(signal.SIGUSR1, handle_sigint)

for a in range(10000):
    time.sleep(0.5)
    print(a)
```
3. from htop send SIGUSR1 to the kernel
4. look at what happened in the console.

Now I wonder how to take advantage of it to be able to refresh/interact with the variable explorer during a computation. 
Maybe for the refresh it would be sufficient to give the possibility to the console to call refresh_namespacebrowser() via get_ipython().*, make the signal connection at the initialisation of the console and send periodically SIGUSR1 to it. Also we should find a way to make the same thing only with IPython if we want to have this cross-platform.

Another idea is to make a queue of spyder instruction to the kernel and make some handler called when it receive SIGUSR1.

Maybe using get_ipython().events could help but I don't understand everything with that. Here seems to be the [doc](http://ipython.readthedocs.io/en/stable/config/callbacks.html).

For scientific computations we often don't set up tests, have dirty code and long execution time. Hence it was really nice in spyder 2 to be able without any effort (or just a 'global') to see early anomalies during execution. Maybe you should keep the python console until we have a solution for the qtconsole.
I'm willing to help but really need help to go further.

**Comment by ccordoba12** [comment]
> I would expect to be able to interact with the variable explorer even during a computation (and better, with up-to-date values), as in spyder 2 or the python console.

This is simply not possible with our current design. We are asking the kernel to *execute* some operations to update the Variable Explorer and get/set values from/to its namespace, so those operations are put on queue after the current computation.

> Hence it was really nice in spyder 2 to be able without any effort (or just a 'global') to see early anomalies during execution.

I wasn't aware of this. It's really nice things were working like that before, but that's not something we planned from the start.

> Maybe you should keep the python console until we have a solution for the qtconsole.

That's a no go. The Python console is unmaintained since almost a year, and it's really unstable (specially on Windows). So it's going to be removed in 3.2, as planned. You can still use any previous version of Spyder as long as you want, but (unfortunately) they won't receive bugfixes.

We could also create an external (third-party) plugin out of it, but we won't put a single bit of effort to fix its bugs (I've already put countless hours to support it throughout the years, and I'm done with it, sorry).

----

The only thing that occurs to me is to switch to use [Comms](http://jupyter-client.readthedocs.io/en/latest/messaging.html#custom-messages) to communicate with the kernel, instead of `execute` requests.

However, that's a huge effort: it amounts to rewrite our current design and also to add support for Comms in qtconsole. So it could come in Spyder 4, but definitely not 3.

**Comment by goanpeca** [comment]
>However, that's a huge effort: it amounts to rewrite our current design and also to add support for Comms in qtconsole. So it could come in Spyder 4, but definitely not 3.

That sounds like a plan! :-)

**Comment by ccordoba12** [comment]
We have to ask Jupyter guys if that's possible (I'm not so sure, but I think it is).

But that's as hard to implement as what we already have (and boy, that was hard!!).

**Comment by goanpeca** [comment]
>But that's as hard to implement as what we already have (and boy, that was hard!!).

:-\, probably but it might pay off in the long run

**Comment by ccordoba12** [comment]
Yes, the implementation would be definitely cleaner and we could have what @ElieGouzien (and probably other people) wants.

**Comment by ElieGouzien** [comment]
Nice to see there is hope !
I will have a look at [Comms](http://jupyter-client.readthedocs.io/en/latest/messaging.html#custom-messages) but it sounds lot of work and I don't have so much time.

----------------------------------------

If I come up with a unix only (temporary) solution, would it be elegible for a pull request ?
More exactly I'm now thinking of :
* Giving to the kernel a reference to the instruction queue owned by the console (widget or client, I don't know).
* Write a new kernel method which looks at that queue and execute its elements.
* Init the kernel with a signal handler that trigger the new method when received SIGUSR1.
* Make the interface to send SIGUSR1 to the kernel when needed.

I'm planning to have a look at it this week-end.

@ccordoba12 :
> We are asking the kernel to execute some operations to update the Variable Explorer and get/set values from/to its namespace, so those operations are put on queue after the current computation.

Where is defined that queue exactly (file/line) ?
