### ISSUE TITLE
Bug: Jedi dependency

### ISSUE THREAD

**Issue by khider** [spyder-ide/spyder#4400]
## Description of your problem

**What steps will reproduce the problem?**

1. Run pip install spyder --upgrade
2. run Spyder

**What is the expected output? What do you see instead?**

I get a lot of error messages on deprecations for uninstalling dependencies. Tried to launch Spyder and I get the error message of the jedi dependencies having to be 0.9.0, yet jedi was upgraded to 0.10.2. This makes the ipython console unusable (not quick start loaded).

Tried to downgrade to 0.9.0. Spyder crashes on lunch. 

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.3
* Python Version:3.5 
* Qt Version:
* PyQt Version:
* Operating system:Mac OS X 10.12.4

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ElieGouzien** [comment]
Hi,

This has normally been fixed with spyder 3.1.4.
I suggest you retry and report here what happens.

**Comment by khider** [comment]
It happened while trying to update spyder.

I can’t anymore. I get the message that I’m up to date


Deborah Khider
Postdoctoral Research Scholar
University of Southern California
Los Angeles, CA 90089
khider@usc. edu | (213)-740-2932
earth.usc.edu/~khider<http://earth.usc.edu/~khider>

On Apr 25, 2017, at 2:24 PM, Élie Gouzien <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

This has normally been fixed with spyder 3.1.4.
I suggest you retry and report here what happens.

**Comment by ccordoba12** [comment]
Spyder 3.1.4 was released a couple of days ago. Please run

    pip install -U spyder

again to get its latest version.
