### ISSUE TITLE
[Question] Add new locale

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder#4401]
* Spyder Version: 3.1.3
Hello, I want to translate/add a new locale (Vietnamese) and cannot find any instruction to do that? Could anyone point me to somewhere to start?

Thank you.

**Comment by rlaverde** [comment]
Spyder use .po files for managing translations https://github.com/spyder-ide/spyder/tree/master/spyder/locale

Normally you will use a program like [poedit](https://poedit.net/), for generating po and mo files for the new language.

You also need to add the new language in [spyder/config/base]( https://github.com/spyder-ide/spyder/blob/master/spyder/config/base.py#L229)

**Comment by goanpeca** [comment]
@rlaverde could we take this opportunity to make some instructions with screnshots and a bit of code and links to programs needed?

**Comment by rlaverde** [comment]
> @rlaverde could we take this opportunity to make some instructions with screnshots and a bit of code and links to programs needed?

in the wiki? https://github.com/spyder-ide/spyder/wiki/Contributing-to-Spyder#translating-spyder-gb-fr-es

I see an issue about using https://www.transifex.com/ #2365 could we try it again? I think that It's relevant again because Spyder is getting new translations (Hungarian, Simple Chinese, maybe Vietnamese)

**Comment by goanpeca** [comment]
I dtarted looking at transifex but never got around it... so I dont know. You want to give it try again?

**Comment by goanpeca** [comment]
@rlaverde if you have some time to make a simplified tutorial that would be great, but using transifex is not a priority right now

**Comment by sohnishi** [comment]
@tienhv,
- You should learn common github developping workflow described in https://github.com/spyder-ide/spyder/wiki/Dev%3A-Github-Workflow at first.
- Add your language entry to spyder/config/base as @rlaverde  described.
- Generate po files from locale/*.pot by gettext tools(msginit, msgmerge etc.) in proper directories.
- Edit po files and make mo files by poedit
- comit, push, and pull request

**Comment by ccordoba12** [comment]
Thanks for detailed explanation @sohnishi!!
