### ISSUE TITLE
Spyder didn't update to 3.1.4

### ISSUE THREAD

**Issue by looninho** [spyder-ide/spyder#4402]
## Description of your problem

 i want to upgrade spyder 3.1.3 using conda but it's still in 3.1.3. Commands that i've used:
 - conda update qt pyqt gives:

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Users\me\AppData\Local\Continuum\Anaconda3:

The following packages will be UPDATED:

    conda: 4.3.14-py36_1 --> 4.3.16-py36_0

Proceed ([y]/n)? y

conda-4.3.16-p 100% |###############################| Time: 0:00:00   1.77 MB/s

- and conda update spyder gives: 

Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\me\AppData\Local\Continuum\Anaconda3:
#
spyder                    3.1.3                    py36_0

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.1.3
* Python Version:3.6
* Qt Version:5.6.2
* PyQt Version:5.6.0
* Operating system: windows 10 Professional

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by aliceell** [comment]
I'm having the same problem. I tried the `conda update conda` command and get the same result:

> (C:\Users\aliceell\AppData\Local\Continuum\Anaconda3) C:\Users\aliceell>conda up
> date conda
> Fetching package metadata ...........
> Solving package specifications: .
> 
> # All requested packages already installed.
> # packages in environment at C:\Users\aliceell\AppData\Local\Continuum\Anaconda3
> :
> #
> conda                     4.3.16                   py35_0

Then when I open spyder, it alerts me that Spyder 3.1.4 is available.

Here are my dependencies:
<details>
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
</details>

**Comment by ccordoba12** [comment]
New conda packages are still not available. Please be patient until they are, and *don't* use `pip` to do the update.

Sorry for the inconvenience, hopefully it'll be fixed soon.
