### ISSUE TITLE
IPython console does not report errors

### ISSUE THREAD

**Issue by shekhovt** [spyder-ide/spyder#4405]
## Description of your problem

When running a script containing an error in Ipython console, the execution terminates silently at the error line and does not report error message

**What steps will reproduce the problem?**

1. Connect to an existing kernel running on other machine
2. Run "hallo.py"
```
print('Hello World!')
print(bla)
```
Output:
```
%run "/home.zam/shekhovt/datagrid/mobile_vis/software/python/flow_learning/tests/hallo.py"
Hello World!
```
Expected output:
```
Hello World!
Traceback (most recent call last):
  File "/home.zam/shekhovt/datagrid/mobile_vis/software/python/flow_learning/hallo.py", line 2, in <module>
    print(bla)
NameError: name 'bla' is not defined
```
## Versions and main components

Spyder Version: 3.1.3
Python Version: 2.7.13 64bits
Qt Version: 5.6.2
PyQt Version: 5 5.6
Anaconda 4.3.16
Operating system: Mac OS 10.10.5

##Dependencies

Please go to the menu entry Help > Optional Dependencies (or
Help > Dependencies), press the button Copy to clipboard
and paste the contents below:

jedi =0.9.0 : 0.9.0 (OK)
matplotlib >=1.0 : 2.0.0 (OK)
nbconvert >=4.0 : 4.2.0 (OK)
numpy >=1.7 : 1.11.3 (OK)
pandas >=0.13.1 : 0.19.2 (OK)
pep8 >=0.6 : 1.7.0 (OK)
psutil >=0.3 : 5.0.1 (OK)
pyflakes >=0.5.0 : 1.5.0 (OK)
pygments >=2.0 : 2.1.3 (OK)
pylint >=0.25 : 1.6.4 (OK)
qtconsole >=4.2.0: 4.2.1 (OK)
rope >=0.9.4 : 0.9.4 (OK)
sphinx >=0.6.6 : 1.5.1 (OK)
sympy >=0.7.3 : 1.0 (OK)

**Comment by boeglinw** [comment]
I have the same problem, my workaround so far is to use runfile , e.g. runfile('hallo.py').
