### ISSUE TITLE
Incorrect Auto-Indentation while editing

### ISSUE THREAD

**Issue by lurobi** [spyder-ide/spyder#4408]
## Description of your problem

**What steps will reproduce the problem?**

1.  In any file type the following line:
```python
    something[0] = 0
```
2.  Hit enter

Result:
```
    something[0] = 0
              <--- cursor lands here, as if bracket was not closed
    <--- Expected cursor here
```

In general, use of square brackets before the equal sign seems to throw off the indentation.  Experimentation shows that if the assignment itself contains any of (), [], '', or "" then the indentation works correctly.

I realize I'm not running the latest version of spyder, but I am running Anaconda's latest download version (4.3.1).  I expect this is related to Issues #3700, #3473, #3931 but it wasn't clear to me if these were resolved before 3.1.2 release

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6.0 64bits
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows (x64)

## Dependencies

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This problem was fixed in 3.1.3, please update.
