### ISSUE TITLE
Part of file switcher always outside of screen when full-screen

### ISSUE THREAD

**Issue by GershTri** [spyder-ide/spyder#4411]
## Description of your problem

**What steps will reproduce the problem?**

1. Opening file switcher with shortcut or menu when Spyder in full-screen mode or expanded

**What is the expected output? What do you see instead?**

I expect the entire file switcher window to be visible. Here's a screenshot of what happens:

![image](https://cloud.githubusercontent.com/assets/20071483/25477257/32664e22-2b3d-11e7-8074-6b15d52e39dd.png)

**Please provide any additional information below**
The file switcher window appears to have a more or less fixed position relative to the editor. When I reduce Spyder to half of screen, it looks like this:

![image](https://cloud.githubusercontent.com/assets/20071483/25478158/5060e5f6-2b40-11e7-9efa-55a6b1204d06.png)

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: OS X El Capitan 10.11.16 (Retina)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a very odd bug indeed.

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 3.2.
