### ISSUE TITLE
Switching through editor tabs "random"

### ISSUE THREAD

**Issue by GershTri** [spyder-ide/spyder#4412]
## I've set up shortcuts to switch files/editor tabs with ctrl + alt + arrow keys ("go to next file", "go to previous file"). Sometimes the movement isn't linear, i.e. not tab1 → tab2 → tab3 → tab4 but tab1 → tab3 → tab4 → tab2. Sometimes this seems to happen spontaneously, but more often after I use the two arrow buttons (<>) in the top-right of the editor.

**What steps will reproduce the problem?**

1. Navigate to tab somewhere in the middle, i.e. if t1, t2, t3, t4, t5, then t3.
2. Press an arrow button a couple of times in one direction or the other.
3. Use keyboard shortcuts to move through file tabs.

**What is the expected output? What do you see instead?**
Switching files should occur sequentially, i.e. 1 → 2 → 3 or 3 → 2 → 1.

**Please provide any additional information below**
If I open the file switcher and use the arrow keys to run once through all the files in the file switcher the bug disappears.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: OS X El Capitan 10.11.16 (Retina)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi =0.9.0 : 0.9.0 (OK)
matplotlib >=1.0 : 2.0.0 (OK)
nbconvert >=4.0 : 5.1.1 (OK)
numpy >=1.7 : 1.12.1 (OK)
pandas >=0.13.1 : 0.19.2 (OK)
pep8 >=0.6 : 1.7.0 (OK)
psutil >=0.3 : 5.2.2 (OK)
pyflakes >=0.6.0 : 1.5.0 (OK)
pygments >=2.0 : 2.2.0 (OK)
pylint >=0.25 : 1.6.4 (OK)
qtconsole >=4.2.0: 4.3.0 (OK)
rope >=0.9.4 : 0.9.4-1 (OK)
sphinx >=0.6.6 : 1.5.4 (OK)
sympy >=0.7.3 : 1.0 (OK)

**Comment by goanpeca** [comment]
@rlaverde add new code recently that most likely fixes this behavior. Any additional comments @rlaverde ?

**Comment by rlaverde** [comment]
The actual behavior (spyder 3.14) is a little odd, It iterate the tabs according the order they were last activated

I wrote a fix for this behavior #4302 that will be part of spyder 3.2 (to be released in June), tabs will change using MRU (Most recent used) behavior . Meanwhile you could use `Ctrl+Repag` `Ctrl+AvPag` to change between tabs.
