### ISSUE TITLE
Add dark backgrounds for File and Variable explorers

### ISSUE THREAD

**Issue by negfrequency** [spyder-ide/spyder#4417]
## Description of your problem
I would love it if dark background options were added to file explorer and var explorer, mostly to make it look identical to my matlab ide.

**What steps will reproduce the problem?**
1. add dark option to file explorer 
2. add dark option to var explorer
3. 

**What is the expected output? What do you see instead?**
A dark background with white foreground text, similar to the the Ipython dark background

**Please provide any additional information below**
I love you guys! keep up the good work

## Versions and main components

* Spyder Version: 3.14
* Python Version: 3.3
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

## Dependencies
None
Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. We will work on this for Spyder 4.

**Comment by ccordoba12** [comment]
This is (essentially) a duplicate of issue #2350.
