### ISSUE TITLE
No option for dedicated IPython console

### ISSUE THREAD

**Issue by Eric89GXL** [spyder-ide/spyder#4418]
Upon hearing about the pending removal of the Python console option, I looked into migrating my workflow to IPython. However, my workflow currently involves using the "Execute in a new dedicated Python console" option. There is no equivalent for IPython.

There is the "clear all variables" IPython option, but this is not equivalent. In my current workflow, I could have, say, 5 scripts open, select each one and hit F5, and it would create a new console for each. I don't see a way to do this with IPython, other than opening 5 new windows, selecting each one in sequence while selecting my script, and hitting F5. This is inferior for rapidly iterating over code, because you need to e.g. keep track of which window belongs to which script, etc., which Spyder does automatically for the dedicated Python case.

I guess this could be solved simply by adding a "Execute in a new dedicated IPython console" option, alongside a "Dedicated IPython console" sub-list. Should this be done?

**Comment by Eric89GXL** [comment]
It looks like this issue/solution idea has been brought up before (https://github.com/spyder-ide/spyder/issues/3533#issuecomment-254102248), so perhaps it just needs to be done?

**Comment by ccordoba12** [comment]
Thanks for reporting @Eric89GXL. Although our plans for 3.2 are not referenced in our Issue tracker (because it's too noisy), we do plan to implement this feature to have feature parity between the two consoles before removing the Python one.

**Comment by ccordoba12** [comment]
@andfoy, please start working on this one.

**Comment by Eric89GXL** [comment]
Okay great, thanks @ccordoba12
