### ISSUE TITLE
Can't view full Python package help documentation

### ISSUE THREAD

**Issue by VikrantDogra** [spyder-ide/spyder#4419]
## Description of your problem
Can't view full Python package help documentation when using Python 3.6.0 on Spyder 3.1.2 in Ananconda 4.3.0 (64-bit). Issue in both IPython Console & Python Console.

**What steps will reproduce the problem?**

1. Launch Spyder 3.1.2 in Ananconda 4.3.0 (64-bit) in a Windows Machine (Windows 8.1 Pro)
2. import matplotlib
3. help(matplotlib)

**What is the expected output? What do you see instead?**
Expected output: View full help documentation on matplotlib.
Actual output: See incomplete documentation. Initial part of documentation cut-off. Happens for packages which have long detailed documentation.

**Please provide any additional information below**
![help matplotlib issue-displaying from where the help doc is visible](https://cloud.githubusercontent.com/assets/19929442/25605539/20ed581c-2f29-11e7-9a35-437b8455b85e.png)

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6.0
* Qt Version:
* PyQt Version:
* Operating system: Windows 8.1 Pro
* Anaconda Version: 4.3.0 (64-bit)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
If the documentation takes more than 500 lines, it'll be cut off because our consoles only allow 500 lines to be present at any time. That limit can be modified in

    Preferences > IPython console > Source code

but you need to be careful because that also affects the efficiency of the console (if you want to print too much text to the console, that could block Spyder).

Of course, you can also use our Help pane to read help, by pressing `Ctrl+I` after any object in the console, like this:

    In [1]: import matplotlib
    In [2]: matplotlib<Ctrl+I>

**Comment by VikrantDogra** [comment]
Hi,
Why not display help the way it happens in Windows Command Prompt i.e. read
page-by-page; press tab to view next page?


Regards,
Vikrant

**Comment by VikrantDogra** [comment]
Why not display help the way it happens in Windows Command Prompt i.e. read
page-by-page; press tab to view next page?

**Comment by fredrik-1** [comment]
Is it possible to get a pager that only show one page at a time in spyder after writing help(obj)? In the same way as it is in python and standard IPython? 

I have tried to set the pager option in IPython to true but, I don't see any difference.  Should that feature still work?

I don't like the  (default or only?) help behaviors in spyder, ctrl+I don't always show anything at all and often just the main docstring of an object, obj? don't show enough for many objects and help(obj) show the last part and you need to scroll a long way to see the first part in a long docstrings (if it is even there). 

Are there any good why to show the full matplotlib axes docstring in spyder?
