### ISSUE TITLE
Crashes after updating to 3.1.4

### ISSUE THREAD

**Issue by webcsm** [spyder-ide/spyder#4422]
## Description of your problem

**What steps will reproduce the problem?**

1. Close preferences dialog
2. Close about dialog

**What is the expected output? What do you see instead?**
The windows should close. Instead I get a crash.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.3
* Qt Version: 4.8.7
* PyQt Version: 4.11.4
* Operating system: Win7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by ccordoba12** [comment]
Although we try to support Qt4/PyQt4, it's really deprecated by the Qt project and no new releases are going to be made for it.

So we recommend you to use Qt5/PyQt5 instead.
