### ISSUE TITLE
Missing manpage for spyder

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/spyder#4423]
Please consider enhancing the documentation to include the generation of a suitable manpage for `spyder`. The GNU guidelines and most Linux distributions highly recommend command-line tools be distributed with corresponding manpages. The [Debian policy](https://www.debian.org/doc/debian-policy/ch-docs.html#s12.1) considers the lack of a manpage a bug.

Thanks,

**Comment by ccordoba12** [comment]
Man pages are mainly for command line applications, and Spyder is not one of those.

So we'll gladly accept PRs for this, but we don't have time to work on this one, sorry.

**Comment by ghisvail** [comment]
> Man pages are mainly for command line applications

FYI, all GNOME applications (nautilus, evince, totem...) have corresponding manpages with the following structure:
```
NAME
SYNOPSIS
DESCRIPTION
OPTIONS
BUGS
AUTHORS
```

**Comment by ccordoba12** [comment]
I'm not saying we don't want to do this, I'm just saying the gain is really minimal and we don't have time to do it.

Of course, we're welcome to receive a PR for it.
