### ISSUE TITLE
Use setup.cfg or pytest.ini instead of runtest.py

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4424]
The way how spyder tests are executed is a little non-standard

`runtest.py` file could be replaced for a configuration in `setup.cfg` or `pytest.ini`:

`addopts =-x -v -rw --durations=10 --cov=spyder_reports --cov-report=term-missing`

and tests will be executed using:
`$ pytest`
or ` $pytest spyder`

I didn't found a reason to use `runtest.py` file, and using `setup.cfg` or `pytest.ini` is more standard

**Comment by goanpeca** [comment]
@ccordoba12 what do you think? Its not priority but we could standarize among projects (plugins etc..) which is what I think @rlaverde is aiming for

**Comment by jitseniesen** [comment]
As I remember (but this may be out of date), `runtest.py` sets an environment variable which cause some modal dialog boxes to close automatically after a certain time. Without it the tests hang.

If we can execute the tests by simply running `pytest`, as suggested, then the unittest plugin can be used to run Spyder's tests, which would be nice (eat your own dog food). Another advantage of using `pytest` is that you can use options to (for instance) select which tests to run. So I would like it if we could switch to running `pytest`.

**Comment by rlaverde** [comment]
> Its not priority but we could standarize among projects (plugins etc..) which is what I think @rlaverde is aiming for

Yes, I noticed this while developing the plugins template (spyder-cookiecutter-plugin)

> As I remember (but this may be out of date), runtest.py sets an environment variable which cause some modal dialog boxes to close automatically after a certain time. Without it the tests hang

I didn't notice [that](https://github.com/spyder-ide/spyder/blob/master/runtests.py#L20), the variable is used to skip the splash and the opening of some files, but It could be replaced for a hack in `conftest.py` as explained in [pytest docs](https://docs.pytest.org/en/latest/example/simple.html#detect-if-running-from-within-a-pytest-run)

**Comment by ccordoba12** [comment]
`SPYDER_PYTEST` defines a `PYTEST` variable, which I'm using to avoid running the event loop of the main window, because pytest-qt provides its own loop. It also adjusts other things for pytest, as can been seen with a simple `ack/ag PYTEST`.

There's also this

https://github.com/spyder-ide/spyder/blob/master/runtests.py#L34-L35

which correctly generates an error when tests fail, and this

https://github.com/spyder-ide/spyder/blob/master/runtests.py#L15

which allows our tests to run correctly in Qt4.

----

@rlaverde, you could give it a try, but if you commit to this, you have to fix all bugs that come after the change. I don't want to put more of my time to something that I've worked really hard to make it work almost flawlessly.

**Comment by goanpeca** [comment]
I would say this is not a priority and tweaking CI systems takes a lot of time! so... I would say your time is better invested elsewhere

**Comment by rlaverde** [comment]
> SPYDER_PYTEST defines a PYTEST variable, which I'm using to avoid running the event loop of the main window, because pytest-qt provides its own loop. It also adjusts other things for pytest, as can been seen with a simple ack/ag PYTEST.
> 
> There's also this
> 
> https://github.com/spyder-ide/spyder/blob/master/runtests.py#L34-L35
> 
> which correctly generates an error when tests fail, and this
> 
> https://github.com/spyder-ide/spyder/blob/master/runtests.py#L15
> 
> which allows our tests to run correctly in Qt4.

This things could be moved to the `conftest.py`

> you could give it a try, but if you commit to this, you have to fix all bugs that come after the change. I don't want to put more of my time to something that I've worked really hard to make it work almost flawlessly.

I don't think this will cause too much trouble, It's moving the work in `runtest.py` to the standard pytest way; but as @goanpeca says this is not a priority so I won't work in this soon (although I'll use the pytest way in the reports plugin).

**Comment by ccordoba12** [comment]
> I don't think this will cause too much trouble

Last famous words ;-)

**Comment by ccordoba12** [comment]
I think we're too invested in `runtests.py` to switch to something else.
