### ISSUE TITLE
Information regarding how to fix the crushing problem if someone accidentally install PyQt4 and PyQt5 at the same environment

### ISSUE THREAD

**Issue by wliu2016** [spyder-ide/spyder#4427]
## Description of your problem
Anaconda3 comes with PyQt4, while Spyder prefers PyQt5.  If someone accidentally, install PyQt4 and PyQt5 in the same environment,  such as me, Spyder is not working properly in Windows 10.  Spyder.exe is not responding and other tools like matplotlib is not working either.  Even uninstall the package could not solve this problem.  

**What steps will reproduce the problem?**
Warning: do not try it unless you know how to fix it.
1. Download and install Anaconda3 installer for Python 3.5 and above;
2. `Pip install pyqt5` in cmd.exe.
3. The Spyder is not working and responding.

**What is the expected output? What do you see instead?**
Python will crush.  The Windows will pop-out a wizard saying Python is not working and need to debug or close the program.  

**Please provide any additional information below**
After googling and searching the issues, the problem is caused as PyQt4 and PyQt5 do not like stay in the same environment.  Even if uninstalling one of them, the Spyder is still not responding due to lack of Qt bindings.  And pip install pyqt5 will not install Qt bindings for Spyder.

To solve this problem, the simple and easiest way is to use conda install pyqt.  

`conda install pyqt`

Hope it helps. 

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.2
* Qt Version: 5.6.2
* PyQt Version: PyQt5
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> Anaconda3 comes with PyQt4, while Spyder prefers PyQt5

That's not true, Spyder can still work with PyQt4.

> pip install pyqt5

This is a recipe for disaster, unless you're an expert and really know what you're doing.

> After googling and searching the issues, the problem is caused as PyQt4 and PyQt5 do not like stay in the same environment

Well, they can't be installed in the same environment if you are using only conda packages. And, as I said above, mixing pip and conda packages must be done with extreme care and deep knowledge of the scientific Python stack.

> To solve this problem, the simple and easiest way is to use conda install pyqt.
>
> conda install pyqt
>
> Hope it helps.

Yep, this helps. But there's nothing we can do in Spyder to prevent users to install pip packages in their Anaconda installation Sorry.

However, I'm glad you were able to fix this problem.

**Comment by wliu2016** [comment]
Lol, I am not an expert. Just made a silly mistake and hope this information can help others.
