### ISSUE TITLE
ImportError: No module named 'bs4'

### ISSUE THREAD

**Issue by xinluwang** [spyder-ide/spyder#4429]
## Description

**What steps will reproduce the problem?**

1.  import bs4 
2. ImportError: No module named 'bs4'
3. Actually, I can import bs4 in terminal ipython but not in Spyder 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.2 
* Python Version: 3.5.2
* Qt Versions: 5.7.0, PyQt5 5.7 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
rope >=0.9.4     :  0.10.3 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
psutil >=0.3     :  5.0.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by andfoy** [comment]
If you are trying to load BeautifulSoup then it should be done as it follows:
```python
from BeautifulSoup import bs4
```

**Comment by xinluwang** [comment]
THE PROBLEM is : I can import bs4  in terminal or other IDE, like Rodeo,  but not in Spyder

**Comment by andfoy** [comment]
Is this your error?
```python
Traceback (most recent call last):

  File "<ipython-input-1-2ab5f7ff4a9e>", line 1, in <module>
    import bs4

  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup

  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 311, in <module>
    from . import _htmlparser

ImportError: cannot import name _htmlparser
```

**Comment by andfoy** [comment]
Try to install ipython-beautifulsoup: 
```
pip install "ipython-beautifulsoup[bs4]"
```

**Comment by andfoy** [comment]
This error is unrelated to Spyder
