### ISSUE TITLE
Suppressing editor code from being flashed into console on execution

### ISSUE THREAD

**Issue by norrrbit** [spyder-ide/spyder#4430]
## Description of your problem
It would be convenient that all the code executed from editor not be echoed by console, so only results would appear in the output. 

**Please provide any additional information below**
That is how PyScripter works, so I think it is doable.

## Versions and main components

* Spyder Version: 3.0.0
* Python Version: 3.5
* Qt Version:
* PyQt Version:
* Operating system: Win 7

**Comment by ccordoba12** [comment]
We have discussed this before and decided not to do it because very few people have asked for this option.

If more people ask for this, we will revisit our decision. For now, I'm afraid we're going to leave things as they are, sorry.

**Comment by norrrbit** [comment]
That's OK. Anyway thank you Carlos for Spyder very much! Great job!

**Comment by ccordoba12** [comment]
Thanks for understanding! ;-)
