### ISSUE TITLE
Cannot install IPython and zmq

### ISSUE THREAD

**Issue by hawkeagle123** [spyder-ide/spyder#4433]
## Description of your problem
I install Anaconda with Spyder.
I only can see python consolde instead of IPython console in Spyder.

I tried 

> pip install pyzmq

and I get

> You are using pip version 7.0.3+xy.11, however version 9.0.1 is available.
> You should consider upgrading via the 'python -m pip install --upgrade pip' command.
> Requirement already satisfied (use --upgrade to upgrade): pyzmq in C:\Users\XXX

I also tried

> conda update ipython

and get

> Fetching package metadata ...........
> Solving package specifications: .
> 
>  All requested packages already installed.
>  packages in environment at C:\Users\XXX\Anaconda2:
> 
> ipython                   5.3.0                    py27_0

## Versions and main components

* Spyder Version:2.3.5.2
* Python Version: 2.7.13
* Qt Version:5.6.2
* PyQt Version:5.6.0
* Operating system:Windows 10

## Dependencies

My optional dependences in Spyder:
IPython >=1.0   :  None (NOK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
zmq >=2.1.11    :  None (NOK)

**Comment by ccordoba12** [comment]
You need to run

    conda install qtconsole

to get the IPython console in Spyder.
