### ISSUE TITLE
User filelock vendored module

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4439]
Hi @ccordoba12 I started using https://github.com/benediktschmitt/py-filelock and seems to be a nice alternative to what we currently have as it is supported outside from this team.

Worth taking a look, and we can still vendor it as it is a single file name, would you like me to make a PR?

**Comment by ccordoba12** [comment]
I think what we have now is working pretty well, actually (specially after PR #3659).

I took a quick look at py-filelock yesterday and didn't find anything similar to our use of `psutil`. Given that this is critical for Spyder, I'm -1 on touching it.
