### ISSUE TITLE
Add GUI autoupdater package for spyder

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4440]
I have code ready to have an autoupdate mechanism ready to be used (for conda), but it needs to be a separate package (`spyder-updater` ?) as spyder cannot update itself while running due to errors on the linking step.

In the current workflow we would add an open updater, in the message dialog on startup that would open this new package and it would take it from there. Would make updating much easier for users of anaconda.

**Comment by ccordoba12** [comment]
Seems interesting. Let's wait a little bit to see how this works for Navigator, and then we could go for it.

**Comment by ccordoba12** [comment]
Closing for now, we can take a look at this in the future.
