### ISSUE TITLE
One-off error with home key in IPython console

### ISSUE THREAD

**Issue by kohr-h** [spyder-ide/spyder#4441]
With Spyder 3.1.4 and IPython 6.0, the home key moves the cursor to the second position instead of the first. A second press of the home button then moves to the first position.

This happens only on single-line input, not when the line is continued. It may be an upstream issue, but it doesn't happen in the raw IPython console on the terminal and not in a Jupyter notebook either.

**Comment by ccordoba12** [comment]
What's your operating system and your Python/Qt/PyQt versions?

**Comment by kohr-h** [comment]
Ah, sorry that I forgot this information.

OS: Linux
Python: 3.6
Qt: 5.6.2
PyQt: 5.6.0

**Comment by ccordoba12** [comment]
I think this is an upstream bug, but since we're also maintaining `qtconsole`, we'll take a look at it.

**Comment by kohr-h** [comment]
Cool, thanks for the quick answer. Awesome work BTW!

**Comment by kohr-h** [comment]
And just for completeness, my `qtconsole` version is 4.3.0.

**Comment by kohr-h** [comment]
I just tested `qtconsole` version 4.2.1, and indeed, the issue is not present there.

**Comment by dhirschfeld** [comment]
I'm also seeing this!

**Comment by SebastianSchafer** [comment]
Hi,
I don't know if you already identified the issue? Anyway, I noticed it today when updating spyder from 3.1.4 (was fine) to 3.2.0. The only changes were an update of qt (don't know the old version) and install of qtconsole. Maybe this additional info helps.
Current config:
OS: Win7
Py 3.6.1 64bit
IPython 5.3.0
qtcsonsole 4.3.0
spyder 3.2.0

**Comment by ccordoba12** [comment]
This is a problem in qtconsole.

**Comment by dhirschfeld** [comment]
Is this the underlying qtconsole bug - jupyter/qtconsole#207?

**Comment by ccordoba12** [comment]
Yep, I think so. We keep it open here so we don't forget to address it in the future.

**Comment by ccordoba12** [comment]
Closing this one because it's well referenced in qtconsole.

**Comment by William96911** [comment]
This issue has not been resolved in Spyder 3.3.0
OS: Win 10
Python: 3.6.6 64bits
Qt: 5.9.3
PyQt5: 5.9.2
