### ISSUE TITLE
Segfault when closing with temporary file open

### ISSUE THREAD

**Issue by kohr-h** [spyder-ide/spyder#4442]
When the last file to be closed upon shutting down Spyder is a temporary scratch space, and when one answers "No" to the question if the file should be saved, Spyder segfaults.

It doesn't happen before, for example when two scratch spaces are open and one is closed without saving, all is good. Also when the last file is saved to disk, there's no segfault.

Spyder: 3.1.4
Python: 3.6
OS: Linux
Python: 3.6
Qt: 5.6.2
PyQt: 5.6.0

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by ccordoba12** [comment]
@dalthviz, please forget about this one.

@rlaverde, please take a look at this one.

**Comment by rlaverde** [comment]
@ccordoba12 after some debugging I found the error, this [line](https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py#L2138) call the previous focus widget that is one of the buttons of the QMessage asking if file should be saved, then isAncestor raises the Segfault when trying to acces to it 

I don't know how It's the best way to solve this

**Comment by goanpeca** [comment]
@rlaverde why dont we return the focus back to whatever makes sense with that QMEssageBox?
