### ISSUE TITLE
After conda update spyder,spyder failed to start

### ISSUE THREAD

**Issue by YISION** [spyder-ide/spyder#4445]
## Description of your problem
After conda update qt pyqt,conda update spyder, I failed to start spyder, and reported " qtpy.PythonQtError: No Qt bindings could be found "

I use conda list to see whether if qt and pyqt was installed，they were in the list. I tried to  import pyqt
in the ipython console, but there reported "no module pyqt"

**What steps will reproduce the problem?**

1. conda update qt pyqt
2. conda update spyder
3. start spyder ide

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: anaconda，python2.7
* pyqt Version:5.6.0
* qt Version: 5.6.2

**Comment by ccordoba12** [comment]
Please post the result of this command

    conda list

**Comment by ccordoba12** [comment]
Closing because of lack of response.
