### ISSUE TITLE
IPython consoles not working

### ISSUE THREAD

**Issue by mgabriell1** [spyder-ide/spyder#4447]
## Description

**What steps will reproduce the problem?**

1. Start spyder
2. Looking at the IPython console or opening a new one
3. 

**What is the expected output? What do you see instead?**
An IPython console should be present.
Instead the console is named "Kernel1" and this message is present

    NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

    To exit, you will have to explicitly quit this process, by either sending "quit" from a client, or using Ctrl-\ in UNIX-like environments.

    To read more about this, see https://github.com/ipython/ipython/issues/2049

    To connect another client to this kernel, use:
    --existing kernel-9324.json

**Please provide any additional information below**
Ipython console works on its own

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.5.2
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.5.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1 (OK)
IPython >=1.0      :  2.4.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.6 (OK)
psutil >=0.3       :  5.2.2 (OK)
rope >=0.9.2       :  0.10.5 (OK)
jedi >=0.8.1;<0.9.0:  0.10.2 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Spyder 2.3 is no longer maintained, sorry. Please update to Spyder 3.1.4 and try again.
