### ISSUE TITLE
F9 changes focus to the console

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#4450]
With a recent git spyder pressing F9 in the editor changes the focus to the console so you can't keep pressing F9 to execute futher lines without clicking back on the editor.

I would like F9 to not change focus to the console.

![image](https://cloud.githubusercontent.com/assets/881019/25883807/e12fe62c-3590-11e7-96a9-4152ac4f75ed.png)
```
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  None (NOK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
@rlaverde, please take a look at this one.

**Comment by rlaverde** [comment]
I'm not able to reproduce this bug

**Comment by ccordoba12** [comment]
@dalthviz, please test this problem on Windows, and if it's there, solve it.

**Comment by dhirschfeld** [comment]
FWIW, I've nuked my old python install and am now running on a freshly installed Anaconda/py36 with an updated spyder and I don't see the problem. F9 correctly keeps focus in the editor, allowing you to keep pressing to execute consecutive lines.
![image](https://user-images.githubusercontent.com/881019/27362318-f462e072-5670-11e7-8a41-6754c6d3daf0.png)

Happy for this to be closed.

**Comment by ccordoba12** [comment]
Great!! One thing less to work on for Spyder 3.2 ;-)

**Comment by taiwanbloke** [comment]
I am seeing this problem with 3.3.3 on Win 7 x64, Python 3.7 and I'm able to reproduce it reliably when the editor is not docked (with IPython console docked).

Behavior when editor is docked: Pressing F9 executes line, focus stays in editor.

Behavior when editor is its own window: Pressing F9 executes line, focus switches to console.

**Comment by MarioVillar** [comment]
Hi, I am facing the same problem in spyder 5.3.2. from Anaconda.

When using base environment, there is no such problem, but when creating a new one or even cloning the base env it appears. Once a file is executed and the _Maximize Current Pane_ button is clicked to maximize the Plots window, then pressing F9 does execute current line but also maximizes the console.

I attach the env where it can be reproduced but, as I am saying, the bug appears in every other env I have tested.

[environment.zip](https://github.com/spyder-ide/spyder/files/10335082/environment.zip)

**Comment by MarioVillar** [comment]
Hi again.

Sorry for my late answer, but I have been pretty busy these days. Thanks for the advice regarding conda environments.

Following it, I was actually able to replicate my previous environment but just using conda package manager and there seems to be no such bug as I was reporting previously. Everything fine then.

Thanks for your time!!

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
