### ISSUE TITLE
Add more annotation keywords to the Editor (e.g. BUG, OPTIMIZE, etc)

### ISSUE THREAD

**Issue by cvanwynsberghe** [spyder-ide/spyder#4452]
Code annotation analysis makes a blue check sign in the editor, which is a useful feature to find TODOs or FIXMEs.

But could it add more words? On the net, and more importantly in [pep8 index](https://www.python.org/dev/peps/pep-0350/#mnemonics), we can find many other tags, eg BUG, HACK, OPTIMIZE, etc.

**Comment by ccordoba12** [comment]
We don't have time to do this, but you're welcome to send us a pull request to add more annotation keywords.
