### ISSUE TITLE
Recommend to use one shortcut (Ctrl+I) for inspect current object

### ISSUE THREAD

**Issue by andrew0056** [spyder-ide/spyder#4458]
Ctrl+I is nice shortcut for invoking the help doc of the function when needed. If I want to change Ctrl+I to Ctrl+Tab, I am not able to change to it both in console & editor. Recommend to use one shortcut (Ctrl+I) for inspect current object

   FYI, I felt Ctrl+Tab is more convenient for one hand operation.

**Comment by ccordoba12** [comment]
You need to change the shortcut separately for the Editor and the consoles. There are entries for each one in

    Preferences > Keyboard shortcuts
