### ISSUE TITLE
missing dependency chardet and pycodestyle

### ISSUE THREAD

**Issue by chrisgee** [spyder-ide/spyder#4460]
## Description of your problem

**What steps will reproduce the problem?**

1. run python setup.py install
2. run spyder
3. program exits with error

**What is the expected output? What do you see instead?**
  File "...../spyder/utils/encoding.py", line 20, in <module>
    from chardet.universaldetector import UniversalDetector
ImportError: No module named chardet.universaldetector

**Please provide any additional information below**
to fix run 

pip install chardet

also after startup I see a message that package pycodestyle is missing.

## Versions and main components
spyder git master (d20428afe7b0dc76b004cb3075f08e76538337e2 [d20428a])

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
If you run

    python setup.py install

you have to install *by hand* all Spyder dependencies (as listed in our Readme), not just chardet and pycodestyle. So this method is recommended only for experts

A much simpler way to install Spyder is to run

    pip install -U spyder

which pulls and installs all our dependencies with that single command.
