### ISSUE TITLE
Spyder runs wrong script

### ISSUE THREAD

**Issue by majklstajpl** [spyder-ide/spyder#4461]
## Description

**What steps will reproduce the problem?**

1. Open script1.py, run it, get graph, close it
2. Open script2.py, run it
3. 

**What is the expected output? What do you see instead?**
Instead of getting figures, that are produced from script2.py, I get figures from script1.py, even though it is closed. The figures don't even save.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
That's because you're using the same console to run both scripts, I think.

You can avoid this by going to the menu

    Preferences > Run > General Settings

and activate the option called

    Clear all variables before execution (IPython consoles)
