### ISSUE TITLE
Code folding does not work on indentation level 0

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#4463]
AFAIU code folding works on indentation.
Recently I cannot fold anymore "def" and "class", ie all stuff without indentation (ie level 0).
Then in function, "for"  or in class "def method", it works fine.
AFAIR it used to work a few weeks ago.
By the way thanks a lot for this great addition.

**Comment by rlaverde** [comment]
> AFAIU code folding works on indentation.

Yes, This have to be improve #4432 

> Recently I cannot fold anymore "def" and "class", ie all stuff without indentation (ie level 0).

This is working for me with the latest `master`, could you give me an example to reproduce this bug?

**Comment by sylvain-bougnoux** [comment]
Hum, as I had launch issues I did several spyder reset. It down on me, that indentation default (4 spaces) was previously set to my preference (2 spaces & tab width=2 spaces).
Therefore I change them back, within advanced option of preference/editor, and restart IDE. *Now code folding works*. If I put back to 4 it does not. Hence you should be able to reproduce the bug tweaking these options.
 
I don’t if it is truly the reason, but definitely it should work on any code, not only the one compatible with your preference (obviously J).
 
Once again thanks a lot.

**Comment by rlaverde** [comment]
I see, the issue is that fold levels were calculated with the previous indentation, and the blocks edited after the change will have a fold level calculated with a different indentation value

I think we could solve this is making indentation levels independent of config preference (indent_chars), using a "heuristic" (the first indentation in the file) to calculate fold levels instead.

@ccordoba12 @goanpeca what do you think?

**Comment by ccordoba12** [comment]
@rlaverde, so the problem lies on using different indentation levels on the same file?

**Comment by rlaverde** [comment]
> so the problem lies on using different indentation levels in the same file?

When start editing a file, then change the configuration to a different indent_chars, and continue editing, the block information about fold level is updated when editing the block(line)

Also different indentation_chars in a file will broke the folding (mixing tabs and spaces, or some lines 4-spaces and others 3-spaces), the FoldDetector expects all indents to be multiply of indent_chars

**Comment by ccordoba12** [comment]
Ok, then your proposed solution sounds good. Please start implementing it.

**Comment by sylvain-bougnoux** [comment]
> I think we could solve this is making indentation levels independent of config preference (indent_chars), using a "heuristic" (the first indentation in the file) to calculate fold levels instead. 
Why do you want to depend on “first indentation”, then what if the indentation style change (e.g. from copying a code). Maybe you can simply detect blocks, by change in indentation between current and previous line (starting with a -1 indentation for the -1 line). Therefore you don’t rely on anything. That’s python philosophy. Just my 2c.
