### ISSUE TITLE
Spyder Start Up Error

### ISSUE THREAD

**Issue by herleeyandi** [spyder-ide/spyder#4467]
Hello last time I use spyder and it really help me a lot, thanks for the great works. However I didn't know why, spyder can not start even I call from start or terminal in Ubuntu. I figuring out the error and I found that this is because the lock file. So simply I go to spyder file and change line in `start_app.py` file and change `spyder.lock` to `spider2.lock` then it works well. But new problem coming that the console whether in terminal or IPython producing error `cannot import name hashtable`. It always appear when doing print function or program output. After that back to the original I change `spider2.lock` to `spyder.lock` it works but the error is still.
Here is the eror:
![image](https://cloud.githubusercontent.com/assets/2309538/26028442/ff0f2062-3852-11e7-8b97-8d1e274ac6d9.png)
![image](https://cloud.githubusercontent.com/assets/2309538/26028445/19340ff2-3853-11e7-9bd4-00fc2eced7d0.png)
Anybody can help?
-Thank you-

**Comment by ccordoba12** [comment]
I'm sorry but I don't what's causing this. How did you install Spyder?

**Comment by herleeyandi** [comment]
Sorry for the late reply. I think this happen when I try jupyter notebook, then have an error about pandas in there. Then I close the jupyter and running spyder and have the error. Simply I just reinstall the Pandas and its works.
