### ISSUE TITLE
Spyder fail to launch after update.

### ISSUE THREAD

**Issue by nirvana1122** [spyder-ide/spyder#4468]
## Description of your problem

Hi, I am getting following error when I try to launch Spyder.

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\requirements.py", line 39, in check_qt
    import qtpy
ImportError: No module named 'qtpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\spyder-script.py", line 5, in <module>
    sys.exit(spyder.app.start.main())
  File "C:\Anaconda3\lib\site-packages\spyder\app\start.py", line 103, in main
    from spyder.app import mainwindow
  File "C:\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "C:\Anaconda3\lib\site-packages\spyder\requirements.py", line 53, in check_qt
    % (qt_infos['pyqt5'] + qt_infos['pyqt']))
  File "C:\Anaconda3\lib\site-packages\spyder\requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Failed to import qtpy.
Please check Spyder installation requirements:

qtpy 1.1.0+ and either
PyQt5 5.2+ or
PyQt4 4.6+

are required to run Spyder.

**Please provide any additional information below**

List of installed packages is 

# packages in environment at C:\Anaconda3:
#
_license                  1.1                      py35_1  
_nb_ext_conf              0.3.0                    py35_0  
alabaster                 0.7.10                   py35_0  
anaconda                  custom                   py35_0  
anaconda-clean            1.1.0                    py35_0  
anaconda-client           1.6.3                    py35_0  
anaconda-navigator        1.5.2                    py35_0  
anaconda-project          0.4.1                    py35_0  
argcomplete               1.0.0                    py35_1  
astroid                   1.4.9                    py35_0  
astropy                   1.3.2               np111py35_0  
babel                     2.4.0                    py35_0  
backports                 1.0                py35_intel_6  [intel]  intel
bdateutil                 0.1                       <pip>
beautifulsoup4            4.6.0                    py35_0  
bitarray                  0.8.1                    py35_1  
blaze                     0.10.1                   py35_0  
bleach                    1.5.0              py35_intel_0  [intel]  intel
bokeh                     0.12.5                   py35_0  
boto                      2.46.1                   py35_0  
bottleneck                1.2.0               np111py35_0  
bzip2                     1.0.6             vc14_intel_10  [intel vc14]  intel
cffi                      1.9.1              py35_intel_1  [intel]  intel
chardet                   3.0.2                    py35_0  
chest                     0.2.3                    py35_0  
click                     6.7                      py35_0  
cloudpickle               0.2.2                    py35_0  
clyent                    1.2.2                    py35_0  
colorama                  0.3.7              py35_intel_5  [intel]  intel
comtypes                  1.1.2                    py35_0  
conda                     4.3.17                   py35_0  
conda-build               2.1.13                   py35_0  
conda-env                 2.6.0                         0  
conda-manager             0.4.0                    py35_0  
conda-verify              2.0.0                    py35_0  
configobj                 5.0.6                    py35_0  
console_shortcut          0.1.1                    py35_1  
contextlib2               0.5.4                    py35_0  
cryptography              1.7.1                    py35_0  
curl                      7.52.1                   vc14_0  [vc14]
cycler                    0.10.0             py35_intel_5  [intel]  intel
cython                    0.25.2             py35_intel_4  [intel]  intel
cytoolz                   0.8.2                    py35_0  
dask                      0.14.3                   py35_0  
datashape                 0.5.4                    py35_0  
datefinder                0.6.1                     <pip>
decorator                 4.0.11             py35_intel_0  [intel]  intel
dill                      0.2.6                    py35_0  
docutils                  0.13.1                   py35_0  
dynd-python               0.7.2                    py35_0  
entrypoints               0.2.2              py35_intel_2  [intel]  intel
ephem                     3.7.6.0                   <pip>
et_xmlfile                1.0.1                    py35_0  
fastcache                 1.0.2                    py35_1  
filelock                  2.0.7                    py35_0  
flask                     0.12.1                   py35_0  
flask-cors                3.0.2                    py35_0  
freetype                  2.5.5                    vc14_2  [vc14]
get_terminal_size         1.0.0              py35_intel_5  [intel]  intel
gevent                    1.2.1                    py35_0  
greenlet                  0.4.12                   py35_0  
h5py                      2.6.0               np111py35_1  
hdf5                      1.8.16            vc14_intel_17  [intel vc14]  intel
heapdict                  1.0.0                    py35_1  
hiredis                   0.2.0                     <pip>
holidays                  0.8.1                     <pip>
html5lib                  0.999              py35_intel_0  [intel]  intel
httplib2                  0.9                       <pip>
IbPy                      0                         <pip>
IbPy2                     0.8.0                     <pip>
icc_rt                    16.0.3                  intel_6  [intel]  intel
icu                       57.1                     vc14_0  [vc14]
idna                      2.2                      py35_0  
imagesize                 0.7.1                    py35_0  
influxdb                  4.0.0                     <pip>
intelpython               2017.0.3                      4    intel
ipykernel                 4.5.0              py35_intel_9  [intel]  intel
ipyparallel               6.0.2                     <pip>
ipython                   5.3.0              py35_intel_0  [intel]  intel
ipython_genutils          0.2.0              py35_intel_0  [intel]  intel
ipywidgets                6.0.0              py35_intel_0  [intel]  intel
isort                     4.2.5                    py35_0  
itsdangerous              0.24                     py35_0  
japanese-holiday          0.0.4                     <pip>
jdcal                     1.3                      py35_0  
jedi                      0.10.2                   py35_0  
jinja2                    2.9.5              py35_intel_3  [intel]  intel
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.5.1              py35_intel_5  [intel]  intel
jupyter                   1.0.0              py35_intel_5  [intel]  intel
jupyter_client            5.0.0              py35_intel_1  [intel]  intel
jupyter_console           5.1.0              py35_intel_0  [intel]  intel
jupyter_core              4.3.0              py35_intel_0  [intel]  intel
Keras                     2.0.3                     <pip>
Lasagne                   0.2.dev1                  <pip>
lazy-object-proxy         1.2.2                    py35_0  
libdynd                   0.7.2                         0  
libgpuarray               0.6.4                    vc14_0  [vc14]
libpng                    1.6.28            vc14_intel_10  [intel vc14]  intel
libpython                 2.0                      py35_0  
libsodium                 1.0.3                         0  
libtiff                   4.0.6                    vc14_3  [vc14]
llvmlite                  0.17.0             py35_intel_2  [intel]  intel
locket                    0.2.0                    py35_1  
lunardate                 0.1.5                     <pip>
lxml                      3.7.3                    py35_0  
m2-msys2-runtime          2.5.0.17080.65c939c               3  
m2-patch                  2.7.5                         2  
m2w64-binutils            2.25.1                        5  
m2w64-bzip2               1.0.6                         6  
m2w64-crt-git             5.0.0.4636.2595836               2  
m2w64-gcc                 5.3.0                         6  
m2w64-gcc-ada             5.3.0                         6  
m2w64-gcc-fortran         5.3.0                         6  
m2w64-gcc-libgfortran     5.3.0                         6  
m2w64-gcc-libs            5.3.0                         7  
m2w64-gcc-libs-core       5.3.0                         7  
m2w64-gcc-objc            5.3.0                         6  
m2w64-gmp                 6.1.0                         2  
m2w64-headers-git         5.0.0.4636.c0ad18a               2  
m2w64-isl                 0.16.1                        2  
m2w64-libiconv            1.14                          6  
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2  
m2w64-libwinpthread-git   5.0.0.4634.697f757               2  
m2w64-make                4.1.2351.a80a8b8               2  
m2w64-mpc                 1.0.3                         3  
m2w64-mpfr                3.1.4                         4  
m2w64-pkg-config          0.29.1                        2  
m2w64-toolchain           5.3.0                         7  
m2w64-tools-git           5.0.0.4592.90b8472               2  
m2w64-windows-default-manifest 6.4                           3  
m2w64-winpthreads-git     5.0.0.4634.697f757               2  
m2w64-zlib                1.2.8                        10  
mako                      1.0.6                    py35_0  
markupsafe                0.23               py35_intel_6  [intel]  intel
marshmallow               2.7.2                     <pip>
matplotlib                2.0.0              py35_intel_0  [intel]  intel
menuinst                  1.4.1              py35_intel_4  [intel]  intel
mingw                     4.7                           1  
mistune                   0.7.4              py35_intel_0  [intel]  intel
mkl                       2017.0.3                intel_6  [intel]  intel
mkl-service               1.1.2                    py35_3  
mpmath                    0.19               py35_intel_5  [intel]  intel
msys2-conda-epoch         20160418                      1  
multipledispatch          0.4.9                    py35_0  
mxnet                     0.7.0                     <pip>
nb_anacondacloud          1.2.0                    py35_0  
nb_conda                  2.0.0                    py35_0  
nb_conda_kernels          2.0.0                    py35_0  
nbconvert                 5.1.1              py35_intel_0  [intel]  intel
nbformat                  4.3.0              py35_intel_0  [intel]  intel
nbpresent                 3.0.2                    py35_0  
networkx                  1.11                     py35_0  
nltk                      3.2.2                    py35_0  
nose                      1.3.7             py35_intel_12  [intel]  intel
notebook                  5.0.0              py35_intel_0  [intel]  intel
numba                     0.32.0            py35_intel_14  [intel]  intel
numexpr                   2.6.2           np111py35_intel_1  [intel]  intel
numpy                     1.12.0                    <pip>
numpy                     1.11.3             py35_intel_6  [intel]  intel
numpydoc                  0.6.0                    py35_0  
odo                       0.5.0                    py35_1  
olefile                   0.44                     py35_0  
openmp                    2017.0.3                intel_5    intel
openpyxl                  2.4.1                    py35_0  
openssl                   1.0.2k             vc14_intel_3  [intel vc14]  intel
ordereddict               1.1                       <pip>
pandas                    0.19.2             py35_intel_4  [intel]  intel
pandas-datareader         0.2.1                    py35_0  
pandocfilters             1.4.1              py35_intel_0  [intel]  intel
partd                     0.3.8                    py35_0  
path.py                   10.1               py35_intel_0  [intel]  intel
pathlib2                  2.2.1                    py35_0  
patsy                     0.4.1                    py35_0  
pep8                      1.7.0                    py35_0  
pickleshare               0.7.4              py35_intel_1  [intel]  intel
pillow                    4.1.1                    py35_0  
pip                       9.0.1              py35_intel_0  [intel]  intel
pkginfo                   1.4.1                    py35_0  
ply                       3.10                     py35_0  
prompt_toolkit            1.0.14             py35_intel_0  [intel]  intel
protobuf                  3.1.0               py35_vc14_1  [vc14]  willyd
protobuf                  3.2.0                     <pip>
psutil                    5.2.2                    py35_0  
py                        1.4.33                   py35_0  
pyasn1                    0.2.3                    py35_0  
pyCalverter               1.6.1                     <pip>
pycosat                   0.6.2              py35_intel_1  [intel]  intel
pycparser                 2.17               py35_intel_0  [intel]  intel
pycrypto                  2.6.1                    py35_5  
pycurl                    7.43.0                   py35_2  
pydaal                    2017.0.3.20170414    py35_intel_3  [intel]  intel
pyflakes                  1.5.0                    py35_0  
pygments                  2.2.0              py35_intel_0  [intel]  intel
pygpu                     0.6.4                    py35_0  
pylint                    1.6.4                    py35_1  
pymysql                   0.7.9                    py35_0  
pyopenssl                 16.2.0                   py35_0  
pyparsing                 2.1.4              py35_intel_5  [intel]  intel
pyqt                      5.6.0                    py35_2  
pyreadline                2.1                      py35_0  
pytables                  3.2.3.1            py35_intel_8  [intel]  intel
pytest                    3.0.7                    py35_0  
python                    3.5.3                   intel_1  [intel]  intel
python-dateutil           2.6.0                     <pip>
python-dateutil           2.6.0              py35_intel_0  [intel]  intel
python-xbrl               1.1.0                     <pip>
pytz                      2017.2             py35_intel_0  [intel]  intel
pywavelets                0.5.2               np111py35_0  
pywin32                   220                      py35_2  
pyyaml                    3.12               py35_intel_1  [intel]  intel
pyzmq                     16.0.2             py35_intel_2  [intel]  intel
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.4                    py35_0  
qtconsole                 4.3.0                    py35_0  
qtpy                      1.2.1                    py35_0  
redis                     2.10.5                    <pip>
regex                     2016.01.10                <pip>
requests                  2.13.0             py35_intel_0  [intel]  intel
requests                  2.13.0                    <pip>
requests-file             1.4.1                    py35_0  
rope                      0.9.4                    py35_1  
ruamel_yaml               0.11.14            py35_intel_1  [intel]  intel
scikit-image              0.13.0              np111py35_0  
scikit-learn              0.18.1             py35_intel_6  [intel]  intel
scipy                     0.18.1          np111py35_intel_13  [intel]  intel
seaborn                   0.7.1                    py35_0  
selenium                  3.4.1                     <pip>
setuptools                27.2.0             py35_intel_0  [intel]  intel
simplegeneric             0.8.1              py35_intel_5  [intel]  intel
singledispatch            3.4.0.3                  py35_0  
sip                       4.19.2                    <pip>
sip                       4.18                     py35_0  
six                       1.10.0             py35_intel_7  [intel]  intel
six                       1.9.0                     <pip>
snowballstemmer           1.2.1                    py35_0  
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.5.4                    py35_0  
sphinx_rtd_theme          0.2.4                    py35_0  
spyder                    3.1.4                    py35_0  
sqlalchemy                1.1.9                    py35_0  
sqlite                    3.13.0                 intel_14  [intel vc14]  intel
statsmodels               0.8.0               np111py35_0  
sympy                     1.0                py35_intel_5  [intel]  intel
tbb                       2017.0.6           py35_intel_3  [intel]  intel
tcl                       8.6.4             vc14_intel_16  [intel vc14]  intel
tensorflow-gpu            1.0.1                     <pip>
testpath                  0.3                py35_intel_0  [intel]  intel
theano                    0.9.0                    py35_0  
Theano                    0.9.0                     <pip>
tk                        8.6.4             vc14_intel_26  [intel vc14]  intel
toolz                     0.8.2                    py35_0  
tornado                   4.4.2              py35_intel_0  [intel]  intel
traitlets                 4.3.2              py35_intel_0  [intel]  intel
unicodecsv                0.14.1                   py35_0  
vc                        14.0                          1    intel
virtualenv                15.1.0                    <pip>
vs2015_runtime            14.0.25123              intel_3  [intel]  intel
wcwidth                   0.1.7              py35_intel_5  [intel]  intel
werkzeug                  0.12.1                   py35_0  
wheel                     0.29.0             py35_intel_5  [intel]  intel
widgetsnbextension        2.0.0                    py35_0    intel
win_unicode_console       0.5                py35_intel_0  [intel]  intel
workalendar               1.0.0                     <pip>
wrapt                     1.10.10                  py35_0  
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.6                    py35_0  
xlwings                   0.10.4                   py35_0  
xlwt                      1.2.0                    py35_0  
xz                        5.2.2             vc14_intel_15  [intel vc14]  intel
zlib                      1.2.11             vc14_intel_2  [intel vc14]  intel

I tried to install PyQt5, but it didn't help.

Thanks,

**Comment by ccordoba12** [comment]
How are you starting Spyder?

**Comment by nirvana1122** [comment]
I usually launch it run dialog box. Since it wasn't doing anything, I tried to launch it from the command prompt.   I uninstalled the Anaconda, downloaded v 4.2 from the archive, and it seems to work now. Thanks for looking into it.
