### ISSUE TITLE
/Users/Clement/anaconda/bin/pythonw: line 3: 92690 Illegal instruction: 4  /Users/Clement/anaconda/python.app/Contents/MacOS/python "$@"

### ISSUE THREAD

**Issue by cralax** [spyder-ide/spyder#4472]
I installed pytorch with cuda which works when using with the python command on the terminal
I'm on mac os Sierra
**What steps will reproduce the problem?**

1. launch terminal
2. typing spyder to launch it
3. It crashesand I have the following message: /Users/Clement/anaconda/bin/pythonw: line 3: 92690 Illegal instruction: 4  /Users/Clement/anaconda/python.app/Contents/MacOS/python "$@"

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.1.4
* Python Version:3.6.0
* Qt Version: 4.3.0
* PyQt Version:?
* Operating system:Sierra 10.12.4

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by cralax** [comment]
I finally reintsall python with a conda command, it works

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.
