### ISSUE TITLE
Inserting a line-break in code/comment with parenthesis deletes part of the code/comment

### ISSUE THREAD

**Issue by msoultan** [spyder-ide/spyder#4475]
## Description of your problem

I have a comment that is too long so I want to break it into two lines - this comment also contains parenthesis which seems to be causing the bug.  I go to where I want to break it and when I hit enter, it chops off some of the text from the line that is moved down a row.  Removing the parenthesis stops the strange behavior.  The example should explain it.

**What steps will reproduce the problem?**

1. enter this comment with all the preceding tabs (it's wrapped when I entered it):

```
								#verify that file has station name in it (just to be sure we're not accidentally pulling the wrong station)
```

2. place your cursor just in front of "pulling" and hit enter

3. you will end up with this:

```
								#verify that file has station name in it (just to be sure we're not accidentally 
												  lling the wrong station)
```

4. As you can see "pulling" has been chopped and it also has the incorrect indentation.  Now put your cursor in front of "lling" and hit backspace a lot of times to try and get "lling" to merge back up with the previous line - it will get "stuck" at the left margin.  It will look like this:

```
								#verify that file has station name in it (just to be sure we're not accidentally 
  lling the wrong station)
```

**What is the expected output? What do you see instead?**

It should insert a clean line break, properly tabbed.  Backspace should be able to merge it with the previous line.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: v3.1.4
* Python Version: 3.6.0 64bit
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll see what we can do about this in a future release.

**Comment by msoultan** [comment]
It turns out this isn't just limited to comments.  I had the following:

```
	print(strStationProjectPath)
	with open(strProjectFile, "r") as fShowTemplate, \
```

I put my cursor just before the closing parenthesis after "strStationProjectPath" and hit enter and I end up with this:

```
	print(strStationProjectPath
	   with open(strProjectFile, "r") as fShowTemplate, \
```

So there's some kinda weirdness going on that has to do with parenthesis and indentation.  Let me know if you need any more info.

Thanks!

**Comment by msoultan** [comment]
So.. more weirdness.  I'm not sure if it's limited to parenthesis.  Take this line of code:

```
						print("\"" + conPathToReaper + """ -renderproject """ & strMasterProjectPath & "TEMP-" & UCase(arrStationTracks(intStation)) & "-" & ReaperFile & """", ShowWindow, WaitUntilFinished
```

Which I know isn't legitimate code as I'm porting a script over from VBScript... but anyways, put your cursor to the right of the three quotes that are just to the left of "-renderproject" and you end up with this:

```
						print("\"" + conPathToReaper + " -renderproject """ & strMasterProjectPath & "TEMP-" & UCase(arrStationTracks(intStation)) & "-" & ReaperFile & """", ShowWindow, WaitUntilFinished
```

Notice how there is only one quote to the left of "-renderproject" - and no, I did not hit backspace twice.

**Comment by ccordoba12** [comment]
@rlaverde, please take a look at this one too.

**Comment by msoultan** [comment]
Here's another one for you.  Type the following:

```
print(
```

spyder will autocomplete and you will end up with the following (with the cursor between the parenthesis):

```
print()
```

hit enter

You'd expect something like this:

```
print(
)
```

But you get this:

```
print(
	  
```

If you try and press backspace, it will move back once (about two spaces worth), but if you backspace again, it won't do anything.  Btw, I am using tabs, not spaces, for my indentation.  Let me know if you need any more testing.

**Comment by msoultan** [comment]
Here's another weird one.  If I have the following (notice the missing colon after fOutFile):

```
	with open(os.path.join(RenderOutputPath,"test.txt", "w") as fOutFile
#1
#2
```

and I place my curson in front of #1 and hit tab, I end up with the following:

```
	with open(os.path.join(RenderOutputPath,"test.txt", "w") as fOutFile
		   #2
```
