### ISSUE TITLE
Double L-click result in KeyboardInterrupt, feature or bug?

### ISSUE THREAD

**Issue by imhuay** [spyder-ide/spyder#4478]
## Description of your problem
Double L-click  in the console result in KeyboardInterrupt
I want know if it is a feature or a bug

**What steps will reproduce the problem?**

1. run 
```
for i in range(1000000):
    print(i)
```
2. Double L-click in the console

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.3
* Qt Version:
* PyQt Version:
* Operating system: Win10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
It's a side effect.

**Comment by ccordoba12** [comment]
And we don't even know why it happens, sorry. Hopefully it won't cause you too much troubles.

**Comment by imhuay** [comment]
I think I know the reason. It's a conflict from some Translator software. This kind of software have a function that translate when select some word, and when do some selecting operation such Double L-click may trigger that event using ‘Ctrl+C’.
