### ISSUE TITLE
Auto-indent Incorrect following line starting with return as part of variable name.

### ISSUE THREAD

**Issue by venuur** [spyder-ide/spyder#4481]
## Description of your problem

Following an assignment to a variable starting with the string "return" as part of the variable name, e.g. "returns", in a function definition, the auto-indent for the following line is incorrectly set as if following a return statement.

**What steps will reproduce the problem?**

1. Create a python file containing the following code:

```
def some_func():
    returns = 10
```

2. Press enter with the cursor at the end of the second line.

**What is the expected output? What do you see instead?**
I expect the cursor to indent to the same level as the second line. Instead the cursor indents to same level as the first line.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10 (Version 1703 OS Build 15063.296)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix it in the next Spyder version.

**Comment by ccordoba12** [comment]
@rlaverde, please take a look at this one. It seems an easy fix.
