### ISSUE TITLE
Use Tab key to copy text to "Replace with:" field

### ISSUE THREAD

**Issue by hiccup7** [spyder-ide/spyder#4482]
This is an enhancement request.  When I am replacing a string in the editor, I often copy the original string into the "Replace with:" field and modify it.  Another programming editor I uses the Tab key as a keyboard shortcut for this operation, which I really like.  The workflow in Spyder would then be as follows: select a string in the editor, press Ctrl-R to copy the string to the Replace field and move the cursor to the "Replace with:" field, then press Tab to copy the string to the "Replace with:" field so it can be modified.  The last step is the enhancement.  A nice little productivity boost!

**Comment by ccordoba12** [comment]
Cool suggestion!! We're very busy right now, but you could give it a try if you want. The find and replace widget is here:

https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/findreplace.py

**Comment by silentquasar** [comment]
With #6094 complete, this should be easy. I'll submit a PR.
