### ISSUE TITLE
Cannot install modules in DMG version

### ISSUE THREAD

**Issue by neuropacabra** [spyder-ide/spyder#4483]
Installing new modules cannot be done in macOS version. I have tried to use sys.path.append() to force Spyder use another Python installation (Anaconda3) on my Mac. But it last only until restart. No luck with hard-wiring it into PYTHONPATH variable.

When calling magic command `!pip install modulename` I get this kind of error:
`ImportError: Bad magic number in /Users/michael/Desktop/Spyder.app/Contents/Resources/site.pyc`

I am trying to use standalone version for macOS. But I need some modules which is not packed originaly and I am not able to do that.

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 3.5.2
* Qt Version: 5.7.0
* PyQt Version: 5.5.7
* Operating system: macOS 10.12.4

**Comment by ccordoba12** [comment]
Our DMGs are completely self contained (i.e. no new software can be installed on them) and we don't plans to change that in the future. They are mostly useful for people to try Spyder and the most important packages of the Python scientific stack, or for teaching classes.

If you want something more advanced, please use Anaconda.
