### ISSUE TITLE
Spyder doesn't connect to kernel. perpetual "connecting to kernel"

### ISSUE THREAD

**Issue by davidseraphi** [spyder-ide/spyder#4484]
## Description

**What steps will reproduce the problem?**

1. when i start spyder it just remains in a perpetual state of "connecting to kernel in the ipython console window"
This question has been asked several times but nothing seems to solve the issue. I'm starting out on the "Introduction to Computer Science and Programming Using Python" and nothing seems to be happening when i open spyder.
The image in the link below is what i'm supposed to be seeing. Am i doing something wrong here?

https://cloud.githubusercontent.com/assets/14263694/26159949/93d3b258-3b28-11e7-945c-e106605f1707.png

Any help would be very much appreciated. Thanks.

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Please open a terminal (cmd.exe), run the following command

    spyder --show-console

and post an image of the errors reported on the console here.

With that info we can diagnose the error and let you know how to fix it.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
