### ISSUE TITLE
spyder_io_hdf5 plugin not available

### ISSUE THREAD

**Issue by smjorda** [spyder-ide/spyder#4487]
## Description

spyder_io_hdf5 plugin doesn't seem to be registered although h5py installed correctly.

**What steps will reproduce the problem?**

1. Ensure h5py installed
2. Go to variable editor pane
3. Click import, note lack of .h5 extension being available

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
This code change fixes it (line 51 and down of otherplugins.py):

****************
    for name in os.listdir(plugin_path):
        # Is this a Spyder plugin?
        if not name.startswith(PLUGIN_PREFIX):
            continue
        # Ensure right type of plugin
        if is_io != name.startswith(IO_PREFIX):
            continue

        # Import the plugin
        _import_plugin(name, plugin_path, modnames, modlist)
**************
## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.5.2
* Qt Versions: 5.7.0, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.6.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Could you open a pull request about this? You can do it using the Github web interface for that.

**Comment by ccordoba12** [comment]
But please do it against the `3.x` branch and not master (`3.x` is our current maintenance branch).
