### ISSUE TITLE
ipython autocompletion issue (ipython 6.0.0 - inferred completions)

### ISSUE THREAD

**Issue by alastairbs** [spyder-ide/spyder#4488]
## Description of your problem

**What steps will reproduce the problem?**

1. thisData = ['123']
2. thisData[0].<tab>
3. 

**What is the expected output? What do you see instead?**
As [here](http://ipython.readthedocs.io/en/stable/whatsnew/version6.html#new-completion-api-and-interface) you should see the auto completion info for the string '123' but nothing appears in the spyder ipython console (works fine in ipython from a terminal).

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version: 5.8.0
* PyQt Version:5.8.1
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
There's nothing we can do about this. There are some changes that need to be done in the `ipykernel` package for the changes made in IPython 6 to be available in Spyder.
