### ISSUE TITLE
strange memory issue with plugin_server process

### ISSUE THREAD

**Issue by davesbc** [spyder-ide/spyder#4489]
## Description of your problem
spyder process:     
pythonw.exe -u plugin_server - jedi slowly ramps up memory usage until it takes up around 2Gb, at which point machine experiences extreme performance problem as total memory 4Gb.
**What steps will reproduce the problem?**

1. normal usage of spyder3.5 for about 3 hours. occurred twice in recent days
2. 
3. 

**What is the expected output? What do you see instead?**
expect around 100mb memory usage, it gets to 2Gb. problem seems to be the Jedi server process.

**Please provide any additional information below**
ending the process clears the memory usage and it slowly builds again

## Versions and main components

* Spyder Version: 3.5
* Python Version: 3.5.3.1
* Qt Version: 
* PyQt Version: 5
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this as soon as we can.

**Comment by ccordoba12** [comment]
This no longer apply.
