### ISSUE TITLE
More Find in Files improvements

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#4490]
![seleccion_002](https://cloud.githubusercontent.com/assets/365293/26038289/d1832ac6-38ca-11e7-8655-e1f1ae0d5417.png)

I used the new Find in Files after PR #4056 was merged, and these are my suggestions to improve your previous work @andfoy (which, by the way, was great!):

1. Results must be shown in ascending order, i.e. first line 1, then line 3, etc. Right now results are shown in descending order (please take a look at the screenshot).
2. We need to remove information about columns. For example, in the screenshot you can see two results about line 1 (one for column 5, the other for column 0). We simply need to report one entry per line (as it's done in `ack` or `ag`).
3. The name of the file must be in bold. Example (from the screenshot):

    **spam.txt** - /home/carlos/Projects/...
    **->** ...

4. The line number must in bold too, the text inside the line must use a monospaced font, and the results detected inside it must be in bold too. Example (from the screenshot):

    **3**:` lore ipsum sit dolor`**`spam`**

5. After a file is completely searched, its results need to be expanded automatically. This avoids the need of pressing the expand button every time you search for something (which becomes tiresome :-).

6. Icons for file types need to be changed to use `file-o` from FontAwesome:

    https://github.com/spyder-ide/spyder/blob/master/spyder/utils/icon_manager.py#L175

**Comment by andfoy** [comment]
With respect to the column information, I decided to display all the results independently, that's because sometimes a search match can be found on files that contain a single text line, such as minified Javascript sources, on this cases, displaying the match elements may be more difficult if the result is shown on a single line

**Comment by goanpeca** [comment]
>We need to remove information about columns. For example, in the screenshot you can see two results about line 1 (one for column 5, the other for column 0). We simply need to report one entry per line (as it's done in ack or ag).

Yeah, I agree with @andfoy, I am not convinced with removing the column info.
