### ISSUE TITLE
IPython Console doesn't connect to kernel

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4492]
## Description

**What steps will reproduce the problem?**

1. IPython console almost always is perpetually saying, "Connecting to kernel. "
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.3 
* Python Version: 2.7.12
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.3.6 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi =0.9.0      :  0.9.0 (OK)
psutil >=0.3     :  5.2.1 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by ccordoba12** [comment]
Please open a terminal, run Spyder there and report the errors that appear there here.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
