### ISSUE TITLE
Can't update to new version

### ISSUE THREAD

**Issue by fitoprincipe** [spyder-ide/spyder#4493]
## Can't update to newer than 2.3.8

**steps that reproduce the problem**

1. $> sudo apt-get update
2. $> sudo apt-get install spyder

**expected output** 
UPDATE
**I see instead**
$> spyder is in it's latest version (2.3.8+dfsg1-1build1)

**additional information**
I wonder if version 3+ is only for python 3+

## Versions and main components

* Spyder Version: 2.3.8+dfsg1-1build1
* Python Version: 2.7.12
* Qt Version: 
* PyQt Version:
* Operating system: Linux Mint 18 Sarah MATE

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=1.0      :  5.1.0 (OK)
jedi >=0.8.1;<0.9.0:  None (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
pandas >=0.13.1    :  0.19.2 (OK)
pep8 >=0.6         :  None (NOK)
psutil >=0.3       :  None (NOK)
pyflakes >=0.5.0   :  None (NOK)
pygments >=1.6     :  2.2.0 (OK)
pylint >=0.25      :  None (NOK)
qtconsole >=4.0    :  None (NOK)
rope >=0.9.2       :  0.10.2 (OK)
sphinx >=0.6.6     :  1.5.5 (OK)
zmq >=2.1.11       :  None (NOK)

**Comment by ccordoba12** [comment]
> I wonder if version 3+ is only for python 3+

Nop, not true. Spyder 3 is available since Zesty (in Ubuntu, I don't know the equivalent in Mint).

http://packages.ubuntu.com/zesty/spyder

So you probably need to update your whole distribution. Or, if you don't want, simply use Anaconda.
