### ISSUE TITLE
A way to fix the file switcher panel

### ISSUE THREAD

**Issue by fitoprincipe** [spyder-ide/spyder#4494]
## Is there a way to fix the file switcher panel ?

**additional information**
I have installed the latest version from source. 
I think switching between working files should be a main feature and deserves to have it's own panel

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.12
* Qt Version:
* PyQt Version:
* Operating system: Linux Mint 18 MATE

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> I think switching between working files should be a main feature and deserves to have it's own panel

Sorry, we have enough panels already, so we're not going to implement this. Besides, other editors provide exactly the same feature as we do (e.g. VSCode and Sublime Text).

**Comment by fitoprincipe** [comment]
I think many panels are less important than the one I suggest. Compare: times you open new files vs times you switch between them. Look at Geany IDE, the feature I suggest is implemented and very useful to me (at least ask others than me). I love Spyder, but it'd only be complete (for me) if I could switch fast and easy between files.

**Comment by jitseniesen** [comment]
You can develop a Spyder plugin that implements such a panel.

**Comment by fitoprincipe** [comment]
Is there a guide on "how to"? I'm not a python expert and don't have much free time to dig in, a guide would be great. Thank you.
