### ISSUE TITLE
Shift+Space shortcut doesn't work

### ISSUE THREAD

**Issue by Yanpas** [spyder-ide/spyder#4496]
## Description

**What steps will reproduce the problem?**

1. Set "Shift Space" for code completion in settings
2. Press it in code, you will see the space
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future Spyder release.

**Comment by ccordoba12** [comment]
We tried to make this work but unfortunately found it's not possible, sorry.

Since Spyder 3.2 all shortcuts that try to use `Shift` and a single key will be forbidden because, unless they are hardcoded in Spyder sourcecode, they can't be assigned through our interface.
