### ISSUE TITLE
Problems with running matplotlib

### ISSUE THREAD

**Issue by NervenCid** [spyder-ide/spyder#4497]
## Description

**What steps will reproduce the problem?**

1. I'm tryng to run the next code:

```python
import matplotlib.pyplot as plt

#Esta funcion se activara si el mouse esta encima de una
#de la figuras
def enter_axes(event):
    print ('Entrando a la figura en: ', event.inaxes)
    event.inaxes.patch.set_facecolor('yellow')
    event.canvas.draw()

#Esta funcion se activara si el mouse esta por fuera
#de una de la figuras
def leave_axes(event):
    print ('Saliendo de la figura en: ', event.inaxes)
    event.inaxes.patch.set_facecolor('white')
    event.canvas.draw()

#Creamos dos figuras
fig = plt.figure()
fig.suptitle('Desplace el mouse sobre una de las figuras')
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)

#Las conectamos con el gestor de eventos
fig.canvas.mpl_connect('axes_enter_event', enter_axes)
fig.canvas.mpl_connect('axes_leave_event', leave_axes)

#Mostramos en pantalla
plt.show()
```

2. I push the botton "Ejecutar el archivo (F5)" (a.k.a run file)
3. I still don't get any response and the windows don't show

**What is the expected output? What do you see instead?**

It must display a matplotlib window, is kinda strange, because the code is to simple and i used Normal Python and it worked fine. But i don't understand why the Python version for Anaconda/spyder Don't

**Please provide any additional information below**

I used the official version of Python and the window show normally and fast

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Did you change your graphics backend before running this code?

**Comment by ccordoba12** [comment]
Running

    %matplotlib qt5

before running your code should solve this issue.

**Comment by NervenCid** [comment]
Hello: 

Thank you for your answer, i am not using ipython and i changed to this:


%matplotlib qt5

import matplotlib.pyplot as plt

#Esta funcion se activara si el mouse esta encima de una
#de las figuras
def enter_axes(event):
    print ('Entrando a la figura en: ', event.inaxes)
    event.inaxes.patch.set_facecolor('yellow')
    event.canvas.draw()

#Esta funcion se activara si el mouse esta por fuera
#de una de la figuras
def leave_axes(event):
    print ('Saliendo de la figura en: ', event.inaxes)
    event.inaxes.patch.set_facecolor('white')
    event.canvas.draw()

#Creamos dos figuras
fig = plt.figure()
fig.suptitle('Desplace el mouse sobre una de las figuras')
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)

#Las conectamos con el gestor de eventos
fig.canvas.mpl_connect('axes_enter_event', enter_axes)
fig.canvas.mpl_connect('axes_leave_event', leave_axes)

#Mostramos en pantalla
plt.show()


But didn't worked

**Comment by ccordoba12** [comment]
> i am not using ipython

You need to use IPython. The Python console will be removed in Spyder 3.2 anyway.
