### ISSUE TITLE
kernel restart when logging to console in debug mode

### ISSUE THREAD

**Issue by robbuckley** [spyder-ide/spyder#4498]
Kernel restarts when running a trivial console logging example in debug mode. 
If i run it in non-debug model (F5), it works fine. If i log only a file , it also works fine.  

is it a duplicate of https://github.com/spyder-ide/spyder/issues/4421 ?

**What steps will reproduce the problem?**

1.  Run the following program with Debug (CTRL+F5) + Continue (CTRL+F12). No breakpoints are set

    logger = logging.getLogger(__name__)
    logger.setLevel(logging.DEBUG)
    
    ch = logging.StreamHandler()    
    ch.setLevel(logging.DEBUG)

    formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    ch.setFormatter(formatter)

    logger.addHandler(ch)

    logger.info('test')
    logger.info('test2')

    ch.close()
    logger.removeHandler(ch)
    logging.shutdown()

**What is the expected output? What do you see instead?**

Expect to see 2x log messages:

2017-05-20 10:39:11,200 - __main__ - INFO - test
2017-05-20 10:39:11,208 - __main__ - INFO - test2

Instead see :

2017-05-20 10:38:41,663 - __main__ - INFO - test
ipdb> 
Restarting kernel because an error occurred while debugging 

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.3 (ipython console reported)
* Qt Version: 5.6.2
* PyQt Version:  5.6.0
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> is it a duplicate of #4421?

Yes, I'm afraid it is. This will be fixed in PR #4202, which will be part of Spyder 3.2. Sorry for the inconveniences this causes you in the meantime.

You can also downgrade to Spyder 3.1.3, which doesn't have this problem.

**Comment by robbuckley** [comment]
hi, it also works for me to disable logging to console before running in debug mode. Logging to file [only] seems to work fine. Im writing this comment in case it helps anyone else, who like me, prefers not to downgrade to avoid this bug

**Comment by ccordoba12** [comment]
Yep, the problem really has to do with printing to the console while debugging. That's what makes the kernel to restart.

**Comment by awa5114** [comment]
How to disable logging to the console please? I'm looking for it in the preferences but cannot find it...
