### ISSUE TITLE
Spyder unable to start Ubuntu after install OpenCV

### ISSUE THREAD

**Issue by giacomomarchioro** [spyder-ide/spyder#4501]
## Description of your problem

Spyder crashes after opening it.

```
Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in <module>
    start_app.main()
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 78, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```

**What steps will reproduce the problem?**

1.  pip install python-opencv?
2. opening spyder

**What is the expected output? What do you see instead?**
It doesn't open. 

I have tried: 

1. uninstalling and installing spyder
2. pip install html5lib
**Please provide any additional information below**

## Versions and main components

* Spyder Version:2.3.8+dfsg1-1build1
* Python Version:Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
* Qt Version:?
* PyQt Version:?
* Operating system: Ubuntu 14.4

**Comment by ccordoba12** [comment]
Spyder 2.3 is not supported anymore, sorry. You probably need to update `beautifulsoup` to fix this error, but I'm not sure.

**Comment by giacomomarchioro** [comment]
Thanks so it wat time to me to upgrade it :
sudo pip install -U spyder

After upgrade it worked.

**Comment by tfmatos** [comment]
Hi, 
I am crossing the same problem... Even after upgrade spyder (sudo -H pip install -U spyder)!
From ubuntu (sudo apt install spyder) I reach only spyder 2.3...... 

Could you give me any advice? 

`Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
`

`:~$ spyder
Traceback (most recent call last):
  File "/usr/bin/spyder", line 3, in <module>
    start_app.main()
  File "/usr/lib/python2.7/dist-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/usr/lib/python2.7/dist-packages/spyderlib/spyder.py", line 155, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/lib/python2.7/dist-packages/spyderlib/utils/environ.py", line 17, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditor.py", line 39, in <module>
    from spyderlib.widgets.dicteditorutils import (sort_against, get_size,
  File "/usr/lib/python2.7/dist-packages/spyderlib/widgets/dicteditorutils.py", line 78, in <module>
    import bs4
  File "/usr/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
`
And the list of packages:

`~$ pip list
Package                       Version               
----------------------------- ----------------------
alabaster                     0.7.10                
astroid                       1.6.4                 
Babel                         2.5.3                 
backcall                      0.1.0                 
beautifulsoup4                4.4.1                 
bleach                        2.1.3                 
blinker                       1.3                   
catfish                       1.4.2                 
chardet                       2.3.0                 
cloudpickle                   0.5.3                 
command-not-found             0.3                   
cryptography                  1.2.3                 
cycler                        0.9.0                 
decorator                     4.0.6                 
defer                         1.0.6                 
Django                        2.0.5                 
docutils                      0.14                  
entrypoints                   0.2.3                 
feedparser                    5.1.3                 
fenics-dijitso                2017.2.0              
fenics-ffc                    2017.2.0              
fenics-fiat                   2017.2.0              
fenics-instant                2017.2.0              
fenics-ufl                    2017.2.0              
html5lib                      1.0.1                 
httplib2                      0.9.1                 
idna                          2.0                   
imagesize                     1.0.0                 
ipykernel                     4.8.2                 
**ipython                       6.4.0**                 
ipython-genutils              0.2.0                 
isort                         4.3.4                 
jedi                          0.12.0                
Jinja2                        2.10                  
jsonschema                    2.6.0                 
jupyter-client                5.2.3                 
jupyter-core                  4.4.0                 
kazam                         1.4.5                 
language-selector             0.1                   
lazy-object-proxy             1.3.1                 
lightdm-gtk-greeter-settings  1.2.1                 
lxml                          3.5.0                 
MarkupSafe                    1.0                   
matplotlib                    1.5.1                 
mccabe                        0.6.1                 
menulibre                     2.1.3                 
mistune                       0.8.3                 
mpi4py                        1.3.1                 
mpmath                        0.19                  
mugshot                       0.3.1                 
nbconvert                     5.3.1                 
nbformat                      4.4.0                 
numpy                         1.11.0                
numpydoc                      0.8.0                 
oauthlib                      1.0.3                 
onboard                       1.2.0                 
openopt                       0.5625                
packaging                     17.1                  
pandas                        0.23.0                
pandocfilters                 1.4.2                 
parso                         0.2.0                 
patsy                         0.5.0                 
pep8                          1.7.0                 
petsc4py                      3.7.0                 
pexpect                       4.0.1                 
pickleshare                   0.7.4                 
Pillow                        3.1.2                 
pip                           10.0.1                
ply                           3.7                   
prompt-toolkit                1.0.15                
psutil                        3.4.2                 
ptyprocess                    0.5                   
pyasn1                        0.1.9                 
pycodestyle                   2.4.0                 
pycups                        1.9.73                
pycurl                        7.43.0                
pyDOE                         0.3.8                 
pyflakes                      1.6.0                 
Pygments                      2.1                   
pygobject                     3.20.0                
PyJWT                         1.3.0                 
pylint                        1.9.1                 
PyOpenGL                      3.1.0                 
pyparsing                     2.0.3                 
PyQt5                         5.9.2                 
python-apt                    1.1.0b1+ubuntu0.16.4.1
python-dateutil               2.7.3                 
python-debian                 0.1.27                
python-systemd                231                   
pytz                          2014.10               
pyxdg                         0.25                  
pyzmq                         15.2.0                
QtAwesome                     0.4.4                 
qtconsole                     4.3.1                 
QtPy                          1.4.2                 
reportlab                     3.3.0                 
requests                      2.9.1                 
rope                          0.10.7                
scikit-learn                  0.19.1                
scipy                         0.17.0                
screen-resolution-extra       0.0.0                 
seaborn                       0.8.1                 
sessioninstaller              0.0.0                 
setproctitle                  1.1.10                
setuptools                    20.7.0                
simplegeneric                 0.8.1                 
sip                           4.19.8                
six                           1.10.0                
slepc4py                      3.7.0                 
snowballstemmer               1.2.1                 
Sphinx                        1.7.4                 
sphinxcontrib-websupport      1.0.1                 
spyder                        3.2.8                 
ssh-import-id                 5.5                   
statsmodels                   0.9.0                 
sympy                         0.7.6.1               
system-service                0.3                   
testpath                      0.3.1                 
tornado                       5.0.2                 
traitlets                     4.3.2                 
ubuntu-drivers-common         0.0.0                 
ufw                           0.35                  
unattended-upgrades           0.1                   
unity-scope-calculator        0.1                   
unity-scope-chromiumbookmarks 0.1                   
unity-scope-colourlovers      0.1                   
unity-scope-devhelp           0.1                   
unity-scope-firefoxbookmarks  0.1                   
unity-scope-gdrive            0.7                   
unity-scope-manpages          0.1                   
unity-scope-openclipart       0.1                   
unity-scope-texdoc            0.1                   
unity-scope-tomboy            0.1                   
unity-scope-virtualbox        0.1                   
unity-scope-yelp              0.1                   
unity-scope-zotero            0.1                   
urllib3                       1.13.1                
vboxapi                       1.0                   
virtualenv                    15.0.1                
wcwidth                       0.1.7                 
webencodings                  0.5.1                 
wheel                         0.29.0                
wrapt                         1.10.11               
xkit                          0.0.0   `
