### ISSUE TITLE
Enhancements on the file explorer

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4508]
Remove the clunky and outdated up/left and right buttons from the file explorer. That is a very poor UX/UI and they just up space.

<img width="585" alt="screen shot 2017-05-23 at 11 50 08 am" src="https://cloud.githubusercontent.com/assets/3627835/26365723/038c4144-3fae-11e7-8fe3-84b78a96b635.png">

We can explore different things like a breadcrumb or look how other IDES handle this

**Comment by ccordoba12** [comment]
How users are supposed to navigate through their file systems then?

**Comment by goanpeca** [comment]
Like every other software in the world except Spyder ?

**Comment by ccordoba12** [comment]
Meaning? :-p
