### ISSUE TITLE
Text Cursor is black on dark background

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#451]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2010-11-12T12:16:24Z_

I just upgraded from Spyder 2.0.0beta5 to 2.0.0beta6.  I noticed I can no longer see the the text cursor (caret), which is very frustrating.  I checked if there was a way to control the color via the Syntax Coloring or Editor settings, but I did not see anything related to this.  Please make it configurable or at least use a light color on dark backgrounds.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=451_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2010-11-15T10:25:38Z_

This issue was closed by revision 4e0f67652b .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-24T07:36:58Z_

This issue was closed by revision 4e0f67652bc4 .

**Comment by CorneelDragon** [comment]
This issue is closed a long time ago, but my mouse is barely visual with theme 'spyder dark' since it is black with a grey lining. It is black with a grey lining. How can I change this?

**Comment by adityapatile** [comment]
This is very painful

**Comment by jnsebgosselin** [comment]
@adityapatile are you on MacOS? If so, please comment on #7813 instead.
