### ISSUE TITLE
IPython crash due to X11 connection broken

### ISSUE THREAD

**Issue by adler-j** [spyder-ide/spyder#4512]
## Description of your problem

IPython (inside spyder) crashes with message:

```
The X11 connection broke (error 1). Did the X11 server die?
```

Sadly I am unable to give much more information, but any hint on what logs to look into would be great. I have not observed the crash to happen outside of spyder.

**What steps will reproduce the problem?**

I am unable to exactly reproduce the problem, it seems to occur after a long running process. It does not necessarily happen when actively executing any code.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.5
* Qt Version: 5
* PyQt Version: 1.2.1
* Operating system: Ubuntu 16.04

**Comment by ccordoba12** [comment]
Sorry, I have no idea why this is happening, and I haven't seen this error before. Besides, without a reproducible example it's impossible for us to help you.

You could start Spyder from a terminal and look for possible errors there. You can also open the pane called *Internal console*, which shows all internal errors generated by Spyder.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
