### ISSUE TITLE
Spyder won't launch

### ISSUE THREAD

**Issue by draguouo** [spyder-ide/spyder#4515]
## Description of your problem
Spyder won't launch (it'll appear, saying "initializing" at the bottom, but then the box will disappear)
**What steps will reproduce the problem?**

1. Clicking on "Spyder" or typing spyder into cmd
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
How did you install Spyder?

**Comment by draguouo** [comment]
Thanks for replying, but I just fixed it - turns out the folder into which I was installing Anaconda had a space. Thanks for the prompt response, though.
