### ISSUE TITLE
Not able to view pandas DataFrame in variable explorer

### ISSUE THREAD

**Issue by shashank31mar** [spyder-ide/spyder#4518]
## Description

**What steps will reproduce the problem?**

1. Created a pandas DataFrame by reading from a csv file
2. Double clicked on DataFrame in variable explorer and the i got the error

![error](https://cloud.githubusercontent.com/assets/10057288/26543307/13f853b6-447b-11e7-94c6-4166950c454e.png)

**What is the expected output? What do you see instead?**
I expected to see a pop-up displaying DataFrame values similar to the result shown in the image
![expected](https://cloud.githubusercontent.com/assets/10057288/26543375/6a8626a4-447b-11e7-9aa1-038c9e3f9b9f.png)

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Please post the code and csv file used to generate the DataFrame. Else we can't help you.

**Comment by shashank31mar** [comment]
I reopened the spider and it was working fine then. So closing this issue
