### ISSUE TITLE
Variables created in remote IPython kernel not appearing in Variable Explorer

### ISSUE THREAD

**Issue by zachturn** [spyder-ide/spyder#4519]
## Description of your problem

My Variable Explorer will not show variables that are created in remote IPython consoles. However, it does work for local IPython consoles.

**What steps will reproduce the problem?**

1. Connect to a remote ipython kernel
2. Create any variable in the console
3. Variable explorer does not display it

**What is the expected output? What do you see instead?**

I would like to see the variable, but I do not.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6 (local) 3.5.2 (remote)
* Qt Version: 5.6
* PyQt Version: 5.6
* Operating system: OSX El Capitan 10.11.6

## Dependencies

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
There's nothing we can do about it for now, but we plan to address this issue in Spyder 4.

**Comment by zachturn** [comment]
Understood, thanks!
