### ISSUE TITLE
Mayavi 4.5.0 crashes on IPython and Python console in Python 2.7.13, Windows-10 64-bit on Anaconda environment

### ISSUE THREAD

**Issue by s0r2637** [spyder-ide/spyder#4531]
## Description

**What steps will reproduce the problem?**

1. from mayavi import mlab
2. 
3. 

**What is the expected output? What do you see instead?**
What is see is the following:
`RuntimeError: Invalid Qt API 'pyqt5', valid values are: 'pyqt' or 'pyside'`

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Mayavi doesn't work with PyQt5, so you need to create a conda env with PyQt4, install Mayavi and make Spyder use that environment instead of the default one.

For the last part, you need to change your Python interpreter to the use the one in your env by going to

    Preferences > Python Interpreter

**Comment by s0r2637** [comment]
Hi Carlos,

I downgraded PyQt to 4.11.4, and now my spyder doesn't work.  Probably
incompatible version.  Below is the error I get in the command line.  What
do I do next?  I can't run Spyder right now.  Need it to work urgently.

*Traceback (most recent call last):*
*  File
"C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\Scripts\spyder-script.py",
line 5, in <module>*
*    sys.exit(spyder.app.start.main())*
*  File
"C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\app\start.py",
line 103, in main*
*    from spyder.app import mainwindow*
*  File
"C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\app\mainwindow.py",
line 49, in <module>*
*    requirements.check_qt()*
*  File
"C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\spyder\requirements.py",
line 39, in check_qt*
*    import qtpy*
*  File
"C:\Users\srajaraman\AppData\Local\Continuum\Anaconda2\lib\site-packages\qtpy\__init__.py",
line 125, in <module>*
*    raise PythonQtError('No Qt bindings could be found')*
*qtpy.PythonQtError: No Qt bindings could be found*

**Comment by s0r2637** [comment]
Hi Carlos,

I found that PySide was missing after I downgraded PyQt to 4.11.4.  Now
Spyder is able to initialize but exits without any error.  Please help!!

Srini
