### ISSUE TITLE
Spyder wont start -- malloc(): memory corruption error

### ISSUE THREAD

**Issue by yalaudah** [spyder-ide/spyder#4542]
Hi Guys. I'm running Anaconda with python 2.7 on Ubuntu 16.04. When I try to run Spyder for the first time, I get a very strange error that I couldn't figure out. Here is the error message: 

***** Error in `/homes/alaudah/anaconda2/bin/python': malloc(): memory corruption: 0x0000000003085750 *****
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff3797a77e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8181e)[0x7ff3797b181e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7ff3797b35d4]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Core.so.5(_ZN9QListData11detach_growEPii+0x67)[0x7ff35b15bfa7]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(+0xd1fb0)[0x7ff357082fb0]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(+0xd214d)[0x7ff35708314d]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN16QFontEngineMultiC2EP11QFontEngineiRK11QStringList+0x237)[0x7ff35714a4b7]
/usr/local/MATLAB/R2017a/bin/glnxa64/libQt5XcbQpa.so.5(+0x9ce10)[0x7ff3458e5e10]
/usr/local/MATLAB/R2017a/bin/glnxa64/libQt5XcbQpa.so.5(+0x9a7d5)[0x7ff3458e37d5]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(+0x1af2bf)[0x7ff3571602bf]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN13QFontDatabase8findFontERK8QFontDefi+0x78f)[0x7ff357160f0f]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN13QFontDatabase4loadEPK12QFontPrivatei+0x6cf)[0x7ff35716176f]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZNK12QFontPrivate15engineForScriptEi+0xc5)[0x7ff35713a665]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZNK11QTextEngine10fontEngineERK11QScriptItemP6QFixedS4_S4_+0x147)[0x7ff3571688d7]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZNK11QTextEngine9shapeTextEi+0x176)[0x7ff3571696f6]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZNK11QTextEngine5shapeEi+0xb3)[0x7ff35716a483]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN9QTextLine13layout_helperEi+0xd71)[0x7ff35717c781]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN11QTextLayout10createLineEv+0x12e)[0x7ff35717d83e]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Svg.so.5(_ZN8QSvgText4drawEP8QPainterR15QSvgExtraStates+0x1128)[0x7ff348272478]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Svg.so.5(_ZN16QSvgTinyDocument4drawEP8QPainterRK6QRectF+0x1cb)[0x7ff34829000b]
/homes/alaudah/anaconda2/plugins/imageformats/libqsvg.so(+0x404e)[0x7ff342ddf04e]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN12QImageReader4readEP6QImage+0x142)[0x7ff3570ff912]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN12QImageReader4readEv+0x24)[0x7ff3570fff34]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN15QPlatformPixmap8fromFileERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE+0x48)[0x7ff357114d28]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN7QPixmap4loadERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE+0x7ba)[0x7ff35710f60a]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/../../../libQt5Gui.so.5(_ZN7QPixmapC2ERK7QStringPKc6QFlagsIN2Qt19ImageConversionFlagEE+0x90)[0x7ff35710f740]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/QtGui.so(+0x1f2b59)[0x7ff3579ccb59]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/PyQt5/QtGui.so(+0x1f3360)[0x7ff3579cd360]
/homes/alaudah/anaconda2/lib/python2.7/site-packages/sip.so(+0x82f8)[0x7ff3584b82f8]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(+0xad568)[0x7ff37a4d3568]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53)[0x7ff37a46fe93]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x715d)[0x7ff37a52280d]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7ff37a524c3e]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7ff37a524d52]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyImport_ExecCodeModuleEx+0xc2)[0x7ff37a536bd2]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x11331e)[0x7ff37a53931e]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x1140d1)[0x7ff37a53a0d1]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(+0x11460c)[0x7ff37a53a60c]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyImport_ImportModuleLevel+0x364)[0x7ff37a53aaf4]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(+0xf42cf)[0x7ff37a51a2cf]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53)[0x7ff37a46fe93]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x43)[0x7ff37a51a7b3]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x3d96)[0x7ff37a51f446]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8c95)[0x7ff37a524345]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x7ff37a524c3e]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCode+0x32)[0x7ff37a524d52]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyRun_FileExFlags+0xb0)[0x7ff37a545450]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(PyRun_SimpleFileExFlags+0xef)[0x7ff37a54562f]
/homes/alaudah/anaconda2/bin/../lib/libpython2.7.so.1.0(Py_Main+0xca4)[0x7ff37a55afd4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7ff379750830]
/homes/alaudah/anaconda2/bin/python[0x400729]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 9311785                            /homes/alaudah/anaconda2/bin/python2.7
00600000-00601000 rw-p 00000000 08:01 9311785                            /homes/alaudah/anaconda2/bin/python2.7
02117000-051e7000 rw-p 00000000 00:00 0                                  [heap]
7ff334000000-7ff334021000 rw-p 00000000 00:00 0 
7ff334021000-7ff338000000 ---p 00000000 00:00 0 
7ff338000000-7ff338021000 rw-p 00000000 00:00 0 
7ff338021000-7ff33c000000 ---p 00000000 00:00 0 
7ff33c000000-7ff33c021000 rw-p 00000000 00:00 0 
7ff33c021000-7ff340000000 ---p 00000000 00:00 0 
7ff341938000-7ff341939000 rw-p 00000000 00:00 0 
7ff341939000-7ff3419f2000 r--p 00000000 08:01 11929896                   /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
7ff3419f2000-7ff3419f9000 r--s 00000000 08:01 10094058                   /homes/alaudah/anaconda2/var/cache/fontconfig/4be9850f182b35c1350b6bbf2e42601c-le64.cache-7
7ff3419f9000-7ff3419fb000 r--s 00000000 08:01 10094056                   /homes/alaudah/anaconda2/var/cache/fontconfig/30a99c4256905863f7aa12b5e873c27c-le64.cache-7
7ff3419fb000-7ff3419fc000 r--s 00000000 08:01 10094055                   /homes/alaudah/anaconda2/var/cache/fontconfig/087e1975ba9a574b140bb1df193bf770-le64.cache-7
7ff3419fc000-7ff341a00000 r--s 00000000 08:01 10094054                   /homes/alaudah/anaconda2/var/cache/fontconfig/6aa41aa22e18b8fa06a12da28ea9c28b-le64.cache-7
7ff341a00000-7ff341a0b000 r--s 00000000 08:01 10094053                   /homes/alaudah/anaconda2/var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-7
7ff341a0b000-7ff341a0d000 r--s 00000000 08:01 10094052                   /homes/alaudah/anaconda2/var/cache/fontconfig/99e8ed0e538f840c565b6ed5dad60d56-le64.cache-7
7ff341a0d000-7ff341a16000 r--s 00000000 08:01 10094051                   /homes/alaudah/anaconda2/var/cache/fontconfig/a6d8cf8e4ec09cdbc8633c31745a07dd-le64.cache-7
7ff341a16000-7ff341a1c000 r--s 00000000 08:01 10094050                   /homes/alaudah/anaconda2/var/cache/fontconfig/2cd17615ca594fa2959ae173292e504c-le64.cache-7
7ff341a1c000-7ff341a1d000 r--s 00000000 08:01 10094049                   /homes/alaudah/anaconda2/var/cache/fontconfig/0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-7
7ff341a1d000-7ff341a32000 r--s 00000000 08:01 10094048                   /homes/alaudah/anaconda2/var/cache/fontconfig/04aabc0a78ac019cf9454389977116d2-le64.cache-7
7ff341a32000-7ff341a33000 r--s 00000000 08:01 10094047                   /homes/alaudah/anaconda2/var/cache/fontconfig/1ac9eb803944fde146138c791f5cc56a-le64.cache-7
7ff341a33000-7ff341a34000 r--s 00000000 08:01 10094046                   /homes/alaudah/anaconda2/var/cache/fontconfig/b95bc8ffbebda2bbdae4265e45b8178d-le64.cache-7
7ff341a34000-7ff341a38000 r--s 00000000 08:01 10094045                   /homes/alaudah/anaconda2/var/cache/fontconfig/385c0604a188198f04d133e54aba7fe7-le64.cache-7
7ff341a38000-7ff341a39000 r--s 00000000 08:01 10094044                   /homes/alaudah/anaconda2/var/cache/fontconfig/9c956a7723ca69a44b382d9179c9802f-le64.cache-7
7ff341a39000-7ff341a3a000 r--s 00000000 08:01 10094043                   /homes/alaudah/anaconda2/var/cache/fontconfig/dc05db6664285cc2f12bf69c139ae4c3-le64.cache-7
7ff341a3a000-7ff341a3b000 r--s 00000000 08:01 10094041                   /homes/alaudah/anaconda2/var/cache/fontconfig/5d1cca7074f29429a8d18692746c2426-le64.cache-7
7ff341a3b000-7ff341a3e000 r--s 00000000 08:01 10094040                   /homes/alaudah/anaconda2/var/cache/fontconfig/767a8244fc0220cfb567a839d0392e0b-le64.cache-7
7ff341a3e000-7ff341a3f000 r--s 00000000 08:01 10094039                   /homes/alaudah/anaconda2/var/cache/fontconfig/4794a0821666d79190d59a36cb4f44b5-le64.cache-7
7ff341a3f000-7ff341a40000 r--s 00000000 08:01 10094038                   /homes/alaudah/anaconda2/var/cache/fontconfig/9eae20f1ff8cc0a7d125749e875856bd-le64.cache-7
7ff341a40000-7ff341a43000 r--s 00000000 08:01 10094037                   /homes/alaudah/anaconda2/var/cache/fontconfig/bf2c1853a9e9b00bb02fe2e9bcf1e201-le64.cache-7
7ff341a43000-7ff341a48000 r--s 00000000 08:01 10094036                   /homes/alaudah/anaconda2/var/cache/fontconfig/8801497958630a81b71ace7c5f9b32a8-le64.cache-7
7ff341a48000-7ff341a83000 r--s 00000000 08:01 10094035                   /homes/alaudah/anaconda2/var/cache/fontconfig/365b55f210c0a22e9a19e35191240f32-le64.cache-7
7ff341a83000-7ff341a84000 r--s 00000000 08:01 10094034                   /homes/alaudah/anaconda2/var/cache/fontconfig/bab58bb527bb656aaa9f116d68a48d89-le64.cache-7
7ff341a84000-7ff341a8b000 r--s 00000000 08:01 10094033                   /homes/alaudah/anaconda2/var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-7
7ff341a8b000-7ff341a93000 r--s 00000000 08:01 10094032                   /homes/alaudah/anaconda2/var/cache/fontconfig/bf3b770c553c462765856025a94f1ce6-le64.cache-7
7ff341a93000-7ff341a94000 r--s 00000000 08:01 10094031                   /homes/alaudah/anaconda2/var/cache/fontconfig/56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-7
7ff341a94000-7ff341a95000 r--s 00000000 08:01 10094030                   /homes/alaudah/anaconda2/var/cache/fontconfig/b9d506c9ac06c20b433354fa67a72993-le64.cache-7
7ff341a95000-7ff341a9b000 r--s 00000000 08:01 10094029                   /homes/alaudah/anaconda2/var/cache/fontconfig/b47c4e1ecd0709278f4910c18777a504-le64.cache-7
7ff341a9b000-7ff341a9e000 r--s 00000000 08:01 10094028                   /homes/alaudah/anaconda2/var/cache/fontconfig/14d493b97896515cad3840ba4896e372-le64.cache-7
7ff341a9e000-7ff341aa6000 r--s 00000000 08:01 10094027                   /homes/alaudah/anaconda2/var/cache/fontconfig/52f7bdb7ce746bfd7eaa1985bd9cfa93-le64.cache-7
7ff341aa6000-7ff341aa9000 r--s 00000000 08:01 10094026                   /homes/alaudah/anaconda2/var/cache/fontconfig/e49e89034d371f0f9de17aab02136486-le64.cache-7
7ff341aa9000-7ff341aab000 r--s 00000000 08:01 10094025                   /homes/alaudah/anaconda2/var/cache/fontconfig/4b14b093aebc79c320de5e86ae1d3314-le64.cache-7
7ff341aab000-7ff341aac000 r--s 00000000 08:01 10094024                   /homes/alaudah/anaconda2/var/cache/fontconfig/8aec10f4cc8391dcef22ca549f1e4354-le64.cache-7
7ff341aac000-7ff341abf000 r--s 00000000 08:01 10094023                   /homes/alaudah/anaconda2/var/cache/fontconfig/d52a8644073d54c13679302ca1180695-le64.cache-7
7ff341abf000-7ff341ac0000 r--s 00000000 08:01 10094022                   /homes/alaudah/anaconda2/var/cache/fontconfig/551ecf3b0e8b0bca0f25c0944f561853-le64.cache-7
7ff341ac0000-7ff341acb000 r--s 00000000 08:01 10094017                   /homes/alaudah/anaconda2/var/cache/fontconfig/d589a48862398ed80a3d6066f4f56f4c-le64.cache-7
7ff341acb000-7ff341b2c000 r-xp 00000000 08:01 9319                       /homes/alaudah/anaconda2/plugins/imageformats/libqwebp.so
7ff341b2c000-7ff341d2c000 ---p 00061000 08:01 9319                       /homes/alaudah/anaconda2/plugins/imageformats/libqwebp.so
7ff341d2c000-7ff341d2d000 r--p 00061000 08:01 9319                       /homes/alaudah/anaconda2/plugins/imageformats/libqwebp.so
7ff341d2d000-7ff341d2f000 rw-p 00062000 08:01 9319                       /homes/alaudah/anaconda2/plugins/imageformats/libqwebp.so
7ff341d2f000-7ff341d30000 rw-p 00000000 00:00 0 
7ff341d30000-7ff341d35000 r-xp 00000000 08:01 9317                       /homes/alaudah/anaconda2/plugins/imageformats/libqwbmp.so
7ff341d35000-7ff341f34000 ---p 00005000 08:01 9317                       /homes/alaudah/anaconda2/plugins/imageformats/libqwbmp.so
7ff341f34000-7ff341f35000 r--p 00004000 08:01 9317                       /homes/alaudah/anaconda2/plugins/imageformats/libqwbmp.so
7ff341f35000-7ff341f36000 rw-p 00005000 08:01 9317                       /homes/alaudah/anaconda2/plugins/imageformats/libqwbmp.so
7ff341f36000-7ff341f9f000 r-xp 00000000 08:01 9321                       /homes/alaudah/anaconda2/plugins/imageformats/libqtiff.so
7ff341f9f000-7ff34219e000 ---p 00069000 08:01 9321                       /homes/alaudah/anaconda2/plugins/imageformats/libqtiff.so
7ff34219e000-7ff34219f000 r--p 00068000 08:01 9321                       /homes/alaudah/anaconda2/plugins/imageformats/libqtiff.so
7ff34219f000-7ff3421a2000 rw-p 00069000 08:01 9321                       /homes/alaudah/anaconda2/plugins/imageformats/libqtiff.so
7ff3421a2000-7ff3421a7000 r-xp 00000000 08:01 9313                       /homes/alaudah/anaconda2/plugins/imageformats/libqtga.so
7ff3421a7000-7ff3423a6000 ---p 00005000 08:01 9313                       /homes/alaudah/anaconda2/plugins/imageformats/libqtga.so
7ff3423a6000-7ff3423a7000 r--p 00004000 08:01 9313                       /homes/alaudah/anaconda2/plugins/imageformats/libqtga.so
7ff3423a7000-7ff3423a8000 rw-p 00005000 08:01 9313                       /homes/alaudah/anaconda2/plugins/imageformats/libqtga.so
7ff3423a8000-7ff3423b4000 r-xp 00000000 08:01 9322                       /homes/alaudah/anaconda2/plugins/imageformats/libqjpeg.so
7ff3423b4000-7ff3425b3000 ---p 0000c000 08:01 9322                       /homes/alaudah/anaconda2/plugins/imageformats/libqjpeg.so
7ff3425b3000-7ff3425b4000 r--p 0000b000 08:01 9322                       /homes/alaudah/anaconda2/plugins/imageformats/libqjpeg.so
7ff3425b4000-7ff3425b5000 rw-p 0000c000 08:01 9322                       /homes/alaudah/anaconda2/plugins/imageformats/libqjpeg.so
7ff3425b5000-7ff3425bc000 r-xp 00000000 08:01 9320                       /homes/alaudah/anaconda2/plugins/imageformats/libqico.so
7ff3425bc000-7ff3427bb000 ---p 00007000 08:01 9320                       /homes/alaudah/anaconda2/plugins/imageformats/libqico.so
7ff3427bb000-7ff3427bc000 r--p 00006000 08:01 9320                       /homes/alaudah/anaconda2/plugins/imageformats/libqico.so
7ff3427bc000-7ff3427bd000 rw-p 00007000 08:01 9320                       /homes/alaudah/anaconda2/plugins/imageformats/libqico.so
7ff3427bd000-7ff3427c6000 r-xp 00000000 08:01 9314                       /homes/alaudah/anaconda2/plugins/imageformats/libqicns.so
7ff3427c6000-7ff3429c5000 ---p 00009000 08:01 9314                       /homes/alaudah/anaconda2/plugins/imageformats/libqicns.so
7ff3429c5000-7ff3429c6000 r--p 00008000 08:01 9314                       /homes/alaudah/anaconda2/plugins/imageformats/libqicns.so
7ff3429c6000-7ff3429c7000 rw-p 00009000 08:01 9314                       /homes/alaudah/anaconda2/plugins/imageformats/libqicns.so
7ff3429c7000-7ff3429cd000 r-xp 00000000 08:01 9316                       /homes/alaudah/anaconda2/plugins/imageformats/libqgif.so
7ff3429cd000-7ff342bcd000 ---p 00006000 08:01 9316                       /homes/alaudah/anaconda2/plugins/imageformats/libqgif.so
7ff342bcd000-7ff342bce000 r--p 00006000 08:01 9316                       /homes/alaudah/anaconda2/plugins/imageformats/libqgif.so
7ff342bce000-7ff342bcf000 rw-p 00007000 08:01 9316                       /homes/alaudah/anaconda2/plugins/imageformats/libqgif.so
7ff342bcf000-7ff342bda000 r-xp 00000000 08:01 9315                       /homes/alaudah/anaconda2/plugins/imageformats/libqdds.so
7ff342bda000-7ff342dd9000 ---p 0000b000 08:01 9315                       /homes/alaudah/anaconda2/plugins/imageformats/libqdds.so
7ff342dd9000-7ff342dda000 r--p 0000a000 08:01 9315                       /homes/alaudah/anaconda2/plugins/imageformats/libqdds.so
7ff342dda000-7ff342ddb000 rw-p 0000b000 08:01 9315                       /homes/alaudah/anaconda2/plugins/imageformats/libqdds.so
7ff342ddb000-7ff342de0000 r-xp 00000000 08:01 9318                       /homes/alaudah/anaconda2/plugins/imageformats/libqsvg.so
7ff342de0000-7ff342fe0000 ---p 00005000 08:01 9318                       /homes/alaudah/anaconda2/plugins/imageformats/libqsvg.so
7ff342fe0000-7ff342fe1000 r--p 00005000 08:01 9318                       /homes/alaudah/anaconda2/plugins/imageformats/libqsvg.so
7ff342fe1000-7ff342fe2000 rw-p 00006000 08:01 9318                       /homes/alaudah/anaconda2/plugins/imageformats/libqsvg.so
7ff342fe2000-7ff342fe3000 ---p 00000000 00:00 0 
7ff342fe3000-7ff3437e3000 rw-p 00000000 00:00 0 
7ff3437e3000-7ff3437ff000 r-xp 00000000 08:01 9327                       /homes/alaudah/anaconda2/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7ff3437ff000-7ff3439fe000 ---p 0001c000 08:01 9327                       /homes/alaudah/anaconda2/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7ff3439fe000-7ff3439ff000 r--p 0001b000 08:01 9327                       /homes/alaudah/anaconda2/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7ff3439ff000-7ff343a00000 rw-p 0001c000 08:01 9327                       /homes/alaudah/anaconda2/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
7ff343a00000-7ff343a05000 r-xp 00000000 08:01 10887060                   /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7ff343a05000-7ff343c04000 ---p 00005000 08:01 10887060                   /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7ff343c04000-7ff343c05000 r--p 00004000 08:01 10887060                   /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7ff343c05000-7ff343c06000 rw-p 00005000 08:01 10887060                   /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7ff343c06000-7ff343c0f000 r-xp 00000000 08:01 10887052                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7ff343c0f000-7ff343e0e000 ---p 00009000 08:01 10887052                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7ff343e0e000-7ff343e0f000 r--p 00008000 08:01 10887052                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7ff343e0f000-7ff343e10000 rw-p 00009000 08:01 10887052                   /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7ff343e10000-7ff343e11000 ---p 00000000 00:00 0 
7ff343e11000-7ff344611000 rw-p 00000000 00:00 0 
7ff344611000-7ff3446ff000 r-xp 00000000 08:01 9312735                    /homes/alaudah/anaconda2/lib/libiconv.so.2.5.1
7ff3446ff000-7ff3448fe000 ---p 000ee000 08:01 9312735                    /homes/alaudah/anaconda2/lib/libiconv.so.2.5.1
7ff3448fe000-7ff344900000 rw-p 000ed000 08:01 9312735                    /homes/alaudah/anaconda2/lib/libiconv.so.2.5.1
7ff344900000-7ff344904000 r-xp 00000000 08:01 1446531                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7ff344904000-7ff344b03000 ---p 00004000 08:01 1446531                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7ff344b03000-7ff344b04000 r--p 00003000 08:01 1446531                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7ff344b04000-7ff344b05000 rw-p 00004000 08:01 1446531                    /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7ff344b05000-7ff344b06000 r-xp 00000000 08:01 10887039                   /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7ff344b06000-7ff344d05000 ---p 00001000 08:01 10887039                   /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7ff344d05000-7ff344d06000 r--p 00000000 08:01 10887039                   /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7ff344d06000-7ff344d07000 rw-p 00001000 08:01 10887039                   /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7ff344d07000-7ff344d93000 r-xp 00000000 08:01 10898023                   /usr/local/MATLAB/R2017a/bin/glnxa64/libfreetype.so.6.11.1
7ff344d93000-7ff344f92000 ---p 0008c000 08:01 10898023                   /usr/local/MATLAB/R2017a/bin/glnxa64/libfreetype.so.6.11.1
7ff344f92000-7ff344f98000 rw-p 0008b000 08:01 10898023                   /usr/local/MATLAB/R2017a/bin/glnxa64/libfreetype.so.6.11.1
7ff344f98000-7ff344fd5000 r-xp 00000000 08:01 9314028                    /homes/alaudah/anaconda2/lib/libfontconfig.so.1.9.2
7ff344fd5000-7ff3451d4000 ---p 0003d000 08:01 9314028                    /homes/alaudah/anaconda2/lib/libfontconfig.so.1.9.2
7ff3451d4000-7ff3451d6000 r--p 0003c000 08:01 9314028                    /homes/alaudah/anaconda2/lib/libfontconfig.so.1.9.2
7ff3451d6000-7ff3451db000 rw-p 0003e000 08:01 9314028                    /homes/alaudah/anaconda2/lib/libfontconfig.so.1.9.2
7ff3451db000-7ff3451e4000 r-xp 00000000 08:01 10887078                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7ff3451e4000-7ff3453e3000 ---p 00009000 08:01 10887078                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7ff3453e3000-7ff3453e4000 r--p 00008000 08:01 10887078                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7ff3453e4000-7ff3453e5000 rw-p 00009000 08:01 10887078                   /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7ff3453e5000-7ff3453fb000 r-xp 00000000 08:01 10886911                   /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7ff3453fb000-7ff3455fa000 ---p 00016000 08:01 10886911                   /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7ff3455fa000-7ff3455fb000 r--p 00015000 08:01 10886911                   /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7ff3455fb000-7ff3455fc000 rw-p 00016000 08:01 10886911                   /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7ff3455fc000-7ff3455ff000 rw-p 00000000 00:00 0 
7ff3455ff000-7ff345606000 r-xp 00000000 08:01 10887031                   /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7ff345606000-7ff345805000 ---p 00007000 08:01 10887031                   /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7ff345805000-7ff345806000 r--p 00006000 08:01 10887031                   /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7ff345806000-7ff345807000 rw-p 00007000 08:01 10887031                   /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7ff345807000-7ff345808000 r--s 00000000 08:01 10094021                   /homes/alaudah/anaconda2/var/cache/fontconfig/8a687c406b77f27d99abfeeba937fcce-le64.cache-7
7ff345808000-7ff34580d000 r--s 00000000 08:01 10094020                   /homes/alaudah/anaconda2/var/cache/fontconfig/75ad6aa2358a85f0de2c8ee4837e8227-le64.cache-7
7ff34580d000-7ff34580e000 r--s 00000000 08:01 10094019                   /homes/alaudah/anaconda2/var/cache/fontconfig/ac2cf712d852da827a87a9baf682f5b9-le64.cache-7
7ff34580e000-7ff345810000 r--s 00000000 08:01 10094018                   /homes/alaudah/anaconda2/var/cache/fontconfig/65f976e5259cbe6dc7697b8648396239-le64.cache-7
7ff345810000-7ff345814000 r--s 00000000 08:01 10094016                   /homes/alaudah/anaconda2/var/cache/fontconfig/246184dc75a16901ca37d96895904249-le64.cache-7
7ff345814000-7ff345822000 r--s 00000000 08:01 10094008                   /homes/alaudah/anaconda2/var/cache/fontconfig/198d8fcf01c96d0cf813f74fd759bdb7-le64.cache-7
7ff345822000-7ff345825000 r--s 00000000 08:01 10094005                   /homes/alaudah/anaconda2/var/cache/fontconfig/75114ca45c98e8a441da0ff356701271-le64.cache-7
7ff345825000-7ff345830000 r--s 00000000 08:01 10094004                   /homes/alaudah/anaconda2/var/cache/fontconfig/83bf95040141907cd45bb53cf7c1c148-le64.cache-7
7ff345830000-7ff345842000 r--s 00000000 08:01 10094003                   /homes/alaudah/anaconda2/var/cache/fontconfig/9b89f8e3dae116d678bbf48e5f21f69b-le64.cache-7
7ff345842000-7ff345849000 r--s 00000000 08:01 10094000                   /homes/alaudah/anaconda2/var/cache/fontconfig/53d14c92082a93e67d5078324eb314ca-le64.cache-7
7ff345849000-7ff345932000 r-xp 00000000 08:01 10898337                   /usr/local/MATLAB/R2017a/bin/glnxa64/libQt5XcbQpa.so.5.5.1
7ff345932000-7ff345b31000 ---p 000e9000 08:01 10898337                   /usr/local/MATLAB/R2017a/bin/glnxa64/libQt5XcbQpa.so.5.5.1
7ff345b31000-7ff345b3a000 rw-p 000e8000 08:01 10898337                   /usr/local/MATLAB/R2017a/bin/glnxa64/libQt5XcbQpa.so.5.5.1
7ff345b3a000-7ff345b3c000 r-xp 00000000 08:01 9291                       /homes/alaudah/anaconda2/plugins/platforms/libqxcb.so
7ff345b3c000-7ff345d3c000 ---p 00002000 08:01 9291                       /homes/alaudah/anaconda2/plugins/platforms/libqxcb.so[1]    30179 abort (core dumped)  spyder
x,

**What steps will reproduce the problem?**
I've tried all the following solutions, and none worked
1. reinstalled spyder (conda remove / conda install)
2. spyder --reset 
3. reinstalled all qt related packages

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6.0 
* Operating system: Ubuntu 16.04

**Comment by ccordoba12** [comment]
As part of your error there is this line

    /usr/local/MATLAB/R2017a/bin/glnxa64/....

so I'd say your error seems to be the fault of Matlab, because it adds Qt5 libraries to PATH and they got mixed with Anaconda's Qt5 ones. And I say Matlab, because Anaconda *doesn't* add its Qt5 libraries to PATH.

**Comment by yalaudah** [comment]
@ccordoba12 I removed the Qt libraries from my PATH, but I still get the same error above (except for the lines referencing Matlab. Any ideas how to fix this?

**Comment by ccordoba12** [comment]
Sorry, I don't have more ideas.
