### ISSUE TITLE
Add a second set of shortcuts for easy use with macOS

### ISSUE THREAD

**Issue by castielle** [spyder-ide/spyder#4551]
For the Mac touch bar, the function keys are off by default.

Make it so Spyder can be registered with Keyboard preferences to always show function keys  by default.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is going to be addressed in Spyder 4.

**Comment by goanpeca** [comment]
@jnsebgosselin this is probably related to your work

**Comment by ccordoba12** [comment]
Duplicate of #10854
