### ISSUE TITLE
Spyder error (Arch linux)

### ISSUE THREAD

**Issue by alabd14313** [spyder-ide/spyder#4552]
Hello!
I have this error in arch linux (both git and official version):
`
raceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/usr/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 43, in <module>
    from PyQt4.QtWebKit import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'
`

**Comment by ccordoba12** [comment]
Please update to Qt5/PyQt5. That should solve your problem.

**Comment by JohnRobson** [comment]
I reinstalled (updated): pyqt5-common python2-pyqt5 python-pyqt5 python-qtpy qt5-webkit qt4 qt5-base qt5 qt5-tools python-qtawesome python-qtpy.

Don't work, same error.

**Comment by ccordoba12** [comment]
Another person mentioned that this is caused by the latest version of Pandas. So you need to downgrade to Pandas 0.19.2 to fix this problem, or uninstall PyQt4 from your system and leave only PyQt5.

Those are you two choices.

**Comment by JohnRobson** [comment]
Both options are very bad because of dependencies. Maybe Spyder should use only PyQt5 and sure, the new Pandas version.

**Comment by ccordoba12** [comment]
This problem was caused by Pandas, not us. It's generated because they are not safely importing PyQt4.

So your third choice is to wait for a new Pandas version.

**Comment by JohnRobson** [comment]
@ccordoba12, You are right.

sudo python -m pip install --upgrade pandas

Solved this problem.
>>> import pandas as pd
>>> pd.__version__
'0.20.2'

**Comment by JohnRobson** [comment]
@ccordoba12, You are right. Pandas 0.20.2 Solved this problem. Thank you

**Comment by ccordoba12** [comment]
No problem, glad to be of help!

**Comment by quiquevisuet** [comment]
On ArchLinux, I was running Spyder 2 and 3 without any trouble. After updated the system Spyder3 gave me the same error posted above. Spyder2 was running correctly, but after uninstalled python-pyqt4 I was able to run Spyder3

**Comment by JohnRobson** [comment]
Just Update Pandas, the package "python-pandas" still old (0.20.1) on pacman, so you can do that:

$ sudo pip3 install --upgrade pandas  # update to Pandas 0.20.2

**Comment by Dschoni** [comment]
I solved the problem by doing 'unset QT_API' before running spyder. Spyder 3 seems to run fine using the qt4 pylab backends for compatibility. (Allthough, you have to do '%matplotlib qt' manually to get back interactive pyplot windows instead of inline plots)
