### ISSUE TITLE
Spyder hangs after Introduction Tour

### ISSUE THREAD

**Issue by notuntoward** [spyder-ide/spyder#4553]
## Description

Spyder hangs after doing interactive tour (Help --> Interactive Tour --> Introduction Tour).  Actually, this happens after many things but this one is reproducible.  By 'hang' I mean that it does not respond to the keyboard or mouse.  It's necessary to kill it from TaskManager.

**What steps will reproduce the problem?**

1. start spyder
2. click through interactive tour
3. at the end, click the X on the interactive tour box

**What is the expected output? What do you see instead?**

Spyder goes back to normal operation.

**Please provide any additional information below**

Running on Windows 10 with latest updates as of 6/3/17

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this before releasing 3.2.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
