### ISSUE TITLE
Tiny plots with Graphics backend set to Automatic

### ISSUE THREAD

**Issue by notuntoward** [spyder-ide/spyder#4555]
## Description

On my Surface Pro 4, I have  preferences --> Ipython console --> graphics --> graphics backend set to Automatic.  I also have High DPI enabled.

But the plots are still tiny, with too-small fonts, etc.

**Please provide any additional information below**

Windows 10

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 3.2, I think. Please reopen this issue if that's not the case once we release it (in two or three weeks).
