### ISSUE TITLE
not seeing dynamic images in ipython  console

### ISSUE THREAD

**Issue by abhijitbera95** [spyder-ide/spyder#4560]
## Description of your problem
I am not seeing the dynamic images in ipython console, but it is clearly possible to see in python console
this is the example of program
"
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

fig = plt.figure()

def f(x, y):
    return np.sin(x) + np.cos(y)

x = np.linspace(0, 2 * np.pi, 120)
y = np.linspace(0, 2 * np.pi, 100).reshape(-1, 1)

im = plt.imshow(f(x, y), animated=True)

def updatefig(*args):
    global x, y
    x += np.pi / 15.
    y += np.pi / 20.
    im.set_array(f(x, y))
    return im,

ani = animation.FuncAnimation(fig, updatefig, interval=50, blit=True)
plt.show()
"

This will create a dynamic output , instead it is showing a fixed image in ipythion console.But, in the python console, expected output is coming
 

## Versions and main components

* Spyder Version:3.14
* Python Version:2.7.13
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system:Windows 10

**Comment by ccordoba12** [comment]
You need to change your graphics backend before running your code. You can do that interactively by running

    In [1]: %matplotlib qt5

or use that setting permanently by going to

    Preferences > IPython console > Graphics > Graphics backend

and selecting `Automatic` there.
