### ISSUE TITLE
Cmd+Left, Cmd+Right doesn't work in IPython console 

### ISSUE THREAD

**Issue by GandalfSaxe** [spyder-ide/spyder#4563]
## Description of your problem
Can't skip to beginning/end of line with the otherwise OS-wide Cmd+Left/Right

**What steps will reproduce the problem?**

1. Go to IPython console
2. Enter multiple words separated by space
3. To try go to beginning of line or end of line with Cmd+left and Cmd+right

**What is the expected output? What do you see instead?**
The expected output is for the text field to behave as any other standard text field in macOS; i.e. Cmd+left/right skips to beginning/end of line.

**Please provide any additional information below**
Curiously enough, skip previous/next word using Opt+left/right is working.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.3
* Qt Version:
* PyQt Version:
* Operating system: macOS Sierra 10.12.5

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
The shortcuts in the IPython console are hardcoded in its widget and can't redefined by Spyder because that widget is part of an external project called Qtconsole.

**Comment by ccordoba12** [comment]
It'd be great if you could come up with a pull request for this functionality. The Qtconsole repository is here

https://github.com/jupyter/qtconsole

Else I don't think this is going to be implemented.
