### ISSUE TITLE
Static code analysis can't find numpy members

### ISSUE THREAD

**Issue by notuntoward** [spyder-ide/spyder#4566]
## Description

The code analysis in Spyder flags errors for some numpy functions, for example, logical_and (see screenshot)

**What steps will reproduce the problem?**

Hit F8 in Spyder

**What is the expected output? What do you see instead?**

![image](https://cloud.githubusercontent.com/assets/3851891/26794676/f54a8710-4a22-11e7-837e-1ec6f6f3c51c.png)

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Spyder runs a package called `pylint` to do static code analysis. So we simply report the messages generated by `pylint`, so we can fix this bug.

Please report it in the Pylint repo instead:

https://github.com/PyCQA/pylint

**Comment by chrhorn** [comment]
I ran into the same problem. The cause is that Spyder uses an outdated version of pylint (1.6.4). The current version (1.7.1) seems to have solved this issue, see https://github.com/PyCQA/pylint/issues/1282, and other Problems related to python 3.6.

Unfortunatly the newer Version is currently unavailable in the conda channels.

**Comment by ccordoba12** [comment]
@chrhorn, thanks for the info. We'll see what we can do about it.
