### ISSUE TITLE
My ipython console is not working.I have tried every method possible still facing the same issue

### ISSUE THREAD

**Issue by iteachmachines** [spyder-ide/spyder#4570]
## Description of your problem

**What steps will reproduce the problem?**

1. Write a simple print 2+2
2. Then run file
3. And it doesn't shows the expecting result

**What is the expected output? What do you see instead?**
The expected output is 4 instead of this i see 
runfile('/home/student/.config/spyder/temp.py', wdir='/home/student/.config/spyder')
Traceback (most recent call last):

  File "<ipython-input-3-cc4b8eeefba9>", line 1, in <module>
    runfile('/home/student/.config/spyder/temp.py', wdir='/home/student/.config/spyder')

NameError: name 'runfile' is not defined

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.1.4
* Python Version:2.7
* Qt Version:
* PyQt Version:
* Operating system:Ubuntu 14.04LTS 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by iteachmachines** [comment]
> ``

**Comment by ccordoba12** [comment]
Please post a screenshot of the IPython console pane after you click on the *Run file* button.

**Comment by iteachmachines** [comment]
/home/student/Pictures/Screenshot from 2017-06-07 03:08:46.png

**Comment by iteachmachines** [comment]
http://imgur.com/a/422fd @ccordoba12

**Comment by ccordoba12** [comment]
How did you install Spyder?

**Comment by iteachmachines** [comment]
sudo apt get-install spyder

**Comment by ccordoba12** [comment]
But neither Spyder 3.1.4 nor IPython 5.3.0 are still not part of Ubuntu, and those are the versions you report you're using:

https://packages.ubuntu.com/zesty/spyder
https://packages.ubuntu.com/zesty/ipython

**Comment by iteachmachines** [comment]
You can see here i am using those two versions only http://imgur.com/a/Ypfpw

**Comment by ccordoba12** [comment]
Yes, I can see that, so you have to have installed those versions using pip and not apt-get.

But pip installation is really for experts, so I'm sorry to say it, but it's up to you to figure out where that error is coming from.

Our recommendation is: unless you really know what you're doing and have a good knowledge of the Python scientific stack, please use Anaconda.

**Comment by iteachmachines** [comment]
I am using anaconda.Now i have integrated it with pycharm and its working better then spyder.

**Comment by ccordoba12** [comment]
Ok, good for you.
