### ISSUE TITLE
Spyder not opening - file '.spyder.py3' not found

### ISSUE THREAD

**Issue by eduazeredo** [spyder-ide/spyder#4571]
## Description of your problem

**What steps will reproduce the problem?**

1. I open Anaconda
2. I launch Spyder
3. The initializing screen appears
4. The message stating Spyder crashed during last session appears
5. Spyder screen opens, and then quits.

**What is the expected output? What do you see instead?**

It was expected Spyder kept running

**Please provide any additional information below**
This happened after I request Spyder to reset its settings to default.

I followed the instructions that asked to reset spyder in the command line. However, the Terminal informs the file has not been found.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3
* Qt Version:
* PyQt Version:
* Operating system: Mac OS Sierra 10.12.3

**Comment by ccordoba12** [comment]
Please run

    spyder --reset

and try again.

**Comment by eduazeredo** [comment]
The reset command worked this time.

But when opening spyder, it went the same. Opens and then closes some seconds later.

**Comment by eduazeredo** [comment]
Just tried the reset command once again.

Now it worked and Spyder is back to life here!
