### ISSUE TITLE
Make a unique instance of the file switcher

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#4575]
The idea here is to make a generic file switcher attached to the main window that could display the files of the plugins, for example the Editor and the Notebook (and others if needed).

The file switcher should display a list with the possible files grouped by plugin like:

**Editor**
_file1_
_file2_

**Notebook**
_notebook1_
_notebook2_

The plugins should give the file switcher a list with the current files that are managing.

@ccordoba12 
@goanpeca , what do you think?

**Comment by ccordoba12** [comment]
+1 from me too. Please start to work on it.

**Comment by rlaverde** [comment]
This is somehow related to #4368, maybe you could address it too.

**Comment by dalthviz** [comment]
A pre-preview:

![gfileswitcher](https://user-images.githubusercontent.com/16781833/27264264-5bed0b56-5440-11e7-8fb9-0e8ea135ac65.gif)

**Comment by ccordoba12** [comment]
@dalthviz, it looks great! What's missing for a PR?

**Comment by dalthviz** [comment]
@ccordoba12  I need to clean the code a little bit (code style, comments, variable names, etc.), but It should be ready soon 👍, also probably write the prerequisites and steps to attach a plugin to the file switcher, and do some testing to see if this changes work for the whole functionality of the file switcher (search by file and by symbol)
