### ISSUE TITLE
Object inspector (Ctrl + I) fails with decorated function

### ISSUE THREAD

**Issue by PertuyF** [spyder-ide/spyder#4578]
## Description

When loading interactive help of a decorated function using Object inspector (Ctrl + I), the docstring of the decorator is displayed instead of that of the function.
More precisely, only some part of the decorator's docstring is displayed for standard decorators like `@staticmethod`, but nothing appears for custom decorators.

**Minimal working example**

```python
def decorator(func):
    """Decorator docstring"""
    pass

@decorator
def test():
    """Docstring test"""
    pass

@staticmethod
def test2():
    """Docstring test2"""
    pass
```

**What is the expected output? What do you see instead?**

Using `Ctrl + I` on `test` will lead to a blank window in the help panel.
Using `Ctrl + I` on `test2` will display this:
```
staticmethod(function) -> method

Convert a function to be a static method.

A static method does not receive an implicit first argument. To declare a static method, use this idiom:

class C:
@staticmethod def f(arg1, arg2, ...):

...
It can be called either on the class (e.g. C.f()) or on an instance (e.g. C().f()). The instance is ignored except for its class.

Static methods in Python are similar to those found in Java or C++. For a more advanced concept, see the classmethod builtin.
```

While  using `Ctrl + I` directly on `staticmethod` will display the complete help as rendered using [docrepr](https://github.com/spyder-ide/docrepr).

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: RHEL7 64-bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this after we release 3.2.

**Comment by beckss** [comment]
The issue still exists in 3.3.0

**Comment by ccordoba12** [comment]
@beckss, that's why is still open, sorry.

**Comment by goanpeca** [comment]
Does not apply anymore for 4.0.0

<img width="479" alt="Screen Shot 2019-11-25 at 14 23 17" src="https://user-images.githubusercontent.com/3627835/69571048-28f36080-0f8f-11ea-97df-9273dff3d6e0.png">

Closing
