### ISSUE TITLE
Multiple whitespaces as a separator in variable explorer

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#4581]
Currently the data import wizard doesn't play nicely with text data with multiple spaces as delimiters(or maybe I don't play nicely with the data importer ;-). This is common in fixed width data sets like this:
```
FIRST  LAST           STATE     TELEPHONE      AGE   WEIGHT
John   Smith          WA        418-Y11-4111    26    3.0456
Mary   Hartford       CA        319-Z19-4341     5   13.5687
Evan   Nolan          IL        219-532-c301   145   45.7890
```
Putting a `' '` (a space) in a the 'other' text box gives this:

![screenshot from 2017-06-09 22-54-23](https://user-images.githubusercontent.com/10513354/27000139-d82be01e-4d67-11e7-8744-60a5ccf6eaf8.png)

When it could give this:

![screenshot from 2017-06-09 22-59-21](https://user-images.githubusercontent.com/10513354/27000146-f6d744e0-4d67-11e7-8119-212dbf0b212f.png)

I can submit a pull request to add a "whitespace" radio button to have this option, if you think that's a good direction to go.

**Comment by ccordoba12** [comment]
> I can submit a pull request to add a "whitespace" radio button to have this option, if you think that's a good direction to go.

Sounds good to me, but I don't understand where that option would be placed.

**Comment by bcolsen** [comment]
something like this:

![image](https://user-images.githubusercontent.com/10513354/27006211-92650a18-4deb-11e7-8812-11f877270537.png)
