### ISSUE TITLE
Finder extension not showing text in sidebar when opening files [macOS 10.13 High Sierra beta]

### ISSUE THREAD

**Issue by GandalfSaxe** [spyder-ide/spyder#4586]
## Description of your problem

**What steps will reproduce the problem?**

1. Choose File->Open... 

**What is the expected output? What do you see instead?**
Expect: The finder extension showing directories.
See: Missing text by the folders in the sidebar.

**Please provide any additional information below**
Error message in terminal:
`objc[1845]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/FinderKit (0x14630f200) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1273c4c00). One of the two will be used. Which one is undefined.`

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I don't understand too well what's this about, sorry. So could you post a screenshot of your problem, please?

**Comment by GandalfSaxe** [comment]
<img width="828" alt="screen shot 2017-06-11 at 23 58 14" src="https://user-images.githubusercontent.com/12127864/27014901-2dc6cb4c-4f02-11e7-8639-ce47ba598fe8.png">

Sure. As you see here, the directory titles are not showing in the sidebar of the finder view extension. I know it's a very early dev beta of macOS High Sierra, but I'd thought I'd let you know anyway. Luckily you can still kind of guess what to click, and the main contents still show in the middle.

**Comment by ccordoba12** [comment]
This looks like a Qt issue and not a Spyder one. I guess it'll be fixed once Qt is updated to support macOS 10.13.

In the meantime, there's nothing we can do about it, sorry.
