### ISSUE TITLE
Spyder-py2 crash on MacOS  10.12.4 (Sierra) : BUG IN LIBTRACE: MH not found

### ISSUE THREAD

**Issue by sebma** [spyder-ide/spyder#4588]
Hi,

Spyder-py2 crashes on MacOS 10.12.4 (Sierra) when I launch the Spyder-Py2.app application.

Can you please help me to fix this problem ?

## Description of your problem

**What steps will reproduce the problem?**

1. 
curl -O https://bitbucket.org/spyder-ide/spyderlib/downloads/spyder-2.3.8-py2.7.dmg
2. 
open spyder-2.3.8-py2.7.dmg
3. 
Drag'n'drop of Spyder-Py2.app in /Applications & Double clic on /Applications/Spyder-Py2.app

**What is the expected output? 

I expect the Spyder window to open

What do you see instead?**

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
dyld: in dlopen()
BUG IN LIBTRACE: MH not found

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.8
* Python Version: 2.7
* Qt Version: qt: stable 5.9.0 (bottled), HEAD [keg-only] (from brew)
* PyQt Version: pyqt: stable 5.8.2 (bottled) (from brew)
* Operating system: MacOS  10.12.4 (Sierra)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Unfortunately, Spyder-py2 crashes therefore I don't get the time to do this.

**Comment by sebma** [comment]
![spyder-2 3 8-py2 7](https://user-images.githubusercontent.com/4569306/27025915-6539451e-4f5c-11e7-9937-38adedc04b1b.png)

**Comment by ccordoba12** [comment]
Thanks for reporting, but our DMGs for Python 2 and Spyder 2.3 are not supported in the latest versions of macOS, sorry.

Besides

1. Spyder 2.3 is not supported anymore.
2. We don't have plans to create DMGs for Python 2 in the future.

**Comment by sebma** [comment]
I think I know why it crashes, Spyder2-py2 needs PyQt4 (not PyQt5).

The PyQt4 binaries for Macos is [here](https://sourceforge.net/projects/pyqtx/files/).

**Comment by ccordoba12** [comment]
Our DMG comes with PyQt4, so that's not really the problem. The problem is Qt4/PyQt4 were not updated to work with macOS 10.10 and higher, so there's nothing we can do about it, sorry.

**Comment by sebma** [comment]
I see.

Do you have a binary release of Spyder 3 for Python 2 for macos 10.12 ?

**Comment by ccordoba12** [comment]
No, and it won't be any because PyQt5 wheel packages are produced for Python 3 only, and we need those packages to create our DMG.

If you want to keep using Python 2, please download and install Anaconda for Python 2.

**Comment by sebma** [comment]
Anaconda seems a bit too big for my needs : ''[Over 150 packages are automatically installed with Anaconda.](https://docs.continuum.io/anaconda/#packages-available-in-anaconda)".

I think I have no other choice than switch to Python3.

What is you latest Spyder package release for Macos ?

**Comment by ccordoba12** [comment]
> Anaconda seems a bit too big for my needs

You can also install Miniconda, which just install the minimal packages needed for conda to run, and then install only the libraries that you need.

> What is you latest Spyder package release for Macos

3.0.2 is our latest DMG and 3.1.4 is our latest version. Sorry, but I don't have more time to update our DMG, so we rely on Anaconda (very few people have asked for an update too).

**Comment by sebma** [comment]
Just installed Miniconda and then installed Spyder with conda.

conda seems kinda of cool, thanks a lot :) !
