### ISSUE TITLE
"Replace all" command has an edge-case where it misses a replace

### ISSUE THREAD

**Issue by mat2py** [spyder-ide/spyder#4594]
## Description of your problem
Using the "Replace all" option in the editor can miss a string to replace, based on the steps below

**What steps will reproduce the problem?**

1. Have two of the same strings on a line to be replaced (i.e. `testing123 = testing12 + 99`), along with others in the file
2. Double click on the second string of the line (testing12), perform the "replace all" action
3. This replaces all occurrences of "testing12" *except* the one on the same line and previous to the first replaced string (the testing12 part of testing123).

Spyder: 3.1.4

**Comment by timhoffm** [comment]
Not reproducible in the current 3.2.x development branch.

## Version and main components

* Spyder Version: 3.2.5.dev0 11afa31
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
