### ISSUE TITLE
Editors not gaining focus when changing by tab click

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4597]
With 2 or more files open on the editor, clicking on different tabs should give the focus to the editor (cursor should start blinking) and the outline explorer should update because of this focus gain. Currently the focus is not given to the editor. This does works with the file switcher.

This is on 3.x but not on 3.1.x.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one. Since this is a bug that appeared in 3.x, please use `git bisect` to detect the commit that introduced it.

**Comment by rlaverde** [comment]
I introduce this bug in https://github.com/spyder-ide/spyder/pull/3946/commits/2228e83b656a476683f27e9ddd5e234a08135be6 while fixing #1170 giving the focus  to the Editor caused the unwanted scrolling, should we revert it?

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
No, we should find a new way to give focus to the current tab. #1170 was very annoying.

@rlaverde, please work on this one.
