### ISSUE TITLE
Spyder launches, hangs on forever and fails to start

### ISSUE THREAD

**Issue by SaintNazaire** [spyder-ide/spyder#4605]
## Description of your problem

From the Anaconda command prompt I launch Spyder. Spyder launches, even loading and issuing a warning that my previous session crashed and that I should consider resetting (which I eventually did without result). The process carries on and then hangs on forever, failing to start (i.e. open the working windows with code, console, variables etc.)

PS: I have used with satisfaction Anaconda and Spyder for months now without any issue, cannot understand what's wrong.

**What steps will reproduce the problem?**

1. Open Anaconda command prompt
2. `Spyder`

**What is the expected output? What do you see instead?**

Spyder should strart, instead Spyder launches, loads, then hangs on and fails to start, can see Python running in the background from the task manager. If I repeat the operation, more python.exe processes run in the background with 0% processors, memory and disk usage.

**Please provide any additional information below**

Tried to reset Spyder

`Spyder --reset`

Spyder resets properly but still fails to start

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.13
* Anaconda Version: 4.3.21
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10, 

## Dependencies

Cannot access help to check dependencies, Spyder fails to start

**Comment by ccordoba12** [comment]
Please open a terminal (cmd.exe) and run

    spyder --show-console

then report here any errors you're seeing there.

**Comment by SaintNazaire** [comment]
I'm afraid I elected to uninstall & reinstall Anaconda 2-4.4.0 which eliminated the problem and prevents me to replicate the issue.

**Comment by SaintNazaire** [comment]
Sorry but I'm back in business with my issue.
After ONE single Spyder start-up it just decided it wanted to do it all over again.

> (C:\Users\me\Anaconda2) C:\Users\me>spyder --show-console
> Traceback (most recent call last):
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
>     mainwindow = run_spyder(app, options, args)
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
>     main.setup()
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 873, in setup
>     from spyder.plugins.ipythonconsole import IPythonConsole
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 60, in <module>
>     from spyder.widgets.ipythonconsole import ClientWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\widgets\ipythonconsole\__init__.py", line 12, in <module>
>     from .debugging import DebuggingWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 16, in <module>
>     from qtconsole.rich_jupyter_widget import RichJupyterWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 14, in <module>
>     from .jupyter_widget import JupyterWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\qtconsole\jupyter_widget.py", line 19, in <module>
>     from IPython.lib.lexers import IPythonLexer, IPython3Lexer
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\__init__.py", line 48, in <module>
>     from .core.application import Application
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\core\application.py", line 25, in <module>
>     from IPython.core import release, crashhandler
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
>     from IPython.core import ultratb
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 128, in <module>
>     from IPython.utils.terminal import get_terminal_size
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\utils\terminal.py", line 22, in <module>
>     from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
> ImportError: No module named shutil_get_terminal_size
> 
> (C:\Users\me\Anaconda2) C:\Users\me>

So then I tried the following:

> (C:\Users\me\Anaconda2) C:\Users\me>conda install shutil_get_terminal_size
> Fetching package metadata ...........
> 
> PackageNotFoundError: Package missing in current win-64 channels:
>   - shutil_get_terminal_size
> 
> Close matches found; did you mean one of these?
> 
>     shutil_get_terminal_size: get_terminal_size
 
Btw Spyder issue or Anaconda issue?

**Comment by ccordoba12** [comment]
Did you use pip to install packages in your Anaconda environment? Because that's usually the cause of the error you're seeing.

**Comment by SaintNazaire** [comment]
No I didn't I conda installed it

> conda install spyder

**Comment by SaintNazaire** [comment]
Still stuck, apparently someone else in India has reported exactly the same issue
https://groups.google.com/forum/#!topic/spyderlib/aMP8diWUL4Q

**Comment by ccordoba12** [comment]
It's very strange that this happens in a clean installation. However, this should solve your problem for good

    conda install get_terminal_size

**Comment by SaintNazaire** [comment]
Hi,

Thank you, actually I did that already (cf comment [very long] comment above).

Today I checked again, indeed a new version of get_terminal_size is out so it updated but I retried and it didn't work.

> (C:\Users\me\Anaconda2) C:\Users\me>spyder --show-console
> Traceback (most recent call last):
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
>     mainwindow = run_spyder(app, options, args)
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
>     main.setup()
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\app\mainwindow.py", line 873, in setup
>     from spyder.plugins.ipythonconsole import IPythonConsole
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 60, in <module>
>     from spyder.widgets.ipythonconsole import ClientWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\widgets\ipythonconsole\__init__.py", line 12, in <module>
>     from .debugging import DebuggingWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 16, in <module>
>     from qtconsole.rich_jupyter_widget import RichJupyterWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 14, in <module>
>     from .jupyter_widget import JupyterWidget
>   File "C:\Users\me\Anaconda2\lib\site-packages\qtconsole\jupyter_widget.py", line 19, in <module>
>     from IPython.lib.lexers import IPythonLexer, IPython3Lexer
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\__init__.py", line 48, in <module>
>     from .core.application import Application
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\core\application.py", line 25, in <module>
>     from IPython.core import release, crashhandler
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\core\crashhandler.py", line 28, in <module>
>     from IPython.core import ultratb
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\core\ultratb.py", line 128, in <module>
>     from IPython.utils.terminal import get_terminal_size
>   File "C:\Users\me\Anaconda2\lib\site-packages\IPython\utils\terminal.py", line 22, in <module>
>     from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
> ImportError: No module named shutil_get_terminal_size

Any other idea?

Many thanks,

Benoit

**Comment by SaintNazaire** [comment]
Actually I found a solution which was to **conda** reinstall ipython and **pip** reinstall backports.shutil_get_terminal_size :

> conda uninstall ipython
> conda install python
> pip uninstall backports.shutil_get_terminal_size
> pip install backports.shutil_get_terminal_size

For more info I suggest to consult the following issues:
- [ipython/ipython/#9656](https://github.com/ipython/ipython/issues/9656)
- [ipython/ipython/#9815]( https://github.com/ipython/ipython/issues/9815)
- [chrippa/backports.shutil_get_terminal_size/#9](https://github.com/chrippa/backports.shutil_get_terminal_size/issues/9)

For some reason however Spyder then issues a warning that nbconvert isn't installed whereas both conda and pip install nbconvert show that nbconvert is fully installed and up to date...

**Comment by SaintNazaire** [comment]
Actually the cleanest of solution can [be found here](https://stackoverflow.com/questions/37232446/ipython-console-cant-locate-backports-shutil-get-terminal-size-and-wont-load).

```
conda install --force ipython
conda install --force backports
```

**Comment by Dabar999** [comment]
Hello!
Spyder was running properly on my PC with Windows 10 until last Windows update two days ago. When i try to run Spyder from Anaconda i got error message:
[15248:13072:1123/124942.758:ERROR:network_change_notifier_win.cc(156)] WSALookupServiceBegin failed with: 8
Assertion failed: Connection reset by peer [10054] (C:\Users\nwani\Downloads\mc3\conda-bld\zeromq_1531316860385\work\src\ip.cpp:485)
[3972:15528:1123/125005.511:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)
Does anybody knows how to fix this problem.
THX!
