### ISSUE TITLE
Turtle libary not working

### ISSUE THREAD

**Issue by okprogrammer** [spyder-ide/spyder#4609]
the above mention code is not working properly. i am writing it again
import turtle
turtle.forward(100)
turtle.right(80)
turtle.forward(100)

**Comment by ccordoba12** [comment]
Please stop opening more issues about the same problem. There's no need for that and you're only making us waste our time.

I think you need to run the command

    In [1]: %gui tk

before running any turtle code. Please try that and let us know if it works for you.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
