### ISSUE TITLE
Goto previous cell behaviour is different than other IDEs

### ISSUE THREAD

**Issue by liavassif** [spyder-ide/spyder#4611]
## Description of your problem
Goto previous cell should go to previous cell only when the cursor is at the first line of the cell (the cell marker), otherwise it should go to the beginning of the current cell (same as in MATLAB, Atom etc.)

While indeed "goto previous cell" is the definition of the action, its actual action should be dependant on the cursor location.

**What steps will reproduce the problem?**

1. Create 2 cells with several lines each
2. Place the cursor at the second line (or any other line except the cell marker) of the second cell
3. Select Goto previous cell 

**What is the expected output? What do you see instead?**
The cursor should be placed at the current cell marker rather than the cell marker of the previous cell

**Please provide any additional information below**

## Versions and main components

* Spyder Version: spyder from GIT obtained on 1/Jun/2017
* Python Version: 3.5.2
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system:Linux

**Comment by ccordoba12** [comment]
Thanks for reporting. @dalthviz, let's make our cell go to next/previous shortcuts to follow the same behavior as in Matlab.
