### ISSUE TITLE
Scroll down/up scrolls down twice

### ISSUE THREAD

**Issue by liavassif** [spyder-ide/spyder#4619]
## Description of your problem
Scroll down/up performs two consecutive calls to scroll instead of a single one

**What steps will reproduce the problem?**

1. Place the cursor on the first line of a file in the editor pane
2. Press scroll down (PageDown key) 

**What is the expected output? What do you see instead?**
The cursor should be at line 26 (assuming the scroll is 25 lines), but instead it is at line 52

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.2.0dev (3.x branch) and 4.0.0dev (master)
* Python Version:3.5.2
* Qt Version:5.6.2
* PyQt Version:5.6
* Operating system:Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by rlaverde** [comment]
This is caused by this change https://github.com/spyder-ide/spyder/commit/738f8e190f4256ff26f741af4c8e7bed20ace460#diff-b19a1c3b49c9057f7bf2edae2a53747dR2710 keyPressEvent is called twice (at keyPress and also at keyRelease)

Should it be `super(CodeEditor, self).KeyReleaseEvent(event)`?

@goanpeca

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.
