### ISSUE TITLE
Spyder Remote development -- Pycharm equivalent?

### ISSUE THREAD

**Issue by AkiNikolaidis** [spyder-ide/spyder#4623]
This is more of a question than a problem: 

I love using Spyder for all of my python dev- but I'm still using Pycharm Professional for remote development. I would love to be able to use Spyder to do the same- editing and running code and having it run on a remote server through an SFTP. 

Is there an easy way to set this up? Or perhaps a tutorial etc that can show me the way?

Thanks again- great project here.

Aki

**Comment by ccordoba12** [comment]
This is not possible right now, sorry. We'll try to work on this after we release Spyder 4 (during Q1 of next year).
