### ISSUE TITLE
Regex lookbehind not working

### ISSUE THREAD

**Issue by jrouces** [spyder-ide/spyder#4625]
## Description of your problem

Regex lookbehinds seem to be broken. For instance this: 
(?<!a)whatever 
does not match
whereverwhatever

I have tested it in Sublime text first to ensure I am not missing something, and it works there.

If it is of any help, the lookbehinds seem to work when using (?<!\n)

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.2
* Qt Version: 4.8.7
* PyQt Version: PyQt4  API v2  4.11.4 on Linux
* Operating system: Ubuntu 16.04.2 LTS

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  3.4.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this after we release Spyder 3.2.

**Comment by goanpeca** [comment]
I tested this on https://pythex.org/

It does not work there either. I don't think this is a Spyder issue.

<img width="916" alt="Screen Shot 2019-11-29 at 23 31 40" src="https://user-images.githubusercontent.com/3627835/69895572-6d209100-1300-11ea-9547-2d1cef31f4c3.png">
