### ISSUE TITLE
problem with spyder

### ISSUE THREAD

**Issue by shimshim2** [spyder-ide/spyder#4629]
## Description

**What steps will reproduce the problem?**

```python
a = 2
b = 4
B = [[1.2,2],[3,4.5]]
print B[0]
c=B[0]
if c==list:
    print a
``` 

**What is the expected output? What do you see instead?**
the right answer is 
[1.2,2]
2
but it shows just
[1.2,2]

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
You need to change your last two lines to be

```python
if type(c) == list:
    print a
```
