### ISSUE TITLE
command for switch-tab uses non-obvious ordering 

### ISSUE THREAD

**Issue by stefanseefeld** [spyder-ide/spyder#4640]
## Description of your problem

Using `<ctrl>-<tab>` to cycle through my open editor tabs uses a highly non-obvious ordering. I expect it to use the visual order, i.e. left-to-right for `<ctrl>-<tab>`, and right-to-left for `<ctrl>-<shift>-<tab>`

(It would also be nice to make the keyboard shortcut configurable in the preferences.)

**Comment by rlaverde** [comment]
Changing tabs with `Ctrl+Tab` `Ctrl+Shift+Tab` has been improved in #4302 It'll use "most recent used" order. (It'll be part of Spyder3.2)
Also you can change Tabs in visual order using `Ctrl+AvPag` `Ctrl+RePag`

>It would also be nice to make the keyboard shortcut configurable in the preferences

 `Ctrl+Tab` `Ctrl+Shift+Tab` shortcuts are configurable, with the only restriction that they should include `Ctrl`

**Comment by stefanseefeld** [comment]
Hmm, neither `<Ctrl>-<PgUp>` nor `<Ctrl>-<PgDown>` have any effect for me.
I'm looking at the "Keyboards shortcuts" table in the "preferences" dialog. What is the name for the "switch tab" commands that are configurable ?

**Comment by ccordoba12** [comment]
That's not part of Spyder 3.1.4 (our latest public release). As @rlaverde said, it *will* be part of Spyder once our 3.2 version is released.
