### ISSUE TITLE
Add a check_compatibility method to PluginMixin

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4641]
On 3.x

https://github.com/spyder-ide/spyder/blob/master/spyder/api/plugins.py

Create a new method for `class SpyderPluginWidget(PluginWidget):`

```python
# For instance Qt4 can be checked here or other things...

    def check_compatibility(self):
        """
        This method can be implemented to check compatibility of plugin on a given os.

        `message` should give information in case of non compatibility:
        For example: 'This plugin does not work with Qt4'
        """
        message = ''
        valid = True
        return valid, message

```

On top of this we need to change the loading of plugins to load it only if compatible

@ccordoba12, @andfoy, @rlaverde  comments, ideas?

**Comment by andfoy** [comment]
I was thinking that in some cases, this function might be not called at all, for example, on Spyder Terminal we don't even expose the Plugin at all if the current Qt backend if different from ``PyQt5`` ((spyder_terminal/__init__.py)[https://github.com/spyder-ide/spyder-terminal/blob/master/spyder_terminal/__init__.py])

**Comment by goanpeca** [comment]
in that case maybe we dont need such method ?

**Comment by andfoy** [comment]
Maybe, it should be defined on each plugin's ``__init__.py``

**Comment by goanpeca** [comment]
What I don't like here, is that we have an orphan PLUGIN_CLASS, I would make it `None` at least

```
from qtpy import PYQT5

PLUGIN_CLASS = None
if PYQT5:
    from .terminalplugin import TerminalPlugin as PLUGIN_CLASS

```

**Comment by andfoy** [comment]
>  What I don't like here, is that we have an orphan PLUGIN_CLASS, I would make it None at least

To be changed on 3.1.2!

**Comment by ccordoba12** [comment]
@andfoy, the idea is to make changes in `spyder-terminal` so that is a message is shown when people try to run it with PyQt4.

So its compatibility is to depend on PyQt5.

**Comment by goanpeca** [comment]
`PLUGIN_COMPATIBLE = (True, '')` then? and check that in spyder

In the case of spyder-terminal check for Qt4 and build a message accordingly

**Comment by andfoy** [comment]
So should we remove that try... except block instead?

**Comment by goanpeca** [comment]
>So should we remove that try... except block instead?

Probably

**Comment by ccordoba12** [comment]
Yes, that's the idea, and use `check_compatibility` instead.

But @goanpeca, then `check_compatibility` should be the first thing to run in `register_plugin`, right? That way, if compatibility is not satisfied, the plugin would not continue the registering process, and will show a (non-modal) QMessageBox instead.

**Comment by ccordoba12** [comment]
Sorry, `check_compatibility` has to be called in the `__init__` method of SpyderPluginWidget:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/plugins/__init__.py#L539

That way it will be run every time a plugin is created.

@dalthviz, please add the `check_compatibility` method to SpyderPluginWidget with @goanpeca suggestion, then call it in its `__init__` method.
