### ISSUE TITLE
New colour scheme results in unreadable tracebacks

### ISSUE THREAD

**Issue by dhirschfeld** [spyder-ide/spyder#4642]
On spyder master a recent change to the color scheme has resulted in unreadable tracebacks:
![image](https://user-images.githubusercontent.com/881019/27502758-d760ea96-58b9-11e7-95e3-815845a8ae2a.png)

This seems similar to what was being used in jupyterlab:

jupyterlab/jupyterlab#807
jupyterlab/jupyterlab#2384

In particular, the discussion in 2384 seems relevant.

**Comment by ccordoba12** [comment]
I can't reproduce this, at least on Linux, sorry.

Please take a look at it on Windows.

**Comment by ccordoba12** [comment]
Do you have set some options about this in your IPython config files?

**Comment by dhirschfeld** [comment]
This was on my work computer on windows x64, Anaconda Python 3.6.

I don't set anything to do with colours for ipython - just use whatever the defaults are. Will check on my home computer also Win x64 / py36

**Comment by dhirschfeld** [comment]
On my home PC (latest master) I'm not seeing it. Will double check at work and post more details...

**Comment by ccordoba12** [comment]
Ok, please do. I think the problem could arise because we're not detecting the background color of the current color scheme correctly. But we're just using a Pygments function for that...

**Comment by dhirschfeld** [comment]
So on my work PC I checked to see if the problem was still there and it was. I then updated to the latest master and the problem appears to be gone.
```
C:\dev\packages\spyder [master ≡]
λ git pull
remote: Counting objects: 402, done.
remote: Compressing objects: 100% (10/10), done.
Receiving objects:  93% (374/402), 84.00 KiB | 66.00 KiB/s
Receiving objects: 100% (402/402), 146.24 KiB | 66.00 KiB/s, done.
Resolving deltas: 100% (308/308), completed with 70 local objects.
From https://github.com/spyder-ide/spyder
   243b390d..b7d651bb  master     -> upstream/master
   3507b148..38518184  3.x        -> upstream/3.x
Updating 243b390d..b7d651bb
<snip>
```
So it looks like somewhere between [`243b390d` and `b7d651bb`](https://github.com/spyder-ide/spyder/compare/243b390d76e62dbe6f0722ef65b63f24cdb7ad4a...b7d651b) the problem has been fixed.

Since I can't repro on master I'll close this as fixed.
