### ISSUE TITLE
Non responsive dialog box (in 3.0.0) warning of newer version of Spyder 

### ISSUE THREAD

**Issue by JWGoodwin** [spyder-ide/spyder#4652]
## Description
Non-responsive dialog box warning of outdated version of Spyder

**What steps will reproduce the problem?**

1.  Launched Spyder from Win7 Start Menu item under Anaconda3.
2.  It produces among other things a popup dialog box warning that there is a new version 3.1.4. 
I pasted in a screenshot of it below.
3. This dialog is totally non-responsive. Neither the links nor the OK button respond.

**What is the expected output? What do you see instead?**
I thought the blue text would be hyperlinks and the OK button would close the dialog.
**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```
![image](https://user-images.githubusercontent.com/29611427/27519191-a75973a0-59bc-11e7-91a9-a90f739741d8.png)

**Comment by ccordoba12** [comment]
This was fixed several months ago. Please update to 3.1.4.

**Comment by JWGoodwin** [comment]
How? Where? The links that tell how to do that are precisely my problem?
