### ISSUE TITLE
Spyder3.exe crashes on launch.

### ISSUE THREAD

**Issue by shubhanknigam** [spyder-ide/spyder#4653]
## Description of your problem
When trying to run Spyder3.exe in Python36-32/Scripts, the Spyder console opens for a few seconds then crashes with following error report.

**Problem signature:**
  Problem Event Name:	APPCRASH
  Application Name:	pythonw.exe
  Application Version:	3.6.1150.1013
  Application Timestamp:	58d169c2
  Fault Module Name:	Qt5WebEngineCore.dll
  Fault Module Version:	5.8.0.0
  Fault Module Timestamp:	588148ea
  Exception Code:	80000003
  Exception Offset:	000a8384
  OS Version:	6.1.7601.2.1.0.768.11
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**What steps will reproduce the problem?**

1. Installed Python directly from website. Installed QtPy and Spyder using cmdline.
2. Double clicked Spyder3.exe in Scripts folder.
3. 

**What is the expected output? What do you see instead?**
The IDE doesn't start, although a screen appears for a few seconds resulting in a crash.

![issue spyder screenshot](https://user-images.githubusercontent.com/29694673/27519928-1a8bfa32-5a1c-11e7-87e4-1f65938d7763.png)

![issue spyder error screenshot](https://user-images.githubusercontent.com/29694673/27519972-2d1afa9e-5a1d-11e7-933f-09904b508656.png)

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.1.4
* Python Version:3.6.1
* Qt Version: Not sure, Used pip to install PyQt through wheels so it installed all the dependencies automatically.
* PyQt Version:5.8.2
* Operating system:Win7 Starter

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please follow this https://github.com/spyder-ide/spyder/issues/3736#issuecomment-262682824

If that doesn't work, please download and install Anaconda. Pip installations are for experts only, so if you want to continue towards that path, it's up to you to solve your problem, sorry.
