### ISSUE TITLE
kernel crash when debugging

### ISSUE THREAD

**Issue by CodingThinking** [spyder-ide/spyder#4654]
## Description of your problem

**What steps will reproduce the problem?**

when I debug in ipython console, the kernel is very easy to crash when I debug step by step.  The crash comes not regularly and almostly when debugging 5 or 6 steps.  The crash comes quicker when my values have a large dimension. Then problem comes since version 3.1.3.  I don't know what leads to this crashing.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1 Anaconda 4.4.0
* Qt Version:
* PyQt Version:
* Operating system: win 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be fixed in Spyder 3.2, to be released in a couple of weeks.

In the meantime, the way to avoid this problem is to *not* have print statements in your code. That's what makes the kernel to be restarted.
