### ISSUE TITLE
runfile/wdir error 

### ISSUE THREAD

**Issue by macobjiller** [spyder-ide/spyder#4656]
## Description

I'm trying to open datasets in spyder, but I keep receiving a runfile/wdir error. I'm trying to take a Udemy course on machine learning.

**What steps will reproduce the problem?**

1. import pandas, numpy, matplotlib.pyplot
2. file = open('Data.csv')
3. error

**What is the expected output? What do you see instead?**

runfile('/Users/MacobJiller/Desktop/Machine Learning/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------/data_preprocessing_template.py', wdir='/Users/MacobJiller/Desktop/Machine Learning/Machine Learning A-Z Template Folder/Part 1 - Data Preprocessing/Section 2 -------------------- Part 1 - Data Preprocessing --------------------')

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
As I said in your other bug, this is not an error. It's the command used by Spyder to run a file in its consoles.

**Comment by diegogocruzcamacho** [comment]
Entonces como se soluciona este no error?

**Comment by ccordoba12** [comment]
No hay forma de solucionarlo. Es decir, es necesario ejecutar el comando `runfile` en la terminal de IPython para poder correr archivos desde el editor.

**Comment by diegogocruzcamacho** [comment]
![image](https://user-images.githubusercontent.com/47399015/78521550-d5d8b800-778f-11ea-87a5-3179df75608c.png)

**Comment by diegogocruzcamacho** [comment]
en el IDE de python?

**Comment by MatParr** [comment]
> No hay forma de solucionarlo. Es decir, es necesario ejecutar el comando `runfile` en la terminal de IPython para poder correr archivos desde el editor.

hey @ccordoba12, in reference to this issue above, our last conversation you mentioned downgrading to version 7.32.0. But that had no impact on the processing, the issues still persist and I'm not sure how to interpret such. There are limited details on google and via ghit, stacks and I even sent an email to python.org hoping for a positive response. 

I am stuck at this point @ccordoba12 and would really appreciate your input here to solve this. On my old 2012 mac catalina 10.15.7 this code is functioning but it takes days to process as per the limitation in CPU resources. To mitigate such, i upgraded to Monterery 12.3 2021 a newer mac and the same code is not functioning. The output seems to not be printed here in the multi-processing to generate the output and I am not sure how to interpret this, or what to do to move forward! 

**Can you assist me here, once more please?**
*AND THANK you Loadsss pal!!**

No matter what I do or deploy, it is not working!!!!

 I also tried rolling back to the older packages to match that of the older Mac computer but Spyder via the ANACONDA Navigator keeps requesting upgrades be implemented and causes major initialisation errors with the python app from that perspective. AND I have no choice but to upgrade to the new versions but stay within the range of what you recommended that last time we communicated.

Pretty pretty please, you input is necessary here or some professional, this is a tad frustrating to remedy as i'm wrestling with all the packages to fine a solution which is strange as it runs without package manipulation or me selecting such on the old mac.

'''
**My code that I tried:**

1. **!ipython 3dcnn9.ipy --batch 120 --epoch 150 --videos ./dataset/ --nclass 8 --output 3dcnnresult/ --color True --skip False --depth 12**

2.**!ipython 3dcnn9.py --batch 120 --epoch 150 --videos ./dataset/ --nclass 8 --output 3dcnnresult/ --color True --skip False --depth 12

3.**!python 3dcnn9.py --batch 120 --epoch 150 --videos ./dataset/ --nclass 8 --output 3dcnnresult/ --color True --skip False --depth 12**

4.**%run 3dcnn9.ipy --batch 120 --epoch 150 --videos ./dataset/ --nclass 8 --output 3dcnnresult/ --color True --skip False --depth 12**
'''

'''
Package dependency:
Python 3.8.13 (default, Mar 28 2022, 06:16:26) 
Type "copyright", "credits" or "license" for more information.

IPython 8.1.1 -- An enhanced Interactive Python.


!pip install tensorflow
!pip install tfLearn
!pip install tqdm
!pip install keras
!pip install sklearn
!pip install numpy
!pip install PyQt5
!pip install --user pyqtwebengine==5.12
!pip install matplotlib
!pip install importlib
!pip install scikit-plot
!pip install graphviz
!pip install pydot
!pip install pyparsing
!pip install argparse
!pip install opencv-python
!pip install python-ffmpeg
!pip install pyperclip
!pip install geopy
!pip install plotly
!pip install logstash
!pip install pandas
!pip install seaborn
!pip install ipyparallel
'''

'''
Errors (or what I interpret as an error):

runfile('/Users/symbadian/opt/3DCNNtesting/packages.ipy', wdir='/Users/symbadian/opt/3DCNNtesting')
[TerminalIPythonApp] WARNING | Unrecognized alias: 'batch', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'epoch', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'videos', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'nclass', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'output', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'color', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'skip', it will have no effect.
[TerminalIPythonApp] WARNING | Unrecognized alias: 'depth', it will have no effect.
'''
