### ISSUE TITLE
Display issue, small mouse cursor in Spyder 3.1.4 on 4K display on ubuntu 16.04.

### ISSUE THREAD

**Issue by ryscet** [spyder-ide/spyder#4657]
## The mouse cursor is very small when hoovering over Spyder window on a HiDPI (4K) display

**What steps will reproduce the problem?**

1.  Use spyder 3.1.4 from anaconda
2.  Use on ubuntu 16.04 with a 4K display
![issue](https://user-images.githubusercontent.com/12048852/27547959-c97d18c0-5a97-11e7-9646-9df82b565aba.png)

**What is the expected output? What do you see instead?**
Mouse cursor changes size from regular to very small when entering over the Spyder window.
The mouse cursor should not change size when inside Spyder window. It should remain the same size.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6
* Qt Version: ??
* PyQt Version: 5
* Operating system: ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. I think this will be fixed in Spyder 3.2, to be released in a couple of weeks.

If not, please reopen this issue.

**Comment by jdnz** [comment]
I still have this issue using Spyder 3.2.8 on Ubuntu 16.04 with a 4K display, should it be fixed?
