### ISSUE TITLE
MATPLOTLIB does not work at all :-(

### ISSUE THREAD

**Issue by N4th4lie** [spyder-ide/spyder#4660]
Hello world! my MATPLOTLIB does not work at all  :-(

**What steps will reproduce the problem?**

import numpy as np
import matplotlib.pyplot as plt
v=np.array([1,3,2,4])
plt.figure()
plt.plot(v)
plt.show()

**What is the expected output? What do you see instead?**
A simple grah is expected.
I see nothingn, only shown the adress : <matplotlib.figure.Figure at 0xb86a0f0>

## Version and main components

* Spyder Version: 3.1.2 
* Python Version: 3.5.3
* Qt Versions: 5.7.1, PyQt5 5.7.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

THANK YOU IN ADVANCE FOR HELP!

**Comment by ccordoba12** [comment]
Please run

    %matplotlib inline

in a new IPython console, then run your code again.

**Comment by N4th4lie** [comment]
@ccordoba12 
I've got the same outcome, an address...

**Comment by Legor** [comment]
I can't reproduce your problem. As expected i get a graph shown no matter if i run your code from a script or directly in the ipython shell. I also dont need to add the extra %matplotlib inline.
This is with a fresh install of spyder 3.1.4 but it should work with your version too.

Is there any other output when running the file you didn't show here?

**Comment by N4th4lie** [comment]
Finally I installed the new version of Python :
* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows.
YAY graphics appears normly!!!

@ccordoba12  & @Legor : Merci beaucoup 
And special thanks to @dbowsman46 ("create an environment variable named QT_QPA_PLATFORM_PLUGIN_PATH to the path .\Anaconda3\Library\plugins\platforms\ .")
#3740

**Comment by N4th4lie** [comment]
Finally I installed the new version of Python :

Spyder Version: 3.1.4
Python Version: 3.6.1
Qt Versions: 5.6.2, PyQt5 5.6 on Windows.

YAY graphics appear normly!!!
@ccordoba12  & @Legor : Merci beaucoup
And special thanks to @dbowmans46 ("create an environment variable named QT_QPA_PLATFORM_PLUGIN_PATH to the path .\Anaconda3\Library\plugins\platforms\ .")
#3740

**Comment by ccordoba12** [comment]
:+1: glad to know it's working for you now.
