### ISSUE TITLE
Qt application does not show any error

### ISSUE THREAD

**Issue by thoduv** [spyder-ide/spyder#4662]
Hello,

I use Spyder for a very small single-file Qt application, and I find it very convenient. Until a few month ago, when an error happened in the event loop, I could see it in a "console debug" tab, but unfortunately it has now disappeared, and I can't see any error anymore. Is there a workaround you could suggest, or a way to display such errors ?

Thanks !

**What steps will reproduce the problem?**
Running this small script in Spyder will make the problem apparent :
```
import sys
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class Test(QPushButton):
    def __init__(self, parent = None):
        QPushButton.__init__(self, 'click!', parent)
        self.clicked.connect(self.test)
        
    def test(self):
        raise Exception('Error not shown!')

if __name__=="__main__":
    app = QApplication(sys.argv)
    btn = Test()
    btn.show()
    app.exec_()
```

**What is the expected output? What do you see instead?**

Expected output : an exception.
Current output : None

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4 (installed with pip)
* Python Version: Python 2.7.12
* Qt Version: Qt 5.6.1
* PyQt Version: PyQt5 5.5.1
* Operating system: Linux 64 bits

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  1.5.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please start Spyder from a system terminal (bash for Linux) and see if your errors are printed there.

**Comment by thoduv** [comment]
Hello. 
I've tried this too, and error aren't printed in the terminal either. Even with SPIDER_DEBUG=1... 
But what I can see in the terminal are the errors printed to stderr from C extensions (that is another problem, of which I don't know if it is related or not). 

----- Mail original -----

De: "Carlos Cordoba" <notifications@github.com> 
À: "spyder-ide/spyder" <spyder@noreply.github.com> 
Cc: "thoduv" <thoduv@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 27 Juin 2017 16:59:52 
Objet: Re: [spyder-ide/spyder] Qt application does not show any error (#4662) 


Please start Spyder from a system terminal (bash for Linux) and see if your errors are printed there.

**Comment by bcolsen** [comment]
@thoduv I'm not sure "console debug" tab is but when I run your script spyder the error print to the ipython console:

```
In [1]: runfile('/home/bcolsen/.config/spyder/temp.py', wdir='/home/bcolsen/.config/spyder')
Traceback (most recent call last):

  File "/home/user/.config/spyder/temp.py", line 17, in test
    raise Exception('Error not shown!')

Exception: Error not shown!
```
I'm running the latest from Anaconda.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Linux 64-bit


## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Closing because this seems fixed.

**Comment by dgwcambustion** [comment]
I'm struggling with this exact problem, the above test program does not throw an error in the IPython console in Spyder, when run from cmd line it does. I'm running the latest version of Spyder and the above dependencies.
