### ISSUE TITLE
Inspecting Numpy bool arrays in Var. Explorer uses deprecated '-' operator in Numpy

### ISSUE THREAD

**Issue by GKosiba** [spyder-ide/spyder#4663]
## Description of your problem
(..)/site-packages/spyderlib/widgets/arrayeditor.py", line 249, in data
/(self.vmax-self.vmin)
TypeError: numpy boolean subtract, the operator '-', is deprecated, use the bitwise_xor, the '^' operator, or the logical_xor function instead. 
**What steps will reproduce the problem?**

1. import numpy as np
2. test = np.zeros((3,3),dtype='bool')
3. Double click test in variable explorer window

**What is the expected output? What do you see instead?**
Popup window of the array w/ values. Crash (Seg. Fault)

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.5
* Qt Version: 4.8.5
* PyQt Version: 4.11.4
* Operating system: RHEL7

## Dependencies
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.14.0.dev0+03283c2 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. The fix seems simple enough, would you like to submit a pull request for it? If you, please make your PR against our 3.x branch.
