### ISSUE TITLE
Proxy error in Spyder

### ISSUE THREAD

**Issue by amanda759** [spyder-ide/spyder#4668]
I recently reinstalled Anaconda/Spyder so I could upgrade to python 3. I'm having proxy errors in Spyder that I don't have when I run python from terminal.

For example, when I run in the following test code in Spyder:
```python
import requests
print(requests.get('http://google.com'))
```
I get this error:
```
ProxyError: HTTPConnectionPool(host='http', port=80): Max retries exceeded with url: http://google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x1185b40b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)))
```

But the same code runs just fine when I run it from the command line in terminal. I checked my proxy settings and everything is as it should be. How do I fix the proxy settings in Spyder?

I'm running Spyder 3.1.4, Python 3.6 on Mac OS 10.11.6

**Comment by ccordoba12** [comment]
Please start Spyder from a terminal to see if that fixes your problems.

**Comment by amanda759** [comment]
That worked, thanks!
