### ISSUE TITLE
Spyder + ipdb : Invoking history with up/down keyboard arrows and CTRL+R keyboard shortcut does not work on Macosx

### ISSUE THREAD

**Issue by sebma** [spyder-ide/spyder#4677]
## Description of your problem

**What steps will reproduce the problem?**

1. Start Spyder
2. Set a breakpoint in a script, run it and click 'Continue execution until next breakpoint'
3. In ipdb, type the full name of a variable + ENTER
4. Type the UP arrow key to recall the previous line

**What is the expected output?**

The previous line appears

**What do you see instead?**

Nothing happens, like ipdb was not using GNU Readline

**Please provide any additional information below**

* Spyder Version: 3.1.3
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Mac OS X 10.12.5

## Dependencies

jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Ctrl+Up/Down in `ipdb` will work in Spyder 3.2.

Ctrl+R is a readline feature that doesn't work in Spyder because our IPython console is not based on readline.

**Comment by sebma** [comment]
You mean : "Up/Down" instead of "Ctrl+Up/Down", right ?

Last question, why don't you use gnu readline with your IPython ?
