### ISSUE TITLE
Debug: "Run Current Line" past the end of a script doesn't exit the debugger

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#4680]
## Description of your problem
Using "Run Current Line (ctrl-f10)" past the end of a program doesn't exit, but starts debugging in sitecustomize.py

**What steps will reproduce the problem?**

1. start debugging with this script:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
x = 1
```
2. press `ctrl-f10` 2 or 3 times (just past the end of the script) 
3. sitecostomize.py will popup

**What is the expected output? What do you see instead?**
It should end debugging

## Versions and main components

* Spyder Version: 3.x branch
* Python Version: 3.6
* Qt Version: 5.6
* PyQt Version: 5.6
* Operating system:

## Dependencies

cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
It seems a small error, so I'm leaving this one for 3.2.1

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.

We need to detect if we are at the end of the file and stop debugging it that's the case.
