### ISSUE TITLE
Debug: If a breakpoint is on the first line of a script the whole script runs

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#4681]
## Description of your problem
This is also not going to happen too often. 

If a breakpoint is on the first line of a script and there are no other breakpoints, the whole script runs

If a breakpoint is on the first line of a script and there is another breakpoint, the first breakpoint is ignored

**What steps will reproduce the problem?**

1. start debugging with this script:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
x = 1 # <- put break point here
print('I ran')
print('Me too')
print('Me three')
```
2. start debug
3. I get:
```
In [1]: debugfile('/home/user/Documents/debug_test.py', wdir='/home/user/Documents')
> /home/user/Documents/debug_test.py(3)<module>()
      1 #!/usr/bin/env python3
      2 # -*- coding: utf-8 -*-
1---> 3 x = 1 # <- put break point here
      4 print('I ran')
      5 print('Me too')

I ran
Me too
Me three

ipdb> 

In [2]: 
```

**What is the expected output? What do you see instead?**
It should stop at the break point

## Versions and main components

* Spyder Version: 3.x branch
* Python Version: 3.6
* Qt Version: 5.6
* PyQt Version: 5.6
* Operating system:

## Dependencies

cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> This is also not going to happen too often.

Leaving for 3.2.1 then. Thanks for helping us to test our debugger thoroughly.

**Comment by ccordoba12** [comment]
@rlaverde, please take a look at this one. The code that tries to move automatically to the first breakpoint is here:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/plugins/editor.py#L2406-L2408

We need to check if a breakpoint is placed in the first line that is not a comment or part of a docstring to apply it.

**Comment by ccordoba12** [comment]
Reopening because #5086 doesn't address this in all situations.
