### ISSUE TITLE
Feature Request: Syntax highlighting for optional arguments

### ISSUE THREAD

**Issue by ysBach** [spyder-ide/spyder#4683]
I am using Spyder 3.1.4 (Python 3.6.1 64bits on Linux).

I asked [whether it's possible to highlight optional argument in spyder](https://stackoverflow.com/questions/44825446/spyder-syntax-highlighting-for-optional-arguments) and got an answer that it's not possible simply because it's not implemented.

The functionality is implemented to many editors I have used (including Visual Studio Code, Sublime text, and Atom) and I think it's quite useful for people like me. 

I hope this to be implemented in Spyder too.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll see what we can do about this in a future release.
