### ISSUE TITLE
Array editor: Change default float formatter from %.3f to %.6g

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#4684]
Currently this array:
```
a = np.array([3.2e-9,45.6e56,22.3,57666.6,0.00000004])
```
looks like this in the array editor with the default %.3f formatting:

![%.3f](https://user-images.githubusercontent.com/10513354/27760319-cb3428d0-5e01-11e7-8e29-48532b8a7e59.png)

I can't tell what most of those numbers are.

But it could look like this with %.6g formatting:

![screenshot from 2017-07-01 02-04-30](https://user-images.githubusercontent.com/10513354/27760323-e81c03aa-5e01-11e7-9862-8664a746c51c.png)

If you think this is a good idea I should be able to do a PR.

**Comment by jitseniesen** [comment]
I like this.

**Comment by ccordoba12** [comment]
Ok, @bcolsen submit a PR for this.

**Comment by ccordoba12** [comment]
Sorry, I just saw there's already a PR for this.
