### ISSUE TITLE
help

### ISSUE THREAD

**Issue by gitoscarhub** [spyder-ide/spyder#4686]
## Description

**What steps will reproduce the problem?**

1. jedi 0.9.0 (NOK)
2. rope none(NOK)
3. sympy none(NOK) 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 3.5.2
* Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Optional dependencies
```
pyflakes >=0.6.0   :  1.1.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1 (OK)
IPython >=1.0      :  2.4.1 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
pandas >=0.13.1    :  0.17.1 (OK)
sphinx >=0.6.6     :  1.3.6 (OK)
psutil >=0.3       :  3.4.2 (OK)
rope >=0.9.2       :  None (NOK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  None (NOK)
pylint >=0.25      :  1.5.2 (OK)

```

**Comment by bcolsen** [comment]
Well seeing that you are on linux it looks like you may have installed spyder using your distributions packaged version.  

2.3.8 is an older spyder version and spyder 3 is out and is running quite well.

I suggest running the latest version of spyder by downloading the Anaconda Python distribution:
https://www.continuum.io/downloads

**Comment by ccordoba12** [comment]
Closing as 2.3.8 is not supported anymore.
