### ISSUE TITLE
Add command 'clear' to spyder

### ISSUE THREAD

**Issue by crazyBaboon** [spyder-ide/spyder#4688]
## Description of your problem

So far, the only script command to clear the workspace variables is the horrible command:

```
from IPython import get_ipython
get_ipython().magic('reset -sf')
```
I am aware of [this](https://github.com/spyder-ide/spyder/issues/2563), but it really does not address this problem as the "option to "clear all" variables before running file" is still GUI defined and once enabled, it will always clear all the variables for every re-run until the user disables it again. Typically only the scripts that start with 'clear all' are intended to clear the workspace, the other scripts that don't start with 'clear all' are not. Whether the workspace is cleared or not should be defined in the script and not in the GUI preferences.

'clear all' and 'clear' are extremely useful Matlab, GNU Octave, FreeMat and Scilab functions that are not yet implemented in Spyder.

A possible solution would be to create a spyder or Ipython function called `clear all` the would basically call the horrible aforementioned command. What do you guys think?

**Comment by ccordoba12** [comment]
We already added that option in Spyder 3.1, well, not as a function, but as an option to our Run preferences.

You can activate it for your current file by going to the menu

    Run > Configure > General settings

and then selecting

    Clear all variables before execution

If you want to activate it for all files, you need to go to

    Tools > Preferences > Run

and selecting the same option.

----

We are not planning to add a command because it could clearly interfere with `clear` functions defined by our users, so I'm closing this issue.

**Comment by crazyBaboon** [comment]
"We are not planning to add a command because it could clearly interfere with clear functions defined by our users, so I'm closing this issue." What if you called it something different like `clear_all`,`clr_all` or even 'cvw'? Surelly that would not interfere with most users?

**Comment by ccordoba12** [comment]
The command you posted is the right command to use. I don't see the need to add another one to do exactly the same, sorry.

**Comment by crazyBaboon** [comment]
`from IPython import get_ipython
get_ipython().magic('reset -sf')` vs `clr_all`... I think it is because it is just easier to use and commit to memory.

**Comment by ccordoba12** [comment]
Sorry, but if we add a command like that then things won't work outside of Spyder.

**Comment by nbonacchi** [comment]
@crazyBaboon why not add the command to your own library and add it to the PYTHONPATH , you can call it whatever you want :)

**Comment by crazyBaboon** [comment]
"Sorry, but if we add a command like that then things won't work outside of Spyder." Fair enough that is a good point.

**Comment by crazyBaboon** [comment]
I have tested the command
`from IPython import get_ipython
get_ipython().magic('reset -sf')` does not work, i.e. it does not clear the workspace. In addition it makes the variable explorer stop displaying variables. Is this my machine being weird? I am using spyder 3.1.4 and python 3.6.1
