### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by futureer** [spyder-ide/spyder#4690]
## Description of your problem
After starting spyder, the ipython console failed to start
**What steps will reproduce the problem?**

1.  start spyder
2. look at the IPython console area

**What is the expected output? What do you see instead?**
Expect the ipython console start normally, while it doesn't.

**Please provide any additional information below**
IPython version: 6.1.0 it works well in the terminal.
And here is the traceback in the console  panel:
Traceback (most recent call last):
File "/home/tesla/anaconda3/lib/python3.6/site?6?2packages/spyder/utils/ipython/start_kernel.py", line 231, in 
main()
File "/home/tesla/anaconda3/lib/python3.6/site?6?2packages/spyder/utils/ipython/start_kernel.py", line 212, in main
from utils.ipython.spyder_kernel import SpyderKernel
ModuleNotFoundError: No module named 'utils.ipython'; 'utils' is not a package

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.0 64 bits (Anaconda 4.3.1)
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Ubuntu 14.04.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
It seems you have a file called `utils` in your current working directory. Please rename it or move it somewhere else.
