### ISSUE TITLE
Spyder 3.1.4 blacks out progress bar

### ISSUE THREAD

**Issue by CBrauer** [spyder-ide/spyder#4697]
The progress is blacked out. For example:

![image](https://user-images.githubusercontent.com/1317234/27840483-32a7bfaa-60ae-11e7-8280-10f298395d76.png)

Is this a feature?

Charles
## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6
* Qt Version: na
* PyQt Version: na
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
I don't understand this, please be more specific. How is this supposed to run?

**Comment by ccordoba12** [comment]
And what code are you trying to run?

**Comment by CBrauer** [comment]
I am using a machine learning package called h2o.  The code is:

```
import h2o
h2o.init()

data = h2o.load_dataset("C:\Temp\h2o\iris_wheader.csv")
print(data.head())
y = "class"
x = data.names
x.remove(y)
train, test = data.split_frame([0.8])

m = h2o.estimators.deeplearning.H2ODeepLearningEstimator()
m.train(x, y, train)
p = m.predict(test)
print(p)
```
I suspect that h2o uses a special highlighting character when they print the progress text, and therefore Spyder is innocent.  Sorry for the confusion.

**Comment by ccordoba12** [comment]
Yeah, probably that progress bar is only meant to be run in a terminal (bash or cmd.exe) and our IPython console is not a terminal.

So I doubt I can do something about this, sorry.

**Comment by ccordoba12** [comment]
Closing because I don't think we can do something about this one.
