### ISSUE TITLE
File switcher (ctrl+tab) doesn't work

### ISSUE THREAD

**Issue by johnml1135** [spyder-ide/spyder#4702]
## Description of your problem

When I have multiple files open and I press "ctrl+tab" the minimal file switcher appears, but it does not actually switch the files.  The window stays open and will not close.

## Solutions?

When pressing ctrl+tab, it may be nice to have the ctrl+p file switcher appear and to cycle through the files in that way.

## Versions
* Spyder Version:
spyder-3.2.0.dev0-2017-06-16 (from WinPython 2017-02 build2)

**Comment by rlaverde** [comment]
I think this is related to #4619 and was fixed in #4631

**Comment by ccordoba12** [comment]
Ok, thanks @rlaverde for the clarification.

**Comment by ccordoba12** [comment]
> When pressing ctrl+tab, it may be nice to have the ctrl+p file switcher appear and to cycle through the files in that way.

@johnml1135, both work differently, and both are present in other editors (e.g. VSCode). The tab switcher let's you cycle in tab order while the File switcher let's you select a file using a fuzzy search.

**Comment by ccordoba12** [comment]
Besides, I can confirm the Tab switcher is working as expected. You just need to keep pressing Tab to cycle among tabs.
