### ISSUE TITLE
Code folding is wrong on commented lines

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#4708]
The indentation of lines fully commented break the blocs logic. eg:

```
def foo():
# comment
  pass
```

the folding triangle appear on '#'.
Probably they should simply be ignored.

**Comment by rlaverde** [comment]
The actual code folding is based in indentation, this is somehow duplicated of #2845, although a better solution will be to implement a fold detector based on tokens (#4432)

**Comment by sylvain-bougnoux** [comment]
Maybe you just have to treat the commented lines differently allowing indentation change for them without breaking the current block. Then possibly add a dedicated block on successive commented lines.
