### ISSUE TITLE
Wrong Command Executed in Python Console command line

### ISSUE THREAD

**Issue by bigdavesmall** [spyder-ide/spyder#4715]
## Description of your problem
When typing commands in the python console command line, the command I enter is not executed.  Instead, an earlier command is executed.  For example, I run my script.  Then I type x.head() and the script runs again.  I type x.count() and the script runs again.  I type x.shape and the x.head() command finally executes.  

**What steps will reproduce the problem?**

1.  Entering a series of commands in the python console.  
2. 
3. 

**What is the expected output? What do you see instead?**
I expect the command I entered to be executed.  I see the result of a previously entered command.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 8

## Dependencies
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Because of this, and many other errors, the Python console is going to be removed in Spyder **3.2**.

Please see issue #4524 for all our reasons to do it.
