### ISSUE TITLE
Selfcompiled Spyder 2.3.9 fails starting IPython

### ISSUE THREAD

**Issue by aselahi** [spyder-ide/spyder#4718]
## Description of your problem
I manually built Spyder 2.3.9 on Debian9 (because Spyder 3 doesn't support variable exploring during debugging). I started Spyder with `python3 bootstrap.py`. Everything seems to work fine except that the IPython doesn't start. Though I found similar bugs, the error messages were different. Trying to launch IPython, the internal console outputs:

```
File "/opt/compile/spyder/spyderlib/plugins/ipythonconsole.py", line 830, in create_new_client
    menu_actions=self.menu_actions)
  File "/opt/compile/spyder/spyderlib/widgets/ipython.py", line 407, in __init__
    local_kernel=False)
  File "/opt/compile/spyder/spyderlib/widgets/ipython.py", line 175, in __init__
    super(IPythonShellWidget, self).__init__(*args, **kw)
  File "/home/myself/.local/lib/python3.5/site-packages/qtconsole/rich_jupyter_widget.py", line 64, in __init__
    _supported_format = [bytes(f) for f in QtGui.QImageReader.supportedImageFormats()]
  File "/home/myself/.local/lib/python3.5/site-packages/qtconsole/rich_jupyter_widget.py", line 64, in <listcomp>
    _supported_format = [bytes(f) for f in QtGui.QImageReader.supportedImageFormats()]
TypeError: 'bytes' object cannot be interpreted as an integer
```

**What steps will reproduce the problem?**

1. Spyder with `python3 bootstrap.py`
2. Try launching IPython console
3. 

**What is the expected output? What do you see instead?**
Expected a working IPython console, instead error message (see above).

**Please provide any additional information below**

During building, an error occured that either PyQT or PySide is needed, though PyQT **was** installed. After that, I installed PySide and building worked. The problem is that my installed PySide seems to be a binding to **_QT4_**. On the other hand, my installed PyQT is **PyQT 5**. So I'm not sure, which version Spyder is using. Maybe that's the problem?

## Versions and main components

* Spyder Version: 2.3.9
* Python3 Version: 3.5.3
* IPython3 Version: 5.1.0
* Qt Version: PyQT 5.7
* PyQt Version: 5.7.1
* PySide Version: 1.2.2
* Operating system: Debian 9

## Dependencies

IPython >=1.0      :  6.1.0 (OK)
jedi >=0.8.1;<0.9.0:  0.10.2 (NOK)
matplotlib >=1.0   :  2.0.0 (OK)
pandas >=0.13.1    :  0.19.2 (OK)
pep8 >=0.6         :  1.6.2 (OK)
psutil >=0.3       :  5.2.2 (OK)
pyflakes >=0.6.0   :  0.8.1 (OK)
pygments >=1.6     :  2.2.0 (OK)
pylint >=0.25      :  1.6.5 (OK)
qtconsole >=4.0    :  4.3.0 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.6.3 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  16.0.2 (OK)

**Comment by ccordoba12** [comment]
My comments:

1. We don't support Spyder 2.3 anymore, sorry.
2. Exploring variables during debugging will be fixed in Spyder 3.2, to be released in a couple of days.
3. Spyder 2.3 doesn't support PyQt5, so it should be using PySide in your case.
4. PySide is very buggy and we stop supporting it since Spyder 3.
5. Spyder 2.3 doesn't support the latest versions of IPython. I don't even remember which version was the last one it supported.

So I'm closing this issue as *Wont' fix* because there's nothing we can do about it. Please be patient and wait for 3.2, that's my advice.
