### ISSUE TITLE
Corrupted spyder/python installation: unable to import name hashtable

### ISSUE THREAD

**Issue by rdevans0** [spyder-ide/spyder#4724]
I have what I believe to be a corrupted spyder/python installation and am looking for steps to fix it. I believe the issues started when I tried to install spyder.vim. I have tried uninstalling and reinstalling using both apt-get and pip. I'll focus on pip for this ticket. 

**What steps will reproduce the problem?**

1. Uninstall/reinstall spyder using pip
2. Start spyder (either using command line or desktop launcher)
3. Run any command using ipython (complains about imports)
4. Open the dependencies window and resize it (crashes spyder)

**What is the expected output? What do you see instead?**
I expect to see no output, however on startup I see:
```
cannot import name hashtable
cannot import name hashtable
cannot import name hashtable
```
This appears both in the command line, and in the main spyder window
Any command run in the ipython windows also show the same error, although execution completes successfully. 

Additionally, if I open the dependencies window (Help > Dependencies) and try to resize it, spyder crashes with the following error:
```
QPaintDevice: Cannot destroy paint device that is being painted
QWidget::repaint: Recursive repaint detected
Segmentation fault (core dumped)
```

**Please provide any additional information below**

Note that I can run python/ipython from terminal without any issues. So I do not believe there is an issue with my base python installation. 

I would add my python path at startup if someone can give me instructions for how to do that. Also I can put the errors when I start the spyder version that is installed using ubuntu apt-get. It also complains about hashtable not being found.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 2.7.10
* Qt Version: 4.8.6
* PyQt Version: 4.11.4 (API v2)
* Operating system: Ubuntu 15.10 64bit

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  1.4.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.8.2 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Sorry but you're using a highly customized environment, so it's up to you to figure out where this error is coming from.

Our recommendation is:

1. Pip installations are for experts.
2. If you're not an expert, please use Anaconda/Miniconda.

**Comment by rdevans0** [comment]
Is there a help forum which would be better suited to ask for help on this?

**Comment by ccordoba12** [comment]
You cold post your question in Stackoverflow or in our Google group, but I doubt someone will answer it because it's very specific and it seems to require a lot of testing to understand what's happening.

I usually answered these questions, but now I don't have time to, sorry.
