### ISSUE TITLE
RuntimeError when closing spyder

### ISSUE THREAD

**Issue by j4321** [spyder-ide/spyder#4725]
## Description of your problem

When I open spyder from the command line and then quit, the following error is displayed in the terminal:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2117, in hideEvent
    if plugin.isAncestorOf(self.last_focused_widget):
RuntimeError: wrapped C/C++ object of type QPushButton has been deleted
```

It happens only when the 'prompt when existing' option is selected, so I guess the error is related to the confirmation dialog.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version: 5.9.1
* PyQt Version: PyQt5 5.9
* Operating system: Archlinux

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  4.3.0 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.1 (OK)
pycodestyle >=0.6:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this error in Spyder 3.2.
