### ISSUE TITLE
Update translations for 3.2

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#4730]
Version **3.2** is finally ready!! So now it has come the time to update our translations for this release.

This is a call to all our translators to update their respective translations. Please create separate pull requests for each language:

- French
  - @goanpeca 
- Japanese
  - @sohnishi
- Portuguese (Brazilian)
  - @manipuladordedados
- Russian
  - @burrbull
  - @Qlogin
- Spanish
  - @ccordoba12

---

**Important notes**:

1. We can only wait for you until Friday July 14 at 06:00 am UTC for your pull requests. There are 68 strings to be updated, so it'll take you a bit of time.
2. Don't forget to do your PRs against the **3.x** branch.

**Comment by ccordoba12** [comment]
Sorry, the right time to submit your translations is Saturday July **15** at 06:00 am.

**Comment by ccordoba12** [comment]
UTC time, as before.

**Comment by ccordoba12** [comment]
@Qlogin and @manipuladordedados, you still have time until Friday to update your respective translations because we plan to release 3.2 on Saturday.

**Comment by burrbull** [comment]
Please, update .pot files before asking for translation. This is not translator's work.

**Comment by ccordoba12** [comment]
The files are updated @burrbull. You need to checkout our 3.x branch to see them (they were not updated in master).

**Comment by burrbull** [comment]
Sorry.

**Comment by ccordoba12** [comment]
No problem, and thanks for helping us with your translation.

**Comment by ccordoba12** [comment]
Thank you all for your help!

3.2 is ready!! I'll do the release in a couple of hours.
