### ISSUE TITLE
Delete redundant functions in TextHelper and CodeEditor

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4732]
There is some logic duplicated in CodeEditor and in TextHelper

I'm planing to leave TextHelper, and move some CodeEditor functions to it, It's that ok?

One of the things missing after #3833

**Comment by ccordoba12** [comment]
> It's that ok?

Sure, please go for it. I can't say much about it until I see your PR, but removing duplicated code is always a good thing.

**Comment by ccordoba12** [comment]
Closing because I don't know what this refers to exactly.
