### ISSUE TITLE
Spyder is not working

### ISSUE THREAD

**Issue by imathur01** [spyder-ide/spyder#4735]
My Spyder is not working. Everytime i click on the icon the application does not open up.

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
How did you install Spyder and for which platform?

**Comment by ccordoba12** [comment]
I mean, Windows, Linux or macOS?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
