### ISSUE TITLE
numpy array raise wrongs in variable explorer

### ISSUE THREAD

**Issue by iipod2010** [spyder-ide/spyder#4736]
## Description of your problem

**What steps will reproduce the problem?**

1. run the following code in Ipython
import numpy as np
a=np.array([1,2])>0.5

2. check it in variable explorer

**What is the expected output? What do you see instead?**
internel console raise the following wrongs:
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 270, in data
    /(self.vmax-self.vmin)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 270, in data
    /(self.vmax-self.vmin)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version:
* PyQt Version: 5.8.2
* Operating system: Windows10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0rc2 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by jitseniesen** [comment]
Thanks for your report. As it happens, this was fixed in the development version two weeks ago (see issue #4663) and the fix will be part of Spyder 3.2, which as I understand it is planned to be released in a few days. Thus I am closing the issue.

If you want to test or can't wait until version 3.2 is released, feel free to try out the development version (either the `3.x` branch or the `master` branch).
