### ISSUE TITLE
The crosstable cant be printed out in Python console

### ISSUE THREAD

**Issue by lxlxlxb** [spyder-ide/spyder#4739]
## Description

**What steps will reproduce the problem?**

from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

import numpy as np

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
df.head()

train, test = df[df['is_train']==True], df[df['is_train']==False]

features = df.columns[:4]
clf = RandomForestClassifier(n_jobs=2)
y, _ = pd.factorize(train['species'])
clf.fit(train[features], y)
preds = iris.target_names[clf.predict(test[features])]

pd.crosstab(test['species'], preds, rownames=['actual'], colnames=['preds'])

I  do a test for code above ,and hope the see the crosstab result. But it cant be printed out in the console. However , when I pasted the code in command window, it runs well ,I can see the table. 
Is there any problem with the console box to show the crosstab result?

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by lxlxlxb** [comment]
the result in JupyterQtConsole is :
Out[3]: 
preds       setosa  versicolor  virginica
actual                                   
setosa          13           0          0
versicolor       0           9          2
virginica        0           1          5

however in Spyder ,there is only(both python console and Ipython console) :
runfile('C:/Users/Administrator/.spyder/temp.py', wdir='C:/Users/Administrator/.spyder')

and no table.....

**Comment by ccordoba12** [comment]
What you get with `runfile` is exactly the same that you get when you run `python myfile.py`. So if you want to see something printed in the console, you need to ask Python explicitly to do that.

In other words, your last line needs to be

`print(pd.crosstab(test['species'], preds, rownames=['actual'], colnames=['preds']))`

**Comment by lxlxlxb** [comment]
Great! Thank you

**Comment by lxlxlxb** [comment]
Great! Thank you
