### ISSUE TITLE
os.system() - TypeError: expected a bytes-like object, str found 

### ISSUE THREAD

**Issue by ben80** [spyder-ide/spyder#4740]
Hi,

**i always get an "internal spyder error" when trying to invoke os.system (net use ...) command.**
This also happens with subprocess.call()
T_ypeError: expected a bytes-like object, str found_ 

## Description of your problem
I try to map a network drive using the "NET USE" command.
I tried it with os.system() and subprocess.call() with the same result.
I tried it with different Spyder Versions (all included in the WinPython package)

**What steps will reproduce the problem?**
1. import os
2. os.system("NET USE z: \\\\Raspberrypi\\rpi_images /user:pi passwd" -> each backslash is written with "double-backslash"
3. Note: unmapping works -> os.system("NET USE z: /del")

**What is the expected output? What do you see instead?**
Internal Error: TypeError: sequence item 0: expected a bytes-like object, str found
The drive is mapped correctly, though.

**Please provide any additional information below**
I tried the same "net use" command in the normal python shell -> works
I tried the same "net use" command (replaced escape symbols) in the windows command prompts  -> works

-> Calling os.system() itself, doesn't seem to be the problem (unmapping works)
-> Maybe this bug is similar? [https://github.com/spyder-ide/spyder/issues/2452](url)

## Versions and main components
* Spyder Version: 3.1.4dev0
* Python Version: 3.5.3 (64 Bit)
* Qt Version: 5.8.0
* PyQt Version: 5.8.1
* Operating system: Win10

## Dependencies
jedi >=0.9.0     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> Maybe this bug is similar? https://github.com/spyder-ide/spyder/issues/2452

If you're running this in the Python console, please stop doing that and use the IPython console instead because we're going to remove the Python console in Spyder **3.2**

**Comment by ben80** [comment]
Thanks, it works with iConsole.
I've seen the other bug before, but didn't recognize that the solution means "use iConsole".

**Comment by ccordoba12** [comment]
Having two consoles was pretty confusing and that's one of reasons we remove the old Python console.

Sorry for the confusion.
