### ISSUE TITLE
Spyder hangs until keyboard interrupt, then resumes normally

### ISSUE THREAD

**Issue by FXLab91** [spyder-ide/spyder#4741]
## Description of your problem

I am running the latest version of Spyder and pyqt (just updated using conda), Python 2.7 on Windows 7.

For  any operation (e.g. 1 + 1) run directly from the iPython console or executing a script, the console hangs, with the "red square" indicating the console is busy. 
If I use Ctrl+c for keyboard interrupt, the correct result is displayed in the console, with no TraceBack or error whatsoever.

I know it is quite a generic description, but I have no idea how to debug/understand what is going on.
The issue appears from time to time (but on a daily basis), and sometimes goes temporarily away when I restart my console.
 
Maybe related, but when I open a new console, I always have a "Kernel died, restarting" message at first, and then the console opens:

![capture](https://user-images.githubusercontent.com/18048812/28161903-35b4b250-67bd-11e7-9327-0eb88f26a231.PNG)

**Comment by ccordoba12** [comment]
Perhaps this is a problem with your firewall and/or antivirus, so could you try to deactivate it for a while and see if the problem disappears?

**Comment by FXLab91** [comment]
Thanks for your answer. Since I am using it at work it is not so easy to deactivate firewall/antivirus. Could you please be more specific about why firewall/antivirus would cause this, so I can discuss it with IT?

**Comment by ccordoba12** [comment]
The IPython console use external Python processes called kernels to run code, and it communicates with them using sockets.

So probably your antivirus or firewall is blocking those sockets in your computer, and that's what's causing the failure you've seen.

**Comment by ccordoba12** [comment]
Closing because we can't do anything about this, sorry.
