### ISSUE TITLE
Adapt Code Introspection, Autocompletion and Linting editor functionalities to comply with MS/VSCode Language Server specification

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#4742]
We should write a full-compliant [Microsoft/language-server-protocol](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md)  client. This should enable us to support editing capabilities such as Linting and Autocompletion on Python and other languages only by installing the correct server. 

This reform also aims to simplify the current editor client-server architecture by only using a single client/server that performs all editing and code introspection tasks.

**Comment by ccordoba12** [comment]
I think there's no need to write a client for this because there's already one and it should be easier for us to contribute to it.

The main problem is to make it work with two completion libraries (Rope and Jedi).

**Comment by andfoy** [comment]
@ccordoba12 Actually, [palantir/python-language-server](https://github.com/palantir/python-language-server) implements its autocompletion services using Jedi

**Comment by andfoy** [comment]
We need to write a client that links the server with the respective Spyder functions

**Comment by andfoy** [comment]
We need to implement the tool side of this Diagram: 
 ![Language-server-protocol](https://raw.githubusercontent.com/Microsoft/language-server-protocol/master/images/interaction-diagram.png)

**Comment by goanpeca** [comment]
The server and the tool are the same thing in the python case afaik

**Comment by ccordoba12** [comment]
@andfoy, @goanpeca is right. You can instantiate a new server and use it as a client.

**Comment by andfoy** [comment]
I've just tested the server side, can I see an example of the server acting as a client?

**Comment by ccordoba12** [comment]
From the Spyder side, I mean :-)

**Comment by andfoy** [comment]
I must say I got a little confused here! From the language-server perspective we have our python-language-server and we're missing the tool side. From the Spyder side we have a server that communicates with Qt? If this is the case, our Spyder server would act as a client for the python-language-server? @ccordoba12

**Comment by ccordoba12** [comment]
> can I see an example of the server acting as a client?

Please take a look at

https://github.com/palantir/python-language-server/blob/develop/test/test_language_server.py#L14

> From the Spyder side we have a server that communicates with Qt?

We have a server that acts as a client, makes requests to the real server, gets its results and pass them to our completion widget and linting facilities.

**Comment by andfoy** [comment]
> https://github.com/palantir/python-language-server/blob/develop/test/test_language_server.py#L14

This could serve as an alternative, However I was thinking of communicating both sides using TCP sockets instead of system pipes, just in case another server does not support pipe communication.

> We have a server that acts as a client, makes requests to the real server, gets its results and pass them to our completion widget and linting facilities.

Now everything is more clear, thanks :-)

**Comment by andfoy** [comment]
@ccordoba12 Do we prefer plain TCP communication or system pipes?

**Comment by ccordoba12** [comment]
> However I was thinking of communicating both sides using TCP sockets instead of system pipes, just in case another server does not support pipe communication.

Ok, I agree with that. Then we would need to develop a new client for that, right?

> Now everything is more clear, thanks :-)

Sorry for the lack of info, I thought this was clear when we talked about it during the sprint.

**Comment by andfoy** [comment]
> Then we would need to develop a new client for that, right?

Yes, but is not more difficult than serializing JSON and send it through a socket :-)

**Comment by goanpeca** [comment]
>Yes, but is not more difficult than serializing JSON and send it through a socket :-)

Agreed :-p

**Comment by ccordoba12** [comment]
Ok, great! Please start to work on that then :-)

**Comment by andfoy** [comment]
Just a minor question, all current introspection requests are handled by the ``IntrospectionManager``, given that, then we would redirect requests directed to the Manager to the ls-server.

**Comment by andfoy** [comment]
With respect to the Linting functionalities, where are they declared

**Comment by ccordoba12** [comment]
> we would redirect requests directed to the Manager to the ls-server.

Yes, I think that's the idea.

> where are they declared?

Pep8 and Pyflakes analysis run in their own threads. They are declared here

https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/editor.py#L214-L221

and the thread manager is declared here

https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/editor.py#L76-L156

**Comment by goanpeca** [comment]
@ccordoba12 but the idea is to stop using the current logic, right? it is too confusing.

**Comment by ccordoba12** [comment]
Yeah, the idea is to remove all our code for code completion and replace it for ls-protocol. But we could probably need to preserve the IntrospectionManager to handle calls to several completion engines.

**Comment by andfoy** [comment]
> Yeah, the idea is to remove all our code for code completion

This means that all ``IntrospectionPlugin`` implementations are to be removed with this change?

**Comment by ccordoba12** [comment]
Yes, I think so. We need to rely only on ls-protocol.
