### ISSUE TITLE
Feature Request: Web App Version

### ISSUE THREAD

**Issue by justinkterry** [spyder-ide/spyder#4743]
With things like chromeos growing in popularity, windows 10s (windows store apps only) rapidly being promoted, and mobile operating systems starting to merge into desktop use (ie samsungs dex or the soon to be released fuschia OS by google), so theres starting to be a real need to run spyder on new operating systems, and this is only going to grow in the future. Especially since those OSes are heavily used in education (ie chrome os has 50% market share in us primary schools).

With the scale of this project and the limitations in porting it to these programs natively, this of course isn't viable. What I was wondering about turning spyder into a webapp that could be easily hosted by users. There's mature and reasonably easily to use tools to port qt apps to web apps, and people could host them on a cheap AWS instance or a little linux computer at their house. That would solve this emerging need and make my life much easier.

**Comment by goanpeca** [comment]
Not going to happen.

Perhaps you are interested in https://github.com/jupyterlab/jupyterlab

**Comment by ccordoba12** [comment]
Not so fast, there could a light at the end of tunnel :-) According to this blogpopst, Qt applications could be run in a browser in a future version:

https://blog.qt.io/blog/2017/07/07/qt-webgl-streaming-merged/

**Comment by justinkterry** [comment]
Based on that post and this:

http://blog.qt.io/blog/2017/02/22/qt-roadmap-for-2017/

It appears that what you'd need will be available in 18 months to a year.
What are your thoughts on adding the functionality at that point? Also I'm
aware of jupyter notebooks and have used them before; I specifically want
Spyder.

**Comment by ccordoba12** [comment]
Sorry, we took a look at this more closely and found that, even with those new developments, it won't be possible to run Spyder with that technology.

But there's also

https://github.com/kripken/emscripten

to compile Qt to Javascript. But let me tell you that this would be a huge (huge!) effort that probably won't play well at the end.

I think the best option would be to create a Crouton environment in ChromeOS and install Anaconda there.

**Comment by ccordoba12** [comment]
Closing as *Won't fix* because we don't plan to address this anytime soon.

**Comment by goanpeca** [comment]
@justinkterry This is JupyterLab https://github.com/jupyterlab/jupyterlab , looks that your needs are more geared towards that. Jupyter Lab is a IDE like (still inmature) thing that runs on the browser.

**Comment by justinkterry** [comment]
@goanpeca I know, I was just specifically looking for spyder
@ccordoba12 
I totally understand not wanting address it, that's fair. I am using crouton now by the way. What I'd like to add though, is that this issue isn't specific to any one platform (ie chrome os). It's that broadly there are a lot of new and emerging platforms out there that people are using that spyder can't run on. 

For example, Windows 10S is windows restricted to only the app store, and microsoft is pushing to kill the win32 interface and massively pushing windows 10s to consumers (if you google it a large number of new devices are coming with it by default, and microsoft is pushing to increase this). Also there's the thing where all new samsung phones (over 5 million now, and it will grow) can be docked to a desktop like interface, which is beginning to become popular in corporate circles. Also there's googles project fuschia, where they appear to be trying to release a whole new operating system built from the ground up to be both a standard mobile and desktop OS thats slated to come out in the next few years. Also there's the large number of people using ipads or android tablets with keyboards as defacto laptops. Also theres Tizen, Samsungs android competitor that's already on all their non-phoens and many of their phones, and that will come to something in the future.

I guess my point is just that given all this, creating mobile applications is important to stay sufficiently compatible, and so it's reasonably likely that this is a road that spyder and like projects will have to cross in the feature. That's why, for example, microsoft created a full featured webapp version of office. That being said, I do completely agree with not wanting to do it sooner than later. 

Also in case you didn't know someone already does this for spyder (though I don't know the technical details), but the interface doesn't allow package management, local resources, etc and it requires a subscription: https://www.rollapp.com/app/spyder

**Comment by goanpeca** [comment]
@justinkterry we are aware of that and we simply don't have the resources, and there are no easy solutions here. We still have years of development to do and I am looking closely at the beeware project and might even contribute to it in the future https://pybee.org . That seems like a more reasonable approach.

**Comment by ccordoba12** [comment]
@justinkterry, we're also targeting developers here, and developers use regular desktop interfaces. Not everything has to run on the cloud.
