### ISSUE TITLE
unexpected behaviour of runfile() on spyder - (Learning Python!)

### ISSUE THREAD

**Issue by mrsblackgr** [spyder-ide/spyder#4747]
I am currently undertaking an online course, and I follow the tutorial step by step.

So when I'm running any command I get the full path in the console, and somethings that are supposed to come up as output, don't:
 
In the first picture is how it's supposed to look like

<img width="1280" alt="screen shot 2017-07-14 at 15 08 41" src="https://user-images.githubusercontent.com/30179209/28215329-ea6f507e-68ad-11e7-9819-c35bc55a13ab.png">

in the second picture is the results I get

<img width="1280" alt="screen shot 2017-07-14 at 15 08 47" src="https://user-images.githubusercontent.com/30179209/28215328-ea6a97fa-68ad-11e7-90cb-9b7c16080dec.png">

I tried to see if I can change something in the settings but I didn't find something. 
Any ideas?
Thank you!!  :)

## Versions and main components

* Spyder Version: 3.1.4
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system: Mac OSX 10.11.6

**Comment by ccordoba12** [comment]
This is not exactly an error but a difference in how you are evaluating your code vs. how it is done by your instructor.

So there are several execution models in Spyder:

1. Evaluate the whole file. This is done with F5 or the green play button, and it is what you're doing.
2. Evaluate line by line. This is done with F9, and it is what your instructor is doing.
3. Evaluate cells. Cells are created with comments that start like this `#%%` and are evaluated with `Shift+Enter`, which evaluates the current cell and moves to the next one; and `Ctrl+Enter`, which remains in the same cell.

**Comment by mrsblackgr** [comment]
Thank you!

**Comment by rohailkhan** [comment]
I am having the same issue...but I still cant get any out put whether I press F5 or F9
