### ISSUE TITLE
How to show full variable

### ISSUE THREAD

**Issue by mrsblackgr** [spyder-ide/spyder#4748]
I am currently undertaking an online course, and I follow the tutorial step by step.

So when I'm printing X I get as a result some of the values, while all the values are supposed to show up as output. how can I fix this?

In the first picture is how it's supposed to look like

![screen shot 2017-07-14 at 17 49 55](https://user-images.githubusercontent.com/30179209/28219635-f3c16090-68bc-11e7-9878-59bcd646b6e8.png)

in the second picture is the results I get

<img width="1212" alt="screen shot 2017-07-14 at 17 50 09" src="https://user-images.githubusercontent.com/30179209/28219649-fe4214c4-68bc-11e7-97e7-f4c33093ed37.png">

Thank you in advance! :)

## Versions and main components

Spyder Version: 3.1.4
Python Version:
Qt Version:
PyQt Version:
Operating system: Mac OSX 10.11.6

**Comment by ccordoba12** [comment]
To get the full contents of your array you need to evaluate this expression in an IPython console

```python
import numpy as np
np.set_printoptions(threshold=1000)
```

However, this won't be necessary since Spyder 3.2, to be released tomorrow.
