### ISSUE TITLE
tryint to get spyder plugins to works (maybe too early ?)

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#4753]
## Description

**What steps will reproduce the problem?**

1. install spyder plugins into spyder 3.2.0dev on winpython-3.5.3
2. start spyder
3. spyder shows an error at start

**What is the expected output? What do you see instead?**
hoped to see the notebook and terminal extensions
maybe did I miss a commit ?

**Please provide any additional information below**

    plugin.initialize_plugin_in_mainwindow_layout()
    self.on_first_registration()
    self.main.tabify_plugins(self.main.extconsole, self)
    self.tabifyDockWidget(first.dockwidget, second.dockwidget)
AttributeError: 'NoneType' object has no attribute 'dockwidget'
WARNING:traitlets:kernel died: 6.001145601272583

## Version and main components

* Spyder Version: 3.2.0.dev0 
* Python Version: 3.5.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by stonebig** [comment]
ok, so:
- the terminal extension has problems,
- unselecting it and selecting the noteebook extension:
   - the notebook extension works,
   - it just fails at first opening of the day because of slow start of jupyter
- now, the notebook extension works as advertised https://youtu.be/Hf07PmwQwPQ?list=PLYx7XA2nY5GfdAFycPLBdUDOUtdQIVoMf&t=329

awesome !

**Comment by andfoy** [comment]
@stonebig What problems do you have with the terminal?

**Comment by stonebig** [comment]
spyder complains at start, so I remove the toolbar.
If  I re-add it now, I see  this unworkable terminal window:

![spyder_3 2_terminal_feature](https://user-images.githubusercontent.com/4312421/28244914-de12b8ec-69f8-11e7-8361-fc4272cb8a3d.PNG)

**Comment by stonebig** [comment]
the `\' of windows have diseappeared, maybe a UTF-8 / latin code page issue ?

**Comment by andfoy** [comment]
Do you have the winpty binaries on your path? Did you install pywinpty?

**Comment by andfoy** [comment]
Is this the latest commit from spyder-terminal repo?

**Comment by stonebig** [comment]
ah,  I may have missed that two ones... will check

**Comment by andfoy** [comment]
@stonebig by judging the screenshot, it seems that you installed spyder-terminal v0.1.1 which is uncompatible with Windows. Our great milestone was to bring it compatible on v0.2, so it would be great if you can give it a test :-)

**Comment by stonebig** [comment]
can't recompile winpty from source ?
````
winpty/cywinpty.c(445): fatal error C1083: Cannot open include file: 'winpty.h': No such file or directory
````

**Comment by andfoy** [comment]
Do you have winpty's binaries on your path @stonebig?

**Comment by stonebig** [comment]
maybe not, and I don't have "bower" to compile spyder-terminal.... I see I'm badly equipped to digg on this issue... will wait official wheels

**Comment by andfoy** [comment]
@stonebig, thanks for your effort. Our official v0.2 release will occur after the official release of spyder v3.2, however, any comment is welcome!

**Comment by stonebig** [comment]
it would be nice if the "winpty" terminal feature was reproduced also per jupyterlab team

**Comment by andfoy** [comment]
@stonebig, @ccordoba12 told me that the people at JupyterLab might be interested on this terminal server, however, we don't know yet if they are going to use it

**Comment by stonebig** [comment]
I would prefer to have spyder-notebooks and spyder-reports well polished and stable today. Terminal may have a lot of incompatible  iteration to go to awesomness; jupyterlab and xonsh cross-sharing, powershell, ...

**Comment by ccordoba12** [comment]
@stonebig, thanks a lot for trying our new plugins and for thinking to include them already in WinPython!

> I would prefer to have spyder-notebooks and spyder-reports well polished and stable today.

I'd say they are pretty stable already, but we will know for sure when people start to use them. I really like the output of spyder-reports, it's beautiful!

> Terminal may have a lot of incompatible iterations to go to awesomness

Spyder-terminal will be awesome on Windows! That has been the great work of @andfoy for its 0.2 version.

**Comment by andfoy** [comment]
@stonebig Spyder-terminal is now available on Windows via PyPi, would you mind if you can give it a test run? 
```
pip install -U spyder-terminal
```

**Comment by stonebig** [comment]
will retry spyder-terminal today. I don't understand evolution state of spyder-unittest, so I may leave it aside
