### ISSUE TITLE
Kernel dies very often and restarts.

### ISSUE THREAD

**Issue by abhijeet-pandey** [spyder-ide/spyder#4760]
## Description

**What steps will reproduce the problem?**

1.  Kernel dies very often and restarts. This happens even when it is idle or when using editor.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Please deactivate your firewall and/or antivirus and try again.

**Comment by MrWanter** [comment]
Thank you, I have run into the same problem, after quit my antivirus, the problem doesn't happen again, but could you pls suggest how to set the antivirus so that we can open it while using spyder?

**Comment by MrWanter** [comment]
unfortunately, the problem happened again when I tried to open a specific file, could you pls suggest a quick way to downgrade Spyder to lower versions?

**Comment by ccordoba12** [comment]
I don't know what antivirus you're using, but you should add a rule to prevent it blocking any Python process.

I'm closing this issue because it's not a Spyder problem and there's nothing we can do about it.

**Comment by ccordoba12** [comment]
I don't work on Windows, so I can't recommend you an antivirus, sorry.

**Comment by abhijeet-pandey** [comment]
Thanks for your response. Will try it out.
