### ISSUE TITLE
Downgrading Spyder in Anaconda

### ISSUE THREAD

**Issue by MrWanter** [spyder-ide/spyder#4761]
Hi! Recently I installed Anaconda packages, but every time when I'm going to open some scripts in Spyder, it just crashes, says python stopped working, I have found there are similar problems posted on the github, seems I can downgrade the Spyder to previous version, I want to downgrade it to 2.3.9, but I don't know how to do it, I have tried `conda install spyder=2.3.9`, it gives:

```
conda install spyder=2.3.9
Fetching package metadata ...........
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - python 3.6*
  - spyder 2.3.9* -> pyqt 4.* -> python 2.6*
Use "conda info <package>" to see the dependencies for each package.
```
Can someone help me? Thanks in advance!

**Comment by ccordoba12** [comment]
Please create a new conda environment and install Spyder there.

You need to use Python 2.7 or 3.5 because there are no PyQt 4 packages available for 3.6.

This command should do the job

    conda create -n old-spyder python=3.5.* spyder=2.3.9

However, Spyder 2.3 is not supported anymore and it doesn't work on Windows 10 or macOS 10.10 or higher.
