### ISSUE TITLE
Exception raised when running file from project explorer

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#4769]
This looks like a simple one but I don't have time now to dig into it.

## Description

**What steps will reproduce the problem?**

1. Right-click on a Python file in the Project explorer
2. Select 'Run' in the context menu

**What is the expected output? What do you see instead?**

The exception below is raised.

**Please provide any additional information below**

  File "/home/jitse/misc/spyder/spyder/widgets/explorer.py", line 557, in run
    self.parent_widget.run.emit(fname)
AttributeError: 'Projects' object has no attribute 'run'

## Version and main components

* Spyder Version: 3.2.0.dev0 76cb1332
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by andfoy** [comment]
I can take a look at this!

**Comment by ccordoba12** [comment]
Thanks @andfoy!
