### ISSUE TITLE
Python crashes at startup

### ISSUE THREAD

**Issue by jhuang76** [spyder-ide/spyder#4771]
## Python crashes at startup. Python tries to import a broken package. Reset does nothing. Traceback:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2336, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 2220, in run_sp
yder
    main.setup()
  File "C:\Python27\lib\site-packages\spyderlib\spyder.py", line 687, in setup
    if is_module_installed('guidata'):
  File "C:\Python27\lib\site-packages\spyderlib\utils\programs.py", line 292, in
 is_module_installed
    actver = get_module_version(module_name)
  File "C:\Python27\lib\site-packages\spyderlib\utils\programs.py", line 238, in
 get_module_version
    mod = __import__(module_name)
  File "C:\JohnHuang\Python Scripts\Python CAE scripts\abaqustools010\aqolt\guid
ata.py", line 2, in <module>
```

**What steps will reproduce the problem?**

1. Simply opening Spyder
2. Resetting Spyder does nothing. 
3. Spyder light works. 
4. Workaround is to change/delete the directory name Spyder is trying to import. 

**What is the expected output? What do you see instead?**
The only message is the msgbox "Spyder crashed during last session"

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 2.3.5.2
* Python Version: 2.7.10 32 bit
* Qt Version: 4.8.6
* PyQt Version: 4.11.3
* Operating system: Windows 7
* Spyder installed using Python-xy

## Dependencies

IPython >=1.0   :  2.4.1 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pyflakes >=0.5.0:  0.9.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
pylint >=0.25   :  1.4.3 (OK)
rope >=0.9.2    :  0.10.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
sympy >=0.7.3   :  1.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)

**Comment by ccordoba12** [comment]
Sorry, Spyder 2.3 is not supported anymore. Please update to our latest version (3.1.4) and try again. I think this error is not present there anymore.
