### ISSUE TITLE
Ipython console report: ImportError: cannot import name 'quick_guide'

### ISSUE THREAD

**Issue by MrWanter** [spyder-ide/spyder#4775]
I'm using spyder 3.1.2 on win10 with python 3.6, I'm not using spyder 3.1.4 as it would always die very often  when I trying to open source files, but recently after I got into debug mode, then the problem of reporting 
```
from IPython.core.usage import quick_guide
ImportError: cannot import name 'quick_guide' 
```
happened, and even if I reinstall spyder 3.1.2, it cannot be solved, can anyone help me? Thanks in advance!

**Comment by ccordoba12** [comment]
Unfortunately this error was fixed in 3.1.4, so you can't use the latest IPython with 3.1.2, sorry.
