### ISSUE TITLE
Code folding does not open the correct line from the backtrace of the ipython window

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#4778]
When running a program, in case of crahs, the ipthon window displays the backtrace with file & line number as hyperlinks. Clicking on these links jump to the current line.
However it does not work if the line is folded. It does not open the folded block.

Thanks anyway, code folding is a great addition.

**Comment by ccordoba12** [comment]
Thanks to you for helping us improve our code folding facilities by reporting all these bugs.

@rlaverde, please work on this one.
