### ISSUE TITLE
typing () after object results in )(

### ISSUE THREAD

**Issue by peendebak** [spyder-ide/spyder#4779]
## Description of your problem

**What steps will reproduce the problem?**

1. After an object of function type () in the console
2. The result is )(

**What is the expected output? What do you see instead?**

The result should be ()

**Please provide any additional information below**

It seems after a function or object the `(` triggers some functionality (e.g. code completion) that delays putting the character in the console. Typing the `)` quickly places this in front of the `(`

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.5
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0.dev (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by timhoffm** [comment]
Not reproducible in the current 3.2.x development branch.

## Version and main components

* Spyder Version: 3.2.5.dev0 11afa31
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

**Comment by ccordoba12** [comment]
Great! Thanks for the confirmation!
