### ISSUE TITLE
Slash does not work as keyboard shortcut key

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#478]
_From [joonp...@gmail.com](https://code.google.com/u/101070586672081573036/) on 2010-11-30T12:51:04Z_

What steps will reproduce the problem?

 1. Assign Ctrl as Mod3 and Slash as Key for comment What is the expected output? What do you see instead? The shortcut does not work, and in the Edit menu, the shortcut for Comment is showing as "Ctrl+" What version of the product are you using? On what operating system? 2.0.1, openSUSE X64

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=478_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-01-31T01:15:23Z_

issue #539 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:18:07Z_

**Labels:** Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:20:15Z_

**Labels:** -Cat-Miscelleneous Cat-Settings

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T13:08:41Z_

**Status:** HelpNeeded

**Comment by spyder-issues-migrator** [comment]
_From [evgeny.g...@gmail.com](https://code.google.com/u/109082887708970094311/) on 2015-01-17T08:57:41Z_

Hello. I am very much used to commenting code via Ctrl+/, so I've looked into this. 

The problem occurs because shortcut strings end up containing names for keys which correspond to printable characters, for example "Ctrl+Slash" instead of "Ctrl+/". This ends up in QKeySequence, which only translates name-to-keycode for non-printable keys[0]. Attached is a patch which fixes this for me.

[0]: https://qt.gitorious.org/qt/qtbase/source/73a1e8c60d894701f34806cc4b847aa2814bf389:src/gui/kernel/qkeysequence.cpp#L401

**Attachment:** [printable-shortcut.patch](http://code.google.com/p/spyderlib/issues/detail?id=478#hc5)

**Comment by ccordoba12** [comment]
The way to enter keyboard shortcuts is being reworked right now. When it's done, it'll be much easier to enter any kind of shortcuts.
