### ISSUE TITLE
Spyder for debugging multi-threads scripts

### ISSUE THREAD

**Issue by MrWanter** [spyder-ide/spyder#4793]
Hi! I'm new to use multi-threads program in python with Spyder, can someone suggest a good tool for debugging the scripts in Spyder,  it seems the `ipdb` tool does work very well. Thanks!

**Comment by ccordoba12** [comment]
> it seems the ipdb tool does work very well

`ipdb` can be used with Spyder too because it's the debugger present in our IPython consoles.

Please post a simple example of the kind of scripts that you want to debug to help you check if things work as expected.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
