### ISSUE TITLE
Launch problem

### ISSUE THREAD

**Issue by gkkot** [spyder-ide/spyder#4796]
Hi!

I'm having trouble launching spyder.  The logo shows up but the console doesn't start - it simply crashes.  

I recently changed my environment (named tfgpu) - not sure if this is related.  

**What is the expected output? What do you see instead?**
Showing the console gives the following:

Traceback (most recent call last):
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\spyder\app\mainwindow.py", line 2999, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\spyder\app\mainwindow.py", line 2901, in run_spyder
    main.setup()
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\spyder\app\mainwindow.py", line 860, in setup
    from spyder.plugins.externalconsole import ExternalConsole
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\spyder\plugins\externalconsole.py", line 39, in <module>
    from spyder.widgets.externalshell.pythonshell import ExternalPythonShell
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\spyder\widgets\externalshell\pythonshell.py", line 34, in <module>
    from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 26, in <module>
    import ipykernel.pickleutil
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\jupyter_client\__init__.py", line 7, in <module>
    from .manager import KernelManager, run_kernel
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\jupyter_client\manager.py", line 32, in <module>
    from .session import Session
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\jupyter_client\session.py", line 56, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\zmq\eventloop\ioloop.py", line 35, in <module>
    from tornado.ioloop import PollIOLoop, PeriodicCallback
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\tornado\ioloop.py", line 46, in <module>
    from tornado.concurrent import TracebackFuture, is_future
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\tornado\concurrent.py", line 37, in <module>
    from concurrent import futures
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\concurrent\futures\__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "C:\Users\gk\.conda\envs\tfgpu\Lib\site-packages\concurrent\futures\_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.2

Thanks!

**Comment by ccordoba12** [comment]
Please post the output of

    conda list

to help you with this problem.

**Comment by gkkot** [comment]
Many thanks!  Output as below

alabaster                 0.7.9                     <pip>
alabaster                 0.7.10                   py35_0
astroid                   1.4.9                    py35_0
astroid                   1.4.9                     <pip>
atari-py                  0.0.18                    <pip>
Babel                     2.3.4                     <pip>
babel                     2.4.0                    py35_0
biopython                 1.68                      <pip>
bleach                    1.5.0                     <pip>
bleach                    1.5.0                    py35_0
boto                      2.47.0                   py35_0
boto3                     1.4.4                    py35_0
botocore                  1.5.67                   py35_0
chardet                   3.0.4                    py35_0
chardet                   2.3.0                     <pip>
colorama                  0.3.7                     <pip>
colorama                  0.3.9                    py35_0
cycler                    0.10.0                   py35_0
decorator                 4.0.11                   py35_0
decorator                 4.0.11                    <pip>
docutils                  0.13.1                   py35_0
docutils                  0.13.1                    <pip>
entrypoints               0.2.2                     <pip>
entrypoints               0.2.3                    py35_0
futures                   3.0.3                    py35_0
gym                       0.8.1                     <pip>
html5lib                  0.999                    py35_0
html5lib                  0.9999999                 <pip>
icu                       57.1                     vc14_0  [vc14]
imagesize                 0.7.1                     <pip>
imagesize                 0.7.1                    py35_0
ipykernel                 4.5.2                     <pip>
ipykernel                 4.6.1                    py35_0
ipython                   5.2.2                     <pip>
ipython                   6.1.0                    py35_0
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.2.0                    py35_0
isort                     4.2.5                     <pip>
isort                     4.2.15                   py35_0
jedi                      0.10.2                   py35_2
jedi                      0.9.0                     <pip>
Jinja2                    2.9.5                     <pip>
jinja2                    2.9.6                    py35_0
jmespath                  0.9.0                    py35_0
joblib                    0.11                     py35_0
jpeg                      9b                       vc14_0  [vc14]
jsonschema                2.6.0                     <pip>
jsonschema                2.6.0                    py35_0
jupyter-client            5.0.0                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter_client            5.1.0                    py35_0
jupyter_core              4.3.0                    py35_0
lazy-object-proxy         1.3.1                    py35_0
lazy-object-proxy         1.2.2                     <pip>
libgpuarray               0.6.8                    vc14_0  [vc14]
libpng                    1.6.27                   vc14_0  [vc14]
libpython                 2.0                      py35_0
m2w64-binutils            2.25.1                        5
m2w64-bzip2               1.0.6                         6
m2w64-crt-git             5.0.0.4636.2595836               2
m2w64-gcc                 5.3.0                         6
m2w64-gcc-ada             5.3.0                         6
m2w64-gcc-fortran         5.3.0                         6
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gcc-objc            5.3.0                         6
m2w64-gmp                 6.1.0                         2
m2w64-headers-git         5.0.0.4636.c0ad18a               2
m2w64-isl                 0.16.1                        2
m2w64-libiconv            1.14                          6
m2w64-libmangle-git       5.0.0.4509.2e5a9a2               2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-make                4.1.2351.a80a8b8               2
m2w64-mpc                 1.0.3                         3
m2w64-mpfr                3.1.4                         4
m2w64-pkg-config          0.29.1                        2
m2w64-toolchain           5.3.0                         7
m2w64-tools-git           5.0.0.4592.90b8472               2
m2w64-windows-default-manifest 6.4                           3
m2w64-winpthreads-git     5.0.0.4634.697f757               2
m2w64-zlib                1.2.8                        10
mako                      1.0.6                    py35_0
markupsafe                0.23                     py35_2
MarkupSafe                0.23                      <pip>
matplotlib                2.0.2               np113py35_0
mccabe                    0.6.1                     <pip>
mistune                   0.7.4                    py35_0
mistune                   0.7.3                     <pip>
mkl                       2017.0.3                      0
mkl-service               1.1.2                    py35_3
msys2-conda-epoch         20160418                      1
nbconvert                 5.2.1                    py35_0
nbconvert                 5.1.1                     <pip>
nbformat                  4.3.0                     <pip>
nbformat                  4.3.0                    py35_0
nose                      1.3.7                    py35_1
numpy                     1.12.0                    <pip>
numpy                     1.13.1                   py35_0
numpydoc                  0.6.0                    py35_0
numpydoc                  0.6.0                     <pip>
olefile                   0.44                      <pip>
openssl                   1.0.2l                   vc14_0  [vc14]
pandas                    0.20.2              np113py35_0
pandocfilters             1.4.1                    py35_0
pandocfilters             1.4.1                     <pip>
path.py                   10.3.1                   py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                     <pip>
pep8                      1.7.0                    py35_0
pickleshare               0.7.4                    py35_0
pickleshare               0.7.4                     <pip>
Pillow                    4.0.0                     <pip>
pip                       9.0.1                    py35_1
prompt-toolkit            1.0.13                    <pip>
prompt_toolkit            1.0.14                   py35_0
protobuf                  3.2.0                     <pip>
psutil                    5.1.3                     <pip>
psutil                    5.2.2                    py35_0
pyfaidx                   0.4.8.2                   <pip>
pyflakes                  1.5.0                     <pip>
pyflakes                  1.5.0                    py35_0
pyglet                    1.2.4                     <pip>
pygments                  2.2.0                    py35_0
Pygments                  2.2.0                     <pip>
pygpu                     0.6.8                    py35_0
pylint                    1.6.5                     <pip>
pylint                    1.6.4                    py35_1
pymc3                     3.0                      py35_0
PyOpenGL                  3.1.0                     <pip>
pyparsing                 2.1.4                    py35_0
pyqt                      5.6.0                    py35_2
python                    3.5.2                         0
python-dateutil           2.6.0                    py35_0
python-dateutil           2.6.0                     <pip>
pytz                      2016.10                   <pip>
pytz                      2017.2                   py35_0
pyzmq                     16.0.2                   py35_0
pyzmq                     16.0.2                    <pip>
qt                        5.6.2                    vc14_5  [vc14]
qtawesome                 0.4.4                    py35_0
QtAwesome                 0.4.4                     <pip>
qtconsole                 4.3.0                    py35_0
qtconsole                 4.2.1                     <pip>
qtpy                      1.2.1                    py35_0
QtPy                      1.2.1                     <pip>
requests                  2.14.2                   py35_0
requests                  2.13.0                    <pip>
rope                      0.9.4                    py35_1
rope-py3k                 0.9.4.post1               <pip>
s3transfer                0.1.10                   py35_0
scipy                     0.19.1              np113py35_0
setuptools                27.2.0                   py35_1
simplegeneric             0.8.1                    py35_1
simplegeneric             0.8.1                     <pip>
sip                       4.18                     py35_0
six                       1.10.0                    <pip>
six                       1.10.0                   py35_1
snowballstemmer           1.2.1                     <pip>
snowballstemmer           1.2.1                    py35_0
Sphinx                    1.5.2                     <pip>
sphinx                    1.6.2                    py35_0
sphinxcontrib             1.0                      py35_0
sphinxcontrib-websupport  1.0.1                    py35_0
spyder                    3.1.3                     <pip>
spyder                    3.1.4                    py35_0
tabulate                  0.7.7                     <pip>
tensorflow-gpu            1.0.0                     <pip>
testpath                  0.3.1                    py35_0
testpath                  0.3                       <pip>
theano                    0.9.0                    py35_0
tk                        8.5.18                   vc14_0  [vc14]
tornado                   4.4.2                     <pip>
tornado                   4.5.1                    py35_0
tqdm                      4.14.0                   py35_0
traitlets                 4.3.2                    py35_0
traitlets                 4.3.1                     <pip>
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py35_0
wcwidth                   0.1.7                     <pip>
wheel                     0.29.0                   py35_0
win-unicode-console       0.5                       <pip>
win_unicode_console       0.5                      py35_0
wrapt                     1.10.10                  py35_0
wrapt                     1.10.8                    <pip>
zlib                      1.2.8                    vc14_3  [vc14]

**Comment by ccordoba12** [comment]
As I thought, you have a mix of conda and pip packages, which I think essentially broke your installation. For example, you have two tornado versions, two trailets versions, etc.

Please create a clean environment and install Spyder there. I'm sure it'll work fine there.
