### ISSUE TITLE
How to debug Spyder with other application?

### ISSUE THREAD

**Issue by naeco2008** [spyder-ide/spyder#4798]
I cannot find a place to ask questions for Spyder, so i put my question here. 

There is an application which will provide Python API, and we are thinking to use Spyder as the Python IDE. But i don't know how i can debug the python scripts in Spyder, but actually they are executed in the application? Since the Python API cannot run without the application, in Spyder when we execute/debug the scripts written with Application API, actually they should be run in this application and return back the result to Spyder. 

Do you know how i can achieve this? I googled this topic and didn't find anything. Is there some document/guidance i can follow?

Thanks, 
-Naeco

**Comment by ccordoba12** [comment]
I have no idea how to help you. It depends on how you interact with your application through the API you defined.

Couldn't you define an API to do what you need? I mean, calling the application, make it process what you want and make it return the result you need from it?

That way it would be really easy to call it from Spyder:

```python
from my_app.api import run

result = run_command('1 + 1')
```

and so the value of `result` would be `2`.

**Comment by naeco2008** [comment]
Thanks @ccordoba12.

I guess i didn't express my idea clearly. I found in Visual Studio if you install ptvs according to https://docs.microsoft.com/en-us/visualstudio/python/installation, you will be able to attach your own application to debug the scripts which can only be run inside of the application. I want to figure out the similar feature in Spyder. I am checking if we would be able to achieve this in Spyder?

Thanks, 
naeco

**Comment by ccordoba12** [comment]
I see. Well, we don't have such functionality and we don't plan to provide it in the furore, sorry.
