### ISSUE TITLE
Is spyder Integrated with Qt-designer ? 

### ISSUE THREAD

**Issue by abhishekbudruk** [spyder-ide/spyder#4800]
## Description of your problem
Since i am new to Spyder IDE
I have 

**Query??**
Is there any way that  allows us to design Python GUI's using Qt-designer in Spyder IDE itself?

## Versions and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.12
* Qt Version:4.8.7
* PyQt Version:4.11.4 
* Operating system: Ubuntu

**Comment by goanpeca** [comment]
@abhishekbudruk no. We design everything directly in code, so we do not use QtDesigner, nor uic files.

**Comment by abhishekbudruk** [comment]
Thanks for your response

**Comment by abhishekbudruk** [comment]
Thanks for the help
