### ISSUE TITLE
Spyder won't launch (loading file explorer forever)

### ISSUE THREAD

**Issue by Titanosaurus** [spyder-ide/spyder#4805]
I'm working with my Windows 8 computer, that has installed in it Python 2.7.13 with the Python(x,y) distribution.

When I launch Spyder It all went well, at least for a week, but now when I try to lunch it it starts to load and when it says it's loading the file explorer it get's stuck forever. I can't open Spyder because of that. I don't know what has changed. I can open de IDE that comes with python and it works well, I can work with python on the cmd and it works well. The problem then seems to be about spyder.

I've uninstalled Python and Python(x,y) form my computer, restarted and reinstalling all. But it still can't open. 

Also when I write:
`spyder --show-console`
in the cmd It just try to launch spyder showing the loading image and stucking once it arrives to file explorer as always.

Please could you help me?

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --reset

and try again.

**Comment by Titanosaurus** [comment]
First of all, thank you so much for your fast reply.

Sorry, I didn't explained that I've also done that.
For confirmation I did once again when I red this and after that when I launch it's exactly the same problema, nothing has changed.

What else should I try?

**Comment by ccordoba12** [comment]
I really don't know what's happening in your case.

Do you have network drives in your computer?

**Comment by deepak539** [comment]
I am facing the same problem as mentioned above, please help me to figure out this

**Comment by Devarsh-leo** [comment]
I am also facing the same problem. Please help me figure it out.

**Comment by deepak539** [comment]
> I am also facing the same problem. Please help me figure it out.

i was facing this issue but then i uninstalled it and tried to install it in diffrent ways and it worked for me....
