### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by MakarevichDmitry** [spyder-ide/spyder#4807]
Hi!
Sorry for my english. I try explain my problem.
1. I`m install spyder 3.2
2. then i`m install spyder_reports
3. I`m launch Spyder3 and catch this error.

**Please provide any additional information below**

  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder_reports-0.1.0.dev0-py3.6.egg/spyder_reports/reportsplugin.py", line 150, in worker_output
    self.show_error_message(error)
  File "/home/dmitry.makarevich/anaconda3/lib/python3.6/site-packages/spyder_reports-0.1.0.dev0-py3.6.egg/spyder_reports/reportsplugin.py", line 131, in show_error_message
    messageBox.setText(message)
TypeError: setText(self, str): argument 1 has unexpected type 'FileNotFoundError'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-reports #32](https://github.com/spyder-ide/spyder-reports/issues/32) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ccordoba12** [comment]
Thanks for reporting. We moved this issue to the `spyder-reports` repository.
