### ISSUE TITLE
xyz

### ISSUE THREAD

**Issue by adwiteeymauriya** [spyder-ide/spyder#4808]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/adwiteey/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/home/adwiteey/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/spyder/otherplugins.py", line 101, in _import_module_from_path
    info = imp.find_module(module_name, [plugin_path])
ImportError: No module named spyder_terminal-0.1.2.dist-info

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.11
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.1.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  3.3.0 (OK)
nbconvert >=4.0   :  5.0.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
I don't know what you're trying to do. Since there's no proper description, I'm closing this issue.

**Comment by adwiteeymauriya** [comment]
It was auto-generated. You can close it. Cheers.
