### ISSUE TITLE
Find in files missing directory selector in 3.2.0

### ISSUE THREAD

**Issue by avylove** [spyder-ide/spyder#4809]
The directory selector seems to have been removed from the Find in files widget.

It's might not be necessary for small projects, but in larger projects it can take considerable time to search all the files. Generally, I limit my searches to the source, documentation, or tests directories to limit time the search takes.

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.2
* Qt Version: 5.7.1
* PyQt Version: 5.8.1
* Operating system: Fedora 26

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.0.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by andfoy** [comment]
@avylove you can control the folder onto which the Find in Files plugin will search by using the standard Current Working Directory selector

**Comment by ccordoba12** [comment]
To clarify what @andfoy said, to select a particular directory for your search, simply use the Working Directory toolbar.

**Comment by avylove** [comment]
Ah, that was not very apparent. I didn't even see that toolbar until you mentioned it. The name is also very misleading, which I know you guys were trying to clear up. When you say current working directory, I assume this references where the consoles and any code will be executed.

From what I can tell, the current working directory toolbar is used to select the search path for Find in files and File Explorer. Does it do anything else?

In both cases, I would say these are search paths and not the current working directory. I also think they have nothing to do with each other and should both have their own path selectors.

**Comment by ccordoba12** [comment]
The Working Directory toolbar displays now the working directory of each 
console (it's updated automatically when you move from console to 
console), and it also syncs the File Explorer current directory to be 
the same one.

We want to reduce the complexity of our interface, so if you want to 
search in a particular directory, simply use `cd` in a console and move 
to that directory. You can also create a Spyder project to always 
perform your searches in your project's main directory.

**Comment by avylove** [comment]
While it seems pretty slick, I'd argue these have nothing to do with each other. Looking it at it from the console perspective it seems useful, but looking at it from Find in Files or the File Explorer, every time I change my search path, it's going to screw up my current working directory in the console.

While I can see this being useful in some cases, especially if you work primarily in the IPython console, but in general use, when the work is editor-centric, this ends up being a peculiarity you have to remember and work around.

I'm not sure what a good solution is.

**Comment by jnsebgosselin** [comment]
An idea could be to replace the three checkboxes by a QComboBox. The three default options ('current working directory', 'current project folder', 'current file') could be added on top, then we add a separator, then we add recent or preferred directories, then a separator, then a "choose a different folder option" which open a directory selector dialog when selected.

**Comment by ccordoba12** [comment]
I like this idea. @andfoy, what do you say?

**Comment by andfoy** [comment]
@ccordoba12 I think it's also a good idea, I can implement it

**Comment by ccordoba12** [comment]
Great! Please do it in the 3.x branch.
