### ISSUE TITLE
Spyder crashes after I upgraded to 3.2.0 because of OpenGL issues

### ISSUE THREAD

**Issue by kuo000** [spyder-ide/spyder#4815]
I just upgraded Spyder to 3.2.0 (Python 3), and it stopped working. Specifically, when I tried launching it at a terminal with `spyder`, I got the following message:
```bash
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile)) 
Aborted (core dumped)
```

It seems like a problem stemming from OpenGL? I tried making a fresh virtualenv and just installed `spyder` and `pyqt5`, and it still doesn't work...

However, the same works in Python 2.

**What steps will reproduce the problem?**

1. `mkvirtualenv --python=/usr/bin/python3 testenv`
2. `pip install pyqt5 spyder`
3. `spyder`

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.5.2
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Ubuntu 16.04 LTS

**Comment by ccordoba12** [comment]
Please post the output of `pip freeze` when run in your virtualenv.

**Comment by kuo000** [comment]
@ccordoba12 Thanks for the quick response.

Here's the result of `pip freeze`:
```bash
alabaster==0.7.10
astroid==1.5.3
Babel==2.4.0
bleach==2.0.0
certifi==2017.4.17
chardet==3.0.4
decorator==4.1.2
docutils==0.13.1
entrypoints==0.2.3
html5lib==0.999999999
idna==2.5
imagesize==0.7.1
ipykernel==4.6.1
ipython==6.1.0
ipython-genutils==0.2.0
isort==4.2.15
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-core==4.3.0
lazy-object-proxy==1.3.1
MarkupSafe==1.0
mccabe==0.6.1
mistune==0.7.4
nbconvert==5.2.1
nbformat==4.3.0
numpydoc==0.7.0
pandocfilters==1.4.1
pexpect==4.2.1
pickleshare==0.7.4
pkg-resources==0.0.0
prompt-toolkit==1.0.14
psutil==5.2.2
ptyprocess==0.5.2
pycodestyle==2.3.1
pyflakes==1.5.0
Pygments==2.2.0
pylint==1.7.2
PyOpenGL==3.1.0
PyQt5==5.9
python-dateutil==2.6.1
pytz==2017.2
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.0
QtPy==1.2.1
requests==2.18.2
rope==0.10.5
simplegeneric==0.8.1
sip==4.19.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.0
testpath==0.3.1
tornado==4.5.1
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.10.10
```

**Comment by goanpeca** [comment]
@kuo000 it might be something related to PyQt5==5.9

**Comment by ccordoba12** [comment]
This is bug in Ubuntu:

https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1590737

so I'm sorry, but there's nothing we can about it in our side.

----

You can find a possible solution here:

https://forum.qt.io/topic/74998/failed-to-create-opengl-context-for-format-qsurfaceformat-in-qt-5-6-0

but I really don't know what's meant for it.

**Comment by kuo000** [comment]
@ccordoba12 Understood.

Thanks for taking the time to investigate this!

**Comment by ccordoba12** [comment]
@jaxankey, it looks like a bug with the Nvidia drivers, so you should switch to use your Intel card instead.

**Comment by jaxankey** [comment]
No idea how you know that, but thank you! I changed from nvidia-390.59 to nvidia-396.24 in Mint's driver manager, and it works now.

Strange that it _suddenly_ happened like this, but glad it's fixed!

Thanks again,
Jack

**Comment by ccordoba12** [comment]
> No idea how you know that, but thank you!

Well, it was reported in the Ubuntu bug I linked above :-)

**Comment by sebma** [comment]
@ccordoba12 I have the same pb.

Which version of spyder can I downgrade to, to make spyder work back again ?

**Comment by sebma** [comment]
@ccordoba12 I also this error before the `Failed to create OpenGL context` message : 

`AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'`

Any idea ?

**Comment by luolitao** [comment]
@sebma https://github.com/spyder-ide/spyder/issues/7415

**Comment by sebma** [comment]
@luolitao Hi, can please reopen because mine is not solved, here is what I did : 

`conda update qt pyqt spyder` and I still get : 
```
$ spyder &
[1] 31885
$
 WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::SwapBehavior(DefaultSwapBehavior), swapInterval 1, profile  QSurfaceFormat::OpenGLContextProfile(NoProfile))

[1]+  Aborted                 (core dumped) spyder
```

**Comment by ccordoba12** [comment]
@sebma, there's nothing we can do about this in Spyder because it's a problem with your graphic card drivers.

So please update them or use your Intel card instead of your Nvidia one, and try again.

**Comment by Magicwangs** [comment]
As For Me, i just 
`conda install pyqt=4`
and then `conda install tensorflow-gpu` (something you need, which will install pyqt5 automaticly)
thing goes well now, maybe it just because i miss something when i install spyder

**Comment by beniroquai** [comment]
@Magicwangs Thanks a ton! It worked! :)
