### ISSUE TITLE
TypeError: 'Icon' object is not callable

### ISSUE THREAD

**Issue by wlsdnen** [spyder-ide/spyder#4817]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\users\jjw\appdata\local\programs\python\python35\lib\site-packages\spyder_terminal\terminalplugin.py", line 156, in __wait_server_to_start
    QMessageBox.Ok)
TypeError: 'Icon' object is not callable

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.5.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by andfoy** [comment]
This issue was moved to spyder-ide/spyder-terminal#96

**Comment by andfoy** [comment]
This issue was moved to spyder-ide/spyder-terminal#97

**Comment by andfoy** [comment]
@wlsdnen Thanks for your report, however this bug belongs to spyder-terminal.
