### ISSUE TITLE
in 3.20, spyder will create multiple instances

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#4818]
in 3.20, spyder will create multiple instances.
in 3.0.2, there's no such bug. but after that, this bug happens

**Comment by ccordoba12** [comment]
I'm sorry but I'm going to ask you to open a new bug and fill in all the information we ask in our issue template, i.e. operating system, qt version, etc.

**Comment by ccordoba12** [comment]
Please never again skip that information if you want our help. We put it there for a reason.
