### ISSUE TITLE
Error whe rearranging tabs and multiple Editors

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4831]
https://github.com/spyder-ide/spyder/issues/564#issuecomment-318436787

## Description of your problem

When I have two editors open with Spyder 3.2 (MacOS X version), I can rearrange the tabs in either window. When I do this with say editor 1, the filename tab order will update on both editors, but editor 2 will not update the actual file in that location. So in editor 1 I will change the order to File2, File1, File3, then editor 2 will show the tab order as File2, File1, File3--but the contents of editor 2 are still File1, File2, File3. Also, if I am editing the contents of File2 in editor 2 (labeled File1), File2 will not save until I switch to the tab labeled File2 in either editor--regardless of the file contents shown. However, the file does save correctly. A restart of Spyder fixes the labeling problem, but any rearrangement of the tabs has the same effect.

**Comment by ccordoba12** [comment]
@rlaverde, thanks for opening this issue.

**Comment by avylove** [comment]
Having the same issue. Even if you close a file, you may still have a mislabeled tab open with that file's contents.

This should be marked critical and fixed in 3.2.1 rather than 3.2.2
