### ISSUE TITLE
Spyder crashed in the middle of debug

### ISSUE THREAD

**Issue by yanggehua** [spyder-ide/spyder#4832]
## Description

**What steps will reproduce the problem?**

1.  change source code while debugging
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/opt/anaconda2/lib/python2.7/site-packages/spyder/widgets/editortools.py", line 490, in clicked
    self.activated(item)
  File "/opt/anaconda2/lib/python2.7/site-packages/spyder/widgets/editortools.py", line 481, in activated
    if _id == editor_id and editor.parent() is parent:
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/spyder/widgets/editortools.py", line 490, in clicked
    self.activated(item)
  File "/opt/anaconda2/lib/python2.7/site-packages/spyder/widgets/editortools.py", line 481, in activated
    if _id == editor_id and editor.parent() is parent:
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.2 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. What did you *exactly* do to change source code while debugging?

Please be more specific because your comment is very vague...

**Comment by ccordoba12** [comment]
Most of these error will be fixed in Spyder 4.
