### ISSUE TITLE
Set working directory button(blue check mark) not functional

### ISSUE THREAD

**Issue by ghltshubh** [spyder-ide/spyder#4834]
## Description of your problem
Set working directory button on the top right is missing or sort of overlapping with the directory path selection drop down. Therefore have to use the keyboard shortcut F5 to set working directory.

**What steps will reproduce the problem?**

1. Choose a directory path from the top right drop down.
2. The set working directory button seems to be overlapping with directory path drop down (blue check mark) which can't be selected therefore have to use F5 keyboard shortcut.

**What is the expected output? What do you see instead?**
The set working directory should be outside the dropdown.

**Please provide any additional information below**
It looks like 
<img width="777" alt="screen shot 2017-07-27 at 10 42 48 pm" src="https://user-images.githubusercontent.com/16928813/28701655-2733942e-731d-11e7-87c6-3399622f4960.png">

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: macOS 10.12.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
That button is not supposed to be selectable, so I don't understand exactly what we should fix...

**Comment by ghltshubh** [comment]
I saw this in this video and thought it was supposed to be selecting the working directory
<img width="208" alt="screen shot 2017-07-27 at 11 03 48 pm" src="https://user-images.githubusercontent.com/16928813/28702050-1503bbb4-7320-11e7-8818-f9ca0d32e705.png">

**Comment by ccordoba12** [comment]
That's using and old Spyder version. When you select a new directory from the dropdown menu, it will automatically be set in your current console.
