### ISSUE TITLE
Python Exit Function Restarts IPython Kernel

### ISSUE THREAD

**Issue by slakerjaker** [spyder-ide/spyder#4840]
## Description

**What steps will reproduce the problem?**

1.  Running Script With exit Function in it to end script
2.  Running Script with quit Function in it to quit script

**What is the expected output? What do you see instead?**
For the script to end and a new line in the IPython console to appear
Connecting to kernel, kernel restart

**Please provide any additional information below**
Once the exit or quit function is run, the IPython console goes to white screen where it says 'Kernel Restarting'.

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
That's what is supposed to do, so it's working correctly.
