### ISSUE TITLE
Setting  QT_SCREEN_SCALE_FACTORS is not working as expected

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4841]
https://github.com/spyder-ide/spyder/issues/4316#issuecomment-318641751

**Comment by ccordoba12** [comment]
I think the solution is to use `QT_SCALE_FACTOR` when users only pass one value to `high_dpi_custom_scale_factors` and `QT_SCREEN_SCALE_FACTORS` when there are several of them.

@rlaverde, please open a PR with that and ask the last user that reported the problem on issue #4316 to test it.
