### ISSUE TITLE
Add ability to change Ctrl+PgUp and PgDn shortcuts

### ISSUE THREAD

**Issue by gabrielclow** [spyder-ide/spyder#4842]
I really dislike editors with MRU behaviour but at the same time I really like Ctrl+Tab and Ctrl+Shift+Tab because I don't have to remove my hand from the mouse like with Ctrl+PgUp or PgDn. I wish I had the ability to customize Ctrl+PgUp and PgDn just like Tab and Shift+Tab so I could replace them and use my preferred behaviour with my preferred shortcuts.

Thanks in advance

**Comment by ccordoba12** [comment]
Sorry, that's not possible in Qt applications, i.e. we have to hardcode those shortcuts in the application itself.

**Comment by gabrielclow** [comment]
I guess I'm just gonna workaround it with Autohotkey then
But I'm just curious, why can I change the MRU shortcuts and not the PgUp and PgDn? They are hardcoded in the Qt Tab widgets?

Many thanks for the fast reply

![image](https://user-images.githubusercontent.com/9113853/28723391-f87a385c-738c-11e7-8759-134caaa7e73a.png)

**Comment by ccordoba12** [comment]
Sorry, I rushed too much to find something to do about this one.

**Comment by ccordoba12** [comment]
Almost all our shortcuts are customizable, and this shouldn't be the exception.

**Comment by gabrielclow** [comment]
That's great! I'm glad to know it's possible. Thanks for your great work on Spyder.

**Comment by rlaverde** [comment]
MRU shortcuts aren't hard coded, but they should have the key Ctrl, and be similar (only one different key) to work correctly.
