### ISSUE TITLE
Pressing Ctrl+Tab wanting to switch to another tab raises an IndexError

### ISSUE THREAD

**Issue by Nikished** [spyder-ide/spyder#4844]
## Description

**What steps will reproduce the problem?**

Press Ctrl+Tab in Spyder. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\nbobrovskiy\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2184, in keyReleaseEvent
    self.tabs_switcher.item_selected()
  File "C:\Users\nbobrovskiy\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 370, in item_selected
    index = self.stack_history[-(self.currentRow()+1)]
  File "C:\Users\nbobrovskiy\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 307, in __getitem__
    return self.id_list.index(self.history[i])
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3

**Comment by goanpeca** [comment]
@rlaverde please fix this one

**Comment by Nikished** [comment]
Exact steps to reproduce this error: Press Ctrl + Tab and then W as well. Current version is unable to handle such situations.
