### ISSUE TITLE
Error when trying to load third-party plugins

### ISSUE THREAD

**Issue by tienhv** [spyder-ide/spyder#4851]
## Description

**What steps will reproduce the problem?**

1. Start sypder.
2. 
3. 

**What is the expected output? What do you see instead?**
It shows right away after starting Spyder.

**Please provide any additional information below**
A message box show this:
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
AttributeError: 'NoneType' object has no attribute 'load_module'
![image](https://user-images.githubusercontent.com/9072983/28740752-f2f86f42-7432-11e7-84e5-539b3cf0e641.png)

Spyder functions fine, no problem after close the message box.
## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Do you have any additional Spyder module installed, like `spyder-terminal`?

**Comment by ccordoba12** [comment]
If that's the case, please uninstall them. This error is only caused because of third-party plugins.
