### ISSUE TITLE
Errror: Cannot open Tools->References Dialog!

### ISSUE THREAD

**Issue by peakerlee2016** [spyder-ide/spyder#4852]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/lgf/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 2579, in edit_preferences
    widget.initialize()
  File "/home/lgf/anaconda2/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 75, in initialize
    self.load_from_conf()
  File "/home/lgf/anaconda2/lib/python2.7/site-packages/spyder/plugins/configdialog.py", line 379, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --reset

and try again. That should fix your problem.
