### ISSUE TITLE
Error when trying to show indentation guidelines

### ISSUE THREAD

**Issue by ChiiMin** [spyder-ide/spyder#4854]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Python\spyder-master\spyder\plugins\editor.py", line 2188, in toggle_show_indent_guides
    for editorstack in self.editorstacks:
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 4.0.0.dev0 
* Python Version: 3.6.1
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting.

@rlaverde, I think this probably happens at startup.
