### ISSUE TITLE
Some issues with dedicated consoles

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#4856]
The dedicated run in ipython console has some issues.

1.) When a script runs, there is a flash for a moment of
<img width="698" alt="screen shot 2017-07-29 at 11 21 25" src="https://user-images.githubusercontent.com/3627835/28746344-17753270-7450-11e7-8d6b-cc1dfbe17b65.png">
before it goes blank again, but then

2.) any output (prints, exceptions) that may or may not occur in the script never show up

3.) Changing the working directory (file explorer, global working directory) every time a new scripts runs turns out to be a very annoying behavior, and I think we should rethink that

**Comment by ccordoba12** [comment]
> When a script runs, there is a flash for a moment of

That's an easy fix.

> any output (prints, exceptions) that may or may not occur in the script never show up

This probably happens the first time you run in a dedicated console. Errors always appear for me afterwards.

> Changing the working directory (file explorer, global working directory) every time a new scripts runs turns out to be a very annoying behavior, and I think we should rethink that

This has been the default behavior for all Spyder history, i.e. changing the cwd to the current file directory on execution, so I'm reluctant to change it.

We are now simply reflecting that in our UI, which is what most people wanted.

**Comment by goanpeca** [comment]
>This probably happens the first time you run in a dedicated console. Errors always appear for me afterwards.

Yes, indeed, but this is still a bug, users should not need to run a script twice to see what failed.

>This has been the default behavior for all Spyder history, i.e. changing the cwd to the current file directory on execution, so I'm reluctant to change it.
We are now simply reflecting that in our UI, which is what most people wanted.

It may be, but it provides a very annoying experience

**Comment by ccordoba12** [comment]
> Yes, indeed, but this is still a bug, users should not need to run a script twice to see what failed.

Sure, I just wanted to verify that it only happens once.

> It may be, but it provides a very annoying experience

Please propose an alternative. Just complaining is not constructive.

**Comment by goanpeca** [comment]
I guess I have to adapt my workflow. If I think of something, will let you know

**Comment by ccordoba12** [comment]
We could change the default option to *not* change the cwd on evaluation, which I also think is a saner default.

@rlaverde, @dalthviz, @andfoy, what do you think?

**Comment by rlaverde** [comment]
>We could change the default option to not change the cwd on evaluation, which I also think is a saner default.

Yes, I also find annoying that the cwd changes too frequently

**Comment by andfoy** [comment]
I agree with @rlaverde and @ccordoba12

**Comment by ccordoba12** [comment]
Ok, I'll work on this one for 3.2.2
