### ISSUE TITLE
first try with recent plugins (spyder-reports creates problems ?)

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#4857]
## Description

**What steps will reproduce the problem?**

1. launch spyder
2. a loud bang occures, after 6 kernel deaths, with the window 
````
    plugin.register_plugin()
    self.report_widget.set_html_from_file(html_path)
    with codecs.open(filename, encoding="utf-8") as file:
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\famille\\AppData\\Local\\Temp\\welcome.html'
WARNING:traitlets:kernel died: 6.001707315444946
````
3. not sure what may or may not work after that, as spyder started

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin.register_plugin()
    self.report_widget.set_html_from_file(html_path)
    with codecs.open(filename, encoding="utf-8") as file:
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\famille\\AppData\\Local\\Temp\\welcome.html'
WARNING:traitlets:kernel died: 6.001707315444946

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.2rc2
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by stonebig** [comment]
if I remove spyder-terminal, kernel dies two times, and I get a:
````
    plugin.register_plugin()
    self.report_widget.set_html_from_file(html_path)
    with codecs.open(filename, encoding="utf-8") as file:
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\famille\\AppData\\Local\\Temp\\welcome.html'
WARNING:traitlets:kernel died: 6.001142263412476
````

**Comment by goanpeca** [comment]
@rlaverde seems related to spyder-reports

**Comment by stonebig** [comment]
checking by uninstalling spyder-reports ...

**Comment by stonebig** [comment]
maybe shall I try to recompile spyder-reports from master ? https://github.com/spyder-ide/spyder-reports/issues/36

**Comment by stonebig** [comment]
ok, it works with spyder-reports master of today

**Comment by ccordoba12** [comment]
> spyder-terminal works \o/ , amazing feat !

That has been @andfoy's feat! Thanks for your incredible work on `spyder-terminal` @andfoy!

**Comment by stonebig** [comment]
Thanks @andfoy ! you did something stated as "impossible".

![spyder-terminal](https://user-images.githubusercontent.com/4312421/28747505-73353a60-74a0-11e7-8670-734617bd33cb.PNG)
