### ISSUE TITLE
how to relaunch "spyder-notebook" after a failed (because slow) start ?

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#4858]
at first slow start, I get a syder-notebook time-out.
![spyder_notebook_slow_start](https://user-images.githubusercontent.com/4312421/28748141-f66ab93c-74af-11e7-88fa-72d4389122b4.PNG)

Then, even if i ask Display->Notebook, I get a grey window and don't know how to relaunch the spyder-notebook process . Is there a way ? if not, could there be ?

**Comment by ccordoba12** [comment]
@stonebig, please open issues about each plugin in its corresponding repo instead of here.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #93](https://github.com/spyder-ide/spyder-notebook/issues/93) via [**ZenHub**](https://www.zenhub.com/)
