### ISSUE TITLE
spyder 3.2.0, pep8 config file is not used.

### ISSUE THREAD

**Issue by lmeyn** [spyder-ide/spyder#4867]
## Description of your problem

~/.config/pep8 has:
max-line-length = 89

However, the editor flags lines greater than 79 characters

This worked in spyder 3.14, but does not work in spyder 3.20

## Versions and main components

* Spyder Version: 3.20
* Python Version: Python 3.6.1 |Anaconda custom (x86_64) (Used "conda update spyder" to get 3.20)
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: OS X 10.11.6 

## Dependencies

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by rlaverde** [comment]
We updated `pep8` to `pycodestyle`, please move your configuration file to `~/.config/pycodestyle`

**Comment by ccordoba12** [comment]
Closing because we can't do anything about it.
