### ISSUE TITLE
Can't change color of Help pane

### ISSUE THREAD

**Issue by sidverm** [spyder-ide/spyder#4872]
## Description

**What steps will reproduce the problem?**

1. Go to preferences
2. Go to Help 

**What is the expected output? What do you see instead?**
I expected 'change background color' or 'select color theme'
But there is no way to change it. 

**Please provide any additional information below**
I prefer working in Sublime Text like dark background. With lots of effort I found a way to change the background of editor and ipython panes separately (though the 'dark' colors are not identical, which sucks) and the worst thing to see is a two dark panes with one white pane (This help pane on top right)! That would have been the minimum for me to move from Sublime to Spyder though the best would be if there was overall theme 
that magically change all panes, toolbars etc to a dark theme or a developer prefers!

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting.

We're aware of this problem and working to fix it in Spyder 4, to be released next year.
