### ISSUE TITLE
Anaconda Navigator doesn't launch spyder app 3.2.0

### ISSUE THREAD

**Issue by castorgit** [spyder-ide/spyder#4874]
## Description of your problem
After upgrade to spyder 3.2.0 Anaconda navigator doesn't launch spyder.
Windows 10
spyder can be launched by typing >spyder in cmd promt

**What steps will reproduce the problem?**

1. run anaconda navigator (1.6.3)
2. launch spyder from anaconda navigator 
3. nothing happens

**What is the expected output? What do you see instead?**
nothing

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Closing because without further info we can't help you, sorry.

**Comment by castorgit** [comment]
IPython >=4.0    :  5.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
... sorry I was away

**Comment by castorgit** [comment]
as I said the issue is with the anaconda launch. I press launch spyder and nothing happens
