### ISSUE TITLE
Run Configuration per file: Working Directory not remembered

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#4879]
## Description of your problem

**What steps will reproduce the problem?**

1. Open the `Run > Configuration per file...` dialog.
2. Check `Working Directory settings > The following directory:`.
3. Select a path.
4. `Run` the file.
5. Open the `Run > Configuration per file...` dialog again.

**What is the expected output? What do you see instead?**

I would expect to still see the path selected in step 3. in the directory box, but this box is empty.

**Please provide any additional information below**

`Run > Run` the file directly still honours the path selected in step 3.

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: Python 3.5.2 64bits
* Qt Version: Qt 5.5.1
* PyQt Version: PyQt5 5.5.1
* Operating system: Linux

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix it after we release 3.2.1
