### ISSUE TITLE
Force-stop does not work on hanged progress.

### ISSUE THREAD

**Issue by CYUlysses** [spyder-ide/spyder#4881]
## Description

**What steps will reproduce the problem?**

1. Have a hanged process (memory overflow). Hitting "stop" button and "Ctrl+C"/"Ctrl+Z" does not work..
2. Try closing the console + terminate kernel
3. Got it.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\envs\py3conda\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1235, in close_client
    self.filenames.pop(index)
IndexError: pop index out of range

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
So do you get this error after closing a hanged console?

**Comment by CYUlysses** [comment]
Yes. I just realized I forgot one thing. Before terminating the hanged console, I opened a new console (and another one sharing the same kernel as the new console) just to see whether Spyder itself was hanged. The error first popped up when I tried to terminate the newly created consoles, and popped up again when I tried to terminate the hanged console.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

To have the equivalent of a hanged console, you can run this code on it

```python
while True:
    1
```
