### ISSUE TITLE
Error when returning from full screen

### ISSUE THREAD

**Issue by JPelda** [spyder-ide/spyder#4882]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/johannes/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2236, in maximize_dockwidget
    self.last_plugin.dockwidget.toggleViewAction().setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'dockwidget'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux
* ubuntu 16
## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this error after we release Spyder 3.2.1

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one. I think this happens when one of the new plugins (notebook, terminal, etc).

**Comment by dalthviz** [comment]
@ccordoba12  testing this in Windows with spyder reports I get:
 ```
File "c:\users\daniel\anaconda3\envs\scipy_test\lib\site-packages\spyder\app\mainwindow.py", line 2257, in maximize_dockwidget
    self.last_plugin.get_focus_widget().setFocus()
AttributeError: 'NoneType' object has no attribute 'setFocus'
```
It's not the same line but maybe could be related?

**Comment by ccordoba12** [comment]
Are the other plugins ok when maximizing/minimizing them?

**Comment by andfoy** [comment]
I've implemented that method on Spyder-terminal and Spyder-vim, respectively

**Comment by dalthviz** [comment]
Yep, it only happened with the reports plugin when testing.

**Comment by ccordoba12** [comment]
Ok, great. @rlaverde already opened an issue about this problem in `spyder-reports`, so we can safely close this one.

**Comment by rlaverde** [comment]
Maybe we could avoid this error from happening again in other external plugins adding a checking in the `SpyderPluginWidget.__init_subclass__`
