### ISSUE TITLE
prefix 'b' of bytes is not highlighting in the editor window

### ISSUE THREAD

**Issue by fanstvn** [spyder-ide/spyder#4884]
## Description

**What steps will reproduce the problem?**

when inputting the bytes-type string in the editor window, the prefix 'b' is not highlighting with the same color of string.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by goanpeca** [comment]
@fanstvn could you add a screenshot?

**Comment by ccordoba12** [comment]
I don't think we're going to address this, but pull requests are welcome.

**Comment by goanpeca** [comment]
@ccordoba12 I think it should be fairly simple? also we should add f strings, no?
