### ISSUE TITLE
Spyder got crashed last session when windows pc shut down suddenly. I tried 'conda update spyder'. However, spyder is not starting. 

### ISSUE THREAD

**Issue by Niladri365** [spyder-ide/spyder#4888]
## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by dalthviz** [comment]
Hi @Niladri365 could you try in `cmd` or terminal `spyder --reset`?

**Comment by Niladri365** [comment]
It worked...Thank you.. I was trying with conda spyder --reset.

**Comment by dalthviz** [comment]
Nice, thanks for the response :)
