### ISSUE TITLE
pandas display freezes spyder when loading column with subscript

### ISSUE THREAD

**Issue by faraonlatino** [spyder-ide/spyder#4890]
## Description
Loading pd.read_csv(myfile) freezes spyder when column name contains a superscript or subscript (for units) 
**What steps will reproduce the problem?**

1. load file with superscript in the column name
2. try seeing the pandas variable at the variable explorer window in spyder

**What is the expected output? What do you see instead?**
spyder freezes

## Version and main components

* Spyder Version: 2.3.5.2 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  2.4.1 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.2 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  None (NOK)
pylint >=0.25   :  1.4.3 (OK)

```

**Comment by ccordoba12** [comment]
We don't support Spyder 2.3 anymore. Besides, I'd recommend you to use Python 3 to deal with files with unicode symbols because it's much better at it.
