### ISSUE TITLE
PEP8 Naming conventions

### ISSUE THREAD

**Issue by koog1000** [spyder-ide/spyder#4893]
Any plans to integrate flake8 with pep8-naming into spyder? Or is there an easy way to do this on my own?

**Comment by ccordoba12** [comment]
We don't have plans to do that in the short term, sorry.

**Comment by koog1000** [comment]
Thanks for the quick response. I hacked it in so I have it for the moment.

**Comment by Prikers** [comment]
@koog1000 would you be able share your trick?

**Comment by koog1000** [comment]
use pip to install flake8 and pep8-naming
in spyder.utils.codeanalysis.check_with_pep8 replace the following:

        args = get_checker_executable('pycodestyle')
        results = check(args, source_code, filename=filename, options=['-r'])
with:

        #args = get_checker_executable('pycodestyle')
        args = ['flake8']
        results = check(args, source_code, filename=filename)  #, options=['-r'])

This is not a good hack. It doesn't do any checking to see if flake8 is installed or any version checking or that the command is setup correctly. It is just the minimum change to add the pep8 naming warnings to spyder.

I'm running Spyder 3.2.0 with Python 2.7.10 32bit on Windows 7.
