### ISSUE TITLE
Spyder naming for Arch Linux distribution

### ISSUE THREAD

**Issue by muflone** [spyder-ide/spyder#4900]
## Description of your problem

There's some discussions in the [Arch Linux bug tracker] about the Spyder naming for the Python 2.x and Python 3.x versions.

Since the 2010 Arch Linux has changed the default [python symlink to point to python 3.x], therefore the default python command now uses Python 3.x.
Every related Python command uses the same schema, except Spyder which actually is an exception in the Arch Linux world.

Can I have the upstream opinion on a naming change for spyder and spyder3 executables?

The naming change would be:
/usr/bin/spyder2 would point to the Python 2.x version
/usr/bin/spyder3 would point to the Python 3.x version
/usr/bin/spyder would be a symlink to /usr/bin/spyder3

My objections are mainly for upstream colliding names, in order also to avoid the issues opening with incoerent names with your naming.

**What steps will reproduce the problem?**

1. Install spyder and spyder3 packages in Arch Linux (pacman -S spyder spyder3)
2. Observe the executables names ($ pacman -Ql spyder spyder3 | grep '/usr/bin/spyder*')
```
spyder /usr/bin/spyder
spyder3 /usr/bin/spyder3
```
3. Execute spyder to launch Spyder for Python 2.x

[Arch Linux bug tracker]: https://bugs.archlinux.org/task/51437
[python symlink to point to python 3.x]: https://www.archlinux.org/news/python-is-now-python-3/

**Comment by ccordoba12** [comment]
This is something we can't do anything about. It has to be solved by the Arch developers.

**Comment by muflone** [comment]
I'm the Arch Linux spyder maintainer, I would be glad to hear your opinion.
The naming scheme will influence how the Arch Linux users will report you the issues.

**Comment by jitseniesen** [comment]
We can do something about the `setup.py` though. At the moment, we install as `spyder` for Python 2 and `spyder3` for Python 3 (on Linux). At some point we probably want to change this, probably on a major version (e.g. Spyder 4, or maybe that's too soon).

I think it will be helpful for Arch Linux and other distributions if we have a plan for this.

**Comment by ccordoba12** [comment]
> I'm the Arch Linux spyder maintainer, I would be glad to hear your opinion.

Sorry, I read this too quickly.

> The naming change would be:
/usr/bin/spyder2 would point to the Python 2.x version
/usr/bin/spyder3 would point to the Python 3.x version
/usr/bin/spyder would be a symlink to /usr/bin/spyder3

I'm fine with this. This is, of course, an Arch particular problem. I think other distributions (e.g. Ubuntu) will maintain the convention to point the `spyder` executable to the Python 2 version.

As @jitseniesen said, we could revisit this in the future, but not until other major distributions decide to it.

**Comment by eli-schwartz** [comment]
The python distribution itself uses python2 and python3, and specifies that `python` should be a symlink to the default system python (which they recommend should be python2). This rule is also applied to all the commands shipped with python2 and python3.

I think thematically any application that works with the python interpreter itself should follow the same guidelines. (In fact, any application that ships executables for both python2 and python3, but in practice only for anything that has functionality specific to the version of python it runs with, e.g. IDEs, pip, source code linters... for anything else you only need the one for the default system python.)
It would be entirely appropriate for said application to use e.g. spyder2, even if you also default to symlinking spyder ==> spyder2 *as Python itself does*. Arch Linux can set our own symlinks for the default version. :smile:

This would essentially preserve the current state of things, while making it somewhat easier for downstream packagers to 1) intuit what the executable names are meant to be, and 2) package it appropriately as per downstream policy.

**Comment by ccordoba12** [comment]
That's way too confusing for *our* current state of things.

As I said, I don't have objections to Arch renaming our Python 2 executable and making `spyder` to point to the Python 3 one. But we're not going to move in that direction in the short term, sorry.

**Comment by muflone** [comment]
So it was done in [spyder 2.3.0-1](https://www.archlinux.org/packages/?sort=&q=spyder&maintainer=&flagged=)

**Comment by ccordoba12** [comment]
Yeah, 3 years ago.

**Comment by muflone** [comment]
ahah indeed... I meant 3.2.0-1
