### ISSUE TITLE
view the df in variable explorer

### ISSUE THREAD

**Issue by harryliuhao** [spyder-ide/spyder#4901]
## Description

**What steps will reproduce the problem?**

1. view the df in variable explorer
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Hao Liu\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 527, in <lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "C:\Users\Hao Liu\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 544, in editor_accepted
    data = self._editors[editor_id]
KeyError: 1286220525784

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Please post the code you used to generate the Dataframe you are tying to see.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
