### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by Zousiyu** [spyder-ide/spyder#4902]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin.register_plugin()
    self.create_new_client(give_focus=False)
    welcome_client = self.create_welcome_client()
    welcome = open(WELCOME).read()
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zousiyu\\Anaconda3\\lib\\site-packages\\spyder_notebook\\utils\\templates\\welcome.html'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This is an issue with our notebook package. We're working to fix it right now.
