### ISSUE TITLE
Turning off line wrapping in the iPython console

### ISSUE THREAD

**Issue by bbenneke** [spyder-ide/spyder#4904]
## Description of your problem

Now that the regular python console was removed in Spyder 3.2, we really need to be able to turn off the text wrapping in the iPython console. Our outputs of large tables and arrays are unreadable due to the line wrapping.

I would suggest an option in the preference menu similar to the one that had existed for the python console for a long time.

**What steps will reproduce the problem?**

1. Running any code in ipython script
2. Displaying a big table or array (or long text). The table will wrap and be almost unreadable due to the line wrapping.
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2
* Python Version: 2.7
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please open an issue about this in 

https://github.com/jupyter/qtconsole

We can't do anything about it in Spyder.
