### ISSUE TITLE
right click on splitted tab gives an error and does not shows the manu

### ISSUE THREAD

**Issue by navidRashik** [spyder-ide/spyder#4909]
## Description

**What steps will reproduce the problem?**

1. right click on splitted tab
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/navid/.local/lib/python2.7/site-packages/spyder/widgets/editor.py", line 1236, in __setup_menu
    add_actions(self.menu, list(actions)+self.__get_split_actions())
  File "/home/navid/.local/lib/python2.7/site-packages/spyder/utils/qthelpers.py", line 311, in add_actions
    target.addAction(action)
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by rlaverde** [comment]
This is similar to #4843, and will be fixed in spyder3.2.1
