### ISSUE TITLE
Can't open or create a new notebook in Spyder on Mac OSX

### ISSUE THREAD

**Issue by tvashtar** [spyder-ide/spyder#4911]
## Description

**What steps will reproduce the problem?**

1. pip install spyder-notebook 
2. Open Spyder
3. Try to Open or create a New Notebook

**What is the expected output? What do you see instead?**

I expected to get a notebook, but I just get an error message, on Mac OSX running Sierra. Note I do have jupyter installed (version 1.0.0), but it seems to be looking for something else?

**Please provide any additional information below**

  File "/Users/conor/anaconda/envs/P3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 314, in create_new_client
    server_info = nbopen(filename)
  File "/Users/conor/anaconda/envs/P3/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 75, in nbopen
    proc = subprocess.Popen(command, creationflags=creation_flag)
  File "/Users/conor/anaconda/envs/P3/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/conor/anaconda/envs/P3/lib/python3.6/subprocess.py", line 1326, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.4.1 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by andfoy** [comment]
Issue moved to [spyder-ide/spyder-notebook #106](https://github.com/spyder-ide/spyder-notebook/issues/106) via [**ZenHub**](https://www.zenhub.com/)
