### ISSUE TITLE
pep8 config now being ignored

### ISSUE THREAD

**Issue by pdrembelas** [spyder-ide/spyder#4917]
After updating to Spyder 3.2 it seems my .pep8 file is no longer being read / respected. It seems Spyder has traded reading in .pep8 file for .pycodestyle but there was no warning this was being done? I finally noticed a note in the changelog that suggested something like this had happened. It would be nice if the .pep8 file was renamed .pycodestyle on update or some kind of warning was issued.

On a related note. I've never been able to get a project level config file to work. Is this something that's been addressed and now works?

**What steps will reproduce the problem?**

Have a .pep8 file

**What is the expected output? What do you see instead?**

The only thing in my .pep8 file was max-line-length = 120

So, I expected the code style analysis to be ok with lines greater than the default 79 characters but it was not.

**Please provide any additional information below**

After adding a .pycodestyle file to my user directory with the [pycodestyle] tag instead of [pep8] my settings were read in fine.

## Versions and main components

* Spyder Version: 3.2
* Python Version: 3.6.1
* Qt Version: N/A
* PyQt Version: N/A
* Operating system: Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by rlaverde** [comment]
This is duplicated of #4867 

> After adding a .pycodestyle file to my user directory with the [pycodestyle] tag instead of [pep8] my settings were read in fine.

Yes, that's the solution, we updated `pep8` to `pycodestyle` (the package was renamed), then the config file has to be changed http://pycodestyle.pycqa.org/en/latest/intro.html#configuration
