### ISSUE TITLE
spyder notebook fails to open notebook

### ISSUE THREAD

**Issue by jcoady** [spyder-ide/spyder#4919]
## Description

I clicked on notebook tab in spyder. The notebook document entitled "untitled0" was completely blank.

**What steps will reproduce the problem?**

1. On windows machine I did pip install spyder-notebook 
2. Launch spyder
3. Click on notebook tab in spyder. 

**What is the expected output? What do you see instead?**
I expected to see the notebook appear in the contents of "untitled0" tab of spyder. Instead the contents were completely blank, no notebook cells were present. No notebook buttons were present on the screen.

**Please provide any additional information below**

  File "C:\Users\John\Anaconda2\envs\py3k\lib\site-packages\spyder_notebook\notebookplugin.py", line 419, in open_console
    kernel_id = client.get_kernel_id()
  File "C:\Users\John\Anaconda2\envs\py3k\lib\site-packages\spyder_notebook\widgets\client.py", line 220, in get_kernel_id
    sessions_url = self.get_session_url()
  File "C:\Users\John\Anaconda2\envs\py3k\lib\site-packages\spyder_notebook\widgets\client.py", line 216, in get_session_url
    return self.add_token(url_path_join(self.server_url, 'api/sessions'))
  File "C:\Users\John\Anaconda2\envs\py3k\lib\site-packages\spyder_notebook\widgets\client.py", line 157, in add_token
    token_url = url + '?token={}'.format(self.token)
AttributeError: 'NotebookClient' object has no attribute 'token'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >

**Comment by andfoy** [comment]
Issue moved to [spyder-ide/spyder-notebook #109](https://github.com/spyder-ide/spyder-notebook/issues/109) via [**ZenHub**](https://www.zenhub.com/)
