### ISSUE TITLE
I have installed anaconda on my linux-ubuntu 16.04. I have used it earlier on windows 10. But like win-10, on ubuntu i am not getting any spyder GUi based launchers, I have to access it from terminal. How do i get to use full features of anaconda without using terminal? 

### ISSUE THREAD

**Issue by ansh997** [spyder-ide/spyder#4923]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/ansh/miniconda3/lib/python3.6/site-packages/spyder/widgets/waitingspinner.py", line 177, in rotate
    def rotate(self):
KeyboardInterrupt

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
There's no way to start Spyder in a graphical way for Anaconda on Linux, sorry.

**Comment by ccordoba12** [comment]
There's anaconda-navigator though, but you have to start that one from a terminal too.

**Comment by wildintellect** [comment]
There is a fix, by creating a desktop launcher file. See https://askubuntu.com/questions/1017284/cant-create-anaconda-shortcut-to-launch-from-desktop-on-ubuntu-17-10

~/.local/share/applications/spyder3.desktop
```
[Desktop Entry]
Type=Application
Name=Spyder
Exec=/home/username/anaconda3/bin/spyder
Terminal=false
Icon=/usr/share/app-install/icons/spyder3.png
```

**Comment by merismsk** [comment]
If you want to launch Spyder GUI, then install it separately as 
sudo apt install spyder

**Comment by jakob1379** [comment]
> 
> 
> If you want to launch Spyder GUI, then install it separately as
> sudo apt install spyder

Or just create a .desktop file. I find the easiest to just copy one and alter it to suite my needs

**Comment by clarkbrent** [comment]
> If you want to launch Spyder GUI, then install it separately as
> sudo apt install spyder

I'd be hesitant to suggest this since there are extra steps involved if you go this route since Spyder won't be using the correct conda environment by default. It's much easier to just use the bin provided by the Anaconda install. Otherwise, you'll have to follow the modular approach to get it working: https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
