### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'execute'

### ISSUE THREAD

**Issue by AlexBella365** [spyder-ide/spyder#4924]
## Description

**What steps will reproduce the problem?**

Run any script in Spyder

**Please provide any additional information below**

  File "/Users/Alex/anaconda/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 872, in run_script
    self.execute_code(line, current_client, clear_variables)
  File "/Users/Alex/anaconda/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 919, in execute_code
    sw.execute(to_text_string(to_text_string(lines)))
  File "/Users/Alex/anaconda/lib/python3.5/site-packages/qtconsole/history_console_widget.py", line 47, in execute
    source, hidden, interactive)
  File "/Users/Alex/anaconda/lib/python3.5/site-packages/qtconsole/console_widget.py", line 631, in execute
    self._execute(source, hidden)
  File "/Users/Alex/anaconda/lib/python3.5/site-packages/qtconsole/frontend_widget.py", line 294, in _execute
    msg_id = self.kernel_client.execute(source, hidden)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
This means that you there's no kernel available to run code. Please post a screenshot of Spyder to try to understand why that's happening.

**Comment by AlexBella365** [comment]
Thanks.
After I reset Spyder to the default settings, it could find the kernel again. Now it works normally.

**Comment by ccordoba12** [comment]
Great to know! Thanks for letting us know about it.

**Comment by Tweetl** [comment]
This answer is very helpful!!!
