### ISSUE TITLE
.turtle is not working on spyder

### ISSUE THREAD

**Issue by DiegoHurtadoGonzalez** [spyder-ide/spyder#4929]
## Description

* *What steps will reproduce the problem?*
1.I imported turtle and defined a function with turtle.forward in it
2.I ran the function
3.Turtle appears, do its work and then stop responding and crashes

* *What is the expected output? What do you see instead?*
I excpect the turtle stays there, without making an error every time I use it

* *Please provide any additional information below*
It only throws an error with Spyder

## Version and main components

* Spyder Version:  2.3.4
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
IPython >=1.0   :  3.0.0 (OK)
zmq >=2.1.11    :  14.5.0 (OK)
pygments >=1.6  :  2.0.2 (OK)
pandas >=0.13.1 :  0.15.2 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

**Comment by ccordoba12** [comment]
Sorry but Spyder 2.3 is not supported anymore. Please update to Spyder 3.2.0 and try again.
