### ISSUE TITLE
Function list fail with \

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#4931]
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder/widgets/ipythonconsole/shell.py in spyder
2. look at the function list at the top of the editor
3. It fails after:
```
def is_running(self):
        if self.kernel_client is not None and \
             self.kernel_client.channels_running:
```
![image](https://user-images.githubusercontent.com/6740194/29159707-7a3efa7a-7da7-11e7-95bc-514fe53c64a6.png)

Idem with spyder/widgets/editor.py after 
```
def has_markers(self):
        """Return True if this editorstack has a marker margin for TODOs or
        code analysis"""
        return self.todolist_enabled or self.pyflakes_enabled\
               or self.pep8_enabled
```
![image](https://user-images.githubusercontent.com/6740194/29159711-814d0cf8-7da7-11e7-95ef-53f8f5cd8ed7.png)

It looks like the function name detection fails after a `\`

## Versions and main components

* Spyder Version: 4.0.0.dev0
* Python Version: 3.6.2
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: macOS 10.12.6

**Comment by rlaverde** [comment]
I think this is an error in how the syntax highlighter, construct the Outline Explorer data (that's used by this dropdown) It somehow depends on the indentation and the line after the '\' breaks its logic.

**Comment by ccordoba12** [comment]
@rlaverde, something we can do about it in 3.x? Or should we leave it for Spyder 4?

**Comment by rlaverde** [comment]
> something we can do about it in 3.x? Or should we leave it for Spyder 4?

I think we could leave it for spyder4. The error doesn't affect the outline explorer, and the "function class dropdown" is only present in spyder4

**Comment by impact27** [comment]
works now
