### ISSUE TITLE
"Replace selection" adds "\." anytime the string to be added contains "."

### ISSUE THREAD

**Issue by Ericvulpi** [spyder-ide/spyder#4934]
## Description of your problem

**What steps will reproduce the problem?**

1. Use the search/Replace text function (command-r)
2. Enter "." in the "Replace with" box
3. Click "Replace selection"

**What is the expected output? "."
What do you see instead?** `"\."`

**Please provide any additional information below**
The "Replace/find next" works fine

## Versions and main components

* Spyder Version: 3.2.0
Python 3.6.2 64bits, Qt 5.6.2, PyQt5 5.6 on Darwin

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.
