### ISSUE TITLE
Feature request: automatic generation of docstring template

### ISSUE THREAD

**Issue by chialikuo** [spyder-ide/spyder#4936]
Hi,

One thing that I think will be very useful for Spyder users (like myself) is automatic generation of docstring templates for functions and classes. PyCharm actually has this useful functionality. To give a concrete example, let's say I have code as shown below:

![screenshot from 2017-08-10 18-18-01](https://user-images.githubusercontent.com/9301871/29194982-3512e634-7dfa-11e7-96ff-e1bcce51ec79.png)

If now I just type three quotation marks `"""` right under the `add` function and hit Enter, a template docstring will be generated for me:

![screenshot from 2017-08-10 18-18-29](https://user-images.githubusercontent.com/9301871/29194976-2dbc94de-7dfa-11e7-9dc1-55ca2d419013.png)

In addition, if your function yields instead of returns, `Yields` instead of `Returns` will be generated. If you raise an exception in your code, a `Raises` block will be included in the docstring template. This may requirement some more code search/inference.

Pycharm now also allows you to choose docstring styles among numpydoc, Google, reStructuredText, and others. I think editors like Sublime and Atom also have plugins that achieve the exact same thing. In addition, I know there's something called `pyment` (https://github.com/dadadel/pyment) that works as a command-line program and can do this to your python code files.

Is it possible to build this same thing into the Spyder editor.

Thanks very much for your consideration.

**Comment by goanpeca** [comment]
@kuo000 sure thing, this sounds like a code snippets functionality.

**Comment by goanpeca** [comment]
@rlaverde thoughts?

**Comment by rlaverde** [comment]
This sounds like a code snippets functionality.

I'm not sure about this, snippets should only support variables, although this feature could be implemented using snippets engine:

- Some function will be fired when """" is entered.
- This function generate a temporary snippet
- Send this snippet to snippets engine

I think that using a third-party tool (pyment as @kuo000 suggests )will be the easiest way to implement this, the code introspection and managing several styles could be a lot of work if we implement that ourselves

**Comment by ccordoba12** [comment]
I agree with using `pyment` too. But for now we have a lot to do for Spyder **4**, so PRs are welcome.

**Comment by ok97465** [comment]
@ccordoba12 Do you have a plan for this issue? Can I try it if you don't have any plans?

**Comment by ccordoba12** [comment]
No, if you want to work on it, please go ahead.
