### ISSUE TITLE
Error when getting completions with the fallback plugin

### ISSUE THREAD

**Issue by yaceben** [spyder-ide/spyder#4938]
## Description

**What steps will reproduce the problem?**

1. I don't know, I was juste editing code with pattern lib imported
2. 
3. 

**What is the expected output? What do you see instead?**
did not really see what happened

**Please provide any additional information below**

  File "/usr/lib/python2.7/site-packages/spyder/utils/introspection/manager.py", line 229, in show_object_info
    self.plugin_manager.send_request(info)
  File "/usr/lib/python2.7/site-packages/spyder/utils/introspection/manager.py", line 94, in send_request
    plugins = [self.plugins[desired]]
KeyError: 'fallback'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.18.0 (OK)
numpy >=1.7       :  1.11.0 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Could you post the code that generated this message?

**Comment by yaceben** [comment]
I finally realised what had happened when I got the error message.

It happens when I add an opening parenthesis after `print` --> `print**(**` generates the error message

`import pattern
from pattern.en import wordnet as WordNet

with open('sometextexample.txt', 'r') as myfile:
    s_corpus=myfile.read()

t_corpus = pattern.en.parsetree(s_corpus, relations=True, lemmata=True)

for s in t_corpus:
    for w in s.words:
        print w.string + ' ' + w.type
    print`

Hope this helps.
Cheers

**Comment by goanpeca** [comment]
@yaceben thanks for the report, to include formatted code blocks you need to use ir like https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

I updated your issue to correctly format the code.

Cheers ;-)

**Comment by yaceben** [comment]
@goanpeca Great ! Thanks a bunch

**Comment by ccordoba12** [comment]
This no longer applies.
