### ISSUE TITLE
Unicode symbols are not highlighted in the Editor

### ISSUE THREAD

**Issue by laikh** [spyder-ide/spyder#4943]
### Description of the problem

When selecting a variable (double left click) in the editor all similar variables are highlighted. This does not work when the variable is a greek symbol.

**What steps will reproduce the problem?**

1. select variable in editor by double clicking on it

**Example**
`α = 15`
`y = 2`
`x = α+y`

selecting y in line 2 will highlight y in line 3
selecting alpha in line 1 will not highlight alpha in line 3

### Versions and main components

* Spyder Version: 3.2
* Python Version: 3.6.1 Anaconda custom (64 bit)
* Qt Version: 5.6.2
* PyQt Version: PyQt5
* Operating system: Windows 10 x64

### Dependencies

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by stonebig** [comment]
hum, it must come from variable detection which is not non-ascii minded, like:
https://github.com/spyder-ide/spyder/blob/0724278a0f2cced5d22a1c094629389609d0a9fb/spyder/widgets/sourcecode/base.py#L606

**Comment by goanpeca** [comment]
Thanks for the info @stonebig. I have been bitten by this in the past :-p

**Comment by goanpeca** [comment]
@rlaverde could you take a look at this one?
