### ISSUE TITLE
ipython console does not start

### ISSUE THREAD

**Issue by mone27** [spyder-ide/spyder#4944]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

this is automatic error detection by spyder:
**Please provide any additional information below**

  File "/home/simone/.local/lib/python3.5/site-packages/spyder/plugins/ipythonconsole.py", line 887, in set_current_client_working_directory
    shellwidget.set_cwd(directory)
  File "/home/simone/.local/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 99, in set_cwd
    self.silent_execute(code)
  File "/home/simone/.local/lib/python3.5/site-packages/spyder/widgets/ipythonconsole/shell.py", line 254, in silent_execute
    self.kernel_client.execute(to_text_string(code), silent=True)
AttributeError: 'NoneType' object has no attribute 'execute'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.5.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```
this is what I see instead of ipython console:

An error ocurred while starting the kernel
Your Python environment or installation doesn't have the ipykernel module installed on it. Without this module is not possible for Spyder to create a console for you.

You can install ipykernel by running in a terminal:

pip install ipykernel

or

conda install ipykernel

ipykernel is installed but spyder can't start the console

**Comment by mone27** [comment]
I understood the origin of the problem.
I didn't use default python interpeter ,but I configured Spyder to run script with a custom interpeter which was in a virtualenv without ipython. So Spyder worked properly while ipython console could not start.
I easily solved the issue changing Python interpeter.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it!
