### ISSUE TITLE
FileNotFound error for "sn_0_8448014/.spyproject/workspace.ini"

### ISSUE THREAD

**Issue by tupa** [spyder-ide/spyder#4945]
## Description of your problem
An error dialog complaining about a missing file is shown when opening spyder.

**What steps will reproduce the problem?**

1. Open spyder on a Mac running MacOS Sierra
2. The following error occurs:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_8448014/.spyproject/workspace.ini'

**Please provide any additional information below**
Folders like "sn_0_4039642/.spyproject/" are created in my home directory! What is the right place for these folders?
No error dialog was showing up when using spyder 3.1.4.

**Traceback**
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 111, in _save
    _write_file(fname)
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_8824938/.spyproject/workspace.ini'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/spyder/plugins/projects.py", line 147, in <lambda>
    lambda v: self.editor.setup_open_files())
  File "/usr/local/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2656, in setup_open_files
    filenames = self.projects.get_project_filenames()
  File "/usr/local/lib/python3.6/site-packages/spyder/plugins/projects.py", line 315, in get_project_filenames
    recent_files = self.current_active_project.get_recent_files()
  File "/usr/local/lib/python3.6/site-packages/spyder/widgets/projects/type/__init__.py", line 78, in get_recent_files
    default=[])
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 377, in get
    self.set(section, option, default)
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 445, in set
    self._save()
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 121, in _save
    raise(e)
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 117, in _save
    _write_file(fname)
  File "/usr/local/lib/python3.6/site-packages/spyder/config/user.py", line 107, in _write_file
    with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_8824938/.spyproject/workspace.ini'

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.2
* Qt Version: 
* PyQt Version: 
* Operating system: macOS Sierra

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by tupa** [comment]
I've noticed that this error occurs only when opening spyder by double-clicking on the application icon. If one opens spyder from a terminal window, it works fine. The mac application bundle for spyder (with a nice icon and file type association) was created by using the following [trick from Stackoverflow](https://stackoverflow.com/a/44348973/8108631).

It seems that some needed environment variables are not accessible when using the trick from stackoverflow, but which ones? If the missing environment variables were known, one could correct the trick from stackoverflow.

My goal is simply to have spyder behaving more like a standard Mac application: have an icon to identify it quickly when switching apps, double-clicking on .py files to open them in spyder, opening spyder using SpotLight, etc.

I've tried also compiling spyder with py2app but without success. Is there a DMG with a mac application bundle for spyder that one could simply download?

**Comment by ccordoba12** [comment]
> It seems that some needed environment variables are not accessible when using the trick from stackoverflow, but which ones?

Sorry, but this is an error caused by a method unsupported by us, so it's not really a bug in Spyder.

> I've tried also compiling spyder with py2app but without success. Is there a DMG with a mac application bundle for spyder that one could simply download?

We had one, but there were not enough hours in day to maintain it.

**Comment by tupa** [comment]
After hours of trial and error, I've finally found how the correct to trick on stackoverflow to get rid of this error. See the [new version of the trick](https://stackoverflow.com/a/44348973/8108631).

It's much better like this because
- Spyder has its own icon in the program switcher (it used to have the generic rocketship icon while there are often several of them when using python on a Mac)
- Spyder can be put in the Dock
- Spyder can be opened by calling it from SpotLight
- Double-clicking a .py file opens it in Spyder

These are small things, but they are very annoying when dysfunctional because we are so used to them on Macs.
