### ISSUE TITLE
Keyboard Short Cut Shift+Del set to delete

### ISSUE THREAD

**Issue by PowerPlum** [spyder-ide/spyder#4947]
## Description of your problem
Keyboard Short Cut Shift+Del set to delete. This is different to every other program used in Windows, where the Shift+Del shortcut results in Cut. Being left handed this is a incredibly useful function that does not work as expected in Spyder. When attempting to change in keyboard shorts cuts I get the forbidden key sequence error!

**What steps will reproduce the problem?**

1. Set Shift+Del to cut as default
2. Allow Shift+Del to be set to user preference
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by andfoy** [comment]
@PowerPlum Most code editors define Shift+Del by default to delete lines, and therfore, we replicate this behaviour as well. With respect to setting a shortcut that contains Shift and another Key is forbidden because Qt does not allow to define them using QShortcuts, instead they must be hardcoded, as such is the case with Shift+Del

**Comment by ccordoba12** [comment]
Sorry but we can't do anything about this. As @andfoy said, `Shitf+Del` can't be reassigned programmatically, so we preferred to go with the convention used in almost all other IDEs, i.e. define `Shift+Del` to delete lines.

Besides, `Ctrl+X` is most common (I think) to cut text.

**Comment by prof7bit** [comment]
@andfoy
> Most code editors define Shift+Del by default to delete lines,

Which ones please? I don't know of any single one that does, in fact quite the opposite is true: every single code editor out there on the planet (except vim and emacs) and also any other text editor or word processor on this planet use shift-del as cut to clipboard, I believe there are even a few standards documents by MS, Gnome, KDE, Apple that define such common shortcuts.

This is why it is so annoying that spyder is virtually the only editor under the sun that does not adhere to this simple convention and one always accidentally deletes text and needs undo when one uses his 30 year old muscle memory to rearrange lines in the text with cut & paste.

Please reopen this bug

**Comment by ccordoba12** [comment]
@prof7bit, we're not going to reopen it, sorry. If you or someone else find a way to make Shift+Del work to cut text and delete lines, we're welcome to review and merge that work (we were unable to find a way).

But we're not going to work on this for the time being.
