### ISSUE TITLE
Variable explorer error on sort by value

### ISSUE THREAD

**Issue by yaceben** [spyder-ide/spyder#4950]
## Description

**What steps will reproduce the problem?**

1. Open a populated nltk.Probability.FreqDist variable viewer
2. (Try to) sort it by value
3. Close it or scroll values

**What is the expected output? What do you see instead?**
No error messages

**Please provide any additional information below**

  File "/usr/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 250, in fetchMore
    self.rows_loaded + items_to_fetch)
  File "/usr/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 179, in set_size_and_type
    for index in range(start, stop) ]
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 250, in fetchMore
    self.rows_loaded + items_to_fetch)
  File "/usr/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 179, in set_size_and_type
    for index in range(start, stop) ]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.18.0 (OK)
numpy >=1.7       :  1.11.0 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

Sample code
```python
import nltk
from nltk.probability import FreqDist

with open('somecorpus.txt', 'r') as myfile:
    s_corpus=myfile.read()

fdist1 = FreqDist()

for sentence in nltk.tokenize.sent_tokenize(s_corpus):
    for word in nltk.tokenize.word_tokenize(sentence):
        fdist1[word] += 1

```

**Comment by ccordoba12** [comment]
Where can we find `'somecorpus.txt'`?

**Comment by yaceben** [comment]
@ccordoba12 it is just a standard textual corpora, in other words, a text document :). You can get one at http://wortschatz.uni-leipzig.de/en/download/ (unfortunately the "small" one I use right now is not free to share). Also a bunch of textual corpora are available directly by invoking the `nltk.download()` function

Cheers

**Comment by ccordoba12** [comment]
Ok, thanks for reporting. We'll take a look at this in a future release.

**Comment by yaceben** [comment]
Thanks ! if you're not able to reproduce the bug just let me know, I'll try to reliably reproduce it again.

**Comment by yaceben** [comment]
Got it, it happens if I first try to sort the view by value and then scroll through the list (~20,000 items).

**Comment by ccordoba12** [comment]
Ok, this could happen because we're not taking sorting into account when asking for more values to display in the viewer.

**Comment by yaceben** [comment]
I might be able to help eventually, although right now I'm not really any good with Python since I wanted to try switching from C++/Matlab to Python for data processing

**Comment by Prikers** [comment]
I think this issue is related to #5232

**Comment by ccordoba12** [comment]
Thanks @Prikers!
