### ISSUE TITLE
Consistent layout in different panes

### ISSUE THREAD

**Issue by timhoffm** [spyder-ide/spyder#4953]
## Description of your problem

The editor and other panes should use the same vertical position for the main widget. This would result in a more consistent look.

**What is the expected output? What do you see instead?**

**Current behavior**: Panes with toolbars have an additional offset.

Example: [ Editor | Explorer | Help ]
![2017_08_13_18_24_49_spyder_3 2 1 dev0_python_3 6_](https://user-images.githubusercontent.com/2836374/29251931-77200f14-805e-11e7-9355-0cf3f531c08e.png)

**Expected**: For Panes with a 'single' line of controls (editor tabs / toolbar), the main widget should start at the same vertical offset for all panes.

Example: [ Editor | Explorer | Help ]
![2017_08_13_18_21_49_spyder_3 2 1 dev0_python_3 6_](https://user-images.githubusercontent.com/2836374/29251459-5e8dde62-8055-11e7-82e1-07d434d41857.png)

**Please provide any additional information below**
The differences arise because the mechanisms are different:
1. The editor uses a tab widget.
2. (Some) other panes use a QVBoxLayout containing one widget for the controls and a separate main widget.

The height of the tab bar (1.) is not equal to the height of the control widgets plus layout spacing (2.).
One solution is to reduce the layout spacing (`layout.setSpacing(2)` in the above example for expected).

Caveats:
- This works on Windows 10. Other window systems may have other dimensions.
- It's a bit difficult to decide on the really optimal spacing: With spacing 2 the editor (blue outline) and the main widgets of the other panes are exactly aligned. However the tab bar itself has a grey bottom line. thus the editor appears to be a pixel above. But given that spacing 2 results in equal top and bottom margin for the combo box and line edit, I still consider it the best value.

![2017_08_13_19_26_01_2017_08_13_18_21_49_spyder_3 2 1 dev0_python_3 6_ png_paint net_v4 0 17](https://user-images.githubusercontent.com/2836374/29251855-53f12ec0-805d-11e7-9be1-39c69f0cbd57.png)

If desired, i can provide a pull request.

## Versions and main components

* Spyder Version: 3.2.1.dev0 af176c3
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6
* Operating system: Windows 10

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
> If desired, i can provide a pull request.

Yes, please create a PR to test your solution in other OSes. And thanks a lot for helping us with this!
