### ISSUE TITLE
Cannot display image on Ipython console

### ISSUE THREAD

**Issue by ferriswym** [spyder-ide/spyder#4956]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "D:\ProgramData\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 134, in _handle_execute_result
    png = decodestring(data['image/png'].encode('ascii'))
  File "D:\ProgramData\Anaconda3\lib\base64.py", line 561, in decodestring
    return decodebytes(s)
  File "D:\ProgramData\Anaconda3\lib\base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
I

**Comment by ccordoba12** [comment]
Please post the code which generated this error.

**Comment by ferriswym** [comment]
Image('G:\Crack Detection\project\Layer\database\blocks\positive\pos1.png')

**Comment by ccordoba12** [comment]
This is a bug in `qtconsole` (the package which powers our IPython console):

https://github.com/jupyter/qtconsole

Please move it there.
