### ISSUE TITLE
Problem importing LatLon and Basemap packages

### ISSUE THREAD

**Issue by LorenzoCorgnati** [spyder-ide/spyder#4959]
## Description of your problem

**What steps will reproduce the problem?**

1. I am working on a Mac Book Pro with Mac OS 10.12.6. I installed Python 2.7 and the mpl_toolkits.basemap and LatLon packages. 
2. On the terminal Python prompt I am able to import these packages.
3. On Spyder I am not able to import the packages. the error "ImportError: No module named 'mpl_toolkits'" is thrown.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
It depends on how you install them. Sorry but this is not a Spyder bug, just an installation problem.
