### ISSUE TITLE
Background cmd.exe process left on Windows when launched from command line

### ISSUE THREAD

**Issue by kgbaird** [spyder-ide/spyder#4960]
## Description of your problem

**What steps will reproduce the problem?**

1. Open a Windows command prompt
2. Get a virtual environment available that has spyder and its dependencies (I use conda, so `activate myenv`)
3. Launch spyder by running the `spyder` command
4. Close spyder
5. Open up task manager or process explorer and view current processes. Notice there is a cmd.exe that was left by spyder

**What is the expected output? What do you see instead?**
When closing spyder, it's parent cmd.exe should not be left

**Please provide any additional information below**
This "hanging" process is particularly troublesome because it places a lock on the working directory when the `spyder` command was launched (meaning it cannot be deleted, renamed, etc.) without manually killing the process

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.5.2
* Qt Version: 5.6.0
* PyQt Version: 5.6.0
* Operating system: Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.8 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
What do you mean by a `cmd.exe`? Is there a system terminal left open?

**Comment by kgbaird** [comment]
Sorry for the confusion. When I launch spyder from the command line, it is initiated as a subprocess of the terminal window I had open. Here is what the process tree looks like after launching spyder using Process Explorer:

![with-spyder-open](https://user-images.githubusercontent.com/7782732/29468012-8fb6bc7a-8410-11e7-9584-6af0c509a84e.PNG)

When spyder is launched, the terminal window spyder was instantiated from is closed. I assume that is because spyder is opened using `pythonw.exe`, but I could be wrong. After I close spyder the process tree looks like this:

![after-closing-spyder](https://user-images.githubusercontent.com/7782732/29468145-040a49b6-8411-11e7-9bed-f48cc56b4f9d.PNG)

The parent process is still open. There is no terminal window open as evidence. This process holds file locks to the working directory when spyder was launched. Only after manually killing this process am I able to delete/rename files in that directory.

**Comment by ccordoba12** [comment]
I see, thanks for the detailed explanation. Now I understand what's happening.

We'll try to fix this in a future release.

**Comment by kgbaird** [comment]
After upgrading to version 3.2.6, it appears this is no longer a problem. My Windows command prompt no longer closes, and when I close spyder I am returned to the command prompt.

**Comment by ccordoba12** [comment]
That's right, we changed the default behavior so that now Spyder doesn't hide automatically the terminal from which it's started.

**Comment by kgbaird** [comment]
Thanks you for the work! I appreciate it
