### ISSUE TITLE
Issue with splitting panes

### ISSUE THREAD

**Issue by gabrielclow** [spyder-ide/spyder#4964]
## Description of your problem

**What steps will reproduce the problem?**

1. Split editor panes twice (vertically or horizontally)
2. Click on the cog for one of the splitted panes
3. Error usually happens here, but sometimes the click works
4. If exception didn't occur, split it one more time and try to click the cog again
5. Error

**What is the expected output? What do you see instead?**
Expected output is normal click on the cog menu, I see an exception instead

**Please provide any additional information below**
Spyder only goes back to normal if I close and reopen. Here's the full exception and some screenshots

  File "C:\Users\gabriel\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1236, in __setup_menu
    add_actions(self.menu, list(actions)+self.__get_split_actions())
  File "C:\Users\gabriel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 309, in add_actions
    action = action.no_icon_action
  File "C:\Users\gabriel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 443, in __getattribute__
    attr = super(SpyderAction, self).__getattribute__(name)
  File "C:\Users\gabriel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 462, in no_icon_action
    return self._action_no_icon
  File "C:\Users\gabriel\Anaconda3\lib\site-packages\spyder\utils\qthelpers.py", line 445, in __getattribute__
    if hasattr(attr, '__call__') and name not in ['triggered', 'toggled',
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted

![capture1](https://user-images.githubusercontent.com/9113853/29320442-9632de7c-81ad-11e7-8e96-ba18fcdfbe93.PNG)
![capture2](https://user-images.githubusercontent.com/9113853/29320447-99c3fd3c-81ad-11e7-83f9-79babf4d2f08.png)

## Versions and main components

* Spyder Version: 3.2.0
* Python Version: 3.6.2
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: latest Windows 10 64bits

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
This error was fixed in Spyder 3.2.1. If you're using Anaconda, please wait a couple of days for it.
