### ISSUE TITLE
Spyder Cannot open Preference tab

### ISSUE THREAD

**Issue by simonzcaiman** [spyder-ide/spyder#4966]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/szhang/miniconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2579, in edit_preferences
    widget.initialize()
  File "/home/szhang/miniconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 75, in initialize
    self.load_from_conf()
  File "/home/szhang/miniconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 379, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by simonzcaiman** [comment]
On my terminal, it says the following: 
Xlib:  extension "RANDR" missing on display ":0.0".
Xlib:  extension "RANDR" missing on display ":0.0".
Xlib:  extension "RANDR" missing on display ":0.0".
[12533:12567:0815/122326.314208:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.

**Comment by simonzcaiman** [comment]
I was able to run it with no prob. I don't know what happened. and this stopped working

**Comment by ccordoba12** [comment]
Please run in a terminal

    spyder --reset

and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
