### ISSUE TITLE
Console slow to close when debugging

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#4970]
## Description of your problem

**What steps will reproduce the problem?**

1.  Start the debugger
2. Try to close the console
3. watch as spyder freezes for 5s

* Spyder Version: 4.0.0.dev0
* Python Version: 3.6.2
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system:macOS 10.12.6

**Comment by ccordoba12** [comment]
Do you have something in the variable explorer?

**Comment by impact27** [comment]
I have the exact same problem with and without something in the variable explorer
