### ISSUE TITLE
Deleting line in editor deletes next line

### ISSUE THREAD

**Issue by minzastro** [spyder-ide/spyder#4973]
1) The caret is at the beginning of the line.
2) I hold "shift" and then move cursor down, to select the whole line.
3) Line is shown as selected
4) I press "Del", while holding shift - now the selected line is gone, and so is the next one, where the cursor was...
This seems to be Qt issue - extra line is deleted if I still hold shift key - shift+del cuts the line. Is it possible to remove qt shift+del shortcut somehow?

## Versions and main components

* Spyder Version:3.2.0
* Python Version:3.6
* Qt Version: 5.9.1
* PyQt Version: 5.8.2
* Operating system:OpenSuse Tumbleweed

**Comment by minzastro** [comment]
This seems to be Qt issue - extra line is deleted if I still hold shift key - shift+del cuts the line. Is it possible to remove qt shift+del shortcut somehow?

**Comment by ccordoba12** [comment]
> Is it possible to remove qt shift+del shortcut somehow?

Sorry, we added that shortcut it per request of users of other IDEs who are accustomed to `Shift+Del` to delete lines.
