### ISSUE TITLE
when i create a new file

### ISSUE THREAD

**Issue by ZaidSamee** [spyder-ide/spyder#4977]
## Description

**What steps will reproduce the problem?**

1. when i create new file then this problem occure
2. 
3. 

**What is the expected output? What do you see instead?**

a new file
**Please provide any additional information below**

  File "D:\C_Drive_Software\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1709, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "D:\C_Drive_Software\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zaid\\.spyder-py3\\template.py'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
It seems you're using and old settings file. Please run

    spyder --reset

in a terminal. That should fix your error.
