### ISSUE TITLE
ModuleNotFoundError: No module named 'pyspark'

### ISSUE THREAD

**Issue by dhirendradas** [spyder-ide/spyder#4979]
## Description

I have done the basic setup and set the path properly. I am getting no module named pyspark error. Please help.

**Please provide any additional information below**

C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\bin>dir
 Volume in drive C is OS
 Volume Serial Number is FAB8-D15B

 Directory of C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\bin

08/16/2017  06:29 PM    <DIR>          .
08/16/2017  06:29 PM    <DIR>          ..
12/15/2016  10:18 PM             1,089 beeline
12/15/2016  10:18 PM               899 beeline.cmd
08/16/2017  06:44 PM            20,242 derby.log
12/15/2016  10:18 PM             1,933 find-spark-home
12/15/2016  10:18 PM             1,909 load-spark-env.cmd
12/15/2016  10:18 PM             2,133 load-spark-env.sh
08/16/2017  06:44 PM    <DIR>          metastore_db
12/15/2016  10:18 PM             2,989 **pyspark**
12/15/2016  10:18 PM             1,002 pyspark.cmd
12/15/2016  10:18 PM             1,493 pyspark2.cmd
12/15/2016  10:18 PM             1,030 run-example
12/15/2016  10:18 PM               988 run-example.cmd
12/15/2016  10:18 PM             3,116 spark-class
12/15/2016  10:18 PM             1,012 spark-class.cmd
12/15/2016  10:18 PM             2,236 spark-class2.cmd
12/15/2016  10:18 PM             3,017 spark-shell
12/15/2016  10:18 PM             1,010 spark-shell.cmd
12/15/2016  10:18 PM             1,530 spark-shell2.cmd
12/15/2016  10:18 PM             1,065 spark-sql
12/15/2016  10:18 PM             1,040 spark-submit
12/15/2016  10:18 PM             1,012 spark-submit.cmd
12/15/2016  10:18 PM             1,128 spark-submit2.cmd
12/15/2016  10:18 PM             1,039 sparkR
12/15/2016  10:18 PM             1,000 sparkR.cmd
12/15/2016  10:18 PM             1,014 sparkR2.cmd
              24 File(s)         54,926 bytes
               3 Dir(s)  301,267,214,336 bytes free

C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\bin>echo %PATH%
C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\python\lib\py4j-0.10.4-src.zip;C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\python\bin;C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\bin;c:\hadoop\bin;C:\Program Files\Dell\DW WLAN Card;;C:\ProgramData\Oracle\Java\javapath;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;c:\Program Files\WIDCOMM\Bluetooth Software\;c:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Skype\Phone\;C:\Users\Basundhara\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Basundhara\AppData\Local\Programs\Python\Python36-32\;C:\Users\Basundhara\AppData\Local\Microsoft\WindowsApps;C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\bin;C:\Program Files\Java\jdk1.8.0_121\bin;

C:\Users\Basundhara\spark-2.1.0-bin-hadoop2.7\bin>

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry, we don't have experience with Spark.
