### ISSUE TITLE
Macports Spyder is out of date

### ISSUE THREAD

**Issue by breedlun** [spyder-ide/spyder#4980]
As shown [here](https://www.macports.org/ports.php?by=name&substr=spyder), the most recent released version of Spyder on macports is 2.3.8, yet Spyder is on 3.2.1 on GitHub.  Was there a decision to stop supporting macports installations?  If so, perhaps the old versions of Spyder should be removed from macports.

**Comment by ccordoba12** [comment]
Sorry but we don't have any influence on Macports. We had a very active maintainer some years ago, but it seems he retired from the project.

**Comment by ccordoba12** [comment]
*Macports* maintainer, I meant.
