### ISSUE TITLE
Unable to start Array builder using keyboard shortcut

### ISSUE THREAD

**Issue by gautham949** [spyder-ide/spyder#4981]
When I use Ctrl+M to start array builder in Spyder, I get the following error message. What is the issue?
  File "C:\Users\Gautham\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 244, in <lambda>
    array_table = config_shortcut(lambda: self.enter_array_table(),
AttributeError: 'ShellWidget' object has no attribute 'enter_array_table'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by goanpeca** [comment]
@ccordoba12 is this related to the ipyconsole restructure?

**Comment by gabrielclow** [comment]
I get the same error if I try to open the array builder on the console but not on the editor

Spyder Version: 3.2.1
Python Version: 3.6.2
Qt 5.6.2, PyQt 5.6.0
Windows 10 64bit
Dependencies:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.
