### ISSUE TITLE
How to open Spyder (env-name) directly

### ISSUE THREAD

**Issue by rounakskm** [spyder-ide/spyder#4982]
Hello,
I created a new python 3.5 environment called neuralnets, and installed sypder in that environment as well. These are the steps I follow to get there.

1.  Start spyder by searching for it in the start menu
2. activate neuralnets command starts the environment prompt prefixed with (neuralnets)
3. spyder --new-instance command starts the Sypder IDE(3.5) 

My question : Is there any way to get there directly?

While searching for Spyder I get two results : Spyder and Spyder(neuralnets)

Clicking on Spyder starts the Sypder IDE, but if I click on  Spyder(neuralnets) nothing happens.
 
## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1 / 3.5.2 (for neuralnets env)
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
I think you can handle this better by using Anaconda Navigator.

@goanpeca?

**Comment by goanpeca** [comment]
@rounakskm are you using anaconda and conda I assume? You can easily launch spyder from anaconda navigator, you might want to give it a try. Otherwise you need to activate the specific environment and launch it from the terminal/prompt

**Comment by rounakskm** [comment]
Thanks for the help. I'll give it a try

Regards,
Rounak

**Comment by ccordoba12** [comment]
Closing because this is not a Spyder bug.

Feel free to keep chatting with @goanpeca here though.
