### ISSUE TITLE
On start up i am getting this problem

### ISSUE THREAD

**Issue by lihka1** [spyder-ide/spyder#4983]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/akhil/anaconda2/lib/python2.7/site-packages/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/home/akhil/anaconda2/lib/python2.7/site-packages/spyder/otherplugins.py", line 101, in _import_module_from_path
    info = imp.find_module(module_name, [plugin_path])
ImportError: No module named spyder_notebook-0.1.1-py2.7.egg-info

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.0.1 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
How did you install Spyder notebook?

**Comment by lihka1** [comment]
conda install spyder-notebook -c spyder-ide

**Comment by ccordoba12** [comment]
Ok, this is an error with Spyder notebook, so I'm moving this issue to the corresponding repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #112](https://github.com/spyder-ide/spyder-notebook/issues/112) via [**ZenHub**](https://www.zenhub.com/)
