### ISSUE TITLE
An error ocurred while starting the kernel - can someone help with the below error?

### ISSUE THREAD

**Issue by pthakur4** [spyder-ide/spyder#4985]
## Description of your problem
An error ocurred while starting the kernel
‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑
TypeError Traceback (most recent call last)
C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py in ()
162 ipk_temp = IPKernelApp.instance()
163 ipk_temp.config = kernel_config()
‑‑> 164 ipk_temp.initialize()
global ipk_temp.initialize = >
165 
166 # Grabbing the kernel's shell to share its namespace with our

in initialize(self=, argv=None)

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\config\application.pyc in catch_config_error(method=, app=, *args=(None,), **kwargs={})
73 """
74 try:
‑‑‑> 75 return method(app, *args, **kwargs)
method = 
app = 
args = (None,)
kwargs = {}
76 except (TraitError, ArgumentError) as e:
77 app.print_help()

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\kernel\zmq\kernelapp.pyc in initialize(self=, argv=None)
354 self.init_io()
355 self.init_signal()
‑‑> 356 self.init_kernel()
self.init_kernel = >
357 # shell init steps
358 self.init_path()

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\kernel\zmq\kernelapp.pyc in init_kernel(self=)
308 log=self.log,
309 profile_dir=self.profile_dir,
‑‑> 310 user_ns=self.user_ns,
global user_ns = undefined
self.user_ns = None
311 )
312 kernel.record_ports(self.ports)

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\config\configurable.pyc in instance(cls=, *args=(), **kwargs={'iopub_socket': , 'log': , 'parent': , 'profile_dir': , 'session': , 'shell_streams': [, ], 'stdin_socket': , 'user_ns': None})
335 # Create and save the instance
336 if cls._instance is None:
‑‑> 337 inst = cls(*args, **kwargs)
inst = undefined
cls = 
args = ()
kwargs = {'log': , 'parent': , 'shell_streams': [, ], 'user_ns': None, 'iopub_socket': , 'profile_dir': , 'session': , 'stdin_socket': }
338 # Now make sure that the instance will also be returned by
339 # parent classes' _instance attribute.

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\kernel\zmq\ipkernel.pyc in __init__(self=, **kwargs={'iopub_socket': , 'log': , 'parent': , 'profile_dir': , 'session': , 'shell_streams': [, ], 'stdin_socket': , 'user_ns': None})
50 user_module = self.user_module,
51 user_ns = self.user_ns,
‑‑‑> 52 kernel = self,
global kernel = undefined
self = 
53 )
54 self.shell.displayhook.session = self.session

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\config\configurable.pyc in instance(cls=, *args=(), **kwargs={'kernel': , 'parent': , 'profile_dir': , 'user_module': None, 'user_ns': None})
335 # Create and save the instance
336 if cls._instance is None:
‑‑> 337 inst = cls(*args, **kwargs)
inst = undefined
cls = 
args = ()
kwargs = {'kernel': , 'user_ns': None, 'profile_dir': , 'parent': , 'user_module': None}
338 # Now make sure that the instance will also be returned by
339 # parent classes' _instance attribute.

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\core\interactiveshell.pyc in __init__(self=, ipython_dir=None, profile_dir=, user_module=None, user_ns=None, custom_exceptions=((), None), **kwargs={'kernel': , 'parent': })
531 self.init_data_pub()
532 self.init_displayhook()
‑‑> 533 self.init_magics()
self.init_magics = >
534 self.init_alias()
535 self.init_logstart()

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\kernel\zmq\zmqshell.pyc in init_magics(self=)
479 
480 def init_magics(self):
‑‑> 481 super(ZMQInteractiveShell, self).init_magics()
global super = undefined
global ZMQInteractiveShell = 
self.init_magics = >
482 self.register_magics(KernelMagics)
483 self.magics_manager.register_alias('ed', 'edit')

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\core\interactiveshell.pyc in init_magics(self=)
2184 # should be split into a prompt manager and displayhook. We probably
2185 # even need a centralize colors management object.
‑> 2186 self.magic('colors %s' % self.colors)
self.magic = >
self.colors = 'Linux'
2187 
2188 # Defined here so that it's included in the documentation

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\core\interactiveshell.pyc in magic(self=, arg_s='colors Linux')
2302 magic_name, _, magic_arg_s = arg_s.partition(' ')
2303 magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
‑> 2304 return self.run_line_magic(magic_name, magic_arg_s)
self.run_line_magic = >
magic_name = 'colors'
magic_arg_s = 'Linux'
2305 
2306 #‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\core\interactiveshell.pyc in run_line_magic(self=, magic_name='colors', line='Linux')
2223 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
2224 with self.builtin_trap:
‑> 2225 result = fn(*args,**kwargs)
result = undefined
fn = >
args = [u'Linux']
kwargs = {}
2226 return result
2227 

in colors(self=, parameter_s=u'Linux')

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\core\magic.pyc in (f=, *a=(, u'Linux'), **k={})
191 # but it's overkill for just that one bit of state.
192 def magic_deco(arg):
‑‑> 193 call = lambda f, *a, **k: f(*a, **k)
global call = undefined
f = 
a = (, u'Linux')
k = {}
194 
195 if callable(arg):

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\core\magics\basic.pyc in colors(self=, parameter_s=u'Linux')
338 shell = self.shell
339 
‑‑> 340 import IPython.utils.rlineimpl as readline
global IPython.utils.rlineimpl = undefined
readline = undefined
341 
342 if not shell.colors_force and \

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\IPython\utils\rlineimpl.py in ()
19 try:
20 # import readline as _rl
‑‑‑> 21 _rl = __import__(_rlmod_name)
global _rl = undefined
global __import__ = undefined
global _rlmod_name = None
22 # from readline import *
23 globals().update({k:v for k,v in _rl.__dict__.items() if not k.startswith('_')})

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\readline.py in ()
32 
33 # create a Readline object to contain the state
‑‑‑> 34 rl = Readline()
global rl = undefined
global Readline = None
35 
36 if rl.disable_readline:

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\pyreadline\rlmain.pyc in __init__(self=)
421 def __init__(self):
422 BaseReadline.__init__(self)
‑‑> 423 self.console = console.Console()
self.console = 
global console.Console = 
424 self.selection_color = self.console.saveattr<<4
425 self.command_color = None

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\site‑packages\pyreadline\console\console.pyc in __init__(self=, newbuffer=0)
219 
220 self.pythondll = \
‑‑> 221 CDLL('python%s%s' % (sys.version[0], sys.version[2]))
global CDLL = 
global sys.version = '2.7.13 |Anaconda 2.2.0 (64‑bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)]'
222 self.pythondll.PyMem_Malloc.restype = c_size_t
223 self.pythondll.PyMem_Malloc.argtypes = [c_size_t]

C:\Users\44062934\AppData\Local\Continuum\Anaconda\lib\ctypes\__init__.pyc in __init__(self= instance, name=u'python27', mode=0, handle=None, use_errno=False, use_last_error=False)
360 
361 if handle is None:
‑‑> 362 self._handle = _dlopen(self._name, mode)
self._handle = undefined
global _dlopen = 
self._name = u'python27'
mode = 0
363 else:
364 self._handle = handle

TypeError: LoadLibrary() argument 1 must be string, not unicode

**Comment by ccordoba12** [comment]
I think

    conda remove pyreadline

should fix your error.
