### ISSUE TITLE
Improve how spyder manages configuration (CONF)

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#4986]
Some widgets and plugins import `CONF` directly, It isn't the best design pattern, because It doesn't allow to change the configuration easily (for example for testing)

The solution:

Neither main window, plugins or widgets should access to the CONF directly, the will receive conf as a part of their creation:

```
class PluginWidget(BasePluginWidget):
    def __init__(self, main=None, configuration=None):
```

I also found a fixture for configuration, that isn't used in this [file](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/fixtures.py), using it will allow to make spyder tests independent of local configuration, and also testing different configuration values easily.

**Comment by goanpeca** [comment]
@rlaverde we needd class PluginWidget(BasePluginWidget):
`    def __init__(self, main=None, configuration=CONF):` otherwise we break plugins for standalone run / test

**Comment by rlaverde** [comment]
After looking where CONF is used, I have change my mind, because:

- We could achieve the same result without changing too much.
- Passing preferences to classes will avoid to use preferences outside of widgets or plugins (eg: highDPI configurations are used before the creation of the main window, also some utils access to configurations)
- It will add some unnecessary complexity

I think that maybe some refactoring (and implement something similar to what Flask or Django does):

- Configurations are exposed through and import or a global (as spyder CONF works at the moment)
- This also expose a function for loading the configuration

code for loading configuration could  look something like this:

```
from spyder import config
config.load(name, defaults, load, version...)
```

And getting a value form configurations:
```
from spyder import config
config.get('main', 'high_dpi_scaling')
```

@goanpeca What do you think?

**Comment by jitseniesen** [comment]
How would testing work?

**Comment by rlaverde** [comment]
A fixture will execute `config.load(name, defaults, load, version...)` with the custom preferences

**Comment by goanpeca** [comment]
I think this will be the result of the new API, so I will close this for now.
