### ISSUE TITLE
Automatic crash

### ISSUE THREAD

**Issue by tanayz** [spyder-ide/spyder#4995]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda2\lib\site-packages\spyder\widgets\editor.py", line 1694, in focus_changed
    self.refresh()
  File "D:\Anaconda2\lib\site-packages\spyder\widgets\editor.py", line 1807, in refresh
    self.__check_file_status(index)
  File "D:\Anaconda2\lib\site-packages\spyder\widgets\editor.py", line 1783, in __check_file_status
    self.reload(index)
  File "D:\Anaconda2\lib\site-packages\spyder\widgets\editor.py", line 1856, in reload
    txt, finfo.encoding = encoding.read(finfo.filename)
  File "D:\Anaconda2\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
IOError: [Errno 22] Invalid argument

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.4 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.1 (OK)

```

**Comment by rlaverde** [comment]
Maybe there is not file or the path is somehow corrupted
Try executing:
`$ spyder --reset`

Anyway why should catch this possible error better, and avoid the crash.

**Comment by ccordoba12** [comment]
@tanayz, what were you doing when this error happened?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
