### ISSUE TITLE
Add spell checker on comments

### ISSUE THREAD

**Issue by xgnata** [spyder-ide/spyder#4997]
Hi,

Maybe I'm missing something but it looks like spyder3.1.4 installed with winpython3.6.1 does not offer spelcheck of comments (starting with #). It looks like spellcheck of doctrings is also not supported.
Acording the the internal dependencies checker, I have installed all the python modules needed for a fully featured spyder. Nothing about spellchecks.

Xavier

**Comment by ccordoba12** [comment]
We have never supported a spell checker in comments nor in docstrings. Besides, we don't have plans to do it in the near future, sorry.

**Comment by xgnata** [comment]
Well, this is bad news as the quality of the comments contribute to the
quality of the code.
This is especially bad for the docstrings as they are often visible in the
end user doc.
As an example, numpy would not look very pro if their documentation was
full of typos.

**Comment by ccordoba12** [comment]
We'd grateful to receive a contribution for this, but (as I said) we don't have plans for something like this right now.
