### ISSUE TITLE
Can't run static code analysis dur to import conflict

### ISSUE THREAD

**Issue by PertuyF** [spyder-ide/spyder#4998]
## Description of your problem

**What steps will reproduce the problem?**

1. Create a package with a module named `io`
2. Import something (e.g. `StringIO`) from standard library's `io` in cutom module `io`
3. Try to run static code analysis on custom module `io`
4. Or try to run static code analysis on any other module located in custom `io`'s directory

**What is the expected output? What do you see instead?**
Instead of running the static code analysis, I get an error related to an import conflict between standard lib `io` and my custom `io` module.

> Fatal Python error: Py_Initialize: can't initialize sys standard streams
> Traceback (most recent call last):
>   File "/my_package/io.py", line 35, in <module>
> ImportError: cannot import name 'StringIO'

**Please provide any additional information below**
This error raises even on a module located in `/my_package/` that does not import the conflicting module or even refer to it.

The same thing happens when calling Python or IPython from this directory, but everything is fine using `my_package` as a namespace.

It suggests that static code analysis starts a Python kernel right inside the parent directory of the inspected module.

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6.0 64bits
* Qt Version: 5.6.2
* PyQt Version: 5 5.6
* Operating system: Linux

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
This clearly shows you that shouldn't use standard library names in your packages.

I'm closing this because we're not going to invest time in fixing something that is a bad practice.

**Comment by PertuyF** [comment]
It is acknowledged in [PEP328](https://www.python.org/dev/peps/pep-0328/#rationale-for-absolute-imports) that shadowing standard library modules can happened, and will likely happened as the standard library expends.

Beside, it is why namespaces exist, so that you can use meaningful module names and prevent collision. Doesn't starting Python from within a package goes against the design of that package as a namespace?

So even if using this name probably wasn't the best idea I had (I will look to renaming), I think this issue is still valid.

**Comment by ccordoba12** [comment]
You're more than welcome to send us a pull request to fix this. But we have to prioritize things and right now don't have time to focus on something like this, sorry.

**Comment by PertuyF** [comment]
Just for info, I have been investigating a bit, and the issue does not exist at all with my Windows Anaconda install.

Calling Python or IPython from a directory were a module shadows a name from the standard lib works, although you cannot import the module itself but only the one from stdlib, as expected.

As this is likely the origin of the bug under Linux, does anyone have an idea on how to explain this OS-specific behaviour?
