### ISSUE TITLE
Error when trying to edit elements of a float numpy array in variable explorer

### ISSUE THREAD

**Issue by alexkopytin** [spyder-ide/spyder#5003]
## Error when trying to edit elements of a float numpy array in variable explorer

**What steps will reproduce the problem?**

1. Doubleclick a float numpy array in variable explorer 
2. Try to edit the fractional part of any element

**What is the expected output? What do you see instead?**
The value of the chosen element is expected to be changed, but it is not.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. What command are you using to create the Numpy array you can't modify?

**Comment by alexkopytin** [comment]
I'm using numpy.array() for example.
