### ISSUE TITLE
How do I enable graphs to be interactive?

### ISSUE THREAD

**Issue by sam22emaye** [spyder-ide/spyder#5004]
The graph that is produced is both low quality and not interactive

**What steps will reproduce the problem?**

import matplotlib.pyplot as plt
import pandas as pd
import pandas_datareader as web
import datetime as dt
from matplotlib import style
style.use('ggplot')
start=dt.datetime(2000,1,1)
end=dt.datetime(2017,1,1)
df=web.DataReader('BRK-A','yahoo',start,end)
print()
df['Close'and'Open'].plot()
**What is the expected output? What do you see instead?**

The graph produced is not interactive.  I'm trying to zoom in and out and interact with the data

## Versions and main components

* Spyder Version:3.2.1
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
You need to evaluate `%gui qt5` in the console or go to

    Tools > Preferences > IPython console > Graphics > Graphics backend

and select `Automatic` there.
