### ISSUE TITLE
Crash/Error on clicking Maximize current pane button

### ISSUE THREAD

**Issue by Ramshandilya** [spyder-ide/spyder#5006]
## Description
> Spyder has encountered a problem. Sorry for the inconvenience

**What steps will reproduce the problem?**

1. Click Maximize current pane button in the Toolbar
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/ramshandilya/anaconda/lib/python3.5/site-packages/spyder/app/mainwindow.py", line 2251, in maximize_dockwidget
    self.last_plugin.dockwidget.setWidget(self.last_plugin)
AttributeError: 'NoneType' object has no attribute 'dockwidget'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
What you do you have focus on when this happen?

**Comment by ccordoba12** [comment]
This is an error in spyder-reports. It'll be fixed in its next version.
