### ISSUE TITLE
Spyder3 freezes when Variable Explorer is used

### ISSUE THREAD

**Issue by ThosV** [spyder-ide/spyder#5009]
Spyder3 will freeze any time I try and do anything in the variable explorer window. Just clicking on any variable is sufficient to freeze the whole system. I can't open other windows, click on any icons etc. So far the only thing I've been able to do to fix it is reboot the machine. 

**What steps will reproduce the problem?**

1. Create a variable that appears in the Variable Explorer window
2. Click on that variable to visualize it. 
3. System should freeze solid. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Using Manjaro Linux 
Using Spyder as part of Anaconda
Spyder didn't work out-of-the-box, but I manually installed libselinux from the AUR which seemed to do the trick. 

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Please update to Spyder 3.2.1 and try again.

**Comment by ThosV** [comment]
Yep, that did the trick. Thanks.

**Comment by ccordoba12** [comment]
Great!
