### ISSUE TITLE
module 'os' has no attribute ' walk

### ISSUE THREAD

**Issue by aiMojica10** [spyder-ide/spyder#5010]
## Description of your problem

**What steps will reproduce the problem?**

1.   I tried to execute this code in Ipython console and it fails  with this error

```python
import os
import os.path as osp
for path, dirs, files in os.walk(os.getcwd()):
    for file in files:
        filename, ext = osp.splitext(file)
        if ext == '.jpg':
            print(osp.join(path,file))
```
            
Traceback (most recent call last):

  File "<ipython-input-45-e8161e31e7e5>", line 3, in <module>
    filename, ext = osp.splitext(file)

AttributeError: module 'os' has no attribute 'splitext'

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: windows

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  None (NOK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
This error is not related to Spyder, sorry. It's just a programming bug.

**Comment by aiMojica10** [comment]
If that’s true, why  in a normal console the  SAME code Works?

Enviado desde Correo<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Carlos Cordoba<mailto:notifications@github.com>
Enviado: sábado, 19 de agosto de 2017 9:31 p. m.
Para: spyder-ide/spyder<mailto:spyder@noreply.github.com>
CC: Anamaria Irmgard Mojica Hanke<mailto:ai.mojica10@uniandes.edu.co>; Author<mailto:author@noreply.github.com>
Asunto: Re: [spyder-ide/spyder] module 'os' has no attribute ' walk (#5010)


This error is not related to Spyder, sorry. It's just a programming bug.

**Comment by dalthviz** [comment]
Hi @aiMojica10 could you retry your code?, for me it is working as expected:

![imagen](https://user-images.githubusercontent.com/16781833/29491695-9978f9d0-8528-11e7-9884-7925e25d8a9b.png)

Maybe you run `os.splitext` instead of `osp.splitext` initially?

**Comment by ccordoba12** [comment]
> Maybe you run os.splitext instead of osp.splitext initially?

That's my guess.
