### ISSUE TITLE
Spyder crashed in middle of a training model process

### ISSUE THREAD

**Issue by EulerFaria** [spyder-ide/spyder#5016]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 291, in chdir
    self.set_as_current_console_wd()
  File "/anaconda/lib/python3.6/site-packages/spyder/plugins/workingdirectory.py", line 296, in set_as_current_console_wd
    self.set_current_console_wd.emit(getcwd())
OSError: [Errno 23] Too many open files in system
WARNING:traitlets:kernel died: 6.000680923461914WARNING:traitlets:kernel restarted

WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restartedWARNING:traitlets:kernel died: 6.007031202316284

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry but this is not a problem in Spyder. It seems your model open too many files in your system, but that's unrelated to Spyder.
