### ISSUE TITLE
When running code in the editor i am getting the following error in the concole

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder#5025]
When running code in the editor i am getting the following error.
NameError: name 'runfile' is not defined

after running 
set SPYDER_DEBUG=3
spyder --show-console

 sys.exit(spyder.app.start.main())
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\app\start.py", line 141, in main
    mainwindow.main()
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3023, in main
    or options.optimize)
  File "C:\Program Files\Anaconda3\lib\site-packages\spyder\utils\windows.py", line 33, in set_attached_console_visible
    return bool(ShowWindow(console_window_handle, flag[state]))
KeyError: 3

* Spyder Version:3.21
* Python Version:3.6
* Qt Version:3.52
* PyQt Version:3.5
* Operating system:win10

**Comment by ccordoba12** [comment]
`set SPYDER_DEBUG=3` was already fixed and it'll be part of Spyder **3.2.2**.

Sorry for the inconvenience in the meantime.

**Comment by boazdori** [comment]
ran set SPYDER_DEBUG=3 still getting the same error

**Comment by ccordoba12** [comment]
I know, the fix hasn't been released yet to a public version. But this bug was already fixed here, in Github.

**Comment by boazdori** [comment]
sorry thanks
