### ISSUE TITLE
Increase the limit of DPI setting for IPython inline graphics 

### ISSUE THREAD

**Issue by raphaeldeimel** [spyder-ide/spyder#5026]
## Description of your problem

**What steps will reproduce the problem?**
1. Run Spyder on a high-DPI Monitor (e..g Laptop with 203 DPI screen). Inline graphics are rendered with unreadable, super-tiny text
2. Go to Tools->Preferences->Ipython Console->Graphics Tab->Inline backend section
3. Try to increase the "Resolution" parameter past 99DPI

**What is the expected output? What do you see instead?**
One should be able to enter triple-digit values, but the GUI does not allow that
Clicking the arrow (or using up key), one is able to increase the DPI, but only to 150.0

The user should be able to set triple-digit DPI values, and to set very large DPI values.

A workaround is to increase all font sizes in the matplotlibrc, but this in turn breaks the correct text size when saving figures to e.g. pdf. 

**Please provide any additional information below**
## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 3.5
* Qt Version: 5.7.1
* PyQt Version: 5.7
* Operating system: Ubuntu 17.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll increase our limit in 3.2.2.

@rlaverde, I think increasing this to 999 should be enough.
