### ISSUE TITLE
error on spyder startup

### ISSUE THREAD

**Issue by ericdelakwame** [spyder-ide/spyder#5029]
## Description
  File "C:\Users\hnic\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 154, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
WARNING:traitlets:kernel died: 6.0134117603302
WARNING:traitlets:kernel died: 6.0070106983184814

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\hnic\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 154, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)
WARNING:traitlets:kernel died: 6.0134117603302
WARNING:traitlets:kernel died: 6.0070106983184814

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
What were you doing when you got this error?

**Comment by ericdelakwame** [comment]
Thanks.
new to python. wa practicing coding.
