### ISSUE TITLE
Add a space after # for commenting

### ISSUE THREAD

**Issue by ZhiliangWu** [spyder-ide/spyder#5034]
## Description of your problem

**What steps will reproduce the problem?**

comment one line of code 

**What is the expected output? What do you see instead?**
say the python code is `x = np.zeros((5, 5))`
Now it looks like `#x = np.zeros((5, 5))`, but according to the standard way of commenting, it should looks like `# x = np.zeros((5, 5))`, which has a space after `#`

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.2.1
* Python Version:3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Linux( Ubuntu 14.04)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We're aware of this issue and we're working to fix it in a future release.

**Comment by juliangilbey** [comment]
Hi, this has been closed, but the problem still appears to persist.  I'm using Spyder version 3.3.5.

Best wishes

**Comment by ccordoba12** [comment]
This will be fixed in Spyder 4, to be released in some months.
