### ISSUE TITLE
Replace selection adds alien backslash character before dot. foo.bar becomes foo\.bar

### ISSUE THREAD

**Issue by mvbentes** [spyder-ide/spyder#5039]
## Description of your problem
The **replace** modal has a problem with the `replace selection` option. Everywhere a dot is suposed to appear, it does so preceded by a backslash.

**What steps will reproduce the problem?**

1. Select some text and hit `ctrl+R`. Example: `foobar`
2. Fill the `replace with` field with something that includes dots. Example: `foo.ba.z .ao aoa . aoouaaoh.`
3. Hit `Replace selection`. Output: `foo\.ba\.z\ \.ao\ aoa\ \.\ aoouaaoh\.`

**Please provide any additional information below**
Looks like a regex escaping issue. It does not happen with either the `replace/find next` or the `Replace all` buttons.

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6.2 64 bits
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Win 7 64 bits

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  None (NOK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by mvbentes** [comment]
Just saw the same issue as closed, so I will wait for that update.

**Comment by ccordoba12** [comment]
Thanks!
