### ISSUE TITLE
Word operators do not have a color style in the IPython console

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#5040]
## Description of your problem

**What steps will reproduce the problem?**

1. write in the IPython console: `for operator in [or, and, is, in]`:

![word_operator_not colored](https://user-images.githubusercontent.com/10170372/29630274-a20467c2-8809-11e7-9433-ddbec22be964.png)

**What is the expected output? What do you see instead?**
The word operators `in`, `and`, `is`, `or` should have the same style as `for` to match the behaviour of the Spyder editor.

![word_operator_colored](https://user-images.githubusercontent.com/10170372/29630267-9a8505f6-8809-11e7-89c0-a1d6c1387fb3.png)
 in]`

**Please provide any additional information below**

## Versions and main components

* Spyder Version: branch 3.x and master
* Python Version: 3.6.1
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows 7 64 bits

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by andfoy** [comment]
@jnsebgosselin Is it possible to highlight self as well? Or is it already highlighted?

**Comment by jnsebgosselin** [comment]
@andfoy yes `self` seems to be highlighted correctly
