### ISSUE TITLE
multiline editing!

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#5043]
Hi thank you for this great editor, I like it so much and using it for my PhD project.

I would like to ask if multiline editing is possible in spyder? I searched online but could find anything related to the topic

Thanks in advance.

**Comment by jnsebgosselin** [comment]
We are currently working on this and this should be available in Sypder 4. Please see https://github.com/spyder-ide/spyder/issues/2112 for more info on this topic.

**Comment by goanpeca** [comment]
Closing as duplicate of https://github.com/spyder-ide/spyder/issues/2112

**Comment by Shalmalee1507** [comment]
Is there an update on this? Would like to know. Thanks in advance!

**Comment by Jomme5** [comment]
2022 how it's going with multiline editing?
