### ISSUE TITLE
Spyder doesn't start

### ISSUE THREAD

**Issue by gwillig** [spyder-ide/spyder#5055]
## Description of your problem
Spyder doesn't start
**What steps will reproduce the problem?**

1. Click the spyder.icon (pythonw.exe)

**What is the expected output? What do you see instead?**
Spyder should start

**Please provide any additional information below**
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

When I type `spyder --show-console` in cmd i receive the following message:

```
Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\WLG1FE\AppData\Local\Continuum\Anaconda3\lib\site.py", line 73,
 in <module>
    import os
  File "C:\Users\WLG1FE\AppData\Local\Continuum\Anaconda3\lib\os.py", line 77, i
n <module>
    import ntpath as path
  File "C:\Users\WLG1FE\AppData\Local\Continuum\Anaconda3\lib\ntpath.py", line 1
, in <module>
    g# Module 'ntpath' -- common operations on WinNT/Win95 pathnames
NameError: name 'g' is not defined`

C:\Users\WLG1FE>
```

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
I think your Anaconda installation is broken. Please uninstall and reinstall it again, or install Spyder in a new conda environment and try to start from there.
