### ISSUE TITLE
Spyder crashed when i clicked 'SAVE'

### ISSUE THREAD

**Issue by smqizq** [spyder-ide/spyder#5056]
## Description

**What steps will reproduce the problem?**

1. I qouted several lines with ''''''
2. I clicked 'SAVE'
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "d:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1474, in save
    finfo.encoding)
  File "d:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'D:\\spyder\\py_excel.py'

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1978, in save
    return editorstack.save(index=index, force=force)
  File "d:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1507, in save
    self)
TypeError:   QMessageBox(QMessageBox.Icon, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.NoButton, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 4 has unexpected type 'EditorStack'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.

**Comment by smqizq** [comment]
I found the reason, because the file I am about to save is hidden, After I removed the hidden attribute, It worked well.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
