### ISSUE TITLE
Fresh Anaconda Installation won't start Spyder with "No Qt bindings could be found"

### ISSUE THREAD

**Issue by Dschoni** [spyder-ide/spyder#5059]
I Installed Spyder with different versions of Anaconda, all resulting in the same error, that I can't start Spyder with the Error message: "qtpy.PythonQtError: No Qt bindings could be found"

I manually installed QT5 and pyqt5 bindings, but that didn't solve the problem.

**What steps will reproduce the problem?**

1.  Install Spyder from Anaconda
2. Start Spyder (from terminal)

**What is the expected output? What do you see instead?**

Spyder should start. Instead it shows the aforementioned error message.

**Please provide any additional information below**

```
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/me/anaconda3  (writable)
    default environment : /home/me/anaconda3
       envs directories : /home/me/anaconda3/envs
                          /home/me/.conda/envs
          package cache : /home/me/anaconda3/pkgs
                          /home/me/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.1 Linux/4.8.0-59-generic debian/stretch/sid glibc/2.24
```

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1.final.0
* Qt Version: 5.6.2
* PyQt Version: qtpy 1.2.1
* Operating system: Ubuntu 16.10

**Comment by ccordoba12** [comment]
Do you have set LD_LIBRARY_PATH?

**Comment by Dschoni** [comment]
Not manually. When searching for my problem, I found your answers regarding this aspect and tried resolving my issue with unsetting any automatically set LD_LIBRARY_PATH (via unset). This didn't help.

I also tried this under different users, installed Anaconda to different locations both with root and as user. I manually installed QT5, tried python 2 and python 3 to no avail.

**Comment by Dschoni** [comment]
I found, that probably the issue is not spyder exclusive:

When I open a python console and do 

`import qtpy`

The same error happens.

**Comment by Dschoni** [comment]
One more point: `QT_API` is set to `pyqt`, unsetting or changing leads to a segmentation fault when starting spyder.

**Comment by Dschoni** [comment]
For now, I deinstalled anaconda3, got anaconda2 (v.4.4.0), did

```
pip uninstall PyQt5
unset QT_API
unset LD_LIBRARY_PATH
```

and can now use spyder again.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by samburu** [comment]
`conda install pyqt` worked for me

**Comment by jasonlcc3000** [comment]
Been looking all over for a solution. Anaconda Navigator and Spyder stopped working after I fiddled with the packages to make pyinstaller work - got the exe created but doesn't work still :(
For me, one of your commands worked to launch Anaconda Navigator and Spyder again:

pip uninstall PyQt5
Successfully uninstalled PyQt5-5.12

And I kept reinstalling and updating like crazy as that's what was recommended by many!!!!!
Thanks a mil.
