### ISSUE TITLE
Kernel dies when trying to run PyTorch code on Linux

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#5060]
Please see this SO question for the details:

https://stackoverflow.com/questions/45875837/spyder-just-kernel-died-restarting-when-i-run-net-forward-in-pytorch

@andfoy, please take a look at this one.

**Comment by andfoy** [comment]
@ccordoba12 Does mixing Spyder versions from PyPi and conda might have some responsibility here? According to the package dump posted by the user, Spyder 3.1.4 and 3.2.1 are both listed:
```
spyder                    3.2.1                     <pip>
spyder                    3.1.4                    py27_0
```

**Comment by ccordoba12** [comment]
Probably, but did you try to run the OP code?

**Comment by andfoy** [comment]
The code posted by the OP works as expected: 
![captura de pantalla de 2017-08-25 11-40-05](https://user-images.githubusercontent.com/1878982/29723493-724979c8-898a-11e7-816c-043104d33109.png)

Actually, it works if I use a deeper model such as the ResNet-101:

![captura de pantalla de 2017-08-25 11-42-42](https://user-images.githubusercontent.com/1878982/29723588-cc982e6a-898a-11e7-959c-69bbcd0e34e1.png)

**Comment by selous123** [comment]
Thank you very much for your answering.

also i run this code with the same version in my other computer.it works well!!!

I try  to solve the mixing version problem. delete the redundant package 3.1.4.**but still "kernel died,restarting"**


first I doubt whether **Spyder** and pytorch have collision in the kernel.
Obviously,The problem should be in the configuration of my own computer
Sadly,there is no error message in the terminal about the kernel died

![selection_014](https://user-images.githubusercontent.com/23351749/29756438-a11e36f0-8bd6-11e7-9dc0-bc642976aaf2.jpg)

**Comment by ccordoba12** [comment]
It seems this is fixed in the latest version of PyTorch:

https://github.com/jupyter/notebook/issues/2784#issuecomment-325230024

**Comment by selous123** [comment]
not only it has errors in the spyder,but also in jupyter and terminal..

[Problem Description](https://github.com/jupyter/notebook/issues/2784#issuecomment-325230024)

**Comment by selous123** [comment]
Just now,I update all the packages in anaconda

`conda update --all`

delightedly the code runs well in terminal and jupyter,but the error in the spyder also exists

**Comment by andfoy** [comment]
Well, I'm running the latest package versions on my current setup, and it works as expected. Any ideas @ccordoba12 ?

**Comment by andfoy** [comment]
Also, the user reports that on a new installation, the package works. @selous123 Have you tried to create a new conda environment on your conflicting PC?

**Comment by selous123** [comment]
everything goes well 

when i use **Source installation**  instead of "pip install..." as official website proposal to reinstall my pytorch and it works.

thank you very much

**Comment by andfoy** [comment]
@selous123 For future installation, PyTorch developers recommend to install the package using conda:
```
conda install pytorch torchvision -c soumith
```
