### ISSUE TITLE
Run in external system terminal doesn't work in macOS

### ISSUE THREAD

**Issue by andrewd76** [spyder-ide/spyder#5062]
## Description

**What steps will reproduce the problem?**

1. open python file
2. "run"->"configuration per file.."
3. set "execute in an external system terminal"
4. "run"
5. nothing happens

**What is the expected output? What do you see instead?**

I expected Terminal app appearance, but terminal doesn't load

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1 and 2.7
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

Best regards,
Andrew

**Comment by ccordoba12** [comment]
We don't have support for running files in system terminals in macOS, but we'll work to add it in a future release.

**Comment by andrewd76** [comment]
Thank you!

**Comment by CAM-Gerlach** [comment]
@juanis2112 I'm about to push a PR with some fixes and improvements to this feature and its tests on Windows and Linux. After that, might you perhaps be able to implement and test a code snippet (e.g. [something like this](https://stackoverflow.com/questions/4404242/programmatically-launch-terminal-app-with-a-specified-command-and-custom-colors) ) to add this functionality? We've had requests for it on our Gitter and it would help bring our macOS platform closer to parity with the others.
