### ISSUE TITLE
clear screen command does not work in IPython console

### ISSUE THREAD

**Issue by che-burashka** [spyder-ide/spyder#5063]
## Description of your problem

**What steps will reproduce the problem?**

1. run some commands
2. hit Ctrl-L
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
You need to update to `qtconsole` 4.3.1 to have a fix for this.

You can do that by running

    conda update qtconsole

or

    pip install -U qtconsole

in a system terminal (cmd.exe on Windows or xterm/konsole/gnome-terminal on Linux).
