### ISSUE TITLE
Error on scrolling to the bottom

### ISSUE THREAD

**Issue by tribbloid** [spyder-ide/spyder#5065]
## Description

**What steps will reproduce the problem?**

1. Scroll a python file to the buttom

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 250, in fetchMore
    self.rows_loaded + items_to_fetch)
  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 174, in set_size_and_type
    for index in range(start, stop) ]
  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 174, in <listcomp>
    for index in range(start, stop) ]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.5.3
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
The error is completely unrelated to scrolling files in the Editor. Are you sure you got this error that way?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
