### ISSUE TITLE
Last macOS dmg installer is from Nov 21 (3.0.2)

### ISSUE THREAD

**Issue by lukaskawerau** [spyder-ide/spyder#5067]
## Description of your problem

There is no available dmg-installer for macOS for a current version of Spyder.
The last available installer is for version [3.0.2](https://github.com/spyder-ide/spyder/releases/tag/v3.0.2) back from November 21 2016.

**Comment by ccordoba12** [comment]
Sorry, we don't have plans to update our DMG installer for the time being, sorry. Please use Anaconda instead.

**Comment by lukaskawerau** [comment]
In that case, the README.md should remove any mention of the DMG installer, no?  
It is also confusing that Spyder prompts you to update to the newest version when you open it, redirects you to Github and then you can't update because there's no new DMG installer available.

Why will there be no new DMG installer?

**Comment by ccordoba12** [comment]
> Why will there be no new DMG installer?

Because I don't have time to create new installers. I'll remove the reference in our README, thanks for pointing that out.
