### ISSUE TITLE
Save Button Dormant

### ISSUE THREAD

**Issue by tjellsworth** [spyder-ide/spyder#5070]
![spyder save error](https://user-images.githubusercontent.com/19624519/29745924-8950bcb0-8b03-11e7-9e05-61fa04b436bb.png)
## Description of your problem
The save button went dormant.
**What steps will reproduce the problem?**

1. Open Sypder
2. Open my file
3. Open the File Explorer to set the working directory
4. I cannot press the save button

**What is the expected output? What do you see instead?**
To be able to save the file

**Please provide any additional information below**

## Versions and main components

* Spyder Version: I don't know it came with Anaconda
* Python Version: 3.6
* Qt Version: ?
* PyQt Version: ?

* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jnsebgosselin** [comment]
Have you done any changes to your file? What happens if you make a change to your file like adding a blank space for example? The save buttons always become inactive when there is nothing to save.

**Comment by tjellsworth** [comment]
Jean-Sébastien,
Thank you. This worked.

Tim Ellsworth
Toyota Motor Manufacturing Mississippi
Model Change Production Engineering Specialist

Worcester Polytechnic Institute Class of 2013
BSME/MSMG

**Comment by jnsebgosselin** [comment]
This is great. Thank you for testing it.
