### ISSUE TITLE
remark: autocompletion in spyder-3.2.1 editor is broken under python-3.6.2 by enum34 package

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder#5071]
## Description of your problem

**What steps will reproduce the problem?**

1. on WinPython-64bit-3.6.2.0Qt5, the auto-completion doesn't work in the editor
2. "pip uninstall enum34" resolves it
3. faulty pymc3 wheel caused the no-needed installation of enum34

**What is the expected output? What do you see instead?**
see https://github.com/winpython/winpython/issues/563#issuecomment-325050265

**Please provide any additional information below**
may have appeared in the past under https://github.com/spyder-ide/spyder/issues/4410

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by gchandra33** [comment]
auto completion in spyder-3.2.1 editor is not working under Winpython ver 3.6.2 can you please help
