### ISSUE TITLE
Crash when inspecting variable during debugging

### ISSUE THREAD

**Issue by abhayap** [spyder-ide/spyder#5077]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 592, in setEditorData
    editor.setDateTime(QDateTime(value.date(), value.time()))
AttributeError: 'NoneType' object has no attribute 'date'
Traceback (most recent call last):
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 592, in setEditorData
    editor.setDateTime(QDateTime(value.date(), value.time()))
AttributeError: 'NoneType' object has no attribute 'date'
Traceback (most recent call last):
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 592, in setEditorData
    editor.setDateTime(QDateTime(value.date(), value.time()))
AttributeError: 'NoneType' object has no attribute 'date'
Traceback (most recent call last):
  File "/Users/abhaya/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 592, in setEditorData
    editor.setDateTime(QDateTime(value.date(), value.time()))
AttributeError: 'NoneType' object has no attribute 'date'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Please post the object you were trying to inspect when this error happened.

**Comment by abhayap** [comment]
How do I post the object?

**Comment by ccordoba12** [comment]
By posting the code you used to generate that object, e.g.

    import numpy as np
    a = np.array([1, 2, 3])

if it were an array.

**Comment by abhayap** [comment]
This is it. It was a call to a rest api.
```
s = requests.Session()
s.headers.update(headers)
adapter = requests.adapters.HTTPAdapter(pool_connections=10, pool_maxsize=50,
                                        max_retries=5, pool_block=False)
s.mount('http://', adapter)
s.mount('https://', adapter)
r = s.get(revisionsapiurl.format(parent, startrevid,
                                         currendrevid, 'desc'), timeout=11)
js = r.json()
```

**Comment by ccordoba12** [comment]
The code is not complete, sorry. We need you to give us a code that we can execute in our side.

**Comment by ccordoba12** [comment]
Closing because you're code is not complete. Please reopen when you post a complete code.
