### ISSUE TITLE
ValueError: not enough values to unpack in the File Explorer

### ISSUE THREAD

**Issue by osirisjs** [spyder-ide/spyder#5080]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\overt_000\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 154, in icon
    file_type, bin_name = mime_type.split('/')
ValueError: not enough values to unpack (expected 2, got 1)

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by ErmanIZTECH** [comment]
How is this going to be solved excuise my unconvenience :(

**Comment by ccordoba12** [comment]
I'll fix this for our next version, to be released next week.

**Comment by ErmanIZTECH** [comment]
Thank you sir.

**Comment by csabella** [comment]
@ccordoba12  If it helps, every error report was on a Windows system.
