### ISSUE TITLE
Memory leak when there are objects in an imported module

### ISSUE THREAD

**Issue by arman00** [spyder-ide/spyder#5084]
## Description
Memory is not released for the objects existing in an imported module. After I use %reset -sf, although it clears all the objects in the variable explorer, it does not clear the objects in the imported module. 

**What steps will reproduce the problem?**

1. Create dummy_mem.py including below lines:
```python
import numpy
arr = numpy.zeros(1024*1024*128)
```
2. Create test_mem.py including below line:
```python
import dummy_mem
```
3. Clear memory, for instance by calling %reset -sf in the console
4. Check the memory usage (In Windows I check pythonw.exe with process explorer)

**What is the expected output? What do you see instead?**
Actual: memory is not released, I read high memory usage on pythonw.exe about 1.1GB
Expected: Memory is released, memory usage on pythonw.exe is about 150Kb

**Please provide any additional information below**
Restart the kernel clears the memory. Also, another way to clear is to run a script without including that module together with %reset -sf. For instance, after I run %reset -sf in the console and then comment out the import line and run test_mem.py again (hit F5), memory is released. Actually the order is not important: if I first comment out and run the script, and then call %reset -sf, it works, too. But only calling %reset -sf  alone (without running a script) does not trigger memory release for the objects in the imported module.

## Version and main components

* Spyder Version: 3.2.2.dev0 
* Python Version: 3.5.3
* Qt Versions: 5.8.0, PyQt5 5.8.1 on Windows

## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by AraHaan** [comment]
This could help if all instances of pythonw.exe was to have the gc module enabled to automatically garbage collect objects that has no references anymore. Although I dont see why they are not automatically collected yet because of python automatically using garbage collection by cgc (Cyclic Garbage Collection) based on reference counting. 🤔

**Comment by ccordoba12** [comment]
Sorry, this is an IPython problem. Please raise this problem with them.

**Comment by arman00** [comment]
Ok, I raised this issue with IPython.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by arman00** [comment]
https://github.com/ipython/ipython/issues/10764#issuecomment-326094539
