### ISSUE TITLE
Spyder 3 not responding

### ISSUE THREAD

**Issue by sugarujumbo** [spyder-ide/spyder#5092]
## Description of your problem

first accidentally installed WinPython 3.5.4.0Qt5-32bit, then tried to uninstall it but couldn't find the option.  Then I installed WinPython 3.6.2.0Qt5-64bit. 

**What steps will reproduce the problem?**
Launched Spyder3 and once launched it goes into "Not Responding" mode

One thing i noticed in the task manager is multiple instances of QtWebEngineProcess.exe, pythonw.exe and 2 python.exe is present.

I tried by deleting the .spyder-py3 folder under settings, didn't solve my issue.

## Versions and main components

* Spyder Version: 3
* Python Version: 3.5.4
* Qt Version:
* PyQt Version: 
* Operating system: I'm using Windows 7 64bit

**Comment by ccordoba12** [comment]
Please report this in the WinPython repo:

https://github.com/winpython/winpython/
