### ISSUE TITLE
Index Error when copying only the "In [1]: " part of an input line.

### ISSUE THREAD

**Issue by BlckKnght** [spyder-ide/spyder#5095]
## Description

If you try to copy only the prompt (and its trailing space) from an IPython console tab, you get an IndexError. The text does get copied.

**What steps will reproduce the problem?**

1. Run any line of code in an IPython console (it can be a trivial expression, like `42` or `"spam"`).
2. Highlight the "In [1]: " prompt from the previous line with your mouse. Make sure you include the space between the prompt and the actual statement in the selection.
3. Press CTRL+C to copy the selected text.

**What is the expected output? What do you see instead?**

I'd expect the prompt to be copied silently. Instead, I get a popup with the exception traceback seen below. The text *is* successfully copied to the clipboard however. I'd guess the issue happens when the program tries to trim out the prompt (as it does successfully if I select a larger amount of text including some of the statement on the line). I'd guess there's an off-by-one error in the code somewhere.

**Please provide any additional information below**

  File "S:\Python36\lib\site-packages\qtconsole\console_widget.py", line 412, in eventFilter
    return self._event_filter_console_keypress(event)
  File "S:\Python36\lib\site-packages\spyder\widgets\ipythonconsole\debugging.py", line 103, in _event_filter_console_keypress
    self)._event_filter_console_keypress(event)
  File "S:\Python36\lib\site-packages\qtconsole\frontend_widget.py", line 381, in _event_filter_console_keypress
    return super(FrontendWidget, self)._event_filter_console_keypress(event)
  File "S:\Python36\lib\site-packages\qtconsole\console_widget.py", line 1424, in _event_filter_console_keypress
    self.copy()
  File "S:\Python36\lib\site-packages\qtconsole\frontend_widget.py", line 249, in copy
    was_newline = text[-1] == '\n'
IndexError: string index out of range

## Version and main components

* Spyder Version: 3.2.0 (note, I can also reproduce the issue in Spyder 3.2.1)
* Python Version: 3.6.2
* Qt Versions: 5.7.1, PyQt5 5.7.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.1

**Comment by ccordoba12** [comment]
This is an error in the `qtconsole` package, not in Spyder. So please open it there:

https://github.com/jupyter/qtconsole
