### ISSUE TITLE
Editor and ipython console tabs have no "close tab" icons

### ISSUE THREAD

**Issue by biaojiang** [spyder-ide/spyder#5097]
## No "close tab" icons appear on the tab buttons
**So, it is annoying that it is not convenient to close the files or ipython consoles**

## Versions and main components
* Spyder 3.2.1 or 3.4 by "python bootstrap.py":
* Python 3.6.2:
* PyQt 5.9:
* MacBook Pro with touch bar, Sierra 10.12.6:

**However, spyder on other Macs are OK**
For python 3.6.1, Sierra 10.12.6, on iMac and MacBook Air, the spyder layouts work fine.
What is the solution?

**Comment by ccordoba12** [comment]
It seems a Qt issue. Nothing we can do in our side other than recommending you to use Anaconda instead.

**Comment by biaojiang** [comment]
I found it is Pyqt5 version problem. For Pyqt5.8, it is OK, all the tabs have the "close" icon to close it, however, after upgraded to 5.9, the editor tabs become white board tab.
