### ISSUE TITLE
After a power failure, cannot launch spyder

### ISSUE THREAD

**Issue by anisioboreli** [spyder-ide/spyder#5102]
## Description of your problem
After a power failure, I cannot launch spyder anymore. I already tryed **spyder --reset**, uninstalling and installing again. Every time I try to open it, this message appears "
![screenshot 2017-08-31 13 27 17](https://user-images.githubusercontent.com/29805366/29934080-3d9bbb94-8e50-11e7-8204-247c3dcf6825.png)
"

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
After the power failure, the folder **jedi-0.10.2.dist-info** was corrupted. I already removed Jedi using _pip uninstall jedi_ and installed it again.

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.5.3
* Qt Version: 
* PyQt Version:
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please try to reinstall Spyder. I really don't know what's happening in this case, so that's my only advice, sorry.
