### ISSUE TITLE
Hide _pycache_ folder in Project and File explorers

### ISSUE THREAD

**Issue by ajayrathore** [spyder-ide/spyder#5108]
## Description of your problem

**What steps will reproduce the problem?**

1. On loading a package, spyder ide creates a "_pycache_" folder which is very annoying, there should be an option to hide this meta information from the user, it creates unnecessary noise.

**What is the expected output? What do you see instead?**
There should be an option to hide this _pycache_ folder

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6.2
* Qt Version:
* PyQt Version:
* Operating system: MacOS

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
That folder is created by Python, not by Spyder. What we can do is hide it from our File and Project explorer views, but not directly from disk.

**Comment by ajayrathore** [comment]
Yes, hiding it from editor view is good enough, don't need to delete from disk

**Comment by ajayrathore** [comment]
Can I know when this will be released? Will this be available in next spyder release?

**Comment by ajayrathore** [comment]
Just downloaded 3.2.3-py36_0, is this fix included in that release. If yes, where is the option to hide __pycache__ folder?

**Comment by ccordoba12** [comment]
If the issue is *not* closed, it's because is not fixed. If you want to see this fixed quickly, please send a pull request for it.
