### ISSUE TITLE
Unable to save file in Python

### ISSUE THREAD

**Issue by anilbhargava** [spyder-ide/spyder#5111]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\abharg\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1474, in save
    finfo.encoding)
  File "C:\Users\abharg\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 227, in write
    with open(filename, mode) as textfile:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\abharg\\Dropbox\\Python Programming\\Session 3. Basic Statistics in Python\\3.Basic statistics_V3_bhuvn.py'

Traceback (most recent call last):
  File "C:\Users\abharg\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1507, in save
    self)
TypeError:   QMessageBox(QMessageBox.Icon, str, str, buttons: Union[QMessageBox.StandardButtons, QMessageBox.StandardButton] = QMessageBox.NoButton, parent: QWidget = None, flags: Union[Qt.WindowFlags, Qt.WindowType] = Qt.Dialog|Qt.MSWindowsFixedSizeDialogHint): argument 4 has unexpected type 'EditorStack'

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas

**Comment by rlaverde** [comment]
According to the traceback, you don't have enough permitions to edit that file:
`PermissionError: [Errno 13] Permission denied: 'C:\Users\abharg\Dropbox\Python Programming\Session 3. Basic Statistics in Python\3.Basic statistics_V3_bhuvn.py'`

Although there is an error in the handling of the permissions error (introduced in #4870), I'll open a PR with a fix.
