### ISSUE TITLE
Spyder-notebook error on startup

### ISSUE THREAD

**Issue by sprague252** [spyder-ide/spyder#5112]
## Description

**What steps will reproduce the problem?**

1. Start spyder with a fresh install of the spader-notebook plugin

**What is the expected output? What do you see instead?**
Error dialog box pops up and the notebook is unusable.

**Please provide any additional information below**

I am not sure if this is going to the right group. I am just submitting as suggested by the dialog box that pops up when I launch Spyder with spyder-notebook freshly installed by pip.

  File "/opt/anaconda/lib/python2.7/site-packages/spyder/otherplugins.py", line 79, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/opt/anaconda/lib/python2.7/site-packages/spyder/otherplugins.py", line 101, in _import_module_from_path
    info = imp.find_module(module_name, [plugin_path])
ImportError: No module named spyder_notebook-0.1.1.dist-info

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by dalthviz** [comment]
Issue moved to [spyder-ide/spyder-notebook #114](https://github.com/spyder-ide/spyder-notebook/issues/114) via [**ZenHub**](https://www.zenhub.com/)
