### ISSUE TITLE
KeyboardInterrupt error in waitingspinner

### ISSUE THREAD

**Issue by awsiitchs** [spyder-ide/spyder#5114]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/Leo/anaconda/lib/python3.6/site-packages/spyder/widgets/waitingspinner.py", line 177, in rotate
    def rotate(self):
KeyboardInterrupt

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by rlaverde** [comment]
I think this is caused because the waiting spinner is started in the creation of find in files, and never stopped (only the progress bar is hidden/shown) https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/findinfiles.py#L784

**Comment by ccordoba12** [comment]
Thanks for noticing @rlaverde! Should we stop it then after it's hidden?

**Comment by rlaverde** [comment]
Yes, start it when progress bar is shown and stop it when progress bar is hidden.

Although if you press Ctrl+C while it's shown and spinning (i.e. searching in files) the error will occur

**Comment by goanpeca** [comment]
>Although if you press Ctrl+C while it's shown and spinning (i.e. searching in files) the error will occur

We should be able to prevent this

**Comment by rlaverde** [comment]
@goanpeca I'm not sure If that will work, the error occur when trying to kill spyder process (pressing `Ctrl+C` in the terminal that is running spyder).

I don't know if maybe another event raise this error, neither this issue or #5049, have steps to reproduce the error.

**Comment by goanpeca** [comment]
ahhh @rlaverde ok I understand. Actually I think that is a spyder bug, we should be able to kill spyder from the console.
