### ISSUE TITLE
I dont know why all my Spider windows are disappear

### ISSUE THREAD

**Issue by cmhjerry** [spyder-ide/spyder#5120]
## Description
I just tried to switch my window layout to Matlab Layout. Then everything disappeared and can't switch back. Could u please let me know how I can solve it? It is urgent. Thank you.

![image](https://user-images.githubusercontent.com/22530674/30009343-a31070d0-90f5-11e7-9e33-06d3b1b54bc0.png)

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by rlaverde** [comment]
You could execute `spyder --reset` to reset to the default settings
