### ISSUE TITLE
spyder(runfile, wdir)

### ISSUE THREAD

**Issue by alistairchua** [spyder-ide/spyder#5124]
I'm new to python programming so please forgive me for being such a noob. There is no output after I have inputed my code. I inputed my code as below: 

**What steps will reproduce the problem?**

1. import numpy as np
import scipy.ndimage
from scipy.misc.pilutil import Image

a = Image.open(C:\Users\Russell\Downloads\laferrari.jpeg).convert("L")

k = np.ones((5,5))/25

b = scipy.ndimage.filters.convolve(a, k)
b = scipy.misc.toimage(b)
b.save(C:\Users\Russell\Downloads\mean_output.jpeg)

**What is the expected output? What do you see instead?**
runfile('C:/Users/Russell/Desktop/New folder (4)/test1.py', wdir='C:/Users/Russell/Desktop/New folder (4)')

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Qt Version: Not sure
* PyQt Version: 4.2.1
* Operating system: Not so sure

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
The result is correct. `runfile` is the command used by Spyder to run your files in our IPython consoles.
