### ISSUE TITLE
Sources checkable preferences aren't sync with preferences

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#5131]
## Description of your problem

- Changing blank spaces, or indent guides from `Source` menu doesn't update preference
- Changing blank spaces, or indent guides in preferences doesn't update preference `Source` menu

**What steps will reproduce the problem?**

1. Activate/deactivate show blank spaces, or show indent guides form source menu
2. Go to Tool>Preferences>Editor
3. The changes aren't reflected
4. Restart spyder, the changes wasn't saved

--
1. Go to Tool>Preferences>Editor
2. Activate/deactivate show blank spaces, or show indent guides 
3. Go to source menu, the changes aren't reflected

* Spyder Version: It happens in spyder3 and 4, with the difference that indent guides isn't present in spyder3

I'm not sure what is the best way to fix this, after #5130 and #5122 it will be four different checkable options, implementing each one independently will cause some duplicated code.

**Comment by ccordoba12** [comment]
@rlaverde, we need to solve this one for beta1.
