### ISSUE TITLE
What is unicode error? 

### ISSUE THREAD

**Issue by alistairchua** [spyder-ide/spyder#5134]
Thanks for your help previously. Now I have a new problem. As I enter my edited code, it return as below: 

**What steps will reproduce the problem?**
This is my edited code: 
import numpy as np
import scipy.ndimage
from scipy.misc.pilutil import Image
a = Image.open('C:\Users\Russell\Downloads\laferrari.jpeg').convert("L")
k = np.ones((5,5))/25
b = scipy.ndimage.filters.convolve(a, k)
b = scipy.misc.toimage(b)
b.save('C:\Users\Russell\Downloads\mean_output.jpeg')

**What is the expected output? What do you see instead?**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Russell\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "C:\Users\Russell\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Russell/Desktop/New folder (4)/test1.py", line 5
    a = Image.open('C:\Users\Russell\Downloads\laferrari.jpeg').convert("L")
                  ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.2
* Python Version: 3.6
* Qt Version: not sure
* PyQt Version: 4.2.1
* Operating system: not sure

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Sorry but this is not a place to ask for Python questions. I'll help you this time, but for the next one please ask somewhere else.

You need to change this line

    a = Image.open('C:\Users\Russell\Downloads\laferrari.jpeg').convert("L")

to

    a = Image.open('C:\\Users\\Russell\\Downloads\\laferrari.jpeg').convert("L")

because Python is taking `\U` as a unicode escape symbol. So using `\\` instead of `\` avoid this problem.
