### ISSUE TITLE
Editor removing characters when pressing TAB to indent or enter for linebreaks.

### ISSUE THREAD

**Issue by sugoidesune** [spyder-ide/spyder#5136]
Description of your problem

What steps will reproduce the problem?

its sporadic. but might be because sometimes the only way to remove indents is to use ctrl-backspace
a regular backspace wont do anything. maybe because of the cell creating characters. #%%
restarting spyder didnt change it.
and after when adding indent with tab afterwards, it deletes the first couple characters.
the enter has a similar reason. hard to pin it down.
gifs showing it:
https://media.giphy.com/media/3ohhwjhhtZcPfGzaLe/giphy.gif
https://media.giphy.com/media/3o7aD18OHv7vYOpFlK/giphy.gif

I'm using Indentation characters "Tabulations", not Space indentation. Tab stop with: 6 spaces

Please provide any additional information below

Versions and main components

Anaconda 1.6.2
Spyder Version: 3.1.4
Python Version: 3.6

**Comment by ccordoba12** [comment]
@rlaverde, this was fixed already, right?

**Comment by rlaverde** [comment]
@ccordoba12  Yes, I think this is duplicated of  #4475, already fixed in spyder3.2

@sugoidesune Please update spyder, and test if this error still happen.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
