### ISSUE TITLE
Can not start the Spyder from Anaconda in the company (maybe firewall?)

### ISSUE THREAD

**Issue by thomas2004ch** [spyder-ide/spyder#5141]
## Description of your problem
I can install the Anaconda 3.4.4 without any problem. But as I start the Spyder, I got error as below:
"This application failed to start because it could not find or load the Qt platform pugin "windows" in "". 

Reinstalling the application may fix this problem."

I've reinstalled the Anaconda. It is the same.

But I have no problem at home. I guess it maybe the friewall in the company.

I've tried creating a file .condarc include the http-proxy etc. But this also doesn't help.

**What steps will reproduce the problem?**
1.  Starting the Spyder from Anaconda

**What is the expected output? What do you see instead?**
The Spyder should be started. But I got error as described above.

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.4.4?
* Python Version:Anaconda 3.4.4
* Qt Version:Not sure
* PyQt Version:Not sure
* Operating system:Window 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please use the latest version of Anaconda and try again.

**Comment by thomas2004ch** [comment]
My anaconda version is 3-4.4. This must be the latest version from Anaconda's HomePage:
https://www.anaconda.com/download/

**Comment by ccordoba12** [comment]
Yes, it is the latest version. Your problem is not caused by Internet access but if you installed Anaconda in a directory with spaces or non-ascii characters.

**Comment by thomas2004ch** [comment]
My Anaconda is installed under: C:\ProgramData\Anaconda3\. Is this OK?

**Comment by goanpeca** [comment]
@thomas2004ch looks like you installed for all users. That is not recommended in general (the latest installer warn about this). We advice to use the installation for current user.

**Comment by thomas2004ch** [comment]
Sorry for the late reply.

_ deinstall the Anaconda and reinstall it. This time just for me under C:\Users\myid\AppData\Local\Continuum\Anaconda3

But nothing is better. I get the same error as before.

**Comment by thomas2004ch** [comment]
No any answer?

**Comment by ccordoba12** [comment]
Sorry, we're out of ideas here...

**Comment by MAFiA303** [comment]
can you install as admin?

**Comment by thomas2004ch** [comment]
What do you mean install as admin? I have the local-admin right.

**Comment by thomas2004ch** [comment]
I solve the problem. I simply install the qt with 'conda install qt'.

That's all!

**Comment by ccordoba12** [comment]
I don't understand how your Anaconda installation ended up without Qt, but good news that you've finally found what to do!
