### ISSUE TITLE
Panes shortcuts not working when undocking panes

### ISSUE THREAD

**Issue by vthuongt** [spyder-ide/spyder#5143]
## Description of your problem

**What steps will reproduce the problem?**

1.  in normal view Ctrl+Shift plus either I or E will switch between IPython Console and Editor 
2. For the IPython Console click on the icon next to the button to close the pane. This will seperate the Console from the rest. (undock button?!)
3. Now put the cursor in the Editor and press Ctrl+shift+I -> Cursor won't jump to IPython Console as before!
4. now dock the Ipython Console back -> Shortcut will work again

**What is the expected output? What do you see instead?**
explained above

**Please provide any additional information below**
none 

## Versions and main components

* Spyder Version: 3,1,3
* Python Version: 3,6,0 64bits
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Win7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a known issue and we're working to try to fix it in Spyder 4, to be released next year.
