### ISSUE TITLE
pip created executable name changes between versions

### ISSUE THREAD

**Issue by TWAC** [spyder-ide/spyder#5144]
## Description of your problem
The executable name keeps changing between versions, requiring me to change my shortcut and relearn command line command.

**What steps will reproduce the problem?**
1. pip install spyder==3.2.0
2. find executable in C:\Python36\Scripts\spyder.exe
3. pip install spyder==3.2.1
4. find executable in C:\Python36\Scripts\spyder3.exe
5. pip install spyder==3.2.2
6. find executable in C:\Python36\Scripts\spyder.exe

**What is the expected output? What do you see instead?**
Always use spyder on Python 2 and spyder3 on Python 3.

**Please provide any additional information below**
The [entry_point](https://github.com/spyder-ide/spyder/blob/v3.2.2/setup.py#L323) is different for Python 2 and Python 3. But the wheels are [universal](https://github.com/spyder-ide/spyder/blob/v3.2.2/setup.cfg#L2). I assume different versions of Python have been used for creating the PyPI wheels.

## Versions and main components
* Spyder Version: Since 3.2.0
* Python Version: 3.6
* Qt Version: Qt5
* PyQt Version: PyQt5
* Operating system: Windows 10

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.0 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
You're totally right, thanks for pointing it out.

This means we have to stop creating universal wheels.
