### ISSUE TITLE
f2py helloworld not printing in Spyder's iPython console

### ISSUE THREAD

**Issue by jennirinker** [spyder-ide/spyder#5145]
## Description of your problem

When I create a simple Fortran helloworld file and compile it using f2py, the output works from python and ipython in the Anaconda Prompt but not the Spyder iPython console.

Here is the Fortran file `helloworld_fortran.f`:
```#fortran
c modified from http://finiteelementanalysis.org/Fortran77_Tutorials/f2py_f77.html
c     NAME OF THIS FILE - helloworld_fortran.f
c     ----------------------------------------

c     This subroutine prints hello World
c     on the screen

      subroutine greetings()

          print*, 'Hello, world! I am Fortran!'

      end subroutine greetings
```

**What steps will reproduce the problem?**

1. Navigate to directory with Fortran file in Anaconda prompt
2. `f2py -c helloworld_fortran.f -m helloworld_fortran --quiet`
3. From Spyder's iPython console, in the same directory:
```#python
from helloworld_fortran import greetings
greetings()
```

**What is the expected output? What do you see instead?**
I expect the console to print `Hello, world! I am Fortran!`, but nothing prints. If I do Step 3 above from an Anaconda prompt (either normal Python or iPython), then the function prints correctly.

**Please provide any additional information below**
I'm compiling my f2py functions using mingw according to the very useful instructions provided [here](https://www.scivision.co/f2py-running-fortran-code-in-python-on-windows/).

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 7

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. I think this is related to #3777.
