### ISSUE TITLE
AttributeError: 'super' object has no attribute '_handle_error' in IPython console

### ISSUE THREAD

**Issue by jiangxinjxau** [spyder-ide/spyder#5158]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Anaconda 4.3.0\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "D:\Anaconda 4.3.0\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this error in our 3.2.3 version.

Could you update qtconsole in the meantime, to see it it fixes this error? You can do that by running this command in a system terminal (i.e. `cmd.exe`):

    conda update qtconsole

**Comment by ajheller** [comment]
upgrading to  qtconsole 4.3.1-py27_0 fixed it for me.
  conda update qtconsole
Thanks... Aaron

**Comment by david-worrall** [comment]
Report, FYI. On OS X, Python 3.7.6 (default, Jan  8 2020 via Anaconda: Same error (system crash, irrespective of which graphics engine is selected.) both through Spyder and from the command-line - I suspect on window instantiation (using Screen(). Code runs fine in Python 2.7. If Anaconda can't fix this they should disable it, IMHO.
