### ISSUE TITLE
Issues with recognizing directory renaming

### ISSUE THREAD

**Issue by immersinn** [spyder-ide/spyder#5183]
## Description

**What steps will reproduce the problem?**

1.Probably a weird corner case that involves me doing things that are very contrary to best practices.  Renaming directories on the fly and then trying to move forward / backward in the File Explorer history caused the error.  Also noticed issues with properly refreshing directory contents, etc.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/immersinn/.virtualenvs/networks/lib/python3.5/site-packages/spyder/widgets/explorer.py", line 1132, in chdir
    os.chdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: '/home/immersinn/gits/networks/learning-path'

Traceback (most recent call last):
  File "/home/immersinn/.virtualenvs/networks/lib/python3.5/site-packages/spyder/widgets/explorer.py", line 1097, in go_to_previous_directory
    self.chdir(browsing_history=True)
  File "/home/immersinn/.virtualenvs/networks/lib/python3.5/site-packages/spyder/widgets/explorer.py", line 1135, in chdir
    except PermissionError:
UnboundLocalError: local variable 'PermissionError' referenced before assignment

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.5.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this after we release 3.2.3

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.
