### ISSUE TITLE
tab opens the interal console

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5192]
## Description

**What steps will reproduce the problem?**

1.  press tab in the editor

**What is the expected output? What do you see instead?**
I would expect to stay in the editor and not go to the internal console

**Please provide any additional information below**

  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 2, in <module>
NameError: name 'fghjkioihgvbnm' is not defined

## Version and main components

* Spyder Version: 4.0.0.dev0 5406a0d6b
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by impact27** [comment]
That only happens if the internal console is open. Otherwise I just loose the focus on the editor.

**Comment by impact27** [comment]
The four spaces are correctly added but the focus is lost

**Comment by rlaverde** [comment]
I think this is related to #5139 please test if it still occurs with the latest master

**Comment by impact27** [comment]
It looks solved thanks

**Comment by ccordoba12** [comment]
Thanks for the confirmation @impact27! Closing then.
