### ISSUE TITLE
Spyder complains about missing ipykernel module in external interpreters

### ISSUE THREAD

**Issue by Os3r3um** [spyder-ide/spyder#5193]
While trying to use Spyder with the Python3.6.3 core I get such error; "Your Python environment or installation doesn't have the ipykernel module installed on it. Without this module is not possible for Spyder to create a console for you."  

**What steps will reproduce the problem?**

1. Get Python 3.6.2 installed along with 3.5.4 
2. Launch Spyder and got to Tools -> Preferences -> Python Interpreter
3. Switch to python3.6
4. Try to open a new Ipython console 

**What is the expected output? What do you see instead?**

Get this error: 

```An error occurred while starting the kernel
Your Python environment or installation doesn't have the ipykernel module installed on it. Without this module is not possible for Spyder to create a console for you.

You can install ipykernel by running in a terminal:
pip install ipykernel
or
conda install ipykernel
```
**Please provide any additional information below**

have tried to install the missing ipykernel thinking it might be missing for the Python3.6 environment but no luck. The package seems to be already installed so nothing needs to be done. 

## Versions and main components

* Spyder Version: Spyder 3.2.2
* Python Version: 3.6.2
* Qt Version: 
* PyQt Version:
* Operating system: Kali Linux, all updates applied.

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.9.1 (OK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
I can't reproduce this error, sorry.

**Comment by autodataming** [comment]
I come acrosss the same error.

**Comment by ccordoba12** [comment]
@autodataming, we're working to improve this situation in our next release.

**Comment by afarane** [comment]
Same issue with me. It seems this is due to multiple envs in Conda and Python Installation

**Comment by gordonzhu** [comment]
Is there any way to solve this issue? While i'm useing python 2.7 it's working fine. 
But when i try to use py 3.6 it should the error:
An error ocurred while starting the kernel
Your Python environment or installation doesn't have the ipykernel and cloudpickle modules installed on it. Without these modules is not possible for Spyder to create a console for you.

You can install them by running in a system terminal:

pip install ipykernel cloudpickle

after i install the ipykernel cloudpickle from console, it's still not working.

**Comment by ccordoba12** [comment]
@gordonzhu, we're working to improve this in Spyder 3.3, to be released next month.

**Comment by simonkm1** [comment]
has it been fixed please?

**Comment by simonkm1** [comment]
With version 3.3.0 it complains about spyder-kernels:
An error ocurred while starting the kernel
Your Python environment or installation doesn't have the spyder‑kernels module installed on it. Without this module is not possible for Spyder to create a console for you.

**Comment by AdrienMau** [comment]
Same error, when I type python in my console, it launches _Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32_ that pip works with.
But in Spyder it uses version _Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]_
Trying to launches 3.6.5 executabe in spyder, gives my spyder-kernel issue.

**Comment by ccordoba12** [comment]
@AdrienMau, please read:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#2-the-modular-approach

to understand how to use other Python environments in Spyder.

**Comment by jennirinker** [comment]
This issue still exists. What's worse, the ``spyder-kernels`` package is not available with either conda or pip so I cannot run an ipython interpreter from my environment.

Steps to reproduce:
1. Create a new environment.
2. In Spyder, switch the interpreter to run from the python.exe located in the environment directory.
3. Spyder 3.3.1 complains that ``Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed.`` and recommends you install ``spyder-kernels=0.*`` using either pip or conda.
4. Try to install ``spyder-kernels`` using conda or pip.
5. Both attempts fail. (conda doesn't have the package, pip gets an "invalid requirement".

**Comment by ccordoba12** [comment]
@jennirinker, please see

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

for more info about this.

**Comment by BeatkinGourav** [comment]
I Installed fresh Anaconda and then within that when I open Spyder I got this message in return
![Capture](https://user-images.githubusercontent.com/19861987/77762723-f900ba80-705f-11ea-9847-5e1262c1a749.PNG)

I tried the following command to install ipykernels but after that also it is not showing.
conda create -n py38 python=3.8 spyder-kernels
conda install spyder-kernels
conda install ipykernels

and I got same issue with spyder until now. and when I tried to update spyder in anaconda to the latest version it shows me unable to update.

**Comment by thethea** [comment]
I stumbled upon the same issue as @BeatkinGourav.

**Comment by goanpeca** [comment]
>and I got same issue with spyder until now. and when I tried to update spyder in anaconda to the latest version it shows me unable to update.

Try

```
conda update anaconda
conda update spyder
```

**Comment by DSLituiev** [comment]
I'm getting this issue 3 years after it's closed. When I follow the instruction with the `conda install spyder‑kernels=0.*` in the environment of the Python executable, I get:

```PackagesNotFoundError: The following packages are not available from current channels:

  - spyder‑kernels=0

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
```

I cannot find "Reset to Defaults" in "Preferences".  Which tab is it in, @rweigel ?

**Comment by kuttamuwa** [comment]
Use Anaconda GUI to install spyder for your env via selecting your env in "Applications on"

**Comment by JoseCuervo92008** [comment]
Hello, 

In my case I got the "No spyder-kernels found" in Ipython console as well, even though my python path was setup correctly and the spyder_kernels folder was there. My version was 1.0 and updating my spyder-kernels from 1.0 to 2.0 solved it. To upgrade:

->Open cmd (in windows)
py
import pip
pip.main(['install','--upgrade','spyder-kernels']) 

Make sure cmd (or powershell) opens the python path you want to use!

**Comment by jithendrabsy** [comment]
I want change the python interpreter to the new conda environment and then spyder is showing up this error! If I change it back to default then it is fine!

"Your Python environment or installation doesn't have the spyder‑kernels module or the right version of it installed. Without this module is not possible for Spyder to create a console for you." I tried many things but still facing the issue.


Or is there another way to run the code in created environment instead of base?

**Comment by JoseCuervo92008** [comment]
Try to updgrade the module spyder-kernels to the latest version 
@jithendrabsy

**Comment by mxshen** [comment]
`pip install spyder-kernels==2.2` helps me solve this problem.

**Comment by sachinmathewjose** [comment]
I am getting the same issue as @jithendrabsy. It happens when I use kernel from the environment. 
i changed the python interpreter to the default and restarted the kernel. Then changed it back and restarted the kernel again. This made the kernel to use my environment. It works as long as I do not close the console. when i start a new console the same issue happens again. 
I am trying to use modular approach as mentioned here:
https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder#2-the-modular-approach


Another thing to note is that after i see the error message if I try to restart the kernel it shows: Cannot restart a kernel not started by Spyder.

**Comment by GBoulware** [comment]
I'm having the same issue as sachinmathewjose. I've installed the spyder kernel package 2.2.1 but I'm still getting the issues.  I can default to original settings in spyder.

I'm using the following versions:


* Spyder version: 5.2.2 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10
![spyder error](https://user-images.githubusercontent.com/65912665/154336963-5b91fe30-8671-4b61-9369-e3fc0e60b052.png)
