### ISSUE TITLE
error in pyqt5 and opencv2

### ISSUE THREAD

**Issue by cmyldz** [spyder-ide/spyder#5198]
![ekran alintisi](https://user-images.githubusercontent.com/31339561/30275858-83bd326a-970b-11e7-86ea-69ee49c51be6.PNG)
 def convert_answer(self):
      
         cap = cv2.VideoCapture('C:\\Users\\cem\\Pictures\\Camera Roll\\WIN_20160317_205235.mp4')
         framerate = cap.get(cv2.cv.CV_CAP_PROP_FPS)
         framecount = 0

         while(True):

                success, image = cap.read()
                framecount += 1
 # Check if this is the frame closest to 10 seconds
                if framecount == framerate * 10 :
                   framecount = 0
                   cv2.imshow('image',image)

    
                if cv2.waitKey(1) & 0xFF == ord('q'):
                   break

         cap.release()
         cv2.destroyAllWindows()

**Comment by ccordoba12** [comment]
It seems your the line that's giving you the error needs to be

    framerate = cap.get(cv2.CV_CAP_PROP_FPS)

But I don't know for sure because I haven't used OpenCV before.

However, this is not a Spyder bug, it seems to be a bug in your code, so I'm closing this issue.
