### ISSUE TITLE
Adding, removing, or moving a breakpoint while debugging changes the focus

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5201]
## Description

**What steps will reproduce the problem?**

1. Debug
2. Press return in the text editor
3. Watch as the focus goes back to ipython

## Version and main components

* Spyder Version: 3.2.4.dev0 474e59379
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
I can't reproduce this on Linux. Maybe it's an issue with Qt.

**Comment by impact27** [comment]
I found out why this is caused: if you add (or remove) a line to a file with a breakpoint, that causes this breakpoint to change line.
And when you add/remove/modify breakpoints, it jumps to the current debug line.
