### ISSUE TITLE
In ipdb, the up and down keys have a strange behaviour

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5202]
## Description

**What steps will reproduce the problem?**

1. debug
2. press up to access the last thing you typed
3. wonder why you ended up in the middle of the history log

## Version and main components

* Spyder Version: 3.2.4.dev0 474e59379
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Yep, I noticed this behavior too. I don't know why it happens though.

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.

**Comment by impact27** [comment]
Apparently the problem is that the cursor doesn't go all the way down when pressing enter. It just goes down one line.
