### ISSUE TITLE
Improvement: add a shortcut to enter the debugger after an error occurs

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5205]
Quite often, when I run a script that crashes, I launch the debugger with:
```
import pdb
pdb.pm()
```
It would be useful if there was a keyboard shortcut and a menu item to do that.

Also when the post mortem is launched, the corresponding file is not automatically opened, so I usually do a `u` then `d` and the correct line appears.

**Comment by ccordoba12** [comment]
There's already a menu item to enter post mortem debugging in

    Run > Configuration per file > General settings > Directly enter debugging when errors appear

I think that covers this use case, right?

**Comment by impact27** [comment]
Well not exactly as I don't want to enter debugging every time. I was thinking of something like: "debbug last error in console" if I can't figure out what the error is about just by looking at the trace.

**Comment by ccordoba12** [comment]
I see. You can also enter debugging after an error occurs by using the `%debug` magic. Is that closer to what you want?

**Comment by impact27** [comment]
Yes, but that is not very different from typing `pdb.pm()`. I just thought it would be cool to have a keyboard shortcut for this. The rationale behind a menu item would be that a new user may not know about the magic commands but this is a cool feature to use. 
For comparison, there is a button and a shortcut to stop debugging when typing `q` does the same thing. Why not add a button for "Debug last error"?

**Comment by ccordoba12** [comment]
It's not a bad idea, and it shouldn't be that hard to implement. The only thing that is not quite clear to me is what icon to use for this in the Debug toolbar.

You're welcome to give it a try!

**Comment by impact27** [comment]
![backtoerror](https://user-images.githubusercontent.com/6740194/30441001-0446b512-9970-11e7-9e29-ffd8cc510421.png)

**Comment by ccordoba12** [comment]
@goanpeca is working on a new icon set for Spyder 4, so we should wait until he replaces our current set for the new one before taking a look at this functionality.
