### ISSUE TITLE
Error when drag and drop file from zip

### ISSUE THREAD

**Issue by toonarmycaptain** [spyder-ide/spyder#5218]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**
Tried to drag and drop file into Spyder. Gave me error and took me here. 

**Please provide any additional information below**

  File "C:\Users\david.antonini\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2171, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by goanpeca** [comment]
>Tried to drag and drop file into Spyder. Gave me error and took me here.

@toonarmycaptain what type of file ?

**Comment by toonarmycaptain** [comment]
It was a .py
I figured afterwards that it was probably since it was housed within a zip file at the time, when unzipped it worked fine.
________________________________

**Comment by toonarmycaptain** [comment]
I'd add that, particularly since other software will work with this (ie I can drag and drop files from zip archives into Word or Paint etc and they open), such functionality would be useful, as users could reasonably expect it to work. Even if the file opened as a 'new' script, rather than a saved/named one.

**Comment by ccordoba12** [comment]
This was working before. We'll fix it in a future release.

**Comment by ccordoba12** [comment]
@dalthviz, I think this only happens on Windows.

**Comment by jnsebgosselin** [comment]
@ccordoba12 and @dalthviz I can reproduce it on master in Python 3.6.2 64bits, Qt 5.9.2, PyQt5 5.9.1 on Windows 7
