### ISSUE TITLE
Error when trying to sort dataframe with duplicate columns

### ISSUE THREAD

**Issue by Jerry-kiwi** [spyder-ide/spyder#5225]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 562, in sortByColumn
    if not self.model().sort(index, sort_order):
  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 312, in sort
    kind='mergesort')
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 3196, in sort_values
    str(by))
ValueError: Cannot sort by duplicate column cv1

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.3
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Please post the code you used to generate the Dataframe you were trying to sort.

**Comment by Jerry-kiwi** [comment]
Sorry.
I've made dtaframe with 2 identical columns. and when i tried to sort it in variable preview - error occured.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this in a future release.

**Comment by Prikers** [comment]
pandas does not allow to sort `DataFrame` on a duplicate column:
```python
In[10]: df
Out[10]: 
   A  A
0  1  1
1  2  2
2  3  3

In[11]: df.sort_values(by='A')
Out[11]: Traceback (most recent call last):
  File "<ipython-input-9-4119ec283a31>", line 1, in <module>
    df.sort_values(by='A')
  File "C:\...\site-packages\pandas\core\frame.py", line 3294, in sort_values
    str(by))

ValueError: Cannot sort by duplicate column A
```
@ccordoba12 how are such things handled in spyder? Should the error be catched and then the sorting is not performed? Or should a specific error message be displayed to the user?

**Comment by ccordoba12** [comment]
@Prikers, I think we should display a message for this because users don't know that Pandas can't perform this operation.

**Comment by ccordoba12** [comment]
@Prikers, do you want to work on this one?

**Comment by Prikers** [comment]
Yes I will!
