### ISSUE TITLE
Clearing IPython console does not actually clear the console

### ISSUE THREAD

**Issue by GalacticStarfish** [spyder-ide/spyder#5227]
## Clearing IPython console does not actually clear the console

**What steps will reproduce the problem?**

1.  Run Sypder 3.1.4
2. on IPython console run `%clear` or right-click on IPython console then left-click "Clear console" 
3. scroll-up, old output is still visible.

If a user clears the IPython console, it does not actually clear, it only scrolls down. This is a problem when testing programs which execute even a moderate number of print statements. Sometimes I want to scroll up to the top of the output, but I can't tell where the top of the output from the more recent runs and where output from a previous run ends. Scrolling down to "clear" the console is not all that helpful.

* Spyder Version: 3.1.4
* Python Version: 3.6.1 64 bit
* Qt Version:  5.6.2
* PyQt Version:  5.6 on Windows
* Operating system: Windows 7 Ultimate 64-bit Service Pack 1

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
This error was fixed in qtconsole 4.3.1, so please open a system terminal (cmd.exe) and run

    conda update qtconsole

then restart Spyder to get the fix for this problem. Thanks!

**Comment by VrunBert** [comment]
### %clear does not seem work at all for a  brand new Anaconda3 -5.0.1 install 


Spyder 3.2.4
Python 3.6.3
IPython 6.1.0
OS: Windows 7 Enterprise 6.1.7601 Service pack 1, x64 bit


jedi 0.10.2
matplotlib 2.1.0
nbconvert 5.3.1
numpy 1.13.3
pandas 0.20.3
pep8 1.7.0
pyflakes 1.6.0
pygments 2.2.0
pylint 1.7.4
qtconsole 4.3.1
rope 0.10.5
sphinx 1.6.3
sympy 1.1.1
