### ISSUE TITLE
How do I suppress "Code analysis: undefined name '_'" warnings?

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#5228]
## Description of your problem

**What steps will reproduce the problem?**

1. Install gettext on an application wide base ([Localizing your application](https://docs.python.org/3/library/gettext.html#localizing-your-application)).
2. Use `_('...')` deliberately in your code.
3. The editor flags up each occurrence of `_('...')` as "**Code analysis**: *undefined name '_'*".

**What is the expected output? What do you see instead?**

It would be great, if these `_('...')` were not flagged up as errors.

**Please provide any additional information below**

Is there any `# pylint: disable=...` directive available to suppress these warnings? I searched the net but came up clear.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.5.2 64bit
* Qt Version: 5.5.1
* PyQt Version: 5.5.1
* Operating system: Linux Mint 18.2 Sonya

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> Is there any # pylint: disable=... directive available to suppress these warnings?

There probably is one, but we don't know about it.

To avoid this error you need to import `_` from somewhere. That's what we do in Spyder:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/plugins/ipythonconsole.py#L45

----

I'm closing this one because it's not a Spyder error, just a question, and we don't know the answer to it, sorry.
