### ISSUE TITLE
I connot update spyder

### ISSUE THREAD

**Issue by TheNightBlades** [spyder-ide/spyder#5231]
I might just be stupid , but I cannot find where I input the command to update spyder

* Spyder Version: 3.2.2
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

**Comment by rlaverde** [comment]
https://github.com/spyder-ide/spyder/releases/tag/v3.2.3

**Comment by ccordoba12** [comment]
There are the commands, and you need to run them inside a system terminal (i.e. cmd.exe).

**Comment by ccordoba12** [comment]
Feel free to post more comments here, in case you have additional questions :-)

**Comment by TheNightBlades** [comment]
I knew the commands but could not figure out where since I would use the python console in spyder to update

**Comment by dalthviz** [comment]
Hi @TheNightBlades it seems that you don't have registered your Anaconda installation in your `PATH`. You can set  your Anaconda installation in your `PATH` or you can use the Anaconda Prompt or Anaconda Navigator (they should be in your start menu) to update and manage your packages.

**Comment by TheNightBlades** [comment]
Thank you very much it worked.
