### ISSUE TITLE
Saved variables cannot be opened

### ISSUE THREAD

**Issue by skyrip94** [spyder-ide/spyder#5235]
## Description of your problem
Can't open saved variables, it seems my variables  corrupted or has problem
**What steps will reproduce the problem?**

1.  Run Code and save variables in 'variable explorer'
2.  Close Spyder IDE
3.  Open Spyder and 'Import data' from save variables.

**What is the expected output? What do you see instead?**
Normally variables shows up and I still can see variables file with size of 600 mb 

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.1
* Qt Version:
* PyQt Version:
* Operating system: WIndows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a known problem and we plan to make this functionality more robust in Spyder 4.

Right now, not all variable types can be saved and restored, and that's probably what's happening in your case.

Sorry for inconvenience, but there's nothing we can do about it for now.

**Comment by skyrip94** [comment]
DO you have any temporary solution? Thanks

**Comment by ccordoba12** [comment]
Take a look at the dill library to save and restore variables.

That's what we plan to use in Spyder 4.
