### ISSUE TITLE
Doesn't able to import .ipynb file.

### ISSUE THREAD

**Issue by samkj** [spyder-ide/spyder#5237]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/samir/anaconda2/lib/python2.7/site-packages/qtconsole/manager.py", line 26, in poll
    def poll(self):
KeyboardInterrupt

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.3.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2+0.g825876c.dirty (OK)
numpy >=1.7       :  1.11.2 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.0.1 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Please explain in more detail what you were doing when this error appeared.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
