### ISSUE TITLE
Can't map keyboard shortcut to ALT + ~ (tilde) key

### ISSUE THREAD

**Issue by katakagi** [spyder-ide/spyder#5238]
## Description of your problem
I am not able to map the shortcut "run selection" to ALT + ~.  The shortcut window indicates "Invalid key entered".  Is it not possible to map a shortcut to the tilde key?  It isn't used in any other shortcut.

**What steps will reproduce the problem?**

1. Tools -> Preferences -> Keyboard shortcuts
2. Attempt to map "run selection" to ALT + ~. 

**What is the expected output? What do you see instead?**
The following statement to appears: "Invalid key entered".

**Please provide any additional information below**
None.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> Is it not possible to map a shortcut to the tilde key?

Sorry, it's not possible because on international keyboards you need to press several key to get `~`.
