### ISSUE TITLE
Code completion tooltip stops at first ')' in a string argument.

### ISSUE THREAD

**Issue by jaxankey** [spyder-ide/spyder#5241]
## Description

**What steps will reproduce the problem?**

1. define this function:
```python
def f(a='b)', c=3): return
```
2. At the terminal, type 
```python
In []: f(
```

**What is the expected output? What do you see instead?**
The code completion tool tip will contain only `f(a='b)`, skipping the remainder of the arguments.

**Please provide any additional information below**
Cross-platform, cross-python versions.

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by goanpeca** [comment]
This seems no longer relevant with Spyder 4
