### ISSUE TITLE
Run file problem for Spyder 3.2.3

### ISSUE THREAD

**Issue by cmbowyer13** [spyder-ide/spyder#5248]
## Description of your problem
Traceback (most recent call last):

  File "<ipython-input-1-f59cb2b0fa53>", line 1, in <module>
    runfile('/Users/calebbowyer/Documents/Python/HW3_py3.py', wdir='/Users/calebbowyer/Documents/Python')

NameError: name 'runfile' is not defined
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by cmbowyer13** [comment]
I'll just downgrade to a previous version that worked in the meantime.

**Comment by ccordoba12** [comment]
Closing because you're providing very little info.
