### ISSUE TITLE
Mouse gives focus point above selected point

### ISSUE THREAD

**Issue by ceaza** [spyder-ide/spyder#5251]
If I click on point the app give focus on the line above

![image](https://user-images.githubusercontent.com/9589657/30509720-607600b6-9ab7-11e7-804b-6007103de4aa.png)

In the image above, selecting line "import pandas" visually will select the line 7 above.

1. Spyder 3.2.3 Winpython 3.6.2
2. High definition display
3. Problem becomes worse when accessing through remote desktop

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6
* Qt Version: 5
* PyQt Version: 5.9
* Operating system: win10

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Did you adjust your resolution using

    Preferences > General > Screen resolution

?

**Comment by ceaza** [comment]
yes I did, 

Using a different remote desktop client (not Microsoft) and problem goes away.

**Comment by ccordoba12** [comment]
Good to know! Should we close this one? I don't think we could do anything about it.
