### ISSUE TITLE
Variable explorer crash when viewing numpy structured array

### ISSUE THREAD

**Issue by HassanNaseri** [spyder-ide/spyder#5254]
The following code creates the object `test_array` , and double-click on it in variable explorer results in error and immediate crash.

```
import numpy as np
test_array  = np.empty(2,dtype=[('X', 'f8', (2,10)), ('S', 'S10')])
```

I cannot capture the error message and there is no crash log file.

* Spyder Version: 3.1.4
* Python Version: 2.7.10 Anaconda
* Operating system: MacOS Sierra
* QT Version: 7.7.3
* PYQTVersion: 5.6.0

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a serious bug indeed!

We'll fix it in Spyder 3.2.4
