### ISSUE TITLE
Spyder doesn't start on Windows 7 within a Virtual Machine (Oracle VirtualBox)

### ISSUE THREAD

**Issue by hirschbeutel** [spyder-ide/spyder#5264]
## Description of your problem
Spyder doesn't start on Windows 7 within a Virtual Machine (Oracle VirtualBox)

**What steps will reproduce the problem?**

1. Install WinPython 64bit 3.5.4.0Qt5
2. Start Spyder.exe

**What is the expected output? What do you see instead?**

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	pythonw.exe
  Anwendungsversion:	3.5.4150.1013
  Anwendungszeitstempel:	59891fd9
  Fehlermodulname:	Qt5WebEngineCore.dll
  Fehlermodulversion:	5.9.1.0
  Fehlermodulzeitstempel:	5953dcc8
  Ausnahmecode:	80000003
  Ausnahmeoffset:	000000000015203e
  Betriebsystemversion:	6.1.7601.2.1.0.768.3
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	16c1
  Zusatzinformation 2:	16c1a9094c08c9aedef94a6cafd1950b
  Zusatzinformation 3:	7343
  Zusatzinformation 4:	7343477b71c328bd09e7e7ae392ee8a4

## Versions and main components

* Spyder Version: 3
* Python Version: 3.5
* Qt Version: Qt5
* PyQt Version: PyQt5
* Operating system: Windows 7 Home Premium

**Comment by ccordoba12** [comment]
This is a bug in Virtualbox, nothing we can do about it.

Please use Anaconda instead, which doesn't have this error.
