### ISSUE TITLE
editor: line 1706: list index out of range

### ISSUE THREAD

**Issue by Airhard** [spyder-ide/spyder#5267]
## Description

**What steps will reproduce the problem?**

1. open files in spyder
2. move files outside of spyder
3. choose close file in spyder

**What is the expected output? What do you see instead?**
i expected the file in the editor to close.
i see that spyder raise an error saying list index out of range

**Please provide any additional information below**

  File "C:\Users\main.user\Anaconda\lib\site-packages\spyder\widgets\editor.py", line 1706, in current_changed
    self.current_file_changed.emit(self.data[index].filename,
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by rlaverde** [comment]
This is a duplicated of #5157 fixed in 3.2.3. Please update spyder.
