### ISSUE TITLE
Enter in IPython console inserts new line when big Dataframes are in namespace

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#5280]
@Khris777 said in https://github.com/spyder-ide/spyder/issues/2696#issuecomment-330441511

@ccordoba12 

Try this example, it reproduces the problem for me:

	import pandas as pd
	import numpy as np
	nrow = 1000000
	ncol = 50
	test = np.ones((nrow,ncol),dtype=object)
	df = pd.DataFrame(test)

Then enter commands like these into the console:

	df.head()
	df[df[1] == 1]
	df[(df[1] == 1)&(df[4] == 1)]

You should pretty soon encounter a case when pressing enter will bring up another line and seemingly not executing the command.

The behaviour is erratic though, sometimes a command works, then it won't.

Adding the commands into a file and pressing F9 for that line always works, and sometimes after doing so entering a command manually will work again as well.

EDIT: It seems like `dtype=object` is a significant factor here. Using the same array with `dtype=int` makes it work well and to encounter some problematic behaviour (still way less than with dtype object) I need to set `nrow = 10000000`. But since I'm working with arrays/dataframes that have mostly strings in them (internally dtype object), the example case is fitting.

**Comment by ccordoba12** [comment]
@Khris777, besides my fix in PR #5298, you also need to go to

    Preferences > IPython console > Display > Interface

and deactivate the option called

    Display ballon tips

Those two things completely fix the error in my side.

**Comment by Khris777** [comment]
Disabling balloon tips already helped a lot, I'm not getting the issue with my example anymore.

Thanks a lot for both fixes.

**Comment by ccordoba12** [comment]
You're welcome!

Problem was the kernel was busy trying to display the ballon tip while you hit Enter to evaluate `df.head()`, for example. And that was the cause for a new line, instead of a direct evaluation of your expression.

**Comment by andreidi** [comment]
Here the problem persists after disabling balloon tip...
Only getting rid of Numpy options configurations (such as below) helps...
`np.set_printoptions(edgeitems=200, linewidth = 200)`
The code uses tensorflow, keras, matplotlib and other usual suspects...
So, if anyone has a idea I would be grateful...

**Comment by ccordoba12** [comment]
@andreidi, thanks for letting us know about it. What those options do?

**Comment by andreidi** [comment]
@ccordoba12 , Hi, well formatting of numpy displayed arrays  (such as how many items left/right for row vectors, how many chars until breaks line)

**Comment by jpalma-espinosa** [comment]
Hello!. I came to reopen this issue (sorry :C)

**Installed packages** 
```
javier@Neurolobo:~$ pip3 list
Package                  Version
------------------------ ----------
alabaster                0.7.12
appnope                  0.1.0
astroid                  2.0.4
Babel                    2.6.0
backcall                 0.1.0
bleach                   3.0.2
certifi                  2018.10.15
chardet                  3.0.4
cloudpickle              0.6.1
cycler                   0.10.0
decorator                4.3.0
defusedxml               0.5.0
docutils                 0.14
entrypoints              0.2.3
idna                     2.7
imagesize                1.1.0
ipykernel                5.1.0
ipython                  7.1.1
ipython-genutils         0.2.0
ipywidgets               7.4.2
isort                    4.3.4
jedi                     0.13.1
Jinja2                   2.10
jsonschema               2.6.0
jupyter                  1.0.0
jupyter-client           5.2.3
jupyter-console          6.0.0
jupyter-core             4.4.0
keyring                  16.1.0
kiwisolver               1.0.1
lazy-object-proxy        1.3.1
MarkupSafe               1.1.0
matplotlib               3.0.2
mccabe                   0.6.1
mistune                  0.8.4
nbconvert                5.4.0
nbformat                 4.4.0
notebook                 5.7.2
numexpr                  2.6.9
numpy                    1.15.4
numpydoc                 0.8.0
opencv-python            3.4.4.19
packaging                18.0
pandas                   0.23.4
pandocfilters            1.4.2
parso                    0.3.1
patsy                    0.5.1
pexpect                  4.6.0
pickleshare              0.7.5
pip                      18.1
prometheus-client        0.4.2
prompt-toolkit           2.0.7
psutil                   5.4.8
ptyprocess               0.6.0
pycodestyle              2.4.0
pyflakes                 2.0.0
Pygments                 2.2.0
pylint                   2.1.1
pyparsing                2.3.0
PyQt5                    5.9.2
python-dateutil          2.7.5
pytz                     2018.7
pyzmq                    17.1.2
QtAwesome                0.5.3
qtconsole                4.4.3
QtPy                     1.5.2
requests                 2.20.1
rope                     0.11.0
scikit-learn             0.20.0
scipy                    1.1.0
seaborn                  0.9.0
Send2Trash               1.5.0
setuptools               40.6.3
sip                      4.19.8
six                      1.11.0
snowballstemmer          1.2.1
Sphinx                   1.8.2
sphinxcontrib-websupport 1.1.0
spyder                   3.3.1
spyder-kernels           0.2.6
statsmodels              0.9.0
tables                   3.4.4
terminado                0.8.1
testpath                 0.4.2
tornado                  5.1.1
tqdm                     4.29.1
traitlets                4.3.2
urllib3                  1.24.1
virtualenv               16.2.0
wcwidth                  0.1.7
webencodings             0.5.1
wheel                    0.32.3
widgetsnbextension       3.4.2
wrapt                    1.10.11

```

**Python version**
```
Python 3.7.1 (default, Nov  6 2018, 18:46:03)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**The steps that took me to the error:**
1. $ spyder3 &

When in spyder, in the IPython terminal:
```
import numpy as np

import pandas as pd

a




```
As a result of that, the IPython freezes, but Spyder doesn't.

I tried the previous fix by disabling the balloon tip with no luck.  

**Hardware**
macOS Mojave 10.14.2
MacBook pro mid 2012.

If you need more information, please let me know
