### ISSUE TITLE
Issue with the GUI

### ISSUE THREAD

**Issue by hansamars** [spyder-ide/spyder#5281]
## Description of your problem

**What steps will reproduce the problem?**

1. Install Python 3.5.4
2. Install Spyder 3 using pip
3. Error

**What is the expected output? What do you see instead?**
This is what I see when I maximize the window
https://drive.google.com/file/d/0B9CX9MQRBm6vaGpKZkxyQ0Y3S0U/view?usp=sharing
**Please provide any additional information below**
This is running on a laptop. The scaling on it is set to 100%

## Versions and main components

* Spyder Version:3.2.3
* Python Version:3.5.4
* Qt Version:
* PyQt Version:5.9
* Operating system:WIn 10

## Dependencies

IPython >=4.0    :  6.2.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
This is a known problem on Windows 10. Sorry, but we don't know how to fix it.

**Comment by ccordoba12** [comment]
Maybe you should try to use Anaconda and see if the problem is present there or not.

**Comment by hansamars** [comment]
@ccordoba12  Anaconda fixes it

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
