### ISSUE TITLE
Need help to add the spyder icon to Spyder3.app on MacOS

### ISSUE THREAD

**Issue by sebma** [spyder-ide/spyder#5288]
## Description of your problem

Hi, this is not an issue.

I have the following applescript : 
```
$ cat Spyder3.applescript
on run
 do shell script "/usr/local/miniconda3/bin/spyder3"
end run
```
And I have created a `/Applications/Spyder3.app` this way : 
`$  osacompile -o /Applications/Spyder3.app Spyder3.applescript`

In `Finder`, I right click on `/Applications/Spyder3.app` and select `Get Info`
and here I am kind of stuck because I don't where to find the spyder3 icon to drag and drop it over the default icon.

Can you please tell me where I can find the spyder3 icon ?

**Comment by ccordoba12** [comment]
This is the icon you need to use for your app

https://github.com/spyder-ide/spyder/blob/master/img_src/spyder.icns

I'm closing this because (as you said) it's not really a bug, but feel free to keep commenting on it if you have more doubts.

**Comment by sebma** [comment]
Must I `cp` it into `/Applications/Spyder3.app/Contents/Resources/applet.icns` ?

**Comment by ccordoba12** [comment]
I think, but I'm not really sure, sorry. It's been a long time since I created an App.

You can take a look at the structure of our old app for guidance:

https://bitbucket.org/spyder-ide/spyderlib/downloads/spyder-3.0.2-py3.5.dmg
