### ISSUE TITLE
Running Sci Kit learn 

### ISSUE THREAD

**Issue by mccurcio** [spyder-ide/spyder#5292]
## Description

**What steps will reproduce the problem?**

1. just run
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

This is a brand new installation of Anaconda Python 3.6 with the Upgrade of Spyder On Linux Mint 18.2(?) 32 bit.
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2391, in run_file
    self.re_run_file()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2411, in re_run_file
    self.save_all()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/spyder/plugins/editor.py", line 1999, in save_all
    self.get_current_editorstack().save_all()
  File "/home/mcc/anaconda3/lib/python3.6/site-packages/spyder/widgets/editor.py", line 1644, in save_all
    if self.data[index].editor.document().isModified():
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
This error is going to be fixed in 3.2.4. Thanks for your patience.
