### ISSUE TITLE
Crash while opening Anaconda

### ISSUE THREAD

**Issue by DanielIAvila** [spyder-ide/spyder#5293]
## Description

**What steps will reproduce the problem?**

1. Open Anaconda x64 bits
2.  Launch environment for Python 2.7
3. Crash

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  elif res.tzname and res.tzname in time.tzname:

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.3.0 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
What's the complete message of the crash?

**Comment by DanielIAvila** [comment]
There was not message, it just crashed. I was asked to put the comment at  github, but now that I think about it I have been having problems with my environment (P2.7). I cannot see the variable explorer, in comparison to the root environment.

**Comment by ccordoba12** [comment]
Sorry, this looks like an installation problem, so there's nothing we can do about it.
