### ISSUE TITLE
pyximport.install() in sitecustomize.py is not a good idea

### ISSUE THREAD

**Issue by mahyarkoy** [spyder-ide/spyder#5299]
## Description of your problem
pyximport.install() in utils/site/sitecustomize.py causes errors when importing.

**What steps will reproduce the problem?**

1. Have two files example.so and example.pyx in the same location
2. Try import example
3. Import will throw error, because pyximport is hooked

**What is the expected output? What do you see instead?**
Instead of importing example.so, it throws "Error compiling Cython file"

**Please provide any additional information below**
In general, it is misleading to have the pyximport hooked to import

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 2.7.12
* Qt Version: 5
* PyQt Version: 5
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0;<6.0:  5.5.0 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.1 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
psutil >=0.3      :  5.3.1 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
How do you propose we fix this?

**Comment by ccordoba12** [comment]
Note to self: take a look at

https://stackoverflow.com/questions/46422488/get-rid-of-pyximport
