### ISSUE TITLE
Embedded editor pops up even if there is one in a seperate window

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#530]
_From [gestat...@gmail.com](https://code.google.com/u/114884686971745659534/) on 2011-01-18T06:37:40Z_

What steps will reproduce the problem?

 1. click the option button of the embedded editor
2. click the option 'new window'
3. close the embedded editor in the original window
4. double click a python file in the file explorer What is the expected output? What do you see instead? * i expected the file to open in the new editor window, what it did
 * additionally the embedded editor popped up again in the main window and showed the same file
 * i expected the editor in the new window to completely replace the embedded editor. What version of the product are you using? On what operating system? * Spyder 2.0.6
 * Python 2.6.5
 * Qt 4.6.2
 * PyQt 4.7.2
 * Linux 2.6.32 x86_64

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=530_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:26:40Z_

**Labels:** Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [gestat...@gmail.com](https://code.google.com/u/114884686971745659534/) on 2012-02-16T01:04:17Z_

I'm using a dual display environment with the main window containing most stuff on the left and a separate editor window on the right screen. Given the little interest in this issue I guess this usecase is quite rare.

Could someone look into this issue? This is really annoying. And I'm pretty sure there is no usecase where someone really needs the editor in both windows.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T06:56:53Z_

This issue was updated by revision 07b664ca9c05 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-11T06:57:14Z_

This issue was updated by revision 7a2085609f1b .

**Comment by spyder-issues-migrator** [comment]
_From [gestat...@gmail.com](https://code.google.com/u/114884686971745659534/) on 2012-03-12T04:51:03Z_

You rock!

**Comment by mattare2** [comment]
I have this issue too, unfortunately.

Python 3.4
Spyder 2.3.8
Win7
