### ISSUE TITLE
Jedi 0.11.0 now with numpydoc support!

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#5302]
It's finally in there and just in time for a new release.

https://github.com/davidhalter/jedi/blob/master/CHANGELOG.rst

I think adding an exception for patching Jedi 0.11.0 would be a good idea since the code in 0.11.0 is nicer than the patch.

I guess the patches could also be removed but this could be seen as a regression.

**Comment by ccordoba12** [comment]
The exception is already in place, you cautiously added it :-)

https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/introspection/jedi_patch.py#L26

**Comment by ccordoba12** [comment]
Sorry, it was me ;-p

https://github.com/spyder-ide/spyder/blame/3.x/spyder/utils/introspection/jedi_patch.py#L26

**Comment by bcolsen** [comment]
I didn't think i was that cautious ;-)  Well that's great it's ready to go then!

**Comment by ccordoba12** [comment]
Well, not really. We were using a deprecated method that is now gone in Jedi 0.11. But I fixed that already and 3.2.4 will be compatible with 0.11
