### ISSUE TITLE
Imported variable in variable explorer not working for script

### ISSUE THREAD

**Issue by hiteshnitetc** [spyder-ide/spyder#5303]
I imported a variable from my desktop to variable explorer of spyder. I want to use this variable in script. But when i use this, error occurs and saying undefined name. 
![screenshot from 2017-09-21 13-55-13](https://user-images.githubusercontent.com/30615882/30690287-30b1bbae-9eb3-11e7-8e3c-7a4e27088a27.png)

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This means that the variable is only defined in the console but that you don't have code to define it in the Editor.

It's just a warning, so you can ignore it. But, this error also means that you won't be able to run your file outside Spyder and without previously loading/defining that variable in the console.

**Comment by hiteshnitetc** [comment]
Thnx. You are correct it's just a warning
