### ISSUE TITLE
Paths in the "Search in" combobox of the "Find in File" plugin becomes corrupted

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#5306]
## Description of your problem

Related to PR #4822 that fixed Issues #4814 and #4809.

**What steps will reproduce the problem?**

1. I don't know... I'm sorry. I'll add more info in the future if I can. I'm using this feature a lot, so I'll keep my eyes opened!

**What is the expected output? What do you see instead?**

Sometimes, _Other directories_ in the  _Search in_ combobox of the _Find in File_ plugin becomes corrupted with no way of removing them. For instance, the `<PyQt5.QtWidgets.QListWidget...` shown in the screenshot below was actually `C:\Users\jsgosselin\spyder` before it became corrupted at some point.  This is the third time that this problem occurs for me. 

Besides, I think an option should be added below _Select other directory_ to clear the list.

![image](https://user-images.githubusercontent.com/10170372/30704150-ca6a9782-9ebf-11e7-9ac1-bc29d255b0c6.png)

**Please provide any additional information below**

## Versions and main components

* Spyder Version: branch 3.x and master
* Python Version: 3.6.2
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows 7 64 bits

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by jnsebgosselin** [comment]
Here is a traceback:

Traceback (most recent call last):
  File "C:\Users\jsgosselin\spyder\spyder\widgets\findinfiles.py", line 114, in run
    self.find_files_in_path(self.rootpath)
  File "C:\Users\jsgosselin\spyder\spyder\widgets\findinfiles.py", line 132, in find_files_in_path
    for path, dirs, files in os.walk(path):
  File "C:\Python36\lib\os.py", line 335, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by jnsebgosselin** [comment]
@andfoy Would you mind if I take a look at this? I would like to fix this bug for the next release.

**Comment by ccordoba12** [comment]
Jean, please go ahead and fix it :+1:

**Comment by jnsebgosselin** [comment]
@ccordoba12 In addition to solve this issue, I had some ideas to improve how the `Search in` QComboBox works. What do you think?

- [ ] When populating the `Search in` QComboBox, do not add the paths that do not exists anymore.
- [ ] When hovering over an item of the QComboBox and pressing <kbd>Del</kbd>, remove the item from the list.
- [ ] Add a  `Clear this list` option below `Select other directory`.

**Comment by jnsebgosselin** [comment]
```python
  File "C:\Users\jsgosselin\spyder\spyder\widgets\findinfiles.py", line 408, in path_selection_changed
    self.external_path = item.path
AttributeError: 'QListWidgetItem' object has no attribute 'path'
```

**Comment by ccordoba12** [comment]
Jean, I agree with all your suggestions.

**Comment by jnsebgosselin** [comment]
The traceback posted in https://github.com/spyder-ide/spyder/issues/5306#issuecomment-334021119 seems not to be related to the undesired behavior described in the OP.

```python
Traceback (most recent call last):
  File "C:\Users\jsgosselin\spyder\spyder\widgets\findinfiles.py", line 115, in run
    self.find_files_in_path(self.rootpath)
  File "C:\Users\jsgosselin\spyder\spyder\widgets\findinfiles.py", line 133, in find_files_in_path
    for path, dirs, files in os.walk(path):
  File "C:\Python36\lib\os.py", line 335, in walk
    top = fspath(top)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
To reproduce this error:
- Open a project in Spyder.
- Go in the `Find in Files` plugin and from the `Search in` combobox, select the `Project` option.
- Close the project.
- Start the search.

![fif_error1](https://user-images.githubusercontent.com/10170372/34446253-83263d82-eca7-11e7-9ffa-cd0d9c8d8094.gif)

**Comment by jnsebgosselin** [comment]
Here is another traceback similar, but not the same, as the one posted in https://github.com/spyder-ide/spyder/issues/5306#issuecomment-353457679. I'm not sure, however, that this is related to the undesired behavior described in the OP.

I am trying to create a reproducible example for the behavior described in the OP. So far, I have not been successful, but I'm documenting the other errors that I'm finding along the way.

```python
Traceback (most recent call last):
  File "C:\Users\jsgosselin\spyder\spyder\widgets\findinfiles.py", line 408, in path_selection_changed
    item = self.path_selection_contents.item(idx)
AttributeError: 'QListWidgetItem' object has no attribute 'path'
```

To reproduce this error:
- Select a path in the `Search in` combobox.
- Change the selection by rolling up the mouse wheel until the separator below the `Select other directory` is hit.

![fif_error2](https://user-images.githubusercontent.com/10170372/34446429-df6cbdc2-eca8-11e7-874a-2da364140ac4.gif)

**Comment by jnsebgosselin** [comment]
Ok, I found out how to reproduce the behaviour described in the OP 😂. This is happening when <kbd>Enter</kbd> is pressed when the focus is on the `Search in` combo-box and when an external path is selected.

The currently selected path is then moved at the beginning of the list, and an empty item is also added. This behaviour is explained by the `keyPressEvent` override in the [BaseComboBox](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/comboboxes.py#L31), from which the `Search in` combo-box is inheriting

Because of this, the wrong information is saved in the configuration file when the `FindinFiles` plugin is closed afterward.  In the [get_options](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L417) method, the external paths are retrieved from index 6 of the `Search in` combo-box (see [here](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L478)). Due to what was explained above, the content that is supposed to be in index 1 to 5 is pushed down in the list. So running `to_text_string` on items that are not an instance of [ExternalPathItem](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L206), such as a separator, returns a string of the object such as `<PyQt5.QtWidgets.QListWidget...` 

![fif_error3](https://user-images.githubusercontent.com/10170372/34448337-4d6ef040-ecba-11e7-87d1-4fff7916a948.gif)

**Comment by ccordoba12** [comment]
Great! So PR coming?

**Comment by jnsebgosselin** [comment]
@ccordoba12 Do I fix the 3 issues I've found while investigating this (see https://github.com/spyder-ide/spyder/issues/5306#issuecomment-354492631, https://github.com/spyder-ide/spyder/issues/5306#issuecomment-354493874, and https://github.com/spyder-ide/spyder/issues/5306#issuecomment-354506402) and do I implement the 4 proposed enhancements (see https://github.com/spyder-ide/spyder/issues/5306#issuecomment-352950794) in the same PR or do I split this in smaller, individual PR?

**Comment by ccordoba12** [comment]
Everything in one PR seems easier to me because all fixes/improvements are related.

**Comment by jnsebgosselin** [comment]
@ccordoba12 Alright thank you. The PR is on the way :)

**Comment by ccordoba12** [comment]
Ok, moving this one to 3.2.6 then :-)
