### ISSUE TITLE
Spyder crashed at start up, not starting even after --reset

### ISSUE THREAD

**Issue by thebigcath** [spyder-ide/spyder#5312]
## Description of your problem
I started Spyder from python(x,y) console. It crashed and won't open again. I tried "spyder --reset" in the command prompt but it had no effect.

**What steps will reproduce the problem?**

1. Start python(x,y)
2. Start spyder
3. 

**What is the expected output? What do you see instead?**
Start spyder, instead I get a pop up that tels me Spyder crashed last session and to try the --reset command before posting here.

**Please provide any additional information below**
Any helped welcomed! Thanks!

## Versions and main components

* Spyder Version:2
* Python Version:2.7.10.0
* Qt Version:
* PyQt Version:
* Operating system: windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Sorry, PythonXY is usually outdated and not so well maintained anymore, so we don't support it.
