### ISSUE TITLE
Not all lists are supported by the variable explorer

### ISSUE THREAD

**Issue by Prikers** [spyder-ide/spyder#5313]
**What steps will reproduce the problem?**

1. Create two lists `a = [len, 1]` and `b = [1, len]` 
2. Check the variable explorer
3. `a` is not supported while `b` is

**What is the expected output? What do you see instead?**
Both `a` and `b` are lists. They should be both supported.

**Comment by Prikers** [comment]
This is caused by the [`is_supported`](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/variableexplorer/utils.py#L511) functions. By default it checks the first item of iterables and if the first item is not supported (like `len`) the whole `list` is considered as not supported.

**Comment by ccordoba12** [comment]
@Prikers, do you want to work on this one?

**Comment by Prikers** [comment]
Yes I will. I just need input from you to know where we want to go with this one. So far we have this behavior:
```python
def is_supported(value, check_all=False, filters=None, iterate=True):
    """Return True if the value is supported, False otherwise"""
    (...) # omitted from brevity
    elif iterate:
        if isinstance(value, (list, tuple, set)):
            valid_count = 0
            for val in value:
                if is_supported(val, filters=filters, iterate=check_all):
                    valid_count += 1
                if not check_all:
                    break
            return valid_count > 0
    (...) # omitted from brevity
```
- Do we want to display all lists even if they contain one non-supported object anywhere? (:+1:)
- Or the opposite?

**Comment by jitseniesen** [comment]
What does supported mean in this context? I know unsupported objects are not displayed in the variable explorer by default, but is that all?

My first thought is: we display all lists (even if they contain only non-supported objects). I think this minimizes confusion.

Things to keep in mind:
* Very long lists should not lead to unresponsive GUI
* Lists containing itself should not cause problems
* I believe dicts and lists are not handled consistently at the moment

**Comment by Prikers** [comment]
> What does supported mean in this context? I know unsupported objects are not displayed in the variable explorer by default, but is that all?

Yes that's it. By turning on the option to display unsupported object the list `[len, 1]` would appear

**Comment by ccordoba12** [comment]
> Do we want to display all lists even if they contain one non-supported object anywhere?

I think this is the best option @Prikers.
