### ISSUE TITLE
IndexError when trying to open a variable in the Variable Explorer

### ISSUE THREAD

**Issue by zaher88abd** [spyder-ide/spyder#5322]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Zaher\Anaconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 607, in setModelData
    self.get_value(index),
  File "C:\Users\Zaher\Anaconda2\envs\tensorflow\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1364, in get_value
    name = index.model().keys[index.row()]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.11.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
How this did exactly happen to you? Please provide a detailed description.

**Comment by zaher88abd** [comment]
I just try to see one of the variables data like open one of the variables from the variables explorer, and it has a lot of data but I don't think that is a the problem.

**Comment by ccordoba12** [comment]
Ok, thanks for your answer. Could you post a screenshot of how the Variable Explorer looks when you see this error? Thanks!

**Comment by zaher88abd** [comment]
I am sorry I don't have it.

**Comment by ccordoba12** [comment]
When this error appears again, please try to upload the screenshot here.

**Comment by ccordoba12** [comment]
@zaher88abd posted this image on issue #5334 

![image](https://user-images.githubusercontent.com/11011876/30868644-9825d83c-a2b5-11e7-8ce2-ba2986082b46.png)

**Comment by ccordoba12** [comment]
@zaher88abd, could you post the code you're running in the console? I mean, the file `sol1.py`?

I still don't understand the source of this error, sorry, but thanks a lot for your help.

**Comment by Prikers** [comment]
@ccordoba12 should we close this one? I do not see the error on the screenshot.

**Comment by ccordoba12** [comment]
Sure, closing because of lack of response.
