### ISSUE TITLE
Ctrl+K does not kill to line end

### ISSUE THREAD

**Issue by Heliosmaster** [spyder-ide/spyder#5323]
## Description of your problem

**What steps will reproduce the problem?**

1. Verify in the keyboard shortcuts that "Ctrl-K" is the keybinding for "kill to line end"
2. Press it while editing (with no text selected)
3. Verify that does nothing

**What is the expected output? What do you see instead?**
It should kill it, consistently with the behavior indicated in the docs and consistently with the behavior of Ctrl-U

**Please provide any additional information below**
Changing the settings to another keybinding, like Ctrl-O, works. Setting it to Ctrl-K does not.
This is a fresh install using Anaconda.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.1 64bits
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Mac OS X 10.11.6 El Capitan 

## Dependencies
```
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by Heliosmaster** [comment]
It seems this is happening only on OSX so it must be conflicting with some global shortcut (Ctrl+K has a similar behavior already in OSX).
I installed Linux using a VM and could not reproduce the bug, there C-K works as expected.

**Comment by jnsebgosselin** [comment]
Same in Windows 7. Setting `kill to line end` to <kbd>ctrl</kbd> + <kbd>K</kbd> works as expected.

**Comment by jnsebgosselin** [comment]
@ccordoba12 I cannot confirm this because I do not have access to a Mac, but PR #7954 should have taken care of this issue, in theory.

**Comment by ccordoba12** [comment]
Ok, let's close it then.
