### ISSUE TITLE
Improve debug logging

### ISSUE THREAD

**Issue by rlaverde** [spyder-ide/spyder#5326]
Improve logging could help with better error reporting #5247, and won't be too hard to implement. (also will help a lot when debugging spyder)

At the moment the only way to debug/log information in spyder is `debug_print`, and using DEBUG variable

I think we could move to use `logging` library, It'll allow us to configure levels, handlers, filters, and support scenarios like:

- Debug specific plugins: something like: spyder --debug=editor could be achieved using filters

Related to #5247
- Append last 5 debug loggings to an error report
- Log all errors to a log file that could be requested when reporting an error
- Even we could attach a socket handler to a webservice and report errors in the background.

cc @goanpeca @ccordoba12

**Comment by ccordoba12** [comment]
I like it, but let's leave it for beta2.
