### ISSUE TITLE
Crash when launching Spyder

### ISSUE THREAD

**Issue by SibasishTripathyy** [spyder-ide/spyder#5339]
## Description of your problem

**What steps will reproduce the problem?**

1. Installed anaconda python 64-bit as admin to all users.
2. Launched spyder using cmd as admin.
3. Crashes

**What is the expected output? What do you see instead?**
Trying to launch Spyder.
Crashes and says "Windows will notify if a solution is available"

**Please provide any additional information below**
Followed all the instructions on #3042 but still can't solve it.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please open a system terminal (cmd.exe), run there

    spyder --show-console

and post the message (if any) shown there in a comment below.

**Comment by SibasishTripathyy** [comment]
Nope, i didn't get any additional message other than "Python has stopped working". Although, i got a one liner i.e,
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)

The screenshot of the same has been uploaded to this link:- https://prnt.sc/gq7srg

Check it out.

**Comment by ccordoba12** [comment]
This is probably a problem with your firewall/antivirus not allowing socket connections in your machine.

Sorry, but that's not a problem in Spyder itself, so we can't help you to solve it.
