### ISSUE TITLE
"Go to definition" not working

### ISSUE THREAD

**Issue by charleslian** [spyder-ide/spyder#5347]
## Description of your problem

**What steps will reproduce the problem?**

1.  pip install -U spyder 
2.  spyder, Ctrl + left

**What is the expected output? What do you see instead?**

Go to the definition.  No action.

**Please provide any additional information below**

Apt install Spyder 2 works well.

## Versions and main components

* Spyder Version: 3.+
* Python Version: 2.7
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

## Dependencies

IPython 5.4.1(OK)
jedi   0.11.0(OK)
matplotlib  2.0.2 (OK)
pandas  0.20.1 (OK)
pep8  1.7.0 (OK)
psutil   5.3.1 (OK)
pyflakes   1.6.0 (OK)
pygments   2.2.0 (OK)
pylint   1.7.2 (OK)
qtconsole 4.3.1 (OK)
rope  0.10.7 (OK)
sphinx    1.6.4 (OK)
sympy  1.0 (OK)
zmq   16.0.2 (OK)

**Comment by ccordoba12** [comment]
Please downgrade to Jedi 0.10.2. Jedi 0.11 is not supported yet, but it will be in our next release (3.2.4), soon to be ready.
