### ISSUE TITLE
Keep cursor focus in editor after running script

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#5348]
## Description of your problem

**What steps will reproduce the problem?**

1. Just write some Python codes and save them as a script 
2. Hit F5 to run it
3. Observe where the focus is after successfully running the script

**What is the expected output? What do you see instead?**

I would like to see the cursor focus remaining in the editor, not jumping to the iPython console.

**Please provide any additional information below**

None

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 2.7
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10

## Dependencies

Not really. This is just a generic problem.

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
It's not possible to get that behavior right now, sorry.

**Comment by ccordoba12** [comment]
You're welcome to send us a pull request to provide this feature.
