### ISSUE TITLE
Button for close all plots/images

### ISSUE THREAD

**Issue by geekonloose** [spyder-ide/spyder#5350]
## Description of your problem
I am using spyder for scientific simulation. As a result I need to plot many data at the end of the simulations. 

Can you provide an option or shortcut to close all the figures. It would be easy to close 10-15 figure at one shot.

**Comment by ccordoba12** [comment]
To close all figures you need to run

```python
import matplotlib.pyplot as plt
plt.close('all')
```

You can also get this behavior if you execute your code in a dedicated console. You can do that by giving focus to the file you want to run in the Editor, then going to the menu

    Run > Configuration per file

and activating the option called

    Execute in a dedicated console

**Comment by geekonloose** [comment]
Ok. Thank you.

**Comment by chriuxenman1** [comment]
I tried this solution you metioned ccordoba12, but this is just a workaround in my opinion. Isn't there a function built in as in MATLAB "clear all", which deletes every figure at the beginning of the code execution?
