### ISSUE TITLE
IPYTHON darks scheme  has output also in black characters

### ISSUE THREAD

**Issue by geekonloose** [spyder-ide/spyder#5351]
## Description of your problem

**What steps will reproduce the problem?**

1. Make IPYTHON window to dark mode
2. Type any 4+4
3. The output will also be in black font, which is unreadable

**What is the expected output? What do you see instead?**
The darks scheme should have characters in contrast like in white.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a know bug if you're using the Sympy integration, and there's nothing we can do about it for now, sorry.

**Comment by geekonloose** [comment]
Thank you..!! Disabled sympy. DArk Theme I am coming :)
