### ISSUE TITLE
Ctrl+T only works inside running console

### ISSUE THREAD

**Issue by HenkHcks** [spyder-ide/spyder#5352]
## Description of your problem
The use case of quickly opening a new console for the current script, by pressing Ctrl+T, and then F5 to run, is suggested to be possible by the Consoles->"Open an IPython console Ctrl+T" menu entry. This however doesn't work. Also quickly opening multiple consoles by pressing Ctrl+T multiple times, is blocked since the shortcut key doesn't work when the console isn't started yet.

**What steps will reproduce the problem?**

1.  Focus the editor
2.  Press Ctrl+T

or 
1. Focus the console
2. Press Ctrl+T
3. A new console will load, showing "connecting to kernel..."
4. While this message is shown, press Ctrl+T

**What is the expected output? What do you see instead?**
An additional console should be opened.

**Please provide any additional information below**

## Versions and main components
* Spyder Version: 3.2.3 
* Python Version: 3.6.2 
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 
## Dependencies     
pyflakes > 0.6.0 : 1.6.0  OK  
pycodestyle > 2.3: 2.3.1  OK  
pygments > 2.0 : 2.2.0  OK  
pandas > 0.13.1 : 0.20.3  OK  
numpy > 1.7 : 1.13.1  OK  
sphinx > 0.6.6 : 1.6.3  OK  
rope > 0.9.4 : 0.9.4-1  OK  
jedi > 0.9.0 : 0.10.2  OK  
nbconvert > 4.0 : 5.2.1  OK  
sympy > 0.7.3 : 1.1.1  OK 
cython > 0.21 : 0.26  OK 
qtconsole > 4.2.0: 4.3.1  OK 
IPython > 4.0 : 6.1.0  OK  
pylint > 0.25 : 1.7.2  OK

**Comment by ccordoba12** [comment]
`Ctrl+T` doesn't work when the Editor is focused, and we don't plan to change that, sorry. You need to give to the console to make it work, as you said.

It's also true that `Ctrl+T` doesn't work when a console hasn't started yet. That's a minor bug, and something we don't have time to fix right now, sorry.

You're welcome to send us a pull request to fix it.

**Comment by HenkHcks** [comment]
Is there an underlying reason for not wanting `Ctrl+T` to be a global shortcut, like `F5` for run? Will you accept a pull request for this?

**Comment by ccordoba12** [comment]
Because it can easily conflict with the shortcuts defined in another plugin. Because of we prefer to limit as much as we can our number of global shortcuts.

**Comment by ccordoba12** [comment]
We don't plan to implement this, sorry.
