### ISSUE TITLE
Spyder fails to open a new IPython console

### ISSUE THREAD

**Issue by nchouika** [spyder-ide/spyder#5353]
## Description

**What steps will reproduce the problem?**

1. Open a new IPython console.
2. 
3. 

**What is the expected output? What do you see instead?**

Spyder doesn't manage to open the console. Error dialog.
Afterwards, Spyder at startup is not able to open the first IPython console either. The error dialog opens at startup.

**Please provide any additional information below**

  File "/usr/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 974, in create_new_client
    self.connect_client_to_kernel(client)
  File "/usr/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 995, in connect_client_to_kernel
    stderr_file)
  File "/usr/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 1383, in create_kernel_manager_and_kernel_client
    stderr = codecs.open(stderr_file, 'w', encoding='utf-8')
  File "/usr/lib/python3.6/codecs.py", line 895, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] Aucun fichier ou dossier de ce type: '/tmp/spyder-nchouika/kernel-8f3ba0aad080.stderr'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
This was fixed in Spyder 3.2.3. Please update to that version.
