### ISSUE TITLE
Don't get list of class members and methods for object

### ISSUE THREAD

**Issue by jsobotkaXsFK** [spyder-ide/spyder#5354]
## Description

I recently downloaded Spyder from Anaconda b/c I would like to use some of the new features in Pandas. Previously, I've been using a version of Spyder from several versions ago (2.2.5). The old version had nice feature that let me figure out what members and methods belonged to an object. Basically, after I defined an object (like a numpy array) and put a "." after the object, a little window would appear that would show the list of members and methods that belonged to the object. I'm not seeing this feature in the new version of Spyder and it's really killing my productivity. 

**What steps will reproduce the problem?**

1. import numpy as np
2. x = np.array([1,2])
3. x.

**What is the expected output? What do you see instead?**

I expect to see a list of available methods for the object x in the editor and in the python terminal. In the older version of Spyder, I see a scroll-able dropdown that has:

all
any
argmax
argmin
...

I'm not seeing anything in the new version of python.

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by jsobotkaXsFK** [comment]
Ok. Scratch that. The information is showing up in the editor. It's not showing up in the console.

Here's a more relevant example:

import openpyxl
pathToExcel = 'myDirectory/myFile.xlsx'
wb = openpyxl.load_workbook(pathToExcel, data_only=True)
es = wb.get_sheet_by_name(excelSheet)
es.

And I see nothing after the '.', which should have methods like rows, etc...

**Comment by ccordoba12** [comment]
You need to press the `Tab` key to get completions in the console. Unfortunately we can't provide automatic completions in the console for now, sorry.
