### ISSUE TITLE
Don't set current working directory for external kernels

### ISSUE THREAD

**Issue by fayeshine** [spyder-ide/spyder#5360]
current working directory is binded with both ipython console directory and the editor file directory, which is not suitable for remote kernel.
I use a remote kernel (by redirect the port to a external server), and the file directory is totally different for ipython console and my local file directory.
Can we separate these two directory as before or at least add an option to separate them?

**Comment by ccordoba12** [comment]
We totally missed this use case. We'll fix it in 3.2.5.

**Comment by ccordoba12** [comment]
@rlaverde, please work on this one.
