### ISSUE TITLE
Sorting by column in variable explorer

### ISSUE THREAD

**Issue by lifescholar** [spyder-ide/spyder#5361]
## Description

**What steps will reproduce the problem?**

1.  Double click on a pandas Series variable in Variable Explorer
2.  Clicked on the column heading for the Series data in the worksheet containing the Series values, to sort it
3.  Results (repeatedly) in error below

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\Users\803375527\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 562, in sortByColumn
    if not self.model().sort(index, sort_order):
  File "D:\Users\803375527\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 312, in sort
    kind='mergesort')
  File "D:\Users\803375527\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\frame.py", line 3201, in sort_values
    na_position=na_position)
  File "D:\Users\803375527\AppData\Local\Continuum\Anaconda3\lib\site-packages\pandas\core\sorting.py", line 247, in nargsort
    indexer = non_nan_idx[non_nans.argsort(kind=kind)]
SystemError: <method-wrapper '__gt__' of CategoricalDtype object at 0x000001A5AF1A0B70> returned a result with an error set

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3

**Comment by Prikers** [comment]
Thanks @lifescholar. Do you have a simple example to reproduce this issue?

**Comment by lifescholar** [comment]
Sure. Looks like a problem with categorical data types. The following code results in this error when you click on the column heading for the series in the variable explorer.

`import pandas as pd

df = pd.DataFrame({'A': [1, 2, 3, 4],
                   'B': ['a', 'b', 'c', 'd']})
df = df.astype(dtype={'B': 'category'})
df_cols = df.dtypes`

**Comment by Prikers** [comment]
Thanks @lifescholar. I will investigate this issue.

**Comment by ccordoba12** [comment]
Thanks @Prikers for looking into it!

Just one word of advice about our milestones: if an issue is tagged with a `3.2.x` milestone, that means that a PR to fix it needs to be created against our `3.x` branch. Else, they need to go against master.

You most probably noticed that, but I wanted to clarify it for you ;-)

**Comment by lifescholar** [comment]
Just to clarify, the error occurs when inspecting df_cols, not df, in my code example.

**Comment by Prikers** [comment]
@lifescholar This seems to be an error in pandas. Probably related to [this issue](https://github.com/pandas-dev/pandas/issues/14368). 
@ccordoba12 should we add an error message as we did in #5327? It is a `SystemError` and seems to be a very specific error.
@ccordoba12 yes I noticed about the branches 😄. For my defense the only time I mixed-up the branches, there was no label on the issue 😇

**Comment by ccordoba12** [comment]
> should we add an error message as we did in #5327?

Yes, please.

> For my defense the only time I mixed-up the branches, there was no label on the issue

Don't worry about it, my comment was just to let things crystal clear for you ;-)
