### ISSUE TITLE
Add "Save all files with <eol> EOL characters" option

### ISSUE THREAD

**Issue by dougthor42** [spyder-ide/spyder#5365]
There should be an option on the editor to always save files with LF / CRLF / CR line endings.

Basically this would run `Source -> Convert end-of-line characters` on every save. There might be a more sophisticated or faster way to do it, but I'm not aware of one.

Option screen could look like:

![image](https://user-images.githubusercontent.com/5386897/31038405-8a57582a-a52b-11e7-9a60-ea9f71922feb.png)

I'll open a PR for this to see how you guys like it. Defaults will be the status-quo: EOLs are not changed on save.

(Edit1: replaced text representation of option screen with image)

**Comment by ccordoba12** [comment]
I like it. Thanks a lot @dougthor42 for taking a look at it!
