### ISSUE TITLE
Can't open anything besides prompt

### ISSUE THREAD

**Issue by JumBe08** [spyder-ide/spyder#5370]
## Description of your problem
Anaconda 5.0.0 - Only the prompt shows in the start menu
Previous versions - Can't run anything besides the prompt

**What steps will reproduce the problem?**
Only thing i did was install and uninstall different versions of conda, none of them worked. I had installed one a year ago, which worked at the time. I also installed python independently from anaconda. I unninstalled one version which stubbornly remains in the start menu and i can't remove.

**Please provide any additional information below**
My problem is similar to the one here:
https://github.com/ContinuumIO/anaconda-issues/issues/264

I used spyder --reset, which gave:
![1](https://user-images.githubusercontent.com/32424209/31050639-3a1322ae-a648-11e7-9351-c51f9809cbc6.png)

Then I used conda install spyder-app, and the result:
![2](https://user-images.githubusercontent.com/32424209/31050686-5a95a8ce-a64a-11e7-9b04-5a6fac5349c9.png)

On that previous issue, one of the users fixed the problem by removing an apostrophe in his name, but mine as none.

Any tips?

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:

Dont know how to check this, since i cant open anything, but right now i used the anaconda 4.2.0 installer

* Operating system: win 10, 64 bits

## Dependencies

Don't know how to check these..

Thanks in advance

**Comment by ccordoba12** [comment]
Please uninstall Anaconda completely and reinstall it again.

**Comment by JumBe08** [comment]
Did it with different versions of Anaconda, with no result. I think there might be something left up in the registry or somewhere else that is messing thigns up. Will try to format the entire thing and reinstall, just to make sure.

**Comment by JumBe08** [comment]
Worked fine after formatting the pc!
