### ISSUE TITLE
Add Clear button to (find) entry boxes

### ISSUE THREAD

**Issue by sphh** [spyder-ide/spyder#5373]
## Description of your problem

Recently I searched for a lot of strings – one after the other. They all came from an electronic document, so I could use copy'n'paste. Since I work on Linux, I just selected the search strings by double clicking it and wanted to paste them with a middle click into the find box. But the box was still populated with the search string from the previous search. This string had to be deleted first. Selecting it and middle click obviously does not work, so had to click into the entry box, switch to the keyboard (CTRL-A, DEL) and paste again with the mouse.

It would have been so much quicker if there were a "Clear search box" button as you can now see nearly everywhere.

Could you please provide such a button in every search box (I can come up with four: The _Editor_ has Find, Find + Replace, the _Find in files_ has one, _Help_ another, but there might be more.) Maybe other entry boxes can also gain from a Clear button?

## Versions and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2 64bits
* Qt Version: 5.5.1
* PyQt Version: 5.5.1
* Operating system: Linux Mint 18.1

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
It's a nice suggestion. Thanks for bringing it up to our attention.

We'll try to implement it in our 3.2.5 version. @andfoy, please work on this one.

**Comment by sphh** [comment]
Great. Thanks! I even added those two lines to my existing 3.2.4 installation, because I cannot wait :-)
