### ISSUE TITLE
Connect to an existing kernel empty tab «Variable explorer»

### ISSUE THREAD

**Issue by nnnet** [spyder-ide/spyder#5378]
Now the window is always empty after connecting to the existing kernel and performing the calculation operations.
How can I see the values of variables after connecting to an existing kernel?

## Versions and main components

* Spyder Version: Spyder 4.0.0.dev0 (Commit: 0608076) 
* Python Version: 2,7
* Qt Version: 4.8.7
* PyQt Version: PyQt4 (API v2) 4.11.4
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
numpy >=1.7       :  1.13.0 (OK)
pandas >=0.13.1   :  0.19.0 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.6.4 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
rope >=0.9.4      :  0.10.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
sympy >=0.7.3     :  1.0 (OK)

**Comment by ccordoba12** [comment]
It is not possible to show variables for external kernels right now. We're working to provide this functionality in Spyder 4.
