### ISSUE TITLE
### gives code analysis error

### ISSUE THREAD

**Issue by geekonloose** [spyder-ide/spyder#5381]
## Description of your problem

**What steps will reproduce the problem?**

1. ### is one of particular comment, which will also be displayed  in outline
2. But, in code analysis, it shows as error (E266)

**What is the expected output? What do you see instead?**
The code analysis should not show error for "###"

**Comment by ccordoba12** [comment]
Please post a screenshot to see how the error is shown up in your screen.

**Comment by geekonloose** [comment]
![image](https://user-images.githubusercontent.com/30520900/31140790-24bfc7b6-a893-11e7-8265-446b12ac2fc8.png)

Check on line 8, it shows code style error. While it is part of outline tree also.

**Comment by ccordoba12** [comment]
Sorry, we can't control this because we use a third-party package to provide our real-time code analysis facilities.

**Comment by rlaverde** [comment]
This error is raised for pycodestyle, see http://pycodestyle.pycqa.org/en/latest/intro.html#error-codes

You  could deactivate it in the pycodestyle configurations, although #2359 need to be fixed first 😕
