### ISSUE TITLE
spyder error

### ISSUE THREAD

**Issue by bhmit** [spyder-ide/spyder#5382]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/anaconda/lib/python3.6/site-packages/spyder_terminal/terminalplugin.py", line 165, in __wait_server_to_start
    self.create_new_term(give_focus=False)
  File "/anaconda/lib/python3.6/site-packages/spyder_terminal/terminalplugin.py", line 315, in create_new_term
    font=font.family())
  File "/anaconda/lib/python3.6/site-packages/spyder_terminal/widgets/terminalgui.py", line 63, in __init__
    self.view = TermView(self, term_url=url, handler=self.handler)
  File "/anaconda/lib/python3.6/site-packages/spyder_terminal/widgets/terminalgui.py", line 147, in __init__
    self.document.profile().clearHttpCache()
AttributeError: 'QWebEngineProfile' object has no attribute 'clearHttpCache'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-terminal #114](https://github.com/spyder-ide/spyder-terminal/issues/114) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ccordoba12** [comment]
@bhmit, this is an error in `spyder-terminal`, so I moved this issue to its repository.

**Comment by bhmit** [comment]
*        I install a Spyder Plugin for displaying a virtual terminal
called *Spyder-terminal <https://github.com/spyder-ide/spyder-terminal> so
when I run the Spyder IDE the error message emerged, and the visual
Terminal appear in the editor, but it's blocked
