### ISSUE TITLE
Spyder Kernal deadhalt and error

### ISSUE THREAD

**Issue by WuyangFF95** [spyder-ide/spyder#5383]
## Description

**What steps will reproduce the problem?**

This error occurs in the Spyder embedded in the WinPython 3.6.2.
1. After initiating Spyder 3.6.2, the Spyder 3.6.2 will get into a "no response" state, the editor cannot show up.
2. Closing one of the "pythonw.exe" with least RAM occupation will recover the program.
3. After recovery, the editor shows up with "temp.py", and then this error is raised.

**What is the expected output? What do you see instead?**
![1](https://user-images.githubusercontent.com/32476254/31130614-74cb031e-a88a-11e7-87ae-f6b8f5ab84a8.png)
![2](https://user-images.githubusercontent.com/32476254/31130620-76800b78-a88a-11e7-878c-99e3c00a2db1.png)

**Please provide any additional information below**

  File "C:\Program Files\WinPython\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder_terminal\terminalplugin.py", line 156, in __wait_server_to_start
    QMessageBox.Ok)
TypeError: 'Icon' object is not callable

## Version and main components

* Spyder Version: 3.2.1.dev0 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
That is an error in `spyder-terminal` and it was fixed in its latest version. Please update it with

    pip install -U spyder-terminal

**Comment by WuyangFF95** [comment]
Many Thanks!
