### ISSUE TITLE
Spyder frequently crashing on MacBook Pro with Touch Bar

### ISSUE THREAD

**Issue by dscience7** [spyder-ide/spyder#5395]
## Description
I have a late 2016 MacBook Pro and Spyder frequently crashes. I get the following error message in terminal after it has crashed. It has happened when I'm running both Python2.7 or Python 3. I thought the problem had gone away when I migrated to Python 3 but has now reappeared.

I didn't have this problem on a MacBook Air running Python 2.7.

Messages in the Terminal below:

/Users/karim/miniconda2/envs/riskpy36/bin/pythonw: line 3:  2901 Segmentation fault: 11  /Users/karim/miniconda2/envs/riskpy36/python.app/Contents/MacOS/python "$@"

**What steps will reproduce the problem?**
No particular steps, I have found no pattern in the crashes.

**What is the expected output? What do you see instead?**
Continued operation of Spyder.

**Please provide any additional information below**
Thanks for all your work, despite the crashes Spyder is a great tool. Let me know if you need any further information.

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by dscience7** [comment]
It appears to be related to launching of iPython consoles within Spyder. On starting Spyder, in the Terminal I get the following:

`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

When I launch more iPython consoles, I get a few more of these error messages. When the same error appears 11 times, Spyder crashes and I get the following:

`[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
/Users/karim/miniconda2/envs/riskpy36/bin/pythonw: line 3:  4622 Segmentation fault: 11  /Users/karim/miniconda2/envs/riskpy36/python.app/Contents/MacOS/python "$@"
(riskpy36) AKs-MacBook-Pro:Model Karim$ [1004/160259:ERROR:mach_broker_mac.mm(52)] bootstrap_look_up: Unknown service name (1102)
[1004/160259:ERROR:browser_io_surface_manager_mac.cc(47)] bootstrap_look_up: Unknown service name (1102)
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

**Comment by ccordoba12** [comment]
Thanks for reporting. This could be fixed when Anacoda updates Qt, the graphical toolkit used by Spyder.

Unfortunately, in the mean time we can only recommend you to run

    spyder --reset

in a terminal and try again.

**Comment by dscience7** [comment]
Hi Carlos,

Thanks for responding. If I installed Python directly and then Spyder (i.e. not use Anaconda) would this issue go away?

**Comment by ccordoba12** [comment]
Probably. Please try it and let us know if that fixes the problem for you.

You could use Homebrew to do it.

**Comment by ccordoba12** [comment]
@dscience7, we're tracking this problem in

https://github.com/ContinuumIO/anaconda-issues/issues/6554

Anaconda Inc. is in the process of updating Qt, and that should fix this problem.
