### ISSUE TITLE
Error, to start Spyder

### ISSUE THREAD

**Issue by haolle** [spyder-ide/spyder#5397]
## Description
Error message:
    Render Report Error
    [WinError 2] The system cannot find the file specified

**What steps will reproduce the problem?**

1. Every time I start Spyder, this dialogue comes up.
2. Even I reset the Spyder to factory defaults, it still comes up.
3. 

**What is the expected output? What do you see instead?**
I didn't configure Spyder for special function or use specific file.
Everything is default.

**Please provide any additional information below**
Where can I find the Spyder error log?
Any log file?

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by dalthviz** [comment]
Hi @haolle could you try to run in cmd `spyder --show-console` and see if something appears?

**Comment by haolle** [comment]
Unfortunately, it is same result with following command in the Python/scripts folder:
Spyder3  -- show-console 

Thanks 

Hal

**Comment by dalthviz** [comment]
And when running the command in the `cmd` it remains open or it closes? (try without the space between `--` and `show-console`). Also, you could try to find a `spyder_crash.log` file (if it exists, it should be in your user directory, probably something like`C:\Users\<your user>\spyder_crash.log` )

**Comment by ccordoba12** [comment]
Closing because of lack of response.
