### ISSUE TITLE
Annoying spyder error

### ISSUE THREAD

**Issue by Justas27** [spyder-ide/spyder#5405]
Receiving annoying popup and that error windows start every time i start a program.

Also the meniu line File, Edit, and Search commands doesn't work if i press mouse on in. (It does work if i press other command first and then scroll to File etc, but to do that this little thing every single time is a bit ... :/ 

Was asked by program to submit it to github, the text below was computed manually by the program:

## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
    stderr=self.server_stderr)
    restore_signals, start_new_session)
    args = list2cmdline(args)
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'NoneType' is not iterable

## Version and main components

* Spyder Version: 3.2.1.dev0 
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by Jeroendevr** [comment]
You are using an old development version. If there is no specific reason for it you could do is update to the latest stable using pip (or use the latest 4.0 development version by cloning the current repo if you want that.)

If you do not use any distribution try `pip install --upgrade spyder` from the command line. It should update the Spyder version to 3.2.3

See [Spyder Official Docs](https://pythonhosted.org/spyder/installation.html)

**Comment by ccordoba12** [comment]
@Jeroendevr is right. Please update Spyder and also `spyder-notebook` to see if the error is fixed.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
