### ISSUE TITLE
pyqtgraph stopped working in Spyder

### ISSUE THREAD

**Issue by Dschoni** [spyder-ide/spyder#5409]
My pyqtgraph windows suddenly stopped working inside Spyder.

**What steps will reproduce the problem?**

Inside an ipython console in Spyder do
1. import numpy as np
2. import pyqtgraph as pg
3. pg.image(np.eye(3))

**What is the expected output? What do you see instead?**
The expected output is a new popup window, holding a pyqtgraph image set to the array.
Instead, a black window with a title bar is shown. When I close the window, an error message pops up, stating, that the:

"Application is not responding."

and giving me two options: Force Quit or Wait (gnome3 default probably).
When I force quit, the embedded Ipython Console gives me a

"Kernel died, restarting"

message.

**Please provide any additional information below**

To start spyder, I have to 

unset QT_API 

(which is otherwise set to pyqt and leads to the error "qtpy.PythonQtError: No Qt bindings could be found" when running spyder.)

## Versions and main components

Installed via Anaconda:

* Spyder Version:  3.2.3
* Python Version:  2.7.13
* Qt Version:         5.6.2
* PyQt Version:    5.6.0
* Operating system: Ubuntu 16.10

## Dependencies

IPython >=4.0;<6.0:  5.3.0 (OK)
cython >=0.21     :  0.26 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by Jeroendevr** [comment]
This has to do with #4349. Within Qt you can only have one instance of QApplication. But Spyder is already a QApplication so this can interfere. You could add some code to check if there is already a QApplication running with the help of: 
`def run():
    if not QApplication.instance():
        app = QApplication(sys.argv)
    else:
        app = QApplication.instance() 
    app.exec_()  `

or depending on how you set up your program you could also add it in your __init__ method see [Comment on #4349](https://github.com/spyder-ide/spyder/issues/4349#issuecomment-293446015)

**Comment by Dschoni** [comment]
I am not sure if this really is true. Until this day everything worked fine and I don't see anything changed in my setup over the day. I am not running a QT application inside Spyder. I just merely execute the three given lines on a new started Spyder and it leads to this behaviour.

**Comment by Jeroendevr** [comment]
Now I understand what you mean. I did run it without Spyder and the same problem occurred.

**Comment by Dschoni** [comment]
If I run in it in a pure python shell outside Spyder, it works without problems.

**Comment by ccordoba12** [comment]
Please run this command after starting an IPython console

   %gui qt5

then run your code.

**Comment by Jeroendevr** [comment]
Can I ask what `%gui qt5 `does?

**Comment by ccordoba12** [comment]
Sure, it activates the Qt5 event loop, so that so you can run Qt apps in the IPython consoles without blocking it and making the apps fully interactive at the same time.

**Comment by Dschoni** [comment]
Works for me in an IPython shell. As the python shell is going to be abandonned in future Spyder releases (?) I consider this done.

**Comment by Dschoni** [comment]
@ccordoba12 right now, the error seems to be back in Spyder 4.0.1 

```
    import numpy as np
    import pyqtgraph as pg
    pg.image(np.eye(3))
```
leads to an unresponsive image widget. If `%gui qt5` is given, the content is shown and the image becomes responsive. Setting the graphics backend to `Automatic` does not solve the problem in this case.

spyder 4.0.1
pyqtgraph 0.10.0
pyqt 5.9.2
qt 5.9.7

fresh conda install.

**Comment by Dschoni** [comment]
Some more research: I could not reproduce this across systems (i.e. running the exact same conda environment on another laptop did not have this problem).  However, on the problematic system, the behaviour is consistent over different combinations of python + qt + pyqtgraph + spyder. So I assume, that my Spyder startup is somehow different than it was before. `spyder --reset` did not change anything.

Machine info:

Lenovo Thinkpad T495
Windows 10 Pro 1903

(The system, where everything runs as it should is a Thinkpad E480 with Windows 10 Pro 1909)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll improve how we handle PyQt apps in 4.0.2, so this could be solved in that version.

**Comment by Dschoni** [comment]
Again, it's not about an PyQt App, it seems to be a problem with the graphical backend not being loaded correctly inside Spyder, but if that's solved in 4.0.2 I'm happy ;)

**Comment by Dschoni** [comment]
I would also be happy on a hint on how to start the qt event loop automatically on each console start (i.e. without the need to type in %gui qt5) as a temporary workaround.

**Comment by Dschoni** [comment]
I installed matplotlib, switched off inline-plotting inside the plot-manager window and magically it started working again. Even if I switch back to the original settings, all plots are now working without the need to start the event loop.

**Comment by ccordoba12** [comment]
Good to know!
