### ISSUE TITLE
Object inspector (Cmd-I) and instant help (arguments) don't work in Editor, but work in Console

### ISSUE THREAD

**Issue by CoderCoderCoder** [spyder-ide/spyder#5415]
## Description

**What steps will reproduce the problem?**

1. Help function (e.g. after typing "print(") that shows the arguments doesn't work if typed in the Editor window, but it works fine in the Console window (shows all the arguments for "print" in this case)
2. Same to the help information if Cmd-I is pressed (on MacOS) - works fine in the Console, but not in the Editor

Please help to solve this issue as I have no idea what could be wrong there, thanks.

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by CoderCoderCoder** [comment]
Update: the only workaround and temporary solution I found is to downgrade Spyder to 3.1.3. Any newer version other than that results in the same misbehaviour. 
I am using Spyder installed through Anaconda Navigator.

**Comment by dalthviz** [comment]
Hi @CoderCoderCoder maybe #5393 is related with your issue?

**Comment by ccordoba12** [comment]
@CoderCoderCoder this is caused because Jedi **0.11** is not compatible with Spyder 3.2.3. This will be fixed in Spyder **3.2.4**.

**Comment by CoderCoderCoder** [comment]
Thanks for your reply, but interestingly this issue is not solved if Jedi 0.9.0 is installed. This is what I tried as well (same to Rope). I used for both the min requirements, and still any newer version than 3.1.3 showed the same misbehaviour. So truly hope all these issues will be solved in 3.2.4 regardless of the used Jedi + Rope versions.

**Comment by minzastro** [comment]
I experienced similar problem. Interestingly, changing **spyder/utils/help/conf.py** seems to solve the problem:
```
#html_use_smartypants = False  # I commented out this
smart_quotes=False  # and added that
```
I run on jedi 0.10.2, will test for jedi 0.11 later.

**Comment by koshyviv** [comment]
Having the same issue from the latest anaconda package
Anaconda Navigator = 1.8.7
Spyder = 3.2.6
Python = 3.6.4

Can someone help?
