### ISSUE TITLE
Cannot get past splash screen

### ISSUE THREAD

**Issue by mwhaap** [spyder-ide/spyder#5416]
## Description of your problem

**What steps will reproduce the problem?**

1. When starting Spyder the splash screen will pop up and make variable amounts of progress then close but the application itself doesn't open.

2. If I try to open Spyder again I get the "Spyder crashed during last session." popup warning.

3. I then reset to defaults by running Spyder with the command line option 'spyder --reset

4. Thee splash screen image pops up for a sec disappears and then nothing happens

5. I try to open Spyder again and end up at step 1 again.

**What is the expected output? What do you see instead?**
The expected outcome is for the main window to load instead I just get the splash screen to pop up for a minute. 

**Please provide any additional information below**

If i try running spyder again using the command prompt 'spyder --show-console'
I get the following error 
AttributeError: 'QHeaderView' object has no attribute 'setSectionsClickable'

I have tried restarting my desktop and I have tried uninstalling and reinstalling spydering using the anaconda prompt 'conda uinstall spyder' and 'conda install spyder' to no avail

The last time the main window was open it crashed with a kernel error in the console as soon as it opened

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 2.7.12
* Qt Version: 4.8.7
* PyQt Version: 4.11.4
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jnsebgosselin** [comment]
@mwhaap Thanks for the report.

@andfoy I think the error originates in the find in files module [here](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/findinfiles.py#L659). The [setClickable](http://doc.qt.io/qt-4.8/qheaderview.html#setClickable) method in `QHeaderView` has been replaced in Qt4 by [setSectionsClickable ](http://doc.qt.io/qt-5/qheaderview.html#setSectionsClickable) in Qt5.

**Comment by jnsebgosselin** [comment]
@mwhaap if you want to fix your issue right now and it is not possible for you to upgrade your pyqt version to pyqt5, try replacing `setSectionsClickable` by `setClickable` in the [findinfiles.py](https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/findinfiles.py#L659) in your local installation of spyder.

**Comment by jnsebgosselin** [comment]
Sorry for all that noise :slightly_frowning_face: , I've kind of understood too late this was more of a dependency issue that a bug.

**Comment by jnsebgosselin** [comment]
@ccordoba12 I think we need to increase the version of qtpy in the [requirements ](https://github.com/spyder-ide/spyder/blob/master/requirements/requirements.txt) from 1.1.0 to at least 1.2.0 where a [patch ](https://github.com/spyder-ide/qtpy/commit/3dc26fb587ecbe4c58bc4f18ae92cca6a1308db3#diff-8b21c2d41a8d046c3ad2e0f1e5061840) was introduced for the QHeaderView class in qtpy.

**Comment by mwhaap** [comment]
I tried switching from pyqt4 to pyqt5 and it fixed the problem,  however I need to use pyqt4 instead of 5 for  compatibility with libraries such as Traits UI.  Going back to Spyder version 3.1.0 and it worked so somthing thats been added to spyder since then is the source of the problem when running qt4

**Comment by ccordoba12** [comment]
@mwhaap, please update `qtpy` to fix this problem, as @jnsebgosselin suggested.

**Comment by mwhaap** [comment]
Ok thanks for the quick help

**Comment by jnsebgosselin** [comment]
>Going back to Spyder version 3.1.0 and it worked so somthing thats been added to spyder since then is the source of the problem when running qt4

@mwhaap You are right, this bug was introduced in version 3.2.0 with in this [commit](https://github.com/spyder-ide/spyder/commit/ce7b12b8119f43c0b448dbd8f67ea06a6e1bb61b#diff-8353c463a005ca100da0de607daf6428).

Updating your qtpy version to at least 1.2.0 should solve the issue.

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one. We need to update our `qtpy` requirement in setup.py, README, docs and our conda recipe.
