### ISSUE TITLE
Runfile error on Spyder

### ISSUE THREAD

**Issue by AlexDeSouza123** [spyder-ide/spyder#5418]
##Hi, Im new on spyder. I couldnt launch run button. When i click run button Python says ">>> runfile('C:/Users/Admin/.spyder2/temp.py', wdir='C:/Users/Admin/.spyder2')"
how I can fix the problem? pls help me , I gott study to my lesson

Spyder(Python 2.7.10)

**Comment by ccordoba12** [comment]
There's no problem. You simply need to add a `print` statement to your file if you want to see something printed in the console. For example

```python
a = 10
print(a)
```

**Comment by Manojkumar-code** [comment]
runfile('C:/Users/Admin/.spyder-py3/temp.py', wdir='C:/Users/Admin/.spyder-py3')

**Comment by ccordoba12** [comment]
Please read my answer above instead of opening new issues about it.
