### ISSUE TITLE
command to open files in spyder editor

### ISSUE THREAD

**Issue by mingguichen** [spyder-ide/spyder#5425]
Is there any function to open .py files in the spyder editor directly from the IPython command line within spyder IDE? I basically want something working like matlab 'open' command. thank you.

**Comment by Jeroendevr** [comment]
You mean opening and a possibility to edit te file, not running directly?

**Comment by ccordoba12** [comment]
Yes, you can use the `%edit` magic, like this

    %edit foo.py

However, I think it doesn't work on Windows right now (not exactly sure why...)

**Comment by mingguichen** [comment]
Could you please let me know which function is called when I double-click the file name inside spyder? Probably I could just directly use that command as well. thanks.

**Comment by ccordoba12** [comment]
We don't have a function for that but use QDesktopServices instead.

**Comment by RTMaloney** [comment]
> Yes, you can use the `%edit` magic, like this
> 
> ```
> %edit foo.py
> ```
> 
> However, I think it doesn't work on Windows right now (not exactly sure why...)

It worked perfectly for me on Windows :)

**Comment by ccordoba12** [comment]
Yep, we fixed that a long time ago.

**Comment by aabhijith185** [comment]
How to open txt files in spyder ide.when performing file operation its showing text file not found
