### ISSUE TITLE
Segmentation fault when trying to change keyboard shortcuts in Preferences

### ISSUE THREAD

**Issue by Griffintaur** [spyder-ide/spyder#5426]
## Description of your problem
There is a segmentation dump issue and spyder is getting crashed whenever I tried to change the default key combination for comment in Spyder. [Ubuntu]
**What steps will reproduce the problem?**
1. Launch and go to preferences
2. Click on the keyboard shortcuts and try to change it.
3. Segmentation dump issue in Ubuntu

**What is the expected output? What do you see instead?**
No crash. changes should be successful.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.2
* Qt Version:
* PyQt Version:
* Operating system: Ububtu

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
What are your Qt and PyQt versions?

**Comment by ccordoba12** [comment]
Also, please run in a terminal

    spyder --reset

and try again

**Comment by csabella** [comment]
I'm using Ubuntu 16.04 as well and I get the segmentation fault if I open any keyboard shortcut window, even if I click the Cancel button without making any changes.

**Comment by ccordoba12** [comment]
As I said before, what are your Qt and PyQt versions?

**Comment by csabella** [comment]
Sorry, I wasn't trying to report a bug, just trying to help provide debugging information.  But, here are my versions:
[Python 3.6.3 64bits, Qt 5.6.2, PyQt5 5.6 on Linux]

**Comment by ccordoba12** [comment]
Thanks @csabella!

**Comment by ccordoba12** [comment]
@csabella, is this still an issue for you?

**Comment by csabella** [comment]
@ccordoba12   It still happens on 3.x, but does not happen on master.

**Comment by ccordoba12** [comment]
I can't reproduce this in Kubuntu 17.04.

**Comment by csabella** [comment]
On the last update, I said it wasn't happening on master, but now it's happening on master for me, as well as 3.x and the release version of 3.2.5.

I open Preferences, then Keyboard Shortcuts, double click on 'Find Next/F3', press F4 for the new shortcut, and click OK.  It closes Spyder and gives a seg fault.  I looked at this a little bit when it was first reported, but I'm going to spend some more time on it now to try to track it down.

**Comment by ccordoba12** [comment]
Thanks Cheryl! I don't think this is going to be easy to fix...

**Comment by ValerioBiscione** [comment]
Had this with sypder 3.4, solved it with spyder 3.6. Try conda update spyder
