### ISSUE TITLE
Very long boot time on windows7, spyder 3.2.1.dev0, WinPythonQt5-64bit-3.6.2.0

### ISSUE THREAD

**Issue by xgnata** [spyder-ide/spyder#5429]
When I click on spyder to launch it, it takes about 15s to get the splash window 'spyder3' and 50s to get a fully stated spyder. The 50s are annoying but the 15s are even more confusing because one think that nothing has started. As a result, I have the tendency to double click again and I end up with 2 or 3 spyders launched after more than a minute.

spyder-reset does not help. Disabling "check for updates at startup" does not help.
It may be related to a proxy issue as I'm using a PC at work. However, unplugging the network cable does not help (but it may be due to the fact that some kind of a connection on localhost takes ages due to strange proxy settings. I have no access to these settings).

The slash window should appear within a second. No more. I would be happy to profile the spyder start to see what is going on but I'm not sure how to do it in my environment.

OS : windows 7
spyder 3.2.1.dev0 
and the list of packages installed is available here
https://github.com/winpython/winpython/blob/master/changelogs/WinPythonQt5-64bit-3.6.2.0.md

**Comment by ccordoba12** [comment]
> I would be happy to profile the spyder start

You can open `spyder/app/mainwindow.py` and start putting prints around to the see where the slowness comes from. That's what I would anyway.

**Comment by xgnata** [comment]
Ok I did it but I get this error. I don't even get how it can work 
(except if mainwindow.py is called from another larger try/except block)

runfile('C:/Users/gnata/Documents/WinPython-64bit-3.6.2.0Qt5/python-3.6.2.amd64/Lib/site-packages/spyder/app/mainwindow.py', 
wdir='C:/Users/gnata/Documents/WinPython-64bit-3.6.2.0Qt5/python-3.6.2.amd64/Lib/site-packages/spyder/app')
Traceback (most recent call last):

   File "<ipython-input-4-6a47ad3408b1>", line 1, in <module>
runfile('C:/Users/gnata/Documents/WinPython-64bit-3.6.2.0Qt5/python-3.6.2.amd64/Lib/site-packages/spyder/app/mainwindow.py', 
wdir='C:/Users/gnata/Documents/WinPython-64bit-3.6.2.0Qt5/python-3.6.2.amd64/Lib/site-packages/spyder/app')

   File 
"C:\Users\gnata\Documents\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder\utils\site\sitecustomize.py", 
line 688, in runfile
     execfile(filename, namespace)

   File 
"C:\Users\gnata\Documents\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\spyder\utils\site\sitecustomize.py", 
line 101, in execfile
     exec(compile(f.read(), filename, 'exec'), namespace)

   File 
"C:/Users/gnata/Documents/WinPython-64bit-3.6.2.0Qt5/python-3.6.2.amd64/Lib/site-packages/spyder/app/mainwindow.py", 
line 92, in <module>
     from qtpy import QtWebEngineWidgets  # analysis:ignore

   File 
"C:\Users\gnata\Documents\WinPython-64bit-3.6.2.0Qt5\python-3.6.2.amd64\lib\site-packages\qtpy\QtWebEngineWidgets.py", 
line 26, in <module>
     from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

**Comment by ccordoba12** [comment]
So the problem is that, for some strange reason, Spyder can't load `QtWebEngineWidgets`. This is a problem with WinPython, which uses `QtWebEngineWidgets` and not with Spyder, so please report this problem there:

https://github.com/winpython/winpython/

----

A quick solution is to use Anaconda instead of WinPython.

**Comment by xgnata** [comment]
I'm not sure we should close it.
I was trying to launch mainwindow.py from spyder itself.
The error I got  is related to stuff like "QtWebEngineWidgets must be imported before a QCoreApplication instance is created" when I try to "from PyQt5.QtWebEngineWidgets import QWebEnginePage" in a ipython console in spyder.
If I try to launch it from the jupyter qtconsole then spyder starts. It takes time as reported but it starts.
I will try to add a few print to see where the slowness is.

**Comment by xgnata** [comment]
it's wired...
When I type ../python-3.6.2.amd64/Lib/site-packages/spyder/app/mainwindow.py in Jupyter Qtconsole then spyder starts almost instantly as expected.
When I launch mainwindow.py from spyder I get the reported error.
And when I click on spyder.exe from winpython, spyder starts but it takes about a minutes.

What is spyder.exe doing??

**Comment by ccordoba12** [comment]
> What is spyder.exe doing??

It's generated automatically by setuptools, so I really don't know.

----

What if you create this Python script in the `Scripts` folder

```python
from spyder.app import start
start.main()
```

name it `start-spyder` and run it from a terminal?
