### ISSUE TITLE
enhancement - hard fork MS visual studio code to provide dominant ide for ML

### ISSUE THREAD

**Issue by johndpope** [spyder-ide/spyder#5432]
## Description of your problem
**What steps will reproduce the problem?**
1. n/a

https://github.com/Microsoft/PTVS/issues/747
https://github.com/agermanidis/livepython/issues/5
https://github.com/Microsoft/vscode/issues/29971 <- they won't support variables.

**Comment by ccordoba12** [comment]
in Microsoft/vscode#29971 you said

> Seems like a case where a hard fork of VS code for machine learning could make the most sense.
Unless the extensions could provide a richer ui.

But we can't simply fork VSCode and use it as the foundation for Spyder, sorry. Spyder uses a quite different technology from VSCode: it's built in Python using the Qt framework, while VSCode uses Typescript and (correct if I'm wrong) it's a webapp.

**Comment by rlaverde** [comment]
Well, as @ccordoba12 says a hard fork is not related to spyder, maybe you could search for other people interested in doing that.

Btw, in spyder we are  adding language server support #4751 that will allow to fully support more languages, also a lot improvements to be released in spyder4.

**Comment by johndpope** [comment]
Thanks for your reply @ccordoba12 - 

I draw your attention to this trending repo -> 
https://github.com/agermanidis/livepython

I believe @agermanidis - has added some hooks that bridge python <--> typescript 

https://github.com/agermanidis/livepython/blob/master/tracer.py
https://github.com/agermanidis/livepython/blob/master/bin/livepython

please consider. I'm sure with enough interest - there's a way. 
Consider that developers (>34,000) could rally to provide help here (you can achieve this elegantly / minimum effort + maximum results). 

<img width="986" alt="screen shot 2017-10-10 at 11 18 57 am" src="https://user-images.githubusercontent.com/289994/31394659-dae15b0e-adac-11e7-92c5-59ed717ac81e.png">

The language server support that @andfoy  has built is an awesome effort. kudos.
From my experience with swift + vscode plugins - (this can lead to competing repos / wasted efforts) It would be ideal to have an out of the box platform / or provide support behind best one.

**Comment by ccordoba12** [comment]
@johndpope, it seems you're well intended, but it's simply not possible for us to use VSCode as the basis for the Spyder. VSCode is a general purpose, minimalist editor while Spyder is focused in Python only and it has a tight integration with its scientific libraries (Matplotlib, Pandas, Cython, IPython, etc).

Even JupyterLab, the next generation of the Jupyter notebook with an IDE look-and-feel, is being created from scratch.

So VSCode is great, and if it had existed 8 years go, we could have used it as our foundation. But it's too late for that now.

**Comment by johndpope** [comment]
@ccordoba12  - thanks for reply Carlos.
So I went back 8 years in time to 2009 and told dev team  to use visual studio code when it comes out in April 29, 2015.They said - come back in 6 years and tell us that. So I did. At that point - the team said - it's too new - come back in a couple of years when it's more established. so here I am speaking with you now.


Jokes aside - 
I'm reading that spyder is tightly coupled to Matplotlib, Pandas, Cython, IPython.
That's all good - but consider all I'm saying is - you could / should decouple UI from the core.
ditch QT. It's heavy and lagging.

This is already some of the work done  @andfoy will enable this to progress using RPC.

Have a look at latest variable inspector -> it rocks. it's in electron. It's fast and smooth.
https://github.com/agermanidis/livepython

My use case for spyder (as I'm sure it is for many) - was I want to fire up some tensorflow code and train models.  The last thing I want is a lagging UI that hangs. 
With html + typescript - it's fast / and the process to do the tabs in each window open is a separate process.  

anyway - I read somewhere if you're arguing with argument - you're losing.
But if you're speaking with JupyterLab - tell I said I said don't waste time / just rip off Microsoft's vs code and pass it off as your own. It will be 10,000 times better. 

think - standing on shoulders of giants.

**Comment by ccordoba12** [comment]
> That's all good - but consider all I'm saying is - you could / should decouple UI from the core.
ditch QT. It's heavy and lagging.

Another great advantage of using Qt is that we can continue using Python to develop Spyder itself (through PyQt).

I really don't want to move now to use Javascript/Typescript. This is just a matter of preference, but I think it's important given that I'm the maintainer of this project.

> Have a look at latest variable inspector -> it rocks. it's in electron. It's fast and smooth.

Then you can look at creating a VSCode extension and integrating with it.

----

Anyway, sorry, but I'm not going to participate anymore in this discussion. What you're proposing is unfeasible/undesirable for us.
