### ISSUE TITLE
Variable explorer can't inspect class variables

### ISSUE THREAD

**Issue by agisbrec** [spyder-ide/spyder#5437]
## Description

**What steps will reproduce the problem?**

1.  Create a simple python file:
`class foo:
    def __init__(self):
        self.bar = 0

f=foo()`
2. Press F5 to run the file.
3. Go to variable explorer to inspect "f".

**What is the expected output? What do you see instead?**
Expected to see the value of f.bar.
Get an error instead:
"Spyder was unable to retrieve the value of this variable from the console.

The error mesage was:
AttributeError("Can't get attribute 'foo' on ",)"

**Please provide any additional information below**
I am not trying to debug here. The program is finished.
This used to work before, but does not work anymore for some reason.

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting.

This is a known limitation. We're working to fix it in Spyder 4.

**Comment by crazyBaboon** [comment]
At least the maintainers acknowledge this is a limitation. It is the first sign it might get fixed. I hope it gets fixed for Spyder 4!

**Comment by ccordoba12** [comment]
@crazyBaboon, it should be fixed after Spyder 3.2.5. Could you try it, please?

**Comment by crazyBaboon** [comment]
Not fixed as of 3.2.6

Execute:
```
class MyClass:
  x = 5  
p1 = MyClass()
print(p1.x) 
```
and you I see absolutely nothing in the variable explorer.

**Comment by ccordoba12** [comment]
Did you deactivate this pointed out in blue here?

![seleccion_013](https://user-images.githubusercontent.com/365293/45313239-f0837600-b4f3-11e8-9d44-0daa7e1a62dd.png)

**Comment by crazyBaboon** [comment]
Thanks! That is awesome.

**Comment by changwn** [comment]
> Did you deactivate the pointed out in blue here?
> 
> ![seleccion_013](https://user-images.githubusercontent.com/365293/45313239-f0837600-b4f3-11e8-9d44-0daa7e1a62dd.png)

This method/operation solve my problem. I can see the variable created by Pytorch.

Spyder version :3.3.2, Python :3.7

**Comment by furkan59** [comment]
Just need to double click on class value on variable explorer.

**Comment by zlamere** [comment]
Another issue to add. If you call use a function to define a class in a self created module, and then call that function within the main program __init__(self) parameters are not shown in the variable explorer
