### ISSUE TITLE
clicking the "Open file" icon in the main window will crash Spyder

### ISSUE THREAD

**Issue by kroongp** [spyder-ide/spyder#5444]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\P\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1840, in load
    self.edit_filetypes = get_edit_filetypes()
  File "E:\P\Anaconda3\lib\site-packages\spyder\config\utils.py", line 119, in get_edit_filetypes
    pygments_exts = _get_pygments_extensions()
  File "E:\P\Anaconda3\lib\site-packages\spyder\config\utils.py", line 86, in _get_pygments_extensions
    for lx in lexers.get_all_lexers():
  File "E:\P\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 53, in get_all_lexers
    for lexer in find_plugin_lexers():
  File "E:\P\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()
  File "E:\P\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2404, in load
    self.require(*args, **kwargs)
  File "E:\P\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2427, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "E:\P\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pyparsing 2.2.0 (e:\p\anaconda3\lib\site-packages), Requirement

**Comment by ccordoba12** [comment]
Could you post the output of

    conda list

please?

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by kroongp** [comment]
I am sorry for the late response, I did'nt follow the thread :(
I upload the condalist.txt you asked for
[condalist.txt](https://github.com/spyder-ide/spyder/files/1410266/condalist.txt)

**Comment by ccordoba12** [comment]
According to your list, you have two different versions of pyparsing, so I think that's what's causing this error:

    pyparsing                 2.1.5                     <pip>
    pyparsing                 2.2.0            py35hcd8862f_1

**Comment by kroongp** [comment]
Thank you very much. I will try to do a full uninstall and install.
I do not have time to do so the next few days, but I will report back the
result. Thanks again

Op 24 okt. 2017 18:35 schreef "Carlos Cordoba" <notifications@github.com>:

**Comment by kroongp** [comment]
Yesterday I did a full uninstall/install of Anaconda, and updated the most important items.
Everything is just working fine now :)
I suppose that an installation of SymPy I did with pip, caused the mismatch problem.
Thanks again for pointing out the version mismatch.

**Comment by ccordoba12** [comment]
Good to know you finally solve this problem!!

Just a word of warning for the future: always try to install packages with conda first, then go to conda-forge, and finally, if no package is available in those two, please use pip.

Mixing pip and conda is not a good practice, and could easily break your Anaconda installation (as it was the case here :-).

**Comment by kroongp** [comment]
I learned this the "hard" way.
I won't make the same mistake again! :)

Op 1 nov. 2017 14:08 schreef "Carlos Cordoba" <notifications@github.com>:

Good to know you finally solve this problem!!

Just a word of warning for the future: always try to install packages with
conda first, then go to conda-forge, and finally, if no package is
available in those two, please use pip.

Mixing pip and conda is not a good practice, and could easily break your
Anaconda installation (as it was the case here :-).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spyder-ide/spyder/issues/5444#issuecomment-341101232>,
or mute the thread
