### ISSUE TITLE
pylab problem

### ISSUE THREAD

**Issue by RIDI13** [spyder-ide/spyder#5451]
## Description

**What steps will reproduce the problem?**

1. import pylab as pl

2. x=np.linspace(-5.*np.pi/2.,5.*np.pi/2.,1000)
pl.figure()
pl.plot(x,np.sin(x),label='sin')
pl.plot(x,np.cos(x),label='cos')
pl.plot(x,np.tan(x),'.',label='tan')
pl.legend()
pl.grid()
pl.ylim([-3,3])
pl.savefig('fct_trigo.pdf')
pl.show()
3. 
AttributeError: module 'matplotlib.cbook' has no attribute 'popall'

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.2
* Qt Versions: 5.7.1, PyQt5 5.8.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
> AttributeError: module 'matplotlib.cbook' has no attribute 'popall'

This looks like an installation error in Matplotlib. Sorry, but we can't do anything about it.

> AttributeError: 'super' object has no attribute '_handle_error'

This error was fixed in Spyder 3.2.3. Please update.
