### ISSUE TITLE
Can't indent code blocks more than once (using tab) on Spyder 4

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#5458]
I'm on spyder4 dev master and can't tab indent a block of code that has any leading spaces and therefore it won't let me indent more than one tab. Shift tab works multiple times to remove indents.

I bisected this to #3958 ...I guess I should have tested better.

**What steps will reproduce the problem?**

1. highlight a block of code
2. press tab once (works)
3. press tab again (nothing)

## Versions and main components

* Spyder Version: 4 master
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Linux

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> I guess I should have tested better.

Don't worry about it. Thanks for letting us know this is a side effect of that PR.

@dalthviz, please work on this one.

**Comment by dalthviz** [comment]
Thanks @bcolsen for noticing this and again for all the help with testing this feature, we really appreciated all your effort :+1:
