### ISSUE TITLE
Cannot open Spyder anymore

### ISSUE THREAD

**Issue by emisai49** [spyder-ide/spyder#5460]
## Description of your problem

After last time I closed Spyder and saved file, I couldn't open Spyder anymore. 
When I try to open Spyder, it launches and appears on the taskbar. But when I click it from the taskbar, nothing pops up.  I try to use win-tab to switch to it, doesn't work either.

## Versions and main components

* Spyder Version: 2.7
* Python Version: 2.7
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
Please run in a system terminal (cmd.exe)

    spyder --reset

and try again. That should fix your problem.
