### ISSUE TITLE
Questions : Macos Spyder shortcuts

### ISSUE THREAD

**Issue by sebma** [spyder-ide/spyder#5461]
Hi,

I'd like to know the shortcut for column editing mode, it does not seem to be : 
<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>B</kbd>

Can you tell me what is the shortcut for that ?

**Comment by ccordoba12** [comment]
Sorry, there's no *column editing mode*. @jnsebgosselin is working on this for Spyder 4, to be released next year.
