### ISSUE TITLE
How to enable auto popup for autocomplete?

### ISSUE THREAD

**Issue by wxguy** [spyder-ide/spyder#5462]
## Description of your problem
The auto complete feature provided in the spyder require user to either use `tab` or `ctrl` + `space`. However, I would like to have a auto complete popup without using additional key. 

Is this possible at all under spyder? If yes then how do I enable? I have searched quite a bit but it did not find any useful link on this topic.

**What steps will reproduce the problem?**

 Open any python file and start importing modules and work normally. When I use os module and typr `os.pat`, the auto complete popup window should appear without pressing any key

**What is the expected output? What do you see instead?**
Same as mentioned above.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Debian 9.2

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Edit:-**
this link https://stackoverflow.com/questions/30640755/is-it-possible-to-set-spyder-auto-completion-without-pressing-the-tab-key say that it will be implemented in version 3. Is it implemented?

**Comment by ccordoba12** [comment]
> Is it implemented?

No, sorry, it'll be implemented in Spyder 4.

**Comment by hutaohutc** [comment]
when will Spyder 4 be available? And when i choose code type "(" ,my code will be delect,for example:
a --> (a),must I type '(' twice? In rstudio, I can choose `'a'` and type `'('` to get `'(a)'`

**Comment by stuartjj** [comment]
> > Is it implemented?
> 
> No, sorry, it'll be implemented in Spyder 4.

I am running Spyder 4.0.0b1 on Anaconda in Mac OS X 10.13.6. I don't have popup autocomplete--is it a feature I have to enable in some way?

**Comment by MarkMoretto** [comment]
Just chiming in to echo @stuartjj 's comment.  I've bootstrapped Spyder 4 and pop-up Intellisense would make it a Visual Studio killer for me.

**Comment by ccordoba12** [comment]
It'll be implemented in beta2.

**Comment by dswenningsen** [comment]
Running v 4.0 (Anaconda) (W10) - This works...

> Tools -> Preferences
> Completion and linting
> Enable everything there
> Set "Show automatic completions after characters entered" to your preference (I chose )
> Set "Show automatic completions after keyboard idle (ms)" to your preference (I left default of 300)
> Click Ok_

Should be good :)

**Comment by wxguy** [comment]
Great news. I feel that it should be documented in the official documentation...
