### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JRKONE** [spyder-ide/spyder#5478]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1516, in go_to_error
    self.edit_goto.emit(osp.abspath(fname), int(lnb), '')
ValueError: invalid literal for int() with base 10: ''

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  None (NOK)
numpy >=1.7       :  1.13.1 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by Jeroendevr** [comment]
Could you provide some code. It is possible you are dividing by zero or trying to int() an empty string.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
