### ISSUE TITLE
Error when switching layout

### ISSUE THREAD

**Issue by yerossxu** [spyder-ide/spyder#5479]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/yexu/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1764, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "/Users/yexu/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1884, in quick_layout_switch
    self.setup_default_layouts(index, settings)
  File "/Users/yexu/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1597, in setup_default_layouts
    layout = layouts[index]
KeyError: 4

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
How was this error generated?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
