### ISSUE TITLE
Spyder crash when dragging a plugin with the mouse

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#5486]
## Description of your problem

**What steps will reproduce the problem?**

1. In `Views` uncheck `Lock panes`
2. Try to move a plugin with the mouse
3. Python is crashing systematically

![moving_plugins_around](https://user-images.githubusercontent.com/10170372/31626451-b433e6dc-b277-11e7-970c-c61da368b0e6.gif)

**Please provide any additional information below**

I think this bug was introduced in PR #3824. This is reproducible only in Spyder 4.0.0.dev0 (Commit: 777015f80) and not in Spyder 3.2.4.dev0 (Commit: 7b8042c0e).

## Versions and main components

* Spyder Version: Spyder 4.0.0.dev0 (Commit: 777015f80)
* Python Version: 3.6.2
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows 7 64 bits

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
