### ISSUE TITLE
Code style (pep8) toggle in source menu

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#5488]
## Issue

I often find myself switching the code style warnings on as off as I switch between files and I think it's about 6 clicks through the preferences to get at it.

I often write scripts for figures or data crunching that are one offs and the pep8 is just noise.

For code that I or some one might use again code style is nice to turn on.  Even at that I usually only turn it on in the clean up stage. 

## Solution?

Add a `Code Style Warnings (PEP8)` toggle in the source menu.

Edit: I just found the `# analysis:ignore ` comment.  A `# analysis:ignore_all ` might be handy too.

**Comment by ccordoba12** [comment]
> Add a Code Style Warnings (PEP8) toggle in the source menu.

I like this idea, thanks for the suggestion.

> I just found the # analysis:ignore comment. A # analysis:ignore_all might be handy too.

That's provided by `pyflakes` (I think) so you should google a bit to see if there's a `# analysis:ignore_all` kind of comment.

**Comment by bcolsen** [comment]
I have started working on this.  I'll have a PR this week.

I have the option in the source menu and when I uncheck it the style warnings disappear, but when check it the warnings don't reappear until I change some code and it recomputes

The config dialog runs this code on apply if you change the style check to get around that:  

https://github.com/spyder-ide/spyder/blob/777015f806261338995cdaa2e8d51badd0d7ef19/spyder/plugins/editor.py#L2757

Any hints on how to get a checkable action like these to run that on a check action:

https://github.com/spyder-ide/spyder/blob/777015f806261338995cdaa2e8d51badd0d7ef19/spyder/plugins/editor.py#L1008

**Comment by ccordoba12** [comment]
@rlaverde was working on this a couple of weeks ago. @rlaverde?

**Comment by rlaverde** [comment]
> was working on this a couple of weeks ago?

Yes, I generalize that logic for checkable preferences in  #5274.

>Any hints on how to get a checkable action like these to run that on a check action:

You could add that logic to the` _toggle_checkable_action()` method, although that will add some complexity to that function. https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor.py#L1252
