### ISSUE TITLE
TypeError when dragging non-text files over Spyder

### ISSUE THREAD

**Issue by frexvahi** [spyder-ide/spyder#5490]
## Description

**What steps will reproduce the problem?**

I dragged two files (.odt and .pdf) over the Spyder window (not to open them in Spyder, simply because the Spyder window was between the Dolphin window and the Thunderbird window.

**What is the expected output? What do you see instead?**
I expected Spyder to do nothing. Instead it produced this error message.

**Please provide any additional information below**

  File "/home/cjk/.conda/lib/python3.6/site-packages/spyder/widgets/editor.py", line 2206, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. It should be an easy fix.

**Comment by jnsebgosselin** [comment]
@ccordoba12 I think this error may be related to #5284 and #5218. The traceback is the same in all three cases.

**Comment by ccordoba12** [comment]
Thanks for noticing it @jnsebgosselin. Let's consolidate everything in the oldest issue.

**Comment by frexvahi** [comment]
The problem has reappeared in 3.2.8

### Traceback
```python-traceback
  File "/home/cjk/.conda/envs/everything/lib/python3.6/site-packages/spyder/widgets/editor.py", line 2367, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Linux 4.15.0-20-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.5 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.3.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment]
@frexvahi, could you use `git bisect` to track the change that reintroduced this bug? Thanks!
