### ISSUE TITLE
Error in attempting to open preferences

### ISSUE THREAD

**Issue by talonmyburgh** [spyder-ide/spyder#5493]
Since spyder no longer has a python console I wanted to find a way to create interactive plots as shown here:
https://stackoverflow.com/questions/45960590/how-to-add-python-console-in-spyder

When I try to open Preferences in spyder:
i.e. Tools>Preferences

Instead of opening Preferences however I get the following spyder error:

  File "/home/footy/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2602, in edit_preferences
    widget.initialize()
  File "/home/footy/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 76, in initialize
    self.load_from_conf()
  File "/home/footy/anaconda3/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 380, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
We don't know why this bug appears, but opening a system terminal and running

    spyder --reset

should fix it.
