### ISSUE TITLE
Spyder couldn't start after main window shows up

### ISSUE THREAD

**Issue by xwang9401** [spyder-ide/spyder#5498]
## Description of your problem
After a clean setup of WinPython-64bit-3.6.2.0Qt5, and clicking the spyder.exe icon, the main window of Spyder shows up, but the IPython console could not be started and connected to, meanwhile the windows becomes frozen and un-clickable after a while (10 or 20 seconds). The same issue happens if I install 3.5.4 instead. (I already have all the antivirus or firewall stopped while trying)

Another weird thing is that, two other colleagues with basically the same computer setup and internet environment do get Spyder working normally, while it's me and another colleagues have the same issue. Could this be related to any other software installed on the computer?

Thanks in advance!
**What steps will reproduce the problem?**

1.  Install WinPython-64bit-3.6.2 or WinPython-64bit-3.5.4
2.  Start Spyder by double-clicking the Spyder.exe icon
3. 

**What is the expected output? What do you see instead?**
The main window shows up and gets frozen before connecting to IPython console.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.1dev0
* Python Version: 3.6.2
* Qt Version: n/a
* PyQt Version: 5.9
* Operating system: Windows 7 64 bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

Couldn't do since Spyder is not clickable.

![spyder](https://user-images.githubusercontent.com/32892202/31714966-93b1d086-b434-11e7-92c0-9d4f6db98812.png)

**Comment by ccordoba12** [comment]
Thanks for reporting. Could you start Spyder in a console with this command

    spyder --show-console

and see if any errors are printed there?

@stonebig, have you seen this bug before?

**Comment by xwang9401** [comment]
Hello,

Thanks for the reply. I tried that before but it didn't help much. There was a console window that flashed for a second on the screen then disappeared, but then the main window of Spyder would never show up.

**Comment by ccordoba12** [comment]
Does this problem happen if you use Anaconda instead of WinPython?

**Comment by xwang9401** [comment]
Sorry but I don't have Anaconda installed on my computer. Do you think that might make a difference? I can certainly try it out.

Also, I've seen other similar issues reported online, and some people think it's the problem between pyqt5.9 and Windows 7. So do you think I should try a WinPython version with an elder pyqt5?

Thanks

**Comment by xwang9401** [comment]
Update: I just tried WinPython 3.5.3 with PyQt5.7.1, and everything works just fine! So is it really of the PyQt5.9 being incompatible with Windows 7? But then I don't understand why my other colleagues can get it working with the same setup...

**Comment by ccordoba12** [comment]
Ok, this seems an issue with WinPython and not Spyder, so I'm closing it.

If you want to keep discussing about it, please open an issue in the WinPython issue tracker.
