### ISSUE TITLE
Spyder Hangs while debugging

### ISSUE THREAD

**Issue by arorar** [spyder-ide/spyder#5500]
## Description of your problem
Spyder Hangs while copying from the ipython console while debugging

**What steps will reproduce the problem?**

1.  Set a break point and start debugging use CTRL + F5 and CTRL + F12
2.  Copy a line from the Ipython console ("not from the code window") by pressing "CTRL+ C" when the debugger stops at the break point. Paste it in Ipython console
3. Press enter in Ipython Console using CTRL + V. The console hangs and the kernel needs to be restarted.

My guess is that pressing CTRL + C halts the kernel. Not sure if this is a way to change the binding

**What is the expected output? What do you see instead?**
Must work while copy pasting from the console during debugging.

**Please provide any additional information below**
Using Anaconda as package manager.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 2.7.14 64 bit
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
> My guess is that pressing CTRL + C halts the kernel. Not sure if this is a way to change the binding

No, there isn't. You need to use `Ctrl+Shift+C` when copying code from the IPython console while debugging to avoid this.
