### ISSUE TITLE
Spyder does not work under python 3.6.3 on mac

### ISSUE THREAD

**Issue by zhiruiwang** [spyder-ide/spyder#5507]
## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**
`
Traceback (most recent call last):
File "/Users/zhirui/anaconda3/bin/spyder", line 7, in 
from spyder.app.start import main
File "/Users/zhirui/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 13, in 
import zmq
File "/Users/zhirui/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 29, in 
_load_libzmq()
File "/Users/zhirui/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 9, in _load_libzmq
import sys, ctypes, platform
File "/Users/zhirui/anaconda3/lib/python3.6/ctypes/__init__.py", line 7, in 
from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/zhirui/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so, 2): Symbol not found: __PyUnicode_AsWideCharString
Referenced from: /Users/zhirui/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
Expected in: flat namespace
in /Users/zhirui/anaconda3/lib/python3.6/lib-dynload/_ctypes.cpython-36m-darwin.so
`

**Please provide any additional information below**
Spyder does not work under python 3.6.3 on mac. When I downgrade to python 3.6.2, everything works fine. 

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: macOS high sierra 10.13

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Please open a terminal and run

    conda update python.app

That should fix your problem.
