### ISSUE TITLE
Shortcut for run selection(fn+F9) not working on mac

### ISSUE THREAD

**Issue by zhiruiwang** [spyder-ide/spyder#5509]
## Description of your problem

**What steps will reproduce the problem?**

1. Open Spyder, fn+F9 not working
2. Go to preferences, reset keyboard shortcuts to default, fn+F9 start working
3. Close Spyder and open it again, fn+F9 still not working. So every time when I open Spyder, I have to reset the keyboard shortcuts.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4(I have this problem since 3.2.2)
* Python Version: 3.6.3(I have this problem since 3.6.2)
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: macOS high sierra 10.13

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0 : 6.1.0 (OK)
cython >=0.21 : 0.26.1 (OK)
jedi >=0.9.0 : 0.10.2 (OK)
nbconvert >=4.0 : 5.3.1 (OK)
numpy >=1.7 : 1.13.3 (OK)
pandas >=0.13.1 : 0.20.3 (OK)
psutil >=0.3 : 5.3.1 (OK)
pycodestyle >=2.3: 2.3.1 (OK)
pyflakes >=0.6.0 : 1.6.0 (OK)
pygments >=2.0 : 2.2.0 (OK)
pylint >=0.25 : 1.7.4 (OK)
qtconsole >=4.2.0: 4.3.1 (OK)
rope >=0.9.4 : 0.10.5 (OK)
sphinx >=0.6.6 : 1.6.3 (OK)
sympy >=0.7.3 : 1.1.1 (OK)

**Comment by Jeroendevr** [comment]
Thank you for reporting. Did you have this issue before running high sierra or didn't you use spyder on sierra?

**Comment by zhiruiwang** [comment]
@Jeroendevr I cannot remember exactly when did this happen, but I think it happened a few days after I upgraded to high sierra. Thank you for asking, do you think it is due to high sierra?

**Comment by ccordoba12** [comment]
Yes, it's quite possible. I think this problem will be solved once Anaconda Inc. updates Qt, the graphical toolkit upon which Spyder is built.

**Comment by ccordoba12** [comment]
Sorry but this is not an error we can solve in Spyder itself.

**Comment by zhiruiwang** [comment]
@ccordoba12 Sure, I have already raised the issue on anaconda-issues: https://github.com/ContinuumIO/anaconda-issues/issues/6803

**Comment by alpoise** [comment]
Have the same problem

**Comment by louis925** [comment]
Having the same problem. Pressing F9 in Spyder doesn't run the selected codes. However, if you try to modify the keyboard shortcut in preference > keyboard shortcut, it can detect F9 properly. So F9 work but Spyder didn't run the selected codes.
Spyder version: 3.3.0
MacOS version: 10.13.6
Python version: 3.6.5
Qt version: 5.9.3
PyQt5 version: 5.9.2

**Comment by mingwandroid** [comment]
Please avoid pip when installing binaries.

**Comment by louis925** [comment]
Why not pip? On the official website of PyQt5, pip is the installation method they suggested.

**Comment by mingwandroid** [comment]
Because conda and pip do not interpretate perfectly.

**Comment by louis925** [comment]
Oh, OK. I am only using pip no conda.
