### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by NwpuPc** [spyder-ide/spyder#5513]
## Description of your problem

**What steps will reproduce the problem?**

1. open spyder

**What is the expected output? What do you see instead?**
Issue 1:
At IPython console:
"An error ocurred while starting the kernel"
"The directory /run/user/1000/jupyter is not writable and it is required to create IPython consoles. Please make it writable."

I have checked the directory /run/user/1000/, it is belong to another user. There is another directory /run/user/1002/ which is belong to me, but nothing in it.

Issue 2:
I cannot input anything from keyboard to any panel, editor, or dialog.
I use vnc to do this, but this error do not occur when I use other applications.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1
* Qt Version: 5.6.2
* PyQt Version: 1.2.1
* Operating system: ubuntu 14.04.5 LTS

## Dependencies
all are installed (OK).

**Comment by Jeroendevr** [comment]
I see you don't use the latest Spyder version. If there is no specific reason for it you could try to update to 3.2.3. By upgrading you distribution or `pip install --upgrade spyder`

**Comment by ccordoba12** [comment]
The error message is quite clear. You need to make

     /run/user/1000/jupyter

writable so that Spyder can create IPython consoles for you.

**Comment by lorenzocardarelli** [comment]
I am experiencing the same trouble. I have no permission to access that folder. Jupyter in Spyder was working few weeks back and I have not changed manually any path. It seems to me that it is not pointing to the Jupyter provided within Anaconda (to which Spyder belongs too) anymore.

How can I redirect Spyder to look for Jupyter somewhere else?

**Comment by ccordoba12** [comment]
That depends on Jupyter, I mean, the directory is defined by Jupyter not by Spyder. Is the Jupyter notebook running for you?

**Comment by moinkhan3012** [comment]
for me jupyter is working fine but there is some problem related with spyder

**Comment by Kassy607** [comment]
I have the same problem here.... does somebody jhave a solution?

**Comment by ccordoba12** [comment]
@Kassy607, please open a terminal and run there

    id -u <your-user>

and report back the number. That will help us to better understand your problem.

**Comment by Kassy607** [comment]
ok sorry i got the solution.... I had to make the whole folder of my winpy installation writable.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
