### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ioodufow** [spyder-ide/spyder#5516]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\2PAC\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 359, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "C:\Users\2PAC\Anaconda3\lib\site-packages\nbformat\__init__.py", line 139, in read
    return read(f, as_version, **kwargs)
  File "C:\Users\2PAC\Anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
    return reads(fp.read(), as_version, **kwargs)
  File "C:\Users\2PAC\Anaconda3\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.2.0 (NOK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a bug in `spyder-notebook`, so I'm moving this issue to its corresponding repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #128](https://github.com/spyder-ide/spyder-notebook/issues/128) via [**ZenHub**](https://www.zenhub.com/)
