### ISSUE TITLE
Add path autocompletion to the Editor

### ISSUE THREAD

**Issue by stevenpawley** [spyder-ide/spyder#5519]
## Description of your problem

**What steps will reproduce the problem?**

1. Path autocompletion, i.e. 'C:/MyFiles/<tab>' is not available in the editor window, only in the console.

**What is the expected output? What do you see instead?**

This would be a really useful enhancement from a data processing perspective. One of the features I love about Rstudio is that I can locate my files in deeply nested directories very quickly using tab-autocompletion.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll consider this for a future release.

**Comment by IonutBarbuMcK** [comment]
This is just to support previous request from @stevenpawley 

Awesome that you have added file path autocompletion for the iPython console in spyder 4.0. Thanks a lot!
Hope to see the functionality also in the editor in a near future release

**Comment by 6884** [comment]
+1, would love to see this in spyder as well!

**Comment by goanpeca** [comment]
Bumping to 4.2 @ccordoba12 ?

**Comment by ccordoba12** [comment]
@andfoy, this will be made possible by updating Jedi to 0.15.2 in PR #11809. So if you write in the Editor:

    '/ho<Tab>'

you'll get

    '/home/'

However, that only works when code snippets are deactivated. If they are activated, you'll get this error:

```python-traceback
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/extensions/snippets.py", line 814, in insert_snippet
    ast = build_snippet_ast(text)
  File "/home/carlos/Projects/spyder/github-repo/spyder/utils/snippets/ast.py", line 154, in build_snippet_ast
    peek_token
SyntaxError: Syntax Error: Expected any of the following characters: ['dollar', 'name', 'int', 'case', '\\:', '\\$', 'text_pipe', '{', '\\}', '\\', '\\/', '\\,', 'symbol', 'whitespace', 'left_curly_name', ':', ':+', ':-', ':?', ',', '<eof>', '}'], got <slash, />
```

Please take care of that.
