### ISSUE TITLE
Unable to save empty notebook

### ISSUE THREAD

**Issue by paragguruji** [spyder-ide/spyder#5520]
## Description

**What steps will reproduce the problem?**

1. Create a new notebook (gets name untitled0)
2. "Save as" with another filename in an existing local project folder

**What is the expected output? What do you see instead?**
Expected to see the file saved locally in the specified folder. Instead get this error dialog box.

**Please provide any additional information below**

  File "C:\Users\Parag\Anaconda2\envs\mlenv\lib\site-packages\spyder_notebook\notebookplugin.py", line 399, in save_as
    nb_contents = nbformat.read(original_path, as_version=4)
  File "C:\Users\Parag\Anaconda2\envs\mlenv\lib\site-packages\nbformat\__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
IOError: [Errno 2] No such file or directory: 'c:\\users\\parag\\appdata\\local\\temp\\spyder\\notebooks\\untitled1.ipynb'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25

**Comment by andfoy** [comment]
Issue moved to [spyder-ide/spyder-notebook #131](https://github.com/spyder-ide/spyder-notebook/issues/131) via [**ZenHub**](https://www.zenhub.com/)
