### ISSUE TITLE
How To Disable Already Running Error?

### ISSUE THREAD

**Issue by NikWillmore** [spyder-ide/spyder#5524]
Fresh installation of Autodesk Fusion 360 that installed Spyder for me. Every time I hit the green run button it forces me to manually confirm to close the existing console and start a new one since my script is already running. No, it's not still running. It has completed "Hello World!" and is done. Same thing for the first debug start button. This would drive me nuts and I've never seen such a bizarre hassle in other Python editors. They just run the script again. This behavior is seen in Fusion 360 Python tutorial videos too.

**Comment by ccordoba12** [comment]
This error only happens for old Spyder versions, which we don't support anymore.

I think you can fix this by going to the menu

    Run > Configure

or maybe an option in

    Preferences > Python console

but I'm not really sure anymore.

**Comment by NikWillmore** [comment]
Ah, Fusion 360 is using an old version then, namely 2.3.2 compared to latest being 3.2.4. 

Alas, it's as if Fusion is owning the process, and it doesn't appear anywhere in the Window Task Manager when running, nor as an installed program, and it only appears in an %AppData% directory structure where Fusion hides out. It's a complicated installation, just just a program, so I can't update it. Nor do I have any of those preferences in this jailed version.
