### ISSUE TITLE
Spyder 3.2.4 dmg for MacOS

### ISSUE THREAD

**Issue by afixibiranchi** [spyder-ide/spyder#5531]
Please update the Spyder 3.2.4 dmg for MacOS

**Comment by Ericvulpi** [comment]
👍 

It is a bit disorientating to :
- get a message to update to 3.2.4 when opening spyder
- go to navigator and find that current 3.2.3 version is up to date
- try anyway a `conda update spyder` in the terminal and have the same answer

**Comment by ccordoba12** [comment]
@Ericvulpi, sorry, we don't control when Anaconda updates our packages. They usually take a couple of days to do it...

@afixibiranchi, sorry, we're not going to create more DMGs from now. That's why we don't promote them anymore.

**Comment by Ericvulpi** [comment]
Anaconda doesn't seem to be moving. Should I open the issue on their side ?
