### ISSUE TITLE
Linux64-Spyder 3.2.4 in Anaconda 1.6.8 doesn't have regular Python Console

### ISSUE THREAD

**Issue by darwinli** [spyder-ide/spyder#5532]
## Description of your problem
I am running Linux 64bit and I installed Spyder 3.2.4 through Anaconda 1.6.8 and the only console available is iPython. I would like to use regular Python 3.6.2 console. Was this removed in the latest Spyder?

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.2
* Qt Version:
* PyQt Version:
* Operating system: Linux 64bit Mint 18.2

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
> Was this removed in the latest Spyder?

Yes, it was. Please see #4524.
