### ISSUE TITLE
Please look into this, if the image in display package is getting called

### ISSUE THREAD

**Issue by Abrahamw007** [spyder-ide/spyder#5542]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Anaconda\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 134, in _handle_execute_result
    png = decodestring(data['image/png'].encode('ascii'))
  File "C:\Anaconda\lib\base64.py", line 561, in decodestring
    return decodebytes(s)
  File "C:\Anaconda\lib\base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)

**Comment by Jeroendevr** [comment]
Thank you for posting this bug. Could you share some code you are trying to run?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
