### ISSUE TITLE
Variable explorer column widths are re-generated in every console evaluation

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#5543]
## Description

The variable explorer window re-generates the column widths on creation of every new variable, over-riding any user modification of the column widths. This is annoying as it also tends to make th type column wide enough to display full type information even though other columns (e.g. the Value) would be the ones the user is more interested in.

**What steps will reproduce the problem?**

1.  Set numpy and pylab to be automatically loaded. Observe that the variable explorer window has  entries for a number of items with long type names (e.g. cast and nbytes).
2.  Shrink the size the of the type column to allow the Value column to be larger
3.  Create a new variable in the console
4. Goto 2

**What is the expected output? What do you see instead?**

Either a smarter layout of columns  when the variable explorer is horizontally constrained, or some mechanism to 'freeze' the column widths or hide/collapse columns.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
> The variable explorer window re-generates the column widths on creation of every new variable, over-riding any user modification of the column widths.

Seems reasonable to me. We'll take a look at it in a future release.

**Comment by Prikers** [comment]
@ccordoba12 I could work on that one. What would be the best solution according to you? Maybe an option button (close to the `reset_namespace` button) which, when on, would "freeze" the column width?

**Comment by ccordoba12** [comment]
Thanks @Prikers!

> Maybe an option button

I don't think an option is necessary. We should simply preserve the column width after each evaluation. That's the intuitive/expected result, as @gb119 pointed out.

**Comment by Prikers** [comment]
So it would be the very first evaluation that would determine the column widths? Or we just set some default rules like name is 20% of the total width, size is 10%, etc.?

**Comment by ccordoba12** [comment]
I think some default rules would be fine. @goanpeca, what do you think?

**Comment by gb119** [comment]
If I might butt in.... :-)
I would think the user manually adjusting the column widths by dragging the splitters in the header should set some flag in the internal state. If that flag is not set then the current behaviour should happen, but if the flag is set, then the columns widths should not longer change.
I guess one could have some UI to reset that - perhaps in a context menu - the existing context menu has a 'resize row to contents' you could add a 'automatically resize column' entry too.

**Comment by ccordoba12** [comment]
Very good ideas @gb119! I really like them ;-)

@Prikers?

**Comment by goanpeca** [comment]
>If I might butt in.... :-)
I would think the user manually adjusting the column widths by dragging the splitters in the header should set some flag in the internal state. If that flag is not set then the current behaviour should happen, but if the flag is set, then the columns widths should not longer change.
I guess one could have some UI to reset that - perhaps in a context menu - the existing context menu has a 'resize row to contents' you could add a 'automatically resize column' entry too.

Sounds good!

**Comment by Prikers** [comment]
Sounds good to me too!
