### ISSUE TITLE
Need to restart Console after each script execution

### ISSUE THREAD

**Issue by hgoumner** [spyder-ide/spyder#5545]
## Description of your problem

When I execute a script (usually with tkinter to load filenames) it runs, but i have to restart the IPython console in order to continue working. Also, when I start Spyder, the console shows that the kernel has died and restarts, and then the line inputs act strangely (when I press enter it resets the counter of the line to the current line # -1):

Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

Restarting kernel... 

In [0]:

In [0]:

In [1]:

**What steps will reproduce the problem?**

1. Start Spyder
2. Run script
3. none

**What is the expected output? What do you see instead?**

The code runs, but it seems like some kind of process keeps going on in the background and I have to restart the console.

**Please provide any additional information below**

I used WinPython-64bit-3.5.4.0Qt5 to install all the packages, and I have tried resetting Spyder with the reset tool, but that did not solve my problem.

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.5.4 64bit
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows 7 Enterprise

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by Jeroendevr** [comment]
Thank you for posting this bug. Could you share some code you are trying to run? Does it also happens every time you use TKinter? Is there a pattern in the dieing of the kernel? For example I had an issue(with the Qt framework where the script would run, rerunning the script did let the kernel died but running after a restarted kernel worked.

**Comment by hgoumner** [comment]
This is the script that I am using. The dying and restarting of the kernel happens every time that i start Spyder. This is the output in the Spyder internal console:

>>> Starting new server
WARNING:traitlets:kernel died: 6.010601043701172
Pweaved C:\Users\goumnero\AppData\Local\Temp\spyder\welcome.md to welcome.html

`
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 20 15:15:20 2017

@author: XXX
"""
#%% Import modules
import pandas as pd
import numpy as np
import scipy as sp

import matplotlib.pyplot as plt

import tkinter
tkinter.Tk().withdraw()
from tkinter.filedialog import askopenfilenames as asks

import os

#%% Inputs

# Filename(s)
fns = asks()

base = []

#%% Load input
    
for i in range(len(fns)):
    
    base.append(os.path.basename(fns[i])[:-4])
    
    if i == 0:
        with open(fns[i], 'r') as file:
            N = 20
            for j in range(N):
                print(str(j+1) + '. ' + file.readline())
            fl = len(file.readlines())+N
        h = int(input('Last line of header: '))
        data = np.zeros((len(fns),100,5))
    
    cur = pd.read_csv(fns[i], sep=',', header=h-1)
    cur = cur.sort_values(cur.columns[0])
    data[i,:cur.shape[0],:] = cur
#    data[i] = data[i][~(data[i]==0).all(1)]

#%% Plot function

def pll(x,T,u,w,name):
    f, (ax1, ax2) = plt.subplots(2, sharex=True)
    
    ax1.plot(x,T-ktoc,'bo-',label=['Temp ' + name])
    ax1.plot(xw1,yw1,'k',xw2,yw2,'k')
    ax1.set_ylim([0,2000])
    ax1.set_xlim([0,450])
    ax1.xaxis.set_ticks(np.arange(0, 450, 50))
    ax1.legend(loc=1)
    ax1.grid()
    
    ax2.plot(x,u,'b',label=['u ' + name])
    ax2.plot(x,w,'r',label=['w ' + name])
    ax2.plot(xw1,yw1,'k',xw2,yw2,'k')
    ax2.set_ylim([-0.5,0.5])
    ax2.legend(loc=1)
    ax2.grid()

#%% Run

# Offset
ktoc = 273.15

# Window
xw1 = 131*np.ones(10)
xw2 = 158*np.ones(10)

yw1 = np.linspace(-3000,3000,10)
yw2 = np.linspace(-3000,3000,10)

for k in range(len(fns)):
    pll(data[k,:,0],data[k,:,2],data[k,:,3],data[k,:,4],str(base[k]))
`

**Comment by ccordoba12** [comment]
Please run this command

    %gui tk

 before running your code in a fresh console, and try again.

**Comment by hgoumner** [comment]
Hello,

thank you for the quick response. I tried running that command but I get the following error:

In [1]: %gui tk
ERROR:root:Cannot activate multiple GUI eventloops

After that, I switched my graphics settings from Automatic to Inline (Preferences > IPython console > Graphics > Graphics backend to 'Inline') and tried again, and now Spyder works fine. 

So changing the graphics to inline (without the need to enter %gui tk) also works for me, however the kernel still dies when I start Spyder. I assume that this is a separate issue, though. Thanks a lot for the help :)

**Comment by ccordoba12** [comment]
> however the kernel still dies when I start Spyder. I assume that this is a separate issue

It's a minor annoyance, it doesn't really die, it just takes too much time to start.

**Comment by cecidip** [comment]
It happens to me ALL THE TIME ! and im a bit fed up ... did you solve it ? What can i do ?

**Comment by hgoumner** [comment]
Hey, so the kernel "dying" at the start up phase is normal, it just takes longer to start than the Spyder GUI. About the tk thing, i had to change my graphics settings like i wrote in my last post. I think that the whole Tk thing is obsolete and a better tool should be used. Unfortunately Qt gives the same problems as Tk from time to time. Good luck.
