### ISSUE TITLE
QT application exits immediately when running from Spyder

### ISSUE THREAD

**Issue by FedeMiorelli** [spyder-ide/spyder#5548]
When running a PyQt4 application in a dedicated console, the Qt program window appears and disappears immediately after execution.
This behaviour occurs if the call to exec_() is within a funcion, but does not happen if the same call is in the __main__ part.

The same issue does not happen with Spyder 3.1.x

Am I doing something wrong?

This code does not work (F5 -> window disappears immediately)
```
from PyQt4.QtGui import QApplication, QMainWindow

def run():
    app = QApplication([])
    form = QMainWindow()
    form.show()
    app.exec_()

if __name__ == '__main__':
    run()
```

This code works (F5 -> Qt application starts)
```
from PyQt4.QtGui import QApplication, QMainWindow

if __name__ == '__main__':
    app = QApplication([])
    form = QMainWindow()
    form.show()
    app.exec_()

```

* Spyder Version: 3.2.4
* Python Version: 2.7.13 64bit
* Qt Version: 4.8.7
* PyQt Version: 4.11.4 (API v2)
* Operating system: (Windows 7 64bit)

**Comment by ccordoba12** [comment]
Thanks for reporting. @dalthviz knows the answer to this one.

@dalthviz, please open a page in our wiki to point users to the solution of this problem, instead of answering this one in each issue.

**Comment by dalthviz** [comment]
@ccordoba12 here the [wiki page](https://github.com/spyder-ide/spyder/wiki/How-to-run-Qt-PyQt-applications-within-Spyder)

@FedeMiorelli I tested the versions of the code you provided but both worked for me (the only thing is that the program window loses focus sometimes at the beginning):

![qtapp](https://user-images.githubusercontent.com/16781833/31976759-f3da1c7e-b8fe-11e7-9ecf-ef7cf2424ddb.gif)

**Comment by ccordoba12** [comment]
Thanks a lot for the wiki page @dalthviz! It would save as a lot of time!

@FedeMiorelli, as @dalthviz said, I think there's no problem here, it's just that your application loses focus after being run.

**Comment by FedeMiorelli** [comment]
Hi @dalthviz  and @ccordoba12, thank you for your feedback.

I'm afraid in my case the application is actually shutting down and not just losing focus.
I can record a similar animation if you let me know the program you used (cool, by the way!)

Anything else I can do to clarify?
Tank you

**Comment by dalthviz** [comment]
Hi @FedeMiorelli if you want to make a gif/animation of what you are experiencing you can use [LICEcap](https://www.cockos.com/licecap/)

**Comment by FedeMiorelli** [comment]
Thank you @dalthviz.
As you can see below, in my configuration the program actually exits and is not just losing focus.
This happens on two different machines with the same configuration. I am using WinPython 2.7.13.1 with the versions specified in the initial post.

![test](https://user-images.githubusercontent.com/7534987/32039053-dafa89bc-ba2c-11e7-8e57-6c007ffcc029.gif)

Cheers,
Federico
