### ISSUE TITLE
My spyder shows this issue on startup

### ISSUE THREAD

**Issue by gdiwakar1987448** [spyder-ide/spyder#5549]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

WARNING:traitlets:kernel died: 6.000343322753906
WARNING:traitlets:kernel died: 6.000343322753906
WARNING:traitlets:kernel died: 6.000343084335327
WARNING:traitlets:kernel died: 6.000343322753906
WARNING:traitlets:kernel died: 6.009343862533569
WARNING:traitlets:kernel died: 6.000343084335327
WARNING:traitlets:kernel died: 6.000343084335327
WARNING:traitlets:kernel died: 6.000343322753906
WARNING:traitlets:kernel died: 6.000343322753906
WARNING:traitlets:kernel died: 6.010343551635742

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
That's not an error, just a warning. The number of those warnings should be reduced in Spyder 3.2.4.
