### ISSUE TITLE
Setting "Clear Line" Keyboard Shortcut Does Not Work Properly

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5558]
## Description

The default KB shortcut for clear line in the console requires some gymnastics (Shift-Esc) and takes far longer than my typical Ctrl-A, Backspace, which does not work for whatever reason (as Ctrl-A/Select-All does not select the current line in the console, as it presumably should). Thus, I went to set it, but seemingly regardless of what I set it to, there was some problem or another. 

Setting it to Ctrl-D made it behave like the delete key, deleting one character at a time in front of the cursor. Setting it to Shift-Ctrl-Backspace made it delete one word at a time, like Ctrl-Backspace, and Shift-Ctrl-Delete did the same thing, except forward-delete like Ctrl-Del. Setting Alt-D selected debug in the Debug menu, like Alt-keys otherwise do. Setting Ctrl-Alt-Shift F made the cursor advance one character forward at a time without deleting, like the right arrow. Setting Ctrl-Shift-A made it select all the text in the console window (pity Ctrl-A didn't do anything, i.e. select the current line like in most other consoles, or I'd be in business without having to worry about this shortcut). Finally, setting an arbitrary shortcut (Ctrl-Shift-Alt-J) made it just type the letter J. However, Shift-Esc, as well as just Esc, still cleared the line even though it wasn't set. 

To make an overly long story short, these are all different shortcuts, which function regardless of how this shortcut it set, which leads to the obvious conclusion that changing the setting isn't actually doing anything. Perhaps it it might have something to do with it being specifically for the console, as it does not conflict (in the KB shortcuts dialog) with other non-console shortcuts, as it should, but neither does it actually do anything to change it.

**What steps will reproduce the problem?**

1. Set "Clear Line" shortcut to something other than the default
2. Attempt to use new shortcut
3. Fail

**What is the expected output? What do you see instead?**

Expected: Set shortcut (ideally, personally I'd prefer Ctrl-D to mirror the editor) clears current line in the console. Also, see no reason why Ctrl-A shouldn't select the current line, as it does in most other (decent) consoles, which then enables easy copying, pasting, deletion, etc.

Actual: Selected shortcut does nothing, or performs some other function, while previous shortcut does not work. Ctrl-A does nothing, while Ctrl-Shift-A selects all console text (not just current line).

**Additional Information**

Tested on multiple machines and anaconda/spyder installs and versions, with same results, including from completely clean/default install and prefs/shortcuts file. Also, believe I might have experienced a keyboard combination I'd set previously and then replaced with another attempt actually starting to work, but I could not clearly reproduce on my clean test setup.

## Version and main components

* Spyder Version: 3.2.2–3.2.4 
* Python Version: 3.6.1–3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 x64

## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
I think that shortcut can't really be set right now, sorry.

@rlaverde, please test if this is the case or not.

**Comment by rlaverde** [comment]
I can reproduce this bug

Some ipyconsole shortcuts are hardcoded https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/ipythonconsole/client.py#L352-L358

Looking at thee history, they are being hardcoded for a long time, but I don't understand the reason
https://github.com/spyder-ide/spyder/commit/12b5b9e1efb70dfb1f5ab0f9ff81e31ee7c27ce8

Looking at the preferences history, these shortcuts were added but only used in the old python console https://github.com/spyder-ide/spyder/commit/e6e783bc64f746e28b575953fb101fb89e50c971

Is ok to change make them loaded them from the preferences? I don't find any good explanation why  they are hardcoded

**Comment by ccordoba12** [comment]
> I don't understand the reason

I hardcoded them myself because at that time there was no way to configure those shortcuts.

> Is ok to change make them loaded them from the preferences?

Yep, thanks for opening a PR to do that ;-)
