### ISSUE TITLE
Prevent pip from installing Spyder when running under Anaconda

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#5562]
I'm really tired of people screwing up their Anaconda installations by using `pip` to update Spyder.

So I want to add a check to our setup.py to prevent `pip` from installing/updating Spyder in the Anaconda environment.

That would save us of so many headaches!!

**Comment by timhoffm** [comment]
Just as a note: This might not be possible when installing from wheels.

> Installing a package from a wheel does not invoke the build system at all.

https://pip.pypa.io/en/stable/reference/pip_install/#build-system-interface

**Comment by ccordoba12** [comment]
Thanks for the pointer @timhoffm. We'll take a look at it.

**Comment by ccordoba12** [comment]
Closing because this is not possible.
