### ISSUE TITLE
Ctrl-Backspace behaves inconsistently in (iPython) console

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5566]
## Description

Often, when sending or copying code to the (iPython) console, I might want to delete a blank line or clean it up to all be on one line. However, unlike in the editor and most all other editors/consoles, Ctrl-Backspace doesn't just delete extra spaces and such from the current cursor position to the beginning of the line, but also the line break and the last word on the previous line. 

In the (perhaps uncommon) case one might actually want to delete either of these as well, another one or two tabs on backspace will do the trick, but conversely there is no easy way to replicate the other behavior, and given the inconsistency with the editor and most other applications it often leads to mistaken deletions. 

Therefore, the newline character and the blank spaces in a line should each be treated as separate words for the purposes of Ctrl-Backspace, as they are elsewhere.

**What steps will reproduce the problem?**

1. Copy e.g. a multiline statement into the console, such as
```
foo = ["foo", "foo", "foo",
          "foo", foo", "bar"]
```
2. Place cursor at beginning of second line text (e.g. with Home)
3. Hit Ctrl-Backspace

**What is the expected output? What do you see instead?**

Expected: Blank spaces are deleted, up to the beginning of the line, as in the Spyder editor
e.g.
```
foo = ["foo", "foo", "foo",
"foo", foo", "bar"]
```
and then an additional tap of Ctrl-Backspace gives
```
foo = ["foo", "foo", "foo","foo", foo", "bar"]
```
with further such keystrokes deleting successive "word" elements as normal.

Instead, with only one press of Ctrl-Backspace, I get
```
foo = ["foo", "foo", ""foo", foo", "bar"]
```
i.e. the blank spaces, the line break, and the last "word" element all deleted. In the editor, the expected behavior occurs, but the latter is the case in the console.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is not a Spyder bug because we depend on the `qtconsole` package to provide our IPython consoles.

So, please fill this bug here:

https://github.com/jupyter/qtconsole

**Comment by CAM-Gerlach** [comment]
Will do, thanks. Would the same be true of the bug I was planning to file regarding Ctrl-A in the console performing the action listed for Meta-A instead (cursor to beginning of line), rather than select-all as it should? Or does that have to do with Spyder's keyboard handling?

**Comment by CAM-Gerlach** [comment]
I see; thanks very much. As I always used Home for the same purpose in consoles on various systems, I never got used to using Ctrl-A for that. From some googling, it doesn't look like there is a common shortcut for select-input, and all I could find in the qtconsole docs was that it uses the standard emacs shortcuts, which weren't of much help. Rather odd though that Ctrl-Shift-A selects everything in the console, but there appears to be nothing to select the current line which would be generally more useful I'd think. In any case, not as a high priority now that the delete line fix will be pushed. Thanks again!
