### ISSUE TITLE
Spyder: cannot connect to X server

### ISSUE THREAD

**Issue by ggarcia0610** [spyder-ide/spyder#5567]
## Description of your problem
When I run spyder on my terminal, I get below message:
#spyder
Spyder: cannot connect to X server

Below is my spyder version along with python running under Linux CentOS 6.8.
I have read some articles about this issue but still couldn't fix the problem.

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**
Should open spyder IDE but nothing fires up/

**Please provide any additional information below**
[] Troubleshooting done:

ran spyder then I get this message (Spyder: cannot connect to X server)
ran spyder --reset then same message I get (Spyder: cannot connect to X server)
ran spyder --new-instance then same message I get (Spyder: cannot connect to X server)
Uninstall then re-install spyder
removed .spyder2 directory that's being created when I ran spyder command.

## Versions and main components
* Spyder Version: 
conda list spyder
packages in environment at /usr/local/anaconda2:

Using Anaconda Cloud api site https://api.anaconda.org
spyder 2.3.9 py27_0

* Python Version:
python --version

Python 2.7.12 :: Anaconda 4.1.1 (64-bit)

python3 --version

Python 3.6.3

* Qt Version:
# conda list qt
# packages in environment at /usr/local/anaconda2:
#
Using Anaconda Cloud api site https://api.anaconda.org
pyqt                      4.11.4                   py27_3
qt                        4.8.7                         3
qtconsole                 4.2.1                    py27_0
qtpy                      1.0.2                    py27_0

* PyQt Version:
# conda list qt
# packages in environment at /usr/local/anaconda2:
#
Using Anaconda Cloud api site https://api.anaconda.org
pyqt                      4.11.4                   py27_3
qt                        4.8.7                         3
qtconsole                 4.2.1                    py27_0
qtpy                      1.0.2                    py27_0

* Operating system:
Linux ( CentOS 6.8 )

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
> #spyder

It seems you're trying to run Spyder as root. Please run it as a regular user or google how to run graphical applications as root.

**Comment by ggarcia0610** [comment]
Yes, I'm running it as root and also tried it running as a regular user.
Can you help me to pin down what the issue is in launching the spyder please.
