### ISSUE TITLE
WindowsError in set_working_directory

### ISSUE THREAD

**Issue by Bloger01** [spyder-ide/spyder#5571]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Python\lib\site-packages\spyder\plugins\ipythonconsole.py", line 912, in set_working_directory
    refresh_console=False)
  File "C:\Python\lib\site-packages\spyder\plugins\workingdirectory.py", line 286, in chdir
    os.chdir(directory)
WindowsError: [Error 2] : u'C:\\Users\\pc 1\\Desktop\\\u0423\u043d\u0438\u0432\u0435\u0440\\Programmieren\\VORLESUNG+UBUNG'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by rlaverde** [comment]
Try using python3, python2 could throw really weird errors when working with unicode characters

**Comment by Bloger01** [comment]
Thanks for answer , my university doesn't allow me to work in python3



Gesendet von App von Mail.Ru für iOS


Dienstag, 31. Oktober 2017, 16:44 +0100 von notifications@github.com  <notifications@github.com>:

**Comment by CAM-Gerlach** [comment]
Clearly a Python2-only Unicode error, that with the immanent end of life of that version and lack of further reports either has already been fixed at some point or is otherwise best fixed by upgrading to Python 3 if you want to use Unicode directory names. Closing this.
