### ISSUE TITLE
AttributeError at Spyder start

### ISSUE THREAD

**Issue by JakobJakobson** [spyder-ide/spyder#5573]
## Description
Spyder throws the error message shown below at startup after selecting automatic graphic backend.

**What steps will reproduce the problem?**

1. Fresh Fedora 26 installation.
2. Selecting the automatic graphics backend in the options.
3. Restarting Spyder.

**What is the expected output? What do you see instead?**
A normal Spyder startup is expected, instead Spyder throws an error window with the following message:

```python
  File "/usr/lib/python3.6/site-packages/qtconsole/base_frontend_mixin.py", line 163, in _dispatch handler(msg)
  File "/usr/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 417, in _handle_error
    super(ShellWidget, self)._handle_error(msg)
AttributeError: 'super' object has no attribute '_handle_error'
```

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.2 
* Python Version: 3.6.2
* Qt Versions: 5.7.1, PyQt5 5.8.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This was fixed in our **3.2.3** version. Please update.
