### ISSUE TITLE
Keras package - Kernel died, restarting

### ISSUE THREAD

**Issue by acoulon18** [spyder-ide/spyder#5579]
## Description of your problem

**What steps will reproduce the problem?**

1. Try to compile a project with the keras lib
2. Then kernel dies and restarts 2 or 3 times
3. And finally the program stops

**What is the expected output? What do you see instead?**
The expected output is the score of my neural network

**Please provide any additional information below**
On the logs viewer screen I got these errors : 

        "message": "Invalid url http://content.continuum.io/api/events",
        "method": "_download",
        "module": "download_api",
        "path": "C:/ProgramData/Anaconda3/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2017-10-26 08:31:08,437"
    
        "message": "Invalid url http://content.continuum.io/api/videos",
        "method": "_download",
        "module": "download_api",
        "path": "C:/ProgramData/Anaconda3/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2017-10-26 08:31:08,590"
    
        "message": "Invalid url http://content.continuum.io/api/webinars",
        "method": "_download",
        "module": "download_api",
        "path": "C:/ProgramData/Anaconda3/lib/site-packages/anaconda_navigator/api/download_api.py",
        "time": "2017-10-26 08:31:08,923"

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6
* Qt Version: 
* PyQt Version: 
* Operating system: Windows 10 64-bits

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

## My code
```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import urllib

import math
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD

def one_sample():
    x = np.array( [ 2.0*3.141592*np.random.ranf(), 2.0*np.random.ranf()-1 ])
    if (math.cos(x[0]) < x[1]):
        y = np.array([ 0, 1])
    else:
        y = np.array([1, 0])
    return x,y

def next_batch(n):
    x = np.zeros( shape=(n,2), dtype=np.float32)
    y = np.zeros( shape=(n,2), dtype=np.int32)
    for i in range(0, n):
        x[i],y[i] = one_sample()
    return x,y

def main():

    model = Sequential()
    # Dense(64) is a fully-connected layer with 64 hidden units.
    # in the first layer, you must specify the expected input data shape:
    # here, 2-dimensional vectors.
	#The last output has to be the number of class
    model.add(Dense(64, activation='relu', input_dim=2))
    model.add(Dropout(0.5))
    model.add(Dense(64, activation='relu'))
    model.add(Dropout(0.5))
    model.add(Dense(2, activation='softmax'))

    sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
    model.compile(loss='categorical_crossentropy',
                  optimizer=sgd,
                  metrics=['accuracy'])
				  
    training_epochs = 50
    for epoch in range(training_epochs):
        input_train, output_train = next_batch(128)
        model.fit(input_train, output_train, epochs=20, batch_size=128)
	
    x_test, y_test = next_batch(128)
    score = model.evaluate(x_test, y_test, batch_size=128)
    print("score=", score)
    
    single_x_test, single_y_result = one_sample()
    q = model.predict( np.array( [single_x_test,] )  )
    print(single_x_test, "is classified as ", q, " and real result is ", single_y_result)

if __name__ == "__main__":
        main()
```

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one.

**Comment by acoulon18** [comment]
I have tried to force the use of GPU with theano import and Nvidia config but it doesn't work. Is there an other solution ?
Thanks !

**Comment by andfoy** [comment]
@acoulon18 Does your code works outside Spyder?

**Comment by acoulon18** [comment]
@andfoy Yes it works ! For now it's ok but if you have some potential solutions I'm interested !

**Comment by ccordoba12** [comment]
@andfoy, does the code provided by @acoulon18 run for you?

**Comment by ccordoba12** [comment]
This error seems unrelated to Spyder, sorry.
