### ISSUE TITLE
Variable explorer randomly stops updating

### ISSUE THREAD

**Issue by I--P** [spyder-ide/spyder#5580]
## Description of your problem

Variable explorer randomly stops updating

**What steps will reproduce the problem?**

Finding a way to reproduce this problem reliably is a problem in itself

**What is the expected output?**

Variables in variable explorer

**What do you see instead?**

Variable explorer shows no variable at all, than starts working, the stops again, randomly.

**Please provide any additional information below**

I'm more asking for help in order to understand where the problem comes from rather than a bug fix as I'm not sure spyder is at fault here.
The setup is the following:
100+ users, each one on a PC running CentOS Linux release 7.4.1708, each user has its home directory mounted as a NFS share exported by redundant NFS servers (windows). 
There is one user per PC.
Spyder is installed locally on each PC, the only remote data come from the users' NFS home directory.
When all these users start using spyder at the same time the variable explorer works randomly, sometimes it won't update at all for hours, sometimes it works like a charm, sometimes it starts and stops working automagically between two runs of the very same python script.
Reseting spyder via --reset or deleting spyder data in .config does nothing.
It seems that when the network is not under load (i.e when there are just a few users in parallel rather than 100 or more) logging in using an user account who had problems with the variable explorer, running the same script, on the same PC, will usually result in a variable explorer working as expected.
Worse than that, if an user with a non working variable explorer logs **at the same time** on another PC (same hardware, same software) and runs the same script, there is no correlation between the behavior of the variable explorer on these two computers.
That's why I deeply suspect that there is some weird interaction between the new variable explorer/iPython console integration and the remote NFS shares used as home directories. With the old style variable explorer/python console we never had any problem with the reload button, but unfortunately this setup is not an option anymore.
Do you have any idea on where to look at to isolate this problem and hopefully find a solution ?
Thanks!

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: Python 3.6.1
* Qt Version: Qt 5.6.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.8.5 20150623 (Red Hat 4.8.5-16))
* PyQt Version:

pipdeptree -fl | grep -i qt
PyQt5==5.8.2
python-qt==0.50
  QtAwesome==0.4.4
    QtPy==1.3.1
  qtconsole==4.3.1
  QtPy==1.3.1

* Operating system:
CentOS Linux release 7.4.1708

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.2.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> That's why I deeply suspect that there is some weird interaction between the new variable explorer/iPython console integration and the remote NFS shares used as home directories.

We haven't tested this use case, so yes, this could be the problem.

Where is Python installed? Is it installed for each user in his/her home directory? Or are they using a global, unique Python to run Spyder and IPython?

**Comment by gabrielclow** [comment]
This has happened to me sometimes but I thought it was something with my work PC because I've never seen it happen on my home desktop or laptop. Just like OP, I have no clue how to reproduce it since it happened very randomly.
When it happened, it messed up the V Explorer inside one specific console tab and restarting the kernel would usually solve it. In general, the other console tabs behaved normally.
If I recall correctly, checking any of the options in the cog menu on the V Explorer had no effect whatsoever.

Spyder version: as far as I remember, it has been happening since 3.2+ or maybe a bit older
Python version: 3.6.x

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by I--P** [comment]
> Where is Python installed? Is it installed for each user in his/her home directory? Or are they using a global, unique Python to run Spyder and IPython?

Every PC has a full-fledge Centos installation, only the users' accounts are network dependents. Everything is configured as on a standard desktop computer, if you had a local user account on these PC you could login and notice no difference at all with any other Centos installation, and there is only one user at a time per PC.

In ~4 hours I'll have ~50 users using spyder, in the meantine if you can think of any test I could perform please tell me. Unfortunately the next opportunity to perform such test will be many weeks away (around mid november iirc).

**Comment by ccordoba12** [comment]
Well, you can run this command to see what results you get after detecting a failing Variable Explorer:

    get_ipython().kernel.get_namespace_view()

**Comment by I--P** [comment]
@ccordoba12  Aww ! I saw your comment too late ! I won't be able to give you the output of this command before mid november.
Anyway restarting the kernel seems to work, thanks @gabrielclow

**Comment by lampuiho** [comment]
My variable explorer stops updating after using "Run current cell".

**Comment by ccordoba12** [comment]
@lampuiho, are you running `%reset -f` in your cell?

**Comment by ccordoba12** [comment]
This no longer applies.
