### ISSUE TITLE
"Python has stopped working" crash some time after opening Spyder

### ISSUE THREAD

**Issue by jhcsu** [spyder-ide/spyder#5583]
## Spyder crashes with "Python has stopped working" at unpredictable intervals

**What steps will reproduce the problem?**

1. Start working with Spyder as usual.  Maybe run some programs, etc.  After a while, when your programs are done running and the iPython console is showing the prompt and waiting for some input, go get some coffee.  Come back, and occasionally discover the "Python has stopped working" message (Spyder has crashed).

**Please provide any additional information below**

This happens to me about once every other day since I started using Spyder recently.  It has never happened while I'm running a program in the iPython console, but that might just be a coincidence.

I have attempted ```spyder --reset```, and this has not resolved the problem.

Intermittent problems like this without obvious ties to other activities may be frustrating to track down.  If anyone can suggest some other info I might post, feel free.  The usual places (system.log, for example) don't have any references to the crash or other unusual activity on my machine at the time of the crash.

## Versions and main components

* Spyder Version: 3.2.4 (happened with 3.2.3 as well)
* Python Version: 2.7.13
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: MacOS 10.12.6

## Dependencies

IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.1 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
psutil >=0.3      :  5.2.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. There are several users who have reported crashes similar to this one in macOS 10.12.6 and 10.13.

Unfortunately, the only solution we can think of is updating Qt, the graphical toolkit used by Spyder. However, we can't do anything about it. It's up to Anaconda to do it, sorry.
