### ISSUE TITLE
some keyboard shortcuts can't work on my win 10

### ISSUE THREAD

**Issue by daxinnan** [spyder-ide/spyder#5586]
## Description

**What steps will reproduce the problem?**

1. I can't use Ctrl +1/2/4/5 to comment
2. But I can use other keyboard shortcuts normally.
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Those are probably used or reserved by the operating system.

@dalthviz, please take a look at this one.

**Comment by daxinnan** [comment]
I just can't use any keyboard shortcuts like Ctrl plus numbers. I don't know how to fix it.

**Comment by dalthviz** [comment]
Hi @daxinnan what is your current keyboard layout?, could you try to test if setting this shortcuts in other programs present the same problem?

**Comment by daxinnan** [comment]
Thank you！That's because the Input I use(one Double Pin Input Solution). When I change to use MS Input,I can use the keyboard shortcuts normally.But I don't know why it causes that, can we fix it?@dalthviz

**Comment by dalthviz** [comment]
I'm not quite sure if we can do something, but thanks @daxinnan for the feedback about the way you manage to make it work again the shortcuts in your setup 👍
