### ISSUE TITLE
Crash on profiler because of lack of profiler.results

### ISSUE THREAD

**Issue by amit-ruf** [spyder-ide/spyder#5587]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/amitruf/anaconda3/lib/python3.5/site-packages/spyder_profiler/widgets/profilergui.py", line 263, in <lambda>
    self.finished(ec, es))
  File "/home/amitruf/anaconda3/lib/python3.5/site-packages/spyder_profiler/widgets/profilergui.py", line 328, in finished
    self.show_data(justanalyzed=True)
  File "/home/amitruf/anaconda3/lib/python3.5/site-packages/spyder_profiler/widgets/profilergui.py", line 349, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "/home/amitruf/anaconda3/lib/python3.5/site-packages/spyder_profiler/widgets/profilergui.py", line 461, in load_data
    stats_indi = [pstats.Stats(profdatafile),]
  File "/home/amitruf/anaconda3/lib/python3.5/pstats.py", line 72, in __init__
    self.init(arg)
  File "/home/amitruf/anaconda3/lib/python3.5/pstats.py", line 86, in init
    self.load_stats(arg)
  File "/home/amitruf/anaconda3/lib/python3.5/pstats.py", line 99, in load_stats
    with open(arg, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/amitruf/.config/spyder-py3/profiler.results'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this problem in our 3.2.5 version.

**Comment by ccordoba12** [comment]
@rlaverde, please take a look at this one.

**Comment by rlaverde** [comment]
I can't reproduce it

@amit-ruf What were you doing when this issue occurred? What steps will reproduce it?

**Comment by amit-ruf** [comment]
I'm not sure, but I did install jupyter notebook support via this link:
https://github.com/spyder-ide/spyder-notebook
I just removed anaconda completely and reinstall. It solved the problem for
now.

**Comment by ccordoba12** [comment]
@rlaverde, this error has been reported several times, so we should catch `IOError` (so things work in Python 2 and 3) and see what action to take in that case (I'm not so sure what to do...).

**Comment by Lemming0815** [comment]
it should be noted that a crash due to missing profile.results file can be fixed by calling `reset_config_files() `from the `spyder.config.base` module.
