### ISSUE TITLE
Close parenthesis when unmatched

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5588]
## Description

When opening a parenthesis, spyder will automatically close it.
Because of that, when I close a parenthesis, it is automatically deleted.
But when I have unmatched parenthesis, I would like to be able to close without going to the end

example: (`|` is the cursor)
`fuc(fun(fuc(arg|))`

If I want to close this parenthesis in spyder, I must type `)))`
So is it possible to disable the parenthesis deletion when all the parenthesis are not matched on that line?

I know the parenthesis might be closed on another line but then I would not type `)`

## Version and main components

* Spyder Version: 3.2.5.dev0 c22566281
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is a valid request, but I don't know how we could solve it in all possible cases.

@rlaverde, what do you think about it?

**Comment by rlaverde** [comment]
Yes, I have also experience this issue. But I don't know how the logic of this works, I'll take a look to the logic and try to fix it.

**Comment by bcolsen** [comment]
I usually turn off bracket matching because of this.
