### ISSUE TITLE
Import numpy failed in ipython or default python interpreter.

### ISSUE THREAD

**Issue by H-Shen** [spyder-ide/spyder#5589]
## Description of your problem

**What steps will reproduce the problem?**

import numpy

**What is the expected output? What do you see instead?**
Import successfully with showing nothing.
ImportError.

**Please provide any additional information below**

Here's the contents of error when I imported numpy in Spyder:

import numpy as np
Traceback (most recent call last):

  File "<ipython-input-2-4ee716103900>", line 1, in <module>
    import numpy as np

  File "/home/shen/anaconda3/lib/python3.6/site-packages/numpy/__init__.py", line 146, in <module>
    from . import add_newdocs

  File "/home/shen/anaconda3/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc

  File "/home/shen/anaconda3/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *

  File "/home/shen/anaconda3/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx

  File "/home/shen/anaconda3/lib/python3.6/site-packages/numpy/core/__init__.py", line 24, in <module>
    raise ImportError(msg)

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: Python 3.6.3 :: Anaconda custom (64-bit)
* Qt Version: 5.6.2
* PyQt Version: PyQt5 5.6 on Linux
* Operating system: Linux Mint 18.2 sonya x86_64 Linux 4.8.0-53-generic

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please run

    conda install -f numpy

and try again. That should solve this error.
