### ISSUE TITLE
math in sphinxify has become huge

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#5597]
Hello,

After some recent updates the formulas have become too big.

![image](https://user-images.githubusercontent.com/17322580/32139065-da986fb0-bc3f-11e7-8162-2dd06ae51ca8.png)

**Comment by ccordoba12** [comment]
Please report all things we ask for in our issue template:

https://github.com/spyder-ide/spyder/blob/master/.github/ISSUE_TEMPLATE.md

Else, I'll simply close this issue for lack of info, sorry.

**Comment by kklmn** [comment]
## Versions and main components

* Spyder Version:  3.2.3
* Python Version: 3.6.1 64-bit
* Qt Version: 5.8.0
* PyQt Version: 5.8.1
* Operating system: Windows 10 64-bit

**Comment by goanpeca** [comment]
@dalthviz could you check if you can reproduce this issue?

**Comment by ccordoba12** [comment]
This was probably caused by the old MathJax version we were using until some months ago. Now this should be fixed.
