### ISSUE TITLE
sphinxify by other projects

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#5598]
Hello,

Probably you didn't intend to give sphinxify to external users, but we are actually using it. Sometimes it doesn't work though, e.g. it throws ExtensionError: "Could not import extension sphinx.ext.autosummary"
on Python 2.7 and Spyder in WinPython or Anaconda. 

If we had access to sphinxify's "confoverrides" dict, we would still be able to use the default sphinxify with
<pre>confoverrides = {'html_context': context, 'extensions': ['sphinx.ext.mathjax']} </pre>

Now we have to modify it locally.
Please include confoverrides to the parameters of sphinxify in the future releases.

Thanks!
Konstantin

**Comment by ccordoba12** [comment]
> Probably you didn't intend to give sphinxify to external users

Yes, we did. Please see:

https://github.com/spyder-ide/docrepr

We'll use that project instead of our current implementation since Spyder 4.

Please open an issue about `confoverrides` there, so we can address it.

**Comment by mje-nz** [comment]
So what's the status of docrepr now, is Spyder still planning to use it?

**Comment by ccordoba12** [comment]
Perhaps in Spyder 5, to be released next year.

**Comment by mje-nz** [comment]
Fair enough. Would you accept contributions?
