### ISSUE TITLE
Spyder 2.3.9

### ISSUE THREAD

**Issue by amilcaryaco** [spyder-ide/spyder#5599]
![spyder](https://user-images.githubusercontent.com/33187383/32139183-b760ac34-bc07-11e7-9024-07ea50215d59.png)

tengo un problema , el terminal IPython  no termina de conectarse con el nucleo .¿Como lo resuelvo ?

**Comment by ccordoba12** [comment]
Gracias por reportar este error. Lastimosamente, ya no soportamos Spyder 2.3.9. Por favor actualiza Spyder a su última versión, que es la **3.2.4**, y vuelve a intentarlo.
