### ISSUE TITLE
rename and then close notebook

### ISSUE THREAD

**Issue by ehiverson** [spyder-ide/spyder#5605]
## Description
I've experienced some odd behavior lately on Spyder. This particular problem was from closing a notebook that I had renamed using File -> Rename. However, after doing that action, the name represented by the tab did not change. And upon closing the window there is a FileNotFoundError. 
**What steps will reproduce the problem?**

1. Rename a notebook ( action not reflected by the name displayed in the tab)
2. close the tab 
3. 

**What is the expected output? What do you see instead?**
I'd expect the tab to close, but instead it gives this error. 

**Please provide any additional information below**

  File "c:\users\erik\appdata\local\programs\python\python35-32\lib\site-packages\spyder_notebook\notebookplugin.py", line 359, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "c:\users\erik\appdata\local\programs\python\python35-32\lib\site-packages\nbformat\__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Erik\\Documents\\Education\\Data Science\\Untitled.ipynb'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.7.1, PyQt5 5.7.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.27.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0

**Comment by ccordoba12** [comment]
Thanks for reporting. I'm moving this issue to our spyder-notebook repo because it belongs there.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #133](https://github.com/spyder-ide/spyder-notebook/issues/133) via [**ZenHub**](https://www.zenhub.com/)
