### ISSUE TITLE
Editor sets incorrect indent when character immediately before the break is a paren

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5606]
## Description

I've been having consistent issues with the  editor's automatic indents, that not only render it useless, but actively hinder in many situations. Specifically, when breaking a line, whenever the last non-whitespace character before the break is a parenthesis (which happens frequently when following the PEP8 recommendation to break before the operator), auto-indent sets an incorrect indent level for the following line, (the indent level of whatever statement on the previous line if after a close paren, or two tabs over if an open paren) and makes it very difficult to even manually fix every time—if I tab or space even one character past the desired position, backspace, shift-tab etc. will send me all the way back where I started. This is sufficiently problematic that the feature is a net loss in efficiency if left unfixed.

**What steps will reproduce the problem?**

1. Paste one of the example snippets below
2. Place cursor where indicated ("|")
3. Hit return/enter for a linebreak
4. Experience the joys and sorrows of trying to manually align it properly, with the auto-indent actively working against you if you slip up.

**What is the expected output? What do you see instead?**

Some contrived/minimal examples (cursor "|"):

**Works:**

_When the last char before a break isn't a paren, regardless of style_
Before Break:
```
if True:
    print(str(str("foo" |+ str("bar"))))
```
vs.
```
if True:
    print(str(str("foo" +| str("bar"))))
```
After Break (As Expected):
```
if True:
    print(str(str("foo" 
                  + str("bar"))))
if True:
    print(str(str("foo" + 
                  str("bar"))))
```

**Doesn't Work**

_When the last character before the break is a close paren, as is much more common when following PEP8 break before operator style, it doesn't work:_
Before Break:
```
if True:
    print(str(str(str("foo") +| "bar")))
```
vs.
```
if True:
    print(str(str(str("foo") |+ "bar")))
```
Expected After Break:
```

if True:
    print(str(str(str("foo") +
                  "bar")))

if True:
    print(str(str(str("foo") 
                  + "bar")))
```
Actual After Break for Second Case:
```
if True:
    print(str(str(str("foo") 
    + "bar")))
```

_Open Paren Case_
Before Break:
```
if True:
    some_long_variable_name = ("foo" + "bar")
```
Expected After Break (Yeah, not great style, but better than the actual):
```
if True:
    some_long_variable_name = (
        "foo" + "bar")
```
Actual After Break:
```
if True:
    some_long_variable_name = (
            "foo" + "bar")
```

_Another (slightly less minimal/contrived) example_
Before break:
```
if True:
    (print(str(("Long string " + "Yeah").|format(some_long_variable_name))
```
vs.
```
if True:
    (print(str(("Long string " + "Yeah")|.format(some_long_variable_name))
```
Expected After Break:
```
if True:
    (print(str(("Long string " + "Yeah").
               format(some_long_variable_name))))

if True:
    (print(str(("Long string " + "Yeah")
               .format(some_long_variable_name))))
```
Actual After Break for Second Case :
```
if True:
    (print(str(("Long string " + "Yeah")
    .format(some_long_variable_name))))
```

**Please provide any additional information below**

Experienced on multiple platforms since Spyder 3.2.2, when I started using it.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for the detailed bug report.

@rlaverde, please take a look at this one.

**Comment by rlaverde** [comment]
I can reproduce these ispsues, but the _Open Parent Case_ is theexcpected behavior, is the _hanging indent_, see :#3487

@ccordoba12 could It go to master instead of 3.x so I could also refactor indentation (using an editor extension)

**Comment by ccordoba12** [comment]
> is the expected behavior, is the hanging indent

Maybe we could then add an option to activate/deactivate hanging indentation?

> could It go to master instead of 3.x

Sure, no problem.

**Comment by CAM-Gerlach** [comment]
Ah, okay. I wasn't so sure about that one. However, is the following example the expected behavior? I.e. not picking up the indent level of the enclosing function? Just want to confirm...
```
test_variable = print(long_function_name(
        "foo", "bar"))
```
Thanks for looking at this!

**Comment by rlaverde** [comment]
>However, is the following example the expected behavior? I.e. not picking up the indent level of the enclosing function?

Yes, that's the expected behavior

>Maybe we could then add an option to activate/deactivate hanging indentation?

No, there's no way to deactivate it (It'll generate pep8 issues), see: https://github.com/spyder-ide/spyder/issues/3480#issuecomment-250394229

Maybe changing two only add two levels when defining a function (one level otherwise) will be the better, see https://www.python.org/dev/peps/pep-0008/#indentation

**Comment by CAM-Gerlach** [comment]
All sounds good; thanks so much to you both for looking into that aspect. The main thing that seemed odd was that it was two levels, not one, when I wasn't doing anything special (e.g. function definition) and I couldn't find anything in PEP8 about two levels except in such special cases, so hopefully that can be fixed assuming it isn't too tricky to check for def, etc. at the beginning of the line before adding two vs one tab. The close paren behavior is a more common problem at least in my code, and seems like a more explicit bug.

**Comment by CAM-Gerlach** [comment]
@rlaverde Hey, here are some more, different cases where Spyder isn't picking up the indents properly...cursor is `|`

After multi-line lists in function calls, similar behavior to close paren above (whether or not close paren or comma is present):
```
if True:
    io.merge_files_header(["CRNS0101-05-2010-CO_Cortez_8_SE.txt",
                           "CRNS0101-05-2011-CO_Cortez_8_SE.txt"],|
```
Expected after linebreak:
```
    io.merge_files_header(["CRNS0101-05-2010-CO_Cortez_8_SE.txt",
                           "CRNS0101-05-2011-CO_Cortez_8_SE.txt"],
                          |
```
Actual after line break:
```
    io.merge_files_header(["CRNS0101-05-2010-CO_Cortez_8_SE.txt",
                           "CRNS0101-05-2011-CO_Cortez_8_SE.txt"],
    |
```

Picking up function-level indent in certain situations even with close paren after function call; Example:
```
if True:
    station_fname_suffixes = ("-" + station_data["STATE"], + "_"
                              + station_data["LOCATION"].replace(" ", "_",
                                                                 regex=True)
                              + ".txt")|
```
Expected after break:
```
if True:
    station_fname_suffixes = ("-" + station_data["STATE"], + "_"
                              + station_data["LOCATION"].replace(" ", "_",
                                                                 regex=True)
                              + ".txt")
    |
```
Actual after break:
```
if True:
    station_fname_suffixes = ("-" + station_data["STATE"], + "_"
                              + station_data["LOCATION"].replace(" ", "_",
                                                                 regex=True)
                              + ".txt")
                              |
```

Thanks for looking into this!

**Comment by CAMGerlach-Baron** [comment]
Yet another (simplified) case; similar to the first one in the previous comment except with parens instead of brackets, and different behavior again: in this case, the next line will autoindent to be two tabs from the left margin, like an open paren (nominally only one for a function or class `def`, but presently in Spyder for any open paren as discussed above), regardless of the actual indent level of the previous statement.

```
data = pd.read_fwf(io.join_path("test" + ".txt",
                                SOME_CONSTANT),|
```
```
if True:
    if True:
        if True:
            if True:
                data = pd.read_fwf(io.join_path("test" + ".txt",
                                                SOME_CONSTANT),|
```
Expected:
```
data = pd.read_fwf(io.join_path("test" + ".txt",
                                SOME_CONSTANT),
                   |
```
```
if True:
    if True:
        if True:
            if True:
                data = pd.read_fwf(io.join_path("test" + ".txt",
                                                SOME_CONSTANT),
                                   |
```
Actual (two tabs from left margin regardless of prior indent)
```
data = pd.read_fwf(io.join_path("test" + ".txt",
                                SOME_CONSTANT),
        |
```
```
if True:
    if True:
        if True:
            if True:
                data = pd.read_fwf(io.join_path("test" + ".txt",
                                                SOME_CONSTANT),
        |

**Comment by CAMGerlach-Baron** [comment]
Yet another diverging case, again with brackets and commas in e.g. function calls...only this time, the comma actually does make a difference, behaving incorrectly when a comma is correctly present and "correctly" when a comma is not present (when it should be for syntactic correctness).

To keep things shorter but clearer, I'll illustrate four similar but slightly different (simplified) cases; in each case, before the line break, assume the cursor was at the end of the last non-empty line. The first case produces the expected outcome for all of them (the cursor aligned one col to the right of the open paren of the function call); the others do not. Thus:

At least one arg before last one, no comma after: Produces expected indent.
```
 if True:
    station_data = pd.read_fwf(encoding="utf-8",
                               usecols=["UTC_DATE", "UTC_TIME",
                                        "WIND_1_5"]
                               |
 ```

At least one arg before, comma after (*new case*): aligns indent as if I hadn't closed the array bracket.
```
if True:
    station_data = pd.read_fwf(encoding="utf-8",
                               usecols=["UTC_DATE", "UTC_TIME",
                                        "WIND_1_5"],
                                        |
```

First arg, comma or not: Same behavior as two comments up, first case (as it is essentially the same situation)...cursor is aligned to the same level as `station_data`, as if starting a new statement inside the if block.
