### ISSUE TITLE
Spyder error on opening object in Object Explorer while running debugger

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5607]
## Description

I got this error report on my work machine, but could not reproduce it after several attempts. Feel free to close of course if you can't either, but I figured I'd submit it in case it was helpful.

Was in ipdb, on a line of a function, and doubleclicked on an object to open it, a list with two strings (the first being the empty string `""`), and immediately received the error. However, the dialog opened successfully, Spyder continued to function normally, and nothing looked amiss. In an immediately previous debugging session on I believe the same code, I'd opened another object and didn't receive the message. Also, I had two variable explorer windows open in the background from a previous debugging session open (both of the same object). I attempted to open other objects afterwards, as well as the same object that cause, and they all worked with no errors reported.

**What steps will reproduce the problem?**

Attempted to reproduce by setting the same breakpoint, rerunning the debugger and opening the same object, but everything worked fine. I even tried opening some other objects in another debugging session, and in the main scope as before in case that was the issue, but to no avail. Therefore, unlikely this will be replicable/fixable unless the below automatic call stack trace provides any insight.

**What is the expected output? What do you see instead?**

Expected: To not see the error message.

Actual: Crash report-type error message issued (see below). Otherwise, everything appeared to function normally before, during and after.

**Please provide any additional information below**

Automatic error trace:
```
  File "C:\Users\christopher.gerlach\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 573, in setEditorData
    value = self.get_value(index)
  File "C:\Users\christopher.gerlach\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 1362, in get_value
    return self.get_value_func(name)
  File "C:\Users\christopher.gerlach\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 295, in get_value
    value = self.shellwidget.get_value(name)
  File "C:\Users\christopher.gerlach\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 94, in get_value
    raise ValueError(msg)
ValueError:     return dir_names
```

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 10 x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. I think we could safely remove the block code that generates this error.

But I'll have to carefully look at it :-)

**Comment by CAM-Gerlach** [comment]
No rush if its a nontrivial task; try as I might I was unable to reproduce the error, have only ever seen it once, and it had no apparent adverse effect.

**Comment by goanpeca** [comment]
@impact27 is this fixed with any of the work you did on the debugger?

**Comment by impact27** [comment]
Well as the code changed significantly since this issue I would say we can close it.
