### ISSUE TITLE
Update pandas in Spyder

### ISSUE THREAD

**Issue by kamrankausar** [spyder-ide/spyder#5610]
## Description of your problem
I want to update pandas to 0.18 or later. I am using pandas0.17 
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:Spyder 2.3.8
* Python Version:3.5.2
* Qt Version:
* PyQt Version:
* Operating system:Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by Jeroendevr** [comment]
I see you don't use the latest Spyder version. It is possible to upgrade to 3.2.4. By upgrading you distribution or 'pip install --upgrade spyder'

**Comment by ccordoba12** [comment]
Pandas is not part of Spyder, you have to update it separately, sorry.

**Comment by kamrankausar** [comment]
Thanks a lot. I fixed that issue
