### ISSUE TITLE
.spyder file installed in my Mac instead of a regular application

### ISSUE THREAD

**Issue by nalin-mathur** [spyder-ide/spyder#5611]
I installed spyder in my Mac using the anaconda distribution by the command 'conda install spyder'. However after installation my spyder ide is now in my /Users/username/.spyder  directory. 

How do I take it to my applications folder so that I can access spyder as a regular application instead of having it be a hidden file that I have to access through the terminal?

**Comment by ccordoba12** [comment]
I think you're a bit confused. `/Users/username/.spyder` is the place where Spyder setting are saved.

> How do I take it to my applications folder so that I can access spyder as a regular application instead of having it be a hidden file that I have to access through the terminal?

When you use Spyder with Anaconda, you have to start it from the command line or using Anaconda Navigator. Unfortunately, Spyder is not installed as a regular macOS application.
