### ISSUE TITLE
Variable explorer does not show empty lists.

### ISSUE THREAD

**Issue by Ossian50** [spyder-ide/spyder#5622]
## Description of your problem
The variable explorer only shows lists with items in them. If a list is created empty it's not in the variable explorer. Also, if a list is created then later emptied the list won't be shown in the variable explorer.
**What steps will reproduce the problem?**

1.  Create an empty list, e.g. $ theList = []
2.  Run the program
3.  Observe that theList is not in the variable explorer

**What is the expected output? What do you see instead?**
I think that the variable explorer should show lists that are empty.

**Please provide any additional information below**
Showing empty lists would facilitate debugging programs.

## Versions and main components

* Spyder Version: 3.2.1
* Python Version: 3.6.0
* Qt Version: 5.6.2
* PyQt Version:  1.2.1
* Operating system: Windows 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.0.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.5 (OK)
sympy >=0.7.3    :  1.0 (OK)

![image](https://user-images.githubusercontent.com/16084857/32235220-7cd8c262-be24-11e7-9510-59166ecbaea2.png)

**Comment by ccordoba12** [comment]
This was fixed in our 3.2.4 version. Please update.
