### ISSUE TITLE
Error prompt every time I attempt to switch to the terminal window

### ISSUE THREAD

**Issue by johnstrada** [spyder-ide/spyder#5625]
## Description

**What steps will reproduce the problem?**

1. open spyder
2. click terminal window

**What is the expected output? What do you see instead?**
working terminal window
Instead, a grey window area only

**Please provide any additional information below**

  File "/anaconda3/lib/python3.6/site-packages/spyder_terminal/terminalplugin.py", line 315, in create_new_term
    font=font.family())
  File "/anaconda3/lib/python3.6/site-packages/spyder_terminal/widgets/terminalgui.py", line 63, in __init__
    self.view = TermView(self, term_url=url, handler=self.handler)
  File "/anaconda3/lib/python3.6/site-packages/spyder_terminal/widgets/terminalgui.py", line 147, in __init__
    self.document.profile().clearHttpCache()
AttributeError: 'QWebEngineProfile' object has no attribute 'clearHttpCache'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by Jeroendevr** [comment]
`QWebEngineProfile` Could indicate is has something to do with the Qt framework. Could you try to update PyQt using `conda update PyQt`

**Comment by ccordoba12** [comment]
This is a bug in `spyder-terminal` and it was fixed in its latest release. Please update.

**Comment by johnstrada** [comment]
Hi Carlos, I did this but am still getting the error message. Additionally, the terminal window now looks like the following (attached).

![screen shot 2017-11-01 at 1 35 55 pm](https://user-images.githubusercontent.com/33262139/32291049-ec7eed54-bf09-11e7-8c45-e4a0880fa42a.png)

**Comment by ccordoba12** [comment]
Please open an issue in spyder-terminal about it:

https://github.com/spyder-ide/spyder-terminal
