### ISSUE TITLE
Kivy module not recognized as a package by Spyder

### ISSUE THREAD

**Issue by leodavinci111** [spyder-ide/spyder#5645]
## Description of your problem

**What steps will reproduce the problem?**

1. Create a new environment
2. install Kivy module  via pip, with all dependencies
3. open and run a 'button' test file as described [here](https://kivy.org/#home)

**What is the expected output? What do you see instead?**
Expected to run the app but 'No module named 'kivy.app'; 'kivy' is not a package' instead

**Please provide any additional information below**

## Versions and main components

* Spyder Version:3.2.4 
* Python Version:3.6.3
* Qt Version:5.6.2
* PyQt Version:5.6.0 
* Operating system:Ubuntu 16.04
* Kivy version is 1.10.0

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by leodavinci111** [comment]
forgot to add that i am able to import and run the kivy module on the terminall without errors. The module is installed inside the site-packages. I did try to add the kivy folder to the PATH, no success.

**Comment by ccordoba12** [comment]
Sorry, this is an installation problem and not a Spyder bug. Due to that, I'm closing it.

**Note**: People have reported some limitations trying to develop Kivy apps with Spyder, so we recommend you to use another IDE. We specialize in scientific/engineering applications, and so we don't have the time to improve our interoperability with Kivy, sorry.
