### ISSUE TITLE
Unable to open preferences after fresh install with Qt 5.9.2

### ISSUE THREAD

**Issue by kov-serg** [spyder-ide/spyder#5649]
## Description

**What steps will reproduce the problem?**

1. Start spyder
2. Open Инструменты/Параметры ( Tools/Preferences )
3. Or press Ctrl+Alt+Shift+P

**What is the expected output? What do you see instead?**
Open settings

**Please provide any additional information below**

  File "c:\apps\dev\python36\lib\site-packages\spyder\app\mainwindow.py", line 2610, in edit_preferences
    dlg.add_page(widget)
  File "c:\apps\dev\python36\lib\site-packages\spyder\plugins\configdialog.py", line 234, in add_page
    widget.apply_button_enabled.connect(self.apply_btn.setEnabled)
AttributeError: 'NoneType' object has no attribute 'setEnabled'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by kov-serg** [comment]
I've found the solution.
1. remove cache file configdialog.*.pyc (in my case lib\site-packages\spyder\plugins\__pycache__\configdialog.cpython-36.pyc )
2. modify configdialog.py (located in lib\site-packages\spyder\plugins\ )
line 148:

from

    self.apply_btn = bbox.button(QDialogButtonBox.Apply)

to

    bbox.addButton(QDialogButtonBox.Apply)
    self.apply_btn = bbox.button(QDialogButtonBox.Apply)

and restart spyder3

ps: is set PYTHONDONTWRITEBYTECODE=1 python will compile on the fly with out writing cache directories

**Comment by ccordoba12** [comment]
Thanks for the solution. We'll implement it in 3.2.5.

**Comment by jnsebgosselin** [comment]
This is strange. I'm not able to reproduce this bug on 3.2.5.dev() on my setup.
 `bbox.button(QDialogButtonBox.Apply)` is returning a `PyQt5.QtWidgets.QPushButton object` as expected.

## Version and main components
Python 3.6.2 64bits, Qt 5.9.2, PyQt5 5.9.1 on Windows 7

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
It seems this error was caused by an old build of PyQt5, since no one else has reported it lately.
