### ISSUE TITLE
Getting this while opening spyder on Mac OS Sierra 10.12.6

### ISSUE THREAD

**Issue by shridude** [spyder-ide/spyder#5656]
## Description

**What steps will reproduce the problem?**

1. Open terminal
2. Type "spyder" to open spyder in python path

**What is the expected output? What do you see instead?**
Got error window after Spyder opens but console never starts, keeps spinning.

**Please provide any additional information below**

AttributeError: Queue instance has no attribute 'put'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is an installation with one of Spyder dependencies. Please post the entire error message and not only the last line.

**Comment by shridude** [comment]
This happened with the Mac OS graphical installer. I did a clean and
reinstall with command line installer and it worked.

**Comment by ccordoba12** [comment]
Thanks for letting us know about it.
