### ISSUE TITLE
Feature request: use tab key to navigate in find/replace

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#5658]
Is it possible to add a feature to use tab key to navigate in find/replace?

Right now, pressing ctrl+R brings out find/replace, and I can type the word to be replaced right away, but when I want to type the new word that is used to replace the old, I need to use the mouse.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a duplicate of #3674 and we're working to implement it in our 3.2.5 version.
