### ISSUE TITLE
python stopped  working

### ISSUE THREAD

**Issue by prabhakarmakam** [spyder-ide/spyder#5659]
## Description of your problem

**What steps will reproduce the problem?**

1. after downloading anaconda
2. i tried launching spyder
3. it throws error message python has stopped working 

**What is the expected output? What do you see instead?**
it should launch spyder

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:windows ultimate 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Sorry but you provided too little information to help you.

Please try to deactivate your antivirus/firewall and try again. That's the only advice I can give you.
