### ISSUE TITLE
Spyder crashing when closing IPython console

### ISSUE THREAD

**Issue by shaiay** [spyder-ide/spyder#5660]
- Open some (say 3 ) consoles
- start closing them
- At some point spyder will crash, sometimes after the first close, sometimes after the third ...

Is there any way to get a logfile from spyder to help debug?

Spyder 3.2.4, Python 2.7.10 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Windows 

Dependencies:
IPython >=4.0;<6.0:  5.5.0 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.1 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.5 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Please update to use Qt5/PyQt5 instead of Qt4/PyQt4. We've heard several bugs like this one are fixed in PyQt5.
