### ISSUE TITLE
Symbol finder gives error message

### ISSUE THREAD

**Issue by JakobJakobson** [spyder-ide/spyder#5661]
## Description

**What steps will reproduce the problem?**

1. Move the Spyder config folder that you have a clean start.
2. Open "Symbol finder" (Ctrl+Alt+P)
3. "Symbol finder" opens.
4. Click somewhere else than the "Symbol finder window".
5. The error message below pops up.

**What is the expected output? What do you see instead?**
Ooening and closing the "Symbol finder window" by clicking somewhere else should close the "Symbol finder window" just normally, instead a error windows pops up.

**Please provide any additional information below**

  File "~/SpyderBug/spyder/spyder/widgets/fileswitcher.py", line 397, in restore_initial_state
    for path in self.initial_cursors:
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 4.0.0.dev0 5083a69fb
* Python Version: 3.6.2
* Qt Versions: 5.7.1, PyQt5 5.8.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
@dalthviz, I think this error was introduced by you. Please take a look at it.
