### ISSUE TITLE
Facing problem in importing Self defined module

### ISSUE THREAD

**Issue by rpiryani** [spyder-ide/spyder#5663]
I am using Spyder 3.2.4
I have created module A and create the file name b.py. In b.py I have created "class B():

Now I am importing above defined class

from A import B

I am getting error
ImportError: cannot import name 'B'

How to resolve this issue.

**Comment by ccordoba12** [comment]
Sorry, this is a Python programming problem, not a Spyder bug or limitation. Please ask for help somewhere else.
