### ISSUE TITLE
Strange font rendering in the splash

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#5667]
## Description of your problem

The spyder splash looks like this on Ubuntu:

![current_splash](https://user-images.githubusercontent.com/10513354/32428257-1311b584-c282-11e7-8423-9662026a5123.png)

This is the same for spyder 3.

In the splash SVG file `splash.svg`, I can see that the font is set to Candara, one of the Microsoft "*C*" fonts, which is not available on my system. This font will be unavailable to anyone that is either not on windows or doesn't have Microsoft Office installed.

Unfortunately embedding Candara in the SVG or distributing it with Spyder is, most likely, against the font's license.  Embedding fonts in SVG is also not well supported.

## Potential Solution

Inkscape can be used to convert SVG text to a path.  The font will no longer be editable but the font forms will be the same on all systems regardless of installed fonts.

## Suggestion

As a suggestion, an open licensed font such as [Quattrocento Sans](https://fonts.google.com/specimen/Quattrocento+Sans) could be used instead,  but the text should still be converted to a path.

![proposed_splash](https://user-images.githubusercontent.com/10513354/32428700-5ef7004c-c284-11e7-889f-ecba2d8953fd.png)

**Comment by ccordoba12** [comment]
The splash looks fine for me on Kubuntu 16.04.

**Comment by bcolsen** [comment]
It must be defaulting to a different font on your computer than mine.  Unless you have Candara font installed.

Here is were it uses Candara font in the SVG:

https://github.com/spyder-ide/spyder/blob/4d1447aa426582e7ae20554f9f51beb14604a3fe/spyder/images/splash.svg#L408

I can submit a patch that uses Quattrocento Sans(I don't have Canadara) and converts the SVG text to a path so the display is always the same regardless of installed font.

Current Splash:

![current_splash](https://user-images.githubusercontent.com/2024217/30523837-885dd886-9bae-11e7-9322-8ae8a2c7c3a2.png)

Proposed Spash:

![proposed_splash](https://user-images.githubusercontent.com/10513354/32428700-5ef7004c-c284-11e7-889f-ecba2d8953fd.png)

**Comment by rlaverde** [comment]
>I can submit a patch that uses Quattrocento Sans(I don't have Canadara)

I think this is a good idea, since Candara is propietary

>converts the SVG text to a path so the display is always the same regardless of installed font.

Yes, this is the solution

But we also need to save the file without the conversion, so when changing again (maybe 4 to 5) it will be easy

**Comment by bcolsen** [comment]
> But we also need to save the file without the conversion, so when changing again (maybe 4 to 5) it will be easy

I can include a copy of the splash that has the text as "splash_edit.svg"

**Comment by ccordoba12** [comment]
Good idea! Thanks for helping us with this one @bcolsen!
