### ISSUE TITLE
Spyder Variable Explorer Memory Leak

### ISSUE THREAD

**Issue by zoebchhatriwala** [spyder-ide/spyder#5669]
## Description
Spyder Variable Explorer leaks memory utilizes full ram and freezes computer to death.

**What steps will reproduce the problem?**

1. Create a sparse matrix of >= 10000 rows X 1000 columns.
2. Go to variable explorer and select the sparse matrix variable.
3. Double click, open it and scroll to the end.
4. Press 'OK' button below.
5. Immediately check Task Manager | Resource Manager
6. Inspect pythonw.exe
7. See process filling up memory exponentially
8. Computer freezes to death after 99% memory consumption.

**What is the expected output? What do you see instead?**
- There should not be 99% memory consumption.
- sparse matrix is not thee culprit. It also happens with large data-sets.

**Please provide any additional information below**
- It only happens if you click 'OK' - Step 3, 4 

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Please post the code you used to create your sparse matrix.

**Comment by ccordoba12** [comment]
That's not complete. Please post a complete example, and if you are able to reproduce this with simple Numpy arrays, the better.

**Comment by zoebchhatriwala** [comment]
You could easily recreate it by creating a sparse matrix of 1000 X 10000.

Try with this:

`
import numpy as np
sparse = np.mgrid[0:1000,0:1000].swapaxes(0,2).swapaxes(0,1)
`
use this code and follow all steps above.

**Comment by ccordoba12** [comment]
I can't reproduce this problem, sorry.

**Comment by ccordoba12** [comment]
Sorry, I think I closed this one too fast. Please see #5830.

**Comment by zoebchhatriwala** [comment]
Hi, Yes that's the same problem I am facing. It's not a problem as clicking cancel or close prevent it from happening. but If it is fixed it would be good so anyone else doesn't face it.
