### ISSUE TITLE
After updating Parso to 0.1.1 Spyder 3.2.4 crash

### ISSUE THREAD

**Issue by IgnacioRubioScola** [spyder-ide/spyder#5673]
## Description of your problem
After updating Parso to 0.1.1 Spyder crash

**What steps will reproduce the problem?**

1. Update Parso to 0.1.1
2. Launch Spyder 3

**What is the expected output? What do you see instead?**

  File "/home/ign/.pyenv/versions/3.6.3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 872, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (parso 0.1.1 (/home/ign/.pyenv/versions/3.6.3/lib/python3.6/site-packages), Requirement.parse('parso==0.1.0'), {'jedi'})

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5
* PyQt Version: 5.9
* Operating system: Ubuntu 17.10 Kernel 4.13

**Comment by IgnacioRubioScola** [comment]
The problem comes from the "jedi" package, it should be updated soon...

**Comment by ccordoba12** [comment]
It seems Jedi requires Parso 0.1.0, so please downgrade.
