### ISSUE TITLE
PYTHONPATH manager: unable to add paths in `/usr` in macOS

### ISSUE THREAD

**Issue by DSLituiev** [spyder-ide/spyder#5679]
## Description of your problem

**What steps will reproduce the problem?**

1. Open PYTHONPATH manager on Mac 10.12.6 / Spyder 3.1.4 
2. No way to add / manually type paths that are hidden from user

**What is the expected output? What do you see instead?**

Option to manually paste / type the path

## Versions and main components

* Spyder Version: Spyder 3.1.4 
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system: Mac 10.12.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by goanpeca** [comment]
@DSLituiev if you use the latest of Spyder, is this problem still there?

**Comment by ccordoba12** [comment]
That's not our problem. Most probably the directory is not accessible from the macOS File dialog. If that's the case, we can't do anything about it, sorry.

@goanpeca, can you verify?

**Comment by goanpeca** [comment]
>Most probably the directory is not accessible from the macOS File dialog. If that's the case, we can't do anything about it, sorry.

Correct, it is not.

@DSLituiev its a mac thing... you can do

https://apple.stackexchange.com/questions/118186/how-to-browse-usr-in-an-open-file-dialog
