### ISSUE TITLE
Bug: Find and Replace indicate "no matches" when "[", "(", or ")" included in the search string

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5680]
## Description

When using both the "Find" and the "Replace" feature, I noticed that whenever my search string included a "[", "(" or ")" (but not a "]", "{", or "}"), the UI will claim "no matches" even though it can still actually find them. I've tried this in large (1,000 line) files with hundreds of these characters, and in no circumstances will it display any matches, though it will still find them (making this less critical). 

**What steps will reproduce the problem?**

1. Ensure focus is on a file with these characters (minimal example:)
```
{foo}
{bar}
[foo]
[bar]
(foo)
(bar)
```
2. Bring up Find or Replace dialogs
3. Search for, e.g. "[", "[foo]", "(bar)"; observe match count

**What is the expected output? What do you see instead?**
For e.g. "[" on the above, expected: 1 of 2 , actual: no matches;
For "(foo)", expected: 1 of 1, actual: no matches.
Etc. for any string containing "(", "[", and/or ")" regardless of what other characters it contains.

**Please provide any additional information below**

Reproduced on multiple spyder installs, machines and OS platforms.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 Pro x64 and Win 10 Ent x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a a look at it in a future release.
