### ISSUE TITLE
ipython console left parenthesis delay

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#5690]
In ipython console, there is some delay (less than one second, but still tangible) when I press the left parenthesis key `(` to enter the left parenthesis character, after a function name.

For example, I have entered `pd.DataFrame` into the ipython console, and now I press `(`, then there is some delay when `(` shows in the console, because the balloon tool tip takes some time to appear.

This has caused me frequent issues when I want to do something like `object.get_attribute()`.  I usually press `(` and then press `)` very fast (as we all do!), but with such a delay, I always end up getting `object.get_attribute)(`, because `(` gets delayed and shows up after `)`.

## Versions and main components

* Spyder Version: 3.2.3
* Operating system: windows 10

**Comment by ccordoba12** [comment]
We improved this a little bit in Spyder 3.2.4, but if after updating it still bothers you, you can deactivate it in

    Preferences > IPython console > Display > Display ballon tips

It only happens when you have big Dataframes or NumPy arrays, and there's little we can do about it for now, sorry.
