### ISSUE TITLE
Connecting with virtual envs supported?

### ISSUE THREAD

**Issue by dalito** [spyder-ide/spyder#5692]
## Description of problem

I wanted to connect spyder with a virtual environment (VE). Spyder is only installed in "main" python (C:\dev_amd64\Python36) but not in the VE "myve". I installed ipykernel in the VE and set the python interpreter in Tools/Proferences/Python Interpreter to python.exe in the VE.

In the IPython shell in can see that the paths for the VE were added but surprisingly  `c:\\dev_amd64\\python36\\lib\\site-packages` from the main python is also on sys.path:
```
In [1]: import sys
In [2]: sys.path
Out[2]: 
['',
 'c:\\dev_amd64\\python36\\lib\\site-packages',
 'c:\\dev_amd64\\python36\\lib\\site-packages\\spyder',
 'C:\\dev_src\\_pyve\\myve\\Scripts\\python36.zip',
 'C:\\dev_amd64\\Python36\\DLLs',
 'C:\\dev_amd64\\Python36\\lib',
 'C:\\dev_amd64\\Python36',
 'C:\\dev_src\\_pyve\\myve',
 'C:\\dev_src\\_pyve\\myve\\lib\\site-packages',
 'c:\\dev_amd64\\python36\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\david\\.ipython']
```
So the VE is not isolated. Is this intended? Am I trying something that is not supported?

For comparison, VE activated from a Windows command prompt:
```
C:\Users\david>c:\dev_src\_pyve\myve\Scripts\activate.bat
(myve) C:\Users\david>py
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 18:11:49) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 
'c:\\dev_src\\_pyve\\myve\\Scripts\\python36.zip', 
'C:\\dev_amd64\\Python36\\DLLs', 
'C:\\dev_amd64\\Python36\\lib', 
'C:\\dev_amd64\\Python36', 
'c:\\dev_src\\_pyve\\myve', 
'c:\\dev_src\\_pyve\\myve\\lib\\site-packages']
>>>
```
## Version and main components
* Spyder Version: 3.2.4
* Python Version: 3.6.3 (tried also 2.7.14)
* Qt Version: 5.9.2
* PyQt Version: 5.9.1
* Operating system: Win 10 Pro German
* Dependencies:
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.1 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  None (NOK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. This will be possible in Spyder 4, but most probably with conda environments at the beginning. For now, there's nothing we can do about it, sorry.

**Comment by dalito** [comment]
Thanks for the reply. For others with the same question: related issue #1575 (and maybe also #5441). 

I would appreciate if standard VEs could be also supported. Not everyone can/wants to use conda. As a first step, it would be already very nice if VEs created outside of Spyder could be used.
