### ISSUE TITLE
Variable Explorer windows don't close when Spyder exits; prevents it from reopening until manually closed

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5696]
## Description

Recently, I've experienced issues on my Windows 8.1 Pro x64 and Windows 10 Ent x64 machines where Spyder will mysteriously not launch (from the start menu icon) with no indication as to why, only on close inspection to find a variable explorer window hidden somewhere that hasn't closed when Spyder exits (as it presumably should). As far as I'm aware, _any_ open variable explorer window, regardless of type, on Spyder exit will stay open and trigger this behavior; Spyder will only launch after every such window is manually tracked down and closed. 

As the windows have little to no function when Spyder is not open, it seems they should be terminated along with their parent application. Perhaps something to do with them have a dialog-type UI, rather than a normal window? No clue; not a GUI programmer.

**What steps will reproduce the problem?**

1. Double click on a suitable variable name in the main variable explorer to open a variable explorer window,
2. Close Spyder.
3.  Attempt to relaunch via start menu shortcut without closing variable explorer sub windows

**What is the expected output? What do you see instead?**

Expected: Variable explorer windows close along with Spyder, and the latter is able to then launch normally after doing so.

Actual: Variable explorer windows do not close with spyder and stay in the background, often hidden, and prevent Spyder from relaunching. 

**Please provide any additional information below**

Reproduced on multiple OS versions/Spyder installs/physical machines.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 Pro x64 and Windows 10 Ent x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. According to

https://stackoverflow.com/q/2216711/438386

the fix seems simple. We'll take a look at it in a future release.
