### ISSUE TITLE
Spyder returns an error when trying to open a new file

### ISSUE THREAD

**Issue by ginsanity15** [spyder-ide/spyder#5699]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\bobgao\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\plugins\editor.py", line 1712, in new
    text, enc = encoding.read(self.TEMPLATE_PATH)
  File "C:\Users\bobgao\AppData\Local\Continuum\anaconda2\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
IOError: [Errno 2] No such file or directory: u'C:\\Users\\bobgao\\.spyder\\template.py'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25

**Comment by ccordoba12** [comment]
Please run in a terminal (cmd.exe)

    spyder --reset

and try again. That should fix this error.
