### ISSUE TITLE
Spyder incompatible with CUDA drivers

### ISSUE THREAD

**Issue by coolydudey60** [spyder-ide/spyder#5710]
## Description of your problem
spyder3 and spyder4 segfault on start when using NVidia CUDA drivers in Linux. However spyder2 (installed via apt-get) works fine. Issue occurs either with pip install or when running from source. Issue is similar to https://github.com/spyder-ide/spyder/issues/4495.

**What steps will reproduce the problem?**

1. pip install spyder or run spyder from source (with NVidia CUDA installed)
2. attempt to run spyder
3. segfault, resulting in core dumped. If running from source, the error` Could not initialize GLX` appears before the segfault.

**Please provide any additional information below**

Following these instructions resolved the issue:
 https://stackoverflow.com/questions/42291236/python-spyder-could-not-initialize-glx 
However, this removes CUDA, and the problem resumes when CUDA is reinstalled.
## Versions and main components

* Spyder Version: 3.2.4 or 4.0
* Python Version: 3.5.2
* Qt Version: 5.9
* PyQt Version: 5.9
* Operating system: XUbuntu 16.04

**Reproducibility**

I am accessing this machine using a remote desktop setup, and the NVidia Card is not actually the display device, only used for development purposes.

**Comment by ccordoba12** [comment]
This is a problem with Qt, not with directly with Spyder. We added a hack to try to solve this with PyOpenGL, but it seems that's not enough, sorry.

Besides not using CUDA, your other choice is to use Anaconda, which doesn't have this problem.

**Comment by coolydudey60** [comment]
Ok thanks. Any idea why it works with Spyder 2 though?

**Comment by ccordoba12** [comment]
Because it doesn't use Qt5.

**Comment by silentquasar** [comment]
Things seem to work fine downgrading to qt 5.6.2--not sure if intermediate version work. 5.9 definitely doesn't. Anyone know of a QT issue that we can follow to track this? So far, I've just found this: https://devtalk.nvidia.com/default/topic/1023403/linux/could-not-initialize-glx-with-nvidia-384-66-on-ubuntu-16-04/

**Comment by saymudeen** [comment]
![Uploading 16222057858762946345815372267427.jpg…]()


I uninstalled some unwanted applications from laptop, afterwards I couldn't even open the anaconda navigator after clicking it's icon, also tried in anaconda prompt, it didn't work
