### ISSUE TITLE
"Show blank spaces" with split view editor 

### ISSUE THREAD

**Issue by msancheznet** [spyder-ide/spyder#5711]
## Description of your problem

**What steps will reproduce the problem?**

1. Open a file in Spyder and create a split view in the editor
2. In the left copy of the file, click "Source" -> "Show blank spaces". This adds marking to left copy of the file.
3. Click on the right copy of the file, which does not have the "blank spaces" markings
4. Click on "Source" again, and the tick for "Show blank spaces" remains active even though it is not for this part of the split view

**What is the expected output? What do you see instead?**
I would expect the "Show blank spaces" to either:
1) Be synchronized with the view that the user is currently focusing on in the editor 
2) Activate/deactivate the markings in all views at the same time.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.2
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by csabella** [comment]
I cannot recreate this.  When I follow the steps to recreate it,  after I click on 'Show Blank Spaces', both panels show the markings, so they are synchronized.  If I unclick the Show Blank Spaces, the markings go away.  I tried doing both from each panel.

I'm on Linux though, so either this might be a Windows-only issue or it was fixed on a recent release.

**Comment by msancheznet** [comment]
Maybe an earlier release fixed part of the problem but I can still recreate like this:

1. Open a file in Spyder and create a split view in the editor
2. Open two files, let's say "file 1.py" and file 2.py".
3. Select "file 1.py" on the left view and "file 2.py" on the right view
4. Click on the left view, then  "Source" -> "Show blank spaces". This adds markings only on the left view.
5. Click on the right view (containing file 2.py, no markings)
6. Go to "Source" -> "Show blank spaces". Notice how the "Show blank spaces" tick is on even though the cursor is in file that does not show markings

**Comment by csabella** [comment]
Thank you for the new information.  It seems that with two files, a split screen isn't even needed to recreate the issue.  When the `Show blank spaces` is clicked, it only affects the file being edited and not the other ones that are open.

This does not seem to be an issue in Spyder 4.0 (master branch) as all the source files show the blank spaces when the checkbox is clicked.  Although, I couldn't find the exact project that resulted in the fix as there are many new options add to the Source menu for the future release.

**Comment by ccordoba12** [comment]
@csabella, @rlaverde fixed that in master by making all entries in the Source menu to apply to all files and also save the change in our config system.

I'm closing this since it's already solved.
