### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by sagarlkhmn** [spyder-ide/spyder#5713]
## Description of your problem
An error ocurred while starting the kernel
C:\Users\REALSYS3\Anaconda3\lib\site‑packages\Sphinx𔂫.6.3‑py3.6.egg\sphinx\util\compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
RemovedInSphinx17Warning)
Traceback (most recent call last):
File "C:\Users\REALSYS3\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 245, in 
main()
File "C:\Users\REALSYS3\Anaconda3\lib\site‑packages\spyder\utils\ipython\start_kernel.py", line 213, in main
from ipykernel.kernelapp import IPKernelApp
File "C:\Users\REALSYS3\Anaconda3\lib\site‑packages\ipykernel\kernelapp.py", line 15, in 
from tornado import ioloop
File "C:\Users\REALSYS3\Anaconda3\lib\site‑packages\tornado\ioloop.py", line 47, in 
from tornado.concurrent import TracebackFuture, is_future
File "C:\Users\REALSYS3\Anaconda3\lib\site‑packages\tornado\concurrent.py", line 34, in 
from tornado.util import raise_exc_info, ArgReplacer, is_finalizing
ImportError: cannot import name 'is_finalizing'

**What steps will reproduce the problem?**

1. Start the spyder ide
2. It fails to connect to kernel and displays the above error
3. 

**What is the expected output? What do you see instead?**
Expected output is ipython kernel gets connected easily

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 10 home

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
Please run in a terminal (cmd.exe), after closing Spyder

    conda install -f tornado

to fix this error.

**Comment by sagarlkhmn** [comment]
Thanks!! It works now. Appreciate it. 👍
