### ISSUE TITLE
Spyder console freezes whenever a traceback error is thrown

### ISSUE THREAD

**Issue by ggiesa** [spyder-ide/spyder#5715]
## Description

**What steps will reproduce the problem?**
Any traceback error will cause the spyder console to freeze. ctrl+d, and %reset won't restart the kernel after this happens. It seems that manually clicking the 'x' button on the console tab is the only thing that works to restart. 

**Please provide any additional information below**
I know that other users have experienced this issue before in past versions of spyder. This started happening to me fairly recently, like 11/5/17 or so, with no issues before that point. 

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This was fixed in our 3.2.2 version. Please update.
