### ISSUE TITLE
Create conda packages for lua-lsp

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#5719]
As part of the LSP effort by @andfoy we should get a grasp of another couple of LSP. Lua could be one of those languages we support.

https://github.com/Alloyed/lua-lsp

**Comment by andfoy** [comment]
I have to inspect if it allows communication over TCP, otherwise we'll have to wait until we implement the stdio transport logic

**Comment by goanpeca** [comment]
>I have to inspect if it allows communication over TCP, otherwise we'll have to wait until we implement the stdio transport logic

We still need the packages, so this can be done in parallel...!

**Comment by ccordoba12** [comment]
Closing because who knows when we'll have time to do this.
