### ISSUE TITLE
Code folding

### ISSUE THREAD

**Issue by karimnorouzi** [spyder-ide/spyder#5724]
I am anticipating code folding a lot. Is there a way for the code folding to be included in the next upcoming release? (ie ASAP ? )

**What steps will reproduce the problem?**

1.  code folding is important for project development.
2.  I like spyder and don't want to move to other platforms
3.  Need code folding, really :)

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Code folding is going to be part of Spyder 4, to be released on Q2 of next year.

**Comment by jakeelove** [comment]
Hi so its 2018, is there a a code folding option in spyder?

**Comment by ccordoba12** [comment]
No yet, you'll have to wait until 2019.

**Comment by jakeelove** [comment]
Oho thank you

**Comment by MIKKELLORENZ** [comment]
I love spyder but at the moment I'm dividing my code into severals scripts as otherwise it becomes unbearable. So i'm supporting this code folding too! Much love! Can't wait for the update.

**Comment by robsomething** [comment]
Just have to say Hooray for code folding!  so far so good and it works intuitively and easy peasy :)

**Comment by MIKKELLORENZ** [comment]
Just manage to get the 4.0 beta. How can't documentation on how to do the folding xD. Anyone who can provide some help?

P.S In the launch picture it says "Spyder 4", but when the IDE opens it says Spyder 3.6 everywhere. Is this just some artifact that hasn't been changed?
