### ISSUE TITLE
does spyder3 support variable-exploring when using the remote jupyter/ipython kernel?

### ISSUE THREAD

**Issue by mongoose64** [spyder-ide/spyder#5726]
## Description of your problem

1. does spyder3 support variable-exploring when using the remote jupyter/ipython kernel?
2. access the kernel on the remote server using ssh

the variable explorer show the variables when using the `internel`/`local` ipython 
but when using the remote ipython kernel (over ssh), the variable explorer shows nothing

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: unknown
* PyQt Version: unknown
* Operating system: windows10 x64

## Dependencies
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Unfortunately the Variable Explorer doesn't work for remote kernels. This is something we're trying to improve for Spyder 4.
