### ISSUE TITLE
Behavior of Stop button in IPython console

### ISSUE THREAD

**Issue by kklmn** [spyder-ide/spyder#5727]
My scripts produce several (tens) matplotlib graphs as separate windows as I don't want to see them in the console, just too many for this. When I want to re-run the script again, I stop the running version with the Stop button, but this action doesn't close the matplotlib windows. Why?

With the old internal python console, not IPython one, I could do so. Now I have to kill them separately or a) to kill the kernel and b) open a new console again -- both actions take several seconds. With repetitive runs this is pretty annoying. 

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.1 64 bit
* Qt Version: 5.8.0
* PyQt Version: 5.8.1
* Operating system: W10 64bit

**Comment by ccordoba12** [comment]
> I stop the running version with the Stop button, but this action doesn't close the matplotlib windows. Why?

The stop button is only meant to interrupt the current evaluation in the kernel, not to close Matplotlib windows.

> With the old internal python console, not IPython one, I could do so.

The old Python console didn't have a stop button. Perhaps you're talking about its restart button...

> Now I have to kill them separately or a) to kill the kernel and b) open a new console again -- both actions take several seconds.

There's a third option. In the menu

    Run > Configuration per file

select the option

    Execute in a dedicated console

That option will clear your kernel's namespace and close all your Matplotlib figures before your next run.

**Comment by kklmn** [comment]
Yes, I am speaking about the "dedicated console".
And no, this option does *not* close Matplotlib windows. Even worse, most ofthen it is not possible to restart the script without closing the console tab, even when the script has normally finished, and never possible when the script has aborted by an exception.

Closing the issue means what? - you can't reproduce it or you find it minor? For me this issue really prevents me from using Spyder the way I used to use it.
