### ISSUE TITLE
Missing python doc in help menu

### ISSUE THREAD

**Issue by ahed87** [spyder-ide/spyder#5728]
Hi,

maybe it is by purpose that the "python documentation" link is removed from the help-menu as part of removing the python console.

I really miss it, would it be possible to put it back?
It seems like the code to find the .chm is still there.

* Spyder Version: 3.2.4
* OS: Windows

**Comment by ccordoba12** [comment]
Ok, we'll put it back in our next version.

**Comment by ahed87** [comment]
great, thanks.
