### ISSUE TITLE
Menu bar "File" and "Edit" not functional in Spyder 3.1.4 on Ubuntu 17.10

### ISSUE THREAD

**Issue by daver1691** [spyder-ide/spyder#5730]
In Spyder 3.1.4, the latest version in Ubuntu 17.10's repository, after starting Spyder, if you click on "File" in the menu bar, it darkens with the "button depressed" appearance, but the drop-menu does not appear. Same problem if "Edit" is clicked.

However, if "Search" is clicked, the drop-menu _does_ appear, and then if the cursor is moved left, the drop-menus for "Edit" and "File" do appear as the mouse hovers over them.

Desktop capture showing problem:  [https://streamable.com/db9q7](https://streamable.com/db9q7)

Tested with Spyder and Spyder3 on Ubuntu 17.10 with Gnome and KDE desktops. Same problem with all.

---

* Spyder Version: 3.1.4
* Python Version: 2.7.14 and 3.6.3
* Qt Version: 5.9.1
* PyQt Version: 5.7
* Operating system: Ubuntu 17.10, Gnome Wayland and KDE Xorg

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  None (NOK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
pyflakes >=0.5.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Closing because of lack of response.
