### ISSUE TITLE
Variable highlighting fails with variables containing middle dot ·

### ISSUE THREAD

**Issue by sbyrnes321** [spyder-ide/spyder#5732]
**What steps will reproduce the problem?**

1. Make a .py file with one line: `ab·cd = 2` (Yes, `ab·cd` is a valid name for a variable in Python 3!)
2. Put your cursor between c and d

**What is the expected output? What do you see instead?**

I expect that the whole variable `ab·cd` will be highlighted. But only the `ab` part gets highlighted.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Ubuntu 17.10 (Anaconda)

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by csabella** [comment]
This is similar to issue #1634 and would be fixed by the PR on that issue.

**Comment by ccordoba12** [comment]
Thanks @csabella!

**Comment by sbyrnes321** [comment]
While I haven't compiled the code after this PR #5676, I strongly suspect that it would not resolve this issue. This issue occurs when the cursor is NOT highlighting a word, but just sitting in the middle of a word. In Python 3, the middle dot · is a valid character in an identifier (e.g. variable name), and is supposed to be treated the same as any normal letter. So if the cursor is sitting in the middle of `ab·cd`, that whole thing is one identifier, and the whole thing should be highlighted.

Both before and after PR #5676, if I'm reading it right, under the circumstance where the cursor is sitting in the middle of a word as opposed to highlighting a selection, it calls `self.get_current_word()`.

And then I believe the issue is [this line](https://github.com/spyder-ide/spyder/blob/160cc23dd38256d41c88534f04103dc611f3f1ea/spyder/widgets/mixins.py#L371):

`match = re.findall(r'([^\d\W]\w*)', text, re.UNICODE)`

That regex is not an accurate description of Python 3 identifiers. When I run this regex on `ab·cd`, the regex splits it into two pieces (`ab` and `cd`), but actually the Python 3 interpreter treats the whole thing `ab·cd` as a single identifier.

In Python 2, the correct regex [seems to be](https://stackoverflow.com/a/48067062) `r'[a-zA-Z_]\w*'`. In Python 3, it seems to be more complicated, and I can't immediately find an appropriate regex on google. Maybe there's a way to use `str.isidentifier`? Or to use some undocumented function in the `tokenize` module?

**Comment by csabella** [comment]
#5676 solves it by allowing it to be highlighted by selection and not by cursor.  So, it's not an exact fix, but it does allow highlighting of it.

As far as the regex, here's the definition of `\w`:
>    For Unicode (str) patterns:
        Matches Unicode word characters; this includes most characters that can be part of a word in any language, as well as numbers and the underscore. If the ASCII flag is used, only [a-zA-Z0-9_] is matched.

But, even this doesn't work:
```
x
Out[14]: 'ab·cd'

match = re.findall(r'\w*', x)

match
Out[16]: ['ab', '', 'cd', '']

match = re.findall(r'\w*', x, re.UNICODE)

match
Out[18]: ['ab', '', 'cd', '']
```

So, it seems like `\w` might be the culprit.  `isindentifier()` is an interesting idea to consider.  I wonder if there's things that would be found by the highlighter now that wouldn't be an indentifier.

**Comment by csabella** [comment]
So I did a little more investigating.  MIDDLE DOT is a Po category, which means it's in the same category as the comma.  So, that explains it's behavior in `re`.  Also, looking at the lexical analysis for idenitifiers (https://docs.python.org/3.8/reference/lexical_analysis.html#identifiers), it's included as an 'Other_ID_Start' character (https://www.unicode.org/Public/10.0.0/ucd/PropList.txt).  So, that explains why it's an identifier.  Now the only thing left is the check the highlight code in Spyder to make sure it's intended just to work with valid identifiers.  Based on the regex, that's probably the intention, but it will need to be verified just so a change doesn't break current usage.

**Comment by sbyrnes321** [comment]
I was feeling really hopeful about replacing the [problematic line](https://github.com/spyder-ide/spyder/blob/160cc23dd38256d41c88534f04103dc611f3f1ea/spyder/widgets/mixins.py#L371) with something using the tokenize module, along the lines of:

    token_generator = tokenize.tokenize(BytesIO(text).readline)
    match = next(token.string for token in token_generator if token.type==1)

...but wouldn't you know it, the `tokenize` module (part of Python's standard library) *also* fails to parse unicode identifiers!! I just submitted a bug report about that to python central - https://bugs.python.org/issue32987  :-P

**Comment by csabella** [comment]
I have been looking into this more and I don't know that there's a perfect solution for the 'word under the cursor' issue.  One of the test cases for `get_current_word` is '123valid_python_word' and it picks out 'valid_python_word'.  So, the regex tries to find the beginning and end of a valid word, but contained within another string.  The test example may not be real world, but something like `self.occurrences.append(cursor.blockNumber())` will select `occurrences` or `append` or `cursor` or `blockNumber` based on where the cursor is.  Another way to do that would be to move one character at a time in each direction until a non-word character is hit, but how would 'non-word character' be defined?  

Parsing the tokens was an interesting idea, but this highlighting even works on words that are in a comment, so limiting it to Python identifiers/tokens would take away some functionality.

I am still thinking about this one, but I'm starting to think this may be an edge case that we just need to use the other method (text selection instead of cursor position) for.     I even looked at `regex` instead of `re`, but I didn't see any difference.

**Comment by sbyrnes321** [comment]
* It's a moot point until `tokenize.py` is fixed, but if you look again, you'll see I was proposing to run `tokenize` just on the string `text`, not on the whole line or whole file, so AFAIK it would work even within a comment.
* If you're OK moving one character at a time, then there's the [`text[i:j].isidentifier()` option](https://docs.python.org/3.6/library/stdtypes.html#str.isidentifier)
