### ISSUE TITLE
Could you add this new Dark Theme

### ISSUE THREAD

**Issue by ctorrez** [spyder-ide/spyder#5737]
## Add this new Dark Theme

Hi guys,

Thank you for your great work. Spyder is my favorite python IDLE for data analysis. I create this Dark Theme, it is a  combination of RStudio Dark Theme and some customization. 

**My-Dark Theme**
``` python
custom_names = ['My-Dark']
My-Dark/currentcell = #073642
My-Dark/sideareas = #324c63
My-Dark/currentline = #083f4d
My-Dark/normal = ('#ffffff', False, False)
My-Dark/definition = ('#268bd2', True, False)
My-Dark/unmatched_p = #dc322f
My-Dark/number = ('#ffff7f', False, False)
My-Dark/string = ('#2ad900', False, False)
My-Dark/ctrlclick = #d33682
My-Dark/builtin = ('#ff9d00', True, False)
My-Dark/comment = ('#4ec9b0', False, True)
My-Dark/occurrence = #0074da
My-Dark/instance = ('#ff0000', False, True)
My-Dark/background = #002240
My-Dark/matched_p = #93a1a1
My-Dark/keyword = ('#00ffbf', True, False)
My-Dark/name = My-Dark
```
![image](https://user-images.githubusercontent.com/15874657/32732199-150cb9e8-c849-11e7-906f-5a15d192dea4.png)

**Comment by ccordoba12** [comment]
Thanks for reporting. It's a nice theme, but we can't add it to distribute with Spyder, sorry.

That's why we give users the possibility to create custom themes.

**Comment by ctorrez** [comment]
Thanks Carlos
