### ISSUE TITLE
won't open after installing for the first time

### ISSUE THREAD

**Issue by nreitman** [spyder-ide/spyder#5738]
## Description

**What steps will reproduce the problem?**

1. install with: conda install spyder-terminal -c spyder-ide
2. open spyder

**What is the expected output? What do you see instead?**
error box pops up on open with message below

**Please provide any additional information below**

  File "/Users/nadine/anaconda2/lib/python2.7/site-packages/spyder_terminal/terminalplugin.py", line 165, in __wait_server_to_start
    self.create_new_term(give_focus=False)
  File "/Users/nadine/anaconda2/lib/python2.7/site-packages/spyder_terminal/terminalplugin.py", line 315, in create_new_term
    font=font.family())
  File "/Users/nadine/anaconda2/lib/python2.7/site-packages/spyder_terminal/widgets/terminalgui.py", line 63, in __init__
    self.view = TermView(self, term_url=url, handler=self.handler)
  File "/Users/nadine/anaconda2/lib/python2.7/site-packages/spyder_terminal/widgets/terminalgui.py", line 147, in __init__
    self.document.profile().clearHttpCache()
AttributeError: 'QWebEngineProfile' object has no attribute 'clearHttpCache'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
What's your spyder-terminal version? This is supposed to be fixed in its latest version.

You can get that version by inspecting the output of

    conda list

**Comment by nreitman** [comment]
spyder-terminal           0.2.2                    py27_0    spyder-ide

**Comment by ccordoba12** [comment]
Ok, thanks. We forgot to update our macOS packages to 0.2.3, which fixes this problem. Please check in a couple of hours again to get the update.
