### ISSUE TITLE
from PyQt5.QtWidgets import * ImportError: /usr/lib64/libGL.so.1: file too short

### ISSUE THREAD

**Issue by huangmozhilv** [spyder-ide/spyder#5740]
## Description of your problem

**What steps will reproduce the problem?**
1. Login to remote Linux server and "cd my/self-defined/directory"
2. Download Anaconda with "wget https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh" and install with "bash Anaconda3-5.0.1-Linux-x86_64.sh"
3. type in command line: spyder

**What is the expected output? What do you see instead?**
Expected output: a separate window opens for spyder
Output instead:
Traceback (most recent call last):
  File "/home/chao2009/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/chao2009/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/home/chao2009/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 78, in <module>
    from qtpy.compat import from_qvariant
  File "/home/chao2009/anaconda3/lib/python3.6/site-packages/qtpy/compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "/home/chao2009/anaconda3/lib/python3.6/site-packages/qtpy/QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: /usr/lib64/libGL.so.1: file too short

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Linux CentOS release 6.9 (Final)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
-bash-4.1$ ls anaconda3/lib
cairo                                      libQt5Bluetooth.la
cmake                                      libQt5Bluetooth.prl
dbus-1.0                                   libQt5Bluetooth.so
engines                                    libQt5Bluetooth.so.5
girepository-1.0                           libQt5Bluetooth.so.5.6
glib-2.0                                   libQt5Bluetooth.so.5.6.2
gstreamer-1.0                              libQt5Bootstrap.a
icu                                        libQt5Bootstrap.la
itcl4.1.0                                  libQt5Bootstrap.prl
libasan.so                                 libQt5CLucene.la
libasan.so.4                               libQt5CLucene.prl
libasan.so.4.0.0                           libQt5CLucene.so
libatomic.so                               libQt5CLucene.so.5
libatomic.so.1                             libQt5CLucene.so.5.6
libatomic.so.1.2.0                         libQt5CLucene.so.5.6.2
libbz2.a                                   libQt5Concurrent.la
libbz2.so                                  libQt5Concurrent.prl
libbz2.so.1.0                              libQt5Concurrent.so
libbz2.so.1.0.6                            libQt5Concurrent.so.5
libcairo.a                                 libQt5Concurrent.so.5.6
libcairo-gobject.a                         libQt5Concurrent.so.5.6.2
libcairo-gobject.la                        libQt5Core.la
libcairo-gobject.so                        libQt5Core.prl
libcairo-gobject.so.2                      libQt5Core.so
libcairo-gobject.so.2.11400.10             libQt5Core.so.5
libcairo.la                                libQt5Core.so.5.6
libcairo-script-interpreter.a              libQt5Core.so.5.6.2
libcairo-script-interpreter.la             libQt5DBus.la
libcairo-script-interpreter.so             libQt5DBus.prl
libcairo-script-interpreter.so.2           libQt5DBus.so
libcairo-script-interpreter.so.2.11400.10  libQt5DBus.so.5
libcairo.so                                libQt5DBus.so.5.6
libcairo.so.2                              libQt5DBus.so.5.6.2
libcairo.so.2.11400.10                     libQt5DesignerComponents.la
libcrypto.a                                libQt5DesignerComponents.prl
libcrypto.so                               libQt5DesignerComponents.so
libcrypto.so.1.0.0                         libQt5DesignerComponents.so.5
libcurl.a                                  libQt5DesignerComponents.so.5.6
libcurl.la                                 libQt5DesignerComponents.so.5.6.2
libcurl.so                                 libQt5Designer.la
libcurl.so.4                               libQt5Designer.prl
libcurl.so.4.4.0                           libQt5Designer.so
libdbus-1.a                                libQt5Designer.so.5
libdbus-1.la                               libQt5Designer.so.5.6
libdbus-1.so                               libQt5Designer.so.5.6.2
libdbus-1.so.3                             libQt5Gui.la
libdbus-1.so.3.14.13                       libQt5Gui.prl
libdynlib1.la                              libQt5Gui.so
libdynlib1.so                              libQt5Gui.so.5
libdynlib2.la                              libQt5Gui.so.5.6
libdynlib2.so                              libQt5Gui.so.5.6.2
libdynlib3.la                              libQt5Help.la
libdynlib3.so                              libQt5Help.prl
libdynlib4.la                              libQt5Help.so
libdynlib4.so                              libQt5Help.so.5
libdynlibadd.la                            libQt5Help.so.5.6
libdynlibadd.so                            libQt5Help.so.5.6.2
libdynlibdiff.la                           libQt5Multimedia.la
libdynlibdiff.so                           libQt5Multimedia.prl
libdynlibdump.la                           libQt5MultimediaQuick_p.la
libdynlibdump.so                           libQt5MultimediaQuick_p.prl
libdynlibls.la                             libQt5MultimediaQuick_p.so
libdynlibls.so                             libQt5MultimediaQuick_p.so.5
libdynlibvers.la                           libQt5MultimediaQuick_p.so.5.6
libdynlibvers.so                           libQt5MultimediaQuick_p.so.5.6.2
libedit.a                                  libQt5Multimedia.so
libedit.la                                 libQt5Multimedia.so.5
libedit.so                                 libQt5Multimedia.so.5.6
libedit.so.0                               libQt5Multimedia.so.5.6.2
libedit.so.0.0.56                          libQt5MultimediaWidgets.la
libexpat.a                                 libQt5MultimediaWidgets.prl
libexpat.la                                libQt5MultimediaWidgets.so
libexpat.so                                libQt5MultimediaWidgets.so.5
libexpat.so.1                              libQt5MultimediaWidgets.so.5.6
libexpat.so.1.6.6                          libQt5MultimediaWidgets.so.5.6.2
libexslt.a                                 libQt5Network.la
libexslt.la                                libQt5Network.prl
libexslt.so                                libQt5Network.so
libexslt.so.0                              libQt5Network.so.5
libexslt.so.0.8.17                         libQt5Network.so.5.6
libffi.a                                   libQt5Network.so.5.6.2
libffi.la                                  libQt5Nfc.la
libffi.so                                  libQt5Nfc.prl
libffi.so.6                                libQt5Nfc.so
libffi.so.6.0.4                            libQt5Nfc.so.5
libfontconfig.a                            libQt5Nfc.so.5.6
libfontconfig.la                           libQt5Nfc.so.5.6.2
libfontconfig.so                           libQt5OpenGLExtensions.a
libfontconfig.so.1                         libQt5OpenGLExtensions.la
libfontconfig.so.1.9.4                     libQt5OpenGLExtensions.prl
libform.a                                  libQt5OpenGL.la
libform.so                                 libQt5OpenGL.prl
libformw.a                                 libQt5OpenGL.so
libformw.so                                libQt5OpenGL.so.5
libformw.so.6                              libQt5OpenGL.so.5.6
libformw.so.6.0                            libQt5OpenGL.so.5.6.2
libfreetype.a                              libQt5PlatformSupport.a
libfreetype.la                             libQt5PlatformSupport.la
libfreetype.so                             libQt5PlatformSupport.prl
libfreetype.so.6                           libQt5PrintSupport.la
libfreetype.so.6.14.0                      libQt5PrintSupport.prl
libgcc_s.so                                libQt5PrintSupport.so
libgcc_s.so.1                              libQt5PrintSupport.so.5
libgfortran.so                             libQt5PrintSupport.so.5.6
libgfortran.so.4                           libQt5PrintSupport.so.5.6.2
libgfortran.so.4.0.0                       libQt5QmlDevTools.a
libgio-2.0.la                              libQt5QmlDevTools.la
libgio-2.0.so                              libQt5QmlDevTools.prl
libgio-2.0.so.0                            libQt5Qml.la
libgio-2.0.so.0.5306.0                     libQt5Qml.prl
libglib-2.0.la                             libQt5Qml.so
libglib-2.0.so                             libQt5Qml.so.5
libglib-2.0.so.0                           libQt5Qml.so.5.6
libglib-2.0.so.0.5306.0                    libQt5Qml.so.5.6.2
libgmodule-2.0.la                          libQt5Quick.la
libgmodule-2.0.so                          libQt5QuickParticles.la
libgmodule-2.0.so.0                        libQt5QuickParticles.prl
libgmodule-2.0.so.0.5306.0                 libQt5QuickParticles.so
libgmp.a                                   libQt5QuickParticles.so.5
libgmp.la                                  libQt5QuickParticles.so.5.6
libgmp.so                                  libQt5QuickParticles.so.5.6.2
libgmp.so.10                               libQt5Quick.prl
libgmp.so.10.3.2                           libQt5Quick.so
libgmpxx.a                                 libQt5Quick.so.5
libgmpxx.la                                libQt5Quick.so.5.6
libgmpxx.so                                libQt5Quick.so.5.6.2
libgmpxx.so.4                              libQt5QuickTest.la
libgmpxx.so.4.5.2                          libQt5QuickTest.prl
libgobject-2.0.la                          libQt5QuickTest.so
libgobject-2.0.so                          libQt5QuickTest.so.5
libgobject-2.0.so.0                        libQt5QuickTest.so.5.6
libgobject-2.0.so.0.5306.0                 libQt5QuickTest.so.5.6.2
libgomp.so                                 libQt5QuickWidgets.la
libgomp.so.1                               libQt5QuickWidgets.prl
libgomp.so.1.0.0                           libQt5QuickWidgets.so
libgraphite2.so                            libQt5QuickWidgets.so.5
libgraphite2.so.3                          libQt5QuickWidgets.so.5.6
libgraphite2.so.3.0.1                      libQt5QuickWidgets.so.5.6.2
libgstallocators-1.0.la                    libQt5Script.la
libgstallocators-1.0.so                    libQt5Script.prl
libgstallocators-1.0.so.0                  libQt5Script.so
libgstallocators-1.0.so.0.1202.0           libQt5Script.so.5
libgstapp-1.0.la                           libQt5Script.so.5.6
libgstapp-1.0.so                           libQt5Script.so.5.6.2
libgstapp-1.0.so.0                         libQt5ScriptTools.la
libgstapp-1.0.so.0.1202.0                  libQt5ScriptTools.prl
libgstaudio-1.0.la                         libQt5ScriptTools.so
libgstaudio-1.0.so                         libQt5ScriptTools.so.5
libgstaudio-1.0.so.0                       libQt5ScriptTools.so.5.6
libgstaudio-1.0.so.0.1202.0                libQt5ScriptTools.so.5.6.2
libgstbase-1.0.la                          libQt5Sql.la
libgstbase-1.0.so                          libQt5Sql.prl
libgstbase-1.0.so.0                        libQt5Sql.so
libgstbase-1.0.so.0.1202.0                 libQt5Sql.so.5
libgstcheck-1.0.la                         libQt5Sql.so.5.6
libgstcheck-1.0.so                         libQt5Sql.so.5.6.2
libgstcheck-1.0.so.0                       libQt5Svg.la
libgstcheck-1.0.so.0.1202.0                libQt5Svg.prl
libgstcontroller-1.0.la                    libQt5Svg.so
libgstcontroller-1.0.so                    libQt5Svg.so.5
libgstcontroller-1.0.so.0                  libQt5Svg.so.5.6
libgstcontroller-1.0.so.0.1202.0           libQt5Svg.so.5.6.2
libgstfft-1.0.la                           libQt5Test.la
libgstfft-1.0.so                           libQt5Test.prl
libgstfft-1.0.so.0                         libQt5Test.so
libgstfft-1.0.so.0.1202.0                  libQt5Test.so.5
libgstnet-1.0.la                           libQt5Test.so.5.6
libgstnet-1.0.so                           libQt5Test.so.5.6.2
libgstnet-1.0.so.0                         libQt5UiTools.a
libgstnet-1.0.so.0.1202.0                  libQt5UiTools.la
libgstpbutils-1.0.la                       libQt5UiTools.prl
libgstpbutils-1.0.so                       libQt5WebChannel.la
libgstpbutils-1.0.so.0                     libQt5WebChannel.prl
libgstpbutils-1.0.so.0.1202.0              libQt5WebChannel.so
libgstreamer-1.0.la                        libQt5WebChannel.so.5
libgstreamer-1.0.so                        libQt5WebChannel.so.5.6
libgstreamer-1.0.so.0                      libQt5WebChannel.so.5.6.2
libgstreamer-1.0.so.0.1202.0               libQt5WebKit.la
libgstriff-1.0.la                          libQt5WebKit.prl
libgstriff-1.0.so                          libQt5WebKit.so
libgstriff-1.0.so.0                        libQt5WebKit.so.5
libgstriff-1.0.so.0.1202.0                 libQt5WebKit.so.5.6
libgstrtp-1.0.la                           libQt5WebKit.so.5.6.2
libgstrtp-1.0.so                           libQt5WebKitWidgets.la
libgstrtp-1.0.so.0                         libQt5WebKitWidgets.prl
libgstrtp-1.0.so.0.1202.0                  libQt5WebKitWidgets.so
libgstrtsp-1.0.la                          libQt5WebKitWidgets.so.5
libgstrtsp-1.0.so                          libQt5WebKitWidgets.so.5.6
libgstrtsp-1.0.so.0                        libQt5WebKitWidgets.so.5.6.2
libgstrtsp-1.0.so.0.1202.0                 libQt5WebSockets.la
libgstsdp-1.0.la                           libQt5WebSockets.prl
libgstsdp-1.0.so                           libQt5WebSockets.so
libgstsdp-1.0.so.0                         libQt5WebSockets.so.5
libgstsdp-1.0.so.0.1202.0                  libQt5WebSockets.so.5.6
libgsttag-1.0.la                           libQt5WebSockets.so.5.6.2
libgsttag-1.0.so                           libQt5Widgets.la
libgsttag-1.0.so.0                         libQt5Widgets.prl
libgsttag-1.0.so.0.1202.0                  libQt5Widgets.so
libgstvideo-1.0.la                         libQt5Widgets.so.5
libgstvideo-1.0.so                         libQt5Widgets.so.5.6
libgstvideo-1.0.so.0                       libQt5Widgets.so.5.6.2
libgstvideo-1.0.so.0.1202.0                libQt5X11Extras.la
libgthread-2.0.la                          libQt5X11Extras.prl
libgthread-2.0.so                          libQt5X11Extras.so
libgthread-2.0.so.0                        libQt5X11Extras.so.5
libgthread-2.0.so.0.5306.0                 libQt5X11Extras.so.5.6
libharfbuzz.a                              libQt5X11Extras.so.5.6.2
libharfbuzz-gobject.a                      libQt5XcbQpa.la
libharfbuzz-gobject.la                     libQt5XcbQpa.prl
libharfbuzz-gobject.so                     libQt5XcbQpa.so
libharfbuzz-gobject.so.0                   libQt5XcbQpa.so.5
libharfbuzz-gobject.so.0.10500.0           libQt5XcbQpa.so.5.6
libharfbuzz-icu.a                          libQt5XcbQpa.so.5.6.2
libharfbuzz-icu.la                         libQt5Xml.la
libharfbuzz-icu.so                         libQt5XmlPatterns.la
libharfbuzz-icu.so.0                       libQt5XmlPatterns.prl
libharfbuzz-icu.so.0.10500.0               libQt5XmlPatterns.so
libharfbuzz.la                             libQt5XmlPatterns.so.5
libharfbuzz.so                             libQt5XmlPatterns.so.5.6
libharfbuzz.so.0                           libQt5XmlPatterns.so.5.6.2
libharfbuzz.so.0.10500.0                   libQt5Xml.prl
libhdf5.a                                  libQt5Xml.so
libhdf5_cpp.a                              libQt5Xml.so.5
libhdf5_cpp.la                             libQt5Xml.so.5.6
libhdf5_cpp.so                             libQt5Xml.so.5.6.2
libhdf5_cpp.so.101                         libquadmath.so
libhdf5_cpp.so.101.0.0                     libquadmath.so.0
libhdf5_fortran.a                          libquadmath.so.0.0.0
libhdf5_fortran.la                         libreadline.a
libhdf5_fortran.so                         libreadline.so
libhdf5_fortran.so.100                     libreadline.so.7
libhdf5_fortran.so.100.1.0                 libreadline.so.7.0
libhdf5_hl.a                               libsodium.a
libhdf5_hl_cpp.a                           libsodium.la
libhdf5_hl_cpp.la                          libsodium.so
libhdf5_hl_cpp.so                          libsodium.so.18
libhdf5_hl_cpp.so.100                      libsodium.so.18.3.0
libhdf5_hl_cpp.so.100.1.0                  libsqlite3.a
libhdf5hl_fortran.a                        libsqlite3.la
libhdf5hl_fortran.la                       libsqlite3.so
libhdf5hl_fortran.so                       libsqlite3.so.0
libhdf5hl_fortran.so.100                   libsqlite3.so.0.8.6
libhdf5hl_fortran.so.100.0.1               libssh2.a
libhdf5_hl.la                              libssh2.so
libhdf5_hl.so                              libssh2.so.1
libhdf5_hl.so.100                          libssh2.so.1.0.1
libhdf5_hl.so.100.0.1                      libssl.a
libhdf5.la                                 libssl.so
libhdf5.settings                           libssl.so.1.0.0
libhdf5.so                                 libstdc++.so
libhdf5.so.101                             libstdc++.so.6
libhdf5.so.101.0.0                         libstdc++.so.6.0.24
libhistory.a                               libtcl8.6.so
libhistory.so                              libtcl.so
libhistory.so.7                            libtclstub8.6.a
libhistory.so.7.0                          libtiff.a
libicudata.a                               libtiff.la
libicudata.so                              libtiff.so
libicudata.so.58                           libtiff.so.5
libicudata.so.58.2                         libtiff.so.5.2.6
libicui18n.a                               libtiffxx.a
libicui18n.so                              libtiffxx.la
libicui18n.so.58                           libtiffxx.so
libicui18n.so.58.2                         libtiffxx.so.5
libicuio.a                                 libtiffxx.so.5.2.6
libicuio.so                                libtinfo.a
libicuio.so.58                             libtinfo.so
libicuio.so.58.2                           libtinfow.a
libicutest.a                               libtinfow.so
libicutest.so                              libtinfow.so.6
libicutest.so.58                           libtinfow.so.6.0
libicutest.so.58.2                         libtk8.6.so
libicutu.a                                 libtk.so
libicutu.so                                libtkstub8.6.a
libicutu.so.58                             libtsan.so
libicutu.so.58.2                           libtsan.so.0
libicuuc.a                                 libtsan.so.0.0.0
libicuuc.so                                libubsan.so
libicuuc.so.58                             libubsan.so.0
libicuuc.so.58.2                           libubsan.so.0.0.0
libiomp5.so                                libxcb.a
libiompstubs5.so                           libxcb-composite.a
libitm.so                                  libxcb-composite.la
libitm.so.1                                libxcb-composite.so
libitm.so.1.0.0                            libxcb-composite.so.0
libjbig85.a                                libxcb-composite.so.0.0.0
libjbig.a                                  libxcb-damage.a
libjpeg.a                                  libxcb-damage.la
libjpeg.la                                 libxcb-damage.so
libjpeg.so                                 libxcb-damage.so.0
libjpeg.so.9                               libxcb-damage.so.0.0.0
libjpeg.so.9.2.0                           libxcb-dpms.a
liblsan.so                                 libxcb-dpms.la
liblsan.so.0                               libxcb-dpms.so
liblsan.so.0.0.0                           libxcb-dpms.so.0
libltdl.a                                  libxcb-dpms.so.0.0.0
libltdl.la                                 libxcb-dri2.a
libltdl.so                                 libxcb-dri2.la
libltdl.so.7                               libxcb-dri2.so
libltdl.so.7.3.1                           libxcb-dri2.so.0
liblzma.a                                  libxcb-dri2.so.0.0.0
liblzma.la                                 libxcb-dri3.a
liblzma.so                                 libxcb-dri3.la
liblzma.so.5                               libxcb-dri3.so
liblzma.so.5.2.3                           libxcb-dri3.so.0
liblzo2.a                                  libxcb-dri3.so.0.0.0
liblzo2.so                                 libxcb-glx.a
liblzo2.so.2                               libxcb-glx.la
liblzo2.so.2.0.0                           libxcb-glx.so
libmenu.a                                  libxcb-glx.so.0
libmenu.so                                 libxcb-glx.so.0.0.0
libmenuw.a                                 libxcb.la
libmenuw.so                                libxcb-present.a
libmenuw.so.6                              libxcb-present.la
libmenuw.so.6.0                            libxcb-present.so
libmkl_ao_worker.so                        libxcb-present.so.0
libmkl_avx2.so                             libxcb-present.so.0.0.0
libmkl_avx512_mic.so                       libxcb-randr.a
libmkl_avx512.so                           libxcb-randr.la
libmkl_avx.so                              libxcb-randr.so
libmkl_blacs_intelmpi_ilp64.so             libxcb-randr.so.0
libmkl_blacs_intelmpi_lp64.so              libxcb-randr.so.0.1.0
libmkl_blacs_openmpi_ilp64.so              libxcb-record.a
libmkl_blacs_openmpi_lp64.so               libxcb-record.la
libmkl_blacs_sgimpt_ilp64.so               libxcb-record.so
libmkl_blacs_sgimpt_lp64.so                libxcb-record.so.0
libmkl_cdft_core.so                        libxcb-record.so.0.0.0
libmkl_core.so                             libxcb-render.a
libmkl_def.so                              libxcb-render.la
libmkl_gf_ilp64.so                         libxcb-render.so
libmkl_gf_lp64.so                          libxcb-render.so.0
libmkl_gnu_thread.so                       libxcb-render.so.0.0.0
libmkl_intel_ilp64.so                      libxcb-res.a
libmkl_intel_lp64.so                       libxcb-res.la
libmkl_intel_thread.so                     libxcb-res.so
libmkl_mc3.so                              libxcb-res.so.0
libmkl_mc.so                               libxcb-res.so.0.0.0
libmkl_pgi_thread.so                       libxcb-screensaver.a
libmkl_rt.so                               libxcb-screensaver.la
libmkl_scalapack_ilp64.so                  libxcb-screensaver.so
libmkl_scalapack_lp64.so                   libxcb-screensaver.so.0
libmkl_sequential.so                       libxcb-screensaver.so.0.0.0
libmkl_tbb_thread.so                       libxcb-shape.a
libmkl_vml_avx2.so                         libxcb-shape.la
libmkl_vml_avx512_mic.so                   libxcb-shape.so
libmkl_vml_avx512.so                       libxcb-shape.so.0
libmkl_vml_avx.so                          libxcb-shape.so.0.0.0
libmkl_vml_cmpt.so                         libxcb-shm.a
libmkl_vml_def.so                          libxcb-shm.la
libmkl_vml_mc2.so                          libxcb-shm.so
libmkl_vml_mc3.so                          libxcb-shm.so.0
libmkl_vml_mc.so                           libxcb-shm.so.0.0.0
libmpc.a                                   libxcb.so
libmpc.la                                  libxcb.so.1
libmpc.so                                  libxcb.so.1.1.0
libmpc.so.3                                libxcb-sync.a
libmpc.so.3.0.0                            libxcb-sync.la
libmpfr.a                                  libxcb-sync.so
libmpfr.la                                 libxcb-sync.so.1
libmpfr.so                                 libxcb-sync.so.1.0.0
libmpfr.so.4                               libxcb-xf86dri.a
libmpfr.so.4.1.5                           libxcb-xf86dri.la
libncurses.a                               libxcb-xf86dri.so
libncurses++.a                             libxcb-xf86dri.so.0
libncurses.so                              libxcb-xf86dri.so.0.0.0
libncurses++w.a                            libxcb-xfixes.a
libncursesw.a                              libxcb-xfixes.la
libncursesw.so                             libxcb-xfixes.so
libncursesw.so.6                           libxcb-xfixes.so.0
libncursesw.so.6.0                         libxcb-xfixes.so.0.0.0
libodbccr.la                               libxcb-xinerama.a
libodbccr.so                               libxcb-xinerama.la
libodbccr.so.2                             libxcb-xinerama.so
libodbccr.so.2.0.0                         libxcb-xinerama.so.0
libodbcinst.la                             libxcb-xinerama.so.0.0.0
libodbcinst.so                             libxcb-xkb.a
libodbcinst.so.2                           libxcb-xkb.la
libodbcinst.so.2.0.0                       libxcb-xkb.so
libodbc.la                                 libxcb-xkb.so.1
libodbc.so                                 libxcb-xkb.so.1.0.0
libodbc.so.2                               libxcb-xtest.a
libodbc.so.2.0.0                           libxcb-xtest.la
libpanel.a                                 libxcb-xtest.so
libpanel.so                                libxcb-xtest.so.0
libpanelw.a                                libxcb-xtest.so.0.0.0
libpanelw.so                               libxcb-xv.a
libpanelw.so.6                             libxcb-xv.la
libpanelw.so.6.0                           libxcb-xvmc.a
libpango-1.0.la                            libxcb-xvmc.la
libpango-1.0.so                            libxcb-xvmc.so
libpango-1.0.so.0                          libxcb-xvmc.so.0
libpango-1.0.so.0.4000.11                  libxcb-xvmc.so.0.0.0
libpangocairo-1.0.la                       libxcb-xv.so
libpangocairo-1.0.so                       libxcb-xv.so.0
libpangocairo-1.0.so.0                     libxcb-xv.so.0.0.0
libpangocairo-1.0.so.0.4000.11             libxml2.a
libpangoft2-1.0.la                         libxml2.la
libpangoft2-1.0.so                         libxml2.so
libpangoft2-1.0.so.0                       libxml2.so.2
libpangoft2-1.0.so.0.4000.11               libxml2.so.2.9.4
libpcre.a                                  libxslt.a
libpcrecpp.a                               libxslt.la
libpcrecpp.la                              libxslt.so
libpcrecpp.so                              libxslt.so.1
libpcrecpp.so.0                            libxslt.so.1.1.29
libpcrecpp.so.0.0.1                        libyaml-0.so.2
libpcre.la                                 libyaml-0.so.2.0.5
libpcreposix.a                             libyaml.a
libpcreposix.la                            libyaml.la
libpcreposix.so                            libyaml.so
libpcreposix.so.0                          libz.a
libpcreposix.so.0.0.5                      libzmq.a
libpcre.so                                 libzmq.so
libpcre.so.1                               libzmq.so.4.2.2
libpcre.so.1.2.9                           libzmq.so.5
libpixman-1.a                              libzmq.so.5.1.2
libpixman-1.la                             libz.so
libpixman-1.so                             libz.so.1
libpixman-1.so.0                           libz.so.1.2.11
libpixman-1.so.0.34.0                      mkl_msg.cat
libpng16.a                                 pkgconfig
libpng16.la                                python3.6
libpng16.so                                sqlite3.20.0
libpng16.so.16                             tcl8
libpng16.so.16.32.0                        tcl8.6
libpng.a                                   tclConfig.sh
libpng.la                                  tclooConfig.sh
libpng.so                                  tdbc1.0.5
libpython3.6m.a                            tdbcmysql1.0.5
libpython3.6m.so                           tdbcodbc1.0.5
libpython3.6m.so.1                         tdbcpostgres1.0.5
libpython3.6m.so.1.0                       terminfo
libqgsttools_p.prl                         thread2.8.1
libqgsttools_p.so                          tk8.6
libqgsttools_p.so.1                        tkConfig.sh
libqgsttools_p.so.1.0                      xml2Conf.sh
libqgsttools_p.so.1.0.0                    xsltConf.sh

**Comment by ccordoba12** [comment]
This doesn't seem a problem with Spyder but with your CentOS installation. For examples, please see:

1. https://forums.fedoraforum.org/showthread.php?277702-Cannot-yum-upgrade-due-to-a-python-module
2. https://bugzilla.redhat.com/show_bug.cgi?id=1263465
