### ISSUE TITLE
Find in Files error

### ISSUE THREAD

**Issue by PowerPlum** [spyder-ide/spyder#5745]
## Description

**What steps will reproduce the problem?**

1. Create array with 600,000 data points
2. Plot using matplotlib using code below:

import matplotlib as mpl
import numpy as np

number_of_data_points = 50000          # Good
number_of_data_points = 55000          # Good
number_of_data_points = 57000          # Good
#number_of_data_points = 60000          # Crashed
#number_of_data_points = 70000          # Crashed
#number_of_data_points = 75000          # Crashed
#number_of_data_points = 100000          # Crashed

time = np.array(range(0, number_of_data_points))
data = np.random.rand(number_of_data_points)

_figsize = (9, 6)
_FigureDPI = 450
_title = "Test PLot"
_xaxis_title = "Time (s)"
_yaxis_title = "Amplitude (-)"

fig, plotAr = mpl.pyplot.subplots(2, figsize=_figsize)
plotAr[0].plot(time, data, linewidth=0.5)
plotAr[0].set_title(_title)
plotAr[0].set_xlabel(_xaxis_title)
plotAr[0].set_ylabel(_yaxis_title)
plotAr[0].grid(color='gray', linestyle='--', linewidth=0.5)
#
_frequency =1.0 / (2 * number_of_data_points//2) * (np.array(range(0, number_of_data_points//2)))
_spectraDS = np.fft.fft(data)
_spectra = 2.0/len(_spectraDS) * np.abs(_spectraDS[0:len(_spectraDS)//2])
_phase = np.angle(_spectraDS[0:len(_spectraDS)//2])

PPlot = plotAr[1].plot(_frequency, _phase,
                       label='Phase', linewidth=0.5, color='lightgreen', zorder=2)
AmpAxes = plotAr[1].twinx()
APlot = AmpAxes.plot(_frequency, _spectra,
                        label='Amplitude Spectra', linewidth=0.75, color='darkblue', zorder=1)
#
plotAr[1].set_xlabel("Frequency (Hz)")
AmpAxes.set_ylabel(_yaxis_title)
plotAr[1].set_ylabel("Phase (radians)")
plotAr[1].set_yticks([-np.pi, -np.pi/2.0, 0.0, np.pi/2.0, np.pi])
plotAr[1].set_yticklabels([r'$-\pi$', r'$-\frac{\pi}{2}$', r'0.0', r'$\frac{\pi}{2}$', r'$\pi$'])
plotAr[1].grid(color='gray', linestyle='--', linewidth=0.5)
fig.tight_layout()
#
PlotLabels = APlot + PPlot
Labels = [l.get_label() for l in PlotLabels]
plotAr[1].legend(PlotLabels, Labels, loc='upper right', fancybox=True, framealpha=0.5, fontsize='small')
#
mpl.pyplot.savefig('Time_trace and spectra.png', dpi=_FigureDPI)
mpl.pyplot.close('all')

**What is the expected output? What do you see instead?**

Saved graph
It appears the limit is around 57,000 data points. How can this be made bigger to plot half a million data points?

**Please provide any additional information below**

Suggestions on web say add following line:

mpl.rcParams['agg.path.chunksize'] = 10000

This has no observable effect

TypeError: expected str, bytes or os.PathLike object, not NoneType

Traceback (most recent call last):

  File "<ipython-input-11-38fa15fb216c>", line 36, in <module>
    mpl.pyplot.savefig('Time_trace and spectra.png', dpi=_FigureDPI)

  File "c:\python\lib\site-packages\matplotlib\pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)

  File "c:\python\lib\site-packages\matplotlib\figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)

  File "c:\python\lib\site-packages\matplotlib\backend_bases.py", line 2259, in print_figure
    **kwargs)

  File "c:\python\lib\site-packages\matplotlib\backends\backend_agg.py", line 507, in print_png
    FigureCanvasAgg.draw(self)

  File "c:\python\lib\site-packages\matplotlib\backends\backend_agg.py", line 430, in draw
    self.figure.draw(self.renderer)

  File "c:\python\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "c:\python\lib\site-packages\matplotlib\figure.py", line 1295, in draw
    renderer, self, artists, self.suppressComposite)

  File "c:\python\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "c:\python\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "c:\python\lib\site-packages\matplotlib\axes\_base.py", line 2399, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)

  File "c:\python\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
    a.draw(renderer)

  File "c:\python\lib\site-packages\matplotlib\artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)

  File "c:\python\lib\site-packages\matplotlib\lines.py", line 781, in draw
    renderer.draw_path(gc, tpath, affine.frozen())

  File "c:\python\lib\site-packages\matplotlib\backends\backend_agg.py", line 167, in draw_path
    raise OverflowError("Exceeded cell block limit (set 'agg.path.chunksize' rcparam)")

OverflowError: Exceeded cell block limit (set 'agg.path.chunksize' rcparam)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.9.1, PyQt5 5.9 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is a problem with Matplotlib, not with Spyder.

> How can this be made bigger to plot half a million data points?

I don't think Matplotlib is able to handle that many points. You can try other libraries like

* Pyqtgraph: http://www.pyqtgraph.org/
* GuiQwt: https://github.com/PierreRaybaut/guiqwt/
* Datashader: https://github.com/bokeh/datashader/ (I think this one doesn't work in Spyder but only in the Jupyter notebook).

I'm closing this issue because it's not a Spyder bug.

**Comment by bcolsen** [comment]
@PowerPlum 

I got 1,000,000 points by going to 100,000 chunksize:
```
mpl.rcParams['agg.path.chunksize'] = 100000
```

![time_trace and spectra](https://user-images.githubusercontent.com/10513354/32806619-64f84c40-c94a-11e7-995e-0ef6a8052716.png)
