### ISSUE TITLE
scipy.stats not working

### ISSUE THREAD

**Issue by mra196** [spyder-ide/spyder#5747]
## Description

I wanted to use scipy.stats module but it was not in the list and when I entered
scipy.stats.linregress(x, y)
It returned an error
AttributeError: module 'scipy' has no attribute 'stats'

I even updated my spyder but didn't solve the issue. Could you please advise on this matter?

Thanks.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
You need to do this to use `scipy.stats`

```python
import scipy.stats
scipy.stats.linregress(x, y)
```

**Comment by mra196** [comment]
So you mean unlike many other modules such as scipy.optimize which I can simply use after importing scipy (and not scipy.optimize), scipy.stats requires to be imported separately from scipy?

**Comment by ccordoba12** [comment]
I tried on my side and yes, that seems to be the case. However, please note that this is not a problem with Spyder but with Scipy, so you should be better by asking on the Scipy Github repo.
