### ISSUE TITLE
Crash of numpy in ubuntu

### ISSUE THREAD

**Issue by Vkomini** [spyder-ide/spyder#5749]
## Description

**What steps will reproduce the problem?**

1. Importing an image 
2. Running a convolution

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/vangjush/.local/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 906, in <lambda>
    clear_variables))
  File "/home/vangjush/.local/lib/python2.7/site-packages/spyder/plugins/ipythonconsole.py", line 948, in execute_code
    sw.sig_prompt_ready.disconnect()
TypeError: disconnect() failed between 'sig_prompt_ready' and all its connections

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.9.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
It's the same error as the one you just reported. Please don't open more error about it.

Until we fix, you can avoid using dedicated consoles or downgrade to Spyder 3.2.3.
