### ISSUE TITLE
Improve working directory dropdown box

### ISSUE THREAD

**Issue by hongshaoyang** [spyder-ide/spyder#5750]
## Description of problem

The dropdown box that lists recent working directories is not very friendly as the width of the box is fixed. If the list of recent working directories is wide, the text is cut off with no way to scroll to the right to see what folder the list items are.

See screenshot below:
![Image of working directory being blocked](https://i.imgur.com/KciVXgX.png)

As you can see, there is no way to tell what is to the right of the cut off text.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6
* Qt Version: 7.7.3
* PyQt Version: 5.9
* Operating system:  macOS Sierra (10.12.6)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by jnsebgosselin** [comment]
Would adding tooltips to each item of the drop-down list showing the full path be a viable solution to this problem? Something like:

![infobulle_wordir_cb](https://user-images.githubusercontent.com/10170372/32842562-61cd37f0-c9eb-11e7-8331-ddb22ec6ec1c.gif)

**Comment by ccordoba12** [comment]
Good idea! I think it's a great usability improvement, and better than simply adding a horizontal scrollbar.

@goanpeca, what do you think?

**Comment by goanpeca** [comment]
@ccordoba12 yep looks good, gofor it @jnsebgosselin :-)

**Comment by jnsebgosselin** [comment]
@ccordoba12 and @goanpeca Alright, working on it! :D
