### ISSUE TITLE
 Static Code Analysis raise an error in Spyder 4.0 (From Master in Github)

### ISSUE THREAD

**Issue by augustosisa** [spyder-ide/spyder#5751]
## Description

**What steps will reproduce the problem?**

1. I was making a Static Code Analysis, and this error was raised. 
2. The code was split horizontally
3. 

**What is the expected output? What do you see instead?**

After restart Spyder, everything is fine. 

**Please provide any additional information below**

  File "C:\Anaconda2\lib\site-packages\spyder\plugins\editor.py", line 1777, in opened_files_list_changed
    action.setEnabled(enable)
  File "C:\Anaconda2\lib\site-packages\spyder\utils\qthelpers.py", line 456, in newfunc
    result = attr(*args, **kwargs)
RuntimeError: wrapped C/C++ object of type SpyderAction has been deleted

## Version and main components

* Spyder Version: 4.0.0.dev0 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  5.1.0 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. Are you using our latest master? I think this was already fixed.

**Comment by CAMGerlach-Baron** [comment]
Might not be related to your issue, but I do recall reports (including my own) a bit back of errors on certain platforms thrown by `pylint` 1.6.x and the latest members of the Spyder 3.2.x series during static analysis that were resolved in 1.7.2+; not sure if this is the case for the 4.x branch.

**Comment by CAM-Gerlach** [comment]
Please confirm this isn't fixed in the latest `master`; otherwise, this will likely be closed in a few days. Thanks!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
