### ISSUE TITLE
AttributeError is thrown when trying to get help of an object

### ISSUE THREAD

**Issue by TemiLee** [spyder-ide/spyder#5755]
## Description

**What steps will reproduce the problem?**

1. when i search ducument in the help pane it has error
2. after i restart spyder the help pane is ok

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/Cellar/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 92, in validate
    valid = self.is_valid(qstr)
  File "/usr/local/Cellar/anaconda3/lib/python3.6/site-packages/spyder/plugins/help.py", line 74, in is_valid
    return shell.is_defined(objtxt, force_import=True)
  File "/usr/local/Cellar/anaconda3/lib/python3.6/site-packages/spyder/widgets/internalshell.py", line 467, in is_defined
    return self.interpreter.is_defined(objtxt, force_import)
  File "/usr/local/Cellar/anaconda3/lib/python3.6/site-packages/spyder/interpreter.py", line 312, in is_defined
    namespace=self.locals)
  File "/usr/local/Cellar/anaconda3/lib/python3.6/site-packages/spyder/utils/dochelpers.py", line 315, in isdefined
    attr_not_found = not hasattr(eval(base, namespace), attr)
  File "<string>", line 1, in <module>
AttributeError: module 'sympy.integrals.integrals' has no attribute 'integrals'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by Jeroendevr** [comment]
Thank you for posting this bug. Could you share some code you are trying to run? Or provide more details about how to reproduce this error? Do you can reproduce this error yourself?

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this error in our next release.

@dalthviz, another easy one for you. Please catch `AttributeError` at the right place.

**Comment by Jeroendevr** [comment]
@ccordoba12 How can you already identify the problem. When I try to reproduce the issue I am not able to.
