### ISSUE TITLE
Ctrl-PageUp/Down does not go through tabs in Spyder 4.x

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#5756]
## Description

On Spyder 3.2.4 (or git branch `3.x`), I can use Ctrl-PageUp and Ctrl-PageDown to cycle through the editor tabs in the order they are displayed at the top. This does not work any more with v4 (git master).

Is this on purpose?

## Version and main components

* Spyder Version: git master
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.4 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.0.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
Are the shortcuts doing something else or don't they work at all?

**Comment by jitseniesen** [comment]
They're not doing anything as far as I can see.

**Comment by jitseniesen** [comment]
I think it is commit 3ff6e179c "Move autoinsert quotes logic to quote editor extension" which disabled the Ctrl-PageUp/PageDown shortcuts. It does not look like this was intentional. @rlaverde ?

**Comment by rlaverde** [comment]
It  wasn't intentionally, It's caused because the `KeyPressEvent` is accepting the event so this it's not handed by the parent, but not accepting the event cause #5139, I think the solution is to ignore it when pressing Modifiers.

**Comment by jitseniesen** [comment]
Wow, that's fast. I checked and it works. Thanks @rlaverde !
