### ISSUE TITLE
spyder launch

### ISSUE THREAD

**Issue by riyaj8888** [spyder-ide/spyder#5761]
##spyder is not launching

i installed anaconda,but spyder is not opening,even it doesn't show any error ,just show buffering for a while then stops,please help me to solve this

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by CAMGerlach-Baron** [comment]
Unfortunately, without any information given that would help people narrow down the error, you won't be able to get much specific help, at least that Google wouldn't have told you.

I'm still a beginner too, but here's some basic questions to start you off that might help people help you:

- You say it is "buffering" and never launches. What do you mean by this, specifically? Describe how you launched Spyder, exactly what you see, and how long you waited before presuming it not to work.
- What version (number) of Anaconda did you install?
- Where did you install it? What is the path to your root anaconda directory?
- Do other anaconda packages/applications work? If you launch a prompt, does e.g. running `conda` or `python` produce the expected result?
- What platform (OS Version, etc) are you running on?
- Anything else specific to your setup you can think of that might relate to the problem?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
