### ISSUE TITLE
Make arrow-key selection in multiple-option tab-completion dialogs "roll over"

### ISSUE THREAD

**Issue by CAMGerlach-Baron** [spyder-ide/spyder#5763]
A bit of a long winded name, but essentially a simple fix (hopefully). In tab completion dialogs, when multiple completion options are possible, it would be a huge efficiency boost to have scrolling the list with up or downarrow "roll over" when reaching the end; i.e., when the first item is selected (as when first getting the dialog), pressing "uparrow" will select the last item, and continue up from there with subsequent presses; similarly, "downarrow" on the last item will go back to the beginning. 

With a list of say n=3 items, it means that any item can be reached with at most one keypress vs. two, and with n=5 with at most two keypresses vs. four. In particular, it can save a lot of time being able to hit "up" and go directly to the last item, if you know that's the one you want. 

(Platform: Windows 8.1/10 x64 Pro/Ent, in case it matters...) Thanks!

**Comment by ccordoba12** [comment]
Interesting idea, but some will have to step up and try to implement it.

**Comment by jnsebgosselin** [comment]
@ccordoba12 It is an interesting idea indeed, but is there any benefit of implementing that while we can actually use the <kbd>End</kbd> and <kbd>Home</kbd> keys to go to the last or first item of the list?

If you still want to go with that idea, I can do it though. I'm currently trying to understand the `CompletionWidget`  for my own project, so it should be quick and easy.

**Comment by ccordoba12** [comment]
> If you still want to go with that idea, I can do it though

I think what's neat about this idea is the fact that you don't need to leave the Up/Down arrow keys to keep moving through the completion entries (using the Home/End keys takes a little bit more time).

I agree with this, so if you want to implement it please do it for master.

**Comment by jnsebgosselin** [comment]
@ccordoba12 alright, good point. Also, it's less confusing to not have to switch keys.

**Comment by CAMGerlach-Baron** [comment]
Whew, that was fast. Thanks for implementing, @jnsebgosselin . I had actually (after much toil, due to being a complete n00b at anything resembling GUI-related programming) found the relevant bit of the code was was naively thinking of implementing it in essentially the same way, but figuring I'd missed something silly being a n00b, so its good to see that I wasn't too far off after all that, haha. It would have taken me way more time to get another dev environment and everything setup than to actually implement it the tweak itself, so glad you could help out.

**Comment by CAMGerlach-Baron** [comment]
Any particular reason @ccordoba12 it shouldn't be backported to 3.2.5? No big rush, just curious.

**Comment by ccordoba12** [comment]
I don't want to introduce too much UX changes in our 3.x branch, so users don't get surprises when moving from one minor release to another.
