### ISSUE TITLE
Unable to see attributes from a class in the spyder variable explorer window

### ISSUE THREAD

**Issue by AlexandreMarcotte** [spyder-ide/spyder#5767]
## Description

**What steps will reproduce the problem?**

1.  Create a class with some attributes
2.  Create an object from this class
3. Click on the object of this class in the variable explorer (which will be absent if the checkbox: 'Excluded unsupported data type' is checked.

**What is the expected output? What do you see instead?**
Expected: 
See the attributes value of the class

Instead: _
- I see an error pop up that says: 
 Spyder was unable to retrieve the value of this variable form the console
The error mesage was: 
AttributeError('Can't get attribute 'THENAMEOFMYCLASS' on ",)

**Please provide any additional information below**
- It was working properly some days ago
- I run into an error about not being able to go to definition that seems to be fix by reinstalling Anaconda 2 days ago

## Version and main components

* Spyder Version: 3.2.2   (Note: I had the problem in 3.2.4 so I downgraded to this version to test because someone I know don't have this problem with this version)
* Python Version: 3.5.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows (10)

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Please post a reproducible example.

**Comment by CAM-Gerlach** [comment]
A quick update: In Spyder 3.2.7, with the ``cloudpickle``, etc changes, the aforementioned error is not generated and everything works fine. Example I used to test:

```python
class foo:
    eggs = "Hello World!"
    
    def __init__(self):
        self.bar = 0
    
    def spam(n):
        return ["spam" for _ in range(n)]

f = foo()
```
