### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by geneing** [spyder-ide/spyder#5783]
## Description

**What steps will reproduce the problem?**

1. Random crash while woking
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python2.7/dist-packages/spyder/widgets/calltip.py", line 117, in hideEvent
    self._cursor_position_changed)
TypeError: 'instancemethod' object is not connected

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.12
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.12 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  0.7.6.1 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Please update to use PyQt5 instead of PyQt4. Although we still try to support PyQt4, it's not maintained anymore and we have not seen this error in PyQt5.
