### ISSUE TITLE
Problem when copy dictionary data on the Variable Explorer

### ISSUE THREAD

**Issue by Issoufa** [spyder-ide/spyder#5785]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.0.0.1/envs/python2.7/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 861, in keyPressEvent
    self.paste()
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.0.0.1/envs/python2.7/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1135, in paste
    self.import_from_string(cliptext, title=_("Import from clipboard"))
  File "/home/x86_64-unknown-linux_ol7-gnu/anaconda-5.0.0.1/envs/python2.7/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1122, in import_from_string
    blacklist=list(data.keys())))
AttributeError: 'list' object has no attribute 'keys'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
What data were you trying to copy to Spyder?

**Comment by Issoufa** [comment]
I have try to copy data of a dictionary with crl+c. Then this error occurs. Thanks Issoufou ABDOU AMADOU



      De : Carlos Cordoba <notifications@github.com>
 À : spyder-ide/spyder <spyder@noreply.github.com> 
Cc : Issoufa <issoufou_abdou1@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Samedi 18 novembre 2017 18h03
 Objet : Re: [spyder-ide/spyder] Problem with copying data on spyder (#5785)
   
What data were you trying to copy to Spyder?—

**Comment by CAM-Gerlach** [comment]
I could not manage to reproduce this on the latest version of Spyder, 3.2.7, both copying and pasting both a dictionary and a list several different ways and places. Therefore, it seems likely that either the source of the error has been fixed or averted, or the information given is not specific enough to allow it to be easily reproduced. Therefore, I'm closing this, unless @Issoufa is able to follow up with more specific information that replicates this on the latest Spyder, or @ccordoba12 thinks otherwise.
