### ISSUE TITLE
Radiobutton/IntVar() malfunction with tkinter in certain Spyder version 

### ISSUE THREAD

**Issue by hugoess** [spyder-ide/spyder#5787]
## Description

**What steps will reproduce the problem?**

1. I ran the following script(just copied from a textbook teaching you use tkinter to build up a GUI)

the expected output of the GUI program is that, if I toggle one of the three radiobuttons, the background color shall be switched to the corresponding color, but it doesn't do so in this version of Spyder/Python3.

The interesting thing is that if I ran the exactly same script on the other PC, with
* Spyder Version: 3.1.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

It worked perfectly just as the textbook indicated.

I feel it really creepy and tried out different ways by myself with 20+ hours, and I finally give up and here by subscribing this issue.

best regards,
Lu

```python
#%%


# =============================================================================
# Chapter 1-8 Checkbuttons IntVar() select()
# =============================================================================

import tkinter as tk
from tkinter import ttk
from tkinter import *


win = tk.Tk()

#aLabel = ttk.Label(win, text = 'A Label')
#aLabel.grid(column = 0, row = 0)

def clickMe():
    global name
    action.configure(text= 'Hello ' + nameEntered.get() + ' ' + numberChosen.get())
    print(nameEntered.get())
    action.configure(state = 'disable')

#    aLabel.configure(foreground = 'red')
    
action = ttk.Button(win, text = 'Click Me!', command = clickMe)
action.grid(column = 2, row = 1)

#name = tk.StringVar()
#nameEntered = ttk.Entry(win, width=12, textvariable=name)

ttk.Label(win, text = 'Enter a name: ').grid(column = 0, row = 0)
nameEntered = Entry(win, width=12)
nameEntered.grid(column = 0, row=1)



Label(win, text = 'Choose a number:').grid(column = 1, row = 0)
number = tk.StringVar() #ここでnumberをStringと定義したので、1,2,4,42が表示される時に、Stringになる
numberChosen = ttk.Combobox(win, width = 12, textvariable = number, state= 'readonly')
numberChosen['values' ] = (1,2,4,42,100)
numberChosen.grid(column=1, row = 1)
numberChosen.current(2)

chVarDis = tk.IntVar()
check1 = tk.Checkbutton(win, text= 'Disabled', variable = chVarDis, state = 'disabled')
check1.select()
check1.grid(column=0, row = 4, sticky = W)

chVarUn = tk.IntVar()
check2 = tk.Checkbutton(win, text= 'Unchecked', variable = chVarUn)
check2.deselect()
check2.grid(column=1, row = 4, sticky = W)

chVarEn = tk.IntVar()
check3 = tk.Checkbutton(win, text= 'Enabled', variable = chVarEn)
check3.select()
check3.grid(column=2, row = 4, sticky = W)

win.title('Python GUI')
#win.resizable(0,0)  # 4 Disable resizing the GUI




COLOR1 = 'Blue'
COLOR2 = 'Gold'
COLOR3 = 'Red'

radVar1 = tk.StringVar()

def radcall():
#    radVar1.set("1")
#    global radVar1
    radSel = radVar1.get()
    if radSel == 1:
        win.configure(background = COLOR1)
    elif radSel == 2:
        win.configure(background = COLOR2)
    elif radSel == 3:
        win.configure(background = COLOR3)
    print(radVar1)
    print(radVar1.get())
    print(radSel)
#    print('Hey')
#    print(rad1['value'])
    

#def radcall():
##    radVar1.set("1")
#    global radVar1
#    radSel = radVar1.get()
#    if rad1['value'] == 1:
#        win.configure(background = COLOR1)
#    elif rad1['value'] == 2:
#        win.configure(background = COLOR2)
#    elif rad1['value'] == 3:
#        win.configure(background = COLOR3)
#    print(radVar1)
#    print(radVar1.get())
##    print('Hey')
##    print(rad1['value'])
    


radVar1= tk.IntVar()
#radVar2 = tk.IntVar()
#radVar3 = tk.IntVar()
#radSel = 1

rad1 = tk.Radiobutton(win, text = COLOR1, variable = radVar1, value = 1, command = radcall)
rad1.deselect()
rad1.grid(column=0, row = 5, sticky = W)

rad2 = tk.Radiobutton(win, text = COLOR2, variable = radVar1,  value = 2,command = radcall)
rad2.deselect()
rad2.grid(column=1, row = 5, sticky = W)

rad3 = tk.Radiobutton(win, text = COLOR3, variable = radVar1,  value = 3,command = radcall)
rad3.deselect()
rad3.grid(column=2, row = 5, sticky = W)

#radVar1.set("1")

#radVar1 = tk.IntVar()
#win.set_focus()
#nameEntered.focus()
win.mainloop()
```

2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
I fail to see how this is related to Spyder, sorry. It seems like a problem with Tk.

**Comment by CAM-Gerlach** [comment]
To confirm that and help you narrow down whatever the problem really is, I would think you could just run it in a regular python or iPython console from e.g. your system shell on the two machines, without Spyder, and observe the results.

**Comment by hugoess** [comment]
Thanks for the kind comments for this problem.

Yesterday I upadated my anaconda package to the newest version(Spyder 3.2.4 & python 3.6.3) with command “conda update —all”. And I ran this script and observed the same outcome as in Spyder 3.2.3 & python 3.6.2 that the value of radiobutton is not passed to the tk.IntVar() and thus the function based on radiobutton regulation doesn’t work.

Besides Spyder 3.1.4 & python 3.6.1 environment, I tested the same script with Pycharm 2017.2 built & python 3.6.3 and my expected outcome was observed. 
From my perspective and my minor knowledge on programming, I would guess that there is something occurs in Spyder. And I’m sorry if it’s not like this and looking forward to figure out the real mechanism.

**Comment by hugoess** [comment]
Right now I confirmed again with jupyter notebook and it worked. (On the first PC which has ran with Spyder 3.2.4 & python 3.6.3|anaconda custom (64-bit)| and failed)

**Comment by ccordoba12** [comment]
We don't have time to help you debug this, sorry. Please let us know if you find how Spyder is interfering with Tk.

**Comment by hugoess** [comment]
Thanks for the effort.

I’m just very curious about that why certain version of Spyder coundn’t show the same result as former version and other IDEs.
Have you successfully reproduced the output?
If other PCs couldn’t, then I think it’s something wrong with the particular PC.

**Comment by CAM-Gerlach** [comment]
You don't have any other machine you can try it on with a fresh install? Or even a VM? I can't find `tkinter` on conda or conda-forge or I'd run it for you and report the results.

**Comment by hugoess** [comment]
I’m not sure if the following photos could better explain what the problem is.(not sure if it could be defined as an interference.)

Case 1
Spyder 3.2.3 & python 3.6.2 Environment(PC 1) run a Spyder cell (in parentheses of #%%)
https://i.imgur.com/ufJfQuG.jpg
https://i.imgur.com/NkRyy8I.jpg

Case 2
Spyder 3.1.4 & python 3.6.1 Environment( PC 2) run a Spyder cell (in parentheses of #%%)
https://i.imgur.com/HLpWJh1.jpg
https://i.imgur.com/md6gOiP.jpg

Case 3
Pycharm 2017.2 & python 3.6.3|anaconda custom (64-bit)| Environment(PC 1)
https://i.imgur.com/0QdgITE.jpg


3 cases using the same script and only case 1 failed.
Run with jupyter notebook on PC1 shows Case 2&3,
But with Spyder 3.2.4 shows case 1.

**Comment by CAM-Gerlach** [comment]
The only pattern of interference I see on your screen is the one due to using a camera to take a photo of a computer display, heh...protip: Windows has such thing as snipping tool and printscreen, if you are not aware.

I think we understand that part, and it certainly may be associated with Spyder somehow. If you can actually dig into the code and see what's actually going on and where Spyder's playing a role, than maybe someone can fix it (or you are welcome to take a stab at it yourself, of course). The fact that it was something changed between those two versions might help you narrow it down; you can do so further by eliminating as many different variables (machine, python, package and spyder versions) as you can between the working and non working environments, and then at that point the diffs might be minimal enough to point you in the right direction. Best of luck!

**Comment by hugoess** [comment]
@CAM-Gerlach Thanks for the suggestion, I'm now trying with a third PC.

For about tkinter, I think it is a standard python GUI toolkit and is included in python. you can check it with a python -m tkinter command.
 if you don't have one,  i just uploaded here ;-)
https://github.com/hugoess/tkinter-package

**Comment by CAM-Gerlach** [comment]
Okay, thanks. In case that didn't clue you in, I'm a n00b when it comes to GUIs and just a random Spyder user besides, so I really don't think I can be much more help than whatever I have already. Hopefully you get it working, or at least isolate the problem.

**Comment by hugoess** [comment]
@CAM-Gerlach Thank you for your encouraging words!

Actually I'm really a novice/noob( started within 2 months) with Python and I found Spyder is a really useful, helpful and easy-to-start-with IDE in scientific analysis.
 
For now I will choose to just continue my development on the working environment and when somehow I become more intermediate( like knowing how to use debug tools), I will try to figure this out at that time.

BTW, I see you commenting at issues here, so you are also a member of Spyder maintenance team or so?

**Comment by CAM-Gerlach** [comment]
Haha, nope, I'm no different from you—I' hope I'm not sending the wrong impression...:/ Like I mentioned above, I'm just a run of the mill Spyder user, and a beginner at that.  I haven't even submitted my first PR yet; I just felt bad I was submitting long and detailed issues for others to fix without helping at all in return, so I try to do what I can triaging issues and helping others with their problems while working on some simple fixes/enhancements on the side, all while I'm not doing my actual job as a researcher.

**Comment by hugoess** [comment]
Good of you, i think somehow you are having a meaningful time XD

**Comment by ccordoba12** [comment]
Closing as this is not a Spyder bug.
