### ISSUE TITLE
IDE Crashes

### ISSUE THREAD

**Issue by IamMayankThakur** [spyder-ide/spyder#5788]
When using spyder on Ubuntu 16.04, upon using libraries like matplotlib to plot graphs, after the graph is displayed, to save the graph, when I right click on it, the IDE crashes.

I tested this a few times and it happened every time.

**What is the expected output? What do you see instead?**

Expected output was the context-menu with the option of saving the graph, but instead the IDE crashed.

**Please provide any additional information below**
It gave a "Segmentation Fault"

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6.2
* Operating system: Ubuntu 16.04

![haha](https://user-images.githubusercontent.com/24970283/32978124-c0279d5e-cc61-11e7-9575-7e7f1f7b5d7f.png)

**Comment by ccordoba12** [comment]
Questions:

1. Are you using Anaconda or your system packages?
2. How are you saving plots? Please post a simple video of what you're doing because the screenshot you posted is really useless.

**Comment by CAM-Gerlach** [comment]
Also, I imagine copying the text from the Help > Dependencies dialog (as well as your Qt and PyQt versions, just in case) wouldn't hurt.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
