### ISSUE TITLE
spyder crash before launch when qt4 and qt5 are installed

### ISSUE THREAD

**Issue by nonamedotc** [spyder-ide/spyder#5795]
## Description of your problem

If Fedora (26 or 27) has python3-pyqt4 installed, spyder3 will not launch without qt4-webkit. 

If python3-qt4 is not installed, then spyder3 will launch without any issues whatsoever. I can work with spyder without any issues with just qt5.

**What steps will reproduce the problem?**

1. Install spyder
2. Install python3-qt4 (this is the package name in Fedora)
3. Launch spyder

**What is the expected output? What do you see instead?**
Expected output is that spyder launches without any issues.

What I see instead is this - 
```
$ spyder3
Traceback (most recent call last):
  File "/usr/bin/spyder3", line 3, in <module>
    start.main()
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 144, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/usr/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 43, in <module>
    from PyQt4.QtWebKit import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt4.QtWebKit'
```

**Please provide any additional information below**

The file where the crash seems to happen is **qtpy/QtWebEngineWidgets.py**. Even with *qt4* installed, I can succesfully import everything qtpy/QtWebEngineWidgets.py used to check for pyqt5.

The section after ImportError works fine on an ipython console.
```
if PYQT5:
    try:
        from PyQt5.QtWebEngineWidgets import QWebEnginePage
        from PyQt5.QtWebEngineWidgets import QWebEngineView
        from PyQt5.QtWebEngineWidgets import QWebEngineSettings
    except ImportError:
        from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
        from PyQt5.QtWebKitWidgets import QWebView as QWebEngineView
        from PyQt5.QtWebKit import QWebSettings as QWebEngineSettings
        WEBENGINE = False
```
Output from an ipython console - 

```
In [1]: from PyQt5.QtWebEngineWidgets import QWebEnginePage
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-00878ab2de5d> in <module>()
----> 1 from PyQt5.QtWebEngineWidgets import QWebEnginePage

ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'

In [2]: from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
In [3]: from PyQt5.QtWebKitWidgets import QWebView as QWebEngineView
In [4]: from PyQt5.QtWebKit import QWebSettings as QWebEngineSettings
```

**Just to be clear**
Spyder works perfectly with just PyQT5. *qt4*webkit is (stragely) needed ONLY when qt4 and qt5 are installed. Just because qt4 is installed, it does not look like qt5 checks should fail but seems to fail.

Should this report be filed against qtpy instead?

## Versions and main components

* Spyder Version: 3.2.4 (and earlier)
* Python Version: 3.6.3
* Qt Version:5.9.2
* PyQt Version: 5.9.1
* Operating system: Linux (Fedora 27).

## Dependencies
```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by nonamedotc** [comment]
there may be some more relevant information in this downstream bug report.

https://bugzilla.redhat.com/show_bug.cgi?id=1510143

**Comment by ccordoba12** [comment]
This bug is caused by Pandas. I left comments on the Redhat bug you posted about it. Please also take a look at pandas-dev/pandas#17723.

**Comment by nonamedotc** [comment]
Thanks!
