### ISSUE TITLE
UnicodeEncodeError when using a project with non-ascii characters on it

### ISSUE THREAD

**Issue by 35liying** [spyder-ide/spyder#5799]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\lenovo\Anaconda3\envs\python222\lib\site-packages\spyder\plugins\projects.py", line 147, in <lambda>
    lambda v: self.main.update_window_title())
  File "C:\Users\lenovo\Anaconda3\envs\python222\lib\site-packages\spyder\app\mainwindow.py", line 1299, in update_window_title
    title = '{0} - {1}'.format(path, title)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-15: ordinal not in range(128)
  elif res.tzname and res.tzname in time.tzname:

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4

**Comment by CAM-Gerlach** [comment]
Google translated title: Please help analyze this error.

Very well. I'm no expert, but looking at the error, your Python version (2.x) and glancing at the relevant file, my uneducated guess would be that you have a couple non-ASCII (e.g. Unicode) characters on your project path that Spyder is trying to set as part of your window title, which in Python 3 would probably work just fine, but in Python 2 they attempt to get converted to ASCII for a standard/non-unicode string which fails...again, just a guess, as I neither use Python 2 nor non-ASCII directory/file names, but it is very likely something related to that.

I exclusively use Python 3 which is all Unicode, all the time, so I can't speak for how this could be best handled in the code if at all, but for the time being I would think that either renaming/moving your project path to somewhere without non-ASCII characters, or switching to Python 3 would probably mitigate it for the time being.

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to solve this problem in a future release.

To temporally solve this, please use directories with Latin letters for your projects.
