### ISSUE TITLE
Spyder irresponsive after returning from screen saver

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#580]
_From [rafael.g...@gmail.com](https://code.google.com/u/117858512978056230339/) on 2011-03-10T15:49:18Z_

What steps will reproduce the problem?

1. I have just spyder open 
2. I do not use the computer and the screen saver starts
3. I press a key or move the mouse to end the screen saver What is the expected output? What do you see instead? I click anywhere and it does not respond until I minimize and maximize the main window - after that, it starts working again.

I noticed that in other non-specific situations, the same happens after spyder losing focus - it becomes non-responsive when you try to focus on it again, but minimizing-maximizing the main window solves the problem What version of the product are you using? On what operating system? Spyder 2.0.6. I get the same behavior on two different computers, one with ubuntu 10.04 and the other 10.10 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=580_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:29:09Z_

**Labels:** Cat-SpyderGUI

**Comment by goanpeca** [comment]
@ccordoba12 closing?

**Comment by ccordoba12** [comment]
Yes, sure.
