### ISSUE TITLE
what's the bug about?

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder#5801]
## Description

**What steps will reproduce the problem?**

1. just click the "open a New notebook" button
2. can not close new tab i just open

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "d:\python36\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "d:\python36\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "d:\python36\lib\site-packages\spyder_notebook\widgets\client.py", line 230, in get_kernel_id
    if session['notebook']['path'] == path:
TypeError: string indices must be integers

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAMGerlach-Baron** [comment]
The bug appears to be about the `spyder-notebook` plugin at least from first glance, not this base Spyder  package itself, so it would might be best if you made an issue over there instead (its under this same github organization), unless those that know better than me suggest otherwise.

**Comment by andfoy** [comment]
Issue moved to [spyder-ide/spyder-notebook #135](https://github.com/spyder-ide/spyder-notebook/issues/135) via [**ZenHub**](https://www.zenhub.com/)
