### ISSUE TITLE
Enabling sympy in an Ipython shell not working?

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#5802]
## Description

When I check the box in the preferences->Ipython Console->Advanced Settings->Use symbolic math

the console banner message reads as follows:

Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.1.0 -- An enhanced Interactive Python.

Populating the interactive namespace from numpy and matplotlib

These commands were executed:
from __future__ import division
from sympy import *
x, y, z, t = symbols('x y z t')
k, m, n = symbols('k m n', integer=True)
f, g, h = symbols('f g h', cls=Function)
**What steps will reproduce the problem?**

This suggests that x,y,z,t,k,m and n should all exist in the current namespace (as in fact should all of sympy). In practice only init_session seems to be there and in current sympy that is broken (see for example sympy#13418).

**What is the expected output? What do you see instead?**

Obviously the underlying error is with sympy and one would have expected it to work, but given that it isn't working, is there anyway for Spyder to warn the user that this is the case rather than showing the misleading banner signon message?

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAMGerlach-Baron** [comment]
The error message is printed by iPython, itself running inside of `qtconsole`, so I'm not sure it makes sense or even is really feasible for Spyder to intervene at least in that aspect.

**Comment by ccordoba12** [comment]
@gb119, as you point out, it's an upstream bug, so there's nothing we can do about it.
