### ISSUE TITLE
Drag to open file

### ISSUE THREAD

**Issue by jakobmoenster** [spyder-ide/spyder#5808]
## Description

**What steps will reproduce the problem?**

1. Drag a .py file into tabs-bar
2. 
3. 

**What is the expected output? What do you see instead?**
Open the file in a tab.
This error message

**Please provide any additional information below**

  File "C:\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2250, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. This bug was already fixed and the fix will be part of our 3.2.5 version.
