### ISSUE TITLE
Global Tasks

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#5812]
Placeholder and reminder of a series of tasks to do in the upcoming weeks:

- [ ] Add open collective badges and text to ALL spyder projects
   - [ ] Pywinpty
   - [ ] Loghub
   - [x] Spyder-Notebook
   - [ ] Spyder-Terminal
   - [ ] Spyder-Reports
- [ ] Add Gitter badge leading to spyder-ide/public room, to unify all projects under the same umbrella.
- [x] Remove any other Gitter channels
- [ ] Add donate button in FB
- [x] Add some header on FB
- [ ] Add some header on twitter

**Comment by ccordoba12** [comment]
I think we can pin a tweet on Twitter to be the first one in the timeline.

**Comment by ccordoba12** [comment]
I think this is solved now.
