### ISSUE TITLE
UnicodeDecodeError thrown when viewing Dataframes with non-ascii index

### ISSUE THREAD

**Issue by erbaoitaly** [spyder-ide/spyder#5833]
## Description

**What steps will reproduce the problem?**

1. check the data in the variable explorer
2. after several times
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/zhangjing/anaconda2/lib/python2.7/site-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 277, in data
    return to_qvariant(to_text_string(self.df_index[row]))
  File "/home/zhangjing/anaconda2/lib/python2.7/site-packages/spyder/py3compat.py", line 123, in to_text_string
    return unicode(obj)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb3 in position 5: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. This means that your Dataframe index has non-ascii characters and Spyder can't handle them. We'll try to fix this in a future release.

In the meantime, you should consider using Python 3 instead of Python 2 to process data with non-ascii characters.
