### ISSUE TITLE
thread/lock mechanism appeared bugged in the console, indeed!

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#5834]
I was trying lock mechanism through the following code:
```
from threading import Thread,Lock
from time import sleep

lock=Lock()

def mythread(arg,name):
  for i in range(arg):
    with lock:
      print(name,'i  ----> ',i)
    sleep(1)

def test():
  thread1 = Thread(target = mythread, args = (5,'thread1'))
  thread1.start()
  thread2 = Thread(target = mythread, args = (5,'thread2'))
  thread2.start()
  thread1.join()
  thread2.join()

test()
```
With a possible output (completely wrong) in the console
```
thread1 i  ----> thread2  0i  ----> 
 0
thread2 thread1i  ---->   i  ----> 1 
1
thread2thread1  i  ----> i  ---->   22

thread2 thread1i  ---->   i  ----> 3 
3
thread2 i  ---->  4
thread1 i  ---->  4
```
I expected nice print separation between the 2 threads (no overlap) in the console. But instead the print statements are scrambled. **Strangely it seems to be due to spyder, as in a python or ipython consoles it works properly**.
Any hint on this very strange behavior?

Last everything (win10), except python 3.5.3.

**Comment by sylvain-bougnoux** [comment]
It is the qt-console. I will submit there.

**Comment by ccordoba12** [comment]
Thanks!
