### ISSUE TITLE
Anaconda punishes people for using Python 3.5

### ISSUE THREAD

**Issue by Mathemilda** [spyder-ide/spyder#5837]
Anaconda developers push people into using latest version of Anaconda by claiming that the
option of working with Python 3.5 is creating an environment. In truth an earlier Anaconada
version can be used, but the option is hidden on the website. 
 An additional problem here is that some packages
do not work with Python 3.6 yet, like nltk for Natural Language Processing,
and keras developers for Deep Learning only recently claimed that their
library now cooperates with Python 3.6, although in practice is it not a
smooth ride. I have students who are learning and the environments for them
is additional burden. I wish you would have a choice for people what
Anaconda version to load with what Python. By the way people with Windows
10 complain that 5th Anaconda crushes. I directed them to Anaconda site but do
not know if they made it or switched to earlier version.
Sorry for belated response. I was extremely busy.
Best,
Mya

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Sorry, we're not affiliated with Anaconda anymore. Please report this problem there:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by Mathemilda** [comment]
But you still recommend Anaconda as a first way to install Spyder.

**Comment by ccordoba12** [comment]
Yes, but all the problems you mentioned are related to Anaconda, not to Spyder, so there's nothing we can do about them here.

**Comment by Mathemilda** [comment]
So if I what to know learn what are your current recommendations on Spyder installation I'm to open a new ticket, because on the following site not-Anaconda ways are called outdated?
https://pythonhosted.org/spyder/

**Comment by ccordoba12** [comment]
We're going to still recommend to use Anaconda in the future because 
it's the easiest way to install Spyder. But we're not responsible nor we 
can fix all Anaconda's shortcomings (such as the ones you listed).

**Comment by Mathemilda** [comment]
Oh, I see. Thanks anyway.
