### ISSUE TITLE
Resizing Windows becomes very slow

### ISSUE THREAD

**Issue by modulusmath** [spyder-ide/spyder#5839]
## Description of your problem
Resizing windows becomes unbearably slow

**What steps will reproduce the problem?**

1. Run lots and lots of python programs over the course of a few days w/o restarting
2. Restart Spyder makes it all  fast again

**What is the expected output? What do you see instead?**
When I try to resize the editor/ipython console window separator it could never resize/respond or take up to 30 seconds to do so.

**Please provide any additional information below**
I realize this is just anecdotal as far as how to repro.

$ps -p 7860  -o rss,cmd,command 
RSS CMD                         COMMAND
381656 /home/john/python/anaconda/ /home/john/python/anaconda/bin/python /home/john/python/anaconda/bin/spyder

$free -g
              total        used        free      shared  buff/cache   available
Mem:             23           4           1           0          18          18
Swap:            15           0          15

## Versions and main components

* Spyder Version:
3.24.

* Python Version:
Anaconda 6.1.0

* Qt Python 
3.6.2 64bits, Qt 5.6.2

* PyQt Version:
PyQt5 5.6 on Linux 

* Operating system:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
It seems you're consuming most of the RAM in your CPU when you

> Run lots and lots of python programs over the course of a few days w/o restarting

and that makes your system slow.

By restarting Spyder, you also kill and restart the IPython console kernels, which are in charge of running code. So, if you want to free memory but don't want to restart Spyder, simply restart your kernel once in a while.

**Comment by modulusmath** [comment]
Thanks - A good idea to restart the kernel once in  a while. Will give it a shot.
My system itself isn't not terribly slow, just the sliding of the separator it seems, not a major issue but I felt I should share it.
