### ISSUE TITLE
while opening Spyder throws an IPython console error:  ' An error occurred while starting the Kernel'

### ISSUE THREAD

**Issue by Amir-CA** [spyder-ide/spyder#5850]
**Last lines from my error message looks like this**

File "C:\Users\ABC\Anaconda3\lib\site‑packages\tornado\concurrent.py", line 34, in 
from tornado.util import raise_exc_info, ArgReplacer, is_finalizing
ImportError: cannot import name 'is_finalizing'

spyder version 3
Python version 3.6

I have ran
_conda update setuptools_

_spyder upgarde_ 

But nothing fixed the error

**Comment by ccordoba12** [comment]
conda install -f tornado

should fix this error.
