### ISSUE TITLE
error while setting file as working directory

### ISSUE THREAD

**Issue by aravindsasidharan** [spyder-ide/spyder#5853]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\DELL\Anaconda3\lib\site-packages\spyder\plugins\workingdirectory.py", line 286, in chdir
    os.chdir(directory)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\Now focus tut\\p'
Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 1132, in chdir
    os.chdir(directory)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'E:\\Now focus tut\\p'

Traceback (most recent call last):
  File "C:\Users\DELL\Anaconda3\lib\site-packages\spyder\plugins\explorer.py", line 102, in chdir
    self.treewidget.chdir(directory)
  File "C:\Users\DELL\Anaconda3\lib\site-packages\spyder\widgets\explorer.py", line 1135, in chdir
    except PermissionError:
UnboundLocalError: local variable 'PermissionError' referenced before assignment

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
I think this was fixed in our 3.2.4 version. Please update.
