### ISSUE TITLE
SPYDER  nbconvert>=4.0.0 missing

### ISSUE THREAD

**Issue by aaaaaacd** [spyder-ide/spyder#5855]
## Description

**What steps will reproduce the problem?**

While launching spyder,it would a problem''
![image](https://user-images.githubusercontent.com/32163791/33409956-e6dfdf96-d5b8-11e7-9745-e2a1bc7a672a.png)''
and can find this error in ''
![image](https://user-images.githubusercontent.com/32163791/33410021-46b3685c-d5b9-11e7-92c2-0bebbe1b8f60.png)
''
 But I have already installed nbconversion and can run ''import nbconvert''.

**What is the expected output? What do you see instead?**

I don't want to see the warning information once launching the spyder.
How to solve this problem or just make the disturbing note disapper?

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  None (NOK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
You probably have nbconvert installed in another Python interpreter. You need to verify that same interpreter Spyder is using is the one where you are installing packages.

**Comment by aaaaaacd** [comment]
Wow,I change the pythonpath manager and installed again,and it works.I consider it maybe the correct way. And thanks a lot.
