### ISSUE TITLE
Layout switching error

### ISSUE THREAD

**Issue by ratnadeepb** [spyder-ide/spyder#5858]
## Description

**What steps will reproduce the problem?**

1. Switching Layout to a pre saved custom one
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/ratnadeepb/app/miniconda3/envs/python3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1769, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "/home/ratnadeepb/app/miniconda3/envs/python3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1889, in quick_layout_switch
    self.setup_default_layouts(index, settings)
  File "/home/ratnadeepb/app/miniconda3/envs/python3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1602, in setup_default_layouts
    layout = layouts[index]
KeyError: 4

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Seems like it could be a bug all right, and your description likely answers @ccordoba12 's question on the closed #5479 as to how the latter occurred, as the error is identical to that.

Does this happen with all custom layouts, or only certain ones? Can you create a new, fresh layout to test?

**Comment by ratnadeepb** [comment]
Happened today a few times. Otherwise it has been okay for a long time.

**Comment by CAM-Gerlach** [comment]
Thanks for following up. So it sometimes happens with a given layout when switching, and sometimes it doesn't? Anything in common about the layout you're switching *from*, by any chance? Anything else different about the times it happens and those it doesn't?

**Comment by ratnadeepb** [comment]
Sorry. Just realized how incomplete my details were. 

So I have this custom layout that I use and have been using for a while now. Today all of a sudden I could not switch. I redid the layout and saved it again and things are fine now.

**Comment by CAM-Gerlach** [comment]
Okay, thanks for the information and glad you got it working. If you can isolate it to something reproducible with the layout that Spyder should read fine but doesn't, then that may be a bug and someone can try to fix it. Otherwise, it may be something on the user side the Spyder has no direct control over, and so at this point given you've solved your problem this can probably be closed unless/until the former happens.

**Comment by ratnadeepb** [comment]
Yes please close it. I'll keep an eye out if it ever happens again.

**Comment by CAM-Gerlach** [comment]
I can't, haha, since I'm just a regular user. You, on the other hand, can as you're the original reporter.

**Comment by ratnadeepb** [comment]
Lolz ... done
