### ISSUE TITLE
hide the 'runfile (...)' expression when running a python script from Spyder

### ISSUE THREAD

**Issue by Noomene** [spyder-ide/spyder#5859]
Is there a way to hide the 'runfile (...)' expression when running a python script from Spyder?
Because it clutters the console. Especially for programs with short outputs where I might want to compare the results of different runs, it gets very annoying to have this same message being written there every single time, between successive outputs. I have seen pictures of other IDEs which do not put this line there every time.

For example: Compiling  the code 'print(3+4)' gives 1.5 lines of said runfile expression (which  by the way is colored, so it looks like an error message) but only  one single character, 7, as actual output. This is really annoying

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows 8 64

## Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.2 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
> Is there a way to hide the 'runfile (...)' expression when running a python script from Spyder?

No, there isn't, sorry. We think it's better to show a command in the console to tell people something is being evaluated there.

If you don't want to evaluate an entire file, you can use F9 to evaluate a single line, or Ctrl+Enter or Shift+Enter to evaluate regions delimited by comments of the form `#%%`, called cells.

**Comment by Noomene** [comment]
What a pity! I guess I'll stick with PyCharms then!

**Comment by ccordoba12** [comment]
It's the same thing if you see it as part of output. I don't get it. But anyway, good luck :+1:

**Comment by jondo** [comment]
This was a duplicate of #2254, by the way.
