### ISSUE TITLE
%clear does not clear the iPython console 

### ISSUE THREAD

**Issue by VrunBert** [spyder-ide/spyder#5863]
## Description of your problem
with latest Anaconda install %clear produces  "The system cannot find the path specified"

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Windows 7 Enterprise 6.1.7601 Service pack 1, x64 bit

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
What is your current directory when this is happening? Is it a UNC drive?

**Comment by VrunBert** [comment]
yes, it is  \\drive\UserData\Name\Home\Working\code while Anaconda is on system C drive.

**Comment by ccordoba12** [comment]
I guess you error appear not just after running `%clear`, but any other command, like `1 + 1`. Is that right?

**Comment by VrunBert** [comment]
everything else runs even magic functions.  I just ran Ipython in shell and get: 
`%clear
ERROR:root:Line magic function '%clear' not found.    `
is not listed under %lsmagic in Ipython shell, but it does when run in Spyder?  is that expected?

**Comment by ccordoba12** [comment]
This is very odd indeed, but unfortunately we don't have time to debug this, sorry. It seems very particular to your case.

If you find a way to solve it, please don't doubt to send a pull request for it.
