### ISSUE TITLE
Sections are not displayed in Help when using Python 2

### ISSUE THREAD

**Issue by yellowhat** [spyder-ide/spyder#5871]
Hi all,
in last version of spyder I noticed that the documentation of a function is not rendered correctly in the ``Help`` tab.
Let's say that I have the following function:

```
def func(arg1, arg2):
    """Summary line.

    Extended description of function.

    Parameters
    ----------
    arg1 : int
        Description of arg1
    arg2 : str
        Description of arg2

    Returns
    -------
    bool
        Description of return value

    """
    return True
```
As you can see there is a documentation part with two section: ``Parameters`` and ``Returns``.
If I type ``CTRL+i`` on the function this is what I get:
![img](https://user-images.githubusercontent.com/1692490/33490703-52287a10-d6b8-11e7-8d53-2253f7d85fa7.png)

The normal text is written but not the name of the sections.

If I do the same thing on the function ``numpy.array``:
![ok](https://user-images.githubusercontent.com/1692490/33490890-d25c1480-d6b8-11e7-8e29-2343be7e1af2.png)

The documentation is rendered correctly.

The text part of ``numpy.array.__doc__`` is very similar to the example:

```
   Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
```

Thanks

**What steps will reproduce the problem?**

1. ``CTRL+i`` on a function
2. 
3. 

## Versions and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14 (Anaconda)
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows

## Dependencies
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.27.3 (OK)
jedi >=0.9.0      :  0.11.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.21.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by CAMGerlach-Baron** [comment]
Thanks for reporting. I pasted the above function its docstring into Spyder 3.2.4 as you have running the same Sphinx 1.6.3 (and Qt/PyQt verisons, on Windows 10 Pro x64), and it worked just fine. Only major difference is I'm running Python 3.6.3. Therefore, perhaps it might be something either something specific to your setup, or specific to Python 2.

![image](https://user-images.githubusercontent.com/32848199/33497625-3021cb0c-d694-11e7-9324-3f248a67f509.png)

**Comment by ccordoba12** [comment]
@CAMGerlach-Baron, could you try this on Python 2? You can easily do that by creating a conda environment for Python 2 and installing Spyder on it. Thanks!

**Comment by CAMGerlach-Baron** [comment]
@ccordoba12 Sure thing. I did so, and can confirm that the problem is indeed isolated to python2, or something directly related, as I get the same malformatted output as the original reporter when tested with the same function.

![image](https://user-images.githubusercontent.com/32848199/33505457-f5992a58-d6b0-11e7-81fc-a4595cb48198.png)

**Comment by ccordoba12** [comment]
We don't support Python 2 anymore.
