### ISSUE TITLE
Python Issue

### ISSUE THREAD

**Issue by nunomcfrancisco** [spyder-ide/spyder#5875]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 248, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 608, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
    from .pylint import Pylint as PLUGIN_CLASS
    from .widgets.pylintgui import PylintWidget
    import pylint
ModuleNotFoundError: No module named 'pylint'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)

```

**Comment by jitseniesen** [comment]
I don't know, but it looks like a problem with how `pylint` (which Spyder depends on) is installed on your system. Check the pylint entry in the table displayed when you click `Dependencies` in the `Help` menu in Spyder. Can you upgrade or re-install `pylint`?

**Comment by CAM-Gerlach** [comment]
FYI, you can upgrade `pylint` with `conda update pylint`, or remove/(re)install it with `conda remove pylint` then `conda install pylint`. Also, `conda list pylint` will get you some basic information about your current `pylint` install.

**Comment by CAM-Gerlach** [comment]
As this issue seems likely to be on the user side, this will likely get closed in a few days unless there is a followup indicating this is something other than a user-side install issue. Thanks!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
