### ISSUE TITLE
problem debugging file

### ISSUE THREAD

**Issue by rogeliotg** [spyder-ide/spyder#5881]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/rogelio/dev/anaconda/lib/python3.6/site-packages/spyder/plugins/editor.py", line 797, in <lambda>
    triggered=lambda: self.debug_command("exit"))
  File "/home/rogelio/dev/anaconda/lib/python3.6/site-packages/spyder/plugins/editor.py", line 2317, in debug_command
    self.main.ipyconsole.write_to_stdin(command)
  File "/home/rogelio/dev/anaconda/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 961, in write_to_stdin
    sw.write_to_stdin(line)
  File "/home/rogelio/dev/anaconda/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/debugging.py", line 29, in write_to_stdin
    self.kernel_client.input(line)
AttributeError: 'NoneType' object has no attribute 'input'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
What were you doing when this happened? Please describe step by step how you got this error so we can reproduce it in our side.

**Comment by ccordoba12** [comment]
Are you trying to start a debugging session in an external kernel?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
