### ISSUE TITLE
Ctrl+i is not working on Spyder 3.2.4 on Windows 10

### ISSUE THREAD

**Issue by Ronnie-Li** [spyder-ide/spyder#5884]
## Description

**What steps will reproduce the problem?**

1. Open Anaconda (or even Spyder directly)
2. Press Ctrl+i on the Python function
3. The Help window is blank.

**What is the expected output? What do you see instead?**
Expected to see the help of the function. But it shows empty window.

**Please provide any additional information below**
Windows 10 (64 bit)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by Ronnie-Li** [comment]
Sorry. It is working. But I don't see help for some functions, such as "pivot_table" and "groupby". I am abot to execute the function but there is just no help.
Know why?

**Comment by ccordoba12** [comment]
Are you pressing `Ctrl+I` from the Editor or the IPython console?

**Comment by Ronnie-Li** [comment]
I pressed the Ctrl+I from the Editor window. It is weird that I can see the help for some functions, such as concat
Additionally, I expect to have free typing on the Object at the Help windows to search the function. But it does not allow me to type any character even though the Lock icon is unlucked.
I am new to Python and Spyder. I am not sure if I missed any setting. or it is a bug (which I doubt because this standard function should work in a large population of the community).
Thanks for the help.

**Comment by CAM-Gerlach** [comment]
In general, from my limited experience, it isn't the most reliable; it will stop working if left open too long or put to sleep (fixed in 3.2.5 IIRC), and certain functions in certain packages cannot be found (makes me all the more appreciate how documentation in Rstudio just *works*, instantly and always). However, much of that is the responsibility of the packages Spyder uses for lookup and help generation (`rope`, `jedi`, `sphinx`), and some are intrinsic to how the functions/packages being "Ctrl-I'ed" are written/structured.

As for `concat`, do you mean `pandas.concat`? That works for me running identical versions of everything relevant to you, in a fresh spyder session, so long as I've actually `import`ed `pandas` of course.

However, with regard to

> Additionally, I expect to have free typing on the Object at the Help windows to search the function. But it does not allow me to type any character even though the Lock icon is unlucked [sic].

This is something I've noticed as well since I started using Spyder with 3.2.1, and has been an annoyance for quite some time. If I need to search for a function, I have to switch the "source" to "console" and type it there. I have no idea what the lock is supposed to do, as the console is always "unlocked" and the editor is always "locked," even though the button can be toggled and changes appearance. Bug @ccordoba12 ?

**Comment by bcolsen** [comment]
@Ronnie-Li Pandas and Matplotlib are starting to work better with jedi(the code completion library) but there is still problems with function return types and for what object is returned.  Jedi has to try to figure this out without running the code.  I might look into this for pandas if I have the time.

**Comment by ccordoba12** [comment]
As @CAM-Gerlach and @bcolsen pointed out, getting documentation from objects in the Editor doesn't work all the time.

> Additionally, I expect to have free typing on the Object at the Help windows to search the function. 

That's not the purpose of that field. It simply shows the documentation of a given object. For instance, you can write there `numpy.sin` and it'll show the docs associated to that object.

We understand this can be confusing, but that's what we offer for now. Perhaps in the future we can turn that field in a proper search box.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 . However, one thing:

> That's not the purpose of that field. It simply shows the documentation of a given object. 

I understood that (and in fact the "search" box in the online help docs does sort of do this); however, that wasn't exactly what I or I believe @Ronnie-Li was referring to, but rather the fact that currently one *can't*

> write there numpy.sin and it'll show the docs associated to that object.

at least when the "Editor" is selected as the "Source", as "locked" or "unlocked" nothing can be manually entered in the field, which appears to be a bug. My comment above describes this in more detail, and at least 2-3 other reporters have also mentioned this behavior in related issues; I can open a separate one if that would be helpful. Thanks!

**Comment by ccordoba12** [comment]
> I can open a separate one if that would be helpful.

Sure. I misunderstood the problem, so it'd be nice to have a new issue about it.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Thanks. Done; opened #5891

**Comment by Vishwanathhiremath** [comment]
The same issue is happening to me and tried the list() on the editor and console as well, but didn't worked!! 
When I pressed Ctrl+I and held for 5 seconds, then the documentation of the class or libraries on which the cursor was positioned came through.. 

Hope this helps!!

**Comment by CAM-Gerlach** [comment]
@Vishwanathhiremath It is very unclear what problem you are reporting. This one was closed several years ago, and there are massive changes to how completion, introspection and help works in Spyder 4 that resolve a lot of these issues. Spyder 4 should be released soon (you can monitor the progress toward release with the milestones on this repo) so I'd just advise being patient (or trying the Spyder 4 beta, if you're brave), and then if the problem still persists in Spyder 4 and hasn't already been reported, filling out a full new issue then. Thanks.

**Comment by t-anya** [comment]
> 
> 
> The same issue is happening to me and tried the list() on the editor and console as well, but didn't worked!!
> When I pressed Ctrl+I and held for 5 seconds, then the documentation of the class or libraries on which the cursor was positioned came through..
> 
> Hope this helps!!

This helps!
Thanks

**Comment by Nanaya-Shiki** [comment]
> The same issue is happening to me and tried the list() on the editor and console as well, but didn't worked!!
> When I pressed Ctrl+I and held for 5 seconds, then the documentation of the class or libraries on which the cursor was positioned came through..
> 
> Hope this helps!!

I'm using version 4.0.1 and I'm having the same problem, but with a 5 second tip it works! Ty.
