### ISSUE TITLE
Cannot open Settings

### ISSUE THREAD

**Issue by homocomputeris** [spyder-ide/spyder#5893]
## Description
Spyder suggested sending this message to GitHub, that's what I'm doing.

**What steps will reproduce the problem?**

1. Try to open Settings menu

**What is the expected output? What do you see instead?**
Settings menu expected but get the error message below:

**Please provide any additional information below**

  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 2609, in edit_preferences
    widget.initialize()
  File "/usr/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 77, in initialize
    self.load_from_conf()
  File "/usr/lib/python3.6/site-packages/spyder/plugins/configdialog.py", line 381, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This was fixed already and it'll be part of our 3.2.5 version.

In the meantime you can run in a terminal

    spyder --reset

to fix it.
