### ISSUE TITLE
spyder3.0.0 Kernel died, restarting

### ISSUE THREAD

**Issue by nuannuan1991** [spyder-ide/spyder#5895]
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder (Windows 7)
2. run my code
3. 

**What is the expected output? What do you see instead?**
Kernel died, restarting

**Please provide any additional information below**
Not only in spyder, but also in  IPython and Jupyter QTConsole，Jupyter Notebook。
All of them appear Kernel died, restarting.
My code is very simple。The code is as follows：

## Versions and main components

* Spyder Version:3.0.0
* Python Version: Anaconda2 (64-bit),python2.7
* Operating system: windows 7
import caffe
import matplotlib.pyplot as plt     
import numpy as np

def vis_square(data):
    data = (data - data.min()) / (data.max() - data.min())
    n = int(np.ceil(np.sqrt(data.shape[0])))
    padding = (((0, n ** 2 - data.shape[0]),
               (0, 1), (0, 1))                 
               + ((0, 0),) * (data.ndim - 3))  
    data = np.pad(data, padding, mode='constant', constant_values=1)  # pad with ones (white)
    data = data.reshape((n, n) + data.shape[1:]).transpose((0, 2, 1, 3) + tuple(range(4, data.ndim + 1)))
    data = data.reshape((n * data.shape[1], n * data.shape[3]) + data.shape[4:])
    if data.shape[2] == 1:
        data = data[:,:,0]
    plt.imshow(data); plt.axis('off')

if __name__ == '__main__':
    caffe.set_mode_cpu()
    solver = caffe.SGDSolver('E:\BaiduYunDownload\caffe\caffe-windows\examples\mnist\lenet_solver.prototxt')
    solver.step(1)
    input_data = solver.net.blobs['data'].data  
    plt.figure(0)
    vis_square(input_data.transpose(0, 2, 3, 1))  
    filters = solver.net.params['conv1'][0].data
    plt.figure(1)
    vis_square(filters.transpose(0, 2, 3, 1))

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by ccordoba12** [comment]
> Not only in spyder, but also in IPython and Jupyter QTConsole，Jupyter Notebook。
All of them appear Kernel died, restarting

Then this is not a Spyder problem. I'm very sorry to say it but we don't have the time to help you debug this.
