### ISSUE TITLE
Tensorflow variable values are not shown in Spyder console

### ISSUE THREAD

**Issue by addarnr** [spyder-ide/spyder#5897]
## Description of your problem
Hello, I am new to python and spyder.  I have a tensorflow code that runs fine. However, I have issues with debugging since it doesn't show any variable values associated with tensorflow in the console. Please see an example 'predict' below after running the code in debug mode. 'predict is the output of a tensorflow function.
ipdb> i
9
ipdb> predict
<tf.Tensor 'Equal:0' shape=(?,) dtype=bool>

**What steps will reproduce the problem?**
1. import numpy as np
import tensorflow as tf
import time
import data_helpers
2. define any tensorflow variables and debug the code by stepping through
3. after the variable line is executed type the variable name in the console and hit enter

**What is the expected output? What do you see instead?**
Expected output is the actual value of the variable.  However it shows tensorflow strings as I have shown above. (<tf.Tensor 'Equal:0' shape=(?,) dtype=bool>)

**Please provide any additional information below**

## Versions and main components
* Spyder Version: 3.2.4
* Python Version: 3.5
* Qt Version: 5.6.2
* PyQt Version:5 5.6
* Operating system: Windows 10 64bit

## Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

Thank you!

**Comment by ccordoba12** [comment]
What's get printed when you try to inspect `predict` out of debugging?

**Comment by OpenMindInternational** [comment]
Seems you are really new to tensorflow, bro.
The fact is, there's no problem with the program spyder,
and the value shown to you is just right.
For your code, you only define the compute method, i.e., _Graph_ in tensorflow,
and have not call the run method of tensorflow which let the compute job goes, i.e., _Session_.
What you have seen in the debugger is the reference of variable kept by _Tensor_,
denoting the compute method of the variable.

__YOU NEED CALL LIKE THIS__
* * *
    import tensorflow as tf
    a = tf.constant([1.0], name="a")
    b = tf.constant([2.0], name="b")
    result = a + b
    with tf.Session() as sess:
        sess.run(result)

Learn more about tensorflow.

**Comment by ccordoba12** [comment]
Thanks for the explanation @OpenMindInternational! Closing this one then.

**Comment by addarnr** [comment]
@OpenMindInternational, Yes, I am new to Tensorflow.  However the example 'predict' that I sent was just a line from a code that includes defining the graph and then running it in a session.  As I mentioned before, the code was running fine.  
Your points are well taken.  Issuing a print(result.eval()) during a session got me the value of the variable.

Thank you!
