### ISSUE TITLE
Error trying spyder-line-profiler

### ISSUE THREAD

**Issue by Neotric** [spyder-ide/spyder#5905]
## Description

**What steps will reproduce the problem?**

1. install sw with sudo -H pip install spyder-line-profiler
2. profile by line program in spyder:

```python
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""
import math

@profile
def my_cube(a):
    return a*a*a

a = 0
for i in range(1000):
    a += math.sin(my_cube(i))
```

**What is the expected output? What do you see instead?**

No reaktion, but error.

**Please provide any additional information below**

  File "/usr/local/lib/python3.5/dist-packages/spyder_line_profiler/widgets/lineprofiler.py", line 242, in start
    self.process.setWorkingDirectory(wdir)
TypeError: QProcess.setWorkingDirectory(str): argument 1 has unexpected type 'bool'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.5.1, PyQt5 5.5.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  3.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment]
I'm moving this to its appropriate repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-line-profiler #25](https://github.com/spyder-ide/spyder-line-profiler/issues/25) via [**ZenHub**](https://www.zenhub.com/)
