### ISSUE TITLE
Introspection dies after some time

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#5906]
## Description

**What steps will reproduce the problem?**

1. Use Spyder for a while
2. Put the computer to sleep?
3. Try to go to definition with cmd + g / help with cmd + i

**What is the expected output? What do you see instead?**
I expect to Go to definition / get Help.
Instead nothing happens.

**Please provide any additional information below**
That reminds me of https://github.com/spyder-ide/spyder/issues/3223
Probably the introspection dies but spyder doen't freeze because of zmq.NOBLOCK

## Version and main components

* Spyder Version: 3.2.5.dev0 2f3172895
* Python Version: 3.6.2
* Qt Versions: 5.9.1, PyQt5 5.9 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is known issue. Hopefully it'll be solved once we merge PR #4751.
