### ISSUE TITLE
cannot open jupyter notebook

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#5921]
## Description

**What steps will reproduce the problem?**

1. cannot open new or existing ipnb files
404 : Not Found
You are requesting a page that does not exist!

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 372, in close_client
    client.shutdown_kernel()
  File "C:\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 236, in shutdown_kernel
    kernel_id = self.get_kernel_id()
  File "C:\Anaconda3\lib\site-packages\spyder_notebook\widgets\client.py", line 222, in get_kernel_id
    sessions = json.loads(sessions_req)
  File "C:\Anaconda3\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.2, PyQt5 5.9.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.

**Comment by Khalilsqu** [comment]
sorry, it is working wight now, thanks alot, appreciate your help and support and very happy this this ide

**Comment by CAM-Gerlach** [comment]
Thanks for reporting, and good to hear. If the problem was resolved, then feel free to close this issue.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #139](https://github.com/spyder-ide/spyder-notebook/issues/139) via [**ZenHub**](https://www.zenhub.com/)
