### ISSUE TITLE
Closing via command line generates error

### ISSUE THREAD

**Issue by cortical-iv** [spyder-ide/spyder#5924]
## Description
**What steps will reproduce the problem?**
1. Activate spyder from terminal (using 'spyder').
2. Hit ctrl^c in terminal.

**What is the expected output? What do you see instead?**
I expect spyder to close, but it doesn't and I get stack trace below. Frankly I think this is probably good behavior, as if someone accidentally closes the wrong terminal window we don't want Spyder to close. But it might be nice to have a UI giving that option, or a friendlier error message with some warning or explanation or something.

This is low priority obviously, but I just thought I'd report it.

**Please provide any additional information below**
  File "/home/cortical_iv/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 184, in _heartbeat
    def _heartbeat(self):
KeyboardInterrupt

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Fixed in 3.2.4. Please update.
