### ISSUE TITLE
"Spyder has encountered an error" when editing python script

### ISSUE THREAD

**Issue by djconly85** [spyder-ide/spyder#5929]
## Description

**What steps will reproduce the problem?**

1. Open Spyder
2. Start typing code into the editor window

**What is the expected output? What do you see instead?**
Expected: Nothing, just be able to code/edit as usual

What I see instead: Error window saying "Spyder has encountered a problem" appears with the details shown in the "additional information" section below.

**Please provide any additional information below**
System info:
---------------------------------------
-Windows 7
-Using as part of Anaconda package
-Spyder 3.2.4 
-Python 3.6.3

Stuff I've tried
---------------------------------------
I googled my issue and saw that a similar problem was submitted last month at this link:
[https://github.com/spyder-ide/spyder/issues/5838](url)

I tried resetting Spyder by entering spyder --reset in the command line, but it did not help.

Error description:
------------------------------------

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 234, in show_object_info
    info = self._get_code_info('info', position, auto=auto)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\manager.py", line 216, in _get_code_info
    **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 75, in __init__
    self._get_info()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 87, in _get_info
    lexer = find_lexer_for_filename(self.filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\utils\introspection\utils.py", line 180, in find_lexer_for_filename
    lexer = get_lexer_for_filename(filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 203, in get_lexer_for_filename
    res = find_lexer_class_for_filename(_fn, code)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\lexers\__init__.py", line 168, in find_lexer_class_for_filename
    for cls in find_plugin_lexers():
  File "C:\ProgramData\Anaconda3\lib\site-packages\pygments\plugin.py", line 53, in find_plugin_lexers
    yield entrypoint.load()

**Comment by mikofski** [comment]
* me too, same traceback, also anaconda3.
* curious, what versions do you have? I just updated several anaconda packages through the "navigator" instead of conda:

|pkg|version|
|----|--------|
|IPython >=4.0    |  6.2.1 (OK)|
|cython >=0.21    |  0.27.3 (OK)|
|jedi >=0.9.0     |  0.11.0 (OK)|
|nbconvert >=4.0  |  5.3.1 (OK)|
|numpy >=1.7      |  1.13.3 (OK)|
|pandas >=0.13.1  |  0.21.0 (OK)|
|pycodestyle >=2.3|  2.3.1 (OK)|
|pyflakes >=0.6.0 |  1.6.0 (OK)|
|pygments >=2.0   |  2.2.0 (OK)|
|pylint >=0.25    |  1.7.4 (OK)|
|qtconsole >=4.2.0|  4.3.1 (OK)|
|rope >=0.9.4     |  0.10.7 (OK)|
|sphinx >=0.6.6   |  1.6.3 (OK)|
|sympy >=0.7.3    |  1.1.1 (OK)|

* also it happens to me using numpy, which often causes code analysis problems, altho never in spyder before, does it happen for you with any code, or is it just numpy?

**Comment by mikofski** [comment]
I downgraded anaconda from the lastest custom (custom-py36h363777c_0) to the lastest stable (5.0.1-py36h8316230_2), and jedi was also downgraded from 0.11 --> 0.10.2, and so far no more errors

**Comment by mikofski** [comment]
what is #5838?

**Comment by Dan-Patterson** [comment]
I also received similar errors referring to lexors and introspection as I was typing a line in.  Dismissing the error several times but no crashes.  only common that I can see off hand is  .... jedi 0.11

**Comment by ccordoba12** [comment]
This error is produced because you have `parso 0.1.1` installed. Please downgrade to `parso 0.1.0` to fix this problem.

You can do that with

    conda install parso=0.1.0

or

    pip install parso==0.1.0

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. The error traceback that was posted is apparently incomplete. However, it is very likely a duplicate of e.g. #5673 , an error that's been reported at least a half dozen times just today. As the full error message states, Jedi is only compatible with parso 0.1.0, not, 0.1.1. Therefore, please downgrade to 0.1.0 to fix this, and this issue can be closed.

**Comment by djconly85** [comment]
Thank you Carlos. I downgraded parso and that fixed the issue.

Darren Conly | Analyst I
Sacramento Area Council of Governments
916-319-5192
dconly@sacog.org<mailto:dconly@sacog.org>

**Comment by ccordoba12** [comment]
Quick note: this can also be fixed by updating Jedi with

     conda update jedi
