### ISSUE TITLE
Tuples can be "edited" in Variable Explorer but changes are discarded

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#5953]
## Description

In the Variable Explorer, if one opens a tuple and double clicks on one of the elements to edit, the field becomes editable and the user can enter, modify or delete text. However, upon hitting return/okay, the changes are (of course, as they should be) discarded. It would seem for consistency with tuples' immutability and to minimize new user confusion about their changes not being saved, that it would be best to make the field selectable (e.g. can select text like a text box as you can currently) but not editable. I presume there's a way to do that by selecting a different type or parameter for the Qt text field object?

**What steps will reproduce the problem?**

1. Create any tuple, e.g. 
```
tup = ("foo", "bar", 42)
```
2. Open in variable explorer and double click an element value
3. Edit field contents then click off/enter

**What is the expected output? What do you see instead?**
Expected: When double clicked, text becomes selectable as if it were a text field, but cannot be changed/edited. 
Actual: Field can be edited like any other text box, but changes of course discarded when clicked off of/"accepted"

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
@CAM-Gerlach, do you want to take a look at this one? It should be an easy fix.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 _Giggles nervously_ Sure, I can give it a look sometime over the next few days, if you think its easy enough (I'm visiting my family at the moment so it might not be right away). Should I base it against 3.x or master? Not sure if it would count as an enhancement or bug fix.

**Comment by ccordoba12** [comment]
> Should I base it against 3.x or master?

`3.x`. You can tell what branch you need to use by looking at the *Milestone* tag on the right. If it starts with `3.2` is for `3.x` , else it's for `master}

**Comment by CAM-Gerlach** [comment]
Well I'm a silly goose, haha—didn't notice a version tag had been added to this one. Thanks.

**Comment by Prikers** [comment]
@CAM-Gerlach you will probably want to have a look at the [`collectioneditor`](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/variableexplorer/collectionseditor.py) file and more specifically to the [`BaseTableView`](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/variableexplorer/collectionseditor.py#L626) and [`CollectionsEditorTableView`](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/variableexplorer/collectionseditor.py#L1139) classes. Do not hesitate to ask if you need guidance.

**Comment by CAM-Gerlach** [comment]
Thanks! Will do as soon as I get a break from family time.

*C.A.M. Gerlach*
