### ISSUE TITLE
Spyder only opens via cmd prompt and not via shortcut link

### ISSUE THREAD

**Issue by mayurpande** [spyder-ide/spyder#5957]
In windows 10, spyder only opens via cmd prompt by typing spyder3, but I have created a shortcut link on desktop. But it doesn't open the program.

**Comment by CAM-Gerlach** [comment]
You need to call `pythonw.exe` with the right argument(s), e.g.; target: `C:\Anaconda3\pythonw.exe C:\Anaconda3\cwp.py C:\Anaconda3 "C:/Anaconda3/pythonw.exe" "C:/Anaconda3/Scripts/spyder-script.py" and start in `"C:\Users\YOURUSERNAME\Documents\Python Scripts"` and this isn't really a Spyder issue. If in doubt, just install Anaconda as that creates a Spyder shortcut in the start menu that works. This can be closed now, thanks.

**Comment by ccordoba12** [comment]
Sorry, we don't support custom installations (i.e. not based on Anaconda), so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
