### ISSUE TITLE
someone please help me out to to solve this error

### ISSUE THREAD

**Issue by Buvaneshbharathwaj** [spyder-ide/spyder#5960]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\BUVI 04\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2609, in edit_preferences
    widget.initialize()
  File "C:\Users\BUVI 04\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 77, in initialize
    self.load_from_conf()
  File "C:\Users\BUVI 04\Anaconda3\lib\site-packages\spyder\plugins\configdialog.py", line 381, in load_from_conf
    color, bold, italic = self.get_option(option, default)
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25

**Comment by ccordoba12** [comment]
Please run in a terminal (cmd.exe)

    spyder --reset

to fix this problem.

**Comment by Buvaneshbharathwaj** [comment]
thank you bro.....i did but in the cmd prompt  i am receving the following message
"'Spyder' is not recognized as an internal or external command,
operable program or batch file." in it

**Comment by ccordoba12** [comment]
Please introduce the command exactly as I posted, i.e. not in capital letters.

**Comment by Buvaneshbharathwaj** [comment]
"C:\Users\BUVI 04\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)>spyder --reset
'spyder' is not recognized as an internal or external command,
operable program or batch file."
same error bro

**Comment by Buvaneshbharathwaj** [comment]
Wil it get updated automatically or any other procedure uh??

On 13-Dec-2017 12:53 AM, "Carlos Cordoba" <notifications@github.com> wrote:

Then please wait until we release Spyder *3.2.5* in a couple of days, which
will fix this error.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/spyder-ide/spyder/issues/5960#issuecomment-351164047>,
or mute the thread

**Comment by CAM-Gerlach** [comment]
Assuming your settings are the defaults, Spyder should notify you that an update is available whenever it is launched. You can also check manually with Help > Check for Updates . Then, you can update with `conda update spyder` from the anaconda prompt.

**Comment by Buvaneshbharathwaj** [comment]
Thank you ✌️

**Comment by CAM-Gerlach** [comment]
Sure. Also, the `spyder --reset` command _should_ work if launched from the Anaconda Prompt and your installation is correct...

**Comment by Buvaneshbharathwaj** [comment]
Yea...  But it's not working... I launched spyder from anaconda navigator
only
