### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by homeahmed2012** [spyder-ide/spyder#5966]
## Description

**What steps will reproduce the problem?**

1. trying to create a new notebook

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/ammma/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 314, in create_new_client
    server_info = nbopen(filename)
  File "/home/ammma/anaconda3/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 75, in nbopen
    proc = subprocess.Popen(command, creationflags=creation_flag)
  File "/home/ammma/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/ammma/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter': 'jupyter'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry, the development of `spyder-notebook` is stalled now because we don't have funding to support it.
