### ISSUE TITLE
switch windows layout ERROR

### ISSUE THREAD

**Issue by lianzhaowen** [spyder-ide/spyder#5967]
## Description

**What steps will reproduce the problem?**

1. view - windows layouts - any layout
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "d:\software\python\python36\lib\site-packages\spyder\app\mainwindow.py", line 1769, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "d:\software\python\python36\lib\site-packages\spyder\app\mainwindow.py", line 1889, in quick_layout_switch
    self.setup_default_layouts(index, settings)
  File "d:\software\python\python36\lib\site-packages\spyder\app\mainwindow.py", line 1614, in setup_default_layouts
    widget.toggle_view(True)
  File "d:\software\python\python36\lib\site-packages\spyder\plugins\__init__.py", line 524, in toggle_view
    self.dockwidget.show()
AttributeError: 'DummyDock' object has no attribute 'show'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1

**Comment by ccordoba12** [comment]
We don't have an object called `DummyDock` in our entire codebase. Do you other, third-party Spyder plugins installed?

**Comment by lianzhaowen** [comment]
only spyder.autopep8

when i uninstall it, that's ok!

**Comment by ccordoba12** [comment]
Ok, I'm moving this issue to its repo then. Unfortunately, we don't have funding right now, so we don't plan to solve it for the moment.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-autopep8 #6](https://github.com/spyder-ide/spyder-autopep8/issues/6) via [**ZenHub**](https://www.zenhub.com/)
