### ISSUE TITLE
IndexError in jedi_plugin.py::get_info()

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#5971]
## Description

When running the Spyder `master` with `SPYDER_DEBUG=1`, the console shows an exception in `jedi_plugin.py`.

**What steps will reproduce the problem?**

1.  Type the following program fragment in the editor
```
import sys
sys.sleep(
```
2. The exception below appears on the console after typing the parenthesis.

**What is the expected output? What do you see instead?**

Output on console:
```
info request from fallback finished: "None" in 0.3 sec
info request
Response error:Traceback (most recent call last):
  File "plugin_server.py", line 95, in run
    response['result'] = func(*args, **kwargs)
  File ".../spyder/utils/introspection/jedi_plugin.py", line 86, in get_info
    call_def = call_def[0]
IndexError: list index out of range
```
**Please provide any additional information below**

The `sys` module does not contain a `sleep` function (it is in `time` instead). There do no seem to be any adverse effects, so probably not high priority.

## Version and main components

* Spyder Version: 4.0.0.dev0 903ee4ace
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Closing because this no longer applies.
