### ISSUE TITLE
Images are not rendered by the Help pane on Ubuntu

### ISSUE THREAD

**Issue by fwitte** [spyder-ide/spyder#5972]
Hi,
I am programming an own python package and have added some images to my documentation. The images are rendered in the html files but are not rendered in the spyder Help pane. I already saw, that this issue existed a year ago for windows systems (see https://github.com/spyder-ide/spyder/issues/2465).

My code looks like this:
```
class test(object):
    """
    more stuff here

    **inlets and outlets**
        - in1
        - out1

    .. image:: _images/turbine.svg
       :scale: 100 %
       :alt: alternative text
       :align: center
    """
    some code
```
In spyder it looks like this:

![bildschirmfoto vom 2017-12-13 09-21-06](https://user-images.githubusercontent.com/20252362/33929414-b6ad03b8-dfe9-11e7-80cd-819ba650322a.png)

while in the docs it looks like this (as expected):

![bildschirmfoto vom 2017-12-13 09-39-09](https://user-images.githubusercontent.com/20252362/33929415-b6ceb544-dfe9-11e7-896d-4530ae47ec10.png)

Thank you and have a nice day!

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.5.2
* Qt Version: 4.8.7
* PyQt Version: 4.11.4
* Operating system: Ubuntu 16.04 LTS 64 bit

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I assume its just not supported at the moment? Reproduced on Windows as the following:

![image](https://user-images.githubusercontent.com/17051931/33947399-4e0d2410-dff2-11e7-83dc-dd256cd125b9.png)

**Comment by ccordoba12** [comment]
I don't think things can work if you use relative paths for your images. What happens if you use absolute paths?

**Comment by CAM-Gerlach** [comment]
I tested it on Windows with PNGs, JPEGs and PDFs using absolute paths, and like before I got an empty "?" frame, appropriately sized for the image I'd set the path to (unlike when I set an invalid path, where I'd just get a very small ? frame), but no image content actually rendered. Not sure if helpful, but just wanted to confirm.
