### ISSUE TITLE
Shift+del should delete line only when empty selection, otherwise clipboard cut

### ISSUE THREAD

**Issue by prof7bit** [spyder-ide/spyder#5973]
## Description of your problem

**What steps will reproduce the problem?**

1.  select some text
2.  press shift-del

**What is the expected output? What do you see instead?**
selected text should be removed and inserted to clipboard so that shift-ins brings it back. (cut & paste)

instead it just deletes all lines that were part of the selection and one line more without putting any of it to the clipboard.

proposed solution:
* when the selection is empty then delete the line and put it to the clipboard
* when the selection is not empty then fall back to the standards conforming behavior of cut exactly the selected text to the clipboard.

Generally it should be expected that after the sequence shift-del, shift-ins the text should be in the same state as it was before, as it is in **any** other code editor out there. 

Many people wo use both hands on the keyboard use these keys as a replacement for the alternative Crtl-X, Ctrl-V because when selecting text with the keyboard (shift and cursor keys) instead of using the mouse then the left hand is already sitting on the shift key while the right index finger is conveniently near del and ins.

When not using it for cutting selected text and instead just deleting the current line without a selection then it should be put to the clipboard anyways, as this is also standard practice in many code editors that have line delete function, there is a corresponding paste key that brings back the line. In spyder it is just lost, not useful when rearranging lines.

Please do not close this bug too quickly, if nobody wants to work on this then I might give it a try myself, this odd behavior of spyder has caused me so much annoyance already I really want to find a solution to make the standard keys behave more standards conforming.

**Comment by ccordoba12** [comment]
This is a good proposal, thanks. Please send us a pull request if you want to see this implemented in a future release because we don't have time to do it.

**Comment by ccordoba12** [comment]
@csabella, maybe you'd like to work on this one?
