### ISSUE TITLE
Remove 'DMG Installers' option from documentation

### ISSUE THREAD

**Issue by davidrpmorris** [spyder-ide/spyder#5978]
Please remove the 'Use our DMG installers' option on the [installation page of the documentation](https://pythonhosted.org/spyder/installation.html) for macOS, as there hasn't been a DMG option since Nov 2016.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I'm still a newbie, but I created a simple PR, #5979 , to fix this as stated above. Please take a look at it to make sure it accurately represents the current state of affairs.

**Comment by ccordoba12** [comment]
Unfortunately I don't know how to update the online docs now that the old PyPI doesn't allow it.

**Comment by ccordoba12** [comment]
After a bit of searching, it seems we need to move our docs to readthedocs. I'll open an issue for that.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 So my glorious PR doesn't actually do anything, haha?

**Comment by ccordoba12** [comment]
It does, don't worry about it ;-) But for your changes to appear online, we need to move them to readthedocs.

**Comment by CAM-Gerlach** [comment]
Gotcha, thanks!

*C.A.M. Gerlach*

**Comment by ccordoba12** [comment]
Closed by #5979.
