### ISSUE TITLE
能否增加主题格式，如护眼模式等，白色主题太单调，且很刺眼，自己配置太过麻烦

### ISSUE THREAD

**Issue by lxylky0814** [spyder-ide/spyder#5980]
## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by jitseniesen** [comment]
I think they are complaining that Spyder's default scheme is too bright.

Please see #2350 for a discussion about adding a dark scheme to Spyder.
不好意思，我的中文很不好。你看 #2350 讨论深色主题。
