### ISSUE TITLE
Inconsistent results creating dataframe in Spyder/qtconsole vs. bare iPython

### ISSUE THREAD

**Issue by nadgamingdna** [spyder-ide/spyder#5984]
## Description

**What steps will reproduce the problem?**

1.

```python
from nsepy import get_history
from datetime import date
import pandas as pd
sbin = get_history(symbol="SBIN", start=date(2017,9,8), end=date(2017,12,8))
itc = get_history(symbol="ITC", start=date(2017,9,8), end=date(2017,12,8))
airtel = get_history(symbol="BHARATIARTL", start=date(2017,9,8), end=date(2017,12,8))
portfolio = pd.DataFrame()
for xx in sbin.columns:
    print xx
    portfolio[xx] = sbin[xx] + itc[xx] + airtel[xx]
print portfolio
```

2. 
3. 

**What is the expected output? What do you see instead?**
dataframe with sum of columns of initial dataframe. dataframe filled with null values. 

**Please provide any additional information below**
code works perfectly in ipython seperatly

## Version and main components

* Spyder Version: 2.3.8 
* Python Version: 2.7.14
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Optional dependencies
```
pyflakes >=0.5.0   :  0.9.2 (OK)
pep8 >=0.6         :  1.6.2 (OK)
pygments >=1.6     :  2.0.2 (OK)
IPython >=1.0      :  5.4.1 (OK)
zmq >=2.1.11       :  14.7.0 (OK)
qtconsole >=4.0    :  4.3.1 (OK)
pandas >=0.13.1    :  0.17.0 (OK)
sphinx >=0.6.6     :  1.3.1 (OK)
rope >=0.9.2       :  0.9.4 (OK)
jedi >=0.8.1;<0.9.0:  0.8.1 (OK)
matplotlib >=1.0   :  1.4.3 (OK)
sympy >=0.7.3      :  0.7.6 (OK)
pylint >=0.25      :  None (NOK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Did you try it in bare `qtconsole`?

**Comment by CAM-Gerlach** [comment]
Also, did you try it in the latest version of Spyder, 3.2.4 as of this writing? And update your dependencies while you're at it?

**Comment by ccordoba12** [comment]
Yep, please update to the latest Spyder because our 2.3 version is not supported anymore.

**Comment by CAM-Gerlach** [comment]
Closed due to the above and lack of response.
