### ISSUE TITLE
Anaconda not launching Spyder, jupytrlab, notebook on Win10

### ISSUE THREAD

**Issue by renieak** [spyder-ide/spyder#5985]
## Description of your problem
I installed Anaconda 1.6.9 on Win10.
I tried launching Spyder, but it would just show me the loading bar at the bottom for sometime, but Spyder won't launch.
(same for the other two as well)

But I am able to launch Spyder directly by clicking on the spyder.exe file in the Program Data folder.

**What steps will reproduce the problem?**

1. Install Anaconda1.6.9 on WIN10 v1709 (OS build 16299.125)
2. Launch Anaconda1.6.9
3. Launch Spyder from within

**What is the expected output? What do you see instead?**
Spyder should launch

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: WIN10 v1709 (OS build 16299.125)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
## Description of your problem
I installed Anaconda 1.6.9 on Win10.
I tried launching Spyder, but it would just show me the loading bar at the bottom for sometime, but Spyder won't launch.

But I am able to launch Spyder directly by clicking on the spyder.exe file in the Program Data folder.

**What steps will reproduce the problem?**

1. Install Anaconda1.6.9 on WIN10 v1709 (OS build 16299.125)
2. Launch Anaconda1.6.9
3. Launch Spyder from within

**What is the expected output? What do you see instead?**
Spyder should launch

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: WIN10 v1709 (OS build 16299.125)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
I saw you posted this error also in the Anaconda issues repo, which was the right thing to do. Please wait until you get an answer there.
