### ISSUE TITLE
IPython Matplotlib QT Backend RuntimeError

### ISSUE THREAD

**Issue by JesterEE** [spyder-ide/spyder#5989]
When starting Spyder with the QT5 graphics backend the following error is generated:
```python
Traceback (most recent call last):

  File "<ipython-input-1-64557277dbff>", line 1, in <module>
    get_ipython().run_line_magic('matplotlib', 'qt5')

  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)

  File "<decorator-gen-108>", line 2, in matplotlib

  File "C:\Anaconda3\lib\site-packages\IPython\core\magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "C:\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)

  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2983, in enable_matplotlib
    self.enable_gui(gui)

  File "C:\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 482, in enable_gui
    real_enable_gui(gui)

  File "C:\Anaconda3\lib\site-packages\ipykernel\eventloops.py", line 337, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")

RuntimeError: Cannot activate multiple GUI eventloops
```

**What steps will reproduce the problem?**

1. Start with a clean spyder environment (delete the old .spyder* directory)
2. Start Spyder
3. Change the matplotlib backend
  a. Preferences -> IPython console -> Graphics -> Graphics backend -> QT5/QT4? (No PyQt4 installed, can't check)
4. Restart the IPython kernel

**What is the expected output? What do you see instead?**
No output is expected ... plots should display in external windows.

**Please provide any additional information below**
This is actually not a Spyder error as it is coming from IPython, *but* I tried running a similar set of commands in an IPython notebook (with Jupyter) and didn't receive this error:

```python
import matplotlib.pyplot

%matplotlib qt5
matplotlib.pyplot.plot()

%matplotlib inline
matplotlib.pyplot.plot()

%matplotlib qt5
matplotlib.pyplot.plot()
```

Something about the way Spyder is attaching to the eventloop with IPython seems to not be working correctly.

**Workaround**
I run a setup script instead of leaving some of the setup to Spyder because the options aren't available in the GUI.  I modified my script to address this by starting with an inline backend, and immediately switching to the QT5 backend.  It works, but I'd rather leave this piece to Spyder because if I switch settings (which I do from time to time) I don't want to have to remember that I hacked it into my environment setup.

```python
from IPython import get_ipython
ipython = get_ipython()
try:
    # Some issue irrelevant commands
    ipython.magic("matplotlib inline"); ipython.magic("matplotlib qt")  # Needed to add this because pylab was giving a RuntimeError when attaching QT to the eventloop
    ipython.magic("pylab --no-import-all")
except AttributeError:  # Not in an IPython environment
    pass
del ipython
```

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for such a detailed report! Can you try this with a new instance of plain `qtconsole`, and see if the problem reoccurs? if so, you'll want to submit your bug there since the problem would presumably be in that codebase, not here.

**Comment by ccordoba12** [comment]
> I run a setup script instead of leaving some of the setup to Spyder because the options aren't available in the GUI

If you do this, you can simply turn off the option called `Activate support` in

    Preferences > IPython console > Graphics

That way, you'll be completely in charge of setting your preferred Matplotlib backend, and Spyder won't interfere with that.

**Comment by JesterEE** [comment]
@CAM-Gerlach You're right ... it's a QtConsole issue.  If you run 
```python
get_ipython().run_line_magic('pylab', 'qt')
```
the same error emerges. 

I will report it there.  Closing.
