### ISSUE TITLE
Annoying Detached Window Behavior

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#600]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-03-28T14:33:16Z_

What steps will reproduce the problem?

1. Detach Console/Pylint/Profiler window and place on second monitor.
2. Attempt to bring any non Spyder window to the top on the second monitor.
3. It's impossible to see anything on the second monitor without minimizing Spyder on the primary monitor. What is the expected output? What do you see instead? Why do the detached windows seem to have "Always on top" behavior on the second monitor?  If this is desired behavior I want to see a setting added to disable it. What version of the product are you using? On what operating system? spyder devel from mercurial (checked out approx. 1 week ago), windows XP SP3, python 2.6.1.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=600_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-03-28T13:51:43Z_

This is not an intended behavior. I'll have to check if this can be changed - my guess is that it should be doable.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:29:47Z_

**Labels:** Cat-SpyderGUI

**Comment by goanpeca** [comment]
I think this is no longer true,

Closing, @ccordoba12 ?

**Comment by ccordoba12** [comment]
Sure. I don't have a way to test this :-)
