### ISSUE TITLE
Error when trying to change python interpreter

### ISSUE THREAD

**Issue by drwawa** [spyder-ide/spyder#6013]
## Description
When I try to change the python interpreter, I receive an error message, then Spyder is unable to connect to the kernel.
**What steps will reproduce the problem?**

1. Preferences->Python Interpreter -> change to another python.exe (within a new anaconda environment). Error message occurs here.
2.  Open new console
3. 

**What is the expected output? What do you see instead?**
I expect a new console to open, however it just continues to attempt to connect.

**Please provide any additional information below**

  File "C:\Users\RDCERWAW\AppData\Local\Continuum\anaconda2\envs\arc1041\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\RDCERWAW\AppData\Local\Continuum\anaconda2\envs\arc1041\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\RDCERWAW\AppData\Local\Continuum\anaconda2\envs\arc1041\lib\site-packages\spyder\plugins\ipythonconsole.py", line 994, in create_new_client
    interpreter=pyexec)
  File "C:\Users\RDCERWAW\AppData\Local\Continuum\anaconda2\envs\arc1041\lib\site-packages\spyder\utils\programs.py", line 425, in is_module_installed
    return eval(output.decode())
  File "<string>", line 1
    could not open C:\Python27\ArcGISx6410.4\Lib\site-packages\DTBGGP64.pth
                 ^
SyntaxError: invalid syntax

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.10
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Seems like the issue is with the Python interpreter you selected, perhaps? Does it work with other interpreters? If so, then it is probably something specific to that, and most likely not within Spyder's control. However, if you can provide more detailed information isolating the problem to Spyder specifically, then we can try to take a look...

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.

**Comment by MadDenker** [comment]
Can we re-open this ticket?  

I am trying to make pyspark.cmd my custom interpreter and I get the following error message: "You selected an invalid Python interpreter for the console so the previous interpreter will stay.  Please make sure to select a valid one."  It appears only exe extensions are accepted.  I am using Windows 10.

**Comment by ccordoba12** [comment]
> It appears only exe extensions are accepted

That's correct.
