### ISSUE TITLE
Selecting a window layout crashes the session

### ISSUE THREAD

**Issue by Swarchal** [spyder-ide/spyder#6016]
## Description

**What steps will reproduce the problem?**

1.  Clicking on View -> Window layouts -> picking a pre-defined layout

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/scott/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1769, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "/home/scott/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1889, in quick_layout_switch
    self.setup_default_layouts(index, settings)
  File "/home/scott/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1616, in setup_default_layouts
    action.setChecked(widget.dockwidget.isVisible())
AttributeError: 'NoneType' object has no attribute 'isVisible'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Something is up with your preferences file, most likely...try `spyder --reset` from the command line to fix it. If that doesn't help, then you can try a clean uninstall or reinstall of anaconda. If neither of those works, then if you can post anything specific about anything you did leading up to this, as well as anything particular about your environment, we might be able to determine what is going on, and if it can be isolated to something in Spyder.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
