### ISSUE TITLE
spyder text scaling issue

### ISSUE THREAD

**Issue by cradbooker** [spyder-ide/spyder#6018]
## Description
![image](https://user-images.githubusercontent.com/28318828/34175269-8a7a5a7a-e4c1-11e7-87dd-0adb9810c5fe.png)
Text scaling for some selection options is enlarged. All functionality appears to be working properly.
Using laptop + dock + 2 external monitors. Issue began occuring after placing laptop onto dock.

**What steps will reproduce the problem?**

1. The issue is always present, even after reboot, updating drivers
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Windows 10 Pro
Version 1607
OS Build 14393.693
Intel HD Graphics 620
Driver version: 22.20.16.4771

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
Have you used our scaling options present in

    Preferences > General > Appearance > Screen resolution

to get a better scaling?

**Comment by cradbooker** [comment]
yes, i have tried each of the scaling options. This does not correct my issue: some text (e.g. file tab names) is larger than other text in the window. The issue scales as different scaling options are selected. Additional example here:
![image](https://user-images.githubusercontent.com/28318828/34180608-f8363558-e4d4-11e7-8370-ed8c088962a7.png)

**Comment by ccordoba12** [comment]
Too bad this is not fixed by our scaling options. That's the best we can provide right now.

@CAM-Gerlach, do you have HiDPI resolution monitors to test this?

**Comment by CAM-Gerlach** [comment]
I'm afraid not, at least at the moment, though I might be able to borrow one at some point if need be...

**Comment by CAM-Gerlach** [comment]
@ccordoba12  I just tested it on a colleague's hiDPI (4K) monitor on Windows, and once HiDPI support is enabled I don't see the issue as described. Might it need 2+ monitors?

**Comment by ccordoba12** [comment]
Closing because this hasn't been reported in a long time,
