### ISSUE TITLE
Warning is not displayed on the correct line for unknown variables in fstring

### ISSUE THREAD

**Issue by Prikers** [spyder-ide/spyder#6020]
## Description of your problem

**What steps will reproduce the problem?**
(I did not find an open issue about it but I may be wrong)
1. Create a fstring with an unknown variable (see screenshot)
2. There is a warning message about it but it is displayed on the first line of the script whichever line the issue is

![image](https://user-images.githubusercontent.com/20270441/34208237-f3319b7e-e58d-11e7-891d-f38015adb563.png)

**What is the expected output? What do you see instead?**
The warning message should be in row 10 in the above screenshot

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment]
I could not reproduce this with `pyflakes` 1.6.0 (and `pycodestyle` 1.7.4) with all other relevant dependencies identical on Win 8.1 and Python 3.6.3, using the same Spyder and Qt/PyQt versions as you.

I get the above warning on line 10, plus some pep8 warnings there and line 11.

![image](https://user-images.githubusercontent.com/17051931/34219673-96e9f052-e577-11e7-84f1-8294a48e608f.png)

**Comment by jnsebgosselin** [comment]
I can reproduce it on Python 3.6.2 64bits, Qt 5.9.2, PyQt5 5.9.1 on Windows 7

pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.0 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.1 (OK)

**Comment by jnsebgosselin** [comment]
Problem is still there after upgrading pyflakes to 1.6.0

**Comment by CAM-Gerlach** [comment]
That's odd; try as I might I could not manage to reproduce the behavior on my machine, whether by typing the text, or copy/pasting it in multiple trials, and even disabling e.g. code style analysis to match @Prikers . I have the same core versions (Spyder, Python, Qt/PyQt) and the following dependencies:

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

I can try tomorrow on my Win 10 machine, just in case that does it...

**Comment by CAMGerlach-Baron** [comment]
Same (cannot reproduce) results on my Win 10 machine...

![image](https://user-images.githubusercontent.com/32848199/34310720-afff5a34-e71e-11e7-9dca-03fa760012c5.png)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 10 Pro x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

**Comment by csabella** [comment]
I tried on Ubuntu with the official release running 3.6.4, 3.x branch, and master branch and couldn't recreate it.  I also tried on Windows 7 with 3.2.4 running 3.6.3 and couldn't recreate it.

I changed my dev to pyflakes 1.5.0 and still couldn't reproduce it.

**Comment by CAM-Gerlach** [comment]
Curiosier and curioser...the only thing I note that differentiates the positive from the negative trials, considering OSes/versions, Qt/PyQt versions, Spyder versions, pyflakes, pycodestyle, IPython, qtconsole, rope, and jedi is that the positive reports have been on Python <= 3.6.2, and the negative ones >= 3.6.3. Any way either of you two can update to that version or later, just for completeness? 

Also, would there be any chance it has to do with the exact sequence of user side actions we are taking to replicate this, or our user-side preferences? I also did not manage to reproduce this in fresh out of the box Spyder 3.2.5 after `spyder --reset`; can either of you try it under that state to check if it makes a difference? Neither copying nor typing the text manually did it for me either.

**Comment by Prikers** [comment]
That is curious indeed! Here what I tried on my home machine (details below):

- Before updating to `3.2.5` 
- After updating to `3.2.5`
- After a `spyder --reset` (spyder `3.2.5`)

I can reproduce the problem for all steps. 

`Python 3.6.1 64 bits, Qt 5.6.2, PyQT5 5.6 on Windows 7` 
```
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
@Prikers, do you have a HiDPI screen?

**Comment by CAM-Gerlach** [comment]
@Prikers It seems like the only consistent element, as mentioned before, is still that all reports of the problem are on Python <= 3.6.2 (3.6.0, 3.6.1, 3.6.2), while all those of it working fine are on Python >= 3.6.3 (3.6.3, 3.6.4). Maybe you could try updating Python to 3.6.3 or later and see if that changes anything?

**Comment by jnsebgosselin** [comment]
- Pip installed, Spyder 3.2.6.dev0 (Commit: 280bb3060), Python 3.6.2 64bits, Qt 5.9.2, PyQt5 5.9.1 on Windows 7 64 bits -> Bug is **reproducible**.
- Anaconda, Spyder 3.2.4, Python 3.6.1 64bits, Qt 5.6.2, PyQt5 5.6 on Windows 7 64 bits -> Bug is **reproducible**
- Anaconda, Spyder 3.2.5 , Python 3.6.3 64bits, Qt 5.6.2, PyQt5 5.6 on Windows 7 64 bits -> Bug is **not reproducible**

Then I upgraded python on my pip install:
- Pip installed, Spyder 3.2.6.dev0 (Commit: 280bb3060), Python 3.6.4 64bits, Qt 5.9.2, PyQt5 5.9.1 on Windows 7 64 bits -> Bug is **not reproducible**

So the problem seems to be fixed on Python > 3.6.2 on my machine.

**Comment by Prikers** [comment]
Thanks @CAM-Gerlach. Indeed, I was considering the python version as the probable root cause. 
Updating python to `3.6.3` fixes the issue!

**Comment by csabella** [comment]
FYI, I believe this is the CPython issue this related to: https://bugs.python.org/issue30465
