### ISSUE TITLE
Nesting scripts -- runfile to call a script within a script gives KeyError: '__file__' , but run as a selection works fine

### ISSUE THREAD

**Issue by pzajonc** [spyder-ide/spyder#6022]
Is there a limitation or a technique needed for nesting scripts in Spyder?  Carlos Córdoba asked me to put this into the issues tracker.  Here are the nested scripts and symptoms of the problem:

Script1.py is:  `print ("hello")`

Script2.py is:  `runfile ('Script1.py') `

Description of problem:
F9 key runs this line of code fine, the text hello prints out without an error

F5 key or another script such as Script3.py:  runfile ('Script2.py')  gives an error message after printing hello:

Output error:
```
hello
Traceback (most recent call last):

  File "<ipython-input-24-c314cb3c22a8>", line 1, in <module>
    runfile('C:\\Users\\Peter\\Documents\\Roparju Regression\\Accudata\\Base\\Code\\TESTING Step.py')

  File "C:\Users\Peter\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 714, in runfile
    namespace.pop('__file__')

KeyError: '__file__'
```

Comments:

Partial work-around seems to work sometimes but not others, but did get me around may hang-up:
try-except works as a selection run (F9) but not as a module run (F5)
```
    try:
        runfile('C:\\Users\\Peter\\Documents\\Roparju Regression\\Accudata\\Base\\Code\\TEST_functions.py')
    except:
        print(" ")
```

I recognize that the pythonic way to call modules is using __main__ and __init__, but it seems to me runfile should be a viable alternative to that within spyder.  

My application has 4 modules called in sequence by a single driver.  So, I run the driver to run the 4 modules when I want.  But, I also have the option to run (and re-run) the individual modules for testing purposes.  Importantly, to run independently, all 4 modules, in turn, need to run a core services module that defines a general set of functions used throughout the application.  

I am interested in the better, more pythonic way to code what's below as long as I have the flexibility to run all, or just a sub-module stand-along (that is, "file read" and "core functions" should be executable):

```
runfile("driver.py")
    runfile("file read")
        runfile("core functions")
    runfile("data recoding")
        runfile("core functions")
    runfile("model build")
        runfile("core functions")
    runfile("model scoring")
        runfile("core functions")
```

Versions:
```
    python 3.6.1
    ipython 6.2.1
    conda 4.3.31
    spyder 3.2.4
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by pzajonc** [comment]
to clarify:  try/except are my workaround because the called module actually runs before the error.  On completion, it seems, something isn't handed off internally and the message is generated and execution stops.  I'm just reporting what I found.

But I don't want to say this requires a fix.  It could be just a documentation issue.  I don't see an explanation of what runfile actually does.  How does it call __main__ and the other modules like __init__, etc.  Spyder coding should be compatible with python module coding conventions.  What I really need is guidance on how to get back on the right path if I need to nest modules.  Why is runfile limited, and what explains the error message?  How should I code the above example of nested module calls without using runfile?  When is runfile useful, and when is it not?  thanks

**Comment by pzajonc** [comment]
The indents got lost in the example.  The nested calls are:
1 runfile("driver.py")
1.1 runfile("file read")
1.1.2runfile("core functions")
1.2 runfile("data recoding")
1.2.1 runfile("core functions")
1.3 runfile("model build")
1.3.1runfile("core functions")
1.4 runfile("model scoring")
1.4.1 runfile("core functions")

**Comment by CAM-Gerlach** [comment]
@pzajonc  Pro tip: If you include triple back tick above and below your code blocks (or a single one before and after a single line/statement), they'll be treated as `code` and your indents will be respected. I edited your post to demonstrate.

**Comment by pzajonc** [comment]
appreciate that tip! @CAM-Gerlach

**Comment by viniciusmoulin** [comment]
Dear pzajonc , I'm having the same problem you have, with the same error message while calling many runfile paths. Have you solved it?

**Comment by pzajonc** [comment]
Yes, not using runfile and using conventional python module import commands, and import imp  
imp.reload(module) 
To reload when needed.  I don’t think runfile is designed as an alternative to import, a core part of python.

**Comment by CAM-Gerlach** [comment]
To my (albeit limited) knowledge, ``runfile`` is not necessarily intended to be used within a script, but rather a mechanism within Spyder's IPython console, triggered manually or from the Spyder GUI, to run a particular file. As it isn't designed to function outside of the Spyder environment itself, it isn't really intended to be used in scripts or modules and would break interoperability when code is run outside of Spyder, which is generally A Bad Thing™. But that's just my understanding, at least of the current situation, which could certainly change as a fix is presently milestoned for the next release after this current one.

**Comment by ccordoba12** [comment]
> runfile is not necessarily intended to be used within a script, but rather a mechanism within Spyder's IPython console, triggered manually or from the Spyder GUI, to run a particular file.

Yes, that's right. That's why I don't know how to handle this one.

**Comment by CAM-Gerlach** [comment]
Well, I suppose we could treat it as a non-public API that users can implement at their peril, and ``wontfix`` this one unless the community wants to work on it...but I really have no idea, you'd know much better than I.

**Comment by pzajonc** [comment]
If runfile is called where it was not intended out of the command-line, give an error message stating "runfile is only available on command line.  Use python import and imp.reload instead"  That would have helped me avoid the initial confusion!  Thanks

**Comment by CAM-Gerlach** [comment]
We could do that, but not sure how quickly it will get done at the moment. If you'd like, you can submit a PR with the change and we can consider it. It shouldn't be hard to do; just add a ``try``/``except`` block around the relevant line, and throw like a ``RuntimeError`` or something with the message. A simple test for it would just be to call ``runfile`` with an argument from the test module, and make sure the proper error is raised. Also, since you seem to have an idea what's going on, you could also take a crack at fixing it, assuming that's possible without breaking any existing functionality.

**Comment by viniciusmoulin** [comment]
To solve my problem, I used execfile(),  instead of runfile() and it worked
fine. But I'll try using the codes as functions and use import to run them,
for my next codes. Thank you all for the discussions!

Em 28 de jan de 2018 16:54, "C.A.M. Gerlach" <notifications@github.com>
escreveu:

**Comment by ccordoba12** [comment]
I guess not. `runfile` is not meant to be used outside of Spyder and in source code.
