### ISSUE TITLE
Can't lauch the spyder3, under the win10+python3.6 with pip install pyqt5 and spyder2.4

### ISSUE THREAD

**Issue by QuntuamLoop** [spyder-ide/spyder#6023]
## Description of your problem
My laptop is the thinkpad t450 with the python 3.6.4 , and I also have install the pyqt5.9.2  and spyder2.4 with the pip installer. But when I input the command 'spyder3' in cmd gui, it can't show anything. 
The problem just happend under this enviroment, in the python 3.5 or anaconda  spyder3 is still a IDE tools for tensorflow or other science computation.

?

**Comment by jitseniesen** [comment]
Spyder 2.4 is seriously out of date and no longer supported (your issue will be closed for this reason). The latest version is 3.2.4. I suggest you update to that version.

**Comment by CAM-Gerlach** [comment]
Also, `pip` installations are for experts; you are welcome to try to get it working but you're on your own. We recommend the Anaconda distribution or similar otherwise.

**Comment by QuntuamLoop** [comment]
@jitseniesen Sorry, for my mistake. It's 3.2.4, 
![image](https://user-images.githubusercontent.com/32284800/34237192-4c2af7fe-e636-11e7-8270-fada968afe0c.png)
This is my running enviroment, under python 3.5.4+pyqt5.9

**Comment by QuntuamLoop** [comment]
![qq 20171221100337](https://user-images.githubusercontent.com/32284800/34237260-a3dfabd4-e636-11e7-90ae-1e59435d31c4.png)
@jitseniesen It's my mistake. It's spyder3.2.4, which can run in python 3.5.4+pyqt5.9, but python  3.6.4 not.

**Comment by ccordoba12** [comment]
@QuntuamLoop, it could be a number of different things, and (since we're unfunded) we don't have the resources nor the time to help you debug them.

Hence our recommendation (stated above by @CAM-Gerlach) to switch to Anaconda. That's the best we can do at the moment, sorry.

**Comment by QuntuamLoop** [comment]
@ccordoba12 Thank you for your suggestions. And many friends around me, also gave the same solutions.

**Comment by CAM-Gerlach** [comment]
@QuntuamLoop  Best of luck!

**Comment by jnsebgosselin** [comment]
Before you change anything to your setup, no error is shown in the cmd window after you ran `spyder3`?

**Comment by QuntuamLoop** [comment]
@jitseniesen Really not. After I installed the python 3.6.4(or 3.6.x ) in win7 in 64bit or win10 in 64bit， then I opened cmd, installed the pyqt5 and  spyder. But after clicked spyder3, the programe started with nothing. 
![3](https://user-images.githubusercontent.com/32284800/34282525-0126f2f0-e701-11e7-9a3d-a3095c62acd8.png)
![2](https://user-images.githubusercontent.com/32284800/34282529-0c2218c4-e701-11e7-8065-0f809765638c.png)

**Comment by jnsebgosselin** [comment]
@QuntuamLoop Go to you spyder installation folder in the cmd window. This should be something like C:\Python36\Lib\site-packages\spyder and run:

`python bootstrap.py --debug`

Do you get some kind of error traceback from this?

**Comment by QuntuamLoop** [comment]
@jnsebgosselin excuse me, is it a right way?
![image](https://user-images.githubusercontent.com/32284800/34294114-fd9f6ef0-e741-11e7-9957-0f5b9698b956.png)

**Comment by jnsebgosselin** [comment]
@QuntuamLoop Sorry, yeah you did it ok. Ì was wrong, there is no boostrap.py distributed when installed with pip. Only when cloning spyder from the git. 

So, instead, in the folder `spyder` where you are, go in the `app` folder and try to run `start.py` or `mainwindow.py` if it doesn't work. 

If the cmd window closes before you can see anything, you can put your command in a .bat file and add pause at the end. Something like

```
python app.py
pause
```

**Comment by QuntuamLoop** [comment]
@jitseniesen finally, I find it's the problem of markupsafe in utf-8. So I use the pip to reintall the package. Thanks for repling me the method. 
<img width="676" alt="1" src="https://user-images.githubusercontent.com/32284800/34413129-5964861a-ec1c-11e7-891c-dbdd4588f836.png">
<img width="732" alt="2" src="https://user-images.githubusercontent.com/32284800/34413131-5b903196-ec1c-11e7-9441-bb49fa69e8d2.png">

**Comment by jnsebgosselin** [comment]
@QuntuamLoop I'm glad you were able to fix your problem, good job!

**Comment by Sup3rGeo** [comment]
Hey guys, also on windows 10, for me its just hanging in Setting up main window splash:

![image](https://user-images.githubusercontent.com/20566367/39998052-1d19edb0-5785-11e8-80fe-57246ccad9e6.png)

Then when I click the splash, python crashes.

**Comment by fahmanali** [comment]
when I run spyder I get "An error ocurred while starting the kernel
Traceback (most recent call last):
File "C:\Users\msi‑pc\Anaconda3\envs\tenv\lib\runpy.py", line 193, in _run_module_as_main"
and in prompt I get "js: Not allowed to load local resource: file:///C:/Users/msi-pc/Anaconda3/envs/tenv/lib/site-packages/spyder/utils/help/static/css/default.css"

note: I have another environment and spyder is work

**Comment by CAM-Gerlach** [comment]
@fahmanali 

> An error ocurred while starting the kernel

This is clearly an unrelated issue with a very different cause and symptoms; it is a generic Python level issue of not being able to start the kernel, whereas this thread is for a specific Qt/C++ level problem where Spyder segfaults before it even launches. In the future, please at least read the title and initial report in a thread before posting to make sure the issue is the same, or at least related.

> Traceback (most recent call last):
> File "C:\Users\msi‑pc\Anaconda3\envs\tenv\lib\runpy.py", line 193, in _run_module_as_main"

Please provide the full traceback if you want someone to be able to help you.

> js: Not allowed to load local resource: file:///C:/Users/msi-pc/Anaconda3/envs/tenv/lib/site-package/spyder/utils/help/static/css/default.css"

This error message is likely unrelated; I get it quite frequently, typically when another Spyder instance is open IIRC like you state. Perhaps one Spyder instance may be locking/blocking on the file when it shouldn't, but I haven't noticed a significant effect yet other than the message (though I haven't tested help rendering too much when it happens).
