### ISSUE TITLE
Spyder won't start

### ISSUE THREAD

**Issue by OD1995** [spyder-ide/spyder#6024]
## Description of your problem
I have downloaded Spyder using Python(x,y) but I am unable to get it to start.

Looking at problems people have had previously, in the command prompt I entered 
`spyder --show-console`

![spyder show console](https://user-images.githubusercontent.com/34351331/34220578-007d3ae4-e5ad-11e7-8f3a-18e15dcd3d39.PNG)

This suggested I needed to install pathlib2
![pip install pathlib2](https://user-images.githubusercontent.com/34351331/34220604-19208998-e5ad-11e7-89ae-281a12b95217.PNG)

A google search suggests this problem can be solved by uninstalling enum34
![pip uninstall enum34](https://user-images.githubusercontent.com/34351331/34220705-6caef19e-e5ad-11e7-9f04-7324e2731e7e.PNG)

So it appears I'm now going around in circles

I am on Windows 10. I had Python (3.6.3) installed before I downloaded Python(x,y) and I also have Anaconda installed, I'm not sure if any of these might explain my problem.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Unfortunately, these sorts of problems are common when using distributions other than Anaconda, or manual installation with `pip`, so we don't officially support them. You're welcome to try to get them to work on your own, but if you have trouble Anaconda is usually a much better solution for non-experts. Therefore, this issue will be closed.
