### ISSUE TITLE
Sum of List gives error in Spyder but not in Jupyter Notebook

### ISSUE THREAD

**Issue by PabloRR100** [spyder-ide/spyder#6025]
## Description of your problem
The sum of lists is raising: '''TypeError: cannot perform reduce with flexible type'''

**What steps will reproduce the problem?**

1. Create the cross function
```
def cross(A, B):
    # Return all possible concatenations of 2 strings
    return [s+t for s in A for t in B]
``` 
2.  Create Python lists
```
rows = 'ABCDEFGHI'
cols = '123456789'

cells     = cross(rows, cols) # --> Creates list of strings of all the cells
row_units = [cross(r, cols) for r in rows]
col_units = [cross(rows, c) for c in cols]
box_units = [cross(rs, cs) for rs in ('ABC', 'DEF', 'GHI') for cs in ('123', '456', '789')]
```
3. Move lists to dictionaries 
```
unitlists = row_units + col_units + box_units # Concatenate lists into 1 list (9+9+9 = 27 length)
units = dict((s, [u for u in unitlists if s in u]) for s in cells) 
peers = dict((s, set(sum(units[s],[])) - set([s])) for s in cells) 
```
That last line peers is raising the next error:
```
TypeError: cannot perform reduce with flexible type
```

**What is the expected output? What do you see instead?**
The output is to create a dictionary with that values, as I am able to get in Jupyter Notebook, for example.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: Spyder 3.2.4
* Python Version: Python 3.6.0
* Operating system: Mac Os High Sierra

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.4.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by CAM-Gerlach** [comment]
Thanks for posting that detailed report. Unfortunately, I was unable to reproduce the same behavior on Spyder 3.2.4 with Python 3.6.3 and Win 8.1. You could always try `spyder --reset` and updating your packages, though given this is apparently with core python, not sure how much that would help. Does it occur if you run the same lines in bare `qtconsole`? How are you running the lines—line by line, as a cell, or running a whole file? Beyond that, are you running Spyder and/or Jupyter with Anaconda, or something else? If nothing else, you could always try a clean reinstall.

Just so you know, if you include three backticks (top left key on a standard qwerty keyboard), your code will be printed verbatim without extranous formatting that makes it difficult to copy and paste properly—I've fixed your post above.

**Comment by PabloRR100** [comment]
Thanks for the early response!

My Python version is Python with Anaconda, sorry for not including that. 
Your command ```spyder --reset``` has worked! It has restores Spyder and the error is not being raised. Given that, do you know what was happening? So I can better solve the problem if it occurs again.

Thank you again so much

**Comment by ccordoba12** [comment]
@PabloRR100, most probably you had activated the option to load pylab automatically, which loads `sum` from Numpy, which is different from the regular `sum`.
