### ISSUE TITLE
When comparing a generated and loaded profile, any negative deltas show (actual_value - ?) 1h:60min, not actual value

### ISSUE THREAD

**Issue by chengtian5huang** [spyder-ide/spyder#6032]
Load data to compare when the loaded data is faster it shows 1h60min,espically the figure is so small,for example 5 ms compare to 3ms,it shows -1h:60min
![default](https://user-images.githubusercontent.com/34744187/34260615-8a4b27fa-e6a1-11e7-972a-b74415b7a9dd.PNG)
**u can easily reproduce it by doing some quick things**

```python
import time
def delay(howlong):
    time.sleep(howlong)
delay(0.005)
print('delay finish')
```

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by ccordoba12** [comment]
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by ccordoba12** [comment]
Unfortunately your description is not clear enough.

**Comment by chengtian5huang** [comment]
![default](https://user-images.githubusercontent.com/34744187/34260615-8a4b27fa-e6a1-11e7-972a-b74415b7a9dd.PNG)
so sorry i forget the pic once u see the pic u know what i am talking about.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Reproduced. This seems to indeed be a bug, from what I can tell.

![image](https://user-images.githubusercontent.com/17051931/34264707-608e51fc-e639-11e7-8890-a1b6536167f5.png)
