### ISSUE TITLE
missing dependency on pyqt5?

### ISSUE THREAD

**Issue by allefeld** [spyder-ide/spyder#6043]
## Description of your problem

**What steps will reproduce the problem?**

1. install python3 under Debian stable
2. `sudo pip3 install  spyder`
3. start Spyder

**What is the expected output? What do you see instead?**

The Spyder GUI should open. It doesn't. If I start Spyder from the command line, I get an error message about a missing module "PyQt5.QtSvg".

**Please provide any additional information below**

The problem can be resolved by installing PyQt5 manually via `sudo pip3 install pyqt5`. The problem might be that Debian provides only the Python 2 version of PyQt5.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.5.3 (from Debian package python3_3.5.3-1_amd64)
* Qt Version: 5.7.1
* PyQt Version: 5.9.2
* Operating system: Debian GNU/Linux stable (9.3)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
IPython >=4.0    :  5.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.4.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This is addressed in the Spyder installation instructions in the documentation and in the package readmes, etc., as PyQt5 must indeed be installed separately when installing manually with `pip`. Unfortunately, such installs can have many pitfalls and dependency issues vs. using a ready to go distribution like Anaconda/Miniconda, so they aren't formally supported, though experienced users such as yourself are welcome to get it working on your own (as you have). Recently, I've submitted a couple PRs improving and clarifying the install documentation and adding a section detailing Anaconda for Linux, so hopefully that helps as well. Therefore, this issue will be closed. Best of luck!

**Comment by allefeld** [comment]
Hi @CAM-Gerlach , I was following the instructions under "Installing on Linux" <http://pythonhosted.org/spyder/installation.html#installing-on-linux>. That does refer to the list of requirements <http://pythonhosted.org/spyder/installation.html#requirements>, but it doesn't say that the only requirement that is not installed automatically is PyQt5. So I'd recommend to write explicitly that one has to run `sudo pip install pyqt5`.

**Comment by ccordoba12** [comment]
This will be added in our 3.2.5 version.

**Comment by CAM-Gerlach** [comment]
@allefeld Ah, I see, thanks. I'd just been doing some minor updates to that doc and, as I was already seeing the current 3.x version (that will go out with 3.2.5 very soon), I wasn't aware it had just been added.  In any case, already fixed.
