### ISSUE TITLE
start spyder  encounter an error

### ISSUE THREAD

**Issue by xxcheng0708** [spyder-ide/spyder#6046]
## Description

**What steps will reproduce the problem?**

1. start spyder on the windows 7 X64
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Unfortunately, your error report doesn't contain any information, such as a traceback or error message, a detailed description of if it worked before, what you did preceding the error, and what you tried to fix it, and information on anything particular to your setup and how you installed Spyder, that would allow us to address it. In any case, this is most likely a user-side issue that can be resolved by a clean install of the up to date Anaconda distribution. Therefore, this issue will be closed promptly. 

If you are able to provide this information to isolate it to a problem with Spyder, then you are welcome to do so and reopen the issue. Best of luck!
