### ISSUE TITLE
Window size not restored after returning from full screen

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#605]
_From [petrus.h...@gmail.com](https://code.google.com/u/113904071220560210639/) on 2011-03-31T13:21:51Z_

What steps will reproduce the problem?

 1. Enter full screen mode
2. Leave full screen mode What is the expected output? What do you see instead? That the spyder window would have the same size as before entering full screen. Now the window becomes very wide (wider than screen) and can not be dragged smaller (larger works) What version of the product are you using? On what operating system? spyder from repository, mac osx 10.6.7, EPD python distribution 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=605_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-04T13:31:57Z_

This is true on Linux and Windows too, although without the nasty effect described by Petrush.

I think the window size has to be registered before going full screen so that after returning from it, it could recover its proper size.

**Summary:** Window size not restored after returning from full screen  
  **Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:29:53Z_

**Labels:** Cat-SpyderGUI

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-20T12:18:23Z_

Following recent changes in the development version, this could be fixed.
Could you please check this?

**Comment by spyder-issues-migrator** [comment]
_From [petrus.h...@gmail.com](https://code.google.com/u/113904071220560210639/) on 2011-05-20T15:25:59Z_

Tried 2.1.0dev updated just now, and bug is still there on mac osx 10.6. Tried to delete all old spyder stuff and reinstall but no change.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-20T17:13:43Z_

Now it's working better. If you go full screen from a non-maximized window, then switching back preserves the size correctly.

The only problem that remains to be solved is when spyder is maximized. After switching back, you don't return to a maximized window, but to a non-maximized window which size is equal to the last non-maximized window you defined.

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-22T06:03:05Z_

This issue was closed by revision 2e17400bd5b5 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-05-22T09:05:17Z_

Thanks Pierre, it's working great now!

**Comment by AnasKamali** [comment]
![Untitled](https://user-images.githubusercontent.com/17400499/60316998-b3a54480-998a-11e9-9cd5-e52e05541db4.png)
spyder is not maximizing.
what should i do?
Every time i launch it, it remains in background.
