### ISSUE TITLE
\r (CR) does not work in Spyder's IPython console

### ISSUE THREAD

**Issue by allefeld** [spyder-ide/spyder#6054]
## Description of your problem

In a script with a lengthy search operation, I want to give the user feedback that "we're on it". To do so, I use the following code

```
sys.stdout.write('...')
sys.stdout.flush()
# lengthy operation
sys.stdout.write('\r')
# further output
```
The idea is that the dots indicating "we're on it" are overwritten by later output. This works as expected when I run the script from an IPython console in a standard terminal window (KDE's Konsole 16.12.0), but not in the IPython console integrated in Spyder. Instead, the dots stay visible and further output is appended, as if there was no "\r".

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.5.3
* Qt Version: 5.7.1
* PyQt Version: 5.9.2
* Jupyter Notebook Version:
* Operating system: Debian GNU/Linux 9.3

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  5.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.4.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by CAM-Gerlach** [comment]
Thanks for your detailed report. I tried the following minimal snippet to reproduce the behavior you're seeing:

```
import sys
import time
sys.stdout.write('...')
sys.stdout.flush()
time.sleep(5)
sys.stdout.write('\r')
sys.stdout.write('Further output')
```

However, run file, run cell, and run selection in both Spyder and bare `qtconsole` all displayed correctly; first writing a `...` and then replacing it with `Further output` at the appropriate time. Therefore, assuming there is nothing substantially different about the parts of the code you didn't include (try running the above snippet to make sure), it seems that it is likely to be either a result of something specific to how `qtconsole` handles `stout` on your OS, or something different with your dependencies. I ran in on a Win 8.1 Pro x64 machine with the same version of Spyder, and the following different dependencies:
* Python 3.6.3 x64
* Qt Version: 5.6.2
* PyQt Version 5.6
* IPython 6.1.0

If there's a way you can test it with those dependency versions (or something closer), as well as the above snippet, that should help narrow it down to an OS issue (quite possible) or not. Also, can you test it on just bare qtconsole, and the different ways of running the code (run file vs. send selection/cell directly to the console)? If it still occurs similarly in the former, then you'll want to submit it to the `qtconsole` repo instead as the problem would then presumably be in that code base. Best of luck!

**Comment by allefeld** [comment]
I did some further research, and now I believe it has nothing to do with Spyder / IPython / qtconsole...

In my actual code I use imdbpie, a library to access IMDb data, and between `sys.stdout.write('\r')` and the further output (via `print`), there is a call to obtain additional data regarding a movie. This call should access the internet and modify an object, but shouldn't have anything to do with console output at all. But, if I remove that call, everything works as it should. A mystery.

Thank you for your reply and sorry for the false alarm!

**Comment by CAM-Gerlach** [comment]
Thanks for following up!
