### ISSUE TITLE
Wrong result of static code analysis

### ISSUE THREAD

**Issue by J-Ty** [spyder-ide/spyder#6061]
## Description
Static code analysis reports an error "module numpy.random has no multivariate_normal member" although such a method exists and the code actually runs without any problems. 

**What steps will reproduce the problem?**

1. Enter code
```
"""minimal example of static code analysis fault"""
import numpy.random
SAMPLE = numpy.random.multivariate_normal([1, 1], [[1, 0], [0, 1]], 50)
```

2. Press F8 or choose "Run static code analysis" from the "Source" menu

**What is the expected output? What do you see instead?**
The expected output is "no issues". 
However, I get an error message "module numpy.random has no multivariate_normal member".
The code runs correctly, so the method indeed is there.  

The state of spyder after code analysis and running the file is presented on the attached picture. 
<img width="625" alt="spyder" src="https://user-images.githubusercontent.com/34869760/34364501-fc8d477e-ea86-11e7-9a48-a33cc8ca362e.png">

**Please provide any additional information below**

## Version and main components

* Win10 64 bit
* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by J-Ty** [comment]
Problem persists after update to 3.2.5.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This (and its many relatives) is a well known issue with `numpy` and `pylint`, and doesn't have anything directly to do with Spyder. You can fix/work around it with e.g.

```
[TYPECHECK]

ignored-modules = numpy
ignored-classes = numpy
```

in your `,pylintrc` file. Thus, this issue will be closed.

**Comment by CAM-Gerlach** [comment]
Also, as a sidenote/protip, triple backtick 
``````
```
will get you verbatim code blocks.
