### ISSUE TITLE
Python3 - Change Workingdirectory to scripts directory

### ISSUE THREAD

**Issue by FelixEcker** [spyder-ide/spyder#6077]
Hello,
im currently writing a program and i need to change the directory often, now i need to change the Directory to the scripts directory. I tried something like: `os.chdir(os.path.dirname(sys.argv[0]))`
but that just says that the path doesn't exists, does anyone know a soloution for Python3.6??

(And sorry for my bad english im actually german)

**Comment by FelixEcker** [comment]
Sorry wrong forum...

**Comment by ccordoba12** [comment]
> im currently writing a program and i need to change the directory often, now i need to change the Directory to the scripts directory

By simply running your file with `F5` or going to the menu

    Run > Run

you'll get this result. You don't need to do anything else in Spyder.
