### ISSUE TITLE
Variable Explorer throws an error instead of displaying contents when attempting to inspect any loaded modules

### ISSUE THREAD

**Issue by adlerosn** [spyder-ide/spyder#6080]
## Description

I double-clicked a module which was the value of a `dict` in variable explorer and got an error.

**What steps will reproduce the problem?**

1. Import a module (example: `import os`)
2. Initialize a `dict` in a variable (example: `d=dict()`)
3. Assign the module to the dict (example: `d['os']=os`)
4. Double-click the cyan entry of your variable on variable explorer
5. Double-click the white entry which corresponds to your module
6. You see the error reporting window.

**What is the expected output? What do you see instead?**

I expected seeing the global variables defined in the module, but I got an error reporting window.

**Please provide any additional information below**

#### Stack trace
```
  File "/usr/local/lib/python3.6/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 513, in createEditor
    readonly=readonly)
  File "/usr/local/lib/python3.6/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 1315, in setup
    self.data_copy = copy.deepcopy(data)
  File "/usr/lib/python3.6/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle module objects
```

#### Screenshot
![screenshot_2017-12-28_16-23-15](https://user-images.githubusercontent.com/12143895/34419520-7fa595ac-ebeb-11e7-8b13-ed98cb5c49ac.png)

## Version and main components

* Ubuntu Studio 17.10
* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I reproduced this with your minimal example:
```
import os
d = dict()
d["os_test"] = os
d["other_test"] = "Other"
```
This actually appears to be changed from Spyder 3.2.4; in the former version, the dictionary simply didn't open at all in a CollectionsEditor; in the latter, it behaved as you described, both opening the dictionary itself and then trying and failing the module object (while succeeding in editing "Other"). 

Looking at the error trace, when a `CollectionsEditor` is opened on a non-standard object like a module, it does a `deepcopy()` of the collection and the objects within, presumably such that it can either save the modified state on an "Ok", or discard it on "Cancel", etc. However, that doesn't work on a module for internal python reasons, so it throws an uncaught error. I'm taking a look at the code right to figure out how to best handle it; we should be able to do _something_ about it.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, it should be enough with catching the `TypeError` generated by this and then `pass` if that happens.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Yup, that's just what I was trying right now!

**Comment by ccordoba12** [comment]
Great! Thanks for taking a look at it!

**Comment by CAM-Gerlach** [comment]
Just a tad more complicated than that (and had to deal with a random conda-env issue), but I got it working just fine without much trouble. I assume I should add a test for it?

**Comment by ccordoba12** [comment]
Only if it doesn't take you much time. Else, just having the fix is fine 
by me.

**Comment by CAM-Gerlach** [comment]
Too late :)

**Comment by CAM-Gerlach** [comment]
Actually, in 3.2.5 this apparently now happens whenever _any_ module is attempted to be opened from the VariableExplorer, inside a dict or not. It seemed odd in the code that only the latter would trigger the relevant bug, so that actually makes sense. It worked in 3.2.4, so not sure why the regression but this should fix it for good regardless.

**Comment by ccordoba12** [comment]
In 3.2.5 we changed to use cloudpickle to get values from the kernel and 
send them to Spyder. Since that library is able to serialize more 
objects than the pickle module, it's to be expected that problems like 
this would appear afterwards.

**Comment by CAM-Gerlach** [comment]
Yeah, I think that was the change that I mentioned vaguely remembering above since it was potentially related to another issue I was having. In any case, this should simplify the test since it only needs to deal with the general case.
