### ISSUE TITLE
Spyder keeps crashing when replacing all values

### ISSUE THREAD

**Issue by leiberl** [spyder-ide/spyder#6086]
## Description
Spyder crashes when I try to "replace all". I have lost a lot of work because of this bug.

**What steps will reproduce the problem?**

1. Highlight the value to replace
2. Cmd+R 
3. Cmd+C 
4. Select the box for the replacement value
5. Cmd+V
4. Modify the value to replace with
5. Press "Replace all"

**What is the expected output? What do you see instead?**
It crashes.

**Please provide any additional information below**
MacBook Pro (Retina, 13-inch, Mid 2014)
macOS High Sierra v.10.13.2

Doesn't seem to matter if I launch Spyder from the terminal or from Anaconda.

Running in virtual conda environment w/python 2.7 

Error message from terminal:
/Users/XXX/anaconda3/envs/test_env/bin/pythonw: line 3: 30106 Segmentation fault: 11  /Users/XXX/anaconda3/envs/test_env/python.app/Contents/MacOS/python "$@"

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 2.7.13
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.18.1 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.5.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  5.1.3 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.2.2 (OK)
pylint >=0.25     :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Sorry to hear that but Anaconda has not updated its Qt package to work with High Sierra, so I think that's the most probable cause of this problem.

Please run in a terminal

    conda update python.app

and try again. Maybe that helps.

**Comment by leiberl** [comment]
Thanks! I seems to have solved the issue.
