### ISSUE TITLE
Spyder does not launch on windows 8 (Anaconda3-5.0.1-Windows-x86_64)

### ISSUE THREAD

**Issue by rahul1994** [spyder-ide/spyder#6097]
i tried to open syder using anaconda prompt

C:\Users\rahul>spyder --show-console
Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)
and i get the window popping showing "python stopped working"  

i got the above error , i also tried reinstalling the anaconda and excluded Anaconda3 folder from virus scanning

**Comment by ccordoba12** [comment]
Please deactivate your firewall/antivirus and try again.

**Comment by CAM-Gerlach** [comment]
Also, I am currently on Windows 8 x64 with Anaconda3 5.0.1 and Spyder 3.2.4 and 3.2.5, and have seen no similar issues. Accordingly, if we don't hear from you after a week (7 days), we'll assume the issue is resolved or unrelated to Spyder, and thus it will be closed. Thanks, and best of luck.

**Comment by rahul1994** [comment]
It works fine after after manupulating firewall and antivirus settings. Thanks....

**Comment by ashish1610dhiman** [comment]
My Spyder also does not open and crashes on startup (With the popup indicated python stopped working)

Error Message on running spyder from Anaconda Console:

(base) C:\Users\Dhiman>spyder
_Assertion failed: Protocol wrong type for socket [10041] (C:\ci\zeromq_154902559
4292\work\src\ip.cpp:417)
[10040:2208:0421/105302.935:ERROR:broker_win.cc(59)] Error reading broker pipe:
The pipe has been ended. (0x6D)_

I am using Spyder 3.3.3 and Windows 7 (64 bit). Please Help resolve the issue.

**Comment by CAM-Gerlach** [comment]
@ashish1610dhiman This issue has been resolved, closed and marked unrelated to Spyder for well over a year; *and* your error message is different from that in the original issue report. Therefore, you should not be posting that here.

Did you even try disabling any firewall, antivirus and any other security software you may have installed and trying to start Spyder again, which is exactly what the fixed the OP's issue? Other than that, the error ``Error reading broker pipe: The pipe has been ended. `` has been reported many times before, with a variety of solutions which you should try (testing Spyder after each one):

* ``conda update spyder spyder-kernels qtconsole``
* Uninstalling ``spyder-autopep8`` or any other Spyder plugins
* ``conda update pyzmq zeromq ipykernel jupyter_client ipython``
* ``conda install pyzmq=17``
* ``conda install pyopengl``
* ``conda update qt pyqt qtpy``
* Update your graphics drivers
* Switch graphics cards
* ``conda install pyqt=5.6``

If none of that works, please open a new issue about your problem with *all* the requested information, and we'll try to help. Thanks, and best of luck.
