### ISSUE TITLE
Use to_unicode_from_fs when saving project paths

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#6103]
Although no one has reported problems about this, it's something we need to do.

**Comment by jnsebgosselin** [comment]
Could this be related to https://github.com/spyder-ide/spyder/issues/5799 or https://github.com/spyder-ide/spyder/issues/5601? Or maybe these issues can be solved with a fix similar to the one proposed here?

**Comment by ccordoba12** [comment]
#5601 is a different issue, but this one is certainly a duplicate of #5799, so I'm closing it.
