### ISSUE TITLE
Spyder crashes before opening

### ISSUE THREAD

**Issue by avi-deka** [spyder-ide/spyder#6111]
What steps will reproduce the problem?**

1. Open Anaconda Navigator
2. Launch Spyder
3. Spyder does not open and "Python is not responding" pops up

What is the expected output? What do you see instead?**
Expected Spyder to open but it crashes instead.

Please provide any additional information below**
I have tried re-installing many times, but nothing changes. Also tried to create a new python3.5 env and open Spyder there, but it did not launch. Changing firewall settings have also not helped. It did not launch when I tried to open using the command prompt either. 
spyder --reset has not helped.

Versions and main components

Spyder Version: 3.2.5
Python Version: 3.6.3
Qt Versions: 5.6.2, 
PyQt5 5.6.0
Operating system: Windows 10

Any help will be greatly appreciated.

**Comment by ccordoba12** [comment]
Please open a terminal (cmd.exe) then run

    spyder

and paste here the error messages you get there.

**Comment by CAM-Gerlach** [comment]
Thanks for your report, and we appreciate you trying those troubleshooting solutions on your own. Have you tried launching it from the start menu shortcut? Did you do a clean reinstall of the full, latest Anaconda distribution, or just Spyder? Do other Anaconda applications (jupyter, etc.) run just fine? Have you installed any spyder plugins?

If none of that fixes it, you should try what is suggested in the comments to Issue #6023 , and let us know what it reports. Also, you can try running with the debug flag on; type ``set SPYDER_DEBUG=3`` , hit enter, than run spyder from that same prompt (``spyder``), and see what it reports.

Finally, you'll also want to provide us with some more information about your environment: from your ``conda list`` output, your Qt and PyQt versions, along with anything special, unusual or out of the ordinary about the machine you're running it on.

**Comment by avi-deka** [comment]
The following message is displayed when I run spyder from the terminal :

**Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
        QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
        QT_SCREEN_SCALE_FACTORS to set per-screen factors.
        QT_SCALE_FACTOR to set the application global scale factor.**

And then after some time, the cursor changes to a rotating circle and "Python is not responding message" pops up.

1. Yes I have tried relaunching from the start menu. Same problem occurs.
2. I did a clean reinstallation of Anaconda, not just Spyder.
3. I don't really use anything other than Spyder, but now when I checked, running `jupyter qtconsole` 
   from the terminal gives the same message in the terminal. I waited for about 15 minutes for QtConsole 
   to open, but it didn't, so I closed the terminal.
4. When I tried using a debug flag, following is shown:
    **Warning: QT_DEVICE_PIXEL_RATIO is deprecated. Instead use:
        QT_AUTO_SCREEN_SCALE_FACTOR to enable platform plugin controlled per-screen factors.
        QT_SCREEN_SCALE_FACTORS to set per-screen factors.
        QT_SCALE_FACTOR to set the application global scale factor.
    Start of MainWindow constructor
    appusermodelid: 0
    End of MainWindow constructor
    *** Start of MainWindow setup ***
      ..core actions
      ..toolbars
      ..tools
      ..sift?
      ..plugin: internal console
        ..internal console: initializing
      ..plugin: working directory
    Loading help...
    Loading outline explorer...
    Loading editor...**
    
  It stays like this for at least 20 mins, and then my cursor changes to a rotating circle, and the "Python 
  is not responding" error pops up.
5. This is the `conda list` from my base env:

# packages in environment at C:\Users\pc\Anaconda3:
#

```
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
alabaster                 0.7.10           py36hcd07829_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.6            py36ha174c20_0
anaconda-navigator        1.6.11           py36h25c516c_0
anaconda-project          0.8.2            py36hfad2e28_0
asn1crypto                0.23.0           py36h546eea3_0
astroid                   1.5.3            py36h9d85297_0
astropy                   2.0.3            py36hfa6e2cd_0
attrs                     17.3.0           py36hc87868e_0
babel                     2.5.0            py36h35444c1_0
backports                 1.0              py36h81696a8_1
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2
beautifulsoup4            4.6.0            py36hd4cc5e8_1
bitarray                  0.8.1            py36h6af124b_0
bkcharts                  0.2              py36h7e685f7_0
blaze                     0.11.3           py36h8a29ca5_0
bleach                    2.1.1            py36h834942a_0
bokeh                     0.12.13          py36h047fa9f_0
boto                      2.48.0           py36h1a776d2_1
bottleneck                1.2.1            py36hd119dfa_0
bzip2                     1.0.6                haa5b126_2
ca-certificates           2017.08.26           h94faf87_0
cachecontrol              0.12.3           py36hfe50d7b_0
certifi                   2017.11.5        py36hb8ac631_0
cffi                      1.11.2           py36h829d1a5_0
chardet                   3.0.4            py36h420ce6e_1
click                     6.7              py36hec8c647_0
cloudpickle               0.5.2            py36h6b1d831_0
clyent                    1.2.2            py36hb10d595_1
colorama                  0.3.9            py36h029ae33_0
comtypes                  1.1.2            py36heb9b3d1_0
conda                     4.4.6                    py36_0
conda-build               3.2.0                    py36_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h065de53_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py36he5d52c0_0
coverage                  4.4.2            py36hd32d05b_0
cryptography              2.1.4            py36he1d7878_0
curl                      7.55.1               h3b839b5_4
cycler                    0.10.0           py36h009560c_0
cython                    0.27.3           py36h22f4c84_0
cytoolz                   0.8.2            py36h547e66e_0
dask                      0.16.0           py36hea4f2f0_0
dask-core                 0.16.0           py36h5683b08_0
datashape                 0.5.4            py36h5770b85_0
decorator                 4.1.2            py36he63a57b_0
distlib                   0.2.5            py36h51371be_0
distributed               1.20.2                   py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3            py36hfd66bb0_2
et_xmlfile                1.0.1            py36h3d2d736_0
fastcache                 1.0.2            py36hffdae1b_0
filelock                  2.0.13           py36h20000bf_0
flask                     0.12.2           py36h98b5e8f_0
flask-cors                3.0.3            py36h8a3855d_0
freetype                  2.8                  h51f8f2c_1
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py36h342a76c_0
glob2                     0.6              py36hdf76b57_0
greenlet                  0.4.12           py36ha00ad21_0
h5py                      2.7.1            py36he54a1c3_0
hdf5                      1.10.1               h98b8871_1
heapdict                  1.0.0            py36h21fa5f4_0
html5lib                  1.0.1            py36h047fa9f_0
hypothesis                3.38.5           py36h987501d_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.6              py36h148d497_1
imageio                   2.2.0            py36had6c2d2_0
imagesize                 0.7.1            py36he29f638_0
intel-openmp              2018.0.0             hd92c6cd_8
ipykernel                 4.7.0            py36h2f9c1c0_0
ipython                   6.2.1            py36h9cf0123_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.0.5            py36h6314756_0
isort                     4.2.15           py36h6198cc5_0
itsdangerous              0.24             py36hb6c5a24_1
jdcal                     1.3              py36h64a5255_0
jedi                      0.11.0                   py36_2
jinja2                    2.10             py36h292fed1_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0            py36h422fd7e_2
jupyter_client            5.1.0            py36h9902a9a_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.30.6           py36h047fa9f_0
jupyterlab_launcher       0.6.0                    py36_0
lazy-object-proxy         1.3.1            py36hd1c21d2_0
libiconv                  1.15                 h1df5818_7
libpng                    1.6.32               h140d38e_4
libssh2                   1.8.0                h75d9407_3
libtiff                   4.0.9                h0f13578_0
libxml2                   2.9.4                h41ea7b2_6
libxslt                   1.1.29               h0037b19_6
llvmlite                  0.21.0           py36he0b0552_0
locket                    0.2.0            py36hfed976d_1
lockfile                  0.12.2           py36h0468280_0
lxml                      4.1.1            py36he0adb16_0
lzo                       2.10                 h6df0209_2
markupsafe                1.0              py36h0e26971_1
matplotlib                2.1.1            py36h2062329_0
mccabe                    0.6.1            py36hb41005a_1
menuinst                  1.4.10           py36h42196fb_0
mistune                   0.8.1            py36h007b88b_0
mkl                       2018.0.1             h2108138_4
mkl-service               1.1.2            py36h57e144c_4
mpmath                    1.0.0            py36hacc8adf_2
msgpack-python            0.4.8            py36h58b1e9d_0
multipledispatch          0.4.9            py36he44c36e_0
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.3.1            py36h8dc0fde_0
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  1.11             py36hdf4b0f5_0
nltk                      3.2.5            py36h76d52bb_0
nose                      1.3.7            py36h1c3779e_2
notebook                  5.2.2            py36hc48260a_0
numba                     0.36.2          np113py36h0128aa7_0
numexpr                   2.6.4            py36h30784b8_0
numpy                     1.13.3           py36ha320f96_0
numpydoc                  0.7.0            py36ha25429e_0
odo                       0.5.1            py36h7560279_0
olefile                   0.44             py36h0a7bdd2_0
openpyxl                  2.4.9            py36h6c6577a_0
openssl                   1.0.2n               h74b6da3_0
packaging                 16.8             py36ha0986f6_1
pandas                    0.22.0           py36h6538335_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36h3ef6317_1
parso                     0.1.1            py36hae3edee_0
partd                     0.3.8            py36hc8e763b_0
path.py                   10.5             py36h2b94a8f_0
pathlib2                  2.3.0            py36h7bfb78b_0
patsy                     0.4.1            py36h42cefec_0
pep8                      1.7.0            py36h0f3d67a_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    4.3.0            py36ha40f157_1
pip                       9.0.1            py36h226ae91_4
pkginfo                   1.4.1            py36hb0f9cfa_1
pluggy                    0.6.0            py36hc7daf1e_0
ply                       3.10             py36h1211beb_0
progress                  1.3              py36hbeca8d3_0
prompt_toolkit            1.0.15           py36h60b8f86_0
psutil                    5.4.1            py36h257d382_0
py                        1.5.2            py36hbcfbabc_0
pycodestyle               2.3.1            py36h7cc55cd_0
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pycrypto                  2.6.1            py36he68e6e2_1
pycurl                    7.43.0           py36h086bf4c_3
pyflakes                  1.6.0            py36h0b975d6_0
pygments                  2.2.0            py36hb010967_0
pylint                    1.7.4            py36ha4e6ded_0
pympler                   0.5              py36h863af32_0
pyodbc                    4.0.21           py36h82c9817_0
pyopenssl                 17.5.0           py36h5b7d817_0
pyparsing                 2.2.0            py36h785a196_1
pyqt                      5.6.0            py36hb5ed885_5
pysocks                   1.6.7            py36h698d350_1
pytables                  3.4.2            py36h71138e3_2
pytest                    3.3.0            py36hf3522a2_0
python                    3.6.3                h3b118a2_4
python-dateutil           2.6.1            py36h509ddcb_1
pytz                      2017.3           py36h1d3fa6b_0
pywavelets                0.5.2            py36hc649158_0
pywin32                   221              py36h9c10281_0
pyyaml                    3.12             py36h1d1928f_1
pyzmq                     16.0.3           py36he714bf5_0
qt                        5.6.2           vc14h6f8c307_12  [vc14]
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.3.1            py36hb8717c5_0
requests                  2.18.4           py36h4371aae_1
rope                      0.10.7           py36had63a69_0
ruamel_yaml               0.11.14          py36h9b16331_2
scikit-image              0.13.1           py36h2813840_0
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
seaborn                   0.8.1            py36h9b69545_0
setuptools                36.5.0           py36h65f9e6e_0
simplegeneric             0.8.1            py36heab741f_0
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h9c25514_2
six                       1.11.0           py36h4db2310_1
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         0.5.3            py36hbefa0ab_0
sortedcontainers          1.5.7            py36ha90ac20_0
sphinx                    1.6.3            py36h9bb690b_0
sphinxcontrib             1.0              py36hbbac3d2_1
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1
spyder                    3.2.5                    py36_0
sqlalchemy                1.1.13           py36h5948d12_0
sqlite                    3.20.1               h9eeafa9_2
statsmodels               0.8.0            py36h6189b4c_0
sympy                     1.1.1            py36h96708e0_0
tblib                     1.3.2            py36h30f5020_0
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.7                hcb92d03_3
toolz                     0.8.2            py36he152a52_0
tornado                   4.5.2            py36h57f6048_0
traitlets                 4.3.2            py36h096827d_0
typing                    3.6.2            py36hb035bda_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.22             py36h276f60a_0
vc                        14                   h2379b0c_2
vs2015_runtime            14.0.25123           hd4c4e62_2
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1            py36h67c50ae_1
werkzeug                  0.12.2           py36h866a736_0
wheel                     0.30.0           py36h6c3ec14_1
widgetsnbextension        3.0.8            py36h933dd4f_0
win_inet_pton             1.0.1            py36he67d7fd_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36he5f5981_0
xlrd                      1.1.0            py36h1cb58dc_1
xlsxwriter                1.0.2            py36hf723b7d_0
xlwings                   0.11.4           py36hd3cf94d_0
xlwt                      1.3.0            py36h1a4751e_0
yaml                      0.1.7                hc54c509_2
zict                      0.1.3            py36h2d8e73e_0
zlib                      1.2.11               h8395fce_2
zope                      1.0                      py36_0
zope.interface            4.4.3            py36h56cab3c_0
```

**Comment by CAM-Gerlach** [comment]
Thanks so much for your quick and detailed response. That is really strange indeed, well beyond my immediate pay grade to solve. It seems something in the Spyder startup procedure between the Loading Editor debug message and loading the ``rope`` introspection plugin is getting stuck in a loop or something and not timing out. It seems like it could be a Qt issue, maybe? Though that warning seems like a red herring... 

Also, note that ``qtconsole`` runs Spyder's console, and so it not loading isn't entirely conclusive that its something more fundamental with your platform—it is even possible the problem could lie with ``qtconsole`` in some way. Therefore, can you try other Anaconda applications, like Jupyter notebook, jupyterlab, IDLE, etc? Does IPython work normally and can you load modules from the Anaconda prompt?

**Comment by avi-deka** [comment]
Ok, I checked the other applications of Anaconda. All of them seem to work fine, except Spyder. IPython also works normally, and there was no problem loading modules from the Anaconda prompt.
I have been using Spyder for the past year, and it was working fine until October. I did not use Spyder for a couple of months since then, and now I am facing this problem.

**Comment by CAM-Gerlach** [comment]
Thanks again for following up, and really sorry you're still having issues. I'm honestly baffled at this one, and I'm almost out of the standard toolbox of troubleshooting fixes, and there appears to be no particular indication what's going on. A few other things to try, just in case: Try running Spyder as admin (through the shortcut or an elevated anaconda prompt); make sure you have no Spyder plugins installed, no spaces, special/non-ASCII characters, or funky permissions on your user/home and Anaconda directory path, try installing just Spyder into a new, fresh Python 3 Anaconda environment and starting it from the command line and Anaconda Navigator with that environment activated, and if you've installed for just you, try installing for all users or vice versa, and make sure Anaconda is installed to the default location for that. Also, any significant system configuration changes between when it worked and when it didn't?

With regard to narrowing down what's actually going on—to confirm, you tried the advanced startup troubleshooting procedure discussed in the comments to issue #6023 , running ``start.py`` and ``mainwindow.py`` (with ``set SPYDER_DEBUG=3`` beforehand for extra info)? If there's anything there that's unclear, I can post a more detailed guide; if anything will reveal what's going on, that will. Other than that, the only real way I can immediatly think of to debug it further would be dig into the ``mainwindow.py`` file and put ``print()``/debug statements or something at regular intervals between the last debug message you see (``Loading editor...``) and the first you don't (usually ``Introspection Plugin Loaded: rope``), to narrow down more precisely where the hang is occurring.

**Comment by avi-deka** [comment]
Ok I'll try the different methods.
As for [#6023](https://github.com/spyder-ide/spyder/issues/6023), I did try the method, and it gave the same problem. After `Loading Editor...` shows up, Spyder stops responding. So, as you mentioned, I tried to dig into `mainwindow.py` to debug, but I could not find `Introspection Plugin Loaded: rope` in the code. Could this be a problem?

**Comment by CAM-Gerlach** [comment]
That debug print is actually in plugins/introspection/manager.py, I believe, in the ``__init__`` call of plugin manager. In turn, it is called by IntrospectionManager() which in turn is called in editor.py , which is called (can't remember exactly which object precisely) by MainWindow.py. So, the error is likely somewhere in the editor launch sequence, possibly between when the constructor is called in mainwindow.py, and the start of the launch of the editor plugins, inclusive. You could try print statements to narrow things down; clone a local copy from github to do that (make sure to run it first with ``python bootstrap.py`` from the``spyder`` directory you cloned to make sure the error still occurs in the first place.

**Comment by avi-deka** [comment]
Ok the problem got solved when I re-installed Anaconda, this time for "All Users". Couldn't figure out why the problem was occuring before, but now Spyder seems to work fine. Thanks a lot for your help!
I guess I'll close this issue and consider it solved.

**Comment by CAM-Gerlach** [comment]
Thanks! Sorry this was such an issue, and glad you got it working. Best of luck going forward!

**Comment by NafriaVijay** [comment]
Spyder3 is not launching in my window 10, not from command prompt not from spyder3.exe

**Comment by CAM-Gerlach** [comment]
@NafriaVijay Did you follow the advice in this thread, in #6023 (that issue sounds way more similar to yours than this one), and the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues? 

Its almost certainly a user install issue, probably with ``pip`` given your executable names, which we don't have the resources to provide individual support for, sorry. Best of luck.

**Comment by NafriaVijay** [comment]
Well as of now I am using Spyder for more then 2 year. It never gave me any trouble till today and it was working 2-3 days ago when I last used it... but no idea why it suddenly stopped working. I have installed Spyder and other python packages many times before never had any problem. Now after failing to launch from desktop shortcut I tried from command prompt as admin, the mouse arrow cursor show a circle and then nothing happened thereafter. Never seen such issue. I don't use anaconda since I use python for multiple purpose and use different IDEs for different needs so I don't want to install all the packages separately for anaconda.

**Comment by NafriaVijay** [comment]
Okay so I was reading in various blog posts that it has something to do with PYQT5 so I uninstalled it and any installed package from riverbank and also uninstalled Spyder. Then I reinstalled spyder3 and now its launching and running okay.

**Comment by CAM-Gerlach** [comment]
Glad you got it fixed!

**Comment by jayrawatrj** [comment]
i have tried all the things mentioned here but still spyder is not opening.. does any have the solution ????plzzz share

**Comment by NafriaVijay** [comment]
Hi jayrawatrj this problem came back again... it has to do something with QT5 and QT4. It happens anytime I have to update my python packages, no pun intended. You can solve it by uninstalling spyder and all the riverbank computing and reinstalling all of them but I am tired of doing this all the time. I switched to VSCode, I know we all are addicted of spyder but can't stop what we were doing and keep on fixing it all the time. Sorry guys at Spyder.

**Comment by NafriaVijay** [comment]
on the second thought..... couldn't help it ... spyder is so pleasing to eyes
just do 
pip install --upgrade pip
pip install --upgrade pyqt5

**Comment by CAM-Gerlach** [comment]
@NafriaVijay Basically, the problem seems to be that Spyder is installed in the environment as other packages that depend on Qt4 or other versions of Qt5, which is a recipe for problems no matter what you're trying to do and make things switch back and forth. 

Now that Spyder 3.3.0's out (and Spyder 3.3.1, due out very soon, will improve it further), we have a much easier and better way to handle this situation: just install Spyder in its own environment, and then install just the ``spyder-kernels`` package in whatever environment(s) you want to use Spyder with (this can be different Anaconda envs, virtualenvs/venvs, or even a totally different Python install) and just point Spyder to the Python interpreter of whatever environment you want to use (under ``Tools -> Preferences -> Python interpreter -> Use the following Python interpreter``). You can set this up via the following commands in the Anaconda prompt/Terminal/command line

```bash
conda create -n spyder-env python=3.6
activate spyder-env
conda install spyder
activate <your-main-env-here>
conda install spyder-kernels=0.*
```

and then you should be good to go, presuming you launch spyder from the ``spyder-env`` environment (via Anaconda navigator, or ``activate spyder-env`` then ``spyder`` from the command line).

If you'd like more detail about all this, I created [a new guide to managing packages and environments with Spyder](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder).

**Comment by NafriaVijay** [comment]
Thanks a lot for clearing it out man, keep up the good work ... however I don't use Anaconda environment, ... I use spyder as it is like any other IDEs. I recently installed some packages and they in turn upgraded some other and Voila my spyder stopped working.... Just know I upgraded my spyder but it didn't work... So finally I tried the ol' faithful method of upgrading pyqt5  and now its working back again ... Just love to share the experience

**Comment by CAM-Gerlach** [comment]
Glad I could help! 

You actually don't need Anaconda to use environments or ``spyder-kernels`` in this manner; you should be able to do it just as well with ``virtualenv``/``venv`` (which are generally strongly recommended for use anyway), or even with two different Python installs if you already have that (e.g. system Python and your scientific Python install). I only used it in the example since most of our users use it and it makes things a little easier/harder to break, as has happened here.

**Comment by Abeltzin** [comment]
I need help, whey i tried to launch Spyder 3.3.3 show an error:

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
objc[1427]: Class RunLoopModeTracker is implemented in both /anaconda3/lib/python3.6/site-packages/PyQt5/Qt/lib/QtCore.framework/Versions/5/QtCore (0x113156270) and /anaconda3/lib/libQt5Core.5.dylib (0x119cbd8b8). One of the two will be used. Which one is undefined.
Traceback (most recent call last):
File "/anaconda3/bin/spyder", line 11, in 
sys.exit(main())
File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 186, in main
from spyder.app import mainwindow
File "/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 90, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ValueError: PyCapsule_GetPointer called with incorrect name

Help please!!!

**Comment by CAM-Gerlach** [comment]
@Abeltzin This is totally unrelated to the issue reported here; if you'd read the original report above, there is nothing that even remotely resembles anything in the above traceback; in fact, no error traceback at all occurs with any of the issues discussed on this thread.

Something's probably wrong with your environment, or perhaps its something macOS-specific. Try ``conda install --force-reinstall sip pyqt qt`` after ``activate``-ing your Spyder environment in the Terminal (``conda activate base`` by default). If that doesn't fix it, please provide the output of ``conda --list`` in your Spyder environment inside a ``<details>`` code block; I edited your post above to show you how; if it doesn't look like the above when you preview/submit it, then you did ***not*** do it correctly). Thanks.

**Comment by Abeltzin** [comment]
Sorry for wrong thread @CAM-Gerlach,  it worked correctly now.
Thanks a lot for your help :)
