### ISSUE TITLE
Ipython kernel not loading although is installed

### ISSUE THREAD

**Issue by mayurpande** [spyder-ide/spyder#6119]
## Description of your problem

I have a virtual environment that has ipykernel install already, however suddenly it will not load.

I have tried to switching the python interepreter and this did nothing.

**What steps will reproduce the problem?**

1. 

**What is the expected output? What do you see instead?**

ipykernel loaded, however all I see is;

An error ocurred while starting the kernel
Your Python environment or installation doesn't have the ipykernel and cloudpickle modules installed on it. Without these modules is not possible for Spyder to create a console for you.

You can install them by running in a system terminal:

pip install ipykernel cloudpickle

or

conda install ipykernel cloudpickle

**Please provide any additional information below**

But requirement is always satisfied.

## Versions and main components

* Spyder Version: 3.2.5
* Python Version: 3
* Qt Version: 
* PyQt Version:
* Operating system: ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
Please read the message: since Spyder 3.2.5 you also need `cloudpickle` to be installed in your virtualenv.
