### ISSUE TITLE
Setting Pythonpath with a path string, not GUI

### ISSUE THREAD

**Issue by DSLituiev** [spyder-ide/spyder#6120]
## Description of your problem

**What steps will reproduce the problem?**

1. Go to menu "python"
2.  Click pythonpath manager
3. Click "add path"

**What is the expected output? What do you see instead?**

Ideally I would love to point to my earlier python repositories that are under `/usr/local/lib/python3.6/site-packages/`. However with GUI I can navigate to only limited number of places on computer.

Expected input:  Config file or input field for path string instead of "chose folder" GUI

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.5
* Python Version: 3.6.2
* Qt Version:
* PyQt Version:
* Operating system: MacOS 10.12.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Sorry, that's a macOS problem, not a Spyder one.

**Comment by CAM-Gerlach** [comment]
You can show hidden files and directories in the open dialog with <kbd>Command</kbd> + <kbd>Shift</kbd>+ <kbd>.</kbd> (period key). Also, you can just paste the full path to the directory right into the open dialog; the normal <kbd>Command</kbd> + <kbd>v</kbd> should automatically open the Go to Folder dialog and paste it in for you.

A text field for direct path entry wouldn't be a bad idea, but we really aren't able to implement it right now as [Spyder is currently unfunded](https://github.com/spyder-ide/spyder/wiki/Anaconda-stopped-funding-Spyder) (though you can [help](https://opencollective.com/spyder)). However, you are welcome to do so yourself and submit a PR for it to be included in the main Spyder repository, as Spyder is developed in Python just like your own code. Just [clone the repo](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md), and check out the [pathmanager.py](https://github.com/spyder-ide/spyder/blob/138b4157793e32943ea3a436df6d3264ece29f97/spyder/widgets/pathmanager.py) file as a starting point. Best of luck!

**Comment by DSLituiev** [comment]
What works here is `Cmd ⌘ + Shift + G` in the dialog
