### ISSUE TITLE
Spyder window re-focus constantly on itself

### ISSUE THREAD

**Issue by jhillairet** [spyder-ide/spyder#6128]
## Description

The following bug appeared after a `conda update --all`

**What steps will reproduce the problem?**

1. Launch Spyder from the start menu shortcut
2. The Spyder window keep re focus on itself : if I select an other software (like chrome), the user focus is immediately lost and goes back to Spyder windows. The Terminal panel also keeps blinking, like if it restart continuously 
3. Closing Spyder leads to crash the program

**What is the expected output? What do you see instead?**
Well, not that ;)

**Please provide any additional information below**

  File "C:\Users\JH218595\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 317, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\Users\JH218595\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 330, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by jhillairet** [comment]
When launched from the Anaconda Prompt, the bug disappeared. But the following message appears in the prompt : 
`(base) C:\Users\truc>spyder
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
`

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. As the error message states, this is a problem with the ``spyder-terminal`` plugin, and thus belongs on that repo. Also, it has been reported several times already; see issues [#123 ](https://github.com/spyder-ide/spyder-terminal/issues/123)and [#125](https://github.com/spyder-ide/spyder-terminal/issues/125) over on that repo, so you should comment there if you have more information to add. Therefore, this issue will be closed. Best of luck!

**Comment by jhillairet** [comment]
Great, thank you for the support. I've indeed removed the `spyder-terminal` package and its works fine now.

**Comment by CAM-Gerlach** [comment]
Glad you got it working!
