### ISSUE TITLE
Spyder encountered a problem after closing online help pane

### ISSUE THREAD

**Issue by emilmirzayev** [spyder-ide/spyder#6131]
I was working with Spyder and accidentally opened online help pane on the lefthand side. I searched for pandas package and saw that, search is taking too long. After, I closed the pane and continued working. Several seconds later, I got an error message saying that Spyder encountered a problem.

My Windows 10 is in German, but Anaconda, Spyder and everything else is in English.

**What steps will reproduce the problem?**

1. Opened Online help pane 
2.  Searched for pandas
3.  Clsoed the pane before it finished searching (took too long)

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

```
durch den Hostcomputer abgebrochen
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54571)
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54573)
----------------------------------------
```

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by goanpeca** [comment]
@dalthviz is this fixed by your work?

**Comment by ccordoba12** [comment]
Yep, should be fixed now.
