### ISSUE TITLE
Code completion not working

### ISSUE THREAD

**Issue by Mi5ke** [spyder-ide/spyder#6146]
## Description

**What steps will reproduce the problem?**

1. Install Spyder on Windows 7
2. Type some Python into the editor
3. Type partial name, press TAB or Ctrl-Space

**What is the expected output? What do you see instead?**
Expect code completion.
No code completion occurs, no pop-up, just nothing happens.

**Please provide any additional information below**
Tried installing rope, rope-py3k, restarted, no change.
Tried restarting, re-opening a fresh editor, no change.
Tried factory reset of preferences, no change.

Code completion does work in the IPython console, but not in the editor.

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by stonebig** [comment]
please remove "enum34", if ever it shows in your "pip list"

**Comment by Mi5ke** [comment]
Thanks, that fixed it!

**Comment by CAM-Gerlach** [comment]
Also, we generally aren't able to offer individual help for installation issues under ``pip``, due to the number of problems that typically occur, and recommend the Anaconda distribution instead, though you are welcome to get it working on your own.

**Comment by Zalaski** [comment]
For anyone who is still pretty much new to Python/pip (like myself), I ran the following line to remove enum34;

> pip uninstall enum34

My code completion now works in Spyder (currently using v3.2.5 with Python 3.6.3).

Thanks for the solution!
