### ISSUE TITLE
Variable Explorer does not display certain variables

### ISSUE THREAD

**Issue by Ethunxxx** [spyder-ide/spyder#6148]
## Description of your problem

**What steps will reproduce the problem?**

1. Open spyder 
2. Type in the terminal 'IS_P = 0'

**What is the expected output? What do you see instead?**
I expect to see the variable 'IS_P' with a value of 0 in the variable explorer. However, it is not displayed. Other variables such as 'ImS_P' as displayed properly, so I suspect it has to do with the chosen variable name.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.5
* Python Version: 3.6.4
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.21.1 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Please go to the cog menu on the right of the Variable Explorer and deselect the option called `Exclude all upper-case references`.
