### ISSUE TITLE
Spyder 3.2.5 Auto Complete and API help not working 

### ISSUE THREAD

**Issue by ameynandedkar** [spyder-ide/spyder#6156]
## Description

**What steps will reproduce the problem?**

1. Install Conda with Spyder 
2. Install tensorlow library for python
3. Opne Spyder, autocomplete and document help (Ctrl + I) is broken

**What is the expected output? What do you see instead?**
Auto complete to work

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Please run in a terminal

    pip uninstall enum

to fix this problem.

**Comment by ameynandedkar** [comment]
`[amey@localhost ~]$ pip uninstall enum
Cannot uninstall requirement enum, not installed
[amey@localhost ~]$ pip3 uninstall enum
Cannot uninstall requirement enum, not installed
`

**Comment by ccordoba12** [comment]
Sorry, it is

     pip uninstall enum34

**Comment by ameynandedkar** [comment]
Hey, thanks! That worked like a charm :)

**Comment by ppip3420** [comment]
Is there something special I need to do after `pip uninstall enum34`? I am not able to open spyder or anaconda navigator after that. 

```
ImportError: No module named enum
```

**Comment by bbatjargal** [comment]
thanks

**Comment by kavousanos** [comment]
Excellent mate, thank you so much!
Still relevant for Spyder 3.3

**Comment by sumanasri** [comment]
I do not have enum34 installed and still unable to get auto complete to work. Please help.

python -m pip uninstall enum34                        
Cannot uninstall requirement enum34, not installed
