### ISSUE TITLE
Just Clic on Search in File... 

### ISSUE THREAD

**Issue by JRelland** [spyder-ide/spyder#6157]
## Description

**What steps will reproduce the problem?**

1. Discovering Spyder.
2. Just clic on Search in the file Then Help Then Escape
3. Language : French

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Jose\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 2026, in revert
    editorstack.revert()
  File "C:\Users\Jose\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2118, in revert
    self.reload(index)
  File "C:\Users\Jose\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2084, in reload
    txt, finfo.encoding = encoding.read(finfo.filename)
  File "C:\Users\Jose\Anaconda3\lib\site-packages\spyder\utils\encoding.py", line 243, in read
    text, encoding = decode( open(filename, 'rb').read() )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Jose\\sanstitre0.py'

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
So are you trying to search for text in an untitled file?

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. Please re-open if you have more information to share, so we can fix the problem. Thanks.
