### ISSUE TITLE
Error on Maximize Current Pane

### ISSUE THREAD

**Issue by dataenthusiast** [spyder-ide/spyder#6169]
## Description

**What steps will reproduce the problem?**

1. Going to View > Maximize Current Pane
2. 
3. 

**What is the expected output? What do you see instead?**
No windows open/maximize, just get error (screenshots attached)

**Please provide any additional information below**

  File "C:\Users\jburkhow\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2264, in maximize_dockwidget
    self.last_plugin.dockwidget.toggleViewAction().setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'dockwidget'

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```
![image](https://user-images.githubusercontent.com/1016310/34678980-9b9520aa-f462-11e7-9446-0c1c56c94c3f.png)

![image](https://user-images.githubusercontent.com/1016310/34679000-a8ef41f4-f462-11e7-9908-2b5d5c9b52ff.png)

**Comment by ccordoba12** [comment]
What pane were you trying to maximize?
