### ISSUE TITLE
Find in Files options not saved to spyder.ini

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#6176]
## Description of your problem

I've discovered this bug while working on PR #6095  and decided not to fix it then since it was already quite big.

The [get_options](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L417) method of the [FindOptions](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L223) widget is used for two things:
- It is used to get the options when [find](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L863) is run. In this case, `all=False` and the options are defined [here](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L487).
- It is also used in the [closing_plugin](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/plugins/findinfiles.py#L157) method of the `FindInFiles` plugin for saving the options to the config file. In this case, `all=True` and the options are defined [here](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L473).

The problem is that there are safeguards within the `get_options` method to prevent the `find` method to be run if one of the parameters is not correct. However, these safeguards also prevent the find in files options to be saved to the config file when Spyder is closed.

**What steps will reproduce the problem?**

For example, the options won't be saved to the config file if the `Search pattern` line edit is empty:
1. Go in the `FindInFiles` plugin and add an external path to the `Search in` combobox.
2. Leave the `Search pattern` line edit empty and close Spyder.
3. Restart Spyder: the external path that was added in 1 does not appear in the list of the  `Search in` combobox.  It was not saved to the config file due to the safeguard [here](https://github.com/spyder-ide/spyder/blob/v3.2.5/spyder/widgets/findinfiles.py#L423).

**What is the expected output? What do you see instead?**

The safeguards should not prevent the Find in Files parameters to be saved to the config  file

## Versions and main components

Spyder 3.2.6.dev0, Python 3.6.4 64bits, Qt 5.9.2, PyQt5 5.9.1 on Windows 7

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
So do you plan to fix this one first before merging #6095?

**Comment by ccordoba12** [comment]
Or do you need me to merge first that PR?

**Comment by jnsebgosselin** [comment]
Yes, I will fix this one once PR #6095 is merged.
