### ISSUE TITLE
PyQt5 is not available from wheel on ARM platforms

### ISSUE THREAD

**Issue by mvillion** [spyder-ide/spyder#6178]
Hello,

The PyQt5 dependency added since 3.2.5 breaks installation on ARM platforms.
Same issue on **Odroid XU4** and **Rapsberry Pi**:

>> sudo pip3 install spyder -U
[...]
        Collecting pyqt5; python_version >= "3" (from spyder)
        Could not find a version that satisfies the requirement pyqt5; python_version >= "3" (from spyder) (from versions: )
        No matching distribution found for pyqt5; python_version >= "3" (from spyder)

A workaround may be:

>> sudo pip3 install rope nbconvert pylint psutil pyopengl chardet qtpy sphinx pyzmq jedi cloudpickle -U
>> sudo pip3 install spyder -U --no-deps

**Comment by ccordoba12** [comment]
How do you run Spyder then?

**Comment by mvillion** [comment]
On ARM devices, it is very difficult to compile a complete PyQt5 library due to memory limitations (especially PyQt5.QtWebkit).
Hopefully, distribution like raspbian stretch offer packages like:
sudo apt install python3-pyqt5 python3-pyqt5.qtwebkit

It works on Rapsberry Pi 3 with:
Python 3.5.3 32bits, Qt 5.7.1, PyQt5 5.7 on Linux

**Comment by ccordoba12** [comment]
We don't have time to deal with this, sorry. Glad you found a workaround.
