### ISSUE TITLE
Code competion window too small on high resolution screens

### ISSUE THREAD

**Issue by hsauro** [spyder-ide/spyder#6181]
## Description of your problem
I have a new laptop with a resolution of 2560 x 1440 running the latest Windows10. However I have found that the code competion window in the spyder editor is too small.  This is indepdnent of the font size used in the editor. See enclosed image. 

![codecompletion](https://user-images.githubusercontent.com/1054990/34748546-f0408c6c-f551-11e7-92a4-ca49b8896c83.png)
**What steps will reproduce the problem?**

1. Launch spyder in high res screen.
2. Import numpy as np
3. Type np. and hit tab to bring up code competion window in editor

**What is the expected output? What do you see instead?**
Output should be a bigger code competion window.

**Please provide any additional information below**
I migth be useful to have preference options to change the size of the code competion window.

## Versions and main components
Spyder 3.2.3 on latest Windows 10
* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0;<6.0:  5.5.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.11.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this in 3.2.7

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one. The widget should have a minimal size and it should expand according to font size.

**Comment by dalthviz** [comment]
Just checking, @hsauro do you enabled the auto high DPI scaling?:

![imagen](https://user-images.githubusercontent.com/16781833/40944295-e021469c-6819-11e8-8ffd-138bd8e1987f.png)

**Comment by goanpeca** [comment]
This is still a problem as the completion widget is not growing. 

See:

<img width="1126" alt="Screen Shot 2019-11-27 at 20 08 34" src="https://user-images.githubusercontent.com/3627835/69769174-c72f2400-1151-11ea-85ea-773c0ec8089b.png">

**Comment by goanpeca** [comment]
This should be a simple fix, so I added it to 4.1

**Comment by dalthviz** [comment]
Note: https://forum.qt.io/topic/69978/scaling-widget-according-to-screen-scaling-ratio-in-os/12

**Comment by Thinking2018** [comment]
I am also facing this problem. When I updated spyder from 3.3 to 4.0, the autocompletion window size is too small. It will not change when I change the font size. The high DPI setting will not solve this issue either.

<img width="608" alt="微信截图_20200107132302" src="https://user-images.githubusercontent.com/42349201/71870511-26b92000-3151-11ea-9517-1a39a9e24daa.png">

**Comment by hippie68** [comment]
The box itself is still a little small. Can you add an option to resize it using the mouse cursor? On my machine (Debian Bookworm, Spyder 5.4.2) not even the word "function" completely fits in the screen.

![spyder_autocomplete_box](https://github.com/spyder-ide/spyder/assets/65259318/d2526510-4050-4a98-8b5a-8ea8c024b0d4)

A drag resize option that remembers the size would fix these issues once and for all.
