### ISSUE TITLE
Spyder doesnt recognize dependencies

### ISSUE THREAD

**Issue by muuky** [spyder-ide/spyder#6183]
## Description

**What steps will reproduce the problem?**

1.  Spyder was crashed when i was doing PYTHONPATH manager
2.  After crash i re-open Spyder using ANACONDA navigator
3.  But after re-open  Spyder there was error message " You have missing dependencies!"

**What is the expected output? What do you see instead?**
Just normal working Spyder without any error message

**Please provide any additional information below**
![anaconda](https://user-images.githubusercontent.com/34735152/34758507-238ca830-f61a-11e7-823e-c9314404036c.PNG)
![c location](https://user-images.githubusercontent.com/34735152/34758508-23b501a4-f61a-11e7-831d-45cd374fefc7.PNG)
![cmmand pormpt install](https://user-images.githubusercontent.com/34735152/34758509-23f4e120-f61a-11e7-82a1-94a080267b33.PNG)
![command prompt](https://user-images.githubusercontent.com/34735152/34758510-241c95a8-f61a-11e7-9075-814f5630f230.PNG)
![spyder error](https://user-images.githubusercontent.com/34735152/34758511-2441dd68-f61a-11e7-8cad-f335033a5fd5.PNG)

error message said there is no "nbconvert" module but "nbconvert" module is already installed
and even i can import "nbconvert" module in Ipython
error message pops up every time when i open Spyder
i already tried reinstall/upgrade Spyder but same issue
before crash Spyder works fine without any error message.

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 2.7.14
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.10.4 on Windows

## Dependencies
```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  None (NOK)
numpy >=1.7       :  1.11.2 (OK)
pandas >=0.13.1   :  None (NOK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  None (NOK)

```

**Comment by ccordoba12** [comment]
Please run

    import sys
    sys.executable

in Spyder's IPython console and report what you get from that.

**Comment by muuky** [comment]
'C:\\Users\\Muuky\\Anaconda3\\envs\\python2\\pythonw.exe'

**Comment by CAM-Gerlach** [comment]
Barring more specific advice, can you try the steps listed in our [Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections?

**Comment by muuky** [comment]
oh i didnt know there is Trobleshooting Guide.
error doesnt pop up after run the command `spyder --reset`

**Comment by CAM-Gerlach** [comment]
We actually just created it, and plan to make it much more visible in the next release (3.2.7), along with improvements to the documentation and error reporting system, among other fixes. Glad you got it fixed!

**Comment by dstanner** [comment]
I am now having this problem. 

spyder v 3.3.3
python v 3.7.2
conda v 4.6.8

Error message:
![Capture](https://user-images.githubusercontent.com/34904658/54234608-ad1eba00-44cc-11e9-9cfb-84d8009b235f.JPG)

`nbconvert` is indeed installed (v. 

What I have tried (and failed)... various permutations of:
- `conda update conda`
- `conda update --all`
- `conda clean --all`
- removing spyder and nbconvert and then reinstalling them with conda
- uninstalling my conda environment, creating a new environment and intalling all relevant packages with `conda install`
- rebooting my computer
- `spyder --reset`

The error persists even when creating a new environment, restarting my computer, pulling packages from conda, restarting my computer again, cleaning conda leftovers, restarting my computer again, updating packages, restarting my computer, cleaning conda again, restarting my computer again, and then launching spyder.

I looked through the troubleshooting guide linked above and I feel like I've exhausted the general options (with the exception of totally wiping anaconda from my computer and starting 100% from scratch).

Any advice would be helpful.

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed error report and trying so many steps before asking us, @muuky , and sorry you're still seeing the issue. Other than a full reinstall, I'm not quite sure what else to try. However, as the message states, Spyder should still work fine; the only thing that *might* missing will be the ability to import Jupyter notebooks.

For completeness, what is your OS version? Your ``Python Interpreter`` settings under Spyder's Preferences? The result of ``import nbconvert`` in the IPython console? The result of

```python
import sys
sys.executable
```

in the console? Thanks.

**Comment by dstanner** [comment]
Thanks!  I'm in Windows 10.

`Python Interpreter` is "Default (i.e., the same as Spyder's).

running `import nbconvert` doesn't return anything to the console, so I'm presuming that means it works just fine (no errors thrown).

`sys.executable` returns: `'C:\\Users\\datanner\\AppData\\Local\\Continuum\\Anaconda3\\envs\\companalytics\\pythonw.exe'`

I should say that this error started after I updated from python 3.6 to 3.7, and all of the dependencies updated. 

And now running `conda update --all` gives the following warning:

```
Warning: 2 possible package resolutions (only showing differing packages):
- defaults::nbconvert-5.4.1-py37_0, defaults::pandoc-1.19.2.1-hb2460c7_1
- defaults::nbconvert-5.3.1-py37_0, defaults::pandoc-2.2.3.2done             
```

Then running conda update alternately either upgrades nbconvert and downgrades pandoc, or upgrades pandoc and downgrades nbconvert.

All new behavior today.

**Comment by hagaishalev** [comment]
I solved the same issue on Windows 10 with
`    conda install nbconvert=5.4.1`
