### ISSUE TITLE
Working Directory Not Changing to Current Directory Automatically

### ISSUE THREAD

**Issue by tpradeep** [spyder-ide/spyder#6184]
## Description of your problem

**What steps will reproduce the problem?**

1. Current working directory doesn't change based on current file being executed
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
Found in many python versions

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 2.7.14
* Qt Version: 5.6.2
* PyQt Version: 5.6.0
* Operating system: Red Hat Enterprise Linux Server release 6.8 (Santiago)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0;<6.0: 5.4.1 (OK)
cython >=0.21 : None (NOK)
jedi >=0.9.0 : 0.11.0 (OK)
nbconvert >=4.0 : 5.3.1 (OK)
numpy >=1.7 : 1.13.3 (OK)
pandas >=0.13.1 : 0.22.0 (OK)
psutil >=0.3 : 5.4.1 (OK)
pycodestyle >=2.3 : 2.3.1 (OK)
pyflakes >=0.5.0 : 1.6.0 (OK)
pygments >=2.0 : 2.2.0 (OK)
pylint >=0.25 : 1.7.4 (OK)
qtconsole >=4.2.0 : 4.3.1 (OK)
rope >=0.9.4 : 0.10.7 (OK)
sphinx >=0.6.6 : 1.6.3 (OK)
sympy >=0.7.3 : None (NOK)

**Comment by tpradeep** [comment]
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.11.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
psutil >=0.3      :  5.4.1 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
This is working fine for me. If that's not working for you, please go to

    Run > Configuration per file > Working directory settings

or

    Tools > Preferences > Run > Working directory settings

to select the right option.
