### ISSUE TITLE
CRASH on laptops with two graphics cards

### ISSUE THREAD

**Issue by chengtian5huang** [spyder-ide/spyder#6186]
## this issue is solved but i think should tell u guys

**What steps will reproduce the problem?**

1. get a laptop with two gpu: one is the ```intel gpu``` imbeded with CORE i3/i5/i7 cpu; one is the nvidia gpu such as ```gtx970m```/```gtxM1050```. for example:
![default](https://user-images.githubusercontent.com/34744187/34762534-19f2e75e-f623-11e7-8b2c-f38a073149bf.PNG)
2. start spyder3 on this laptop.

**What is the expected output? What do you see instead?**
of course i expect it can run normally.
BUT it acts as following:
1. after the "ipython console panel" is loaded spyder3 crashs: the editor (where we type code) and the console panel (wher we read outputs) are dead(no reaction, cursor stops blink)
2.although these two are dead the toppest bar (''file edit search.....help'') is still action, i can click them and they react.
![spydertopbar](https://user-images.githubusercontent.com/34744187/34762559-2530039a-f623-11e7-8c0d-d738b8cf3348.PNG)

# Here comes the solution
***solution1***:
disable the nvidia gpu in Windows Device Manager, spyder3 can run as expected.
***solution2***
update the driver version of intel gpu from 23.20.16.4877(or older) to 4901, spyder3 can run as expected without disable the nvidia gpu.

**Additonal info**
* when spyder3 crashs, nvidia software told me that ```pythonw.exe``` is using the nvidia gpu.
* ***on another laptop(intel gpu:hd630+nvidia gpu:gtxM1050)***
i installed python 3.6.4,pip,spyder3(and its dependencies) and nothing else, spyder3 crashed just the same way the other laptop did. with solution1 , spyder3 can run fine. when i try solution2,i cant update the driver version of intel gpu which is 23.20.16.4877.
* close the ```ipython console panel``` , then next start will be alright 

## Versions and main components

* Spyder Version:3.2.6(both laptop)
* Python Version: 3.6.4(both laptop)
* Qt Version: dont remember
* PyQt Version: dont remember
* Operating system: win10

## Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
> solution1:
disable the nvidia gpu in Windows Device Manager, spyder3 can run as expected.
solution2
update the driver version of intel gpu from 23.20.16.4877(or older) to 4901, spyder3 can run as expected without disable the nvidia gpu.

It seems you already figured out the right solutions. Unfortunately, there's nothing we can do in Spyder to help people with this problem, sorry.
