### ISSUE TITLE
UnicodeEncodeError when searching text in the Editor

### ISSUE THREAD

**Issue by master-nemo** [spyder-ide/spyder#6187]
## Description
after update to 3.2.6 when trying to search text in file (ctrl+f) then start typing it display error message with invite to send this issue report

**What steps will reproduce the problem?**

0.  Russian interface
1. ctrl+f
2. start typing text to search 
(it continue to appear UPD when text found))

**What is the expected output? What do you see instead?**
expected normal usual context search. error message instead

UPD:
--reset  and --defaults cant't help with that
change interface to English (was Russian) fixed error. so i suppose it some mistakes in translation file or something in utf8 of some strings

**Please provide any additional information below**

  File "f:\dev\python27\lib\site-packages\spyder\widgets\findreplace.py", line 365, in text_has_been_edited
    self.find(changed=True, forward=True, start_highlight_timer=True)
  File "f:\dev\python27\lib\site-packages\spyder\widgets\findreplace.py", line 441, in find
    total_matches=number_matches)
  File "f:\dev\python27\lib\site-packages\spyder\widgets\findreplace.py", line 575, in change_number_matches
    total_matches)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.9
* Qt Versions: 4.8.6, PyQt4 (API v2) 4.11.3 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.1 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this in 3.2.7.
