### ISSUE TITLE
Icon should be moved from share/pixmaps to share/icons

### ISSUE THREAD

**Issue by Ganondolf** [spyder-ide/spyder#6188]
While /usr/share/pixmaps is in the icon path, ~/.local/share/pixmaps is not, so local installs (e.g. by pip install spyder3 --user) have no icon for the menu item. Moreover the spyder icon is a .png, not a .xpm, and the pixmap format (and location) is supported but (afaiu) deprecated.

I'm using spyder 3.2.6 with python 3.5.2 on Linux Mint 18.3

**Comment by ccordoba12** [comment]
Thanks for reporting, we'll fix this in 3.2.7.
