### ISSUE TITLE
Crash when dragging and dropping python file into spyder

### ISSUE THREAD

**Issue by nurnbeck** [spyder-ide/spyder#6196]
## Description

**What steps will reproduce the problem?**

1. drag and drop a python program into spyder

**What is the expected output? What do you see instead?**
instantly gave me a report error message, did not open program in spyder

1. 

**Please provide any additional information below**

  File "/usr/lib/python3.6/site-packages/spyder/widgets/editor.py", line 2250, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by ccordoba12** [comment]
This was fixed in our 3.2.5 version, please update.
