### ISSUE TITLE
Spyder won't launch from Python(x,y) console or desktop shortcut

### ISSUE THREAD

**Issue by jonathank98** [spyder-ide/spyder#6197]
## Description of your problem

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version:(2.3.9)
* Python Version:(2.3.9)
* Qt Version:
* PyQt Version:
* Operating system: Windows 10
![spyder_issue](https://user-images.githubusercontent.com/10983407/34852753-1f8c4940-f6e5-11e7-8370-cda105b6628b.JPG)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
That Spyder of Spyder is more than 3 years old and we don't support it anymore, sorry.
