### ISSUE TITLE
Unable to display `altair` visualisations on spyder 3.2.5

### ISSUE THREAD

**Issue by shivendra90** [spyder-ide/spyder#6200]
## Description

**What steps will reproduce the problem?**

1.  Import `altair` library as alt.
2. Use any example or own example to define the `altair` chart (for ex. [https://altair-viz.github.io/documentation/displaying.html](url)
3. Display the chart.

**What is the expected output? What do you see instead?**
There is no output but some white space between the executed line and the running line suggesting that there is either a missing dependency or spyder's inability to display the chart.

**Please provide any additional information below**
I've provided a screenshot below to make things clearer. It can be seen that when I define `chart` and execute it, there is no output at all. When I move the cursor to that blank space, it becomes smaller is size that tells me that the output is there but has not displayed fully.

**Edit:** Updated Spyder to 3.2.6 and still no output for `altair` chart.

![spyder_issue](https://user-images.githubusercontent.com/9760865/34872276-5e9ef14c-f7b6-11e7-8618-d90ed3ca6ec6.png)

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
Spyder can't display HTML/JS content on its consoles, and that's what Altair is trying to do, sorry.

**Comment by djouallah** [comment]
can we add this, altair is becoming the new standard interactive chart in python
