### ISSUE TITLE
Bug with saved window layouts

### ISSUE THREAD

**Issue by dacyr** [spyder-ide/spyder#6202]
## Description

**What steps will reproduce the problem?**

1. Saved a window layout as just the text editor named Editor.  No ipython, variable explorer, file explorer, or help.
2. Opened default spyder window layout.
3. Selected Editor window layout.

**What is the expected output? What do you see instead?**
Expected Editor window layout.  Spyder crashed instead.

**Please provide any additional information below**

  File "/home/damian/opt/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1783, in <lambda>
    return lambda: self.quick_layout_switch(i)
  File "/home/damian/opt/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1903, in quick_layout_switch
    self.setup_default_layouts(index, settings)
  File "/home/damian/opt/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 1616, in setup_default_layouts
    layout = layouts[index]
KeyError: 4

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting, we'll fix this in a future release.

**Comment by CAM-Gerlach** [comment]
Also, seems to have been reported before as #5858 but this appears to be a clear way to reproduce it.

**Comment by csabella** [comment]
I'm glad there were some old issues with this; otherwise, I would have thought it was related to #6153.  Since I've been in layouts recently, I'll take a look, but so far I haven't been able to recreate it.  I know what needs to happen for the error to occur, but I just can't figure out the sequence of events for making that happen.
