### ISSUE TITLE
spyder-terminal caused problem. 

### ISSUE THREAD

**Issue by haydarcelik** [spyder-ide/spyder#6223]
## Description

I installed spyder-terminal but it didn't work. When I tried to close the terminal inside the spyder, it caused error.

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 317, in <lambda>
    term.terminal_closed.connect(lambda: self.close_term(term=term))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 330, in close_term
    term.close()
AttributeError: 'NoneType' object has no attribute 'close'

## Version and main components

* Spyder Version: 3.2.5 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. As the error message states, this is a problem with the ``spyder-terminal`` plugin, and thus belongs on that repo. It has been reported both here and there several times already; see issues [#123 ](https://github.com/spyder-ide/spyder-terminal/issues/123)and [#125](https://github.com/spyder-ide/spyder-terminal/issues/125) over on that repo, so you should comment there if you have more information to add. Therefore, this issue will be closed. Best of luck!

**Comment by haydarcelik** [comment]
Thank you for the update.
