### ISSUE TITLE
Problem for reading netcdf file via OpenDAP with netCDF4 library

### ISSUE THREAD

**Issue by jhlasheras** [spyder-ide/spyder#6233]
## Description of your problem
No able to read a netcdf file via opendap in spyder using the netCDF4 library. 
Recibing **OSError: NetCDF: Invalid argument**
When using jupyter notebook or ipython i am able to read the file perfectly. I have checked the version of ipython and of netCDF4 been used and apparently is the same.
 
**What steps will reproduce the problem?**

1. import netCDF4
2. ds = netCDF4.Dataset('http://thredds.socib.es/thredds/dodsC/hf_radar/hf_radar_ibiza-scb_codarssproc001/L1/2016/dep0001_hf-radar-ibiza_scb-codarssproc001_L1_2016-02.nc')

## Versions and main components

* Spyder Version:  3.2.6
* Python Version:  3.6.0
* netCDF4 Version: 1.2.4
* ipython Version:  5.1.0

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I'm running Spyder 3.2.6, Python 3.6.4 x64, netCDF 1.3.1, IPython 6.2.1 and Qt/PyQt 5.6(.2) on Windows 8.1 Pro x64 and it worked fine, importing and loading the dataset with no warnings or errors, and viewing it in the Console (though apparently it is not supported in the Variable Explorer, giving the error ``EOFerror: Ran out of input`` when trying to read it from the console). Can you try using the above versions (and inform us as to your OS and version) and report your results? Also, are you able to provide a full traceback for the error? Can you try it with ``qtconsole`` just for completeness (launched with e.g. ``jupyter qtconsole``)?

**Comment by jhlasheras** [comment]
I have updated all to the versions you were saying. I still have recive an error:

OSError: [Errno -36] NetCDF: Invalid argument: b'http://thredds.socib.es/thredds/dodsC/hf_radar/hf_radar_ibiza-scb_codarssproc001/L1/2016/dep0001_hf-radar-ibiza_scb-codarssproc001_L1_2016-02.nc'

Using qtconsole and other python interpreters (ipython,idle,jupyter) I have no problem

**Comment by CAM-Gerlach** [comment]
To trace the error further, you can enclose your code in a try/except loop, then pull the traceback from the exception with the ``__traceback__`` attribute. Also, you can enable the postmortem debugger with ``pdb`` from the Console and see if that allows you to glean any insight onto what is occurring, like e.g. some weird interaction with ``OpenDAP`` or something. Also, did you install Spyder and ``netCDF`` via Anaconda or another method?

> Found out that when loading other libraries and afterwards trying to load the netcdf file, the same error occurs.

Sorry, I'm not sure I understand what you mean by this. Could you try explaining it a different way?

> Just happen for openDAP files. A local netcdf file can be read without problems.

Perhaps it is your system firewall, or other security software you may be running affecting Spyder differently, then? Could you try disabling any of that you have and repeating the test? 

> The bug apparently replies for other computers

Huh? Do you mean you were able to replicate it, or are you describing the behavior somehow?

**Comment by CAM-Gerlach** [comment]
Any updates, @jhlasheras ? If we don't hear from you after a few more days, this issue will end up getting closed. Thanks!

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. Please comment and reopen if you can provide the requested information; thanks!

**Comment by jhlasheras** [comment]
I found the problem may be due to the **matplotlib backend.**
When initializing  with **Tk backend** the problem dissaspears.
For spyder **start_kernel.py** needs to be changed in order to force spyder to use Kt backend as default

Adding this at the begining of the script solves the problem in other ipython interpreters:

import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

**Comment by ccordoba12** [comment]
@jhlasheras, please use our Preferences system to achieve that:

    Preferences > IPython console > Graphics > Backend
