### ISSUE TITLE
Color scheme changes after kernel restart

### ISSUE THREAD

**Issue by amccaugh** [spyder-ide/spyder#6235]
## Description

The color scheme shown in the console window changes after you restart the kernel

**What steps will reproduce the problem?**

1. Open a new IPython console
2. Cause an error (run an undefined function "prin")
3. Observe the color scheme -- as expected
4. Restart that console's kernel (I used ctrl-.)
2. Cause an error (run an undefined function "prin")
3. Observe the color scheme -- has now changed to very bright colors

![2018-01-17_12-11-18](https://user-images.githubusercontent.com/2075083/35061968-0760b4d8-fb80-11e7-9662-b36825e47e59.gif)

## Versions and main components

* Spyder Version: 3.2.6
* Python Version:  3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by csabella** [comment]
Confirmed this is happening on Windows 7, but it is not happening on Ubuntu.

**Comment by ccordoba12** [comment]
@csabella, do you have time to take a look at this one?

**Comment by csabella** [comment]
@ccordoba12   I started taking a look at this, but it's a mystery so far.  There are two places in the Spyder code where `%colors` is invoked, but using `debug_print` on Ubuntu, those methods aren't called during a kernel reset.  I need to check debug_print on Windows, but I'm also thinking that this may be happening in qtconsole and not Spyder.  I need to do some more digging.

**Comment by csabella** [comment]
I believe this was caused by IPython pull requests 10260 (https://github.com/ipython/ipython/pull/10260), 10281, and 9838, but I can't install a version before 5.3.0 to check it out.  Probably the best thing for Spyder to do would be to call the overrides of the %colors on a restart.

**Comment by ccordoba12** [comment]
> Probably the best thing for Spyder to do would be to call the overrides of the %colors on a restart.

What do you mean by that?

**Comment by csabella** [comment]
> What do you mean by that?

I apologize; I've been looking at `debug_print` so much that I knew what I meant.  :-) 

In the IPython console, in `client.py`, there is a method called `configure_shellwidget` with the following:
```
        if not create_qss_style(self.shellwidget.syntax_style)[1]:
            self.shellwidget.silent_execute("%colors linux")
        else:
            self.shellwidget.silent_execute("%colors lightbg")
```

When a Spyder is first opened or when a new console is created, this code is called.  However, it is not called on a restart of the kernel.  It would seem that the IPython defaults take over and change the color settings in the console.  So I was thinking that maybe we need to execute this on a restart.

**Comment by ccordoba12** [comment]
Ok, good call! Could you open a PR with that insight? Thanks!
