### ISSUE TITLE
Errors pop up when change the key shortcuts in python 2.7

### ISSUE THREAD

**Issue by Gabrielvon** [spyder-ide/spyder#6245]
## Description of your problem
Hi,

I came across this pop-up error when I want to change the default shortcut of spyder27 in the conda environment of python 2.7. It seems simple to modify certain number of lines in the code. However, I am new to the development issues so I don't know how to solve this. 
![image](https://user-images.githubusercontent.com/8952869/35130685-23fd4c04-fcfd-11e7-8227-f6a9f305a813.png)

**What steps will reproduce the problem?**

I just simply open my spyder27 using command line, go to Preferences -> Keyboard shortcuts and do the modification. The error shows when I press the new shortcut before I select 'ok'.
![image](https://user-images.githubusercontent.com/8952869/35130869-04da0be0-fcfe-11e7-9807-ee0e36825eaf.png)

**What is the expected output? What do you see instead?**
Please give me any advice that I can change the default shortcuts. Thanks!

**Please provide any additional information below**
I tried that in my python 3 environment and it works fine.

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 2.7
* Qt Version: 5.6.2
* PyQt Version: 5.6.2
* Operating system: window 7

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.27.3 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. @csabella, could you take a look at this one? This error appeared after your PR #6092.

**Comment by Gabrielvon** [comment]
Sorry. A stupid but quick question. Since I found this issues seems solved on #6251 , should I do anything on my end so that I can modify the shortcut normally?

**Comment by csabella** [comment]
@Gabrielvon  Release 3.2.7 with the fix in it should be out before the end of the month.  If that's too long to wait, you can try to edit the `spyder.ini` file directly, but that's not really recommended.  Although, if you mess it up, it is recoverable using `spyder --reset`.  Search for `spyder.ini` on your system.  Open it in Notepad, or some other simple text editor (not Spyder and not Word), and search on `shortcuts`.  Hopefully, you'll find the shortcuts you want to modify and you'll be able to change them as you wish.

**Comment by Gabrielvon** [comment]
@csabella Awesome! Perfectly solved my problems. Thanks a lot!
