### ISSUE TITLE
Spyder notebook complains about missing file or directory: 'jupyter'

### ISSUE THREAD

**Issue by BjornFJohansson** [spyder-ide/spyder#6248]
This issue might be in the wrong place, but I sent i automatically from spyder.

## Description

**What steps will reproduce the problem?**

1. conda install -c spyder-ide spyder-notebook
2. switch to notebook pane in spyder
3. right click and open an ipynb file on the file system (that file works with the jupyter notebook cmd)

**What is the expected output? What do you see instead?**
![image](https://user-images.githubusercontent.com/9726401/35137736-c7d20484-fce2-11e7-8a75-30e681fd0817.png)

**Please provide any additional information below**

  File "/home/bjorn/anaconda3/envs/bjorn36/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 412, in open_notebook
    self.create_new_client(filename=filename)
  File "/home/bjorn/anaconda3/envs/bjorn36/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 314, in create_new_client
    server_info = nbopen(filename)
  File "/home/bjorn/anaconda3/envs/bjorn36/lib/python3.6/site-packages/spyder_notebook/utils/nbopen.py", line 75, in nbopen
    proc = subprocess.Popen(command, creationflags=creation_flag)
  File "/home/bjorn/anaconda3/envs/bjorn36/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/home/bjorn/anaconda3/envs/bjorn36/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'jupyter': 'jupyter'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```
`(bjorn36) bjorn@bjorn-ThinkPad-T450s:~$ conda install -c spyder-ide spyder-notebook
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/bjorn/anaconda3/envs/bjorn36:

The following NEW packages will be INSTALLED:

    spyder-notebook: 0.1.1-py36_0 spyder-ide

spyder-noteboo 100% |####################################################################################| Time: 0:00:00 105.01 kB/s
(bjorn36) bjorn@bjorn-ThinkPad-T450s:~$ `

`(bjorn36) bjorn@bjorn-ThinkPad-T450s:~$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.1.3
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/bjorn/anaconda3  (writable)
    default environment : /home/bjorn/anaconda3/envs/bjorn36
       envs directories : /home/bjorn/anaconda3/envs
                          /home/bjorn/.conda/envs
          package cache : /home/bjorn/anaconda3/pkgs
                          /home/bjorn/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/BjornFJohansson/linux-64
                          https://conda.anaconda.org/BjornFJohansson/noarch
            config file : /home/bjorn/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.13.0-26-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
(bjorn36) bjorn@bjorn-ThinkPad-T450s:~$ conda list
# packages in environment at /home/bjorn/anaconda3/envs/bjorn36:
#
alabaster                 0.7.10           py36h306e16b_0    defaults
anaconda                  custom           py36hbbc8b67_0    defaults
anaconda-client           1.6.5            py36h19c0dcd_0    defaults
anaconda-navigator        1.6.9            py36h11ddaaa_0    defaults
anaconda-project          0.8.0            py36h29abdf5_0    defaults
appdirs                   1.4.3                    py36_0    defaults
asn1crypto                0.22.0           py36h265ca7c_1    defaults
astroid                   1.5.3            py36hbdb9df2_0    defaults
astropy                   2.0.2            py36ha51211e_4    defaults
attrs                     17.3.0           py36h5ab58ff_0    defaults
autopep8                  1.3.3                      py_0    conda-forge
babel                     2.5.0            py36h7d14adf_0    defaults
backports                 1.0              py36hfa02d7e_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2    defaults
beautifulsoup4            4.6.0            py36h49b8c8c_1    defaults
biopython                 1.69                np113py36_0    defaults
bitarray                  0.8.1            py36h5834eb8_0    defaults
bkcharts                  0.2              py36h735825a_0    defaults
blaze                     0.11.3           py36h4e06776_0    defaults
bleach                    2.0.0            py36h688b259_0    defaults
bokeh                     0.12.10          py36hbb0e44a_0    defaults
boto                      2.48.0           py36h6e4cd66_1    defaults
bottleneck                1.2.1            py36haac1ea0_0    defaults
bzip2                     1.0.6                h0376d23_1    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
cairo                     1.14.10              haa5651f_5    defaults
certifi                   2017.7.27.1      py36h8b7b77e_0    defaults
cffi                      1.10.0           py36had8d393_1    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7              py36h5253387_0    defaults
cloudpickle               0.4.0            py36h30f8c20_0    defaults
clyent                    1.2.2            py36h7e57e65_1    defaults
colorama                  0.3.9            py36h489cec4_0    defaults
contextlib2               0.5.5            py36h6c84a62_0    defaults
coverage                  4.4.2            py36hca7c4c5_0    defaults
cryptography              2.0.3            py36ha225213_1    defaults
curl                      7.55.1               hcb0b314_2    defaults
cycler                    0.10.0           py36h93f1223_0    defaults
cython                    0.26.1           py36h21c49d0_0    defaults
cytoolz                   0.8.2            py36h708bfd4_0    defaults
dask                      0.15.3           py36hdc2c8aa_0    defaults
dask-core                 0.15.3           py36h10e6167_0    defaults
datashape                 0.5.4            py36h3ad6b5c_0    defaults
dbus                      1.10.22              h3b5a359_0    defaults
decorator                 4.1.2            py36hd076ac8_0    defaults
distributed               1.19.1           py36h25f3894_0    defaults
docutils                  0.14             py36hb0f60f5_0    defaults
dropbox                   8.5.0            py36h9ff2726_0    anaconda
entrypoints               0.2.3            py36h1aec115_2    defaults
et_xmlfile                1.0.1            py36hd6bccc3_0    defaults
expat                     2.2.4                hc00ebd1_1    defaults
fastcache                 1.0.2            py36h5b0c431_0    defaults
filelock                  2.0.12           py36hacfa1f5_0    defaults
flask                     0.12.2           py36hb24657c_0    defaults
flask-cors                3.0.3            py36h2d857d3_0    defaults
fontconfig                2.12.4               h88586e7_1    defaults
freetype                  2.8                  h52ed37b_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py36h2fe25dc_0    defaults
glib                      2.53.6               hc861d11_1    defaults
glob2                     0.5              py36h2c1b292_1    defaults
gmp                       6.1.2                hb3b607b_0    defaults
gmpy2                     2.0.8            py36h55090d7_1    defaults
graphite2                 1.3.10               hc526e54_0    defaults
greenlet                  0.4.12           py36h2d503a6_0    defaults
gst-plugins-base          1.12.2               he3457e5_0    defaults
gstreamer                 1.12.2               h4f93127_0    defaults
h5py                      2.7.0            py36he81ebca_1    defaults
harfbuzz                  1.5.0                h2545bd6_0    defaults
hdf5                      1.10.1               hb0523eb_0    defaults
heapdict                  1.0.0            py36h79797d7_0    defaults
html5lib                  0.999999999      py36h2cfc398_0    defaults
hypothesis                3.38.5           py36h196a6cc_0    defaults
icu                       58.2                 h211956c_0    defaults
idna                      2.6              py36h82fb2a8_1    defaults
imageio                   2.2.0            py36he555465_0    defaults
imagesize                 0.7.1            py36h52d8127_0    defaults
intel-openmp              2018.0.0             h15fc484_7    defaults
ipdb                      0.10.3                   py36_0    conda-forge
ipykernel                 4.6.1            py36hbf841aa_0    defaults
ipython                   6.2.1            py36h88c514a_1    defaults
ipython_genutils          0.2.0            py36hb52b0d5_0    defaults
ipywidgets                7.0.0            py36h7b55c3a_0    defaults
isort                     4.2.15           py36had401c0_0    defaults
itsdangerous              0.24             py36h93cc618_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py36h4c697fb_0    defaults
jedi                      0.10.2           py36h552def0_0    defaults
jinja2                    2.9.6            py36h489bce4_1    defaults
jpeg                      9b                   habf39ab_1    defaults
jsonschema                2.6.0            py36h006f8b5_0    defaults
jupyter                   1.0.0            py36h9896ce5_0    defaults
jupyter_client            5.1.0            py36h614e9ea_0    defaults
jupyter_console           5.2.0            py36he59e554_1    defaults
jupyter_core              4.4.0            py36h7c827e3_0    defaults
jupyterlab                0.30.6           py36h2f9c1c0_0    defaults
jupyterlab_launcher       0.6.0                    py36_0    defaults
lazy-object-proxy         1.3.1            py36h10fcdad_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc                    5.4.0                         0    brown-data-science
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libpng                    1.6.32               hda9c8bc_2    defaults
libsodium                 1.0.13               h31c71d8_2    defaults
libssh2                   1.8.0                h8c220ad_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.8                h90200ff_9    defaults
libtool                   2.4.6                hd50d1a6_0    defaults
libxcb                    1.12                 h84ff03f_3    defaults
libxml2                   2.9.4                h6b072ca_5    defaults
libxslt                   1.1.29               hcf9102b_5    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36h787c0ad_1    defaults
lxml                      4.1.0            py36h5b66e50_0    defaults
lzo                       2.10                 h1bfc0ba_1    defaults
markupsafe                1.0              py36hd9260cd_1    defaults
matplotlib                2.1.0            py36hba5de38_0    defaults
mccabe                    0.6.1            py36h5ad9710_1    defaults
mistune                   0.7.4            py36hbab8784_0    defaults
mkl                       2018.0.0             hb491cac_4    defaults
mkl-service               1.1.2            py36h17a0993_4    defaults
mpc                       1.0.3                hf803216_4    defaults
mpfr                      3.1.5                h12ff648_1    defaults
mpldatacursor             0.6.2                    py36_1    BjornFJohansson
mpmath                    0.19             py36h8cc018b_2    defaults
msgpack-python            0.4.8            py36hec4c5d1_0    defaults
multipledispatch          0.4.9            py36h41da3fb_0    defaults
navigator-updater         0.1.0            py36h14770f7_0    defaults
nbconvert                 5.3.1            py36hb41ffb7_0    defaults
nbformat                  4.4.0            py36h31c9010_0    defaults
nbval                     0.7                        py_0    conda-forge
ncurses                   6.0                  h06874d7_1    defaults
networkx                  2.0              py36h7e96fb8_0    defaults
nltk                      3.2.4            py36h1a0979f_0    defaults
nose                      1.3.7            py36hcdf7029_2    defaults
notebook                  5.2.2            py36h40a37e6_0    defaults
numba                     0.35.0             np113py36_10    defaults
numexpr                   2.6.2            py36hdd3393f_1    defaults
numpy                     1.13.3           py36ha12f23b_0    defaults
numpydoc                  0.7.0            py36h18f165f_0    defaults
odo                       0.5.1            py36h90ed295_0    defaults
olefile                   0.44             py36h79f9f78_0    defaults
openpyxl                  2.4.8            py36h41dd2a8_1    defaults
openssl                   1.0.2l               h077ae2c_5    defaults
ordered-set               2.0.2                    py36_0    conda-forge
p7zip                     16.02                hcef1464_0    brown-data-science
packaging                 16.8             py36ha668100_1    defaults
pandas                    0.20.3           py36h842e28d_2    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py36ha6701b7_1    defaults
pango                     1.40.11              h8191d47_0    defaults
partd                     0.3.8            py36h36fd896_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.3.1           py36he0c6f6d_0    defaults
pathlib2                  2.3.0            py36h49efa8e_0    defaults
patsy                     0.4.1            py36ha3be15e_0    defaults
pcre                      8.41                 hc71a17e_0    defaults
pdfrw                     0.4              py36heaf6461_0    BjornFJohansson
pep8                      1.7.0            py36h26ade29_0    defaults
pexpect                   4.2.1            py36h3b9d41b_0    defaults
pickleshare               0.7.4            py36h63277f8_0    defaults
pillow                    4.2.1            py36h9119f52_0    defaults
pint                      0.8.1                    py36_0    conda-forge
pip                       9.0.1            py36h8ec8b28_3    defaults
pixman                    0.34.0               h83dc358_2    defaults
pkginfo                   1.4.1            py36h215d178_1    defaults
pluggy                    0.6.0            py36hb689045_0    defaults
ply                       3.10             py36hed35086_0    defaults
prettytable               0.7.2                    py36_1    conda-forge
prompt_toolkit            1.0.15           py36h17d85b1_0    defaults
psutil                    5.4.0            py36h84c53db_0    defaults
ptyprocess                0.5.2            py36h69acd42_0    defaults
py                        1.5.2            py36h29bf505_0    defaults
pycodestyle               2.3.1            py36hf609f19_0    defaults
pycosat                   0.6.2            py36h1a0ea17_1    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pycrypto                  2.6.1            py36h6998063_1    defaults
pycurl                    7.43.0           py36h5e72054_3    defaults
pyexcel-ezodf             0.3.4                      py_0    conda-forge
pyfiglet                  0.7.5                    py36_0    conda-forge
pyflakes                  1.6.0            py36h7bd6a15_0    defaults
pygments                  2.2.0            py36h0d3125c_0    defaults
pylint                    1.7.4            py36hb9d4533_0    defaults
pympler                   0.5              py36h6b12e4d_0    defaults
pyodbc                    4.0.17           py36h999153c_0    defaults
pyopenssl                 17.2.0           py36h5cc804b_0    defaults
pyparsing                 2.2.0            py36hee85983_1    defaults
pypdf2                    1.26.0                   py36_1    conda-forge
pyqt                      5.6.0            py36h0386399_5    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pytables                  3.4.2            py36h3b5282a_2    defaults
pytest                    3.3.1                    py36_0    conda-forge
pytest-cov                2.5.1            py36hd4733f3_0    defaults
pytest-mock               1.6.3                    py36_1    conda-forge
pytest-runner             3.0              py36hd5415d6_0    defaults
python                    3.6.3                hc9025b9_1    defaults
python-dateutil           2.6.1            py36h88d3b88_1    defaults
pytz                      2017.2           py36hc2ccc2a_1    defaults
pywavelets                0.5.2            py36he602eb0_0    defaults
pyyaml                    3.12             py36hafb9ca4_1    defaults
pyzmq                     16.0.2           py36h3b0cf96_2    defaults
qt                        5.6.2               h974d657_12    defaults
qtawesome                 0.4.4            py36h609ed8c_0    defaults
qtconsole                 4.3.1            py36h8f73b5b_0    defaults
qtpy                      1.3.1            py36h3691cc8_0    defaults
readline                  7.0                  hac23ff0_3    defaults
reportlab                 3.4.0                    py36_0    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
requests-mock             1.4.0                    py36_0    BjornFJohansson
requests-toolbelt         0.8.0                    py36_0    conda-forge
rope                      0.10.5           py36h1f8c17e_0    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
scikit-image              0.13.0           py36had3c07a_1    defaults
scikit-learn              0.19.1           py36h7aa7ec6_0    defaults
scipy                     0.19.1           py36h9976243_3    defaults
seaborn                   0.8.0            py36h197244f_0    defaults
setuptools                38.2.4                   py36_0    conda-forge
simplegeneric             0.8.1            py36h2cb9092_0    defaults
singledispatch            3.4.0.3          py36h7a266c3_0    defaults
sip                       4.18.1           py36h51ed4ed_2    defaults
six                       1.11.0           py36h372c433_1    defaults
snowballstemmer           1.2.1            py36h6febd40_0    defaults
sortedcollections         0.5.3            py36h3c761f9_0    defaults
sortedcontainers          1.5.7            py36hdf89491_0    defaults
sphinx                    1.6.3            py36he5f0bdb_0    defaults
sphinxcontrib             1.0              py36h6d0f590_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1    defaults
spyder                    3.2.6                    py36_0    defaults
spyder-notebook           0.1.1                    py36_0    spyder-ide
sqlalchemy                1.1.13           py36hfb5efd7_0    defaults
sqlite                    3.20.1               h6d8b0f3_1    defaults
statsmodels               0.8.0            py36h8533d0b_0    defaults
sympy                     1.1.1            py36hc6d1c1c_0    defaults
tblib                     1.3.2            py36h34cf8b6_0    defaults
termcolor                 1.1.0                    py36_0    defaults
terminado                 0.6              py36ha25a19f_0    defaults
testpath                  0.3.1            py36h8cadb63_0    defaults
tk                        8.6.7                h5979e9b_1    defaults
toolz                     0.8.2            py36h81f2dff_0    defaults
tornado                   4.5.2            py36h1283b2a_0    defaults
tqdm                      4.19.4           py36ha5a5176_0    defaults
traitlets                 4.3.2            py36h674d592_0    defaults
twine                     1.9.1                    py36_2    conda-forge
typing                    3.6.2            py36h7da032a_0    defaults
unicodecsv                0.14.1           py36ha668878_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
wcwidth                   0.1.7            py36hdf4376a_0    defaults
webencodings              0.5.1            py36h800622e_1    defaults
werkzeug                  0.12.2           py36hc703753_0    defaults
wheel                     0.29.0           py36he7f4e38_1    defaults
widgetsnbextension        3.0.2            py36hd01bb71_1    defaults
wrapt                     1.10.11          py36h28b7045_0    defaults
xlrd                      1.1.0            py36h1db9f0c_1    defaults
xlsxwriter                1.0.2            py36h3de1aca_0    defaults
xlwt                      1.3.0            py36h7b00a1f_0    defaults
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
zeromq                    4.2.2                hb0b69da_1    defaults
zict                      0.1.3            py36h3a3bf81_0    defaults
zlib                      1.2.11               hfbfcf68_1    defaults
zope                      1.0                      py36_0    defaults
zope.interface            4.4.3            py36h0ccbf34_0    defaults
(bjorn36) bjorn@bjorn-ThinkPad-T450s:~$ 
`

**Comment by ccordoba12** [comment]
Moving this one to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #141](https://github.com/spyder-ide/spyder-notebook/issues/141) via [**ZenHub**](https://www.zenhub.com/)
