### ISSUE TITLE
Convert re expressions to use raw strings

### ISSUE THREAD

**Issue by csabella** [spyder-ide/spyder#6254]
This is probably a long way off, but I just saw this in the CPython 3.7 REPL.
```
Python 3.7.0a4+ (heads/master:7ed7aead95, Jan 15 2018, 05:37:55) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> s = '123abcd'
>>> re.findall('\d', s)
<stdin>:1: DeprecationWarning: invalid escape sequence \d
['1', '2', '3']

>>> re.findall(r'\d', s)
['1', '2', '3']
>>> 
```
So, any regular strings in a re expression that use one of the escape characters now give a DeprecationWarning (which has existed since 3.6, but they recently changed the REPL to show deprecation warnings).  I think it might be best to convert all the `re` code to use raw strings so that this doesn't cause any issues later.  I can't imagine what will happen to codebases when this is an error and not a warning.

If you agree that this should be done, which version should it be under?

**Comment by ccordoba12** [comment]
> If you agree that this should be done, which version should it be under?

I think this should be done against 3.x, in case we are unable to release 4.0 before Python 3.7 is out.

**Comment by CAM-Gerlach** [comment]
Is this a matter of sticking ``r`` in front of all the``re`` strings, and double checking to make sure there aren't any now-unnecessary double escapes and that they otherwise still work? If it turns out to be a lot of menial work, let me know if you'd like to deputize me as an extra hand to help with chunks of this.

**Comment by csabella** [comment]
@CAM-Gerlach   Thanks!  It seems like it will be mostly small touches, like you said sticking an `r` in front of the `re` strings.  I think the more important part of this one will be the code review and testing.

**Comment by CAM-Gerlach** [comment]
Well that was quick! Let me know if you need anything else.
