### ISSUE TITLE
Syntax highlighting for other file types

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#626]
_From [rutok...@gmail.com](https://code.google.com/u/110295942747353194960/) on 2011-04-17T08:48:17Z_

It is important IDE feature to edit all project related files in one place. Spyder currently doesn't highlight syntax in common related files (such as html, css, xml..). It would be nice to add syntax highlighting for at least those "common" files, if not the ability to load some kind of syntax definition files (which would make syntax highlighting extensible).

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=626_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-17T13:23:24Z_

Thanks for your interest in Spyder.

The syntax highlighting is already extensible but only by writing a Python class in here: https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/codeeditor/syntaxhighlighters.py The html and css classes have just been wrote by a contributor (Alex Fargus: https://code.google.com/r/alexfargus-syntaxhighlighters/ ): https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/codeeditor/syntaxhighlighters.py#708 The xml syntax highlighter should not be too hard to implement -- let's open an issue for that: https://code.google.com/p/spyderlib/issues/detail?id=628

**Status:** Done

**Comment by spyder-issues-migrator** [comment]
_From [rutok...@gmail.com](https://code.google.com/u/110295942747353194960/) on 2011-04-17T13:59:02Z_

Wow, thank you for fast reply and quick resolution. I really like Spyder and this made it yet a bit better :-)
Thank you for your work!

**Comment by cloudcell** [comment]
I tried everything I could but I could not make the syntax highlightener highlight *.pyi files. Please help me fix this issue if you can.

**Comment by ccordoba12** [comment]
Please open a new issue about it. We don't provide completions for those files yet.
