### ISSUE TITLE
Deprecation Warning on imp module

### ISSUE THREAD

**Issue by csabella** [spyder-ide/spyder#6260]
I ran bootstrap with DeprecationWarnings turned on.  (yikes!)

Anyway, got this:
```
/home/cheryl/spyder/spyder/utils/programs.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
```

Opening this issue to refactor the use of `imp`.  It may require different usage under 2.7 than just using `importlib` as `importlib` in 2.7 isn't the same as `importlib` in 3.3+.

**Comment by maurerle** [comment]
This can be closed, as it is fixed and old.
