### ISSUE TITLE
Cannot get Pandas DataFrame to render as table.

### ISSUE THREAD

**Issue by EdwardJB** [spyder-ide/spyder#6261]
## Description of your problem

Cannot get Pandas DataFrame to render as table. I've just spent too long trying to do this can simply cannot manage it.

**What steps will reproduce the problem?**

1. Run this code: 

```
import pandas as pd
df=pd.DataFrame([1,2,3])
df
```

**What is the expected output? What do you see instead?**

I'd expect to see a [rendered table inline with the console, like this](https://stackoverflow.com/questions/25818216/how-can-i-remove-borders-from-display-of-dataframe-in-ipython-qtconsole-anacond).

Instead get this output:

```
Out[22]: 
   0
0  1
1  2
2  3
```

I realize I can view via the Variable Explorer, but I need the data inline.

Plotting inline and embedding PNGs etc. works OK. Trying to force things to render via HTML, or trying to render Latex, just does this sort of thing:

```
from IPython.core.display import HTML
HTML('<a href="http://example.com">link</a>')
Out[24]: <IPython.core.display.HTML object>
```

**Please provide any additional information below**
## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

The "About" box isn't copy pastable. But it's the latest via pip as per now on Windows 10.

**Comment by ccordoba12** [comment]
Our console had very limited support to display Html content, but it was removed by the Jupyter guys several years ago (three at least, I think).

> or trying to render Latex

That should be working just fine. If not, please open an issue here

https://github.com/jupyter/qtconsole
