### ISSUE TITLE
QT warning on console on first startup after undocking (QWindowsWindow::setGeometry: Unable to set geometry... )

### ISSUE THREAD

**Issue by robbuckley** [spyder-ide/spyder#6268]
## Description of your problem

warning message below displayed on windows CMD console when starting spyder in certain conditions. Does not seem to affect the operation once its running

QWindowsWindow::setGeometry: Unable to set geometry 1920x1131+1920+29 on QWidgetWindow/'MainWindowClassWindow'. Resulting geometry:  1920x1055+1920+29 (frame: 9, 38, 9, 9, custom margin: 0, 0, 0, 0, minimum size: 440x333, maximum size: 16777215x16777215)

**What steps will reproduce the problem?**

1.  while docked (+external monitor), run spyder by entering 'spyder' from windows CMD line
2. shut down
3. eject from dock
4. run spyder again (as step 1)
5. error message is seen

**What is the expected output? What do you see instead?**
dont expect to see any warning message on teh cmd line

**Please provide any additional information below**

after shutting down spyder and restarting without docking, the message is not reproduced. To reproduce it again, i have to dock, run spyder, then repeat from step 1 above

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.4
* Qt Version: 5.6.2
* PyQt Version: 5.5.6
* Operating system: Win 10 Pro

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
> warning message below displayed on windows CMD console when starting spyder in certain conditions. Does not seem to affect the operation once its running

Thanks for reporting, but this seems a Qt problem more than a Spyder one. Due to that, I really doubt we can do something about it.

Besides, fortunately it's a warning.

**Comment by CAM-Gerlach** [comment]
Its harmless, as far as I can tell; I see it all the time on different Windows machines.
