### ISSUE TITLE
Console Syntax Highlighting changes within the same traceback

### ISSUE THREAD

**Issue by csabella** [spyder-ide/spyder#6270]
In a single traceback (that is, no other commands or intervention while this was printing out), the syntax highlighting changes colors from linux (which is not selected) to lightbg (which is selected).

![screenshot from 2018-01-22 12-10-20](https://user-images.githubusercontent.com/25619791/35234459-38c4286e-ff6f-11e7-87a0-8653e380373e.png)

It does the opposite on a dark background:
![screenshot from 2018-01-22 12-28-15](https://user-images.githubusercontent.com/25619791/35234699-00e09332-ff70-11e7-923a-d8ec0a545367.png)

**Comment by CAM-Gerlach** [comment]
Yup, same for me Spyder 3.2.6, Qt/PyQt 5.6.2/5.6, Python 3.6.4 x64, IPython 6.1.0 and qtconsole 4.3.1 on Windows 8.1 Pro x64. I was unable to cleanly reproduce this in bare ``qtconsole``, as there is only one color scheme, the default.

![image](https://user-images.githubusercontent.com/17051931/35253004-bbf5292a-ffa8-11e7-937d-5a821206412b.png)

**Comment by impact27** [comment]
I think this is the expected behaviour. The file in which the exception occured is colored differently to separate it from the stack files.

**Comment by goanpeca** [comment]
So should we close?

**Comment by ccordoba12** [comment]
If this something that IPython does, then we can't solve it here.

**Comment by mkovach2** [comment]
Hi!  dunno if this is still a problem, but I was able to at least band-aid it (on Windows 11, spyder 5.4.2) by opening
`AppData\Local\Programs\Spyder\pkgs\IPython\core\excolors.py`
and swapping lines 80-81 with lines 108-109, making the Linux color scheme's traceback use LightGreen for regular and emphasized traceback lines, and Green for LightBG's regular traceback lines.   Hope this helps for now

**Comment by CAM-Gerlach** [comment]
It seems this may be the intended behavior, but you could consider at least submitting an issue/PR to upstream IPython (particularly since the change you made is to that codebase)?
