### ISSUE TITLE
code in editor not running in console

### ISSUE THREAD

**Issue by jaaks** [spyder-ide/spyder#6271]
## Description

**What steps will reproduce the problem?**

1. import openpyxl
2. wb=openpyxl.load_workbook('a workbook')
3. type (wb)

**What is the expected output? What do you see instead?**
If I hit run, nothing appears in the console windows
If I enter the code directly into the console, it runs fine.

**Please provide any additional information below**
Am using anaconda3 5.0.0,  on win 10
Did try updating. The message indicated I am running the latest version.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
You need to change `type(wb)` to `print(type(wb))` to see something when running the file with `Run`.

**Comment by jaaks** [comment]
Did that. Same result. Nothing.
