### ISSUE TITLE
It crashes when minimize or resizing the spyder in Windows 7

### ISSUE THREAD

**Issue by tedykim11** [spyder-ide/spyder#6279]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4.dev0 
* Python Version: 3.5.3
* Qt Versions: 5.8.0, PyQt5 5.8.1 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.0 (OK)
matplotlib >=1.0 :  2.0.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.6.5 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Unfortunately, your error report doesn't contain any information, such as a traceback or error message, a detailed description of whether if it worked before, what you did preceding the error, and what you tried to fix it, and information on anything particular to your setup and how you installed Spyder, that would allow us to address it. Furthermore, your version of Spyder is many months out of date along with your environment, while you are using a much newer version of Qt, which has the potential to cause issues outside of Spyder's control.

In any case, this is most likely a user-side issue that can be resolved by a clean install of the up to date Anaconda distribution. Furthermore, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. Therefore, this issue will be closed.  

If the problem still occurs, and you are able to provide the of this information to allow us to see if it is an issue with Spyder and if so, fix it from our end, then you are welcome to do so and reopen this issue. Best of luck!
