### ISSUE TITLE
Do not reopen Project explorer on startup

### ISSUE THREAD

**Issue by homocomputeris** [spyder-ide/spyder#6292]
## Description

**What steps will reproduce the problem?**

1. Close _Project explorer_ pane
2. Close Spyder
3. Open Spyder

**What is the expected output?** 
No _Project explorer_

**What do you see instead?**
_Project explorer_ is back, however the corresponding checkbox in _Projects_ drop-down menu is unchecked

**Please provide any additional information below**
I don't know if it's a bug or a feature. Anyway, Spyder should not decide for me what to see. Exists since 3.2.4 at least.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by csabella** [comment]
@homocomputeris   Thanks for the report!

**Comment by CAM-Gerlach** [comment]
Thanks @csabella , I've seen this one consistently as well (on Windows) but I didn't want to gum up the works reporting it if it only bothered me...looks like that's not the case. 

I guess the broader question is when opening a project (which is the routine underlying this), would we then not want to open project explorer if it isn't already open in the previous project? What if no project was open previously? Just save the last known state and go by that? 

Just some questions to ponder...

**Comment by jitseniesen** [comment]
It bothered me as well, to be honest. Can we do the same as we do for the Outline panel? I don't know exactly when the Outline panel appears and disappears, but it does not bother me so the rules for the Outline panel are at least sensible for how I use it.

**Comment by CAM-Gerlach** [comment]
> Can we do the same as we do for the Outline panel?

At least on Windows, I haven't observed any funny business with that in any Spyder version I've used (since 3.2.1).

**Comment by jitseniesen** [comment]
Sorry, I closed the issue by accident
