### ISSUE TITLE
environment / recent files lost on restart

### ISSUE THREAD

**Issue by robbuckley** [spyder-ide/spyder#6300]
on startup on spyder, it behaves like a new install -- i.o. no files were opened except a new 'temp.py', and the File/Open recent list is empty.  Im in the same runtime env as last time (base conda env, on windows 10)

**What steps will reproduce the problem?**

sorry, not sure how to repro... Im happy to help investigate

**What is the expected output? What do you see instead?**

on startup of spyder i expect to see the files open which were open in the last session. 
File/open recent should have a list of the most recently opened files from previous sessions

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.4
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: win 10 pro

## Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
I think this happens because there's a problem while writing Spyder preferences to disk. So if Spyder finds that kind of problem, it resorts to use a clean set of settings.

**Comment by ccordoba12** [comment]
Please try to find a directory called `.spyder-py3` under your `C:\Users\<your-user>` directory and see what contents it has.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide the information requested, then please do re-open this and add it as a comment. Thanks!
