### ISSUE TITLE
Spyder does not start

### ISSUE THREAD

**Issue by nathaly-l** [spyder-ide/spyder#6309]
I reinstalled Python(x,y). Now Spyder is not starting anymore.

When I click on the icon, a command prompt opens for way less than a second and closes again. After that, noting happens. I already tried the following:

1. typing `spyder --reset` into the Windows Command Prompt
2. deleting spyder.lock from `C:\Users\myname\.spyder`
3. reinstalling Python(x,y) again
4. typing `pip install -U spyder` into the Windows Command Prompt

Nothing helped so far.

Versions:

- Python Version: Python(x,y)-2.7.10.0
- Operating system: Windows 10 Pro 64bit

**Comment by CAM-Gerlach** [comment]
From what we can tell, Python(x,y) may or may not actually be maintained at this point; the website hasn't been updated in a long time, and we have no control over any problems specific to that distribution. Furthermore, ``pip`` installations are really for experts only, and can involve many tricky mahcine-specific issues.

You are welcome to try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues, to see if you can get it working on your own. 

However, while we offer a number of methods to install Spyder, we are only able to officially support the Anaconda distribution, as it avoids many of the problems and pitfalls found in other install methods, particularly for less experienced users. Therefore, this issue will be closed. Best of luck!
