### ISSUE TITLE
Selecting "tutorial" from help menu does not bring up Help pane automatically if not loaded, leading to user confusion

### ISSUE THREAD

**Issue by mlclark88** [spyder-ide/spyder#6317]
## Description

**What steps will reproduce the problem?**

1. Open help tab
2. click Spyder tutorial
3. Nothing happens

**What is the expected output? What do you see instead?**
When I click spyder tutorial, nothing happens. 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by csabella** [comment]
The Spyder tutorial opens in the Help pane.  It does seem that if the Help pane isn't already visible, that it doesn't open it.  Please click on `View -> Panes` and make sure that Help is selected.  If you click the Tutorial, the Help panel should show text that starts with 'Spyder is an Integrated Development Environment (IDE) for scientific computing using the Python programming language.'

**Comment by CAM-Gerlach** [comment]
Reproduced, when the help pane is closed; when opened again the Tutorial shows up.

I was going to suggest how to fix it (opening the help pane if closed when ``show_tutorial`` is called, but ended up just doing it myself. PR incoming momentarily as soon as I write a quick test.

**Comment by CAM-Gerlach** [comment]
I fixed the behavior just fine, but the tests are proving rather more time-consuming than anticipated, given the need to setup all the fixtures and mocks for a mainwindow, console, help viewer etc. from scratch to properly test the behavior. I'm most of the way there, but I need to put it on hold for a bit to finish priority items for 3.2.7, so its bumped to the next release. Thanks for your patience.
