### ISSUE TITLE
n**3 with n>0 gives negative result

### ISSUE THREAD

**Issue by dododoooo** [spyder-ide/spyder#6328]
## Description

**What steps will reproduce the problem?**

1. here the simple script: 
import numpy 

def numpysum(n):

    a=numpy.arange(n)**2
    b=numpy.arange(n)**3
    c=a+b
    return c

2. in the console i write: numpysum(2000)
3. 

**What is the expected output? What do you see instead?**
Believe it or not this is what i see:
numpysum(2000)
Out[29]: 
array([         0,          2,         12, ..., -621892610, -609918596,
       -597932592], dtype=int32)

**Please provide any additional information below**
Please, explain me this because i tried it all

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by dododoooo** [comment]
Please, tell me how i can visualize all the result and not only the first and last terms. Thank you a lot

**Comment by bcolsen** [comment]
This is not a spyder problem.

You are getting 32-bit integers from numpy.arange() and they are overflowing to negative here:
```python
b=numpy.arange(n)**3
```
1999**3 gives 7,988,005,999 which is greater than the maximum of 2,147,483,647 that a 32-bit signed integer can represent without looping over and giving negative values. See (https://en.wikipedia.org/wiki/Integer_overflow)

Long story short use floats or int64:
```python
def numpysum(n):
    a=numpy.arange(n ,dtype=float)**2
    b=numpy.arange(n ,dtype=float)**3
    c=a+b
    return c
```

**Comment by dododoooo** [comment]
Thank you a lot. I arrived at the same conclusion in the meanwhile but you
was crystal clear and now i understand a lot better the problem. Which is
the command to use int64? Thank you sir

Il 29 gen 2018 10:00 PM, "bcolsen" <notifications@github.com> ha scritto:

**Comment by bcolsen** [comment]
Just put in int64 instead of float:

This is with int32:
```python
np.arange(2000,dtype=int32)**3
array([         0,          1,          8, ..., -625880619, -613910600,
       -601928593], dtype=int32)
```
Vs this with int64:
```python
np.arange(2000,dtype=int64)**3
array([         0,          1,          8, ..., 7964053973, 7976023992,
       7988005999])
```

Vs this with float:
```python
np.arange(2000,dtype=float)**3
array([  0.00000000e+00,   1.00000000e+00,   8.00000000e+00, ...,
         7.96405397e+09,   7.97602399e+09,   7.98800600e+09])
```

**Comment by dododoooo** [comment]
Ok, I get that int32 and also int64 are not defined. Is this depending on
my version? Python 3.6

Il 29 gen 2018 10:21 PM, "bcolsen" <notifications@github.com> ha scritto:

**Comment by bcolsen** [comment]
Oops try numpy.int64

**Comment by dododoooo** [comment]
Perfect. Thank you so much. It works just like you showed. It is very
clear. Thanks again

Il 29 gen 2018 10:30 PM, "bcolsen" <notifications@github.com> ha scritto:

> Oops try numpy.int64

**Comment by ccordoba12** [comment]
Thanks @bcolsen for helping @dododoooo.
