### ISSUE TITLE
UUID crash on Spyder 3.2.4/3.2.6 startup

### ISSUE THREAD

**Issue by paddyh087** [spyder-ide/spyder#6335]
## Description

**What steps will reproduce the problem?**

1. Open Spyder from anaconda, or console (MacOS 10.13.3)
2. Spyder will crash
3. NB. I have tried conda update conda, conda update anaconda, conda update --all. No avail.

**What is the expected output? What do you see instead?**
Spyder crashes. uuid.uuid1() appears to be the cause. importing uuid and running uuid.uuid1() into ipython also raises the same error.

**Please provide any additional information below**

  File "/Users/pjh523/anaconda3/lib/python3.6/site-packages/spyder/plugins/ipythonconsole.py", line 950, in update_working_directory
    shellwidget.get_cwd()
  File "/Users/pjh523/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 128, in get_cwd
    self.silent_exec_method(code)
  File "/Users/pjh523/anaconda3/lib/python3.6/site-packages/spyder/widgets/ipythonconsole/shell.py", line 340, in silent_exec_method
    local_uuid = to_text_string(uuid.uuid1())
  File "/Users/pjh523/anaconda3/lib/python3.6/uuid.py", line 606, in uuid1
    clock_seq_hi_variant, clock_seq_low, node), version=1)
  File "/Users/pjh523/anaconda3/lib/python3.6/uuid.py", line 168, in __init__
    raise ValueError('field 6 out of range (need a 48-bit value)')
ValueError: field 6 out of range (need a 48-bit value)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

**Comment by ccordoba12** [comment]
> Spyder crashes. uuid.uuid1() appears to be the cause. importing uuid and running uuid.uuid1() into ipython also raises the same error.

Then this is not a Spyder problem. Please report in Anaconda:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by CAM-Gerlach** [comment]
Thanks for the followup @paddyh087

**Comment by ATFromGA** [comment]
I apologize for being a complete beginner, but how do I actually get use the information in that link to solve the problem with SPYDER?

**Comment by CAM-Gerlach** [comment]
> I apologize for being a complete beginner, but how do I actually use the information in that link to solve the problem with SPYDER?

The problem is, as stated, not with Spyder, but rather an interaction between Python and the OS (High Sierra) that we have no control over. The fix suggested in the thread was manually patching the problem ``uuid()`` function to handle the longer address without raising an exception; otherwise, you can wait a couple weeks for Python 3.6.5 to be released which will include the fix.
