### ISSUE TITLE
tensorflow upgrade makes spyder(3.2.5) editor auto-complitation fail in python3.6.4

### ISSUE THREAD

**Issue by QuntuamLoop** [spyder-ide/spyder#6342]
the enviroment is in the python 3.6.4, with the tensorflow upgrade to the new version 1.5.0. The function in spyder editor auto-complitation was failed. After I uninstall the package future and futures, the function was work again. 
I also made a test in python 3.5.4, and there was no problem.
Did some guys suffered this problem?
![1](https://user-images.githubusercontent.com/32284800/35603573-e74fb2e4-0678-11e8-98f2-fb77f67c94bd.png)
![2](https://user-images.githubusercontent.com/32284800/35603576-e8e155ae-0678-11e8-94f4-d57234a2cf26.png)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. In general, given the problem occurred as a result of a specific, ``pip``-installed package, with the ever-problematic ``tensorflow``, on a ``pip`` install of Spyder, possibly involved Spyder's third party completion libraries, and in case was resolved by uninstalling said package, there really isn't going to be much of anything we can do about this from our end, sorry. Therefore, this issue will be closed. 

However, if you need additional help, please check out our autocomplete problems mega thread, issue #5782 , as well as [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections. Best of luck!
