### ISSUE TITLE
Code Completion Not working with DataFrames in Editor

### ISSUE THREAD

**Issue by Deom23** [spyder-ide/spyder#6349]
New to Spyder, but I am having issues getting the code completion to work within the editor in Spyder. It works just fine for packages, but when I have a dataframe and type Df. tab , it will not show me any of the column names within the dataframe. If i try this within the console it works just fine. I tried both the Anaconda install , and I also got rid of that and installed spyder via a pip command in python terminal, same effect both ways. 

## Versions and main components
* Spyder Version: 3.2.6
* Python Version: 3.6.4
* Qt Version:
* PyQt Version:
* Operating system: Windows 10

## Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by ccordoba12** [comment]
> it will not show me any of the column names within the dataframe

I think that's not supported by Jedi, the completion library we depend on, sorry. There's nothing we can do about it.

>  If i try this within the console it works just fine

The console and the Editor use different completion mechanisms. See this

https://stackoverflow.com/questions/42777430/why-autocompletion-options-in-spyder-3-1-are-not-fully-working-in-the-editor

for an explanation.
