### ISSUE TITLE
Mac eGPU, Sierra 10.13.3 Spyder Crash

### ISSUE THREAD

**Issue by newrickey** [spyder-ide/spyder#6350]
## Description of your problem

**What steps will reproduce the problem?**

1. Without a eGPU, spyder will launch from either Anaconda or from the terminal line
2.  Previous version of Mac OS were tested using spyder and it launched fine
3.  Required updates to mac os and it appears they are changing how eGPU are supported (for the good!) but I think it may have introduced an incompatibility with Spyder
4. I did a screen recording of the crash with the gGPU and it happens immediately after the kernel is loaded. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
The crash only happens with an eGPU attached best I can tell. I'm running CUDA 9.0 with 387.128 driver, NVIDIA web drivers 387.10.10.10.25.156.   The eGPU is a AkiTio Node with Titan Xp installed connected via thunderbolt 3. 

This appears to be the only program that crashes. I tried running native python 3.6, anaconda 3.5, anaconda 3.6. I've tried to update packages as best I can. I'm thinking it is OS related. I saw there was another note like this on a windows computer where the drivers were an issue.

Spyder isn't producing a meaningful error report in the command line. Just a generic segmentation fault. 

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

Mac OSx 10.13.3
## Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
Anaconda hasn't updated Qt/PyQt to work with High Sierra. Sorry, there's nothing we can do about it.
