### ISSUE TITLE
 Autocomplete does not work after installing tensorflow1.5.0

### ISSUE THREAD

**Issue by iipod2010** [spyder-ide/spyder#6365]
## Description of your problem

**What steps will reproduce the problem?**

1.uninstall python3.6.1
2.delete python36 directory
3.install python3.6.1
4.pip install spyder
5.if pip install tensorflow1.5.0:
      Autocomplete does not work in editor
if pip install tensorflow1.3.0:
      Autocomplete does  work in editor

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components
* Spyder Version:3.2.6
* Python Version:3.6.1
* Qt Version:5.10.0
* PyQt Version:5.10
* Operating system:Windows10

## Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. In general, given the problem occurred as a result of a specific, ``pip``-installed package, with the ever-problematic ``tensorflow``, on a ``pip`` install of Spyder, possibly involved Spyder's third party completion libraries, and in case was resolved by uninstalling said package, there really isn't going to be much of anything we can do about this from our end, sorry. Therefore, this issue will be closed. 

However, if you need additional help, please check out our autocomplete problems mega thread, issue #5782 , as well as [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections. Best of luck!
