### ISSUE TITLE
create exe failed

### ISSUE THREAD

**Issue by DingGY** [spyder-ide/spyder#6367]
I cant create exe

1. I have installed all the module of spyder
2. The spyder running successed by script
3. It will output the following when I execute the create_exe.py to create .exe file

$ python create_exe.py
Traceback (most recent call last):
  File "create_exe.py", line 53, in <module>
    create_executable()
  File "create_exe.py", line 32, in create_executable
    target_dir="%s-win32-%s-sa-%s" % (name, python_qt, ver))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36-32\lib\site-packages\guidata\disthelpers.py", line 384, in setup
    assert osp.isfile(script)
AssertionError

I see the value of script in assert osp.isfile(script) is "spyder/spyder"

* Spyder Version: 4.0.0.dev0
* Python Version: 3.6.1 32bit
* Qt Version: 5.9.3
* PyQt Version: pyQt 5.9.2
* Operating system: win7

I can't handle it。

**Comment by ccordoba12** [comment]
Please don't use create_exe. It's a file meant to be used only by us developers and it's broken right now.
