### ISSUE TITLE
Spyder won't launch after Installing Driver for USB 3.0 Docking Station

### ISSUE THREAD

**Issue by H4genT** [spyder-ide/spyder#6368]
## Description of your problem
Hi,
I am using Spyder through the WinPython-64bit-3.6.3.0Qt5 distribution. To add a third screen to my Laptop I started using a USB 3.0 Docking Station. After Installing the driver "Generic Driver for ThinkPad USB 3.0 Docks and Adapters" Spyder won't launch. Uninstalling the Driver fixes the problem, but my question is if this is a known issue and if there is a way to use both Spyder and the Docking Station.

**What steps will reproduce the problem?**

1. Install Generic Driver for ThinkPad USB 3.0 Docks and Adapters
2. Try to run Spyder

**What is the expected output? What do you see instead?**
I expect Spyder to launch. Instead the cursors changes to a loading symbol, after that nothing happens.

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Qt Version: 5
* PyQt Version: 5.9
* Operating system: Windows 7 Professional

If I need to provide any additional information please let me know.

Thank you
Hagen

**Comment by ccordoba12** [comment]
> I am using Spyder through the WinPython-64bit-3.6.3.0Qt5 distribution

Please report this problem with the WinPython guys:

https://github.com/winpython/winpython/

**Comment by H4genT** [comment]
I will do that, thank you for taking the time to answer my question!

**Comment by CAM-Gerlach** [comment]
Also, I previously used one of those things (DisplayLink) and the driver had a lot of known conflicts and problems on their side.
