### ISSUE TITLE
Spyder3 doesn't start

### ISSUE THREAD

**Issue by druizz90** [spyder-ide/spyder#6369]
## Description of your problem

I have a problem with Spyder3, I could worked with it perfectly two days ago. I have made in the command line" spyder3 --reset and the problem continues. When I start Spyder3 in the command line, y get this: 
File "/usr/lib/python3.6/site-packages/babel/dates.py", line 23, in <module>
    import pytz as _pytz
ModuleNotFoundError: No module named 'pytz'

I have installed this library, and I have reinstalled this library and spyder3 many times without success. If I open Python3 and I make "import pytz" I don't get any fail.

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6
* Qt Version: 5.9.1
* PyQt Version: 5.10
* Operating system: Linux (Fedora 27)

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

I can't start Spyder3, but this are my libraries from Python3:

alabaster (0.7.10)
altgraph (0.15)
asn1crypto (0.23.0)
astroid (1.6.1)
Babel (2.5.3)
bleach (2.1.2)
blivet (2.1.11)
blivet-gui (2.1.7)
Bottleneck (1.2.1)
cffi (1.10.0)
chardet (3.0.4)
cloudpickle (0.5.2)
coverage (4.4.2)
cryptography (2.0.2)
cupshelpers (1.0)
cx-Freeze (5.1.1)
cycler (0.10.0)
decorator (4.0.11)
docutils (0.14)
entrypoints (0.2.3)
et-xmlfile (1.0.1)
fros (1.1)
funcsigs (1.0.2)
future (0.16.0)
gpg (1.9.0)
html5lib (1.0.1)
idna (2.5)
imagesize (0.7.1)
iniparse (0.4)
initial-setup (0.3.51)
IPy (0.81)
ipykernel (4.8.0)
ipython (6.2.1)
ipython-genutils (0.2.0)
isc (2.0)
isort (4.2.15)
jdcal (1.3)
jedi (0.11.1)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-client (5.2.2)
jupyter-core (4.4.0)
langtable (0.0.38)
lazy-object-proxy (1.3.1)
macholib (1.9)
MarkupSafe (1.0)
matplotlib (2.1.2)
mccabe (0.6.1)
meld (3.18.0)
mistune (0.8.3)
mock (2.0.0)
nbconvert (5.3.1)
nbformat (4.4.0)
ntplib (0.3.3)
numexpr (2.6.1)
numpy (1.14.0)
numpydoc (0.7.0)
olefile (0.44)
openpyxl (2.4.9)
ordered-set (2.0.0)
pandas (0.20.1)
pandas-datareader (0.3.0.post0)
pandocfilters (1.4.2)
parso (0.1.1)
path.py (5.2)
pathlib2 (2.3.0)
pbr (3.1.1)
pefile (2017.11.5)
pep8 (1.6.2)
pexpect (4.3.1)
pickleshare (0.7.4)
pid (2.1.1)
Pillow (4.3.0)
pip (9.0.1)
ply (3.9)
prompt-toolkit (1.0.15)
psutil (5.4.3)
ptyprocess (0.5.2)
pwquality (1.4.0)
py (1.4.34)
pycairo (1.15.3)
pycodestyle (2.3.1)
pycparser (2.14)
pycups (1.9.72)
pycurl (7.43.0)
pydbus (0.6.0)
pyflakes (1.6.0)
Pygments (2.2.0)
pygobject (3.26.1)
PyInstaller (3.3.1)
PyIscsi (1.0)
pykickstart (2.41)
pylint (1.8.2)
PyOpenGL (3.1.0)
pyOpenSSL (17.2.0)
pyparsing (2.2.0)
pyparted (3.11.0)
PyQt5 (5.10)
PySocks (1.6.7)
pytest (3.2.3)
pytest-runner (2.9)
python-augeas (0.5.0)
python-dateutil (2.6.1)
python-dmidecode (3.12.2)
python-meh (0.43)
pytz (2017.3)
pyudev (0.21.0)
PyYAML (3.12)
pyzmq (16.0.4)
Qt.py (1.0.0)
QtAwesome (0.4.4)
qtconsole (4.3.1)
QtPy (1.3.1)
requests (2.18.4)
requests-file (1.4)
requests-ftp (0.3.1)
rope (0.10.7)
rpm (4.14.0)
scandir (1.3)
scipy (1.0.0)
sepolicy (1.1)
setools (4.1.1)
setuptools (38.4.0)
simplegeneric (0.8.1)
simpleline (0.6)
sip (4.19.7)
six (1.11.0)
slip (0.6.4)
slip.dbus (0.6.4)
snowballstemmer (1.2.1)
sos (3.5)
Sphinx (1.6.6)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
spyder (3.2.6)
SQLAlchemy (1.1.15)
SSSDConfig (1.16.0)
systemd-python (234)
tables (3.3.0)
testpath (0.3.1)
tornado (4.5.3)
traitlets (4.3.2)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5.1)
Whoosh (2.7.4)
wrapt (1.10.10)
xlrd (1.0.0)
xlwt (1.1.2)

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.
