### ISSUE TITLE
Feature: add lines to see where function,classes, loops start

### ISSUE THREAD

**Issue by Murmele** [spyder-ide/spyder#6373]
Hello,
in python I think sometimes it is hard to see, where a function, class, if or for loop ends. To solve this problem, it would be nice it is possible to implement something like in the picture below. So you see every time where you have to start to write. Is it possible to implements something like this?

Best regards,

Martin

![pic1](https://user-images.githubusercontent.com/10099533/35757378-0c00f498-086f-11e8-8d55-3f6cda0515de.png)

**Comment by bcolsen** [comment]
Spyder 4 pretty much has this feature when you turn on indent visualization.

![screenshot from 2018-02-02 16-20-12](https://user-images.githubusercontent.com/10513354/35759194-4a1db3ea-0835-11e8-95f7-db0c7c7ae93e.png)
 
It doesn't really end the lines until the start of the next indented text (i.e. It draws vertical lines over blank lines at the end of a function). Unfortunately, I think that's all the python interpreter is looking for to find the blocks.  I guess you could find the end of the block and not draw the lines on the blank lines.

**Comment by ccordoba12** [comment]
Yep, this is already implemented in our master branch and it'll be part of Spyder 4.
