### ISSUE TITLE
Showing warning sign even if nothing's wrong

### ISSUE THREAD

**Issue by yomoko** [spyder-ide/spyder#6387]
Hi, spyder is showing this warning sign![image](https://user-images.githubusercontent.com/33768560/35812398-d22a180c-0a5e-11e8-9f4f-fc6e91992316.png) and says 'variable' may be undefined, or defined from start imports: file name, when actually there is nothing wrong. Also it underlines all the variables which are imported from another file, that's not very good because it will be messed up with real error. Is there any way to fix that? Thanks

**Comment by ccordoba12** [comment]
That's just a warning. You can ignore it if you want.

> Is there any way to fix that?

You can disable these warning in

    Tools > Preferences > Editor > Code Introspection/Analysis > Real-time code analysis.
