### ISSUE TITLE
Spyder has encountered a problem

### ISSUE THREAD

**Issue by OUTmanzhou** [spyder-ide/spyder#6391]
![default](https://user-images.githubusercontent.com/36190904/35854316-044ae994-0b6b-11e8-9baf-9d443d84ddb5.PNG)
install spyder with python3.6
When I open spyder,it will look like that.Did i miss some moudle?

**Comment by ccordoba12** [comment]
Please press the button *Submit to Github* to open an issue about the problem you're having here.
