### ISSUE TITLE
Mouse cursor issue with PyQt 5.10

### ISSUE THREAD

**Issue by farameris** [spyder-ide/spyder#6393]
## Description

**What steps will reproduce the problem?**

1. Push Ctrl key on keyboard
2. Put mouse cursor over any variable: mouse cursor changes from "text select" to "link select"
3. Release Ctrl key on keyboard

**What is the expected output? What do you see instead?**

The mouse cursor should change back to "text select" after releasing the Ctrl key but doesn't !
Same problem when saving file : "text select" cursor goes to "busy" pointer but doesn't go back to "text select" when the saving action is finished. 

**Please provide any additional information below**

I have to get the mouse cursor out of the editor to get back the normal "text select" cursor.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.10 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by CAM-Gerlach** [comment]
As a note, I was unable to reproduce this on Windows 8.1 with Spyder 3.2.6 and Python 3.6.4. Major difference is I was using the standard Qt/PyQt 5.6.2/5.6, while you're using the newer Qt/PyQt 5.10.

**Comment by sylvain-bougnoux** [comment]
Same issue with master release (at least 2 days ago).
With ctrl+S (save the editor). The cursor turns to disk-like and keeps into that state until it moves outside the editor. 
PyQt 5.10 as well. Win10.

**Comment by ccordoba12** [comment]
This has to be an issue with PyQt 5.10 for sure, so we're going to pin pyqt5 to 5.9.2 in our wheels. There has been several reports that things are failing strangely with 5.10.

For now, please downgrade to 5.9.2 manually.

**Comment by farameris** [comment]
Downgrading to 5.9.2 worked for me ! Thanks !

**Comment by stonebig** [comment]
PyQt-5-5.10.1 is out. Maybe a few bugs are corrected now.

**Comment by farameris** [comment]
Just tried PyQT-5-5.10.1, the bug about no update of mouse icone is corrected ! Good to go in spyder official wheels ;-)

**Comment by CAM-Gerlach** [comment]
I believe there may have been some additional issues besides this, though?

**Comment by farameris** [comment]
You are right, last com modified !

**Comment by fccoelho** [comment]
I am still having mouse issues on PyQT 5.12 (Ubuntu eoan)
