### ISSUE TITLE
Python Spyder 3 Crashing upon Startup

### ISSUE THREAD

**Issue by psppb** [spyder-ide/spyder#6394]
When I launch Spyder 3 from Winpython it creats a completely blank white screen and then an editor window in the middle that has no drop down menus. The computer I work on just had a Windows 10 update 

**What steps will reproduce the problem?**

1. Tried to Re-install it. Same issue
2. Someone on a forum told me to delete temp.py and that did not work
3.  Tried Resetting spyder.exe

**What is the expected output? What do you see instead?**
Same output nothing changes 

**Please provide any additional information below**

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please report this error with the WinPython guys:

https://github.com/winpython/winpython/
