### ISSUE TITLE
Python Spyder will not work in extended displays

### ISSUE THREAD

**Issue by psppb** [spyder-ide/spyder#6395]
Python Spyder works in my laptops main display but as soon as I drag it to my third or second display It crashes. I updated the software on the dock but it still does not work. 

**What steps will reproduce the problem?**

1. Opened Python Spyder in main display on laptop
2.  Dragged it to display #2 
3.  Entire thing crashes (no mouse no cursor) Drag it back and it works fine

**What is the expected output? What do you see instead?**
Yesterday it worked on all three displays 

**Please provide any additional information below**
Stupid Windows update ran last night 

## Versions and main components

* Spyder Version: 3.2
* Python Version: 3.6
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
Please report this problem with the WinPython guys. This is not a Spyder problem but a Qt/PyQt one (these are the graphical libraries used by Spyder).

**Comment by CAM-Gerlach** [comment]
Indeed. I do this dozens of times every day on a number of different machines, and have never had a problem.
