### ISSUE TITLE
Python process icon appears when launching Spyder

### ISSUE THREAD

**Issue by shreyas707** [spyder-ide/spyder#6396]
When I go to Preferences > IPython Console > Graphics and select Automatic under Graphics Backend to render the graphs of matplotlib in a separate window, I see a python process icon (completely white) in my dock. This didn't occur when I selected Inline instead of Automatic.
For this icon to go away, I have to delete the .ipython hidden folder from my Users folder. After doing that, with inline or any other option, this doesn't appear. But as soon as I select Automatic, I see this icon appearing again.

If I force close the icon, I see an error message in ipython console and the kernel restarts and the icon appears again. I think this has something to do with the Automatic setting. This doesn't happen on Windows as I have tried it on a friend's laptop. Unfortunately, I don't have access to another Mac to try this out.

I don't want to see this icon as it is redundant. Is there any quick fix for this?

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: 3.6.4
* Qt Version: 5.10.0
* PyQt Version: 5.10
* Operating system: MacOS High Sierra 10.13.3

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
> I don't want to see this icon as it is redundant. Is there any quick fix for this?

This is a known issue in macOS, it happens because IPython creates a thread to make external plots on an external window, and it's not something we can fix in Spyder.

@minrk, do you know a workaround for this?

**Comment by minrk** [comment]
I don't know a way to prevent qt from registering an app icon. FWIW, using the native backend doesn't seem to have this issue: `%matplotlib osx`

**Comment by shreyas707** [comment]
Oh alright. Well that's ok. I'll just use the native backend then. 
Thank you so much guys! Really appreciate your work :) Love the IDE!

**Comment by ccordoba12** [comment]
Thanks Min! Closing then :-)
