### ISSUE TITLE
spyder-notebook not working on Macbook

### ISSUE THREAD

**Issue by uniele** [spyder-ide/spyder#6398]
## Description

**What steps will reproduce the problem?**

1. Install the plugin by "conda install spyder-notebook -c spyder-ide"
2. Spyder shows up but notebook button doesn't. 

**What is the expected output? What do you see instead?**

![image](https://user-images.githubusercontent.com/13804769/35902726-a78540a0-0c1f-11e8-93aa-cb1b1a2e01a3.png)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.10.0, PyQt5 5.10 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by BjornFJohansson** [comment]
might have have this problem as well, I think that the spyder-notebook started complaining when I installed jupyter extensions. Not sure if that make sense.

**Comment by BjornFJohansson** [comment]
removed spyder-notebook with:
`conda remove spyder-notebook`
and now spyder starts again.

**Comment by ccordoba12** [comment]
Thanks for reporting. Moving this to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #142](https://github.com/spyder-ide/spyder-notebook/issues/142) via [**ZenHub**](https://www.zenhub.com/)
