### ISSUE TITLE
Are copy line/duplicate line shortcuts working on Linux ?

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#641]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-04-25T04:59:16Z_

Apparently they aren't working on Ubuntu.
(Ctrl+Alt+Up/Down)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=641_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-05-16T01:31:11Z_

**Labels:** Cat-Settings

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-08T00:56:33Z_

This issue was closed by revision 8412d0fbbbea .

**Status:** Fixed

**Comment by bhishanpdl** [comment]
I am also having the same problem on Mac.
Given shortcut in preferences is opt-shf-up, however, it did not work.

In fact nothing works. I tried multiple cominations like:
opt-shf-up
ctrl-shf-up
cmd-shf-up

None of them works.

Has anybody successfully duplicated a line in spyder editor on Mac ?
