### ISSUE TITLE
Suggestion Concerning Formatting of Decorators

### ISSUE THREAD

**Issue by GalacticStarfish** [spyder-ide/spyder#6419]
## Suggestion Concerning Formatting of Decorators

Consider the following of, albeit incorrect, code:

`@decorator_name additional_text`

Note the space character between `decorator_name` and `additional_text` Currently, Spyder formats the entire line in brown italicized text, instead of only applying special formatting to the decorator.

The line of code given earlier is invalid. As such, I understand why the text-formatting appears strange. However, and IDEs are primarily used for looking at code which contains mistakes. As such, it makes sense for the Spyder IDE to be able to nicely color and italicize code that is not syntactically perfect.

It would be more visually apparent if `decorator_name` and `additional_text` were formatted differently. It's more difficult to gloss over the space character in-between the two strings if they are different colors.

Currently, Spyder formats the entire line in brown italicized text. My suggestion is that only the first part of the line, read up until the first white space char, use the special decorating formatting (brown italicized text). The remainder of the line can be displayed using default formatting (usually black, non-italic).

Interestingly, two or more one space chars separating the strings does produce the behavior I am recommending.

## Versions and main components

* Spyder Version: 3.1.4
* Python Version: 3.6.1 64bits
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Windows 7 64-bit

## Dependencies

jedi >=0.9.0     :  0.10.2 (OK)
matplotlib >=1.0 :  2.0.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed report. I just tested it in Spyder 3.2.6, and the behavior you suggested is in fact what I see—just the @decorator is brown, and any additional words with spaces are the normal text color. As your version of Spyder is very out of date (and your Python version and some other deps could use an update), please update to the latest version. 

Using conda, I'd recommend
```
conda update conda
conda update anaconda
conda update python
conda update spyder
```
in that order. Unless it reoccurs, in which case it may be a bug and you should reopen it, this issue will be closed. Thanks.
