### ISSUE TITLE
ImportError: No module named 'spyderlib'

### ISSUE THREAD

**Issue by ZZshengyeah** [spyder-ide/spyder#6425]
## Description of your problem
I can not open spyder3 in my terminal and I got the error " ImportError: No module named 'spyderlib' "
**What steps will reproduce the problem?**

1. open spyder3
2. 
3. 

**What is the expected output? What do you see instead?**
Traceback (most recent call last):
  File "/usr/bin/spyder3", line 2, in <module>
    from spyderlib import start_app
ImportError: No module named 'spyderlib'

**Please provide any additional information below**
My spyder2 is right, but I can not open spyder3, and I have reinstalled it.

## Versions and main components

* Spyder Version:
* Python Version:
* Qt Version:
* PyQt Version:
* Operating system:

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

**Comment by ccordoba12** [comment]
It seems you're using your package manager to install Spyder, and it's providing you a very old version of Spyder (more than three years old now).

Unfortunately, we don't support that version anymore. Our recommendation is to download and install Anaconda instead, with which you can always have the latest Spyder version.

**Comment by ZZshengyeah** [comment]
Thanks. I have installed Anaconda, and it worked, but the PATH is supposed to be setted. And I am trying to solve it.
