### ISSUE TITLE
Editor Loading Issue

### ISSUE THREAD

**Issue by cagostino** [spyder-ide/spyder#6436]
## Description

1. One of my scripts encountered an error and I clicked the hyperlink in the ipython console to the script that was causing the problem. The file opened up after ~5 seconds(slowly) and then Spyder popped up a message suggesting I submit this as an issue to github so I decided to. Not sure what the error is but I figure it may make some more sense to you all.

**What is the expected output? What do you see instead?**
Not sure what the expected output  should be or what exactly went wrong.

  File "C:\Users\Chris\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1370, in close_file
    self.remove_from_data(index)
  File "C:\Users\Chris\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1160, in remove_from_data
    self.data.pop(index)
IndexError: pop index out of range

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. In a test file, I stuck in a few lines of code, had it ``raise`` an ``Exception``, ran the file with "Run file", and then clicked the link in the Console. However, the file opened right away (whether it was open or closed), and I wasn't able to reproduce the error. Therefore, we'l likelyl need to know a little more from you to see if we can reproduce it so it can be fixed.

Can you consistently reproduce it with that specific file, or does it not reoccur when you try it? If it does, does it happen with any file you click the link to (you can create a test file to find out)? Or only that one? You should also update Python, IPython, qtconsole and Spyder just to make sure as your current versions are a bit out of date, with
```
conda update conda
conda update anaconda
conda update python
conda update spyder
 ```

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. Please reopen if you can provide more details; thanks.
