### ISSUE TITLE
ValueError when closing a file whose folder changed name in File Explorer

### ISSUE THREAD

**Issue by yulkang** [spyder-ide/spyder#6445]
## Description

**What steps will reproduce the problem?**

1. Open files in the editor.
2. Rename folders containing the files in File Explorer.
3. When a dialog box asks "Do you want to close ...?", select "Yes".

**What is the expected output? What do you see instead?**

I expect the files to be closed. (Or even better, the relocation inside File Explorer to be recognized so that I don't need to close and open the files again manually.)

Files are closed, but Spyder raised an exception. It didn't crash though.

**Please provide any additional information below**

  File "/Users/yulkang/anaconda/envs/python3/lib/python3.5/site-packages/spyder/plugins/editor.py", line 1364, in close_file_in_all_editorstacks
    index = editorstack.get_index_from_filename(filename)
  File "/Users/yulkang/anaconda/envs/python3/lib/python3.5/site-packages/spyder/widgets/editor.py", line 1384, in get_index_from_filename
    return filenames.index(filename)
ValueError: '/Users/yulkang/PATH_BEFORE_RENAMING/main_est_p.py' is not in list

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.5.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.1 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this problem in a future release.

**Comment by csabella** [comment]
The issue with this is that rename was only defined for files and not directories.  The pull request corrects that by iterating over all open files to check if they are in the renamed directory.
