### ISSUE TITLE
test_completions_custom_path fails with jedi 0.9.0 (Spyder 3)

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#6447]
The `test_completions_custom_path` fails if jedi 0.9.0 is installed and succeeds with jedi 0.10.2. This test was introduced in PR #4962 by @rlaverde to fix #4410, a bug with code completion. As I understand it, the feature that the test is written for requires jedi 0.10.0 or higher. Spyder only requires jedi 0.9.0. This affects both the `master` and the `3.x` branch.

One possible solution is to the test if jedi 0.9.x is installed. This is done with another test in the same PR.

Alternatively, we could require jedi 0.10.0. This would simplify our code base and ensure that everybody profits from the bug fix (the original bug seems to have taken quite some effort to be tracked down). For the record, jedi 0.10.0 was released February 2017 on PIP and May 2017 on conda.

We could also take the first approach for Spyder 3.x and the second approach for Spyder 4.x. Bumping the requirement in a minor release is perhaps too big a change in this case.

Suggestions?

**Comment by ccordoba12** [comment]
> The test_completions_custom_path fails if jedi 0.9.0 is installed and succeeds with jedi 0.10.2

We need to demand 0.10 for that test. The requirement to use custom paths with Jedi 0.10+ is already in our code.

> We could also take the first approach for Spyder 3.x and the second approach for Spyder 4.x

Yep, since 3.x is maintenance, we can't bump the minimal Jedi version to 0.10, but we can do that for 0.4. I think we could even use 0.11 to remove other patches as well.

**Comment by CAM-Gerlach** [comment]
Oops, sorry for the mess above.

BTW, I know that the ever-troublesome ``test_introspection`` in ``test_editor_introspection`` also requires jedi 0.9.0 (by the way, the latter has been failing for at least a couple weeks now, but as it doesn't run on our CIs I've just been manually skipping it locally until my key work items for 3.2.7 are complete).

**Comment by ccordoba12** [comment]
> the latter has been failing for at least a couple weeks now

It's passing for me locally in Python 3 and PyQt5.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Ah, looks like your just-merged #6433  fixed it. Thanks!

**Comment by jitseniesen** [comment]
> Yep, since 3.x is maintenance, we can't bump the minimal Jedi version to 0.10, but we can do that for 0.4. 

Okay, I'll prepare two separate PRs.

**Comment by jitseniesen** [comment]
I created issue #6474 so that I don't forget about the second PR.
