### ISSUE TITLE
Setting a path containing a single quote

### ISSUE THREAD

**Issue by pcw00** [spyder-ide/spyder#6451]
## Description
(I'm new to both Python and Spyder, so I apologise if my terminology isn't correct)
Spyder 3.2.6 is unable to pass paths for working directories that contain a single quote to the IPython interpreter. I use my uni OneDrive account which has a single quote in the path that I cannot change.

**What steps will reproduce the problem?**

1. Click on the folder icon at the top right of the title bar (Windows 10).

2. Select a path with a folder containing a single quote, e.g. 
C:\Users\xxxx\OneDrive - Queen's University Belfast\test

3. IPython console throws an error. If I copy and paste the command shown in the error message then either (i) escape the single quote or (ii) change the path string to being enclosed in double quotes, it seems to work--e.g.:
get_ipython().kernel.set_cwd(u'C:\\Users\\xxxx\\OneDrive - Queen\'s University Belfast\\test')
(N.b. there is a backslash before the single quote in "Queen's" in the line above--it seems to get stripped by the webpage "Queen\\'s")
OR
get_ipython().kernel.set_cwd(u"C:\\Users\\xxxx\\OneDrive - Queen's University Belfast\\test")

**What is the expected output? What do you see instead?**
  File "<ipython-input-4-523d9ca4caac>", line 1
    get_ipython().kernel.set_cwd(u'C:\\Users\\xxxx\\OneDrive - Queen's University Belfast\\test')
                                                                     ^
SyntaxError: invalid syntax

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this problem in a future release and sorry for the inconvenience in the meantime.

**Comment by csabella** [comment]
I wasn't sure how to create a test for this, but I was able to recreate it.  With the patch in place, the output in the console looks like:
```
In [1]: import os

In [2]: os.getcwd()
Out[2]: "/home/cheryl/spyder/cheryl's"
```
This output cannot be created without the patch.

**Comment by pcw00** [comment]
Many thanks, it’s working now in 3.2.8

Paul
