### ISSUE TITLE
Spyder Notebook Crashes

### ISSUE THREAD

**Issue by anthoniraj** [spyder-ide/spyder#6456]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/anthoniraja/.virtualenvs/venvdemo/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 377, in close_client
    self.clients.remove(client)
ValueError: list.remove(x): x not in list

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.10 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Moving this to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #144](https://github.com/spyder-ide/spyder-notebook/issues/144) via [**ZenHub**](https://www.zenhub.com/)
