### ISSUE TITLE
Editor's split view tabs mirror each other

### ISSUE THREAD

**Issue by homocomputeris** [spyder-ide/spyder#6466]
## Description

I don't know if it's a bug or a feature

**What steps will reproduce the problem?**

1. Open some files
2. Split editor
3. Close a file on the left, for example

**What is the expected output? What do you see instead?**
I expect to see, let's say, file1 on the left and file2 on the right.
But Editor closes the same file in both split tabs. And opens a new file in both of them.
At least you can show different files in each tab, but this behaviour is still counter intuitive. The good old Far Manager, for example, easily shows two independent panes.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.10.1, PyQt5 5.10 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by homocomputeris** [comment]
![spyder_tabs](https://user-images.githubusercontent.com/7422433/36308175-ca784c18-131f-11e8-8d02-97f4a599362a.png)

**Comment by ccordoba12** [comment]
> I don't know if it's a bug or a feature

This is a feature, i.e. how things work in Spyder right now. I really don't find counter intuitive, and as far as I recall, you're the first to complain about it.

**Comment by jitseniesen** [comment]
Issue #5739 seems quite similar.

**Comment by ccordoba12** [comment]
Maybe @homocomputeris would like to take a look at it.

**Comment by homocomputeris** [comment]
@ccordoba12 @jitseniesen I think it's the same.
It is counter-intuitive for me because I have no idea why the panes _should_ mirror each other.
For example, I can have two independent windows with completely independent tabs in a browser, in Far Manager, in PyCharm, in Atom, in SublimeText. Or I can open the same files in both panes if I want. Anywhere but Kate and Spyder 😄

**Comment by CAM-Gerlach** [comment]
@homocomputeris Well, as @ccordoba12 said you're welcome to take a crack at changing this in a PR, and we'll certainly at least consider it. While I can see advantages of both approaches from  Ux perspective, if given the choice the "independent" approach (with e.g. a context menu or modifier-key option to clone the tab to the other view) would get my vote as well personally, all else equal, but thus far its not been a big enough issue to implement.
