### ISSUE TITLE
Variable explorer PIL image error

### ISSUE THREAD

**Issue by Lewn** [spyder-ide/spyder#6467]
## Description
I'm not sure what happened, but the error below was produced, I am not able to reproduce it...
The error popped up as I closed a PIL image from the variable explorer

**What steps will reproduce the problem?**
I'm not able to reproduce the problem

**What is the expected output? What do you see instead?**
The window closed, as expected, but the error window also popped up, with the following error.

**Please provide any additional information below**

  File "C:\Users\USER\AppData\Local\conda\conda\envs\py36_forge\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 524, in <lambda>
    lambda eid=id(editor): self.editor_accepted(eid))
  File "C:\Users\USER\AppData\Local\conda\conda\envs\py36_forge\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 546, in editor_accepted
    self.set_value(index, conv_func(value))
  File "C:\Users\USER\AppData\Local\conda\conda\envs\py36_forge\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 461, in <lambda>
    conv_func = lambda arr: Image.fromarray(arr, mode=value.mode)
AttributeError: type object 'Image' has no attribute 'fromarray'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4

**Comment by CAM-Gerlach** [comment]
Thanks for the report. While it may be possible for someone (wiser than I) to guess at what's going on, truth be told we are unlikely to be able to fix this without being able to reproduce it. We've seen this a few times before, but in each case the poster never followed up explaining how it happened, and thus their issue got closed after a week/7 days as this one likely might be. By any chance were you using ``tkinter`` at any point?

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.

**Comment by Lewn** [comment]
As far as I know I was not using `tkinter` at any point. I was using the `conda-forge` windows installation. I agree that it will be difficult/almost impossible to fix this without being able to reproduce it. I mainly thought that if other people where experiencing similar issues, there might be a pattern.

**Comment by CAM-Gerlach** [comment]
Thanks. Hopefully, it doesn't happen again...
