### ISSUE TITLE
Failed to open file: /tmp/.gln1VlUe (deleted)

### ISSUE THREAD

**Issue by mjlbach** [spyder-ide/spyder#6471]
## Description of your problem
Spyder keeps querying for a non-existent temporary file
[0217/012305.088782:WARNING:stack_trace_posix.cc(648)] Failed to open file: /tmp/.gln1VlUe (deleted)

**What steps will reproduce the problem?**

1.  Install python 3.6.3
2.  Install spyder in a virtual environment using pew or venv
3.  Start spyder

**What is the expected output? What do you see instead?**

Spyder launches, just reporting the error since I couldn't find any mention of this in the closed issues or on the google group.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.6
* Python Version: 3.6.3
* Qt Version: 5.9.1
* PyQt Version: PyQt 5.10
* Operating system: Ubuntu 17.10

## Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. As you state, I can't find any issues that appear to be similar. However, from your description, it sounds like you're installing Spyder via the "expert" method using ``pip`` or your distribution's Python, but as our readme, install instructions and documentation states, due to limited resources and the many potential ``pip``-falls of that approach, we are unable to provide individual support for installation-related problems (as this appears to be), and recommend you install the Anaconda distribution instead.

You can try resolving this by reinstalling, manually creating the file, or restting Spyder's configuration with ``spyder --reset``. Also, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

If you complete all of that and have reason to believe it is related to Spyder itself and not your installation, then please post the information requested in the guide here. Otherwise, or if we can confirm it is an installation issue, this issue will be closed after one week (7 days). Thanks, and best of luck!

**Comment by mjlbach** [comment]
Fortunately it doesn't interfere with using spyder. I did try both I tried modifying the source code in the MainWindow class to eliminate temp file loading but it didn't alleviate the problem.  I've also tried the suggested troubleshooting steps in the Troubleshooting guide First Aid/CPR sections to no luck. If I can figure out a fix/modification on my own I will post. Otherwise is there any additional information I should post for future reference?

**Comment by CAM-Gerlach** [comment]
Thanks for the followup

>  is there any additional information I should post for future reference?

I'm still unclear on exactly what specific symptoms you're experiencing. In what form are you receiving the above error message—in a "Report Error" dialog, in a warning popup, in the console or how? Is that the exact and complete message? At what point in Spyder startup does it occur? Does it only happen in a virtual environment? Do you see any pertinent output when running with ``spyder --debug`` or setting the environment variable SPYDER_DEBUG=3 and then running Spyder from the same command prompt, as the guide suggests?

If you could describe your circumstances in more detail, and post the remaining information listed under the [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the guide, that would be helpful as well. It still seems likely to have something to do with your specific ``pip`` manual install, but this should hopefully at least help us narrow that down or not, and if you have a proper fix then we would be glad to review a PR if it really is an issue on the Spyder side. Thanks.

**Comment by mjlbach** [comment]
Sorry about that, I thought I included everything under the troubleshooting guide in my initial post. 


```
(spyder) ➜  ~ export SPYDER_DEBUG=3
(spyder) ➜  ~ spyder3
Start of MainWindow constructor
End of MainWindow constructor
*** Start of MainWindow setup ***
  ..core actions
  ..toolbars
  ..tools
  ..sift?
  ..plugin: internal console
    ..internal console: initializing
  ..plugin: working directory
Loading help...
**[0218/115843.159710:WARNING:stack_trace_posix.cc(648)] Failed to open file: /tmp/.glRW0ytz (deleted)**
  Error: No such file or directory
Loading outline explorer...
Loading editor...
Introspection Plugin Loaded: rope
Introspection Plugin Loaded: jedi
Introspection Plugin Loaded: fallback
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x7fb39831c5e8>
current_changed: 0 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x7fb39831c5e8> 140409329272296
Added thread <spyder.widgets.editor.AnalysisThread object at 0x7fb398264b88> to queue
Added thread <spyder.widgets.editor.AnalysisThread object at 0x7fb398264ca8> to queue
  ..widgets
Loading file explorer...
Loading history plugin...
Loading online help...
Loading project explorer...
Loading namespace browser...
Loading IPython console...
Updating queue:
    started: 0
    pending: 2
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x7fb398264b88>
Updating queue:
    started: 1
    pending: 1
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x7fb398264ca8>
Setting up main window...
Updating queue:
    started: 0
    pending: 0
Updating queue:
    started: 0
    pending: 0
Setting up window...
*** End of MainWindow setup ***
Call to 'close_threads'
Initialized fallback
setfocusto: <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x7fb39825e828>
current_changed: 0 <spyder.widgets.sourcecode.codeeditor.CodeEditor object at 0x7fb39825e828> 140409328494632
Added thread <spyder.widgets.editor.AnalysisThread object at 0x7fb3d49ffca8> to queue
Added thread <spyder.widgets.editor.AnalysisThread object at 0x7fb3d4a011f8> to queue
Updating queue:
    started: 0
    pending: 2
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x7fb3d49ffca8>
Updating queue:
    started: 1
    pending: 1
===>starting: <spyder.widgets.editor.AnalysisThread object at 0x7fb3d4a011f8>
Updating queue:
    started: 1
    pending: 0
Updating queue:
    started: 0
    pending: 0
Initialized jedi
Initialized rope

```

**Comment by CAM-Gerlach** [comment]
Sorry for the delay following up. I can't be sure precisely what causes this, though likely a more experienced hand here does, but I'm surprised that ``spyder --reset`` doesn't fix it. It can be isolated to something between the start of loading the help plugin and the start of loading the outline explorer, possibly in the ``Help`` class (in ``spyder/plugins/help.py``) ``__init__`` method (or possibly its ``register_plugins`` method), if you'd like to look. However, it seems system specific and is only a warning, so I'm not sure I'd worry about it too much...

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by ccordoba12** [comment]
It doesn't seem related to Spyder.

**Comment by epifanio** [comment]
Just a note, googling for the same error I ended up here. 
In my case it has nothing to do with Spyder, in my case it was an issue on the PyQt5 side and opengl version installed by mesa which was in conflict with the one installed by the nvidia drivers.
Removing the affected files fixed the issue for me.

**Comment by ccordoba12** [comment]
Thanks for letting us know @epifanio!

**Comment by caidish** [comment]
> Just a note, googling for the same error I ended up here.
> In my case it has nothing to do with Spyder, in my case it was an issue on the PyQt5 side and opengl version installed by mesa which was in conflict with the one installed by the nvidia drivers.
> Removing the affected files fixed the issue for me.

I encounter the exact same problem. Could you describe the detail 'removing the affected files xxx'  for me? I appreciate it if you can offer any help.
