### ISSUE TITLE
Displaying image

### ISSUE THREAD

**Issue by paulmcolaka** [spyder-ide/spyder#6472]
## Description

![tree2](https://user-images.githubusercontent.com/28704381/36341114-51c116fc-13fa-11e8-8d89-7d9f8764452b.jpg)

Initially it was displaying an image and then later I get a pop up that I need to come here 
**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Paul\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Users\Paul\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 134, in _handle_execute_result
    png = decodestring(data['image/png'].encode('ascii'))
  File "C:\Users\Paul\Anaconda3\lib\base64.py", line 561, in decodestring
    return decodebytes(s)
  File "C:\Users\Paul\Anaconda3\lib\base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. It seems like the error is likely to be either with the ``qtconsole`` package, or perhaps an (uncaught) exception related to a problem with the image itself. Can you try the same steps you did here with a bare ``qtconsole`` (launch from Anaconda Navigator or ``jupyter qtconsole`` from the Anaconda Prompt) and see if the problem reoccurs? If so, you should report over at that repo instead. Also, does it only happen with this particular image, with any of a certain type, or with any arbitrary one? If the former, can you provide us the image to try to reproduce it? Thanks.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response.
