### ISSUE TITLE
Spyder doesn't recognize TensorFlow GPU

### ISSUE THREAD

**Issue by alenashilina** [spyder-ide/spyder#6475]
Hello.

So I spent a good amount of time installing and tuning TensorFlow GPU version.

And through Anaconda prompt it works perfectly. 

I run this piece of code to check if I can use GPU:
```
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```
And it gives me the result:

```
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 11171278383842874612
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 3238717030
locality {
  bus_id: 1
}
incarnation: 17164589319225185596
physical_device_desc: "device: 0, name: GeForce GTX 960M, pci bus id: 0000:01:00.0, compute capability: 5.0"
]
```
However if I run it in Spyder I'm getting that I can only use my CPU:

```
[name: "/cpu:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 18858102688050260
]
```
I tried to open Spyder through the environment, since it's the only suggestion I could find on the Internet. Like
```
activate tensorflow
spyder 
```
But still it shows I can use only CPU. 
I also tried to update the spyder... still no luck. Spyder refuses to see that I can use GPU.
What the trick can be? How can I make Spyder see the GPU

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Perhaps the problem has to do with Tensorflow and IPython, since that's the interpreter Spyder is running your code in? Please try in a standard IPython shell from the Anaconda prompt (and if it does work, a bare ``qtconsole`` instance with ``jupyter qtconsole``); if it doesn't work in either, then the problem lies with them rather than with Spyder and you'll want to report it to that repo instead.

**Comment by CAM-Gerlach** [comment]
Also, just to be sure, make sure you update Python, IPython etc with

``conda update conda``
``conda update anaconda``
``conda update python ipython``

in ``base`` and the environment you installed tensorflow into. Also, IIRC, the tensorflow ``conda`` environment is old and not well supported, if I'm remembering that right.

**Comment by alenashilina** [comment]
I have just reinstalled everything from the scratch (starting with anaconda). Then spyder refused to see firstly tensorflow, then keras, then pillow... Then I reinstall those several times, and opened spyder under tensorflow environment.. Somehow it works now.

**Comment by CAM-Gerlach** [comment]
Thanks, and glad you got it working.

**Comment by wentinghome** [comment]
My Spyder also doesn't use GPU. But if I opened terminal from anaconda, and use "python myfile.py", the program runs on GPU. Do you have any suggestions besides re-installation? Thanks a lot.

**Comment by CAM-Gerlach** [comment]
Did you read through and follow the relevant [guide](https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder) on working with packages and environments in Spyder? Could be due to different working environments in Spyder vs. Anaconda Prompt (which I'm guessing is what you are referring to when you say "Terminal from Anaconda").

**Comment by Ehteshamciitwah** [comment]
Hello,
I installed tensorflow gpu 2.5 and it will automatically install Cuda and cudnn. I install jupyter and check the config devices and it is showing both CPU and GPU. But when I want to try on spyder. spyder is not detecting GPU. Is there any problem of TensorFlow 2.5 with spyder. Need Suggestion. Thank you
