### ISSUE TITLE
admin right needed now?

### ISSUE THREAD

**Issue by randomgambit** [spyder-ide/spyder#6483]
Hello there!

I am using Anaconda 5.0.1 on windows 10. and I noticed that running `conda update conda` will fail without admin rights. It used to be the case I was able to run all the conda update suite (-anaconda, -conda, -all) without admin rights. 

Is this expected? 

Thanks for your help

**Comment by ccordoba12** [comment]
This is an Anaconda problem. Please report it in its appropriate place:

https://github.com/ContinuumIO/anaconda-issues/issues/
