### ISSUE TITLE
"Submit to Github" Bug-Report Button triggers a failing file download instead of submitting a bug

### ISSUE THREAD

**Issue by ventilator** [spyder-ide/spyder#6494]
## Problem Description

I want to submit a bug to Github via "Submit to Github" Button when spyder crashes

### What steps will reproduce the problem?

1.  Spyder crashed due to ipython error
2.  Click Submit to Github button (see screenshot)
3.  Firefox/IE is opened, tries to download a file which does not exist (ofc) instead to submit a bug

### What is the expected output? What do you see instead?

I want firefox to open the github bug submission page

### Paste Traceback/Error Below (if applicable)

![grafik](https://user-images.githubusercontent.com/4276067/36542474-2f30a978-17e1-11e8-9204-8e42a3c8326a.png)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.4
* Python: Winpython 32bit-3.6.3.0Qt5
* Qt:5
* PyQt:
* Operating System: Win10 64bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks @ventilator for your report. To avoid this sort of problems we rewrote from scratch the way Spyder sends reports to Github. This new work will be available in our 3.2.7 version, to be released in a couple of days.

For now, please use the latest WinPython version. The error you want to report was already fixed on it.

**Comment by CAM-Gerlach** [comment]
Fixed in #5346 , for reference.
