### ISSUE TITLE
is there a way to maximise each pane on a different monitor?

### ISSUE THREAD

**Issue by randomgambit** [spyder-ide/spyder#6498]
Hello,

Sorry is this is an obvious question, but I have two monitors and I would like to use one of them for scripting, and the other to show the ipython console.

I was only able to detach the console manually, move it to the other screen, can kind of enlarge it manually to fit my screen. Is there some setting that does that automatically? I do not see a full-screen button on the ipython console.

Thanks!

**Comment by ccordoba12** [comment]
This is already fixed in our master branch and it'll be part of Spyder 4. When you detach a pane, it's added to its own window and so it can be easily moved to different monitors.

I think we still have to make shortcuts to work between windows, but that's going to be worked out before we release Spyder 4.

**Comment by randomgambit** [comment]
ok cool. yes something a bit annoying is the following. say you have the main Spyder window on one screen and the console on another. if you select some code and hit F9, then the cursor moves to the console. so that I need to manually click back on the main screen to edit my code again....
is spyder 4 already on conda?
thanks!

**Comment by ccordoba12** [comment]
We don't know when Spyder 4 is going to be released, most probably in H1 of 2019.

**Comment by randomgambit** [comment]
woooooooot 😅 but you said this is fixed already on the master branch. is it for spyder 3? does that fix the annoying cursor switch issue?
thanks!!

**Comment by ccordoba12** [comment]
> woooooooot

Well, please see: https://github.com/spyder-ide/spyder/wiki/Anaconda-stopped-funding-Spyder

> is it for spyder 3?

Nop, Spyder 3 is in maintenance now, so it receives minor features and bugfixes.

> does that fix the annoying cursor switch issue?

Probably not, I'm not sure.

**Comment by randomgambit** [comment]
ohhhh I didnt know that. I am sorry. I guess this is related to visualstudio being offered now during the install?

**Comment by ccordoba12** [comment]
No, it's not.

**Comment by CAM-Gerlach** [comment]
@randomgambit Shameless plug: If you'd like to help make Spyder 4 sooner, you can help fund development on our [OpenCollective site](https://opencollective.com/spyder/), and get any organizations/friends you're aware of that use Spyder to do the same.
