### ISSUE TITLE
Old functions can't use imported functions when the script is run a second time.

### ISSUE THREAD

**Issue by Giset0** [spyder-ide/spyder#6499]
## Problem Description

When the following script is run twice from within spyder, it raises an AttributeError the second time.

Some ideas why this might happen:
I think it is somehow connected to Spyder being written in Pyqt, and code from the first run is affecting the second run, because no new QApplication is created for the second run.
In the second run, the signal "QApplication.lastWindowClosed" is emitted and calling the custom function "log()".
In this function a function from the module logging is used, but Spyder doesn't seem to remember the logging module in this function in the second run, thus "logging" ist set to "None" instead of the imported module when run the second time, resulting in the AttributeError.

In this example I can fix it by disconnecting the "lastWindowClosed" signal everytime at the program start, but in more complicated programms it might take a few more lines.

### What steps will reproduce the problem?

1. create a file pack.py:
```
# pack.py

import sys
import logging

from PyQt5.QtWidgets import QApplication


def log():
    logging.warning("Test!")


def connect_qapp():
    qapp = QApplication.instance()
    if not qapp:
        qapp = QApplication(sys.argv)
    qapp.lastWindowClosed.connect(log)
```
2. Create a file main.py in the same folder:
```
# main.py

import sys

from PyQt5.QtWidgets import QApplication

from pack import connect_qapp


qapp = QApplication.instance()
if not qapp:
    qapp = QApplication(sys.argv)
connect_qapp()

# the following lines provide a workaround:
"""
try:
    qapp.lastWindowClosed.disconnect()
except TypeError:
    pass
"""

qapp.lastWindowClosed.emit()
qapp.exec_()

```
2. Run main.py twice from Spyder

### What is the expected output? What do you see instead?
The expected output is no AttributeError, but I see an AttributeError when the programm is
run a second time.

### Paste Traceback/Error Below (if applicable)

```python-traceback


  File "pack.py", line 10, in log
    logging.warning("Test!")

AttributeError: 'NoneType' object has no attribute 'warning'

```

## Package Versions

* Spyder: 3.2.6
* Python: 2.7.14 64bits
* Qt: 5.6.2
* PyQt: PyQt5 5.6 on Windows
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in our next release.

**Comment by goanpeca** [comment]
Is this still the case @impact27?

Thanks!

**Comment by ccordoba12** [comment]
No, it's not because we run things in an empty namespace by default now.
