### ISSUE TITLE
After deleting a directory set as working directory and changing to a new working directory the script won't run

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#650]
_From [bentkows...@gmail.com](https://code.google.com/u/114523486630528179401/) on 2011-05-11T07:20:49Z_

What I'm doing:
1. Open a script and hit F6 to set a working directory for a script. Run the script.
2. Go to a file manager and remove that directory or rename it.
3. Hit F6 again for the same script, change the working directory to a different existing one. Run the script.

Spyder prompts a message: "The following working directory is not valid: [path to non-existing directory]" and refuse to run the script. Happens also after restarting Spyder2.
Going to spyder.ini file and manually cleaning the content of the run configuration section sorts those things out.

I'm using Spyder 2.0.11 on Ubuntu 10.04.2 64-bit

Cheers,
  Piotr

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=650_

**Comment by spyder-issues-migrator** [comment]
_From [sfa....@gmail.com](https://code.google.com/u/100329444270405434809/) on 2011-11-15T08:26:10Z_

I have same problem. Didn't recreate the exact flow but now I am stuck with the spyder message "The following working directory is not valid: [path to non-existing directory]" .

Where is the spyder.ini file located? I can't find it in my computer.

I'm, using Spyder 2.0.13 on Windows7

Thanks,
Roee

**Comment by spyder-issues-migrator** [comment]
_From [bentkows...@gmail.com](https://code.google.com/u/114523486630528179401/) on 2011-11-30T04:45:45Z_

Latest version of Spyder 2.1.3 has the same bug. It might have something to do with my Global Working Directory settings in preferences. I have:
Startup   : the same as in last session
Open file : the current file directory
New file  : the global working directory
Change to 
file base
directory : when opening a file

@ Roee : sory mate, can't help you... don't know Win that much.

**Comment by spyder-issues-migrator** [comment]
_From [visiosub...@gmail.com](https://code.google.com/u/101792976755362964990/) on 2013-04-08T01:08:24Z_

I see this is an old issue, but it is still there. If you are new to the IDE, it is a disgusting bug, since it is not obvious what you should do to remedy the situation. Instead of checking the Directories in the Run Configuration history and just complaining, obsolete paths should be deleted/cleaned.

@ Roee (and others), if you've not yet found the .spyder.ini after all this years, it is here:
Windows 7:
C:\Users\<your_windows_user_login_name>\.spyder2\.spyder.ini

Linux:
some where in your Home directory. Mind you, that dot at the beginning of the directory/filename means that the directory/file in is not normally visible in the file browsers in Linux systems. You have to switch the visibility of hidden files e.g. in KDEs Dolphin with ALT + . (if I correctly remember)

Greets
Chikaya

**Comment by spyder-issues-migrator** [comment]
_From [visiosub...@gmail.com](https://code.google.com/u/101792976755362964990/) on 2013-04-08T01:13:27Z_

Oh Sorry I forgot, I'm on:
Spyder 2.1.13 
distributed with Python(x,y) 2.7.3.1

Chikaya

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-04-30T07:11:38Z_

This issue was updated by revision 80ddd295acf2 .

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-30T07:30:29Z_

**Labels:** MS-v2.2

**Comment by Gabomfim** [comment]
If you can't update your working directory try this:
Run > Configuration per file:
 In working directory settings: choose - the current working directory

Hope I can help!

░░░░░░░░░░░░▄▄▄█▀▀▀▀▀▀▀▀█▄▄▄░░░░░░░░░░░░
░░░░░░░░▄▄█▀▀░░░░░░░░░░░░░░▀▀█▄▄░░░░░░░░
░░░░░░▄█▀░░░░▄▄▄▄▄▄▄░░░░░░░░░░░▀█▄░░░░░░
░░░░▄█▀░░░▄██▄▄▄▄▄▄▄██▄░░░░▄█▀▀▀▀██▄░░░░
░░░█▀░░░░█▀▀▀░░▄██░░▄▄█░░░██▀▀▀███▄██░░░
░░█░░░░░░▀█▀▀▀▀▀▀▀▀▀██▀░░░▀█▀▀▀▀███▄▄█░░
░█░░░░░░░░░▀▀█▄▄██▀▀░░░░░░░░▀▄▄▄░░░▄▄▀█░
█▀░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▀▀▀▀▀░░▀█
█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄░░░░█
█░░░░░░░░░░░░░░░░░░░░░░░░▄▄▄▄▄██░░▀█░░░█
█░░░░░░░░░░░░░░█░░░▄▄▄█▀▀▀░░░▄█▀░░░░░░░█
█░░░░░░░░░░░░░░░░░░▀░░░░░░░░█▀░░░░░░░░░█
█▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄█
░█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█░
░░█░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░█░░
░░░█▄░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄█░░░
░░░░▀█▄░░░░░░░░░░░░░░░░░░░░░░░░░░▄█▀░░░░
░░░░░░▀█▄░░░░░░░░░░░░░░░░░░░░░░▄█▀░░░░░░
