### ISSUE TITLE
Spyder Crash

### ISSUE THREAD

**Issue by bestickley** [spyder-ide/spyder#6500]
## Description

**What steps will reproduce the problem?**

1. Open Spyder
2. 
3. 

**What is the expected output? What do you see instead?**
I expected Spyder to open without error.

**Please provide any additional information below**

  File "C:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\__init__.py", line 511, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 713, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1009, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1035, in connect_client_to_kernel
    stderr_file)
  File "C:\WinPython\python-3.6.3.amd64\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1440, in create_kernel_manager_and_kernel_client
    kernel_manager.start_kernel(stderr=stderr)
  File "C:\WinPython\python-3.6.3.amd64\lib\site-packages\jupyter_client\manager.py", line 234, in start_kernel
    "Currently valid addresses are: %s" % local_ips()
RuntimeError: Can only launch a kernel on a local interface. Make sure that the '*_address' attributes are configured properly. Currently valid addresses are: ['10.30.231.246', '0.0.0.0', '']

## Version and main components

* Spyder Version: 3.2.4 
* Py

**Comment by ccordoba12** [comment]
Please download and use the latest version of WinPython. This error is fixed on it.

**Comment by bestickley** [comment]
Is this the latest version you are referring to: WinPython-64bit-3.6.3.0Qt5.exe ?
I recently downloaded it two days ago.

**Comment by ccordoba12** [comment]
We don't any relation with WinPython, they just informed us that the 
problems was already fixed. So please talk to them directly.

**Comment by CAM-Gerlach** [comment]
It should be 3.6.4 or something, IIRC. If you search around on this repo, a number of other threads have WinPython users and associated folks discussing it, though again its not under our control.

**Comment by CAM-Gerlach** [comment]
Also discussed in #5101 and elsewhere.

**Comment by bestickley** [comment]
Thank you so much for your help. I've isolated the issue down to the vbs file in Scripts called Noshell.vbs. 
When I double click on the Spyder.exe, the NoShell.vbs file runs and it gets to line 11 and RunCmd in the CreateObject() function call is an empty string. Not sure why that is.

NoShell.vbs Code:
If WScript.Arguments.Count >= 1 Then
    ReDim arr(WScript.Arguments.Count-1)
    For i = 0 To WScript.Arguments.Count-1
        Arg = WScript.Arguments(i)
        If InStr(Arg, " ") > 0 Then Arg = chr(34) & Arg & chr(34)
      arr(i) = Arg
    Next

    RunCmd = Join(arr)
    Wscript.Echo "RunCmd: " & RunCmd
    CreateObject("Wscript.Shell").Run RunCmd, 0 , True
End If

**Comment by CAM-Gerlach** [comment]
Thanks. As a general tip, you can put a triple backtick above and below a code block to have it interpreted as code; otherwise the formatting can get quite messed up—I fixed your post above.

I can't find any file or reference thereof called ``Noshell.vbs`` anywhere in our repo. Therefore, it seems likely it is an issue with something persistent related to your Anaconda install instead, and thus entirely outside our control. Where did you find this file, exactly?

**Comment by bestickley** [comment]
Thanks for fixing my post!

Sounds good.
