### ISSUE TITLE
Spyser problem

### ISSUE THREAD

**Issue by priyankajayakumar** [spyder-ide/spyder#6502]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
    max_entries=self.get_option('max_entries', 50))
    data = pickle.loads(open(self.DATAPATH, 'rb').read())
_pickle.UnpicklingError: invalid load key, '\x00'.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

**Comment by ccordoba12** [comment]
Also, please read this guide

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you can fix your problem with it.

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. From what you've provided, I've seen nothing to indicate the error isn't with your own code. Therefore, this issue will be closed. If you can provide more information, such as what is requested in the Troubleshooting Guide, please reopen and comment accordingly. Best of luck!
