### ISSUE TITLE
test_issue_4066 hangs when run from inside Spyder

### ISSUE THREAD

**Issue by jitseniesen** [spyder-ide/spyder#6508]
I can successfully run the Spyder tests in the master branch from the command line using the `py.test` command without any options (summary: 459 passed, 73 skipped, 3 xfailed). There are just minor problems: some tests do not close their windows and there are some warnings that a QProcess is destroyed while the process is still running.

However, if I run the tests using the unittest plugin, then `test_issue_4066` does not terminate. It opens a new Spyder main window (like when running via py.test) but does not close it automatically, If I close it by hand, the test fails. It looks likes the Spyder  main window opened by the test uses the default settings if the tests are run using py.test and the current settings if run using the plugin.

I will have a look whether I can find out what's going on. I'd love to be able to run Spyder's test from within Spyder (eat your dog food). Of course, it may well be that the error is in the plugin.

**Comment by ccordoba12** [comment]
> However, if I run the tests using the unittest plugin, then test_issue_4066 does not terminate

We could skip if run inside the plugin. I mean, that test is fairly complex, but we could run it only when pytest is called in the terminal.

> It looks likes the Spyder main window opened by the test uses the default settings if the tests are run using py.test and the current settings if run using the plugin.

We have a flag in our `conftest.py` to make Spyder use our defaults when being called by Pytest:

https://github.com/spyder-ide/spyder/blob/master/conftest.py#L19

It seems the plugin is not loading it...

> I will have a look whether I can find out what's going on. I'd love to be able to run Spyder's test from within Spyder (eat your dog food).

Sure, I hope to do that too! Please keep working on this one.

**Comment by jitseniesen** [comment]
Thanks for pointing me to conftest.py. It looks like it has to do with the order that files are imported. When running the tests directly under py.test, `conftest.py` is imported before `spyder.config.base` which checks at import time whether the flag is set. However, when running the tests under the plugin, `spyder.config.base` is imported before `conftest.py`, so when the flag is checked it is not yet set. The easiest solution seems to be to delay the check until run time.

**Comment by jitseniesen** [comment]
This was fixed by PR #6540.
