### ISSUE TITLE
crash of spyder and anaconda navigator when importing a project

### ISSUE THREAD

**Issue by heemansh** [spyder-ide/spyder#6511]
### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:
* Python:
* Qt:
* PyQt:
* Operating System:

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
There's no info at all in this issue, so I'm closing it, sorry. Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if that helps.
