### ISSUE TITLE
[Bug] Spyder lags and freezes when tries to run code second time in a non-default console

### ISSUE THREAD

**Issue by homocomputeris** [spyder-ide/spyder#6515]
## Description

**What steps will reproduce the problem?**

1. `spyder --reset`
2.  Set Spyder to run script in a new console
3.  Try to run the same script twice

**What is the expected output?**
Run the code

**What do you see instead?**
The last output in the console tab is` %clear`. 
This tab doesn't respond to either stop button or Ctrl-C.
Closing Spyder lags for a minute or so. Closing the tab lags. Opening Preferences lags too.

**Please provide any additional information below**
Qt 5.10 issue?

## Related issue
Reverting settings back to running in the current console doesn't prevent spawning new console tabs.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.10.0, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.7.0 (OK)
rope >=0.9.4     :  0.10.6 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by homocomputeris** [comment]
Downgraded to 5.9 and got this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/spyder", line 8, in <module>
    start.main()
  File "/usr/lib/python3.6/site-packages/spyder/app/start.py", line 154, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 49, in <module>
    requirements.check_qt()
  File "/usr/lib/python3.6/site-packages/spyder/requirements.py", line 39, in check_qt
    import qtpy
  File "/usr/lib/python3.6/site-packages/qtpy/__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

**Comment by CAM-Gerlach** [comment]
Looks like its not detecting your Qt install at all now...something went wrong with the install. For this reason, we recommend using the Anaconda distribution, which avoids many of the install-specific issues with using ``pip`` or your distro's package manager.

**Comment by homocomputeris** [comment]
May it be related to https://github.com/spyder-ide/spyder/issues/5958?

As I can't check it in Arch, I suggest closing the issue. Maybe it will resolve itself in the coming update and Arch's maintainers will do something with PyQt 5.9 compatibility.

**Comment by ccordoba12** [comment]
Please use Anaconda in the meantime.
