### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'load_module'

### ISSUE THREAD

**Issue by johnwshc** [spyder-ide/spyder#6518]
### What steps will reproduce the problem?

start up of spyder (in Anaconda distribution) generatets error every time: platform: windows 10, v 1709, build: 16299.248

hardware: Inspiron 5759 intel i7 - 6500U @ 2.5 ghz

### Traceback
```python-traceback
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
AttributeError: 'NoneType' object has no attribute 'load_module'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.6.1
* Qt 5.6.2
* PyQt5 5.6
* Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
Do you have other Spyder plugins installed? Like spyder-notebook or spyder-terminal?

**Comment by johnwshc** [comment]
No -- unless they were in the default anaconda install. Where can I list
installed plugins ?

**Comment by ccordoba12** [comment]
Please run in a terminal (cmd.exe)

    spyder --reset

and try again.

**Comment by johnwshc** [comment]
Same result


On February 26, 2018, at 12:53 PM, Carlos Cordoba <notifications@github.com> wrote:

Please run in a terminal (cmd.exe)

spyder --reset 

and try again.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spyder-ide/spyder","title":"spyder-ide/spyder","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/spyder-ide/spyder">https://github.com/spyder-ide/spyder</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ccordoba12 in #6518: Please run in a terminal (cmd.exe)\r\n\r\n spyder --reset\r\n\r\nand try again."}],"action":{"name":"View Issue","url":"<a href="https://github.com/spyder-ide/spyder/issues/6518#issuecomment-368589015">https://github.com/spyder-ide/spyder/issues/6518#issuecomment-368589015</a>"}}}

**Comment by ccordoba12** [comment]
@dalthviz, please catch the AttributeError around this line:

https://github.com/spyder-ide/spyder/blob/3.x/spyder/otherplugins.py#L121

and return None in the except part.
