### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'

### ISSUE THREAD

**Issue by parichaya** [spyder-ide/spyder#6519]
### What steps will reproduce the problem?

Selected Monokai theme and clicked Apply, and then encountered an "internal problem".

### Traceback
```python-traceback
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.5.2
* Qt 5.9.3
* PyQt5 5.9.2
* Linux 4.4.0-112-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
Is the Editor working for you as expected?

**Comment by ccordoba12** [comment]
I think I know where this problem is coming from. We'll fix it in our next release.

**Comment by apsql** [comment]
After the internal error occurs, the whole IDE keeps working as expected (and the color scheme is applied, too). Spyder does not close in response to the error.

**Comment by ccordoba12** [comment]
Yeah, the error is not critical but it doesn't allow to apply a new coloring theme, I guess.

Sorry we missed it.

**Comment by apsql** [comment]
Incorrect in my case: the new syntax highlighting scheme is regularly applied, both in the editor and in the IPython console, despite the error shows up and the error reporting dialog box pops up. In essence, the error does not affect functionality of Spyder on my machine. 

The worst that happens to me is that clicking "Ok" in the Preferences triggers the error but would not close the Preferences box, so I have to click "Apply" (triggering the error **and** effectively applying any changes) and then click "Close" to return to the Editor.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it. It's simply an annoying thing, still it needs to be fixed.

**Comment by parichaya** [comment]
I, just came back online. Yes, you are right - it lets me change the theme and all, just that the error shows up also and hence I posted it here. It's so nice to see such a good community for Spyder. Thanks for your help.
