### ISSUE TITLE
Text in "About Spyder" menu is not selectable

### ISSUE THREAD

**Issue by GalacticStarfish** [spyder-ide/spyder#6535]
## Problem Description

The text in the "About Spyder" menu is not selectable, and the version number must be typed by hand instead of copied and pasted.

### What steps will reproduce the problem?

1.  Navigate to Help > About Spyder
2.  left click and drag mouse to try to select text

### What is the expected output? What do you see instead?

Expect text to be selectable with mouse

## Package Versions

* Spyder: 3.2.3
* Python:  3.6.2 64 bit
* Qt:  5.6.2
* PyQt:  5.6
* Operating System: Windows 7 Ultimate service pack 1

### Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I've been planning to change this for the About and Depenedencies dialogs (as well as making them non-modal, as there was no reason for them to be), given that both I and other users have complained about both. @ccordoba12 , any reservations you have with either?

**Comment by CAM-Gerlach** [comment]
Also, FYI @GalacticStarfish I suggest updating Spyder and your enviroment as it is a number of months out of date. In the Anaconda prompt, type

```bash
conda update conda
conda update anaconda
conda update spyder
```

**Comment by ccordoba12** [comment]
@CAM-Gerlach, fine by me  if you want to work on this one. However, the Dependencies dialog has a *Copy to clipboard* button that allows to paste deps here.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Yeah, I'm not too concerned about the dependencies dialog with respect to that, but no real reason not to I guess...the modality is much more of the problem there.

**Comment by jnsebgosselin** [comment]
I'm able to select and copy the text in the About Window in Windows 10 and I was before in Windows 7. I'm no sure I understand the issue here...

![image](https://user-images.githubusercontent.com/10170372/37596881-fa72a7be-2b53-11e8-853d-da20d515450c.png)

**Comment by CAM-Gerlach** [comment]
@jnsebgosselin Hmm. I just tested it now on Win 8.1 and I can't, but I'll try it on my Win 10 machine in a few minutes, though I don't ever remember the issue there either. What versions of Qt and PyQt are you running? Through conda or pip?

**Comment by jnsebgosselin** [comment]
- The screenshot above is with PyQt 5.6 installed with Anaconda, but running Spyder from source.
- It also works with PyQt 5.9 installed with pip and Spyder running from source.
- I've tested with Spyder 3.2.6 installed with Anaconda and PyQt 5.6 and it works. 
- I tested it with Spyder 3.2.3 as reported in the OP with PyQt 5.6 and this is working.
- This was also working as expected in Windows 7 on my older computer. 
- <kbd>CTRL</kbd> + <kbd>A</kbd> also works...

hehe so I do not understand what is going on.

**Comment by bcolsen** [comment]
I can select it in Ubuntu as well.  The cursor doesn't change but I can select, copy and paste.

**Comment by CAM-Gerlach** [comment]
Weird. I can't get it to select with the mouse or the keyboard on Win 8.1/Anaconda 5.1.0 with either Spyder 3.2.8 stable, 3.x from source, and 4/master from source. I can test on my work machine Win 10) tomorrow.

**Comment by ccordoba12** [comment]
Maybe the update to PyQt 5.9 (which is underway in Anaconda) will fix this.

**Comment by jnsebgosselin** [comment]
> Maybe the update to PyQt 5.9 (which is underway in Anaconda) will fix this.

I don't know. It is working with PyQt 5.6 for me too lol So that is very strange.

![image](https://user-images.githubusercontent.com/10170372/37627426-b53d6c86-2baa-11e8-999f-9af7d8c1a117.png)

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment]
Strange. Maybe its Windows 8.1? I'll test my work machine tomorrow.

**Comment by jnsebgosselin** [comment]
OK, I've managed to reproduce it! This is somewhat related to the `Qt windows style.`

I'm able to select the text when using the `Fusion` style, while I am not when using the `WindowsVista` style.

![image](https://user-images.githubusercontent.com/10170372/37868418-5a296752-2f7c-11e8-8640-0c08b5c160d6.png)
