### ISSUE TITLE
Latest release problem with layouts

### ISSUE THREAD

**Issue by jimbasquiat** [spyder-ide/spyder#6541]
## Problem Description
Just tried to install version 3.2.7: Immediately had a problem with the layout where:
- windows detach from their "docked" position too easily to become free floating:
It is then very hard (actually i didn't managed to) dock them back in their original location.
I tried the view>windows layout>reset to default but it didn't work (i ended with an empty left bottom corner). I tried the other layout options but no luck. Additionally maximizing the window made it much larger than my screen.

ALSO: I just read about your financial problem, it's very sad as Spyder is the best IDE IMO for working with pandas etc. I'll make a donation, but I feel like what you guys need is an institutional sponsor: Look out there, there are plenty of them(here for instance a french one that also give out international grants: https://www.reseau-entreprendre.org/en/homepage/). Also maybe it would be good if you set up a petition page for people to sign up to show their support - and also show anaconda that the spyder community is alive and well!

### What steps will reproduce the problem?

1. Undock a window from the default layout
2. try to dock it back in its location , or reset the layout to deafult

### What is the expected output? What do you see instead?
I would like to revert to default. I see instead a layout where the editor is on the top left corner, the help  on the top right, and console to right, leaving bottom left empty. I tried to move around the windows / use the other default layout, with no luck. Maximizing / using other preset layouts also make the software window much larger than my screen.

## Package Versions

* Spyder:3.2.7
* Python:3.6.4
* Qt:5.6.2
* PyQt:5.6.0
* Operating System: Linux PC1 4.10.0-38-generic #42~16.04.1-Ubuntu SMP

### Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. I tested it just now and this all works just fine on Windows for me, so perhaps a Linux specific (Qt)) issue? @ccordoba12 ? Also, thanks for your suggestion on grants, we're currently looking in to some (I'm actually writing one up as we speak), but more suggestions are always welcome. Also, we have an [OpenCollective page](https://opencollective.com/spyder/) to show your support.

**Comment by ccordoba12** [comment]
> It is then very hard (actually i didn't managed to) dock them back in their original location.

This is true. If you move a dock around after detaching it, it can be hard to put it in the same place it was before. However, could you post a little video to understand better your problem? That would really help us.

Also, why are you undocking panes? To create a new layout or to move a pane to a different screen?

**Comment by CAM-Gerlach** [comment]
On Windows, you can just drag a detached panel anywhere near another to snap it back in. Maybe that's not possible, or at least more difficult, on Linux?

![image](https://user-images.githubusercontent.com/17051931/36759210-4225a34a-1bdc-11e8-873c-902e03a1a050.png)

**Comment by jimbasquiat** [comment]
> Also, why are you undocking panes? To create a new layout or to move a pane to a different screen?

No I didn't do it on purpose, just opened the software after updating it with the latest version, and just maybe 1 misplaced click on the top part of the editor and it was undocked (seemed much more sensitive than 3.2.6. After that - no way to get default layout back, even by restarting the soft, so I had to revert to 3.2.6.

3.2.6 is very sturdy on that regard and I have not had any problem at all with layouts.

Regarding the video: How would I go about at uploading it? here, is it possible? Or would I have to upload it on youtube or smthg (that would prob.be a bit more trouble for me!)

**Comment by ccordoba12** [comment]
> 3.2.6 is very sturdy on that regard and I have not had any problem at all with layouts.

We haven't changed anything important about layouts. @csabella fixed a couple issues about layouts in 3.2.7, but that's it.

Did you run `spyder --reset` and the problem was not fixed for you?

> Regarding the video: How would I go about at uploading it? here, is it possible?

Since you're using Linux, I'm afraid you'll have to upload the video to Youtube. Or you can try to install Licecap with Wine and upload an animated gif here.

**Comment by ccordoba12** [comment]
> Ok yep reinstalling did the trick.. sorry to have bothered you with that...

Good to know! By the way, we made docking/undocking more intuitive for Spyder 4, so this problem won't appear there. Sorry, but we don't have plans to do anything about it for Spyder 3.

> Where can I see the list of updates for that new 3.2.7 by the way?

We maintain a detailed Changelog for that:

https://github.com/spyder-ide/spyder/blob/master/CHANGELOG.md
