### ISSUE TITLE
Spyder froze during script execution. Script was saved, but savefile nowhere to be found

### ISSUE THREAD

**Issue by jvollme** [spyder-ide/spyder#6567]
I have been working on a particular script for several days now. I have saved it using the "save" button in spyder (even making backup-copies using "save as", but not double checking if they were actually created but simply expecting them to  turn up in the working dir...).
However, right now, now the whole IDE just froze during execution ("F5") of the script. Naturally, before killing the whole process, I wanted to check if the saved file is actually intact. However, it (nor the backups) is nowhere to be found in the working directory! Also cant find it anywhere using ```find ~/. -name "*.py```. 
I have tried opening a secend instance of spyder using ```spyder --new-instance``` and looking at "recent-files" but that script is not listed there (only something much older).

Please, Is there any possibility of finding/reconstructing that file again? 
I noticed that spyder saves the current version of the script when hitting "run script" (F5). But does it actively delete the previous version before saving the current one?
Does it have any "Temporary directory" for saving currntly opened documents? Where would i find that (I have installed spyder using conda?)

**Comment by jvollme** [comment]
Update: Spyder finally killed itself with the following error message:
```
QTextCursor::setPosition: Position '26176' out of range
QClipboard::setData: Cannot set X11 selection owner for PRIMARY
```
The presumably "saved" versions of the script are nowhere to be found...

**Comment by jvollme** [comment]
Phew, after restarting spyder (now that the instance in which I edited the scripts in question has been killed), I do have the scripts again and could save them (to the cloud this time, and double checking that the files were actually created where I expected them to be...).
Sorry for the panicked issue, I consider this solved ...

**Comment by theo123490** [comment]
I have the same problem, spyder crashed and I need to reset it, so naturally, I go to anaconda console and run 'spyder --reset' I can't do drag and drop to the script and when I open the script with notepad++ it shows a line full of Nul. 

![image](https://user-images.githubusercontent.com/38230742/53284350-9c104200-3785-11e9-9a39-87e966b9d721.png)
