### ISSUE TITLE
In the find/replace dialog the tab key niether inserts a tab character nor advances to the next field

### ISSUE THREAD

**Issue by GalacticStarfish** [spyder-ide/spyder#6581]
## Problem Description

In the find/replace dialog the tab key neither inserts a tab character nor advances to the next field

### What steps will reproduce the problem?

1.  In the drop-down menus navigate to Search > Replace Text
2.  Place keyboard focus in the top (find) field of the replace dialog
3.  press the tab key
4. observe that keyboard cursor has not changed position

### What is the expected output? What do you see instead?

I expect pressing the tab key to either move the keyboard focus to the next field (the new string which is used to replace the old string) or that pressing the tab key will insert a tab character.

## Package Versions

* Spyder: 3.2.3
* Python: 3.6.2 62-bit
* Qt:  5.6.2
* PyQt:  5.6
* Operating System: Windows

### Dependencies

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by jitseniesen** [comment]
This was fixed in Spyder version 3.2.6 (the tab key now moves to the next field), which was release two months ago, so please upgrade. The original issue is #3674.
