### ISSUE TITLE
Problem in Shortcut Editor

### ISSUE THREAD

**Issue by RicardoNoguerales** [spyder-ide/spyder#6582]
## Problem Description

**Shortcut Editor** can't be closed, nor pressing Ok either Cancel.

Spyder installed through `pip `, downloaded file is **spyder-3.2.6-py2-none-any.whl**
Using Python 2.7.8

### The problem

`super()` is called without arguments.
This is OK in Python 3, but in Python 2 `super()` needs at least one argument.

### Solution

In   **C:\Python27\Lib\site-packages\spyder\plugins\shortcuts.py** , in `class ShortcutEditor`

  line 214 (reject method), replace
        `super().reject()`
     with
        `super(ShortcutEditor, self).reject()`

  line 223 (accept method ), replace
       ` super().accept()`
     with
        `super(ShortcutEditor, self).accept()`

**Comment by csabella** [comment]
Thank you for the report.  This was fixed in 3.2.7 with PR #6251.  3.2.7 was already released, so you should be able to install it soon.

**Comment by CAM-Gerlach** [comment]
It should be live now, if it wasn't already.
