### ISSUE TITLE
Spider was doing fine job, pointing out errors till it didnot work. There wasno cursor in console when i opened spider.

### ISSUE THREAD

**Issue by spider00** [spyder-ide/spyder#6596]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

AttributeError: module 're' has no attribute 'search'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by spider00** [comment]
While clicking run button the output is like:

Traceback (most recent call last):
  File "/home/arjun/anaconda_install/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/arjun/anaconda_install/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/arjun/anaconda_install/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/arjun/anaconda_install/lib/python3.6/site-packages/pylint/__init__.py", line 8, in <module>
    from .__pkginfo__ import version as __version__
  File "/home/arjun/anaconda_install/lib/python3.6/site-packages/pylint/__pkginfo__.py", line 16, in <module>
    from pkg_resources import parse_version
  File "/home/arjun/anaconda_install/lib/python3.6/site-packages/pkg_resources/__init__.py", line 24, in <module>
    import re
  File "/home/arjun/AnacondaProjects/re.py", line 12, in <module>
    searchobj = re.search('(.*) / (.*)' , text)
AttributeError: module 're' has no attribute 'search'

**Comment by jitseniesen** [comment]
I think the problem is the file `/home/arjun/AnacondaProjects/re.py`. This file has the same name as the `re` module for regular expressions in the standard Python library. I suggest you rename your file as it is generally a bad idea to have the same name as used in the standard library, and hopefully that will fix the issue.

**Comment by CAM-Gerlach** [comment]
Let us know whether it fixes the issue; if we don't hear from you after a week, we'll assume it did and this issue will be closed. Thanks.

**Comment by ccordoba12** [comment]
> This file has the same name as the re module for regular expressions in the standard Python library

Yep, this is the problem here. @spider00, please rename your file to something else to fix this.
