### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ashutoshnpr** [spyder-ide/spyder#6599]
### What steps will reproduce the problem?

Spyder suddenly crashed while I was working on a code and my PC restarted closing everything. When I reopened Spyder, the file I was working on got everything erased and is showing just spaces(blank). I opened the file using Notepad++ but it is showing "NULL NULL NULL" everywhere with 2,598 columns. Can someone help if I could somehow recover my code?

**Comment by ccordoba12** [comment]
We're very sorry, but there's no way to recover your code. To address this problem we're working on saving backup files.

For next time, please use git to save your word.

**Comment by CAM-Gerlach** [comment]
Possible duplicate of #6571 , and mitigated by the implementation of #2111
