### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by BurgerAutomata** [spyder-ide/spyder#6643]
I have just update spyder from console with conda update --all. I am currently using it in a PyTorch environment where I installed pytorch from petercj123 repository

The kernels in the ipython console are unable to be started. This is happening on start of spyder.

**Comment by MAFiA303** [comment]
try downgrading tornado from 5 to 4.5.3

**Comment by BurgerAutomata** [comment]
@MAFiA303 it worked!

**Comment by CAM-Gerlach** [comment]
This is a duplicate of #6627 ; and in any case outside of Spyder's control. To fix for now, run ``conda install tornado=4.5.3`` from the Anaconda Prompt/Terminal/shell (Windows/Mac/Linux) in the ``conda`` environment that Spyder is installed in.
