### ISSUE TITLE
Toolbar moved up

### ISSUE THREAD

**Issue by MuhammedBuyukkinaci** [spyder-ide/spyder#6652]
## Problem Description
Hi, I installed Spyder via pip. However, the toolbar doesn't look proper. It slipped up. It is annoying. Before updating to 3.2.7, the problem was also existent. I couldn't find any way to make it correct.

![screenshot 2](https://user-images.githubusercontent.com/33747602/37105681-df8f3bd6-2240-11e8-8343-cccbe49b9c72.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.7
* Python: 3.6
* Qtpy: 1.3.1
* PyQt5: 5.9.2
* Operating System: windows 10 home

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This is fixed by closing the Help pane. We really don't know what causes this error, sorry.

**Comment by jnsebgosselin** [comment]
@ccordoba12 Is this a Windows 10 specific issue?

**Comment by ccordoba12** [comment]
Win 10 + PyQt 5.9+

**Comment by jnsebgosselin** [comment]
I'm going to look at it once I receive my new computer with windows 10 and a high res screen next week.

**Comment by ccordoba12** [comment]
Great, thanks!

**Comment by MuhammedBuyukkinaci** [comment]
Maybe the problem is due to high res screen. My laptop also has a 4K screen.

**Comment by CAM-Gerlach** [comment]
Its likely due to having a HiDPI screen. In Preferences, under General, enable HiDPI mode and restart Spyder.

**Comment by MuhammedBuyukkinaci** [comment]
Yes, I closed help window and it look OK.
![screenshot 3](https://user-images.githubusercontent.com/33747602/37117064-2ac21450-2261-11e8-9b11-649ff6b04b3d.png)
