### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dberrian** [spyder-ide/spyder#6653]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\db\Anaconda2\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1536, in go_to_error
    self.edit_goto.emit(osp.abspath(fname), int(lnb), '')
ValueError: invalid literal for int() with base 10: ''

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This error is fixed in our latest version (3.2.7). Please update by running in the Anaconda prompt:

    conda update spyder

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I can't find a completed issue report that has this issue exactly; there are others with similar last lines but different actual tracebacks/situations. #5478 appears to be an exact duplicate, but was closed as a NoResponce.

**Comment by ccordoba12** [comment]
@csabella fixed this. I don't remember what was the release this release it was included in, though.

**Comment by csabella** [comment]
https://github.com/spyder-ide/spyder/pull/5585

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 and @csabella !
