### ISSUE TITLE
Spyder is making me lose internet connection

### ISSUE THREAD

**Issue by Juanouo** [spyder-ide/spyder#6680]
## Problem Description
So, since I decided to update Spyder (I think I was running 3.2.0 before updating) it started having this problem where at random intervals (5-30 minutes) it leads to a total loss of traffic in my internet connection for 1-3 minutes, even though it says it is connected. When I try to open any webpage it says there's no internet connection. I don't have to be running a script for this to happen, it'll be randomly happening as long as I have Spyder in the background.
Things I have tried:
Updating conda, anaconda, spyder
Uninstalling anaconda, then reinstall
Uninstalling spyder and anaconda, then reinstall
Turn off firewall

Nothing has worked as of now.
Thanks in advance if anyone can help  

### What steps will reproduce the problem?

1. Open Spyder (usually through Anaconda, but doesn't matter if it is through there)
2. Browse internet until webpages stop loading for 1-3 minutes until internet comes back

```

## Package Versions

* Spyder:3.2.7
* Python: 3.6
* Qt: 5.6.2
* PyQt: 5.6.0
*Anaconda: 5.1.0
* Operating System: Windows 10

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. This has been reported before, but we don't know the cause nor how to fix it, sorry.
