### ISSUE TITLE
System time change causes Spyder error

### ISSUE THREAD

**Issue by angertdevsingh** [spyder-ide/spyder#6682]
## Description

When the system time is changed to the past, Spyder opens an error dialog.

It has something to do with line 571 in:
> C:\Users\user\Anaconda3\Lib\site-packages\spyder\widgets\ipythonconsole\client.py

**What steps will reproduce the problem?**

1. Open Spyder.
2. Change system time to 2017 or earlier.

**What is the expected output? What do you see instead?**

An error dialog as shown below

![image](https://user-images.githubusercontent.com/17932244/37169677-7885734a-2300-11e8-9c69-5b286aaa61b3.png)

When the time is changed back, the error dialog goes away.

**Please provide any additional information below**

  OS: Windows 10

Error message details:

> File "C:\Users\angert\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
>     "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
> OSError: [Errno 22] Invalid argument
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "C:\Users\angert\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
>     "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
> OSError: [Errno 22] Invalid argument
>   File "C:\Users\angert\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
>     "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
> OSError: [Errno 22] Invalid argument
> Traceback (most recent call last):
> Traceback (most recent call last):
>   File "C:\Users\angert\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
>     "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
> OSError: [Errno 22] Invalid argument
>   File "C:\Users\angert\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\client.py", line 571, in show_time
>     "</b></span>" % (color, strftime(fmt, gmtime(elapsed_time)))
> OSError: [Errno 22] Invalid argument
> Traceback (most recent call last):
> Traceback (most recent call last):

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

Edit: Added image of error dialog box.

**Comment by ccordoba12** [comment]
Thanks for reporting. This seems like an easy fix.

**Comment by angertdevsingh** [comment]
@ccordoba12 No problem, thank you for fixing it. I am not very familiar with Spyder patches so please excuse me if this is common knowledge, but is there an estimated release date of v3.2.9 ?

**Comment by CAM-Gerlach** [comment]
It isn't common knowledge (I actually don't know it myself); but given we haven't released 3.2.8 yet and we just released 3.2.7 it will probably be a bit, since we're currently unfunded.

**Comment by ccordoba12** [comment]
> but is there an estimated release date of v3.2.9 ?

Two months, perhaps a bit less.

**Comment by CAM-Gerlach** [comment]
FYI @angertdevsingh , since its made it into 3.2.8, looks like you'll get this a lot sooner than two months.

**Comment by angertdevsingh** [comment]
@CAM-Gerlach Thank you, that's great to hear!

**Comment by CAM-Gerlach** [comment]
In fact it should drop tomorrow morning, though it might take a few days for ``conda`` packages to be generated.

**Comment by angertdevsingh** [comment]
@ccordoba12, I don't want to clutter the thread too much, so I'll keep it brief but thank you so much for fixing the bug. It's allowed me to keep my workflow and my sanity!

**Comment by ccordoba12** [comment]
Please thank @csabella, she was the one who fixed this bug.
