### ISSUE TITLE
Cannot plot local varibles in variable explorer when debugging

### ISSUE THREAD

**Issue by skyblueee** [spyder-ide/spyder#6695]
my python file:
```python
import numpy as np
def func():
    bb = np.arange(10)
    return bb      # breakpoint here

a = np.arange(5)
cc = func()
```
1. put a breakpoint before `return bb` and debug the file
2. the program stops before return, and now two variables in the variable explorer:
        * global variable a = array([0, 1, 2, 3, 4])
        * local variable bb = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
3. right click on a and select plot, no problem. BUT, right click on bb and select bb, report `***KeyError: 'bb'`

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by gerazov** [comment]
:+1:  This would be really useful for debugging array variables.

**Comment by goanpeca** [comment]
@impact27 could you take a look at this one?

**Comment by ccordoba12** [comment]
The error is here:

https://github.com/spyder-ide/spyder-kernels/blob/2c5b36cdb797b8aba77bc406ca96f5e079c4aaca/spyder_kernels/console/start.py#L267

So we're not taking into account the current frame namespace when passing a variable to the `%varexp` magic.

**Comment by henry-gio** [comment]
Running spyder 4.1.1, same code as above.
In debug mode r-click on 'a' or 'bb' and select Plot from menu.
The plot window opens, blank, and freezes. 
Windows warning: "Python is not responding".
If I stop the debug (blue square button) the plot appears in the figure.

**Comment by ccordoba12** [comment]
Plotting of variables while debugging only works with the inline backend, not with other Matplotlib backends.

**Comment by bburne** [comment]
In Spyder 5.3.2, This problem appears again. Could you take a look?

**Comment by ccordoba12** [comment]
@bburne, please open a new issue about that and post a simple code example that reproduces it.
