### ISSUE TITLE
Changing fonts in Editor

### ISSUE THREAD

**Issue by JoelShen123** [spyder-ide/spyder#6720]
Hi,
I am working with the newest version of Spyder running Python 3.6. However, I am unable to select a font of my choice for the editor panel. I have checked the "Preferences" in the "Tools" tab; however, the fonts available are limited and highly unsatisfying.

Is there a way where I can install my own fonts in some folder, then use that specific font? Thanks.

Regards,
Joel

* Operating System: Windows 10

**Comment by CAM-Gerlach** [comment]
These are the fonts installed via your operating system; you can install more the same way you install any other font. The main limitation Spyder imposes is the plain text font must be monospace, for fairly obvious reasons (particularly in Python). However, if you install a font like FiraCode that might not automatically get detected as monospace, you can still select it manually by typing its name in the selection box.
