### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by juseedom** [spyder-ide/spyder#6725]
### What steps will reproduce the problem?

**# only update spyder via conda, then error prompt out**
(base) C:\Users\jianx>conda update bokeh matplotlib jupyter spyder tornado
Solving environment: done

## Package Plan ##

  environment location: C:\Users\jianx\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - bokeh
    - jupyter
    - matplotlib
    - spyder
    - tornado

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    tornado-5.0                |           py36_0         648 KB
    kiwisolver-1.0.1           |   py36h12c3424_0          61 KB
    bokeh-0.12.14              |           py36_0         4.1 MB
    spyder-3.2.7               |           py36_0         2.7 MB
    matplotlib-2.2.0           |   py36h4dabdea_0         6.5 MB
    ------------------------------------------------------------
                                           Total:        14.0 MB

The following NEW packages will be INSTALLED:

    kiwisolver: 1.0.1-py36h12c3424_0

The following packages will be UPDATED:

    bokeh:      0.12.13-py36h047fa9f_0 --> 0.12.14-py36_0
    matplotlib: 2.1.2-py36h016c42a_0   --> 2.2.0-py36h4dabdea_0
    spyder:     3.2.6-py36_0           --> 3.2.7-py36_0
    tornado:    4.5.3-py36_0           --> 5.0-py36_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
tornado 5.0: ############################################################################################### | 100%
kiwisolver 1.0.1: ########################################################################################## | 100%
bokeh 0.12.14: ############################################################################################# | 100%
spyder 3.2.7: ############################################################################################## | 100%
matplotlib 2.2.0: ########################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\jianx\AppData\Local\Continuum\anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\jianx\AppData\Local\Continuum\anaconda3\pythonw.exe, args are ['C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\cwp.py', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\pythonw.exe', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\jianx\AppData\Local\Continuum\anaconda3\python.exe, args are ['C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\cwp.py', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\python.exe', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\spyder-script.py', '--reset']
| DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\jianx\AppData\Local\Continuum\anaconda3', env_name: 'None', mode: 'None', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\jianx\AppData\Local\Continuum\anaconda3\pythonw.exe, args are ['C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\cwp.py', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\pythonw.exe', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\spyder-script.py']
/ DEBUG menuinst_win32:create(323): Shortcut cmd is C:\Users\jianx\AppData\Local\Continuum\anaconda3\python.exe, args are ['C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\cwp.py', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\python.exe', 'C:\\Users\\jianx\\AppData\\Local\\Continuum\\anaconda3\\Scripts\\spyder-script.py', '--reset']
done

(base) C:\Users\jianx>

### Traceback
```python-traceback
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 514, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 725, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1038, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1073, in connect_client_to_kernel
    kc.start_channels(shell=True, iopub=True)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\kernel_mixins.py", line 43, in start_channels
    super(QtKernelClientMixin, self).start_channels(*args, **kw)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 212, in start_channels
    self.shell_channel._inspect = self._check_kernel_info_reply
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\client.py", line 143, in shell_channel
    socket, self.session, self.ioloop
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyter_client\threaded.py", line 205, in ioloop
    self._ioloop = ioloop.IOLoop()
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 845, in initialize
    super(PollIOLoop, self).initialize(**kwargs)
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 357, in initialize
    self.make_current()
  File "C:\Users\jianx\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\ioloop.py", line 315, in make_current
    assert asyncio is None
AssertionError
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.6.4
* Qt 5.6.2
* PyQt5 5.6
* Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by juseedom** [comment]
# i tried with update pyzmq, ipykernel, seems errors gone
(base) C:\Users\jianx>conda update pyzmq ipykernel
Solving environment: done

## Package Plan ##

  environment location: C:\Users\jianx\AppData\Local\Continuum\anaconda3

  added / updated specs:
    - ipykernel
    - pyzmq


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyzmq-17.0.0               |   py36hfa6e2cd_0         558 KB
    ipykernel-4.8.2            |           py36_0         146 KB
    ------------------------------------------------------------
                                           Total:         704 KB

The following packages will be UPDATED:

    ipykernel: 4.8.0-py36_0          --> 4.8.2-py36_0
    pyzmq:     16.0.3-py36he714bf5_0 --> 17.0.0-py36hfa6e2cd_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
pyzmq 17.0.0: ############################################################################################## | 100%
ipykernel 4.8.2: ########################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This is a duplicate of #6627 ; and in any case outside of Spyder's control. To fix it, run ``conda update pyzmq tornado ipykernel`` from the Anaconda Prompt/Terminal/shell (Windows/Mac/Linux) in the ``conda`` environment that Spyder is installed in.
