### ISSUE TITLE
Changing file in editor with [Ctl]+[tab] uncompatible with tiling window manager

### ISSUE THREAD

**Issue by ElieGouzien** [spyder-ide/spyder#6743]
## Problem Description
The widget opened when using [Ctl]+[tab] opens as full window with (i3) tiling window manager.
I think it should be opened as a floating window (just like the file switcher or symbol finder).

### What steps will reproduce the problem?
* Open Spyder with i3 window manager ;
* open two files ;
* switch file with [Ctl] + [Tab].

## Package Versions

* Spyder 3.2.7
* Python 3.5.2
* Qt 5.9.3
* PyQt5 5.9.2
* Linux 4.4.0-116-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.1.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1 (OK)
pandas >=0.13.1  :  0.17.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.3.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  3.4.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.23.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.5.2 (OK)
```

**Comment by ccordoba12** [comment]
You're welcome to submit a PR for this. Unfortunately we don't have time to fix it.

**Comment by ElieGouzien** [comment]
I can try. Could you tell me in which file to look ?
