### ISSUE TITLE
'Execute in an external system terminal' doesn't work if there is spaces in the path where the python interpreter is installed in Windows

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#6746]
## Problem Description

I'm trying to execute a script in an external system terminal on Windows 10 64bit and it is not working.

### What steps will reproduce the problem?
Let's say I have this very simple script :
```python
# -*- coding: utf-8 -*-
print('test')
```
1.  Run the script with <kbd>F5</kbd> using the configuration per file shown below so that the script is executed in an external system terminal and so that I can interact with the Python console after execution.

![image](https://user-images.githubusercontent.com/10170372/37351401-5977428a-26b1-11e8-901b-43cdb3e0cbdd.png)

### What is the expected output? What do you see instead?

I expect the script to run in an external system terminal and to be able to see the result in the Python console. Instead, the cmd windows is shown for a fraction of a second, then nothing happens.

### Paste Traceback/Error Below (if applicable)

There is no traceback/error.

## Package Versions

* Spyder: Spyder 4.0.0.dev0 
* Python: Python 3.6.4 64bits
* Qt: Qt 5.9.1
* PyQt: PyQt5 5.9
* Operating System: Windows 10 amd64

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by jnsebgosselin** [comment]
**Why it is not working**

The python interpreter is installed in `C:\Program Files\Python36` which is a common place where program are installed in Windows.

The command to execute the script in an external system terminal is not working because of the space in `Program Files` .

In the function [run_python_script_in_terminal](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/programs.py#L255) in [spyder/utils/program.py](https://github.com/spyder-ide/spyder/blob/master/spyder/utils/programs.py), I think the path that is returned by `get_python_executable()` should be enclosed in "" to fix this.

**Comment by ccordoba12** [comment]
> I think the path that is returned by get_python_executable() should be enclosed in "" to fix this.

That seems the right fix. Would you like to submit a PR for this?

**Comment by jnsebgosselin** [comment]
@ccordoba12 sure, I'm going to do it today.
