### ISSUE TITLE
The Spyder does not release the command line after it gets closed

### ISSUE THREAD

**Issue by VanitarNordic** [spyder-ide/spyder#6747]
## Problem Description

I just installed the Spyder 3.2.7 on a fresh Anaconda environment by the Conda command. The Spyder opens flawlessly, but if we close it, it does not release the command line where it has started. it sticks there.

![2018-03-13_19-07-49](https://user-images.githubusercontent.com/18719591/37352175-e83fc34e-26f1-11e8-8978-133fe93ff469.jpg)

## Package Versions

* Spyder: 3.2.7 (installed by anaconda)
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
This is not our problem. For now you need to downgrade Tornado with

    conda install tornado=4.5.3

This will be fixed when a new version of `jupyter_client` is uploaded by Anaconda.

**Comment by VanitarNordic** [comment]
Thank you
