### ISSUE TITLE
Spyder won't properly close on Mac OSX Darwin

### ISSUE THREAD

**Issue by ibackus** [spyder-ide/spyder#6748]
## Problem Description

Spyder won't properly close on Mac OSX Darwin.

I bought a new macbook pro, first time using OSX in a long time.  When I close out of spyder, the window closes, but spyder keeps running.  It still ties up the terminal that I launch it from and remains on the dock.

### What steps will reproduce the problem?

1. Open spyder in a terminal.
2. Close spyder.

### What is the expected output? What do you see instead?

Spyder should just open and then close.  Instead, it it remains on the dock and the process continues running.

## Package Versions

* Spyder: 3.2.7
* Python: 3.6.3
* Qt: 5.6.2
* PyQt: 5.6
* Operating System: OSX Darwin

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment]
It does't close properly on any platform. For now, please run

    conda install tornado=4.5.3

to avoid this problem. It'll be fixed after Anaconda uploads the latest version of `jupyter_client`.
