### ISSUE TITLE
Environment variables defined in .bashrc or .bash_profile don't show up in ipython

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#675]
_From [AlexPark...@gmail.com](https://code.google.com/u/102366852192629979535/) on 2011-06-01T07:56:18Z_

What steps will reproduce the problem?

 1. Define an environment variable in ~/.bash_profile or ~/.bashrc (e.g. export TEST='test')
2. Start spyder
3. In ipython terminal, import os and type "os.environ['TEST']" What is the expected output? What do you see instead? If I start ipython from the terminal then os.environ['TEST'] prints 'test'.
However, using ipython from within spyder gives me KeyError: u'TEST' What version of the product are you using? On what operating system? Spyder 2.0.11, ipython 
Mac OS 10.6 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=675_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-01T06:01:56Z_

Are you sure that you did restart Spyder *and* the parent terminal after setting this environment variable?

**Comment by spyder-issues-migrator** [comment]
_From [AlexPark...@gmail.com](https://code.google.com/u/102366852192629979535/) on 2011-06-01T06:18:24Z_

Hmm - I created an Application using Automator to run spyder, but for some reason this doesn't set the shell up correctly. If I call it directly from the shell then it all works fine. Sorry about that.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-01T06:20:19Z_

No problem!

**Status:** Invalid

**Comment by rsettigunte** [comment]
I am facing an issue running a python code in spyder on mac - python 3.7. All are 64 bit installs

Sample code
import cx_Oracle
print (cx_Oracle.clientversion())

I get the following error
DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

The same code with no error when run from a terminal. 

.bash_profile has these entries for env variables
export PATH=/Users/rshankar/instantclient_12_2:$PATH
export ORACLE_HOME=/Users/rshankar/instantclient_12_2
export VERSION=12.2.0.1.0
export DYLD_LIBRARY_PATH=$ORACLE_HOME
export LD_LIBRARY_PATH=$ORACLE_HOME
export ARCH=x86_64

Out of the above, I don't see LD_LIBRARY_PATH and DYLD_LIBRARY variables when I check show environment variables. Interestingly I see others

Not able to understand whey these variables don't get uploaded and I continue to battle with this error

Any help on this

**Comment by rsettigunte** [comment]
I set the variables explicitly  using os.env in ipython console. They show up in the list.  I executed the same 2 lines in ipython console and I get the same error (no error when executed outside spyder from a terminal)

import cx_Oracle
print (cx_Oracle.clientversion())

DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "dlopen(libclntsh.dylib, 1): image not found". See https://oracle.github.io/odpi/doc/installation.html#macos for help

**Comment by ccordoba12** [comment]
You need to start Spyder from a terminal for it to pick up the env vars defined there.

**Comment by rsettigunte** [comment]
I have done the same. Spyder is invoked from the terminal

**Comment by rsettigunte** [comment]
Sorry to clutter with more mails. I tried one more thing. Added a new env variable (TEST) to .bash_profile.  Restarted spyder. This env did show up in the list. There is some thing wrong only about LD_LIBRARY_PATH and DYLD_LIBRARY_PATH env variables.  

Thanks for your patience to read through

**Comment by rsettigunte** [comment]
Finally, the problem was fixed by disabling SIP on mac. I am able to run python script with no errors from spyder. It is able to recognize LD_LIBRARY_PATH and DYLD_LIBRARY_PATH settings

**Comment by ccordoba12** [comment]
Ok, good to know!

**Comment by cruyffturn** [comment]
On Mac 10.13 with spyder3 the following steps work:

1. Define an environment variable in ~/.bashrc
2. source ~/.bashrc
3. Open a new terminal tab.
4. Launch spyder.
