### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by lygbird** [spyder-ide/spyder#6752]
cannot connect to kernel of ipython console

**Comment by CAM-Gerlach** [comment]
No substantive information was provided with this report; however, it is most likely a duplicate of #6627 or perhaps an issue with ``jupyter_client`` we just discovered earlier. To fix it, run ``conda update pyzmq tornado ipykernel jupyter_client=5.2.2`` from the Anaconda Prompt/Terminal/shell (Windows/Mac/Linux) in the ``conda`` environment that Spyder is installed in. Thanks.
