### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by kakazuya** [spyder-ide/spyder#6756]
![screenshot 8](https://user-images.githubusercontent.com/37357861/37382946-a382d262-276b-11e8-803a-9d00e4a8d2d7.png)

**Comment by ccordoba12** [comment]
You need to paste the contents of your clipboard after pressing *Submit to Github* so we can receive the error message generated by Spyder. Else, we can't help you.

**Comment by CAM-Gerlach** [comment]
You can also try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
