### ISSUE TITLE
spyder3.2.8 unable to start kernel

### ISSUE THREAD

**Issue by nanni018** [spyder-ide/spyder#6768]
If you don't find anything, please provide a detailed step-by-step description (in English) of the problem and what led up to it below. Issue reports without a clear way to reproduce them will be closed. Thanks! --->
An error ocurred while starting the kernel
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site‑packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
callback(*args, **kwargs)
File "/usr/local/lib/python3.6/site‑packages/tornado/stack_context.py", line 276, in null_wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.6/site‑packages/ipykernel/kernelbase.py", line 283, in dispatcher
return self.dispatch_shell(stream, msg)
## Problem Description
kernel does not start or stays in a loo
## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Darwin 17.4.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
Sorry but the error message you posted is not complete, so it's hard to know what's happening exactly. A possible solution is to downgrade Tornado with

    pip install tornado==4.5.3

**Comment by nanni018** [comment]
thanks that worked

**Comment by CAM-Gerlach** [comment]
I would assume duplicate of #6627  then?

**Comment by ccordoba12** [comment]
Probably, although the error is slightly different.

**Comment by CAM-Gerlach** [comment]
Thanks.

**Comment by femiaiyeku** [comment]
Upgrading ipykernel worked for me
conda upgrade ipykernel
