### ISSUE TITLE
Search issue

### ISSUE THREAD

**Issue by dpwilt** [spyder-ide/spyder#6775]
## Problem Description
I ran across this when editing some code to clean it up. I was searching for the number 4 followed by a decimal (period) character in the Spyder IDE (regex off), and the IDE reported a huge number (44 to be exact) of matches. But when I clicked the next/previous arrows in the search box, there were only two occurrences. After fiddling a bit, it was clear that the IDE was treating the "4." as a regular expression when it reports number of matches, in spite of the regexp (gear icon) being turned off. When I turned it on, 44 matches (correct); off, 44 matches (wrong!)

### What steps will reproduce the problem?

1. Open python source code in IDE
2. Have some strings that match regex "4." but don't match string "4." In my minimal example I have one comment line:
# 4 4 4 4 4 <newline>
3. Search for "4." with regex "gear" icon on/off and check reported number of matches. In my case it is the same whether regex is on or off. In the minimal example, 5 matches. With regexp on, hitting the arrow button it will march through the 5 matches, with regexp off, it shows the orange "not found" background and says 5 matches.

### What is the expected output? What do you see instead?
Expect reported matches to correspond to actual occurences. Instead, it reports matches as if the search is a regex regardless of the state of the regex flag

### Paste Traceback/Error Below (if applicable)
NA

## Package Versions

* Spyder: 3.2.4
* Python: 3.6.3 64bits
* Qt: 5.6.2
* PyQt: PyQt5 5.6 on Windows
* Operating System: Windows 10

### Dependencies
NA

**Comment by jitseniesen** [comment]
Thanks for your report. This has the same cause as issue #5680 and it is fixed by the latest version of Spyder, which is 3.2.8. So please upgrade Spyder and it should work.

I'm closing this issue; please comment and re-open if, contrary to what I say, you find that it is not fixed after upgrading.

**Comment by dpwilt** [comment]
Thank you so much for the immediate reply!  I will upgrade right away. I apologize for raising a duplicated issue. Thank you again!! Dan
