### ISSUE TITLE
Error message when starting latest spyder git clone from bootstrap.py with spyder-autopep8 plugin istalled

### ISSUE THREAD

**Issue by EBenkler** [spyder-ide/spyder#6784]
## Problem Description
Error message when starting latest spyder git clone from bootstrap.py with spyder-autopep8 plugin istalled

### What steps will reproduce the problem?
1) 
conda install spyder
2)
copy spyder-autopep8 folder to .spyder-py3/plugins/ folder
3)
conda remove spyder
git clone https://github.com/spyder-ide/spyder.git
cd spyder
python bootstrap.py

For the installation, I followed the instructions given in the spyder/spider-IDE/README.md and spyder/spider-autopep8/README.md

I have checked that I have no other spyder version installed sytem-wide, as discussed in issue #4952

### Traceback
```python-traceback
    module = _import_module_from_path(module_name, plugin_path)
    module = spec.loader.load_module(module_name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 262, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    from .autopep8plugin import AutoPEP8 as PLUGIN_CLASS  # pylint: disable=C0103
    from spyder.plugins import SpyderPluginMixin
ImportError: cannot import name 'SpyderPluginMixin'
```

## Package Versions

* Spyder version: 4.0.0.dev0 73c9e1c66
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.11.0    :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by CAM-Gerlach** [comment]
Thanks @EBenkler for the detailed report. As the issue is related to the Autopep8 plugin, not Spyder itself, it should presumably be reported to that repo instead. Please be aware that as we are currently lacking funding, we might not be able to do much to support the plugin at the moment, but its helpful to report the problem to at least document the issue and see if its an easy fix. Thanks.

**Comment by jnsebgosselin** [comment]
@EBenkler I think you need to run Spyder in the 3.x branch for this to work, not master (which will become Spyder 4) or use Spyder from Anaconda. They say master in the Readme of the plugin, but at the time, master was Spyder 3 in development.

**Comment by ccordoba12** [comment]
@EBenkler, spyder-autopep8 has not been updated in a long time, so please don't use it.
