### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by popcycle** [spyder-ide/spyder#6793]
### What steps will reproduce the problem?

I received the error below becuase conda install of spyder-reports conastantly errors.
Even after I installed the dependent packages

Pandoc then Pweave

Pweave removed and replaced many files that I believe were dependent as indicated by the errors

I ran the spyder reports conda install again....
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - spyder-reports

Current channels:

  - https://conda.anaconda.org/spyder-ide/win-64
  - https://conda.anaconda.org/spyder-ide/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch

From the Anaconda prompt I instead tried pip install spyder-reports.
  
Here is what happened when I installed the Pweave package

(base) C:\Users\cy>conda install -c conda-forge pweave
Solving environment: done

## Package Plan ##

  environment location: C:\Users\cy\Anaconda2

  added / updated specs:
    - pweave

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2n             |            vc9_0         4.7 MB  conda-forge
    markdown-2.6.11            |             py_0          56 KB  conda-forge
    conda-4.3.34               |           py27_0         535 KB  conda-forge
    bzip2-1.0.6                |            vc9_1         109 KB  conda-forge
    curl-7.59.0                |            vc9_0         359 KB  conda-forge
    libiconv-1.15              |            vc9_0         660 KB  conda-forge
    krb5-1.14.2                |            vc9_0         732 KB  conda-forge
    hdf5-1.10.1                |            vc9_2        17.6 MB  conda-forge
    pweave-0.25                |           py27_0         162 KB  conda-forge
    jpeg-9b                    |            vc9_2         308 KB  conda-forge
    freetype-2.8.1             |            vc9_0         463 KB  conda-forge
    libxml2-2.9.5              |            vc9_2         3.2 MB  conda-forge
    qt-5.6.2                   |            vc9_1        56.3 MB  conda-forge
    libssh2-1.8.0              |            vc9_2         182 KB  conda-forge
    icu-58.2                   |            vc9_0        21.9 MB  conda-forge
    libxslt-1.1.32             |            vc9_0         457 KB  conda-forge
    ca-certificates-2018.1.18  |                0         178 KB  conda-forge
    lzo-2.10                   |            vc9_0         149 KB  conda-forge
    libpng-1.6.34              |            vc9_0         538 KB  conda-forge
    sqlite-3.22.0              |            vc9_0         856 KB  conda-forge
    libtiff-4.0.9              |            vc9_0         616 KB  conda-forge
    yaml-0.1.7                 |            vc9_0         100 KB  conda-forge
    zlib-1.2.11                |            vc9_0         116 KB  conda-forge
    certifi-2018.1.18          |           py27_0         144 KB  conda-forge
    lxml-4.2.0                 |           py27_0         1.1 MB  conda-forge
    tk-8.6.7                   |            vc9_0         3.4 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       114.7 MB

The following NEW packages will be INSTALLED:

    krb5:            1.14.2-vc9_0          conda-forge [vc9]
    markdown:        2.6.11-py_0           conda-forge
    pweave:          0.25-py27_0           conda-forge

The following packages will be UPDATED:

    ca-certificates: 2017.08.26-h94faf87_0             --> 2018.1.18-0      conda-forge
    certifi:         2018.1.18-py27_0                  --> 2018.1.18-py27_0 conda-forge
    curl:            7.58.0-h7a46e7a_0                 --> 7.59.0-vc9_0     conda-forge [vc9]
    freetype:        2.8-hea645e0_1                    --> 2.8.1-vc9_0      conda-forge [vc9]
    hdf5:            1.10.1-h79de857_2                 --> 1.10.1-vc9_2     conda-forge [vc9]
    jpeg:            9b-ha175dff_2                     --> 9b-vc9_2         conda-forge [vc9]
    libpng:          1.6.34-h325896a_0                 --> 1.6.34-vc9_0     conda-forge [vc9]
    libtiff:         4.0.9-hafacce9_0                  --> 4.0.9-vc9_0      conda-forge [vc9]
    libxslt:         1.1.32-h89dfad8_0                 --> 1.1.32-vc9_0     conda-forge [vc9]
    lxml:            4.1.1-py27h31b8cb8_1              --> 4.2.0-py27_0     conda-forge
    openssl:         1.0.2n-hc64555f_0                 --> 1.0.2n-vc9_0     conda-forge [vc9]
    sqlite:          3.22.0-h8b3e59e_0                 --> 3.22.0-vc9_0     conda-forge [vc9]

The following packages will be DOWNGRADED:

    bzip2:           1.0.6-h8a7aa22_4                  --> 1.0.6-vc9_1      conda-forge [vc9]
    conda:           4.4.11-py27_0                     --> 4.3.34-py27_0    conda-forge
    icu:             58.2-h2aa20d9_1                   --> 58.2-vc9_0       conda-forge [vc9]
    libiconv:        1.15-hda2e4ec_7                   --> 1.15-vc9_0       conda-forge [vc9]
    libssh2:         1.8.0-h77a7533_4                  --> 1.8.0-vc9_2      conda-forge [vc9]
    libxml2:         2.9.7-h325896a_0                  --> 2.9.5-vc9_2      conda-forge [vc9]
    lzo:             2.10-h0bb7fe3_2                   --> 2.10-vc9_0       conda-forge [vc9]
    qt:              5.6.2-vc9hc26998b_12              --> 5.6.2-vc9_1      conda-forge [vc9]
    tk:              8.6.7-h144d9c4_3                  --> 8.6.7-vc9_0      conda-forge [vc9]
    yaml:            0.1.7-h3e6d941_2                  --> 0.1.7-vc9_0      conda-forge [vc9]
    zlib:            1.2.11-hbc2faf4_2                 --> 1.2.11-vc9_0     conda-forge [vc9]

Proceed ([y]/n)? y

Downloading and Extracting Packages
openssl 1.0.2n: ############################################################################################### | 100%
markdown 2.6.11: ############################################################################################## | 100%
conda 4.3.34: ################################################################################################# | 100%
bzip2 1.0.6: ################################################################################################## | 100%
curl 7.59.0: ################################################################################################## | 100%
libiconv 1.15: ################################################################################################ | 100%
krb5 1.14.2: ################################################################################################## | 100%
hdf5 1.10.1: ################################################################################################## | 100%
pweave 0.25: ################################################################################################## | 100%
jpeg 9b: ###################################################################################################### | 100%
freetype 2.8.1: ############################################################################################### | 100%
libxml2 2.9.5: ################################################################################################ | 100%
qt 5.6.2: ######1                                                                                               |   6%
libssh2 1.8.0: ################################################################################################ | 100%
icu 58.2: ##################################################################################################### | 100%
libxslt 1.1.32: ############################################################################################### | 100%
ca-certificates 2018.1.18: #################################################################################### | 100%
lzo 2.10: ##################################################################################################### | 100%
libpng 1.6.34: ################################################################################################ | 100%
sqlite 3.22.0: ################################################################################################ | 100%
libtiff 4.0.9: ################################################################################################ | 100%
yaml 0.1.7: ################################################################################################### | 100%
zlib 1.2.11: ################################################################################################## | 100%
certifi 2018.1.18: ############################################################################################ | 100%
lxml 4.2.0: ################################################################################################### | 100%
tk 8.6.7: ##################################################################################################### | 100%

IOError(0, 'Error')

Once I launched spyder...

 File "C:\Users\cy\Anaconda2\lib\site-packages\spyder\otherplugins.py", line 85, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder\otherplugins.py", line 109, in _import_module_from_path
    module = imp.load_module(module_name, *info)
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder_reports\__init__.py", line 11, in <module>
    from .reportsplugin import ReportsPlugin
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder_reports\reportsplugin.py", line 26, in <module>
    from pweave import Pweb, __version__ as pweave_version
  File "C:\Users\cy\Anaconda2\lib\site-packages\pweave\__init__.py", line 6, in <module>
    from . import readers
  File "C:\Users\cy\Anaconda2\lib\site-packages\pweave\readers.py", line 8, in <module>
    from urllib import request, parse
ImportError: cannot import name request

### Traceback
```python-traceback
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder\otherplugins.py", line 85, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder\otherplugins.py", line 109, in _import_module_from_path
    module = imp.load_module(module_name, *info)
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder_reports\__init__.py", line 11, in <module>
    from .reportsplugin import ReportsPlugin
  File "C:\Users\cy\Anaconda2\lib\site-packages\spyder_reports\reportsplugin.py", line 26, in <module>
    from pweave import Pweb, __version__ as pweave_version
  File "C:\Users\cy\Anaconda2\lib\site-packages\pweave\__init__.py", line 6, in <module>
    from . import readers
  File "C:\Users\cy\Anaconda2\lib\site-packages\pweave\readers.py", line 8, in <module>
    from urllib import request, parse
ImportError: cannot import name request
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.14
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.2 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
Moving to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-reports #71](https://github.com/spyder-ide/spyder-reports/issues/71) via [**ZenHub**](https://www.zenhub.com/)
