### ISSUE TITLE
Code completion: insert automatically parentheses for functions/methods

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#680]
_From [jorisvan...@gmail.com](https://code.google.com/u/101707288318167035253/) on 2011-06-03T08:49:09Z_

What steps will reproduce the problem?

1. For example if you type in the editor 'plt.', a list of possibilities will show.
2. When I choose one, for expample 'show', in the editor 'plt.show' shows up.

What is the expected output? What do you see instead? Would it be possible that not 'plt.show' appears, but at once 'plt.show()' (and with the cursor between the brackets), so you don't have to type the brackets yourself?
Because after show, brackets are always needed. What version of the product are you using? On what operating system? Spyder 2.0.11, Ubuntu 11.04

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=680_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-06-03T07:16:18Z_

I think it can be done quite easily. I'll take a look at it.

**Summary:** Code completion: insert automatically parentheses for functions/methods  
  **Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement Milestone-Release2.1 Cat-Editor

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-16T05:47:56Z_

**Labels:** -Milestone-Release2.1 Milestone-Release2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:48:27Z_

**Labels:** -Milestone-Release2.2 Milestone-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:55:49Z_

**Labels:** -Milestone-v2.2 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:14:39Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-29T14:39:30Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T06:00:20Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by goanpeca** [comment]
Is this closer to your area of expertize in spyder @blink1073 ?

**Comment by ccordoba12** [comment]
This would be cool to have!

**Comment by blink1073** [comment]
Agreed.

**Comment by ccordoba12** [comment]
We finally decided not to do this because it's really hard to determine in which situations auto-adding parens is an improvement and when it's a disadvantage.

See PR #2602 for the final decision.
