### ISSUE TITLE
Can't open on Ubuntu 18.04 Beta

### ISSUE THREAD

**Issue by justinkterry** [spyder-ide/spyder#6800]
I'm currently using the Ubuntu 18.04 beta with no GPU or OS customization, which is set to be the flagship Ubuntu distro in around a month. Opening spyder installed via apt gives this giant list of errors:

https://pastebin.com/vYMijXFv

Update: I tested exusively for Python3 versions, and tries installs via both pip and apt.

**Comment by ccordoba12** [comment]
It looks like a Qt compilation problem, for which we can't do anything about it. Qt is the graphical library used by Spyder.

For the apt packages, please open a bug in Ubuntu's bug tracker. i'm sure you'll get an answer about this problem there.

For the pip packages, please report this problem in the PyQt mailing list:

https://www.riverbankcomputing.com/support/lists

Other than that, our advice is to avoid further headaches and simply use Anaconda.

**Comment by justinkterry** [comment]
Here's the report to Ubuntu for posterity:

https://bugs.launchpad.net/ubuntu/+bug/1757981
