### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by claydavidson** [spyder-ide/spyder#6814]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
### What steps will reproduce the problem?

Don't know Markdown. New to Spyder too. Have it running in a virtualenv on windows. I installed it using pip install spyder --upgrade and it seemed to work. For a while. 

Somehow lost my console window and could not figure out how to get it back. Tried menu item for creating a new console but nothing seemed to happen.  Found a menu item to connect to an existing console based upon browsing to a json file. Did that and picked one that had todays date on it. Was rewarded with this wonderful internal error.

File "i:\progs\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1782, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "i:\progs\lib\site-packages\qtconsole\base_frontend_mixin.py", line 57, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'

hth,

clay

**Comment by ccordoba12** [comment]
> Did that and picked one that had todays date on it. Was rewarded with this wonderful internal error. File "i:\progs\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1782, in _create_client_for_kernel client.shellwidget.kernel_client = kernel_client File "i:\progs\lib\site-packages\qtconsole\base_frontend_mixin.py", line 57, in kernel_client kernel_client.iopub_channel.message_received.connect(self._dispatch) AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel' hth, clay 

This error was introduced in `jupyter_client` **5.2.3**. To fix it, please run

    pip install tornado==4.5.3
    pip install jupyter_client==5.2.2

**Comment by claydavidson** [comment]
Carlos,
Will do.
Thought I was just reporting an error to be helpful. Never expected a reply, much less a fix.
Thanks. I will keep trying this out.
Clay


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Carlos Cordoba <notifications@github.com> Date: 3/21/18  4:04 PM  (GMT-06:00) To: spyder-ide/spyder <spyder@noreply.github.com> Cc: Clay Davidson <clay@his.com>, Author <author@noreply.github.com> Subject: Re: [spyder-ide/spyder] Automatic error report (#6814) 

Did that and picked one that had todays date on it. Was rewarded with this wonderful internal error. File "i:\progs\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1782, in _create_client_for_kernel client.shellwidget.kernel_client = kernel_client File "i:\progs\lib\site-packages\qtconsole\base_frontend_mixin.py", line 57, in kernel_client kernel_client.iopub_channel.message_received.connect(self._dispatch) AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel' hth, clay

This error was introduced in jupyter_client 5.2.3. To fix it, please run
pip install tornado==4.5.3
pip install jupyter_client==5.2.2


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spyder-ide/spyder","title":"spyder-ide/spyder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/spyder-ide/spyder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ccordoba12 in #6814: \u003e Did that and picked one that had todays date on it. Was rewarded with this wonderful internal error. File \"i:\\progs\\lib\\site-packages\\spyder\\plugins\\ipythonconsole.py\", line 1782, in _create_client_for_kernel client.shellwidget.kernel_client = kernel_client File \"i:\\progs\\lib\\site-packages\\qtconsole\\base_frontend_mixin.py\", line 57, in kernel_client kernel_client.iopub_channel.message_received.connect(self._dispatch) AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel' hth, clay \r\n\r\nThis error was introduced in `jupyter_client` **5.2.3**. To fix it, please run\r\n\r\n    pip install tornado==4.5.3\r\n    pip install jupyter_client==5.2.2"}],"action":{"name":"View Issue","url":"https://github.com/spyder-ide/spyder/issues/6814#issuecomment-375094985"}}}
