### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by srharris91** [spyder-ide/spyder#6815]
## Problem Description
Failed to "Open console" when using spyder-notebook
### What steps will reproduce the problem?

* Install Spyder-notebook using pip3
* Open Spyder3
* Open a new notebook and running any simple line (e.g. A=6.)
* Open console
* Gives an error, and does not open the console to view the variables in the variable explorer

Using:
* Python 3.5.2
* Jupyter-notebook 5.4.1 (with a few extensions such as vim-bindings)
* Ubuntu 16.04 LTS
* Spyder3 using pip3

### Traceback
```python-traceback
  File "/usr/local/lib/python3.5/dist-packages/spyder_notebook/notebookplugin.py", line 424, in open_console
    None)
  File "/usr/local/lib/python3.5/dist-packages/spyder/plugins/ipythonconsole.py", line 1782, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "/usr/local/lib/python3.5/dist-packages/qtconsole/base_frontend_mixin.py", line 57, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.5.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Linux 4.13.0-36-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment]
Moving this to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #145](https://github.com/spyder-ide/spyder-notebook/issues/145) via [**ZenHub**](https://www.zenhub.com/)
