### ISSUE TITLE
Lose custom preferences after restart PC.

### ISSUE THREAD

**Issue by QuantumLiu** [spyder-ide/spyder#6817]
### What steps will reproduce the problem?

1.Set custom layout,fonts and etc.Then restart the computer and open spyder again.
2.Startup command:C:\Anaconda3\Scripts\spyder.bat -w C:/pyprojects --hide-console

## Package Versions

* Spyder:4.00.dev0
* Python:3.5.4
* Qt:5.9.1
* PyQt:5.9
* Operating System:win10 x64

**Comment by ccordoba12** [comment]
Sorry but without more details we can't help you. It probably happens because permission errors in your user home directory, which is

    C:\Users\<your user>\.spyder-py3

Please review that you have read/write permissions in that directory.
