### ISSUE TITLE
can't import cartopy with spyder 

### ISSUE THREAD

**Issue by lihu8918** [spyder-ide/spyder#6824]
## Problem Description
I installed anaconda3 (win64), and installed cartopy with conda install. when I import cartopy with spyder , it gives me this error "ModuleNotFoundError: No module named 'cartopy.crs'; 'cartopy' is not a package". However, cartopy can be successfully imported by jupyter or ipython.
How to fix this problem?

### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:3.2.6
* Python:3.6.4
* Qt:
* PyQt:
* Operating System:win10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by lihu8918** [comment]
So sorry, guys! I made a stupid mistake, I named the script with 'cartopy.py', renaming its name solved the problem!

**Comment by ccordoba12** [comment]
Great to hear you find the solution to your problem!
