### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by agarwalharsh73** [spyder-ide/spyder#6833]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Not able to open a .py file by dragging it into the IDE

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This is an apparent duplicate of #5218 and was fixed in Spyder 3.2.5, released many months ago. You can update with ``conda update spyder`` from the appropriate console (Anaconda prompt, Terminal, or your Linux command line).
