### ISSUE TITLE
How to increase the size of my tiny "Open file" window when I want to open a new file in Spyder?

### ISSUE THREAD

**Issue by thomasernste** [spyder-ide/spyder#6840]
## Problem Description

When I want to open a new file with File --> Open, the new window called "Open file" pops up and it is *extremely* small (see attached image for my screenshot). 

![screenshot from 2018-03-25 11-52-41](https://user-images.githubusercontent.com/1892013/37877595-141e0ff4-3023-11e8-89f7-4a1c953c05db.png)

So the "Open file" window is so small that I can't really see the contents of the "Look in" line and I can't see some of the names of the files in a given directory.

So every time I want to open a new file, I have to first open up this "Open file" window and then manually resize this window in order to be able to see my file names in my directories.

Is there a way to change the settings so this window is larger when I want to open a file?

**Comment by ccordoba12** [comment]
> Is there a way to change the settings so this window is larger when I want to open a file?

This is handled by the operating system, not by Spyder, so there's nothing we can do about it, sorry.

**Comment by thomasernste** [comment]
Ah, thanks. I just changed my display settings and that did fix the problem.
