### ISSUE TITLE
os problem or something deeper ?

### ISSUE THREAD

**Issue by yiorgos1973** [spyder-ide/spyder#6843]
## Description

**What steps will reproduce the problem?**

1. import os in Console
2. typing os.spawnl
3. pressed Shift+'9' to type the left parenthesis

**What is the expected output? What do you see instead?
![image](https://user-images.githubusercontent.com/31057989/37889591-ce8ceb1e-30d5-11e8-8ce3-051c08f85eb8.png)

**Please provide any additional information below**

  File "C:\Users\DOT\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\Users\DOT\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\namespacebrowser.py", line 218, in _handle_execute_reply
    self.handle_exec_method(msg)
  File "C:\Users\DOT\Anaconda3\lib\site-packages\spyder\widgets\ipythonconsole\shell.py", line 388, in handle_exec_method
    self.sig_change_cwd.emit(self._cwd)
TypeError: ShellWidget.sig_change_cwd[str].emit(): argument 1 has unexpected type 'bool'
  RemovedInSphinx17Warning)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. Please update to our latest version (3.2.8) and try again. I think this was fixed already.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
