### ISSUE TITLE
click menu and then spyder segmentation fault (core dumped)

### ISSUE THREAD

**Issue by pythonwood** [spyder-ide/spyder#6846]
## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.6
* Qt version: 4.8.6
* PyQt4 (API v2) version: 4.10.4
* Operating system: Linux 4.2.0-27-generic (ubuntu14.04)

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  1.2.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
pylint >=0.25     :  1.5.6 (OK)
```

open spyder is ok. But click menu Projects -> New Project will  crash with segmentation fault (core dumped)

**Comment by ccordoba12** [comment]
Although we try to support PyQt4, the fact is that it was discontinued about three years ago and it has serious problems in newer systems.

This is the most probable cause of your problem, so please update to PyQt5 to fix it.
