### ISSUE TITLE
ModuleNotFoundError: No module named 'pyproj'

### ISSUE THREAD

**Issue by OscarDLH** [spyder-ide/spyder#6847]
## Description

**What steps will reproduce the problem?**

1. Import pyproj library in the editor of Spyder
2. Run the program
3. "ModuleNotFoundError: No module named 'pyproj'" issue. When I run the same program in python IDLE, it works perfectly.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
You probably not installed pyproj in the right conda environment or Python interpreter. Please verify that installed it in the same Python that you're using to run Spyder.
