### ISSUE TITLE
The variable explorer/import data, does not work

### ISSUE THREAD

**Issue by VanitarNordic** [spyder-ide/spyder#6872]
## Problem Description
I tried to save a numpy array on the hard disk and import and load it later on. when I tried to load it again using `import data`, it does not import it to the variable explorer.

in the code the numpy array has initiated using `LV = np.empty(shape=[0, 2])` and filled with data in a loop. I attached the array for you to verify.

[LV.zip](https://github.com/spyder-ide/spyder/files/1865282/LV.zip)

### What steps will reproduce the problem?

1. Right click on the Variable Explorer and press Save Array to save the selected numpy array (`whatever.npy`)
2.  Reset and clear the environment
3. try to load it by Import data

### What is the expected output? What do you see instead?

I should see the data loaded in the variable exporter but it shows nothing

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.4
* Qt: 5.6.2
* PyQt: 5.6
* Operating System: Windows-10

### Dependencies

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by jitseniesen** [comment]
@VanitarNordic You called the array `LV`. By default, variables whose names are all capitals, are not shown in the Variable Explorer. I think that if you de-select "Exclude all-uppercase references" (and "Exclude capitalized references") in the Variable Explorer options menu, the array should become visible. You can open the options menu by clicking on the cog wheel icon at the upper right of the Variable Explorer.

**Comment by VanitarNordic** [comment]
@jitseniesen 

Oh yeah. I changed the file name capitals with small letters and now it works. thank you.
