### ISSUE TITLE
Run without saving for flying thoughts

### ISSUE THREAD

**Issue by shamashii** [spyder-ide/spyder#6884]
## Problem Description
Sometimes one have thoughts and want to evaluate quickly, an one key run solution is needed. Although there are 2 ways to run code: F5 or F9, but F5 needs to save first to run; F9 needs select all to run.

### What steps will reproduce the problem?

1. New temp py file and type some lines code.
2. Without saving, then want to run code with one key press.
3. 

### What is the expected output? What do you see instead?
Run temp code snippets with one key press. 2 probably ways:
1,When creating a new file then immediately saving on disk;
2,Some function operation like "ctrl-a first, then F9" in one key press.(Note:  [Pyzo](http://www.pyzo.org/) )

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> Without saving, then want to run code with one key press.

You can create a cell that embraces all the contents of your file (by creating a comment that starts with `#%%`) and then evaluate with `Shift+Enter` or `Ctrl+Enter`.

> Without saving, then want to run code with one key press.

This is unfortunately not possible because we need to read the contents of the file on disk to pass them to `runfile`.
