### ISSUE TITLE
Remove support for PyQt4

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#6889]
Our reasons to do it are:

* Qt4 was discontinued in December 2015, more than two years ago.
* Spyder is quite buggy while running in PyQt4, as reported by our own developers.
* None of the core devs is running Spyder in PyQt4.
* Several of our tests segfault in PyQt4.
* By removing support for PyQt4 we could employ our limited resources in improving other aspects of the project.

TODO

- [x] Remove PyQt4 from our requirements and raise PyQt5 requirement to 5.5
- [x] Remove PyQt4 from our tests.

**Comment by goanpeca** [comment]
@ccordoba12 we could perhaps start testing with qt 5.9 ?

https://anaconda.org/rdonnelly/qt

**Comment by ccordoba12** [comment]
Sure, we can test with 5.6 and 5.9, once we remove the PyQt4 slots.
