### ISSUE TITLE
error whenn 

### ISSUE THREAD

**Issue by YIJUNDONGMIT** [spyder-ide/spyder#6896]
### What steps will reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:
* Python:
* Qt:
* PyQt:
* Operating System:

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Closing because this is empty.

**Comment by CAM-Gerlach** [comment]
No substantive information provided. If you can describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, then please re-open.
