### ISSUE TITLE
Flatpak support?

### ISSUE THREAD

**Issue by JakobJakobson** [spyder-ide/spyder#6898]
Dear developers,

have you considered Flatpak  (http://docs.flatpak.org/en/latest/index.html) support so far?

Even though it means implementing yet another distributing way of your software, on the long run it could simplify your life as it is (ideally?) distribution independent.

Regards,

Jakob

**Comment by ccordoba12** [comment]
Sorry, the only distribution we recommend and give support to is Anaconda. Anything else would be a burden in our very limited resources. Besides, Spyder is not really that useful without all the scientific libraries it's integrated with.

**Comment by ccordoba12** [comment]
That's great news! Thanks for sharing @kevinsmia1939!

**Comment by kevinsmia1939** [comment]
> currently the flatpak is listed as "Unverified"
> 
> are there plans to make it "verified" in the future ?

Verification on Flathub required that original developer maintain it, but as they are not interest to do so, it is likely to remain unverified for sometime.

**Comment by iloveakitas** [comment]
> > currently the flatpak is listed as "Unverified"
> > are there plans to make it "verified" in the future ?
> 
> Verification on Flathub required that original developer maintain it, but as they are not interest to do so, it is likely to remain unverified for sometime.

https://docs.flathub.org/docs/for-app-authors/verification
It can get verified if the developers authorize it: "Verification is the process by which Flathub and developers confirm that an app is published by the original developer or an authorized party. Verification is done by verifying the developer's identity through their ownership of the domain associated with the app ID."
