### ISSUE TITLE
Object-Inspector shows no Headings when invoked from editor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#690]
_From [faucon.e...@gmail.com](https://code.google.com/u/100607043469122138931/) on 2011-06-16T02:01:30Z_

What steps will reproduce the problem?

 An example (reproducable with other docstrings as well)
1. in the editor type "numpy.linspace("
2. the object inspector shows documentation of the function, but without headings (they are left out)
3. type numpy.linspace( in the console
4. the object inspector shows the documentation of the function, this time rendered right with all headings What version of the product are you using? On what operating system? Spyder developement version (860ec3f6d9fe) on debian sid.

some screenshots are attached to show the difference.

**Attachment:** [from_editor.png from_console.png](http://code.google.com/p/spyderlib/issues/detail?id=690)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=690_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-28T21:29:47Z_

I'm working on this. It's not an easy fix, so it'll be released after 2.1, in a month or so.

Thanks for reporting and for your interest in Spyder!

**Status:** Started  
  **Labels:** Cat-ObjectInspector

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-28T23:53:45Z_

I would certainly have to re-read the code to be sure of this but as I remember it, the header is generated with Spyder utilities (not 'rope') which require the corresponding object reference (and we don't have it in the editor). 

So basically, to close this issue, we could simply say that -by design- the header is only available when the object inspector is called from the console... But, again, I didn't think about it for long so maybe, Carlos, you have another idea on this.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-10T20:35:35Z_

This issue was updated by revision 67837f6c4008 .


-. This was breaking the work of Sphinx.
-. We still have to add the signature at the beginning of docstrings.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-10T20:46:55Z_

Sorry Pierre, I hadn't read your comment before pushing my commit. The problem was rope was adding a 2 spaces indent to docstrings, which I fixed with in rope_patch.

By the header you mean the signature, right? That's still missing, as I mentioned, but I think I could use the function you defined to get it because it works with the inspect module, if I remember correctly.

On the other hand, I think the reporter meant by headers the Html sections (like Parameters or Returns) which are shown correctly now.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-11-12T02:47:31Z_

Ok I misunderstood the issue then, no problem. So we may close it because I don't think we can access to the object signature through the inspect module as rope do not provide the object itself. Or am I missing something? (maybe I am missing something: I'm curently at the circus with my wife and son (it's the intermission!))

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-12T06:15:53Z_

Please leave it open. If I couldn't get it through the inspect module, I think I could use the same functions you're using to generate the calltip, which are taken from rope, right?

Enjoy the circus!

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-12-08T15:25:09Z_

This issue was updated by revision 68f75f829959 .


There is still some work to do so that signatures and notes are the same when
viewed from the Editor and the Console.

**Status:** Fixed

**Comment by ironbar** [comment]
I'm having the same issue on spyder 3.1.4

**Comment by ironbar** [comment]
Reverting to 2.3.9 solved the issue.
