### ISSUE TITLE
don't know what happened but i report 

### ISSUE THREAD

**Issue by celdeldel** [spyder-ide/spyder#6903]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/anaconda3/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/client.py", line 237, in stop_button_click_handler
    self.interrupt_kernel()
  File "/anaconda3/lib/python2.7/site-packages/spyder/widgets/ipythonconsole/client.py", line 393, in interrupt_kernel
    self.shellwidget.request_interrupt_kernel()
  File "/anaconda3/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 345, in request_interrupt_kernel
    self.interrupt_kernel()
  File "/anaconda3/lib/python2.7/site-packages/qtconsole/frontend_widget.py", line 638, in interrupt_kernel
    self.kernel_manager.interrupt_kernel()
  File "/anaconda3/lib/python2.7/site-packages/jupyter_client/manager.py", line 406, in interrupt_kernel
    self.signal_kernel(signal.SIGINT)
  File "/anaconda3/lib/python2.7/site-packages/jupyter_client/manager.py", line 426, in signal_kernel
    self.kernel.send_signal(signum)
  File "/anaconda3/lib/python2.7/subprocess.py", line 1247, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
WARNING:traitlets:kernel died: 18.0055680275

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.26.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  4.2.1 (OK)
pylint >=0.25     :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
> don't know what happened but i report 

Sorry, but without knowing the exact circumstances that caused this, we can't help you. Could you tell us what were you doing when you get this error?

**Comment by CAM-Gerlach** [comment]
Seems similar or identical to #6880 , just on a different Spyder version.

**Comment by celdeldel** [comment]
@ccordoba12 I was training a CNN : 


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.conv3 = nn.Conv2d(16, 32, 5)
        self.fc1 = nn.Linear(18432, 500)
        self.fc2 = nn.Linear(500, 84)
        self.fc3 = nn.Linear(84, 2)


    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        #print(x.shape)
        x = self.pool(F.relu(self.conv3(x)))
        x = x.view(-1, 18432)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

**Comment by ccordoba12** [comment]
What is CNN and how we can install it?

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
