### ISSUE TITLE
Notebook crashed

### ISSUE THREAD

**Issue by VolkerBergen** [spyder-ide/spyder#6927]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/volker.bergen/anaconda3/envs/py36/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 359, in close_client
    nb_contents = nbformat.read(path, as_version=4)
  File "/Users/volker.bergen/anaconda3/envs/py36/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/63/zhs0n9ps13gb512434w1c8kcrgy342/T/spyder-volker.bergen/notebooks/untitled0.ipynb'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Moving to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #148](https://github.com/spyder-ide/spyder-notebook/issues/148) via [**ZenHub**](https://www.zenhub.com/)
