### ISSUE TITLE
Inconsistent behaviour between Spyder and Python3 console when using matplotlib (TypeError)

### ISSUE THREAD

**Issue by pierrebenoit** [spyder-ide/spyder#6930]
## Problem Description

Script that works fine under Spyder (and also under Rodeo, don't know if this matters, I'm migrating to Spyder now), raises a Matplotlib TypeError when run from the console/terminal.

I wonder what is Spyder doing differently: is it grabbing other modules? 

The whole thing is puzzling and unsettling (since I expect to be able to test in Spyder and distribute the script).

matplotlib is 2.2.2, pandas is 0.22.0 in both cases.

Tried to get help in [stackoverflow](https://stackoverflow.com/questions/49720922/python3-matplotlib-plot-typerror-plot-ok-under-rodeo), but no luck: 

### What steps will reproduce the problem?

1. running  the attached script both in Spyder and from the terminal/console.

from dateutil.parser import parse
import matplotlib.pyplot as plt

l=["2015-04-13 Thu 14:31", "2015-04-10 Wed 15:04", "2015-04-07 Tue 14:34", "2015-04-04 Mon 11:44", "2015-04-01 Sun 12:46"]

dates = [parse(x).date() for x in l]
times = [parse(x).time() for x in l]

fig = plt.figure(figsize=(8, 5))
ax = fig.add_subplot(111)
plt.plot(dates,times,marker='o')

### What is the expected output? What do you see instead?
Expected: getting a png rendered in both Spyder and from the Terminal.
Instead: TypeError when running from the terminal

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
  File "file.py", line 12, in <module>
    plt.plot(dates,times,marker='o')
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/pyplot.py", line 3358, in plot
    ret = ax.plot(*args, **kwargs)
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 1528, in plot
    self.add_line(line)
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1932, in add_line
    self._update_line_limits(line)
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/axes/_base.py", line 1954, in _update_line_limits
    path = line.get_path()
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/lines.py", line 951, in get_path
    self.recache()
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/lines.py", line 657, in recache
    y = _to_unmasked_float_array(yconv).ravel()
  File "/home/d4/.local/lib/python3.5/site-packages/matplotlib/cbook/__init__.py", line 2050, in _to_unmasked_float_array
    return np.asarray(x, float)
  File "/home/d4/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 492, in asarray
    return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'datetime.time'

## Package Versions

* Spyder: Spyder 3.1.3
* Python: 3.5.3 (in both cases)
* Qt:
* PyQt: PyQt5
* Operating System: Debian Stretch

### Dependencies

```
PASTE DEPENDENCIES HERE
```
jedi >=0.9.0     :  0.11.1 (OK)
matplotlib >=1.0 :  2.2.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.5 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
> File "/home/d4/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 492, in asarray
return array(a, dtype, copy=False, order=order)
TypeError: float() argument must be a string or a number, not 'datetime.time'

Sorry but this is a problem in Numpy, not in Spyder, so it's up to you to figure out its cause.

**Comment by jitseniesen** [comment]
@pierrebenoit That's surprising. It is the same on my system (Fedora), so it's probably not a weird installation error. I don't know the exact cause, but I noticed that if you add `import pandas` at the top of your script, the error goes away when running from console. So my best guess is that it has to do with Spyder secretly importing pandas, possibly in https://github.com/spyder-ide/spyder/blob/3.x/spyder/utils/site/sitecustomize.py#L286 .

**Comment by ccordoba12** [comment]
@jitseniesen, should we report this upstream? If so, to what project?

**Comment by pierrebenoit** [comment]
No need to report it, it's a known issue in matplolib/pandas. There's something about it in [stackoverflow](https://stackoverflow.com/questions/47404653/pandas-0-21-0-timestamp-compatibility-issue-with-matplotlib).

**Comment by jitseniesen** [comment]
> No need to report it, it's a known issue in matplolib/pandas. There's something about it in stackoverflow.

I came to the same conclusion.
