### ISSUE TITLE
False variable assigned but never used warning shown on ide

### ISSUE THREAD

**Issue by piyushjn08** [spyder-ide/spyder#6935]
Hello,

Spyder ide is giving false warning of variable being assigned but unused on spyder ide,

The problem occurs when we have a variable which is declared above if statement and is used inside if and else statement. same variable used inside 'if' is fine but it shows warning when used inside 'else' at the same time.

example:

steps = 0
    if(a>b):
        steps = abs(dx)
    else:
        steps = abs(dy)

for 'steps' variable inside else it shows warning

A snapshot as been attached
![screenshot from 2018-04-10 11-27-56](https://user-images.githubusercontent.com/35859644/38538662-6a6c0cd0-3cb2-11e8-90ea-48c4fe03e040.png)

**Comment by ccordoba12** [comment]
This probably happens because you're creating an assignment for `steps` but you're not using below that point.

In any case, this is not something we can fix. We simply show the warnings reported by [pyflakes](https://github.com/PyCQA/pyflakes), which is the library we rely on for this task.
