### ISSUE TITLE
Tried to link to a different Python.exe. Hit Error. Spyder told me to report this.

### ISSUE THREAD

**Issue by jordanlui** [spyder-ide/spyder#6939]
## Description
Hitting host of issues with Spyder working in Py2 and Py3 env in Anaconda so I tried to link my Python IDE to an alternate Python.exe, hoping that this can help me spin up a kernel to execute code. I know I'm probably making  a lot of guesses but the software hit a snag and told me to report to GitHub.

**What steps will reproduce the problem?**

1. Open Spyder
2. Connect to Existing Kernel: Path to file: "C:\Users\Jordan\Anaconda3\envs\mypy2\python.exe"
3. Crash

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Jordan\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1047, in create_client_for_kernel
    password)
  File "C:\Users\Jordan\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1724, in _create_client_for_kernel
    kernel_client.load_connection_file()
  File "C:\Users\Jordan\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 494, in load_connection_file
    info = json.load(f)
  File "C:\Users\Jordan\Anaconda3\lib\json\__init__.py", line 296, in load
    return loads(fp.read(),
  File "C:\Users\Jordan\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
> File "C:\Users\Jordan\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to

If this is the error you're getting, it means you have Python 3 in the PYTHONPATH or PATH of your Python 2 environment.

That's not a problem with Spyder but with how you're managing things.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
