### ISSUE TITLE
internal console opening everytime

### ISSUE THREAD

**Issue by nikhilamunipalli** [spyder-ide/spyder#6950]
## Description

**What steps will reproduce the problem?**

1. load spyder
2. type code
3. run code

**What is the expected output? What do you see instead?**
output expected in iPython console
but internal console opens everytime inspite of disabling display
**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 2.7.14
* Qt Versions: 5.9.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.5.0 :  1.5.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
matplotlib >=1.0 :  2.2.2 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.8.4 (OK)

```

**Comment by ccordoba12** [comment]
> but internal console opens everytime inspite of disabling display

This most probably happens because an error is showing there. Please copy what's shown in the internal console and paste it here to try to help you better.

**Comment by CAM-Gerlach** [comment]
You also have a very old version of Spyder; its around a year old or more. Please update with ``conda update spyder`` (or ``pip update spyder`` if you don't use Anaconda).

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
