### ISSUE TITLE
Spyder pausing/lagging for about 8 seconds before running inline

### ISSUE THREAD

**Issue by badlyans** [spyder-ide/spyder#6953]
## Problem Description

2 week following a fresh install of Anaconda on new PC, Spyder console started pausing for several seconds before returning results of executed code.  

For example:  In console I type in "1+1" and hit enter I get back "2" after about 5 seconds.

If I hit the "stop the current command" button I get the results back immediately.
If I run the same script/code from python in windows cmd or in Atom it runs as expected.

I have tried reboot, killing nonessential processes, reinstalling Anaconda, reinstalling python and Spyder only with no success.

### What steps will reproduce the problem?

1.  Running code in console with any level of complexity - example "1+1"
2.  Running code using run file button or F5
3.  Running one line of code from file or F9

### What is the expected output? What do you see instead?

I expect output. 
I see 5 second lag before output

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder:   3.2.8
* Python:   3.6.5 64bits
* Qt:          5.9.3 
* PyQt:      5.9.2
* Operating System:  Windows 7 Enterprise 64-bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by CAM-Gerlach** [comment]
Thanks for the report. Can you try running the same lines in ``jupyter qtconsole``? Do you see a similar lag there? Do you have any security, IDS, firewall, antivirus, etc. software installed that could be causing this? Also, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues. If we don't hear from you after one week (7 days), the issue will be closed. Thanks.

**Comment by CAM-Gerlach** [comment]
>  Could this be some sort of a display setting?

Nope, none that I know of, unless it has something to do with ``sympy`` support being enabled or something (make sure everything under Preference > IPython Console > Advanced is disabled).

Other than that, try running ``spyder --reset`` at the Anaconda Prompt in whatever environment Spyder is installed in (if its in the default ``base`` env, it should already be activated automatically) to make sure it isn't some preference setting that's slowing Spyder down.

Beyond that or a weird security software issue, I'm not really sure what it could be. @ccordoba12 Any thoughts?

**Comment by ccordoba12** [comment]
None from me, sorry.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12

**Comment by badlyans** [comment]
Thank you both.  I will wait for the security team to help me test the antivirus theory and possibly delete my windows profile and try a fresh install again before updating.

**Comment by CAM-Gerlach** [comment]
@badlyans Any news? Did the security team fix it, and if not did you try the fixes we suggested? Thanks.

**Comment by badlyans** [comment]
Yes, They updated my Dell encryption software which helped a bit and when we disabled Symantec it was much improved.  Obviously that was just a test and we can't leave that feature off so when I have time I will delete my windows profile and create a new one.
Thanks again!

**Comment by CAM-Gerlach** [comment]
Okay, thanks. Best of luck!

**Comment by hardidi** [comment]
Hi there,

I am experiencing the exact same issue with my ipython console freezing for about 1-2s when executing even the simplest command within spyder. Similarly, if I press the "Stop current command" button, the result appears immediately. However, running the same command in ipython from a command line, or using the jupyter qtconsole is fine as well. I don't have the option of turning my AV off neither..
This is kind of making spyder useless, unfortunately. Any help is greatly appreciated!

Thanks,
Michael

This is what I'm using:

Spyder: 3.3.0
Python: 3.6.5 64bits
PyQt: 5.9.3
Operating System: Windows 10 Enterprise 64-bit
AV/Firewall: Symantec Endpoint Protection
Dell Latitude I7

**Comment by CAM-Gerlach** [comment]
@hardidi The problem is very likely with Symantec falsely detecting the ZeroMQ connection between Spyder/Qtconsole and IPython (all things outside our control) as malicious as the previous user stated, but to confirm that you (or your IT department) should temporarily disable it for a few moments re-test Spyder to confirm the lag is reduced or eliminated. If that's that case, you (or they) should then be able to add Spyder, Jupyter, QtConsole, etc. to your firewall and AV's whitelists, and create allow rules along the lines of [those suggested in the IPython documentation](https://ipython.org/ipython-doc/3/notebook/public_server.html#firewall-setup), that should have the same positive effect without reducing or eliminating whatever modest protection an AV gives these days against the most dangerous enterprise threats.

**Comment by hardidi** [comment]
@CAM-Gerlach Thanks for the very quick response! I will try to get my IT department to temporarily deactivate the AV and check spyder again. Will update you once done.

**Comment by stud-many** [comment]
I have exactly the same issue with Spyder lagging for up to 20 seconds or so.
Using F5 key or pressing the Play-Button results in the lag. iPython-console and everything else works fine.

**Comment by hardidi** [comment]
Not sure if replying here works.
Using Windows' default antivirus fixed the issue for me. Sorry for
forgetting to update this topic.

**Comment by stud-many** [comment]
Thanks for your reply. I read through this topic so I already saw your solution. But only using the windows antivirus is not working for me somehow. Even deactivating is not necessarily speeding it up.

**Comment by CAM-Gerlach** [comment]
Hey @stud-many ; can you make sure you don't have any firewalls or other security software (IDS/IPS, etc) installed? Anything special about your system configuration? Can you describe how you installed Spyder (standalone installer, pip, Anaconda, etc) and your OS and Spyder versions? Could you be a little more specific about when the slowdown does and doesn't occur, and about how long the lag is? Thanks!
