### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Msabih** [spyder-ide/spyder#6956]
Spyder crashes while closing jupyter notebook. 
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
Please describe step by step how you got this error so we can reproduce it in our side. If you fail to do that, we'll close this issue in a week from now.

Also, please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

to see if you are able to fix this problem by following it.

**Comment by CAM-Gerlach** [comment]
> Spyder crashes while closing jupyter notebook.

Jupyter notebook *within Spyder*, i.e. the ``spyder-notebook`` plugin? If so, this belongs in that repo, and be aware it currently has known issues and isn't maintained for lack of funds.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
