### ISSUE TITLE
Crash when deleting a file in file explorer opened in editor

### ISSUE THREAD

**Issue by intelpen** [spyder-ide/spyder#6958]
## Description

**What steps will reproduce the problem?**

1. delete a file in file explorer opened in editor
2. Spyder crushes

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "c:\program files\python35\lib\site-packages\spyder\plugins\editor.py", line 1356, in close_file_in_all_editorstacks
    index = editorstack.get_index_from_filename(filename)
  File "c:\program files\python35\lib\site-packages\spyder\widgets\editor.py", line 1345, in get_index_from_filename
    return filenames.index(filename)
ValueError: 'E:\\science\\info\\Competitions\\CodeJam2018\\Round1A\\p1_waffle_choppers\\p1_waffle_choppers_numpy.py' is not in list

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.5.2
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
Good point. We'll try to fix it in our next release.
