### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by gkvallis** [spyder-ide/spyder#6971]
1. Open spyder from command line with 'spyder'
2. Opening almost any command from the menu when 'notebook' is selected at the base of the window.
3. 'Spyder has encountered an intermal problem' box appears

**Comment by ccordoba12** [comment]
> Opening almost any command from the menu when 'notebook' is selected at the base of the window.

What do you mean by this? Please post a screenshot of what you're trying to do before the error appears.

**Comment by gkvallis** [comment]
This might be a false alarm. I tried to open a notebook from the main Open menu in Spyder, rather than from the little gear wheel to the top right of the window. Still, I'm surprised that Spyder should throw an internal error and auto-generate a report given something as innocuous as that. I'll investigate further to see if it happens in a serious situation,

**Comment by gkvallis** [comment]
Fine with me to close this issue. My anaconda distribution was evidently getting disjointed and I did a complete reinstall. After a further update of qt everything works now, and Spyder no longer throws the strange 'internal error' panel.
