### ISSUE TITLE
cannot saving ipynb

### ISSUE THREAD

**Issue by BenedictusAryo** [spyder-ide/spyder#6981]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_notebook\notebookplugin.py", line 402, in save_as
    nb_contents = nbformat.read(original_path, as_version=4)
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbformat\__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PSI\\AppData\\Local\\Temp\\spyder\\notebooks\\untitled0.ipynb'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
This is an error with Spyder notebook, not the core Spyder IDE. Therefore, please report it in the spyder-ide/spyder-notebook repo, although be aware due to a lack of funds at present, it may not be able to be fixed for a while.
