### ISSUE TITLE
Unable to type single or double quotes on Sypder Editor (3.6), neither on IPython

### ISSUE THREAD

**Issue by pedro612xyz** [spyder-ide/spyder#6982]
## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Please describe in detail the circumstances in which the error occurred, and post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can. Otherwise, your issue will likely have to be closed after one week (7 days). 

Also, if it occurs again, please reference [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) section for some basic steps to try to fix it or at least narrow it down for us. Thanks, and best of luck!

**Comment by jitseniesen** [comment]
@pedro612xyz It's not clear what you mean, but maybe your system is set up so that single and double quote are used to type accents. If you type `'` and then `e`, you get an `é` (e with accent). On such systems, you need to type `'` and then a space to get a single quote.

**Comment by pedro612xyz** [comment]
@jitseniesen Thanks by the interesting.
On the shell, (bash "GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)"),
I can type both ' and ", without problems. Also if I type ' and then e I got é.
However, if I call spyder, from the same shell, I cannot type ' or ", even with the space.

**Comment by pedro612xyz** [comment]
@jitseniesen Let me add two other tests.

If I just call "ipython", thus text mode only, on the shell, that works fine, i.e. I can type ' or ".
However, I've the problem, i.e. not able to type ' or ",  if I call qtconsole, by "jupyter qtconsole", thus I'll be on GUI. 
Jupyter QtConsole 4.3.1
Note: On other GUI tools there is no such problem, for instance soffice, firefox, gedit,

**Comment by pedro612xyz** [comment]
@CAM-Gerlach 
I have the same problem on Sypder Editor as well.

**Comment by CAM-Gerlach** [comment]
Hey; did you try the steps listed in the linked sections of the Troubleshooting Guide as requested in my post above? If that didn't fix it, can you provide the rest of the information requested in the Calling for Help section as linked above? Thanks.

**Comment by pedro612xyz** [comment]
@CAM-Gerlach 
unfortunately the Troubleshooting Guide didn't help and I think I provided the necessary data already.
Anyhow, since I can have the tool working without problems in an another machine, a Ubuntu 17, let's close this case.
Thanks all!!!

**Comment by pedro612xyz** [comment]
nfortunately the Troubleshooting Guide didn't help and I think I provided the necessary data already.
Anyhow, since I can have the tool working without problems in an another machine, a Ubuntu 17, let's close this case.
Thanks all!!!

**Comment by CAM-Gerlach** [comment]
Thanks for the quick followup, and glad to hear you got it working on another machine.

> I think I provided the necessary data already.

You were very helpful; I didn't meant to dock that, sorry. Its just that we weren't able to reproduce it with the data we had, and thus it was likely machine specific, so I was trying to track down that.

> Anyhow, since I can have the tool working without problems in an another machine, a Ubuntu 17,

Great news. Something machine specific, as we suspected, though hopefully you are able to figure out what at some point. Best of luck!

**Comment by ccordoba12** [comment]
@Mark3xtrm, are you using Spyder with Anaconda? Or through VNC in a remote machine?

**Comment by ccordoba12** [comment]
Ok, the libraries on which Spyder depends on on Linux are not well packaged by Anaconda. So, please install and run Spyder from Conda-forge with the following commands:

    conda create -n spyder-env -c conda-forge spyder python=3.10
    conda activate spyder-env
    spyder

and let us know if that fixes the problem for you.
