### ISSUE TITLE
qt5 error

### ISSUE THREAD

**Issue by arunabhcode** [spyder-ide/spyder#6985]
## Description

**What steps will reproduce the problem?**

1. install opencv
2. 
3. 

**What is the expected output? What do you see instead?**
package should be imported as it gets imported just fine in terminal but instead i get
ImportError: /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5: undefined symbol: _Z10qAllocMoreii
**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.1.4 
* Python Version: 3.5.2
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pep8 >=0.6       :  1.7.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.2 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
matplotlib >=1.0 :  2.2.2 (OK)
sympy >=0.7.3    :  None (NOK)
pylint >=0.25    :  1.8.4 (OK)

```

**Comment by CAM-Gerlach** [comment]
> Spyder Version: 3.1.4

That Spyder version is a year old or more; please update to the latest version, 3.2.8, with ``conda update spyder`` (or ``pip update spyder`` if you don't use Anaconda). Furthermore, does this occur outside of Spyder, e.g. if you try importing it in ``jupyter qtconsole``?

Also, please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by arunabhcode** [comment]
Updating it solves it. Thank you.
