### ISSUE TITLE
list of variables for template editing?

### ISSUE THREAD

**Issue by TreeFrogBandit** [spyder-ide/spyder#6995]
Not a problem per se. but I'm looking to set up a standard template for my new code with a few lines of code already written. I notice that there is an option to add the date `%(date)s` to the template. Are there any other variables I can use, or is it just this?

Thanks

**Comment by CAM-Gerlach** [comment]
Thanks for reporting; good points. Currently, there is only `%(date)s` and `%(username)s` though there have been on and off plans to add more. In effect, this is a duplicate of #2884 . Feel free to add your input over there, or even submit a patch with improvements.
