### ISSUE TITLE
Save as dialog stays open when trying to save figures in the IPython console

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#7009]
### What steps will reproduce the problem?

```
import matplotlib.pyplot as plt
plt.plot([1, 0])
```

A plot is displayed inline.

Right click on inline plot -> save image as...

A window appear, I select a place to save, the window disapear.

Go to another desktop (with cmd + left)

Come back to the spyder desktop

The window is back! it is gray, unresponsive, and unclosable.

## Package Versions

* Spyder version: 3.3.0.dev0 c7275ba40
* Python version: 3.6.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Darwin 17.5.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.0 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.7.4 (OK)
```

**Comment by impact27** [comment]
![gray](https://user-images.githubusercontent.com/6740194/39123066-98e578a8-46ee-11e8-8fbe-b1a62523829f.png)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix it in a future release.

**Comment by CAM-Gerlach** [comment]
Couldn't (easily) reproduce it on Windows 8.1 and Spyder 3.2.9, but I'm not terribly surprised since I can't just switch to another desktop, and only alt-tabbed instead.

**Comment by ccordoba12** [comment]
It's probably a macOS bug only. Bad thing none of us use it as its main OS (I have a VM, but that's it).

**Comment by CAM-Gerlach** [comment]
If you want, I know at least one person who uses macOS regularly with Spyder who can test something for us...

**Comment by ccordoba12** [comment]
If you can ask him to give us a hand, that'd be great!

**Comment by CAM-Gerlach** [comment]
Okay. Beyond having him try to replicate it, anything else I should ask him to try?

**Comment by ccordoba12** [comment]
Nope

**Comment by CAM-Gerlach** [comment]
Done, standing by.

**Comment by impact27** [comment]
I have two additional observations:
- I can create as many windows as I like (at least 3) by clicking 
    "Save Image As..."
    "Cancel"
    "Go to left desktop""
    "Come back"
    "Repeat"
Each change of desktop creates one image (Even if I save several times)
- I can revive (un-grey) the windows by using mission control:
If I go to the greyed window from mission control, either by having it in the foreground when switching desktops or by using mission control to switch window instead of clicking on it,  it comes back to live. (I can't actually save anything but I can select folders and close the window.)
If I close it in this way a second time, It doesn't come back.

**Comment by CAM-Gerlach** [comment]
@impact27 I can't find the commit ``c7275ba40`` anywhere in mainline Spyder--did you make changes to your branch? If so, does this still happen if you ``checkout`` the latest 3.x? How about stable Spyder 3.2.8?

**Comment by pbitzer** [comment]
@CAM-Gerlach Under 3.2.8, I am unable replicate this. I'm able to "Save Image As" and navigate the dialog successfully...even after switching Spaces/Desktops. I've tried two different configs, although both are Sierra and it looks the OP is High Sierra:

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Darwin 16.7.0
and 
* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 16.7.0

**Comment by CAM-Gerlach** [comment]
Thanks, @pbitzer . You certainly covered the parameter space quite well with Qt and Python; High Sierra and the (apparently modified) 3.3dev Spyder version the OP is using are the only remaining free variables. It looks like unless it is something environment-specific, it is probably connected to one of those two—there have been known issues in the past with High Sierra and earlier versions of Qt (5.6), though not sure if that's still true of 5.9.

@impact27 To rule out other variables, can you test with Qt 5.9.4, Spyder 3.2.8 (and the latest mainline Spyder ``3.x`` from here) and Python 3.6.5? If you update python with conda, make sure you update ``python,app`` as well (via ``conda update python python.app`` to make sure to avoid an Anaconda issue. Thanks.

**Comment by impact27** [comment]
I can reproduce with:

Spyder 3.3.0.dev0 (Commit: 01f1f429c)
Python 3.6.5 64bits, 
Qt 5.10.1, 
PyQt5 5.10.1 on Darwin 

Running from source with bootstrap.py

**Comment by CAM-Gerlach** [comment]
Okay, thanks. That makes it even less likely to be a specific Qt version, and rules out anything different with Python, as well as any changes on your end.

> on Darwin

What OS version, just to be clear? Still High Sierra?

> Spyder 3.3.0.dev0 (Commit: 01f1f42)

Can you test with Spyder 3.2.8 as requested?

**Comment by impact27** [comment]
Can still reproduce on:

Spyder 3.2.8
Python 3.6.5 64bits, Qt 5.9.3, PyQt5 5.9.2 on Darwin 
installed from pip 
(Which apparently downgraded PyQt5)
On macOS 10.13.4

**Comment by CAM-Gerlach** [comment]
> (Which apparently downgraded PyQt5)

We don't fully support Qt/PyQt 5.10 yet; its still rather buggy.

> installed from pip

Can you install everything with Anaconda instead, as the [Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ),) requests? ``pip`` is well known to cause all manner of problems, particularly with packages that need heavy compilation like ``Qt``, so its best to rule that out, although it seems increasingly probable that something with High Sierra is indeed the most likely culprit, You can also try the other steps listed there as appropriate, under the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) subsections.

**Comment by goanpeca** [comment]
@impact27 is this still an issue?

**Comment by impact27** [comment]
No I can't reproduce anymore, I will reopen it if I see it again.
