### ISSUE TITLE
Error while opening Spyder first time after boot

### ISSUE THREAD

**Issue by kulchidambar** [spyder-ide/spyder#7021]
## Description

**What steps will reproduce the problem?**

1. When opening first time
2. 
3. 

**What is the expected output? What do you see instead?**
Normal spider window

**Please provide any additional information below**
No additional information

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Please post the error message you get when Spyder fails to start. Else we can't help you.

**Comment by kulchidambar** [comment]
Dear Sir,
I was not able to catch the error. But I will let you know the error report if I get this error again.
Thanking you.
Chidambar Kulkarni

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Please try the steps listed in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

Closing this now. Please re-open if it happens again and you can provide detailed information as to what occured. Thanks, and best of luck!
