### ISSUE TITLE
Error message box popped up

### ISSUE THREAD

**Issue by chipmuenk** [spyder-ide/spyder#7028]
I have no idea - the message box stating that an error has occured just popped up

**What steps will reproduce the problem?**

1.  Maybe updating spyder (conda update spyder) while an instance of spyder is running
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/muenker/anaconda2/lib/python2.7/site-packages/spyder/utils/introspection/plugin_client.py", line 158, in _on_finished
    self.run()
  File "/home/muenker/anaconda2/lib/python2.7/site-packages/spyder/utils/introspection/plugin_client.py", line 104, in run
    raise IOError('Could not start %s' % self)
IOError: Could not start <spyder.utils.introspection.plugin_client.PluginClient object at 0x7fcbda467640>

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.11
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.2.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.1.3 (OK)
pandas >=0.13.1   :  0.18.1 (OK)
numpy >=1.7       :  1.11.0 (OK)
sphinx >=0.6.6    :  1.4.1 (OK)
rope >=0.9.4      :  0.9.4 (OK)
jedi >=0.9.0      :  0.9.0 (OK)
psutil >=0.3      :  4.3.0 (OK)
nbconvert >=4.0   :  4.2.0 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.24 (OK)
qtconsole >=4.2.0 :  4.2.1 (OK)
IPython >=4.0;<6.0:  4.2.0 (OK)
pylint >=0.25     :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
> Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4

We're about to remove support for PyQt4. Please update to PyQt5 and try again.

**Comment by chipmuenk** [comment]
ok, sorry for the unclear error message - spyder made me do it :-)
