### ISSUE TITLE
LombScargle not fully working

### ISSUE THREAD

**Issue by nadiyaikon** [spyder-ide/spyder#7033]
## Description

**What steps will reproduce the problem?**

1. LS = LombScargle(t, y, normalization='psd')
2. frequency, power = LS.autopower()
3. print (LS.false_alarm_probability(power.max()))

**What is the expected output? What do you see instead?**
One number corresponding to the probability of the peak being significant should be printed. However, this is what I get instead:
__init__() got an unexpected keyword argument 'normalization'

And if I remove the normalization part from within the brackets, then this is what I get:
'LombScargle' object has no attribute 'false_alarm_probability'

**Please provide any additional information below**
I have astropy 3.0.2 installed and if I go to the core.py (in the lombscargle folder), the **def** _false_alarm_probability_ IS inside the **class** _LombScargle_, as well as the _normalization_ variable. Thus, I am really not sure why it isn't recognised when I run the code.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
Are you sure you're using the same Python inside and outside Spyder?

**Comment by nadiyaikon** [comment]
@ccordoba12 I've just solved it by transferring some files to another folder. So all is gooood thanks

**Comment by CAM-Gerlach** [comment]
Thanks for letting us know, @nadiyaikon , and glad you got it fixed!

**Comment by acamargofb** [comment]
I am getting kind of the same error following  http://docs.astropy.org/en/stable/stats/lombscargle.html#  the error that I got is:
ls.false_alarm_probability(power.max())
AttributeError: 'LombScargle' object has no attribute 'false_alarm_probability'

Does someone faced the same problem? 

Thanks a lot in advance,

Aldo

**Comment by CAM-Gerlach** [comment]
@acamargofb As was apparently the case for the original poster, this is very likely to be a problem with your code (or perhaps Astropy) and have nothing to do with Spyder.

If you try the exact same code outside of Spyder in the same Anaconda (or virtualenv, etc) environment, e.g. in a QtConsole interpreter (which can be launched with ``jupyter qtconsole`` from the command line), do you receive the same error? If so, it certainly isn't related to Spyder.  Presuming that's the case, my naive guess would be you've either missed/overlooked something in your code, or the tutorial is written for a different version of Astropy than the one you're using.
