### ISSUE TITLE
How to increase the Line Spacing/ Height in the Editor of Spyder

### ISSUE THREAD

**Issue by pyj8711** [spyder-ide/spyder#7035]
## Problem Description
The Line Spacing in Spyder Editor is too small for me. But I cannot find a way to increase it.

### What steps will reproduce the problem?

1. Just write some codes in the Editor.
2. 
3. 

### What is the expected output? What do you see instead?
The Line Spacing can be adjusted.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.8
* Python: 3.6
* Qt:
* PyQt:
* Operating System: Win 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Sorry, this can't be adjusted in Spyder. Please try to use a different font family or size to fix this in your side.
