### ISSUE TITLE
# Importation import numpy as np from pylab import * gaussian = lambda x: np.exp(-(0.5-x)**2/1.5) x=np.arange(-2,2.5,0.01) y=gaussian(x) plot(x,y) xlabel("x values") ylabel("y values") title("Gaussian function") show()

### ISSUE THREAD

**Issue by cecethea** [spyder-ide/spyder#7036]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/cece/anaconda4/lib/python2.7/site-packages/spyder/plugins/editor.py", line 2361, in run_file
    if editorstack.save():
  File "/home/cece/anaconda4/lib/python2.7/site-packages/spyder/widgets/editor.py", line 1600, in save
    return self.save_as(index=index)
  File "/home/cece/anaconda4/lib/python2.7/site-packages/spyder/widgets/editor.py", line 1751, in save_as
    ok = self.save(index=new_index, force=True)
  File "/home/cece/anaconda4/lib/python2.7/site-packages/spyder/widgets/editor.py", line 1641, in save
    str(error)),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
It seems you're trying to save a file with unicode characters on it, without declaring its coding first. For that, please be sure to add this comment as your first line:

    # -*- coding: utf-8 -*-
