### ISSUE TITLE
Save workspace in .spydata not producing file

### ISSUE THREAD

**Issue by Mark584** [spyder-ide/spyder#7043]
## Problem Description

When I'm trying to save my current workspace into a .spydata file, no file is produced by spyder. Also, no error message is produced. However, when I'm trying to save the workspace into a .mat file, is shows: 'Unable to save current workspace. Could not convert (type ) to array' 

### What steps will reproduce the problem?

1. Clicking on 'Save data as...'
2. Setting a file name and clicking on save
3. Nothing happens

### What is the expected output? What do you see instead?

Expected a file being produced. No file was produced. When I'm starting with an empty workspace, saving the .spydata file works.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.5 | Anaconda, Inc.
* Qt:
* PyQt:
* Operating System: Windows 10 64-bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for reporting. Could you post a simple example of a workspace you're unable to save?

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Comment by divyarathi1** [comment]
Hi, I keep running into this problem now and then too. At times workspaces reload 
successfully  after saving through the 'save data as' as a .spydata file. But most often when re-loading it runs into some error. Attaching an example below:

![Screen Shot 2020-06-17 at 7 05 13 PM](https://user-images.githubusercontent.com/20824106/84904872-7c650180-b0cd-11ea-8c1a-542e5b2065d5.png)

**Comment by divyarathi1** [comment]
Hi, I keep running into this problem now and then too. At times workspaces reload
successfully after saving through the 'save data as' as a .spydata file. But most often when re-loading it runs into some error. Attaching an example below:
![Screen Shot 2020-06-17 at 7 05 01 PM](https://user-images.githubusercontent.com/20824106/84905312-20e74380-b0ce-11ea-9aab-261e3ca77b03.png)

**Comment by divyarathi1** [comment]
Hi, I keep running into this problem now and then too. At times workspaces reload
successfully (by import data) after saving through the 'save data as' as a .spydata file. But most often when re-loading it runs into some error. Attaching an example below:

![Screen Shot 2020-06-17 at 7 05 01 PM](https://user-images.githubusercontent.com/20824106/84905439-496f3d80-b0ce-11ea-85a8-a93c0eb24a1a.png)

**Comment by dalthviz** [comment]
Hi @divyarathi1, thanks for the feedback! I think your issue is more related to loading the `.spydata` file than creating it.

Please, open another issue with a reproducible example (or the steps you follow in order to get the message showed) :)

My initial guess is that some of the objects you have in your namespace are not being handle correctly by Spyder when loading the file, or maybe you are trying to overwrite an already populated namespace and some of the objects you're using doesn't provide a way to reload
