### ISSUE TITLE
Add line-level timings to the profiler

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#705]
_From [novi...@gmail.com](https://code.google.com/u/117248594063299312220/) on 2011-07-06T12:10:21Z_

Possibly through the integration of Robert Kern's line profiler: http://pypi.python.org/pypi/line_profiler

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=705_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-07T00:06:57Z_

**Status:** Accepted  
  **Labels:** -Type-Defect Type-Enhancement Cat-Profiler Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-15T07:19:20Z_

**Labels:** -Milestone-Release2.1 Milestone-Release2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:49:14Z_

**Labels:** -Milestone-Release2.2 Milestone-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:58:20Z_

**Labels:** -Milestone-v2.2 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:13:45Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-11T08:37:30Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T05:42:10Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-10-10T18:27:48Z_

I started a plugin for line_profiler here: https://github.com/Nodd/spyder_line_profiler Right now lineprofilergui.py works if launched as a script from within spyder, but crashes spyder if launched as a normal plugin. It is of course heavily based on the profiler plugin.

**Attachment:** [slp.png](http://code.google.com/p/spyderlib/issues/detail?id=705#hc8)

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-10-11T03:38:48Z_

Actually, it works fine with a standard spyder install. I guess the problem is in bootstrap.py.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2013-10-12T04:48:05Z_

The plugin is finished ! I'm open to suggestions to improve it.

The problem with bootstrap.py went away on its own after an update.

**Comment by spyder-issues-migrator** [comment]
_From [googol.p...@gmail.com](https://code.google.com/u/114320778963558170584/) on 2014-12-08T01:58:52Z_

I have problems using the line_profiler plugin: https://github.com/Nodd/spyder_line_profiler I have line_profiler installed, but still get the warning "please install the line_profiler module" in spyder. I suspect the reason for this is my default installation path, but I don't know how to deal with it:

I'm using Ubuntu 14.04, which default python is /usr/lib/python2.7

I install line_profiler by pip install line_profiler, and it is installed in /usr/local/lib/python2.7/dist-packages

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-09T15:47:43Z_

Joseph, could you help this user with your plugin?

**Cc:** contrebasse

**Comment by spyder-issues-migrator** [comment]
_From [vishnia...@gmail.com](https://code.google.com/u/103405887791949639593/) on 2014-12-19T16:37:05Z_

I think one issue is the check on line 70 in lineprofilegui.py . https://github.com/Nodd/spyder_line_profiler/blob/master/widgets/lineprofilergui.py Here are the results:



import line_profiler
import kernprof
from spyderlib.utils import programs
programs.is_module_installed('line_profiler')
programs.is_module_installed('kernprof')
programs.find_program('kernprof.py')
programs.find_program('kernprof')

Out[1]: '.../bin/kernprof'

I tried to remove ".py" from the check, but still receive an error "Failed to start process".

**Comment by spyder-issues-migrator** [comment]
_From [vishnia...@gmail.com](https://code.google.com/u/103405887791949639593/) on 2014-12-20T18:03:56Z_

Okay so I also edited all references from "kernprof.py" to "kernprof" and it seems to be working. I am attaching the modified "lineprofilergui.py" for your reference. Could you please try and see if this works for you?

**Attachment:** [lineprofilergui.py](http://code.google.com/p/spyderlib/issues/detail?id=705#hc14)

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-12-21T12:32:00Z_

Oh sorry, I just saw this problem !

Indeed with the last version the script is installed as kernprof, but I didn't remembered that it would cause problem. line_profiler is very useful but not on a daily basis.

I'll check this during the week.

BTW Carlos, should I open a PR to add this plugin to the official spyder releases, or do you prefer to keep it external ?

**Comment by spyder-issues-migrator** [comment]
_From [vishnia...@gmail.com](https://code.google.com/u/103405887791949639593/) on 2014-12-23T17:39:51Z_

Thanks, I think this is an excellent feature that should come with spyder by default.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-12-24T09:24:05Z_

@-contrebasse: Let's wait until we move to Github for a PR. I'll prefer that we improve our third-party plugins installation before taking a decision.

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-06T08:28:03Z_

OK, it's been a little more than a week, but the plugin is now fixed on github. Thanks !

**Comment by spyder-issues-migrator** [comment]
_From [googol.p...@gmail.com](https://code.google.com/u/114320778963558170584/) on 2015-01-14T19:33:34Z_

hi, can anyone answer me? 

I'm using Ubuntu 14.04, which default python is /usr/lib/python2.7

I install line_profiler by pip, which is located in /usr/local/lib/python2.7/dist-packages

Then I try to open the window of line_profiler in spyder, but it gives me a warning like this: please install the line_profiler module.

what should I do? Many thanks!

**Comment by spyder-issues-migrator** [comment]
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2015-01-16T11:53:58Z_

Hi, try to update the spyder plugin. line_profiler recently changed its script name from kerprof.py to kernprof, it has been corrected in the plugin last week.

**Comment by ahed87** [comment]
Hi,

just added issue #28 on spyder_line_profiler.

The second item mentioned there is more related to spyder itself, and how it finds the right python install to use for running scripts.
Maybe the user experience can be improved if spyder starts to recognize where it is installed and selects the corresponding python.exe.

BTW: Spyder is great, I have been using it for years now.

**Comment by ccordoba12** [comment]
line_profiler has been migrated here:

https://github.com/spyder-ide/spyder.line_profiler

Could you report your issue again there? Thanks :-)

**Comment by ahed87** [comment]
did not catch that it also was in a spyder repository - good to know

hm...
the real issue was actually on memory_profiler, which does not seem to be part of the "upgraded" location.

I'm attaching the link instead, since it was not obvious where to find it.
If you still think it belongs in the new repository (I don't), I will put it there.

https://github.com/Nodd/spyder_line_profiler/issues/28

**Comment by ccordoba12** [comment]
Memory profiler is here now:

https://github.com/spyder-ide/spyder.memory_profiler

**Comment by Nodd** [comment]
The bug in memory_profiler is now fixed in the old version. The new version is not compatible with spyder 3.0beta yet.
I will create bug reports in the new repositories.
