### ISSUE TITLE
Autocomplete wont work

### ISSUE THREAD

**Issue by paulgureghian** [spyder-ide/spyder#7061]
## Problem Description
I have both jedi and rope but autocomplete doesnt seem to work
### What steps will reproduce the problem?

open spyder, enter code, no autocomplete suggestions 

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Autocomplete doesn't work on the fly. You need to press `Tab` next to some text to get completions for it.

If that still doesn't work, please take a look at issue #5782.

**Comment by CAM-Gerlach** [comment]
Also, on the fly autocomplete e.g. #3708 should be added in Spyder 4, due out by early next year.
