### ISSUE TITLE
RuntimeWarning when displaying min/max in the Variable Explorer

### ISSUE THREAD

**Issue by mattip** [spyder-ide/spyder#7063]
## Problem Description

Originally reported as numpy/numpy#11029

In numpy 1.14, umath.minimum.reduce and umath.maximum.reduce will raise `RuntimeWarning` if they encounter a NAN value. It seems the variable explorer is not filtering these warnings, so they turn up on the console when 
- max,min display is enabled in the variable explorer
- there is a NAN value in the ndarray

### What steps will reproduce the problem?
1. Use numpy 1.14.0 or later
2. Turn on max/min display by clicking to the variable explorer tab, clicking on the setup gear in the corner, and making sure "Show arrays min/max" checkbox is checked.
3. in the console, `import numpy as np; A=np.full(16, np.nan)'

Note that numpy 1.14.0 - 1.14.3 have a bug, doing `A=np.full(7, np.nan)` would not show the warning.

### What is the expected output? What do you see instead?

In the console, I see two `RuntimeWarnings`

## Package Versions

* Spyder: 3.2.8
* Python: 3.5.2
* Qt: 5.9.3
* PyQt: 5.9.2
* Operating System: Ubuntu 16.04

### Dependencies

```
IPython >=4.0    :  6.3.1 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.15.0.dev0+52316e3 (OK)
pandas >=0.13.1  :  None (NOK)
psutil >=0.3     :  5.4.5 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.3 (OK)
sympy >=0.7.3    :  None (NOK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this in our next release.

**Comment by CAM-Gerlach** [comment]
Yup, reproduced.
