### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by lpdsdx** [spyder-ide/spyder#7072]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
with open(fname, 'w', encoding='utf-8') as configfile:
FileNotFoundError: [Errno 2] No such file or directory: 'sn_0_3965896/.spyproject/workspace.ini'

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This appears to be a duplicate of #5765 . If you can provide us more information over on that thread, please do so.
