### ISSUE TITLE
Tkinter apps don't work properly when graphics backend is set to Tkinter

### ISSUE THREAD

**Issue by czatom** [spyder-ide/spyder#7074]
## Problem Description
There are some problems when running tkinter scripts with graphics backend set to Tkinter.

- Application won't close properly (after closing window something is still running in the background, so the console is busy). 
Somehow this is the solution:
```
        self.master.quit() # stops the mainloop?
        self.master.destroy()
```
- Widgets won't change state properly
- I can't start application without passing root object to main class (descendant of the Frame class):
```
    root = tk.Tk()
    app = SomeClass(master=root)
    app.master.title('PyExplore - Python Data Exploration Tool - version 0.1')
    app.mainloop()
```

### What steps will reproduce the problem?

1. Set graphics backend to Tkinter
2. Run some tkinter script like the one below:
```
import tkinter as tk
import tkinter.ttk as ttk
 
def check_test():
    print("state: {}".format(chk_state.get()))

window = tk.Tk()
window.geometry('350x200+1000+400')
chk_state = tk.IntVar(value=-1)
#chk_state.set(True) #set check state
chk = ttk.Checkbutton(window, text='Choose', var=chk_state, command=check_test)
chk.grid(column=0, row=0)
window.mainloop()
```
3. Try to change checkbox state
4. Try to close application

### What is the expected output? What do you see instead?

I would expect something like this:

- widgets change state properly
- after closing window console is released

![expected_output](https://user-images.githubusercontent.com/18006001/39675110-c5a319e6-5156-11e8-8b8f-76a1514cb33a.gif)

What I got looks like this:

![actual_output](https://user-images.githubusercontent.com/18006001/39675109-c57d7c90-5156-11e8-9b18-e804c74492bc.gif)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Package Versions

* Spyder: 3.2.8
* Python: 3.6.5
* Qt: 5.9.4
* PyQt: 5.9.1
* Operating System: Windows 10

### Dependencies

```
IPython >=4.0    :  6.3.1 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.2 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for the very detailed report! Can you try changing your graphics backend to something else, or unchecking "Activate support" under Preferences > IPython Console > Graphics?

**Comment by ccordoba12** [comment]
@czatom, Tk under Windows doesn't work well if you're using Anaconda, and I think that's the fault of Anaconda. Is this the case for you?

**Comment by czatom** [comment]
@CAM-Gerlach It works correctly with Graphics backend set to Inline, Automatic or Qt5. After unchecking "Activate support" it also gives desired results.

@ccordoba12 I checked it. There is same problem on linux.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Will/can we do anything about this, or should it be closed as ``wontfix``?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
We should investigate further.

**Comment by jproy** [comment]
Hello, after many many many problems on my Mac, using Spyder 3.3.2, Anaconda 5.3.1 and ipykernel 4.9.0, ipython 6.5.0, python 3.7.1, I found maybe a stable situation when working with tkinter (up to now). Write a tkinter program without mainloop. Deactivate graphic support in Ipython Console prefs, always run programs in the same console (new kernels die frequently with tkinter), evaluate %gui tk in a console and run the program (do not delete variables when executing). Woaw. I wish someone of your team use a mac for the big rest of us... I think also that the updating mechanism of Anaconda is unstable. For example I update spyder which updates Python to 3.7.1 and I still have 3.7.0 in the console... I had to tweak interpreter path in the prefs to get 3.7.1...

**Comment by CAM-Gerlach** [comment]
> I wish someone of your team use a mac for the big rest of us... 

We've been looking for someone with access to a macOS platform for some time, and actually managed to find someone recently. However, she had to temporarily pause her Spyder development efforts to work for Jupyter, but she should be back in a few months.

> I think also that the updating mechanism of Anaconda is unstable. For example I update spyder which updates Python to 3.7.1 and I still have 3.7.0 in the console..

We don't have any control over ``conda``, but what you've reported likely has nothing to do with instability of the update mechanism. Instead, if you had to tweak the interpreter path to get the updated version, this simply means you installed the updates in a different Anaconda environment than your Spyder instance was running from, or you needed to restart Spyder (or at least open a new Console) to use the newly updated version, and everything was working as designed. See [our guide](
) on working with packages and environments for more, and improvements coming in Spyder 4 will include full GUI package and environment management within the IDE to make this much easier.

**Comment by jproy** [comment]
Interesting, when version 4 will be available ?

**Comment by CAM-Gerlach** [comment]
[Here's](https://github.com/spyder-ide/spyder/wiki/Roadmap) a link to  the Roadmap; Beta 3 will be the one with the key changes I mentioned. The final release should follow in perhaps early March.

**Comment by ccordoba12** [comment]
This issue is too old and most probably it no longer applies. So, I'm closing it.
