### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ld26464** [spyder-ide/spyder#7076]
### What steps will reproduce the problem?

This happened during install of beautiful-soup from A-Navigator interface. It looked like it was trying to install a lot of old (python 2?) dependencies. I did this because the basic install of beautifulsoup4 wasn't being found and throwing some sort of error when loading either 'requests' or 'urllib4' libraries. "moduleNotFoundError: No module named 'BeautifulSoup'" but I hadn't loaded it directly. 

### Traceback
```python-traceback
  File "/Users/blackness2/Developer/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 158, in _on_finished
  File "/Users/blackness2/Developer/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 104, in run
OSError: Could not start <spyder.utils.introspection.plugin_client.PluginClient object at 0x181da2b9d8>
Traceback (most recent call last):
  File "/Users/blackness2/Developer/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 158, in _on_finished
  File "/Users/blackness2/Developer/anaconda3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 104, in run
OSError: Could not start <spyder.utils.introspection.plugin_client.PluginClient object at 0x181da2b708>
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 17.5.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

**Comment by ccordoba12** [comment]
I really don't know what happens here, so I think you'll have to revert the packages you just installed and try again.

**Comment by ld26464** [comment]
Thanks, I did and it seemed to work itself out. 
Lee

**Comment by ccordoba12** [comment]
What happens if you install Spyder in a different environment?

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
