### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by qiangshizhuzai** [spyder-ide/spyder#7081]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I call dlib in spyder to do face recognition. When I debug step by step,the result of the program is correct.However,when I directly enter run button,the program runs the result,and then reconnect to the kernel.In other words, the kernel died and restarted immediately after the run of the code. Then the console window show the initial state as follow:

Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 6.3.1 -- An enhanced Interactive Python.

**Comment by ccordoba12** [comment]
Please the most simple code example that causes this error, so we can run it in our side.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
