### ISSUE TITLE
QtWebEngineProcess stays open after closing ipython tab

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#7091]
For each ipython tab i open, I get a new QtWebEngineProcess, as expected from:
https://github.com/spyder-ide/spyder/blob/37c9491ca5468d3738377b95305095811c8a1c0e/spyder/widgets/ipythonconsole/client.py#L137

But this process stays open after closing the tab! I strongly believe that closing spyder takes an extra 5-10s because of that.

Disabling the automatic tab opening:
![screen shot 2018-05-07 at 15 29 31](https://user-images.githubusercontent.com/6740194/39707283-e30c6194-520b-11e8-8169-bff0fe0a546e.png)
First I have 1 main Python process, 2 other python process and 2 QtWebEngineProcess.
If I close spyder now it will be fast.
![screen shot 2018-05-07 at 15 30 39](https://user-images.githubusercontent.com/6740194/39707282-e2f63766-520b-11e8-9f6e-eb3467518d93.png)
Then I open 3 tabs. I get 3 extra python process, and 3 extra QtWebEngineProcess. Spyder will need to wait for some kind of timeout before closing (5-15 s usually).
![screen shot 2018-05-07 at 15 31 23](https://user-images.githubusercontent.com/6740194/39707281-e2df47e0-520b-11e8-93dc-45722047ea0c.png)
The three tabs are closed. The 3 extra python process disappeared, but not the QtWebEngineProcess. Spyder is still slow to close.

Python 3.6.5 64bits, Qt 5.9.1, PyQt5 5.9 on Darwin

**Comment by impact27** [comment]
This looks like a reference cycle. I thinks the ipython client never gets deleted because reasons?
I will see if I find something.

**Comment by impact27** [comment]
![client](https://user-images.githubusercontent.com/6740194/39861266-f82041f8-5437-11e8-8d43-88220529d033.png)

**Comment by impact27** [comment]
exit_callback might make a loop and ShellWidget has 4 references to client, mostly from lambda functions.

**Comment by ccordoba12** [comment]
We decided to use a single infowidget for all our consoles to tackle this. It's just a workaround, but a useful one if you open a lot of consoles.
