### ISSUE TITLE
Suggestion: Package installation using GUI

### ISSUE THREAD

**Issue by munitech4u** [spyder-ide/spyder#7098]
Hi,

Is it feasible to add an option similar to RStudio to install the packages for the current version of python on which Spyder is Running using GUI button option in toolbar instead of using Conda/pip command line tool?

Like install button: Install Package >Search>Install

## Versions
* Spyder version: 3.2.6
* Python version: 3.6
* Operating System name/version: Windows 8

**Comment by ccordoba12** [comment]
Yes, it is. We'll try to implement this for Spyder 4.

**Comment by ccordoba12** [comment]
Yes, that's right.

**Comment by ccordoba12** [comment]
Closing as we don't plan to work on this.
