### ISSUE TITLE
typo in locale\fr

### ISSUE THREAD

**Issue by erwanp** [spyder-ide/spyder#7100]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)

## Problem Description

Typo in the French /locale:

"Save As" is **"Enregitrer un fichier"** where it should be **"Enregistrer un fichier"**

The file to modify is:

```
spyder\locale\fr\LC_MESSAGES\spyder.mo
```

## Versions

* Spyder version: 3.2.8

**Comment by ccordoba12** [comment]
@dalthviz, please fix this one.
