### ISSUE TITLE
Allow keyboard shorcuts to be cleared in preferences

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#7109]
I looked but I could find a way to clear a keyboard shortcut in the preferences.  This option would disable the shortcut without needing to set it something else. This could be a button like `clear` on the keyboard setting dialog.

![shortcuts](https://user-images.githubusercontent.com/10513354/39943358-d2a26008-551f-11e8-9a98-10ac9e92c522.png)
With a `clear` or `unset` button on there.

This would be handy sine then we could have entries in the shortcuts that are set to nothing by default but could be user enabled

spyder version: master

**Comment by CAM-Gerlach** [comment]
Thanks @bcolsen . This would indeed be very valuable, and its currently in consideration as part of the keyboard shortcut editor enhancements being planned for Spyder 4.
