### ISSUE TITLE
Find in Files Search button disabled and Stop enabled but does nothing

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#711]
_From [owe...@hotmail.com](https://code.google.com/u/116339678255815012807/) on 2011-07-15T09:34:52Z_

What steps will reproduce the problem?

 1. "Find in Files" works for a while, then stops working. Stop button is enabled, Search button is greyed-out.
2. Type a new search term in the editbox. "Search" button is disabled. 3. What is the expected output? What do you see instead? What I expect to see: After you type a new search term, the "Search" button becomes enabled, then you press Search, then the search is executed and results appear. If it was in the middle of a Search, I would also expect the Stop button to cancel the existing search and re-enable the Search button. In fact, there is no ongoing search so it is unexpected that the Stop button is enabled.

What I see instead: Search button is greyed-out, Stop button is enabled. None of the following actions make any difference including:
pressing Stop button, closing and reopening the Find-in-Files widget, closing and re-opening Spyder, selecting old search terms from the pulldown.

Re-booting my computer fixes the problem for a while. What version of the product are you using? On what operating system? Spyder 2.0.1 distributed with Python(x,y) 2.6.5.5
Win7 64-bit 

Please provide any additional information below

. There are several Python files open in the editor during all of this.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=711_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-07-16T01:08:33Z_

You may try to open the internal console (menu "View") and see if there any traceback there. If so, please attached the error messages to this Issue. 

Thanks for the feedback.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-05T20:51:40Z_

**Labels:** Cat-Miscelleneous

**Comment by spyder-issues-migrator** [comment]
_From [holzma...@gmail.com](https://code.google.com/u/117038174657625698320/) on 2011-12-17T02:57:20Z_

I have the same problem and the internal console indeed shows a traceback (spyder 2.1.2 on ubuntu linux):

Python 2.7.2+ (default, Oct  4 2011, 20:03:08) 
[GCC 4.6.1] on linux2
Type "copyright", "credits" or "license" for more information.

\>>> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/findinfiles.py", line 167, in run
    ok = self.find_files_in_path(self.rootpath)
  File "/usr/local/lib/python2.7/dist-packages/spyderlib/widgets/findinfiles.py", line 229, in find_files_in_path
    for path, dirs, files in os.walk(path):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/posixpath.py", line 71, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 18: ordinal not in range(128)

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-17T03:15:08Z_

Well, I suppose you are trying to search in a directory containing non-ASCII characters?

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-05-23T12:05:45Z_

I can reproduce this with current version:

1. Make sure path combobox is filled with entries
2. Choosing entry in path combobox fires search
3. Choose one, wait until search completes
4. Choose another

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-23T12:10:15Z_

Still can't reproduce this behavior.

Could you try and list a detailed procedure to reproduce this bug from the test script (i.e. by executing spyderlib/widgets/findinfiles.py and set the appropriate parameters)?

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-05-23T13:52:12Z_

See how it looks on Fedora 16 with PyQt4 http://youtu.be/l9AkeCugooQ

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-24T04:40:46Z_

Thanks for the video, it's perfectly clear but I'm still unable to reproduce this behavior...

Maybe it's a problem related to the fact that buttons are enabled/disabled after starting the search thread.
The thread starts here: https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/findinfiles.py#732 but the button states are changed only here: https://code.google.com/p/spyderlib/source/browse/spyderlib/widgets/findinfiles.py#733 Could you try and move the 733-734 lines above line 732?

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-05-28T04:12:12Z_

Nothing changes. This time I managed to catch some messages in stderr. It behaves totally erratic. Seems like some race condition is taking place.

$ python spyderlib/widgets/findinfiles.py
Object::disconnect: Unexpected null parameter
$ python spyderlib/widgets/findinfiles.py
$ python spyderlib/widgets/findinfiles.py
Object::disconnect: Unexpected null parameter
sys.excepthook is missing
lost sys.stderr
$

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2012-06-11T00:13:08Z_

issue #1088 has been merged into this issue.

**Cc:** techtonik@gmail.com

**Comment by goanpeca** [comment]
@ccordoba12 can we close this?

**Comment by ccordoba12** [comment]
Sure, it's an old bug.
