### ISSUE TITLE
"Set Console working directory" button not working in Spyder

### ISSUE THREAD

**Issue by rahul-raj** [spyder-ide/spyder#7116]
Spyder version: 3.2.8
Python version: 3.6.5 64-bit
Qt version : 5.6.2
IPython version : 6.4.0

Steps to reproduce the issue:
1) Open Spyder in Windows 10
2) Default working directory listed as : **C:\Users\Admin\.spyder-py3**
3) Browse another working directory
4) Now click on "set console working directory" from the options:
  https://i.imgur.com/Rjar1JM.png 
5) Now default directory "C:\Users\Admin\.spyder-py3" again appears on the panel and
   the previously selected directory is de-selected:
  https://i.imgur.com/Nx4QHOu.png 

Expected output:
It should update the directory path in the panel instead it keeps going back to default directory path..
Working directory is never changed.

**Comment by CAM-Gerlach** [comment]
Thanks for the detailed report and screenshots, making it easy to break down what's happening. Here's what's going on:

> 2) Default working directory listed as : **C:\Users\Admin\.spyder-py3**

This is the Spyder config directory, and, crucially, the location of the default ``temp.py`` file you have open in the editor.

> 3) Browse another working directory

If you check in the console (with ``pwd``), or any other place that uses the working directory, this automatically sets the working directory already. So, at this point, your working directory is already set where you want it.

> 4) Now click on "set console working directory" from the options:

This is a dropdown menu from an editor pane, and sets the working directory to the parent dir of the file being currently displayed in that pane...

> 5) Now default directory "C:\Users\Admin\.spyder-py3" again appears on the panel and
   the previously selected directory is de-selected:

...which, in this case for the ``temp.py`` file you had open, happens to be the same directory you had set as the working dir originally.

So, you can just change the working directory directly from the text box or file browser; no need for an extra step. Use that menu option if you want to set the working dir to that of the currently selected file. Also, Spyder has a Projects feature to set your working directory (and files open, etc) automatically.

Sorry for the confusion; we're working at dramatically overhauling our currently quite skimpy documentation; the initial release should hopefully be in a few days time, and I'm hoping to get the chance to document Spyder's functionality in far more extensive detail over the summer. Thanks for your patience, and best of luck!
