### ISSUE TITLE
vim plugin spyder_vim error

### ISSUE THREAD

**Issue by xuerenjie124** [spyder-ide/spyder#7117]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_vim\vim_widget.py", line 735, in on_text_changed
    self.vim_keys(key, repeat)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_vim\vim_widget.py", line 75, in __call__
    method(repeat)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_vim\vim_widget.py", line 505, in p
    self.P(repeat)
  File "D:\ProgramData\Anaconda3\lib\site-packages\spyder_vim\vim_widget.py", line 525, in P
    if lines[0].strip():
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. This is a problem with the ``spyder-vim`` plugin, not spyder itself, and should thus be directed to the [spyder-vim](https://github.com/spyder-ide/spyder-vim/issues) repo. Be advised, due to our current funding situation, it be a while before it is fixed, but we will be adding built-in shortcut presets to Spyder 4 as well as expanded shortcut management features, to include ``vim`` (and ``emacs``) shortcuts.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-vim #41](https://github.com/spyder-ide/spyder-vim/issues/41) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CAM-Gerlach** [comment]
I asked in chat but it must have got buried—I tried to move it, but couldn't find the button in Zenhub even after reading the Zenhub docs and googling it. Do only you have access to it?

**Comment by ccordoba12** [comment]
@goanpeca, how can we give @CAM-Gerlach access to this feature?
