### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by gilfoyle1995** [spyder-ide/spyder#7120]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
my spyder environment keeps on crashing in mac os x high sierra please help

**Comment by ccordoba12** [comment]
Please open Terminal.app and run there

    conda update python python.app

That should fix your problem. I'm closing this one because you didn't give more details.
