### ISSUE TITLE
Make ./bootstap.py --debug accept an integer to set debug levels

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#7123]
I looks like the code currently converts a bool to an int and sets the SPYDER_DEBUG environment variable to 0 or 1.

This line will take an int after `--debug` but also if there is no int specified after `--debug` then 1 is returned and if there is no `--debug`  then 0 is returned:
```python
parser.add_argument('--debug', nargs='?', const=1, type=int, default=0)
```
See here: https://docs.python.org/3/library/argparse.html#nargs

This would maintain backwards compatibility as well as allow lines like this:
```
./bootstrap.py --debug 3 --test
```

**Comment by ccordoba12** [comment]
Nice catch! Please create a PR against our 3.x branch to fix this.

**Comment by bcolsen** [comment]
I'm :+1: for #7131.  That sounds good to me.

**Comment by ccordoba12** [comment]
I set `--debug` to the maximum level of debugging (3 or verbose) in PR #7734. The other level (2 or minimal) gives very little info, so I don't think it requires a change like the one proposed here.

**Comment by ccordoba12** [comment]
I set `--debug` to the maximum level of debugging (3 or verbose) in PR #7734. However, you can change between the `verbose` and `minimal` levels (the only ones I left after that PR) with

    python bootstrap.py -- --debug-info {verbose, minimal}
