### ISSUE TITLE
Error when renaming a directory with several opened files in it

### ISSUE THREAD

**Issue by chipmuenk** [spyder-ide/spyder#7126]
### What steps will reproduce the problem?

renamed a directory with several opened files in it

### Traceback
```python-traceback
  File "D:\Programme\Anaconda3\lib\site-packages\spyder\plugins\editor.py", line 1364, in close_file_in_all_editorstacks
    index = editorstack.get_index_from_filename(filename)
  File "D:\Programme\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 1364, in get_index_from_filename
    return filenames.index(filename)
ValueError: 'D:\\Daten\\design\\python\\git\\pyfda\\pyfda\\hdl_generation\\hdl_df2.py' is not in list
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.5.2
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)
```

<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by CAM-Gerlach** [comment]
This should have been fixed already in 3.2.8 with #6445 , but I guess it must be distinct somehow (or the fix was not entirely effective)...

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.

**Comment by dalthviz** [comment]
Hi @chipmuenk I'm not being able to reproduce the issue (I tried renaming the directory with the File Explorer in Spyder and in the system file explorer). Did you do something more than renaming the directory?

Any info you could provide to replicate the issue would be greatly appreciated :)

As @CAM-Gerlach said, maybe something different was made in order to trigger an error like the one in #6445

**Comment by ccordoba12** [comment]
@dalthviz, perhaps this happens when *all* files in the Editor are removed at once. Pleas try that.

**Comment by dalthviz** [comment]
I could not reproduce this issue after all, @chipmuenk feel free to reopen it if you can give us more info about how to reproduce the error or you handle to experiment it again.
