### ISSUE TITLE
Spyder won't launch. Python has stopped working

### ISSUE THREAD

**Issue by rakshanda22** [spyder-ide/spyder#7136]
I am facing the following issue when launching spyder. 

Assertion failed: Socket operation on non-socket (bundled\zeromq\src\select.cpp:185)
[1324:4776:0515/171855.478:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

I've already tried 
spyder --reset
pip install pyqt5
conda update spyder
conda update conda

Below is the version list

* Spyder version: 3.2.8  
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt version:  5.6.0
* Operating System name/version: Windows 10, 64bits

**Comment by ccordoba12** [comment]
Please deactivate your firewall/antivirus and try again.

**Comment by raorm** [comment]
I think I might be having same issue after installing pyqt5 recently.
I've tried uninstalling and reinstalling spyder, updating conda and spyder, spyder --reset and uninstalling pyqt5.

I get this error:

`AttributeError: 'DummyDock' object has no attribute 'show'
[32472:1444:0516/093202.412:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)`

**Comment by rakshanda22** [comment]
@ccordoba12  It is working now. Thanks

**Comment by CAM-Gerlach** [comment]
@rakshanda22 Great news! Glad to hear.

@raorm 

> I think I might be having same issue

That one looks like it might be a duplicate of #5967 and, likely, spyder-ide/spyder-autopep8#6 . If you have ``spyder-autopep8`` (a third party plugin that is currently not able to be actively supported due to limited funding), you should uninstall it to fix it.

**Comment by Pragya-Dwivedi** [comment]
I'm also facing the same problem. Jupyter notebook and spyder notebook both are not getting launched from anaconda navigator. While giving command "spyder notebook" in anaconda prompt, the initialization will start, but then a pop-up will come as "Python stopped working", the error will be 

Assertion failed: error not defined [0] (C:\ci\zeromq_1549025594292\work\src\err.cpp:383)

Jupyter notebook will not even show any response.

I tried reinstalling several times, still, but the problem remains the same. Kindly help.

**Comment by akshata96** [comment]
Facing the same issue as @Pragya-Dwivedi
