### ISSUE TITLE
can not editor

### ISSUE THREAD

**Issue by yichichou** [spyder-ide/spyder#7138]
## Description

**What steps will reproduce the problem?**

1. when print list value
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

MemoryError

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by CAM-Gerlach** [comment]
My guess is that, Spyder or one of its dependencies is not installed correctly. Your first course of action should be a clean install of the latest version (5.1.0) of 64-bit Anaconda, and then update Spyder to the latest version with ``conda update spyder``. Beyond that, at least one of the other suggestions in the aforementioned Troubleshooting Guide should resolve it.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.
