### ISSUE TITLE
Could not connect to local kernel inside a docker

### ISSUE THREAD

**Issue by jmarrietar** [spyder-ide/spyder#7147]
Hi, 

Is there some quick-start instructions on how to connect Spyder on Host to an existing 'remote' kernel inside a docker?. I am able to open the Jupyter kernel on the browser what would like to connect spyder to it. 

Someone has done something similar before?. 

Thank you in advance.

**Comment by jmarrietar** [comment]
Yes, I tried somehow follow this https://github.com/ipython/ipython/wiki/Cookbook:-Connecting-to-a-remote-kernel-via-ssh and could connect in my local to local kernel, but not in a docker one. I expose port 8888 in docker

**Comment by ccordoba12** [comment]
Then use the dialog located in

    Consoles > Connect to an existing kernel

and pass there the ssh info of your docker instance.

I'll open an issue in our docs about this, so we don't forget to explain how to do it in the future.
