### ISSUE TITLE
Spyder doesn't launch: stuck on “Setting up main window”

### ISSUE THREAD

**Issue by raphsilva** [spyder-ide/spyder#7153]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I try to run Spyder on Ubuntu 16.10, it doesn't launch and gets stuck on "Setting up main window" forever. No error messages are shown and it doesn't crash.

When I try to run it from the source, the very same thing happens, and I get the message

> Revision 03c7161, Branch: master
> 01. Patched sys.path with /home/user/spyder/spyder
> 02. PyQt5 is detected, selecting
> 03. Imported Spyder 4.0.0.dev0
>     [Python 3.5.2 64bits, Qt 5.9.3, PyQt5 5.9.2 on Linux]
> 04. Running Spyder
> Bootstrap completed in 00:00:00.5483

I tryied to debug the code and found that it doesn't get past the line (which is in the file spyder/app/mainwindow.py)

```
self.console = Console(self, namespace, exitfunc=self.closing,
                            profile=self.profile,
                            multithreaded=self.multithreaded,
                            message=_("Spyder Internal Console\n\n"
                                    "This console is used to report application\n"
                                    "internal errors and to inspect Spyder\n"
                                    "internals with the following commands:\n"
                                    "  spy.app, spy.window, dir(spy)\n\n"
                                    "Please don't use it to run your code\n\n"))
```
Going deeper, it doesn't go past the line `sys.stdout = self.stdout_write` at `def redirect_stds(self)` in spyder/interpreter.py.

### What steps reproduce the problem?

1. Try to run Spyder 3 or 4. 

### What is the expected output? What do you see instead?

Spyder should launch. 
Instead, it gets stuck on "Setting up main window" forever.
Spyder 2 runs just fine.

### Paste Traceback/Error Below (if applicable)

> ```python-traceback
> 
>   File "/home/user/spyder/spyder/spyder/app/mainwindow.py", line 3241, in main
>     mainwindow = run_spyder(app, options, args)
>   File "/home/user/spyder/spyder/spyder/app/mainwindow.py", line 3111, in run_spyder
>     main.setup()
>   File "/home/user/spyder/spyder/spyder/app/mainwindow.py", line 1175, in setup
>     self.setup_layout(default=False)
>   File "/home/user/spyder/spyder/spyder/app/mainwindow.py", line 1465, in setup_layout
>     self.setup_default_layouts('default', settings)
>   File "/home/user/spyder/spyder/spyder/app/mainwindow.py", line 1641, in setup_default_layouts
>     widget.toggle_view(True)
>   File "/home/user/spyder/spyder/spyder/plugins/ipythonconsole.py", line 760, in toggle_view
>     self.create_new_client(give_focus=False)
>   File "/home/user/spyder/spyder/spyder/plugins/ipythonconsole.py", line 1082, in create_new_client
>     self.connect_client_to_kernel(client, is_cython=is_cython)
>   File "/home/user/spyder/spyder/spyder/plugins/ipythonconsole.py", line 1120, in connect_client_to_kernel
>     kc.start_channels(shell=True, iopub=True)
>   File "/usr/local/lib/python3.5/dist-packages/qtconsole/kernel_mixins.py", line 43, in start_channels
>     super(QtKernelClientMixin, self).start_channels(*args, **kw)
>   File "/usr/local/lib/python3.5/dist-packages/jupyter_client/threaded.py", line 235, in start_channels
>     self.ioloop_thread.start()
>   File "/usr/local/lib/python3.5/dist-packages/jupyter_client/threaded.py", line 174, in start
>     self._start_event.wait()
>   File "/usr/lib/python3.5/threading.py", line 549, in wait
>     signaled = self._cond.wait(timeout)
>   File "/usr/lib/python3.5/threading.py", line 293, in wait
>     waiter.acquire()
> KeyboardInterrupt

```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 3 and 4
* Python version: 3.5
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 16.04

### Dependencies
<!--- Please go to the menu entry Help > Dependencies,
press the Copy to clipboard button and paste below --->

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations (even from packages provided by Linux distros) are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Comment by violetina** [comment]
FYI i have the same and is related to https://github.com/jupyter/notebook/issues/3595 and https://bugs.gentoo.org/648088 , still waiting for version dump dev-python/pyzmq >= v17

**Comment by ccordoba12** [comment]
@violetina, please use Anaconda in the meantime.

**Comment by ferrabra** [comment]
I installed with PIP and I figured out the issue only happens with Python 3.8. I've tested on Python 3.7.5 and all works finely!

**Comment by fbosio** [comment]
> FYI i have the same and is related to [jupyter/notebook#3595](https://github.com/jupyter/notebook/issues/3595) and https://bugs.gentoo.org/648088 , still waiting for version dump dev-python/pyzmq >= v17

Exactly! [This workaround](https://github.com/tornadoweb/tornado/issues/2608#issuecomment-550180288) did the trick for me:
1. Open `%YOUR_PYTHON_ENV_DIR%\Lib\site-packages\tornado\platform\asyncio.py` where `%YOUR_PYTHON_ENV_DIR%` may be your Python3, Anaconda, Miniconda, env directory etc.
2. Add above the line `if typing.TYPE_CHECKING:` (immediately below the imports):
 ```
 if sys.platform == 'win32':
     asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
 ```

Now Spyder 4.1.2 runs fine with Python 3.8 :)

**Comment by ccordoba12** [comment]
@fbosio, that manual patching won't be needed since our next version (4.1.3) because we are doing it in our code to have out of the box support for Python 3.8.

**Comment by fbosio** [comment]
@ccordoba12 Good to read that! Will it be available in the Anaconda Cloud?

**Comment by ccordoba12** [comment]
Yes, of course.

**Comment by fbosio** [comment]
¡Muchas gracias! :) Saludos

**Comment by puneetmadaan** [comment]
@fbosio  your fix worked like  a charm, thanks.

**Comment by fbosio** [comment]
> @fbosio your fix worked like a charm, thanks.

@puneetmadaan Well, glad to hear that! I must note though, that this fix in't actually mine, but was proposed in [this issue](https://github.com/tornadoweb/tornado/issues/2608). And, according to @ccordoba12, this fix will not be needed in Spyder 4.1.3.
Anyway, any contribution that I can make, even in an indirect way, makes me happier, so thank you very much for mentioning it!
Regards.

**Comment by CAM-Gerlach** [comment]
Thanks so much for your help, @fbosio ! We really appreciate it. In fact, helping other users on this very issue tracker was the first step for me on the path to being a Spyder core developer. As you mention, 4.1.3 was indeed released a month ago, so now is the time to update if you are still experiencing this issue. Thanks!

**Comment by fbosio** [comment]
> so now is the time to update

@CAM-Gerlach Ok, did my `conda update --all`... all cool!

**Comment by CAM-Gerlach** [comment]
Great to hear!

Actually, we generally recommend you avoid `conda update --all` whenever practicable (and the conda maintainers themselves are strongly considering removing the feature), since it indiscriminately updates all the packages in the environment, which can sometimes introduce untested incompatibilities, bugs and more. Instead, you should just update the particular package you want, in this case Spyder, with `conda update spyder`.
