### ISSUE TITLE
Validate serialized length of modified objects in the Variable Explorer

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#7158]
This is causing huge memory leaks right now, so it's really critical for us to fix it.

**Comment by CAM-Gerlach** [comment]
Is this related or the same as the cause of the memory leaks when modifying objects discussed and confirmed in #5830 , but never fixed?

**Comment by ccordoba12** [comment]
> but never fixed?

I asked @dalthviz to open these issues because the memory leaks were caused by several things, not a single one.

Besides, he's going to work on them in the next couple of weeks.

**Comment by CAM-Gerlach** [comment]
Okay, great! Glad to hear.

**Comment by ccordoba12** [comment]
It's not a duplicate. That issue made me realize all these problems, so leave it open for now. We'll see what to do about it later.
