### ISSUE TITLE
when press Ctrl

### ISSUE THREAD

**Issue by duzijj** [spyder-ide/spyder#7162]
when press Ctrl+D by mistake, the current ipython console will be closed without prompt. But this can't be disabled by preferences.

**Comment by duzijj** [comment]
when press Ctrl+D by mistake, the current ipython console will be closed.But this can't be unabled

**Comment by ccordoba12** [comment]
Unfortunately IPython console shortcuts can't be configured right now, i.e. they are hard-coded. This is a known limitation and we'll try to address it in the future.
