### ISSUE TITLE
Error when passing a regexp to the findreplace widget

### ISSUE THREAD

**Issue by ymurakumo** [spyder-ide/spyder#7177]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/Users/ymurakumo/anaconda3/lib/python3.6/site-packages/spyder/widgets/findreplace.py", line 557, in replace_find_selection
    replacement = re_pattern.sub(replace_text, selected_text)
  File "/Users/ymurakumo/anaconda3/lib/python3.6/re.py", line 326, in _subx
    template = _compile_repl(template, pattern)
  File "/Users/ymurakumo/anaconda3/lib/python3.6/re.py", line 317, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/Users/ymurakumo/anaconda3/lib/python3.6/sre_parse.py", line 879, in parse_template
    s = Tokenizer(source)
  File "/Users/ymurakumo/anaconda3/lib/python3.6/sre_parse.py", line 231, in __init__
    self.__next()
  File "/Users/ymurakumo/anaconda3/lib/python3.6/sre_parse.py", line 245, in __next
    self.string, len(self.string) - 1) from None
sre_constants.error: bad escape (end of pattern) at position 0

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this in our next release.

**Comment by ymurakumo** [comment]
Thanks. I'm looking forward to fix this bug on next Spyder version and update one.

**Comment by CAM-Gerlach** [comment]
So its easy to reproduce, can you provide an example of a regex which causes this error? Thanks.

**Comment by ccordoba12** [comment]
Leaving this to do after 3.3 because we don't a clear to reproduce it.
