### ISSUE TITLE
Inconsistent pandas dataframe output behaviour depending on the datatype of the last column

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#7179]
I'm redirecting this issue to here since it might be a Spyder issue and not a pandas issue:

https://github.com/pandas-dev/pandas/issues/21166

* Spyder version: 3.2.8
* Python version: 3.6.5 64bits
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this after we release 3.3, in a couple of weeks.

**Comment by goanpeca** [comment]
No loner an issue on master. Closing.
