### ISSUE TITLE
Error when loading a notebook 

### ISSUE THREAD

**Issue by KrunalDatascience** [spyder-ide/spyder#7182]
Saved the notebook from spyder. It didn't load post saving. And now tried opened it through spyder-notebook it is not loading and the screen got hanged.

**Comment by ccordoba12** [comment]
Moving to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #149](https://github.com/spyder-ide/spyder-notebook/issues/149) via [**ZenHub**](https://www.zenhub.com/)
