### ISSUE TITLE
Shortcut for closing ipython console missing

### ISSUE THREAD

**Issue by vthuongt** [spyder-ide/spyder#7183]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I want to reassign the shortcut to close an Ipython console. Thus I tried Tools->Preferences->Keyboard shortcuts
I can only find shortcuts for "new tab", "reset namespace" and "restart kernel" for the "ipython_console" context. However I can't find the "close tab"' shortcut which is Ctrl+W in standard configuration. 

### What steps reproduce the problem?

1.  install anaconda and setup new env with spyder
2.  open spyder preferences

### What is the expected output? What do you see instead?
I expect an entry in the list for closing an ipython console tab

## Versions

* Spyder version: 3.2.6
* Python version: 3.6.4 64 bits
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Ubuntu 14.04.5 LTS

### Dependencies
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  0.27.3 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
psutil >=0.3     :  5.4.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
The shortcut is `Ctrl+D`. Unfortunately, most of the IPython console shortcuts can't be configured through Spyder Preferences system because they are hardcoded.

We'll try to address this in the future, but in the meantime you can find all available shortcuts by going to the menu

    Help > IPython documentation > Console help

and reading the section `Key bindings`.

**Comment by vthuongt** [comment]
For me Ctrl+D and Ctrl+W are working. Can I somehow disable Ctrl+W?

**Comment by ccordoba12** [comment]
If it's not present in our Preferences, then you can't, sorry.
