### ISSUE TITLE
“Python has stopped working” on spyder lauch

### ISSUE THREAD

**Issue by jderekito** [spyder-ide/spyder#7185]
Hello,  

I am running Spyder 3.2.8 a windows 10 VM within Anaconda 4.3.27. When I attempt to launch Spyder at the command prompt, I get the following error “Python has stopped working”

I have verified that in this same Anaconda installation, Jupyter Notebook works fine. Also, I should note that Python 2.7 is also installed on the same machine and referenced in the path. Does Spyder look to the Windows path on startup, and if so could that be causing this issue?

Thanks,

Derek

**Comment by ccordoba12** [comment]
> Python 2.7 is also installed on the same machine and referenced in the path

This is really bad. Please remove it and try again.

**Comment by ccordoba12** [comment]
> I have tested this on two other machines (not VMs) with a similar configuration and not been able to reproduce the issue as it occurs on the VM.

Then I'd say this is not a Spyder problem. The real problem is that you have Python2 in your PATH, which can make Spyder to mix Python 2 and 3 packages, leading to the crash you're seeing.

I'm closing this because there's nothing else we can do to help you, sorry.

**Comment by CAM-Gerlach** [comment]
I have another version of Python (like 3.4 or something) on my $PATH$ on Windows (i.e. if I type ``where python`` (or ``which python``, I can never remember ``which`` one is the Windows one and ``which`` one is Linux) in an Anaconda prompt  it will be listed after , and I've never had that problem with Spyder whether from the shortcut, Anaconda Navigator, or from the Anaconda prompt (obviously, if you're launching it from a bare ``cmd`` shell, its not going to work whether or not you had another python installed). You can type ``where python`` yourself and make sure Anaconda python is present and first; if that's the case, then you should be okay in that department.

How are you trying to launch Spyder? I would try the steps in the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ), specifically the [Basic First Aid](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#basic-first-aid-general-troubleshooting) and [Emergency CPR](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) sections, which resolve the great majority of Spyder installation issues.

**Comment by jderekito** [comment]
Thanks for these suggestions. I am still working on the troubleshooting guide, but the where python trick is particularly helpful to know about.

**Comment by jderekito** [comment]
Just wanted to follow-up with what appears to have fixed my issue. 
ccordoba12 suggestion on https://github.com/spyder-ide/spyder/issues/3903
ended up fixing it for me. That was to run:

`conda update qt pyqt spyder`

**Comment by CAM-Gerlach** [comment]
Thanks, good to hear!

**Comment by muhaco** [comment]
At first startup I was getting crash error I deleted the aticfx64.dll file. 'attention above is the translation' :)
