### ISSUE TITLE
Updated computer and now getting SystemExit: "C:\Anaconda\envs\python27\lib\site-packages\spyder\utils\ipython\start_kernel.py", line 226 error

### ISSUE THREAD

**Issue by bellwolf** [spyder-ide/spyder#7186]
I am using spyder3, running python27 in its own environment (windows 10). I am running a package which scrapes tweets and everything was working great - then I updated my computer and now I am getting an SystemExit error. Looks like it is related to ipython or the kernel...

                       Traceback (most recent call last):

                       File "C:\Anaconda\envs\python27\lib\site-packages\spyder\utils\ipython\start_kernel.py", 
                       line 226, in main  locals().pop('__file__')

                      KeyError: '__file__'

Any suggestions? I have already updated pyzmq, ipykernel conda setuptools and reset spyder.

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.2.8). Please update by opening the Anaconda Prompt and running there

    conda update spyder
