### ISSUE TITLE
Interface is messed up after installing several plugins

### ISSUE THREAD

**Issue by iphton** [spyder-ide/spyder#7207]
A few days ago , i've introduced with some of spyder-ide plug-in and tried to install many such as `unittest` , `notebook` , `line profiler` , `spyder-terminal` , `memory-profiler` , `spyder-report`. 

The installation was good though i couldn't install `spyder-vim` and `conda-manager` plug-in. But the main problems was after installing above plug-in when i went to open spyder , it like it's just broken somehow and not responding. 

![g](https://user-images.githubusercontent.com/17668390/40583766-9c0cc656-6149-11e8-80cc-b4ce3fc9d4d6.JPG)

There're no other way actually to uninstall it. But another thing , if i uninstall spyder only from anaconda and then re-install it , it wouldn't solve, i had to uninstall anaconda and re-install it and only then it back to in normal, without plug-in of course.

**Comment by ccordoba12** [comment]
>  it like it's just broken somehow and not responding.

We haven't seen that before. You need to rearrange your plugins manually by pressing the undocking button (the one to the left of the **x** button on the right top of each pane) and move the plugin wherever you want it to be.

However, we'll investigate this further to see why this is happening and try to solve it on our side.

> There're no other way actually to uninstall it

Well, simply remove them with pip or conda. They are proper Python packages.

**Comment by CAM-Gerlach** [comment]
This may be in fact related to #6627 or #6783 . Try ``conda update pyzmq ipykernel`` or ``conda install tornado=4.5.3`` to see if that fixes it.
