### ISSUE TITLE
PyLint plugin reports "Please install pylint" in MacPorts Spyder

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#721]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-07-29T22:41:15Z_

What steps will reproduce the problem?

 1. Install macports python27 @-2.7.2_0
2. Install macports py27-lint @-0.23.0_0
3. Install macports py27-pyqt4 @-4.8.3_1
4. Install Spyder
5. Run Spyder and observe message that says "Please install pylint" in the
PyLint panel. What is the expected output? What do you see instead? Since MacPorts supports several different versions, Python is installed as a Framework.
Ports which use the python PortGroups (  python24,  python25,  python26, and  python31) are automatically installed so as to avoid conflicts. What version of the product are you using? On what operating system? Spyder 2.0.12, python 2.7.2, Mac OS X 

Please provide any additional information below

. I looked in the MacPorts default directory '/opt/local/bin' and found 'pylint-2.7' which is a symbolic link to '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/pylint'.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=721_

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-07-30T08:44:31Z_

I can import pylint from the mac terminal command line and help('modules') lists pylint.

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-07-30T09:23:07Z_

pylint script is located in '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pylint'

When I load pylint in IDLE, it runs the '__init__.py' script inside the aforementioned pylint directory.

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-07-30T14:20:12Z_

I think I have traced the problem to 'pylintgui.py' or 'programs.py' on a MacPorts install of Spyder2. A symbolic-link to pylint, named 'pylint-2.7' is installed in '/opt/local/bin', which is in my PATH. Python is installed as Framework on Mac OS X. I have Python 2.7 installed, which uses the python PortGroup 'python27'. Ports which use the python27 PortGroup are automatically installed so as to avoid conflicts. For instance, pylint is installed into '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/pylint' with the aforementioned link residing in '/opt/local/bin'.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-01T20:58:51Z_

Hi Mark,

I've checked that the only available version in Macports is py26-spyder @-2.0.8, which means you need to install python 2.6 to get Spyder through Macports. But you are reporting that you have Python 2.7 from Macports *and* Spyder 2.0.12, which means you installed the last one from *source*.

So I would bet your problem is that you didn't select the right Python version when you were installing Spyder. You have to write in a terminal:

/opt/local/bin/python2.7 setup.py install

to install it. (I don't know if this is the right path to python2.7 in your MacPorts installation, I'm just guessing here, so please find and use the right one). If you just use

python setup.py install

(as it's mentioned in the README), Spyder will be installed with the first Python version that comes in your PATH and that version most surely don't have pylint installed.

Please tell me if this works for you or not.

Cheers,
Carlos

**Summary:** PyLint plugin reports "Please install pylint" in MacPorts Spyder  
  **Labels:** OpSys-OSX

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-01T21:09:21Z_

**Labels:** Cat-Pylint

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-02T05:51:25Z_

Carlos,

MacPorts allows you to create local portfiles in order to test new versions, or ports that don't exist. The python version selected is controlled by the Portgroup called in the portfile. Please refer to the MacPorts documentation for portfile ( http://guide.macports.org/#development.introduction ), Portgroup ( http://guide.macports.org/#reference.portgroup ) and dependancies ( http://guide.macports.org/#reference.dependencies ).

Also, there is no "pylint" port. There are:

$ port echo name:py.*lint
py-lint                         
py25-lint                       
py26-lint                       
py27-lint                  

As such, none of these ports can claim /opt/local/bin/pylint. That is why there is a suffix on each binary. Any port using this software needs to refer to it by the correct suffixed name.

**Attachment:** [Portfile](http://code.google.com/p/spyderlib/issues/detail?id=721#hc9)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-02T06:28:14Z_

OK, sorry for my confusion, I understand you better now. So you created your own portfile to test Spyder 2.0.12 (quite cool!) and Spyder can't find pylint because there is not a binary called pylint per se.

How are the pylint binaries called by MacPorts? The solution would be to look for these names too, as you suggested.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-02T07:45:30Z_

The name format is pylint{-${python.branch}} 

e.g. pylint-2.5, pylint-2.6, pylint-2.7, etc.

I'm wondering if, for convenience, you should use PYTHONPATH to check for pylint?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-02T12:33:07Z_

It's cleaner -from the developper point of view- to look for the executable (pylint or pylint-{PythoMajor}{PythonMinor}) because we may then use the executable either in another thread (current implementation)  in a separate process, all of this very easily because pylint is assumed to be installed properly (i.e. an executable is available in system PATH.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-02T12:35:38Z_

Sorry, the last comment was posted too fast: current implementation of pylint plugin call pylint in a separate process (not in another thread).

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-02T13:38:06Z_

The only thing is that we need to select the pylint binary according to the python version under which Spyder is running.

Mark, would be ok for you to contribute a little patch for this? As you mentioned, you just have to add some code to get_nt_program_name in utils/programs.py to check for pylint{-${python.branch}}, and return the binary name if it's found in your PATH

You can get the current Python version with:

import sys
sys.version_info

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-03T10:00:46Z_

I have also been discussing this issue on the MacPorts-users list. This patch could be incorporated as a diff file used by the portfile script that installs spyder into the python framework. Or, were you intending to incorporate this on your end?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-03T10:35:03Z_

As I told you, it could go in the function that detects if a program is installed (get_nt_program_name), or it could also go at the definition of PYLINT_PATH (in spyderplugins/widgets/pylintgui.py). On a second thought, I think the first alternative is a bit ugly but the second one is viable.

Maybe it's easier for you to patch Spyder (changing 'pylint' in PYLINT_PATH to, for example, 'pylint-2.7') than for us to add a special piece of code to detect these different versions.

Keep us posted of your decision.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-03T10:38:33Z_

Sorry, get_nt_program_name just constructs the name of the program to be detected (for windows), it doesn't actually detect it.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-08-03T11:06:37Z_

I'm kind of reluctant to handle this in Spyder's code (of course, if it's the only way, we will take action anyway) because there is absolutely no reason for MacPorts to differentiate pylint scripts depending on Python minor version number: after all, this script is an executable that should behaves exactly the same way on any Python version. 

Of course this would make sense to differentiate pylint executable for Python 2 and Python 3. 

So the purist in me would tend to say that when pylint is properly installed, the command 'pylint' should work in a terminal.

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-03T11:51:12Z_

This is a peculiarity with MacPorts. The spyder program is itself installed for each python framework, I.e. spyder-2.6, spyder-2.7, etc.. It therefore makes sense to patch spyder in the MacPorts package. I'll keep you posted.

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-03T18:31:55Z_

I have opened a MacPorts 'ticket' to add a py27-spyder port and apply attached patch so that pylintgui.py checks for pylint by the correct suffixed name. 

I have tested a local install and it works perfectly!

**Attachment:** [Portfile patch-widgets-pylintgui.py.diff](http://code.google.com/p/spyderlib/issues/detail?id=721#hc20)

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-04T07:30:20Z_

Great, we'll leave this issue open until the MacPorts ticket is fixed

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-06T09:47:15Z_

Reading through the 'port' man page I found this section on 'select' target:

select
     For a given group, selects a version to be the default by creating appro-
     priate symbolic links.  For instance, python might be linked to
     python2.6.  Available select groups are installed as subdirectories of
     ${prefix}/etc/select/.  To list the available versions in a group, use
     --list.  To see which version is currently selected for a group, use
     --show.  To change the selected version for a group, use --set.

     For example:

           port select --list python
           port select --show gcc
           port select --set gcc mp-gcc44

Currently, a group does not exist for pylint. If implemented, the command 'pylint' would work in a terminal.

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-06T14:33:18Z_

Ticket `#30626`: 'pylint: use select portgroup' has been submitted to MacPorts. This would allow users to select a version of pylint to be the default (see comment above).

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-09T03:22:37Z_

Does Spyder use PATH to locate all modules (pyflakes, rope, sphinx, matplotlib, IPython and pylint)? I've noticed, for example, that Spyder is able to locate IPython  in my PATH. But it is a symlink with a similar naming convention as pylint, i.e. 'ipython-2.7'.

**Comment by spyder-issues-migrator** [comment]
_From [mark.bre...@gmail.com](https://code.google.com/u/105352503584143565057/) on 2011-08-12T10:52:47Z_

This has been committed in r82219 . Ticket URL: \< https://trac.macports.org/ticket/30446#comment:11 >

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-08-16T08:28:00Z_

Ok, thanks for your work upstream with the MacPorts guys.

If you have any more troubles, please don't hesitate to open more issues. We want to support Mac users as best as we can.

**Status:** WontFix

**Comment by nathan-artist** [comment]
I am having the same problem today with Python 2.7.11 and Spyder 2.3.7 and all its dependencies installed via MacPorts. The "static code analysis" panel in Spyder reports "Please install pylint". But pylint 1.5.3 is already installed (port py27-pylint), with symlinks at /opt/local/bin/pylint and /opt/local/bin/pylint-2.7 and both are in my PATH. Everything else except pylint appears to be working in Spyder.
