### ISSUE TITLE
debugging threads doesn't work in Spyder 

### ISSUE THREAD

**Issue by Dileepmeom** [spyder-ide/spyder#7212]
## Problem Description
I am trying to debug one of my multi-threaded programs in Python 2.7 with Anaconda distribution on Spyder 3.2 (latest release came from Anaconda package)- when the threads are started, IDE is unable to hit any breakpoints and the program runs in normal mode cannot do step by step debugging either.
- the same issue I observed in Pycharm as well. however, if I change the python version from Anaconda to normal python which is again ver 2.7, it works perfectly fine in pycharm. The same in Spyder as Ipython and cloud pickle was there.

### What steps reproduce the problem?

1. check any multi-threaded program in Anaconda installation in spyder, try to debug step mode after threads are started.
2. the same program if you run in a pure python (not Anaconda distribution) and different IDE it works fine.
3. 

### What is the expected output? What do you see instead?
Unable to hit break-points after threads are started 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2
* Python version: 2.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> check any multi-threaded program

Please post a simple code example that we can run and test in our side. Thanks.

**Comment by CAM-Gerlach** [comment]
Closed due to lack of response. If you can provide more information, please re-open and do so. Thanks.

**Comment by KestutisMa** [comment]
Hello, Spyder3 v3.3.1 (on Arch linux), breakpoint on line *print("thread started.")* doesn't hit.
```python
import threading

class MyThread():
    def start(self):
        self._thread = threading.Thread(target=self.run)
        self._thread.start()

    def run(self):
        print("thread started.")

def run():
    myThread = MyThread()
    myThread.start()        

if __name__ == '__main__':
    run()
````
Thanks for attention to this.

**Comment by CAM-Gerlach** [comment]
Thanks for the reproducible example, @KestutisMa . I can get the breakpoint to trigger, but it then exits. The fundamental problem is that ``pdb``/``ipdb`` does not work properly in multithreaded code, which AFAIK is not really possible to fix from our end without replacing ``ipdb``. Fortunately, we are doing just that for Spyder 4 by adding a full debugging kernel, so it might be possible to do so in the future. @dalthviz , can you comment further on this?

> Spyder3 v3.3.1

FYI, the current version in the 3.x stable series is 3.3.3 (with 3.3.4 about to be released), which contains numerous bug fixes and minor improvements, as well as major enhancements to saving and reloading sessions in ``spyder-kernels``. 3.3.1 is many months old now, so its high time to upgrade.

**Comment by dalthviz** [comment]
I think that **maybe** it could be possible to manage debugging with multiplethreads by using `set_trace` explicitly in the code you are running. For example, you will need to put in the `run` method something like:

```python
def run(self):
    import ipdb; ipdb.set_trace()
    print("thread started.")
```

**Comment by CAM-Gerlach** [comment]
@dalthviz I had tested ``pdb.set_trace()`` and ``breakpoint()`` as well, and again debugging stopped at the breakpiont but immediately excited with ``bdb.BdbQuit``.

**Comment by cg-mayrhofer** [comment]
On Spyder 4.2.5 the command `import pdb; pdb.set_trace()` works and the debugger enters the thread. Thanks to @dalthviz for the advise. 
Anyway I had to use pdb and not ipdb...

**Comment by micklexqg** [comment]
> On Spyder 4.2.5 the command `import pdb; pdb.set_trace()` works and the debugger enters the thread. Thanks to @dalthviz for the advise. Anyway I had to use pdb and not ipdb...

On Spyder 5.4.1 the command `import pdb; pdb.set_trace()` still not works, how do you solve it?

**Comment by CAM-Gerlach** [comment]
FWIW, testing in Spyder 5.3.3 on Windows via Conda-Forge, with Python 3.9.4 and Spyder-Kernels 2.3.2 in the console working env and 3.9.12 in Spyder's runtime env, running either `import pdb; pdb.set_trace()` or `breakpoint()` works fine with Run File, Run Cell, and Run Selection with a minimal reproducible example (as well as more complex cases):

```python
print("Test 0")

print("Test 1")

import pdb; pdb.set_trace()

print("Test 2")

print("Test 3")
```

Can you reproduce the issue running this minimal reproducible example? If so, could you please provide the following:

* Paste the version info provided by the `Copy version info` button in the Spyder `About` dialog
* The version of Python (`import sys; sys.version`) and Spyder-Kernels (`import spyder_kernels; spyder_kernels.__version__`) in the Console you're using
* Exact steps to reproduce the error (e.g. how did you run the code)
* The precise behavior you saw when you did so, compared to what you expected

Thanks!
