### ISSUE TITLE
Outline pane, clicking on file name should move to start of file

### ISSUE THREAD

**Issue by gb119** [spyder-ide/spyder#7214]
## Feature Suggestion  Description

Clicking on a leaf node in the outline pane tree takes you to the start of the relevant bit of code, but clicking on the root node (the filename) does nothing. It would be better if it took you to the start of the file.

This would be a useful feature for when one realizes halfway through adding some code that some extra modules need to be imported at the start of the file - being able to quickly get there using the outline view would be handy. It would also make the root node behave in a more consistent fashion to the leaf nodes.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Linux 4.13.0-43-generic

**Comment by ccordoba12** [comment]
Thanks for the suggestion. It seems simple enough that we could implement it in our next release.

**Comment by bcolsen** [comment]
I'm currently using the outliner with "show all files" and clicking back and forth on the files in the list to switch files like switching between tabs. In this work flow, putting the cursor to the top when I switch between files would be less than ideal.

Changing the cursor to the file start if you click on the file name could work if it only brought you to the top of the file when that file is in focus.

Another idea would be to always have a "File Start" top level item at the start of the file tree. This would be a little strange to see but it would be more obvious what will happen when you click on it.

**Comment by ccordoba12** [comment]
@bcolsen, thanks for your input. What if a double-click takes you to the top of the file?

**Comment by bcolsen** [comment]
That would work for me but I don't think it's very discoverable.

I was going to submit the idea that the outliner position should follow the current cursor position. Placing the cursor at the file start before the first tag tag was one of the corner cases for what should be highlighted. Having a "start tag" would help with that.

**Comment by gb119** [comment]
So  when you double click leaf nodes they expand or contract - for UI consistency I'd expect the root file nodes to do the same rather than move the cursor - the fact that currently it does neither is possibly an orthogonal problem!
I don;t normally use the all-files option, but I did notice that when you clicks on a new filename, the old file node is collapsed and the new file node is expanded  - so only the current file is expanded. This made me think that you could get both the switch and move to top of the file behaviors  by looking at whether the file node is expanded or not.
If the file node is not expanded, switch the editor tab, expand the outline view, but don't move the cursor
If the file node is expanded, then move the cursor (and switch editor tabs if necessary).

I don't think that is overloading the UI too much and it seems to my mind consistent with how the outline pane works in other respects. The special 'top-of-file' entry is also possible, but it's a bit VB-esque with a [declarations] section heading....

**Comment by bcolsen** [comment]
> So when you double click leaf nodes they expand or contract - for UI consistency I'd expect the root file nodes to do the same rather than move the cursor - the fact that currently it does neither is possibly an orthogonal problem!

Yes this is what double clicking should do. It actually does do this currently when you click on a file name but since that file becomes the active file then the tree is automatically expended because it is the active file. I don't think this needs to be fixed.

>If the file node is not expanded, switch the editor tab, expand the outline view, but don't move the cursor
>If the file node is expanded, then move the cursor (and switch editor tabs if necessary).

This is a fine idea. I don't think that I'll accidentally click on the file twice.
