### ISSUE TITLE
Error when saving notebooks

### ISSUE THREAD

**Issue by JiangShenLi-1703** [spyder-ide/spyder#7216]
### What steps will reproduce the problem?

Using the spyder-notebook plugin, had run a code cell. Then I used righ-mouse-button on the 'untitled' tab, to save and rename. After hitting ok on the Save, this error popup occured.

### Traceback
```python-traceback
  File "/Users/leejohnson/anaconda3/lib/python3.6/site-packages/spyder_notebook/notebookplugin.py", line 402, in save_as
    nb_contents = nbformat.read(original_path, as_version=4)
  File "/Users/leejohnson/anaconda3/lib/python3.6/site-packages/nbformat/__init__.py", line 138, in read
    with io.open(fp, encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/t1/vlw6f83159q7r73w2vg7syxw0000gn/T/spyder-leejohnson/notebooks/untitled1.ipynb'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Darwin 17.5.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.4.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. I'll move this to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #150](https://github.com/spyder-ide/spyder-notebook/issues/150) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CAM-Gerlach** [comment]
@JiangShenLi-1703 As @ccordoba12 said, please post your comments in the issue thread he opened for you on the correct repo, not this one. Thanks, and best of luck.
