### ISSUE TITLE
underscores are missing in ide

### ISSUE THREAD

**Issue by bobsacamanois** [spyder-ide/spyder#7231]
Some instances of the variable: subnetwork_sna_results

is displayed without underscores in IDE screen, cf attached screenshot. 

![screenshot from 2018-05-30 22-52-42](https://user-images.githubusercontent.com/24832133/40744236-974a1216-645c-11e8-896a-f44899c08e52.png)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.11.3 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
> Qt Versions: 4.8.7, PyQt4 (API v2) 4.11.4 on Linux

Sorry, we don't support Qt/PyQt 4 anymore. Please switch to PyQt5 and try again.

**Comment by bobsacamanois** [comment]
After updating it to PyQT5 (conda install pyqt=5) it worked. 
Thank you for the help Brother.
Bests.

**Comment by ccordoba12** [comment]
Great!
