### ISSUE TITLE
ImportError when trying to load third-party plugins

### ISSUE THREAD

**Issue by amsesk** [spyder-ide/spyder#7259]
## Problem Description

I'm not entirely sure what the effects of this error are, and its doesn't seem to have a negative impact on my uses for spyder. The GUI still opens successfully and I can load, edit, and save files. I figured I'd report this error just in case its resolution can be useful for others. 

Error appeared more or less randomly today and is raised everytime I start it up now. Error first appeared on v3.2.6, but is still appearing after update to v3.2.8 today.

### Traceback
```python-traceback
  File "/Users/kevinamses/miniconda2/lib/python2.7/site-packages/spyder/otherplugins.py", line 85, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/Users/kevinamses/miniconda2/lib/python2.7/site-packages/spyder/otherplugins.py", line 107, in _import_module_from_path
    info = imp.find_module(module_name, [plugin_path])
ImportError: No module named spyder_projects
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.14
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Darwin 15.6.0

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.4.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.7.4 (OK)
```

**Comment by CAM-Gerlach** [comment]
Thanks for reporting; we've never seen this particular bug before.. Have you installed any Spyder plugins? You updated Spyder with ``conda``, not ``pip``, correct? Do the commands in the ``Projects`` menu function? Can you start Spyder from the Terminal (by typing ``spyder``) after first typing ``export SPYDER_DEBUG=3`` to enable debug mode, and see if there is any relevant output and exactly where in the startup sequence the error occurred? 

Also, please post the information listed in [relevant subsection](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#must-have-and-helpful-items-to-include) of the Spyder Troubleshooting Guide as a comment to this issue, and we'll try to help if we can. Thanks, and best of luck!

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this in our next version.

**Comment by amsesk** [comment]
Hello. Yes, I used conda to install and update spyder. The same error occurs when loading with SPYDER_DEBUG=3, just that no error notification window is opened, and the error appears in the command line instead.

` ERROR: 3rd party plugin import failed for `spyder_projects`
Traceback (most recent call last):
  File "/Users/kevinamses/miniconda2/lib/python2.7/site-packages/spyder/otherplugins.py", line 85, in _import_plugin
    module = _import_module_from_path(module_name, plugin_path)
  File "/Users/kevinamses/miniconda2/lib/python2.7/site-packages/spyder/otherplugins.py", line 107, in _import_module_from_path
    info = imp.find_module(module_name, [plugin_path])`

The buttons in the project menu appear to still work (ie I can create a new project), but I don't use these functions, so I can't fully test them out to see if/where they stop working.

I think I've posted all of the relevant information outlined in your link, but let me know if there is anything else and I will try to get you what you need.

Kevin

**Comment by CAM-Gerlach** [comment]
Thanks @amsesk , looks like @ccordoba12 is already on top of things and it'll be fixed shortly. We appreciate your help!
