### ISSUE TITLE
Spyder Summary Table for Logistic Regression Reloaded Anaconda and fixed the problem

### ISSUE THREAD

**Issue by melvin001** [spyder-ide/spyder#7271]
## Description

**What steps will reproduce the problem?**

1. Note the screen shot below.  This code works on one of my computers but not on my new laptop.  Running spyder 3.6
2. logit1 = smf.logit('target_flag ~ mvr_pts+bluebook',data=train)   
result=logit1.fit()
print (result.summary())
3. AttributeError: module 'scipy.stats' has no attribute 'chisqprob'

**What is the expected output? What do you see instead?**
![image](https://user-images.githubusercontent.com/5473962/41170422-229bd48a-6b01-11e8-8b0a-11f1eb77cb92.png)

**Please provide any additional information below**
Hope the image is visible.  If not, the code is under 2. above and the error is under 3.  Error is for the summary table.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
> AttributeError: module 'scipy.stats' has no attribute 'chisqprob'

Sorry, this is an installation problem with Scipy and it has nothing to do with Spyder.

You could try

    conda install -f scipy

to fix it. There's nothing else we can suggest you from our side, sorry.
