### ISSUE TITLE
Failed Installing Spyder3 - "No matching distribution found for spyder3"

### ISSUE THREAD

**Issue by Greilachelous** [spyder-ide/spyder#7273]
Hello,

I'm trying to install inside of a virtualenv (not Anaconda) actually in virtualenvwrapper environment:

`pip3 install spyder3 --user`
```
Collecting spyder3
Could not find a version that satisfies the requirement spyder3 (from versions: )
No matching distribution found for spyder3

```
Python 3.5.2
Ubuntu 16.04 LTS
Qt version: 5.9.3
PyQt version: 5.9.2

virtualenv: 16.0.0
virtualenvwrapper:  4.8.2 

What could be the problem?

**Comment by ccordoba12** [comment]
The package is called spyder, not spyder3.

**Comment by Greilachelous** [comment]
Oh, damn, very sry Sir!
Thank you for your work!
