### ISSUE TITLE
Automatic error report while trying to autocomplete in editor

### ISSUE THREAD

**Issue by west-world** [spyder-ide/spyder#7275]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Updated jedi to version 12.0 ,
Opened spyder ,  try accessing any item that needs autocomplete in the text editor.
Spyder - 3.2.8
Python - 3.6
using anaconda Environment.

**Comment by ccordoba12** [comment]
Thanks for reporting. This error will be fixed in our next version (**3.3.0**) to be released in a couple of weeks.
