### ISSUE TITLE
Error in Online Help

### ISSUE THREAD

**Issue by dmayilyan** [spyder-ide/spyder#7280]
### What steps will reproduce the problem?

Tried to search for `property` keyword in **Online help** tab and received a crash, even though class property was successfully found.

### Traceback
```python-traceback
    self.process_request(request, client_address)
----------------------------------------
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by goanpeca** [comment]
@dalthviz was this fixed by your work?

**Comment by ccordoba12** [comment]
Yeah, I think so.
