### ISSUE TITLE
No module named 'statsmodel'

### ISSUE THREAD

**Issue by HemanthK** [spyder-ide/spyder#7282]
1.  Trying to run the code from the link below.
http://barnesanalytics.com/analyzing-multivariate-time-series-using-arimax-in-python-with-statsmodels
2. import statsmodel.api as sm
3. 

It should Import the statsmodel but I get the following error
No module named 'statsmodel'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.4
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.6.6 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is not a Spyder problem but an installation one, so we can't help you about it, sorry.

**Comment by CAM-Gerlach** [comment]
Make sure you install ``statsmodels`` in the environment in which you're running Spyder.
