### ISSUE TITLE
Syntax error highlighting not working - Spyder 2.3.8 

### ISSUE THREAD

**Issue by mubastan** [spyder-ide/spyder#7289]
Earlier version used to underline syntax errors in the code.

I am currently using Spyder 2.3.8 on Linux Mint 18.3, Python 2.7.12.
I checked the Preferences, but could not find any option related to syntax errors.

Is syntax error highlighting no longer available?

**Comment by ccordoba12** [comment]
> I am currently using Spyder 2.3.8

We don't support this version anymore (it's about three years old). Please update to our latest version (3.2.8) and use PyQt5 instead.
