### ISSUE TITLE
Run With Arguments

### ISSUE THREAD

**Issue by Davo36** [spyder-ide/spyder#7292]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* x[ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* x[ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
You used to be able to run a script in Spyder and specify command line arguments.  Now, the only way this can be done is if the script is run in an external console.  This console then closes as soon as the script finishes, so you can't see the output of your program.

I think it would be really good if we could run scripts in the Spyder IDE IPython console and see the output of a script.

### What steps reproduce the problem?

1.  Open Run -> Configuration Per File
2. The default option of "Execute in Current Console" is selected.
3. The option to add "Command Line Options" is greyed out.
4. If you select "Execute in and external system console" then the option to add "Command Line Options" is available.
5.  When run, the script runs in a system console and that console closes immediately the script is finished - even if the "Interact with the Python console after execution" checkbox is ticked.

### What is the expected output? What do you see instead?
I'd like to be able to run in the integrated Spyder IPython console and be able to specify command line arguments at the same time.

### Paste Traceback/Error Below (if applicable)
N/A

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by ccordoba12** [comment]
@Davo36, look under the section called **General settings**. There you will find **Command line options** and it's not greyed out. 

![seleccion_001](https://user-images.githubusercontent.com/365293/41444480-ed1d5dda-7008-11e8-8c66-a6b7a155d3d0.png)

**Comment by Davo36** [comment]
Ah I see, sorry mate.

I saw it down the bottom there and it didn't occur to me that it was in another place as well.

Thanks for the prompt reply.

**Comment by ccordoba12** [comment]
No problem :+1:

**Comment by CAM-Gerlach** [comment]
Happened to me my first time using it too :)
