### ISSUE TITLE
Cannot get tutorial to launch

### ISSUE THREAD

**Issue by ranaq** [spyder-ide/spyder#7301]
I recently installed Spyder as part of an Anaconda installation. The first couple times I opened Spyder, I received a prompt to view the tutorial. I was working through the tutorial, and was in the 'Hello world' section. I did the exercise where you press CMD + i, to get help on whatever I hovered over. However, in doing so, the help window covered up the tutorial.  When I closed the help window to go back to the tutorial, the tutorial was gone. I tried re-opening the tutorial by going to Help menu > Spyder tutorial. But nothing happens. I tried restarting the Spyder but still no luck. 

version 2.3.8. Python 3.5.1 64bits, Qt 4.8.7, PyQt4(API v2)4.11.4 on Windows

**Comment by ccordoba12** [comment]
> version 2.3.8

We don't support this version anymore because it's more than 3 years old. Please update to our latest one (3.2.8) and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
