### ISSUE TITLE
Can not auto complete code in spyder ide version 3.2.8

### ISSUE THREAD

**Issue by siyoulee** [spyder-ide/spyder#7303]
I'm using anaconda 5.2 and spyder 3.2.8 in Mac or Win10

I found I can auto complete all coding in ipython console using 'Tab',but I can't auto complete in editor.

And interesting is:
some code can auto complete in editor,some code can not.Like bleow:
Positive in completion  : np.*  /  pd.*   /    string.upper()
Negative in completion : dataframe.* 

Please fix it, I try all I can find in these discussion in google  but failed.

**Comment by ccordoba12** [comment]
Please read this

https://stackoverflow.com/questions/42777430/why-autocompletion-options-in-spyder-3-1-are-not-fully-working-in-the-editor

to understand why this doesn't work in our Editor.

**Comment by siyoulee** [comment]
thanks, rodeo is works better and I hope spyder can improve,it's a very useful feature

**Comment by TFDeeplearner** [comment]
I'm using anaconda 5.2 and spyder 3.2.8 in ubuntu16.04, I also have this problem now. I have tried "spyder -- reset" already, but it still doesn't work. No found enum or enum34 in conda list and pip list. Is there any solution now?

**Comment by ajkapoor** [comment]
I am new to spyder and I am facing the same problem of autocompletion not working, can anyone please help, fyi enum or enum34 not found in the conda list
