### ISSUE TITLE
Spyder won't open after updating to Python 3.6.5 no matter what I do - Ubuntu

### ISSUE THREAD

**Issue by tdalis** [spyder-ide/spyder#7308]
I decided to update to the latest Python version and Spyder stop working. I am on Ubuntu 18.04 LTS and I've removed it using Conda, reinstalled it using Conda and from Ubuntu Software App (Store). 
Spyder has become my favorite IDE for Python this year and I'd really liked to continue working on it. Any ideas?

**Comment by beew** [comment]
Works here (installed spyder with pip3) What are the error messages of you start spyder in the terminal?

Ubuntu 18.04 python 3.6.5

**Comment by dalthviz** [comment]
Hi @tdalis maybe following some actions listed in our [Troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ#emergency-cpr-spyder-wont-launch) will help.

Any new information you can give us to trace the issue would be greatly appreciated. For example the error prompt you see in the terminal while running Spyder as @beew suggests, or the way you updated Python (usually mixing ways for the installation of packages brings troubles). If any prompt appears, you can also see if searching that prompt in [other issues](https://github.com/spyder-ide/spyder/issues) shows you a way to make Spyder work again. 

Let us know if something works for you to help others in case they face a similar situation :)

**Comment by tdalis** [comment]
Hey guys, the message I get from the terminal is:
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
When I try to open the Spyder3 outside of the terminal it just stops at the stage from the screenshot.
![spyder3bug](https://user-images.githubusercontent.com/19262536/41592852-ebe0f96c-73b5-11e8-97ab-b938d0293a27.png)
Spyder that works with Python2.7 works as normal, but I work with Python3.6 and Spyder3 won't work. Spyder3 is installed with Anaconda3 and Python3.6 is also installed with Anaconda3 - Do you have any suggestions? Should I remove Anaconda3 if I want to install Spyder3 with pip3 and if so, then it's best to install Python3.6 manually too?

**Comment by ccordoba12** [comment]
> I've removed it using Conda, reinstalled it using Conda and from Ubuntu Software App (Store).

Please read our

https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ

If you are unable to fix the problem after that, please install Anaconda instead. Unfortunately, we don't have the resources nor the time to help people with custom installations, so it's up to you to figure this one out.

This is because custom installations are for experts or very knowledgeable people who really know what they are doing and are able to easily solve problems like this.

**Comment by beew** [comment]
" Anaconda3 if I want to install Spyder3 with pip3 and if so, then it's best to install Python3.6 manually too?"

Ubunti 18.04 comes with python3.6.5

**Comment by ccordoba12** [comment]
Closing because of lack of response.
