### ISSUE TITLE
IPython console pager not working

### ISSUE THREAD

**Issue by fredrik-1** [spyder-ide/spyder#7311]
Is it possible to get a pager that only show one page at a time after writing help(obj)? In the same way as it is in python and standard IPython?

I have tried to set the pager option in spyders/IPython to true but I don't see any difference. Should that feature still work?
 
## Versions

* Spyder version:  3.2.8
* Python version:  3.6.5
* Qt version:  5.6.2
* PyQt version:  5.6
* Operating System name/version:  windows

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by jitseniesen** [comment]
As far as I can see, qtconsole does not page the output of `help`. It does however page the output of `obj?`, which our console does not do, so something seems to be wrong.

**Comment by ccordoba12** [comment]
> As far as I can see, qtconsole does not page the output of help

That's right.

> It does however page the output of obj?, which our console does not do, so something seems to be wrong.

The pager in our consoles is deactivated by default. You can reactivate it in

    Preferences > IPython console > Display > Use a pager to display additional text inside the console

**Comment by jitseniesen** [comment]
I see. Then I don't know exactly what this issue is about.

**Comment by ccordoba12** [comment]
Right, this is not something we can fix here.

@fredrik-1, no, there's no way to use a pager for `help(obj)`, but that's the reason we have our Help pane. You can get the help of any object in there by pressing `Ctrl+I` in front of it.

**Comment by fredrik-1** [comment]
I don't get this. Am I the only one that use `help` and find the behavior in spyder/qtconsole really frustrating and the behavior in python/ipython much better? I really like spyder except for this behavior.

Am I missing something or is something wrong with my spyder? 

If I am working with a matplotlib figure (just an example) I get the following output if I write `ctrl+I` in front of it.

```
The top level container for all the plot elements.

The Figure instance supports callbacks through a callbacks attribute which is a .CallbackRegistry instance. The events you can connect to are 'dpi_changed', and the callback will be called with func(fig) where fig is the Figure instance.

Attributes

patch
The .Rectangle instance representing the figure patch.
suppressComposite
For multiple figure images, the figure will make composite images depending on the renderer option_image_nocomposite function. If suppressComposite is a boolean, this will override the renderer.
```

I don't even get the information in the init function. 

`fig?` is better
```
Type:           Figure
String form:    Figure(640x478)
File:           c:\a_myfiles\github\matplotlib\lib\matplotlib\figure.py
Docstring:     
The top level container for all the plot elements.

The Figure instance supports callbacks through a *callbacks* attribute
which is a `.CallbackRegistry` instance.  The events you can connect to
are 'dpi_changed', and the callback will be called with ``func(fig)`` where
fig is the `Figure` instance.

Attributes
----------
patch
    The `.Rectangle` instance representing the figure patch.

suppressComposite
    For multiple figure images, the figure will make composite images
    depending on the renderer option_image_nocomposite function.  If
    *suppressComposite* is a boolean, this will override the renderer.
Init docstring:
Parameters
----------
figsize : 2-tuple of floats, default: :rc:`figure.figsize`
    Figure dimension ``(width, height)`` in inches.

dpi : float, default: :rc:`figure.dpi`
    Dots per inch.

facecolor : default: :rc:`figure.facecolor`
    The figure patch facecolor.

edgecolor : default: :rc:`figure.edgecolor`
    The figure patch edge color.

linewidth : float
    The linewidth of the frame (i.e. the edge linewidth of the figure
    patch).

frameon : bool, default: :rc:`figure.frameon`
    If ``False``, suppress drawing the figure frame.

subplotpars : :class:`SubplotParams`
    Subplot parameters. If not given, the default subplot
    parameters :rc:`figure.subplot.*` are used.

tight_layout : bool or dict, default: :rc:`figure.autolayout`
    If ``False`` use *subplotpars*. If ``True`` adjust subplot
    parameters using `.tight_layout` with default padding.
    When providing a dict containing the keys ``pad``, ``w_pad``,
    ``h_pad``, and ``rect``, the default `.tight_layout` paddings
    will be overridden.

constrained_layout : bool
    If ``True`` use constrained layout to adjust positioning of plot
    elements.  Like ``tight_layout``, but designed to be more
    flexible.  See
    :doc:`/tutorials/intermediate/constrainedlayout_guide`
    for examples.  (Note: does not work with :meth:`.subplot` or
    :meth:`.subplot2grid`.)
    Defaults to :rc:`figure.constrained_layout.use`.
``` 

Still no information about the methods though.

`help(fig)` get a long output with all information but I need to scroll back to try to find the beginning and the beginning might not even be left in the console for large objects. 

I am most often interested in all information so `help` with a pager is the best option.

**Comment by ccordoba12** [comment]
@fredrik-1, you're welcome to submit a pull request to

https://github.com/jupyter/qtconsole

to use its pager for `help(obj)`. Or you can open this same issue there and wait for us (we're in charge of that repo) or someone else to fix this.

But this is really low priority for us, sorry.

**Comment by NotNormallyAGitUser** [comment]
I've resorted to using Vim to open the a module's *.py file just to see the methods.  I have to get the path to the file from "Object?" in the Spyder console.  A pager would redress this issue.

**Comment by ccordoba12** [comment]
The pager was restored in the Spyder 4 days (i.e. more than two years). So, it seems you're using a quite old Spyder version.

But the pager is still not working with `help`.
