### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by rossolutions** [spyder-ide/spyder#7318]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I can't close the scripts window of jupyter notebooks

**Comment by ccordoba12** [comment]
If you're using `spyder-notebook`, please uninstall it. We're not maintaining it at the moment because we don't have the resources to do it, sorry.
