### ISSUE TITLE
spyder 3.2.8 in fresh conda env in mint 18.3 virtualbox does not start.

### ISSUE THREAD

**Issue by jontis** [spyder-ide/spyder#7323]
## Problem Description
spyder 3.2.8 in fresh conda env in mint 18.3 virtualbox does not start.
First shows the init screen and the crashes before the main screen opens with message:
$ spyder
QApplication: invalid style override passed, ignoring it.
Segmentation fault (core dumped)

git cloning in the master branch and starting from bootstrap.py does start and give an ok looking main window BUT when clicking menu tabs (file, edit, search ... ) does not open a menu.
$ python bootstrap.py 
Executing Spyder from source checkout
Revision a325257, Branch: master
01. Patched sys.path with /home/jonathan/code/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.6.5 64bits, Qt 5.9.4, PyQt5 5.9.2 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.1642
QApplication: invalid style override passed, ignoring it.
QOpenGLFramebufferObject: Unsupported framebuffer format.

## Versions

* Spyder version: 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Mint 18.3 on virtualbox on Mac Book Pro High Sierra

### Dependencies
Not possible

**Comment by jontis** [comment]
Some further info. I was able to get it to start by unchecking "3D acceleration" in my virtual box setup.
Graphics problems?

**Comment by ccordoba12** [comment]
Yes, but not in Spyder. This is a problem with faulty graphics drivers, which cause Qt (the graphical library Spyder is built on) to not render correctly.

Glad you found a solution for it.
