### ISSUE TITLE
Syntax highlighting for numeric literals containing underscores

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#7324]
## Problem Description
I am using the [numeric literals with underscores](https://www.python.org/dev/peps/pep-0515/) new in Python 3.6, because I need to deal with large integers. My Spyder version does not do syntax highlighting correctly with these numbers.

### What steps will reproduce the problem?
Enter the integer `x = 1_000_000` in the editor. The number does not get highlighted as literal like in `x = 1000000`.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll add this functionality in a future release.

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.
