### ISSUE TITLE
Spyder IDE Solid Black Background

### ISSUE THREAD

**Issue by dcosenz1** [spyder-ide/spyder#7327]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I have uninstalled and reinstalled Anaconda and Spyder (Python 3.5) and have also emailed my professor, but to no avail on this issue.  Spyder opens up, but to a solid black background which makes the application unusuable.  I can still right click and scroll over the drop down menus which appear, but I cannot see or write any code because of the black background.  Any help on this please?

### What steps reproduce the problem?

1. Every time I open the app
2. Uninstalling and reinstalling does not work
3. 

### What is the expected output? What do you see instead?
Black screen upon application opening. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.5
* Qt version: 
* PyQt version: 
* Operating System name/version: Anaconda 3 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
What operating system are you using? Windows, Linux or macOS?

**Comment by dcosenz1** [comment]
Windows 7

Best regards,
Dean Cosenza

Villanova University
B.S. Mechanical Engineering 2018
M.S. Mechanical Engineering 2019

dcosenz1@villanova.edu | 516-640-9495
________________________________

**Comment by ccordoba12** [comment]
I think this is caused because you have an Nvidia graphics card and you're using it as the default one. So you have two choices to fix this:

1. Switch to use your Intel card by default. This probably requires restarting your computer.
2. Add a rule to your Nvidia settings to use a file called `pythonw.exe` from Anaconda with your Intel card. I don't know how that's done on Windows, but here you can find more details: https://github.com/ContinuumIO/anaconda-issues/issues/9597.

**Comment by dcosenz1** [comment]
Thank you! I will try both of these and will keep you posted. Appreciate your help!


Best regards,

Dean Cosenza


Villanova University

B.S. Mechanical Engineering 2018

M.S. Mechanical Engineering 2019


dcosenz1@villanova.edu | 516-640-9495

________________________________

**Comment by dcosenz1** [comment]
Hi Carlos,

I am still having the issue with the black background.  I tried both the intel card and adding the line on the Nvidia settings, but the background is still there

**Comment by ccordoba12** [comment]
Another possible solution is for you to open an Anaconda prompt and run there

    conda install pyopengl

and try again.

**Comment by dcosenz1** [comment]
Hi Carlos,

I got it to work! Thank you so much for your help.

Best regards,
Dean Cosenza

Villanova University
B.S. Mechanical Engineering 2018
M.S. Mechanical Engineering 2019

dcosenz1@villanova.edu | 516-640-9495
________________________________

**Comment by ccordoba12** [comment]
Good to know! Just for your information, installing this extra package won't be necessary with our next version (Spyder **3.3**), to be released in a couple of weeks.
