### ISSUE TITLE
Failure checking out a branch and the opened file is in a different path

### ISSUE THREAD

**Issue by manort** [spyder-ide/spyder#7328]
This happened:
1. I had a file opened in Spyder
2. I git-checked out another branch with that file placed in a different path
3. Spyder told me to close the tab since the file couldn't be found
4. Spyder raised an internal problem

TRACE:
  self.refresh_plugin()   # To give focus to the plugin's widget
  File "/Users/manuel/anaconda/envs/sentisis3/lib/python3.6/site-packages/spyder/plugins/explorer.py", line 94, in refresh_plugin
    self.treewidget.update_history(new_path)
  File "/Users/manuel/anaconda/envs/sentisis3/lib/python3.6/site-packages/spyder/widgets/explorer.py", line 1124, in update_history
    directory = osp.abspath(to_text_string(directory))
  File "/Users/manuel/anaconda/envs/sentisis3/lib/python3.6/posixpath.py", line 374, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this in a future release.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Is this because what was previously the working directory doesn't exist on the other branch, and we just need to check for that?

**Comment by ccordoba12** [comment]
Yes, I think so.

**Comment by jitseniesen** [comment]
I can get the same error message without version control using the following steps:

1. Make a new directory
2. Change the Spyder working directory to this directory
3. Delete the directory outside Spyder
4. Click on the File Explorer tab to bring it on top (if it is already on top, then first click on another tab and then click on the File Explorer tab).

**Comment by ccordoba12** [comment]
Ok, thanks a lot @jitseniesen!

@dalthviz, please work on this one.

**Comment by CAM-Gerlach** [comment]
@dalthviz You can't just do ``rm -rf`` in msys2 (Git-bash) or Cygwin?

**Comment by dalthviz** [comment]
Good catch @CAM-Gerlach that was something I didn't test. Although testing it, at least with Git-bash,it doesn't let you delete the directory:

![imagen](https://user-images.githubusercontent.com/16781833/43799965-942f944c-9a54-11e8-9789-42ba2fee8375.png)
