### ISSUE TITLE
When and where spyder 3.3 will be available?

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#7330]
It is not  really a bug report. but According to [roadmap](https://github.com/spyder-ide/spyder/wiki/Roadmap) Spyder 3.3 is already released, but I cannot find it anywhere (it is the master branch??).

Also I would like to test Spyder 4.0dev version, where it could be found?

**Comment by ccordoba12** [comment]
Sorry, it hasn't been released yet. I'll update the roadmap.

Spyder 3.3 is what's present in the 3.x branch. Please read our contributing guide to see how to test our master branch.
