### ISSUE TITLE
Issuewith Ctrl + I,No support for class or method with press of a button. Can't even update contents in object tab. Ctrl +I worked once and hanged thereafter.

### ISSUE THREAD

**Issue by shubhamp01** [spyder-ide/spyder#7332]
## Description

**What steps will reproduce the problem?**

1. 
2. 
![image](https://user-images.githubusercontent.com/40504307/41800451-4283063e-763b-11e8-8fae-9a0c629ce7f6.png)

3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 3.5.2
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by dalthviz** [comment]
Hi @shubhamp01 could you update to Spyder 3.2.8 and see if that helps?

Also please read our [Troubleshooting guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ). Let us know if something there helps you out with the issue.

**Comment by ccordoba12** [comment]
@shubhamp01, it's true we don't support this functionality right now and we don't have plans to do it in the future.

The right way to do this is for you to import first `fit_transform` (for example) in a console, then press `Ctrl+I` next to it to see its help.
