### ISSUE TITLE
Spyder IPython Console hangs after a few seconds when there is an error

### ISSUE THREAD

**Issue by KrishSankaran** [spyder-ide/spyder#7334]
Dear members, 

 I am new to Python, coming from Matlab and Fortran background. In the last few weeks, I have been working with Spyder IDE to programme some back numerical methods. I have had a frequent hanging of IPython console on Spyder. It is quite strange that it goes to hanging mode. I am not sure if this is the issue of Spyder or the libraries I have in the programme. 

I am running the Spyder on my Mac OS and it is fully functional when the code is running. But if it has some errors...it goes into hanging mode. Kindly excuse me if this issue has been already addressed elsewhere. 

These are the dependencies I have in the programme
import math
import numpy as np 
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

The IPython console goes to hanging mode like this
In [2]...
    ....
    ....
I need to finally kill the IPython console with CMD+. on my mac OS

Thanks for your support. 

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> These are the dependencies I have in the programme

Please provide a complete program, not juts its beginning (unless only with the code you provided you're seeing the error you mention here).

> Spyder version:
    Python version:
    Qt version:
    PyQt version:
    Operating System name/version:

Please provide all this information. You can get it by going to the menu `Help > About Spyder`.

**Comment by KrishSankaran** [comment]
Hola Carlos, 

My Spyder version is 3.2.8 and I using Mac OS High Sierra 10.13.5. 

The modules are as follows:

Module  Min required : Installed
IPython  >=4.0    :  6.4.0 (OK)
cython   >=0.21    :  None (NOK)
jedi        >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
psutil >=0.3     :  5.4.5 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.9.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

The code is a simple numerical plotting as below
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 25 02:15:30 2018

@author: Dr. Krish Sankaran
"""

import math
import numpy as np 
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt


eps = 8.854e-12
mu = 12.56637061e-7
freq = 10e9
c = 3e8 

wavelen = c/freq

ppw = 10 

BCs = 'pec'

xmin = 0.0
xmax = 0.3
ymin = 0.0
ymax = 0.3

dx = dy = wavelen / ppw
nSteps = 10
nx = int(abs(xmax-xmin)/dx)
ny = int(abs(ymax-ymin)/dy)

dt = (c*np.sqrt((dx**-2)+(dy**-2)))**-1 

Gn0 = 10
edec = 10


Bx=np.zeros((nx,ny))
By=np.zeros((nx,ny))
Ez=np.zeros((nx,ny))



CB_dx=(dt/dx)*(1/(mu*eps))
CB_dy=(dt/dy)*(1/(mu*eps))
CE_dx=(dt/dx)
CE_dy=(dt/dy)
            
# setup meshgrid
xc = np.linspace(xmin,xmax,nx,endpoint=True)
yc = np.linspace(ymin,ymax,ny,endpoint=True)
X,Y = np.meshgrid(xc,yc)

for n in range(nSteps):
    print(n)
       
    for i in range(Bx.shape[0]): 
        for j in range(Bx.shape[1]-1):
            Bx[i,j]=Bx[i,j]-CE_dy*(Ez[i,j+1]-Ez[i,j])

    for i in range(By.shape[0]-1): 
        for j in range(By.shape[1]):
            By[i,j]=By[i,j]+CE_dx*(Ez[i+1,j]-Ez[i,j])
    
    for i in range(1,Ez.shape[0]-1): 
        for j in range(1,Ez.shape[1]-1):
            Ez[i,j]=Ez[i,j]+CB_dx*(By[i,j]-By[i-1,j])-CB_dy*(Bx[i,j]-Bx[i,j-1])
           
    if source == 'Sinosoidal': 
        Ez[(nx)//2,(ny)//2] = 2*np.sin(2*np.pi*freq*n*dt) 
    elif source == 'Gaussian':
        Ez[(nx)//2,(ny)//2] = (math.exp(-((n-Gn0)/edec)**2))
    
    if BCs == 'pec': 
        for i in range(Ez.shape[0]):            
            Ez[i,0]=0
            Ez[i,Ez.shape[1]-1]=0
        for j in range(Ez.shape[1]):
            Ez[0,j]=0
            Ez[Ez.shape[0]-1,j]=0
    
    ax = Axes3D(plt.figure(1))
    ax.plot_surface(X,Y,Ez,cmap='hot')
    ax.contour(X,Y,Ez,zdir="x",offset=xmin) 
    ax.contour(X,Y,Ez,zdir="y",offset=ymax)
    ax.contour(X,Y,Ez,zdir="z",offset=-2.0)
    ax.set_zlim3d(-2, 1.5)
    ax.set_xlabel('X Label') 
    ax.set_ylabel('Y Label')
    ax.set_zlabel('Z Label')

    plt.pause(0.0001) 

-------------------------------------
Thanks for your support.

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by KrishSankaran** [comment]
Python version: 3.6.5
Qt version: not sure how to find it
PyQt version: not sure how to find it. 

Sorry was waiting for your response...didnot realize that you are waiting for more info from my side.

**Comment by KrishSankaran** [comment]
I installed Spyder3 using pip3 install command.

**Comment by KrishSankaran** [comment]
Python version: 3.6.5
Qt version 4.8.7 
Spyder3 installed using pip3 install command.

Here is the complete list

pip3 list
Package                  Version  
------------------------ ---------
alabaster                0.7.10   
appnope                  0.1.0    
apptools                 4.4.0    
astroid                  1.6.4    
Babel                    2.5.3    
backcall                 0.1.0    
bleach                   2.1.3    
certifi                  2018.4.16
chardet                  3.0.4    
click                    6.7      
cloudpickle              0.5.3    
configobj                5.0.6    
cycler                   0.10.0   
decorator                4.3.0    
docutils                 0.14     
entrypoints              0.2.3    
envisage                 4.6.0    
Flask                    1.0.2    
html5lib                 1.0.1    
idna                     2.6      
imagesize                1.0.0    
ipykernel                4.8.2    
ipython                  6.4.0    
ipython-genutils         0.2.0    
isort                    4.3.4    
itsdangerous             0.24     
jedi                     0.12.0   
Jinja2                   2.10     
jsonschema               2.6.0    
jupyter-client           5.2.3    
jupyter-core             4.4.0    
kiwisolver               1.0.1    
lazy-object-proxy        1.3.1    
llvmlite                 0.23.2   
MarkupSafe               1.0      
matplotlib               2.2.2    
mayavi                   4.6.0    
mccabe                   0.6.1    
mistune                  0.8.3    
mpmath                   1.0.0    
nbconvert                5.3.1    
nbformat                 4.4.0    
numba                    0.38.1   
numpy                    1.14.3   
numpydoc                 0.8.0    
packaging                17.1     
pandas                   0.23.0   
pandocfilters            1.4.2    
parso                    0.2.0    
pexpect                  4.5.0    
pickleshare              0.7.4    
Pint                     0.8.1    
pip                      10.0.1   
prompt-toolkit           1.0.15   
psutil                   5.4.5    
ptyprocess               0.5.2    
pycodestyle              2.4.0    
pyface                   6.0.0    
pyflakes                 1.6.0    
Pygments                 2.2.0    
pylint                   1.9.1    
pyparsing                2.2.0    
PyQt5                    5.11.2   
PyQt5-sip                4.19.11  
python-dateutil          2.7.3    
pytz                     2018.4   
pyzmq                    17.0.0   
QScintilla               2.10.7   
QtAwesome                0.4.4    
qtconsole                4.3.1    
QtPy                     1.4.2    
requests                 2.18.4   
rope                     0.10.7   
scipy                    1.1.0    
seaborn                  0.8.1    
setuptools               39.2.0   
simplegeneric            0.8.1    
sip                      4.19.8   
six                      1.11.0   
snowballstemmer          1.2.1    
Sphinx                   1.7.4    
sphinxcontrib-websupport 1.0.1    
spyder                   3.2.8    
sympy                    1.1.1    
testpath                 0.3.1    
tornado                  5.0.2    
traitlets                4.3.2    
traits                   4.6.0    
traitsui                 6.0.0    
urllib3                  1.22     
vtk                      8.1.1    
wcwidth                  0.1.7    
webencodings             0.5.1    
Werkzeug                 0.14.1   
wheel                    0.31.1   
wrapt                    1.10.11

**Comment by KrishSankaran** [comment]
PyQt5 5.11.2 is already installed. 
If there is no support this installation method, I totally understand. No issues. 
Thanks for support. 

Best regards

**Comment by ccordoba12** [comment]
I hope your problem is solved now. Thanks for understanding.
