### ISSUE TITLE
Update readme and contributing guide to reflect need to install (correct version of) spyder-kernels

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#7337]
The last 2 pushes on the upstream fail.
I had to downgrade to PR#7287, or a325257695644caf22e22e6d64c6a5db9a7e0c90 (2 pushes ago), then it works.

```
D:\>\Contrib\spyder\bootstrap.py
Executing Spyder from source checkout
Traceback (most recent call last):
  File "D:\Contrib\spyder\bootstrap.py", line 118, in <module>
    from spyder.utils.vcs import get_git_revision
  File "D:\Contrib\spyder\spyder\utils\vcs.py", line 16, in <module>
    from spyder.utils import programs
  File "D:\Contrib\spyder\spyder\utils\programs.py", line 23, in <module>
    from spyder.config.utils import is_anaconda
  File "D:\Contrib\spyder\spyder\config\utils.py", line 15, in <module>
    from spyder_kernels.utils import iofuncs
ModuleNotFoundError: No module named 'spyder_kernels' to start. 
```

cheers.

**Comment by ccordoba12** [comment]
We added a new dependency to Spyder called `spyder-kernels`. To fix this problem you simply need to run

    pip install spyder-kernels==1.*

if you're in master, or

   pip install spyder-kernels==0.*

if you're in our 3.x branch.

**Comment by jnsebgosselin** [comment]
@ccordoba12 What is your setup for running Spyder from source? Do you use a clone of the `spyder-kernels` and switch back from the `master` to the `0.x` branch when switching from the `master` to the `3.x` in Spyder and vice-versa?

**Comment by ccordoba12** [comment]
I think I'll need to have four conda/venvs from now on: two for master (py27 and py36) and two for 3.x (py27 and py36).

I know `spyder-kernels` adds another layer complexity to development, but it will be of great help for users. Besides, it helped us to simplify a lot how we start and handle kernels in Spyder.

**Comment by jnsebgosselin** [comment]
Ok, I understand, thanks for your insights!

Maybe the Readme section [Running from a Github clone](https://github.com/spyder-ide/spyder#running-from-a-github-clone) and the [contributing instructions](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md) will need a little update to take into account this change.

I'm not sure our current instruction are still valid if one wishes to run Spyder from source on the master branch because the version of `spyder-kernels` that is going to be installed will be for the 3.x branch.

**Comment by ccordoba12** [comment]
You're right. @CAM-Gerlach, could you help us to update our installation instructions?

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Thanks; will do in the docs. I presume you also like me to update the readme and contributing files here? I can edit this issue accordingly if so.

**Comment by ccordoba12** [comment]
> I presume you also like me to update the readme and contributing files here?

Yes, please.
