### ISSUE TITLE
Outline explorer not synchronized at startup

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#7338]
A small GUI bug.

When starting spyder with several files open, and the "structure panel" switched on. The GUI ends up, just after booting, with first file tab and apparently last parsed structure (from last tab), hence leading to a non synchronization between the 2. Switching twice file tabs resynchronizes everything hopefully.

(current mainstream)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at it in a future release.

**Comment by ccordoba12** [comment]
> what is the reasoning behind this new "smart" behavior in Spyder 4?

A user suggested that it's annoying to see the focus in the Editor changing continually when Spyder is starting. That's why we keep the focus in the last opened file (I think, or is it the first one? I don't remember) in Spyder 4, while the others are loaded in the background.

**Comment by jnsebgosselin** [comment]
> A user suggested that it's annoying to see the focus in the Editor changing continually when Spyder is starting. That's why we keep the focus in the last opened file (I think, or is it the first one? I don't remember) in Spyder 4, while the others are loaded in the background.

I agree, but I think this would be better if we could solve this "file-focus-changing" issue without actually moving the last focused file to index 0. Having Spyder messing up with the order of the files every-time it is started is annoying.

Would you be opened to change this if I can find a better solution (and I would also fix this issue in the same time)?

**Comment by ccordoba12** [comment]
Sure, I have no problem with that.

**Comment by jnsebgosselin** [comment]
Alright, I'll take a look at this.
