### ISSUE TITLE
Indent guides going too far down

### ISSUE THREAD

**Issue by sylvain-bougnoux** [spyder-ide/spyder#7339]
Another 2c bug.

In my opinion indent guides are going too far.

![image](https://user-images.githubusercontent.com/6706662/41836946-7e959114-785c-11e8-8d9c-9d1c431c0eb2.png)

Even worst

![image](https://user-images.githubusercontent.com/6706662/41836905-5ba54230-785c-11e8-9f16-9553407d00d8.png)

Thanks.

**Comment by ccordoba12** [comment]
I don't understand what you mean. Are you suggesting that we shouldn't show the indentation guides in those two cases?

**Comment by sylvain-bougnoux** [comment]
Not exactly, I think the vertical line goes 1 or 2 lines too far (going down) – it is too long. It is clear in the 2nd example, it should not be displayed above the comment. It should stick to the concerned block.
 
 
 
De : Carlos Cordoba <notifications@github.com> 
Envoyé : lundi 25 juin 2018 18:15
À : spyder-ide/spyder <spyder@noreply.github.com>
Cc : sylvain-bougnoux <bougnoux@imra-europe.com>; Author <author@noreply.github.com>
Objet : Re: [spyder-ide/spyder] Indent guides going too far down (#7339)
 
I don't understand what you mean. Are you suggesting that we shouldn't show the indentation guides in those two cases?

**Comment by ccordoba12** [comment]
I see, thanks for the clarification.

**Comment by ccordoba12** [comment]
@texadactyl, that's a completely different problem from the one reported here. Please open a new issue about it, instead of trying to hijack this one.

**Comment by ccordoba12** [comment]
Sorry, not an English-native speaker here (*derailed* perhaps is better). This issue is about a new feature in our master branch, so it has nothing to do with your problem.

**Comment by adodell** [comment]
Can confirm this is an issue, I am running Spyder 4.0.0b1 and I get something similar with the Indent Guides.

![capture](https://user-images.githubusercontent.com/11433737/44219276-7c41f680-a130-11e8-814f-3bf3c6ebe84c.PNG)

As you can see, the Indent Guide will go straight through comments, but it will stop at the first line of real python code

![capture2](https://user-images.githubusercontent.com/11433737/44219380-b7dcc080-a130-11e8-8995-b360427b0f36.PNG)

I think the Indent will keep going until there is a line of real python code, as seen below...

![capture3](https://user-images.githubusercontent.com/11433737/44219436-db077000-a130-11e8-9af2-aa944c65f010.PNG)

There are no tabs on lines 6 or 7, but the Indent Guide keeps going down until the print statement.

I hope that clarifies things Carlos, I'm loving the new additions to Spyder 4 already!

**Comment by Khalilsqu** [comment]
I resolved this Issue, would you accept PR? I am just not sure how to send PR, this is my first time.

CODE BEFORE 
![spyder_issue_indentation_before](https://user-images.githubusercontent.com/22060413/50304674-7c5c5500-0488-11e9-90e8-fc932f6e5b19.JPG)

CODE AFTER RESOLVING THE ISSUE.
![spyder_issue_indentation](https://user-images.githubusercontent.com/22060413/50304694-91d17f00-0488-11e9-85f3-e7f64296c124.JPG)
