### ISSUE TITLE
Link to Fedora website is broken on installation page

### ISSUE THREAD

**Issue by fwolfheimer** [spyder-ide/spyder#7341]
## Problem Description
The "Fedora" link on the download website is broken.
https://pythonhosted.org/spyder/installation.html -> Installation on Linux -> 3. Other Distributions ->Fedora.

### What steps reproduce the problem?
Go to the website and click on the link.

### What is the expected output? What do you see instead?
Website opens.

**Comment by ccordoba12** [comment]
We can't update the documentation placed in https://pythonhosted.org/spyder. However, this problem is already fixed in our new documetation website:

http://docs.spyder-ide.org/installation.html
