### ISSUE TITLE
Spyder closes unexpectedly while resizing window layout

### ISSUE THREAD

**Issue by pxcandeias** [spyder-ide/spyder#7348]
## Problem Description

Spyder closes unexpectedly while resizing window layout. This happens on **Linux Mint 18.3**, on **Windows10 64bits** there are no problems with an equivalent installation (same _Python, Anaconda and Spyder_ versions).

### What steps reproduce the problem?

1.  Open Spyder
2.  Select Spyder Default Layout
3.  Resize window layout until Spyder closes unexpectedly (although not immediate, it does not take long)

### What is the expected output? What do you see instead?

Resizing of the window layout. Spyder closes unexpectedly. Not sure if this happens only with Spyder Default Layout, have not tested all the others.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> spy.app
<PyQt5.QtWidgets.QApplication object at 0x7f27e6bc81f8>

>>> spy.window
<spyder.app.mainwindow.MainWindow object at 0x7f27ee4adb88>

>>> dir(spy)
['app', 'versions', 'window']

>>> 
```

## Versions

* Spyder version: 3.2.8
* Python version: Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Linux Mint 18.3

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
psutil >=0.3     :  5.4.5 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
> This happens on Linux Mint 18.3, on Windows10 64bits there are no problems with an equivalent installation

If this happens on Linux and not on Windows, then it doesn't look as a problem in Spyder but in Qt. And if that's the case, then we can't do anything about it, sorry.

Besides, I can't reproduce it locally (although I'm using Kubuntu 17.04).
