### ISSUE TITLE
every pip install , spyder don't start show bad pyqt5 version 

### ISSUE THREAD

**Issue by catafest** [spyder-ide/spyder#7351]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

spyder 3.2.8 has requirement pyqt5<5.10; python_version >= "3", but you'll have
pyqt5 5.10.1 which is incompatible.

### What steps reproduce the problem?

1.  every pip install spyder report same error 
2. spyder --reset don't solve the start of spyder 
3. spyder don's start 

### What is the expected output? What do you see instead?
spyder cannot deal with pyqt5 versions 
spyder don's start 
spyder 3.2.8 has requirement pyqt5<5.10; python_version >= "3", but you'll have
pyqt5 5.10.1 which is incompatible.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: spyder 3.2.8
* Python version: Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
 on win32
* Qt version: 
* PyQt version: pyqt5 5.10.1 which is incompatible.
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> spyder 3.2.8 has requirement pyqt5<5.10; python_version >= "3", but you'll have
pyqt5 5.10.1 which is incompatible.

What is that you don't understand about this message? It's quite clear to me: we don't support pyqt 5.10 or higher, but pyqt 5.9 or less. So your solution is to run

    pip install pyqt==5.9*

**Comment by apostlechinx** [comment]
Could not find a version that satisfies the requirement pyqt==5.9* (from versions: )

**Comment by ccordoba12** [comment]
It's `pyqt5`, not `pyqt`, sorry.

**Comment by anilpankaj** [comment]
Could not find a version that satisfies the requirement pyqt5==5.9* (from versions: 5.8, 5.8.1.1, 5.8.2, 5.9, 5.9.1, 5.9.2, 5.10, 5.10.1, 5.11.2, 5.11.3, 5.12, 5.12.1, 5.12.2)
No matching distribution found for pyqt5==5.9*

**Comment by MMaazT** [comment]
@anilpankaj remove the asterisk after 5.9.

**Comment by MajidAkh** [comment]
pip install pyqt5

remove the "=="
