### ISSUE TITLE
spyder cannot connect to kernel

### ISSUE THREAD

**Issue by atahadd** [spyder-ide/spyder#7354]
### What steps reproduce the problem?
Spyder used to work properly. I updated a package and did not work
Now it cannot connect to kernel.

When I reset spyder this error appears:
_qt.qpa.gl: Unable to disable rotation.
*** Reset Spyder settings to defaults ***
removing: C:\Users\admin\.spyder-py3\spyder.ini
removing: C:\Users\admin\.spyder-py3\langconfig_

## Versions

* Spyder version: 3.2.8
* Python version: 3.5
* Qt version: 5.9,5
* PyQt version: 5.9.2
* Operating System name/version: window 7 (64)

**Comment by ccordoba12** [comment]
> Spyder used to work properly. I updated a package and did not work

We can't help you with such sparse info. Please start Spyder from a system terminal (cmd.exe) and report any errors shown there.

**Comment by atahadd** [comment]
spyder is running and does not show any error.
When it lunches, connecting to kernel appears without any response

**Comment by ccordoba12** [comment]
> spyder is running and does not show any error.

I'm very sorry but we can't help you further. If there's no error, it shouldn't be any error when connecting to kernels.

**Comment by ccordoba12** [comment]
Sorry, I forgot this is usually a problem with your antivirus/firewall blocking network communications in your computer. So you should deactivate them and try again.
