### ISSUE TITLE
Spyder 3.6.8 async def feature failure 

### ISSUE THREAD

**Issue by kennyjudo** [spyder-ide/spyder#7359]
## Problem Description
Spyder 3.6.8, WIN10, Anaconda, I just run the sample from python.org as below, it has error message "raise RuntimeError('This event loop is already running') and do not go through the rest of program, just hang..... 

code as below: 

```python
async def hello_world():
    print("Hello World!")

loop = asyncio.get_event_loop()
# Blocking call which returns when the hello_world() coroutine is done
loop.run_until_complete(hello_world())
loop.close()
```

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@minrk, @takluyver, quick question: is the asycio event loop already supported by IPython/ipykernel? I saw some work on that but I'm not sure if it's done its way into a release yet.

**Comment by takluyver** [comment]
No, I don't think it's even merged.

**Comment by ccordoba12** [comment]
Thanks for the info @takluyver!

@kennyjudo, I'm closing this one because there's nothing we can do about it in Spyder. You have to wait until IPython/ipykernel adds support for the asyncio eventloop, sorry.
