### ISSUE TITLE
Unable to launch Spyder from Anaconda Navigator 1.8.7 on Windows 10

### ISSUE THREAD

**Issue by danchhuang** [spyder-ide/spyder#7364]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ X Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

I've followed the above steps but I don't know to tick the check boxes

## Problem Description
Unable to launch Spyder from Anaconda Navigator 1.8.7 on Windows 10. The Spyder window will pop up to a blank window with the title bar showing (Not Responding)

The error message I get:
[964:14260:0628/212821.305:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[964:14260:0628/212821.306:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\lazzy\AppData\Local\Spyder\QtWebEngine\Default\GPUCache to C:\Users\lazzy\AppData\Local\Spyder\QtWebEngine\Default\old_GPUCache_001
[964:14260:0628/212821.306:ERROR:cache_creator.cc(134)] Unable to create cache
[964:14260:0628/212821.306:ERROR:shader_disk_cache.cc(570)] Shader Cache Creation failed: -2

However, if I reset Spyder it would then work, but I have to reset Spyder everytime I want to open Spyder. Same issue whether I try open it from start menu or cmd or navigator.

I have done a complete reinstall of anaconda but same issue persists.

### What steps reproduce the problem?

1. Shut down Spyder and reopen it.
2. 
3. 

### What is the expected output? What do you see instead?
Spyder to open without any issue

### Paste Traceback/Error Below (if applicable)

[964:14260:0628/212821.305:ERROR:cache_util_win.cc(20)] Unable to move the cache: 5
[964:14260:0628/212821.306:ERROR:cache_util.cc(134)] Unable to move cache folder C:\Users\lazzy\AppData\Local\Spyder\QtWebEngine\Default\GPUCache to C:\Users\lazzy\AppData\Local\Spyder\QtWebEngine\Default\old_GPUCache_001
[964:14260:0628/212821.306:ERROR:cache_creator.cc(134)] Unable to create cache
[964:14260:0628/212821.306:ERROR:shader_disk_cache.cc(570)] Shader Cache Creation failed: -2

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please open the Anaconda Prompt and run there

    conda install pyopengl

That should solve this problem.

**Comment by danchhuang** [comment]
I have installed pyopengl but it did not solve the problem.

**Comment by ccordoba12** [comment]
Sorry but this doesn't look like something we can help you to fix in Spyder. It seems a bug in Qt, the graphical toolkit upon which Spyder is built.

**Comment by ccordoba12** [comment]
That's why I'm closing this one for now.

**Comment by ccordoba12** [comment]
>  I'm not sure if this is the issue of my laptop where the HDMI only uses the dedicated Nvidia GTX1070 Max-Q graphics card.

I'd say this is the source of the problem.

**Comment by kaungsoethar** [comment]
> Sorry but this doesn't look like something we can help you to fix in Spyder. It seems to be a bug in Qt, the graphical toolkit upon which Spyder is built.

Thank you
That works well

**Comment by supriyode2181** [comment]
unable to launch spyder after reset
unable to install it by conda install qt=5.6* pyqt=5.6* sip=4.18*
I have attached few screen shots please help me on that matter
![prob@spyder](https://user-images.githubusercontent.com/53032734/61433652-82001780-a951-11e9-892a-4d0c52b1d15b.png)
![prob@spyder02](https://user-images.githubusercontent.com/53032734/61433655-8298ae00-a951-11e9-98ab-0c7b8048410f.png)
![prob@spyder03](https://user-images.githubusercontent.com/53032734/61433656-83314480-a951-11e9-8e3e-f8a98cc849d9.png)

**Comment by luizabbadia** [comment]
conda install qt=5.6* pyqt=5.6* sip=4.18*
this worked for me!!! 
Many thanks

**Comment by KBC1997** [comment]
Have installed the tensarflow environment in anaconda... but spyder is not getting launched 
Its only working under base environment...
please share the solution
