### ISSUE TITLE
Spyder cannot start after upgrading to 3.2.8 

### ISSUE THREAD

**Issue by JiangShenLi-1703** [spyder-ide/spyder#7371]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
'''
Traceback (most recent call last):
  File "/home/nxf28235/.conda/envs/my_root/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>                                                                                                                      
    from PyQt5.QtWebEngineWidgets import QWebEnginePage                                                                
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory                                    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nxf28235/.conda/envs/my_root/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/nxf28235/.conda/envs/my_root/lib/python3.6/site-packages/spyder/app/start.py", line 164, in main
    from spyder.app import mainwindow
  File "/home/nxf28235/.conda/envs/my_root/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/nxf28235/.conda/envs/my_root/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
'''

### What steps reproduce the problem?

1. Execute spyder from the Linux command line
2. Or, attempt to launch Spyder from Anaconda Navigator
3. Or, cd to the Spyder install app directory, launch 'jupyter qtconsole', run start.py

### What is the expected output? What do you see instead?
Spyder doesn't launch, get error traceback due to libEGL.so.1 not found.

### Paste Traceback/Error Below (if applicable)

```python-traceback

run start.py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.conda/envs/my_root/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py in <module>()
     21     try:
---> 22         from PyQt5.QtWebEngineWidgets import QWebEnginePage
     23         from PyQt5.QtWebEngineWidgets import QWebEngineView

ImportError: libEGL.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

ModuleNotFoundError                       Traceback (most recent call last)
~/.conda/pkgs/spyder-3.2.8-py36_0/lib/python3.6/site-packages/spyder/app/start.py in <module>()
    179 
    180 if __name__ == "__main__":
--> 181     main()

~/.conda/pkgs/spyder-3.2.8-py36_0/lib/python3.6/site-packages/spyder/app/start.py in main()
    157         if lock_created:
    158             # Start a new instance
--> 159             from spyder.app import mainwindow
    160             if running_under_pytest():
    161                 return mainwindow.main()

~/.conda/envs/my_root/lib/python3.6/site-packages/spyder/app/mainwindow.py in <module>()
     90 
     91 # Avoid a bug in Qt: https://bugreports.qt.io/browse/QTBUG-46720
---> 92 from qtpy import QtWebEngineWidgets  # analysis:ignore
     93 
     94 # To catch font errors in QtAwesome

~/.conda/envs/my_root/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py in <module>()
     24         from PyQt5.QtWebEngineWidgets import QWebEngineSettings
     25     except ImportError:
---> 26         from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
     27         from PyQt5.QtWebKitWidgets import QWebView as QWebEngineView
     28         from PyQt5.QtWebKit import QWebSettings as QWebEngineSettings

ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```

## Versions

* Spyder version: 3.2.4 (Should be 3.2.8, but 'conda update --all' downgraded Spyder for some reason)
* Python version: 3.6.3
* Qt version:        5.6.2
* PyQt version:    5.6.0
* Operating System name/version: Red Hat Enterprise Linux Server release 6.7 (Santiago)

### Dependencies

From 'conda info spyder'
```
    chardet >=2.0
    cloudpickle
    jedi >=0.9
    nbconvert
    numpydoc
    pickleshare
    psutil
    pycodestyle
    pyflakes
    pygments >=2.0
    pylint
    pyqt
    python >=3.5,<3.6.0a0
    pyzmq
    qtawesome >=0.4.1
    qtconsole >=4.2
    qtpy >=1.2.0
    rope >=0.9.4
    sphinx

```

**Comment by JiangShenLi-1703** [comment]
Re: The spyder version: It appears I genuinely  have Spyder 3.2.8.
Executing 'conda update spyder -n my_root' results in:

spyder                    3.2.8                    py36_0

**Comment by ccordoba12** [comment]
To fix this please open a system terminal (xterm, console, etc) and run there

    conda install pyopengl

**Comment by JiangShenLi-1703** [comment]
I did that yesterday (amongst other fix attempts I found through searching).
Here are the specifics (saved earlier today):
< The last of 379 lines saved from 'conda info pyopengl'>
pyopengl 3.1.1a1 np19py35_0
---------------------------
file name   : pyopengl-3.1.1a1-np19py35_0.tar.bz2
name        : pyopengl
version     : 3.1.1a1
build string: np19py35_0
build number: 0
channel     : defaults
size        : 1.1 MB
arch        : x86_64
date        : 2015-09-10
license     : BSD
md5         : 45ae01c145892556023b4826b98ddb43
noarch      : None
platform    : linux
url         : https://repo.continuum.io/pkgs/free/linux-64/pyopengl-3.1.1a1-np19py35_0.tar.bz2
dependencies:
    freeglut 2.8.1
    numpy 1.9*
    python 3.5*

**Comment by JiangShenLi-1703** [comment]
I just now realize you closed the issue, without my verifying it’d been
solved.

I had already installed pyopengl without it being a fix.

I spent many hours searching and experimenting before I opened the ticket.

I’ll revert my invironment back to the installed base, where I can run
Spyder 3.2.4.

**Comment by ccordoba12** [comment]
> I just now realize you closed the issue, without my verifying it’d been solved.

If installing `pyopengl` doesn't help you, then there's nothing else we can do for you, sorry. That's why I closed the issue.

This is not a problem in Spyder itself. It's a problem in the interaction between Qt and your operating system. My advice is for you to find out what package provides this library:

> ImportError: libEGL.so.1: cannot open shared object file: No such file or directory

or look at selecting a different OpenGL implementation in your system (e.g. a software implementation that uses mesa). However, I don't know how that's done in Redhat, sorry.
