### ISSUE TITLE
Anaconda won't launch Spyder

### ISSUE THREAD

**Issue by MahreenAthar** [spyder-ide/spyder#7375]
I click on spyder (i launch it from anaconda), it seems to launch but doesn't. Gives this error:
![capture](https://user-images.githubusercontent.com/39671939/42166118-78944324-7e23-11e8-9d53-f0b984ac1fd3.PNG)

**Comment by ccordoba12** [comment]
What's your Windows version?

**Comment by ccordoba12** [comment]
This looks like an installation problem. So my only advice for you is to uninstall and reinstall Anaconda again to see if it's fixed.

**Comment by MahreenAthar** [comment]
Thanks. It worked!
