### ISSUE TITLE
[BUG] Spyder debug-mode returns "*** NameError: name 'labels' is not defined" when existing list object 'labels' is used in a comprehension

### ISSUE THREAD

**Issue by jeremymatt** [spyder-ide/spyder#7386]
## Problem Description / Task Background
I have a function that I use to generate complex plots of different data sets with consistent formatting.  There are multiple lines on each plot, but I only want a subset of those lines included in the legend. To get rid of the unwanted labels, I start by grabbing the handles and labels with *get_legend_handles_labels()* from matplotlib.  Once I have the list of labels, I identify the index (the idx array) and use a comprehension build a list of the labels I want to keep.  The comprehension is as follows:
```python
la = [labels[index] for index in idx]
```

In debug mode, if I break on this line and then enter it into the iPython console I get the following error:
```
*** NameError: name 'labels' is not defined
```

**NOTES:**
1. This error **does not** appear if I run the code in standard run mode.  The plot (with the truncated legend) is generated as expected.
2. 'labels' **does** exist at this point in the code - if I type 'labels' into the console it returns the contents of labels.
3. This error does **does not** appear in debug mode if I do not place the plot code in a separate function.  That is, the break point is in the same file that I started debugging, instead of being in a function called by the file I'm debugging.

## What steps reproduce the problem?
To demonstrate this problem (in a highly simplified manner), I wrote three .py files:
1. *Spyder_Error_driver.py*: Loads and calls the *Spyder_Error_Demo.py* function.  The code is:
```python
import Spyder_Error_Demo as SED
labels_keep = SED.Spyder_Error_Demo()
print(labels_keep)
```
2. *Spyder_Error_Demo.py*: Makes a list, defines indices to keep, and uses a comprehension to extract the 'keep' labels.  The code is:
```python
import numpy as np
def Spyder_Error_Demo():
    labels = ['keep','other','keep2','other']
    idx = np.array([0,2])
    labels_keep = [labels[index] for index in idx]
    return labels_keep
```
3. *Spyder_Error_Demo_script.py*: Performs the same operations as the other two files, but without calling a function.  The code is:
```python
import numpy as np
labels = ['keep','other','keep2','other']
idx = np.array([0,2])
labels_keep = [labels[index] for index in idx]
print(labels_keep)
```

To show that the code works as intended, paste the code for the three files into .py files and save with the names provided above.  Then run:
1. *Spyder_Error_Demo.py*
2. *Spyder_Error_Demo_script.py*
3. Both will print: ```['keep', 'keep2']```

To reproduce the problem:
1. Place a breakpoint at line 5 of *Spyder_Error_Demo.py* 
2. Run *Spyder_Error_driver.py* in debug mode
3. Continue to the breakpoint on line 5
4. Type "labels" into the iPython console.  This will show the contents of 'labels'
5. Paste ```labels_keep = [labels[index] for index in idx]``` into the iPython console.  This results in an error: ```*** NameError: name 'labels' is not defined```.

To show that this only seems to appear when debugging a function:
1. Place a breakpoint at line 4 of *Spyder_Error_Demo_script.py*
2. Run *Spyder_Error_Demo_script.py* in debug mode
3. Continue to the breakpoint on line 4
4. Paste ```labels_keep = [labels[index] for index in idx]``` into the iPython console.  This does not result in an error and the 'labels_keep' variable is created as expected.

## Versions

* Anaconda: 1.8.7
* Spyder version: 3.2.8 
* Python version: 3.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/versions: Windows 10 & Windows 7 & Mint VM on Windows 10

### Dependencies 

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.3 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.5 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  2.0.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by jeremymatt** [comment]
@ccordoba12 Thanks for your work on Spyder - it's a great tool.  Apologies in advance if I'm not explaining clearly or if I'm using incorrect terminology (I'm new-ish to Python & Spyder).

I am aware of the multi-line limitation (and am looking forward to when it is overcome), but in this case I'm not convinced that it's the problem.  It seems like there's something else going on because comprehensions generally seem to work in ```ipdb```.  However, comprehensions do not work under the following specific conditions:
1.The break point is in a function called by the main script being debugged (IE myscript.py is being debugged; myscript.py calls ```myfunc()``` and the breakpoint is in ```myfunc()```); and 
2. An object not generated by the comprehension is in the 'output expression' portion of a comprehension.  

Although I suppose it's possible that comprehensions shouldn't work at all due to the multi-line limitiation.  However, in that case, the fact that they do work in some cases is in itself the bug.

Below is some testing I did to see if the problem is dependent on object type (I don't think that it is):

### In debug-mode console with the break in a function:
* no error: ```t = [x for x in labels]```; where labels is a list of strings
* **returns error**: ```t = [labels[x] for x in idx]```; where labels is a list of strings and idx is an array of integers
* **returns error**: ```t = [test[x] for x in range(1,3)]```; where test is a numpy array
* **returns error**: ```t = [test.loc[x] for x in range(1,3)]```; where ```test = pd.DataFrame({'test':test})```
* **returns error**: ```t = [test[x] for x in range(0,2)]```; where```test = {0: 'a', 1: 'b'}```
* **returns error**: ```t = [test for x in range(0,2)]```; where```test = {0: 'a', 1: 'b'}```

### In debug-mode console with the break in the main script:
* no error: ```t = [x for x in labels]```; where labels is a list of strings
* no error: ```t = [labels[x] for x in idx]```; where labels is a list of strings and idx is an array of integers
* no error: ```t = [test[x] for x in range(1,3)]```; where ```test=np.array([4,3,2,1])``` 
* no error: ```t = [test.loc[x] for x in range(1,3)]```; where ```test = pd.DataFrame({'test':test})```
* no error: ```t = [test[x] for x in range(0,2)]```; where```test = {0: 'a', 1: 'b'}```
* no error: ```t = [test for x in range(0,2)]```; where```test = {0: 'a', 1: 'b'}``` (it works, although why you would actually want to do this I'm not sure)


note that the 'error returned' is always: ```*** NameError: name '<object name>' is not defined```

**Comment by jeremymatt** [comment]
No worries, my fault for not explaining the problem more concisely.  Boiling a problem down to only the essential details is a skill I'm still working on - thanks for your patience.  

Regarding ```!```, I just tried that but it didn't seem to make a difference.  I get the same error when I break in the function, but the error does not show up when I break outside of a function.
**Breaking inside the function:**
```
      2 def Spyder_Error_Demo():
      3     labels = ['keep','other','keep2','other']
      4     idx = np.array([0,2])
24--> 5     labels_keep = [labels[index] for index in idx]
      6     return labels_keep


ipdb> 
ipdb> !labels_keep = [labels[index] for index in idx]
*** NameError: name 'labels' is not defined
```
**Breaking outside the function:**
```
      3 labels = ['keep','other','keep2','other']
      4 idx = np.array([0,2])
25--> 5 labels_keep = [labels[index] for index in idx]
      6 print(labels_keep)


ipdb> 
ipdb> !labels_keep = [labels[index] for index in idx]

ipdb> labels_keep
['keep', 'keep2']
```
###Side note:
I tried ```t = []``` and ```for x in idx: t.append(labels[x])``` as two separate 1-line inputs in ```ipdb``` and it worked fine in both the *break-inside-function* and the *break-outside-function* cases.  Not sure if that tidbit is of interest, but it might be because it is functionally the same as the ```t = [labels[x] for x in idx]``` comprehension.  It also might suggest that iterating/indexing into an object isn't the problem and that whatever is going on is more related to comprehensions specifically.
```
      2 def Spyder_Error_Demo():
      3     labels = ['keep','other','keep2','other']
      4     idx = np.array([0,2])
24--> 5     labels_keep = [labels[index] for index in idx]
      6     return labels_keep

ipdb> t = []

ipdb> for x in idx: t.append(labels[x])

ipdb> t
['keep', 'keep2']
```

**Comment by ccordoba12** [comment]
Thanks a lot for the reproducible example! This really looks like a bug, so we'll take a look and try to fix it in a future release.

**Comment by jeremymatt** [comment]
You're welcome, and I'm glad I was able to help out a little bit.  Thanks again for the hard work you and the rest of the team put in - it's very appreciated.

**Comment by bcolsen** [comment]
@jeremymatt  Thank you for the in-depth bug report! I know how much work that can be.

This an interesting issue and it seems to be related to this python bug https://bugs.python.org/issue21161 

This is solved by using the `interact` command at the pdb prompt:

![interact](https://user-images.githubusercontent.com/10513354/42362705-c023ed8a-80b1-11e8-9642-0db09c21a0ab.gif)

This seems like the official way to work with this type of problem, so I'm not sure if there is much to be done in Spyder. Unfortunately, there maybe bug in Spyder because I can't exit the pdb interactive mode without restarting the console, but I'll submit that separately.

There is also a work around where you can run `globals().update(locals())` in pdb before running `labels_keep = [labels[index] for index in idx]`. That will also work, by it might cause some strange things to happen in more complicated code.

**Comment by ccordoba12** [comment]
Thanks @bcolsen for helping us with this one! I didn't know the `interact` command, but it seems very handy.

**Comment by jeremymatt** [comment]
@bcolsen Thanks for the detailed response, that will be very helpful.  I apologize for the slow response, I was away from my computer for the weekend.  It is unfortunate that interact can't be exited out of though.

I tried reading the thread you linked, but I have to admit that it's a bit beyond my level of expertise.

This is just to satisfy my own curiosity: is the reason that the error does not occur when debugging a script because the variables in that script are treated as global (this seems odd to me)?  I did run a quick test, and if I define 'labels' as a global, the ```labels_keep=[labels[index] for index in idx]``` line does run correctly in the ```ipdb```.

**Comment by bcolsen** [comment]
@jeremymatt 

> It is unfortunate that interact can't be exited out of though.

The fix is on the way: https://github.com/jupyter/qtconsole/pull/290

 > This is just to satisfy my own curiosity: is the reason that the error does not occur when debugging a script because the variables in that script are treated as global (this seems odd to me)? 

Yes python scripts are almost highest level of execution second only to python's own built-ins. Everything, other than built-ins, that a python script uses is defined in the script either through imports or directly in the script it's self. 

Python's name space hierarchy looks like this:

>Local -> Enclosed -> Global -> Built-in,
>
>where the arrows should denote the direction of the namespace-hierarchy search order.
>
>   - Local can be inside a function or class method, for example.
>   - Enclosed can be its enclosing function, e.g., if a function is wrapped inside another function.
>   - Global refers to the uppermost level of the executing script itself, and
>   - Built-in are special names that Python reserves for itself.

quote from:
https://sebastianraschka.com/Articles/2014_python_scope_and_namespaces.html

To explain the original problem here, list comprehensions are functions in python3 with their own namespace. A list comprehension defined in the debugger is probably not being "enclosed" by the function so it can't see the function's local namespace. The `interact` command also just globals the locals to make the environment more script like.
