### ISSUE TITLE
Spyder window fix

### ISSUE THREAD

**Issue by sneh24487** [spyder-ide/spyder#7391]
## Problem Description:

Spyder window scaling doesn't work as expected and control tabs are missing from top. However, this issue can be addressed by pressing 
![spyder_scaletofullscreenbutmissingothertabs](https://user-images.githubusercontent.com/32103928/42352572-30b2e3cc-8070-11e8-9c23-907f8d7275f5.PNG)
![to_fix_spyder_scaling](https://user-images.githubusercontent.com/32103928/42352574-30cd0ee6-8070-11e8-9ffc-b10f3cf0f299.PNG)

. And if apply full screen then it will cover enter
![latestver_spyder_no_controlbar](https://user-images.githubusercontent.com/32103928/42352487-a426b8f2-806f-11e8-90d5-4b6259a1bf0a.PNG)

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
I think to fix this problem you need to close the *Help* pane. Please do that and report back.

**Comment by sneh24487** [comment]
Thank you for resolving this.


It's working as expected.


________________________________

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.
