### ISSUE TITLE
v3.3.0: Ipython console does not start

### ISSUE THREAD

**Issue by simonkm1** [spyder-ide/spyder#7393]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
An error ocurred while starting the kernel
Your Python environment or installation doesn't have the spyder‑kernels module installed on it. Without this module is not possible for Spyder to create a console for you.

### What steps reproduce the problem?

1. Installed in Python3.6 environment
2. Start spyder3 from the Scripts
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version: win7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by danieltomasz** [comment]
Did you try to install from pip spyder-kernels?

**Comment by ccordoba12** [comment]
Conda packages are still not available, so you have to use `pip` for now, following @danieltomasz's advice.
