### ISSUE TITLE
Spyder 3.30 pip installed  wrong spyder-kernels requirement (<1.0 is required)

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#7395]
### Issue Report Checklist

[x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
 [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
 [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
[x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
 [x] Tried basic troubleshooting (if a bug/error)
     [x] Restarted Spyder
     [x] Reset preferences with ``spyder --reset``
     [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
     [x] Tried the other applicable steps from the Troubleshooting Guide
 [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder does not start

Steps to reproduce
_* updating spyder: pip3 install -U spyder
* installing spyder kernels: pip3 install spyder-kernels
output
Spyder not starting
```
Output:

RuntimeError: Please check Spyder installation requirements:
spyder-kernels < 1.0 is required (found 1.0.1).
```

```

* Spyder version: 3.30
* Python version: 3.6.5
* Qt version: 
* PyQt version: 
* Operating System name/version: Ubuntu 18.04

**Comment by danieltomasz** [comment]
When I install spyder-kernels 0.2.3  I am getting the same error like in this issue https://github.com/spyder-ide/spyder/issues/7393

**Comment by ccordoba12** [comment]
Yes, that's right. If you install Spyder with

    pip install -U spyder

the right version of spyder-kernels will be pulled.

**Comment by mleroy003** [comment]
Under Anaconda, avoid to use pip to manage a package that is part of the distribution, it may broke something. Instead, use conda :
conda update spyder

**Comment by LattyMoore** [comment]
I had exactly the same problem, but I did update via conda. 'conda update --all' installs the wrong version of spyder-kernels. That was a week or so ago and I just rolled back the whole upgrade. It's still pulling down the wrong version today, so I signed up to report this.  'conda update spyder' is a tidier fix.

**Comment by matthewfieger** [comment]
Spyder also stopped starting for me after running 'conda update --all'.  It was returning 'spyder-kernels < 1.0 is required (found 1.0.1)'.  Running 'conda update spyder' fixed the problem.

**Comment by dphaas** [comment]
Problem still exists with 'conda update --all'. Running 'conda update spyder' fixed the problem.
       conda version : 4.6.3
 conda-build version : not installed
      python version : 3.7.2.final.0

**Comment by GuoshengCui** [comment]
how to install spyder-kernels 0.2.4? My spyder-kernels version is 1.3.2.

**Comment by ccordoba12** [comment]
conda install spyder-kernels=0.*

or

    pip install spyder-kernels==0.*

depending on how you installed Spyder.

**Comment by chandu8542** [comment]
I installed spyder 4.1.2 using pip and spyder kernel is 1.9.0. But still it says error starting the kernel. I tried to uninstall kernel and then re-install using pip but error persists.

Python 3.8.2 64-bit | Qt 5.12.8 | PyQt5 5.12.3 | Linux 4.15.0-96-generic

**Comment by m4r35n357** [comment]
$ pip install spyder‑kernels==0.*
ERROR: Invalid requirement: 'spyder‑kernels==0.*'

**Comment by SamuelMarks** [comment]
Trial and error showed it has an underscore now, the help text needs to be updated:
```sh
$ pip install spyder_kernels
```
