### ISSUE TITLE
spyder-kernel

### ISSUE THREAD

**Issue by josephsacco** [spyder-ide/spyder#7399]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by josephsacco** [comment]
Is PyQT5 < 5.10 still correct?  Spyder-3.3.0 seems to work OK with PyQt5 == 5.11.2.

At issue is QScintilla

QScintilla==2.10.7
  - PyQt5 [required: >=5.10.1, installed: 5.11.2]
    - PyQt5-sip [required: >=4.19.11,<4.20, installed: 4.19.11]

Thoughts?

-Joseph

**Comment by ccordoba12** [comment]
Sorry, we haven't tested with the latest PyQt5. So for now, yes, PyQt5 < 5.10 is still required.

**Comment by josephsacco** [comment]
Carlos,

Thank you for responding.  

Some observations...

- On my iMac running OSX10.13.5,  the current install of the Anaconda suite contains a version of Spyder-3.2.8 that uses PyQt-5.10.1

- The requirements.txt file in the spyder source tree has no constraint on pyqt5

- The spyder installation documentation [https://pythonhosted.org/spyder/installation.html] sets only a lower bound requirement on the version of PyQt5, PyQt5 >=5.2

-Joseph
