### ISSUE TITLE
Spyder silently fails to open, if dependencies (pyqt and qt) are not met. 

### ISSUE THREAD

**Issue by metterklume** [spyder-ide/spyder#7402]
I ran into an unusual problem where Spyder refused to open with no errors. After a lot of searching, I figured out that the popular nlp packages `textblob` and `spacy` downgrade the versions of pyqt and qt to 5.6. 

This pathology is not spyder's fault. **But** a lot of users would benefit if spyder gave an error message on the terminal saying dependencies were not met etc. instead of failing silently. 

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder fails to open. There are no error messages on the terminal.

### What steps reproduce the problem?

1. Install one of the following packages: `textblob`, `spacy` (maybe others)
2. When prompted to confirm *downgrade*, say yes.
    The following packages will be DOWNGRADED:  
        pyqt:            5.9.2-py36h1aa27d4_0             --> 5.6.0-py36_2
        qt:              5.9.4-vc14hd9fb3db_0             --> 5.6.2-vc14_1     conda-forge [vc14]
3. spyder will not open. nothing is printed on the terminal.

### What is the expected output? What do you see instead?

spyder fails silently. Instead there should be a dependency check and an error message informing the user that pyqt and qt need to be upgraded.

Simple fix:  `conda install pyqt`

## Versions

* Spyder version: 
* Python version: 3.6.5
* Qt version: 5.9.4 
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64 bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> I ran into an unusual problem where Spyder refused to open with no errors.

The real problem is you're mixing packages from conda-forge with default packages from Anaconda, and that's something you need to really avoid.

For that you need to create a new conda env and install everything (including Spyder) from conda-forge. Then you'll see no problems with Spyder.

**Comment by metterklume** [comment]
I am sure you are right, but note that even the front page of conda-forge tells you to add the channel into an existing Anaconda environment. Hence many users mix packages because they don't know better.

Regardless, wouldn't it be better if spyder had more verbose output into the terminal?

(Thanks for all your work. Spyder is the the best!)
