### ISSUE TITLE
Don't ask again ineffective in Console delete all variables dialog 

### ISSUE THREAD

**Issue by wtheis** [spyder-ide/spyder#7404]
### What steps will reproduce the problem?

1. click the eraser icon in the ipython console
2. confirm don't ask again, 
3. click OK,
4. click eraser again -> confirmation dialog opens again 

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4-1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.2 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0     :  5.3.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. I can confirm this bug and we'll try to fix in our next release.
