### ISSUE TITLE
pydoc -p5000 renders a link, but clicking it opens a terminal in default browser having standard user permissions and current login, but none of the xterm features

### ISSUE THREAD

**Issue by rebelclause** [spyder-ide/spyder#7405]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [no, not using conda, Ubuntu bionic dist with pip3 --user module installations ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ can't see or find this console ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x - mostly though, it is on my technology learning curve horizon ] Tried basic troubleshooting (if a bug/error)
    * [ check ] Restarted Spyder
    * [ no ] Reset preferences with ``spyder --reset``
    * [no ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ no] Tried the other applicable steps from the Troubleshooting Guide
* [ yes ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Terminal session pops up when calling pydocs with port from the Spyder3 terminal plugin.
Also, terminal sometimes defaults to xterm color scheme, but infrequently, mostly presenting the terminal with stark white text on black background.
The integrated pydocs is fantastic, btw.

### What steps reproduce the problem?

1. run pydoc -p5000 at the prompt in Spyder3 terminal.
2. using only the left mouse button, click the supplied link to localhost
3. the link should open in the default browser to the URL: http://127.0.0.1:8071/?path=/home/user/current_project_folder

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.6
* Python version: 3.6.5
* Qt version: latest
* PyQt version: latest
* Operating System name/version: Ubuntu Bionic 18.04 

### Dependencies

```
PASTE DEPENDENCIES HERE
IPython >=4.0    :  5.5.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.5 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
psutil >=0.3     :  5.4.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
> run pydoc -p5000 at the prompt in Spyder3 terminal.

By Spyder3 terminal you mean our [spyder-terminal](https://github.com/spyder-ide/spyder-terminal) plugin?

> the link should open in the default browser to the URL

So what's the problem exactly? Where the URL is opened then?

**Comment by rebelclause** [comment]
Yes. The active link tells you one thing, but the spyder-terminal plugin launches itself into a browser tab instead of the tab opening to the url of the pydoc-served document. 

The link you provided and that you felt compelled to seek clarification.... Have I opened this issue in the wrong thread?

**Comment by ccordoba12** [comment]
> Have I opened this issue in the wrong thread?

The wrong repo. Moving this to the right one.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-terminal #145](https://github.com/spyder-ide/spyder-terminal/issues/145) via [**ZenHub**](https://www.zenhub.com/)
