### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by asad2002m** [spyder-ide/spyder#7415]
### What steps will reproduce the problem?

Cannot uninstall 'spyder'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall. I got this error during updating Spyder for my environment using pip 

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.28.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
> Cannot uninstall 'spyder'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall

Spyder has wheels for Python 2 and 3, so unless you did

    python setup.py install

after decompressing our tarballs, then you shouldn't see that error. By doing

    pip install -U spyder

there shouldn't be any problem.

The other error you mention

> plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

is fixed already in Spyder 3.3
