### ISSUE TITLE
Opening is slow (Boot)

### ISSUE THREAD

**Issue by Krprashant94** [spyder-ide/spyder#7416]
## Opening is slow (Boot)

Spyder is slow during open. If I close the app and open it again then it takes comparatively (with notpad++ and Sublime text) more time. 
Why you not optimizing this. You can do one thing "Open the editor first after; do all other tasks in the thread. So Booting the editor can take less time" 
Most of the time I do not compile the program instantly. But I require an instant opening of a file.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.2
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
numpy >=1.7      :  1.14.5 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
This error is fixed in our latest version (3.3.0). Conda packages for it should available next week.

In the meantime, please close Spyder, open the Anaconda Prompt and run there

    spyder --reset
