### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by kattoor1984** [spyder-ide/spyder#7419]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Once I install Anaconda latest version, opened spyder first time, the entire screen is blank, but right click is working, and if I mouse hover on the menu location, I can see the menu options. Otherwise it is completely blank screen

**Comment by ccordoba12** [comment]
Please open a system terminal and run the

    conda install pyopengl

to fix this.
