### ISSUE TITLE
spyder 3.3.0 crash when running program

### ISSUE THREAD

**Issue by wyfoffice** [spyder-ide/spyder#7420]
the latest spyder is easy to fail down when I import libraries.

here is the example that I failed to import :
from cmfrec import CMF
which is fine in commend.

now raise an error:
ImportError: cannot import name 'CMF'

while the jupyter notebook and commend can run this line

**Comment by ccordoba12** [comment]
This is an installation problem and not an issue with Spyder.

You need to be sure that the Python interpreter where you installed that library is the same one used by Spyder.

You can check that by going to

   Preferences > Python interpreter
