### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by henrymartin1** [spyder-ide/spyder#7429]
The problem occurs every time I start Spyder and started after I deleted and reinstalled Anaconda python (64bit).  Spyder then works as intended. 
[conda_list.txt](https://github.com/spyder-ide/spyder/files/2185091/conda_list.txt)

[pip_freeze.txt](https://github.com/spyder-ide/spyder/files/2185097/pip_freeze.txt)

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.3 (OK)
numpy >=1.7      :  1.14.5 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
This problem is fixed in our latest release (Spyder 3.3). New conda packages for it should be available this week.
