### ISSUE TITLE
screen is black when I launch spyder from anaconda navigator. I can see the panel but everything else is black

### ISSUE THREAD

**Issue by SapnaSM** [spyder-ide/spyder#7433]
## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Linux 4.13.0-39-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
psutil >=0.3     :  5.4.5 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
This error is fixed by closing Spyder, opening a system terminal (xterm, konsole, etc), running there

    conda install pyopengl

and starting Spyder again.

**Comment by d-shiri** [comment]
That command didn't solve the problem

**Comment by ccordoba12** [comment]
Please update Spyder, this should be fixed in our latest version.
