### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by FaWa70** [spyder-ide/spyder#7435]
### What steps will reproduce the problem?
Launching Spyder from outside Anaconda Navigator (Win10) raises this error:
"  plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'  "

Launching Spyder from Anaconda Navigator works without error. 

All this appeared after a tempted update to spyder 3.3. using conda (Which did not work as matplotlib did no longer see that pillow is installed)
Thereafter I did 'conda update conda' (nothing to do) and 'conda update anconda' (lots of packages updated). Now version 2.8 of Spyder is back and works, but with this error at startup.

**Comment by ccordoba12** [comment]
> All this appeared after a tempted update to spyder 3.3. using conda

Conda packages for 3.3 are still not available, so either you installed it with pip or did something else. In any case, this error is already fixed in 3.3.
