### ISSUE TITLE
Miss clicking and window overlap on Spyder

### ISSUE THREAD

**Issue by hughgaffney1** [spyder-ide/spyder#7460]
Whenever I open and use Spyder the mouse will click the line above where it was positioned. The window also overlaps slightly which may be related. Not sure if it is a scaling issue with my laptop screen and if it is I'm not sure how to fix it. 

![spyder missclick error](https://user-images.githubusercontent.com/40799405/42736288-37fb6810-8832-11e8-8ab4-b47afeb6f12a.png)
My cursor is where it says run file and as you can see it is interpreting it as if I am hovering over the run file icon above.

**Comment by ccordoba12** [comment]
This problem should be fixed by closing the Help pane.

**Comment by ccordoba12** [comment]
Please let us know if that's the case.

**Comment by CAM-Gerlach** [comment]
Indeed, appears to be an exact duplicate of #7391, and possibly also the same essential issue as that discussed in much more detail in #7197

**Comment by hughgaffney1** [comment]
Yes, I had read through #7197 and wasn't able to fix it but the fix from #7391 took care of it. Closing help didn't seem to make a difference but switching the full screen on and off fixed everything. Thanks.
