### ISSUE TITLE
"switch to console" keyboard shortcut doesn't do anything

### ISSUE THREAD

**Issue by mind6** [spyder-ide/spyder#7465]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

"switch to console" keyboard shortcut doesn't do anything.

### What steps reproduce the problem?

0. have one ipython console and one editor window open
1. put mouse cursor in editor window
2. press ctrl+shift+c

### What is the expected output? What do you see instead?

nothing happens. Spyder does receive the ctrl+shift+c input on my computer, because I can set other commands to this combo and they work fine. 

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5 64-bit
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

```

**Comment by bcolsen** [comment]
I can confirm this ctrl+shift+c seem to do nothing since the spyder python console is now removed.

@mind6 The console you want to get to is the IPython console currently so use ctrl+shift+i or you can change this to ctrl+shift+c in the preferences if you like.

To fix this I would suggest removing this python console shortcut and potentially change the IPython shortcut to ctrl+shift+c as this might be more intuitive.

**Comment by ccordoba12** [comment]
> To fix this I would suggest removing this python console shortcut

Done in PR #7471.

> potentially change the IPython shortcut to ctrl+shift+c as this might be more intuitive.

We can discuss this for Spyder 4 but I'd prefer to leave it as it is for our 3 series.

**Comment by mind6** [comment]
Thanks for your quick solutions. I should have looked for the "switch to ipython console" command before I posted.
