### ISSUE TITLE
Kernel Connection Problem

### ISSUE THREAD

**Issue by LeandroPD** [spyder-ide/spyder#7469]
## Problem Description

The simply wont connect when starting spyder. I already tried to restart the computer. I already tried to ''spyder --reset'' at the prompt. But kernel will still not connect.

### What steps will reproduce the problem?

When lauching spyder from anaconda. Spyder starts but kernel doesnt connect.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
```

**Comment by ccordoba12** [comment]
This problem is usually related to your firewall/antivirus. Please deactivate or uninstall them and try again. If that doesn't work, I'm afraid we can't help you further because this is really not a problem in Spyder.
