### ISSUE TITLE
Matplotlib canvas in QMainWindow changes size when moving the mouse

### ISSUE THREAD

**Issue by FaWa70** [spyder-ide/spyder#7472]
## Problem Description
I have a QT application (QMainWindow) with a matplotlib canvas and the associated toolbar. If launch this from Spyder, the matplotlib canvas changes size when decreasing the window width. When displaying an image in the canvas, the canvas size will change when moving the mouse in the image. (Kind of trembling display that makes a precise selection of points in the image impossible.)
Remarks: 
- Excecution from outside spyder does not show this problem
- I made an Anaconda uninstall and reinstall, but it did not save the problem
- It's strange but not very urgent as I can run the program without problems from outside spyder
By the way, thank you very much for all the work you do for Spyder. 

### What steps will reproduce the problem?
1) execute [this file](https://github.com/FaWa70/LIC-image-analyser/blob/master/superpose_ex_situ_images_v30.py) 
from Spyder
2) push 'load file' on the upper left of the frist tab and load for example 
[this file](https://github.com/FaWa70/LIC-image-analyser/blob/master/Laser%20pos04%202018%20355%20front.tiff)
3) Decrease the width of the window
4) move the mouse pointer over the displayed image

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by goanpeca** [comment]
@FaWa70 Cannot access the `execute this file` file. Do you have it around still?

**Comment by FaWa70** [comment]
Hello, thanks for looking into this, but somehow the problem was solved. I just tested again the behaviour with the present Anaconda install and the new version of the file that was deleted from guthub, and now the canvas stays stable even when the numbers in the toolbar change beacause of moving the mouse. I will try to close the comment.

**Comment by FaWa70** [comment]
As said, the problem was solved by one of the updates between july 2018 and now, november 2019. Thanks
