### ISSUE TITLE
2nd Environment - no applications working

### ISSUE THREAD

**Issue by bobbiejim01** [spyder-ide/spyder#7474]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm currently running Anaconda with Python 3.6. This all works fine. When I add a new environment with Python 3.5.2, I cannot get any of the applications to launch in the new environment. I get the eThe base environment continues to work. 

### What steps reproduce the problem?

1. Add new environment using 'conda create --name myenv python=3.5.2
2. Install Spyder. 
3. Launch Spyder

### What is the expected output? What do you see instead?
Instead of launching Spyder, I revieve this error: 'Fatal Python Error: PyThreadState_Get: no current thread'. I get the same error if I try to reset Spyder.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3?
* Python version: 3.5.2
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by bobbiejim01** [comment]
I've been sent a section of code and it's throwing up all kinds of errors. I'm working through these issues, but I wondered whether the easiest thing to do would be too run it in the older version of python they are using.

**Comment by ccordoba12** [comment]
Well, the error you mentioned above is not related to Spyder, so my advice is for you to open this bug in Anaconda:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by cehceh** [comment]
Hi All,
The problem description , steps that reproduce the problem and the error message are the same in my case .... When i try to open spyder to a new environment the error occurs 'Fatal Python Error: PyThreadState_Get: no current thread'
Thanks
