### ISSUE TITLE
Spyder variable explorer import data does nothing upon trying to load a .spydata file

### ISSUE THREAD

**Issue by TinyCloud** [spyder-ide/spyder#7483]
## Problem Description
Whenever I've saved a session's data as a .spydata file and tried to import it at a later point in time, the behavior is highly erratic - works sometimes and does not do anything sometimes.

### What steps will reproduce the problem?
- Export a copy of the session dataframes and variables by Save as from Variable explorer . Ex: test.spydata in your working directory.
- Use import from variable explorer to open the same file. Does not always work.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 2.7.15
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 17.6.0

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
Moving to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-kernels #9](https://github.com/spyder-ide/spyder-kernels/issues/9) via [**ZenHub**](https://www.zenhub.com/)
