### ISSUE TITLE
NameError : name 'runfile' is not defined in Spyder 

### ISSUE THREAD

**Issue by jaabili** [spyder-ide/spyder#7485]
How do I define the runfile in Python path manager in Spyder(Anaconda3)  to execute the code.
![err](https://user-images.githubusercontent.com/13446217/42832281-5fe8684a-8a0e-11e8-80ad-2d9096a11c7a.PNG)

**Comment by ccordoba12** [comment]
Did you change your Python interpreter in

    Tools > Preferences > Python interpreter

?

**Comment by jaabili** [comment]
Thank You sir ! It's working fine now.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know about it.
