### ISSUE TITLE
How to plot image in ipdb mode

### ISSUE THREAD

**Issue by ymcasky** [spyder-ide/spyder#7487]
How can I plot image in debug mode?

Here is my sample code:

```
[x,y] = np.meshgrid(np.linspace(-wDeg/2,wDeg/2,nPix),np.linspace(-wDeg/2,wDeg/2,nPix))
plt.imshow(x)
plt.show()
plt.pause(1)
```
The image show like this...
https://ppt.cc/fqNoox

Pycharm can show correctly but I like spyder more!

**Comment by bcolsen** [comment]
I can get the plot to work fine, but it doesn't update until you step past `plt.pause(1)`.  You shouldn't need the `plt.show`.

Unfortunately, the plots are only interactive (zooming and panning) for the duration of the pause.

This is my special ipdb ploting line `plt.figure();plt.imshow(x);plt.pause(1)`

**Comment by ccordoba12** [comment]
You need to precede your plot command with the `%plot` magic, like this

     ipdb> %plot plt.plot(range(10))

However, this only works when the Matplotlib Inline backend is active (it doesn't work with other backends). So be sure of activating it in

    Tools > Preferences > IPython console > Graphics > Backend

**Comment by angeloyeo** [comment]
@ccordoba12 Hello. When I try to use %plot magic function my console is throwing an error saying

"*** IPython.core.error.UsageError: Line magic function `%plot` not found"

I'm using Spyder verision 4 and Python 3.7. I definitely set the Matplotlib Inline backend active. Any tips please?
