### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by JiafG** [spyder-ide/spyder#7490]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
can't open files when I drag them in to the window of SPYDER,
it juste gives me the path of them

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update spyder

or

    pip install -U spyder
