### ISSUE TITLE
Works in iPython, not Spyder: script that loops over several plots and awaits user input for each

### ISSUE THREAD

**Issue by kevinUCeqEng** [spyder-ide/spyder#7491]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I wrote a script whose purpose is to loop through multiple datasets, plotting each one using Matplotlib, waiting for the user to adjust x limits (if desired) and hit the space bar, and then to store the new x-limits by querying the figure object before closing it. Each subsequent figure is displayed only after the user has hit the space bar to complete the previous one. Here's the minimal reproducible code (it just loops twice and plots a straight line on each).

```
import matplotlib.pyplot as plt

def getXlimsFromUser():
    """
    Given something to plot, plot it and wait for user
    to rescale the axes (if desired) and then hit the space bar. Resulting
    new limits will be returned.
    
    There must be an already open plot window called "f" in the calling env.
    """
    
    # Variables to store xlims captured in event handler function.
    # Because python 2.x doesn't support "nonlocal" keyword, must
    # make these mutable - so, a list:
    xLims = []
    
    # event handler function - nested
    def spaceBarDone(event):
        """
        When space bar is pressed, get x limits from plot and use them to define
        crop window for the record.
        """
        if event.key!=" ": return
        
        # get xlim (matplotlib)
        xlims = event.canvas.figure.get_axes()[0].get_xlim()
        xLims.append(xlims)
        
        # close window
        plt.close()
    
    # Connect the event handler:
    cid = f.canvas.mpl_connect('key_press_event',spaceBarDone)
    
    # Keep window shown in interactive mode so they only pop up one at a time.
    plt.show(block=True)
    print xLims
    return xLims

if __name__=='__main__':
    for i in range(2):
        f = plt.figure()
        plt.plot([0,10],[-1,1])
        newLims = getXlimsFromUser()
```

The problem is described below:

### What steps reproduce the problem?

  * Using Spyder 3.3 installed in a Anaconda (Python 2.7) environment with Tkinter backend.
  * If I set the run preferences in Spyder to use a dedicated external (system) console, the code runs as I expect.
  * If I run it from Python or iPython in a system terminal, it works fine too.
  * If I run it from qtconsole, per the troubleshooting instructions, it seems to run but does not display graphics windows and instead just shows `<Figure size 640x480 with 1 Axes>` twice in succession.
  * If I run it from Spyder via the iPython REPL (existing or dedicated new instance), the script displays the first plot as expected. However as soon as user hits the space bar, the first figure closes and Spyder's iPython (qtconsole?) seems to hang indefinitely. The `print xLims` statement is never executed so presumably the callback function hangs before it gets there. The second plot does not appear as expected. If I hit ctrl-C and/or the "stop" button on the Spyder terminal, I get a traceback.

### What is the expected output? What do you see instead?

See below.

### Paste Traceback/Error Below (if applicable)

Here is the traceback:

```python-traceback

runfile('/home/kmf76/PwaveMethod/py/zoomPlotClick_so.py', wdir='/home/kmf76/PwaveMethod/py')
Traceback (most recent call last):

  File "<ipython-input-1-7db8010bb457>", line 1, in <module>
    runfile('/home/kmf76/PwaveMethod/py/zoomPlotClick_so.py', wdir='/home/kmf76/PwaveMethod/py')

  File "/home/kmf76/anaconda2/envs/Pwave/lib/python2.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "/home/kmf76/anaconda2/envs/Pwave/lib/python2.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 98, in execfile
    builtins.execfile(filename, *where)

  File "/home/kmf76/PwaveMethod/py/zoomPlotClick_so.py", line 45, in <module>
    newLims = getXlimsFromUser()

  File "/home/kmf76/PwaveMethod/py/zoomPlotClick_so.py", line 36, in getXlimsFromUser
    plt.show(block=True)

  File "/home/kmf76/anaconda2/envs/Pwave/lib/python2.7/site-packages/matplotlib/pyplot.py", line 253, in show
    return _show(*args, **kw)

  File "/home/kmf76/anaconda2/envs/Pwave/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 208, in show
    cls.mainloop()

  File "/home/kmf76/anaconda2/envs/Pwave/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1073, in mainloop
    Tk.mainloop()

  File "/home/kmf76/anaconda2/envs/Pwave/lib/python2.7/lib-tk/Tkinter.py", line 419, in mainloop
    _default_root.tk.mainloop(n)

KeyboardInterrupt

```

## Versions

* Spyder version:  3.3.0
* Python version: 2.7.14
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Linux Mint 18.1 Serena (Cinnamon)

### Dependencies

```
IPython >=4.0;<6.0:  5.7.0 (OK)
cython >=0.21     :  0.28.2 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
I found the error: since you're using `plt.show(block=True)` you *can't* activate the graphics support in Spyder because that support is non-blocking.

So you need to go first to

    Preferences > IPython Console > Graphics

and deactivate the option called `Activate support`.

Then you need to create a new console, and finally change your code to this:

```python
import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt

def getXlimsFromUser():
    """
    Given something to plot, plot it and wait for user
    to rescale the axes (if desired) and then hit the space bar. Resulting
    new limits will be returned.
    
    There must be an already open plot window called "f" in the calling env.
    """
    
    # Variables to store xlims captured in event handler function.
    # Because python 2.x doesn't support "nonlocal" keyword, must
    # make these mutable - so, a list:
    xLims = []
    
    # event handler function - nested
    def spaceBarDone(event):
        """
        When space bar is pressed, get x limits from plot and use them to define
        crop window for the record.
        """
        if event.key!=" ": return
        
        # get xlim (matplotlib)
        xlims = event.canvas.figure.get_axes()[0].get_xlim()
        xLims.append(xlims)
        
        # close window
        plt.close()
    
    # Connect the event handler:
    cid = f.canvas.mpl_connect('key_press_event',spaceBarDone)
    
    # Keep window shown in interactive mode so they only pop up one at a time.
    plt.show(block=True)
    print(xLims)
    return xLims

if __name__=='__main__':
    for i in range(2):
        f = plt.figure()
        plt.plot([0,10],[-1,1])
        newLims = getXlimsFromUser()
```

The main change is at the top, where I set the Matplotlib backend with code.

**Comment by kevinrse** [comment]
Thank you!
