### ISSUE TITLE
Crash after looking a word with ortographical accent

### ISSUE THREAD

**Issue by edbriales** [spyder-ide/spyder#7494]
## Description

**What steps will reproduce the problem?**

1.  Ctrl + F to find a word
2.  Write a word with ortographical accent ("Cámara")
3.  When writing the "m" letter it crashes

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\Users\Eduardo\Anaconda2\lib\site-packages\spyder\widgets\findreplace.py", line 365, in text_has_been_edited
    self.find(changed=True, forward=True, start_highlight_timer=True)
  File "C:\Users\Eduardo\Anaconda2\lib\site-packages\spyder\widgets\findreplace.py", line 413, in find
    words=words, regexp=regexp)
  File "C:\Users\Eduardo\Anaconda2\lib\site-packages\spyder\widgets\mixins.py", line 497, in find_text
    pattern = QRegularExpression(r"\b{}\b".format(text) if words else
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 2: ordinal not in range(128)

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.0). Please update by opening the Anaconda Prompt and running there

    conda update spyder

If an update to that version is not available yet, please be patient, it should be shortly.
