### ISSUE TITLE
Error when trying to save file called untitled0.py

### ISSUE THREAD

**Issue by ingdemurtas** [spyder-ide/spyder#7498]
Following installation of Anaconda, the first file I open is named untitled0.py (it was created with another editor). I press run (the green arrow), Spyder ask me to save the file. I navigate to the folder and choose to overwrite the original file. I get this error message.
I think the problem is that Spyder is assuming that the file isn't saved, because of its name. But the file was actually saved already!

**Comment by ccordoba12** [comment]
We were unable to reproduce this issue, sorry.
