### ISSUE TITLE
"Toggle comment" should work line-by-line

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#7509]
"Toggle comment" ought to **comment** all selected _uncommented_ lines, and **uncomment** all selected _commented_ lines.

Currently it seems to work based on the commented status of the first line selected. It ought to process each line separately, to do a true "toggle".

Now, if you "Toggle comment" this code:

```
tubeID = PCBDiameter+2*Fit
tubeOD = tubeID + 2*Thickness
#tube = ring(tubeOD, tubeID, TubeLen)
```

You get:

```
#tubeID = PCBDiameter+2*Fit
#tubeOD = tubeID + 2*Thickness
##tube = ring(tubeOD, tubeID, TubeLen)
```

But you ought to get:

```
#tubeID = PCBDiameter+2*Fit
#tubeOD = tubeID + 2*Thickness
tube = ring(tubeOD, tubeID, TubeLen)
```

**Comment by ccordoba12** [comment]
> "Toggle comment" ought to comment all selected uncommented lines, and uncomment all selected commented lines.

Thanks for the suggestion but that would be a nightmare to implement correctly and satisfy all users at the same time, so we're not going to do it.
