### ISSUE TITLE
Tab key ought to advance cursor to next field (Search/Replace dialog)

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#7510]
In Spyder's Search/Replace dialog (Search>Replace text), the Tab key ought to advance the cursor from the search box to the replace box.

(And, probably, more generally in other Spyder dialogs.)

Right now the only way I know to move from typing into the search box to the replace box is with the mouse. This is slow - most programs allow Tab for this (at least in the Windows world).

(If Spyder had a "refactor" function [variable renaming], this wouldn't be so important.)

**Comment by ccordoba12** [comment]
Already implemented. Please update your Spyder version.
