### ISSUE TITLE
Creating a new project makes the path with mixed slashes

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#7518]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Happens when you select a different `Location`
![imagen](https://user-images.githubusercontent.com/16781833/43031092-7e5cd136-8c60-11e8-9312-7b13192ba9f0.png)

### What steps reproduce the problem?

1. Select a different `Location` from the project creation dialog
2. Type a name for the project

### What is the expected output? What do you see instead?

A proper path and not mixed slashes

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt version: 5
* Operating System name/version: Windows

### Dependencies

IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.1 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
sympy >=0.7.3    :  None (NOK)

**Comment by vitoriahmc** [comment]
Can I work on this one?

**Comment by ccordoba12** [comment]
Sure, please go ahead @vitoriahmc! It shouldn't be that hard to solve.

**Comment by jitseniesen** [comment]
@vitoriahmc Do ask if you could use some help
