### ISSUE TITLE
Spyder IDE, Pandas Data Frame not loading file [>60 MB], giving Error: File does not exist.

### ISSUE THREAD

**Issue by shiva-narayana** [spyder-ide/spyder#7524]
Spyder IDE, Pandas Data Frame not loading file [>60 MB], giving Error: File does not exist. 
Can somebody help me:
 File "pandas/_libs/parsers.pyx", line 718, in pandas._libs.parsers.TextReader._setup_parser_source FileNotFoundError: File b'E:\DS_2\DS_Kaggle\Competitions\DS_Kaggle_HomeCreditDefaultRisk\x07pplication_train.csv' does not exist. 
But, other small files are being loaded using Pandas Data Frame. 
Is it because of my LapTop Low Configuration Problem [Lenovo: Intel i5-6200U, 2.3 GHz, 12 GB Ram] OR Spyder Ide. 
Thanks.

**Comment by ccordoba12** [comment]
You have to write your path as

    'E:\\DS_2\\DS_Kaggle\\Competitions\\DS_Kaggle_HomeCreditDefaultRisk\\application_train.csv'

or

    'E:/DS_2/DS_Kaggle/Competitions/DS_Kaggle_HomeCreditDefaultRisk/application_train.csv'
