### ISSUE TITLE
Code Autocompletion not working in Editor

### ISSUE THREAD

**Issue by masoodimran** [spyder-ide/spyder#7533]
### What steps will reproduce the problem?

After typing the object instance, if you hit tab, nothing is shown.

While it works in the IPython console, it is not working in the Editor after upgrade to Spyder 3.3.

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.6
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
numpy >=1.7       :  1.12.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
Please open an Anaconda Prompt and run there

    conda install parso=0.2*

That should fix the error.
