### ISSUE TITLE
spyder does not open (not giving any error)

### ISSUE THREAD

**Issue by Ashish0091** [spyder-ide/spyder#7535]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
problem: I have created a python virtual env and typed spyder. when i hit enter it does not open and do'nt even show any error.

previously it was working fine. I have tried these things 1.updating conda and spyder (nothing happens) 2. I am able to open it outside of virtual env
![spydererror](https://user-images.githubusercontent.com/24604443/43074152-244cde48-8e31-11e8-9332-020c235d5dba.png)

**Comment by ccordoba12** [comment]
This was solved in StackOverflow.

For next time, please don't open an issue here and a question in StackOverflow. Choose one of them and be patient (at least a couple of days) before opening an issue/question in the other website.
