### ISSUE TITLE
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS' on launch

### ISSUE THREAD

**Issue by Neil-Bennett** [spyder-ide/spyder#7545]
## Description

**What steps will reproduce the problem?**

1. Launch Spyder - pop up window display the information below

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

Error message first seen after updating Spyder through Anaconda navigator

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.6
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
numpy >=1.7      :  1.11.3 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.0). Please update by opening the Anaconda Prompt and running there

    conda update spyder
