### ISSUE TITLE
kernel no connect

### ISSUE THREAD

**Issue by jjpantano** [spyder-ide/spyder#7547]
### What steps will reproduce the problem?

just upgraded to spyder 3.3 and Connecting to kernel appears and the kernel never starts.

## Versions

* Spyder version: 3.3.0 
* Python version: 3.6.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.9.4-1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0     :  5.3.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
Please start Spyder from a system terminal (cmd.exe) and see if there are there any errors reported there.

If there are no errors, I'm sorry to say we can't help you.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
