### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by GordonHK** [spyder-ide/spyder#7550]
Once I upgrade both of my spyder and spyder kernels, the spyder then pops up an internal error, below us the system details of my spyder:

* spyder-kernels (1.0.1) - Jupyter kernels for the Spyder console INSTALLED: 1.0.1 (latest)
* spyder-notebook (0.1.2) - Jupyter notebook integration with Spyder
* spyder-terminal (0.2.4) - Spyder Plugin for displaying a virtual terminal (OS independent) inside the main Spyder window
* spyder-reports (0.1.1) - Spyder-IDE plugin for Markdown reports using Pweave.
* spyder-unittest (0.3.1) - Plugin to run tests from within the Spyder IDE
* spyder-line-profiler (0.1.1) - Plugin for the Spyder IDE that integrates the Python line profiler.
* spyder-memory-profiler (0.1.2)  - Plugin for the Spyder IDE that integrates the Python memory profiler spyder (3.3.0) - Scientific PYthon Development Environment INSTALLED: 3.2.8 LATEST:    3.3.0
* spyder-conda (0.1.0)
* kn-spyder-tag (3.2.8) - Python project to create a small buzz network associating tags that are most likely to create buzz
* spyder.example (0.0.1) - A Spyder Plugin example package
* spyder.autopep8 (0.0.1) - A plugin to run the autopep8 python linter from within the spyder editor

**Comment by ccordoba12** [comment]
> the spyder then pops up an internal error

What's the internal error?

**Comment by ccordoba12** [comment]
I guess you were able to make 3.3.0 work, which solves the problem you reported.
