### ISSUE TITLE
Spyder 2.3.8 can't start because QT_API is neither pyqt nor pyside; OS X 10.13.6 has pyqt5 instead

### ISSUE THREAD

**Issue by courtneypk-work** [spyder-ide/spyder#7559]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am on a mac, with the following specs/configuratoins:
* OS X 10.13.6. 
* anaconda-navigator v 1.8.7
* conda version 4.5.8
* the root or base env has python 3.6.3 and I also have an env with python 3.4.5. because I support a machine that has that version.
* spyder is version 2.3.8 in the python 3.4.5 env, and it is version 3.3.0 in the python 3.6.3 env.

I can start up spyder 3.3.0 just fine in the base env. However, when I try starting spyder 2.3.8 in the python 3.4.5 env from the command line, I get the error:
```
Traceback (most recent call last):
  File "/Users/paulcourtney/anaconda3/envs/Python_345/bin/spyder", line 3, in <module>
    start_app.main()
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/spyder.py", line 48, in <module>
    requirements.check_qt()
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/qt/__init__.py", line 12, in <module>
    assert os.environ['QT_API'] in ('pyqt', 'pyside')
AssertionError
```
So spyder 2.3.8 will not start. 

I also did some sleuthing of similar problems (https://github.com/spyder-ide/spyder/issues/3171). I examined the `QT_API` environment variable in my mac and found it to be `pyqt5`. This explains to me why the assert is failing - neither `pyqt` nor `pyside` are found. 

I also found that spyder 2.3.8 will sometimes fail when starting from Anaconda Navigator and sometimes successfully start. When it fails, the same error message is given.

### What steps reproduce the problem?

1. Mac OS X 10.13.6 with Anaconda Navigator v 1.8.7
2. Use conda to create an env for python 3.4.5
3. Start spyder from the command line while in the python 3.4.5 env or start spyder from Anaconda Navigator with the Python 3.4.5 env selected.

### What is the expected output? What do you see instead?
I should see Spyder start up. Instead I see the error message.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/Users/paulcourtney/anaconda3/envs/Python_345/bin/spyder", line 3, in <module>
    start_app.main()
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/start_app.py", line 114, in main
    from spyderlib import spyder
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/spyder.py", line 48, in <module>
    requirements.check_qt()
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/requirements.py", line 40, in check_qt
    from spyderlib import qt
  File "/Users/paulcourtney/anaconda3/envs/Python_345/lib/python3.4/site-packages/spyderlib/qt/__init__.py", line 12, in <module>
    assert os.environ['QT_API'] in ('pyqt', 'pyside')
AssertionError

```

## Versions

* Spyder version: 2.3.8
* Python version: 3.4.5
* Qt version: 4.8.7
* PyQt version: 4.11.4
* Operating System name/version: OS X High Sierra 10.13.6

#### Note that these dependencies are courtesy of Spyder rather miraculously starting up from Anaconda Navigator.

```
IPython >=1.0      :  5.1.0 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  None (NOK)
pandas >=0.13.1    :  None (NOK)
pep8 >=0.6         :  1.7.0 (OK)
psutil >=0.3       :  5.0.1 (OK)
pyflakes >=0.6.0   :  1.5.0 (OK)
pygments >=1.6     :  2.1.3 (OK)
pylint >=0.25      :  1.7.4 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
sphinx >=0.6.6     :  1.5.1 (OK)
sympy >=0.7.3      :  None (NOK)
zmq >=2.1.11       :  16.0.2 (OK)

```

**Comment by ccordoba12** [comment]
We don't support that version anymore (it's more than 2 years old). Please use conda to install our latest version (3.3.0).
