### ISSUE TITLE
Annoying "Are you sure you want to restart the kernel?"

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#7561]
## Problem Description

Dialog box "Are you sure you want to restart the kernel?" is quite annoying.

### What steps reproduce the problem?

1.  Right-click on iPython console tab
2.  Choose "Restart kernel"

### What is the expected output? What do you see instead?

I expect the kernel to restart.
Instead I get a dialog box that forces me to say "Yes".

(If somebody feels this dialog is really important, can it be made optional in Preferences?)

## Versions

* Spyder version:  3.3.0
* Python version: 3.6
* Operating System name/version:  Win10 x64

### Dependencies

IPython >=4.0     :  6.4.0 (OK)
cython >=0.21     :  0.28.3 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for the suggestion. We'll try to address it in a future release.
