### ISSUE TITLE
IPython console unable to start. "An error ocurred wile starting the kernel"

### ISSUE THREAD

**Issue by aryamanjain** [spyder-ide/spyder#7575]
I Anaconda3-4.2.0 installed earlier. I uninstalled that and installed Anaconda3-5.2.0-Windows-x86_64.
Unfortunately, Spyder 3.2.8 did not launch after the splash page.
I tried disabling the anti-virus and running Spyder again but it didn't make a difference. I then uninstalled and reinstalled Anaconda while disabling the anti-virus. It still did not work.

Finally, I created a new environment from the Anaconda Navigator. For some reason, this new environment had Spyder 2.3.8. This Spyder got running, but the IPython console was unable to connect to the kernel.

Traceback (most recent call last):
File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 186, in 
ipk_temp.initialize()
File "", line 2, in initialize
File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\ipykernel\kernelapp.py", line 456, in initialize
self.init_sockets()
File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\ipykernel\kernelapp.py", line 232, in init_sockets
context = zmq.Context.instance()
File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\zmq\sugar\context.py", line 108, in instance
cls._instance = cls(io_threads=io_threads)
File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
zmq.error.ZMQError: Unknown error

**Comment by ccordoba12** [comment]
Please open an Anaconda Prompt and run there

    conda install -f zeromq pyzmq

and try again.

**Comment by aryamanjain** [comment]
Hi. Thanks for the suggestion! But I'm still getting this error:

> Error in sitecustomize; set PYTHONVERBOSE for traceback:
> TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
> Traceback (most recent call last):
> File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 186, in 
> ipk_temp.initialize()
> File "", line 2, in initialize
> File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\traitlets\config\application.py", line 87, in catch_config_error
> return method(app, *args, **kwargs)
> File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\ipykernel\kernelapp.py", line 456, in initialize
> self.init_sockets()
> File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\ipykernel\kernelapp.py", line 232, in init_sockets
> context = zmq.Context.instance()
> File "C:\Users\a‑jai\AppData\Local\conda\conda\envs\new_env\lib\site‑packages\zmq\sugar\context.py", line 108, in instance
> cls._instance = cls(io_threads=io_threads)
> File "zmq/backend/cython/context.pyx", line 49, in zmq.backend.cython.context.Context.__cinit__
> zmq.error.ZMQError: Unknown error

**Comment by ccordoba12** [comment]
> TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

This suggests that this is a problem with your firewall/antivirus blocking internal traffic needed to start and communicate to our kernels.

You said you deactivated your antivirus, so maybe you need to uninstall it or try to add a rule for Python to open a socket in your computer.

Unfortunately we can't help you further because we don't know what else to recommend you and this is not really an Spyder problem.
