### ISSUE TITLE
Spyder launch screen and CTRL+I issue

### ISSUE THREAD

**Issue by iamnoobpleasehelp** [spyder-ide/spyder#7576]
## Problem Description

Please note that I am new to coding. Spyder was working fine. I decided to update Spyder using the Anaconda prompt and followed the instructions. When I relaunched Spyder, the problem surfaced as described below. The problem is partially solved when you switch the Help settings to Plain Text instead of Rich Text. However, I would much rather view it in the Rich Text mode.

> Spyder window is rendered larger than its own containing window resulting menus and status bar to be partially displayed.

as described in #4821. In addition, the cursor location is off by approximately a cm.

### What steps reproduce the problem?

1.  Launch Spyder with default settings
2. Use the Help function

### What is the expected output? What do you see instead?
Problems (First picture when launched) (Second picture when using the help function):
![problem1](https://user-images.githubusercontent.com/41853545/43364294-850652e2-92e5-11e8-9872-2a5b79cb2e51.JPG)
![prob2](https://user-images.githubusercontent.com/41853545/43364293-84fbebd6-92e5-11e8-95c7-e913bdf6c0a4.JPG)

Temporary Solutions (First solution when closing help window as suggested in #4821) (Second solution when switching help setting to plain text):
![temp1](https://user-images.githubusercontent.com/41853545/43364303-9362e9f4-92e5-11e8-8ced-fe1ca63f66e1.JPG)
![temp2](https://user-images.githubusercontent.com/41853545/43364304-936d2284-92e5-11e8-879f-fa63a2d7e86a.JPG)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please close Spyder, open the Anaconda prompt, run there

    conda install qt=5.6* pyqt=5.6* sip=4.18*

and try again.

**Comment by iamnoobpleasehelp** [comment]
@ccordoba12 It has returned to normal. Thank you!
