### ISSUE TITLE
Cant update conda 

### ISSUE THREAD

**Issue by Stasello21** [spyder-ide/spyder#7577]
## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by Stasello21** [comment]
Hello! 
I am trying to update conda using anaconda promt : conda update conda. It shows all the packages being downloaded, verified but when it starts to execute - this error occurs. 

ERROR conda.core.link:_execute(502): An error occurred while uninstalling package 'defaults::anaconda-5.2.0-py36_3'.
PermissionError(13, 'Access is denied')

it happens on both Mac and Windows. I have full admin rights and I have installed the Anaconda for all users. 

Any ideas what can I do here? 
thank you
Stan

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with Anaconda, so please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/

The only thing that occurs to me is that you should launch the Anaconda Prompt with admin privileges (on Windows) and run `conda update spyder` with sudo on macOS.

However, if you're the only user in your computer, you should remove your previous installation and reinstall Anaconda for your user only.

**Comment by ccordoba12** [comment]
> However, if you're the only user in your computer, you should remove your previous installation and reinstall Anaconda for your user only.

That's the recommended installation method because it's less prone to errors.

**Comment by Stasello21** [comment]
regarding Windows update - you are right. right click on Anaconda Prompt and run as admin - worked out.
