### ISSUE TITLE
Spyder 3.3 doesnt run - only 3.2.8. Pyqt-related "black screen problem" ensues.

### ISSUE THREAD

**Issue by kevinrse** [spyder-ide/spyder#7579]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* N/A Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

I use Spyder within a dedicated Anaconda/Conda environment. Consequently I'm posting to both the Conda and Spyder issue trackers. I hope that's not poor etiquette but I think aspects of my issue are relevant to both groups. Thanks to all of you for good products and good past support.

So, there are two main problems: (1) Spyder all black, consistent with a few other bug reports; (2) Spyder installed version = 3.3 but seems to only run 3.2.8.

According to other threads on the "black screen issue" here, if the second problem is fixed, I think the first will be solved as well.

In the last few weeks I once solved the black screen problem by finding this thread
https://github.com/ContinuumIO/anaconda-issues/issues/9331
and downgrading pyqt to 5.6. Since then, however, I have had the problem crop up again.

At present I'm using Spyder for python coding in a dedicated environment. With my environment active, I `conda list | grep spyder` and see that my Spyder version is 3.3. When I start Spyder, however:
(1) I get a notification that Spyder 3.3 is available and I should update;
(2) Spyder window is entirely black;
(3) even though window is all black, I can still get a context menu by right-clicking. I select "about Spyder" and see that the spyder I'm getting is actually version 3.2.8(!?);
(4) In the stdout stream in my terminal, I see a bunch of "shader program is not linked" errors.

As far as I can see, this issue is consistent with the problem in the thread linked above, except that downgrading pyqt no longer solves the problem! Again, it seems that the crux of the issue is probably I'm somehow not actually able to run Spyder 3.3 even though Conda tells me it is installed.

I stumbled across this thread
https://github.com/spyder-ide/spyder/issues/7327
as well and installed pyopengl. Did not solve problem.

Some other miscellaneous details: I have confirmed that the above issues arise BOTH with my recently-downgraded pyqt=5.6 AND with an update to newest pyqt, currently 5.9.2.  I have also verified that `which spyder` points to my Anaconda2 dir. Linux Mint 18.1 64-bit. Conda --version = 4.5.8.  Please let me know if I can provide any other info. Thanks again.

## Versions

* Spyder version: 3.3.0 (but 3.2.8 is running!)
* Python version: 2.7.14
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: Linux Mint 18.1 Serena / Cinnamon DE / 64-bit

### Dependencies

```
IPython >=4.0;<6.0:  5.7.0 (OK)
cython >=0.21     :  0.28.2 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.3 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
> (1) Spyder all black, consistent with a few other bug reports;

This is fixed in our 3.3 version or by installing `pyopengl`.

(2) Spyder installed version = 3.3 but seems to only run 3.2.8.

You need to track down where the 3.2.8 version is installed and remove it, so the 3.3 one takes place. It's probably installed in your base/root conda env or system wide (if at some point you ran `sudo pip install spyder`). This is not a Spyder problem, so you need to do it by yourself.

**Comment by adaaaaaa** [comment]
why IPython >=4.0;<6.0?
i'm using version 6.5.0...

**Comment by electricmomo** [comment]
(1) not fixed. Hell of a very annoying bug.

**Comment by ccordoba12** [comment]
Closing because this is very old now.
