### ISSUE TITLE
unable to connect to internet

### ISSUE THREAD

**Issue by suyog957** [spyder-ide/spyder#7585]
## Description

**What steps will reproduce the problem?**

1. updating anaconda
2. trying install any new libraries
3. trying to update a library

**What is the expected output? What do you see instead?**
installing / updating should be smooth

**Please provide any additional information below**

![image](https://user-images.githubusercontent.com/10611697/43413935-68820aec-93ff-11e8-906d-6d9bbbe7b80a.png)

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.8.1 (NOK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
That's just a warning, you can ignore it or avoid it completely by going to

    Tools > Preferences > General > Advanced Settings

and deactivating the option called

    Check for updates on startup
