### ISSUE TITLE
dependency problem on Mac OS

### ISSUE THREAD

**Issue by Albert65** [spyder-ide/spyder#7586]
## Problem Description

Every time I update my Python3 packages by Pip3, I have to reinstall
spyder with certain downgrade. 

### What steps reproduce the problem?

1. Install Python 3 with Homebrew on Mac, then spyder via Pip3
2. Upgrade the Python packages
3. Then you will see spyder does not work anymore because of PyQt dependencies (although IPython is also contributing to failure)

### What is the expected output? What do you see instead?

I would expect Spyder either blocks update of certain dependencies or conforms their latest versions.

### Paste Traceback/Error Below (if applicable)

***** UPDATE by pip3

pip3 list | cut -d ' ' -f 1 | tail -n +3 | xargs pip3 install -U
.............

**spyder 3.3.0 has requirement pyqt5<5.10; python_version >= "3", but you'll have pyqt5 5.11.2 which is incompatible.**
spyder 3.3.0 has requirement spyder-kernels<1.0, but you'll have spyder-kernels 1.0.1 which is incompatible.
ipython 6.4.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you'll have prompt-toolkit 2.0.4 which is incompatible.
Installing collected packages: astroid, pip, prompt-toolkit, pylint, PyQt5, Sphinx, spyder-kernels
  Found existing installation: astroid 2.0
    Uninstalling astroid-2.0:
      Successfully uninstalled astroid-2.0
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
  Found existing installation: prompt-toolkit 1.0.15
    Uninstalling prompt-toolkit-1.0.15:
      Successfully uninstalled prompt-toolkit-1.0.15
  Found existing installation: pylint 2.0.0
    Uninstalling pylint-2.0.0:
      Successfully uninstalled pylint-2.0.0
  Found existing installation: PyQt5 5.9.2
    Uninstalling PyQt5-5.9.2:
      Successfully uninstalled PyQt5-5.9.2
  Found existing installation: Sphinx 1.7.5
    Uninstalling Sphinx-1.7.5:
      Successfully uninstalled Sphinx-1.7.5
  Found existing installation: spyder-kernels 0.2.4
    Uninstalling spyder-kernels-0.2.4:
      Successfully uninstalled spyder-kernels-0.2.4
Successfully installed PyQt5-5.11.2 Sphinx-1.7.6 astroid-2.0.1 pip-18.0 prompt-toolkit-2.0.4 pylint-2.0.1 spyder-kernels-1.0.1

***** NOW DOWNGRADE and reinstall spyder

pip3 install spyder
...............

Requirement already satisfied: spyder in /usr/local/lib/python3.7/site-packages (3.3.0)
Requirement already satisfied: qtawesome>=0.4.1 in /usr/local/lib/python3.7/site-packages (from spyder) (0.4.4)
Requirement already satisfied: qtconsole>=4.2.0 in /usr/local/lib/python3.7/site-packages (from spyder) (4.3.1)
Requirement already satisfied: rope>=0.10.5 in /usr/local/lib/python3.7/site-packages (from spyder) (0.10.7)
Requirement already satisfied: numpydoc in /usr/local/lib/python3.7/site-packages (from spyder) (0.8.0)
Requirement already satisfied: pygments>=2.0 in /usr/local/lib/python3.7/site-packages (from spyder) (2.2.0)
Requirement already satisfied: pyflakes in /usr/local/lib/python3.7/site-packages (from spyder) (2.0.0)
Requirement already satisfied: pycodestyle in /usr/local/lib/python3.7/site-packages (from spyder) (2.4.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.7/site-packages (from spyder) (5.4.6)
Requirement already satisfied: qtpy>=1.2.0 in /usr/local/lib/python3.7/site-packages (from spyder) (1.4.2)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.7/site-packages (from spyder) (0.5.3)
Requirement already satisfied: chardet>=2.0.0 in /usr/local/lib/python3.7/site-packages (from spyder) (3.0.4)
Collecting pyqt5<5.10; python_version >= "3" (from spyder)
  Using cached https://files.pythonhosted.org/packages/5e/41/93bf8f289b476bc5d8cece7948a166cbcea761f5b1262e5fdd7076a5e02a/PyQt5-5.9.2-5.9.3-cp35.cp36.cp37-abi3-macosx_10_6_intel.whl
Requirement already satisfied: jedi>=0.9.0 in /usr/local/lib/python3.7/site-packages (from spyder) (0.12.1)
Requirement already satisfied: sphinx in /usr/local/lib/python3.7/site-packages (from spyder) (1.7.6)
Requirement already satisfied: pylint in /usr/local/lib/python3.7/site-packages (from spyder) (2.0.1)
Requirement already satisfied: nbconvert in /usr/local/lib/python3.7/site-packages (from spyder) (5.3.1)
Requirement already satisfied: keyring in /usr/local/lib/python3.7/site-packages (from spyder) (13.2.1)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.7/site-packages (from spyder) (0.7.4)
Requirement already satisfied: pyzmq in /usr/local/lib/python3.7/site-packages (from spyder) (17.1.0)
Collecting spyder-kernels<1.0 (from spyder)
  Using cached https://files.pythonhosted.org/packages/1d/6c/2d151d2711baed6fd40383d7f24307eb190b38293d80b3ef7e585f72c58e/spyder_kernels-0.2.4-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from qtawesome>=0.4.1->spyder) (1.11.0)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.7/site-packages (from qtconsole>=4.2.0->spyder) (0.2.0)
Requirement already satisfied: traitlets in /usr/local/lib/python3.7/site-packages (from qtconsole>=4.2.0->spyder) (4.3.2)
Requirement already satisfied: ipykernel>=4.1 in /usr/local/lib/python3.7/site-packages (from qtconsole>=4.2.0->spyder) (4.8.2)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.7/site-packages (from qtconsole>=4.2.0->spyder) (4.4.0)
Requirement already satisfied: jupyter-client>=4.1 in /usr/local/lib/python3.7/site-packages (from qtconsole>=4.2.0->spyder) (5.2.3)
Requirement already satisfied: Jinja2>=2.3 in /usr/local/lib/python3.7/site-packages (from numpydoc->spyder) (2.10)
Requirement already satisfied: sip<4.20,>=4.19.4 in /usr/local/lib/python3.7/site-packages (from pyqt5<5.10; python_version >= "3"->spyder) (4.19.8)
Requirement already satisfied: parso>=0.3.0 in /usr/local/lib/python3.7/site-packages (from jedi>=0.9.0->spyder) (0.3.1)
Requirement already satisfied: docutils>=0.11 in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (0.14)
Requirement already satisfied: sphinxcontrib-websupport in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (1.1.0)
Requirement already satisfied: babel!=2.0,>=1.3 in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (2.6.0)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (2.19.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (17.1)
Requirement already satisfied: snowballstemmer>=1.1 in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (1.2.1)
Requirement already satisfied: alabaster<0.8,>=0.7 in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (0.7.11)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (40.0.0)
Requirement already satisfied: imagesize in /usr/local/lib/python3.7/site-packages (from sphinx->spyder) (1.0.0)
Requirement already satisfied: mccabe in /usr/local/lib/python3.7/site-packages (from pylint->spyder) (0.6.1)
Requirement already satisfied: isort>=4.2.5 in /usr/local/lib/python3.7/site-packages (from pylint->spyder) (4.3.4)
Requirement already satisfied: astroid>=2.0.1 in /usr/local/lib/python3.7/site-packages (from pylint->spyder) (2.0.1)
Requirement already satisfied: nbformat>=4.4 in /usr/local/lib/python3.7/site-packages (from nbconvert->spyder) (4.4.0)
Requirement already satisfied: mistune>=0.7.4 in /usr/local/lib/python3.7/site-packages (from nbconvert->spyder) (0.8.3)
Requirement already satisfied: entrypoints>=0.2.2 in /usr/local/lib/python3.7/site-packages (from nbconvert->spyder) (0.2.3)
Requirement already satisfied: testpath in /usr/local/lib/python3.7/site-packages (from nbconvert->spyder) (0.3.1)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.7/site-packages (from nbconvert->spyder) (1.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.7/site-packages (from nbconvert->spyder) (2.1.3)
Requirement already satisfied: decorator in /usr/local/lib/python3.7/site-packages (from traitlets->qtconsole>=4.2.0->spyder) (4.3.0)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python3.7/site-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder) (6.4.0)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.7/site-packages (from ipykernel>=4.1->qtconsole>=4.2.0->spyder) (5.1)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/site-packages (from jupyter-client>=4.1->qtconsole>=4.2.0->spyder) (2.7.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.3->numpydoc->spyder) (1.0)
Requirement already satisfied: pytz>=0a in /usr/local/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx->spyder) (2018.5)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->spyder) (2.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->spyder) (2018.4.16)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=2.0.0->sphinx->spyder) (1.23)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.7/site-packages (from packaging->sphinx->spyder) (2.2.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.7/site-packages (from astroid>=2.0.1->pylint->spyder) (1.10.11)
Requirement already satisfied: lazy-object-proxy in /usr/local/lib/python3.7/site-packages (from astroid>=2.0.1->pylint->spyder) (1.3.1)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.7/site-packages (from nbformat>=4.4->nbconvert->spyder) (2.6.0)
Requirement already satisfied: html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre in /usr/local/lib/python3.7/site-packages (from bleach->nbconvert->spyder) (1.0.1)
Requirement already satisfied: backcall in /usr/local/lib/python3.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder) (0.1.0)
Requirement already satisfied: appnope; sys_platform == "darwin" in /usr/local/lib/python3.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder) (0.1.0)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder) (0.8.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.7/site-packages (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder) (4.6.0)
Collecting prompt-toolkit<2.0.0,>=1.0.15 (from ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder)
  Using cached https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl
Requirement already satisfied: webencodings in /usr/local/lib/python3.7/site-packages (from html5lib!=1.0b1,!=1.0b2,!=1.0b3,!=1.0b4,!=1.0b5,!=1.0b6,!=1.0b7,!=1.0b8,>=0.99999999pre->bleach->nbconvert->spyder) (0.5.1)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder) (0.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.7/site-packages (from prompt-toolkit<2.0.0,>=1.0.15->ipython>=4.0.0->ipykernel>=4.1->qtconsole>=4.2.0->spyder) (0.1.7)
Installing collected packages: pyqt5, spyder-kernels, prompt-toolkit
  Found existing installation: PyQt5 5.11.2
    Uninstalling PyQt5-5.11.2:
      Successfully uninstalled PyQt5-5.11.2
  Found existing installation: spyder-kernels 1.0.1
    Uninstalling spyder-kernels-1.0.1:
      Successfully uninstalled spyder-kernels-1.0.1
  Found existing installation: prompt-toolkit 2.0.4
    Uninstalling prompt-toolkit-2.0.4:
      Successfully uninstalled prompt-toolkit-2.0.4
Successfully installed prompt-toolkit-1.0.15 pyqt5-5.9.2 spyder-kernels-0.2.4

## Versions

* Spyder version: 3.3.0
* Python version: 3.7
* Qt version: 5+
* PyQt version: 5+
* Operating System name/version: Mac OS High Sierra, Homebrew 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> spyder 3.3.0 has requirement pyqt5<5.10; python_version >= "3", but you'll have pyqt5 5.11.2 which is incompatible.
spyder 3.3.0 has requirement spyder-kernels<1.0, but you'll have spyder-kernels 1.0.1 which is incompatible.
ipython 6.4.0 has requirement prompt-toolkit<2.0.0,>=1.0.15, but you'll have prompt-toolkit 2.0.4 which is incompatible.

Sorry, but that's why pip **10** doesn't update all package dependencies when you're updating a single package.

If you want to update *all* your packages with

    pip3 list | cut -d ' ' -f 1 | tail -n +3 | xargs pip3 install -U

then you have to live with downgrading the things that need to be downgraded, sorry.
