### ISSUE TITLE
Spyder does not start (fresh installation of Anaconda)

### ISSUE THREAD

**Issue by rohitspace** [spyder-ide/spyder#7601]
## Problem Description
Spyder does not open. 

### What steps reproduce the problem?

1. A fresh installation of Ananconda
2. Fresh Ananaconda plus updating conda and all packages
3. Reinstalling latest Anaconda

### What is the expected output? What do you see instead?
Spyder should start since it is a fresh installation and no changes have been made whatsoever.
But Spyder does not start.
 An import error is displayed.

```python-traceback

(base) C:\Users\User>spyder
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\start.py", line 190, in main
    from spyder.app import mainwindow
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 80, in <module>
    from qtpy.compat import from_qvariant
  File "C:\Users\User\Anaconda3\lib\site-packages\qtpy\compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "C:\Users\User\Anaconda3\lib\site-packages\qtpy\QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: DLL load failed: The specified procedure could not be found.

```

## Versions

* Spyder version: 3.3.0
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro, version 1803

```
 active environment : base
    active env location : C:\Users\User\Anaconda3
            shell level : 1
       user config file : C:\Users\User\.condarc
 populated config files :
          conda version : 4.5.9
    conda-build version : 3.12.0
         python version : 3.6.6.final.0
       base environment : C:\Users\User\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-32
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-32
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-32
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-32
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-32
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\User\Anaconda3\pkgs
                          C:\Users\User\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\User\Anaconda3\envs
                          C:\Users\User\AppData\Local\conda\conda\envs
                          C:\Users\User\.conda\envs
               platform : win-32
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```

<details>
(base) C:\Users\User>conda list
# packages in environment at C:\Users\User\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36ha9200a3_0
alabaster                 0.7.11                   py36_0
anaconda                  custom           py36h8b40cde_0
anaconda-client           1.6.14                   py36_0
anaconda-navigator        1.8.7                    py36_0
anaconda-project          0.8.2            py36hdea9eaf_0
appdirs                   1.4.3                    py36_0
asn1crypto                0.24.0                   py36_0
astroid                   1.6.5                    py36_0
astropy                   3.0.3            py36hfa6e2cd_2
atomicwrites              1.1.5                    py36_0
attrs                     18.1.0                   py36_0
automat                   0.7.0                    py36_0
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
backports                 1.0              py36hf8a4c8f_1
backports.shutil_get_terminal_size 1.0.0            py36h567543b_2
beautifulsoup4            4.6.1                    py36_0
bitarray                  0.8.3            py36hfa6e2cd_0
bkcharts                  0.2              py36h41dda5e_0
blas                      1.0                         mkl
blaze                     0.11.3           py36h70bead1_0
bleach                    2.1.3                    py36_0
blosc                     1.14.3               he51fdeb_0
bokeh                     0.13.0                   py36_0
boto                      2.49.0                   py36_0
bottleneck                1.2.1            py36hd155fb5_0
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2018.03.07                    0
certifi                   2018.4.16                py36_0
cffi                      1.11.5           py36h945400d_0
chardet                   3.0.4                    py36_1
click                     6.7              py36hfb6b3c4_0
cloudpickle               0.5.3                    py36_0
clyent                    1.2.2            py36h4dd741a_1
colorama                  0.3.9            py36he9a059a_0
comtypes                  1.1.6                    py36_0
conda                     4.5.9                    py36_0
conda-build               3.12.0                   py36_1
conda-env                 2.6.0                h36134e3_1
conda-verify              3.1.0                    py36_0
console_shortcut          0.1.1                h6bb2dd7_3
constantly                15.1.0                   py36_0
contextlib2               0.5.5            py36h19a5d9b_0
cryptography              2.2.2            py36hfa6e2cd_0
curl                      7.61.0               h7602738_0
cycler                    0.10.0           py36hd299a41_0
cython                    0.28.4           py36h6538335_0
cytoolz                   0.9.0.1          py36hfa6e2cd_0
dask                      0.18.2                   py36_0
dask-core                 0.18.2                   py36_0
datashape                 0.5.4            py36h801e743_0
decorator                 4.3.0                    py36_0
distributed               1.22.0                   py36_0
docutils                  0.14             py36h4cf9f97_0
entrypoints               0.2.3            py36hd26a89c_2
et_xmlfile                1.0.1            py36ha14dd7c_0
fastcache                 1.0.2            py36hfa6e2cd_2
filelock                  3.0.4                    py36_0
flask                     1.0.2                    py36_1
flask-cors                3.0.6                    py36_0
freetype                  2.8                  h0224ed4_1
future                    0.16.0                   py36_1
get_terminal_size         1.0.0                h4b36c58_0
gevent                    1.3.5            py36hfa6e2cd_0
glob2                     0.6              py36h2e90fdd_0
greenlet                  0.4.14           py36hfa6e2cd_0
h5py                      2.8.0            py36h3bdd7fb_0
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py36_2
html5lib                  1.0.1            py36h6ed1b79_0
hyperlink                 18.0.0                   py36_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 h3fcc66b_1
idna                      2.7                      py36_0
imageio                   2.3.0                    py36_0
imagesize                 1.0.0                    py36_0
incremental               17.5.0           py36h08178a5_0
intel-openmp              2018.0.3                      0
ipykernel                 4.8.2                    py36_0
ipython                   6.5.0                    py36_0
ipython_genutils          0.2.0            py36h011d6f9_0
ipywidgets                7.3.1                    py36_0
isort                     4.3.4                    py36_0
itsdangerous              0.24             py36h0eb04fb_1
jdcal                     1.4                      py36_0
jedi                      0.12.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   he27b436_2
jsonschema                2.6.0            py36hc586ae5_0
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36hb66b1b8_1
jupyter_core              4.4.0                    py36_0
jupyterlab                0.33.4                   py36_0
jupyterlab_launcher       0.11.2                   py36_0
keyring                   13.2.1                   py36_0
kiwisolver                1.0.1            py36h7de1d16_0
lazy-object-proxy         1.3.1            py36hfebf436_0
libcurl                   7.61.0               h7602738_0
libiconv                  1.15                 hc4a7105_7
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                hd619d38_4
libtiff                   4.0.9                hb8ad9f9_1
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.23.2           py36he51fdeb_0
locket                    0.2.0            py36h3eabf40_1
lxml                      4.2.3            py36hef2cd61_0
lzo                       2.10                 h00ab751_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.0              py36hfa6e2cd_1
matplotlib                2.2.2            py36h153e9ff_1
mccabe                    0.6.1            py36ha34857b_1
menuinst                  1.4.14           py36hfa6e2cd_0
mistune                   0.8.3            py36hfa6e2cd_1
mkl                       2018.0.3                      1
mkl-service               1.1.2            py36hb217b18_4
mkl_fft                   1.0.4            py36h1e22a9b_1
mkl_random                1.0.1            py36h9258bd6_0
more-itertools            4.2.0                    py36_0
mpmath                    1.0.0            py36haf93544_2
msgpack-python            0.5.6            py36he980bc4_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.5.0                    py36_0
navigator-updater         0.2.1                    py36_0
nbconvert                 5.3.1            py36h5066f46_0
nbformat                  4.4.0            py36hfe36a2e_0
networkx                  2.1                      py36_0
nltk                      3.3.0                    py36_0
nose                      1.3.7                    py36_2
notebook                  5.6.0                    py36_0
numba                     0.38.1           py36h830ac7b_0
numexpr                   2.6.5            py36hcd2f87e_0
numpy                     1.15.0           py36h9fa60d3_0
numpy-base                1.15.0           py36h4a99626_0
numpydoc                  0.8.0                    py36_0
odo                       0.5.1            py36h3d61389_0
olefile                   0.45.1                   py36_0
openpyxl                  2.5.4                    py36_0
openssl                   1.0.2o               h8ea7d77_0
packaging                 17.1                     py36_0
pandas                    0.23.3           py36h830ac7b_0
pandoc                    2.2.1                h1a437c5_0
pandocfilters             1.4.2            py36hbaae778_1
parso                     0.3.1                    py36_0
partd                     0.3.8            py36h9032c1e_0
path.py                   11.0.1                   py36_0
pathlib2                  2.3.2                    py36_0
patsy                     0.5.0                    py36_0
pep8                      1.7.1                    py36_0
pickleshare               0.7.4            py36he181f7f_0
pillow                    5.1.0            py36h0738816_0
pip                       10.0.1                   py36_0
pkginfo                   1.4.2                    py36_1
pluggy                    0.6.0                    py36_0
ply                       3.11                     py36_0
prometheus_client         0.3.1                    py36_0
prompt_toolkit            1.0.15           py36ha226939_0
psutil                    5.4.6            py36hfa6e2cd_0
py                        1.5.4                    py36_0
pyasn1                    0.4.4                    py36_0
pyasn1-modules            0.2.2                    py36_0
pycodestyle               2.4.0                    py36_0
pycosat                   0.6.3            py36hbfdb8c3_0
pycparser                 2.18                     py36_1
pycrypto                  2.6.1            py36hfa6e2cd_9
pycurl                    7.43.0.2         py36h74b6da3_0
pyflakes                  2.0.0                    py36_0
pygments                  2.2.0            py36h1a04f08_0
pylint                    1.9.2                    py36_0
pyodbc                    4.0.23           py36h6538335_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.0                    py36_1
pyqt                      5.9.2            py36h1aa27d4_0
pysocks                   1.6.8                    py36_0
pytables                  3.4.4            py36he6f6034_0
pytest                    3.6.4                    py36_0
pytest-arraydiff          0.2                      py36_0
pytest-astropy            0.4.0                    py36_0
pytest-doctestplus        0.1.3                    py36_0
pytest-openfiles          0.3.0                    py36_0
pytest-remotedata         0.3.0                    py36_0
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.3                    py36_0
pytz                      2018.5                   py36_0
pywavelets                0.5.2            py36hf262123_0
pywin32                   223              py36hfa6e2cd_1
pywinpty                  0.5.4                    py36_0
pyyaml                    3.13             py36hfa6e2cd_0
pyzmq                     17.0.0           py36hfa6e2cd_3
qt                        5.9.6            vc14h62aca36_0
qtawesome                 0.4.4            py36h6b33ce7_0
qtconsole                 4.3.1            py36h86495bc_0
qtpy                      1.4.2                    py36_0
requests                  2.19.1                   py36_0
rope                      0.10.7           py36h2a980e7_0
ruamel_yaml               0.15.46          py36hfa6e2cd_0
scikit-image              0.14.0           py36h6538335_1
scikit-learn              0.19.1           py36hb0057d7_0
scipy                     1.1.0            py36h672f292_0
seaborn                   0.9.0                    py36_0
send2trash                1.5.0                    py36_0
service_identity          17.0.0                   py36_0
setuptools                39.2.0                   py36_0
simplegeneric             0.8.1                    py36_2
singledispatch            3.4.0.3          py36h2687f66_0
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
snappy                    1.1.7                h8327587_3
snowballstemmer           1.2.1            py36h5e2b779_0
sortedcollections         1.0.1                    py36_0
sortedcontainers          2.0.4                    py36_0
sphinx                    1.7.6                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder                    3.3.0                    py36_0
spyder-kernels            0.2.4                    py36_0
sqlalchemy                1.2.10           py36hfa6e2cd_0
sqlite                    3.24.0               h7602738_0
statsmodels               0.9.0            py36h452e1ab_0
sympy                     1.2                      py36_0
tblib                     1.3.2            py36h96aaa60_0
terminado                 0.8.1                    py36_1
testpath                  0.3.1            py36ha9283f1_0
tk                        8.6.7                ha9f76c9_3
toolz                     0.9.0                    py36_0
tornado                   5.0.2            py36hfa6e2cd_0
traitlets                 4.3.2            py36h0dbcc04_0
twisted                   18.4.0           py36hfa6e2cd_0
typing                    3.6.4                    py36_0
unicodecsv                0.14.1           py36h238903e_0
urllib3                   1.23                     py36_0
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
wcwidth                   0.1.7            py36hc8ec93f_0
webencodings              0.5.1            py36hf0a7dc3_1
werkzeug                  0.14.1                   py36_0
wheel                     0.31.1                   py36_0
widgetsnbextension        3.3.1                    py36_0
win_inet_pton             1.0.1            py36h6b5aef5_1
win_unicode_console       0.5              py36ha08cfaa_0
wincertstore              0.2              py36hcdd9a18_0
winpty                    0.4.3                         4
wrapt                     1.10.11          py36h084cbfa_0
xlrd                      1.1.0            py36he7b893d_1
xlsxwriter                1.0.5                    py36_0
xlwings                   0.11.8                   py36_0
xlwt                      1.3.0            py36hb79324b_0
yaml                      0.1.7                h896c600_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3            py36hf291af1_0
zlib                      1.2.11               hbb18732_2
zope                      1.0                      py36_0
zope.interface            4.5.0            py36hfa6e2cd_0
</details>

**Comment by ccordoba12** [comment]
This error usually happens because you have another Qt5 installation in your system. So please search for `Qt5*.dll` in your PC, find out what program installed them and uninstall it.

**Comment by ccordoba12** [comment]
I don't know how else to help you, very sorry. My last recommendation is to use a Windows or Linux virtual machine to run Spyder inside it.

**Comment by hubtub2** [comment]
I have the exact same problem when trying to start spyder from a fresh anaconda install. Running Windows 10 and installed Anaconda3 5.2.0 64Bit. I had several other python installations (pycharm and several winpythons 3.x/2.7). I deinstalled them all and also did a reinstallation of anaconda. No success. I have several other programs installed that seem to use Qt5 (Mendely, Microsoft Onedrive, ...) which I do not want to deinstall.

**Comment by rohitspace** [comment]
Unable to solve this issue!!!!!

**Comment by rohitspace** [comment]
```
(base) C:\Users\User>spyder
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\start.py", line 190, in main
    from spyder.app import mainwindow
  File "C:\Users\User\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 80, in <module>
    from qtpy.compat import from_qvariant
  File "C:\Users\User\Anaconda3\lib\site-packages\qtpy\compat.py", line 15, in <module>
    from .QtWidgets import QFileDialog
  File "C:\Users\User\Anaconda3\lib\site-packages\qtpy\QtWidgets.py", line 22, in <module>
    from PyQt5.QtWidgets import *
ImportError: DLL load failed: The specified procedure could not be found.

```
