### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by PascPeli** [spyder-ide/spyder#7608]
plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
 

maybe after i run 
#conda clean -tp
or maybe after I created a new env

Every time I launch Spyder from startmenu I get this error. I dont get it when I launch from Anaconda Navigator

conda info:
     active environment : base
    active env location : C:\Users\PascPeli\Anaconda3
            shell level : 1
       user config file : C:\Users\PascPeli\.condarc
 populated config files : C:\Users\PascPeli\.condarc
          conda version : 4.5.9
    conda-build version : 3.12.0
         python version : 3.6.6.final.0
       base environment : C:\Users\PascPeli\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\PascPeli\Anaconda3\pkgs
                          C:\Users\PascPeli\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\PascPeli\Anaconda3\envs
                          C:\Users\PascPeli\AppData\Local\conda\conda\envs
                          C:\Users\PascPeli\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.0). Please update by opening the Anaconda Prompt and running there

    conda update spyder
