### ISSUE TITLE
Segmentation fault (core dumped) when trying to start conda-installed spyder 3.3.0

### ISSUE THREAD

**Issue by Omer80** [spyder-ide/spyder#7620]
## Problem Description
I have Spyder 3.3.0 installed through conda. I am getting a segmentation fault:
```
$ spyder
Segmentation fault (core dumped)
```
### What steps reproduce the problem?

1. Install Anaconda for Python 2.7 on Ubuntu 16.04
2. Install `matplotlib` version `1.5.3`
3. Type in "spyder" at the command line.

### What is the expected output? What do you see instead?

I expect Spyder to start. Instead I get `Segmentation fault (core dumped)`

### Paste Traceback/Error Below (if applicable)

There's no traceback or error, just ```Segmentation fault (core dumped)```

## Versions

* Spyder version: 3.3.0
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Ubuntu 16.04

**Comment by ccordoba12** [comment]
> Install matplotlib version 1.5.3

What happens if you reinstall the latest Matplotlib?

**Comment by Omer80** [comment]
I cloned an environment from a different computer to the new installation and somehow the problem is solved. I could not trace any difference between the packages of Matplotlib, Spyder, PyQt or Qt between what was previously installed and what is running now..
