### ISSUE TITLE
Menu bar drop down not at correct position.

### ISSUE THREAD

**Issue by MRudey** [spyder-ide/spyder#7626]
## Problem Description
On a monitor in portrait mode which is not the main monitor the drop down menus of the menu bar, appear much lower than needed. They are aligned with the bottom of the top bar in Linux on the main monitor.
I do not use Spyer 3.3. as Anaconda does not provide the newest version and also a conda update spyer did not yield any results.

### What steps reproduce the problem?

1. Get a second monitor and flip it to be in portrait mode.
2. Move the position of the monitor so that its top is higher than the top of the main monitor.
3. Open spyder and click one of the menu bar items.

### What is the expected output? What do you see instead?
The drop down menus should be aligned with the menu bar. Instead they are aligned with the bottom of the Linux menu bar.
![screenshot from 2018-08-06 12-15-39](https://user-images.githubusercontent.com/11921755/43711290-8494af3c-9972-11e8-8e96-a867ad8d7822.png)

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Linux Ubuntu 18.04.1

### Dependencies
IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.15.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
psutil >=0.3     :  5.4.5 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
I think you need to close the Help pane to get a fix for this.

**Comment by MRudey** [comment]
Due to other reasons I had to make a new setup of Ubuntu. I now installed the newest version with
`python3 pip -m install spyder`
Now I have Spyder 3.3.0 but the problem persists, even with a closed Help Pane.
![screenshot from 2018-08-07 15-56-23](https://user-images.githubusercontent.com/11921755/43780438-de5fe4d0-9a5a-11e8-827a-a9fb93ed3b5c.png)

**Comment by ccordoba12** [comment]
No idea, I don't have a second monitor to try this, sorry.

**Comment by goanpeca** [comment]
This is not a Spyder issue. It is (was) a [Qt Bug](https://bugreports.qt.io/browse/QTBUG-60513?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true)
