### ISSUE TITLE
DataFrame viewer resizes the index column wrongly

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#7629]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] ~~Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)~~
I am seeing this with Spyder 3.3.0, which already is the latest release on PyPI.
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] ~~Reset preferences with ``spyder --reset`` / Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)~~
           I am using Spyder from freshly installed WinPython64-3.7.0.1
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The `Resize` button in the DataFrame viewer fails to resize the index column correctly.

### What steps reproduce the problem?

1. Define `df = pd.DataFrame(data=[42], index=['long-index-value'])`
2. Open `df` in the DataFrame viewer.
3. Click `Resize`.

### What is the expected output? What do you see instead?
I see the following broken display:
![wrong-index-resize](https://user-images.githubusercontent.com/21648/43724765-19637a94-999b-11e8-91f6-7a4b0b7e1a99.png)

## Versions

* Spyder version: 3.3.0
* Python version: 3.7.0 64bits
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Windows 7

### Dependencies
<details>
<summary>Click to expand</summary>

```
IPython >=4.0     :  6.4.0 (OK)
cython >=0.21     :  0.28.3 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```
</details>

**Comment by ccordoba12** [comment]
I think we don't apply the resize operation to the Index column, but this could be fixed in our master branch.

@dalthviz, what's the behavior after your changes in master?

**Comment by dalthviz** [comment]
@ccordoba12 after the resize this is what you see:

![imagen](https://user-images.githubusercontent.com/16781833/43761567-14ee2cb6-99eb-11e8-9b4d-8c663ca46616.png)

However, before the resize, you see something like this:

![imagen](https://user-images.githubusercontent.com/16781833/43761720-7e59c49e-99eb-11e8-88e3-1f68d610d8af.png)

**Comment by ccordoba12** [comment]
Ok, @dalthviz, please work to resize the Index column to its longest content or a maximum size.
