### ISSUE TITLE
SPYDER Debugging not working

### ISSUE THREAD

**Issue by vbagadia10** [spyder-ide/spyder#7631]
## Problem Description
Trying to enter debug mode, spyder simply goes through the entire file without allowing me an option to go step by step. I have tried uninstalling anaconda and reinstalling, updating spyder, updating conda upgrade --all, and upgrading IPython like suggested in other threads. 

### What steps reproduce the problem?

1. Open Spyder
2. Debugging not working (does not stop, just runs through entire file)
3. 

### What is the expected output? What do you see instead?
Enter debugging mode...I am not able to debug properly. 

## Versions

* Spyder version: 3.3
* Python version: 3.6.6
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

**Comment by vbagadia10** [comment]
@ccordoba12

**Comment by ccordoba12** [comment]
> Trying to enter debug mode

How did you do that?

**Comment by ccordoba12** [comment]
Please post a video of what you're experiencing here because I don't understand it, sorry.

**Comment by vbagadia10** [comment]
[~ - Spyder (Python 3.6) 8_8_2018 9_38_37 AM.zip](https://github.com/spyder-ide/spyder/files/2270452/-.Spyder.Python.3.6.8_8_2018.9_38_37.AM.zip)




debugfile('C:/Users/vbagadia/dev/calipsogen/calipsogen.py', wdir='C:/Users/vbagadia/dev/calipsogen')
Traceback (most recent call last):

  File "C:\Users\vbagadia\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-622e887b976b>", line 1, in <module>
    debugfile('C:/Users/vbagadia/dev/calipsogen/calipsogen.py', wdir='C:/Users/vbagadia/dev/calipsogen')

  File "C:\Users\vbagadia\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 701, in debugfile
    debugger.run("runfile(%r, args=%r, wdir=%r)" % (filename, args, wdir))

  File "C:\Users\vbagadia\AppData\Local\Continuum\anaconda3\lib\bdb.py", line 434, in run
    exec(cmd, globals, locals)

  File "<string>", line 1, in <module>

  File "C:\Users\vbagadia\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 678, in runfile
    execfile(filename, namespace)

  File "C:\Users\vbagadia\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 106, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "c:/users/vbagadia/dev/calipsogen/calipsogen.py", line 56
    print "Unable to execute query on metadata_product table for non visible granules"
                                                                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unable to execute query on metadata_product table for non visible granules")?

**Comment by ccordoba12** [comment]
> File "c:/users/vbagadia/dev/calipsogen/calipsogen.py", line 56
print "Unable to execute query on metadata_product table for non visible granules"
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Unable to execute query on metadata_product table for non visible granules")?

Well, the error is quite clear and Python is even telling you how to solve: In line **56** of your `calipsogen.py` file you have this `print` statement:

    print "Unable to execute query on metadata_product table for non visible granules"

Since you're using Python 3, this needs to be surrounded by parentheses, like this:

    print("Unable to execute query on metadata_product table for non visible granules")

That error message doesn't allow our consoles to enter debug mode, so this is not Spyder's fault.
