### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by PrateekNahar** [spyder-ide/spyder#7635]
While executing VGG16 model code in anaconda spyder i am getting error on :   

hist = custom_vgg_model.fit(X_train, y_train, batch_size=160, epochs=1, verbose=1, validation_data=(X_test, y_test)) 
this line of code.

This is the error:
An error ocurred while starting the kernel
2018󈚬󈚫 15:18:13.596221: W tensorflow/core/framework/allocator.cc:108] Allocation of 67108864 exceeds 10% of system memory.
2018󈚬󈚫 15:18:13.686227: W tensorflow/core/framework/allocator.cc:108] Allocation of 411041792 exceeds 10% of system memory.
2018󈚬󈚫 15:18:16.080364: W tensorflow/core/framework/allocator.cc:108] Allocation of 411041792 exceeds 10% of system memory.
2018󈚬󈚫 15:18:16.080364: W tensorflow/core/framework/allocator.cc:108] Allocation of 67108864 exceeds 10% of system memory.
2018󈚬󈚫 15:24:04.614299: W tensorflow/core/framework/allocator.cc:108] Allocation of 2055208960 exceeds 10% of system memory.

**Comment by ccordoba12** [comment]
Well, it seems you don't have enough memory in your system to run your code, sorry.

In any case, this is not a Spyder problem, so I'm closing this.

**Comment by PrateekNahar** [comment]
Ok Thank U
