### ISSUE TITLE
How to solve this problem: You have missing dependencies jedi >0.9.0:None(NOK)

### ISSUE THREAD

**Issue by hitergelei** [spyder-ide/spyder#7636]
## Description

**What steps will reproduce the problem?**

1.  I use miniconda
2. When I open the spyder, the spyder shows "error You have missing dependencies jedi >0.9.0:None(NOK)"

**What is the expected output? What do you see instead?**
![image](https://user-images.githubusercontent.com/23741177/43770214-48484b0e-9a6e-11e8-8cdc-cc8c8792a8e4.png)

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
WARNING:traitlets:kernel died: 6.006259202957153

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.5
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.3 (OK)
numpy >=1.7      :  1.15.0 (OK)
sphinx >=0.6.6   :  1.7.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  None (NOK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
If you want to go the hard way and use miniconda, you really need to know how to solve this problem:

    conda install jedi.

> AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
WARNING:traitlets:kernel died: 6.006259202957153

This is fixed in our latest version:

    conda update spyder

**Comment by asmwarrior** [comment]
I see a very similar issue when I try to run spyder under winpython, I can open the spyder main window, but the spyder is eating 8% cpu always.

I just checked the dependency, and see some modules are missing.
See this comment:
https://github.com/winpython/winpython/issues/816#issuecomment-601012939

but the strange thing is all the modules are already bundled in the winpython installer.
