### ISSUE TITLE
APPCRASH (mkl_core.dll)

### ISSUE THREAD

**Issue by NavinSinghsays** [spyder-ide/spyder#7637]
Well, I have tried everything said/asked from the following issue. I don't have any s/w with same dll file. I tried installing/uninstalling. Please, somebody, suggest a suitable solution

 [https://github.com/ContinuumIO/anaconda-issues/issues/8561#issuecomment-408424223]

![error sypder](https://user-images.githubusercontent.com/40607848/43774534-0642c970-9a67-11e8-8e0f-04b487d2d55d.jpg)

**Comment by ccordoba12** [comment]
Sorry but this is an Anaconda issue, not a Spyder one. Please continue the discussion with @mingwandroid in the issue you referenced above.
