### ISSUE TITLE
could you use setuptools instead of pure distutils.

### ISSUE THREAD

**Issue by picca** [spyder-ide/spyder#7638]
Hello,

while preparing the Debian package, I need to patch the setup.py in order to use setuptools instead of distutils.

This way the dependencies of the package are automatically generated from the seup.py requirement.

It would be great if you could considere it.

Thanks

Frederic

**Comment by ccordoba12** [comment]
Not in the cards for us, sorry. We're happy with using `distutils` for now.

**Comment by ccordoba12** [comment]
To expand a little bit: it's easier for us to handle deps with conda this way and avoiding people running `python setup.py` instead of using pip.
