### ISSUE TITLE
Include runtests.py in tarball

### ISSUE THREAD

**Issue by picca** [spyder-ide/spyder#7639]
Hello, I try to run the test during the build in order to check that everythings is fine.
But I get this

I: pybuild base:217: cd /<<BUILDDIR>>/spyder-3.3.0+dfsg1/.pybuild/cpython3_3.7_spyder/build; python3.7 -m pytest 
============================= test session starts ==============================
platform linux -- Python 3.7.0+, pytest-3.6.4, py-1.5.4, pluggy-0.6.0 -- /usr/bin/python3.7
cachedir: ../../../.pytest_cache
PyQt5 5.11.2 -- Qt runtime 5.11.1 -- Qt compiled 5.11.1
rootdir: /<<BUILDDIR>>/spyder-3.3.0+dfsg1, inifile:
plugins: xvfb-1.0.0, qt-2.3.1, flaky-3.3.0
collecting ... collected 483 items

spyder/app/tests/test_mainwindow.py::test_calltip SKIPPED                [  0%]

Then nothing....

do you have a an idea of what is going one.

Cheers

Frederic

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> python3.7 -m pytest

We don't run our tests like this. We run them with

    python runtests.py

where `runtests.py` is a script that lives in our repo. We'll add it to our tarball in 3.3.2.

**Comment by ccordoba12** [comment]
@picca, I decided to do this for 3.3.1 because it's really easy.

You need to have Xvfb installed and a window manager running on the same port Xvfb is running to successfully run our test suite. Please take a look at our Travis file for details:

https://github.com/spyder-ide/spyder/blob/master/.travis.yml

And, as I said, you need to run our suite like this

    python runtests.py

from our Spyder's root directory and `conftest.py` needs to be next to `runtests.py` (I'll add it to our tarballs too).

**Comment by picca** [comment]
Hello CArlos,

I am preparing the 3.3.1 verison for Debian,

but I end up with this issue during the test.

I used your runtest script.

Cheers

Fred


copying spyder_pylint/locale/ru/LC_MESSAGES/pylint.mo -> /<<BUILDDIR>>/spyder-3.3.1+dfsg1/.pybuild/cpython3_3.6_spyder/build/spyder_pylint/locale/ru/LC_MESSAGES
   debian/rules override_dh_auto_test
make[1]: Entering directory '/<<BUILDDIR>>/spyder-3.3.1+dfsg1'
PYBUILD_SYSTEM=custom \
PYBUILD_TEST_ARGS="{interpreter} ./runtests.py" dh_auto_test
	pybuild --test -i python{version} -p 2.7
	pybuild --test --test-pytest -i python{version} -p "3.7 3.6"
I: pybuild base:217: python3.7 ./runtests.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 372, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/<<BUILDDIR>>/spyder-3.3.1+dfsg1/spyder')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 403, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/<<BUILDDIR>>/spyder-3.3.1+dfsg1/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/_pytest/config/__init__.py", line 409, in _importconftest
    mod = conftestpath.pyimport()
  File "/usr/lib/python3/dist-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/<<BUILDDIR>>/spyder-3.3.1+dfsg1/conftest.py", line 22, in <module>
    from spyder.config.base import get_conf_path
  File "/<<BUILDDIR>>/spyder-3.3.1+dfsg1/spyder/config/base.py", line 416, in <module>
    _ = get_translation("spyder")
  File "/<<BUILDDIR>>/spyder-3.3.1+dfsg1/spyder/config/base.py", line 387, in get_translation
    language = load_lang_conf()
  File "/<<BUILDDIR>>/spyder-3.3.1+dfsg1/spyder/config/base.py", line 360, in load_lang_conf
    lang = get_interface_language()
  File "/<<BUILDDIR>>/spyder-3.3.1+dfsg1/spyder/config/base.py", line 331, in get_interface_language
    spyder_languages = get_available_translations()
  File "/<<BUILDDIR>>/spyder-3.3.1+dfsg1/spyder/config/base.py", line 286, in get_available_translations
    listdir = os.listdir(locale_path)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/spyder/locale'
ERROR: could not load /<<BUILDDIR>>/spyder-3.3.1+dfsg1/conftest.py

E: pybuild pybuild:338: test: plugin custom failed with: exit code=4: python3.7 ./runtests.py

**Comment by ccordoba12** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/spyder/locale'

It seems our translations directory is not available when you try to run `runtests.py`

**Comment by picca** [comment]
Yes this is during the build process so the files are not installed at the final location.

**Comment by ccordoba12** [comment]
Sorry but I can't help you with that. This is a Debian specific thing.

You could patch `get_available_translations` to not fail if it can't find our locale directory.

**Comment by picca** [comment]
Hello so when you run your test syou already have the locales installed on your system ?

**Comment by ccordoba12** [comment]
Yes, and that's because we need to set the language used by Spyder to English because some tests depend on it.
