### ISSUE TITLE
Tutorial is out of date and needs updating

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#7641]
## Problem Description

Currently, the tutorial is quite (years) out of date, referring to commands and menu entries whose names have since changed, devoting several sections and passages to the long-removed (non-I)Python console, recommending out of date approaches to various problems, etc. For a new user being introduced to Spyder via the tutorial, which is how many including myself took their first steps with the IDE (e.g. I just got my department to switch to Spyder for their introductory course in scientific computing, which all students are required to take in a few weeks time), this is likely to be a confusing and frustrating experience, an could even cause them to abandon it altogether and switch to another option. 

Therefore, if at all possible, it seems paramount that we should update this ASAP, preferably for 3.3.1 which will be what e.g. new students will be using at the beginning of the year and will likely be the last substantial changes in the 3.x series. I'm going to do it right now and hopefully finish in a few hours time, and for the initial pass just make in place updates to the existing content with as few non-essential changes as possible to speed up the review process, and then after that do I pass where I implement all stuff from our docs style guide and any other improvements on top of that, to try to make sure that at least the first get in on time.

**Comment by ccordoba12** [comment]
Unless you have this for today, I'll leave it for 3.3.2

**Comment by CAM-Gerlach** [comment]
Working on it as we speak. I'll have the straight updates/corrections/removals within an hour or two, and the further changes (additions, conforming to our docs style guide, etc) an hour or so after—but I can always back those out those latter changes and stick them in another branch for after the 3.3.1 release if you think they will make your review take too long.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Pushed it up, as #7643

**Comment by ccordoba12** [comment]
Fixed by #7643.
