### ISSUE TITLE
Update 4.0beta1 release date

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#7653]
Hi folks, I'm a very keen user who is chomping at the bit to try out the new code folding capability landing in 4.0. Just wondering when the beta release is expected, I see there are [5 outstanding issues remaining](https://github.com/spyder-ide/spyder/milestone/23) and hope we're soon for a release!!

**Comment by ccordoba12** [comment]
I'll try to do this release later today or tomorrow.

**Comment by ccordoba12** [comment]
This is released! Please see

https://github.com/spyder-ide/spyder/releases

to see how to install it.

**Comment by durack1** [comment]
@ccordoba12 this is great, thanks! I also dropped a new issue down at #7680, which at least for me would make using the beta release(s) easier alongside the "production" versions..
