### ISSUE TITLE
python editor not opening in spyder

### ISSUE THREAD

**Issue by diwakargautam** [spyder-ide/spyder#7658]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
not opening the python file editor while invoking same through file then new file.

**Comment by ccordoba12** [comment]
I don't understand what you mean by this, sorry. Please post a screenshot or a video of the problem you're experiencing. Thanks!

**Comment by diwakargautam** [comment]
I have installed Spyder and configured it to open notebook files of
jupyter. That  worked well ..but now my Spyder is not responding when
opening a new file from file tab.

**Comment by ccordoba12** [comment]
Sorry but you don't even mention what operating system you're using so we can't help you further.

My advice is to revert what you did so you can have the old behavior back.
