### ISSUE TITLE
Sort alphabetically or quick search in outline

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#766]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-09-22T10:08:21Z_

Spyder Version:  2.1.0beta1 

What steps will reproduce the problem?

 With overly long contents in outline it is often hard to find the stuff. It will help to add button to sort A->Z and vice versa inside the dialog. On the second thought a search form accessible with keyboard shortcut maybe even more usable.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=766_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-11-30T10:55:22Z_

issue #840 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-12-09T06:53:16Z_

issue #874 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [pmav99@gmail.com](https://code.google.com/u/pmav99@gmail.com/) on 2011-12-09T07:07:00Z_

Also, useful would be to have some shortcut-keys in order to expand/collapse the Trees to predefined levels (module, class etc).

WingIDE has a similar feature in the main editor (with code folding).

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:10:47Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by goanpeca** [comment]
@techtonik I dont think this makes sense now that we have a `Ctrl+P` [finder](https://github.com/spyder-ide/spyder/pull/2590) for the editor 

@ccordoba12 closing?

**Comment by ccordoba12** [comment]
Sure, closing.
