### ISSUE TITLE
Installation for Python 2.7

### ISSUE THREAD

**Issue by daneos** [spyder-ide/spyder#7661]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I'm unable to install Spyder with pip on Python 2.7. Spyder requires pylint which in turn requires Python 3.4. From what I found out, pylint supports only Python 3, but Spyder is supposed to support Python 2.7. Is there a way to install Spyder without pylint?

### What steps reproduce the problem?

1. `pip install spyder` on a machine with Python 2.7 only

### What is the expected output? What do you see instead?
Expected output is spyder being installed.
I see `pylint requires Python '>=3.4.*' but the running Python is 2.7.5`

## Versions

* Spyder version: 3.3.0
* Python version: 2.7.5
* Qt version: not relevant
* PyQt version: not relevant
* Operating System name/version: CentOS 7

**Comment by ccordoba12** [comment]
You're probably using a very old version of pip, unable to get the right version of pylint for Python 2.

Sorry, but this is not our fault and that's why we recommend to use Anaconda instead of any other method.

**Comment by daneos** [comment]
Yes, I'm using pip 9.0.3 since it's last version that support deprecated features we need in our setup.
Checked this with latest pip (18.0) and everything works.
Thanks for the information!
