### ISSUE TITLE
VGG16 Kernel Error

### ISSUE THREAD

**Issue by PrateekNahar** [spyder-ide/spyder#7666]
I am getting this error while executing VGG16 code on line :    

hist = custom_vgg_model.fit(X_train, y_train, batch_size=160, epochs=1, verbose=1, validation_data=(X_test, y_test))

and the error is:
An error ocurred while starting the kernel
2018󈚬󈚮 10:32:38.938180: W tensorflow/core/framework/allocator.cc:108] Allocation of 67108864 exceeds 10% of system memory.
2018󈚬󈚮 10:32:38.938180: W tensorflow/core/framework/allocator.cc:108] Allocation of 411041792 exceeds 10% of system memory.
2018󈚬󈚮 10:32:43.385434: W tensorflow/core/framework/allocator.cc:108] Allocation of 411041792 exceeds 10% of system memory.
2018󈚬󈚮 10:32:43.385434: W tensorflow/core/framework/allocator.cc:108] Allocation of 67108864 exceeds 10% of system memory.
2018󈚬󈚮 10:35:01.800351: W tensorflow/core/framework/allocator.cc:108] Allocation of 2055208960 exceeds 10% of system memory.

**Comment by ccordoba12** [comment]
Please don't report this error again. As I said to you before, this is not an error in Spyder so we can't help you with it.
