### ISSUE TITLE
Error at "static code analysis"

### ISSUE THREAD

**Issue by mescobal** [spyder-ide/spyder#7670]
## Description

**What steps will reproduce the problem?**

1. Load a python script
2. Click "Analyze" in Static Code Analysis window

**What is the expected output? What do you see instead?**
Expected: analysis performed.,
Resulto: error window with pylint related messages.

KeyError: None

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.15rc1
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.13.3 (OK)
sphinx >=0.6.6    :  1.6.7 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.5.0 (OK)
pylint >=0.25     :  1.8.3 (OK)

```

**Comment by ccordoba12** [comment]
> Resulto: error window with pylint related messages.

Please post the error messages you get. Else we can't help you.

**Comment by mescobal** [comment]
Error message transription:
-------------------------------------
No config file found, using default configuration
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/pylint/__main__.py", line 7, in <module>
    pylint.run_pylint()
  File "/usr/lib/python2.7/dist-packages/pylint/__init__.py", line 16, in run_pylint
    Run(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 1347, in __init__
    linter.check(args)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 768, in check
    self._do_check(files_or_modules)
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 883, in _do_check
    for descr in self.expand_files(files_or_modules):
  File "/usr/lib/python2.7/dist-packages/pylint/lint.py", line 922, in expand_files
    self.add_message(key, args=message)
  File "/usr/lib/python2.7/dist-packages/pylint/utils.py", line 423, in add_message
    self.stats['by_module'][self.current_name][msg_cat] += 1
KeyError: None
...................................................................

**Comment by ccordoba12** [comment]
As you can see from the error message your reported, this is a not a problem with Spyder but with Pylint. However, I can't reproduce this error using the exact same Pylint version you have.

Could you post the file you're trying to analyze and that's giving you that error?

**Comment by mescobal** [comment]
It's the same with any python file. If I run pylint from the command line (in the same directory the file is located) it runs OK. That's why I assume the error is not from pylint.

**Comment by ccordoba12** [comment]
> It's the same with any python file

Sorry, I can't reproduce this on my Linux PC. Please report this problem with the package maintainers of your Linux distro or simply switch to use Anaconda.

**Comment by mescobal** [comment]
I think I've found the problem. When I load Spyer for the first time, the combo box of "Static code analysis" (I don't know the exact translation because mine is in Spanish) is empty. Despite this, the button labeled "Analyze" is enabled (green). When I click the button without selecting the file, I get the error.
If I select a file first. Pylint runs OK.

**Comment by mescobal** [comment]
Perhaps the "Analyze button" has to be disabled until the user selects a file (I assumed that the file being analyzed was the current one in the editor).

**Comment by ccordoba12** [comment]
Thanks! We'll take a look at this in our next release.

**Comment by ccordoba12** [comment]
> Perhaps the "Analyze button" has to be disabled until the user selects a file (I assumed that the file being analyzed was the current one in the editor).

This is the case now in our latest version (3.3.1). Please update and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
