### ISSUE TITLE
TypeError: initialize() got an unexpected keyword argument 'make_current'

### ISSUE THREAD

**Issue by aidenyao** [spyder-ide/spyder#7672]
### What steps will reproduce the problem?

PYTHONPATH manager add python path:/opt/ros/indigo/lib/python2.7/dist-packages
.........................................

## Versions

* Spyder version: 3.3.0 
* Python version: 2.7.15
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Linux 4.4.0-131-generic

### Dependencies

```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.7.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
Sorry, I can't reproduce this error. Could you provide more details of how you got it?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
