### ISSUE TITLE
Use a separate configuration directory for beta and dev releases to avoid contaminating user settings

### ISSUE THREAD

**Issue by durack1** [spyder-ide/spyder#7680]
Can the *.beta releases be updated to use a different assortment of dot files, so `.spyder` could become `.spyder-beta`, this would preserve the beta alongside the current `3.3.1` release so that a production and testing environment can co-exist happily. I also wonder whether the same could be possible for the `.ipython` and `.matplotlib` subdirs?

**Comment by ccordoba12** [comment]
This is a good suggestion. @CAM-Gerlach, what do you think about it?

> I also wonder whether the same could be possible for the .ipython and .matplotlib subdirs?

This is not something Spyder should handle because it could cause more headaches than benefits. So I don't think we'd implement it.

**Comment by durack1** [comment]
@ccordoba12 glad you think it's worth considering. If they are pointing at different dirs, at least for spyder itself, then a beta user could relatively easily update to successive betas, providing feedback, but also enabling the use of the standard release

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Definitely agreed; this would be very useful to enable messing around without launching with ``--safe-mode`` all the time. Shouldn't changing the ``.spyder`` and ``.spyder-py3`` directory names to something like ``.spyder-beta`` and ``.spyder-py3-beta`` (for of Spyder 5, we can unify them, since Py2 will be dropped completely, but that's a different issue) be sufficient for now? Then for Beta 3 or whenever the project changes are implemented, we'd presumably need to change the ``.spyderproject`` name as well (or just rename it entirely).

**Comment by CAM-Gerlach** [comment]
> Yes, it should. Would you like to implement it?

Sure, I guess. Where do I make the change(s)? Do you want iit be hardcoded on ``master`` until the final release? A command line flag enabled by default for now on ``master``? Or something that automatically parses the version string to determine if the current version qualifies as a "beta"? I can also also try to add a unit test if practicable.

**Comment by ccordoba12** [comment]
> Sure, I guess. Where do I make the change; just in config/base.py or are there other places too?

I think there are no other places needed.

> Or something that automatically parses the version string to determine if the current version qualifies as a "beta"?

Exactly. That's what I'd do too.

> I can also also try to add a unit test if practicable.

Sure, it should be pretty simple: a test for `get_conf_path` should be enough.

**Comment by CAM-Gerlach** [comment]
> That's what I'd do too.

Okay, cool. That should be simple enough.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I've been finally doing the big legal housecleaning I've been planning on for a while, along with spinning up with the first day of my new research position yesterday as well as the start of classes before I do this, but with regard to the version string, should ``dev`` builds (checkouts from ``master``) also count as ``beta`` for settings isolation, or only the four released snapshots? I'd think the latter would make more sense, but its up to you what you think's best.

**Comment by ccordoba12** [comment]
> but with regard to the version string, should dev builds (checkouts from master) also count as beta for settings isolation

That would be really helpful for the dev team and I haven't thought about that! So please also make `dev` as well as `beta` to count for settings isolation.

**Comment by CAM-Gerlach** [comment]
Great, that's what I thought too (I mistyped "latter" instead of "former" above). I'll probably get to it this weekend.

**Comment by durack1** [comment]
Hi folks, I'm just pinging myself on this as I'd forgotten where this issue was living.. What are the chances this could sneak into v4.0beta2?

**Comment by CAM-Gerlach** [comment]
I can take a look at it later this evening since it seems pretty simple to do. Sorry for leaving this for so long as I was working on other projects.

**Comment by durack1** [comment]
@CAM-Gerlach no problem! I've been a reluctant tester of v4.0beta1 as it's going to mess up my envs, so was hoping this could land so I can jump into testing alongside

**Comment by CAM-Gerlach** [comment]
Heh, its already wiped all my custom keyboard shortcuts and color schemes which is what I deserve for not implementing this sooner, I guess.

**Comment by durack1** [comment]
@CAM-Gerlach, exactly, you’ve hit one of the very reasons having a different dotfile subdir is a good idea for the betas

**Comment by durack1** [comment]
@ccordoba12 @CAM-Gerlach this is great, which beta will it be released in?

**Comment by CAM-Gerlach** [comment]
@durack1 Beta 2. In the future, you can check which Spyder release any feature will be present in by looking at the Github milestone in the middle of the right sidebar.

**Comment by durack1** [comment]
@CAM-Gerlach nice, of course.. And now a question that is not answerable from the current milestone pin - when is beta2 likely to land? It's 93% complete.. https://github.com/spyder-ide/spyder/milestone/44

**Comment by ccordoba12** [comment]
We sincerely don't know. We're still dealing with some hard bugs, so it'll be ready when it's ready.

**Comment by durack1** [comment]
@ccordoba12 I thought as much.. Good luck getting it across the line.

Is there a mailing list or any subscription (other than watching this repo) that announces such releases?

**Comment by ccordoba12** [comment]
Yes, I announce new versions in our Google group:

https://groups.google.com/group/spyderlib

**Comment by CAM-Gerlach** [comment]
@durack1 You can also try it out right now by just cloning this repo, creating a new conda environment (or ``virtualenv``/``venv``, if not using Anaconda/Miniconda), and installing the dependencies with ``conda install -c spyder-ide --file requirements/conda.txt``. You can then launch Spyder by just running ``python bootstrap.py`` from the root of the repo.
