### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by p2r2** [spyder-ide/spyder#7687]
### What steps will reproduce the problem?

Spyder said 3.3.1 was available, so I opened Anaconda Prompt and ran conda update Spyder (it said it'd update to 3.3.0). Once done, I restarted Spyder, but Spyder said the kernels weren't installed, so I ran conda install spyder-kernels as directed by the error in Spyder. This caused Spyder to downgrade back to 3.2.8. I restarted, and here we are

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.5.5
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
What happens if you try to upgrade Spyder again? This error is solved precisely in 3.3.0.

**Comment by p2r2** [comment]
Good afternoon,

I ran conda update spyder again, which updated Spyder to 3.3.0 and
downgraded spyder-kernels to 0.2.4 (or something like that, I closed the
prompt before I took a note). When running spyder, it tells me 3.3.1 is
available, but ignoring that, I again have the same issue: the Console says

An error ocurred while starting the kernel
Your Python environment or installation doesn't have the spyder‑kernels module
installed on it. Without this module is not possible for Spyder to create a
console for you.

You can install it by running in a system terminal:

conda install spyder‑kernels

or

pip install spyder‑kernels

**Comment by p2r2** [comment]
Attempting to update the spyder-kernels with conda again forces spyder to downgrade to 3.2.8, as before. This works

**Comment by ccordoba12** [comment]
@jjhelmus, I think this problem is caused because you guys pushed `spyder-kernels` packages for its **1.0.1**, which is not necessary right now (it will be for Spyder 4, but for our 3 series).

Could you remove them, please?

**Comment by jjhelmus** [comment]
I'm not sure how the 1.0.1 `spyder-kernels` packages got into the channel.  My name is on the git log so it most likely was an oversight on my part.  I've revoke the packages so they are no longer considered by the solver.  Luckily it appears these were only created for Windows.

**Comment by ccordoba12** [comment]
Thanks!

>  Luckily it appears these were only created for Windows.

Yeah, that's the strangest part.

**Comment by ccordoba12** [comment]
@p2r2, could you try to update Spyder again?

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by p2r2** [comment]
Apologies, I had not realised there was a message addressed to me.
Unfortunately updating spyder does not work, nor does removing and
reinstalling it (I tried several combinations of spyder and
spyder-kernels). I also tried an installation into a fresh conda
environment, but no luck. Either the kernel failed to launch, or the
program itself got stuck, unresponsive, on a white screen at startup.
