### ISSUE TITLE
IPython console acting weird, extra lines at start up and very slow

### ISSUE THREAD

**Issue by tryfonch** [spyder-ide/spyder#7689]
Hi, I am running spyder through an anaconda environment. When my Spyder screen opens up this is how my Ipython console looks like at the startup:
![image](https://user-images.githubusercontent.com/29928641/44096958-9be7c546-9faa-11e8-84e2-1b0f2f87e58c.png)

As you can see there are 3 "ln [1]: " rows. Any clue what might be causing this?

I am also facing a very very slow ipython console startup (takes almost 1 min!) either when I open up spyder for the first time or when I restart the existing console/ open a new one in a new tab. I believe it is related with the previous issue.

* Spyder version: 3.3.0
* Spyder Kernels: 0.2.4
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Professional

**Comment by ccordoba12** [comment]
> Any clue what might be causing this?

The most probable cause for this is lack of RAM. How much RAM do you have?

**Comment by ccordoba12** [comment]
Consoles should load faster if you deactivate our Matplotlib integration in

    Tools > Preferences > IPython console > Graphics > Activate support

**Comment by tryfonch** [comment]
@ccordoba12 thanks, will give it a try and will update if it persists. May that be because of anacodna? Maybe uninstall and reinstalling it could solve the issue?!

**Comment by ccordoba12** [comment]
I doubt the problem is caused by Anaconda. If things don't improve, I'd say the problem is caused by your firwewall/antivirus getting in the way.

**Comment by tryfonch** [comment]
@ccordoba12  Thanks. closing this for now

**Comment by tryfonch** [comment]
@ccordoba12  So everything is resolved now. Had to uninstall and re-install conda. Apparently something was wrong there. It took me 40sec to activate an env, or close to 2 mins to show the packages when I tried to install something in the virt env.

After that everything seems to work fine. There is only one '[1] : ' line showing up and when I hit enter in the console it is executing instead of inserting new line (didn't mention this earlier because i thought it was a side effect of the multiple '[1] : ' lines.

Hope someone else finds this useful.

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it!

**Comment by RylandCapital** [comment]
I am having the same issue. using winnpython. I have an older version of spyder/ winpython in the same folder where the ipython console works great. after getting winpython 3.7.4 and spyder 3.3.5  now I have to wait 30+ seconds to load a console and it takes 5+ seconds execute print('hello'). spyder winnpython combo has always been great to me! any idea?
