### ISSUE TITLE
Add warning box option before closing spyder

### ISSUE THREAD

**Issue by gentillehawk** [spyder-ide/spyder#7696]
I would like ask that an option be put into spyder to enable a warning box before closing the application. This would not be enabled by default, but would add it as an option. Currently the individual console tabs have a warning before closing. I would like this functionality adding to the overall application. I have had several instances of closing spyder by accident while halfway through a 12-hour run of a script. I would like to be able to turn on a safeguard to prevent this from happening in the future.

**Comment by ccordoba12** [comment]
That option is already available. You can find it by going to the menu

    Tools > Preferences > General > Advanced Settings

and activating the option called

    Prompt when exiting

**Comment by Mezaour-younes** [comment]
I had the same issues with @gentillehawk thanks for the answer <3

**Comment by Femkemilene** [comment]
Now found under Tools > Preferences > Application > Advanced settings

**Comment by ccordoba12** [comment]
@Femkemilene, that's because you're using an old Spyder version. Please update.
