### ISSUE TITLE
Unusual characters break help

### ISSUE THREAD

**Issue by endolith** [spyder-ide/spyder#7699]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

[Weird but valid characters in function names](https://www.dcl.hpi.uni-potsdam.de/home/loewis/table-3131.html) are not recognized by Spyder so it doesn't show the docstring.

### What steps reproduce the problem?

1. Create a function with name `aaʹbb`
2. Type aa and press Tab to complete the name
3. Press Ctrl+I for help on that function.  

### What is the expected output? 

Help says "No documentation available" for object `bb`.

### What do you see instead?

It should show documentation for object `aaʹbb`

### Paste Traceback/Error Below (if applicable)

```python-traceback

def aaʹbb(a):
    """this is the docstring"""
    pass


aaʹbb
Out[3]: <function __main__.aaʹbb>

aaʹbb?
Signature: aaʹbb(a)
Docstring: this is the docstring
```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Windows 7 

### Dependencies

```
IPython >=4.0     :  6.2.1 (OK)
cython >=0.21     :  0.27.3 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.3 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in Spyder 4.

**Comment by goanpeca** [comment]
This is still an issue o Spyder 4.0

**Comment by dalthviz** [comment]
Note: with Python 3.7.6 an error raises when trying to define the function used as example

![image](https://user-images.githubusercontent.com/16781833/72548339-763bd200-385c-11ea-8c0d-0bdbe4aca06a.png)
