### ISSUE TITLE
just black window is displayed when spyder starts ?!

### ISSUE THREAD

**Issue by as4end** [spyder-ide/spyder#7701]
### What steps will reproduce the problem?

i have just installer spyder.
i have just installer spyder.

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 8

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.0 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please close Spyder, open an Anaconda Prompt, run there

    conda install pyopengl

and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
