### ISSUE TITLE
Error after upgrading to Python 3.7

### ISSUE THREAD

**Issue by subhylahiri** [spyder-ide/spyder#7721]
### What steps will reproduce the problem?

1. Upgrade to python 3.7
2. Start spyder

Issue reporter appears immediately.
Internal console says:

>>> Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\spyder\widgets\pydocgui.py", line 39, in run
    self.callback(pydoc._start_server(pydoc._url_handler, self.port))
TypeError: _start_server() missing 1 required positional argument: 'port'

I'm using Anaconda3 on Windows 10 (64bit) with Python 3.7.0, IPython 6.5.0, Spyder 3.3.1

### Traceback
```python-traceback
TypeError: _start_server() missing 1 required positional argument: 'port'
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.0 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll fix this in our next release.

**Comment by Chisuz** [comment]
so - any solutions available in november 2018? i just updated and now nothing works : (
