### ISSUE TITLE
Cmnd + I does not work

### ISSUE THREAD

**Issue by ramnikbansal** [spyder-ide/spyder#7737]
## Problem Description
Cmd +I does not open Help. Says no documentation available.
### What steps will reproduce the problem?

It works in the beginning but then stops working.

## Package Versions
* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Darwin 16.7.0

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
psutil >=0.3     :  5.4.5 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
Help doesn't work for all libraries because it has some limitations. Please post the code you're trying to get help for.

**Comment by etl17** [comment]
I am experiencing the same issue (on Ubuntu Linux). Ctrl-I doesn't work at all in the editor.
Example objects that I've tried: numpy, keras.models.Sequential, matplotlib.pyplot etc.

**Comment by ccordoba12** [comment]
@etl17, are you working on master or our latest stable release?

**Comment by etl17** [comment]
I am working on master.

**Comment by ccordoba12** [comment]
Master is semi-broken right now. Please switch to beta1 or wait until we release beta2.
