### ISSUE TITLE
The "Redo" shortcut in the Editor is not working in Spyder4.0.0.dev0

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7743]
## Problem Description

The `Redo` shortcut, which is set to default Spyder shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> in the **master** branch is not working in the Editor, but is everywhere else in the application (IPython console, Find in Files, etc...)

Note that everything is working fine in the 3.x branch, so that is probably why we haven't receive any bug reports about that yet.

The goal of this issue is to document what I'm doing in order to pinpoint and understand the issue before trying to fix it.

http://doc.qt.io/qt-5/qkeyevent.html
http://doc.qt.io/qt-5/qkeysequence.html
http://doc.qt.io/qt-5/qplaintextedit.html#editing-key-bindings
http://doc.qt.io/qt-5/qshortcut.html

## Versions

* Spyder version: Spyder 4.0.0.dev0 
* Python version: Python 3.6.5 64bits
* Qt version: Qt 5.9.3
* PyQt version: PyQt5 5.9.2 
* Operating System name/version: Windows  10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.11.0     :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.13.0 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.4.0.dev (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.2.0 (OK)
pylint >=0.25     :  1.8.3 (OK)
```

**Comment by jnsebgosselin** [comment]
Redo shortcut is is working in v4.0.0Beta1.

**Comment by ccordoba12** [comment]
Could you test before and after split-plugins was merged?

**Comment by jnsebgosselin** [comment]
@andfoy @ccordoba12 

This Issue was introduced in https://github.com/spyder-ide/spyder/commit/5abd2a27e1c30b9ab4656e5aa290e99ac15b5ccb

More specifically, this line is the culprit:
https://github.com/spyder-ide/spyder/commit/5abd2a27e1c30b9ab4656e5aa290e99ac15b5ccb#diff-b19a1c3b49c9057f7bf2edae2a53747dR2865

**Comment by jnsebgosselin** [comment]
I've done some digging and this clock code is very shady: https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/codeeditor.py#L2870

```python
        for qname, name in checks:
            seq = getattr(QKeySequence, qname)
            sc = get_shortcut('editor', name)
            default = QKeySequence(seq).toString()
            # XXX - Using debug_print, it can be seen that event and seq
            # will never be equal, so this code is never executed.
            # Need to find out the intended purpose and if it should be
            # retained.
            if event == seq and sc != default:
                # if we have overridden it, call our action
                for shortcut in self.shortcuts:
                    qsc, name, keystr = shortcut.data
                    if keystr == default:
                        qsc.activated.emit()
                        event.ignore()
                        return

                # otherwise, pass it on to parent
                event.ignore()
                return
```

I think this should be rework. When I do <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> I end up at `# otherwise, pass it on to parent`, but clearly, and I've checked, the event is not passed to the parent.

**Comment by jnsebgosselin** [comment]
According to the doc (http://doc.qt.io/qt-5/qkeysequence.html), the standard shortcuts for `Redo` are:

![image](https://user-images.githubusercontent.com/10170372/44487889-67c89700-a625-11e8-8add-9c0d413128c6.png)

**Comment by jnsebgosselin** [comment]
If my understanding of the code shown in https://github.com/spyder-ide/spyder/issues/7743#issuecomment-415144753 is correct, for any version of Spyder :

- Setting the `Delete line` shortcut to `Ctrl+C` and then<br>pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> in the editor should not work 👎  
- Setting the `Go to line` shortcut to `Ctrl+C` and then<br>pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> in the editor should not work 👎

In both cases, we enter the `if event == seq and sc != default:` code block because <kbd>Ctrl</kbd>+<kbd>C</kbd> is the default OS builtin key sequence for `Copy` and because the shortcut key sequence for the copy action in Spyder was set to something other than the default key sequence for Copy. So the `XXX` comment for this code block is wrong and should be removed.

In both cases though, we end up at `# otherwise, pass it on to parent`. On my Windows 10 laptop with PyQt5.9.2 and Qt5.9.3, the event is not handled as expected by the parent even if we ignore it and so, both cases do not work. 

One of the problem is that the line `if keystr == default:` is wrong. This condition doesn't compare the same things at all. `keystr ` corresponds to the name given to the shortcut in Spyder and `default` corresponds to the OS default sequence of keystring used to activate the `Copy` shortcut. This line should be replaced by `qsc.key().toString() == default:`. After changing this :

- Setting the `Delete line` shortcut to `Ctrl+C` and then<br>pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> in the editor should work 👍  
- Setting the `Go to line` shortcut to `Ctrl+C` and then<br>pressing <kbd>Ctrl</kbd>+<kbd>C</kbd> in the editor should not work 👎

So, the `Delete line` shortcut is now handled correctly and the action is called correctly with `qsc.activated.emit()`. For the  `Go to line`  shortcut though, we still end up at `# otherwise, pass it on to parent`. This is because this shortcut is not defined in the codeeditor class, so there is no way we can manually activate it from the editor. So we pass the event to the parent and pray for the best. On my Windows 10 laptop, this doesn't work.

@ccordoba12 could you check please what happens in Linux when you set the shortcut `Delete line` and `Go to line` to `Ctrl+C`?

**Comment by jnsebgosselin** [comment]
But, why do we even need to handle the `Qt Builtin key sequences` in the first place? Shouldn't these be handled by the `QShortcut` we are creating for each shortcut in the `CodeEditor.create_shortcuts` method? We are even creating `QShorcut` for the copy, cut, paste, undo, redo, and select all shortcut.

That would be the best... but in Windows (maybe it is the case also for Linux, I need to test it) it seems that if a shortcut is assigned a builtin qt keybindings for editing (see http://doc.qt.io/qt-5/qplaintextedit.html#editing-key-bindings for the list of keybindings), the shortcut is not activated when doing the appropriate key sequence on the keyboard. We end up in the `keyPressEvent` and we need to activate the shortcut manually if we want it to work.

When setting a `QShorcut` to a key sequence that is not a builtin keybindings, doing the appropriate key sequence is then handled directly by the shortcut and we do not even enter the `keyPressEvent`, so there is nothing to handle.

For example, if the `Copy` shortcut is set to `Ctrl+C`, the shortcut we define for `Copy` is not activated and we need to handle it in the `keyPressEvent` method override. If we set the `Copy` shortcut to `Ctrl+Shift+Y` instead, which is not in the list of builtin keybindings, and press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Y</kbd>, the event is then handled by the shortcut and we never enter the `keyPressEvent` of the codeeditor.

**Comment by jnsebgosselin** [comment]
Now, the `Redo` shortcut is a more complicated case in because it is associated with 3 different default keybindings in Windows (see https://github.com/spyder-ide/spyder/issues/7743#issuecomment-415162335), while there is only one in Linux. This is the reason why it fails currently in the master branch on Windows when this shortcut is set to `Ctrl+Shift+Z`, while it works in Linux.

In Linux, if the `Redo` shortcut is set to `Ctrl+Shift+Z` and we press the <kbd>Ctrl</kbd>+<kbd>Shift</kbd> + <kbd>Z</kbd> keys, the `event == seq ` will be `True` because the key sequence of the event matches the default keybinding for the `Redo` shortcut on Linux, and the `sc != default` will be `False` because the key sequence set for the `Redo` shortcut that is set in Spyder is the same as the OS default one. Therefore, `if event == seq and sc != default:` will be `False`, and the event will eventually be handled by `TextEditBaseWidget.keyPressEvent(self, event)`.

In Windows we have a problem because there is 3 default keybindings associated with the `Redo` shortcut. So, if the `Redo` shortcut is set to `Ctrl+Shift+Z` in Spyder and we press the <kbd>Ctrl</kbd>+<kbd>Shift</kbd> + <kbd>Z</kbd> keys, the `event == seq ` will be `True` because the key sequence of the event matches **ONE** of the default keybinding for the `Redo` shortcut on Windows. The problem occurs when evaluating `sc != default`. `QKeySequence(QKeySequence.Redo).toString()` return the keystring related to the first default key sequence listed for the `Redo` shortcut in Windows, so that `default` equals to `Ctrl+Y`. So `sc != default` will be evaluated to be True, and therefore the `if event == seq and sc != default:` will also be True and we will start looping through the shortcut defined in the codeeditor to find one whose key sequence matches that of `default`. The problem is that, the `Redo` shortcut will not match in this case because its key sequence is set to `Ctrl+Shift+Z` while `default` has a value of `Ctrl+Y`. So we end up at `# otherwise, pass it on to parent` and nothing happens...

If my understanding of the code is correct, in the latest version of the master branch:

- The `Redo` shortcut should not work 👎 in Windows with <kbd>Ctrl</kbd>+<kbd>Y</kbd>, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Backspace</kbd> if it is set to `Ctrl+Shift+Z`

- The `Redo` shortcut should work 👍 in Windows with <kbd>Ctrl</kbd>+<kbd>Y</kbd>, <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> and <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Backspace</kbd> if it is set to `Ctrl+Y`

In the later case, it works because `sc != default` will be evaluated to false and the event is handled further down the `keyPressEvent` method in `TextEditBaseWidget.keyPressEvent(self, event)`.
Any other shortcut set to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>Z</kbd> or <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>Backspace</kbd> will not work and a `Redo` action will be issued instead.

**So, setting the `Redo` shortcut to `Ctrl+Y` in Spyder is a valid workaround for this issue until this is fixed.** But the way builtin OS shortcuts are handled in Spyder is fragile and should be improved. More discussion about that will follow.

**Comment by ccordoba12** [comment]
> We are even creating QShorcut for the copy, cut, paste, undo, redo, and select all shortcut.

That was done by Steve to create an Emacs shortcut set in the future.

> So, setting the Redo shortcut to Ctrl+Y in Spyder is a valid workaround for this issue until this is fixed

I don't know about that because it changes the default behavior.

> But the way builtin OS shortcuts are handled in Spyder is fragile and should be improved.

Ok, thanks!

**Comment by jnsebgosselin** [comment]
>> We are even creating QShorcut for the copy, cut, paste, undo, redo, and select all shortcut.

> That was done by Steve to create an Emacs shortcut set in the future.

This is Ok and necessary, otherwise setting the `Copy` shortcut to something other than a OS default keysequence, like `Ctrl+Shift+Y` would do nothing.

>> So, setting the Redo shortcut to Ctrl+Y in Spyder is a valid workaround for this issue until this is fixed

>I don't know about that because it changes the default behavior.

I meant that it is a valid workaround for Windows users until the issue is resolved, I am not suggesting we actually change the default in Spyder.

Moreover, doing this in Windows doesn't change the default behavior. In Windows, when the keybinding for the `Redo` shortcut is set to `Ctrl+Y` in the `keyboard shortcut preferences` of Spyder, the`Redo` shortcut will work with `Ctrl+Shift+Z`, `Ctrl+Y`, or `Alt+Shift+Backspace` like it should by default in Windows. It is not the case though if it is set to `Ctrl+Shift+Z` due to the problems described in the comments above.

**Comment by ccordoba12** [comment]
> I meant that it is a valid workaround for Windows users until the issue is resolved, I am not suggesting we actually change the default in Spyder.

Ok, nice. Please go ahead with it then.
