### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by manzo1991** [spyder-ide/spyder#7773]
### What steps will reproduce the problem?

save the notebook via Save as... function (top right of the notebook interface)

**Comment by ccordoba12** [comment]
Moving to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-notebook #162](https://github.com/spyder-ide/spyder-notebook/issues/162) via [**ZenHub**](https://www.zenhub.com/)
