### ISSUE TITLE
Unable to launch Spyder after installing Anaconda

### ISSUE THREAD

**Issue by amitsharma23** [spyder-ide/spyder#7778]
### Problem Description
I am unable to launch Spyder after I installed Anaconda. It seems like Spyder is running in the background but it is not opening in the upfront.

### What is the expected output? What do you see instead?
Spyder should open so that I can practice machine learning but it is not happening.

## Versions
* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

## Also, I do not have any prior knowledge of programming. I just started to learn the basics of Machine Learning and found myself stuck in the very beginning. I tried executing the commands 'pip install pyqt5' and 'conda install -f zeromq pyzmq', this also didn't solve the issue. I have attached the screenshots of the Anaconda Prompt after writing these codes. 
Please guide me further so I can go ahead with my learning. 

![capture1](https://user-images.githubusercontent.com/40753294/44745163-91e9ef80-ab24-11e8-8c57-b73080c4307a.JPG)
![capture2](https://user-images.githubusercontent.com/40753294/44745352-1ccaea00-ab25-11e8-840a-1046aa076727.JPG)
![capture3](https://user-images.githubusercontent.com/40753294/44745353-1ccaea00-ab25-11e8-8ece-f5f1ebb2147b.JPG)

**Comment by ccordoba12** [comment]
When you ran

    pip install pyqt5

you most probably broke your Anaconda installation.

So please uninstall Anaconda, reinstall it again, then open an Anaconda Prompt, run there

    conda update spyder

and finally try opening Spyder again.

**Comment by amitsharma23** [comment]
I reinstalled Anaconda and typed this code and got an error. I also turned off my anti-virus and firewall this time. Please find the error report and guide me further.
![capture](https://user-images.githubusercontent.com/40753294/44812475-e2c91900-abf4-11e8-9eb9-81c6bc404035.JPG)
![capturew](https://user-images.githubusercontent.com/40753294/44812487-ea88bd80-abf4-11e8-975e-2ad33b4d64cb.JPG)

**Comment by bcolsen** [comment]
The error says that you can't connect to the Anaconda repository on the internet.

I found an answer for you and to help you with future problems I'll show you how I did it:

A quick google of CondaHTTPError brings me to here:

https://stackoverflow.com/questions/42563757/conda-update-condahttperror-http-none

Where I learn it could be a to type the command:
```
conda config --set ssl_verify no
```

Stackoverflow is a great resource for programming in general.

**Comment by ccordoba12** [comment]
After following @bcolsen's advice, you can also run

    conda install pyopengl

to see if that fixes your problem.

**Comment by amitsharma23** [comment]
I tried executing all the mentioned codes. I am not getting any http errors now but the Spyder editor is still refusing to start. Is there anything else which could be done?
![capture](https://user-images.githubusercontent.com/40753294/44945179-1ed0c980-ae01-11e8-9197-d8774b4938e3.JPG)
![captur](https://user-images.githubusercontent.com/40753294/44945181-27c19b00-ae01-11e8-9515-19bb5c4e5311.JPG)

**Comment by amitsharma23** [comment]
I deactivated them, but still,  Spyder Editor is not opening up. Even the Jupyter notebook is not working. I am able to write the codes in it but none of the codes are getting executed.
![capture](https://user-images.githubusercontent.com/40753294/44948244-c963df00-ae37-11e8-9dbe-5b4af6eacabf.JPG)
![capture1](https://user-images.githubusercontent.com/40753294/44948279-85bda500-ae38-11e8-9278-e21fe2fe7444.JPG)

**Comment by ccordoba12** [comment]
> Even the Jupyter notebook is not working. I am able to write the codes in it but none of the codes are getting executed.

I'm almost sure the problem with the notebook is the same that affects Spyder. Your other option would be to uninstall McAfee and install something else.

**Comment by amitsharma23** [comment]
Sorry for bothering you @ccordoba12 again.

Now the firewall in the system is turned off, I have uninstalled the antivirus. When I writing `jupyter notebook`, it opens up the notebook but I am unable to execute any codes. 
Also, why is it saying that the zero active kernels in the anaconda prompt? Please help me further as this is critical for me.
![capture](https://user-images.githubusercontent.com/40753294/44958925-da2e5680-af04-11e8-9865-17321ad6cfd4.JPG)

**Comment by pinkpigwombat** [comment]
Mac user, downloaded Spyder through Anaconda. Jupyter and other packages work fine, but I can't open Spyder.

I tried to remove and install back, but it still doesn't work.

Traceback (most recent call last): File "/anaconda3/bin/spyder", line 7, in from spyder.app.start import main File "/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 12, in import zmq File "/anaconda3/lib/python3.6/site-packages/zmq/init.py", line 42, in _load_libzmq() File "/anaconda3/lib/python3.6/site-packages/zmq/init.py", line 9, in _load_libzmq import sys, ctypes, platform, os File "/anaconda3/lib/python3.6/platform.py", line 116, in import sys, os, re, subprocess File "/anaconda3/lib/python3.6/subprocess.py", line 136, in import _posixsubprocess ImportError: dlopen(/anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so, 2): Symbol not found: __Py_set_inheritable_async_safe Referenced from: /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so Expected in: flat namespace in /anaconda3/lib/python3.6/lib-dynload/_posixsubprocess.cpython-36m-darwin.so

Hope someone can help me with this problem

**Comment by bcolsen** [comment]
@pinkpigwombat Google says try this:

https://stackoverflow.com/questions/50504279/spyder-startup-trouble

**Comment by ccordoba12** [comment]
Closing because this is not a Spyder problem.
