### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by hksantosh** [spyder-ide/spyder#7783]
### What steps will reproduce the problem?

1) Installed gensim
2) Start spyder ==> failed to open
3) conda upgrade --all
4) Start spyder

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.6
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.1 (OK)
sphinx >=0.6.6   :  1.7.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.2 (OK)
cython >=0.21    :  0.28.5 (OK)
qtconsole >=4.2.0:  4.4.1 (OK)
IPython >=4.0    :  6.5.0 (OK)
pylint >=0.25    :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please run

    conda remove spyder-kernels
    conda update spyder

and try again.

**Comment by hksantosh** [comment]
Worked fine! Thank you!!
