### ISSUE TITLE
Suppress ipdb output during debug

### ISSUE THREAD

**Issue by lazy2late** [spyder-ide/spyder#7787]
Is this the right place to make a feature request in spyder ide to suppress the source code echo while using ipdb (thank you for making spyder an awesome ide)?  

when i am using spyder to debug the ipdb prompt echos the source code (and a few lines below and above) please let me add a  way to suppress this source code echo.  

I am a python tutor and i really like to use sypder and ipdb to show new programmers how each line of code changes the variable values and the output of some simple loop or if statement.

Do i need to make a feature request for ipdb?

other people on stackoverflow have made this request and i agree with them:

https://stackoverflow.com/questions/44308115/suppressing-ipdb-output-in-spyder-ipython-interpreter

https://stackoverflow.com/questions/51703320/python-spyder-is-there-a-way-to-suppress-the-position-output-during-debugging?rq=1

**Comment by bcolsen** [comment]
Something like this in the appropriate spot might work:

```Python
ipdb.set_trace(context=0)
```

**Comment by bcolsen** [comment]
Nope that doesn't work.  IPython debugger doesn't allow zero context.  

I can get it down to one line though by change a couple line in spydercustomize.py:

~line 387 change to:
```python
@monkeypatch_method(pdb.Pdb, 'Pdb')
def __init__(self, completekey='tab', stdin=None, stdout=None,
             skip=None, nosigint=False, context=5):
    self._old_Pdb___init__(context=context)
```
~line 682 in the debugfile function change to:
```python
debugger = pdb.Pdb(context=1)
```

**Comment by lazy2late** [comment]
thank you for the information about ipython debugger, should i make a feature request in ipython (or ipython debugger)?

**Comment by bcolsen** [comment]
This is the file that would need to be changed:
https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py

I checked the line return logic and it returns an empty list with a context of 0, but that might break some things further down the line. 

I don't think many people would want 0 context other than Spyder users.

**Comment by ccordoba12** [comment]
@lazy2late, they will be removed in Spyder 4. For now, there's nothing we can do about it, sorry.

**Comment by lazy2late** [comment]
thank you very much

**Comment by impact27** [comment]
The echo is created in spydercustomize.py by `self.print_stack_entry(self.stack[self.curindex])`. I personally like it but there could be an option to remove the echo.

**Comment by ccordoba12** [comment]
@impact27, thanks for finding the source of the problem. I think we should remove that line and let users press `ll` or `list` on the debugger to find the current location they are placed in.

@bcolsen?

**Comment by impact27** [comment]
I disagree, my eyes have to travel much more if I have to refer to the editor each time I make a step.

**Comment by bcolsen** [comment]
I don't use debug that much(But I might use it more with all these great improvements :+1: ) but I can see both sides. 

I think we should definitely have them as an option. Maybe off by default though? The only thing I have against them is it just makes me have to go back further in the console to find the problem I was having.  

Could we have the lines displayed if the commands are entered into the console and not if hotkeys or the buttons are used?

**Comment by impact27** [comment]
We can do hidden execution to send an enable / disable command with the comms.

**Comment by impact27** [comment]
How about: no option, echo if typed in the console, and don't echo if using the buttons?
