### ISSUE TITLE
Incorrect 'local variable is assigned to but never used' warning with del in if block

### ISSUE THREAD

**Issue by H0R5E** [spyder-ide/spyder#7795]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I've noticed that the warning "local variable 'blah' is assigned to but never used' will be triggered on the edge case of a deleted variable inside an if statement. This may be a pyflakes thing, but I thought I would mention it here first.

### What steps reproduce the problem?

Consider the following function:

```
def test():
    
    if True:
        color = 1
        del color
```

The `color` variable on line 4 is highlighted as "local variable 'color' is assigned to but never used"

### What is the expected output? What do you see instead?

The warning should not be produced. If the `del` statement is replaced with `print` no warning is issued. Also, the warning is not issued if the `if` block is removed.

## Versions

* Spyder version: 3.3.1
* Python version: 2.7.14
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Windows

### Dependencies

```
IPython >=4.0;<6.0:  5.4.1 (OK)
cython >=0.21     :  0.26.1 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
matplotlib >=2.0.0:  2.0.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.20.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.5.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.6.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
```

**Comment by ccordoba12** [comment]
> This may be a pyflakes thing, but I thought I would mention it here first.

Thanls for reporting, but you're right, this a Pyflakes thing. We only the warnings/errors reported by it.
