### ISSUE TITLE
Spyder fails to start

### ISSUE THREAD

**Issue by borabosna** [spyder-ide/spyder#7797]
### What steps will reproduce the problem?

    Unzip the source package available for download on the Spyder Github repository (or clone it from Github)

    Change current directory to the unzipped directory

    Install Spyder’s requirements with:

    pip install -r requirements/requirements.txt

    Run Spyder with the command:

    python bootstrap.py

### Traceback
```python-traceback
  File "C:\spyder-master\spyder\plugins\editor\plugin.py", line 620, in report_open_file
    stat = self.main.lspmanager.start_lsp_client(language.lower())
  File "C:\spyder-master\spyder\plugins\lspmanager.py", line 712, in start_lsp_client
    language_client['instance'].start()
  File "C:\spyder-master\spyder\plugins\editor\lsp\client.py", line 130, in start
    creationflags=creation_flags)
  File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

## Versions

* Spyder version: 4.0.0.dev0 
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
sphinx >=0.6.6   :  1.7.8 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.11.0    :  0.12.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Sorry, but master is currently semi-broken (see issue #7724 for all the things that need to be done).

For now, please install our beta1 with

    pip install spyder --pre

to get our latest working code.
