### ISSUE TITLE
internal problem: plugin = mod.PLUGIN_CLASS(self)

### ISSUE THREAD

**Issue by Shanzaay** [spyder-ide/spyder#7802]
Every time i open spyder i get a pop up message "spyder has encountered an internal problem".

**And the detail of the problem is:**
plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
WARNING:traitlets:kernel died: 18.00585126876831

**What should i do to resolve it?**

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.1). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by Shanzaay** [comment]
>
> And one i run the update command i get *All requested packages already
> installed.*

yet every time i use spyder i get the same pop up message.

**Comment by ccordoba12** [comment]
Then please run

    conda remove spyder-kernels
    conda install spyder-kernels=0.*
    conda install spyder=3.3.1

**Comment by Shanzaay** [comment]
When i run this command *conda remove spyder-kernels* ...   I get this
error...

*Solving environment: failed*

*PackagesNotFoundError: The following packages are missing from the target
environment:*
*  - spyder-kernels*

**Comment by ccordoba12** [comment]
Then proceed with the other two commands.

**Comment by Shanzaay** [comment]
Problem solved. Thanks a bunch Carlos...

**Comment by ccordoba12** [comment]
Great! Thanks for letting us know about it.

**Comment by tarunbhavnani** [comment]
Thanks Carlos!
