### ISSUE TITLE
Change the way to exclude file types in Find in files

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#7803]
Right now the way to exclude file types in Find in Files is very complex because you have to create a regular expression to do it.

The idea is to simplify that process to allow users to do it in a more human way, i.e. like this

    *.js, *.json, *.html

**Comment by ccordoba12** [comment]
> Do you have a UI design in mind to achieve what you are proposing?

My plan is to maintain the current UI but that users can enter the exclude pattern in a simpler way, i.e. `*.js, *html`, etc.

Also, as your comment has proved, we'll make that option visible by default.

**Comment by aglotero** [comment]
In fact, the Finder code expects a string or a regex, there is the option to tell if you are passing a regex or a plain string, but the plain string is not working. I'm working on this :)

**Comment by ccordoba12** [comment]
@aglotero is working with me on this as part of the SciPyLA sprints, taking place in Curitiba, Brazil.
