### ISSUE TITLE
Stopping a search using FindInFiles freezes the app

### ISSUE THREAD

**Issue by aglotero** [spyder-ide/spyder#7804]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When you use FindInFiles on a directory with huge files or a lot of files, the stop button does not stop the Find, crashing the IDE.

### What steps reproduce the problem?

1. Open Spyder
2. Set FindInFiles to look on a directory with huge files or with a lot of files
3. Start a search
4. Stop de search

### What is the expected output? What do you see instead?
The expected output is the search being stopped and the result list with partial results.
I'm getting a frozen window and a message from Ubuntu to close or wait for the app.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by aglotero** [comment]
There are some places where `self.stopped = True` is needed, I'm working on a fix :)

**Comment by derek-v-s** [comment]
This still happens if it's set to "Current working directory".

Python 3.7.3 64-bit | Qt 5.13.1 | PyQt5 5.13.0 | Linux 5.2.11-1-default 

Installed via zypper on openSUSE Tumbleweed.
