### ISSUE TITLE
Some modules are not imported in the console

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#781]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-03T11:09:28Z_

Spyder Version:  2.1.0beta3
Python Version:  2.6.1
Qt Version:      4.7.3, PyQt4 (API v1) 4.8.5 on Windows 

What steps will reproduce the problem?
1. Execute a file in the console that has "import ctypes" What is the expected output? What do you see instead? Traceback snippet:
   import ctypes
   File "C:\Python26\lib\ctypes__init__.py", line 10, in <module>
     from _ctypes import Union, Structure, Array
   ImportError: DLL load failed: The specified module could not be found.

Script should run as expected without this import error. 

Please provide any additional information below

. I just updated to spyder 2.1.0beta3 reset my spyder ini, so not sure exactly what the culprit is.  I was able to run file that import ctypes last week.

I also have a colleague facing a similar issue where when executing in spyder the script is unable to import a usb module from site-packages.  In both cases the script works fine from the command line or in other editors.  My colleague is still using spyder 2.0.12.

Any thoughts?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=781_

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-10-03T22:26:01Z_

Have you tried comparing sys.path and interpreter location for both cases?

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-04T07:45:48Z_

Differences in sys.path:
Spyder: c:\python26\lib\site-packages and c:\Python26\lib\site-packages.  Would this somehow cause a conflict?  There is also the inclusion of the path of the currently executing script, which seems fine.

How do I check the interpreter location for Spyder?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T07:43:20Z_

You may also try to compare contents of sys.modules on both cases.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-07T08:17:24Z_

Okay, there's a TON of stuff missing from sys.modules when I execute under spyder.
spyder's list:
spyderlib.widgets.externalshell.cPickle
functools
win32security
ctypes.os
spyderlib.utils.bsdsocket
encodings.encodings

When running at the command line there are 40 modules versus the 6 when running from spyder.  Why would all these modules be missing when executing under spyder?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T14:25:44Z_

I'm getting tons of modules with sys.modules inside Spyder.

You can check your intepreter location in Tools > Preferences > Console > Advanced settings > Python executable. Maybe there lies your problem, I mean on using a different interpreter for Spyder instead of your regular one.

**Summary:** Some modules are not imported in the console  
  **Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-07T14:31:12Z_

I have two machines with spyder 2.1.0beta3.  One machine exhibits this problem while the other does not.  On both machines Tools > Preferences > Console > Advanced settings settings are identical, so the issue must lie elsewhere.  Any more ideas?

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T15:14:57Z_

How did you install Spyder? Using python setup.py install for both machines? Or did you use Pythonxy?

I'm curious because I've only used the last alternative (and probably also Pierre) but maybe there are some unnoticed problems with the first one (like this one).

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-07T15:23:53Z_

I installed both via the installer: spyder-2.1.0beta3_py26.exe

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-07T15:30:11Z_

Also, now that I've reset my ini while looking into 754 this issue has gone away.  It appears somehow they affect each other.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-07T15:35:50Z_

Alright, so luckily I had made some copies of my ini file.  I found what's breaking the console for me.  This whole case sensitivity problem has been causing other problems that I have mentioned before: Issue `#634` and Issue `#612` Working: pythonexecutable = u'C:\\Python26\\pythonw.exe'
broken:  pythonexecutable = u'c:\\python26\\pythonw.exe'

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-08T07:11:48Z_

This is really strange as I don't see any code fragment in Spyder that would change this option value to lower case...

By the way, I see that the executable is 'pythonw.exe' and not 'python.exe'. This has nothing to do with this issue but it is not a good thing at all for Spyder's internals. I should do something to avoid this.
With recent changes hiding automatically the parent console, you are supposed to run Spyder with python.exe

**Labels:** OpSys-Windows

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-08T07:14:23Z_

Regarding the Python executable name, see this: https://code.google.com/p/spyderlib/issues/detail?id=794

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T01:00:12Z_

Oh, I suddenly remembered that the os.path.normcase function is used at different places in Spyder's code and -on Windows platforms- it converts the path to lowercase!
I'm sure that's the cause of all these issues. I'll check it out.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T01:10:15Z_

False alarm... I don't see anything relevant regarding the os.path.normcase use...

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T01:20:44Z_

I really don't understand what's going on here: I search everywhere in the code the reason why this option (console/pythonexecutable) could be converted to lowercase at some point and found nothing relevant.

Did you change this option through the preferences dialog box?

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-11T07:51:38Z_

I have never changed this setting as I had no reason to.  There is definitely something  happening internally with the case of file names.  I've seen this kind of behavior before per Issue `#612` and Issue `#634` .

**Comment by ccordoba12** [comment]
Closing, very old bug.
