### ISSUE TITLE
Unable to execute codes in Jupyter Notebook

### ISSUE THREAD

**Issue by amitsharma23** [spyder-ide/spyder#7814]
## Problem Description
After Installing Anaconda, I am not being able to execute any codes in Jupyter.

### What is the expected output? What do you see instead?
A code should execute but Jupyter is not responding to any of the codes. I have added screenshots of my Jupyter screen which shows that the codes are not being executed. I have also added the screenshots of the Anaconda Prompt after typing `jupyter notebook`.
Note - I have turned off my firewall and I also do not have any anti-virus software in my system.

## Versions
Spyder version: 3.2.8
Python version: 3.6.5
Qt version: 5.9.5
PyQt version: 5.9.2
Operating System name/version: Windows 10

![capture](https://user-images.githubusercontent.com/40753294/44954541-e2fd3900-aec0-11e8-9114-fcc4b78ad776.JPG)
![capture1](https://user-images.githubusercontent.com/40753294/44954543-e2fd3900-aec0-11e8-81f1-ba92c70a3794.JPG)

**Comment by ccordoba12** [comment]
As I told you before, this is neither a problem with Spyder or the Jupyter notebook. It's a problem with your computer.

So, please don't open more issues about this and try to figure it out by yourself. As I also told you, I would remove my current antivirus and try to install a simpler one, or just an antivirus.
