### ISSUE TITLE
Debug Multiprocessing program - Spyder Internal Error

### ISSUE THREAD

**Issue by BabluTed** [spyder-ide/spyder#7825]
When debug the Multiprocessing program, Spyder internal error raised
ValueError: Invalid Signature: b'3a5019894f6550eb8be65348d9c77af4075e41dfea276b1b436f366a292369f3'

**Comment by ccordoba12** [comment]
Please provide a simple and reproducible example that generates this. This way we can test it and reproduce it in our side.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
