### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by xjliugit** [spyder-ide/spyder#7828]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
After update all packages in anaconda3
run spyder directly from command
 then error happen.

from the detail a message shows:
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

**Comment by ccordoba12** [comment]
You need to close Spyder, open an Anaconda prompt, run there

    conda remove spyder-kernels
    conda install spyder-kernels=0.*
    conda update spyder

to fix this.
