### ISSUE TITLE
ipython control-r history search not working

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#783]
_From [dallas.m...@gmail.com](https://code.google.com/u/110563883795311213368/) on 2011-10-04T12:54:57Z_

What steps will reproduce the problem?

 1. ipython console in 2.0.12
2. Control-R history search in ipython console 3. What is the expected output? What do you see instead? Should pass Control-R to ipython and start history search.  Instead, it prints a special character to the console.  Control-D does what I expect: asks to terminate session. What version of the product are you using? On what operating system? 2.0.12
Gentoo 

Please provide any additional information below

.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=783_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T08:00:22Z_

I can't find anything on this neither in the discussion group or in the GoogleCode issues but I'm sure that this is a known bug and that there is no easy solution to this.

Anyone else can help?

**Comment by spyder-issues-migrator** [comment]
_From [dallas.m...@gmail.com](https://code.google.com/u/110563883795311213368/) on 2011-10-06T11:12:29Z_

Should the spyder ipython console act like the a stand-alone ipython console, or should I expect some key-bindings are different?  Does spyder pass the key strokes directly to ipython?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-06T13:52:07Z_

Actually IPython is executed as every other Python script is executed in Spyder's external console (although a few tricks were necessary to make it work). I really don't know about this shortcut but my guess it that it relies on a part of terminal emulation that Spyder do not handle, that's all. But I would have to dig deeper to answer you properly.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-06T20:37:27Z_

This is an exclusive feature of real terminals in Linux (i.e. konsole, gnome-terminal, xterm, etc). I don't know if this works on Windows.

That's why Spyder doesn't have it and even ipython qtconsole doesn't emulate it. Maybe it could be developed as an enhancement but I don't see much of a point to it, because we have the History plugin, where you can search your entire command history.

**Labels:** Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-09T07:25:16Z_

I agree with you Carlos.

**Status:** WontFix

**Comment by foobarbecue** [comment]
This is a crucial part of my ipython workflow. I probably press control-r three times as often as I type a new command, because most new commands are variants of something I've written at some point in the past. I've been trying to get into using Spyder and the lack of this feature is the major thing keeping me away at the moment.

**Comment by ccordoba12** [comment]
@foobarbecue, this is not our fault. It's just not implemented in the Jupyter qtconsole, someone will have to do it :-)

**Comment by foobarbecue** [comment]
Ah. I see. I'd never actually used the qtconsole outside of Spyder so I figured it was part of Spyder.

**Comment by ccordoba12** [comment]
Nop, it isn't :-) It lives here:

https://github.com/jupyter/qtconsole
