### ISSUE TITLE
Inconsistent behavior with creating/saving files with default names

### ISSUE THREAD

**Issue by zapcity** [spyder-ide/spyder#7831]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Creating a new file (after restarting spyder) when a tab with a default file name 'untitled0.py' already exists as a tab, creates a new tab with the name 'untitled0.p - untitled0.py' which points to 'untitled0.py' on disk. When the new tab content is saved, it will overwrite the content of the original file on disk.

### What steps reproduce the problem?

1. Remove all tabs within spyder
2. Create a new file and leave the default name as unititled0.py
3. Close spyder and restart
4. The tab 'untitled0.py' should be showing by default (normal behavior)
5. Click "New file". This will create a new tab called 'untitled0.py - untitled0.py' (unexpected behavior)
6. When you click the 'untitled0.py - untitled0.py' tab, python shows that it is pointing to 'untitled0.py' on disk. In addition, the tab 'untitled0.py' for some reason gets renamed to 'untitled0.py - untitled0.py'. So now you have two tabs with the name 'untitled0.py - untitled0.py' (unexpected behavior)
7. When saving the content of 'untitled0.py - untitled0.py', it overwrites the content of 'untitled0.py' on disk (unexpected behavior)
8. The above behavior occurs for tabs named untitled2.py, untitled3.py etc, but not for tabs with non-default user defined names.

### What is the expected output? What do you see instead?

Irrespective of what tabs are open, and what they are named, pressing 'New file' should create a tab with a unique name, which ideally does not reference a file on disk within the default save path. 

In its current state, if a tab called 'untitled0.py - untitled0.py' is created, then it should create a file called 'untitled0.py - untitled0.py' when saved, but not overwrite 'untitled0.py' as it does now.

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.6
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Windows 10 Version 1709 (OS Build 16299.611)

### Dependencies

IPython >=4.0     :  6.2.1 (OK)
cython >=0.21     :  0.28.1 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.1 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
This is low priority for us.

**Comment by ccordoba12** [comment]
@steff456, please take a look at this one.
