### ISSUE TITLE
Drag and Drop with # or ^ doesn't work

### ISSUE THREAD

**Issue by SteffenZienert** [spyder-ide/spyder#7834]
### What steps will reproduce the problem?

1. Have a text file with # or ^ in the filename, like '#Test.py'
2. Try to Drag & Drop it in the Editor panel in spyder

I can open the file normaly through the Open File dialog (Ctrl + O), so it seems to be a problem only with the Drag & Drop feature.
I use Spyder 3.3.1 with anaconda on a Win10 64bit machine. The issue persists on a different Win10 64bit machine with WinPython.

### Traceback
```python-traceback
  File "C:\Users\HLO\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2397, in dropEvent
    files = [f for f in files if encoding.is_text_file(f)]
TypeError: 'NoneType' object is not iterable
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This problem was already fixed.
