### ISSUE TITLE
my spyder compiler is freezing. plz help!!

### ISSUE THREAD

**Issue by sayak-roman** [spyder-ide/spyder#7839]
## Description I'm have windows 10 64bit. I downloaded the latest the latest version of spyder ie Python 3.2.8 and the compiler freezes after Ipython console shows up.

**What steps will reproduce the problem?**

1. I switch on on spyder
2. everything goes fine until the 'connecting to kernel version' shows up
3. everything freezes except for the menu bar after the IPython console shows up

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.5
* Qt Versions: 5.9.4, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)

```

**Comment by sayak-roman** [comment]
@ccordoba12 here is the screenshot
![screenshot 2](https://user-images.githubusercontent.com/42074173/45249351-b6bc3f00-b33c-11e8-9bb9-66a8d1eccfd2.png)
everything freezes except for the menu bar. pls help sir.

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by mmagnuski** [comment]
I can confirm this solves the problem! :+1:

**Comment by mmagnuski** [comment]
although I am now having the same (similar?) problem when using spyder-notebook: the notebook would freeze every 2-3 minutes and unfreeze after something like 10-15 seconds.
