### ISSUE TITLE
Network printers are not listed in File > Print

### ISSUE THREAD

**Issue by BrendanMD** [spyder-ide/spyder#7841]
Can not print my python source from the main Spyder menu (File >> Print) because network printer is not listed in the "Name" drop-down. I can only print to a file. Other applications (e.g.Firefox) do list the network printer.

spyder             3.3.1            py36_1
python            3.6.4            hc3d631a_3
qt                    5.6.2            hd25b39d_14
pyqt                5.6.0            py36h0386399_5

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
NAME="Ubuntu"
VERSION="14.04.1 LTS, Trusty Tahr"

**Comment by ccordoba12** [comment]
I don't know how to fix this and it's very low priority for us. So for now you can print to a pdf file and then print from there to your network printer.

**Comment by BrendanMD** [comment]
Likely an issue with qtpy, not spyder.

**Comment by BrendanMD** [comment]
More likely a cups issue with qt, or perhaps anaconda did not compile qt with cups support. In either event not a Spyder bug. Closing issue.
