### ISSUE TITLE
Set data structure type is not supported in Variable Explorer

### ISSUE THREAD

**Issue by adodell** [spyder-ide/spyder#7843]
I have noticed that the Set data structure that is built into the Python language is an "Unsupported Data Type" for Spyder, and thus I cannot see it in the Variable Explorer if I have a set defined.

Below are two pictures showing this...

---------------------------

![spyderset1](https://user-images.githubusercontent.com/11433737/45173566-6ec2de00-b1bd-11e8-9ca2-d2692b10cc06.PNG)

---------------------------

![spyderset2](https://user-images.githubusercontent.com/11433737/45173567-6f5b7480-b1bd-11e8-9b59-c5f0e839007b.PNG)

---------------------------

I am using Spyder 3.3.1, Python 3.6.6, IPython 6.5.0

I know a similar problem exists for Numpy Arrays which is going to be fixed in Spyder 4. Will this issue regarding Sets also be fixed in Spyder 4? Has this issue been brought to the Spyder team's attention?

Thanks!

**Comment by Prikers** [comment]
This has been fixed in through #5230 and it is available in v4.0beta1
