### ISSUE TITLE
Add a "Copy to clipboard" button to the "About Spyder" window

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7844]
## New Feature Description

I propose that we add a `Copy to clipboard` button in the `About Spyder` dialog window, like we have already in the `Dependencies` dialog window.

I suggest that we copy the information with already the right format so that those can be copied directly in the `Version` section of our issue template.

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 
 
![image](https://user-images.githubusercontent.com/10170372/45179757-65e70200-b1e7-11e8-9971-af5b4b6cc481.png)

**Comment by bcolsen** [comment]
I think this would be much better than what have now.

I to simplify thing further could we have the about copy button pull in the dependencies as well. then there is only one instruction: click button in about, then paste here.

**Comment by ccordoba12** [comment]
I agree with this change too.
