### ISSUE TITLE
Code folding cells

### ISSUE THREAD

**Issue by fgiaret** [spyder-ide/spyder#7846]
Hi, I hope this is the right place to ask this kind of questions. I'm currently using Spyder 4.0.0b1 and I find the code folding feature very useful: is it possible to define regions in code, in a way similar to C#? 

#region
//some methods
#endregion

If it doesn't already exist, I think that such a feature would be very useful to organise bigger projects.
Thanks!

**Comment by ccordoba12** [comment]
> is it possible to define regions in code, in a way similar to C#?

Yes, you can. In our case (this works in Spyder and also in PyCharm) is

#%%
code
#%%

However, they can't be folded. Is that what you need?

**Comment by fgiaret** [comment]
Yes, if sections defined by #%%...#%% were foldable/unfoldable, that would be exactly what I meant.

**Comment by fgiaret** [comment]
Great, thank you very much!

**Comment by bcolsen** [comment]
I like this :+1:  

I think it would be really great if they respected the code cell levels like the outline explorer with  `#%%%` as a sub cell that would get folded when the top level folds.

**Comment by MadsMohr** [comment]
Also looking for this feature! would be very nice.

**Comment by jamesdgessel** [comment]
Also hoping for this feature!!! Would be amazing.

**Comment by ccordoba12** [comment]
I think this is going to be solved in 4.2, thanks to the work @andfoy is doing in PR #13109.
