### ISSUE TITLE
Problem with shortcuts using the "Shift" and another key

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7854]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

As mentioned in https://github.com/spyder-ide/spyder/pull/7768#issuecomment-418938416, it is not possible to assign a key sequence using Shift and another key in Spyder.

![image](https://user-images.githubusercontent.com/10170372/45237098-b9bb1f00-b2ab-11e8-9780-99b6d7110780.png)

Unfortunately, 4 shortcuts use this by default in Spyder :

![image](https://user-images.githubusercontent.com/10170372/45237130-d6efed80-b2ab-11e8-8fab-71125ed687fa.png)

This means that if one binds `Ctrl+Y` to the `clear line` shortcut for example, they won't be able to use the `Shift+Esc` sequence elsewhere or even to revert to the `Shift+Esc` afterwards for the `clear line` shortcut, unless they reset all shortcuts to their default key sequences. 

So, I think we need to change a little bit this rule and add exceptions to it, so that one can use `Shift+Enter`, `Shift+Delete`, `Shift+Insert`, etc as valid shortcut key sequences.

**Comment by ccordoba12** [comment]
We added that restriction because we were unable to find a way to use `Shift+<any key>` unless they are hard-coded in the Editor.

However, that situation could have changed due to your latest work.

**Comment by jnsebgosselin** [comment]
> We added that restriction because we were unable to find a way to use Shift+<any key> unless they are hard-coded in the Editor.
>
>However, that situation could have changed due to your latest work.

OK, I understand.

It is still the case for global shortcuts, but my latest work has solved that for the editor.

So maybe we can tweak the restriction a little bit to allow Shift+<any key> to work for the editor, but not everywhere else?

**Comment by ccordoba12** [comment]
Ok, I agree with that.
