### ISSUE TITLE
Nbconvert 5.4.0 breaking mainwindow notebook test due to change in output file text

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#7856]
## Problem Description

Currently,  ``test_open_notebooks_from_project_explorer`` in ``mainwindow.py`` is failing on the pip build of Py3.6 Linux on Travis. The apparent cause is the new version of ``nbconvert``, 5.4.0, which adds a shebang line at the top of the output Python file that results in the failing, as it checks for the file exactly matching the expected text which doesn't include the shebang. Should this be fixed in a straightforward manner (checking for the text including the shebang if e.g. ``nbconvert.__version__ >= 5.4.0``), or is there a more robust way we should handle this that won't break in the future if something else changes?

**Comment by ccordoba12** [comment]
> Should this be fixed in a straightforward manner (checking for the text including the shebang if e.g. nbconvert.__version__ >= 5.4.0)

That's what I was planing to do. Do you want to submit a PR for it?

**Comment by CAM-Gerlach** [comment]
I would, but if you were already going to do it, go ahead with it—the test apparently doesn't work on Windows so I can't test it locally unless I switch to my Linux box.
