### ISSUE TITLE
Where is "runtime-dir/kernel-pid.json" file?

### ISSUE THREAD

**Issue by jsh9** [spyder-ide/spyder#7861]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am following the steps in the documentation (https://docs.spyder-ide.org/ipythonconsole.html#connect-to-an-external-kernel) to try to open up an ipython kernel on my remote computer and then access it from my local computer.

I used `ipython kernel` on my remote computer, and saw the following message on the terminal:
```
NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

To exit, you will have to explicitly quit this process, by either sending
"quit" from a client, or using Ctrl-\ in UNIX-like environments.

To read more about this, see https://github.com/ipython/ipython/issues/2049


To connect another client to this kernel, use:
    --existing kernel-17928.json
```
This step in the documentation ("Make sure to copy the connection file (runtime-dir/kernel-pid.json) to the machine you’re running Spyder on (if remote) or note its location (if local).") requires me to find the location of `kernel-17928.json`, but I don't know where this json file is on my remote computer.

## Versions

* Spyder version: 3.3.1 (remote) and 3.3.0 (local)
* Python version: 3.6
* Qt version: 5.9.6 (remote) and 5.6.2 (local)
* PyQt version: 5.9.2 (remote) and 5.6.0 (local)
* Operating System name/version: macOS (remote), Windows (local)

**Comment by ccordoba12** [comment]
Moving to the right repo.

**Comment by ccordoba12** [comment]
Issue moved to [spyder-ide/spyder-docs #78](https://github.com/spyder-ide/spyder-docs/issues/78) via [**ZenHub**](https://www.zenhub.com/)
