### ISSUE TITLE
The "Next word" and " Previous word" shortcuts do not work as expected

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#7872]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The `Next word` and `Previous word` shortcut call the `End of word` and `Start of word` actions instead of `Next word` and `Previous word`.

This error occurs in the 3.x and master branch and is is due to an error [here](https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/sourcecode/codeeditor.py#L599) in the code for the 3.x and [here](https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/codeeditor.py#L546) for master:

The `StartOfWord` and `EndOfWord` variable name should be replaced by `PreviousWord` and `NextWord`

Also, a test should be added to catch this error. This is problematic however because, as explained in #7853, both shortcuts use the `Meta` key by default in the key sequence. So this would have to be changed also as part of fixing this.

**Comment by jnsebgosselin** [comment]
I would replace the default key sequence for these 2 shortcuts like this :

Next word: `Meta+Right` -> `Ctrl+Right`
Previous word: `Meta+Left` -> `Ctrl+Left`

Which are the default key sequence for all OSes but macOS:

http://doc.qt.io/qt-5/qkeysequence.html#standard-shortcuts
![image](https://user-images.githubusercontent.com/10170372/45301720-7ea13180-b4df-11e8-99c0-701e2420eb86.png)

**Comment by ccordoba12** [comment]
Ok, thanks a lot. Please work on this for Spyder 3.

**Comment by jnsebgosselin** [comment]
@ccordoba12 
I think we should do 2 PR to fix this if this is possible. 

In a PR based against 3.x, we should only replace the `StartOfWord` and `EndOfWord` variable name by `PreviousWord` and `NextWord`. Due to the situation with builtin shortcuts in 3.x, I'm not sure it is worth doing more than that.

In another PR based against master, I think we should:
1. replace the `StartOfWord` and `EndOfWord` variable name by `PreviousWord` and `NextWord`
2. change the default key sequence for the 2 shortcuts.
3. add a test

**Comment by ccordoba12** [comment]
> I think we should do 2 PR to fix this if this is possible

Agreed with your plan :+1:
