### ISSUE TITLE
Error when closing dataframe while data is being fetched

### ISSUE THREAD

**Issue by manmartgarc** [spyder-ide/spyder#7880]
### What steps will reproduce the problem?

I was using the data viewer to open a pandas DataFrame with shape = (1788, 3), after I closed the data viewer, this error appeared.

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\dataframeeditor.py", line 513, in <lambda>
    lambda val: self.load_more_data(val, rows=True))
NameError: free variable 'self' referenced before assignment in enclosing scope
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.8 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
Note: This happens when users are scrolling a big dataframe and closing it before it gets all the data that's being fetched.

**Comment by ccordoba12** [comment]
@juanis2112, this is an easy one for you. Please enclose the entire contents of the `load_more_data` method, placed here:

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/variableexplorer/widgets/dataframeeditor.py#L512

in a `try/except NameError` block.

And also do the same for the `load_more_data` method in arrayeditor, here:

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/variableexplorer/widgets/arrayeditor.py#L420
