### ISSUE TITLE
Error while restarting kernel

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#7882]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I restart my kernel I get this error:

```python-traceback
Traceback (most recent call last):
  File "/home/user/spyder/spyder/plugins/ipythonconsole/plugin.py", line 1661, in restart_kernel
    stderr = self.get_stderr_file_handle(stderr_file)
AttributeError: 'IPythonConsole' object has no attribute 'get_stderr_file_handle
```

I think there shouldn't be a `self` in there. But when I fixed that, then I get:
```python-traceback
Traceback (most recent call last):
  File "/home/bcolsen/spyder/spyder/plugins/ipythonconsole/plugin.py", line 1663, in restart_kernel
    client.restart_kernel(stderr=stderr)
TypeError: restart_kernel() got an unexpected keyword argument 'stderr'
```
`client.restart_kernel` doesn't have any args so I'm not sure what this code is supposed to do.

I think #7829 was the last PR in this section.

### What steps reproduce the problem?

1. restart the kernel

### What is the expected output? What do you see instead?

doesn't restart

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "/home/user/spyder/spyder/plugins/ipythonconsole/plugin.py", line 1661, in restart_kernel
    stderr = self.get_stderr_file_handle(stderr_file)
AttributeError: 'IPythonConsole' object has no attribute 'get_stderr_file_handle

```

## Versions

* Spyder version: 4.0.0.dev0 (Commit: 39245fb) 
* Python version: 3.6.5 64-bit
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Linux

### Dependencies

``` 
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
psutil >=0.3      :  5.4.6 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
I don't understand why our tests didn't detect this regression. But I'll fix it today for sure.

**Comment by bcolsen** [comment]
I had a look at the test. It looks like it only covers `Client.restart_kernel` which work fine.

**Comment by ccordoba12** [comment]
I see, so we need to test also at the plugin level.

Since I was the one who wrote that test, shame on me ;-p
