### ISSUE TITLE
numpy.set_printoptions formatter keyword has no effect on output

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#7885]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

IPython console in Spyder ignores formatter parameter settings in np.set_printoptions. I'm trying to suppress scientific output when examining variables in the REPL. The code below demonstrates the problem. 

### What steps reproduce the problem?
Execute the following code 
. 
>>> import numpy as np
>>> a = np.array([123412341234.123412341234])
>>> a
 array([1.23412341e+11])    <--- as expected, so far so good!

>>> np.set_printoptions(suppress=True,formatter={'float_kind':'{:0.2f}'.format})
>>> a
array([1.23412341e+11])   <---- Should not use exponential output

>>> print(a)
[1.23412341e+11]    <--- Incorrect, should not have exponent

This is an example. Formatters for int, etc do not alter the output. For example {'all':'hi'.format} should just print out 'hi' for any value, but does not.

### What is the expected output? What do you see instead?

The example above shows what I see. Below is what happens if I run an IPython console from the command line, or the Jupyter QtConsole from Anaconda Navigator:

>>> import numpy as np
>>> a = np.array([123412341234.123412341234])
>>> a
 array([1.23412341e+11])   

>>> np.set_printoptions(suppress=True,formatter={'float_kind':'{:0.2f}'.format})
>>> a
array([123412341234.12])      <---- this is correct, no exponent
>>> print(a)
[123412341234.12]                <----- correct

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.1
* Python version:  3.6.5 64 bits
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Windows 7
Numpy version: 1.14.2

### Dependencies

IPython >=4.0     :  6.3.1 (OK)
cython >=0.21     :  0.28.1 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.2 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.8.4 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by ccordoba12** [comment]
Note: This probably needs to be fixed in `spyder-kernels`.
