### ISSUE TITLE
spyder incompatibility with tensorflow

### ISSUE THREAD

**Issue by Art31** [spyder-ide/spyder#7893]
## Description

**What steps will reproduce the problem?**
OS: windows 10
1.  installing tensorflow 1.9
2. installing spyder 3.2
3. running spyder

**What is the expected output? What do you see instead?**
it is expected to run normally but it bugs on the first screen

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.6
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.15.1 (OK)
sphinx >=0.6.6   :  1.7.9 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.12.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.4.1 (OK)
IPython >=4.0    :  6.5.0 (OK)
pylint >=0.25    :  2.1.1 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.1). Please update by opening the Anaconda Prompt and running there

    conda update spyder
