### ISSUE TITLE
Save used command line options per script

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#790]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-10-07T11:28:16Z_

What is the expected output? What do you see instead? I'd like for spyder to retain a history of the command line arguments used to run scripts (per script) so I can easily swap between different sets of arguments and easily craft new ones from prior ones. What version of the product are you using? On what operating system? spyder 2.1.0beta1, python 2.6.1, WinXP SP3

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=790_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T14:01:21Z_

Good point and I don't think too hard to implement

**Summary:** Save a record for command line options per script  
  **Labels:** -Type-Defect Type-Enhancement Cat-Console

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-10-07T14:01:57Z_

**Summary:** Save used command line options per script

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-10-11T10:39:28Z_

This is a good idea.
I'm scheduling this for v2.2 as I'm currently struggling to fix the last bugs before releasing v2.1 final.

If I have (or if anyone else has) some time, maybe it will be taken care of in v2.1 anyway.

**Status:** Accepted  
  **Labels:** Milestone-Release2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:49:40Z_

**Labels:** -Milestone-Release2.2 Milestone-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:58:38Z_

**Labels:** -Milestone-v2.2 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T14:14:09Z_

**Labels:** -Type-Enhancement Type-Enh

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-02-11T08:58:17Z_

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-05-11T06:00:54Z_

**Labels:** -MS-v2.3 MS-v2.4

**Comment by goanpeca** [comment]
@blink1073  isnt this already fixed?

**Comment by ccordoba12** [comment]
Yes, this is fixed now.
