### ISSUE TITLE
functionality for don't flash output of cells

### ISSUE THREAD

**Issue by M-Younus** [spyder-ide/spyder#7900]
Please add functionality for don't flash output of cells like in notebooks whenever we reopen the notebook it contain previous outputs.
Thanks

**Comment by ccordoba12** [comment]
Sorry, we can't include outputs as part of the code you run by default. But you can save the state of the console at any point by doing what is mentioned here:

https://stackoverflow.com/questions/28229010/how-can-save-to-file-the-on-screen-output-of-a-python-ide
