### ISSUE TITLE
Qt4 is mistakenly an option in graphics preferences

### ISSUE THREAD

**Issue by hiccup7** [spyder-ide/spyder#7903]
## Problem Description
PyQt4 support was removed in https://github.com/spyder-ide/spyder/issues/6889
However, Qt4 is still an option is Spyder v3.3.1.
See Tools > Preference > IPython console > Graphics tab > Backend

**Comment by ccordoba12** [comment]
The fact that Spyder doesn't work anymore with Qt4 doesn't mean that people can't use Spyder to create applications with PyQt4 or use the Matplotlib Qt4Agg backend.

That's why that option was not removed when we removed support for PyQt4.
