### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by tanthiamhuat** [spyder-ide/spyder#7909]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I am trying to connect to connect to remote ipython kernel.
Step 1) Generate json file with %connect_info
Step 2) Connect to that json file with password

**Comment by ccordoba12** [comment]
Please read our docs on how to do it:

https://docs.spyder-ide.org/ipythonconsole.html#connect-to-an-external-kernel
