### ISSUE TITLE
Default language of Spyder

### ISSUE THREAD

**Issue by Gotfeurdom** [spyder-ide/spyder#7911]
I just installed Anaconda and opened Spyder
Anaconda language is english while Spyder's is french
My OS is also in english

How the fuck did you choose your default language installation ? Also why can't we change it in the settings ?
Are you people special or something ?

I miss the old days when we just had to choose the language we wanted at the installation step, so simple, took a few second of our time, and we didn't feel like we were buttfucked by some idiot's genius idea

**Comment by jnsebgosselin** [comment]
`Preferences > General > Advanced Settings > Language`

![image](https://user-images.githubusercontent.com/10170372/45629831-49f42380-ba65-11e8-955c-c1908692e6f6.png)

**Comment by ccordoba12** [comment]
> How the fuck did you choose your default language installation ?

> Are you people special or something ?

Please refrain your tone next time you want our help or you simply won't receive it.

**Comment by Gotfeurdom** [comment]
> 
> 
> `Preferences > General > Advanced Settings > Language`
> 
> ![image](https://user-images.githubusercontent.com/10170372/45629831-49f42380-ba65-11e8-955c-c1908692e6f6.png)

My bad
I just formatted my computer and I remember there wasn't that option last time
I was on a french OS then so I thought it was justified
To avoid the same issues I decided to install my OS in english and I keep getting french installations left and right
I just saw red instantly and posted my message when it happened with Spyder

Also I maintain that one has to be very special to use IP to select a language

**Comment by ccordoba12** [comment]
> Also I maintain that one has to be very special to use IP to select a language

What do you mean by IP? We get your OS language by running `locale.getdefaultlocale()`. In other words, we use what Python reports.

**Comment by Gotfeurdom** [comment]
> 
> 
> > Also I maintain that one has to be very special to use IP to select a language
> 
> What do you mean by IP? We get your OS language by running `locale.getdefaultlocale()`. In other words, we use what Python reports.

It was a general statement related to my little story, not necessarily towards you.
I spent half an hour trying to get an english version of adobe reader that worked for example because they used IP as such
