### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by odahme** [spyder-ide/spyder#7913]
### What steps will reproduce the problem?

I have no idea. Just started Spyder and got the messages, that Spyder has encountered an internal problem.

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.0 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.2 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.9.0 (OK)
```

**Comment by ccordoba12** [comment]
> I have no idea. Just started Spyder and got the messages, that Spyder has encountered an internal problem.

Without you letting us know what the specific error you encountered was, we can't help you. Please give us the details of the error.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
