### ISSUE TITLE
[Request] Add option to have up/down arrows always move through history

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#7916]
If I execute several multi-line statements in the ipython console, when I go back to the last line by pressing the up arrow and it encounters a multi-line statement in the history, pressing up arrow again will shift the focus to the previous line within that same statement.

Would be nice if there were an option by which pressing the up arrow when browsing the history in the console would move it to the statement that happened before, instead of passing through the lines of the multi-line statement.

**Comment by ccordoba12** [comment]
I don't what [qtconsole](https://github.com/jupyter/qtconsole) version you're using, but that's not true anymore. When you press the up arrow, the cursor will move to the first line in a multiline statement, so when you press up arrow again, you'll move to the previous entry in history,
