### ISSUE TITLE
Issues installing pyhdf package

### ISSUE THREAD

**Issue by gj886403** [spyder-ide/spyder#7918]
## I am trying to install pyhdf package with the anaconda prompt. When doing this I get the following errors:

![condaverificationerror](https://user-images.githubusercontent.com/34081092/45721261-4b296b80-bb9f-11e8-8f68-91dba7064ddf.JPG)

![clobbererror](https://user-images.githubusercontent.com/34081092/45721268-59778780-bb9f-11e8-84a6-94852bda5dba.JPG)

Any suggestions on how to resolve this? Thanks in advance.

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.14
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.2 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
I'm very sorry but this is only to report Spyder problems and yours is clearly not one of them.
