### ISSUE TITLE
Spyder crashed during last session

### ISSUE THREAD

**Issue by kao123** [spyder-ide/spyder#7925]
## Problem Description
Spyder IDE won't launch. I tried running the following command "python3 -c "from spyderlib.spyder import main; main()" --reset", it shows that it has succesfully deleted the files but when i try launching spyder it shows an error message.
I've even purged spyder from my pc and installed it back, but it wouldn't work

### What steps reproduce the problem?

1.  launching spyder 
2. trying reset spyder default settings as shown in error message

### What is the expected output? What do you see instead?
instead of launching spyder IDE I get this message:
Spyder crashed during last session.

If Spyder does not start at all and before submitting a bug report, please try to reset settings to defaults by running Spyder with the command line option '--reset':
python spyder --reset

Warning: this command will remove all your Spyder configuration files located in '/home/kukku/.spyder2-py3').

If restoring the default settings does not help, please take the time to search for known bugs or discussions matching your situation before eventually creating a new issue here. Your feedback will always be greatly appreciated.

### Paste Traceback/Error Below (if applicable)

> spyder3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2331, in main
    mainwindow = run_spyder(app, options, args)
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 2215, in run_spyder
    main.setup()
  File "/usr/lib/python3/dist-packages/spyderlib/spyder.py", line 752, in setup
    from spyderlib.plugins.inspector import ObjectInspector
  File "/usr/lib/python3/dist-packages/spyderlib/plugins/inspector.py", line 41, in <module>
    from spyderlib.widgets.ipython import IPythonControlWidget
  File "/usr/lib/python3/dist-packages/spyderlib/widgets/ipython.py", line 28, in <module>
    pygments_patch.apply()
  File "/usr/lib/python3/dist-packages/spyderlib/pygments_patch.py", line 22, in apply
    from pygments.lexer import _TokenType, Text, Error
  File "/usr/lib/python3/dist-packages/pygments/lexer.py", line 19, in <module>
    from pygments.filters import get_filter_by_name
  File "/usr/lib/python3/dist-packages/pygments/filters/__init__.py", line 20, in <module>
    from pygments.plugin import find_plugin_filters
  File "/usr/lib/python3/dist-packages/pygments/plugin.py", line 39, in <module>
    import pkg_resources
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

## Versions

* Spyder version: spyder3
* Python version: python3 
* Operating System name/version:  Ubuntu 16.04

```

**Comment by kao123** [comment]
it seemed that my pip install wasn't upgraded 
i have solved the problem by running
pip install --upgrade setuptools
after i run
sudo pip install -U Spyder
spyder has sucesfully launched, but i can't used the ipython console anymore
here is the traceback:


"An error ocurred while starting the kernel
‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑‑
RuntimeError Traceback (most recent call last)
/usr/lib/python3/dist‑packages/spyderlib/widgets/externalshell/start_ipython_kernel.py in ()
184 ipk_temp = IPKernelApp.instance()
185 ipk_temp.config = kernel_config()
‑‑> 186 ipk_temp.initialize()
global ipk_temp.initialize = >
187 
188 # Grabbing the kernel's shell to share its namespace with our

in initialize(self=, argv=None)

/usr/lib/python3/dist‑packages/IPython/config/application.py in catch_config_error(method=, app=, *args=(None,), **kwargs={})
90 """
91 try:
‑‑‑> 92 return method(app, *args, **kwargs)
method = 
app = 
args = (None,)
kwargs = {}
93 except (TraitError, ArgumentError) as e:
94 app.print_help()

/usr/lib/python3/dist‑packages/IPython/kernel/zmq/kernelapp.py in initialize(self=, argv=None)
440 self.init_io()
441 self.init_signal()
‑‑> 442 self.init_kernel()
self.init_kernel = >
443 # shell init steps
444 self.init_path()

/usr/lib/python3/dist‑packages/IPython/kernel/zmq/kernelapp.py in init_kernel(self=)
384 def init_kernel(self):
385 """Create the Kernel object itself"""
‑‑> 386 shell_stream = ZMQStream(self.shell_socket)
shell_stream = undefined
global ZMQStream = 
self.shell_socket = 
387 control_stream = ZMQStream(self.control_socket)
388 

/usr/lib/python3/dist‑packages/zmq/eventloop/zmqstream.py in __init__(self=, socket=, io_loop=None)
101 def __init__(self, socket, io_loop=None):
102 self.socket = socket
‑‑> 103 self.io_loop = io_loop or IOLoop.instance()
self.io_loop = None
io_loop = None
global IOLoop.instance = 
104 self.poller = zmq.Poller()
105 

/usr/lib/python3/dist‑packages/zmq/eventloop/ioloop.py in instance(*args=(), **kwargs={})
144 # when using tornado 3
145 if tornado_version >= (3,):
‑‑> 146 PollIOLoop.configure(ZMQIOLoop)
global PollIOLoop.configure = >
global ZMQIOLoop = 
147 return PollIOLoop.instance(*args, **kwargs)
148 

/usr/local/lib/python3.5/dist‑packages/tornado/ioloop.py in configure(cls=, impl=, **kwargs={})
196 if not issubclass(impl, BaseAsyncIOLoop):
197 raise RuntimeError(
‑‑> 198 "only AsyncIOLoop is allowed when asyncio is available")
199 super(IOLoop, cls).configure(impl, **kwargs)
200 

RuntimeError: only AsyncIOLoop is allowed when asyncio is available"

Please how can i solve it??

**Comment by ChuliangXiao** [comment]
Had the same error with `spyder3` on mac (without conda). Thanks for your suggestion
```bash
pip install --upgrade setuptools
```
Now `spyder3` works and no problem with `IPython`.
