### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Jacinth999** [spyder-ide/spyder#7937]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
There was an infinite loop running. I could'nt terminate that loop. So,i have closed spyder. After restarting the kernel it is not working. No program is executing in kernel.

**Comment by ccordoba12** [comment]
> No program is executing in kernel. 

I don't understand what you mean by this. Please pots a screenshot to better understand what's happening in your case.

**Comment by Jacinth999** [comment]
I was  writing a program on random library. The infinite loop couldn't be
terminated.The kernel was not restarting. It was showing that there was an
internal problem with kernel. After that I couldn't execute any program.
So, i have reinstalled Spyder . Now there is no problem with it.

**Comment by ccordoba12** [comment]
So can we close this issue?

**Comment by Jacinth999** [comment]
Yes we can close this issue. Thank you

**Comment by ccordoba12** [comment]
Ok, glad to know you were able to sort out this problem.

**Comment by Jacinth999** [comment]
I'm again facing this problem.

**Comment by Jacinth999** [comment]
Error
