### ISSUE TITLE
Spyder Does Not Launch After Updating Anaconda Packages

### ISSUE THREAD

**Issue by staqiuddin** [spyder-ide/spyder#7940]
## Problem Description
I have Anaconda Python Distribution. After executing the `conda update conda` and `conda update --all` commands, Spyder no longer launches. Among the updated packages is `spyder-kernels` (updated to v1.0.1).

### What steps reproduce the problem?

1. Execute `conda update conda` from Anaconda Prompt.
2. Execute `conda update --all` from Anaconda Prompt.
3. Launch Spyder.

### What is the expected output? What do you see instead?
Spyder should launch.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\start.py", line 190, in main
    from spyder.app import mainwindow
  File "C:\Users\user\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 51, in <module>
    requirements.check_spyder_kernels()
  File "C:\Users\user\Anaconda3\lib\site-packages\spyder\requirements.py", line 66, in check_spyder_kernels
    % actual_ver)
  File "C:\Users\user\Anaconda3\lib\site-packages\spyder\requirements.py", line 24, in show_warning
    raise RuntimeError(message)
RuntimeError: Please check Spyder installation requirements:
spyder-kernels < 1.0 is required (found 1.0.1).

```

## Versions
* Spyder version: 3.3.1
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies
N/A (Spyder does not launch).

**Comment by ccordoba12** [comment]
Please run

    conda remove spyder-kernels
    conda install spyder-kernels=0.*

to fix this problem.

**Comment by staqiuddin** [comment]
Thank you @ccordoba12 for your efforts, prompt reply and help. Appreciated.

**Comment by ccordoba12** [comment]
Thanks for your kind words!

**Comment by dphaas** [comment]
Needed this fix on Win7-64, conda=4.6.2, python=3.7.2.  Reverted spyder-kernels from 1.0.1 to 0.3.0.  Spyder now launches without error

**Comment by sbsreyes** [comment]
@ccordoba12 Mi hermano ud es un genio, muchas gracias

**Comment by ccordoba12** [comment]
Vale, de nada!

**Comment by M-a-gg-a** [comment]
Hi, 
 I downloaded some packages, when I tried to run spyder I got a lot of errors and run these commands: 
conda remove spyder-kernels
conda install spyder-kernels=0.*

After that, I am getting a message 'spyder' is not recognized as an internal or external command, operable program or batch file. 
spyder - 4.2.1
python 3.9.1
windows 10

Thanks for your help!

**Comment by ccordoba12** [comment]
@M-a-gg-a, I think you were caught by the problem reported on issue #14687. Please see there for temporal solutions.

**Comment by M-a-gg-a** [comment]
Thank you very much for your response,  I ran the indicated code and spyder is working well.

I still have the following  four packages to install  and I don’t want to break spyder, I have to turn in homework every week. Would it be ok to install the packages as indicated below? or do I need to use a different command?


  *   Keras:
conda create -n tf tensorflow
conda activate tf



  *   Tensorflow
conda install -c anaconda keras



  *   Piglet
conda install -c anaconda akode piglet



  *   pysimplegui
conda install -c conda-forge pysimplegui


[cid:image002.png@01D6FD9C.D2DEA360]

Thank you for your help,



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ccordoba12** [comment]
Yeah, I think that's ok. After that, you need to connect your `tf` environment by following the instructions in our [FAQ](http://docs.spyder-ide.org/current/faq.html#using-existing-environment).

**Comment by M-a-gg-a** [comment]
Will do! Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by Siriussgh** [comment]
Hello ! I'm new to python I have problem on launching Spyder on anaconda, how to solve it. Thank you in advance 

objc[728]: Class RunLoopModeTracker is implemented in both /Users/macuser/opt/anaconda3/lib/python3.8/site-packages/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x11324c288) and /Users/macuser/opt/anaconda3/lib/libQt5Core.5.9.7.dylib (0x11ccfca80). One of the two will be used. Which one is undefined. Traceback (most recent call last): File "/Users/macuser/opt/anaconda3/bin/spyder", line 11, in  sys.exit(main()) File "/Users/macuser/opt/anaconda3/lib/python3.8/site-packages/spyder/app/start.py", line 201, in main from spyder.app import main-window File "/Users/macuser/opt/anaconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 84, in  from qtpy import QtWebEngineWidgets # analysis:ignore File "/Users/macuser/opt/anaconda3/lib/python3.8/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in  from PyQt5.QtWebEngineWidgets import QWebEnginePage ValueError: PyCapsule_GetPointer called with incorrect name
