### ISSUE TITLE
How to make main window concise

### ISSUE THREAD

**Issue by 229668880** [spyder-ide/spyder#7948]
Hi,
Spyder seems too bucky. It is a little to start Spyder for me. How to only show script window and console window? Just two windows, no unnecessary widgets.  A concise version of Spyder looks like Rgui.exe.

After start Spyder, only two windows are displayed. One is  a script window like notepad.exe, the other is the console.  You can choose some lines in script, then right click it to run.

**Comment by ccordoba12** [comment]
Just close the other panes so that you only have the Editor and the Console panes in the window. Each pane has a little `x` button on its top right corner that let's you do that.

**Comment by jnsebgosselin** [comment]
Could you post a screenshot of Rgui showing what you are talking about please?

**Comment by 229668880** [comment]
<img width="734" alt="capture" src="https://user-images.githubusercontent.com/6130276/46061297-c939d380-c198-11e8-90a9-23a36643eda8.PNG">
