### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by estathop** [spyder-ide/spyder#7950]
Tried to open and watch a big dictionary variable in variable explorer
```
  lambda eid=id(editor): self.editor_accepted(eid))
  File "/home/estathop/anaconda2/envs/tensorflow/lib/python2.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 563, in editor_accepted
    data = self._editors[editor_id]
KeyError: 140486674989592
```

**Comment by ccordoba12** [comment]
Sorry but your description is not enough. Please give a reproducible way to generate this error so we can fix it in our side.

**Comment by estathop** [comment]
I just pressed automatic error report, I don't know what you are asking

**Comment by ccordoba12** [comment]
That we need from you a way to reproduce this problem. Just filling the error report without further information is not enough for us.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
