### ISSUE TITLE
Crashing kernel

### ISSUE THREAD

**Issue by mirko3funovic** [spyder-ide/spyder#7952]
### What steps will reproduce the problem?

This code below will trash the kernel when executed *second* time. Steps:
1) Execute the code from within Spyder
2) Little Qt window opens
3) Close the Qt window by clicking [X]
4) Execute the code again
5) "Kernel died, restarting"

    from PyQt5.QtWidgets import QApplication, QLabel
    app = QApplication([])
    label = QLabel('Hello World!')
    label.show()
    app.exec_()
    

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please see

https://github.com/spyder-ide/spyder/wiki/How-to-run-PyQt-applications-within-Spyder

**Comment by mirko3funovic** [comment]
Thanks for the link, but it is still crashing after I set it to Automatic. I restarted Spyder after changing the option.

![image](https://user-images.githubusercontent.com/12074648/46032225-02a30e00-c0c9-11e8-8f10-e055dd8ee1d8.png)
