### ISSUE TITLE
Extremely slow load and run

### ISSUE THREAD

**Issue by skintigh** [spyder-ide/spyder#7958]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Fresh install of Anaconda on a new computer, not used once.
On launching Spyder, the logo is displayed for around 3 minutes before the IDE loads
Next it spent 10 or so minutes attempting to connect to the kernel. I tried killing it, reloading, killing the console, killing it and running "spyder --reset" in an anaconda prompt, none made a difference. Eventually it stopped on it's own.

Then I wrote:
    print("hello world")
and ran it. It took 7 seconds to execute. Subsequent runs also take 7 seconds to print "hello world."

"spyder --reset" in an anaconda prompt didn't help
"Check for updates" is disabled
I unchecked "Use a single instance" (under Preferences > General > Advanced Settings) [FYI: the Troubleshooting Guide omits that is found under the "Tools" menu.]
I uninstalled and reinstalled for all users.
I updated conda
Updated anaconda
updated spyder

Internal console:
WARNING:traitlets:kernel died: 18.000919103622437
WARNING:traitlets:kernel died: 18.000887155532837

This seems like a good IDE but so far it is basically unusable even after hours of debugging.

### What steps reproduce the problem?

1. Open Spyder
2. print("hello world")

### What is the expected output? What do you see instead?
Response an "hello world" in under 10 minutes, at the very lease some sort of feedback or message indicating why it takes 10 minutes from start to printing "hello world". Extremely long load time and run time.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64-bit

3.6GHz x 4 i7-7700 32 GB RAM

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Sorry but this seems a problem particular to your system and not to Spyder, so we can't help you. I'd recommend a Windows re-installation. That's the only thing that occurs to me.
