### ISSUE TITLE
Search for "whole words" does not return the correct number of matches

### ISSUE THREAD

**Issue by mvillion** [spyder-ide/spyder#7960]
## Description

In the editor, suppose we have the following file:
____
item = "item"
item_etc = "item_etc"
____
If we search for the string item, spyder finds 4 occurences.
If we search for the string item as a whole word, spyder does find 2 occurences when clicking on arrows in the search bar but still reports 4 occurences.

### What is the expected output? What do you see instead?
Shouldn't it report?: 1 of 2 and 2 of 2
It reports instead: 1 of 4 and 2 of 4.

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.5 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.11.0     :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We probably need to adapt the the report occurrences to use the options in the widget.
