### ISSUE TITLE
This was fixed in our 3.2.7 version. Please update.

### ISSUE THREAD

**Issue by khemesphere** [spyder-ide/spyder#7961]
_Originally posted by @ccordoba12 in https://github.com/spyder-ide/spyder/issues/6586#issuecomment-370152074_

Having trouble with Spyder in Anaconda - Console says: "Connecting to Kernel" and does not connect. I tried upgrading to newest Spyder, and then downgrading back to 3.2.7. Would appreciate assistance.

**Comment by ccordoba12** [comment]
> Would appreciate assistance.

With what exactly?

**Comment by khemesphere** [comment]
New to python via spyder - can't access console. Wondering how to fix the 'connecting to kernel' issue.

**Comment by ccordoba12** [comment]
Are you unable to update Spyder? Please be more clear.

**Comment by khemesphere** [comment]
Spyder is version 3.3.1 now - updated through Anaconda. When I open Spyder, the console 1/A still shows 'Connecting to kernel' - never actually connecting.

**Comment by ccordoba12** [comment]
Please open an Anaconda prompt, run there

    conda install ipykernel=4.8.2

and try again.

**Comment by ccordoba12** [comment]
And before running that command, you need to close Spyder.

**Comment by khemesphere** [comment]
ccordaba, thank you. I left the kernel connecting for an hour or so and it connected! 
I just inquired in my terminal:
`python3 -m ipykernel --version`
it returned 6.5.0. Is this okay? Or do I need to downgrade to make it happy?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
