### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Jascareer** [spyder-ide/spyder#7967]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
![image](https://user-images.githubusercontent.com/5587611/46253059-888bd400-c490-11e8-84c4-4fb262ef7139.png)

**Comment by ccordoba12** [comment]
Sorry but what you reported is not enough. Next time this error appears, please press the *Show details* button in the error report dialog so we can see what error was generated.
