### ISSUE TITLE
Automatic Updates on Outline Explorer

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#7976]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The outline explorer only updates when a file is saved. If a line is added to a file the links in the outline explorer will link to the wrong line until the file is saved. Also the section names are not updated

### What steps reproduce the problem?

1. Add a line near the start of the file
2. click a function
3. it goes to the wrong line

### What is the expected output? What do you see instead?

The link goes to the right line.

## Version
Master

## Solution

One simple solution would be to add an update timer similar to the variable explorer.

**Comment by impact27** [comment]
The outline explorer is using a line number to reference the line, which is fragile. Would it be better to reference the QTextBlock instead? The line can then recovered with `firstLineNumber()` or `blockNumber() `.

**Comment by bcolsen** [comment]
> Would it be better to reference the QTextBlock instead?

Yes, I think that would work. 

Any ideas about adding new function/class/cell definitions? Could use syntax highlighter to detect new definitions and activate the oe_data tree parsing? In turn this could be a useful way to define unique cells.

**Comment by impact27** [comment]
Why are the `oedata` stored in a `outlineexplorer_data` dictionary instead of in `block.userData()`? This would solve this very nicely no? There would be no need to call the outline explorer anywhere in the code as the `oedata` would be accessible from the block directly.

**Comment by bcolsen** [comment]
> Why are the oedata stored in a outlineexplorer_data dictionary instead of in block.userData()? This would solve this very nicely no?

I was looking into the qt docs myself the other night and  `userData()` does look promising! I think the line dictionary was used because the line order is important in making the tree, but we might be able to use block comparisons to sort a list.

> is saving an id for every single line of every single open file not a bit extreme?

Yes, but I don't think we need to do that. For the outliner at least we only need to keep track of definitions, code cells and special comments.

> For block_id, I first thought of id(block), but this is not constant for some reason. id(block.userData()) seems to be a bit better. This would not be conserved if the file is reopened. Do you have a better idea for block_id? 

Names are the best I can think of that has any hope of being conserved when reopening. If the file has no name, non-unique names or names that change these won't be conserved, but I think people will find that reasonable.
 
> Once we have a block identifier, whatever it is, can be use with the cell name to identify a cell. It could even be used without the cell name to allow for a cell rename.

To rename we can use block comparisons to see if that block is already in the dictionary and change the name and this would change the block id too if the block id is name based. People wouldn't expect to make function call with the old function name after they change the name code cells wouldn't be any different.
