### ISSUE TITLE
How can I use getcomputedStyle function of java script in spyder ide

### ISSUE THREAD

**Issue by Sarthak1119** [spyder-ide/spyder#7977]
Hi, 
I want to find the style of ::before element. I am using window.getComputedStyle function of javascript but spyder ide is not able to recognize the javascript function.

Please help me and let me know which package I should install with anaconda and what should I import in the file?

**Comment by ccordoba12** [comment]
Spyder only works with Python, not with JavaScript nor any other programming language.
