### ISSUE TITLE
 Crash when saving an image in the IPython console

### ISSUE THREAD

**Issue by strpeter** [spyder-ide/spyder#7978]
### What steps will reproduce the problem?

The problem is reproducible:

1. Plot a simple drawing using matplotlib in console
```
import matplotlib.pyplot as plt
plt.plot([0, 1])
```
2. Right click the image to chose "save image as" for destination of the file.
3. Now we store the figure on an existing name e.g. 'test.png'. It can also be another file ending. What happens now is a black screen and you're logged out from Gnome Desktop Manager.

The entire desktop session is closed without any prevention. The steps are identic with the Crash report #4088 except that even the entire desktop crashes.

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.18.9-arch1-1-ARCH

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.0 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by goanpeca** [comment]
With the new plots viewer, I believe this should no longer be an issue. Closing.
