### ISSUE TITLE
Variables click 

### ISSUE THREAD

**Issue by chaochii** [spyder-ide/spyder#7985]
### What steps will reproduce the problem?

Turned DataFrame into np array and operated. Click variables and it crashes.

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.11.0     :  0.12.0 (OK)
psutil >=0.3      :  5.4.5 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by chaochii** [comment]
I wanted to do some simple mathematical operation on the converted numpy array. However, spyder crashes instantly when the result variable was clicked.

**Comment by ccordoba12** [comment]
Please here paste the code which generated the crash. Else we can't help you, sorry.
