### ISSUE TITLE
Keyboard input is not captured correctly when running Spyder over remote connection 

### ISSUE THREAD

**Issue by StephanSchwebel** [spyder-ide/spyder#8010]
## Description

I am connected to my "work" PC (windows 10 64bit) via:
1) Personal laptop (windows 10 64bit)
2) Remote network connection (web interface on Edge)
3) Terminal Server (Windows Server 2012 R2)
4) Remote Desktop

Open Spyder 3.2.8 and use any text input (editor, console).
Press a key (e.g. 'k') on the laptop keyboard and the letter is displayed correctly but any subsequent key-press will result in 'k' being displayed irrespective of the key.
If Spyder loses input focus and regains it again, the first key press is correct, subsequent keys are incorrect.
Other text editors (Notepad++, Visual Studio 2017, MS Word etc.) work fine with regard to keyboard input, 

**Please provide any additional information below**
Text input works as expected when I log directly into the "work" PC (i.e. not remotely)

## Version and main components

* Spyder Version: 3.2.8
* Python Version: 3.6.5

**Comment by jnsebgosselin** [comment]
@StephanSchwebel Thanks for your report.

Does this occur only in the Editor on in any text input widget?

**Comment by ccordoba12** [comment]
Closing because of lack of response.

**Comment by StephanSchwebel** [comment]
Sorry, the notification e-mail got quarantined.
The answer to your question is in the original description.
>>Does this occur only in the Editor on in any text input widget?
"Open Spyder 3.2.8 and use any text input (editor, console)."
So the answer is yes, any text input widget within spyder exhibits the problem.

**Comment by ccordoba12** [comment]
@StephanSchwebel, I use Teamviewer to connect to a remote Windows desktop and I don't experience this.

It's probably a Qt issue (Qt is the graphical toolkit Spyder is built on top of) and that's something we can fix here, sorry.

**Comment by StephanSchwebel** [comment]
Hi Carlos,

When I connect using TeamViewer I don’t experience the problem either. Does this have any impact on your assessment?

Thanks,

Stephan

**Comment by ccordoba12** [comment]
That only means that this problem is not related to Spyder, as I suspected.

**Comment by Sandell0** [comment]
I am connected to my PC (Windows 10 64bit) via Teamviewer (14.4.2669) from MacBook Air 13 and experienced all the same issues described by StephanSchwebel.

Spyder Version: 3.3.4
Python Version: 3.7.3
