### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by MaurizioMalaspina** [spyder-ide/spyder#8018]
### What steps will reproduce the problem?

Spider 3.3.1 was available, so I launched the upgrade process by typing "pip install --upgrade spyder" at the Python console.
During install an issue occurred... so I've now a partial installation of Spyder.

**Comment by MaurizioMalaspina** [comment]
I've installed:

Anaconda Navigator 1.9.2
Spyder 3.2.8

on Win10 Home x64.
I launched the terminal without ask for "execute as Administrator"

**Comment by ccordoba12** [comment]
> pip install --upgrade spyder
> Anaconda Navigator 1.9.2

If you're using Anaconda you *must not* use pip to install Spyder. We warn these everywhere we can:

https://github.com/spyder-ide/spyder/releases/tag/v3.3.1

By doing that you corrupted your Anaconda installation and you need to reinstall it.
