### ISSUE TITLE
Paste multiple functions

### ISSUE THREAD

**Issue by dormeursleepy** [spyder-ide/spyder#8026]
Hi,
I'm new to Python, I recently started to use spyder with Python 3.3.5 32 bit, IPython 3.2.0 at home.
I started creating a few things that work well on my computer.

But when I open the .py files at work (they use spyder with Python 3.3.3 32 bit, I don't know which IPython version but I can find it if needed), I have a problem.

At home, I can copy my whole code and paste it in the console without any problem.
At work, I can only copy one function after another, so if I have, say, 10 functions in my file, it's pretty long to do. I cannot imagine doing that with a more complicated .py file with hundred functions.

So, is there an easy way to fix this? Is it version dependent or is it just an option to change somewhere?
I noticed the console doesn't look the same at home and at work, at home it's called console 1/A and input lines start with `In[1]:`, `In[2]`, etc, and at work they start with `>>>`

**Comment by ccordoba12** [comment]
Please read this:

http://docs.spyder-ide.org/editor.html#defining-code-cells

Also, you're also using very old versions of Python and Spyder. You should update to our latest version in case you're unable to use cells.
