### ISSUE TITLE
DataFrames in Variable Explorer: Missings should have distinctive background color

### ISSUE THREAD

**Issue by jondo** [spyder-ide/spyder#8037]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When opening a Pandas DataFrame with missing values in the Variable Explorer, the missings are displayed with red cell background, which is similar to the red background of the minimal values. So the missings are difficult to spot.

I suggest using a white background for the missings instead.

### What steps reproduce the problem?

1. `df=pd.DataFrame([1,None,5,9])`
2. Open df in the Variable Explorer.

### What is the expected output? What do you see instead?

I see
![screenshot-missings-in-variable-explorer](https://user-images.githubusercontent.com/21648/46651707-28d4ad80-cba1-11e8-8fcb-6ce5290b1e7d.png)

I expect the nan field to have a visually distinctive color, e.g. white.

## Versions

* Spyder version: 3.3.1
* Python version: 3.7.0 64bits
* Qt version: Qt 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Win7 64-bit

(everything from WinPython64-3.7.0.2)

### Dependencies

Available on request.

**Comment by ccordoba12** [comment]
That's a very good suggestion, but (unfortunately) we don't have the time to implement it. Probably after Spyder 4 is released.

**Comment by jondo** [comment]
That's fine. I am simply using this patch against `spyder\\widgets\\variableexplorer\\dataframeeditor.py` for now:

```python
@@ -228,6 +228,8 @@ class DataFrameModel(QAbstractTableModel):
         if not self.bgcolor_enabled:
             return
         value = self.get_value(index.row(), column-1)
+        if np.isnan(value):
+            return Qt.white
         if self.max_min_col[column - 1] is None:
             color = QColor(BACKGROUND_NONNUMBER_COLOR)
             if is_text_string(value):
```

**Comment by jondo** [comment]
@CAM-Gerlach, I want to discuss the following here outside my pull request, since it's not implementation related:

You [would call](https://github.com/spyder-ide/spyder/pull/8059#pullrequestreview-164444951) a neutral background color appropriate. I don't think so: Since a neutral background is also used for text columns, the missings would stay difficult to spot there.

**Comment by jondo** [comment]
Hmm... on the other hand, the neutral color is already white, at least in the Linux Mint 19 Cinnamon standard theme! The following is `df=pd.DataFrame(['a',None,'c'])` on master (with a very bright grey background for the missing value):

![missing-text](https://user-images.githubusercontent.com/21648/46906476-a414c700-cef3-11e8-9421-7739881d702f.png)

What about a strong yellow? Green feels too positive for missings :-) I guess that all kinds of missings (numerical, text, object) should get the same color.

**Comment by CAM-Gerlach** [comment]
Good point. My view is we should simply follow our existing conventions here, with NA/Null/NaN/etc joining ``None`` as being a distinctive light gray, as you see in your example. If you implement the changes I've requested (merging the nan check into the following ``if`` block and letting it do the work for you), this will achieve exactly that, while also eliminating the uneeded, less performant and harder to maintain additional block.

> What about a strong yellow? Green feels too positive for missings :-)

I'd strongly recommend against a non-gray (i.e. neutral) color, as we want to represent them as clearly distinct from numbers, which have color scales applied to them. We are planning to add custom color palettes for the color scales at some point, so any non-white/gray color is likely to interfere with at least one of them. Therefore, the best solution, IMO, is to simply follow our existing practice and treat ``NaN``/etc. just like the other null and misc values we currently handle (``None``, etc).

**Comment by jondo** [comment]
OK.

By the way, I wrote "the neutral color is already white" because I nearly could not distinguish the light grey from the white neighbor cells. Now I have found out why: I had my monitor's contrast set too high.
