### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by NeoDH** [spyder-ide/spyder#8053]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
 'plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.1). Please update by opening the Anaconda Prompt and running there

    conda update spyder
