### ISSUE TITLE
My Spder Background is complete black

### ISSUE THREAD

**Issue by Hassankashi** [spyder-ide/spyder#8054]
### What steps will reproduce the problem?

When I installed anaconda after when I try to use spyder I can not see anything except black screen.
I have read:
https://github.com/ContinuumIO/anaconda-issues/issues/9597
https://github.com/spyder-ide/spyder/issues/7327

I tried : conda install pyopengl
 from anaconda prompt

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 2008ServerR2

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
This should be solved in our next release (3.3.2). In the meantime, please close Spyder, open the Anaconda Prompt, run there:

    conda install qt=5.6 pyqt=5.6 sip=4.18

and try again.

**Comment by Hassankashi** [comment]
@ccordoba12 Thank you so much, it solved my problem, now I can see IDE. 
Was it because of I had 2008ServerR2 and something was related to my graphic card?

**Comment by ccordoba12** [comment]
I think it's something related to the drivers of your graphics card, or maybe to your DirectX version. Let's hope it's fixed in our next version.
