### ISSUE TITLE
Problem to import Basemap (1.2.0) in Spyder - KeyError: 'PROJ_LIB' - Windows 10

### ISSUE THREAD

**Issue by rpedruzzi** [spyder-ide/spyder#8060]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Dear all,
I am using spyder 3.3.1 with python 3.6.5, Ipython 6.4.0, conda version : 4.5.11 and I am having problem with Basemap.
I tried to install the new anaconda with python 3.7 and I have the same problem.
I do not problems with other packages, like cartopy, which uses proj/proj.
This is the issue

Traceback (most recent call last):

File "", line 1, in 
from mpl_toolkits.basemap import Basemap

File "C:\Users\pedruzzi\anaconda3\lib\site-packages\mpl_toolkits\basemap_init_.py", line 155, in 
pyproj_datadir = os.environ['PROJ_LIB']

File "C:\Users\pedruzzi\anaconda3\lib\os.py", line 669, in getitem
raise KeyError(key) from None

KeyError: 'PROJ_LIB'

### What steps reproduce the problem?

1. from mpl_toolkits.basemap import Basemap
2. 
3. 

### What is the expected output? What do you see instead?
I was expeting the backeage to be load and I got this:
File "", line 1, in 
from mpl_toolkits.basemap import Basemap

File "C:\Users\pedruzzi\anaconda3\lib\site-packages\mpl_toolkits\basemap_init_.py", line 155, in 
pyproj_datadir = os.environ['PROJ_LIB']

File "C:\Users\pedruzzi\anaconda3\lib\os.py", line 669, in getitem
raise KeyError(key) from None

KeyError: 'PROJ_LIB'

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.5
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: 
Windows 10 64bits

### Dependencies

```
PASTE DEPENDENCIES HERE
```
basemap 1.2.0 py36h4e5d7af_0
dependencies:
    geos >=3.6.2,<3.6.3.0a0
    matplotlib >=1.0.0
    numpy >=1.11.3,<2.0a0
    pyproj >=1.9.3
    pyshp >=1.2.0
    python >=3.6,<3.7.0a0
    six
    vc >=14.1,<15.0a0

**Comment by ccordoba12** [comment]
> pyproj_datadir = os.environ['PROJ_LIB']

This means that `basemap` is expecting the `PROJ_LIB` environment variable to be set before being imported. However, this is not related to Spyder and I don't know how to solve it, sorry.

**Comment by jamessong** [comment]
it is related to Spyder! Since if you run this outside Spyder, it works. 
Insider Spyder, os.environ didn't list out PROJ_LIB

**Comment by ccordoba12** [comment]
@jamessong, you need to start Spyder from a terminal (xterm, cdm.exe or Terminal.app) to have the environment variables defined on them in its IPthon console.

**Comment by jamessong** [comment]
just realized that, but already wasted some time ...  
strange why can the anaconda prompt recognize these environment variables?  

 (base) C:\Users\Ja>echo %PROJ_LIB%
C:\Users\Ja\Anaconda3\Library\share
