### ISSUE TITLE
Explanatory text for Greedy Completion preferences option cut off only in dark theme

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8070]
## Problem Description

As discussed in #8020 and part of #8068 .

The explanatory text for the Greedy completion preference option is cut off in the dark theme, while it is normal in the standard light theme (possibly due to the ``code`` formatting???).

Witness:

![image.png](https://images.zenhubusercontent.com/5aac63014b5806bc2bcb3680/d5e59668-7ae9-4962-8db2-a5df4bc6ff8d)

vs.

![image.png](https://images.zenhubusercontent.com/5aac63014b5806bc2bcb3680/74d70b8e-fcc7-49da-b43a-eee065e83097)

**Comment by ccordoba12** [comment]
It seems fixed in QDarkStyle **2.6.1**. @CAM-Gerlach, please confirm and close if that's the case,

**Comment by CAM-Gerlach** [comment]
Yup, fixed!

![image](https://user-images.githubusercontent.com/17051931/47886545-bb671600-de08-11e8-9b89-4e41ed2fa1c5.png)
