### ISSUE TITLE
Make internal console respect user's syntax highlighting theme

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8072]
## Problem Description

A part of #8068 .

Currently, the Internal Console and the Issue Report dialog use the default Spyder syntax highlighting theme, which wasn't as big of a problem in the past. However, now that Spyder is offering an application-wide dark theme, it looks odd to have these panes in a different color as the rest of the UI. As a stopgap, we could have them default to the Spyder Dark scheme if using the dark UI theme, but if we're going that far and it isn't much more effort, it would seem prudent to just use the proper theme to begin with.

e.g.

![image.png](https://images.zenhubusercontent.com/5aac63014b5806bc2bcb3680/91afa621-d44a-4f24-bca8-558cb7305e00)

**Comment by ccordoba12** [comment]
The error dialog stuff (only the description widget though) was fixed in PR #8081. The traceback part and the internal console will be fixed in another PR.
