### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by shreyasmishra1998** [spyder-ide/spyder#8074]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I used pip install --upgrade spyder in anaconda terminal window but it did not update and then when I opened Spyder again , it said there was an internal error

**Comment by ccordoba12** [comment]
> pip install --upgrade spyder

We warn loudly against this when using Anaconda, like here:

https://github.com/spyder-ide/spyder/releases/tag/v3.3.1

So you most probably corrupted your installation and now you need to reinstall, sorry.

**Comment by shreyasmishra1998** [comment]
Ok thanks
