### ISSUE TITLE
Incorrect custom shortcut displayed in menus for Run Cell command

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8076]
## Problem Description

I've defined a custom shortcut, Ctrl-Shift-Return, for "Run Cell" (along with the other run commands). While other shortcuts display fine, "Run Cell" displays the shortcut as ``Ctrl-Return`` in the Run menu instead, which I believe is (perhaps not coincidentally) the original shortcut. However, the correct shortcut does work just fine.

This is the case in both Spyder 3 and Spyder 4. Ctrl-Shift-Return is the correct shortcut that I set, and indeed works, but it displays as Ctrl-Return... There should be enough space to do so, considering it adds only one extra small character over Alt-Shift-Return that is displayed, and there's a ton of extra horizontal space in the menu. Do you want me to run some more tests on this?

![image.png](https://images.zenhubusercontent.com/5aac63014b5806bc2bcb3680/c51f50da-8696-456d-ac7f-67695f15b9cc)

![image.png](https://images.zenhubusercontent.com/5aac63014b5806bc2bcb3680/4383cd69-9474-4850-af64-d18a5e5516ea)

## Versions

* Spyder version: 3.3.1 and ``master``
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

**Comment by jnsebgosselin** [comment]
Thanks for filling an Issue about this. If I recall correctly, this happens because the label in the menu is hardcoded for this shortcut. I will take care of it.
