### ISSUE TITLE
Consider making the dark theme (and corresponding Spyder Dark syntax scheme) the default in Spyder 4

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8080]
## Problem Description

Per the initial discussion in #8020 and the broader theme of #8068 , we should strongly consider making the dark theme (and the Spyder dark syntax highlighting scheme) the default in Spyder 4, like Rstudio did when they added their dark theme. This would help visually establish a fresh new look for Spyder 4, makes Spyder look much more modern and professional, matches Rstudio, VSCode, Atom, PyCharm and other IDEs (IIRC), and makes for much more impactful and higher-contrast website and docs screenshots (I note, as I've done previously, that all of the aforementioned IDEs have primarily or exclusively the dark theme version in the screenshots on their respective websites).

**Comment by ccordoba12** [comment]
@spyder-ide/core-developers, what do you think about this? I'm +0.5 for now because, even though I like dark themes, I don't know how well our implementation could end up being.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 This would be the final act in the #8068 epic, so we could always defer a final decision until we see how it turns out.

**Comment by jnsebgosselin** [comment]
@ccordoba12 you need to @spyder-ide/junior-developers too if you want to poke everyone actively working on the project.

I vote for dark theme as default because that is what seems to be the trend these days, but I think I will continue to use the light theme due to personal preferences, but maybe I will change my mind after using the dark theme once it is fully implemented :)

**Comment by dalthviz** [comment]
I think that probably the final decision has to be taken after testing the theme in different OS and other criteria (about the implementation robustness and perception of the overall image). But dark as default could be nice :)
