### ISSUE TITLE
spyder appcrash with module name atio6axx.dll

### ISSUE THREAD

**Issue by James-Hao** [spyder-ide/spyder#8098]
Problem Description
Firstly, i would apologize for the few experience in Github, here i got a problem which perplex me a whole day: Today's morning, my codes was performed normally as usual, but when i do some modification for codes, a common error: valid syntax appeared. After i did some fix, the spyder had crashed without reason. No matter what i did, it cannot open again, then i reinstalled anaconda3 which is latest version, when i open spyder again, there is the appcrash as below.

Problem signature:
Problem Event Name:	APPCRASH
Application Name:	pythonw.exe
Application Version:	3.7.150.1013
Application Timestamp:	5b34dd6b
Fault Module Name:	atio6axx.dll
Fault Module Version:	6.14.10.12422
Fault Module Timestamp:	52212c19
Exception Code:	c0000005
Exception Offset::	000000000131ba69
OS Version:	6.1.7601.2.1.0.256.48
Locale ID:	2052
Additional Information 1:	9ed1
Additional Information 2:	9ed114e9a8e476e135da726878a499f4
Additional Information 3:	78b1
Additional Information 4:	78b11368e776746f243084f49b67fca0

I'm sorry again for my unofficial format question.  Thanks very much , wating for your help!!!

**Comment by ccordoba12** [comment]
This seems a problem with your graphics card driver:

https://community.amd.com/thread/184943

So you probably updated it and now things are broken. I don't know how else to help you, sorry.

**Comment by James-Hao** [comment]
> This seems a problem with your graphics card driver:
> 
> https://community.amd.com/thread/184943
> 
> So you probably updated it and now things are broken. I don't know how else to help you, sorry.

Thanks a lot.  just now i'v tried the method you applied and thanks i'v solved the appcrash problem. However, when i restart the computer and open spyder, here comes a new problem as below:

Problem signature:
Problem Event Name:: AppHangB1
Application Name:	pythonw.exe
Application Version:: 3.7.150.1013
Application Timestamp:	5b34dd6b
signature hung : a766
hang type: 0
OS Version:	6.1.7601.2.1.0.256.48
Locale ID:   2052
Additional signature hung 1:	a76615e5797198bc3156a9f92f6e54b6
Additional signature hung 2:	1d25
Additional signature hung  3:	1d25622be1b88d9103eb5297841c18a7
Additional signature hung 4:	a766
Additional signature hung 5:	a76615e5797198bc3156a9f92f6e54b6
Additional signature hung 6:	1d25
 Additional signature hung 7:	1d25622be1b88d9103eb5297841c18a7


Hope your help. Thanks

**Comment by ccordoba12** [comment]
Sorry but this is unrelated to Spyder itself. It really has to do with your installation and the configuration present in your system.

Since we don't have more help to offer, I'm closing this issue.
