### ISSUE TITLE
spyder not working

### ISSUE THREAD

**Issue by SHIVAMGUPTA24** [spyder-ide/spyder#8099]
when i use pyqt5==5.9.2
then spyder works but when it upgrade to 5.10.1 it dont

### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> then spyder works but when it upgrade to 5.10.1 it dont

And that's why the latest PyQt5 version we support is 5.9, so please keep using it.

**Comment by SHIVAMGUPTA24** [comment]
but if one have to use  pqt5 of higher version for other purpose then what one must do?

**Comment by ccordoba12** [comment]
Please read this to understand how to work with multiple envs:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

**Comment by SHIVAMGUPTA24** [comment]
whats the reason its not working on 5.10?
