### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by willyabraham** [spyder-ide/spyder#8113]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
no entiendo , pero cada vez que compilo se cuelga.

**Comment by ccordoba12** [comment]
Hola, por favor coloca aquí una copia del código que estás intentando ejecutar, o una versión simplificada en caso de que sea muy complejo, para poder ayudarte.

De lo contrario, tendremos que cerrar este reporte porque la información que nos diste no es suficiente.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
