### ISSUE TITLE
Unable to import h20 on spyder

### ISSUE THREAD

**Issue by komalborate** [spyder-ide/spyder#8118]
## Problem Description
Tried importing h2o package after installing latest release of h2o from h2o.ai

### What steps will reproduce the problem?
Install in Python
Run the following commands in a Terminal window to install H2O for Python.

Install dependencies (prepending with sudo if needed):
pip install requests
pip install tabulate
pip install "colorama>=0.3.8"
pip install future
Note: These are the dependencies required to run H2O. A complete list of dependencies is maintained in the following file: https://github.com/h2oai/h2o-3/blob/master/h2o-py/conda/h2o/meta.yaml.

Run the following command to remove any existing H2O module for Python.
pip uninstall h2o
Use pip to install this version of the H2O Python module.
pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o
Note: When installing H2O from pip in OS X El Capitan, users must include the --user flag. For example:

pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o --user
Optionally initialize H2O in Python and run a demo to see H2O at work.
python
import h2o
h2o.init()
h2o.demo("glm")

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```
![h2o error](https://user-images.githubusercontent.com/43761141/47283249-6e9a6880-d5da-11e8-9b77-e73b93188e6f.png)

**Comment by ccordoba12** [comment]
Well, the problem is clear: you need to install `six`, with `pip install six`.

If you have more problems of this kind, please read our guide to solve them:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

but please don't open more issues about this because these are not really Spyder problems.
