### ISSUE TITLE
Jumps in Editor when defocused, scrolled and then clicked

### ISSUE THREAD

**Issue by bgerazov** [spyder-ide/spyder#8120]
Hey guys, awesome job with Spyder 4! I'm really loving it!

This is a minor issue but a bit annoying so I'm gonna post it so it's out there (it was also the same in Spyder3).

When I defocus Spyder (say to search for some Python code in Firefox) and then I scroll down my code in the Editor and click on it, the Editor jumps back to the last cursor position and not where I clicked.

This also happens if you scroll the Editor then defocus and then click.

**Comment by ccordoba12** [comment]
> Hey guys, awesome job with Spyder 4! I'm really loving it!

Thanks for your kind words.

> When I defocus Spyder (say to search for some Python code in Firefox) and then I scroll down my code in the Editor and click on it, the Editor jumps back to the last cursor position and not where I clicked.

Please post a little video that shows this problem because I followed your instructions on Linux and I was unable to reproduce it.

Also, please fill the information we asked in our Github template. For that, please click the *New issue* green button again, copy the text from `## Versions` up to the end and fill by that info by hand. Without that info, you won't receive more help from us, sorry.

**Comment by ogliver** [comment]
I'm experiencing the same problem on Linux, Spyder version 4.1.2. 
Did you find out what caused it? Is the issue resubmitted somewhere else?

**Comment by gerazov** [comment]
It's OK on my side. Also on Linux with Spyder 4.1.2. 
I resubmitted it here #8126 but it was closed as unconfirmed.

**Comment by CAClaveau** [comment]
Same problem for me also on Ubuntu 20.04.2 LTS, with Spyder 4.2.1.I really like Spyder to code in Python, however this bug sometimes makes it very tedious to use .. Hopefully this will be fixed in future versions. Thank you for offering us this very nice IDE.

**Comment by ccordoba12** [comment]
@CAClaveau, at the end we were unable to reproduce this bug. Please open a new issue about it and post a video or an animated gif so we can see how it gets triggered.

**Comment by fyalcin** [comment]
I am also having this issue. Spyder 4.1.5 on Ubuntu 20.04.2 LTS with Gnome 3.36.8(don't know if relevant).

This is a [video](https://streamable.com/qdfrmo) showing the problem. Basically when you scroll inside Spyder and then defocus it, when you return and click somewhere, it jumps to the relative position where your cursor was in Spyder.

**Comment by ataey** [comment]
Please fix this issue. It is really, really annoying.

**Comment by CAClaveau** [comment]
@ataey I agree! I installed version 5.1.5 this week, the problem persists ... it's a "minor" bug in a way but it's quickly annoying while Spyder is a really great tool!

**Comment by ccordoba12** [comment]
@CAClaveau, please post a video of what you're seeing to see if we can reproduce this problem on our side and then fix it.

**Comment by CAClaveau** [comment]
Hi @ccordoba12, yes I will make a video this week and post it to show you what this line jump back to where the last cursor position was, not where I clicked, looks like. Thank you again for your reply.
