### ISSUE TITLE
Option to show/hide code style analysis warnings does not work

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#8121]
## Problem Description

Unchecking.checking the menu option `Source > Show code style warning (pep8)` does not do anything.

![image](https://user-images.githubusercontent.com/10170372/47296640-ea97af00-d5e0-11e8-8d9e-f497bfc28722.png)

### What steps reproduce the problem?

1. Uncheck the menu option  `Source > Show code style warning (pep8)`

### What is the expected output? What do you see instead?

Warning should disappears from the left and right panels in the Editor, but they don't. 

## Versions

* Spyder version: Master https://github.com/spyder-ide/spyder/commit/53b3619422d8d916baa7aced9afdc58833955b20
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.9.6
* PyQt version:  PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
I'm aware of this and I'll try to solve it for beta2.

**Comment by max3-2** [comment]
Any updates on this or #8461 ? 
Currently, with large files where PEP 8 is not followed, this makes spyder hilariously slow.

**Comment by ccordoba12** [comment]
> Currently, with large files where PEP 8 is not followed, this makes spyder hilariously slow.

Two things about your comment:

1. What's slow exactly? Please be precise.
2. This is still alpha stuff, so please don't complain about it. If you want beta quality, please stick to 4.0beta1, or 3.3.2 for stable stuff.

**Comment by ccordoba12** [comment]
> To be more precise: spyder editor gets slow if there are a lot of warnings

What's slow exactly? Browsing a file or getting code completion? Or something else?

>  the markers in the scroll bar block every other code introspection marker like the yellow "live searches" which I honestly learned to love!

I understand what you mean by this. Could you post a screenshot?

> this bug was introduced with 4.0.0beta1 and not just in current master

We're perfectly aware of that. We rewrote our linting and code completion architecture and so what's present in beta1 is completely different from what's coming in beta2. But until we publish beta2, there are several things we have to fix for this big change, hence the warning I gave you about using alpha stuff if you're on master.

**Comment by max3-2** [comment]
> What's slow exactly? Browsing a file or getting code completion? Or something else?

I would say the _overall_ response. There's slow scrolling, typing is lacking behind. Completion pops up late. Feels like too much on display

> > the markers in the scroll bar block every other code introspection marker like the yellow "live searches" which I honestly learned to love!
> 
> I don't understand what you mean by this. Could you post a screenshot?

<img width="1156" alt="bildschirmfoto 2019-01-14 um 19 11 09" src="https://user-images.githubusercontent.com/10244463/51131575-73b13180-1830-11e9-86df-c43c3e0d79fc.png">

The marked sidebar is clustered with warnings. If errors, TODOs or something else is displayed there, it's going under.

**Comment by krzyLadda** [comment]
its not woriking in 4.2.1 version. So I changed warning icon to background color. Path to icon: Anaconda3\Lib\site-packages\spyder\images\editor

**Comment by krzyLadda** [comment]
i solved this problem in this way. In spyder/utils/icon_manager.py  changed warning color to background color. In dark theme it is '#222b35'. So you must change line
  'warning':                 [('fa.warning',), {'color': 'orange'}],
to
  'warning':                 [('fa.warning',), {'color': '#222b35'}],
this makes annoying triangles on the left side of editor invisible. 
the markings on the right side (scroll bar) may also be there.

this solution leaves error markers, which is better than turn off all markes in preferences

**Comment by Carbolognaise** [comment]
2024 in less than a month and still not fixed
![Uploading image.png…]()
