### ISSUE TITLE
Jumps in Editor when defocused, scrolled and then clicked (versions)

### ISSUE THREAD

**Issue by bgerazov** [spyder-ide/spyder#8126]
Hey guys, awesome job with Spyder 4! I'm really loving it!

This is a minor issue but a bit annoying so I'm gonna post it so it's out there (it was also the same in Spyder3).

When I defocus Spyder (say to search for some Python code in Firefox) and then I scroll down my code in the Editor and click on it, the Editor jumps back to the last cursor position and not where I clicked.

This also happens if you scroll the Editor then defocus and then click.

But this only happens on my PC at work so I guess it's configuration related. Here's the info on my setup:

## Versions
* Spyder version: 4.0.0b1
* Python version: 3.6.6 64bits
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 16.04.3 LTS Linux4.4.0-137-generic

### Dependencies
```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.11.0     :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
I can't reproduce this and I'm also using Linux. Without a way to reproduce this problem, we'll be unable to fix it, sorry.

**Comment by bgerazov** [comment]
No worries, if it's not something that's persistent it's ok :wink:
