### ISSUE TITLE
Error window pops up when select console

### ISSUE THREAD

**Issue by takumi-ricoh** [spyder-ide/spyder#8127]
### What steps will reproduce the problem?

1.Tool > Configuration > Excecution > Console
2.Select Console Option
3.OK

then a window pop up
「不正なファイルパス」(in japanese)

means 
"wrong filepath"

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.0 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Please post a screenshot of what you're trying to do and the result you get because I don't understand what's happening in your case.

**Comment by takumi-ricoh** [comment]
I will report a little detailed situation.
· If press the "OK" button on the "Preference" screen, this error will be displayed.
· It always occurs on this screen, not limited to "Run".
· Restarted, but it did not fix it.

![image](https://user-images.githubusercontent.com/32160810/47398901-25c8e800-d771-11e8-82a1-03ccd65f6bb5.png)

![image](https://user-images.githubusercontent.com/32160810/47399003-ac7dc500-d771-11e8-87a6-7aca52a86d71.png)

**Comment by ccordoba12** [comment]
Please close Spyder, open an Anaconda prompt and run there

    spyder --reset

and try again. That should fix this error.

**Comment by takumi-ricoh** [comment]
thanks!  it fixed problem
