### ISSUE TITLE
Error on opening Spyder (via anaconda)

### ISSUE THREAD

**Issue by robinkramer2** [spyder-ide/spyder#8138]
## Description

I had issues with Pyinstaller and PyQt5 on windows, which was giving me an error. Firstly, I reinstalled PyQt5 using pip, but this did not do the trick. Next, I followed the advice on this thread: https://github.com/pyinstaller/pyinstaller/issues/3740 . The issue was solved, so hurray. 

After rebooting my computer, later that day, I could not open spyder anymore. I receive the error as described over here: https://github.com/ContinuumIO/anaconda-issues/issues/1333 . 
`$ conda install qt=5 pyqt=5 qtpy=1.1.2 --force` did the trick and made Spyder start up again. However, I got the error shown below. 

    plugin = mod.PLUGIN_CLASS(self)
    AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

Naturally I did a google search again and found this thread: https://github.com/spyder-ide/spyder/issues/7488 . This did not solve the issue unfortunately. 
*What happened here? And what can I do to make it disappear, without harming PyInstaller again?*

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.6
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.2 (OK)
sphinx >=0.6.6   :  1.7.9 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.12.1 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  1.2 (OK)
cython >=0.21    :  0.28.5 (OK)
qtconsole >=4.2.0:  4.4.1 (OK)
IPython >=4.0    :  6.5.0 (OK)
pylint >=0.25    :  2.1.1 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.1). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by ccordoba12** [comment]
I meant, this error

    plugin = mod.PLUGIN_CLASS(self)
    AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

**Comment by robinkramer2** [comment]
@ccordoba12 I have updated the issue. The error was the result of one of my intermediate steps `$ conda install qt=5 pyqt=5 qtpy=1.1.2 --force`. Updating back to spyder 3.3.1 made spyder not functional again. Could you reopen the issue?

**Comment by ccordoba12** [comment]
We can't help you to debug Pyinstaller stuff, sorry.

**Comment by ccordoba12** [comment]
I meant that we don't have time to help you debug this problem because it's not directly related to Spyder but to Pyinstaller.

**Comment by robinkramer2** [comment]
Okay, thanks for the help anyways.
