### ISSUE TITLE
PATH problem since updating macOS

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#8159]
After updating macOS to Mojave, I had an issue launching spyder:
'pyls' is not found by `subprocess.Popen` because `/usr/local/bin` is not in `os.environ['PATH']`

I fixed it by adding in spyder/plugins/editor/lsp/client.py before [Line 127](https://github.com/spyder-ide/spyder/blob/a3af9c758e2e9fc25564b73a114e491deb299e11/spyder/plugins/editor/lsp/client.py#L127)

`os.environ['PATH'] +=':/usr/local/bin'`

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for the report @impact27! We'll fix this for beta2 (we certainly need to be more robust about finding `pyls`).

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one. We should use

    sys.executable -m pyls

to start pyls.
