### ISSUE TITLE
IPython console stuck with "Connecting to Kernel..." on launch

### ISSUE THREAD

**Issue by xhain** [spyder-ide/spyder#8161]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After updating spyder the interactive console didn't start due to "ipywidgets" missing.
After installing that the interactive console doesn't start and gets stuck at "Connecting to kernel..."

### What steps reproduce the problem?

1. Open Spyder
2. ???
3.  No Profit!

### What is the expected output? What do you see instead?
I want the interactive console to work.

### Paste Traceback/Error Below (if applicable)

```python-traceback

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> 

```

## Versions

* Spyder version: spyder 3.3.1 py35_1  / spyder 3.2.6 <pip>
* Python version: python 3.5.6
* Qt version: qt 5.9.6
* PyQt version: pyqt 5.9.2 
* Operating System name/version: OSX 10.12.6

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.13.3 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.7 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.2 (OK)
```

**Comment by ccordoba12** [comment]
This is really unhelpful. Without an error message, I'm afraid we can't help you.

**Comment by xhain** [comment]
@ccordoba12 
Would love to receive an error. Then I could continue researching the issue.
I'll just wipe everything and reinstall form scratch. Closing for now.
