### ISSUE TITLE
Spyder closes by itself with no error message whenever open/save file

### ISSUE THREAD

**Issue by kgita** [spyder-ide/spyder#8164]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
Everytime I tried to open or save a file, spyder closes by itself and no error message was displayed.

**Comment by ccordoba12** [comment]
This seems like a duplicate of issue #3903. Please look there for a possible solution.

**Comment by kgita** [comment]
I did try those as instructed in issue #3903 before but still getting the same issue:
- reinstalling the Ananconda, 
- conda update qt pyqt spyder to update Spyder
- and I don't have Dell's backup and recovery installed so this should not be the error

**Comment by ccordoba12** [comment]
I'm very sorry but that's all we know about this problem.
