### ISSUE TITLE
IPython console crash on restart

### ISSUE THREAD

**Issue by RollsW** [spyder-ide/spyder#8165]
### Issue Report Checklist
* [.] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [.] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [.] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [.] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [.] Tried basic troubleshooting (if a bug/error)
    * [.] Restarted Spyder
    * [.] Reset preferences with ``spyder --reset``
    * [.] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [.] Tried the other applicable steps from the Troubleshooting Guide
* [.] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
IPython console crashes on restart

### What steps reproduce the problem?
1.  Closed the last IPython console window in Spyder using the red x (not right-click restart kernel)
2. Spyder tries to relaunch the console, but fails.
3. Loading a new console window also fails
3. Restarting Spyder resets the console, and it works again (until it doesn't)

### What is the expected output? What do you see instead?
Expected a relaunched IPython console, but it comes back with several repetitions of:
An error occurred while starting the kernel, and extensive trace-back

### Paste Traceback/Error Below (if applicable)
From the internal console: 

```WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel restarted
WARNING:traitlets:KernelRestarter: restart failed
WARNING:traitlets:kernel died: 18.00145149230957
WARNING:traitlets:kernel died: 18.000707626342773
WARNING:traitlets:kernel died: 18.004438638687134
WARNING:traitlets:kernel died: 18.00048804283142
WARNING:traitlets:kernel died: 18.005245208740234
WARNING:traitlets:kernel died: 18.0008544921875
WARNING:traitlets:kernel died: 18.000506162643433
WARNING:traitlets:kernel died: 18.003576517105103
WARNING:traitlets:kernel died: 18.00945520401001
WARNING:traitlets:kernel died: 18.003608226776123
WARNING:traitlets:kernel died: 18.00072407722473
WARNING:traitlets:kernel died: 18.001404762268066
WARNING:traitlets:kernel died: 18.000327587127686
WARNING:traitlets:kernel died: 18.001220226287842
WARNING:traitlets:kernel died: 18.000407695770264
WARNING:traitlets:kernel died: 18.00104856491089
```

From the IPython Console
```Traceback (most recent call last):
File "C:\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 272, in main
import_spydercustomize()
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 32, in import_spydercustomize
import spydercustomize
File "C:\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 25, in 
from IPython.core.getipython import get_ipython
File "C:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 55, in 
from .terminal.embed import embed
File "C:\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 15, in 
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 60, in 
from IPython.display import display
File "C:\Anaconda3\lib\site‑packages\IPython\display.py", line 16, in 
from IPython.lib.display import *
File "C:\Anaconda3\lib\site‑packages\IPython\lib\display.py", line 5, in 
from html import escape as html_escape
ImportError: cannot import name 'escape'
```

## Versions
* Spyder version: 3.3.1 
* Python version: 3.6.6 64 bit
* Qt version: 5.11.2
* PyQt version: 5.11.3
* Operating System name/version: Windows

### Dependencies
```
IPython >=4.0     :  7.0.1 (OK)
cython >=0.21     :  0.29 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.3 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

**Comment by ccordoba12** [comment]
It seems you have a file called named `html.py` somewhere in your Users directory. You need to locate it and rename it or remove it to fix this error.

**Comment by RollsW** [comment]
Well, that's embarrassing... Thanks @ccordoba12, appreciate the speedy response.

W

**Comment by ccordoba12** [comment]
No worries, it's impossible to know when a particular file will collide with a module of another package. Besides, we already have a way to prevent this and it'll be part of our next release (3.3.2).
