### ISSUE TITLE
Variable explorer doesn't show variable name which started with two char in Upper Case 

### ISSUE THREAD

**Issue by yxxthu** [spyder-ide/spyder#8166]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 7

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by jnsebgosselin** [comment]
![image](https://user-images.githubusercontent.com/10170372/47693301-920f7580-dbcf-11e8-80cb-06a1785fd604.png)

**Comment by yxxthu** [comment]
I find my variables by uncheck these two options. Thanks very much.
