### ISSUE TITLE
Move all color-related options into Preferences -> Color scheme

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#820]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-11-01T02:17:32Z_

Spyder Version:  2.1.0
Python Version:  2.7.2 
Qt Version:      4.7.4, PySide 1.0.7 on Linux 

What steps will reproduce the problem?

 To change backround color for Spyder and all its plugins, you need to click through all preference pages to find out which scheme is active.

It will be much more ituitive if all scheme selection and scheme color options were concentrated on the same page. This will require some 'extension point' mechanizm which allows plugins to plug into scheme selection page. Any ideas how to implement this?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=820_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-08-23T13:23:14Z_

**Status:** Accepted  
  **Labels:** Cat-Settings MS-v2.4

**Comment by goanpeca** [comment]
I am doing the redesign of the Syntax Highlighters/Color Scheme preferences of spyder.

This is an initial idea (location of buttons is subject to opinions so please jump in)

![image](https://cloud.githubusercontent.com/assets/3627835/11619029/c2b06c22-9c70-11e5-9945-c66c3cf83cff.png)

Clicking on create new Scheme, or Edit Selected would open something like:
![image](https://cloud.githubusercontent.com/assets/3627835/11619037/e17fd4b2-9c70-11e5-84d6-3853c88509b5.png)

----

I think the combo box should be the global color scheme selector, and every other widget should use that setting.

**Comment by goanpeca** [comment]
The color dialog could also have a "preview editor" to the right, so changes could be rendered in realtime

Also, from here it would be straightforward to export/import color schemes in other formats

**Comment by ccordoba12** [comment]
@goanpeca, awesome! This is really nice :-)

My suggestions:

1. Could it be possible to put all the buttons to the left and the preview to the right? I mean, something like:

        Color scheme               Preview
        Edit selected
        Reset
        Delete
        Create new scheme

2. The Delete button should be disabled when the selected scheme is not a custom one.

3. As you said, later we can add buttons for Import/Export and maybe also change to use a more widely used format for schemes.

**Comment by goanpeca** [comment]
@ccordoba12 

![image](https://cloud.githubusercontent.com/assets/3627835/11630744/d11442be-9ccc-11e5-9384-5763b1c5c8f8.png)

**Comment by ccordoba12** [comment]
Nice!!

More suggestions:

1. Change `Color scheme` on the dropdown menu to `Scheme:`. That would make the buttons below not so wide, and so nicer to look at. Also, Preview would be a bit wider.
2. Could add some space between `Delete` and `Create new scheme`? Even better would be to show `Create new scheme` at the bottom of the layout.

    I'm saying this because `Create new scheme` is a different  operation from the others, so we should show it visually separated from them.
