### ISSUE TITLE
Spyder4: Shift-Tab unindent works once and then changes panes

### ISSUE THREAD

**Issue by bgerazov** [spyder-ide/spyder#8200]
## Problem Description
In the Spyder4 Editor using Shift-Tab to unindent works only once on the code and then switches to the Variable explorer pane and shift-tabs through the buttons and then the variables.

### What steps reproduce the problem?
1. place cursor on a line of code.
2. press Shift-Tab multiple times.

## Versions

* Spyder version: 4.0.0b1
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 16.04.3 LTS Linux 4.4

### Dependencies
```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.11.0     :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This was already fixed in PR #8079.
