### ISSUE TITLE
Spyder 3.3.1 (Windows 10) will not launch from the .exe. It will launch from the python script but then opens an extra window.

### ISSUE THREAD

**Issue by thundergrip** [spyder-ide/spyder#8209]
## Problem Description

I am running spyder 3.3.1 updated through the Anaconda distribution. The spyder.exe file does not start spyder when executed - it brings up a window momentarily (too quickly to be read) which closes itself, and nothing further happens. 

I'm referring to site-packages > spyder-3.3.1-py35_1 > Scripts > Spyder.exe

If I launch the spyder-script.py file (in the same folder) it does launch Spyder as usual, but also opens a command prompt window which has to stay open the entire time I am using the program, which is inconvenient to say the least. I'm trying to get Spyder to run without opening extra windows and I've traced the problem back to not being able to use this .exe. 

>conda update spyder tells me that my package is up to date.

I have never submitted a topic here before so I apologize if something was done wrong, but I don't know where else to turn. Thanks in advance.

### What steps reproduce the problem?

1. Open the file Spyder.exe in the spyder installation.

### What is the expected output? What do you see instead?

Expected output: Spyder opens, displaying only one window - the Spyder window.
What happens: A small window is opened for a millisecond then disappears.

## Versions

* Spyder version: 3.3.1
* Python version: 3.5.6b 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.2 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.2 (OK)

**Comment by ccordoba12** [comment]
Please open an Anaconda prompt (cmd.exe), run there

    spyder

and report what possible errors you see there.

**Comment by thundergrip** [comment]
If I simply open a cmd.exe window and execute >spyder, Spyder launches successfully, but I don't get my prompt back. If I close the prompt window, Spyder closes. If I close Spyder, I get my prompt back.

**Comment by thundergrip** [comment]
Note: There are no error messages etc.

**Comment by ccordoba12** [comment]
If you want to hide the prompt window, use the hide option:

    spyder --hide-console

**Comment by thundergrip** [comment]
This works - but how can I embed that argument into a shortcut, so that when Spyder is launched from the Start menu, or opens when I open a .py file, I don't get the prompt window?

**Comment by thundergrip** [comment]
If this is impossible, or has been answered somewhere else, please let me know.

**Comment by ccordoba12** [comment]
Anaconda creates an Start menu entry to start Spyder. Is it not working for you?

**Comment by thundergrip** [comment]
Using that shortcut opens a command prompt window, which persists until Spyder is closed. The same thing happens if I open a .py file, with Spyder as the associated program. When I'm launching Spyder this way I can't supply the hide-console argument. For some reason, I can't use the .exe that is included in the Spyder package, which I assume has something to do with this.

**Comment by ccordoba12** [comment]
Sorry, this is not something we can help you to solve. There are some solutions in stackoverflow, please google for them.
