### ISSUE TITLE
PyLS hangs if definition cannot be located

### ISSUE THREAD

**Issue by emanspeaks** [spyder-ide/spyder#8213]
### What steps will reproduce the problem?

1.  Find a line of code with at least two levels of dot operators and no typehints, such as `self.encoding_changed.emit(finfo.encoding)`, where  the type of encoding_changed is not known
2.  Highlight the last level of dot operators (in my example, `emit`)
3.  Attempt to go to definition, either via context menu or shortcut  (Cursor should not advance to the definition)
4.  Make some change that should trigger diagnostic warning, like add whitespace to the end of a line
5.  Warning will fail to appear for the code style violation

This PyLS hang will persist until the file is closed.

## Versions

* Spyder version: 4.0.0.dev0 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  2.0.0 (OK)
pyls >=0.19.0     :  0+unknown (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by emanspeaks** [comment]
The more I think about this, it could be more of a PyLS issue.  But maybe Spyder can work around it by timing out on requests from PyLS and restart the thread if it never returns in a `response_required` request.

I'll wait to hear what you guys think before I submit an issue on PyLS.

**Comment by ccordoba12** [comment]
What PyLS version are you using?

**Comment by emanspeaks** [comment]
Oh, sorry, I checked out the 0.19.0 branch of the PyLS git repo.
