### ISSUE TITLE
Error on startup with non-clean config file (from previous files/projects open?) and recent master builds

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8216]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In recent dev builds of ``master`` (past few days) I've been getting the following error on launch, that otherwise doesn't seem to have ill effect. However, I can't easily reproduce it in a clean config (``--safe-mode``) so I'm not sure if its a bug or something with my configuration switching back and forth between Spyders. This was with just one horizontally split Editor pane. I started getting it before I ever undocked anything or used "New Window"after I'd launched Spyder with your spyder-ide/spyder#8192 once and then switched back to master and launched another Spyder, and now I get it every time I launch ``master`` or the #8192 branch without ``--safe-mode``.

@jnsebgosselin reported he gets this as well, even without any split.

```python-traceback
  File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\spyder\plugins\editor\plugin.py", line 1312, in toogle
    conf_name)
  File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\spyder\plugins\editor\plugin.py", line 1329, in _toggle_checkable_action
    if self.editorstacks:
AttributeError: 'Editor' object has no attribute 'editorstacks'
```

## Versions

* Spyder version: ``master``
* Python version: 3.6.6
* Qt version: 5.9,6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

**Comment by ccordoba12** [comment]
Fixed by #8249.
