### ISSUE TITLE
Spyder from Anaconda doesn't start

### ISSUE THREAD

**Issue by puppetrx** [spyder-ide/spyder#8223]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder just doesn't start. I tried uninstalling and installing agains last version, but to no avail

### What steps reproduce the problem?

1. Open Anaconda Promp
2. Write spyder

### What is the expected output? What do you see instead?
I expect Spyder to run, but isntead I got an error on the command line

### Paste Traceback/Error Below (if applicable)

(base) C:\Users\Usuario>spyder
Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\qtpy\__init__.py", line 199, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\app\start.py", line 190, in main
    from spyder.app import mainwindow
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 50, in <module>
    requirements.check_qt()
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt
    import qtpy
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\qtpy\__init__.py", line 205, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

``

## Versions

* Spyder version: 3.3.1
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
We can't solve this error in our side. It's usually caused by other software that also uses Qt (our graphical toolkit).

You need to look for `Qt5*.dll` libraries, see to what software they are related and uninstall them. Other than that, we don't have more advice to give you, sorry.

**Comment by puppetrx** [comment]
Could you please elaborate a little bit more? I'm a bit unsure on how to proceed

**Comment by ccordoba12** [comment]
You need to use the Search Windows tool and look for the pattern I gave you above.
