### ISSUE TITLE
Spyder doesn´t start after lib update

### ISSUE THREAD

**Issue by FdMon** [spyder-ide/spyder#8238]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

After update some python libreries spyder doesn´t start 

I use spyder since more than 2 years in the same machine. I never had a problem afeter any update but this time i´m not able to fix this issue.

### What steps reproduce the problem?

1. start spyder
2. 
3. 

### What is the expected output? What do you see instead?

I have a error related with a missed module:  'PyQt5.QtWebKitWidgets

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: libXss.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.6/site-packages/spyder/app/start.py", line 190, in main
    from spyder.app import mainwindow
  File "/opt/anaconda3/lib/python3.6/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/opt/anaconda3/lib/python3.6/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version:  Red Hat Enterprise Linux Server release 7.3 (Maipo)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> ImportError: libXss.so.1: cannot open shared object file: No such file or directory

This line signals the error: you need to find what package in your distribution provides that library (it seems it's called `libXScrnSaver` according [this thread](https://github.com/atom/atom/issues/13176)), so you need to install it with yum of dnf and the problem will be solved.
