### ISSUE TITLE
Cannot runcell if double backslash is present

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#8241]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

@bcolsen

I think this was introduced in PR https://github.com/spyder-ide/spyder/pull/7310. I was not able to reproduce the error when checking out to https://github.com/spyder-ide/spyder/commit/29e06238763bb58c003c70c70fd59dc1458386fb.

### What steps reproduce the problem?

1. Create a new file with the following content in the Editor :

```python
# -*- coding: utf-8 -*-
#%%

dirname = ("C:\\Users\\User\\test.py")

# %%
```

2. Run the cell (`Ctrl + Enter` or `Shift + Enter`).

### What is the expected output? What do you see instead?

`dirname` should be defined in the current console, but an error is raised instead.

### Paste Traceback/Error Below (if applicable)

```python-traceback
runcell('','C:/Users/User/Desktop/test.py')
  File "<ipython-input-26-0a3ec57e3b80>", line 4
    dirname = ("C:\Users\User\test.py")
              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

## Versions

* Spyder version: Spyder 4.0.0.dev0  https://github.com/spyder-ide/spyder/commit/44793430dff620e8031caacfed2338c54c77d2a8
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.6.2 
* PyQt version: PyQt5 5.6
* Operating System name/version:  Windows 10 

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
@bcolsen, could you take a look at this one? Thanks!

**Comment by bcolsen** [comment]
It looks like the escape `/`'s are being remove before running the cell.

I get the same error running: 
```
In [112]: dirname = ('C:\Users\User\test.py')
  File "<ipython-input-112-09e9a480868a>", line 1
    dirname = ('C:\Users\User\test.py')
              ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```
I can test this tonight but I think a ` 'r"""{}"""')` on this line might work:
https://github.com/spyder-ide/spyder/blob/4733c44459a086a1d60bea53f594d207b6ff9028/spyder/plugins/ipythonconsole/plugin.py#L939

**Comment by ccordoba12** [comment]
Yep, I was thinking an `r` would help to solve this.

**Comment by jnsebgosselin** [comment]
Cool, thank you very much for taking care of this! This is a little bit annoying hehe

**Comment by bcolsen** [comment]
I actually ran into this one myself this afternoon with a `\n` :-)
