### ISSUE TITLE
Triple quotes in a code cell breaks runcell

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#8267]
## Problem Description

If a triple quotes is present in the code of the cell, running the cell returns an error instead of running as expected.

### What steps reproduce the problem?

1. Create a new file with the following content in the Editor :
```python
# %%
"""
test
"""
# %%
```
2. Run the cell (Ctrl + Enter or Shift + Enter).

### Paste Traceback/Error Below (if applicable)

```python-traceback
runcell('','C:/Users/User/OneDrive/Research/PostDoc - MDDELCC/Analyses Baro/untitled0.py')
  File "<ipython-input-11-7f05e5d89a67>", line 7
    \"\"\"
          ^
SyntaxError: unexpected character after line continuation character
```

## Versions

* Spyder version: Spyder 4.0.0.dev0 https://github.com/spyder-ide/spyder/commit/ac3b24db9ee01ba12ff1044435d3abdea659878d
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.9.4
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by bcolsen** [comment]
Wow the raw string didn't do me any favors with the triple quote escaping.

I think instead of a raw string I might just replace all the `\` with `\\` before I escape the triple quotes. I think this should work. Any corner cases or better solution here I'm not thinking of?
