### ISSUE TITLE
FR: Dark theme for Outliner

### ISSUE THREAD

**Issue by gerroon** [spyder-ide/spyder#8275]
Hi

Can you please add a dark background support for the outliner. I use dark theme for the editor and such but the outliner is not respecting the color theme. That is such a contrast that it is imposible to look at the editor while the outliner is open

thanks for the great editor

**Comment by ccordoba12** [comment]
That's already implemented and it'll be part of Spyder 4. If you're using hacks to add a dark theme for Spyder 3, then there's nothing we can do about it, sorry.

Also, please don't open more issues for the dark theme if they are directed for Spyder 3, thanks.
