### ISSUE TITLE
spyder.desktop doesn't contain  WMClass variable for grouping windows

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#8290]
Desktop file delivered by Spyder after installation doesn't contain an entry for 'StartupWMClass'. 
In Ubuntu 18.04 & Gnome 3.28 it causes to grouping new instances of  Spyder apart Spyder icon on dash.
(the effect  is two Spyder icon on Dash)

Adding entry `StartupWMClass=Spyder` to spyder.desktop file solve this issue. Could you try to update the desktop file in the new release of spyder (for example 3.3.2)

The issue is caused by  the desktop entry say "Spyder3" but running instance window is called "Spyder" (tested by  `xprop WM_CLASS`)

**Comment by ccordoba12** [comment]
Ok, will do. Thanks for reporting and for giving us the solution.
