### ISSUE TITLE
More easily override conflicted shortcuts

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#8293]
During changing keyboard shortcuts of a function (let's say `func`), after pressing a new (conflicted) shortcut, the "OK" button is disabled, and a message showed that: "The new shortcut conflicts with - func1: short1". Then you have to cancel and find `func1`, and change it to `short2`. Great chances that `short2` will be conflicted to `func2`, then `func2` -> `func3` -> `func4` all the way in.  And go through `func4` -> `func3` -> `func2` -> `func1` all the way out. And finally set the shortcut you like in the first place if you still remember it.

Or you can just go to `func1` and clear the shortcut, and go back to set `func` in the first place.

Which leads to this feature request: an `override` button to override the shortcut. By override I mean if there's `func1: short1`, I want `short1` to `func`, a button to force `short1` to `func` and clear shortcut of `func1`

**Comment by ccordoba12** [comment]
@jnsebgosselin, what do you think about this one?

**Comment by jnsebgosselin** [comment]
With the changes I've made to the shortcut manager in Spyder 4, it is now possible to clear a shortcut. So this:

> Or you can just go to func1 and clear the shortcut, and go back to set func in the first place.

Is now possible.

Being able to override in a single step would be even better. So yeah, I agree with this proposition.

![image](https://user-images.githubusercontent.com/10170372/48926844-59e21680-ee9f-11e8-9f33-4cd4943521ff.png)

**Comment by jnsebgosselin** [comment]
Regarding the UI/UX part, I think we could simply change the text of the warning when there is a conflict and allow the override simply by pressing Ok. There is no need for additional button.

![image](https://user-images.githubusercontent.com/10170372/48948623-191be900-ef03-11e8-8152-9a8cbc6f0cd6.png)

The text could be something like:

_The new shortcut conflict with **file switcher**. This will unbind the shortcut from **file switcher** and assign it to **find text**_

**Comment by ccordoba12** [comment]
Nice solution @jnsebgosselin! I like it!!
