### ISSUE TITLE
Autocomplete doesn't replace text sometimes

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#8297]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Sometimes the autocomplete will not work as expected. Usually after using Spyder for a while

### What steps reproduce the problem?

1. type "np.newa"
2. press "tab" to get an autocompletion 

### What is the expected output? What do you see instead?
I would expect "np.newaxis"

Instead I get "np.newanewaxis"

## Versions

* Spyder version: Spyder 4.0.0.dev0
* Python version: Python 3.7.0 64-bit | Qt 5.9.3 | PyQt5 5.9.2 | Darwin 18.2.0 
* Qt version: 
* PyQt version: 
* Operating System name/version: Mojave 10.14.1

### Dependencies

pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
pyls >=0.19.0     :  0.21.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)

**Comment by jnsebgosselin** [comment]
I can reproduce this on Windows 10 too.

**Comment by ccordoba12** [comment]
Yes, I noticed that too. It should be an easy fix.

**Comment by ccordoba12** [comment]
@dalthviz, please work on this one.

**Comment by ok97465** [comment]
![testautocomplete](https://user-images.githubusercontent.com/22970578/49809011-3248e480-fda1-11e8-80ea-45effc163b9c.gif)

I used the latest git clone. If there is the parentheses at the end of the statement, autocomplete does not seem to work well.

**Comment by jnsebgosselin** [comment]
@ccordoba12 I do not see how PR #8387 addresses this issue since only the tests were changed.

**Comment by ccordoba12** [comment]
This issue was already fixed. I only asked @dalthviz to improve a little bit the completion test.

@ok97465, are you using the latest master?

**Comment by impact27** [comment]
I just updated to the newest master and can reproduce @ok97465

**Comment by jnsebgosselin** [comment]
> This issue was already fixed in PR #8257. I only asked @dalthviz to improve a little bit the completion test.

Ah ok thanks, that makes sense. For the record, I can reproduce this also on Windows.

**Comment by ccordoba12** [comment]
@dalthviz, I can reproduce @ok97465 example. You only need to type until line 7 to get the error.

**Comment by impact27** [comment]
I don't even need any of that: 
In an otherwise empty file:
`(sli<tab>)` gives `(slislice)`

**Comment by ccordoba12** [comment]
Ok, so it's the presence of braces which generates that! Thanks @impact27!

**Comment by bcolsen** [comment]
More generally this seems to be reproducible whenever there isn't white-space after the word that is being `<tab>` completed.

`np.ze<tab>,` gives `np.zezeros,`

Interestingly if there are non punctuation characters after the cursor the completion is even more strange:  
`np.ze<tab>m` gives `np.zeosm`

I'm not sure what to do in this case but I think `np.zerosm` would be best so the user can continue with a space or brackets and complete the line.

**Comment by bcolsen** [comment]
So the "completion" from pls is is the whole word `zeros` and not just the actual completion of `np.ze` in this case `ros`?

**Comment by bcolsen** [comment]
According to my reading of this:
https://microsoft.github.io/language-server-protocol/specification#textDocument_completion

It seems like `textEdit?: TextEdit;` should give us only the string that is needed for completion from the server.

**Comment by dalthviz** [comment]
Checking the current reponse of `pyls` [at this line](https://github.com/spyder-ide/spyder/blob/4f976e81d8c1161302b98fd9d02465e81780e7ee/spyder/plugins/editor/lsp/providers/document.py#L104), seems like the `textEdit` value is not returned. So probably that's why we made the current logic and then `textEdit` value needs to be added over `pyls` side.

So we could handle this client side (basically fixing the `insert_completion` and using the whole word) or appending the `textEdit` value to the responses of the completions of `pyls` (probably [here](https://github.com/palantir/python-language-server/blob/000993507a1bee471f4ab74f652e11875faed9a4/pyls/plugins/rope_completion.py#L51) and [here](https://github.com/palantir/python-language-server/blob/000993507a1bee471f4ab74f652e11875faed9a4/pyls/plugins/jedi_completion.py#L17)) and managing this value in the `QListWidgetItem` (probably as data)

@spyder-ide/core-developers what do you guys think?

**Comment by ccordoba12** [comment]
Let's talk about this in our meeting tomorrow.
