### ISSUE TITLE
Discord module "not found" when imported, but installed.

### ISSUE THREAD

**Issue by dp0013** [spyder-ide/spyder#8298]
### What steps will reproduce the problem?

"import discord" doesn't work and only produces the error showed in the pic below.  I double checked via the cmd window and it is installed in the Python 36_32 site-packages folder.  I can even see all the help available on this module, its methods, etc.  Why is Spyder not able to  import the discord module into my file?

## Versions

* Spyder version: 3.3.1 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by dp0013** [comment]
![discord_error](https://user-images.githubusercontent.com/12663040/48954233-50b18200-ef51-11e8-9ac2-ae640a1540be.jpg)

**Comment by dp0013** [comment]
![discord_error](https://user-images.githubusercontent.com/12663040/48954391-f664f100-ef51-11e8-8bf1-298d1c7b8900.jpg)

**Comment by ccordoba12** [comment]
This is not a Spyder problem but we wrote the following guide to help people with this kind of problems:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

Please try to solve your problem by reading it.

**Comment by dp0013** [comment]
Thanks so much!  New to use using Spyder, Anaconda, and all this jazz so the guide is much appreciated!
    On Saturday, November 24, 2018, 12:36:51 AM GMT+2, Carlos Cordoba <notifications@github.com> wrote:  
 
 
This is not a Spyder problem but we wrote the following guide to help people with this kind of problems:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

Please try to solve your problem by reading it.
