### ISSUE TITLE
unable to see some icons

### ISSUE THREAD

**Issue by aster94** [spyder-ide/spyder#8313]
* Spyder version: 3.3.1
* Python version: 3.7
* Qt version: 5.9.6
* PyQt version:  5.9.2
* Operating System name/version: kde neon 18.04

![schermata 2018-11-26 15 56 37](https://user-images.githubusercontent.com/21184718/49021978-1c79d380-f194-11e8-9995-90f8889905e2.png)

**Comment by ccordoba12** [comment]
Please read the last comment on issue #2350.

**Comment by aster94** [comment]
@ccordoba12 ok thanks! have a good work on spyder 4 :+1:
