### ISSUE TITLE
How to import new gym environment into spyder

### ISSUE THREAD

**Issue by stewegg** [spyder-ide/spyder#8315]
I am very new to the gym environment and python; however, I have years of experience in programming.
I have been trying to set up a new environment for myself by following https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym

The environment that I created is currently blank.
But I thought I would test it anyway by using gym-pull to pull it into my Spyder in Anaconda.

After installing gym-pull using pip and import gym-pull as shown below, I got an error message.
```
import os
import numpy as np
import gym
from gym import wrappers
import gym_pull
gym_pull.pull('github.com/stewegg/gym-foo')

```

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "<ipython-input-20-2337cf17fd1e>", line 5, in <module>
    import gym_pull

  File "C:\ProgramData\Anaconda3\lib\site-packages\gym_pull\__init__.py", line 6, in <module>
    from gym.configuration import logger_setup, undo_logger_setup

ModuleNotFoundError: No module named 'gym.configuration'

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

I must have miss something.
Any help would be greatly appreciated!

Thank you very much

**Comment by ccordoba12** [comment]
What does this have to do with Spyder? I don't get it...

**Comment by stewegg** [comment]
> What does this have to do with Spyder? I don't get it...

I am sorry. As I am new to this. Could you please point me to the correct place about this issue?

**Comment by ccordoba12** [comment]
I'd say on the gym repo:

https://github.com/openai/gym/issues
