### ISSUE TITLE
Some issues with the Plots plugin

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#8320]
While working on PR #8192, I discovered a couple of problems with the Plots plugin:

1. Miniatures are not shown on Python 2. I went back to the PR where the plugin was introduced and verified that the problem was present from the beginning.

2. The Save and Remove buttons on the miniatures scrollbar are not shown correctly in the dark theme:

    ![seleccion_003](https://user-images.githubusercontent.com/365293/49105698-578d0d00-f24f-11e8-956a-06503c306eda.png)

    @jnsebgosselin, I think you crafted things very well for Fusion but did not considered other themes ;-)

3. By default plots are shown in the IPython console *and* the Plots plugin. I think we should change that and instead:

    1. Print a message in the console the first time, saying that plots are now rendered in the Plots plugin.
    2. This message should also mention how to get the previous behavior.

@jnsebgosselin, could you help us with this one? Thanks!

**Comment by jnsebgosselin** [comment]
> @jnsebgosselin, could you help us with this one? Thanks!

Sure, I'll take a look at it very soon. Thank you very much for taking the time to log these issues.

**Comment by ccordoba12** [comment]
Sure, no problem :+1:

**Comment by ccordoba12** [comment]
@jnsebgosselin, since these issues are very simple, I'm going to ask @dalthviz to do it. Hope that's ok for you.

**Comment by jnsebgosselin** [comment]
Sure let's go! I'm very busy right now, so that is very welcomed.
