### ISSUE TITLE
Show inputs to function

### ISSUE THREAD

**Issue by Jakobhenningjensen** [spyder-ide/spyder#8324]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [ x] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ x] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When you want to call a function, say `np.array(x)` you get to see the input after `np.array(` but as soon you start typing the input variable (and their default values) disapear. In Rstudio you can see them again by using "tab". 
Is there a way to implement that aswell? If you have a lot of inputs in, say `sklearns.svm.svc` and you can't remember them all, it really helps to be able to see them fast in that way.

### What steps reproduce the problem?

1. Calling a function
2. 
3. 

### What is the expected output? What do you see instead?
expected: function(<tab>) shows the inputs for the function
what I see: nothing

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.1
* Python version: 3.6.7 64 bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version:  Windows 10 /Ubuntu 18.04

### Dependencies
```
IPython >=4.0     :  7.1.1 (OK)
cython >=0.21     :  0.29 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

**Comment by ccordoba12** [comment]
> In Rstudio you can see them again by using "tab".
Is there a way to implement that aswell?

Shift+tab

**Comment by Jakobhenningjensen** [comment]
That does not work either

**Comment by ccordoba12** [comment]
Sorry, it has to be pressed next to a comma.

**Comment by Jakobhenningjensen** [comment]
It works if you press "tab" (not shift+tab) next to a comma.
