### ISSUE TITLE
spyder encounter a problem

### ISSUE THREAD

**Issue by ElonXie** [spyder-ide/spyder#8325]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

ValueError: Invalid Signature: b'7c24c07eeed4b7dc1dbba6d7709f571c051be78286507978e9cbc788b3f33ecc'
ValueError: Invalid Signature: b'7c24c07eeed4b7dc1dbba6d7709f571c051be78286507978e9cbc788b3f33ecc'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by ElonXie** [comment]
Hi,Carlos:
    Actually I'm not familiar with Github, so it's exciting to receive your solution.
    I just uninstalled my Anaconda and ,instead, installed an earlier version, and  it worked.
    Very thanks for your help!
   
| |
NJU-谢东瀚
|
|
sdaxdh@163.com
|
签名由网易邮箱大师定制
On 11/28/2018 22:38，Carlos Cordoba<notifications@github.com> wrote：

This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

conda update spyder
