### ISSUE TITLE
Kernel died, restarting

### ISSUE THREAD

**Issue by mengdexiaolian** [spyder-ide/spyder#8328]
## Description
when i run the following code, spyder happens "Kernel died, restarting". my dlib version is 19.7.0.
i have debugged and found that it caused by this line: dets = detector(img, 1) 

code:
import dlib
import cv2

detector = dlib.get_frontal_face_detector() #获取人脸分类器

#pictures = ["obama", "jobs","silicon_valley"]
pictures = ["obama"]

# 传入的命令行参数
for picturename in pictures:
    picture = picturename+".jpg"
    # opencv 读取图片，并显示
    img = cv2.imread(picture, cv2.IMREAD_COLOR)
    print("img", img.size)

    # 摘自官方文档：
    # image is a numpy ndarray containing either an 8bit grayscale or RGB image.
    # opencv读入的图片默认是bgr格式，我们需要将其转换为rgb格式；都是numpy的ndarray类。
    b, g, r = cv2.split(img)    # 分离三个颜色通道
    img2 = cv2.merge([r, g, b])   # 融合三个颜色通道生成新图片
    print("img2", img2.shape)

    dets = detector(img, 1) #使用detector进行人脸检测 dets为返回的结果
    print("Number of faces detected: {}".format(len(dets)))  # 打印识别到的人脸个数
    # enumerate是一个Python的内置方法，用于遍历索引
    # index是序号；face是dets中取出的dlib.rectangle类的对象，包含了人脸的区域等信息
    # left()、top()、right()、bottom()都是dlib.rectangle类的方法，对应矩形四条边的位置
    for index, face in enumerate(dets):
        print('face {}; left {}; top {}; right {}; bottom {}'.format(index, face.left(), face.top(), face.right(), face.bottom()))

        # 在图片中标注人脸，并显示
        left = face.left()
        top = face.top()
        right = face.right()
        bottom = face.bottom()
        cv2.rectangle(img, (left, top), (right, bottom), (0, 255, 0), 3)
        cv2.namedWindow(picture, cv2.WINDOW_AUTOSIZE)
        cv2.imshow(picture, img)

# 等待按键，随后退出，销毁窗口
k = cv2.waitKey(0)
cv2.destroyAllWindows()

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
IPython >=4.0    :  5.3.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.13.1 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
numpy >=1.7      :  1.15.4 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

```

**Comment by ccordoba12** [comment]
Are you able to run your code without problems outside Spyder?

**Comment by mengdexiaolian** [comment]
when i run in pycharm, it still failed, the error is reported as following:
Process finished with exit code -1073741795 (0xC000001D). I guessed whether the dlib is not matched or operational system is not matched. I am working on win7, AMD-64bit PC.

**Comment by ccordoba12** [comment]
> when i run in pycharm, it still failed

Then this is not an Spyder error but an error or problem in your code, sorry.
