### ISSUE TITLE
Describe plugin loading order

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#833]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-11-12T06:22:42Z_

What steps will reproduce the problem?

 It is not clear how to approach Spyder customization without clear docs on plugin loading process. What is the expected output? What do you see instead? I expect a picture of Spyder internals and loading process to see where I could 'plug in'.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=833_

**Comment by ccordoba12** [comment]
Spyder plugin order can be seen in `spyderlib/spyder.py`. Other than that, I don't think we're going to do something else about it.
