### ISSUE TITLE
Discrepancy in ```sudo apt install spyder3``` vs ```conda install spyder```

### ISSUE THREAD

**Issue by saber7165** [spyder-ide/spyder#8333]
## Problem Description
Two cases:
1. Install spyder in a virtual env using ```conda install spyder``` in that env. Then launch spyder and type 
```
import utils
```
gives 
```
Traceback (most recent call last):

  File "<ipython-input-1-69d9c258b31d>", line 1, in <module>
    import utils

ModuleNotFoundError: No module named 'utils'
```

2. Install spyder using ```sudo apt install spyder3```. Then launch spyder and try 
```
import utils
```
It does import utils:
```
In [4]: utils
Out[4]: <module 'utils' from '/usr/lib/python3/dist-packages/spyder/utils/__init__.py'>
```

I prefer the behavior in 1 as 2 would interfere with my local utils package.

**Comment by saber7165** [comment]
Thanks for the description. Digging a bit into this, it seems that 2 comes with the following in sys.path:
```
'/usr/lib/python3/dist-packages',
'/usr/lib/python3/dist-packages/spyder',
```
Which is not necessary when working in a virtual env and actually interferes with other modules in the env. 
So you are saying this is an issue with Debian?

**Comment by saber7165** [comment]
I did some more digging. So when I launch spyder3 and run the following:
```
import sys
sys.path
```
I get 
```
['',
 '/usr/lib/python36.zip',
 '/usr/lib/python3.6',
 '/usr/lib/python3.6/lib-dynload',
 '/usr/local/lib/python3.6/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3/dist-packages/IPython/extensions',
 '/home/ubuntu/.ipython']
``` 
Then, I go to "preferences" -> "Python interpreter", select "Use the following python interpreter", and point it to my env python3.6. Now typing 
```
import sys
sys.path
```
gives 
```
['',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3/dist-packages/spyder',
 '/home/ubuntu/miniconda3/envs/hvtrac/lib/python36.zip',
 '/home/ubuntu/miniconda3/envs/hvtrac/lib/python3.6',
 '/home/ubuntu/miniconda3/envs/hvtrac/lib/python3.6/lib-dynload',
 '/home/ubuntu/miniconda3/envs/hvtrac/lib/python3.6/site-packages',
 '/usr/lib/python3/dist-packages/IPython/extensions',
 '/home/ubuntu/.ipython']
```
So why these lines are added?
```
'/usr/lib/python3/dist-packages',
'/usr/lib/python3/dist-packages/spyder',
```

**Comment by ccordoba12** [comment]
Those are added by the Debian/Ubuntu Python version and we don't have control over that, sorry.
