### ISSUE TITLE
SPyder 4.0.0b1 fails to install with latest Anaconda.

### ISSUE THREAD

**Issue by ivanarnold** [spyder-ide/spyder#8335]
### Issue Report Checklist

* [ *] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [* ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ *] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ *] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [ *] Restarted Spyder
    * [* ] Reset preferences with ``spyder --reset``
    * [ *] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [* ] Tried the other applicable steps from the Troubleshooting Guide
* [* ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder 4.0.0b1 fails to  install with newest Anaconda.

### What steps reproduce the problem?

1. Download latest Anaconda
2. Follow install instructions for Spyder 4.0.0b1
3. Watch it fail with requirement  "spyder=4.0.0b1 -> python[version='>=3.6,<3.7.0a0']"

### What is the expected output? What do you see instead?
Spyder 4.0.0b1 should install.

I think this issue is probably simple, but the latest version of Anaconda (5.3.1) fails when trying to install the beta (4.0.0b1) version of Spyder. It seems that this beta requires a Python version less than 3.7.0, and the new Anaconda has 3.7.1.

Downgradng Anaconda to 5.1 (Python 3.6) fixes the issue. I haven't tried other versions of Anaconda, but this seems a simple issue of version mismatch. If Spyder 4.0.0b1 runs fine with Python 3.7.1 maybe the dependencies could be changed? Otherwise you might want to add this issue to the beta install page.

Sorry if this has been addressed elsewhere. A quick google and forum search didn't turn anything up.

**Comment by ccordoba12** [comment]
This happens because at the time we released beta1, Python 3.7 was not available so we were unable to create packages for it.

We'll fix that in a couple of hours by creating packages for it.

**Comment by ivanarnold** [comment]
Awesome! I figured it was something simple like that.

Thanks very much for the SPyder IDE. Every time I try using something else it becomes clear how useful it is for scientific programming and analysis and I come straight back.

**Comment by ccordoba12** [comment]
Thanks for your kind words!
