### ISSUE TITLE
AttributeError in profiler

### ISSUE THREAD

**Issue by lazarp2** [spyder-ide/spyder#8336]
### What steps will reproduce the problem?

Press F10
a window popped up
pressed ESC to close it

### Traceback
```python-traceback
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 264, in <lambda>
    self.finished(ec, es))
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 335, in finished
    self.show_data(justanalyzed=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 362, in show_data
    self.datatree.show_tree()
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 526, in show_tree
    rootkey = self.find_root()  # This root contains profiler overhead
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 507, in find_root
    self.profdata.sort_stats("cumulative")
AttributeError: 'NoneType' object has no attribute 'sort_stats'
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by JoelGodin** [comment]
For info: Doesn't happen on OSX.
If you go to the menu at the top, hit 'Run' > 'Profile'  do you get the same error?

**Comment by ccordoba12** [comment]
Please give us a step-by-step description to reproduce this error. Else we don't know how to solve it.

**Comment by lazarp2** [comment]
I have seen the issue I reported one more timeBut now, it doesn't happen, and hitting run > profile doesn't cause it either. FYI, I am running Windows 10 
thanks 
    On Friday, November 30, 2018, 7:37:49 PM CST, Joel Godin <notifications@github.com> wrote:  
 
 
For info: Doesn't happen on OSX.
If you go to the menu at the top, hit 'Run' > 'Profile' do you get the same error?
