### ISSUE TITLE
IOError: Could not start spyder.utils.introspection.plugin_client.PluginClient

### ISSUE THREAD

**Issue by gibsondanield** [spyder-ide/spyder#8338]
## Description

**What steps will reproduce the problem?**

1. Not sure, spyder was running in background at the time

**Please provide any additional information below**

  File "/usr/lib/python2.7/dist-packages/spyder/utils/introspection/plugin_client.py", line 158, in _on_finished
    self.run()
  File "/usr/lib/python2.7/dist-packages/spyder/utils/introspection/plugin_client.py", line 104, in run
    raise IOError('Could not start %s' % self)
IOError: Could not start <spyder.utils.introspection.plugin_client.PluginClient object at 0x7fdd75944cc8>

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 2.7.15rc1
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.5.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sphinx >=0.6.6    :  1.6.7 (OK)
rope >=0.9.4      :  0.10.5 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0;<6.0:  5.4.1 (OK)
pylint >=0.25     :  1.8.2 (OK)

```

**Comment by ccordoba12** [comment]
Please update to our latest version (3.3.2) and try again.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
