### ISSUE TITLE
Bug with tkinter destroy

### ISSUE THREAD

**Issue by jproy** [spyder-ide/spyder#8346]
### What steps will reproduce the problem?

In the following program, I can close the window with its close button but neither with the 'Esc' binding, nor the button callback. I am sent to the IPython console but the window stays here with a spinning wheel ! Works fine in the Terminal or with Anaconda IDLE. I am on Mac, High Sierra, Anaconda and Spyder last versions (IPython 7.1.1, Spyder 3.3.2). I suspect a problem with Spyder.

    from tkinter import *
    class Myapp(object):
        def __init__(self):
            self.root = Tk()
            self.root.geometry('150x100+1+1')
            self.root.title('Root')
            self.root.bind('<Escape>', lambda e: self.root.destroy())
            self.button = Button(self.root, text='End Program', command=self.end)
            self.button.place(x=10, y=45)
            self.L = [1,2,3]   # result of an omitted computation
        def end(self):
            self.root.destroy()
    app = Myapp()
    app.root.mainloop()
    print(app.L)

Any hint ? Thanks.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by jproy** [comment]
Nobody can help ?...

**Comment by ccordoba12** [comment]
Already answered in StackOverflow. Please don't open an issue here and an question there for next time, it's just makes us waste more time.

**Comment by jproy** [comment]
Hum. If I deactivate the check-box  and suppress the mainloop call, it worked the first time but not anymore after. I don't even see the window now, and the console prints immediately [1,2,3]. Even when restarting Spyder. Did you try that on a Mac ?

**Comment by ccordoba12** [comment]
I don't own a mac, sorry. It works fine on Linux though.

**Comment by jproy** [comment]
That is the problem.
IMHO you should ensure it works on any platform without tweaking the program or adapting the prefs of the IDE to such and such program ? My 2 cents of course. 
As for my book I am obliged (temporarily I hope) to ask the reader to move to IDLE for tkinter programs. Sad, I liked Spyder after years of teaching with IDLE...
My best to your team.

    -jpr

**Comment by ccordoba12** [comment]
> IMHO you should ensure it works on any platform without tweaking the program or adapting the prefs of the IDE to such and such program ? My 2 cents of course.

That's technically not possible because users can create GUIs not just in Tk but also in PyQt, Wx, Gtk, OpenGL, etc. So some amount of configuration is needed. And that's why you need to run `%gui tk` or `%matplotlib tk`, etc; or deactivate our support for Matplotlib graphics entirely. But that's something we won't do because our main target are scientists/engineers and the first thing they need to do is to plot things.

> As for my book I am obliged (temporarily I hope) to ask the reader to move to IDLE for tkinter programs.

That's your choice, but (as I said) your code works fine on Linux and (I just tested it unmodified) on Windows too.

Since none of the core developers uses macOS, then we can't test things there easily.

> Sad, I liked Spyder after years of teaching with IDLE...

Our purpose is not to replace IDLE.

**Comment by mxardre** [comment]
Have the same issu on macos mojave Spyder 4.2.5 with anaconda.
That is quite sad.
None of the solution worked
