### ISSUE TITLE
ImportError when I try to run a program

### ISSUE THREAD

**Issue by gsagostini** [spyder-ide/spyder#8352]
### What steps will reproduce the problem?

I tried to run a program (that was working fine on Spyder in another computer) and I get an importError, saying that

"Importing the multiarray numpy extension module failed. Most likely you are trying to import a failed build of numpy."

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
That's an installation problem, not a Spyder one. If you're using Anaconda, you can solve it by closing Spyder, opening an Anaconda Prompt, running there

    conda install -f numpy

and trying again.
