### ISSUE TITLE
file cleared after close spyder while not responding

### ISSUE THREAD

**Issue by reneroelands** [spyder-ide/spyder#8354]
### What steps will reproduce the problem?

I was debugging a python script when spyder became not responsive. When i closed the spyder application and restarted, file i was working on was empty.

This problem is sufficiently annoying to stop using spyder

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
> This problem is sufficiently annoying to stop using spyder

We understand and we're taking measures to fix this in our next major version (Spyder 4) by providing autosaving functionality and being more carefull when savinf files.

Sorry for the troubles this is causing you in our current version.
