### ISSUE TITLE
Spyder 4 slow on macOS Mojave

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#8355]
## Problem Description
On mojave 10.14.1, spyder 4 is slow and unresponsive. The console sometimes needs minutes to parse simple commands. Line ending and confirm executions work mixed, sometimes even do nothing. Console crashes often.
pip packages up to date:

```
ipykernel                5.1.0     
ipython                  7.2.0   
ipython-genutils         0.2.0     
ipywidgets               7.4.2     
```

### What steps reproduce the problem?

1. upgrade to spyder 4.0 beta1 from spyder 3

### What is the expected output? What do you see instead?

Have spyder4 with the same performance as spyder3. However, its slow and unstable. Can anyone reproduce?

## Versions

* Spyder version: 4.0.beta1
* Python version: 3.7.1
* Qt version: 5.11.2
* PyQt version: 5.11.3
* Operating System name/version: macOS 10.14.1

**Comment by ccordoba12** [comment]
This is not a problem in Spyder but in ipykernel. Please see the last comments of issue #2902 for the solution.
