### ISSUE TITLE
How to get the table name in .docx file using pytohn

### ISSUE THREAD

**Issue by VijayaLakshmiArthanari** [spyder-ide/spyder#8356]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am trying to get the name of the table in .docx file.For eg, I am trying to get the 'Education qualification' table in CV's. Some of the resume having more tables. From that table how can i identify my requirement.
### What steps reproduce the problem?

If we identify the table name, We will found the table exactly.

### What is the expected output? What do you see instead?
Only the 'Education Qualification' table as a out put.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.2.8
* Python version: 2.7
* Qt version: 4.8.7
* PyQt version: 4.10.4
* Operating System name/version: Windows7-64 bit

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This is not a general Python support forum, but a place to report problems about Spyder.

Due to that, I'm sorry but I'm going to close this issue.
