### ISSUE TITLE
IPython console: add horizontal scrolling bar 

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#8361]
This is rather a feature request or an option for those who like it.

I use quite often pandas and sometimes the columns number is too large. Printing the columns and inspecting few first rows is a common practice. Spyder wraps the columns on top of each other and thus the user sometimes find it hard to analyse quickly the data specially if the work is done in lower than 15 inch laptop screen. 

![spyder](https://user-images.githubusercontent.com/22060413/49423523-b0006500-f78f-11e8-9ae8-80520b9c69ec.gif)

For example in Pycharm the IPython windows shows the full length of all columns. It includes a horizontal scroll bar if the screen size does not  allow displaying all columns.

Therefore, is it possible to make an option for the user to show a scrolling bar in IPython console which should avoid long texts or Dataframes being wrapped around.

![pycharm](https://user-images.githubusercontent.com/22060413/49423674-24d39f00-f790-11e8-8928-517e593a56d8.gif)

Thanks alot.

Regards

* Spyder version: 4 beta1
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version: windows

**Comment by ccordoba12** [comment]
This is not something we can solve here. Please open it in this repo:

https://github.com/jupyter/qtconsole
