### ISSUE TITLE
Support color scheme Sublime Text Monokai Extended (and more)

### ISSUE THREAD

**Issue by PanderMusubi** [spyder-ide/spyder#8371]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Please, support color scheme Sublime Text Monokai Extended, see details at https://github.com/eclipse-color-theme/eclipse-color-theme/blob/master/com.github.eclipsecolortheme/themes/sublime-text-monokai-extended.xml

Perhaps, a script could be used to convert all themes from https://github.com/eclipse-color-theme/eclipse-color-theme/tree/master/com.github.eclipsecolortheme/themes to Spyder color themes. As a few of these thems are already available as a scheme in Spyder, settig up such conversion should be relatively easy.

Benefit for the end user is that his or her favorite color scheme which they might be used to in other IDEs, is also availavle in Spyder.

See also https://ethanschoonover.com/solarized/ If this issue is implemented, Spyder could also be listed there.

### What steps reproduce the problem?

1. Go to Preferences
2. Go to Syntax coloring
3. Change color scheme

### What is the expected output? What do you see instead?

That Sublime Text Monokai Extended would be available.

![2018-12-05-163131_1920x1080_scrot](https://user-images.githubusercontent.com/198964/49524796-b801f700-f8ac-11e8-9b26-7452930e23ba.png)

## Versions

* Spyder version: 3.2.6
* Python version: 3.6.7
* Qt version: 5.11.1
* PyQt version: 5.11.2
* Operating System name/version: Ubuntu 18.10

**Comment by ccordoba12** [comment]
We don't have time for this, so pull requests are welcome.

**Comment by PanderMusubi** [comment]
(probably note to self) only 15 colors per theme to convert to scheme and add to https://github.com/spyder-ide/spyder/blob/master/spyder/defaults/defaults-3.0.0.ini#L366

**Comment by PanderMusubi** [comment]
Here is a conversion https://github.com/PanderMusubi/convert-theme-to-scheme

I have tested it by copy pasting the output into `spyder.ini` and it works. Best is that some core developers from Spyder test this too.

Merging the output of this script with the existing schemes has to be done manually, but that is easy. Care has to be taken not to include duplicate schemes.

**Comment by ccordoba12** [comment]
As I said, please create a pull request for this if you want to see it merged. We're quite busy and don't have time to test it ourselves.

----

> (probably note to self) only 15 colors per theme to convert to scheme and add to https://github.com/spyder-ide/spyder/blob/master/spyder/defaults/defaults-3.0.0.ini#L366

Don't touch that file, there's no need of that. New settings need to go to

    spyder/config/main.py

**Comment by PanderMusubi** [comment]
(Comment from PR) For this and future PRs, please use https://github.com/PanderMusubi/convert-theme-to-scheme which will generate the Python code to include. It also generated an INI file to easily test the schemes. I will leave the squashing and rebasing to you. If you need me to help with convert-theme-to-scheme, please let me know.
