### ISSUE TITLE
Astropy Quantity Array not Rendering in Console

### ISSUE THREAD

**Issue by KylePoe** [spyder-ide/spyder#8372]
### What steps will reproduce the problem?

# Enter in console
from astropy import units as u
import numpy as np

a = u.quantity.Quantity(np.random.rand(10))

a

This was not a problem until the most recent update. It used to print the array in a rendered fashion, but it now prints only the first member of the array.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.3
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Darwin 16.7.0

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.6.6 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.22.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.2.1 (OK)
matplotlib >=2.0.0:  2.1.2 (OK)
pylint >=0.25     :  1.8.2 (OK)
```

**Comment by KylePoe** [comment]
My apologies, I'm not well-acquainted with Markdown, so this doesn't look quite how I expected. I hope it is still legible.

**Comment by ccordoba12** [comment]
Are you sure this is a problem with Spyder and not with an update in Astropy or Numpy?

**Comment by KylePoe** [comment]
I am not sure. I updated everything in Anaconda at the same time, so I suppose it could be anything. I unfortunately lack the expertise to further investigate that aspect of things, I just wanted to bring it to someone's attention.

**Comment by ccordoba12** [comment]
We'd like to help you but unfortunately we lack the resources to debug where this problem is coming from. Besides, I really doubt it has to do with Spyder because we have very few interactions with Astropy and Numpy in our code.
