### ISSUE TITLE
Spyder 4: Is variable refactoring available?

### ISSUE THREAD

**Issue by shivendra90** [spyder-ide/spyder#8404]
So I'm using the latest build of Spyder 4 beta and would really like if some refactoring capability was available. Of course I can use VSC or PyCharm for this, but a really intelligent and advanced editor for Spyder 4 would make it the choice of scientific computing. is there anything similar that I can enable it (like some plugin)?

**Comment by ccordoba12** [comment]
Sorry, refactoring is not in the plans for Spyder 4.
