### ISSUE TITLE
Cannot detect my GTX1060 GPU

### ISSUE THREAD

**Issue by lamhoson** [spyder-ide/spyder#8407]
Spyder 3.3.2

 x = tf.random_uniform([3, 3])
print("Is there a GPU available: "),
print(tf.test.is_gpu_available())
print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))
x = tf.random_uniform([3, 3])
print("Is there a GPU available: "),
print(tf.test.is_gpu_available())
print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))
Is there a GPU available: 
False
Is the Tensor on GPU #0:  
False
Is there a GPU available: 
False
Is the Tensor on GPU #0:  
False

**Comment by ccordoba12** [comment]
You need to start Spyder from a system terminal (xterm, cmd.exe or Terminal.app) because Tensorflow needs from environment variables defined there.

Please report back if that works or not for you.

**Comment by lamhoson** [comment]
I tried to start it from Anaconda3's DOS terminal.  Same problem.


The environment should be set by following installation already:
conda create -n tensorflow_gpuenv tensorflow-gpu
conda activate tensorflow_gpuenv


How could i install Spyder and GPU version TensorFlow in a separate environment from Anaconda3 such that everything is know ?




发自网易邮箱 iPhone 版
On 12/11/2018 05:36，Carlos Cordoba<notifications@github.com> wrote：

You need to start Spyder from a system terminal (xterm, cmd.exe or Terminal.app) because Tensorflow needs from environment variables defined there.

Please report back if that works or not for you.

**Comment by ccordoba12** [comment]
Sorry, I don't know because I don't use Tensorflow.

Besides, I'm closing this issue because it's not directly related to Spyder, sorry.
