### ISSUE TITLE
Can't define function in console (Spyder 3.3.2)

### ISSUE THREAD

**Issue by shivendra90** [spyder-ide/spyder#8410]
### What steps will reproduce the problem?

1. Open a normal Spyder session.
2. Try defining a function inside the console.
3. Press enter after defining the first varable under the function scope.

For example, I was defining a simple function that would plot a visualisation, like so:

    def plot_visual(dep, indep):
        X_grid = np.arange(min(X), max(X), 0.01)
    
Here I would want to add 5-6 more lines within the function scope but pressing enter does not __indent__ the code automatically as it should and instead ends the definition and what I get is a new global console line, like this:

    In [7]: def plot_visual(dep, indep):
                X_grid = np.arange(min(X), max(X), 0.01)
    
    In [8]:

Which is of course not what I require. This is the first time I'm seeing this problem. Am I missing some setting here? To my knowledge, I'm working on default settings and have defined several functions before.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
psutil >=0.3      :  5.4.3 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.27.3 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.3 (OK)
```

**Comment by ccordoba12** [comment]
This was fixed in qtconsole **4.4.3**, but that version was not released by Anaconda yet (in case you're using it).

@jjhelmus, could you help us with updating qtconsole to that version? Thanks!

**Comment by jjhelmus** [comment]
qtconsole 4.4.3 packages are now available in the `defaults` channel.

**Comment by ccordoba12** [comment]
Thanks a lot for the quick response @jjhelmus!

**Comment by shivendra90** [comment]
Confirmed `qtconsole` updated to 4.4.2 and function definition working properly.
