### ISSUE TITLE
Fail to connect to remote kernel

### ISSUE THREAD

**Issue by JensHumrich** [spyder-ide/spyder#8411]
### What steps will reproduce the problem?

Tried to use Spyder to connect to a remote kernel. The connection is working if I try to connect via 
ipython qtconsole --existing ./kernel-21278.json --ssh developer@192.168.199.4
but this time it was causing this error

### Traceback
```python-traceback
  File "C:\Users\V363958\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1060, in create_client_for_kernel
    password)
  File "C:\Users\V363958\AppData\Local\Continuum\anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1782, in _create_client_for_kernel
    client.shellwidget.kernel_client = kernel_client
  File "C:\Users\V363958\AppData\Local\Continuum\anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 57, in kernel_client
    kernel_client.iopub_channel.message_received.connect(self._dispatch)
AttributeError: 'QtKernelClient' object has no attribute 'iopub_channel'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.14.3 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.28.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.4.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
```

**Comment by JensHumrich** [comment]
The error can be reproduced by also opening a succesful connection to the server via 
ipython qtconsole --existing ./kernel-21278.json --ssh developer@192.168.199.4
[TerminalIPythonApp] WARNING | Subcommand `ipython qtconsole` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter qtconsole` in the future
[JupyterQtConsoleApp] Forwarding connections to 127.0.0.1 via developer@192.168.199.4
[JupyterQtConsoleApp] To connect another client via this tunnel, use:
[JupyterQtConsoleApp] --existing kernel-21278-ssh.json

and then using the kernel-21278-ssh.json file to connect.

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.2). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by JensHumrich** [comment]
Sorry, thought I updated. Error is solved.

**Comment by ccordoba12** [comment]
No problem, glad things are working for you now.
