### ISSUE TITLE
runfile unwanted backslash convertion in args

### ISSUE THREAD

**Issue by beheleke** [spyder-ide/spyder#8413]
## Problem Description

I use menu->"run configuration per file" and enter "\x \y \z" as "command line options" which results in

`runfile('path/to/file.py', args='/x /y /z', wdir='path/to')`

The issue is, that i get unwanted backslash convertion in the _args_ argument. So, testing and debugging the script with arguments is not possible.

### What is the expected output? What do you see instead?

I expect:
`args='\x \y \z'` instead ` args='/x /y /z'`

also, since I'm on windows I expect also backslashes in paths instead forward slashes.

## Versions
* Spyder version: 3.3.1
* Python version: 3.6.5
* Operating System name/version: Win 10, 64b it

**Comment by ccordoba12** [comment]
Thanks for reporting. We don't have time to address this but you're welcome to submit a pull request to fix it.

**Comment by goanpeca** [comment]
@impact27 you have worked a bit with this part, right?

Do you know if this is still an issue?

**Comment by impact27** [comment]
Looks like this is fixed:
```
In [1]: runfile('/Users/quentinpeter/Desktop/untitled1.py', args='\x \y \z', wdir='/Users/quentinpeter/Desktop')
  File "<ipython-input-1-67dfa52b68bd>", line 1
    runfile('/Users/quentinpeter/Desktop/untitled1.py', args='\x \y \z', wdir='/Users/quentinpeter/Desktop')
                                                            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \xXX escape
```

PS: if you actually want to get `\x`, you need to escape the backslash: `\\x`
