### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by migai** [spyder-ide/spyder#8417]
### What steps will reproduce the problem?

I opened spyder in Windows.  Seems to work fine.  Not sure why this "internal problem" window popped up.

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.8.2 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.13.1 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  1.3 (OK)
cython >=0.21    :  0.29 (OK)
qtconsole >=4.2.0:  4.4.2 (OK)
IPython >=4.0    :  7.2.0 (OK)
pylint >=0.25    :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.2). Please update by opening the Anaconda Prompt and running there

    conda update spyder
