### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by BalajiSysenso** [spyder-ide/spyder#8420]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
When Iam run a file that contains some large code, It shows as Kernel died. And It restarting the kernal, After restarting the file has been running successfully. After next time I have same issue, That is file running only after kernel restarting, I mean its executing only the second time of running the same script.

Running First time : Kernel died, restarting
Run again the same script : Running successfully.

Kindly help me to solve this issue.

**Comment by ccordoba12** [comment]
Sorry but the your description is not enough to help you.

You need to simplify your program as much as you can and post here or send us a version that generates the error you're seeing.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
