### ISSUE TITLE
Backgroud color of Plotwidget in dark theme

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#8443]
## Problem Description
The background color of the plot widget becomes white after click "remove images".  

![plot_wiget_color_error](https://user-images.githubusercontent.com/22970578/50043351-e2766000-00b5-11e9-9f64-b4ad9e941e08.gif)

So I commented out 758 line of figurebrower.py.

    # self.setStyleSheet("background-color: white")

![plot_wiget_color_correct](https://user-images.githubusercontent.com/22970578/50043374-33865400-00b6-11e9-9161-3bfbb8880c25.gif)

## Versions

* Spyder version: 4.0.0 dev0 (lastest master)
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: linux(manjaro)/4.19.6

**Comment by ccordoba12** [comment]
@dalthviz, an easy one for you.
