### ISSUE TITLE
NameError: name 'runcell' is not defined

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#8447]
## Problem Description
![image](https://user-images.githubusercontent.com/22970578/50069773-72560000-01c3-11e9-86d1-b287d3f4c4d4.png)

I tried to run cell, but I am getting an error.

## Versions

* Spyder version: 4.0.0.dev0 (lastest master)
* Python version: 3.6.5
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: windows 7
* spyder kernel : 1.1.0

**Comment by bcolsen** [comment]
The new runcell feature in spyder 4 requires you to install the latest master from spyder-kernels: https://github.com/spyder-ide/spyder-kernels

Clone the spyder-kernels repository and from that cloned directory run `python setup.py install`.

Thank you for testing out Spyder, and sorry that this requirement wasn't better documented.

**Comment by ok97465** [comment]
@bcolsen Thank you. I solved it.

**Comment by gepcel** [comment]
How did you solve it? I'm using spyder v4 from master and installed spyder-kernels from master, and still get "name 'runcell' is not defined"

**Comment by ok97465** [comment]
> How did you solve it? I'm using spyder v4 from master and installed spyder-kernels from master, and still get "name 'runcell' is not defined"

@gepcel This problem was solved by spyder-kernels 1.2.0.
You can install it with the following command:

    conda install -c spyder-ide spyder-kernels==1.2

Good luck to you

**Comment by gepcel** [comment]
It turns out that install spyder-kernels-master by `python setup.py install`, without uninstalling the spyder-kernels 1.0 (installed through conda) first, spyder still uses the old kernel.

`conda uninstall spyder-kernels` solved it. Thanks.
