### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by shuhang123** [spyder-ide/spyder#8454]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
when source save as the sample name of file, I agree 'yes' to replace. Then, It make the window of Spyder internal error.
当我将源码另存为一个相同文件名，我同意替换之前的源码文件。然后，它弹出一个关于Spyder 内部错误的窗口。

**Comment by ccordoba12** [comment]
Please update to our latest version (3.3.2) by opening the Anaconda Prompt and running there

    conda update spyder

That version has much better reporting facilities and will let us better know what's happening in your case.
