### ISSUE TITLE
Project Explorer is sometimes not set correctly when switching projects

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#8455]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports

## Problem Description

This bug is easier to reproduce and understand with two different drive with different letters, but it is also possible to reproduce it with only one drive. In fact this problem will occur when the root path of the project we are switching to is not contained in the root path of the project we are switching from.

So lets say that you create one project at `C:/Users/User/cdisk_project/project` and another one on a usb stick at `E:/usb_projects/project`, then switching from one project to the other cause the project explorer to set its root path incorrectly.

### What steps reproduce the problem?

1. Create a project on a given Drive
2. Create another project on another Drive (with a different name)
3.  Switch from one project to the other

### What is the expected output? What do you see instead?

I have already explained this above, but here is a screenshot.

![image](https://user-images.githubusercontent.com/10170372/50162362-2b900500-02ac-11e9-8e26-747446c07974.png)

### Paste Traceback/Error Below (if applicable)

There is no traceback

## Versions

* Spyder version: Spyder 4.0.0.dev0 https://github.com/spyder-ide/spyder/commit/8be3fd8d042425005cfeeeef3e8e21d63149731d
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.9.4
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)

```

**Comment by jnsebgosselin** [comment]
This bug was hard to track down, but easy to solve. So I'm going to submit a PR to fix this soon.

**Comment by ccordoba12** [comment]
Thanks @jnsebgosselin!
