### ISSUE TITLE
Spyder won't load previously open files from any project with a clean prefs file

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#8458]
## Problem Description

As originally reported in #8415 and thought to be due to that ~~issue~~ PR (I couldn't repro it in ``master`` at the time), and experienced by the PR contributor as well. From a clean prefs file (``--safe-mode``), I get the below error when trying to open any project; the project opens but without its previous files open and a completely blank Editor. If I then close the project, the previously recorded open files are wiped. This occurs both on opening a project with, and without one open, and on both new and previous projects. Also, it even happens on closing a project if there were any Editor files open previously, since Spyder will run into the same error trying to restore the previously open files in the Editor.

### What steps reproduce the problem?

1. Open Spyder in ``--safe-mode``
2. Open an existing project with files in the workspace, or create, save and re-open a new one

### Paste Traceback/Error Below (if applicable)

```python-traceback
  File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\spyder\plugins\projects\plugin.py", line 147, in <lambda>
    lambda v: self.main.editor.setup_open_files())
  File "C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\spyder\plugins\editor\plugin.py", line 2932, in setup_open_files
    is_vertical, cfname, clines = layout.get('splitsettings')[0]
AttributeError: 'NoneType' object has no attribute 'get'
```

## Proposed Solution

It seems to be that the ``layout_settings`` option for the Editor is either ``None`` or not present, which results in ``layout`` being ``None``. I already implemented and tested an if/else around the problem section that required ``layout``  to fix this, loading the files with the default focuswhich resulted in the projects and their saved workspaces being opened, switched, saved and closed successfully. I can go ahead with a PR, but is my understanding correct? Is there a better way to handle/implement this?

## Versions

* Spyder version: master
* Python version: 3.6.7
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

**Comment by jnsebgosselin** [comment]
> As originally reported in #8415 and thought to be due to that issue (I couldn't repro it in master at the time)

Of which issue are you talking about exactly @CAM-Gerlach? 

Also does this happen when not in safe mode?

**Comment by CAM-Gerlach** [comment]
> Of which issue are you talking about exactly @CAM-Gerlach?

Sorry, I meant "PR" (the one I linked). There was another error raised on opening a project in a VCS repo root that *was* caused by it and I couldn't get this error to repro in my testing on master either (since it wasn't in safe mode, I don't believe).

> Also does this happen when not in safe mode?

Not in my most recent testing at least, and the PR author on that one found that as well.

> My confusion is that, at some point it was hinted in PR #8415 that the error was maybe related to Issue #8375

No, its not, but before I investigated I was uncertain since the symptoms were superficially similar (project sessions were not getting restored after closing/switching projects) and I hadn't noticed it before.

**Comment by jnsebgosselin** [comment]
> Also does this happen when not in safe mode?

Ok, I can reproduce this too, it happens if you start Spyder with a clean .ini and try to open a project. Being in safe-mode or not does not seem to be relevant.

I think your explanation and solution is reasonable. I would open a PR to implement it if I were you.

**Comment by ccordoba12** [comment]
> I think your explanation and solution is reasonable. I would open a PR to implement it if I were you.

I agree with @jnsebgosselin about this. And don't worry to create a test for this, the solution seems quite straightforward.

**Comment by jnsebgosselin** [comment]
...and while testing this, I wiped two of my Spyder projects, nice XD

**Comment by CAM-Gerlach** [comment]
> it happens if you start Spyder with a clean .ini and try to open a project. Being in safe-mode or not does not seem to be relevant.

Right, that's what I presumed, since as I mentioned the observed criterion was

> a clean prefs file (--safe-mode)

> ...and while testing this, I wiped two of my Spyder projects, nice XD

Don't say I didn't warn you :P And I learned that from experiance testing this on pretty much *all* of my Spyder projects, heh.

But in all seriousness, <kbd>F</kbd>

> If I then close the project, the previously recorded open files are wiped.

**Comment by CAM-Gerlach** [comment]
I'll go ahead with a PR, then. Thanks @ccordoba12 and @jnsebgosselin !

**Comment by CAM-Gerlach** [comment]
> I'm not sure I agree with you on this. I think the tests should have been able to catch that.

I definitely agree; I was actually writing one now. If practicable; I like to write both a unit test for the individual changes, and a functional test for the whole system, the latter of which can be more complex but can catch a lot more "real-world" issues than a unit test. For example, a full-up functional test for #8375 would have caught this, since it would have actually triggered the problem (but likely would have been more of a pain to write).
