### ISSUE TITLE
Using Tensorflow Backend and Kernel died, restarting

### ISSUE THREAD

**Issue by chaogeenjoy** [spyder-ide/spyder#8465]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I just write "from keras.models import MinMaxScaler" and the console says "Using TensorFlow backend. Kernel died, restarting"

### What steps reproduce the problem?

1. try to run the python file with only one piece of command
2. 
3. 

### What is the expected output? What do you see instead?
there should be no output
but the kernel died

### Paste Traceback/Error Below (if applicable)

```python-traceback

runfile('C:/Users/Charles/.spyder-py3/temp.py', wdir='C:/Users/Charles/.spyder-py3')
Using TensorFlow backend.

Kernel died, restarting


 Populating the interactive namespace from numpy and matplotlib


runfile('C:/Users/xxx/.spyder-py3/temp.py', wdir='C:/Users/xxx/.spyder-py3')
Using TensorFlow backend.

Kernel died, restarting
```

## Versions

* Spyder version: 3.2.3
* Python version: 3.6.2
* Qt version: 5.6.2
* PyQt version: 5.6.0
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.1 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by ccordoba12** [comment]
Does your code run in the Jupyter notebook?

**Comment by chaogeenjoy** [comment]
No.
I have change the python version from 3.6 to 3.5, and the problem has disappeared. I do not know the reason.

**Comment by ccordoba12** [comment]
Glad to know you were able to sort this problem out.

**Comment by Coerchan** [comment]
is that any approach can solve this problem except lower 3.6 to 3.5?

**Comment by JebasWinston10** [comment]
> No. I have change the python version from 3.6 to 3.5, and the problem has disappeared. I do not know the reason.

My code still doesn't run even after lowering the version to 3.5. Help me if you found any solution for this.
