### ISSUE TITLE
Crash with Bluescreen (Windows)

### ISSUE THREAD

**Issue by ozkangokdere** [spyder-ide/spyder#8467]
### What steps will reproduce the problem?

- Spyder is open
- Make windows lock position
- Drink some tea or coffee, choose your favourite
- Come back, open lock. Voila, system is completely restarted.

Below you can see system details:
System Information report written at: 12/20/18 13:40:32
System Name: LAPTOP-FAVEVO0E
[System Summary]

Item	Value	
OS Name	Microsoft Windows 10 Pro	
Version	10.0.17134 Build 17134	
Other OS Description 	Not Available	
OS Manufacturer	Microsoft Corporation	
System Name	LAPTOP-FAVEVO0E	
System Manufacturer	LENOVO	
System Model	81B0	
System Type	x64-based PC	
System SKU	LENOVO_MT_81B0_BU_idea_FM_V330-14IKB	
Processor	Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz, 2001 Mhz, 4 Core(s), 8 Logical Processor(s)	
BIOS Version/Date	LENOVO 6UCN35WW(V2.02), 14.11.2017	
SMBIOS Version	3.0	
Embedded Controller Version	2.35	
BIOS Mode	UEFI	
BaseBoard Manufacturer	LENOVO	
BaseBoard Model	Not Available	
BaseBoard Name	Base Board	
Platform Role	Mobile	
Secure Boot State	On	
PCR7 Configuration	Elevation Required to View	
Windows Directory	C:\WINDOWS	
System Directory	C:\WINDOWS\system32	
Boot Device	\Device\HarddiskVolume1	
Locale	Turkey	
Hardware Abstraction Layer	Version = "10.0.17134.471"	
Installed Physical Memory (RAM)	8,00 GB	
Total Physical Memory	7,83 GB	
Available Physical Memory	1,64 GB	
Total Virtual Memory	18,8 GB	
Available Virtual Memory	12,0 GB	
Page File Space	11,0 GB	
Page File	C:\pagefile.sys	
Kernel DMA Protection	Off	
Virtualization-based security	Not enabled	
Device Encryption Support	Elevation Required to View	
Hyper-V - VM Monitor Mode Extensions	Yes	
Hyper-V - Second Level Address Translation Extensions	Yes	
Hyper-V - Virtualization Enabled in Firmware	Yes	
Hyper-V - Data Execution Protection	Yes	

### Traceback
```python-traceback
TypeError: _start_server() missing 1 required positional argument: 'port'
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by bcolsen** [comment]
This is bug has been fixed in the 3.3.2 release. Please upgrade to get the fix.
