### ISSUE TITLE
Feature Request: copy figure of plot widget to clipboard

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#8468]
## Problem Description
I often paste figures into my document. Currently Plot Widget only supports save function, so I have to go through several steps to put figure into document. I would be convenient if the copy function is added.

I think that there are three ways to add the copy function to the plot widget.
- option 1
![fig_copy_context](https://user-images.githubusercontent.com/22970578/50296409-c9a6e980-04bd-11e9-8a1a-00c54ff91f58.gif)
  
- option 2
![fig_copy_thumnail](https://user-images.githubusercontent.com/22970578/50296425-d297bb00-04bd-11e9-9c65-bf6cc3b6a323.gif)
  
- option 3
![fig_copy_toolbar](https://user-images.githubusercontent.com/22970578/50296451-de837d00-04bd-11e9-96b0-d25a3a8940b0.gif)

Please add a "Copy figure to Clipboard" feature to Plot Widget.

**Comment by goanpeca** [comment]
Thoughts @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
Thanks for your suggestion. This is definitively a feature that needs to be added.

- I like option 1 and I think it should also be implemented for the thumbnails.
- Option 3 is definitively something that needs to be added.
- I like Option 2, but it makes the thumbnails look a little bit crowded with 3 icons.
- Also, I think that being able to use a keyboard shortcut (like `Ctrl+C`) to copy the figure of the selected thumbnail to the clipboard would also be quite useful.

Would you be interested in proposing a PR to implement it? If not, I'll try do it during the holidays.

**Comment by ok97465** [comment]
@jnsebgosselin My code for "copy to clipboard" is working in my platform. but I am not experienced programmer. I am a radar engineer. So my code might have a problem. Can I pull request my code?

**Comment by jnsebgosselin** [comment]
> Can I pull request my code?

@ok97465 Yeah sure, we will review it. and help you if needed.

@goanpeca or @ccordoba12 What do you think, do you have anything to say about this feature request before a PR is opened for this?

**Comment by ccordoba12** [comment]
@jnsebgosselin, I also think this would be really nice to have and we're welcome to receive a PR for it.
