### ISSUE TITLE
pyqt5 Dependency seems outdated

### ISSUE THREAD

**Issue by max3-2** [spyder-ide/spyder#8475]
## Problem Description
When installing, spyder downgrades pyqt5

### What steps reproduce the problem?

1. Have a new version of pyqt (eg. 5.11.x)
2. Install spyder
3. pyqt5 gets downgraded to pyqt5 < 5.10

### Issue
I dont see any need for that version downgrade. I always upgrade right after spyder install to the newest PyPi version wihtout any problems. Is there a reason to stay below 5.10? Is it possible to remove that from setup.py?

**Comment by mvillion** [comment]
Maybe it would be a good option to leave it the user to choose between PyQt5 5.9 or 5.11 or PySide2 (5.11.0, 5.11.1, 5.11.2, 5.12.0, ...).

**Comment by stonebig** [comment]
Spyder doesn't work with pyside2. Spyder team is waiting pyside2 to be less buggy

**Comment by ccordoba12** [comment]
> Spyder team is waiting pyside2 to be less buggy

This was true before, but now I have to say that a) we don't have time to support PySide2 and b) we gain nothing by doing so (sorry).

@stonebig and @mvillion, if you're willing to invest the (most probably) dozens of hours required to make our test suite pass on PySide2 and then you commit to keep maintaining it in the future, then we'll be glad to merge any PR sent our way.

Else, we have much more important thing to focus on.

**Comment by mvillion** [comment]
I am sorry I fired an off topic discussion regarding PySide2.  (I suppose PyQt is an import base for Spyder. Having a second option like PySide2 will make it future proof.)

The initial question raises a concern regarding Spyder being stuck to PyQt 5.9. Using Spyder forces the user to remain on 5.9 for PyQt5, PyQtChart and PyDataVisualization.

**Comment by ccordoba12** [comment]
> Is it to be expected that PyQt introduces changes that break Spyder?

There were several strange errors and segfaults with 5.10

> Is it possible to have that >=0.19?

No, it's not because completion fail on Windows.
