### ISSUE TITLE
Spyder的HELP界面主题没法变成黑色

### ISSUE THREAD

**Issue by linlin98126** [spyder-ide/spyder#8483]
### What steps will reproduce the problem?

Spyder设置为黑色主题后，位于窗口左边的编辑器以及右下角Ipython主题都是黑色的，然而右上角的help,Variable explorer,File explorer均是白色背景主题，十分刺眼，希望改进。

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Sorry, we don't speak Chinese, so please repost your problem in English in a comment below.

**Comment by ccordoba12** [comment]
A completely dark theme was already added and it'll be part of our next major version (Spyder 4) to be released in 2019. See pull request #8020 for some screenshots.

**Comment by linlin98126** [comment]
Thank you so much! Looking forward to the 4.0 version.
