### ISSUE TITLE
Breakpoints are ignored sometimes

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#849]
_From [billhugh...@gmail.com](https://code.google.com/u/109102297815155152624/) on 2011-11-22T10:07:06Z_

What steps will reproduce the problem?

 1. create a simple script with 5 lines of print statements
2. use the editor to set a breakpoint on any on of the lines
3. start the debugger and type 'cont' What is the expected output? What do you see instead? Expecting to see the script break at the line with the breakpoint set however it continues on and finishes the script ignoring the breakpoint. What version of the product are you using? On what operating system? 2.1.1 Windows 7 32Bit 

Please provide any additional information below

. If I say break(3) at the pdb promt and then type 'cont', the script will break at line 3 so it looks like the editor is not setting the breakpoint?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=849_

**Comment by spyder-issues-migrator** [comment]
_From [billhugh...@gmail.com](https://code.google.com/u/109102297815155152624/) on 2011-11-22T08:17:45Z_

After playing with this a bit more, I find that if I set run>configure>"execute in current Python interpreter", breakpoints work.  The default is "execute in new dedicated interpreter".  Is this by design?

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-11-22T09:50:39Z_

I'm running 2.1.2.  I'm not able to get breakpoints to work in either of these cases.  I've been putting pdb.set_trace() statements into my scripts to get the debugger to stop.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-11-22T10:07:50Z_

To check if breakpoints are really taken into account, simply type `b` in Pdb to list all breakpoints.

Note that if a breakpoint is set in a function, typing `c` (continue) in Pdb will skip it because the debugger won't step into the function. You would have to type `n` several times then `s` to step into the function... that's a little bit annoying but, AFAIK, this is a limitation of Pdb. But I'm not a regular user of Pdb at all.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2011-11-28T07:10:09Z_

**Labels:** Cat-Debugger

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-12-01T08:58:14Z_

Hmm... one of my previous breakpoints finally has showed up, but it seems new ones aren't showing up.  It's hard to recommend spyder to my colleagues without good debugging support.  This used to work much better.  I'm not sure when it broke.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-04T06:12:46Z_

I can't reproduce this bug.

When I'm debugging a simple script like code sample (1) in this post for example: http://groups.google.com/group/spyderlib/browse_thread/thread/3a7ef892695e417a I'm setting three breakpoints in the editor:

\# start
"""Project Euler problem 23 - slow version"""
from eulertools import factors

ab = [] # \<---- HERE
for n in range(12, 28124):
   if sum(factors(n)[:-1])>n:
       ab.append(n) # \<---- HERE

nums = [] # \<---- HERE
for n in range(len(ab)):
   for m in range(n, len(ab)):
       v = ab[n]+ab[m]
       if v > 28123: break
       nums.append(v)

print sum(range(28124))-sum(list(set(nums)))

Then I'm debugging the script (Ctrl+F5) without changing the default run configuration (so in a new interpreter) and when I enter "b":
\> d:\python\euler1.py(6)<module>()
-> """
(Pdb) b
Num Type         Disp Enb   Where
1   breakpoint   keep yes   at d:\python\euler1.py:15
2   breakpoint   keep yes   at d:\python\euler1.py:17
3   breakpoint   keep yes   at d:\python\euler1.py:20
(Pdb) 

...I see my breakpoints.

And it's working in all these situations:
  * I'm changing the run configuration to run the script in current interpreter
  * I'm removing/adding breakpoints and:
    * reexecuting the script by pressing Ctrl+F5
    * reexecuting the script by pressing on the "Run again this program" button (top-right corner of the console)

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-12-05T07:57:12Z_

I think in my case I was forgetting to hold ctrl when pressing F5.  Any clear/good reason to keep them separate?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-05T08:42:37Z_

It seems natural to separate running from debugging actions. 

The only way to not separate those two actions is to run the script if there is no breakpoint and to debug it if there is breakpoints. But it would force the user to remove all breakpoints before running a program. And this would be hard to guess if there are breakpoints in modules that are imported by the main module (the current implementation sends all breakpoint for all files to Pdb, so that it may take them into account in case one of them is called during the execution of the main script). So I don't see how I could handle this except in the simplest situations where the breakpoints are only added to the main script.

**Comment by spyder-issues-migrator** [comment]
_From [steve.f....@gmail.com](https://code.google.com/u/117650558843796505335/) on 2011-12-12T13:24:38Z_

Bill, the first line in the debug window should be something like "> path/to/script.py(1)<module>()".  Is the case of the path/to/script all correct?

Pierre, I'm seeing the conversion to lowercase again.  This again appears to be preventing the breakpoints from being set properly.  If I type "b" nothing is printed even thought I have breakpoints set in the editor.  I can manually set them by entering "b 33" or whatever.  Is there any chance this is somehow pdb's fault?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2011-12-21T13:44:38Z_

issue #888 has been merged into this issue.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-03-11T06:55:56Z_

**Labels:** Milestone-Release2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:45:30Z_

**Labels:** -Milestone-Release2.2 Milestone-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:56:47Z_

**Labels:** -Milestone-v2.2 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-04-07T20:21:29Z_

I have seen this behavior on and off, and it's real. I don't have a solid way to reproduce it, but I can say that after setting and removing breakpoints, multiple launches of the debugger, it will eventually show up. I'll keep looking for the recipe to produce it repeatably. 

I've been studying the code related to breakpoints in order to understand possible sources of the problem. As I see it, the problem can be partitioned into two locations: either the editor fails to store the breakpoints to spyder.ini or SpyderPdb fails to load them correctly.

Luckily, I just now experienced the problem (wish I knew why!) and can provide these additional details: I set a breakpoint, launched the debugger, and tried to list breakpoints using "break" inside the debugger. The breakpoint was missing. I quickly checked the breakpoint dictionary in spyder.ini, and the desired breakpoint was *not* listed there. It is definitely still marked in the editor, but it is not in spyder.ini. The list of breakpoints showing in the pdb session matches the breakpoint dictionary in spyder.ini, implying that the problem is probably on the editor side rather on the SpdyerPdb side.

**Status:** Accepted

**Comment by spyder-issues-migrator** [comment]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2012-09-08T19:10:36Z_

I'm seeing the same problem, Spyder 2.1.11 on Python(x,y), Win32.

I'm not 100% sure it's reproducible, but the problem seems to occur more often when a NEW breakpoint is set after stopping at a prior breakpoint.

For example, if I set a breakpoint then debug, I'll hit the breakpoint. Then while stopped, I set another breakpoint elsewhere then type 'c' to pdb to continue.  The new (2nd) breakpoint is ignored.

**Comment by spyder-issues-migrator** [comment]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2012-09-14T12:07:34Z_

For what it's worth, this problem occurs ONLY if you attempt to set breakpoints via the GUI (clicking to the left of the line numbers in the editor window).

Breakpoints set with the 'b' command in pdb work fine.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2012-09-18T07:50:09Z_

@-dave.lindbergh: The behavior you mentioned in comment 15 is actually a known limitation of the current implementation. You can read a bit more about how Spyder handles breakpoints here: https://code.google.com/p/spyderlib/wiki/BreakpointDesign In short, the list of current breakpoints is passed to the pdb session when it is launched, but after that there is no interaction between Spyder and pdb on the list of breakpoints. The only way to add a breakpoint once pdb has launched is by the method you used in comment 16.

While I'm here, I'll comment a bit more about the behavior I reported in comment 14. I have not been able to reproduce the condition I experienced there. In retrospect, if I were hard pressed to draw any correlation I would have to say that all the times where I experienced ignored breakpoint behavior I was actually debugging Spyder *with* Spyder itself. In that situation, both Spyder sessions would be sharing the same spyder.ini file where the breakpoint dictionary is stored. It's pretty easy to see where the breakpoint state could become ambiguous in that case.

**Comment by spyder-issues-migrator** [comment]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2012-09-19T17:18:09Z_

@-jed.ludlow: Thanks; I now understand that this is a limitation-by-design for now.

However Spyder gives the _appearance_ that the GUI debugger works like most others, but doesn't work that way. This is very confusing to new users.

I have no problem at all with using the command-driven pdb to debug. But if Spyder is shows GUI breakpoints next to the line numbers, those GUI breakpoints should be an accurate representation of where the breakpoints are in the debugger.

They're not now.  As a result, Spyder misleads the new user into thinking he can set/clear breakpoints in the GUI while stepping thru the code. 

I think that until a proper (fully-implemented) GUI debugger is available, it would be better to remove the GUI debugging stuff completely.  It's not very useful as-is, pdb works fine in the interim, and it misleads new users into thinking something is broken.

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-01-28T17:31:21Z_

I'm going to eventually address this, but I probably won't get to it for a bit. Let's not hold up the 2.2 release.

**Labels:** -MS-v2.2 MS-v2.3

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2013-04-06T09:29:01Z_

**Summary:** Breakpoints are ignored sometimes  \<span class="oldvalue"> (was: breakpoints are ignored) \</span>  
  **Labels:** -MS-v2.3 MS-v2.2

**Comment by spyder-issues-migrator** [comment]
_From [jed.lud...@gmail.com](https://code.google.com/u/114333776555678317161/) on 2013-04-06T11:14:19Z_

Fixed by this series of changes: revision 60d63ffc8b5d revision 3942ebdecbfe revision c4597613ba21

**Status:** Fixed

**Comment by spyder-issues-migrator** [comment]
_From [j...@dedricks.net](https://code.google.com/u/116902552555432303445/) on 2014-10-17T09:36:18Z_

I am new to Python, and new to Spyder, .  But for me at least, this problem has not been resolved.  Breakpoints set via double-click in the editor create the visual indicator next to the line number, but do nothing.  Because the issue is not intermittent and I'm a noob, it's possible this is a misconfiguration issue (the available information on setup of Python generally and Spyder specifically is pretty sparse.)  But maybe one reason this has been tough to diagnose is that devs tend not to have misconfigured systems ;^)

Python 3.4.1 |Anaconda 2.1.0 (64-bit)| (default, Sep 24 2014, 18:32:42) [MSC v.1600 64 bit (AMD64)]   IPython 2.2.0 -- An enhanced Interactive Python.

**Comment by spyder-issues-migrator** [comment]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2014-10-17T13:24:07Z_

Re `#22`: Are you sure you're clicking on "Debug" instead of clicking on "Run" to start the program?  If you click "Run" it'll go faster, but won't stop on breakpoints.

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2014-10-17T16:45:48Z_

@-joel: Could you attach an example file where breakpoints are not working?

**Comment by spyder-issues-migrator** [comment]
_From [j...@dedricks.net](https://code.google.com/u/116902552555432303445/) on 2014-10-19T17:11:19Z_

Dave:  This was indeed the problem - just pressed the obvious (run) button, not knowing that there's a distinction between "run" and "debug".

At first I felt a bit silly, but at second glance it's worth noting here that the Spyder documentation doesn't mention this anywhere - in fact it doesn't really explain the GUI at all.  The section on "Debugging" is 1/2 page and just refers the reader to an article that discusses debugging from the command line without an IDE.

After spending quite awhile looking in vain for documentation on Spyder, I gave up and switched to PyCharm.  At first I was surprised that breakpoints didn't work there either (turns out it also requires you to push a different button to run with breakpoints enabled.)  But the documentation explains that clearly, so it only took a minute or two to get it sorted out.

Thanks for your response.
-J

**Comment by spyder-issues-migrator** [comment]
_From [dave.lin...@gmail.com](https://code.google.com/u/107110792395568123171/) on 2014-10-20T10:10:37Z_

@-j: Yes, documentation is the weakest point of Spyder; I've been using it for a long time now and there are lots of UI elements that I don't understand, still.

**Comment by igor144** [comment]
Hello!
I have the same problem with breakpoints. The debugger just ignores all of them.
I start a program by pressing Ctrl+F5. I can see all breakpoint in the console typing 'b'. The commands 'next' and 'step' work well, but when I type 'continue' the debugger run my program till the end without any stop,
My system settings are:
Spyder 3.3.2
Python 2.7

**Comment by ccordoba12** [comment]
This shouldn't be a problem in Spyder 4. Therefore, please update to our latest version.

**Comment by igor144** [comment]
I've just installed Spider 4.1.0, but it spontaneously closes after 10-20 seconds after running.

**Comment by bspiveyxom** [comment]
I just installed Spyder 3.3.6, and I am having this issue. Breakpoints show up when listed from the menu, but they are not stopping execution no matter the Debug run option selected: step, continue, etc.

**Comment by bspiveyxom** [comment]
This is the latest version I can install, but if there is a good version prior to this, I can rollback.

**Comment by FarhangAmaji** [comment]
from to 2015 till now this problem exists???!!
its not a version thing, I have had spyder from 4.2 I think and all versions had this problem. this is the most annoying thing about spyder, after that its no git section and after that bad completion which has got a little better in latest version bothers.

**Comment by ccordoba12** [comment]
If the graphical breakpoints you set in Spyder are not hit, the simply use the `breakpoint()` function in the line you want to enter the debugger. That's what most people do.
