### ISSUE TITLE
help window is not working

### ISSUE THREAD

**Issue by Dhananjay9260** [spyder-ide/spyder#8492]
### What steps will reproduce the problem?

After clicking clt+i "document is not available is showing in rich text

### Traceback
```python-traceback
    method()
----------------------------------------
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-42-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> document is not available

Well, the message is clear enough: Spyder was unable to get any documentation from the method you're inspecting.

**Comment by gepcel** [comment]
I have the same problem, Ctrl+I doesn't work in editor, but works in console for the same method.
