### ISSUE TITLE
any sqlite3 support?

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder#8501]
now spyder have notebook extention...
why spyder have no extention for sqlite3?

**Comment by ccordoba12** [comment]
What do you mean by this? Would you like to have support for sqlite in the Variable Explorer?

**Comment by adaaaaaa** [comment]
yes,show the database's table   @ccordoba12

**Comment by ccordoba12** [comment]
Sorry, this is not in our plans right now.
