### ISSUE TITLE
Display Problem of Variable Explorer

### ISSUE THREAD

**Issue by CSMANIG** [spyder-ide/spyder#8504]
### What steps will reproduce the problem?

Am not able to view the dataset information in variable explorer.
Kindly give me the solution asap.

1. Load the datset using python 
2. view the dataset
3. click variable explorer
4. not showing anything

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.5.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> Load the datset using python

This is not specific at all. What's your dataset? A csv file, a compressed numpy array?

**Comment by ccordoba12** [comment]
Closing because of lack of response.
