### ISSUE TITLE
Adding external font to the Spyder IDE | Andale Mono | Adding Zip to the Fonts

### ISSUE THREAD

**Issue by preethamsridhar** [spyder-ide/spyder#8505]
Hello,

I would like to add "Andale Mono" font to the Spyder IDE. Anybody who could tell me how to add the font or if somebody can tell how the Spyder IDE is internally accessing only a few fonts as "Plain text font" would be great. Thank you.

**Comment by ccordoba12** [comment]
Spyder doesn't handle fonts by itself, so you need to install that font in your system and the you'll be able to select it through the "Plain text font" dialog.

> Anybody who could tell me how to add the font

Just google for it: How to install a font on Windows/macOS/Linux?

**Comment by mehedi02** [comment]
@ccordoba12  external font don't appear in "Plain text font" menu, I installed Monaco font in the system and using it in other code editor but can't use it in spyder

**Comment by salmanea** [comment]
I am using Spyder 5, but my fonts still do not appear in the "Plain text font" dialog

**Comment by KennyISHIMURA** [comment]
I am too. My fonts still do not appear in the "Plain text font" dialog!

**Comment by v1ctorf** [comment]
It worked after I restart it (`Alt+Shift+R`) 

![image](https://user-images.githubusercontent.com/3472721/153954600-72209676-31b7-4023-a83a-937329a94283.png)

**Comment by AhmedMagdiii** [comment]
how i solve Arabic language in plots it viewed as separated
