### ISSUE TITLE
AttributeError: 'WebView' object has no attribute 'setBackgroundColor'

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#8506]
## Problem Description
I was trying to test PR #8494 in a linux machine (WLS) since test are passing in my windows 10 machine. So I made a new clone of Spyder from github in the linux machine. Now I cannot run Spyder in bootstrap mode.
I also made a new recent clone in my windows machine. The same problem appears as well.

1 . Windows machine
![image](https://user-images.githubusercontent.com/22060413/50571281-0caa6c00-0d9e-11e9-8810-c3dc35e2e78b.png)

2. linux machine (WLS)
![image](https://user-images.githubusercontent.com/22060413/50571253-5181d300-0d9d-11e9-99b7-a5efd66c373d.png)

https://github.com/spyder-ide/spyder/blob/c0b8950904907a463f00eb8eec96117f56615218/spyder/plugins/help/widgets.py#L103

This was updated 5 days ago. I believe the problem is related to this new update. The old forked clone I have runs just fine.

**Comment by ccordoba12** [comment]
@dalthviz, did you test PR #8497 in a Qt version that has Webkit instead of Webengine?

**Comment by dalthviz** [comment]
@ccordoba12 nop, I missed that, sorry. I'm working in the fix
