### ISSUE TITLE
menu open on the main screen when a second screen is used

### ISSUE THREAD

**Issue by Shegrad** [spyder-ide/spyder#8507]
### What steps will reproduce the problem?

when I use 2 screens, and when the spyder window is on the second screen, the menu open on the main screen not on the screen where the spyder window is

## Versions

* Spyder version: 3.3.2 
* Python version: 2.7.15
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.5.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
Please update Qt/PyQt by opening an Anaconda prompt and running there

    conda update qt pyqt

Then try again and report back.

**Comment by ccordoba12** [comment]
Closing because of lack of response.
