### ISSUE TITLE
Not working shortcut for copy figure in Plots Widget if there are multiple consoles.

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#8511]
## Problem Description
Shortcuts of Plots Widget do not work if there are multiple consoles.

![short_cut_error](https://user-images.githubusercontent.com/22970578/50597484-e8a87100-0eea-11e9-9caf-6dd1b94d4ac7.gif)

I modified the code as shown below and it works normally.
(253 line of plugins/plots/widgets/figurebrower.py)

        def create_shortcuts(self):
        """Create shortcuts for this widget."""
            # Configurable
            copyfig = config_shortcut(self.copy_figure, context='plots',
                                      name='copy', parent=self)

![short_cut_fix](https://user-images.githubusercontent.com/22970578/50597630-62d8f580-0eeb-11e9-96ee-f4d43caee7ad.gif)

Is this the right way to modify it?

## Versions

* Spyder version: 4.0.0.dev0 (lastest commit)
* Python version: 3.6.7
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: Linux 4.20.0-1-MANJARO

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> Is this the right way to modify it?

If it's working for you, then sure. Please submit a pull request to fix this, thanks!
