### ISSUE TITLE
cannot connecting to kernel

### ISSUE THREAD

**Issue by hibetterheyj** [spyder-ide/spyder#8526]
## Description

**What is the expected output? What do you see instead?**

connecting to kernel

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

I just do 

```shell
spyder --reset
```

**Comment by hibetterheyj** [comment]
I build another environment in anaconda

- Python 3.7.1 

Spyder works well

- Python 3.6.2

called `tensorflow` with scipy and matplotlib installed

worked not well by using `spyder --reset`

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.2). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by ccordoba12** [comment]
That's because you installed Spyder incorrectly. Did you use pip to do it?

**Comment by hibetterheyj** [comment]
Sorry, I just use `conda install Spyder` not `pip`
Shall I just remove and reinstall with `pip`
