### ISSUE TITLE
Python Kernel works upon startup, then fails after a minute or so of being up

### ISSUE THREAD

**Issue by krislag** [spyder-ide/spyder#8534]
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ x] Tried basic troubleshooting (if a bug/error)
    * [ x] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [ x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The Python kernel will simply not work after a minute of startup. It will run programs for a short period of time, and then it will lag out and say that I cannot connect to the kernel. The kernel also displays an error of b''

### What steps reproduce the problem?

1.  Restart anaconda
2.  Open spyder, wait a minute and try to run program
3. 

### What is the expected output? What do you see instead?

I expect to have my program run, but instead it fails. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE
WARNING:traitlets:kernel died: 18.00031614303589
WARNING:traitlets:kernel died: 18.000559091567993
WARNING:traitlets:kernel died: 18.00022053718567
WARNING:traitlets:kernel died: 18.00002908706665
WARNING:traitlets:kernel died: 18.000185251235962
WARNING:traitlets:kernel died: 18.000141859054565
WARNING:traitlets:kernel died: 18.000078201293945
```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
This looks like a firewall/antivirus issue. Please deactivate them and try again.

**Comment by krislag** [comment]
it worked! thank you so much!

**Comment by ccordoba12** [comment]
Ok, glad to know that fixed your problem.
