### ISSUE TITLE
bug in debug version of spyder with python 3.7

### ISSUE THREAD

**Issue by isalirezag** [spyder-ide/spyder#8539]
There is a bug in spyder debug mode 
when i run the code in the debug mode i can not go back using the keyboards in the console
im using spyder 3.3.2 and python 3.7, apparently it is fine with python 3.6.6 and im on ubuntu 16.4

Python 3.7.1 64-bit | Qt 5.6.2 | PyQt5 5.6 | Linux 4.15.0-43-generic

**Comment by ccordoba12** [comment]
> i can go back using the keyboards in the console

*can* or *can't*, you mean here?

**Comment by isalirezag** [comment]
cannot*

**Comment by ccordoba12** [comment]
Sorry to hear that but we're in the process of rewriting our debugger support for Spyder 4, so we don't plan to address more minor bugs (like this one) in Spyder 3.
