### ISSUE TITLE
Hitting backspace multiple times causes findBlockByNumber error

### ISSUE THREAD

**Issue by MarkMoretto** [spyder-ide/spyder#8544]
### What steps will reproduce the problem?

I was hitting backspace to remove spacing from a class staticmethod and eventually this findBlockByNumber error appeared.

I am not using an Anaconda-installed version of Spyder.

### Traceback
```python-traceback
  File "C:\Users\MMorett1\AppData\Local\Programs\Python\spyder\spyder\plugins\editor\panels\codefolding.py", line 418, in mouseMoveEvent
    self._highlight_block(block)
  File "C:\Users\MMorett1\AppData\Local\Programs\Python\spyder\spyder\plugins\editor\panels\codefolding.py", line 386, in _highlight_block
    self._current_scope.get_range() != scope.get_range()):
  File "C:\Users\MMorett1\AppData\Local\Programs\Python\spyder\spyder\plugins\editor\utils\folding.py", line 96, in get_range
    block = block.document().findBlockByNumber(last_line)
AttributeError: 'NoneType' object has no attribute 'findBlockByNumber'
```

## Versions

* Spyder version: 4.0.0.dev0 f88215500
* Python version: 3.6.5
* Qt version: 5.11.2
* PyQt5 version: 5.11.3
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pep8 >=0.6        :  1.7.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
pyls >=0.19.0     :  0.21.4 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Were you in the first or last line of your file while doing this?

**Comment by MarkMoretto** [comment]
I don't believe it was the last line of a file; I think I was within class function when the error came up.  It triggered when the cursor reached the leftmost part of the editor and jumped up one line where there was additional text.

It's been a few days, so I'm not 100% certain whether Spyder offered to correct any indentation formatting issues when I opened the script.

**Comment by ccordoba12** [comment]
Closing because this hasn't resurfaced again.
