### ISSUE TITLE
When plotting backend is set to OS X, console crashes

### ISSUE THREAD

**Issue by Stargrazer82301** [spyder-ide/spyder#8551]
## Problem Description

Whenever I try to import matplotlib.pyplot with the graphics backend set to OS X, I get an error that reads:

`ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.`

### What steps reproduce the problem?

1. Setting the graphics backend to OS X (on a macos machine)
2. Entering import matplotlib.pyplot

### What is the expected output? What do you see instead?

The expected output is the ability to import matplotlib.pyplot. Instead I see the error above. I installed Spyder via Anaconda, as per the instructions given on the Spyder website

If I try to use Anaconda to install python.app, as per the error message, Anaconda just tells me "All requested packages already installed.".

And as I'm using Spyder, I have no way to switch to this "pythonw".

If I switch the backed to Qt4 or Qt5 or tkinter, then I commands that are supposed to interact with the plotting windows, like plt.close('all') no longer work, and I end up with hundreds of windows everywhere.

If I switch the backend to inline, it works, but obviously I lose the ability to have a GUI or interact with multi-figure plots.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Mac OS High Sierra

### Dependencies

IPython >=4.0 : 7.2.0 (OK)
cython >=0.21 : 0.29.2 (OK)
jedi >=0.9.0 : 0.13.2 (OK)
matplotlib >=2.0.0: 3.0.2 (OK)
nbconvert >=4.0 : 5.4.0 (OK)
numpy >=1.7 : 1.15.4 (OK)
pandas >=0.13.1 : 0.23.4 (OK)
psutil >=0.3 : 5.4.8 (OK)
pycodestyle >=2.3 : 2.4.0 (OK)
pyflakes >=0.6.0 : 2.0.0 (OK)
pygments >=2.0 : 2.3.1 (OK)
pylint >=0.25 : 2.2.2 (OK)
qtconsole >=4.2.0 : 4.4.3 (OK)
rope >=0.9.4 : 0.11.0 (OK)
sphinx >=0.6.6 : 1.8.2 (OK)
sympy >=0.7.3 : 1.3 (OK)

**Comment by ccordoba12** [comment]
> ImportError: Python is not installed as a framework.

This has nothing to do with Spyder. Besides, I think the osx backend was deprecated some time ago.

In any case, there's nothing we can do about it, sorry.

**Comment by ccordoba12** [comment]
> And as I'm using Spyder, I have no way to switch to this "pythonw".

Well, one option is to select `pythonw` in our menu

    Tools > Preferences > Python interpreter > Use the following interpreter

**Comment by Stargrazer82301** [comment]
Ah, thanks; but if I try that, I can no longer type left-brackets in the console. When I do, nothing happens until I restart the console, at which all the left-brackets I tried to type appear at once!

**Comment by ccordoba12** [comment]
Sorry to hear that! In any case, was not the osx backend deprecated some time ago?
