### ISSUE TITLE
accidently activating profiler

### ISSUE THREAD

**Issue by rubenmu** [spyder-ide/spyder#8554]
### What steps will reproduce the problem?

had some code like this marked in the editor *len([1,2,3,4])*
then accidently pressed F10 instead of F9, which activated the profiler

### Traceback
```python-traceback
  File "C:\Users\Ruben.Mueller\AppData\Local\Continuum\Anaconda3\envs\pyqt5\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 264, in <lambda>
    self.finished(ec, es))
  File "C:\Users\Ruben.Mueller\AppData\Local\Continuum\Anaconda3\envs\pyqt5\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 335, in finished
    self.show_data(justanalyzed=True)
  File "C:\Users\Ruben.Mueller\AppData\Local\Continuum\Anaconda3\envs\pyqt5\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 362, in show_data
    self.datatree.show_tree()
  File "C:\Users\Ruben.Mueller\AppData\Local\Continuum\Anaconda3\envs\pyqt5\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 526, in show_tree
    rootkey = self.find_root()  # This root contains profiler overhead
  File "C:\Users\Ruben.Mueller\AppData\Local\Continuum\Anaconda3\envs\pyqt5\lib\site-packages\spyder_profiler\widgets\profilergui.py", line 507, in find_root
    self.profdata.sort_stats("cumulative")
AttributeError: 'NoneType' object has no attribute 'sort_stats'
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 403, 'json': {'message': 'At least one email address must be verified to do that.', 'documentation_url': 'https://help.github.com/articles/adding-an-email-address-to-your-github-account'}}
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 403, 'json': {'message': 'At least one email address must be verified to do that.', 'documentation_url': 'https://help.github.com/articles/adding-an-email-address-to-your-github-account'}}
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.11.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.14.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by rubenmu** [comment]
actually it was not this list directly, it was a list in a class.
The code was wrong, and pointed to a method which should return the list, causing the
TypeError: object of type 'method' has no len()

**Comment by ccordoba12** [comment]
Could you post the code you used so we can reproduce this error in our side? Thanks!

**Comment by rubenmu** [comment]
Hi,
I ran the code exactly as he was again.
I could back then but can no longer reproduce the error now. 

Maybe it was another action before which led to the behavior?
I don't know. Maybe you just close this case.



-----Ursprüngliche Nachricht-----
Von: Carlos Cordoba [mailto:notifications@github.com] 
Gesendet: Freitag, 11. Januar 2019 16:41
An: spyder-ide/spyder <spyder@noreply.github.com>
Cc: Ruben Müller <Ruben.Mueller@bah-berlin.de>; Author <author@noreply.github.com>
Betreff: Re: [spyder-ide/spyder] accidently activating profiler (#8554)

Could you post the code you used so we can reproduce this error in our side? Thanks!

**Comment by ccordoba12** [comment]
Ok, I'll close for now. Please report back here if you find a way to reproduce this error.
