### ISSUE TITLE
cmd+i works but text cannot be entered spyder python

### ISSUE THREAD

**Issue by wyattbair** [spyder-ide/spyder#8563]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
when using the help pane, cmd+I will work on any function in the editor, however, when I try to input text into the search bar manually it will not allow me to interact.

this occurs only when the search bar is set to editor.

### What steps reproduce the problem?

1. go to help pane and use cmd+i to see help for a function
2. try to type in a different function
3. it won't let you interact with the search bar.

### What is the expected output? What do you see instead?
it seems as though I should be able to type a function name into the help window rather than typing it in the file just to figure out what the necessary parameters are, but when i try the search bar will not allow me to click or type on/in it.

## Versions

* Spyder version: 3.3.2
* Python version: 3.7
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: macOS Mojave

### Dependencies

IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.8 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

**Comment by ccordoba12** [comment]
You need to change the `Source` option in the Help pane from `Editor` to `Console` to be able to type text in its search bar.

This is a known limitation and we'll try to address it in the future.
