### ISSUE TITLE
Code analysis and completion often break when the "Automatic code completion" option is checked

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#8565]
## Problem Description

When the option `Automatic code completion` is checked, code completion and analysis often break.

### What steps reproduce the problem?

1. Make sure the preferences `Editor > Code Introspection/Analysis > Automatic code completion` is checked
2. Type in the editor :
```python
import numpy as np
np.z
```
3. Wait for the completion results to be displayed.

Note that in step2, it is important to type the `z` before the completion results are displayed in the Editor.

### What is the expected output? What do you see instead?

For some reason, the completion results do not seem to take into account the `z`. After that, code introspection and analysis is broken and I need to restart Spyder to make it work again.

![image](https://user-images.githubusercontent.com/10170372/51087675-4d05d480-1724-11e9-9b80-532b06ed48ff.png)

## Versions

* Spyder version: Spyder 4.0.0.dev0 https://github.com/spyder-ide/spyder/commit/a5ca1f20f69ba8f9bc1b85e166ce865302c06a54
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.9.4
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)

```

**Comment by jnsebgosselin** [comment]
Here is an animation showing the reproducible case discussed above :

![crash_introspection2](https://user-images.githubusercontent.com/10170372/51087725-e634eb00-1724-11e9-95e3-382fa640ad71.gif)

**Comment by ccordoba12** [comment]
Thanks @jnsebgosselin for the report. We definitely have to fix this for beta2.

**Comment by bcolsen** [comment]
I have had it break as well on Ubuntu.
