### ISSUE TITLE
Deleting a folder which contains a sub-folder(s) raises an error

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#8567]
When deleting a folder which contains subfolders(s), an error is raised saying that cannot delete the folder. But eventually folder's contents are deleted.

![delete_folder_issue](https://user-images.githubusercontent.com/22060413/51087008-99add780-1745-11e9-982b-623c3e958050.gif)

Spyder: Master (currently under development) 
OS: windows: 10
Python version: 3.6

**Comment by ccordoba12** [comment]
@Khalilsqu, would you like to work on this one?

**Comment by Khalilsqu** [comment]
@ccordoba12 Gladly, Thanks a lot, However, I do it next weekends, I have paper submission deadline on 15th, it done but just few minor modification on some figures, I also have a presentation in a meeting on 17th. I will take care of it next weekend. Promise. 💯

**Comment by ccordoba12** [comment]
No problem. Thanks for your help!
