### ISSUE TITLE
Renaming a folder which contains subfolders raises Access denied

### ISSUE THREAD

**Issue by Khalilsqu** [spyder-ide/spyder#8568]
When trying to rename a folder which contains subfolder(s), Access denied error is raised.

![rename_folder_issue](https://user-images.githubusercontent.com/22060413/51087154-24db9d00-1747-11e9-9ecb-1224c8cfe368.gif)

Spyder: Master (currently under development) 
OS: windows: 10
Python version: 3.6

**Comment by ccordoba12** [comment]
I think this happens only on Windows and it occurs when you have a file in your subfolder open either in Spyder or another text editor.

@Khalilsqu, could you confirm it? Thanks!

**Comment by Khalilsqu** [comment]
@ccordoba12 , I will investigate further within the weekend and inform you. Thanks..

**Comment by Khalilsqu** [comment]
It is a similar issue to #8567. No file or are open. It only happens in windows OS.

**Comment by ccordoba12** [comment]
> It only happens in windows OS.

I thought so. I think this is not possible to fix due to the way Windows work: you can't rename a file/folder that it's already opened on it.

So I think we should close this one. Do you agree @Khalilsqu?

**Comment by ccordoba12** [comment]
Ok, thanks for taking a look at it.
