### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by DanteSung** [spyder-ide/spyder#8572]
I used tf.layer.dense to train a NN and type some extra lines in the command window which is 
In [4]: dif = np.square(X_lable-X)
In [5]: absX = np.square(X_lable)
   ...: absX = absX.mean()
   ...: rate = dif/absX
   ...:
   ...:
In [6]:
   
Then the bug happens.

**Comment by ccordoba12** [comment]
This is fixed in the latest version of qtconsole. Please update by opening the Anaconda Prompt and running there

    conda update qtconsole
