### ISSUE TITLE
Feature Suggestion: Cut current line

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#8574]
This is a function I have been missing since a long time (since I first used it in other IDEs e.g VBStudio back in 2005).
Often I want to duplicate the current line elsewhere. Right now I have to select the line with my mouse and press CTRL+X to cut it.

Do you think it would be possible to add a keyboard-shortcut for cutting the current line in the editor/console?

Once again props for this very good yet simple IDE, I've been using very extensively!

**Comment by ccordoba12** [comment]
There's a shortcut to remove the current line, but it doesn't add its contents to the clipboard. What about if we do just that? Would that be enough for you @skjerns?

**Comment by skjerns** [comment]
if it would copy the just-cut line to the clipboard, that would be exactly what I need! thank you for the quick response :)

**Comment by ccordoba12** [comment]
Ok, we'll implement this for Spyder 4.

**Comment by skjerns** [comment]
super cool!

**Comment by bcolsen** [comment]
>I'm not sure that having my clipboard content overridden every time I remove the current line with Ctrl+d is something I like... this will an important impact on my workflow.

I was going to mention this as well.

**Comment by skjerns** [comment]
I was also assuming a new shortcut and not overriding the current one.

**Comment by wheyVanilla** [comment]
Is there any updates for this one?

**Comment by ccordoba12** [comment]
Sorry, we haven't implemented this due to lack of time. But we'll try to do it for Spyder 6, to be released before the end of the year.

**Comment by Yugadeep** [comment]
Okay, I'm low-key excited about this feature. I've wanted quick selecting line/ quick cutting line for the longest time.

**Comment by ccordoba12** [comment]
To everyone following this issue: it'll fixed in our 6.1.0 version, to be released in the first half of 2025.
