### ISSUE TITLE
Kernel died, restarting

### ISSUE THREAD

**Issue by Heavenlinguistics** [spyder-ide/spyder#8575]
## Problem Description
I've written a program in spyder, everything works well at the beginning. 
But then the program is aborted in the halfway and "Kernel died, restarting" is reported in the console.

The program is the following code. The code works well for one time, but when i tried to run it in a for loop as following, the problem above occured. 

I've tried to closed the firewall and antivirus software, but the problem is still there.

`from pyltp import Parser
import os

LTP_DATA_DIR='F:\LTP-project\ltp_data'
fr1=open('words.txt','r',encoding='utf-8')
lines1=fr1.readlines()
fr2=open('pos.txt','r',encoding='utf-8')
lines2=fr2.readlines()
fw=open('dependencies.txt','w',encoding='utf-8')
LTP_DATA_DIR = 'F:\LTP-project\ltp_data' 
par_model_path = os.path.join(LTP_DATA_DIR, 'parser.model') 
parser = Parser()
parser.load(par_model_path)

for i in range(len(lines1)):
        words=lines1[i].strip().split()
        postags=lines2[i].strip().split()
        arcs = parser.parse(words, postags)
parser.release() `

### What steps reproduce the problem?
1. run the program above in spyder 
### What is the expected output? What do you see instead?
I expected that the program would not stop until the condition of  the for loop has been achieved, 
Instead, the program is aborted in the halfway of the for loop. 

### Paste Traceback/Error Below (if applicable)
"""
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel died: 6.008459091186523
WARNING:traitlets:kernel died: 6.004070997238159
WARNING:traitlets:kernel restarted
WARNING:traitlets:kernel died: 6.0140540599823
WARNING:traitlets:kernel restarted
"""

## Versions
* Spyder version: 3.2.3
* Python version: 3.6.2 64bits
* Qt version: 5.6.2
* PyQt version: 5.5.6
* Operating System name/version: windows 64bits 

### Dependencies
```
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  None (NOK)
pandas >=0.13.1  :  None (NOK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  None (NOK)

```

**Comment by ccordoba12** [comment]
Sorry but this is not a bug in Spyder but in the code you're trying to run with it, which is different. Therefore, we can't help you with that, sorry.
