### ISSUE TITLE
Cannot update to Spyder 3.3 with "conda update spyder" in in Anaconda Prompt 

### ISSUE THREAD

**Issue by gphmath** [spyder-ide/spyder#8587]
## Description

plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
![image](https://user-images.githubusercontent.com/10369892/51288644-1687cc80-1a38-11e9-855d-2413579e2db8.png)

"conda update spyder" in Anaconda Prompt doesn't update Spyder to 3.3

**What steps will reproduce the problem?**

1. I installed Anaconda including the Spyder 
2. open spyder and it  show me the error message as the picture, I don't know what happened?
3. So I write "conda update spyder" in Anaconda Prompt with Administrator Right, and it shows result as the picture below, which seems that successfully updated.
4. But I open the Spyder again ,everything is the same, and version is still Spyder 3.2.3
5. By the way Anaconda is the latest version, I just change python 3.7 to python 3.6.8. Does it matters?
 
![image](https://user-images.githubusercontent.com/10369892/51289758-6799bf80-1a3c-11e9-9544-4b3bd5571d5c.png)

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.8
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
This is not a Spyder problem but a problem with conda, so please report it here:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by gphmath** [comment]
> This is not a Spyder problem but a problem with conda, so please report it here:
> 
> https://github.com/ContinuumIO/anaconda-issues/issues/

O,thanks for replying!
 I just run "conda install spyder=3.3.0" instead of "conda update spyder" in Anaconda Prompt.
And updated to Spyder 3.3 successfully, error is eliminated. This issue can be closed.

**Comment by ccordoba12** [comment]
Ok, good to know this problem is fixed for you now.
