### ISSUE TITLE
Spyder Crashed

### ISSUE THREAD

**Issue by amitgupta1991** [spyder-ide/spyder#8605]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Unable to start Spyder using Anaconda. It is giving an error that Spyder crashed during last session.

### What steps reproduce the problem?

1.  I tried re-installing the software, but still getting the same issue.
2.  Tried to go ahead with the comments mentioned in other similar issues, but not able to work it out as the Anaconda prompt is not appearing.
3. 

### What is the expected output? What do you see instead?

Instead of getting the Spyder interface for coding, I get a popup message error.

### Paste Traceback/Error Below (if applicable)

![spydercrash](https://user-images.githubusercontent.com/46863702/51442774-2ccaac80-1d06-11e9-86f8-d8c8ee2a2447.PNG)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 Single Language 

### Dependencies

NOT GETTING ANY DEPENDENCIES TAB IN HELP.
```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please run in Anaconda prompt

    spyder --reset

That should fix your problem.

**Comment by amitgupta1991** [comment]
How to go to Anaconda prompt...??

I tried typing conda in cmd but no such command exists it says...Can you guide me how to open the Ananconda promt.

Regards,
Amit Gupta

Sent from Mail for Windows 10

________________________________

**Comment by ccordoba12** [comment]
Just write in the Windows Start menu "Anaconda prompt" and you'll get it.

**Comment by breyner-posso** [comment]
Hi! I got the same error message but I'm using it in Ubuntu 16.04. How can I fix this problem? I tried to uninstall it, but I couldn't.

Thanks a lot for your help!
