### ISSUE TITLE
Spyder shutdown automatically every 1 hour more or less

### ISSUE THREAD

**Issue by zhanghang02** [spyder-ide/spyder#8610]
### Issue Report Checklist

 done*[ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
 done*[ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
done* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
Can* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
done* [ ] Tried basic troubleshooting (if a bug/error)
    done* [ ] Restarted Spyder
    done* [ ] Reset preferences with ``spyder --reset``
    done* [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    done* [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When I open the spyder IDE, it always shutodown automatically nearly every one hour, sometimes 30 min, with no prompt. Just suddenly disappeared.

It's not a normal close process, because when I reopen the spyder, nothing saved.

I tried everything to solve it but failed, reset the spyder, reinstall the anaconda 64bit, uninstall anaconda and reinstall anaconda 32bit. 

Finally I reinstall my system-Win10, and after reinstall the system and drive, I first install the anaconda and leave a totally blank .py there with spyder IDE. Still shutdown automatically after a while.

The only finding is when I opened a jupyter sever, it shutdown after a while too.

Could someone kindly give me some hints to solve it? I realllllly need Spyder... Thanks!

I pasted the likly windows troubleshooting log

- System 

  - Provider 

   [ Name]  Application Error 
 
  - EventID 1000 

   [ Qualifiers]  0 
 
   Level 2 
 
   Task 100 
 
   Keywords 0x80000000000000 
 
  - TimeCreated 

   [ SystemTime]  2019-01-20T10:36:29.752200000Z 
 
   EventRecordID 1313 
 
   Channel Application 
 
   Computer DESKTOP-ADSCT6E 
 
   Security 
 

- EventData 

   pythonw.exe 
   3.7.1150.1013 
   5c0f4334 
   KERNELBASE.dll 
   10.0.17763.134 
   1659a33b 
   40000015 
   0000000000055299 
   29c4 
   01d4b09b22afa5e3 
   C:\ProgramData\Anaconda3\pythonw.exe 
   C:\Windows\System32\KERNELBASE.dll 
   63e98b84-5a13-4671-a2e3-fb25c0e36ba4 

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 5.9.7            vc14h73c81de_0  [vc14]
* PyQt version:  5.9.2            py37h6538335_2
* Operating System name/version: Win10 latest Version

### Dependencies

IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

**Comment by ccordoba12** [comment]
> The only finding is when I opened a jupyter sever, it shutdown after a while too.

This means it's related to Spyder specifically but instead something odd is interfering with both Spyder and Jupyter.

> Could someone kindly give me some hints to solve it? I realllllly need Spyder... Thanks!

We can give you two advices:

1. Turn off/disable/uninstall your firewall/antivirus. That should help.
2. Run Spyder in Linux virtual machine.

Other than that, we can't help you further, sorry.
