### ISSUE TITLE
Wiki navigation to Google Gadget

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#862]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2011-12-02T05:23:35Z_

What steps will reproduce the problem?

 1. Every wiki page may have Edit button that is linked to Wiki source.
2. But this requires updating every page table by hand.

This probably be easier to maintain if we'll try to move navigation table into Google Gadget. It may also help determine and highlight current section automatically.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=862_

**Comment by goanpeca** [comment]
This is no longer relevant after the move to Github
