### ISSUE TITLE
Spyder Issues with the new update

### ISSUE THREAD

**Issue by Swetha1931** [spyder-ide/spyder#8623]
## Problem Description

The Spyder throws Errors as shown below when I try to run the file. 
These errors have been occurring since I installed Flask in the system. 

### What steps reproduce the problem?

1. Restarting the Spyder
2. Running any Flask files with .py
3. 

### What is the expected output? What do you see instead?

Output must have been a simple "Hello World" as  a Web App.

I get errors in Packages

### Paste Traceback/Error Below (if applicable)

runfile('C:/Users/sweth/Desktop/IOT/startpage.py', wdir='C:/Users/sweth/Desktop/IOT')
Traceback (most recent call last):

  File "<ipython-input-1-b8cb421accc0>", line 1, in <module>
    runfile('C:/Users/sweth/Desktop/IOT/startpage.py', wdir='C:/Users/sweth/Desktop/IOT')

  File "C:\Users\sweth\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\sweth\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/sweth/Desktop/IOT/startpage.py", line 17, in <module>
    app.run()

  File "C:\Users\sweth\Anaconda3\lib\site-packages\flask\app.py", line 938, in run
    cli.show_server_banner(self.env, self.debug, self.name, False)

  File "C:\Users\sweth\Anaconda3\lib\site-packages\flask\cli.py", line 629, in show_server_banner
    click.echo(message)

  File "C:\Users\sweth\Anaconda3\lib\site-packages\click\utils.py", line 259, in echo
    file.write(message)

UnsupportedOperation: not writable

## Versions

* Spyder version: 3.2.8
* Python version: 3.6.5
* Qt version: 5.9.5
* PyQt version: 5.9.2
* Operating System name/version: Windows 10. Version 1803

### Dependencies

IPython >=4.0    :  6.4.0 (OK)
cython >=0.21    :  0.28.2 (OK)
jedi >=0.9.0     :  0.12.0 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.14.3 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.8.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.7.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

**Comment by ccordoba12** [comment]
This is an error in your `startpage.py` not in Spyder itself. Therefore, we can't help you about it, sorry.

**Comment by Swetha1931** [comment]
http://www.compjour.org/lessons/flask-single-page/serving-simple-html-response/

I typed only the "Hello World" codes only. But I can't run it

**Comment by Swetha1931** [comment]
from flask import Flaskapp = Flask(__name__)
@app.route('/')def homepage():
    return """Hello world!"""
if __name__ == '__main__':
    app.run(use_reloader=True, debug=True)

When I try to run the codes, they show the same Error. But Other
Python codes without Flask are Working.
