### ISSUE TITLE
Assign a keyboard shortcut to switch to the Plots pane

### ISSUE THREAD

**Issue by gepcel** [spyder-ide/spyder#8640]
I'm using spyder 4 from master. How can I assign a shortcut to switch to the plot widget?

**Comment by ccordoba12** [comment]
There's no shortcut right now to go to the Plots pane, but it's a good idea to have one for it.

@jnsebgosselin, what do you think about using `Ctrl+Shift+G` (`G` for graphics)? `Ctrl+Shift+P` is already taken for Projects.

**Comment by ccordoba12** [comment]
@gepcel, after we assign a default shortcut, you'll be able to change it through our Preferences to the one you like.

**Comment by jnsebgosselin** [comment]
> @jnsebgosselin, what do you think about using `Ctrl+Shift+G` (`G` for graphics)? `Ctrl+Shift+P` is already taken for Projects.

Ok, I think that makes sense, `G` can also be for graphs.

**Comment by ccordoba12** [comment]
Great! Do you have time to work on this one?

**Comment by ok97465** [comment]
@jnsebgosselin @ccordoba12  What do you think of adding shortcuts for "next figure" and "previous figure" of plots pane? It was a convenient shortcut to me.

**Comment by jnsebgosselin** [comment]
> Great! Do you have time to work on this one?

Yes, I will try to do it soon.

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin @ccordoba12 What do you think of adding shortcuts for "next figure" and "previous figure" of plots pane? It was a convenient shortcut to me.

Good idea, please open a new issue about your it.
