### ISSUE TITLE
Assign a keyboard shortcut for "next figure" and "previous figure" of the Plots pane

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#8641]
I think it would be nice to add shortcuts for "next figure", "previous figure" of the Plots pane.
Thank you.

**Comment by ccordoba12** [comment]
@ok97465, do you want to work on this one? Else we'll leave it for beta3.

**Comment by ok97465** [comment]
@ccordoba12 I will try it. Thank you.
