### ISSUE TITLE
spider not working properly, please help

### ISSUE THREAD

**Issue by jhaashish0960** [spyder-ide/spyder#8660]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by jhaashish0960** [comment]
![capture](https://user-images.githubusercontent.com/28383126/51893880-17373180-235b-11e9-9c6d-d1668d4289a2.PNG)
 what should i do?

**Comment by ccordoba12** [comment]
Sorry, you didn't provide a description of your problem so we can't help you.

**Comment by jhaashish0960** [comment]
sir, i have written this code. But i cannot get the output as required.
please help

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=a2c9b1f6-178f-4dcc-8a24-1101d174a8e8>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=a2c9b1f6-178f-4dcc-8a24-1101d174a8e8>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jhaashish0960** [comment]
please, do help me sir. I do not have anyone to help me.

**Comment by ccordoba12** [comment]
I don't even know what's happening in your case, that's why I closed the issue.
