### ISSUE TITLE
My file got erased

### ISSUE THREAD

**Issue by OswaldoSantanaVentagium** [spyder-ide/spyder#8666]
### What steps will reproduce the problem?

I was working on a file named Inst_Stories_Info.py 
I ran the Play button to see some changes I made and then it asked me to save the file, which I did. After that the script page was empty and all my work was gone. Please Help me!!! I need your help since this issue might cause me to lose my job!

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
We're very sorry for that. You can extract some contents from your file, if you ran it as cells, by going to the `HIstory` pane.

This was probably caused by you removing your file outside Spyder before running it, for which we can't provide a solution, sorry.

**Comment by OswaldoSantanaVentagium** [comment]
No, I ran it as a whole script. I jsut made a small change and when I clicked on run it asked me to save it and after I did everything was empty. So easy for you to say, but that is my fault for trstuing spyder I assume. Thank you.

**Comment by ccordoba12** [comment]
We're very sorry for your problem but it's the first time I heard something like this in almost 10 years working for Spyder.
