### ISSUE TITLE
spyder stops when run pyqtgraph exapmle

### ISSUE THREAD

**Issue by takumi-ricoh** [spyder-ide/spyder#8679]
### What steps will reproduce the problem?

Run this on IPython console.

import pyqtgraph.examples
pyqtgraph.examples.run()

Here is the docment
http://www.pyqtgraph.org/documentation/introduction.html

This script works fine on "Anaconda Prompt" or "jupyter qtconsole"

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.0 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.0 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
For this work you need to run the following command in the console before running the code above

    %matplotlib inline
