### ISSUE TITLE
spyder not detecting numpy library

### ISSUE THREAD

**Issue by suffiyanshaikh** [spyder-ide/spyder#8680]
### What steps will reproduce the problem?

i have installed numypy library 1.6 but my spyder ide is not detecting the numpy library in the dependencies list it showing not installed due this my programs are not running

## Versions

* Spyder version: 3.3.2 
* Python version: 3.6.7
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-43-generic

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  None (NOK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  None (NOK)
pandas >=0.13.1   :  None (NOK)
psutil >=0.3      :  5.5.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
Please see this

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
