### ISSUE TITLE
Spyder not outputting or saving variables

### ISSUE THREAD

**Issue by wilma22** [spyder-ide/spyder#8701]
Spyder is not outputting lines of code I run, nor is it saving variables. I have updated to the latest version, and it is still the same.. If I restart the kernel It will work, but quickly it reverts back to not outputting or saving anything again.. This problem (seemed) to come out of the blue and I hadn't any problems of the sort before this began..

* Spyder version: 3.3.2
* Python version: 3.6

**Comment by ccordoba12** [comment]
What's your operating system? Windows, Linux or macOS?

**Comment by wilma22** [comment]
macOS

**Comment by ccordoba12** [comment]
I thought so. Is issue #2902 similar to your problem?

**Comment by wilma22** [comment]
It's similar in that it that the first few commands execute as normal, but it isn't that it slows down, it does not execute at all.

**Comment by ccordoba12** [comment]
Ok, please follow the instructions there to see if the proposed solutions work for you.

**Comment by wilma22** [comment]
Tried:

conda uninstall spyder
conda install git+https://github.com/spyder-ide/spyder@3.x
(failed)
conda uninstall ipykernel
conda install ipykernel==4.10.0

No difference..

I am not an experienced programmer, so maybe I'm missing something more obvious..

**Comment by ccordoba12** [comment]
Sorry to hear that but we don't have more advice to give you other than what users have found in that issue.

I'm going to close this issue for now. Please post a comment on issue #2902 describing your problem to see if you someone else can help you there.
