### ISSUE TITLE
PYTHONPATH manager removes path after restarting

### ISSUE THREAD

**Issue by JeppeHagedorn** [spyder-ide/spyder#8708]
### What steps will reproduce the problem?

I'm trying to install/get some tools through PYTHONPATH manager.
Spyder v. 3.3.2, Python v. 3.7, macOS Mojave

The tools I'm trying to access are in: …/Homemade_toolbox/Tools

1. I add path through PYTHONPATH
2. I restart Spyder (ctrl-shift-R)
3. Path is removed from PYTHONPATH
4. call from Function import Fuction_func
5. Error: ModuleNotFoundError: No module named 'Function_func'

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this in a future release.

**Comment by goanpeca** [comment]
This is probably no longer relevant
