### ISSUE TITLE
Ctrl + I | Inspect Current Object not working 

### ISSUE THREAD

**Issue by NitinSabharwal** [spyder-ide/spyder#8709]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Ctrl + I | Inspect Current Object not working 

### What steps reproduce the problem?
On clicking , "Ctrl + I" , help pane is showing blank.
While doing the coding , we normally used "Ctrl + I to Inspect Current Object  and look for respective parameters". 

Few days back, it was working fine but after installing Tensorflow, I am assuming this error started coming.

### What is the expected output? What do you see instead?
Expected is, it should open the functions on clicking. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> Few days back, it was working fine but after installing Tensorflow

I'm almost sure this is the problem. Please uninstall Tensorflow and reinstall it in an environment, following our guide for that:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
