### ISSUE TITLE
Add filters to exclude modules and functions in Variable Explorer

### ISSUE THREAD

**Issue by reisarthur** [spyder-ide/spyder#8715]
## Problem Description

In the 'Variable Explorer', the objects of classes I've created only appear if I uncheck the filter 'Exclude unsupported data types'. But, at the same time, if I uncheck it, all the imported modules and functions unnecessarily appear (at least for me).

For example, in the image below, no variables were shown before unchecking this option. But it's a great tool for my specific application to see the variable mesh (type Mesh) in the Explorer.

![image](https://user-images.githubusercontent.com/13154469/52311415-035c8280-298e-11e9-983a-2d4f11cf7f5c.png)

## Desired Solution
I'd really appreciate if it's added in the following versions of Spyder more options in the Variable Explorer Filters, like:

- Exclude modules
- Exclude functions
- Exclude builtin methods

## Versions
* Spyder version: 3.3.2
* Python version: 3.7.1
* Operating System name/version: Windows10
* Dependencies: All OK!

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to take a look at in a future release.
