### ISSUE TITLE
Feature Request: Add a option to set a indentation of QTreeWidget

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#8732]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I use a narrow window for outline explorer and project explorer. So a indentation of QTreewidget is long for me. What do you think about adding a option to set a indendation?

![indentation_example](https://user-images.githubusercontent.com/22970578/52481885-1de36580-2bf3-11e9-8a9e-56be372ed07c.png)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: spyder 4.0.0dev lastest commit
* Python version: 3.6.8
* Qt version: 5.9.4
* PyQt version: 5.9.2
* Operating System name/version: 4.20.3-1-MANJARO

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please don't add an option. Simply reduce the current indentation so things look better after your change.

**Comment by ok97465** [comment]
@ccordoba12 Ok. Thak you for your reply.
