### ISSUE TITLE
Console naming

### ISSUE THREAD

**Issue by arman00** [spyder-ide/spyder#8742]
This is just a simple question. Consoles are named like Console 1/A, Console 2/A, ... I haven't came across so far something like Console 1/B Console 1/C. What is the purpose of the letter in the name, do the letter have some meaning? Why not Console 1 is used instead of Console 1/A?

**Comment by ccordoba12** [comment]
You can connect a new console to the same kernel a previous console is using by going to the menu

    Consoles > Connect to an existing kernel

And that's when you'll get Console 1/B, 1/C, etc.
