### ISSUE TITLE
Spyder size in Applications is large - is it related to cache? 

### ISSUE THREAD

**Issue by solomonvimal** [spyder-ide/spyder#8744]
Please see the screenshot below. It looks like Spyder is consuming a lot of space in my macbook, I am not sure why this is so. Also, Spyder takes a long time to launch. Is this related to cache? If so, how do I clear it? Thanks.
![image](https://user-images.githubusercontent.com/2102394/52528206-67808e80-2c8d-11e9-9c31-47760ff2ffaf.png)

**Comment by solomonvimal** [comment]
6 hours later, it went up to another 45 GB, though I force quit Spyder and start it again. Looks like something weird is going on. 
![image](https://user-images.githubusercontent.com/2102394/52530860-f4910b00-2cc0-11e9-9f76-bcfa1315bc7e.png)

**Comment by ccordoba12** [comment]
The bug you're having was fixed a long time ago (a year or so), but since we stopped to creating our DMGs like two years ago, you need to get rid of them and install Anaconda instead.
