### ISSUE TITLE
Spyder should depend on QtWebEngine for pyqt >= 5.12

### ISSUE THREAD

**Issue by jenshnielsen** [spyder-ide/spyder#8747]
In PyQt5.12 the QtWebEngine has been split out into its own pypi package see 
https://www.riverbankcomputing.com/news/pyqt-512 but spyder does not depend on it so a new pip install of spyder fails on launch. 

### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?
In a clean env without pyqt or spyder installed
1. pip install spyder
2. spyder3.exe

### What is the expected output? What do you see instead?
```
Traceback (most recent call last):
  File "c:\users\jenielse\appdata\local\continuum\miniconda3\envs\mypipenv\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEnginePage
ModuleNotFoundError: No module named **'PyQt5.QtWebEngineWidgets'**
```
 
pip install pyqtwebengine fixes the issue and spyder launches normally

## Versions

* Spyder version: 3.3.3
* Python version: 3.6.8 
* Qt version: 5.12
* PyQt version: 5.12
* Operating System name/version: Windows 10

**Comment by ccordoba12** [comment]
We didn't know that was going to happen, else we'll have added it as a dependency in our 3.3.3 release. But we'll fix it for 3.3.4.
