### ISSUE TITLE
Closing moved files creates IndexError

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#8749]
### What steps will reproduce the problem?

- close all files so that you have untilted1.py
- open two files
- move/delete/rename them outside of spider
- when coming back to spyder, a windows appears that will ask you to close the first one. do that
- You end up on the second one. The windows doesn't appear
- click on untilted1.py
- click back on the second one
- a windows appears that will ask you to close it. do that
- Indexerror

### Traceback
```python-traceback
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/editor.py", line 1971, in current_changed
    (index, self.data[index].editor.filename))
IndexError: list index out of range
```

## Versions

* Spyder version: 4.0.0.dev0 dccf03854
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
pyls >=0.19.0     :  0.21.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for the very clear way to reproduce this.
