### ISSUE TITLE
Spyder has to wait 18 seconds before closing

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#8751]
On the following line:

https://github.com/spyder-ide/spyder/blob/0dff08677acde2d7e5389c757e859df1e8fbdae9/spyder/plugins/ipythonconsole/widgets/client.py#L500

Spyder creates a thread that will close all the channels of kernel_client.
unfortunately, kernel_client has a heartbeat channel that only wakes up every 18 seconds. (kernel_client.hb_channel)
This means that the created thread will have to wait until a heartbeat is heard.

somehow if I replace this line by `self.shellwidget.kernel_client.shutdown()` spyder closes immediately.

**Comment by impact27** [comment]
I created a pull request on Jupiter client: https://github.com/jupyter/jupyter_client/pull/420

**Comment by ccordoba12** [comment]
Ok, thanks a lot for your help @impact27!

**Comment by impact27** [comment]
As a workaround, how bad would it be to not call stop_channels?

**Comment by ccordoba12** [comment]
I don't know and I wouldn't like to speculate about it because I don't the Jupyter architecture that well.

**Comment by ccordoba12** [comment]
Closing because @impact27's PR was merged in jupyter-client.
