### ISSUE TITLE
open .mat with scipy.io.loadmat

### ISSUE THREAD

**Issue by elap2** [spyder-ide/spyder#8757]
### What steps will reproduce the problem?

after loading in to the variable explorer .mat file, I was clicking in the feature with type void2624, size (1,1), and value ndarray object of numpy module
the date is within this structure.

thanks

### Traceback
```python-traceback
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 476, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 661, in setup_and_check
    readonly, xlabels, ylabels))
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 540, in __init__
    ylabels=ylabels, readonly=readonly, parent=self)
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 154, in __init__
    self.vmin = np.nanmin(self.color_func(data))
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py", line 294, in nanmin
    res = _copyto(res, np.nan, mask)
  File "D:\Users\lapi2\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py", line 106, in _copyto
    a = a.dtype.type(val)
AttributeError: 'float' object has no attribute 'dtype'
WARNING:spyder.widgets.github.backend:failed to send bug report on github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}}
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by danieltomasz** [comment]
I cannot reproduce this behaviour with `3.3.3`. Could you include MWE with sample data? Or try to update to the latest `Spyder 3.3.3`, `Numpy 1.16.1`and `Scipy 1.2.1`.

It is also possible that there is something wrong with your input mat file.

**Comment by ccordoba12** [comment]
@elap2, this looks like an installation problem so you'd probably be better by reinstalling Anaconda and trying again.

**Comment by elap2** [comment]
> I cannot reproduce this behaviour with `3.3.3`. Could you include MWE with sample data? Or try to update to the latest `Spyder 3.3.3`, `Numpy 1.16.1`and `Scipy 1.2.1`.
> 
> It is also possible that there is something wrong with your input mat file.

import scipy.io
import os

os.chdir('directory_to_be_imported')
mat = scipy.io.loadmat('name_of_file.mat')

does spyder accept the objects from .mat workspaces?

thanks

**Comment by ccordoba12** [comment]
Please upload a mat file that it's generating this error so we can test it in our side.

**Comment by elap2** [comment]
Thanks Daniel, Thanks Cordoba

Please close the case, the scipy.io function loads the .mat variables correctly as mapping types => type(var) output: dict

I solved the problem as follow:

mport scipy.io
import os

os.chdir('directory_to_be_imported')
mat = scipy.io.loadmat('name_of_file.mat')
type(mat) # == dict
var = mat['key'].item(i)[j] #i and j are indexes of the variable

# and so on with the code to get the values
