### ISSUE TITLE
Text written in help pane gets automatically selected and replaced with every keystroke

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#8762]
**Steps to reproduce:**
* Type something in the help pane, in the field named “Object” where one puts names like `np.arange`.

**Expected behavior:**
After every keystroke, the text that was written there should remain, unless deleted or selected by the user.

**Actual behavior:**
After every keystroke, the full text there becomes selected, which makes it be deleted/replaced with every keystroke (so it only displays the last character that one typed).

**Reproducible:** always

**Setup:** Spyder 3.3.3, Python 3.6.5, running on either Windows 10 or Debian Linux (KDE).

**Comment by sapphire008** [comment]
This is indeed a problem. The only work around  I could think of is to type the query in a text editor and paste it in the search bar.

**Comment by ccordoba12** [comment]
What if we change the current behavior to expect an Enter from the user before searching of an object's help? Would that be better?

**Comment by david-cortes** [comment]
That’s certainly better than how it is right now, but isn’t it possible to revert that search field to how it was in 3.3.1?

**Comment by ccordoba12** [comment]
I think we didn't change anything related to that behavior, but we'll take a look at it for 3.3.4

**Comment by ccordoba12** [comment]
I can confirm this error, so we'll definitely fix it in 3.3.4

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
