### ISSUE TITLE
python softwares do not run on my windows 10 laptop

### ISSUE THREAD

**Issue by nilutpolkashyap** [spyder-ide/spyder#8765]
### Issue Report Checklist

* [* ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [* ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ *] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [* ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [* ] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [* ] Reset preferences with ``spyder --reset``
    * [ *] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [* ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I installed python idle on my laptop and the IDLE does start but does not respond and shows the error message "IDLE's sub process did not make a connection. Either IDLE cant start a sub process or personal firewall software is blocking the connection." The command prompt version of python IDLE s working fine. I also install the anaconda package but the whole package does not work. The Spyder IDLE simply does not respond and shows the message "Spyder has encountered an internal problem." The jupyter notebook also does not work. The cmd window just flashes for around 3-4 seconds and then disappears. The Anaconda Navgator also does not work. 
I also tried to install the Winpython package but the same problems persists as the Anaconda package. 
I also install the pycharm software. But it also does not respond.  It also shows errors. 

I tried to reinstall all the above mentioned softwares several times but the same problems continue to persists.

Please someone help me to figure out the problems due to which  I am facing the errors.

Thank You.....
### What steps reproduce the problem?

1. Tried to renistall the softwares but the problems persists.
2. Tried several troubleshooting problems but the problems still persists

### What is the expected output? What do you see instead?
1. Opening of the Spyder environment
2. Opening of the python IDLE environment
3. Opening of pycharm environment

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.7
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```
![untitled](https://user-images.githubusercontent.com/47447024/52727669-bb67dc00-2fdb-11e9-8fdd-6c3d3467cbc7.png)
![untitled1](https://user-images.githubusercontent.com/47447024/52727671-bc990900-2fdb-11e9-939a-bc14738eeabb.png)

**Comment by nilutpolkashyap** [comment]
My system information
OS - Windows 10 64 bit
Intel i3 2nd gen.
4 gb RAM
Nvidia geforce with CUDA

**Comment by ccordoba12** [comment]
![untitled](https://user-images.githubusercontent.com/47447024/52727669-bb67dc00-2fdb-11e9-8fdd-6c3d3467cbc7.png)

Please fill out ths form by writing the information we ask you to fill (the form is almost self-explanatory) and send it to us by providing your Github credentials. That form contains much more detailed information that will help us to understand your problem.

I'm closing this issue for now because without that information we can't help you, sorry.

**Comment by nilutpolkashyap** [comment]
Can u please help me. Which form do I need to fill?

**Comment by ccordoba12** [comment]
The one in the screenshot above.

**Comment by ccordoba12** [comment]
I mean, the one it says

**Spyder has encountered an internal problem**.

Please read what it says with care and you'll understand what I'm talking about.

**Comment by nilutpolkashyap** [comment]
I wanted to fill the form. But the whole page does not respond. I can't type nor can I click anywhere. The whole page just hangs until I have to close it. Please help me.

**Comment by ccordoba12** [comment]
Well, your screenshot shows some strange symbols back in the IPython console. That could mean that you installed Anaconda in a path with special characters (like `ñ` or `á`), which could be causing your problem, so should try to rename that directory or create a new Windows user without special characters and install Anaconda there.

You also seem to have a different Python installation other than Anaconda, so you should try to uninstall it.

But all these are just pure speculations based on the extremely little info you provided. However, other than this advice, I'm afraid there's nothing else we can do for you, sorry.

**Comment by stonebig** [comment]
this part in your screenshot is very strange:
![image](https://user-images.githubusercontent.com/4312421/52744252-72fcee00-2fdc-11e9-9929-0a61d7b8d698.png)

you may start "WinPython Command Prompt.exe"

type CHCP <enter>

and post the screen shot
![image](https://user-images.githubusercontent.com/4312421/52744362-d25afe00-2fdc-11e9-8b3a-11484e6652bd.png)

maybe will it give more clue

**Comment by nilutpolkashyap** [comment]
![untitled2](https://user-images.githubusercontent.com/47447024/52756606-ef68ee80-3027-11e9-9606-73b23df4612a.png)

Sir as instructed by you, I have typed the command  chcp in the "WinPython Command Prompt.exe" and got  the result "Active Code Pages= 437".

**Comment by nilutpolkashyap** [comment]
Sir, can u please with the above

**Comment by stonebig** [comment]
hum, code page 437 means original US DOS codepage. Did you tweak the langage of your Windows PC ?  Uttar Pradesh, India  ?

**Comment by nilutpolkashyap** [comment]
@stonebig sir , what does tweak mean????
I don't know how to tweak the language.

**Comment by stonebig** [comment]
ok.

**Comment by nilutpolkashyap** [comment]
@ccordoba12 sir can you please help me with my problem?

**Comment by nilutpolkashyap** [comment]
@stonebig can you please guide me further

**Comment by ccordoba12** [comment]
We really don't understand your problem. My last advice is for you to reinstall Windows because there's something seriously wrong with your current installation.

Sorry, but I don't see any other solution.

**Comment by stonebig** [comment]
well, as a stupid try, as I'm clueless, I would suggest you experiment IDLE on a Python-2.7 32bit, just to see if you arrive to make IDLE work at last. for example https://sourceforge.net/projects/winpython/files/WinPython_2.7/2.7.10.3/
