### ISSUE TITLE
Apparent memory leak: over 10 gibibytes

### ISSUE THREAD

**Issue by dHannasch** [spyder-ide/spyder#8766]
### What steps will reproduce the problem?

Unfortunately I cannot reproduce this reliably; I'm hoping to connect with other people experiencing this so that we can find common factors.

This is a standard Anaconda install on Ubuntu 16.04.
The only unusual thing about the Anaconda setup is that it uses a proxy (set in .condarc).
Python version 3.7.1. Conda version 4.5.12.
Spyder version 3.3.2 installed via conda.

Every so often, when Spyder is open, memory usage for the process "ZMQbg/1" will climb and keep climbing past 10 GiB (at which point I close Spyder, which ends that process; presumably if Spyder were left open it would keep climbing indefinitely).

I cannot stress enough that Spyder is not running anything; I open Spyder, open a few small Python files for viewing (without running them), and leave it until "ZMQbg/1" starts chewing up a lot of RAM. Except...sometimes that never happens, memory usage of ZMQbg/1 stays at 39.3 MiB forever, and I don't know what the difference is.

A search of known issues turned up nothing that looks related to this. (Several issues about memory usage and freeing memory, but only when Spyder is actually running something.) So...now the next time someone searches, they'll find this.

(https://github.com/spyder-ide/spyder/issues/5268 sounds similar, but not similar enough to be related.)

I'm using Spyder's issue reporter, so I believe my environment information will be attached.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-43-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
What happens if instead of closing Spyder you restart the kernel of the (presumably) only console you have opened?

**Comment by dHannasch** [comment]
Good question, I don't know. I'll try that the next time I can get it to occur.

**Comment by ccordoba12** [comment]
Please see https://github.com/jupyter/help/issues/507. It looks that this is not related to Spyder but to the Jupyter architecture that we use to run code in the background.

So I'm closing this for now.
