### ISSUE TITLE
Icons not displaying in Options menus in macOS

### ISSUE THREAD

**Issue by juanis2112** [spyder-ide/spyder#8767]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder icons were removed in Mac OS X because of the Human Interface Guidelines, which don't allow icons in menus but it would be better if there could be icons in at least the menus that are not part of the main menu.

### What steps reproduce the problem?

1. 
2. 
3. 

### What is the expected output? What do you see instead?

Icons are not displaying in the consoles menu.

![Uploading Screen Shot 2019-02-13 at 9.16.51 PM.png…]()

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@juanis2112, this is an interesting issue and I think you'll have fun solving it.

For this I think you need to

1. Remove [this line](https://github.com/spyder-ide/spyder/blob/master/spyder/app/mainwindow.py#L3276-L3277).
2. Connect an slot to the `AboutToShow`/`AboutToHide` signals of all main menus to hide/show their icons, respectively.

**Comment by goanpeca** [comment]
>muestren los íconos en los menús de opciones de los plugins pero no en los menus principales de Spyder

**Comment by ccordoba12** [comment]
This is just for Gonzalo to remember what this issue is about.
