### ISSUE TITLE
The spyder help menu doesn't work

### ISSUE THREAD

**Issue by gordonruby** [spyder-ide/spyder#8775]
### What steps will reproduce the problem?

I simply opened Spyder through Anaconda for the first time and clicked on the tutorial button because I'm new to Spyder. It basically encountered a problem right away.

### Traceback
```python-traceback
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/help.py", line 746, in handle_link_clicks
  File "/anaconda3/lib/python3.7/site-packages/spyder/plugins/help.py", line 740, in show_tutorial
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda3/lib/python3.7/site-packages/spyder/utils/help/tutorial.rst'
```

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 17.7.0

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is an installation issue. I don't understand why `tutorial.rst` (the file that contains our tutorial) was not installed in your case, but I verified that it's part of our conda packages.

So you could try to solve this by opening Terminal.app and running there

    conda install -f spyder

**Comment by ccordoba12** [comment]
Closing because of lack of response.
