### ISSUE TITLE
Spyder 3.3.3 cannot run asyncio script when automatic graph out enabled

### ISSUE THREAD

**Issue by greg500** [spyder-ide/spyder#8777]
## Problem Description

Hello,

Since spyder 3.3.3 update script with asyncio code will block when automatic graph  out is enabled.

Here is a basic example:

```python
import asyncio
import nest_asyncio
nest_asyncio.apply()
async def main():
    
    await asyncio.sleep(1)
    print('hello')

loop=asyncio.get_event_loop()
loop.run_until_complete(main())
```    

This script will freeze without throwing an exception.

Downgrading to spyder 3.3.2, spyder-kernels 0.2.6, ipykernel 4.9.0 will solve
the problem

### What steps reproduce the problem?

1. Conda  update spyder to 3.3.3
2. Reset spyder settings
3. Preferences ->Ipython console -> graph tab -> out  automatic
4. Run the above script

## Versions

* Spyder version: 3.3.3
* Python version: 3.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Ipykernel 5.1.0
* Operating System name/version:  Windows 10 64 bits

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.28.2 (OK)
jedi >=0.9.0      :  0.12.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.14.3 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  1.6.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
> Downgrading to spyder 3.3.2, spyder-kernels 0.2.6, ipykernel 4.9.0 will solve

I think this is an IPython issue only, so please update spyder and spyder-kernels to their latest versions while leaving ipykernel in 4.9.0 and try again.

**Comment by greg500** [comment]
Thank you for your answer.
I have forced the ipykernel downgrade and it works.

**Comment by ccordoba12** [comment]
Ok, so that means this is not an Spyder error. I think your problem is related to this issue

https://github.com/ipython/ipykernel/issues/372

which was closed in ipykernel, so I'd say there's nothing to do about it.
