### ISSUE TITLE
Spyder not opening

### ISSUE THREAD

**Issue by realperson999** [spyder-ide/spyder#8780]
### Issue Report Checklist

* [yes ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [yes ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [yes, pip ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [yes ] Tried basic troubleshooting (if a bug/error)
    * [yes ] Restarted Spyder
    * [yes ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [yes ] Tried the other applicable steps from the Troubleshooting Guide
* [yes ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After doing a mass-upgrade of all my installed pip packages(probably my woopsy), spyder wouldn't open. After uninstalling all pip modules, uninstalling python, deleting everything from the disk that's python/spyder related (by using those two words as search terms) -> restarting -> installing python 3.7.2 fresh, reinstalling all packages and spyder via pip -> the same problem persists

I don't get any errors when running spyder3 from the command line. The mouse indicates something is loading when I try to open spyder but no application opens.

## Versions
* Spyder version: 3.3.3
* Python version: 3.7.2
* Qt version: 5.12.1
* PyQt version: 5.12
* Operating System name/version: Windows 10

### Dependencies
```
qtconsole 4.4.3
rope 0.12.0
pyflakes 2.1.0
sphinx 1.8.4
pygments 2.3.1
pylint 2.2.2
pycodestyle 2.5.0
psutil 5.5.0
qtawesome 0.5.6
pickleshare 0.7.5
pyzmq 17.1.2
qtpy 1.6.0
chardet 3.0.4
numpydoc 0.8.0
cloudpickle 0.8.0
jedi 0.12.2
spyder-kernels 0.4.2
ipython 7.2.0
pandas 0.24.1
numpy 1.16.1
sympy 1.3
cython 0.29.5
```

Edit: I thought I would add I tried downgrading tornado like in #8763, but with no success.

**Comment by realperson999** [comment]
Downgrading pyqt5 to 5.11.3 fixed it. 5.12 was the issue.

**Comment by ccordoba12** [comment]
Ok.
