### ISSUE TITLE
Can't make static code analyisis when using geopandas.read_file()


### ISSUE THREAD

**Issue by ccamara** [spyder-ide/spyder#8788]
### What steps will reproduce the problem?

Whenever I have the following code on my file:

```python
geopandas.read_file("data/export.geojson")
```
I cannot execute Static code analysis on spyder 3.3.3, as it gets stopped and a new black window with "error" title is displayed, but no more information.

If I comment out that line code analysis work as usual.

### Traceback
```python-traceback
RecursionError: maximum recursion depth exceeded

WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'code': 401, 'json': {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
```

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Linux 4.15.0-45-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.3 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
psutil >=0.3      :  5.5.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.24.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Please report this problem here:

https://github.com/PyCQA/pylint/issues

because the only thing we do is to call `pylint` behind the scenes to generate the reports shown in our "Static code analysis" pane.

Thanks!

**Comment by ccamara** [comment]
Thank you, I am new to spyder and python and I posted it here using the crash form that appears on spyder.

I will do as you request, although I am afraid there is not much information about the proper error due to the fact that spyder error window is completely black and does not give any kind of feedback about the error.

**Comment by ccordoba12** [comment]
You can report the Recursion error you got above. That should be enough.

**Comment by ccamara** [comment]
Thank you again!
