### ISSUE TITLE
Unable to increae the recursion depthusing sys

### ISSUE THREAD

**Issue by bertramwooster** [spyder-ide/spyder#8796]
### What steps will reproduce the problem?

Implemented an elementary recursion-sort on a list of len 5000; invoking sys.setrecursionlimit(10000) and then execution just casuses the kernel to die.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.3 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Does your code run fine in the Jupyter notebook?

**Comment by bertramwooster** [comment]
Nope, it doesn't. But I tried calling it from anaconda prompt and it works fine there.

**Comment by ccordoba12** [comment]
> Nope, it doesn't

Then this is a Jupyter problem, not a Spyder one. Please report it here:

https://github.com/ipython/ipykernel/issues
