### ISSUE TITLE
Can't Run QT scripts withou program hang... Workarounds on StackOverflow don't work

### ISSUE THREAD

**Issue by BillRoss1854** [spyder-ide/spyder#8799]
### What steps will reproduce the problem?

The most basic qt application hang when run inside Spyder console.  If this does not get resolved I will explore alternative ides

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Please read our guide (which you can easily find by googling something like "How to run PyQt applications in Spyder")

https://github.com/spyder-ide/spyder/wiki/How-to-run-PyQt-applications-within-Spyder

**Comment by BillRoss1854** [comment]
Carlos:
Thanks for the response!  I've spent all morning trying the suggestions on
the suggested post.  This includes running the sample application.  With
each try I can get the application to run but it hangs so that I need to
restart the kernal each time I run the application.
I'm running Spyder 3.3.2 and Python36... Would that make a difference?
Regards
Bill

**Comment by ccordoba12** [comment]
I don't know what happens, sorry. The example application runs fine for me on Windows.

**Comment by ccordoba12** [comment]
You could update Spyder, maybe that helps.
