### ISSUE TITLE
urllib.request.urlopen imported but unused how can i handle this error??

### ISSUE THREAD

**Issue by MehranTariq** [spyder-ide/spyder#8804]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.8
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.1.0 (OK)
pycodestyle >=2.3:  2.5.0 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  None (NOK)
sphinx >=0.6.6   :  1.8.4 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.13.2 (OK)
nbconvert >=4.0  :  5.4.0 (OK)
sympy >=0.7.3    :  1.3 (OK)
cython >=0.21    :  0.29.5 (OK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.2.0 (OK)
pylint >=0.25    :  2.2.2 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder
