### ISSUE TITLE
Strange lines after logging in/out of remote desktop session

### ISSUE THREAD

**Issue by ibraheemalkilanny** [spyder-ide/spyder#8805]
### What steps will reproduce the problem?

After opening Spyder using normal PC monitor, I log into PC from another PC with remote connection. The lines of the opened editor become strange: some of them are larger, some of them are smaller, some of them are more padded, etc.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.1 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
> After opening Spyder using normal PC monitor, I log into PC from another PC with remote connection.

This is not enough to help you. Please describe from what operating system (Windows, Linux) to which operating system you're connecting and what program you're using to perform the connection.

**Comment by ibraheemalkilanny** [comment]
Sorry, I thought that would be unncessary to mention.

This occurs with me using Windows 10, Remote Desktop Connection (RDP). I suspect that RPD is modyfing screen resolution of the remote PC to match the screen viewing, after that RPD is restoring old resolution settings (that were before connection). Then Spyder editor becomes with very strange lines.

**Comment by ccordoba12** [comment]
This looks more like a problem in RDP than in Spyder itself. Since I use Teamviewer and I don't have this problem, I'm going to close this issue, sorry.

**Comment by ibraheemalkilanny** [comment]
Thank you. To know why this IDE is not used by many people, see how much it is bad to waste time to report a BUG in it without any desire to enhance. This BUG is happen after screen resize / resolution change.

**Comment by ccordoba12** [comment]
There's nothing we can do on our side about this, sorry.

I don't think you know how Spyder is built, but it's a pure Python package built on top of a graphical toolkit called Qt. So even if we were able to find the source of this problem, it needs to be solved in Qt, not here.

And sorry for my brief response, but I have to answer ~10 issues here plus ~3-5 questions on StackOverflow about Spyder (which doesn't seem to indicate low usage, as you suggest) and I try to provide at least a solution for each. In this case, my advice is for you to use Teamviewer or another remote connection technology if you want to keep using Spyder (if not, you're welcome to use any other program you like).

**Comment by bexer** [comment]
I have the same setup and problem. I've found that the problem goes away after resizing the Spyder window. Not sure why it's happening initially.
