### ISSUE TITLE
Spyder help in Rich mode not rendering

### ISSUE THREAD

**Issue by PJussel** [spyder-ide/spyder#8806]
### What steps will reproduce the problem?

Starting spyder with resetted settings, typing in ipython console:

```
import numpy as np
np.asarray()
```
   
Now pressing Ctrl-I should display help about the function. However, whild source correctly states "console" and object "np.asarray", there is no help rendered, the window remains empty. Changing to plain text shows the help. 

### How does it look like?

![rich](https://user-images.githubusercontent.com/12828726/53073137-7b2ac100-34e7-11e9-8f30-36ca7fa7ec86.jpg)

Above screenshow shows the missing help information.

![plain](https://user-images.githubusercontent.com/12828726/53073156-84b42900-34e7-11e9-8b45-3e9d797d192e.jpg)

In plain text everything looks fine...

### Environment

IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
sympy >=0.7.3     :  1.3 (OK)

**Comment by ccordoba12** [comment]
How did you install Spyder?

**Comment by PJussel** [comment]
Installation procedure:

- installing miniconda (64bit Version, Windows 10)
- conda update conda
- conda install anaconda

After this procedure the incorrect displaying already was there, therefore I did an additional

- conda update spyder

**Comment by ccordoba12** [comment]
I think this is a problem with graphics card drivers. Please try to update them and also DirectX.

If that doesn't work, please dowgrade Qt/PyQt with

    conda install qt=5.6 pyqt=5.6

That should fix your problem.
