### ISSUE TITLE
A python console failed to start (urgent problem)

### ISSUE THREAD

**Issue by tonyVeco** [spyder-ide/spyder#8809]
I am using Anaconda3 (64bit) for windows 10, and I have worked until yesterday without any problem with Spyder , after creating a Python3.4 environment (spyder version 3.1.2)

Today I have opened again Spyder but I got this message :  

> A python console failed to start

I have tried to quit Spyder and open it again but the issue remains and I don't know what to do, as I did not modify anything in these days to justify this issue.  How can I solve this problem? I am using it for work so it is quite urgent!

**Comment by ccordoba12** [comment]
Please open an Anaconda Prompt and run there

    spyder --reset

That could help.

**Comment by tonyVeco** [comment]
Oh thanks for the quick reply!! I did it, and the reset was successful, but the problem has remained

**Comment by tonyVeco** [comment]
I now remember, what I did before opening spyder today, was opening the jupyter Notebook (py34) because I clicked wrongly on it. I immediately closed its window and went to open spyder, and then the problem began. I don't know if that can be of help to understand

**Comment by ccordoba12** [comment]
You could create a new conda environment and start afresh by running this command in an Anaconda Prompt:

    conda create -n spy.env python=3.6 spyder

After that you need to

    activate spy-env
    spyder

**Comment by tonyVeco** [comment]
oh ok, but I can also do this for python 3.4 is it right???
and before that, should I need to delete the old 3.4 environment?

**Comment by ccordoba12** [comment]
> oh ok, but I can also do this for python 3.4 is it right???

Yes, you can that too. For that you just need to change the first command above:

    conda create -n spy.env python=3.4 spyder

> and before that, should I need to delete the old 3.4 environment?

No, you don't need to.

**Comment by tonyVeco** [comment]
Thanks!!! i have created it and it seems to work!!!
