### ISSUE TITLE
Spyder won't start with unicode in the install path in Window 10

### ISSUE THREAD

**Issue by Kadir** [spyder-ide/spyder#8817]
Nice

**Comment by bcolsen** [comment]
Google Translate from Turkish:
>CHRISTMAS OROSPU CHILDREN. ÇALIŞMIYO WORKSHOP
I set it up 9 times
QT SOUND

That doesn't give us a lot to work with unfortunately. Please try to install Spyder using the Anaconda python distribution.

**Comment by Kadir** [comment]
Sorry, I have unicode letters in my username, so spyder could not handle them, and couldnt import pyqt5 libraries to launch. I had reinstalled to different directories. But the problem is it install some of the libraries under appdata/roaming/ folder.
And its not turkish its Greek.

**Comment by bcolsen** [comment]
> And its not turkish its Greek.

Sorry about that. That was google translate's best guess.

> I have unicode letters in my username

What version of python are you using? That should be fine in python3, but it may be a problem in the Anaconda installation.
