### ISSUE TITLE
duplicate scroll bars on CodeEditor widget

### ISSUE THREAD

**Issue by athompson673** [spyder-ide/spyder#8820]
### Problem Description (more of an annoyance really)

This may or may not have been a problem with earlier versions, but I have begun noticing it having updated OSX to Mojave, which is a bit more aggressive about auto-hiding scroll bars. The issue is that whenever scrolling vertically inside an editor, the native os vertical scroll bar un-hides, and pushes the ScrollFlagArea scroll bar over to the side. This is distracting, every time it moves, and is entirely redundant as the ScrollFlagArea already implements all the functionality of a native scroll bar (Therefore I daresay it *should be just outright disabled). I'd like to keep the OS wide scroll bar setting for other applications, but this is a specific instance (even within spyder) where I don't want the system scroll bar. I tried hiding the scroll bar in various ways and came up with a mostly satisfactory solution, however I believe the best solution might be re-implementing the ScrollFlagArea as a subclass of a Qt scrollbar rather than just a QWidget. This I haven't investigated hardly at all, so maybe not.

### Working solution

getting rid of the OS scrollbar (or changing the hide policy) breaks the custom one, so I settled on just making it 1 pixel wide, and I think it even doesn't draw the 1 px anyway (I looked and couldn't see it)

/spyder/widgets/sourcecode/codeeditor.py:

```
class CodeEditor(TextEditBaseWidget):
    # ...
    def __init__(self, parent=None):
        TextEditBaseWidget.__init__(self, parent)
        
#        self.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff) #XXX (wrecks vertical scaling)
#        self.verticalScrollBar().hide() #XXX (does nothing)
#        self.verticalScrollBar().setVisible(False) #XXX (doesn't hide area, only the handle)
#        self.verticalScrollBar().setStyleSheet("QScrollBar {height:0px;}") #XXX (same as always off)
        self.verticalScrollBar().setStyleSheet("QScrollBar {width:1px;}") #XXX 

```
* Spyder version: 3.3.3
* Python version: 3.7.0
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: OSX Mojave 10.14.1

**Comment by ccordoba12** [comment]
Thanks for your interest in helping us with this, but this problem is already solved and its solution will be part of Spyder 4.
