### ISSUE TITLE
Executing ‘run selection’ on function definition line (without selecting it) does not execute lines under it

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#8822]
**Steps to reproduce:**
* Write some non-lambda function in the editor, e.g.
```python
def afunction(x):
	x = x + 1
	return x
```
* Click on the line that starts the function, without selecting any text (e.g. `def afunction(x):`)
* Execute the keyboard shortcut for “run selection”

**Expected behavior:** should execute the whole function like in other IDEs.

**Actual behavior:** executes only the first line, and thus fails to define the function.

**Comment by ccordoba12** [comment]
This is a known issue and not an easy one to fix, but thanks for reporting.
