### ISSUE TITLE
Remote Kernel Connection Hanging

### ISSUE THREAD

**Issue by the-modeler** [spyder-ide/spyder#8825]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder is hanging on "Connecting to kernel..." when I try to connect to a remote iPython kernel. I can configure the port forwarding manually and make it work, but it's annoying and seems wrong

### What steps reproduce the problem?

1. run `python3 -m spyder_kernels.console` on server
2. run `scp sever:/run/user/XXXX/jupyter/kernel-1234.json ./` on client
3. start spyder
4. point spyder at `kernel-1234.json` and fill out remote kernel fields
5. click ok
6. observe "Connecting to kernel..." in iPython area

ALTERNATIVELY
3a. run `ssh -L port1:localhost:port1 -L port2:localhost:port2 -L port3:localhost:port3 -L port4:localhost:port4 -L port5:localhost:port5 username@server` on client using port numbers from json file
4. point spyder at `kernel-1234.json` and do not check `This is a remote kernel`
5. click ok
6. success!

### What is the expected output? What do you see instead?

I expected to get a usable iPython terminal, instead it says connecting to kernel forever. Wireshark shows that there is data flowing along the ssh connection, but I can't get much information out of it

Manually setting up the port forwarding worked fine, and I'm going to write a configuration script that takes care of stuff for me. I also saw some discussion online about spyder implementing some kind of inline sshfs system to explore remote files, and I'd be very interested in that feature or advice on mocking up the functionality

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Linux 4.15.0-43-generic

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.8 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
> Manually setting up the port forwarding worked fine, and I'm going to write a configuration script that takes care of stuff for me

I'm glad you made things work. It seems you're using a setup for sshd different from the default one? I say it because I get an ssh connection just fine on my own Linux machine.

**Comment by the-modeler** [comment]
I don't think I've changed my sshd configuration, but I don't know how to check to see if it's default. I normally use a `.ssh/config` file on the client machine, so I tried using the server name listed there as well as the server ip address and the dns name

I am using ssh_agent. Could that be interfering? I can't see my .ssh/id_rsa key from the spyder key browser but I've tried hardcoding the path and putting my server password in the password field

**Comment by ccordoba12** [comment]
> I am using ssh_agent. Could that be interfering?

What do you mean by this?

**Comment by the-modeler** [comment]
I'm using ssh-agent to manage my rsa keys. I'm pretty sure this is the typical workflow, but I wanted to mention it in case spyder is trying to use something else

**Comment by ccordoba12** [comment]
So you're using an ssh key instead of your system password to connect to the remote kernel?

**Comment by the-modeler** [comment]
I've tried using my key and I've tried using the system password

**Comment by ccordoba12** [comment]
Sorry, I doubt we can do anything about this in Spyder because the functionality is working (at least for me). Most probably it has to do with something in your server.
