### ISSUE TITLE
Variable explorer shows wrong size

### ISSUE THREAD

**Issue by marinomaria** [spyder-ide/spyder#8831]
## Problem Description
When I run my script using Pandas some variables appear on the variable explorer wrong sized. At first, I thought there was a problem with my code, so I double-checked it and tried ```np.shape()``` on the variables that seemed to be wrong. But when I do this the output is different from what the variable explorer shows, as you can see in the image below:
Variables "_edad_", "_genero_", "_manipulada_",  "_polarizacion_", "_dicc2_" and "_dicc3_".

![image](https://user-images.githubusercontent.com/44098774/53267981-95b99180-36c3-11e9-8965-08bbaf9046f6.png)

I have tried already restarting Spyder, restarting my computer and ``` spyder --reset``` on the Anaconda prompt.

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.0 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
Please upload a simple code that consistently shows this error. That way we'll be able to better understand what's happening here.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by henrikbrautmeier** [comment]
The same error occurs for me. I think it happens if the workspace is really large and many big variables are stored. I hope I find time to artifically recreate this error wihtin the next weeks
