### ISSUE TITLE
runfile error for all code

### ISSUE THREAD

**Issue by ishreshth** [spyder-ide/spyder#8840]
### What steps will reproduce the problem?

import files.
matplotlib.pyplot is not recognized. 
enter file to read
you will get the readfile issue and cannot work after that

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 7

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
Sorry but your description is not enough to help you. Please provide:

1. The code that you're running.
2. The error you're getting when running that code.

**Comment by ishreshth** [comment]
``
![capture](https://user-images.githubusercontent.com/35741298/53301006-b6284e00-3873-11e9-8a99-b94dea06214f.PNG)

**Comment by ccordoba12** [comment]
You need to enclose your last statement (`df.head()`) in a `print` one to see its output in the console, like this:

    print(df.head())

**Comment by ishreshth** [comment]
Hey That works! thanks a lot.
