### ISSUE TITLE
i don't know whats wrong with my code. some one help!!!

### ISSUE THREAD

**Issue by low-ham** [spyder-ide/spyder#8853]
## Problem Description
I don't know whats wrong with the code line...       (var(input), name (""))

can someone please fix it.

### What is the expected output? What do you see instead?
the expected out come is a guessing game

this is the entire code...

5# -*- coding: utf-8 -*-
"""
Created on Tue Feb 27 19:42:25 2018

@author: hcarr
"""
def main():
   import random
import time
   (var(input), name (""))
number = random.randint(1, 10)
tries = 1
print('hi what is your name?')
  (var(input) name(""))
print ('hi ' name ' i am thinking of a number between 1 & 20')

guess = int(input("have a guess  "))
if guess < number:    
   print("Your guess is too low.")
if guess > number:
   print("Your guess is too high.")
while guess != number:
   tries += 1
guess = int(input("try again  "))
if guess < number:
   print("Your guess is too low.")
if guess > number:
   print("Your guess is too high.")
if guess == number:
   print("well done ",name," the number was", number, "and it only took", tries, "tries")
time.sleep(5) 
question = input("do you want to play again [Y/N] ")
if question == "y":
   main()
else :
    if  (datetime.now(<0400)
    print("thanks for playing ",name," enjoy the rest of your day.")
    
else: (datetime.now(>1900)  
print("thanks for playing",name," enjoy the rest of your night.")
    
 exit
main()   
```

**Comment by ccordoba12** [comment]
Sorry, this is not a general Python programming forum but a place to report problems or bugs present in Spyder.

You can consider asking your question here:

https://stackoverflow.com/
