### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by tanmayg** [spyder-ide/spyder#8863]
### What steps will reproduce the problem?

I simply started the spyder and it came up with the error.

Before that I ran command to disable proxy on my system:
set NO_PROXY=continuum.io,anaconda.org

And I also updated spyder with:
conda update spyder

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.6
* Qt version: 4.8.7
* PyQt4 (API v2) version: 4.11.4
* Operating system: Windows 7

### Dependencies

```
pyflakes >=0.6.0 :  2.0.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.8.2 (OK)
rope >=0.9.4     :  0.11.0 (OK)
jedi >=0.9.0     :  0.13.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.3 (OK)
cython >=0.21    :  0.28.5 (OK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.2.0 (OK)
pylint >=0.25    :  2.2.2 (OK)
```
G: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder
