### ISSUE TITLE
Update __class__/type attribute of existing instances when reloading class definition

### ISSUE THREAD

**Issue by daharn** [spyder-ide/spyder#8866]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
This is less a problem than a feature request, although it can lead to some headaches, especially if you use spyder as a Matlab replacement, that means working interactively with objects in a live interpreter session and saving workspace objects to disk using serialization.

With spyders UMR in place, recent changes in module files lead to the module being reimported, meaning that changed function, class and method definitions can be accessed immediately, even by function objects or class instances that were initiated before these changes took place (Although tab completion usually does not work straight away, but that is a minor concern).

However, even though the existing "old" class instances ("old" meaning from before updating the module containing their definition) behave exactly as any newly initiated instances in a live interpreter session, the result of a call of `instance.__class__ `or `type(instance)` will point to a different location than for any newly initiated instances.

Apart from the fact that this somewhat feels wrong (instances behaving like they were initiated with the latest class definition but still pointing to a former class definition as their origin), this leads to issues when trying to serialize (i.e. pickle) these kind of objects. pickle will complain that `< class > is not  the same object as  < class >`, which it indeed isn't. But since the old class object does not exist any more (except from memory) there is no way these objects can be pickled now.

### What steps reproduce the problem?

1. Writing a simple module named `module.py` containing a class definition:
```
class Spam():
    def ham(self):
        pass
```

2. Go to the ipython session and initiate an object:
```
>>> from module import Spam
>>> spam  = Spam()
>>> spam.ham()

```
3. Now change the definition in `module.py` to

```
class Spam():
    def ham(self):
        print('ham')
        
    def eggs(self):
        pass
```
4. Now back in the interpreter we find 
```
>>> spam.ham()
ham
>>> spam.eggs()

```
so the changes are immediately reflected in the "old" instance spam.
5. Now instantiate a new object `new_spam`:
```
>>> new_spam = Spam()
>>> type(new_spam) is type(spam)
False
```
So even though they would act identical in all aspects, they are still considered different types. Since pickle (or dill) looks up any class definition of objects by name before pickling them, this will fail because the class name will lead to a different location than what `__class__` points to.

### What is the expected output? What do you see instead?

A possible ad hoc solution is to redefine the `__class__` attribute of the "old" instance:
```
>>> spam.__class__ = module.Spam
>>> type(spam) is type(new_spam)
True
```
Would it make sense and would it be even possible to automatize this for all existing instances in the workspace (and possible nested instances inside lists and other instances)?

Or is the above the desired behavior? It makes sense for a regular python session, where you usually wouldn't change scripts "on the fly", but since Spyder emulates Matlabs more interactive workflow, it might be more intuitive to implement automatic instance updates here.

## Versions

* Spyder version: 3.3.3
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: CentOS Linux 7

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.5 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
psutil >=0.3      :  5.5.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
> Would it make sense and would it be even possible to automatize this for all existing instances in the workspace (and possible nested instances inside lists and other instances)?

I think this would require a dictionary mapping new classes to old ones. But that needs to be provided by the user because I really don't see how we could do it programmatically. So I guess this is not possible?

Besides, unless you want to invest the time to implement a solution, this seems a pretty narrow use case for us to devote time to it. So do you want to work on it?

**Comment by daharn** [comment]
After looking into this a little more, it seems like it is merely an ipython issue than a spyder issue:

https://github.com/ipython/ipython/issues/11588#issuecomment-464949800

Just to be sure, what exactly is the difference between spyder's UMR and ipython's %autoreload, that is, how do they interact?

**Comment by ccordoba12** [comment]
They really don't interact: `%autoreload` reloads a file that has been *previously imported* (that's the critical part) as soon as it's saved; and the UMR forces a module reload by deleting the module from `sys.modules`.

Since this is an IPython issue, I'm closing it.

**Comment by daharn** [comment]
Yes, thank you. So just to wrap this up: With `%autoreload` enabled, does UMR offer any additional functionality? Are there any use cases where updated code would not be detected and reloaded by the former but included when re-importing the module?

**Comment by ccordoba12** [comment]
`%autoreload` reloads the code immediately in the console, so it's useful if you're iterating over a piece of code by making changes in your module and trying them immediately in the console (something that I find extremely useful and the reason why I decided to turn on `%autoreload` by default in our consoles, even if IPython doesn't do that).

The UMR is useful when you don't want to import first all your local modules one by one to the console so `%autoreload` can make its magic, but instead you want to make modifications to several modules at the same time and check them by running a single master file (e.g. `run_analysis.py` or something like that).

**Comment by daharn** [comment]
Should be solved in the next IPython release: 
https://github.com/ipython/ipython/pull/11644#issuecomment-502927225
