### ISSUE TITLE
Spyder crash when trying to save a new file or load a file.

### ISSUE THREAD

**Issue by JiataoWen** [spyder-ide/spyder#8867]
## Problem Description
Spyder crash when trying to save a new file or load a file.

### What steps reproduce the problem?
1. check on "open file" or "save as"
2. check on "Browse a working directory"

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 5.6.2
* Qtpy version: 1.5.2
* Operating System name/version: windows 7

I read the #3903, but did not help.

**Comment by ccordoba12** [comment]
> Spyder crash when trying to save a new file or load a file.

What's the crash? Do you see any errors you can report to us? Else we can't offer any assistance to you, sorry.

**Comment by JiataoWen** [comment]
An alert appears when I click "save as".
![capture](https://user-images.githubusercontent.com/35470574/53670250-0d4d6a80-3c48-11e9-86bc-6910e6ec1a85.PNG)

**Comment by ccordoba12** [comment]
Sorry, that's still not enough to help you. Please start Spyder in terminal (cmd.exe) with this command

    spyder

and report back if any errors are logged there.

**Comment by JiataoWen** [comment]
my PC has some hardware problem, and i am fixing it. I will upload the error message later. thanks for the supporting.

**Comment by JiataoWen** [comment]
Sorry, there is no any error message reported from terminal and Anaconda Prompt. Are there any log files that I can check?

**Comment by ccordoba12** [comment]
No. Please open the Anaconda prompt, run there

    conda update spyder qt pyqt

and try again.

**Comment by JiataoWen** [comment]
After the updates, I can't run the Spyder.

![capture](https://user-images.githubusercontent.com/35470574/53931536-87745980-4063-11e9-999a-2baab2c76e60.PNG)

**Comment by ccordoba12** [comment]
This is a problem with your firewall or antivirus. Please deactivate them and try again.
