### ISSUE TITLE
Fatal Error in Launcher when trying to "open with" spyder3

### ISSUE THREAD

**Issue by ItimadFang** [spyder-ide/spyder#8869]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am able to open .py files after I have launched Spyder. I am unable to open .py files in Spyder by double-clicking on them. I tried right-clicking and using the 'open with' procedure to get .py files to always open with spyder, but I get this error:

Fatal Error in Launcher
Unable to create process using
'"c:\ci\spyder_1549989126116\_h_env\pythonw.exe"
"C:\Users\D\Anaconda3\Scripts\spyder3.exe"
"C:\Users\D\mycode.py"'

A screenshot of the error message is attached.
![capture](https://user-images.githubusercontent.com/10007964/53632472-5b954600-3c15-11e9-88b7-e56146bbea91.PNG)

### What steps reproduce the problem?

1. Right-click on a .py file
2.  Navigate to 'Open With' -> 'Choose Another App' -> 'Look for another app on this PC' -> Navigate to C:\Users\D\Anaconda3\Scripts\spyder3.exe

### What is the expected output? What do you see instead?
I would expect Spyder to launch and open the .py file in the console. Instead, the "Fatal Error in Launcher" message presents itself for a few seconds before disappearing and Spyder does not launch at all.

### Paste Traceback/Error Below (if applicable)
N/A

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.0 64-bit
* Qt version: 5.9.3
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.1.1 (OK)

```

**Comment by ccordoba12** [comment]
> I am unable to open .py files in Spyder by double-clicking on them

That's something that needs to be solved in Anaconda, it can't be solved here sorry.

**Comment by ItimadFang** [comment]
> > I am unable to open .py files in Spyder by double-clicking on them
> 
> That's something that needs to be solved in Anaconda, it can't be solved here sorry.

Tips on where to go for help solving this in Anaconda?
