### ISSUE TITLE
Ctrl-Shfit-I not working from separate editor window

### ISSUE THREAD

**Issue by dstrozzi** [spyder-ide/spyder#8871]
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ X] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I start Spyder 3.3.3 on a Windows 10 machine, Anaconda distribution, Python 3.7.1.  I have one Spyder window, with ipython in one panel, editor in another.  From editor, C-S-I switches to ipython console.  Good.  I right-click on the editor tab, do "New Window", switch to that window.  C-S-I does nothing.  Bad.

**Comment by ccordoba12** [comment]
We're aware of this problem but we don't have a solution for it yet.
