### ISSUE TITLE
Uninstalling Anaconda leaves traces that prevent a new clean installation in windows 10-64

### ISSUE THREAD

**Issue by titobr** [spyder-ide/spyder#8872]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Good day all.
I have been using Anaconda Spyder successfully for about a year. About 3 weeks ago I started using the PyQt5 GUIs and at point, my Spyder and Anaconda Navigator IDE broke (they won’t lunch). I searched this web site and others to find a solution but nothing worked. I decided to completely uninstall Anaconda using the windows uninstaller, deleted all the .conda and  .python files that I could find and that the uninstaller did not deleate, cleaned the registers using the CCleaner software, rebooted the computer, downloaded the latest Anaconda installer, and the problem remains the same. Spyder or Anaconda will not lunch.
Things that I have tried are:
Spyper –reset
Uninstall SIP and PyQt5 and the reinstalling them using the conda install (package) --just in case  that they are corrupted.
Conda install py pyqt
Python lunches fine when called from the CMD prompt, but when I execute spyder or Anaconda-Navegator, it does nothing but return a command prompt.
This happens in a windows 10-64, Python 3.7.1,  and whatever the latest version of Anaconda is as of 3/1/2019.
I am at a complete lost. 
My question would be: How to completely clean the Anaconda installation from my windows 10-64 computer, so that I can install a new, clean Anaconda. –Assuming that the problem doesn’t come from Anaconda itself, this should always work.
Any help would be tremendously appreciated.

### What steps reproduce the problem?

1. Attempts to lunch Spyder fails with no errors
2. Attempts to lunch Anaconda Navigator fails. –no errors
3. Python works when executed from the Command prompt

### What is the expected output? What do you see instead?

After a complete uninstall and reinstall of Anaconda, Everything should work as it did before

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  Latest version as of 3/1/2019 (from site)
* Python version:  3.7.1
* Qt version: Latest version as of 3/1/2019 (from site)
* PyQt version: Latest version as of 3/1/2019 (from site)
* Operating System name/version: Windows 10-64

### Dependencies

```Can't go to help menu. as it will no longer launch
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> About 3 weeks ago I started using the PyQt5 GUIs and at point, my Spyder and Anaconda Navigator IDE broke (they won’t lunch)

That's because the PyQt5 packages from Anaconda and those you can install with pip are incompatible.

By using pip you corrupted your Anaconda installation and now the only solution is your to uninstall Anaconda and reinstall it again.

Note: I think you can use pip after creating a conda environment (just google how to do that), but I'm not really sure. You should try that after reinstall Anaconda, just in case that doens't work because it'll force you to reinstall Anaconda again.

**Comment by titobr** [comment]
Carlos, thank you for your answer. I have already done what you subjected.
Completely uninstalled Anaconda from my computer, cleaned any files that
were not automatically deleated by the uninstaller, downloaded the newest
package directly from Anaconda and then reinstalling. This produces the
same problem right out of the box. -The new installation fails from the
start. This leads me to believe that either uninstalling Anaconda leaves
traces in the computer, or that the packages from the Anaconda itself are
corrupted. I  tend to believe my first assumption.

My original question was “How to completely clean Anaconda from my computer
so that I can install a brand new version of Anaconda and have it work
correctly right out of the package.

Thanks for your help again.

**Comment by ccordoba12** [comment]
After installing Anaconda, please update Python with

    conda update python

That should fix your problem. That's the only additional advice I have to give you, sorry.

**Comment by titobr** [comment]
It tell me that “All requested packages already installed”, but  Still no lunch. :=(

**Comment by fpertille** [comment]
Please, did you solve this problem? I have exactly the same.

I removed Anaconda 64 bit and when installing again no error was visible in the installation process. In fact, the installation was incompleted.
I partially solved this problem by installing the 32 bit version. But as I needed version 64, it was not worth to me!
Please, help! How to completely clean Anaconda from my computer!!!

**Comment by xutkarshjain** [comment]
@titobr thanks for your solution. i am also facing same issue with spyder. so i am just going to reinstall anaconda.
Now my doubt is that, should i need to search all directories for removing .py files. when i used to save my python files in separate disk (D).
-> should i have to remove python-notebook files too ??
-> what if i just remove anaconda folder manually because i use various IDE (like: PyCharm, Idle) that may contain .py files also.

**Comment by pauelm** [comment]
The Anaconda installation is notorious at being a hot mess.  Even if you get packages working correctly, it is inevitable that you will run into problems all over again, when you use pip to install new packages, as Anaconda and pip will continue clobbering each other.  Unfortunately, the only way to avoid the broken, corrupt installs / uninstalls is to avoid Anaconda all together, and pip install only the packages that you need.  Having many packages to install can be a pain, but you can also script it out.  This way, not only you avoid Anaconda creating conflicts with pip, but you also avoid bloatware.
