### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by ChangChunHe** [spyder-ide/spyder#8876]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

cannot exhibit data when click varirables in my Variable explorer

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder
