### ISSUE TITLE
Font size menus

### ISSUE THREAD

**Issue by FastFooties** [spyder-ide/spyder#8882]
### What steps will reproduce the problem?

I start Spyder and all the font size of the menu's is normal looking. When I take my laptop from the docking station, the font size of the menu's (like the tabs of the different scripts) is off. When I put the laptop back in the dockingstation the font size remains larger than normal. Even after restarting Spyder the font size remains larger than normal.

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.6.7
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  1.6.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.4 (OK)
rope >=0.9.4      :  0.10.7 (OK)
jedi >=0.11.0     :  0.12.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.0 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  6.4.0 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
pylint >=0.25     :  1.8.4 (OK)
```

**Comment by ccordoba12** [comment]
> When I take my laptop from the docking station, the font size of the menu's (like the tabs of the different scripts) is off

What do you mean by "off"?

> When I put the laptop back in the dockingstation the font size remains larger than normal.

I think you need to adapt the scaling factor of your screen by going to

    Tools > Preferences > General > Screen resolution

and set a value there that works for you.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
