### ISSUE TITLE
Can't view large np array in Spyder

### ISSUE THREAD

**Issue by catruck** [spyder-ide/spyder#8884]
Hello,

Dep is:
numpy : 1.16.2
spyder : Beta

Problem: 
Small array can be interpreted , but when I try to see one larger array I get error.

![arr_problem](https://user-images.githubusercontent.com/25405157/53795596-f86c2200-3f3a-11e9-98b6-1e208d2020b2.PNG)

How to solve this issue?
Thanks

**Comment by ccordoba12** [comment]
Please report the error using the form that we provide for you (i.e. the third window from to right in your screenshot above).

Just fill in the required details and send it again by providing your Github credentials (they'll be asked after you press the "Submit to Github" button on the bottom).

**Comment by catruck** [comment]
done,
thanks
https://github.com/spyder-ide/spyder/issues/8885#issue-417212092
