### ISSUE TITLE
Can not import opencv

### ISSUE THREAD

**Issue by breyner-posso** [spyder-ide/spyder#8886]
### What steps will reproduce the problem?

import cv2

# When I try to import opencv I get an error message

## Versions

* Spyder version: 3.3.3 
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-45-generic

### Dependencies

```
IPython >=4.0     :  7.3.0 (OK)
cython >=0.21     :  0.29.5 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
psutil >=0.3      :  5.5.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by breyner-posso** [comment]
This is the error message:

ImportError: /opt/ros/kinetic/lib/python2.7/dist-packages/cv2.so: undefined symbol: PyCObject_Type

**Comment by ccordoba12** [comment]
Please read our guide about how to solve this problem:

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

**Comment by ccordoba12** [comment]
You're probably mixing Anaconda packages and the packages from `/opt/ros/kinetic`?
