### ISSUE TITLE
"Kernel died, restarting" everytime the session.run([], {input:value}) function from onnx runtime is called

### ISSUE THREAD

**Issue by mahdouch550** [spyder-ide/spyder#8890]
I have an ONNX object detection model from CNTK. I create a session instance using the onnxruntime.InferenceSession(onnxModelFilePath), I set the input as described. The problem is when I call the session.run([], {input:value}) function to save the result, I get the "Kernel died, restarting" error message. I tried it with Spyder, Jupyter, and Powershell, I keep getting the same error message. Any help would be appreciated. Apologies for any inaccuracy.

**Comment by ccordoba12** [comment]
> I tried it with Spyder, Jupyter, and Powershell, I keep getting the same error message

Then this is not a Spyder internal problem but a problem with CNTK or your code. Hence we can't help you because this place is only to help users with Spyder bugs, sorry.
