### ISSUE TITLE
XmbTextListToTextProperty result code -2 message is printed to the Terminal

### ISSUE THREAD

**Issue by pinikop** [spyder-ide/spyder#8901]
## Problem Description
When lunching Spyder from the Terminal the following message is printed to the Terminal:  

XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2
XmbTextListToTextProperty result code -2

Hovering with the mouse cursor over the menus also print these lines to the Terminal.  

### What steps reproduce the problem?

1. Lunching Spyder

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.1 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04.2

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.8 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
It seems this is not a problem with Spyder but with your Linux distro. See for example:

https://forum.manjaro.org/t/getting-error-xmbtextlisttotextproperty-result-code-2-when-running-qt-examples/24879/10

Hope that helps.
