### ISSUE TITLE
Wrong display in Spyder3 icons

### ISSUE THREAD

**Issue by beows** [spyder-ide/spyder#8903]
### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
After installing Spyder 3 with pip it seems to run fine but the icons don't display correctly. They are shown like with wrong definition. If you press them the functions work but they don't show the correct look. I attach a screenshot to the end.

### What steps reproduce the problem?
It happens always that I run Spyder 3 from scratch and I have tried to reset all the preferences to default values and other choices but have not been able to solve it. It is not dramatic because the icons and everything seem to work but it is annoying and I cannot figure out what I'm missing or I did wrong.

### What is the expected output? What do you see instead?
I would expect to have a good display of the icons and the rest of the window parts.

### Paste Traceback/Error Below (if applicable)

```python-traceback



```

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.2 64 bit
* Qt version: 5.12.1
* PyQt version: 5.12
* Operating System name/version: MacOS High Sierra 10.13.6

### Dependencies

```
IPython >=4.0     :  7.3.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
psutil >=0.3      :  5.6.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
```
![spyder3_wrong_display](https://user-images.githubusercontent.com/48319588/53992879-2feef000-412e-11e9-9514-11178c5722e2.jpg)

**Comment by ccordoba12** [comment]
Please run

    pip install -U qtawesome

to fix this.

**Comment by beows** [comment]
Fantastic! Thanks a lot!
