### ISSUE TITLE
Script won't run

### ISSUE THREAD

**Issue by csrubin** [spyder-ide/spyder#8905]
### What steps will reproduce the problem?

Import pyautogui

pyautogui.moveTo(100,100,duration=0.25)
Click green arrow to run. 

runfile(<filepath>) shows in console but nothing happens.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.6.8
* Qt version: 5.11.1
* PyQt5 version: 5.11.2
* Operating System: Darwin 18.2.0

### Dependencies

```
pyflakes >=0.6.0  :  1.5.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.5.6 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
psutil >=0.3      :  5.2.2 (OK)
nbconvert >=4.0   :  5.1.1 (OK)
pandas >=0.13.1   :  0.20.1 (OK)
numpy >=1.7       :  1.12.1 (OK)
sympy >=0.7.3     :  1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
IPython >=4.0     :  5.3.0 (OK)
matplotlib >=2.0.0:  2.0.2 (OK)
pylint >=0.25     :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
Please see

https://github.com/spyder-ide/spyder/wiki/How-to-run-PyQt-applications-within-Spyder

That could help in this case too.

**Comment by ccordoba12** [comment]
Closing due to lack of response.
