### ISSUE TITLE
IPython console error: "An error occurred while starting the kernel"

### ISSUE THREAD

**Issue by renan-ms** [spyder-ide/spyder#8919]
Could anybody help me with this error? Thanks in advance.

While running my code in Spyder 3.3.2 for hours, the following error has come out:

![Spyder_Kernel_Error](https://user-images.githubusercontent.com/41458949/54125045-b16ea880-43e2-11e9-8576-694e1490ce09.png)

![spyder_version](https://user-images.githubusercontent.com/41458949/54125064-c0555b00-43e2-11e9-8f4d-e72e352e2cc2.png)

Translating to english: An error occcured while starting the kernel b' '
@ccordoba12

**Comment by ccordoba12** [comment]
Please update to 3.3.3, which fixed this problem.
