### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Dylanbron** [spyder-ide/spyder#8924]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
i can't connect to the remote machine using the .json file and inputting the ip and port number

**Comment by ccordoba12** [comment]
Please see this

https://docs.spyder-ide.org/ipythonconsole.html#connect-to-an-external-kernel

and this

https://github.com/spyder-ide/spyder-docs/issues/95
