### ISSUE TITLE
error

### ISSUE THREAD

**Issue by gowthamraj96** [spyder-ide/spyder#8925]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\base_frontend_mixin.py", line 163, in _dispatch
    handler(msg)
  File "C:\ProgramData\Anaconda3\lib\site-packages\qtconsole\rich_jupyter_widget.py", line 169, in _handle_display_data
    png = decodestring(data['image/png'].encode('ascii'))
  File "C:\ProgramData\Anaconda3\lib\base64.py", line 561, in decodestring
    return decodebytes(s)
  File "C:\ProgramData\Anaconda3\lib\base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
I

**Comment by ccordoba12** [comment]
Please update qtconsole by opening the Anaconda Prompt and running there

    conda update qtconsole

to fix this error.
