### ISSUE TITLE
Single click to interact with items in Project Explorer, rather than double-click

### ISSUE THREAD

**Issue by dbouchard3** [spyder-ide/spyder#8930]
I've recently switched from VSCode to Spyder and a minor annoyance for me is that in Spyder I have to double-click to interact with items in the Project Explorer. By "interact", I mean open and closing folders and opening documents.

In VSCode, you only have to single-click and, even though it might seem like hardly any difference, I think single-clicking is a better user experience.

**Comment by ccordoba12** [comment]
Thanks for the suggestion. We'll try to address this for Spyder 4.

**Comment by domokane** [comment]
I don't even get double-click to open files. Something is broken. Any ideas ?
