### ISSUE TITLE
Unable to launch spyder

### ISSUE THREAD

**Issue by schirama** [spyder-ide/spyder#8940]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When opening Spyder on my windows 10 computer, I get an error message that "Spyder crashed during last session" and does not start at all.

### What steps reproduce the problem?

1. Opening it through Windows start menu -> spyder icon
2. Opening it through Anaconda Navigator application -> "launch" spyder
3. Opening it through Anaconda Command Prompt -> "spyder" 

### What is the expected output? What do you see instead?
I am expecting to see the spyder IDE open but this is what pops up instead:
![image](https://user-images.githubusercontent.com/48530262/54322130-5bf4f000-45ca-11e9-99cf-f3ef2e312c51.png)

### Paste Traceback/Error Below (if applicable)

![image](https://user-images.githubusercontent.com/48530262/54322153-762ece00-45ca-11e9-874b-3883f7ba0892.png)

## Versions

* Spyder version: 3.3.2
* Python version: 3.7.1
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

I really appreciate any and all help on this. It is for a college computer science project that is due very soon. If this is an issue that has already been answered before, please link the page where I can find the original post. Thank you so much!

**Comment by bcolsen** [comment]
You can just rename or delete the file `history.py` in your spyder configuration directory.

If that doesn't work then running:

`spyder --reset`

in the Anaconda Prompt should work

This was previously reported in #3376 but it looks like this can still pop up.

**Comment by schirama** [comment]
The `spyder --reset` command fixed the issue. Thank you for your help!
