### ISSUE TITLE
nbconvert is reported as a missing dependency

### ISSUE THREAD

**Issue by al3xsh** [spyder-ide/spyder#8941]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When I start spyder I get a message that I have missing dependencies:

nbconvert >=4.0: None (NOK)

despite having version 5.3.1 installed (via conda)

### What steps reproduce the problem?

1. conda create --name test python=3.7 && conda activate test
2. conda install spyder
3. spyder

### What is the expected output? What do you see instead?

Expected output is no error.

What I see is:

![sypder-nbconvert-error](https://user-images.githubusercontent.com/10220372/54345258-9ac28e80-463a-11e9-8261-23961809929a.png)

## Versions

* Spyder version: 3.3.3
* Python version: 3.7
* Qt version: 5.9.7-h5867ecd_1
* PyQt version: 5.9.2-py37h05f1152_2
* Operating System name/version: Ubuntu 18.04

**Comment by al3xsh** [comment]
Although nbconvert is installed (and everything was installed on a completely fresh version of Anaconda), when I open python and try to import nbconvert I get:

```
>>> import nbconvert
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/code/development_tools/anaconda3/envs/test/lib/python3.7/site-packages/nbconvert/__init__.py", line 7, in <module>
    from . import postprocessors
  File "/home/alex/code/development_tools/anaconda3/envs/test/lib/python3.7/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
    from .serve import ServePostProcessor
  File "/home/alex/code/development_tools/anaconda3/envs/test/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
    class ProxyHandler(web.RequestHandler):
  File "/home/alex/code/development_tools/anaconda3/envs/test/lib/python3.7/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
    @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```

Do you think this could be the issue?

Regards,

Alex

**Comment by ccordoba12** [comment]
Thanks for reporting. This is an issue with the nbconvert conda packages.

**Comment by ccordoba12** [comment]
Pinging @jjhelmus about this one. @jjhelmus, it seems you need to unpin `pandoc` in the `nbconvert` recipe to make conda install the latest nbconvert, which is the one compatible with the latest tornado.

See

https://github.com/conda-forge/nbconvert-feedstock/issues/27
https://github.com/conda-forge/nbconvert-feedstock/pull/28

**Comment by al3xsh** [comment]
Thanks,

Running `conda install nbconvert` upgraded nbconvert to 5.4.1 and the error went away!

Regards,

Alex

**Comment by jjhelmus** [comment]
@ccordoba12 A new build of `nbconvert` 5.4.1 is available in `defaults` that unpins the `pandoc` dependency.

**Comment by ccordoba12** [comment]
Thanks a lot @jjhelmus!

**Comment by NaderNazemi** [comment]
Please help, I tried installing nbconvert using conda, but it fails by saying "requests" is a dependency and and cannot be removed. 
This all started when I downgraded "tornado" to an older version. 
Also when I type "conda list", I am getting an error.

**Comment by ngayraud** [comment]
Still doing this for me today, after installing the new spyder version through conda. I am getting the `AttributeError: module 'tornado.web' has no attribute 'asynchronous'` error. Any ideas?

**Comment by SamProspa** [comment]
> Thanks,
> 
> Running `conda install nbconvert` upgraded nbconvert to 5.4.1 and the error went away!
> 
> Regards,
> 
> Alex

Me too, This method worked well. 

Thanks for sharing

**Comment by aysebilgegunduz** [comment]
I still got error and `conda install nbconvert` returns with following error:
`Traceback (most recent call last):
    File "C:\Users\uname\Anaconda3\lib\site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 580, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'`

**Comment by ccordoba12** [comment]
Hey @aysebilgegunduz, it seems your Anaconda installation is broken. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to remove it and reinstall it again.

**Comment by aysebilgegunduz** [comment]
> Hey @aysebilgegunduz, it seems your Anaconda installation is broken. Please see [our video](https://www.youtube.com/watch?v=Ul79ihg41Rs) to learn how to remove it and reinstall it again.

Yes, thank you I reinstalled it.

**Comment by dkobayas-cyber** [comment]
I have the same issue about the missing dependency of nbconvert. I ran `conda install nbconvert` on the Anaconda Powershell Prompt, but it says that all the requested packages are already installed. Is there any other workaround?

 Versions
- Spyder: 5.4.3
- Python: 3.8.18
- Operating System: Windows 10

Note that `import nbconvert` gives me long lines of error messages like below. I think it is related to the problem, but I'm sure how to fix it, since the latest nbconvert is already installed. 
```
>>> import nbconvert
Traceback (most recent call last):
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\nbconvert\filters\markdown_mistune.py", line 25, in <module>
    from mistune import (  # type:ignore[attr-defined]
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\mistune\__init__.py", line 4, in <module>
    from .renderers import AstRenderer, HTMLRenderer
ImportError: cannot import name 'AstRenderer' from 'mistune.renderers' (C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\mistune\renderers\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\nbconvert\__init__.py", line 7, in <module>
    from .exporters import (
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\nbconvert\exporters\__init__.py", line 4, in <module>
    from .html import HTMLExporter
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\nbconvert\exporters\html.py", line 29, in <module>
    from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\nbconvert\filters\markdown_mistune.py", line 40, in <module>
    from mistune import (  # type: ignore[attr-defined]
  File "C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\mistune\__init__.py", line 4, in <module>
    from .renderers import AstRenderer, HTMLRenderer
ImportError: cannot import name 'AstRenderer' from 'mistune.renderers' (C:\Users\Daigo\anaconda3\envs\env_SLAM\lib\site-packages\mistune\renderers\__init__.py)
```

**Comment by ccordoba12** [comment]
@dkobayas-cyber, you can try to run

    conda update mistune

to see if that helps.
