### ISSUE TITLE
pandas_datareader not installed

### ISSUE THREAD

**Issue by brooksr1** [spyder-ide/spyder#8958]
### What steps will reproduce the problem?

import pandas_datareader
gives error No module named 'pandas_datareader'
this is Windows 10 and Python 3.7

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is not a Spyder problem but we wrote this guide

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to help users with this kind of problem.

**Comment by brooksr1** [comment]
Thank you, Carlos.  I will work on this later today.

 

Brooks

**Comment by brooksr1** [comment]
I tried to follow the guide, but I have no idea what environment the package was installed with.  I think pandas was installed when Anaconda was installed.  I think pandas_datareader was supposed to be installed with it.

 

Please advise.

 

Brooks

 

This happens because foo was installed (with either conda or pip) in a different conda or venv/virtualenv environment than the one in which Spyder is currently running.

To confirm this is the problem, you need to:

1.	Activate the environment (e.g. myenv) in which you installed the package
