### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by lifeislong** [spyder-ide/spyder#8975]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
![image](https://user-images.githubusercontent.com/28038669/54569172-cff12700-4a14-11e9-9ea9-251ff16dcb51.png)

**Comment by ccordoba12** [comment]
Please update Spyder to its latest version (3.3.3) and try again. I think we fixed this problem already.

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by lifeislong** [comment]
> 
> 
> Please update Spyder to its latest version (3.3.3) and try again. I think we fixed this problem already.

3.3.3 works well! Thanks for your effort! 牛逼
