### ISSUE TITLE
AutoRotateScreen

### ISSUE THREAD

**Issue by NicHack17** [spyder-ide/spyder#8981]
### What steps will reproduce the problem?

When I open Spyder from Anaconda Navigator, the automatic rotation of my laptop screen is disabled. This phenomenon only occurs when the Spyder window is active.  Could you solve this problem?

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Sorry, we don't have the means to do it because we don't have those kind of laptops.
