### ISSUE TITLE
Anaconda nAVIGATOR FAILS TO LAUNCH ANY PLATFORM

### ISSUE THREAD

**Issue by sandippurnapatra** [spyder-ide/spyder#8983]
### What steps will reproduce the problem?

I am Using Windows 10 Pro. I have installed Anaconda Navigator successfully. It is opening alright but I am unable to launch any application from it. I see it tries to launch but nothing happens.

Please let me know how I can solve the issue with Windows PowerShell as I am unable to launch Windows Command Prompt.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10 Pro

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with Anaconda. Please report it here

https://github.com/ContinuumIO/anaconda-issues/issues/
