### ISSUE TITLE
Update PyQt requirement to 5.12.1 

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder#8987]
in spyder `3.3.4` update PyQt requirement to newer PyQt version 

```
spyder 3.3.3 has requirement pyqt5<=5.12; python_version >= "3", but you'll have pyqt5 5.12.1 which is incompatible.
```

**Comment by ccordoba12** [comment]
This is already done:

https://github.com/spyder-ide/spyder/blob/3.x/setup.py#L247

I'll release 3.3.4 tomorrow to fix this problem.

**Comment by remiDEGUI** [comment]
Hello,
Is the issue of compatibility between spyder3.3.4 ans pyqt5.12 really solved ? 
I had to downgrade pyqt5.12 to 5.11 to launch spyder.

**Comment by danieltomasz** [comment]
try to update `Spyder` to 3.3.4, it works for  me
