### ISSUE TITLE
Run cell (ctrl+Enter) don't work in Spyder inatalled with the Anaconda

### ISSUE THREAD

**Issue by danidean** [spyder-ide/spyder#8994]
### Issue Report Checklist

*  Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
*Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* Tried basic troubleshooting (if a bug/error)
    * Restarted Spyder
    * Reset preferences with ``spyder --reset``
    * Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * Tried the other applicable steps from the Troubleshooting Guide
*  Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Executing the "run cell" (ctrl + enter) on code in the Spyder editor produces no response/output in the console. The same with the "print" command appearing in the code - no output displayed in the console. 

### What steps reproduce the problem?

1. Using the "ctrl + enter" command on relevant code in the editor.
2. print() seems not to work.
3. Only when copying the code from 1 and 2 into the console command prompt I get the relevant  results.

### What is the expected output? What do you see instead?
Nothing is produced

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.2
* Python version: 3.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: 
win 10 pro
### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Did you create a cell with a comment of the form `#%%` before pressing `Ctrl+Enter`?

**Comment by ccordoba12** [comment]
Closing due to lack of response.

**Comment by AfzalivE** [comment]
> Did you create a cell with a comment of the form `#%%` before pressing `Ctrl+Enter`?

This didn't use to be a requirement, right? Is this the only way to run individual lines now?

**Comment by ccordoba12** [comment]
No, individual lines are run with `F9`.

**Comment by AfzalivE** [comment]
Lol. Yeah, sorry. Got rusty and forgot about it.

**Comment by yiorgosn** [comment]
In the event you are still reading this thread.  The Spyder 4.0 IDE is fantastic, thank you.  If you could someday let users switch the F9 functionality to running cells and control-Enter to execute a line or selection, that would be great.   I am automatically used to testing lines with control-Enter and the #%% is just not as convenient or visually inviting with the Spyder Dark Theme.

Thank you again for a great product.

**Comment by le0x99** [comment]
@yiorgosn How can i used ctrl+enter to run certain lines in spyder4? It gets somehow converted into a "runcell" command, which does not work...

**Comment by yiorgosn** [comment]
Currently the only way to do it with Spyder 4.0 is to place #%% before 
and after the line or lines you wish to execute.  Then just press 
control - enter by having your cursor inside the designated section 
(between the 2 #%%).

------ Original Message ------

**Comment by ccordoba12** [comment]
@yiorgosn, if swapping F9 and Ctri+Enter default behaviors is not working for you, that's a bug that we need to fix. Please open a new issue about it so we don't forget to take a look at it in the future.

**Comment by le0x99** [comment]
@yiorgosn You can just change the shortcuts in the settings !! Spyder 4 ftw

**Comment by yiorgosn** [comment]
I am just new here and made a rookie mistake, sorry for the trouble, it 
was but a simple fix.

Tools -> Preferences - Keyboard Shortcuts

Thanks again!  I absolutely love Spyder 4.0!


------ Original Message ------

**Comment by yiorgosn** [comment]
Yes indeed just go to :

Tools -> Preferences - Keyboard Shortcuts

And change the functionality of F9 and control - enter.

Thanks!

**Comment by mayurpande** [comment]
Hi I just came across this as I was having difficulty running a cell block. I am able to run a cell block using `#%%` before and after, not sure why we have to do this, but at least it works. But now it won't let me run a block of code without indenting everything backwards! Is this going to be fixed in the future? Otherwise I might have to back to spyder3. Thanks

**Comment by aqifilyaskhan** [comment]
finally i found a solution, what a headache it was
i stopped using spyder because i thought it got corrupted

**Comment by MadDenker** [comment]
I do not see how this is fixed.  Changing the shortcut in settings doesn't change the behavior.  I still cannot highlight rows and run that cell.  How can that behavior be brought back?

**Comment by oneforall-shared** [comment]
![2020-03-20_234934](https://user-images.githubusercontent.com/59865318/77194189-7dee5000-6b05-11ea-914d-9e8a29642089.jpg)

I got the same issue but resolved it using F9. instead of using "ctrl+enter"  use 'F9' to execute a single line or a block of code.

![ddd](https://user-images.githubusercontent.com/59865318/77194343-cb6abd00-6b05-11ea-8230-b5c266a1d695.jpg)

**Comment by jatiniitr** [comment]
I am also facing the same issue. Run line is not working, the consloe says :
"runcell(0, '/Users/jatin.dixit/untitled0.py')" but entire code gets executed.

**Comment by SandreL** [comment]
Any update on this? Can't queue cells or blocks of code

**Comment by ccordoba12** [comment]
> Can't queue cells or blocks of code

That functionality was removed a couple of years ago and it'll come back in Spyder 4.2 or 5, we're still thinking about it.

**Comment by paulogcsouza** [comment]
I am using F9 for this function. it's working well

**Comment by likitha718** [comment]
In Spyder 3.7, Select the desired lines of Code -> -> press (Fn + F9) which works just like (Ctrl + Enter) in Spyder 3.6.

**Comment by byersiiasa** [comment]
I'm experiencing an issue in Spyder 4, freshly installed, that Ctrl+Enter starts to execute the whole script (e.g. liek F5), and not the cell.
I have checked keyboard shortcuts and have cells split by #%%
Anyone else get this?

**Comment by dalthviz** [comment]
Hi @byersiiasa could you provide a GIF to understands the behavior you're experiencing (or maybe a reproducible example)? I tested on Windows and the shortcut seems like it's working:

![cells](https://user-images.githubusercontent.com/16781833/86259149-4752b780-bb81-11ea-933b-8e2c04578ec8.gif)

If you keep experiencing an issue maybe it could be worthy to open a new issue where you add more info about your setup (i.e OS, specific version, etc.) and the GIF or steps to reproduce the issue you're facing :)

**Comment by byersiiasa** [comment]
thanks @dalthviz will try a MWE
whats the cool gif app you used that shows the keys?

**Comment by dalthviz** [comment]
Awesome @byersiiasa :) About the apps: to record the GIF I used [LICECap](https://github.com/justinfrankel/licecap) and to show the keystrokes I used [Carnac](https://github.com/Code52/carnac)

**Comment by byersiiasa** [comment]
sorry to say - that I did a classic "power cycle" - and my issue disappeared... thanks though!

**Comment by dalthviz** [comment]
No problem @byersiiasa glad you figure it out!

**Comment by Atulsingh92** [comment]
Hi, 
Sorry to ping to an old issue. 
My problem is that ctrl+enter, doesn't end, such that console moves from `In [1] to In [2]` .
This is for spyder- 5.4.0 and python 3.8, with spyder-kernels 2.4.3.

Could you give any pointers to fix this?

**Comment by ccordoba12** [comment]
@Atulsingh92, could you post a simple code example that's giving you that problem? That way we could test it on our side to understand what's happening in your case.
