### ISSUE TITLE
UI Clean up - EPIC

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9004]
- [ ] Add options to increase/decrease icon size in toolbars.

**Comment by jnsebgosselin** [comment]
@goanpeca I think I can take care of the toolbar icon size option if you want.

**Comment by ccordoba12** [comment]
Please do @jnsebgosselin. We're busy with other things right now.

**Comment by dalthviz** [comment]
Superseded by https://github.com/spyder-ide/spyder/issues/9413
