### ISSUE TITLE
Shorten status bar widgets size

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9006]
Currently, the status bar is crowded because we use too much space for the status widgets.

We could gain some space and clean up things, much like VSCode does.

<img width="1440" alt="Screen Shot 2019-03-22 at 11 53 31" src="https://user-images.githubusercontent.com/3627835/54839572-21114d00-4c99-11e9-944f-75f9b203e8f6.png">

<img width="1440" alt="Screen Shot 2019-03-22 at 12 18 30" src="https://user-images.githubusercontent.com/3627835/54841148-a21e1380-4c9c-11e9-93fa-1951b8f96509.png">

**Comment by ccordoba12** [comment]
That's because we show messages in the status bar, which are mostly are the tooltips from entries in several menus.

How should we handle that?

**Comment by goanpeca** [comment]
See the screenshot above (I am talking about the status widgets in spyder to the right), the branch and the conda env is another issue ;-)

**Comment by ccordoba12** [comment]
I see, ok.

> (Separate issue: the status bar for the dark style seems to be not working as expected on OSX)

Yep, could you take care of that?

**Comment by goanpeca** [comment]
>Yep, could you take care of that?

Yep :-)
