### ISSUE TITLE
bug in the icons

### ISSUE THREAD

**Issue by lucasunu** [spyder-ide/spyder#9012]
### What steps will reproduce the problem?

the icons are weird, instead of appearing certain images appears completely erased images

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.2
* Qt version: 5.12.1
* PyQt5 version: 5.12
* Operating System: Linux 4.19.30-1-MANJARO

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.0 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed by updating to the latest version of QtAwesome (0.5.7)
