### ISSUE TITLE
Merge documentation and Spyder's website

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#903]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-01-04T09:48:53Z_

We have to take action on this because it's not a good solution to have both websites:
- maintaining both documentation and the GoogleCode website is painful
- having both websites is confusing for users (see for example: https://groups.google.com/d/msg/spyderlib/YyF6cJQD-Yo/8UiGwBGUYq8J )

Maybe putting all the GoogleCode wiki pages into the documentation hosted at packages.python.org would be a good solution:
- this would be better for visibility as this is the top website when googling 'spyder python'
- all the documentation will be in the main source repository (makes it easier to write both doc and code)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=903_

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2012-01-07T06:17:07Z_

I think we could merge docs and website in a single Sphinx tree without too much trouble. I totally agree this will be beneficial for the project but it will require a fair amount of work. I can't set a deadline for sure, but I'll try to have this ready in about a month.

The only drawback I see is that the size of the main source repo will be increased as we had to add all images that are now hosted in the wiki repo. And the source repo is a bit heavy right now (~22 Mb).

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2014-08-25T01:48:27Z_

Now that the site has been moved to bitbucket, there are some things that could be done. 

Website
\-------
I believe that we could use different tools to make the experience as smooth as possible (a tool for a specific purpose) and try to have this integrated through a self contained website that points to the correct places and serves as entry point for any google search. From here visitors would be pointed to documentation, development, tutorials, blogs etc...

Another Option would be to take advantage of github pages so the webpage could be hosted there.

I am thinking in the lines of http://www.scrapy.org , in terms of how it points to different locations and already has the Fork me ribbon which I find quite nice :). I do not use scrapy as an example of aesthetics!

We could acquire a domain in the lines of
www.spyder-ide.org


Documentation
\-------------
I think https://readthedocs.org/ might offer some great enhancements to the current documentation workflow (actually not sure how it is done now)... taken from their site

""Read the Docs hosts documentation, making it fully searchable and easy to find. You can import your docs using any major version control system, including Mercurial, Git, Subversion, and Bazaar. We support webhooks so your docs get built when you commit code. There's also support for versioning so you can build docs from tags and branches of your code in your repository. A full list of features is available.""

Wiki
\----
Now that code is hosted at bitbucket the wiki over there should be used as documentation for developers giving as much help as it is needed for newbies, defining a clear roadmap, FAQ, etc...

Social Media
\------------
This would be indeed a big effort, but the idea here is to increase even more the visibility of Spyder. This can include different fronts

-Twitter: Basically 
-Facebook
-Google+ Google pages
-Youtube/Vimeo: I have a plan to start making short video tutorials in the usage of the different aspects of spyder, but as a starting point we could start making the channels and building the infrastructure

I will not have time to spare on this until perhaps the start of 2015 as I am still working on some PR's

Google Code
\-----------
Nothing against google code, but when issues are moved to bitbucket, the wiki is decommissioned and a brand new webpage is created for Spyder, I do not longer see any need for it, but then again, this is just me.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2014-08-25T02:09:24Z_

Sphinx layout is used overused and so many people fail to do anything distinguished out of it that I don't think at all that it is a good idea to switch to it - I'd personally think twice before jumping in. Spyder site currently has a message that there people who can think and implement something new and original, not a bunch of crazy folks reinventing a bicycle, because they couldn't understand the code of some other editor to patch it.

Github is extremely bad site for people not in its inner circle. Without SSO login it is a disaster. I can't say that Google Code is better, but at least it is not so confusing for people.

\> "Now that code is hosted at bitbucket the wiki over there should be used as documentation for developers giving as much help as it is needed for newbies, defining a clear roadmap, FAQ, etc..."

Wrong, wrong and again wrong. Accessibility, usability and design. These are the factors. Not the location. You can edit pages for GC wiki, but did you? Why do you think that moving it to other location will magically make it full of "as much help as it is needed for newbies, defining a clear roadmap, FAQ, etc.."?

\> "..when issues are moved to bitbucket.."

Do you like Bitbucket tracker more than GC? Why?

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2014-08-25T02:29:57Z_

Wow... that is a lot of unnecessary rage in a comment... 

1.) I just suggested Github pages as a hosting solution 
2.) I cannot edit pages at the wiki and hence no, I did not modify them, but guess what I can edit them over bitbucket and I started with a roadmap. https://bitbucket.org/spyder-ide/spyderlib/wiki/Home 3.) No, relocating everything is not a magic solution and I never intended it to be like that, my concern as a contributor now is to attract people to help in maintaining things, and it helps if most of dev related stuff is in one place, issues wiki repository PR and the rest. Of course if you are motivated enough you can find everything by yourself or by asking in the mailing lists, but this might prevent people from jumping in... spyder already has a large codebase and it can be daunting at first glance.

4.) On "Accessibility, usability and design" is precisely why I suggest making a website for Spyder, which does not have to be attached to google code or bitbucket or github, that is Accessible, Usable and nicely design so that it points where to go.

5.)I have nothing against the google code issue tracker and I can say the same that a page here says 

"...the Google Code issue tracker is more superior, so we plan to use it for the foreseeable future..."

I just think that issue tracking, code hosting, PR should be in the same place to have a better flow. Also I believe the ability to have nested discussions and the inclusion of markdown in issues greatly enhances the communication of ideas between users and developers.

**Comment by spyder-issues-migrator** [comment]
_From [techtonik@gmail.com](https://code.google.com/u/techtonik@gmail.com/) on 2014-08-25T07:10:09Z_

Ahh, sorry.. People keep telling me to abandon this style of criticizing things, but sometimes it just spills out, esp. in stressful conditions. Don't want to hurt anyone, so just don't pay attention at emotional side.

1.) Bitbucket also has this capability, see https://bitbucket.org/techtonik/techtonik.bitbucket.org 2.) @-Carlos, why you don't add wiki edit permissions for all contributors? I even think that "Allow non-members to edit wiki pages" should be turned on https://code.google.com/p/spyderlib/adminWiki 3.) Do you know what a UX discipline is? If you start writing articles about it for Spyder blog with research related to Spyder - it will surely attract more people. Making it possible to commit and review stuff for Spyder from Spyder will definitely help. Moving pages that people who use Spyder will see only once won't help here. Automate and autogenerate as much as possible. Chromium guys are really good at that.

4.) Website edits and updates are not as easy as you might think. Wiki is the easiest thing so far.

5.) The point about flow is good, I support it. So, the missing features - lack of code snippets in issue text, no nested threads - these should be documented. You can also ping Carlos to add linking BB text issue `#111` to GC issues - I see it doesn't work - https://bitbucket.org/spyder-ide/spyderlib/pull-request/68/fix-issue-1812-fix-errors-with-tab/diff

**Comment by spyder-issues-migrator** [comment]
_From [goanp...@gmail.com](https://code.google.com/u/114799823853069473860/) on 2014-08-25T07:29:04Z_

(Well... stop doing comments if you are under stress. If being stressed is a permanent condition, then stop commenting and go do some yoga :)  )

1.) Great, then maybe that should be used 

3.) Nope I am not an expert on UX, I barely know what it is. That is the whole point of having projects and enhancing VC on spyder, having everything close by helps.

4.) Yes they are. And besides we can use a repo to host the site and use something like this. No html needed. http://blog.getpelican.com/ 5.) There are already some scripts that help make this migration from GC to BB. https://answers.atlassian.com/questions/297709/migrating-issues-from-google-code-to-bitbucket

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T17:52:34Z_

**Owner:** goanp...@gmail.com

**Comment by goanpeca** [comment]
Hi @ccordoba12 , I think we can make the milestone for this 2.4 so I can focus on the other pending PRs.

I still have some things to figure out, and I am really considering switching over to [mkdocs](http://www.mkdocs.org/) as it would unify all documentation efforts (The website content, comments in issues and PRs, Wiki pages and documentation of Spyder to a single language, Markdown).

The main advantage of Sphinx is being able to generate automatic documentation from a module by parsing the functions and the docstrings. Spyder by itself will not need this in the foreseeable future so using Sphinx (although favoured by the Python community) would add an extra unneeded layer of complexity.

**Comment by jitseniesen** [comment]
Is this still relevant? It's not clear to me what "documentation" and "website" in this issue's title refers to. I only know http://pythonhosted.org/spyder/ .

**Comment by goanpeca** [comment]
Hi @jitseniesen this was making reference to unifying the information in one place. That development is taking place over https://github.com/spyder-ide/website-spyder so its still relevant although we track issues over there.

**Comment by ccordoba12** [comment]
Since this doesn't belong to here anymore, I'm closing it.
