### ISSUE TITLE
Editor text is all shown in bold text

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9044]
## Problem Description
@goanpeca  PR #9010 introduced a bug where the text in the Editor is all shown in bold.

![image](https://user-images.githubusercontent.com/10170372/55099944-112daa80-5097-11e9-8149-ad2680dc6e30.png)

The problem is due to [this line](https://github.com/spyder-ide/spyder/commit/bc7b90bbdfd23d0800961555815eb24282a35e63#diff-5c40d568fb43c7ea3925c425b0f33a65L35) that was changed for [this line](https://github.com/spyder-ide/spyder/commit/bc7b90bbdfd23d0800961555815eb24282a35e63#diff-5c40d568fb43c7ea3925c425b0f33a65R44).

By changing either `self.text_font = get_font(option='font')` for `self.text_font = get_font(option='rich_font')` or `self.text_font.setBold(True)`  to `self.text_font.setBold(False)`, the problem is resolved.

## Versions

* Spyder version: Spyder 4.0.0.dev0 https://github.com/spyder-ide/spyder/commit/bc7b90bbdfd23d0800961555815eb24282a35e63
* Python version: Python 3.7.1 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
pyls >=0.19.0     :  0.21.5 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by goanpeca** [comment]
Hi @jnsebgosselin for pointing this out! 

Weird... that should have only affected the status bar. Will fix it!

**Comment by jnsebgosselin** [comment]
Btw, doing this:

`self.text_font = QFont(get_font(option='font'))`

store a copy of the font in `self.text_font` and fixes the issue.

**Comment by goanpeca** [comment]
Indeed that solves the issue! Thanks for looking into it :-)
