### ISSUE TITLE
Interactivity testing: canvas.mpl_connect has to be run after each click to have animation update

### ISSUE THREAD

**Issue by patgitacc** [spyder-ide/spyder#9047]
## Description

Event listener has to be run every time a click is made to get an update of the figure.

**What steps will reproduce the problem?**

1. Run the folowing :
import numpy as np
import matplotlib.pyplot as plt
plt.figure()
data = np.random.rand(10)
plt.plot(data)

def onclick(event):
    plt.cla()
    plt.plot(data)
    plt.gca().set_title('Event at pixels {},{} {}and data {}, {}'.format(
        event.x, event.y, '\n', event.xdata, event.ydata))
    
plt.gcf().canvas.mpl_connect('button_press_event', onclick)

2. To have an update of the title, I have to run the last line of code again (F9)

**What is the expected output? What do you see instead?**

The event listener has to be run just once and the figure has to be updated after each click. 

**Please provide any additional information below**

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

**Comment by bcolsen** [comment]
You need to call `plt.pause` to let matplotlib redraw.  This should work:

```python
import numpy as np
import matplotlib.pyplot as plt

plt.figure()
data = np.random.rand(10)
plt.plot(data)

def onclick(event):
    plt.cla()
    plt.plot(data)
    plt.gca().set_title('Event at pixels {},{} {}and data {}, {}'.format(
    event.x, event.y, '\n', event.xdata, event.ydata))
    plt.pause(0.1)

plt.gcf().canvas.mpl_connect('button_press_event', onclick)
```
