### ISSUE TITLE
Variable explorer viewers go to the background on macOS

### ISSUE THREAD

**Issue by lschneidpro** [spyder-ide/spyder#9051]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hi there, using spyder on both windows and mac os, I noticed an odd behaviour compared on Mac OS comapred to the windows version.

On windows, I can easily open and explore different variables at the same time for comparison purpose. On Mac OS, when i open a second variable window, the first one would disapear behind spyder windows.

### What steps reproduce the problem?

1. Create at least two array, dataframe,list....
2. Inspect them with the variables explorer on Mac OS
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: last one
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
@goanpeca, is there something we can do about this?

**Comment by goanpeca** [comment]
Will look into it

**Comment by goanpeca** [comment]
@lschneidpro like this?

![varexp](https://user-images.githubusercontent.com/3627835/55661510-c962fd80-57d1-11e9-8901-10615fb286c2.gif)

**Comment by goanpeca** [comment]
@ccordoba12 should this go to 3.x?

**Comment by lschneidpro** [comment]
@goanpeca

yes, looks good

**Comment by ccordoba12** [comment]
> should this go to 3.x?

Sure, it's a very simple fix.

**Comment by kayan1** [comment]
Not sure if there is a better place to post this question (I've search many places and this was the closest thread), but I seem to remember on a previous version of Spyder, the Variable Explorer would open like it does in MATLAB: instead of opening a new window for each variable inspected (how it currently behaves in 3.3.6), it used to open in a new tase behind the editor. I liked this behavior more, is there a reason why it was changed to producing new window each time I inspect a variable from the VE?

**Comment by rajat-voyfai** [comment]
Hi, I think this issue stills exists on Mac. I'm on Spyder 5.5.5

**Comment by dalthviz** [comment]
Hi there @rajat-voyfai if you have a way to reproduce this in a reliable manner and you are not using Spyder < 3.3.5 please open a new issue detailing the steps to reproduce (doing a GIF or screen recording of the behavior you are experiencing could be useful) as well as sharing all the details of your installation/setup (Spyder version, dependencies version list, method you used to install Spyder, etc) and referencing this issue
