### ISSUE TITLE
Why i cant see variable on variable explorer?

### ISSUE THREAD

**Issue by massecre2** [spyder-ide/spyder#9059]
## Problem Description
Hi to all. I was working with the csv data with API. 

```
import pandas as pd 
from sodapy import Socrata 


client = Socrata("XX",
                  "XX",
                  username="XX",
                  password="XXX")
 
results = client.get("ipu4-2q9a", limit=2000)

global BOROUGHT
BOROUGHT = [d['city'] for d in results]
print(BOROUGHT)
```

That is my own code. I dont understand it when i ran this code on spyder, results availabe on the variable explorer but BOROUGHT not. I search on the google and same source , it says variable explorer only show global variables. So than i already convert it into global variables? How can i show on the variable explorer?

![resim](https://user-images.githubusercontent.com/8548059/55223836-25e97a00-5220-11e9-9220-95a163e9c498.png)

### What steps reproduce the problem?

1. Open Spyder, and run code 
2. I convert to global variables which variable i want to see on variable explorer(etc, borough)
3. there is no any variables on variable explorer

### What is the expected output? What do you see instead?
I dont understand it when i ran this code on spyder, results availabe on the variable explorer but BOROUGHT not. I search on the google and same source , it'll be say variable explorer only show global variables. So than i already convert it into global variables? How can i show on the variable explorer?

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.1 64-Bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

**Comment by ccordoba12** [comment]
Please go to the menu

    Tools > Preferences > Variable Explorer

and deactivate the option called

    Exclude all-uppercase references
