### ISSUE TITLE
Spyder has encountered a problem

### ISSUE THREAD

**Issue by devvikas** [spyder-ide/spyder#9060]
## Description

**What steps will reproduce the problem?**

1. img = cv2.imread('some image file',0)
2. click on the variable explorer to open the image in array view.

**Array vi
![error](https://user-images.githubusercontent.com/13313619/55230488-fb121c80-5245-11e9-91db-4b8108fde15a.png)
**

**Please provide any additional information below**

  File "D:\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "D:\Anaconda\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.23.4 (OK)
numpy >=1.7      :  1.16.2 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder
