### ISSUE TITLE
Default icons invisible in dark themes

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#9061]
When using a dark theme in Linux, the default Spyder 3 icons look almost invisible, especially with high contrast settings. This is an example of how it looks like in KDE with theme "Breeze dark" (it can get worse with other colors and themes):
![spyder_dark](https://user-images.githubusercontent.com/11860098/55233273-bb8d0580-5230-11e9-81fe-54f71b368fed.png)
Would be nice if these default icons could be made in a lighter gray shade so that thet would play well with dark themes.

**Comment by ccordoba12** [comment]
Thanks for reporting. This is already fixed because we added a dark theme for our next version (Spyder 4), to be released later this year.
