### ISSUE TITLE
Handling conda environments with spyder v 4.0.0b1

### ISSUE THREAD

**Issue by steadyfish** [spyder-ide/spyder#9063]
### What steps will reproduce the problem?

Steps to reproduce:
Updated spyder based on this answer - https://stackoverflow.com/questions/52380572/handling-folds-in-spyder

Updated spyder-kernels back to v0.* to work with conda environments. 

Restarting IPython console showed up Issue reporter popup

### Traceback
```python-traceback
  File "C:\Anaconda\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1432, in close_client
  File "C:\Anaconda\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1111, in create_new_client
  File "C:\Anaconda\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 406, in is_module_installed
  File "C:\Anaconda\Anaconda3\lib\inspect.py", line 973, in getsource
    lines, lnum = getsourcelines(object)
  File "C:\Anaconda\Anaconda3\lib\inspect.py", line 955, in getsourcelines
    lines, lnum = findsource(object)
  File "C:\Anaconda\Anaconda3\lib\inspect.py", line 786, in findsource
    raise OSError('could not get source code')
OSError: could not get source code
```

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.11.0     :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> Updated spyder-kernels back to v0.* to work with conda environments.

Spyder 4 only works with `spyder-kernels` **1.0+**

**Comment by steadyfish** [comment]
@ccordoba12  Thanks for your quick response. 

With that, is there a recommended way of handling environments in Spyder 4?

**Comment by ccordoba12** [comment]
You need to install spyder-kernels 1.0+ in all of them, then select the environment you want to use in

    Preferences > Python interpreter
