### ISSUE TITLE
temp.py Always Opens with Previous Content

### ISSUE THREAD

**Issue by HJLBX** [spyder-ide/spyder#9068]
### What steps will reproduce the problem?

Every time I open Spyder IDE, the editor opens to the temp.py and contains the entire code that I previously typed but did not save.

I dont' want Spyder to retain the prior script.

There is no way to change this behavior ? This behavior is extremely annoying because I have to delete the prior script to get a clear screen. If I wanted to retain the script, then I would go ahead and take the necessary steps to save it as a .py file.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> There is no way to change this behavior ?

No, there isn't.

> This behavior is extremely annoying because I have to delete the prior script to get a clear screen

Well, don't use `temp.py` to write your code if you don't want to see this behavior.
