### ISSUE TITLE
Spyder 4.0b1: cannot drag panes like in Spyder 3

### ISSUE THREAD

**Issue by RnoldR** [spyder-ide/spyder#9078]
## Problem Description
A pane can be undocked, but it cannot be docked again in Spyder 4.0.0b1. I had to create a new env, install spyder 3 and create the layout I wished to have. After that it appeared in Spyder 4

### What steps reproduce the problem?
1. Do a Spyder --reset 
2. goto view and add two panes: the project explorer and the outline pane.
3. undock the outline pane and watch it become an autonomous separate window. This can be moved everywhere but not be docked.

### What is the expected output? What do you see instead?
When clicking on undock in spyder 3 an outline is drawn around the undocked pane and it can be moved everywhere to be docked in a new position.

### Paste Traceback/Error Below (if applicable)
No errors, it just does not work as expected.

## Versions
* Spyder version: 4.0.0b1
* Python version: 3.6.8 (64 bits)
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04

### Dependencies

```
pyflakes >=0.6.0  :  2.1.0 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.11.0     :  0.13.3 (OK)
psutil >=0.3      :  5.5.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.16.0 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This was already completely reworked in master and it'll be available in our next beta. In the meantime, if you want stability, please stick to Spyder 3.

**Comment by RnoldR** [comment]
Great to know! I find the beta version of Spyder 4 quite stable, just thought I'd mention this.

**Comment by dinya** [comment]
It seems the last beta release (4.0.0 beta2) has a similar problem with the docking/undocking. I can dock/undock to the same location, but can't move the dockable widget to a custom location like in the spyder 3.x.

Python 3.7.3, Windows 7 64 bit

Is that a reason to new issue or reopen this one?

**Comment by ccordoba12** [comment]
The way to reorganize panes changed in Spyder 4. Now you have to go to the menu

    View > Lock panes and toolbars

and make sure that that option is turned off. Then you could move panes around by dragging and dropping them from the top.

**Comment by dinya** [comment]
@ccordoba12 

Thanks a lot!
