### ISSUE TITLE
Spyder 3 kernel needs to be restarted after each execution

### ISSUE THREAD

**Issue by ujwalaparupalli** [spyder-ide/spyder#9083]
## Problem Description

I am using spyder3 on ubuntu 16.04 as an IDE for python programming. The problem with spyder3 is when I run my program for the first time, it runs well and the second time I run it shows kernel busy forever, but does not actually do any computation. I need to restart the kernel and then it works gain. But I have to do this for each execution of a program which is not a good practice. I removed and installed spyder3 again, but didnot solve my problem. I will be grateful if anyone can help me to solve this issue.

Thank you very much for your time.

* Spyder version: 3
* Python version: 3.5
* Qt version: 
* PyQt version: 5
* Operating System name/version: Ubuntu 16.04

**Comment by ccordoba12** [comment]
>  The problem with spyder3 is when I run my program for the first time, it runs well and the second time I run it shows kernel busy forever

Please post a simple code example that displays this behavior, so we can take a look at it.

**Comment by ujwalaparupalli** [comment]
Hello,

Here is the code I tried.

`    import cv2
    img = cv2.imread('IMG_6862.jpg')
    gray= cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    
    sift = cv2.xfeatures2d.SIFT_create()
    kp = sift.detect(gray,None)
    kp, des = sift.compute(gray,kp)
    img = cv2.drawKeypoints(gray, kp, img, flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)
    cv2.imwrite('detected_sift_keypoints.jpg',img)

`
I tried running this program as soon as I started spyder3 and the output i got the following output which is expected:
![spyder1](https://user-images.githubusercontent.com/27281676/55397454-8e996500-5546-11e9-9292-869f13683948.png)
I tried running the same program again and then it shows kernel busy and stays like that forever as shown in the image.
![spyder2](https://user-images.githubusercontent.com/27281676/55397613-e932c100-5546-11e9-9874-7a5afb4e0bf6.png)

Spyder is exhibiting this behavior for every code i run. I hope this gives you an idea of the problem.

Thank you.

**Comment by ccordoba12** [comment]
Please update to our latest version (3.3.4 if you're using pip, 3.3.3 if conda) and try again. It should be fixed in that version.

**Comment by ujwalaparupalli** [comment]
Hello, I solved the problem by doing:

sudo pip install -U spyder

This worked for me :-). Thank you for your quick replies.

**Comment by ccordoba12** [comment]
Ok, great to know :+1:
