### ISSUE TITLE
Crash in Editor

### ISSUE THREAD

**Issue by farismismar** [spyder-ide/spyder#9091]
Spyder 3.3.4 on MacOS 10.13.4.  Keeps crashing sporadically.  One way to reproduce the problem is to type an object in the Console 1/A then '.' in an attempt to get the autocomplete list of methods, then click in the main code screen as if you are editing your code there.

**Comment by ccordoba12** [comment]
I'm going to close this and ask you to open a new issue with all the information we require in our issues template.

We require it so as to not waste our time asking for your Qt/PyQt versions and the rest of the things mentioned in the template.

That information is also filled up automatically when you report an issue through the menu

    Help >  Report issue...
