### ISSUE TITLE
How to Read Multiple pdf files through GUI

### ISSUE THREAD

**Issue by Ashu-jun** [spyder-ide/spyder#9094]
## Problem Description
I m trying to read to multiple pdf files through GUI and storing read data in directory.
Using python 3.7.anaconda spyder 3.2,tkinter

### What steps reproduce the problem?

1. GUI is not working properly
2. 
3. 

### What is the expected output? What do you see instead?
I want to read multiple files when i click Button but  it is executing before clicking it before window creation. I want window should be created and then when i click button it should read it and also a massage that reading is done. 

### Paste Traceback/Error Below (if applicable)

 
 ret.color = graphics.stroke_color

AttributeError: 'PDFGraphicState' object has no attribute 'stroke_color'
```

## Versions
<!--- You can get this information from Help > About Spyder...
or (if Spyder won't launch) the "conda list" command
from the Anaconda Prompt/Terminal/command line. --->

* Spyder version: 3.2
* Python version: 3.7 ,using tkinter
* Qt version: 
* PyQt version: 
* Operating System name/version: windows 10

### code
from readDir import *
from tkinter import *

root=Tk()
Button(root, text='Batch Processing',width=20,bg='blue',fg='white',command=getAll(dirName)).place(x=1030,y=130)


root.mainloop()
```

**Comment by ccordoba12** [comment]
If you want to run Tk applications in our IPython console, you need to change your graphics backend first in

    Tools > Preferences > IPython Console > Graphics > Backend

to Tk, then restart all open consoles or restart Spyder.

Other than that, we can't help further you because this is place to report Spyder problems, not to get general help, sorry.

**Comment by Ashu-jun** [comment]
Okay thank you
