### ISSUE TITLE
Interactive matplotlib figures do not respond after script re-run with dialogue open

### ISSUE THREAD

**Issue by pyZerrenner** [spyder-ide/spyder#9096]
While writing the description I found that this applies to the matplotlib or qtconsole bug tracker.
This Issue can be closed.
Sorry for the inconvenience.

For completeness, here is the gist of the problem:

Open an interactive matplotlib figure. Open the dialogue window "Configure subplots" or "Edit axes" of the figure (all figures are now frozen and cannot be interacted with). Execute ``plt.close()`` in the parent console. The figure is closed but the dialog box is still open. Once the dialog is closed, the "frozen" state is not lifted properly, probably because the parent figure is gone. All figures (also subsequently created ones) cannot be interacted with (except via the console or the Windows taskbar).

This is an issue with either matplotlib (it doesn't expect a figure to be closed while a dialog is open and thus doen't handle this situation correctly) or with qtconsole (it allows console interaction, while a dialog box is open).
This issue does not appear in a standalone IPython console, because the console is blocked as long as the dialogue box is open (so ``plt.close()`` cannot be executed until the dialog is closed).

**Comment by ccordoba12** [comment]
> While writing the description I found that this applies to the matplotlib or qtconsole bug tracker.
This Issue can be closed.
Sorry for the inconvenience.

Ok, thanks for letting us know about it. Perhaps this is avoided if you change the Matplotlib backend before creating figures, with the command

    %matplotlib qt
