### ISSUE TITLE
change python interpreter  in preferences in spyder

### ISSUE THREAD

**Issue by Silon632** [spyder-ide/spyder#9101]
I have created two virtual environments,"pytorch" and "tensorflow", respectively for tensorflow and pytorch,when I want to change the python interpreter for pytorch from that for tensorflow(path->D:\ProgramFiles\Anaconda3\envs\tensorflow\pythonw.exe) in preferences(like this:Use the following interpreter-> D:\ProgramFiles\Anaconda3\envs\pytorch\python.exe),but when I verified that like "import sys; print(sys.executable)",it's still the path 'D:\ProgramFiles\Anaconda3\envs\tensorflow\pythonw.exe' .It didn't update!!But I can run codes in the virtual environment "pytorch" at terminal.Please tell me how to solve it,thanks!

**Comment by ccordoba12** [comment]
Do you have the latest Spyder version (3.3.3)? An error like yours was fixed in 3.3.2, I think.

**Comment by Silon632** [comment]
> Do you have the latest Spyder version (3.3.3)? An error like yours was fixed in 3.3.2, I think.

Thank you for your reply. Yes, I have the latest version(3.3.3), I just reset spyder settings to defaults and it works now.

**Comment by ccordoba12** [comment]
Ok, great! :+1: 

Thanks for letting us know about it.
