### ISSUE TITLE
AttributeError: module 'seaborn' has no attribute 'kdeplot' - in Spyder (through Anaconda)

### ISSUE THREAD

**Issue by patgitacc** [spyder-ide/spyder#9103]
### What steps will reproduce the problem?

Consider the following in Spyder :

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(1234)
v1 = pd.Series(np.random.normal(0, 10, 1000), name='v1')
v2 = pd.Series(2 * v1 + np.random.normal(60, 15, 1000), name='v2')
v3 = np.concatenate((v1, v2))
plt.figure()
sns.kdeplot(v3)

==> AttributeError: module 'seaborn' has no attribute 'kdeplot'

The same works very well in jupyter notebook.
I had another Python installed. I uninstalled ervything (Anaconda + Python) and re installed the most recent Anaconda, I still have the problem.

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
This is an installation problem, not a problem with Spyder. Please report it in Anaconda.
