### ISSUE TITLE
Spyder 3 don't allow me to inspect an array that is read from a csv in the variable explorer 

### ISSUE THREAD

**Issue by etradu** [spyder-ide/spyder#9108]
### What steps will reproduce the problem?

I'm uploading a CSV file as:
data = np.loadtxt('file.csv', delimiter=';',dtype='str',encoding='latin1')
                  
But Spyder don't allow me to check the data variable in a separate window or see its contents.

![image](https://user-images.githubusercontent.com/42227283/55564683-09d15700-56be-11e9-940a-26d3b0042503.png)

### Traceback
```python-traceback
  File "C:\WPy-3670\python-3.6.7.amd64\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 482, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "C:\WPy-3670\python-3.6.7.amd64\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 620, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array
```

## Versions

* Spyder version: 3.3.2.dev0 
* Python version: 3.6.7
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by bcolsen** [comment]
This is fixed in our latest version (3.3.3). Please update by opening the Anaconda Prompt and running there

    conda update spyder

**Comment by etradu** [comment]
Thank you, I was using winpython  *3.6*.7, and it has spyder 3.3.1

**Comment by bcolsen** [comment]
The latest version of winpython should work.
