### ISSUE TITLE
Using normal python installation as interpreter does not work

### ISSUE THREAD

**Issue by hdkire** [spyder-ide/spyder#9116]
## Problem Description

Using normal python installation as interpreter does not work.

### What steps reproduce the problem?

Create 3 environments:

1. Python venv where spyder == 3.3.4 is installed via pip
2. Python venv where spyder-kernels == 0.4.3 is installed via pip
3. Normal Python installation (no kind of virtual env) where spyder-kernels == 0.4.3 is installed via pip

Now start spyder from env 1. using spyder3.exe and specify the Python interpreter to use (in preferences), it works for env 2, but not for env3.

When selecting env3 it seems to fall back to the default interpreter (env1) instead.
Tested by running: `import sys; sys.executable` in the IPython console.

I've tried different versions for spyder, spyder-kernels and have reset Spyder to factory defaults several times.

## Versions

Tested on Windows 10.
All environments are based on Python 3.7.2 (64 bit)

Pip freeze (env1)

alabaster==0.7.12
astroid==2.2.5
attrs==19.1.0
Babel==2.6.0
backcall==0.1.0
bleach==3.1.0
certifi==2019.3.9
chardet==3.0.4
cloudpickle==0.8.1
colorama==0.4.1
decorator==4.4.0
defusedxml==0.5.0
docutils==0.14
entrypoints==0.3
idna==2.8
imagesize==1.1.0
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
isort==4.3.16
jedi==0.13.3
Jinja2==2.10
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
keyring==19.0.1
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
mccabe==0.6.1
mistune==0.8.4
nbconvert==5.4.1
nbformat==4.4.0
numpydoc==0.8.0
packaging==19.0
pandocfilters==1.4.2
parso==0.3.4
pickleshare==0.7.5
prompt-toolkit==2.0.9
psutil==5.6.1
pycodestyle==2.5.0
pyflakes==2.1.1
Pygments==2.3.1
pylint==2.3.1
pyparsing==2.3.1
PyQt5==5.12.1
PyQt5-sip==4.19.15
PyQtWebEngine==5.12.1
pyrsistent==0.14.11
python-dateutil==2.8.0
pytz==2018.9
pywin32-ctypes==0.2.0
pyzmq==18.0.1
QtAwesome==0.5.7
qtconsole==4.4.3
QtPy==1.7.0
requests==2.21.0
rope==0.14.0
six==1.12.0
snowballstemmer==1.2.1
Sphinx==2.0.0
sphinxcontrib-applehelp==1.0.1
sphinxcontrib-devhelp==1.0.1
sphinxcontrib-htmlhelp==1.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.2
sphinxcontrib-serializinghtml==1.1.1
spyder==3.3.4
spyder-kernels==0.4.3
testpath==0.4.2
tornado==6.0.2
traitlets==4.3.2
typed-ast==1.3.1
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
wrapt==1.11.1

Pip freeze (env2, env3)

backcall==0.1.0
cloudpickle==0.8.1
colorama==0.4.1
decorator==4.4.0
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
jedi==0.13.3
jupyter-client==5.2.4
jupyter-core==4.4.0
parso==0.3.4
pickleshare==0.7.5
prompt-toolkit==2.0.9
Pygments==2.3.1
python-dateutil==2.8.0
pyzmq==18.0.1
six==1.12.0
spyder-kernels==0.4.3
tornado==6.0.2
traitlets==4.3.2
wcwidth==0.1.7

**Comment by ccordoba12** [comment]
> When selecting env3 it seems to fall back to the default interpreter (env1) instead.

This looks like a PATH issue, so not a problem with Spyder directly.

I'm very sorry but we don't have time to help you debug this because we mainly support Anaconda. So it's up to you to understand the source of this problem.

**Comment by hdkire** [comment]
> > When selecting env3 it seems to fall back to the default interpreter (env1) instead.
> 
> This looks like a PATH issue, so not a problem with Spyder directly.

At least there are no obvious conflicts in the PATH and PYTHONPATH is empty.
For what it is worth, spyder manages to start one process which uses env3 out of a total of 10 python processes, not counting Qtwebengineprocesses:
`"env3\pythonw.exe" -m spyder_kernels.console ...`

> I'm very sorry but we don't have time to help you debug this because we mainly support Anaconda. So it's up to you to understand the source of this problem.

If you are interested, I might continue to look into it and I could post updates if I find something useful.

**Comment by ccordoba12** [comment]
Sure, if you want to keep us posted about your findings and there's something we can do to solve this issue, that's fine for me.

**Comment by ccordoba12** [comment]
I'm going to close this one just to clean our backlog a bit, but you're welcome to keep posting here.

**Comment by hdkire** [comment]
The problem might be related to Python 3.7.2. There are no obvious issues in 3.7.3 using the same package versions. Looking at the Python changelog (https://docs.python.org/3/whatsnew/changelog.html) there seems to be significant changes to venv (on Windows) happening in 3.7.2 and 3.7.3.

3.7.3:

https://bugs.python.org/issue35872: Uses the base Python executable when invoking venv in a virtual environment
https://bugs.python.org/issue35873: Prevents venv paths being inherited by child processes

3.7.2:

https://bugs.python.org/issue34977: venv on Windows will now use a python.exe redirector rather than copying the actual binaries from the base environment.
