### ISSUE TITLE
Wrong Help displayed when using editor option

### ISSUE THREAD

**Issue by emilmirzayev** [spyder-ide/spyder#9131]
### Issue Report Checklist

* [ *] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ *] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [* ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [* ] Restarted Spyder
    * [ *] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [* ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When trying to get the help using **ctrl + I** sometimes it shows completely unrelated help. Yet, when I search for that help text in the console using the library level "index" it shows correct output.
Example:
`grouped_results = df.groupby("session_id")[numeric_columns].aggregate(["mean", "min", "max", "var"])`
![image](https://user-images.githubusercontent.com/25964049/55715857-e5df7f80-59f5-11e9-8846-610c552712d9.png)

`pd.DataFrame.groupby()`
![image](https://user-images.githubusercontent.com/25964049/55715904-f859b900-59f5-11e9-9a9d-bb88ee5f3ed6.png)

Sometimes it doesnt even find a documenation (very inconsistent)

## Versions

Spyder 3.3.4
Python 3.7.2 32-bit
Qt 5.12.1
PyQt5 5.12
Windows 10 

### Dependencies

```
IPython >=4.0     :  7.3.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  None (NOK)

```

**Comment by ccordoba12** [comment]
Unfortunately this is a problem with Pandas because it uses a dynamic way to generate docstrings for some its classes and methods.

For now there's nothing we can do about it, sorry.

**Comment by bcolsen** [comment]
Duplicate of #5522
