### ISSUE TITLE
Help pane doesn't accept aliased modules

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#9143]
**Steps to reproduce:**
* Import some module in Python with an alias - e.g.
```python
import numpy as np
```
(not `import numpy`)
* Type the name of one of the imported module's function/classes in the help pane along with its prefix - e.g. `np.arange`
* Press enter.

**Expected behavior:** should show the help for the function/class that was requested. Should also ideally not need an enter keypress, like it was in 3.3.1.

**Actual behavior:** deletes what was just written and goes back to what was previously there, or to blank if nothing was written before. As such, cannot get help for a function inside an aliased package unless importing it like
```python
from numpy import arange
```
Will also not take it with the package's full name - e.g. `numpy.arange` would also not work.

**Setup:** Spyder 3.3.4, running on windows 10, installed from Anaconda, Python 3.6.8.

**Comment by bcolsen** [comment]
I can confirm this in master as well. 

`ctrl+i` on `np.arange` in the console works as expected.

**Comment by goanpeca** [comment]
Is this a regression ? or this has been a bug for some time?

**Comment by david-cortes** [comment]
> Is this a regression ? or this has been a bug for some time?

It's a regression, was working fine in 3.3.3 when copy-pasted, and fine in 3.3.1 when written.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one. I think it's related with the changes you made in 3.3.4 to try to fix another problem in the search field of the Help pane.
