### ISSUE TITLE
How to quickly view the source code of a function in Spyder?I konw that the source code can be conveniently viewed in pycharm, but it seems that only the help document can be viewed in spyder.

### ISSUE THREAD

**Issue by catqaq** [spyder-ide/spyder#9159]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Just keep pressed the `Ctrl` key and move with the mouse to the function/class/method you want to see its source code, the do a left mouse click on it.

You can also press `Ctrl+G` and Spyder will show you the source code of the function/class/method the cursor is placed on.

**Comment by catqaq** [comment]
Thanks a lot! It works!

**Comment by onkarkawade** [comment]
In the source code, I am not able to see the full code.
It's showing 4 dots after every like below the code

# Buffering cannot be determined: fall back to BinaryIO
@overload
def open(
    file: _OpenFile,
    mode: OpenBinaryMode,
    buffering: int,
    encoding: None = ...,
    errors: None = ...,
    newline: None = ...,
    closefd: bool = ...,
    opener: Optional[_Opener] = ...,
) -> BinaryIO: ...

Please suggest how to see code

**Comment by onkarkawade** [comment]
In source code, I am not able to see deteil code.
Its showing 4 dots every end of line like below
# Buffering cannot be determined: fall back to BinaryIO
@overload
def open(
    file: _OpenFile,
    mode: OpenBinaryMode,
    buffering: int,
    encoding: None = ...,
    errors: None = ...,
    newline: None = ...,
    closefd: bool = ...,
    opener: Optional[_Opener] = ...,
) -> BinaryIO: ...


How to check all code ?

**Comment by onkarkawade** [comment]
In the source code, I am not able to see the detailed code. It's showing 4 dots at the end of the line.

like this : 

if sys.platform != "win32":
    # Unix only
    def chroot(path: AnyPath) -> None: ...
    def lchflags(path: AnyPath, flags: int) -> None: ...
    def lchmod(path: AnyPath, mode: int) -> None: ...
    def lchown(path: AnyPath, uid: int, gid: int) -> None: ...


How to get detailed code?
