### ISSUE TITLE
spyder can not import tensorflow. The 'stop the current command' button in ipython console remains red forever after running an import statement. 

### ISSUE THREAD

**Issue by towkimiah** [spyder-ide/spyder#9163]
### Issue Report Checklist

* [ 1] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ 2] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [3 ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [4 ] Restarted Spyder
    * [ 5] Reset preferences with ``spyder --reset``
    * [6 ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [7 ] Tried the other applicable steps from the Troubleshooting Guide
* [8 ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder cannot import tensorflow. Im using a virutal environment for tensoflow cpu. 
import tensorflow as tf 
tried to run this command on spyder. When I run command, in IPython console " In [1]: " shows up but the "stop the current command" button stays red forever, which stays gray if code runs successfully.  

If i run 
import numpy
it runs without any error. and the red button stays gray. 

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```
![Capture](https://user-images.githubusercontent.com/46684245/56209531-a3f9ad80-6075-11e9-9677-ecee59210401.PNG)

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.8
* Qt version: 5.9.7 
* PyQt version: 5.9.2
* Operating System name/version: windows 10 64bit

### Dependencies

```
(tensorflow) C:\Users\towki>pip list
Package                  Version
------------------------ ---------
absl-py                  0.7.1
alabaster                0.7.12
asn1crypto               0.24.0
astor                    0.7.1
astroid                  2.2.5
attrs                    19.1.0
Babel                    2.6.0
backcall                 0.1.0
bleach                   3.1.0
certifi                  2019.3.9
cffi                     1.12.2
chardet                  3.0.4
cloudpickle              0.8.0
colorama                 0.4.1
contextlib2              0.5.5
cryptography             2.6.1
cycler                   0.10.0
Cython                   0.29.6
decorator                4.4.0
defusedxml               0.5.0
docutils                 0.14
entrypoints              0.3
gast                     0.2.2
grpcio                   1.19.0
h5py                     2.8.0
html5lib                 0.9999999
idna                     2.8
imagesize                1.1.0
ipykernel                5.1.0
ipython                  7.4.0
ipython-genutils         0.2.0
ipywidgets               7.4.2
isort                    4.3.16
jedi                     0.13.3
Jinja2                   2.10.1
jsonschema               3.0.1
jupyter                  1.0.0
jupyter-client           5.2.4
jupyter-console          6.0.0
jupyter-core             4.4.0
Keras                    2.2.4
Keras-Applications       1.0.7
Keras-Preprocessing      1.0.9
keyring                  18.0.0
kiwisolver               1.0.1
lazy-object-proxy        1.3.1
lxml                     4.3.2
Markdown                 3.1
MarkupSafe               1.1.1
matplotlib               3.0.3
mccabe                   0.6.1
mistune                  0.8.4
mkl-fft                  1.0.10
mkl-random               1.0.2
mock                     2.0.0
nbconvert                5.4.1
nbformat                 4.4.0
notebook                 5.7.8
numpy                    1.16.2
numpydoc                 0.8.0
olefile                  0.46
packaging                19.0
pandocfilters            1.4.2
parso                    0.4.0
pbr                      5.1.3
pickleshare              0.7.5
Pillow                   5.4.1
pip                      19.0.3
prometheus-client        0.6.0
prompt-toolkit           2.0.9
protobuf                 3.7.1
psutil                   5.6.1
pycodestyle              2.5.0
pycparser                2.19
pyflakes                 2.1.1
Pygments                 2.3.1
pylint                   2.3.1
pyOpenSSL                19.0.0
pyparsing                2.4.0
pyreadline               2.1
pyrsistent               0.14.11
PySocks                  1.6.8
python-dateutil          2.8.0
pytz                     2018.9
pywin32                  223
pywinpty                 0.5.5
PyYAML                   5.1
pyzmq                    18.0.1
QtAwesome                0.5.7
qtconsole                4.4.3
QtPy                     1.7.0
requests                 2.21.0
rope                     0.12.0
scipy                    1.2.1
Send2Trash               1.5.0
setuptools               41.0.0
six                      1.12.0
snowballstemmer          1.2.1
Sphinx                   1.8.5
sphinxcontrib-websupport 1.1.0
spyder                   3.3.4
spyder-kernels           0.4.4
tensorboard              1.7.0
tensorflow               1.13.1
tensorflow-estimator     1.13.0
termcolor                1.1.0
terminado                0.8.2
testpath                 0.4.2
tornado                  6.0.2
traitlets                4.3.2
typed-ast                1.3.1
urllib3                  1.24.1
wcwidth                  0.1.7
webencodings             0.5.1
Werkzeug                 0.15.2
wheel                    0.33.1
widgetsnbextension       3.4.2
win-inet-pton            1.1.0
wincertstore             0.2
wrapt                    1.11.1
```

**Comment by ccordoba12** [comment]
Please try to run your code in the Jupyter notebook and tell us what you find.

**Comment by towkimiah** [comment]
> Please try to run your code in the Jupyter notebook and tell us what you find.
It gives the following error. 
![Capture2](https://user-images.githubusercontent.com/46684245/56214115-13c06600-607f-11e9-882e-f9ba032ea6bb.PNG)
@ccordoba12 thank you for your time. looking forward to hearing from you.

**Comment by ccordoba12** [comment]
I'm very sorry but if your code fails in both Spyder *and* the Jupyter notebook, it means this not related to us.

Since you're using `pip`, my last recommendation is to switch to Anaconda and install tensorflow with it.
