### ISSUE TITLE
brace matching confused by strings with braces

### ISSUE THREAD

**Issue by jbhatami** [spyder-ide/spyder#9179]
### What steps will reproduce the problem?

The following code:
print('string with parenthesis)')

confuses the brace matching logic.

It thinks the parenthesis in the string is part of the parenthesis in the print function.

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.3
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a known issue, but we don't know how to solve it.
