### ISSUE TITLE
ReInstalled Anconda Set Python 3.6

### ISSUE THREAD

**Issue by ayelet11** [spyder-ide/spyder#9184]
### What steps will reproduce the problem?

I uninstalled Anaconda (two instances).  I reinstalled to the latest version. I did "conda update python= 3.6" from cmd with some errors and ran into some errors ($ET _sysp=%~dpA
'ET' is not recognized as an internal or external command,
operable program or batch file.

$IF NOT EXIST "!_sysp!\Scripts\conda.exe"
Collecting package metadata: done
Solving environment: done
). Then launched Spyder

### Traceback
```python-traceback
  File "C:\Users\Garber\Anaconda3\lib\site-packages\spyder\plugins\__init__.py", line 515, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Garber\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 773, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Garber\Anaconda3\lib\site-packages\spyder\plugins\ipythonconsole.py", line 1095, in create_new_client
    version='<1.0.0')
  File "C:\Users\Garber\Anaconda3\lib\site-packages\spyder\utils\programs.py", line 454, in is_module_installed
    return eval(output.decode())
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing
```

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.7 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please close Spyder, open an Anaconda Prompt, run there

    spyder --reset

and try again. That should fix your problem.

**Comment by ayelet11** [comment]
Thanks very much

בתאריך יום ב׳, 22 באפר׳ 2019, 10:50, מאת Carlos Cordoba ‏<
notifications@github.com>:
