### ISSUE TITLE
Stop during startup

### ISSUE THREAD

**Issue by Ticonderoga** [spyder-ide/spyder#9185]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm working with archlinux and I've been using spyder3-git (AUR package) for a long time on a daily basis.  With a fresh install on my new PC  the startup of Spyder newer ends. 
* At first green splash screen -> OK
* The main window appears -> OK
* No interaction is possible with the window (menu, console, help etc...) with keyboard or the mouse. It looks like an infinite loop ..
* I should kill the process to get rid of the window  

I tried to reset or even build a brand new spyder from github ==> same result

### What steps reproduce the problem?

1.  Just install spyder from github ...
2.  start spyder ...
3. 

### What is the expected output? What do you see instead?
normal startup

### Paste Traceback/Error Below (if applicable)

when I break the execution it ends on 

[spyder-debug.log](https://github.com/spyder-ide/spyder/files/3101651/spyder-debug.log)

```python-traceback



```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> No interaction is possible with the window (menu, console, help etc...) with keyboard or the mouse. It looks like an infinite loop

This looks like a problem with Qt/PyQt and not with Spyder.

> when I break the execution it ends on
spyder-debug.log

I don't see any problem in your debug file, so I don't know what can be happening in your case.

If you find more info, please post it here.

**Comment by Ticonderoga** [comment]
Well I didn't find any issue with Qt or pyqt but I really think it's a spyder issue ... have a look to my htop.

[Spyder-cpu.log](https://github.com/spyder-ide/spyder/files/3103043/Spyder-cpu.log)

**Comment by ccordoba12** [comment]
Sorry, I have no idea what's happening in your case.

**Comment by Ticonderoga** [comment]
OK I made some test and I finally get the following results 
with a standard Archlinux => window unresponsive
===================
python bootstrap.py  
Executing Spyder from source checkout
Revision c9ad42a34, Branch: master
01. Patched sys.path with /home/phil/src-install/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.7.3 64bits, Qt 5.12.2, PyQt5 5.12.1 on Linux]
04. Running Spyder

with a conda install => Working spyder
===================
python bootstrap.py                                                                 
Executing Spyder from source checkout
Revision c9ad42a34, Branch: master
01. Patched sys.path with /home/phil/src-install/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.7.3 64bits, Qt 5.9.6, PyQt5 5.9.2 on Linux]
04. Running Spyder

So I strongly recommend to not update your archlinux with Qt5.12 ...

**Comment by Ticonderoga** [comment]
Finally an update of pyside2 fix the whole thing !! Sorry
