### ISSUE TITLE
Error  symbol finder

### ISSUE THREAD

**Issue by lordflaron** [spyder-ide/spyder#9192]
### What steps will reproduce the problem?

Problem when doing fast symbol search, and clicking on any function name in window.

### Traceback
```python-traceback
  File "/home/lordflaron/src/spyder/spyder/widgets/fileswitcher.py", line 637, in enter
    stack_index = self.paths.index(self.filtered_path[row])
AttributeError: 'FileSwitcher' object has no attribute 'filtered_path'
```

## Versions

* Spyder version: 4.0.0.dev0 df354d171
* Python version: 3.7.3
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Linux 5.0.7-arch1-1-ARCH

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  2.0.0 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.19.0     :  0.26.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.1 (OK)
numpy >=1.7       :  1.16.1 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
Could you provide a simple video to see how to generate this error? Thanks!

**Comment by lordflaron** [comment]
Here it is! Sorry for the wait.

This behavior takes place, immediately after I turn on Spyder, without running anything beforehand:

![output](https://user-images.githubusercontent.com/6379396/56627263-dec18f80-65f9-11e9-9f1c-35e5b73022e4.gif)

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
@ccordoba12 I tried to reproduce this error but I was unable to (I tried opening a project and enabling the `Show selector for classes and functions`)

@lordflaron thank you for the `gif` :+1:, seeing it I think there is another part of the traceback that is not in the original comment (for what I see, something related with `helperwidgets.py`). Could you paste the traceback that appears in the `gif` here? Also, did you make changes in the preferences before experiencing the issue? All the info to replicated the issues is really appreciated :)

**Comment by lordflaron** [comment]
Here is the full traceback:

```
  File "/home/lordflaron/src/spyder/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Traceback (most recent call last):
  File "/home/lordflaron/src/spyder/spyder/widgets/helperwidgets.py", line 127, in paint
    textRect = style.subElementRect(QStyle.SE_ItemViewItemText, options)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
```

In terms of any information I can give, this is what the terminal shows when I run spyder:

```
qt5ct: using qt5ct plugin
D-Bus global menu: no
```
The preferences I changed were my theme to be solarized light and for the fonts on both plain text and rich text to be "Space Mono". Other than that, nothing. Hope that helps!

**Comment by ccordoba12** [comment]
That's a problem with Qt and not with Spyder. Please report it with your distribution or use Anaconda instead.
