### ISSUE TITLE
Pass language from console and editor on calltip call

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9194]
On spyder/widgets/mixins.py

```python
    _PARAMETER_HIGHLIGHT_COLOR = '#DAA520'
    _DEFAULT_TITLE_COLOR = '#2D62FF'
    _CHAR_HIGHLIGHT_COLOR = 'red'
    _DEFAULT_TEXT_COLOR = '#999999'
```

and 

```python
# TODO: Select language and pass it to call
```
----

@dalthviz we need to be able to ask the kernel what language it is running (right now python, but it could be anything)

spyder/plugins/ipythonconsole/widgets/help.py
```python
# TODO: Pass the language from the Console to the calltip
```

**Comment by ccordoba12** [comment]
@dalthviz, the language name is obtained after making a `kernel_info` request to the kernel. The incoming info is handled here:

https://github.com/jupyter/qtconsole/blob/77238a8195eb1f7ac085579d6ad38cd258123aee/qtconsole/jupyter_widget.py#L288

So please do a PR in `qtconsole` to set `language_name` as an attribute of `JupyterWidget` in `_handle_kernel_info_reply`. Also initialize it to `None` in the `__init__` method of that class. That's a minor change to avoid overriding `_handle_kernel_info_reply` in our side.

After that's in place, we could easily get `language_name` through the `shellwidget` of each console.

**Comment by ccordoba12** [comment]
For the Editor, we need to add, there's already `self.language` in CodeEditor that we need to pass to tooltips and calltips to set its language correctly.
