### ISSUE TITLE
Cannot connect to an external PyLS server

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#9195]
## Problem Description

The new menu does not allow to connect to an external PyLS server. 

### What steps reproduce the problem?

1. Run spyder-pyls server on one terminal with the command `python -m pyls -vvv --port 2089 --tcp`
2. Run spyder on another terminal
3. Try to connect with the running server by changing the port in Preferences > Completion and linting > Advanced 
4. After giving apply, there's no new connection received by the local pyls server.
* The same happens after trying to setup a new server for python.

### What is the expected output? What do you see instead?
Connect to an external PyLS server running locally.

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: ba26876de) 
* Python version: 3.6.8
* Qt version: 5.12.2
* PyQt version: 5.12.1 
* Operating System name/version: Darwin 18.2.0 

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.19.0     :  0.21.5 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, I was wrong when I instructed you to assume that external servers can only live in external machines. As @steff456 pointed out, external servers are simply servers started outside Spyder.

So to fix this we need to add a new checkbox in `Completion and linting > Advanced Setttings` (below the current options) with this text:

    [ ] This is a remote server

associated to the option `advanced/external` and being `False` by default. Then we need to use that option to set the value of `self.python_config['external']` in `update_python_config` of `LSPManager`.
