### ISSUE TITLE
Combobox with issues using dark theme - QDarkStyle problem

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/spyder#9199]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Combo boxes are showing a white line in top and bottom when opened, and it includes a checkbox inside the combobox when using DarkStyle.

**That is a problem with QDarkStyle, I need a confirmation of this bug reported in:** https://github.com/ColinDuquesnoy/QDarkStyleSheet/issues/132

### What steps reproduce the problem?

1. Open the Spyder IDE
2. Go to Help tab
3. Open Combobox of Console
4. Or preferences/Appearence theme combobox

![combobox-problem](https://user-images.githubusercontent.com/5084939/56686935-82b74380-66ab-11e9-8a00-9bb4df7b08c7.gif)
![combobox-problem-too](https://user-images.githubusercontent.com/5084939/56686938-84810700-66ab-11e9-97d2-4bbe91748082.gif)
![combobox-no-problem](https://user-images.githubusercontent.com/5084939/56687335-6b2c8a80-66ac-11e9-8272-e38f9921555a.gif)

### What is the expected output? What do you see instead?

A normal combobox as in Fonts Menu.

## Versions

* Spyder version: 4.0.0.dev
* Python version: 3.6.8
* Qt version: 5.6.2
* PyQt version: 5.6
* Operating System name/version: Linux, Ubuntu 18.04

Also, providing this versions as you do with dependencies should very nice to make the reporting easy. Or using [help-dev](https://pypi.org/project/helpdev/) below.

[helpdev-info.txt](https://github.com/spyder-ide/spyder/files/3113847/helpdev-info.txt)

### Dependencies

pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.6 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.19.0     :  0.26.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.3.1 (OK)

**Comment by ccordoba12** [comment]
@dpizetta, thanks for reporting. I noticed this problem too. Is there something we can do about it in Spyder?

**Comment by goanpeca** [comment]
I think I know how to solve it. I had this same issue with Navigator

**Comment by ccordoba12** [comment]
Thanks a lot @goanpeca!

**Comment by dpizetta** [comment]
@ccordoba12  I think that is a problem with qdarkstyle, but if @goanpeca can share some info about it that I can use in the qdss will help me a lot! Tks

**Comment by goanpeca** [comment]
>I think that is a problem with qdarkstyle, but if @goanpeca can share some info about it that I can use in the qdss will help me a lot! Tks

Yes it is, I meant I fixed a similar issue I had for another app.

**Comment by goanpeca** [comment]
Still issues, but getting there

<img width="716" alt="Screen Shot 2019-04-25 at 21 13 29" src="https://user-images.githubusercontent.com/3627835/56779101-0140dd80-679f-11e9-97b7-6a3a961480be.png">

**Comment by ccordoba12** [comment]
This was fixed in QDarkstyle **2.6.7**
