### ISSUE TITLE
How to solve this problem: You have missing dependencies jedi >0.9.0:None(NOK)

### ISSUE THREAD

**Issue by Duke-ding** [spyder-ide/spyder#9204]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/home/dlw/anaconda2/envs/py3/lib/python3.6/site-packages/spyder/utils/introspection/plugin_client.py", line 184, in _heartbeat
    def _heartbeat(self):
KeyboardInterrupt

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.6.2
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.16.3 (OK)
sphinx >=0.6.6   :  2.0.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  None (NOK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.4.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

**Comment by ccordoba12** [comment]
> You have missing dependencies jedi >0.9.0:None

You have to install Jedi with

    conda install jedi
