### ISSUE TITLE
Show PyLS server errors in Spyder's error report dialog

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#9211]
Instead of simply logging the errors received from the LSP servers, as it's currently done here:

https://github.com/spyder-ide/spyder/blob/c5f95e341f64189a06930dc6750d8429d97a7a4b/spyder/plugins/editor/lsp/client.py#L239-L241

I'd like those errors to be routed to our error repor dialog, so people can send them to us, but only if the language is Python.

For that @steff456, please emit a Qt signal with the error, then capture it from with the manager, like this

https://github.com/spyder-ide/spyder/blob/5a39ace4a24d95b0b4ecaf0fada0317988d37dc3/spyder/plugins/editor/lsp/manager.py#L164-L166

and send it to the main window, to a method similar to `report_issue`.

**Comment by steff456** [comment]
@ccordoba12, how do I report the error on the main window? On a Qt dialog or should I redirect to the github report widget?

**Comment by ccordoba12** [comment]
Ok, let's continue the discussion in the PR.
