### ISSUE TITLE
TypeError: cursor_position_changed

### ISSUE THREAD

**Issue by kareemjeiroudi** [spyder-ide/spyder#9221]
### What steps will reproduce the problem?

typing `(` without closing `)` and then moving the cursor.

### Traceback
```python-traceback
  File "/Users/kareem/miniconda3/envs/data_science/lib/python3.5/site-packages/spyder/widgets/calltip.py", line 117, in hideEvent
    self._cursor_position_changed)
TypeError: 'method' object is not connected
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.5.5
* Qt version: 5.12.2
* PyQt5 version: 5.12.1
* Operating System: Darwin 18.5.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.14.3 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by goanpeca** [comment]
@kareemjeiroudi thanks for reporting!

**Comment by kareemjeiroudi** [comment]
However, I have to add that this bug has never occurred to me before, and therefore I'm not sure if it's that easily reproducible, but I tried to recall the last action I made before the pop up appeared.
