### ISSUE TITLE
Spyder cannot find dll with "automatic" graphics backend

### ISSUE THREAD

**Issue by hroest** [spyder-ide/spyder#9227]
### What steps reproduce the problem?

1. Install "pyopenms" package with `pip install pyopenms` on the command line (e.g. Anaconda Powershell Prompt)
2. Set graphics backend to "automatic"
3. Restart spyder
4. `import pyopenms`

NOTE: this works again when changing the backend back to the default "Inline" (and restarting)

### What is the expected output? What do you see instead?

Expected: import the module without error
Instead: 

### Paste Traceback/Error Below (if applicable)

```python-traceback

Traceback (most recent call last):

  File "<ipython-input-1-c9c025a84644>", line 1, in <module>
    import pyopenms

  File "D:\software\Anaconda3\lib\site-packages\pyopenms\__init__.py", line 75, in <module>
    raise e

  File "D:\software\Anaconda3\lib\site-packages\pyopenms\__init__.py", line 45, in <module>
    from .all_modules import *

  File "D:\software\Anaconda3\lib\site-packages\pyopenms\all_modules.py", line 1, in <module>
    from .pyopenms_1 import *

ImportError: DLL load failed: The specified procedure could not be found.


In [2]: 
```

## Versions

* Spyder version: 3.3.5
* Python version: 3.7.3
* Qt version: Qt 5.12.2 
* PyQt version: PyQt5 5.12.1
* Operating System name/version: Windows 10 

### Dependencies

```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
> pip install pyopenms

I guess this package introduces an incompatibility with PyQt5 (which is the one that provides the automatic kernel functionality).

What happens if instead you select the Tk backend?

**Comment by hroest** [comment]
Yes, that indeed seems to be the problem. PyOpenMS has its own Qt libraries that it links against and I guess these lead to issues with the Spyder libraries. When using the Tk backend, then Spyder just in general dies and that is completely unrelated to pyOpenMS (e.g. starting a new kernel with the Tk backend and plotting something just leads to a non-responding program which I assume is a separate issue (should I open another issue for this?).

**Comment by ccordoba12** [comment]
> Yes, that indeed seems to be the problem. PyOpenMS has its own Qt libraries that it links against and I guess these lead to issues with the Spyder libraries

Yep, we can't do anything about it.

> When using the Tk backend, then Spyder just in general dies and that is completely unrelated

That's odd. Yes, please open a new issue about it, thanks!

**Comment by HijaziHassan** [comment]
Unfortunately, nothing is changed.
