### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by rampyg** [spyder-ide/spyder#9232]
### What steps will reproduce the problem?

Installed ggplot from conda-forge. It needed downgrading/upgrading certain packages including Spyder, causing problems with Spyder.

### Traceback
```python-traceback
    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'
```

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.1
* Qt version: 4.8.7
* PyQt4 (API v2) version: 4.11.4
* Operating system: Windows 10

### Dependencies

```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.4.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.15.4 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.4). Please update by opening the Anaconda Prompt and running there

    conda update spyder
