### ISSUE TITLE
Cursors do not work in Debug terminal using Spyder 4

### ISSUE THREAD

**Issue by stfnrpplngr** [spyder-ide/spyder#9233]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I cannot navigate through statements typed into the terminal when I am in Debug mode. The only way to insert something to the beginning of line is to parts of my command.

### What steps reproduce the problem?
1. Run a script in Debug mode.

### What is the expected output? What do you see instead?
![issue_spyder4_debug](https://user-images.githubusercontent.com/20129752/56894711-f760f800-6a86-11e9-894d-ec463825becb.gif)

### Paste Traceback/Error Below (if applicable)
No traceback

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.3 64 bits
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Pro

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.11.0     :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
@impact27, I think you fixed something related to this problem in qtconsole, right?

**Comment by impact27** [comment]
https://github.com/jupyter/qtconsole/pull/331

**Comment by impact27** [comment]
@stfnrpplngr you can downgrade qtconsole if you want this to work.

**Comment by ccordoba12** [comment]
@impact27, sorry for the delay in reviewing and merging your work (I thought it was merged already, but I'll try to do it as soon as possible).

What qtconsole versions are working correctly?

**Comment by impact27** [comment]
anything before https://github.com/jupyter/qtconsole/commit/d8a4810f4046e3cde098f0e1e336b447ce2b5b20 
4.4.2 or something

**Comment by ccordoba12** [comment]
Closing because @impact27 already reported this problem in qtconsole, where he also fixed it.
