### ISSUE TITLE
Autosave Error: The system cannot find the file specified

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#9234]
### What steps will reproduce the problem?

**Note:** This is *not* the same issue I reported on the Gitter that I can fairly consistently reproduce.

After not using Spyder for many hours, I switched back to it, made a small modification to an existing file (that was saved and correctly did not have an autosave), and almost immediately saved it. However, I got an autosave error dialog as well as this error message upon doing so. In any case, this new autosaved file sticks around after closing the saved file, and causes a recovery dialog to appear on the next Spyder launch (in addition to the other problem, autosaves being created for unmodified files).

I cannot repro it by simply making a change and saving the file again (although I can, of course, by making a change, waiting  for an autosave to be created, and then removing it). An autosave of the file appeared just as I was saving; I suspect it was either somehow triggered by the save itself or happened to be being saved simultaneously, and either way resulted in the error. 

While it therefore seems a bit of a fluke that I'm so far unable to reproduce, aside from that, I'm not sure simply not being able to find the autosave file (which could happen for a number of non-Spyder-related reasons, like the user removing it manually, or opening/saving it in another Spyder instance) should be a reportable Spyder-level error, but that's your call.

![image](https://user-images.githubusercontent.com/17051931/56905647-9af1de80-6a6e-11e9-82c6-15422bf5cd69.png)

### Traceback
```python-traceback
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\C. A. M. Gerlach\\.spyder-py3-dev\\autosave\\lis_vs_glm.py'
```

## Versions

* Spyder version: 4.0.0.dev0 719f56082
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.4 (OK)
pyls >=0.19.0     :  0.21.5 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.4 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.2.0 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
pylint >=0.25     :  2.2.2 (OK)
```

**Comment by jitseniesen** [comment]
I am assuming that this is the same issue as #9420 and closing it as a duplicate.

**Comment by CAM-Gerlach** [comment]
@jitseniesen Whatever the original cause might have been, its couldn't have been the same as #9420 , as that was a known result of my PR #9327 . However, I was unable to find a method to consistently reproduce it, so unless someone else stumbles upon one in the future, this is unlikely to be solved anytime soon anyway.
