### ISSUE TITLE
Help Window causes memory inflation


### ISSUE THREAD

**Issue by AyFahrettin** [spyder-ide/spyder#9241]
### What steps will reproduce the problem?

On editor, when I put cursor on any method and press Ctrl+I for displaying method details on 'Help Window', the memory increases suddenly so that the computer is locked due to the lack of memory 

It happens also when using IPython Console instead of editor. 

I was using Help Window before without a problem but somehow it happens everytime although i restarted the computer multiple times. 

## Versions

* Spyder version: 4.0.0b1 
* Python version: 2.7.15
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-48-generic

### Dependencies

```
pyflakes >=0.5.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.11.0     :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
How much memory do you have in your computer?

**Comment by AyFahrettin** [comment]
Hi Cordoba,

I have 8 GB memory. Also, the spyder was the only program running. I checked the memory before and saw that it allocates amount of 5-6 GB memory in a few seconds. 

Now, I am not able to raise this problem again. It runs without a problem. If I can, I will write here after.

**Comment by AyFahrettin** [comment]
In addition, the problem had been occured when I tried to see any method from  sklearn module. For example, KNeighborsClassifier.score(),  confusion_matrix(), train_test_split() etc.

I dont think it is  specific to description of a single method.

**Comment by ccordoba12** [comment]
This is not something we can control, sorry. Probably the webpages for those scikit-learn methods are very complex and require a lot of memory.
