### ISSUE TITLE
Remove unused Pyflakes and pep8 checks

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#9242]
## Problem Description
Verify the unused checks for pyflakes and pep8 to remove them. 

This issue forms part of the LSP integration (#7724)

**Comment by goanpeca** [comment]
@ccordoba12 perhaps we should remove the pyflakes messages that refer TODO, FIXME and XXX as we will get double marks?

See:

<img width="407" alt="Screen Shot 2019-04-30 at 15 21 19" src="https://user-images.githubusercontent.com/3627835/56990844-c69ec280-6b5b-11e9-8aaf-25cc6efa90d9.png">

**Comment by ccordoba12** [comment]
Sure, but that's not part of this issue.
