### ISSUE TITLE
Remove duplicated warning marks for code annotations 

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9244]
Spyder handles code annotations separately from the LSP, but it seems pyls also checks some of these tags. We should remove these messages from LSP and only use the conde annotations Spyder finds.

See:

<img width="407" alt="Screen Shot 2019-04-30 at 15 21 19" src="https://user-images.githubusercontent.com/3627835/56990844-c69ec280-6b5b-11e9-8aaf-25cc6efa90d9.png">

**Comment by ccordoba12** [comment]
We're probably not going to ship with a PyLS with Pylint support available, so I'm leaving this for beta3.

**Comment by goanpeca** [comment]
Sounds good !

**Comment by dalthviz** [comment]
I was unable to reproduce this:

![imagen](https://user-images.githubusercontent.com/16781833/144474078-a0bfd491-1c74-4199-90ce-363c7109ac95.png)
