### ISSUE TITLE
Improve dialog to start servers for other languages

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9245]
<img width="502" alt="Screen Shot 2019-04-30 at 16 31 30" src="https://user-images.githubusercontent.com/3627835/56994692-775d8f80-6b65-11e9-893b-5a403c723eb4.png">

- [ ] Increase editor space to the right, reduce on the left
- [ ] Add stretch on options on the left
- [ ] Check syntax highlighter is applied without changes

**Comment by ccordoba12** [comment]
This was fixed by PR #9288.
