### ISSUE TITLE
Improve messages of code analysis tooltip

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9247]
See:

<img width="298" alt="Screen Shot 2019-04-30 at 16 39 41" src="https://user-images.githubusercontent.com/3627835/56995171-9ad50a00-6b66-11e9-8dcf-9c51581d4421.png">
<img width="511" alt="Screen Shot 2019-04-30 at 16 39 51" src="https://user-images.githubusercontent.com/3627835/56995185-a45e7200-6b66-11e9-8dbc-8673f5f24816.png">

**Comment by goanpeca** [comment]
@ccordoba12 since these calltips disappear, we cannot add the docs for the different errors. We would need to add either shortcut (and hint the use of it) or make them stay if moving away from the line number area.

**Comment by ccordoba12** [comment]
> since these calltips disappear, we cannot add the docs for the different errors

Ok, then don't worry about it. We just need to make clear that `C0304`, etc are code errors.

**Comment by goanpeca** [comment]
@ccordoba12  do we need to display that things come from pylint or pyflakes?

What should we do with duplicated messages (from pylint + pyflakes etc..)?

Do we want a dedicated Icon for each line depending on the severity?

I think the actual message plus the severity is what is important (the code, or what tool found is not super important)

How about:

```
[SEVERITY ICON] Statement seems to have no effect (PyLint Code W0104)
```

Where `(PyLint Code W0104)` would be smaller and in italics.

**Comment by ccordoba12** [comment]
My answers:

>  do we need to display that things come from pylint or pyflakes?

No

> What should we do with duplicated messages (from pylint + pyflakes etc..)?

Pyflakes and Pylint should be mutually exclusive. Since the PyLS doesn't provide an option to turn off Pylint, I restricted our dependency on it to versions that doesn't include Pylint for now (i.e. < 0.25)

> Do we want a dedicated Icon for each line depending on the severity?

This is pretty good suggestion! Since a line can have several types of errors, in LineNumberArea we should only display a single icon, the one corresponding to the most critical message reported by the PyLS (in this order: errors first, then warnings and finally hints). But in the tooltip we should show all messages with their associated icons.

> [SEVERITY ICON] Statement seems to have no effect (pylint code W0104)

I like this better.

> Where (PyLint Code W0104) would be smaller and in italics.

I like this too.

**Comment by ccordoba12** [comment]
> > do we need to display that things come from pylint or pyflakes?

> No

Sorry, to clarify this: I'd like to see the source of the error at the end of message and next to the error code.

**Comment by goanpeca** [comment]
I am using the same icon for now while donig some tests. This requires using the images at the moment, I am checking to see if we could use font awesome instead.

It would look something like this:
<img width="389" alt="Screen Shot 2019-05-14 at 07 06 25" src="https://user-images.githubusercontent.com/3627835/57698848-2d23e600-761c-11e9-84b0-580612a5209e.png">

**Comment by ccordoba12** [comment]
Looking pretty good already. Thanks!
