### ISSUE TITLE
Appearance preferences for syntax highlighting with dark theme look weird

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9248]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice

## Problem Description

![image](https://user-images.githubusercontent.com/10170372/57803564-ba536180-7726-11e9-8afc-bb7423c450e4.png)

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version:

**Comment by ccordoba12** [comment]
I know how to fix this one.

**Comment by jnsebgosselin** [comment]
@goanpeca could you explain a little bit more what is it that looks weird.

I can work on this one if you are interested.

**Comment by goanpeca** [comment]
The background of the editor should look all brownish not dark blue on some parts and brownish on others. (the fix for this is probably already found on the code editor?

This should probably be fixed within the code editor widget so that using it elsewhere (like on the preferences) results in the expected look, otherwise we might need to fix it everywhere we use it, which does not sound right.

**Comment by jnsebgosselin** [comment]
Thanks @goanpeca. I'm going to fix it.
