### ISSUE TITLE
Spyder steals my letters!

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9257]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder steals letters and give them back as a block at a latter point. 

### What steps reproduce the problem?

1. Create a new file (I created `test.py` on the Desktop)
2. Type the following as fast as you can:
```python
import numpy as np
np.asarray()
np.asarray()
np.asarray()
np.asarray()
np.asarray()
```
3. Save the file under a new name (I save it as `test2.py` on the Desktop)

### What is the expected output? What do you see instead?
I expect to see what I typed. instead I see:
```python
import numpy as np
np.asaray()
np.asarray()
np.asaray()
np.asaray()
np.asaray()
rrrr
```
In this case only the `r` are missing, but I had parenthesis and other letters missing in the same way.
The `rrrr` at the end appeared when I saved the file under a new name.

### Paste Traceback/Error Below (if applicable)
NA

## Versions

* Spyder version:  Spyder 4.0.0.dev0 (Commit: 2c90e2aea) 
* Python version: Python 3.7.3 64-bit
* Qt version: Qt 5.9.1
* PyQt version: PyQt5 5.9
* Operating System name/version: Darwin 18.5.0

### Dependencies

pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.19.0     :  0.25.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)

**Comment by impact27** [comment]
Another test:
```python
def asarray():
    pass
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
import numpy as np
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
asarray()
np.asarray)
np.asarray()
np.asarray()
np.asarray()
np.asaray()
np.asarray()
np.asaray()
np.asaray()
(rrr)
```

**Comment by impact27** [comment]
It takes me about 250ms to type a letter, and I can repeat the r in about 150ms.

**Comment by bcolsen** [comment]
So this is a problem in the code completion? Does it happen when code completion is disabled?

**Comment by impact27** [comment]
> So this is a problem in the code completion? Does it happen when code completion is disabled?
> 
You are correct, it does not

**Comment by impact27** [comment]
I solved it by removing
```python
         elif text in self.auto_completion_characters: 
             self.insert_text(text) 
             if not self.in_comment_or_string(): 
                 last_obj = getobj(self.get_text('sol', 'cursor')) 
                 if last_obj and not last_obj.isdigit(): 
                     self.do_completion(automatic=True) 
```
It is a bit annoying anyway to have the widget appearing randomly. If I want code completion I can press `<tab>`. Is there a way to do that from the options?
There is probably an underlying bug but I suspect it is with Qt. Something like: If you receive an event while processing another event, it is not queued properly?

**Comment by CAM-Gerlach** [comment]
Thanks for your report of this theft. We take it very seriously, and will given Spyder a verbal reprimand and re-training on how to not steal things in order to prevent it from ever happening again :)

> It is a bit annoying anyway to have the widget appearing randomly. If I want code completion I can press <tab>. Is there a way to do that from the options?

It appears on pressing ``.``; its also called "dot completion". You can disable it under ``Editor > Code Introspection/Analysis > Automatic Code Completion``.

@ccordoba12 In Spyder 4 (i.e. Beta 3), we could just omit this option completely and have the options be either full on-the-fly completion, or only on-demand completion, with OTF being the default but an easy to find option to disable it in the prefs.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.

**Comment by dalthviz** [comment]
@ccordoba12 I think the PR that @impact27 is working on, is going to fix this :) (thanks @impact27 !)
or should I do something just for this one?

**Comment by ccordoba12** [comment]
Nop, don't worry. You're right that PR #9260 is going to fix this.
