### ISSUE TITLE
input terminal issue

### ISSUE THREAD

**Issue by mguaita** [spyder-ide/spyder#9261]
### What steps will reproduce the problem?

#Upon asigning a sentence in the Ipython terminal, I can't** move through the different indexs of the string introduced. The cursor inmediately comes back to the last position of the string, not allowing me to introduce any character changes on the string. Never had this problem before.

aux = input('Introduce a sentence: ')

Tried unistalling and installing anaconda again, reset default configuration through spyder and through the anaconda prompt (spyder --reset).

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This problem will be fixed in qtconsole **4.4.4**, to be released shortly.
