### ISSUE TITLE
Auto completion widget shows even after line return

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9267]
### What steps will reproduce the problem?

1. Type 
```python
import numpy as np
np.as
```
2. Type `<TAB> + <RETURN>` very quickly

3.
![before](https://user-images.githubusercontent.com/6740194/57197609-bdea2a00-6f69-11e9-8225-0e04de1a2b89.gif)

## Versions

* Spyder version: 4.0.0.dev0 db6848f80
* Python version: 3.7.3
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Darwin 18.5.0

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.19.0     :  0.25.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
Is there currently a timer to trigger this? If we do not we should probably have a small one to get rid of this issues

**Comment by impact27** [comment]
The time is whatever time lsp takes to come back with a reply. The way I do it in #9260 is to check if the autocompletion has not gone stale in the meanwhile.

**Comment by goanpeca** [comment]
Yes, I think we need a timer could help in this situation

**Comment by impact27** [comment]
I am not sure I understand how a timer would help? Surely you want the completion to happen as quickly as possible?
