### ISSUE TITLE
"Edit with Spyder" (Windows) should set cwd to .py file directory

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#9270]
## Problem Description

In Windows, when you right-click on a .py file and choose "Edit with Spyder", Spyder starts up with the working directory (os.getcwd) set to the Spyder settings directory.

In Preferences you can change this (I think) to one specific directory of choice, but only one.

When starting Spyder this way, the cwd should be set to the location of the ,py file.

(At least, that should be one of the options in Preferences.)

### What steps reproduce the problem?

0. Install WinPython
1. Right-click on a .py file
2. Choose "Edit with Spyder".
3. Observe resulting os.getcwd()

### What is the expected output? What do you see instead?

cwd should be location of .py file.

* Spyder version: 3.3.1
* Python version: 3.7
* Operating System name/version: Win 10 Pro x64

**Comment by ccordoba12** [comment]
> Install WinPython

This is a WinPython issue because we don't install an "Edit with Spyder" menu entry. So please report it there:

https://github.com/winpython/winpython/
