### ISSUE TITLE
Spyder crashes when launched : Fedora 30 + Anaconda3-2019.03

### ISSUE THREAD

**Issue by josephsacco** [spyder-ide/spyder#9275]
### Issue Report Checklist

* [x ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x ] Tried basic troubleshooting (if a bug/error)
    * [x ] Restarted Spyder
    * [x ] Reset preferences with ``spyder --reset``
    * [x ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x ] Tried the other applicable steps from the Troubleshooting Guide
* [x ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
System: 
* iMac running OS X 10.14.4
* VMware fusion 11.0.3
* Fedora 30 [run as a VMware fusion guest operating system]
* Anaconda3-2019.03-Linux-x86_64

Problem:
Spyder crashes when launched:
   (base) [jsacco@vmfedora ~]$ spyder

   libGL error: MESA-LOADER: failed to open vmwgfx (search paths /usr/lib64/dri)
   libGL error: failed to load driver: vmwgfx
   libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
   libGL error: failed to load driver: swrast
   Segmentation fault (core dumped)

### What steps reproduce the problem?
1. Activate (base) anaconda environment
2. launch spyder. 

### What is the expected output? What do you see instead?
I expect spyder to launch.  

I believe the source of the problem is related to the anaconda3-2019.03 distribution and fedora30. In particular the MESA drivers, and the code that invokes them are potential suspects.

Consider the following experiments:
* Deactivate the anaconda base environment
* Use the fedora30 version of python3:
     jsacco@vmfedora ~]$ /usr/bin/python3 ~/anaconda3/bin/spyder

==> spyder launches

The libGL problem persists with spyder 3.3.4 and anaconda.
* Download and unpack the spyder 3.3.4 distribution
*  Launch "bootstrap.py"
   * Use fedora30 python3
   ==> all is well
   * Use anaconda3-2019.03 python3
  ==> libGL error

Repeat the above experiments in a VM running fedora29 and all is well. 

Note:
     mesa-dry-drivers.x86_64:
       Fedora 30: 19.0.3-1.fc30
       Fedora 29: 18.3.6.3.fc29

### Paste Traceback/Error Below (if applicable)
[jsacco@vmfedora ~]$ spyder
   libGL error: MESA-LOADER: failed to open vmwgfx (search paths /usr/lib64/dri)
   libGL error: failed to load driver: vmwgfx
   libGL error: MESA-LOADER: failed to open swrast (search paths /usr/lib64/dri)
   libGL error: failed to load driver: swrast
   Segmentation fault (core dumped)

## Versions

* Spyder version: 3.3.3
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Fedora 30[run as a VMware fusion guest operating system]

### Dependencies
NA

**Comment by josephsacco** [comment]
I forgot to mention [:-)]...  Fedora30 has a spyder-3.3.3 package that launches and runs without error:
   python3-spyder.noarch                             3.3.4-1.fc30 
   python3-spyder-kernels.noarch               1:0.2.4-4.fc30

-Joseph

**Comment by josephsacco** [comment]
And yes... spyder-3.3.4 is available on Koji, which explains the version numbers seen in the previous comment.

**Comment by ccordoba12** [comment]
> I forgot to mention [:-)]... Fedora30 has a spyder-3.3.3 package that launches and runs without error:
python3-spyder.noarch 3.3.4-1.fc30
python3-spyder-kernels.noarch 1:0.2.4-4.fc30

That means this is not an Spyder problem but an issue with the Qt/PyQt Anaconda packages. Therefore, please report your problem here:

https://github.com/ContinuumIO/anaconda-issues/issues/

**Comment by josephsacco** [comment]
Thanks,  Carlos.

See:

   https://github.com/ContinuumIO/anaconda-issues/issues/10888

-Joseph
