### ISSUE TITLE
Avoid the possibility of duplicate preferences dialogs

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9281]
I noticed on OSX that pressing the shortcut several times in a row would display several Preferences dialogs.

<img width="1440" alt="Screen Shot 2019-05-06 at 18 14 49" src="https://user-images.githubusercontent.com/3627835/57260805-dc642a00-702a-11e9-8abc-0b34238c5c82.png">

**Comment by goanpeca** [comment]
@ccordoba12 should I fix this for 3.x of master?

**Comment by ccordoba12** [comment]
Master is ok (as you already did :+1:).
