### ISSUE TITLE
Hangs on"Connecting to kernel"

### ISSUE THREAD

**Issue by skjerns** [spyder-ide/spyder#9285]
## Problem Description

After returning from 3 weeks without my laptop, my spyder suddenly did not connect to the kernel anymore . I did not change any configuration and it did work back in April.

I've made a fresh install of Anaconda (3.7 2019.03 x86_64) but the problem persists. I'm using Windows 10.

The problem seems to be that the `jupyter qtconsole` leaves behind a dead kernel. Any idea how to fix it?

### What steps reproduce the problem?

1. Install newest Anaconda3 with the installer
2. Open `spyder`
3. Console panel hangs with "Connecting to kernel"

Internal console shows `kernel died`

### Solutions tried
* reset spyder `spyder --reset`
* turned off all Firewalls and AVs
* upgraded spyder to 3.3.4 (via conda)
* update spyder to beta 4.0.1b (via conda)
* reinstalled conda 5.10 (py3.6), which definitely did work
* ipython console from `cmd` runs fine
* `jupyter qtconsole` hands with "kernel died, restarting", no restart is happening

no luck

### Paste Traceback/Error Below (if applicable)

```python-traceback

WARNING:traitlets:kernel died: 18.00057578086853

```

## Versions

* Spyder version:  3.3.3
* Python version: 3.7
* Qt version: 5.9.6
* PyQt version: 1.7  / Q5 5.9.2
* Operating System name/version: Win10

### Dependencies

```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)```

**Comment by ccordoba12** [comment]
> reinstalled conda 5.10 (py3.6), which definitely did work

I don't understand this. Did you mean *Qt* 5.10?

> jupyter qtconsole hands with "kernel died, restarting", no restart is happening

Please post the errors displayed in the system terminal (cmd.exe) you used to start qtconsole.

**Comment by skjerns** [comment]
> I don't understand this. Did you mean Qt 5.10?

No,, I meant installing anaconda3 5.1.0. This by the way did solve my problem after all, to revert to this version with python 3.6.


> Please post the errors displayed in the system terminal (cmd.exe) you used to start qtconsole.

Same as the spyder internal console:
```
WARNING:traitlets:kernel died: 18.00057578086853
```

**Comment by ccordoba12** [comment]
Sorry but without a concrete error message we can't help you.

**Comment by skjerns** [comment]
Okay. As I can work with Anaconda 5.1.0 and Python 3.6, I'll just wait and hope it will be solved in the future releases automagically :)
