### ISSUE TITLE
flash back when I use control+roller to zoom out my Script

### ISSUE THREAD

**Issue by Doongming** [spyder-ide/spyder#9286]
### What steps will reproduce the problem?

First, I edited my script, then it flash back when I use control+roller to zoom out my script. It seems that shortcut key 'control' will clashes with other shortcuts.  

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.2
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-29deepin-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
psutil >=0.3      :  5.4.7 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.2 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by goanpeca** [comment]
Hi @Doongming what do you mean?

Could you explain a bit more or add a screenshot/screencast to better understand the issue?

**Comment by Doongming** [comment]
![flash back](https://user-images.githubusercontent.com/40790658/57345516-b00cf280-717d-11e9-9bf0-b9c024d41abe.gif)
OK, I upload the screencast. And my script. Spyder will flash back when I use 'control+-' or 'control+roller'. 

--------------------------------------------ipython_log.py
import matplotlib.pyplot as plt
from scipy import interpolate
import numpy as np
data1_1 = open('/home/jdm/hccifull/cc-ch-11a.txt', 'r')
data1_2 = open('/home/jdm/hccifull/cc-ci-11a.txt', 'r')
data1_3 = open('/home/jdm/hccifull/ch-ci-11a.txt', 'r')
data1 = open('/home/jdm/hccifull/cc-ch.txt', 'r')
data2 = open('/home/jdm/hccifull/cc-ci.txt', 'r')
data3 = open('/home/jdm/hccifull/ch-ci.txt', 'r')
data4 = open('/home/jdm/hccifull/ch-theta.txt', 'r')
data5 = open('/home/jdm/hccifull/cc-theta.txt', 'r')
data6 = open('/home/jdm/hccifull/ci-theta.txt', 'r')
data7 = open('/home/jdm/hccifull/ch-phi.txt', 'r')
data8 = open('/home/jdm/hccifull/cc-phi.txt', 'r')
data9 = open('/home/jdm/hccifull/ci-phi.txt', 'r')
data10 = open('/home/jdm/hccifull/theta-phi.txt', 'r')

v1d1 = open('/home/jdm/hccifull/ch.txt', 'r')
v1d2 = open('/home/jdm/hccifull/cc.txt', 'r')
v1d3 = open('/home/jdm/hccifull/ci.txt', 'r')
v1d4 = open('/home/jdm/hccifull/theta.txt', 'r')
v1d5 = open('/home/jdm/hccifull/phi.txt', 'r')

Ncc=6;Nci=13;Nch=7;Ntheta=6;Nphi=6;
V_2d_cc_ch=np.zeros((5,Ncc,Nch))
V_2d_cc_ci=np.zeros((5,Ncc,Nci))
V_2d_ch_ci=np.zeros((5,Nch,Nci))
V_2d_theta_ch=np.zeros((5,Ntheta,Nch))
V_2d_theta_cc=np.zeros((5,Ntheta,Ncc))
V_2d_theta_ci=np.zeros((5,Ntheta,Nci))
V_2d_phi_ch=np.zeros((5,Nphi,Nch))
V_2d_phi_cc=np.zeros((5,Nphi,Ncc))
V_2d_phi_ci=np.zeros((5,Nphi,Nci))
V_2d_theta_phi=np.zeros((5,Ntheta,Nphi))

V_2d_cc_ch_11a=np.zeros((Ncc,Nch))
V_2d_cc_ci_11a=np.zeros((Ncc,Nci))
V_2d_ch_ci_11a=np.zeros((Nch,Nci))

#########cc-ch
V=[]
a=Ncc
b=Nch
for num0 in data2.readlines():
     temp=num0.strip().split()
     V.append([float(temp[0]),float(temp[1]),float(temp[2]),])
V=np.array(V)

for num0 in range(3):
  for i in range(a):
    for j in range(b):
      if i%2==0:
        V_2d_cc_ch[2*num0,i,j]=V[i*b+j][num0]
      else:
        V_2d_cc_ch[2*num0,i,j]=V[(i+1)*b-j-1][num0]

V_2d_cc_ch[1]=V_2d_cc_ch[0];V_2d_cc_ch[3]=V_2d_cc_ch[2]



#########cc-ci
V=[]
a=Ncc
b=Nci
for num0 in data3.readlines():
     temp=num0.strip().split()
     V.append([float(temp[0]),float(temp[1]),float(temp[2]),])
V=np.array(V)

for num0 in range(3):
  for i in range(a):
    for j in range(b):
      if i%2==0:
        V_2d_cc_ci[2*num0,i,j]=V[i*b+j][num0]
      else:
        V_2d_cc_ci[2*num0,i,j]=V[(i+1)*b-j-1][num0]

V_2d_cc_ci[1]=V_2d_cc_ci[0];V_2d_cc_ci[3]=V_2d_cc_ci[2]


#########ch-ci
V=[]
a=Nch
b=Nci
for num0 in data1.readlines():
     temp=num0.strip().split()
     V.append([float(temp[0]),float(temp[1]),float(temp[2]),])
V=np.array(V)

for num0 in range(3):
  for i in range(a):
    for j in range(b):
      if i%2==0:
        V_2d_ch_ci[2*num0,i,j]=V[i*b+j][num0]
      else:
        V_2d_ch_ci[2*num0,i,j]=V[(i+1)*b-j-1][num0]

V_2d_ch_ci[1]=V_2d_ch_ci[0];V_2d_ch_ci[3]=V_2d_ch_ci[2]





########
V=[]
a=int(Ntheta/2)
b=Ncc
for num0 in data5.readlines():
     temp=num0.strip().split()
     V.append([float(temp[0]),float(temp[1]),float(temp[2]),float(temp[3]),float(temp[4]),])

V=np.array(V)

for num0 in range(5):   
  for i in range(a):                                                
   for j in range(b):                                                
      if i%2==0:                                                       
        V_2d_cc_theta[num0,i,j]=V[i*b+j][num0]                                    
      else:                                                            
        V_2d_cc_theta[num0,i,j]=V[(i+1)*b-j-1][num0]

**Comment by ccordoba12** [comment]
I still don't understand what the problem is.

**Comment by goanpeca** [comment]
I think the problem is that when using the zooming options (via keyboard or mouse roller) the app quits (segfault?) with all those `painter` errors
