### ISSUE TITLE
Hovers, tooltips and calltips are shown at the wrong position on Linux

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#9287]
I just tested PR #9191 and I'm seeing all those widgets placed incorrectly. Here are a couple of examples:

![Selección_001](https://user-images.githubusercontent.com/365293/57333332-dcdced80-711c-11e9-8150-dead1ee49307.png)

![Selección_002](https://user-images.githubusercontent.com/365293/57333383-f67e3500-711c-11e9-8640-2ef27584ce6f.png)

@goanpeca, please take a look at this one. Thanks!

**Comment by goanpeca** [comment]
Is this Linux?

**Comment by ccordoba12** [comment]
Yep, Kubuntu 18.10
