### ISSUE TITLE
Updating Spyder

### ISSUE THREAD

**Issue by jandyman** [spyder-ide/spyder#9295]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Spyder says 3.3.4 is available, as does "conda search", but update fails

### What steps reproduce the problem?

1.  Try updating from Anaconda navigator. It says there is nothing to update from 3.3.2
2. Try with command line "conda update spyder". Same thing.
3. Try "conda search spyder", and it indicates that 3.3.4 is available.

### What is the expected output? What do you see instead?

I expect to be able to update Spyder. Note that I'm not an expert Conda user

This is a part of what "conda search spyder" returns:

spyder                         3.3.4          py36_0  pkgs/main           
spyder                         3.3.4          py37_0  pkgs/main   

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Please run

    conda install spyder=3.3.4

to see if that helps.

**Comment by jandyman** [comment]
Yes, that works. Can you explain to me _why_ it works but update doesn't, especially since the release instructions say to update? I'm on MacOS Mojave, BTW.

**Comment by ccordoba12** [comment]
I really don't know. I guess some package versions doesn't allow `update` to work as expected.

**Comment by jandyman** [comment]
Probably a good idea to update the instructions then?

**Comment by ccordoba12** [comment]
Yes, I agree.
