### ISSUE TITLE
Autocall prints interpretation 3 times

### ISSUE THREAD

**Issue by rlabbe** [spyder-ide/spyder#9297]
### Issue Report Checklist

* [*] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [*] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [*] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [*] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [*] Tried basic troubleshooting (if a bug/error)
    * [*] Restarted Spyder
    * [*] Reset preferences with ``spyder --reset``
    * [*] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [*] Tried the other applicable steps from the Troubleshooting Guide
* [*] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In Preferences/IPython console I have autocall set to full. When Autocall is invoked, it prints the autocall conversion 3 times before showing the results. 

### What steps reproduce the problem?

1. From the console type
>>> a = 3
>>> type a

### What is the expected output? What do you see instead?
I see
------> type(a)
------> type(a)
------> type(a)
Out[2]: int

Whereas i should see

------> type(a)
Out[2]: int

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 7 

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

**Comment by ccordoba12** [comment]
This is a problem in IPython. Please report it here:

https://github.com/ipython/ipython
