### ISSUE TITLE
About dialog on OSX is too big and bolded

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9298]
The About dialog on mac is looking quite ugly (added the Mac about for comparison)

<img width="1014" alt="Screen Shot 2019-05-08 at 14 56 40" src="https://user-images.githubusercontent.com/3627835/57404420-8b2a7680-71a1-11e9-89f1-b8d368c6ab0e.png">

I will try to improve it

**Comment by ccordoba12** [comment]
Selecting an smaller font size should do it, I'd say.
