### ISSUE TITLE
Spyder forces discrete graphics on OSX

### ISSUE THREAD

**Issue by eagene** [spyder-ide/spyder#9302]
I've found other related issues but have not been able to resolve this issue. I ran conda update spyder and conda update --all. Launching spyder still switches to my discrete graphics.

### Issue Report Checklist

* [X ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [NA ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ X] Tried basic troubleshooting (if a bug/error)
    * [ X] Restarted Spyder
    * [ NA Reset preferences with ``spyder --reset``
    * [X ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [NA ] Tried the other applicable steps from the Troubleshooting Guide
* [X ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Spyder forces discrete graphics on OSX

### What steps reproduce the problem?

1. Launching spyder
2. 
3. 

### What is the expected output? What do you see instead?
No switch to discrete graphics. Switch to discrete graphics. :)

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: Spyder 3.3.4 
* Python version: Python 3.6.6 64-bit
* Qt version: Qt  5.9.6 
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Darwin 18.5.0 

### Dependencies

```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
Please go to

    Preferences > General > Advanced Settings > Rendering engine

and select there `Automatic`. That should fix this problem.

**Comment by eagene** [comment]
This didn’t work for me. It’s still switching. I tried starting both from anaconda navigator and from a command prompt in a python3 conda env and in both cases it switches my GPU and switches back when I exit spyder.

**Comment by ccordoba12** [comment]
Sorry but that's the only thing we do to change that could affect your graphics card. Is there also a switch when after Navigator is started?

**Comment by eagene** [comment]
No, nothing happens when Navigator is started/stopped, only when spyder is then started/stopped. I just tried rebooting and then starting only Spyder - same problem. I triple checked the pref and rendering engine is set to automatic. Anaconda Navigator shows as not requiring high oerf gpu until I starts spyder, then it does.

I'd love to get this working to save my battery life when I'm not powered.

Thanks!
Elizabeth

**Comment by ccordoba12** [comment]
We'll take a look at it after we release Spyder 4, unless @goanpeca has time to do it before that.

**Comment by goanpeca** [comment]
I recall doing something for navigator that in theory should have fixed it, but I think it was not working.

It had to do with a setting of the Spyder OSX app.

**Comment by goanpeca** [comment]
https://bugreports.qt.io/browse/QTBUG-62009
https://developer.apple.com/library/archive/qa/qa1734/_index.html

**Comment by eagene** [comment]
This mac is:
MacBook Pro (Retina, 15-inch, Mid 2015)
AMD Radeon R9 M370X 2 GB
Intel Iris Pro 1536 MB

**Comment by ccordoba12** [comment]
If I understand

https://bugreports.qt.io/browse/QTBUG-62009

correctly, this can be caused by us importing `QtQuick` in `app/mainwindow.py` to set the OpenGL implementation set in our Preferences.

**Comment by Christian-Moore** [comment]
Hello! I encountered the very same issue, and have found what so far seems to be an effective resolution. Just add the following in the info.plist folder inside of the Python app within the Anaconda folder:
`<key>NSSupportsAutomaticGraphicsSwitching</key>
	<true/>`
I've so far found it to work perfectly. I'll say otherwise if that stops being the case.
Here's an informational image:
<img width="617" alt="Screen Shot 2019-11-20 at 2 16 54 PM" src="https://user-images.githubusercontent.com/41198866/69270222-87d86480-0ba0-11ea-8994-ddb033bae45e.png">

**Comment by Christian-Moore** [comment]
Make sure to put a newline between the true part and the Anaconda part.

**Comment by Christian-Moore** [comment]
@eagene Does this work?
@ccordoba12 Are there any potential issues I could be missing here?

**Comment by eagene** [comment]
I only tried a single quick test, but it seems to work!

Thanks so much, Christian.

Elizabeth

**Comment by dknm** [comment]
it's still an issue with Spyder 4.1.4

your code worked a treat - thanks @Christian-Moore

**Comment by ccordoba12** [comment]
> @ccordoba12 Are there any potential issues I could be missing here?

I'm very sorry for jus answering to your question now. I just missed your message. I'm still not sure, but probably there won't be because your change only applies to Spyder.

**Comment by ccordoba12** [comment]
@steff456, please create a pull request with @Christian-Moore's suggestion on this feedstock: https://github.com/conda-forge/python.app-feedstock (don't forget to ping on it too).

Then we'll inform the Anaconda team that they need to apply that patch to their `python.app` package as well.

**Comment by ccordoba12** [comment]
This problem was fixed upstream by @steff456 here:

https://github.com/conda-forge/python.app-feedstock/pull/14

Now users need to wait for her fix to be picked up by Anaconda.
