### ISSUE TITLE
objects arrays currently not supported

### ISSUE THREAD

**Issue by pallaviagrawal1729** [spyder-ide/spyder#9305]
### What steps will reproduce the problem?

In Variable Explorer I am trying to view my variables but its showing an error continuously i.e. objects arrays currently not supported.
The value that my object holds is ndarray object of numpy module

the object description:
x=datasets.iloc[:,:-1].values

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is a known issue and it'll be fixed in Spyder 4, to be released later this year. For now there's nothing we can do about it, sorry.
