### ISSUE TITLE
Receiving error when i try to open table from variable explorer in Spyder3 ide.

### ISSUE THREAD

**Issue by gokhangerdan** [spyder-ide/spyder#9308]
## Description

**What steps will reproduce the problem?**

1. Create a 3 column pandas dataframe with data type: int64 and 60810 rows. (`numerical_data`)
2. fit and transform data using sklearn simple imputer
3. try to open table from variable explorer

**What is the expected output? What do you see instead?**
I should see the table

**Please provide any additional information below**

`from sklearn.impute import SimpleImputer`
`import numpy as np`

`imputer = SimpleImputer(missing_values=np.nan, strategy="most_frequent")`
`imputer = imputer.fit(numerical_data)`
`numerical_data = imputer.transform(numerical_data)`

  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.7
* Qt Versions: 5.9.5, PyQt5 5.10.1 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  0.23.0 (OK)
numpy >=1.7      :  1.16.2 (OK)
sphinx >=0.6.6   :  1.6.7 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.13.3 (OK)
psutil >=0.3     :  5.6.1 (OK)
nbconvert >=4.0  :  5.4.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  0.29.7 (OK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.3.0 (OK)
pylint >=0.25    :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version (3.3.4). Please update.
