### ISSUE TITLE
Some issues with calltips and hovers

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder#9311]
@goanpeca, I noted the following issues the last couple of days:

* `Press Ctrl+I for additional help` is misleading right now because calltips are shown after writing a left parenthesis, and pressing `Ctrl+I` does nothing at that point (as you already noticed). So please remove that message. We'll restore it once you solve issue #9279.

* There's no documentation shown for calltips while it's shown for hovers. Please take a look at what's happening with that. Screenshots:

    ![Selección_005](https://user-images.githubusercontent.com/365293/57453933-eb83eb80-7267-11e9-9bb0-a12ae3dd9b7b.png)

    ![Selección_006](https://user-images.githubusercontent.com/365293/57453975-08b8ba00-7268-11e9-9945-6bfee3950fb6.png)

* The results of pressing `Ctrl+I` next to an object and pressing a hover to get documentation are different. Screenshots attached:

    - `Ctrl+I`
    ![Selección_003](https://user-images.githubusercontent.com/365293/57453799-9a73f780-7267-11e9-9daf-ab4d6fbc2ca3.png)

    - Pressing on hover
    ![Selección_004](https://user-images.githubusercontent.com/365293/57453864-c0999780-7267-11e9-8eb0-f897a72ba889.png)

* The placement of hovers is covering the object name a little bit, so I think they should be placed a little bit below. For example, you can't  correctly read `vectorize` in the screenshot below

    ![Selección_005](https://user-images.githubusercontent.com/365293/57454186-88468900-7268-11e9-88f8-0bba4ea7d1cf.png)

**Comment by goanpeca** [comment]
>Press Ctrl+I for additional help is misleading right now because calltips are shown after writing a left parenthesis, and pressing Ctrl+I does nothing at that point (as you already noticed). So please remove that message. We'll restore it once you solve issue #9279.

Yes indeed, makes sense

>There's no documentation shown for calltips while it's shown for hovers. Please take a look at what's happening with that. Screenshots:

We/you agreed that for the calltips we should not display anything beyond the signature, maybe I should get rid of the `No documentation` available message, cause that is indeed misleading

>The results of pressing Ctrl+I next to an object and pressing a hover to get documentation are different. Screenshots attached:

Yes, I could reproduce it

>The placement of hovers is covering the object name a little bit, so I think they should be placed a little bit below. For example, you can't correctly read vectorize in the screenshot below

Yes I have seen this on windows and linux (not OSX). Hmmm I wonder why is that :-|

**Comment by ccordoba12** [comment]
> We/you agreed that for the calltips we should not display anything beyond the signature

That was to keep PR #9140 in scope. But now that hovers are in place, I like the idea of seeing a sneak peek of the docstring. So please add the same amount of docstring text that's shown in hovers, instead of `No documentation available`

> Yes I have seen this on windows and linux (not OSX).

Maybe you need to define different placement rules per OS?

**Comment by goanpeca** [comment]
>Maybe you need to define different placement rules per OS?

It might have to do with the windows flags also, not sure. If I cannot find a reliable metric, you suggest I use fontmetrics, until it fits, so that zoom in and out are taken into account?

**Comment by ccordoba12** [comment]
Is it not possible to use the same vertical placement rule than for calltips? That's working fine.
