### ISSUE TITLE
Sypder3-git says pyls is missing.

### ISSUE THREAD

**Issue by OverfloError** [spyder-ide/spyder#9314]
### What steps will reproduce the problem?

Install spyder3-git on arch version 3.3.and start it.
The versions:
spyder3-git  3.3.4.r3518.g01720a856-1
python-spyder-kernels-git  1.3.3.r17.g2c5b36c-1

Other installed packages
----------------------------- ----------------
alabaster                     0.7.12          
appdirs                       1.4.3           
asn1crypto                    0.24.0          
astroid                       2.1.0           
atomicwrites                  1.3.0           
autopep8                      1.4.4           
Babel                         2.6.0           
backcall                      0.1.0           
bcrypt                        3.1.6           
bleach                        3.1.0           
btrfsutil                     1.1.0           
CacheControl                  0.12.5          
cffi                          1.12.3          
chardet                       3.0.4           
cloudpickle                   0.8.1           
colorama                      0.4.1           
cryptography                  2.6.1           
cycler                        0.10.0          
Cython                        0.29.7          
decorator                     4.4.0           
defusedxml                    0.6.0           
distlib                       0.2.8           
distro                        1.4.0           
docutils                      0.14            
entrypoints                   0.3             
future                        0.17.1          
gmpy2                         2.1.0a4         
h5py                          2.9.0           
html5lib                      1.0.1           
idna                          2.8             
imagesize                     1.1.0           
ipykernel                     4.9.0           
ipython                       7.5.0           
ipython-genutils              0.1.0           
ipywidgets                    7.4.2           
isort                         4.3.4           
jedi                          0.13.3          
jeepney                       0.4             
Jinja2                        2.10.1          
jsonschema                    2.6.0           
jupyter-client                5.2.4           
jupyter-console               6.0.0           
jupyter-core                  4.4.0           
keyring                       19.0.1          
kiwisolver                    1.1.0           
lazy-object-proxy             1.4.0           
lit                           0.8.0.dev0      
lockfile                      0.12.2          
louis                         3.9.0           
lxml                          4.3.3           
MarkupSafe                    1.1.1           
matplotlib                    3.0.3           
mccabe                        0.6.1           
mistune                       0.8.4           
mpmath                        1.1.0           
msgpack                       0.6.1           
nbconvert                     5.4.0           
nbformat                      4.4.0           
nltk                          3.4.1           
notebook                      5.7.8           
numpy                         1.16.3          
packaging                     19.0            
pandas                        0.24.2          
pandocfilters                 1.4.2           
paramiko                      2.4.2           
parso                         0.4.0           
pep517                        0.5.0           
pexpect                       4.7.0           
pickleshare                   0.7.5           
pip                           19.0.3          
pluggy                        0.11.0          
ply                           3.11            
progress                      1.5             
prometheus-client             0.6.0           
prompt-toolkit                2.0.9           
psutil                        5.6.2           
ptyprocess                    0.6.0           
pyasn1                        0.4.5           
pycodestyle                   2.5.0           
pycparser                     2.19            
pydocstyle                    3.0.0           
pyflakes                      2.1.1           
Pygments                      2.3.1           
PyGObject                     3.32.1          
pylint                        2.2.2           
PyNaCl                        1.3.0           
PyOpenGL                      3.1.0           
pyparsing                     2.4.0           
PyQt5                         5.12.2          
PyQt5-sip                     4.19.17         
python-dateutil               2.8.0           
python-jsonrpc-server         0.1.2           
python-language-server        0.26.1          
pytoml                        0.1.20          
pytz                          2019.1          
pyzmq                         18.0.1          
QDarkStyle                    2.6.8           
QtAwesome                     0.5.7           
qtconsole                     4.4.3           
QtPy                          1.7.0           
Reflector                     2019.3.8.1.54.39
requests                      2.21.0          
retrying                      1.3.3           
rope                          0.12.0          
scipy                         1.2.1           
SecretStorage                 3.1.1           
Send2Trash                    1.5.0           
setuptools                    41.0.1          
simplegeneric                 0.8.1           
sip                           4.19.17         
six                           1.12.0          
snowballstemmer               1.2.1           
Sphinx                        2.0.1           
sphinxcontrib-applehelp       1.0.1           
sphinxcontrib-devhelp         1.0.1           
sphinxcontrib-htmlhelp        1.0.1           
sphinxcontrib-jsmath          1.0.1           
sphinxcontrib-qthelp          1.0.2           
sphinxcontrib-serializinghtml 1.1.3           
spyder                        4.0.0.dev0      
spyder-kernels                1.4.0.dev0      
sympy                         1.4             
team                          1.0             
terminado                     0.8.1           
testpath                      0.4.2           
tornado                       5.1.1           
traitlets                     4.3.2           
urllib3                       1.24.2          
wcwidth                       0.1.7           
webencodings                  0.5.1           
widgetsnbextension            3.4.2           
wrapt                         1.11.1          
wurlitzer                     1.0.2           
yapf                          0.27.0        

## Versions

* Spyder version: 4.0.0.dev0 
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Linux 5.0.13-zen1-1-zen

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
psutil >=0.3       :  5.6.2 (OK)
pyls >=0.19.0;<0.25:  0.26.1 (NOK)
nbconvert >=4.0    :  5.4.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.3 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.7 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.2.2 (OK)
```

**Comment by ccordoba12** [comment]
> python-language-server 0.26.1

This is the problem. Please downgrade to **0.24** (and inform Arch maintainers about it). The reasoning is explained in PR #9310.
