### ISSUE TITLE
"Run" should always execute main project .py

### ISSUE THREAD

**Issue by nerdfever** [spyder-ide/spyder#9315]
## Problem Description

When you have a project open, choosing "Run" (from the menu, shortcut key, or big green button) ought to execute the top-level .py file in the project.

For example, in my current project, I usually have 3 files open in the editor - my main file ("video83.py") and two library files the main file imports ("nerdlib.py" and "nerdlib_video.py")

See the screenshot below.

![image](https://user-images.githubusercontent.com/9833299/57470571-24679480-7257-11e9-99b9-2673490db0ac.png)

Right now, if I click "Run", whichever file is currently in the foreground of the editor executes.

That's fine, and expected behavior if I _don't_ have a project open.

But if I _do_ have a project open, I should be able to specify in the project which file will execute when I click "Run".

Because executing the wrong file (forgot to click correct editor tab before hitting "Run") wastes a lot of time while a new kernel loads and executes.

(It would be fine to also have an additional menu option "Run file being edited" that would perform the current behavior.)

### What steps reproduce the problem?

1. Setup a project
2. Open multiple .py files in editor
3. Click run

### What is the expected output? What do you see instead?

I expect that my main project .py file will run.

Instead, whichever file is in the foreground of the editor runs.

## Versions

* Spyder version: 3.3.1
* Python version: 3.7
* Operating System name/version: Win10 Pro x64

**Comment by ccordoba12** [comment]
Thanks for reporting. This is a known issue and we'll fix it in Spyder 4.
