### ISSUE TITLE
Attribute error: Object has no attribute 'speak'

### ISSUE THREAD

**Issue by Ram-Kishore** [spyder-ide/spyder#9316]
## Description

**What steps will reproduce the problem?**

1. remove pyttsx, pyttsx3 and win32com module
2. and reinstall win32com.client
3. 

**What is the expected output? What do you see instead?**
code should run with no error, but i see attribute error

**Please provide any additional information below**
it was working fine untill i was installing pyttsx3 module. but code show error after installation of this module.

## Version and main components

* Spyder Version: 3.5
* Python Version: 3.7
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.3.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.9.0 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.24.1 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

**Comment by ccordoba12** [comment]
> it was working fine untill i was installing pyttsx3 module. but code show error after installation of this module.

Sorry, this is not a place to get help about general Python problems but to inform about Spyder bugs. Therefore, I'm closing this issue.
