### ISSUE TITLE
unable to view confusion matrix in variable explorer

### ISSUE THREAD

**Issue by shivspidy** [spyder-ide/spyder#9319]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "E:\anaconda\lib\site-packages\spyder\widgets\variableexplorer\collectionseditor.py", line 455, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "E:\anaconda\lib\site-packages\spyder\widgets\variableexplorer\arrayeditor.py", line 606, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.0 
* Python Version: 3.6.8
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.1.1 (OK)
pycodestyle >=2.3:  2.5.0 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  0.24.2 (OK)
numpy >=1.7      :  1.16.2 (OK)
sphinx >=0.6.6   :  2.0.1 (OK)
rope >=0.9.4     :  0.14.0 (OK)
jedi >=0.9.0     :  0.13.3 (OK)
nbconvert >=4.0  :  5.5.0 (OK)
sympy >=0.7.3    :  1.4 (OK)
cython >=0.21    :  0.29.7 (OK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.5.0 (OK)
pylint >=0.25    :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.4
