### ISSUE TITLE
Spyder submenus appear to be farther below menu in a second monitor

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#932]
_From [changyg2...@gmail.com](https://code.google.com/u/110752828996715276496/) on 2012-02-08T00:26:39Z_

What steps will reproduce the problem?

 1.Attach a second monitor to laptop (Dell Inspiron 1520)
2.open Spyder
3.click on the File menu and the submenus show up in a position farther from File. What is the expected output? What do you see instead? I expect to see the submenus appear just below the File menu.
Instead, I see they are farther down from File. What version of the product are you using? On what operating system? Spyder 2.1.6.
Fedora 16 

Please provide any additional information below

. An interesting thing is the distance from submenu and menu increase as the window size is increased.
The same problem occurs with Oracle VirtualBox menus.
Is this a problem with Spyder or with the second monitor (Fedora is handling properly?)

Thanks.

I love Spyder. Thanks for the great work.

**Attachment:** [Spyder_submenu_off_in_the_second_monitor_20120207.png](http://code.google.com/p/spyderlib/issues/detail?id=932)

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=932_

**Comment by spyder-issues-migrator** [comment]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2013-05-25T06:50:04Z_

Hello, I got the same kind of bug report from a Debian user http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=709782 do you know if tis problem is qt4 or window manager related ?

**Comment by spyder-issues-migrator** [comment]
_From [changyg2...@gmail.com](https://code.google.com/u/110752828996715276496/) on 2013-05-25T07:53:10Z_

Hi,

The problem is automatically fixed after I upgrade Fedora to 17. Thanks for
debugging.

Best,
YG

**Comment by spyder-issues-migrator** [comment]
_From [pi...@synchrotron-soleil.fr](https://code.google.com/u/111976521841338120241/) on 2013-05-25T10:24:56Z_

Yes it seems that this is a gnome problem, which version are you using ?

**Comment by spyder-issues-migrator** [comment]
_From [changyg2...@gmail.com](https://code.google.com/u/110752828996715276496/) on 2013-05-25T10:56:26Z_

Hi,

I am using spyder-2.1.13-3.fc17.

More details:
"""
Spyder 2.1.13
Python code real-time analysis is powered by pyflakes 0.5.0 and other code
introspection features are powered by rope 0.9.4

Python 2.7.3 64bits, Qt 4.8.4, PyQt4 (API v1) 4.10.1 on Linux.
'"""

By the way, Spyder is great. Thanks to you guys' hard work.

I have one question or feature request:

In Spyder, Ctrl+Space will show the available variables for ease of
auto-completion. Do you know if there is a way Spyder can show available
variables as I type?

Best,
YG




Best,
Yonggang

**Comment by goanpeca** [comment]
This seems fixed already.. @ccordoba12?

**Comment by ccordoba12** [comment]
I think. The reported Spyder version is quite old :-)
