### ISSUE TITLE
Can't view the variable from variable explorer

### ISSUE THREAD

**Issue by gaurav16gupta** [spyder-ide/spyder#9329]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 449, in createEditor
    if not editor.setup_and_check(value, title=key, readonly=readonly):
  File "/usr/lib/python3/dist-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 619, in setup_and_check
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

## Version and main components

* Spyder Version: 3.2.6 
* Python Version: 3.6.7
* Qt Versions: 5.12.1, PyQt5 5.12 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  2.1.1 (OK)
pycodestyle >=2.3:  2.5.0 (OK)
pygments >=2.0   :  2.3.1 (OK)
pandas >=0.13.1  :  0.24.0 (OK)
numpy >=1.7      :  1.16.3 (OK)
sphinx >=0.6.6   :  1.8.4 (OK)
rope >=0.9.4     :  0.12.0 (OK)
jedi >=0.9.0     :  0.13.3 (OK)
psutil >=0.3     :  5.5.1 (OK)
nbconvert >=4.0  :  5.4.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.4.3 (OK)
IPython >=4.0    :  7.3.0 (OK)
pylint >=0.25    :  2.3.0 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.4
