### ISSUE TITLE
RuntimeError after closing a split editor

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9341]
### What steps will reproduce the problem?

1. open and close a split editor
2. ?
3. Get the error

### Traceback
```python-traceback
    self.process_code_analysis(params['params'])
    self.cleanup_code_analysis()
    self.setUpdatesEnabled(False)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

Traceback (most recent call last):
    msg = self.format(record)
    return fmt.format(record)
    record.message = record.getMessage()
    msg = msg % self.args
ValueError: incomplete format
Call stack:
    start.main()
    mainwindow.main()
    mainwindow = run_spyder(app, options, args)
    app.exec_()
    handler(resp['params'])
    {'params': diagnostics})
    handler(params)
    self.log_lsp_handle_errors("Error when processing linting")
    logger.error('%', 1, stack_info=True)
Arguments: (1,)
Traceback (most recent call last):
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/lsp/client.py", line 249, in on_msg_received
    handler(resp['params'])
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/lsp/providers/document.py", line 51, in process_document_diagnostics
    {'params': diagnostics})
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 805, in handle_response
    self.lsp_response_signal.emit(method, params)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted
```

## Versions

* Spyder version: 4.0.0.dev0 45efb0945
* Python version: 3.7.3
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Darwin 18.5.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.5 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.25.0 (NOK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.5.0.dev0 (OK)
IPython >=4.0      :  7.3.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Ok, I understand the error now. It happens when you close the splitted panel before linting results arrive from the PyLS.

@andfoy, please take a look at this one. We should unregister the CodeEditor instance that gets removed, right? (well, you know better).

Please focus on solving this one as soon as possible so we can have it as part of beta2.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, I think issue #9325 should be merged with this one.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Yes, it would seem one of them should be merged with the other. #9325 has much more extensive detail and documentation of the problem, including all relevant logs and environment information, and has seniority, but this issue has a longer actual traceback and is more focused on what the actual problem appears to be. Your call which to keep as the canonical one.

**Comment by CAM-Gerlach** [comment]
BTW, thanks @impact27 for helping narrow this tricky issue down.

**Comment by ccordoba12** [comment]
I know that #9325 has more info but it lacks the critical part of the traceback posted by @impact27. So I'm closing it in favor of this one.

**Comment by impact27** [comment]
completions = params['params']
    block.setUserData(data)
    cursor.setPosition(block2.position(), QTextCursor.KeepAnchor)
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted

Traceback (most recent call last):
    msg = self.format(record)
    return fmt.format(record)
    record.message = record.getMessage()
    msg = msg % self.args
ValueError: incomplete format
Call stack:
    start.main()
    mainwindow.main()
  File "/Users/quentinpeter/pyscripts/spyder/spyder/app/mainwindow.py", line 3502, in main
    else:
    handler(resp['params'])
    {'params': diagnostics})
    # We need this because logger.error activates our error
    completion_list = sorted(completions,
    self.enable_hover = config['hoverProvider']
Arguments: (1,)
Traceback (most recent call last):
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/lsp/client.py", line 249, in on_msg_received
    handler(resp['params'])
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/lsp/providers/document.py", line 51, in process_document_diagnostics
    {'params': diagnostics})
  File "/Users/quentinpeter/pyscripts/spyder/spyder/plugins/editor/widgets/codeeditor.py", line 809, in handle_response
    # to get the entire stack info generated by it, which
RuntimeError: wrapped C/C++ object of type CodeEditor has been deleted
