### ISSUE TITLE
File not saved when calling runfile from console

### ISSUE THREAD

**Issue by impact27** [spyder-ide/spyder#9342]
### What steps will reproduce the problem?

When pressing the green "Run file" arrow, the file is automatically saved. It would be cool if the same appened when I type `runfile('file.py')` in the console.

## Versions

* Spyder version: 4.0.0.dev0 f1daab7a4
* Python version: 3.7.3
* Qt version: 5.9.1
* PyQt5 version: 5.9
* Operating System: Darwin 18.5.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.5 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.25.0 (NOK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.5.0.dev0 (OK)
IPython >=4.0      :  7.3.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
We really need to add Comms to qtconsole to expand the things we can do between the Spyder interface and the kernel.

Trying to do something else is brittle and hacky.
