### ISSUE TITLE
Spyder stops running - no error message

### ISSUE THREAD

**Issue by joesoap99** [spyder-ide/spyder#9346]
### What steps will reproduce the problem?

I have a script which normally takes 20 minutes to run.
The first time I run it Spyder stops processing after about 5 minutes. No error message.

I stop the kernal, open a new one and the script runs fine to the end.

This happens every time I run the script.

Anaconda Spyder, Python 3.7, Spyder 3.3.4

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.3 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.7 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by joesoap99** [comment]
It is a single script file which I run for different dates.
The code works perfectly on the second run. Every time it stops part way through on the first run of the kernel.

I do not see how it can be anything to do with the code.
If it were the code, then some sort of error message would be given.

**Comment by ccordoba12** [comment]
I also don't understand how this is related to Spyder if the problem only appears with a single file and not with all of them.

Is that a file you simple enough you can share?

**Comment by joesoap99** [comment]
This particular file runs for 20 minutes. My other scripts run in less than a minute so are not relevant.
File is 2000 lines long, is confidential, so not suitable for sharing.
It is unlikely to be anything to do with the file as it runs perfectly on very subsequent run except the first.

**Comment by ccordoba12** [comment]
Ok, I understand. But without further details is impossible for us to help you, so I'm going to close this one.

If you manage to isolate the problem, please let is know.
