### ISSUE TITLE
Breakpoint placement bug

### ISSUE THREAD

**Issue by kaitokuShimizu** [spyder-ide/spyder#9347]
### What steps will reproduce the problem?

Breakpoints are incorrectly placed if there are collasped functions above.
(Breakpoint labelled with '*' beside line number)

 1>> def myfunc1(): # Collasped
 
 5>> def myfunc2():
 6>>     x = [0, 1, 2, ,3 , 4] # Arbitary Code
*7>>     x[0] = 2              # Desired break
 8>>     print(x[1])           # Arbitary Code

The ide will not register this breakpoint location correctly. Instead it will think that the breakpoint is above the current line as if myfunc1 has not been collasped. In the above example, since myfunc1 is 4 lines long, the breakpoint will be registered at line 3 instead.

## Versions

* Spyder version: 4.0.0b1 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.0 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.11.0     :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.7 (OK)
qtconsole >=4.2.0 :  4.4.4 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll take a look at this for beta3.

**Comment by ccordoba12** [comment]
@steff456 looked at this and found that it's no longer a problem in beta2. So please update.
