### ISSUE TITLE
Autocomplete only works when ran as root

### ISSUE THREAD

**Issue by lynxloco** [spyder-ide/spyder#9350]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Autocomplete in the IDE only works when ran as root. The console works fine.

### What steps reproduce the problem?

1. Open spyder as a non-root user
2. Type "imp" and press tab
3. "imp" isn't autocompleted to import

### What is the expected output? What do you see instead?
That spyder correctly autocompletes the typed statement, as it does when spyder is ran as root.

## Versions

* Spyder version: 3.3.4
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt version: 5.12.2
* Operating System name/version: Ubuntu 19.04, Linux 5.0.0

### Dependencies

IPython >=4.0     :  7.5.0 (OK)
cython >=0.21     :  0.29.7 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.3 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.5.1 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.10.5 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.4 (OK)

**Comment by ccordoba12** [comment]
Sorry, this looks like an installation issue. We recommend you to use Anaconda instead or wait until Spyder 4, which will have much better code completion facilities.
