### ISSUE TITLE
image to string converion error

### ISSUE THREAD

**Issue by muhammadahmad1997** [spyder-ide/spyder#9351]
![aaaa](https://user-images.githubusercontent.com/48186350/57886865-9fc4d980-7847-11e9-941a-736ed5cf0dee.PNG)
i am trying to run a single python file and trying to convert the image to text (image is placed in same folder where the python file is )

from PIL import Image
from tesseract import image_to_string
print (image_to_string(Image.open('cc.png')))
print ( image_to_string(Image.open('cc.jpg'), lang='eng'))

this is the code and i hav alot of errors 

![ababa](https://user-images.githubusercontent.com/48186350/57887027-f500eb00-7847-11e9-89a0-79a8c35a97d3.PNG)

**Comment by bcolsen** [comment]
This seems to be a problem with your tesseract installation and not with Spyder

It seems that you somehow installed the python 2 version of tesseract on your python 3 version of anaconda
