### ISSUE TITLE
Help Panel: LaTeX rendering is unreadable when using dark theme

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#9357]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When a docstring renders LaTeX as part of its body, it is rendered on black by default, this causes readability problems when the dark theme is used, as it is not possible to read the rendered formulas.

### What steps reproduce the problem?

1. Import torch
2. Request help for ```torch.nn.AdaptiveAvg2D``` using help shortcut

### What is the expected output? What do you see instead?
![imagen](https://user-images.githubusercontent.com/1878982/57953448-b43fbb00-78b5-11e9-91dc-0b2c64c6a3fe.png)

## Versions

* Spyder version: 4.0 beta2
* Python version:  3.7
* Qt version: 5.9
* PyQt version: 5.9
* Operating System name/version: Ubuntu 18.04

**Comment by stonebig** [comment]
maybe change back the default to non-dark ?

**Comment by andfoy** [comment]
@stonebig We should be able to render LaTeX, regardless of the theme used

**Comment by ccordoba12** [comment]
@andfoy, please take a look at this one. We need to add a more recent version of MathJax, and for that please copy/paste its latest stable release to `plugins/help/utils/js/mathjax`, then add a CSS rule in `plugins/help/utils/static/dark_css/default.css` to change the color of its divs to white.

**Comment by ccordoba12** [comment]
Actually, let's leave this one to @steff456.
