### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by gabrielraya** [spyder-ide/spyder#9358]
**Spyder does not display Image numpy array.** 
I used SimpleITK library to convert raw data images to numpy arrays, then I tried to open this to inspect the values but I got this error from Spyder.
![error](https://user-images.githubusercontent.com/15808937/57968054-dbee5c00-7965-11e9-9a09-1015c6a6c78a.PNG)

This worked yesterday but as I run spyder with a set environment from git bash, 
i got this errro, maybe is because I am running Spyder from git bash but that should not be a problem.
In git bash I got this error

> QQuickWidget: Cannot render due to failing makeCurrent()

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.4

**Comment by gabrielraya** [comment]
It didn't work!

**Comment by ccordoba12** [comment]
>  I update spyder as you said, then I activated again my environment, and run spyder but it did not work! I checked this by using the default environment and it worked

If you have Spyder installed in you environment, you also need to update it there.
