### ISSUE TITLE
Some issues with the Plot viewer

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9367]
## Problem Description

I will group a couple of issues I see currently with the `Plots` pane:

1. Images on retina displays look distorted. (maybe this thread helps https://gist.github.com/minrk/3301035)
2. There seems to be some horizontal scrolling with the list of images to the right:
![problem1](https://user-images.githubusercontent.com/3627835/57983399-fdf3e700-7a16-11e9-820e-c83ebd9bdcc3.gif)
3. The down arrow should allow moving between images, instead it only move the list downwards
![problem2](https://user-images.githubusercontent.com/3627835/57983424-457a7300-7a17-11e9-8598-a5afcd20e188.gif)

**Comment by goanpeca** [comment]
Thoughts @jnsebgosselin :-) ?

**Comment by goanpeca** [comment]
@jnsebgosselin any thoughts here?

**Comment by jnsebgosselin** [comment]
I @goanpeca. Thanks for taking the time to report these issues.

> Images on retina displays look distorted.

I will try to take a look at this. However I don't have access to a Mac. Is this doing this also with any high resolution monitors?

> There seems to be some horizontal scrolling with the list of images to the right

I will take care of this, I know what needs to be done.

> The down arrow should allow moving between images, instead it only move the list downwards

I don't know about this. The down/up arrows act like scrollbar buttons, so it makes sense to me that clicking on them doesn't change the current selected image.

This is similar to the caret not changing line when we use the arrows on the Editor's vertical scrollbar. 

Besides, There is already the `Previous Figure` and `Next Figure`  buttons and their associated shortcut to navigate/cycle through the images.

But that being said, if you still think it is a change that should be implemented, I can do it.

**Comment by jnsebgosselin** [comment]
> Images on retina displays look distorted.

@goanpeca is this related to this https://github.com/spyder-ide/spyder/issues/9148?

**Comment by goanpeca** [comment]
Yes, I think they are related

**Comment by RIM-LLC** [comment]
I'm also having what appears to be an issue with the quality of the images plotted on the Plots window. See on the image below that the letters on the charts are blurry. If I save the image using the "Save" icon on the navigation bar, the quality is OK. This image was a snap from a 4K monitor (Windows 10). Note that I have "Enable auto high DPI scaling" checked (which indeed helped with the size of menus, icons, etc).
![Annotation 2019-11-11 145755](https://user-images.githubusercontent.com/57544001/68617995-64bdfe80-0496-11ea-95ed-2a9c392cab43.jpg)

**Comment by ccordoba12** [comment]
@RIM-LLC, solving the problem you mention in the Plots pane is harder than you think (although it seems simple). We need to detect the screen resolution programatically and inform the IPython console if it's high or low res for it to adjust the plots size.

We'll try to address that for version 4.1, to be released in January 2020.

**Comment by gerazov** [comment]
Another issue that could be fixed is for the Plots pane to remember the last folder for saving, so you don't have to navigate down the same path on every save. Currently it opens the current working directory.

**Comment by goanpeca** [comment]
You are right! @gerazov could you open a new issue with this suggestion?

Makes it easier to track and fix :-)

**Comment by gerazov** [comment]
Sure :smile: I wanted to - but then found this misc thread ...

**Comment by RIM-LLC** [comment]
@gerazov - would you mind adding on the suggestions, something like the following: 

Generate a date/time-based filename (so we don't need to rename each picture we want to save if saving multiple figures).  Look at the picture below to see how Snip & Sketch generates a date/time-based file name:

![Annotation 2019-11-27 105138](https://user-images.githubusercontent.com/57544001/69738377-046cc500-1104-11ea-83b1-21b31ee6ad45.jpg)

**Comment by gerazov** [comment]
I like the idea - but @goanpeca should this be a new issue?

**Comment by goanpeca** [comment]
>but @goanpeca should this be a new issue?

Yes, I would make it a new issue

**Comment by RIM-LLC** [comment]
OK - I will open a new issue. Tks

**Comment by prof7bit** [comment]
I would love to see a proper standard scroll bar and get rid of the up/down buttons. If a lot of plots have been accumulated during the day it is very hard to scroll this list.

**Comment by jnsebgosselin** [comment]
> 
> 
> I would love to see a proper standard scroll bar and get rid of the up/down buttons. If a lot of plots have been accumulated during the day it is very hard to scroll this list. The save- and delete-icons could be moved into the context menu to remove needless clutter from the UI. Arrow up/down keys should move the selection and not scroll the list. A normal list widget with standard mouse and keyboard behavior would do a better job and would be less confusing.

After playing with the plot plugin for some time now, I agree with this. @goanpeca what do you think?

The current implementation that I made was based on [Rodeo](https://rodeo.yhat.com/) design, but I think this is not ideal.

**Comment by goanpeca** [comment]
I agree! Go for it

**Comment by jnsebgosselin** [comment]
> 
> 
> I agree! Go for it

Master or 4.x branch?

**Comment by goanpeca** [comment]
@ccordoba12 ?

**Comment by ccordoba12** [comment]
4.x is fine for me because it solves very important usability issues.

**Comment by goanpeca** [comment]
So should we close this one @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
It is your call.

Is the problem with high retina still a thing? I guess so, but I think this problem should be tracked in its own issue.

**Comment by goanpeca** [comment]
Yeah let's close it and handle the retina thing on a separate one. We have one? otherwise could you open it :-) ? 

Thanks!

**Comment by Rational-IM** [comment]
FYI - I still see blurry images (on my 4K monitor) on the current version (4.0.1). Maybe plotting high-resolution charts was already addressed. Also, the "scroll-bars" suggested above would be welcome. Even better if arrows up/down would show different plots (vs. only moving the plots up/down on the scrollbar).

**Comment by jnsebgosselin** [comment]
> Yeah let's close it and handle the retina thing on a separate one. We have one? otherwise could you open it :-) ?
> 

Yes I think the issue is tracked in Issue https://github.com/spyder-ide/spyder/issues/9148

I'm pretty sure there is nothing that can be done on the Plots plugin side about this issue though. The Plots plugin renders what he receives. I think this needs to be fix upstream in the console.

**Comment by jnsebgosselin** [comment]
> 
> FYI - I still see blurry images (on my 4K monitor) on the current version (4.0.1). Maybe plotting high-resolution charts was already addressed.

Thanks for the confirmation.

> Also, the "scroll-bars" suggested above would be welcome. Even better if arrows up/down would show different plots (vs. only moving the plots up/down on the scrollbar).

This will land in next version, please see PR https://github.com/spyder-ide/spyder/pull/11576
