### ISSUE TITLE
Resizing plot panes does not resize the content

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9368]
I suggest that when panes are resized the content adapts to the new size. This is not currently the case for the Plots pane

![problem3](https://user-images.githubusercontent.com/3627835/57983466-d05b6d80-7a17-11e9-9a1e-745da82f8667.gif)

**Comment by ccordoba12** [comment]
This could be possible if we switch from Png to Svg for the default Inline backend format.

**Comment by jnsebgosselin** [comment]
I'll take care of this, thanks for filling an issue about this.

**Comment by jnsebgosselin** [comment]
Also making svg defaults is not a good idea IMO, but I'm not sure this is related to the current issue.
