### ISSUE TITLE
4.0b2 error

### ISSUE THREAD

**Issue by adaaaaaa** [spyder-ide/spyder#9374]
`/home/captain/.local/lib/python3.7/site-packages/qtpy/__init__.py:211: RuntimeWarning: Selected binding "pyqt5" could not be found, using "pyside2"
  'using "{}"'.format(initial_api, API), RuntimeWarning)
Traceback (most recent call last):
  File "/home/captain/.local/bin/spyder3", line 10, in <module>
    sys.exit(main())
  File "/home/captain/.local/lib/python3.7/site-packages/spyder/app/start.py", line 190, in main
    from spyder.app import mainwindow
  File "/home/captain/.local/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 51, in <module>
    requirements.check_qt()
  File "/home/captain/.local/lib/python3.7/site-packages/spyder/requirements.py", line 42, in check_qt
    package_name, required_ver = qt_infos[qtpy.API]
KeyError: 'pyside2'`

i have both pyside2 and pyqt5 installed...and 4.0b1 worked fine...
Why 4.0b2 came out this error message?

**Comment by ccordoba12** [comment]
> RuntimeWarning: Selected binding "pyqt5" could not be found

This says it all: qtpy couldn't find pyqt5 in your system and switch to pyside2, but Spyder can't work with pyside2.

Please uninstall pyside2 and try again.

**Comment by adaaaaaa** [comment]
after the error...first , i search the package i found no pyside2,
then i install it and still error
then i upgrade pyqt5 to 5.12.2 still error
then i uninstall pyside2 still error
then i reinstall spyder4.0b2 still error...all error is the same... @ccordoba12

**Comment by ccordoba12** [comment]
Do you have pyqtwebengine installed as well?

**Comment by adaaaaaa** [comment]
@ccordoba12  yes...

**Comment by ccordoba12** [comment]
Sorry, I'm out of ideas. Last two recommendations:

1. Remove everything in `/home/captain/.local/lib/python3.7/` and use a clean virtualenv instead (if you don't remove the first directory, you can't use a clean virtualenv, I think).
2. Use Anaconda instead (which is our recommended and supported method of installation).

**Comment by adaaaaaa** [comment]
after remove spyder4.0b2 and pyqt5...i can launch a buggy 4.0b1...
then i install 4.0b2...and it become a buggy spyder... @ccordoba12 
![spyder](https://user-images.githubusercontent.com/23206387/58059413-4dfdb580-7b9f-11e9-9eb3-98255f893c7c.png)
it's stuck a thread and eating more and more memory...my cpu is 6cores 12threads...
and in terminal i get one line warning: [W 08:02:04.187 NotebookApp] WebSocket ping timeout after 90000 ms.

**Comment by ccordoba12** [comment]
If you're using Spyder
