### ISSUE TITLE
Unable to see suggestions if I us backspace till .

### ISSUE THREAD

**Issue by sunn-e** [spyder-ide/spyder#9375]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
when I use backspace, for example, if I type `tf.xyz' and I use backspaces till `.` symbol, I no longer get suggestion unless I go back one more backspace and retype `.` and rest i.e. `.xyx` then only I will get suggestions. This gets very annoying when a spelling mistake happens and I have to go back all the way till `.` symbol. 

### What steps reproduce the problem?

1. type anything like eg `right_side = tf.strib`
2. now hit a back space since we wanted to type `strided_slice` and not `strided_slice`
3. Correct it  and go on, `right_side = tf.strid` and you will notice no longer suggestion pops up.
4. You have to backspace till `.` gets deleted. if you again type, you will get pop up as usual.

### What is the expected output? What do you see instead?
It should pop up even if I do backspace on wrong names.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.4
* Python version: 3.7
* Qt version: 4.4.4
* PyQt version: 
* Operating System name/version: win 10 build 17763.rs5_release.180914-1434 in test mode

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We're working to solve this in Spyder 4.
