### ISSUE TITLE
Additions to PYTHONPATH are not working in recent versions of macOS

### ISSUE THREAD

**Issue by jandyman** [spyder-ide/spyder#9388]
### Issue Report Checklist

* [] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Dylib won't load unless in working folder, regardless of PYTHONPATH setting.

### What steps reproduce the problem?

1. Try to use PYTHONPATH manager to point to folder containing a dylib referenced by an so. Doesn't work.
2. Copy the library to the working folder. It works.

### What is the expected output? What do you see instead?

Expected PYTHONPATH manager to allow the dependent dylib to live in its original location

### Paste Traceback/Error Below (if applicable)

ImportError: dlopen(/Users/andy/Dropbox (Personal)/Developer/boost_1_70_0/libs/python/example/tutorial/hello_ext.so, 2): Library not loaded: libboost_python37.dylib
  Referenced from: /Users/andy/Dropbox (Personal)/Developer/boost_1_70_0/libs/python/example/tutorial/hello_ext.so
  Reason: image not found

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.4
* Python version: 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: Mac OS Mojave

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
I think this doesn't depend on PYTHONPATH but on PATH instead. Could you try changing PATH and see what happens? Thanks!

**Comment by jandyman** [comment]
It doesn't help. Here's what I did (below). Before doing this, I copied lib boost_python37.dylib to /Users/Andy.

import os
print(os.environ['PATH'])
os.environ['PATH'] += ':/Users/andy'
os.environ['DYLD_LIBRARY_PATH'] = '/Users/andy'
print(os.environ['PATH'])
print(os.environ['DYLD_LIBRARY_PATH'])
import hello_ext

output:
 
/Users/andy/anaconda3/bin:/Users/andy/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
/Users/andy/anaconda3/bin:/Users/andy/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/andy
/Users/andy
Traceback (most recent call last):

  File "<ipython-input-1-a9df7f24794e>", line 7, in <module>
    import hello_ext

ImportError: dlopen(/Users/andy/Dropbox (Personal)/Developer/boost_1_70_0/libs/python/example/tutorial/hello_ext.so, 2): Library not loaded: libboost_python37.dylib
  Referenced from: /Users/andy/Dropbox (Personal)/Developer/boost_1_70_0/libs/python/example/tutorial/hello_ext.so
  Reason: image not found

Somehow, the boost.python test scripts get this to work, but it automatic and hidden and I need to figure out how to use boost.python in my "real world" (i.e. Spyder). It's very mysterious why this doesn't seem to work.

**Comment by jandyman** [comment]
It may be that the Mac OS SIP (System Intregrity Protection) is preventing these older environment variables to work. I got that feedback on the Python C++ sig. Based on that feedback, I found a tool called install_name_tool and used it to modify hello_ext.so to point to the actual location. That works well, so at least I have a path forward with boost.python.

**Comment by ccordoba12** [comment]
Ok, thanks for letting us know.

**Comment by ccordoba12** [comment]
Closing because I don't think we could handle a use case like this one in our Pythonpath manager.
