### ISSUE TITLE
Problem with spyder update

### ISSUE THREAD

**Issue by pgr123** [spyder-ide/spyder#9389]
> Good morning,
>
> I use Spyder for many years but I have now a big problem. Spyder says me there is a new version 4.0.0b2, so I tried to install it with easy_install -U spyder and then I got an error : (I use Ubuntu MATE 18.04 64 bits with Python 2.7)
> pascal@EL1352:~$ sudo easy_install -U spyder
> [sudo] Mot de passe de pascal :
> Searching for spyder
> Reading https://pypi.org/simple/spyder/
> Downloading https://files.pythonhosted.org/packages/f4/cb/600529b54ec0a4e4c75419fb6c3f7370f86e712828805afecedd2ca38ae7/spyder-4.0.0b2-py2-none-any.whl#sha256=e0d4da156594fba9f41c0b45842d0efd693338da3ddc0a671d44a0063a082657
> Best match: spyder 4.0.0b2
> Processing spyder-4.0.0b2-py2-none-any.whl
> Installing spyder-4.0.0b2-py2-none-any.whl to /usr/local/lib/python2.7/dist-packages
> writing requirements to /usr/local/lib/python2.7/dist-packages/spyder-4.0.0b2-py2.7.egg/EGG-INFO/requires.txt
> Removing spyder 4.0.0b1 from easy-install.pth file
> Adding spyder 4.0.0b2 to easy-install.pth file
> Installing spyder script to /usr/local/bin
>
> Installed /usr/local/lib/python2.7/dist-packages/spyder-4.0.0b2-py2.7.egg
> Processing dependencies for spyder
> Searching for qtawesome>=0.5.7
> Reading https://pypi.org/simple/qtawesome/
> Downloading https://files.pythonhosted.org/packages/d8/7f/762f452eef57daf382fc8c16e65026269a96e2f326e4b475008a9adca9de/QtAwesome-0.5.7-py2.py3-none-any.whl#sha256=cf221d54ccdc3eb6c34728f26aea409633d043360640ffff0db791c11a852c5c
> Best match: QtAwesome 0.5.7
> Processing QtAwesome-0.5.7-py2.py3-none-any.whl
> Installing QtAwesome-0.5.7-py2.py3-none-any.whl to /usr/local/lib/python2.7/dist-packages
> writing requirements to /usr/local/lib/python2.7/dist-packages/QtAwesome-0.5.7-py2.7.egg/EGG-INFO/requires.txt
> Adding QtAwesome 0.5.7 to easy-install.pth file
>
> Installed /usr/local/lib/python2.7/dist-packages/QtAwesome-0.5.7-py2.7.egg
> Searching for qdarkstyle>=2.6.4
> Reading https://pypi.org/simple/qdarkstyle/
> Downloading https://files.pythonhosted.org/packages/2b/ab/8996b69475feda604e8b2f60b7d3e48938c0e07f48532ee112ce097cc6de/QDarkStyle-2.6.8-py2.py3-none-any.whl#sha256=fd1abae37d3a0a004089178da7c0b26ec5eb29f965b3e573853b8f280b614dea
> Best match: QDarkStyle 2.6.8
> Processing QDarkStyle-2.6.8-py2.py3-none-any.whl
> Installing QDarkStyle-2.6.8-py2.py3-none-any.whl to /usr/local/lib/python2.7/dist-packages
> Adding QDarkStyle 2.6.8 to easy-install.pth file
> Installing qdarkstyle script to /usr/local/bin
>
> Installed /usr/local/lib/python2.7/dist-packages/QDarkStyle-2.6.8-py2.7.egg
> Searching for python-language-server[all]<0.25,>=0.19.0
> Reading https://pypi.org/simple/python-language-server/
> Downloading https://files.pythonhosted.org/packages/f4/77/3e0647076d9b28d9d0fc8eee50c907e203a54453ed8195861263d140e939/python-language-server-0.24.0.tar.gz#sha256=a056d2504d78fc596099a24a8aa20895923c4fbe05620afeb46fe193a5d9f517
> Best match: python-language-server 0.24.0
> Processing python-language-server-0.24.0.tar.gz
> Writing /tmp/easy_install-zwUfo9/python-language-server-0.24.0/setup.cfg
> Running python-language-server-0.24.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zwUfo9/python-language-server-0.24.0/egg-dist-tmp-V4D4b5
> UPDATING build/lib.linux-x86_64-2.7/pyls/_version.py
> set build/lib.linux-x86_64-2.7/pyls/_version.py to '0.24.0'
> zip_safe flag not set; analyzing archive contents...
> test.plugins.test_autopep8_format: module references __file__
> test.plugins.test_completion: module references __file__
> test.plugins.test_definitions: module references __file__
> test.plugins.test_highlight: module references __file__
> test.plugins.test_hover: module references __file__
> test.plugins.test_mccabe_lint: module references __file__
> test.plugins.test_pycodestyle_lint: module references __file__
> test.plugins.test_pydocstyle_lint: module references __file__
> test.plugins.test_pyflakes_lint: module references __file__
> test.plugins.test_signature: module references __file__
> test.plugins.test_symbols: module references __file__
> test.plugins.test_yapf_format: module references __file__
> creating /usr/local/lib/python2.7/dist-packages/python_language_server-0.24.0-py2.7.egg
> Extracting python_language_server-0.24.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
> Adding python-language-server 0.24.0 to easy-install.pth file
> Installing pyls script to /usr/local/bin
>
> Installed /usr/local/lib/python2.7/dist-packages/python_language_server-0.24.0-py2.7.egg
> Searching for pyqtwebengine<5.13
> Reading https://pypi.org/simple/pyqtwebengine/
> No local packages or working download links found for pyqtwebengine<5.13
> error: Could not find suitable distribution for Requirement.parse('pyqtwebengine<5.13')
>
> Do you know what I can do or i must change using spyder and use another IDE ?
> Then I tried to reinstall the old version 3.2.6 and that was difficult but I finish to succeed.
>
> Please help me or say me if I must use Eric6 or Eclipse (that will be a pity) !!!!!
>
> Have a good day and excuse my very bad english.
>
> Pascal Grandeau
>

**Comment by ccordoba12** [comment]
> sudo easy_install -U spyder

This is **really** bad, for two reasons:

1. You're using easy_install, which has been deprecated at least 5 years ago, if not more. Now you need to use pip.
1. You're messing with your system Python installation (i.e. the one in `/usr`), which can affect your entire system because Python is used to do a lot of things on Linux. You must avoid doing that in the future and instead use virtualenvs (please google how to use them). And you should also remove the packages installed by easy_install.

> Installed /usr/local/lib/python2.7/dist-packages/python_language_server-0.24.0-py2.7.egg
Searching for pyqtwebengine<5.13
Reading https://pypi.org/simple/pyqtwebengine/
No local packages or working download links found for pyqtwebengine<5.13
error: Could not find suitable distribution for Requirement.parse('pyqtwebengine<5.13')

This error will be solved in our next beta but for now beta2 is not compatible with Python 2. You can instead use beta1 if you want with

    pip install --pre spyder==4.0.0b1

or downgrade to our latest stable release with

    pip install spyder==3.3.4
