### ISSUE TITLE
Error when launching Preferences in Chinese

### ISSUE THREAD

**Issue by qrqiuren** [spyder-ide/spyder#9390]
### What steps will reproduce the problem?

1. Download Spyder 4.0.0b2 from conda
2. Start Spyder
3. Launch the preference window and then an error report window shows. However, the preference window seems working correctly.

### Traceback
```python-traceback
    widget = plugin.create_configwidget(dlg)
    configwidget.initialize()
    self.setup_page()
    "separate window.") % (inline, automatic))
TypeError: not all arguments converted during string formatting
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.6.7
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.3 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.7 (OK)
qtconsole >=4.2.0  :  4.4.4 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
Please run in a terminal (cmd.exe)

    spyder --reset

and try again.

**Comment by qrqiuren** [comment]
> 
> 
> Please run in a terminal (cmd.exe)
> 
> ```
> spyder --reset
> ```
> 
> and try again.

All things are still the same.

**Comment by ccordoba12** [comment]
Are you using Spyder in Chinese?

**Comment by qrqiuren** [comment]
> 
> 
> Are you using Spyder in Chinese?

Yes

**Comment by ccordoba12** [comment]
Ok, I guessed that. Thanks for the confirmation.

We'll fix this error in our next beta.

**Comment by ccordoba12** [comment]
@steff456, the idea here is to add the missing string replacement here

https://github.com/spyder-ide/spyder/blob/c68f2f337253b8185fc5fbbd099a09c98de15afa/spyder/locale/zh_CN/LC_MESSAGES/spyder.po#L2419-L2426

You can see that at the end of line 2425 there's a `<b>`, when it should be `<b>%s</b>`.

After doing that change, please go to

    Preferences > General > Advanced settings > Language

select each one of last two (I don't know which one is Chinese) and test that our Preferences can open without problems after the restart that changes the language.

**Comment by qrqiuren** [comment]
> 
> 
> @steff456, the idea here is to add the missing string replacement here
> 
> https://github.com/spyder-ide/spyder/blob/c68f2f337253b8185fc5fbbd099a09c98de15afa/spyder/locale/zh_CN/LC_MESSAGES/spyder.po#L2419-L2426
> 
> You can see that at the end of line 2425 there's a `<b>`, when it should be `<b>%s</b>`.
> 
> After doing that change, please go to
> 
> ```
> Preferences > General > Advanced settings > Language
> ```
> 
> select each one of last two (I don't know which one is Chinese) and test that our Preferences can open without problems after the restart that changes the language.

Line breaks shouldn't affect the results in po files since the strings are concatenated. The real problem is this:

In the second line of translation, the symbol "%" has been mistakenly replaced by the full-width symbol "％", which is widely used in CJK input methods.

**Comment by ccordoba12** [comment]
We already figured it out, but thanks.
