### ISSUE TITLE
using BeautifulSoup4 to webscrape wikipedia

### ISSUE THREAD

**Issue by Tique19** [spyder-ide/spyder#9395]
### What steps will reproduce the problem?

import urlopen and BeautifulSoup, parse the wiki url for Belarus, findAll tables

### Traceback
```python-traceback
    documentation=documentation,
    res = self._check_signature_and_format(signature, parameter)
    parameter=parameter,
    parameter=parameter,
IndexError: tuple index out of range

Traceback (most recent call last):
    msg = self.format(record)
    return fmt.format(record)
    record.message = record.getMessage()
    msg = msg % self.args
ValueError: incomplete format
Call stack:
    sys.exit(main())
    mainwindow.main()
    mainwindow = run_spyder(app, options, args)
    app.exec_()
    handler(resp['result'], req_id)
    {'params': response})
    handler(params)
    self.log_lsp_handle_errors("Error when processing signature")
    logger.error('%', 1, stack_info=True)
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
@Tique19 it seems to be a problem with the `CalltipWidget` what method where you calling?

**Comment by Tique19** [comment]
findAll in the BeautifulSoup Library

On May 23, 2019, at 12:06 AM, Gonzalo Peña-Castellanos <notifications@github.com<mailto:notifications@github.com>> wrote:


@Tique19<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Tique19&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=7XQ8wd-iaUQP_AOYU5fc9g&m=46JBEsd9v01QQwGWpH-FkdXQvdKHWtjUbrbS2AvUxFs&s=kmGOZlxmaRokaWfhcFw-D2UoS3sfWHv6XK7sG6ruSHs&e=> it seems to be a problem with the CalltipWidget what method where you calling?
