### ISSUE TITLE
Zoom buttons state and scaling percentage update when "Fits plot to window" is activated

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9405]
## Problem Description

I think when the `Fits plot to window` option is checked, the zooming in/out capability should be deactivated. This would also serve as a visual indicator that the `Fits plot to window` is on.

Also, the displayed % should be updated to reflect the actual scaling of the figure when it is fitted to the Plots plane.

![image](https://user-images.githubusercontent.com/10170372/58253957-af588c80-7d37-11e9-899b-386de5638cb7.png)

**Comment by jnsebgosselin** [comment]
@goanpeca Do you agree with this? If so, I have a PR ready already to address this.

**Comment by goanpeca** [comment]
Hi @jnsebgosselin, yes I think it makes sense 👍
