### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by Qingchu1995** [spyder-ide/spyder#9409]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
I loaded a npy file containing a 2D numpy variable. However, it reported errors when I tried to visualize the databy variable exlporer. The error is following:
    self.data.flags.writeable = True
ValueError: cannot set WRITEABLE flag to True of this array

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.4
