### ISSUE TITLE
Problem raw_input with accent

### ISSUE THREAD

**Issue by pgr123** [spyder-ide/spyder#9411]
I use Python 2.7 with Spyder 3.2.6 and when I try :+1: 
x = raw_input('date de départ : ')
I get a very strange string !!!!
While with Python (without Spyder), it works fine.
I know the problem is the accent (é) but this works in Python 2 without problem, so the problem comes from Spyder.
Can you help me, maybe a parameter in Spyder to adjust.
Thank you.

**Comment by goanpeca** [comment]
Thanks for reporting. Could you add a screenshot?

**Comment by pgr123** [comment]
Here is a screenshot
![Problem accent file   console](https://user-images.githubusercontent.com/37294226/58313177-3af01d00-7e0d-11e9-80d6-33be86fcf4dc.png)
Before, when I write in temp.py : x=raw_input( I got an error withe Sphinx. Matbe the problem is here but how can I do ?
![Error message with sphinx](https://user-images.githubusercontent.com/37294226/58313283-7be83180-7e0d-11e9-939b-90183131d05b.png)
Thank you.

**Comment by pgr123** [comment]
It seems to work well with Python 3, Spyder 3.3.4 and sphinx 2.0.1.
But it does not work with Python 2 and spyder 3.3.3 (sphinx1.8.4) while with Python (without Spyder), it works fine : 
![Test with Python 2](https://user-images.githubusercontent.com/37294226/58316513-ff0c8600-7e13-11e9-9554-a5592bae82e8.png)

**Comment by ccordoba12** [comment]
> x = raw_input('date de départ : ')

Please use

    x = raw_input(u'date de départ : ')

and try again.

**Comment by pgr123** [comment]
I have already tried and I get another error : 
**In the console :** 
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

x = raw_input(u'date de départ : ')

Traceback (most recent call last):

  File "<ipython-input-1-b4745496e2bb>", line 1, in <module>
    x = raw_input(u'date de départ : ')

  File "/home/pascal/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 701, in raw_input
    return self._input_request(str(prompt),

UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 9: ordinal not in range(128)

**and in a file I get that error :**
runfile('/home/pascal/.config/spyder/temp.py', wdir='/home/pascal/.config/spyder')
Traceback (most recent call last):

  File "/home/pascal/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2895, in run_code
    self.showtraceback()

  File "/home/pascal/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 1826, in showtraceback
    value, tb, tb_offset=tb_offset)

  File "/home/pascal/.local/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1411, in structured_traceback
    self, etype, value, tb, tb_offset, number_of_lines_of_context)

  File "/home/pascal/.local/lib/python2.7/site-packages/IPython/core/ultratb.py", line 1328, in structured_traceback
    self, etype, value, elist, tb_offset, number_of_lines_of_context

  File "/home/pascal/.local/lib/python2.7/site-packages/IPython/core/ultratb.py", line 644, in structured_traceback
    out_list.extend(self._format_list(elist))

  File "/home/pascal/.local/lib/python2.7/site-packages/IPython/core/ultratb.py", line 682, in _format_list
    item += '    %s\n' % line.strip()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 25: ordinal not in range(128)

Thank you.
I do not understand where is the problem because that works well in a terminal.

**Comment by ccordoba12** [comment]
> File "/home/pascal/.local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 701, in raw_input
return self._input_request(str(prompt),
>
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 9: ordinal not in range(128)

This shows that the error is present in the `ipykernel` package, not in Spyder. So please report it there:

https://github.com/ipython/ipykernel

> I do not understand where is the problem because that works well in a terminal.

The terminal uses a completely different architecture than the Jupyter one (which we also use in our console). The Python interpreter uses readline, the IPython terminal uses `prompt_toolkit` and our console uses a two process architecture composed of a kernel (to evaluate code) and interface (to run code and display what comes from it).

**Comment by pgr123** [comment]
This works well with ipython : 
pascal@EL1352:~$ ipython
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
Type "copyright", "credits" or "license" for more information.

IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: x=raw_input("début : ")
début : 25/05/2019

In [2]: x
Out[2]: '25/05/2019'

In [3]: 

So I do not understand why Spyder does not work with taht !!!!

**Comment by ccordoba12** [comment]
Please read with care my answer above:

You: 
> This works well with ipython

Me: 
> the IPython terminal interpreter uses `prompt_toolkit`

You:
> So I do not understand why Spyder does not work with taht !!!!

Me:
> The terminal uses a completely different architecture than the Jupyter one (which we also use in our console) ... and our console uses a two process architecture composed of a kernel (to evaluate code) and an interface (to run code and display what comes from it).

----

I hope it's clear now because I don't know how to make clearer. The fact that things work either in the Python interpreter or an IPython session started in a terminal (as you did above), doesn't mean that they should work the same in Spyder's console because each of these interpreters is built with different technologies.

Anyway, please report your problem in `ipykernel`, because that's the right place to fix it, not here.

**Comment by pgr123** [comment]
Your answer was very clear but I have not an explication why this work with Python 3 and not Python 2. I have signaled the problem to ipkernel. I'll see. In the meantime I will avoid accents with raw_input and I must change all the raw_input in all my programs which worked well before ! 
For you, of course, it is not a problem but in French it is one ! And what's odd for me is that it's no problem with print !
Thank you for all.
Pierre Raybaut will be interested by that problem ! I'll contact him.
Have a good sunday.

**Comment by pgr123** [comment]
I think it's a shame to have chosen Jupyter at least for French ! 
Before, I never had problem with raw_input and the accents !
I'll wait the answer of ipykernel if there is one (!) but I think I will have to change of IDE, and it's a pity for me which use Spyder for many years and I love it !

**Comment by goanpeca** [comment]
>Your answer was very clear but I have not an explication why this work with Python 3 and not Python 2.

This is a long history here of this, but it boils down to unicode support, one of the big headaches and changes from  python 2 and python3. It also has to do with the default encoding your terminal might be using, and the default encoding that is selected when spyder runs.

**Comment by pgr123** [comment]
I use
# -*- coding: utf-8 -*-
so theoretically it's UTF8.
And with Python 2.7 in a terminal this works but not in the spyder console.

**Comment by pgr123** [comment]
So the only thing I can do is to downgrade Spyder (or to use another IDE !!!!). It is a very pity for me !!!
I think this is the same problem for latin country as Spain or Italy !!! The world is not only anglo-american !!!!

**Comment by ccordoba12** [comment]
Several of us Spyder core developers are Spanish speaking people, but most of us moved to use Python 3 several years ago. Since Python 2 is six months away of its end of life, you should be considering to move soon too.

However, we'll try to see if we can help the ipykernel guys with this bug.

**Comment by ccordoba12** [comment]
(And by the way, using a lot of exclamation marks is not useful to make your use case stronger).
