### ISSUE TITLE
Cannot install Spyder 3.3.4

### ISSUE THREAD

**Issue by pgr123** [spyder-ide/spyder#9416]
Good morning.
I use Ubuntu MATE 18.04 and Python 2.7 and I cannot install Spyder 3.3.4 : I get an error : 
pascal@EL1352:~$ pip install spyder==3.3.4
Collecting spyder==3.3.4
  Using cached https://files.pythonhosted.org/packages/7c/ac/edaec8736d5425abe02eb5d177c7d342f1f725c6c737f81bc02433691c13/spyder-3.3.4-py2-none-any.whl
Collecting qtpy>=1.5.0 (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/14/a8/6145994bd4eb03f2bfe54a87665588891dacf2dd5e96ca6546cf16d76f45/QtPy-1.7.1-py2.py3-none-any.whl
Collecting pickleshare (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/9a/41/220f49aaea88bc6fa6cba8d05ecf24676326156c23b991e80b3f2fc24c77/pickleshare-0.7.5-py2.py3-none-any.whl
Collecting pyflakes (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/84/f2/ed0ffb887f8138a8fe5a621b8c0bb9598bfb3989e029f6c6a85ee66628ee/pyflakes-2.1.1-py2.py3-none-any.whl
Collecting spyder-kernels<1.0,>=0.4.3 (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/d5/f7/a7e25bc3034644fb915f57290969107c897bae2b57029c4368c0a907039f/spyder_kernels-0.4.4-py2.py3-none-any.whl
Collecting jedi>=0.9.0 (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/25/2b/1f188901be099d52d7b06f4d3b7cb9f8f09692c50697b139eaf6fa2928d8/jedi-0.13.3-py2.py3-none-any.whl
Collecting nbconvert (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/35/e7/f46c9d65f149271e47fca6ab084ef5c6e4cb1870f4c5cce6690feac55231/nbconvert-5.5.0-py2.py3-none-any.whl
Collecting pycodestyle (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/0e/0c/04a353e104d2f324f8ee5f4b32012618c1c86dd79e52a433b64fceed511b/pycodestyle-2.5.0-py2.py3-none-any.whl
Collecting rope>=0.10.5 (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/82/dc/3f8fe60b883796d14dc49526521d12c4d060f3ec971ca97f2f00051b88dc/rope-0.14.0-py2-none-any.whl
Collecting qtconsole>=4.2.0 (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/c7/45/1a50288305797fbca7c2039f9baefff1a9df603322874743fbb8408d8ec2/qtconsole-4.4.4-py2.py3-none-any.whl
Collecting pygments>=2.0 (from spyder==3.3.4)
  Using cached https://files.pythonhosted.org/packages/6e/00/c5cb5fc7c047da4af049005d0146b3a961b1a25d9cefbbe24bf0882a11ad/Pygments-2.4.0-py2.py3-none-any.whl
Collecting pyqtwebengine<5.13 (from spyder==3.3.4)
  Could not find a version that satisfies the requirement pyqtwebengine<5.13 (from spyder==3.3.4) (from versions: )
No matching distribution found for pyqtwebengine<5.13 (from spyder==3.3.4)
pascal@EL1352:~$ 

Do you know what can I do ?
Thank you.

**Comment by ccordoba12** [comment]
This error will be fixed in our next release (3.3.5). For now please use Python 3 or Anaconda.
