### ISSUE TITLE
Syntax analysis returns non-existent error with function annotation

### ISSUE THREAD

**Issue by pj1989** [spyder-ide/spyder#9419]
## Problem Description

PEP 3107 introduced function annotations in Python.
However, Spyder code analyzer does not recognize the syntax and return a `syntax error in forward annotation`

### What steps reproduce the problem?

1.  Just copy-past the first example in PEP 3107 as:
```
def compile(source: "something compilable",
            filename: "where the compilable thing comes from",
            mode: "is this a single statement or a suite?"):
    pass
```
2. A syntax error symbol (red circle with X) will appear on line 1 . The code, however runs perfectly without any error.

## Versions

* Spyder version:  3.3.4
* Python version: 3.7.1
* Qt version:  5.9.6
* PyQt version:  5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.2.0 (OK)
cython >=0.21     :  0.29.2 (OK)
jedi >=0.9.0      :  0.13.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.2.2 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

**Comment by bcolsen** [comment]
Thank you for submitting this bug. This is not a Spyder bug but a pyflakes bug.

Closely related to these bugs:
https://github.com/PyCQA/pyflakes/issues/340
https://github.com/PyCQA/pyflakes/issues/373

Pyflakes seem to only implement PEP484 as from https://github.com/PyCQA/pyflakes/issues/340
> PEP484 replaces the lack of guidance in PEP3107

So it is up to python foundation to regress PEP3107 as invalid syntax in favor of PEP484 or pyflakes to not complain about it.
