### ISSUE TITLE
Zooming in plot viewer doesn't work when using "Fit plots to window"

### ISSUE THREAD

**Issue by Illviljan** [spyder-ide/spyder#9424]
## Problem Description
The zoom in/out buttons are still interactive and increases/decreases when clicked on them. Nothing happens to the plot however, since it has already fit to the window. It's the default setting behavior too.

### What steps reproduce the problem?
1. Turn on and off the "Fit plots to windows" while clicking furiously on the zoom in and out buttons.

### What is the expected output? What do you see instead?
The zoom buttons should either be removed or not be interacteable while the "Fit plots to window" option is set. 
The zoom buttons could also imply better that it's just the image that's being resized. I thought those buttons worked similarly to the zoom buttons in interactive mode.

## Versions
* Spyder version: 4.0.0b2
* Python version: 3.7.3

**Comment by ccordoba12** [comment]
Thanks for reporting. This was fixed already and it'll be part of beta3.
