### ISSUE TITLE
cannot search help entries in searchbox

### ISSUE THREAD

**Issue by ferminfm** [spyder-ide/spyder#9426]
### What steps will reproduce the problem?

open anaconda-navigator (ubuntu 18.04)
start spyder
in the help navigator tab on the right side choose "terminal" then enter some latin text in the search box.

Result: only the first character is displayed and the rest is deleted every time a new character is imput. Example: write "plot", and only the final "t" is visible so it only searches for single letter entries which are non existen obviously. Cannot search the help database practically.

If we change the last step and input Japanse chacters in the search box the result is a program crash.

### Traceback
```python-traceback
  File "/home/franco/anaconda2/lib/python2.7/site-packages/spyder/plugins/help.py", line 92, in validate
    valid = self.is_valid(qstr)
  File "/home/franco/anaconda2/lib/python2.7/site-packages/spyder/plugins/help.py", line 68, in is_valid
    if not re.search(r'^[a-zA-Z0-9_\.]*$', str(qstr), 0):
UnicodeEncodeError: 'ascii' codec can't encode character u'\u3049' in position 0: ordinal not in range(128)
WARNING:spyder.widgets.github.backend:Failed to send bug report on Github. response={'json': {'documentation_url': u'https://developer.github.com/v3', 'message': u'Bad credentials'}, 'code': 401}
```

## Versions

* Spyder version: 3.3.3 
* Python version: 2.7.16
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-50-generic

### Dependencies

```
pyflakes >=0.5.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0;<6.0:  5.8.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  1.9.2 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for reporting. 3.3.4 has a partial fix for this but our next version (3.3.5, to be released) fixes it for good.
