### ISSUE TITLE
Ploting a matplotlib graph

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder#9433]
### What steps will reproduce the problem?

can't plot to an external plot that can be modified as before zoom in to a specific location, moving the data to the left etc.

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is working as expected. Simply set your graphics backend to "Automatic" in

    Tools > Preferences > IPython console > Graphics > Graphics Backend

and you'll have interactive plots.

Or what's the error that you're seeing?

**Comment by boazdori** [comment]
I played with the adjustment in the console set to automatic still prints static to console and plot not as a separate window as before

**Comment by ccordoba12** [comment]
You need to restart the console's kernel with `Ctrl+.` when the console is focused, or restart Spyder, for the change in backend to take effect.

**Comment by boazdori** [comment]
thanks for the help working

**Comment by ccordoba12** [comment]
No problem. We should inform users when a kernel restart is required after a setting in our Preferences is changed.
