### ISSUE TITLE
Under the dark theme, the right warning display sidebar is not offset to match the scroll bar position

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#9439]
First discussed on #8068 , but issue opened on request of @ccordoba12 .

When using the dark theme, the right sidebar that shows error/warning/etc. markers throughout the document is not offset to match the scrollbar like with the light theme, so the latter is not usable as an indicator of which should be visible. Compare the light theme:

![image](https://user-images.githubusercontent.com/17051931/58411225-6eaf8a80-8039-11e9-8593-3d401c3c7f68.png)

With the dark theme:

![image](https://user-images.githubusercontent.com/17051931/58411047-08c30300-8039-11e9-96a4-d9005a94ec59.png)

Presumably, the warning bar needs to be offset by a distance equal to the scroll arrow widget on the top and bottom on the dark theme to avoid this problem.

## Versions

* Spyder version: 4.0 ``master``, since dark theme implementation
* Python version: 3.6-3.7
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 Pro x64

### Dependencies

``qdarkstyle 2.6.8``

**Comment by ccordoba12** [comment]
@jnsebgosselin, do you have any ideas about how we could solve this?

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin, do you have any ideas about how we could solve this?

Yes I know why. I will fix it.

**Comment by CAM-Gerlach** [comment]
Thanks @jnsebgosselin and @ccordoba12 !

**Comment by ccordoba12** [comment]
Thanks a lot @jnsebgosselin!
