### ISSUE TITLE
logging.shutdown() fails to close logging handler when executed in Spyder

### ISSUE THREAD

**Issue by texadactyl** [spyder-ide/spyder#9440]
```python
import logging

FLAG_SHUTDOWN = False

def init():
    logobj = logging.getLogger(__name__)
    logobj.setLevel(logging.DEBUG)
    hconsole = logging.StreamHandler()
    logobj.addHandler(hconsole)
    return logobj

def closer(arg_logger):
    if FLAG_SHUTDOWN:
        logging.shutdown()
    else:
        handlers = arg_logger.handlers[:]
        for handler in handlers:
            handler.close()
            arg_logger.removeHandler(handler)

def speak(arg_logger):
    logger.info("------------------------------------------------")
    logger.info("Line 1")
    logger.info("Line 2")
    logger.info("Line 3")

logger = init()
speak(logger)
speak(logger)
closer(logger)
```

The attached Python script runs without anomalies.  It closes every handler one at a time.  It can be run in the Spyder environment repeatedly without causing duplicated logging records.

However, changing 

`FLAG_SHUTDOWN = True`

will cause the closer() subroutine to use `logging.shutdown()` which should force the "logging system to perform an orderly shutdown by flushing and closing all handlers" according to Python 3 documentation.  It doesn't seem to do anything in the Spyder environment (conflict?).  

When I rerun the same script a second time, I see duplicated messages, probably from the old handler and the new handler.  A 3rd time, triplicated messages, etc.

Not asking for any extraordinary effort here.  Just a resolution of some sort.  Maybe, Spyder should trap the logging.shutdown() call (happening already?) and throw an Exception (Don't do that).  I'd rather be punished for having a misunderstanding that is causing a conflict. (:

**Comment by texadactyl** [comment]
Anaconda environment, up-to-date.
spyder                    3.3.4                    py36_0  
spyder-kernels            0.4.4                    py36_0

**Comment by ccordoba12** [comment]
You omitted from your quoting of the `logging.shutdown` docs some important stuff. This is the full text:

```
logging.shutdown()

    Informs the logging system to perform an orderly shutdown by flushing and closing all handlers. This should be called at application exit and no further use of the logging system should be made after this call.
```

The critical part is:

> This should be called at application exit and no further use of the logging system should be made after this call.

In our case, *application exit* means a kernel restart because it is not possible to evaluate more code after it.

So this means that you can't call `logging.shutdown` in an interactive session (like the one provided by our IPython consoles) and expect to keep working with `logging` in the next evaluation.

A possible workaround would be to turn on

    Remove all variables before execution

in the menu

    Run > Configuration per file

and see if that helps.

**Comment by texadactyl** [comment]
@ccordoba12 I did consider what you felt was critical in the documentation but 
- I was focused on the fact that the old handlers were not being closed during shutdown() as documented.  Something seems to be going wrong but no Exceptions were thrown.
- My Python program, in fact, follows the documentation advise i.e. makes no further use of  logging and exits.  However, I realise that Spyder and my Python programs viewed monolithically by the Python kernel are what the advise is referring to.
- My Python program does successfully use logging in subsequent executions but new handlers were added to the old handlers.

Thanks for the work-around.  My code includes manually walking the list of handlers already so I'll just keep using that unconditionally since it works in Spyder and at the bash shell prompt.

So, I have to say that this is a logging.shutdown() oddity and I would not expect Spyder to do anything about it.  I'll bet that I am not the only one who has run into this.

**Comment by texadactyl** [comment]
@ccordoba12 I'll assume that you read my previous comment.

**Comment by ccordoba12** [comment]
Sorry, we can't really help you with this in our end.

**Comment by texadactyl** [comment]
Agreed. Its a logging.shutdown() anomaly that I can easily avoid using my sample closer() without the boolean switch.

**Comment by izhgtumekhanik** [comment]
[texadactyl](https://github.com/texadactyl), If there is a need for this...
```python
import importlib
import logging

importlib.reload(logging)

FLAG_SHUTDOWN = True

def init():
...
```

**Comment by ccordoba12** [comment]
@izhgtumekhanik, what do you mean by that? I mean, does `importlib.reload(logging)` solve this problem for you?
