### ISSUE TITLE
Information icon in File Switcher is not themed under the dark theme

### ISSUE THREAD

**Issue by CAM-Gerlach** [spyder-ide/spyder#9442]
### Issue Report Checklist

Originally discussed on #8068 .

Under the dark theme, the "information" icon in the file switcher is still not themed, as seen in #8616 .

![image](https://user-images.githubusercontent.com/17051931/51778512-b47a3780-20c7-11e9-9d53-e2da1615d45a.png)

## Versions

* Spyder version: 4.0.0 latest ``master``
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

### Dependencies

```
qdarkstyle 2.6.8
```

**Comment by dpizetta** [comment]
@CAM-Gerlach could you tell me which widget is that button? Mays is something with qdarkstyle, maybe not. Tks

**Comment by CAM-Gerlach** [comment]
@dpizetta Thanks. The issue is with Spyder, by all appearances, but it should be pretty straightforward for them to resolve once they get to it.

In ``spyder/widgets/helperwidgets.py``:

```python
class HelperToolButton(QToolButton):
    """Subclasses QToolButton, to provide a simple tooltip on mousedown.
    """
    def __init__(self):
        QToolButton.__init__(self)
        self.setIcon(get_std_icon('MessageBoxInformation'))
        style = """
            QToolButton {
              border: 1px solid grey;
              padding:0px;
              border-radius: 2px;
              background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                  stop: 0 #f6f7fa, stop: 1 #dadbde);  
            }
            """
        self.setStyleSheet(style)
```

**Comment by dpizetta** [comment]
Tks. The style is hardcoded. Try to remove this, then it will use the qtoolbutton style. If any problem still there, let me know.

```
        style = """
            QToolButton {
              border: 1px solid grey;
              padding:0px;
              border-radius: 2px;
              background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,
                  stop: 0 #f6f7fa, stop: 1 #dadbde);  
            }
            """
        self.setStyleSheet(style)
```

**Comment by CAM-Gerlach** [comment]
Thanks @dpizetta , hopefully someone will get to this soon and your suggestion works.

**Comment by CAM-Gerlach** [comment]
Thanks @dpizetta , I'm sure the Spyder team will appreciate your help.

**Comment by ccordoba12** [comment]
@dpizetta, thanks a lot for your help with this one!

@juanis2112, please take a look at this issue, following @dpizetta's advice. The idea is that the icon uses `MAIN_FG_COLOR` so that it looks white on the dark interface and black on the light one.
