### ISSUE TITLE
Code cells that fill the whole screen lose their background highlight

### ISSUE THREAD

**Issue by bcolsen** [spyder-ide/spyder#9443]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

If a code cell fills the whole screen it loses the code cell highlighting.

![Code cell unhighlight](https://user-images.githubusercontent.com/10513354/58441311-473ed900-809e-11e9-8944-c47d12c04e28.gif)

### What steps reproduce the problem?

1. Make a code cell bigger than the screen space of the editor
2. Scroll until the top of the cell is out of the screen

### What is the expected output? What do you see instead?

It should stay highlighted so the user knows that they are still in a cell.

## Versions

* Spyder version: master

**Comment by bcolsen** [comment]
Because of the some changes in PR:#9082 this bug has returned. 

It looks like `has_cell_separators` in `syntaxhighlighters` is set to false if a line is changed and that line isn't a code cell comment. `has_cell_separators` needs to indicate if the file has at least on code cell.

Now that the outliner tree is updated frequently we could change `has_cell_separators` based on whether there is a code cell in the outliner tree.

@impact27 Any thoughts on this?

**Comment by impact27** [comment]
I would probably:
 - Get rid of `found_cell_separators` as it is not reliable. (The syntax highlighter is not notified about deletions)
 - Check the document for any oedata that  are cells.

You can get all the outlineexplorer data with `CodeEditor`'s `outlineexplorer_data_list`. From one `OutlineExplorerData` you can use `_document_cells` to get all the cells.

(It would probably be a good idea to consolidate these two. You can find all the block iterations by searching for `while block.isValid():`.)

**Comment by impact27** [comment]
Also both of these are generators so you can stop the iteration as soon as you find a cell.
