### ISSUE TITLE
Not able to create a new breakpoint after a collapsed function

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder#9457]
## Problem Description
If a function is collapsed, a new breakpoint cannot be created in the lines below it. 

### What steps reproduce the problem?

1. Create a function and collapse it
2. Try to create a new breakpoint in any of the lines below
3. Nothing happens

### What is the expected output? What do you see instead?

We should be able to modify the state of breakpoints after a collapsed function.

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: 886f73cff)
* Python version: 3.6.8
* Qt version: 5.12.2
* PyQt version: 5.12.1
* Operating System name/version: Darwin 18.2.0

**Comment by ccordoba12** [comment]
@dalthviz, given that you work on the debugger panel, you have any ideas about where @steff456 can start looking to solve this bug?

**Comment by dalthviz** [comment]
@ccordoba12 @steff456 after testing a little bit it seems like when collapsing the code in the debug panel is not mapping correctly the space released for the collapsed lines so for example:

![debug](https://user-images.githubusercontent.com/16781833/58604984-4fe10c00-8264-11e9-8c57-38a082009c36.gif)

**Comment by dalthviz** [comment]
Also it seems that even if not showing when the code is collapsed, the breakpoint its being set:

![debug2](https://user-images.githubusercontent.com/16781833/58605235-10ff8600-8265-11e9-995c-906a0d258e39.gif)

**Comment by ccordoba12** [comment]
So we need to make the debug panel to follow the mapping created by the folding panel?

**Comment by dalthviz** [comment]
Yep :)
