### ISSUE TITLE
Restore underlining errors and warnings in the Editor

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9472]
Add additional highlights to the code editor words to indicate the problems (errors, warning, info, hint) on the text itself, using curly underline and colors

<img width="439" alt="Screen Shot 2019-05-29 at 19 15 33" src="https://user-images.githubusercontent.com/3627835/58599500-2b763700-8246-11e9-8cf2-b17ba8a80cba.png">

<img width="748" alt="Screen Shot 2019-05-29 at 19 20 58" src="https://user-images.githubusercontent.com/3627835/58599686-f61e1900-8246-11e9-8347-477e4220d671.png">

**Comment by ccordoba12** [comment]
@steff456, please work on this one. The idea is to underline the parts of a line where there are errors/warnings/hints reported by the PyLS.

This was working in Spyder 3, so please take a look at

https://github.com/spyder-ide/spyder/blob/3.x/spyder/widgets/sourcecode/codeeditor.py

and look for `underline` there.
