### ISSUE TITLE
Change entry_points to call latest spyder from 'spyder' cmd line

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/spyder#9480]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice

## Problem Description

- Calling spyder from terminal needs to be done using `spyder3`, not only `spyder`, which is sometimes anoying;
- To start Spyder 4, you need to call `spyder3` - may not updated yet.

### What is the expected output? What do you see instead?

- `spyder` entry point call the latest spyder available.
- `spyderX`, where X = 2,3,4,  call specific version if available.

As we are not supposed to install more than one Spyder on the same environment, we get some cases:

Install Spyder 3;
- call `spyder` > open Spyder 3;
- call `spyder3` > open Spyder 3;
- call `spyder4` > command not found error;

Install Spyder 4;
- call `spyder` > open Spyder 4;
- call `spyder3` >  command not found error;
- call `spyder4` > open Spyder 4;

This can be done for v2, if needed.

I can submit a PR for this if agreed :) 

```
    setup_args['entry_points'] = {
        'gui_scripts': [
            '{} = spyder.app.start:main'.format(
                'spyder3' if PY3 else 'spyder')
        ]

```

PS: Looking forward to the release of v4. Tks

**Comment by ccordoba12** [comment]
@dpizetta, we use our own script to start Spyder from a git clone. It's called `bootstrap.py` and it's placed in the root of our repo.

This is mentioned in our Contributing guidelines

https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md#running-spyder

but you probably missed it.

So I think this change is not really necessary?

**Comment by dpizetta** [comment]
Oh, may I not expressed exactly. Yes, I can do it by hand, but I mean that when you install using pip you need to run using spyder3 instead of just spyder. The example from v4 was just another case. What do you think?

**Comment by dpizetta** [comment]
Ah, another case that I have experienced is that users/developers that use cmd line to do things, when they would like to call spyder, they use 'spyder' as the first trial. And it is a kind surprising when they receive that there is no command 'spyder'. So, they need to check or see docs to call the right name.

In my optinion, this is as annoying as when using Qt.py (not qtpy) that it is called Qt.Py, install with qt.py and imported as Qt. It is hard to find.

**Comment by jitseniesen** [comment]
The 3 in `spyder3` refers to the Python version, not the Spyder version.

**Comment by ccordoba12** [comment]
>The 3 in spyder3 refers to the Python version, not the Spyder version.

Yeah, we did that to conform with Linux distros: `spyder3` for Python 3 and `spyder` for Python 2.

> Ah, another case that I have experienced is that users/developers that use cmd line to do things, when they would like to call spyder, they use 'spyder' as the first trial. And it is a kind surprising when they receive that there is no command 'spyder'.

Since pip doesn't run any Python code at installation, our only choice to avoid this would be to create wheels per each operating system (i.e. to maintain the difference between `spyder3/spyder` on Linux and use only `spyder` on the others). But that seems too much effort for so little gain, specially given that the vast majority of our users install Spyder through Anaconda (which doesn't have this issue).

So I'm sorry for pip users, but this is another reason why we always recommend Anaconda over pip.

**Comment by ccordoba12** [comment]
@dpizetta, I don't know if there's something else you want to discuss about this.

**Comment by dpizetta** [comment]
I understand. TKs @ccordoba12. Closing this so.
