### ISSUE TITLE
Cannot type curly braces

### ISSUE THREAD

**Issue by Andersmb** [spyder-ide/spyder#9487]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
For some reason I cannot type curly braces, like {}, in the Spyder editor. However, it does work in the Spyder console. I recently updated to the newest version of Spyder (4.0.0b2)

This is obviously crippling.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
> For some reason I cannot type curly braces, like {}, in the Spyder editor

Sorry but you didn't fill the information we request in our issue template (like Qt version, PyQt version, Operating system, etc). Without that we can't help you.

Please create a new issue about this by going to the menu

    Help > Report issue...

That will fill our required info automatically.
