### ISSUE TITLE
Unexpected indent after pyplot command

### ISSUE THREAD

**Issue by gcoopermax** [spyder-ide/spyder#9490]
Hi

I am a newbee here so please pardon any lapses in etiquette :)

I am writing a python code in Spyder 4.0.0b2  and I have to use pyplot. I notice that after below line, Spyder indents for no reason, even though this is not a code block

`https://i.ibb.co/3yJzqQJ/indent-error.png`

Spyder even identifies this as unexpected indent, except that I didn't create it!
What am I missing here?

**Comment by bcolsen** [comment]
Thanks for the bug report!

This is a strange one that was first reported in #7377

The code thinks that the `#` in the color string is the beginning of a code comment so it ignores the finishing `)` and thinks you are continuing the function and indented the code.
