### ISSUE TITLE
Pyside installing 

### ISSUE THREAD

**Issue by akbar1111111** [spyder-ide/spyder#9496]
Hi 
I am trying to install pyside using "conda install -c anaconda pyside"
but it took a long time for the step "solving environment" and it still works on that.
 what can be the reason for that?
my spyder is 3.3.4 .
Tnx

**Comment by ccordoba12** [comment]
Sorry but this is a place to report problems about Spyder, not about Anaconda. To get support for Anaconda, please post your problem here:

https://github.com/ContinuumIO/anaconda-issues/issues/
