### ISSUE TITLE
Cursor is not restore properly in the Editor

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9501]
## Problem Description

The cursor in the Editor is not restored properly after it was changed to a `PointingHandCursor`.

![cursor](https://user-images.githubusercontent.com/10170372/58898648-0875d800-86c9-11e9-91ac-c222742f8e11.gif)

### What steps reproduce the problem?

1. Select a word or a url in the Editor
2.  Press `Ctrl + F` or `Ctrl + C` or `Ctrl + R`  combination
3.  Move the mouse around

Also

1. Go over a word with the mouse cursor
2.  Press `Ctrl`
3.  Release `Ctrl`

### What is the expected output? What do you see instead?

The cursor remains to `Qt.PointingHandCursor` while it should be restored with `restoreOverrideCursor`

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: 64a9d6ad9) 
* Python version: Python 3.7.1 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

**Comment by jnsebgosselin** [comment]
@ccordoba12 I'll take care of this, I know how to fix it.

**Comment by ccordoba12** [comment]
Ok, thanks a lot @jnsebgosselin!

**Comment by goanpeca** [comment]
@jnsebgosselin we probably need to add the cursor restore here

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/codeeditor.py#L3118
