### ISSUE TITLE
issue with the function int()

### ISSUE THREAD

**Issue by florianhos** [spyder-ide/spyder#9503]
### What steps will reproduce the problem?

I created a script to do the calculations on one experiment i am conducting.  To do so, i needed to convert a time from hour and minutes (12h32) to minutes only (752min).

And for two specifics times, 15h36min and 15h37min I have the same results when I use this line :

P=15.37  #time of one step of the experiment

Z=int((int(P)*60+((P-int(P))*100)))

the result is 936 for both times (15.36 and 15.37)

So far, it happend only for those 2 times. And using the function round() instead of int() seems to work. 

Have a nice day ! 

## Versions

* Spyder version: 3.3.2 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.1.1 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

**Comment by ccordoba12** [comment]
Thanks for opening this issue. I'm afraid we can't give an answer to your question because this is a place to report problems or bugs with Spyder, not to get help about Python in general.

Therefore, I'm going to ask you to submit your question here:

http://stackoverflow.com/

I'm sure you'll get an answer there.

**Comment by florianhos** [comment]
Ops sorry I didn’t paid attention.

Thx for the quick reply, have a nice day !


________________________________
