### ISSUE TITLE
Toggle uppercase/lowercase menu icons

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9512]
## Problem Description

I just saw that the `Toggle Uppercase` and `Toggle Lowercase` actions were added to the `Edit` menu in Spyder4. Good idea and thank you for that.

I suggest that we use these two icons from mdi qtawesome for these actions so it looks even better. What do you think?

![image](https://user-images.githubusercontent.com/10170372/58968892-cb6f1b80-8784-11e9-8d20-a92830cf06f1.png)

**Comment by jnsebgosselin** [comment]
> @jnsebgosselin sounds like a great idea. Want to make a PR :-) ?

Of course, I was just waiting for the green light hehe! :)

**Comment by ccordoba12** [comment]
+1 from me too.
