### ISSUE TITLE
Variable Explorer bug when sorting by 'size'

### ISSUE THREAD

**Issue by quiguisola** [spyder-ide/spyder#9516]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The variable explorer bugs when sorting variables by size.
![spider](https://user-images.githubusercontent.com/36287784/58977361-27d73880-878f-11e9-890f-9d0b15d58070.jpg)
Here I ran my script and the variable explorer shows all my variables correctly.
![spider 2](https://user-images.githubusercontent.com/36287784/58977409-4c331500-878f-11e9-8156-d873713af278.jpg)
Here, I sorted the variables by type and everything is still fine.
![spider 3](https://user-images.githubusercontent.com/36287784/58977441-5e14b800-878f-11e9-85f8-8d54cac8b056.jpg)
Here, I sorted the variables by size and the sorting is messed up.
As we can see in the first picture, my 'data' variable is a (32,117) Dataframe. On the second picture, everything is still ok, but in the third picture, when I sorted them by size, it shows that 'data' is (32,) size, while the correct size is attached to the 'conf_games' variable.

### What steps reproduce the problem?

1. Sort the variables by type and then by size.
2. 
3. 

### What is the expected output? What do you see instead?
Explained above.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.4
* Python version: 3.7.3
* Qt version: 5.9.2
* PyQt version: 5.9.6
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to solve this in Spyder 4.

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one.
