### ISSUE TITLE
Changing spyder theme clears console outputs

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#9530]
**Steps to reproduce:**
* Execute some commands in the console.
* Open the settings.
* Change the interface theme.

**Expected behavior:** should change the interface theme to what was selected, without making any changed in what's currently displayed anywhere in spyder other than the colors.

**Actual behavior:** clears all the contents in the console pane.

**Setup:** Spyder 4 beta 2, running on windows 10.

**Comment by ccordoba12** [comment]
> Change the interface theme.

Changing the interface theme requires a Spyder restart (as you probably noticed), so there's no way we can restore the contents present on each console after doing that, sorry.

**Comment by ccordoba12** [comment]
What I meant is that a Spyder restart also implies a restart of all consoles.
