### ISSUE TITLE
Error in Debugging

### ISSUE THREAD

**Issue by prafullasaxena** [spyder-ide/spyder#9536]
### What steps will reproduce the problem?

After installing
conda install spyder-pyls
error in debugging. not able to stop debugging from stop button.

### Traceback
```python-traceback
  File "/home/prafulla/anaconda3/lib/python3.7/site-packages/spyder/app/mainwindow.py", line 1961, in valid_project
    if bool(self.projects.get_active_project_path()):
AttributeError: 'NoneType' object has no attribute 'get_active_project_path'
```

## Versions

* Spyder version: 3.3.0 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-51-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening a terminal and running there

    conda install spyder=3.3.4

**Comment by prafullasaxena** [comment]
still i am unable to stop debugging. When i go with debugging options: step in, step out, continue till next break point, works fine but when i stop debugging, it does not stop debugging even starts execution right away without any interruption and then i am not able to stop it and forcefully i need to close either spyder or python console. earlier it was fine with 3.3.4 but now i dont know what went erong
