### ISSUE TITLE
Icons in Spyder3

### ISSUE THREAD

**Issue by Lattitude75** [spyder-ide/spyder#9538]
### What steps will reproduce the problem?

The icons in Spyder3 do not work under dark mode of the host operating system. I am currently using KDE in dark mode on Arch Linux. I request you to please update the same as quickly as possible as I a have been waiting for this fix since a long time and i prefer to keep my windows dark. 

## Versions

* Spyder version: 3.3.4 
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Linux 5.1.6-arch1-1-ARCH

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.10 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
That was fixed already and it'll be part of Spyder 4, to be released later in 2019.
