### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by angelupes08** [spyder-ide/spyder#9540]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
I am not able to perform coding in Spyder because of the error coming in the IPython console that says -"An error ocurred while starting the kernel

### What steps reproduce the problem?

1. Restarting the kernel
2. 
3. 

### Paste Traceback/Error Below (if applicable)

Traceback (most recent call last):
File "C:\Users\ANGEL\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\ANGEL\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\ANGEL\Anaconda3\lib\site‑packages\spyder_kernels\console\__main__.py", line 11, in 
start.main()
File "C:\Users\ANGEL\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 279, in main
import_spydercustomize()
File "C:\Users\ANGEL\Anaconda3\lib\site‑packages\spyder_kernels\console\start.py", line 39, in import_spydercustomize
import spydercustomize
File "C:\Users\ANGEL\Anaconda3\lib\site‑packages\spyder_kernels\customize\spydercustomize.py", line 19, in 
import pdb
File "C:\Users\ANGEL\Anaconda3\lib\pdb.py", line 73, in 
import cmd
File "C:\Users\ANGEL\Anaconda3\lib\cmd.py", line 45, in 
import string, sys
File "C:\Users\ANGEL\string.py", line 37, in 
pancard_number[2]="A" #This line will result in an error, i.e., string is immutable
TypeError: 'str' object does not support item assignment

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: Python 3.7
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)

**Comment by ccordoba12** [comment]
> C:\Users\ANGEL\string.py

You need to remove or rename this file for this to work correctly. The thing is that file has the same name as an internal Python module, and that's what breaks things internally.
