### ISSUE TITLE
Wrap text in warnings and hover tips

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#9543]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Hover tips and warnings extend beyond Spyder screen

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this one. It shouldn't be that hard to solve.
