### ISSUE TITLE
dark mode not applicable in the entire app

### ISSUE THREAD

**Issue by Cheruiyotd** [spyder-ide/spyder#9558]
### What steps will reproduce the problem?

This isnt a bug but a missing feature. Dark theme does not apply to; static code analysis, File eplorer, toolbars and Variable explorer. I believe it would be great if perhaps we had system-wide dark theme and maybe partial dark theme as it is currently.

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.7
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.4.2 (OK)
sphinx >=0.6.6    :  2.0.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.9 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by Cheruiyotd** [comment]
this should be in pull request section

**Comment by ccordoba12** [comment]
This was already fixed and it'll be part of Spyder 4, to be released later in 2019.

**Comment by programehr** [comment]
It seems like the issue is back in 5.0.0!
