### ISSUE TITLE
Spyder has encountered a problem

### ISSUE THREAD

**Issue by benmcneil** [spyder-ide/spyder#9559]
Hi, every few minutes or so I get this Error popup in Spyder with no related information as to the cause. Is there anyway to see what is causing the error so I can attempt to diagnose it?

Thanks.

"Spyder has encountered a problem. Sorry for the inconvenience. You can automatically submit this error to our Github issues tracker. Note. You need a Github account for that."

![spyder error](https://user-images.githubusercontent.com/17131089/59355247-af272d80-8cf4-11e9-8887-b1b53def6750.png)

**Comment by ccordoba12** [comment]
Please press the button below that says "Submit to Github" and resubmit your problem again.

I'm closing this issue because you gave us no useful information to help you, sorry.
