### ISSUE TITLE
Selected working directory in Preferences is not preserved after a restart

### ISSUE THREAD

**Issue by boazdori** [spyder-ide/spyder#9561]
### What steps will reproduce the problem?

under preferance i chose a working directory as a start up directrory when starting spyder again reverts back to c:\users\user directory

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  1.8.5 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.2 (OK)
sympy >=0.7.3      :  1.3 (OK)
cython >=0.21      :  0.29.6 (OK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, could you verify if this is happening to you on Windows or not?

**Comment by boazdori** [comment]
yes windows 10

**Comment by dalthviz** [comment]
@ccordoba12 yes, testing it, it happened to me too. In the preferences, the selected woking directory shows the change but the working directory toolbar shows the home directory (after restarting Spyder manually this is what I see):

![imagen](https://user-images.githubusercontent.com/16781833/59482860-4218b280-8e30-11e9-927c-3fe4e4f1ab49.png)

**Comment by ccordoba12** [comment]
Thanks for the confirmation @dalthviz. Could you also test what happens on Linux?

**Comment by dalthviz** [comment]
Testing on Linux (Ubuntu) the same behaviour happens:

![linux](https://user-images.githubusercontent.com/16781833/59528122-079c2d80-8ea3-11e9-9f3f-9ac953b9e18f.PNG)

**Comment by ccordoba12** [comment]
Ok, thanks @dalthviz. I thought it was a Windows issue only.

**Comment by goanpeca** [comment]
Who could work on this @ccordoba12 ?

**Comment by ccordoba12** [comment]
Let's give this one to @steff456 to this one.
