### ISSUE TITLE
Error for calltip with empty signature

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#9570]
### What steps will reproduce the problem?

import os

os.getcwd( -> triggers calltip but an error raises

### Traceback
```python-traceback
  File "C:\Users\Daniel\Anaconda3\envs\spyder4\lib\site-packages\qtconsole\base_frontend_mixin.py", line 138, in _dispatch
    handler(msg)
  File "C:\Users\Daniel\Desktop\Spyder\spyder\spyder\plugins\ipythonconsole\widgets\help.py", line 141, in _handle_inspect_reply
    documentation = self.get_documentation(content)
  File "C:\Users\Daniel\Desktop\Spyder\spyder\spyder\plugins\ipythonconsole\widgets\help.py", line 46, in get_documentation
    documentation = text.split(signature)
ValueError: empty separator
```

## Versions

* Spyder version: 4.0.0.dev0 eb70e6b6d
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```
pygments >=2.0     :  2.4.0 (OK)
qdarkstyle >=2.6.4 :  2.6.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.3 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.7 (OK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by goanpeca** [comment]
Thanks for reporting @dalthviz will fix it now

**Comment by goanpeca** [comment]
Hi @dalthviz sorry, I thought this was related to the code editor. I think you have more xp with the ipython console :-p. Could you fix it?

---
Also

**Comment by ccordoba12** [comment]
@goanpeca, you need to update qtconsole to fix that error.

**Comment by goanpeca** [comment]
Right I forgot

**Comment by dalthviz** [comment]
@goanpeca no worries, actually I think the error is part of the changes I made to show documentation in the calltips of the IPython Console, so I will work on it :+1:

**Comment by goanpeca** [comment]
Thanks!
