### ISSUE TITLE
Remember what was selected in the "Search in" combo box of the "Find"pluggin

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9577]
I would like that on restart, Spyder remembers what was selected in the "Search in" combo box of the `Find` plugin.

If you agree with that, what do we need to do to achieve that? Do we simply add it to our config?

![image](https://user-images.githubusercontent.com/10170372/59511675-e2002b80-8e84-11e9-9683-29e83e896b0f.png)

## Versions

* Spyder 4.0.0.dev0 (Commit: f17a9b15c) 
* Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by ccordoba12** [comment]
This is a good idea, so I agree with it.

> Do we simply add it to our config?

Please take a look at how history is saved for the Working directory and follow the same pattern.
