### ISSUE TITLE
WaitSpinner color under the dark theme should be white and suggestion for improving the look of the spinner

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9578]
## Problem Description

The wait spinner in the `Find` plugin should be white under the dark theme.

![waiting_spinner_dark](https://user-images.githubusercontent.com/10170372/59516741-001f5900-8e90-11e9-8b52-73115b1b5645.gif)

Also, while working on another project, I made some changes to the look of the spinner. I personally like it better like that, but what do you think?

![waiting_spinner_modif](https://user-images.githubusercontent.com/10170372/59516773-16c5b000-8e90-11e9-8127-3fa36155cd26.gif)

## Versions

* Spyder 4.0.0.dev0 (Commit: f17a9b15c) 
* Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by goanpeca** [comment]
Hi yes! Agreed is much better!

**Comment by goanpeca** [comment]
It would be good to define some usage guidelines if we need to use the spinner somewhere else
