### ISSUE TITLE
object array not supported in spyder3.3.3

### ISSUE THREAD

**Issue by abhishek948** [spyder-ide/spyder#9589]
### What steps will reproduce the problem?

dataset = pd.read_csv("iris.data")
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:, 4].values

here, i want to show variable exploer but i got error when open y variable that " object variable not supported"

i am using spyder 3.3.3

what i do?

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> here, i want to show variable exploer but i got error when open y variable that " object variable not supported"

It's not an error, it's an information message and it's quite clear. We'll try to support them in our next major version (Spyder 4).
