### ISSUE TITLE
Some completion trigger characters supported by LSP servers are not used

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder#9596]
## Problem Description
Right now, some of the completion/signature trigger characters are not being used by Spyder to invoke ``textDocument/completion`` and ``textDocument/signature`` requests to the LSP servers.

For instance, in signature completion on Python, "," should be used to trigger a signature event and highlight the next argument in a function.

```json
"signatureHelpProvider": {
     "triggerCharacters": ["(", ",", "="]
}
```

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/1878982/59652774-cd59b700-9154-11e9-9a07-1a08a3cecbff.gif)

On other languages, such as Elixir, trigger characters that are different from "." are just simply ignored. 

```json
"completionProvider": {
     "triggerCharacters": [".", "@"]
}
```

![ezgif com-video-to-gif(3)](https://user-images.githubusercontent.com/1878982/59653044-0f372d00-9156-11e9-8d73-cb70d0290f91.gif)

**Comment by ccordoba12** [comment]
This is something we need to improve in CodeEditor, right?

**Comment by andfoy** [comment]
> This is something we need to improve in CodeEditor, right?

That is correct!

**Comment by goanpeca** [comment]
@andfoy I could not reproduce this

![complet](https://user-images.githubusercontent.com/3627835/59690702-73cea800-91a7-11e9-9e5d-fc23ce448313.gif)

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/codeeditor.py#L884

https://github.com/spyder-ide/spyder/blob/master/spyder/plugins/editor/widgets/codeeditor.py#L3257

**Comment by andfoy** [comment]
> @andfoy I could not reproduce this

It seems that this fails when a file is opened outside a project.

**Comment by goanpeca** [comment]
>It seems that this fails when a file is opened outside a project.

@andfoy the test I made was not using projects. What do you mean?

**Comment by andfoy** [comment]
> @andfoy the test I made was not using projects. What do you mean?

Try to open a project and request some signature hint using ",". The initial "(" works, but not the ",", however, If the project is reopened once again, the signature works as expected. It seems to be a server error, rather than a CodeEditor one

**Comment by andfoy** [comment]
Sorry, this is a bug introduced by https://github.com/palantir/python-language-server/pull/601
