### ISSUE TITLE
Cannot open/save files from gui: QFileDialog issue.

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#960]
_From [danielzi...@gmail.com](https://code.google.com/u/117559567857443329925/) on 2012-03-02T20:48:26Z_

Spyder Version:  2.1.8
Python Version:  2.6.6
Qt Version:      4.6.2, PyQt4 (API v1) 4.6.2 on Linux 

What steps will reproduce the problem?

 1. Open/Save a file from the GUI.
2. -
3. - What is the expected output? What do you see instead? It does nothing. No window appears 

Please provide any additional information below

. Fully up to date Centos 6.2 + PyQt4-webkit, PyQt4-webkit-devel from EPEL.

When trying to open/close a file:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/spyderlib/plugins/editor.py", line 1453, in load
    _("Open file"), basedir, EDIT_FILTERS)
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/compat.py", line 178, in getopenfilenames
    options=options)
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/compat.py", line 132, in _qfiledialog_wrapper
    filters, selectedfilter, options)
TypeError: argument 5 of QFileDialog.getOpenFileNamesAndFilter() has an invalid type

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/spyderlib/plugins/editor.py", line 1567, in save_as
    if editorstack.save_as():
  File "/usr/lib/python2.6/site-packages/spyderlib/widgets/editor.py", line 1333, in save_as
    filename = self.select_savename(finfo.filename)
  File "/usr/lib/python2.6/site-packages/spyderlib/widgets/editor.py", line 1322, in select_savename
    original_filename, EDIT_FILTERS)
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/compat.py", line 189, in getsavefilename
    options=options)
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/compat.py", line 132, in _qfiledialog_wrapper
    filters, selectedfilter, options)
TypeError: argument 5 of QFileDialog.getSaveFileNameAndFilter() has an invalid type

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=960_

**Comment by spyder-issues-migrator** [comment]
_From [boris.kr...@gmail.com](https://code.google.com/u/100894856217318981841/) on 2012-03-12T19:59:54Z_

I see the same issue on RHEL6

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T06:23:19Z_

Please try to do the following test in a Python interpreter:

\>>> from spyderlib.qt.QtGui import QApplication
\>>> qapp = QApplication([])
\>>> from spyderlib.qt.compat import *
\>>> getopenfilenames(None, 'caption', '', '*.py;;*.txt', '*.py')

The result should be a QFileDialog popping up and the following output in the console:
selectedfilter: '*.py'
([], u'*.py')

**Status:** Accepted  
  **Labels:** -Priority-Medium Priority-Critical OpSys-Linux Milestone-Release2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T06:23:36Z_

**Owner:** pierre.raybaut

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:43:47Z_

**Labels:** -Milestone-Release2.1 Milestone-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-18T13:57:17Z_

**Labels:** -Milestone-v2.1 MS-v2.1

**Comment by spyder-issues-migrator** [comment]
_From [danielzi...@gmail.com](https://code.google.com/u/117559567857443329925/) on 2012-03-24T10:22:01Z_

Hi, Pierre. The three first lines succeeded, but the last fails. Below is the output from python and ipython.

Thanks for your time.
Daniel.

\>>> from spyderlib.qt.QtGui import QApplication
\>>> qapp = QApplication([])
\>>> from spyderlib.qt.compat import *
\>>> getopenfilenames(None, 'caption', '', '*.py;;*.txt', '*.py')


python 2.6.6: 

Traceback (most recent call last):
  File "<stdin>", line 1, in \<module>
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/compat.py", line 178, in getopenfilenames
    options=options)
  File "/usr/lib/python2.6/site-packages/spyderlib/qt/compat.py", line 132, in _qfiledialog_wrapper
    filters, selectedfilter, options)
TypeError: argument 5 of QFileDialog.getOpenFileNamesAndFilter() has an invalid type



IPython 0.10:
\---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

/home/daniel/<ipython console> in \<module>()

/usr/lib/python2.6/site-packages/spyderlib/qt/compat.pyc in getopenfilenames(parent, caption, basedir, filters, selectedfilter, options)
    176                                 caption=caption, basedir=basedir,
    177                                 filters=filters, selectedfilter=selectedfilter,
--> 178                                 options=options)
    179 
    180 def getsavefilename(parent=None, caption='', basedir='', filters='',

/usr/lib/python2.6/site-packages/spyderlib/qt/compat.pyc in _qfiledialog_wrapper(attr, parent, caption, basedir, filters, selectedfilter, options)
    130     try:
    131         result = func(parent, caption, basedir,
--> 132                       filters, selectedfilter, options)
    133     finally:
    134         if sys.platform == "win32":

TypeError: argument 5 of QFileDialog.getOpenFileNamesAndFilter() has an invalid type

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-25T04:18:24Z_

Ok, then please try this:

\>>> from spyderlib.qt.QtGui import *
\>>> from spyderlib.qt.QtCore import *
\>>> qapp = QApplication([])
\>>> from spyderlib.qt.compat import *
\>>> getopenfilenames(None, QString('caption'), QString(), QString('*.py;;*.txt'), QString('*.py'))

and this:

\>>> from spyderlib.qt.QtGui import *
\>>> qapp = QApplication([])
\>>> QFileDialog.getOpenFileNamesAndFilter(None, 'caption', '', '*.py;;*.txt', '*.py')

the expected result is the same as before.

**Comment by spyder-issues-migrator** [comment]
_From [danielzi...@gmail.com](https://code.google.com/u/117559567857443329925/) on 2012-03-25T14:36:52Z_

Hi Pierre. The same as before: error at the las line.

\>>> from spyderlib.qt.QtGui import *
\>>> from spyderlib.qt.QtCore import *
\>>> qapp = QApplication([])
\>>> from spyderlib.qt.compat import *
\>>> getopenfilenames(None, QString('caption'), QString(), QString('*.py;;*.txt'), QString('*.py'))

\---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

/home/daniel/<ipython console> in \<module>()

/usr/lib/python2.6/site-packages/spyderlib/qt/compat.pyc in getopenfilenames(parent, caption, basedir, filters, selectedfilter, options)
    176                                 caption=caption, basedir=basedir,
    177                                 filters=filters, selectedfilter=selectedfilter,
--> 178                                 options=options)
    179 
    180 def getsavefilename(parent=None, caption='', basedir='', filters='',

/usr/lib/python2.6/site-packages/spyderlib/qt/compat.pyc in _qfiledialog_wrapper(attr, parent, caption, basedir, filters, selectedfilter, options)
    130     try:
    131         result = func(parent, caption, basedir,
--> 132                       filters, selectedfilter, options)
    133     finally:
    134         if sys.platform == "win32":

TypeError: argument 5 of QFileDialog.getOpenFileNamesAndFilter() has an invalid type


\>>> from spyderlib.qt.QtGui import *
\>>> qapp = QApplication([])
\>>> QFileDialog.getOpenFileNamesAndFilter(None, 'caption', '', '*.py;;*.txt', '*.py')

\---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

/home/daniel/<ipython console> in \<module>()

TypeError: argument 5 of QFileDialog.getOpenFileNamesAndFilter() has an invalid type

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-25T22:26:37Z_

As the second code sample is directly using the PyQt function, it may be a PyQt bug. Could you please try and make the QFileDialog.getFile[...] function work by trying to set expected arguments?

**Comment by spyder-issues-migrator** [comment]
_From [ghisv...@gmail.com](https://code.google.com/u/103124226509116879823/) on 2012-04-16T04:55:14Z_

Also, the Open Dialog works as expected in spyder-2.0.12. Using SL-6.2 here, but should be the same for CentOS 6.2.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-16T06:39:48Z_

That's because Spyder v2.0.12 use QFileDialog.getOpenFileNames instead of QFileDialog.getOpenFileNamesAndFilter.

If noone is able to make this *standard* PyQt function (getOpenFileNamesAndFilter) work on CentOS 6.2, I can't take action on this issue.

**Comment by spyder-issues-migrator** [comment]
_From [ghisv...@gmail.com](https://code.google.com/u/103124226509116879823/) on 2012-05-28T04:42:01Z_

Ok. Does it come from an incompatibility with Qt 4.6.2 in general (anybody running a distro with Qt 4.6.2 where it actually works ?) or is it specifically the version of Qt shipped by RedHat that is messed up ? In the latter case, is it worth filing a bug @-redhat ?

I am currently happy with 2.0.12, but some people might want the latest enhancement introduced in the 2.1 series.

**Comment by spyder-issues-migrator** [comment]
_From [formy...@googlemail.com](https://code.google.com/u/113999221398490367026/) on 2012-07-11T05:44:58Z_

It seems like the optional argument 5 "initialFilter" as it is called in the reference of QFileDialog.getOpenFileNamesAndFilter has been added to the interface in PyQt4 version >= 4.7. As a workaround for PyQt4 4.6 one can remove the "selectedfilter" argument in line 133 of compat.py:

try:
    result = func(parent, caption, basedir,
                  filters, options)

Pierre, what is this "initialFilter" for? The PyQt documentation doesn't really tell. Maybe you could check PyQt4.QtCore.PYQT_VERSION to determine which is the right function interface for getOpenFileNamesAndFilter?

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-16T11:30:31Z_

The initialFilter is the filter which will be selected when showing the open dialog box. The default value is 0, meaning that the first entry will be selected.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-16T11:37:00Z_

And you're right, the initialFilter has been introduced in Jan. 2010 for PyQt v4.7, whereas the function getOpenFilenamesAndFilter was for example introduced with PyQt v4.6.

So the right thing to do is indeed to test for the PyQt version, as you suggested.
I'll implement this ASAP.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-16T13:01:51Z_

Does applying the following patch works for you?

@@ -131,6 +131,9 @@
     try:
         result = func(parent, caption, basedir,
                       filters, selectedfilter, options)
+    except TypeError:
+        # PyQt v4.6 (see issue #960 )
+        result = func(parent, caption, basedir, filters, options)
     finally:
         if sys.platform == "win32":
             \# On Windows platforms: restore standard outputs

**Status:** Started

**Comment by spyder-issues-migrator** [comment]
_From [formy...@googlemail.com](https://code.google.com/u/113999221398490367026/) on 2012-07-22T22:37:21Z_

Sorry for the delay, I have been traveling. I will test the patch later today when I have access to the CentOS System.

**Comment by spyder-issues-migrator** [comment]
_From [formy...@googlemail.com](https://code.google.com/u/113999221398490367026/) on 2012-07-23T06:36:33Z_

The patch works as expected. Thank you!

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-07-27T11:34:08Z_

This issue was closed by revision 9eb59cdf5568 .

**Status:** Fixed

**Comment by m-gorbulsky** [comment]
Hello! 
I've got the same problem when running my application from the Spider IDE on windows. In PyCharm or from the command string verything works ok, but when I use Spider IDE i recieve:

TypeError: QFileDialog.getOpenFileName(QWidget parent=None, QString caption=QString(), QString directory=QString(), QString filter=QString(), QString selectedFilter=None, QFileDialog.Options options=0): argument 5 has unexpected type 'str'

Do I have to report a new issue?

**Comment by ccordoba12** [comment]
Please open a new issue and post a simple code example that reproduces your problem.
