### ISSUE TITLE
Pressing Delete at end of line should also lstrip the line below

### ISSUE THREAD

**Issue by definite-purple** [spyder-ide/spyder#9603]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** ~~and **Version**~~ sections below

## Problem Description
When reformatting code I often use the Delete-Key at the end of the line to move the contents of the next one onto the end.

It would be nice if pressing delete at the end of a line removed all space-characters between the cursor and the first non-space in the next line.

### What steps reproduce the problem?

1. Write two lines of code where the second line is indented
2. Move the cursor to the end of the first line
3. Press the delete key

### What is the expected output? What do you see instead?
I expect the next line to be appended to the current one, beginning with the first non-space.

Instead this happens:

![Delete at EOL](https://user-images.githubusercontent.com/32204163/59710590-87125f80-9209-11e9-8370-d2914feafeb4.gif)

**Comment by ccordoba12** [comment]
Sorry, I don't agree with this. It could be really confusing for newbies and I haven't seen other editors/IDEs to do that.
