### ISSUE TITLE
Analyze Button of Code Pane doesn't respect save before analysis Preference

### ISSUE THREAD

**Issue by definite-purple** [spyder-ide/spyder#9604]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
 * [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
With the respective preference chosen,  
starting a Code Analysis by pressing F8 saves the code file beforehand,  
but the Analyze Button of the Code Analysis Pane doesn't respect the preference.

### What steps reproduce the problem?

![Code Analysis](https://user-images.githubusercontent.com/32204163/59719214-30625100-921c-11e9-94a0-09e7d6440411.gif)
1. Set the Preference `Code Analysis -> Save file before analyzing it`
2. Modify some code, but don't save
3. Bring the Code Analysis Pane into the foreground and click the button with the green triangle

## Versions

* Spyder version: 4.0.0dev2
* Python version: Python 3.6.8 64-bit
* Qt version: Qt 5.12.3
* PyQt version: PyQt5 5.12.2
* Operating System name/version: Fedora 28 Linux 5.0.16-100.fc28.x86_64 

### Dependencies

pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.1.1 (OK)
psutil >=0.3       :  5.6.3 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  0.22.0 (OK)
numpy >=1.7        :  1.14.5 (OK)
sympy >=0.7.3      :  1.2 (OK)
cython >=0.21      :  0.29.10 (OK)
qtconsole >=4.2.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  2.2.3 (OK)
pylint >=0.25      :  2.3.1 (OK)

**Comment by ccordoba12** [comment]
Thanks for reporting. We'll try to fix this in beta4.
