### ISSUE TITLE
Minimize icon is out of center

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/spyder#9611]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice

## Problem Description

In outline and profile

![Screenshot Linux 2019-06-19 14 53 06](https://user-images.githubusercontent.com/5084939/59789382-313ec580-92a4-11e9-9dff-d0ca002bd965.png)

![Screenshot Linux 2019-06-19 14 51 32](https://user-images.githubusercontent.com/5084939/59789360-24ba6d00-92a4-11e9-841b-2ac8738e3dfd.png)

### What is the expected output? What do you see instead?

Expected to be at the center.

## Versions

- Spyder 4.0.0.dev0 (Commit: 1a079fc93) 
- Python 3.6.8 64-bit
- Qt 5.12.3
- PyQt5 5.12.2
- Linux 4.15.0-52-generic
- QdarkStyle Develop (Commit: 18ef745e2674) 

### Dependencies

pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
psutil >=0.3       :  5.6.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  None (NOK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.5.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  None (NOK)
pylint >=0.25      :  2.3.1 (OK)

**Comment by dpizetta** [comment]
![icons-image-out-off-center](https://user-images.githubusercontent.com/5084939/59791117-ca231000-92a7-11e9-9833-4fa40ce51428.gif)

**Comment by ccordoba12** [comment]
How can this be fixed? Is this not an issue that should go in QDarkstyle?

**Comment by dpizetta** [comment]
Oh, may changing the icon file or something like this issue/PR: #2504. This is not related to QDark because the image is not from there.  Note that only that icon is unaligned. Tks

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification!

**Comment by jnsebgosselin** [comment]
Instead of using the `spyder.inward` icon for this button, maybe using an icon from `fas` or `mdi` could be an option to solve this issue? Here are some options:

![image](https://user-images.githubusercontent.com/10170372/60388470-19272d00-9a80-11e9-8e16-427d84c2160e.png)

**Comment by jnsebgosselin** [comment]
Here is my favorite icon selection for this in the light and dark mode. I used the mdi icons for the collapse and expand selection as well to match the icons of the collapse and expand all buttons.

![image](https://user-images.githubusercontent.com/10170372/60388804-71602e00-9a84-11e9-9537-c50255607cba.png)

**Comment by ccordoba12** [comment]
> I used the mdi icons for the collapse and expand selection as well to match the icons of the collapse and expand all buttons.

I like this solution a lot. Thanks for looking into it!
