### ISSUE TITLE
URL awereness is broken in latest master

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9614]
## Problem Description

Ctrl clicking on a URL raises an error.

This was introduced in PR #9572.

https://github.com/spyder-ide/spyder/pull/9572/files#diff-52750ace6e2fd77d54b81a616c01ce5dR3447

A default value for the `full_uri ` variable should be defined at the start of the new `go_to_uri_from_cursor` method to avoid that.

### Paste Traceback/Error Below (if applicable)

```python-traceback
  File "C:\Users\User\spyder\spyder\plugins\editor\widgets\codeeditor.py", line 3663, in mousePressEvent
    if uri:
  File "C:\Users\User\spyder\spyder\plugins\editor\widgets\codeeditor.py", line 3465, in go_to_uri_from_cursor
    full_uri = 'mailto:' + full_uri
UnboundLocalError: local variable 'full_uri' referenced before assignment
```

## Versions

* Spyder 4.0.0.dev0 (Commit: f1c0e09e2) 
* Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10 

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.8 (OK)
sphinx >=0.6.6     :  1.8.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.3.1 (OK)
pandas >=0.13.1    :  0.23.4 (OK)
numpy >=1.7        :  1.16.3 (OK)
sympy >=0.7.3      :  1.4 (OK)
cython >=0.21      :  0.29.2 (OK)
qtconsole >=4.5.0  :  4.6.0.dev0 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  3.1.0 (OK)
pylint >=0.25      :  2.2.2 (OK)

```

**Comment by goanpeca** [comment]
Thanks for this! I will fix it now and add a test
