### ISSUE TITLE
Lowercase in text out of pattern

### ISSUE THREAD

**Issue by dpizetta** [spyder-ide/spyder#9616]
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice

## Problem Description

The solitary window that shows a lowercase text. PT-BR and EN. Maybe all languages.

![Screenshot Linux 2019-06-13 14 59 45](https://user-images.githubusercontent.com/5084939/59791259-179f7d00-92a8-11e9-9c80-f39330268586.png)

### What is the expected output? What do you see instead?

As other texts. 

Also I'll talk about the icon pattern for searching paths, but it was already mentioned in other issue.

## Versions

- Spyder 4.0.0.dev0 (Commit: 1a079fc93) 
- Python 3.6.8 64-bit
- Qt 5.12.3
- PyQt5 5.12.2
- Linux 4.15.0-52-generic
- QdarkStyle Develop (Commit: 18ef745e2674) 

### Dependencies

pygments >=2.0     :  2.4.2 (OK)
qdarkstyle >=2.6.4 :  2.8 (OK)
sphinx >=0.6.6     :  2.0.1 (OK)
psutil >=0.3       :  5.6.2 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.5.0 (OK)
pandas >=0.13.1    :  None (NOK)
numpy >=1.7        :  1.16.4 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.5.0  :  4.5.1 (OK)
IPython >=4.0      :  7.5.0 (OK)
matplotlib >=2.0.0 :  None (NOK)
pylint >=0.25      :  2.3.1 (OK)

**Comment by ccordoba12** [comment]
> The solitary window that shows a lowercase text

Is that screenshot the only place where this inconsistency appears?

**Comment by dpizetta** [comment]
Yep, that I've noticed.

**Comment by ccordoba12** [comment]
Thanks for the confirmation!

**Comment by oscargus** [comment]
I piggy-back on this with some related casing consistency issues in the preferences (inspired by this):

Tab-headings:
General -> Advanced Settings: should be "Advanced settings" (or change a lot of other tabs...)
Editor -> Run Code: "Run code"
iPython console -> Advanced Settings: "Advanced settings"

Box headings:
Python interpreter -> User Module Reloader (UMR): doubtful, but maybe "User module reloader (UMR)"
Run -> Working Directory settings: "Working directory settings"
iPython console -> Display -> Completion Type: "Completion type"
iPython console -> Advanced Settings -> Symbolic Mathematics: "Symbolic mathematics"

Sections:
Code Analysis: "Code analysis"

I can make a PR if wanted, but not sure how to regenerate/update the translation files in an easy way.
