### ISSUE TITLE
Spyder Scrolls to Top of Console

### ISSUE THREAD

**Issue by Elliptica1** [spyder-ide/spyder#9617]
## Problem Description

Whenever I switch between the iPython Console windows, when I switch back the console automatically scrolls to the top of the window. This makes it impossible to compare output across windows or keep track of one's place in the code. 

### What steps reproduce the problem?

1. Open two or more consoles and switch between them

### What is the expected output? What do you see instead?

The console should stay at the last executed line.

## Versions

* Spyder version: 3.3.3
* Python version:  3.6.8
* Operating System name/version:  Windows 10

### Dependencies
IPython >=4.0     :  6.1.0 (OK)
cython >=0.21     :  0.25.2 (OK)
jedi >=0.9.0      :  0.10.2 (OK)
matplotlib >=2.0.0:  3.0.2 (OK)
nbconvert >=4.0   :  5.2.1 (OK)
numpy >=1.7       :  1.15.4 (OK)
pandas >=0.13.1   :  0.19.2 (OK)
pycodestyle >=2.3 :  2.3.1 (OK)
pyflakes >=0.6.0  :  1.5.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.7.1 (OK)
qtconsole >=4.2.0 :  4.3.0 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.6.2 (OK)
sympy >=0.7.3     :  1.0 (OK)

**Comment by ccordoba12** [comment]
> qtconsole >=4.2.0 : 4.3.0 (OK)

Please update qtconsole to its latest version (4.5.1) to get the fix for this problem.
