### ISSUE TITLE
Highlighting errors and warnings wipe underlining of errors and warning.

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9631]
## Problem Description

When an error or warning is highlighted in the editor, the underlining of errors and warnings are removed. They are reapplied only when a call is make to process code analysis again.

### What steps reproduce the problem?

1. Go over an error or a warning in the error and warning panel of the Editor

![underine_bug](https://user-images.githubusercontent.com/10170372/59895268-ea3ef600-93b1-11e9-885d-529fc2f8f804.gif)

The problem is with the call to `clear_extra_selections` in the `highlight_line_warning` method of the `codeeditor.py`. I do not know how this could be fixed easily.

```python
    def highlight_line_warning(self, block_data):
        return
        self.clear_extra_selections('code_analysis')
        self.__highlight_selection('code_analysis', block_data.selection,
                                   background_color=block_data.color)
        self.update_extra_selections()
        self.linenumberarea.update()
        QTimer.singleShot(
            5000, lambda: self.clear_extra_selections('code_analysis'))
```

## Versions

* Spyder 4.0.0.dev0 (Commit: ffa3deb3d) 
* Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by jnsebgosselin** [comment]
I think to fix that we will need to add a new key to `__highlight_selection` so to distinguidh between `code_analysis` highlight and `code_analysis` underline.

**Comment by andfoy** [comment]
> I think to fix that we will need to add a new key to __highlight_selection so to distinguidh between code_analysis highlight and code_analysis underline.

Yes, that is the way! I have a branch with these modifications, if you are interested in this one

**Comment by jnsebgosselin** [comment]
@andfoy do you want to fix it since you already have a working solution? If you're busy with other things atm, I will take care of it though.

**Comment by ccordoba12** [comment]
@jnsebgosselin, if you can help @andfoy with this one, it'll be highly appreciated!
