### ISSUE TITLE
Make highlighting of errors and warning synchronized with errors and warnings popup show and hide

### ISSUE THREAD

**Issue by jnsebgosselin** [spyder-ide/spyder#9635]
## Problem Description

This is a feature/enhancement proposal.

Currently, hovering over an error or a warning icon in the `linenumber` panel of the Editor makes a tooltip instantly appear with a description of the errors/warnings and also highlight the corresponding errors/warnings in the Editor.

As soon as the mouse cursor is moved outside of the icon location, the tooltip disappears. However, the clearing of the highlights is on a 500 ms timer. In my opinion, this makes the highlighting of errors and warnings a little bit clumsy and irritating, because sometimes, the highlights are cleared very quickly, while at other times, it seems to take forever for them to be cleared.

I think the highlighting of the errors and warnings in the text should be sync with the showing and hiding of the errors and warnings tooltip and should not use a timer.

What do you guy think?

## Versions

* Spyder 4.0.0.dev0 (Commit: 5e72dd504) 
* Python 3.7.1 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

**Comment by ccordoba12** [comment]
I agree with this.

**Comment by jnsebgosselin** [comment]
Cool! It is a very simple fix, so I will take care of this shortly.

**Comment by ccordoba12** [comment]
Thanks!

**Comment by jnsebgosselin** [comment]
This is blocked by https://github.com/spyder-ide/spyder/issues/9631.
