### ISSUE TITLE
spyder is not plotting graph

### ISSUE THREAD

**Issue by anonymous645** [spyder-ide/spyder#9653]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

**Comment by anonymous645** [comment]
![Screenshot (87)](https://user-images.githubusercontent.com/49645689/59975888-302ad280-95db-11e9-9dea-1bdb5c43044f.png)
whenever I try to plot any graph using matplotlib . spyder crashes every time . tried updating and tried every possible trick to debug it but nothing happened.

**Comment by ccordoba12** [comment]
You need to change you backend to Automatic in

    Tools > Preferences > IPython console > Graphics

**Comment by ShubhangJani** [comment]
@ccordoba12 That still isn't the final solution, unfortunately. I always had my graphic settings to Automatic and for some reason my plots are not being displayed when using matplotlib on spyder 4.

The code runs, but once I run the selected code that has to do with plotting, spyder just crashes.

Please let me know.

**Comment by hubertmucha** [comment]
i have the same porblem

**Comment by ShubhangJani** [comment]
@hubertmucha Hello. I actually figured out the solution (at least from my problem). I was performing K-Nearest Neighbors when doing mine. In my code, my step value was really really small (causing the IDE to crash due to the intense specificity. My step was 0.0001. If you use step = 0.01, it should work for you:
 
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0].min() - 1, stop = x_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = x_set[:, 1].min() - 1, stop = x_set[:, 1].max() + 1, step = 0.01))
plt.contourf(x1, x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.shape),
             alpha = 0.75, cmap = ListedColormap(('red', 'green')))

If you are using Kernel SVM polynomial type, make sure you decrease your degree value.

**Comment by bassemkabesh** [comment]
I think you will find the answer here 
https://stackoverflow.com/questions/32774520/why-matplotlib-give-the-error-matplotlib-lines-line2d-object-at-0x0392a9d0
