### ISSUE TITLE
Automatic error report

### ISSUE THREAD

**Issue by acekanth** [spyder-ide/spyder#9656]
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>
![image](https://user-images.githubusercontent.com/44270906/59978780-d7206600-95fd-11e9-906b-189372fe2493.png)
![spyder_error](https://user-images.githubusercontent.com/44270906/59978798-06cf6e00-95fe-11e9-9bea-048165719d1f.jpg)

**Comment by ccordoba12** [comment]
Please reopen again because this image didn't upload correctly.
