### ISSUE TITLE
run cell (ctrl+return) option not working

### ISSUE THREAD

**Issue by SudhanshuShanker** [spyder-ide/spyder#9690]
### What steps will reproduce the problem?

Using "run cell" option runs the whole file.            

## Versions

* Spyder version: 4.0.0b2 
* Python version: 3.6.7
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating System: Linux 4.18.0-15-generic

### Dependencies

```
pygments >=2.0     :  2.3.1 (OK)
qdarkstyle >=2.6.4 :  2.7 (OK)
sphinx >=0.6.6     :  2.1.0 (OK)
psutil >=0.3       :  5.6.1 (OK)
pyls >=0.19.0;<0.25:  0.24.0 (OK)
nbconvert >=4.0    :  5.4.1 (OK)
pandas >=0.13.1    :  0.24.2 (OK)
numpy >=1.7        :  1.16.3 (OK)
sympy >=0.7.3      :  None (NOK)
cython >=0.21      :  None (NOK)
qtconsole >=4.2.0  :  4.4.3 (OK)
IPython >=4.0      :  7.4.0 (OK)
matplotlib >=2.0.0 :  3.0.3 (OK)
pylint >=0.25      :  2.3.1 (OK)
```

**Comment by bcolsen** [comment]
@SudhanshuShanker Thank you for trying out Spyder 4!

How are you defining your code cells?
https://docs.spyder-ide.org/editor.html#defining-code-cells

There are new "run cell" mechanics in version 4, if there are no code cells defined in the file (with `# %%` for example) "run cell" will now run the whole file.

If you have a file with code cells properly defined and it is still running the whole file, can you show us the code or a reproducible example?

**Comment by SudhanshuShanker** [comment]
In spyder3, one can select a chunk of code (using a mouse) to use the "run cell" feature to execute selected lines only.  But, this is not working in the current beta version. I like this feature as it makes the analysis of different parts of code extremely convenient.

**Comment by bcolsen** [comment]
That option is called "Run selection or current line". It is in the toolbar or use the the shortcut key `F9`. I don't think this default behavior has changed from spyder3 to spyder4.

**Comment by ccordoba12** [comment]
Yeah, if "Run cell" worked on selections in Spyder 3, that was a bug and not a feature. And that was fixed in Spyder 4.

**Comment by Johnnyboycurtis** [comment]
Can "Run selection or current line" be bound to CTRL+ENTER? I don't find defining cells apriori convenient as I sometimes I need to run varying permutations of lines ad hoc. 

I do not manually changing this behavior if someone can point me to a file where key bindings are located.

Otherwise, I think I will revert back to Spyder 3.

**Comment by Joey1237** [comment]
This problem can be solved by defining  code cells.
https://docs.spyder-ide.org/editor.html#defining-code-cells
Thanks !

**Comment by oster33** [comment]
My cells appear to be properly defined and I can run a selection, but am unable to run a full cell using either ^enter or the run cell button.  Here is what I get when I use control enter. 
In [37]: runcell(3, with the path to the file that I am trying to run)
