### ISSUE TITLE
Online Help pane doesn't support the dark theme

### ISSUE THREAD

**Issue by dalthviz** [spyder-ide/spyder#9696]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

![imagen](https://user-images.githubusercontent.com/16781833/60229016-21058800-985a-11e9-8658-6b7e1ae5d794.png)

## Versions

* Spyder version: 4.0beta2
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1

**Comment by mohitisgreat** [comment]
I don't think it is a spyder specific thing, since the reference documentation of python (HTML format) is only available in only one theme(light theme). Spyder just serve the reference documentation simply like browsers do. It is not an issue with spyder but the python reference documentation.

**Comment by dalthviz** [comment]
Hi @mohitisgreat this issue is intended to remaind us that the `Online Help` pane should [inject some sort of CSS/Javascript](https://doc.qt.io/qt-5/qtwebengine-webenginewidgets-stylesheetbrowser-example.html) with the dark theme when rendering the pages `pydoc` generates (in order to show the documentation in a more integrated way with the dark theme). Although, as you say, the documentation is served as it is from `pydoc` and searching a little bit even an issue in Python exists to make it look more appealing [here](https://bugs.python.org/issue10716). The idea is resolve this over the Spyder side (at least for the moment)

**Comment by ccordoba12** [comment]
@dalthviz, please take a look at this project

https://github.com/aroberge/mod_pydoc

for a Python approach on how to customize the Pydoc css.

I think we could patch/extend the `pydoc` module instead of providing a modified copy of the entire module (as that project does).
