### ISSUE TITLE
Cannot install anymore spyder 4.0.0 b2

### ISSUE THREAD

**Issue by rlloretb** [spyder-ide/spyder#9707]
I upgraded to Anaconda3 and MacOS Mojave and I cannot install the beta 2 anymore.

conda install -c spyder-ide spyder=4.0.0b2

UnsatisfiableError: The following specifications were found to be incompatible with each other:
  - anaconda==2019.03=py37_0 -> importlib_metadata==0.8=py37_0 -> zipp[version='>=0.3.2']
  - anaconda==2019.03=py37_0 -> spyder==3.3.3=py37_0 -> spyder-kernels[version='>=0.4.2,<1']
  - importlib_metadata
  - pkgs/main/osx-64::path.py==11.5.0=py37_0 -> importlib_metadata[version='>=0.5']
  - spyder-kernels
  - spyder=4.0.0b2 -> spyder-kernels[version='>=1.2,<1.4']
  - zipp

**Comment by ccordoba12** [comment]
Please uninstall your current spyder and spyder-kernels packages and try again.

**Comment by rlloretb** [comment]
Thank you very much. 
Note: I had to reinstall many additional packages afterwards, like numpy and pandas.

**Comment by ccordoba12** [comment]
Sorry about that, but at least it worked. This should be fixed in beta3, to be released in a couple of days.
