### ISSUE TITLE
Unable to import statsmodels.formula.api due to AttributeError: module 'scipy' has no attribute 'special'

### ISSUE THREAD

**Issue by thisisaggarwal** [spyder-ide/spyder#9715]
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

I'm trying to import statsmodels.formula.api but keep getting AttributeError: module 'scipy' has no attribute 'special'. Earlier I had same error with fraction instead of special which was resolved by downgrading scipy to 1.2.0 from 1.3.0

### What steps reproduce the problem?

1. import statsmodels.formula.api as sm
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

import statsmodels.formula.api as sm
Traceback (most recent call last):

  File "<ipython-input-16-5ad1e596ef83>", line 1, in <module>
    import statsmodels.formula.api as sm

  File "/home/mr_aggarwal/anaconda3/lib/python3.6/site-packages/statsmodels/formula/api.py", line 15, in <module>
    from statsmodels.discrete.discrete_model import MNLogit

  File "/home/mr_aggarwal/anaconda3/lib/python3.6/site-packages/statsmodels/discrete/discrete_model.py", line 45, in <module>
    from statsmodels.distributions import genpoisson_p

  File "/home/mr_aggarwal/anaconda3/lib/python3.6/site-packages/statsmodels/distributions/__init__.py", line 2, in <module>
    from .edgeworth import ExpandedNormal

  File "/home/mr_aggarwal/anaconda3/lib/python3.6/site-packages/statsmodels/distributions/edgeworth.py", line 9, in <module>
    import scipy.special as special

AttributeError: module 'scipy' has no attribute 'special'


```

## Versions

* Spyder version: 3.3.4
* Python version: 3.6.8
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Linux 4.15.0-51-generic

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  0.28.5 (OK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
psutil >=0.3      :  5.4.7 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
rope >=0.9.4      :  0.11.0 (OK)
sphinx >=0.6.6    :  1.7.9 (OK)
sympy >=0.7.3     :  1.2 (OK)
```

**Comment by ccordoba12** [comment]
This is not a Spyder problem, but an installation one with Scipy.

> Earlier I had same error with fraction instead of special which was resolved by downgrading scipy to 1.2.0 from 1.3.0

If you used pip to perform this operation then you most probably corrupted your installation and that's the source of your problem. If not, please report this in Anaconda:

https://github.com/ContinuumIO/anaconda-issues/issues/
