### ISSUE TITLE
Issue faced while the app is opening

### ISSUE THREAD

**Issue by samarthasahoo** [spyder-ide/spyder#9729]
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

    plugin = mod.PLUGIN_CLASS(self)
AttributeError: '_ModuleMock' object has no attribute 'PLUGIN_CLASS'

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.8
* Qt Versions: 5.9.6, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  2.1.1 (OK)
pycodestyle >=2.3:  2.5.0 (OK)
pygments >=2.0   :  2.4.2 (OK)
pandas >=0.13.1  :  0.24.2 (OK)
numpy >=1.7      :  1.16.4 (OK)
sphinx >=0.6.6   :  2.1.0 (OK)
rope >=0.9.4     :  0.14.0 (OK)
jedi >=0.9.0     :  0.13.3 (OK)
nbconvert >=4.0  :  5.5.0 (OK)
sympy >=0.7.3    :  1.4 (OK)
cython >=0.21    :  0.29.10 (OK)
qtconsole >=4.2.0:  4.5.1 (OK)
IPython >=4.0    :  7.5.0 (OK)
pylint >=0.25    :  2.3.1 (OK)

```

**Comment by ccordoba12** [comment]
This is fixed in our latest version. Please update by opening the Anaconda Prompt and running there

    conda install spyder=3.3.4
