### ISSUE TITLE
Spyder 3.5.5 update deletes all my already installed packages

### ISSUE THREAD

**Issue by garethwalkom** [spyder-ide/spyder#9730]
## Problem Description

When I updated my Spyder to version 3.5.5 in the Anaconda Prompt, and then opened Spyder, the following packages needed to be installed again:
- Numpy
- Pandas
- Matplotlib
- Imageio
- Scipy
- Scikit-image

### What steps reproduce the problem?

1.  Open Anaconda Prompt
2.  $ conda update spyder
3.  $ spyder

### What is the expected output? What do you see instead?

Expected Spyder to have kept all my packages after updating Spyder to 3.5.5

## Versions

* Spyder version: 3.5.5
* Python version: 3.7.1 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
IPython >=4.0     :  7.6.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  None (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  None (OK)
pandas >=0.13.1   :  None (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.0 (OK)
sympy >=0.7.3     :  None (NOK)
```

**Comment by ccordoba12** [comment]
This is not a problem but with Anaconda. Please report it there:

https://github.com/ContinuumIO/anaconda-issues/issues/
