### ISSUE TITLE
unable to connect to kernel for the spyder console

### ISSUE THREAD

**Issue by StevenDowney86** [spyder-ide/spyder#9736]
### What steps will reproduce the problem?

I submitted an issue two days ago and you responded back with the recommendation to:

"conda install spyder‑kernels=0.*

The dash in the command above is not the same dash that you get in a latin keyboard, which is -. So that's the problem.

The correct command is

 conda install spyder-kernels=0.*"

I then entered the updated command you recommended and my terminal showed:
 

(base) Stevens-MacBook-Pro:~ downey$ conda install spyder-kernels=0.*
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

I then opened Spyder and the same message showed in the console:

"An error ocurred while starting the kernel

Your Python environment or installation doesn't have the spyder-kernels....

You can install by running in a system terminal:

conda install spyder-kernels=0*

..."

Do you have any other recommendations?

As an aside, I am a beginner with Spyder and was using pip in the terminal to try to install packages last week when I had the issue. I also started learning and using git in the terminal but I don't see how that would affect Spyder.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Darwin 18.6.0

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
psutil >=0.3      :  5.6.1 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
> Do you have any other recommendations?

No, and please **do not** open the same issue again.

I already told what's the problem, so please write the command in the terminal instead of copying it from our IPython console.

**Comment by ccordoba12** [comment]
> then entered the updated command you recommended and my terminal showed

Sorry, I didn't see this. You need to install spyder-kernels In your specific environment, not in the base one.

Please see

https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder

to understand how to work with conda environments.
