### ISSUE TITLE
Auto cell proposal

### ISSUE THREAD

**Issue by loczaj** [spyder-ide/spyder#9738]
Dear Developers,

I would like to propose a new feature to Spyder IDE.

The "run cell" feature of the IDE is very handy, however it could be improved.
It would be nice if the cell boundaries (if not defined by %%) would be automatically detected. This would enable a very comfortable usage that enables evaluation of top level classes, functions, etc. one by one (in console) without the need of defining cells in the code.

This would work as the "run statement" function in SQL Developer.
The top level (outermost) def statement or class definition could be evaluated at once (with all sub statements). This enables running a module by evaluating its top level statements on by one. This also enables re-evaluating a modified def statement or class definition inside a module.

Statement boundaries could be detected automatically this way:
A new line followed by not indented non comment.

I crated a simple patch introducing this behavior. I know this patch (and the algorithm above) is not 100 percent correct, but it can show the proposal in live, and allows experimenting around it.

Result of diff -wu base.335.py spyder/widgets/sourcecode/base.py is attached to the issue. Diff is created against original base.py in version 3.3.5.

Thanks, regards,
Roland Lohner
[auto-cells.patch.txt](https://github.com/spyder-ide/spyder/files/3355435/auto-cells.patch.txt)

**Comment by ccordoba12** [comment]
Sorry, although a cool idea in principle, this would be a nightmare to implement correctly in practice for all possible uses cases and scenarios.

As the Zen of Python goes: "Explicit is better than implicit", sorry.

**Comment by loczaj** [comment]
Hi Carlos,
Thanks for the fast reply.
I understand and accept your point.
Best wishes! Roland

**Comment by ccordoba12** [comment]
Thanks for understanding!
