### ISSUE TITLE
Videocamera resource not gettting closed after script termination

### ISSUE THREAD

**Issue by DebalB** [spyder-ide/spyder#9744]
## Problem Description
I am running a Python script using Spyder 3.3.5 (Python 3.7.3) on windows10.
The script opens a video stream using imutils package and captures images and closes the stream before exiting.
the problem i face is that the video camera stays ON even after the script has finished.
only restarting Spyder helps turn OFF the video camera.
i dont face this issue when using command line or Pycharm to execute the same script.

### What steps reproduce the problem?
run the following code snippet. ensure imutils package is installed
~~~~~~~~~~~~~~~
from imutils.video import VideoStream
import time
vs = VideoStream(src=0).start()
# some code in between ........
time.sleep(5.0)
vs.stop()
~~~~~~~~~~~~~~~~~
### What is the expected output? What do you see instead?
the problem i face is that the video camera stays ON even after the script has finished.
only restarting Spyder helps turn OFF the video camera.
I expect the videocamera to be in OFF state once script has finished executing

### Paste Traceback/Error Below (if applicable)
NA

## Versions
* Spyder version: 3.3.5
* Python version: 3.7.3
* Qt version: NA
* PyQt version: NA
* Operating System name/version: Windows 10 Home edition

### Dependencies
imutils package

**Comment by ccordoba12** [comment]
Please try to run

    %reset -f

to see if that fixes your problem.

**Comment by ccordoba12** [comment]
I the IPython console, I meant.

**Comment by DebalB** [comment]
hi
thanks for the workaround.
i have tried it a couple of times and it seems to be working.
however is there any plan to fix this issue in the next version?

**Comment by ccordoba12** [comment]
You can make that permanent for your file by going to the menu

    Run > Configuration per file > Remove all variables before execution

or for all files by going to

    Tools > Preferences > Run > Remove all variables before execution
