### ISSUE TITLE
Separator on plots plugin acts more like a button than a resize area

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9747]
The separator has the appearance of allowing the user to change the width gradually, but currently the behavior is more of something being toggled (a button instead of a draggable area)

![plots](https://user-images.githubusercontent.com/3627835/60556568-99ab8f00-9d07-11e9-935d-6781402304c3.gif)

**Comment by jnsebgosselin** [comment]
Is a button like in adobe reader what you have in mind? Or we could also simply add a button to the plugin toolbar that allow to hide/show the thumbnails scrollbar? The later option would be easier to do.

![acrobat_sidebar_button](https://user-images.githubusercontent.com/10170372/60676208-4f7ff600-9e4c-11e9-806e-7e3b136efca6.gif)

**Comment by goanpeca** [comment]
>Is a button like in adobe reader what you have in mind?

If that is the road we are taking then yes, (it would be a tool button with a expanding vertical policy)

>The later option would be easier to do.

I guess, but the UX of having the button right there feels nicer? Besides ease of implementation any particular preferences @jnsebgosselin ?

The other option is that the dragging actually reduces gradually the size of the thumbnails (from a minimum value, to a maximum value)

**Comment by jnsebgosselin** [comment]
> The other option is that the dragging actually reduces gradually the size of the thumbnails (from a minimum value, to a maximum value)

Is it something that would be worth implementing? I think this wouldn't be too complicated to do and could be done as part of PR #9720.

**Comment by goanpeca** [comment]
I do not have a particular favorite to be honest, it is the UX/UI that bothers me. Either way is fine by me as long as the UX/UI is consistent.

- If a toggle button, hide show the thumbnails.
- If a size grip, allow for gradual change of thumbnail

If either seems like too much for nothing then I guess the button on the toolbar is fine 🤷‍♂

Thoughts @ccordoba12 ?

**Comment by ccordoba12** [comment]
> The other option is that the dragging actually reduces gradually the size of the thumbnails (from a minimum value, to a maximum value)

I also prefer this option instead of the current behavior. Thankfully is not too complicated to implement (according to @jnsebgosselin), so it'd be nice to have it as part of PR #9720.

**Comment by jnsebgosselin** [comment]
> 
> 
> > The other option is that the dragging actually reduces gradually the size of the thumbnails (from a minimum value, to a maximum value)
> 
> I also prefer this option instead of the current behavior. Thankfully is not too complicated to implement (according to @jnsebgosselin), so it'd be nice to have it as part of PR #9720.

Ok good, I'll work on it 👍

**Comment by goanpeca** [comment]
Thanks @jnsebgosselin !

**Comment by goanpeca** [comment]
Question @jnsebgosselin then in this case we would still need the toggle button in the toolbar? so that users can completely hide it? The resize should probably have a minimum value (otherwise it would be "lost"?

**Comment by jnsebgosselin** [comment]
> Question @jnsebgosselin then in this case we would still need the toggle button in the toolbar? so that users can completely hide it? The resize should probably have a minimum value (otherwise it would be "lost"?

We can set a minimum value on the resize and if the user continue to drag after hitting the minimum, the scrollbar would collapse.

That being said, I think that also adding a collapse button in the toolbar is a good idea.
