### ISSUE TITLE
IPythone console crashes in Ubuntu 16.04 only

### ISSUE THREAD

**Issue by Jarvine** [spyder-ide/spyder#9752]
### Issue Report Checklist

* [*] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [*] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [*] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [*] Tried basic troubleshooting (if a bug/error)
    * [*] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [*] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [*] Tried the other applicable steps from the Troubleshooting Guide
* [*] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Python scripts causes the IPython console kernel to become busy, which is then immediately followed by both the desktop freezing and the Ubuntu (16.04 LTS) machine re-starting spontaneously (i.e., crashes). I am running Spyder in Anaconda  (Python 3.6.8 64-bit, Qt 5.9.6, PyQt5 5.9.2, Linux 4.4.0-154-generic).  

Note, this same Python script is successfully run on:
Windows 7 (Anaconda 1.9.6, Spyder 3.3.2, Python 3.6.7 64-bit, Qt 5.9.6, PyQt5 5.9.2, Windows 7), 
Windows 10 (Python 3.6.8 64-bit, Qt 5.9.6, PyQt5 5.9.2, Windows 10), and 
Mac (MacOS High Sierra (10.13.6), Anaconda 1.9.7, Python 3.6.6, Qt 5.9.6, PyQt5 5.9.2, Darwin 17.7.0).  

Initial troubleshooting narrowed the problem to the lines in the script calling for plt.tight_layout().  In debug mode the script would run up to the next plt.tight_layout() call out and then hang, freeze, automatically re-start Ubuntu machine.  All such lines were sequentially commented out until the script ran successfully to full completion (i.e., performs a series of statistical tests, time-series analysis, and plots various graphs both to IPython console and file).  Re-ran the script (F5), without making ANY changes, and the kernel hangs, resulting in both a freezing of the screen and a re-start of the Ubuntu machine.  

Logged in, open terminal, typed anaconda-navigator, changed environments in Anaconda to Py3.7, launched Spyder (3.3.3), ran the same script (with all plt.tight_layout() commented out), and the script ran successfully to completion.  Re-started the kernel in the IPython console before attempting to re-run the script, but this caused a few errors in the IPython console that froze the screen and caused the Ubuntu machine to re-start.  After re-start, I opened new terminal window, typed anaconda-navigator, and the screen froze and system crashed.  Once the system re-started, I manually shut down the system, re-started, opened new terminal window, successfully launched anaconda-navigator, selected Py3.7 environment, launched Spyder (3.3.3) and then IPython hung at "Kernel connecting..."

Logged in, open new terminal window, successfully launched anaconda-navigator, selected py36 env, changed version of Spyder to 3.3.2 to see if version has an effect, closed Anaconda, logged out of Ubuntu, logged in, opened new window, successfully launched anaconda-navigator, selected py36 environment, launched Spyder 3.3.2 and the system hung and automatically re-started.

Also note that I can run other Python scripts in Anaconda/Spyder in either environment (py36 or py37), such as a bi-directional LSTM models, ConvNet models, etc.  But once these problems start, it's very difficult to launch Spyder without causing the system to hang.

### What steps reproduce the problem?

1. ananconda-navigator in terminal prompt
2. Select environment, launch Spyder (sometimes it hangs right here)
3. F5, kernel busy - hangs

### What is the expected output? What do you see instead?
Kernel is busy, IPython console hangs (no output), desktop freezes, computer self re-starts

### Paste Traceback/Error Below (if applicable)

Nothing.  But this is an error I get upon launching anaconda from the terminal prompt:

/usr/local/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py:1364: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(f)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.5
* Python version: Python 3.6.8 64-bit
* Qt version:  Qt 5.9.6
* PyQt version:  PyQt5 5.9.2
* Operating System name/version:  Linux 4.4.0-154-generic (Ubuntu 16.04 LTS)

### Dependencies

```
PASTE DEPENDENCIES HERE
```
IPython >=4.0     :  7.6.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.0 (OK)
sympy >=0.7.3     :  None (NOK)

**Comment by ccordoba12** [comment]
A couple of questions:

1. Does your problem appear if you run your code in the Jupyter notebook?
2. What happens when you run the code in qtconsole?

If you experience the same result in any of those, then the problem is not caused by Spyder but by something else (maybe Matplotlib, since you said that `plt.tight_layout()`).

If that's not the case, you have to share with us a minimal source code that reproduces this problem. Please don't submit your entire code because we won't be able to run it, just the simplest code that generates the hang and subsequent restart.

With that code we will be able to investigate what could be causing your problem.

**Comment by Jarvine** [comment]
Hi Carlos,

I ran the code in Jupyter notebook and it crashed (i.e., the screen froze and Ubuntu rebooted, as before).  I then parsed the code into sections and created separate Jupyter notebooks for each section to see where it crashes.  Here is the clincher, I was able to get each notebook (each parsed section of the code) to run without issue until I reached a particular graph before the system crashed.  Then I went back and ran each notebook again, and then I crashed at a different notebooks (i.e., different graph).  Eventually, I crashed for each notebook that produced a graph as output.  I created a brand new notebook, copied the script from one of the notebooks that crashed, and it ran successfully.  Then I ran it again, and it crashed.

The problem appears intermittent.  One second I can run the code (e.g., in Jupyter notebook) and produce the desired output (e.g., a graph): the next second it causes my Ubuntu machine to crash, and from then it seems to be impossible to run the code successfully.

I have attached the notebook (with the expected output) that has crashed though at first it ran successfully multiple times.  I have also attached a small data file (.csv).

[Issue_9752_files.zip](https://github.com/spyder-ide/spyder/files/3363488/Issue_9752_files.zip)

Thanks!

**Comment by ccordoba12** [comment]
We'd really like to help you but if you're seeing the same problem in the notebook, it means it's not caused by Spyder (nor by the notebook, for that matter).

If a Matplotlib plot is generating the issue, then my suggestion is to report it there.
