### ISSUE TITLE
Text in help search bar becomes selected once help is displayed

### ISSUE THREAD

**Issue by david-cortes** [spyder-ide/spyder#9757]
Following issues https://github.com/spyder-ide/spyder/issues/9143 and https://github.com/spyder-ide/spyder/issues/8762

**Steps to reproduce:**
* Import some package (e.g. `import numpy as np`)
* Try to get help for some function from that package by typing it in the editor (e.g. `np.arange`)

**Expected behavior:** should work in some way that I could quickly type `module.submodule.function_or_method` and get its helps displayed in the help pane.

**Actual behavior:** as soon as something that matches a package name (aliased or not) or something else with docs of its own is input, the whole text in the bar becomes selected, e.g. if I try to quickly type `np.arange` or `pandas.DataFrame.from_dict`, once it reaches `np` or `pandas` or `pandas.DataFrame`, the text becomes selected, and thus replaced with the next keystroke.

**Setup:** Spyder 3.3.5, running on Windows 10.

**Comment by ccordoba12** [comment]
@dalthviz, please give priority to this one over your other work so we can release 3.3.6 as soon as possible. Thanks!
