### ISSUE TITLE
Pane tab label cropped on activation

### ISSUE THREAD

**Issue by oscargus** [spyder-ide/spyder#9766]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When activating a pane, the width of the tab is a bit too small (see the "Find" tab):
![image](https://user-images.githubusercontent.com/8114497/60755888-80039380-9ff6-11e9-8494-45da07432323.png)

However, after a restart (or closing and opening again), it is back to its correct size (also showing that this is a general problem as the breakpoints tab show the same behaviour):
![image](https://user-images.githubusercontent.com/8114497/60755909-d8d32c00-9ff6-11e9-8d51-dc9fd506609d.png)

(I seem to recall some issue that may be related to this, but I cannot seem to find it now...)

### What steps reproduce the problem?

1. Start a new session
2. Open a tab/pane which has not been opened

### What is the expected output? What do you see instead?
Correct size first time it is started.

## Versions

* Spyder version: 4.0.0.dev0 (works in 3.3.4 but there is much more spacing there so hard to tell...)
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.0 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.10 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.5.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@goanpeca, please take a look at this one.

**Comment by goanpeca** [comment]
Fix at https://github.com/ColinDuquesnoy/QDarkStyleSheet/pull/198

**Comment by goanpeca** [comment]
@oscargus if you would like to help with the review of this fix, I can explain how to install QDarkStyle in dev mode, so you can test the fixes right away.

**Comment by oscargus** [comment]
@goanpeca I've been away for a few days. 

Thanks for solving this! Not sure how/when QDarkStyle is updated within Spyder, but good to know that it is sorted. Should I close this now or wait before it is propagated to Spyder?

**Comment by goanpeca** [comment]
Let's wait to be sure ;-)

**Comment by ccordoba12** [comment]
Closing because this should be fixed in the next QDarkstyle release.
