### ISSUE TITLE
Close wiki unify content on repository, docs repository or on website

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder#9767]
@ccordoba12 removed all the wiki pages. Can you disable the wiki?

The content can be found here if needed

[spyder.wiki.zip](https://github.com/spyder-ide/spyder/files/3364991/spyder.wiki.zip)

We should probably move the ROADMAP (beta, or normal) to either the spyder repo or the docs repo or the website.

@oscargus you can use the file I linked with the contents to update the contribution.md file. Thanks!

**Comment by oscargus** [comment]
OK! I realized that the "Troubleshooting..." entry in the help menu is pointing to a Wiki page, now not reachable.

**Comment by goanpeca** [comment]
@oscargus I can restore that page if needed. But we should really unify everything under the website/or the docs.

**Comment by ccordoba12** [comment]
> removed all the wiki pages. Can you disable the wiki?

Why did you do that??!!!! We had important resources there, referenced in a lot of StackOverflow questions!! Please revert the wiki **immediately**.

I think I only agreed to remove the development pages, which I didn't know they existed (because I didn't create them), no to remove the entire wiki!

**Comment by ccordoba12** [comment]
> We should probably move the ROADMAP (beta, or normal) to either the spyder repo or the docs repo or the website.

And also the beta changelog, I mean, come on!! This is completely non-sensical!

You should have removed the wiki once all pages will be placed in other places, at the very least!

**Comment by ccordoba12** [comment]
@goanpeca, please close this issue once you restore the wiki. This is not the way to go, because the wiki is nice to have for certain things.

The only bad thing is to have outdated pages that people is trying to use to get started with Spyder development.

**Comment by ccordoba12** [comment]
@goanpeca, I'm very sorry for my outburst here. It's just that for a moment I thought we lost all the time and effort invested in several critical pages placed in our wiki.

I'm not against other developers taking the initiative and doing things on their own. But a decision as important as removing the wiki completely without moving its referenced pages to other places must be consulted first with the rest of the core team, or at least with me privately.

**Comment by goanpeca** [comment]
@ccordoba12 apology accepted.

From the conversation, we had over at the other issue I had understood that the wiki should be removed (not only the sections regarding contributing to the project), so my bad there. The wiki is a repository and I had the clone in my computer so restoring it was not really an issue.

However, this is not the first time such *outbursts* arise, as @CAM-Gerlach can unfortunately attest, and these kind of replies to contributors to the project are not acceptable, even more so taking into account the [Code of Conduct](https://github.com/spyder-ide/spyder/blob/master/CODE_OF_CONDUCT.md#contributor-covenant-code-of-conduct) you uploaded a few weeks ago.

**Comment by ccordoba12** [comment]
> However, this is not the first time such outbursts arise, as @CAM-Gerlach can unfortunately attest, and these kind of replies to contributors to the project are not acceptable, even more so taking into account the Code of Conduct you uploaded a few weeks ago.

Ok, I totally agree with you on this point. I'll open an issue in our private repo to discuss this situation with the core team.
