### ISSUE TITLE
error in spyder 

### ISSUE THREAD

**Issue by shorooq-alazzam** [spyder-ide/spyder#9770]
### Issue Report Checklist

* [1 ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [2 ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ 3] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
i had this error 
  raise ValueError("np.nan is an invalid document, expected byte or "

ValueError: np.nan is an invalid document, expected byte or unicode string.

### What steps reproduce the problem?

1. i searched to solve this error but i didn't find any solution 
2. 
3. 

### What is the expected output? What do you see instead?
the code must run without any problem because it was running before 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version:  3.3.3
* Python version:3.7 
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version:Win10 x64bit

**Comment by ccordoba12** [comment]
This is not a problem with Spyder but with your code, sorry.
