### ISSUE TITLE
Equation is not displayed in Help pane on Windows

### ISSUE THREAD

**Issue by ok97465** [spyder-ide/spyder#9785]
## Description
Equation is not displayed in help pane in windows.
Equation is displayed in help pane in linux(manjaro).

### What steps will reproduce the problem?

1. type -> from numpy import convolve
2. request help info of convolve

![dark](https://user-images.githubusercontent.com/22970578/60816179-1f31b200-a1d4-11e9-9606-5c4c39528fc5.png)
[windows]

![image](https://user-images.githubusercontent.com/22970578/60816951-b8ad9380-a1d5-11e9-8f5a-0bb1d5e3f96e.png)
[majaro]

## Versions

* Spyder version: 4.0.0b3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, could you test this on Windows? Thanks!

**Comment by dalthviz** [comment]
@ccordoba12 testing this on Windows 8.1 I see the same behaviour reported by @ok97465 :

![imagen](https://user-images.githubusercontent.com/16781833/60831069-4eb5cf80-a17e-11e9-9ea7-28acf7add748.png)

**Comment by ccordoba12** [comment]
Ok, thanks for the confirmation @dalthviz! Then please take a look at this one.

My guess is that we're not pointing to the right path where MathJax is located when trying to load the library in the generated web page.
