### ISSUE TITLE
Spyder crashes when I lock my screen

### ISSUE THREAD

**Issue by combobulate** [spyder-ide/spyder#9788]
### What steps will reproduce the problem?

1. Launch Spyder
2. Use ctrl+alt+delete to lock screen
3. Unlock screen: Spyder is no longer open

I see an existing report on this issue that was not resolved.

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
This is not a problem with Spyder. Please see issue #8942 for a possible solution.

**Comment by combobulate** [comment]
This is a problem that impacts Spyder, regardless of if you feel it is Spyder's responsibility to handle the issue. For anyone else experiencing this issue without resolution, heads up that if Spyder is in the background when locking your computer, it usually seems to stay open.

**Comment by ccordoba12** [comment]
What I meant is that we can't solve it in our code. So it's not an issue of responsibility, it's a simply a technical issue because this problem is out of our hands (and it only happens on Windows, by the way).
