### ISSUE TITLE
"Custom Window Layouts" are unreliable, sizes and placements change

### ISSUE THREAD

**Issue by spyder-issues-migrator** [spyder-ide/spyder#979]
_From [vbgunzmo...@gmail.com](https://code.google.com/u/113355091090079718578/) on 2012-03-29T08:57:50Z_

What steps will reproduce the problem?

 1. Set layout 1, 2 or 3
2. CTRL+SHIFT+ALT+M OR Switch from one layout to another

What I expect to see is for all windows to go back and resize themselves the way they were when the layout was set. Breakage is really bad after CTRL+SHIFT+ALT+M, both windows and sizes change and all layouts break. Mostly just sizes for some windows change too much from one layout to another.

This behaviour is pretty consistent.

I am using Spyder 2.1.6 on Fedora 16.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=979_

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-03-31T04:27:32Z_

This seems to be OS-specific as I can't reproduce this behavior on Windows platforms.

Anyone else is able to reproduce this bug?

**Labels:** OpSys-Linux

**Comment by spyder-issues-migrator** [comment]
_From [vbgunz](https://code.google.com/u/vbgunz/) on 2012-04-09T10:23:44Z_

Hello Pierre,

I decided to download, PyQt for Python 2.7 x64, Python 2.7 x64 and "spyder-2.1.9_py27.exe" for Windows 7 Professional x64 yesterday, just to see if this problem showed up in Windows and it showed up on the very first try.

It doesn't appear to be just a Linux or 2.1.6 issue. Sorry I couldn't check sooner.

**Comment by spyder-issues-migrator** [comment]
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-04-10T00:35:53Z_

Well then could you please write a N-step procedure for anyone else to be able to reproduce this unexpected behavior?

Right now, if I follow these steps, I'm not seeing anything unexpected:
1. Reset window layout. 
2. Maximize editor
3. Un-maximize editor 
4. Store the layout as custom layout `#1`
5. Reorganize the layout (e. g. move the console on top of the editor)
6. Re-do step 1 to 3
7. Restore custom layout #1

**Comment by spyder-issues-migrator** [comment]
_From [ccordoba12](https://code.google.com/u/ccordoba12/) on 2015-01-02T18:12:31Z_

Closing because of lack of response.

**Status:** WontFix

**Comment by mat2py** [comment]
This behaviour can be reproduced simply by:

1. Set layout 1
2. Rearrange and resize the panes
3. Switch to/from layout 1 (to return back to the previously set layout 1)
4. Reverted layout is different to initial


Spyder 2.3.8
Python 2.7.12
Anaconda 4.1.1 (64-bit)
Ubuntu 15.10

**Comment by ccordoba12** [comment]
This has been rewritten in Spyder 3.0 and works more reliably now.
