### ISSUE TITLE
sets variable .remove()

### ISSUE THREAD

**Issue by enskrgz** [spyder-ide/spyder#9790]
### What steps will reproduce the problem?

i searching ctrl+I but studentsSet.remove()(sets variable) not finded 

## Versions

* Spyder version: 3.3.3 
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pyflakes >=0.6.0  :  2.1.1 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pygments >=2.0    :  2.3.1 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
rope >=0.9.4      :  0.12.0 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
IPython >=4.0     :  7.4.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

**Comment by ccordoba12** [comment]
I don't understand what you mean by this, sorry. Please provide a step by step description of the result you want to achieve in Spyder and why you're not getting that result.

**Comment by enskrgz** [comment]
I couldn't get help from .remove () command on sets in spyder

**Comment by ccordoba12** [comment]
Ok, I see. This a known failure and something we can do nothing about it. Not all methods offer documentation and in other cases it's not possible to get the required documentation by introspecting the requested object, sorry.

**Comment by enskrgz** [comment]
ok,  thanks
