### ISSUE TITLE
Again: Resource temporarily unavailable

### ISSUE THREAD

**Issue by Khris777** [spyder-ide/spyder#9810]
## Problem Description

I'm starting Spyder in a virtual anaconda-environment called "main", I'm doing this via the shortcut provided by Anaconda in the start menu. When Executing an entire script by pressing F5 and afterwards entering `reset` to reset the console I'm getting a `Again: Resource temporarily unavailable`-error. 

I'm getting the same error when using `getpass.getpass()` in a file and executing it via F5.

None of this happens when I execute the same code by marking the lines and pressing F9. If I only execute code via F9 I can use `reset` fine, it becomes only unusable after pressing F5.

### What steps reproduce the problem?

1. Start Spyder in an environment using the shortcut provided by Anaconda.
2a. Execute some file by pressing F5, then enter `reset`.
2b. Use `getpass.getpass()` in the file you're executing.

### What is the expected output? What do you see instead?

No error.

### Paste Traceback/Error Below (if applicable)

```
---------------------------------------------------------------------------
Again                                     Traceback (most recent call last)
C:/Users/My.Name/Documents/Python_Projects/SVN/Sources/dev/allgemein_sonstiges/check_ip.py in <module>
----> 1 get_ipython().run_line_magic('reset', '')

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2305                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2306             with self.builtin_trap:
-> 2307                 result = fn(*args, **kwargs)
   2308             return result
   2309 

<C:\Users\My.Name\AppData\Local\Continuum\anaconda3\Lib\site-packages\decorator.py:decorator-gen-86> in reset(self, parameter_s)

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    185     # but it's overkill for just that one bit of state.
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 
    189         if callable(arg):

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\IPython\core\magics\namespace.py in reset(self, parameter_s)
    535                 ans = self.shell.ask_yes_no(
    536                 "Once deleted, variables cannot be recovered. Proceed (y/[n])?",
--> 537                 default='n')
    538             except StdinNotImplementedError:
    539                 ans = True

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\IPython\core\interactiveshell.py in ask_yes_no(self, prompt, default, interrupt)
   3511         if self.quiet:
   3512             return True
-> 3513         return ask_yes_no(prompt,default,interrupt)
   3514 
   3515     def show_usage(self):

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\IPython\utils\io.py in ask_yes_no(prompt, default, interrupt)
    172     while ans not in answers.keys():
    173         try:
--> 174             ans = input(prompt+' ').lower()
    175             if not ans:  # response was an empty string
    176                 ans = default

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\ipykernel\kernelbase.py in raw_input(self, prompt)
    851             self._parent_ident,
    852             self._parent_header,
--> 853             password=False,
    854         )
    855 

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\ipykernel\kernelbase.py in _input_request(self, prompt, ident, parent, password)
    861         while True:
    862             try:
--> 863                 self.stdin_socket.recv_multipart(zmq.NOBLOCK)
    864             except zmq.ZMQError as e:
    865                 if e.errno == zmq.EAGAIN:

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\zmq\sugar\socket.py in recv_multipart(self, flags, copy, track)
    468             for any of the reasons :func:`~Socket.recv` might fail
    469         """
--> 470         parts = [self.recv(flags, copy=copy, track=track)]
    471         # have first part already, only loop while more to receive
    472         while self.getsockopt(zmq.RCVMORE):

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\zmq\backend\cython\checkrc.pxd in zmq.backend.cython.checkrc._check_rc()

Again: Resource temporarily unavailable
```

```
---------------------------------------------------------------------------
Again                                     Traceback (most recent call last)
C:/Users/My.Name/Documents/Python_Projects/SVN/Sources/dev/allgemein_sonstiges/check_ip.py in <module>
----> 1 getpass.getpass()

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\ipykernel\kernelbase.py in getpass(self, prompt, stream)
    834             self._parent_ident,
    835             self._parent_header,
--> 836             password=True,
    837         )
    838 

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\ipykernel\kernelbase.py in _input_request(self, prompt, ident, parent, password)
    861         while True:
    862             try:
--> 863                 self.stdin_socket.recv_multipart(zmq.NOBLOCK)
    864             except zmq.ZMQError as e:
    865                 if e.errno == zmq.EAGAIN:

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\zmq\sugar\socket.py in recv_multipart(self, flags, copy, track)
    468             for any of the reasons :func:`~Socket.recv` might fail
    469         """
--> 470         parts = [self.recv(flags, copy=copy, track=track)]
    471         # have first part already, only loop while more to receive
    472         while self.getsockopt(zmq.RCVMORE):

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket.Socket.recv()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()

zmq/backend/cython/socket.pyx in zmq.backend.cython.socket._recv_copy()

~\AppData\Local\Continuum\anaconda3\Lib\site-packages\zmq\backend\cython\checkrc.pxd in zmq.backend.cython.checkrc._check_rc()

Again: Resource temporarily unavailable
```

## Versions

* Spyder version: 3.3.4
* Python version: 3,7,3 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 64-bit

### Dependencies

```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.16.2 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)
```

**Comment by ccordoba12** [comment]
@dalthviz, are you able to reproduce this on Windows?

**Comment by dalthviz** [comment]
@ccordoba12 I was not able to reproduce this. In the case of the `reset` I see the prompt to confirm the reset of the namespace and in the case of `getpass` a message that the console will show the password:

![image](https://user-images.githubusercontent.com/16781833/61017744-ee7b8500-a359-11e9-8b7e-880988bdd18b.png)

Are you experiencing this while running anything or just a certain script @Khris777? Any information to replicate the issue is greatly appreciated.

**Comment by Khris777** [comment]
I'll try to give as much background information as possible.

I just started a new Spyder instance and the only thing I did was execute a new script only saying
```
import getpass
getpass.getpass()
```
in a fresh console, and the error appeared.

Then in another new console executed a script that only says
```
import io
import os
```
and entered `reset`, the error appeared as well.

I haven't found any other instances that cause the error, e.g. the `%timeit` magic command works fine.

I have had some trouble with running Spyder in a virtual environment before since at the beginning I didn't know how all of that worked, so before my current `main` environment I had run it in different environments and experienced issues like [this one](https://github.com/ContinuumIO/anaconda-issues/issues/10895). During the time I didn't get the environments right I had set Spyder to use a specific Python console in the respective environment but since then I have switched back to default in the settings.

When you start a new console in Spyder there are a few lines at the top telling me about Python version and such. After I had set Spyder to use a certain interpreter this header had changed, it has become shorter than the default one, looking like this:
```
Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 7.4.0 -- An enhanced Interactive Python.
```
However when I switched back to default the message stayed like this, it didn't revert to the longer message I used to get as default. I think that longer message also mentioned Qt. I don't know how to get the default back, but apart from that error message both seem to work the same. This might be a hint to the issue as the first time the error message appeared was during the time I got my environments wrong.

For a while I started Spyder using this batch command:
```
@ECHO OFF
CALL ACTIVATE main
spyder.exe
EXIT
```
I experienced the same errors then. At some point I tested the Anaconda shortcuts again and this time it worked fine so I'm using that again, the errors are still there though.

I also ran into [this conda issue that might be related](https://github.com/conda/conda/issues/8813) at some point which was apparently my own fault, but still really confusing.

That's all I guess, I'm almost certain it has to do with me handling environments wrong and some setting didn't get set or reset properly.

**Comment by ccordoba12** [comment]
@dalthviz, please try running

```python
import getpass
getpass.getpass()
```

from the editor instead of in the console to see what happens.

**Comment by dalthviz** [comment]
@ccordoba12 running `getpass` from the `Editor` shows the following:

![image](https://user-images.githubusercontent.com/16781833/61093114-96eb2100-a40e-11e9-83e1-90afc58b8bb0.png)

@Khris777 what happens when you run from the `Anaconda Prompt`? Also, could you try to create another env (`conda create -n main2 spyder=3.3.4` for example) and test if you experience the same behavior as with the `main` env? Thanks

**Comment by Khris777** [comment]
@dalthviz 

Running Spyder from Anaconda Prompt after activating the `main`-environment leads to the same error.

I created a new environment with the command you provided and launched spyder there, same error.

The only case when I'm not getting the error is when launching Spyder in the base (root) environment.

**Comment by ccordoba12** [comment]
@Khris777, I'm sorry but this is not a problem with Spyder (as can be seen from your traceback, there's not a single call to Spyder code there). Besides. we tried to see if your error is reproducible in our side and we were unable to do that. My last piece of advice is to deactivate your firewall/antivirus because this could be caused by any of them.

If that doesn't help, please report your error here:

https://github.com/ipython/ipykernel/

**Comment by Khris777** [comment]
I see. Thanks for the advice. 

Do you have any hint why it only happens when the entire script is executed while executing parts of the code via F9 works fine?

**Comment by ccordoba12** [comment]
I have no idea, sorry.

**Comment by Khris777** [comment]
In the end I scrapped my entire bugged Anaconda installation and did a clean reinstall using Miniconda.

The problem is gone now.
