### ISSUE TITLE
Feature Request: Alternative to tab view of documents

### ISSUE THREAD

**Issue by Murmele** [spyder-ide/spyder#9822]
In QtCreator they use a different approach for handling multiple open documents. They don't use tabs, but a list with all open documents. In the lower right part you see the open documents and can easily switch between them. You are also able to search for documents in the document tree and open it. I like this approach, maybe you like it too.
![Spyder](https://user-images.githubusercontent.com/10099533/61140094-19d1b180-a4cb-11e9-9a9d-de6376e3556d.png)

**Comment by ccordoba12** [comment]
We already have a file switcher (which by default is showed after pressing Ctrl+P) that has the list of open files in the Editor and allows you to do a fuzzy search on that list.

We don't have plans to implement something as your proposal in the future, sorry.
